proxygen: proxygen/wangle/wangle/example/accept_steering/accept_steering_server.cpp File Reference
accept_steering_server.cpp File Reference
#include <folly/portability/GFlags.h>
#include <folly/init/Init.h>
#include <wangle/bootstrap/AcceptRoutingHandler.h>
#include <wangle/bootstrap/RoutingDataHandler.h>
#include <wangle/bootstrap/ServerBootstrap.h>
#include <wangle/channel/AsyncSocketHandler.h>
Classes
class NaiveRoutingDataHandler
class NaiveRoutingDataHandlerFactory
class ThreadPrintingHandler
class ServerPipelineFactory
Functions
DEFINE_int32 (port, 23,"test server port")
int main (int argc, char **argv)
Function Documentation
DEFINE_int32 (port , 23 , "test server port")
int main (int argc, char ** argv)
Definition at line 104 of file accept_steering_server.cpp.
References wangle::ServerBootstrap< Pipeline >::bind(), folly::init(), and wangle::ServerBootstrap< Pipeline >::pipeline().
{
   folly::Init init(&argc, &argv);
   auto routingHandlerFactory =
       std::make_shared<NaiveRoutingDataHandlerFactory>();
   auto childPipelineFactory = std::make_shared<ServerPipelineFactory>();
   ServerBootstrap<DefaultPipeline> server;
   server.pipeline(
       std::make_shared<AcceptRoutingPipelineFactory<DefaultPipeline, char>>(
           &server, routingHandlerFactory, childPipelineFactory));
   server.bind(FLAGS_port);
   server.waitForStop();
   return 0;
 }