proxygen: proxygen/folly/folly/container/test/AccessTest.cpp File Reference
AccessTest.cpp File Reference
#include <folly/container/Access.h>
#include <array>
#include <initializer_list>
#include <vector>
#include <folly/portability/GTest.h>
Classes
class AccessTest
Functions
TEST_F (AccessTest, size_vector)
TEST_F (AccessTest, size_array)
TEST_F (AccessTest, size_carray)
TEST_F (AccessTest, size_initializer_list)
TEST_F (AccessTest, empty_vector)
TEST_F (AccessTest, empty_array)
TEST_F (AccessTest, empty_carray)
TEST_F (AccessTest, empty_initializer_list)
TEST_F (AccessTest, data_vector)
TEST_F (AccessTest, data_array)
TEST_F (AccessTest, data_carray)
TEST_F (AccessTest, data_initializer_list)
Function Documentation
TEST_F (AccessTest , size_vector)
Definition at line 27 of file AccessTest.cpp.
References EXPECT_EQ, and folly::size().
{
   EXPECT_EQ(3, folly::size(std::vector<int>{1, 2, 3}));
 }
TEST_F (AccessTest , size_array)
Definition at line 31 of file AccessTest.cpp.
References a, EXPECT_EQ, and folly::size().
{
   constexpr auto const a = std::array<int, 3>{{1, 2, 3}};
   constexpr auto const size = folly::size(a);
   EXPECT_EQ(3, size);
 }
TEST_F (AccessTest , size_carray)
Definition at line 37 of file AccessTest.cpp.
References a, EXPECT_EQ, and folly::size().
{
   constexpr int const a[3] = {1, 2, 3};
   constexpr auto const size = folly::size(a);
   EXPECT_EQ(3, size);
 }
TEST_F (AccessTest , size_initializer_list)
Definition at line 43 of file AccessTest.cpp.
References EXPECT_EQ, and folly::size().
{
   EXPECT_EQ(3, folly::size({1, 2, 3}));
   EXPECT_EQ(3, folly::size(std::initializer_list<int>{1, 2, 3}));
 }
TEST_F (AccessTest , empty_vector)
Definition at line 48 of file AccessTest.cpp.
References folly::empty(), EXPECT_FALSE, and EXPECT_TRUE.
{
   EXPECT_FALSE(folly::empty(std::vector<int>{1, 2, 3}));
   EXPECT_TRUE(folly::empty(std::vector<int>{}));
 }
TEST_F (AccessTest , empty_array)
Definition at line 53 of file AccessTest.cpp.
References a, folly::empty(), EXPECT_FALSE, and EXPECT_TRUE.
{
   {
     constexpr auto const a = std::array<int, 3>{{1, 2, 3}};
     constexpr auto const empty = folly::empty(a);
     EXPECT_FALSE(empty);
   }
   {
     constexpr auto const a = std::array<int, 0>{{}};
     constexpr auto const empty = folly::empty(a);
     EXPECT_TRUE(empty);
   }
 }
TEST_F (AccessTest , empty_carray)
Definition at line 66 of file AccessTest.cpp.
References a, folly::empty(), and EXPECT_FALSE.
{
   constexpr int const a[3] = {1, 2, 3};
   constexpr auto const empty = folly::empty(a);
   EXPECT_FALSE(empty);
   //  zero-length arrays are not allowed in the language
 }
TEST_F (AccessTest , empty_initializer_list)
Definition at line 73 of file AccessTest.cpp.
References folly::empty(), EXPECT_FALSE, and EXPECT_TRUE.
{
   EXPECT_FALSE(folly::empty({1, 2, 3}));
   EXPECT_FALSE(folly::empty(std::initializer_list<int>{1, 2, 3}));
   EXPECT_TRUE(folly::empty(std::initializer_list<int>{}));
 }
TEST_F (AccessTest , data_vector)
Definition at line 79 of file AccessTest.cpp.
References folly::data(), and EXPECT_EQ.
{
   EXPECT_EQ(1, *folly::data(std::vector<int>{1, 2, 3}));
   auto v = std::vector<int>{1, 2, 3};
   *folly::data(v) = 4;
   EXPECT_EQ(4, v[0]);
 }
TEST_F (AccessTest , data_array)
Definition at line 86 of file AccessTest.cpp.
References a, data, folly::data(), and EXPECT_EQ.
{
   constexpr auto const a = std::array<int, 3>{{1, 2, 3}};
   auto const data = folly::data(a); // not constexpr until C++17
   EXPECT_EQ(1, *data);
 }
TEST_F (AccessTest , data_carray)
Definition at line 92 of file AccessTest.cpp.
References a, data, folly::data(), and EXPECT_EQ.
{
   constexpr int const a[3] = {1, 2, 3};
   auto const data = folly::data(a); // not constexpr until C++17
   EXPECT_EQ(1, *data);
 }
TEST_F (AccessTest , data_initializer_list)
Definition at line 98 of file AccessTest.cpp.
References folly::data(), and EXPECT_EQ.
{
   EXPECT_EQ(1, *folly::data({1, 2, 3}));
   EXPECT_EQ(1, *folly::data(std::initializer_list<int>{1, 2, 3}));
 }