proxygen: proxygen/folly/folly/memory/test/ArenaTest.cpp File Reference
ArenaTest.cpp File Reference
#include <folly/memory/Arena.h>
#include <folly/Memory.h>
#include <folly/portability/GTest.h>
#include <set>
#include <vector>
#include <glog/logging.h>
Functions
TEST (Arena, SizeSanity)
TEST (Arena, BytesUsedSanity)
TEST (Arena, Vector)
TEST (Arena, SizeLimit)
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 160 of file ArenaTest.cpp.
References testing::InitGoogleTest(), and RUN_ALL_TESTS().
{
   testing::InitGoogleTest(&argc, argv);
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   auto ret = RUN_ALL_TESTS();
   return ret;
 }
TEST (Arena , SizeSanity)
Definition at line 30 of file ArenaTest.cpp.
References folly::Arena< Alloc >::allocate(), folly::Arena< Alloc >::deallocate(), EXPECT_EQ, EXPECT_TRUE, folly::goodMallocSize(), i, folly::Arena< SysAllocator< void > >::kBlockOverhead, ptr, and folly::Arena< Alloc >::totalSize().
{
   std::set<size_t*> allocatedItems;
   static const size_t requestedBlockSize = 64;
   SysArena arena(requestedBlockSize);
   size_t minimum_size = sizeof(SysArena), maximum_size = minimum_size;
   EXPECT_EQ(arena.totalSize(), minimum_size);
   // Insert a single small element to get a new block
   size_t* ptr = static_cast<size_t*>(arena.allocate(sizeof(long)));
   allocatedItems.insert(ptr);
   minimum_size += requestedBlockSize;
   maximum_size += goodMallocSize(requestedBlockSize + SysArena::kBlockOverhead);
   EXPECT_TRUE(arena.totalSize() >= minimum_size);
   EXPECT_TRUE(arena.totalSize() <= maximum_size);
   VLOG(4) << minimum_size << " < " << arena.totalSize() << " < "
           << maximum_size;
   // Insert a larger element, size should be the same
   ptr = static_cast<size_t*>(arena.allocate(requestedBlockSize / 2));
   allocatedItems.insert(ptr);
   EXPECT_TRUE(arena.totalSize() >= minimum_size);
   EXPECT_TRUE(arena.totalSize() <= maximum_size);
   VLOG(4) << minimum_size << " < " << arena.totalSize() << " < "
           << maximum_size;
   // Insert 10 full block sizes to get 10 new blocks
   for (int i = 0; i < 10; i++) {
     ptr = static_cast<size_t*>(arena.allocate(requestedBlockSize));
     allocatedItems.insert(ptr);
   }
   minimum_size += 10 * requestedBlockSize;
   maximum_size +=
       10 * goodMallocSize(requestedBlockSize + SysArena::kBlockOverhead);
   EXPECT_TRUE(arena.totalSize() >= minimum_size);
   EXPECT_TRUE(arena.totalSize() <= maximum_size);
   VLOG(4) << minimum_size << " < " << arena.totalSize() << " < "
           << maximum_size;
   // Insert something huge
   ptr = static_cast<size_t*>(arena.allocate(10 * requestedBlockSize));
   allocatedItems.insert(ptr);
   minimum_size += 10 * requestedBlockSize;
   maximum_size +=
       goodMallocSize(10 * requestedBlockSize + SysArena::kBlockOverhead);
   EXPECT_TRUE(arena.totalSize() >= minimum_size);
   EXPECT_TRUE(arena.totalSize() <= maximum_size);
   VLOG(4) << minimum_size << " < " << arena.totalSize() << " < "
           << maximum_size;
   // Nuke 'em all
   for (const auto& item : allocatedItems) {
     arena.deallocate(item, 0 /* unused */);
   }
   // The total size should be the same
   EXPECT_TRUE(arena.totalSize() >= minimum_size);
   EXPECT_TRUE(arena.totalSize() <= maximum_size);
   VLOG(4) << minimum_size << " < " << arena.totalSize() << " < "
           << maximum_size;
 }
TEST (Arena , BytesUsedSanity)
Definition at line 91 of file ArenaTest.cpp.
References folly::Arena< Alloc >::allocate(), folly::Arena< Alloc >::bytesUsed(), EXPECT_EQ, EXPECT_TRUE, folly::goodMallocSize(), and folly::Arena< Alloc >::totalSize().
{
   static const size_t smallChunkSize = 1024;
   static const size_t blockSize = goodMallocSize(16 * smallChunkSize);
   const size_t bigChunkSize = blockSize - 4 * smallChunkSize;
   size_t bytesUsed = 0;
   SysArena arena(blockSize);
   EXPECT_EQ(arena.bytesUsed(), bytesUsed);
   // Insert 2 small chunks
   arena.allocate(smallChunkSize);
   arena.allocate(smallChunkSize);
   bytesUsed += 2 * smallChunkSize;
   EXPECT_EQ(arena.bytesUsed(), bytesUsed);
   EXPECT_TRUE(arena.totalSize() >= blockSize);
   EXPECT_TRUE(arena.totalSize() <= 2 * blockSize);
   // Insert big chunk, should still fit in one block
   arena.allocate(bigChunkSize);
   bytesUsed += bigChunkSize;
   EXPECT_EQ(arena.bytesUsed(), bytesUsed);
   EXPECT_TRUE(arena.totalSize() >= blockSize);
   EXPECT_TRUE(arena.totalSize() <= 2 * blockSize);
   // Insert big chunk once more, should trigger new block allocation
   arena.allocate(bigChunkSize);
   bytesUsed += bigChunkSize;
   EXPECT_EQ(arena.bytesUsed(), bytesUsed);
   EXPECT_TRUE(arena.totalSize() >= 2 * blockSize);
   EXPECT_TRUE(arena.totalSize() <= 3 * blockSize);
   // Test that bytesUsed() accounts for alignment
   static const size_t tinyChunkSize = 7;
   arena.allocate(tinyChunkSize);
   EXPECT_TRUE(arena.bytesUsed() >= bytesUsed + tinyChunkSize);
   size_t delta = arena.bytesUsed() - bytesUsed;
   EXPECT_EQ(delta & (delta - 1), 0);
 }
TEST (Arena , Vector)
Definition at line 131 of file ArenaTest.cpp.
References EXPECT_EQ, i, and folly::Arena< Alloc >::totalSize().
                     {
   static const size_t requestedBlockSize = 64;
   SysArena arena(requestedBlockSize);
   EXPECT_EQ(arena.totalSize(), sizeof(SysArena));
   std::vector<size_t, SysArenaAllocator<size_t>> vec{
       {}, SysArenaAllocator<size_t>(arena)};
   for (size_t i = 0; i < 1000; i++) {
     vec.push_back(i);
   }
   for (size_t i = 0; i < 1000; i++) {
     EXPECT_EQ(i, vec[i]);
   }
 }
TEST (Arena , SizeLimit)
Definition at line 149 of file ArenaTest.cpp.
References a, folly::Arena< Alloc >::allocate(), EXPECT_THROW, and EXPECT_TRUE.
{
   static const size_t requestedBlockSize = sizeof(size_t);
   static const size_t maxSize = 10 * requestedBlockSize;
   SysArena arena(requestedBlockSize, maxSize);
   void* a = arena.allocate(sizeof(size_t));
   EXPECT_TRUE(a != nullptr);
   EXPECT_THROW(arena.allocate(maxSize + 1), std::bad_alloc);
 }