proxygen: proxygen/folly/folly/container/test/ArrayTest.cpp File Reference
ArrayTest.cpp File Reference
#include <folly/container/Array.h>
#include <folly/portability/GTest.h>
#include <string>
Functions
TEST (make_array, base_case)
TEST (make_array, deduce_size_primitive)
TEST (make_array, deduce_size_class)
TEST (make_array, deduce_everything)
TEST (make_array, fixed_common_type)
TEST (make_array, deduced_common_type)
TEST (make_array_with, example)
Function Documentation
TEST (make_array , base_case)
Definition at line 23 of file ArrayTest.cpp.
References EXPECT_EQ, and value.
{
   auto arr = make_array<int>();
   static_assert(
       is_same<typename decltype(arr)::value_type, int>::value,
       "Wrong array type");
   EXPECT_EQ(arr.size(), 0);
 }
TEST (make_array , deduce_size_primitive)
Definition at line 31 of file ArrayTest.cpp.
References EXPECT_EQ, and value.
{
   auto arr = make_array<int>(1, 2, 3, 4, 5);
   static_assert(
       is_same<typename decltype(arr)::value_type, int>::value,
       "Wrong array type");
   EXPECT_EQ(arr.size(), 5);
 }
TEST (make_array , deduce_size_class)
Definition at line 39 of file ArrayTest.cpp.
References EXPECT_EQ, string, and value.
{
   auto arr = make_array<string>(string{"foo"}, string{"bar"});
   static_assert(
       is_same<typename decltype(arr)::value_type, std::string>::value,
       "Wrong array type");
   EXPECT_EQ(arr.size(), 2);
   EXPECT_EQ(arr[1], "bar");
 }
TEST (make_array , deduce_everything)
Definition at line 48 of file ArrayTest.cpp.
References EXPECT_EQ, folly::make_array(), string, and value.
{
   auto arr = make_array(string{"foo"}, string{"bar"});
   static_assert(
       is_same<typename decltype(arr)::value_type, std::string>::value,
       "Wrong array type");
   EXPECT_EQ(arr.size(), 2);
   EXPECT_EQ(arr[1], "bar");
 }
TEST (make_array , fixed_common_type)
Definition at line 57 of file ArrayTest.cpp.
References EXPECT_EQ, and value.
{
   auto arr = make_array<double>(1.0, 2.5f, 3, 4, 5);
   static_assert(
       is_same<typename decltype(arr)::value_type, double>::value,
       "Wrong array type");
   EXPECT_EQ(arr.size(), 5);
 }
TEST (make_array , deduced_common_type)
Definition at line 65 of file ArrayTest.cpp.
References EXPECT_EQ, f, folly::make_array(), and value.
{
   auto arr = make_array(1.0, 2.5f, 3, 4, 5);
   static_assert(
       is_same<typename decltype(arr)::value_type, double>::value,
       "Wrong array type");
   EXPECT_EQ(arr.size(), 5);
 }
TEST (make_array_with , example)
Definition at line 73 of file ArrayTest.cpp.
References EXPECT_EQ, folly::array_detail::make_array_with(), and folly::make_array_with().
{
   struct make_item {
     constexpr int operator()(size_t index) const {
       return index + 4;
     }
   };
   using folly::make_array_with;
   using folly::array_detail::make_array_with; // should not collide
   constexpr auto actual = make_array_with<3>(make_item{});
   constexpr auto expected = make_array<int>(4, 5, 6);
   EXPECT_EQ(expected, actual);
 }