proxygen: proxygen/folly/folly/io/async/test/AsyncUDPSocketGSOTest.cpp File Reference
AsyncUDPSocketGSOTest.cpp File Reference
#include <numeric>
#include <thread>
#include <folly/Conv.h>
#include <folly/SocketAddress.h>
#include <folly/io/IOBuf.h>
#include <folly/io/async/AsyncTimeout.h>
#include <folly/io/async/AsyncUDPServerSocket.h>
#include <folly/io/async/AsyncUDPSocket.h>
#include <folly/io/async/EventBase.h>
#include <folly/portability/GMock.h>
#include <folly/portability/GTest.h>
Classes
class TestData
class UDPAcceptor
class UDPServer
class UDPClient
class AsyncSocketGSOIntegrationTest
class GSOBuf
class GSOSendTest
Functions
TEST_F (AsyncSocketGSOIntegrationTest, PingPongGlobalGSO)
TEST_F (AsyncSocketGSOIntegrationTest, PingPongRequestGSO)
TEST (AsyncSocketGSOTest, send)
Variables
constexpr auto kGSO1 = 100
constexpr auto kGSO2 = 200
constexpr auto kGSO = kGSO1 + kGSO2
Function Documentation
TEST (AsyncSocketGSOTest , send)
Definition at line 454 of file AsyncUDPSocketGSOTest.cpp.
References folly::AsyncUDPSocket::address(), folly::AsyncUDPSocket::bind(), folly::AsyncUDPSocket::getGSO(), kGSO, kGSO1, kGSO2, and test().
{
   EventBase evb;
   folly::AsyncUDPSocket client(&evb);
   client.bind(folly::SocketAddress("127.0.0.1", 0));
   if (client.getGSO() < 0) {
     LOG(INFO) << "GSO not supported";
     // GSO not supported
     return;
   }
   folly::AsyncUDPSocket server(&evb);
   server.bind(folly::SocketAddress("127.0.0.1", 0));
   // send less than GSO in a single IOBuf
   {
     GSOSendTest test(client, server.address(), kGSO, kGSO - 1);
     CHECK_LT(test.get(), 0);
   }
   // send less than GSO in multiple IOBufs
   {
     GSOSendTest test(client, server.address(), kGSO, kGSO1 - 1, kGSO2);
     CHECK_LT(test.get(), 0);
   }
   // send  GSO in a single IOBuf
   {
     GSOSendTest test(client, server.address(), kGSO, kGSO);
     CHECK_LT(test.get(), 0);
   }
   // send GSO in multiple IOBuf
   {
     GSOSendTest test(client, server.address(), kGSO, kGSO1, kGSO2);
     CHECK_LT(test.get(), 0);
   }
   // send more than GSO in a single IOBuf
   {
     GSOSendTest test(client, server.address(), kGSO, kGSO + 1);
     CHECK_EQ(test.get(), kGSO + 1);
   }
   // send more than GSO in a multiple IOBufs
   {
     GSOSendTest test(client, server.address(), kGSO, kGSO1 + 1, kGSO2 + 1);
     CHECK_EQ(test.get(), kGSO + 2);
   }
 }
TEST_F (AsyncSocketGSOIntegrationTest , PingPongGlobalGSO)
Definition at line 373 of file AsyncUDPSocketGSOTest.cpp.
References ASSERT_TRUE, and folly::none.
{
   int gso = 1000;
   int in[] = {100, 1200, 3000, 200, 100, 300};
   int expected[] = {1000, 1000, 1000, 1000, 900};
   TestData testData(
       gso,
       true /*useSocketGSO*/,
       in,
       sizeof(in) / sizeof(in[0]),
       expected,
       sizeof(expected) / sizeof(expected[0]));
   ASSERT_TRUE(testData.checkIn());
   startServer();
   auto pingClient = performPingPongTest(testData, folly::none);
   ASSERT_TRUE(testData.checkOut());
 }
TEST_F (AsyncSocketGSOIntegrationTest , PingPongRequestGSO)
Definition at line 390 of file AsyncUDPSocketGSOTest.cpp.
References ASSERT_TRUE, and folly::none.
{
   int gso = 421;
   int in[] = {100, 1200, 3000, 200, 100, 300};
   int expected[] = {421, 421, 421, 421, 421, 421, 421, 421, 421, 421, 421, 269};
   TestData testData(
       gso,
       false /*useSocketGSO*/,
       in,
       sizeof(in) / sizeof(in[0]),
       expected,
       sizeof(expected) / sizeof(expected[0]));
   ASSERT_TRUE(testData.checkIn());
   startServer();
   auto pingClient = performPingPongTest(testData, folly::none);
   ASSERT_TRUE(testData.checkOut());
 }
Variable Documentation
constexpr auto kGSO = kGSO1 + kGSO2
Definition at line 410 of file AsyncUDPSocketGSOTest.cpp.
Referenced by TEST().
constexpr auto kGSO1 = 100
Definition at line 408 of file AsyncUDPSocketGSOTest.cpp.
Referenced by TEST().
constexpr auto kGSO2 = 200
Definition at line 409 of file AsyncUDPSocketGSOTest.cpp.
Referenced by TEST().