proxygen: proxygen/folly/folly/io/async/test/AsyncSignalHandlerTest.cpp File Reference
AsyncSignalHandlerTest.cpp File Reference
#include <folly/io/async/AsyncSignalHandler.h>
#include <folly/io/async/EventBase.h>
#include <folly/portability/GTest.h>
Functions
TEST (AsyncSignalHandler, basic)
TEST (AsyncSignalHandler, attachEventBase)
Function Documentation
TEST (AsyncSignalHandler , basic)
Definition at line 36 of file AsyncSignalHandlerTest.cpp.
References EXPECT_FALSE, EXPECT_TRUE, handler(), and folly::EventBase::loopOnce().
{
   EventBase evb;
   TestSignalHandler handler{&evb};
   handler.registerSignalHandler(SIGUSR1);
   kill(getpid(), SIGUSR1);
   EXPECT_FALSE(handler.called);
   evb.loopOnce(EVLOOP_NONBLOCK);
   EXPECT_TRUE(handler.called);
 }
TEST (AsyncSignalHandler , attachEventBase)
Definition at line 48 of file AsyncSignalHandlerTest.cpp.
References EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, and handler().
{
   TestSignalHandler handler{nullptr};
   EXPECT_FALSE(handler.getEventBase());
   EventBase evb;
   handler.attachEventBase(&evb);
   EXPECT_EQ(&evb, handler.getEventBase());
   handler.registerSignalHandler(SIGUSR1);
   kill(getpid(), SIGUSR1);
   EXPECT_FALSE(handler.called);
   evb.loopOnce(EVLOOP_NONBLOCK);
   EXPECT_TRUE(handler.called);
   handler.unregisterSignalHandler(SIGUSR1);
   handler.detachEventBase();
   EXPECT_FALSE(handler.getEventBase());
 }