proxygen: proxygen/folly/folly/io/async/test/AsyncSSLSocketTest2.cpp File Reference
AsyncSSLSocketTest2.cpp File Reference
#include <folly/io/async/test/AsyncSSLSocketTest.h>
#include <folly/futures/Promise.h>
#include <folly/init/Init.h>
#include <folly/io/async/AsyncSSLSocket.h>
#include <folly/io/async/EventBase.h>
#include <folly/io/async/SSLContext.h>
#include <folly/io/async/ScopedEventBaseThread.h>
#include <folly/portability/GTest.h>
#include <folly/portability/PThread.h>
#include <folly/ssl/Init.h>
Classes
struct folly::EvbAndContext
class folly::AttachDetachClient
class folly::ConnectClient
class folly::NoopReadCallback
Namespaces
folly
—— Concurrent Priority Queue Implementation ——
Functions
folly::TEST (AsyncSSLSocketTest2, AttachDetachSSLContext)
folly::TEST (AsyncSSLSocketTest2, TestTLS12DefaultClient)
folly::TEST (AsyncSSLSocketTest2, TestTLS12BadClient)
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 283 of file AsyncSSLSocketTest2.cpp.
References folly::init(), folly::ssl::init(), testing::InitGoogleTest(), folly::portability::ssl::OPENSSL_cleanup(), and RUN_ALL_TESTS().
{
   folly::ssl::init();
 #ifdef SIGPIPE
   signal(SIGPIPE, SIG_IGN);
 #endif
   testing::InitGoogleTest(&argc, argv);
   folly::init(&argc, &argv);
   return RUN_ALL_TESTS();
   OPENSSL_cleanup();
 }