proxygen: proxygen/folly/folly/detail/AtFork.cpp File Reference
AtFork.cpp File Reference
#include <folly/detail/AtFork.h>
#include <list>
#include <mutex>
#include <folly/lang/Exception.h>
#include <folly/portability/PThread.h>
Namespaces
folly
—— Concurrent Priority Queue Implementation ——
folly::detail
Variable Documentation
folly::Function<void()> child
Definition at line 35 of file AtFork.cpp.
Referenced by proxygen::HTTP2PriorityQueue::Node::addChildren(), proxygen::HTTP2PriorityQueue::Node::dropPriorityNodes(), proxygen::HTTP2PriorityQueue::Node::flattenSubtree(), proxygen::HTTP2PriorityQueue::Node::flattenSubtreeDFS(), proxygen::HTTP2PriorityQueue::Node::iterate(), folly::detail::AtFork::registerHandler(), proxygen::HTTP2PriorityQueue::Node::removeFromTree(), folly::RequestContext::setShallowCopyContext(), TEST(), folly::test::DeterministicSchedule::thread(), folly::LogCategory::updateEffectiveLevel(), proxygen::HTTP2PriorityQueue::Node::updateEnqueuedWeight(), and proxygen::HTTP2PriorityQueue::Node::visitBFS().
void* object
Definition at line 32 of file AtFork.cpp.
Referenced by upload.ClientLoginError::__init__(), upload.HttpRpcServer::_GetOpener(), folly::exception_wrapper::get_exception(), cpp.ast.TypeConverter::GetTemplateIndices(), cpp.ast.Type::IsExportable(), folly::dynamic::merge_diff(), folly::SingletonThreadLocal< T, Tag, Make, TLTag >::Wrapper::operator T &(), folly::printBenchmarkResultsAsJson(), folly::detail::AtFork::registerHandler(), TEST(), and TEST_F().
folly::Function<void()> parent
Definition at line 34 of file AtFork.cpp.
Referenced by proxygen::SPDYCodec::addPriorityNodes(), proxygen::HTTP2Codec::addPriorityNodes(), proxygen::HTTP2PriorityQueue::addTransaction(), folly::test::DeterministicSchedule::beforeThreadExit(), folly::RelaxedConcurrentPriorityQueue< T, MayBlock, SupportsSize, PopBatch, ListTargetSize, Mutex, Atom >::binarySearchPosition(), folly::LoggerDB::createCategoryLocked(), testing::internal::FilePath::CreateDirectoriesRecursively(), folly::SerialExecutor::getNumPriorities(), folly::LoggerDB::getOrCreateCategoryLocked(), folly::threadlocal_detail::ThreadEntryNode::getThreadEntry(), testing::internal::IsPathSeparator(), folly::LockedPtrBase< SynchronizedType, SynchronizedType::MutexType, LockPolicy >::LockedPtrBase(), folly::LockedPtrBase< SynchronizedType, std::mutex, LockPolicy >::LockedPtrBase(), folly::LogCategory::LogCategory(), testing::internal::OsStackTraceGetter::OsStackTraceGetter(), proxygen::PassThroughHTTPCodecFilter::PassThroughHTTPCodecFilter(), proxygen::HTTP2PriorityQueue::Node::propagatePendingEgressClear(), proxygen::HTTP2PriorityQueue::Node::propagatePendingEgressSignal(), folly::detail::AtFork::registerHandler(), folly::RelaxedConcurrentPriorityQueue< T, MayBlock, SupportsSize, PopBatch, ListTargetSize, Mutex, Atom >::regularInsert(), proxygen::TraceEvent::setParentID(), folly::RequestContext::setShallowCopyContext(), proxygen::HTTPCodec::PriorityQueue::~PriorityQueue(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
folly::Function<bool()> prepare
Definition at line 33 of file AtFork.cpp.
Referenced by folly::detail::AtFork::registerHandler().
std::list<AtForkTask> tasks
Definition at line 81 of file AtFork.cpp.
Referenced by testFiberLocal().
std::mutex tasksLock
Definition at line 80 of file AtFork.cpp.
Referenced by folly::detail::AtFork::registerHandler().