proxygen: proxygen/folly/folly/test/AtForkTest.cpp File Reference
AtForkTest.cpp File Reference
#include <folly/detail/AtFork.h>
#include <folly/portability/GTest.h>
#include <glog/logging.h>
#include <atomic>
#include <mutex>
#include <thread>
Functions
TEST (ThreadLocal, AtFork)
TEST (ThreadLocal, AtForkOrdering)
Function Documentation
TEST (ThreadLocal , AtFork)
Definition at line 25 of file AtForkTest.cpp.
References EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testing::gmock_matchers_test::foo, folly::detail::AtFork::registerHandler(), folly::detail::AtFork::unregisterHandler(), and folly::detail::distributed_mutex::wait().
{
   int foo;
   bool forked = false;
   folly::detail::AtFork::registerHandler(
       &foo,
       [&] {
         forked = true;
         return true;
       },
       [] {},
       [] {});
   auto pid = fork();
   if (pid) {
     int status;
     auto pid2 = wait(&status);
     EXPECT_EQ(status, 0);
     EXPECT_EQ(pid, pid2);
   } else {
     exit(0);
   }
   EXPECT_TRUE(forked);
   forked = false;
   folly::detail::AtFork::unregisterHandler(&foo);
   pid = fork();
   if (pid) {
     int status;
     auto pid2 = wait(&status);
     EXPECT_EQ(status, 0);
     EXPECT_EQ(pid, pid2);
   } else {
     exit(0);
   }
   EXPECT_FALSE(forked);
 }
TEST (ThreadLocal , AtForkOrdering)
Definition at line 60 of file AtForkTest.cpp.
References a, b, EXPECT_EQ, testing::gmock_matchers_test::foo, foo2(), g(), mutex, folly::detail::AtFork::registerHandler(), and folly::detail::distributed_mutex::wait().
{
   std::atomic<bool> done{false};
   std::atomic<bool> started{false};
   std::mutex a;
   std::mutex b;
   int foo;
   int foo2;
   folly::detail::AtFork::registerHandler(
       &foo,
       [&] { return a.try_lock(); },
       [&] { a.unlock(); },
       [&] { a.unlock(); });
   folly::detail::AtFork::registerHandler(
       &foo2,
       [&] { return b.try_lock(); },
       [&] { b.unlock(); },
       [&] { b.unlock(); });
   auto thr = std::thread([&]() {
     std::lock_guard<std::mutex> g(a);
     started = true;
     usleep(100);
     std::lock_guard<std::mutex> g2(b);
   });
   while (!started) {
   }
   auto pid = fork();
   if (pid) {
     int status;
     auto pid2 = wait(&status);
     EXPECT_EQ(status, 0);
     EXPECT_EQ(pid, pid2);
   } else {
     exit(0);
   }
   done = true;
   thr.join();
 }