proxygen: proxygen/folly/folly/synchronization/test/BatonBenchmark.cpp File Reference
BatonBenchmark.cpp File Reference
#include <folly/synchronization/Baton.h>
#include <thread>
#include <folly/Benchmark.h>
#include <folly/portability/Semaphore.h>
#include <folly/synchronization/test/BatonTestHelpers.h>
#include <folly/test/DeterministicSchedule.h>
Functions
BENCHMARK (baton_pingpong_blocking, iters)
BENCHMARK (baton_pingpong_nonblocking, iters)
BENCHMARK_DRAW_LINE ()
BENCHMARK (baton_pingpong_emulated_futex_blocking, iters)
BENCHMARK (baton_pingpong_emulated_futex_nonblocking, iters)
BENCHMARK (posix_sem_pingpong, iters)
int main (int argc, char **argv)
Function Documentation
BENCHMARK (baton_pingpong_blocking , iters)
Definition at line 30 of file BatonBenchmark.cpp.
{
   run_pingpong_test<true, std::atomic>(iters);
 }
BENCHMARK (baton_pingpong_nonblocking , iters)
Definition at line 34 of file BatonBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE().
{
   run_pingpong_test<false, std::atomic>(iters);
 }
BENCHMARK (baton_pingpong_emulated_futex_blocking , iters)
Definition at line 40 of file BatonBenchmark.cpp.
{
   run_pingpong_test<true, EmulatedFutexAtomic>(iters);
 }
BENCHMARK (baton_pingpong_emulated_futex_nonblocking , iters)
Definition at line 44 of file BatonBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE().
{
   run_pingpong_test<false, EmulatedFutexAtomic>(iters);
 }
BENCHMARK (posix_sem_pingpong , iters)
Definition at line 50 of file BatonBenchmark.cpp.
References a, b, and i.
{
   sem_t sems[3];
   sem_t* a = sems + 0;
   sem_t* b = sems + 2; // to get it on a different cache line
   sem_init(a, 0, 0);
   sem_init(b, 0, 0);
   auto thr = std::thread([=] {
     for (size_t i = 0; i < iters; ++i) {
       sem_wait(a);
       sem_post(b);
     }
   });
   for (size_t i = 0; i < iters; ++i) {
     sem_post(a);
     sem_wait(b);
   }
   thr.join();
 }
BENCHMARK_DRAW_LINE ()
int main (int argc, char ** argv)
Definition at line 75 of file BatonBenchmark.cpp.
References folly::runBenchmarks().
{
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   folly::runBenchmarks();
   return 0;
 }