proxygen: proxygen/folly/folly/test/function_benchmark/benchmark_impl.h File Reference
benchmark_impl.h File Reference
#include <functional>
#include <folly/Function.h>
Functions
void BM_fn_ptr_invoke_impl (int iters, void(*fn)())
void BM_std_function_invoke_impl (int iters, const std::function< void()> &fn)
void BM_Function_invoke_impl (int iters, const folly::Function< void() const > &fn)
void BM_mem_fn_invoke_impl (int iters, TestClass *tc, void(TestClass::*memfn)())
void BM_virtual_fn_invoke_impl (int iters, VirtualClass *vc)
void BM_fn_ptr_invoke_inlined_impl (int iters, void(*fn)())
template<typename T >
void BM_invoke_fn_template_impl (int iters, const T &fn)
Function Documentation
void BM_fn_ptr_invoke_impl (int iters, void(*)() fn)
Definition at line 26 of file benchmark_impl.cpp.
Referenced by BENCHMARK().
{
   for (int n = 0; n < iters; ++n) {
     fn();
   }
 }
void BM_fn_ptr_invoke_inlined_impl (int iters, void(*)() fn) inline
Definition at line 40 of file benchmark_impl.h.
Referenced by BENCHMARK().
{
   for (int n = 0; n < iters; ++n) {
     fn();
   }
 }
void BM_Function_invoke_impl (int iters, const folly::Function< void() const > & fn)
Definition at line 38 of file benchmark_impl.cpp.
Referenced by BENCHMARK().
{
   for (int n = 0; n < iters; ++n) {
     fn();
   }
 }
template<typename T > void BM_invoke_fn_template_impl (int iters, const T & fn)
Definition at line 49 of file benchmark_impl.h.
Referenced by BENCHMARK().
{
   for (int n = 0; n < iters; ++n) {
     fn();
   }
 }
void BM_mem_fn_invoke_impl (int iters, TestClass * tc, void(TestClass::*)() memfn)
Definition at line 46 of file benchmark_impl.cpp.
Referenced by BENCHMARK().
{
   for (int n = 0; n < iters; ++n) {
     (tc->*memfn)();
   }
 }
void BM_std_function_invoke_impl (int iters, const std::function< void()> & fn)
Definition at line 32 of file benchmark_impl.cpp.
Referenced by BENCHMARK().
{
   for (int n = 0; n < iters; ++n) {
     fn();
   }
 }
void BM_virtual_fn_invoke_impl (int iters, VirtualClass * vc)
Definition at line 55 of file benchmark_impl.cpp.
References VirtualClass::doNothing().
Referenced by BENCHMARK().
{
   for (int n = 0; n < iters; ++n) {
     vc->doNothing();
   }
 }