proxygen: proxygen/folly/folly/experimental/test/BitVectorCodingTest.cpp File Reference
BitVectorCodingTest.cpp File Reference
#include <algorithm>
#include <numeric>
#include <random>
#include <vector>
#include <folly/Benchmark.h>
#include <folly/experimental/BitVectorCoding.h>
#include <folly/experimental/Select64.h>
#include <folly/experimental/test/CodingTestUtils.h>
#include <folly/init/Init.h>
Classes
class BitVectorCodingTest
Namespaces
bm
Typedefs
typedef BitVectorEncoder< uint32_t, uint32_t, 128, 128 > bm::Encoder
Functions
TEST_F (BitVectorCodingTest, Empty)
TEST_F (BitVectorCodingTest, Simple)
TEST_F (BitVectorCodingTest, SkipPointers)
TEST_F (BitVectorCodingTest, ForwardPointers)
TEST_F (BitVectorCodingTest, SkipForwardPointers)
void bm::init ()
void bm::free ()
BENCHMARK (Next, iters)
size_t Skip_ForwardQ128 (size_t iters, size_t logAvgSkip)
BENCHMARK (Jump_ForwardQ128, iters)
BENCHMARK_DRAW_LINE ()
size_t SkipTo_SkipQ128 (size_t iters, size_t logAvgSkip)
BENCHMARK (JumpTo_SkipQ128, iters)
BENCHMARK (Encode_10)
BENCHMARK (Encode)
int main (int argc, char **argv)
Variables
std::vector< uint32_t > bm::data
std::vector< size_t > bm::order
std::vector< uint32_t > bm::encodeSmallData
std::vector< uint32_t > bm::encodeLargeData
Encoder::MutableCompressedList bm::list
Function Documentation
BENCHMARK (Next , iters)
Definition at line 100 of file BitVectorCodingTest.cpp.
References bm::data, folly::compression::dispatchInstructions(), and bm::list.
{
   dispatchInstructions([&](auto instructions) {
     bmNext<BitVectorReader<bm::Encoder, decltype(instructions)>>(
         bm::list, bm::data, iters);
   });
 }
BENCHMARK (Jump_ForwardQ128 , iters)
Definition at line 123 of file BitVectorCodingTest.cpp.
References folly::BENCHMARK_DRAW_LINE(), bm::data, folly::compression::dispatchInstructions(), bm::list, and bm::order.
{
   dispatchInstructions([&](auto instructions) {
     bmJump<BitVectorReader<bm::Encoder, decltype(instructions)>>(
         bm::list, bm::data, bm::order, iters);
   });
 }
BENCHMARK (JumpTo_SkipQ128 , iters)
Definition at line 148 of file BitVectorCodingTest.cpp.
References folly::BENCHMARK_DRAW_LINE(), bm::data, folly::compression::dispatchInstructions(), bm::list, and bm::order.
{
   dispatchInstructions([&](auto instructions) {
     bmJumpTo<BitVectorReader<bm::Encoder, decltype(instructions)>>(
         bm::list, bm::data, bm::order, iters);
   });
 }
BENCHMARK (Encode_10)
Definition at line 157 of file BitVectorCodingTest.cpp.
References folly::test::begin(), folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::encode(), bm::encodeSmallData, folly::test::end(), folly::compression::BitVectorCompressedListBase< Pointer >::free(), and bm::list.
                      {
   auto list = bm::Encoder::encode(
       bm::encodeSmallData.begin(), bm::encodeSmallData.end());
   list.free();
 }
BENCHMARK (Encode)
Definition at line 163 of file BitVectorCodingTest.cpp.
References folly::test::begin(), folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::encode(), bm::encodeLargeData, folly::test::end(), folly::compression::BitVectorCompressedListBase< Pointer >::free(), bm::list, s, Skip_ForwardQ128(), SkipTo_SkipQ128(), and folly::detail::distributed_mutex::time().
                   {
   auto list = bm::Encoder::encode(
       bm::encodeLargeData.begin(), bm::encodeLargeData.end());
   list.free();
 }
BENCHMARK_DRAW_LINE ()
int main (int argc, char ** argv)
Definition at line 200 of file BitVectorCodingTest.cpp.
References bm::free(), folly::init(), bm::init(), testing::InitGoogleTest(), RUN_ALL_TESTS(), and folly::runBenchmarks().
{
   testing::InitGoogleTest(&argc, argv);
   folly::init(&argc, &argv);
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   auto ret = RUN_ALL_TESTS();
   if (ret == 0 && FLAGS_benchmark) {
     bm::init();
     folly::runBenchmarks();
     bm::free();
   }
   return ret;
 }
size_t Skip_ForwardQ128 (size_t iters, size_t logAvgSkip)
Definition at line 107 of file BitVectorCodingTest.cpp.
References BENCHMARK_NAMED_PARAM_MULTI, bm::data, folly::compression::dispatchInstructions(), and bm::list.
Referenced by BENCHMARK().
{
   dispatchInstructions([&](auto instructions) {
     bmSkip<BitVectorReader<bm::Encoder, decltype(instructions)>>(
         bm::list, bm::data, logAvgSkip, iters);
   });
   return iters;
 }
size_t SkipTo_SkipQ128 (size_t iters, size_t logAvgSkip)
Definition at line 132 of file BitVectorCodingTest.cpp.
References BENCHMARK_NAMED_PARAM_MULTI, bm::data, folly::compression::dispatchInstructions(), and bm::list.
Referenced by BENCHMARK().
{
   dispatchInstructions([&](auto instructions) {
     bmSkipTo<BitVectorReader<bm::Encoder, decltype(instructions)>>(
         bm::list, bm::data, logAvgSkip, iters);
   });
   return iters;
 }
TEST_F (BitVectorCodingTest , Empty)
Definition at line 48 of file BitVectorCodingTest.cpp.
{
   doTestEmpty();
 }
TEST_F (BitVectorCodingTest , Simple)
Definition at line 52 of file BitVectorCodingTest.cpp.
{
   doTestAll<0, 0>();
 }
TEST_F (BitVectorCodingTest , SkipPointers)
Definition at line 56 of file BitVectorCodingTest.cpp.
{
   doTestAll<128, 0>();
 }
TEST_F (BitVectorCodingTest , ForwardPointers)
Definition at line 60 of file BitVectorCodingTest.cpp.
{
   doTestAll<0, 128>();
 }
TEST_F (BitVectorCodingTest , SkipForwardPointers)
Definition at line 64 of file BitVectorCodingTest.cpp.
{
   doTestAll<128, 128>();
 }