proxygen: proxygen/folly/folly/stats/test/BucketedTimeSeriesBenchmark.cpp File Reference
BucketedTimeSeriesBenchmark.cpp File Reference
#include <folly/stats/BucketedTimeSeries.h>
#include <glog/logging.h>
#include <folly/Benchmark.h>
#include <folly/stats/BucketedTimeSeries-defs.h>
Functions
void addValue (unsigned int iters, seconds duration, size_t numBuckets, size_t callsPerSecond)
BENCHMARK_DRAW_LINE ()
int main (int argc, char *argv[])
Function Documentation
void addValue (unsigned int iters, seconds duration, size_t numBuckets, size_t callsPerSecond)
Definition at line 28 of file BucketedTimeSeriesBenchmark.cpp.
References folly::BucketedTimeSeries< VT, CT >::addValue(), BENCHMARK_DRAW_LINE(), BENCHMARK_NAMED_PARAM, and folly::BenchmarkSuspender::dismiss().
{
   BenchmarkSuspender suspend;
   BucketedTimeSeries<int64_t> ts(numBuckets, duration);
   suspend.dismiss();
   seconds currentTime(1342000000);
   size_t timeCounter = 0;
   for (unsigned int n = 0; n < iters; ++n, ++timeCounter) {
     if (timeCounter >= callsPerSecond) {
       timeCounter = 0;
       ++currentTime;
     }
     ts.addValue(currentTime, n);
   }
 }
BENCHMARK_DRAW_LINE ()
Referenced by addValue().
int main (int argc, char * argv[])
Definition at line 76 of file BucketedTimeSeriesBenchmark.cpp.
References argv, and folly::runBenchmarks().
{
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   folly::runBenchmarks();
   return 0;
 }