proxygen: proxygen/folly/folly/stats/test/BufferedStatTest.cpp File Reference
BufferedStatTest.cpp File Reference
#include <folly/stats/detail/BufferedStat-defs.h>
#include <folly/Range.h>
#include <folly/portability/GTest.h>
Classes
struct MockClock
class SimpleDigest< MergeSize >
class BufferedDigestTest
class BufferedSlidingWindowTest
Functions
TEST_F (BufferedDigestTest, Buffering)
TEST_F (BufferedDigestTest, PartiallyPassedExpiry)
TEST_F (BufferedDigestTest, ForceUpdate)
TEST_F (BufferedSlidingWindowTest, Buffering)
TEST_F (BufferedSlidingWindowTest, PartiallyPassedExpiry)
TEST_F (BufferedSlidingWindowTest, ForceUpdate)
TEST_F (BufferedSlidingWindowTest, BufferingAfterSlide)
TEST_F (BufferedSlidingWindowTest, TwoSlides)
TEST_F (BufferedSlidingWindowTest, MultiWindowDurationSlide)
TEST_F (BufferedSlidingWindowTest, SlidePastWindow)
Variables
const size_t kDigestSize = 100
Function Documentation
TEST_F (BufferedDigestTest , Buffering)
Definition at line 93 of file BufferedStatTest.cpp.
References EXPECT_TRUE.
{
   bd->append(0);
   bd->append(1);
   bd->append(2);
   auto digest = bd->get();
   EXPECT_TRUE(digest.empty());
 }
TEST_F (BufferedDigestTest , PartiallyPassedExpiry)
Definition at line 102 of file BufferedStatTest.cpp.
References EXPECT_EQ, MockClock::Now, and values().
{
   bd->append(0);
   bd->append(1);
   bd->append(2);
   MockClock::Now += bufferDuration / 10;
   auto digest = bd->get();
   auto values = digest.getValues();
   EXPECT_EQ(0, values[0]);
   EXPECT_EQ(1, values[1]);
   EXPECT_EQ(2, values[2]);
 }
TEST_F (BufferedDigestTest , ForceUpdate)
Definition at line 117 of file BufferedStatTest.cpp.
References EXPECT_EQ, EXPECT_TRUE, MockClock::Now, and values().
{
   bd->append(0);
   bd->append(1);
   bd->append(2);
   // empty since we haven't passed expiry
   auto digest = bd->get();
   EXPECT_TRUE(digest.empty());
   // force update
   bd->flush();
   digest = bd->get();
   auto values = digest.getValues();
   EXPECT_EQ(0, values[0]);
   EXPECT_EQ(1, values[1]);
   EXPECT_EQ(2, values[2]);
   // append 3 and do a normal get; only the previously
   // flushed values should show up and not 3 since we
   // haven't passed expiry
   bd->append(3);
   digest = bd->get();
   values = digest.getValues();
   EXPECT_EQ(0, values[0]);
   EXPECT_EQ(1, values[1]);
   EXPECT_EQ(2, values[2]);
   // pass expiry; 3 should now be visible
   MockClock::Now += bufferDuration;
   digest = bd->get();
   values = digest.getValues();
   EXPECT_EQ(0, values[0]);
   EXPECT_EQ(1, values[1]);
   EXPECT_EQ(2, values[2]);
   EXPECT_EQ(3, values[3]);
 }
TEST_F (BufferedSlidingWindowTest , Buffering)
Definition at line 168 of file BufferedStatTest.cpp.
References EXPECT_EQ.
{
   bsw->append(0);
   bsw->append(1);
   bsw->append(2);
   auto digests = bsw->get();
   EXPECT_EQ(0, digests.size());
 }
TEST_F (BufferedSlidingWindowTest , PartiallyPassedExpiry)
Definition at line 177 of file BufferedStatTest.cpp.
References EXPECT_EQ, i, MockClock::Now, and folly::size().
{
   bsw->append(0);
   bsw->append(1);
   bsw->append(2);
   MockClock::Now += windowDuration / 10;
   auto digests = bsw->get();
   EXPECT_EQ(1, digests.size());
   EXPECT_EQ(3, digests[0].getValues().size());
   for (double i = 0; i < 3; ++i) {
     EXPECT_EQ(i, digests[0].getValues()[i]);
   }
 }
TEST_F (BufferedSlidingWindowTest , ForceUpdate)
Definition at line 194 of file BufferedStatTest.cpp.
References EXPECT_EQ, i, MockClock::Now, and folly::size().
{
   bsw->append(0);
   bsw->append(1);
   bsw->append(2);
   // empty since we haven't passed expiry
   auto digests = bsw->get();
   EXPECT_EQ(0, digests.size());
   // flush
   bsw->flush();
   digests = bsw->get();
   EXPECT_EQ(1, digests.size());
   EXPECT_EQ(3, digests[0].getValues().size());
   for (double i = 0; i < 3; ++i) {
     EXPECT_EQ(i, digests[0].getValues()[i]);
   }
   // append 3 and flush again; 3 will be merged with
   // current window
   bsw->append(3);
   bsw->flush();
   digests = bsw->get();
   EXPECT_EQ(1, digests.size());
   EXPECT_EQ(4, digests[0].getValues().size());
   for (double i = 0; i < 4; ++i) {
     EXPECT_EQ(i, digests[0].getValues()[i]);
   }
   // append 4 and do a regular get. previous values
   // show up but not 4
   bsw->append(4);
   digests = bsw->get();
   EXPECT_EQ(1, digests.size());
   EXPECT_EQ(4, digests[0].getValues().size());
   for (double i = 0; i < 4; ++i) {
     EXPECT_EQ(i, digests[0].getValues()[i]);
   }
   // pass expiry
   MockClock::Now += windowDuration;
   digests = bsw->get();
   EXPECT_EQ(2, digests.size());
   EXPECT_EQ(1, digests[0].getValues().size());
   EXPECT_EQ(4, digests[0].getValues().front());
   EXPECT_EQ(4, digests[1].getValues().size());
   for (double i = 0; i < 4; ++i) {
     EXPECT_EQ(i, digests[1].getValues()[i]);
   }
 }
TEST_F (BufferedSlidingWindowTest , BufferingAfterSlide)
Definition at line 247 of file BufferedStatTest.cpp.
References EXPECT_EQ, and MockClock::Now.
{
   MockClock::Now += std::chrono::milliseconds{1};
   bsw->append(1);
   auto digests = bsw->get();
   EXPECT_EQ(0, digests.size());
 }
TEST_F (BufferedSlidingWindowTest , TwoSlides)
Definition at line 256 of file BufferedStatTest.cpp.
References EXPECT_EQ, MockClock::Now, and folly::size().
{
   bsw->append(0);
   MockClock::Now += windowDuration;
   bsw->append(1);
   MockClock::Now += windowDuration;
   auto digests = bsw->get();
   EXPECT_EQ(2, digests.size());
   EXPECT_EQ(1, digests[0].getValues().size());
   EXPECT_EQ(1, digests[0].getValues()[0]);
   EXPECT_EQ(1, digests[1].getValues().size());
   EXPECT_EQ(0, digests[1].getValues()[0]);
 }
TEST_F (BufferedSlidingWindowTest , MultiWindowDurationSlide)
Definition at line 274 of file BufferedStatTest.cpp.
References EXPECT_EQ, and MockClock::Now.
{
   bsw->append(0);
   MockClock::Now += windowDuration * 2;
   auto digests = bsw->get();
   EXPECT_EQ(1, digests.size());
 }
TEST_F (BufferedSlidingWindowTest , SlidePastWindow)
Definition at line 283 of file BufferedStatTest.cpp.
References EXPECT_EQ, and MockClock::Now.
{
   bsw->append(0);
   MockClock::Now += windowDuration * (nBuckets + 1);
   auto digests = bsw->get();
   EXPECT_EQ(0, digests.size());
 }
Variable Documentation
const size_t kDigestSize = 100
Definition at line 25 of file BufferedStatTest.cpp.
Referenced by BufferedDigestTest::SetUp(), BufferedSlidingWindowTest::SetUp(), and SimpleDigest< MergeSize >::SimpleDigest().