proxygen: proxygen/folly/folly/concurrency/test/CacheLocalityTest.cpp File Reference
CacheLocalityTest.cpp File Reference
#include <folly/concurrency/CacheLocality.h>
#include <folly/portability/GTest.h>
#include <glog/logging.h>
#include <memory>
#include <thread>
#include <unordered_map>
Functions
TEST (CacheLocality, FakeSysfs)
TEST (ThreadId, SimplePthread)
TEST (AccessSpreader, Simple)
TEST (AccessSpreader, SimpleCached)
TEST (AccessSpreader, ConcurrentAccessCached)
Variables
static std::unordered_map< std::string, std::string > fakeSysfsTree
static const CacheLocality nonUniformExampleLocality
This is the expected CacheLocality structure for fakeSysfsTree.
Function Documentation
TEST (CacheLocality , FakeSysfs)
Definition at line 312 of file CacheLocalityTest.cpp.
References EXPECT_EQ, EXPECT_TRUE, name, nonUniformExampleLocality, folly::Getcpu::resolveVdsoFunc(), string, and folly::TEST().
{
   auto parsed = CacheLocality::readFromSysfsTree([](std::string name) {
     auto iter = fakeSysfsTree.find(name);
     return iter == fakeSysfsTree.end() ? std::string() : iter->second;
   });
   auto& expected = nonUniformExampleLocality;
   EXPECT_EQ(expected.numCpus, parsed.numCpus);
   EXPECT_EQ(expected.numCachesByLevel, parsed.numCachesByLevel);
   EXPECT_EQ(expected.localityIndexByCpu, parsed.localityIndexByCpu);
 }
TEST (ThreadId , SimplePthread)
Definition at line 347 of file CacheLocalityTest.cpp.
References EXPECT_EQ, EXPECT_TRUE, and folly::FallbackGetcpu< ThreadId >::getcpu().
{
   unsigned cpu = 0;
   auto rv =
       folly::FallbackGetcpu<HashingThreadId>::getcpu(&cpu, nullptr, nullptr);
   EXPECT_EQ(rv, 0);
   EXPECT_TRUE(cpu > 0);
   unsigned again;
   folly::FallbackGetcpu<HashingThreadId>::getcpu(&again, nullptr, nullptr);
   EXPECT_EQ(cpu, again);
 }
TEST (AccessSpreader , Simple)
Definition at line 372 of file CacheLocalityTest.cpp.
References EXPECT_LT, and s.
{
   for (size_t s = 1; s < 200; ++s) {
     EXPECT_LT(AccessSpreader<>::current(s), s);
   }
 }
TEST (AccessSpreader , SimpleCached)
Definition at line 378 of file CacheLocalityTest.cpp.
References EXPECT_LT, and s.
{
   for (size_t s = 1; s < 200; ++s) {
     EXPECT_LT(AccessSpreader<>::cachedCurrent(s), s);
   }
 }
TEST (AccessSpreader , ConcurrentAccessCached)
Definition at line 384 of file CacheLocalityTest.cpp.
References a, c, folly::AccessSpreader< Atom >::current(), DECLARE_SPREADER_TAG, EXPECT_EQ, EXPECT_LT, EXPECT_TRUE, folly::CoreRawAllocator< Stripes >::get(), i, s, folly::TEST(), threads, folly::CacheLocality::uniform(), and folly::fibers::yield().
{
   std::vector<std::thread> threads;
   for (size_t i = 0; i < 4; ++i) {
     threads.emplace_back([]() {
       for (size_t s : {16, 32, 64}) {
         for (size_t j = 1; j < 200; ++j) {
           EXPECT_LT(AccessSpreader<>::cachedCurrent(s), s);
           EXPECT_LT(AccessSpreader<>::cachedCurrent(s), s);
         }
         std::this_thread::yield();
       }
     });
   }
   for (auto& thread : threads) {
     thread.join();
   }
 }
Variable Documentation
std::unordered_map<std::string, std::string> fakeSysfsTree static
This is the relevant nodes from a production box's sysfs tree. If you think this map is ugly you should see the version of this test that used a real directory tree. To reduce the chance of testing error I haven't tried to remove the common prefix
Definition at line 32 of file CacheLocalityTest.cpp.
const CacheLocality nonUniformExampleLocality static
Initial value:
= {
    32,
    {16, 16, 2},
    {0,  2, 4, 6, 8, 10, 11, 12, 14, 16, 18, 20, 22, 24, 26, 28,
     30, 1, 3, 5, 7, 9,  13, 15, 17, 19, 21, 23, 25, 27, 29, 31}}
This is the expected CacheLocality structure for fakeSysfsTree.
Definition at line 306 of file CacheLocalityTest.cpp.
Referenced by TEST().