proxygen: proxygen/folly/folly/futures/test/CallbackLifetimeTest.cpp File Reference
CallbackLifetimeTest.cpp File Reference
#include <folly/futures/Future.h>
#include <thread>
#include <folly/futures/test/TestExecutor.h>
#include <folly/portability/GTest.h>
Functions
TEST_F (CallbackLifetimeTest, thenReturnsValue)
TEST_F (CallbackLifetimeTest, thenReturnsValueThrows)
TEST_F (CallbackLifetimeTest, thenReturnsFuture)
TEST_F (CallbackLifetimeTest, thenReturnsFutureThrows)
TEST_F (CallbackLifetimeTest, onErrorTakesExnReturnsValueMatch)
TEST_F (CallbackLifetimeTest, onErrorTakesExnReturnsValueMatchThrows)
TEST_F (CallbackLifetimeTest, onErrorTakesExnReturnsValueWrong)
TEST_F (CallbackLifetimeTest, onErrorTakesExnReturnsValueWrongThrows)
TEST_F (CallbackLifetimeTest, onErrorTakesExnReturnsFutureMatch)
TEST_F (CallbackLifetimeTest, onErrorTakesExnReturnsFutureMatchThrows)
TEST_F (CallbackLifetimeTest, onErrorTakesExnReturnsFutureWrong)
TEST_F (CallbackLifetimeTest, onErrorTakesExnReturnsFutureWrongThrows)
TEST_F (CallbackLifetimeTest, onErrorTakesWrapReturnsValue)
TEST_F (CallbackLifetimeTest, onErrorTakesWrapReturnsValueThrows)
TEST_F (CallbackLifetimeTest, onErrorTakesWrapReturnsFuture)
TEST_F (CallbackLifetimeTest, onErrorTakesWrapReturnsFutureThrows)
Function Documentation
TEST_F (CallbackLifetimeTest , thenReturnsValue)
Definition at line 77 of file CallbackLifetimeTest.cpp.
References testing::_, c, folly::pushmi::executor, EXPECT_EQ, folly::via(), and folly::detail::distributed_mutex::wait().
{
   auto c = mkC();
   via(&executor).thenValue([_ = mkCGuard(c)](auto&&) {}).wait();
   EXPECT_EQ(1, *c);
 }
TEST_F (CallbackLifetimeTest , thenReturnsValueThrows)
Definition at line 83 of file CallbackLifetimeTest.cpp.
References testing::_, c, folly::pushmi::executor, EXPECT_EQ, folly::via(), and folly::detail::distributed_mutex::wait().
{
   auto c = mkC();
   via(&executor).thenValue([_ = mkCGuard(c)](auto&&) { raise(); }).wait();
   EXPECT_EQ(1, *c);
 }
TEST_F (CallbackLifetimeTest , thenReturnsFuture)
Definition at line 89 of file CallbackLifetimeTest.cpp.
References testing::_, c, folly::pushmi::executor, EXPECT_EQ, folly::makeFuture(), folly::via(), and folly::detail::distributed_mutex::wait().
{
   auto c = mkC();
   via(&executor)
       .thenValue([_ = mkCGuard(c)](auto&&) { return makeFuture(); })
       .wait();
   EXPECT_EQ(1, *c);
 }
TEST_F (CallbackLifetimeTest , thenReturnsFutureThrows)
Definition at line 97 of file CallbackLifetimeTest.cpp.
References testing::_, c, folly::pushmi::executor, EXPECT_EQ, folly::via(), and folly::detail::distributed_mutex::wait().
{
   auto c = mkC();
   via(&executor)
       .thenValue([_ = mkCGuard(c)](auto&&) { return raiseFut(); })
       .wait();
   EXPECT_EQ(1, *c);
 }
TEST_F (CallbackLifetimeTest , onErrorTakesExnReturnsValueMatch)
Definition at line 105 of file CallbackLifetimeTest.cpp.
References testing::_, c, folly::pushmi::executor, EXPECT_EQ, folly::via(), and folly::detail::distributed_mutex::wait().
{
   auto c = mkC();
   via(&executor)
       .thenValue(raise)
       .onError([_ = mkCGuard(c)](std::exception&) {})
       .wait();
   EXPECT_EQ(1, *c);
 }
TEST_F (CallbackLifetimeTest , onErrorTakesExnReturnsValueMatchThrows)
Definition at line 114 of file CallbackLifetimeTest.cpp.
References testing::_, c, folly::pushmi::executor, EXPECT_EQ, folly::via(), and folly::detail::distributed_mutex::wait().
{
   auto c = mkC();
   via(&executor)
       .thenValue(raise)
       .onError([_ = mkCGuard(c)](std::exception&) { raise(); })
       .wait();
   EXPECT_EQ(1, *c);
 }
TEST_F (CallbackLifetimeTest , onErrorTakesExnReturnsValueWrong)
Definition at line 123 of file CallbackLifetimeTest.cpp.
References testing::_, c, folly::pushmi::executor, EXPECT_EQ, folly::via(), and folly::detail::distributed_mutex::wait().
{
   auto c = mkC();
   via(&executor)
       .thenValue(raise)
       .onError([_ = mkCGuard(c)](std::logic_error&) {})
       .wait();
   EXPECT_EQ(1, *c);
 }
TEST_F (CallbackLifetimeTest , onErrorTakesExnReturnsValueWrongThrows)
Definition at line 132 of file CallbackLifetimeTest.cpp.
References testing::_, c, folly::pushmi::executor, EXPECT_EQ, folly::via(), and folly::detail::distributed_mutex::wait().
{
   auto c = mkC();
   via(&executor)
       .thenValue(raise)
       .onError([_ = mkCGuard(c)](std::logic_error&) { raise(); })
       .wait();
   EXPECT_EQ(1, *c);
 }
TEST_F (CallbackLifetimeTest , onErrorTakesExnReturnsFutureMatch)
Definition at line 141 of file CallbackLifetimeTest.cpp.
References testing::_, c, folly::pushmi::executor, EXPECT_EQ, folly::makeFuture(), folly::via(), and folly::detail::distributed_mutex::wait().
{
   auto c = mkC();
   via(&executor)
       .thenValue(raise)
       .onError([_ = mkCGuard(c)](std::exception&) { return makeFuture(); })
       .wait();
   EXPECT_EQ(1, *c);
 }
TEST_F (CallbackLifetimeTest , onErrorTakesExnReturnsFutureMatchThrows)
Definition at line 150 of file CallbackLifetimeTest.cpp.
References testing::_, c, folly::pushmi::executor, EXPECT_EQ, folly::via(), and folly::detail::distributed_mutex::wait().
{
   auto c = mkC();
   via(&executor)
       .thenValue(raise)
       .onError([_ = mkCGuard(c)](std::exception&) { return raiseFut(); })
       .wait();
   EXPECT_EQ(1, *c);
 }
TEST_F (CallbackLifetimeTest , onErrorTakesExnReturnsFutureWrong)
Definition at line 159 of file CallbackLifetimeTest.cpp.
References testing::_, c, folly::pushmi::executor, EXPECT_EQ, folly::makeFuture(), folly::via(), and folly::detail::distributed_mutex::wait().
{
   auto c = mkC();
   via(&executor)
       .thenValue(raise)
       .onError([_ = mkCGuard(c)](std::logic_error&) { return makeFuture(); })
       .wait();
   EXPECT_EQ(1, *c);
 }
TEST_F (CallbackLifetimeTest , onErrorTakesExnReturnsFutureWrongThrows)
Definition at line 168 of file CallbackLifetimeTest.cpp.
References testing::_, c, folly::pushmi::executor, EXPECT_EQ, folly::via(), and folly::detail::distributed_mutex::wait().
{
   auto c = mkC();
   via(&executor)
       .thenValue(raise)
       .onError([_ = mkCGuard(c)](std::logic_error&) { return raiseFut(); })
       .wait();
   EXPECT_EQ(1, *c);
 }
TEST_F (CallbackLifetimeTest , onErrorTakesWrapReturnsValue)
Definition at line 177 of file CallbackLifetimeTest.cpp.
References testing::_, c, folly::pushmi::executor, EXPECT_EQ, folly::via(), and folly::detail::distributed_mutex::wait().
{
   auto c = mkC();
   via(&executor)
       .thenValue(raise)
       .onError([_ = mkCGuard(c)](exception_wrapper&&) {})
       .wait();
   EXPECT_EQ(1, *c);
 }
TEST_F (CallbackLifetimeTest , onErrorTakesWrapReturnsValueThrows)
Definition at line 186 of file CallbackLifetimeTest.cpp.
References testing::_, c, folly::pushmi::executor, EXPECT_EQ, folly::via(), and folly::detail::distributed_mutex::wait().
{
   auto c = mkC();
   via(&executor)
       .thenValue(raise)
       .onError([_ = mkCGuard(c)](exception_wrapper&&) { raise(); })
       .wait();
   EXPECT_EQ(1, *c);
 }
TEST_F (CallbackLifetimeTest , onErrorTakesWrapReturnsFuture)
Definition at line 195 of file CallbackLifetimeTest.cpp.
References testing::_, c, folly::pushmi::executor, EXPECT_EQ, folly::makeFuture(), folly::via(), and folly::detail::distributed_mutex::wait().
{
   auto c = mkC();
   via(&executor)
       .thenValue(raise)
       .onError([_ = mkCGuard(c)](exception_wrapper&&) { return makeFuture(); })
       .wait();
   EXPECT_EQ(1, *c);
 }
TEST_F (CallbackLifetimeTest , onErrorTakesWrapReturnsFutureThrows)
Definition at line 204 of file CallbackLifetimeTest.cpp.
References testing::_, c, folly::pushmi::executor, EXPECT_EQ, folly::via(), and folly::detail::distributed_mutex::wait().
{
   auto c = mkC();
   via(&executor)
       .thenValue(raise)
       .onError([_ = mkCGuard(c)](exception_wrapper&&) { return raiseFut(); })
       .wait();
   EXPECT_EQ(1, *c);
 }