proxygen: folly::gen::detail::Visit< Visitor >::Generator< Value, Source > Class Template Reference
folly::gen::detail::Visit< Visitor >::Generator< Value, Source > Class Template Reference
#include <Base-inl.h>
Public Member Functions
Generator (Source source, const Visitor &visitor)
template<class Body >
void foreach (Body &&body) const
template<class Handler >
bool apply (Handler &&handler) const
Public Member Functions inherited from folly::gen::GenImpl< Value, Generator< Value, Source > >
bool apply (Handler &&handler) const
void foreach (Body &&body) const
Public Member Functions inherited from folly::gen::FBounded< Self >
const Self & self () const
Self & self ()
Static Public Attributes
static constexpr bool infinite = Source::infinite
Static Public Attributes inherited from folly::gen::GenImpl< Value, Generator< Value, Source > >
static constexpr bool infinite
Private Attributes
Source source_
Visitor visitor_
Additional Inherited Members
Public Types inherited from folly::gen::GenImpl< Value, Generator< Value, Source > >
typedef Value ValueType
typedef std::decay< Value >::type StorageType
Protected Member Functions inherited from folly::gen::GenImpl< Value, Generator< Value, Source > >
GenImpl ()=default
GenImpl (GenImpl &&)=default
GenImpl (const GenImpl &)=default
GenImpl & operator= (GenImpl &&)=default
GenImpl & operator= (const GenImpl &)=default
Detailed Description
template<class Visitor>
template<class Value, class Source>
class folly::gen::detail::Visit< Visitor >::Generator< Value, Source >
Definition at line 761 of file Base-inl.h.
Constructor & Destructor Documentation
template<class Visitor > template<class Value , class Source > folly::gen::detail::Visit< Visitor >::Generator< Value, Source >::Generator (Source source, const Visitor & visitor) inline explicit
Definition at line 766 of file Base-inl.h.
         : source_(std::move(source)), visitor_(visitor) {}
Member Function Documentation
template<class Visitor > template<class Value , class Source > template<class Handler > bool folly::gen::detail::Visit< Visitor >::Generator< Value, Source >::apply (Handler && handler) const inline
Definition at line 778 of file Base-inl.h.
References handler(), value, and testing::Value().
{
       return source_.apply([&](Value value) {
         visitor_(value); // not forwarding to avoid accidental moves
         return handler(std::forward<Value>(value));
       });
     }
template<class Visitor > template<class Value , class Source > template<class Body > void folly::gen::detail::Visit< Visitor >::Generator< Value, Source >::foreach (Body && body) const inline
Definition at line 770 of file Base-inl.h.
References value, and testing::Value().
{
       source_.foreach([&](Value value) {
         visitor_(value); // not forwarding to avoid accidental moves
         body(std::forward<Value>(value));
       });
     }
Member Data Documentation
template<class Visitor > template<class Value , class Source > constexpr bool folly::gen::detail::Visit< Visitor >::Generator< Value, Source >::infinite = Source::infinite static
Definition at line 785 of file Base-inl.h.
template<class Visitor > template<class Value , class Source > Source folly::gen::detail::Visit< Visitor >::Generator< Value, Source >::source_ private
Definition at line 762 of file Base-inl.h.
template<class Visitor > template<class Value , class Source > Visitor folly::gen::detail::Visit< Visitor >::Generator< Value, Source >::visitor_ private
Definition at line 763 of file Base-inl.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/gen/Base-inl.h