proxygen: testing::gmock_matchers_test::IsGreaterThan Class Reference
testing::gmock_matchers_test::IsGreaterThan Class Reference
Public Member Functions
IsGreaterThan (int threshold)
bool operator() (int n) const
IsGreaterThan (int threshold)
bool operator() (int n) const
IsGreaterThan (int threshold)
bool operator() (int n) const
Private Attributes
int threshold_
Detailed Description
Definition at line 2441 of file gmock-matchers_test.cc.
Constructor & Destructor Documentation
testing::gmock_matchers_test::IsGreaterThan::IsGreaterThan (int threshold) inline explicit
Definition at line 2443 of file gmock-matchers_test.cc.
 : threshold_(threshold) {}
testing::gmock_matchers_test::IsGreaterThan::IsGreaterThan (int threshold) inline explicit
Definition at line 2443 of file gmock-matchers_test.cc.
 : threshold_(threshold) {}
testing::gmock_matchers_test::IsGreaterThan::IsGreaterThan (int threshold) inline explicit
Definition at line 2443 of file gmock-matchers_test.cc.
 : threshold_(threshold) {}
Member Function Documentation
bool testing::gmock_matchers_test::IsGreaterThan::operator() (int n) const inline
Definition at line 2445 of file gmock-matchers_test.cc.
 { return n > threshold_; }
bool testing::gmock_matchers_test::IsGreaterThan::operator() (int n) const inline
Definition at line 2445 of file gmock-matchers_test.cc.
References EXPECT_FALSE, EXPECT_TRUE, testing::gmock_matchers_test::IsPositive(), testing::internal::MatcherBase< T >::Matches(), testing::gmock_matchers_test::ReferencesFooAndIsZero(), testing::internal::TEST(), and testing::Truly().
 { return n > threshold_; }
bool testing::gmock_matchers_test::IsGreaterThan::operator() (int n) const inline
Definition at line 2445 of file gmock-matchers_test.cc.
References EXPECT_FALSE, EXPECT_TRUE, testing::gmock_matchers_test::IsPositive(), testing::internal::MatcherBase< T >::Matches(), testing::gmock_matchers_test::ReferencesFooAndIsZero(), testing::internal::TEST(), and testing::Truly().
 { return n > threshold_; }
Member Data Documentation
int testing::gmock_matchers_test::IsGreaterThan::threshold_ private
Definition at line 2448 of file gmock-matchers_test.cc.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-matchers_test.cc