proxygen: folly::io::test::CompressionTest Class Reference
folly::io::test::CompressionTest Class Reference
Protected Member Functions
void SetUp () override
void runSimpleIOBufTest (const DataHolder &dh)
void runSimpleStringTest (const DataHolder &dh)
Private Member Functions
std::unique_ptr< IOBuf > split (std::unique_ptr< IOBuf > data) const
Private Attributes
uint64_t uncompressedLength_
size_t chunks_
std::unique_ptr< Codec > codec_
Detailed Description
Definition at line 197 of file CompressionTest.cpp.
Member Function Documentation
void folly::io::test::CompressionTest::runSimpleIOBufTest (const DataHolder & dh) protected
Definition at line 221 of file CompressionTest.cpp.
References codec_, folly::io::test::DataHolder::data(), EXPECT_EQ, EXPECT_LE, folly::io::test::DataHolder::hash(), folly::io::test::hashIOBuf(), folly::split(), and folly::IOBuf::wrapBuffer().
{
   const auto original = split(IOBuf::wrapBuffer(dh.data(uncompressedLength_)));
   const auto compressed = split(codec_->compress(original.get()));
   EXPECT_LE(
       compressed->computeChainDataLength(),
       codec_->maxCompressedLength(uncompressedLength_));
   if (!codec_->needsUncompressedLength()) {
     auto uncompressed = codec_->uncompress(compressed.get());
     EXPECT_EQ(uncompressedLength_, uncompressed->computeChainDataLength());
     EXPECT_EQ(dh.hash(uncompressedLength_), hashIOBuf(uncompressed.get()));
   }
   {
     auto uncompressed =
         codec_->uncompress(compressed.get(), uncompressedLength_);
     EXPECT_EQ(uncompressedLength_, uncompressed->computeChainDataLength());
     EXPECT_EQ(dh.hash(uncompressedLength_), hashIOBuf(uncompressed.get()));
   }
 }
void folly::io::test::CompressionTest::runSimpleStringTest (const DataHolder & dh) protected
Definition at line 240 of file CompressionTest.cpp.
References codec_, folly::io::test::DataHolder::data(), folly::Range< Iter >::data(), EXPECT_EQ, EXPECT_LE, and string.
{
   const auto original = std::string(
       reinterpret_cast<const char*>(dh.data(uncompressedLength_).data()),
       uncompressedLength_);
   const auto compressed = codec_->compress(original);
   EXPECT_LE(
       compressed.length(), codec_->maxCompressedLength(uncompressedLength_));
   if (!codec_->needsUncompressedLength()) {
     auto uncompressed = codec_->uncompress(compressed);
     EXPECT_EQ(uncompressedLength_, uncompressed.length());
     EXPECT_EQ(uncompressed, original);
   }
   {
     auto uncompressed = codec_->uncompress(compressed, uncompressedLength_);
     EXPECT_EQ(uncompressedLength_, uncompressed.length());
     EXPECT_EQ(uncompressed, original);
   }
 }
void folly::io::test::CompressionTest::SetUp () inline override protected
Definition at line 200 of file CompressionTest.cpp.
References codec_, folly::io::test::DataHolder::data(), folly::io::getCodec(), and folly::split().
{
     auto tup = GetParam();
     int lengthLog = std::get<0>(tup);
     // Small hack to test empty data
     uncompressedLength_ = (lengthLog < 0) ? 0 : uint64_t(1) << std::get<0>(tup);
     chunks_ = std::get<1>(tup);
     codec_ = getCodec(std::get<2>(tup));
   }
std::unique_ptr< IOBuf > folly::io::test::CompressionTest::split (std::unique_ptr< IOBuf > data) const private
Definition at line 261 of file CompressionTest.cpp.
References folly::IOBufQueue::append(), folly::IOBuf::copyBuffer(), i, folly::IOBufQueue::move(), folly::Random::rand64(), folly::size(), and folly::split().
{
   if (data->isChained()) {
     data->coalesce();
   }
   const size_t size = data->computeChainDataLength();
   std::multiset<size_t> splits;
   for (size_t i = 1; i < chunks_; ++i) {
     splits.insert(Random::rand64(size));
   }
   folly::IOBufQueue result;
   size_t offset = 0;
   for (size_t split : splits) {
     result.append(IOBuf::copyBuffer(data->data() + offset, split - offset));
     offset = split;
   }
   result.append(IOBuf::copyBuffer(data->data() + offset, size - offset));
   return result.move();
 }
Member Data Documentation
size_t folly::io::test::CompressionTest::chunks_ private
Definition at line 217 of file CompressionTest.cpp.
std::unique_ptr<Codec> folly::io::test::CompressionTest::codec_ private
Definition at line 218 of file CompressionTest.cpp.
uint64_t folly::io::test::CompressionTest::uncompressedLength_ private
Definition at line 216 of file CompressionTest.cpp.
The documentation for this class was generated from the following file:
proxygen/folly/folly/compression/test/CompressionTest.cpp