proxygen: testing::gmock_more_actions_test::DeletionTester Class Reference
testing::gmock_more_actions_test::DeletionTester Class Reference
Public Member Functions
DeletionTester (bool *is_deleted)
~DeletionTester ()
DeletionTester (bool *is_deleted)
~DeletionTester ()
DeletionTester (bool *is_deleted)
~DeletionTester ()
Private Attributes
bool * is_deleted_
Detailed Description
Definition at line 563 of file gmock-more-actions_test.cc.
Constructor & Destructor Documentation
testing::gmock_more_actions_test::DeletionTester::DeletionTester (bool * is_deleted) inline explicit
Definition at line 565 of file gmock-more-actions_test.cc.
     : is_deleted_(is_deleted) {
     // Make sure the bit is set to false.
     *is_deleted_ = false;
   }
testing::gmock_more_actions_test::DeletionTester::~DeletionTester () inline
Definition at line 571 of file gmock-more-actions_test.cc.
                     {
     *is_deleted_ = true;
   }
testing::gmock_more_actions_test::DeletionTester::DeletionTester (bool * is_deleted) inline explicit
Definition at line 565 of file gmock-more-actions_test.cc.
     : is_deleted_(is_deleted) {
     // Make sure the bit is set to false.
     *is_deleted_ = false;
   }
testing::gmock_more_actions_test::DeletionTester::~DeletionTester () inline
Definition at line 571 of file gmock-more-actions_test.cc.
References ch, testing::gmock_more_actions_test::CharPtr(), EXPECT_EQ, EXPECT_FALSE, EXPECT_THROW, EXPECT_TRUE, std::tr1::make_tuple(), testing::gtest_printers_test::MyFunction(), testing::Action< F >::Perform(), s, string, folly::pushmi::detail::t, and testing::gmock_more_actions_test::TEST().
                     {
     *is_deleted_ = true;
   }
testing::gmock_more_actions_test::DeletionTester::DeletionTester (bool * is_deleted) inline explicit
Definition at line 565 of file gmock-more-actions_test.cc.
     : is_deleted_(is_deleted) {
     // Make sure the bit is set to false.
     *is_deleted_ = false;
   }
testing::gmock_more_actions_test::DeletionTester::~DeletionTester () inline
Definition at line 571 of file gmock-more-actions_test.cc.
References ch, testing::gmock_more_actions_test::CharPtr(), EXPECT_EQ, EXPECT_FALSE, EXPECT_THROW, EXPECT_TRUE, std::tr1::make_tuple(), testing::gtest_printers_test::MyFunction(), testing::Action< F >::Perform(), s, string, folly::pushmi::detail::t, and testing::gmock_more_actions_test::TEST().
                     {
     *is_deleted_ = true;
   }
Member Data Documentation
bool * testing::gmock_more_actions_test::DeletionTester::is_deleted_ private
Definition at line 576 of file gmock-more-actions_test.cc.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-more-actions_test.cc