proxygen: folly::StandardLogHandlerFactory::OptionProcessor Class Reference
folly::StandardLogHandlerFactory::OptionProcessor Class Reference abstract
#include <StandardLogHandlerFactory.h>
Public Member Functions
virtual ~OptionProcessor ()
virtual bool processOption (StringPiece name, StringPiece value)=0
Detailed Description
Definition at line 39 of file StandardLogHandlerFactory.h.
Constructor & Destructor Documentation
virtual folly::StandardLogHandlerFactory::OptionProcessor::~OptionProcessor () inline virtual
Definition at line 41 of file StandardLogHandlerFactory.h.
References name, processOption(), and folly::value().
 {}
Member Function Documentation
virtual bool folly::StandardLogHandlerFactory::OptionProcessor::processOption (StringPiece name, StringPiece value) pure virtual
Process an option.
This should return true if the option was processed successfully, or false if this is an unknown option name. It should throw an exception if the option name is known but there is a problem with the value.
Implemented in folly::TestHandlerFactory::TestWriterFactory, folly::StreamHandlerFactory::WriterFactory, and folly::FileHandlerFactory::WriterFactory.
Referenced by folly::StandardLogHandlerFactory::createHandler(), and ~OptionProcessor().
The documentation for this class was generated from the following file:
proxygen/folly/folly/logging/StandardLogHandlerFactory.h