proxygen: folly::HazptrLockFreeLIFO< T, Atom > Class Template Reference
folly::HazptrLockFreeLIFO< T, Atom > Class Template Reference
#include <HazptrLockFreeLIFO.h>
Classes
struct Node
Public Member Functions
HazptrLockFreeLIFO ()
~HazptrLockFreeLIFO ()
void push (T val)
bool pop (T &val)
Private Member Functions
Node * head ()
bool cas_head (Node *&expected, Node *newval)
Private Attributes
Atom< Node * > head_
Detailed Description
template<typename T, template< typename > class Atom = std::atomic>
class folly::HazptrLockFreeLIFO< T, Atom >
Definition at line 23 of file HazptrLockFreeLIFO.h.
Constructor & Destructor Documentation
template<typename T, template< typename > class Atom = std::atomic> folly::HazptrLockFreeLIFO< T, Atom >::HazptrLockFreeLIFO () inline
Definition at line 29 of file HazptrLockFreeLIFO.h.
 : head_(nullptr) {}
template<typename T, template< typename > class Atom = std::atomic> folly::HazptrLockFreeLIFO< T, Atom >::~HazptrLockFreeLIFO () inline
Definition at line 31 of file HazptrLockFreeLIFO.h.
References folly::HazptrLockFreeLIFO< T, Atom >::head(), cpp.ast::next(), folly::HazptrLockFreeLIFO< T, Atom >::Node::next(), and folly::hazptr_obj_base< T, Atom, D >::retire().
{
     Node* next;
     for (auto node = head(); node; node = next) {
       next = node->next();
       node->retire();
     }
     hazptr_cleanup<Atom>();
   }
Member Function Documentation
template<typename T, template< typename > class Atom = std::atomic> bool folly::HazptrLockFreeLIFO< T, Atom >::cas_head (Node *& expected, Node * newval) inline private
Definition at line 72 of file HazptrLockFreeLIFO.h.
Referenced by folly::HazptrLockFreeLIFO< T, Atom >::pop(), and folly::HazptrLockFreeLIFO< T, Atom >::push().
{
     return head_.compare_exchange_weak(
         expected, newval, std::memory_order_acq_rel, std::memory_order_acquire);
   }
template<typename T, template< typename > class Atom = std::atomic> Node* folly::HazptrLockFreeLIFO< T, Atom >::head () inline private
Definition at line 68 of file HazptrLockFreeLIFO.h.
Referenced by folly::HazptrLockFreeLIFO< T, Atom >::push(), and folly::HazptrLockFreeLIFO< T, Atom >::~HazptrLockFreeLIFO().
                {
     return head_.load(std::memory_order_acquire);
   }
template<typename T, template< typename > class Atom = std::atomic> bool folly::HazptrLockFreeLIFO< T, Atom >::pop (T & val) inline
Definition at line 47 of file HazptrLockFreeLIFO.h.
References folly::HazptrLockFreeLIFO< T, Atom >::cas_head(), folly::hazptr_holder< Atom >::get_protected(), h, cpp.ast::next(), folly::HazptrLockFreeLIFO< T, Atom >::Node::next(), folly::hazptr_holder< Atom >::reset(), folly::hazptr_obj_base< T, Atom, D >::retire(), and folly::HazptrLockFreeLIFO< T, Atom >::Node::value().
Referenced by lifo_test().
                    {
     hazptr_local<1, Atom> h;
     hazptr_holder<Atom>& hptr = h[0];
     Node* node;
     while (true) {
       node = hptr.get_protected(head_);
       if (node == nullptr) {
         return false;
       }
       auto next = node->next();
       if (cas_head(node, next)) {
         break;
       }
     }
     hptr.reset();
     val = node->value();
     node->retire();
     return true;
   }
template<typename T, template< typename > class Atom = std::atomic> void folly::HazptrLockFreeLIFO< T, Atom >::push (T val) inline
Definition at line 40 of file HazptrLockFreeLIFO.h.
References folly::HazptrLockFreeLIFO< T, Atom >::cas_head(), folly::HazptrLockFreeLIFO< T, Atom >::head(), and Node< Atom >::Node().
Referenced by lifo_test().
                    {
     auto node = new Node(val, head());
     while (!cas_head(node->next_, node)) {
       /* try again */;
     }
   }
Member Data Documentation
template<typename T, template< typename > class Atom = std::atomic> Atom<Node*> folly::HazptrLockFreeLIFO< T, Atom >::head_ private
Definition at line 24 of file HazptrLockFreeLIFO.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/synchronization/example/HazptrLockFreeLIFO.h