proxygen: folly::symbolizer::Dwarf::Section Class Reference
folly::symbolizer::Dwarf::Section Class Reference
Public Member Functions
Section ()
Section (folly::StringPiece d)
bool next (folly::StringPiece &chunk)
bool is64Bit () const
Private Attributes
bool is64Bit_
folly::StringPiece data_
Detailed Description
Definition at line 151 of file Dwarf.h.
Constructor & Destructor Documentation
folly::symbolizer::Dwarf::Section::Section () inline
Definition at line 153 of file Dwarf.h.
References cpp.ast::next().
 : is64Bit_(false) {}
folly::symbolizer::Dwarf::Section::Section (folly::StringPiece d) explicit
Definition at line 36 of file Dwarf.cpp.
References folly::Range< Iter >::advance(), folly::Range< Iter >::assign(), folly::Range< Iter >::data(), folly::Range< Iter >::empty(), folly::Range< Iter >::end(), FOLLY_SAFE_CHECK, int64_t, is64Bit(), fizz::detail::read(), folly::Range< Iter >::removePrefix(), folly::Range< Iter >::removeSuffix(), folly::Range< Iter >::size(), start, folly::Range< Iter >::startsWith(), folly::T, type, uint64_t, uint8_t, val, value, and x.
 : is64Bit_(false), data_(d) {}
Member Function Documentation
bool folly::symbolizer::Dwarf::Section::is64Bit () const inline
Definition at line 162 of file Dwarf.h.
Referenced by folly::symbolizer::Dwarf::findDebugInfoOffset(), folly::symbolizer::Dwarf::findLocation(), folly::symbolizer::Dwarf::LineNumberVM::LineNumberVM(), and Section().
{
       return is64Bit_;
     }
bool folly::symbolizer::Dwarf::Section::next (folly::StringPiece & chunk)
Definition at line 284 of file Dwarf.cpp.
References folly::Range< Iter >::data(), data_, folly::Range< Iter >::empty(), folly::Range< Iter >::end(), FOLLY_SAFE_CHECK, folly::Range< Iter >::reset(), folly::Range< Iter >::size(), and uint32_t.
Referenced by folly::symbolizer::Dwarf::findDebugInfoOffset(), folly::symbolizer::Dwarf::findLocation(), and folly::symbolizer::Dwarf::LineNumberVM::LineNumberVM().
{
   chunk = data_;
   if (chunk.empty()) {
     return false;
   }
   // Initial length is a uint32_t value for a 32-bit section, and
   // a 96-bit value (0xffffffff followed by the 64-bit length) for a 64-bit
   // section.
   auto initialLength = read<uint32_t>(chunk);
   is64Bit_ = (initialLength == (uint32_t)-1);
   auto length = is64Bit_ ? read<uint64_t>(chunk) : initialLength;
   FOLLY_SAFE_CHECK(length <= chunk.size(), "invalid DWARF section");
   chunk.reset(chunk.data(), length);
   data_.assign(chunk.end(), data_.end());
   return true;
 }
Member Data Documentation
folly::StringPiece folly::symbolizer::Dwarf::Section::data_ private
Definition at line 169 of file Dwarf.h.
bool folly::symbolizer::Dwarf::Section::is64Bit_ private
Definition at line 168 of file Dwarf.h.
The documentation for this class was generated from the following files:
proxygen/folly/folly/experimental/symbolizer/Dwarf.h
proxygen/folly/folly/experimental/symbolizer/Dwarf.cpp