proxygen: folly::detail::TypeDescriptorHasher Class Reference
folly::detail::TypeDescriptorHasher Class Reference
#include <Singleton.h>
Public Member Functions
size_t operator() (const TypeDescriptor &ti) const
Detailed Description
Definition at line 219 of file Singleton.h.
Member Function Documentation
size_t folly::detail::TypeDescriptorHasher::operator() (const TypeDescriptor & ti) const inline
Definition at line 221 of file Singleton.h.
References folly::hash::hash_combine(), ptr, folly::detail::singletonPrintDestructionStackTrace(), folly::detail::singletonThrowGetInvokedAfterDestruction(), folly::detail::singletonThrowNullCreator(), folly::detail::singletonWarnCreateBeforeRegistrationCompleteAndAbort(), folly::detail::singletonWarnCreateCircularDependencyAndAbort(), folly::detail::singletonWarnCreateUnregisteredAndAbort(), folly::detail::singletonWarnDestroyInstanceLeak(), folly::detail::singletonWarnLeakyDoubleRegistrationAndAbort(), folly::detail::singletonWarnLeakyInstantiatingNotRegisteredAndAbort(), folly::detail::singletonWarnRegisterMockEarlyAndAbort(), folly::detail::TypeDescriptor::tag_ti_, folly::detail::TypeDescriptor::ti_, and type.
{
     return folly::hash::hash_combine(ti.ti_, ti.tag_ti_);
   }
The documentation for this class was generated from the following file:
proxygen/folly/folly/Singleton.h