proxygen: testing::gmock_generated_actions_test::UnaryConstructorClass Class Reference
testing::gmock_generated_actions_test::UnaryConstructorClass Class Reference
Public Member Functions
UnaryConstructorClass (int value)
UnaryConstructorClass (int value)
UnaryConstructorClass (int value)
Public Attributes
int value_
Detailed Description
Definition at line 1021 of file gmock-generated-actions_test.cc.
Constructor & Destructor Documentation
testing::gmock_generated_actions_test::UnaryConstructorClass::UnaryConstructorClass (int value) inline explicit
Definition at line 1023 of file gmock-generated-actions_test.cc.
 : value_(value) {}
testing::gmock_generated_actions_test::UnaryConstructorClass::UnaryConstructorClass (int value) inline explicit
Definition at line 1023 of file gmock-generated-actions_test.cc.
References c, EXPECT_EQ, std::tr1::make_tuple(), testing::Action< F >::Perform(), testing::gmock_generated_actions_test::TEST(), and testing::gmock_generated_actions_test::Unary().
 : value_(value) {}
testing::gmock_generated_actions_test::UnaryConstructorClass::UnaryConstructorClass (int value) inline explicit
Definition at line 1023 of file gmock-generated-actions_test.cc.
References c, EXPECT_EQ, std::tr1::make_tuple(), testing::Action< F >::Perform(), testing::gmock_generated_actions_test::TEST(), and testing::gmock_generated_actions_test::Unary().
 : value_(value) {}
Member Data Documentation
int testing::gmock_generated_actions_test::UnaryConstructorClass::value_
Definition at line 1024 of file gmock-generated-actions_test.cc.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-generated-actions_test.cc