proxygen: testing::internal::UnitTestRecordPropertyTestHelper Class Reference
testing::internal::UnitTestRecordPropertyTestHelper Class Reference
Protected Member Functions
UnitTestRecordPropertyTestHelper ()
void UnitTestRecordProperty (const char *key, const std::string &value)
UnitTestRecordPropertyTestHelper ()
void UnitTestRecordProperty (const char *key, const std::string &value)
UnitTestRecordPropertyTestHelper ()
void UnitTestRecordProperty (const char *key, const std::string &value)
Protected Member Functions inherited from testing::Test
Test ()
virtual void SetUp ()
virtual void TearDown ()
Test ()
virtual void SetUp ()
virtual void TearDown ()
Test ()
virtual void SetUp ()
virtual void TearDown ()
Protected Attributes
UnitTest unit_test_
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Detailed Description
Definition at line 184 of file gtest_unittest.cc.
Constructor & Destructor Documentation
testing::internal::UnitTestRecordPropertyTestHelper::UnitTestRecordPropertyTestHelper () inline protected
Definition at line 186 of file gtest_unittest.cc.
 {}
testing::internal::UnitTestRecordPropertyTestHelper::UnitTestRecordPropertyTestHelper () inline protected
Definition at line 186 of file gtest_unittest.cc.
 {}
testing::internal::UnitTestRecordPropertyTestHelper::UnitTestRecordPropertyTestHelper () inline protected
Definition at line 186 of file gtest_unittest.cc.
 {}
Member Function Documentation
void testing::internal::UnitTestRecordPropertyTestHelper::UnitTestRecordProperty (const char * key, const std::string & value) inline protected
Definition at line 189 of file gtest_unittest.cc.
{
     unit_test_.RecordProperty(key, value);
   }
void testing::internal::UnitTestRecordPropertyTestHelper::UnitTestRecordProperty (const char * key, const std::string & value) inline protected
Definition at line 189 of file gtest_unittest.cc.
References testing::internal::AlwaysFalse(), testing::internal::AlwaysTrue(), testing::internal::AppendUserMessage(), testing::internal::ArrayAwareFind(), testing::internal::ArrayEq(), testing::AssertionFailure(), testing::AssertionSuccess(), testing::internal::edit_distance::CalculateOptimalEdits(), testing::internal::CaptureStdout(), testing::internal::CodePointToUtf8(), testing::internal::CopyArray(), testing::internal::CountIf(), testing::internal::edit_distance::CreateUnifiedDiff(), testing::DoubleLE(), testing::internal::EqFailure(), folly::pushmi::operators::filter, testing::FloatLE(), testing::internal::ForEach(), testing::internal::FormatEpochTimeInMillisAsIso8601(), testing::internal::FormatTimeInMillisAsSeconds(), testing::internal::GetCapturedStdout(), testing::internal::GetCurrentOsStackTraceExceptTop(), testing::internal::GetElementOr(), testing::internal::GetNextRandomSeed(), testing::internal::GetRandomSeedFromFlag(), testing::internal::GetTestTypeId(), testing::internal::GetTimeInMillis(), testing::internal::GetTypeId(), testing::internal::GetUnitTestImpl(), GTEST_FLAG, testing::internal::Int32FromEnvOrDie(), testing::internal::IsContainerTest(), testing::IsNotSubstring(), testing::IsSubstring(), testing::internal::kMaxRandomSeed, testing::kMaxStackTraceDepth, testing::internal::kTestTypeIdInGoogleTest, gmock_output_test::output, testing::internal::ParseInt32Flag(), repeat(), testing::internal::ShouldRunTestOnShard(), testing::internal::ShouldShard(), testing::internal::ShouldUseColor(), testing::internal::Shuffle(), testing::internal::ShuffleRange(), testing::internal::SkipPrefix(), testing::StaticAssertTypeEq(), testing::internal::StreamableToString(), gmock_test_utils::TestCase, and testing::internal::WideStringToUtf8().
{
     unit_test_.RecordProperty(key, value);
   }
void testing::internal::UnitTestRecordPropertyTestHelper::UnitTestRecordProperty (const char * key, const std::string & value) inline protected
Definition at line 189 of file gtest_unittest.cc.
References testing::internal::AlwaysFalse(), testing::internal::AlwaysTrue(), testing::internal::AppendUserMessage(), testing::internal::ArrayAwareFind(), testing::internal::ArrayEq(), testing::AssertionFailure(), testing::AssertionSuccess(), testing::internal::edit_distance::CalculateOptimalEdits(), testing::internal::CaptureStdout(), testing::internal::CodePointToUtf8(), testing::internal::CopyArray(), testing::internal::CountIf(), testing::internal::edit_distance::CreateUnifiedDiff(), testing::DoubleLE(), testing::internal::EqFailure(), folly::pushmi::operators::filter, testing::FloatLE(), testing::internal::ForEach(), testing::internal::FormatEpochTimeInMillisAsIso8601(), testing::internal::FormatTimeInMillisAsSeconds(), testing::internal::GetCapturedStdout(), testing::internal::GetCurrentOsStackTraceExceptTop(), testing::internal::GetElementOr(), testing::internal::GetNextRandomSeed(), testing::internal::GetRandomSeedFromFlag(), testing::internal::GetTestTypeId(), testing::internal::GetTimeInMillis(), testing::internal::GetTypeId(), testing::internal::GetUnitTestImpl(), GTEST_FLAG, testing::internal::Int32FromEnvOrDie(), testing::internal::IsContainerTest(), testing::IsNotSubstring(), testing::IsSubstring(), testing::internal::kMaxRandomSeed, testing::kMaxStackTraceDepth, testing::internal::kTestTypeIdInGoogleTest, gmock_output_test::output, testing::internal::ParseInt32Flag(), repeat(), testing::internal::ShouldRunTestOnShard(), testing::internal::ShouldShard(), testing::internal::ShouldUseColor(), testing::internal::Shuffle(), testing::internal::ShuffleRange(), testing::internal::SkipPrefix(), testing::StaticAssertTypeEq(), testing::internal::StreamableToString(), gmock_test_utils::TestCase, and testing::internal::WideStringToUtf8().
{
     unit_test_.RecordProperty(key, value);
   }
Member Data Documentation
UnitTest testing::internal::UnitTestRecordPropertyTestHelper::unit_test_ protected
Definition at line 193 of file gtest_unittest.cc.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest_unittest.cc