proxygen: folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator Class Reference
folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator Class Reference
#include <ThreadLocal.h>
Public Types
using difference_type = ssize_t
using value_type = T
using reference = T const &
using pointer = T const *
using iterator_category = std::bidirectional_iterator_tag
Public Member Functions
Iterator & operator++ ()
Iterator & operator++ (int)
Iterator & operator-- ()
Iterator & operator-- (int)
T & operator* ()
T const & operator* () const
T * operator-> ()
T const * operator-> () const
bool operator== (Iterator const &rhs) const
bool operator!= (Iterator const &rhs) const
Private Member Functions
void increment ()
void decrement ()
const T & dereference () const
T & dereference ()
bool equal (const Iterator &other) const
Iterator (const Accessor *accessor)
bool valid () const
void incrementToValid ()
void decrementToValid ()
Private Attributes
const Accessor * accessor_
threadlocal_detail::ThreadEntryNode * e_
Friends
class Accessor
Detailed Description
template<class T, class Tag = void, class AccessMode = void>
class folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator
Definition at line 260 of file ThreadLocal.h.
Member Typedef Documentation
template<class T, class Tag = void, class AccessMode = void> using folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::difference_type = ssize_t
Definition at line 314 of file ThreadLocal.h.
template<class T, class Tag = void, class AccessMode = void> using folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::iterator_category = std::bidirectional_iterator_tag
Definition at line 318 of file ThreadLocal.h.
template<class T, class Tag = void, class AccessMode = void> using folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::pointer = T const*
Definition at line 317 of file ThreadLocal.h.
template<class T, class Tag = void, class AccessMode = void> using folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::reference = T const&
Definition at line 316 of file ThreadLocal.h.
template<class T, class Tag = void, class AccessMode = void> using folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::value_type = T
Definition at line 315 of file ThreadLocal.h.
Constructor & Destructor Documentation
template<class T, class Tag = void, class AccessMode = void> folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::Iterator (const Accessor * accessor) inline explicit private
Definition at line 289 of file ThreadLocal.h.
           : accessor_(accessor),
             e_(&accessor_->meta_.head_.elements[accessor_->id_].node) {}
Member Function Documentation
template<class T, class Tag = void, class AccessMode = void> void folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::decrement () inline private
Definition at line 270 of file ThreadLocal.h.
References folly::threadlocal_detail::ThreadEntryNode::getPrev().
{
         e_ = e_->getPrev();
         decrementToValid();
       }
template<class T, class Tag = void, class AccessMode = void> void folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::decrementToValid () inline private
Definition at line 306 of file ThreadLocal.h.
References folly::threadlocal_detail::ThreadEntry::elements, folly::threadlocal_detail::ThreadEntryNode::getPrev(), folly::threadlocal_detail::StaticMetaBase::head_, folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::id_, folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::meta_, and folly::threadlocal_detail::ElementWrapper::node.
{
         for (; e_ != &accessor_->meta_.head_.elements[accessor_->id_].node &&
              !valid();
              e_ = e_->getPrev()) {
         }
       }
template<class T, class Tag = void, class AccessMode = void> const T& folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::dereference () const inline private
Definition at line 275 of file ThreadLocal.h.
References folly::threadlocal_detail::ThreadEntry::elements, folly::threadlocal_detail::ThreadEntryNode::getThreadEntry(), folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::id_, folly::threadlocal_detail::ElementWrapper::ptr, and folly::T.
{
         return *static_cast<T*>(
             e_->getThreadEntry()->elements[accessor_->id_].ptr);
       }
template<class T, class Tag = void, class AccessMode = void> T& folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::dereference () inline private
Definition at line 280 of file ThreadLocal.h.
References folly::threadlocal_detail::ThreadEntry::elements, folly::threadlocal_detail::ThreadEntryNode::getThreadEntry(), folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::id_, folly::threadlocal_detail::ElementWrapper::ptr, and folly::T.
{
         return *static_cast<T*>(
             e_->getThreadEntry()->elements[accessor_->id_].ptr);
       }
template<class T, class Tag = void, class AccessMode = void> bool folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::equal (const Iterator & other) const inline private
Definition at line 285 of file ThreadLocal.h.
References folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::accessor_, folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::e_, and folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::id_.
{
         return (accessor_->id_ == other.accessor_->id_ && e_ == other.e_);
       }
template<class T, class Tag = void, class AccessMode = void> void folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::increment () inline private
Definition at line 265 of file ThreadLocal.h.
References folly::threadlocal_detail::ThreadEntryNode::getNext().
{
         e_ = e_->getNext();
         incrementToValid();
       }
template<class T, class Tag = void, class AccessMode = void> void folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::incrementToValid () inline private
Definition at line 299 of file ThreadLocal.h.
References folly::threadlocal_detail::ThreadEntry::elements, folly::threadlocal_detail::ThreadEntryNode::getNext(), folly::threadlocal_detail::StaticMetaBase::head_, folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::id_, folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::meta_, and folly::threadlocal_detail::ElementWrapper::node.
{
         for (; e_ != &accessor_->meta_.head_.elements[accessor_->id_].node &&
              !valid();
              e_ = e_->getNext()) {
         }
       }
template<class T, class Tag = void, class AccessMode = void> bool folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::operator!= (Iterator const & rhs) const inline
Definition at line 362 of file ThreadLocal.h.
{
         return !equal(rhs);
       }
template<class T, class Tag = void, class AccessMode = void> T& folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::operator* () inline
Definition at line 342 of file ThreadLocal.h.
References folly::gen::dereference.
                      {
         return dereference();
       }
template<class T, class Tag = void, class AccessMode = void> T const& folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::operator* () const inline
Definition at line 346 of file ThreadLocal.h.
References folly::gen::dereference.
{
         return dereference();
       }
template<class T, class Tag = void, class AccessMode = void> Iterator& folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::operator++ () inline
Definition at line 320 of file ThreadLocal.h.
{
         increment();
         return *this;
       }
template<class T, class Tag = void, class AccessMode = void> Iterator& folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::operator++ (int) inline
Definition at line 325 of file ThreadLocal.h.
References folly::copy().
{
         Iterator copy(*this);
         increment();
         return copy;
       }
template<class T, class Tag = void, class AccessMode = void> Iterator& folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::operator-- () inline
Definition at line 331 of file ThreadLocal.h.
{
         decrement();
         return *this;
       }
template<class T, class Tag = void, class AccessMode = void> Iterator& folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::operator-- (int) inline
Definition at line 336 of file ThreadLocal.h.
References folly::copy().
{
         Iterator copy(*this);
         decrement();
         return copy;
       }
template<class T, class Tag = void, class AccessMode = void> T* folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::operator-> () inline
Definition at line 350 of file ThreadLocal.h.
References folly::gen::dereference.
                       {
         return &dereference();
       }
template<class T, class Tag = void, class AccessMode = void> T const* folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::operator-> () const inline
Definition at line 354 of file ThreadLocal.h.
References folly::gen::dereference.
{
         return &dereference();
       }
template<class T, class Tag = void, class AccessMode = void> bool folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::operator== (Iterator const & rhs) const inline
Definition at line 358 of file ThreadLocal.h.
{
         return equal(rhs);
       }
template<class T, class Tag = void, class AccessMode = void> bool folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::valid () const inline private
Definition at line 295 of file ThreadLocal.h.
References folly::threadlocal_detail::ThreadEntry::elements, folly::threadlocal_detail::ThreadEntryNode::getThreadEntry(), folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::id_, and folly::threadlocal_detail::ElementWrapper::ptr.
{
         return (e_->getThreadEntry()->elements[accessor_->id_].ptr);
       }
Friends And Related Function Documentation
template<class T, class Tag = void, class AccessMode = void> friend class Accessor friend
Definition at line 261 of file ThreadLocal.h.
Member Data Documentation
template<class T, class Tag = void, class AccessMode = void> const Accessor* folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::accessor_ private
Definition at line 262 of file ThreadLocal.h.
Referenced by folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::equal().
template<class T, class Tag = void, class AccessMode = void> threadlocal_detail::ThreadEntryNode* folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::e_ private
Definition at line 263 of file ThreadLocal.h.
Referenced by folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::equal().
The documentation for this class was generated from the following file:
proxygen/folly/folly/ThreadLocal.h