proxygen: fizz::tool::TerminalInputHandler Class Reference
fizz::tool::TerminalInputHandler Class Reference
#include <FizzCommandCommon.h>
Public Member Functions
TerminalInputHandler (folly::EventBase *evb, InputHandlerCallback *cb)
void handlerReady (uint16_t events) noexceptoverride
Public Member Functions inherited from folly::EventHandler
EventHandler (EventBase *eventBase, int fd)
EventHandler (EventBase *eventBase=nullptr, NetworkSocket fd=NetworkSocket())
virtual ~EventHandler ()
bool registerHandler (uint16_t events)
void unregisterHandler ()
bool isHandlerRegistered () const
void attachEventBase (EventBase *eventBase)
void detachEventBase ()
void changeHandlerFD (int fd)
void changeHandlerFD (NetworkSocket fd)
void initHandler (EventBase *eventBase, int fd)
void initHandler (EventBase *eventBase, NetworkSocket fd)
uint16_t getRegisteredEvents () const
bool registerInternalHandler (uint16_t events)
bool isPending () const
Private Member Functions
void hitEOF ()
Private Attributes
InputHandlerCallback * cb_
folly::EventBase * evb_
Additional Inherited Members
Public Types inherited from folly::EventHandler
enum EventFlags {
NONE = 0, READ = EV_READ, WRITE = EV_WRITE, READ_WRITE = (READ | WRITE),
PERSIST = EV_PERSIST
}
Detailed Description
Definition at line 70 of file FizzCommandCommon.h.
Constructor & Destructor Documentation
fizz::tool::TerminalInputHandler::TerminalInputHandler (folly::EventBase * evb, InputHandlerCallback * cb) explicit
Definition at line 49 of file FizzCommandCommon.cpp.
References folly::EventHandler::registerHandler().
     : EventHandler(evb, 0), cb_(cb), evb_(evb) {
   registerHandler(EventHandler::READ | EventHandler::PERSIST);
 }
Member Function Documentation
void fizz::tool::TerminalInputHandler::handlerReady (uint16_t events) override virtual noexcept
handlerReady() is invoked when the handler is ready.
Parameters
events A bitset indicating the events that are ready.
Implements folly::EventHandler.
Definition at line 56 of file FizzCommandCommon.cpp.
References cb_, fizz::tool::InputHandlerCallback::connected(), folly::errnoStr(), hitEOF(), fizz::detail::read(), and fizz::tool::InputHandlerCallback::write().
{
   // Handle read ready on stdin, but only once we're connected.
   if (events & EventHandler::READ && cb_->connected()) {
     std::array<char, 512> buf;
     int result = read(0, buf.data(), buf.size());
     if (result > 0) {
       cb_->write(IOBuf::wrapBuffer(buf.data(), result));
     } else {
       if (result < 0) {
         LOG(ERROR) << "Error on terminal read: " << folly::errnoStr(errno);
       }
       hitEOF();
     }
   }
 }
void fizz::tool::TerminalInputHandler::hitEOF () private
Definition at line 73 of file FizzCommandCommon.cpp.
References cb_, fizz::tool::InputHandlerCallback::close(), evb_, and folly::EventBase::runInLoop().
Referenced by handlerReady().
{
   evb_->runInLoop([cb_ = cb_]() { cb_->close(); });
 }
Member Data Documentation
InputHandlerCallback* fizz::tool::TerminalInputHandler::cb_ private
Definition at line 80 of file FizzCommandCommon.h.
Referenced by handlerReady(), and hitEOF().
folly::EventBase* fizz::tool::TerminalInputHandler::evb_ private
Definition at line 81 of file FizzCommandCommon.h.
Referenced by hitEOF().
The documentation for this class was generated from the following files:
proxygen/fizz/fizz/tool/FizzCommandCommon.h
proxygen/fizz/fizz/tool/FizzCommandCommon.cpp