proxygen: folly::settings::Snapshot Class Reference
folly::settings::Snapshot Class Reference final
#include <Settings.h>
Public Member Functions
template<class T , std::atomic< uint64_t > * P>
detail::SnapshotSettingWrapper< T > operator() (detail::SettingWrapper< T, P > &&setting)
Snapshot ()=default
void publish () override
bool setFromString (StringPiece settingName, StringPiece newValue, StringPiece reason) override
Optional< SettingsInfo > getAsString (StringPiece settingName) const override
bool resetToDefault (StringPiece settingName) override
void forEachSetting (const std::function< void(const SettingMetadata &, StringPiece, StringPiece)> &func) const override
Friends
template<typename T >
class detail::SnapshotSettingWrapper
Detailed Description
Captures the current state of all setting values and allows updating multiple settings at once, with verification and rollback.
A single snapshot cannot be used concurrently from different threads. Multiple concurrent snapshots are safe. Passing a single snapshot from one thread to another is safe as long as the user properly synchronizes the handoff.
Example usage:
folly::settings::Snapshot snapshot; // FOLLY_SETTING(project, name) refers to the globally visible value // snapshot(FOLLY_SETTING(project, name)) refers to the value saved in the // snapshot FOLLY_SETTING(project, name).set(new_value); assert(*FOLLY_SETTING(project, name) == new_value); assert(*snapshot(FOLLY_SETTING(project, name)) == old_value);
snapshot(FOLLY_SETTING(project, name)).set(new_snapshot_value); assert(*FOLLY_SETTING(project, name) == new_value); assert(*snapshot(FOLLY_SETTING(project, name)) == new_snapshot_value);
// At this point we can discard the snapshot and forget new_snapshot_value, // or choose to publish: snapshot.publish(); assert(*FOLLY_SETTING(project, name) == new_snapshot_value);
Definition at line 267 of file Settings.h.
Constructor & Destructor Documentation
folly::settings::Snapshot::Snapshot () default
Returns a snapshot of all current setting values. Global settings changes will not be visible in the snapshot, and vice versa.
Member Function Documentation
void folly::settings::Snapshot::forEachSetting (const std::function< void(const SettingMetadata &, StringPiece, StringPiece)> & func) const override
Iterates over all known settings and calls func(meta, to<string>(value), reason) for each.
Definition at line 95 of file Settings.cpp.
References map(), and folly::value().
Referenced by TEST().
                     {
   detail::SettingsMap map;
   /* Note that this won't hold the lock over the callback, which is
      what we want since the user might call other settings:: APIs */
   map = *detail::settingsMap().rlock();
   for (const auto& kv : map) {
     auto value = kv.second->getAsString(this);
     func(kv.second->meta(), value.first, value.second);
   }
 }
Optional< Snapshot::SettingsInfo > folly::settings::Snapshot::getAsString (StringPiece settingName) const override
Returns
If the setting exists, the current setting information. Empty Optional otherwise.
Definition at line 75 of file Settings.cpp.
References folly::none, and folly::Range< Iter >::str().
Referenced by TEST().
{
   auto mapPtr = detail::settingsMap().rlock();
   auto it = mapPtr->find(settingName.str());
   if (it == mapPtr->end()) {
     return none;
   }
   return it->second->getAsString(this);
 }
template<class T , std::atomic< uint64_t > * P> detail::SnapshotSettingWrapper<T> folly::settings::Snapshot::operator() (detail::SettingWrapper< T, P > && setting) inline
Wraps a global FOLLY_SETTING(a, b) and returns a snapshot-local wrapper.
Definition at line 273 of file Settings.h.
{
     return detail::SnapshotSettingWrapper<T>(*this, setting.core_);
   }
void folly::settings::Snapshot::publish () override
Apply all settings updates from this snapshot to the global state unconditionally.
Definition at line 176 of file Settings.cpp.
Referenced by TEST().
{
   for (auto& it : snapshotValues_) {
     it.second.publish();
   }
 }
bool folly::settings::Snapshot::resetToDefault (StringPiece settingName) override
Reset the value of the setting identified by name to its default value. The reason will be set to "default".
Returns
True if the setting was reset, false if the setting is not found.
Definition at line 85 of file Settings.cpp.
References folly::Range< Iter >::str().
Referenced by TEST().
{
   auto mapPtr = detail::settingsMap().rlock();
   auto it = mapPtr->find(settingName.str());
   if (it == mapPtr->end()) {
     return false;
   }
   it->second->resetToDefault(this);
   return true;
 }
bool folly::settings::Snapshot::setFromString (StringPiece settingName, StringPiece newValue, StringPiece reason) override
Look up a setting by name, and update the value from a string representation.
Returns
True if the setting was successfully updated, false if no setting with that name was found.
Exceptions
std::runtime_error If there's a conversion error.
Definition at line 62 of file Settings.cpp.
References folly::Range< Iter >::str().
Referenced by TEST().
{
   auto mapPtr = detail::settingsMap().rlock();
   auto it = mapPtr->find(settingName.str());
   if (it == mapPtr->end()) {
     return false;
   }
   it->second->setFromString(newValue, reason, this);
   return true;
 }
Friends And Related Function Documentation
template<typename T > friend class detail::SnapshotSettingWrapper friend
Definition at line 328 of file Settings.h.
The documentation for this class was generated from the following files:
proxygen/folly/folly/experimental/settings/Settings.h
proxygen/folly/folly/experimental/settings/Settings.cpp