proxygen: folly::RequestToken Class Reference
folly::RequestToken Class Reference
#include <Request.h>
Public Member Functions
RequestToken (const std::string &str)
bool operator== (const RequestToken &other) const
std::string getDebugString () const
Static Private Member Functions
static Synchronized< F14FastMap< std::string, uint32_t > > & getCache ()
Private Attributes
uint32_t token_
Friends
struct std::hash< folly::RequestToken >
Detailed Description
Definition at line 33 of file Request.h.
Constructor & Destructor Documentation
folly::RequestToken::RequestToken (const std::string & str) explicit
Definition at line 27 of file Request.cpp.
References c, getCache(), token_, and uint32_t.
Referenced by folly::RequestContext::clearContextData(), folly::RequestContext::doSetContextData(), folly::RequestContext::getContextData(), folly::RequestContext::hasContextData(), folly::RequestContext::overwriteContextData(), folly::RequestContext::setContextData(), and folly::RequestContext::setContextDataIfAbsent().
{
   auto& cache = getCache();
   {
     auto c = cache.rlock();
     auto res = c->find(str);
     if (res != c->end()) {
       token_ = res->second;
       return;
     }
   }
   auto c = cache.wlock();
   auto res = c->find(str);
   if (res != c->end()) {
     token_ = res->second;
     return;
   }
   static uint32_t nextToken{1};
   token_ = nextToken++;
   (*c)[str] = token_;
 }
Member Function Documentation
Synchronized< F14FastMap< std::string, uint32_t > > & folly::RequestToken::getCache () static private
Definition at line 60 of file Request.cpp.
Referenced by getDebugString(), and RequestToken().
{
   static Indestructible<Synchronized<F14FastMap<std::string, uint32_t>>> cache;
   return *cache;
 }
std::string folly::RequestToken::getDebugString () const
Definition at line 49 of file Request.cpp.
References c, getCache(), and token_.
Referenced by folly::RequestContext::doSetContextData(), and operator==().
{
   auto& cache = getCache();
   auto c = cache.rlock();
   for (auto& v : *c) {
     if (v.second == token_) {
       return v.first;
     }
   }
   throw std::logic_error("Could not find debug string in RequestToken");
 }
bool folly::RequestToken::operator== (const RequestToken & other) const inline
Definition at line 37 of file Request.h.
References getDebugString(), string, and token_.
{
     return token_ == other.token_;
   }
Friends And Related Function Documentation
friend struct std::hash< folly::RequestToken > friend
Definition at line 44 of file Request.h.
Member Data Documentation
uint32_t folly::RequestToken::token_ private
Definition at line 49 of file Request.h.
Referenced by getDebugString(), std::hash< folly::RequestToken >::operator()(), operator==(), and RequestToken().
The documentation for this class was generated from the following files:
proxygen/folly/folly/io/async/Request.h
proxygen/folly/folly/io/async/Request.cpp