proxygen: folly::Init Class Reference
folly::Init Class Reference
#include <Init.h>
Public Member Functions
FOLLY_NOINLINE Init (int *argc, char ***argv, bool removeFlags=true)
FOLLY_NOINLINE ~Init ()
Detailed Description
Definition at line 47 of file Init.h.
Constructor & Destructor Documentation
folly::Init::Init (int * argc, char *** argv, bool removeFlags = true)
Definition at line 62 of file Init.cpp.
References folly::init().
{
   init(argc, argv, removeFlags);
 }
folly::Init::~Init ()
Definition at line 66 of file Init.cpp.
References folly::SingletonVault::destroyInstances(), and folly::SingletonVault::singleton().
             {
   SingletonVault::singleton()->destroyInstances();
 }
The documentation for this class was generated from the following files:
proxygen/folly/folly/init/Init.h
proxygen/folly/folly/init/Init.cpp