proxygen: UDPAcceptor Class Reference
UDPAcceptor Class Reference
Public Member Functions
UDPAcceptor (EventBase *evb)
void onListenStarted () noexceptoverride
void onListenStopped () noexceptoverride
void onDataAvailable (std::shared_ptr< folly::AsyncUDPSocket > socket, const folly::SocketAddress &client, std::unique_ptr< folly::IOBuf > data, bool) noexceptoverride
UDPAcceptor (EventBase *evb, int n, bool changePortForWrites)
void onListenStarted () noexceptoverride
void onListenStopped () noexceptoverride
void onDataAvailable (std::shared_ptr< folly::AsyncUDPSocket > socket, const folly::SocketAddress &client, std::unique_ptr< folly::IOBuf > data, bool truncated) noexceptoverride
void sendPong (std::shared_ptr< folly::AsyncUDPSocket > socket) noexcept
Private Attributes
EventBase *const evb_ {nullptr}
const int n_ {-1}
bool changePortForWrites_ {true}
folly::SocketAddress lastClient_
std::string lastMsg_
Detailed Description
Definition at line 94 of file AsyncUDPSocketGSOTest.cpp.
Constructor & Destructor Documentation
UDPAcceptor::UDPAcceptor (EventBase * evb) inline
Definition at line 96 of file AsyncUDPSocketGSOTest.cpp.
 : evb_(evb) {}
UDPAcceptor::UDPAcceptor (EventBase * evb, int n, bool changePortForWrites) inline
Definition at line 42 of file AsyncUDPSocketTest.cpp.
       : evb_(evb), n_(n), changePortForWrites_(changePortForWrites) {}
Member Function Documentation
void UDPAcceptor::onDataAvailable (std::shared_ptr< folly::AsyncUDPSocket > socket, const folly::SocketAddress & client, std::unique_ptr< folly::IOBuf > data, bool truncated) inline override noexcept
Definition at line 49 of file AsyncUDPSocketTest.cpp.
References data, and folly::netops::socket().
{
     lastClient_ = client;
     lastMsg_ = data->clone()->moveToFbString().toStdString();
     auto len = data->computeChainDataLength();
     VLOG(4) << "Worker " << n_ << " read " << len << " bytes "
             << "(trun:" << truncated << ") from " << client.describe() << " - "
             << lastMsg_;
     sendPong(socket);
   }
void UDPAcceptor::onDataAvailable (std::shared_ptr< folly::AsyncUDPSocket > socket, const folly::SocketAddress & client, std::unique_ptr< folly::IOBuf > data, bool) inline override noexcept
Definition at line 102 of file AsyncUDPSocketGSOTest.cpp.
References folly::IOBuf::clone().
{
     // send pong
     socket->write(client, data->clone());
   }
void UDPAcceptor::onListenStarted () inline override noexcept
Definition at line 45 of file AsyncUDPSocketTest.cpp.
 {}
void UDPAcceptor::onListenStarted () inline override noexcept
Definition at line 98 of file AsyncUDPSocketGSOTest.cpp.
 {}
void UDPAcceptor::onListenStopped () inline override noexcept
Definition at line 47 of file AsyncUDPSocketTest.cpp.
 {}
void UDPAcceptor::onListenStopped () inline override noexcept
Definition at line 100 of file AsyncUDPSocketGSOTest.cpp.
 {}
void UDPAcceptor::sendPong (std::shared_ptr< folly::AsyncUDPSocket > socket) inline noexcept
Definition at line 65 of file AsyncUDPSocketTest.cpp.
References folly::IOBuf::copyBuffer(), evb_, and folly::netops::socket().
{
     try {
       auto writeSocket = socket;
       if (changePortForWrites_) {
         writeSocket = std::make_shared<folly::AsyncUDPSocket>(evb_);
         writeSocket->setReuseAddr(false);
         writeSocket->bind(folly::SocketAddress("127.0.0.1", 0));
       }
       writeSocket->write(lastClient_, folly::IOBuf::copyBuffer(lastMsg_));
     } catch (const std::exception& ex) {
       VLOG(4) << "Failed to send PONG " << ex.what();
     }
   }
Member Data Documentation
bool UDPAcceptor::changePortForWrites_ {true} private
Definition at line 83 of file AsyncUDPSocketTest.cpp.
EventBase *const UDPAcceptor::evb_ {nullptr} private
Definition at line 112 of file AsyncUDPSocketGSOTest.cpp.
folly::SocketAddress UDPAcceptor::lastClient_ private
Definition at line 85 of file AsyncUDPSocketTest.cpp.
std::string UDPAcceptor::lastMsg_ private
Definition at line 86 of file AsyncUDPSocketTest.cpp.
const int UDPAcceptor::n_ {-1} private
Definition at line 81 of file AsyncUDPSocketTest.cpp.
The documentation for this class was generated from the following files:
proxygen/folly/folly/io/async/test/AsyncUDPSocketGSOTest.cpp
proxygen/folly/folly/io/async/test/AsyncUDPSocketTest.cpp