proxygen: testing::Cardinality Class Reference
testing::Cardinality Class Reference
#include <gmock-cardinalities.h>
Public Member Functions
Cardinality ()
Cardinality (const CardinalityInterface *impl)
int ConservativeLowerBound () const
int ConservativeUpperBound () const
bool IsSatisfiedByCallCount (int call_count) const
bool IsSaturatedByCallCount (int call_count) const
bool IsOverSaturatedByCallCount (int call_count) const
void DescribeTo (::std::ostream *os) const
Cardinality ()
Cardinality (const CardinalityInterface *impl)
int ConservativeLowerBound () const
int ConservativeUpperBound () const
bool IsSatisfiedByCallCount (int call_count) const
bool IsSaturatedByCallCount (int call_count) const
bool IsOverSaturatedByCallCount (int call_count) const
void DescribeTo (::std::ostream *os) const
Cardinality ()
Cardinality (const CardinalityInterface *impl)
int ConservativeLowerBound () const
int ConservativeUpperBound () const
bool IsSatisfiedByCallCount (int call_count) const
bool IsSaturatedByCallCount (int call_count) const
bool IsOverSaturatedByCallCount (int call_count) const
void DescribeTo (::std::ostream *os) const
Static Public Member Functions
static void DescribeActualCallCountTo (int actual_call_count,::std::ostream *os)
static void DescribeActualCallCountTo (int actual_call_count,::std::ostream *os)
static void DescribeActualCallCountTo (int actual_call_count,::std::ostream *os)
Private Attributes
internal::linked_ptr< const CardinalityInterface > impl_
Detailed Description
Definition at line 83 of file gmock-cardinalities.h.
Constructor & Destructor Documentation
testing::Cardinality::Cardinality () inline
Definition at line 87 of file gmock-cardinalities.h.
 {}
testing::Cardinality::Cardinality (const CardinalityInterface * impl) inline explicit
Definition at line 90 of file gmock-cardinalities.h.
 : impl_(impl) {}
testing::Cardinality::Cardinality () inline
Definition at line 87 of file gmock-cardinalities.h.
 {}
testing::Cardinality::Cardinality (const CardinalityInterface * impl) inline explicit
Definition at line 90 of file gmock-cardinalities.h.
 : impl_(impl) {}
testing::Cardinality::Cardinality () inline
Definition at line 87 of file gmock-cardinalities.h.
 {}
testing::Cardinality::Cardinality (const CardinalityInterface * impl) inline explicit
Definition at line 90 of file gmock-cardinalities.h.
 : impl_(impl) {}
Member Function Documentation
int testing::Cardinality::ConservativeLowerBound () const inline
Definition at line 94 of file gmock-cardinalities.h.
Referenced by testing::internal::ExpectationBase::CheckActionCountIfNotDone().
 { return impl_->ConservativeLowerBound(); }
int testing::Cardinality::ConservativeLowerBound () const inline
Definition at line 94 of file gmock-cardinalities.h.
 { return impl_->ConservativeLowerBound(); }
int testing::Cardinality::ConservativeLowerBound () const inline
Definition at line 94 of file gmock-cardinalities.h.
 { return impl_->ConservativeLowerBound(); }
int testing::Cardinality::ConservativeUpperBound () const inline
Definition at line 95 of file gmock-cardinalities.h.
Referenced by testing::internal::ExpectationBase::CheckActionCountIfNotDone().
 { return impl_->ConservativeUpperBound(); }
int testing::Cardinality::ConservativeUpperBound () const inline
Definition at line 95 of file gmock-cardinalities.h.
 { return impl_->ConservativeUpperBound(); }
int testing::Cardinality::ConservativeUpperBound () const inline
Definition at line 95 of file gmock-cardinalities.h.
 { return impl_->ConservativeUpperBound(); }
static void testing::Cardinality::DescribeActualCallCountTo (int actual_call_count, ::std::ostream * os) static
void testing::Cardinality::DescribeActualCallCountTo (int actual_call_count, ::std::ostream * os) static
Definition at line 130 of file gmock-cardinalities.cc.
Referenced by testing::internal::ExpectationBase::DescribeCallCountTo().
{
   if (actual_call_count > 0) {
     *os << "called " << FormatTimes(actual_call_count);
   } else {
     *os << "never called";
   }
 }
static void testing::Cardinality::DescribeActualCallCountTo (int actual_call_count, ::std::ostream * os) static
void testing::Cardinality::DescribeTo (::std::ostream * os) const inline
Definition at line 115 of file gmock-cardinalities.h.
References testing::AnyNumber(), testing::AtLeast(), testing::AtMost(), testing::Between(), c, testing::Exactly(), GTEST_API_, testing::MakeCardinality(), max, and min.
 { impl_->DescribeTo(os); }
void testing::Cardinality::DescribeTo (::std::ostream * os) const inline
Definition at line 115 of file gmock-cardinalities.h.
References testing::AnyNumber(), testing::AtLeast(), testing::AtMost(), testing::Between(), c, testing::Exactly(), GTEST_API_, testing::MakeCardinality(), max, and min.
 { impl_->DescribeTo(os); }
void testing::Cardinality::DescribeTo (::std::ostream * os) const inline
Definition at line 115 of file gmock-cardinalities.h.
Referenced by testing::internal::ExpectationBase::CheckActionCountIfNotDone(), and testing::internal::ExpectationBase::DescribeCallCountTo().
 { impl_->DescribeTo(os); }
bool testing::Cardinality::IsOverSaturatedByCallCount (int call_count) const inline
Definition at line 109 of file gmock-cardinalities.h.
Referenced by testing::internal::ExpectationBase::IsOverSaturated().
{
     return impl_->IsSaturatedByCallCount(call_count) &&
         !impl_->IsSatisfiedByCallCount(call_count);
   }
bool testing::Cardinality::IsOverSaturatedByCallCount (int call_count) const inline
Definition at line 109 of file gmock-cardinalities.h.
{
     return impl_->IsSaturatedByCallCount(call_count) &&
         !impl_->IsSatisfiedByCallCount(call_count);
   }
bool testing::Cardinality::IsOverSaturatedByCallCount (int call_count) const inline
Definition at line 109 of file gmock-cardinalities.h.
{
     return impl_->IsSaturatedByCallCount(call_count) &&
         !impl_->IsSatisfiedByCallCount(call_count);
   }
bool testing::Cardinality::IsSatisfiedByCallCount (int call_count) const inline
Definition at line 98 of file gmock-cardinalities.h.
{
     return impl_->IsSatisfiedByCallCount(call_count);
   }
bool testing::Cardinality::IsSatisfiedByCallCount (int call_count) const inline
Definition at line 98 of file gmock-cardinalities.h.
{
     return impl_->IsSatisfiedByCallCount(call_count);
   }
bool testing::Cardinality::IsSatisfiedByCallCount (int call_count) const inline
Definition at line 98 of file gmock-cardinalities.h.
Referenced by testing::internal::ExpectationBase::IsSatisfied().
{
     return impl_->IsSatisfiedByCallCount(call_count);
   }
bool testing::Cardinality::IsSaturatedByCallCount (int call_count) const inline
Definition at line 103 of file gmock-cardinalities.h.
{
     return impl_->IsSaturatedByCallCount(call_count);
   }
bool testing::Cardinality::IsSaturatedByCallCount (int call_count) const inline
Definition at line 103 of file gmock-cardinalities.h.
Referenced by testing::internal::ExpectationBase::IsSaturated().
{
     return impl_->IsSaturatedByCallCount(call_count);
   }
bool testing::Cardinality::IsSaturatedByCallCount (int call_count) const inline
Definition at line 103 of file gmock-cardinalities.h.
{
     return impl_->IsSaturatedByCallCount(call_count);
   }
Member Data Documentation
internal::linked_ptr< const CardinalityInterface > testing::Cardinality::impl_ private
Definition at line 122 of file gmock-cardinalities.h.
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-cardinalities.h
proxygen/fizz/build_/gtest/src/gtest/googlemock/src/gmock-cardinalities.cc