proxygen: wangle::Subscription< T > Class Template Reference
wangle::Subscription< T > Class Template Reference
#include <Subscription.h>
Public Member Functions
Subscription ()=default
Subscription (const Subscription &)=delete
Subscription (Subscription &&other) noexcept
Subscription & operator= (Subscription &&other) noexcept
~Subscription ()
Private Types
typedef Observable< T >::Unsubscriber Unsubscriber
Private Member Functions
Subscription (std::shared_ptr< Unsubscriber > unsubscriber, uint64_t id)
void unsubscribe ()
Private Attributes
std::shared_ptr< Unsubscriber > unsubscriber_
uint64_t id_ {0}
Friends
class Observable< T >
Detailed Description
template<class T>
class wangle::Subscription< T >
Definition at line 27 of file Subscription.h.
Member Typedef Documentation
template<class T> typedef Observable<T>::Unsubscriber wangle::Subscription< T >::Unsubscriber private
Definition at line 51 of file Subscription.h.
Constructor & Destructor Documentation
template<class T> wangle::Subscription< T >::Subscription () default
template<class T> wangle::Subscription< T >::Subscription (const Subscription< T > &) delete
template<class T> wangle::Subscription< T >::Subscription (Subscription< T > && other) inline noexcept
Definition at line 33 of file Subscription.h.
References folly::gen::move.
{
     *this = std::move(other);
   }
template<class T> wangle::Subscription< T >::~Subscription () inline
Definition at line 46 of file Subscription.h.
References wangle::Subscription< T >::unsubscribe().
                   {
     unsubscribe();
   }
template<class T> wangle::Subscription< T >::Subscription (std::shared_ptr< Unsubscriber > unsubscriber, uint64_t id) inline private
Definition at line 53 of file Subscription.h.
References wangle::Subscription< T >::id_.
     : unsubscriber_(std::move(unsubscriber)), id_(id) {
     CHECK(id_ > 0);
   }
Member Function Documentation
template<class T> Subscription& wangle::Subscription< T >::operator= (Subscription< T > && other) inline noexcept
Definition at line 37 of file Subscription.h.
References wangle::Subscription< T >::id_, folly::gen::move, wangle::Subscription< T >::unsubscribe(), and wangle::Subscription< T >::unsubscriber_.
{
     unsubscribe();
     unsubscriber_ = std::move(other.unsubscriber_);
     id_ = other.id_;
     other.unsubscriber_ = nullptr;
     other.id_ = 0;
     return *this;
   }
template<class T> void wangle::Subscription< T >::unsubscribe () inline private
Definition at line 58 of file Subscription.h.
References wangle::Subscription< T >::id_, and wangle::Subscription< T >::unsubscriber_.
Referenced by wangle::Subscription< T >::operator=(), and wangle::Subscription< T >::~Subscription().
                      {
     if (unsubscriber_ && id_ > 0) {
       unsubscriber_->unsubscribe(id_);
       id_ = 0;
       unsubscriber_ = nullptr;
     }
   }
Friends And Related Function Documentation
template<class T> friend class Observable< T > friend
Definition at line 69 of file Subscription.h.
Member Data Documentation
template<class T> uint64_t wangle::Subscription< T >::id_ {0} private
Definition at line 67 of file Subscription.h.
Referenced by wangle::Subscription< T >::operator=(), wangle::Subscription< T >::Subscription(), and wangle::Subscription< T >::unsubscribe().
template<class T> std::shared_ptr<Unsubscriber> wangle::Subscription< T >::unsubscriber_ private
Definition at line 66 of file Subscription.h.
Referenced by wangle::Subscription< T >::operator=(), and wangle::Subscription< T >::unsubscribe().
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/deprecated/rx/Subscription.h