proxygen: testing::Sequence Class Reference
testing::Sequence Class Reference
#include <gmock-spec-builders.h>
Public Member Functions
Sequence ()
void AddExpectation (const Expectation &expectation) const
Sequence ()
void AddExpectation (const Expectation &expectation) const
Sequence ()
void AddExpectation (const Expectation &expectation) const
Private Attributes
internal::linked_ptr< Expectation > last_expectation_
Detailed Description
Definition at line 619 of file gmock-spec-builders.h.
Constructor & Destructor Documentation
testing::Sequence::Sequence () inline
Definition at line 622 of file gmock-spec-builders.h.
 : last_expectation_(new Expectation) {}
testing::Sequence::Sequence () inline
Definition at line 622 of file gmock-spec-builders.h.
References testing::internal::g_gmock_implicit_sequence, GTEST_API_, testing::internal::GTEST_ATTRIBUTE_UNUSED_, and GTEST_DISALLOW_COPY_AND_ASSIGN_.
 : last_expectation_(new Expectation) {}
testing::Sequence::Sequence () inline
Definition at line 622 of file gmock-spec-builders.h.
References testing::internal::g_gmock_implicit_sequence, GTEST_API_, testing::internal::GTEST_ATTRIBUTE_UNUSED_, and GTEST_DISALLOW_COPY_AND_ASSIGN_.
 : last_expectation_(new Expectation) {}
Member Function Documentation
void testing::Sequence::AddExpectation (const Expectation & expectation) const
Definition at line 794 of file gmock-spec-builders.cc.
References testing::Expectation::expectation_base(), and testing::internal::ExpectationBase::immediate_prerequisites_.
Referenced by testing::internal::FunctionMockerBase< R(A1, A2)>::AddNewExpectation(), and testing::internal::TypedExpectation< F >::InSequence().
{
   if (*last_expectation_ != expectation) {
     if (last_expectation_->expectation_base() != NULL) {
       expectation.expectation_base()->immediate_prerequisites_
           += *last_expectation_;
     }
     *last_expectation_ = expectation;
   }
 }
void testing::Sequence::AddExpectation (const Expectation & expectation) const
void testing::Sequence::AddExpectation (const Expectation & expectation) const
Member Data Documentation
internal::linked_ptr< Expectation > testing::Sequence::last_expectation_ private
Definition at line 633 of file gmock-spec-builders.h.
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-spec-builders.h
proxygen/fizz/build_/gtest/src/gtest/googlemock/src/gmock-spec-builders.cc