proxygen: proxygen::HPACKHeader Class Reference
proxygen::HPACKHeader Class Reference
#include <HPACKHeader.h>
Public Member Functions
HPACKHeader ()
HPACKHeader (const HPACKHeaderName &name_, const folly::fbstring &value_)
HPACKHeader (folly::StringPiece name_, folly::StringPiece value_)
HPACKHeader (HPACKHeader &&goner) noexcept
HPACKHeader & operator= (HPACKHeader &&goner) noexcept
~HPACKHeader ()
uint32_t bytes () const
bool operator== (const HPACKHeader &other) const
bool operator< (const HPACKHeader &other) const
bool operator> (const HPACKHeader &other) const
HPACKHeader copy () const
bool hasValue () const
Public Attributes
HPACKHeaderName name
folly::fbstring value
Static Public Attributes
static const uint32_t kMinLength = 32
Detailed Description
Definition at line 20 of file HPACKHeader.h.
Constructor & Destructor Documentation
proxygen::HPACKHeader::HPACKHeader () inline
Definition at line 24 of file HPACKHeader.h.
Referenced by copy().
 {}
proxygen::HPACKHeader::HPACKHeader (const HPACKHeaderName & name_, const folly::fbstring & value_) inline
Definition at line 26 of file HPACKHeader.h.
                                           :
       name(name_), value(value_) {}
proxygen::HPACKHeader::HPACKHeader (folly::StringPiece name_, folly::StringPiece value_) inline
Definition at line 30 of file HPACKHeader.h.
                                       :
       name(name_), value(value_.data(), value_.size()) {}
proxygen::HPACKHeader::HPACKHeader (HPACKHeader && goner) inline noexcept
Definition at line 34 of file HPACKHeader.h.
       : name(std::move(goner.name)),
         value(std::move(goner.value)) {}
proxygen::HPACKHeader::~HPACKHeader () inline
Definition at line 44 of file HPACKHeader.h.
 {}
Member Function Documentation
uint32_t proxygen::HPACKHeader::bytes () const inline
size in bytes of the header entry, as defined in the HPACK spec
Definition at line 49 of file HPACKHeader.h.
References name, proxygen::HPACKHeaderName::size(), folly::basic_fbstring< E, T, A, Storage >::size(), and value.
Referenced by proxygen::HeaderTable::add(), proxygen::QPACKHeaderTable::canIndex(), proxygen::HPACKDecoderBase::emit(), proxygen::HPACKEncoder::encodeAsLiteral(), proxygen::operator<<(), proxygen::HeaderTableTests::resizeAndFillTable(), proxygen::QPACKEncoder::shouldIndex(), proxygen::TEST_F(), and TEST_F().
{
     return folly::to<uint32_t>(kMinLength + name.size() + value.size());
   }
HPACKHeader proxygen::HPACKHeader::copy () const inline
Definition at line 71 of file HPACKHeader.h.
References HPACKHeader(), name, and value.
Referenced by TestContext::add(), proxygen::HPACKEncoder::encodeAsLiteral(), proxygen::QPACKEncoder::encodeHeaderQ(), proxygen::QPACKHeaderTable::maybeDuplicate(), proxygen::HeaderTableTests::resizeAndFillTable(), and proxygen::TEST_F().
{
     return HPACKHeader(name, value);
   }
bool proxygen::HPACKHeader::hasValue () const inline
Some header entries don't have a value, see StaticHeaderTable
Definition at line 78 of file HPACKHeader.h.
References folly::basic_fbstring< E, T, A, Storage >::empty(), and value.
Referenced by TEST_F().
{
     return !value.empty();
   }
bool proxygen::HPACKHeader::operator< (const HPACKHeader & other) const inline
Definition at line 56 of file HPACKHeader.h.
References name, and value.
{
     bool eqname = (name == other.name);
     if (!eqname) {
       return name < other.name;
     }
     return value < other.value;
   }
HPACKHeader& proxygen::HPACKHeader::operator= (HPACKHeader && goner) inline noexcept
Definition at line 38 of file HPACKHeader.h.
References name, folly::f14::swap(), and value.
{
     std::swap(name, goner.name);
     std::swap(value, goner.value);
     return *this;
   }
bool proxygen::HPACKHeader::operator== (const HPACKHeader & other) const inline
Definition at line 53 of file HPACKHeader.h.
References name, and value.
{
     return name == other.name && value == other.value;
   }
bool proxygen::HPACKHeader::operator> (const HPACKHeader & other) const inline
Definition at line 63 of file HPACKHeader.h.
References name, and value.
{
     bool eqname = (name == other.name);
     if (!eqname) {
       return name > other.name;
     }
     return value > other.value;
   }
Member Data Documentation
const uint32_t proxygen::HPACKHeader::kMinLength = 32 static
Definition at line 22 of file HPACKHeader.h.
HPACKHeaderName proxygen::HPACKHeader::name
Definition at line 82 of file HPACKHeader.h.
Referenced by proxygen::HeaderTable::add(), bytes(), copy(), proxygen::HPACKDecoder::decodeLiteralHeader(), proxygen::QPACKDecoder::decodeLiteralHeaderQ(), proxygen::HPACKDecoderBase::emit(), proxygen::HPACKEncoder::encodeAsLiteral(), proxygen::QPACKEncoder::encodeHeaderQ(), proxygen::HPACKEncoder::encodeLiteral(), proxygen::QPACKEncoder::encodeLiteralQHelper(), proxygen::HPACKContext::getIndex(), proxygen::HeaderTable::getIndex(), proxygen::QPACKHeaderTable::getIndex(), proxygen::NoPathIndexingStrategy::indexHeader(), proxygen::HeaderIndexingStrategy::indexHeader(), operator<(), proxygen::operator<<(), operator=(), operator==(), operator>(), TEST_F(), proxygen::TEST_F(), and TEST_P().
folly::fbstring proxygen::HPACKHeader::value
Definition at line 83 of file HPACKHeader.h.
Referenced by bytes(), copy(), proxygen::HPACKDecoder::decodeLiteralHeader(), proxygen::QPACKDecoder::decodeLiteralHeaderQ(), proxygen::HPACKDecoderBase::emit(), proxygen::HPACKEncoder::encodeLiteral(), proxygen::QPACKEncoder::encodeLiteralQHelper(), proxygen::HPACKContext::getIndex(), proxygen::HeaderTable::getIndex(), proxygen::QPACKHeaderTable::getIndex(), hasValue(), proxygen::HeaderIndexingStrategy::indexHeader(), operator<(), proxygen::operator<<(), operator=(), operator==(), operator>(), TEST_F(), and TEST_P().
The documentation for this class was generated from the following file:
proxygen/lib/http/codec/compress/HPACKHeader.h