proxygen: folly::symbolizer::FDSymbolizePrinter Class Reference
folly::symbolizer::FDSymbolizePrinter Class Reference
#include <Symbolizer.h>
Public Member Functions
FDSymbolizePrinter (int fd, int options=0, size_t bufferSize=0)
~FDSymbolizePrinter () override
virtual void flush () override
Public Member Functions inherited from folly::symbolizer::SymbolizePrinter
void print (uintptr_t address, const SymbolizedFrame &frame)
void println (uintptr_t address, const SymbolizedFrame &frame)
void println (const uintptr_t *addresses, const SymbolizedFrame *frames, size_t frameCount)
void print (StringPiece sp)
template<size_t N>
void println (const FrameArray< N > &fa, size_t skip=0)
virtual ~SymbolizePrinter ()
void color (Color c)
Private Member Functions
void doPrint (StringPiece sp) override
Private Attributes
const int fd_
std::unique_ptr< IOBuf > buffer_
Additional Inherited Members
Public Types inherited from folly::symbolizer::SymbolizePrinter
enum Options {
NO_FILE_AND_LINE = 1 << 0, TERSE = 1 << 1, COLOR = 1 << 2, COLOR_IF_TTY = 1 << 3,
NO_FRAME_ADDRESS = 1 << 4
}
enum Color {
DEFAULT, RED, GREEN, YELLOW,
BLUE, CYAN, WHITE, PURPLE,
NUM
}
Protected Member Functions inherited from folly::symbolizer::SymbolizePrinter
SymbolizePrinter (int options, bool isTty=false)
Protected Attributes inherited from folly::symbolizer::SymbolizePrinter
const int options_
const bool isTty_
Detailed Description
Print a list of symbolized addresses to a file descriptor. Ignores errors. Async-signal-safe.
Definition at line 287 of file Symbolizer.h.
Constructor & Destructor Documentation
folly::symbolizer::FDSymbolizePrinter::FDSymbolizePrinter (int fd, int options = 0, size_t bufferSize = 0) explicit
Definition at line 367 of file Symbolizer.cpp.
     : SymbolizePrinter(options, isColorfulTty(options, fd)),
       fd_(fd),
       buffer_(bufferSize ? IOBuf::create(bufferSize) : nullptr) {}
folly::symbolizer::FDSymbolizePrinter::~FDSymbolizePrinter () override
Definition at line 372 of file Symbolizer.cpp.
References flush().
{
   flush();
 }
Member Function Documentation
void folly::symbolizer::FDSymbolizePrinter::doPrint (StringPiece sp) override private virtual
Implements folly::symbolizer::SymbolizePrinter.
Definition at line 376 of file Symbolizer.cpp.
References buffer_, folly::Range< Iter >::data(), fd_, flush(), folly::Range< Iter >::size(), and folly::writeFull().
{
   if (buffer_) {
     if (sp.size() > buffer_->tailroom()) {
       flush();
       writeFull(fd_, sp.data(), sp.size());
     } else {
       memcpy(buffer_->writableTail(), sp.data(), sp.size());
       buffer_->append(sp.size());
     }
   } else {
     writeFull(fd_, sp.data(), sp.size());
   }
 }
void folly::symbolizer::FDSymbolizePrinter::flush () override virtual
If output buffered inside this class, send it to the output stream, so that any output done in other ways appears after this.
Reimplemented from folly::symbolizer::SymbolizePrinter.
Definition at line 390 of file Symbolizer.cpp.
References buffer_, fd_, and folly::writeFull().
Referenced by doPrint(), folly::symbolizer::SafeStackTracePrinter::flush(), and ~FDSymbolizePrinter().
{
   if (buffer_ && !buffer_->empty()) {
     writeFull(fd_, buffer_->data(), buffer_->length());
     buffer_->clear();
   }
 }
Member Data Documentation
std::unique_ptr<IOBuf> folly::symbolizer::FDSymbolizePrinter::buffer_ private
Definition at line 297 of file Symbolizer.h.
Referenced by doPrint(), and flush().
const int folly::symbolizer::FDSymbolizePrinter::fd_ private
Definition at line 296 of file Symbolizer.h.
Referenced by doPrint(), and flush().
The documentation for this class was generated from the following files:
proxygen/folly/folly/experimental/symbolizer/Symbolizer.h
proxygen/folly/folly/experimental/symbolizer/Symbolizer.cpp