proxygen: testing::gmock_more_actions_test::Foo Class Reference
testing::gmock_more_actions_test::Foo Class Reference
Public Member Functions
Foo ()
int Nullary () const
short Unary (long x)
string Binary (const string &str, char c) const
int Ternary (int x, bool y, char z)
int SumOf4 (int a, int b, int c, int d) const
int SumOfLast2 (Unused, Unused, int a, int b) const
int SumOf5 (int a, int b, int c, int d, int e)
int SumOf6 (int a, int b, int c, int d, int e, int f)
string Concat7 (const char *s1, const char *s2, const char *s3, const char *s4, const char *s5, const char *s6, const char *s7)
string Concat8 (const char *s1, const char *s2, const char *s3, const char *s4, const char *s5, const char *s6, const char *s7, const char *s8)
string Concat9 (const char *s1, const char *s2, const char *s3, const char *s4, const char *s5, const char *s6, const char *s7, const char *s8, const char *s9)
string Concat10 (const char *s1, const char *s2, const char *s3, const char *s4, const char *s5, const char *s6, const char *s7, const char *s8, const char *s9, const char *s10)
Foo ()
int Nullary () const
short Unary (long x)
string Binary (const string &str, char c) const
int Ternary (int x, bool y, char z)
int SumOf4 (int a, int b, int c, int d) const
int SumOfLast2 (Unused, Unused, int a, int b) const
int SumOf5 (int a, int b, int c, int d, int e)
int SumOf6 (int a, int b, int c, int d, int e, int f)
string Concat7 (const char *s1, const char *s2, const char *s3, const char *s4, const char *s5, const char *s6, const char *s7)
string Concat8 (const char *s1, const char *s2, const char *s3, const char *s4, const char *s5, const char *s6, const char *s7, const char *s8)
string Concat9 (const char *s1, const char *s2, const char *s3, const char *s4, const char *s5, const char *s6, const char *s7, const char *s8, const char *s9)
string Concat10 (const char *s1, const char *s2, const char *s3, const char *s4, const char *s5, const char *s6, const char *s7, const char *s8, const char *s9, const char *s10)
Foo ()
int Nullary () const
short Unary (long x)
string Binary (const string &str, char c) const
int Ternary (int x, bool y, char z)
int SumOf4 (int a, int b, int c, int d) const
int SumOfLast2 (Unused, Unused, int a, int b) const
int SumOf5 (int a, int b, int c, int d, int e)
int SumOf6 (int a, int b, int c, int d, int e, int f)
string Concat7 (const char *s1, const char *s2, const char *s3, const char *s4, const char *s5, const char *s6, const char *s7)
string Concat8 (const char *s1, const char *s2, const char *s3, const char *s4, const char *s5, const char *s6, const char *s7, const char *s8)
string Concat9 (const char *s1, const char *s2, const char *s3, const char *s4, const char *s5, const char *s6, const char *s7, const char *s8, const char *s9)
string Concat10 (const char *s1, const char *s2, const char *s3, const char *s4, const char *s5, const char *s6, const char *s7, const char *s8, const char *s9, const char *s10)
Private Attributes
int value_
Detailed Description
Definition at line 180 of file gmock-more-actions_test.cc.
Constructor & Destructor Documentation
testing::gmock_more_actions_test::Foo::Foo () inline
Definition at line 182 of file gmock-more-actions_test.cc.
 : value_(123) {}
testing::gmock_more_actions_test::Foo::Foo () inline
Definition at line 182 of file gmock-more-actions_test.cc.
 : value_(123) {}
testing::gmock_more_actions_test::Foo::Foo () inline
Definition at line 182 of file gmock-more-actions_test.cc.
 : value_(123) {}
Member Function Documentation
string testing::gmock_more_actions_test::Foo::Binary (const string & str, char c) const inline
Definition at line 188 of file gmock-more-actions_test.cc.
References c.
Referenced by Concat10(), and testing::gmock_more_actions_test::TEST().
 { return str + c; }
string testing::gmock_more_actions_test::Foo::Binary (const string & str, char c) const inline
Definition at line 188 of file gmock-more-actions_test.cc.
References c.
 { return str + c; }
string testing::gmock_more_actions_test::Foo::Binary (const string & str, char c) const inline
Definition at line 188 of file gmock-more-actions_test.cc.
References c.
 { return str + c; }
string testing::gmock_more_actions_test::Foo::Concat10 (const char * s1, const char * s2, const char * s3, const char * s4, const char * s5, const char * s6, const char * s7, const char * s8, const char * s9, const char * s10) inline
Definition at line 222 of file gmock-more-actions_test.cc.
References testing::gmock_more_actions_test::Binary(), Binary(), testing::gmock_more_actions_test::Char(), testing::gmock_more_actions_test::CharPtr(), testing::gmock_more_actions_test::Concat10(), Concat10(), testing::gmock_more_actions_test::Concat7(), Concat7(), testing::gmock_more_actions_test::Concat8(), Concat8(), testing::gmock_more_actions_test::Concat9(), Concat9(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testing::gmock_matchers_test::foo, testing::Invoke(), std::tr1::make_tuple(), testing::gmock_more_actions_test::Nullary(), Nullary(), testing::Action< F >::Perform(), s, testing::gmock_more_actions_test::Short(), string, testing::gmock_more_actions_test::SumOf4(), SumOf4(), testing::gmock_more_actions_test::SumOf5(), SumOf5(), testing::gmock_more_actions_test::SumOf6(), SumOf6(), testing::gmock_more_actions_test::SumOfFirst2(), SumOfLast2(), testing::gmock_more_actions_test::Ternary(), Ternary(), testing::gmock_more_actions_test::TEST(), testing::gmock_more_actions_test::Unary(), Unary(), value, and testing::WithoutArgs().
{
     return string(s1) + s2 + s3 + s4 + s5 + s6 + s7 + s8 + s9 + s10;
   }
string testing::gmock_more_actions_test::Foo::Concat10 (const char * s1, const char * s2, const char * s3, const char * s4, const char * s5, const char * s6, const char * s7, const char * s8, const char * s9, const char * s10) inline
Definition at line 222 of file gmock-more-actions_test.cc.
References testing::gmock_more_actions_test::Binary(), Binary(), testing::gmock_more_actions_test::Char(), testing::gmock_more_actions_test::CharPtr(), testing::gmock_more_actions_test::Concat10(), Concat10(), testing::gmock_more_actions_test::Concat7(), Concat7(), testing::gmock_more_actions_test::Concat8(), Concat8(), testing::gmock_more_actions_test::Concat9(), Concat9(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testing::gmock_matchers_test::foo, testing::Invoke(), std::tr1::make_tuple(), testing::gmock_more_actions_test::Nullary(), Nullary(), testing::Action< F >::Perform(), s, testing::gmock_more_actions_test::Short(), string, testing::gmock_more_actions_test::SumOf4(), SumOf4(), testing::gmock_more_actions_test::SumOf5(), SumOf5(), testing::gmock_more_actions_test::SumOf6(), SumOf6(), testing::gmock_more_actions_test::SumOfFirst2(), SumOfLast2(), testing::gmock_more_actions_test::Ternary(), Ternary(), testing::gmock_more_actions_test::TEST(), testing::gmock_more_actions_test::Unary(), Unary(), value, and testing::WithoutArgs().
{
     return string(s1) + s2 + s3 + s4 + s5 + s6 + s7 + s8 + s9 + s10;
   }
string testing::gmock_more_actions_test::Foo::Concat10 (const char * s1, const char * s2, const char * s3, const char * s4, const char * s5, const char * s6, const char * s7, const char * s8, const char * s9, const char * s10) inline
Definition at line 222 of file gmock-more-actions_test.cc.
References string.
Referenced by Concat10(), and testing::gmock_more_actions_test::TEST().
{
     return string(s1) + s2 + s3 + s4 + s5 + s6 + s7 + s8 + s9 + s10;
   }
string testing::gmock_more_actions_test::Foo::Concat7 (const char * s1, const char * s2, const char * s3, const char * s4, const char * s5, const char * s6, const char * s7) inline
Definition at line 204 of file gmock-more-actions_test.cc.
References string.
Referenced by Concat10(), and testing::gmock_more_actions_test::TEST().
{
     return string(s1) + s2 + s3 + s4 + s5 + s6 + s7;
   }
string testing::gmock_more_actions_test::Foo::Concat7 (const char * s1, const char * s2, const char * s3, const char * s4, const char * s5, const char * s6, const char * s7) inline
Definition at line 204 of file gmock-more-actions_test.cc.
References string.
{
     return string(s1) + s2 + s3 + s4 + s5 + s6 + s7;
   }
string testing::gmock_more_actions_test::Foo::Concat7 (const char * s1, const char * s2, const char * s3, const char * s4, const char * s5, const char * s6, const char * s7) inline
Definition at line 204 of file gmock-more-actions_test.cc.
References string.
{
     return string(s1) + s2 + s3 + s4 + s5 + s6 + s7;
   }
string testing::gmock_more_actions_test::Foo::Concat8 (const char * s1, const char * s2, const char * s3, const char * s4, const char * s5, const char * s6, const char * s7, const char * s8) inline
Definition at line 210 of file gmock-more-actions_test.cc.
References string.
{
     return string(s1) + s2 + s3 + s4 + s5 + s6 + s7 + s8;
   }
string testing::gmock_more_actions_test::Foo::Concat8 (const char * s1, const char * s2, const char * s3, const char * s4, const char * s5, const char * s6, const char * s7, const char * s8) inline
Definition at line 210 of file gmock-more-actions_test.cc.
References string.
Referenced by Concat10(), and testing::gmock_more_actions_test::TEST().
{
     return string(s1) + s2 + s3 + s4 + s5 + s6 + s7 + s8;
   }
string testing::gmock_more_actions_test::Foo::Concat8 (const char * s1, const char * s2, const char * s3, const char * s4, const char * s5, const char * s6, const char * s7, const char * s8) inline
Definition at line 210 of file gmock-more-actions_test.cc.
References string.
{
     return string(s1) + s2 + s3 + s4 + s5 + s6 + s7 + s8;
   }
string testing::gmock_more_actions_test::Foo::Concat9 (const char * s1, const char * s2, const char * s3, const char * s4, const char * s5, const char * s6, const char * s7, const char * s8, const char * s9) inline
Definition at line 216 of file gmock-more-actions_test.cc.
References string.
{
     return string(s1) + s2 + s3 + s4 + s5 + s6 + s7 + s8 + s9;
   }
string testing::gmock_more_actions_test::Foo::Concat9 (const char * s1, const char * s2, const char * s3, const char * s4, const char * s5, const char * s6, const char * s7, const char * s8, const char * s9) inline
Definition at line 216 of file gmock-more-actions_test.cc.
References string.
Referenced by Concat10(), and testing::gmock_more_actions_test::TEST().
{
     return string(s1) + s2 + s3 + s4 + s5 + s6 + s7 + s8 + s9;
   }
string testing::gmock_more_actions_test::Foo::Concat9 (const char * s1, const char * s2, const char * s3, const char * s4, const char * s5, const char * s6, const char * s7, const char * s8, const char * s9) inline
Definition at line 216 of file gmock-more-actions_test.cc.
References string.
{
     return string(s1) + s2 + s3 + s4 + s5 + s6 + s7 + s8 + s9;
   }
int testing::gmock_more_actions_test::Foo::Nullary () const inline
Definition at line 184 of file gmock-more-actions_test.cc.
Referenced by Concat10(), and testing::gmock_more_actions_test::TEST().
 { return value_; }
int testing::gmock_more_actions_test::Foo::Nullary () const inline
Definition at line 184 of file gmock-more-actions_test.cc.
 { return value_; }
int testing::gmock_more_actions_test::Foo::Nullary () const inline
Definition at line 184 of file gmock-more-actions_test.cc.
 { return value_; }
int testing::gmock_more_actions_test::Foo::SumOf4 (int a, int b, int c, int d) const inline
Definition at line 192 of file gmock-more-actions_test.cc.
{
     return a + b + c + d + value_;
   }
int testing::gmock_more_actions_test::Foo::SumOf4 (int a, int b, int c, int d) const inline
Definition at line 192 of file gmock-more-actions_test.cc.
Referenced by Concat10(), and testing::gmock_more_actions_test::TEST().
{
     return a + b + c + d + value_;
   }
int testing::gmock_more_actions_test::Foo::SumOf4 (int a, int b, int c, int d) const inline
Definition at line 192 of file gmock-more-actions_test.cc.
{
     return a + b + c + d + value_;
   }
int testing::gmock_more_actions_test::Foo::SumOf5 (int a, int b, int c, int d, int e) inline
Definition at line 198 of file gmock-more-actions_test.cc.
 { return a + b + c + d + e; }
int testing::gmock_more_actions_test::Foo::SumOf5 (int a, int b, int c, int d, int e) inline
Definition at line 198 of file gmock-more-actions_test.cc.
 { return a + b + c + d + e; }
int testing::gmock_more_actions_test::Foo::SumOf5 (int a, int b, int c, int d, int e) inline
Definition at line 198 of file gmock-more-actions_test.cc.
Referenced by Concat10(), and testing::gmock_more_actions_test::TEST().
 { return a + b + c + d + e; }
int testing::gmock_more_actions_test::Foo::SumOf6 (int a, int b, int c, int d, int e, int f) inline
Definition at line 200 of file gmock-more-actions_test.cc.
References f.
Referenced by Concat10(), and testing::gmock_more_actions_test::TEST().
{
     return a + b + c + d + e + f;
   }
int testing::gmock_more_actions_test::Foo::SumOf6 (int a, int b, int c, int d, int e, int f) inline
Definition at line 200 of file gmock-more-actions_test.cc.
References f.
{
     return a + b + c + d + e + f;
   }
int testing::gmock_more_actions_test::Foo::SumOf6 (int a, int b, int c, int d, int e, int f) inline
Definition at line 200 of file gmock-more-actions_test.cc.
References f.
{
     return a + b + c + d + e + f;
   }
int testing::gmock_more_actions_test::Foo::SumOfLast2 (Unused , Unused , int a, int b) const inline
Definition at line 196 of file gmock-more-actions_test.cc.
References b.
Referenced by Concat10(), and testing::gmock_more_actions_test::TEST().
 { return a + b; }
int testing::gmock_more_actions_test::Foo::SumOfLast2 (Unused , Unused , int a, int b) const inline
Definition at line 196 of file gmock-more-actions_test.cc.
References b.
 { return a + b; }
int testing::gmock_more_actions_test::Foo::SumOfLast2 (Unused , Unused , int a, int b) const inline
Definition at line 196 of file gmock-more-actions_test.cc.
References b.
 { return a + b; }
int testing::gmock_more_actions_test::Foo::Ternary (int x, bool y, char z) inline
Definition at line 190 of file gmock-more-actions_test.cc.
 { return value_ + x + y*z; }
int testing::gmock_more_actions_test::Foo::Ternary (int x, bool y, char z) inline
Definition at line 190 of file gmock-more-actions_test.cc.
 { return value_ + x + y*z; }
int testing::gmock_more_actions_test::Foo::Ternary (int x, bool y, char z) inline
Definition at line 190 of file gmock-more-actions_test.cc.
Referenced by Concat10(), and testing::gmock_more_actions_test::TEST().
 { return value_ + x + y*z; }
short testing::gmock_more_actions_test::Foo::Unary (long x) inline
Definition at line 186 of file gmock-more-actions_test.cc.
References x.
 { return static_cast<short>(value_ + x); }  // NOLINT
short testing::gmock_more_actions_test::Foo::Unary (long x) inline
Definition at line 186 of file gmock-more-actions_test.cc.
References x.
 { return static_cast<short>(value_ + x); }  // NOLINT
short testing::gmock_more_actions_test::Foo::Unary (long x) inline
Definition at line 186 of file gmock-more-actions_test.cc.
References x.
Referenced by Concat10(), and testing::gmock_more_actions_test::TEST().
 { return static_cast<short>(value_ + x); }  // NOLINT
Member Data Documentation
int Foo::value_ private
Definition at line 230 of file gmock-more-actions_test.cc.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-more-actions_test.cc