proxygen: folly::SomeClass Class Reference
folly::SomeClass Class Reference
#include <ThenCompileTest.h>
Public Member Functions
template<class Ret , class... Params>
std::enable_if<!isFuture< Ret >::value, Ret >::type aMethod (Params...)
template<class Ret , class... Params>
std::enable_if< isFuture< Ret >::value, Ret >::type aMethod (Params...)
Static Public Member Functions
template<class Ret , class... Params>
static std::enable_if<!isFuture< Ret >::value, Ret >::type aStaticMethod (Params...)
template<class Ret , class... Params>
static std::enable_if< isFuture< Ret >::value, Ret >::type aStaticMethod (Params...)
Detailed Description
Definition at line 64 of file ThenCompileTest.h.
Member Function Documentation
template<class Ret , class... Params> std::enable_if<!isFuture<Ret>::value, Ret>::type folly::SomeClass::aMethod (Params...) inline
Definition at line 80 of file ThenCompileTest.h.
Referenced by TEST().
{
     return Ret();
   }
template<class Ret , class... Params> std::enable_if<isFuture<Ret>::value, Ret>::type folly::SomeClass::aMethod (Params...) inline
Definition at line 85 of file ThenCompileTest.h.
References folly::makeFuture(), and folly::T.
{
     typedef typename Ret::value_type T;
     return makeFuture(T());
   }
template<class Ret , class... Params> static std::enable_if<!isFuture<Ret>::value, Ret>::type folly::SomeClass::aStaticMethod (Params...) inline static
Definition at line 68 of file ThenCompileTest.h.
Referenced by TEST().
{
     return Ret();
   }
template<class Ret , class... Params> static std::enable_if<isFuture<Ret>::value, Ret>::type folly::SomeClass::aStaticMethod (Params...) inline static
Definition at line 73 of file ThenCompileTest.h.
References folly::makeFuture(), and folly::T.
                  {
     typedef typename Ret::value_type T;
     return makeFuture(T());
   }
The documentation for this class was generated from the following file:
proxygen/folly/folly/futures/test/ThenCompileTest.h