proxygen: testing::internal::UniversalPrinter< T > Class Template Reference
testing::internal::UniversalPrinter< T > Class Template Reference
#include <gtest-printers.h>
Static Public Member Functions
static void Print (const T &value,::std::ostream *os)
static void Print (const T &value,::std::ostream *os)
static void Print (const T &value,::std::ostream *os)
Detailed Description
template<typename T>
class testing::internal::UniversalPrinter< T >
Definition at line 362 of file gtest-printers.h.
Member Function Documentation
template<typename T > static void testing::internal::UniversalPrinter< T >::Print (const T & value, ::std::ostream * os) inline static
Definition at line 698 of file gtest-printers.h.
References GTEST_DISABLE_MSC_WARNINGS_POP_, and testing::internal::PrintTo().
Referenced by testing::internal::ReferenceWrapper< T >::operator T &(), testing::internal::ActionResultHolder< T >::PrintAsActionResult(), and testing::internal::PrintTo().
{
     // By default, ::testing::internal::PrintTo() is used for printing
     // the value.
     //
     // Thanks to Koenig look-up, if T is a class and has its own
     // PrintTo() function defined in its namespace, that function will
     // be visible here.  Since it is more specific than the generic ones
     // in ::testing::internal, it will be picked by the compiler in the
     // following statement - exactly what we want.
     PrintTo(value, os);
   }
template<typename T > static void testing::internal::UniversalPrinter< T >::Print (const T & value, ::std::ostream * os) inline static
Definition at line 698 of file gtest-printers.h.
References folly::test::begin(), GTEST_API_, GTEST_DISABLE_MSC_WARNINGS_POP_, testing::internal::PrintRawArrayTo(), testing::internal::PrintTo(), T, and testing::internal::UniversalPrintArray().
{
     // By default, ::testing::internal::PrintTo() is used for printing
     // the value.
     //
     // Thanks to Koenig look-up, if T is a class and has its own
     // PrintTo() function defined in its namespace, that function will
     // be visible here.  Since it is more specific than the generic ones
     // in ::testing::internal, it will be picked by the compiler in the
     // following statement - exactly what we want.
     PrintTo(value, os);
   }
template<typename T > static void testing::internal::UniversalPrinter< T >::Print (const T & value, ::std::ostream * os) inline static
Definition at line 698 of file gtest-printers.h.
References folly::test::begin(), GTEST_API_, GTEST_DISABLE_MSC_WARNINGS_POP_, testing::internal::PrintRawArrayTo(), testing::internal::PrintTo(), T, and testing::internal::UniversalPrintArray().
{
     // By default, ::testing::internal::PrintTo() is used for printing
     // the value.
     //
     // Thanks to Koenig look-up, if T is a class and has its own
     // PrintTo() function defined in its namespace, that function will
     // be visible here.  Since it is more specific than the generic ones
     // in ::testing::internal, it will be picked by the compiler in the
     // following statement - exactly what we want.
     PrintTo(value, os);
   }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/gtest-printers.h