proxygen: testing::gmock_matchers_test::DerivedClass Class Reference
testing::gmock_matchers_test::DerivedClass Class Reference
Public Member Functions
int k () const
int k () const
int k () const
Public Member Functions inherited from testing::gmock_matchers_test::AClass
AClass ()
int n () const
void set_n (int new_n)
const string & s () const
void set_s (const string &new_s)
double & x () const
AClass ()
int n () const
void set_n (int new_n)
const string & s () const
void set_s (const string &new_s)
double & x () const
AClass ()
int n () const
void set_n (int new_n)
const string & s () const
void set_s (const string &new_s)
double & x () const
Private Attributes
int k_
Detailed Description
Definition at line 3604 of file gmock-matchers_test.cc.
Member Function Documentation
int testing::gmock_matchers_test::DerivedClass::k () const inline
Definition at line 3606 of file gmock-matchers_test.cc.
 { return k_; }
int testing::gmock_matchers_test::DerivedClass::k () const inline
Definition at line 3606 of file gmock-matchers_test.cc.
References testing::_, a, testing::gmock_matchers_test::Describe(), testing::gmock_matchers_test::DescribeNegation(), testing::gmock_matchers_test::DoubleFunction(), dummy(), testing::Eq(), EXPECT_DEATH_IF_SUPPORTED, EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testing::gmock_matchers_test::Explain(), testing::Ge(), testing::gmock_matchers_test::GreaterThan(), testing::gmock_matchers_test::IntFunction(), testing::gmock_matchers_test::IntToStringFunction(), testing::internal::MatcherBase< T >::Matches(), testing::Not(), testing::gmock_matchers_test::OfType(), testing::Property(), testing::Ref(), testing::gmock_matchers_test::RefUncopyableFunction(), testing::ResultOf(), s, testing::gmock_matchers_test::AClass::set_n(), testing::gmock_matchers_test::AClass::set_s(), testing::StartsWith(), testing::StrEq(), testing::gmock_matchers_test::StringFunction(), testing::internal::TEST(), and x.
 { return k_; }
int testing::gmock_matchers_test::DerivedClass::k () const inline
Definition at line 3606 of file gmock-matchers_test.cc.
References testing::_, a, testing::gmock_matchers_test::Describe(), testing::gmock_matchers_test::DescribeNegation(), testing::gmock_matchers_test::DoubleFunction(), dummy(), testing::Eq(), EXPECT_DEATH_IF_SUPPORTED, EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testing::gmock_matchers_test::Explain(), testing::Ge(), testing::gmock_matchers_test::GreaterThan(), testing::gmock_matchers_test::IntFunction(), testing::gmock_matchers_test::IntToStringFunction(), testing::internal::MatcherBase< T >::Matches(), testing::Not(), testing::gmock_matchers_test::OfType(), testing::Property(), testing::Ref(), testing::gmock_matchers_test::RefUncopyableFunction(), testing::ResultOf(), s, testing::gmock_matchers_test::AClass::set_n(), testing::gmock_matchers_test::AClass::set_s(), testing::StartsWith(), testing::StrEq(), testing::gmock_matchers_test::StringFunction(), testing::internal::TEST(), and x.
 { return k_; }
Member Data Documentation
int testing::gmock_matchers_test::DerivedClass::k_ private
Definition at line 3608 of file gmock-matchers_test.cc.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-matchers_test.cc