proxygen: folly::BasicTokenBucket< Clock > Class Template Reference
folly::BasicTokenBucket< Clock > Class Template Reference
#include <TokenBucket.h>
Public Member Functions
BasicTokenBucket (double genRate, double burstSize, double zeroTime=0) noexcept
BasicTokenBucket (const BasicTokenBucket &other) noexcept=default
BasicTokenBucket & operator= (const BasicTokenBucket &other) noexcept=default
void reset (double genRate, double burstSize, double nowInSeconds=defaultClockNow()) noexcept
void setCapacity (double tokens, double nowInSeconds) noexcept
bool consume (double toConsume, double nowInSeconds=defaultClockNow())
double consumeOrDrain (double toConsume, double nowInSeconds=defaultClockNow())
double available (double nowInSeconds=defaultClockNow()) const
double rate () const noexcept
double burst () const noexcept
Static Public Member Functions
static double defaultClockNow () noexcept(noexcept(Impl::defaultClockNow()))
Private Types
using Impl = BasicDynamicTokenBucket< Clock >
Private Attributes
Impl tokenBucket_
double rate_
double burstSize_
Detailed Description
template<typename Clock = std::chrono::steady_clock>
class folly::BasicTokenBucket< Clock >
Specialization of BasicDynamicTokenBucket with a fixed token generation rate and a fixed maximum burst size.
Definition at line 221 of file TokenBucket.h.
Member Typedef Documentation
template<typename Clock = std::chrono::steady_clock> using folly::BasicTokenBucket< Clock >::Impl = BasicDynamicTokenBucket<Clock> private
Definition at line 225 of file TokenBucket.h.
Constructor & Destructor Documentation
template<typename Clock = std::chrono::steady_clock> folly::BasicTokenBucket< Clock >::BasicTokenBucket (double genRate, double burstSize, double zeroTime = 0) inline noexcept
Construct a token bucket with a specific maximum rate and burst size.
Parameters
genRate Number of tokens to generate per second.
burstSize Maximum burst size. Must be greater than 0.
zeroTime Initial time at which to consider the token bucket starting to fill. Defaults to 0, so by default token bucket is "full" after construction.
Definition at line 237 of file TokenBucket.h.
References folly::pushmi::__adl::noexcept(), and folly::BasicDynamicTokenBucket< Clock >::operator=().
       : tokenBucket_(zeroTime), rate_(genRate), burstSize_(burstSize) {
     assert(rate_ > 0);
     assert(burstSize_ > 0);
   }
template<typename Clock = std::chrono::steady_clock> folly::BasicTokenBucket< Clock >::BasicTokenBucket (const BasicTokenBucket< Clock > & other) default noexcept
Copy constructor.
Warning: not thread safe!
Member Function Documentation
template<typename Clock = std::chrono::steady_clock> double folly::BasicTokenBucket< Clock >::available (double nowInSeconds = defaultClockNow()) const inline
Returns the number of tokens currently available.
Thread-safe (but returned value may immediately be outdated).
Definition at line 347 of file TokenBucket.h.
Referenced by TEST().
{
     return tokenBucket_.available(rate_, burstSize_, nowInSeconds);
   }
template<typename Clock = std::chrono::steady_clock> double folly::BasicTokenBucket< Clock >::burst () const inline noexcept
Returns the maximum burst size.
Thread-safe (but returned value may immediately be outdated).
Definition at line 365 of file TokenBucket.h.
{
     return burstSize_;
   }
template<typename Clock = std::chrono::steady_clock> bool folly::BasicTokenBucket< Clock >::consume (double toConsume, double nowInSeconds = defaultClockNow()) inline
Attempts to consume some number of tokens. Tokens are first added to the bucket based on the time elapsed since the last attempt to consume tokens. Note: Attempts to consume more tokens than the burst size will always fail.
Thread-safe.
Parameters
toConsume The number of tokens to consume.
nowInSeconds Current time in seconds. Should be monotonically increasing from the nowInSeconds specified in this token bucket's constructor.
Returns
True if the rate limit check passed, false otherwise.
Definition at line 318 of file TokenBucket.h.
Referenced by doTokenBucketTest(), TEST(), and TEST_P().
{
     return tokenBucket_.consume(toConsume, rate_, burstSize_, nowInSeconds);
   }
template<typename Clock = std::chrono::steady_clock> double folly::BasicTokenBucket< Clock >::consumeOrDrain (double toConsume, double nowInSeconds = defaultClockNow()) inline
Similar to consume, but always consumes some number of tokens. If the bucket contains enough tokens - consumes toConsume tokens. Otherwise the bucket is drained.
Thread-safe.
Parameters
toConsume The number of tokens to consume.
nowInSeconds Current time in seconds. Should be monotonically increasing from the nowInSeconds specified in this token bucket's constructor.
Returns
number of tokens that were consumed.
Definition at line 335 of file TokenBucket.h.
{
     return tokenBucket_.consumeOrDrain(
         toConsume, rate_, burstSize_, nowInSeconds);
   }
template<typename Clock = std::chrono::steady_clock> static double folly::BasicTokenBucket< Clock >::defaultClockNow () inline static noexcept
Returns the current time in seconds since Epoch.
Definition at line 263 of file TokenBucket.h.
{
     return Impl::defaultClockNow();
   }
template<typename Clock = std::chrono::steady_clock> BasicTokenBucket& folly::BasicTokenBucket< Clock >::operator= (const BasicTokenBucket< Clock > & other) default noexcept
Copy-assignment operator.
Warning: not thread safe!
template<typename Clock = std::chrono::steady_clock> double folly::BasicTokenBucket< Clock >::rate () const inline noexcept
Returns the number of tokens generated per second.
Thread-safe (but returned value may immediately be outdated).
Definition at line 356 of file TokenBucket.h.
{
     return rate_;
   }
template<typename Clock = std::chrono::steady_clock> void folly::BasicTokenBucket< Clock >::reset (double genRate, double burstSize, double nowInSeconds = defaultClockNow()) inline noexcept
Change rate and burst size.
Warning: not thread safe!
Parameters
genRate Number of tokens to generate per second.
burstSize Maximum burst size. Must be greater than 0.
nowInSeconds Current time in seconds. Should be monotonically increasing from the nowInSeconds specified in this token bucket's constructor.
Definition at line 278 of file TokenBucket.h.
References folly::BasicDynamicTokenBucket< Clock >::available().
Referenced by folly::BasicTokenBucket< Clock >::setCapacity().
{
     assert(genRate > 0);
     assert(burstSize > 0);
     const double availTokens = available(nowInSeconds);
     rate_ = genRate;
     burstSize_ = burstSize;
     setCapacity(availTokens, nowInSeconds);
   }
template<typename Clock = std::chrono::steady_clock> void folly::BasicTokenBucket< Clock >::setCapacity (double tokens, double nowInSeconds) inline noexcept
Change number of tokens in bucket.
Warning: not thread safe!
Parameters
tokens Desired number of tokens in bucket after the call.
nowInSeconds Current time in seconds. Should be monotonically increasing from the nowInSeconds specified in this token bucket's constructor.
Definition at line 300 of file TokenBucket.h.
References folly::BasicTokenBucket< Clock >::reset(), and tokens.
{
     tokenBucket_.reset(nowInSeconds - tokens / rate_);
   }
Member Data Documentation
template<typename Clock = std::chrono::steady_clock> double folly::BasicTokenBucket< Clock >::burstSize_ private
Definition at line 372 of file TokenBucket.h.
template<typename Clock = std::chrono::steady_clock> double folly::BasicTokenBucket< Clock >::rate_ private
Definition at line 371 of file TokenBucket.h.
template<typename Clock = std::chrono::steady_clock> Impl folly::BasicTokenBucket< Clock >::tokenBucket_ private
Definition at line 370 of file TokenBucket.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/TokenBucket.h