proxygen: testing::gmock_generated_actions_test::NullaryFunctor Class Reference
testing::gmock_generated_actions_test::NullaryFunctor Class Reference
Public Member Functions
int operator() ()
int operator() ()
int operator() ()
Detailed Description
Definition at line 73 of file gmock-generated-actions_test.cc.
Member Function Documentation
int testing::gmock_generated_actions_test::NullaryFunctor::operator() () inline
Definition at line 75 of file gmock-generated-actions_test.cc.
 { return 2; }
int testing::gmock_generated_actions_test::NullaryFunctor::operator() () inline
Definition at line 75 of file gmock-generated-actions_test.cc.
References testing::gmock_generated_actions_test::ByConstRef(), testing::gmock_generated_actions_test::ByNonConstRef(), testing::gmock_generated_actions_test::g_done, testing::gmock_generated_actions_test::g_double, testing::gmock_generated_actions_test::Plus1(), testing::gmock_generated_actions_test::ReferencesGlobalDouble(), s, and testing::gmock_generated_actions_test::Unary().
 { return 2; }
int testing::gmock_generated_actions_test::NullaryFunctor::operator() () inline
Definition at line 75 of file gmock-generated-actions_test.cc.
References testing::gmock_generated_actions_test::ByConstRef(), testing::gmock_generated_actions_test::ByNonConstRef(), testing::gmock_generated_actions_test::g_done, testing::gmock_generated_actions_test::g_double, testing::gmock_generated_actions_test::Plus1(), testing::gmock_generated_actions_test::ReferencesGlobalDouble(), s, and testing::gmock_generated_actions_test::Unary().
 { return 2; }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-generated-actions_test.cc