proxygen: gmock_leak_test.GMockLeakTest Class Reference
gmock_leak_test.GMockLeakTest Class Reference
Public Member Functions
def testCatchesLeakedMockByDefault (self)
def testDoesNotCatchLeakedMockWhenDisabled (self)
def testCatchesLeakedMockWhenEnabled (self)
def testCatchesLeakedMockWhenEnabledWithExplictFlagValue (self)
def testCatchesMultipleLeakedMocks (self)
def testCatchesLeakedMockByDefault (self)
def testDoesNotCatchLeakedMockWhenDisabled (self)
def testCatchesLeakedMockWhenEnabled (self)
def testCatchesLeakedMockWhenEnabledWithExplictFlagValue (self)
def testCatchesMultipleLeakedMocks (self)
def testCatchesLeakedMockByDefault (self)
def testDoesNotCatchLeakedMockWhenDisabled (self)
def testCatchesLeakedMockWhenEnabled (self)
def testCatchesLeakedMockWhenEnabledWithExplictFlagValue (self)
def testCatchesMultipleLeakedMocks (self)
Detailed Description
Definition at line 56 of file gmock_leak_test.py.
Member Function Documentation
def gmock_leak_test.GMockLeakTest.testCatchesLeakedMockByDefault (self)
Definition at line 58 of file gmock_leak_test.py.
References gmock_test_utils.Subprocess.
Referenced by gmock_leak_test.GMockLeakTest.testCatchesLeakedMockByDefault().
   def testCatchesLeakedMockByDefault(self):
     self.assertNotEqual(
         0,
         gmock_test_utils.Subprocess(TEST_WITH_EXPECT_CALL,
                                     env=environ).exit_code)
     self.assertNotEqual(
         0,
         gmock_test_utils.Subprocess(TEST_WITH_ON_CALL,
                                     env=environ).exit_code)
def gmock_leak_test.GMockLeakTest.testCatchesLeakedMockByDefault (self)
Definition at line 58 of file gmock_leak_test.py.
References gmock_test_utils.Subprocess, and gmock_leak_test.GMockLeakTest.testCatchesLeakedMockByDefault().
   def testCatchesLeakedMockByDefault(self):
     self.assertNotEqual(
         0,
         gmock_test_utils.Subprocess(TEST_WITH_EXPECT_CALL,
                                     env=environ).exit_code)
     self.assertNotEqual(
         0,
         gmock_test_utils.Subprocess(TEST_WITH_ON_CALL,
                                     env=environ).exit_code)
def gmock_leak_test.GMockLeakTest.testCatchesLeakedMockByDefault (self)
Definition at line 58 of file gmock_leak_test.py.
References gmock_test_utils.Subprocess, and gmock_leak_test.GMockLeakTest.testCatchesLeakedMockByDefault().
   def testCatchesLeakedMockByDefault(self):
     self.assertNotEqual(
         0,
         gmock_test_utils.Subprocess(TEST_WITH_EXPECT_CALL,
                                     env=environ).exit_code)
     self.assertNotEqual(
         0,
         gmock_test_utils.Subprocess(TEST_WITH_ON_CALL,
                                     env=environ).exit_code)
def gmock_leak_test.GMockLeakTest.testCatchesLeakedMockWhenEnabled (self)
Definition at line 80 of file gmock_leak_test.py.
References gmock_test_utils.Subprocess, and gmock_leak_test.GMockLeakTest.testCatchesLeakedMockWhenEnabled().
   def testCatchesLeakedMockWhenEnabled(self):
     self.assertNotEqual(
         0,
         gmock_test_utils.Subprocess(TEST_WITH_EXPECT_CALL +
                                     ['--gmock_catch_leaked_mocks'],
                                     env=environ).exit_code)
     self.assertNotEqual(
         0,
         gmock_test_utils.Subprocess(TEST_WITH_ON_CALL +
                                     ['--gmock_catch_leaked_mocks'],
                                     env=environ).exit_code)
def gmock_leak_test.GMockLeakTest.testCatchesLeakedMockWhenEnabled (self)
Definition at line 80 of file gmock_leak_test.py.
References gmock_test_utils.Subprocess.
Referenced by gmock_leak_test.GMockLeakTest.testCatchesLeakedMockWhenEnabled().
   def testCatchesLeakedMockWhenEnabled(self):
     self.assertNotEqual(
         0,
         gmock_test_utils.Subprocess(TEST_WITH_EXPECT_CALL +
                                     ['--gmock_catch_leaked_mocks'],
                                     env=environ).exit_code)
     self.assertNotEqual(
         0,
         gmock_test_utils.Subprocess(TEST_WITH_ON_CALL +
                                     ['--gmock_catch_leaked_mocks'],
                                     env=environ).exit_code)
def gmock_leak_test.GMockLeakTest.testCatchesLeakedMockWhenEnabled (self)
Definition at line 80 of file gmock_leak_test.py.
References gmock_test_utils.Subprocess, and gmock_leak_test.GMockLeakTest.testCatchesLeakedMockWhenEnabled().
   def testCatchesLeakedMockWhenEnabled(self):
     self.assertNotEqual(
         0,
         gmock_test_utils.Subprocess(TEST_WITH_EXPECT_CALL +
                                     ['--gmock_catch_leaked_mocks'],
                                     env=environ).exit_code)
     self.assertNotEqual(
         0,
         gmock_test_utils.Subprocess(TEST_WITH_ON_CALL +
                                     ['--gmock_catch_leaked_mocks'],
                                     env=environ).exit_code)
def gmock_leak_test.GMockLeakTest.testCatchesLeakedMockWhenEnabledWithExplictFlagValue (self)
Definition at line 92 of file gmock_leak_test.py.
References gmock_test_utils.Subprocess.
Referenced by gmock_leak_test.GMockLeakTest.testCatchesLeakedMockWhenEnabledWithExplictFlagValue().
   def testCatchesLeakedMockWhenEnabledWithExplictFlagValue(self):
     self.assertNotEqual(
         0,
         gmock_test_utils.Subprocess(TEST_WITH_EXPECT_CALL +
                                     ['--gmock_catch_leaked_mocks=1'],
                                     env=environ).exit_code)
def gmock_leak_test.GMockLeakTest.testCatchesLeakedMockWhenEnabledWithExplictFlagValue (self)
Definition at line 92 of file gmock_leak_test.py.
References gmock_test_utils.Subprocess, and gmock_leak_test.GMockLeakTest.testCatchesLeakedMockWhenEnabledWithExplictFlagValue().
   def testCatchesLeakedMockWhenEnabledWithExplictFlagValue(self):
     self.assertNotEqual(
         0,
         gmock_test_utils.Subprocess(TEST_WITH_EXPECT_CALL +
                                     ['--gmock_catch_leaked_mocks=1'],
                                     env=environ).exit_code)
def gmock_leak_test.GMockLeakTest.testCatchesLeakedMockWhenEnabledWithExplictFlagValue (self)
Definition at line 92 of file gmock_leak_test.py.
References gmock_test_utils.Subprocess, and gmock_leak_test.GMockLeakTest.testCatchesLeakedMockWhenEnabledWithExplictFlagValue().
   def testCatchesLeakedMockWhenEnabledWithExplictFlagValue(self):
     self.assertNotEqual(
         0,
         gmock_test_utils.Subprocess(TEST_WITH_EXPECT_CALL +
                                     ['--gmock_catch_leaked_mocks=1'],
                                     env=environ).exit_code)
def gmock_leak_test.GMockLeakTest.testCatchesMultipleLeakedMocks (self)
Definition at line 99 of file gmock_leak_test.py.
References gmock_test_utils.Main(), gmock_test_utils.Subprocess, and gmock_leak_test.GMockLeakTest.testCatchesMultipleLeakedMocks().
   def testCatchesMultipleLeakedMocks(self):
     self.assertNotEqual(
         0,
         gmock_test_utils.Subprocess(TEST_MULTIPLE_LEAKS +
                                     ['--gmock_catch_leaked_mocks'],
                                     env=environ).exit_code)
def gmock_leak_test.GMockLeakTest.testCatchesMultipleLeakedMocks (self)
Definition at line 99 of file gmock_leak_test.py.
References gmock_test_utils.Main(), gmock_test_utils.Subprocess, and gmock_leak_test.GMockLeakTest.testCatchesMultipleLeakedMocks().
   def testCatchesMultipleLeakedMocks(self):
     self.assertNotEqual(
         0,
         gmock_test_utils.Subprocess(TEST_MULTIPLE_LEAKS +
                                     ['--gmock_catch_leaked_mocks'],
                                     env=environ).exit_code)
def gmock_leak_test.GMockLeakTest.testCatchesMultipleLeakedMocks (self)
Definition at line 99 of file gmock_leak_test.py.
References gmock_test_utils.Main(), and gmock_test_utils.Subprocess.
Referenced by gmock_leak_test.GMockLeakTest.testCatchesMultipleLeakedMocks().
   def testCatchesMultipleLeakedMocks(self):
     self.assertNotEqual(
         0,
         gmock_test_utils.Subprocess(TEST_MULTIPLE_LEAKS +
                                     ['--gmock_catch_leaked_mocks'],
                                     env=environ).exit_code)
def gmock_leak_test.GMockLeakTest.testDoesNotCatchLeakedMockWhenDisabled (self)
Definition at line 68 of file gmock_leak_test.py.
References gmock_test_utils.Subprocess, and gmock_leak_test.GMockLeakTest.testDoesNotCatchLeakedMockWhenDisabled().
   def testDoesNotCatchLeakedMockWhenDisabled(self):
     self.assertEquals(
         0,
         gmock_test_utils.Subprocess(TEST_WITH_EXPECT_CALL +
                                     ['--gmock_catch_leaked_mocks=0'],
                                     env=environ).exit_code)
     self.assertEquals(
         0,
         gmock_test_utils.Subprocess(TEST_WITH_ON_CALL +
                                     ['--gmock_catch_leaked_mocks=0'],
                                     env=environ).exit_code)
def gmock_leak_test.GMockLeakTest.testDoesNotCatchLeakedMockWhenDisabled (self)
Definition at line 68 of file gmock_leak_test.py.
References gmock_test_utils.Subprocess.
Referenced by gmock_leak_test.GMockLeakTest.testDoesNotCatchLeakedMockWhenDisabled().
   def testDoesNotCatchLeakedMockWhenDisabled(self):
     self.assertEquals(
         0,
         gmock_test_utils.Subprocess(TEST_WITH_EXPECT_CALL +
                                     ['--gmock_catch_leaked_mocks=0'],
                                     env=environ).exit_code)
     self.assertEquals(
         0,
         gmock_test_utils.Subprocess(TEST_WITH_ON_CALL +
                                     ['--gmock_catch_leaked_mocks=0'],
                                     env=environ).exit_code)
def gmock_leak_test.GMockLeakTest.testDoesNotCatchLeakedMockWhenDisabled (self)
Definition at line 68 of file gmock_leak_test.py.
References gmock_test_utils.Subprocess, and gmock_leak_test.GMockLeakTest.testDoesNotCatchLeakedMockWhenDisabled().
   def testDoesNotCatchLeakedMockWhenDisabled(self):
     self.assertEquals(
         0,
         gmock_test_utils.Subprocess(TEST_WITH_EXPECT_CALL +
                                     ['--gmock_catch_leaked_mocks=0'],
                                     env=environ).exit_code)
     self.assertEquals(
         0,
         gmock_test_utils.Subprocess(TEST_WITH_ON_CALL +
                                     ['--gmock_catch_leaked_mocks=0'],
                                     env=environ).exit_code)
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock_leak_test.py