proxygen: fizz::MockPlaintextWriteRecordLayer Class Reference
fizz::MockPlaintextWriteRecordLayer Class Reference
#include <Mocks.h>
Public Member Functions
MOCK_CONST_METHOD1 (_write, TLSContent(TLSMessage &msg))
TLSContent write (TLSMessage &&msg) const override
MOCK_CONST_METHOD1 (_writeInitialClientHello, TLSContent(Buf &))
TLSContent writeInitialClientHello (Buf encoded) const override
void setDefaults ()
Public Member Functions inherited from fizz::PlaintextWriteRecordLayer
~PlaintextWriteRecordLayer () override=default
EncryptionLevel getEncryptionLevel () const override
Public Member Functions inherited from fizz::WriteRecordLayer
virtual ~WriteRecordLayer ()=default
TLSContent writeAlert (Alert &&alert) const
TLSContent writeAppData (std::unique_ptr< folly::IOBuf > &&appData) const
template<typename... Args>
TLSContent writeHandshake (Buf &&encodedHandshakeMsg, Args &&...args) const
void setProtocolVersion (ProtocolVersion version) const
Additional Inherited Members
Protected Attributes inherited from fizz::WriteRecordLayer
ProtocolVersion recordVersion_ {ProtocolVersion::tls_1_2}
bool useAdditionalData_ {true}
Detailed Description
Definition at line 67 of file Mocks.h.
Member Function Documentation
fizz::MockPlaintextWriteRecordLayer::MOCK_CONST_METHOD1 (_write , TLSContent(TLSMessage &msg))
fizz::MockPlaintextWriteRecordLayer::MOCK_CONST_METHOD1 (_writeInitialClientHello , TLSContent(Buf &))
void fizz::MockPlaintextWriteRecordLayer::setDefaults () inline
Definition at line 79 of file Mocks.h.
References testing::_, fizz::TLSContent::contentType, folly::IOBuf::copyBuffer(), fizz::TLSContent::data, fizz::TLSContent::encryptionLevel, testing::InvokeWithoutArgs(), ON_CALL, and fizz::setWriteDefaults().
                      {
     setWriteDefaults(this);
     ON_CALL(*this, _writeInitialClientHello(_))
         .WillByDefault(InvokeWithoutArgs([]() {
           TLSContent record;
           record.contentType = ContentType::handshake;
           record.data = folly::IOBuf::copyBuffer("handshake");
           record.encryptionLevel = EncryptionLevel::Plaintext;
           return record;
         }));
   }
TLSContent fizz::MockPlaintextWriteRecordLayer::write (TLSMessage && msg) const inline override virtual
Reimplemented from fizz::PlaintextWriteRecordLayer.
Definition at line 70 of file Mocks.h.
References MOCK_CONST_METHOD1.
{
     return _write(msg);
   }
TLSContent fizz::MockPlaintextWriteRecordLayer::writeInitialClientHello (Buf encodedClientHello) const inline override virtual
Write the initial ClientHello handshake message. This is a separate method as the record encoding can be slightly different since the version has not been negotiated yet.
Reimplemented from fizz::PlaintextWriteRecordLayer.
Definition at line 75 of file Mocks.h.
{
     return _writeInitialClientHello(encoded);
   }
The documentation for this class was generated from the following file:
proxygen/fizz/fizz/record/test/Mocks.h