proxygen: fizz::KeyDerivation Class Reference
fizz::KeyDerivation Class Reference abstract
#include <KeyDerivation.h>
Public Member Functions
virtual ~KeyDerivation ()=default
virtual size_t hashLength () const =0
virtual folly::ByteRange blankHash () const =0
virtual Buf expandLabel (folly::ByteRange secret, folly::StringPiece label, Buf hashValue, uint16_t length)=0
virtual std::vector< uint8_t > deriveSecret (folly::ByteRange secret, folly::StringPiece label, folly::ByteRange messageHash)=0
virtual Buf hkdfExpand (folly::ByteRange secret, Buf info, uint16_t length)=0
virtual std::vector< uint8_t > hkdfExtract (folly::ByteRange salt, folly::ByteRange ikm)=0
virtual void hash (const folly::IOBuf &in, folly::MutableByteRange out)=0
virtual void hmac (folly::ByteRange key, const folly::IOBuf &in, folly::MutableByteRange out)=0
Detailed Description
Interface for common TLS 1.3 key derivation functions.
Definition at line 19 of file KeyDerivation.h.
Constructor & Destructor Documentation
virtual fizz::KeyDerivation::~KeyDerivation () virtual default
Member Function Documentation
virtual folly::ByteRange fizz::KeyDerivation::blankHash () const pure virtual
Returns the hash of a blank input (ie Hash("")).
Implemented in fizz::KeyDerivationImpl< Hash >.
virtual std::vector<uint8_t> fizz::KeyDerivation::deriveSecret (folly::ByteRange secret, folly::StringPiece label, folly::ByteRange messageHash) pure virtual
Implemented in fizz::KeyDerivationImpl< Hash >.
Referenced by fizz::KeyDerivationImpl< Hash >::blankHash(), and fizz::MockKeyDerivation::hkdfExpand().
virtual Buf fizz::KeyDerivation::expandLabel (folly::ByteRange secret, folly::StringPiece label, Buf hashValue, uint16_t length) pure virtual
Implemented in fizz::KeyDerivationImpl< Hash >, and fizz::MockKeyDerivation.
Referenced by fizz::KeyDerivationImpl< Hash >::blankHash().
virtual void fizz::KeyDerivation::hash (const folly::IOBuf & in, folly::MutableByteRange out) pure virtual
Implemented in fizz::KeyDerivationImpl< Hash >.
Referenced by fizz::MockKeyDerivation::hkdfExpand().
virtual size_t fizz::KeyDerivation::hashLength () const pure virtual
Implemented in fizz::KeyDerivationImpl< Hash >.
virtual Buf fizz::KeyDerivation::hkdfExpand (folly::ByteRange secret, Buf info, uint16_t length) pure virtual
Performs HDKF expansion.
Implemented in fizz::KeyDerivationImpl< Hash >, and fizz::MockKeyDerivation.
Referenced by fizz::KeyDerivationImpl< Hash >::blankHash().
virtual std::vector<uint8_t> fizz::KeyDerivation::hkdfExtract (folly::ByteRange salt, folly::ByteRange ikm) pure virtual
Implemented in fizz::KeyDerivationImpl< Hash >.
Referenced by fizz::MockKeyDerivation::hkdfExpand().
virtual void fizz::KeyDerivation::hmac (folly::ByteRange key, const folly::IOBuf & in, folly::MutableByteRange out) pure virtual
Implemented in fizz::KeyDerivationImpl< Hash >.
Referenced by fizz::MockKeyDerivation::hkdfExpand().
The documentation for this class was generated from the following file:
proxygen/fizz/fizz/crypto/KeyDerivation.h