proxygen: folly::XlogCategoryInfo< IsInHeaderFile > Class Template Reference
folly::XlogCategoryInfo< IsInHeaderFile > Class Template Reference
#include <LogStreamProcessor.h>
Public Member Functions
bool isInitialized () const
LogCategory * init (folly::StringPiece categoryName, bool isOverridden)
LogCategory * getCategory (XlogFileScopeInfo *)
XlogCategoryInfo< IsInHeaderFile > * getInfo (XlogFileScopeInfo *)
Private Attributes
std::atomic< bool > isInitialized_
LogCategory * category_
Detailed Description
template<bool IsInHeaderFile>
class folly::XlogCategoryInfo< IsInHeaderFile >
Definition at line 74 of file LogStreamProcessor.h.
Member Function Documentation
template<bool IsInHeaderFile> LogCategory* folly::XlogCategoryInfo< IsInHeaderFile >::getCategory (XlogFileScopeInfo *) inline
Definition at line 427 of file xlog.h.
Referenced by folly::LogStreamProcessor::LogStreamProcessor().
{
     return category_;
   }
template<bool IsInHeaderFile> XlogCategoryInfo<IsInHeaderFile>* folly::XlogCategoryInfo< IsInHeaderFile >::getInfo (XlogFileScopeInfo *) inline
Get a pointer to pass into the LogStreamProcessor constructor, so that it is able to look up the LogCategory information.
Definition at line 435 of file xlog.h.
{
     return this;
   }
template<bool IsInHeaderFile> LogCategory * folly::XlogCategoryInfo< IsInHeaderFile >::init (folly::StringPiece categoryName, bool isOverridden)
Definition at line 86 of file xlog.cpp.
References folly::LoggerDB::get(), folly::getXlogCategoryNameForFile(), folly::XlogLevelInfo< IsInHeaderFile >::loadLevelFull(), folly::UNINITIALIZED, UNLIKELY, folly::LoggerDB::xlogInit(), and folly::LoggerDB::xlogInitCategory().
Referenced by folly::LogStreamProcessor::LogStreamProcessor().
{
   return LoggerDB::get().xlogInitCategory(
       isOverridden ? categoryName : getXlogCategoryNameForFile(categoryName),
       &category_,
       &isInitialized_);
 }
template<bool IsInHeaderFile> bool folly::XlogCategoryInfo< IsInHeaderFile >::isInitialized () const inline
Definition at line 421 of file xlog.h.
References folly::init().
Referenced by folly::LogStreamProcessor::LogStreamProcessor().
{
     return isInitialized_.load(std::memory_order_acquire);
   }
Member Data Documentation
template<bool IsInHeaderFile> LogCategory* folly::XlogCategoryInfo< IsInHeaderFile >::category_ private
Definition at line 442 of file xlog.h.
template<bool IsInHeaderFile> std::atomic<bool> folly::XlogCategoryInfo< IsInHeaderFile >::isInitialized_ private
Definition at line 441 of file xlog.h.
The documentation for this class was generated from the following files:
proxygen/folly/folly/logging/LogStreamProcessor.h
proxygen/folly/folly/logging/xlog.h
proxygen/folly/folly/logging/xlog.cpp