proxygen: testing::internal::MatchMatrix Class Reference
testing::internal::MatchMatrix Class Reference
#include <gmock-matchers.h>
Public Member Functions
MatchMatrix (size_t num_elements, size_t num_matchers)
size_t LhsSize () const
size_t RhsSize () const
bool HasEdge (size_t ilhs, size_t irhs) const
void SetEdge (size_t ilhs, size_t irhs, bool b)
bool NextGraph ()
void Randomize ()
string DebugString () const
MatchMatrix (size_t num_elements, size_t num_matchers)
size_t LhsSize () const
size_t RhsSize () const
bool HasEdge (size_t ilhs, size_t irhs) const
void SetEdge (size_t ilhs, size_t irhs, bool b)
bool NextGraph ()
void Randomize ()
string DebugString () const
MatchMatrix (size_t num_elements, size_t num_matchers)
size_t LhsSize () const
size_t RhsSize () const
bool HasEdge (size_t ilhs, size_t irhs) const
void SetEdge (size_t ilhs, size_t irhs, bool b)
bool NextGraph ()
void Randomize ()
string DebugString () const
Private Member Functions
size_t SpaceIndex (size_t ilhs, size_t irhs) const
size_t SpaceIndex (size_t ilhs, size_t irhs) const
size_t SpaceIndex (size_t ilhs, size_t irhs) const
Private Attributes
size_t num_elements_
size_t num_matchers_
::std::vector< char > matched_
Detailed Description
Definition at line 3257 of file gmock-matchers.h.
Constructor & Destructor Documentation
testing::internal::MatchMatrix::MatchMatrix (size_t num_elements, size_t num_matchers) inline
Definition at line 3259 of file gmock-matchers.h.
       : num_elements_(num_elements),
         num_matchers_(num_matchers),
         matched_(num_elements_* num_matchers_, 0) {
   }
testing::internal::MatchMatrix::MatchMatrix (size_t num_elements, size_t num_matchers) inline
Definition at line 3259 of file gmock-matchers.h.
       : num_elements_(num_elements),
         num_matchers_(num_matchers),
         matched_(num_elements_* num_matchers_, 0) {
   }
testing::internal::MatchMatrix::MatchMatrix (size_t num_elements, size_t num_matchers) inline
Definition at line 3259 of file gmock-matchers.h.
       : num_elements_(num_elements),
         num_matchers_(num_matchers),
         matched_(num_elements_* num_matchers_, 0) {
   }
Member Function Documentation
string testing::internal::MatchMatrix::DebugString () const
Definition at line 382 of file gmock-matchers.cc.
References i.
Referenced by testing::gmock_matchers_test::TEST_F(), and testing::gmock_matchers_test::TEST_P().
{
   ::std::stringstream ss;
   const char *sep = "";
   for (size_t i = 0; i < LhsSize(); ++i) {
     ss << sep;
     for (size_t j = 0; j < RhsSize(); ++j) {
       ss << HasEdge(i, j);
     }
     sep = ";";
   }
   return ss.str();
 }
string testing::internal::MatchMatrix::DebugString () const
string testing::internal::MatchMatrix::DebugString () const
bool testing::internal::MatchMatrix::HasEdge (size_t ilhs, size_t irhs) const inline
Definition at line 3267 of file gmock-matchers.h.
{
     return matched_[SpaceIndex(ilhs, irhs)] == 1;
   }
bool testing::internal::MatchMatrix::HasEdge (size_t ilhs, size_t irhs) const inline
Definition at line 3267 of file gmock-matchers.h.
{
     return matched_[SpaceIndex(ilhs, irhs)] == 1;
   }
bool testing::internal::MatchMatrix::HasEdge (size_t ilhs, size_t irhs) const inline
Definition at line 3267 of file gmock-matchers.h.
Referenced by testing::internal::LogElementMatcherPairVec(), testing::gmock_matchers_test::TEST_P(), and testing::internal::UnorderedElementsAreMatcherImplBase::VerifyAllElementsAndMatchersAreMatched().
{
     return matched_[SpaceIndex(ilhs, irhs)] == 1;
   }
size_t testing::internal::MatchMatrix::LhsSize () const inline
Definition at line 3265 of file gmock-matchers.h.
 { return num_elements_; }
size_t testing::internal::MatchMatrix::LhsSize () const inline
Definition at line 3265 of file gmock-matchers.h.
 { return num_elements_; }
size_t testing::internal::MatchMatrix::LhsSize () const inline
Definition at line 3265 of file gmock-matchers.h.
Referenced by testing::internal::LogElementMatcherPairVec(), testing::internal::UnorderedElementsAreMatcherImpl< Container >::MatchAndExplain(), testing::gmock_matchers_test::TEST_P(), and testing::internal::UnorderedElementsAreMatcherImplBase::VerifyAllElementsAndMatchersAreMatched().
 { return num_elements_; }
bool testing::internal::MatchMatrix::NextGraph ()
Definition at line 359 of file gmock-matchers.cc.
References b.
Referenced by testing::gmock_matchers_test::TEST_P().
{
   for (size_t ilhs = 0; ilhs < LhsSize(); ++ilhs) {
     for (size_t irhs = 0; irhs < RhsSize(); ++irhs) {
       char& b = matched_[SpaceIndex(ilhs, irhs)];
       if (!b) {
         b = 1;
         return true;
       }
       b = 0;
     }
   }
   return false;
 }
bool testing::internal::MatchMatrix::NextGraph ()
bool testing::internal::MatchMatrix::NextGraph ()
void testing::internal::MatchMatrix::Randomize ()
void testing::internal::MatchMatrix::Randomize ()
Definition at line 373 of file gmock-matchers.cc.
References b.
Referenced by testing::gmock_matchers_test::TEST_P().
{
   for (size_t ilhs = 0; ilhs < LhsSize(); ++ilhs) {
     for (size_t irhs = 0; irhs < RhsSize(); ++irhs) {
       char& b = matched_[SpaceIndex(ilhs, irhs)];
       b = static_cast<char>(rand() & 1);  // NOLINT
     }
   }
 }
void testing::internal::MatchMatrix::Randomize ()
size_t testing::internal::MatchMatrix::RhsSize () const inline
Definition at line 3266 of file gmock-matchers.h.
 { return num_matchers_; }
size_t testing::internal::MatchMatrix::RhsSize () const inline
Definition at line 3266 of file gmock-matchers.h.
 { return num_matchers_; }
size_t testing::internal::MatchMatrix::RhsSize () const inline
Definition at line 3266 of file gmock-matchers.h.
Referenced by testing::internal::FindPairing(), testing::internal::LogElementMatcherPairVec(), testing::gmock_matchers_test::TEST_P(), and testing::internal::UnorderedElementsAreMatcherImplBase::VerifyAllElementsAndMatchersAreMatched().
 { return num_matchers_; }
void testing::internal::MatchMatrix::SetEdge (size_t ilhs, size_t irhs, bool b) inline
Definition at line 3270 of file gmock-matchers.h.
{
     matched_[SpaceIndex(ilhs, irhs)] = b ? 1 : 0;
   }
void testing::internal::MatchMatrix::SetEdge (size_t ilhs, size_t irhs, bool b) inline
Definition at line 3270 of file gmock-matchers.h.
Referenced by testing::internal::UnorderedElementsAreMatcherImpl< Container >::AnalyzeElements(), and testing::gmock_matchers_test::TEST_F().
{
     matched_[SpaceIndex(ilhs, irhs)] = b ? 1 : 0;
   }
void testing::internal::MatchMatrix::SetEdge (size_t ilhs, size_t irhs, bool b) inline
Definition at line 3270 of file gmock-matchers.h.
{
     matched_[SpaceIndex(ilhs, irhs)] = b ? 1 : 0;
   }
size_t testing::internal::MatchMatrix::SpaceIndex (size_t ilhs, size_t irhs) const inline private
Definition at line 3284 of file gmock-matchers.h.
References testing::internal::FindMaxBipartiteMatching(), testing::internal::FindPairing(), g(), and GTEST_API_.
{
     return ilhs * num_matchers_ + irhs;
   }
size_t testing::internal::MatchMatrix::SpaceIndex (size_t ilhs, size_t irhs) const inline private
Definition at line 3284 of file gmock-matchers.h.
{
     return ilhs * num_matchers_ + irhs;
   }
size_t testing::internal::MatchMatrix::SpaceIndex (size_t ilhs, size_t irhs) const inline private
Definition at line 3284 of file gmock-matchers.h.
References testing::internal::FindMaxBipartiteMatching(), testing::internal::FindPairing(), g(), and GTEST_API_.
{
     return ilhs * num_matchers_ + irhs;
   }
Member Data Documentation
std::vector< char > testing::internal::MatchMatrix::matched_ private
Definition at line 3294 of file gmock-matchers.h.
size_t testing::internal::MatchMatrix::num_elements_ private
Definition at line 3288 of file gmock-matchers.h.
size_t testing::internal::MatchMatrix::num_matchers_ private
Definition at line 3289 of file gmock-matchers.h.
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h
proxygen/fizz/build_/gtest/src/gtest/googlemock/src/gmock-matchers.cc