proxygen: folly::basic_once_flag< Mutex, Atom > Class Template Reference
folly::basic_once_flag< Mutex, Atom > Class Template Reference
#include <CallOnce.h>
Public Member Functions
constexpr basic_once_flag () noexcept=default
basic_once_flag (const basic_once_flag &)=delete
basic_once_flag & operator= (const basic_once_flag &)=delete
Private Member Functions
template<typename F , typename... Args>
FOLLY_ALWAYS_INLINE void call_once (F &&f, Args &&...args)
template<typename F , typename... Args>
FOLLY_NOINLINE void call_once_slow (F &&f, Args &&...args)
Private Attributes
Atom< bool > called_ {false}
Mutex mutex_
Friends
template<typename Mutex_ , template< typename > class Atom_, typename F , typename... Args>
void call_once (basic_once_flag< Mutex_, Atom_ > &, F &&, Args &&...)
Detailed Description
template<typename Mutex, template< typename > class Atom>
class folly::basic_once_flag< Mutex, Atom >
Definition at line 31 of file CallOnce.h.
Constructor & Destructor Documentation
template<typename Mutex, template< typename > class Atom> constexpr folly::basic_once_flag< Mutex, Atom >::basic_once_flag () default noexcept
Referenced by folly::call_once().
template<typename Mutex, template< typename > class Atom> folly::basic_once_flag< Mutex, Atom >::basic_once_flag (const basic_once_flag< Mutex, Atom > &) delete
Member Function Documentation
template<typename Mutex, template< typename > class Atom> template<typename F , typename... Args> FOLLY_ALWAYS_INLINE void folly::basic_once_flag< Mutex, Atom >::call_once (F && f, Args &&... args) inline private
Definition at line 81 of file CallOnce.h.
{
     if (LIKELY(called_.load(std::memory_order_acquire))) {
       return;
     }
     call_once_slow(std::forward<F>(f), std::forward<Args>(args)...);
   }
template<typename Mutex, template< typename > class Atom> template<typename F , typename... Args> FOLLY_NOINLINE void folly::basic_once_flag< Mutex, Atom >::call_once_slow (F && f, Args &&... args) inline private
Definition at line 89 of file CallOnce.h.
Referenced by folly::basic_once_flag< SharedMutex >::call_once().
{
     std::lock_guard<Mutex> lock(mutex_);
     if (called_.load(std::memory_order_relaxed)) {
       return;
     }
     invoke(std::forward<F>(f), std::forward<Args>(args)...);
     called_.store(true, std::memory_order_release);
   }
template<typename Mutex, template< typename > class Atom> basic_once_flag& folly::basic_once_flag< Mutex, Atom >::operator= (const basic_once_flag< Mutex, Atom > &) delete
Referenced by folly::call_once().
Friends And Related Function Documentation
template<typename Mutex, template< typename > class Atom> template<typename Mutex_ , template< typename > class Atom_, typename F , typename... Args> void call_once (basic_once_flag< Mutex_, Atom_ > & , F && , Args && ...) friend
Referenced by folly::call_once().
Member Data Documentation
template<typename Mutex, template< typename > class Atom> Atom<bool> folly::basic_once_flag< Mutex, Atom >::called_ {false} private
Definition at line 98 of file CallOnce.h.
Referenced by folly::basic_once_flag< SharedMutex >::call_once(), and folly::basic_once_flag< SharedMutex >::call_once_slow().
template<typename Mutex, template< typename > class Atom> Mutex folly::basic_once_flag< Mutex, Atom >::mutex_ private
Definition at line 99 of file CallOnce.h.
Referenced by folly::basic_once_flag< SharedMutex >::call_once_slow().
The documentation for this class was generated from the following file:
proxygen/folly/folly/synchronization/CallOnce.h