proxygen: testing::internal::DummyMatchResultListener Class Reference
testing::internal::DummyMatchResultListener Class Reference
#include <gmock-matchers.h>
Public Member Functions
DummyMatchResultListener ()
DummyMatchResultListener ()
DummyMatchResultListener ()
Public Member Functions inherited from testing::MatchResultListener
MatchResultListener (::std::ostream *os)
virtual ~MatchResultListener ()=0
template<typename T >
MatchResultListener & operator<< (const T &x)
::std::ostream * stream ()
bool IsInterested () const
MatchResultListener (::std::ostream *os)
virtual ~MatchResultListener ()=0
template<typename T >
MatchResultListener & operator<< (const T &x)
::std::ostream * stream ()
bool IsInterested () const
MatchResultListener (::std::ostream *os)
virtual ~MatchResultListener ()=0
template<typename T >
MatchResultListener & operator<< (const T &x)
::std::ostream * stream ()
bool IsInterested () const
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (DummyMatchResultListener)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (DummyMatchResultListener)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (DummyMatchResultListener)
Detailed Description
Definition at line 228 of file gmock-matchers.h.
Constructor & Destructor Documentation
testing::internal::DummyMatchResultListener::DummyMatchResultListener () inline
Definition at line 230 of file gmock-matchers.h.
References testing::MatchResultListener::GTEST_DISALLOW_COPY_AND_ASSIGN_().
 : MatchResultListener(NULL) {}
testing::internal::DummyMatchResultListener::DummyMatchResultListener () inline
Definition at line 230 of file gmock-matchers.h.
References testing::MatchResultListener::GTEST_DISALLOW_COPY_AND_ASSIGN_().
 : MatchResultListener(NULL) {}
testing::internal::DummyMatchResultListener::DummyMatchResultListener () inline
Definition at line 230 of file gmock-matchers.h.
References testing::MatchResultListener::GTEST_DISALLOW_COPY_AND_ASSIGN_().
 : MatchResultListener(NULL) {}
Member Function Documentation
testing::internal::DummyMatchResultListener::GTEST_DISALLOW_COPY_AND_ASSIGN_ (DummyMatchResultListener) private
testing::internal::DummyMatchResultListener::GTEST_DISALLOW_COPY_AND_ASSIGN_ (DummyMatchResultListener) private
testing::internal::DummyMatchResultListener::GTEST_DISALLOW_COPY_AND_ASSIGN_ (DummyMatchResultListener) private
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h