proxygen: testing::internal::TestResultAccessor Class Reference
testing::internal::TestResultAccessor Class Reference
#include <gtest-internal-inl.h>
Static Public Member Functions
static void RecordProperty (TestResult *test_result, const std::string &xml_element, const TestProperty &property)
static void ClearTestPartResults (TestResult *test_result)
static const std::vector< testing::TestPartResult > & test_part_results (const TestResult &test_result)
static void RecordProperty (TestResult *test_result, const std::string &xml_element, const TestProperty &property)
static void ClearTestPartResults (TestResult *test_result)
static const std::vector< testing::TestPartResult > & test_part_results (const TestResult &test_result)
static void RecordProperty (TestResult *test_result, const std::string &xml_element, const TestProperty &property)
static void ClearTestPartResults (TestResult *test_result)
static const std::vector< testing::TestPartResult > & test_part_results (const TestResult &test_result)
Detailed Description
Definition at line 1014 of file gtest-internal-inl.h.
Member Function Documentation
static void testing::internal::TestResultAccessor::ClearTestPartResults (TestResult * test_result) inline static
Definition at line 1022 of file gtest-internal-inl.h.
References testing::TestResult::ClearTestPartResults().
Referenced by operator<<().
{
     test_result->ClearTestPartResults();
   }
static void testing::internal::TestResultAccessor::ClearTestPartResults (TestResult * test_result) inline static
Definition at line 1022 of file gtest-internal-inl.h.
References testing::TestResult::ClearTestPartResults().
{
     test_result->ClearTestPartResults();
   }
static void testing::internal::TestResultAccessor::ClearTestPartResults (TestResult * test_result) inline static
Definition at line 1022 of file gtest-internal-inl.h.
References testing::TestResult::ClearTestPartResults().
{
     test_result->ClearTestPartResults();
   }
static void testing::internal::TestResultAccessor::RecordProperty (TestResult * test_result, const std::string & xml_element, const TestProperty & property) inline static
Definition at line 1016 of file gtest-internal-inl.h.
References testing::TestResult::RecordProperty().
{
     test_result->RecordProperty(xml_element, property);
   }
static void testing::internal::TestResultAccessor::RecordProperty (TestResult * test_result, const std::string & xml_element, const TestProperty & property) inline static
Definition at line 1016 of file gtest-internal-inl.h.
References testing::TestResult::RecordProperty().
{
     test_result->RecordProperty(xml_element, property);
   }
static void testing::internal::TestResultAccessor::RecordProperty (TestResult * test_result, const std::string & xml_element, const TestProperty & property) inline static
Definition at line 1016 of file gtest-internal-inl.h.
References testing::TestResult::RecordProperty().
{
     test_result->RecordProperty(xml_element, property);
   }
static const std::vector<testing::TestPartResult>& testing::internal::TestResultAccessor::test_part_results (const TestResult & test_result) inline static
Definition at line 1026 of file gtest-internal-inl.h.
References folly::netops::close(), testing::TestCase::elapsed_time(), testing::UnitTest::elapsed_time(), testing::TestPartResult::file_name(), GTEST_API_, GTEST_CHECK_, GTEST_DISALLOW_COPY_AND_ASSIGN_, GTEST_LOG_, testing::TestPartResult::line_number(), testing::TestPartResult::message(), testing::TestInfo::name(), testing::TestCase::name(), testing::TestCase::Passed(), testing::UnitTest::Passed(), testing::TestInfo::result(), testing::internal::StreamableToString(), string, testing::TestResult::test_part_results(), value, and fizz::detail::write().
{
     return test_result.test_part_results();
   }
static const std::vector<testing::TestPartResult>& testing::internal::TestResultAccessor::test_part_results (const TestResult & test_result) inline static
Definition at line 1026 of file gtest-internal-inl.h.
References folly::netops::close(), testing::TestCase::elapsed_time(), testing::UnitTest::elapsed_time(), testing::TestPartResult::file_name(), GTEST_API_, GTEST_CHECK_, GTEST_DISALLOW_COPY_AND_ASSIGN_, GTEST_LOG_, testing::TestPartResult::line_number(), testing::TestPartResult::message(), testing::TestInfo::name(), testing::TestCase::name(), testing::TestCase::Passed(), testing::UnitTest::Passed(), testing::TestInfo::result(), testing::internal::StreamableToString(), string, testing::TestResult::test_part_results(), value, and fizz::detail::write().
{
     return test_result.test_part_results();
   }
static const std::vector<testing::TestPartResult>& testing::internal::TestResultAccessor::test_part_results (const TestResult & test_result) inline static
Definition at line 1026 of file gtest-internal-inl.h.
References folly::netops::close(), testing::TestCase::elapsed_time(), testing::UnitTest::elapsed_time(), testing::TestPartResult::file_name(), GTEST_API_, GTEST_CHECK_, GTEST_DISALLOW_COPY_AND_ASSIGN_, GTEST_LOG_, testing::TestPartResult::line_number(), testing::TestPartResult::message(), testing::TestInfo::name(), testing::TestCase::name(), testing::TestCase::Passed(), testing::UnitTest::Passed(), testing::TestInfo::result(), testing::internal::StreamableToString(), string, testing::TestResult::test_part_results(), value, and fizz::detail::write().
{
     return test_result.test_part_results();
   }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest-internal-inl.h