proxygen: TestExtendingFormatter< containerMode, Args > Class Template Reference
TestExtendingFormatter< containerMode, Args > Class Template Reference
Private Member Functions
TestExtendingFormatter (StringPiece &str, Args &&...args)
template<size_t K, class Callback >
void doFormatArg (FormatArg &arg, Callback &cb) const
Friends
class BaseFormatter< TestExtendingFormatter< containerMode, Args... >, containerMode, Args... >
template<class... A>
std::string texsformat (StringPiece fmt, A &&...arg)
Additional Inherited Members
Public Types inherited from folly::BaseFormatter< TestExtendingFormatter< containerMode, Args... >, containerMode, Args... >
typedef detail::FormatterTag IsFormatter
typedef BaseFormatter BaseType
Public Member Functions inherited from folly::BaseFormatter< TestExtendingFormatter< containerMode, Args... >, containerMode, Args... >
void operator() (Output &out) const
std::enable_if< IsSomeString< Str >::value >::type appendTo (Str &str) const
std::string str () const
fbstring fbstr () const
Detailed Description
template<bool containerMode, class... Args>
class TestExtendingFormatter< containerMode, Args >
Definition at line 468 of file FormatTest.cpp.
Constructor & Destructor Documentation
template<bool containerMode, class... Args> TestExtendingFormatter< containerMode, Args >::TestExtendingFormatter (StringPiece & str, Args &&... args) inline explicit private
Definition at line 477 of file FormatTest.cpp.
       : BaseFormatter<
             TestExtendingFormatter<containerMode, Args...>,
             containerMode,
             Args...>(str, std::forward<Args>(args)...) {}
Member Function Documentation
template<bool containerMode, class... Args> template<size_t K, class Callback > void TestExtendingFormatter< containerMode, Args >::doFormatArg (FormatArg & arg, Callback & cb) const inline private
Definition at line 484 of file FormatTest.cpp.
References testing::Args(), folly::format(), s, folly::sformat(), and string.
{
     std::string result;
     auto appender = [&result](StringPiece s) {
       result.append(s.data(), s.size());
     };
     this->template getFormatValue<K>().format(arg, appender);
     result = sformat("{{{}}}", result);
     cb(StringPiece(result));
   }
Friends And Related Function Documentation
template<bool containerMode, class... Args> friend class BaseFormatter< TestExtendingFormatter< containerMode, Args... >,containerMode,Args... > friend
Definition at line 497 of file FormatTest.cpp.
template<bool containerMode, class... Args> template<class... A> std::string texsformat (StringPiece fmt, A &&... arg) friend
The documentation for this class was generated from the following file:
proxygen/folly/folly/test/FormatTest.cpp