proxygen: folly::pushmi::flow_receiver< VF, EF, DF, StrtF > Class Template Reference
folly::pushmi::flow_receiver< VF, EF, DF, StrtF > Class Template Reference
#include <flow_receiver.h>
Public Types
using properties = property_set< is_receiver<>, is_flow<>>
Public Member Functions
flow_receiver ()=default
constexpr flow_receiver (VF nf)
constexpr flow_receiver (EF ef)
constexpr flow_receiver (DF df)
constexpr flow_receiver (EF ef, DF df)
constexpr flow_receiver (VF nf, EF ef, DF df=DF{}, StrtF strtf=StrtF{})
requires Invocable< VF &, V > void value (V &&v)
requires Invocable< EF &, E > void error (E e) noexcept
void done ()
requires Invocable< StrtF &, Up && > void starting (Up &&up)
Private Attributes
bool done_ = false
bool started_ = false
VF nf_
EF ef_
DF df_
StrtF strtf_
Detailed Description
template<class VF, class EF, class DF, class StrtF>
class folly::pushmi::flow_receiver< VF, EF, DF, StrtF >
Definition at line 160 of file flow_receiver.h.
Member Typedef Documentation
template<class VF , class EF , class DF , class StrtF > using folly::pushmi::flow_receiver< VF, EF, DF, StrtF >::properties = property_set<is_receiver<>, is_flow<>>
Definition at line 169 of file flow_receiver.h.
Constructor & Destructor Documentation
template<class VF , class EF , class DF , class StrtF > folly::pushmi::flow_receiver< VF, EF, DF, StrtF >::flow_receiver () default
template<class VF , class EF , class DF , class StrtF > constexpr folly::pushmi::flow_receiver< VF, EF, DF, StrtF >::flow_receiver (VF nf) inline explicit
Definition at line 179 of file flow_receiver.h.
       : flow_receiver(std::move(nf), EF{}, DF{}) {}
template<class VF , class EF , class DF , class StrtF > constexpr folly::pushmi::flow_receiver< VF, EF, DF, StrtF >::flow_receiver (EF ef) inline explicit
Definition at line 181 of file flow_receiver.h.
References folly::gen::move.
       : flow_receiver(VF{}, std::move(ef), DF{}) {}
template<class VF , class EF , class DF , class StrtF > constexpr folly::pushmi::flow_receiver< VF, EF, DF, StrtF >::flow_receiver (DF df) inline explicit
Definition at line 183 of file flow_receiver.h.
References folly::gen::move.
       : flow_receiver(VF{}, EF{}, std::move(df)) {}
template<class VF , class EF , class DF , class StrtF > constexpr folly::pushmi::flow_receiver< VF, EF, DF, StrtF >::flow_receiver (EF ef, DF df) inline
Definition at line 185 of file flow_receiver.h.
       : nf_(), ef_(std::move(ef)), df_(std::move(df)) {}
template<class VF , class EF , class DF , class StrtF > constexpr folly::pushmi::flow_receiver< VF, EF, DF, StrtF >::flow_receiver (VF nf, EF ef, DF df = DF{}, StrtF strtf = StrtF{}) inline
Definition at line 187 of file flow_receiver.h.
References folly::gen::move, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
                 {},
       StrtF strtf = StrtF{})
       : nf_(std::move(nf)),
         ef_(std::move(ef)),
         df_(std::move(df)),
         strtf_(std::move(strtf)) {}
Member Function Documentation
template<class VF , class EF , class DF , class StrtF > void folly::pushmi::flow_receiver< VF, EF, DF, StrtF >::done () inline
Definition at line 212 of file flow_receiver.h.
References folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
               {
     if (!started_) {std::abort();}
     if (done_){ return; }
     done_ = true;
     df_();
   }
template<class VF , class EF , class DF , class StrtF > requires Invocable<EF&, E> void folly::pushmi::flow_receiver< VF, EF, DF, StrtF >::error (E e) inline noexcept
Definition at line 205 of file flow_receiver.h.
References folly::gen::move.
{
     static_assert(NothrowInvocable<EF&, E>, "error function must be noexcept");
     if (!started_) {std::abort();}
     if (done_){ return; }
     done_ = true;
     ef_(std::move(e));
   }
template<class VF , class EF , class DF , class StrtF > requires Invocable<StrtF&, Up&&> void folly::pushmi::flow_receiver< VF, EF, DF, StrtF >::starting (Up && up) inline
Definition at line 220 of file flow_receiver.h.
References PUSHMI_TYPE_CONSTRAINT, and folly::pushmi::requires().
{
     if (started_) {std::abort();}
     started_ = true;
     strtf_( (Up &&) up);
   }
template<class VF , class EF , class DF , class StrtF > requires Invocable<VF&, V> void folly::pushmi::flow_receiver< VF, EF, DF, StrtF >::value (V && v) inline
Definition at line 198 of file flow_receiver.h.
References folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
                     {
     if (!started_) {std::abort();}
     if (done_){ return; }
     nf_((V&&) v);
   }
Member Data Documentation
template<class VF , class EF , class DF , class StrtF > DF folly::pushmi::flow_receiver< VF, EF, DF, StrtF >::df_ private
Definition at line 165 of file flow_receiver.h.
template<class VF , class EF , class DF , class StrtF > bool folly::pushmi::flow_receiver< VF, EF, DF, StrtF >::done_ = false private
Definition at line 161 of file flow_receiver.h.
template<class VF , class EF , class DF , class StrtF > EF folly::pushmi::flow_receiver< VF, EF, DF, StrtF >::ef_ private
Definition at line 164 of file flow_receiver.h.
template<class VF , class EF , class DF , class StrtF > VF folly::pushmi::flow_receiver< VF, EF, DF, StrtF >::nf_ private
Definition at line 163 of file flow_receiver.h.
template<class VF , class EF , class DF , class StrtF > bool folly::pushmi::flow_receiver< VF, EF, DF, StrtF >::started_ = false private
Definition at line 162 of file flow_receiver.h.
template<class VF , class EF , class DF , class StrtF > StrtF folly::pushmi::flow_receiver< VF, EF, DF, StrtF >::strtf_ private
Definition at line 166 of file flow_receiver.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/pushmi/flow_receiver.h