proxygen: testing::UnitTest Class Reference
testing::UnitTest Class Reference
#include <gtest.h>
Public Member Functions
int Run () GTEST_MUST_USE_RESULT_
const char * original_working_dir () const
const TestCase * current_test_case () const GTEST_LOCK_EXCLUDED_(mutex_)
const TestInfo * current_test_info () const GTEST_LOCK_EXCLUDED_(mutex_)
int random_seed () const
int successful_test_case_count () const
int failed_test_case_count () const
int total_test_case_count () const
int test_case_to_run_count () const
int successful_test_count () const
int failed_test_count () const
int reportable_disabled_test_count () const
int disabled_test_count () const
int reportable_test_count () const
int total_test_count () const
int test_to_run_count () const
TimeInMillis start_timestamp () const
TimeInMillis elapsed_time () const
bool Passed () const
bool Failed () const
const TestCase * GetTestCase (int i) const
const TestResult & ad_hoc_test_result () const
TestEventListeners & listeners ()
int Run () GTEST_MUST_USE_RESULT_
const char * original_working_dir () const
const TestCase * current_test_case () const GTEST_LOCK_EXCLUDED_(mutex_)
const TestInfo * current_test_info () const GTEST_LOCK_EXCLUDED_(mutex_)
int random_seed () const
int successful_test_case_count () const
int failed_test_case_count () const
int total_test_case_count () const
int test_case_to_run_count () const
int successful_test_count () const
int failed_test_count () const
int reportable_disabled_test_count () const
int disabled_test_count () const
int reportable_test_count () const
int total_test_count () const
int test_to_run_count () const
TimeInMillis start_timestamp () const
TimeInMillis elapsed_time () const
bool Passed () const
bool Failed () const
const TestCase * GetTestCase (int i) const
const TestResult & ad_hoc_test_result () const
TestEventListeners & listeners ()
int Run () GTEST_MUST_USE_RESULT_
const char * original_working_dir () const
const TestCase * current_test_case () const GTEST_LOCK_EXCLUDED_(mutex_)
const TestInfo * current_test_info () const GTEST_LOCK_EXCLUDED_(mutex_)
int random_seed () const
int successful_test_case_count () const
int failed_test_case_count () const
int total_test_case_count () const
int test_case_to_run_count () const
int successful_test_count () const
int failed_test_count () const
int reportable_disabled_test_count () const
int disabled_test_count () const
int reportable_test_count () const
int total_test_count () const
int test_to_run_count () const
TimeInMillis start_timestamp () const
TimeInMillis elapsed_time () const
bool Passed () const
bool Failed () const
const TestCase * GetTestCase (int i) const
const TestResult & ad_hoc_test_result () const
TestEventListeners & listeners ()
Static Public Member Functions
static UnitTest * GetInstance ()
static UnitTest * GetInstance ()
static UnitTest * GetInstance ()
Private Member Functions
Environment * AddEnvironment (Environment *env)
void AddTestPartResult (TestPartResult::Type result_type, const char *file_name, int line_number, const std::string &message, const std::string &os_stack_trace) GTEST_LOCK_EXCLUDED_(mutex_)
void RecordProperty (const std::string &key, const std::string &value)
TestCase * GetMutableTestCase (int i)
internal::UnitTestImpl * impl ()
const internal::UnitTestImpl * impl () const
UnitTest ()
virtual ~UnitTest ()
void PushGTestTrace (const internal::TraceInfo &trace) GTEST_LOCK_EXCLUDED_(mutex_)
void PopGTestTrace () GTEST_LOCK_EXCLUDED_(mutex_)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (UnitTest)
Environment * AddEnvironment (Environment *env)
void AddTestPartResult (TestPartResult::Type result_type, const char *file_name, int line_number, const std::string &message, const std::string &os_stack_trace) GTEST_LOCK_EXCLUDED_(mutex_)
void RecordProperty (const std::string &key, const std::string &value)
TestCase * GetMutableTestCase (int i)
internal::UnitTestImpl * impl ()
const internal::UnitTestImpl * impl () const
UnitTest ()
virtual ~UnitTest ()
void PushGTestTrace (const internal::TraceInfo &trace) GTEST_LOCK_EXCLUDED_(mutex_)
void PopGTestTrace () GTEST_LOCK_EXCLUDED_(mutex_)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (UnitTest)
Environment * AddEnvironment (Environment *env)
void AddTestPartResult (TestPartResult::Type result_type, const char *file_name, int line_number, const std::string &message, const std::string &os_stack_trace) GTEST_LOCK_EXCLUDED_(mutex_)
void RecordProperty (const std::string &key, const std::string &value)
TestCase * GetMutableTestCase (int i)
internal::UnitTestImpl * impl ()
const internal::UnitTestImpl * impl () const
UnitTest ()
virtual ~UnitTest ()
void PushGTestTrace (const internal::TraceInfo &trace) GTEST_LOCK_EXCLUDED_(mutex_)
void PopGTestTrace () GTEST_LOCK_EXCLUDED_(mutex_)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (UnitTest)
Private Attributes
internal::Mutex mutex_
internal::UnitTestImpl * impl_
Friends
class Test
class internal::AssertHelper
class internal::ScopedTrace
class internal::StreamingListenerTest
class internal::UnitTestRecordPropertyTestHelper
Environment * AddGlobalTestEnvironment (Environment *env)
internal::UnitTestImpl * internal::GetUnitTestImpl ()
void internal::ReportFailureInUnknownLocation (TestPartResult::Type result_type, const std::string &message)
Environment * AddGlobalTestEnvironment (Environment *env)
internal::UnitTestImpl * internal::GetUnitTestImpl ()
void internal::ReportFailureInUnknownLocation (TestPartResult::Type result_type, const std::string &message)
Environment * AddGlobalTestEnvironment (Environment *env)
internal::UnitTestImpl * internal::GetUnitTestImpl ()
void internal::ReportFailureInUnknownLocation (TestPartResult::Type result_type, const std::string &message)
Detailed Description
Definition at line 1151 of file gtest.h.
Constructor & Destructor Documentation
testing::UnitTest::UnitTest () private
Definition at line 4299 of file gtest.cc.
Referenced by testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
                    {
   impl_ = new internal::UnitTestImpl(this);
 }
testing::UnitTest::~UnitTest () private virtual
Definition at line 4304 of file gtest.cc.
Referenced by testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
                     {
   delete impl_;
 }
testing::UnitTest::UnitTest () private
virtual testing::UnitTest::~UnitTest () private virtual
testing::UnitTest::UnitTest () private
virtual testing::UnitTest::~UnitTest () private virtual
Member Function Documentation
const TestResult & testing::UnitTest::ad_hoc_test_result () const
Definition at line 4069 of file gtest.cc.
Referenced by testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PortableLocaltime(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   return *impl()->ad_hoc_test_result();
 }
const TestResult& testing::UnitTest::ad_hoc_test_result () const
const TestResult& testing::UnitTest::ad_hoc_test_result () const
Environment* testing::UnitTest::AddEnvironment (Environment * env) private
Environment * testing::UnitTest::AddEnvironment (Environment * env) private
Definition at line 4095 of file gtest.cc.
Referenced by testing::AddGlobalTestEnvironment(), impl(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   if (env == NULL) {
     return NULL;
   }
   impl_->environments().push_back(env);
   return env;
 }
Environment* testing::UnitTest::AddEnvironment (Environment * env) private
void testing::UnitTest::AddTestPartResult (TestPartResult::Type result_type, const char * file_name, int line_number, const std::string & message, const std::string & os_stack_trace) private
void testing::UnitTest::AddTestPartResult (TestPartResult::Type result_type, const char * file_name, int line_number, const std::string & message, const std::string & os_stack_trace) private
Definition at line 4108 of file gtest.cc.
References testing::internal::TraceInfo::file, testing::internal::FormatFileLocation(), testing::Message::GetString(), GTEST_FLAG, GTEST_NAME_, i, testing::internal::kStackTraceMarker, testing::TestPartResult::kSuccess, testing::internal::TraceInfo::line, folly::detail::lock(), message, testing::internal::TraceInfo::message, and mutex_.
Referenced by testing::internal::ReportFailureInUnknownLocation(), testing::TestPartNonfatallyFailed(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   Message msg;
   msg << message;
   internal::MutexLock lock(&mutex_);
   if (impl_->gtest_trace_stack().size() > 0) {
     msg << "\n" << GTEST_NAME_ << " trace:";
     for (int i = static_cast<int>(impl_->gtest_trace_stack().size());
          i > 0; --i) {
       const internal::TraceInfo& trace = impl_->gtest_trace_stack()[i - 1];
       msg << "\n" << internal::FormatFileLocation(trace.file, trace.line)
           << " " << trace.message;
     }
   }
   if (os_stack_trace.c_str() != NULL && !os_stack_trace.empty()) {
     msg << internal::kStackTraceMarker << os_stack_trace;
   }
   const TestPartResult result =
     TestPartResult(result_type, file_name, line_number,
                    msg.GetString().c_str());
   impl_->GetTestPartResultReporterForCurrentThread()->
       ReportTestPartResult(result);
   if (result_type != TestPartResult::kSuccess) {
     // gtest_break_on_failure takes precedence over
     // gtest_throw_on_failure.  This allows a user to set the latter
     // in the code (perhaps in order to use Google Test assertions
     // with another testing framework) and specify the former on the
     // command line for debugging.
     if (GTEST_FLAG(break_on_failure)) {
 #if GTEST_OS_WINDOWS && !GTEST_OS_WINDOWS_PHONE && !GTEST_OS_WINDOWS_RT
       // Using DebugBreak on Windows allows gtest to still break into a debugger
       // when a failure happens and both the --gtest_break_on_failure and
       // the --gtest_catch_exceptions flags are specified.
       DebugBreak();
 #else
       // Dereference NULL through a volatile pointer to prevent the compiler
       // from removing. We use this rather than abort() or __builtin_trap() for
       // portability: Symbian doesn't implement abort() well, and some debuggers
       // don't correctly trap abort().
       *static_cast<volatile int*>(NULL) = 1;
 #endif  // GTEST_OS_WINDOWS
     } else if (GTEST_FLAG(throw_on_failure)) {
 #if GTEST_HAS_EXCEPTIONS
       throw internal::GoogleTestFailureException(result);
 #else
       // We cannot call abort() as it generates a pop-up in debug mode
       // that cannot be suppressed in VC 7.1 or below.
       exit(1);
 #endif
     }
   }
 }
void testing::UnitTest::AddTestPartResult (TestPartResult::Type result_type, const char * file_name, int line_number, const std::string & message, const std::string & os_stack_trace) private
const TestCase* testing::UnitTest::current_test_case () const
const TestCase* testing::UnitTest::current_test_case () const
const TestCase * testing::UnitTest::current_test_case () const
Definition at line 4271 of file gtest.cc.
References folly::detail::lock().
Referenced by testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   internal::MutexLock lock(&mutex_);
   return impl_->current_test_case();
 }
const TestInfo* testing::UnitTest::current_test_info () const
const TestInfo* testing::UnitTest::current_test_info () const
const TestInfo * testing::UnitTest::current_test_info () const
Definition at line 4279 of file gtest.cc.
References folly::detail::lock().
Referenced by testing::CurrentTestInfoTest::SetUpTestCase(), CommonTest< T >::TearDown(), testing::CurrentTestInfoTest::TearDownTestCase(), testing::TEST_F(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   internal::MutexLock lock(&mutex_);
   return impl_->current_test_info();
 }
int testing::UnitTest::disabled_test_count () const
int testing::UnitTest::disabled_test_count () const
int testing::UnitTest::disabled_test_count () const
Definition at line 4028 of file gtest.cc.
Referenced by testing::internal::UnitTestHelper::GetSortedTests(), testing::internal::TEST(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   return impl()->disabled_test_count();
 }
internal::TimeInMillis testing::UnitTest::elapsed_time () const
Definition at line 4050 of file gtest.cc.
Referenced by testing::internal::PrettyUnitTestResultPrinter::OnTestIterationEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PortableLocaltime(), testing::internal::TestResultAccessor::test_part_results(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   return impl()->elapsed_time();
 }
TimeInMillis testing::UnitTest::elapsed_time () const
TimeInMillis testing::UnitTest::elapsed_time () const
bool testing::UnitTest::Failed () const
bool testing::UnitTest::Failed () const
Definition at line 4059 of file gtest.cc.
Referenced by testing::internal::FinalSuccessChecker::TearDown(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
 { return impl()->Failed(); }
bool testing::UnitTest::Failed () const
int testing::UnitTest::failed_test_case_count () const
Definition at line 3999 of file gtest.cc.
Referenced by testing::internal::FinalSuccessChecker::TearDown(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   return impl()->failed_test_case_count();
 }
int testing::UnitTest::failed_test_case_count () const
int testing::UnitTest::failed_test_case_count () const
int testing::UnitTest::failed_test_count () const
int testing::UnitTest::failed_test_count () const
int testing::UnitTest::failed_test_count () const
Definition at line 4020 of file gtest.cc.
Referenced by testing::internal::PrettyUnitTestResultPrinter::OnTestIterationEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PortableLocaltime(), testing::internal::PrettyUnitTestResultPrinter::PrintFailedTests(), testing::internal::FinalSuccessChecker::TearDown(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
 { return impl()->failed_test_count(); }
static UnitTest* testing::UnitTest::GetInstance () static
static UnitTest* testing::UnitTest::GetInstance () static
UnitTest * testing::UnitTest::GetInstance () static
Definition at line 3972 of file gtest.cc.
Referenced by testing::AddGlobalTestEnvironment(), testing::internal::UnitTestHelper::FindTestCase(), testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile(), testing::internal::UnitTestHelper::GetSortedTestCases(), testing::internal::UnitTestHelper::GetSortedTests(), testing::internal::GetUnitTestImpl(), impl(), testing::internal::Log(), main(), testing::internal::AssertHelper::operator=(), testing::internal::PortableLocaltime(), testing::Test::RecordProperty(), testing::internal::GoogleTestFailureReporter::ReportFailure(), testing::internal::ReportFailureInUnknownLocation(), testing::TestInfo::Run(), testing::TestCase::Run(), testing::internal::ScopedTrace::ScopedTrace(), testing::internal::UnitTestImpl::set_catch_exceptions(), testing::CurrentTestInfoTest::SetUpTestCase(), testing::internal::ShouldRunTestCase(), CommonTest< T >::TearDown(), testing::internal::FinalSuccessChecker::TearDown(), testing::CurrentTestInfoTest::TearDownTestCase(), testing::internal::TEST(), TEST(), testing::TEST_F(), testing::TestPartNonfatallyFailed(), testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile(), and testing::internal::ScopedTrace::~ScopedTrace().
{
   // When compiled with MSVC 7.1 in optimized mode, destroying the
   // UnitTest object upon exiting the program messes up the exit code,
   // causing successful tests to appear failed.  We have to use a
   // different implementation in this case to bypass the compiler bug.
   // This implementation makes the compiler happy, at the cost of
   // leaking the UnitTest object.
   // CodeGear C++Builder insists on a public destructor for the
   // default implementation.  Use this implementation to keep good OO
   // design with private destructor.
 #if (_MSC_VER == 1310 && !defined(_DEBUG)) || defined(__BORLANDC__)
   static UnitTest* const instance = new UnitTest;
   return instance;
 #else
   static UnitTest instance;
   return &instance;
 #endif  // (_MSC_VER == 1310 && !defined(_DEBUG)) || defined(__BORLANDC__)
 }
TestCase* testing::UnitTest::GetMutableTestCase (int i) private
TestCase * testing::UnitTest::GetMutableTestCase (int i) private
Definition at line 4075 of file gtest.cc.
Referenced by testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   return impl()->GetMutableTestCase(i);
 }
TestCase* testing::UnitTest::GetMutableTestCase (int i) private
const TestCase * testing::UnitTest::GetTestCase (int i) const
Definition at line 4063 of file gtest.cc.
Referenced by testing::internal::UnitTestHelper::FindTestCase(), testing::internal::UnitTestHelper::GetSortedTestCases(), testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PortableLocaltime(), testing::internal::PrettyUnitTestResultPrinter::PrintFailedTests(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   return impl()->GetTestCase(i);
 }
const TestCase* testing::UnitTest::GetTestCase (int i) const
const TestCase* testing::UnitTest::GetTestCase (int i) const
testing::UnitTest::GTEST_DISALLOW_COPY_AND_ASSIGN_ (UnitTest) private
testing::UnitTest::GTEST_DISALLOW_COPY_AND_ASSIGN_ (UnitTest) private
testing::UnitTest::GTEST_DISALLOW_COPY_AND_ASSIGN_ (UnitTest) private
internal::UnitTestImpl* testing::UnitTest::impl () inline private
Definition at line 1287 of file gtest.h.
 { return impl_; }
internal::UnitTestImpl* testing::UnitTest::impl () inline private
Definition at line 1287 of file gtest.h.
Referenced by testing::internal::GetUnitTestImpl(), testing::internal::AssertHelper::operator=(), testing::internal::UnitTestImpl::set_catch_exceptions(), and testing::internal::ShouldRunTestCase().
 { return impl_; }
internal::UnitTestImpl* testing::UnitTest::impl () inline private
Definition at line 1287 of file gtest.h.
 { return impl_; }
const internal::UnitTestImpl* testing::UnitTest::impl () const inline private
Definition at line 1288 of file gtest.h.
References AddEnvironment(), testing::AddGlobalTestEnvironment(), argv, testing::AssertionSuccess(), testing::internal::CmpHelperEQ(), testing::internal::CmpHelperEQFailure(), testing::internal::EqFailure(), testing::internal::FormatForComparisonFailureMessage(), GetInstance(), testing::internal::GetUnitTestImpl(), GTEST_API_, GTEST_DISABLE_MSC_WARNINGS_POP_, GTEST_DISABLE_MSC_WARNINGS_PUSH_, GTEST_DISALLOW_COPY_AND_ASSIGN_, GTEST_LOCK_EXCLUDED_, testing::InitGoogleTest(), mutex_, testing::internal::ReportFailureInUnknownLocation(), folly::detail::rhs, and string.
 { return impl_; }
const internal::UnitTestImpl* testing::UnitTest::impl () const inline private
Definition at line 1288 of file gtest.h.
 { return impl_; }
const internal::UnitTestImpl* testing::UnitTest::impl () const inline private
Definition at line 1288 of file gtest.h.
References AddEnvironment(), testing::AddGlobalTestEnvironment(), argv, testing::AssertionSuccess(), testing::internal::CmpHelperEQ(), testing::internal::CmpHelperEQFailure(), testing::internal::EqFailure(), testing::internal::FormatForComparisonFailureMessage(), GetInstance(), testing::internal::GetUnitTestImpl(), GTEST_API_, GTEST_DISABLE_MSC_WARNINGS_POP_, GTEST_DISABLE_MSC_WARNINGS_PUSH_, GTEST_DISALLOW_COPY_AND_ASSIGN_, GTEST_LOCK_EXCLUDED_, testing::InitGoogleTest(), mutex_, testing::internal::ReportFailureInUnknownLocation(), folly::detail::rhs, and string.
 { return impl_; }
TestEventListeners& testing::UnitTest::listeners ()
TestEventListeners & testing::UnitTest::listeners ()
Definition at line 4081 of file gtest.cc.
Referenced by main(), testing::TestInfo::Run(), testing::TestCase::Run(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   return *impl()->listeners();
 }
TestEventListeners& testing::UnitTest::listeners ()
const char* testing::UnitTest::original_working_dir () const
const char* testing::UnitTest::original_working_dir () const
const char * testing::UnitTest::original_working_dir () const
Definition at line 4265 of file gtest.cc.
Referenced by testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   return impl_->original_working_dir_.c_str();
 }
bool testing::UnitTest::Passed () const
Definition at line 4055 of file gtest.cc.
Referenced by testing::internal::PrettyUnitTestResultPrinter::OnTestIterationEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), testing::internal::FinalSuccessChecker::TearDown(), testing::internal::TestResultAccessor::test_part_results(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
 { return impl()->Passed(); }
bool testing::UnitTest::Passed () const
bool testing::UnitTest::Passed () const
void testing::UnitTest::PopGTestTrace () private
void testing::UnitTest::PopGTestTrace () private
Definition at line 4317 of file gtest.cc.
References folly::detail::lock().
Referenced by testing::internal::PortableLocaltime(), testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile(), and testing::internal::ScopedTrace::~ScopedTrace().
{
   internal::MutexLock lock(&mutex_);
   impl_->gtest_trace_stack().pop_back();
 }
void testing::UnitTest::PopGTestTrace () private
void testing::UnitTest::PushGTestTrace (const internal::TraceInfo & trace) private
void testing::UnitTest::PushGTestTrace (const internal::TraceInfo & trace) private
void testing::UnitTest::PushGTestTrace (const internal::TraceInfo & trace) private
Definition at line 4310 of file gtest.cc.
References folly::detail::lock(), and mutex_.
Referenced by testing::internal::PortableLocaltime(), testing::internal::ScopedTrace::ScopedTrace(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   internal::MutexLock lock(&mutex_);
   impl_->gtest_trace_stack().push_back(trace);
 }
int testing::UnitTest::random_seed () const
Definition at line 4286 of file gtest.cc.
References GTEST_LOCK_EXCLUDED_, and mutex_.
Referenced by testing::internal::PrettyUnitTestResultPrinter::OnTestIterationStart(), testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PortableLocaltime(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
 { return impl_->random_seed(); }
int testing::UnitTest::random_seed () const
int testing::UnitTest::random_seed () const
void testing::UnitTest::RecordProperty (const std::string & key, const std::string & value) private
void testing::UnitTest::RecordProperty (const std::string & key, const std::string & value) private
Definition at line 4175 of file gtest.cc.
Referenced by testing::Test::RecordProperty(), testing::TestPartNonfatallyFailed(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   impl_->RecordProperty(TestProperty(key, value));
 }
void testing::UnitTest::RecordProperty (const std::string & key, const std::string & value) private
int testing::UnitTest::reportable_disabled_test_count () const
Definition at line 4023 of file gtest.cc.
Referenced by testing::internal::PrettyUnitTestResultPrinter::OnTestIterationEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PortableLocaltime(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   return impl()->reportable_disabled_test_count();
 }
int testing::UnitTest::reportable_disabled_test_count () const
int testing::UnitTest::reportable_disabled_test_count () const
int testing::UnitTest::reportable_test_count () const
int testing::UnitTest::reportable_test_count () const
Definition at line 4033 of file gtest.cc.
Referenced by testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PortableLocaltime(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   return impl()->reportable_test_count();
 }
int testing::UnitTest::reportable_test_count () const
int testing::UnitTest::Run ()
int testing::UnitTest::Run ()
int testing::UnitTest::Run ()
Definition at line 4185 of file gtest.cc.
References testing::internal::posix::GetEnv(), GTEST_FLAG, testing::internal::HandleExceptionsInMethodIfSupported(), and testing::internal::UnitTestImpl::RunAllTests().
Referenced by testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
                   {
   const bool in_death_test_child_process =
       internal::GTEST_FLAG(internal_run_death_test).length() > 0;
   // Google Test implements this protocol for catching that a test
   // program exits before returning control to Google Test:
   //
   //   1. Upon start, Google Test creates a file whose absolute path
   //      is specified by the environment variable
   //      TEST_PREMATURE_EXIT_FILE.
   //   2. When Google Test has finished its work, it deletes the file.
   //
   // This allows a test runner to set TEST_PREMATURE_EXIT_FILE before
   // running a Google-Test-based test program and check the existence
   // of the file at the end of the test execution to see if it has
   // exited prematurely.
   // If we are in the child process of a death test, don't
   // create/delete the premature exit file, as doing so is unnecessary
   // and will confuse the parent process.  Otherwise, create/delete
   // the file upon entering/leaving this function.  If the program
   // somehow exits before this function has a chance to return, the
   // premature-exit file will be left undeleted, causing a test runner
   // that understands the premature-exit-file protocol to report the
   // test as having failed.
   const internal::ScopedPrematureExitFile premature_exit_file(
       in_death_test_child_process ?
       NULL : internal::posix::GetEnv("TEST_PREMATURE_EXIT_FILE"));
   // Captures the value of GTEST_FLAG(catch_exceptions).  This value will be
   // used for the duration of the program.
   impl()->set_catch_exceptions(GTEST_FLAG(catch_exceptions));
 #if GTEST_HAS_SEH
   // Either the user wants Google Test to catch exceptions thrown by the
   // tests or this is executing in the context of death test child
   // process. In either case the user does not want to see pop-up dialogs
   // about crashes - they are expected.
   if (impl()->catch_exceptions() || in_death_test_child_process) {
 # if !GTEST_OS_WINDOWS_MOBILE && !GTEST_OS_WINDOWS_PHONE && !GTEST_OS_WINDOWS_RT
     // SetErrorMode doesn't exist on CE.
     SetErrorMode(SEM_FAILCRITICALERRORS | SEM_NOALIGNMENTFAULTEXCEPT |
                  SEM_NOGPFAULTERRORBOX | SEM_NOOPENFILEERRORBOX);
 # endif  // !GTEST_OS_WINDOWS_MOBILE
 # if (defined(_MSC_VER) || GTEST_OS_WINDOWS_MINGW) && !GTEST_OS_WINDOWS_MOBILE
     // Death test children can be terminated with _abort().  On Windows,
     // _abort() can show a dialog with a warning message.  This forces the
     // abort message to go to stderr instead.
     _set_error_mode(_OUT_TO_STDERR);
 # endif
 # if _MSC_VER >= 1400 && !GTEST_OS_WINDOWS_MOBILE
     // In the debug version, Visual Studio pops up a separate dialog
     // offering a choice to debug the aborted program. We need to suppress
     // this dialog or it will pop up for every EXPECT/ASSERT_DEATH statement
     // executed. Google Test will notify the user of any unexpected
     // failure via stderr.
     //
     // VC++ doesn't define _set_abort_behavior() prior to the version 8.0.
     // Users of prior VC versions shall suffer the agony and pain of
     // clicking through the countless debug dialogs.
     // TODO(vladl@google.com): find a way to suppress the abort dialog() in the
     // debug mode when compiled with VC 7.1 or lower.
     if (!GTEST_FLAG(break_on_failure))
       _set_abort_behavior(
           0x0,                                    // Clear the following flags:
           _WRITE_ABORT_MSG | _CALL_REPORTFAULT);  // pop-up window, core dump.
 # endif
   }
 #endif  // GTEST_HAS_SEH
   return internal::HandleExceptionsInMethodIfSupported(
       impl(),
       &internal::UnitTestImpl::RunAllTests,
       "auxiliary test code (environments or event listeners)") ? 0 : 1;
 }
internal::TimeInMillis testing::UnitTest::start_timestamp () const
Definition at line 4045 of file gtest.cc.
Referenced by testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PortableLocaltime(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
     return impl()->start_timestamp();
 }
TimeInMillis testing::UnitTest::start_timestamp () const
TimeInMillis testing::UnitTest::start_timestamp () const
int testing::UnitTest::successful_test_case_count () const
int testing::UnitTest::successful_test_case_count () const
int testing::UnitTest::successful_test_case_count () const
Definition at line 3994 of file gtest.cc.
Referenced by testing::internal::FinalSuccessChecker::TearDown(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   return impl()->successful_test_case_count();
 }
int testing::UnitTest::successful_test_count () const
int testing::UnitTest::successful_test_count () const
int testing::UnitTest::successful_test_count () const
Definition at line 4015 of file gtest.cc.
Referenced by testing::internal::PrettyUnitTestResultPrinter::OnTestIterationEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), testing::internal::FinalSuccessChecker::TearDown(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   return impl()->successful_test_count();
 }
int testing::UnitTest::test_case_to_run_count () const
int testing::UnitTest::test_case_to_run_count () const
int testing::UnitTest::test_case_to_run_count () const
Definition at line 4010 of file gtest.cc.
Referenced by testing::internal::UnitTestHelper::GetSortedTests(), testing::internal::PrettyUnitTestResultPrinter::OnTestIterationEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestIterationStart(), testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), testing::internal::TEST(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   return impl()->test_case_to_run_count();
 }
int testing::UnitTest::test_to_run_count () const
Definition at line 4041 of file gtest.cc.
Referenced by testing::internal::UnitTestHelper::GetSortedTests(), testing::internal::PrettyUnitTestResultPrinter::OnTestIterationEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestIterationStart(), testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), testing::internal::TEST(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
 { return impl()->test_to_run_count(); }
int testing::UnitTest::test_to_run_count () const
int testing::UnitTest::test_to_run_count () const
int testing::UnitTest::total_test_case_count () const
Definition at line 4004 of file gtest.cc.
Referenced by testing::internal::UnitTestHelper::FindTestCase(), testing::internal::UnitTestHelper::GetSortedTestCases(), testing::internal::UnitTestHelper::GetSortedTests(), testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PortableLocaltime(), testing::internal::PrettyUnitTestResultPrinter::PrintFailedTests(), testing::internal::FinalSuccessChecker::TearDown(), testing::internal::TEST(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   return impl()->total_test_case_count();
 }
int testing::UnitTest::total_test_case_count () const
int testing::UnitTest::total_test_case_count () const
int testing::UnitTest::total_test_count () const
int testing::UnitTest::total_test_count () const
Definition at line 4038 of file gtest.cc.
Referenced by testing::internal::UnitTestHelper::GetSortedTests(), testing::internal::TEST(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
 { return impl()->total_test_count(); }
int testing::UnitTest::total_test_count () const
Friends And Related Function Documentation
Environment* AddGlobalTestEnvironment (Environment * env) friend
Definition at line 1350 of file gtest.h.
{
   return UnitTest::GetInstance()->AddEnvironment(env);
 }
Environment* AddGlobalTestEnvironment (Environment * env) friend
Definition at line 1350 of file gtest.h.
{
   return UnitTest::GetInstance()->AddEnvironment(env);
 }
Environment* AddGlobalTestEnvironment (Environment * env) friend
Definition at line 1350 of file gtest.h.
{
   return UnitTest::GetInstance()->AddEnvironment(env);
 }
internal::AssertHelper friend
Definition at line 1293 of file gtest.h.
internal::UnitTestImpl* internal::GetUnitTestImpl () friend
internal::UnitTestImpl* internal::GetUnitTestImpl () friend
internal::UnitTestImpl* internal::GetUnitTestImpl () friend
void internal::ReportFailureInUnknownLocation (TestPartResult::Type result_type, const std::string & message) friend
void internal::ReportFailureInUnknownLocation (TestPartResult::Type result_type, const std::string & message) friend
void internal::ReportFailureInUnknownLocation (TestPartResult::Type result_type, const std::string & message) friend
internal::ScopedTrace friend
Definition at line 1294 of file gtest.h.
internal::StreamingListenerTest friend
Definition at line 1295 of file gtest.h.
internal::UnitTestRecordPropertyTestHelper friend
Definition at line 1296 of file gtest.h.
Test friend
Definition at line 1292 of file gtest.h.
Member Data Documentation
internal::UnitTestImpl * testing::UnitTest::impl_ private
Definition at line 1326 of file gtest.h.
internal::Mutex testing::UnitTest::mutex_ mutable private
Definition at line 1320 of file gtest.h.
Referenced by testing::internal::PortableLocaltime().
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/gtest.h
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest.cc