proxygen: folly::DelayedDestructionBase::IntrusivePtr< AliasType > Class Template Reference
folly::DelayedDestructionBase::IntrusivePtr< AliasType > Class Template Reference
#include <DelayedDestructionBase.h>
Public Member Functions
IntrusivePtr ()=default
IntrusivePtr (const IntrusivePtr &)=default
IntrusivePtr (IntrusivePtr &&) noexcept=default
template<typename CopyAliasType , typename = typename std::enable_if< std::is_convertible<CopyAliasType*, AliasType*>::value>::type>
IntrusivePtr (const IntrusivePtr< CopyAliasType > &copy)
template<typename CopyAliasType , typename = typename std::enable_if< std::is_convertible<CopyAliasType*, AliasType*>::value>::type>
IntrusivePtr (IntrusivePtr< CopyAliasType > &&copy)
IntrusivePtr (AliasType *dd)
template<typename CopyAliasType , typename Deleter , typename = typename std::enable_if< std::is_convertible<CopyAliasType*, AliasType*>::value>::type>
IntrusivePtr (const std::unique_ptr< CopyAliasType, Deleter > &copy)
IntrusivePtr & operator= (const IntrusivePtr &)=default
IntrusivePtr & operator= (IntrusivePtr &&) noexcept=default
template<typename CopyAliasType , typename = typename std::enable_if< std::is_convertible<CopyAliasType*, AliasType*>::value>::type>
IntrusivePtr & operator= (IntrusivePtr< CopyAliasType > copy) noexcept
IntrusivePtr & operator= (AliasType *dd)
void reset (AliasType *dd=nullptr)
AliasType * get () const
AliasType & operator* () const
AliasType * operator-> () const
operator bool () const
Static Public Member Functions
template<typename... Args>
static IntrusivePtr< AliasType > make (Args &&...args)
Friends
template<typename CopyAliasType >
class IntrusivePtr
Additional Inherited Members
Private Member Functions inherited from folly::DelayedDestructionBase::DestructorGuard
DestructorGuard (DelayedDestructionBase *dd)
DestructorGuard (const DestructorGuard &dg)
DestructorGuard (DestructorGuard &&dg) noexcept
DestructorGuard & operator= (DestructorGuard dg) noexcept
DestructorGuard & operator= (DelayedDestructionBase *dd)
~DestructorGuard ()
DelayedDestructionBase * get () const
operator bool () const
Detailed Description
template<typename AliasType>
class folly::DelayedDestructionBase::IntrusivePtr< AliasType >
This smart pointer is a convenient way to manage a concrete DelayedDestructorBase child. It can replace the equivalent raw pointer and provide automatic memory management.
Definition at line 114 of file DelayedDestructionBase.h.
Constructor & Destructor Documentation
template<typename AliasType> folly::DelayedDestructionBase::IntrusivePtr< AliasType >::IntrusivePtr () default
template<typename AliasType> folly::DelayedDestructionBase::IntrusivePtr< AliasType >::IntrusivePtr (const IntrusivePtr< AliasType > &) default
template<typename AliasType> folly::DelayedDestructionBase::IntrusivePtr< AliasType >::IntrusivePtr (IntrusivePtr< AliasType > &&) default noexcept
template<typename AliasType> template<typename CopyAliasType , typename = typename std::enable_if< std::is_convertible<CopyAliasType*, AliasType*>::value>::type> folly::DelayedDestructionBase::IntrusivePtr< AliasType >::IntrusivePtr (const IntrusivePtr< CopyAliasType > & copy) inline
Definition at line 132 of file DelayedDestructionBase.h.
References type, and value.
         : DestructorGuard(copy) {}
template<typename AliasType> template<typename CopyAliasType , typename = typename std::enable_if< std::is_convertible<CopyAliasType*, AliasType*>::value>::type> folly::DelayedDestructionBase::IntrusivePtr< AliasType >::IntrusivePtr (IntrusivePtr< CopyAliasType > && copy) inline
Definition at line 139 of file DelayedDestructionBase.h.
         : DestructorGuard(std::move(copy)) {}
template<typename AliasType> folly::DelayedDestructionBase::IntrusivePtr< AliasType >::IntrusivePtr (AliasType * dd) inline explicit
Definition at line 142 of file DelayedDestructionBase.h.
References type, and value.
 : DestructorGuard(dd) {}
template<typename AliasType> template<typename CopyAliasType , typename Deleter , typename = typename std::enable_if< std::is_convertible<CopyAliasType*, AliasType*>::value>::type> folly::DelayedDestructionBase::IntrusivePtr< AliasType >::IntrusivePtr (const std::unique_ptr< CopyAliasType, Deleter > & copy) inline explicit
Definition at line 152 of file DelayedDestructionBase.h.
References folly::pushmi::__adl::noexcept(), folly::DelayedDestructionBase::DestructorGuard::operator=(), type, and value.
         : DestructorGuard(copy.get()) {}
Member Function Documentation
template<typename AliasType> AliasType* folly::DelayedDestructionBase::IntrusivePtr< AliasType >::get () const inline
Definition at line 176 of file DelayedDestructionBase.h.
References folly::DelayedDestructionBase::DestructorGuard::get().
Referenced by folly::operator!=(), and folly::operator==().
{
       return static_cast<AliasType*>(DestructorGuard::get());
     }
template<typename AliasType> template<typename... Args> static IntrusivePtr<AliasType> folly::DelayedDestructionBase::IntrusivePtr< AliasType >::make (Args &&... args) inline static
Definition at line 120 of file DelayedDestructionBase.h.
References folly::pushmi::__adl::noexcept(), type, and value.
{
       return {new AliasType(std::forward<Args>(args)...)};
     }
template<typename AliasType> folly::DelayedDestructionBase::IntrusivePtr< AliasType >::operator bool () const inline explicit
Definition at line 188 of file DelayedDestructionBase.h.
{
       return DestructorGuard::operator bool();
     }
template<typename AliasType> AliasType& folly::DelayedDestructionBase::IntrusivePtr< AliasType >::operator* () const inline
Definition at line 180 of file DelayedDestructionBase.h.
{
       return *get();
     }
template<typename AliasType> AliasType* folly::DelayedDestructionBase::IntrusivePtr< AliasType >::operator-> () const inline
Definition at line 184 of file DelayedDestructionBase.h.
{
       return get();
     }
template<typename AliasType> IntrusivePtr& folly::DelayedDestructionBase::IntrusivePtr< AliasType >::operator= (const IntrusivePtr< AliasType > &) default
template<typename AliasType> IntrusivePtr& folly::DelayedDestructionBase::IntrusivePtr< AliasType >::operator= (IntrusivePtr< AliasType > &&) default noexcept
template<typename AliasType> template<typename CopyAliasType , typename = typename std::enable_if< std::is_convertible<CopyAliasType*, AliasType*>::value>::type> IntrusivePtr& folly::DelayedDestructionBase::IntrusivePtr< AliasType >::operator= (IntrusivePtr< CopyAliasType > copy) inline noexcept
Definition at line 162 of file DelayedDestructionBase.h.
References folly::copy(), and folly::DelayedDestructionBase::DestructorGuard::operator=().
{
       DestructorGuard::operator=(copy);
       return *this;
     }
template<typename AliasType> IntrusivePtr& folly::DelayedDestructionBase::IntrusivePtr< AliasType >::operator= (AliasType * dd) inline
Definition at line 167 of file DelayedDestructionBase.h.
References folly::DelayedDestructionBase::DestructorGuard::operator=().
{
       DestructorGuard::operator=(dd);
       return *this;
     }
template<typename AliasType> void folly::DelayedDestructionBase::IntrusivePtr< AliasType >::reset (AliasType * dd = nullptr) inline
Definition at line 172 of file DelayedDestructionBase.h.
{
       *this = dd;
     }
Friends And Related Function Documentation
template<typename AliasType> template<typename CopyAliasType > friend class IntrusivePtr friend
Definition at line 116 of file DelayedDestructionBase.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/io/async/DelayedDestructionBase.h