proxygen: folly::fibers::GuardPageAllocator Class Reference
folly::fibers::GuardPageAllocator Class Reference
#include <GuardPageAllocator.h>
Public Member Functions
GuardPageAllocator (bool useGuardPages)
~GuardPageAllocator ()
unsigned char * allocate (size_t size)
void deallocate (unsigned char *limit, size_t size)
Private Attributes
std::unique_ptr< StackCacheEntry > stackCache_
std::allocator< unsigned char > fallbackAllocator_
bool useGuardPages_ {true}
Detailed Description
Stack allocator that protects an extra memory page after the end of the stack. Will only add extra memory pages up to a certain number of allocations to avoid creating too many memory maps for the process.
Definition at line 31 of file GuardPageAllocator.h.
Constructor & Destructor Documentation
folly::fibers::GuardPageAllocator::GuardPageAllocator (bool useGuardPages) explicit
Parameters
useGuardPages if true, protect limited amount of stacks with guard pages, otherwise acts as std::allocator.
Definition at line 293 of file GuardPageAllocator.cpp.
References ~GuardPageAllocator().
     : useGuardPages_(useGuardPages) {
 #ifndef _WIN32
   installSignalHandler();
 #endif
 }
folly::fibers::GuardPageAllocator::~GuardPageAllocator () default
Referenced by GuardPageAllocator().
Member Function Documentation
unsigned char * folly::fibers::GuardPageAllocator::allocate (size_t size)
Returns
pointer to the bottom of the allocated stack of `size' bytes.
Definition at line 302 of file GuardPageAllocator.cpp.
References fallbackAllocator_, folly::fibers::CacheManager::getStackCache(), folly::fibers::CacheManager::instance(), stackCache_, and useGuardPages_.
{
   if (useGuardPages_ && !stackCache_) {
     stackCache_ = CacheManager::instance().getStackCache(size);
   }
   if (stackCache_) {
     auto p = stackCache_->cache().borrow(size);
     if (p != nullptr) {
       return p;
     }
   }
   return fallbackAllocator_.allocate(size);
 }
void folly::fibers::GuardPageAllocator::deallocate (unsigned char * limit, size_t size)
Deallocates the previous result of an `allocate(size)' call.
Definition at line 316 of file GuardPageAllocator.cpp.
References fallbackAllocator_, and stackCache_.
Referenced by folly::fibers::Fiber::~Fiber().
{
   if (!(stackCache_ && stackCache_->cache().giveBack(limit, size))) {
     fallbackAllocator_.deallocate(limit, size);
   }
 }
Member Data Documentation
std::allocator<unsigned char> folly::fibers::GuardPageAllocator::fallbackAllocator_ private
Definition at line 52 of file GuardPageAllocator.h.
Referenced by allocate(), and deallocate().
std::unique_ptr<StackCacheEntry> folly::fibers::GuardPageAllocator::stackCache_ private
Definition at line 51 of file GuardPageAllocator.h.
Referenced by allocate(), and deallocate().
bool folly::fibers::GuardPageAllocator::useGuardPages_ {true} private
Definition at line 53 of file GuardPageAllocator.h.
Referenced by allocate().
The documentation for this class was generated from the following files:
proxygen/folly/folly/fibers/GuardPageAllocator.h
proxygen/folly/folly/fibers/GuardPageAllocator.cpp