proxygen: folly::F14VectorSet< Key, Hasher, KeyEqual, Alloc > Class Template Reference
folly::F14VectorSet< Key, Hasher, KeyEqual, Alloc > Class Template Reference
#include <F14Set-fwd.h>
Public Member Functions
F14VectorSet ()=default
F14VectorSet & operator= (std::initializer_list< value_type > ilist)
Public Member Functions inherited from folly::f14::detail::F14BasicSet< Key, Hasher, KeyEqual, Alloc >
F14BasicSet ()=default
std::size_t getAllocatedMemorySize () const
void visitAllocationClasses (V &&visitor) const
void visitContiguousRanges (V &&visitor) const
Private Types
using Super = f14::detail::F14BasicSet< Key, Hasher, KeyEqual, Alloc >
Detailed Description
template<typename Key, typename Hasher, typename KeyEqual, typename Alloc>
class folly::F14VectorSet< Key, Hasher, KeyEqual, Alloc >
Definition at line 41 of file F14Set-fwd.h.
Member Typedef Documentation
template<typename Key, typename Hasher, typename KeyEqual, typename Alloc> using folly::F14VectorSet< Key, Hasher, KeyEqual, Alloc >::Super = f14::detail::F14BasicSet<Key, Hasher, KeyEqual, Alloc> private
Definition at line 132 of file F14Set.h.
Constructor & Destructor Documentation
template<typename Key, typename Hasher, typename KeyEqual, typename Alloc> folly::F14VectorSet< Key, Hasher, KeyEqual, Alloc >::F14VectorSet () default
Member Function Documentation
template<typename Key, typename Hasher, typename KeyEqual, typename Alloc> F14VectorSet& folly::F14VectorSet< Key, Hasher, KeyEqual, Alloc >::operator= (std::initializer_list< value_type > ilist) inline
Definition at line 141 of file F14Set.h.
References a, testing::Args(), folly::assume(), b, folly::test::begin(), folly::padded::cbegin(), folly::padded::cend(), upload::const, count, destroy(), folly::empty(), folly::test::end(), folly::eq, folly::f14::detail::F14BasicSet< K, H, E, A >::F14BasicSet(), folly::gen::first, FOLLY_ALWAYS_INLINE, FOLLY_SAFE_DCHECK, folly::f14::detail::F14BasicSet< K, H, E, A >::getAllocatedMemorySize(), folly::init(), gen_gtest_pred_impl::Iter(), k, testing::Key(), folly::gen::move, folly::pushmi::__adl::noexcept(), folly::f14::operator!=(), folly::f14::operator==(), ptr, folly::reserve, folly::detail::rhs, folly::size(), folly::f14::swap(), folly::T, uint32_t, folly::value(), testing::Value(), values(), folly::f14::detail::F14BasicSet< K, H, E, A >::visitAllocationClasses(), and folly::f14::detail::F14BasicSet< K, H, E, A >::visitContiguousRanges().
{
     Super::operator=(ilist);
     return *this;
   }
The documentation for this class was generated from the following files:
proxygen/folly/folly/container/F14Set-fwd.h
proxygen/folly/folly/container/F14Set.h