proxygen: testing::internal::UntypedOnCallSpecBase Class Reference
testing::internal::UntypedOnCallSpecBase Class Reference
#include <gmock-spec-builders.h>
Public Member Functions
UntypedOnCallSpecBase (const char *a_file, int a_line)
const char * file () const
int line () const
UntypedOnCallSpecBase (const char *a_file, int a_line)
const char * file () const
int line () const
UntypedOnCallSpecBase (const char *a_file, int a_line)
const char * file () const
int line () const
Protected Types
enum Clause {
kNone, kWith, kWillByDefault, kNone,
kWith, kWillByDefault, kNone, kWith,
kWillByDefault
}
enum Clause {
kNone, kWith, kWillByDefault, kNone,
kWith, kWillByDefault, kNone, kWith,
kWillByDefault
}
enum Clause {
kNone, kWith, kWillByDefault, kNone,
kWith, kWillByDefault, kNone, kWith,
kWillByDefault
}
Protected Member Functions
void AssertSpecProperty (bool property, const string &failure_message) const
void ExpectSpecProperty (bool property, const string &failure_message) const
void AssertSpecProperty (bool property, const string &failure_message) const
void ExpectSpecProperty (bool property, const string &failure_message) const
void AssertSpecProperty (bool property, const string &failure_message) const
void ExpectSpecProperty (bool property, const string &failure_message) const
Protected Attributes
const char * file_
int line_
Clause last_clause_
Detailed Description
Definition at line 245 of file gmock-spec-builders.h.
Member Enumeration Documentation
enum testing::internal::UntypedOnCallSpecBase::Clause protected
Enumerator
kNone
kWith
kWillByDefault
kNone
kWith
kWillByDefault
kNone
kWith
kWillByDefault
Definition at line 257 of file gmock-spec-builders.h.
               {
     // Do not change the order of the enum members!  The run-time
     // syntax checking relies on it.
     kNone,
     kWith,
     kWillByDefault
   };
enum testing::internal::UntypedOnCallSpecBase::Clause protected
Enumerator
kNone
kWith
kWillByDefault
kNone
kWith
kWillByDefault
kNone
kWith
kWillByDefault
Definition at line 257 of file gmock-spec-builders.h.
               {
     // Do not change the order of the enum members!  The run-time
     // syntax checking relies on it.
     kNone,
     kWith,
     kWillByDefault
   };
enum testing::internal::UntypedOnCallSpecBase::Clause protected
Enumerator
kNone
kWith
kWillByDefault
kNone
kWith
kWillByDefault
kNone
kWith
kWillByDefault
Definition at line 257 of file gmock-spec-builders.h.
               {
     // Do not change the order of the enum members!  The run-time
     // syntax checking relies on it.
     kNone,
     kWith,
     kWillByDefault
   };
Constructor & Destructor Documentation
testing::internal::UntypedOnCallSpecBase::UntypedOnCallSpecBase (const char * a_file, int a_line) inline
Definition at line 248 of file gmock-spec-builders.h.
       : file_(a_file), line_(a_line), last_clause_(kNone) {}
testing::internal::UntypedOnCallSpecBase::UntypedOnCallSpecBase (const char * a_file, int a_line) inline
Definition at line 248 of file gmock-spec-builders.h.
       : file_(a_file), line_(a_line), last_clause_(kNone) {}
testing::internal::UntypedOnCallSpecBase::UntypedOnCallSpecBase (const char * a_file, int a_line) inline
Definition at line 248 of file gmock-spec-builders.h.
       : file_(a_file), line_(a_line), last_clause_(kNone) {}
Member Function Documentation
void testing::internal::UntypedOnCallSpecBase::AssertSpecProperty (bool property, const string & failure_message) const inline protected
Definition at line 266 of file gmock-spec-builders.h.
References testing::internal::Assert().
{
     Assert(property, file_, line_, failure_message);
   }
void testing::internal::UntypedOnCallSpecBase::AssertSpecProperty (bool property, const string & failure_message) const inline protected
Definition at line 266 of file gmock-spec-builders.h.
References testing::internal::Assert().
{
     Assert(property, file_, line_, failure_message);
   }
void testing::internal::UntypedOnCallSpecBase::AssertSpecProperty (bool property, const string & failure_message) const inline protected
Definition at line 266 of file gmock-spec-builders.h.
References testing::internal::Assert().
{
     Assert(property, file_, line_, failure_message);
   }
void testing::internal::UntypedOnCallSpecBase::ExpectSpecProperty (bool property, const string & failure_message) const inline protected
Definition at line 271 of file gmock-spec-builders.h.
References testing::internal::Expect().
{
     Expect(property, file_, line_, failure_message);
   }
void testing::internal::UntypedOnCallSpecBase::ExpectSpecProperty (bool property, const string & failure_message) const inline protected
Definition at line 271 of file gmock-spec-builders.h.
References testing::internal::Expect().
{
     Expect(property, file_, line_, failure_message);
   }
void testing::internal::UntypedOnCallSpecBase::ExpectSpecProperty (bool property, const string & failure_message) const inline protected
Definition at line 271 of file gmock-spec-builders.h.
References testing::internal::Expect().
{
     Expect(property, file_, line_, failure_message);
   }
const char* testing::internal::UntypedOnCallSpecBase::file () const inline
Definition at line 252 of file gmock-spec-builders.h.
Referenced by testing::internal::FunctionMockerBase< R(A1, A2)>::DescribeDefaultActionTo().
 { return file_; }
const char* testing::internal::UntypedOnCallSpecBase::file () const inline
Definition at line 252 of file gmock-spec-builders.h.
 { return file_; }
const char* testing::internal::UntypedOnCallSpecBase::file () const inline
Definition at line 252 of file gmock-spec-builders.h.
 { return file_; }
int testing::internal::UntypedOnCallSpecBase::line () const inline
Definition at line 253 of file gmock-spec-builders.h.
 { return line_; }
int testing::internal::UntypedOnCallSpecBase::line () const inline
Definition at line 253 of file gmock-spec-builders.h.
 { return line_; }
int testing::internal::UntypedOnCallSpecBase::line () const inline
Definition at line 253 of file gmock-spec-builders.h.
Referenced by testing::internal::FunctionMockerBase< R(A1, A2)>::DescribeDefaultActionTo().
 { return line_; }
Member Data Documentation
const char * testing::internal::UntypedOnCallSpecBase::file_ protected
Definition at line 275 of file gmock-spec-builders.h.
Clause testing::internal::UntypedOnCallSpecBase::last_clause_ protected
Definition at line 280 of file gmock-spec-builders.h.
int testing::internal::UntypedOnCallSpecBase::line_ protected
Definition at line 276 of file gmock-spec-builders.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-spec-builders.h