proxygen: folly::TestSSLAsyncCacheServer Class Reference
folly::TestSSLAsyncCacheServer Class Reference
#include <AsyncSSLSocketTest.h>
Public Member Functions
TestSSLAsyncCacheServer (SSLServerAcceptCallbackBase *acb, int lookupDelay=100)
uint32_t getAsyncCallbacks () const
uint32_t getAsyncLookups () const
Public Member Functions inherited from folly::TestSSLServer
TestSSLServer (SSLServerAcceptCallbackBase *acb, bool enableTFO=false)
TestSSLServer (SSLServerAcceptCallbackBase *acb, std::shared_ptr< SSLContext > ctx, bool enableTFO=false)
virtual ~TestSSLServer ()
EventBase & getEventBase ()
void loadTestCerts ()
const SocketAddress & getAddress () const
Static Private Member Functions
static SSL_SESSION * getSessionCallback (SSL *ssl, unsigned char *, int, int *copyflag)
Static Private Attributes
static uint32_t asyncCallbacks_ = 0
static uint32_t asyncLookups_ = 0
static uint32_t lookupDelay_ = 0
Additional Inherited Members
Protected Attributes inherited from folly::TestSSLServer
EventBase evb_
std::shared_ptr< SSLContext > ctx_
SSLServerAcceptCallbackBase * acb_
std::shared_ptr< AsyncServerSocket > socket_
SocketAddress address_
std::thread thread_
Detailed Description
Definition at line 714 of file AsyncSSLSocketTest.h.
Constructor & Destructor Documentation
folly::TestSSLAsyncCacheServer::TestSSLAsyncCacheServer (SSLServerAcceptCallbackBase * acb, int lookupDelay = 100) inline explicit
Definition at line 716 of file AsyncSSLSocketTest.h.
References ctx_, and getSessionCallback().
       : TestSSLServer(acb) {
     SSL_CTX* sslCtx = ctx_->getSSLCtx();
 #ifdef SSL_ERROR_WANT_SESS_CACHE_LOOKUP
     SSL_CTX_sess_set_get_cb(
         sslCtx, TestSSLAsyncCacheServer::getSessionCallback);
 #endif
     SSL_CTX_set_session_cache_mode(
         sslCtx, SSL_SESS_CACHE_NO_INTERNAL | SSL_SESS_CACHE_SERVER);
     asyncCallbacks_ = 0;
     asyncLookups_ = 0;
     lookupDelay_ = lookupDelay;
   }
Member Function Documentation
uint32_t folly::TestSSLAsyncCacheServer::getAsyncCallbacks () const inline
Definition at line 732 of file AsyncSSLSocketTest.h.
Referenced by folly::TEST().
{
     return asyncCallbacks_;
   }
uint32_t folly::TestSSLAsyncCacheServer::getAsyncLookups () const inline
Definition at line 735 of file AsyncSSLSocketTest.h.
Referenced by folly::TEST().
{
     return asyncLookups_;
   }
static SSL_SESSION* folly::TestSSLAsyncCacheServer::getSessionCallback (SSL * ssl, unsigned char * , int , int * copyflag) inline static private
Definition at line 744 of file AsyncSSLSocketTest.h.
References folly::netops::bind(), folly::getctx(), folly::AsyncSocket::getEventBase(), folly::getfds(), folly::AsyncSSLSocket::getFromSSL(), folly::AsyncSSLSocket::restartSSLAccept(), folly::sslsocketpair(), and folly::TimeoutManager::tryRunAfterDelay().
Referenced by TestSSLAsyncCacheServer().
                      {
     *copyflag = 0;
     asyncCallbacks_++;
     (void)ssl;
 #ifdef SSL_ERROR_WANT_SESS_CACHE_LOOKUP
     if (!SSL_want_sess_cache_lookup(ssl)) {
       // libssl.so mismatch
       std::cerr << "no async support" << std::endl;
       return nullptr;
     }
     AsyncSSLSocket* sslSocket = AsyncSSLSocket::getFromSSL(ssl);
     assert(sslSocket != nullptr);
     // Going to simulate an async cache by just running delaying the miss 100ms
     if (asyncCallbacks_ % 2 == 0) {
       // This socket is already blocked on lookup, return miss
       std::cerr << "returning miss" << std::endl;
     } else {
       // fresh meat - block it
       std::cerr << "async lookup" << std::endl;
       sslSocket->getEventBase()->tryRunAfterDelay(
           std::bind(&AsyncSSLSocket::restartSSLAccept, sslSocket),
           lookupDelay_);
       *copyflag = SSL_SESSION_CB_WOULD_BLOCK;
       asyncLookups_++;
     }
 #endif
     return nullptr;
   }
Member Data Documentation
uint32_t folly::TestSSLAsyncCacheServer::asyncCallbacks_ = 0 static private
Definition at line 740 of file AsyncSSLSocketTest.h.
uint32_t folly::TestSSLAsyncCacheServer::asyncLookups_ = 0 static private
Definition at line 741 of file AsyncSSLSocketTest.h.
uint32_t folly::TestSSLAsyncCacheServer::lookupDelay_ = 0 static private
Definition at line 742 of file AsyncSSLSocketTest.h.
The documentation for this class was generated from the following files:
proxygen/folly/folly/io/async/test/AsyncSSLSocketTest.h
proxygen/folly/folly/io/async/test/AsyncSSLSocketTest.cpp