proxygen: folly::detail::ScopeGuardImpl< FunctionType, InvokeNoexcept > Class Template Reference
folly::detail::ScopeGuardImpl< FunctionType, InvokeNoexcept > Class Template Reference
#include <ScopeGuard.h>
Public Member Functions
ScopeGuardImpl (FunctionType &fn) noexcept(std::is_nothrow_copy_constructible< FunctionType >::value)
ScopeGuardImpl (const FunctionType &fn) noexcept(std::is_nothrow_copy_constructible< FunctionType >::value)
ScopeGuardImpl (FunctionType &&fn) noexcept(std::is_nothrow_move_constructible< FunctionType >::value)
ScopeGuardImpl (ScopeGuardImpl &&other) noexcept(std::is_nothrow_move_constructible< FunctionType >::value)
~ScopeGuardImpl () noexcept(InvokeNoexcept)
Public Member Functions inherited from folly::detail::ScopeGuardImplBase
void dismiss () noexcept
Private Member Functions
template<typename Fn >
ScopeGuardImpl (Fn &&fn, ScopeGuardImplBase &&failsafe)
void * operator new (std::size_t)=delete
void execute () noexcept(InvokeNoexcept)
Static Private Member Functions
static ScopeGuardImplBase makeFailsafe (std::true_type, const void *) noexcept
template<typename Fn >
static auto makeFailsafe (std::false_type, Fn *fn) noexcept-> ScopeGuardImpl< decltype(std::ref(*fn)), InvokeNoexcept >
Private Attributes
FunctionType function_
Additional Inherited Members
Protected Member Functions inherited from folly::detail::ScopeGuardImplBase
ScopeGuardImplBase () noexcept
Static Protected Member Functions inherited from folly::detail::ScopeGuardImplBase
static void warnAboutToCrash () noexcept
static ScopeGuardImplBase makeEmptyScopeGuard () noexcept
template<typename T >
static const T & asConst (const T &t) noexcept
Protected Attributes inherited from folly::detail::ScopeGuardImplBase
bool dismissed_
Detailed Description
template<typename FunctionType, bool InvokeNoexcept>
class folly::detail::ScopeGuardImpl< FunctionType, InvokeNoexcept >
Definition at line 58 of file ScopeGuard.h.
Constructor & Destructor Documentation
template<typename FunctionType, bool InvokeNoexcept> folly::detail::ScopeGuardImpl< FunctionType, InvokeNoexcept >::ScopeGuardImpl (FunctionType & fn) inline explicit noexcept
Definition at line 60 of file ScopeGuard.h.
       : ScopeGuardImpl(
             asConst(fn),
             makeFailsafe(
                 std::is_nothrow_copy_constructible<FunctionType>{},
                 &fn)) {}
template<typename FunctionType, bool InvokeNoexcept> folly::detail::ScopeGuardImpl< FunctionType, InvokeNoexcept >::ScopeGuardImpl (const FunctionType & fn) inline explicit noexcept
Definition at line 68 of file ScopeGuard.h.
       : ScopeGuardImpl(
             fn,
             makeFailsafe(
                 std::is_nothrow_copy_constructible<FunctionType>{},
                 &fn)) {}
template<typename FunctionType, bool InvokeNoexcept> folly::detail::ScopeGuardImpl< FunctionType, InvokeNoexcept >::ScopeGuardImpl (FunctionType && fn) inline explicit noexcept
Definition at line 76 of file ScopeGuard.h.
       : ScopeGuardImpl(
             std::move_if_noexcept(fn),
             makeFailsafe(
                 std::is_nothrow_move_constructible<FunctionType>{},
                 &fn)) {}
template<typename FunctionType, bool InvokeNoexcept> folly::detail::ScopeGuardImpl< FunctionType, InvokeNoexcept >::ScopeGuardImpl (ScopeGuardImpl< FunctionType, InvokeNoexcept > && other) inline noexcept
Definition at line 84 of file ScopeGuard.h.
References folly::detail::ScopeGuardImplBase::dismissed_, and folly::exchange().
       : function_(std::move_if_noexcept(other.function_)) {
     // If the above line attempts a copy and the copy throws, other is
     // left owning the cleanup action and will execute it (or not) depending
     // on the value of other.dismissed_. The following lines only execute
     // if the move/copy succeeded, in which case *this assumes ownership of
     // the cleanup action and dismisses other.
     dismissed_ = exchange(other.dismissed_, true);
   }
template<typename FunctionType, bool InvokeNoexcept> folly::detail::ScopeGuardImpl< FunctionType, InvokeNoexcept >::~ScopeGuardImpl () inline noexcept
Definition at line 95 of file ScopeGuard.h.
References folly::detail::ScopeGuardImplBase::dismissed_.
{
     if (!dismissed_) {
       execute();
     }
   }
template<typename FunctionType, bool InvokeNoexcept> template<typename Fn > folly::detail::ScopeGuardImpl< FunctionType, InvokeNoexcept >::ScopeGuardImpl (Fn && fn, ScopeGuardImplBase && failsafe) inline explicit private
Definition at line 114 of file ScopeGuard.h.
References folly::detail::ScopeGuardImplBase::dismiss().
       : ScopeGuardImplBase{}, function_(std::forward<Fn>(fn)) {
     failsafe.dismiss();
   }
Member Function Documentation
template<typename FunctionType, bool InvokeNoexcept> void folly::detail::ScopeGuardImpl< FunctionType, InvokeNoexcept >::execute () inline private noexcept
Definition at line 121 of file ScopeGuard.h.
References folly::detail::ScopeGuardImplBase::warnAboutToCrash().
{
     if (InvokeNoexcept) {
       try {
         function_();
       } catch (...) {
         warnAboutToCrash();
         std::terminate();
       }
     } else {
       function_();
     }
   }
template<typename FunctionType, bool InvokeNoexcept> static ScopeGuardImplBase folly::detail::ScopeGuardImpl< FunctionType, InvokeNoexcept >::makeFailsafe (std::true_type , const void *) inline static private noexcept
Definition at line 102 of file ScopeGuard.h.
References folly::detail::ScopeGuardImplBase::makeEmptyScopeGuard().
{
     return makeEmptyScopeGuard();
   }
template<typename FunctionType, bool InvokeNoexcept> template<typename Fn > static auto folly::detail::ScopeGuardImpl< FunctionType, InvokeNoexcept >::makeFailsafe (std::false_type , Fn * fn) -> ScopeGuardImpl<decltype(std::ref(*fn)), InvokeNoexcept> inline static private noexcept
Definition at line 107 of file ScopeGuard.h.
{
     return ScopeGuardImpl<decltype(std::ref(*fn)), InvokeNoexcept>{
         std::ref(*fn)};
   }
template<typename FunctionType, bool InvokeNoexcept> void* folly::detail::ScopeGuardImpl< FunctionType, InvokeNoexcept >::operator new (std::size_t) private delete
Member Data Documentation
template<typename FunctionType, bool InvokeNoexcept> FunctionType folly::detail::ScopeGuardImpl< FunctionType, InvokeNoexcept >::function_ private
Definition at line 134 of file ScopeGuard.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/ScopeGuard.h