proxygen: testing::internal::FieldMatcher< Class, FieldType > Class Template Reference
testing::internal::FieldMatcher< Class, FieldType > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
FieldMatcher (FieldType Class::*field, const Matcher< const FieldType & > &matcher)
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
template<typename T >
bool MatchAndExplain (const T &value, MatchResultListener *listener) const
FieldMatcher (FieldType Class::*field, const Matcher< const FieldType & > &matcher)
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
template<typename T >
bool MatchAndExplain (const T &value, MatchResultListener *listener) const
FieldMatcher (FieldType Class::*field, const Matcher< const FieldType & > &matcher)
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
template<typename T >
bool MatchAndExplain (const T &value, MatchResultListener *listener) const
Private Member Functions
bool MatchAndExplainImpl (false_type, const Class &obj, MatchResultListener *listener) const
bool MatchAndExplainImpl (true_type, const Class *p, MatchResultListener *listener) const
GTEST_DISALLOW_ASSIGN_ (FieldMatcher)
bool MatchAndExplainImpl (false_type, const Class &obj, MatchResultListener *listener) const
bool MatchAndExplainImpl (true_type, const Class *p, MatchResultListener *listener) const
GTEST_DISALLOW_ASSIGN_ (FieldMatcher)
bool MatchAndExplainImpl (false_type, const Class &obj, MatchResultListener *listener) const
bool MatchAndExplainImpl (true_type, const Class *p, MatchResultListener *listener) const
GTEST_DISALLOW_ASSIGN_ (FieldMatcher)
Private Attributes
const FieldType Class::* field_
const Matcher< const FieldType & > matcher_
Detailed Description
template<typename Class, typename FieldType>
class testing::internal::FieldMatcher< Class, FieldType >
Definition at line 2181 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename Class , typename FieldType > testing::internal::FieldMatcher< Class, FieldType >::FieldMatcher (FieldType Class::* field, const Matcher< const FieldType & > & matcher) inline
Definition at line 2183 of file gmock-matchers.h.
       : field_(field), matcher_(matcher) {}
template<typename Class , typename FieldType > testing::internal::FieldMatcher< Class, FieldType >::FieldMatcher (FieldType Class::* field, const Matcher< const FieldType & > & matcher) inline
Definition at line 2183 of file gmock-matchers.h.
       : field_(field), matcher_(matcher) {}
template<typename Class , typename FieldType > testing::internal::FieldMatcher< Class, FieldType >::FieldMatcher (FieldType Class::* field, const Matcher< const FieldType & > & matcher) inline
Definition at line 2183 of file gmock-matchers.h.
       : field_(field), matcher_(matcher) {}
Member Function Documentation
template<typename Class , typename FieldType > void testing::internal::FieldMatcher< Class, FieldType >::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 2192 of file gmock-matchers.h.
{
     *os << "is an object whose given field ";
     matcher_.DescribeNegationTo(os);
   }
template<typename Class , typename FieldType > void testing::internal::FieldMatcher< Class, FieldType >::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 2192 of file gmock-matchers.h.
{
     *os << "is an object whose given field ";
     matcher_.DescribeNegationTo(os);
   }
template<typename Class , typename FieldType > void testing::internal::FieldMatcher< Class, FieldType >::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 2192 of file gmock-matchers.h.
{
     *os << "is an object whose given field ";
     matcher_.DescribeNegationTo(os);
   }
template<typename Class , typename FieldType > void testing::internal::FieldMatcher< Class, FieldType >::DescribeTo (::std::ostream * os) const inline
Definition at line 2187 of file gmock-matchers.h.
{
     *os << "is an object whose given field ";
     matcher_.DescribeTo(os);
   }
template<typename Class , typename FieldType > void testing::internal::FieldMatcher< Class, FieldType >::DescribeTo (::std::ostream * os) const inline
Definition at line 2187 of file gmock-matchers.h.
{
     *os << "is an object whose given field ";
     matcher_.DescribeTo(os);
   }
template<typename Class , typename FieldType > void testing::internal::FieldMatcher< Class, FieldType >::DescribeTo (::std::ostream * os) const inline
Definition at line 2187 of file gmock-matchers.h.
{
     *os << "is an object whose given field ";
     matcher_.DescribeTo(os);
   }
template<typename Class , typename FieldType > testing::internal::FieldMatcher< Class, FieldType >::GTEST_DISALLOW_ASSIGN_ (FieldMatcher< Class, FieldType >) private
template<typename Class , typename FieldType > testing::internal::FieldMatcher< Class, FieldType >::GTEST_DISALLOW_ASSIGN_ (FieldMatcher< Class, FieldType >) private
template<typename Class , typename FieldType > testing::internal::FieldMatcher< Class, FieldType >::GTEST_DISALLOW_ASSIGN_ (FieldMatcher< Class, FieldType >) private
template<typename Class , typename FieldType > template<typename T > bool testing::internal::FieldMatcher< Class, FieldType >::MatchAndExplain (const T & value, MatchResultListener * listener) const inline
Definition at line 2198 of file gmock-matchers.h.
References GTEST_REMOVE_CONST_, and type.
{
     return MatchAndExplainImpl(
         typename ::testing::internal::
             is_pointer<GTEST_REMOVE_CONST_(T)>::type(),
         value, listener);
   }
template<typename Class , typename FieldType > template<typename T > bool testing::internal::FieldMatcher< Class, FieldType >::MatchAndExplain (const T & value, MatchResultListener * listener) const inline
Definition at line 2198 of file gmock-matchers.h.
References GTEST_REMOVE_CONST_, and type.
{
     return MatchAndExplainImpl(
         typename ::testing::internal::
             is_pointer<GTEST_REMOVE_CONST_(T)>::type(),
         value, listener);
   }
template<typename Class , typename FieldType > template<typename T > bool testing::internal::FieldMatcher< Class, FieldType >::MatchAndExplain (const T & value, MatchResultListener * listener) const inline
Definition at line 2198 of file gmock-matchers.h.
References GTEST_REMOVE_CONST_, T, and type.
{
     return MatchAndExplainImpl(
         typename ::testing::internal::
             is_pointer<GTEST_REMOVE_CONST_(T)>::type(),
         value, listener);
   }
template<typename Class , typename FieldType > bool testing::internal::FieldMatcher< Class, FieldType >::MatchAndExplainImpl (false_type , const Class & obj, MatchResultListener * listener) const inline private
Definition at line 2209 of file gmock-matchers.h.
References testing::internal::MatchPrintAndExplain().
{
     *listener << "whose given field is ";
     return MatchPrintAndExplain(obj.*field_, matcher_, listener);
   }
template<typename Class , typename FieldType > bool testing::internal::FieldMatcher< Class, FieldType >::MatchAndExplainImpl (false_type , const Class & obj, MatchResultListener * listener) const inline private
Definition at line 2209 of file gmock-matchers.h.
References testing::internal::MatchPrintAndExplain().
{
     *listener << "whose given field is ";
     return MatchPrintAndExplain(obj.*field_, matcher_, listener);
   }
template<typename Class , typename FieldType > bool testing::internal::FieldMatcher< Class, FieldType >::MatchAndExplainImpl (false_type , const Class & obj, MatchResultListener * listener) const inline private
Definition at line 2209 of file gmock-matchers.h.
References testing::internal::MatchPrintAndExplain().
{
     *listener << "whose given field is ";
     return MatchPrintAndExplain(obj.*field_, matcher_, listener);
   }
template<typename Class , typename FieldType > bool testing::internal::FieldMatcher< Class, FieldType >::MatchAndExplainImpl (true_type , const Class * p, MatchResultListener * listener) const inline private
Definition at line 2215 of file gmock-matchers.h.
{
     if (p == NULL)
       return false;
     *listener << "which points to an object ";
     // Since *p has a field, it must be a class/struct/union type and
     // thus cannot be a pointer.  Therefore we pass false_type() as
     // the first argument.
     return MatchAndExplainImpl(false_type(), *p, listener);
   }
template<typename Class , typename FieldType > bool testing::internal::FieldMatcher< Class, FieldType >::MatchAndExplainImpl (true_type , const Class * p, MatchResultListener * listener) const inline private
Definition at line 2215 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, and GTEST_REFERENCE_TO_CONST_.
{
     if (p == NULL)
       return false;
     *listener << "which points to an object ";
     // Since *p has a field, it must be a class/struct/union type and
     // thus cannot be a pointer.  Therefore we pass false_type() as
     // the first argument.
     return MatchAndExplainImpl(false_type(), *p, listener);
   }
template<typename Class , typename FieldType > bool testing::internal::FieldMatcher< Class, FieldType >::MatchAndExplainImpl (true_type , const Class * p, MatchResultListener * listener) const inline private
Definition at line 2215 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, and GTEST_REFERENCE_TO_CONST_.
{
     if (p == NULL)
       return false;
     *listener << "which points to an object ";
     // Since *p has a field, it must be a class/struct/union type and
     // thus cannot be a pointer.  Therefore we pass false_type() as
     // the first argument.
     return MatchAndExplainImpl(false_type(), *p, listener);
   }
Member Data Documentation
template<typename Class , typename FieldType > const FieldType Class::* testing::internal::FieldMatcher< Class, FieldType >::field_ private
Definition at line 2227 of file gmock-matchers.h.
template<typename Class , typename FieldType > const Matcher< const FieldType & > testing::internal::FieldMatcher< Class, FieldType >::matcher_ private
Definition at line 2228 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h