proxygen: fizz::WriteRecordLayer Class Reference
fizz::WriteRecordLayer Class Reference abstract
#include <RecordLayer.h>
Public Member Functions
virtual ~WriteRecordLayer ()=default
virtual TLSContent write (TLSMessage &&msg) const =0
TLSContent writeAlert (Alert &&alert) const
TLSContent writeAppData (std::unique_ptr< folly::IOBuf > &&appData) const
template<typename... Args>
TLSContent writeHandshake (Buf &&encodedHandshakeMsg, Args &&...args) const
void setProtocolVersion (ProtocolVersion version) const
virtual EncryptionLevel getEncryptionLevel () const =0
Protected Attributes
ProtocolVersion recordVersion_ {ProtocolVersion::tls_1_2}
bool useAdditionalData_ {true}
Static Private Member Functions
template<typename... Args>
static void addMessage (Buf &buf, Buf &&add, Args &&...args)
static void addMessage (Buf &)
Detailed Description
Definition at line 59 of file RecordLayer.h.
Constructor & Destructor Documentation
virtual fizz::WriteRecordLayer::~WriteRecordLayer () virtual default
Member Function Documentation
template<typename... Args> static void fizz::WriteRecordLayer::addMessage (Buf & buf, Buf && add, Args &&... args) inline static private
Definition at line 111 of file RecordLayer.h.
References add, and folly::gen::move.
{
     buf->prependChain(std::move(add));
     addMessage(buf, std::forward<Args>(args)...);
   }
static void fizz::WriteRecordLayer::addMessage (Buf &) inline static private
Definition at line 116 of file RecordLayer.h.
 {}
virtual EncryptionLevel fizz::WriteRecordLayer::getEncryptionLevel () const pure virtual
Returns the current encryption level of the data that the write record layer writes at.
Implemented in fizz::EncryptedWriteRecordLayer, and fizz::PlaintextWriteRecordLayer.
void fizz::WriteRecordLayer::setProtocolVersion (ProtocolVersion version) const inline
Definition at line 80 of file RecordLayer.h.
References fizz::getRealDraftVersion(), fizz::tls_1_0, fizz::tls_1_2, fizz::tls_1_3_20, fizz::tls_1_3_21, fizz::tls_1_3_22, and fizz::tls_1_3_23.
Referenced by fizz::sm::getCertificateRequest().
{
     auto realVersion = getRealDraftVersion(version);
     if (realVersion == ProtocolVersion::tls_1_3_21 ||
         realVersion == ProtocolVersion::tls_1_3_20) {
       recordVersion_ = ProtocolVersion::tls_1_0;
     } else {
       recordVersion_ = ProtocolVersion::tls_1_2;
     }
     if (realVersion == ProtocolVersion::tls_1_3_23 ||
         realVersion == ProtocolVersion::tls_1_3_22 ||
         realVersion == ProtocolVersion::tls_1_3_21 ||
         realVersion == ProtocolVersion::tls_1_3_20) {
       useAdditionalData_ = false;
     } else {
       useAdditionalData_ = true;
     }
   }
virtual TLSContent fizz::WriteRecordLayer::write (TLSMessage && msg) const pure virtual
Implemented in fizz::MockEncryptedWriteRecordLayer, fizz::EncryptedWriteRecordLayer, fizz::MockPlaintextWriteRecordLayer, fizz::PlaintextWriteRecordLayer, and fizz::test::ConcreteWriteRecordLayer.
TLSContent fizz::WriteRecordLayer::writeAlert (Alert && alert) const inline
Definition at line 65 of file RecordLayer.h.
References fizz::alert, fizz::encode(), folly::gen::move, and fizz::detail::write().
Referenced by fizz::server::detail::handleAppClose(), fizz::client::detail::handleAppClose(), fizz::server::detail::handleError(), and fizz::client::detail::handleError().
{
     return write(TLSMessage{ContentType::alert, encode(std::move(alert))});
   }
TLSContent fizz::WriteRecordLayer::writeAppData (std::unique_ptr< folly::IOBuf > && appData) const inline
Definition at line 69 of file RecordLayer.h.
References fizz::application_data, testing::Args(), folly::gen::move, and fizz::detail::write().
Referenced by fizz::sm::generateTicket(), fizz::sm::getCertificateRequest(), fizz::sm::getMaxEarlyDataSize(), and fizz::sm::handleEarlyAppWrite().
{
     return write(TLSMessage{ContentType::application_data, std::move(appData)});
   }
template<typename... Args> TLSContent fizz::WriteRecordLayer::writeHandshake (Buf && encodedHandshakeMsg, Args &&... args) const inline
Definition at line 74 of file RecordLayer.h.
References fizz::handshake, folly::gen::move, and fizz::detail::write().
Referenced by fizz::sm::generateTicket(), fizz::sm::getCertificateRequest(), fizz::sm::getHrrKeyExchangers(), fizz::sm::getMaxEarlyDataSize(), fizz::server::AeadCookieCipher< AeadType, HkdfType >::getStatelessResponse(), fizz::sm::handleCertMsg(), and fizz::sm::writeNewSessionTicket().
{
     TLSMessage msg{ContentType::handshake, std::move(encodedHandshakeMsg)};
     addMessage(msg.fragment, std::forward<Args>(args)...);
     return write(std::move(msg));
   }
Member Data Documentation
ProtocolVersion fizz::WriteRecordLayer::recordVersion_ {ProtocolVersion::tls_1_2} mutable protected
Definition at line 106 of file RecordLayer.h.
Referenced by fizz::EncryptedWriteRecordLayer::write().
bool fizz::WriteRecordLayer::useAdditionalData_ {true} mutable protected
Definition at line 107 of file RecordLayer.h.
Referenced by fizz::EncryptedWriteRecordLayer::write().
The documentation for this class was generated from the following file:
proxygen/fizz/fizz/record/RecordLayer.h