proxygen: folly::Logger Class Reference
folly::Logger Class Reference
#include <Logger.h>
Public Member Functions
Logger (folly::StringPiece name)
Logger (LogCategory *cat)
Logger (LoggerDB *db, folly::StringPiece name)
LogCategory * getCategory () const
Private Attributes
LogCategory *const category_ {nullptr}
Detailed Description
Logger is the class you will use to specify the log category when logging messages with FB_LOG().
Logger is really just a small wrapper class that contains a pointer to the appropriate LogCategory object. It primarily exists as syntactic sugar to allow for easily looking up LogCategory objects.
Definition at line 157 of file Logger.h.
Constructor & Destructor Documentation
folly::Logger::Logger (folly::StringPiece name) explicit
Construct a Logger for the given category name.
A LogCategory object for this category will be created if one does not already exist.
Definition at line 28 of file Logger.cpp.
References folly::LoggerDB::get(), and folly::LoggerDB::getCategory().
 : Logger{LoggerDB::get().getCategory(name)} {}
folly::Logger::Logger (LogCategory * cat) explicit
Construct a Logger pointing to an existing LogCategory object.
Definition at line 30 of file Logger.cpp.
 : category_(cat) {}
folly::Logger::Logger (LoggerDB * db, folly::StringPiece name)
Construct a Logger for a specific LoggerDB object, rather than the main singleton.
This is primarily intended for use in unit tests.
Definition at line 32 of file Logger.cpp.
References folly::LoggerDB::getCategory().
     : Logger{db->getCategory(name)} {}
Member Function Documentation
LogCategory* folly::Logger::getCategory () const inline
Get the LogCategory that this Logger refers to.
Definition at line 183 of file Logger.h.
References category_.
Referenced by TEST().
{
     return category_;
   }
Member Data Documentation
LogCategory* const folly::Logger::category_ {nullptr} private
Definition at line 188 of file Logger.h.
Referenced by getCategory().
The documentation for this class was generated from the following files:
proxygen/folly/folly/logging/Logger.h
proxygen/folly/folly/logging/Logger.cpp