proxygen: folly::pushmi::any_constrained_single_sender< E, CV, VN > Class Template Reference
folly::pushmi::any_constrained_single_sender< E, CV, VN > Class Template Reference
#include <constrained_single_sender.h>
Classes
union data
struct vtable
Public Types
using properties = property_set< is_constrained<>, is_single<>>
Public Member Functions
any_constrained_single_sender ()=default
any_constrained_single_sender (any_constrained_single_sender &&that) noexcept
requires ConstrainedSenderTo< wrapped_t< Wrapped >, any_receiver< E, VN... > > any_constrained_single_sender (Wrapped obj) noexcept(insitu< Wrapped >())
~any_constrained_single_sender ()
any_constrained_single_sender & operator= (any_constrained_single_sender &&that) noexcept
CV top ()
any_constrained_executor< E, CV > executor ()
void submit (CV at, any_receiver< E, VN... > out)
Private Types
template<class T , class U = std::decay_t<T>>
using wrapped_t = std::enable_if_t<!std::is_same< U, any_constrained_single_sender >::value, U >
Private Member Functions
template<class Wrapped >
any_constrained_single_sender (Wrapped obj, std::false_type)
template<class Wrapped >
any_constrained_single_sender (Wrapped obj, std::true_type) noexcept
Static Private Member Functions
template<class Wrapped >
static constexpr bool insitu ()
Private Attributes
union folly::pushmi::any_constrained_single_sender::data data_
vtable const * vptr_ = &noop_
Static Private Attributes
static constexpr vtable const noop_ {}
Detailed Description
template<class E, class CV, class... VN>
class folly::pushmi::any_constrained_single_sender< E, CV, VN >
Definition at line 26 of file constrained_single_sender.h.
Member Typedef Documentation
template<class E, class CV, class... VN> using folly::pushmi::any_constrained_single_sender< E, CV, VN >::properties = property_set<is_constrained<>, is_single<>>
Definition at line 106 of file constrained_single_sender.h.
template<class E, class CV, class... VN> template<class T , class U = std::decay_t<T>> using folly::pushmi::any_constrained_single_sender< E, CV, VN >::wrapped_t = std::enable_if_t<!std::is_same<U, any_constrained_single_sender>::value, U> private
Definition at line 103 of file constrained_single_sender.h.
Constructor & Destructor Documentation
template<class E, class CV, class... VN> template<class Wrapped > folly::pushmi::any_constrained_single_sender< E, CV, VN >::any_constrained_single_sender (Wrapped obj, std::false_type) inline private
Definition at line 49 of file constrained_single_sender.h.
     : any_constrained_single_sender() {
     struct s {
       static void op(data& src, data* dst) {
         if (dst)
           dst->pobj_ = std::exchange(src.pobj_, nullptr);
         delete static_cast<Wrapped const*>(src.pobj_);
       }
       static CV top(data& src) {
         return ::folly::pushmi::top(*static_cast<Wrapped*>(src.pobj_));
       }
       static any_constrained_executor<E, CV> executor(data& src) {
         return any_constrained_executor<E, CV>{
             executor(*static_cast<Wrapped*>(src.pobj_))};
       }
       static void submit(data& src, CV at, any_receiver<E, VN...> out) {
         ::folly::pushmi::submit(
             *static_cast<Wrapped*>(src.pobj_), std::move(at), std::move(out));
       }
     };
     static const vtable vtbl{s::op, s::top, s::executor, s::submit};
     data_.pobj_ = new Wrapped(std::move(obj));
     vptr_ = &vtbl;
   }
template<class E, class CV, class... VN> template<class Wrapped > folly::pushmi::any_constrained_single_sender< E, CV, VN >::any_constrained_single_sender (Wrapped obj, std::true_type) inline private noexcept
Definition at line 74 of file constrained_single_sender.h.
     : any_constrained_single_sender() {
     struct s {
       static void op(data& src, data* dst) {
         if (dst)
           new (dst->buffer_) Wrapped(
               std::move(*static_cast<Wrapped*>((void*)src.buffer_)));
         static_cast<Wrapped const*>((void*)src.buffer_)->~Wrapped();
       }
       static CV top(data& src) {
         return ::folly::pushmi::top(*static_cast<Wrapped*>((void*)src.buffer_));
       }
       static any_constrained_executor<E, CV> executor(data& src) {
         return any_constrained_executor<E, CV>{::folly::pushmi::executor(
             *static_cast<Wrapped*>((void*)src.buffer_))};
       }
       static void submit(data& src, CV cv, any_receiver<E, VN...> out) {
         ::folly::pushmi::submit(
             *static_cast<Wrapped*>((void*)src.buffer_),
             std::move(cv),
             std::move(out));
       }
     };
     static const vtable vtbl{s::op, s::top, s::executor, s::submit};
     new (data_.buffer_) Wrapped(std::move(obj));
     vptr_ = &vtbl;
   }
template<class E, class CV, class... VN> folly::pushmi::any_constrained_single_sender< E, CV, VN >::any_constrained_single_sender () default
Referenced by folly::pushmi::any_constrained_single_sender< E, TP, VN... >::operator=().
template<class E, class CV, class... VN> folly::pushmi::any_constrained_single_sender< E, CV, VN >::any_constrained_single_sender (any_constrained_single_sender< E, CV, VN > && that) inline noexcept
Definition at line 109 of file constrained_single_sender.h.
       : any_constrained_single_sender() {
     that.vptr_->op_(that.data_, &data_);
     std::swap(that.vptr_, vptr_);
   }
template<class E, class CV, class... VN> requires ConstrainedSenderTo<wrapped_t<Wrapped>, any_receiver<E, VN...> > folly::pushmi::any_constrained_single_sender< E, CV, VN >::any_constrained_single_sender (Wrapped obj) inline explicit noexcept
Definition at line 116 of file constrained_single_sender.h.
   : any_constrained_single_sender{std::move(obj), bool_<insitu<Wrapped>()>{}} {
   }
template<class E, class CV, class... VN> folly::pushmi::any_constrained_single_sender< E, CV, VN >::~any_constrained_single_sender () inline
Definition at line 119 of file constrained_single_sender.h.
Referenced by folly::pushmi::any_constrained_single_sender< E, TP, VN... >::operator=().
{
     vptr_->op_(data_, nullptr);
   }
Member Function Documentation
template<class E, class CV, class... VN> any_constrained_executor<E, CV> folly::pushmi::any_constrained_single_sender< E, CV, VN >::executor () inline
Definition at line 130 of file constrained_single_sender.h.
Referenced by folly::pushmi::any_constrained_single_sender< E, TP, VN... >::any_constrained_single_sender(), and folly::pushmi::any_time_single_sender< E, TP, VN >::executor().
{
     return vptr_->executor_(data_);
   }
template<class E, class CV, class... VN> template<class Wrapped > static constexpr bool folly::pushmi::any_constrained_single_sender< E, CV, VN >::insitu () inline static private
Definition at line 32 of file constrained_single_sender.h.
{
     return sizeof(Wrapped) <= sizeof(data::buffer_) &&
         std::is_nothrow_move_constructible<Wrapped>::value;
   }
template<class E, class CV, class... VN> any_constrained_single_sender& folly::pushmi::any_constrained_single_sender< E, CV, VN >::operator= (any_constrained_single_sender< E, CV, VN > && that) inline noexcept
Definition at line 122 of file constrained_single_sender.h.
{
     this->~any_constrained_single_sender();
     new ((void*)this) any_constrained_single_sender(std::move(that));
     return *this;
   }
template<class E, class CV, class... VN> void folly::pushmi::any_constrained_single_sender< E, CV, VN >::submit (CV at, any_receiver< E, VN... > out) inline
Definition at line 133 of file constrained_single_sender.h.
Referenced by folly::pushmi::any_constrained_single_sender< E, TP, VN... >::any_constrained_single_sender().
{
     vptr_->submit_(data_, std::move(at), std::move(out));
   }
template<class E, class CV, class... VN> CV folly::pushmi::any_constrained_single_sender< E, CV, VN >::top () inline
Definition at line 127 of file constrained_single_sender.h.
Referenced by folly::pushmi::any_constrained_single_sender< E, TP, VN... >::any_constrained_single_sender().
            {
     return vptr_->top_(data_);
   }
Member Data Documentation
template<class E, class CV, class... VN> union folly::pushmi::any_constrained_single_sender::data folly::pushmi::any_constrained_single_sender< E, CV, VN >::data_ private
Referenced by folly::pushmi::any_constrained_single_sender< E, TP, VN... >::any_constrained_single_sender(), folly::pushmi::constrained_single_sender< Data, DSF, DZF, DEXF >::constrained_single_sender(), folly::pushmi::any_constrained_single_sender< E, TP, VN... >::executor(), folly::pushmi::any_constrained_single_sender< E, TP, VN... >::submit(), folly::pushmi::any_constrained_single_sender< E, TP, VN... >::top(), and folly::pushmi::any_constrained_single_sender< E, TP, VN... >::~any_constrained_single_sender().
template<class E, class CV, class... VN> constexpr any_constrained_single_sender< E, CV, VN... >::vtable const folly::pushmi::any_constrained_single_sender< E, CV, VN >::noop_ {} static private
Definition at line 46 of file constrained_single_sender.h.
Referenced by folly::pushmi::any_constrained_single_sender< E, TP, VN... >::submit().
template<class E, class CV, class... VN> vtable const* folly::pushmi::any_constrained_single_sender< E, CV, VN >::vptr_ = &noop_ private
Definition at line 47 of file constrained_single_sender.h.
Referenced by folly::pushmi::any_constrained_single_sender< E, TP, VN... >::any_constrained_single_sender().
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/pushmi/constrained_single_sender.h