proxygen: testing::CardinalityInterface Class Reference
testing::CardinalityInterface Class Reference abstract
#include <gmock-cardinalities.h>
Public Member Functions
virtual ~CardinalityInterface ()
virtual int ConservativeLowerBound () const
virtual int ConservativeUpperBound () const
virtual bool IsSatisfiedByCallCount (int call_count) const =0
virtual bool IsSaturatedByCallCount (int call_count) const =0
virtual void DescribeTo (::std::ostream *os) const =0
virtual ~CardinalityInterface ()
virtual int ConservativeLowerBound () const
virtual int ConservativeUpperBound () const
virtual bool IsSatisfiedByCallCount (int call_count) const =0
virtual bool IsSaturatedByCallCount (int call_count) const =0
virtual void DescribeTo (::std::ostream *os) const =0
virtual ~CardinalityInterface ()
virtual int ConservativeLowerBound () const
virtual int ConservativeUpperBound () const
virtual bool IsSatisfiedByCallCount (int call_count) const =0
virtual bool IsSaturatedByCallCount (int call_count) const =0
virtual void DescribeTo (::std::ostream *os) const =0
Detailed Description
Definition at line 59 of file gmock-cardinalities.h.
Constructor & Destructor Documentation
virtual testing::CardinalityInterface::~CardinalityInterface () inline virtual
Definition at line 61 of file gmock-cardinalities.h.
 {}
virtual testing::CardinalityInterface::~CardinalityInterface () inline virtual
Definition at line 61 of file gmock-cardinalities.h.
 {}
virtual testing::CardinalityInterface::~CardinalityInterface () inline virtual
Definition at line 61 of file gmock-cardinalities.h.
 {}
Member Function Documentation
virtual int testing::CardinalityInterface::ConservativeLowerBound () const inline virtual
Definition at line 65 of file gmock-cardinalities.h.
 { return 0; }
virtual int testing::CardinalityInterface::ConservativeLowerBound () const inline virtual
Definition at line 65 of file gmock-cardinalities.h.
 { return 0; }
virtual int testing::CardinalityInterface::ConservativeLowerBound () const inline virtual
Definition at line 65 of file gmock-cardinalities.h.
 { return 0; }
virtual int testing::CardinalityInterface::ConservativeUpperBound () const inline virtual
Definition at line 66 of file gmock-cardinalities.h.
References DescribeTo(), IsSatisfiedByCallCount(), and IsSaturatedByCallCount().
 { return INT_MAX; }
virtual int testing::CardinalityInterface::ConservativeUpperBound () const inline virtual
Definition at line 66 of file gmock-cardinalities.h.
References DescribeTo(), GTEST_API_, IsSatisfiedByCallCount(), and IsSaturatedByCallCount().
 { return INT_MAX; }
virtual int testing::CardinalityInterface::ConservativeUpperBound () const inline virtual
Definition at line 66 of file gmock-cardinalities.h.
References DescribeTo(), GTEST_API_, IsSatisfiedByCallCount(), and IsSaturatedByCallCount().
 { return INT_MAX; }
virtual void testing::CardinalityInterface::DescribeTo (::std::ostream * os) const pure virtual
virtual void testing::CardinalityInterface::DescribeTo (::std::ostream * os) const pure virtual
virtual void testing::CardinalityInterface::DescribeTo (::std::ostream * os) const pure virtual
Referenced by ConservativeUpperBound().
virtual bool testing::CardinalityInterface::IsSatisfiedByCallCount (int call_count) const pure virtual
virtual bool testing::CardinalityInterface::IsSatisfiedByCallCount (int call_count) const pure virtual
virtual bool testing::CardinalityInterface::IsSatisfiedByCallCount (int call_count) const pure virtual
Referenced by ConservativeUpperBound().
virtual bool testing::CardinalityInterface::IsSaturatedByCallCount (int call_count) const pure virtual
virtual bool testing::CardinalityInterface::IsSaturatedByCallCount (int call_count) const pure virtual
virtual bool testing::CardinalityInterface::IsSaturatedByCallCount (int call_count) const pure virtual
Referenced by ConservativeUpperBound().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-cardinalities.h