proxygen: folly::PackedSyncPtr< T > Class Template Reference
folly::PackedSyncPtr< T > Class Template Reference
#include <PackedSyncPtr.h>
Public Member Functions
void init (T *initialPtr=nullptr, uint16_t initialExtra=0)
void set (T *t)
T * get () const
T * operator-> () const
reference operator* () const
reference operator[] (std::ptrdiff_t i) const
void lock () const
void unlock () const
bool try_lock () const
uint16_t extra () const
void setExtra (uint16_t extra)
Private Types
typedef std::add_lvalue_reference< T >::type reference
Private Attributes
PicoSpinLock< uintptr_t > data_
Detailed Description
template<class T>
class folly::PackedSyncPtr< T >
Definition at line 63 of file PackedSyncPtr.h.
Member Typedef Documentation
template<class T> typedef std::add_lvalue_reference<T>::type folly::PackedSyncPtr< T >::reference private
Definition at line 67 of file PackedSyncPtr.h.
Member Function Documentation
template<class T> uint16_t folly::PackedSyncPtr< T >::extra () const inline
Definition at line 133 of file PackedSyncPtr.h.
References folly::PackedSyncPtr< T >::data_, and folly::PicoSpinLock< IntType, Bit >::getData().
Referenced by SyncVec< T >::end(), folly::atomic_shared_ptr< T, Atom, CountedDetail >::get_local_count(), folly::atomic_shared_ptr< T, Atom, CountedDetail >::get_shared_ptr(), folly::atomic_shared_ptr< T, Atom, CountedDetail >::owners_eq(), SyncVec< T >::push_back(), folly::atomic_shared_ptr< T, Atom, CountedDetail >::putOwnedBase(), folly::PackedSyncPtr< T >::set(), folly::atomic_shared_ptr< T, Atom, CountedDetail >::takeOwnedBase(), and TEST().
{
     return data_.getData() >> 48;
   }
template<class T> T* folly::PackedSyncPtr< T >::get () const inline
Definition at line 103 of file PackedSyncPtr.h.
References folly::PackedSyncPtr< T >::data_, folly::PicoSpinLock< IntType, Bit >::getData(), and folly::T.
Referenced by SyncVec< T >::begin(), folly::atomic_shared_ptr< T, Atom, CountedDetail >::compare_exchange_weak(), SyncVec< T >::end(), folly::atomic_shared_ptr< T, Atom, CountedDetail >::get_shared_ptr(), folly::atomic_shared_ptr< T, Atom, CountedDetail >::owners_eq(), SyncVec< T >::push_back(), folly::atomic_shared_ptr< T, Atom, CountedDetail >::putOwnedBase(), folly::atomic_shared_ptr< T, Atom, CountedDetail >::release_external(), folly::atomic_shared_ptr< T, Atom, CountedDetail >::takeOwnedBase(), TEST(), and SyncVec< T >::~SyncVec().
                  {
     return reinterpret_cast<T*>(data_.getData() & (-1ull >> 16));
   }
template<class T> void folly::PackedSyncPtr< T >::init (T * initialPtr = nullptr, uint16_t initialExtra = 0) inline
Definition at line 77 of file PackedSyncPtr.h.
References folly::PackedSyncPtr< T >::data_, folly::PicoSpinLock< IntType, Bit >::init(), and folly::PackedSyncPtr< T >::setExtra().
Referenced by folly::atomic_shared_ptr< T, Atom, CountedDetail >::get_newptr(), folly::atomic_shared_ptr< T, Atom, CountedDetail >::init(), SyncVec< T >::SyncVec(), and TEST().
{
     auto intPtr = reinterpret_cast<uintptr_t>(initialPtr);
     CHECK(!(intPtr >> 48));
     data_.init(intPtr);
     setExtra(initialExtra);
   }
template<class T> void folly::PackedSyncPtr< T >::lock () const inline
Definition at line 118 of file PackedSyncPtr.h.
References folly::PackedSyncPtr< T >::data_, and folly::PicoSpinLock< IntType, Bit >::lock().
Referenced by SyncVec< T >::lock(), and TEST().
                     {
     data_.lock();
   }
template<class T> reference folly::PackedSyncPtr< T >::operator* () const inline
Definition at line 109 of file PackedSyncPtr.h.
{
     return *get();
   }
template<class T> T* folly::PackedSyncPtr< T >::operator-> () const inline
Definition at line 106 of file PackedSyncPtr.h.
{
     return get();
   }
template<class T> reference folly::PackedSyncPtr< T >::operator[] (std::ptrdiff_t i) const inline
Definition at line 112 of file PackedSyncPtr.h.
{
     return get()[i];
   }
template<class T> void folly::PackedSyncPtr< T >::set (T * t) inline
Definition at line 89 of file PackedSyncPtr.h.
References folly::PackedSyncPtr< T >::data_, folly::PackedSyncPtr< T >::extra(), folly::PicoSpinLock< IntType, Bit >::setData(), and folly::pushmi::detail::t.
Referenced by SyncVec< T >::push_back(), and TEST().
                  {
     auto intPtr = reinterpret_cast<uintptr_t>(t);
     auto shiftedExtra = uintptr_t(extra()) << 48;
     CHECK(!(intPtr >> 48));
     data_.setData(intPtr | shiftedExtra);
   }
template<class T> void folly::PackedSyncPtr< T >::setExtra (uint16_t extra) inline
Definition at line 143 of file PackedSyncPtr.h.
References folly::PackedSyncPtr< T >::data_, folly::PicoSpinLock< IntType, Bit >::getData(), ptr, and folly::PicoSpinLock< IntType, Bit >::setData().
Referenced by folly::PackedSyncPtr< T >::init(), SyncVec< T >::push_back(), folly::atomic_shared_ptr< T, Atom, CountedDetail >::takeOwnedBase(), and TEST().
{
     CHECK(!(extra & 0x8000));
     auto ptr = data_.getData() & (-1ull >> 16);
     data_.setData((uintptr_t(extra) << 48) | ptr);
   }
template<class T> bool folly::PackedSyncPtr< T >::try_lock () const inline
Definition at line 124 of file PackedSyncPtr.h.
References folly::PackedSyncPtr< T >::data_, and folly::PicoSpinLock< IntType, Bit >::try_lock().
{
     return data_.try_lock();
   }
template<class T> void folly::PackedSyncPtr< T >::unlock () const inline
Definition at line 121 of file PackedSyncPtr.h.
References folly::PackedSyncPtr< T >::data_, and folly::PicoSpinLock< IntType, Bit >::unlock().
Referenced by TEST(), and SyncVec< T >::unlock().
                       {
     data_.unlock();
   }
Member Data Documentation
template<class T> PicoSpinLock<uintptr_t> folly::PackedSyncPtr< T >::data_ private
Definition at line 150 of file PackedSyncPtr.h.
Referenced by folly::PackedSyncPtr< T >::extra(), folly::PackedSyncPtr< T >::get(), folly::PackedSyncPtr< T >::init(), folly::PackedSyncPtr< T >::lock(), folly::PackedSyncPtr< T >::set(), folly::PackedSyncPtr< T >::setExtra(), folly::PackedSyncPtr< T >::try_lock(), and folly::PackedSyncPtr< T >::unlock().
The documentation for this class was generated from the following file:
proxygen/folly/folly/PackedSyncPtr.h