proxygen: fizz::EncryptedWriteRecordLayer Class Reference
fizz::EncryptedWriteRecordLayer Class Reference
#include <EncryptedRecordLayer.h>
Public Member Functions
~EncryptedWriteRecordLayer () override=default
EncryptedWriteRecordLayer (EncryptionLevel encryptionLevel)
TLSContent write (TLSMessage &&msg) const override
virtual void setAead (folly::ByteRange, std::unique_ptr< Aead > aead)
void setMaxRecord (uint16_t size)
void setMinDesiredRecord (uint16_t size)
EncryptionLevel getEncryptionLevel () const override
Public Member Functions inherited from fizz::WriteRecordLayer
virtual ~WriteRecordLayer ()=default
TLSContent writeAlert (Alert &&alert) const
TLSContent writeAppData (std::unique_ptr< folly::IOBuf > &&appData) const
template<typename... Args>
TLSContent writeHandshake (Buf &&encodedHandshakeMsg, Args &&...args) const
void setProtocolVersion (ProtocolVersion version) const
Private Member Functions
Buf getBufToEncrypt (folly::IOBufQueue &queue) const
Private Attributes
std::unique_ptr< Aead > aead_
uint16_t maxRecord_ {kMaxPlaintextRecordSize}
uint16_t desiredMinRecord_ {kMinSuggestedRecordSize}
uint64_t seqNum_ {0}
EncryptionLevel encryptionLevel_
Additional Inherited Members
Protected Attributes inherited from fizz::WriteRecordLayer
ProtocolVersion recordVersion_ {ProtocolVersion::tls_1_2}
bool useAdditionalData_ {true}
Detailed Description
Definition at line 67 of file EncryptedRecordLayer.h.
Constructor & Destructor Documentation
fizz::EncryptedWriteRecordLayer::~EncryptedWriteRecordLayer () override default
fizz::EncryptedWriteRecordLayer::EncryptedWriteRecordLayer (EncryptionLevel encryptionLevel) explicit
Definition at line 143 of file EncryptedRecordLayer.cpp.
     : encryptionLevel_(encryptionLevel) {}
Member Function Documentation
Buf fizz::EncryptedWriteRecordLayer::getBufToEncrypt (folly::IOBufQueue & queue) const private
Definition at line 222 of file EncryptedRecordLayer.cpp.
References desiredMinRecord_, folly::IOBufQueue::front(), folly::IOBuf::length(), maxRecord_, folly::IOBufQueue::pop_front(), and folly::IOBufQueue::splitAtMost().
Referenced by write().
{
   if (queue.front()->length() > maxRecord_) {
     return queue.splitAtMost(maxRecord_);
   } else if (queue.front()->length() >= desiredMinRecord_) {
     return queue.pop_front();
   } else {
     return queue.splitAtMost(desiredMinRecord_);
   }
 }
EncryptionLevel fizz::EncryptedWriteRecordLayer::getEncryptionLevel () const override virtual
Returns the current encryption level of the data that the write record layer writes at.
Implements fizz::WriteRecordLayer.
Definition at line 232 of file EncryptedRecordLayer.cpp.
References encryptionLevel_.
{
   return encryptionLevel_;
 }
virtual void fizz::EncryptedWriteRecordLayer::setAead (folly::ByteRange , std::unique_ptr< Aead > aead) inline virtual
Reimplemented in fizz::MockEncryptedWriteRecordLayer.
Definition at line 75 of file EncryptedRecordLayer.h.
References fizz::EncryptedReadRecordLayer::aead_, folly::gen::move, and fizz::EncryptedReadRecordLayer::seqNum_.
{
     if (seqNum_ != 0) {
       throw std::runtime_error("aead set after write");
     }
     aead_ = std::move(aead);
   }
void fizz::EncryptedWriteRecordLayer::setMaxRecord (uint16_t size) inline
Definition at line 84 of file EncryptedRecordLayer.h.
References folly::size().
{
     CHECK_GT(size, 0);
     DCHECK_LE(size, kMaxPlaintextRecordSize);
     maxRecord_ = size;
   }
void fizz::EncryptedWriteRecordLayer::setMinDesiredRecord (uint16_t size) inline
Definition at line 90 of file EncryptedRecordLayer.h.
References fizz::EncryptedReadRecordLayer::getEncryptionLevel(), and folly::size().
{
     CHECK_GT(size, 0);
     DCHECK_LE(size, kMaxPlaintextRecordSize);
     desiredMinRecord_ = size;
   }
TLSContent fizz::EncryptedWriteRecordLayer::write (TLSMessage && msg) const override virtual
Implements fizz::WriteRecordLayer.
Reimplemented in fizz::MockEncryptedWriteRecordLayer.
Definition at line 147 of file EncryptedRecordLayer.cpp.
References aead_, folly::IOBufQueue::append(), fizz::application_data, fizz::TLSContent::contentType, folly::IOBuf::copyBuffer(), folly::IOBuf::create(), fizz::TLSContent::data, folly::IOBufQueue::empty(), fizz::TLSContent::encryptionLevel, encryptionLevel_, getBufToEncrypt(), fizz::kEncryptedHeaderSize, max, folly::gen::move, folly::IOBuf::prependChain(), folly::range(), fizz::WriteRecordLayer::recordVersion_, seqNum_, uint16_t, fizz::WriteRecordLayer::useAdditionalData_, folly::IOBuf::wrapBufferAsValue(), and folly::io::detail::Writable< Derived >::writeBE().
{
   folly::IOBufQueue queue;
   queue.append(std::move(msg.fragment));
   std::unique_ptr<folly::IOBuf> outBuf;
   std::array<uint8_t, kEncryptedHeaderSize> headerBuf;
   auto header = folly::IOBuf::wrapBufferAsValue(folly::range(headerBuf));
   aead_->setEncryptedBufferHeadroom(kEncryptedHeaderSize);
   while (!queue.empty()) {
     auto dataBuf = getBufToEncrypt(queue);
     // Currently we never send padding.
     // check if we have enough room to add the encrypted footer.
     if (!dataBuf->isShared() &&
         dataBuf->prev()->tailroom() >= sizeof(ContentType)) {
       // extend it and add it
       folly::io::Appender appender(dataBuf.get(), 0);
       appender.writeBE(static_cast<ContentTypeType>(msg.type));
     } else {
       // not enough or shared - let's add enough for the tag as well
       auto encryptedFooter = folly::IOBuf::create(
           sizeof(ContentType) + aead_->getCipherOverhead());
       folly::io::Appender appender(encryptedFooter.get(), 0);
       appender.writeBE(static_cast<ContentTypeType>(msg.type));
       dataBuf->prependChain(std::move(encryptedFooter));
     }
     if (seqNum_ == std::numeric_limits<uint64_t>::max()) {
       throw std::runtime_error("max write seq num");
     }
     // we will either be able to memcpy directly into the ciphertext or
     // need to create a new buf to insert before the ciphertext but we need
     // it for additional data
     header.clear();
     folly::io::Appender appender(&header, 0);
     appender.writeBE(
         static_cast<ContentTypeType>(ContentType::application_data));
     appender.writeBE(static_cast<ProtocolVersionType>(recordVersion_));
     auto ciphertextLength =
         dataBuf->computeChainDataLength() + aead_->getCipherOverhead();
     appender.writeBE<uint16_t>(ciphertextLength);
     auto cipherText = aead_->encrypt(
         std::move(dataBuf), useAdditionalData_ ? &header : nullptr, seqNum_++);
     std::unique_ptr<folly::IOBuf> record;
     if (!cipherText->isShared() &&
         cipherText->headroom() >= kEncryptedHeaderSize) {
       // prepend and then write it in
       cipherText->prepend(kEncryptedHeaderSize);
       memcpy(cipherText->writableData(), header.data(), header.length());
       record = std::move(cipherText);
     } else {
       record = folly::IOBuf::copyBuffer(header.data(), header.length());
       record->prependChain(std::move(cipherText));
     }
     if (!outBuf) {
       outBuf = std::move(record);
     } else {
       outBuf->prependChain(std::move(record));
     }
   }
   if (!outBuf) {
     outBuf = folly::IOBuf::create(0);
   }
   TLSContent content;
   content.data = std::move(outBuf);
   content.contentType = msg.type;
   content.encryptionLevel = encryptionLevel_;
   return content;
 }
Member Data Documentation
std::unique_ptr<Aead> fizz::EncryptedWriteRecordLayer::aead_ private
Definition at line 101 of file EncryptedRecordLayer.h.
Referenced by write().
uint16_t fizz::EncryptedWriteRecordLayer::desiredMinRecord_ {kMinSuggestedRecordSize} private
Definition at line 104 of file EncryptedRecordLayer.h.
Referenced by getBufToEncrypt().
EncryptionLevel fizz::EncryptedWriteRecordLayer::encryptionLevel_ private
Definition at line 107 of file EncryptedRecordLayer.h.
Referenced by getEncryptionLevel(), and write().
uint16_t fizz::EncryptedWriteRecordLayer::maxRecord_ {kMaxPlaintextRecordSize} private
Definition at line 103 of file EncryptedRecordLayer.h.
Referenced by getBufToEncrypt().
uint64_t fizz::EncryptedWriteRecordLayer::seqNum_ {0} mutable private
Definition at line 106 of file EncryptedRecordLayer.h.
Referenced by write().
The documentation for this class was generated from the following files:
proxygen/fizz/fizz/record/EncryptedRecordLayer.h
proxygen/fizz/fizz/record/EncryptedRecordLayer.cpp