proxygen: folly::gen::detail::UnsplitBuffer< Delimiter, OutputBuffer > Class Template Reference
folly::gen::detail::UnsplitBuffer< Delimiter, OutputBuffer > Class Template Reference
#include <String-inl.h>
Public Member Functions
UnsplitBuffer (const Delimiter &delimiter, OutputBuffer *outputBuffer)
template<class Source , class Value >
void compose (const GenImpl< Value, Source > &source) const
Public Member Functions inherited from folly::gen::Operator< UnsplitBuffer< Delimiter, OutputBuffer > >
ResultGen compose (const GenImpl< Value, Source > &source) const
Public Member Functions inherited from folly::gen::FBounded< Self >
const Self & self () const
Self & self ()
Private Attributes
Delimiter delimiter_
OutputBuffer * outputBuffer_
Additional Inherited Members
Protected Member Functions inherited from folly::gen::Operator< UnsplitBuffer< Delimiter, OutputBuffer > >
Operator ()=default
Operator (Operator &&) noexcept=default
Operator (const Operator &)=default
Operator & operator= (Operator &&) noexcept=default
Operator & operator= (const Operator &)=default
Detailed Description
template<class Delimiter, class OutputBuffer>
class folly::gen::detail::UnsplitBuffer< Delimiter, OutputBuffer >
UnsplitBuffer - For joining tokens from a generator into a string, and inserting them into a custom buffer.
This type is primarily used through the 'unsplit' function.
Definition at line 326 of file String-inl.h.
Constructor & Destructor Documentation
template<class Delimiter, class OutputBuffer> folly::gen::detail::UnsplitBuffer< Delimiter, OutputBuffer >::UnsplitBuffer (const Delimiter & delimiter, OutputBuffer * outputBuffer) inline
Definition at line 331 of file String-inl.h.
       : delimiter_(delimiter), outputBuffer_(outputBuffer) {
     CHECK(outputBuffer);
   }
Member Function Documentation
template<class Delimiter, class OutputBuffer> template<class Source , class Value > void folly::gen::detail::UnsplitBuffer< Delimiter, OutputBuffer >::compose (const GenImpl< Value, Source > & source) const inline
Definition at line 337 of file String-inl.h.
References folly::toAppend(), v, and testing::Value().
Referenced by folly::gen::detail::Unsplit< Delimiter, Output >::compose().
{
     // If the output buffer is empty, we skip inserting the delimiter for the
     // first element.
     bool skipDelim = outputBuffer_->empty();
     source | [&](Value v) {
       if (skipDelim) {
         skipDelim = false;
         toAppend(std::forward<Value>(v), outputBuffer_);
       } else {
         toAppend(delimiter_, std::forward<Value>(v), outputBuffer_);
       }
     };
   }
Member Data Documentation
template<class Delimiter, class OutputBuffer> Delimiter folly::gen::detail::UnsplitBuffer< Delimiter, OutputBuffer >::delimiter_ private
Definition at line 327 of file String-inl.h.
template<class Delimiter, class OutputBuffer> OutputBuffer* folly::gen::detail::UnsplitBuffer< Delimiter, OutputBuffer >::outputBuffer_ private
Definition at line 328 of file String-inl.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/gen/String-inl.h