proxygen: folly::Indestructible< T > Class Template Reference
folly::Indestructible< T > Class Template Reference final
#include <Indestructible.h>
Classes
union Storage
Public Member Functions
template<typename S = T, typename = decltype(S())>
constexpr Indestructible () noexcept(noexcept(T()))
template<typename U = T, _t< std::enable_if< std::is_constructible< T, U && >::value >> * = nullptr, _t< std::enable_if< !std::is_same< Indestructible< T >, remove_cvref_t< U >>::value >> * = nullptr, _t< std::enable_if<!std::is_convertible< U &&, T >::value >> * = nullptr>
constexpr Indestructible (U &&u) noexcept(noexcept(T(std::declval< U >())))
template<typename U = T, _t< std::enable_if< std::is_constructible< T, U && >::value >> * = nullptr, _t< std::enable_if< !std::is_same< Indestructible< T >, remove_cvref_t< U >>::value >> * = nullptr, _t< std::enable_if< std::is_convertible< U &&, T >::value >> * = nullptr>
constexpr Indestructible (U &&u) noexcept(noexcept(T(std::declval< U >())))
template<typename... Args, typename = decltype(T(std::declval<Args>()...))>
constexpr Indestructible (Args &&...args) noexcept(noexcept(T(std::declval< Args >()...)))
template<typename U , typename... Args, typename = decltype(T(std::declval<std::initializer_list<U>&>(), std::declval<Args>()...))>
constexpr Indestructible (std::initializer_list< U > il, Args...args) noexcept(noexcept(T(std::declval< std::initializer_list< U > & >(), std::declval< Args >()...)))
~Indestructible ()=default
Indestructible (Indestructible const &)=delete
Indestructible & operator= (Indestructible const &)=delete
Indestructible (Indestructible &&other) noexcept(noexcept(T(std::declval< T >())))
Indestructible & operator= (Indestructible &&other) noexcept(noexcept(T(std::declval< T >())))
T * get () noexcept
T const * get () const noexcept
T & operator* () noexcept
T const & operator* () const noexcept
T * operator-> () noexcept
T const * operator-> () const noexcept
Private Member Functions
void check () const noexcept
Private Attributes
Storage storage_ {}
bool erased_ {false}
Detailed Description
template<typename T>
class folly::Indestructible< T >
Definition at line 61 of file Indestructible.h.
Constructor & Destructor Documentation
template<typename T> template<typename S = T, typename = decltype(S())> constexpr folly::Indestructible< T >::Indestructible () inline noexcept
Definition at line 64 of file Indestructible.h.
References folly::T, and folly::value().
Referenced by folly::Indestructible< T >::Indestructible().
 {}
template<typename T> template<typename U = T, _t< std::enable_if< std::is_constructible< T, U && >::value >> * = nullptr, _t< std::enable_if< !std::is_same< Indestructible< T >, remove_cvref_t< U >>::value >> * = nullptr, _t< std::enable_if<!std::is_convertible< U &&, T >::value >> * = nullptr> constexpr folly::Indestructible< T >::Indestructible (U && u) inline explicit noexcept
Constructor accepting a single argument by forwarding reference, this allows using list initialzation without the overhead of things like in_place, etc and also works with std::initializer_list constructors which can't be deduced, the default parameter helps there.
auto i = folly::Indestructible<std::map<int, int>>{{{1, 2}}};
This provides convenience
There are two versions of this constructor - one for when the element is implicitly constructible from the given argument and one for when the type is explicitly but not implicitly constructible from the given argument.
Definition at line 88 of file Indestructible.h.
References folly::T.
       : storage_(std::forward<U>(u)) {}
template<typename T> template<typename U = T, _t< std::enable_if< std::is_constructible< T, U && >::value >> * = nullptr, _t< std::enable_if< !std::is_same< Indestructible< T >, remove_cvref_t< U >>::value >> * = nullptr, _t< std::enable_if< std::is_convertible< U &&, T >::value >> * = nullptr> constexpr folly::Indestructible< T >::Indestructible (U && u) inline noexcept
Definition at line 98 of file Indestructible.h.
References testing::Args(), and folly::T.
       : storage_(std::forward<U>(u)) {}
template<typename T> template<typename... Args, typename = decltype(T(std::declval<Args>()...))> constexpr folly::Indestructible< T >::Indestructible (Args &&... args) inline explicit noexcept
Definition at line 103 of file Indestructible.h.
References testing::Args(), and folly::T.
       : storage_(std::forward<Args>(args)...) {}
template<typename T> template<typename U , typename... Args, typename = decltype(T(std::declval<std::initializer_list<U>&>(), std::declval<Args>()...))> constexpr folly::Indestructible< T >::Indestructible (std::initializer_list< U > il, Args... args) inline explicit noexcept
Definition at line 112 of file Indestructible.h.
References folly::Indestructible< T >::Indestructible(), folly::Indestructible< T >::operator=(), and folly::Indestructible< T >::~Indestructible().
       : storage_(il, std::forward<Args>(args)...) {}
template<typename T> folly::Indestructible< T >::~Indestructible () default
Referenced by folly::Indestructible< T >::Indestructible().
template<typename T> folly::Indestructible< T >::Indestructible (Indestructible< T > const &) delete
template<typename T> folly::Indestructible< T >::Indestructible (Indestructible< T > && other) inline noexcept
Definition at line 123 of file Indestructible.h.
       : storage_(std::move(other.storage_.value)) {
     other.erased_ = true;
   }
Member Function Documentation
template<typename T> void folly::Indestructible< T >::check () const inline private noexcept
Definition at line 156 of file Indestructible.h.
References folly::Indestructible< T >::erased_.
Referenced by folly::Indestructible< T >::get().
{
     assert(!erased_);
   }
template<typename T> T* folly::Indestructible< T >::get () inline noexcept
Definition at line 134 of file Indestructible.h.
References folly::Indestructible< T >::check(), folly::Indestructible< T >::storage_, and folly::Indestructible< T >::Storage::value.
Referenced by folly::getCoreAllocator().
                     {
     check();
     return &storage_.value;
   }
template<typename T> T const* folly::Indestructible< T >::get () const inline noexcept
Definition at line 138 of file Indestructible.h.
References folly::Indestructible< T >::check(), folly::Indestructible< T >::storage_, and folly::Indestructible< T >::Storage::value.
{
     check();
     return &storage_.value;
   }
template<typename T> T& folly::Indestructible< T >::operator* () inline noexcept
Definition at line 142 of file Indestructible.h.
{
     return *get();
   }
template<typename T> T const& folly::Indestructible< T >::operator* () const inline noexcept
Definition at line 145 of file Indestructible.h.
{
     return *get();
   }
template<typename T> T* folly::Indestructible< T >::operator-> () inline noexcept
Definition at line 148 of file Indestructible.h.
{
     return get();
   }
template<typename T> T const* folly::Indestructible< T >::operator-> () const inline noexcept
Definition at line 151 of file Indestructible.h.
{
     return get();
   }
template<typename T> Indestructible& folly::Indestructible< T >::operator= (Indestructible< T > const &) delete
Referenced by folly::Indestructible< T >::Indestructible().
template<typename T> Indestructible& folly::Indestructible< T >::operator= (Indestructible< T > && other) inline noexcept
Definition at line 128 of file Indestructible.h.
References folly::gen::move, folly::Indestructible< T >::storage_, and folly::Indestructible< T >::Storage::value.
{
     storage_.value = std::move(other.storage_.value);
     other.erased_ = true;
   }
Member Data Documentation
template<typename T> bool folly::Indestructible< T >::erased_ {false} private
Definition at line 175 of file Indestructible.h.
Referenced by folly::Indestructible< T >::check().
template<typename T> Storage folly::Indestructible< T >::storage_ {} private
Definition at line 174 of file Indestructible.h.
Referenced by folly::Indestructible< T >::get(), and folly::Indestructible< T >::operator=().
The documentation for this class was generated from the following file:
proxygen/folly/folly/Indestructible.h