proxygen: folly::ThreadLocalPtr< T, Tag, AccessMode > Class Template Reference
folly::ThreadLocalPtr< T, Tag, AccessMode > Class Template Reference
#include <ThreadLocal.h>
Classes
class Accessor
Public Member Functions
constexpr ThreadLocalPtr ()
ThreadLocalPtr (ThreadLocalPtr &&other) noexcept
ThreadLocalPtr & operator= (ThreadLocalPtr &&other)
~ThreadLocalPtr ()
T * get () const
T * operator-> () const
T & operator* () const
T * release ()
void reset (T *newPtr=nullptr)
operator bool () const
template<typename SourceT , typename Deleter , typename = typename std::enable_if< std::is_convertible<SourceT*, T*>::value>::type>
void reset (std::unique_ptr< SourceT, Deleter > source)
template<typename SourceT , typename = typename std::enable_if< std::is_convertible<SourceT*, T*>::value>::type>
void reset (std::unique_ptr< SourceT > source)
template<class Deleter >
void reset (T *newPtr, const Deleter &deleter)
Accessor accessAllThreads () const
Private Types
typedef threadlocal_detail::StaticMeta< Tag, AccessMode > StaticMeta
Private Member Functions
void destroy ()
ThreadLocalPtr (const ThreadLocalPtr &)=delete
ThreadLocalPtr & operator= (const ThreadLocalPtr &)=delete
Private Attributes
StaticMeta::EntryID id_
Detailed Description
template<class T, class Tag = void, class AccessMode = void>
class folly::ThreadLocalPtr< T, Tag, AccessMode >
Definition at line 56 of file ThreadLocal.h.
Member Typedef Documentation
template<class T, class Tag = void, class AccessMode = void> typedef threadlocal_detail::StaticMeta<Tag, AccessMode> folly::ThreadLocalPtr< T, Tag, AccessMode >::StaticMeta private
Definition at line 139 of file ThreadLocal.h.
Constructor & Destructor Documentation
template<class T, class Tag = void, class AccessMode = void> constexpr folly::ThreadLocalPtr< T, Tag, AccessMode >::ThreadLocalPtr () inline
Definition at line 142 of file ThreadLocal.h.
 : id_() {}
template<class T, class Tag = void, class AccessMode = void> folly::ThreadLocalPtr< T, Tag, AccessMode >::ThreadLocalPtr (ThreadLocalPtr< T, Tag, AccessMode > && other) inline noexcept
Definition at line 144 of file ThreadLocal.h.
 : id_(std::move(other.id_)) {}
template<class T, class Tag = void, class AccessMode = void> folly::ThreadLocalPtr< T, Tag, AccessMode >::~ThreadLocalPtr () inline
Definition at line 153 of file ThreadLocal.h.
                     {
     destroy();
   }
template<class T, class Tag = void, class AccessMode = void> folly::ThreadLocalPtr< T, Tag, AccessMode >::ThreadLocalPtr (const ThreadLocalPtr< T, Tag, AccessMode > &) private delete
Member Function Documentation
template<class T, class Tag = void, class AccessMode = void> Accessor folly::ThreadLocalPtr< T, Tag, AccessMode >::accessAllThreads () const inline
Definition at line 437 of file ThreadLocal.h.
Referenced by folly::detail::ThreadCachedInts< folly::detail::folly::detail::Tag >::readFull().
{
     static_assert(
         !std::is_same<Tag, void>::value,
         "Must use a unique Tag to use the accessAllThreads feature");
     return Accessor(id_.getOrAllocate(StaticMeta::instance()));
   }
template<class T, class Tag = void, class AccessMode = void> void folly::ThreadLocalPtr< T, Tag, AccessMode >::destroy () inline private
Definition at line 445 of file ThreadLocal.h.
                  {
     StaticMeta::instance().destroy(&id_);
   }
template<class T, class Tag = void, class AccessMode = void> T* folly::ThreadLocalPtr< T, Tag, AccessMode >::get () const inline
Definition at line 157 of file ThreadLocal.h.
Referenced by TEST().
                  {
     threadlocal_detail::ElementWrapper& w = StaticMeta::get(&id_);
     return static_cast<T*>(w.ptr);
   }
template<class T, class Tag = void, class AccessMode = void> folly::ThreadLocalPtr< T, Tag, AccessMode >::operator bool () const inline explicit
Definition at line 189 of file ThreadLocal.h.
{
     return get() != nullptr;
   }
template<class T, class Tag = void, class AccessMode = void> T& folly::ThreadLocalPtr< T, Tag, AccessMode >::operator* () const inline
Definition at line 166 of file ThreadLocal.h.
{
     return *get();
   }
template<class T, class Tag = void, class AccessMode = void> T* folly::ThreadLocalPtr< T, Tag, AccessMode >::operator-> () const inline
Definition at line 162 of file ThreadLocal.h.
{
     return get();
   }
template<class T, class Tag = void, class AccessMode = void> ThreadLocalPtr& folly::ThreadLocalPtr< T, Tag, AccessMode >::operator= (ThreadLocalPtr< T, Tag, AccessMode > && other) inline
Definition at line 146 of file ThreadLocal.h.
{
     assert(this != &other);
     destroy();
     id_ = std::move(other.id_);
     return *this;
   }
template<class T, class Tag = void, class AccessMode = void> ThreadLocalPtr& folly::ThreadLocalPtr< T, Tag, AccessMode >::operator= (const ThreadLocalPtr< T, Tag, AccessMode > &) private delete
template<class T, class Tag = void, class AccessMode = void> T* folly::ThreadLocalPtr< T, Tag, AccessMode >::release () inline
Definition at line 170 of file ThreadLocal.h.
Referenced by TEST().
                {
     threadlocal_detail::ElementWrapper& w = StaticMeta::get(&id_);
     return static_cast<T*>(w.release());
   }
template<class T, class Tag = void, class AccessMode = void> void folly::ThreadLocalPtr< T, Tag, AccessMode >::reset (T * newPtr = nullptr) inline
Definition at line 176 of file ThreadLocal.h.
Referenced by wangle::Observable< T >::forEachObserver(), folly::detail::ThreadCachedInts< folly::detail::folly::detail::Tag >::init(), runTestTag(), wangle::Observable< T >::subscribeImpl(), TEST(), and wangle::Observable< T >::unsubscribe().
{
     auto guard = makeGuard([&] { delete newPtr; });
     threadlocal_detail::ElementWrapper* w = &StaticMeta::get(&id_);
     w->dispose(TLPDestructionMode::THIS_THREAD);
     // need to get a new ptr since the
     // ThreadEntry::elements array can be reallocated
     w = &StaticMeta::get(&id_);
     w->cleanup();
     guard.dismiss();
     w->set(newPtr);
   }
template<class T, class Tag = void, class AccessMode = void> template<typename SourceT , typename Deleter , typename = typename std::enable_if< std::is_convertible<SourceT*, T*>::value>::type> void folly::ThreadLocalPtr< T, Tag, AccessMode >::reset (std::unique_ptr< SourceT, Deleter > source) inline
reset() that transfers ownership from a smart pointer
Definition at line 201 of file ThreadLocal.h.
{
     auto deleter = [delegate = source.get_deleter()](
                        T* ptr, TLPDestructionMode) { delegate(ptr); };
     reset(source.release(), deleter);
   }
template<class T, class Tag = void, class AccessMode = void> template<typename SourceT , typename = typename std::enable_if< std::is_convertible<SourceT*, T*>::value>::type> void folly::ThreadLocalPtr< T, Tag, AccessMode >::reset (std::unique_ptr< SourceT > source) inline
reset() that transfers ownership from a smart pointer with the default deleter
Definition at line 215 of file ThreadLocal.h.
{
     reset(source.release());
   }
template<class T, class Tag = void, class AccessMode = void> template<class Deleter > void folly::ThreadLocalPtr< T, Tag, AccessMode >::reset (T * newPtr, const Deleter & deleter) inline
reset() with a custom deleter: deleter(T* ptr, TLPDestructionMode mode) "mode" is ALL_THREADS if we're destructing this ThreadLocalPtr (and thus deleting pointers for all threads), and THIS_THREAD if we're only deleting the member for one thread (because of thread exit or reset()). Invoking the deleter must not throw.
Definition at line 228 of file ThreadLocal.h.
{
     auto guard = makeGuard([&] {
       if (newPtr) {
         deleter(newPtr, TLPDestructionMode::THIS_THREAD);
       }
     });
     threadlocal_detail::ElementWrapper* w = &StaticMeta::get(&id_);
     w->dispose(TLPDestructionMode::THIS_THREAD);
     // need to get a new ptr since the
     // ThreadEntry::elements array can be reallocated
     w = &StaticMeta::get(&id_);
     w->cleanup();
     guard.dismiss();
     w->set(newPtr, deleter);
   }
Member Data Documentation
template<class T, class Tag = void, class AccessMode = void> StaticMeta::EntryID folly::ThreadLocalPtr< T, Tag, AccessMode >::id_ mutable private
Definition at line 453 of file ThreadLocal.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/ThreadLocal.h