proxygen: folly::hazptr_obj_base< T, Atom, D > Class Template Reference
folly::hazptr_obj_base< T, Atom, D > Class Template Reference
#include <Hazptr-fwd.h>
Public Member Functions
void retire (D deleter={}, hazptr_domain< Atom > &domain=default_hazptr_domain< Atom >())
void retire (hazptr_domain< Atom > &domain)
Public Member Functions inherited from folly::hazptr_obj< Atom >
hazptr_obj () noexcept
hazptr_obj (const hazptr_obj< Atom > &) noexcept
hazptr_obj (hazptr_obj< Atom > &&) noexcept
hazptr_obj< Atom > & operator= (const hazptr_obj< Atom > &) noexcept
hazptr_obj< Atom > & operator= (hazptr_obj< Atom > &&) noexcept
Public Member Functions inherited from folly::hazptr_deleter< T, D >
void set_deleter (D d={})
void delete_obj (T *p)
Private Member Functions
void pre_retire (D deleter)
void set_reclaim ()
Detailed Description
template<typename T, template< typename > class Atom, typename D>
class folly::hazptr_obj_base< T, Atom, D >
hazptr_obj_base
hazptr_obj_base
Base template for objects protected by hazard pointers.
Definition at line 66 of file Hazptr-fwd.h.
Member Function Documentation
template<typename T, template< typename > class Atom, typename D> void folly::hazptr_obj_base< T, Atom, D >::pre_retire (D deleter) inline private
Definition at line 242 of file HazptrObj.h.
{
     this->pre_retire_check(); // defined in hazptr_obj
     this->set_deleter(std::move(deleter));
   }
template<typename T, template< typename > class Atom, typename D> void folly::hazptr_obj_base< T, Atom, D >::retire (D deleter = {}, hazptr_domain< Atom > & domain = default_hazptr_domain<Atom>()) inline
Definition at line 229 of file HazptrObj.h.
Referenced by basic_objects_test(), folly::HazptrWideCAS< T, Atom >::cas(), cleanup_test(), folly::detail::ConcurrentHashMapSegment< KeyType, ValueType, ShardBits, HashFn, KeyEqual, Allocator, Atom, Mutex >::clear(), folly::RelaxedConcurrentPriorityQueue< T, MayBlock, SupportsSize, PopBatch, ListTargetSize, Mutex, Atom >::moundPopMany(), folly::HazptrLockFreeLIFO< T, Atom >::pop(), TEST(), folly::RelaxedConcurrentPriorityQueue< T, MayBlock, SupportsSize, PopBatch, ListTargetSize, Mutex, Atom >::tryPopFromSharedBuffer(), and folly::HazptrLockFreeLIFO< T, Atom >::~HazptrLockFreeLIFO().
                   {},
       hazptr_domain<Atom>& domain = default_hazptr_domain<Atom>()) {
     pre_retire(std::move(deleter));
     set_reclaim();
     this->push_to_retired(domain); // defined in hazptr_obj
   }
template<typename T, template< typename > class Atom, typename D> void folly::hazptr_obj_base< T, Atom, D >::retire (hazptr_domain< Atom > & domain) inline
Definition at line 237 of file HazptrObj.h.
{
     retire({}, domain);
   }
template<typename T, template< typename > class Atom, typename D> void folly::hazptr_obj_base< T, Atom, D >::set_reclaim () inline private
Definition at line 247 of file HazptrObj.h.
                      {
     this->reclaim_ = [](hazptr_obj<Atom>* p, hazptr_obj_list<Atom>&) {
       auto hobp = static_cast<hazptr_obj_base<T, Atom, D>*>(p);
       auto obj = static_cast<T*>(hobp);
       hobp->delete_obj(obj);
     };
   }
The documentation for this class was generated from the following files:
proxygen/folly/folly/synchronization/Hazptr-fwd.h
proxygen/folly/folly/synchronization/HazptrObj.h