proxygen: folly::ZeroCopyTestAsyncSocket::Callback Class Reference
folly::ZeroCopyTestAsyncSocket::Callback Class Reference
Public Member Functions
Callback (ZeroCopyTestAsyncSocket *parent)
void connectSuccess () noexceptoverride
void connectErr (const folly::AsyncSocketException &ex) noexceptoverride
void getReadBuffer (void **bufReturn, size_t *lenReturn) override
void readDataAvailable (size_t len) noexceptoverride
void readEOF () noexceptoverride
void readErr (const folly::AsyncSocketException &ex) noexceptoverride
Public Member Functions inherited from folly::AsyncSocket::ConnectCallback
virtual ~ConnectCallback ()=default
Private Attributes
ZeroCopyTestAsyncSocket * parent_ {nullptr}
Detailed Description
Definition at line 96 of file ZeroCopy.h.
Constructor & Destructor Documentation
folly::ZeroCopyTestAsyncSocket::Callback::Callback (ZeroCopyTestAsyncSocket * parent) inline explicit
Definition at line 99 of file ZeroCopy.h.
 : parent_(parent) {}
Member Function Documentation
void folly::ZeroCopyTestAsyncSocket::Callback::connectErr (const folly::AsyncSocketException & ex) inline override virtual noexcept
connectErr() will be invoked if the connection attempt fails.
Parameters
ex An exception describing the error that occurred.
Implements folly::AsyncSocket::ConnectCallback.
Definition at line 106 of file ZeroCopy.h.
References folly::ZeroCopyTestAsyncSocket::onDataFinish(), and parent_.
{
       LOG(ERROR) << "Connect error: " << ex.what();
       parent_->onDataFinish(folly::exception_wrapper(ex));
     }
void folly::ZeroCopyTestAsyncSocket::Callback::connectSuccess () inline override virtual noexcept
connectSuccess() will be invoked when the connection has been successfully established.
Implements folly::AsyncSocket::ConnectCallback.
Definition at line 101 of file ZeroCopy.h.
References folly::ZeroCopyTestAsyncSocket::onConnected(), parent_, and folly::ZeroCopyTestAsyncSocket::sock_.
{
       parent_->sock_->setReadCB(this);
       parent_->onConnected();
     }
void folly::ZeroCopyTestAsyncSocket::Callback::getReadBuffer (void ** bufReturn, size_t * lenReturn) inline override
Definition at line 111 of file ZeroCopy.h.
References folly::ZeroCopyTestAsyncSocket::getReadBuffer(), and parent_.
{
       parent_->getReadBuffer(bufReturn, lenReturn);
     }
void folly::ZeroCopyTestAsyncSocket::Callback::readDataAvailable (size_t len) inline override noexcept
Definition at line 115 of file ZeroCopy.h.
References parent_, and folly::ZeroCopyTestAsyncSocket::readDataAvailable().
{
       parent_->readDataAvailable(len);
     }
void folly::ZeroCopyTestAsyncSocket::Callback::readEOF () inline override noexcept
Definition at line 119 of file ZeroCopy.h.
References folly::ZeroCopyTestAsyncSocket::onDataFinish(), and parent_.
{
       parent_->onDataFinish(folly::exception_wrapper());
     }
void folly::ZeroCopyTestAsyncSocket::Callback::readErr (const folly::AsyncSocketException & ex) inline override noexcept
Definition at line 123 of file ZeroCopy.h.
References folly::ZeroCopyTestAsyncSocket::onDataFinish(), and parent_.
{
       parent_->onDataFinish(folly::exception_wrapper(ex));
     }
Member Data Documentation
ZeroCopyTestAsyncSocket* folly::ZeroCopyTestAsyncSocket::Callback::parent_ {nullptr} private
Definition at line 128 of file ZeroCopy.h.
Referenced by connectErr(), connectSuccess(), getReadBuffer(), readDataAvailable(), readEOF(), and readErr().
The documentation for this class was generated from the following file:
proxygen/folly/folly/io/async/test/ZeroCopy.h