proxygen: testing::internal::KeyMatcher< M > Class Template Reference
testing::internal::KeyMatcher< M > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
KeyMatcher (M m)
template<typename PairType >
operator Matcher< PairType > () const
KeyMatcher (M m)
template<typename PairType >
operator Matcher< PairType > () const
KeyMatcher (M m)
template<typename PairType >
operator Matcher< PairType > () const
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (KeyMatcher)
GTEST_DISALLOW_ASSIGN_ (KeyMatcher)
GTEST_DISALLOW_ASSIGN_ (KeyMatcher)
Private Attributes
const M matcher_for_key_
Detailed Description
template<typename M>
class testing::internal::KeyMatcher< M >
Definition at line 2983 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename M > testing::internal::KeyMatcher< M >::KeyMatcher (M m) inline explicit
Definition at line 2985 of file gmock-matchers.h.
 : matcher_for_key_(m) {}
template<typename M > testing::internal::KeyMatcher< M >::KeyMatcher (M m) inline explicit
Definition at line 2985 of file gmock-matchers.h.
 : matcher_for_key_(m) {}
template<typename M > testing::internal::KeyMatcher< M >::KeyMatcher (M m) inline explicit
Definition at line 2985 of file gmock-matchers.h.
 : matcher_for_key_(m) {}
Member Function Documentation
template<typename M > testing::internal::KeyMatcher< M >::GTEST_DISALLOW_ASSIGN_ (KeyMatcher< M >) private
template<typename M > testing::internal::KeyMatcher< M >::GTEST_DISALLOW_ASSIGN_ (KeyMatcher< M >) private
template<typename M > testing::internal::KeyMatcher< M >::GTEST_DISALLOW_ASSIGN_ (KeyMatcher< M >) private
template<typename M > template<typename PairType > testing::internal::KeyMatcher< M >::operator Matcher< PairType > () const inline
Definition at line 2988 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(new KeyMatcherImpl<PairType>(matcher_for_key_));
   }
template<typename M > template<typename PairType > testing::internal::KeyMatcher< M >::operator Matcher< PairType > () const inline
Definition at line 2988 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, GTEST_REMOVE_REFERENCE_AND_CONST_, M, and testing::MakeMatcher().
{
     return MakeMatcher(new KeyMatcherImpl<PairType>(matcher_for_key_));
   }
template<typename M > template<typename PairType > testing::internal::KeyMatcher< M >::operator Matcher< PairType > () const inline
Definition at line 2988 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, GTEST_REMOVE_REFERENCE_AND_CONST_, M, and testing::MakeMatcher().
{
     return MakeMatcher(new KeyMatcherImpl<PairType>(matcher_for_key_));
   }
Member Data Documentation
template<typename M > const M testing::internal::KeyMatcher< M >::matcher_for_key_ private
Definition at line 2993 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h