proxygen: testing::gmock_matchers_test::IntValue Class Reference
testing::gmock_matchers_test::IntValue Class Reference
Public Member Functions
IntValue (int a_value)
int value () const
IntValue (int a_value)
int value () const
IntValue (int a_value)
int value () const
Private Attributes
int value_
Detailed Description
Definition at line 537 of file gmock-matchers_test.cc.
Constructor & Destructor Documentation
testing::gmock_matchers_test::IntValue::IntValue (int a_value) inline explicit
Definition at line 541 of file gmock-matchers_test.cc.
 : value_(a_value) {}
testing::gmock_matchers_test::IntValue::IntValue (int a_value) inline explicit
Definition at line 541 of file gmock-matchers_test.cc.
 : value_(a_value) {}
testing::gmock_matchers_test::IntValue::IntValue (int a_value) inline explicit
Definition at line 541 of file gmock-matchers_test.cc.
 : value_(a_value) {}
Member Function Documentation
int testing::gmock_matchers_test::IntValue::value () const inline
Definition at line 543 of file gmock-matchers_test.cc.
Referenced by testing::gmock_matchers_test::IsPositiveIntValue(), and value().
 { return value_; }
int testing::gmock_matchers_test::IntValue::value () const inline
Definition at line 543 of file gmock-matchers_test.cc.
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, testing::gmock_matchers_test::IsPositiveIntValue(), testing::internal::MatcherBase< T >::Matches(), testing::internal::TEST(), testing::Truly(), and value().
 { return value_; }
int testing::gmock_matchers_test::IntValue::value () const inline
Definition at line 543 of file gmock-matchers_test.cc.
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, testing::gmock_matchers_test::IsPositiveIntValue(), testing::internal::MatcherBase< T >::Matches(), testing::internal::TEST(), testing::Truly(), and value().
 { return value_; }
Member Data Documentation
int testing::gmock_matchers_test::IntValue::value_ private
Definition at line 545 of file gmock-matchers_test.cc.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-matchers_test.cc