proxygen: folly::detail::Sleeper Class Reference
folly::detail::Sleeper Class Reference
#include <Sleeper.h>
Public Member Functions
Sleeper () noexcept
void wait () noexcept
Static Public Member Functions
static void sleep () noexcept
Private Attributes
uint32_t spinCount
Static Private Attributes
static const uint32_t kMaxActiveSpin = 4000
Detailed Description
Definition at line 39 of file Sleeper.h.
Constructor & Destructor Documentation
folly::detail::Sleeper::Sleeper () inline noexcept
Definition at line 45 of file Sleeper.h.
 : spinCount(0) {}
Member Function Documentation
static void folly::detail::Sleeper::sleep () inline static noexcept
Definition at line 47 of file Sleeper.h.
Referenced by folly::detail::distributed_mutex::spin(), and wait().
{
     /*
      * Always sleep 0.5ms, assuming this will make the kernel put
      * us down for whatever its minimum timer resolution is (in
      * linux this varies by kernel version from 1ms to 10ms).
      */
     struct timespec ts = {0, 500000};
     nanosleep(&ts, nullptr);
   }
void folly::detail::Sleeper::wait () inline noexcept
Definition at line 57 of file Sleeper.h.
References folly::asm_volatile_pause(), sleep(), and spinCount.
Referenced by folly::MicroSpinLock::lock(), and folly::PicoSpinLock< uintptr_t >::lock().
{
     if (spinCount < kMaxActiveSpin) {
       ++spinCount;
       asm_volatile_pause();
     } else {
       sleep();
     }
   }
Member Data Documentation
const uint32_t folly::detail::Sleeper::kMaxActiveSpin = 4000 static private
Definition at line 40 of file Sleeper.h.
uint32_t folly::detail::Sleeper::spinCount private
Definition at line 42 of file Sleeper.h.
Referenced by wait().
The documentation for this class was generated from the following file:
proxygen/folly/folly/synchronization/detail/Sleeper.h