proxygen: folly::RWSpinLock::ReadHolder Class Reference
folly::RWSpinLock::ReadHolder Class Reference
#include <RWSpinLock.h>
Public Member Functions
ReadHolder (RWSpinLock *lock)
ReadHolder (RWSpinLock &lock)
ReadHolder (ReadHolder &&other) noexcept
ReadHolder (UpgradedHolder &&upgraded)
ReadHolder (WriteHolder &&writer)
ReadHolder & operator= (ReadHolder &&other)
ReadHolder (const ReadHolder &other)=delete
ReadHolder & operator= (const ReadHolder &other)=delete
~ReadHolder ()
void reset (RWSpinLock *lock=nullptr)
void swap (ReadHolder *other)
Private Attributes
RWSpinLock * lock_
Friends
class UpgradedHolder
class WriteHolder
Detailed Description
Definition at line 314 of file RWSpinLock.h.
Constructor & Destructor Documentation
folly::RWSpinLock::ReadHolder::ReadHolder (RWSpinLock * lock) inline explicit
Definition at line 316 of file RWSpinLock.h.
References lock_, and folly::RWSpinLock::lock_shared().
Referenced by operator=().
                                           : lock_(lock) {
       if (lock_) {
         lock_->lock_shared();
       }
     }
folly::RWSpinLock::ReadHolder::ReadHolder (RWSpinLock & lock) inline explicit
Definition at line 322 of file RWSpinLock.h.
References lock_, and folly::RWSpinLock::lock_shared().
                                           : lock_(&lock) {
       lock_->lock_shared();
     }
folly::RWSpinLock::ReadHolder::ReadHolder (ReadHolder && other) inline noexcept
Definition at line 326 of file RWSpinLock.h.
                                             : lock_(other.lock_) {
       other.lock_ = nullptr;
     }
folly::RWSpinLock::ReadHolder::ReadHolder (UpgradedHolder && upgraded) inline explicit
Definition at line 331 of file RWSpinLock.h.
References lock_, and folly::RWSpinLock::unlock_upgrade_and_lock_shared().
                                                    : lock_(upgraded.lock_) {
       upgraded.lock_ = nullptr;
       if (lock_) {
         lock_->unlock_upgrade_and_lock_shared();
       }
     }
folly::RWSpinLock::ReadHolder::ReadHolder (WriteHolder && writer) inline explicit
Definition at line 338 of file RWSpinLock.h.
References lock_, and folly::RWSpinLock::unlock_and_lock_shared().
                                               : lock_(writer.lock_) {
       writer.lock_ = nullptr;
       if (lock_) {
         lock_->unlock_and_lock_shared();
       }
     }
folly::RWSpinLock::ReadHolder::ReadHolder (const ReadHolder & other) delete
folly::RWSpinLock::ReadHolder::~ReadHolder () inline
Definition at line 354 of file RWSpinLock.h.
References lock_, and folly::RWSpinLock::unlock_shared().
                   {
       if (lock_) {
         lock_->unlock_shared();
       }
     }
Member Function Documentation
ReadHolder& folly::RWSpinLock::ReadHolder::operator= (ReadHolder && other) inline
Definition at line 345 of file RWSpinLock.h.
References lock_, ReadHolder(), swap(), and folly::f14::swap().
Referenced by folly::RWSpinLock::UpgradedHolder::operator=(), and folly::RWSpinLock::WriteHolder::operator=().
{
       using std::swap;
       swap(lock_, other.lock_);
       return *this;
     }
ReadHolder& folly::RWSpinLock::ReadHolder::operator= (const ReadHolder & other) delete
void folly::RWSpinLock::ReadHolder::reset (RWSpinLock * lock = nullptr) inline
Definition at line 360 of file RWSpinLock.h.
References folly::RWSpinLock::lock(), lock_, folly::RWSpinLock::lock_shared(), and folly::RWSpinLock::unlock_shared().
{
       if (lock == lock_) {
         return;
       }
       if (lock_) {
         lock_->unlock_shared();
       }
       lock_ = lock;
       if (lock_) {
         lock_->lock_shared();
       }
     }
void folly::RWSpinLock::ReadHolder::swap (ReadHolder * other) inline
Definition at line 373 of file RWSpinLock.h.
References lock_, and folly::f14::swap().
Referenced by operator=(), folly::RWSpinLock::UpgradedHolder::operator=(), folly::RWSpinLock::WriteHolder::operator=(), folly::RWSpinLock::UpgradedHolder::swap(), and folly::RWSpinLock::WriteHolder::swap().
{
       std::swap(lock_, other->lock_);
     }
Friends And Related Function Documentation
friend class UpgradedHolder friend
Definition at line 378 of file RWSpinLock.h.
Referenced by folly::RWSpinLock::UpgradedHolder::operator=().
friend class WriteHolder friend
Definition at line 379 of file RWSpinLock.h.
Referenced by folly::RWSpinLock::WriteHolder::operator=().
Member Data Documentation
RWSpinLock* folly::RWSpinLock::ReadHolder::lock_ private
Definition at line 380 of file RWSpinLock.h.
Referenced by operator=(), folly::RWSpinLock::UpgradedHolder::operator=(), folly::RWSpinLock::WriteHolder::operator=(), ReadHolder(), reset(), folly::RWSpinLock::UpgradedHolder::reset(), folly::RWSpinLock::WriteHolder::reset(), swap(), folly::RWSpinLock::UpgradedHolder::swap(), folly::RWSpinLock::WriteHolder::swap(), folly::RWSpinLock::UpgradedHolder::UpgradedHolder(), folly::RWSpinLock::WriteHolder::WriteHolder(), ~ReadHolder(), folly::RWSpinLock::UpgradedHolder::~UpgradedHolder(), and folly::RWSpinLock::WriteHolder::~WriteHolder().
The documentation for this class was generated from the following file:
proxygen/folly/folly/synchronization/RWSpinLock.h