proxygen: testing::internal::Mutex Class Reference
testing::internal::Mutex Class Reference
#include <gtest-port.h>
Public Member Functions
Mutex ()
void Lock ()
void Unlock ()
void AssertHeld () const
Mutex ()
void Lock ()
void Unlock ()
void AssertHeld () const
Mutex ()
void Lock ()
void Unlock ()
void AssertHeld () const
Detailed Description
Definition at line 2136 of file gtest-port.h.
Constructor & Destructor Documentation
testing::internal::Mutex::Mutex () inline
Definition at line 2138 of file gtest-port.h.
Referenced by testing::internal::GetThreadCount().
 {}
testing::internal::Mutex::Mutex () inline
Definition at line 2138 of file gtest-port.h.
 {}
testing::internal::Mutex::Mutex () inline
Definition at line 2138 of file gtest-port.h.
 {}
Member Function Documentation
void testing::internal::Mutex::AssertHeld () const inline
Definition at line 2141 of file gtest-port.h.
Referenced by testing::internal::GetThreadCount(), testing::internal::NoDefaultContructor::NoDefaultContructor(), and testing::internal::TEST().
 {}
void testing::internal::Mutex::AssertHeld () const inline
Definition at line 2141 of file gtest-port.h.
 {}
void testing::internal::Mutex::AssertHeld () const inline
Definition at line 2141 of file gtest-port.h.
 {}
void testing::internal::Mutex::Lock () inline
Definition at line 2139 of file gtest-port.h.
 {}
void testing::internal::Mutex::Lock () inline
Definition at line 2139 of file gtest-port.h.
 {}
void testing::internal::Mutex::Lock () inline
Definition at line 2139 of file gtest-port.h.
Referenced by testing::internal::GetThreadCount(), testing::internal::TEST(), and testing::internal::To::To().
 {}
void testing::internal::Mutex::Unlock () inline
Definition at line 2140 of file gtest-port.h.
Referenced by testing::internal::GetThreadCount(), testing::internal::TEST(), and testing::internal::To::To().
 {}
void testing::internal::Mutex::Unlock () inline
Definition at line 2140 of file gtest-port.h.
 {}
void testing::internal::Mutex::Unlock () inline
Definition at line 2140 of file gtest-port.h.
 {}
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h