proxygen: folly::ReadCallbackBase Class Reference
folly::ReadCallbackBase Class Reference
#include <AsyncSSLSocketTest.h>
Public Member Functions
ReadCallbackBase (WriteCallbackBase *wcb)
~ReadCallbackBase () override
void setSocket (const std::shared_ptr< AsyncSSLSocket > &socket)
void setState (StateEnum s)
void readErr (const AsyncSocketException &ex) noexceptoverride
void readEOF () noexceptoverride
Public Member Functions inherited from folly::AsyncReader::ReadCallback
virtual ~ReadCallback ()=default
virtual void getReadBuffer (void **bufReturn, size_t *lenReturn)=0
virtual void readDataAvailable (size_t len) noexcept=0
virtual bool isBufferMovable () noexcept
virtual size_t maxBufferSize () const
virtual void readBufferAvailable (std::unique_ptr< IOBuf >) noexcept
Public Attributes
std::shared_ptr< AsyncSSLSocket > socket_
WriteCallbackBase * wcb_
StateEnum state
Detailed Description
Definition at line 277 of file AsyncSSLSocketTest.h.
Constructor & Destructor Documentation
folly::ReadCallbackBase::ReadCallbackBase (WriteCallbackBase * wcb) inline explicit
Definition at line 279 of file AsyncSSLSocketTest.h.
       : wcb_(wcb), state(STATE_WAITING) {}
folly::ReadCallbackBase::~ReadCallbackBase () inline override
Definition at line 282 of file AsyncSSLSocketTest.h.
References EXPECT_EQ, and folly::STATE_SUCCEEDED.
{
     EXPECT_EQ(STATE_SUCCEEDED, state);
   }
Member Function Documentation
void folly::ReadCallbackBase::readEOF () inline override virtual noexcept
readEOF() will be invoked when the transport is closed.
The read callback will be automatically uninstalled immediately before readEOF() is invoked.
Implements folly::AsyncReader::ReadCallback.
Reimplemented in folly::EmptyReadCallback, and folly::ReadEOFCallback.
Definition at line 303 of file AsyncSSLSocketTest.h.
References folly::SendMsgParamsCallbackBase::socket_.
Referenced by folly::ReadEOFCallback::readEOF().
{
     std::cerr << "readEOF" << std::endl;
     socket_->close();
   }
void folly::ReadCallbackBase::readErr (const AsyncSocketException & ex) inline override virtual noexcept
readError() will be invoked if an error occurs reading from the transport.
The read callback will be automatically uninstalled immediately before readError() is invoked.
Parameters
ex An exception describing the error that occurred.
Implements folly::AsyncReader::ReadCallback.
Reimplemented in folly::EmptyReadCallback, folly::WriteErrorCallback, and folly::ReadErrorCallback.
Definition at line 297 of file AsyncSSLSocketTest.h.
References folly::SendMsgParamsCallbackBase::socket_, and folly::STATE_FAILED.
Referenced by folly::ReadErrorCallback::readErr().
{
     std::cerr << "readError " << ex.what() << std::endl;
     state = STATE_FAILED;
     socket_->close();
   }
void folly::ReadCallbackBase::setSocket (const std::shared_ptr< AsyncSSLSocket > & socket) inline
Definition at line 286 of file AsyncSSLSocketTest.h.
References folly::netops::socket(), and folly::SendMsgParamsCallbackBase::socket_.
Referenced by folly::TEST().
{
     socket_ = socket;
   }
void folly::ReadCallbackBase::setState (StateEnum s) inline
Definition at line 290 of file AsyncSSLSocketTest.h.
References s.
{
     state = s;
     if (wcb_) {
       wcb_->state = s;
     }
   }
Member Data Documentation
std::shared_ptr<AsyncSSLSocket> folly::ReadCallbackBase::socket_
Definition at line 309 of file AsyncSSLSocketTest.h.
StateEnum folly::ReadCallbackBase::state
Definition at line 311 of file AsyncSSLSocketTest.h.
Referenced by TEST(), folly::TEST(), and TEST_P().
WriteCallbackBase* folly::ReadCallbackBase::wcb_
Definition at line 310 of file AsyncSSLSocketTest.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/io/async/test/AsyncSSLSocketTest.h