proxygen: wangle::InboundHandlerContext< In > Class Template Reference
wangle::InboundHandlerContext< In > Class Template Reference abstract
#include <HandlerContext.h>
Public Member Functions
virtual ~InboundHandlerContext ()=default
virtual void fireRead (In msg)=0
virtual void fireReadEOF ()=0
virtual void fireReadException (folly::exception_wrapper e)=0
virtual void fireTransportActive ()=0
virtual void fireTransportInactive ()=0
virtual PipelineBase * getPipeline ()=0
virtual std::shared_ptr< PipelineBase > getPipelineShared ()=0
std::shared_ptr< folly::AsyncTransport > getTransport ()
Detailed Description
template<class In>
class wangle::InboundHandlerContext< In >
Definition at line 69 of file HandlerContext.h.
Constructor & Destructor Documentation
template<class In> virtual wangle::InboundHandlerContext< In >::~InboundHandlerContext () virtual default
Member Function Documentation
template<class In> virtual void wangle::InboundHandlerContext< In >::fireRead (In msg) pure virtual
Implemented in wangle::InboundContextImpl< H >.
Referenced by wangle::ByteToMessageDecoder< T >::read(), and TestHandlerPipeline::read().
template<class In> virtual void wangle::InboundHandlerContext< In >::fireReadEOF () pure virtual
Implemented in wangle::InboundContextImpl< H >.
Referenced by wangle::InboundHandler< folly::IOBufQueue &, M >::readEOF().
template<class In> virtual void wangle::InboundHandlerContext< In >::fireReadException (folly::exception_wrapper e) pure virtual
Implemented in wangle::InboundContextImpl< H >.
Referenced by wangle::InboundHandler< folly::IOBufQueue &, M >::readException().
template<class In> virtual void wangle::InboundHandlerContext< In >::fireTransportActive () pure virtual
Implemented in wangle::InboundContextImpl< H >.
Referenced by wangle::ByteToMessageDecoder< T >::transportActive(), and wangle::InboundHandler< folly::IOBufQueue &, M >::transportActive().
template<class In> virtual void wangle::InboundHandlerContext< In >::fireTransportInactive () pure virtual
Implemented in wangle::InboundContextImpl< H >.
Referenced by wangle::ByteToMessageDecoder< T >::transportInactive(), and wangle::InboundHandler< folly::IOBufQueue &, M >::transportInactive().
template<class In> virtual PipelineBase* wangle::InboundHandlerContext< In >::getPipeline () pure virtual
Implemented in wangle::InboundContextImpl< H >.
template<class In> virtual std::shared_ptr<PipelineBase> wangle::InboundHandlerContext< In >::getPipelineShared () pure virtual
Implemented in wangle::InboundContextImpl< H >.
template<class In> std::shared_ptr<folly::AsyncTransport> wangle::InboundHandlerContext< In >::getTransport () inline
Definition at line 81 of file HandlerContext.h.
{
     return getPipeline()->getTransport();
   }
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/channel/HandlerContext.h