proxygen: folly::SparseByteSet Class Reference
folly::SparseByteSet Class Reference
#include <SparseByteSet.h>
Public Member Functions
SparseByteSet ()
bool add (uint8_t i)
bool contains (uint8_t i) const
Static Public Attributes
static constexpr uint16_t kCapacity = 256
Private Attributes
uint16_t size_
uint8_t sparse_ [kCapacity]
uint8_t dense_ [kCapacity]
Detailed Description
Definition at line 48 of file SparseByteSet.h.
Constructor & Destructor Documentation
folly::SparseByteSet::SparseByteSet () inline
Definition at line 54 of file SparseByteSet.h.
 : size_(0) {}
Member Function Documentation
bool folly::SparseByteSet::add (uint8_t i) inline
Definition at line 61 of file SparseByteSet.h.
References contains(), dense_, i, size_, sparse_, and uint8_t.
Referenced by folly::detail::qfind_first_byte_of_byteset().
{
     bool r = !contains(i);
     if (r) {
       DCHECK_LT(size_, kCapacity);
       dense_[size_] = i;
       sparse_[i] = uint8_t(size_);
       size_++;
     }
     return r;
   }
bool folly::SparseByteSet::contains (uint8_t i) const inline
Definition at line 77 of file SparseByteSet.h.
References dense_, i, size_, and sparse_.
Referenced by add(), and folly::detail::qfind_first_byte_of_byteset().
{
     return sparse_[i] < size_ && dense_[sparse_[i]] == i;
   }
Member Data Documentation
uint8_t folly::SparseByteSet::dense_[kCapacity] private
Definition at line 85 of file SparseByteSet.h.
Referenced by add(), and contains().
constexpr uint16_t folly::SparseByteSet::kCapacity = 256 static
Definition at line 51 of file SparseByteSet.h.
uint16_t folly::SparseByteSet::size_ private
Definition at line 82 of file SparseByteSet.h.
Referenced by add(), and contains().
uint8_t folly::SparseByteSet::sparse_[kCapacity] private
Definition at line 84 of file SparseByteSet.h.
Referenced by add(), and contains().
The documentation for this class was generated from the following file:
proxygen/folly/folly/container/SparseByteSet.h