proxygen: wangle::PeekingAcceptorHandshakeHelper::PeekCallback Class Reference
wangle::PeekingAcceptorHandshakeHelper::PeekCallback Class Reference abstract
#include <PeekingAcceptorHandshakeHelper.h>
Public Member Functions
PeekCallback (size_t bytesRequired)
virtual ~PeekCallback ()=default
size_t getBytesRequired () const
virtual AcceptorHandshakeHelper::UniquePtr getHelper (const std::vector< uint8_t > &peekedBytes, const folly::SocketAddress &clientAddr, std::chrono::steady_clock::time_point acceptTime, TransportInfo &tinfo)=0
Private Attributes
const size_t bytesRequired_
Detailed Description
Definition at line 35 of file PeekingAcceptorHandshakeHelper.h.
Constructor & Destructor Documentation
wangle::PeekingAcceptorHandshakeHelper::PeekCallback::PeekCallback (size_t bytesRequired) inline explicit
Definition at line 37 of file PeekingAcceptorHandshakeHelper.h.
References ~PeekCallback().
                                                :
       bytesRequired_(bytesRequired) {}
virtual wangle::PeekingAcceptorHandshakeHelper::PeekCallback::~PeekCallback () virtual default
Referenced by PeekCallback().
Member Function Documentation
size_t wangle::PeekingAcceptorHandshakeHelper::PeekCallback::getBytesRequired () const inline
Definition at line 41 of file PeekingAcceptorHandshakeHelper.h.
References bytesRequired_, and getHelper().
Referenced by wangle::SecurityProtocolContextManager::addPeeker().
{
       return bytesRequired_;
     }
virtual AcceptorHandshakeHelper::UniquePtr wangle::PeekingAcceptorHandshakeHelper::PeekCallback::getHelper (const std::vector< uint8_t > & peekedBytes, const folly::SocketAddress & clientAddr, std::chrono::steady_clock::time_point acceptTime, TransportInfo & tinfo) pure virtual
Implemented in wangle::DefaultToFizzPeekingCallback, wangle::DefaultToSSLPeekingCallback, MockPeekingCallback, wangle::TLSPlaintextPeekingCallback, and LengthPeeker< N >.
Referenced by getBytesRequired().
Member Data Documentation
const size_t wangle::PeekingAcceptorHandshakeHelper::PeekCallback::bytesRequired_ private
Definition at line 52 of file PeekingAcceptorHandshakeHelper.h.
Referenced by getBytesRequired().
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/acceptor/PeekingAcceptorHandshakeHelper.h