proxygen: upload.ClientLoginError Class Reference
upload.ClientLoginError Class Reference
Public Member Functions
def __init__ (self, url, code, msg, headers, args)
def __init__ (self, url, code, msg, headers, args)
def __init__ (self, url, code, msg, headers, args)
def __init__ (self, url, code, msg, headers, args)
def __init__ (self, url, code, msg, headers, args)
def __init__ (self, url, code, msg, headers, args)
Public Attributes
args
reason
Detailed Description
Raised to indicate there was an error authenticating with ClientLogin.
Definition at line 115 of file upload.py.
Constructor & Destructor Documentation
def upload.ClientLoginError.__init__ (self, url, code, msg, headers, args)
Definition at line 118 of file upload.py.
Referenced by upload.ClientLoginError.__init__().
   def __init__(self, url, code, msg, headers, args):
     urllib2.HTTPError.__init__(self, url, code, msg, headers, None)
     self.args = args
     self.reason = args["Error"]
def upload.ClientLoginError.__init__ (self, url, code, msg, headers, args)
Definition at line 118 of file upload.py.
References upload.ClientLoginError.__init__(), upload.ClientLoginError.args, object, and upload.ClientLoginError.reason.
   def __init__(self, url, code, msg, headers, args):
     urllib2.HTTPError.__init__(self, url, code, msg, headers, None)
     self.args = args
     self.reason = args["Error"]
def upload.ClientLoginError.__init__ (self, url, code, msg, headers, args)
Definition at line 118 of file upload.py.
References upload.ClientLoginError.__init__(), upload.ClientLoginError.args, object, and upload.ClientLoginError.reason.
   def __init__(self, url, code, msg, headers, args):
     urllib2.HTTPError.__init__(self, url, code, msg, headers, None)
     self.args = args
     self.reason = args["Error"]
def upload.ClientLoginError.__init__ (self, url, code, msg, headers, args)
Definition at line 118 of file upload.py.
References upload.ClientLoginError.__init__(), upload.ClientLoginError.args, object, and upload.ClientLoginError.reason.
   def __init__(self, url, code, msg, headers, args):
     urllib2.HTTPError.__init__(self, url, code, msg, headers, None)
     self.args = args
     self.reason = args["Error"]
def upload.ClientLoginError.__init__ (self, url, code, msg, headers, args)
Definition at line 118 of file upload.py.
References upload.ClientLoginError.__init__(), upload.ClientLoginError.args, object, and upload.ClientLoginError.reason.
   def __init__(self, url, code, msg, headers, args):
     urllib2.HTTPError.__init__(self, url, code, msg, headers, None)
     self.args = args
     self.reason = args["Error"]
def upload.ClientLoginError.__init__ (self, url, code, msg, headers, args)
Definition at line 118 of file upload.py.
References upload.ClientLoginError.__init__(), upload.ClientLoginError.args, object, and upload.ClientLoginError.reason.
   def __init__(self, url, code, msg, headers, args):
     urllib2.HTTPError.__init__(self, url, code, msg, headers, None)
     self.args = args
     self.reason = args["Error"]
Member Data Documentation
upload.ClientLoginError.args
Definition at line 120 of file upload.py.
Referenced by upload.ClientLoginError.__init__().
upload.ClientLoginError.reason
Definition at line 121 of file upload.py.
Referenced by upload.ClientLoginError.__init__().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/scripts/upload.py