proxygen: folly::AtomicIntrusiveLinkedList< T, HookMember > Class Template Reference
folly::AtomicIntrusiveLinkedList< T, HookMember > Class Template Reference
#include <AtomicIntrusiveLinkedList.h>
Public Member Functions
AtomicIntrusiveLinkedList ()
AtomicIntrusiveLinkedList (const AtomicIntrusiveLinkedList &)=delete
AtomicIntrusiveLinkedList & operator= (const AtomicIntrusiveLinkedList &)=delete
AtomicIntrusiveLinkedList (AtomicIntrusiveLinkedList &&other) noexcept
AtomicIntrusiveLinkedList & operator= (AtomicIntrusiveLinkedList &&other) noexcept
~AtomicIntrusiveLinkedList ()
bool empty () const
bool insertHead (T *t)
template<typename F >
bool sweepOnce (F &&func)
template<typename F >
void sweep (F &&func)
template<typename F >
void reverseSweep (F &&func)
Private Member Functions
template<typename F >
void unlinkAll (T *head, F &&func)
Static Private Member Functions
static T *& next (T *t)
static T * reverse (T *head)
Private Attributes
std::atomic< T * > head_ {nullptr}
Detailed Description
template<class T, AtomicIntrusiveLinkedListHook< T > T::* HookMember>
class folly::AtomicIntrusiveLinkedList< T, HookMember >
Definition at line 44 of file AtomicIntrusiveLinkedList.h.
Constructor & Destructor Documentation
template<class T, AtomicIntrusiveLinkedListHook< T > T::* HookMember> folly::AtomicIntrusiveLinkedList< T, HookMember >::AtomicIntrusiveLinkedList () inline
Definition at line 46 of file AtomicIntrusiveLinkedList.h.
 {}
template<class T, AtomicIntrusiveLinkedListHook< T > T::* HookMember> folly::AtomicIntrusiveLinkedList< T, HookMember >::AtomicIntrusiveLinkedList (const AtomicIntrusiveLinkedList< T, HookMember > &) delete
template<class T, AtomicIntrusiveLinkedListHook< T > T::* HookMember> folly::AtomicIntrusiveLinkedList< T, HookMember >::AtomicIntrusiveLinkedList (AtomicIntrusiveLinkedList< T, HookMember > && other) inline noexcept
Definition at line 50 of file AtomicIntrusiveLinkedList.h.
{
     auto tmp = other.head_.load();
     other.head_ = head_.load();
     head_ = tmp;
   }
template<class T, AtomicIntrusiveLinkedListHook< T > T::* HookMember> folly::AtomicIntrusiveLinkedList< T, HookMember >::~AtomicIntrusiveLinkedList () inline
Note: list must be empty on destruction.
Definition at line 67 of file AtomicIntrusiveLinkedList.h.
{
     assert(empty());
   }
Member Function Documentation
template<class T, AtomicIntrusiveLinkedListHook< T > T::* HookMember> bool folly::AtomicIntrusiveLinkedList< T, HookMember >::empty () const inline
Definition at line 71 of file AtomicIntrusiveLinkedList.h.
Referenced by TEST().
                      {
     return head_.load() == nullptr;
   }
template<class T, AtomicIntrusiveLinkedListHook< T > T::* HookMember> bool folly::AtomicIntrusiveLinkedList< T, HookMember >::insertHead (T * t) inline
Atomically insert t at the head of the list.
Returns
True if the inserted element is the only one in the list after the call.
Definition at line 80 of file AtomicIntrusiveLinkedList.h.
Referenced by TEST().
{
     assert(next(t) == nullptr);
     auto oldHead = head_.load(std::memory_order_relaxed);
     do {
       next(t) = oldHead;
       /* oldHead is updated by the call below.
          NOTE: we don't use next(t) instead of oldHead directly due to
          compiler bugs (GCC prior to 4.8.3 (bug 60272), clang (bug 18899),
          MSVC (bug 819819); source:
          http://en.cppreference.com/w/cpp/atomic/atomic/compare_exchange */
     } while (!head_.compare_exchange_weak(
         oldHead, t, std::memory_order_release, std::memory_order_relaxed));
     return oldHead == nullptr;
   }
template<class T, AtomicIntrusiveLinkedListHook< T > T::* HookMember> static T*& folly::AtomicIntrusiveLinkedList< T, HookMember >::next (T * t) inline static private
Definition at line 148 of file AtomicIntrusiveLinkedList.h.
{
     return (t->*HookMember).next;
   }
template<class T, AtomicIntrusiveLinkedListHook< T > T::* HookMember> AtomicIntrusiveLinkedList& folly::AtomicIntrusiveLinkedList< T, HookMember >::operator= (const AtomicIntrusiveLinkedList< T, HookMember > &) delete
template<class T, AtomicIntrusiveLinkedListHook< T > T::* HookMember> AtomicIntrusiveLinkedList& folly::AtomicIntrusiveLinkedList< T, HookMember >::operator= (AtomicIntrusiveLinkedList< T, HookMember > && other) inline noexcept
Definition at line 55 of file AtomicIntrusiveLinkedList.h.
{
     auto tmp = other.head_.load();
     other.head_ = head_.load();
     head_ = tmp;
     return *this;
   }
template<class T, AtomicIntrusiveLinkedListHook< T > T::* HookMember> static T* folly::AtomicIntrusiveLinkedList< T, HookMember >::reverse (T * head) inline static private
Definition at line 154 of file AtomicIntrusiveLinkedList.h.
{
     T* rhead = nullptr;
     while (head != nullptr) {
       auto t = head;
       head = next(t);
       next(t) = rhead;
       rhead = t;
     }
     return rhead;
   }
template<class T, AtomicIntrusiveLinkedListHook< T > T::* HookMember> template<typename F > void folly::AtomicIntrusiveLinkedList< T, HookMember >::reverseSweep (F && func) inline
Similar to sweep() but calls func() on elements in LIFO order.
func() is called for all elements in the list at the moment reverseSweep() is called. Unlike sweep() it does not loop to ensure the list is empty at some point after the last invocation. This way callers can reason about the ordering: elements inserted since the last call to reverseSweep() will be provided in LIFO order.
Example: if elements are inserted in the order 1-2-3, the callback is invoked 3-2-1. If the callback moves elements onto a stack, popping off the stack will produce the original insertion order 1-2-3.
Definition at line 138 of file AtomicIntrusiveLinkedList.h.
Referenced by TEST().
{
     // We don't loop like sweep() does because the overall order of callbacks
     // would be strand-wise LIFO which is meaningless to callers.
     auto head = head_.exchange(nullptr);
     unlinkAll(head, std::forward<F>(func));
   }
template<class T, AtomicIntrusiveLinkedListHook< T > T::* HookMember> template<typename F > void folly::AtomicIntrusiveLinkedList< T, HookMember >::sweep (F && func) inline
Repeatedly replaces the head with nullptr, and calls func() on the removed elements in the order from tail to head. Stops when the list is empty.
Definition at line 119 of file AtomicIntrusiveLinkedList.h.
Referenced by TEST().
{
     while (sweepOnce(func)) {
     }
   }
template<class T, AtomicIntrusiveLinkedListHook< T > T::* HookMember> template<typename F > bool folly::AtomicIntrusiveLinkedList< T, HookMember >::sweepOnce (F && func) inline
Replaces the head with nullptr, and calls func() on the removed elements in the order from tail to head. Returns false if the list was empty.
Definition at line 104 of file AtomicIntrusiveLinkedList.h.
{
     if (auto head = head_.exchange(nullptr)) {
       auto rhead = reverse(head);
       unlinkAll(rhead, std::forward<F>(func));
       return true;
     }
     return false;
   }
template<class T, AtomicIntrusiveLinkedListHook< T > T::* HookMember> template<typename F > void folly::AtomicIntrusiveLinkedList< T, HookMember >::unlinkAll (T * head, F && func) inline private
Definition at line 168 of file AtomicIntrusiveLinkedList.h.
{
     while (head != nullptr) {
       auto t = head;
       head = next(t);
       next(t) = nullptr;
       func(t);
     }
   }
Member Data Documentation
template<class T, AtomicIntrusiveLinkedListHook< T > T::* HookMember> std::atomic<T*> folly::AtomicIntrusiveLinkedList< T, HookMember >::head_ {nullptr} private
Definition at line 146 of file AtomicIntrusiveLinkedList.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/AtomicIntrusiveLinkedList.h