proxygen: cpp.ast.Friend Class Reference
cpp.ast.Friend Class Reference
Public Member Functions
def __init__ (self, start, end, expr, namespace)
def __init__ (self, start, end, expr, namespace)
def __init__ (self, start, end, expr, namespace)
Public Member Functions inherited from cpp.ast.Expr
def __init__ (self, start, end, expr)
def Requires (self, node)
def __str__ (self)
def __init__ (self, start, end, expr)
def Requires (self, node)
def __str__ (self)
def __init__ (self, start, end, expr)
def Requires (self, node)
def __str__ (self)
Public Member Functions inherited from cpp.ast.Node
def __init__ (self, start, end)
def IsDeclaration (self)
def IsDefinition (self)
def IsExportable (self)
def Requires (self, node)
def XXX__str__ (self)
def __repr__ (self)
def __init__ (self, start, end)
def IsDeclaration (self)
def IsDefinition (self)
def IsExportable (self)
def Requires (self, node)
def XXX__str__ (self)
def __repr__ (self)
def __init__ (self, start, end)
def IsDeclaration (self)
def IsDefinition (self)
def IsExportable (self)
def Requires (self, node)
def XXX__str__ (self)
def __repr__ (self)
Public Attributes
namespace
Public Attributes inherited from cpp.ast.Expr
expr
Public Attributes inherited from cpp.ast.Node
start
end
Detailed Description
Definition at line 198 of file ast.py.
Constructor & Destructor Documentation
def cpp.ast.Friend.__init__ (self, start, end, expr, namespace)
Definition at line 199 of file ast.py.
Referenced by cpp.ast.Friend.__init__().
     def __init__(self, start, end, expr, namespace):
         Expr.__init__(self, start, end, expr)
         self.namespace = namespace[:]
def cpp.ast.Friend.__init__ (self, start, end, expr, namespace)
Definition at line 199 of file ast.py.
References cpp.ast.Friend.__init__(), and cpp.ast.Friend.namespace.
     def __init__(self, start, end, expr, namespace):
         Expr.__init__(self, start, end, expr)
         self.namespace = namespace[:]
def cpp.ast.Friend.__init__ (self, start, end, expr, namespace)
Definition at line 199 of file ast.py.
References cpp.ast.Friend.__init__(), and cpp.ast.Friend.namespace.
     def __init__(self, start, end, expr, namespace):
         Expr.__init__(self, start, end, expr)
         self.namespace = namespace[:]
Member Data Documentation
cpp.ast.Friend.namespace
Definition at line 201 of file ast.py.
Referenced by cpp.ast.Friend.__init__(), cpp.ast._GenericDeclaration.__init__(), cpp.ast._GenericDeclaration._TypeStringHelper(), cpp.ast._GenericDeclaration.FullName(), and cpp.ast.Function.IsExportable().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/scripts/generator/cpp/ast.py