proxygen: folly::RecordIOReader::Iterator Class Reference
folly::RecordIOReader::Iterator Class Reference
#include <RecordIO-inl.h>
Private Member Functions
Iterator (ByteRange range, uint32_t fileId, off_t pos)
reference dereference () const
bool equal (const Iterator &other) const
void increment ()
void advanceToValid ()
Private Attributes
ByteRange range_
uint32_t fileId_
std::pair< ByteRange, off_t > recordAndPos_
Friends
class boost::iterator_core_access
class RecordIOReader
Detailed Description
Definition at line 27 of file RecordIO-inl.h.
Constructor & Destructor Documentation
folly::RecordIOReader::Iterator::Iterator (ByteRange range, uint32_t fileId, off_t pos) private
Definition at line 75 of file RecordIO.cpp.
References folly::Range< Iter >::advance(), advanceToValid(), folly::Range< Iter >::clear(), range_, recordAndPos_, and folly::Range< Iter >::size().
Referenced by folly::RecordIOReader::seek().
     : range_(range), fileId_(fileId), recordAndPos_(ByteRange(), 0) {
   if (size_t(pos) >= range_.size()) {
     // Note that this branch can execute if pos is negative as well.
     recordAndPos_.second = off_t(-1);
     range_.clear();
   } else {
     recordAndPos_.second = pos;
     range_.advance(size_t(pos));
     advanceToValid();
   }
 }
Member Function Documentation
void folly::RecordIOReader::Iterator::advanceToValid () private
Definition at line 88 of file RecordIO.cpp.
References folly::Range< Iter >::advance(), folly::Range< Iter >::begin(), folly::Range< Iter >::clear(), folly::Range< Iter >::data(), folly::Range< Iter >::empty(), fileId_, folly::hash::SpookyHashV2::Final(), folly::recordio_helpers::findRecord(), folly::hash::SpookyHashV2::Hash32(), folly::hash::SpookyHashV2::Hash64(), folly::recordio_helpers::headerSize(), folly::hash::SpookyHashV2::Init(), max, folly::range(), range_, folly::recordio_helpers::RecordInfo::record, recordAndPos_, folly::Range< Iter >::size(), uint32_t, uint64_t, and folly::hash::SpookyHashV2::Update().
Referenced by increment(), and Iterator().
{
   ByteRange record = findRecord(range_, fileId_).record;
   if (record.empty()) {
     recordAndPos_ = std::make_pair(ByteRange(), off_t(-1));
     range_.clear(); // at end
   } else {
     size_t skipped = size_t(record.begin() - range_.begin());
     DCHECK_GE(skipped, headerSize());
     skipped -= headerSize();
     range_.advance(skipped);
     recordAndPos_.first = record;
     recordAndPos_.second += off_t(skipped);
   }
 }
reference folly::RecordIOReader::Iterator::dereference () const inline private
Definition at line 37 of file RecordIO-inl.h.
References recordAndPos_.
{
     return recordAndPos_;
   }
bool folly::RecordIOReader::Iterator::equal (const Iterator & other) const inline private
Definition at line 40 of file RecordIO-inl.h.
References range_.
{
     return range_ == other.range_;
   }
void folly::RecordIOReader::Iterator::increment () inline private
Definition at line 43 of file RecordIO-inl.h.
References folly::Range< Iter >::advance(), advanceToValid(), folly::recordio_helpers::headerSize(), range_, recordAndPos_, and folly::gen::skip().
                    {
     size_t skip = recordio_helpers::headerSize() + recordAndPos_.first.size();
     recordAndPos_.second += off_t(skip);
     range_.advance(skip);
     advanceToValid();
   }
Friends And Related Function Documentation
friend class boost::iterator_core_access friend
Definition at line 31 of file RecordIO-inl.h.
friend class RecordIOReader friend
Definition at line 32 of file RecordIO-inl.h.
Member Data Documentation
uint32_t folly::RecordIOReader::Iterator::fileId_ private
Definition at line 52 of file RecordIO-inl.h.
Referenced by advanceToValid(), and folly::RecordIOReader::seek().
ByteRange folly::RecordIOReader::Iterator::range_ private
Definition at line 51 of file RecordIO-inl.h.
Referenced by advanceToValid(), equal(), increment(), and Iterator().
std::pair<ByteRange, off_t> folly::RecordIOReader::Iterator::recordAndPos_ private
Definition at line 54 of file RecordIO-inl.h.
Referenced by advanceToValid(), dereference(), increment(), and Iterator().
The documentation for this class was generated from the following files:
proxygen/folly/folly/io/RecordIO-inl.h
proxygen/folly/folly/io/RecordIO.cpp