proxygen: TelnetHandler Class Reference
TelnetHandler Class Reference
Public Member Functions
void read (Context *, std::string msg) override
void readException (Context *ctx, exception_wrapper e) override
void readEOF (Context *ctx) override
void read (Context *ctx, std::string msg) override
void transportActive (Context *ctx) override
Public Member Functions inherited from wangle::HandlerAdapter< std::string >
void read (Context *ctx, std::stringmsg) override
folly::Future< folly::Unit > write (Context *ctx, std::stringmsg) override
Public Member Functions inherited from wangle::Handler< std::string, std::string, std::string, std::string >
~Handler () override=default
virtual void transportInactive (Context *ctx)
virtual folly::Future< folly::Unit > writeException (Context *ctx, folly::exception_wrapper e)
virtual folly::Future< folly::Unit > close (Context *ctx)
Public Member Functions inherited from wangle::HandlerBase< HandlerContext< std::string, std::string > >
virtual ~HandlerBase ()=default
virtual void attachPipeline (HandlerContext< std::string, std::string > *)
virtual void detachPipeline (HandlerContext< std::string, std::string > *)
HandlerContext< std::string, std::string > * getContext ()
Additional Inherited Members
Public Types inherited from wangle::HandlerAdapter< std::string >
typedef Handler< std::string, std::string, std::string, std::string >::Context Context
Public Types inherited from wangle::Handler< std::string, std::string, std::string, std::string >
typedef std::string rin
typedef std::string rout
typedef std::string win
typedef std::string wout
typedef HandlerContext< std::string, std::string > Context
Static Public Attributes inherited from wangle::Handler< std::string, std::string, std::string, std::string >
static const HandlerDir dir
Detailed Description
Definition at line 36 of file TelnetClient.cpp.
Member Function Documentation
void TelnetHandler::read (Context * ctx, std::string msg) inline override virtual
Implements wangle::Handler< std::string, std::string, std::string, std::string >.
Definition at line 34 of file TelnetServer.cpp.
References folly::netops::close(), and fizz::detail::write().
{
     if (msg.empty()) {
       write(ctx, "Please type something.\r\n");
     } else if (msg == "bye") {
       write(ctx, "Have a fabulous day!\r\n").thenValue([ctx, this](auto&&) {
         close(ctx);
       });
     } else {
       write(ctx, "Did you say '" + msg + "'?\r\n");
     }
   }
void TelnetHandler::read (Context * , std::string msg) inline override virtual
Implements wangle::Handler< std::string, std::string, std::string, std::string >.
Definition at line 38 of file TelnetClient.cpp.
{
     std::cout << msg;
   }
void TelnetHandler::readEOF (Context * ctx) inline override virtual
Reimplemented from wangle::Handler< std::string, std::string, std::string, std::string >.
Definition at line 45 of file TelnetClient.cpp.
References folly::netops::close().
{
     std::cout << "EOF received :(" << std::endl;
     close(ctx);
   }
void TelnetHandler::readException (Context * ctx, exception_wrapper e) inline override virtual
Reimplemented from wangle::Handler< std::string, std::string, std::string, std::string >.
Definition at line 41 of file TelnetClient.cpp.
References folly::netops::close(), and folly::exceptionStr().
{
     std::cout << exceptionStr(e) << std::endl;
     close(ctx);
   }
void TelnetHandler::transportActive (Context * ctx) inline override virtual
Reimplemented from wangle::Handler< std::string, std::string, std::string, std::string >.
Definition at line 46 of file TelnetServer.cpp.
References folly::SocketAddress::describe(), wangle::HandlerContext< In, Out >::getTransport(), and fizz::detail::write().
{
     auto sock = ctx->getTransport();
     SocketAddress localAddress;
     sock->getLocalAddress(&localAddress);
     write(ctx, "Welcome to " + localAddress.describe() + "!\r\n");
     write(ctx, "Type 'bye' to disconnect.\r\n");
   }
The documentation for this class was generated from the following files:
proxygen/wangle/wangle/example/telnet/TelnetClient.cpp
proxygen/wangle/wangle/example/telnet/TelnetServer.cpp