proxygen: testing::gmock_matchers_test::AllArgsHelper Class Reference
testing::gmock_matchers_test::AllArgsHelper Class Reference
Public Member Functions
AllArgsHelper ()
MOCK_METHOD2 (Helper, int(char x, int y))
AllArgsHelper ()
MOCK_METHOD2 (Helper, int(char x, int y))
AllArgsHelper ()
MOCK_METHOD2 (Helper, int(char x, int y))
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (AllArgsHelper)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (AllArgsHelper)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (AllArgsHelper)
Detailed Description
Definition at line 2596 of file gmock-matchers_test.cc.
Constructor & Destructor Documentation
testing::gmock_matchers_test::AllArgsHelper::AllArgsHelper () inline
Definition at line 2598 of file gmock-matchers_test.cc.
References GTEST_DISALLOW_COPY_AND_ASSIGN_, and MOCK_METHOD2.
 {}
testing::gmock_matchers_test::AllArgsHelper::AllArgsHelper () inline
Definition at line 2598 of file gmock-matchers_test.cc.
References testing::_, testing::AllArgs(), testing::AllOf(), ASSERT_THAT, testing::EndsWith(), EXPECT_CALL, EXPECT_EQ, EXPECT_FATAL_FAILURE, EXPECT_NONFATAL_FAILURE, EXPECT_THAT, testing::Ge(), testing::Gt(), GTEST_DISALLOW_COPY_AND_ASSIGN_, testing::Le(), testing::Lt(), MOCK_METHOD2, testing::Not(), testing::gmock_matchers_test::OfType(), ON_CALL, testing::Ref(), testing::Return(), testing::StartsWith(), and testing::internal::TEST().
 {}
testing::gmock_matchers_test::AllArgsHelper::AllArgsHelper () inline
Definition at line 2598 of file gmock-matchers_test.cc.
References testing::_, testing::AllArgs(), testing::AllOf(), ASSERT_THAT, testing::EndsWith(), EXPECT_CALL, EXPECT_EQ, EXPECT_FATAL_FAILURE, EXPECT_NONFATAL_FAILURE, EXPECT_THAT, testing::Ge(), testing::Gt(), GTEST_DISALLOW_COPY_AND_ASSIGN_, testing::Le(), testing::Lt(), MOCK_METHOD2, testing::Not(), testing::gmock_matchers_test::OfType(), ON_CALL, testing::Ref(), testing::Return(), testing::StartsWith(), and testing::internal::TEST().
 {}
Member Function Documentation
testing::gmock_matchers_test::AllArgsHelper::GTEST_DISALLOW_COPY_AND_ASSIGN_ (AllArgsHelper) private
testing::gmock_matchers_test::AllArgsHelper::GTEST_DISALLOW_COPY_AND_ASSIGN_ (AllArgsHelper) private
testing::gmock_matchers_test::AllArgsHelper::GTEST_DISALLOW_COPY_AND_ASSIGN_ (AllArgsHelper) private
testing::gmock_matchers_test::AllArgsHelper::MOCK_METHOD2 (Helper , int(char x, int y))
testing::gmock_matchers_test::AllArgsHelper::MOCK_METHOD2 (Helper , int(char x, int y))
testing::gmock_matchers_test::AllArgsHelper::MOCK_METHOD2 (Helper , int(char x, int y))
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-matchers_test.cc