proxygen: folly::F14VectorMap< Key, Mapped, Hasher, KeyEqual, Alloc > Class Template Reference
folly::F14VectorMap< Key, Mapped, Hasher, KeyEqual, Alloc > Class Template Reference
#include <F14Map-fwd.h>
Public Member Functions
F14VectorMap ()=default
F14VectorMap & operator= (std::initializer_list< value_type > ilist)
Public Member Functions inherited from folly::f14::detail::F14BasicMap< Key, Mapped, Hasher, KeyEqual, Alloc >
F14BasicMap ()=default
std::size_t getAllocatedMemorySize () const
void visitAllocationClasses (V &&visitor) const
void visitContiguousRanges (V &&visitor) const
Private Types
using Super = f14::detail::F14BasicMap< Key, Mapped, Hasher, KeyEqual, Alloc >
Detailed Description
template<typename Key, typename Mapped, typename Hasher, typename KeyEqual, typename Alloc>
class folly::F14VectorMap< Key, Mapped, Hasher, KeyEqual, Alloc >
Definition at line 46 of file F14Map-fwd.h.
Member Typedef Documentation
template<typename Key, typename Mapped, typename Hasher, typename KeyEqual, typename Alloc> using folly::F14VectorMap< Key, Mapped, Hasher, KeyEqual, Alloc >::Super = f14::detail::F14BasicMap<Key, Mapped, Hasher, KeyEqual, Alloc> private
Definition at line 151 of file F14Map.h.
Constructor & Destructor Documentation
template<typename Key, typename Mapped, typename Hasher, typename KeyEqual, typename Alloc> folly::F14VectorMap< Key, Mapped, Hasher, KeyEqual, Alloc >::F14VectorMap () default
Member Function Documentation
template<typename Key, typename Mapped, typename Hasher, typename KeyEqual, typename Alloc> F14VectorMap& folly::F14VectorMap< Key, Mapped, Hasher, KeyEqual, Alloc >::operator= (std::initializer_list< value_type > ilist) inline
Definition at line 160 of file F14Map.h.
References a, testing::Args(), folly::assume(), b, folly::test::begin(), folly::padded::cbegin(), folly::padded::cend(), count, destroy(), folly::empty(), folly::test::end(), folly::eq, folly::f14::detail::F14BasicMap< K, M, H, E, A >::F14BasicMap(), folly::gen::first, FOLLY_ALWAYS_INLINE, FOLLY_SAFE_DCHECK, folly::f14::detail::F14BasicMap< K, M, H, E, A >::getAllocatedMemorySize(), folly::init(), gen_gtest_pred_impl::Iter(), testing::Key(), M, folly::gen::move, folly::pushmi::__adl::noexcept(), folly::f14::operator!=(), folly::f14::operator==(), ptr, folly::reserve, folly::detail::rhs, folly::size(), folly::f14::swap(), folly::T, uint32_t, value, folly::value(), testing::Value(), values(), folly::f14::detail::F14BasicMap< K, M, H, E, A >::visitAllocationClasses(), and folly::f14::detail::F14BasicMap< K, M, H, E, A >::visitContiguousRanges().
{
     Super::operator=(ilist);
     return *this;
   }
The documentation for this class was generated from the following files:
proxygen/folly/folly/container/F14Map-fwd.h
proxygen/folly/folly/container/F14Map.h