proxygen: testing::PolymorphicMatcher< Impl >::MonomorphicImpl< T > Class Template Reference
testing::PolymorphicMatcher< Impl >::MonomorphicImpl< T > Class Template Reference
Public Member Functions
MonomorphicImpl (const Impl &impl)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (T x, MatchResultListener *listener) const
MonomorphicImpl (const Impl &impl)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (T x, MatchResultListener *listener) const
MonomorphicImpl (const Impl &impl)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (T x, MatchResultListener *listener) const
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
virtual ~MatcherDescriberInterface ()
virtual ~MatcherDescriberInterface ()
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (MonomorphicImpl)
GTEST_DISALLOW_ASSIGN_ (MonomorphicImpl)
GTEST_DISALLOW_ASSIGN_ (MonomorphicImpl)
Private Attributes
const Impl impl_
Detailed Description
template<class Impl>
template<typename T>
class testing::PolymorphicMatcher< Impl >::MonomorphicImpl< T >
Definition at line 449 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<class Impl> template<typename T > testing::PolymorphicMatcher< Impl >::MonomorphicImpl< T >::MonomorphicImpl (const Impl & impl) inline explicit
Definition at line 451 of file gmock-matchers.h.
 : impl_(impl) {}
template<class Impl> template<typename T > testing::PolymorphicMatcher< Impl >::MonomorphicImpl< T >::MonomorphicImpl (const Impl & impl) inline explicit
Definition at line 451 of file gmock-matchers.h.
 : impl_(impl) {}
template<class Impl> template<typename T > testing::PolymorphicMatcher< Impl >::MonomorphicImpl< T >::MonomorphicImpl (const Impl & impl) inline explicit
Definition at line 451 of file gmock-matchers.h.
 : impl_(impl) {}
Member Function Documentation
template<class Impl> template<typename T > virtual void testing::PolymorphicMatcher< Impl >::MonomorphicImpl< T >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 457 of file gmock-matchers.h.
{
       impl_.DescribeNegationTo(os);
     }
template<class Impl> template<typename T > virtual void testing::PolymorphicMatcher< Impl >::MonomorphicImpl< T >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 457 of file gmock-matchers.h.
{
       impl_.DescribeNegationTo(os);
     }
template<class Impl> template<typename T > virtual void testing::PolymorphicMatcher< Impl >::MonomorphicImpl< T >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 457 of file gmock-matchers.h.
{
       impl_.DescribeNegationTo(os);
     }
template<class Impl> template<typename T > virtual void testing::PolymorphicMatcher< Impl >::MonomorphicImpl< T >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 453 of file gmock-matchers.h.
{
       impl_.DescribeTo(os);
     }
template<class Impl> template<typename T > virtual void testing::PolymorphicMatcher< Impl >::MonomorphicImpl< T >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 453 of file gmock-matchers.h.
{
       impl_.DescribeTo(os);
     }
template<class Impl> template<typename T > virtual void testing::PolymorphicMatcher< Impl >::MonomorphicImpl< T >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 453 of file gmock-matchers.h.
{
       impl_.DescribeTo(os);
     }
template<class Impl> template<typename T > testing::PolymorphicMatcher< Impl >::MonomorphicImpl< T >::GTEST_DISALLOW_ASSIGN_ (MonomorphicImpl< T >) private
template<class Impl> template<typename T > testing::PolymorphicMatcher< Impl >::MonomorphicImpl< T >::GTEST_DISALLOW_ASSIGN_ (MonomorphicImpl< T >) private
template<class Impl> template<typename T > testing::PolymorphicMatcher< Impl >::MonomorphicImpl< T >::GTEST_DISALLOW_ASSIGN_ (MonomorphicImpl< T >) private
template<class Impl> template<typename T > virtual bool testing::PolymorphicMatcher< Impl >::MonomorphicImpl< T >::MatchAndExplain (T x, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< T >.
Definition at line 461 of file gmock-matchers.h.
{
       return impl_.MatchAndExplain(x, listener);
     }
template<class Impl> template<typename T > virtual bool testing::PolymorphicMatcher< Impl >::MonomorphicImpl< T >::MatchAndExplain (T x, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< T >.
Definition at line 461 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, testing::MakeMatcher(), and testing::MakePolymorphicMatcher().
{
       return impl_.MatchAndExplain(x, listener);
     }
template<class Impl> template<typename T > virtual bool testing::PolymorphicMatcher< Impl >::MonomorphicImpl< T >::MatchAndExplain (T x, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< T >.
Definition at line 461 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, testing::MakeMatcher(), and testing::MakePolymorphicMatcher().
{
       return impl_.MatchAndExplain(x, listener);
     }
Member Data Documentation
template<class Impl> template<typename T > const Impl testing::PolymorphicMatcher< Impl >::MonomorphicImpl< T >::impl_ private
Definition at line 466 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h