proxygen: testing::internal::WhenDynamicCastToMatcher< To & > Class Template Reference
testing::internal::WhenDynamicCastToMatcher< To & > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
WhenDynamicCastToMatcher (const Matcher< To & > &matcher)
template<typename From >
bool MatchAndExplain (From &from, MatchResultListener *listener) const
WhenDynamicCastToMatcher (const Matcher< To & > &matcher)
template<typename From >
bool MatchAndExplain (From &from, MatchResultListener *listener) const
WhenDynamicCastToMatcher (const Matcher< To & > &matcher)
template<typename From >
bool MatchAndExplain (From &from, MatchResultListener *listener) const
Public Member Functions inherited from testing::internal::WhenDynamicCastToMatcherBase< To & >
WhenDynamicCastToMatcherBase (const Matcher< To & > &matcher)
WhenDynamicCastToMatcherBase (const Matcher< To & > &matcher)
WhenDynamicCastToMatcherBase (const Matcher< To & > &matcher)
void DescribeTo (::std::ostream *os) const
void DescribeTo (::std::ostream *os) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
Additional Inherited Members
Static Protected Member Functions inherited from testing::internal::WhenDynamicCastToMatcherBase< To & >
static string GetToName ()
static string GetToName ()
static string GetToName ()
Protected Attributes inherited from testing::internal::WhenDynamicCastToMatcherBase< To & >
const Matcher< To & > matcher_
Detailed Description
template<typename To>
class testing::internal::WhenDynamicCastToMatcher< To & >
Definition at line 2161 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename To > testing::internal::WhenDynamicCastToMatcher< To & >::WhenDynamicCastToMatcher (const Matcher< To & > & matcher) inline explicit
Definition at line 2163 of file gmock-matchers.h.
       : WhenDynamicCastToMatcherBase<To&>(matcher) {}
template<typename To > testing::internal::WhenDynamicCastToMatcher< To & >::WhenDynamicCastToMatcher (const Matcher< To & > & matcher) inline explicit
Definition at line 2163 of file gmock-matchers.h.
       : WhenDynamicCastToMatcherBase<To&>(matcher) {}
template<typename To > testing::internal::WhenDynamicCastToMatcher< To & >::WhenDynamicCastToMatcher (const Matcher< To & > & matcher) inline explicit
Definition at line 2163 of file gmock-matchers.h.
       : WhenDynamicCastToMatcherBase<To&>(matcher) {}
Member Function Documentation
template<typename To > template<typename From > bool testing::internal::WhenDynamicCastToMatcher< To & >::MatchAndExplain (From & from, MatchResultListener * listener) const inline
Definition at line 2167 of file gmock-matchers.h.
References folly::pushmi::operators::from, testing::internal::MatchPrintAndExplain(), and folly::to().
{
     // We don't want an std::bad_cast here, so do the cast with pointers.
     To* to = dynamic_cast<To*>(&from);
     if (to == NULL) {
       *listener << "which cannot be dynamic_cast to " << this->GetToName();
       return false;
     }
     return MatchPrintAndExplain(*to, this->matcher_, listener);
   }
template<typename To > template<typename From > bool testing::internal::WhenDynamicCastToMatcher< To & >::MatchAndExplain (From & from, MatchResultListener * listener) const inline
Definition at line 2167 of file gmock-matchers.h.
References folly::pushmi::operators::from, testing::internal::MatchPrintAndExplain(), and folly::to().
{
     // We don't want an std::bad_cast here, so do the cast with pointers.
     To* to = dynamic_cast<To*>(&from);
     if (to == NULL) {
       *listener << "which cannot be dynamic_cast to " << this->GetToName();
       return false;
     }
     return MatchPrintAndExplain(*to, this->matcher_, listener);
   }
template<typename To > template<typename From > bool testing::internal::WhenDynamicCastToMatcher< To & >::MatchAndExplain (From & from, MatchResultListener * listener) const inline
Definition at line 2167 of file gmock-matchers.h.
References folly::pushmi::operators::from, testing::internal::MatchPrintAndExplain(), and folly::to().
{
     // We don't want an std::bad_cast here, so do the cast with pointers.
     To* to = dynamic_cast<To*>(&from);
     if (to == NULL) {
       *listener << "which cannot be dynamic_cast to " << this->GetToName();
       return false;
     }
     return MatchPrintAndExplain(*to, this->matcher_, listener);
   }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h