proxygen: testing::internal::UnitTestHelper Class Reference
testing::internal::UnitTestHelper Class Reference
Static Public Member Functions
static TestCase const ** GetSortedTestCases ()
static const TestCase * FindTestCase (const char *name)
static TestInfo const ** GetSortedTests (const TestCase *test_case)
static TestCase const ** GetSortedTestCases ()
static const TestCase * FindTestCase (const char *name)
static TestInfo const ** GetSortedTests (const TestCase *test_case)
static TestCase const ** GetSortedTestCases ()
static const TestCase * FindTestCase (const char *name)
static TestInfo const ** GetSortedTests (const TestCase *test_case)
Detailed Description
Definition at line 53 of file gtest-unittest-api_test.cc.
Member Function Documentation
static const TestCase* testing::internal::UnitTestHelper::FindTestCase (const char * name) inline static
Definition at line 73 of file gtest-unittest-api_test.cc.
References testing::UnitTest::GetInstance(), testing::UnitTest::GetTestCase(), i, name, testing::TestCase::name(), and testing::UnitTest::total_test_case_count().
Referenced by GetSortedTests(), testing::internal::FinalSuccessChecker::TearDown(), and testing::internal::TEST().
{
     UnitTest& unit_test = *UnitTest::GetInstance();
     for (int i = 0; i < unit_test.total_test_case_count(); ++i) {
       const TestCase* test_case = unit_test.GetTestCase(i);
       if (0 == strcmp(test_case->name(), name))
         return test_case;
     }
     return NULL;
   }
static const TestCase* testing::internal::UnitTestHelper::FindTestCase (const char * name) inline static
Definition at line 73 of file gtest-unittest-api_test.cc.
References testing::UnitTest::GetInstance(), testing::UnitTest::GetTestCase(), i, name, testing::TestCase::name(), and testing::UnitTest::total_test_case_count().
{
     UnitTest& unit_test = *UnitTest::GetInstance();
     for (int i = 0; i < unit_test.total_test_case_count(); ++i) {
       const TestCase* test_case = unit_test.GetTestCase(i);
       if (0 == strcmp(test_case->name(), name))
         return test_case;
     }
     return NULL;
   }
static const TestCase* testing::internal::UnitTestHelper::FindTestCase (const char * name) inline static
Definition at line 73 of file gtest-unittest-api_test.cc.
References testing::UnitTest::GetInstance(), testing::UnitTest::GetTestCase(), i, name, testing::TestCase::name(), and testing::UnitTest::total_test_case_count().
{
     UnitTest& unit_test = *UnitTest::GetInstance();
     for (int i = 0; i < unit_test.total_test_case_count(); ++i) {
       const TestCase* test_case = unit_test.GetTestCase(i);
       if (0 == strcmp(test_case->name(), name))
         return test_case;
     }
     return NULL;
   }
static TestCase const** testing::internal::UnitTestHelper::GetSortedTestCases () inline static
Definition at line 57 of file gtest-unittest-api_test.cc.
References testing::UnitTest::GetInstance(), testing::UnitTest::GetTestCase(), i, and testing::UnitTest::total_test_case_count().
{
     UnitTest& unit_test = *UnitTest::GetInstance();
     TestCase const** const test_cases =
         new const TestCase*[unit_test.total_test_case_count()];
     for (int i = 0; i < unit_test.total_test_case_count(); ++i)
       test_cases[i] = unit_test.GetTestCase(i);
     std::sort(test_cases,
               test_cases + unit_test.total_test_case_count(),
               LessByName<TestCase>());
     return test_cases;
   }
static TestCase const** testing::internal::UnitTestHelper::GetSortedTestCases () inline static
Definition at line 57 of file gtest-unittest-api_test.cc.
References testing::UnitTest::GetInstance(), testing::UnitTest::GetTestCase(), i, and testing::UnitTest::total_test_case_count().
Referenced by GetSortedTests(), testing::internal::FinalSuccessChecker::TearDown(), and testing::internal::TEST().
{
     UnitTest& unit_test = *UnitTest::GetInstance();
     TestCase const** const test_cases =
         new const TestCase*[unit_test.total_test_case_count()];
     for (int i = 0; i < unit_test.total_test_case_count(); ++i)
       test_cases[i] = unit_test.GetTestCase(i);
     std::sort(test_cases,
               test_cases + unit_test.total_test_case_count(),
               LessByName<TestCase>());
     return test_cases;
   }
static TestCase const** testing::internal::UnitTestHelper::GetSortedTestCases () inline static
Definition at line 57 of file gtest-unittest-api_test.cc.
References testing::UnitTest::GetInstance(), testing::UnitTest::GetTestCase(), i, and testing::UnitTest::total_test_case_count().
{
     UnitTest& unit_test = *UnitTest::GetInstance();
     TestCase const** const test_cases =
         new const TestCase*[unit_test.total_test_case_count()];
     for (int i = 0; i < unit_test.total_test_case_count(); ++i)
       test_cases[i] = unit_test.GetTestCase(i);
     std::sort(test_cases,
               test_cases + unit_test.total_test_case_count(),
               LessByName<TestCase>());
     return test_cases;
   }
static TestInfo const** testing::internal::UnitTestHelper::GetSortedTests (const TestCase * test_case) inline static
Definition at line 86 of file gtest-unittest-api_test.cc.
References ASSERT_EQ, ASSERT_TRUE, testing::AssertionFailure(), testing::AssertionSuccess(), testing::TestCase::disabled_test_count(), testing::UnitTest::disabled_test_count(), testing::gmock_generated_actions_test::Dummy(), EXPECT_EQ, EXPECT_FALSE, EXPECT_STREQ, EXPECT_TRUE, FindTestCase(), testing::UnitTest::GetInstance(), GetSortedTestCases(), GetSortedTests(), testing::TestCase::GetTestInfo(), i, testing::internal::IsNull(), testing::internal::kTypedTestCases, testing::internal::kTypedTests, name, testing::TestCase::name(), testing::TestCase::should_run(), testing::internal::TEST(), testing::UnitTest::test_case_to_run_count(), testing::TestCase::test_to_run_count(), testing::UnitTest::test_to_run_count(), testing::UnitTest::total_test_case_count(), testing::TestCase::total_test_count(), testing::UnitTest::total_test_count(), testing::TestCase::type_param(), testing::TYPED_TEST(), and testing::TYPED_TEST_CASE().
{
     TestInfo const** const tests =
         new const TestInfo*[test_case->total_test_count()];
     for (int i = 0; i < test_case->total_test_count(); ++i)
       tests[i] = test_case->GetTestInfo(i);
     std::sort(tests, tests + test_case->total_test_count(),
               LessByName<TestInfo>());
     return tests;
   }
static TestInfo const** testing::internal::UnitTestHelper::GetSortedTests (const TestCase * test_case) inline static
Definition at line 86 of file gtest-unittest-api_test.cc.
References testing::gmock_generated_actions_test::Dummy(), testing::TestCase::GetTestInfo(), i, testing::internal::kTypedTestCases, testing::internal::kTypedTests, testing::TestCase::total_test_count(), testing::TYPED_TEST(), and testing::TYPED_TEST_CASE().
Referenced by GetSortedTests(), testing::internal::FinalSuccessChecker::TearDown(), and testing::internal::TEST().
{
     TestInfo const** const tests =
         new const TestInfo*[test_case->total_test_count()];
     for (int i = 0; i < test_case->total_test_count(); ++i)
       tests[i] = test_case->GetTestInfo(i);
     std::sort(tests, tests + test_case->total_test_count(),
               LessByName<TestInfo>());
     return tests;
   }
static TestInfo const** testing::internal::UnitTestHelper::GetSortedTests (const TestCase * test_case) inline static
Definition at line 86 of file gtest-unittest-api_test.cc.
References ASSERT_EQ, ASSERT_TRUE, testing::AssertionFailure(), testing::AssertionSuccess(), testing::TestCase::disabled_test_count(), testing::UnitTest::disabled_test_count(), testing::gmock_generated_actions_test::Dummy(), EXPECT_EQ, EXPECT_FALSE, EXPECT_STREQ, EXPECT_TRUE, FindTestCase(), testing::UnitTest::GetInstance(), GetSortedTestCases(), GetSortedTests(), testing::TestCase::GetTestInfo(), i, testing::internal::IsNull(), testing::internal::kTypedTestCases, testing::internal::kTypedTests, name, testing::TestCase::name(), testing::TestCase::should_run(), testing::internal::TEST(), testing::UnitTest::test_case_to_run_count(), testing::TestCase::test_to_run_count(), testing::UnitTest::test_to_run_count(), testing::UnitTest::total_test_case_count(), testing::TestCase::total_test_count(), testing::UnitTest::total_test_count(), testing::TestCase::type_param(), testing::TYPED_TEST(), and testing::TYPED_TEST_CASE().
{
     TestInfo const** const tests =
         new const TestInfo*[test_case->total_test_count()];
     for (int i = 0; i < test_case->total_test_count(); ++i)
       tests[i] = test_case->GetTestInfo(i);
     std::sort(tests, tests + test_case->total_test_count(),
               LessByName<TestInfo>());
     return tests;
   }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest-unittest-api_test.cc