proxygen: folly::Req Class Reference
folly::Req Class Reference
#include <FlatCombiningExamples.h>
Public Types
enum Type { Type::ADD, Type::FETCHADD }
Public Member Functions
void setType (Type type)
Type getType ()
void setVal (uint64_t val)
uint64_t getVal ()
void setRes (uint64_t res)
uint64_t getRes ()
Private Attributes
Type type_
uint64_t val_
uint64_t res_
Detailed Description
Definition at line 127 of file FlatCombiningExamples.h.
Member Enumeration Documentation
enum folly::Req::Type strong
Enumerator
ADD
FETCHADD
Definition at line 129 of file FlatCombiningExamples.h.
 { ADD, FETCHADD };
Member Function Documentation
uint64_t folly::Req::getRes () inline
Definition at line 151 of file FlatCombiningExamples.h.
                     {
     return res_;
   }
Type folly::Req::getType () inline
Definition at line 135 of file FlatCombiningExamples.h.
References type_.
Referenced by folly::FcCustomExample< Req, Mutex, Atom >::combinedOp().
                  {
     return type_;
   }
uint64_t folly::Req::getVal () inline
Definition at line 143 of file FlatCombiningExamples.h.
Referenced by folly::FcCustomExample< Req, Mutex, Atom >::combinedOp().
                     {
     return val_;
   }
void folly::Req::setRes (uint64_t res) inline
Definition at line 147 of file FlatCombiningExamples.h.
Referenced by folly::FcCustomExample< Req, Mutex, Atom >::combinedOp().
{
     res_ = res;
   }
void folly::Req::setType (Type type) inline
Definition at line 131 of file FlatCombiningExamples.h.
References type, and type_.
{
     type_ = type;
   }
void folly::Req::setVal (uint64_t val) inline
Definition at line 139 of file FlatCombiningExamples.h.
References val.
{
     val_ = val;
   }
Member Data Documentation
uint64_t folly::Req::res_ private
Definition at line 158 of file FlatCombiningExamples.h.
Type folly::Req::type_ private
Definition at line 156 of file FlatCombiningExamples.h.
uint64_t folly::Req::val_ private
Definition at line 157 of file FlatCombiningExamples.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/flat_combining/test/FlatCombiningExamples.h