proxygen: proxygen::TestStreamingCallback Class Reference
proxygen::TestStreamingCallback Class Reference
#include <TestStreamingCallback.h>
Public Member Functions
void onHeader (const folly::fbstring &name, const folly::fbstring &value) override
void onHeadersComplete (HTTPHeaderSize) override
void onDecodeError (HPACK::DecodeError decodeError) override
void reset ()
folly::Expected< HeaderDecodeResult, HPACK::DecodeError > getResult ()
bool hasError () const
std::unique_ptr< std::vector< HPACKHeader > > hpackHeaders () const
char * duplicate (const folly::fbstring &str)
Public Member Functions inherited from proxygen::HPACK::StreamingCallback
virtual ~StreamingCallback ()
Public Attributes
compress::HeaderPieceList headers
HPACK::DecodeError error {HPACK::DecodeError::NONE}
folly::Function< void()> headersCompleteCb
Public Attributes inherited from proxygen::HPACK::StreamingCallback
HeaderCodec::Stats * stats {nullptr}
Detailed Description
Definition at line 18 of file TestStreamingCallback.h.
Member Function Documentation
char* proxygen::TestStreamingCallback::duplicate (const folly::fbstring & str) inline
Definition at line 64 of file TestStreamingCallback.h.
References folly::basic_fbstring< E, T, A, Storage >::data(), and folly::basic_fbstring< E, T, A, Storage >::length().
Referenced by onHeader().
{
     char* res = CHECK_NOTNULL(new char[str.length() + 1]);
     memcpy(res, str.data(), str.length() + 1);
     return res;
   }
folly::Expected<HeaderDecodeResult, HPACK::DecodeError> proxygen::TestStreamingCallback::getResult () inline
Definition at line 39 of file TestStreamingCallback.h.
References error, headers, folly::makeUnexpected(), and proxygen::HPACK::NONE.
Referenced by isLowercase(), and TEST_F().
{
     if (error == HPACK::DecodeError::NONE) {
       return HeaderDecodeResult{headers, 0};
     } else {
       return folly::makeUnexpected(error);
     }
   }
bool proxygen::TestStreamingCallback::hasError () const inline
Definition at line 47 of file TestStreamingCallback.h.
References error, and proxygen::HPACK::NONE.
Referenced by proxygen::hpack::decode(), encodeDecode(), proxygen::hpack::encodeDecode(), hpackHeaders(), isLowercase(), and TEST().
{
     return error != HPACK::DecodeError::NONE;
   }
std::unique_ptr<std::vector<HPACKHeader> > proxygen::TestStreamingCallback::hpackHeaders () const inline
Definition at line 51 of file TestStreamingCallback.h.
References hasError(), headers, and i.
Referenced by proxygen::hpack::decode(), and proxygen::hpack::encodeDecode().
{
     CHECK(!hasError());
     auto result = std::make_unique<std::vector<HPACKHeader>>();
     for (size_t i = 0; i < headers.size(); i += 2) {
       result->emplace_back(headers[i].str, headers[i + 1].str);
     }
     return result;
   }
void proxygen::TestStreamingCallback::onDecodeError (HPACK::DecodeError decodeError) inline override virtual
Implements proxygen::HPACK::StreamingCallback.
Definition at line 30 of file TestStreamingCallback.h.
References error.
{
     error = decodeError;
   }
void proxygen::TestStreamingCallback::onHeader (const folly::fbstring & name, const folly::fbstring & value) inline override virtual
Implements proxygen::HPACK::StreamingCallback.
Definition at line 20 of file TestStreamingCallback.h.
References duplicate(), headers, and folly::basic_fbstring< E, T, A, Storage >::size().
{
     headers.emplace_back(duplicate(name), name.size(), true, false);
     headers.emplace_back(duplicate(value), value.size(), true, false);
   }
void proxygen::TestStreamingCallback::onHeadersComplete (HTTPHeaderSize) inline override virtual
Implements proxygen::HPACK::StreamingCallback.
Definition at line 25 of file TestStreamingCallback.h.
References headersCompleteCb.
{
     if (headersCompleteCb) {
       headersCompleteCb();
     }
   }
void proxygen::TestStreamingCallback::reset () inline
Definition at line 34 of file TestStreamingCallback.h.
References error, headers, and proxygen::HPACK::NONE.
Referenced by TEST_F().
                {
     headers.clear();
     error = HPACK::DecodeError::NONE;
   }
Member Data Documentation
HPACK::DecodeError proxygen::TestStreamingCallback::error {HPACK::DecodeError::NONE}
Definition at line 63 of file TestStreamingCallback.h.
Referenced by getResult(), hasError(), isLowercase(), onDecodeError(), and reset().
compress::HeaderPieceList proxygen::TestStreamingCallback::headers
Definition at line 62 of file TestStreamingCallback.h.
Referenced by getResult(), hpackHeaders(), onHeader(), and reset().
folly::Function<void()> proxygen::TestStreamingCallback::headersCompleteCb
Definition at line 70 of file TestStreamingCallback.h.
Referenced by onHeadersComplete().
The documentation for this class was generated from the following file:
proxygen/lib/http/codec/compress/test/TestStreamingCallback.h