proxygen: ReadCallback::Buffer Class Reference
ReadCallback::Buffer Class Reference
#include <AsyncSocketTest.h>
Public Member Functions
Buffer ()
Buffer (char *buf, size_t len)
void reset ()
void allocate (size_t len)
void free ()
Public Attributes
char * buffer
size_t length
Detailed Description
Definition at line 151 of file AsyncSocketTest.h.
Constructor & Destructor Documentation
ReadCallback::Buffer::Buffer () inline
Definition at line 153 of file AsyncSocketTest.h.
 : buffer(nullptr), length(0) {}
ReadCallback::Buffer::Buffer (char * buf, size_t len) inline
Definition at line 154 of file AsyncSocketTest.h.
 : buffer(buf), length(len) {}
Member Function Documentation
void ReadCallback::Buffer::allocate (size_t len) inline
Definition at line 160 of file AsyncSocketTest.h.
References buffer().
{
       assert(buffer == nullptr);
       this->buffer = static_cast<char*>(malloc(len));
       this->length = len;
     }
void ReadCallback::Buffer::free () inline
Definition at line 165 of file AsyncSocketTest.h.
References buffer(), and bm::free().
                 {
       ::free(buffer);
       reset();
     }
void ReadCallback::Buffer::reset () inline
Definition at line 156 of file AsyncSocketTest.h.
References buffer().
                  {
       buffer = nullptr;
       length = 0;
     }
Member Data Documentation
char* ReadCallback::Buffer::buffer
Definition at line 170 of file AsyncSocketTest.h.
size_t ReadCallback::Buffer::length
Definition at line 171 of file AsyncSocketTest.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/io/async/test/AsyncSocketTest.h