proxygen: folly::test::TemporaryFile Class Reference
folly::test::TemporaryFile Class Reference
#include <TestUtil.h>
Public Types
enum Scope { Scope::PERMANENT, Scope::UNLINK_IMMEDIATELY, Scope::UNLINK_ON_DESTRUCTION }
Public Member Functions
TemporaryFile (StringPiece namePrefix=StringPiece(), fs::path dir=fs::path(), Scope scope=Scope::UNLINK_ON_DESTRUCTION, bool closeOnDestruction=true)
~TemporaryFile ()
TemporaryFile (TemporaryFile &&other) noexcept
TemporaryFile & operator= (TemporaryFile &&other)
void close ()
int fd () const
const fs::path & path () const
void reset ()
Private Member Functions
void assign (TemporaryFile &other)
Private Attributes
Scope scope_
bool closeOnDestruction_
int fd_
fs::path path_
Detailed Description
Temporary file.
By default, the file is created in a system-specific location (the value of the TMPDIR environment variable, or /tmp), but you can override that with a different (non-empty) directory passed to the constructor.
By default, the file is closed and deleted when the TemporaryFile object is destroyed, but both these behaviors can be overridden with arguments to the constructor.
Definition at line 40 of file TestUtil.h.
Member Enumeration Documentation
enum folly::test::TemporaryFile::Scope strong
Enumerator
PERMANENT
UNLINK_IMMEDIATELY
UNLINK_ON_DESTRUCTION
Definition at line 42 of file TestUtil.h.
                    {
     PERMANENT,
     UNLINK_IMMEDIATELY,
     UNLINK_ON_DESTRUCTION,
   };
Constructor & Destructor Documentation
folly::test::TemporaryFile::TemporaryFile (StringPiece namePrefix = StringPiece(), fs::path dir = fs::path(), Scope scope = Scope::UNLINK_ON_DESTRUCTION, bool closeOnDestruction = true) explicit
Definition at line 55 of file TestUtil.cpp.
References folly::checkUnixError(), fd_, path_, scope_, UNLINK_IMMEDIATELY, and folly::WARNING.
     : scope_(scope),
       closeOnDestruction_(closeOnDestruction),
       fd_(-1),
       path_(generateUniquePath(std::move(dir), namePrefix)) {
   fd_ = open(path_.string().c_str(), O_RDWR | O_CREAT | O_EXCL, 0666);
   checkUnixError(fd_, "open failed");
   if (scope_ == Scope::UNLINK_IMMEDIATELY) {
     boost::system::error_code ec;
     fs::remove(path_, ec);
     if (ec) {
       LOG(WARNING) << "unlink on construction failed: " << ec;
     } else {
       path_.clear();
     }
   }
 }
folly::test::TemporaryFile::~TemporaryFile ()
Definition at line 109 of file TestUtil.cpp.
References reset().
{
   reset();
 }
folly::test::TemporaryFile::TemporaryFile (TemporaryFile && other) inline noexcept
Definition at line 55 of file TestUtil.h.
References assign().
{
     assign(other);
   }
Member Function Documentation
void folly::test::TemporaryFile::assign (TemporaryFile & other) inline private
Definition at line 80 of file TestUtil.h.
References closeOnDestruction_, folly::exchange(), fd_, path_, and scope_.
Referenced by operator=(), and TemporaryFile().
{
     scope_ = other.scope_;
     closeOnDestruction_ = other.closeOnDestruction_;
     fd_ = std::exchange(other.fd_, -1);
     path_ = other.path_;
   }
void folly::test::TemporaryFile::close ()
Definition at line 78 of file TestUtil.cpp.
References fd_.
Referenced by operator=(), reset(), and TEST().
{
   if (::close(fd_) == -1) {
     PLOG(ERROR) << "close failed";
   }
   fd_ = -1;
 }
int folly::test::TemporaryFile::fd () const inline
Definition at line 68 of file TestUtil.h.
References fd_, path(), and reset().
Referenced by folly::symbolizer::test::TEST(), folly::test::TEST(), TEST(), TEST_F(), and TEST_P().
                  {
     return fd_;
   }
TemporaryFile& folly::test::TemporaryFile::operator= (TemporaryFile && other) inline
Definition at line 59 of file TestUtil.h.
References assign(), close(), and reset().
{
     if (this != &other) {
       reset();
       assign(other);
     }
     return *this;
   }
const fs::path & folly::test::TemporaryFile::path () const
Definition at line 85 of file TestUtil.cpp.
References path_, scope_, and UNLINK_IMMEDIATELY.
Referenced by folly::test::CaptureFD::CaptureFD(), fd(), wangle::getPersistentCacheFilename(), folly::test::CaptureFD::read(), folly::test::CaptureFD::readIncremental(), TEST(), fizz::test::TEST(), folly::test::TEST(), TEST_F(), and TEST_P().
{
   CHECK(scope_ != Scope::UNLINK_IMMEDIATELY);
   DCHECK(!path_.empty());
   return path_;
 }
void folly::test::TemporaryFile::reset ()
Definition at line 91 of file TestUtil.cpp.
References close(), closeOnDestruction_, fd_, path_, PERMANENT, scope_, and folly::WARNING.
Referenced by fd(), operator=(), and ~TemporaryFile().
{
   if (fd_ != -1 && closeOnDestruction_) {
     if (::close(fd_) == -1) {
       PLOG(ERROR) << "close failed (fd = " << fd_ << "): ";
     }
   }
   // If we previously failed to unlink() (UNLINK_IMMEDIATELY), we'll
   // try again here.
   if (scope_ != Scope::PERMANENT && !path_.empty()) {
     boost::system::error_code ec;
     fs::remove(path_, ec);
     if (ec) {
       LOG(WARNING) << "unlink on destruction failed: " << ec;
     }
   }
 }
Member Data Documentation
bool folly::test::TemporaryFile::closeOnDestruction_ private
Definition at line 76 of file TestUtil.h.
Referenced by assign(), and reset().
int folly::test::TemporaryFile::fd_ private
Definition at line 77 of file TestUtil.h.
Referenced by assign(), close(), fd(), reset(), and TemporaryFile().
fs::path folly::test::TemporaryFile::path_ private
Definition at line 78 of file TestUtil.h.
Referenced by assign(), path(), folly::test::TemporaryDirectory::path(), reset(), and TemporaryFile().
Scope folly::test::TemporaryFile::scope_ private
Definition at line 75 of file TestUtil.h.
Referenced by assign(), path(), reset(), and TemporaryFile().
The documentation for this class was generated from the following files:
proxygen/folly/folly/experimental/TestUtil.h
proxygen/folly/folly/experimental/TestUtil.cpp