proxygen: folly::FormatValue< dynamic > Class Template Reference
folly::FormatValue< dynamic > Class Template Reference
#include <dynamic-inl.h>
Public Member Functions
FormatValue (const dynamic &val)
template<class FormatCallback >
void format (FormatArg &arg, FormatCallback &cb) const
Private Attributes
const dynamic & val_
Detailed Description
template<>
class folly::FormatValue< dynamic >
Definition at line 1167 of file dynamic-inl.h.
Constructor & Destructor Documentation
folly::FormatValue< dynamic >::FormatValue (const dynamic & val) inline explicit
Definition at line 1169 of file dynamic-inl.h.
 : val_(val) {}
Member Function Documentation
template<class FormatCallback > void folly::FormatValue< dynamic >::format (FormatArg & arg, FormatCallback & cb) const inline
Definition at line 1172 of file dynamic-inl.h.
References folly::dynamic::ARRAY, folly::dynamic::BOOL, folly::dynamic::DOUBLE, folly::format(), folly::dynamic::INT64, folly::dynamic::NULLT, folly::dynamic::OBJECT, folly::FormatArg::splitIntKey(), folly::FormatArg::splitKey(), folly::dynamic::STRING, and folly::Range< Iter >::toString().
{
     switch (val_.type()) {
       case dynamic::NULLT:
         FormatValue<std::nullptr_t>(nullptr).format(arg, cb);
         break;
       case dynamic::BOOL:
         FormatValue<bool>(val_.asBool()).format(arg, cb);
         break;
       case dynamic::INT64:
         FormatValue<int64_t>(val_.asInt()).format(arg, cb);
         break;
       case dynamic::STRING:
         FormatValue<std::string>(val_.asString()).format(arg, cb);
         break;
       case dynamic::DOUBLE:
         FormatValue<double>(val_.asDouble()).format(arg, cb);
         break;
       case dynamic::ARRAY:
         FormatValue(val_.at(arg.splitIntKey())).format(arg, cb);
         break;
       case dynamic::OBJECT:
         FormatValue(val_.at(arg.splitKey().toString())).format(arg, cb);
         break;
     }
   }
Member Data Documentation
const dynamic& folly::FormatValue< dynamic >::val_ private
Definition at line 1199 of file dynamic-inl.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/dynamic-inl.h