proxygen: folly::io::test::DataHolder Class Reference
folly::io::test::DataHolder Class Reference
Public Member Functions
uint64_t hash (size_t size) const
ByteRange data (size_t size) const
Protected Member Functions
DataHolder (size_t sizeLog2)
Protected Attributes
const size_t size_
std::unique_ptr< uint8_t[]> data_
std::unordered_map< uint64_t, uint64_t > hashCache_
Detailed Description
Definition at line 51 of file CompressionTest.cpp.
Constructor & Destructor Documentation
folly::io::test::DataHolder::DataHolder (size_t sizeLog2) explicit protected
Definition at line 63 of file CompressionTest.cpp.
     : size_(size_t(1) << sizeLog2), data_(new uint8_t[size_]) {}
Member Function Documentation
ByteRange folly::io::test::DataHolder::data (size_t size) const
Definition at line 78 of file CompressionTest.cpp.
References data_, folly::size(), and size_.
Referenced by folly::io::test::StreamingCompressionTest::runCompressStreamTest(), folly::io::test::StreamingCompressionTest::runFlushTest(), folly::io::test::StreamingCompressionTest::runResetStreamTest(), folly::io::test::CompressionTest::runSimpleIOBufTest(), folly::io::test::CompressionTest::runSimpleStringTest(), folly::io::test::CompressionVarintTest::runSimpleTest(), folly::io::test::CompressionCorruptionTest::runSimpleTest(), folly::io::test::AutomaticCodecTest::runSimpleTest(), folly::io::test::StreamingCompressionTest::runUncompressStreamTest(), folly::io::test::CompressionTest::SetUp(), folly::io::test::StreamingCompressionTest::SetUp(), folly::io::test::TEST(), and folly::io::test::TEST_P().
{
   CHECK_LE(size, size_);
   return ByteRange(data_.get(), size);
 }
uint64_t folly::io::test::DataHolder::hash (size_t size) const
Definition at line 66 of file CompressionTest.cpp.
References data_, folly::hash::fnv64_buf(), h, hashCache_, folly::size(), size_, and uint64_t.
Referenced by folly::io::test::StreamingCompressionTest::runCompressStreamTest(), folly::io::test::StreamingCompressionTest::runResetStreamTest(), folly::io::test::CompressionTest::runSimpleIOBufTest(), folly::io::test::CompressionVarintTest::runSimpleTest(), folly::io::test::CompressionCorruptionTest::runSimpleTest(), folly::io::test::AutomaticCodecTest::runSimpleTest(), and folly::io::test::TEST_P().
{
   CHECK_LE(size, size_);
   auto p = hashCache_.find(size);
   if (p != hashCache_.end()) {
     return p->second;
   }
   uint64_t h = folly::hash::fnv64_buf(data_.get(), size);
   hashCache_[size] = h;
   return h;
 }
Member Data Documentation
std::unique_ptr<uint8_t[]> folly::io::test::DataHolder::data_ protected
Definition at line 59 of file CompressionTest.cpp.
Referenced by folly::io::test::ConstantDataHolder::ConstantDataHolder(), data(), hash(), and folly::io::test::RandomDataHolder::RandomDataHolder().
std::unordered_map<uint64_t, uint64_t> folly::io::test::DataHolder::hashCache_ mutable protected
Definition at line 60 of file CompressionTest.cpp.
Referenced by hash().
const size_t folly::io::test::DataHolder::size_ protected
Definition at line 58 of file CompressionTest.cpp.
Referenced by folly::io::test::ConstantDataHolder::ConstantDataHolder(), data(), and hash().
The documentation for this class was generated from the following file:
proxygen/folly/folly/compression/test/CompressionTest.cpp