proxygen: testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)> Class Template Reference
testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)> Class Template Reference
#include <gmock-generated-function-mockers.h>
Public Types
typedef R F(A1, A2, A3, A4, A5, A6, A7, A8, A9)
typedef internal::Function< F >::ArgumentTuple ArgumentTuple
typedef R F(A1, A2, A3, A4, A5, A6, A7, A8, A9)
typedef internal::Function< F >::ArgumentTuple ArgumentTuple
typedef R F(A1, A2, A3, A4, A5, A6, A7, A8, A9)
typedef internal::Function< F >::ArgumentTuple ArgumentTuple
Public Types inherited from testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>
typedef Function< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >::Result Result
typedef Function< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >::Result Result
typedef Function< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >::Result Result
typedef Function< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >::ArgumentTuple ArgumentTuple
typedef Function< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >::ArgumentTuple ArgumentTuple
typedef Function< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >::ArgumentTuple ArgumentTuple
typedef Function< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >::ArgumentMatcherTuple ArgumentMatcherTuple
typedef Function< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >::ArgumentMatcherTuple ArgumentMatcherTuple
typedef Function< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >::ArgumentMatcherTuple ArgumentMatcherTuple
Public Member Functions
MockSpec< F > & With (const Matcher< A1 > &m1, const Matcher< A2 > &m2, const Matcher< A3 > &m3, const Matcher< A4 > &m4, const Matcher< A5 > &m5, const Matcher< A6 > &m6, const Matcher< A7 > &m7, const Matcher< A8 > &m8, const Matcher< A9 > &m9)
R Invoke (A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9)
MockSpec< F > & With (const Matcher< A1 > &m1, const Matcher< A2 > &m2, const Matcher< A3 > &m3, const Matcher< A4 > &m4, const Matcher< A5 > &m5, const Matcher< A6 > &m6, const Matcher< A7 > &m7, const Matcher< A8 > &m8, const Matcher< A9 > &m9)
R Invoke (A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9)
MockSpec< F > & With (const Matcher< A1 > &m1, const Matcher< A2 > &m2, const Matcher< A3 > &m3, const Matcher< A4 > &m4, const Matcher< A5 > &m5, const Matcher< A6 > &m6, const Matcher< A7 > &m7, const Matcher< A8 > &m8, const Matcher< A9 > &m9)
R Invoke (A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9)
Public Member Functions inherited from testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>
FunctionMockerBase ()
FunctionMockerBase ()
FunctionMockerBase ()
virtual ~FunctionMockerBase () GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
virtual ~FunctionMockerBase () GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
virtual ~FunctionMockerBase () GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
const OnCallSpec< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) > * FindOnCallSpec (const ArgumentTuple &args) const
const OnCallSpec< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) > * FindOnCallSpec (const ArgumentTuple &args) const
const OnCallSpec< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) > * FindOnCallSpec (const ArgumentTuple &args) const
Result PerformDefaultAction (const ArgumentTuple &args, const string &call_description) const
Result PerformDefaultAction (const ArgumentTuple &args, const string &call_description) const
Result PerformDefaultAction (const ArgumentTuple &args, const string &call_description) const
virtual UntypedActionResultHolderBase * UntypedPerformDefaultAction (const void *untyped_args, const string &call_description) const
virtual UntypedActionResultHolderBase * UntypedPerformDefaultAction (const void *untyped_args, const string &call_description) const
virtual UntypedActionResultHolderBase * UntypedPerformDefaultAction (const void *untyped_args, const string &call_description) const
virtual UntypedActionResultHolderBase * UntypedPerformAction (const void *untyped_action, const void *untyped_args) const
virtual UntypedActionResultHolderBase * UntypedPerformAction (const void *untyped_action, const void *untyped_args) const
virtual UntypedActionResultHolderBase * UntypedPerformAction (const void *untyped_action, const void *untyped_args) const
virtual void ClearDefaultActionsLocked () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
virtual void ClearDefaultActionsLocked () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
virtual void ClearDefaultActionsLocked () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
Public Member Functions inherited from testing::internal::UntypedFunctionMockerBase
UntypedFunctionMockerBase ()
virtual ~UntypedFunctionMockerBase ()
bool VerifyAndClearExpectationsLocked () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void RegisterOwner (const void *mock_obj) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
void SetOwnerAndName (const void *mock_obj, const char *name) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
const void * MockObject () const GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
const char * Name () const GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
UntypedActionResultHolderBase * UntypedInvokeWith (const void *untyped_args) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
UntypedFunctionMockerBase ()
virtual ~UntypedFunctionMockerBase ()
bool VerifyAndClearExpectationsLocked () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void RegisterOwner (const void *mock_obj) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
void SetOwnerAndName (const void *mock_obj, const char *name) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
const void * MockObject () const GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
const char * Name () const GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
UntypedActionResultHolderBase * UntypedInvokeWith (const void *untyped_args) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
UntypedFunctionMockerBase ()
virtual ~UntypedFunctionMockerBase ()
bool VerifyAndClearExpectationsLocked () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void RegisterOwner (const void *mock_obj) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
void SetOwnerAndName (const void *mock_obj, const char *name) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
const void * MockObject () const GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
const char * Name () const GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
UntypedActionResultHolderBase * UntypedInvokeWith (const void *untyped_args) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
Additional Inherited Members
Protected Types inherited from testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>
typedef ActionResultHolder< Result > ResultHolder
typedef ActionResultHolder< Result > ResultHolder
typedef ActionResultHolder< Result > ResultHolder
Protected Types inherited from testing::internal::UntypedFunctionMockerBase
typedef std::vector< const void * > UntypedOnCallSpecs
typedef std::vector< internal::linked_ptr< ExpectationBase > > UntypedExpectations
typedef std::vector< const void * > UntypedOnCallSpecs
typedef std::vector< internal::linked_ptr< ExpectationBase > > UntypedExpectations
typedef std::vector< const void * > UntypedOnCallSpecs
typedef std::vector< internal::linked_ptr< ExpectationBase > > UntypedExpectations
Protected Member Functions inherited from testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>
Result InvokeWith (const ArgumentTuple &args) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
Result InvokeWith (const ArgumentTuple &args) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
Result InvokeWith (const ArgumentTuple &args) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
OnCallSpec< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) > & AddNewOnCallSpec (const char *file, int line, const ArgumentMatcherTuple &m) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
OnCallSpec< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) > & AddNewOnCallSpec (const char *file, int line, const ArgumentMatcherTuple &m) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
OnCallSpec< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) > & AddNewOnCallSpec (const char *file, int line, const ArgumentMatcherTuple &m) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
TypedExpectation< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) > & AddNewExpectation (const char *file, int line, const string &source_text, const ArgumentMatcherTuple &m) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
TypedExpectation< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) > & AddNewExpectation (const char *file, int line, const string &source_text, const ArgumentMatcherTuple &m) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
TypedExpectation< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) > & AddNewExpectation (const char *file, int line, const string &source_text, const ArgumentMatcherTuple &m) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
MockSpec< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) > & current_spec ()
MockSpec< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) > & current_spec ()
MockSpec< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) > & current_spec ()
Protected Member Functions inherited from testing::internal::UntypedFunctionMockerBase
Expectation GetHandleOf (ExpectationBase *exp)
Expectation GetHandleOf (ExpectationBase *exp)
Expectation GetHandleOf (ExpectationBase *exp)
Protected Attributes inherited from testing::internal::UntypedFunctionMockerBase
const void * mock_obj_
const char * name_
UntypedOnCallSpecs untyped_on_call_specs_
UntypedExpectations untyped_expectations_
Detailed Description
template<typename R, typename A1, typename A2, typename A3, typename A4, typename A5, typename A6, typename A7, typename A8, typename A9>
class testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>
Definition at line 270 of file gmock-generated-function-mockers.h.
Member Typedef Documentation
template<typename R , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 > typedef internal::Function<F>::ArgumentTuple testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>::ArgumentTuple
Definition at line 274 of file gmock-generated-function-mockers.h.
template<typename R , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 > typedef internal::Function<F>::ArgumentTuple testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>::ArgumentTuple
Definition at line 274 of file gmock-generated-function-mockers.h.
template<typename R , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 > typedef internal::Function<F>::ArgumentTuple testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>::ArgumentTuple
Definition at line 274 of file gmock-generated-function-mockers.h.
template<typename R , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 > typedef R testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>::F(A1, A2, A3, A4, A5, A6, A7, A8, A9)
Definition at line 273 of file gmock-generated-function-mockers.h.
template<typename R , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 > typedef R testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>::F(A1, A2, A3, A4, A5, A6, A7, A8, A9)
Definition at line 273 of file gmock-generated-function-mockers.h.
template<typename R , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 > typedef R testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>::F(A1, A2, A3, A4, A5, A6, A7, A8, A9)
Definition at line 273 of file gmock-generated-function-mockers.h.
Member Function Documentation
template<typename R , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 > R testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>::Invoke (A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9) inline
Definition at line 285 of file gmock-generated-function-mockers.h.
{
     // Even though gcc and MSVC don't enforce it, 'this->' is required
     // by the C++ standard [14.6.4] here, as the base class type is
     // dependent on the template argument (and thus shouldn't be
     // looked into when resolving InvokeWith).
     return this->InvokeWith(ArgumentTuple(a1, a2, a3, a4, a5, a6, a7, a8, a9));
   }
template<typename R , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 > R testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>::Invoke (A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9) inline
Definition at line 285 of file gmock-generated-function-mockers.h.
{
     // Even though gcc and MSVC don't enforce it, 'this->' is required
     // by the C++ standard [14.6.4] here, as the base class type is
     // dependent on the template argument (and thus shouldn't be
     // looked into when resolving InvokeWith).
     return this->InvokeWith(ArgumentTuple(a1, a2, a3, a4, a5, a6, a7, a8, a9));
   }
template<typename R , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 > R testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>::Invoke (A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9) inline
Definition at line 285 of file gmock-generated-function-mockers.h.
{
     // Even though gcc and MSVC don't enforce it, 'this->' is required
     // by the C++ standard [14.6.4] here, as the base class type is
     // dependent on the template argument (and thus shouldn't be
     // looked into when resolving InvokeWith).
     return this->InvokeWith(ArgumentTuple(a1, a2, a3, a4, a5, a6, a7, a8, a9));
   }
template<typename R , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 > MockSpec<F>& testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>::With (const Matcher< A1 > & m1, const Matcher< A2 > & m2, const Matcher< A3 > & m3, const Matcher< A4 > & m4, const Matcher< A5 > & m5, const Matcher< A6 > & m6, const Matcher< A7 > & m7, const Matcher< A8 > & m8, const Matcher< A9 > & m9) inline
Definition at line 276 of file gmock-generated-function-mockers.h.
References std::tr1::make_tuple().
{
     this->current_spec().SetMatchers(::testing::make_tuple(m1, m2, m3, m4, m5,
         m6, m7, m8, m9));
     return this->current_spec();
   }
template<typename R , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 > MockSpec<F>& testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>::With (const Matcher< A1 > & m1, const Matcher< A2 > & m2, const Matcher< A3 > & m3, const Matcher< A4 > & m4, const Matcher< A5 > & m5, const Matcher< A6 > & m6, const Matcher< A7 > & m7, const Matcher< A8 > & m8, const Matcher< A9 > & m9) inline
Definition at line 276 of file gmock-generated-function-mockers.h.
References std::tr1::make_tuple().
{
     this->current_spec().SetMatchers(::testing::make_tuple(m1, m2, m3, m4, m5,
         m6, m7, m8, m9));
     return this->current_spec();
   }
template<typename R , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 > MockSpec<F>& testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>::With (const Matcher< A1 > & m1, const Matcher< A2 > & m2, const Matcher< A3 > & m3, const Matcher< A4 > & m4, const Matcher< A5 > & m5, const Matcher< A6 > & m6, const Matcher< A7 > & m7, const Matcher< A8 > & m8, const Matcher< A9 > & m9) inline
Definition at line 276 of file gmock-generated-function-mockers.h.
References std::tr1::make_tuple().
{
     this->current_spec().SetMatchers(::testing::make_tuple(m1, m2, m3, m4, m5,
         m6, m7, m8, m9));
     return this->current_spec();
   }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-generated-function-mockers.h