proxygen: InvokeHelper Class Reference
InvokeHelper Class Reference
#include <gmock_link_test.h>
Public Member Functions
void VoidFromVoid ()
void VoidFromString (char *)
void VoidFromVoid ()
void VoidFromString (char *)
void VoidFromVoid ()
void VoidFromString (char *)
Static Public Member Functions
static void StaticVoidFromVoid ()
static void StaticVoidFromString (char *)
static int StaticIntFromString (char *)
static bool StaticBoolFromString (const char *)
static void StaticVoidFromVoid ()
static void StaticVoidFromString (char *)
static int StaticIntFromString (char *)
static bool StaticBoolFromString (const char *)
static void StaticVoidFromVoid ()
static void StaticVoidFromString (char *)
static int StaticIntFromString (char *)
static bool StaticBoolFromString (const char *)
Detailed Description
Definition at line 223 of file gmock_link_test.h.
Member Function Documentation
static bool InvokeHelper::StaticBoolFromString (const char *) inline static
Definition at line 230 of file gmock_link_test.h.
Referenced by TEST().
 { return true; }
static bool InvokeHelper::StaticBoolFromString (const char *) inline static
Definition at line 230 of file gmock_link_test.h.
 { return true; }
static bool InvokeHelper::StaticBoolFromString (const char *) inline static
Definition at line 230 of file gmock_link_test.h.
 { return true; }
static int InvokeHelper::StaticIntFromString (char *) inline static
Definition at line 229 of file gmock_link_test.h.
 { return 1; }
static int InvokeHelper::StaticIntFromString (char *) inline static
Definition at line 229 of file gmock_link_test.h.
 { return 1; }
static int InvokeHelper::StaticIntFromString (char *) inline static
Definition at line 229 of file gmock_link_test.h.
Referenced by TEST().
 { return 1; }
static void InvokeHelper::StaticVoidFromString (char *) inline static
Definition at line 227 of file gmock_link_test.h.
 {}
static void InvokeHelper::StaticVoidFromString (char *) inline static
Definition at line 227 of file gmock_link_test.h.
Referenced by TEST().
 {}
static void InvokeHelper::StaticVoidFromString (char *) inline static
Definition at line 227 of file gmock_link_test.h.
 {}
static void InvokeHelper::StaticVoidFromVoid () inline static
Definition at line 225 of file gmock_link_test.h.
 {}
static void InvokeHelper::StaticVoidFromVoid () inline static
Definition at line 225 of file gmock_link_test.h.
 {}
static void InvokeHelper::StaticVoidFromVoid () inline static
Definition at line 225 of file gmock_link_test.h.
Referenced by TEST().
 {}
void InvokeHelper::VoidFromString (char *) inline
Definition at line 228 of file gmock_link_test.h.
 {}
void InvokeHelper::VoidFromString (char *) inline
Definition at line 228 of file gmock_link_test.h.
 {}
void InvokeHelper::VoidFromString (char *) inline
Definition at line 228 of file gmock_link_test.h.
Referenced by TEST().
 {}
void InvokeHelper::VoidFromVoid () inline
Definition at line 226 of file gmock_link_test.h.
Referenced by TEST().
 {}
void InvokeHelper::VoidFromVoid () inline
Definition at line 226 of file gmock_link_test.h.
 {}
void InvokeHelper::VoidFromVoid () inline
Definition at line 226 of file gmock_link_test.h.
 {}
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock_link_test.h