proxygen: testing::internal::EitherOfMatcherImpl< T > Class Template Reference
testing::internal::EitherOfMatcherImpl< T > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
EitherOfMatcherImpl (const Matcher< T > &matcher1, const Matcher< T > &matcher2)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (T x, MatchResultListener *listener) const
EitherOfMatcherImpl (const Matcher< T > &matcher1, const Matcher< T > &matcher2)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (T x, MatchResultListener *listener) const
EitherOfMatcherImpl (const Matcher< T > &matcher1, const Matcher< T > &matcher2)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (T x, MatchResultListener *listener) const
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
virtual ~MatcherDescriberInterface ()
virtual ~MatcherDescriberInterface ()
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (EitherOfMatcherImpl)
GTEST_DISALLOW_ASSIGN_ (EitherOfMatcherImpl)
GTEST_DISALLOW_ASSIGN_ (EitherOfMatcherImpl)
Private Attributes
const Matcher< T > matcher1_
const Matcher< T > matcher2_
Detailed Description
template<typename T>
class testing::internal::EitherOfMatcherImpl< T >
Definition at line 1664 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename T > testing::internal::EitherOfMatcherImpl< T >::EitherOfMatcherImpl (const Matcher< T > & matcher1, const Matcher< T > & matcher2) inline
Definition at line 1666 of file gmock-matchers.h.
       : matcher1_(matcher1), matcher2_(matcher2) {}
template<typename T > testing::internal::EitherOfMatcherImpl< T >::EitherOfMatcherImpl (const Matcher< T > & matcher1, const Matcher< T > & matcher2) inline
Definition at line 1666 of file gmock-matchers.h.
       : matcher1_(matcher1), matcher2_(matcher2) {}
template<typename T > testing::internal::EitherOfMatcherImpl< T >::EitherOfMatcherImpl (const Matcher< T > & matcher1, const Matcher< T > & matcher2) inline
Definition at line 1666 of file gmock-matchers.h.
       : matcher1_(matcher1), matcher2_(matcher2) {}
Member Function Documentation
template<typename T > virtual void testing::internal::EitherOfMatcherImpl< T >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 1677 of file gmock-matchers.h.
{
     *os << "(";
     matcher1_.DescribeNegationTo(os);
     *os << ") and (";
     matcher2_.DescribeNegationTo(os);
     *os << ")";
   }
template<typename T > virtual void testing::internal::EitherOfMatcherImpl< T >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 1677 of file gmock-matchers.h.
{
     *os << "(";
     matcher1_.DescribeNegationTo(os);
     *os << ") and (";
     matcher2_.DescribeNegationTo(os);
     *os << ")";
   }
template<typename T > virtual void testing::internal::EitherOfMatcherImpl< T >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 1677 of file gmock-matchers.h.
{
     *os << "(";
     matcher1_.DescribeNegationTo(os);
     *os << ") and (";
     matcher2_.DescribeNegationTo(os);
     *os << ")";
   }
template<typename T > virtual void testing::internal::EitherOfMatcherImpl< T >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 1669 of file gmock-matchers.h.
{
     *os << "(";
     matcher1_.DescribeTo(os);
     *os << ") or (";
     matcher2_.DescribeTo(os);
     *os << ")";
   }
template<typename T > virtual void testing::internal::EitherOfMatcherImpl< T >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 1669 of file gmock-matchers.h.
{
     *os << "(";
     matcher1_.DescribeTo(os);
     *os << ") or (";
     matcher2_.DescribeTo(os);
     *os << ")";
   }
template<typename T > virtual void testing::internal::EitherOfMatcherImpl< T >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 1669 of file gmock-matchers.h.
{
     *os << "(";
     matcher1_.DescribeTo(os);
     *os << ") or (";
     matcher2_.DescribeTo(os);
     *os << ")";
   }
template<typename T > testing::internal::EitherOfMatcherImpl< T >::GTEST_DISALLOW_ASSIGN_ (EitherOfMatcherImpl< T >) private
template<typename T > testing::internal::EitherOfMatcherImpl< T >::GTEST_DISALLOW_ASSIGN_ (EitherOfMatcherImpl< T >) private
template<typename T > testing::internal::EitherOfMatcherImpl< T >::GTEST_DISALLOW_ASSIGN_ (EitherOfMatcherImpl< T >) private
template<typename T > virtual bool testing::internal::EitherOfMatcherImpl< T >::MatchAndExplain (T x, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< T >.
Definition at line 1685 of file gmock-matchers.h.
References testing::StringMatchResultListener::str().
{
     // If either matcher1_ or matcher2_ matches x, we just need to
     // explain why *one* of them matches.
     StringMatchResultListener listener1;
     if (matcher1_.MatchAndExplain(x, &listener1)) {
       *listener << listener1.str();
       return true;
     }
     StringMatchResultListener listener2;
     if (matcher2_.MatchAndExplain(x, &listener2)) {
       *listener << listener2.str();
       return true;
     }
     // Otherwise we need to explain why *both* of them fail.
     const internal::string s1 = listener1.str();
     const internal::string s2 = listener2.str();
     if (s1 == "") {
       *listener << s2;
     } else {
       *listener << s1;
       if (s2 != "") {
         *listener << ", and " << s2;
       }
     }
     return false;
   }
template<typename T > virtual bool testing::internal::EitherOfMatcherImpl< T >::MatchAndExplain (T x, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< T >.
Definition at line 1685 of file gmock-matchers.h.
References testing::Args(), GTEST_DISALLOW_ASSIGN_, and testing::StringMatchResultListener::str().
{
     // If either matcher1_ or matcher2_ matches x, we just need to
     // explain why *one* of them matches.
     StringMatchResultListener listener1;
     if (matcher1_.MatchAndExplain(x, &listener1)) {
       *listener << listener1.str();
       return true;
     }
     StringMatchResultListener listener2;
     if (matcher2_.MatchAndExplain(x, &listener2)) {
       *listener << listener2.str();
       return true;
     }
     // Otherwise we need to explain why *both* of them fail.
     const internal::string s1 = listener1.str();
     const internal::string s2 = listener2.str();
     if (s1 == "") {
       *listener << s2;
     } else {
       *listener << s1;
       if (s2 != "") {
         *listener << ", and " << s2;
       }
     }
     return false;
   }
template<typename T > virtual bool testing::internal::EitherOfMatcherImpl< T >::MatchAndExplain (T x, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< T >.
Definition at line 1685 of file gmock-matchers.h.
References testing::Args(), GTEST_DISALLOW_ASSIGN_, and testing::StringMatchResultListener::str().
{
     // If either matcher1_ or matcher2_ matches x, we just need to
     // explain why *one* of them matches.
     StringMatchResultListener listener1;
     if (matcher1_.MatchAndExplain(x, &listener1)) {
       *listener << listener1.str();
       return true;
     }
     StringMatchResultListener listener2;
     if (matcher2_.MatchAndExplain(x, &listener2)) {
       *listener << listener2.str();
       return true;
     }
     // Otherwise we need to explain why *both* of them fail.
     const internal::string s1 = listener1.str();
     const internal::string s2 = listener2.str();
     if (s1 == "") {
       *listener << s2;
     } else {
       *listener << s1;
       if (s2 != "") {
         *listener << ", and " << s2;
       }
     }
     return false;
   }
Member Data Documentation
template<typename T > const Matcher< T > testing::internal::EitherOfMatcherImpl< T >::matcher1_ private
Definition at line 1716 of file gmock-matchers.h.
template<typename T > const Matcher< T > testing::internal::EitherOfMatcherImpl< T >::matcher2_ private
Definition at line 1717 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h