proxygen: folly::SocketPair Class Reference
folly::SocketPair Class Reference
#include <SocketPair.h>
Public Types
enum Mode { BLOCKING, NONBLOCKING }
Public Member Functions
SocketPair (Mode mode=NONBLOCKING)
~SocketPair ()
int operator[] (int index) const
void closeFD0 ()
void closeFD1 ()
int extractFD0 ()
int extractFD1 ()
int extractFD (int index)
Private Attributes
int fds_ [2]
Detailed Description
Definition at line 21 of file SocketPair.h.
Member Enumeration Documentation
enum folly::SocketPair::Mode
Enumerator
BLOCKING
NONBLOCKING
Definition at line 23 of file SocketPair.h.
 { BLOCKING, NONBLOCKING };
Constructor & Destructor Documentation
folly::SocketPair::SocketPair (Mode mode = NONBLOCKING) explicit
Definition at line 29 of file SocketPair.cpp.
References fds_, NONBLOCKING, and folly::netops::socketpair().
{
   if (socketpair(PF_UNIX, SOCK_STREAM, 0, fds_) != 0) {
     throw std::runtime_error(folly::to<std::string>(
         "test::SocketPair: failed create socket pair", errno));
   }
   if (mode == NONBLOCKING) {
     if (fcntl(fds_[0], F_SETFL, O_NONBLOCK) != 0) {
       throw std::runtime_error(folly::to<std::string>(
           "test::SocketPair: failed to set non-blocking "
           "read mode",
           errno));
     }
     if (fcntl(fds_[1], F_SETFL, O_NONBLOCK) != 0) {
       throw std::runtime_error(folly::to<std::string>(
           "test::SocketPair: failed to set non-blocking "
           "write mode",
           errno));
     }
   }
 }
folly::SocketPair::~SocketPair ()
Definition at line 51 of file SocketPair.cpp.
References closeFD0(), and closeFD1().
{
   closeFD0();
   closeFD1();
 }
Member Function Documentation
void folly::SocketPair::closeFD0 ()
Definition at line 56 of file SocketPair.cpp.
References folly::netops::close(), and fds_.
Referenced by operator[](), and ~SocketPair().
{
   if (fds_[0] >= 0) {
     close(fds_[0]);
     fds_[0] = -1;
   }
 }
void folly::SocketPair::closeFD1 ()
Definition at line 63 of file SocketPair.cpp.
References folly::netops::close(), and fds_.
Referenced by operator[](), and ~SocketPair().
{
   if (fds_[1] >= 0) {
     close(fds_[1]);
     fds_[1] = -1;
   }
 }
int folly::SocketPair::extractFD (int index) inline
Definition at line 41 of file SocketPair.h.
References fds_.
Referenced by extractFD0(), and extractFD1().
{
     int fd = fds_[index];
     fds_[index] = -1;
     return fd;
   }
int folly::SocketPair::extractFD0 () inline
Definition at line 35 of file SocketPair.h.
References extractFD().
                    {
     return extractFD(0);
   }
int folly::SocketPair::extractFD1 () inline
Definition at line 38 of file SocketPair.h.
References extractFD().
                    {
     return extractFD(1);
   }
int folly::SocketPair::operator[] (int index) const inline
Definition at line 28 of file SocketPair.h.
References closeFD0(), closeFD1(), and fds_.
{
     return fds_[index];
   }
Member Data Documentation
int folly::SocketPair::fds_[2] private
Definition at line 48 of file SocketPair.h.
Referenced by closeFD0(), closeFD1(), extractFD(), operator[](), and SocketPair().
The documentation for this class was generated from the following files:
proxygen/folly/folly/io/async/test/SocketPair.h
proxygen/folly/folly/io/async/test/SocketPair.cpp