proxygen: MPMC< T > Class Template Reference
MPMC< T > Class Template Reference
Public Member Functions
MPMC (uint64_t capacity)
void enqueue (const T &v)
void enqueue (T &&v)
bool try_enqueue (const T &v)
bool try_enqueue (const T &&v)
template<typename Rep , typename Period >
bool try_enqueue_for (const T &v, const std::chrono::duration< Rep, Period > &duration)
void dequeue (T &item)
bool try_dequeue (T &item)
template<typename Rep , typename Period >
bool try_dequeue_for (T &item, const std::chrono::duration< Rep, Period > &duration)
MPMC ()
template<typename... Args>
void enqueue (Args &&...args)
void dequeue (T &item)
bool try_dequeue (T &item)
template<typename Rep , typename Period >
bool try_dequeue_for (T &item, const std::chrono::duration< Rep, Period > &duration) noexcept
Private Attributes
folly::MPMCQueue< T > q_
Detailed Description
template<typename T>
class MPMC< T >
Definition at line 428 of file DynamicBoundedQueueTest.cpp.
Constructor & Destructor Documentation
template<typename T > MPMC< T >::MPMC (uint64_t capacity) inline explicit
Definition at line 432 of file DynamicBoundedQueueTest.cpp.
 : q_(capacity) {}
template<typename T > MPMC< T >::MPMC () inline
Definition at line 400 of file UnboundedQueueTest.cpp.
References testing::Args().
 : q_(FLAGS_capacity) {}
Member Function Documentation
template<typename T > void MPMC< T >::dequeue (T & item) inline
Definition at line 407 of file UnboundedQueueTest.cpp.
{
     q_.blockingRead(item);
   }
template<typename T > void MPMC< T >::dequeue (T & item) inline
Definition at line 457 of file DynamicBoundedQueueTest.cpp.
{
     q_.blockingRead(item);
   }
template<typename T > template<typename... Args> void MPMC< T >::enqueue (Args &&... args) inline
Definition at line 403 of file UnboundedQueueTest.cpp.
{
     q_.blockingWrite(std::forward<Args>(args)...);
   }
template<typename T > void MPMC< T >::enqueue (const T & v) inline
Definition at line 434 of file DynamicBoundedQueueTest.cpp.
{
     q_.blockingWrite(v);
   }
template<typename T > void MPMC< T >::enqueue (T && v) inline
Definition at line 438 of file DynamicBoundedQueueTest.cpp.
References folly::gen::move.
                       {
     q_.blockingWrite(std::move(v));
   }
template<typename T > bool MPMC< T >::try_dequeue (T & item) inline
Definition at line 411 of file UnboundedQueueTest.cpp.
{
     return q_.read(item);
   }
template<typename T > bool MPMC< T >::try_dequeue (T & item) inline
Definition at line 461 of file DynamicBoundedQueueTest.cpp.
{
     return q_.read(item);
   }
template<typename T > template<typename Rep , typename Period > bool MPMC< T >::try_dequeue_for (T & item, const std::chrono::duration< Rep, Period > & duration) inline noexcept
Definition at line 416 of file UnboundedQueueTest.cpp.
References now().
{
     auto deadline = std::chrono::steady_clock::now() + duration;
     return q_.tryReadUntil(deadline, item);
   }
template<typename T > template<typename Rep , typename Period > bool MPMC< T >::try_dequeue_for (T & item, const std::chrono::duration< Rep, Period > & duration) inline
Definition at line 466 of file DynamicBoundedQueueTest.cpp.
References now().
{
     return q_.tryReadUntil(std::chrono::steady_clock::now() + duration, item);
   }
template<typename T > bool MPMC< T >::try_enqueue (const T & v) inline
Definition at line 442 of file DynamicBoundedQueueTest.cpp.
{
     return q_.write(v);
   }
template<typename T > bool MPMC< T >::try_enqueue (const T && v) inline
Definition at line 446 of file DynamicBoundedQueueTest.cpp.
References folly::gen::move.
{
     return q_.write(std::move(v));
   }
template<typename T > template<typename Rep , typename Period > bool MPMC< T >::try_enqueue_for (const T & v, const std::chrono::duration< Rep, Period > & duration) inline
Definition at line 451 of file DynamicBoundedQueueTest.cpp.
References now().
{
     return q_.tryWriteUntil(std::chrono::steady_clock::now() + duration, v);
   }
Member Data Documentation
template<typename T > folly::MPMCQueue< T > MPMC< T >::q_ private
Definition at line 429 of file DynamicBoundedQueueTest.cpp.
The documentation for this class was generated from the following files:
proxygen/folly/folly/concurrency/test/DynamicBoundedQueueTest.cpp
proxygen/folly/folly/concurrency/test/UnboundedQueueTest.cpp