proxygen: testing::gmock_matchers_test::PolymorphicIsEvenImpl Class Reference
testing::gmock_matchers_test::PolymorphicIsEvenImpl Class Reference
Public Member Functions
void DescribeTo (ostream *os) const
void DescribeNegationTo (ostream *os) const
template<typename T >
bool MatchAndExplain (const T &x, MatchResultListener *listener) const
void DescribeTo (ostream *os) const
void DescribeNegationTo (ostream *os) const
template<typename T >
bool MatchAndExplain (const T &x, MatchResultListener *listener) const
void DescribeTo (ostream *os) const
void DescribeNegationTo (ostream *os) const
template<typename T >
bool MatchAndExplain (const T &x, MatchResultListener *listener) const
Detailed Description
Definition at line 480 of file gmock-matchers_test.cc.
Member Function Documentation
void testing::gmock_matchers_test::PolymorphicIsEvenImpl::DescribeNegationTo (ostream * os) const inline
Definition at line 484 of file gmock-matchers_test.cc.
{
     *os << "is odd";
   }
void testing::gmock_matchers_test::PolymorphicIsEvenImpl::DescribeNegationTo (ostream * os) const inline
Definition at line 484 of file gmock-matchers_test.cc.
{
     *os << "is odd";
   }
void testing::gmock_matchers_test::PolymorphicIsEvenImpl::DescribeNegationTo (ostream * os) const inline
Definition at line 484 of file gmock-matchers_test.cc.
{
     *os << "is odd";
   }
void testing::gmock_matchers_test::PolymorphicIsEvenImpl::DescribeTo (ostream * os) const inline
Definition at line 482 of file gmock-matchers_test.cc.
 { *os << "is even"; }
void testing::gmock_matchers_test::PolymorphicIsEvenImpl::DescribeTo (ostream * os) const inline
Definition at line 482 of file gmock-matchers_test.cc.
 { *os << "is even"; }
void testing::gmock_matchers_test::PolymorphicIsEvenImpl::DescribeTo (ostream * os) const inline
Definition at line 482 of file gmock-matchers_test.cc.
 { *os << "is even"; }
template<typename T > bool testing::gmock_matchers_test::PolymorphicIsEvenImpl::MatchAndExplain (const T & x, MatchResultListener * listener) const inline
Definition at line 489 of file gmock-matchers_test.cc.
References testing::gmock_matchers_test::Describe(), testing::Eq(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testing::gmock_matchers_test::Explain(), testing::MakePolymorphicMatcher(), testing::internal::MatcherBase< T >::Matches(), testing::Not(), testing::gmock_matchers_test::PolymorphicIsEven(), testing::MatchResultListener::stream(), and testing::internal::TEST().
{
     // Verifies that we can stream to the listener directly.
     *listener << "% " << 2;
     if (listener->stream() != NULL) {
       // Verifies that we can stream to the listener's underlying stream
       // too.
       *listener->stream() << " == " << (x % 2);
     }
     return (x % 2) == 0;
   }
template<typename T > bool testing::gmock_matchers_test::PolymorphicIsEvenImpl::MatchAndExplain (const T & x, MatchResultListener * listener) const inline
Definition at line 489 of file gmock-matchers_test.cc.
References testing::MatchResultListener::stream().
{
     // Verifies that we can stream to the listener directly.
     *listener << "% " << 2;
     if (listener->stream() != NULL) {
       // Verifies that we can stream to the listener's underlying stream
       // too.
       *listener->stream() << " == " << (x % 2);
     }
     return (x % 2) == 0;
   }
template<typename T > bool testing::gmock_matchers_test::PolymorphicIsEvenImpl::MatchAndExplain (const T & x, MatchResultListener * listener) const inline
Definition at line 489 of file gmock-matchers_test.cc.
References testing::gmock_matchers_test::Describe(), testing::Eq(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testing::gmock_matchers_test::Explain(), testing::MakePolymorphicMatcher(), testing::internal::MatcherBase< T >::Matches(), testing::Not(), testing::gmock_matchers_test::PolymorphicIsEven(), testing::MatchResultListener::stream(), and testing::internal::TEST().
{
     // Verifies that we can stream to the listener directly.
     *listener << "% " << 2;
     if (listener->stream() != NULL) {
       // Verifies that we can stream to the listener's underlying stream
       // too.
       *listener->stream() << " == " << (x % 2);
     }
     return (x % 2) == 0;
   }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-matchers_test.cc