proxygen: testing::internal::DefaultPerThreadTestPartResultReporter Class Reference
testing::internal::DefaultPerThreadTestPartResultReporter Class Reference
#include <gtest-internal-inl.h>
Public Member Functions
DefaultPerThreadTestPartResultReporter (UnitTestImpl *unit_test)
virtual void ReportTestPartResult (const TestPartResult &result)
DefaultPerThreadTestPartResultReporter (UnitTestImpl *unit_test)
virtual void ReportTestPartResult (const TestPartResult &result)
DefaultPerThreadTestPartResultReporter (UnitTestImpl *unit_test)
virtual void ReportTestPartResult (const TestPartResult &result)
Public Member Functions inherited from testing::TestPartResultReporterInterface
virtual ~TestPartResultReporterInterface ()
virtual ~TestPartResultReporterInterface ()
virtual ~TestPartResultReporterInterface ()
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (DefaultPerThreadTestPartResultReporter)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (DefaultPerThreadTestPartResultReporter)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (DefaultPerThreadTestPartResultReporter)
Private Attributes
UnitTestImpl *const unit_test_
Detailed Description
Definition at line 481 of file gtest-internal-inl.h.
Constructor & Destructor Documentation
testing::internal::DefaultPerThreadTestPartResultReporter::DefaultPerThreadTestPartResultReporter (UnitTestImpl * unit_test) explicit
Definition at line 695 of file gtest.cc.
Referenced by testing::internal::ShouldRunTestCase().
                              : unit_test_(unit_test) {}
testing::internal::DefaultPerThreadTestPartResultReporter::DefaultPerThreadTestPartResultReporter (UnitTestImpl * unit_test) explicit
testing::internal::DefaultPerThreadTestPartResultReporter::DefaultPerThreadTestPartResultReporter (UnitTestImpl * unit_test) explicit
Member Function Documentation
testing::internal::DefaultPerThreadTestPartResultReporter::GTEST_DISALLOW_COPY_AND_ASSIGN_ (DefaultPerThreadTestPartResultReporter) private
testing::internal::DefaultPerThreadTestPartResultReporter::GTEST_DISALLOW_COPY_AND_ASSIGN_ (DefaultPerThreadTestPartResultReporter) private
testing::internal::DefaultPerThreadTestPartResultReporter::GTEST_DISALLOW_COPY_AND_ASSIGN_ (DefaultPerThreadTestPartResultReporter) private
void testing::internal::DefaultPerThreadTestPartResultReporter::ReportTestPartResult (const TestPartResult & result) virtual
Implements testing::TestPartResultReporterInterface.
Definition at line 698 of file gtest.cc.
References testing::internal::UnitTestImpl::GetGlobalTestPartResultReporter(), testing::TestPartResultReporterInterface::ReportTestPartResult(), and unit_test_.
Referenced by testing::internal::ShouldRunTestCase().
{
   unit_test_->GetGlobalTestPartResultReporter()->ReportTestPartResult(result);
 }
virtual void testing::internal::DefaultPerThreadTestPartResultReporter::ReportTestPartResult (const TestPartResult & result) virtual
Implements testing::TestPartResultReporterInterface.
virtual void testing::internal::DefaultPerThreadTestPartResultReporter::ReportTestPartResult (const TestPartResult & result) virtual
Implements testing::TestPartResultReporterInterface.
Member Data Documentation
UnitTestImpl *const testing::internal::DefaultPerThreadTestPartResultReporter::unit_test_ private
Definition at line 490 of file gtest-internal-inl.h.
Referenced by ReportTestPartResult().
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest-internal-inl.h
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest.cc