proxygen: testing::internal::ReturnAction< R >::Impl< ByMoveWrapper< R_ >, F > Class Template Reference
testing::internal::ReturnAction< R >::Impl< ByMoveWrapper< R_ >, F > Class Template Reference
Public Types
typedef Function< F >::Result Result
typedef Function< F >::ArgumentTuple ArgumentTuple
typedef Function< F >::Result Result
typedef Function< F >::ArgumentTuple ArgumentTuple
typedef Function< F >::Result Result
typedef Function< F >::ArgumentTuple ArgumentTuple
Public Types inherited from testing::ActionInterface< F >
typedef internal::Function< F >::Result Result
typedef internal::Function< F >::ArgumentTuple ArgumentTuple
typedef internal::Function< F >::Result Result
typedef internal::Function< F >::ArgumentTuple ArgumentTuple
typedef internal::Function< F >::Result Result
typedef internal::Function< F >::ArgumentTuple ArgumentTuple
Public Member Functions
Impl (const linked_ptr< R > &wrapper)
virtual Result Perform (const ArgumentTuple &)
Impl (const linked_ptr< R > &wrapper)
virtual Result Perform (const ArgumentTuple &)
Impl (const linked_ptr< R > &wrapper)
virtual Result Perform (const ArgumentTuple &)
Public Member Functions inherited from testing::ActionInterface< F >
ActionInterface ()
virtual ~ActionInterface ()
ActionInterface ()
virtual ~ActionInterface ()
ActionInterface ()
virtual ~ActionInterface ()
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (Impl)
GTEST_DISALLOW_ASSIGN_ (Impl)
GTEST_DISALLOW_ASSIGN_ (Impl)
Private Attributes
bool performed_
const linked_ptr< R > wrapper_
Detailed Description
template<typename R>
template<typename R_, typename F>
class testing::internal::ReturnAction< R >::Impl< ByMoveWrapper< R_ >, F >
Definition at line 595 of file gmock-actions.h.
Member Typedef Documentation
template<typename R > template<typename R_ , typename F > typedef Function<F>::ArgumentTuple testing::internal::ReturnAction< R >::Impl< ByMoveWrapper< R_ >, F >::ArgumentTuple
Definition at line 598 of file gmock-actions.h.
template<typename R > template<typename R_ , typename F > typedef Function<F>::ArgumentTuple testing::internal::ReturnAction< R >::Impl< ByMoveWrapper< R_ >, F >::ArgumentTuple
Definition at line 598 of file gmock-actions.h.
template<typename R > template<typename R_ , typename F > typedef Function<F>::ArgumentTuple testing::internal::ReturnAction< R >::Impl< ByMoveWrapper< R_ >, F >::ArgumentTuple
Definition at line 598 of file gmock-actions.h.
template<typename R > template<typename R_ , typename F > typedef Function<F>::Result testing::internal::ReturnAction< R >::Impl< ByMoveWrapper< R_ >, F >::Result
Definition at line 597 of file gmock-actions.h.
template<typename R > template<typename R_ , typename F > typedef Function<F>::Result testing::internal::ReturnAction< R >::Impl< ByMoveWrapper< R_ >, F >::Result
Definition at line 597 of file gmock-actions.h.
template<typename R > template<typename R_ , typename F > typedef Function<F>::Result testing::internal::ReturnAction< R >::Impl< ByMoveWrapper< R_ >, F >::Result
Definition at line 597 of file gmock-actions.h.
Constructor & Destructor Documentation
template<typename R > template<typename R_ , typename F > testing::internal::ReturnAction< R >::Impl< ByMoveWrapper< R_ >, F >::Impl (const linked_ptr< R > & wrapper) inline explicit
Definition at line 600 of file gmock-actions.h.
         : performed_(false), wrapper_(wrapper) {}
template<typename R > template<typename R_ , typename F > testing::internal::ReturnAction< R >::Impl< ByMoveWrapper< R_ >, F >::Impl (const linked_ptr< R > & wrapper) inline explicit
Definition at line 600 of file gmock-actions.h.
         : performed_(false), wrapper_(wrapper) {}
template<typename R > template<typename R_ , typename F > testing::internal::ReturnAction< R >::Impl< ByMoveWrapper< R_ >, F >::Impl (const linked_ptr< R > & wrapper) inline explicit
Definition at line 600 of file gmock-actions.h.
         : performed_(false), wrapper_(wrapper) {}
Member Function Documentation
template<typename R > template<typename R_ , typename F > testing::internal::ReturnAction< R >::Impl< ByMoveWrapper< R_ >, F >::GTEST_DISALLOW_ASSIGN_ (Impl< ByMoveWrapper< R_ >, F >) private
template<typename R > template<typename R_ , typename F > testing::internal::ReturnAction< R >::Impl< ByMoveWrapper< R_ >, F >::GTEST_DISALLOW_ASSIGN_ (Impl< ByMoveWrapper< R_ >, F >) private
template<typename R > template<typename R_ , typename F > testing::internal::ReturnAction< R >::Impl< ByMoveWrapper< R_ >, F >::GTEST_DISALLOW_ASSIGN_ (Impl< ByMoveWrapper< R_ >, F >) private
template<typename R > template<typename R_ , typename F > virtual Result testing::internal::ReturnAction< R >::Impl< ByMoveWrapper< R_ >, F >::Perform (const ArgumentTuple &) inline virtual
Implements testing::ActionInterface< F >.
Definition at line 603 of file gmock-actions.h.
References GTEST_CHECK_, and testing::internal::move().
{
       GTEST_CHECK_(!performed_)
           << "A ByMove() action should only be performed once.";
       performed_ = true;
       return internal::move(wrapper_->payload);
     }
template<typename R > template<typename R_ , typename F > virtual Result testing::internal::ReturnAction< R >::Impl< ByMoveWrapper< R_ >, F >::Perform (const ArgumentTuple &) inline virtual
Implements testing::ActionInterface< F >.
Definition at line 603 of file gmock-actions.h.
References GTEST_CHECK_, GTEST_DISALLOW_ASSIGN_, and testing::internal::move().
{
       GTEST_CHECK_(!performed_)
           << "A ByMove() action should only be performed once.";
       performed_ = true;
       return internal::move(wrapper_->payload);
     }
template<typename R > template<typename R_ , typename F > virtual Result testing::internal::ReturnAction< R >::Impl< ByMoveWrapper< R_ >, F >::Perform (const ArgumentTuple &) inline virtual
Implements testing::ActionInterface< F >.
Definition at line 603 of file gmock-actions.h.
References GTEST_CHECK_, GTEST_DISALLOW_ASSIGN_, and testing::internal::move().
{
       GTEST_CHECK_(!performed_)
           << "A ByMove() action should only be performed once.";
       performed_ = true;
       return internal::move(wrapper_->payload);
     }
Member Data Documentation
template<typename R > template<typename R_ , typename F > bool testing::internal::ReturnAction< R >::Impl< ByMoveWrapper< R_ >, F >::performed_ private
Definition at line 611 of file gmock-actions.h.
template<typename R > template<typename R_ , typename F > const linked_ptr< R > testing::internal::ReturnAction< R >::Impl< ByMoveWrapper< R_ >, F >::wrapper_ private
Definition at line 612 of file gmock-actions.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-actions.h