proxygen: folly::observer::SimpleObservable< T > Class Template Reference
folly::observer::SimpleObservable< T > Class Template Reference
#include <SimpleObservable.h>
Classes
struct Context
struct Wrapper
Public Member Functions
SimpleObservable (T value)
SimpleObservable (std::shared_ptr< const T > value)
void setValue (T value)
void setValue (std::shared_ptr< const T > value)
Observer< T > getObserver ()
Private Attributes
std::shared_ptr< Context > context_
std::once_flag observerInit_
folly::Optional< Observer< T > > observer_
Detailed Description
template<typename T>
class folly::observer::SimpleObservable< T >
Definition at line 26 of file SimpleObservable.h.
Constructor & Destructor Documentation
template<typename T > folly::observer::SimpleObservable< T >::SimpleObservable (T value) explicit
Definition at line 24 of file SimpleObservable-inl.h.
References folly::gen::move, and folly::observer::SimpleObservable< T >::setValue().
     : context_(std::make_shared<Context>()) {
   setValue(std::move(value));
 }
template<typename T > folly::observer::SimpleObservable< T >::SimpleObservable (std::shared_ptr< const T > value) explicit
Definition at line 30 of file SimpleObservable-inl.h.
References folly::gen::move, and folly::observer::SimpleObservable< T >::setValue().
     : context_(std::make_shared<Context>()) {
   setValue(std::move(value));
 }
Member Function Documentation
template<typename T > Observer< T > folly::observer::SimpleObservable< T >::getObserver ()
Definition at line 72 of file SimpleObservable-inl.h.
References folly::call_once(), folly::observer::SimpleObservable< T >::Wrapper< T >::context, folly::observer::SimpleObservable< T >::context_, folly::gen::move, folly::observer::SimpleObservable< T >::observer_, and folly::observer::SimpleObservable< T >::observerInit_.
Referenced by TEST().
{
   std::call_once(observerInit_, [&]() {
     SimpleObservable<T>::Wrapper wrapper;
     wrapper.context = context_;
     ObserverCreator<SimpleObservable<T>::Wrapper> creator(std::move(wrapper));
     observer_ = std::move(creator).getObserver();
   });
   return *observer_;
 }
template<typename T > void folly::observer::SimpleObservable< T >::setValue (T value)
Definition at line 36 of file SimpleObservable-inl.h.
References folly::gen::move.
Referenced by folly::observer::SimpleObservable< T >::SimpleObservable(), and TEST().
{
   setValue(std::make_shared<const T>(std::move(value)));
 }
template<typename T > void folly::observer::SimpleObservable< T >::setValue (std::shared_ptr< const T > value)
Definition at line 41 of file SimpleObservable-inl.h.
References folly::observer::SimpleObservable< T >::context_.
{
   context_->value_.swap(value);
   context_->callback_.withWLock([](folly::Function<void()>& callback) {
     if (callback) {
       callback();
     }
   });
 }
Member Data Documentation
template<typename T> std::shared_ptr<Context> folly::observer::SimpleObservable< T >::context_ private
Definition at line 41 of file SimpleObservable.h.
Referenced by folly::observer::SimpleObservable< T >::getObserver(), and folly::observer::SimpleObservable< T >::setValue().
template<typename T> folly::Optional<Observer<T> > folly::observer::SimpleObservable< T >::observer_ private
Definition at line 45 of file SimpleObservable.h.
Referenced by folly::observer::SimpleObservable< T >::getObserver().
template<typename T> std::once_flag folly::observer::SimpleObservable< T >::observerInit_ private
Definition at line 44 of file SimpleObservable.h.
Referenced by folly::observer::SimpleObservable< T >::getObserver().
The documentation for this class was generated from the following files:
proxygen/folly/folly/experimental/observer/SimpleObservable.h
proxygen/folly/folly/experimental/observer/SimpleObservable-inl.h