proxygen: folly::exception_tracer::StackTraceStack Class Reference
folly::exception_tracer::StackTraceStack Class Reference
#include <StackTrace.h>
Classes
class Node
Public Member Functions
bool pushCurrent ()
bool pop ()
bool moveTopFrom (StackTraceStack &other)
void clear ()
bool empty () const
StackTrace * top ()
StackTrace * next (StackTrace *p)
Private Member Functions
void checkGuard () const
Private Attributes
uintptr_t guard1_
Node * top_
uintptr_t guard2_
Detailed Description
Definition at line 37 of file StackTrace.h.
Member Function Documentation
void folly::exception_tracer::StackTraceStack::checkGuard () const inline private
Definition at line 87 of file StackTrace.h.
Referenced by clear(), moveTopFrom(), next(), pop(), pushCurrent(), and top().
{
 #ifndef NDEBUG
     assert(guard1_ == 0 && guard2_ == 0);
 #endif
   }
void folly::exception_tracer::StackTraceStack::clear ()
Clear the stack.
Definition at line 94 of file StackTrace.cpp.
References checkGuard(), pop(), and top_.
Referenced by getExceptionStackTraceStack().
{
   checkGuard();
   while (top_) {
     pop();
   }
 }
bool folly::exception_tracer::StackTraceStack::empty () const inline
Is the stack empty?
Definition at line 69 of file StackTrace.h.
References cpp.ast::next(), and folly::pushmi::top.
                      {
     return !top_;
   }
bool folly::exception_tracer::StackTraceStack::moveTopFrom (StackTraceStack & other)
Move the top stack trace from other onto this. Returns true on success, false on failure (other was empty).
Definition at line 81 of file StackTrace.cpp.
References checkGuard(), folly::exception_tracer::StackTraceStack::Node::next, and top_.
Referenced by getExceptionStackTraceStack().
{
   checkGuard();
   if (!other.top_) {
     return false;
   }
   auto node = other.top_;
   other.top_ = node->next;
   node->next = top_;
   top_ = node;
   return true;
 }
StackTrace * folly::exception_tracer::StackTraceStack::next (StackTrace * p)
Return the stack trace following p, or nullptr if p is the bottom of the stack.
Definition at line 106 of file StackTrace.cpp.
References checkGuard(), and folly::exception_tracer::StackTraceStack::Node::next.
Referenced by folly::exception_tracer::getCurrentExceptions().
{
   checkGuard();
   assert(p);
   return static_cast<Node*>(p)->next;
 }
bool folly::exception_tracer::StackTraceStack::pop ()
Pop the top stack trace from the stack. Returns true on success, false on failure (stack was empty).
Definition at line 69 of file StackTrace.cpp.
References checkGuard(), folly::exception_tracer::StackTraceStack::Node::deallocate(), folly::exception_tracer::StackTraceStack::Node::next, and top_.
Referenced by clear().
{
   checkGuard();
   if (!top_) {
     return false;
   }
   auto node = top_;
   top_ = node->next;
   node->deallocate();
   return true;
 }
bool folly::exception_tracer::StackTraceStack::pushCurrent ()
Push the current stack trace onto the stack. Returns false on failure (not enough memory, getting stack trace failed), true on success.
Definition at line 49 of file StackTrace.cpp.
References folly::exception_tracer::StackTraceStack::Node::allocate(), checkGuard(), folly::symbolizer::getStackTrace(), folly::exception_tracer::kMaxFrames, and top_.
{
   checkGuard();
   auto node = Node::allocate();
   if (!node) {
     // cannot allocate memory
     return false;
   }
   ssize_t n = folly::symbolizer::getStackTrace(node->addresses, kMaxFrames);
   if (n == -1) {
     node->deallocate();
     return false;
   }
   node->frameCount = n;
   node->next = top_;
   top_ = node;
   return true;
 }
StackTrace * folly::exception_tracer::StackTraceStack::top ()
Return the top stack trace, or nullptr if the stack is empty.
Definition at line 101 of file StackTrace.cpp.
References checkGuard(), and top_.
Referenced by folly::exception_tracer::getCurrentExceptions().
{
   checkGuard();
   return top_;
 }
Member Data Documentation
uintptr_t folly::exception_tracer::StackTraceStack::guard1_ private
Definition at line 94 of file StackTrace.h.
uintptr_t folly::exception_tracer::StackTraceStack::guard2_ private
Definition at line 98 of file StackTrace.h.
Node* folly::exception_tracer::StackTraceStack::top_ private
Definition at line 96 of file StackTrace.h.
Referenced by clear(), moveTopFrom(), pop(), pushCurrent(), and top().
The documentation for this class was generated from the following files:
proxygen/folly/folly/experimental/exception_tracer/StackTrace.h
proxygen/folly/folly/experimental/exception_tracer/StackTrace.cpp