proxygen: folly::hazptr_obj< Atom > Class Template Reference
folly::hazptr_obj< Atom > Class Template Reference
#include <Hazptr-fwd.h>
Public Member Functions
hazptr_obj () noexcept
hazptr_obj (const hazptr_obj< Atom > &) noexcept
hazptr_obj (hazptr_obj< Atom > &&) noexcept
hazptr_obj< Atom > & operator= (const hazptr_obj< Atom > &) noexcept
hazptr_obj< Atom > & operator= (hazptr_obj< Atom > &&) noexcept
Private Types
using ReclaimFnPtr = void(*)(hazptr_obj< Atom > *, hazptr_obj_list< Atom > &)
Private Member Functions
hazptr_obj< Atom > * next () const noexcept
void set_next (hazptr_obj *obj) noexcept
ReclaimFnPtr reclaim () noexcept
const void * raw_ptr () const
void pre_retire_check () noexcept
void push_to_retired (hazptr_domain< Atom > &domain)
FOLLY_NOINLINE void pre_retire_check_fail () noexcept
Private Attributes
ReclaimFnPtr reclaim_
hazptr_obj< Atom > * next_
Friends
template<template< typename > class>
class hazptr_domain
template<typename , template< typename > class, typename >
class hazptr_obj_base
template<typename , template< typename > class, typename >
class hazptr_obj_base_linked
template<template< typename > class>
class hazptr_obj_list
template<template< typename > class>
class hazptr_priv
class hazptr_domain< Atom >
template<typename , template< typename > class, typename >
class hazptr_obj_base_refcounted
class hazptr_priv< Atom >
template<typename , template< typename > class, typename >
class hazptr_obj_base
Detailed Description
template<template< typename > class Atom>
class folly::hazptr_obj< Atom >
Classes related to objects protected by hazard pointers. Defined in HazptrObj.hhazptr_obj
hazptr_obj
Object protected by hazard pointers.
Definition at line 51 of file Hazptr-fwd.h.
Member Typedef Documentation
template<template< typename > class Atom> using folly::hazptr_obj< Atom >::ReclaimFnPtr = void (*)(hazptr_obj<Atom>*, hazptr_obj_list<Atom>&) private
Definition at line 41 of file HazptrObj.h.
Constructor & Destructor Documentation
template<template< typename > class Atom> folly::hazptr_obj< Atom >::hazptr_obj () inline noexcept
Constructors
Definition at line 62 of file HazptrObj.h.
 : next_(this) {}
template<template< typename > class Atom> folly::hazptr_obj< Atom >::hazptr_obj (const hazptr_obj< Atom > &) inline noexcept
Definition at line 64 of file HazptrObj.h.
 : next_(this) {}
template<template< typename > class Atom> folly::hazptr_obj< Atom >::hazptr_obj (hazptr_obj< Atom > &&) inline noexcept
Definition at line 66 of file HazptrObj.h.
 : next_(this) {}
Member Function Documentation
template<template< typename > class Atom> hazptr_obj<Atom>* folly::hazptr_obj< Atom >::next () const inline private noexcept
Definition at line 86 of file HazptrObj.h.
References folly::hazptr_obj< Atom >::next_.
Referenced by folly::hazptr_domain< DeterministicAtomic >::bulk_lookup_and_reclaim().
{
     return next_;
   }
template<template< typename > class Atom> hazptr_obj<Atom>& folly::hazptr_obj< Atom >::operator= (const hazptr_obj< Atom > &) inline noexcept
Copy operator
Definition at line 69 of file HazptrObj.h.
{
     return *this;
   }
template<template< typename > class Atom> hazptr_obj<Atom>& folly::hazptr_obj< Atom >::operator= (hazptr_obj< Atom > &&) inline noexcept
Move operator
Definition at line 74 of file HazptrObj.h.
{
     return *this;
   }
template<template< typename > class Atom> void folly::hazptr_obj< Atom >::pre_retire_check () inline private noexcept
Definition at line 102 of file HazptrObj.h.
References folly::hazptr_obj< Atom >::pre_retire_check_fail().
Referenced by folly::hazptr_obj_base< Node, Atom >::pre_retire().
{
     // Only for catching misuse bugs like double retire
     if (next_ != this) {
       pre_retire_check_fail();
     }
   }
template<template< typename > class Atom> FOLLY_NOINLINE void folly::hazptr_obj< Atom >::pre_retire_check_fail () inline private noexcept
Definition at line 120 of file HazptrObj.h.
References Atom.
Referenced by folly::hazptr_obj< Atom >::pre_retire_check().
{
     CHECK_EQ(next_, this);
   }
template<template< typename > class Atom> void folly::hazptr_obj< Atom >::push_to_retired (hazptr_domain< Atom > & domain) inline private
Definition at line 109 of file HazptrObj.h.
References folly::hazptr_domain_push_retired(), and folly::hazptr_domain< Atom >::shutdown_.
Referenced by folly::hazptr_obj_base< Node, Atom >::retire().
{
 #if FOLLY_HAZPTR_THR_LOCAL
     if (&domain == &default_hazptr_domain<Atom>() && !domain.shutdown_) {
       hazptr_priv_tls<Atom>().push(this);
       return;
     }
 #endif
     hazptr_obj_list<Atom> l(this);
     hazptr_domain_push_retired(l, true, domain);
   }
template<template< typename > class Atom> const void* folly::hazptr_obj< Atom >::raw_ptr () const inline private
Definition at line 98 of file HazptrObj.h.
Referenced by folly::hazptr_domain< DeterministicAtomic >::bulk_lookup_and_reclaim().
{
     return this;
   }
template<template< typename > class Atom> ReclaimFnPtr folly::hazptr_obj< Atom >::reclaim () inline private noexcept
Definition at line 94 of file HazptrObj.h.
References folly::hazptr_obj< Atom >::reclaim_.
Referenced by folly::hazptr_domain< DeterministicAtomic >::bulk_lookup_and_reclaim().
{
     return reclaim_;
   }
template<template< typename > class Atom> void folly::hazptr_obj< Atom >::set_next (hazptr_obj< Atom > * obj) inline private noexcept
Definition at line 90 of file HazptrObj.h.
{
     next_ = obj;
   }
Friends And Related Function Documentation
template<template< typename > class Atom> template<template< typename > class> friend class hazptr_domain friend
Definition at line 44 of file HazptrObj.h.
template<template< typename > class Atom> friend class hazptr_domain< Atom > friend
Definition at line 79 of file HazptrObj.h.
template<template< typename > class Atom> template<typename , template< typename > class, typename > friend class hazptr_obj_base friend
Definition at line 46 of file HazptrObj.h.
template<template< typename > class Atom> template<typename , template< typename > class, typename > class hazptr_obj_base () friend
Definition at line 81 of file HazptrObj.h.
template<template< typename > class Atom> template<typename , template< typename > class, typename > friend class hazptr_obj_base_linked friend
Definition at line 48 of file HazptrObj.h.
template<template< typename > class Atom> template<typename , template< typename > class, typename > friend class hazptr_obj_base_refcounted friend
Definition at line 83 of file HazptrObj.h.
template<template< typename > class Atom> template<template< typename > class> friend class hazptr_obj_list friend
Definition at line 50 of file HazptrObj.h.
template<template< typename > class Atom> template<template< typename > class> friend class hazptr_priv friend
Definition at line 52 of file HazptrObj.h.
template<template< typename > class Atom> friend class hazptr_priv< Atom > friend
Definition at line 84 of file HazptrObj.h.
Member Data Documentation
template<template< typename > class Atom> hazptr_obj<Atom>* folly::hazptr_obj< Atom >::next_ private
Definition at line 55 of file HazptrObj.h.
Referenced by folly::hazptr_obj< Atom >::next().
template<template< typename > class Atom> ReclaimFnPtr folly::hazptr_obj< Atom >::reclaim_ private
Definition at line 54 of file HazptrObj.h.
Referenced by folly::hazptr_obj< Atom >::reclaim(), and folly::hazptr_obj_base< Node, Atom >::set_reclaim().
The documentation for this class was generated from the following files:
proxygen/folly/folly/synchronization/Hazptr-fwd.h
proxygen/folly/folly/synchronization/HazptrObj.h