proxygen: testing::internal::linked_ptr_internal Class Reference
testing::internal::linked_ptr_internal Class Reference
#include <gtest-linked_ptr.h>
Public Member Functions
void join_new ()
void join (linked_ptr_internal const *ptr) GTEST_LOCK_EXCLUDED_(g_linked_ptr_mutex)
bool depart () GTEST_LOCK_EXCLUDED_(g_linked_ptr_mutex)
void join_new ()
void join (linked_ptr_internal const *ptr) GTEST_LOCK_EXCLUDED_(g_linked_ptr_mutex)
bool depart () GTEST_LOCK_EXCLUDED_(g_linked_ptr_mutex)
void join_new ()
void join (linked_ptr_internal const *ptr) GTEST_LOCK_EXCLUDED_(g_linked_ptr_mutex)
bool depart () GTEST_LOCK_EXCLUDED_(g_linked_ptr_mutex)
Private Attributes
linked_ptr_internal const * next_
Detailed Description
Definition at line 89 of file gtest-linked_ptr.h.
Member Function Documentation
bool testing::internal::linked_ptr_internal::depart () inline
Definition at line 125 of file gtest-linked_ptr.h.
References folly::detail::lock(), and next_.
Referenced by testing::internal::linked_ptr< const testing::MatcherInterface< const internal::string & > >::depart(), testing::internal::linked_ptr< const testing::MatcherInterface< const internal::string & > >::operator=(), testing::internal::linked_ptr< const testing::MatcherInterface< const internal::string & > >::reset(), and testing::internal::linked_ptr< const testing::MatcherInterface< const internal::string & > >::~linked_ptr().
{
     MutexLock lock(&g_linked_ptr_mutex);
     if (next_ == this) return true;
     linked_ptr_internal const* p = next_;
     while (p->next_ != this) {
       assert(p->next_ != next_ &&
              "Trying to depart() a linked ring we are not in. "
              "Is GMock thread safety enabled?");
       p = p->next_;
     }
     p->next_ = next_;
     return false;
   }
bool testing::internal::linked_ptr_internal::depart () inline
Definition at line 125 of file gtest-linked_ptr.h.
References folly::detail::lock(), and next_.
{
     MutexLock lock(&g_linked_ptr_mutex);
     if (next_ == this) return true;
     linked_ptr_internal const* p = next_;
     while (p->next_ != this) {
       assert(p->next_ != next_ &&
              "Trying to depart() a linked ring we are not in. "
              "Is GMock thread safety enabled?");
       p = p->next_;
     }
     p->next_ = next_;
     return false;
   }
bool testing::internal::linked_ptr_internal::depart () inline
Definition at line 125 of file gtest-linked_ptr.h.
References folly::detail::lock(), and next_.
{
     MutexLock lock(&g_linked_ptr_mutex);
     if (next_ == this) return true;
     linked_ptr_internal const* p = next_;
     while (p->next_ != this) {
       assert(p->next_ != next_ &&
              "Trying to depart() a linked ring we are not in. "
              "Is GMock thread safety enabled?");
       p = p->next_;
     }
     p->next_ = next_;
     return false;
   }
void testing::internal::linked_ptr_internal::join (linked_ptr_internal const * ptr) inline
Definition at line 108 of file gtest-linked_ptr.h.
References folly::detail::lock(), next_, and ptr.
{
     MutexLock lock(&g_linked_ptr_mutex);
     linked_ptr_internal const* p = ptr;
     while (p->next_ != ptr) {
       assert(p->next_ != this &&
              "Trying to join() a linked ring we are already in. "
              "Is GMock thread safety enabled?");
       p = p->next_;
     }
     p->next_ = this;
     next_ = ptr;
   }
void testing::internal::linked_ptr_internal::join (linked_ptr_internal const * ptr) inline
Definition at line 108 of file gtest-linked_ptr.h.
References folly::detail::lock(), next_, and ptr.
{
     MutexLock lock(&g_linked_ptr_mutex);
     linked_ptr_internal const* p = ptr;
     while (p->next_ != ptr) {
       assert(p->next_ != this &&
              "Trying to join() a linked ring we are already in. "
              "Is GMock thread safety enabled?");
       p = p->next_;
     }
     p->next_ = this;
     next_ = ptr;
   }
void testing::internal::linked_ptr_internal::join (linked_ptr_internal const * ptr) inline
Definition at line 108 of file gtest-linked_ptr.h.
References folly::detail::lock(), next_, and ptr.
Referenced by testing::internal::linked_ptr< const testing::MatcherInterface< const internal::string & > >::copy().
{
     MutexLock lock(&g_linked_ptr_mutex);
     linked_ptr_internal const* p = ptr;
     while (p->next_ != ptr) {
       assert(p->next_ != this &&
              "Trying to join() a linked ring we are already in. "
              "Is GMock thread safety enabled?");
       p = p->next_;
     }
     p->next_ = this;
     next_ = ptr;
   }
void testing::internal::linked_ptr_internal::join_new () inline
Definition at line 92 of file gtest-linked_ptr.h.
References next_.
                   {
     next_ = this;
   }
void testing::internal::linked_ptr_internal::join_new () inline
Definition at line 92 of file gtest-linked_ptr.h.
References next_.
Referenced by testing::internal::linked_ptr< const testing::MatcherInterface< const internal::string & > >::capture(), and testing::internal::linked_ptr< const testing::MatcherInterface< const internal::string & > >::copy().
                   {
     next_ = this;
   }
void testing::internal::linked_ptr_internal::join_new () inline
Definition at line 92 of file gtest-linked_ptr.h.
References next_.
                   {
     next_ = this;
   }
Member Data Documentation
linked_ptr_internal const * testing::internal::linked_ptr_internal::next_ mutable private
Definition at line 142 of file gtest-linked_ptr.h.
Referenced by depart(), join(), and join_new().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/internal/gtest-linked_ptr.h