proxygen: folly::fibers::Baton::Waiter Class Reference
folly::fibers::Baton::Waiter Class Reference abstract
#include <Baton.h>
Public Member Functions
virtual void post ()=0
virtual ~Waiter ()
Detailed Description
Definition at line 44 of file Baton.h.
Constructor & Destructor Documentation
virtual folly::fibers::Baton::Waiter::~Waiter () inline virtual
Definition at line 48 of file Baton.h.
References folly::fibers::Baton::Baton(), folly::pushmi::__adl::noexcept(), and folly::fibers::Baton::~Baton().
 {}
Member Function Documentation
virtual void folly::fibers::Baton::Waiter::post () pure virtual
Implemented in folly::fibers::Baton::FiberWaiter.
Referenced by folly::fibers::Baton::setWaiter(), and folly::fibers::Baton::timed_wait().
The documentation for this class was generated from the following file:
proxygen/folly/folly/fibers/Baton.h