proxygen: wangle::StaticPipeline< R, W, Handler, Handlers... > Class Template Reference
wangle::StaticPipeline< R, W, Handler, Handlers... > Class Template Reference
#include <StaticPipeline.h>
Public Types
using Ptr = std::shared_ptr< StaticPipeline >
Public Member Functions
~StaticPipeline () override
Static Public Member Functions
template<class... HandlerArgs>
static Ptr create (HandlerArgs &&...handlers)
Protected Member Functions
template<class... HandlerArgs>
StaticPipeline (HandlerArgs &&...handlers)
template<class HandlerArg , class... HandlerArgs>
StaticPipeline (bool isFirst, HandlerArg &&handler, HandlerArgs &&...handlers)
void initialize ()
Private Member Functions
template<class HandlerArg >
std::enable_if< std::is_same< typename std::remove_reference< HandlerArg >::type, Handler >::value >::type setHandler (HandlerArg &&arg)
template<class HandlerArg >
std::enable_if< std::is_same< typename std::decay< HandlerArg >::type, std::shared_ptr< Handler > >::value >::type setHandler (HandlerArg &&arg)
template<class HandlerArg >
std::enable_if< std::is_same< typename std::decay< HandlerArg >::type, Handler * >::value >::type setHandler (HandlerArg &&arg)
Private Attributes
bool isFirst_
std::shared_ptr< Handler > handlerPtr_
ContextType< Handler >::type ctx_
Detailed Description
template<class R, class W, class Handler, class... Handlers>
class wangle::StaticPipeline< R, W, Handler, Handlers... >
Definition at line 69 of file StaticPipeline.h.
Member Typedef Documentation
template<class R , class W , class Handler , class... Handlers> using wangle::StaticPipeline< R, W, Handler, Handlers... >::Ptr = std::shared_ptr<StaticPipeline>
Definition at line 75 of file StaticPipeline.h.
Constructor & Destructor Documentation
template<class R , class W , class Handler , class... Handlers> wangle::StaticPipeline< R, W, Handler, Handlers... >::~StaticPipeline () inline override
Definition at line 85 of file StaticPipeline.h.
References wangle::PipelineBase::detachHandlers().
{
     if (isFirst_) {
       Pipeline<R, W>::detachHandlers();
     }
   }
template<class R , class W , class Handler , class... Handlers> template<class... HandlerArgs> wangle::StaticPipeline< R, W, Handler, Handlers... >::StaticPipeline (HandlerArgs &&... handlers) inline explicit protected
Definition at line 93 of file StaticPipeline.h.
     : StaticPipeline(true, std::forward<HandlerArgs>(handlers)...) {
     isFirst_ = true;
   }
template<class R , class W , class Handler , class... Handlers> template<class HandlerArg , class... HandlerArgs> wangle::StaticPipeline< R, W, Handler, Handlers... >::StaticPipeline (bool isFirst, HandlerArg && handler, HandlerArgs &&... handlers) inline protected
Definition at line 99 of file StaticPipeline.h.
References wangle::PipelineBase::addContextFront(), ctx_, and handler().
     : StaticPipeline<R, W, Handlers...>(
           false,
           std::forward<HandlerArgs>(handlers)...) {
     isFirst_ = isFirst;
     setHandler(std::forward<HandlerArg>(handler));
     Pipeline<R, W>::addContextFront(&ctx_);
   }
Member Function Documentation
template<class R , class W , class Handler , class... Handlers> template<class... HandlerArgs> static Ptr wangle::StaticPipeline< R, W, Handler, Handlers... >::create (HandlerArgs &&... handlers) inline static
Definition at line 78 of file StaticPipeline.h.
References ptr.
{
     auto ptr =  std::shared_ptr<StaticPipeline>(
         new StaticPipeline(std::forward<HandlerArgs>(handlers)...));
     ptr->initialize();
     return ptr;
   }
template<class R , class W , class Handler , class... Handlers> void wangle::StaticPipeline< R, W, Handler, Handlers... >::initialize () inline protected
Definition at line 111 of file StaticPipeline.h.
References ctx_, type, and value.
                     {
     CHECK(handlerPtr_);
     ctx_.initialize(Pipeline<R, W>::shared_from_this(), handlerPtr_);
     StaticPipeline<R, W, Handlers...>::initialize();
   }
template<class R , class W , class Handler , class... Handlers> template<class HandlerArg > std::enable_if<std::is_same< typename std::remove_reference<HandlerArg>::type, Handler >::value>::type wangle::StaticPipeline< R, W, Handler, Handlers... >::setHandler (HandlerArg && arg) inline private
Definition at line 123 of file StaticPipeline.h.
References type, and value.
{
     BaseWithOptional<Handler>::handler_.emplace(std::forward<HandlerArg>(arg));
     handlerPtr_ = std::shared_ptr<Handler>(
         &(*BaseWithOptional<Handler>::handler_),
         [](Handler*){});
   }
template<class R , class W , class Handler , class... Handlers> template<class HandlerArg > std::enable_if<std::is_same< typename std::decay<HandlerArg>::type, std::shared_ptr<Handler> >::value>::type wangle::StaticPipeline< R, W, Handler, Handlers... >::setHandler (HandlerArg && arg) inline private
Definition at line 135 of file StaticPipeline.h.
References type, and value.
{
     handlerPtr_ = std::forward<HandlerArg>(arg);
   }
template<class R , class W , class Handler , class... Handlers> template<class HandlerArg > std::enable_if<std::is_same< typename std::decay<HandlerArg>::type, Handler* >::value>::type wangle::StaticPipeline< R, W, Handler, Handlers... >::setHandler (HandlerArg && arg) inline private
Definition at line 144 of file StaticPipeline.h.
{
     handlerPtr_ = std::shared_ptr<Handler>(arg, [](Handler*){});
   }
Member Data Documentation
template<class R , class W , class Handler , class... Handlers> ContextType<Handler>::type wangle::StaticPipeline< R, W, Handler, Handlers... >::ctx_ private
Definition at line 150 of file StaticPipeline.h.
template<class R , class W , class Handler , class... Handlers> std::shared_ptr<Handler> wangle::StaticPipeline< R, W, Handler, Handlers... >::handlerPtr_ private
Definition at line 149 of file StaticPipeline.h.
template<class R , class W , class Handler , class... Handlers> bool wangle::StaticPipeline< R, W, Handler, Handlers... >::isFirst_ private
Definition at line 148 of file StaticPipeline.h.
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/channel/StaticPipeline.h