proxygen: wangle::LengthFieldPrepender Class Reference
wangle::LengthFieldPrepender Class Reference
#include <LengthFieldPrepender.h>
Public Member Functions
LengthFieldPrepender (int lengthFieldLength=4, int lengthAdjustment=0, bool lengthIncludesLengthField=false, bool networkByteOrder=true)
folly::Future< folly::Unit > write (Context *ctx, std::unique_ptr< folly::IOBuf > buf) override
Public Member Functions inherited from wangle::OutboundHandler< Win, Wout >
~OutboundHandler () override=default
virtual folly::Future< folly::Unit > write (Context *ctx, Win msg)=0
virtual folly::Future< folly::Unit > writeException (Context *ctx, folly::exception_wrapper e)
virtual folly::Future< folly::Unit > close (Context *ctx)
Public Member Functions inherited from wangle::HandlerBase< OutboundHandlerContext< Wout > >
virtual ~HandlerBase ()=default
virtual void attachPipeline (OutboundHandlerContext< Wout > *)
virtual void detachPipeline (OutboundHandlerContext< Wout > *)
OutboundHandlerContext< Wout > * getContext ()
Private Attributes
int lengthFieldLength_
int lengthAdjustment_
bool lengthIncludesLengthField_
bool networkByteOrder_
Additional Inherited Members
Public Types inherited from wangle::OutboundHandler< Win, Wout >
typedef folly::Unit rin
typedef folly::Unit rout
typedef Win win
typedef Wout wout
typedef OutboundHandlerContext< Wout > Context
Static Public Attributes inherited from wangle::OutboundHandler< Win, Wout >
static const HandlerDir dir = HandlerDir::OUT
Detailed Description
An encoder that prepends the length of the message. The length value is prepended as a binary form.
For example, LengthFieldPrepender(2)will encode the following 12-bytes string:
+-------------—+ | "HELLO, WORLD" | +-------------—+
into the following:
+-----—+-------------—+
0x000C | "HELLO, WORLD" | +-----—+-------------—+
If you turned on the lengthIncludesLengthFieldLength flag in the constructor, the encoded data would look like the following (12 (original data) + 2 (prepended data) = 14 (0xE)):
+-----—+-------------—+
0x000E | "HELLO, WORLD" | +-----—+-------------—+
Definition at line 50 of file LengthFieldPrepender.h.
Constructor & Destructor Documentation
wangle::LengthFieldPrepender::LengthFieldPrepender (int lengthFieldLength = 4, int lengthAdjustment = 0, bool lengthIncludesLengthField = false, bool networkByteOrder = true) explicit
Definition at line 25 of file LengthFieldPrepender.cpp.
     : lengthFieldLength_(lengthFieldLength)
     , lengthAdjustment_(lengthAdjustment)
     , lengthIncludesLengthField_(lengthIncludesLengthField)
     , networkByteOrder_(networkByteOrder) {
     CHECK(lengthFieldLength == 1 ||
           lengthFieldLength == 2 ||
           lengthFieldLength == 4 ||
           lengthFieldLength == 8 );
   }
Member Function Documentation
Future< Unit > wangle::LengthFieldPrepender::write (Context * ctx, std::unique_ptr< folly::IOBuf > buf) override
Definition at line 40 of file LengthFieldPrepender.cpp.
References c, folly::IOBuf::computeChainDataLength(), folly::IOBuf::create(), wangle::OutboundHandlerContext< Out >::fireWrite(), lengthAdjustment_, lengthFieldLength_, lengthIncludesLengthField_, folly::gen::move, networkByteOrder_, uint16_t, uint32_t, uint64_t, and uint8_t.
{
   int length = lengthAdjustment_ + buf->computeChainDataLength();
   if (lengthIncludesLengthField_) {
     length += lengthFieldLength_;
   }
   if (length < 0) {
     throw std::runtime_error("Length field < 0");
   }
   auto len = IOBuf::create(lengthFieldLength_);
   len->append(lengthFieldLength_);
   folly::io::RWPrivateCursor c(len.get());
   switch (lengthFieldLength_) {
     case 1: {
       if (length >= 256) {
         throw std::runtime_error("length does not fit byte");
       }
       if (networkByteOrder_) {
         c.writeBE((uint8_t)length);
       } else {
         c.writeLE((uint8_t)length);
       }
       break;
     }
     case 2: {
       if (length >= 65536) {
         throw std::runtime_error("length does not fit byte");
       }
       if (networkByteOrder_) {
         c.writeBE((uint16_t)length);
       } else {
         c.writeLE((uint16_t)length);
       }
       break;
     }
     case 4: {
       if (networkByteOrder_) {
         c.writeBE((uint32_t)length);
       } else {
         c.writeLE((uint32_t)length);
       }
       break;
     }
     case 8: {
       if (networkByteOrder_) {
         c.writeBE((uint64_t)length);
       } else {
         c.writeLE((uint64_t)length);
       }
       break;
     }
     default: {
       throw std::runtime_error("Invalid lengthFieldLength");
     }
   }
   len->prependChain(std::move(buf));
   return ctx->fireWrite(std::move(len));
 }
Member Data Documentation
int wangle::LengthFieldPrepender::lengthAdjustment_ private
Definition at line 63 of file LengthFieldPrepender.h.
Referenced by write().
int wangle::LengthFieldPrepender::lengthFieldLength_ private
Definition at line 62 of file LengthFieldPrepender.h.
Referenced by write().
bool wangle::LengthFieldPrepender::lengthIncludesLengthField_ private
Definition at line 64 of file LengthFieldPrepender.h.
Referenced by write().
bool wangle::LengthFieldPrepender::networkByteOrder_ private
Definition at line 65 of file LengthFieldPrepender.h.
Referenced by write().
The documentation for this class was generated from the following files:
proxygen/wangle/wangle/codec/LengthFieldPrepender.h
proxygen/wangle/wangle/codec/LengthFieldPrepender.cpp