proxygen: fizz::client::ClientStateMachine Class Reference
fizz::client::ClientStateMachine Class Reference
#include <ClientProtocol.h>
Public Types
using StateType = State
using ProcessingActions = Actions
using CompletedActions = Actions
Public Member Functions
virtual ~ClientStateMachine ()=default
virtual Actions processConnect (const State &, std::shared_ptr< const FizzClientContext > context, std::shared_ptr< const CertificateVerifier > verifier, folly::Optional< std::string > sni, folly::Optional< CachedPsk > cachedPsk, const std::shared_ptr< ClientExtensions > &extensions)
virtual Actions processSocketData (const State &, folly::IOBufQueue &)
virtual Actions processWriteNewSessionTicket (const State &, WriteNewSessionTicket)
virtual Actions processAppWrite (const State &, AppWrite)
virtual Actions processEarlyAppWrite (const State &, EarlyAppWrite)
virtual Actions processAppClose (const State &)
Detailed Description
Definition at line 20 of file ClientProtocol.h.
Member Typedef Documentation
using fizz::client::ClientStateMachine::CompletedActions = Actions
Definition at line 24 of file ClientProtocol.h.
using fizz::client::ClientStateMachine::ProcessingActions = Actions
Definition at line 23 of file ClientProtocol.h.
using fizz::client::ClientStateMachine::StateType = State
Definition at line 22 of file ClientProtocol.h.
Constructor & Destructor Documentation
virtual fizz::client::ClientStateMachine::~ClientStateMachine () virtual default
Member Function Documentation
Actions fizz::client::ClientStateMachine::processAppClose (const State & state) virtual
Definition at line 201 of file ClientProtocol.cpp.
References fizz::client::detail::handleAppClose().
{
   return detail::handleAppClose(state);
 }
Actions fizz::client::ClientStateMachine::processAppWrite (const State & state, AppWrite write) virtual
Definition at line 189 of file ClientProtocol.cpp.
References folly::gen::move, and fizz::client::detail::processEvent().
Referenced by fizz::client::test::TEST_F().
                     {
   return detail::processEvent(state, std::move(write));
 }
Actions fizz::client::ClientStateMachine::processConnect (const State & state, std::shared_ptr< const FizzClientContext > context, std::shared_ptr< const CertificateVerifier > verifier, folly::Optional< std::string > sni, folly::Optional< CachedPsk > cachedPsk, const std::shared_ptr< ClientExtensions > & extensions) virtual
Definition at line 144 of file ClientProtocol.cpp.
References fizz::Connect::cachedPsk, folly::netops::connect(), fizz::Connect::context, fizz::Connect::extensions, folly::gen::move, fizz::client::detail::processEvent(), fizz::Connect::sni, and fizz::Connect::verifier.
{
   Connect connect;
   connect.context = std::move(context);
   connect.sni = std::move(sni);
   connect.verifier = std::move(verifier);
   connect.extensions = extensions;
   connect.cachedPsk = std::move(cachedPsk);
   return detail::processEvent(state, std::move(connect));
 }
Actions fizz::client::ClientStateMachine::processEarlyAppWrite (const State & state, EarlyAppWrite write) virtual
Definition at line 195 of file ClientProtocol.cpp.
References folly::gen::move, and fizz::client::detail::processEvent().
{
   return detail::processEvent(state, std::move(write));
 }
Actions fizz::client::ClientStateMachine::processSocketData (const State & state, folly::IOBufQueue & buf) virtual
Definition at line 160 of file ClientProtocol.cpp.
References fizz::client::detail::actions(), fizz::decode_error, fizz::client::detail::handleError(), folly::gen::move, folly::none, fizz::client::detail::processEvent(), fizz::ReadRecordLayer::readEvent(), and fizz::client::State::readRecordLayer().
{
   try {
     if (!state.readRecordLayer()) {
       return detail::handleError(
           state,
           ReportError("attempting to process data without record layer"),
           folly::none);
     }
     auto param = state.readRecordLayer()->readEvent(buf);
     if (!param.hasValue()) {
       return actions(WaitForData());
     }
     return detail::processEvent(state, std::move(*param));
   } catch (const std::exception& e) {
     return detail::handleError(
         state,
         ReportError(folly::exception_wrapper(std::current_exception(), e)),
         AlertDescription::decode_error);
   }
 }
Actions fizz::client::ClientStateMachine::processWriteNewSessionTicket (const State & state, WriteNewSessionTicket write) virtual
Definition at line 183 of file ClientProtocol.cpp.
References folly::gen::move, and fizz::client::detail::processEvent().
Referenced by fizz::client::test::TEST_F().
{
   return detail::processEvent(state, std::move(write));
 }
The documentation for this class was generated from the following files:
proxygen/fizz/fizz/client/ClientProtocol.h
proxygen/fizz/fizz/client/ClientProtocol.cpp