proxygen: testing::internal::GoogleTestFailureReporter Class Reference
testing::internal::GoogleTestFailureReporter Class Reference
Public Member Functions
virtual void ReportFailure (FailureType type, const char *file, int line, const string &message)
virtual void ReportFailure (FailureType type, const char *file, int line, const string &message)
virtual void ReportFailure (FailureType type, const char *file, int line, const string &message)
Detailed Description
Definition at line 76 of file gmock-internal-utils.cc.
Member Function Documentation
virtual void testing::internal::GoogleTestFailureReporter::ReportFailure (FailureType type, const char * file, int line, const string & message) inline virtual
Definition at line 78 of file gmock-internal-utils.cc.
References testing::internal::posix::Abort(), testing::TestPartResult::kFatalFailure, and testing::TestPartResult::kNonFatalFailure.
{
     AssertHelper(type == kFatal ?
                  TestPartResult::kFatalFailure :
                  TestPartResult::kNonFatalFailure,
                  file,
                  line,
                  message.c_str()) = Message();
     if (type == kFatal) {
       posix::Abort();
     }
   }
virtual void testing::internal::GoogleTestFailureReporter::ReportFailure (FailureType type, const char * file, int line, const string & message) inline virtual
Definition at line 78 of file gmock-internal-utils.cc.
References testing::internal::posix::Abort(), testing::internal::GetCurrentOsStackTraceExceptTop(), testing::internal::GetFailureReporter(), testing::UnitTest::GetInstance(), GMOCK_FLAG, GTEST_API_, testing::internal::GTEST_DEFINE_STATIC_MUTEX_(), testing::internal::kErrorVerbosity, testing::TestPartResult::kFatalFailure, testing::internal::kInfoVerbosity, testing::TestPartResult::kNonFatalFailure, testing::internal::kWarning, testing::internal::Log(), testing::internal::LogIsVisible(), and message.
{
     AssertHelper(type == kFatal ?
                  TestPartResult::kFatalFailure :
                  TestPartResult::kNonFatalFailure,
                  file,
                  line,
                  message.c_str()) = Message();
     if (type == kFatal) {
       posix::Abort();
     }
   }
virtual void testing::internal::GoogleTestFailureReporter::ReportFailure (FailureType type, const char * file, int line, const string & message) inline virtual
Definition at line 78 of file gmock-internal-utils.cc.
References testing::internal::posix::Abort(), testing::internal::GetCurrentOsStackTraceExceptTop(), testing::internal::GetFailureReporter(), testing::UnitTest::GetInstance(), GMOCK_FLAG, GTEST_API_, testing::internal::GTEST_DEFINE_STATIC_MUTEX_(), testing::internal::kErrorVerbosity, testing::TestPartResult::kFatalFailure, testing::internal::kInfoVerbosity, testing::TestPartResult::kNonFatalFailure, testing::internal::kWarning, testing::internal::Log(), testing::internal::LogIsVisible(), and message.
{
     AssertHelper(type == kFatal ?
                  TestPartResult::kFatalFailure :
                  TestPartResult::kNonFatalFailure,
                  file,
                  line,
                  message.c_str()) = Message();
     if (type == kFatal) {
       posix::Abort();
     }
   }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/src/gmock-internal-utils.cc