proxygen: folly::File Class Reference
folly::File Class Reference
#include <File.h>
Public Member Functions
File () noexcept
File (int fd, bool ownsFd=false) noexcept
File (const char *name, int flags=O_RDONLY, mode_t mode=0666)
File (const std::string &name, int flags=O_RDONLY, mode_t mode=0666)
File (StringPiece name, int flags=O_RDONLY, mode_t mode=0666)
~File ()
int fd () const
operator bool () const
File dup () const
void close ()
bool closeNoThrow ()
int release () noexcept
void swap (File &other) noexcept
File (File &&) noexcept
File & operator= (File &&)
void lock ()
bool try_lock ()
void unlock ()
void lock_shared ()
bool try_lock_shared ()
void unlock_shared ()
Static Public Member Functions
template<typename... Args>
static Expected< File, exception_wrapper > makeFile (Args &&...args) noexcept
static File temporary ()
Private Member Functions
void doLock (int op)
bool doTryLock (int op)
File (const File &)=delete
File & operator= (const File &)=delete
Private Attributes
int fd_
bool ownsFd_
Detailed Description
A File represents an open file.
Definition at line 37 of file File.h.
Constructor & Destructor Documentation
folly::File::File () noexcept
Creates an empty File object, for late initialization.
Definition at line 33 of file File.cpp.
Referenced by dup(), makeFile(), operator bool(), and temporary().
 : fd_(-1), ownsFd_(false) {}
folly::File::File (int fd, bool ownsFd = false) explicit noexcept
Create a File object from an existing file descriptor. Takes ownership of the file descriptor if ownsFd is true.
Definition at line 35 of file File.cpp.
References fd().
                                        : fd_(fd), ownsFd_(ownsFd) {
   CHECK_GE(fd, -1) << "fd must be -1 or non-negative";
   CHECK(fd != -1 || !ownsFd) << "cannot own -1";
 }
folly::File::File (const char * name, int flags = O_RDONLY, mode_t mode = 0666) explicit
Open and create a file object. Throws on error. Owns the file descriptor implicitly.
Definition at line 40 of file File.cpp.
References fd_, folly::format(), ownsFd_, and folly::throwSystemError().
     : fd_(::open(name, flags, mode)), ownsFd_(false) {
   if (fd_ == -1) {
     throwSystemError(
         folly::format("open(\"{}\", {:#o}, 0{:#o}) failed", name, flags, mode)
             .fbstr());
   }
   ownsFd_ = true;
 }
folly::File::File (const std::string & name, int flags = O_RDONLY, mode_t mode = 0666) explicit
Definition at line 50 of file File.cpp.
     : File(name.c_str(), flags, mode) {}
folly::File::File (StringPiece name, int flags = O_RDONLY, mode_t mode = 0666) explicit
Definition at line 53 of file File.cpp.
     : File(name.str(), flags, mode) {}
folly::File::~File ()
Definition at line 66 of file File.cpp.
References closeNoThrow(), fd(), and fd_.
Referenced by makeFile().
             {
   auto fd = fd_;
   if (!closeNoThrow()) { // ignore most errors
     DCHECK_NE(errno, EBADF)
         << "closing fd " << fd << ", it may already "
         << "have been closed. Another time, this might close the wrong FD.";
   }
 }
folly::File::File (File && other) noexcept
Definition at line 56 of file File.cpp.
                                 : fd_(other.fd_), ownsFd_(other.ownsFd_) {
   other.release();
 }
folly::File::File (const File &) private delete
Member Function Documentation
void folly::File::close ()
If we own the file descriptor, close the file and throw on error. Otherwise, do nothing.
Definition at line 117 of file File.cpp.
References closeNoThrow(), and folly::throwSystemError().
Referenced by closeNoThrow(), folly::gen::detail::FileWriter::compose(), operator bool(), and TEST().
                  {
   if (!closeNoThrow()) {
     throwSystemError("close() failed");
   }
 }
bool folly::File::closeNoThrow ()
Closes the file (if owned). Returns true on success, false (and sets errno) on error.
Definition at line 123 of file File.cpp.
References close(), fd_, ownsFd_, and release().
Referenced by close(), operator bool(), operator=(), and ~File().
{
   int r = ownsFd_ ? ::close(fd_) : 0;
   release();
   return r == 0;
 }
void folly::File::doLock (int op) private
Definition at line 142 of file File.cpp.
References folly::checkUnixError(), fd_, and folly::flockNoInt().
Referenced by lock(), lock_shared(), and operator bool().
{
   checkUnixError(flockNoInt(fd_, op), "flock() failed (lock)");
 }
bool folly::File::doTryLock (int op) private
Definition at line 146 of file File.cpp.
References folly::checkUnixError(), fd_, and folly::flockNoInt().
Referenced by operator bool(), try_lock(), and try_lock_shared().
{
   int r = flockNoInt(fd_, op | LOCK_NB);
   // flock returns EWOULDBLOCK if already locked
   if (r == -1 && errno == EWOULDBLOCK) {
     return false;
   }
   checkUnixError(r, "flock() failed (try_lock)");
   return true;
 }
File folly::File::dup () const
Duplicate file descriptor and return File that owns it.
Definition at line 106 of file File.cpp.
References folly::checkUnixError(), fd(), fd_, and File().
Referenced by operator bool(), and temporary().
                      {
   if (fd_ != -1) {
     int fd = ::dup(fd_);
     checkUnixError(fd, "dup() failed");
     return File(fd, true);
   }
   return File();
 }
int folly::File::fd () const inline
Return the file descriptor, or -1 if the file was closed.
Definition at line 85 of file File.h.
References fd_.
Referenced by folly::gen::detail::FileReader::apply(), folly::ShutdownSocketSet::doShutdown(), dup(), folly::MemoryMapping::fd(), File(), folly::MemoryMapping::init(), folly::AsyncFileWriter::onIoError(), folly::AsyncFileWriter::performIO(), folly::test::CaptureFD::readIncremental(), folly::RecordIOWriter::RecordIOWriter(), temporary(), folly::TEST(), TEST(), folly::test::TEST(), folly::ImmediateFileWriter::ttyOutput(), folly::AsyncFileWriter::ttyOutput(), folly::RecordIOWriter::write(), folly::gen::detail::FileWriter::write(), folly::ImmediateFileWriter::writeMessage(), and ~File().
                  {
     return fd_;
   }
void folly::File::lock ()
Definition at line 129 of file File.cpp.
References doLock().
Referenced by operator bool().
                 {
   doLock(LOCK_EX);
 }
void folly::File::lock_shared ()
Definition at line 135 of file File.cpp.
References doLock().
Referenced by operator bool().
{
   doLock(LOCK_SH);
 }
template<typename... Args> static Expected<File, exception_wrapper> folly::File::makeFile (Args &&... args) inline static noexcept
All the constructors that are not noexcept can throw std::system_error. This is a helper method to use folly::Expected to chain a file open event to something else you want to do with the open fd.
Definition at line 67 of file File.h.
References File(), folly::makeUnexpected(), temporary(), and ~File().
Referenced by TEST().
{
     try {
       return File(std::forward<Args>(args)...);
     } catch (const std::system_error& se) {
       return makeUnexpected(exception_wrapper(std::current_exception(), se));
     }
   }
folly::File::operator bool () const inline explicit
Returns 'true' iff the file was successfully opened.
Definition at line 92 of file File.h.
References close(), closeNoThrow(), doLock(), doTryLock(), dup(), fd_, File(), lock(), lock_shared(), folly::pushmi::__adl::noexcept(), operator=(), release(), swap(), try_lock(), try_lock_shared(), unlock(), and unlock_shared().
{
     return fd_ != -1;
   }
File & folly::File::operator= (File && other)
Definition at line 60 of file File.cpp.
References closeNoThrow(), and swap().
Referenced by operator bool().
{
   closeNoThrow();
   swap(other);
   return *this;
 }
File& folly::File::operator= (const File &) private delete
int folly::File::release () noexcept
Returns and releases the file descriptor; no longer owned by this File. Returns -1 if the File object didn't wrap a file.
Definition at line 89 of file File.cpp.
References fd_, and ownsFd_.
Referenced by closeNoThrow(), operator bool(), and TEST().
{
   int released = fd_;
   fd_ = -1;
   ownsFd_ = false;
   return released;
 }
void folly::File::swap (File & other) noexcept
Swap this File with another.
Definition at line 96 of file File.cpp.
References fd_, ownsFd_, and folly::swap().
Referenced by operator bool(), and operator=().
{
   using std::swap;
   swap(fd_, other.fd_);
   swap(ownsFd_, other.ownsFd_);
 }
File folly::File::temporary () static
Create and return a temporary, owned file (uses tmpfile()).
Definition at line 75 of file File.cpp.
References folly::checkFopenError(), folly::checkUnixError(), dup(), fd(), FILE, File(), and SCOPE_EXIT.
Referenced by makeFile(), folly::TEST(), and TEST().
{
   // make a temp file with tmpfile(), dup the fd, then return it in a File.
   FILE* tmpFile = tmpfile();
   checkFopenError(tmpFile, "tmpfile() failed");
   SCOPE_EXIT {
     fclose(tmpFile);
   };
   int fd = ::dup(fileno(tmpFile));
   checkUnixError(fd, "dup() failed");
   return File(fd, true);
 }
bool folly::File::try_lock ()
Definition at line 132 of file File.cpp.
References doTryLock().
Referenced by main(), and operator bool().
                     {
   return doTryLock(LOCK_EX);
 }
bool folly::File::try_lock_shared ()
Definition at line 138 of file File.cpp.
References doTryLock().
Referenced by main(), and operator bool().
{
   return doTryLock(LOCK_SH);
 }
void folly::File::unlock ()
Definition at line 156 of file File.cpp.
References folly::checkUnixError(), fd_, and folly::flockNoInt().
Referenced by operator bool(), and unlock_shared().
                   {
   checkUnixError(flockNoInt(fd_, LOCK_UN), "flock() failed (unlock)");
 }
void folly::File::unlock_shared ()
Definition at line 159 of file File.cpp.
References unlock().
Referenced by operator bool().
{
   unlock();
 }
Member Data Documentation
int folly::File::fd_ private
Definition at line 152 of file File.h.
Referenced by closeNoThrow(), doLock(), doTryLock(), dup(), fd(), File(), operator bool(), release(), swap(), unlock(), and ~File().
bool folly::File::ownsFd_ private
Definition at line 153 of file File.h.
Referenced by closeNoThrow(), File(), release(), and swap().
The documentation for this class was generated from the following files:
proxygen/folly/folly/File.h
proxygen/folly/folly/File.cpp