proxygen: folly::Try< void > Class Template Reference
folly::Try< void > Class Template Reference
#include <Try.h>
Public Types
typedef void element_type
Public Member Functions
Try () noexcept
Try (exception_wrapper e) noexcept
Try & operator= (const Try< void > &t) noexcept
Try (const Try< void > &t) noexcept
~Try ()
void emplace () noexcept
template<typename... Args>
exception_wrapper & emplaceException (Args &&...args) noexcept(std::is_nothrow_constructible< exception_wrapper, Args &&... >::value)
void value () const
void operator* () const
void throwIfFailed () const
bool hasValue () const
bool hasException () const
template<class Ex >
bool hasException () const
exception_wrapper & exception ()&
exception_wrapper && exception ()&&
const exception_wrapper & exception () const &
const exception_wrapper && exception () const &&
std::exception * tryGetExceptionObject ()
std::exception const * tryGetExceptionObject () const
template<class E >
E * tryGetExceptionObject ()
template<class E >
E const * tryGetExceptionObject () const
template<class Ex , class F >
bool withException (F func)
template<class Ex , class F >
bool withException (F func) const
template<class F >
bool withException (F func)
template<class F >
bool withException (F func) const
template<bool , typename R >
R get ()
Private Attributes
bool hasValue_
union folly::Try< void >:: { ... }
Detailed Description
template<>
class folly::Try< void >
Definition at line 383 of file Try.h.
Member Typedef Documentation
typedef void folly::Try< void >::element_type
Definition at line 388 of file Try.h.
Constructor & Destructor Documentation
folly::Try< void >::Try () inline noexcept
Definition at line 391 of file Try.h.
 : hasValue_(true) {}
folly::Try< void >::Try (exception_wrapper e) inline explicit noexcept
Definition at line 398 of file Try.h.
References folly::pushmi::__adl::noexcept().
       : hasValue_(false), e_(std::move(e)) {}
folly::Try< void >::Try (const Try< void > & t) inline noexcept
Definition at line 405 of file Try.h.
References e_, and hasException().
                                    : hasValue_(t.hasValue_) {
     if (t.hasException()) {
       new (&e_) exception_wrapper(t.e_);
     }
   }
folly::Try< void >::~Try () inline
Definition at line 411 of file Try.h.
          {
     if (hasException()) {
       e_.~exception_wrapper();
     }
   }
Member Function Documentation
void folly::Try< void >::emplace () inline noexcept
Definition at line 423 of file Try.h.
References testing::Args(), folly::pushmi::__adl::noexcept(), and value.
Referenced by TEST(), and folly::tryEmplaceWith().
{
     if (hasException()) {
       e_.~exception_wrapper();
       hasValue_ = true;
     }
   }
template<typename... Args> exception_wrapper & folly::Try< void >::emplaceException (Args &&... args) noexcept
Definition at line 203 of file Try-inl.h.
References folly::Try< T >::e_, folly::Try< T >::hasException(), and folly::exception_wrapper::~exception_wrapper().
Referenced by TEST(), and folly::tryEmplaceWith().
{
   if (hasException()) {
     e_.~exception_wrapper();
   }
   new (&e_) exception_wrapper(static_cast<Args&&>(args)...);
   hasValue_ = false;
   return e_;
 }
exception_wrapper& folly::Try< void >::exception () inline
Definition at line 478 of file Try.h.
{
     if (!hasException()) {
       throw_exception<TryException>("Try does not contain an exception");
     }
     return e_;
   }
exception_wrapper&& folly::Try< void >::exception () inline
Definition at line 485 of file Try.h.
References folly::gen::move.
{
     if (!hasException()) {
       throw_exception<TryException>("Try does not contain an exception");
     }
     return std::move(e_);
   }
const exception_wrapper& folly::Try< void >::exception () const inline
Definition at line 492 of file Try.h.
{
     if (!hasException()) {
       throw_exception<TryException>("Try does not contain an exception");
     }
     return e_;
   }
const exception_wrapper&& folly::Try< void >::exception () const inline
Definition at line 499 of file Try.h.
References folly::gen::move.
{
     if (!hasException()) {
       throw_exception<TryException>("Try does not contain an exception");
     }
     return std::move(e_);
   }
template<bool , typename R > R folly::Try< void >::get () inline
Definition at line 577 of file Try.h.
           {
     return std::forward<R>(*this);
   }
bool folly::Try< void >::hasException () const inline
Definition at line 463 of file Try.h.
Referenced by TEST(), and Try().
{
     return !hasValue_;
   }
template<class Ex > bool folly::Try< void >::hasException () const inline
Definition at line 469 of file Try.h.
{
     return hasException() && e_.is_compatible_with<Ex>();
   }
bool folly::Try< void >::hasValue () const inline
Definition at line 459 of file Try.h.
Referenced by TEST().
{
     return hasValue_;
   }
void folly::Try< void >::operator* () const inline
Definition at line 451 of file Try.h.
References folly::value().
{
     return value();
   }
Try< void > & folly::Try< void >::operator= (const Try< void > & t) inline noexcept
Definition at line 185 of file Try-inl.h.
References testing::Args(), folly::pushmi::detail::t, and folly::exception_wrapper::~exception_wrapper().
{
   if (t.hasException()) {
     if (hasException()) {
       e_ = t.e_;
     } else {
       new (&e_) exception_wrapper(t.e_);
       hasValue_ = false;
     }
   } else {
     if (hasException()) {
       e_.~exception_wrapper();
       hasValue_ = true;
     }
   }
   return *this;
 }
void folly::Try< void >::throwIfFailed () const inline
Definition at line 213 of file Try-inl.h.
References folly::Try< T >::e_, folly::Try< T >::hasException(), folly::exception_wrapper::throw_exception(), type, and folly::Try< T >::value().
{
   if (hasException()) {
     e_.throw_exception();
   }
 }
std::exception* folly::Try< void >::tryGetExceptionObject () inline
Definition at line 510 of file Try.h.
{
     return hasException() ? e_.get_exception() : nullptr;
   }
std::exception const* folly::Try< void >::tryGetExceptionObject () const inline
Definition at line 513 of file Try.h.
{
     return hasException() ? e_.get_exception() : nullptr;
   }
template<class E > E* folly::Try< void >::tryGetExceptionObject () inline
Definition at line 523 of file Try.h.
{
     return hasException() ? e_.get_exception<E>() : nullptr;
   }
template<class E > E const* folly::Try< void >::tryGetExceptionObject () const inline
Definition at line 527 of file Try.h.
{
     return hasException() ? e_.get_exception<E>() : nullptr;
   }
void folly::Try< void >::value () const inline
Definition at line 447 of file Try.h.
Referenced by folly::coro::detail::BlockingWaitPromise< void >::get().
                      {
     throwIfFailed();
   }
template<class Ex , class F > bool folly::Try< void >::withException (F func) inline
Definition at line 539 of file Try.h.
References folly::gen::move.
{
     if (!hasException()) {
       return false;
     }
     return e_.with_exception<Ex>(std::move(func));
   }
template<class Ex , class F > bool folly::Try< void >::withException (F func) const inline
Definition at line 546 of file Try.h.
References folly::gen::move.
{
     if (!hasException()) {
       return false;
     }
     return e_.with_exception<Ex>(std::move(func));
   }
template<class F > bool folly::Try< void >::withException (F func) inline
Definition at line 562 of file Try.h.
References folly::gen::move.
{
     if (!hasException()) {
       return false;
     }
     return e_.with_exception(std::move(func));
   }
template<class F > bool folly::Try< void >::withException (F func) const inline
Definition at line 569 of file Try.h.
References folly::gen::move.
{
     if (!hasException()) {
       return false;
     }
     return e_.with_exception(std::move(func));
   }
Member Data Documentation
union { ... }
exception_wrapper folly::Try< void >::e_
Definition at line 584 of file Try.h.
Referenced by Try().
bool folly::Try< void >::hasValue_ private
Definition at line 582 of file Try.h.
The documentation for this class was generated from the following files:
proxygen/folly/folly/Try.h
proxygen/folly/folly/Try-inl.h