proxygen: testing::internal::UniversalTersePrinter< char * > Class Template Reference
testing::internal::UniversalTersePrinter< char * > Class Template Reference
#include <gtest-printers.h>
Static Public Member Functions
static void Print (char *str,::std::ostream *os)
static void Print (char *str,::std::ostream *os)
static void Print (char *str,::std::ostream *os)
Detailed Description
template<>
class testing::internal::UniversalTersePrinter< char * >
Definition at line 813 of file gtest-printers.h.
Member Function Documentation
static void testing::internal::UniversalTersePrinter< char * >::Print (char * str, ::std::ostream * os) inline static
Definition at line 815 of file gtest-printers.h.
References testing::gtest_printers_test::Print(), and testing::internal::UniversalPrint().
{
     UniversalTersePrinter<const char*>::Print(str, os);
   }
static void testing::internal::UniversalTersePrinter< char * >::Print (char * str, ::std::ostream * os) inline static
Definition at line 815 of file gtest-printers.h.
References testing::gtest_printers_test::Print(), and testing::internal::UniversalPrint().
{
     UniversalTersePrinter<const char*>::Print(str, os);
   }
static void testing::internal::UniversalTersePrinter< char * >::Print (char * str, ::std::ostream * os) inline static
Definition at line 815 of file gtest-printers.h.
References testing::gtest_printers_test::Print(), and testing::internal::UniversalPrint().
{
     UniversalTersePrinter<const char*>::Print(str, os);
   }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/gtest-printers.h