proxygen: folly::detail::ThreadCachedLists< Tag > Class Template Reference
folly::detail::ThreadCachedLists< Tag > Class Template Reference
#include <ThreadCachedLists.h>
Classes
struct AtomicListHead
struct ListHead
struct TLHead
Public Member Functions
void push (Node *node)
void collect (ListHead &list)
Private Member Functions
void pushGlobal (ListHead &list)
Private Attributes
folly::Synchronized< ListHead > ghead_
folly::ThreadLocalPtr< TLHead, Tag > lhead_
Detailed Description
template<typename Tag>
class folly::detail::ThreadCachedLists< Tag >
Definition at line 42 of file ThreadCachedLists.h.
Member Function Documentation
template<typename Tag > void folly::detail::ThreadCachedLists< Tag >::collect (ListHead & list)
Definition at line 143 of file ThreadCachedLists.h.
References folly::detail::ThreadCachedLists< Tag >::ListHead::splice().
Referenced by TEST().
{
   auto acc = lhead_.accessAllThreads();
   for (auto& thr : acc) {
     list.splice(thr);
   }
   list.splice(*ghead_.wlock());
 }
template<typename Tag > void folly::detail::ThreadCachedLists< Tag >::push (Node * node)
Definition at line 108 of file ThreadCachedLists.h.
References folly::detail::ThreadCachedListsBase::Node::next_.
Referenced by TEST().
{
   DCHECK(node->next_ == nullptr);
   static thread_local TLHead* cache_{nullptr};
   if (!cache_) {
     auto l = lhead_.get();
     if (!l) {
       lhead_.reset(new TLHead(this));
       l = lhead_.get();
       DCHECK(l);
     }
     cache_ = l;
   }
   while (true) {
     auto head = cache_->head_.load(std::memory_order_relaxed);
     if (!head) {
       node->next_ = nullptr;
       if (cache_->head_.compare_exchange_weak(head, node)) {
         cache_->tail_.store(node);
         break;
       }
     } else {
       auto tail = cache_->tail_.load(std::memory_order_relaxed);
       if (tail) {
         node->next_ = tail;
         if (cache_->tail_.compare_exchange_weak(node->next_, node)) {
           break;
         }
       }
     }
   }
 }
template<typename Tag> void folly::detail::ThreadCachedLists< Tag >::pushGlobal (ListHead & list) private
Member Data Documentation
template<typename Tag> folly::Synchronized<ListHead> folly::detail::ThreadCachedLists< Tag >::ghead_ private
Definition at line 85 of file ThreadCachedLists.h.
Referenced by folly::detail::ThreadCachedLists< Tag >::TLHead::~TLHead().
template<typename Tag> folly::ThreadLocalPtr<TLHead, Tag> folly::detail::ThreadCachedLists< Tag >::lhead_ private
Definition at line 98 of file ThreadCachedLists.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/synchronization/detail/ThreadCachedLists.h