proxygen: folly::EventBaseThread Class Reference
folly::EventBaseThread Class Reference
#include <EventBaseThread.h>
Public Member Functions
EventBaseThread ()
EventBaseThread (bool autostart, EventBaseManager *ebm=nullptr, folly::StringPiece threadName=folly::StringPiece())
EventBaseThread (EventBaseManager *ebm)
~EventBaseThread ()
EventBaseThread (EventBaseThread &&) noexcept
EventBaseThread & operator= (EventBaseThread &&) noexcept
EventBase * getEventBase () const
bool running () const
void start (folly::StringPiece threadName=folly::StringPiece())
void stop ()
Private Member Functions
EventBaseThread (EventBaseThread const &)=default
EventBaseThread & operator= (EventBaseThread const &)=default
Private Attributes
EventBaseManager * ebm_
std::unique_ptr< ScopedEventBaseThread > th_
Detailed Description
Definition at line 28 of file EventBaseThread.h.
Constructor & Destructor Documentation
folly::EventBaseThread::EventBaseThread ()
Definition at line 24 of file EventBaseThread.cpp.
Referenced by EventBaseThread().
 : EventBaseThread(true) {}
folly::EventBaseThread::EventBaseThread (bool autostart, EventBaseManager * ebm = nullptr, folly::StringPiece threadName = folly::StringPiece()) explicit
Definition at line 26 of file EventBaseThread.cpp.
References start().
     : ebm_(ebm) {
   if (autostart) {
     start(threadName);
   }
 }
folly::EventBaseThread::EventBaseThread (EventBaseManager * ebm) explicit
Definition at line 36 of file EventBaseThread.cpp.
References EventBaseThread(), folly::pushmi::__adl::noexcept(), operator=(), and ~EventBaseThread().
     : EventBaseThread(true, ebm) {}
folly::EventBaseThread::~EventBaseThread () default
Referenced by EventBaseThread().
folly::EventBaseThread::EventBaseThread (EventBaseThread &&) default noexcept
folly::EventBaseThread::EventBaseThread (EventBaseThread const &) private default
Member Function Documentation
EventBase * folly::EventBaseThread::getEventBase () const
Definition at line 45 of file EventBaseThread.cpp.
References th_.
Referenced by TEST_F().
{
   return th_ ? th_->getEventBase() : nullptr;
 }
EventBaseThread & folly::EventBaseThread::operator= (EventBaseThread &&) default noexcept
Referenced by EventBaseThread().
EventBaseThread& folly::EventBaseThread::operator= (EventBaseThread const &) private default
bool folly::EventBaseThread::running () const
Definition at line 49 of file EventBaseThread.cpp.
References th_.
{
   return !!th_;
 }
void folly::EventBaseThread::start (folly::StringPiece threadName = folly::StringPiece())
Definition at line 53 of file EventBaseThread.cpp.
References ebm_, and th_.
Referenced by EventBaseThread(), and TEST_F().
{
   if (th_) {
     return;
   }
   th_ = std::make_unique<ScopedEventBaseThread>(ebm_, threadName);
 }
void folly::EventBaseThread::stop ()
Definition at line 60 of file EventBaseThread.cpp.
References th_.
Referenced by TEST_F().
{
   th_ = nullptr;
 }
Member Data Documentation
EventBaseManager* folly::EventBaseThread::ebm_ private
Definition at line 51 of file EventBaseThread.h.
Referenced by start().
std::unique_ptr<ScopedEventBaseThread> folly::EventBaseThread::th_ private
Definition at line 52 of file EventBaseThread.h.
Referenced by getEventBase(), running(), start(), and stop().
The documentation for this class was generated from the following files:
proxygen/folly/folly/io/async/EventBaseThread.h
proxygen/folly/folly/io/async/EventBaseThread.cpp