proxygen: folly::pushmi::constrained_single_sender< SF, ZF, EXF > Class Template Reference
folly::pushmi::constrained_single_sender< SF, ZF, EXF > Class Template Reference
#include <constrained_single_sender.h>
Public Types
using properties = property_set< is_constrained<>, is_single<>>
Public Member Functions
constexpr constrained_single_sender ()=default
constexpr constrained_single_sender (SF sf)
constexpr constrained_single_sender (SF sf, EXF exf)
constexpr constrained_single_sender (SF sf, EXF exf, ZF zf)
auto top ()
auto executor ()
requires Regular< CV > &&Receiver< Out > &&Invocable< SF &, CV, Out > void submit (CV cv, Out out)
Private Attributes
SF sf_
ZF zf_
EXF exf_
Detailed Description
template<class SF, class ZF, class EXF>
class folly::pushmi::constrained_single_sender< SF, ZF, EXF >
Definition at line 145 of file constrained_single_sender.h.
Member Typedef Documentation
template<class SF , class ZF , class EXF > using folly::pushmi::constrained_single_sender< SF, ZF, EXF >::properties = property_set<is_constrained<>, is_single<>>
Definition at line 151 of file constrained_single_sender.h.
Constructor & Destructor Documentation
template<class SF , class ZF , class EXF > constexpr folly::pushmi::constrained_single_sender< SF, ZF, EXF >::constrained_single_sender () default
template<class SF , class ZF , class EXF > constexpr folly::pushmi::constrained_single_sender< SF, ZF, EXF >::constrained_single_sender (SF sf) inline explicit
Definition at line 154 of file constrained_single_sender.h.
       : sf_(std::move(sf)) {}
template<class SF , class ZF , class EXF > constexpr folly::pushmi::constrained_single_sender< SF, ZF, EXF >::constrained_single_sender (SF sf, EXF exf) inline
Definition at line 156 of file constrained_single_sender.h.
       : sf_(std::move(sf)), exf_(std::move(exf)) {}
template<class SF , class ZF , class EXF > constexpr folly::pushmi::constrained_single_sender< SF, ZF, EXF >::constrained_single_sender (SF sf, EXF exf, ZF zf) inline
Definition at line 158 of file constrained_single_sender.h.
       : sf_(std::move(sf)), zf_(std::move(zf)), exf_(std::move(exf)) {}
Member Function Documentation
template<class SF , class ZF , class EXF > auto folly::pushmi::constrained_single_sender< SF, ZF, EXF >::executor () inline
Definition at line 164 of file constrained_single_sender.h.
References folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
 { return exf_(); }
template<class SF , class ZF , class EXF > requires Regular<CV>&& Receiver<Out>&& Invocable<SF&, CV, Out> void folly::pushmi::constrained_single_sender< SF, ZF, EXF >::submit (CV cv, Out out) inline
Definition at line 168 of file constrained_single_sender.h.
References folly::gen::move, and folly::pushmi::requires().
{
     sf_(std::move(cv), std::move(out));
   }
template<class SF , class ZF , class EXF > auto folly::pushmi::constrained_single_sender< SF, ZF, EXF >::top () inline
Definition at line 161 of file constrained_single_sender.h.
              {
     return zf_();
   }
Member Data Documentation
template<class SF , class ZF , class EXF > EXF folly::pushmi::constrained_single_sender< SF, ZF, EXF >::exf_ private
Definition at line 148 of file constrained_single_sender.h.
template<class SF , class ZF , class EXF > SF folly::pushmi::constrained_single_sender< SF, ZF, EXF >::sf_ private
Definition at line 146 of file constrained_single_sender.h.
template<class SF , class ZF , class EXF > ZF folly::pushmi::constrained_single_sender< SF, ZF, EXF >::zf_ private
Definition at line 147 of file constrained_single_sender.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/pushmi/constrained_single_sender.h