proxygen: fizz::SelfCert Class Reference
fizz::SelfCert Class Reference abstract
#include <Certificate.h>
Public Member Functions
virtual ~SelfCert ()=default
virtual std::vector< std::string > getAltIdentities () const =0
virtual std::vector< SignatureScheme > getSigSchemes () const =0
virtual CertificateMsg getCertMessage (Buf certificateRequestContext=nullptr) const =0
virtual CompressedCertificate getCompressedCert (CertificateCompressionAlgorithm algo) const =0
virtual Buf sign (SignatureScheme scheme, CertificateVerifyContext context, folly::ByteRange toBeSigned) const =0
Public Member Functions inherited from folly::AsyncTransportCertificate
virtual ~AsyncTransportCertificate ()=default
virtual std::string getIdentity () const =0
virtual folly::ssl::X509UniquePtr getX509 () const =0
Detailed Description
Definition at line 37 of file Certificate.h.
Constructor & Destructor Documentation
virtual fizz::SelfCert::~SelfCert () virtual default
Member Function Documentation
virtual std::vector<std::string> fizz::SelfCert::getAltIdentities () const pure virtual
Returns additional identities this certificate can also represent (for example subject alternate names).
Implemented in fizz::SelfCertImpl< T >, fizz::SelfCertImpl< KeyType::P256 >, and fizz::SelfCertImpl< KeyType::RSA >.
virtual CertificateMsg fizz::SelfCert::getCertMessage (Buf certificateRequestContext = nullptr) const pure virtual
Implemented in fizz::SelfCertImpl< T >, fizz::SelfCertImpl< KeyType::P256 >, fizz::SelfCertImpl< KeyType::RSA >, and fizz::test::MockSelfCert.
Referenced by fizz::ExportedAuthenticator::makeAuthenticator().
virtual CompressedCertificate fizz::SelfCert::getCompressedCert (CertificateCompressionAlgorithm algo) const pure virtual
Implemented in fizz::SelfCertImpl< T >, fizz::SelfCertImpl< KeyType::P256 >, and fizz::SelfCertImpl< KeyType::RSA >.
virtual std::vector<SignatureScheme> fizz::SelfCert::getSigSchemes () const pure virtual
Returns the signature schemes this certificate can be used with.
Implemented in fizz::SelfCertImpl< T >, fizz::SelfCertImpl< KeyType::P256 >, and fizz::SelfCertImpl< KeyType::RSA >.
Referenced by fizz::detail::getSignatureScheme().
virtual Buf fizz::SelfCert::sign (SignatureScheme scheme, CertificateVerifyContext context, folly::ByteRange toBeSigned) const pure virtual
Implemented in fizz::SelfCertImpl< T >, fizz::SelfCertImpl< KeyType::P256 >, fizz::SelfCertImpl< KeyType::RSA >, fizz::SelfCertImpl< T >, fizz::SelfCertImpl< T >, fizz::SelfCertImpl< T >, and fizz::SelfCertImpl< T >.
Referenced by fizz::ExportedAuthenticator::makeAuthenticator().
The documentation for this class was generated from the following file:
proxygen/fizz/fizz/protocol/Certificate.h