proxygen: fizz::extensions::TokenBindingServerExtension Class Reference
fizz::extensions::TokenBindingServerExtension Class Reference
#include <TokenBindingServerExtension.h>
Public Member Functions
TokenBindingServerExtension (const std::shared_ptr< TokenBindingContext > &tokenBindingContext)
std::vector< Extension > getExtensions (const ClientHello &chlo) override
const auto & getNegotiatedKeyParam ()
Public Member Functions inherited from fizz::ServerExtensions
virtual ~ServerExtensions ()=default
Private Member Functions
folly::Optional< TokenBindingProtocolVersion > negotiateVersion (const TokenBindingProtocolVersion &clientPref)
Private Attributes
std::shared_ptr< TokenBindingContext > tokenBindingContext_
folly::Optional< TokenBindingKeyParameters > negotiatedKeyParam_
Detailed Description
Definition at line 19 of file TokenBindingServerExtension.h.
Constructor & Destructor Documentation
fizz::extensions::TokenBindingServerExtension::TokenBindingServerExtension (const std::shared_ptr< TokenBindingContext > & tokenBindingContext) inline explicit
Definition at line 21 of file TokenBindingServerExtension.h.
       : tokenBindingContext_(tokenBindingContext) {}
Member Function Documentation
std::vector<Extension> fizz::extensions::TokenBindingServerExtension::getExtensions (const ClientHello & chlo) inline override virtual
Returns a list of extensions to be added to EncryptedExtensions, given a ClientHello.
Implements fizz::ServerExtensions.
Definition at line 25 of file TokenBindingServerExtension.h.
References fizz::encodeExtension(), fizz::ClientHello::extensions, fizz::extensions::TokenBindingParameters::key_parameters_list, folly::gen::move, fizz::server::negotiate(), negotiatedKeyParam_, negotiateVersion(), params, tokenBindingContext_, and fizz::extensions::TokenBindingParameters::version.
{
     std::vector<Extension> serverExtensions;
     auto params = getExtension<TokenBindingParameters>(chlo.extensions);
     if (params) {
       auto negotiatedVersion = negotiateVersion(params->version);
       auto negotiatedKeyParam = server::negotiate(
           tokenBindingContext_->getKeyParams(), params->key_parameters_list);
       if (negotiatedKeyParam && negotiatedVersion) {
         TokenBindingParameters negotiatedParams;
         negotiatedParams.version = *negotiatedVersion;
         negotiatedParams.key_parameters_list.push_back(*negotiatedKeyParam);
         serverExtensions.push_back(encodeExtension(negotiatedParams));
         negotiatedKeyParam_ = std::move(negotiatedKeyParam);
       }
     }
     return serverExtensions;
   }
const auto& fizz::extensions::TokenBindingServerExtension::getNegotiatedKeyParam () inline
Definition at line 42 of file TokenBindingServerExtension.h.
References negotiatedKeyParam_.
{
     return negotiatedKeyParam_;
   }
folly::Optional<TokenBindingProtocolVersion> fizz::extensions::TokenBindingServerExtension::negotiateVersion (const TokenBindingProtocolVersion & clientPref) inline private
For TokenBinding, the server can negotiate any version below the clients preferred version, inclusive.
Definition at line 54 of file TokenBindingServerExtension.h.
References folly::none.
Referenced by getExtensions().
{
     for (const auto& pref : tokenBindingContext_->getSupportedVersions()) {
       if (pref <= clientPref) {
         return pref;
       }
     }
     return folly::none;
   }
Member Data Documentation
folly::Optional<TokenBindingKeyParameters> fizz::extensions::TokenBindingServerExtension::negotiatedKeyParam_ private
Definition at line 48 of file TokenBindingServerExtension.h.
Referenced by getExtensions(), and getNegotiatedKeyParam().
std::shared_ptr<TokenBindingContext> fizz::extensions::TokenBindingServerExtension::tokenBindingContext_ private
Definition at line 47 of file TokenBindingServerExtension.h.
Referenced by getExtensions().
The documentation for this class was generated from the following file:
proxygen/fizz/fizz/extensions/tokenbinding/TokenBindingServerExtension.h