proxygen: testing::internal::QuantifierMatcherImpl< Container > Class Template Reference
testing::internal::QuantifierMatcherImpl< Container > Class Template Reference
#include <gmock-matchers.h>
Public Types
typedef StlContainerView< RawContainer > View
typedef View::type StlContainer
typedef View::const_reference StlContainerReference
typedef StlContainer::value_type Element
typedef StlContainerView< RawContainer > View
typedef View::type StlContainer
typedef View::const_reference StlContainerReference
typedef StlContainer::value_type Element
typedef StlContainerView< RawContainer > View
typedef View::type StlContainer
typedef View::const_reference StlContainerReference
typedef StlContainer::value_type Element
Public Member Functions
typedef GTEST_REMOVE_REFERENCE_AND_CONST_ (Container) RawContainer
template<typename InnerMatcher >
QuantifierMatcherImpl (InnerMatcher inner_matcher)
bool MatchAndExplainImpl (bool all_elements_should_match, Container container, MatchResultListener *listener) const
typedef GTEST_REMOVE_REFERENCE_AND_CONST_ (Container) RawContainer
template<typename InnerMatcher >
QuantifierMatcherImpl (InnerMatcher inner_matcher)
bool MatchAndExplainImpl (bool all_elements_should_match, Container container, MatchResultListener *listener) const
typedef GTEST_REMOVE_REFERENCE_AND_CONST_ (Container) RawContainer
template<typename InnerMatcher >
QuantifierMatcherImpl (InnerMatcher inner_matcher)
bool MatchAndExplainImpl (bool all_elements_should_match, Container container, MatchResultListener *listener) const
Public Member Functions inherited from testing::MatcherInterface< Container >
virtual bool MatchAndExplain (Containerx, MatchResultListener *listener) const =0
virtual bool MatchAndExplain (Containerx, MatchResultListener *listener) const =0
virtual bool MatchAndExplain (Containerx, MatchResultListener *listener) const =0
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
virtual void DescribeTo (::std::ostream *os) const =0
virtual void DescribeNegationTo (::std::ostream *os) const
virtual ~MatcherDescriberInterface ()
virtual void DescribeTo (::std::ostream *os) const =0
virtual void DescribeNegationTo (::std::ostream *os) const
virtual ~MatcherDescriberInterface ()
virtual void DescribeTo (::std::ostream *os) const =0
virtual void DescribeNegationTo (::std::ostream *os) const
Protected Member Functions
GTEST_DISALLOW_ASSIGN_ (QuantifierMatcherImpl)
GTEST_DISALLOW_ASSIGN_ (QuantifierMatcherImpl)
GTEST_DISALLOW_ASSIGN_ (QuantifierMatcherImpl)
Protected Attributes
const Matcher< const Element & > inner_matcher_
Detailed Description
template<typename Container>
class testing::internal::QuantifierMatcherImpl< Container >
Definition at line 2800 of file gmock-matchers.h.
Member Typedef Documentation
template<typename Container > typedef StlContainer::value_type testing::internal::QuantifierMatcherImpl< Container >::Element
Definition at line 2806 of file gmock-matchers.h.
template<typename Container > typedef StlContainer::value_type testing::internal::QuantifierMatcherImpl< Container >::Element
Definition at line 2806 of file gmock-matchers.h.
template<typename Container > typedef StlContainer::value_type testing::internal::QuantifierMatcherImpl< Container >::Element
Definition at line 2806 of file gmock-matchers.h.
template<typename Container > typedef View::type testing::internal::QuantifierMatcherImpl< Container >::StlContainer
Definition at line 2804 of file gmock-matchers.h.
template<typename Container > typedef View::type testing::internal::QuantifierMatcherImpl< Container >::StlContainer
Definition at line 2804 of file gmock-matchers.h.
template<typename Container > typedef View::type testing::internal::QuantifierMatcherImpl< Container >::StlContainer
Definition at line 2804 of file gmock-matchers.h.
template<typename Container > typedef View::const_reference testing::internal::QuantifierMatcherImpl< Container >::StlContainerReference
Definition at line 2805 of file gmock-matchers.h.
template<typename Container > typedef View::const_reference testing::internal::QuantifierMatcherImpl< Container >::StlContainerReference
Definition at line 2805 of file gmock-matchers.h.
template<typename Container > typedef View::const_reference testing::internal::QuantifierMatcherImpl< Container >::StlContainerReference
Definition at line 2805 of file gmock-matchers.h.
template<typename Container > typedef StlContainerView<RawContainer> testing::internal::QuantifierMatcherImpl< Container >::View
Definition at line 2803 of file gmock-matchers.h.
template<typename Container > typedef StlContainerView<RawContainer> testing::internal::QuantifierMatcherImpl< Container >::View
Definition at line 2803 of file gmock-matchers.h.
template<typename Container > typedef StlContainerView<RawContainer> testing::internal::QuantifierMatcherImpl< Container >::View
Definition at line 2803 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename Container > template<typename InnerMatcher > testing::internal::QuantifierMatcherImpl< Container >::QuantifierMatcherImpl (InnerMatcher inner_matcher) inline explicit
Definition at line 2809 of file gmock-matchers.h.
       : inner_matcher_(
            testing::SafeMatcherCast<const Element&>(inner_matcher)) {}
template<typename Container > template<typename InnerMatcher > testing::internal::QuantifierMatcherImpl< Container >::QuantifierMatcherImpl (InnerMatcher inner_matcher) inline explicit
Definition at line 2809 of file gmock-matchers.h.
       : inner_matcher_(
            testing::SafeMatcherCast<const Element&>(inner_matcher)) {}
template<typename Container > template<typename InnerMatcher > testing::internal::QuantifierMatcherImpl< Container >::QuantifierMatcherImpl (InnerMatcher inner_matcher) inline explicit
Definition at line 2809 of file gmock-matchers.h.
       : inner_matcher_(
            testing::SafeMatcherCast<const Element&>(inner_matcher)) {}
Member Function Documentation
template<typename Container > testing::internal::QuantifierMatcherImpl< Container >::GTEST_DISALLOW_ASSIGN_ (QuantifierMatcherImpl< Container >) protected
template<typename Container > testing::internal::QuantifierMatcherImpl< Container >::GTEST_DISALLOW_ASSIGN_ (QuantifierMatcherImpl< Container >) protected
template<typename Container > testing::internal::QuantifierMatcherImpl< Container >::GTEST_DISALLOW_ASSIGN_ (QuantifierMatcherImpl< Container >) protected
template<typename Container > typedef testing::internal::QuantifierMatcherImpl< Container >::GTEST_REMOVE_REFERENCE_AND_CONST_ (Container)
template<typename Container > typedef testing::internal::QuantifierMatcherImpl< Container >::GTEST_REMOVE_REFERENCE_AND_CONST_ (Container)
template<typename Container > typedef testing::internal::QuantifierMatcherImpl< Container >::GTEST_REMOVE_REFERENCE_AND_CONST_ (Container)
template<typename Container > bool testing::internal::QuantifierMatcherImpl< Container >::MatchAndExplainImpl (bool all_elements_should_match, Container container, MatchResultListener * listener) const inline
Definition at line 2816 of file gmock-matchers.h.
References i, testing::internal::PrintIfNotEmpty(), testing::StringMatchResultListener::str(), and testing::MatchResultListener::stream().
{
     StlContainerReference stl_container = View::ConstReference(container);
     size_t i = 0;
     for (typename StlContainer::const_iterator it = stl_container.begin();
          it != stl_container.end(); ++it, ++i) {
       StringMatchResultListener inner_listener;
       const bool matches = inner_matcher_.MatchAndExplain(*it, &inner_listener);
       if (matches != all_elements_should_match) {
         *listener << "whose element #" << i
                   << (matches ? " matches" : " doesn't match");
         PrintIfNotEmpty(inner_listener.str(), listener->stream());
         return !all_elements_should_match;
       }
     }
     return all_elements_should_match;
   }
template<typename Container > bool testing::internal::QuantifierMatcherImpl< Container >::MatchAndExplainImpl (bool all_elements_should_match, Container container, MatchResultListener * listener) const inline
Definition at line 2816 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, i, testing::internal::PrintIfNotEmpty(), and testing::StringMatchResultListener::str().
{
     StlContainerReference stl_container = View::ConstReference(container);
     size_t i = 0;
     for (typename StlContainer::const_iterator it = stl_container.begin();
          it != stl_container.end(); ++it, ++i) {
       StringMatchResultListener inner_listener;
       const bool matches = inner_matcher_.MatchAndExplain(*it, &inner_listener);
       if (matches != all_elements_should_match) {
         *listener << "whose element #" << i
                   << (matches ? " matches" : " doesn't match");
         PrintIfNotEmpty(inner_listener.str(), listener->stream());
         return !all_elements_should_match;
       }
     }
     return all_elements_should_match;
   }
template<typename Container > bool testing::internal::QuantifierMatcherImpl< Container >::MatchAndExplainImpl (bool all_elements_should_match, Container container, MatchResultListener * listener) const inline
Definition at line 2816 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, i, testing::internal::PrintIfNotEmpty(), and testing::StringMatchResultListener::str().
{
     StlContainerReference stl_container = View::ConstReference(container);
     size_t i = 0;
     for (typename StlContainer::const_iterator it = stl_container.begin();
          it != stl_container.end(); ++it, ++i) {
       StringMatchResultListener inner_listener;
       const bool matches = inner_matcher_.MatchAndExplain(*it, &inner_listener);
       if (matches != all_elements_should_match) {
         *listener << "whose element #" << i
                   << (matches ? " matches" : " doesn't match");
         PrintIfNotEmpty(inner_listener.str(), listener->stream());
         return !all_elements_should_match;
       }
     }
     return all_elements_should_match;
   }
Member Data Documentation
template<typename Container > const Matcher< const Element & > testing::internal::QuantifierMatcherImpl< Container >::inner_matcher_ protected
Definition at line 2837 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h