proxygen: fizz::client::FizzClientContext Class Reference
fizz::client::FizzClientContext Class Reference
#include <FizzClientContext.h>
Public Member Functions
FizzClientContext ()
virtual ~FizzClientContext ()=default
void setSupportedVersions (std::vector< ProtocolVersion > versions)
const auto & getSupportedVersions () const
void setSupportedCiphers (std::vector< CipherSuite > ciphers)
const auto & getSupportedCiphers () const
void setSupportedSigSchemes (std::vector< SignatureScheme > schemes)
const auto & getSupportedSigSchemes () const
void setSupportedGroups (std::vector< NamedGroup > groups)
const auto & getSupportedGroups () const
void setDefaultShares (std::vector< NamedGroup > groups)
const auto & getDefaultShares () const
void setSupportedPskModes (std::vector< PskKeyExchangeMode > modes)
const auto & getSupportedPskModes () const
void setSupportedAlpns (std::vector< std::string > protocols)
const auto & getSupportedAlpns () const
void setClientCertificate (std::shared_ptr< SelfCert > cert)
const auto & getClientCertificate () const
void setPskCache (std::shared_ptr< PskCache > pskCache)
folly::Optional< CachedPsk > getPsk (const std::string &identity) const
void putPsk (const std::string &identity, CachedPsk psk) const
void removePsk (const std::string &identity) const
void setSendEarlyData (bool sendEarlyData)
bool getSendEarlyData () const
void setCompatibilityMode (bool enabled)
bool getCompatibilityMode () const
void setFactory (std::unique_ptr< Factory > factory)
const Factory * getFactory () const
void setCertDecompressionManager (std::shared_ptr< CertDecompressionManager > mgr)
std::vector< CertificateCompressionAlgorithm > getSupportedCertDecompressionAlgorithms () const
std::shared_ptr< CertificateDecompressor > getCertDecompressorForAlgorithm (CertificateCompressionAlgorithm algo) const
Private Attributes
std::unique_ptr< Factory > factory_
std::vector< ProtocolVersion > supportedVersions_ = {ProtocolVersion::tls_1_3}
std::vector< CipherSuite > supportedCiphers_
std::vector< SignatureScheme > supportedSigSchemes_
std::vector< NamedGroup > supportedGroups_
std::vector< NamedGroup > defaultShares_ = {NamedGroup::x25519}
std::vector< PskKeyExchangeMode > supportedPskModes_
std::vector< std::string > supportedAlpns_
bool sendEarlyData_ {false}
bool compatMode_ {false}
std::shared_ptr< PskCache > pskCache_
std::shared_ptr< const SelfCert > clientCert_
std::shared_ptr< CertDecompressionManager > certDecompressionManager_
Detailed Description
Definition at line 20 of file FizzClientContext.h.
Constructor & Destructor Documentation
fizz::client::FizzClientContext::FizzClientContext () inline
Definition at line 22 of file FizzClientContext.h.
References ~FizzClientContext().
 : factory_(std::make_unique<Factory>()) {}
virtual fizz::client::FizzClientContext::~FizzClientContext () virtual default
Referenced by FizzClientContext().
Member Function Documentation
std::shared_ptr<CertificateDecompressor> fizz::client::FizzClientContext::getCertDecompressorForAlgorithm (CertificateCompressionAlgorithm algo) const inline
Given a compression algorithm, returns the decompressor to decompress certs. If the algorithm isn't found, returns nullptr.
Definition at line 198 of file FizzClientContext.h.
References certDecompressionManager_.
Referenced by fizz::sm::handleCertMsg().
{
     if (certDecompressionManager_) {
       return certDecompressionManager_->getDecompressor(algo);
     } else {
       return nullptr;
     }
   }
const auto& fizz::client::FizzClientContext::getClientCertificate () const inline
Definition at line 108 of file FizzClientContext.h.
References clientCert_.
Referenced by fizz::sm::getClientCert().
{
     return clientCert_;
   }
bool fizz::client::FizzClientContext::getCompatibilityMode () const inline
Definition at line 158 of file FizzClientContext.h.
References compatMode_.
Referenced by fizz::sm::getHrrKeyExchangers(), fizz::sm::handleCertMsg(), and fizz::sm::handleEarlyAppWrite().
{
     return compatMode_;
   }
const auto& fizz::client::FizzClientContext::getDefaultShares () const inline
Definition at line 75 of file FizzClientContext.h.
References defaultShares_.
{
     return defaultShares_;
   }
const Factory* fizz::client::FizzClientContext::getFactory () const inline
Definition at line 169 of file FizzClientContext.h.
References factory_.
Referenced by fizz::sm::getHrrKeyExchangers(), fizz::sm::getMaxEarlyDataSize(), fizz::sm::handleCertMsg(), and fizz::sm::negotiatePsk().
{
     return factory_.get();
   }
folly::Optional<CachedPsk> fizz::client::FizzClientContext::getPsk (const std::string & identity) const inline
Definition at line 119 of file FizzClientContext.h.
References folly::none, and pskCache_.
{
     if (pskCache_) {
       return pskCache_->getPsk(identity);
     } else {
       return folly::none;
     }
   }
bool fizz::client::FizzClientContext::getSendEarlyData () const inline
Definition at line 146 of file FizzClientContext.h.
References sendEarlyData_.
Referenced by fizz::sm::getEarlyDataParams().
{
     return sendEarlyData_;
   }
const auto& fizz::client::FizzClientContext::getSupportedAlpns () const inline
Definition at line 97 of file FizzClientContext.h.
References supportedAlpns_.
Referenced by fizz::sm::getEarlyDataParams(), fizz::sm::getHrrKeyExchangers(), and fizz::sm::validateAcceptedEarly().
{
     return supportedAlpns_;
   }
std::vector<CertificateCompressionAlgorithm> fizz::client::FizzClientContext::getSupportedCertDecompressionAlgorithms () const inline
Returns a vector representing the compression algorithms the manager has decompressors for.
Definition at line 186 of file FizzClientContext.h.
References certDecompressionManager_.
Referenced by fizz::sm::getHrrKeyExchangers(), and fizz::sm::handleCertMsg().
{
     if (certDecompressionManager_) {
       return certDecompressionManager_->getSupportedAlgorithms();
     } else {
       return {};
     }
   }
const auto& fizz::client::FizzClientContext::getSupportedCiphers () const inline
Definition at line 43 of file FizzClientContext.h.
References supportedCiphers_.
Referenced by fizz::sm::getHrrKeyExchangers(), fizz::sm::negotiatePsk(), and fizz::sm::validatePsk().
{
     return supportedCiphers_;
   }
const auto& fizz::client::FizzClientContext::getSupportedGroups () const inline
Definition at line 65 of file FizzClientContext.h.
References supportedGroups_.
Referenced by fizz::sm::getHrrKeyExchangers().
{
     return supportedGroups_;
   }
const auto& fizz::client::FizzClientContext::getSupportedPskModes () const inline
Definition at line 86 of file FizzClientContext.h.
References supportedPskModes_.
Referenced by fizz::sm::getHrrKeyExchangers(), and fizz::sm::negotiatePsk().
{
     return supportedPskModes_;
   }
const auto& fizz::client::FizzClientContext::getSupportedSigSchemes () const inline
Definition at line 54 of file FizzClientContext.h.
References supportedSigSchemes_.
Referenced by fizz::sm::getClientCert(), fizz::sm::getHrrKeyExchangers(), fizz::client::AsyncFizzClientT< SM >::getSupportedSigSchemes(), and fizz::sm::handleCertMsg().
{
     return supportedSigSchemes_;
   }
const auto& fizz::client::FizzClientContext::getSupportedVersions () const inline
Definition at line 32 of file FizzClientContext.h.
References supportedVersions_.
Referenced by fizz::sm::getHrrKeyExchangers(), fizz::sm::negotiatePsk(), and fizz::sm::validatePsk().
{
     return supportedVersions_;
   }
void fizz::client::FizzClientContext::putPsk (const std::string & identity, CachedPsk psk) const inline
Definition at line 127 of file FizzClientContext.h.
References folly::gen::move, and pskCache_.
{
     if (pskCache_) {
       pskCache_->putPsk(identity, std::move(psk));
     }
   }
void fizz::client::FizzClientContext::removePsk (const std::string & identity) const inline
Definition at line 133 of file FizzClientContext.h.
References pskCache_.
{
     if (pskCache_) {
       pskCache_->removePsk(identity);
     }
   }
void fizz::client::FizzClientContext::setCertDecompressionManager (std::shared_ptr< CertDecompressionManager > mgr) inline
Sets the certificate decompression manager for server certs.
Definition at line 176 of file FizzClientContext.h.
References certDecompressionManager_.
{
     certDecompressionManager_ = mgr;
   }
void fizz::client::FizzClientContext::setClientCertificate (std::shared_ptr< SelfCert > cert) inline
Sets the certificate to use if the server requests client authentication
Definition at line 104 of file FizzClientContext.h.
References clientCert_, and folly::gen::move.
{
     clientCert_ = std::move(cert);
   }
void fizz::client::FizzClientContext::setCompatibilityMode (bool enabled) inline
Sets whether we want to use compatibility mode (sending a fake session ID and ChangeCipherSpec).
Definition at line 154 of file FizzClientContext.h.
References compatMode_.
{
     compatMode_ = enabled;
   }
void fizz::client::FizzClientContext::setDefaultShares (std::vector< NamedGroup > groups) inline
Set the default key shares to send. Must be a subset of supported groups.
Definition at line 72 of file FizzClientContext.h.
References defaultShares_, and folly::gen::move.
{
     defaultShares_ = std::move(groups);
   }
void fizz::client::FizzClientContext::setFactory (std::unique_ptr< Factory > factory) inline
Set the factory to use. Should generally only be changed for testing.
Definition at line 165 of file FizzClientContext.h.
References factory_, and folly::gen::move.
{
     factory_ = std::move(factory);
   }
void fizz::client::FizzClientContext::setPskCache (std::shared_ptr< PskCache > pskCache) inline
Set the Psk Cache to use.
Definition at line 115 of file FizzClientContext.h.
References folly::gen::move, and pskCache_.
{
     pskCache_ = std::move(pskCache);
   }
void fizz::client::FizzClientContext::setSendEarlyData (bool sendEarlyData) inline
Sets whether we should attempt to send early data.
Definition at line 142 of file FizzClientContext.h.
References sendEarlyData_.
{
     sendEarlyData_ = sendEarlyData;
   }
void fizz::client::FizzClientContext::setSupportedAlpns (std::vector< std::string > protocols) inline
Sets the supported ALPN supported protocols, in preference order.
Definition at line 93 of file FizzClientContext.h.
References folly::gen::move, and supportedAlpns_.
{
     supportedAlpns_ = std::move(protocols);
   }
void fizz::client::FizzClientContext::setSupportedCiphers (std::vector< CipherSuite > ciphers) inline
Set the supported ciphers, in preference order.
Definition at line 39 of file FizzClientContext.h.
References folly::gen::move, and supportedCiphers_.
{
     supportedCiphers_ = std::move(ciphers);
   }
void fizz::client::FizzClientContext::setSupportedGroups (std::vector< NamedGroup > groups) inline
Set the supported named groups, in preference order.
Definition at line 61 of file FizzClientContext.h.
References folly::gen::move, and supportedGroups_.
{
     supportedGroups_ = std::move(groups);
   }
void fizz::client::FizzClientContext::setSupportedPskModes (std::vector< PskKeyExchangeMode > modes) inline
Set the supported psk modes, in preference order.
Definition at line 82 of file FizzClientContext.h.
References folly::gen::move, and supportedPskModes_.
{
     supportedPskModes_ = std::move(modes);
   }
void fizz::client::FizzClientContext::setSupportedSigSchemes (std::vector< SignatureScheme > schemes) inline
Set the supported signature schemes, in preference order.
Definition at line 50 of file FizzClientContext.h.
References folly::gen::move, and supportedSigSchemes_.
{
     supportedSigSchemes_ = std::move(schemes);
   }
void fizz::client::FizzClientContext::setSupportedVersions (std::vector< ProtocolVersion > versions) inline
Set the supported protocol versions, in preference order.
Definition at line 28 of file FizzClientContext.h.
References folly::gen::move, and supportedVersions_.
{
     supportedVersions_ = std::move(versions);
   }
Member Data Documentation
std::shared_ptr<CertDecompressionManager> fizz::client::FizzClientContext::certDecompressionManager_ private
Definition at line 234 of file FizzClientContext.h.
Referenced by getCertDecompressorForAlgorithm(), getSupportedCertDecompressionAlgorithms(), and setCertDecompressionManager().
std::shared_ptr<const SelfCert> fizz::client::FizzClientContext::clientCert_ private
Definition at line 233 of file FizzClientContext.h.
Referenced by getClientCertificate(), and setClientCertificate().
bool fizz::client::FizzClientContext::compatMode_ {false} private
Definition at line 230 of file FizzClientContext.h.
Referenced by getCompatibilityMode(), and setCompatibilityMode().
std::vector<NamedGroup> fizz::client::FizzClientContext::defaultShares_ = {NamedGroup::x25519} private
Definition at line 223 of file FizzClientContext.h.
Referenced by getDefaultShares(), and setDefaultShares().
std::unique_ptr<Factory> fizz::client::FizzClientContext::factory_ private
Definition at line 208 of file FizzClientContext.h.
Referenced by getFactory(), and setFactory().
std::shared_ptr<PskCache> fizz::client::FizzClientContext::pskCache_ private
Definition at line 232 of file FizzClientContext.h.
Referenced by getPsk(), putPsk(), removePsk(), and setPskCache().
bool fizz::client::FizzClientContext::sendEarlyData_ {false} private
Definition at line 228 of file FizzClientContext.h.
Referenced by getSendEarlyData(), and setSendEarlyData().
std::vector<std::string> fizz::client::FizzClientContext::supportedAlpns_ private
Definition at line 227 of file FizzClientContext.h.
Referenced by getSupportedAlpns(), and setSupportedAlpns().
std::vector<CipherSuite> fizz::client::FizzClientContext::supportedCiphers_ private
Initial value:
= {
      CipherSuite::TLS_AES_128_GCM_SHA256,
      CipherSuite::TLS_AES_256_GCM_SHA384,
  }
Definition at line 211 of file FizzClientContext.h.
Referenced by getSupportedCiphers(), and setSupportedCiphers().
std::vector<NamedGroup> fizz::client::FizzClientContext::supportedGroups_ private
Initial value:
= {NamedGroup::x25519,
                                              NamedGroup::secp256r1}
Definition at line 221 of file FizzClientContext.h.
Referenced by getSupportedGroups(), and setSupportedGroups().
std::vector<PskKeyExchangeMode> fizz::client::FizzClientContext::supportedPskModes_ private
Initial value:
= {
      PskKeyExchangeMode::psk_dhe_ke,
      PskKeyExchangeMode::psk_ke}
Definition at line 224 of file FizzClientContext.h.
Referenced by getSupportedPskModes(), and setSupportedPskModes().
std::vector<SignatureScheme> fizz::client::FizzClientContext::supportedSigSchemes_ private
Initial value:
= {
      SignatureScheme::ecdsa_secp256r1_sha256,
      SignatureScheme::rsa_pss_sha256}
Definition at line 218 of file FizzClientContext.h.
Referenced by getSupportedSigSchemes(), and setSupportedSigSchemes().
std::vector<ProtocolVersion> fizz::client::FizzClientContext::supportedVersions_ = {ProtocolVersion::tls_1_3} private
Definition at line 210 of file FizzClientContext.h.
Referenced by getSupportedVersions(), and setSupportedVersions().
The documentation for this class was generated from the following file:
proxygen/fizz/fizz/client/FizzClientContext.h