proxygen: fizz::X25519KeyExchange Class Reference
fizz::X25519KeyExchange Class Reference
#include <X25519.h>
Public Member Functions
~X25519KeyExchange () override=default
void generateKeyPair () override
std::unique_ptr< folly::IOBuf > getKeyShare () const override
std::unique_ptr< folly::IOBuf > generateSharedSecret (folly::ByteRange keyShare) const override
Public Member Functions inherited from fizz::KeyExchange
virtual ~KeyExchange ()=default
Private Types
using PrivKey = std::array< uint8_t, crypto_scalarmult_SCALARBYTES >
using PubKey = std::array< uint8_t, crypto_scalarmult_BYTES >
Private Attributes
folly::Optional< PrivKey > privKey_
folly::Optional< PubKey > pubKey_
Detailed Description
X25519 key exchange implementation using libsodium.
Definition at line 23 of file X25519.h.
Member Typedef Documentation
using fizz::X25519KeyExchange::PrivKey = std::array<uint8_t, crypto_scalarmult_SCALARBYTES> private
Definition at line 32 of file X25519.h.
using fizz::X25519KeyExchange::PubKey = std::array<uint8_t, crypto_scalarmult_BYTES> private
Definition at line 33 of file X25519.h.
Constructor & Destructor Documentation
fizz::X25519KeyExchange::~X25519KeyExchange () override default
Member Function Documentation
void fizz::X25519KeyExchange::generateKeyPair () override virtual
Generates an ephemeral key pair.
Implements fizz::KeyExchange.
Definition at line 20 of file X25519.cpp.
References folly::gen::move.
Referenced by fizz::test::TEST().
{
   auto privKey = PrivKey();
   auto pubKey = PubKey();
   auto err = crypto_box_curve25519xsalsa20poly1305_keypair(
       pubKey.data(), privKey.data());
   if (err != 0) {
     throw std::runtime_error(to<std::string>("Could not generate keys ", err));
   }
   privKey_ = std::move(privKey);
   pubKey_ = std::move(pubKey);
 }
std::unique_ptr< folly::IOBuf > fizz::X25519KeyExchange::generateSharedSecret (folly::ByteRange keyShare) const override virtual
Generate a shared secret with our key pair and a peer's public key share.
Performs all necessary validation of the public key share and throws on error.
generateKeyPair() must be called before.
Implements fizz::KeyExchange.
Definition at line 39 of file X25519.cpp.
References folly::IOBuf::create(), folly::Range< Iter >::data(), and folly::Range< Iter >::size().
Referenced by fizz::test::TEST().
{
   if (!privKey_ || !pubKey_) {
     throw std::runtime_error("Key not generated");
   }
   if (keyShare.size() != crypto_scalarmult_BYTES) {
     throw std::runtime_error("Invalid external public key");
   }
   auto key = IOBuf::create(crypto_scalarmult_BYTES);
   key->append(crypto_scalarmult_BYTES);
   int err =
       crypto_scalarmult(key->writableData(), privKey_->data(), keyShare.data());
   if (err != 0) {
     throw std::runtime_error("Invalid point");
   }
   return key;
 }
std::unique_ptr< IOBuf > fizz::X25519KeyExchange::getKeyShare () const override virtual
Returns the public key to share with peers.
generateKeyPair() must be called before.
Implements fizz::KeyExchange.
Definition at line 32 of file X25519.cpp.
References folly::IOBuf::copyBuffer().
{
   if (!privKey_ || !pubKey_) {
     throw std::runtime_error("Key not generated");
   }
   return IOBuf::copyBuffer(pubKey_->data(), pubKey_->size());
 }
Member Data Documentation
folly::Optional<PrivKey> fizz::X25519KeyExchange::privKey_ private
Definition at line 35 of file X25519.h.
folly::Optional<PubKey> fizz::X25519KeyExchange::pubKey_ private
Definition at line 36 of file X25519.h.
The documentation for this class was generated from the following files:
proxygen/fizz/fizz/crypto/exchange/X25519.h
proxygen/fizz/fizz/crypto/exchange/X25519.cpp