proxygen: folly::pushmi::any_flow_many_sender< PE, PV, E, VN > Class Template Reference
folly::pushmi::any_flow_many_sender< PE, PV, E, VN > Class Template Reference
#include <flow_many_sender.h>
Classes
union data
struct vtable
Public Types
using properties = property_set< is_sender<>, is_flow<>, is_many<>>
Public Member Functions
any_flow_many_sender ()=default
any_flow_many_sender (any_flow_many_sender &&that) noexcept
requires FlowSender< wrapped_t< Wrapped >, is_many<> > any_flow_many_sender (Wrapped obj) noexcept(insitu< Wrapped >())
~any_flow_many_sender ()
any_flow_many_sender & operator= (any_flow_many_sender &&that) noexcept
any_executor< E > executor ()
void submit (any_flow_receiver< PE, PV, E, VN... > out)
Private Types
template<class T , class U = std::decay_t<T>>
using wrapped_t = std::enable_if_t<!std::is_same< U, any_flow_many_sender >::value, U >
Private Member Functions
template<class Wrapped >
any_flow_many_sender (Wrapped obj, std::false_type)
template<class Wrapped >
any_flow_many_sender (Wrapped obj, std::true_type) noexcept
Static Private Member Functions
template<class Wrapped >
static constexpr bool insitu ()
Private Attributes
union folly::pushmi::any_flow_many_sender::data data_
vtable const * vptr_ = &noop_
Static Private Attributes
static constexpr vtable const noop_ {}
Detailed Description
template<class PE, class PV, class E, class... VN>
class folly::pushmi::any_flow_many_sender< PE, PV, E, VN >
Definition at line 26 of file flow_many_sender.h.
Member Typedef Documentation
template<class PE , class PV , class E , class... VN> using folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::properties = property_set<is_sender<>, is_flow<>, is_many<>>
Definition at line 94 of file flow_many_sender.h.
template<class PE , class PV , class E , class... VN> template<class T , class U = std::decay_t<T>> using folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::wrapped_t = std::enable_if_t<!std::is_same<U, any_flow_many_sender>::value, U> private
Definition at line 92 of file flow_many_sender.h.
Constructor & Destructor Documentation
template<class PE , class PV , class E , class... VN> template<class Wrapped > folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::any_flow_many_sender (Wrapped obj, std::false_type) inline private
Definition at line 47 of file flow_many_sender.h.
References upload::const, folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::data_, folly::exchange(), folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::executor(), folly::pushmi::executor, folly::gen::move, folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::data::pobj_, s, folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::submit(), and submit.
                                                    : any_flow_many_sender() {
     struct s {
       static void op(data& src, data* dst) {
         if (dst)
           dst->pobj_ = std::exchange(src.pobj_, nullptr);
         delete static_cast<Wrapped const*>(src.pobj_);
       }
       static any_executor<E> executor(data& src) {
         return any_executor<E>{
             ::folly::pushmi::executor(*static_cast<Wrapped*>(src.pobj_))};
       }
       static void submit(data& src, any_flow_receiver<PE, PV, E, VN...> out) {
         ::folly::pushmi::submit(
             *static_cast<Wrapped*>(src.pobj_), std::move(out));
       }
     };
     static const vtable vtbl{s::op, s::executor, s::submit};
     data_.pobj_ = new Wrapped(std::move(obj));
     vptr_ = &vtbl;
   }
template<class PE , class PV , class E , class... VN> template<class Wrapped > folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::any_flow_many_sender (Wrapped obj, std::true_type) inline private noexcept
Definition at line 68 of file flow_many_sender.h.
References folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::data::buffer_, upload::const, folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::data_, folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::executor(), folly::pushmi::executor, folly::gen::move, s, folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::submit(), and submit.
     : any_flow_many_sender() {
     struct s {
       static void op(data& src, data* dst) {
         if (dst)
           new (dst->buffer_) Wrapped(
               std::move(*static_cast<Wrapped*>((void*)src.buffer_)));
         static_cast<Wrapped const*>((void*)src.buffer_)->~Wrapped();
       }
       static any_executor<E> executor(data& src) {
         return any_executor<E>{::folly::pushmi::executor(
             *static_cast<Wrapped*>((void*)src.buffer_))};
       }
       static void submit(data& src, any_flow_receiver<PE, PV, E, VN...> out) {
         ::folly::pushmi::submit(
             *static_cast<Wrapped*>((void*)src.buffer_), std::move(out));
       }
     };
     static const vtable vtbl{s::op, s::executor, s::submit};
     new (data_.buffer_) Wrapped(std::move(obj));
     vptr_ = &vtbl;
   }
template<class PE , class PV , class E , class... VN> folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::any_flow_many_sender () default
Referenced by folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::operator=().
template<class PE , class PV , class E , class... VN> folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::any_flow_many_sender (any_flow_many_sender< PE, PV, E, VN > && that) inline noexcept
Definition at line 97 of file flow_many_sender.h.
References folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::data_, folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::vtable::op_, folly::pushmi::PUSHMI_TEMPLATE(), folly::pushmi::requires(), folly::f14::swap(), and folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::vptr_.
       : any_flow_many_sender() {
     that.vptr_->op_(that.data_, &data_);
     std::swap(that.vptr_, vptr_);
   }
template<class PE , class PV , class E , class... VN> requires FlowSender<wrapped_t<Wrapped>, is_many<> > folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::any_flow_many_sender (Wrapped obj) inline explicit noexcept
Definition at line 104 of file flow_many_sender.h.
References folly::gen::move.
     : any_flow_many_sender{std::move(obj), bool_<insitu<Wrapped>()>{}} {}
template<class PE , class PV , class E , class... VN> folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::~any_flow_many_sender () inline
Definition at line 106 of file flow_many_sender.h.
References folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::data_, and folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::vtable::op_.
Referenced by folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::operator=().
{
     vptr_->op_(data_, nullptr);
   }
Member Function Documentation
template<class PE , class PV , class E , class... VN> any_executor<E> folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::executor () inline
Definition at line 114 of file flow_many_sender.h.
References folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::data_, and folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::vtable::executor_.
Referenced by folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::any_flow_many_sender().
{
     return vptr_->executor_(data_);
   }
template<class PE , class PV , class E , class... VN> template<class Wrapped > static constexpr bool folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::insitu () inline static private
Definition at line 32 of file flow_many_sender.h.
References folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::data::buffer_, and value.
{
     return sizeof(Wrapped) <= sizeof(data::buffer_) &&
         std::is_nothrow_move_constructible<Wrapped>::value;
   }
template<class PE , class PV , class E , class... VN> any_flow_many_sender& folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::operator= (any_flow_many_sender< PE, PV, E, VN > && that) inline noexcept
Definition at line 109 of file flow_many_sender.h.
References folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::any_flow_many_sender(), folly::gen::move, and folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::~any_flow_many_sender().
{
     this->~any_flow_many_sender();
     new ((void*)this) any_flow_many_sender(std::move(that));
     return *this;
   }
template<class PE , class PV , class E , class... VN> void folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::submit (any_flow_receiver< PE, PV, E, VN... > out) inline
Definition at line 117 of file flow_many_sender.h.
References folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::data_, folly::gen::move, folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::noop_, and folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::vtable::submit_.
Referenced by folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::any_flow_many_sender().
{
     vptr_->submit_(data_, std::move(out));
   }
Member Data Documentation
template<class PE , class PV , class E , class... VN> union folly::pushmi::any_flow_many_sender::data folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::data_ private
Referenced by folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::any_flow_many_sender(), folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::executor(), folly::pushmi::flow_many_sender< Data, DSF, DEXF >::PUSHMI_EXP(), folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::submit(), and folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::~any_flow_many_sender().
template<class PE , class PV , class E , class... VN> constexpr any_flow_many_sender< PE, PV, E, VN... >::vtable const folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::noop_ {} static private
Definition at line 44 of file flow_many_sender.h.
Referenced by folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::submit().
template<class PE , class PV , class E , class... VN> vtable const* folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::vptr_ = &noop_ private
Definition at line 45 of file flow_many_sender.h.
Referenced by folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::any_flow_many_sender().
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/pushmi/flow_many_sender.h