proxygen: testing::internal::InvokeAction< FunctionImpl > Class Template Reference
testing::internal::InvokeAction< FunctionImpl > Class Template Reference
#include <gmock-more-actions.h>
Public Member Functions
InvokeAction (FunctionImpl function_impl)
template<typename Result , typename ArgumentTuple >
Result Perform (const ArgumentTuple &args)
InvokeAction (FunctionImpl function_impl)
template<typename Result , typename ArgumentTuple >
Result Perform (const ArgumentTuple &args)
InvokeAction (FunctionImpl function_impl)
template<typename Result , typename ArgumentTuple >
Result Perform (const ArgumentTuple &args)
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (InvokeAction)
GTEST_DISALLOW_ASSIGN_ (InvokeAction)
GTEST_DISALLOW_ASSIGN_ (InvokeAction)
Private Attributes
FunctionImpl function_impl_
Detailed Description
template<typename FunctionImpl>
class testing::internal::InvokeAction< FunctionImpl >
Definition at line 52 of file gmock-more-actions.h.
Constructor & Destructor Documentation
template<typename FunctionImpl > testing::internal::InvokeAction< FunctionImpl >::InvokeAction (FunctionImpl function_impl) inline explicit
Definition at line 56 of file gmock-more-actions.h.
       : function_impl_(function_impl) {}
template<typename FunctionImpl > testing::internal::InvokeAction< FunctionImpl >::InvokeAction (FunctionImpl function_impl) inline explicit
Definition at line 56 of file gmock-more-actions.h.
       : function_impl_(function_impl) {}
template<typename FunctionImpl > testing::internal::InvokeAction< FunctionImpl >::InvokeAction (FunctionImpl function_impl) inline explicit
Definition at line 56 of file gmock-more-actions.h.
       : function_impl_(function_impl) {}
Member Function Documentation
template<typename FunctionImpl > testing::internal::InvokeAction< FunctionImpl >::GTEST_DISALLOW_ASSIGN_ (InvokeAction< FunctionImpl >) private
Referenced by testing::internal::InvokeAction< FunctionImpl >::Perform(), and testing::internal::InvokeMethodAction< Class, MethodPtr >::Perform().
template<typename FunctionImpl > testing::internal::InvokeAction< FunctionImpl >::GTEST_DISALLOW_ASSIGN_ (InvokeAction< FunctionImpl >) private
template<typename FunctionImpl > testing::internal::InvokeAction< FunctionImpl >::GTEST_DISALLOW_ASSIGN_ (InvokeAction< FunctionImpl >) private
template<typename FunctionImpl > template<typename Result , typename ArgumentTuple > Result testing::internal::InvokeAction< FunctionImpl >::Perform (const ArgumentTuple & args) inline
Definition at line 60 of file gmock-more-actions.h.
References testing::internal::InvokeAction< FunctionImpl >::function_impl_, and testing::Invoke().
{
     return InvokeHelper<Result, ArgumentTuple>::Invoke(function_impl_, args);
   }
template<typename FunctionImpl > template<typename Result , typename ArgumentTuple > Result testing::internal::InvokeAction< FunctionImpl >::Perform (const ArgumentTuple & args) inline
Definition at line 60 of file gmock-more-actions.h.
References testing::internal::InvokeAction< FunctionImpl >::function_impl_, testing::internal::InvokeAction< FunctionImpl >::GTEST_DISALLOW_ASSIGN_(), and testing::Invoke().
{
     return InvokeHelper<Result, ArgumentTuple>::Invoke(function_impl_, args);
   }
template<typename FunctionImpl > template<typename Result , typename ArgumentTuple > Result testing::internal::InvokeAction< FunctionImpl >::Perform (const ArgumentTuple & args) inline
Definition at line 60 of file gmock-more-actions.h.
References testing::internal::InvokeAction< FunctionImpl >::function_impl_, testing::internal::InvokeAction< FunctionImpl >::GTEST_DISALLOW_ASSIGN_(), and testing::Invoke().
{
     return InvokeHelper<Result, ArgumentTuple>::Invoke(function_impl_, args);
   }
Member Data Documentation
template<typename FunctionImpl > FunctionImpl testing::internal::InvokeAction< FunctionImpl >::function_impl_ private
Definition at line 65 of file gmock-more-actions.h.
Referenced by testing::internal::InvokeAction< FunctionImpl >::Perform().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-more-actions.h