proxygen: wangle::AcceptorHandshakeManager Class Reference
wangle::AcceptorHandshakeManager Class Reference abstract
#include <AcceptorHandshakeManager.h>
Public Member Functions
AcceptorHandshakeManager (Acceptor *acceptor, const folly::SocketAddress &clientAddr, std::chrono::steady_clock::time_point acceptTime, TransportInfo tinfo)
~AcceptorHandshakeManager () override=default
virtual void start (folly::AsyncSSLSocket::UniquePtr sock) noexcept
void timeoutExpired () noexceptoverride
void describe (std::ostream &os) const override
bool isBusy () const override
void notifyPendingShutdown () override
void closeWhenIdle () override
void dropConnection () override
void dropConnection (SSLErrorEnum reason)
void dumpConnectionState (uint8_t) override
Public Member Functions inherited from wangle::ManagedConnection
ManagedConnection ()
virtual std::chrono::milliseconds getIdleTime () const
void fireNotifyPendingShutdown ()
void fireCloseWhenIdle (bool force_to_close=false)
virtual void resetTimeout ()
void resetTimeoutTo (std::chrono::milliseconds)
virtual void scheduleTimeout (folly::HHWheelTimer::Callback *callback, std::chrono::milliseconds timeout)
ConnectionManager * getConnectionManager ()
Public Member Functions inherited from folly::HHWheelTimer::Callback
Callback ()=default
virtual ~Callback ()
virtual void callbackCanceled () noexcept
void cancelTimeout ()
bool isScheduled () const
std::chrono::milliseconds getTimeRemaining ()
Public Member Functions inherited from folly::DelayedDestruction
virtual void destroy ()
bool getDestroyPending () const
Public Member Functions inherited from folly::DelayedDestructionBase
virtual ~DelayedDestructionBase ()=default
Public Member Functions inherited from wangle::AcceptorHandshakeHelper::Callback
virtual ~Callback ()=default
Protected Member Functions
void connectionReady (folly::AsyncTransportWrapper::UniquePtr transport, std::string nextProtocol, SecureTransportType secureTransportType, folly::Optional< SSLErrorEnum > details) noexceptoverride
void connectionError (folly::AsyncTransportWrapper *transport, folly::exception_wrapper ex, folly::Optional< SSLErrorEnum > details) noexceptoverride
std::chrono::milliseconds timeSinceAcceptMs () const
virtual void startHelper (folly::AsyncSSLSocket::UniquePtr sock)=0
void startHandshakeTimeout ()
Protected Member Functions inherited from wangle::ManagedConnection
~ManagedConnection () override
Protected Member Functions inherited from folly::HHWheelTimer::Callback
virtual std::chrono::steady_clock::time_point getCurTime ()
Protected Member Functions inherited from folly::DelayedDestruction
~DelayedDestruction () override=default
DelayedDestruction ()
Protected Member Functions inherited from folly::DelayedDestructionBase
DelayedDestructionBase ()
uint32_t getDestructorGuardCount () const
Protected Attributes
Acceptor * acceptor_
folly::SocketAddress clientAddr_
std::chrono::steady_clock::time_point acceptTime_
TransportInfo tinfo_
AcceptorHandshakeHelper::UniquePtr helper_
Detailed Description
Definition at line 70 of file AcceptorHandshakeManager.h.
Constructor & Destructor Documentation
wangle::AcceptorHandshakeManager::AcceptorHandshakeManager (Acceptor * acceptor, const folly::SocketAddress & clientAddr, std::chrono::steady_clock::time_point acceptTime, TransportInfo tinfo) inline
Definition at line 73 of file AcceptorHandshakeManager.h.
References folly::pushmi::__adl::noexcept(), and wangle::AcceptorHandshakeHelper::start().
                            :
     acceptor_(acceptor),
     clientAddr_(clientAddr),
     acceptTime_(acceptTime),
     tinfo_(std::move(tinfo)) {}
wangle::AcceptorHandshakeManager::~AcceptorHandshakeManager () override default
Member Function Documentation
void wangle::AcceptorHandshakeManager::closeWhenIdle () inline override virtual
Instruct the connection that it should shutdown as soon as it is safe. This is called after notifyPendingShutdown().
Implements wangle::ManagedConnection.
Definition at line 102 of file AcceptorHandshakeManager.h.
 {}
void wangle::AcceptorHandshakeManager::connectionError (folly::AsyncTransportWrapper * transport, folly::exception_wrapper ex, folly::Optional< SSLErrorEnum > sslErr) override protected virtual noexcept
Called if an error was encountered while performing handshake.
If sslErr is set, Acceptor::updateSSLStats will be called.
Implements wangle::AcceptorHandshakeHelper::Callback.
Definition at line 52 of file AcceptorHandshakeManager.cpp.
References acceptor_, destroy(), and folly::gen::move.
{
   if (sslErr) {
     acceptor_->updateSSLStats(
         transport, timeSinceAcceptMs(), sslErr.value());
   }
   acceptor_->getConnectionManager()->removeConnection(this);
   acceptor_->sslConnectionError(std::move(ex));
   destroy();
 }
void wangle::AcceptorHandshakeManager::connectionReady (folly::AsyncTransportWrapper::UniquePtr transport, std::string nextProtocol, SecureTransportType secureTransportType, folly::Optional< SSLErrorEnum > sslErr) override protected virtual noexcept
Called after handshake has been completed successfully.
If sslErr is set, Acceptor::updateSSLStats will be called.
Implements wangle::AcceptorHandshakeHelper::Callback.
Definition at line 29 of file AcceptorHandshakeManager.cpp.
References acceptor_, destroy(), and folly::gen::move.
{
   if (sslErr) {
     acceptor_->updateSSLStats(
         transport.get(),
         timeSinceAcceptMs(),
         sslErr.value());
   }
   acceptor_->getConnectionManager()->removeConnection(this);
   // We pass TransportInfo by reference even though we're about to destroy it,
   // so lets hope that anything saving it makes a copy!
   acceptor_->sslConnectionReady(
       std::move(transport),
       std::move(clientAddr_),
       std::move(nextProtocol),
       secureTransportType,
       tinfo_);
   destroy();
 }
void wangle::AcceptorHandshakeManager::describe (std::ostream & os) const inline override virtual
Print a human-readable description of the connection.
Parameters
os Destination stream.
Implements wangle::ManagedConnection.
Definition at line 92 of file AcceptorHandshakeManager.h.
{
     os << "pending handshake on " << clientAddr_;
   }
void wangle::AcceptorHandshakeManager::dropConnection () inline override virtual
Forcibly drop a connection.
If a request is in progress, this should cause the connection to be closed with a reset.
Implements wangle::ManagedConnection.
Definition at line 104 of file AcceptorHandshakeManager.h.
References wangle::AcceptorHandshakeHelper::dropConnection(), and wangle::NO_ERROR.
{
     dropConnection(SSLErrorEnum::NO_ERROR);
   }
void wangle::AcceptorHandshakeManager::dropConnection (SSLErrorEnum reason) inline
Definition at line 108 of file AcceptorHandshakeManager.h.
{
     VLOG(10) << "Dropping in progress handshake for " << clientAddr_;
     helper_->dropConnection(reason);
   }
void wangle::AcceptorHandshakeManager::dumpConnectionState (uint8_t loglevel) inline override virtual
Dump the state of the connection to the log
Implements wangle::ManagedConnection.
Definition at line 113 of file AcceptorHandshakeManager.h.
References wangle::AcceptorHandshakeHelper::Callback::connectionError(), wangle::AcceptorHandshakeHelper::Callback::connectionReady(), and string.
 {}
bool wangle::AcceptorHandshakeManager::isBusy () const inline override virtual
Check whether the connection has any requests outstanding.
Implements wangle::ManagedConnection.
Definition at line 96 of file AcceptorHandshakeManager.h.
{
     return true;
   }
void wangle::AcceptorHandshakeManager::notifyPendingShutdown () inline override virtual
Notify the connection that a shutdown is pending. This method will be called at the beginning of graceful shutdown.
Implements wangle::ManagedConnection.
Definition at line 100 of file AcceptorHandshakeManager.h.
 {}
void wangle::AcceptorHandshakeManager::start (folly::AsyncSSLSocket::UniquePtr sock) virtual noexcept
Definition at line 22 of file AcceptorHandshakeManager.cpp.
References acceptor_, and folly::gen::move.
Referenced by wangle::Acceptor::startHandshakeManager().
{
   acceptor_->getConnectionManager()->addConnection(this, true);
   startHelper(std::move(sock));
   startHandshakeTimeout();
 }
void wangle::AcceptorHandshakeManager::startHandshakeTimeout () protected
Definition at line 70 of file AcceptorHandshakeManager.cpp.
References acceptor_, wangle::Acceptor::getConnectionManager(), wangle::Acceptor::getSSLHandshakeTimeout(), and wangle::ConnectionManager::scheduleTimeout().
{
   auto handshake_timeout = acceptor_->getSSLHandshakeTimeout();
   acceptor_->getConnectionManager()->scheduleTimeout(
       this, handshake_timeout);
 }
virtual void wangle::AcceptorHandshakeManager::startHelper (folly::AsyncSSLSocket::UniquePtr sock) protected pure virtual
Implemented in wangle::PeekingAcceptorHandshakeManager.
void wangle::AcceptorHandshakeManager::timeoutExpired () inline override virtual noexcept
timeoutExpired() is invoked when the timeout has expired.
Implements wangle::ManagedConnection.
Definition at line 87 of file AcceptorHandshakeManager.h.
References wangle::AcceptorHandshakeHelper::dropConnection(), and wangle::TIMEOUT.
{
     VLOG(4) << "SSL handshake timeout expired";
     dropConnection(SSLErrorEnum::TIMEOUT);
   }
std::chrono::milliseconds wangle::AcceptorHandshakeManager::timeSinceAcceptMs () const protected
Definition at line 65 of file AcceptorHandshakeManager.cpp.
References acceptTime_, and now().
{
   return std::chrono::duration_cast<std::chrono::milliseconds>(
       std::chrono::steady_clock::now() - acceptTime_);
 }
Member Data Documentation
Acceptor* wangle::AcceptorHandshakeManager::acceptor_ protected
Definition at line 135 of file AcceptorHandshakeManager.h.
Referenced by startHandshakeTimeout().
std::chrono::steady_clock::time_point wangle::AcceptorHandshakeManager::acceptTime_ protected
Definition at line 137 of file AcceptorHandshakeManager.h.
Referenced by timeSinceAcceptMs().
folly::SocketAddress wangle::AcceptorHandshakeManager::clientAddr_ protected
Definition at line 136 of file AcceptorHandshakeManager.h.
AcceptorHandshakeHelper::UniquePtr wangle::AcceptorHandshakeManager::helper_ protected
Definition at line 139 of file AcceptorHandshakeManager.h.
TransportInfo wangle::AcceptorHandshakeManager::tinfo_ protected
Definition at line 138 of file AcceptorHandshakeManager.h.
The documentation for this class was generated from the following files:
proxygen/wangle/wangle/acceptor/AcceptorHandshakeManager.h
proxygen/wangle/wangle/acceptor/AcceptorHandshakeManager.cpp