proxygen: MultiFilePollerTest Class Reference
MultiFilePollerTest Class Reference
Public Member Functions
void SetUp () override
void delayedWrite (const std::string &path, const std::string &data)
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Protected Attributes
std::unique_ptr< MultiFilePoller > updater_
std::string tmpdirPath_
TemporaryDirectory tmpdir_ {"MultiFilePollerTest"}
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Protected Member Functions inherited from testing::Test
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Detailed Description
Definition at line 38 of file MultiFilePollerTest.cpp.
Member Function Documentation
void MultiFilePollerTest::delayedWrite (const std::string & path, const std::string & data) inline
Definition at line 45 of file MultiFilePollerTest.cpp.
References ASSERT_TRUE, kWriteWaitMs, folly::makeFuture(), folly::detail::distributed_mutex::wait(), and folly::writeFile().
{
     // The delay makes sure mtime (in granularity of sec) of the modified
     // file is increased by at least 1. Otherwise wangle::FilePoller may not
     // detect the change.
     folly::makeFuture()
         .delayed(kWriteWaitMs)
         .thenValue(
             [&](auto&&) { ASSERT_TRUE(folly::writeFile(data, path.c_str())); })
         .wait();
   }
void MultiFilePollerTest::SetUp () inline override virtual
Reimplemented from testing::Test.
Definition at line 40 of file MultiFilePollerTest.cpp.
References kPollIntervalMs.
{
     updater_.reset(new MultiFilePoller(kPollIntervalMs));
     tmpdirPath_ = folly::fs::canonical(tmpdir_.path()).string();
   }
Member Data Documentation
TemporaryDirectory MultiFilePollerTest::tmpdir_ {"MultiFilePollerTest"} protected
Definition at line 59 of file MultiFilePollerTest.cpp.
std::string MultiFilePollerTest::tmpdirPath_ protected
Definition at line 58 of file MultiFilePollerTest.cpp.
std::unique_ptr<MultiFilePoller> MultiFilePollerTest::updater_ protected
Definition at line 57 of file MultiFilePollerTest.cpp.
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/util/test/MultiFilePollerTest.cpp