proxygen: folly::XlogLevelInfo< IsInHeaderFile > Class Template Reference
folly::XlogLevelInfo< IsInHeaderFile > Class Template Reference
#include <xlog.h>
Public Member Functions
bool check (LogLevel levelToCheck, folly::StringPiece categoryName, bool isOverridden, XlogFileScopeInfo *)
Private Member Functions
LogLevel loadLevelFull (folly::StringPiece categoryName, bool isOverridden)
Private Attributes
std::atomic< LogLevel > level_
Detailed Description
template<bool IsInHeaderFile>
class folly::XlogLevelInfo< IsInHeaderFile >
A file-static XlogLevelInfo and XlogCategoryInfo object is declared for each XLOG() statement.
We intentionally do not provide constructors for these structures, and rely on their members to be zero-initialized when the program starts. This ensures that everything will work as desired even if XLOG() statements are used during dynamic object initialization before main().
Definition at line 381 of file xlog.h.
Member Function Documentation
template<bool IsInHeaderFile> bool folly::XlogLevelInfo< IsInHeaderFile >::check (LogLevel levelToCheck, folly::StringPiece categoryName, bool isOverridden, XlogFileScopeInfo *) inline
Definition at line 383 of file xlog.h.
References LIKELY.
{
     // Do an initial relaxed check.  If this fails we know the category level
     // is initialized and the log admittance check failed.
     // Use LIKELY() to optimize for the case of disabled debug statements:
     // we disabled debug statements to be cheap.  If the log message is
     // enabled then this check will still be minimal perf overhead compared to
     // the overall cost of logging it.
     if (LIKELY(levelToCheck < level_.load(std::memory_order_relaxed))) {
       return false;
     }
     // If we are still here, then either:
     // - The log level check actually passed, or
     // - level_ has not been initialized yet, and we have to initialize it and
     //   then re-perform the check.
     //
     // Do this work in a separate helper method.  It is intentionally defined
     // in the xlog.cpp file to avoid inlining, to reduce the amount of code
     // emitted for each XLOG() statement.
     auto currentLevel = loadLevelFull(categoryName, isOverridden);
     return levelToCheck >= currentLevel;
   }
template<bool IsInHeaderFile> LogLevel folly::XlogLevelInfo< IsInHeaderFile >::loadLevelFull (folly::StringPiece categoryName, bool isOverridden) private
Definition at line 72 of file xlog.cpp.
References folly::LoggerDB::get(), folly::getXlogCategoryNameForFile(), folly::UNINITIALIZED, UNLIKELY, and folly::LoggerDB::xlogInit().
Referenced by folly::XlogCategoryInfo< IsInHeaderFile >::init().
{
   auto currentLevel = level_.load(std::memory_order_acquire);
   if (UNLIKELY(currentLevel == ::folly::LogLevel::UNINITIALIZED)) {
     return LoggerDB::get().xlogInit(
         isOverridden ? categoryName : getXlogCategoryNameForFile(categoryName),
         &level_,
         nullptr);
   }
   return currentLevel;
 }
Member Data Documentation
template<bool IsInHeaderFile> std::atomic<LogLevel> folly::XlogLevelInfo< IsInHeaderFile >::level_ private
Definition at line 415 of file xlog.h.
The documentation for this class was generated from the following files:
proxygen/folly/folly/logging/xlog.h
proxygen/folly/folly/logging/xlog.cpp