proxygen: testing::internal::ScopedTrace Class Reference
testing::internal::ScopedTrace Class Reference
#include <gtest-internal.h>
Public Member Functions
ScopedTrace (const char *file, int line, const Message &message)
~ScopedTrace ()
ScopedTrace (const char *file, int line, const Message &message)
~ScopedTrace ()
ScopedTrace (const char *file, int line, const Message &message)
~ScopedTrace ()
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (ScopedTrace)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (ScopedTrace)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (ScopedTrace)
Detailed Description
Definition at line 156 of file gtest-internal.h.
Constructor & Destructor Documentation
testing::internal::ScopedTrace::ScopedTrace (const char * file, int line, const Message & message)
Definition at line 3828 of file gtest.cc.
References testing::internal::TraceInfo::file, testing::UnitTest::GetInstance(), testing::internal::TraceInfo::line, testing::internal::TraceInfo::message, and testing::UnitTest::PushGTestTrace().
Referenced by testing::internal::PortableLocaltime().
{
   TraceInfo trace;
   trace.file = file;
   trace.line = line;
   trace.message = message.GetString();
   UnitTest::GetInstance()->PushGTestTrace(trace);
 }
testing::internal::ScopedTrace::~ScopedTrace ()
Definition at line 3839 of file gtest.cc.
References testing::UnitTest::GetInstance(), GTEST_NAME_, testing::internal::OsStackTraceGetterInterface::kElidedFramesMarker, and testing::UnitTest::PopGTestTrace().
Referenced by testing::internal::PortableLocaltime().
{
   UnitTest::GetInstance()->PopGTestTrace();
 }
testing::internal::ScopedTrace::ScopedTrace (const char * file, int line, const Message & message)
testing::internal::ScopedTrace::~ScopedTrace ()
testing::internal::ScopedTrace::ScopedTrace (const char * file, int line, const Message & message)
testing::internal::ScopedTrace::~ScopedTrace ()
Member Function Documentation
testing::internal::ScopedTrace::GTEST_DISALLOW_COPY_AND_ASSIGN_ (ScopedTrace) private
testing::internal::ScopedTrace::GTEST_DISALLOW_COPY_AND_ASSIGN_ (ScopedTrace) private
testing::internal::ScopedTrace::GTEST_DISALLOW_COPY_AND_ASSIGN_ (ScopedTrace) private
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/internal/gtest-internal.h
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest.cc