proxygen: testing::TestProperty Class Reference
testing::TestProperty Class Reference
#include <gtest.h>
Public Member Functions
TestProperty (const std::string &a_key, const std::string &a_value)
const char * key () const
const char * value () const
void SetValue (const std::string &new_value)
TestProperty (const std::string &a_key, const std::string &a_value)
const char * key () const
const char * value () const
void SetValue (const std::string &new_value)
TestProperty (const std::string &a_key, const std::string &a_value)
const char * key () const
const char * value () const
void SetValue (const std::string &new_value)
Private Attributes
std::string key_
std::string value_
Detailed Description
Definition at line 486 of file gtest.h.
Constructor & Destructor Documentation
testing::TestProperty::TestProperty (const std::string & a_key, const std::string & a_value) inline
Definition at line 491 of file gtest.h.
                                                                  :
     key_(a_key), value_(a_value) {
   }
testing::TestProperty::TestProperty (const std::string & a_key, const std::string & a_value) inline
Definition at line 491 of file gtest.h.
                                                                  :
     key_(a_key), value_(a_value) {
   }
testing::TestProperty::TestProperty (const std::string & a_key, const std::string & a_value) inline
Definition at line 491 of file gtest.h.
                                                                  :
     key_(a_key), value_(a_value) {
   }
Member Function Documentation
const char* testing::TestProperty::key () const inline
Definition at line 496 of file gtest.h.
Referenced by testing::FormatWordList(), testing::internal::TestPropertyKeyIs::operator()(), operator<<(), testing::TestResult::RecordProperty(), and testing::TestResult::ValidateTestProperty().
{
     return key_.c_str();
   }
const char* testing::TestProperty::key () const inline
Definition at line 496 of file gtest.h.
{
     return key_.c_str();
   }
const char* testing::TestProperty::key () const inline
Definition at line 496 of file gtest.h.
{
     return key_.c_str();
   }
void testing::TestProperty::SetValue (const std::string & new_value) inline
Definition at line 506 of file gtest.h.
{
     value_ = new_value;
   }
void testing::TestProperty::SetValue (const std::string & new_value) inline
Definition at line 506 of file gtest.h.
References GTEST_API_, and string.
{
     value_ = new_value;
   }
void testing::TestProperty::SetValue (const std::string & new_value) inline
Definition at line 506 of file gtest.h.
References GTEST_API_, and string.
{
     value_ = new_value;
   }
const char* testing::TestProperty::value () const inline
Definition at line 501 of file gtest.h.
Referenced by operator<<(), and testing::TestResult::RecordProperty().
{
     return value_.c_str();
   }
const char* testing::TestProperty::value () const inline
Definition at line 501 of file gtest.h.
{
     return value_.c_str();
   }
const char* testing::TestProperty::value () const inline
Definition at line 501 of file gtest.h.
{
     return value_.c_str();
   }
Member Data Documentation
std::string testing::TestProperty::key_ private
Definition at line 512 of file gtest.h.
std::string testing::TestProperty::value_ private
Definition at line 514 of file gtest.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/gtest.h