proxygen: testing::internal::PairMatcherImpl< PairType > Class Template Reference
testing::internal::PairMatcherImpl< PairType > Class Template Reference
#include <gmock-matchers.h>
Public Types
typedef RawPairType::first_type FirstType
typedef RawPairType::second_type SecondType
typedef RawPairType::first_type FirstType
typedef RawPairType::second_type SecondType
typedef RawPairType::first_type FirstType
typedef RawPairType::second_type SecondType
Public Member Functions
typedef GTEST_REMOVE_REFERENCE_AND_CONST_ (PairType) RawPairType
template<typename FirstMatcher , typename SecondMatcher >
PairMatcherImpl (FirstMatcher first_matcher, SecondMatcher second_matcher)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (PairType a_pair, MatchResultListener *listener) const
typedef GTEST_REMOVE_REFERENCE_AND_CONST_ (PairType) RawPairType
template<typename FirstMatcher , typename SecondMatcher >
PairMatcherImpl (FirstMatcher first_matcher, SecondMatcher second_matcher)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (PairType a_pair, MatchResultListener *listener) const
typedef GTEST_REMOVE_REFERENCE_AND_CONST_ (PairType) RawPairType
template<typename FirstMatcher , typename SecondMatcher >
PairMatcherImpl (FirstMatcher first_matcher, SecondMatcher second_matcher)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (PairType a_pair, MatchResultListener *listener) const
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
virtual ~MatcherDescriberInterface ()
virtual ~MatcherDescriberInterface ()
Private Member Functions
void ExplainSuccess (const internal::string &first_explanation, const internal::string &second_explanation, MatchResultListener *listener) const
GTEST_DISALLOW_ASSIGN_ (PairMatcherImpl)
void ExplainSuccess (const internal::string &first_explanation, const internal::string &second_explanation, MatchResultListener *listener) const
GTEST_DISALLOW_ASSIGN_ (PairMatcherImpl)
void ExplainSuccess (const internal::string &first_explanation, const internal::string &second_explanation, MatchResultListener *listener) const
GTEST_DISALLOW_ASSIGN_ (PairMatcherImpl)
Private Attributes
const Matcher< const FirstType & > first_matcher_
const Matcher< const SecondType & > second_matcher_
Detailed Description
template<typename PairType>
class testing::internal::PairMatcherImpl< PairType >
Definition at line 3001 of file gmock-matchers.h.
Member Typedef Documentation
template<typename PairType > typedef RawPairType::first_type testing::internal::PairMatcherImpl< PairType >::FirstType
Definition at line 3004 of file gmock-matchers.h.
template<typename PairType > typedef RawPairType::first_type testing::internal::PairMatcherImpl< PairType >::FirstType
Definition at line 3004 of file gmock-matchers.h.
template<typename PairType > typedef RawPairType::first_type testing::internal::PairMatcherImpl< PairType >::FirstType
Definition at line 3004 of file gmock-matchers.h.
template<typename PairType > typedef RawPairType::second_type testing::internal::PairMatcherImpl< PairType >::SecondType
Definition at line 3005 of file gmock-matchers.h.
template<typename PairType > typedef RawPairType::second_type testing::internal::PairMatcherImpl< PairType >::SecondType
Definition at line 3005 of file gmock-matchers.h.
template<typename PairType > typedef RawPairType::second_type testing::internal::PairMatcherImpl< PairType >::SecondType
Definition at line 3005 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename PairType > template<typename FirstMatcher , typename SecondMatcher > testing::internal::PairMatcherImpl< PairType >::PairMatcherImpl (FirstMatcher first_matcher, SecondMatcher second_matcher) inline
Definition at line 3008 of file gmock-matchers.h.
       : first_matcher_(
             testing::SafeMatcherCast<const FirstType&>(first_matcher)),
         second_matcher_(
             testing::SafeMatcherCast<const SecondType&>(second_matcher)) {
   }
template<typename PairType > template<typename FirstMatcher , typename SecondMatcher > testing::internal::PairMatcherImpl< PairType >::PairMatcherImpl (FirstMatcher first_matcher, SecondMatcher second_matcher) inline
Definition at line 3008 of file gmock-matchers.h.
       : first_matcher_(
             testing::SafeMatcherCast<const FirstType&>(first_matcher)),
         second_matcher_(
             testing::SafeMatcherCast<const SecondType&>(second_matcher)) {
   }
template<typename PairType > template<typename FirstMatcher , typename SecondMatcher > testing::internal::PairMatcherImpl< PairType >::PairMatcherImpl (FirstMatcher first_matcher, SecondMatcher second_matcher) inline
Definition at line 3008 of file gmock-matchers.h.
       : first_matcher_(
             testing::SafeMatcherCast<const FirstType&>(first_matcher)),
         second_matcher_(
             testing::SafeMatcherCast<const SecondType&>(second_matcher)) {
   }
Member Function Documentation
template<typename PairType > virtual void testing::internal::PairMatcherImpl< PairType >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 3024 of file gmock-matchers.h.
{
     *os << "has a first field that ";
     first_matcher_.DescribeNegationTo(os);
     *os << ", or has a second field that ";
     second_matcher_.DescribeNegationTo(os);
   }
template<typename PairType > virtual void testing::internal::PairMatcherImpl< PairType >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 3024 of file gmock-matchers.h.
{
     *os << "has a first field that ";
     first_matcher_.DescribeNegationTo(os);
     *os << ", or has a second field that ";
     second_matcher_.DescribeNegationTo(os);
   }
template<typename PairType > virtual void testing::internal::PairMatcherImpl< PairType >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 3024 of file gmock-matchers.h.
{
     *os << "has a first field that ";
     first_matcher_.DescribeNegationTo(os);
     *os << ", or has a second field that ";
     second_matcher_.DescribeNegationTo(os);
   }
template<typename PairType > virtual void testing::internal::PairMatcherImpl< PairType >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 3016 of file gmock-matchers.h.
{
     *os << "has a first field that ";
     first_matcher_.DescribeTo(os);
     *os << ", and has a second field that ";
     second_matcher_.DescribeTo(os);
   }
template<typename PairType > virtual void testing::internal::PairMatcherImpl< PairType >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 3016 of file gmock-matchers.h.
{
     *os << "has a first field that ";
     first_matcher_.DescribeTo(os);
     *os << ", and has a second field that ";
     second_matcher_.DescribeTo(os);
   }
template<typename PairType > virtual void testing::internal::PairMatcherImpl< PairType >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 3016 of file gmock-matchers.h.
{
     *os << "has a first field that ";
     first_matcher_.DescribeTo(os);
     *os << ", and has a second field that ";
     second_matcher_.DescribeTo(os);
   }
template<typename PairType > void testing::internal::PairMatcherImpl< PairType >::ExplainSuccess (const internal::string & first_explanation, const internal::string & second_explanation, MatchResultListener * listener) const inline private
Definition at line 3061 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_.
{
     *listener << "whose both fields match";
     if (first_explanation != "") {
       *listener << ", where the first field is a value " << first_explanation;
     }
     if (second_explanation != "") {
       *listener << ", ";
       if (first_explanation != "") {
         *listener << "and ";
       } else {
         *listener << "where ";
       }
       *listener << "the second field is a value " << second_explanation;
     }
   }
template<typename PairType > void testing::internal::PairMatcherImpl< PairType >::ExplainSuccess (const internal::string & first_explanation, const internal::string & second_explanation, MatchResultListener * listener) const inline private
Definition at line 3061 of file gmock-matchers.h.
{
     *listener << "whose both fields match";
     if (first_explanation != "") {
       *listener << ", where the first field is a value " << first_explanation;
     }
     if (second_explanation != "") {
       *listener << ", ";
       if (first_explanation != "") {
         *listener << "and ";
       } else {
         *listener << "where ";
       }
       *listener << "the second field is a value " << second_explanation;
     }
   }
template<typename PairType > void testing::internal::PairMatcherImpl< PairType >::ExplainSuccess (const internal::string & first_explanation, const internal::string & second_explanation, MatchResultListener * listener) const inline private
Definition at line 3061 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_.
{
     *listener << "whose both fields match";
     if (first_explanation != "") {
       *listener << ", where the first field is a value " << first_explanation;
     }
     if (second_explanation != "") {
       *listener << ", ";
       if (first_explanation != "") {
         *listener << "and ";
       } else {
         *listener << "where ";
       }
       *listener << "the second field is a value " << second_explanation;
     }
   }
template<typename PairType > testing::internal::PairMatcherImpl< PairType >::GTEST_DISALLOW_ASSIGN_ (PairMatcherImpl< PairType >) private
template<typename PairType > testing::internal::PairMatcherImpl< PairType >::GTEST_DISALLOW_ASSIGN_ (PairMatcherImpl< PairType >) private
template<typename PairType > testing::internal::PairMatcherImpl< PairType >::GTEST_DISALLOW_ASSIGN_ (PairMatcherImpl< PairType >) private
template<typename PairType > typedef testing::internal::PairMatcherImpl< PairType >::GTEST_REMOVE_REFERENCE_AND_CONST_ (PairType)
template<typename PairType > typedef testing::internal::PairMatcherImpl< PairType >::GTEST_REMOVE_REFERENCE_AND_CONST_ (PairType)
template<typename PairType > typedef testing::internal::PairMatcherImpl< PairType >::GTEST_REMOVE_REFERENCE_AND_CONST_ (PairType)
template<typename PairType > virtual bool testing::internal::PairMatcherImpl< PairType >::MatchAndExplain (PairType a_pair, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< PairType >.
Definition at line 3033 of file gmock-matchers.h.
References testing::internal::PrintIfNotEmpty(), and testing::StringMatchResultListener::str().
{
     if (!listener->IsInterested()) {
       // If the listener is not interested, we don't need to construct the
       // explanation.
       return first_matcher_.Matches(a_pair.first) &&
              second_matcher_.Matches(a_pair.second);
     }
     StringMatchResultListener first_inner_listener;
     if (!first_matcher_.MatchAndExplain(a_pair.first,
                                         &first_inner_listener)) {
       *listener << "whose first field does not match";
       PrintIfNotEmpty(first_inner_listener.str(), listener->stream());
       return false;
     }
     StringMatchResultListener second_inner_listener;
     if (!second_matcher_.MatchAndExplain(a_pair.second,
                                          &second_inner_listener)) {
       *listener << "whose second field does not match";
       PrintIfNotEmpty(second_inner_listener.str(), listener->stream());
       return false;
     }
     ExplainSuccess(first_inner_listener.str(), second_inner_listener.str(),
                    listener);
     return true;
   }
template<typename PairType > virtual bool testing::internal::PairMatcherImpl< PairType >::MatchAndExplain (PairType a_pair, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< PairType >.
Definition at line 3033 of file gmock-matchers.h.
References testing::MatchResultListener::IsInterested(), testing::internal::PrintIfNotEmpty(), testing::StringMatchResultListener::str(), and testing::MatchResultListener::stream().
{
     if (!listener->IsInterested()) {
       // If the listener is not interested, we don't need to construct the
       // explanation.
       return first_matcher_.Matches(a_pair.first) &&
              second_matcher_.Matches(a_pair.second);
     }
     StringMatchResultListener first_inner_listener;
     if (!first_matcher_.MatchAndExplain(a_pair.first,
                                         &first_inner_listener)) {
       *listener << "whose first field does not match";
       PrintIfNotEmpty(first_inner_listener.str(), listener->stream());
       return false;
     }
     StringMatchResultListener second_inner_listener;
     if (!second_matcher_.MatchAndExplain(a_pair.second,
                                          &second_inner_listener)) {
       *listener << "whose second field does not match";
       PrintIfNotEmpty(second_inner_listener.str(), listener->stream());
       return false;
     }
     ExplainSuccess(first_inner_listener.str(), second_inner_listener.str(),
                    listener);
     return true;
   }
template<typename PairType > virtual bool testing::internal::PairMatcherImpl< PairType >::MatchAndExplain (PairType a_pair, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< PairType >.
Definition at line 3033 of file gmock-matchers.h.
References testing::internal::PrintIfNotEmpty(), and testing::StringMatchResultListener::str().
{
     if (!listener->IsInterested()) {
       // If the listener is not interested, we don't need to construct the
       // explanation.
       return first_matcher_.Matches(a_pair.first) &&
              second_matcher_.Matches(a_pair.second);
     }
     StringMatchResultListener first_inner_listener;
     if (!first_matcher_.MatchAndExplain(a_pair.first,
                                         &first_inner_listener)) {
       *listener << "whose first field does not match";
       PrintIfNotEmpty(first_inner_listener.str(), listener->stream());
       return false;
     }
     StringMatchResultListener second_inner_listener;
     if (!second_matcher_.MatchAndExplain(a_pair.second,
                                          &second_inner_listener)) {
       *listener << "whose second field does not match";
       PrintIfNotEmpty(second_inner_listener.str(), listener->stream());
       return false;
     }
     ExplainSuccess(first_inner_listener.str(), second_inner_listener.str(),
                    listener);
     return true;
   }
Member Data Documentation
template<typename PairType > const Matcher< const FirstType & > testing::internal::PairMatcherImpl< PairType >::first_matcher_ private
Definition at line 3079 of file gmock-matchers.h.
template<typename PairType > const Matcher< const SecondType & > testing::internal::PairMatcherImpl< PairType >::second_matcher_ private
Definition at line 3080 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h