proxygen: folly::AsyncTransport::BufferCallback Class Reference
folly::AsyncTransport::BufferCallback Class Reference abstract
#include <AsyncTransport.h>
Public Member Functions
virtual ~BufferCallback ()
virtual void onEgressBuffered ()=0
virtual void onEgressBufferCleared ()=0
Detailed Description
Definition at line 437 of file AsyncTransport.h.
Constructor & Destructor Documentation
virtual folly::AsyncTransport::BufferCallback::~BufferCallback () inline virtual
Definition at line 439 of file AsyncTransport.h.
 {}
Member Function Documentation
virtual void folly::AsyncTransport::BufferCallback::onEgressBufferCleared () pure virtual
Implemented in proxygen::HTTPSession, and BufferCallback.
Referenced by folly::AsyncSocket::handleWrite().
virtual void folly::AsyncTransport::BufferCallback::onEgressBuffered () pure virtual
Implemented in proxygen::HTTPSession, and BufferCallback.
Referenced by folly::AsyncSocket::handleWrite(), and folly::AsyncSocket::writeImpl().
The documentation for this class was generated from the following file:
proxygen/folly/folly/io/async/AsyncTransport.h