proxygen: fizz::server::test::AeadCookieCipherTest Class Reference
fizz::server::test::AeadCookieCipherTest Class Reference
Public Member Functions
void SetUp () override
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Protected Member Functions
Buf getClientHello (Buf cookie)
Protected Member Functions inherited from testing::Test
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Protected Attributes
std::shared_ptr< FizzServerContext > context_
std::shared_ptr< AES128CookieCipher > cipher_
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Detailed Description
Definition at line 40 of file AeadCookieCipherTest.cpp.
Member Function Documentation
Buf fizz::server::test::AeadCookieCipherTest::getClientHello (Buf cookie) inline protected
Definition at line 54 of file AeadCookieCipherTest.cpp.
References c, chlo, fizz::test::TestMessages::clientHello(), fizz::Cookie::cookie, fizz::TLSContent::data, fizz::encodeExtension(), fizz::encodeHandshake(), folly::gen::move, and fizz::PlaintextWriteRecordLayer::writeInitialClientHello().
{
     auto chlo = TestMessages::clientHello();
     if (cookie) {
       Cookie c;
       c.cookie = std::move(cookie);
       chlo.extensions.push_back(encodeExtension(std::move(c)));
     }
     return PlaintextWriteRecordLayer()
         .writeInitialClientHello(encodeHandshake(std::move(chlo)))
         .data;
   }
void fizz::server::test::AeadCookieCipherTest::SetUp () inline override virtual
Reimplemented from testing::Test.
Definition at line 42 of file AeadCookieCipherTest.cpp.
References EXPECT_TRUE, folly::gen::move, s, secret, fizz::tls_1_3, and fizz::test::toIOBuf().
{
     context_ = std::make_shared<FizzServerContext>();
     context_->setSupportedVersions({ProtocolVersion::tls_1_3});
     cipher_ = std::make_shared<AES128CookieCipher>();
     cipher_->setContext(context_.get());
     auto s = toIOBuf(secret);
     std::vector<ByteRange> cookieSecrets{{s->coalesce()}};
     EXPECT_TRUE(cipher_->setCookieSecrets(std::move(cookieSecrets)));
   }
Member Data Documentation
std::shared_ptr<AES128CookieCipher> fizz::server::test::AeadCookieCipherTest::cipher_ protected
Definition at line 69 of file AeadCookieCipherTest.cpp.
std::shared_ptr<FizzServerContext> fizz::server::test::AeadCookieCipherTest::context_ protected
Definition at line 68 of file AeadCookieCipherTest.cpp.
The documentation for this class was generated from the following file:
proxygen/fizz/fizz/server/test/AeadCookieCipherTest.cpp