proxygen: testing::internal::BoundSecondMatcher< Tuple2Matcher, Second > Class Template Reference
testing::internal::BoundSecondMatcher< Tuple2Matcher, Second > Class Template Reference
#include <gmock-matchers.h>
Classes
class Impl
Public Member Functions
BoundSecondMatcher (const Tuple2Matcher &tm, const Second &second)
template<typename T >
operator Matcher< T > () const
void operator= (const BoundSecondMatcher &)
BoundSecondMatcher (const Tuple2Matcher &tm, const Second &second)
template<typename T >
operator Matcher< T > () const
void operator= (const BoundSecondMatcher &)
BoundSecondMatcher (const Tuple2Matcher &tm, const Second &second)
template<typename T >
operator Matcher< T > () const
void operator= (const BoundSecondMatcher &)
Private Attributes
const Tuple2Matcher tuple2_matcher_
const Second second_value_
Detailed Description
template<typename Tuple2Matcher, typename Second>
class testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >
Definition at line 3552 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename Tuple2Matcher, typename Second> testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::BoundSecondMatcher (const Tuple2Matcher & tm, const Second & second) inline
Definition at line 3554 of file gmock-matchers.h.
       : tuple2_matcher_(tm), second_value_(second) {}
template<typename Tuple2Matcher, typename Second> testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::BoundSecondMatcher (const Tuple2Matcher & tm, const Second & second) inline
Definition at line 3554 of file gmock-matchers.h.
       : tuple2_matcher_(tm), second_value_(second) {}
template<typename Tuple2Matcher, typename Second> testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::BoundSecondMatcher (const Tuple2Matcher & tm, const Second & second) inline
Definition at line 3554 of file gmock-matchers.h.
       : tuple2_matcher_(tm), second_value_(second) {}
Member Function Documentation
template<typename Tuple2Matcher, typename Second> template<typename T > testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::operator Matcher< T > () const inline
Definition at line 3558 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(new Impl<T>(tuple2_matcher_, second_value_));
   }
template<typename Tuple2Matcher, typename Second> template<typename T > testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::operator Matcher< T > () const inline
Definition at line 3558 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(new Impl<T>(tuple2_matcher_, second_value_));
   }
template<typename Tuple2Matcher, typename Second> template<typename T > testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::operator Matcher< T > () const inline
Definition at line 3558 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(new Impl<T>(tuple2_matcher_, second_value_));
   }
template<typename Tuple2Matcher, typename Second> void testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::operator= (const BoundSecondMatcher< Tuple2Matcher, Second > &) inline
Definition at line 3570 of file gmock-matchers.h.
References GTEST_LOG_.
{
     GTEST_LOG_(FATAL) << "BoundSecondMatcher should never be assigned.";
   }
template<typename Tuple2Matcher, typename Second> void testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::operator= (const BoundSecondMatcher< Tuple2Matcher, Second > &) inline
Definition at line 3570 of file gmock-matchers.h.
References GTEST_LOG_.
{
     GTEST_LOG_(FATAL) << "BoundSecondMatcher should never be assigned.";
   }
template<typename Tuple2Matcher, typename Second> void testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::operator= (const BoundSecondMatcher< Tuple2Matcher, Second > &) inline
Definition at line 3570 of file gmock-matchers.h.
References GTEST_LOG_.
{
     GTEST_LOG_(FATAL) << "BoundSecondMatcher should never be assigned.";
   }
Member Data Documentation
template<typename Tuple2Matcher, typename Second> const Second testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::second_value_ private
Definition at line 3604 of file gmock-matchers.h.
template<typename Tuple2Matcher, typename Second> const Tuple2Matcher testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::tuple2_matcher_ private
Definition at line 3603 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h