proxygen: testing::internal2::TypeWithoutFormatter< T, kConvertibleToInteger > Class Template Reference
testing::internal2::TypeWithoutFormatter< T, kConvertibleToInteger > Class Template Reference
#include <gtest-printers.h>
Static Public Member Functions
static void PrintValue (const T &value,::std::ostream *os)
static void PrintValue (const T &value,::std::ostream *os)
static void PrintValue (const T &value,::std::ostream *os)
Detailed Description
template<typename T>
class testing::internal2::TypeWithoutFormatter< T, kConvertibleToInteger >
Definition at line 163 of file gtest-printers.h.
Member Function Documentation
template<typename T > static void testing::internal2::TypeWithoutFormatter< T, kConvertibleToInteger >::PrintValue (const T & value, ::std::ostream * os) inline static
Definition at line 172 of file gtest-printers.h.
References value.
{
     const internal::BiggestInt kBigInt = value;
     *os << kBigInt;
   }
template<typename T > static void testing::internal2::TypeWithoutFormatter< T, kConvertibleToInteger >::PrintValue (const T & value, ::std::ostream * os) inline static
Definition at line 172 of file gtest-printers.h.
References testing_internal::DefaultPrintNonContainerTo(), testing::internal2::kOtherType, testing::internal2::operator<<(), testing::internal2::TypeWithoutFormatter< T, kTypeKind >::PrintValue(), T, and value.
{
     const internal::BiggestInt kBigInt = value;
     *os << kBigInt;
   }
template<typename T > static void testing::internal2::TypeWithoutFormatter< T, kConvertibleToInteger >::PrintValue (const T & value, ::std::ostream * os) inline static
Definition at line 172 of file gtest-printers.h.
References testing_internal::DefaultPrintNonContainerTo(), testing::internal2::kOtherType, testing::internal2::operator<<(), testing::internal2::TypeWithoutFormatter< T, kTypeKind >::PrintValue(), T, and value.
{
     const internal::BiggestInt kBigInt = value;
     *os << kBigInt;
   }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/gtest-printers.h