proxygen: testing::internal::MatcherAsPredicate< M > Class Template Reference
testing::internal::MatcherAsPredicate< M > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
MatcherAsPredicate (M matcher)
template<typename T >
bool operator() (const T &x) const
MatcherAsPredicate (M matcher)
template<typename T >
bool operator() (const T &x) const
MatcherAsPredicate (M matcher)
template<typename T >
bool operator() (const T &x) const
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (MatcherAsPredicate)
GTEST_DISALLOW_ASSIGN_ (MatcherAsPredicate)
GTEST_DISALLOW_ASSIGN_ (MatcherAsPredicate)
Private Attributes
M matcher_
Detailed Description
template<typename M>
class testing::internal::MatcherAsPredicate< M >
Definition at line 1796 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename M > testing::internal::MatcherAsPredicate< M >::MatcherAsPredicate (M matcher) inline explicit
Definition at line 1798 of file gmock-matchers.h.
 : matcher_(matcher) {}
template<typename M > testing::internal::MatcherAsPredicate< M >::MatcherAsPredicate (M matcher) inline explicit
Definition at line 1798 of file gmock-matchers.h.
 : matcher_(matcher) {}
template<typename M > testing::internal::MatcherAsPredicate< M >::MatcherAsPredicate (M matcher) inline explicit
Definition at line 1798 of file gmock-matchers.h.
 : matcher_(matcher) {}
Member Function Documentation
template<typename M > testing::internal::MatcherAsPredicate< M >::GTEST_DISALLOW_ASSIGN_ (MatcherAsPredicate< M >) private
template<typename M > testing::internal::MatcherAsPredicate< M >::GTEST_DISALLOW_ASSIGN_ (MatcherAsPredicate< M >) private
template<typename M > testing::internal::MatcherAsPredicate< M >::GTEST_DISALLOW_ASSIGN_ (MatcherAsPredicate< M >) private
template<typename M > template<typename T > bool testing::internal::MatcherAsPredicate< M >::operator() (const T & x) const inline
Definition at line 1807 of file gmock-matchers.h.
References testing::Matches().
{
     // We let matcher_ commit to a particular type here instead of
     // when the MatcherAsPredicate object was constructed.  This
     // allows us to write Matches(m) where m is a polymorphic matcher
     // (e.g. Eq(5)).
     //
     // If we write Matcher<T>(matcher_).Matches(x) here, it won't
     // compile when matcher_ has type Matcher<const T&>; if we write
     // Matcher<const T&>(matcher_).Matches(x) here, it won't compile
     // when matcher_ has type Matcher<T>; if we just write
     // matcher_.Matches(x), it won't compile when matcher_ is
     // polymorphic, e.g. Eq(5).
     //
     // MatcherCast<const T&>() is necessary for making the code work
     // in all of the above situations.
     return MatcherCast<const T&>(matcher_).Matches(x);
   }
template<typename M > template<typename T > bool testing::internal::MatcherAsPredicate< M >::operator() (const T & x) const inline
Definition at line 1807 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, M, and testing::Matches().
{
     // We let matcher_ commit to a particular type here instead of
     // when the MatcherAsPredicate object was constructed.  This
     // allows us to write Matches(m) where m is a polymorphic matcher
     // (e.g. Eq(5)).
     //
     // If we write Matcher<T>(matcher_).Matches(x) here, it won't
     // compile when matcher_ has type Matcher<const T&>; if we write
     // Matcher<const T&>(matcher_).Matches(x) here, it won't compile
     // when matcher_ has type Matcher<T>; if we just write
     // matcher_.Matches(x), it won't compile when matcher_ is
     // polymorphic, e.g. Eq(5).
     //
     // MatcherCast<const T&>() is necessary for making the code work
     // in all of the above situations.
     return MatcherCast<const T&>(matcher_).Matches(x);
   }
template<typename M > template<typename T > bool testing::internal::MatcherAsPredicate< M >::operator() (const T & x) const inline
Definition at line 1807 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, M, and testing::Matches().
{
     // We let matcher_ commit to a particular type here instead of
     // when the MatcherAsPredicate object was constructed.  This
     // allows us to write Matches(m) where m is a polymorphic matcher
     // (e.g. Eq(5)).
     //
     // If we write Matcher<T>(matcher_).Matches(x) here, it won't
     // compile when matcher_ has type Matcher<const T&>; if we write
     // Matcher<const T&>(matcher_).Matches(x) here, it won't compile
     // when matcher_ has type Matcher<T>; if we just write
     // matcher_.Matches(x), it won't compile when matcher_ is
     // polymorphic, e.g. Eq(5).
     //
     // MatcherCast<const T&>() is necessary for making the code work
     // in all of the above situations.
     return MatcherCast<const T&>(matcher_).Matches(x);
   }
Member Data Documentation
template<typename M > M testing::internal::MatcherAsPredicate< M >::matcher_ private
Definition at line 1826 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h