proxygen: folly::RequestContext Class Reference
folly::RequestContext Class Reference
#include <Request.h>
Classes
struct State
Public Member Functions
void setContextData (const RequestToken &val, std::unique_ptr< RequestData > data)
void setContextData (const std::string &val, std::unique_ptr< RequestData > data)
bool setContextDataIfAbsent (const RequestToken &val, std::unique_ptr< RequestData > data)
bool setContextDataIfAbsent (const std::string &val, std::unique_ptr< RequestData > data)
void clearContextData (const RequestToken &val)
void clearContextData (const std::string &val)
bool hasContextData (const RequestToken &val) const
bool hasContextData (const std::string &val) const
RequestData * getContextData (const RequestToken &val)
const RequestData * getContextData (const RequestToken &val) const
RequestData * getContextData (const std::string &val)
const RequestData * getContextData (const std::string &val) const
void onSet ()
void onUnset ()
Static Public Member Functions
static void create ()
static RequestContext * get ()
static std::shared_ptr< RequestContext > setContext (std::shared_ptr< RequestContext > ctx)
static std::shared_ptr< RequestContext > saveContext ()
Private Types
enum DoSetBehaviour { DoSetBehaviour::SET, DoSetBehaviour::SET_IF_ABSENT, DoSetBehaviour::OVERWRITE }
Private Member Functions
void overwriteContextData (const RequestToken &val, std::unique_ptr< RequestData > data)
void overwriteContextData (const std::string &val, std::unique_ptr< RequestData > data)
bool doSetContextData (const RequestToken &val, std::unique_ptr< RequestData > &data, DoSetBehaviour behaviour)
bool doSetContextData (const std::string &val, std::unique_ptr< RequestData > &data, DoSetBehaviour behaviour)
Static Private Member Functions
static std::shared_ptr< RequestContext > & getStaticContext ()
static std::shared_ptr< RequestContext > setShallowCopyContext ()
Private Attributes
folly::Synchronized< State > state_
Friends
struct ShallowCopyRequestContextScopeGuard
Detailed Description
Definition at line 113 of file Request.h.
Member Enumeration Documentation
enum folly::RequestContext::DoSetBehaviour strong private
Enumerator
SET
SET_IF_ABSENT
OVERWRITE
Definition at line 223 of file Request.h.
{
     SET,
     SET_IF_ABSENT,
     OVERWRITE,
   };
Member Function Documentation
void folly::RequestContext::clearContextData (const RequestToken & val)
Definition at line 176 of file Request.cpp.
References folly::data(), folly::gen::move, folly::ulock(), and folly::wlock().
Referenced by TEST_F().
{
   RequestData::SharedPtr requestData;
   // Delete the RequestData after giving up the wlock just in case one of the
   // RequestData destructors will try to grab the lock again.
   {
     auto ulock = state_.ulock();
     auto it = ulock->requestData_.find(val);
     if (it == ulock->requestData_.end()) {
       return;
     }
     auto wlock = ulock.moveFromUpgradeToWrite();
     if (it->second && it->second->hasCallback()) {
       it->second->onUnset();
       wlock->callbackData_.erase(it->second.get());
     }
     requestData = std::move(it->second);
     wlock->requestData_.erase(it);
   }
 }
void folly::RequestContext::clearContextData (const std::string & val) inline
Definition at line 158 of file Request.h.
References folly::RequestToken::RequestToken().
{
     clearContextData(RequestToken(val));
   }
static void folly::RequestContext::create () inline static
Definition at line 118 of file Request.h.
References folly::data(), and val.
Referenced by folly::RequestContextScopeGuard::RequestContextScopeGuard(), and TEST_F().
{
     setContext(std::make_shared<RequestContext>());
   }
bool folly::RequestContext::doSetContextData (const RequestToken & val, std::unique_ptr< RequestData > & data, DoSetBehaviour behaviour) private
Definition at line 87 of file Request.cpp.
References folly::RequestData::constructPtr(), folly::RequestToken::getDebugString(), folly::ulock(), val, folly::WARNING, and folly::wlock().
{
   auto ulock = state_.ulock();
   bool conflict = false;
   auto it = ulock->requestData_.find(val);
   if (it != ulock->requestData_.end()) {
     if (behaviour == DoSetBehaviour::SET_IF_ABSENT) {
       return false;
     } else if (behaviour == DoSetBehaviour::SET) {
       LOG_FIRST_N(WARNING, 1)
           << "Calling RequestContext::setContextData for "
           << val.getDebugString() << " but it is already set";
     }
     conflict = true;
   }
   auto wlock = ulock.moveFromUpgradeToWrite();
   if (conflict) {
     if (it->second) {
       if (it->second->hasCallback()) {
         it->second->onUnset();
         wlock->callbackData_.erase(it->second.get());
       }
       it->second.reset(nullptr);
     }
     if (behaviour == DoSetBehaviour::SET) {
       return true;
     }
   }
   if (data && data->hasCallback()) {
     wlock->callbackData_.insert(data.get());
     data->onSet();
   }
   wlock->requestData_[val] = RequestData::constructPtr(data.release());
   return true;
 }
bool folly::RequestContext::doSetContextData (const std::string & val, std::unique_ptr< RequestData > & data, DoSetBehaviour behaviour) inline private
Definition at line 233 of file Request.h.
References folly::RequestToken::RequestToken().
{
     return doSetContextData(RequestToken(val), data, behaviour);
   }
RequestContext * folly::RequestContext::get () static
Definition at line 290 of file Request.cpp.
References context.
Referenced by folly::RequestEventBase::get(), RequestContextTest::getContext(), folly::RequestEventBase::set(), folly::ShallowCopyRequestContextScopeGuard::ShallowCopyRequestContextScopeGuard(), TEST(), and TEST_F().
{
   auto& context = getStaticContext();
   if (!context) {
     static RequestContext defaultContext;
     return std::addressof(defaultContext);
   }
   return context.get();
 }
RequestData * folly::RequestContext::getContextData (const RequestToken & val)
Definition at line 151 of file Request.cpp.
References folly::get_ref_default(), and val.
Referenced by folly::RequestEventBase::get(), TEST(), and TEST_F().
{
   const RequestData::SharedPtr dflt{nullptr};
   return get_ref_default(state_.rlock()->requestData_, val, dflt).get();
 }
const RequestData * folly::RequestContext::getContextData (const RequestToken & val) const
Definition at line 156 of file Request.cpp.
References folly::get_ref_default(), and val.
{
   const RequestData::SharedPtr dflt{nullptr};
   return get_ref_default(state_.rlock()->requestData_, val, dflt).get();
 }
RequestData* folly::RequestContext::getContextData (const std::string & val) inline
Definition at line 173 of file Request.h.
References folly::RequestToken::RequestToken().
{
     return getContextData(RequestToken(val));
   }
const RequestData* folly::RequestContext::getContextData (const std::string & val) const inline
Definition at line 176 of file Request.h.
References folly::RequestToken::RequestToken().
{
     return getContextData(RequestToken(val));
   }
std::shared_ptr< RequestContext > & folly::RequestContext::getStaticContext () static private
Definition at line 263 of file Request.cpp.
References folly::pushmi::operators::get.
{
   using SingletonT = SingletonThreadLocal<std::shared_ptr<RequestContext>>;
   return SingletonT::get();
 }
bool folly::RequestContext::hasContextData (const RequestToken & val) const
Definition at line 147 of file Request.cpp.
{
   return state_.rlock()->requestData_.count(val);
 }
bool folly::RequestContext::hasContextData (const std::string & val) const inline
Definition at line 165 of file Request.h.
References folly::RequestToken::RequestToken().
{
     return hasContextData(RequestToken(val));
   }
void folly::RequestContext::onSet ()
Definition at line 162 of file Request.cpp.
References folly::data(), and folly::rlock().
{
   auto rlock = state_.rlock();
   for (const auto& data : rlock->callbackData_) {
     data->onSet();
   }
 }
void folly::RequestContext::onUnset ()
Definition at line 169 of file Request.cpp.
References folly::data(), and folly::rlock().
{
   auto rlock = state_.rlock();
   for (const auto& data : rlock->callbackData_) {
     data->onUnset();
   }
 }
void folly::RequestContext::overwriteContextData (const RequestToken & val, std::unique_ptr< RequestData > data) private
Definition at line 141 of file Request.cpp.
Referenced by folly::ShallowCopyRequestContextScopeGuard::ShallowCopyRequestContextScopeGuard().
{
   doSetContextData(val, data, DoSetBehaviour::OVERWRITE);
 }
void folly::RequestContext::overwriteContextData (const std::string & val, std::unique_ptr< RequestData > data) inline private
Definition at line 216 of file Request.h.
References folly::gen::move, and folly::RequestToken::RequestToken().
{
     overwriteContextData(RequestToken(val), std::move(data));
   }
static std::shared_ptr<RequestContext> folly::RequestContext::saveContext () inline static
Definition at line 196 of file Request.h.
Referenced by folly::fibers::FiberManager::initLocalData(), folly::fibers::FiberManager::loopUntilNoReadyImpl(), folly::NotificationQueue< folly::AsyncServerSocket::QueueMessage >::putMessageImpl(), folly::NotificationQueue< folly::AsyncServerSocket::QueueMessage >::putMessagesImpl(), folly::EventBase::runInLoop(), folly::fibers::FiberManager::runReadyFiber(), folly::AsyncTimeout::scheduleTimeout(), proxygen::AsyncTimeoutSet::scheduleTimeout(), folly::HHWheelTimer::scheduleTimeout(), folly::futures::detail::FutureBase< T >::setCallback_(), folly::TEST(), TEST(), and TEST_F().
{
     return getStaticContext();
   }
std::shared_ptr< RequestContext > folly::RequestContext::setContext (std::shared_ptr< RequestContext > ctx) static
Definition at line 227 of file Request.cpp.
References folly::acquireLocked(), folly::as_const(), folly::data(), FOLLY_SDT, folly::RequestData::onSet(), and folly::RequestData::onUnset().
Referenced by folly::fibers::FiberManager::loopUntilNoReadyImpl(), folly::fibers::FiberManager::runReadyFiber(), RequestContextTest::SetUp(), TEST(), TEST_F(), proxygen::AsyncTimeoutSet::timeoutExpired(), folly::NotificationQueue< folly::AsyncServerSocket::QueueMessage >::tryConsume(), folly::RequestContextScopeGuard::~RequestContextScopeGuard(), and folly::ShallowCopyRequestContextScopeGuard::~ShallowCopyRequestContextScopeGuard().
{
   auto& staticCtx = getStaticContext();
   if (newCtx == staticCtx) {
     return newCtx;
   }
   FOLLY_SDT(
       folly, request_context_switch_before, staticCtx.get(), newCtx.get());
   auto curCtx = staticCtx;
   if (newCtx && curCtx) {
     // Only call set/unset for all request data that differs
     auto ret = folly::acquireLocked(
         as_const(newCtx->state_), as_const(curCtx->state_));
     auto& newLock = std::get<0>(ret);
     auto& curLock = std::get<1>(ret);
     auto& newData = newLock->callbackData_;
     auto& curData = curLock->callbackData_;
     exec_set_difference(
         curData, newData, [](RequestData* data) { data->onUnset(); });
     staticCtx = newCtx;
     exec_set_difference(
         newData, curData, [](RequestData* data) { data->onSet(); });
   } else {
     if (curCtx) {
       curCtx->onUnset();
     }
     staticCtx = newCtx;
     if (newCtx) {
       newCtx->onSet();
     }
   }
   return curCtx;
 }
void folly::RequestContext::setContextData (const RequestToken & val, std::unique_ptr< RequestData > data)
Definition at line 129 of file Request.cpp.
Referenced by folly::RequestEventBase::set(), TEST(), and TEST_F().
{
   doSetContextData(val, data, DoSetBehaviour::SET);
 }
void folly::RequestContext::setContextData (const std::string & val, std::unique_ptr< RequestData > data) inline
Definition at line 138 of file Request.h.
References folly::gen::move, and folly::RequestToken::RequestToken().
{
     setContextData(RequestToken(val), std::move(data));
   }
bool folly::RequestContext::setContextDataIfAbsent (const RequestToken & val, std::unique_ptr< RequestData > data)
Definition at line 135 of file Request.cpp.
{
   return doSetContextData(val, data, DoSetBehaviour::SET_IF_ABSENT);
 }
bool folly::RequestContext::setContextDataIfAbsent (const std::string & val, std::unique_ptr< RequestData > data) inline
Definition at line 150 of file Request.h.
References folly::gen::move, and folly::RequestToken::RequestToken().
{
     return setContextDataIfAbsent(RequestToken(val), std::move(data));
   }
std::shared_ptr< RequestContext > folly::RequestContext::setShallowCopyContext () static private
Definition at line 269 of file Request.cpp.
References folly::acquireLocked(), folly::as_const(), child, folly::RequestData::constructPtr(), parent, and folly::f14::swap().
{
   auto& parent = getStaticContext();
   auto child = std::make_shared<RequestContext>();
   if (parent) {
     auto ret = folly::acquireLocked(as_const(parent->state_), child->state_);
     auto& parentLock = std::get<0>(ret);
     auto& childLock = std::get<1>(ret);
     childLock->callbackData_ = parentLock->callbackData_;
     childLock->requestData_.reserve(parentLock->requestData_.size());
     for (const auto& entry : parentLock->requestData_) {
       childLock->requestData_.insert(std::make_pair(
           entry.first, RequestData::constructPtr(entry.second.get())));
     }
   }
   // Do not use setContext to avoid global set/unset
   std::swap(child, parent);
   return child;
 }
Friends And Related Function Documentation
friend struct ShallowCopyRequestContextScopeGuard friend
Definition at line 205 of file Request.h.
Member Data Documentation
folly::Synchronized<State> folly::RequestContext::state_ private
Definition at line 249 of file Request.h.
The documentation for this class was generated from the following files:
proxygen/folly/folly/io/async/Request.h
proxygen/folly/folly/io/async/Request.cpp