proxygen: folly::FormatValue< bool > Class Template Reference
folly::FormatValue< bool > Class Template Reference
#include <Format-inl.h>
Public Member Functions
FormatValue (bool val)
template<class FormatCallback >
void format (FormatArg &arg, FormatCallback &cb) const
Private Attributes
bool val_
Detailed Description
template<>
class folly::FormatValue< bool >
Definition at line 635 of file Format-inl.h.
Constructor & Destructor Documentation
folly::FormatValue< bool >::FormatValue (bool val) inline explicit
Definition at line 637 of file Format-inl.h.
 : val_(val) {}
Member Function Documentation
template<class FormatCallback > void folly::FormatValue< bool >::format (FormatArg & arg, FormatCallback & cb) const inline
Definition at line 640 of file Format-inl.h.
References folly::format(), folly::format_value::formatString(), folly::FormatArg::presentation, and folly::FormatArg::validate().
{
     if (arg.presentation == FormatArg::kDefaultPresentation) {
       arg.validate(FormatArg::Type::OTHER);
       format_value::formatString(val_ ? "true" : "false", arg, cb);
     } else { // number
       FormatValue<int>(val_).format(arg, cb);
     }
   }
Member Data Documentation
bool folly::FormatValue< bool >::val_ private
Definition at line 650 of file Format-inl.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/Format-inl.h