proxygen: Widget Class Reference
Widget Class Reference
#include <widget.h>
Public Member Functions
Widget (int number, const std::string &name)
~Widget ()
float GetFloatValue () const
int GetIntValue () const
std::string GetStringValue () const
void GetCharPtrValue (char *buffer, size_t max_size) const
~Widget ()
Widget (int number, const std::string &name)
~Widget ()
float GetFloatValue () const
int GetIntValue () const
std::string GetStringValue () const
void GetCharPtrValue (char *buffer, size_t max_size) const
Widget (int number, const std::string &name)
~Widget ()
float GetFloatValue () const
int GetIntValue () const
std::string GetStringValue () const
void GetCharPtrValue (char *buffer, size_t max_size) const
Static Public Member Functions
static void customDeleter (Widget *w, TLPDestructionMode mode)
Public Attributes
int val_
Static Public Attributes
static int totalVal_ = 0
Private Attributes
float number_
std::string name_
Detailed Description
Definition at line 42 of file widget.h.
Constructor & Destructor Documentation
Widget::Widget (int number, const std::string & name)
Definition at line 40 of file widget.cc.
     : number_(number),
       name_(name) {}
Widget::~Widget ()
Definition at line 44 of file widget.cc.
 {}
Widget::~Widget () inline
Definition at line 53 of file ThreadLocalTest.cpp.
             {
     totalVal_ += val_;
   }
Widget::Widget (int number, const std::string & name)
Widget::~Widget ()
Widget::Widget (int number, const std::string & name)
Widget::~Widget ()
Member Function Documentation
static void Widget::customDeleter (Widget * w, TLPDestructionMode mode) inline static
Definition at line 57 of file ThreadLocalTest.cpp.
References folly::ALL_THREADS, and totalVal_.
Referenced by TEST().
{
     totalVal_ += (mode == TLPDestructionMode::ALL_THREADS) ? 1000 : 1;
     delete w;
   }
void Widget::GetCharPtrValue (char * buffer, size_t max_size) const
Definition at line 58 of file widget.cc.
References name_.
Referenced by TEST().
{
   // Copy the char* representation of name_ into buffer, up to max_size.
   strncpy(buffer, name_.c_str(), max_size-1);
   buffer[max_size-1] = '\0';
   return;
 }
void Widget::GetCharPtrValue (char * buffer, size_t max_size) const
void Widget::GetCharPtrValue (char * buffer, size_t max_size) const
float Widget::GetFloatValue () const
Definition at line 46 of file widget.cc.
References number_.
Referenced by TEST().
{
   return number_;
 }
float Widget::GetFloatValue () const
float Widget::GetFloatValue () const
int Widget::GetIntValue () const
int Widget::GetIntValue () const
Definition at line 50 of file widget.cc.
References number_.
Referenced by TEST().
{
   return static_cast<int>(number_);
 }
int Widget::GetIntValue () const
std::string Widget::GetStringValue () const
Definition at line 54 of file widget.cc.
References name_.
Referenced by TEST().
{
   return name_;
 }
std::string Widget::GetStringValue () const
std::string Widget::GetStringValue () const
Member Data Documentation
std::string Widget::name_ private
Definition at line 58 of file widget.h.
Referenced by GetCharPtrValue(), and GetStringValue().
float Widget::number_ private
Definition at line 57 of file widget.h.
Referenced by GetFloatValue(), and GetIntValue().
int Widget::totalVal_ = 0 static
Definition at line 51 of file ThreadLocalTest.cpp.
Referenced by customDeleter(), and TEST().
int Widget::val_
Definition at line 52 of file ThreadLocalTest.cpp.
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googletest/xcode/Samples/FrameworkSample/widget.h
proxygen/folly/folly/test/ThreadLocalTest.cpp
proxygen/fizz/build_/gtest/src/gtest/googletest/xcode/Samples/FrameworkSample/widget.cc