proxygen: folly::exception_tracer::StackTraceStack::Node Class Reference
folly::exception_tracer::StackTraceStack::Node Class Reference
Public Member Functions
void deallocate ()
Public Member Functions inherited from folly::exception_tracer::StackTrace
StackTrace ()
Static Public Member Functions
static Node * allocate ()
Public Attributes
Node * next
Public Attributes inherited from folly::exception_tracer::StackTrace
size_t frameCount
uintptr_t addresses [kMaxFrames]
Private Member Functions
Node ()
~Node ()
Detailed Description
Definition at line 28 of file StackTrace.cpp.
Constructor & Destructor Documentation
folly::exception_tracer::StackTraceStack::Node::Node () inline private
Definition at line 36 of file StackTrace.cpp.
Referenced by allocate().
 : next(nullptr) {}
folly::exception_tracer::StackTraceStack::Node::~Node () inline private
Definition at line 37 of file StackTrace.cpp.
 {}
Member Function Documentation
auto folly::exception_tracer::StackTraceStack::Node::allocate () static
Definition at line 40 of file StackTrace.cpp.
References Node().
Referenced by folly::exception_tracer::StackTraceStack::pushCurrent().
{
   // Null pointer on error, please.
   return new (std::nothrow) Node();
 }
void folly::exception_tracer::StackTraceStack::Node::deallocate ()
Definition at line 45 of file StackTrace.cpp.
Referenced by folly::exception_tracer::StackTraceStack::pop().
{
   delete this;
 }
Member Data Documentation
Node* folly::exception_tracer::StackTraceStack::Node::next
Definition at line 33 of file StackTrace.cpp.
Referenced by folly::exception_tracer::StackTraceStack::moveTopFrom(), folly::exception_tracer::StackTraceStack::next(), and folly::exception_tracer::StackTraceStack::pop().
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/exception_tracer/StackTrace.cpp