proxygen: testing::Matcher< T > Class Template Reference
testing::Matcher< T > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
Matcher ()
Matcher (const MatcherInterface< T > *impl)
Matcher (T value)
Matcher ()
Matcher (const MatcherInterface< T > *impl)
Matcher (T value)
Matcher ()
Matcher (const MatcherInterface< T > *impl)
Matcher (T value)
Public Member Functions inherited from testing::internal::MatcherBase< T >
bool MatchAndExplain (T x, MatchResultListener *listener) const
bool Matches (T x) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
void ExplainMatchResultTo (T x,::std::ostream *os) const
const MatcherDescriberInterface * GetDescriber () const
bool MatchAndExplain (T x, MatchResultListener *listener) const
bool Matches (T x) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
void ExplainMatchResultTo (T x,::std::ostream *os) const
const MatcherDescriberInterface * GetDescriber () const
bool MatchAndExplain (T x, MatchResultListener *listener) const
bool Matches (T x) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
void ExplainMatchResultTo (T x,::std::ostream *os) const
const MatcherDescriberInterface * GetDescriber () const
Additional Inherited Members
Protected Member Functions inherited from testing::internal::MatcherBase< T >
MatcherBase ()
MatcherBase (const MatcherInterface< T > *impl)
virtual ~MatcherBase ()
MatcherBase ()
MatcherBase (const MatcherInterface< T > *impl)
virtual ~MatcherBase ()
MatcherBase ()
MatcherBase (const MatcherInterface< T > *impl)
virtual ~MatcherBase ()
Detailed Description
template<typename T>
class testing::Matcher< T >
Definition at line 319 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename T> testing::Matcher< T >::Matcher () inline explicit
Definition at line 324 of file gmock-matchers.h.
Referenced by testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::Impl< T >::MatchAndExplain(), and testing::Matcher< internal::string >::Matcher().
 {}  // NOLINT
template<typename T> testing::Matcher< T >::Matcher (const MatcherInterface< T > * impl) inline explicit
Definition at line 327 of file gmock-matchers.h.
       : internal::MatcherBase<T>(impl) {}
template<typename T> testing::Matcher< T >::Matcher (T value)
Definition at line 3747 of file gmock-matchers.h.
References testing::Eq().
 { *this = Eq(value); }
template<typename T> testing::Matcher< T >::Matcher () inline explicit
Definition at line 324 of file gmock-matchers.h.
 {}  // NOLINT
template<typename T> testing::Matcher< T >::Matcher (const MatcherInterface< T > * impl) inline explicit
Definition at line 327 of file gmock-matchers.h.
       : internal::MatcherBase<T>(impl) {}
template<typename T> testing::Matcher< T >::Matcher (T value)
template<typename T> testing::Matcher< T >::Matcher () inline explicit
Definition at line 324 of file gmock-matchers.h.
 {}  // NOLINT
template<typename T> testing::Matcher< T >::Matcher (const MatcherInterface< T > * impl) inline explicit
Definition at line 327 of file gmock-matchers.h.
       : internal::MatcherBase<T>(impl) {}
template<typename T> testing::Matcher< T >::Matcher (T value)
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h