proxygen: wangle::InboundLink< In > Class Template Reference
wangle::InboundLink< In > Class Template Reference abstract
#include <HandlerContext-inl.h>
Public Member Functions
virtual ~InboundLink ()=default
virtual void read (In msg)=0
virtual void readEOF ()=0
virtual void readException (folly::exception_wrapper e)=0
virtual void transportActive ()=0
virtual void transportInactive ()=0
Detailed Description
template<class In>
class wangle::InboundLink< In >
Definition at line 54 of file HandlerContext-inl.h.
Constructor & Destructor Documentation
template<class In> virtual wangle::InboundLink< In >::~InboundLink () virtual default
Member Function Documentation
template<class In> virtual void wangle::InboundLink< In >::read (In msg) pure virtual
Implemented in wangle::InboundContextImpl< H >, and wangle::ContextImpl< H >.
Referenced by wangle::Pipeline< R, W >::read().
template<class In> virtual void wangle::InboundLink< In >::readEOF () pure virtual
Implemented in wangle::InboundContextImpl< H >, and wangle::ContextImpl< H >.
Referenced by wangle::Pipeline< R, W >::readEOF().
template<class In> virtual void wangle::InboundLink< In >::readException (folly::exception_wrapper e) pure virtual
Implemented in wangle::InboundContextImpl< H >, and wangle::ContextImpl< H >.
Referenced by wangle::Pipeline< R, W >::readException().
template<class In> virtual void wangle::InboundLink< In >::transportActive () pure virtual
Implemented in wangle::InboundContextImpl< H >, and wangle::ContextImpl< H >.
Referenced by wangle::Pipeline< R, W >::transportActive().
template<class In> virtual void wangle::InboundLink< In >::transportInactive () pure virtual
Implemented in wangle::InboundContextImpl< H >, and wangle::ContextImpl< H >.
Referenced by wangle::Pipeline< R, W >::transportInactive().
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/channel/HandlerContext-inl.h