proxygen: folly::ssl::detail::SSLSessionImpl Class Reference
folly::ssl::detail::SSLSessionImpl Class Reference
#include <SSLSessionImpl.h>
Public Member Functions
SSLSessionImpl (SSL_SESSION *session, bool takeOwnership=true)
SSLSessionImpl (const std::string &serializedSession)
virtual ~SSLSessionImpl ()
std::string serialize () const
std::string getSessionID () const
const SSL_SESSION * getRawSSLSession () const
SSL_SESSION * getRawSSLSessionDangerous ()
Private Member Functions
void upRef ()
void downRef ()
Private Attributes
SSL_SESSION * session_ {nullptr}
Detailed Description
Definition at line 29 of file SSLSessionImpl.h.
Constructor & Destructor Documentation
folly::ssl::detail::SSLSessionImpl::SSLSessionImpl (SSL_SESSION * session, bool takeOwnership = true) explicit
Definition at line 29 of file SSLSessionImpl.cpp.
References session_, and upRef().
     : session_(session) {
   if (session_ == nullptr) {
     throw std::runtime_error("SSL_SESSION is null");
   }
   // If we're not given ownership, we need to up the refcount so the SSL_SESSION
   // object won't be freed while SSLSessionImpl is alive
   if (!takeOwnership) {
     upRef();
   }
 }
folly::ssl::detail::SSLSessionImpl::SSLSessionImpl (const std::string & serializedSession) explicit
Definition at line 41 of file SSLSessionImpl.cpp.
References session_.
{
   auto sessionData =
       reinterpret_cast<const unsigned char*>(serializedSession.data());
   auto longLen = long(serializedSession.length());
   if ((session_ = d2i_SSL_SESSION(nullptr, &sessionData, longLen)) == nullptr) {
     throw std::runtime_error("Cannot deserialize SSLSession string");
   }
 }
folly::ssl::detail::SSLSessionImpl::~SSLSessionImpl () virtual
Definition at line 50 of file SSLSessionImpl.cpp.
References downRef().
{
   downRef();
 }
Member Function Documentation
void folly::ssl::detail::SSLSessionImpl::downRef () private
Definition at line 99 of file SSLSessionImpl.cpp.
References session_.
Referenced by ~SSLSessionImpl().
{
   if (session_) {
     SSL_SESSION_free(session_);
   }
 }
const SSL_SESSION * folly::ssl::detail::SSLSessionImpl::getRawSSLSession () const
Definition at line 84 of file SSLSessionImpl.cpp.
References session_.
{
   return const_cast<SSL_SESSION*>(session_);
 }
SSL_SESSION * folly::ssl::detail::SSLSessionImpl::getRawSSLSessionDangerous ()
Definition at line 88 of file SSLSessionImpl.cpp.
References session_, and upRef().
{
   upRef();
   return session_;
 }
std::string folly::ssl::detail::SSLSessionImpl::getSessionID () const
Definition at line 73 of file SSLSessionImpl.cpp.
References ptr, session_, and string.
{
   std::string ret;
   if (session_) {
     const unsigned char* ptr = nullptr;
     unsigned int len = 0;
     ptr = SSL_SESSION_get_id(session_, &len);
     ret.assign(ptr, ptr + len);
   }
   return ret;
 }
std::string folly::ssl::detail::SSLSessionImpl::serialize () const
Definition at line 54 of file SSLSessionImpl.cpp.
References session_, and string.
{
   std::string ret;
   // Get the length first, then we know how much space to allocate.
   auto len = i2d_SSL_SESSION(session_, nullptr);
   if (len > 0) {
     std::unique_ptr<unsigned char[]> uptr(new unsigned char[size_t(len)]);
     auto p = uptr.get();
     auto written = i2d_SSL_SESSION(session_, &p);
     if (written <= 0) {
       VLOG(2) << "Could not serialize SSL_SESSION!";
     } else {
       ret.assign(uptr.get(), uptr.get() + written);
     }
   }
   return ret;
 }
void folly::ssl::detail::SSLSessionImpl::upRef () private
Definition at line 93 of file SSLSessionImpl.cpp.
References session_.
Referenced by getRawSSLSessionDangerous(), and SSLSessionImpl().
{
   if (session_) {
     SSL_SESSION_up_ref(session_);
   }
 }
Member Data Documentation
SSL_SESSION* folly::ssl::detail::SSLSessionImpl::session_ {nullptr} private
Definition at line 43 of file SSLSessionImpl.h.
Referenced by downRef(), getRawSSLSession(), getRawSSLSessionDangerous(), getSessionID(), serialize(), SSLSessionImpl(), and upRef().
The documentation for this class was generated from the following files:
proxygen/folly/folly/ssl/detail/SSLSessionImpl.h
proxygen/folly/folly/ssl/detail/SSLSessionImpl.cpp