proxygen: folly::MemoryIdlerTimeout Class Reference
folly::MemoryIdlerTimeout Class Reference
Public Member Functions
MemoryIdlerTimeout (EventBase *b)
void timeoutExpired () noexceptoverride
void runLoopCallback () noexceptoverride
Public Member Functions inherited from folly::AsyncTimeout
AsyncTimeout (TimeoutManager *timeoutManager)
AsyncTimeout (EventBase *eventBase)
AsyncTimeout (TimeoutManager *timeoutManager, InternalEnum internal)
AsyncTimeout (EventBase *eventBase, InternalEnum internal)
AsyncTimeout ()
virtual ~AsyncTimeout ()
bool scheduleTimeout (uint32_t milliseconds)
bool scheduleTimeout (TimeoutManager::timeout_type timeout)
void cancelTimeout ()
bool isScheduled () const
void attachTimeoutManager (TimeoutManager *timeoutManager, InternalEnum internal=InternalEnum::NORMAL)
void attachEventBase (EventBase *eventBase, InternalEnum internal=InternalEnum::NORMAL)
void detachTimeoutManager ()
void detachEventBase ()
const TimeoutManager * getTimeoutManager ()
struct event * getEvent ()
Public Member Functions inherited from folly::EventBase::LoopCallback
virtual ~LoopCallback ()=default
void cancelLoopCallback ()
bool isLoopCallbackScheduled () const
Private Attributes
EventBase * base_
bool idled {false}
Additional Inherited Members
Public Types inherited from folly::AsyncTimeout
typedef TimeoutManager::InternalEnum InternalEnum
Static Public Member Functions inherited from folly::AsyncTimeout
template<typename TCallback >
static std::unique_ptr< AsyncTimeout > make (TimeoutManager &manager, TCallback &&callback)
template<typename TCallback >
static std::unique_ptr< AsyncTimeout > schedule (TimeoutManager::timeout_type timeout, TimeoutManager &manager, TCallback &&callback)
Detailed Description
Definition at line 36 of file IOThreadPoolExecutor.cpp.
Constructor & Destructor Documentation
folly::MemoryIdlerTimeout::MemoryIdlerTimeout (EventBase * b) inline explicit
Definition at line 38 of file IOThreadPoolExecutor.cpp.
 : AsyncTimeout(b), base_(b) {}
Member Function Documentation
void folly::MemoryIdlerTimeout::runLoopCallback () inline override virtual noexcept
Implements folly::EventBase::LoopCallback.
Definition at line 44 of file IOThreadPoolExecutor.cpp.
References base_, count, folly::detail::MemoryIdler::defaultIdleTimeout, folly::detail::MemoryIdler::flushLocalMallocCaches(), folly::detail::MemoryIdler::getVariationTimeout(), idled, folly::detail::MemoryIdler::kDefaultStackToRetain, folly::AtomicStruct< T, Atom >::load(), folly::EventBase::runBeforeLoop(), folly::AsyncTimeout::scheduleTimeout(), and folly::detail::MemoryIdler::unmapUnusedStack().
{
     if (idled) {
       MemoryIdler::flushLocalMallocCaches();
       MemoryIdler::unmapUnusedStack(MemoryIdler::kDefaultStackToRetain);
       idled = false;
     } else {
       std::chrono::steady_clock::duration idleTimeout =
           MemoryIdler::defaultIdleTimeout.load(std::memory_order_acquire);
       idleTimeout = MemoryIdler::getVariationTimeout(idleTimeout);
       scheduleTimeout(static_cast<uint32_t>(
           std::chrono::duration_cast<std::chrono::milliseconds>(idleTimeout)
               .count()));
     }
     // reschedule this callback for the next event loop.
     base_->runBeforeLoop(this);
   }
void folly::MemoryIdlerTimeout::timeoutExpired () inline override virtual noexcept
timeoutExpired() is invoked when the timeout period has expired.
Implements folly::AsyncTimeout.
Definition at line 40 of file IOThreadPoolExecutor.cpp.
References idled.
{
     idled = true;
   }
Member Data Documentation
EventBase* folly::MemoryIdlerTimeout::base_ private
Definition at line 66 of file IOThreadPoolExecutor.cpp.
Referenced by runLoopCallback().
bool folly::MemoryIdlerTimeout::idled {false} private
Definition at line 67 of file IOThreadPoolExecutor.cpp.
Referenced by runLoopCallback(), and timeoutExpired().
The documentation for this class was generated from the following file:
proxygen/folly/folly/executors/IOThreadPoolExecutor.cpp