proxygen: testing::gmock_nice_strict_test::MockBar Class Reference
testing::gmock_nice_strict_test::MockBar Class Reference
Public Member Functions
MockBar (const string &s)
MockBar (char a1, char a2, string a3, string a4, int a5, int a6, const string &a7, const string &a8, bool a9, bool a10)
virtual ~MockBar ()
const string & str () const
MOCK_METHOD0 (This, int())
MOCK_METHOD2 (That, string(int, bool))
MockBar (const string &s)
MockBar (char a1, char a2, string a3, string a4, int a5, int a6, const string &a7, const string &a8, bool a9, bool a10)
virtual ~MockBar ()
const string & str () const
MOCK_METHOD0 (This, int())
MOCK_METHOD2 (That, string(int, bool))
MockBar (const string &s)
MockBar (char a1, char a2, string a3, string a4, int a5, int a6, const string &a7, const string &a8, bool a9, bool a10)
virtual ~MockBar ()
const string & str () const
MOCK_METHOD0 (This, int())
MOCK_METHOD2 (That, string(int, bool))
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockBar)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockBar)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockBar)
Private Attributes
string str_
Detailed Description
Definition at line 88 of file gmock-nice-strict_test.cc.
Constructor & Destructor Documentation
testing::gmock_nice_strict_test::MockBar::MockBar (const string & s) inline explicit
Definition at line 90 of file gmock-nice-strict_test.cc.
 : str_(s) {}
testing::gmock_nice_strict_test::MockBar::MockBar (char a1, char a2, string a3, string a4, int a5, int a6, const string & a7, const string & a8, bool a9, bool a10) inline
Definition at line 92 of file gmock-nice-strict_test.cc.
References string.
{
     str_ = string() + a1 + a2 + a3 + a4 + static_cast<char>(a5) +
         static_cast<char>(a6) + a7 + a8 + (a9 ? 'T' : 'F') + (a10 ? 'T' : 'F');
   }
virtual testing::gmock_nice_strict_test::MockBar::~MockBar () inline virtual
Definition at line 98 of file gmock-nice-strict_test.cc.
 {}
testing::gmock_nice_strict_test::MockBar::MockBar (const string & s) inline explicit
Definition at line 90 of file gmock-nice-strict_test.cc.
 : str_(s) {}
testing::gmock_nice_strict_test::MockBar::MockBar (char a1, char a2, string a3, string a4, int a5, int a6, const string & a7, const string & a8, bool a9, bool a10) inline
Definition at line 92 of file gmock-nice-strict_test.cc.
References string.
{
     str_ = string() + a1 + a2 + a3 + a4 + static_cast<char>(a5) +
         static_cast<char>(a6) + a7 + a8 + (a9 ? 'T' : 'F') + (a10 ? 'T' : 'F');
   }
virtual testing::gmock_nice_strict_test::MockBar::~MockBar () inline virtual
Definition at line 98 of file gmock-nice-strict_test.cc.
 {}
testing::gmock_nice_strict_test::MockBar::MockBar (const string & s) inline explicit
Definition at line 90 of file gmock-nice-strict_test.cc.
 : str_(s) {}
testing::gmock_nice_strict_test::MockBar::MockBar (char a1, char a2, string a3, string a4, int a5, int a6, const string & a7, const string & a8, bool a9, bool a10) inline
Definition at line 92 of file gmock-nice-strict_test.cc.
References string.
{
     str_ = string() + a1 + a2 + a3 + a4 + static_cast<char>(a5) +
         static_cast<char>(a6) + a7 + a8 + (a9 ? 'T' : 'F') + (a10 ? 'T' : 'F');
   }
virtual testing::gmock_nice_strict_test::MockBar::~MockBar () inline virtual
Definition at line 98 of file gmock-nice-strict_test.cc.
 {}
Member Function Documentation
testing::gmock_nice_strict_test::MockBar::GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockBar) private
testing::gmock_nice_strict_test::MockBar::GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockBar) private
testing::gmock_nice_strict_test::MockBar::GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockBar) private
testing::gmock_nice_strict_test::MockBar::MOCK_METHOD0 (This , int())
testing::gmock_nice_strict_test::MockBar::MOCK_METHOD0 (This , int())
testing::gmock_nice_strict_test::MockBar::MOCK_METHOD0 (This , int())
testing::gmock_nice_strict_test::MockBar::MOCK_METHOD2 (That , string(int, bool))
testing::gmock_nice_strict_test::MockBar::MOCK_METHOD2 (That , string(int, bool))
testing::gmock_nice_strict_test::MockBar::MOCK_METHOD2 (That , string(int, bool))
const string& testing::gmock_nice_strict_test::MockBar::str () const inline
Definition at line 100 of file gmock-nice-strict_test.cc.
References testing::internal::CaptureStdout(), testing::internal::Delete(), testing::gmock_nice_strict_test::Foo::DoThat(), testing::gmock_nice_strict_test::Foo::DoThis(), EXPECT_CALL, EXPECT_EQ, EXPECT_NONFATAL_FAILURE, EXPECT_THAT, testing::internal::GetCapturedStdout(), GMOCK_FLAG, Mock::GTEST_DISALLOW_COPY_AND_ASSIGN_(), testing::HasSubstr(), testing::Invoke(), Mock::MOCK_METHOD0(), MOCK_METHOD2, ON_CALL, and testing::gmock_nice_strict_test::TEST().
 { return str_; }
const string& testing::gmock_nice_strict_test::MockBar::str () const inline
Definition at line 100 of file gmock-nice-strict_test.cc.
References testing::internal::CaptureStdout(), testing::internal::Delete(), testing::gmock_nice_strict_test::Foo::DoThat(), testing::gmock_nice_strict_test::Foo::DoThis(), EXPECT_CALL, EXPECT_EQ, EXPECT_NONFATAL_FAILURE, EXPECT_THAT, testing::internal::GetCapturedStdout(), GMOCK_FLAG, Mock::GTEST_DISALLOW_COPY_AND_ASSIGN_(), testing::HasSubstr(), testing::Invoke(), Mock::MOCK_METHOD0(), MOCK_METHOD2, ON_CALL, and testing::gmock_nice_strict_test::TEST().
 { return str_; }
const string& testing::gmock_nice_strict_test::MockBar::str () const inline
Definition at line 100 of file gmock-nice-strict_test.cc.
References Mock::MOCK_METHOD0(), and MOCK_METHOD2.
 { return str_; }
Member Data Documentation
string testing::gmock_nice_strict_test::MockBar::str_ private
Definition at line 106 of file gmock-nice-strict_test.cc.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-nice-strict_test.cc