proxygen: wangle::StringCodec Class Reference
wangle::StringCodec Class Reference
#include <StringCodec.h>
Public Types
typedef Handler< std::unique_ptr< folly::IOBuf >, std::string, std::string, std::unique_ptr< folly::IOBuf > >::Context Context
Public Types inherited from wangle::Handler< std::unique_ptr< folly::IOBuf >, std::string, std::string, std::unique_ptr< folly::IOBuf > >
typedef std::unique_ptr< folly::IOBuf > rin
typedef std::string rout
typedef std::string win
typedef std::unique_ptr< folly::IOBuf > wout
typedef HandlerContext< std::string, std::unique_ptr< folly::IOBuf > > Context
Public Member Functions
void read (Context *ctx, std::unique_ptr< folly::IOBuf > buf) override
folly::Future< folly::Unit > write (Context *ctx, std::string msg) override
Public Member Functions inherited from wangle::Handler< std::unique_ptr< folly::IOBuf >, std::string, std::string, std::unique_ptr< folly::IOBuf > >
~Handler () override=default
virtual void read (Context *ctx, std::unique_ptr< folly::IOBuf >msg)=0
virtual void readEOF (Context *ctx)
virtual void readException (Context *ctx, folly::exception_wrapper e)
virtual void transportActive (Context *ctx)
virtual void transportInactive (Context *ctx)
virtual folly::Future< folly::Unit > write (Context *ctx, std::stringmsg)=0
virtual folly::Future< folly::Unit > writeException (Context *ctx, folly::exception_wrapper e)
virtual folly::Future< folly::Unit > close (Context *ctx)
Public Member Functions inherited from wangle::HandlerBase< HandlerContext< std::string, std::unique_ptr< folly::IOBuf > > >
virtual ~HandlerBase ()=default
virtual void attachPipeline (HandlerContext< std::string, std::unique_ptr< folly::IOBuf > > *)
virtual void detachPipeline (HandlerContext< std::string, std::unique_ptr< folly::IOBuf > > *)
HandlerContext< std::string, std::unique_ptr< folly::IOBuf > > * getContext ()
Additional Inherited Members
Static Public Attributes inherited from wangle::Handler< std::unique_ptr< folly::IOBuf >, std::string, std::string, std::unique_ptr< folly::IOBuf > >
static const HandlerDir dir
Detailed Description
Definition at line 26 of file StringCodec.h.
Member Typedef Documentation
typedef Handler< std::unique_ptr<folly::IOBuf>, std::string, std::string, std::unique_ptr<folly::IOBuf> >::Context wangle::StringCodec::Context
Definition at line 31 of file StringCodec.h.
Member Function Documentation
void wangle::StringCodec::read (Context * ctx, std::unique_ptr< folly::IOBuf > buf) inline override
Definition at line 33 of file StringCodec.h.
References folly::IOBuf::coalesce(), data, folly::IOBuf::data(), and folly::IOBuf::length().
{
     if (buf) {
       buf->coalesce();
       std::string data((const char*)buf->data(), buf->length());
       ctx->fireRead(data);
     }
   }
folly::Future<folly::Unit> wangle::StringCodec::write (Context * ctx, std::string msg) inline override
Definition at line 41 of file StringCodec.h.
References folly::IOBuf::copyBuffer(), and folly::gen::move.
{
     auto buf = folly::IOBuf::copyBuffer(msg.data(), msg.length());
     return ctx->fireWrite(std::move(buf));
   }
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/codec/StringCodec.h