proxygen: testing::internal::OnCallSpec< F > Class Template Reference
testing::internal::OnCallSpec< F > Class Template Reference
#include <gmock-spec-builders.h>
Public Types
typedef Function< F >::ArgumentTuple ArgumentTuple
typedef Function< F >::ArgumentMatcherTuple ArgumentMatcherTuple
typedef Function< F >::ArgumentTuple ArgumentTuple
typedef Function< F >::ArgumentMatcherTuple ArgumentMatcherTuple
typedef Function< F >::ArgumentTuple ArgumentTuple
typedef Function< F >::ArgumentMatcherTuple ArgumentMatcherTuple
Public Member Functions
OnCallSpec (const char *a_file, int a_line, const ArgumentMatcherTuple &matchers)
OnCallSpec & With (const Matcher< const ArgumentTuple & > &m)
OnCallSpec & WillByDefault (const Action< F > &action)
bool Matches (const ArgumentTuple &args) const
const Action< F > & GetAction () const
OnCallSpec (const char *a_file, int a_line, const ArgumentMatcherTuple &matchers)
OnCallSpec & With (const Matcher< const ArgumentTuple & > &m)
OnCallSpec & WillByDefault (const Action< F > &action)
bool Matches (const ArgumentTuple &args) const
const Action< F > & GetAction () const
OnCallSpec (const char *a_file, int a_line, const ArgumentMatcherTuple &matchers)
OnCallSpec & With (const Matcher< const ArgumentTuple & > &m)
OnCallSpec & WillByDefault (const Action< F > &action)
bool Matches (const ArgumentTuple &args) const
const Action< F > & GetAction () const
Public Member Functions inherited from testing::internal::UntypedOnCallSpecBase
UntypedOnCallSpecBase (const char *a_file, int a_line)
const char * file () const
int line () const
UntypedOnCallSpecBase (const char *a_file, int a_line)
const char * file () const
int line () const
UntypedOnCallSpecBase (const char *a_file, int a_line)
const char * file () const
int line () const
Private Attributes
ArgumentMatcherTuple matchers_
Matcher< const ArgumentTuple & > extra_matcher_
Action< F > action_
Additional Inherited Members
Protected Types inherited from testing::internal::UntypedOnCallSpecBase
enum Clause {
kNone, kWith, kWillByDefault, kNone,
kWith, kWillByDefault, kNone, kWith,
kWillByDefault
}
enum Clause {
kNone, kWith, kWillByDefault, kNone,
kWith, kWillByDefault, kNone, kWith,
kWillByDefault
}
enum Clause {
kNone, kWith, kWillByDefault, kNone,
kWith, kWillByDefault, kNone, kWith,
kWillByDefault
}
Protected Member Functions inherited from testing::internal::UntypedOnCallSpecBase
void AssertSpecProperty (bool property, const string &failure_message) const
void ExpectSpecProperty (bool property, const string &failure_message) const
void AssertSpecProperty (bool property, const string &failure_message) const
void ExpectSpecProperty (bool property, const string &failure_message) const
void AssertSpecProperty (bool property, const string &failure_message) const
void ExpectSpecProperty (bool property, const string &failure_message) const
Protected Attributes inherited from testing::internal::UntypedOnCallSpecBase
const char * file_
int line_
Clause last_clause_
Detailed Description
template<typename F>
class testing::internal::OnCallSpec< F >
Definition at line 285 of file gmock-spec-builders.h.
Member Typedef Documentation
template<typename F> typedef Function<F>::ArgumentMatcherTuple testing::internal::OnCallSpec< F >::ArgumentMatcherTuple
Definition at line 288 of file gmock-spec-builders.h.
template<typename F> typedef Function<F>::ArgumentMatcherTuple testing::internal::OnCallSpec< F >::ArgumentMatcherTuple
Definition at line 288 of file gmock-spec-builders.h.
template<typename F> typedef Function<F>::ArgumentMatcherTuple testing::internal::OnCallSpec< F >::ArgumentMatcherTuple
Definition at line 288 of file gmock-spec-builders.h.
template<typename F> typedef Function<F>::ArgumentTuple testing::internal::OnCallSpec< F >::ArgumentTuple
Definition at line 287 of file gmock-spec-builders.h.
template<typename F> typedef Function<F>::ArgumentTuple testing::internal::OnCallSpec< F >::ArgumentTuple
Definition at line 287 of file gmock-spec-builders.h.
template<typename F> typedef Function<F>::ArgumentTuple testing::internal::OnCallSpec< F >::ArgumentTuple
Definition at line 287 of file gmock-spec-builders.h.
Constructor & Destructor Documentation
template<typename F> testing::internal::OnCallSpec< F >::OnCallSpec (const char * a_file, int a_line, const ArgumentMatcherTuple & matchers) inline
Definition at line 292 of file gmock-spec-builders.h.
       : UntypedOnCallSpecBase(a_file, a_line),
         matchers_(matchers),
         // By default, extra_matcher_ should match anything.  However,
         // we cannot initialize it with _ as that triggers a compiler
         // bug in Symbian's C++ compiler (cannot decide between two
         // overloaded constructors of Matcher<const ArgumentTuple&>).
         extra_matcher_(A<const ArgumentTuple&>()) {
   }
template<typename F> testing::internal::OnCallSpec< F >::OnCallSpec (const char * a_file, int a_line, const ArgumentMatcherTuple & matchers) inline
Definition at line 292 of file gmock-spec-builders.h.
       : UntypedOnCallSpecBase(a_file, a_line),
         matchers_(matchers),
         // By default, extra_matcher_ should match anything.  However,
         // we cannot initialize it with _ as that triggers a compiler
         // bug in Symbian's C++ compiler (cannot decide between two
         // overloaded constructors of Matcher<const ArgumentTuple&>).
         extra_matcher_(A<const ArgumentTuple&>()) {
   }
template<typename F> testing::internal::OnCallSpec< F >::OnCallSpec (const char * a_file, int a_line, const ArgumentMatcherTuple & matchers) inline
Definition at line 292 of file gmock-spec-builders.h.
       : UntypedOnCallSpecBase(a_file, a_line),
         matchers_(matchers),
         // By default, extra_matcher_ should match anything.  However,
         // we cannot initialize it with _ as that triggers a compiler
         // bug in Symbian's C++ compiler (cannot decide between two
         // overloaded constructors of Matcher<const ArgumentTuple&>).
         extra_matcher_(A<const ArgumentTuple&>()) {
   }
Member Function Documentation
template<typename F> const Action<F>& testing::internal::OnCallSpec< F >::GetAction () const inline
Definition at line 334 of file gmock-spec-builders.h.
Referenced by testing::internal::FunctionMockerBase< R(A1, A2)>::PerformDefaultAction().
{
     AssertSpecProperty(last_clause_ == kWillByDefault,
                        ".WillByDefault() must appear exactly "
                        "once in an ON_CALL().");
     return action_;
   }
template<typename F> const Action<F>& testing::internal::OnCallSpec< F >::GetAction () const inline
Definition at line 334 of file gmock-spec-builders.h.
{
     AssertSpecProperty(last_clause_ == kWillByDefault,
                        ".WillByDefault() must appear exactly "
                        "once in an ON_CALL().");
     return action_;
   }
template<typename F> const Action<F>& testing::internal::OnCallSpec< F >::GetAction () const inline
Definition at line 334 of file gmock-spec-builders.h.
{
     AssertSpecProperty(last_clause_ == kWillByDefault,
                        ".WillByDefault() must appear exactly "
                        "once in an ON_CALL().");
     return action_;
   }
template<typename F> bool testing::internal::OnCallSpec< F >::Matches (const ArgumentTuple & args) const inline
Definition at line 329 of file gmock-spec-builders.h.
References testing::internal::TupleMatches().
Referenced by testing::internal::FunctionMockerBase< R(A1, A2)>::FindOnCallSpec().
{
     return TupleMatches(matchers_, args) && extra_matcher_.Matches(args);
   }
template<typename F> bool testing::internal::OnCallSpec< F >::Matches (const ArgumentTuple & args) const inline
Definition at line 329 of file gmock-spec-builders.h.
References testing::internal::TupleMatches().
{
     return TupleMatches(matchers_, args) && extra_matcher_.Matches(args);
   }
template<typename F> bool testing::internal::OnCallSpec< F >::Matches (const ArgumentTuple & args) const inline
Definition at line 329 of file gmock-spec-builders.h.
References testing::internal::TupleMatches().
{
     return TupleMatches(matchers_, args) && extra_matcher_.Matches(args);
   }
template<typename F> OnCallSpec& testing::internal::OnCallSpec< F >::WillByDefault (const Action< F > & action) inline
Definition at line 316 of file gmock-spec-builders.h.
References upload::action, and testing::Action< F >::IsDoDefault().
{
     ExpectSpecProperty(last_clause_ < kWillByDefault,
                        ".WillByDefault() must appear "
                        "exactly once in an ON_CALL().");
     last_clause_ = kWillByDefault;
     ExpectSpecProperty(!action.IsDoDefault(),
                        "DoDefault() cannot be used in ON_CALL().");
     action_ = action;
     return *this;
   }
template<typename F> OnCallSpec& testing::internal::OnCallSpec< F >::WillByDefault (const Action< F > & action) inline
Definition at line 316 of file gmock-spec-builders.h.
References upload::action, and testing::Action< F >::IsDoDefault().
{
     ExpectSpecProperty(last_clause_ < kWillByDefault,
                        ".WillByDefault() must appear "
                        "exactly once in an ON_CALL().");
     last_clause_ = kWillByDefault;
     ExpectSpecProperty(!action.IsDoDefault(),
                        "DoDefault() cannot be used in ON_CALL().");
     action_ = action;
     return *this;
   }
template<typename F> OnCallSpec& testing::internal::OnCallSpec< F >::WillByDefault (const Action< F > & action) inline
Definition at line 316 of file gmock-spec-builders.h.
References upload::action, and testing::Action< F >::IsDoDefault().
{
     ExpectSpecProperty(last_clause_ < kWillByDefault,
                        ".WillByDefault() must appear "
                        "exactly once in an ON_CALL().");
     last_clause_ = kWillByDefault;
     ExpectSpecProperty(!action.IsDoDefault(),
                        "DoDefault() cannot be used in ON_CALL().");
     action_ = action;
     return *this;
   }
template<typename F> OnCallSpec& testing::internal::OnCallSpec< F >::With (const Matcher< const ArgumentTuple & > & m) inline
Definition at line 304 of file gmock-spec-builders.h.
References m.
{
     // Makes sure this is called at most once.
     ExpectSpecProperty(last_clause_ < kWith,
                        ".With() cannot appear "
                        "more than once in an ON_CALL().");
     last_clause_ = kWith;
     extra_matcher_ = m;
     return *this;
   }
template<typename F> OnCallSpec& testing::internal::OnCallSpec< F >::With (const Matcher< const ArgumentTuple & > & m) inline
Definition at line 304 of file gmock-spec-builders.h.
References m.
{
     // Makes sure this is called at most once.
     ExpectSpecProperty(last_clause_ < kWith,
                        ".With() cannot appear "
                        "more than once in an ON_CALL().");
     last_clause_ = kWith;
     extra_matcher_ = m;
     return *this;
   }
template<typename F> OnCallSpec& testing::internal::OnCallSpec< F >::With (const Matcher< const ArgumentTuple & > & m) inline
Definition at line 304 of file gmock-spec-builders.h.
References m.
{
     // Makes sure this is called at most once.
     ExpectSpecProperty(last_clause_ < kWith,
                        ".With() cannot appear "
                        "more than once in an ON_CALL().");
     last_clause_ = kWith;
     extra_matcher_ = m;
     return *this;
   }
Member Data Documentation
template<typename F> Action< F > testing::internal::OnCallSpec< F >::action_ private
Definition at line 357 of file gmock-spec-builders.h.
template<typename F> Matcher< const ArgumentTuple & > testing::internal::OnCallSpec< F >::extra_matcher_ private
Definition at line 356 of file gmock-spec-builders.h.
template<typename F> ArgumentMatcherTuple testing::internal::OnCallSpec< F >::matchers_ private
Definition at line 355 of file gmock-spec-builders.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-spec-builders.h