proxygen: testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher > Class Template Reference
testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher > Class Template Reference
#include <gmock-matchers.h>
Classes
class Impl
Public Member Functions
BeginEndDistanceIsMatcher (const DistanceMatcher &distance_matcher)
template<typename Container >
operator Matcher< Container > () const
BeginEndDistanceIsMatcher (const DistanceMatcher &distance_matcher)
template<typename Container >
operator Matcher< Container > () const
BeginEndDistanceIsMatcher (const DistanceMatcher &distance_matcher)
template<typename Container >
operator Matcher< Container > () const
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (BeginEndDistanceIsMatcher)
GTEST_DISALLOW_ASSIGN_ (BeginEndDistanceIsMatcher)
GTEST_DISALLOW_ASSIGN_ (BeginEndDistanceIsMatcher)
Private Attributes
const DistanceMatcher distance_matcher_
Detailed Description
template<typename DistanceMatcher>
class testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >
Definition at line 2452 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename DistanceMatcher > testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::BeginEndDistanceIsMatcher (const DistanceMatcher & distance_matcher) inline explicit
Definition at line 2454 of file gmock-matchers.h.
       : distance_matcher_(distance_matcher) {}
template<typename DistanceMatcher > testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::BeginEndDistanceIsMatcher (const DistanceMatcher & distance_matcher) inline explicit
Definition at line 2454 of file gmock-matchers.h.
       : distance_matcher_(distance_matcher) {}
template<typename DistanceMatcher > testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::BeginEndDistanceIsMatcher (const DistanceMatcher & distance_matcher) inline explicit
Definition at line 2454 of file gmock-matchers.h.
       : distance_matcher_(distance_matcher) {}
Member Function Documentation
template<typename DistanceMatcher > testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::GTEST_DISALLOW_ASSIGN_ (BeginEndDistanceIsMatcher< DistanceMatcher >) private
template<typename DistanceMatcher > testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::GTEST_DISALLOW_ASSIGN_ (BeginEndDistanceIsMatcher< DistanceMatcher >) private
template<typename DistanceMatcher > testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::GTEST_DISALLOW_ASSIGN_ (BeginEndDistanceIsMatcher< DistanceMatcher >) private
template<typename DistanceMatcher > template<typename Container > testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::operator Matcher< Container > () const inline
Definition at line 2458 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(new Impl<Container>(distance_matcher_));
   }
template<typename DistanceMatcher > template<typename Container > testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::operator Matcher< Container > () const inline
Definition at line 2458 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(new Impl<Container>(distance_matcher_));
   }
template<typename DistanceMatcher > template<typename Container > testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::operator Matcher< Container > () const inline
Definition at line 2458 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(new Impl<Container>(distance_matcher_));
   }
Member Data Documentation
template<typename DistanceMatcher > const DistanceMatcher testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::distance_matcher_ private
Definition at line 2506 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h