proxygen: Counters Class Reference
Counters Class Reference
Public Member Functions
Counters (size_t numCounters)
void increment (int64_t obj_id)
int64_t getValue (int64_t obj_id)
string toString ()
Private Attributes
AtomicHashMap< int64_t, int64_t > ahm
Detailed Description
Definition at line 266 of file AtomicHashMapTest.cpp.
Constructor & Destructor Documentation
Counters::Counters (size_t numCounters) inline explicit
Definition at line 274 of file AtomicHashMapTest.cpp.
 : ahm(numCounters) {}
Member Function Documentation
int64_t Counters::getValue (int64_t obj_id) inline
Definition at line 284 of file AtomicHashMapTest.cpp.
References folly::AtomicHashMap< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::end(), and folly::AtomicHashMap< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::find().
Referenced by TEST().
{
     auto ret = ahm.find(obj_id);
     return ret != ahm.end() ? ret->second : 0;
   }
void Counters::increment (int64_t obj_id) inline
Definition at line 276 of file AtomicHashMapTest.cpp.
References folly::AtomicHashMap< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::insert().
Referenced by TEST().
{
     auto ret = ahm.insert(std::make_pair(obj_id, 1));
     if (!ret.second) {
       // obj_id already exists, increment count
       __sync_fetch_and_add(&ret.first->second, 1);
     }
   }
string Counters::toString () inline
Definition at line 290 of file AtomicHashMapTest.cpp.
References folly::AtomicHashMap< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::size().
Referenced by TEST().
                     {
     string ret = "{\n";
     ret.reserve(ahm.size() * 32);
     for (const auto& e : ahm) {
       ret += folly::to<string>("  [", e.first, ":", e.second, "]\n");
     }
     ret += "}\n";
     return ret;
   }
Member Data Documentation
AtomicHashMap<int64_t, int64_t> Counters::ahm private
Definition at line 271 of file AtomicHashMapTest.cpp.
The documentation for this class was generated from the following file:
proxygen/folly/folly/test/AtomicHashMapTest.cpp