proxygen: fizz::client::test::MockClientStateMachine Class Reference
fizz::client::test::MockClientStateMachine Class Reference
#include <Mocks.h>
Public Member Functions
MOCK_METHOD6 (_processConnect, folly::Optional< Actions >(const State &, std::shared_ptr< const FizzClientContext > context, std::shared_ptr< const CertificateVerifier >, folly::Optional< std::string > host, folly::Optional< CachedPsk > cachedPsk, const std::shared_ptr< ClientExtensions > &extensions))
Actions processConnect (const State &state, std::shared_ptr< const FizzClientContext > context, std::shared_ptr< const CertificateVerifier > verifier, folly::Optional< std::string > host, folly::Optional< CachedPsk > cachedPsk, const std::shared_ptr< ClientExtensions > &extensions) override
MOCK_METHOD2 (_processSocketData, folly::Optional< Actions >(const State &, folly::IOBufQueue &))
Actions processSocketData (const State &state, folly::IOBufQueue &queue) override
MOCK_METHOD2 (_processAppWrite, folly::Optional< Actions >(const State &, AppWrite &))
Actions processAppWrite (const State &state, AppWrite appWrite) override
MOCK_METHOD2 (_processEarlyAppWrite, folly::Optional< Actions >(const State &, EarlyAppWrite &))
Actions processEarlyAppWrite (const State &state, EarlyAppWrite appWrite) override
MOCK_METHOD1 (_processAppClose, folly::Optional< Actions >(const State &))
Actions processAppClose (const State &state) override
Public Member Functions inherited from fizz::client::ClientStateMachine
virtual ~ClientStateMachine ()=default
virtual Actions processConnect (const State &, std::shared_ptr< const FizzClientContext > context, std::shared_ptr< const CertificateVerifier > verifier, folly::Optional< std::string > sni, folly::Optional< CachedPsk > cachedPsk, const std::shared_ptr< ClientExtensions > &extensions)
virtual Actions processSocketData (const State &, folly::IOBufQueue &)
virtual Actions processWriteNewSessionTicket (const State &, WriteNewSessionTicket)
virtual Actions processAppWrite (const State &, AppWrite)
virtual Actions processEarlyAppWrite (const State &, EarlyAppWrite)
virtual Actions processAppClose (const State &)
Additional Inherited Members
Public Types inherited from fizz::client::ClientStateMachine
using StateType = State
using ProcessingActions = Actions
using CompletedActions = Actions
Detailed Description
Definition at line 20 of file Mocks.h.
Member Function Documentation
fizz::client::test::MockClientStateMachine::MOCK_METHOD1 (_processAppClose , folly::Optional< Actions > const State &)
Referenced by fizz::client::test::MockHandshakeCallbackT< fizz::client::test::MockClientStateMachineInstance >::fizzHandshakeSuccess(), and processEarlyAppWrite().
fizz::client::test::MockClientStateMachine::MOCK_METHOD2 (_processSocketData , folly::Optional< Actions > const State &, folly::IOBufQueue &)
Referenced by processAppWrite(), processConnect(), and processSocketData().
fizz::client::test::MockClientStateMachine::MOCK_METHOD2 (_processAppWrite , folly::Optional< Actions > const State &, AppWrite &)
fizz::client::test::MockClientStateMachine::MOCK_METHOD2 (_processEarlyAppWrite , folly::Optional< Actions > const State &, EarlyAppWrite &)
fizz::client::test::MockClientStateMachine::MOCK_METHOD6 (_processConnect , folly::Optional< Actions > const State &, std::shared_ptr< const FizzClientContext > context, std::shared_ptr< const CertificateVerifier >, folly::Optional< std::string > host, folly::Optional< CachedPsk > cachedPsk, const std::shared_ptr< ClientExtensions > &extensions)
Actions fizz::client::test::MockClientStateMachine::processAppClose (const State & state) inline override
Definition at line 66 of file Mocks.h.
{
     return *_processAppClose(state);
   }
Actions fizz::client::test::MockClientStateMachine::processAppWrite (const State & state, AppWrite appWrite) inline override
Definition at line 53 of file Mocks.h.
References MOCK_METHOD2().
{
     return *_processAppWrite(state, appWrite);
   }
Actions fizz::client::test::MockClientStateMachine::processConnect (const State & state, std::shared_ptr< const FizzClientContext > context, std::shared_ptr< const CertificateVerifier > verifier, folly::Optional< std::string > host, folly::Optional< CachedPsk > cachedPsk, const std::shared_ptr< ClientExtensions > & extensions) inline override
Definition at line 31 of file Mocks.h.
References MOCK_METHOD2().
{
     return *_processConnect(
         state, context, verifier, host, cachedPsk, extensions);
   }
Actions fizz::client::test::MockClientStateMachine::processEarlyAppWrite (const State & state, EarlyAppWrite appWrite) inline override
Definition at line 60 of file Mocks.h.
References MOCK_METHOD1().
                {
     return *_processEarlyAppWrite(state, appWrite);
   }
Actions fizz::client::test::MockClientStateMachine::processSocketData (const State & state, folly::IOBufQueue & queue) inline override
Definition at line 45 of file Mocks.h.
References MOCK_METHOD2().
                {
     return *_processSocketData(state, queue);
   }
The documentation for this class was generated from the following file:
proxygen/fizz/fizz/client/test/Mocks.h