proxygen: folly::AsyncSocket::ConnectCallback Class Reference
folly::AsyncSocket::ConnectCallback Class Reference abstract
#include <AsyncSocket.h>
Public Member Functions
virtual ~ConnectCallback ()=default
virtual void connectSuccess () noexcept=0
virtual void connectErr (const AsyncSocketException &ex) noexcept=0
Detailed Description
Definition at line 85 of file AsyncSocket.h.
Constructor & Destructor Documentation
virtual folly::AsyncSocket::ConnectCallback::~ConnectCallback () virtual default
Member Function Documentation
virtual void folly::AsyncSocket::ConnectCallback::connectErr (const AsyncSocketException & ex) pure virtual noexcept
connectErr() will be invoked if the connection attempt fails.
Parameters
ex An exception describing the error that occurred.
Implemented in folly::SSLClient, folly::ConnectClient, BogoTestClient, fizz::client::AsyncFizzClientT< SM >, fizz::client::AsyncFizzClientT< fizz::client::test::MockClientStateMachineInstance >, proxygen::HTTPConnector, Cb, folly::AttachDetachClient, ProxyService::ProxyHandler, BlockingSocket, folly::ZeroCopyTestAsyncSocket::Callback, SSLCacheClient, wangle::ClientBootstrap< Pipeline >::ConnectCallback, BogoTestServer, fizz::client::test::MockConnectCallback, and ConnCallback.
Referenced by folly::AsyncSocket::invalidState(), folly::AsyncSocket::invokeConnectErr(), and fizz::client::test::TEST_F().
virtual void folly::AsyncSocket::ConnectCallback::connectSuccess () pure virtual noexcept
connectSuccess() will be invoked when the connection has been successfully established.
Implemented in folly::SSLClient, folly::ConnectClient, BogoTestClient, fizz::client::AsyncFizzClientT< SM >, fizz::client::AsyncFizzClientT< fizz::client::test::MockClientStateMachineInstance >, proxygen::HTTPConnector, Cb, ProxyService::ProxyHandler, folly::AttachDetachClient, BlockingSocket, folly::ZeroCopyTestAsyncSocket::Callback, SSLCacheClient, BogoTestServer, wangle::ClientBootstrap< Pipeline >::ConnectCallback, fizz::client::test::MockConnectCallback, and ConnCallback.
Referenced by folly::AsyncSocket::invokeConnectSuccess().
The documentation for this class was generated from the following file:
proxygen/folly/folly/io/async/AsyncSocket.h