proxygen: cpp.ast.Include Class Reference
cpp.ast.Include Class Reference
Public Member Functions
def __init__ (self, start, end, filename, system)
def __str__ (self)
def __init__ (self, start, end, filename, system)
def __str__ (self)
def __init__ (self, start, end, filename, system)
def __str__ (self)
Public Member Functions inherited from cpp.ast.Node
def __init__ (self, start, end)
def IsDeclaration (self)
def IsDefinition (self)
def IsExportable (self)
def Requires (self, node)
def XXX__str__ (self)
def __repr__ (self)
def __init__ (self, start, end)
def IsDeclaration (self)
def IsDefinition (self)
def IsExportable (self)
def Requires (self, node)
def XXX__str__ (self)
def __repr__ (self)
def __init__ (self, start, end)
def IsDeclaration (self)
def IsDefinition (self)
def IsExportable (self)
def Requires (self, node)
def XXX__str__ (self)
def __repr__ (self)
Public Attributes
filename
system
Public Attributes inherited from cpp.ast.Node
start
end
Detailed Description
Definition at line 155 of file ast.py.
Constructor & Destructor Documentation
def cpp.ast.Include.__init__ (self, start, end, filename, system)
Definition at line 156 of file ast.py.
Referenced by cpp.ast.Include.__init__().
     def __init__(self, start, end, filename, system):
         Node.__init__(self, start, end)
         self.filename = filename
         self.system = system
def cpp.ast.Include.__init__ (self, start, end, filename, system)
Definition at line 156 of file ast.py.
References cpp.ast.Include.__init__(), cpp.ast.Include.filename, and cpp.ast.Include.system.
     def __init__(self, start, end, filename, system):
         Node.__init__(self, start, end)
         self.filename = filename
         self.system = system
def cpp.ast.Include.__init__ (self, start, end, filename, system)
Definition at line 156 of file ast.py.
References cpp.ast.Include.__init__(), cpp.ast.Include.filename, and cpp.ast.Include.system.
     def __init__(self, start, end, filename, system):
         Node.__init__(self, start, end)
         self.filename = filename
         self.system = system
Member Function Documentation
def cpp.ast.Include.__str__ (self)
Definition at line 161 of file ast.py.
References cpp.ast.Node._StringHelper(), cpp.ast.Include.filename, and cpp.ast.Include.system.
Referenced by cpp.ast.Include.__str__().
     def __str__(self):
         fmt = '"%s"'
         if self.system:
             fmt = '<%s>'
         return self._StringHelper(self.__class__.__name__, fmt % self.filename)
def cpp.ast.Include.__str__ (self)
Definition at line 161 of file ast.py.
References cpp.ast.Include.__str__(), cpp.ast.Node._StringHelper(), cpp.ast.Include.filename, and cpp.ast.Include.system.
     def __str__(self):
         fmt = '"%s"'
         if self.system:
             fmt = '<%s>'
         return self._StringHelper(self.__class__.__name__, fmt % self.filename)
def cpp.ast.Include.__str__ (self)
Definition at line 161 of file ast.py.
References cpp.ast.Include.__str__(), cpp.ast.Node._StringHelper(), cpp.ast.Include.filename, and cpp.ast.Include.system.
     def __str__(self):
         fmt = '"%s"'
         if self.system:
             fmt = '<%s>'
         return self._StringHelper(self.__class__.__name__, fmt % self.filename)
Member Data Documentation
cpp.ast.Include.filename
Definition at line 158 of file ast.py.
Referenced by cpp.ast.Include.__init__(), cpp.ast.AstBuilder.__init__(), cpp.ast.Include.__str__(), cpp.ast.AstBuilder._GetClass(), and cpp.ast.AstBuilder.HandleError().
cpp.ast.Include.system
Definition at line 159 of file ast.py.
Referenced by cpp.ast.Include.__init__(), and cpp.ast.Include.__str__().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/scripts/generator/cpp/ast.py