proxygen: testing::internal::ExpectationTester Class Reference
testing::internal::ExpectationTester Class Reference
Public Member Functions
void SetCallCount (int n, ExpectationBase *exp)
void SetCallCount (int n, ExpectationBase *exp)
void SetCallCount (int n, ExpectationBase *exp)
Detailed Description
Definition at line 52 of file gmock-spec-builders_test.cc.
Member Function Documentation
void testing::internal::ExpectationTester::SetCallCount (int n, ExpectationBase * exp) inline
Definition at line 55 of file gmock-spec-builders_test.cc.
References testing::_, testing::AnyNumber(), testing::AtLeast(), testing::AtMost(), testing::Between(), testing::gmock_generated_actions_test::Binary(), testing::internal::ExpectationBase::call_count_, testing::internal::CaptureStdout(), testing::Const(), testing::ContainsRegex(), testing::DoAll(), testing::DoDefault(), testing::Eq(), EXPECT_CALL, testing::internal::FormatFileLocation(), testing::internal::GetCapturedStdout(), GMOCK_FLAG, testing::Gt(), GTEST_DISALLOW_COPY_AND_ASSIGN_, testing::HasSubstr(), testing::Invoke(), testing::InvokeWithoutArgs(), testing::IsNotSubstring(), testing::IsSubstring(), testing::internal::kErrorVerbosity, testing::internal::kInfoVerbosity, testing::internal::kWarningVerbosity, testing::Lt(), MOCK_CONST_METHOD0, MOCK_METHOD0, MOCK_METHOD1, MOCK_METHOD2, testing::Ne(), testing::internal::PrintTo(), testing::Return(), testing::SetArgPointee(), and testing::internal::TEST().
{
     exp->call_count_ = n;
   }
void testing::internal::ExpectationTester::SetCallCount (int n, ExpectationBase * exp) inline
Definition at line 55 of file gmock-spec-builders_test.cc.
References testing::_, testing::AnyNumber(), testing::AtLeast(), testing::AtMost(), testing::Between(), testing::gmock_generated_actions_test::Binary(), testing::internal::ExpectationBase::call_count_, testing::internal::CaptureStdout(), testing::Const(), testing::ContainsRegex(), testing::DoAll(), testing::DoDefault(), testing::Eq(), EXPECT_CALL, testing::internal::FormatFileLocation(), testing::internal::GetCapturedStdout(), GMOCK_FLAG, testing::Gt(), GTEST_DISALLOW_COPY_AND_ASSIGN_, testing::HasSubstr(), testing::Invoke(), testing::InvokeWithoutArgs(), testing::IsNotSubstring(), testing::IsSubstring(), testing::internal::kErrorVerbosity, testing::internal::kInfoVerbosity, testing::internal::kWarningVerbosity, testing::Lt(), MOCK_CONST_METHOD0, MOCK_METHOD0, MOCK_METHOD1, MOCK_METHOD2, testing::Ne(), testing::internal::PrintTo(), testing::Return(), testing::SetArgPointee(), and testing::internal::TEST().
{
     exp->call_count_ = n;
   }
void testing::internal::ExpectationTester::SetCallCount (int n, ExpectationBase * exp) inline
Definition at line 55 of file gmock-spec-builders_test.cc.
References testing::_, testing::AnyNumber(), testing::AtLeast(), testing::AtMost(), testing::Between(), testing::gmock_generated_actions_test::Binary(), testing::internal::ExpectationBase::call_count_, testing::internal::CaptureStdout(), testing::Const(), testing::ContainsRegex(), testing::DoAll(), testing::DoDefault(), testing::Eq(), EXPECT_CALL, testing::internal::FormatFileLocation(), testing::internal::GetCapturedStdout(), GMOCK_FLAG, testing::Gt(), GTEST_DISALLOW_COPY_AND_ASSIGN_, testing::HasSubstr(), testing::Invoke(), testing::InvokeWithoutArgs(), testing::IsNotSubstring(), testing::IsSubstring(), testing::internal::kErrorVerbosity, testing::internal::kInfoVerbosity, testing::internal::kWarningVerbosity, testing::Lt(), MOCK_CONST_METHOD0, MOCK_METHOD0, MOCK_METHOD1, MOCK_METHOD2, testing::Ne(), testing::internal::PrintTo(), testing::Return(), testing::SetArgPointee(), and testing::internal::TEST().
{
     exp->call_count_ = n;
   }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-spec-builders_test.cc