proxygen: wangle::Handler< Rin, Rout, Win, Wout > Class Template Reference
wangle::Handler< Rin, Rout, Win, Wout > Class Template Reference abstract
#include <Handler.h>
Public Types
typedef Rin rin
typedef Rout rout
typedef Win win
typedef Wout wout
typedef HandlerContext< Rout, Wout > Context
Public Member Functions
~Handler () override=default
virtual void read (Context *ctx, Rin msg)=0
virtual void readEOF (Context *ctx)
virtual void readException (Context *ctx, folly::exception_wrapper e)
virtual void transportActive (Context *ctx)
virtual void transportInactive (Context *ctx)
virtual folly::Future< folly::Unit > write (Context *ctx, Win msg)=0
virtual folly::Future< folly::Unit > writeException (Context *ctx, folly::exception_wrapper e)
virtual folly::Future< folly::Unit > close (Context *ctx)
Public Member Functions inherited from wangle::HandlerBase< HandlerContext< Rout, Wout > >
virtual ~HandlerBase ()=default
virtual void attachPipeline (HandlerContext< Rout, Wout > *)
virtual void detachPipeline (HandlerContext< Rout, Wout > *)
HandlerContext< Rout, Wout > * getContext ()
Static Public Attributes
static const HandlerDir dir = HandlerDir::BOTH
Detailed Description
template<class Rin, class Rout = Rin, class Win = Rout, class Wout = Rin>
class wangle::Handler< Rin, Rout, Win, Wout >
Definition at line 49 of file Handler.h.
Member Typedef Documentation
template<class Rin, class Rout = Rin, class Win = Rout, class Wout = Rin> typedef HandlerContext<Rout, Wout> wangle::Handler< Rin, Rout, Win, Wout >::Context
Definition at line 57 of file Handler.h.
template<class Rin, class Rout = Rin, class Win = Rout, class Wout = Rin> typedef Rin wangle::Handler< Rin, Rout, Win, Wout >::rin
Definition at line 53 of file Handler.h.
template<class Rin, class Rout = Rin, class Win = Rout, class Wout = Rin> typedef Rout wangle::Handler< Rin, Rout, Win, Wout >::rout
Definition at line 54 of file Handler.h.
template<class Rin, class Rout = Rin, class Win = Rout, class Wout = Rin> typedef Win wangle::Handler< Rin, Rout, Win, Wout >::win
Definition at line 55 of file Handler.h.
template<class Rin, class Rout = Rin, class Win = Rout, class Wout = Rin> typedef Wout wangle::Handler< Rin, Rout, Win, Wout >::wout
Definition at line 56 of file Handler.h.
Constructor & Destructor Documentation
template<class Rin, class Rout = Rin, class Win = Rout, class Wout = Rin> wangle::Handler< Rin, Rout, Win, Wout >::~Handler () override default
Member Function Documentation
template<class Rin, class Rout = Rin, class Win = Rout, class Wout = Rin> virtual folly::Future<folly::Unit> wangle::Handler< Rin, Rout, Win, Wout >::close (Context * ctx) inline virtual
Reimplemented in BonkMultiplexClientDispatcher, wangle::MockHandler< Rin, Rout, Win, Wout >, wangle::ClientDispatcherBase< SerializePipeline, Bonk, Xtruct >, and wangle::ClientDispatcherBase< wangle::Pipeline, folly::Req, Resp >.
Definition at line 79 of file Handler.h.
{
     return ctx->fireClose();
   }
template<class Rin, class Rout = Rin, class Win = Rout, class Wout = Rin> virtual void wangle::Handler< Rin, Rout, Win, Wout >::read (Context * ctx, Rin msg) pure virtual
Implemented in ConcreteHandler< Rin, Rout, Win, Wout >, wangle::HandlerAdapter< Resp, folly::Req >, wangle::HandlerAdapter< Xtruct, Bonk >, wangle::HandlerAdapter< int, std::unique_ptr< folly::IOBuf > >, wangle::HandlerAdapter< folly::IOBufQueue &, int >, wangle::HandlerAdapter< std::string >, wangle::HandlerAdapter< folly::IOBufQueue &, T >, wangle::HandlerAdapter< Resp, Req >, wangle::HandlerAdapter< T, std::unique_ptr< folly::IOBuf > >, wangle::HandlerAdapter< std::string, std::unique_ptr< folly::IOBuf > >, wangle::HandlerAdapter< Req, Resp >, wangle::SerialClientDispatcher< wangle::Pipeline, folly::Req, Resp >, BonkMultiplexClientDispatcher, wangle::MockHandler< Rin, Rout, Win, Wout >, EchoHandler, TelnetHandler, EchoHandler, FileServerHandler, TelnetHandler, ClientSerializeHandler, and ServerSerializeHandler.
template<class Rin, class Rout = Rin, class Win = Rout, class Wout = Rin> virtual void wangle::Handler< Rin, Rout, Win, Wout >::readEOF (Context * ctx) inline virtual
Reimplemented in EchoHandler, and TelnetHandler.
Definition at line 61 of file Handler.h.
Referenced by wangle::MockBytesToBytesHandler::defaultFuture().
{
     ctx->fireReadEOF();
   }
template<class Rin, class Rout = Rin, class Win = Rout, class Wout = Rin> virtual void wangle::Handler< Rin, Rout, Win, Wout >::readException (Context * ctx, folly::exception_wrapper e) inline virtual
Reimplemented in FileServerHandler, EchoHandler, and TelnetHandler.
Definition at line 64 of file Handler.h.
Referenced by wangle::MockBytesToBytesHandler::defaultFuture().
{
     ctx->fireReadException(std::move(e));
   }
template<class Rin, class Rout = Rin, class Win = Rout, class Wout = Rin> virtual void wangle::Handler< Rin, Rout, Win, Wout >::transportActive (Context * ctx) inline virtual
Reimplemented in FileServerHandler, and TelnetHandler.
Definition at line 67 of file Handler.h.
Referenced by wangle::MockBytesToBytesHandler::defaultFuture().
{
     ctx->fireTransportActive();
   }
template<class Rin, class Rout = Rin, class Win = Rout, class Wout = Rin> virtual void wangle::Handler< Rin, Rout, Win, Wout >::transportInactive (Context * ctx) inline virtual
Definition at line 70 of file Handler.h.
Referenced by wangle::MockBytesToBytesHandler::defaultFuture().
{
     ctx->fireTransportInactive();
   }
template<class Rin, class Rout = Rin, class Win = Rout, class Wout = Rin> virtual folly::Future<folly::Unit> wangle::Handler< Rin, Rout, Win, Wout >::write (Context * ctx, Win msg) pure virtual
Implemented in ConcreteHandler< Rin, Rout, Win, Wout >, wangle::HandlerAdapter< Resp, folly::Req >, wangle::HandlerAdapter< Xtruct, Bonk >, wangle::HandlerAdapter< int, std::unique_ptr< folly::IOBuf > >, wangle::HandlerAdapter< folly::IOBufQueue &, int >, wangle::HandlerAdapter< std::string >, wangle::HandlerAdapter< folly::IOBufQueue &, T >, wangle::HandlerAdapter< Resp, Req >, wangle::HandlerAdapter< T, std::unique_ptr< folly::IOBuf > >, wangle::HandlerAdapter< std::string, std::unique_ptr< folly::IOBuf > >, wangle::HandlerAdapter< Req, Resp >, wangle::MockHandler< Rin, Rout, Win, Wout >, ClientSerializeHandler, and ServerSerializeHandler.
template<class Rin, class Rout = Rin, class Win = Rout, class Wout = Rin> virtual folly::Future<folly::Unit> wangle::Handler< Rin, Rout, Win, Wout >::writeException (Context * ctx, folly::exception_wrapper e) inline virtual
Reimplemented in wangle::MockHandler< Rin, Rout, Win, Wout >.
Definition at line 75 of file Handler.h.
{
     return ctx->fireWriteException(std::move(e));
   }
Member Data Documentation
template<class Rin, class Rout = Rin, class Win = Rout, class Wout = Rin> const HandlerDir wangle::Handler< Rin, Rout, Win, Wout >::dir = HandlerDir::BOTH static
Definition at line 51 of file Handler.h.
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/channel/Handler.h