proxygen: folly::ReadMostlyMainPtr< T, RefCount > Class Template Reference
folly::ReadMostlyMainPtr< T, RefCount > Class Template Reference
#include <ReadMostlySharedPtr.h>
Public Member Functions
ReadMostlyMainPtr ()
ReadMostlyMainPtr (std::shared_ptr< T > ptr)
ReadMostlyMainPtr (const ReadMostlyMainPtr &)=delete
ReadMostlyMainPtr & operator= (const ReadMostlyMainPtr &)=delete
ReadMostlyMainPtr (ReadMostlyMainPtr &&other) noexcept
ReadMostlyMainPtr & operator= (ReadMostlyMainPtr &&other) noexcept
bool operator== (const ReadMostlyMainPtr< T, RefCount > &other) const
bool operator== (T *other) const
bool operator== (const ReadMostlySharedPtr< T, RefCount > &other) const
~ReadMostlyMainPtr () noexcept
void reset () noexcept
void reset (std::shared_ptr< T > ptr)
T * get () const
std::shared_ptr< T > getStdShared () const
T & operator* () const
T * operator-> () const
ReadMostlySharedPtr< T, RefCount > getShared () const
operator bool () const
Private Attributes
detail::ReadMostlySharedPtrCore< T, RefCount > * impl_ {nullptr}
Friends
class ReadMostlyWeakPtr< T, RefCount >
class ReadMostlySharedPtr< T, RefCount >
class ReadMostlyMainPtrDeleter< RefCount >
Detailed Description
template<typename T, typename RefCount = DefaultRefCount>
class folly::ReadMostlyMainPtr< T, RefCount >
Definition at line 26 of file ReadMostlySharedPtr.h.
Constructor & Destructor Documentation
template<typename T, typename RefCount = DefaultRefCount> folly::ReadMostlyMainPtr< T, RefCount >::ReadMostlyMainPtr () inline
Definition at line 100 of file ReadMostlySharedPtr.h.
 {}
template<typename T, typename RefCount = DefaultRefCount> folly::ReadMostlyMainPtr< T, RefCount >::ReadMostlyMainPtr (std::shared_ptr< T > ptr) inline explicit
Definition at line 102 of file ReadMostlySharedPtr.h.
{
     reset(std::move(ptr));
   }
template<typename T, typename RefCount = DefaultRefCount> folly::ReadMostlyMainPtr< T, RefCount >::ReadMostlyMainPtr (const ReadMostlyMainPtr< T, RefCount > &) delete
template<typename T, typename RefCount = DefaultRefCount> folly::ReadMostlyMainPtr< T, RefCount >::ReadMostlyMainPtr (ReadMostlyMainPtr< T, RefCount > && other) inline noexcept
Definition at line 109 of file ReadMostlySharedPtr.h.
{
     *this = std::move(other);
   }
template<typename T, typename RefCount = DefaultRefCount> folly::ReadMostlyMainPtr< T, RefCount >::~ReadMostlyMainPtr () inline noexcept
Definition at line 131 of file ReadMostlySharedPtr.h.
{
     reset();
   }
Member Function Documentation
template<typename T, typename RefCount = DefaultRefCount> T* folly::ReadMostlyMainPtr< T, RefCount >::get () const inline
Definition at line 151 of file ReadMostlySharedPtr.h.
Referenced by folly::ReadMostlyMainPtr< T >::operator==(), folly::ReadMostlySharedPtr< T >::operator==(), folly::operator==(), and TEST_F().
                  {
     if (impl_) {
       return impl_->ptrRaw_;
     } else {
       return nullptr;
     }
   }
template<typename T, typename RefCount = DefaultRefCount> ReadMostlySharedPtr<T, RefCount> folly::ReadMostlyMainPtr< T, RefCount >::getShared () const inline
Definition at line 175 of file ReadMostlySharedPtr.h.
Referenced by TEST_F().
{
     return ReadMostlySharedPtr<T, RefCount>(*this);
   }
template<typename T, typename RefCount = DefaultRefCount> std::shared_ptr<T> folly::ReadMostlyMainPtr< T, RefCount >::getStdShared () const inline
Definition at line 159 of file ReadMostlySharedPtr.h.
Referenced by TEST_F().
{
     if (impl_) {
       return impl_->getShared();
     } else {
       return {};
     }
   }
template<typename T, typename RefCount = DefaultRefCount> folly::ReadMostlyMainPtr< T, RefCount >::operator bool () const inline explicit
Definition at line 179 of file ReadMostlySharedPtr.h.
{
     return impl_ != nullptr;
   }
template<typename T, typename RefCount = DefaultRefCount> T& folly::ReadMostlyMainPtr< T, RefCount >::operator* () const inline
Definition at line 167 of file ReadMostlySharedPtr.h.
{
     return *get();
   }
template<typename T, typename RefCount = DefaultRefCount> T* folly::ReadMostlyMainPtr< T, RefCount >::operator-> () const inline
Definition at line 171 of file ReadMostlySharedPtr.h.
{
     return get();
   }
template<typename T, typename RefCount = DefaultRefCount> ReadMostlyMainPtr& folly::ReadMostlyMainPtr< T, RefCount >::operator= (const ReadMostlyMainPtr< T, RefCount > &) delete
template<typename T, typename RefCount = DefaultRefCount> ReadMostlyMainPtr& folly::ReadMostlyMainPtr< T, RefCount >::operator= (ReadMostlyMainPtr< T, RefCount > && other) inline noexcept
Definition at line 113 of file ReadMostlySharedPtr.h.
{
     std::swap(impl_, other.impl_);
     return *this;
   }
template<typename T, typename RefCount = DefaultRefCount> bool folly::ReadMostlyMainPtr< T, RefCount >::operator== (const ReadMostlyMainPtr< T, RefCount > & other) const inline
Definition at line 119 of file ReadMostlySharedPtr.h.
{
     return get() == other.get();
   }
template<typename T, typename RefCount = DefaultRefCount> bool folly::ReadMostlyMainPtr< T, RefCount >::operator== (T * other) const inline
Definition at line 123 of file ReadMostlySharedPtr.h.
{
     return get() == other;
   }
template<typename T, typename RefCount = DefaultRefCount> bool folly::ReadMostlyMainPtr< T, RefCount >::operator== (const ReadMostlySharedPtr< T, RefCount > & other) const inline
Definition at line 127 of file ReadMostlySharedPtr.h.
{
     return get() == other.get();
   }
template<typename T, typename RefCount = DefaultRefCount> void folly::ReadMostlyMainPtr< T, RefCount >::reset () inline noexcept
Definition at line 135 of file ReadMostlySharedPtr.h.
Referenced by folly::detail::SingletonHolder< T >::createInstance(), and TEST_F().
{
     if (impl_) {
       impl_->count_.useGlobal();
       impl_->weakCount_.useGlobal();
       impl_->decref();
       impl_ = nullptr;
     }
   }
template<typename T, typename RefCount = DefaultRefCount> void folly::ReadMostlyMainPtr< T, RefCount >::reset (std::shared_ptr< T > ptr) inline
Definition at line 144 of file ReadMostlySharedPtr.h.
{
     reset();
     if (ptr) {
       impl_ = new detail::ReadMostlySharedPtrCore<T, RefCount>(std::move(ptr));
     }
   }
Friends And Related Function Documentation
template<typename T, typename RefCount = DefaultRefCount> friend class ReadMostlyMainPtrDeleter< RefCount > friend
Definition at line 186 of file ReadMostlySharedPtr.h.
template<typename T, typename RefCount = DefaultRefCount> friend class ReadMostlySharedPtr< T, RefCount > friend
Definition at line 185 of file ReadMostlySharedPtr.h.
template<typename T, typename RefCount = DefaultRefCount> friend class ReadMostlyWeakPtr< T, RefCount > friend
Definition at line 184 of file ReadMostlySharedPtr.h.
Member Data Documentation
template<typename T, typename RefCount = DefaultRefCount> detail::ReadMostlySharedPtrCore<T, RefCount>* folly::ReadMostlyMainPtr< T, RefCount >::impl_ {nullptr} private
Definition at line 188 of file ReadMostlySharedPtr.h.
Referenced by folly::ReadMostlyWeakPtr< T >::operator=(), folly::ReadMostlySharedPtr< T >::operator=(), folly::ReadMostlySharedPtr< T >::ReadMostlySharedPtr(), and folly::ReadMostlyWeakPtr< T >::ReadMostlyWeakPtr().
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/ReadMostlySharedPtr.h