proxygen: folly::detail::ScopeGuardImplBase Class Reference
folly::detail::ScopeGuardImplBase Class Reference
#include <ScopeGuard.h>
Public Member Functions
void dismiss () noexcept
Protected Member Functions
ScopeGuardImplBase () noexcept
Static Protected Member Functions
static void warnAboutToCrash () noexcept
static ScopeGuardImplBase makeEmptyScopeGuard () noexcept
template<typename T >
static const T & asConst (const T &t) noexcept
Protected Attributes
bool dismissed_
Detailed Description
Definition at line 35 of file ScopeGuard.h.
Constructor & Destructor Documentation
folly::detail::ScopeGuardImplBase::ScopeGuardImplBase () inline protected noexcept
Definition at line 42 of file ScopeGuard.h.
References folly::pushmi::__adl::noexcept(), and warnAboutToCrash().
 : dismissed_(false) {}
Member Function Documentation
template<typename T > static const T& folly::detail::ScopeGuardImplBase::asConst (const T & t) inline static protected noexcept
Definition at line 50 of file ScopeGuard.h.
References folly::pushmi::detail::t.
{
     return t;
   }
void folly::detail::ScopeGuardImplBase::dismiss () inline noexcept
Definition at line 37 of file ScopeGuard.h.
References dismissed_.
Referenced by folly::detail::ScopeGuardImpl< FunctionType, InvokeNoexcept >::ScopeGuardImpl().
{
     dismissed_ = true;
   }
static ScopeGuardImplBase folly::detail::ScopeGuardImplBase::makeEmptyScopeGuard () inline static protected noexcept
Definition at line 45 of file ScopeGuard.h.
Referenced by folly::detail::ScopeGuardImpl< FunctionType, InvokeNoexcept >::makeFailsafe().
{
     return ScopeGuardImplBase{};
   }
void folly::detail::ScopeGuardImplBase::warnAboutToCrash () static protected noexcept
Definition at line 21 of file ScopeGuard.cpp.
Referenced by folly::detail::ScopeGuardImpl< FunctionType, InvokeNoexcept >::execute(), and ScopeGuardImplBase().
{
   // Ensure the availability of std::cerr
   std::ios_base::Init ioInit;
   std::cerr
       << "This program will now terminate because a folly::ScopeGuard callback "
          "threw an \nexception.\n";
 }
Member Data Documentation
bool folly::detail::ScopeGuardImplBase::dismissed_ protected
Definition at line 54 of file ScopeGuard.h.
Referenced by dismiss(), folly::detail::ScopeGuardImpl< FunctionType, InvokeNoexcept >::ScopeGuardImpl(), and folly::detail::ScopeGuardImpl< FunctionType, InvokeNoexcept >::~ScopeGuardImpl().
The documentation for this class was generated from the following files:
proxygen/folly/folly/ScopeGuard.h
proxygen/folly/folly/ScopeGuard.cpp