proxygen: folly::SpinLock Class Reference
folly::SpinLock Class Reference
#include <SpinLock.h>
Public Member Functions
FOLLY_ALWAYS_INLINE SpinLock () noexcept
FOLLY_ALWAYS_INLINE void lock () const noexcept
FOLLY_ALWAYS_INLINE void unlock () const noexcept
FOLLY_ALWAYS_INLINE bool try_lock () const noexcept
Private Attributes
folly::MicroSpinLock lock_
Detailed Description
Definition at line 44 of file SpinLock.h.
Constructor & Destructor Documentation
FOLLY_ALWAYS_INLINE folly::SpinLock::SpinLock () inline noexcept
Definition at line 46 of file SpinLock.h.
References folly::MicroSpinLock::init(), and lock_.
{
     lock_.init();
   }
Member Function Documentation
FOLLY_ALWAYS_INLINE void folly::SpinLock::lock () const inline noexcept
Definition at line 49 of file SpinLock.h.
References folly::MicroSpinLock::lock(), and lock_.
Referenced by folly::ssl::detail::isSSLLockDisabled().
{
     lock_.lock();
   }
FOLLY_ALWAYS_INLINE bool folly::SpinLock::try_lock () const inline noexcept
Definition at line 55 of file SpinLock.h.
References lock_, and folly::MicroSpinLock::try_lock().
Referenced by folly::NotificationQueue< folly::AsyncServerSocket::QueueMessage >::checkQueueSize().
{
     return lock_.try_lock();
   }
FOLLY_ALWAYS_INLINE void folly::SpinLock::unlock () const inline noexcept
Definition at line 52 of file SpinLock.h.
References lock_, and folly::MicroSpinLock::unlock().
Referenced by folly::ssl::detail::isSSLLockDisabled(), folly::fibers::TimedRWMutex< BatonType >::ReadHolder::~ReadHolder(), and folly::fibers::TimedRWMutex< BatonType >::WriteHolder::~WriteHolder().
{
     lock_.unlock();
   }
Member Data Documentation
folly::MicroSpinLock folly::SpinLock::lock_ mutable private
Definition at line 60 of file SpinLock.h.
Referenced by lock(), SpinLock(), folly::SpinLockGuardImpl< LOCK >::SpinLockGuardImpl(), try_lock(), unlock(), and folly::SpinLockGuardImpl< LOCK >::~SpinLockGuardImpl().
The documentation for this class was generated from the following file:
proxygen/folly/folly/SpinLock.h