proxygen: QueueNode< E > Class Template Reference
QueueNode< E > Class Template Reference
#include <sample3-inl.h>
Public Member Functions
const E & element () const
QueueNode * next ()
const QueueNode * next () const
const E & element () const
QueueNode * next ()
const QueueNode * next () const
const E & element () const
QueueNode * next ()
const QueueNode * next () const
Private Member Functions
QueueNode (const E &an_element)
const QueueNode & operator= (const QueueNode &)
QueueNode (const QueueNode &)
QueueNode (const E &an_element)
const QueueNode & operator= (const QueueNode &)
QueueNode (const QueueNode &)
QueueNode (const E &an_element)
const QueueNode & operator= (const QueueNode &)
QueueNode (const QueueNode &)
Private Attributes
E element_
QueueNode * next_
Friends
class Queue< E >
Detailed Description
template<typename E>
class QueueNode< E >
Definition at line 49 of file sample3-inl.h.
Constructor & Destructor Documentation
template<typename E> QueueNode< E >::QueueNode (const E & an_element) inline explicit private
Definition at line 63 of file sample3-inl.h.
Referenced by QueueNode< int >::QueueNode().
 : element_(an_element), next_(NULL) {}
template<typename E> QueueNode< E >::QueueNode (const QueueNode< E > &) private
template<typename E> QueueNode< E >::QueueNode (const E & an_element) inline explicit private
Definition at line 63 of file sample3-inl.h.
 : element_(an_element), next_(NULL) {}
template<typename E> QueueNode< E >::QueueNode (const QueueNode< E > &) private
template<typename E> QueueNode< E >::QueueNode (const E & an_element) inline explicit private
Definition at line 63 of file sample3-inl.h.
 : element_(an_element), next_(NULL) {}
template<typename E> QueueNode< E >::QueueNode (const QueueNode< E > &) private
Member Function Documentation
template<typename E> const E& QueueNode< E >::element () const inline
Definition at line 54 of file sample3-inl.h.
Referenced by Queue< int >::Dequeue(), and Queue< int >::Enqueue().
 { return element_; }
template<typename E> const E& QueueNode< E >::element () const inline
Definition at line 54 of file sample3-inl.h.
 { return element_; }
template<typename E> const E& QueueNode< E >::element () const inline
Definition at line 54 of file sample3-inl.h.
 { return element_; }
template<typename E> QueueNode* QueueNode< E >::next () inline
Definition at line 57 of file sample3-inl.h.
Referenced by Queue< int >::Clear(), and QueueTest::MapTester().
 { return next_; }
template<typename E> QueueNode* QueueNode< E >::next () inline
Definition at line 57 of file sample3-inl.h.
 { return next_; }
template<typename E> QueueNode* QueueNode< E >::next () inline
Definition at line 57 of file sample3-inl.h.
 { return next_; }
template<typename E> const QueueNode* QueueNode< E >::next () const inline
Definition at line 58 of file sample3-inl.h.
 { return next_; }
template<typename E> const QueueNode* QueueNode< E >::next () const inline
Definition at line 58 of file sample3-inl.h.
 { return next_; }
template<typename E> const QueueNode* QueueNode< E >::next () const inline
Definition at line 58 of file sample3-inl.h.
 { return next_; }
template<typename E> const QueueNode& QueueNode< E >::operator= (const QueueNode< E > &) private
template<typename E> const QueueNode& QueueNode< E >::operator= (const QueueNode< E > &) private
Referenced by Queue< int >::Map(), and QueueNode< int >::QueueNode().
template<typename E> const QueueNode& QueueNode< E >::operator= (const QueueNode< E > &) private
Friends And Related Function Documentation
template<typename E> friend class Queue< E > friend
Definition at line 50 of file sample3-inl.h.
Member Data Documentation
template<typename E> E QueueNode< E >::element_ private
Definition at line 69 of file sample3-inl.h.
Referenced by QueueNode< int >::element(), and QueueNode< int >::QueueNode().
template<typename E> QueueNode * QueueNode< E >::next_ private
Definition at line 70 of file sample3-inl.h.
Referenced by Queue< int >::Dequeue(), Queue< int >::Enqueue(), Queue< int >::Map(), QueueNode< int >::next(), and QueueNode< int >::QueueNode().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/samples/sample3-inl.h