proxygen: testing::internal::NotNullMatcher Class Reference
testing::internal::NotNullMatcher Class Reference
#include <gmock-matchers.h>
Public Member Functions
template<typename Pointer >
bool MatchAndExplain (const Pointer &p, MatchResultListener *) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
template<typename Pointer >
bool MatchAndExplain (const Pointer &p, MatchResultListener *) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
template<typename Pointer >
bool MatchAndExplain (const Pointer &p, MatchResultListener *) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
Detailed Description
Definition at line 997 of file gmock-matchers.h.
Member Function Documentation
void testing::internal::NotNullMatcher::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 1010 of file gmock-matchers.h.
{
     *os << "is NULL";
   }
void testing::internal::NotNullMatcher::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 1010 of file gmock-matchers.h.
{
     *os << "is NULL";
   }
void testing::internal::NotNullMatcher::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 1010 of file gmock-matchers.h.
{
     *os << "is NULL";
   }
void testing::internal::NotNullMatcher::DescribeTo (::std::ostream * os) const inline
Definition at line 1009 of file gmock-matchers.h.
 { *os << "isn't NULL"; }
void testing::internal::NotNullMatcher::DescribeTo (::std::ostream * os) const inline
Definition at line 1009 of file gmock-matchers.h.
 { *os << "isn't NULL"; }
void testing::internal::NotNullMatcher::DescribeTo (::std::ostream * os) const inline
Definition at line 1009 of file gmock-matchers.h.
 { *os << "isn't NULL"; }
template<typename Pointer > bool testing::internal::NotNullMatcher::MatchAndExplain (const Pointer & p, MatchResultListener *) const inline
Definition at line 1000 of file gmock-matchers.h.
References testing::internal::GetRawPointer().
{
 #if GTEST_LANG_CXX11
     return p != nullptr;
 #else  // GTEST_LANG_CXX11
     return GetRawPointer(p) != NULL;
 #endif  // GTEST_LANG_CXX11
   }
template<typename Pointer > bool testing::internal::NotNullMatcher::MatchAndExplain (const Pointer & p, MatchResultListener *) const inline
Definition at line 1000 of file gmock-matchers.h.
References testing::internal::GetRawPointer().
{
 #if GTEST_LANG_CXX11
     return p != nullptr;
 #else  // GTEST_LANG_CXX11
     return GetRawPointer(p) != NULL;
 #endif  // GTEST_LANG_CXX11
   }
template<typename Pointer > bool testing::internal::NotNullMatcher::MatchAndExplain (const Pointer & p, MatchResultListener *) const inline
Definition at line 1000 of file gmock-matchers.h.
References testing::internal::GetRawPointer().
{
 #if GTEST_LANG_CXX11
     return p != nullptr;
 #else  // GTEST_LANG_CXX11
     return GetRawPointer(p) != NULL;
 #endif  // GTEST_LANG_CXX11
   }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h