proxygen: ThreadExecutor Class Reference
ThreadExecutor Class Reference
Simple executor that does work in another thread.
Public Member Functions
ThreadExecutor (size_t n=1024)
~ThreadExecutor () override
void add (Func fn) override
void waitForStartup ()
Public Member Functions inherited from folly::Executor
virtual ~Executor ()
virtual void add (Func)=0
virtual void addWithPriority (Func, int8_t priority)
virtual uint8_t getNumPriorities () const
Private Member Functions
void work ()
Private Attributes
folly::MPMCQueue< Func > funcs
std::atomic< bool > done {false}
std::thread worker
folly::Baton baton
Additional Inherited Members
Static Public Member Functions inherited from folly::Executor
template<typename ExecutorT >
static KeepAlive< ExecutorT > getKeepAliveToken (ExecutorT *executor)
template<typename ExecutorT >
static KeepAlive< ExecutorT > getKeepAliveToken (ExecutorT &executor)
Static Public Attributes inherited from folly::Executor
static const int8_t LO_PRI = SCHAR_MIN
static const int8_t MID_PRI = 0
static const int8_t HI_PRI = SCHAR_MAX
Protected Member Functions inherited from folly::Executor
virtual bool keepAliveAcquire ()
virtual void keepAliveRelease ()
Static Protected Member Functions inherited from folly::Executor
template<typename ExecutorT >
static bool isKeepAliveDummy (const KeepAlive< ExecutorT > &keepAlive)
template<typename ExecutorT >
static KeepAlive< ExecutorT > makeKeepAlive (ExecutorT *executor)
Detailed Description
Simple executor that does work in another thread.
Definition at line 314 of file ViaTest.cpp.
Constructor & Destructor Documentation
ThreadExecutor::ThreadExecutor (size_t n = 1024) inline explicit
Definition at line 332 of file ViaTest.cpp.
References folly::netops::bind(), and work().
                                            : funcs(n) {
     worker = std::thread(std::bind(&ThreadExecutor::work, this));
   }
ThreadExecutor::~ThreadExecutor () inline override
Definition at line 336 of file ViaTest.cpp.
{
     done = true;
     funcs.write([] {});
     worker.join();
   }
Member Function Documentation
void ThreadExecutor::add (Func fn) inline override
Definition at line 342 of file ViaTest.cpp.
References folly::gen::move.
Referenced by TEST().
{
     funcs.blockingWrite(std::move(fn));
   }
void ThreadExecutor::waitForStartup () inline
Definition at line 346 of file ViaTest.cpp.
References folly::Baton< MayBlock, Atom >::wait().
Referenced by TEST().
{
     baton.wait();
   }
void ThreadExecutor::work () inline private
Definition at line 320 of file ViaTest.cpp.
References folly::Baton< MayBlock, Atom >::post().
Referenced by ThreadExecutor().
               {
     baton.post();
     Func fn;
     while (!done) {
       while (!funcs.isEmpty()) {
         funcs.blockingRead(fn);
         fn();
       }
     }
   }
Member Data Documentation
folly::Baton ThreadExecutor::baton private
Definition at line 318 of file ViaTest.cpp.
std::atomic<bool> ThreadExecutor::done {false} private
Definition at line 316 of file ViaTest.cpp.
folly::MPMCQueue<Func> ThreadExecutor::funcs private
Definition at line 315 of file ViaTest.cpp.
std::thread ThreadExecutor::worker private
Definition at line 317 of file ViaTest.cpp.
The documentation for this class was generated from the following file:
proxygen/folly/folly/futures/test/ViaTest.cpp