proxygen: testing::internal::EqHelper< lhs_is_null_literal > Class Template Reference
testing::internal::EqHelper< lhs_is_null_literal > Class Template Reference
#include <gtest.h>
Static Public Member Functions
template<typename T1 , typename T2 >
static AssertionResult Compare (const char *lhs_expression, const char *rhs_expression, const T1 &lhs, const T2 &rhs)
static AssertionResult Compare (const char *lhs_expression, const char *rhs_expression, BiggestInt lhs, BiggestInt rhs)
template<typename T1 , typename T2 >
static AssertionResult Compare (const char *lhs_expression, const char *rhs_expression, const T1 &lhs, const T2 &rhs)
static AssertionResult Compare (const char *lhs_expression, const char *rhs_expression, BiggestInt lhs, BiggestInt rhs)
template<typename T1 , typename T2 >
static AssertionResult Compare (const char *lhs_expression, const char *rhs_expression, const T1 &lhs, const T2 &rhs)
static AssertionResult Compare (const char *lhs_expression, const char *rhs_expression, BiggestInt lhs, BiggestInt rhs)
Detailed Description
template<bool lhs_is_null_literal>
class testing::internal::EqHelper< lhs_is_null_literal >
Definition at line 1413 of file gtest.h.
Member Function Documentation
template<bool lhs_is_null_literal> template<typename T1 , typename T2 > static AssertionResult testing::internal::EqHelper< lhs_is_null_literal >::Compare (const char * lhs_expression, const char * rhs_expression, const T1 & lhs, const T2 & rhs) inline static
Definition at line 1417 of file gtest.h.
References testing::internal::CmpHelperEQ().
{
     return CmpHelperEQ(lhs_expression, rhs_expression, lhs, rhs);
   }
template<bool lhs_is_null_literal> template<typename T1 , typename T2 > static AssertionResult testing::internal::EqHelper< lhs_is_null_literal >::Compare (const char * lhs_expression, const char * rhs_expression, const T1 & lhs, const T2 & rhs) inline static
Definition at line 1417 of file gtest.h.
References testing::internal::CmpHelperEQ().
{
     return CmpHelperEQ(lhs_expression, rhs_expression, lhs, rhs);
   }
template<bool lhs_is_null_literal> template<typename T1 , typename T2 > static AssertionResult testing::internal::EqHelper< lhs_is_null_literal >::Compare (const char * lhs_expression, const char * rhs_expression, const T1 & lhs, const T2 & rhs) inline static
Definition at line 1417 of file gtest.h.
References testing::internal::CmpHelperEQ().
{
     return CmpHelperEQ(lhs_expression, rhs_expression, lhs, rhs);
   }
template<bool lhs_is_null_literal> static AssertionResult testing::internal::EqHelper< lhs_is_null_literal >::Compare (const char * lhs_expression, const char * rhs_expression, BiggestInt lhs, BiggestInt rhs) inline static
Definition at line 1430 of file gtest.h.
References testing::internal::CmpHelperEQ().
{
     return CmpHelperEQ(lhs_expression, rhs_expression, lhs, rhs);
   }
template<bool lhs_is_null_literal> static AssertionResult testing::internal::EqHelper< lhs_is_null_literal >::Compare (const char * lhs_expression, const char * rhs_expression, BiggestInt lhs, BiggestInt rhs) inline static
Definition at line 1430 of file gtest.h.
References testing::internal::CmpHelperEQ().
{
     return CmpHelperEQ(lhs_expression, rhs_expression, lhs, rhs);
   }
template<bool lhs_is_null_literal> static AssertionResult testing::internal::EqHelper< lhs_is_null_literal >::Compare (const char * lhs_expression, const char * rhs_expression, BiggestInt lhs, BiggestInt rhs) inline static
Definition at line 1430 of file gtest.h.
References testing::internal::CmpHelperEQ().
{
     return CmpHelperEQ(lhs_expression, rhs_expression, lhs, rhs);
   }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/gtest.h