proxygen: folly::detail::MMapAlloc Class Reference
folly::detail::MMapAlloc Class Reference
#include <AtomicUnorderedMapUtils.h>
Public Member Functions
void * allocate (size_t size)
void deallocate (void *p, size_t size)
Private Member Functions
size_t computeSize (size_t size)
Detailed Description
Definition at line 30 of file AtomicUnorderedMapUtils.h.
Member Function Documentation
void* folly::detail::MMapAlloc::allocate (size_t size) inline
Definition at line 41 of file AtomicUnorderedMapUtils.h.
References computeSize(), and MAP_POPULATE.
{
     auto len = computeSize(size);
     int extraflags = 0;
 #if defined(MAP_POPULATE)
     extraflags |= MAP_POPULATE;
 #endif
     // MAP_HUGETLB is a perf win, but requires cooperation from the
     // deployment environment (and a change to computeSize()).
     void* mem = static_cast<void*>(mmap(
         nullptr,
         len,
         PROT_READ | PROT_WRITE,
         MAP_PRIVATE | MAP_ANONYMOUS | extraflags,
         -1,
         0));
     if (mem == reinterpret_cast<void*>(-1)) {
       throw std::system_error(errno, std::system_category());
     }
 #if !defined(MAP_POPULATE) && defined(MADV_WILLNEED)
     madvise(mem, size, MADV_WILLNEED);
 #endif
     return mem;
   }
size_t folly::detail::MMapAlloc::computeSize (size_t size) inline private
Definition at line 32 of file AtomicUnorderedMapUtils.h.
Referenced by allocate(), and deallocate().
{
     long pagesize = sysconf(_SC_PAGESIZE);
     size_t mmapLength = ((size - 1) & ~(pagesize - 1)) + pagesize;
     assert(size <= mmapLength && mmapLength < size + pagesize);
     assert((mmapLength % pagesize) == 0);
     return mmapLength;
   }
void folly::detail::MMapAlloc::deallocate (void * p, size_t size) inline
Definition at line 67 of file AtomicUnorderedMapUtils.h.
References computeSize().
{
     auto len = computeSize(size);
     munmap(p, len);
   }
The documentation for this class was generated from the following file:
proxygen/folly/folly/detail/AtomicUnorderedMapUtils.h