proxygen: pump.CodeNode Class Reference
pump.CodeNode Class Reference
Public Member Functions
def __init__ (self, atomic_code_list=None)
def __init__ (self, atomic_code_list=None)
def __init__ (self, atomic_code_list=None)
Public Attributes
atomic_code
Detailed Description
Definition at line 390 of file pump.py.
Constructor & Destructor Documentation
def pump.CodeNode.__init__ (self, atomic_code_list = None)
Definition at line 391 of file pump.py.
Referenced by pump.CodeNode.__init__().
   def __init__(self, atomic_code_list=None):
     self.atomic_code = atomic_code_list
def pump.CodeNode.__init__ (self, atomic_code_list = None)
Definition at line 391 of file pump.py.
References pump.CodeNode.__init__(), and pump.CodeNode.atomic_code.
   def __init__(self, atomic_code_list=None):
     self.atomic_code = atomic_code_list
def pump.CodeNode.__init__ (self, atomic_code_list = None)
Definition at line 391 of file pump.py.
References pump.CodeNode.__init__(), and pump.CodeNode.atomic_code.
   def __init__(self, atomic_code_list=None):
     self.atomic_code = atomic_code_list
Member Data Documentation
pump.CodeNode.atomic_code
Definition at line 392 of file pump.py.
Referenced by pump.CodeNode.__init__(), and pump.VarNode.__init__().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/scripts/pump.py