proxygen: folly::test::CaptureFD Class Reference
folly::test::CaptureFD Class Reference
#include <TestUtil.h>
Classes
struct NoOpChunkCob
Public Types
using ChunkCob = std::function< void(folly::StringPiece)>
Public Member Functions
CaptureFD (int fd, ChunkCob chunk_cob=NoOpChunkCob())
~CaptureFD ()
void release ()
std::string read () const
std::string readIncremental ()
Private Attributes
ChunkCob chunkCob_
TemporaryFile file_
int fd_
int oldFDCopy_
off_t readOffset_
Detailed Description
Temporarily capture a file descriptor by redirecting it into a file. You can consume its entire output thus far via read(), incrementally via readIncremental(), or via callback using chunk_cob. Great for testing logging (see also glog*Pattern()).
Definition at line 222 of file TestUtil.h.
Member Typedef Documentation
using folly::test::CaptureFD::ChunkCob = std::function<void(folly::StringPiece)>
Definition at line 229 of file TestUtil.h.
Constructor & Destructor Documentation
folly::test::CaptureFD::CaptureFD (int fd, ChunkCob chunk_cob = NoOpChunkCob()) explicit
chunk_cob is is guaranteed to consume all the captured output. It is invoked on each readIncremental(), and also on FD release to capture as-yet unread lines. Chunks can be empty.
Definition at line 185 of file TestUtil.cpp.
References folly::netops::close(), fd_, file_, oldFDCopy_, and folly::test::TemporaryFile::path().
     : chunkCob_(std::move(chunk_cob)), fd_(fd), readOffset_(0) {
   oldFDCopy_ = dup(fd_);
   PCHECK(oldFDCopy_ != -1) << "Could not copy FD " << fd_;
   int file_fd = open(file_.path().string().c_str(), O_WRONLY | O_CREAT, 0600);
   PCHECK(dup2(file_fd, fd_) != -1)
       << "Could not replace FD " << fd_ << " with " << file_fd;
   PCHECK(close(file_fd) != -1) << "Could not close " << file_fd;
 }
folly::test::CaptureFD::~CaptureFD ()
Definition at line 206 of file TestUtil.cpp.
References release().
                       {
   release();
 }
Member Function Documentation
std::string folly::test::CaptureFD::read () const
Reads the whole file into a string, but does not remove the redirect.
Definition at line 210 of file TestUtil.cpp.
References file_, folly::test::TemporaryFile::path(), folly::readFile(), and string.
{
   std::string contents;
   std::string filename = file_.path().string();
   PCHECK(folly::readFile(filename.c_str(), contents));
   return contents;
 }
std::string folly::test::CaptureFD::readIncremental ()
Read any bytes that were appended to the file since the last readIncremental. Great for testing line-by-line output.
Definition at line 217 of file TestUtil.cpp.
References chunkCob_, f, folly::File::fd(), file_, folly::openNoInt(), folly::test::TemporaryFile::path(), folly::preadFull(), readOffset_, folly::size(), and string.
Referenced by release(), and TEST().
{
   std::string filename = file_.path().string();
   // Yes, I know that I could just keep the file open instead. So sue me.
   folly::File f(openNoInt(filename.c_str(), O_RDONLY), true);
   auto size = size_t(lseek(f.fd(), 0, SEEK_END) - readOffset_);
   std::unique_ptr<char[]> buf(new char[size]);
   auto bytes_read = folly::preadFull(f.fd(), buf.get(), size, readOffset_);
   PCHECK(ssize_t(size) == bytes_read);
   readOffset_ += off_t(size);
   chunkCob_(StringPiece(buf.get(), buf.get() + size));
   return std::string(buf.get(), size);
 }
void folly::test::CaptureFD::release ()
Restore the captured FD to its original state. It can be useful to do this before the destructor so that you can read() the captured data and log about it to the formerly captured stderr or stdout.
Definition at line 196 of file TestUtil.cpp.
References folly::netops::close(), fd_, oldFDCopy_, and readIncremental().
Referenced by ~CaptureFD().
{
   if (oldFDCopy_ != fd_) {
     readIncremental(); // Feed chunkCob_
     PCHECK(dup2(oldFDCopy_, fd_) != -1)
         << "Could not restore old FD " << oldFDCopy_ << " into " << fd_;
     PCHECK(close(oldFDCopy_) != -1) << "Could not close " << oldFDCopy_;
     oldFDCopy_ = fd_; // Make this call idempotent
   }
 }
Member Data Documentation
ChunkCob folly::test::CaptureFD::chunkCob_ private
Definition at line 258 of file TestUtil.h.
Referenced by readIncremental().
int folly::test::CaptureFD::fd_ private
Definition at line 261 of file TestUtil.h.
Referenced by CaptureFD(), and release().
TemporaryFile folly::test::CaptureFD::file_ private
Definition at line 259 of file TestUtil.h.
Referenced by CaptureFD(), read(), and readIncremental().
int folly::test::CaptureFD::oldFDCopy_ private
Definition at line 262 of file TestUtil.h.
Referenced by CaptureFD(), and release().
off_t folly::test::CaptureFD::readOffset_ private
Definition at line 264 of file TestUtil.h.
Referenced by readIncremental().
The documentation for this class was generated from the following files:
proxygen/folly/folly/experimental/TestUtil.h
proxygen/folly/folly/experimental/TestUtil.cpp