proxygen: WaitableMutex Class Reference
WaitableMutex Class Reference
Public Member Functions
void unlock ()
template<typename Wait >
void wait (Wait wfunc)
Private Types
using Lot = ParkingLot< std::function< bool(void)>>
Static Private Attributes
static Lot lot
Detailed Description
Definition at line 73 of file ParkingLotTest.cpp.
Member Typedef Documentation
using WaitableMutex::Lot = ParkingLot<std::function<bool(void)>> private
Definition at line 74 of file ParkingLotTest.cpp.
Member Function Documentation
void WaitableMutex::unlock () inline
Definition at line 78 of file ParkingLotTest.cpp.
References folly::RemoveBreak, folly::RemoveContinue, uint64_t, and folly::ParkingLot< Data >::unpark().
                 {
     bool unparked = false;
     lot.unpark(uint64_t(this), [&](std::function<bool(void)> wfunc) {
       if (wfunc()) {
         unparked = true;
         return UnparkControl::RemoveBreak;
       } else {
         return UnparkControl::RemoveContinue;
       }
     });
     if (!unparked) {
       std::mutex::unlock();
     }
     // Otherwise, we pass mutex directly to waiter without needing to unlock.
   }
template<typename Wait > void WaitableMutex::wait (Wait wfunc) inline
Definition at line 95 of file ParkingLotTest.cpp.
References lot, folly::ParkingLot< Data >::park(), and uint64_t.
Referenced by TEST().
{
     lot.park(
         uint64_t(this),
         wfunc,
         [&]() { return !wfunc(); },
         [&]() { std::mutex::unlock(); });
   }
Member Data Documentation
WaitableMutex::Lot WaitableMutex::lot static private
Definition at line 75 of file ParkingLotTest.cpp.
Referenced by wait().
The documentation for this class was generated from the following file:
proxygen/folly/folly/synchronization/test/ParkingLotTest.cpp