proxygen: testing::gmock_matchers_test::AClass Class Reference
testing::gmock_matchers_test::AClass Class Reference
Public Member Functions
AClass ()
int n () const
void set_n (int new_n)
const string & s () const
void set_s (const string &new_s)
double & x () const
AClass ()
int n () const
void set_n (int new_n)
const string & s () const
void set_s (const string &new_s)
double & x () const
AClass ()
int n () const
void set_n (int new_n)
const string & s () const
void set_s (const string &new_s)
double & x () const
Private Attributes
int n_
string s_
Static Private Attributes
static double x_ = 0.0
Detailed Description
Definition at line 3578 of file gmock-matchers_test.cc.
Constructor & Destructor Documentation
testing::gmock_matchers_test::AClass::AClass () inline
Definition at line 3580 of file gmock-matchers_test.cc.
 : n_(0) {}
testing::gmock_matchers_test::AClass::AClass () inline
Definition at line 3580 of file gmock-matchers_test.cc.
 : n_(0) {}
testing::gmock_matchers_test::AClass::AClass () inline
Definition at line 3580 of file gmock-matchers_test.cc.
 : n_(0) {}
Member Function Documentation
int testing::gmock_matchers_test::AClass::n () const inline
Definition at line 3583 of file gmock-matchers_test.cc.
 { return n_; }
int testing::gmock_matchers_test::AClass::n () const inline
Definition at line 3583 of file gmock-matchers_test.cc.
 { return n_; }
int testing::gmock_matchers_test::AClass::n () const inline
Definition at line 3583 of file gmock-matchers_test.cc.
 { return n_; }
const string& testing::gmock_matchers_test::AClass::s () const inline
Definition at line 3588 of file gmock-matchers_test.cc.
References s_.
 { return s_; }
const string& testing::gmock_matchers_test::AClass::s () const inline
Definition at line 3588 of file gmock-matchers_test.cc.
References s_.
 { return s_; }
const string& testing::gmock_matchers_test::AClass::s () const inline
Definition at line 3588 of file gmock-matchers_test.cc.
References s_.
 { return s_; }
void testing::gmock_matchers_test::AClass::set_n (int new_n) inline
Definition at line 3585 of file gmock-matchers_test.cc.
Referenced by testing::gmock_matchers_test::DerivedClass::k(), and testing::gmock_matchers_test::TEST().
 { n_ = new_n; }
void testing::gmock_matchers_test::AClass::set_n (int new_n) inline
Definition at line 3585 of file gmock-matchers_test.cc.
 { n_ = new_n; }
void testing::gmock_matchers_test::AClass::set_n (int new_n) inline
Definition at line 3585 of file gmock-matchers_test.cc.
 { n_ = new_n; }
void testing::gmock_matchers_test::AClass::set_s (const string & new_s) inline
Definition at line 3590 of file gmock-matchers_test.cc.
References s_.
 { s_ = new_s; }
void testing::gmock_matchers_test::AClass::set_s (const string & new_s) inline
Definition at line 3590 of file gmock-matchers_test.cc.
References s_.
Referenced by testing::gmock_matchers_test::DerivedClass::k(), and testing::gmock_matchers_test::TEST().
 { s_ = new_s; }
void testing::gmock_matchers_test::AClass::set_s (const string & new_s) inline
Definition at line 3590 of file gmock-matchers_test.cc.
References s_.
 { s_ = new_s; }
double& testing::gmock_matchers_test::AClass::x () const inline
Definition at line 3593 of file gmock-matchers_test.cc.
References s_, and x_.
 { return x_; }
double& testing::gmock_matchers_test::AClass::x () const inline
Definition at line 3593 of file gmock-matchers_test.cc.
References s_, and x_.
 { return x_; }
double& testing::gmock_matchers_test::AClass::x () const inline
Definition at line 3593 of file gmock-matchers_test.cc.
References x_.
 { return x_; }
Member Data Documentation
int testing::gmock_matchers_test::AClass::n_ private
Definition at line 3595 of file gmock-matchers_test.cc.
string testing::gmock_matchers_test::AClass::s_ private
Definition at line 3596 of file gmock-matchers_test.cc.
double testing::gmock_matchers_test::AClass::x_ = 0.0 static private
Definition at line 3598 of file gmock-matchers_test.cc.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-matchers_test.cc