proxygen: testing::MatchResultListener Class Reference
testing::MatchResultListener Class Reference abstract
#include <gmock-matchers.h>
Public Member Functions
MatchResultListener (::std::ostream *os)
virtual ~MatchResultListener ()=0
template<typename T >
MatchResultListener & operator<< (const T &x)
::std::ostream * stream ()
bool IsInterested () const
MatchResultListener (::std::ostream *os)
virtual ~MatchResultListener ()=0
template<typename T >
MatchResultListener & operator<< (const T &x)
::std::ostream * stream ()
bool IsInterested () const
MatchResultListener (::std::ostream *os)
virtual ~MatchResultListener ()=0
template<typename T >
MatchResultListener & operator<< (const T &x)
::std::ostream * stream ()
bool IsInterested () const
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (MatchResultListener)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (MatchResultListener)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (MatchResultListener)
Private Attributes
::std::ostream *const stream_
Detailed Description
Definition at line 80 of file gmock-matchers.h.
Constructor & Destructor Documentation
testing::MatchResultListener::MatchResultListener (::std::ostream * os) inline explicit
Definition at line 85 of file gmock-matchers.h.
References ~MatchResultListener().
 : stream_(os) {}
testing::MatchResultListener::~MatchResultListener () inline pure virtual
Definition at line 112 of file gmock-matchers.h.
Referenced by IsInterested(), and MatchResultListener().
{
 }
testing::MatchResultListener::MatchResultListener (::std::ostream * os) inline explicit
Definition at line 85 of file gmock-matchers.h.
References ~MatchResultListener().
 : stream_(os) {}
virtual testing::MatchResultListener::~MatchResultListener () pure virtual
testing::MatchResultListener::MatchResultListener (::std::ostream * os) inline explicit
Definition at line 85 of file gmock-matchers.h.
References ~MatchResultListener().
 : stream_(os) {}
virtual testing::MatchResultListener::~MatchResultListener () pure virtual
Member Function Documentation
testing::MatchResultListener::GTEST_DISALLOW_COPY_AND_ASSIGN_ (MatchResultListener) private
Referenced by testing::StringMatchResultListener::Clear(), testing::internal::DummyMatchResultListener::DummyMatchResultListener(), IsInterested(), testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::MatchAndExplain(), and testing::internal::StreamMatchResultListener::StreamMatchResultListener().
testing::MatchResultListener::GTEST_DISALLOW_COPY_AND_ASSIGN_ (MatchResultListener) private
testing::MatchResultListener::GTEST_DISALLOW_COPY_AND_ASSIGN_ (MatchResultListener) private
bool testing::MatchResultListener::IsInterested () const inline
Definition at line 104 of file gmock-matchers.h.
References stream_.
Referenced by testing::internal::UnorderedElementsAreMatcherImpl< Container >::AnalyzeElements(), testing::internal::FindPairing(), testing::internal::LogElementMatcherPairVec(), testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::MatchAndExplain(), testing::internal::FloatingEqMatcher< FloatType >::Impl< T >::MatchAndExplain(), testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::MatchAndExplain(), testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::MatchAndExplain(), testing::internal::PairMatcherImpl< PairType >::MatchAndExplain(), testing::internal::ElementsAreMatcherImpl< Container >::MatchAndExplain(), testing::internal::UnorderedElementsAreMatcherImpl< Container >::MatchAndExplain(), testing::internal::MatchPrintAndExplain(), and testing::internal::UnorderedElementsAreMatcherImplBase::VerifyAllElementsAndMatchersAreMatched().
 { return stream_ != NULL; }
bool testing::MatchResultListener::IsInterested () const inline
Definition at line 104 of file gmock-matchers.h.
References GTEST_DISALLOW_COPY_AND_ASSIGN_(), stream_, and ~MatchResultListener().
 { return stream_ != NULL; }
bool testing::MatchResultListener::IsInterested () const inline
Definition at line 104 of file gmock-matchers.h.
References GTEST_DISALLOW_COPY_AND_ASSIGN_(), stream_, and ~MatchResultListener().
 { return stream_ != NULL; }
template<typename T > MatchResultListener& testing::MatchResultListener::operator<< (const T & x) inline
Definition at line 91 of file gmock-matchers.h.
References stream_, and x.
{
     if (stream_ != NULL)
       *stream_ << x;
     return *this;
   }
template<typename T > MatchResultListener& testing::MatchResultListener::operator<< (const T & x) inline
Definition at line 91 of file gmock-matchers.h.
References stream_, and x.
{
     if (stream_ != NULL)
       *stream_ << x;
     return *this;
   }
template<typename T > MatchResultListener& testing::MatchResultListener::operator<< (const T & x) inline
Definition at line 91 of file gmock-matchers.h.
References stream_, and x.
{
     if (stream_ != NULL)
       *stream_ << x;
     return *this;
   }
::std::ostream* testing::MatchResultListener::stream () inline
Definition at line 98 of file gmock-matchers.h.
References stream_.
 { return stream_; }
::std::ostream* testing::MatchResultListener::stream () inline
Definition at line 98 of file gmock-matchers.h.
References stream_.
 { return stream_; }
::std::ostream* testing::MatchResultListener::stream () inline
Definition at line 98 of file gmock-matchers.h.
References stream_.
Referenced by testing::internal::FindPairing(), testing::internal::LogElementMatcherPairVec(), testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::MatchAndExplain(), testing::gmock_matchers_test::NewEvenMatcherImpl::MatchAndExplain(), testing::gmock_matchers_test::PolymorphicIsEvenImpl::MatchAndExplain(), testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::MatchAndExplain(), testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::MatchAndExplain(), testing::internal::ContainerEqMatcher< Container >::MatchAndExplain(), testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::MatchAndExplain(), testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::MatchAndExplain(), testing::internal::PairMatcherImpl< PairType >::MatchAndExplain(), testing::internal::ElementsAreMatcherImpl< Container >::MatchAndExplain(), testing::internal::QuantifierMatcherImpl< Container >::MatchAndExplainImpl(), testing::internal::MatchPrintAndExplain(), and testing::internal::UnorderedElementsAreMatcherImplBase::VerifyAllElementsAndMatchersAreMatched().
 { return stream_; }
Member Data Documentation
std::ostream *const testing::MatchResultListener::stream_ private
Definition at line 107 of file gmock-matchers.h.
Referenced by IsInterested(), operator<<(), and stream().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h