proxygen: folly::coro::TaskWithExecutor< T > Class Template Reference
folly::coro::TaskWithExecutor< T > Class Template Reference
#include <Task.h>
Classes
class Awaiter
Public Member Functions
~TaskWithExecutor ()
TaskWithExecutor (TaskWithExecutor &&t) noexcept
TaskWithExecutor & operator= (TaskWithExecutor t) noexcept
folly::Executor * executor () const noexcept
void swap (TaskWithExecutor &t) noexcept
auto start ()&&
Awaiter operator co_await ()&&noexcept
Private Types
using handle_t = std::experimental::coroutine_handle< detail::TaskPromise< T >>
Private Member Functions
TaskWithExecutor (handle_t coro) noexcept
Private Attributes
handle_t coro_
Friends
class Task< T >
Detailed Description
template<typename T>
class folly::coro::TaskWithExecutor< T >
Represents an allocated but not yet started coroutine that has already been bound to an executor.
This task, when co_awaited, will launch the task on the bound executor and will resume the awaiting coroutine on the bound executor when it completes.
Definition at line 41 of file Task.h.
Member Typedef Documentation
template<typename T > using folly::coro::TaskWithExecutor< T >::handle_t = std::experimental::coroutine_handle<detail::TaskPromise<T>> private
Definition at line 165 of file Task.h.
Constructor & Destructor Documentation
template<typename T > folly::coro::TaskWithExecutor< T >::~TaskWithExecutor () inline
Definition at line 168 of file Task.h.
                       {
     if (coro_) {
       coro_.destroy();
     }
   }
template<typename T > folly::coro::TaskWithExecutor< T >::TaskWithExecutor (TaskWithExecutor< T > && t) inline noexcept
Definition at line 174 of file Task.h.
       : coro_(std::exchange(t.coro_, {})) {}
template<typename T > folly::coro::TaskWithExecutor< T >::TaskWithExecutor (handle_t coro) inline explicit private noexcept
Definition at line 239 of file Task.h.
 : coro_(coro) {}
Member Function Documentation
template<typename T > folly::Executor* folly::coro::TaskWithExecutor< T >::executor () const inline noexcept
Definition at line 182 of file Task.h.
{
     return coro_.promise().executor_;
   }
template<typename T > Awaiter folly::coro::TaskWithExecutor< T >::operator co_await () inline noexcept
Definition at line 232 of file Task.h.
References folly::exchange().
{
     return Awaiter{std::exchange(coro_, {})};
   }
template<typename T > TaskWithExecutor& folly::coro::TaskWithExecutor< T >::operator= (TaskWithExecutor< T > t) inline noexcept
Definition at line 177 of file Task.h.
References folly::swap(), and folly::pushmi::detail::t.
{
     swap(t);
     return *this;
   }
template<typename T > auto folly::coro::TaskWithExecutor< T >::start () inline
Definition at line 192 of file Task.h.
References folly::gen::move.
                   {
     return folly::coro::toSemiFuture(std::move(*this));
   }
template<typename T > void folly::coro::TaskWithExecutor< T >::swap (TaskWithExecutor< T > & t) inline noexcept
Definition at line 186 of file Task.h.
References folly::f14::swap(), and folly::pushmi::detail::t.
{
     std::swap(coro_, t.coro_);
   }
Friends And Related Function Documentation
template<typename T > friend class Task< T > friend
Definition at line 237 of file Task.h.
Member Data Documentation
template<typename T > handle_t folly::coro::TaskWithExecutor< T >::coro_ private
Definition at line 241 of file Task.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/coro/Task.h