proxygen: NodeRC< Mutable, Atom > Class Template Reference
NodeRC< Mutable, Atom > Class Template Reference
Public Member Functions
NodeRC (int v=0, NodeRC *n=nullptr, bool acq=false) noexcept
~NodeRC ()
int value () const noexcept
NodeRC< Mutable, Atom > * next () const noexcept
template<typename S >
void push_links (bool m, S &s)
Public Member Functions inherited from folly::hazptr_obj_base_linked< NodeRC< Mutable, Atom >, Atom >
void retire ()
void unlink ()
void unlink_and_reclaim_unchecked ()
Public Member Functions inherited from folly::hazptr_obj_linked< Atom >
void acquire_link () noexcept
void acquire_link_safe () noexcept
void acquire_ref () noexcept
void acquire_ref_safe () noexcept
Public Member Functions inherited from folly::hazptr_obj< Atom >
hazptr_obj () noexcept
hazptr_obj (const hazptr_obj< Atom > &) noexcept
hazptr_obj (hazptr_obj< Atom > &&) noexcept
hazptr_obj< Atom > & operator= (const hazptr_obj< Atom > &) noexcept
hazptr_obj< Atom > & operator= (hazptr_obj< Atom > &&) noexcept
Public Member Functions inherited from folly::hazptr_deleter< NodeRC< Mutable, Atom >, D >
void set_deleter (D d={})
void delete_obj (NodeRC< Mutable, Atom > *p)
Private Attributes
Atom< NodeRC< Mutable, Atom > * > next_
int val_
Detailed Description
template<bool Mutable, template< typename > class Atom = std::atomic>
class NodeRC< Mutable, Atom >
NodeRC
Definition at line 127 of file HazptrTest.cpp.
Constructor & Destructor Documentation
template<bool Mutable, template< typename > class Atom = std::atomic> NodeRC< Mutable, Atom >::NodeRC (int v = 0, NodeRC< Mutable, Atom > * n = nullptr, bool acq = false) inline explicit noexcept
Definition at line 132 of file HazptrTest.cpp.
References Count::inc_ctors(), and folly::gen::Mutable.
       : next_(n), val_(v) {
     this->set_deleter();
     c_.inc_ctors();
     if (acq) {
       if (Mutable) {
         this->acquire_link_safe();
       } else {
         this->acquire_ref_safe();
       }
     }
   }
template<bool Mutable, template< typename > class Atom = std::atomic> NodeRC< Mutable, Atom >::~NodeRC () inline
Definition at line 145 of file HazptrTest.cpp.
References Count::inc_dtors().
             {
     c_.inc_dtors();
   }
Member Function Documentation
template<bool Mutable, template< typename > class Atom = std::atomic> NodeRC<Mutable, Atom>* NodeRC< Mutable, Atom >::next () const inline noexcept
Definition at line 153 of file HazptrTest.cpp.
Referenced by linked_test(), and mt_linked_test().
{
     return next_.load(std::memory_order_acquire);
   }
template<bool Mutable, template< typename > class Atom = std::atomic> template<typename S > void NodeRC< Mutable, Atom >::push_links (bool m, S & s) inline
Definition at line 158 of file HazptrTest.cpp.
References Atom, folly::gen::Mutable, and cpp.ast::next().
{
     if (Mutable == m) {
       auto p = next();
       if (p) {
         s.push(p);
       }
     }
   }
template<bool Mutable, template< typename > class Atom = std::atomic> int NodeRC< Mutable, Atom >::value () const inline noexcept
Definition at line 149 of file HazptrTest.cpp.
{
     return val_;
   }
Member Data Documentation
template<bool Mutable, template< typename > class Atom = std::atomic> Atom<NodeRC<Mutable, Atom>*> NodeRC< Mutable, Atom >::next_ private
Definition at line 128 of file HazptrTest.cpp.
template<bool Mutable, template< typename > class Atom = std::atomic> int NodeRC< Mutable, Atom >::val_ private
Definition at line 129 of file HazptrTest.cpp.
The documentation for this class was generated from the following file:
proxygen/folly/folly/synchronization/test/HazptrTest.cpp