proxygen: folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Skipper Class Reference
folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Skipper Class Reference
#include <ConcurrentSkipList.h>
Public Types
typedef T value_type
typedef T & reference
typedef T * pointer
typedef ptrdiff_t difference_type
Public Member Functions
Skipper (const std::shared_ptr< SkipListType > &skipList)
Skipper (const Accessor &accessor)
void init ()
Skipper & operator++ ()
bool good () const
int maxLayer () const
int curHeight () const
const value_type & data () const
value_type & operator* () const
value_type * operator-> ()
bool to (const value_type &data)
Private Types
typedef detail::SkipListNode< T > NodeType
typedef ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT > SkipListType
typedef SkipListType::Accessor Accessor
Private Member Functions
NodeType * head () const
Private Attributes
Accessor accessor_
int headHeight_
NodeType * succs_ [MAX_HEIGHT]
NodeType * preds_ [MAX_HEIGHT]
uint8_t hints_ [MAX_HEIGHT]
Detailed Description
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24>
class folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Skipper
Definition at line 760 of file ConcurrentSkipList.h.
Member Typedef Documentation
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> typedef SkipListType::Accessor folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Skipper::Accessor private
Definition at line 763 of file ConcurrentSkipList.h.
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> typedef ptrdiff_t folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Skipper::difference_type
Definition at line 769 of file ConcurrentSkipList.h.
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> typedef detail::SkipListNode<T> folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Skipper::NodeType private
Definition at line 761 of file ConcurrentSkipList.h.
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> typedef T* folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Skipper::pointer
Definition at line 768 of file ConcurrentSkipList.h.
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> typedef T& folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Skipper::reference
Definition at line 767 of file ConcurrentSkipList.h.
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> typedef ConcurrentSkipList<T, Comp, NodeAlloc, MAX_HEIGHT> folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Skipper::SkipListType private
Definition at line 762 of file ConcurrentSkipList.h.
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> typedef T folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Skipper::value_type
Definition at line 766 of file ConcurrentSkipList.h.
Constructor & Destructor Documentation
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Skipper::Skipper (const std::shared_ptr< SkipListType > & skipList) inline
Definition at line 771 of file ConcurrentSkipList.h.
References folly::init().
                                                        : accessor_(skipList) {
     init();
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Skipper::Skipper (const Accessor & accessor) inline
Definition at line 775 of file ConcurrentSkipList.h.
References folly::init().
                                     : accessor_(accessor) {
     init();
   }
Member Function Documentation
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> int folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Skipper::curHeight () const inline
Definition at line 814 of file ConcurrentSkipList.h.
References folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::height(), and min.
{
     // need to cap the height to the cached head height, as the current node
     // might be some newly inserted node and also during the time period the
     // head height may have grown.
     return succs_[0] ? std::min(headHeight_, succs_[0]->height()) : 0;
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> const value_type& folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Skipper::data () const inline
Definition at line 821 of file ConcurrentSkipList.h.
{
     DCHECK(succs_[0] != nullptr);
     return succs_[0]->data();
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> bool folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Skipper::good () const inline
Definition at line 806 of file ConcurrentSkipList.h.
                     {
     return succs_[0] != nullptr;
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> NodeType* folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Skipper::head () const inline private
Definition at line 867 of file ConcurrentSkipList.h.
{
     return accessor_.skiplist()->head_.load(std::memory_order_consume);
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> void folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Skipper::init () inline
Definition at line 779 of file ConcurrentSkipList.h.
References folly::detail::SkipListNode< T >::height(), i, folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::maxLayer(), folly::detail::SkipListNode< T >::skip(), and uint8_t.
               {
     // need to cache the head node
     NodeType* head_node = head();
     headHeight_ = head_node->height();
     for (int i = 0; i < headHeight_; ++i) {
       preds_[i] = head_node;
       succs_[i] = head_node->skip(i);
     }
     int max_layer = maxLayer();
     for (int i = 0; i < max_layer; ++i) {
       hints_[i] = uint8_t(i + 1);
     }
     hints_[max_layer] = max_layer;
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> int folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Skipper::maxLayer () const inline
Definition at line 810 of file ConcurrentSkipList.h.
{
     return headHeight_ - 1;
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> value_type& folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Skipper::operator* () const inline
Definition at line 826 of file ConcurrentSkipList.h.
{
     DCHECK(succs_[0] != nullptr);
     return succs_[0]->data();
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> Skipper& folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Skipper::operator++ () inline
Definition at line 795 of file ConcurrentSkipList.h.
References folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::height(), and i.
{
     preds_[0] = succs_[0];
     succs_[0] = preds_[0]->skip(0);
     int height = curHeight();
     for (int i = 1; i < height && preds_[0] == succs_[i]; ++i) {
       preds_[i] = succs_[i];
       succs_[i] = preds_[i]->skip(i);
     }
     return *this;
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> value_type* folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Skipper::operator-> () inline
Definition at line 831 of file ConcurrentSkipList.h.
{
     DCHECK(succs_[0] != nullptr);
     return &succs_[0]->data();
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> bool folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Skipper::to (const value_type & data) inline
Definition at line 842 of file ConcurrentSkipList.h.
References folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::findInsertionPoint(), folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::greater(), and folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::maxLayer().
{
     int layer = curHeight() - 1;
     if (layer < 0) {
       return false; // reaches the end of the list
     }
     int lyr = hints_[layer];
     int max_layer = maxLayer();
     while (SkipListType::greater(data, succs_[lyr]) && lyr < max_layer) {
       ++lyr;
     }
     hints_[layer] = lyr; // update the hint
     int foundLayer = SkipListType::findInsertionPoint(
         preds_[lyr], lyr, data, preds_, succs_);
     if (foundLayer < 0) {
       return false;
     }
     DCHECK(succs_[0] != nullptr)
         << "lyr=" << lyr << "; max_layer=" << max_layer;
     return !succs_[0]->markedForRemoval();
   }
Member Data Documentation
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> Accessor folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Skipper::accessor_ private
Definition at line 871 of file ConcurrentSkipList.h.
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> int folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Skipper::headHeight_ private
Definition at line 872 of file ConcurrentSkipList.h.
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> uint8_t folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Skipper::hints_[MAX_HEIGHT] private
Definition at line 874 of file ConcurrentSkipList.h.
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> NodeType * folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Skipper::preds_[MAX_HEIGHT] private
Definition at line 873 of file ConcurrentSkipList.h.
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> NodeType* folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Skipper::succs_[MAX_HEIGHT] private
Definition at line 873 of file ConcurrentSkipList.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/ConcurrentSkipList.h