proxygen: folly::AsyncSocket::WriteRequest Class Reference
folly::AsyncSocket::WriteRequest Class Reference abstract
#include <AsyncSocket.h>
Public Member Functions
WriteRequest (AsyncSocket *socket, WriteCallback *callback)
virtual void start ()
virtual void destroy ()=0
virtual WriteResult performWrite ()=0
virtual void consume ()=0
virtual bool isComplete ()=0
WriteRequest * getNext () const
WriteCallback * getCallback () const
uint32_t getTotalBytesWritten () const
void append (WriteRequest *next)
void fail (const char *fn, const AsyncSocketException &ex)
void bytesWritten (size_t count)
Protected Member Functions
virtual ~WriteRequest ()
Protected Attributes
AsyncSocket * socket_
parent socket
WriteRequest * next_ {nullptr}
pointer to next WriteRequest
WriteCallback * callback_
completion callback
uint32_t totalBytesWritten_ {0}
total bytes written
Detailed Description
A WriteRequest object tracks information about a pending write operation.
Definition at line 888 of file AsyncSocket.h.
Constructor & Destructor Documentation
folly::AsyncSocket::WriteRequest::WriteRequest (AsyncSocket * socket, WriteCallback * callback) inline
Definition at line 890 of file AsyncSocket.h.
         : socket_(socket), callback_(callback) {}
virtual folly::AsyncSocket::WriteRequest::~WriteRequest () inline protected virtual
Definition at line 931 of file AsyncSocket.h.
 {}
Member Function Documentation
void folly::AsyncSocket::WriteRequest::append (WriteRequest * next) inline
Definition at line 915 of file AsyncSocket.h.
References cpp.ast::next().
Referenced by folly::AsyncSocket::writeImpl(), and folly::AsyncSocket::writeRequest().
{
       assert(next_ == nullptr);
       next_ = next;
     }
void folly::AsyncSocket::WriteRequest::bytesWritten (size_t count) inline
Definition at line 924 of file AsyncSocket.h.
References count, socket_, and uint32_t.
{
       totalBytesWritten_ += uint32_t(count);
       socket_->appBytesWritten_ += count;
     }
virtual void folly::AsyncSocket::WriteRequest::consume () pure virtual
Implemented in folly::AsyncSocket::BytesWriteRequest.
Referenced by folly::AsyncSocket::handleWrite(), and folly::AsyncSocket::writeImpl().
virtual void folly::AsyncSocket::WriteRequest::destroy () pure virtual
Implemented in folly::AsyncSocket::BytesWriteRequest.
Referenced by folly::AsyncSocket::failAllWrites(), folly::AsyncSocket::failWrite(), and folly::AsyncSocket::handleWrite().
void folly::AsyncSocket::WriteRequest::fail (const char * fn, const AsyncSocketException & ex) inline
Definition at line 920 of file AsyncSocket.h.
References socket_.
Referenced by gtest_xml_test_utils.GTestXMLTestCase::_GetChildren(), and fatal_test.FatalTests::is_debug_build().
{
       socket_->failWrite(fn, ex);
     }
WriteCallback* folly::AsyncSocket::WriteRequest::getCallback () const inline
Definition at line 907 of file AsyncSocket.h.
References callback_.
Referenced by folly::AsyncSocket::failAllWrites(), folly::AsyncSocket::failWrite(), and folly::AsyncSocket::handleWrite().
{
       return callback_;
     }
WriteRequest* folly::AsyncSocket::WriteRequest::getNext () const inline
Definition at line 903 of file AsyncSocket.h.
Referenced by folly::AsyncSocket::failAllWrites(), folly::AsyncSocket::failWrite(), folly::AsyncSocket::handleWrite(), and folly::AsyncSocket::BytesWriteRequest::performWrite().
{
       return next_;
     }
uint32_t folly::AsyncSocket::WriteRequest::getTotalBytesWritten () const inline
Definition at line 911 of file AsyncSocket.h.
Referenced by folly::AsyncSocket::failAllWrites(), and folly::AsyncSocket::failWrite().
{
       return totalBytesWritten_;
     }
virtual bool folly::AsyncSocket::WriteRequest::isComplete () pure virtual
Implemented in folly::AsyncSocket::BytesWriteRequest.
Referenced by folly::AsyncSocket::handleWrite().
virtual WriteResult folly::AsyncSocket::WriteRequest::performWrite () pure virtual
Implemented in folly::AsyncSocket::BytesWriteRequest.
Referenced by folly::AsyncSocket::handleWrite().
virtual void folly::AsyncSocket::WriteRequest::start () inline virtual
Definition at line 893 of file AsyncSocket.h.
References folly::AsyncSocket::destroy(), and folly::AsyncSocket::performWrite().
Referenced by folly::AsyncSocket::writeRequest().
 {}
Member Data Documentation
WriteCallback* folly::AsyncSocket::WriteRequest::callback_ protected
completion callback
Definition at line 935 of file AsyncSocket.h.
WriteRequest* folly::AsyncSocket::WriteRequest::next_ {nullptr} protected
pointer to next WriteRequest
Definition at line 934 of file AsyncSocket.h.
AsyncSocket* folly::AsyncSocket::WriteRequest::socket_ protected
parent socket
Definition at line 933 of file AsyncSocket.h.
Referenced by folly::AsyncSocket::BytesWriteRequest::consume(), and folly::AsyncSocket::BytesWriteRequest::performWrite().
uint32_t folly::AsyncSocket::WriteRequest::totalBytesWritten_ {0} protected
total bytes written
Definition at line 936 of file AsyncSocket.h.
Referenced by folly::AsyncSocket::BytesWriteRequest::consume().
The documentation for this class was generated from the following file:
proxygen/folly/folly/io/async/AsyncSocket.h