proxygen: fizz::extensions::TokenBindingClientExtension Class Reference
fizz::extensions::TokenBindingClientExtension Class Reference
#include <TokenBindingClientExtension.h>
Public Member Functions
TokenBindingClientExtension (const std::shared_ptr< TokenBindingContext > &context)
std::vector< Extension > getClientHelloExtensions () const override
void onEncryptedExtensions (const std::vector< Extension > &extensions) override
const auto & getVersion ()
const auto & getNegotiatedKeyParam ()
Public Member Functions inherited from fizz::ClientExtensions
virtual ~ClientExtensions ()=default
Private Attributes
folly::Optional< TokenBindingProtocolVersion > negotiatedVersion_
folly::Optional< TokenBindingKeyParameters > negotiatedKeyParam_
std::shared_ptr< TokenBindingContext > context_
Detailed Description
Definition at line 19 of file TokenBindingClientExtension.h.
Constructor & Destructor Documentation
fizz::extensions::TokenBindingClientExtension::TokenBindingClientExtension (const std::shared_ptr< TokenBindingContext > & context) inline explicit
Definition at line 21 of file TokenBindingClientExtension.h.
References getClientHelloExtensions(), and onEncryptedExtensions().
       : context_(context) {}
Member Function Documentation
std::vector< Extension > fizz::extensions::TokenBindingClientExtension::getClientHelloExtensions () const override virtual
Returns a list of extensions to be added to the ClientHello. Note that this can be called multiple times on a single connection (if a HelloRetryRequest is received).
Implements fizz::ClientExtensions.
Definition at line 14 of file TokenBindingClientExtension.cpp.
References context_, fizz::encodeExtension(), fizz::extensions::TokenBindingParameters::key_parameters_list, and fizz::extensions::TokenBindingParameters::version.
Referenced by TokenBindingClientExtension().
           {
   std::vector<Extension> clientExtensions;
   if (context_->getSupportedVersions().empty() ||
       context_->getKeyParams().empty()) {
     return clientExtensions;
   }
   TokenBindingParameters clientParams;
   clientParams.version = context_->getSupportedVersions().front();
   clientParams.key_parameters_list = context_->getKeyParams();
   clientExtensions.push_back(encodeExtension(clientParams));
   return clientExtensions;
 }
const auto& fizz::extensions::TokenBindingClientExtension::getNegotiatedKeyParam () inline
Definition at line 33 of file TokenBindingClientExtension.h.
References negotiatedKeyParam_.
{
     return negotiatedKeyParam_;
   }
const auto& fizz::extensions::TokenBindingClientExtension::getVersion () inline
Definition at line 29 of file TokenBindingClientExtension.h.
References negotiatedVersion_.
{
     return negotiatedVersion_;
   }
void fizz::extensions::TokenBindingClientExtension::onEncryptedExtensions (const std::vector< Extension > & extensions) override virtual
Called with the extensions present in EncryptedExtensions.
Implements fizz::ClientExtensions.
Definition at line 28 of file TokenBindingClientExtension.cpp.
References context_, negotiatedKeyParam_, negotiatedVersion_, fizz::unsupported_extension, and version.
Referenced by TokenBindingClientExtension().
{
   auto serverParams = getExtension<TokenBindingParameters>(extensions);
   if (!serverParams.hasValue()) {
     VLOG(6) << "Server did not negotiate token binding";
     return;
   }
   if (serverParams->key_parameters_list.size() != 1) {
     throw FizzException(
         "Incorrect number of key_parameters sent by server",
         AlertDescription::unsupported_extension);
   }
   if (serverParams->version > context_->getSupportedVersions().front()) {
     throw FizzException(
         "Server sent higher tokbind version",
         AlertDescription::unsupported_extension);
   }
   auto keyParam = std::find(
       context_->getKeyParams().begin(),
       context_->getKeyParams().end(),
       serverParams->key_parameters_list.front());
   if (keyParam == context_->getKeyParams().end()) {
     throw FizzException(
         "Unsupported key parameter sent by server",
         AlertDescription::unsupported_extension);
   }
   auto version = std::find(
       context_->getSupportedVersions().begin(),
       context_->getSupportedVersions().end(),
       serverParams->version);
   if (version == context_->getSupportedVersions().end()) {
     VLOG(6) << "Server sent lower, unsupported, token binding version";
     return;
   }
   negotiatedVersion_ = *version;
   negotiatedKeyParam_ = *keyParam;
 }
Member Data Documentation
std::shared_ptr<TokenBindingContext> fizz::extensions::TokenBindingClientExtension::context_ private
Definition at line 40 of file TokenBindingClientExtension.h.
Referenced by getClientHelloExtensions(), and onEncryptedExtensions().
folly::Optional<TokenBindingKeyParameters> fizz::extensions::TokenBindingClientExtension::negotiatedKeyParam_ private
Definition at line 39 of file TokenBindingClientExtension.h.
Referenced by getNegotiatedKeyParam(), and onEncryptedExtensions().
folly::Optional<TokenBindingProtocolVersion> fizz::extensions::TokenBindingClientExtension::negotiatedVersion_ private
Definition at line 38 of file TokenBindingClientExtension.h.
Referenced by getVersion(), and onEncryptedExtensions().
The documentation for this class was generated from the following files:
proxygen/fizz/fizz/extensions/tokenbinding/TokenBindingClientExtension.h
proxygen/fizz/fizz/extensions/tokenbinding/TokenBindingClientExtension.cpp