proxygen: wangle::ClientBootstrap< Pipeline >::ConnectCallback Class Reference
wangle::ClientBootstrap< Pipeline >::ConnectCallback Class Reference
Public Member Functions
ConnectCallback (folly::Promise< Pipeline * > promise, ClientBootstrap *bootstrap, std::shared_ptr< folly::AsyncSocket > socket, SSLSessionEstablishedCallbackUniquePtr sslSessionEstablishedCallback)
void connectSuccess () noexceptoverride
void connectErr (const folly::AsyncSocketException &ex) noexceptoverride
Public Member Functions inherited from folly::AsyncSocket::ConnectCallback
virtual ~ConnectCallback ()=default
Private Attributes
folly::Promise< Pipeline * > promise_
ClientBootstrap * bootstrap_
std::shared_ptr< folly::AsyncSocket > socket_
folly::DestructorCheck::Safety safety_
SSLSessionEstablishedCallbackUniquePtr sslSessionEstablishedCallback_
Detailed Description
template<typename Pipeline>
class wangle::ClientBootstrap< Pipeline >::ConnectCallback
Definition at line 37 of file ClientBootstrap.h.
Constructor & Destructor Documentation
template<typename Pipeline> wangle::ClientBootstrap< Pipeline >::ConnectCallback::ConnectCallback (folly::Promise< Pipeline * > promise, ClientBootstrap * bootstrap, std::shared_ptr< folly::AsyncSocket > socket, SSLSessionEstablishedCallbackUniquePtr sslSessionEstablishedCallback) inline
Definition at line 39 of file ClientBootstrap.h.
Referenced by wangle::ClientBootstrap< DefaultPipeline >::connect().
         : promise_(std::move(promise)),
           bootstrap_(bootstrap),
           socket_(socket),
           safety_(*bootstrap),
           sslSessionEstablishedCallback_(
               std::move(sslSessionEstablishedCallback)) {}
Member Function Documentation
template<typename Pipeline> void wangle::ClientBootstrap< Pipeline >::ConnectCallback::connectErr (const folly::AsyncSocketException & ex) inline override virtual noexcept
connectErr() will be invoked if the connection attempt fails.
Parameters
ex An exception describing the error that occurred.
Implements folly::AsyncSocket::ConnectCallback.
Definition at line 71 of file ClientBootstrap.h.
References wangle::ClientBootstrap< Pipeline >::ConnectCallback::promise_.
{
       promise_.setException(
         folly::make_exception_wrapper<folly::AsyncSocketException>(ex));
       delete this;
     }
template<typename Pipeline> void wangle::ClientBootstrap< Pipeline >::ConnectCallback::connectSuccess () inline override virtual noexcept
connectSuccess() will be invoked when the connection has been successfully established.
Implements folly::AsyncSocket::ConnectCallback.
Definition at line 51 of file ClientBootstrap.h.
References wangle::ClientBootstrap< Pipeline >::ConnectCallback::bootstrap_, folly::DestructorCheck::Safety::destroyed(), wangle::BaseClientBootstrap< P >::getPipeline(), folly::AsyncSSLSocket::getSSLSession(), folly::AsyncSSLSocket::getSSLSessionReused(), wangle::BaseClientBootstrap< P >::makePipeline(), folly::gen::move, wangle::ClientBootstrap< Pipeline >::ConnectCallback::promise_, wangle::ClientBootstrap< Pipeline >::ConnectCallback::safety_, wangle::ClientBootstrap< Pipeline >::ConnectCallback::socket_, wangle::ClientBootstrap< Pipeline >::ConnectCallback::sslSessionEstablishedCallback_, and wangle::Pipeline< R, W >::transportActive().
{
       if (!safety_.destroyed()) {
         if (sslSessionEstablishedCallback_) {
           AsyncSSLSocket* sslSocket =
             dynamic_cast<AsyncSSLSocket*>(socket_.get());
           if (sslSocket && !sslSocket->getSSLSessionReused()) {
             sslSessionEstablishedCallback_->onEstablished(
               sslSocket->getSSLSession());
           }
         }
         bootstrap_->makePipeline(std::move(socket_));
         if (bootstrap_->getPipeline()) {
           bootstrap_->getPipeline()->transportActive();
         }
         promise_.setValue(bootstrap_->getPipeline());
       }
       delete this;
     }
Member Data Documentation
template<typename Pipeline> ClientBootstrap* wangle::ClientBootstrap< Pipeline >::ConnectCallback::bootstrap_ private
Definition at line 78 of file ClientBootstrap.h.
Referenced by wangle::ClientBootstrap< Pipeline >::ConnectCallback::connectSuccess().
template<typename Pipeline> folly::Promise<Pipeline*> wangle::ClientBootstrap< Pipeline >::ConnectCallback::promise_ private
Definition at line 77 of file ClientBootstrap.h.
Referenced by wangle::ClientBootstrap< Pipeline >::ConnectCallback::connectErr(), and wangle::ClientBootstrap< Pipeline >::ConnectCallback::connectSuccess().
template<typename Pipeline> folly::DestructorCheck::Safety wangle::ClientBootstrap< Pipeline >::ConnectCallback::safety_ private
Definition at line 80 of file ClientBootstrap.h.
Referenced by wangle::ClientBootstrap< Pipeline >::ConnectCallback::connectSuccess().
template<typename Pipeline> std::shared_ptr<folly::AsyncSocket> wangle::ClientBootstrap< Pipeline >::ConnectCallback::socket_ private
Definition at line 79 of file ClientBootstrap.h.
Referenced by wangle::ClientBootstrap< Pipeline >::ConnectCallback::connectSuccess().
template<typename Pipeline> SSLSessionEstablishedCallbackUniquePtr wangle::ClientBootstrap< Pipeline >::ConnectCallback::sslSessionEstablishedCallback_ private
Definition at line 81 of file ClientBootstrap.h.
Referenced by wangle::ClientBootstrap< DefaultPipeline >::connect(), and wangle::ClientBootstrap< Pipeline >::ConnectCallback::connectSuccess().
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/bootstrap/ClientBootstrap.h