proxygen: testing::internal::UnorderedElementsAreMatcherImplBase Class Reference
testing::internal::UnorderedElementsAreMatcherImplBase Class Reference
#include <gmock-matchers.h>
Protected Types
typedef ::std::vector< const MatcherDescriberInterface * > MatcherDescriberVec
typedef ::std::vector< const MatcherDescriberInterface * > MatcherDescriberVec
typedef ::std::vector< const MatcherDescriberInterface * > MatcherDescriberVec
Protected Member Functions
void DescribeToImpl (::std::ostream *os) const
void DescribeNegationToImpl (::std::ostream *os) const
bool VerifyAllElementsAndMatchersAreMatched (const ::std::vector< string > &element_printouts, const MatchMatrix &matrix, MatchResultListener *listener) const
MatcherDescriberVec & matcher_describers ()
void DescribeToImpl (::std::ostream *os) const
void DescribeNegationToImpl (::std::ostream *os) const
bool VerifyAllElementsAndMatchersAreMatched (const ::std::vector< string > &element_printouts, const MatchMatrix &matrix, MatchResultListener *listener) const
MatcherDescriberVec & matcher_describers ()
void DescribeToImpl (::std::ostream *os) const
void DescribeNegationToImpl (::std::ostream *os) const
bool VerifyAllElementsAndMatchersAreMatched (const ::std::vector< string > &element_printouts, const MatchMatrix &matrix, MatchResultListener *listener) const
MatcherDescriberVec & matcher_describers ()
Static Protected Member Functions
static Message Elements (size_t n)
static Message Elements (size_t n)
static Message Elements (size_t n)
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (UnorderedElementsAreMatcherImplBase)
GTEST_DISALLOW_ASSIGN_ (UnorderedElementsAreMatcherImplBase)
GTEST_DISALLOW_ASSIGN_ (UnorderedElementsAreMatcherImplBase)
Private Attributes
MatcherDescriberVec matcher_describers_
Detailed Description
Definition at line 3311 of file gmock-matchers.h.
Member Typedef Documentation
typedef ::std::vector<const MatcherDescriberInterface*> testing::internal::UnorderedElementsAreMatcherImplBase::MatcherDescriberVec protected
Definition at line 3316 of file gmock-matchers.h.
typedef ::std::vector<const MatcherDescriberInterface*> testing::internal::UnorderedElementsAreMatcherImplBase::MatcherDescriberVec protected
Definition at line 3316 of file gmock-matchers.h.
typedef ::std::vector<const MatcherDescriberInterface*> testing::internal::UnorderedElementsAreMatcherImplBase::MatcherDescriberVec protected
Definition at line 3316 of file gmock-matchers.h.
Member Function Documentation
void testing::internal::UnorderedElementsAreMatcherImplBase::DescribeNegationToImpl (::std::ostream * os) const protected
Definition at line 416 of file gmock-matchers.cc.
References i.
{
   if (matcher_describers_.empty()) {
     *os << "isn't empty";
     return;
   }
   if (matcher_describers_.size() == 1) {
     *os << "doesn't have " << Elements(1)
         << ", or has " << Elements(1) << " that ";
     matcher_describers_[0]->DescribeNegationTo(os);
     return;
   }
   *os << "doesn't have " << Elements(matcher_describers_.size())
       << ", or there exists no permutation of elements such that:\n";
   const char* sep = "";
   for (size_t i = 0; i != matcher_describers_.size(); ++i) {
     *os << sep << " - element #" << i << " ";
     matcher_describers_[i]->DescribeTo(os);
     sep = ", and\n";
   }
 }
void testing::internal::UnorderedElementsAreMatcherImplBase::DescribeNegationToImpl (::std::ostream * os) const protected
void testing::internal::UnorderedElementsAreMatcherImplBase::DescribeNegationToImpl (::std::ostream * os) const protected
void testing::internal::UnorderedElementsAreMatcherImplBase::DescribeToImpl (::std::ostream * os) const protected
Definition at line 395 of file gmock-matchers.cc.
References i.
{
   if (matcher_describers_.empty()) {
     *os << "is empty";
     return;
   }
   if (matcher_describers_.size() == 1) {
     *os << "has " << Elements(1) << " and that element ";
     matcher_describers_[0]->DescribeTo(os);
     return;
   }
   *os << "has " << Elements(matcher_describers_.size())
       << " and there exists some permutation of elements such that:\n";
   const char* sep = "";
   for (size_t i = 0; i != matcher_describers_.size(); ++i) {
     *os << sep << " - element #" << i << " ";
     matcher_describers_[i]->DescribeTo(os);
     sep = ", and\n";
   }
 }
void testing::internal::UnorderedElementsAreMatcherImplBase::DescribeToImpl (::std::ostream * os) const protected
void testing::internal::UnorderedElementsAreMatcherImplBase::DescribeToImpl (::std::ostream * os) const protected
static Message testing::internal::UnorderedElementsAreMatcherImplBase::Elements (size_t n) inline static protected
Definition at line 3333 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, and GTEST_REMOVE_REFERENCE_AND_CONST_.
{
     return Message() << n << " element" << (n == 1 ? "" : "s");
   }
static Message testing::internal::UnorderedElementsAreMatcherImplBase::Elements (size_t n) inline static protected
Definition at line 3333 of file gmock-matchers.h.
{
     return Message() << n << " element" << (n == 1 ? "" : "s");
   }
static Message testing::internal::UnorderedElementsAreMatcherImplBase::Elements (size_t n) inline static protected
Definition at line 3333 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, and GTEST_REMOVE_REFERENCE_AND_CONST_.
{
     return Message() << n << " element" << (n == 1 ? "" : "s");
   }
testing::internal::UnorderedElementsAreMatcherImplBase::GTEST_DISALLOW_ASSIGN_ (UnorderedElementsAreMatcherImplBase) private
testing::internal::UnorderedElementsAreMatcherImplBase::GTEST_DISALLOW_ASSIGN_ (UnorderedElementsAreMatcherImplBase) private
testing::internal::UnorderedElementsAreMatcherImplBase::GTEST_DISALLOW_ASSIGN_ (UnorderedElementsAreMatcherImplBase) private
MatcherDescriberVec& testing::internal::UnorderedElementsAreMatcherImplBase::matcher_describers () inline protected
Definition at line 3329 of file gmock-matchers.h.
{
     return matcher_describers_;
   }
MatcherDescriberVec& testing::internal::UnorderedElementsAreMatcherImplBase::matcher_describers () inline protected
Definition at line 3329 of file gmock-matchers.h.
{
     return matcher_describers_;
   }
MatcherDescriberVec& testing::internal::UnorderedElementsAreMatcherImplBase::matcher_describers () inline protected
Definition at line 3329 of file gmock-matchers.h.
{
     return matcher_describers_;
   }
bool testing::internal::UnorderedElementsAreMatcherImplBase::VerifyAllElementsAndMatchersAreMatched (const ::std::vector< string > & element_printouts, const MatchMatrix & matrix, MatchResultListener * listener) const protected
Definition at line 444 of file gmock-matchers.cc.
References testing::internal::MatchMatrix::HasEdge(), testing::MatchResultListener::IsInterested(), testing::internal::MatchMatrix::LhsSize(), testing::internal::MatchMatrix::RhsSize(), and testing::MatchResultListener::stream().
{
   bool result = true;
   ::std::vector<char> element_matched(matrix.LhsSize(), 0);
   ::std::vector<char> matcher_matched(matrix.RhsSize(), 0);
   for (size_t ilhs = 0; ilhs < matrix.LhsSize(); ilhs++) {
     for (size_t irhs = 0; irhs < matrix.RhsSize(); irhs++) {
       char matched = matrix.HasEdge(ilhs, irhs);
       element_matched[ilhs] |= matched;
       matcher_matched[irhs] |= matched;
     }
   }
   {
     const char* sep =
         "where the following matchers don't match any elements:\n";
     for (size_t mi = 0; mi < matcher_matched.size(); ++mi) {
       if (matcher_matched[mi])
         continue;
       result = false;
       if (listener->IsInterested()) {
         *listener << sep << "matcher #" << mi << ": ";
         matcher_describers_[mi]->DescribeTo(listener->stream());
         sep = ",\n";
       }
     }
   }
   {
     const char* sep =
         "where the following elements don't match any matchers:\n";
     const char* outer_sep = "";
     if (!result) {
       outer_sep = "\nand ";
     }
     for (size_t ei = 0; ei < element_matched.size(); ++ei) {
       if (element_matched[ei])
         continue;
       result = false;
       if (listener->IsInterested()) {
         *listener << outer_sep << sep << "element #" << ei << ": "
                   << element_printouts[ei];
         sep = ",\n";
         outer_sep = "";
       }
     }
   }
   return result;
 }
bool testing::internal::UnorderedElementsAreMatcherImplBase::VerifyAllElementsAndMatchersAreMatched (const ::std::vector< string > & element_printouts, const MatchMatrix & matrix, MatchResultListener * listener) const protected
bool testing::internal::UnorderedElementsAreMatcherImplBase::VerifyAllElementsAndMatchersAreMatched (const ::std::vector< string > & element_printouts, const MatchMatrix & matrix, MatchResultListener * listener) const protected
Member Data Documentation
MatcherDescriberVec testing::internal::UnorderedElementsAreMatcherImplBase::matcher_describers_ private
Definition at line 3338 of file gmock-matchers.h.
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h
proxygen/fizz/build_/gtest/src/gtest/googlemock/src/gmock-matchers.cc