proxygen: folly::TDigest::Centroid Class Reference
folly::TDigest::Centroid Class Reference
#include <TDigest.h>
Public Member Functions
Centroid (double mean=0.0, double weight=1.0)
double mean () const
double weight () const
double add (double sum, double weight)
bool operator< (const Centroid &other) const
Private Attributes
double mean_
double weight_
Detailed Description
Definition at line 52 of file TDigest.h.
Constructor & Destructor Documentation
folly::TDigest::Centroid::Centroid (double mean = 0.0, double weight = 1.0) inline explicit
Definition at line 54 of file TDigest.h.
References weight().
         : mean_(mean), weight_(weight) {
       DCHECK_GT(weight, 0);
     }
Member Function Documentation
double folly::TDigest::Centroid::add (double sum, double weight) inline
Definition at line 369 of file TDigest.cpp.
References folly::TDigest::sum().
Referenced by folly::TDigest::merge(), and weight().
{
   sum += (mean_ * weight_);
   weight_ += weight;
   mean_ = sum / weight_;
   return sum;
 }
double folly::TDigest::Centroid::mean () const inline
Definition at line 59 of file TDigest.h.
References mean_.
Referenced by folly::TDigest::merge(), and operator<().
{
       return mean_;
     }
bool folly::TDigest::Centroid::operator< (const Centroid & other) const inline
Definition at line 72 of file TDigest.h.
References mean().
{
       return mean() < other.mean();
     }
double folly::TDigest::Centroid::weight () const inline
Definition at line 63 of file TDigest.h.
References add(), folly::TDigest::sum(), and weight_.
Referenced by Centroid(), and folly::TDigest::merge().
{
       return weight_;
     }
Member Data Documentation
double folly::TDigest::Centroid::mean_ private
Definition at line 77 of file TDigest.h.
Referenced by mean().
double folly::TDigest::Centroid::weight_ private
Definition at line 78 of file TDigest.h.
Referenced by weight().
The documentation for this class was generated from the following files:
proxygen/folly/folly/stats/TDigest.h
proxygen/folly/folly/stats/TDigest.cpp