proxygen: wangle::AsyncUDPServerSocketFactory::ThreadSafeDestructor Class Reference
wangle::AsyncUDPServerSocketFactory::ThreadSafeDestructor Class Reference
#include <ServerSocketFactory.h>
Public Member Functions
void operator() (folly::AsyncUDPServerSocket *socket) const
Detailed Description
Definition at line 127 of file ServerSocketFactory.h.
Member Function Documentation
void wangle::AsyncUDPServerSocketFactory::ThreadSafeDestructor::operator() (folly::AsyncUDPServerSocket * socket) const inline
Definition at line 129 of file ServerSocketFactory.h.
References folly::AsyncUDPServerSocket::getEventBase(), folly::EventBase::runImmediatelyOrRunInEventBaseThreadAndWait(), and folly::netops::socket().
{
       socket->getEventBase()->runImmediatelyOrRunInEventBaseThreadAndWait(
         [socket]() {
           delete socket;
         }
       );
     }
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/bootstrap/ServerSocketFactory.h