proxygen: folly::coro::detail::BlockingWaitPromise< void > Class Template Reference
folly::coro::detail::BlockingWaitPromise< void > Class Template Reference final
#include <BlockingWait.h>
Public Member Functions
BlockingWaitPromise ()=default
BlockingWaitTask< void > get_return_object () noexcept
void return_void () noexcept
void unhandled_exception () noexcept
folly::Try< void > getAsTry ()
void get ()
Public Member Functions inherited from folly::coro::detail::BlockingWaitPromiseBase
BlockingWaitPromiseBase () noexcept=default
std::experimental::suspend_always initial_suspend ()
FinalAwaiter final_suspend () noexcept
Private Attributes
folly::Try< void > * result_
Additional Inherited Members
Protected Member Functions inherited from folly::coro::detail::BlockingWaitPromiseBase
void wait () noexcept
Detailed Description
template<>
class folly::coro::detail::BlockingWaitPromise< void >
Definition at line 168 of file BlockingWait.h.
Constructor & Destructor Documentation
folly::coro::detail::BlockingWaitPromise< void >::BlockingWaitPromise () default
Member Function Documentation
void folly::coro::detail::BlockingWaitPromise< void >::get () inline
Definition at line 191 of file BlockingWait.h.
References folly::Try< void >::value().
              {
     return getAsTry().value();
   }
BlockingWaitTask< void > folly::coro::detail::BlockingWaitPromise< void >::get_return_object () inline noexcept
Definition at line 246 of file BlockingWait.h.
{
   return BlockingWaitTask<void>{std::experimental::coroutine_handle<
       BlockingWaitPromise<void>>::from_promise(*this)};
 }
folly::Try<void> folly::coro::detail::BlockingWaitPromise< void >::getAsTry () inline
Definition at line 181 of file BlockingWait.h.
References folly::coro::detail::BlockingWaitPromiseBase::wait().
{
     folly::Try<void> result;
     result_ = &result;
     std::experimental::coroutine_handle<
         BlockingWaitPromise<void>>::from_promise(*this)
         .resume();
     this->wait();
     return result;
   }
void folly::coro::detail::BlockingWaitPromise< void >::return_void () inline noexcept
Definition at line 174 of file BlockingWait.h.
 {}
void folly::coro::detail::BlockingWaitPromise< void >::unhandled_exception () inline noexcept
Definition at line 176 of file BlockingWait.h.
References folly::exception_wrapper::from_exception_ptr().
{
     result_->emplaceException(
         exception_wrapper::from_exception_ptr(std::current_exception()));
   }
Member Data Documentation
folly::Try<void>* folly::coro::detail::BlockingWaitPromise< void >::result_ private
Definition at line 196 of file BlockingWait.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/coro/BlockingWait.h