proxygen: testing::gmock_matchers_test::NotCopyable Class Reference
testing::gmock_matchers_test::NotCopyable Class Reference
Public Member Functions
NotCopyable (int a_value)
int value () const
bool operator== (const NotCopyable &rhs) const
bool operator>= (const NotCopyable &rhs) const
NotCopyable (int a_value)
int value () const
bool operator== (const NotCopyable &rhs) const
bool operator>= (const NotCopyable &rhs) const
NotCopyable (int a_value)
int value () const
bool operator== (const NotCopyable &rhs) const
bool operator>= (const NotCopyable &rhs) const
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (NotCopyable)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (NotCopyable)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (NotCopyable)
Private Attributes
int value_
Detailed Description
Definition at line 4036 of file gmock-matchers_test.cc.
Constructor & Destructor Documentation
testing::gmock_matchers_test::NotCopyable::NotCopyable (int a_value) inline explicit
Definition at line 4038 of file gmock-matchers_test.cc.
 : value_(a_value) {}
testing::gmock_matchers_test::NotCopyable::NotCopyable (int a_value) inline explicit
Definition at line 4038 of file gmock-matchers_test.cc.
 : value_(a_value) {}
testing::gmock_matchers_test::NotCopyable::NotCopyable (int a_value) inline explicit
Definition at line 4038 of file gmock-matchers_test.cc.
 : value_(a_value) {}
Member Function Documentation
testing::gmock_matchers_test::NotCopyable::GTEST_DISALLOW_COPY_AND_ASSIGN_ (NotCopyable) private
testing::gmock_matchers_test::NotCopyable::GTEST_DISALLOW_COPY_AND_ASSIGN_ (NotCopyable) private
testing::gmock_matchers_test::NotCopyable::GTEST_DISALLOW_COPY_AND_ASSIGN_ (NotCopyable) private
bool testing::gmock_matchers_test::NotCopyable::operator== (const NotCopyable & rhs) const inline
Definition at line 4042 of file gmock-matchers_test.cc.
References value, and value().
{
     return value() == rhs.value();
   }
bool testing::gmock_matchers_test::NotCopyable::operator== (const NotCopyable & rhs) const inline
Definition at line 4042 of file gmock-matchers_test.cc.
References value, and value().
{
     return value() == rhs.value();
   }
bool testing::gmock_matchers_test::NotCopyable::operator== (const NotCopyable & rhs) const inline
Definition at line 4042 of file gmock-matchers_test.cc.
References value, and value().
{
     return value() == rhs.value();
   }
bool testing::gmock_matchers_test::NotCopyable::operator>= (const NotCopyable & rhs) const inline
Definition at line 4046 of file gmock-matchers_test.cc.
References testing::AnyOf(), testing::ByRef(), c, testing::ContainerEq(), testing::gmock_matchers_test::Describe(), testing::gmock_matchers_test::DescribeNegation(), testing::ElementsAre(), testing::ElementsAreArray(), testing::Eq(), EXPECT_EQ, EXPECT_FALSE, EXPECT_THAT, EXPECT_TRUE, testing::gmock_matchers_test::Explain(), testing::Ge(), testing::gmock_matchers_test::GreaterThan(), GTEST_DISALLOW_COPY_AND_ASSIGN_, testing::Lt(), std::tr1::make_tuple(), testing::internal::MatcherBase< T >::Matches(), testing::Not(), testing::Pair(), testing::SizeIs(), string, testing::internal::TEST(), testing::TYPED_TEST(), testing::TYPED_TEST_CASE(), value, value(), testing::WhenSorted(), and testing::WhenSortedBy().
{
     return value() >= rhs.value();
   }
bool testing::gmock_matchers_test::NotCopyable::operator>= (const NotCopyable & rhs) const inline
Definition at line 4046 of file gmock-matchers_test.cc.
References value, and value().
{
     return value() >= rhs.value();
   }
bool testing::gmock_matchers_test::NotCopyable::operator>= (const NotCopyable & rhs) const inline
Definition at line 4046 of file gmock-matchers_test.cc.
References testing::AnyOf(), testing::ByRef(), c, testing::ContainerEq(), testing::gmock_matchers_test::Describe(), testing::gmock_matchers_test::DescribeNegation(), testing::ElementsAre(), testing::ElementsAreArray(), testing::Eq(), EXPECT_EQ, EXPECT_FALSE, EXPECT_THAT, EXPECT_TRUE, testing::gmock_matchers_test::Explain(), testing::Ge(), testing::gmock_matchers_test::GreaterThan(), GTEST_DISALLOW_COPY_AND_ASSIGN_, testing::Lt(), std::tr1::make_tuple(), testing::internal::MatcherBase< T >::Matches(), testing::Not(), testing::Pair(), testing::SizeIs(), string, testing::internal::TEST(), testing::TYPED_TEST(), testing::TYPED_TEST_CASE(), value, value(), testing::WhenSorted(), and testing::WhenSortedBy().
{
     return value() >= rhs.value();
   }
int testing::gmock_matchers_test::NotCopyable::value () const inline
Definition at line 4040 of file gmock-matchers_test.cc.
 { return value_; }
int testing::gmock_matchers_test::NotCopyable::value () const inline
Definition at line 4040 of file gmock-matchers_test.cc.
 { return value_; }
int testing::gmock_matchers_test::NotCopyable::value () const inline
Definition at line 4040 of file gmock-matchers_test.cc.
Referenced by operator==(), and operator>=().
 { return value_; }
Member Data Documentation
int testing::gmock_matchers_test::NotCopyable::value_ private
Definition at line 4050 of file gmock-matchers_test.cc.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-matchers_test.cc