proxygen: TimeoutTest Class Reference
TimeoutTest Class Reference
Public Member Functions
void SetUp () override
void loop ()
void setClock (milliseconds ms)
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Protected Attributes
MockTimeoutManager timeoutManager_
MockTimeoutClock timeoutClock_
boost::container::flat_multimap< milliseconds, AsyncTimeout * > timeouts_
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Protected Member Functions inherited from testing::Test
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Detailed Description
Definition at line 87 of file AsyncTimeoutSetTest.cpp.
Member Function Documentation
void TimeoutTest::loop () inline
Definition at line 117 of file AsyncTimeoutSetTest.cpp.
References folly::pushmi::detail::t.
               {
     for (auto t = timeoutClock_.millisecondsSinceEpoch() + milliseconds(1);
          !timeouts_.empty(); t++) {
       setClock(t);
     }
   }
void TimeoutTest::setClock (milliseconds ms) inline
Definition at line 124 of file AsyncTimeoutSetTest.cpp.
References folly::event_ref_flags(), EXPECT_CALL, folly::AsyncTimeout::getEvent(), proxygen::millisecondsSinceEpoch(), testing::Return(), and folly::AsyncTimeout::timeoutExpired().
{
     EXPECT_CALL(timeoutClock_, millisecondsSinceEpoch())
       .WillRepeatedly(Return(ms));
     while (!timeouts_.empty() &&
            timeoutClock_.millisecondsSinceEpoch() >= timeouts_.begin()->first) {
       AsyncTimeout* timeout = timeouts_.begin()->second;
       timeouts_.erase(timeouts_.begin());
       folly::event_ref_flags(timeout->getEvent()) &= ~EVLIST_TIMEOUT;
       timeout->timeoutExpired();
     }
   }
void TimeoutTest::SetUp () inline override virtual
Reimplemented from testing::Test.
Definition at line 90 of file AsyncTimeoutSetTest.cpp.
References testing::_, folly::event_ref_flags(), EXPECT_CALL, folly::AsyncTimeout::getEvent(), testing::Invoke(), testing::Return(), TestTimeout::setTimeoutClock(), and folly::pushmi::detail::t.
{
     TestTimeout::setTimeoutClock(timeoutClock_);
     setClock(milliseconds(0));
     EXPECT_CALL(timeoutManager_, attachTimeoutManager(_, _))
       .WillRepeatedly(Return());
     EXPECT_CALL(timeoutManager_, scheduleTimeout(_, _))
       .WillRepeatedly(Invoke([this] (AsyncTimeout* p, milliseconds t) {
             timeoutManager_.cancelTimeout(p);
             folly::event_ref_flags(p->getEvent()) |= EVLIST_TIMEOUT;
             timeouts_.emplace(t + timeoutClock_.millisecondsSinceEpoch(),
                              p);
             return true;
           }));
     EXPECT_CALL(timeoutManager_, cancelTimeout(_))
       .WillRepeatedly(Invoke([this] (AsyncTimeout* p) {
             for (auto it = timeouts_.begin(); it != timeouts_.end(); it++) {
               if (it->second == p) {
                 timeouts_.erase(it);
                 break;
               }
             }
           }));
   }
Member Data Documentation
MockTimeoutClock TimeoutTest::timeoutClock_ protected
Definition at line 139 of file AsyncTimeoutSetTest.cpp.
MockTimeoutManager TimeoutTest::timeoutManager_ protected
Definition at line 138 of file AsyncTimeoutSetTest.cpp.
boost::container::flat_multimap<milliseconds, AsyncTimeout*> TimeoutTest::timeouts_ protected
Definition at line 140 of file AsyncTimeoutSetTest.cpp.
The documentation for this class was generated from the following file:
proxygen/lib/utils/test/AsyncTimeoutSetTest.cpp