proxygen: PrimeTable Class Reference
PrimeTable Class Reference abstract
#include <prime_tables.h>
Public Member Functions
virtual ~PrimeTable ()
virtual bool IsPrime (int n) const =0
virtual int GetNextPrime (int p) const =0
virtual ~PrimeTable ()
virtual bool IsPrime (int n) const =0
virtual int GetNextPrime (int p) const =0
virtual ~PrimeTable ()
virtual bool IsPrime (int n) const =0
virtual int GetNextPrime (int p) const =0
Detailed Description
Definition at line 43 of file prime_tables.h.
Constructor & Destructor Documentation
virtual PrimeTable::~PrimeTable () inline virtual
Definition at line 45 of file prime_tables.h.
References GetNextPrime(), and IsPrime().
 {}
virtual PrimeTable::~PrimeTable () inline virtual
Definition at line 45 of file prime_tables.h.
References GetNextPrime(), and IsPrime().
 {}
virtual PrimeTable::~PrimeTable () inline virtual
Definition at line 45 of file prime_tables.h.
References GetNextPrime(), and IsPrime().
 {}
Member Function Documentation
virtual int PrimeTable::GetNextPrime (int p) const pure virtual
Implemented in PreCalculatedPrimeTable, PreCalculatedPrimeTable, PreCalculatedPrimeTable, OnTheFlyPrimeTable, OnTheFlyPrimeTable, and OnTheFlyPrimeTable.
Referenced by ~PrimeTable(), and PrimeTableTest< T >::~PrimeTableTest().
virtual int PrimeTable::GetNextPrime (int p) const pure virtual
Implemented in PreCalculatedPrimeTable, PreCalculatedPrimeTable, PreCalculatedPrimeTable, OnTheFlyPrimeTable, OnTheFlyPrimeTable, and OnTheFlyPrimeTable.
virtual int PrimeTable::GetNextPrime (int p) const pure virtual
Implemented in PreCalculatedPrimeTable, PreCalculatedPrimeTable, PreCalculatedPrimeTable, OnTheFlyPrimeTable, OnTheFlyPrimeTable, and OnTheFlyPrimeTable.
virtual bool PrimeTable::IsPrime (int n) const pure virtual
Implemented in PreCalculatedPrimeTable, PreCalculatedPrimeTable, PreCalculatedPrimeTable, OnTheFlyPrimeTable, OnTheFlyPrimeTable, and OnTheFlyPrimeTable.
Referenced by OnTheFlyPrimeTable::GetNextPrime(), ~PrimeTable(), and PrimeTableTest< T >::~PrimeTableTest().
virtual bool PrimeTable::IsPrime (int n) const pure virtual
Implemented in PreCalculatedPrimeTable, PreCalculatedPrimeTable, PreCalculatedPrimeTable, OnTheFlyPrimeTable, OnTheFlyPrimeTable, and OnTheFlyPrimeTable.
virtual bool PrimeTable::IsPrime (int n) const pure virtual
Implemented in PreCalculatedPrimeTable, PreCalculatedPrimeTable, PreCalculatedPrimeTable, OnTheFlyPrimeTable, OnTheFlyPrimeTable, and OnTheFlyPrimeTable.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/samples/prime_tables.h