proxygen: wangle::AsyncServerSocketFactory::ThreadSafeDestructor Class Reference
wangle::AsyncServerSocketFactory::ThreadSafeDestructor Class Reference
#include <ServerSocketFactory.h>
Public Member Functions
void operator() (folly::AsyncServerSocket *socket) const
Detailed Description
Definition at line 83 of file ServerSocketFactory.h.
Member Function Documentation
void wangle::AsyncServerSocketFactory::ThreadSafeDestructor::operator() (folly::AsyncServerSocket * socket) const inline
Definition at line 85 of file ServerSocketFactory.h.
References folly::AsyncServerSocket::destroy(), folly::AsyncServerSocket::getEventBase(), and folly::EventBase::runImmediatelyOrRunInEventBaseThreadAndWait().
{
       folly::EventBase* evb = socket->getEventBase();
       if (evb) {
         evb->runImmediatelyOrRunInEventBaseThreadAndWait([socket]() {
           socket->destroy();
         });
       } else {
         socket->destroy();
       }
     }
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/bootstrap/ServerSocketFactory.h