proxygen: testing::internal::FinalSuccessChecker Class Reference
testing::internal::FinalSuccessChecker Class Reference
Protected Member Functions
virtual void TearDown ()
virtual void TearDown ()
virtual void TearDown ()
Additional Inherited Members
Public Member Functions inherited from testing::Environment
virtual ~Environment ()
virtual void SetUp ()
virtual ~Environment ()
virtual void SetUp ()
virtual ~Environment ()
virtual void SetUp ()
Detailed Description
Definition at line 234 of file gtest-unittest-api_test.cc.
Member Function Documentation
virtual void testing::internal::FinalSuccessChecker::TearDown () inline protected virtual
Reimplemented from testing::Environment.
Definition at line 236 of file gtest-unittest-api_test.cc.
References ASSERT_EQ, EXPECT_EQ, EXPECT_FALSE, EXPECT_STREQ, EXPECT_TRUE, testing::UnitTest::Failed(), testing::UnitTest::failed_test_case_count(), testing::UnitTest::failed_test_count(), testing::internal::UnitTestHelper::FindTestCase(), testing::UnitTest::GetInstance(), testing::internal::UnitTestHelper::GetSortedTestCases(), testing::internal::UnitTestHelper::GetSortedTests(), testing::TestResult::GetTestProperty(), testing::internal::IsNull(), name, testing::UnitTest::Passed(), testing::TestInfo::result(), testing::UnitTest::successful_test_case_count(), testing::UnitTest::successful_test_count(), and testing::UnitTest::total_test_case_count().
{
     UnitTest* unit_test = UnitTest::GetInstance();
     EXPECT_EQ(1 + kTypedTestCases, unit_test->successful_test_case_count());
     EXPECT_EQ(3 + kTypedTests, unit_test->successful_test_count());
     EXPECT_EQ(0, unit_test->failed_test_case_count());
     EXPECT_EQ(0, unit_test->failed_test_count());
     EXPECT_TRUE(unit_test->Passed());
     EXPECT_FALSE(unit_test->Failed());
     ASSERT_EQ(2 + kTypedTestCases, unit_test->total_test_case_count());
     const TestCase** const test_cases = UnitTestHelper::GetSortedTestCases();
     EXPECT_STREQ("ApiTest", test_cases[0]->name());
     EXPECT_TRUE(IsNull(test_cases[0]->type_param()));
     EXPECT_TRUE(test_cases[0]->should_run());
     EXPECT_EQ(1, test_cases[0]->disabled_test_count());
     ASSERT_EQ(4, test_cases[0]->total_test_count());
     EXPECT_EQ(3, test_cases[0]->successful_test_count());
     EXPECT_EQ(0, test_cases[0]->failed_test_count());
     EXPECT_TRUE(test_cases[0]->Passed());
     EXPECT_FALSE(test_cases[0]->Failed());
     EXPECT_STREQ("DISABLED_Test", test_cases[1]->name());
     EXPECT_TRUE(IsNull(test_cases[1]->type_param()));
     EXPECT_FALSE(test_cases[1]->should_run());
     EXPECT_EQ(1, test_cases[1]->disabled_test_count());
     ASSERT_EQ(1, test_cases[1]->total_test_count());
     EXPECT_EQ(0, test_cases[1]->successful_test_count());
     EXPECT_EQ(0, test_cases[1]->failed_test_count());
 #if GTEST_HAS_TYPED_TEST
     EXPECT_STREQ("TestCaseWithCommentTest/0", test_cases[2]->name());
     EXPECT_STREQ(GetTypeName<int>().c_str(), test_cases[2]->type_param());
     EXPECT_TRUE(test_cases[2]->should_run());
     EXPECT_EQ(0, test_cases[2]->disabled_test_count());
     ASSERT_EQ(1, test_cases[2]->total_test_count());
     EXPECT_EQ(1, test_cases[2]->successful_test_count());
     EXPECT_EQ(0, test_cases[2]->failed_test_count());
     EXPECT_TRUE(test_cases[2]->Passed());
     EXPECT_FALSE(test_cases[2]->Failed());
 #endif  // GTEST_HAS_TYPED_TEST
     const TestCase* test_case = UnitTestHelper::FindTestCase("ApiTest");
     const TestInfo** tests = UnitTestHelper::GetSortedTests(test_case);
     EXPECT_STREQ("DISABLED_Dummy1", tests[0]->name());
     EXPECT_STREQ("ApiTest", tests[0]->test_case_name());
     EXPECT_FALSE(tests[0]->should_run());
     EXPECT_STREQ("TestCaseDisabledAccessorsWork", tests[1]->name());
     EXPECT_STREQ("ApiTest", tests[1]->test_case_name());
     EXPECT_TRUE(IsNull(tests[1]->value_param()));
     EXPECT_TRUE(IsNull(tests[1]->type_param()));
     EXPECT_TRUE(tests[1]->should_run());
     EXPECT_TRUE(tests[1]->result()->Passed());
     EXPECT_EQ(0, tests[1]->result()->test_property_count());
     EXPECT_STREQ("TestCaseImmutableAccessorsWork", tests[2]->name());
     EXPECT_STREQ("ApiTest", tests[2]->test_case_name());
     EXPECT_TRUE(IsNull(tests[2]->value_param()));
     EXPECT_TRUE(IsNull(tests[2]->type_param()));
     EXPECT_TRUE(tests[2]->should_run());
     EXPECT_TRUE(tests[2]->result()->Passed());
     EXPECT_EQ(0, tests[2]->result()->test_property_count());
     EXPECT_STREQ("UnitTestImmutableAccessorsWork", tests[3]->name());
     EXPECT_STREQ("ApiTest", tests[3]->test_case_name());
     EXPECT_TRUE(IsNull(tests[3]->value_param()));
     EXPECT_TRUE(IsNull(tests[3]->type_param()));
     EXPECT_TRUE(tests[3]->should_run());
     EXPECT_TRUE(tests[3]->result()->Passed());
     EXPECT_EQ(1, tests[3]->result()->test_property_count());
     const TestProperty& property = tests[3]->result()->GetTestProperty(0);
     EXPECT_STREQ("key", property.key());
     EXPECT_STREQ("value", property.value());
     delete[] tests;
 #if GTEST_HAS_TYPED_TEST
     test_case = UnitTestHelper::FindTestCase("TestCaseWithCommentTest/0");
     tests = UnitTestHelper::GetSortedTests(test_case);
     EXPECT_STREQ("Dummy", tests[0]->name());
     EXPECT_STREQ("TestCaseWithCommentTest/0", tests[0]->test_case_name());
     EXPECT_TRUE(IsNull(tests[0]->value_param()));
     EXPECT_STREQ(GetTypeName<int>().c_str(), tests[0]->type_param());
     EXPECT_TRUE(tests[0]->should_run());
     EXPECT_TRUE(tests[0]->result()->Passed());
     EXPECT_EQ(0, tests[0]->result()->test_property_count());
     delete[] tests;
 #endif  // GTEST_HAS_TYPED_TEST
     delete[] test_cases;
   }
virtual void testing::internal::FinalSuccessChecker::TearDown () inline protected virtual
Reimplemented from testing::Environment.
Definition at line 236 of file gtest-unittest-api_test.cc.
References ASSERT_EQ, EXPECT_EQ, EXPECT_FALSE, EXPECT_STREQ, EXPECT_TRUE, testing::UnitTest::Failed(), testing::UnitTest::failed_test_case_count(), testing::UnitTest::failed_test_count(), testing::internal::UnitTestHelper::FindTestCase(), testing::UnitTest::GetInstance(), testing::internal::UnitTestHelper::GetSortedTestCases(), testing::internal::UnitTestHelper::GetSortedTests(), testing::TestResult::GetTestProperty(), testing::internal::IsNull(), name, testing::UnitTest::Passed(), testing::TestInfo::result(), testing::UnitTest::successful_test_case_count(), testing::UnitTest::successful_test_count(), and testing::UnitTest::total_test_case_count().
{
     UnitTest* unit_test = UnitTest::GetInstance();
     EXPECT_EQ(1 + kTypedTestCases, unit_test->successful_test_case_count());
     EXPECT_EQ(3 + kTypedTests, unit_test->successful_test_count());
     EXPECT_EQ(0, unit_test->failed_test_case_count());
     EXPECT_EQ(0, unit_test->failed_test_count());
     EXPECT_TRUE(unit_test->Passed());
     EXPECT_FALSE(unit_test->Failed());
     ASSERT_EQ(2 + kTypedTestCases, unit_test->total_test_case_count());
     const TestCase** const test_cases = UnitTestHelper::GetSortedTestCases();
     EXPECT_STREQ("ApiTest", test_cases[0]->name());
     EXPECT_TRUE(IsNull(test_cases[0]->type_param()));
     EXPECT_TRUE(test_cases[0]->should_run());
     EXPECT_EQ(1, test_cases[0]->disabled_test_count());
     ASSERT_EQ(4, test_cases[0]->total_test_count());
     EXPECT_EQ(3, test_cases[0]->successful_test_count());
     EXPECT_EQ(0, test_cases[0]->failed_test_count());
     EXPECT_TRUE(test_cases[0]->Passed());
     EXPECT_FALSE(test_cases[0]->Failed());
     EXPECT_STREQ("DISABLED_Test", test_cases[1]->name());
     EXPECT_TRUE(IsNull(test_cases[1]->type_param()));
     EXPECT_FALSE(test_cases[1]->should_run());
     EXPECT_EQ(1, test_cases[1]->disabled_test_count());
     ASSERT_EQ(1, test_cases[1]->total_test_count());
     EXPECT_EQ(0, test_cases[1]->successful_test_count());
     EXPECT_EQ(0, test_cases[1]->failed_test_count());
 #if GTEST_HAS_TYPED_TEST
     EXPECT_STREQ("TestCaseWithCommentTest/0", test_cases[2]->name());
     EXPECT_STREQ(GetTypeName<int>().c_str(), test_cases[2]->type_param());
     EXPECT_TRUE(test_cases[2]->should_run());
     EXPECT_EQ(0, test_cases[2]->disabled_test_count());
     ASSERT_EQ(1, test_cases[2]->total_test_count());
     EXPECT_EQ(1, test_cases[2]->successful_test_count());
     EXPECT_EQ(0, test_cases[2]->failed_test_count());
     EXPECT_TRUE(test_cases[2]->Passed());
     EXPECT_FALSE(test_cases[2]->Failed());
 #endif  // GTEST_HAS_TYPED_TEST
     const TestCase* test_case = UnitTestHelper::FindTestCase("ApiTest");
     const TestInfo** tests = UnitTestHelper::GetSortedTests(test_case);
     EXPECT_STREQ("DISABLED_Dummy1", tests[0]->name());
     EXPECT_STREQ("ApiTest", tests[0]->test_case_name());
     EXPECT_FALSE(tests[0]->should_run());
     EXPECT_STREQ("TestCaseDisabledAccessorsWork", tests[1]->name());
     EXPECT_STREQ("ApiTest", tests[1]->test_case_name());
     EXPECT_TRUE(IsNull(tests[1]->value_param()));
     EXPECT_TRUE(IsNull(tests[1]->type_param()));
     EXPECT_TRUE(tests[1]->should_run());
     EXPECT_TRUE(tests[1]->result()->Passed());
     EXPECT_EQ(0, tests[1]->result()->test_property_count());
     EXPECT_STREQ("TestCaseImmutableAccessorsWork", tests[2]->name());
     EXPECT_STREQ("ApiTest", tests[2]->test_case_name());
     EXPECT_TRUE(IsNull(tests[2]->value_param()));
     EXPECT_TRUE(IsNull(tests[2]->type_param()));
     EXPECT_TRUE(tests[2]->should_run());
     EXPECT_TRUE(tests[2]->result()->Passed());
     EXPECT_EQ(0, tests[2]->result()->test_property_count());
     EXPECT_STREQ("UnitTestImmutableAccessorsWork", tests[3]->name());
     EXPECT_STREQ("ApiTest", tests[3]->test_case_name());
     EXPECT_TRUE(IsNull(tests[3]->value_param()));
     EXPECT_TRUE(IsNull(tests[3]->type_param()));
     EXPECT_TRUE(tests[3]->should_run());
     EXPECT_TRUE(tests[3]->result()->Passed());
     EXPECT_EQ(1, tests[3]->result()->test_property_count());
     const TestProperty& property = tests[3]->result()->GetTestProperty(0);
     EXPECT_STREQ("key", property.key());
     EXPECT_STREQ("value", property.value());
     delete[] tests;
 #if GTEST_HAS_TYPED_TEST
     test_case = UnitTestHelper::FindTestCase("TestCaseWithCommentTest/0");
     tests = UnitTestHelper::GetSortedTests(test_case);
     EXPECT_STREQ("Dummy", tests[0]->name());
     EXPECT_STREQ("TestCaseWithCommentTest/0", tests[0]->test_case_name());
     EXPECT_TRUE(IsNull(tests[0]->value_param()));
     EXPECT_STREQ(GetTypeName<int>().c_str(), tests[0]->type_param());
     EXPECT_TRUE(tests[0]->should_run());
     EXPECT_TRUE(tests[0]->result()->Passed());
     EXPECT_EQ(0, tests[0]->result()->test_property_count());
     delete[] tests;
 #endif  // GTEST_HAS_TYPED_TEST
     delete[] test_cases;
   }
virtual void testing::internal::FinalSuccessChecker::TearDown () inline protected virtual
Reimplemented from testing::Environment.
Definition at line 236 of file gtest-unittest-api_test.cc.
References ASSERT_EQ, EXPECT_EQ, EXPECT_FALSE, EXPECT_STREQ, EXPECT_TRUE, testing::UnitTest::Failed(), testing::UnitTest::failed_test_case_count(), testing::UnitTest::failed_test_count(), testing::internal::UnitTestHelper::FindTestCase(), testing::UnitTest::GetInstance(), testing::internal::UnitTestHelper::GetSortedTestCases(), testing::internal::UnitTestHelper::GetSortedTests(), testing::TestResult::GetTestProperty(), testing::internal::IsNull(), name, testing::UnitTest::Passed(), testing::TestInfo::result(), testing::UnitTest::successful_test_case_count(), testing::UnitTest::successful_test_count(), and testing::UnitTest::total_test_case_count().
{
     UnitTest* unit_test = UnitTest::GetInstance();
     EXPECT_EQ(1 + kTypedTestCases, unit_test->successful_test_case_count());
     EXPECT_EQ(3 + kTypedTests, unit_test->successful_test_count());
     EXPECT_EQ(0, unit_test->failed_test_case_count());
     EXPECT_EQ(0, unit_test->failed_test_count());
     EXPECT_TRUE(unit_test->Passed());
     EXPECT_FALSE(unit_test->Failed());
     ASSERT_EQ(2 + kTypedTestCases, unit_test->total_test_case_count());
     const TestCase** const test_cases = UnitTestHelper::GetSortedTestCases();
     EXPECT_STREQ("ApiTest", test_cases[0]->name());
     EXPECT_TRUE(IsNull(test_cases[0]->type_param()));
     EXPECT_TRUE(test_cases[0]->should_run());
     EXPECT_EQ(1, test_cases[0]->disabled_test_count());
     ASSERT_EQ(4, test_cases[0]->total_test_count());
     EXPECT_EQ(3, test_cases[0]->successful_test_count());
     EXPECT_EQ(0, test_cases[0]->failed_test_count());
     EXPECT_TRUE(test_cases[0]->Passed());
     EXPECT_FALSE(test_cases[0]->Failed());
     EXPECT_STREQ("DISABLED_Test", test_cases[1]->name());
     EXPECT_TRUE(IsNull(test_cases[1]->type_param()));
     EXPECT_FALSE(test_cases[1]->should_run());
     EXPECT_EQ(1, test_cases[1]->disabled_test_count());
     ASSERT_EQ(1, test_cases[1]->total_test_count());
     EXPECT_EQ(0, test_cases[1]->successful_test_count());
     EXPECT_EQ(0, test_cases[1]->failed_test_count());
 #if GTEST_HAS_TYPED_TEST
     EXPECT_STREQ("TestCaseWithCommentTest/0", test_cases[2]->name());
     EXPECT_STREQ(GetTypeName<int>().c_str(), test_cases[2]->type_param());
     EXPECT_TRUE(test_cases[2]->should_run());
     EXPECT_EQ(0, test_cases[2]->disabled_test_count());
     ASSERT_EQ(1, test_cases[2]->total_test_count());
     EXPECT_EQ(1, test_cases[2]->successful_test_count());
     EXPECT_EQ(0, test_cases[2]->failed_test_count());
     EXPECT_TRUE(test_cases[2]->Passed());
     EXPECT_FALSE(test_cases[2]->Failed());
 #endif  // GTEST_HAS_TYPED_TEST
     const TestCase* test_case = UnitTestHelper::FindTestCase("ApiTest");
     const TestInfo** tests = UnitTestHelper::GetSortedTests(test_case);
     EXPECT_STREQ("DISABLED_Dummy1", tests[0]->name());
     EXPECT_STREQ("ApiTest", tests[0]->test_case_name());
     EXPECT_FALSE(tests[0]->should_run());
     EXPECT_STREQ("TestCaseDisabledAccessorsWork", tests[1]->name());
     EXPECT_STREQ("ApiTest", tests[1]->test_case_name());
     EXPECT_TRUE(IsNull(tests[1]->value_param()));
     EXPECT_TRUE(IsNull(tests[1]->type_param()));
     EXPECT_TRUE(tests[1]->should_run());
     EXPECT_TRUE(tests[1]->result()->Passed());
     EXPECT_EQ(0, tests[1]->result()->test_property_count());
     EXPECT_STREQ("TestCaseImmutableAccessorsWork", tests[2]->name());
     EXPECT_STREQ("ApiTest", tests[2]->test_case_name());
     EXPECT_TRUE(IsNull(tests[2]->value_param()));
     EXPECT_TRUE(IsNull(tests[2]->type_param()));
     EXPECT_TRUE(tests[2]->should_run());
     EXPECT_TRUE(tests[2]->result()->Passed());
     EXPECT_EQ(0, tests[2]->result()->test_property_count());
     EXPECT_STREQ("UnitTestImmutableAccessorsWork", tests[3]->name());
     EXPECT_STREQ("ApiTest", tests[3]->test_case_name());
     EXPECT_TRUE(IsNull(tests[3]->value_param()));
     EXPECT_TRUE(IsNull(tests[3]->type_param()));
     EXPECT_TRUE(tests[3]->should_run());
     EXPECT_TRUE(tests[3]->result()->Passed());
     EXPECT_EQ(1, tests[3]->result()->test_property_count());
     const TestProperty& property = tests[3]->result()->GetTestProperty(0);
     EXPECT_STREQ("key", property.key());
     EXPECT_STREQ("value", property.value());
     delete[] tests;
 #if GTEST_HAS_TYPED_TEST
     test_case = UnitTestHelper::FindTestCase("TestCaseWithCommentTest/0");
     tests = UnitTestHelper::GetSortedTests(test_case);
     EXPECT_STREQ("Dummy", tests[0]->name());
     EXPECT_STREQ("TestCaseWithCommentTest/0", tests[0]->test_case_name());
     EXPECT_TRUE(IsNull(tests[0]->value_param()));
     EXPECT_STREQ(GetTypeName<int>().c_str(), tests[0]->type_param());
     EXPECT_TRUE(tests[0]->should_run());
     EXPECT_TRUE(tests[0]->result()->Passed());
     EXPECT_EQ(0, tests[0]->result()->test_property_count());
     delete[] tests;
 #endif  // GTEST_HAS_TYPED_TEST
     delete[] test_cases;
   }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest-unittest-api_test.cc