proxygen: testing::DefaultValue< T & > Class Template Reference
testing::DefaultValue< T & > Class Template Reference
#include <gmock-actions.h>
Static Public Member Functions
static void Set (T &x)
static void Clear ()
static bool IsSet ()
static bool Exists ()
static T & Get ()
static void Set (T &x)
static void Clear ()
static bool IsSet ()
static bool Exists ()
static T & Get ()
static void Set (T &x)
static void Clear ()
static bool IsSet ()
static bool Exists ()
static T & Get ()
Static Private Attributes
static T * address_ = NULL
Detailed Description
template<typename T>
class testing::DefaultValue< T & >
Definition at line 275 of file gmock-actions.h.
Member Function Documentation
template<typename T > static void testing::DefaultValue< T & >::Clear () inline static
Definition at line 283 of file gmock-actions.h.
                       {
     address_ = NULL;
   }
template<typename T > static void testing::DefaultValue< T & >::Clear () inline static
Definition at line 283 of file gmock-actions.h.
                       {
     address_ = NULL;
   }
template<typename T > static void testing::DefaultValue< T & >::Clear () inline static
Definition at line 283 of file gmock-actions.h.
                       {
     address_ = NULL;
   }
template<typename T > static bool testing::DefaultValue< T & >::Exists () inline static
Definition at line 292 of file gmock-actions.h.
References testing::internal::BuiltInDefaultValue< T >::Exists().
{
     return IsSet() || internal::BuiltInDefaultValue<T&>::Exists();
   }
template<typename T > static bool testing::DefaultValue< T & >::Exists () inline static
Definition at line 292 of file gmock-actions.h.
References testing::internal::BuiltInDefaultValue< T >::Exists().
{
     return IsSet() || internal::BuiltInDefaultValue<T&>::Exists();
   }
template<typename T > static bool testing::DefaultValue< T & >::Exists () inline static
Definition at line 292 of file gmock-actions.h.
References testing::internal::BuiltInDefaultValue< T >::Exists().
{
     return IsSet() || internal::BuiltInDefaultValue<T&>::Exists();
   }
template<typename T > static T& testing::DefaultValue< T & >::Get () inline static
Definition at line 299 of file gmock-actions.h.
References testing::internal::BuiltInDefaultValue< T >::Get().
                   {
     return address_ == NULL ?
         internal::BuiltInDefaultValue<T&>::Get() : *address_;
   }
template<typename T > static T& testing::DefaultValue< T & >::Get () inline static
Definition at line 299 of file gmock-actions.h.
References testing::internal::BuiltInDefaultValue< T >::Get().
                   {
     return address_ == NULL ?
         internal::BuiltInDefaultValue<T&>::Get() : *address_;
   }
template<typename T > static T& testing::DefaultValue< T & >::Get () inline static
Definition at line 299 of file gmock-actions.h.
References testing::internal::BuiltInDefaultValue< T >::Get().
                   {
     return address_ == NULL ?
         internal::BuiltInDefaultValue<T&>::Get() : *address_;
   }
template<typename T > static bool testing::DefaultValue< T & >::IsSet () inline static
Definition at line 288 of file gmock-actions.h.
 { return address_ != NULL; }
template<typename T > static bool testing::DefaultValue< T & >::IsSet () inline static
Definition at line 288 of file gmock-actions.h.
 { return address_ != NULL; }
template<typename T > static bool testing::DefaultValue< T & >::IsSet () inline static
Definition at line 288 of file gmock-actions.h.
 { return address_ != NULL; }
template<typename T > static void testing::DefaultValue< T & >::Set (T & x) inline static
Definition at line 278 of file gmock-actions.h.
References x.
                         {  // NOLINT
     address_ = &x;
   }
template<typename T > static void testing::DefaultValue< T & >::Set (T & x) inline static
Definition at line 278 of file gmock-actions.h.
References x.
                         {  // NOLINT
     address_ = &x;
   }
template<typename T > static void testing::DefaultValue< T & >::Set (T & x) inline static
Definition at line 278 of file gmock-actions.h.
References x.
                         {  // NOLINT
     address_ = &x;
   }
Member Data Documentation
template<typename T > T * testing::DefaultValue< T & >::address_ = NULL static private
Definition at line 305 of file gmock-actions.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-actions.h