proxygen: folly::StreamHandlerFactory::WriterFactory Class Reference
folly::StreamHandlerFactory::WriterFactory Class Reference
Public Member Functions
bool processOption (StringPiece name, StringPiece value) override
std::shared_ptr< LogWriter > createWriter () override
Public Member Functions inherited from folly::StandardLogHandlerFactory::OptionProcessor
virtual ~OptionProcessor ()
Public Attributes
std::string stream_
FileWriterFactory fileWriterFactory_
Detailed Description
Definition at line 25 of file StreamHandlerFactory.cpp.
Member Function Documentation
std::shared_ptr<LogWriter> folly::StreamHandlerFactory::WriterFactory::createWriter () inline override virtual
Implements folly::StandardLogHandlerFactory::WriterFactory.
Definition at line 36 of file StreamHandlerFactory.cpp.
References folly::FileWriterFactory::createWriter(), fileWriterFactory_, folly::gen::move, and stream_.
{
     // Get the output file to use
     File outputFile;
     if (stream_.empty()) {
       throw std::invalid_argument(
           "no stream name specified for stream handler");
     } else if (stream_ == "stderr") {
       outputFile = File{STDERR_FILENO, /* ownsFd */ false};
     } else if (stream_ == "stdout") {
       outputFile = File{STDOUT_FILENO, /* ownsFd */ false};
     } else {
       throw std::invalid_argument(to<std::string>(
           "unknown stream \"",
           stream_,
           "\": expected one of stdout or stderr"));
     }
     return fileWriterFactory_.createWriter(std::move(outputFile));
   }
bool folly::StreamHandlerFactory::WriterFactory::processOption (StringPiece name, StringPiece value) inline override virtual
Process an option.
This should return true if the option was processed successfully, or false if this is an unknown option name. It should throw an exception if the option name is known but there is a problem with the value.
Implements folly::StandardLogHandlerFactory::OptionProcessor.
Definition at line 28 of file StreamHandlerFactory.cpp.
References fileWriterFactory_, folly::FileWriterFactory::processOption(), folly::Range< Iter >::str(), and stream_.
{
     if (name == "stream") {
       stream_ = value.str();
       return true;
     }
     return fileWriterFactory_.processOption(name, value);
   }
Member Data Documentation
FileWriterFactory folly::StreamHandlerFactory::WriterFactory::fileWriterFactory_
Definition at line 57 of file StreamHandlerFactory.cpp.
Referenced by createWriter(), and processOption().
std::string folly::StreamHandlerFactory::WriterFactory::stream_
Definition at line 56 of file StreamHandlerFactory.cpp.
Referenced by createWriter(), and processOption().
The documentation for this class was generated from the following file:
proxygen/folly/folly/logging/StreamHandlerFactory.cpp