proxygen: ZlibServerFilterTest Class Reference
ZlibServerFilterTest Class Reference
Public Member Functions
void SetUp () override
void TearDown () override
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Protected Member Functions
void exercise_compression (bool expectCompression, std::string url, std::string acceptedEncoding, std::string expectedEncoding, std::string originalRequestBody, std::string responseContentType, std::unique_ptr< folly::IOBuf > originalResponseBody, int32_t compressionLevel=4, uint32_t minimumCompressionSize=1)
std::unique_ptr< folly::IOBuf > createResponseChain (std::vector< std::string > const &bodyStrings)
Protected Member Functions inherited from testing::Test
Test ()
Test ()
Test ()
Protected Attributes
ZlibServerFilter * filter_ {nullptr}
MockRequestHandler * requestHandler_
std::unique_ptr< MockResponseHandler > responseHandler_
std::unique_ptr< ZlibStreamDecompressor > zd_
ResponseHandler * downstream_ {nullptr}
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Detailed Description
Definition at line 35 of file ZlibServerFilterTest.cpp.
Member Function Documentation
std::unique_ptr<folly::IOBuf> ZlibServerFilterTest::createResponseChain (std::vector< std::string > const & bodyStrings) inline protected
Definition at line 193 of file ZlibServerFilterTest.cpp.
References folly::IOBuf::copyBuffer(), folly::gen::move, folly::IOBuf::prependChain(), and s.
{
     std::unique_ptr<folly::IOBuf> responseBodyChain;
     for (auto& s : bodyStrings) {
       auto nextBody = folly::IOBuf::copyBuffer(s.c_str());
       if (responseBodyChain) {
         responseBodyChain->prependChain(std::move(nextBody));
       } else {
         responseBodyChain = std::move(nextBody);
       }
     }
     return responseBodyChain;
   }
void ZlibServerFilterTest::exercise_compression (bool expectCompression, std::string url, std::string acceptedEncoding, std::string expectedEncoding, std::string originalRequestBody, std::string responseContentType, std::unique_ptr< folly::IOBuf > originalResponseBody, int32_t compressionLevel = 4, uint32_t minimumCompressionSize = 1) inline protected
Definition at line 58 of file ZlibServerFilterTest.cpp.
References testing::_, ASSERT_FALSE, proxygen::ResponseBuilder::body(), proxygen::HTTPMessage::checkForHeaderToken(), folly::IOBuf::clone(), folly::IOBuf::cloneOne(), folly::IOBuf::copyBuffer(), folly::IOBuf::countChainElements(), proxygen::ZlibStreamDecompressor::decompress(), testing::DoAll(), EXPECT_CALL, EXPECT_FALSE, EXPECT_THAT, EXPECT_TRUE, folly::pushmi::operators::filter, proxygen::HTTPMessage::getHeaders(), proxygen::HTTPMessage::getIsChunked(), proxygen::ZlibStreamDecompressor::getStatus(), proxygen::ZlibStreamDecompressor::hasError(), proxygen::ResponseBuilder::header(), proxygen::HTTP_HEADER_ACCEPT_ENCODING, proxygen::HTTP_HEADER_CONTENT_ENCODING, proxygen::HTTP_HEADER_CONTENT_TYPE, testing::Invoke(), folly::IOBuf::isChained(), folly::gen::move, folly::IOBuf::next(), folly::IOBuf::prependChain(), testing::Return(), proxygen::ResponseBuilder::send(), folly::netops::send(), proxygen::ResponseBuilder::sendWithEOM(), proxygen::HTTPHeaders::set(), proxygen::HTTPMessage::setURL(), and proxygen::ResponseBuilder::status().
{
     // If there is only one IOBuf, then it's not chunked.
     bool isResponseChunked = originalResponseBody->isChained();
     size_t chunkCount = originalResponseBody->countChainElements();
     // Chunked and compressed responses will have an extra block
     if (isResponseChunked && expectCompression) {
       chunkCount += 1;
     }
     // Request Handler Expectations
     EXPECT_CALL(*requestHandler_, onBody(_)).Times(1);
     EXPECT_CALL(*requestHandler_, onEOM()).Times(1);
     // Need to capture whatever the filter is for ResponseBuilder later
     EXPECT_CALL(*requestHandler_, setResponseHandler(_))
         .WillOnce(DoAll(SaveArg<0>(&downstream_), Return()));
     // Response Handler Expectations
     // Headers are only sent once
     EXPECT_CALL(*responseHandler_, sendHeaders(_)).WillOnce(DoAll(
         Invoke([&](HTTPMessage& msg) {
           auto& headers = msg.getHeaders();
           if (expectCompression) {
             EXPECT_TRUE(msg.checkForHeaderToken(
                 HTTP_HEADER_CONTENT_ENCODING, expectedEncoding.c_str(), false));
           }
           if (msg.getIsChunked()) {
             EXPECT_FALSE(headers.exists("Content-Length"));
           } else {
             //Content-Length is not set on chunked messages
             EXPECT_TRUE(headers.exists("Content-Length"));
           }
         }),
         Return()));
     if (isResponseChunked) {
       // The final chunk has 0 body
       EXPECT_CALL(*responseHandler_, sendChunkHeader(_)).Times(chunkCount);
       EXPECT_CALL(*responseHandler_, sendChunkTerminator()).Times(chunkCount);
     } else {
       EXPECT_CALL(*responseHandler_, sendChunkHeader(_)).Times(0);
       EXPECT_CALL(*responseHandler_, sendChunkTerminator()).Times(0);
     }
     // Accumulate the body, decompressing it if it's compressed
     std::unique_ptr<folly::IOBuf> responseBody;
     EXPECT_CALL(*responseHandler_, sendBody(_))
         .Times(chunkCount)
         .WillRepeatedly(DoAll(
             Invoke([&](std::shared_ptr<folly::IOBuf> body) {
               std::unique_ptr<folly::IOBuf> processedBody;
               if (expectCompression) {
                 processedBody = zd_->decompress(body.get());
                 ASSERT_FALSE(zd_->hasError())
                     << "Failed to decompress body. r=" << zd_->getStatus();
               } else {
                 processedBody = folly::IOBuf::copyBuffer(
                     body->data(), body->length(), 0, 0);
               }
               if (responseBody) {
                 responseBody->prependChain(std::move(processedBody));
               } else {
                 responseBody = std::move(processedBody);
               }
             }),
             Return()));
     EXPECT_CALL(*responseHandler_, sendEOM()).Times(1);
     /* Simulate Request/Response  */
     HTTPMessage msg;
     msg.setURL(url);
     msg.getHeaders().set(HTTP_HEADER_ACCEPT_ENCODING, acceptedEncoding);
     std::set<std::string> compressibleTypes = {"text/html"};
     auto filterFactory = std::make_unique<ZlibServerFilterFactory>(
         compressionLevel, minimumCompressionSize, compressibleTypes);
     auto filter = filterFactory->onRequest(requestHandler_, &msg);
     filter->setResponseHandler(responseHandler_.get());
     // Send fake request
     filter->onBody(folly::IOBuf::copyBuffer(originalRequestBody));
     filter->onEOM();
     // Send a fake Response
     if (isResponseChunked) {
       ResponseBuilder(downstream_)
         .status(200, "OK")
         .header(HTTP_HEADER_CONTENT_TYPE, responseContentType)
         .send();
       folly::IOBuf* crtBuf;
       crtBuf = originalResponseBody.get();
       do {
         ResponseBuilder(downstream_).body(crtBuf->cloneOne()).send();
         crtBuf = crtBuf->next();
       } while (crtBuf != originalResponseBody.get());
       ResponseBuilder(downstream_).sendWithEOM();
     } else {
       // Send unchunked response
       ResponseBuilder(downstream_)
           .status(200, "OK")
           .header(HTTP_HEADER_CONTENT_TYPE, responseContentType)
           .body(originalResponseBody->clone())
           .sendWithEOM();
     }
     filter->requestComplete();
     EXPECT_THAT(responseBody, IOBufEquals(originalRequestBody));
   }
void ZlibServerFilterTest::SetUp () inline override virtual
Reimplemented from testing::Test.
Definition at line 37 of file ZlibServerFilterTest.cpp.
References proxygen::GZIP.
{
     // requesthandler is the server, responsehandler is the client
     requestHandler_ = new MockRequestHandler();
     responseHandler_ = std::make_unique<MockResponseHandler>(requestHandler_);
     zd_ = std::make_unique<ZlibStreamDecompressor>(ZlibCompressionType::GZIP);
   }
void ZlibServerFilterTest::TearDown () inline override virtual
Reimplemented from testing::Test.
Definition at line 44 of file ZlibServerFilterTest.cpp.
{
     Mock::VerifyAndClear(requestHandler_);
     Mock::VerifyAndClear(responseHandler_.get());
     delete requestHandler_;
   }
Member Data Documentation
ResponseHandler* ZlibServerFilterTest::downstream_ {nullptr} protected
Definition at line 56 of file ZlibServerFilterTest.cpp.
ZlibServerFilter* ZlibServerFilterTest::filter_ {nullptr} protected
Definition at line 52 of file ZlibServerFilterTest.cpp.
MockRequestHandler* ZlibServerFilterTest::requestHandler_ protected
Definition at line 53 of file ZlibServerFilterTest.cpp.
std::unique_ptr<MockResponseHandler> ZlibServerFilterTest::responseHandler_ protected
Definition at line 54 of file ZlibServerFilterTest.cpp.
std::unique_ptr<ZlibStreamDecompressor> ZlibServerFilterTest::zd_ protected
Definition at line 55 of file ZlibServerFilterTest.cpp.
The documentation for this class was generated from the following file:
proxygen/httpserver/filters/tests/ZlibServerFilterTest.cpp