proxygen: upload.MercurialVCS Class Reference
upload.MercurialVCS Class Reference
Public Member Functions
def __init__ (self, options, repo_dir)
def GenerateDiff (self, extra_args)
def GetUnknownFiles (self)
def GetBaseFile (self, filename)
def __init__ (self, options, repo_dir)
def GenerateDiff (self, extra_args)
def GetUnknownFiles (self)
def GetBaseFile (self, filename)
def __init__ (self, options, repo_dir)
def GenerateDiff (self, extra_args)
def GetUnknownFiles (self)
def GetBaseFile (self, filename)
def __init__ (self, options, repo_dir)
def GenerateDiff (self, extra_args)
def GetUnknownFiles (self)
def GetBaseFile (self, filename)
def __init__ (self, options, repo_dir)
def GenerateDiff (self, extra_args)
def GetUnknownFiles (self)
def GetBaseFile (self, filename)
def __init__ (self, options, repo_dir)
def GenerateDiff (self, extra_args)
def GetUnknownFiles (self)
def GetBaseFile (self, filename)
Public Member Functions inherited from upload.VersionControlSystem
def __init__ (self, options)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def CheckForUnknownFiles (self)
def GetBaseFile (self, filename)
def GetBaseFiles (self, diff)
def UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
def IsImage (self, filename)
def __init__ (self, options)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def CheckForUnknownFiles (self)
def GetBaseFile (self, filename)
def GetBaseFiles (self, diff)
def UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
def IsImage (self, filename)
def __init__ (self, options)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def CheckForUnknownFiles (self)
def GetBaseFile (self, filename)
def GetBaseFiles (self, diff)
def UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
def IsImage (self, filename)
def __init__ (self, options)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def CheckForUnknownFiles (self)
def GetBaseFile (self, filename)
def GetBaseFiles (self, diff)
def UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
def IsImage (self, filename)
def __init__ (self, options)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def CheckForUnknownFiles (self)
def GetBaseFile (self, filename)
def GetBaseFiles (self, diff)
def UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
def IsImage (self, filename)
def __init__ (self, options)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def CheckForUnknownFiles (self)
def GetBaseFile (self, filename)
def GetBaseFiles (self, diff)
def UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
def IsImage (self, filename)
Public Attributes
repo_dir
subdir
base_rev
Public Attributes inherited from upload.VersionControlSystem
options
Private Member Functions
def _GetRelPath (self, filename)
def _GetRelPath (self, filename)
def _GetRelPath (self, filename)
def _GetRelPath (self, filename)
def _GetRelPath (self, filename)
def _GetRelPath (self, filename)
Detailed Description
Implementation of the VersionControlSystem interface for Mercurial.
Definition at line 1042 of file upload.py.
Constructor & Destructor Documentation
def upload.MercurialVCS.__init__ (self, options, repo_dir)
Definition at line 1045 of file upload.py.
Referenced by upload.MercurialVCS.__init__().
   def __init__(self, options, repo_dir):
     super(MercurialVCS, self).__init__(options)
     # Absolute path to repository (we can be in a subdir)
     self.repo_dir = os.path.normpath(repo_dir)
     # Compute the subdir
     cwd = os.path.normpath(os.getcwd())
     assert cwd.startswith(self.repo_dir)
     self.subdir = cwd[len(self.repo_dir):].lstrip(r"\/")
     if self.options.revision:
       self.base_rev = self.options.revision
     else:
       self.base_rev = RunShell(["hg", "parent", "-q"]).split(':')[1].strip()
def upload.MercurialVCS.__init__ (self, options, repo_dir)
Definition at line 1045 of file upload.py.
References upload.MercurialVCS.__init__(), upload.MercurialVCS.base_rev, upload.MercurialVCS.repo_dir, upload.RunShell(), folly::gen.split(), folly::detail::distributed_mutex.strip(), and upload.MercurialVCS.subdir.
   def __init__(self, options, repo_dir):
     super(MercurialVCS, self).__init__(options)
     # Absolute path to repository (we can be in a subdir)
     self.repo_dir = os.path.normpath(repo_dir)
     # Compute the subdir
     cwd = os.path.normpath(os.getcwd())
     assert cwd.startswith(self.repo_dir)
     self.subdir = cwd[len(self.repo_dir):].lstrip(r"\/")
     if self.options.revision:
       self.base_rev = self.options.revision
     else:
       self.base_rev = RunShell(["hg", "parent", "-q"]).split(':')[1].strip()
def upload.MercurialVCS.__init__ (self, options, repo_dir)
Definition at line 1045 of file upload.py.
References upload.MercurialVCS.__init__(), upload.MercurialVCS.base_rev, upload.MercurialVCS.repo_dir, upload.RunShell(), folly::gen.split(), folly::detail::distributed_mutex.strip(), and upload.MercurialVCS.subdir.
   def __init__(self, options, repo_dir):
     super(MercurialVCS, self).__init__(options)
     # Absolute path to repository (we can be in a subdir)
     self.repo_dir = os.path.normpath(repo_dir)
     # Compute the subdir
     cwd = os.path.normpath(os.getcwd())
     assert cwd.startswith(self.repo_dir)
     self.subdir = cwd[len(self.repo_dir):].lstrip(r"\/")
     if self.options.revision:
       self.base_rev = self.options.revision
     else:
       self.base_rev = RunShell(["hg", "parent", "-q"]).split(':')[1].strip()
def upload.MercurialVCS.__init__ (self, options, repo_dir)
Definition at line 1045 of file upload.py.
References upload.MercurialVCS.__init__(), upload.MercurialVCS.base_rev, upload.MercurialVCS.repo_dir, upload.RunShell(), folly::gen.split(), folly::detail::distributed_mutex.strip(), and upload.MercurialVCS.subdir.
   def __init__(self, options, repo_dir):
     super(MercurialVCS, self).__init__(options)
     # Absolute path to repository (we can be in a subdir)
     self.repo_dir = os.path.normpath(repo_dir)
     # Compute the subdir
     cwd = os.path.normpath(os.getcwd())
     assert cwd.startswith(self.repo_dir)
     self.subdir = cwd[len(self.repo_dir):].lstrip(r"\/")
     if self.options.revision:
       self.base_rev = self.options.revision
     else:
       self.base_rev = RunShell(["hg", "parent", "-q"]).split(':')[1].strip()
def upload.MercurialVCS.__init__ (self, options, repo_dir)
Definition at line 1045 of file upload.py.
References upload.MercurialVCS.__init__(), upload.MercurialVCS.base_rev, upload.MercurialVCS.repo_dir, upload.RunShell(), folly::gen.split(), folly::detail::distributed_mutex.strip(), and upload.MercurialVCS.subdir.
   def __init__(self, options, repo_dir):
     super(MercurialVCS, self).__init__(options)
     # Absolute path to repository (we can be in a subdir)
     self.repo_dir = os.path.normpath(repo_dir)
     # Compute the subdir
     cwd = os.path.normpath(os.getcwd())
     assert cwd.startswith(self.repo_dir)
     self.subdir = cwd[len(self.repo_dir):].lstrip(r"\/")
     if self.options.revision:
       self.base_rev = self.options.revision
     else:
       self.base_rev = RunShell(["hg", "parent", "-q"]).split(':')[1].strip()
def upload.MercurialVCS.__init__ (self, options, repo_dir)
Definition at line 1045 of file upload.py.
References upload.MercurialVCS.__init__(), upload.MercurialVCS.base_rev, upload.MercurialVCS.repo_dir, upload.RunShell(), folly::gen.split(), folly::detail::distributed_mutex.strip(), and upload.MercurialVCS.subdir.
   def __init__(self, options, repo_dir):
     super(MercurialVCS, self).__init__(options)
     # Absolute path to repository (we can be in a subdir)
     self.repo_dir = os.path.normpath(repo_dir)
     # Compute the subdir
     cwd = os.path.normpath(os.getcwd())
     assert cwd.startswith(self.repo_dir)
     self.subdir = cwd[len(self.repo_dir):].lstrip(r"\/")
     if self.options.revision:
       self.base_rev = self.options.revision
     else:
       self.base_rev = RunShell(["hg", "parent", "-q"]).split(':')[1].strip()
Member Function Documentation
def upload.MercurialVCS._GetRelPath (self, filename) private
Get relative path of a file according to the current directory,
given its logical path in the repo.
Definition at line 1058 of file upload.py.
References upload.MercurialVCS.subdir.
Referenced by upload.MercurialVCS._GetRelPath(), and upload.MercurialVCS.GetBaseFile().
   def _GetRelPath(self, filename):
     """Get relative path of a file according to the current directory,
     given its logical path in the repo."""
     assert filename.startswith(self.subdir), filename
     return filename[len(self.subdir):].lstrip(r"\/")
def upload.MercurialVCS._GetRelPath (self, filename) private
Get relative path of a file according to the current directory,
given its logical path in the repo.
Definition at line 1058 of file upload.py.
References upload.MercurialVCS._GetRelPath(), and upload.MercurialVCS.subdir.
   def _GetRelPath(self, filename):
     """Get relative path of a file according to the current directory,
     given its logical path in the repo."""
     assert filename.startswith(self.subdir), filename
     return filename[len(self.subdir):].lstrip(r"\/")
def upload.MercurialVCS._GetRelPath (self, filename) private
Get relative path of a file according to the current directory,
given its logical path in the repo.
Definition at line 1058 of file upload.py.
References upload.MercurialVCS._GetRelPath(), and upload.MercurialVCS.subdir.
   def _GetRelPath(self, filename):
     """Get relative path of a file according to the current directory,
     given its logical path in the repo."""
     assert filename.startswith(self.subdir), filename
     return filename[len(self.subdir):].lstrip(r"\/")
def upload.MercurialVCS._GetRelPath (self, filename) private
Get relative path of a file according to the current directory,
given its logical path in the repo.
Definition at line 1058 of file upload.py.
References upload.MercurialVCS._GetRelPath(), and upload.MercurialVCS.subdir.
   def _GetRelPath(self, filename):
     """Get relative path of a file according to the current directory,
     given its logical path in the repo."""
     assert filename.startswith(self.subdir), filename
     return filename[len(self.subdir):].lstrip(r"\/")
def upload.MercurialVCS._GetRelPath (self, filename) private
Get relative path of a file according to the current directory,
given its logical path in the repo.
Definition at line 1058 of file upload.py.
References upload.MercurialVCS._GetRelPath(), and upload.MercurialVCS.subdir.
   def _GetRelPath(self, filename):
     """Get relative path of a file according to the current directory,
     given its logical path in the repo."""
     assert filename.startswith(self.subdir), filename
     return filename[len(self.subdir):].lstrip(r"\/")
def upload.MercurialVCS._GetRelPath (self, filename) private
Get relative path of a file according to the current directory,
given its logical path in the repo.
Definition at line 1058 of file upload.py.
References upload.MercurialVCS._GetRelPath(), and upload.MercurialVCS.subdir.
   def _GetRelPath(self, filename):
     """Get relative path of a file according to the current directory,
     given its logical path in the repo."""
     assert filename.startswith(self.subdir), filename
     return filename[len(self.subdir):].lstrip(r"\/")
def upload.MercurialVCS.GenerateDiff (self, extra_args)
Definition at line 1064 of file upload.py.
References upload.MercurialVCS.base_rev, upload.ErrorExit(), upload.MercurialVCS.GenerateDiff(), join, and upload.RunShell().
   def GenerateDiff(self, extra_args):
     # If no file specified, restrict to the current subdir
     extra_args = extra_args or ["."]
     cmd = ["hg", "diff", "--git", "-r", self.base_rev] + extra_args
     data = RunShell(cmd, silent_ok=True)
     svndiff = []
     filecount = 0
     for line in data.splitlines():
       m = re.match("diff --git a/(\S+) b/(\S+)", line)
       if m:
         # Modify line to make it look like as it comes from svn diff.
         # With this modification no changes on the server side are required
         # to make upload.py work with Mercurial repos.
         # NOTE: for proper handling of moved/copied files, we have to use
         # the second filename.
         filename = m.group(2)
         svndiff.append("Index: %s" % filename)
         svndiff.append("=" * 67)
         filecount += 1
         logging.info(line)
       else:
         svndiff.append(line)
     if not filecount:
       ErrorExit("No valid patches found in output from hg diff")
     return "\n".join(svndiff) + "\n"
def upload.MercurialVCS.GenerateDiff (self, extra_args)
Definition at line 1064 of file upload.py.
References upload.MercurialVCS.base_rev, upload.ErrorExit(), join, and upload.RunShell().
Referenced by upload.MercurialVCS.GenerateDiff().
   def GenerateDiff(self, extra_args):
     # If no file specified, restrict to the current subdir
     extra_args = extra_args or ["."]
     cmd = ["hg", "diff", "--git", "-r", self.base_rev] + extra_args
     data = RunShell(cmd, silent_ok=True)
     svndiff = []
     filecount = 0
     for line in data.splitlines():
       m = re.match("diff --git a/(\S+) b/(\S+)", line)
       if m:
         # Modify line to make it look like as it comes from svn diff.
         # With this modification no changes on the server side are required
         # to make upload.py work with Mercurial repos.
         # NOTE: for proper handling of moved/copied files, we have to use
         # the second filename.
         filename = m.group(2)
         svndiff.append("Index: %s" % filename)
         svndiff.append("=" * 67)
         filecount += 1
         logging.info(line)
       else:
         svndiff.append(line)
     if not filecount:
       ErrorExit("No valid patches found in output from hg diff")
     return "\n".join(svndiff) + "\n"
def upload.MercurialVCS.GenerateDiff (self, extra_args)
Definition at line 1064 of file upload.py.
References upload.MercurialVCS.base_rev, upload.ErrorExit(), upload.MercurialVCS.GenerateDiff(), join, and upload.RunShell().
   def GenerateDiff(self, extra_args):
     # If no file specified, restrict to the current subdir
     extra_args = extra_args or ["."]
     cmd = ["hg", "diff", "--git", "-r", self.base_rev] + extra_args
     data = RunShell(cmd, silent_ok=True)
     svndiff = []
     filecount = 0
     for line in data.splitlines():
       m = re.match("diff --git a/(\S+) b/(\S+)", line)
       if m:
         # Modify line to make it look like as it comes from svn diff.
         # With this modification no changes on the server side are required
         # to make upload.py work with Mercurial repos.
         # NOTE: for proper handling of moved/copied files, we have to use
         # the second filename.
         filename = m.group(2)
         svndiff.append("Index: %s" % filename)
         svndiff.append("=" * 67)
         filecount += 1
         logging.info(line)
       else:
         svndiff.append(line)
     if not filecount:
       ErrorExit("No valid patches found in output from hg diff")
     return "\n".join(svndiff) + "\n"
def upload.MercurialVCS.GenerateDiff (self, extra_args)
Definition at line 1064 of file upload.py.
References upload.MercurialVCS.base_rev, upload.ErrorExit(), upload.MercurialVCS.GenerateDiff(), join, and upload.RunShell().
   def GenerateDiff(self, extra_args):
     # If no file specified, restrict to the current subdir
     extra_args = extra_args or ["."]
     cmd = ["hg", "diff", "--git", "-r", self.base_rev] + extra_args
     data = RunShell(cmd, silent_ok=True)
     svndiff = []
     filecount = 0
     for line in data.splitlines():
       m = re.match("diff --git a/(\S+) b/(\S+)", line)
       if m:
         # Modify line to make it look like as it comes from svn diff.
         # With this modification no changes on the server side are required
         # to make upload.py work with Mercurial repos.
         # NOTE: for proper handling of moved/copied files, we have to use
         # the second filename.
         filename = m.group(2)
         svndiff.append("Index: %s" % filename)
         svndiff.append("=" * 67)
         filecount += 1
         logging.info(line)
       else:
         svndiff.append(line)
     if not filecount:
       ErrorExit("No valid patches found in output from hg diff")
     return "\n".join(svndiff) + "\n"
def upload.MercurialVCS.GenerateDiff (self, extra_args)
Definition at line 1064 of file upload.py.
References upload.MercurialVCS.base_rev, upload.ErrorExit(), upload.MercurialVCS.GenerateDiff(), join, and upload.RunShell().
   def GenerateDiff(self, extra_args):
     # If no file specified, restrict to the current subdir
     extra_args = extra_args or ["."]
     cmd = ["hg", "diff", "--git", "-r", self.base_rev] + extra_args
     data = RunShell(cmd, silent_ok=True)
     svndiff = []
     filecount = 0
     for line in data.splitlines():
       m = re.match("diff --git a/(\S+) b/(\S+)", line)
       if m:
         # Modify line to make it look like as it comes from svn diff.
         # With this modification no changes on the server side are required
         # to make upload.py work with Mercurial repos.
         # NOTE: for proper handling of moved/copied files, we have to use
         # the second filename.
         filename = m.group(2)
         svndiff.append("Index: %s" % filename)
         svndiff.append("=" * 67)
         filecount += 1
         logging.info(line)
       else:
         svndiff.append(line)
     if not filecount:
       ErrorExit("No valid patches found in output from hg diff")
     return "\n".join(svndiff) + "\n"
def upload.MercurialVCS.GenerateDiff (self, extra_args)
Definition at line 1064 of file upload.py.
References upload.MercurialVCS.base_rev, upload.ErrorExit(), upload.MercurialVCS.GenerateDiff(), join, and upload.RunShell().
   def GenerateDiff(self, extra_args):
     # If no file specified, restrict to the current subdir
     extra_args = extra_args or ["."]
     cmd = ["hg", "diff", "--git", "-r", self.base_rev] + extra_args
     data = RunShell(cmd, silent_ok=True)
     svndiff = []
     filecount = 0
     for line in data.splitlines():
       m = re.match("diff --git a/(\S+) b/(\S+)", line)
       if m:
         # Modify line to make it look like as it comes from svn diff.
         # With this modification no changes on the server side are required
         # to make upload.py work with Mercurial repos.
         # NOTE: for proper handling of moved/copied files, we have to use
         # the second filename.
         filename = m.group(2)
         svndiff.append("Index: %s" % filename)
         svndiff.append("=" * 67)
         filecount += 1
         logging.info(line)
       else:
         svndiff.append(line)
     if not filecount:
       ErrorExit("No valid patches found in output from hg diff")
     return "\n".join(svndiff) + "\n"
def upload.MercurialVCS.GetBaseFile (self, filename)
Definition at line 1102 of file upload.py.
References upload.MercurialVCS._GetRelPath(), upload.MercurialVCS.base_rev, count, upload.EncodeMultipartFormData(), upload.ErrorExit(), upload.MercurialVCS.GetBaseFile(), upload.GetRpcServer(), upload.GuessVCS(), upload.VersionControlSystem.IsImage(), join, upload.main(), fizz::detail.read(), upload.RealMain(), replace(), upload.RunShell(), upload.RunShellWithReturnCode(), folly::gen.split(), upload.SplitPatch(), upload.StatusUpdate(), folly::detail::distributed_mutex.strip(), and upload.UploadSeparatePatches().
   def GetBaseFile(self, filename):
     # "hg status" and "hg cat" both take a path relative to the current subdir
     # rather than to the repo root, but "hg diff" has given us the full path
     # to the repo root.
     base_content = ""
     new_content = None
     is_binary = False
     oldrelpath = relpath = self._GetRelPath(filename)
     # "hg status -C" returns two lines for moved/copied files, one otherwise
     out = RunShell(["hg", "status", "-C", "--rev", self.base_rev, relpath])
     out = out.splitlines()
     # HACK: strip error message about missing file/directory if it isn't in
     # the working copy
     if out[0].startswith('%s: ' % relpath):
       out = out[1:]
     if len(out) > 1:
       # Moved/copied => considered as modified, use old filename to
       # retrieve base contents
       oldrelpath = out[1].strip()
       status = "M"
     else:
       status, _ = out[0].split(' ', 1)
     if status != "A":
       base_content = RunShell(["hg", "cat", "-r", self.base_rev, oldrelpath],
         silent_ok=True)
       is_binary = "\0" in base_content  # Mercurial's heuristic
     if status != "R":
       new_content = open(relpath, "rb").read()
       is_binary = is_binary or "\0" in new_content
     if is_binary and base_content:
       # Fetch again without converting newlines
       base_content = RunShell(["hg", "cat", "-r", self.base_rev, oldrelpath],
         silent_ok=True, universal_newlines=False)
     if not is_binary or not self.IsImage(relpath):
       new_content = None
     return base_content, new_content, is_binary, status
 # NOTE: The SplitPatch function is duplicated in engine.py, keep them in sync.
def upload.MercurialVCS.GetBaseFile (self, filename)
Definition at line 1102 of file upload.py.
References upload.MercurialVCS._GetRelPath(), upload.MercurialVCS.base_rev, count, upload.EncodeMultipartFormData(), upload.ErrorExit(), upload.MercurialVCS.GetBaseFile(), upload.GetRpcServer(), upload.GuessVCS(), upload.VersionControlSystem.IsImage(), join, upload.main(), fizz::detail.read(), upload.RealMain(), replace(), upload.RunShell(), upload.RunShellWithReturnCode(), folly::gen.split(), upload.SplitPatch(), upload.StatusUpdate(), folly::detail::distributed_mutex.strip(), and upload.UploadSeparatePatches().
   def GetBaseFile(self, filename):
     # "hg status" and "hg cat" both take a path relative to the current subdir
     # rather than to the repo root, but "hg diff" has given us the full path
     # to the repo root.
     base_content = ""
     new_content = None
     is_binary = False
     oldrelpath = relpath = self._GetRelPath(filename)
     # "hg status -C" returns two lines for moved/copied files, one otherwise
     out = RunShell(["hg", "status", "-C", "--rev", self.base_rev, relpath])
     out = out.splitlines()
     # HACK: strip error message about missing file/directory if it isn't in
     # the working copy
     if out[0].startswith('%s: ' % relpath):
       out = out[1:]
     if len(out) > 1:
       # Moved/copied => considered as modified, use old filename to
       # retrieve base contents
       oldrelpath = out[1].strip()
       status = "M"
     else:
       status, _ = out[0].split(' ', 1)
     if status != "A":
       base_content = RunShell(["hg", "cat", "-r", self.base_rev, oldrelpath],
         silent_ok=True)
       is_binary = "\0" in base_content  # Mercurial's heuristic
     if status != "R":
       new_content = open(relpath, "rb").read()
       is_binary = is_binary or "\0" in new_content
     if is_binary and base_content:
       # Fetch again without converting newlines
       base_content = RunShell(["hg", "cat", "-r", self.base_rev, oldrelpath],
         silent_ok=True, universal_newlines=False)
     if not is_binary or not self.IsImage(relpath):
       new_content = None
     return base_content, new_content, is_binary, status
 # NOTE: The SplitPatch function is duplicated in engine.py, keep them in sync.
def upload.MercurialVCS.GetBaseFile (self, filename)
Definition at line 1102 of file upload.py.
References upload.MercurialVCS._GetRelPath(), upload.MercurialVCS.base_rev, count, upload.EncodeMultipartFormData(), upload.ErrorExit(), upload.MercurialVCS.GetBaseFile(), upload.GetRpcServer(), upload.GuessVCS(), upload.VersionControlSystem.IsImage(), join, upload.main(), fizz::detail.read(), upload.RealMain(), replace(), upload.RunShell(), upload.RunShellWithReturnCode(), folly::gen.split(), upload.SplitPatch(), upload.StatusUpdate(), folly::detail::distributed_mutex.strip(), and upload.UploadSeparatePatches().
   def GetBaseFile(self, filename):
     # "hg status" and "hg cat" both take a path relative to the current subdir
     # rather than to the repo root, but "hg diff" has given us the full path
     # to the repo root.
     base_content = ""
     new_content = None
     is_binary = False
     oldrelpath = relpath = self._GetRelPath(filename)
     # "hg status -C" returns two lines for moved/copied files, one otherwise
     out = RunShell(["hg", "status", "-C", "--rev", self.base_rev, relpath])
     out = out.splitlines()
     # HACK: strip error message about missing file/directory if it isn't in
     # the working copy
     if out[0].startswith('%s: ' % relpath):
       out = out[1:]
     if len(out) > 1:
       # Moved/copied => considered as modified, use old filename to
       # retrieve base contents
       oldrelpath = out[1].strip()
       status = "M"
     else:
       status, _ = out[0].split(' ', 1)
     if status != "A":
       base_content = RunShell(["hg", "cat", "-r", self.base_rev, oldrelpath],
         silent_ok=True)
       is_binary = "\0" in base_content  # Mercurial's heuristic
     if status != "R":
       new_content = open(relpath, "rb").read()
       is_binary = is_binary or "\0" in new_content
     if is_binary and base_content:
       # Fetch again without converting newlines
       base_content = RunShell(["hg", "cat", "-r", self.base_rev, oldrelpath],
         silent_ok=True, universal_newlines=False)
     if not is_binary or not self.IsImage(relpath):
       new_content = None
     return base_content, new_content, is_binary, status
 # NOTE: The SplitPatch function is duplicated in engine.py, keep them in sync.
def upload.MercurialVCS.GetBaseFile (self, filename)
Definition at line 1102 of file upload.py.
References upload.MercurialVCS._GetRelPath(), upload.MercurialVCS.base_rev, upload.VersionControlSystem.IsImage(), fizz::detail.read(), upload.RunShell(), folly::gen.split(), and folly::detail::distributed_mutex.strip().
Referenced by upload.MercurialVCS.GetBaseFile().
   def GetBaseFile(self, filename):
     # "hg status" and "hg cat" both take a path relative to the current subdir
     # rather than to the repo root, but "hg diff" has given us the full path
     # to the repo root.
     base_content = ""
     new_content = None
     is_binary = False
     oldrelpath = relpath = self._GetRelPath(filename)
     # "hg status -C" returns two lines for moved/copied files, one otherwise
     out = RunShell(["hg", "status", "-C", "--rev", self.base_rev, relpath])
     out = out.splitlines()
     # HACK: strip error message about missing file/directory if it isn't in
     # the working copy
     if out[0].startswith('%s: ' % relpath):
       out = out[1:]
     if len(out) > 1:
       # Moved/copied => considered as modified, use old filename to
       # retrieve base contents
       oldrelpath = out[1].strip()
       status = "M"
     else:
       status, _ = out[0].split(' ', 1)
     if status != "A":
       base_content = RunShell(["hg", "cat", "-r", self.base_rev, oldrelpath],
         silent_ok=True)
       is_binary = "\0" in base_content  # Mercurial's heuristic
     if status != "R":
       new_content = open(relpath, "rb").read()
       is_binary = is_binary or "\0" in new_content
     if is_binary and base_content:
       # Fetch again without converting newlines
       base_content = RunShell(["hg", "cat", "-r", self.base_rev, oldrelpath],
         silent_ok=True, universal_newlines=False)
     if not is_binary or not self.IsImage(relpath):
       new_content = None
     return base_content, new_content, is_binary, status
 # NOTE: The SplitPatch function is duplicated in engine.py, keep them in sync.
def upload.MercurialVCS.GetBaseFile (self, filename)
Definition at line 1102 of file upload.py.
References upload.MercurialVCS._GetRelPath(), upload.MercurialVCS.base_rev, count, upload.EncodeMultipartFormData(), upload.ErrorExit(), upload.MercurialVCS.GetBaseFile(), upload.GetRpcServer(), upload.GuessVCS(), upload.VersionControlSystem.IsImage(), join, upload.main(), fizz::detail.read(), upload.RealMain(), replace(), upload.RunShell(), upload.RunShellWithReturnCode(), folly::gen.split(), upload.SplitPatch(), upload.StatusUpdate(), folly::detail::distributed_mutex.strip(), and upload.UploadSeparatePatches().
   def GetBaseFile(self, filename):
     # "hg status" and "hg cat" both take a path relative to the current subdir
     # rather than to the repo root, but "hg diff" has given us the full path
     # to the repo root.
     base_content = ""
     new_content = None
     is_binary = False
     oldrelpath = relpath = self._GetRelPath(filename)
     # "hg status -C" returns two lines for moved/copied files, one otherwise
     out = RunShell(["hg", "status", "-C", "--rev", self.base_rev, relpath])
     out = out.splitlines()
     # HACK: strip error message about missing file/directory if it isn't in
     # the working copy
     if out[0].startswith('%s: ' % relpath):
       out = out[1:]
     if len(out) > 1:
       # Moved/copied => considered as modified, use old filename to
       # retrieve base contents
       oldrelpath = out[1].strip()
       status = "M"
     else:
       status, _ = out[0].split(' ', 1)
     if status != "A":
       base_content = RunShell(["hg", "cat", "-r", self.base_rev, oldrelpath],
         silent_ok=True)
       is_binary = "\0" in base_content  # Mercurial's heuristic
     if status != "R":
       new_content = open(relpath, "rb").read()
       is_binary = is_binary or "\0" in new_content
     if is_binary and base_content:
       # Fetch again without converting newlines
       base_content = RunShell(["hg", "cat", "-r", self.base_rev, oldrelpath],
         silent_ok=True, universal_newlines=False)
     if not is_binary or not self.IsImage(relpath):
       new_content = None
     return base_content, new_content, is_binary, status
 # NOTE: The SplitPatch function is duplicated in engine.py, keep them in sync.
def upload.MercurialVCS.GetBaseFile (self, filename)
Definition at line 1102 of file upload.py.
References upload.MercurialVCS._GetRelPath(), upload.MercurialVCS.base_rev, count, upload.EncodeMultipartFormData(), upload.ErrorExit(), upload.MercurialVCS.GetBaseFile(), upload.GetRpcServer(), upload.GuessVCS(), upload.VersionControlSystem.IsImage(), join, upload.main(), fizz::detail.read(), upload.RealMain(), replace(), upload.RunShell(), upload.RunShellWithReturnCode(), folly::gen.split(), upload.SplitPatch(), upload.StatusUpdate(), folly::detail::distributed_mutex.strip(), and upload.UploadSeparatePatches().
   def GetBaseFile(self, filename):
     # "hg status" and "hg cat" both take a path relative to the current subdir
     # rather than to the repo root, but "hg diff" has given us the full path
     # to the repo root.
     base_content = ""
     new_content = None
     is_binary = False
     oldrelpath = relpath = self._GetRelPath(filename)
     # "hg status -C" returns two lines for moved/copied files, one otherwise
     out = RunShell(["hg", "status", "-C", "--rev", self.base_rev, relpath])
     out = out.splitlines()
     # HACK: strip error message about missing file/directory if it isn't in
     # the working copy
     if out[0].startswith('%s: ' % relpath):
       out = out[1:]
     if len(out) > 1:
       # Moved/copied => considered as modified, use old filename to
       # retrieve base contents
       oldrelpath = out[1].strip()
       status = "M"
     else:
       status, _ = out[0].split(' ', 1)
     if status != "A":
       base_content = RunShell(["hg", "cat", "-r", self.base_rev, oldrelpath],
         silent_ok=True)
       is_binary = "\0" in base_content  # Mercurial's heuristic
     if status != "R":
       new_content = open(relpath, "rb").read()
       is_binary = is_binary or "\0" in new_content
     if is_binary and base_content:
       # Fetch again without converting newlines
       base_content = RunShell(["hg", "cat", "-r", self.base_rev, oldrelpath],
         silent_ok=True, universal_newlines=False)
     if not is_binary or not self.IsImage(relpath):
       new_content = None
     return base_content, new_content, is_binary, status
 # NOTE: The SplitPatch function is duplicated in engine.py, keep them in sync.
def upload.MercurialVCS.GetUnknownFiles (self)
Return a list of files unknown to the VCS.
Definition at line 1090 of file upload.py.
References upload.MercurialVCS.base_rev, upload.MercurialVCS.GetUnknownFiles(), and upload.RunShell().
   def GetUnknownFiles(self):
     """Return a list of files unknown to the VCS."""
     args = []
     status = RunShell(["hg", "status", "--rev", self.base_rev, "-u", "."],
         silent_ok=True)
     unknown_files = []
     for line in status.splitlines():
       st, fn = line.split(" ", 1)
       if st == "?":
         unknown_files.append(fn)
     return unknown_files
def upload.MercurialVCS.GetUnknownFiles (self)
Return a list of files unknown to the VCS.
Definition at line 1090 of file upload.py.
References upload.MercurialVCS.base_rev, upload.MercurialVCS.GetUnknownFiles(), and upload.RunShell().
   def GetUnknownFiles(self):
     """Return a list of files unknown to the VCS."""
     args = []
     status = RunShell(["hg", "status", "--rev", self.base_rev, "-u", "."],
         silent_ok=True)
     unknown_files = []
     for line in status.splitlines():
       st, fn = line.split(" ", 1)
       if st == "?":
         unknown_files.append(fn)
     return unknown_files
def upload.MercurialVCS.GetUnknownFiles (self)
Return a list of files unknown to the VCS.
Definition at line 1090 of file upload.py.
References upload.MercurialVCS.base_rev, upload.MercurialVCS.GetUnknownFiles(), and upload.RunShell().
   def GetUnknownFiles(self):
     """Return a list of files unknown to the VCS."""
     args = []
     status = RunShell(["hg", "status", "--rev", self.base_rev, "-u", "."],
         silent_ok=True)
     unknown_files = []
     for line in status.splitlines():
       st, fn = line.split(" ", 1)
       if st == "?":
         unknown_files.append(fn)
     return unknown_files
def upload.MercurialVCS.GetUnknownFiles (self)
Return a list of files unknown to the VCS.
Definition at line 1090 of file upload.py.
References upload.MercurialVCS.base_rev, upload.MercurialVCS.GetUnknownFiles(), and upload.RunShell().
   def GetUnknownFiles(self):
     """Return a list of files unknown to the VCS."""
     args = []
     status = RunShell(["hg", "status", "--rev", self.base_rev, "-u", "."],
         silent_ok=True)
     unknown_files = []
     for line in status.splitlines():
       st, fn = line.split(" ", 1)
       if st == "?":
         unknown_files.append(fn)
     return unknown_files
def upload.MercurialVCS.GetUnknownFiles (self)
Return a list of files unknown to the VCS.
Definition at line 1090 of file upload.py.
References upload.MercurialVCS.base_rev, and upload.RunShell().
Referenced by upload.MercurialVCS.GetUnknownFiles().
   def GetUnknownFiles(self):
     """Return a list of files unknown to the VCS."""
     args = []
     status = RunShell(["hg", "status", "--rev", self.base_rev, "-u", "."],
         silent_ok=True)
     unknown_files = []
     for line in status.splitlines():
       st, fn = line.split(" ", 1)
       if st == "?":
         unknown_files.append(fn)
     return unknown_files
def upload.MercurialVCS.GetUnknownFiles (self)
Return a list of files unknown to the VCS.
Definition at line 1090 of file upload.py.
References upload.MercurialVCS.base_rev, upload.MercurialVCS.GetUnknownFiles(), and upload.RunShell().
   def GetUnknownFiles(self):
     """Return a list of files unknown to the VCS."""
     args = []
     status = RunShell(["hg", "status", "--rev", self.base_rev, "-u", "."],
         silent_ok=True)
     unknown_files = []
     for line in status.splitlines():
       st, fn = line.split(" ", 1)
       if st == "?":
         unknown_files.append(fn)
     return unknown_files
Member Data Documentation
upload.MercurialVCS.base_rev
Definition at line 1054 of file upload.py.
Referenced by upload.MercurialVCS.__init__(), upload.MercurialVCS.GenerateDiff(), upload.MercurialVCS.GetBaseFile(), and upload.MercurialVCS.GetUnknownFiles().
upload.MercurialVCS.repo_dir
Definition at line 1048 of file upload.py.
Referenced by upload.MercurialVCS.__init__().
upload.MercurialVCS.subdir
Definition at line 1052 of file upload.py.
Referenced by upload.MercurialVCS.__init__(), and upload.MercurialVCS._GetRelPath().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/scripts/upload.py