proxygen: gtest_xml_output_unittest.GTestXMLOutputUnitTest Class Reference
gtest_xml_output_unittest.GTestXMLOutputUnitTest Class Reference
Public Member Functions
def testNonEmptyXmlOutput (self)
def testEmptyXmlOutput (self)
def testTimestampValue (self)
def testDefaultOutputFile (self)
def testSuppressedXmlOutput (self)
def testFilteredTestXmlOutput (self)
def testNonEmptyXmlOutput (self)
def testEmptyXmlOutput (self)
def testTimestampValue (self)
def testDefaultOutputFile (self)
def testSuppressedXmlOutput (self)
def testFilteredTestXmlOutput (self)
def testNonEmptyXmlOutput (self)
def testEmptyXmlOutput (self)
def testTimestampValue (self)
def testDefaultOutputFile (self)
def testSuppressedXmlOutput (self)
def testFilteredTestXmlOutput (self)
Public Member Functions inherited from gtest_xml_test_utils.GTestXMLTestCase
def AssertEquivalentNodes (self, expected_node, actual_node)
def NormalizeXml (self, element)
def AssertEquivalentNodes (self, expected_node, actual_node)
def NormalizeXml (self, element)
def AssertEquivalentNodes (self, expected_node, actual_node)
def NormalizeXml (self, element)
Private Member Functions
def _GetXmlOutput (self, gtest_prog_name, extra_args, expected_exit_code)
def _TestXmlOutput (self, gtest_prog_name, expected_xml, expected_exit_code, extra_args=None)
def _GetXmlOutput (self, gtest_prog_name, extra_args, expected_exit_code)
def _TestXmlOutput (self, gtest_prog_name, expected_xml, expected_exit_code, extra_args=None)
def _GetXmlOutput (self, gtest_prog_name, extra_args, expected_exit_code)
def _TestXmlOutput (self, gtest_prog_name, expected_xml, expected_exit_code, extra_args=None)
Additional Inherited Members
Static Public Attributes inherited from gtest_xml_test_utils.GTestXMLTestCase
dictionary identifying_attribute
Detailed Description
Unit test for Google Test's XML output functionality.
Definition at line 152 of file gtest_xml_output_unittest.py.
Member Function Documentation
def gtest_xml_output_unittest.GTestXMLOutputUnitTest._GetXmlOutput (self, gtest_prog_name, extra_args, expected_exit_code) private
Returns the xml output generated by running the program gtest_prog_name.
Furthermore, the program's exit code must be expected_exit_code.
Definition at line 263 of file gtest_xml_output_unittest.py.
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput(), gtest_test_utils.GetTempDir(), and gtest_test_utils.GetTestExecutablePath().
Referenced by gtest_xml_output_unittest.GTestXMLOutputUnitTest._GetXmlOutput(), gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput(), and gtest_xml_output_unittest.GTestXMLOutputUnitTest.testTimestampValue().
   def _GetXmlOutput(self, gtest_prog_name, extra_args, expected_exit_code):
     """
     Returns the xml output generated by running the program gtest_prog_name.
     Furthermore, the program's exit code must be expected_exit_code.
     """
     xml_path = os.path.join(gtest_test_utils.GetTempDir(),
                             gtest_prog_name + 'out.xml')
     gtest_prog_path = gtest_test_utils.GetTestExecutablePath(gtest_prog_name)
     command = ([gtest_prog_path, '%s=xml:%s' % (GTEST_OUTPUT_FLAG, xml_path)] +
                extra_args)
     p = gtest_test_utils.Subprocess(command)
     if p.terminated_by_signal:
       self.assert_(False,
                    '%s was killed by signal %d' % (gtest_prog_name, p.signal))
     else:
       self.assert_(p.exited)
       self.assertEquals(expected_exit_code, p.exit_code,
                         "'%s' exited with code %s, which doesn't match "
                         'the expected exit code %s.'
                         % (command, p.exit_code, expected_exit_code))
     actual = minidom.parse(xml_path)
     return actual
def gtest_xml_output_unittest.GTestXMLOutputUnitTest._GetXmlOutput (self, gtest_prog_name, extra_args, expected_exit_code) private
Returns the xml output generated by running the program gtest_prog_name.
Furthermore, the program's exit code must be expected_exit_code.
Definition at line 263 of file gtest_xml_output_unittest.py.
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._GetXmlOutput(), gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput(), gtest_test_utils.GetTempDir(), and gtest_test_utils.GetTestExecutablePath().
   def _GetXmlOutput(self, gtest_prog_name, extra_args, expected_exit_code):
     """
     Returns the xml output generated by running the program gtest_prog_name.
     Furthermore, the program's exit code must be expected_exit_code.
     """
     xml_path = os.path.join(gtest_test_utils.GetTempDir(),
                             gtest_prog_name + 'out.xml')
     gtest_prog_path = gtest_test_utils.GetTestExecutablePath(gtest_prog_name)
     command = ([gtest_prog_path, '%s=xml:%s' % (GTEST_OUTPUT_FLAG, xml_path)] +
                extra_args)
     p = gtest_test_utils.Subprocess(command)
     if p.terminated_by_signal:
       self.assert_(False,
                    '%s was killed by signal %d' % (gtest_prog_name, p.signal))
     else:
       self.assert_(p.exited)
       self.assertEquals(expected_exit_code, p.exit_code,
                         "'%s' exited with code %s, which doesn't match "
                         'the expected exit code %s.'
                         % (command, p.exit_code, expected_exit_code))
     actual = minidom.parse(xml_path)
     return actual
def gtest_xml_output_unittest.GTestXMLOutputUnitTest._GetXmlOutput (self, gtest_prog_name, extra_args, expected_exit_code) private
Returns the xml output generated by running the program gtest_prog_name.
Furthermore, the program's exit code must be expected_exit_code.
Definition at line 263 of file gtest_xml_output_unittest.py.
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._GetXmlOutput(), gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput(), gtest_test_utils.GetTempDir(), and gtest_test_utils.GetTestExecutablePath().
   def _GetXmlOutput(self, gtest_prog_name, extra_args, expected_exit_code):
     """
     Returns the xml output generated by running the program gtest_prog_name.
     Furthermore, the program's exit code must be expected_exit_code.
     """
     xml_path = os.path.join(gtest_test_utils.GetTempDir(),
                             gtest_prog_name + 'out.xml')
     gtest_prog_path = gtest_test_utils.GetTestExecutablePath(gtest_prog_name)
     command = ([gtest_prog_path, '%s=xml:%s' % (GTEST_OUTPUT_FLAG, xml_path)] +
                extra_args)
     p = gtest_test_utils.Subprocess(command)
     if p.terminated_by_signal:
       self.assert_(False,
                    '%s was killed by signal %d' % (gtest_prog_name, p.signal))
     else:
       self.assert_(p.exited)
       self.assertEquals(expected_exit_code, p.exit_code,
                         "'%s' exited with code %s, which doesn't match "
                         'the expected exit code %s.'
                         % (command, p.exit_code, expected_exit_code))
     actual = minidom.parse(xml_path)
     return actual
def gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput (self, gtest_prog_name, expected_xml, expected_exit_code, extra_args = None) private
Asserts that the XML document generated by running the program
gtest_prog_name matches expected_xml, a string containing another
XML document.  Furthermore, the program's exit code must be
expected_exit_code.
Definition at line 288 of file gtest_xml_output_unittest.py.
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._GetXmlOutput(), gtest_xml_test_utils.GTestXMLTestCase.AssertEquivalentNodes(), gtest_test_utils.Main(), and gtest_xml_test_utils.GTestXMLTestCase.NormalizeXml().
                      expected_exit_code, extra_args=None):
     """
     Asserts that the XML document generated by running the program
     gtest_prog_name matches expected_xml, a string containing another
     XML document.  Furthermore, the program's exit code must be
     expected_exit_code.
     """
     actual = self._GetXmlOutput(gtest_prog_name, extra_args or [],
                                 expected_exit_code)
     expected = minidom.parseString(expected_xml)
     self.NormalizeXml(actual.documentElement)
     self.AssertEquivalentNodes(expected.documentElement,
                                actual.documentElement)
     expected.unlink()
     actual.unlink()
def gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput (self, gtest_prog_name, expected_xml, expected_exit_code, extra_args = None) private
Asserts that the XML document generated by running the program
gtest_prog_name matches expected_xml, a string containing another
XML document.  Furthermore, the program's exit code must be
expected_exit_code.
Definition at line 288 of file gtest_xml_output_unittest.py.
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._GetXmlOutput(), gtest_xml_test_utils.GTestXMLTestCase.AssertEquivalentNodes(), gtest_test_utils.Main(), and gtest_xml_test_utils.GTestXMLTestCase.NormalizeXml().
Referenced by gtest_xml_output_unittest.GTestXMLOutputUnitTest._GetXmlOutput(), gtest_xml_output_unittest.GTestXMLOutputUnitTest.testEmptyXmlOutput(), gtest_xml_output_unittest.GTestXMLOutputUnitTest.testFilteredTestXmlOutput(), and gtest_xml_output_unittest.GTestXMLOutputUnitTest.testNonEmptyXmlOutput().
                      expected_exit_code, extra_args=None):
     """
     Asserts that the XML document generated by running the program
     gtest_prog_name matches expected_xml, a string containing another
     XML document.  Furthermore, the program's exit code must be
     expected_exit_code.
     """
     actual = self._GetXmlOutput(gtest_prog_name, extra_args or [],
                                 expected_exit_code)
     expected = minidom.parseString(expected_xml)
     self.NormalizeXml(actual.documentElement)
     self.AssertEquivalentNodes(expected.documentElement,
                                actual.documentElement)
     expected.unlink()
     actual.unlink()
def gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput (self, gtest_prog_name, expected_xml, expected_exit_code, extra_args = None) private
Asserts that the XML document generated by running the program
gtest_prog_name matches expected_xml, a string containing another
XML document.  Furthermore, the program's exit code must be
expected_exit_code.
Definition at line 288 of file gtest_xml_output_unittest.py.
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._GetXmlOutput(), gtest_xml_test_utils.GTestXMLTestCase.AssertEquivalentNodes(), gtest_test_utils.Main(), and gtest_xml_test_utils.GTestXMLTestCase.NormalizeXml().
                      expected_exit_code, extra_args=None):
     """
     Asserts that the XML document generated by running the program
     gtest_prog_name matches expected_xml, a string containing another
     XML document.  Furthermore, the program's exit code must be
     expected_exit_code.
     """
     actual = self._GetXmlOutput(gtest_prog_name, extra_args or [],
                                 expected_exit_code)
     expected = minidom.parseString(expected_xml)
     self.NormalizeXml(actual.documentElement)
     self.AssertEquivalentNodes(expected.documentElement,
                                actual.documentElement)
     expected.unlink()
     actual.unlink()
def gtest_xml_output_unittest.GTestXMLOutputUnitTest.testDefaultOutputFile (self)
Confirms that Google Test produces an XML output file with the expected
default name if no name is explicitly specified.
Definition at line 201 of file gtest_xml_output_unittest.py.
References gtest_test_utils.GetTempDir(), gtest_test_utils.GetTestExecutablePath(), and gtest_xml_output_unittest.GTestXMLOutputUnitTest.testDefaultOutputFile().
   def testDefaultOutputFile(self):
     """
     Confirms that Google Test produces an XML output file with the expected
     default name if no name is explicitly specified.
     """
     output_file = os.path.join(gtest_test_utils.GetTempDir(),
                                GTEST_DEFAULT_OUTPUT_FILE)
     gtest_prog_path = gtest_test_utils.GetTestExecutablePath(
         'gtest_no_test_unittest')
     try:
       os.remove(output_file)
     except OSError:
       e = sys.exc_info()[1]
       if e.errno != errno.ENOENT:
         raise
     p = gtest_test_utils.Subprocess(
         [gtest_prog_path, '%s=xml' % GTEST_OUTPUT_FLAG],
         working_dir=gtest_test_utils.GetTempDir())
     self.assert_(p.exited)
     self.assertEquals(0, p.exit_code)
     self.assert_(os.path.isfile(output_file))
def gtest_xml_output_unittest.GTestXMLOutputUnitTest.testDefaultOutputFile (self)
Confirms that Google Test produces an XML output file with the expected
default name if no name is explicitly specified.
Definition at line 201 of file gtest_xml_output_unittest.py.
References gtest_test_utils.GetTempDir(), gtest_test_utils.GetTestExecutablePath(), and gtest_xml_output_unittest.GTestXMLOutputUnitTest.testDefaultOutputFile().
   def testDefaultOutputFile(self):
     """
     Confirms that Google Test produces an XML output file with the expected
     default name if no name is explicitly specified.
     """
     output_file = os.path.join(gtest_test_utils.GetTempDir(),
                                GTEST_DEFAULT_OUTPUT_FILE)
     gtest_prog_path = gtest_test_utils.GetTestExecutablePath(
         'gtest_no_test_unittest')
     try:
       os.remove(output_file)
     except OSError:
       e = sys.exc_info()[1]
       if e.errno != errno.ENOENT:
         raise
     p = gtest_test_utils.Subprocess(
         [gtest_prog_path, '%s=xml' % GTEST_OUTPUT_FLAG],
         working_dir=gtest_test_utils.GetTempDir())
     self.assert_(p.exited)
     self.assertEquals(0, p.exit_code)
     self.assert_(os.path.isfile(output_file))
def gtest_xml_output_unittest.GTestXMLOutputUnitTest.testDefaultOutputFile (self)
Confirms that Google Test produces an XML output file with the expected
default name if no name is explicitly specified.
Definition at line 201 of file gtest_xml_output_unittest.py.
References gtest_test_utils.GetTempDir(), and gtest_test_utils.GetTestExecutablePath().
Referenced by gtest_xml_output_unittest.GTestXMLOutputUnitTest.testDefaultOutputFile().
   def testDefaultOutputFile(self):
     """
     Confirms that Google Test produces an XML output file with the expected
     default name if no name is explicitly specified.
     """
     output_file = os.path.join(gtest_test_utils.GetTempDir(),
                                GTEST_DEFAULT_OUTPUT_FILE)
     gtest_prog_path = gtest_test_utils.GetTestExecutablePath(
         'gtest_no_test_unittest')
     try:
       os.remove(output_file)
     except OSError:
       e = sys.exc_info()[1]
       if e.errno != errno.ENOENT:
         raise
     p = gtest_test_utils.Subprocess(
         [gtest_prog_path, '%s=xml' % GTEST_OUTPUT_FLAG],
         working_dir=gtest_test_utils.GetTempDir())
     self.assert_(p.exited)
     self.assertEquals(0, p.exit_code)
     self.assert_(os.path.isfile(output_file))
def gtest_xml_output_unittest.GTestXMLOutputUnitTest.testEmptyXmlOutput (self)
Verifies XML output for a Google Test binary without actual tests.
Runs a test program that generates an empty XML output, and
tests that the XML output is expected.
Definition at line 167 of file gtest_xml_output_unittest.py.
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput().
Referenced by gtest_xml_output_unittest.GTestXMLOutputUnitTest.testEmptyXmlOutput().
   def testEmptyXmlOutput(self):
     """Verifies XML output for a Google Test binary without actual tests.
     Runs a test program that generates an empty XML output, and
     tests that the XML output is expected.
     """
     self._TestXmlOutput('gtest_no_test_unittest', EXPECTED_EMPTY_XML, 0)
def gtest_xml_output_unittest.GTestXMLOutputUnitTest.testEmptyXmlOutput (self)
Verifies XML output for a Google Test binary without actual tests.
Runs a test program that generates an empty XML output, and
tests that the XML output is expected.
Definition at line 167 of file gtest_xml_output_unittest.py.
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput(), and gtest_xml_output_unittest.GTestXMLOutputUnitTest.testEmptyXmlOutput().
   def testEmptyXmlOutput(self):
     """Verifies XML output for a Google Test binary without actual tests.
     Runs a test program that generates an empty XML output, and
     tests that the XML output is expected.
     """
     self._TestXmlOutput('gtest_no_test_unittest', EXPECTED_EMPTY_XML, 0)
def gtest_xml_output_unittest.GTestXMLOutputUnitTest.testEmptyXmlOutput (self)
Verifies XML output for a Google Test binary without actual tests.
Runs a test program that generates an empty XML output, and
tests that the XML output is expected.
Definition at line 167 of file gtest_xml_output_unittest.py.
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput(), and gtest_xml_output_unittest.GTestXMLOutputUnitTest.testEmptyXmlOutput().
   def testEmptyXmlOutput(self):
     """Verifies XML output for a Google Test binary without actual tests.
     Runs a test program that generates an empty XML output, and
     tests that the XML output is expected.
     """
     self._TestXmlOutput('gtest_no_test_unittest', EXPECTED_EMPTY_XML, 0)
def gtest_xml_output_unittest.GTestXMLOutputUnitTest.testFilteredTestXmlOutput (self)
Verifies XML output when a filter is applied.
Runs a test program that executes only some tests and verifies that
non-selected tests do not show up in the XML output.
Definition at line 253 of file gtest_xml_output_unittest.py.
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput().
Referenced by gtest_xml_output_unittest.GTestXMLOutputUnitTest.testFilteredTestXmlOutput().
   def testFilteredTestXmlOutput(self):
     """Verifies XML output when a filter is applied.
     Runs a test program that executes only some tests and verifies that
     non-selected tests do not show up in the XML output.
     """
     self._TestXmlOutput(GTEST_PROGRAM_NAME, EXPECTED_FILTERED_TEST_XML, 0,
                         extra_args=['%s=SuccessfulTest.*' % GTEST_FILTER_FLAG])
def gtest_xml_output_unittest.GTestXMLOutputUnitTest.testFilteredTestXmlOutput (self)
Verifies XML output when a filter is applied.
Runs a test program that executes only some tests and verifies that
non-selected tests do not show up in the XML output.
Definition at line 253 of file gtest_xml_output_unittest.py.
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput(), and gtest_xml_output_unittest.GTestXMLOutputUnitTest.testFilteredTestXmlOutput().
   def testFilteredTestXmlOutput(self):
     """Verifies XML output when a filter is applied.
     Runs a test program that executes only some tests and verifies that
     non-selected tests do not show up in the XML output.
     """
     self._TestXmlOutput(GTEST_PROGRAM_NAME, EXPECTED_FILTERED_TEST_XML, 0,
                         extra_args=['%s=SuccessfulTest.*' % GTEST_FILTER_FLAG])
def gtest_xml_output_unittest.GTestXMLOutputUnitTest.testFilteredTestXmlOutput (self)
Verifies XML output when a filter is applied.
Runs a test program that executes only some tests and verifies that
non-selected tests do not show up in the XML output.
Definition at line 253 of file gtest_xml_output_unittest.py.
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput(), and gtest_xml_output_unittest.GTestXMLOutputUnitTest.testFilteredTestXmlOutput().
   def testFilteredTestXmlOutput(self):
     """Verifies XML output when a filter is applied.
     Runs a test program that executes only some tests and verifies that
     non-selected tests do not show up in the XML output.
     """
     self._TestXmlOutput(GTEST_PROGRAM_NAME, EXPECTED_FILTERED_TEST_XML, 0,
                         extra_args=['%s=SuccessfulTest.*' % GTEST_FILTER_FLAG])
def gtest_xml_output_unittest.GTestXMLOutputUnitTest.testNonEmptyXmlOutput (self)
Runs a test program that generates a non-empty XML output, and
tests that the XML output is expected.
Definition at line 160 of file gtest_xml_output_unittest.py.
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput().
Referenced by gtest_xml_output_unittest.GTestXMLOutputUnitTest.testNonEmptyXmlOutput().
     def testNonEmptyXmlOutput(self):
       """
       Runs a test program that generates a non-empty XML output, and
       tests that the XML output is expected.
       """
       self._TestXmlOutput(GTEST_PROGRAM_NAME, EXPECTED_NON_EMPTY_XML, 1)
def gtest_xml_output_unittest.GTestXMLOutputUnitTest.testNonEmptyXmlOutput (self)
Runs a test program that generates a non-empty XML output, and
tests that the XML output is expected.
Definition at line 160 of file gtest_xml_output_unittest.py.
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput(), and gtest_xml_output_unittest.GTestXMLOutputUnitTest.testNonEmptyXmlOutput().
     def testNonEmptyXmlOutput(self):
       """
       Runs a test program that generates a non-empty XML output, and
       tests that the XML output is expected.
       """
       self._TestXmlOutput(GTEST_PROGRAM_NAME, EXPECTED_NON_EMPTY_XML, 1)
def gtest_xml_output_unittest.GTestXMLOutputUnitTest.testNonEmptyXmlOutput (self)
Runs a test program that generates a non-empty XML output, and
tests that the XML output is expected.
Definition at line 160 of file gtest_xml_output_unittest.py.
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput(), and gtest_xml_output_unittest.GTestXMLOutputUnitTest.testNonEmptyXmlOutput().
     def testNonEmptyXmlOutput(self):
       """
       Runs a test program that generates a non-empty XML output, and
       tests that the XML output is expected.
       """
       self._TestXmlOutput(GTEST_PROGRAM_NAME, EXPECTED_NON_EMPTY_XML, 1)
def gtest_xml_output_unittest.GTestXMLOutputUnitTest.testSuppressedXmlOutput (self)
Tests that no XML file is generated if the default XML listener is
shut down before RUN_ALL_TESTS is invoked.
Definition at line 224 of file gtest_xml_output_unittest.py.
References gtest_test_utils.GetTempDir(), and gtest_xml_output_unittest.GTestXMLOutputUnitTest.testSuppressedXmlOutput().
   def testSuppressedXmlOutput(self):
     """
     Tests that no XML file is generated if the default XML listener is
     shut down before RUN_ALL_TESTS is invoked.
     """
     xml_path = os.path.join(gtest_test_utils.GetTempDir(),
                             GTEST_PROGRAM_NAME + 'out.xml')
     if os.path.isfile(xml_path):
       os.remove(xml_path)
     command = [GTEST_PROGRAM_PATH,
                '%s=xml:%s' % (GTEST_OUTPUT_FLAG, xml_path),
                '--shut_down_xml']
     p = gtest_test_utils.Subprocess(command)
     if p.terminated_by_signal:
       # p.signal is avalable only if p.terminated_by_signal is True.
       self.assertFalse(
           p.terminated_by_signal,
           '%s was killed by signal %d' % (GTEST_PROGRAM_NAME, p.signal))
     else:
       self.assert_(p.exited)
       self.assertEquals(1, p.exit_code,
                         "'%s' exited with code %s, which doesn't match "
                         'the expected exit code %s.'
                         % (command, p.exit_code, 1))
     self.assert_(not os.path.isfile(xml_path))
def gtest_xml_output_unittest.GTestXMLOutputUnitTest.testSuppressedXmlOutput (self)
Tests that no XML file is generated if the default XML listener is
shut down before RUN_ALL_TESTS is invoked.
Definition at line 224 of file gtest_xml_output_unittest.py.
References gtest_test_utils.GetTempDir(), and gtest_xml_output_unittest.GTestXMLOutputUnitTest.testSuppressedXmlOutput().
   def testSuppressedXmlOutput(self):
     """
     Tests that no XML file is generated if the default XML listener is
     shut down before RUN_ALL_TESTS is invoked.
     """
     xml_path = os.path.join(gtest_test_utils.GetTempDir(),
                             GTEST_PROGRAM_NAME + 'out.xml')
     if os.path.isfile(xml_path):
       os.remove(xml_path)
     command = [GTEST_PROGRAM_PATH,
                '%s=xml:%s' % (GTEST_OUTPUT_FLAG, xml_path),
                '--shut_down_xml']
     p = gtest_test_utils.Subprocess(command)
     if p.terminated_by_signal:
       # p.signal is avalable only if p.terminated_by_signal is True.
       self.assertFalse(
           p.terminated_by_signal,
           '%s was killed by signal %d' % (GTEST_PROGRAM_NAME, p.signal))
     else:
       self.assert_(p.exited)
       self.assertEquals(1, p.exit_code,
                         "'%s' exited with code %s, which doesn't match "
                         'the expected exit code %s.'
                         % (command, p.exit_code, 1))
     self.assert_(not os.path.isfile(xml_path))
def gtest_xml_output_unittest.GTestXMLOutputUnitTest.testSuppressedXmlOutput (self)
Tests that no XML file is generated if the default XML listener is
shut down before RUN_ALL_TESTS is invoked.
Definition at line 224 of file gtest_xml_output_unittest.py.
References gtest_test_utils.GetTempDir().
Referenced by gtest_xml_output_unittest.GTestXMLOutputUnitTest.testSuppressedXmlOutput().
   def testSuppressedXmlOutput(self):
     """
     Tests that no XML file is generated if the default XML listener is
     shut down before RUN_ALL_TESTS is invoked.
     """
     xml_path = os.path.join(gtest_test_utils.GetTempDir(),
                             GTEST_PROGRAM_NAME + 'out.xml')
     if os.path.isfile(xml_path):
       os.remove(xml_path)
     command = [GTEST_PROGRAM_PATH,
                '%s=xml:%s' % (GTEST_OUTPUT_FLAG, xml_path),
                '--shut_down_xml']
     p = gtest_test_utils.Subprocess(command)
     if p.terminated_by_signal:
       # p.signal is avalable only if p.terminated_by_signal is True.
       self.assertFalse(
           p.terminated_by_signal,
           '%s was killed by signal %d' % (GTEST_PROGRAM_NAME, p.signal))
     else:
       self.assert_(p.exited)
       self.assertEquals(1, p.exit_code,
                         "'%s' exited with code %s, which doesn't match "
                         'the expected exit code %s.'
                         % (command, p.exit_code, 1))
     self.assert_(not os.path.isfile(xml_path))
def gtest_xml_output_unittest.GTestXMLOutputUnitTest.testTimestampValue (self)
Checks whether the timestamp attribute in the XML output is valid.
Runs a test program that generates an empty XML output, and checks if
the timestamp attribute in the testsuites tag is valid.
Definition at line 176 of file gtest_xml_output_unittest.py.
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._GetXmlOutput(), and gtest_xml_output_unittest.GTestXMLOutputUnitTest.testTimestampValue().
   def testTimestampValue(self):
     """Checks whether the timestamp attribute in the XML output is valid.
     Runs a test program that generates an empty XML output, and checks if
     the timestamp attribute in the testsuites tag is valid.
     """
     actual = self._GetXmlOutput('gtest_no_test_unittest', [], 0)
     date_time_str = actual.documentElement.getAttributeNode('timestamp').value
     # datetime.strptime() is only available in Python 2.5+ so we have to
     # parse the expected datetime manually.
     match = re.match(r'(\d+)-(\d\d)-(\d\d)T(\d\d):(\d\d):(\d\d)', date_time_str)
     self.assertTrue(
         re.match,
         'XML datettime string %s has incorrect format' % date_time_str)
     date_time_from_xml = datetime.datetime(
         year=int(match.group(1)), month=int(match.group(2)),
         day=int(match.group(3)), hour=int(match.group(4)),
         minute=int(match.group(5)), second=int(match.group(6)))
     time_delta = abs(datetime.datetime.now() - date_time_from_xml)
     # timestamp value should be near the current local time
     self.assertTrue(time_delta < datetime.timedelta(seconds=600),
                     'time_delta is %s' % time_delta)
     actual.unlink()
def gtest_xml_output_unittest.GTestXMLOutputUnitTest.testTimestampValue (self)
Checks whether the timestamp attribute in the XML output is valid.
Runs a test program that generates an empty XML output, and checks if
the timestamp attribute in the testsuites tag is valid.
Definition at line 176 of file gtest_xml_output_unittest.py.
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._GetXmlOutput().
Referenced by gtest_xml_output_unittest.GTestXMLOutputUnitTest.testTimestampValue().
   def testTimestampValue(self):
     """Checks whether the timestamp attribute in the XML output is valid.
     Runs a test program that generates an empty XML output, and checks if
     the timestamp attribute in the testsuites tag is valid.
     """
     actual = self._GetXmlOutput('gtest_no_test_unittest', [], 0)
     date_time_str = actual.documentElement.getAttributeNode('timestamp').value
     # datetime.strptime() is only available in Python 2.5+ so we have to
     # parse the expected datetime manually.
     match = re.match(r'(\d+)-(\d\d)-(\d\d)T(\d\d):(\d\d):(\d\d)', date_time_str)
     self.assertTrue(
         re.match,
         'XML datettime string %s has incorrect format' % date_time_str)
     date_time_from_xml = datetime.datetime(
         year=int(match.group(1)), month=int(match.group(2)),
         day=int(match.group(3)), hour=int(match.group(4)),
         minute=int(match.group(5)), second=int(match.group(6)))
     time_delta = abs(datetime.datetime.now() - date_time_from_xml)
     # timestamp value should be near the current local time
     self.assertTrue(time_delta < datetime.timedelta(seconds=600),
                     'time_delta is %s' % time_delta)
     actual.unlink()
def gtest_xml_output_unittest.GTestXMLOutputUnitTest.testTimestampValue (self)
Checks whether the timestamp attribute in the XML output is valid.
Runs a test program that generates an empty XML output, and checks if
the timestamp attribute in the testsuites tag is valid.
Definition at line 176 of file gtest_xml_output_unittest.py.
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._GetXmlOutput(), and gtest_xml_output_unittest.GTestXMLOutputUnitTest.testTimestampValue().
   def testTimestampValue(self):
     """Checks whether the timestamp attribute in the XML output is valid.
     Runs a test program that generates an empty XML output, and checks if
     the timestamp attribute in the testsuites tag is valid.
     """
     actual = self._GetXmlOutput('gtest_no_test_unittest', [], 0)
     date_time_str = actual.documentElement.getAttributeNode('timestamp').value
     # datetime.strptime() is only available in Python 2.5+ so we have to
     # parse the expected datetime manually.
     match = re.match(r'(\d+)-(\d\d)-(\d\d)T(\d\d):(\d\d):(\d\d)', date_time_str)
     self.assertTrue(
         re.match,
         'XML datettime string %s has incorrect format' % date_time_str)
     date_time_from_xml = datetime.datetime(
         year=int(match.group(1)), month=int(match.group(2)),
         day=int(match.group(3)), hour=int(match.group(4)),
         minute=int(match.group(5)), second=int(match.group(6)))
     time_delta = abs(datetime.datetime.now() - date_time_from_xml)
     # timestamp value should be near the current local time
     self.assertTrue(time_delta < datetime.timedelta(seconds=600),
                     'time_delta is %s' % time_delta)
     actual.unlink()
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest_xml_output_unittest.py