proxygen: folly::futures::detail::Core< T > Class Template Reference
folly::futures::detail::Core< T > Class Template Reference final
#include <Core.h>
Classes
class CoreAndCallbackReference
Public Types
using Result = Try< T >
using Callback = folly::Function< void(Result &&)>
Public Member Functions
Core (Core const &)=delete
Core & operator= (Core const &)=delete
Core (Core &&) noexcept=delete
Core & operator= (Core &&)=delete
bool hasCallback () const noexcept
May call from any thread.
bool hasResult () const noexcept
bool ready () const noexcept
Try< T > & getTry ()
Try< T > const & getTry () const
template<typename F >
void setCallback (F &&func, std::shared_ptr< folly::RequestContext > context)
void setProxy (Core *proxy)
void setResult (Try< T > &&t)
void detachFuture () noexcept
void detachPromise () noexcept
void setExecutor (Executor::KeepAlive<> x, int8_t priority=Executor::MID_PRI)
void setExecutor (Executor *x, int8_t priority=Executor::MID_PRI)
Executor * getExecutor () const
int8_t getPriority () const
void raise (exception_wrapper e)
std::function< void(exception_wrapper const &)> getInterruptHandler ()
template<typename F >
void setInterruptHandler (F &&fn)
void setInterruptHandlerNoLock (std::function< void(exception_wrapper const &)> fn)
Static Public Member Functions
static Core * make ()
State will be Start.
static Core * make (Try< T > &&t)
template<typename... Args>
static Core< T > * make (in_place_t, Args &&...args)
Private Types
using Context = std::shared_ptr< RequestContext >
Private Member Functions
Core ()
Core (Try< T > &&t)
template<typename... Args>
Core (in_place_t, Args &&...args) noexcept(std::is_nothrow_constructible< T, Args &&... >::value)
~Core ()
void doCallback ()
void proxyCallback ()
void detachOne () noexcept
void derefCallback () noexcept
Private Attributes
union {
Callback callback_
};
union {
Result result_
Core * proxy_
};
std::atomic< State > state_
std::atomic< unsigned char > attached_
std::atomic< unsigned char > callbackReferences_ {0}
std::atomic< bool > interruptHandlerSet_ {false}
SpinLock interruptLock_
int8_t priority_ {-1}
Executor::KeepAlive executor_
union {
Context context_
};
std::unique_ptr< exception_wrapper > interrupt_ {}
std::function< void(exception_wrapper const &)> interruptHandler_ {nullptr}
Detailed Description
template<typename T>
class folly::futures::detail::Core< T >
The shared state object for Future and Promise.
Nomenclature:
"result": a Try object which, when set, contains a T or exception.
"move-out the result": used to mean the Try object and/or its contents are moved-out by a move-constructor or move-assignment. After the result is set, Core itself never modifies (including moving out) the result; however the docs refer to both since caller-code can move-out the result implicitly (see below for examples) whereas other types of modifications are more explicit in the caller code.
"callback": a function provided by the future which Core may invoke. The thread in which the callback is invoked depends on the executor; if there is no executor or an inline executor the thread-choice depends on timing.
"executor": an object which may in the future invoke a provided function (some executors may, as a matter of policy, simply destroy provided functions without executing them).
"consumer thread": the thread which currently owns the Future and which may provide the callback and/or the interrupt.
"producer thread": the thread which owns the Future and which may provide the result and which may provide the interrupt handler.
"interrupt": if provided, an object managed by (if non-empty) exception_wrapper.
"interrupt handler": if provided, a function-object passed to promise.setInterruptHandler(). Core invokes the interrupt handler with the interrupt when both are provided (and, best effort, if there is not yet any result).
Core holds three sets of data, each of which is concurrency-controlled:
The primary producer-to-consumer info-flow: this info includes the result, callback, executor, and a priority for running the callback. Management of and concurrency control for this info is by an FSM based on enum class State. All state transitions are atomic; other producer-to-consumer data is sometimes modified within those transitions; see below for details.
The consumer-to-producer interrupt-request flow: this info includes an interrupt-handler and an interrupt. Concurrency of this info is controlled by a Spin Lock (interruptLock_).
Lifetime control info: this includes two reference counts, both which are internally synchronized (atomic).
The FSM to manage the primary producer-to-consumer info-flow has these allowed (atomic) transitions:
+-------------------------------------------------------------—+ | —> OnlyResult --— | | / \ | | (setResult()) (setCallback()) | | / \ | | Start ------—> ---—> Done | | \ \ / | | \ (setCallback()) (setResult()) | | \ \ / | | \ —> OnlyCallback — | | \ \ | | (setProxy()) (setProxy()) | | \ \ | | \ ---—> Empty | | \ / | | \ (setCallback()) | | \ / | | ------—> Proxy -------— | +-------------------------------------------------------------—+
States and the corresponding producer-to-consumer data status & ownership:
Start: has neither result nor callback. While in this state, the producer thread may set the result (setResult()) or the consumer thread may set the callback (setCallback()).
OnlyResult: producer thread has set the result and must never access it. The result is logically owned by, and possibly modified or moved-out by, the consumer thread. Callers of the future object can do arbitrary modifications, including moving-out, via continuations or via non-const and/or rvalue-qualified future.result(), future.value(), etc. Future/SemiFuture proper also move-out the result in some cases, e.g., in wait(), get(), when passing through values or results from core to core, as then-value and then-error, etc.
OnlyCallback: consumer thread has set a callback/continuation. From this point forward only the producer thread can safely access that callback (see setResult() and doCallback() where the producer thread can both read and modify the callback).
Proxy: producer thread has set a proxy core which the callback should be proxied to.
Done: callback can be safely accessed only within doCallback(), which gets called on exactly one thread exactly once just after the transition to Done. The future object will have determined whether that callback has/will move-out the result, but either way the result remains logically owned exclusively by the consumer thread (the code of Future/SemiFuture, of the continuation, and/or of callers of future.result(), etc.).
Empty: the core successfully proxied the callback and is now empty.
Start state:
Start: e.g., Core<X>::make().
(See also Core<X>::make(x) which logically transitions Start => OnlyResult within the underlying constructor.)
Terminal states:
OnlyResult: a terminal state when a callback is never attached, and also sometimes when a callback is provided, e.g., sometimes when future.wait() and/or future.get() are used.
Done: a terminal state when future.then() is used, and sometimes also when future.wait() and/or future.get() are used.
Proxy: a terminal state if proxy core was set, but callback was never set.
Empty: a terminal state when proxying a callback was successful.
Notes and caveats:
Unfortunately, there are things that users can do to break concurrency and we can't detect that. However users should be ok if they follow move semantics religiously wrt threading.
Futures and/or Promises can and usually will migrate between threads, though this usually happens within the API code. For example, an async operation will probably make a promise-future pair (see overloads of makePromiseContract()), then move the Promise into another thread that will eventually fulfill it.
Things get slightly more complicated with executors and via, but the principle is the same.
In general, as long as the user doesn't access a future or promise object from more than one thread at a time there won't be any problems.
Definition at line 195 of file Core.h.
Member Typedef Documentation
template<typename T> using folly::futures::detail::Core< T >::Callback = folly::Function<void(Result&&)>
Definition at line 202 of file Core.h.
template<typename T> using folly::futures::detail::Core< T >::Context = std::shared_ptr<RequestContext> private
Definition at line 659 of file Core.h.
template<typename T> using folly::futures::detail::Core< T >::Result = Try<T>
Definition at line 201 of file Core.h.
Constructor & Destructor Documentation
template<typename T> folly::futures::detail::Core< T >::Core (Core< T > const &) delete
template<typename T> folly::futures::detail::Core< T >::Core (Core< T > &&) delete noexcept
template<typename T> folly::futures::detail::Core< T >::Core () inline private
Definition at line 501 of file Core.h.
 : state_(State::Start), attached_(2) {}
template<typename T> folly::futures::detail::Core< T >::Core (Try< T > && t) inline explicit private
Definition at line 503 of file Core.h.
References testing::Args().
       : result_(std::move(t)), state_(State::OnlyResult), attached_(1) {}
template<typename T> template<typename... Args> folly::futures::detail::Core< T >::Core (in_place_t , Args &&... args) inline explicit private noexcept
Definition at line 507 of file Core.h.
       : result_(in_place, std::forward<Args>(args)...),
         state_(State::OnlyResult),
         attached_(1) {}
template<typename T> folly::futures::detail::Core< T >::~Core () inline private
Definition at line 513 of file Core.h.
References folly::futures::detail::Done, folly::futures::detail::Empty, FOLLY_FALLTHROUGH, folly::futures::detail::OnlyResult, and folly::futures::detail::Proxy.
           {
     DCHECK(attached_ == 0);
     auto state = state_.load(std::memory_order_relaxed);
     switch (state) {
       case State::OnlyResult:
         FOLLY_FALLTHROUGH;
       case State::Done:
         result_.~Result();
         break;
       case State::Proxy:
         proxy_->detachFuture();
         break;
       case State::Empty:
         break;
       default:
         terminate_with<std::logic_error>("~Core unexpected state");
     }
   }
Member Function Documentation
template<typename T> void folly::futures::detail::Core< T >::derefCallback () inline private noexcept
Definition at line 650 of file Core.h.
References c, and callback_.
{
     auto c = callbackReferences_.fetch_sub(1, std::memory_order_acq_rel);
     assert(c >= 1);
     if (c == 1) {
       context_.~Context();
       callback_.~Callback();
     }
   }
template<typename T> void folly::futures::detail::Core< T >::detachFuture () inline noexcept
Called by a destructing Future (in the consumer thread, by definition). Calls delete this if there are no more references to this (including if detachPromise() is called previously or concurrently).
Definition at line 409 of file Core.h.
Referenced by folly::futures::detail::FutureBase< T >::detach(), and folly::Promise< T >::detach().
{
     detachOne();
   }
template<typename T> void folly::futures::detail::Core< T >::detachOne () inline private noexcept
Definition at line 642 of file Core.h.
References a.
{
     auto a = attached_.fetch_sub(1, std::memory_order_acq_rel);
     assert(a >= 1);
     if (a == 1) {
       delete this;
     }
   }
template<typename T> void folly::futures::detail::Core< T >::detachPromise () inline noexcept
Called by a destructing Promise (in the producer thread, by definition). Calls delete this if there are no more references to this (including if detachFuture() is called previously or concurrently).
Definition at line 416 of file Core.h.
Referenced by folly::futures::detail::coreDetachPromiseMaybeWithResult().
{
     DCHECK(hasResult());
     detachOne();
   }
template<typename T> void folly::futures::detail::Core< T >::doCallback () inline private
Definition at line 570 of file Core.h.
References callback_, folly::futures::detail::Core< T >::callback_, folly::futures::detail::Core< T >::context_, folly::futures::detail::Done, folly::exchange(), int8_t, LIKELY, folly::gen::move, folly::futures::detail::Core< T >::result_, and SCOPE_EXIT.
                     {
     DCHECK(state_ == State::Done);
     auto x = exchange(executor_, Executor::KeepAlive<>());
     int8_t priority = priority_;
     if (x) {
       exception_wrapper ew;
       // We need to reset `callback_` after it was executed (which can happen
       // through the executor or, if `Executor::add` throws, below). The
       // executor might discard the function without executing it (now or
       // later), in which case `callback_` also needs to be reset.
       // The `Core` has to be kept alive throughout that time, too. Hence we
       // increment `attached_` and `callbackReferences_` by two, and construct
       // exactly two `CoreAndCallbackReference` objects, which call
       // `derefCallback` and `detachOne` in their destructor. One will guard
       // this scope, the other one will guard the lambda passed to the executor.
       attached_.fetch_add(2, std::memory_order_relaxed);
       callbackReferences_.fetch_add(2, std::memory_order_relaxed);
       CoreAndCallbackReference guard_local_scope(this);
       CoreAndCallbackReference guard_lambda(this);
       try {
         auto xPtr = x.get();
         if (LIKELY(x->getNumPriorities() == 1)) {
           xPtr->add([core_ref = std::move(guard_lambda),
                      keepAlive = std::move(x)]() mutable {
             auto cr = std::move(core_ref);
             Core* const core = cr.getCore();
             RequestContextScopeGuard rctx(core->context_);
             core->callback_(std::move(core->result_));
           });
         } else {
           xPtr->addWithPriority(
               [core_ref = std::move(guard_lambda),
                keepAlive = std::move(x)]() mutable {
                 auto cr = std::move(core_ref);
                 Core* const core = cr.getCore();
                 RequestContextScopeGuard rctx(core->context_);
                 core->callback_(std::move(core->result_));
               },
               priority);
         }
       } catch (const std::exception& e) {
         ew = exception_wrapper(std::current_exception(), e);
       } catch (...) {
         ew = exception_wrapper(std::current_exception());
       }
       if (ew) {
         RequestContextScopeGuard rctx(context_);
         result_ = Try<T>(std::move(ew));
         callback_(std::move(result_));
       }
     } else {
       attached_.fetch_add(1, std::memory_order_relaxed);
       SCOPE_EXIT {
         context_.~Context();
         callback_.~Callback();
         detachOne();
       };
       RequestContextScopeGuard rctx(context_);
       callback_(std::move(result_));
     }
   }
template<typename T> Executor* folly::futures::detail::Core< T >::getExecutor () const inline
Definition at line 436 of file Core.h.
Referenced by folly::SemiFuture< T >::releaseDeferredExecutor().
{
     return executor_.get();
   }
template<typename T> std::function<void(exception_wrapper const&)> folly::futures::detail::Core< T >::getInterruptHandler () inline
Definition at line 463 of file Core.h.
References folly::lock().
{
     if (!interruptHandlerSet_.load(std::memory_order_acquire)) {
       return nullptr;
     }
     std::lock_guard<SpinLock> lock(interruptLock_);
     return interruptHandler_;
   }
template<typename T> int8_t folly::futures::detail::Core< T >::getPriority () const inline
Definition at line 440 of file Core.h.
{
     return priority_;
   }
template<typename T> Try<T>& folly::futures::detail::Core< T >::getTry () inline
Call only from consumer thread (since the consumer thread can modify the referenced Try object; see non-const overloads of future.result(), etc., and certain Future-provided callbacks which move-out the result).
Unconditionally returns a reference to the result.
State dependent preconditions:
Start or OnlyCallback: Never safe - do not call. (Access in those states would be undefined behavior since the producer thread can, in those states, asynchronously set the referenced Try object.)
OnlyResult: Always safe. (Though the consumer thread should not use the returned reference after it attaches a callback unless it knows that the callback does not move-out the referenced result.)
Done: Safe but sometimes unusable. (Always returns a valid reference, but the referenced result may or may not have been modified, including possibly moved-out, depending on what the callback did; some but not all callbacks modify (possibly move-out) the result.)
Definition at line 280 of file Core.h.
References folly::futures::detail::Proxy.
                    {
     DCHECK(hasResult());
     auto core = this;
     while (core->state_.load(std::memory_order_relaxed) == State::Proxy) {
       core = core->proxy_;
     }
     return core->result_;
   }
template<typename T> Try<T> const& folly::futures::detail::Core< T >::getTry () const inline
Definition at line 288 of file Core.h.
References folly::futures::detail::Proxy.
{
     DCHECK(hasResult());
     auto core = this;
     while (core->state_.load(std::memory_order_relaxed) == State::Proxy) {
       core = core->proxy_;
     }
     return core->result_;
   }
template<typename T> bool folly::futures::detail::Core< T >::hasCallback () const inline noexcept
May call from any thread.
Definition at line 231 of file Core.h.
References folly::futures::detail::Done, and folly::futures::detail::OnlyCallback.
Referenced by folly::futures::detail::FutureBase< T >::throwIfContinued().
{
     constexpr auto allowed = State::OnlyCallback | State::Done;
     auto const state = state_.load(std::memory_order_acquire);
     return State() != (state & allowed);
   }
template<typename T> bool folly::futures::detail::Core< T >::hasResult () const inline noexcept
May call from any thread
True if state is OnlyResult or Done.
Identical to this->ready()
Definition at line 242 of file Core.h.
References folly::futures::detail::Done, folly::futures::detail::OnlyResult, and folly::futures::detail::Proxy.
Referenced by folly::futures::detail::coreDetachPromiseMaybeWithResult(), folly::Promise< T >::isFulfilled(), and folly::futures::detail::FutureBase< T >::isReady().
{
     constexpr auto allowed = State::OnlyResult | State::Done;
     auto core = this;
     auto state = core->state_.load(std::memory_order_acquire);
     while (state == State::Proxy) {
       core = core->proxy_;
       state = core->state_.load(std::memory_order_acquire);
     }
     return State() != (state & allowed);
   }
template<typename T> static Core* folly::futures::detail::Core< T >::make () inline static
State will be Start.
Definition at line 205 of file Core.h.
Referenced by folly::makeFuture(), and folly::makeSemiFuture().
                       {
     return new Core();
   }
template<typename T> static Core* folly::futures::detail::Core< T >::make (Try< T > && t) inline static
State will be OnlyResult Result held will be move-constructed from t
Definition at line 211 of file Core.h.
References testing::Args(), folly::gen::move, and folly::pushmi::detail::t.
{
     return new Core(std::move(t));
   }
template<typename T> template<typename... Args> static Core<T>* folly::futures::detail::Core< T >::make (in_place_t , Args &&... args) inline static
State will be OnlyResult Result held will be the T constructed from forwarded args
Definition at line 218 of file Core.h.
References folly::in_place(), and folly::pushmi::__adl::noexcept().
{
     return new Core<T>(in_place, std::forward<Args>(args)...);
   }
template<typename T> Core& folly::futures::detail::Core< T >::operator= (Core< T > const &) delete
template<typename T> Core& folly::futures::detail::Core< T >::operator= (Core< T > &&) delete
template<typename T> void folly::futures::detail::Core< T >::proxyCallback () inline private
Definition at line 633 of file Core.h.
References callback_, folly::futures::detail::Empty, and folly::gen::move.
{
     state_.store(State::Empty, std::memory_order_relaxed);
     proxy_->setExecutor(std::move(executor_), priority_);
     proxy_->setCallback(std::move(callback_), std::move(context_));
     proxy_->detachFuture();
     context_.~Context();
     callback_.~Callback();
   }
template<typename T> void folly::futures::detail::Core< T >::raise (exception_wrapper e) inline
Call only from consumer thread
Eventual effect is to pass e to the Promise's interrupt handler, either synchronously within this call or asynchronously within setInterruptHandler(), depending on which happens first (a coin-toss if the two calls are racing).
Has no effect if it was called previously. Has no effect if State is OnlyResult or Done.
Definition at line 453 of file Core.h.
References folly::lock(), and folly::gen::move.
Referenced by folly::futures::detail::FutureBase< T >::raise().
{
     std::lock_guard<SpinLock> lock(interruptLock_);
     if (!interrupt_ && !hasResult()) {
       interrupt_ = std::make_unique<exception_wrapper>(std::move(e));
       if (interruptHandler_) {
         interruptHandler_(*interrupt_);
       }
     }
   }
template<typename T> bool folly::futures::detail::Core< T >::ready () const inline noexcept
May call from any thread
True if state is OnlyResult or Done.
Identical to this->hasResult()
Definition at line 258 of file Core.h.
{
     return hasResult();
   }
template<typename T> template<typename F > void folly::futures::detail::Core< T >::setCallback (F && func, std::shared_ptr< folly::RequestContext > context) inline
Call only from consumer thread. Call only once - else undefined behavior.
See FSM graph for allowed transitions.
If it transitions to Done, synchronously initiates a call to the callback, and might also synchronously execute that callback (e.g., if there is no executor or if the executor is inline).
Definition at line 306 of file Core.h.
References folly::assume(), callback_, folly::futures::detail::Done, folly::gen::move, folly::futures::detail::OnlyCallback, folly::futures::detail::OnlyResult, folly::futures::detail::Proxy, and folly::futures::detail::Start.
Referenced by folly::futures::detail::FutureBase< T >::setCallback_().
{
     DCHECK(!hasCallback());
     // construct callback_ first; if that fails, context_ will not leak
     ::new (&callback_) Callback(std::forward<F>(func));
     ::new (&context_) Context(std::move(context));
     auto state = state_.load(std::memory_order_acquire);
     if (state == State::Start) {
       if (state_.compare_exchange_strong(
               state, State::OnlyCallback, std::memory_order_release)) {
         return;
       }
       assume(state == State::OnlyResult || state == State::Proxy);
     }
     if (state == State::OnlyResult) {
       state_.store(State::Done, std::memory_order_relaxed);
       doCallback();
       return;
     }
     if (state == State::Proxy) {
       return proxyCallback();
     }
     terminate_with<std::logic_error>("setCallback unexpected state");
   }
template<typename T> void folly::futures::detail::Core< T >::setExecutor (Executor::KeepAlive<> x, int8_t priority = Executor::MID_PRI) inline
Call only from consumer thread, either before attaching a callback or after the callback has already been invoked, but not concurrently with anything which might trigger invocation of the callback.
Definition at line 424 of file Core.h.
References folly::gen::move, and folly::futures::detail::OnlyCallback.
Referenced by folly::SemiFuture< T >::defer(), folly::SemiFuture< T >::releaseDeferredExecutor(), folly::SemiFuture< T >::stealDeferredExecutor(), and folly::SemiFuture< T >::via().
{
     DCHECK(state_ != State::OnlyCallback);
     executor_ = std::move(x);
     priority_ = priority;
   }
template<typename T> void folly::futures::detail::Core< T >::setExecutor (Executor * x, int8_t priority = Executor::MID_PRI) inline
Definition at line 432 of file Core.h.
References folly::getKeepAliveToken().
{
     setExecutor(getKeepAliveToken(x), priority);
   }
template<typename T> template<typename F > void folly::futures::detail::Core< T >::setInterruptHandler (F && fn) inline
Call only from producer thread
May invoke fn() (passing the interrupt) synchronously within this call (if raise() preceded or perhaps if raise() is called concurrently).
Has no effect if State is OnlyResult or Done.
Note: fn() must not touch resources that are destroyed immediately after setResult() is called. Reason: it is possible for fn() to get called asynchronously (in the consumer thread) after the producer thread calls setResult().
Definition at line 483 of file Core.h.
References folly::as_const(), and folly::lock().
Referenced by folly::Promise< T >::setInterruptHandler().
{
     std::lock_guard<SpinLock> lock(interruptLock_);
     if (!hasResult()) {
       if (interrupt_) {
         fn(as_const(*interrupt_));
       } else {
         setInterruptHandlerNoLock(std::forward<F>(fn));
       }
     }
   }
template<typename T> void folly::futures::detail::Core< T >::setInterruptHandlerNoLock (std::function< void(exception_wrapper const &)> fn) inline
Definition at line 494 of file Core.h.
References folly::gen::move.
Referenced by folly::Future< T >::onError().
{
     interruptHandlerSet_.store(true, std::memory_order_relaxed);
     interruptHandler_ = std::move(fn);
   }
template<typename T> void folly::futures::detail::Core< T >::setProxy (Core< T > * proxy) inline
Call only from producer thread. Call only once - else undefined behavior.
See FSM graph for allowed transitions.
This can not be called concurrently with setResult().
Definition at line 342 of file Core.h.
References folly::assume(), FOLLY_FALLTHROUGH, folly::futures::detail::OnlyCallback, folly::futures::detail::Proxy, and folly::futures::detail::Start.
{
     DCHECK(!hasResult());
     proxy_ = proxy;
     auto state = state_.load(std::memory_order_acquire);
     switch (state) {
       case State::Start:
         if (state_.compare_exchange_strong(
                 state, State::Proxy, std::memory_order_release)) {
           break;
         }
         assume(state == State::OnlyCallback);
         FOLLY_FALLTHROUGH;
       case State::OnlyCallback:
         proxyCallback();
         break;
       default:
         terminate_with<std::logic_error>("setCallback unexpected state");
     }
     detachOne();
   }
template<typename T> void folly::futures::detail::Core< T >::setResult (Try< T > && t) inline
Call only from producer thread. Call only once - else undefined behavior.
See FSM graph for allowed transitions.
If it transitions to Done, synchronously initiates a call to the callback, and might also synchronously execute that callback (e.g., if there is no executor or if the executor is inline).
Definition at line 376 of file Core.h.
References folly::assume(), folly::futures::detail::Done, FOLLY_FALLTHROUGH, folly::gen::move, folly::futures::detail::OnlyCallback, folly::futures::detail::OnlyResult, folly::futures::detail::Start, and folly::pushmi::detail::t.
Referenced by folly::futures::detail::coreDetachPromiseMaybeWithResult(), and folly::Promise< T >::setTry().
{
     DCHECK(!hasResult());
     ::new (&result_) Result(std::move(t));
     auto state = state_.load(std::memory_order_acquire);
     while (true) {
       switch (state) {
         case State::Start:
           if (state_.compare_exchange_strong(
                   state, State::OnlyResult, std::memory_order_release)) {
             return;
           }
           assume(state == State::OnlyCallback);
           FOLLY_FALLTHROUGH;
         case State::OnlyCallback:
           if (state_.compare_exchange_strong(
                   state, State::Done, std::memory_order_release)) {
             doCallback();
             return;
           }
           FOLLY_FALLTHROUGH;
         default:
           terminate_with<std::logic_error>("setResult unexpected state");
       }
     }
   }
Member Data Documentation
union { ... }
union { ... }
union { ... }
template<typename T> std::atomic<unsigned char> folly::futures::detail::Core< T >::attached_ private
Definition at line 671 of file Core.h.
template<typename T> Callback folly::futures::detail::Core< T >::callback_
Definition at line 662 of file Core.h.
Referenced by folly::futures::detail::Core< T >::doCallback().
template<typename T> std::atomic<unsigned char> folly::futures::detail::Core< T >::callbackReferences_ {0} private
Definition at line 672 of file Core.h.
template<typename T> Context folly::futures::detail::Core< T >::context_
Definition at line 678 of file Core.h.
Referenced by folly::futures::detail::Core< T >::doCallback().
template<typename T> Executor::KeepAlive folly::futures::detail::Core< T >::executor_ private
Definition at line 676 of file Core.h.
template<typename T> std::unique_ptr<exception_wrapper> folly::futures::detail::Core< T >::interrupt_ {} private
Definition at line 680 of file Core.h.
template<typename T> std::function<void(exception_wrapper const&)> folly::futures::detail::Core< T >::interruptHandler_ {nullptr} private
Definition at line 681 of file Core.h.
template<typename T> std::atomic<bool> folly::futures::detail::Core< T >::interruptHandlerSet_ {false} private
Definition at line 673 of file Core.h.
template<typename T> SpinLock folly::futures::detail::Core< T >::interruptLock_ private
Definition at line 674 of file Core.h.
template<typename T> int8_t folly::futures::detail::Core< T >::priority_ {-1} private
Definition at line 675 of file Core.h.
template<typename T> Core* folly::futures::detail::Core< T >::proxy_
Definition at line 668 of file Core.h.
template<typename T> Result folly::futures::detail::Core< T >::result_
Definition at line 667 of file Core.h.
Referenced by folly::futures::detail::Core< T >::doCallback().
template<typename T> std::atomic<State> folly::futures::detail::Core< T >::state_ private
Definition at line 670 of file Core.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/futures/detail/Core.h