proxygen: fizz::test::EncryptedRecordTest Class Reference
fizz::test::EncryptedRecordTest Class Reference
Protected Member Functions
void addToQueue (const std::string &hex)
Protected Member Functions inherited from testing::Test
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Static Protected Member Functions
static Buf getBuf (const std::string &hex, size_t headroom=0, size_t tailroom=0)
static void expectSame (const Buf &buf, const std::string &hex)
Protected Attributes
EncryptedReadRecordLayer read_ {EncryptionLevel::AppTraffic}
EncryptedWriteRecordLayer write_ {EncryptionLevel::AppTraffic}
MockAead * readAead_
MockAead * writeAead_
IOBufQueue queue_ {IOBufQueue::cacheChainLength()}
IOBufEqualTo eq_
Private Member Functions
void SetUp () override
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Detailed Description
Definition at line 26 of file EncryptedRecordTest.cpp.
Member Function Documentation
void fizz::test::EncryptedRecordTest::addToQueue (const std::string & hex) inline protected
Definition at line 52 of file EncryptedRecordTest.cpp.
{
     queue_.append(getBuf(hex));
   }
static void fizz::test::EncryptedRecordTest::expectSame (const Buf & buf, const std::string & hex) inline static protected
Definition at line 56 of file EncryptedRecordTest.cpp.
References EXPECT_EQ, and folly::hexlify().
{
     auto str = buf->moveToFbString().toStdString();
     EXPECT_EQ(hexlify(str), hex);
   }
static Buf fizz::test::EncryptedRecordTest::getBuf (const std::string & hex, size_t headroom = 0, size_t tailroom = 0) inline static protected
Definition at line 47 of file EncryptedRecordTest.cpp.
References folly::IOBuf::copyBuffer(), folly::data(), and folly::unhexlify().
{
     auto data = unhexlify(hex);
     return IOBuf::copyBuffer(data.data(), data.size(), headroom, tailroom);
   }
void fizz::test::EncryptedRecordTest::SetUp () inline override private virtual
Reimplemented from testing::Test.
Definition at line 27 of file EncryptedRecordTest.cpp.
References folly::gen::move.
{
     auto readAead = std::make_unique<MockAead>();
     readAead_ = readAead.get();
     read_.setAead(folly::ByteRange(), std::move(readAead));
     auto writeAead = std::make_unique<MockAead>();
     writeAead_ = writeAead.get();
     write_.setAead(folly::ByteRange(), std::move(writeAead));
   }
Member Data Documentation
IOBufEqualTo fizz::test::EncryptedRecordTest::eq_ protected
Definition at line 44 of file EncryptedRecordTest.cpp.
IOBufQueue fizz::test::EncryptedRecordTest::queue_ {IOBufQueue::cacheChainLength()} protected
Definition at line 42 of file EncryptedRecordTest.cpp.
EncryptedReadRecordLayer fizz::test::EncryptedRecordTest::read_ {EncryptionLevel::AppTraffic} protected
Definition at line 37 of file EncryptedRecordTest.cpp.
MockAead* fizz::test::EncryptedRecordTest::readAead_ protected
Definition at line 39 of file EncryptedRecordTest.cpp.
EncryptedWriteRecordLayer fizz::test::EncryptedRecordTest::write_ {EncryptionLevel::AppTraffic} protected
Definition at line 38 of file EncryptedRecordTest.cpp.
MockAead* fizz::test::EncryptedRecordTest::writeAead_ protected
Definition at line 40 of file EncryptedRecordTest.cpp.
The documentation for this class was generated from the following file:
proxygen/fizz/fizz/record/test/EncryptedRecordTest.cpp