proxygen: folly::fibers::FiberImpl Class Reference
folly::fibers::FiberImpl Class Reference
#include <BoostContextCompatibility.h>
Public Member Functions
FiberImpl (folly::Function< void()> func, unsigned char *stackLimit, size_t stackSize)
void activate ()
void deactivate ()
Private Types
using FiberContext = boost::ctx::fcontext_t
using MainContext = boost::ctx::fcontext_t
Static Private Member Functions
static void fiberFunc (intptr_t arg)
Private Attributes
folly::Function< void()> func_
FiberContext fiberContext_
MainContext mainContext_
Detailed Description
Definition at line 44 of file BoostContextCompatibility.h.
Member Typedef Documentation
using folly::fibers::FiberImpl::FiberContext = boost::ctx::fcontext_t private
Definition at line 52 of file BoostContextCompatibility.h.
using folly::fibers::FiberImpl::MainContext = boost::ctx::fcontext_t private
Definition at line 62 of file BoostContextCompatibility.h.
Constructor & Destructor Documentation
folly::fibers::FiberImpl::FiberImpl (folly::Function< void()> func, unsigned char * stackLimit, size_t stackSize) inline
Definition at line 66 of file BoostContextCompatibility.h.
References fiberContext_, and fiberFunc().
       : func_(std::move(func)) {
     auto stackBase = stackLimit + stackSize;
 #if BOOST_VERSION >= 106100
     stackBase_ = stackBase;
     fiberContext_ =
         boost::context::detail::make_fcontext(stackBase, stackSize, &fiberFunc);
 #elif BOOST_VERSION >= 105200
     fiberContext_ =
         boost::context::make_fcontext(stackBase, stackSize, &fiberFunc);
 #else
     fiberContext_.fc_stack.limit = stackLimit;
     fiberContext_.fc_stack.base = stackBase;
     make_fcontext(&fiberContext_, &fiberFunc);
 #endif
   }
Member Function Documentation
void folly::fibers::FiberImpl::activate () inline
Definition at line 86 of file BoostContextCompatibility.h.
References context, fiberContext_, and mainContext_.
Referenced by folly::fibers::FiberManager::activateFiber().
                   {
 #if BOOST_VERSION >= 106100
     auto transfer = boost::context::detail::jump_fcontext(fiberContext_, this);
     fiberContext_ = transfer.fctx;
     auto context = reinterpret_cast<intptr_t>(transfer.data);
 #elif BOOST_VERSION >= 105200
     auto context = boost::context::jump_fcontext(
         &mainContext_, fiberContext_, reinterpret_cast<intptr_t>(this));
 #else
     auto context = jump_fcontext(
         &mainContext_, &fiberContext_, reinterpret_cast<intptr_t>(this));
 #endif
     DCHECK_EQ(0, context);
   }
void folly::fibers::FiberImpl::deactivate () inline
Definition at line 101 of file BoostContextCompatibility.h.
References context, fiberContext_, fiberFunc(), folly::kIsArchAmd64, folly::kIsLinux, and mainContext_.
Referenced by folly::fibers::FiberManager::deactivateFiber().
                     {
 #if BOOST_VERSION >= 106100
     auto transfer =
         boost::context::detail::jump_fcontext(mainContext_, nullptr);
     mainContext_ = transfer.fctx;
     fixStackUnwinding();
     auto context = reinterpret_cast<intptr_t>(transfer.data);
 #elif BOOST_VERSION >= 105600
     auto context =
         boost::context::jump_fcontext(&fiberContext_, mainContext_, 0);
 #elif BOOST_VERSION >= 105200
     auto context =
         boost::context::jump_fcontext(fiberContext_, &mainContext_, 0);
 #else
     auto context = jump_fcontext(&fiberContext_, &mainContext_, 0);
 #endif
     DCHECK_EQ(this, reinterpret_cast<FiberImpl*>(context));
   }
static void folly::fibers::FiberImpl::fiberFunc (intptr_t arg) inline static private
Definition at line 142 of file BoostContextCompatibility.h.
References func_.
Referenced by deactivate(), and FiberImpl().
{
     auto fiberImpl = reinterpret_cast<FiberImpl*>(arg);
     fiberImpl->func_();
   }
Member Data Documentation
FiberContext folly::fibers::FiberImpl::fiberContext_ private
Definition at line 149 of file BoostContextCompatibility.h.
Referenced by activate(), deactivate(), and FiberImpl().
folly::Function<void()> folly::fibers::FiberImpl::func_ private
Definition at line 148 of file BoostContextCompatibility.h.
Referenced by fiberFunc().
MainContext folly::fibers::FiberImpl::mainContext_ private
Definition at line 150 of file BoostContextCompatibility.h.
Referenced by activate(), and deactivate().
The documentation for this class was generated from the following file:
proxygen/folly/folly/fibers/BoostContextCompatibility.h