proxygen: folly::symbolizer::SignalSafeElfCache::Path Class Reference
folly::symbolizer::SignalSafeElfCache::Path Class Reference
Public Member Functions
Path ()
Path (StringPiece s)
void assign (StringPiece s)
bool operator< (const Path &other) const
bool operator== (const Path &other) const
const char * data () const
Static Public Attributes
static constexpr size_t kMaxSize = PATH_MAX - 1
Private Attributes
char data_ [kMaxSize+1]
Detailed Description
Definition at line 72 of file ElfCache.h.
Constructor & Destructor Documentation
folly::symbolizer::SignalSafeElfCache::Path::Path () inline
Definition at line 74 of file ElfCache.h.
            {
       assign(folly::StringPiece());
     }
folly::symbolizer::SignalSafeElfCache::Path::Path (StringPiece s) inline explicit
Definition at line 78 of file ElfCache.h.
{
       assign(s);
     }
Member Function Documentation
void folly::symbolizer::SignalSafeElfCache::Path::assign (StringPiece s) inline
Definition at line 82 of file ElfCache.h.
References folly::Range< Iter >::data(), data_, folly::Range< Iter >::empty(), and folly::Range< Iter >::size().
Referenced by folly::symbolizer::SignalSafeElfCache::getFile().
{
       DCHECK_LE(s.size(), kMaxSize);
       if (!s.empty()) {
         memcpy(data_, s.data(), s.size());
       }
       data_[s.size()] = '\0';
     }
const char* folly::symbolizer::SignalSafeElfCache::Path::data () const inline
Definition at line 98 of file ElfCache.h.
References data_.
Referenced by folly::symbolizer::SignalSafeElfCache::getFile().
{
       return data_;
     }
bool folly::symbolizer::SignalSafeElfCache::Path::operator< (const Path & other) const inline
Definition at line 90 of file ElfCache.h.
References data_, and data_.
{
       return strcmp(data_, other.data_) < 0;
     }
bool folly::symbolizer::SignalSafeElfCache::Path::operator== (const Path & other) const inline
Definition at line 94 of file ElfCache.h.
References data_, and data_.
{
       return strcmp(data_, other.data_) == 0;
     }
Member Data Documentation
char folly::symbolizer::SignalSafeElfCache::Path::data_[kMaxSize+1] private
Definition at line 105 of file ElfCache.h.
Referenced by operator<(), and operator==().
constexpr size_t folly::symbolizer::SignalSafeElfCache::Path::kMaxSize = PATH_MAX - 1 static
Definition at line 102 of file ElfCache.h.
Referenced by folly::symbolizer::SignalSafeElfCache::getFile().
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/symbolizer/ElfCache.h