proxygen: example::ExampleObject Class Reference
example::ExampleObject Class Reference
#include <lib.h>
Public Member Functions
ExampleObject (folly::StringPiece str)
~ExampleObject ()
void doStuff ()
Private Attributes
std::string value_
Detailed Description
Definition at line 23 of file lib.h.
Constructor & Destructor Documentation
example::ExampleObject::ExampleObject (folly::StringPiece str) inline explicit
Definition at line 25 of file lib.h.
References doStuff(), folly::Range< Iter >::str(), value_, XLOGF, and ~ExampleObject().
                                                : value_{str.str()} {
     // All XLOG() statements in this file will log to the category
     // folly.experimental.logging.example.lib
     XLOGF(DBG1, "ExampleObject({}) constructed at {}", value_, this);
   }
example::ExampleObject::~ExampleObject ()
Definition at line 19 of file lib.cpp.
References value_, and XLOGF.
Referenced by ExampleObject().
{
   // All XLOG() statements in this file will log to the category
   // folly.logging.example.lib
   XLOGF(DBG1, "ExampleObject({}) at {} destroyed", value_, this);
 }
Member Function Documentation
void example::ExampleObject::doStuff ()
Referenced by ExampleObject().
Member Data Documentation
std::string example::ExampleObject::value_ private
Definition at line 35 of file lib.h.
Referenced by ExampleObject(), and ~ExampleObject().
The documentation for this class was generated from the following files:
proxygen/folly/folly/logging/example/lib.h
proxygen/folly/folly/logging/example/lib.cpp