proxygen: upload.GitVCS Class Reference
upload.GitVCS Class Reference
Public Member Functions
def __init__ (self, options)
def GenerateDiff (self, extra_args)
def GetUnknownFiles (self)
def GetBaseFile (self, filename)
def __init__ (self, options)
def GenerateDiff (self, extra_args)
def GetUnknownFiles (self)
def GetBaseFile (self, filename)
def __init__ (self, options)
def GenerateDiff (self, extra_args)
def GetUnknownFiles (self)
def GetBaseFile (self, filename)
def __init__ (self, options)
def GenerateDiff (self, extra_args)
def GetUnknownFiles (self)
def GetBaseFile (self, filename)
def __init__ (self, options)
def GenerateDiff (self, extra_args)
def GetUnknownFiles (self)
def GetBaseFile (self, filename)
def __init__ (self, options)
def GenerateDiff (self, extra_args)
def GetUnknownFiles (self)
def GetBaseFile (self, filename)
Public Member Functions inherited from upload.VersionControlSystem
def __init__ (self, options)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def CheckForUnknownFiles (self)
def GetBaseFile (self, filename)
def GetBaseFiles (self, diff)
def UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
def IsImage (self, filename)
def __init__ (self, options)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def CheckForUnknownFiles (self)
def GetBaseFile (self, filename)
def GetBaseFiles (self, diff)
def UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
def IsImage (self, filename)
def __init__ (self, options)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def CheckForUnknownFiles (self)
def GetBaseFile (self, filename)
def GetBaseFiles (self, diff)
def UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
def IsImage (self, filename)
def __init__ (self, options)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def CheckForUnknownFiles (self)
def GetBaseFile (self, filename)
def GetBaseFiles (self, diff)
def UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
def IsImage (self, filename)
def __init__ (self, options)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def CheckForUnknownFiles (self)
def GetBaseFile (self, filename)
def GetBaseFiles (self, diff)
def UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
def IsImage (self, filename)
def __init__ (self, options)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def CheckForUnknownFiles (self)
def GetBaseFile (self, filename)
def GetBaseFiles (self, diff)
def UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
def IsImage (self, filename)
Public Attributes
base_hashes
Public Attributes inherited from upload.VersionControlSystem
options
Detailed Description
Implementation of the VersionControlSystem interface for Git.
Definition at line 985 of file upload.py.
Constructor & Destructor Documentation
def upload.GitVCS.__init__ (self, options)
Definition at line 988 of file upload.py.
Referenced by upload.GitVCS.__init__().
   def __init__(self, options):
     super(GitVCS, self).__init__(options)
     # Map of filename -> hash of base file.
     self.base_hashes = {}
def upload.GitVCS.__init__ (self, options)
Definition at line 988 of file upload.py.
References upload.GitVCS.__init__(), and upload.GitVCS.base_hashes.
   def __init__(self, options):
     super(GitVCS, self).__init__(options)
     # Map of filename -> hash of base file.
     self.base_hashes = {}
def upload.GitVCS.__init__ (self, options)
Definition at line 988 of file upload.py.
References upload.GitVCS.__init__(), and upload.GitVCS.base_hashes.
   def __init__(self, options):
     super(GitVCS, self).__init__(options)
     # Map of filename -> hash of base file.
     self.base_hashes = {}
def upload.GitVCS.__init__ (self, options)
Definition at line 988 of file upload.py.
References upload.GitVCS.__init__(), and upload.GitVCS.base_hashes.
   def __init__(self, options):
     super(GitVCS, self).__init__(options)
     # Map of filename -> hash of base file.
     self.base_hashes = {}
def upload.GitVCS.__init__ (self, options)
Definition at line 988 of file upload.py.
References upload.GitVCS.__init__(), and upload.GitVCS.base_hashes.
   def __init__(self, options):
     super(GitVCS, self).__init__(options)
     # Map of filename -> hash of base file.
     self.base_hashes = {}
def upload.GitVCS.__init__ (self, options)
Definition at line 988 of file upload.py.
References upload.GitVCS.__init__(), and upload.GitVCS.base_hashes.
   def __init__(self, options):
     super(GitVCS, self).__init__(options)
     # Map of filename -> hash of base file.
     self.base_hashes = {}
Member Function Documentation
def upload.GitVCS.GenerateDiff (self, extra_args)
Definition at line 993 of file upload.py.
References upload.GitVCS.base_hashes, upload.ErrorExit(), join, and upload.RunShell().
Referenced by upload.GitVCS.GenerateDiff().
   def GenerateDiff(self, extra_args):
     # This is more complicated than svn's GenerateDiff because we must convert
     # the diff output to include an svn-style "Index:" line as well as record
     # the hashes of the base files, so we can upload them along with our diff.
     if self.options.revision:
       extra_args = [self.options.revision] + extra_args
     gitdiff = RunShell(["git", "diff", "--full-index"] + extra_args)
     svndiff = []
     filecount = 0
     filename = None
     for line in gitdiff.splitlines():
       match = re.match(r"diff --git a/(.*) b/.*$", line)
       if match:
         filecount += 1
         filename = match.group(1)
         svndiff.append("Index: %s\n" % filename)
       else:
         # The "index" line in a git diff looks like this (long hashes elided):
         #   index 82c0d44..b2cee3f 100755
         # We want to save the left hash, as that identifies the base file.
         match = re.match(r"index (\w+)\.\.", line)
         if match:
           self.base_hashes[filename] = match.group(1)
       svndiff.append(line + "\n")
     if not filecount:
       ErrorExit("No valid patches found in output from git diff")
     return "".join(svndiff)
def upload.GitVCS.GenerateDiff (self, extra_args)
Definition at line 993 of file upload.py.
References upload.GitVCS.base_hashes, upload.ErrorExit(), upload.GitVCS.GenerateDiff(), join, and upload.RunShell().
   def GenerateDiff(self, extra_args):
     # This is more complicated than svn's GenerateDiff because we must convert
     # the diff output to include an svn-style "Index:" line as well as record
     # the hashes of the base files, so we can upload them along with our diff.
     if self.options.revision:
       extra_args = [self.options.revision] + extra_args
     gitdiff = RunShell(["git", "diff", "--full-index"] + extra_args)
     svndiff = []
     filecount = 0
     filename = None
     for line in gitdiff.splitlines():
       match = re.match(r"diff --git a/(.*) b/.*$", line)
       if match:
         filecount += 1
         filename = match.group(1)
         svndiff.append("Index: %s\n" % filename)
       else:
         # The "index" line in a git diff looks like this (long hashes elided):
         #   index 82c0d44..b2cee3f 100755
         # We want to save the left hash, as that identifies the base file.
         match = re.match(r"index (\w+)\.\.", line)
         if match:
           self.base_hashes[filename] = match.group(1)
       svndiff.append(line + "\n")
     if not filecount:
       ErrorExit("No valid patches found in output from git diff")
     return "".join(svndiff)
def upload.GitVCS.GenerateDiff (self, extra_args)
Definition at line 993 of file upload.py.
References upload.GitVCS.base_hashes, upload.ErrorExit(), upload.GitVCS.GenerateDiff(), join, and upload.RunShell().
   def GenerateDiff(self, extra_args):
     # This is more complicated than svn's GenerateDiff because we must convert
     # the diff output to include an svn-style "Index:" line as well as record
     # the hashes of the base files, so we can upload them along with our diff.
     if self.options.revision:
       extra_args = [self.options.revision] + extra_args
     gitdiff = RunShell(["git", "diff", "--full-index"] + extra_args)
     svndiff = []
     filecount = 0
     filename = None
     for line in gitdiff.splitlines():
       match = re.match(r"diff --git a/(.*) b/.*$", line)
       if match:
         filecount += 1
         filename = match.group(1)
         svndiff.append("Index: %s\n" % filename)
       else:
         # The "index" line in a git diff looks like this (long hashes elided):
         #   index 82c0d44..b2cee3f 100755
         # We want to save the left hash, as that identifies the base file.
         match = re.match(r"index (\w+)\.\.", line)
         if match:
           self.base_hashes[filename] = match.group(1)
       svndiff.append(line + "\n")
     if not filecount:
       ErrorExit("No valid patches found in output from git diff")
     return "".join(svndiff)
def upload.GitVCS.GenerateDiff (self, extra_args)
Definition at line 993 of file upload.py.
References upload.GitVCS.base_hashes, upload.ErrorExit(), upload.GitVCS.GenerateDiff(), join, and upload.RunShell().
   def GenerateDiff(self, extra_args):
     # This is more complicated than svn's GenerateDiff because we must convert
     # the diff output to include an svn-style "Index:" line as well as record
     # the hashes of the base files, so we can upload them along with our diff.
     if self.options.revision:
       extra_args = [self.options.revision] + extra_args
     gitdiff = RunShell(["git", "diff", "--full-index"] + extra_args)
     svndiff = []
     filecount = 0
     filename = None
     for line in gitdiff.splitlines():
       match = re.match(r"diff --git a/(.*) b/.*$", line)
       if match:
         filecount += 1
         filename = match.group(1)
         svndiff.append("Index: %s\n" % filename)
       else:
         # The "index" line in a git diff looks like this (long hashes elided):
         #   index 82c0d44..b2cee3f 100755
         # We want to save the left hash, as that identifies the base file.
         match = re.match(r"index (\w+)\.\.", line)
         if match:
           self.base_hashes[filename] = match.group(1)
       svndiff.append(line + "\n")
     if not filecount:
       ErrorExit("No valid patches found in output from git diff")
     return "".join(svndiff)
def upload.GitVCS.GenerateDiff (self, extra_args)
Definition at line 993 of file upload.py.
References upload.GitVCS.base_hashes, upload.ErrorExit(), upload.GitVCS.GenerateDiff(), join, and upload.RunShell().
   def GenerateDiff(self, extra_args):
     # This is more complicated than svn's GenerateDiff because we must convert
     # the diff output to include an svn-style "Index:" line as well as record
     # the hashes of the base files, so we can upload them along with our diff.
     if self.options.revision:
       extra_args = [self.options.revision] + extra_args
     gitdiff = RunShell(["git", "diff", "--full-index"] + extra_args)
     svndiff = []
     filecount = 0
     filename = None
     for line in gitdiff.splitlines():
       match = re.match(r"diff --git a/(.*) b/.*$", line)
       if match:
         filecount += 1
         filename = match.group(1)
         svndiff.append("Index: %s\n" % filename)
       else:
         # The "index" line in a git diff looks like this (long hashes elided):
         #   index 82c0d44..b2cee3f 100755
         # We want to save the left hash, as that identifies the base file.
         match = re.match(r"index (\w+)\.\.", line)
         if match:
           self.base_hashes[filename] = match.group(1)
       svndiff.append(line + "\n")
     if not filecount:
       ErrorExit("No valid patches found in output from git diff")
     return "".join(svndiff)
def upload.GitVCS.GenerateDiff (self, extra_args)
Definition at line 993 of file upload.py.
References upload.GitVCS.base_hashes, upload.ErrorExit(), upload.GitVCS.GenerateDiff(), join, and upload.RunShell().
   def GenerateDiff(self, extra_args):
     # This is more complicated than svn's GenerateDiff because we must convert
     # the diff output to include an svn-style "Index:" line as well as record
     # the hashes of the base files, so we can upload them along with our diff.
     if self.options.revision:
       extra_args = [self.options.revision] + extra_args
     gitdiff = RunShell(["git", "diff", "--full-index"] + extra_args)
     svndiff = []
     filecount = 0
     filename = None
     for line in gitdiff.splitlines():
       match = re.match(r"diff --git a/(.*) b/.*$", line)
       if match:
         filecount += 1
         filename = match.group(1)
         svndiff.append("Index: %s\n" % filename)
       else:
         # The "index" line in a git diff looks like this (long hashes elided):
         #   index 82c0d44..b2cee3f 100755
         # We want to save the left hash, as that identifies the base file.
         match = re.match(r"index (\w+)\.\.", line)
         if match:
           self.base_hashes[filename] = match.group(1)
       svndiff.append(line + "\n")
     if not filecount:
       ErrorExit("No valid patches found in output from git diff")
     return "".join(svndiff)
def upload.GitVCS.GetBaseFile (self, filename)
Definition at line 1026 of file upload.py.
References upload.GitVCS.base_hashes, upload.ErrorExit(), upload.GitVCS.GetBaseFile(), and upload.RunShellWithReturnCode().
   def GetBaseFile(self, filename):
     hash = self.base_hashes[filename]
     base_content = None
     new_content = None
     is_binary = False
     if hash == "0" * 40:  # All-zero hash indicates no base file.
       status = "A"
       base_content = ""
     else:
       status = "M"
       base_content, returncode = RunShellWithReturnCode(["git", "show", hash])
       if returncode:
         ErrorExit("Got error status from 'git show %s'" % hash)
     return (base_content, new_content, is_binary, status)
def upload.GitVCS.GetBaseFile (self, filename)
Definition at line 1026 of file upload.py.
References upload.GitVCS.base_hashes, upload.ErrorExit(), upload.GitVCS.GetBaseFile(), and upload.RunShellWithReturnCode().
   def GetBaseFile(self, filename):
     hash = self.base_hashes[filename]
     base_content = None
     new_content = None
     is_binary = False
     if hash == "0" * 40:  # All-zero hash indicates no base file.
       status = "A"
       base_content = ""
     else:
       status = "M"
       base_content, returncode = RunShellWithReturnCode(["git", "show", hash])
       if returncode:
         ErrorExit("Got error status from 'git show %s'" % hash)
     return (base_content, new_content, is_binary, status)
def upload.GitVCS.GetBaseFile (self, filename)
Definition at line 1026 of file upload.py.
References upload.GitVCS.base_hashes, upload.ErrorExit(), upload.GitVCS.GetBaseFile(), and upload.RunShellWithReturnCode().
   def GetBaseFile(self, filename):
     hash = self.base_hashes[filename]
     base_content = None
     new_content = None
     is_binary = False
     if hash == "0" * 40:  # All-zero hash indicates no base file.
       status = "A"
       base_content = ""
     else:
       status = "M"
       base_content, returncode = RunShellWithReturnCode(["git", "show", hash])
       if returncode:
         ErrorExit("Got error status from 'git show %s'" % hash)
     return (base_content, new_content, is_binary, status)
def upload.GitVCS.GetBaseFile (self, filename)
Definition at line 1026 of file upload.py.
References upload.GitVCS.base_hashes, upload.ErrorExit(), upload.GitVCS.GetBaseFile(), and upload.RunShellWithReturnCode().
   def GetBaseFile(self, filename):
     hash = self.base_hashes[filename]
     base_content = None
     new_content = None
     is_binary = False
     if hash == "0" * 40:  # All-zero hash indicates no base file.
       status = "A"
       base_content = ""
     else:
       status = "M"
       base_content, returncode = RunShellWithReturnCode(["git", "show", hash])
       if returncode:
         ErrorExit("Got error status from 'git show %s'" % hash)
     return (base_content, new_content, is_binary, status)
def upload.GitVCS.GetBaseFile (self, filename)
Definition at line 1026 of file upload.py.
References upload.GitVCS.base_hashes, upload.ErrorExit(), upload.GitVCS.GetBaseFile(), and upload.RunShellWithReturnCode().
   def GetBaseFile(self, filename):
     hash = self.base_hashes[filename]
     base_content = None
     new_content = None
     is_binary = False
     if hash == "0" * 40:  # All-zero hash indicates no base file.
       status = "A"
       base_content = ""
     else:
       status = "M"
       base_content, returncode = RunShellWithReturnCode(["git", "show", hash])
       if returncode:
         ErrorExit("Got error status from 'git show %s'" % hash)
     return (base_content, new_content, is_binary, status)
def upload.GitVCS.GetBaseFile (self, filename)
Definition at line 1026 of file upload.py.
References upload.GitVCS.base_hashes, upload.ErrorExit(), and upload.RunShellWithReturnCode().
Referenced by upload.GitVCS.GetBaseFile().
   def GetBaseFile(self, filename):
     hash = self.base_hashes[filename]
     base_content = None
     new_content = None
     is_binary = False
     if hash == "0" * 40:  # All-zero hash indicates no base file.
       status = "A"
       base_content = ""
     else:
       status = "M"
       base_content, returncode = RunShellWithReturnCode(["git", "show", hash])
       if returncode:
         ErrorExit("Got error status from 'git show %s'" % hash)
     return (base_content, new_content, is_binary, status)
def upload.GitVCS.GetUnknownFiles (self)
Definition at line 1021 of file upload.py.
References upload.GitVCS.GetUnknownFiles(), and upload.RunShell().
   def GetUnknownFiles(self):
     status = RunShell(["git", "ls-files", "--exclude-standard", "--others"],
                       silent_ok=True)
     return status.splitlines()
def upload.GitVCS.GetUnknownFiles (self)
Definition at line 1021 of file upload.py.
References upload.GitVCS.GetUnknownFiles(), and upload.RunShell().
   def GetUnknownFiles(self):
     status = RunShell(["git", "ls-files", "--exclude-standard", "--others"],
                       silent_ok=True)
     return status.splitlines()
def upload.GitVCS.GetUnknownFiles (self)
Definition at line 1021 of file upload.py.
References upload.GitVCS.GetUnknownFiles(), and upload.RunShell().
   def GetUnknownFiles(self):
     status = RunShell(["git", "ls-files", "--exclude-standard", "--others"],
                       silent_ok=True)
     return status.splitlines()
def upload.GitVCS.GetUnknownFiles (self)
Definition at line 1021 of file upload.py.
References upload.GitVCS.GetUnknownFiles(), and upload.RunShell().
   def GetUnknownFiles(self):
     status = RunShell(["git", "ls-files", "--exclude-standard", "--others"],
                       silent_ok=True)
     return status.splitlines()
def upload.GitVCS.GetUnknownFiles (self)
Definition at line 1021 of file upload.py.
References upload.RunShell().
Referenced by upload.GitVCS.GetUnknownFiles().
   def GetUnknownFiles(self):
     status = RunShell(["git", "ls-files", "--exclude-standard", "--others"],
                       silent_ok=True)
     return status.splitlines()
def upload.GitVCS.GetUnknownFiles (self)
Definition at line 1021 of file upload.py.
References upload.GitVCS.GetUnknownFiles(), and upload.RunShell().
   def GetUnknownFiles(self):
     status = RunShell(["git", "ls-files", "--exclude-standard", "--others"],
                       silent_ok=True)
     return status.splitlines()
Member Data Documentation
upload.GitVCS.base_hashes
Definition at line 991 of file upload.py.
Referenced by upload.GitVCS.__init__(), upload.GitVCS.GenerateDiff(), and upload.GitVCS.GetBaseFile().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/scripts/upload.py