proxygen: wangle::EventBaseHandler Class Reference
wangle::EventBaseHandler Class Reference
#include <EventBaseHandler.h>
Public Member Functions
folly::Future< folly::Unit > write (Context *ctx, std::unique_ptr< folly::IOBuf > buf) override
folly::Future< folly::Unit > close (Context *ctx) override
Public Member Functions inherited from wangle::OutboundHandler< Win, Wout >
~OutboundHandler () override=default
virtual folly::Future< folly::Unit > write (Context *ctx, Win msg)=0
virtual folly::Future< folly::Unit > writeException (Context *ctx, folly::exception_wrapper e)
Public Member Functions inherited from wangle::HandlerBase< OutboundHandlerContext< Wout > >
virtual ~HandlerBase ()=default
virtual void attachPipeline (OutboundHandlerContext< Wout > *)
virtual void detachPipeline (OutboundHandlerContext< Wout > *)
OutboundHandlerContext< Wout > * getContext ()
Additional Inherited Members
Public Types inherited from wangle::OutboundHandler< Win, Wout >
typedef folly::Unit rin
typedef folly::Unit rout
typedef Win win
typedef Wout wout
typedef OutboundHandlerContext< Wout > Context
Static Public Attributes inherited from wangle::OutboundHandler< Win, Wout >
static const HandlerDir dir = HandlerDir::OUT
Detailed Description
Definition at line 24 of file EventBaseHandler.h.
Member Function Documentation
folly::Future<folly::Unit> wangle::EventBaseHandler::close (Context * ctx) inline override virtual
Reimplemented from wangle::OutboundHandler< Win, Wout >.
Definition at line 38 of file EventBaseHandler.h.
References wangle::OutboundHandlerContext< Out >::fireClose(), and wangle::OutboundHandlerContext< Out >::getTransport().
{
     DCHECK(ctx->getTransport());
     DCHECK(ctx->getTransport()->getEventBase());
     folly::Future<folly::Unit> retval;
     ctx->getTransport()->getEventBase()->runImmediatelyOrRunInEventBaseThreadAndWait([&](){
         retval = ctx->fireClose();
     });
     return retval;
   }
folly::Future<folly::Unit> wangle::EventBaseHandler::write (Context * ctx, std::unique_ptr< folly::IOBuf > buf) inline override
Definition at line 26 of file EventBaseHandler.h.
References wangle::OutboundHandlerContext< Out >::fireWrite(), wangle::OutboundHandlerContext< Out >::getTransport(), and folly::gen::move.
{
     folly::Future<folly::Unit> retval;
     DCHECK(ctx->getTransport());
     DCHECK(ctx->getTransport()->getEventBase());
     ctx->getTransport()->getEventBase()->runImmediatelyOrRunInEventBaseThreadAndWait([&](){
         retval = ctx->fireWrite(std::move(buf));
     });
     return retval;
   }
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/channel/EventBaseHandler.h