proxygen: testing::internal::UniversalPrinter< T & > Class Template Reference
testing::internal::UniversalPrinter< T & > Class Template Reference
#include <gtest-printers.h>
Static Public Member Functions
static void Print (const T &value,::std::ostream *os)
static void Print (const T &value,::std::ostream *os)
static void Print (const T &value,::std::ostream *os)
Detailed Description
template<typename T>
class testing::internal::UniversalPrinter< T & >
Definition at line 758 of file gtest-printers.h.
Member Function Documentation
template<typename T > static void testing::internal::UniversalPrinter< T & >::Print (const T & value, ::std::ostream * os) inline static
Definition at line 764 of file gtest-printers.h.
References GTEST_DISABLE_MSC_WARNINGS_POP_, testing::internal::UniversalPrint(), and value.
{
     // Prints the address of the value.  We use reinterpret_cast here
     // as static_cast doesn't compile when T is a function type.
     *os << "@" << reinterpret_cast<const void*>(&value) << " ";
     // Then prints the value itself.
     UniversalPrint(value, os);
   }
template<typename T > static void testing::internal::UniversalPrinter< T & >::Print (const T & value, ::std::ostream * os) inline static
Definition at line 764 of file gtest-printers.h.
References GTEST_DISABLE_MSC_WARNINGS_POP_, testing::internal::UniversalPrint(), and value.
{
     // Prints the address of the value.  We use reinterpret_cast here
     // as static_cast doesn't compile when T is a function type.
     *os << "@" << reinterpret_cast<const void*>(&value) << " ";
     // Then prints the value itself.
     UniversalPrint(value, os);
   }
template<typename T > static void testing::internal::UniversalPrinter< T & >::Print (const T & value, ::std::ostream * os) inline static
Definition at line 764 of file gtest-printers.h.
References GTEST_DISABLE_MSC_WARNINGS_POP_, testing::internal::UniversalPrint(), and value.
{
     // Prints the address of the value.  We use reinterpret_cast here
     // as static_cast doesn't compile when T is a function type.
     *os << "@" << reinterpret_cast<const void*>(&value) << " ";
     // Then prints the value itself.
     UniversalPrint(value, os);
   }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/gtest-printers.h