proxygen: fizz::HandshakeContextImpl< Hash > Class Template Reference
fizz::HandshakeContextImpl< Hash > Class Template Reference
#include <HandshakeContext.h>
Public Member Functions
HandshakeContextImpl (const std::string &hkdfLabelPrefix)
void appendToTranscript (const Buf &data) override
Buf getHandshakeContext () const override
Buf getFinishedData (folly::ByteRange baseKey) const override
folly::ByteRange getBlankContext () const override
Public Member Functions inherited from fizz::HandshakeContext
virtual ~HandshakeContext ()=default
Private Attributes
folly::ssl::OpenSSLHash::Digest hashState_
std::string hkdfLabelPrefix_
Detailed Description
template<typename Hash>
class fizz::HandshakeContextImpl< Hash >
Definition at line 47 of file HandshakeContext.h.
Constructor & Destructor Documentation
template<typename Hash > fizz::HandshakeContextImpl< Hash >::HandshakeContextImpl (const std::string & hkdfLabelPrefix)
Definition at line 14 of file HandshakeContext-inl.h.
References folly::ssl::OpenSSLHash::Digest::hash_init(), and fizz::HandshakeContextImpl< Hash >::hashState_.
     : hkdfLabelPrefix_(hkdfLabelPrefix) {
   hashState_ = folly::ssl::OpenSSLHash::Digest();
   hashState_.hash_init(Hash::HashEngine());
 }
Member Function Documentation
template<typename Hash > void fizz::HandshakeContextImpl< Hash >::appendToTranscript (const Buf & transcript) override virtual
Appends transcript to the current handshake transcript.
Implements fizz::HandshakeContext.
Definition at line 22 of file HandshakeContext-inl.h.
References folly::ssl::OpenSSLHash::Digest::hash_update(), and fizz::HandshakeContextImpl< Hash >::hashState_.
{
   hashState_.hash_update(*data);
 }
template<typename Hash > folly::ByteRange fizz::HandshakeContextImpl< Hash >::getBlankContext () const inline override virtual
Returns the handshake context for an empty transcript.
Implements fizz::HandshakeContext.
Definition at line 57 of file HandshakeContext.h.
{
     return Hash::BlankHash;
   }
template<typename Hash > Buf fizz::HandshakeContextImpl< Hash >::getFinishedData (folly::ByteRange baseKey) const override virtual
Returns the finished verify_data from the current handshake context and baseKey.
Implements fizz::HandshakeContext.
Definition at line 37 of file HandshakeContext-inl.h.
References context, folly::IOBuf::create(), data, fizz::HandshakeContextImpl< Hash >::getHandshakeContext(), and fizz::HandshakeContextImpl< Hash >::hkdfLabelPrefix_.
{
   auto context = getHandshakeContext();
   auto finishedKey =
       KeyDerivationImpl<Hash>(hkdfLabelPrefix_)
           .expandLabel(
               baseKey, "finished", folly::IOBuf::create(0), Hash::HashLen);
   auto data = folly::IOBuf::create(Hash::HashLen);
   data->append(Hash::HashLen);
   auto outRange = folly::MutableByteRange(data->writableData(), data->length());
   Hash::hmac(finishedKey->coalesce(), *context, outRange);
   return data;
 }
template<typename Hash > Buf fizz::HandshakeContextImpl< Hash >::getHandshakeContext () const override virtual
Returns the handshake context for the current transcript.
Implements fizz::HandshakeContext.
Definition at line 27 of file HandshakeContext-inl.h.
References folly::IOBuf::create(), folly::ssl::OpenSSLHash::Digest::hash_final(), and fizz::HandshakeContextImpl< Hash >::hashState_.
Referenced by fizz::HandshakeContextImpl< Hash >::getFinishedData().
{
   folly::ssl::OpenSSLHash::Digest copied(hashState_);
   auto out = folly::IOBuf::create(Hash::HashLen);
   out->append(Hash::HashLen);
   folly::MutableByteRange outRange(out->writableData(), out->length());
   copied.hash_final(outRange);
   return out;
 }
Member Data Documentation
template<typename Hash > folly::ssl::OpenSSLHash::Digest fizz::HandshakeContextImpl< Hash >::hashState_ private
Definition at line 62 of file HandshakeContext.h.
Referenced by fizz::HandshakeContextImpl< Hash >::appendToTranscript(), fizz::HandshakeContextImpl< Hash >::getHandshakeContext(), and fizz::HandshakeContextImpl< Hash >::HandshakeContextImpl().
template<typename Hash > std::string fizz::HandshakeContextImpl< Hash >::hkdfLabelPrefix_ private
Definition at line 63 of file HandshakeContext.h.
Referenced by fizz::HandshakeContextImpl< Hash >::getFinishedData().
The documentation for this class was generated from the following files:
proxygen/fizz/fizz/protocol/HandshakeContext.h
proxygen/fizz/fizz/protocol/HandshakeContext-inl.h