proxygen: folly::coro::detail::BlockingWaitPromiseBase Class Reference
folly::coro::detail::BlockingWaitPromiseBase Class Reference
#include <BlockingWait.h>
Classes
struct FinalAwaiter
Public Member Functions
BlockingWaitPromiseBase () noexcept=default
std::experimental::suspend_always initial_suspend ()
FinalAwaiter final_suspend () noexcept
Protected Member Functions
void wait () noexcept
Private Attributes
folly::fibers::Baton baton_
Detailed Description
Definition at line 37 of file BlockingWait.h.
Constructor & Destructor Documentation
folly::coro::detail::BlockingWaitPromiseBase::BlockingWaitPromiseBase () default noexcept
Referenced by folly::coro::detail::BlockingWaitPromiseBase::FinalAwaiter::await_resume().
Member Function Documentation
FinalAwaiter folly::coro::detail::BlockingWaitPromiseBase::final_suspend () inline noexcept
Definition at line 58 of file BlockingWait.h.
Referenced by folly::coro::detail::BlockingWaitPromise< T & >::yield_value().
{
     return {};
   }
std::experimental::suspend_always folly::coro::detail::BlockingWaitPromiseBase::initial_suspend () inline
Definition at line 54 of file BlockingWait.h.
{
     return {};
   }
void folly::coro::detail::BlockingWaitPromiseBase::wait () inline protected noexcept
Definition at line 63 of file BlockingWait.h.
References baton_, and folly::fibers::Baton::wait().
Referenced by folly::coro::detail::BlockingWaitPromise< T >::getAsTry(), folly::coro::detail::BlockingWaitPromise< T & >::getAsTry(), and folly::coro::detail::BlockingWaitPromise< void >::getAsTry().
{
     baton_.wait();
   }
Member Data Documentation
folly::fibers::Baton folly::coro::detail::BlockingWaitPromiseBase::baton_ private
Definition at line 68 of file BlockingWait.h.
Referenced by folly::coro::detail::BlockingWaitPromiseBase::FinalAwaiter::await_suspend(), and wait().
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/coro/BlockingWait.h