proxygen: wangle::LocalSSLSessionCache Class Reference
wangle::LocalSSLSessionCache Class Reference
#include <SSLSessionCacheManager.h>
Public Member Functions
LocalSSLSessionCache (uint32_t maxCacheSize, uint32_t cacheCullSize)
~LocalSSLSessionCache ()
Public Attributes
SSLSessionCacheMap sessionCache
std::mutex lock
uint32_t removedSessions_ {0}
Private Member Functions
void pruneSessionCallback (const std::string &sessionId, SSL_SESSION *session)
Detailed Description
Holds an SSLSessionCacheMap and associated lock
Definition at line 38 of file SSLSessionCacheManager.h.
Constructor & Destructor Documentation
wangle::LocalSSLSessionCache::LocalSSLSessionCache (uint32_t maxCacheSize, uint32_t cacheCullSize)
Definition at line 55 of file SSLSessionCacheManager.cpp.
References folly::netops::bind(), pruneSessionCallback(), sessionCache, and folly::EvictingCacheMap< TKey, TValue, THash, TKeyEqual >::setPruneHook().
Referenced by wangle::ShardedLocalSSLSessionCache::ShardedLocalSSLSessionCache().
     : sessionCache(maxCacheSize, cacheCullSize) {
   sessionCache.setPruneHook(std::bind(
                               &LocalSSLSessionCache::pruneSessionCallback,
                               this, std::placeholders::_1,
                               std::placeholders::_2));
 }
wangle::LocalSSLSessionCache::~LocalSSLSessionCache () inline
Definition at line 42 of file SSLSessionCacheManager.h.
References folly::EvictingCacheMap< TKey, TValue, THash, TKeyEqual >::clear(), g(), lock, and sessionCache.
{
     std::lock_guard<std::mutex> g(lock);
     // EvictingCacheMap dtor doesn't free values
     sessionCache.clear();
   }
Member Function Documentation
void wangle::LocalSSLSessionCache::pruneSessionCallback (const std::string & sessionId, SSL_SESSION * session) private
Definition at line 64 of file SSLSessionCacheManager.cpp.
References wangle::SSLUtil::hexlify(), and removedSessions_.
Referenced by LocalSSLSessionCache().
{
   VLOG(4) << "Free SSL session from local cache; id="
           << SSLUtil::hexlify(sessionId);
   SSL_SESSION_free(session);
   ++removedSessions_;
 }
Member Data Documentation
std::mutex wangle::LocalSSLSessionCache::lock
Definition at line 49 of file SSLSessionCacheManager.h.
Referenced by wangle::ShardedLocalSSLSessionCache::lookupSession(), wangle::ShardedLocalSSLSessionCache::removeSession(), wangle::ShardedLocalSSLSessionCache::storeSession(), and ~LocalSSLSessionCache().
uint32_t wangle::LocalSSLSessionCache::removedSessions_ {0}
Definition at line 50 of file SSLSessionCacheManager.h.
Referenced by pruneSessionCallback(), and wangle::ShardedLocalSSLSessionCache::storeSession().
SSLSessionCacheMap wangle::LocalSSLSessionCache::sessionCache
Definition at line 48 of file SSLSessionCacheManager.h.
Referenced by LocalSSLSessionCache(), wangle::ShardedLocalSSLSessionCache::lookupSession(), wangle::ShardedLocalSSLSessionCache::storeSession(), and ~LocalSSLSessionCache().
The documentation for this class was generated from the following files:
proxygen/wangle/wangle/ssl/SSLSessionCacheManager.h
proxygen/wangle/wangle/ssl/SSLSessionCacheManager.cpp