proxygen: folly::coro::detail::InlineTask< T >::Awaiter Class Reference
folly::coro::detail::InlineTask< T >::Awaiter Class Reference
#include <InlineTask.h>
Public Member Functions
~Awaiter ()
bool await_ready () noexcept
handle_t await_suspend (std::experimental::coroutine_handle<> awaitingCoroutine) noexcept
T await_resume ()
Private Member Functions
Awaiter (handle_t coro) noexcept
Private Attributes
handle_t coro_
Friends
class InlineTask< T >
Detailed Description
template<typename T>
class folly::coro::detail::InlineTask< T >::Awaiter
Definition at line 178 of file InlineTask.h.
Constructor & Destructor Documentation
template<typename T> folly::coro::detail::InlineTask< T >::Awaiter::~Awaiter () inline
Definition at line 180 of file InlineTask.h.
                {
       if (coro_) {
         coro_.destroy();
       }
     }
template<typename T> folly::coro::detail::InlineTask< T >::Awaiter::Awaiter (handle_t coro) inline explicit private noexcept
Definition at line 205 of file InlineTask.h.
 : coro_(coro) {}
Member Function Documentation
template<typename T> bool folly::coro::detail::InlineTask< T >::Awaiter::await_ready () inline noexcept
Definition at line 186 of file InlineTask.h.
{
       return false;
     }
template<typename T> T folly::coro::detail::InlineTask< T >::Awaiter::await_resume () inline
Definition at line 197 of file InlineTask.h.
References destroy(), folly::exchange(), and folly::makeGuard().
                      {
       auto destroyOnExit =
           folly::makeGuard([this] { std::exchange(coro_, {}).destroy(); });
       return coro_.promise().result();
     }
template<typename T> handle_t folly::coro::detail::InlineTask< T >::Awaiter::await_suspend (std::experimental::coroutine_handle<> awaitingCoroutine) inline noexcept
Definition at line 190 of file InlineTask.h.
{
       assert(coro_ && !coro_.done());
       coro_.promise().set_continuation(awaitingCoroutine);
       return coro_;
     }
Friends And Related Function Documentation
template<typename T> friend class InlineTask< T > friend
Definition at line 204 of file InlineTask.h.
Member Data Documentation
template<typename T> handle_t folly::coro::detail::InlineTask< T >::Awaiter::coro_ private
Definition at line 206 of file InlineTask.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/coro/detail/InlineTask.h