proxygen: folly::gen::VirtualGen< Value >::WrapperBase Class Reference
folly::gen::VirtualGen< Value >::WrapperBase Class Reference abstract
Public Member Functions
virtual ~WrapperBase () noexcept
virtual bool apply (const std::function< bool(Value)> &handler) const =0
virtual void foreach (const std::function< void(Value)> &body) const =0
virtual std::unique_ptr< const WrapperBase > clone () const =0
Detailed Description
template<class Value>
class folly::gen::VirtualGen< Value >::WrapperBase
Definition at line 2486 of file Base-inl.h.
Constructor & Destructor Documentation
template<class Value> virtual folly::gen::VirtualGen< Value >::WrapperBase::~WrapperBase () inline virtual noexcept
Definition at line 2488 of file Base-inl.h.
References folly::apply(), handler(), and testing::Value().
 {}
Member Function Documentation
template<class Value> virtual bool folly::gen::VirtualGen< Value >::WrapperBase::apply (const std::function< bool(Value)> & handler) const pure virtual
Implemented in folly::gen::VirtualGen< Value >::WrapperImpl< Wrapped >.
template<class Value> virtual std::unique_ptr<const WrapperBase> folly::gen::VirtualGen< Value >::WrapperBase::clone () const pure virtual
Implemented in folly::gen::VirtualGen< Value >::WrapperImpl< Wrapped >.
template<class Value> virtual void folly::gen::VirtualGen< Value >::WrapperBase::foreach (const std::function< void(Value)> & body) const pure virtual
Implemented in folly::gen::VirtualGen< Value >::WrapperImpl< Wrapped >.
The documentation for this class was generated from the following file:
proxygen/folly/folly/gen/Base-inl.h