proxygen: fizz::Exporter Class Reference
fizz::Exporter Class Reference
#include <Exporter.h>
Static Public Member Functions
static Buf getEkm (CipherSuite cipher, folly::ByteRange exporterMaster, folly::StringPiece label, Buf context, uint16_t length)
Detailed Description
Definition at line 16 of file Exporter.h.
Member Function Documentation
Buf fizz::Exporter::getEkm (CipherSuite cipher, folly::ByteRange exporterMaster, folly::StringPiece label, Buf context, uint16_t length) static
Definition at line 13 of file Exporter.cpp.
References folly::IOBuf::create(), folly::Range< Iter >::hash(), fizz::Factory::makeKeyDeriver(), folly::range(), secret, and folly::IOBuf::wrapBuffer().
Referenced by fizz::server::FizzServer< ActionMoveVisitor, SM >::getEarlyEkm(), fizz::client::FizzClient< ActionMoveVisitor, SM >::getEarlyEkm(), and fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::getEkm().
                      {
   if (!context) {
     context = folly::IOBuf::create(0);
   }
   auto deriver = Factory().makeKeyDeriver(cipher);
   std::vector<uint8_t> base(deriver->hashLength());
   folly::MutableByteRange hashedContext(base.data(), base.size());
   deriver->hash(*context, hashedContext);
   auto secret =
       deriver->deriveSecret(exporterMaster, label, deriver->blankHash());
   return deriver->expandLabel(
       folly::range(secret),
       "exporter",
       folly::IOBuf::wrapBuffer(hashedContext),
       length);
 }
The documentation for this class was generated from the following files:
proxygen/fizz/fizz/protocol/Exporter.h
proxygen/fizz/fizz/protocol/Exporter.cpp