proxygen: folly::Executor::KeepAlive< ExecutorT > Class Template Reference
folly::Executor::KeepAlive< ExecutorT > Class Template Reference
#include <Executor.h>
Public Member Functions
KeepAlive ()=default
~KeepAlive ()
KeepAlive (KeepAlive &&other) noexcept
template<typename OtherExecutor , typename = typename std::enable_if< std::is_convertible<OtherExecutor*, ExecutorT*>::value>::type>
KeepAlive (KeepAlive< OtherExecutor > &&other) noexcept
KeepAlive & operator= (KeepAlive &&other)
template<typename OtherExecutor , typename = typename std::enable_if< std::is_convertible<OtherExecutor*, ExecutorT*>::value>::type>
KeepAlive & operator= (KeepAlive< OtherExecutor > &&other)
void reset ()
operator bool () const
ExecutorT * get () const
ExecutorT & operator* () const
ExecutorT * operator-> () const
KeepAlive copy () const
Private Member Functions
KeepAlive (ExecutorT *executor, bool dummy)
Private Attributes
intptr_t executorAndDummyFlag_ {reinterpret_cast<intptr_t>(nullptr)}
Static Private Attributes
static constexpr intptr_t kDummyFlag = 1
static constexpr intptr_t kExecutorMask = ~kDummyFlag
Friends
class Executor
template<typename OtherExecutor >
class KeepAlive
Detailed Description
template<typename ExecutorT = Executor>
class folly::Executor::KeepAlive< ExecutorT >
Definition at line 53 of file Executor.h.
Constructor & Destructor Documentation
template<typename ExecutorT = Executor> folly::Executor::KeepAlive< ExecutorT >::KeepAlive () default
Referenced by folly::Executor::KeepAlive< folly::VirtualEventBase >::operator=().
template<typename ExecutorT = Executor> folly::Executor::KeepAlive< ExecutorT >::~KeepAlive () inline
Definition at line 57 of file Executor.h.
                  {
       reset();
     }
template<typename ExecutorT = Executor> folly::Executor::KeepAlive< ExecutorT >::KeepAlive (KeepAlive< ExecutorT > && other) inline noexcept
Definition at line 61 of file Executor.h.
         : executorAndDummyFlag_(exchange(other.executorAndDummyFlag_, 0)) {}
template<typename ExecutorT = Executor> template<typename OtherExecutor , typename = typename std::enable_if< std::is_convertible<OtherExecutor*, ExecutorT*>::value>::type> folly::Executor::KeepAlive< ExecutorT >::KeepAlive (KeepAlive< OtherExecutor > && other) inline noexcept
Definition at line 68 of file Executor.h.
         : KeepAlive(other.get(), other.executorAndDummyFlag_ & kDummyFlag) {
       other.executorAndDummyFlag_ = 0;
     }
template<typename ExecutorT = Executor> folly::Executor::KeepAlive< ExecutorT >::KeepAlive (ExecutorT * executor, bool dummy) inline private
Definition at line 125 of file Executor.h.
         : executorAndDummyFlag_(
               reinterpret_cast<intptr_t>(executor) | (dummy ? kDummyFlag : 0)) {
       assert(executor);
       assert(
           (reinterpret_cast<intptr_t>(executor) & kExecutorMask) ==
           reinterpret_cast<intptr_t>(executor));
     }
Member Function Documentation
template<typename ExecutorT = Executor> KeepAlive folly::Executor::KeepAlive< ExecutorT >::copy () const inline
Definition at line 113 of file Executor.h.
Referenced by folly::futures::detail::DeferredExecutor::setExecutor(), and folly::window().
{
       return getKeepAliveToken(get());
     }
template<typename ExecutorT = Executor> ExecutorT* folly::Executor::KeepAlive< ExecutorT >::get () const inline
Definition at line 100 of file Executor.h.
Referenced by folly::TEST().
{
       return reinterpret_cast<ExecutorT*>(
           executorAndDummyFlag_ & kExecutorMask);
     }
template<typename ExecutorT = Executor> folly::Executor::KeepAlive< ExecutorT >::operator bool () const inline explicit
Definition at line 96 of file Executor.h.
{
       return executorAndDummyFlag_;
     }
template<typename ExecutorT = Executor> ExecutorT& folly::Executor::KeepAlive< ExecutorT >::operator* () const inline
Definition at line 105 of file Executor.h.
{
       return *get();
     }
template<typename ExecutorT = Executor> ExecutorT* folly::Executor::KeepAlive< ExecutorT >::operator-> () const inline
Definition at line 109 of file Executor.h.
{
       return get();
     }
template<typename ExecutorT = Executor> KeepAlive& folly::Executor::KeepAlive< ExecutorT >::operator= (KeepAlive< ExecutorT > && other) inline
Definition at line 73 of file Executor.h.
{
       reset();
       executorAndDummyFlag_ = exchange(other.executorAndDummyFlag_, 0);
       return *this;
     }
template<typename ExecutorT = Executor> template<typename OtherExecutor , typename = typename std::enable_if< std::is_convertible<OtherExecutor*, ExecutorT*>::value>::type> KeepAlive& folly::Executor::KeepAlive< ExecutorT >::operator= (KeepAlive< OtherExecutor > && other) inline
Definition at line 83 of file Executor.h.
{
       return *this = KeepAlive(std::move(other));
     }
template<typename ExecutorT = Executor> void folly::Executor::KeepAlive< ExecutorT >::reset () inline
Definition at line 87 of file Executor.h.
Referenced by folly::Executor::KeepAlive< folly::VirtualEventBase >::operator=(), folly::fibers::ExecutorLoopController::runLoop(), and folly::Executor::KeepAlive< folly::VirtualEventBase >::~KeepAlive().
                  {
       if (Executor* executor = get()) {
         if (exchange(executorAndDummyFlag_, 0) & kDummyFlag) {
           return;
         }
         executor->keepAliveRelease();
       }
     }
Friends And Related Function Documentation
template<typename ExecutorT = Executor> friend class Executor friend
Definition at line 121 of file Executor.h.
template<typename ExecutorT = Executor> template<typename OtherExecutor > friend class KeepAlive friend
Definition at line 123 of file Executor.h.
Member Data Documentation
template<typename ExecutorT = Executor> intptr_t folly::Executor::KeepAlive< ExecutorT >::executorAndDummyFlag_ {reinterpret_cast<intptr_t>(nullptr)} private
Definition at line 134 of file Executor.h.
Referenced by folly::Executor::KeepAlive< folly::VirtualEventBase >::get(), folly::Executor::isKeepAliveDummy(), folly::Executor::KeepAlive< folly::VirtualEventBase >::KeepAlive(), folly::Executor::KeepAlive< folly::VirtualEventBase >::operator bool(), folly::Executor::KeepAlive< folly::VirtualEventBase >::operator=(), and folly::Executor::KeepAlive< folly::VirtualEventBase >::reset().
template<typename ExecutorT = Executor> constexpr intptr_t folly::Executor::KeepAlive< ExecutorT >::kDummyFlag = 1 static private
Definition at line 118 of file Executor.h.
Referenced by folly::Executor::KeepAlive< folly::VirtualEventBase >::reset().
template<typename ExecutorT = Executor> constexpr intptr_t folly::Executor::KeepAlive< ExecutorT >::kExecutorMask = ~kDummyFlag static private
Definition at line 119 of file Executor.h.
Referenced by folly::Executor::KeepAlive< folly::VirtualEventBase >::get().
The documentation for this class was generated from the following file:
proxygen/folly/folly/Executor.h