proxygen: testing::internal::DefaultGlobalTestPartResultReporter Class Reference
testing::internal::DefaultGlobalTestPartResultReporter Class Reference
#include <gtest-internal-inl.h>
Public Member Functions
DefaultGlobalTestPartResultReporter (UnitTestImpl *unit_test)
virtual void ReportTestPartResult (const TestPartResult &result)
DefaultGlobalTestPartResultReporter (UnitTestImpl *unit_test)
virtual void ReportTestPartResult (const TestPartResult &result)
DefaultGlobalTestPartResultReporter (UnitTestImpl *unit_test)
virtual void ReportTestPartResult (const TestPartResult &result)
Public Member Functions inherited from testing::TestPartResultReporterInterface
virtual ~TestPartResultReporterInterface ()
virtual ~TestPartResultReporterInterface ()
virtual ~TestPartResultReporterInterface ()
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (DefaultGlobalTestPartResultReporter)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (DefaultGlobalTestPartResultReporter)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (DefaultGlobalTestPartResultReporter)
Private Attributes
UnitTestImpl *const unit_test_
Detailed Description
Definition at line 465 of file gtest-internal-inl.h.
Constructor & Destructor Documentation
testing::internal::DefaultGlobalTestPartResultReporter::DefaultGlobalTestPartResultReporter (UnitTestImpl * unit_test) explicit
Definition at line 686 of file gtest.cc.
Referenced by testing::internal::ShouldRunTestCase().
                              : unit_test_(unit_test) {}
testing::internal::DefaultGlobalTestPartResultReporter::DefaultGlobalTestPartResultReporter (UnitTestImpl * unit_test) explicit
testing::internal::DefaultGlobalTestPartResultReporter::DefaultGlobalTestPartResultReporter (UnitTestImpl * unit_test) explicit
Member Function Documentation
testing::internal::DefaultGlobalTestPartResultReporter::GTEST_DISALLOW_COPY_AND_ASSIGN_ (DefaultGlobalTestPartResultReporter) private
testing::internal::DefaultGlobalTestPartResultReporter::GTEST_DISALLOW_COPY_AND_ASSIGN_ (DefaultGlobalTestPartResultReporter) private
testing::internal::DefaultGlobalTestPartResultReporter::GTEST_DISALLOW_COPY_AND_ASSIGN_ (DefaultGlobalTestPartResultReporter) private
void testing::internal::DefaultGlobalTestPartResultReporter::ReportTestPartResult (const TestPartResult & result) virtual
Implements testing::TestPartResultReporterInterface.
Definition at line 689 of file gtest.cc.
References testing::TestResult::AddTestPartResult(), testing::internal::UnitTestImpl::current_test_result(), testing::internal::UnitTestImpl::listeners(), testing::TestEventListener::OnTestPartResult(), testing::TestEventListeners::repeater(), and unit_test_.
Referenced by testing::internal::ShouldRunTestCase().
{
   unit_test_->current_test_result()->AddTestPartResult(result);
   unit_test_->listeners()->repeater()->OnTestPartResult(result);
 }
virtual void testing::internal::DefaultGlobalTestPartResultReporter::ReportTestPartResult (const TestPartResult & result) virtual
Implements testing::TestPartResultReporterInterface.
virtual void testing::internal::DefaultGlobalTestPartResultReporter::ReportTestPartResult (const TestPartResult & result) virtual
Implements testing::TestPartResultReporterInterface.
Member Data Documentation
UnitTestImpl *const testing::internal::DefaultGlobalTestPartResultReporter::unit_test_ private
Definition at line 474 of file gtest-internal-inl.h.
Referenced by ReportTestPartResult().
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest-internal-inl.h
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest.cc