proxygen: folly::pushmi::strand_executor< E, Executor > Class Template Reference
folly::pushmi::strand_executor< E, Executor > Class Template Reference
#include <strand.h>
Public Types
using properties = property_set< is_sender<>, is_executor<>, property_set_index_t< properties_t< Executor >, is_never_blocking<>>, is_fifo_sequence<>, is_single<>>
Public Member Functions
strand_executor (std::shared_ptr< strand_queue< E, Executor >> queue)
auto executor ()
requires ReceiveValue< Out, any_executor_ref< E > > &&ReceiveError< Out, E > void submit (Out out)
Private Attributes
std::shared_ptr< strand_queue< E, Executor > > queue_
Detailed Description
template<class E, class Executor>
class folly::pushmi::strand_executor< E, Executor >
Definition at line 27 of file strand.h.
Member Typedef Documentation
template<class E , class Executor > using folly::pushmi::strand_executor< E, Executor >::properties = property_set< is_sender<>, is_executor<>, property_set_index_t<properties_t<Executor>, is_never_blocking<>>, is_fifo_sequence<>, is_single<>>
Definition at line 188 of file strand.h.
Constructor & Destructor Documentation
template<class E , class Executor > folly::pushmi::strand_executor< E, Executor >::strand_executor (std::shared_ptr< strand_queue< E, Executor >> queue) inline
Definition at line 190 of file strand.h.
       : queue_(std::move(queue)) {}
Member Function Documentation
template<class E , class Executor > auto folly::pushmi::strand_executor< E, Executor >::executor () inline
Definition at line 193 of file strand.h.
References folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
                   {
     return *this;
   }
template<class E , class Executor > requires ReceiveValue<Out, any_executor_ref<E> >&& ReceiveError<Out, E> void folly::pushmi::strand_executor< E, Executor >::submit (Out out) inline
Definition at line 200 of file strand.h.
References folly::gen::guard(), folly::gen::move, and submit.
{
     // queue for later
     std::unique_lock<std::mutex> guard{queue_->lock_};
     queue_->items_.push(any_receiver<E, any_executor_ref<E>>{std::move(out)});
     if (queue_->remaining_ == 0) {
       // noone is minding the shop, send a worker
       ::folly::pushmi::submit(
           queue_->ex_, strand_queue_receiver<E, Executor>{queue_});
     }
   }
Member Data Documentation
template<class E , class Executor > std::shared_ptr<strand_queue<E, Executor> > folly::pushmi::strand_executor< E, Executor >::queue_ private
Definition at line 180 of file strand.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/pushmi/strand.h