proxygen: testing::internal::GTestFlagSaver Class Reference
testing::internal::GTestFlagSaver Class Reference
#include <gtest-internal-inl.h>
Public Member Functions
GTestFlagSaver ()
~GTestFlagSaver ()
GTestFlagSaver ()
~GTestFlagSaver ()
GTestFlagSaver ()
~GTestFlagSaver ()
Private Attributes
bool also_run_disabled_tests_
bool break_on_failure_
bool catch_exceptions_
std::string color_
std::string death_test_style_
bool death_test_use_fork_
std::string filter_
std::string internal_run_death_test_
bool list_tests_
std::string output_
bool print_time_
internal::Int32 random_seed_
internal::Int32 repeat_
bool shuffle_
internal::Int32 stack_trace_depth_
std::string stream_result_to_
bool throw_on_failure_
Detailed Description
Definition at line 162 of file gtest-internal-inl.h.
Constructor & Destructor Documentation
testing::internal::GTestFlagSaver::GTestFlagSaver () inline
Definition at line 165 of file gtest-internal-inl.h.
References also_run_disabled_tests_, break_on_failure_, catch_exceptions_, color_, death_test_style_, death_test_use_fork_, folly::pushmi::operators::filter, filter_, GTEST_FLAG, internal_run_death_test_, list_tests_, gmock_output_test::output, output_, print_time_, random_seed_, repeat(), repeat_, shuffle_, stack_trace_depth_, stream_result_to_, and throw_on_failure_.
                    {
     also_run_disabled_tests_ = GTEST_FLAG(also_run_disabled_tests);
     break_on_failure_ = GTEST_FLAG(break_on_failure);
     catch_exceptions_ = GTEST_FLAG(catch_exceptions);
     color_ = GTEST_FLAG(color);
     death_test_style_ = GTEST_FLAG(death_test_style);
     death_test_use_fork_ = GTEST_FLAG(death_test_use_fork);
     filter_ = GTEST_FLAG(filter);
     internal_run_death_test_ = GTEST_FLAG(internal_run_death_test);
     list_tests_ = GTEST_FLAG(list_tests);
     output_ = GTEST_FLAG(output);
     print_time_ = GTEST_FLAG(print_time);
     random_seed_ = GTEST_FLAG(random_seed);
     repeat_ = GTEST_FLAG(repeat);
     shuffle_ = GTEST_FLAG(shuffle);
     stack_trace_depth_ = GTEST_FLAG(stack_trace_depth);
     stream_result_to_ = GTEST_FLAG(stream_result_to);
     throw_on_failure_ = GTEST_FLAG(throw_on_failure);
   }
testing::internal::GTestFlagSaver::~GTestFlagSaver () inline
Definition at line 186 of file gtest-internal-inl.h.
References also_run_disabled_tests_, break_on_failure_, catch_exceptions_, color_, death_test_style_, death_test_use_fork_, folly::pushmi::operators::filter, filter_, GTEST_FLAG, internal_run_death_test_, list_tests_, gmock_output_test::output, output_, print_time_, random_seed_, repeat(), repeat_, shuffle_, stack_trace_depth_, stream_result_to_, and throw_on_failure_.
                     {
     GTEST_FLAG(also_run_disabled_tests) = also_run_disabled_tests_;
     GTEST_FLAG(break_on_failure) = break_on_failure_;
     GTEST_FLAG(catch_exceptions) = catch_exceptions_;
     GTEST_FLAG(color) = color_;
     GTEST_FLAG(death_test_style) = death_test_style_;
     GTEST_FLAG(death_test_use_fork) = death_test_use_fork_;
     GTEST_FLAG(filter) = filter_;
     GTEST_FLAG(internal_run_death_test) = internal_run_death_test_;
     GTEST_FLAG(list_tests) = list_tests_;
     GTEST_FLAG(output) = output_;
     GTEST_FLAG(print_time) = print_time_;
     GTEST_FLAG(random_seed) = random_seed_;
     GTEST_FLAG(repeat) = repeat_;
     GTEST_FLAG(shuffle) = shuffle_;
     GTEST_FLAG(stack_trace_depth) = stack_trace_depth_;
     GTEST_FLAG(stream_result_to) = stream_result_to_;
     GTEST_FLAG(throw_on_failure) = throw_on_failure_;
   }
testing::internal::GTestFlagSaver::GTestFlagSaver () inline
Definition at line 165 of file gtest-internal-inl.h.
References also_run_disabled_tests_, break_on_failure_, catch_exceptions_, color_, death_test_style_, death_test_use_fork_, folly::pushmi::operators::filter, filter_, GTEST_FLAG, internal_run_death_test_, list_tests_, gmock_output_test::output, output_, print_time_, random_seed_, repeat(), repeat_, shuffle_, stack_trace_depth_, stream_result_to_, and throw_on_failure_.
                    {
     also_run_disabled_tests_ = GTEST_FLAG(also_run_disabled_tests);
     break_on_failure_ = GTEST_FLAG(break_on_failure);
     catch_exceptions_ = GTEST_FLAG(catch_exceptions);
     color_ = GTEST_FLAG(color);
     death_test_style_ = GTEST_FLAG(death_test_style);
     death_test_use_fork_ = GTEST_FLAG(death_test_use_fork);
     filter_ = GTEST_FLAG(filter);
     internal_run_death_test_ = GTEST_FLAG(internal_run_death_test);
     list_tests_ = GTEST_FLAG(list_tests);
     output_ = GTEST_FLAG(output);
     print_time_ = GTEST_FLAG(print_time);
     random_seed_ = GTEST_FLAG(random_seed);
     repeat_ = GTEST_FLAG(repeat);
     shuffle_ = GTEST_FLAG(shuffle);
     stack_trace_depth_ = GTEST_FLAG(stack_trace_depth);
     stream_result_to_ = GTEST_FLAG(stream_result_to);
     throw_on_failure_ = GTEST_FLAG(throw_on_failure);
   }
testing::internal::GTestFlagSaver::~GTestFlagSaver () inline
Definition at line 186 of file gtest-internal-inl.h.
References also_run_disabled_tests_, folly::test::begin(), break_on_failure_, c, catch_exceptions_, testing::internal::CodePointToUtf8(), color_, count, testing::internal::CountIf(), death_test_style_, death_test_use_fork_, folly::test::end(), folly::pushmi::operators::filter, filter_, for_each(), testing::internal::ForEach(), testing::internal::Random::Generate(), testing::internal::GetElementOr(), GTEST_API_, testing::internal::GTEST_ATTRIBUTE_UNUSED_, GTEST_CHECK_, GTEST_FLAG, i, testing::internal::Int32FromEnvOrDie(), internal_run_death_test_, list_tests_, gmock_output_test::output, output_, print_time_, random(), random_seed_, repeat(), repeat_, testing::internal::ShouldRunTestOnShard(), testing::internal::ShouldShard(), testing::internal::Shuffle(), shuffle_, testing::internal::ShuffleRange(), folly::size(), stack_trace_depth_, stream_result_to_, string, folly::f14::swap(), throw_on_failure_, testing::internal::WideStringToUtf8(), and testing::internal::WriteToShardStatusFileIfNeeded().
                     {
     GTEST_FLAG(also_run_disabled_tests) = also_run_disabled_tests_;
     GTEST_FLAG(break_on_failure) = break_on_failure_;
     GTEST_FLAG(catch_exceptions) = catch_exceptions_;
     GTEST_FLAG(color) = color_;
     GTEST_FLAG(death_test_style) = death_test_style_;
     GTEST_FLAG(death_test_use_fork) = death_test_use_fork_;
     GTEST_FLAG(filter) = filter_;
     GTEST_FLAG(internal_run_death_test) = internal_run_death_test_;
     GTEST_FLAG(list_tests) = list_tests_;
     GTEST_FLAG(output) = output_;
     GTEST_FLAG(print_time) = print_time_;
     GTEST_FLAG(random_seed) = random_seed_;
     GTEST_FLAG(repeat) = repeat_;
     GTEST_FLAG(shuffle) = shuffle_;
     GTEST_FLAG(stack_trace_depth) = stack_trace_depth_;
     GTEST_FLAG(stream_result_to) = stream_result_to_;
     GTEST_FLAG(throw_on_failure) = throw_on_failure_;
   }
testing::internal::GTestFlagSaver::GTestFlagSaver () inline
Definition at line 165 of file gtest-internal-inl.h.
References also_run_disabled_tests_, break_on_failure_, catch_exceptions_, color_, death_test_style_, death_test_use_fork_, folly::pushmi::operators::filter, filter_, GTEST_FLAG, internal_run_death_test_, list_tests_, gmock_output_test::output, output_, print_time_, random_seed_, repeat(), repeat_, shuffle_, stack_trace_depth_, stream_result_to_, and throw_on_failure_.
                    {
     also_run_disabled_tests_ = GTEST_FLAG(also_run_disabled_tests);
     break_on_failure_ = GTEST_FLAG(break_on_failure);
     catch_exceptions_ = GTEST_FLAG(catch_exceptions);
     color_ = GTEST_FLAG(color);
     death_test_style_ = GTEST_FLAG(death_test_style);
     death_test_use_fork_ = GTEST_FLAG(death_test_use_fork);
     filter_ = GTEST_FLAG(filter);
     internal_run_death_test_ = GTEST_FLAG(internal_run_death_test);
     list_tests_ = GTEST_FLAG(list_tests);
     output_ = GTEST_FLAG(output);
     print_time_ = GTEST_FLAG(print_time);
     random_seed_ = GTEST_FLAG(random_seed);
     repeat_ = GTEST_FLAG(repeat);
     shuffle_ = GTEST_FLAG(shuffle);
     stack_trace_depth_ = GTEST_FLAG(stack_trace_depth);
     stream_result_to_ = GTEST_FLAG(stream_result_to);
     throw_on_failure_ = GTEST_FLAG(throw_on_failure);
   }
testing::internal::GTestFlagSaver::~GTestFlagSaver () inline
Definition at line 186 of file gtest-internal-inl.h.
References also_run_disabled_tests_, folly::test::begin(), break_on_failure_, c, catch_exceptions_, testing::internal::CodePointToUtf8(), color_, count, testing::internal::CountIf(), death_test_style_, death_test_use_fork_, folly::test::end(), folly::pushmi::operators::filter, filter_, for_each(), testing::internal::ForEach(), testing::internal::Random::Generate(), testing::internal::GetElementOr(), GTEST_API_, testing::internal::GTEST_ATTRIBUTE_UNUSED_, GTEST_CHECK_, GTEST_FLAG, i, testing::internal::Int32FromEnvOrDie(), internal_run_death_test_, list_tests_, gmock_output_test::output, output_, print_time_, random(), random_seed_, repeat(), repeat_, testing::internal::ShouldRunTestOnShard(), testing::internal::ShouldShard(), testing::internal::Shuffle(), shuffle_, testing::internal::ShuffleRange(), folly::size(), stack_trace_depth_, stream_result_to_, string, folly::f14::swap(), throw_on_failure_, testing::internal::WideStringToUtf8(), and testing::internal::WriteToShardStatusFileIfNeeded().
                     {
     GTEST_FLAG(also_run_disabled_tests) = also_run_disabled_tests_;
     GTEST_FLAG(break_on_failure) = break_on_failure_;
     GTEST_FLAG(catch_exceptions) = catch_exceptions_;
     GTEST_FLAG(color) = color_;
     GTEST_FLAG(death_test_style) = death_test_style_;
     GTEST_FLAG(death_test_use_fork) = death_test_use_fork_;
     GTEST_FLAG(filter) = filter_;
     GTEST_FLAG(internal_run_death_test) = internal_run_death_test_;
     GTEST_FLAG(list_tests) = list_tests_;
     GTEST_FLAG(output) = output_;
     GTEST_FLAG(print_time) = print_time_;
     GTEST_FLAG(random_seed) = random_seed_;
     GTEST_FLAG(repeat) = repeat_;
     GTEST_FLAG(shuffle) = shuffle_;
     GTEST_FLAG(stack_trace_depth) = stack_trace_depth_;
     GTEST_FLAG(stream_result_to) = stream_result_to_;
     GTEST_FLAG(throw_on_failure) = throw_on_failure_;
   }
Member Data Documentation
bool testing::internal::GTestFlagSaver::also_run_disabled_tests_ private
Definition at line 208 of file gtest-internal-inl.h.
Referenced by GTestFlagSaver(), and ~GTestFlagSaver().
bool testing::internal::GTestFlagSaver::break_on_failure_ private
Definition at line 209 of file gtest-internal-inl.h.
Referenced by GTestFlagSaver(), and ~GTestFlagSaver().
bool testing::internal::GTestFlagSaver::catch_exceptions_ private
Definition at line 210 of file gtest-internal-inl.h.
Referenced by testing::internal::UnitTestImpl::catch_exceptions(), GTestFlagSaver(), testing::internal::UnitTestImpl::set_catch_exceptions(), and ~GTestFlagSaver().
std::string testing::internal::GTestFlagSaver::color_ private
Definition at line 211 of file gtest-internal-inl.h.
Referenced by GTestFlagSaver(), and ~GTestFlagSaver().
std::string testing::internal::GTestFlagSaver::death_test_style_ private
Definition at line 212 of file gtest-internal-inl.h.
Referenced by GTestFlagSaver(), and ~GTestFlagSaver().
bool testing::internal::GTestFlagSaver::death_test_use_fork_ private
Definition at line 213 of file gtest-internal-inl.h.
Referenced by GTestFlagSaver(), and ~GTestFlagSaver().
std::string testing::internal::GTestFlagSaver::filter_ private
Definition at line 214 of file gtest-internal-inl.h.
Referenced by GTestFlagSaver(), and ~GTestFlagSaver().
std::string testing::internal::GTestFlagSaver::internal_run_death_test_ private
Definition at line 215 of file gtest-internal-inl.h.
Referenced by GTestFlagSaver(), and ~GTestFlagSaver().
bool testing::internal::GTestFlagSaver::list_tests_ private
Definition at line 216 of file gtest-internal-inl.h.
Referenced by GTestFlagSaver(), and ~GTestFlagSaver().
std::string testing::internal::GTestFlagSaver::output_ private
Definition at line 217 of file gtest-internal-inl.h.
Referenced by GTestFlagSaver(), and ~GTestFlagSaver().
bool testing::internal::GTestFlagSaver::print_time_ private
Definition at line 218 of file gtest-internal-inl.h.
Referenced by GTestFlagSaver(), and ~GTestFlagSaver().
internal::Int32 testing::internal::GTestFlagSaver::random_seed_ private
Definition at line 219 of file gtest-internal-inl.h.
Referenced by GTestFlagSaver(), testing::internal::UnitTestImpl::random_seed(), testing::internal::UnitTestImpl::set_catch_exceptions(), and ~GTestFlagSaver().
internal::Int32 testing::internal::GTestFlagSaver::repeat_ private
Definition at line 220 of file gtest-internal-inl.h.
Referenced by GTestFlagSaver(), and ~GTestFlagSaver().
bool testing::internal::GTestFlagSaver::shuffle_ private
Definition at line 221 of file gtest-internal-inl.h.
Referenced by GTestFlagSaver(), and ~GTestFlagSaver().
internal::Int32 testing::internal::GTestFlagSaver::stack_trace_depth_ private
Definition at line 222 of file gtest-internal-inl.h.
Referenced by GTestFlagSaver(), and ~GTestFlagSaver().
std::string testing::internal::GTestFlagSaver::stream_result_to_ private
Definition at line 223 of file gtest-internal-inl.h.
Referenced by GTestFlagSaver(), and ~GTestFlagSaver().
bool testing::internal::GTestFlagSaver::throw_on_failure_ private
Definition at line 224 of file gtest-internal-inl.h.
Referenced by GTestFlagSaver(), and ~GTestFlagSaver().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest-internal-inl.h