proxygen: folly::AttachDetachClient Class Reference
folly::AttachDetachClient Class Reference
Public Member Functions
AttachDetachClient (const folly::SocketAddress &address)
Future< bool > getFuture ()
void connect ()
void connectSuccess () noexceptoverride
void connectErr (const AsyncSocketException &ex) noexceptoverride
void writeSuccess () noexceptoverride
void writeErr (size_t, const AsyncSocketException &ex) noexceptoverride
void getReadBuffer (void **bufReturn, size_t *lenReturn) override
void readEOF () noexceptoverride
void readErr (const AsyncSocketException &ex) noexceptoverride
void readDataAvailable (size_t len) noexceptoverride
Public Member Functions inherited from folly::AsyncSocket::ConnectCallback
virtual ~ConnectCallback ()=default
Public Member Functions inherited from folly::AsyncWriter::WriteCallback
virtual ~WriteCallback ()=default
Public Member Functions inherited from folly::AsyncReader::ReadCallback
virtual ~ReadCallback ()=default
virtual bool isBufferMovable () noexcept
virtual size_t maxBufferSize () const
virtual void readBufferAvailable (std::unique_ptr< IOBuf >) noexcept
Private Member Functions
void detach ()
Private Attributes
EvbAndContext t1_
EvbAndContext t2_
std::shared_ptr< AsyncSSLSocket > sslSocket_
folly::SocketAddress address_
char buf_ [128]
char readbuf_ [128]
uint32_t bytesRead_
folly::Promise< bool > promise_
Detailed Description
Definition at line 61 of file AsyncSSLSocketTest2.cpp.
Constructor & Destructor Documentation
folly::AttachDetachClient::AttachDetachClient (const folly::SocketAddress & address) inline explicit
Definition at line 83 of file AsyncSSLSocketTest2.cpp.
       : address_(address), bytesRead_(0) {}
Member Function Documentation
void folly::AttachDetachClient::connect () inline
Definition at line 90 of file AsyncSSLSocketTest2.cpp.
References folly::EvbAndContext::attach(), folly::EvbAndContext::createSocket(), folly::EvbAndContext::ctx_, folly::EvbAndContext::getEventBase(), i, and folly::EventBase::runInEventBaseThread().
                  {
     // create in one and then move to another
     auto t1Evb = t1_.getEventBase();
     t1Evb->runInEventBaseThread([this] {
       sslSocket_ = t1_.createSocket();
       // ensure we can detach and reattach the context before connecting
       for (int i = 0; i < 1000; ++i) {
         sslSocket_->detachSSLContext();
         sslSocket_->attachSSLContext(t1_.ctx_);
       }
       // detach from t1 and connect in t2
       detach();
       auto t2Evb = t2_.getEventBase();
       t2Evb->runInEventBaseThread([this] {
         t2_.attach(*sslSocket_);
         sslSocket_->connect(this, address_);
       });
     });
   }
void folly::AttachDetachClient::connectErr (const AsyncSocketException & ex) inline override virtual noexcept
connectErr() will be invoked if the connection attempt fails.
Parameters
ex An exception describing the error that occurred.
Implements folly::AsyncSocket::ConnectCallback.
Definition at line 133 of file AsyncSSLSocketTest2.cpp.
{
     cerr << "AttachDetachClient::connectError: " << ex.what() << endl;
     sslSocket_.reset();
   }
void folly::AttachDetachClient::connectSuccess () inline override virtual noexcept
connectSuccess() will be invoked when the connection has been successfully established.
Implements folly::AsyncSocket::ConnectCallback.
Definition at line 110 of file AsyncSSLSocketTest2.cpp.
References folly::EvbAndContext::attach(), folly::EvbAndContext::ctx_, EXPECT_TRUE, folly::EvbAndContext::getEventBase(), i, and folly::EventBase::runInEventBaseThread().
{
     auto t2Evb = t2_.getEventBase();
     EXPECT_TRUE(t2Evb->isInEventBaseThread());
     cerr << "client SSL socket connected" << endl;
     for (int i = 0; i < 1000; ++i) {
       sslSocket_->detachSSLContext();
       sslSocket_->attachSSLContext(t2_.ctx_);
     }
     // detach from t2 and then read/write in t1
     t2Evb->runInEventBaseThread([this] {
       detach();
       auto t1Evb = t1_.getEventBase();
       t1Evb->runInEventBaseThread([this] {
         t1_.attach(*sslSocket_);
         sslSocket_->write(this, buf_, sizeof(buf_));
         sslSocket_->setReadCB(this);
         memset(readbuf_, 'b', sizeof(readbuf_));
         bytesRead_ = 0;
       });
     });
   }
void folly::AttachDetachClient::detach () inline private
Definition at line 77 of file AsyncSSLSocketTest2.cpp.
                 {
     sslSocket_->detachEventBase();
     sslSocket_->detachSSLContext();
   }
Future<bool> folly::AttachDetachClient::getFuture () inline
Definition at line 86 of file AsyncSSLSocketTest2.cpp.
References folly::Promise< T >::getFuture().
{
     return promise_.getFuture();
   }
void folly::AttachDetachClient::getReadBuffer (void ** bufReturn, size_t * lenReturn) inline override virtual
When data becomes available, getReadBuffer() will be invoked to get the buffer into which data should be read.
This method allows the ReadCallback to delay buffer allocation until data becomes available. This allows applications to manage large numbers of idle connections, without having to maintain a separate read buffer for each idle connection.
It is possible that in some cases, getReadBuffer() may be called multiple times before readDataAvailable() is invoked. In this case, the data will be written to the buffer returned from the most recent call to readDataAvailable(). If the previous calls to readDataAvailable() returned different buffers, the ReadCallback is responsible for ensuring that they are not leaked.
If getReadBuffer() throws an exception, returns a nullptr buffer, or returns a 0 length, the ReadCallback will be uninstalled and its readError() method will be invoked.
getReadBuffer() is not allowed to change the transport state before it returns. (For example, it should never uninstall the read callback, or set a different read callback.)
Parameters
bufReturn getReadBuffer() should update *bufReturn to contain the address of the read buffer. This parameter will never be nullptr.
lenReturn getReadBuffer() should update *lenReturn to contain the maximum number of bytes that may be written to the read buffer. This parameter will never be nullptr.
Implements folly::AsyncReader::ReadCallback.
Definition at line 148 of file AsyncSSLSocketTest2.cpp.
{
     *bufReturn = readbuf_ + bytesRead_;
     *lenReturn = sizeof(readbuf_) - bytesRead_;
   }
void folly::AttachDetachClient::readDataAvailable (size_t len) inline override virtual noexcept
readDataAvailable() will be invoked when data has been successfully read into the buffer returned by the last call to getReadBuffer().
The read callback remains installed after readDataAvailable() returns. It must be explicitly uninstalled to stop receiving read events. getReadBuffer() will be called at least once before each call to readDataAvailable(). getReadBuffer() will also be called before any call to readEOF().
Parameters
len The number of bytes placed in the buffer.
Implements folly::AsyncReader::ReadCallback.
Definition at line 161 of file AsyncSSLSocketTest2.cpp.
References EXPECT_EQ, EXPECT_TRUE, folly::EvbAndContext::getEventBase(), folly::EventBase::isInEventBaseThread(), and folly::Promise< T >::setValue().
{
     EXPECT_TRUE(t1_.getEventBase()->isInEventBaseThread());
     EXPECT_EQ(sslSocket_->getEventBase(), t1_.getEventBase());
     cerr << "client read data: " << len << endl;
     bytesRead_ += len;
     if (len == sizeof(buf_)) {
       EXPECT_EQ(memcmp(buf_, readbuf_, bytesRead_), 0);
       sslSocket_->closeNow();
       sslSocket_.reset();
       promise_.setValue(true);
     }
   }
void folly::AttachDetachClient::readEOF () inline override virtual noexcept
readEOF() will be invoked when the transport is closed.
The read callback will be automatically uninstalled immediately before readEOF() is invoked.
Implements folly::AsyncReader::ReadCallback.
Definition at line 152 of file AsyncSSLSocketTest2.cpp.
{
     cerr << "client readEOF" << endl;
   }
void folly::AttachDetachClient::readErr (const AsyncSocketException & ex) inline override virtual noexcept
readError() will be invoked if an error occurs reading from the transport.
The read callback will be automatically uninstalled immediately before readError() is invoked.
Parameters
ex An exception describing the error that occurred.
Implements folly::AsyncReader::ReadCallback.
Definition at line 156 of file AsyncSSLSocketTest2.cpp.
References folly::Promise< T >::setException().
{
     cerr << "client readError: " << ex.what() << endl;
     promise_.setException(ex);
   }
void folly::AttachDetachClient::writeErr (size_t bytesWritten, const AsyncSocketException & ex) inline override virtual noexcept
writeError() will be invoked if an error occurs writing the data.
Parameters
bytesWritten The number of bytes that were successfull
ex An exception describing the error that occurred.
Implements folly::AsyncWriter::WriteCallback.
Definition at line 142 of file AsyncSSLSocketTest2.cpp.
{
     cerr << "client writeError: " << ex.what() << endl;
   }
void folly::AttachDetachClient::writeSuccess () inline override virtual noexcept
writeSuccess() will be invoked when all of the data has been successfully written.
Note that this mainly signals that the buffer containing the data to write is no longer needed and may be freed or re-used. It does not guarantee that the data has been fully transmitted to the remote endpoint. For example, on socket-based transports, writeSuccess() only indicates that the data has been given to the kernel for eventual transmission.
Implements folly::AsyncWriter::WriteCallback.
Definition at line 138 of file AsyncSSLSocketTest2.cpp.
{
     cerr << "client write success" << endl;
   }
Member Data Documentation
folly::SocketAddress folly::AttachDetachClient::address_ private
Definition at line 70 of file AsyncSSLSocketTest2.cpp.
char folly::AttachDetachClient::buf_[128] private
Definition at line 71 of file AsyncSSLSocketTest2.cpp.
uint32_t folly::AttachDetachClient::bytesRead_ private
Definition at line 73 of file AsyncSSLSocketTest2.cpp.
folly::Promise<bool> folly::AttachDetachClient::promise_ private
Definition at line 75 of file AsyncSSLSocketTest2.cpp.
char folly::AttachDetachClient::readbuf_[128] private
Definition at line 72 of file AsyncSSLSocketTest2.cpp.
std::shared_ptr<AsyncSSLSocket> folly::AttachDetachClient::sslSocket_ private
Definition at line 69 of file AsyncSSLSocketTest2.cpp.
EvbAndContext folly::AttachDetachClient::t1_ private
Definition at line 67 of file AsyncSSLSocketTest2.cpp.
EvbAndContext folly::AttachDetachClient::t2_ private
Definition at line 68 of file AsyncSSLSocketTest2.cpp.
The documentation for this class was generated from the following file:
proxygen/folly/folly/io/async/test/AsyncSSLSocketTest2.cpp