proxygen: LRUPersistentCacheTest< MutexT > Class Template Reference
LRUPersistentCacheTest< MutexT > Class Template Reference
Protected Member Functions
void SetUp () override
Protected Member Functions inherited from testing::Test
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Protected Attributes
unique_ptr< MockPersistenceLayer > persistence
std::shared_ptr< folly::ManualExecutor > manualExecutor
std::shared_ptr< folly::InlineExecutor > inlineExecutor
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Detailed Description
template<typename MutexT>
class LRUPersistentCacheTest< MutexT >
Definition at line 92 of file LRUPersistentCacheTest.cpp.
Member Function Documentation
template<typename MutexT > void LRUPersistentCacheTest< MutexT >::SetUp () inline override protected virtual
Reimplemented from testing::Test.
Definition at line 94 of file LRUPersistentCacheTest.cpp.
References testing::_, MockPersistenceLayer::getLastPersistedVersionConcrete(), testing::Invoke(), ON_CALL, and MockPersistenceLayer::setPersistedVersionConcrete().
{
      persistence = make_unique<MockPersistenceLayer>();
      ON_CALL(*persistence, getLastPersistedVersion())
          .WillByDefault(Invoke(
              persistence.get(),
              &MockPersistenceLayer::getLastPersistedVersionConcrete));
      ON_CALL(*persistence, setPersistedVersion(_))
          .WillByDefault(Invoke(
              persistence.get(),
              &MockPersistenceLayer::setPersistedVersionConcrete));
      manualExecutor = std::make_shared<folly::ManualExecutor>();
      inlineExecutor = std::make_shared<folly::InlineExecutor>();
    }
Member Data Documentation
template<typename MutexT > std::shared_ptr<folly::InlineExecutor> LRUPersistentCacheTest< MutexT >::inlineExecutor protected
Definition at line 110 of file LRUPersistentCacheTest.cpp.
template<typename MutexT > std::shared_ptr<folly::ManualExecutor> LRUPersistentCacheTest< MutexT >::manualExecutor protected
Definition at line 109 of file LRUPersistentCacheTest.cpp.
template<typename MutexT > unique_ptr<MockPersistenceLayer> LRUPersistentCacheTest< MutexT >::persistence protected
Definition at line 108 of file LRUPersistentCacheTest.cpp.
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/client/persistence/test/LRUPersistentCacheTest.cpp