proxygen: testing::gmock_matchers_test::DivisibleByImpl Class Reference
testing::gmock_matchers_test::DivisibleByImpl Class Reference
Public Member Functions
DivisibleByImpl (int a_divider)
template<typename T >
bool MatchAndExplain (const T &n, MatchResultListener *listener) const
void DescribeTo (ostream *os) const
void DescribeNegationTo (ostream *os) const
void set_divider (int a_divider)
int divider () const
DivisibleByImpl (int a_divider)
template<typename T >
bool MatchAndExplain (const T &n, MatchResultListener *listener) const
void DescribeTo (ostream *os) const
void DescribeNegationTo (ostream *os) const
void set_divider (int a_divider)
int divider () const
DivisibleByImpl (int a_divider)
template<typename T >
bool MatchAndExplain (const T &n, MatchResultListener *listener) const
void DescribeTo (ostream *os) const
void DescribeNegationTo (ostream *os) const
void set_divider (int a_divider)
int divider () const
Private Attributes
int divider_
Detailed Description
Definition at line 3963 of file gmock-matchers_test.cc.
Constructor & Destructor Documentation
testing::gmock_matchers_test::DivisibleByImpl::DivisibleByImpl (int a_divider) inline explicit
Definition at line 3965 of file gmock-matchers_test.cc.
 : divider_(a_divider) {}
testing::gmock_matchers_test::DivisibleByImpl::DivisibleByImpl (int a_divider) inline explicit
Definition at line 3965 of file gmock-matchers_test.cc.
 : divider_(a_divider) {}
testing::gmock_matchers_test::DivisibleByImpl::DivisibleByImpl (int a_divider) inline explicit
Definition at line 3965 of file gmock-matchers_test.cc.
 : divider_(a_divider) {}
Member Function Documentation
void testing::gmock_matchers_test::DivisibleByImpl::DescribeNegationTo (ostream * os) const inline
Definition at line 3979 of file gmock-matchers_test.cc.
{
     *os << "is not divisible by " << divider_;
   }
void testing::gmock_matchers_test::DivisibleByImpl::DescribeNegationTo (ostream * os) const inline
Definition at line 3979 of file gmock-matchers_test.cc.
{
     *os << "is not divisible by " << divider_;
   }
void testing::gmock_matchers_test::DivisibleByImpl::DescribeNegationTo (ostream * os) const inline
Definition at line 3979 of file gmock-matchers_test.cc.
{
     *os << "is not divisible by " << divider_;
   }
void testing::gmock_matchers_test::DivisibleByImpl::DescribeTo (ostream * os) const inline
Definition at line 3975 of file gmock-matchers_test.cc.
{
     *os << "is divisible by " << divider_;
   }
void testing::gmock_matchers_test::DivisibleByImpl::DescribeTo (ostream * os) const inline
Definition at line 3975 of file gmock-matchers_test.cc.
{
     *os << "is divisible by " << divider_;
   }
void testing::gmock_matchers_test::DivisibleByImpl::DescribeTo (ostream * os) const inline
Definition at line 3975 of file gmock-matchers_test.cc.
{
     *os << "is divisible by " << divider_;
   }
int testing::gmock_matchers_test::DivisibleByImpl::divider () const inline
Definition at line 3984 of file gmock-matchers_test.cc.
References testing::AllOf(), testing::gmock_matchers_test::DivisibleBy(), EXPECT_EQ, testing::gmock_matchers_test::Explain(), testing::Ge(), testing::gmock_matchers_test::GreaterThan(), testing::Le(), testing::MakePolymorphicMatcher(), and testing::internal::TEST().
 { return divider_; }
int testing::gmock_matchers_test::DivisibleByImpl::divider () const inline
Definition at line 3984 of file gmock-matchers_test.cc.
Referenced by testing::gmock_matchers_test::TEST().
 { return divider_; }
int testing::gmock_matchers_test::DivisibleByImpl::divider () const inline
Definition at line 3984 of file gmock-matchers_test.cc.
References testing::AllOf(), testing::gmock_matchers_test::DivisibleBy(), EXPECT_EQ, testing::gmock_matchers_test::Explain(), testing::Ge(), testing::gmock_matchers_test::GreaterThan(), testing::Le(), testing::MakePolymorphicMatcher(), and testing::internal::TEST().
 { return divider_; }
template<typename T > bool testing::gmock_matchers_test::DivisibleByImpl::MatchAndExplain (const T & n, MatchResultListener * listener) const inline
Definition at line 3969 of file gmock-matchers_test.cc.
{
     *listener << "which is " << (n % divider_) << " modulo "
               << divider_;
     return (n % divider_) == 0;
   }
template<typename T > bool testing::gmock_matchers_test::DivisibleByImpl::MatchAndExplain (const T & n, MatchResultListener * listener) const inline
Definition at line 3969 of file gmock-matchers_test.cc.
{
     *listener << "which is " << (n % divider_) << " modulo "
               << divider_;
     return (n % divider_) == 0;
   }
template<typename T > bool testing::gmock_matchers_test::DivisibleByImpl::MatchAndExplain (const T & n, MatchResultListener * listener) const inline
Definition at line 3969 of file gmock-matchers_test.cc.
{
     *listener << "which is " << (n % divider_) << " modulo "
               << divider_;
     return (n % divider_) == 0;
   }
void testing::gmock_matchers_test::DivisibleByImpl::set_divider (int a_divider) inline
Definition at line 3983 of file gmock-matchers_test.cc.
Referenced by testing::gmock_matchers_test::TEST().
 { divider_ = a_divider; }
void testing::gmock_matchers_test::DivisibleByImpl::set_divider (int a_divider) inline
Definition at line 3983 of file gmock-matchers_test.cc.
 { divider_ = a_divider; }
void testing::gmock_matchers_test::DivisibleByImpl::set_divider (int a_divider) inline
Definition at line 3983 of file gmock-matchers_test.cc.
 { divider_ = a_divider; }
Member Data Documentation
int testing::gmock_matchers_test::DivisibleByImpl::divider_ private
Definition at line 3987 of file gmock-matchers_test.cc.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-matchers_test.cc