proxygen: folly::python::AsyncioExecutor Class Reference
folly::python::AsyncioExecutor Class Reference
#include <AsyncioExecutor.h>
Public Types
using Func = folly::Func
Public Member Functions
~AsyncioExecutor () override
void add (Func func) override
int fileno () const
void drive () noexceptoverride
Public Member Functions inherited from folly::DrivableExecutor
~DrivableExecutor () override=default
Public Member Functions inherited from folly::Executor
virtual ~Executor ()
virtual void addWithPriority (Func, int8_t priority)
virtual uint8_t getNumPriorities () const
Protected Member Functions
bool keepAliveAcquire () override
void keepAliveRelease () override
Private Attributes
folly::NotificationQueue< Func > queue_
folly::NotificationQueue< Func >::SimpleConsumer consumer_ {queue_}
std::atomic< size_t > keepAliveCounter_ {1}
Additional Inherited Members
Static Public Member Functions inherited from folly::Executor
template<typename ExecutorT >
static KeepAlive< ExecutorT > getKeepAliveToken (ExecutorT *executor)
template<typename ExecutorT >
static KeepAlive< ExecutorT > getKeepAliveToken (ExecutorT &executor)
Static Public Attributes inherited from folly::Executor
static const int8_t LO_PRI = SCHAR_MIN
static const int8_t MID_PRI = 0
static const int8_t HI_PRI = SCHAR_MAX
Static Protected Member Functions inherited from folly::Executor
template<typename ExecutorT >
static bool isKeepAliveDummy (const KeepAlive< ExecutorT > &keepAlive)
template<typename ExecutorT >
static KeepAlive< ExecutorT > makeKeepAlive (ExecutorT *executor)
Detailed Description
Definition at line 27 of file AsyncioExecutor.h.
Member Typedef Documentation
using folly::python::AsyncioExecutor::Func = folly::Func
Definition at line 29 of file AsyncioExecutor.h.
Constructor & Destructor Documentation
folly::python::AsyncioExecutor::~AsyncioExecutor () inline override
Definition at line 31 of file AsyncioExecutor.h.
References drive(), keepAliveCounter_, and keepAliveRelease().
{
     keepAliveRelease();
     while (keepAliveCounter_ > 0) {
       drive();
     }
   }
Member Function Documentation
void folly::python::AsyncioExecutor::add (Func) inline override virtual
Enqueue a function to executed by this executor. This and all variants must be threadsafe.
Implements folly::Executor.
Definition at line 38 of file AsyncioExecutor.h.
References folly::gen::move, and queue_.
{
     queue_.putMessage(std::move(func));
   }
void folly::python::AsyncioExecutor::drive () inline override virtual noexcept
Implements folly::DrivableExecutor.
Definition at line 46 of file AsyncioExecutor.h.
References consumer_, and folly::exceptionStr().
Referenced by ~AsyncioExecutor().
{
     consumer_.consumeUntilDrained([](Func&& func) {
       try {
         func();
       } catch (...) {
         LOG(ERROR) << "Exception thrown by NotificationQueueExecutor task."
                    << "Exception message: "
                    << folly::exceptionStr(std::current_exception());
       }
     });
   }
int folly::python::AsyncioExecutor::fileno () const inline
Definition at line 42 of file AsyncioExecutor.h.
References consumer_.
                      {
     return consumer_.getFd();
   }
bool folly::python::AsyncioExecutor::keepAliveAcquire () inline override protected virtual
Reimplemented from folly::Executor.
Definition at line 59 of file AsyncioExecutor.h.
References keepAliveCounter_.
{
     auto keepAliveCounter =
         keepAliveCounter_.fetch_add(1, std::memory_order_relaxed);
     // We should never increment from 0
     DCHECK(keepAliveCounter > 0);
     return true;
   }
void folly::python::AsyncioExecutor::keepAliveRelease () inline override protected virtual
Reimplemented from folly::Executor.
Definition at line 67 of file AsyncioExecutor.h.
References keepAliveCounter_.
Referenced by ~AsyncioExecutor().
{
     auto keepAliveCounter = --keepAliveCounter_;
     DCHECK(keepAliveCounter >= 0);
   }
Member Data Documentation
folly::NotificationQueue<Func>::SimpleConsumer folly::python::AsyncioExecutor::consumer_ {queue_} private
Definition at line 74 of file AsyncioExecutor.h.
Referenced by drive(), and fileno().
std::atomic<size_t> folly::python::AsyncioExecutor::keepAliveCounter_ {1} private
Definition at line 75 of file AsyncioExecutor.h.
Referenced by keepAliveAcquire(), keepAliveRelease(), and ~AsyncioExecutor().
folly::NotificationQueue<Func> folly::python::AsyncioExecutor::queue_ private
Definition at line 73 of file AsyncioExecutor.h.
Referenced by add().
The documentation for this class was generated from the following file:
proxygen/folly/folly/python/AsyncioExecutor.h