proxygen: fizz::PlaintextWriteRecordLayer Class Reference
fizz::PlaintextWriteRecordLayer Class Reference
#include <PlaintextRecordLayer.h>
Public Member Functions
~PlaintextWriteRecordLayer () override=default
TLSContent write (TLSMessage &&msg) const override
virtual TLSContent writeInitialClientHello (Buf encodedClientHello) const
EncryptionLevel getEncryptionLevel () const override
Public Member Functions inherited from fizz::WriteRecordLayer
virtual ~WriteRecordLayer ()=default
TLSContent writeAlert (Alert &&alert) const
TLSContent writeAppData (std::unique_ptr< folly::IOBuf > &&appData) const
template<typename... Args>
TLSContent writeHandshake (Buf &&encodedHandshakeMsg, Args &&...args) const
void setProtocolVersion (ProtocolVersion version) const
Private Member Functions
TLSContent write (TLSMessage msg, ProtocolVersion recordVersion) const
Additional Inherited Members
Protected Attributes inherited from fizz::WriteRecordLayer
ProtocolVersion recordVersion_ {ProtocolVersion::tls_1_2}
bool useAdditionalData_ {true}
Detailed Description
Definition at line 44 of file PlaintextRecordLayer.h.
Constructor & Destructor Documentation
fizz::PlaintextWriteRecordLayer::~PlaintextWriteRecordLayer () override default
Member Function Documentation
EncryptionLevel fizz::PlaintextWriteRecordLayer::getEncryptionLevel () const override virtual
Returns the current encryption level of the data that the write record layer writes at.
Implements fizz::WriteRecordLayer.
Definition at line 146 of file PlaintextRecordLayer.cpp.
References fizz::Plaintext.
{
   return EncryptionLevel::Plaintext;
 }
TLSContent fizz::PlaintextWriteRecordLayer::write (TLSMessage && msg) const override virtual
Implements fizz::WriteRecordLayer.
Reimplemented in fizz::MockPlaintextWriteRecordLayer, and fizz::test::ConcreteWriteRecordLayer.
Definition at line 101 of file PlaintextRecordLayer.cpp.
References folly::gen::move, and fizz::detail::write().
{
   return write(std::move(msg), recordVersion_);
 }
TLSContent fizz::PlaintextWriteRecordLayer::write (TLSMessage msg, ProtocolVersion recordVersion) const private
Definition at line 112 of file PlaintextRecordLayer.cpp.
References fizz::application_data, fizz::TLSContent::contentType, folly::IOBuf::create(), fizz::TLSContent::data, data, fizz::TLSContent::encryptionLevel, fizz::TLSMessage::fragment, fizz::kPlaintextHeaderSize, folly::gen::move, fizz::Plaintext, fizz::TLSMessage::type, uint16_t, and folly::io::detail::Writable< Derived >::writeBE().
{
   if (msg.type == ContentType::application_data) {
     throw std::runtime_error("refusing to send plaintext application data");
   }
   auto fragment = std::move(msg.fragment);
   folly::io::Cursor cursor(fragment.get());
   std::unique_ptr<folly::IOBuf> data;
   while (!cursor.isAtEnd()) {
     Buf thisFragment;
     auto len = cursor.cloneAtMost(thisFragment, kMaxPlaintextRecordSize);
     auto header = folly::IOBuf::create(kPlaintextHeaderSize);
     folly::io::Appender appender(header.get(), kPlaintextHeaderSize);
     appender.writeBE(static_cast<ContentTypeType>(msg.type));
     appender.writeBE(static_cast<ProtocolVersionType>(recordVersion));
     appender.writeBE<uint16_t>(len);
     if (!data) {
       data = std::move(header);
     } else {
       data->prependChain(std::move(header));
     }
     data->prependChain(std::move(thisFragment));
   }
   TLSContent content;
   content.data = std::move(data);
   content.contentType = msg.type;
   content.encryptionLevel = EncryptionLevel::Plaintext;
   return content;
 }
TLSContent fizz::PlaintextWriteRecordLayer::writeInitialClientHello (Buf encodedClientHello) const virtual
Write the initial ClientHello handshake message. This is a separate method as the record encoding can be slightly different since the version has not been negotiated yet.
Reimplemented in fizz::MockPlaintextWriteRecordLayer.
Definition at line 105 of file PlaintextRecordLayer.cpp.
References fizz::handshake, folly::gen::move, fizz::tls_1_0, and fizz::detail::write().
Referenced by fizz::sm::getCertificateRequest(), and fizz::server::test::AeadCookieCipherTest::getClientHello().
{
   return write(
       TLSMessage{ContentType::handshake, std::move(encodedClientHello)},
       ProtocolVersion::tls_1_0);
 }
The documentation for this class was generated from the following files:
proxygen/fizz/fizz/record/PlaintextRecordLayer.h
proxygen/fizz/fizz/record/PlaintextRecordLayer.cpp