proxygen: folly::ThreadPoolExecutor::ThreadList Class Reference
folly::ThreadPoolExecutor::ThreadList Class Reference
#include <ThreadPoolExecutor.h>
Public Member Functions
void add (const ThreadPtr &state)
void remove (const ThreadPtr &state)
const std::vector< ThreadPtr > & get () const
Static Private Member Functions
static bool compare (const ThreadPtr &ts1, const ThreadPtr &ts2)
Private Attributes
std::vector< ThreadPtr > vec_
Detailed Description
Definition at line 229 of file ThreadPoolExecutor.h.
Member Function Documentation
void folly::ThreadPoolExecutor::ThreadList::add (const ThreadPtr & state) inline
Definition at line 231 of file ThreadPoolExecutor.h.
Referenced by folly::ThreadPoolExecutor::addThreads().
{
       auto it = std::lower_bound(
           vec_.begin(),
           vec_.end(),
           state,
           // compare method is a static method of class
           // and therefore cannot be inlined by compiler
           // as a template predicate of the STL algorithm
           // but wrapped up with the lambda function (lambda will be inlined)
           // compiler can inline compare method as well
           [&](const ThreadPtr& ts1, const ThreadPtr& ts2) -> bool { // inline
             return compare(ts1, ts2);
           });
       vec_.insert(it, state);
     }
static bool folly::ThreadPoolExecutor::ThreadList::compare (const ThreadPtr & ts1, const ThreadPtr & ts2) inline static private
Definition at line 266 of file ThreadPoolExecutor.h.
{
       return ts1->id < ts2->id;
     }
const std::vector<ThreadPtr>& folly::ThreadPoolExecutor::ThreadList::get () const inline
Definition at line 261 of file ThreadPoolExecutor.h.
Referenced by folly::IOThreadPoolExecutor::add(), folly::ThreadPoolExecutor::addObserver(), folly::IOThreadPoolExecutor::getPendingTaskCountImpl(), folly::ThreadPoolExecutor::getPoolStats(), folly::ThreadPoolExecutor::join(), folly::IOThreadPoolExecutor::pickThread(), folly::ThreadPoolExecutor::removeObserver(), folly::ThreadPoolExecutor::stop(), folly::IOThreadPoolExecutor::stopThreads(), and folly::ThreadPoolExecutor::~ThreadPoolExecutor().
{
       return vec_;
     }
void folly::ThreadPoolExecutor::ThreadList::remove (const ThreadPtr & state) inline
Definition at line 247 of file ThreadPoolExecutor.h.
References cpp.ast::next().
Referenced by folly::IOThreadPoolExecutor::stopThreads(), and folly::CPUThreadPoolExecutor::threadRun().
{
       auto itPair = std::equal_range(
           vec_.begin(),
           vec_.end(),
           state,
           // the same as above
           [&](const ThreadPtr& ts1, const ThreadPtr& ts2) -> bool { // inline
             return compare(ts1, ts2);
           });
       CHECK(itPair.first != vec_.end());
       CHECK(std::next(itPair.first) == itPair.second);
       vec_.erase(itPair.first);
     }
Member Data Documentation
std::vector<ThreadPtr> folly::ThreadPoolExecutor::ThreadList::vec_ private
Definition at line 270 of file ThreadPoolExecutor.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/executors/ThreadPoolExecutor.h