proxygen: folly::pushmi::any_many_sender< E, VN > Class Template Reference
folly::pushmi::any_many_sender< E, VN > Class Template Reference
#include <forwards.h>
Classes
union data
struct vtable
Public Types
using properties = property_set< is_sender<>, is_many<>>
Public Member Functions
any_many_sender ()=default
any_many_sender (any_many_sender &&that) noexcept
requires SenderTo< wrapped_t< Wrapped >, any_receiver< E, VN... >, is_many<> > any_many_sender (Wrapped obj) noexcept(insitu< Wrapped >())
~any_many_sender ()
any_many_sender & operator= (any_many_sender &&that) noexcept
any_executor< E > executor ()
void submit (any_receiver< E, VN... > out)
Private Types
template<class T , class U = std::decay_t<T>>
using wrapped_t = std::enable_if_t<!std::is_same< U, any_many_sender >::value, U >
Private Member Functions
template<class Wrapped >
any_many_sender (Wrapped obj, std::false_type)
template<class Wrapped >
any_many_sender (Wrapped obj, std::true_type) noexcept
Static Private Member Functions
template<class Wrapped >
static constexpr bool insitu ()
Private Attributes
union folly::pushmi::any_many_sender::data data_
vtable const * vptr_ = &noop_
Static Private Attributes
static constexpr vtable const noop_ {}
Detailed Description
template<class E, class... VN>
class folly::pushmi::any_many_sender< E, VN >
Definition at line 114 of file forwards.h.
Member Typedef Documentation
template<class E, class... VN> using folly::pushmi::any_many_sender< E, VN >::properties = property_set<is_sender<>, is_many<>>
Definition at line 96 of file many_sender.h.
template<class E, class... VN> template<class T , class U = std::decay_t<T>> using folly::pushmi::any_many_sender< E, VN >::wrapped_t = std::enable_if_t<!std::is_same<U, any_many_sender>::value, U> private
Definition at line 93 of file many_sender.h.
Constructor & Destructor Documentation
template<class E, class... VN> template<class Wrapped > folly::pushmi::any_many_sender< E, VN >::any_many_sender (Wrapped obj, std::false_type) inline private
Definition at line 49 of file many_sender.h.
References upload::const, folly::pushmi::any_many_sender< E, VN >::data_, folly::exchange(), folly::pushmi::any_many_sender< E, VN >::executor(), folly::pushmi::executor, folly::gen::move, folly::pushmi::any_many_sender< E, VN >::data::pobj_, s, folly::pushmi::any_many_sender< E, VN >::submit(), and submit.
                                               : any_many_sender() {
     struct s {
       static void op(data& src, data* dst) {
         if (dst)
           dst->pobj_ = std::exchange(src.pobj_, nullptr);
         delete static_cast<Wrapped const*>(src.pobj_);
       }
       static any_executor<E> executor(data& src) {
         return any_executor<E>{
             ::folly::pushmi::executor(*static_cast<Wrapped*>(src.pobj_))};
       }
       static void submit(data& src, any_receiver<E, VN...> out) {
         ::folly::pushmi::submit(
             *static_cast<Wrapped*>(src.pobj_), std::move(out));
       }
     };
     static const vtable vtbl{s::op, s::executor, s::submit};
     data_.pobj_ = new Wrapped(std::move(obj));
     vptr_ = &vtbl;
   }
template<class E, class... VN> template<class Wrapped > folly::pushmi::any_many_sender< E, VN >::any_many_sender (Wrapped obj, std::true_type) inline private noexcept
Definition at line 70 of file many_sender.h.
References folly::pushmi::any_many_sender< E, VN >::data::buffer_, upload::const, folly::pushmi::any_many_sender< E, VN >::data_, folly::pushmi::any_many_sender< E, VN >::executor(), folly::pushmi::executor, folly::gen::move, s, folly::pushmi::any_many_sender< E, VN >::submit(), and submit.
                                                       : any_many_sender() {
     struct s {
       static void op(data& src, data* dst) {
         if (dst)
           new (dst->buffer_)
               Wrapped(std::move(*static_cast<Wrapped*>((void*)src.buffer_)));
         static_cast<Wrapped const*>((void*)src.buffer_)->~Wrapped();
       }
       static any_executor<E> executor(data& src) {
         return any_executor<E>{::folly::pushmi::executor(
             *static_cast<Wrapped*>((void*)src.buffer_))};
       }
       static void submit(data& src, any_receiver<E, VN...> out) {
         ::folly::pushmi::submit(
             *static_cast<Wrapped*>((void*)src.buffer_), std::move(out));
       }
     };
     static const vtable vtbl{s::op, s::executor, s::submit};
     new (data_.buffer_) Wrapped(std::move(obj));
     vptr_ = &vtbl;
   }
template<class E, class... VN> folly::pushmi::any_many_sender< E, VN >::any_many_sender () default
Referenced by folly::pushmi::any_many_sender< E, VN >::operator=().
template<class E, class... VN> folly::pushmi::any_many_sender< E, VN >::any_many_sender (any_many_sender< E, VN > && that) inline noexcept
Definition at line 99 of file many_sender.h.
References folly::pushmi::any_many_sender< E, VN >::data_, folly::pushmi::any_many_sender< E, VN >::vtable::op_, folly::pushmi::PUSHMI_TEMPLATE(), folly::pushmi::requires(), folly::f14::swap(), and folly::pushmi::any_many_sender< E, VN >::vptr_.
                                                    : any_many_sender() {
     that.vptr_->op_(that.data_, &data_);
     std::swap(that.vptr_, vptr_);
   }
template<class E, class... VN> requires SenderTo< wrapped_t<Wrapped>, any_receiver<E, VN...>, is_many<> > folly::pushmi::any_many_sender< E, VN >::any_many_sender (Wrapped obj) inline explicit noexcept
Definition at line 109 of file many_sender.h.
References folly::gen::move.
       : any_many_sender{std::move(obj), bool_<insitu<Wrapped>()>{}} {}
template<class E, class... VN> folly::pushmi::any_many_sender< E, VN >::~any_many_sender () inline
Definition at line 111 of file many_sender.h.
References folly::pushmi::any_many_sender< E, VN >::data_, and folly::pushmi::any_many_sender< E, VN >::vtable::op_.
Referenced by folly::pushmi::any_many_sender< E, VN >::operator=().
                      {
     vptr_->op_(data_, nullptr);
   }
Member Function Documentation
template<class E, class... VN> any_executor<E> folly::pushmi::any_many_sender< E, VN >::executor () inline
Definition at line 119 of file many_sender.h.
References folly::pushmi::any_many_sender< E, VN >::data_, and folly::pushmi::any_many_sender< E, VN >::vtable::executor_.
Referenced by folly::pushmi::any_many_sender< E, VN >::any_many_sender().
{
     return vptr_->executor_(data_);
   }
template<class E, class... VN> template<class Wrapped > static constexpr bool folly::pushmi::any_many_sender< E, VN >::insitu () inline static private
Definition at line 32 of file many_sender.h.
References folly::pushmi::any_many_sender< E, VN >::data::buffer_, and value.
{
     return sizeof(Wrapped) <= sizeof(data::buffer_) &&
         std::is_nothrow_move_constructible<Wrapped>::value;
   }
template<class E, class... VN> any_many_sender& folly::pushmi::any_many_sender< E, VN >::operator= (any_many_sender< E, VN > && that) inline noexcept
Definition at line 114 of file many_sender.h.
References folly::pushmi::any_many_sender< E, VN >::any_many_sender(), folly::gen::move, and folly::pushmi::any_many_sender< E, VN >::~any_many_sender().
{
     this->~any_many_sender();
     new ((void*)this) any_many_sender(std::move(that));
     return *this;
   }
template<class E, class... VN> void folly::pushmi::any_many_sender< E, VN >::submit (any_receiver< E, VN... > out) inline
Definition at line 122 of file many_sender.h.
References folly::pushmi::any_many_sender< E, VN >::data_, folly::gen::move, folly::pushmi::any_many_sender< E, VN >::noop_, and folly::pushmi::any_many_sender< E, VN >::vtable::submit_.
Referenced by folly::pushmi::any_many_sender< E, VN >::any_many_sender().
{
     vptr_->submit_(data_, std::move(out));
   }
Member Data Documentation
template<class E, class... VN> union folly::pushmi::any_many_sender::data folly::pushmi::any_many_sender< E, VN >::data_ private
Referenced by folly::pushmi::any_many_sender< E, VN >::any_many_sender(), folly::pushmi::any_many_sender< E, VN >::executor(), folly::pushmi::many_sender< Data, DSF, DEXF >::PUSHMI_EXP(), folly::pushmi::any_many_sender< E, VN >::submit(), and folly::pushmi::any_many_sender< E, VN >::~any_many_sender().
template<class E, class... VN> constexpr any_many_sender< E, VN... >::vtable const folly::pushmi::any_many_sender< E, VN >::noop_ {} static private
Definition at line 46 of file many_sender.h.
Referenced by folly::pushmi::any_many_sender< E, VN >::submit().
template<class E, class... VN> vtable const* folly::pushmi::any_many_sender< E, VN >::vptr_ = &noop_ private
Definition at line 47 of file many_sender.h.
Referenced by folly::pushmi::any_many_sender< E, VN >::any_many_sender().
The documentation for this class was generated from the following files:
proxygen/folly/folly/experimental/pushmi/forwards.h
proxygen/folly/folly/experimental/pushmi/many_sender.h