proxygen: testing::internal::ExpectationBase Class Reference
testing::internal::ExpectationBase Class Reference abstract
#include <gmock-spec-builders.h>
Public Member Functions
ExpectationBase (const char *file, int line, const string &source_text)
virtual ~ExpectationBase ()
const char * file () const
int line () const
const char * source_text () const
const Cardinality & cardinality () const
void DescribeLocationTo (::std::ostream *os) const
void DescribeCallCountTo (::std::ostream *os) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
virtual void MaybeDescribeExtraMatcherTo (::std::ostream *os)=0
ExpectationBase (const char *file, int line, const string &source_text)
virtual ~ExpectationBase ()
const char * file () const
int line () const
const char * source_text () const
const Cardinality & cardinality () const
void DescribeLocationTo (::std::ostream *os) const
void DescribeCallCountTo (::std::ostream *os) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
virtual void MaybeDescribeExtraMatcherTo (::std::ostream *os)=0
ExpectationBase (const char *file, int line, const string &source_text)
virtual ~ExpectationBase ()
const char * file () const
int line () const
const char * source_text () const
const Cardinality & cardinality () const
void DescribeLocationTo (::std::ostream *os) const
void DescribeCallCountTo (::std::ostream *os) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
virtual void MaybeDescribeExtraMatcherTo (::std::ostream *os)=0
Protected Types
enum Clause {
kNone, kWith, kTimes, kInSequence,
kAfter, kWillOnce, kWillRepeatedly, kRetiresOnSaturation,
kNone, kWith, kTimes, kInSequence,
kAfter, kWillOnce, kWillRepeatedly, kRetiresOnSaturation,
kNone, kWith, kTimes, kInSequence,
kAfter, kWillOnce, kWillRepeatedly, kRetiresOnSaturation
}
enum Clause {
kNone, kWith, kTimes, kInSequence,
kAfter, kWillOnce, kWillRepeatedly, kRetiresOnSaturation,
kNone, kWith, kTimes, kInSequence,
kAfter, kWillOnce, kWillRepeatedly, kRetiresOnSaturation,
kNone, kWith, kTimes, kInSequence,
kAfter, kWillOnce, kWillRepeatedly, kRetiresOnSaturation
}
enum Clause {
kNone, kWith, kTimes, kInSequence,
kAfter, kWillOnce, kWillRepeatedly, kRetiresOnSaturation,
kNone, kWith, kTimes, kInSequence,
kAfter, kWillOnce, kWillRepeatedly, kRetiresOnSaturation,
kNone, kWith, kTimes, kInSequence,
kAfter, kWillOnce, kWillRepeatedly, kRetiresOnSaturation
}
typedef std::vector< const void * > UntypedActions
typedef std::vector< const void * > UntypedActions
typedef std::vector< const void * > UntypedActions
Protected Member Functions
virtual Expectation GetHandle ()=0
void AssertSpecProperty (bool property, const string &failure_message) const
void ExpectSpecProperty (bool property, const string &failure_message) const
void SpecifyCardinality (const Cardinality &cardinality)
bool cardinality_specified () const
void set_cardinality (const Cardinality &a_cardinality)
void RetireAllPreRequisites () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool is_retired () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void Retire () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool IsSatisfied () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool IsSaturated () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool IsOverSaturated () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool AllPrerequisitesAreSatisfied () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void FindUnsatisfiedPrerequisites (ExpectationSet *result) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
int call_count () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void IncrementCallCount () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void CheckActionCountIfNotDone () const GTEST_LOCK_EXCLUDED_(mutex_)
void UntypedTimes (const Cardinality &a_cardinality)
GTEST_DISALLOW_ASSIGN_ (ExpectationBase)
virtual Expectation GetHandle ()=0
void AssertSpecProperty (bool property, const string &failure_message) const
void ExpectSpecProperty (bool property, const string &failure_message) const
void SpecifyCardinality (const Cardinality &cardinality)
bool cardinality_specified () const
void set_cardinality (const Cardinality &a_cardinality)
void RetireAllPreRequisites () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool is_retired () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void Retire () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool IsSatisfied () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool IsSaturated () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool IsOverSaturated () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool AllPrerequisitesAreSatisfied () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void FindUnsatisfiedPrerequisites (ExpectationSet *result) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
int call_count () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void IncrementCallCount () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void CheckActionCountIfNotDone () const GTEST_LOCK_EXCLUDED_(mutex_)
void UntypedTimes (const Cardinality &a_cardinality)
GTEST_DISALLOW_ASSIGN_ (ExpectationBase)
virtual Expectation GetHandle ()=0
void AssertSpecProperty (bool property, const string &failure_message) const
void ExpectSpecProperty (bool property, const string &failure_message) const
void SpecifyCardinality (const Cardinality &cardinality)
bool cardinality_specified () const
void set_cardinality (const Cardinality &a_cardinality)
void RetireAllPreRequisites () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool is_retired () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void Retire () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool IsSatisfied () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool IsSaturated () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool IsOverSaturated () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool AllPrerequisitesAreSatisfied () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void FindUnsatisfiedPrerequisites (ExpectationSet *result) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
int call_count () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void IncrementCallCount () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void CheckActionCountIfNotDone () const GTEST_LOCK_EXCLUDED_(mutex_)
void UntypedTimes (const Cardinality &a_cardinality)
GTEST_DISALLOW_ASSIGN_ (ExpectationBase)
Protected Attributes
const char * file_
int line_
const string source_text_
bool cardinality_specified_
Cardinality cardinality_
ExpectationSet immediate_prerequisites_
int call_count_
bool retired_
UntypedActions untyped_actions_
bool extra_matcher_specified_
bool repeated_action_specified_
bool retires_on_saturation_
Clause last_clause_
bool action_count_checked_
Mutex mutex_
Friends
class ::testing::Expectation
class UntypedFunctionMockerBase
class ::testing::Sequence
class ::testing::internal::ExpectationTester
template<typename Function >
class TypedExpectation
template<typename Function >
class TypedExpectation
template<typename Function >
class TypedExpectation
Detailed Description
Definition at line 690 of file gmock-spec-builders.h.
Member Typedef Documentation
typedef std::vector<const void*> testing::internal::ExpectationBase::UntypedActions protected
Definition at line 734 of file gmock-spec-builders.h.
typedef std::vector<const void*> testing::internal::ExpectationBase::UntypedActions protected
Definition at line 734 of file gmock-spec-builders.h.
typedef std::vector<const void*> testing::internal::ExpectationBase::UntypedActions protected
Definition at line 734 of file gmock-spec-builders.h.
Member Enumeration Documentation
enum testing::internal::ExpectationBase::Clause protected
Enumerator
kNone
kWith
kTimes
kInSequence
kAfter
kWillOnce
kWillRepeatedly
kRetiresOnSaturation
kNone
kWith
kTimes
kInSequence
kAfter
kWillOnce
kWillRepeatedly
kRetiresOnSaturation
kNone
kWith
kTimes
kInSequence
kAfter
kWillOnce
kWillRepeatedly
kRetiresOnSaturation
Definition at line 722 of file gmock-spec-builders.h.
               {
     // Don't change the order of the enum members!
     kNone,
     kWith,
     kTimes,
     kInSequence,
     kAfter,
     kWillOnce,
     kWillRepeatedly,
     kRetiresOnSaturation
   };
enum testing::internal::ExpectationBase::Clause protected
Enumerator
kNone
kWith
kTimes
kInSequence
kAfter
kWillOnce
kWillRepeatedly
kRetiresOnSaturation
kNone
kWith
kTimes
kInSequence
kAfter
kWillOnce
kWillRepeatedly
kRetiresOnSaturation
kNone
kWith
kTimes
kInSequence
kAfter
kWillOnce
kWillRepeatedly
kRetiresOnSaturation
Definition at line 722 of file gmock-spec-builders.h.
               {
     // Don't change the order of the enum members!
     kNone,
     kWith,
     kTimes,
     kInSequence,
     kAfter,
     kWillOnce,
     kWillRepeatedly,
     kRetiresOnSaturation
   };
enum testing::internal::ExpectationBase::Clause protected
Enumerator
kNone
kWith
kTimes
kInSequence
kAfter
kWillOnce
kWillRepeatedly
kRetiresOnSaturation
kNone
kWith
kTimes
kInSequence
kAfter
kWillOnce
kWillRepeatedly
kRetiresOnSaturation
kNone
kWith
kTimes
kInSequence
kAfter
kWillOnce
kWillRepeatedly
kRetiresOnSaturation
Definition at line 722 of file gmock-spec-builders.h.
               {
     // Don't change the order of the enum members!
     kNone,
     kWith,
     kTimes,
     kInSequence,
     kAfter,
     kWillOnce,
     kWillRepeatedly,
     kRetiresOnSaturation
   };
Constructor & Destructor Documentation
testing::internal::ExpectationBase::ExpectationBase (const char * file, int line, const string & source_text)
Definition at line 68 of file gmock-spec-builders.cc.
     : file_(a_file),
       line_(a_line),
       source_text_(a_source_text),
       cardinality_specified_(false),
       cardinality_(Exactly(1)),
       call_count_(0),
       retired_(false),
       extra_matcher_specified_(false),
       repeated_action_specified_(false),
       retires_on_saturation_(false),
       last_clause_(kNone),
       action_count_checked_(false) {}
testing::internal::ExpectationBase::~ExpectationBase () virtual
Definition at line 85 of file gmock-spec-builders.cc.
 {}
testing::internal::ExpectationBase::ExpectationBase (const char * file, int line, const string & source_text)
virtual testing::internal::ExpectationBase::~ExpectationBase () virtual
testing::internal::ExpectationBase::ExpectationBase (const char * file, int line, const string & source_text)
virtual testing::internal::ExpectationBase::~ExpectationBase () virtual
Member Function Documentation
bool testing::internal::ExpectationBase::AllPrerequisitesAreSatisfied () const protected
Definition at line 115 of file gmock-spec-builders.cc.
References testing::ExpectationSet::begin(), testing::ExpectationSet::end(), and immediate_prerequisites_.
{
   g_gmock_mutex.AssertHeld();
   for (ExpectationSet::const_iterator it = immediate_prerequisites_.begin();
        it != immediate_prerequisites_.end(); ++it) {
     if (!(it->expectation_base()->IsSatisfied()) ||
         !(it->expectation_base()->AllPrerequisitesAreSatisfied()))
       return false;
   }
   return true;
 }
bool testing::internal::ExpectationBase::AllPrerequisitesAreSatisfied () const protected
bool testing::internal::ExpectationBase::AllPrerequisitesAreSatisfied () const protected
void testing::internal::ExpectationBase::AssertSpecProperty (bool property, const string & failure_message) const inline protected
Definition at line 741 of file gmock-spec-builders.h.
References testing::internal::Assert().
{
     Assert(property, file_, line_, failure_message);
   }
void testing::internal::ExpectationBase::AssertSpecProperty (bool property, const string & failure_message) const inline protected
Definition at line 741 of file gmock-spec-builders.h.
References testing::internal::Assert().
{
     Assert(property, file_, line_, failure_message);
   }
void testing::internal::ExpectationBase::AssertSpecProperty (bool property, const string & failure_message) const inline protected
Definition at line 741 of file gmock-spec-builders.h.
References testing::internal::Assert().
{
     Assert(property, file_, line_, failure_message);
   }
int testing::internal::ExpectationBase::call_count () const inline protected
Definition at line 815 of file gmock-spec-builders.h.
{
     g_gmock_mutex.AssertHeld();
     return call_count_;
   }
int testing::internal::ExpectationBase::call_count () const inline protected
Definition at line 815 of file gmock-spec-builders.h.
Referenced by DescribeCallCountTo().
{
     g_gmock_mutex.AssertHeld();
     return call_count_;
   }
int testing::internal::ExpectationBase::call_count () const inline protected
Definition at line 815 of file gmock-spec-builders.h.
{
     g_gmock_mutex.AssertHeld();
     return call_count_;
   }
const Cardinality& testing::internal::ExpectationBase::cardinality () const inline
Definition at line 702 of file gmock-spec-builders.h.
Referenced by CheckActionCountIfNotDone(), and DescribeCallCountTo().
 { return cardinality_; }
const Cardinality& testing::internal::ExpectationBase::cardinality () const inline
Definition at line 702 of file gmock-spec-builders.h.
 { return cardinality_; }
const Cardinality& testing::internal::ExpectationBase::cardinality () const inline
Definition at line 702 of file gmock-spec-builders.h.
 { return cardinality_; }
bool testing::internal::ExpectationBase::cardinality_specified () const inline protected
Definition at line 756 of file gmock-spec-builders.h.
 { return cardinality_specified_; }
bool testing::internal::ExpectationBase::cardinality_specified () const inline protected
Definition at line 756 of file gmock-spec-builders.h.
 { return cardinality_specified_; }
bool testing::internal::ExpectationBase::cardinality_specified () const inline protected
Definition at line 756 of file gmock-spec-builders.h.
 { return cardinality_specified_; }
void testing::internal::ExpectationBase::CheckActionCountIfNotDone () const protected
void testing::internal::ExpectationBase::CheckActionCountIfNotDone () const protected
Definition at line 173 of file gmock-spec-builders.cc.
References action_count_checked_, cardinality(), cardinality_specified_, testing::Cardinality::ConservativeLowerBound(), testing::Cardinality::ConservativeUpperBound(), DescribeLocationTo(), testing::Cardinality::DescribeTo(), testing::internal::kWarning, testing::internal::Log(), repeated_action_specified_, source_text(), and untyped_actions_.
{
   bool should_check = false;
   {
     MutexLock l(&mutex_);
     if (!action_count_checked_) {
       action_count_checked_ = true;
       should_check = true;
     }
   }
   if (should_check) {
     if (!cardinality_specified_) {
       // The cardinality was inferred - no need to check the action
       // count against it.
       return;
     }
     // The cardinality was explicitly specified.
     const int action_count = static_cast<int>(untyped_actions_.size());
     const int upper_bound = cardinality().ConservativeUpperBound();
     const int lower_bound = cardinality().ConservativeLowerBound();
     bool too_many;  // True if there are too many actions, or false
     // if there are too few.
     if (action_count > upper_bound ||
         (action_count == upper_bound && repeated_action_specified_)) {
       too_many = true;
     } else if (0 < action_count && action_count < lower_bound &&
                !repeated_action_specified_) {
       too_many = false;
     } else {
       return;
     }
     ::std::stringstream ss;
     DescribeLocationTo(&ss);
     ss << "Too " << (too_many ? "many" : "few")
        << " actions specified in " << source_text() << "...\n"
        << "Expected to be ";
     cardinality().DescribeTo(&ss);
     ss << ", but has " << (too_many ? "" : "only ")
        << action_count << " WillOnce()"
        << (action_count == 1 ? "" : "s");
     if (repeated_action_specified_) {
       ss << " and a WillRepeatedly()";
     }
     ss << ".";
     Log(kWarning, ss.str(), -1);  // -1 means "don't print stack trace".
   }
 }
void testing::internal::ExpectationBase::CheckActionCountIfNotDone () const protected
void testing::internal::ExpectationBase::DescribeCallCountTo (::std::ostream * os) const
void testing::internal::ExpectationBase::DescribeCallCountTo (::std::ostream * os) const
Definition at line 150 of file gmock-spec-builders.cc.
References call_count(), cardinality(), testing::Cardinality::DescribeActualCallCountTo(), testing::Cardinality::DescribeTo(), is_retired(), IsOverSaturated(), IsSatisfied(), and IsSaturated().
Referenced by testing::internal::FunctionMockerBase< R(A1, A2)>::PrintTriedExpectationsLocked(), and testing::internal::UntypedFunctionMockerBase::VerifyAndClearExpectationsLocked().
{
   g_gmock_mutex.AssertHeld();
   // Describes how many times the function is expected to be called.
   *os << "         Expected: to be ";
   cardinality().DescribeTo(os);
   *os << "\n           Actual: ";
   Cardinality::DescribeActualCallCountTo(call_count(), os);
   // Describes the state of the expectation (e.g. is it satisfied?
   // is it active?).
   *os << " - " << (IsOverSaturated() ? "over-saturated" :
                    IsSaturated() ? "saturated" :
                    IsSatisfied() ? "satisfied" : "unsatisfied")
       << " and "
       << (is_retired() ? "retired" : "active");
 }
void testing::internal::ExpectationBase::DescribeCallCountTo (::std::ostream * os) const
void testing::internal::ExpectationBase::DescribeLocationTo (::std::ostream * os) const inline
Definition at line 705 of file gmock-spec-builders.h.
References testing::internal::FormatFileLocation(), and GTEST_EXCLUSIVE_LOCK_REQUIRED_.
Referenced by CheckActionCountIfNotDone(), testing::internal::FunctionMockerBase< R(A1, A2)>::PrintTriedExpectationsLocked(), and testing::internal::UntypedFunctionMockerBase::UntypedInvokeWith().
{
     *os << FormatFileLocation(file(), line()) << " ";
   }
void testing::internal::ExpectationBase::DescribeLocationTo (::std::ostream * os) const inline
Definition at line 705 of file gmock-spec-builders.h.
References testing::internal::FormatFileLocation(), and GTEST_EXCLUSIVE_LOCK_REQUIRED_.
{
     *os << FormatFileLocation(file(), line()) << " ";
   }
void testing::internal::ExpectationBase::DescribeLocationTo (::std::ostream * os) const inline
Definition at line 705 of file gmock-spec-builders.h.
References testing::internal::FormatFileLocation(), and GTEST_EXCLUSIVE_LOCK_REQUIRED_.
{
     *os << FormatFileLocation(file(), line()) << " ";
   }
void testing::internal::ExpectationBase::ExpectSpecProperty (bool property, const string & failure_message) const inline protected
Definition at line 746 of file gmock-spec-builders.h.
References testing::internal::Expect().
{
     Expect(property, file_, line_, failure_message);
   }
void testing::internal::ExpectationBase::ExpectSpecProperty (bool property, const string & failure_message) const inline protected
Definition at line 746 of file gmock-spec-builders.h.
References testing::internal::Expect().
Referenced by UntypedTimes().
{
     Expect(property, file_, line_, failure_message);
   }
void testing::internal::ExpectationBase::ExpectSpecProperty (bool property, const string & failure_message) const inline protected
Definition at line 746 of file gmock-spec-builders.h.
References testing::internal::Expect().
{
     Expect(property, file_, line_, failure_message);
   }
const char* testing::internal::ExpectationBase::file () const inline
Definition at line 698 of file gmock-spec-builders.h.
Referenced by testing::internal::UntypedFunctionMockerBase::UntypedInvokeWith(), and testing::internal::UntypedFunctionMockerBase::VerifyAndClearExpectationsLocked().
 { return file_; }
const char* testing::internal::ExpectationBase::file () const inline
Definition at line 698 of file gmock-spec-builders.h.
 { return file_; }
const char* testing::internal::ExpectationBase::file () const inline
Definition at line 698 of file gmock-spec-builders.h.
 { return file_; }
void testing::internal::ExpectationBase::FindUnsatisfiedPrerequisites (ExpectationSet * result) const protected
void testing::internal::ExpectationBase::FindUnsatisfiedPrerequisites (ExpectationSet * result) const protected
Definition at line 128 of file gmock-spec-builders.cc.
References testing::ExpectationSet::begin(), testing::ExpectationSet::end(), and immediate_prerequisites_.
{
   g_gmock_mutex.AssertHeld();
   for (ExpectationSet::const_iterator it = immediate_prerequisites_.begin();
        it != immediate_prerequisites_.end(); ++it) {
     if (it->expectation_base()->IsSatisfied()) {
       // If *it is satisfied and has a call count of 0, some of its
       // pre-requisites may not be satisfied yet.
       if (it->expectation_base()->call_count_ == 0) {
         it->expectation_base()->FindUnsatisfiedPrerequisites(result);
       }
     } else {
       // Now that we know *it is unsatisfied, we are not so interested
       // in whether its pre-requisites are satisfied.  Therefore we
       // don't recursively call FindUnsatisfiedPrerequisites() here.
       *result += *it;
     }
   }
 }
void testing::internal::ExpectationBase::FindUnsatisfiedPrerequisites (ExpectationSet * result) const protected
virtual Expectation testing::internal::ExpectationBase::GetHandle () protected pure virtual
Implemented in testing::internal::TypedExpectation< F >, testing::internal::TypedExpectation< F >, and testing::internal::TypedExpectation< F >.
virtual Expectation testing::internal::ExpectationBase::GetHandle () protected pure virtual
Implemented in testing::internal::TypedExpectation< F >, testing::internal::TypedExpectation< F >, and testing::internal::TypedExpectation< F >.
Referenced by testing::internal::FunctionMockerBase< R(A1, A2)>::PrintTriedExpectationsLocked().
virtual Expectation testing::internal::ExpectationBase::GetHandle () protected pure virtual
Implemented in testing::internal::TypedExpectation< F >, testing::internal::TypedExpectation< F >, and testing::internal::TypedExpectation< F >.
testing::internal::ExpectationBase::GTEST_DISALLOW_ASSIGN_ (ExpectationBase) protected
testing::internal::ExpectationBase::GTEST_DISALLOW_ASSIGN_ (ExpectationBase) protected
testing::internal::ExpectationBase::GTEST_DISALLOW_ASSIGN_ (ExpectationBase) protected
void testing::internal::ExpectationBase::IncrementCallCount () inline protected
Definition at line 822 of file gmock-spec-builders.h.
References GTEST_LOCK_EXCLUDED_, and mutex_.
{
     g_gmock_mutex.AssertHeld();
     call_count_++;
   }
void testing::internal::ExpectationBase::IncrementCallCount () inline protected
Definition at line 822 of file gmock-spec-builders.h.
References GTEST_LOCK_EXCLUDED_, and mutex_.
{
     g_gmock_mutex.AssertHeld();
     call_count_++;
   }
void testing::internal::ExpectationBase::IncrementCallCount () inline protected
Definition at line 822 of file gmock-spec-builders.h.
References GTEST_LOCK_EXCLUDED_, and mutex_.
{
     g_gmock_mutex.AssertHeld();
     call_count_++;
   }
bool testing::internal::ExpectationBase::is_retired () const inline protected
Definition at line 772 of file gmock-spec-builders.h.
{
     g_gmock_mutex.AssertHeld();
     return retired_;
   }
bool testing::internal::ExpectationBase::is_retired () const inline protected
Definition at line 772 of file gmock-spec-builders.h.
{
     g_gmock_mutex.AssertHeld();
     return retired_;
   }
bool testing::internal::ExpectationBase::is_retired () const inline protected
Definition at line 772 of file gmock-spec-builders.h.
Referenced by DescribeCallCountTo(), and RetireAllPreRequisites().
{
     g_gmock_mutex.AssertHeld();
     return retired_;
   }
bool testing::internal::ExpectationBase::IsOverSaturated () const inline protected
Definition at line 800 of file gmock-spec-builders.h.
References GTEST_EXCLUSIVE_LOCK_REQUIRED_, and testing::Cardinality::IsOverSaturatedByCallCount().
{
     g_gmock_mutex.AssertHeld();
     return cardinality().IsOverSaturatedByCallCount(call_count_);
   }
bool testing::internal::ExpectationBase::IsOverSaturated () const inline protected
Definition at line 800 of file gmock-spec-builders.h.
References GTEST_EXCLUSIVE_LOCK_REQUIRED_, and testing::Cardinality::IsOverSaturatedByCallCount().
Referenced by DescribeCallCountTo(), and testing::internal::UntypedFunctionMockerBase::VerifyAndClearExpectationsLocked().
{
     g_gmock_mutex.AssertHeld();
     return cardinality().IsOverSaturatedByCallCount(call_count_);
   }
bool testing::internal::ExpectationBase::IsOverSaturated () const inline protected
Definition at line 800 of file gmock-spec-builders.h.
References GTEST_EXCLUSIVE_LOCK_REQUIRED_, and testing::Cardinality::IsOverSaturatedByCallCount().
{
     g_gmock_mutex.AssertHeld();
     return cardinality().IsOverSaturatedByCallCount(call_count_);
   }
bool testing::internal::ExpectationBase::IsSatisfied () const inline protected
Definition at line 786 of file gmock-spec-builders.h.
References testing::Cardinality::IsSatisfiedByCallCount().
Referenced by DescribeCallCountTo(), and testing::internal::UntypedFunctionMockerBase::VerifyAndClearExpectationsLocked().
{
     g_gmock_mutex.AssertHeld();
     return cardinality().IsSatisfiedByCallCount(call_count_);
   }
bool testing::internal::ExpectationBase::IsSatisfied () const inline protected
Definition at line 786 of file gmock-spec-builders.h.
References testing::Cardinality::IsSatisfiedByCallCount().
{
     g_gmock_mutex.AssertHeld();
     return cardinality().IsSatisfiedByCallCount(call_count_);
   }
bool testing::internal::ExpectationBase::IsSatisfied () const inline protected
Definition at line 786 of file gmock-spec-builders.h.
References testing::Cardinality::IsSatisfiedByCallCount().
{
     g_gmock_mutex.AssertHeld();
     return cardinality().IsSatisfiedByCallCount(call_count_);
   }
bool testing::internal::ExpectationBase::IsSaturated () const inline protected
Definition at line 793 of file gmock-spec-builders.h.
References testing::Cardinality::IsSaturatedByCallCount().
{
     g_gmock_mutex.AssertHeld();
     return cardinality().IsSaturatedByCallCount(call_count_);
   }
bool testing::internal::ExpectationBase::IsSaturated () const inline protected
Definition at line 793 of file gmock-spec-builders.h.
References testing::Cardinality::IsSaturatedByCallCount().
Referenced by DescribeCallCountTo(), and testing::internal::FunctionMockerBase< R(A1, A2)>::UntypedFindMatchingExpectation().
{
     g_gmock_mutex.AssertHeld();
     return cardinality().IsSaturatedByCallCount(call_count_);
   }
bool testing::internal::ExpectationBase::IsSaturated () const inline protected
Definition at line 793 of file gmock-spec-builders.h.
References testing::Cardinality::IsSaturatedByCallCount().
{
     g_gmock_mutex.AssertHeld();
     return cardinality().IsSaturatedByCallCount(call_count_);
   }
int testing::internal::ExpectationBase::line () const inline
Definition at line 699 of file gmock-spec-builders.h.
 { return line_; }
int testing::internal::ExpectationBase::line () const inline
Definition at line 699 of file gmock-spec-builders.h.
 { return line_; }
int testing::internal::ExpectationBase::line () const inline
Definition at line 699 of file gmock-spec-builders.h.
Referenced by testing::internal::UntypedFunctionMockerBase::UntypedInvokeWith(), and testing::internal::UntypedFunctionMockerBase::VerifyAndClearExpectationsLocked().
 { return line_; }
virtual void testing::internal::ExpectationBase::MaybeDescribeExtraMatcherTo (::std::ostream * os) pure virtual
Implemented in testing::internal::TypedExpectation< F >, testing::internal::TypedExpectation< F >, and testing::internal::TypedExpectation< F >.
virtual void testing::internal::ExpectationBase::MaybeDescribeExtraMatcherTo (::std::ostream * os) pure virtual
Implemented in testing::internal::TypedExpectation< F >, testing::internal::TypedExpectation< F >, and testing::internal::TypedExpectation< F >.
Referenced by testing::internal::UntypedFunctionMockerBase::VerifyAndClearExpectationsLocked().
virtual void testing::internal::ExpectationBase::MaybeDescribeExtraMatcherTo (::std::ostream * os) pure virtual
Implemented in testing::internal::TypedExpectation< F >, testing::internal::TypedExpectation< F >, and testing::internal::TypedExpectation< F >.
void testing::internal::ExpectationBase::Retire () inline protected
Definition at line 779 of file gmock-spec-builders.h.
Referenced by RetireAllPreRequisites().
{
     g_gmock_mutex.AssertHeld();
     retired_ = true;
   }
void testing::internal::ExpectationBase::Retire () inline protected
Definition at line 779 of file gmock-spec-builders.h.
{
     g_gmock_mutex.AssertHeld();
     retired_ = true;
   }
void testing::internal::ExpectationBase::Retire () inline protected
Definition at line 779 of file gmock-spec-builders.h.
{
     g_gmock_mutex.AssertHeld();
     retired_ = true;
   }
void testing::internal::ExpectationBase::RetireAllPreRequisites () protected
Definition at line 95 of file gmock-spec-builders.cc.
References testing::ExpectationSet::begin(), testing::ExpectationSet::end(), immediate_prerequisites_, is_retired(), Retire(), and RetireAllPreRequisites().
Referenced by RetireAllPreRequisites().
{
   if (is_retired()) {
     // We can take this short-cut as we never retire an expectation
     // until we have retired all its pre-requisites.
     return;
   }
   for (ExpectationSet::const_iterator it = immediate_prerequisites_.begin();
        it != immediate_prerequisites_.end(); ++it) {
     ExpectationBase* const prerequisite = it->expectation_base().get();
     if (!prerequisite->is_retired()) {
       prerequisite->RetireAllPreRequisites();
       prerequisite->Retire();
     }
   }
 }
void testing::internal::ExpectationBase::RetireAllPreRequisites () protected
void testing::internal::ExpectationBase::RetireAllPreRequisites () protected
void testing::internal::ExpectationBase::set_cardinality (const Cardinality & a_cardinality) inline protected
Definition at line 759 of file gmock-spec-builders.h.
References GTEST_EXCLUSIVE_LOCK_REQUIRED_.
{
     cardinality_ = a_cardinality;
   }
void testing::internal::ExpectationBase::set_cardinality (const Cardinality & a_cardinality) inline protected
Definition at line 759 of file gmock-spec-builders.h.
References GTEST_EXCLUSIVE_LOCK_REQUIRED_.
{
     cardinality_ = a_cardinality;
   }
void testing::internal::ExpectationBase::set_cardinality (const Cardinality & a_cardinality) inline protected
Definition at line 759 of file gmock-spec-builders.h.
References GTEST_EXCLUSIVE_LOCK_REQUIRED_.
{
     cardinality_ = a_cardinality;
   }
const char* testing::internal::ExpectationBase::source_text () const inline
Definition at line 700 of file gmock-spec-builders.h.
 { return source_text_.c_str(); }
const char* testing::internal::ExpectationBase::source_text () const inline
Definition at line 700 of file gmock-spec-builders.h.
Referenced by CheckActionCountIfNotDone(), testing::internal::FunctionMockerBase< R(A1, A2)>::PrintTriedExpectationsLocked(), and testing::internal::UntypedFunctionMockerBase::VerifyAndClearExpectationsLocked().
 { return source_text_.c_str(); }
const char* testing::internal::ExpectationBase::source_text () const inline
Definition at line 700 of file gmock-spec-builders.h.
 { return source_text_.c_str(); }
void testing::internal::ExpectationBase::SpecifyCardinality (const Cardinality & cardinality) protected
void testing::internal::ExpectationBase::SpecifyCardinality (const Cardinality & cardinality) protected
Definition at line 89 of file gmock-spec-builders.cc.
References cardinality_, and cardinality_specified_.
Referenced by UntypedTimes().
{
   cardinality_specified_ = true;
   cardinality_ = a_cardinality;
 }
void testing::internal::ExpectationBase::SpecifyCardinality (const Cardinality & cardinality) protected
void testing::internal::ExpectationBase::UntypedTimes (const Cardinality & a_cardinality) protected
void testing::internal::ExpectationBase::UntypedTimes (const Cardinality & a_cardinality) protected
void testing::internal::ExpectationBase::UntypedTimes (const Cardinality & a_cardinality) protected
Definition at line 225 of file gmock-spec-builders.cc.
References ExpectSpecProperty(), kTimes, last_clause_, and SpecifyCardinality().
Referenced by testing::internal::TypedExpectation< F >::Times().
{
   if (last_clause_ == kTimes) {
     ExpectSpecProperty(false,
                        ".Times() cannot appear "
                        "more than once in an EXPECT_CALL().");
   } else {
     ExpectSpecProperty(last_clause_ < kTimes,
                        ".Times() cannot appear after "
                        ".InSequence(), .WillOnce(), .WillRepeatedly(), "
                        "or .RetiresOnSaturation().");
   }
   last_clause_ = kTimes;
   SpecifyCardinality(a_cardinality);
 }
Friends And Related Function Documentation
friend class ::testing::Expectation friend
Definition at line 719 of file gmock-spec-builders.h.
friend class ::testing::internal::ExpectationTester friend
Definition at line 836 of file gmock-spec-builders.h.
friend class ::testing::Sequence friend
Definition at line 835 of file gmock-spec-builders.h.
template<typename Function > friend class TypedExpectation friend
Definition at line 839 of file gmock-spec-builders.h.
template<typename Function > class TypedExpectation () friend
Definition at line 839 of file gmock-spec-builders.h.
template<typename Function > class TypedExpectation () friend
Definition at line 839 of file gmock-spec-builders.h.
UntypedFunctionMockerBase friend
Definition at line 720 of file gmock-spec-builders.h.
Member Data Documentation
bool testing::internal::ExpectationBase::action_count_checked_ mutable protected
Definition at line 869 of file gmock-spec-builders.h.
Referenced by CheckActionCountIfNotDone().
int testing::internal::ExpectationBase::call_count_ protected
Definition at line 862 of file gmock-spec-builders.h.
Referenced by testing::internal::ExpectationTester::SetCallCount().
Cardinality testing::internal::ExpectationBase::cardinality_ protected
Definition at line 851 of file gmock-spec-builders.h.
Referenced by SpecifyCardinality().
bool testing::internal::ExpectationBase::cardinality_specified_ protected
Definition at line 850 of file gmock-spec-builders.h.
Referenced by CheckActionCountIfNotDone(), and SpecifyCardinality().
bool testing::internal::ExpectationBase::extra_matcher_specified_ protected
Definition at line 865 of file gmock-spec-builders.h.
const char * testing::internal::ExpectationBase::file_ protected
Definition at line 846 of file gmock-spec-builders.h.
ExpectationSet testing::internal::ExpectationBase::immediate_prerequisites_ protected
Definition at line 858 of file gmock-spec-builders.h.
Referenced by testing::Sequence::AddExpectation(), AllPrerequisitesAreSatisfied(), FindUnsatisfiedPrerequisites(), and RetireAllPreRequisites().
Clause testing::internal::ExpectationBase::last_clause_ protected
Definition at line 868 of file gmock-spec-builders.h.
Referenced by UntypedTimes().
int testing::internal::ExpectationBase::line_ protected
Definition at line 847 of file gmock-spec-builders.h.
Mutex testing::internal::ExpectationBase::mutex_ mutable protected
Definition at line 870 of file gmock-spec-builders.h.
bool testing::internal::ExpectationBase::repeated_action_specified_ protected
Definition at line 866 of file gmock-spec-builders.h.
Referenced by CheckActionCountIfNotDone().
bool testing::internal::ExpectationBase::retired_ protected
Definition at line 863 of file gmock-spec-builders.h.
bool testing::internal::ExpectationBase::retires_on_saturation_ protected
Definition at line 867 of file gmock-spec-builders.h.
const string testing::internal::ExpectationBase::source_text_ protected
Definition at line 848 of file gmock-spec-builders.h.
UntypedActions testing::internal::ExpectationBase::untyped_actions_ protected
Definition at line 864 of file gmock-spec-builders.h.
Referenced by CheckActionCountIfNotDone().
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-spec-builders.h
proxygen/fizz/build_/gtest/src/gtest/googlemock/src/gmock-spec-builders.cc