proxygen: folly::detail::emplace_iterator_base< Derived, EmplaceImpl, true > Class Template Reference
folly::detail::emplace_iterator_base< Derived, EmplaceImpl, true > Class Template Reference
#include <Iterator.h>
Public Member Functions
template<typename... Args>
Derived & operator= (std::pair< Args... > &args)
template<typename... Args>
Derived & operator= (const std::pair< Args... > &args)
template<typename... Args>
Derived & operator= (std::pair< Args... > &&args)
template<typename... Args>
Derived & operator= (std::tuple< Args... > &args)
template<typename... Args>
Derived & operator= (const std::tuple< Args... > &args)
template<typename... Args>
Derived & operator= (std::tuple< Args... > &&args)
emplace_iterator_base (const emplace_iterator_base &)=default
emplace_iterator_base (emplace_iterator_base &&) noexcept=default
emplace_iterator_base & operator= (emplace_iterator_base &)=default
emplace_iterator_base & operator= (const emplace_iterator_base &)=default
emplace_iterator_base & operator= (emplace_iterator_base &&) noexcept=default
Public Member Functions inherited from folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false >
template<typename T >
Derived & operator= (T &&arg)
template<typename... Args>
Derived & operator= (emplace_args< Args... > &args)
template<typename... Args>
Derived & operator= (const emplace_args< Args... > &args)
template<typename... Args>
Derived & operator= (emplace_args< Args... > &&args)
Derived & operator* ()
Derived & operator++ ()
Derived & operator++ (int)
emplace_iterator_base (const emplace_iterator_base &)=default
emplace_iterator_base (emplace_iterator_base &&) noexcept=default
emplace_iterator_base & operator= (emplace_iterator_base &)=default
emplace_iterator_base & operator= (const emplace_iterator_base &)=default
emplace_iterator_base & operator= (emplace_iterator_base &&) noexcept=default
Private Types
using Base = emplace_iterator_base< Derived, EmplaceImpl, false >
Additional Inherited Members
Public Types inherited from folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false >
using iterator_category = std::output_iterator_tag
using value_type = void
using difference_type = void
using pointer = void
using reference = void
using container_type = std::remove_reference_t< decltype(*EmplaceImpl::container)>
Protected Member Functions inherited from folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false >
template<typename Args , std::size_t... I>
Derived & unpackAndEmplace (Args &args, index_sequence< I... >)
template<typename Args , std::size_t... I>
Derived & unpackAndEmplace (const Args &args, index_sequence< I... >)
template<typename Args , std::size_t... I>
Derived & unpackAndEmplace (Args &&args, index_sequence< I... >)
Detailed Description
template<typename Derived, typename EmplaceImpl>
class folly::detail::emplace_iterator_base< Derived, EmplaceImpl, true >
Partial specialization of emplace_iterator_base with implicit unpacking enabled.
Uses inheritance rather than SFINAE. operator= requires a single argument, which makes it very tricky to use std::enable_if or similar.
Definition at line 311 of file Iterator.h.
Member Typedef Documentation
template<typename Derived , typename EmplaceImpl > using folly::detail::emplace_iterator_base< Derived, EmplaceImpl, true >::Base = emplace_iterator_base<Derived, EmplaceImpl, false> private
Definition at line 314 of file Iterator.h.
Constructor & Destructor Documentation
template<typename Derived , typename EmplaceImpl > folly::detail::emplace_iterator_base< Derived, EmplaceImpl, true >::emplace_iterator_base (const emplace_iterator_base< Derived, EmplaceImpl, true > &) default
template<typename Derived , typename EmplaceImpl > folly::detail::emplace_iterator_base< Derived, EmplaceImpl, true >::emplace_iterator_base (emplace_iterator_base< Derived, EmplaceImpl, true > &&) default noexcept
Member Function Documentation
template<typename Derived , typename EmplaceImpl > template<typename... Args> Derived& folly::detail::emplace_iterator_base< Derived, EmplaceImpl, true >::operator= (std::pair< Args... > & args) inline
Special output operator for arguments packed into a std::pair. Unpacks the pair and performs variadic call to container's emplace function.
Definition at line 325 of file Iterator.h.
References testing::Args().
{
     return this->unpackAndEmplace(args, index_sequence_for<Args...>{});
   }
template<typename Derived , typename EmplaceImpl > template<typename... Args> Derived& folly::detail::emplace_iterator_base< Derived, EmplaceImpl, true >::operator= (const std::pair< Args... > & args) inline
Definition at line 329 of file Iterator.h.
References testing::Args().
{
     return this->unpackAndEmplace(args, index_sequence_for<Args...>{});
   }
template<typename Derived , typename EmplaceImpl > template<typename... Args> Derived& folly::detail::emplace_iterator_base< Derived, EmplaceImpl, true >::operator= (std::pair< Args... > && args) inline
Definition at line 333 of file Iterator.h.
References testing::Args(), and folly::gen::move.
{
     return this->unpackAndEmplace(
         std::move(args), index_sequence_for<Args...>{});
   }
template<typename Derived , typename EmplaceImpl > template<typename... Args> Derived& folly::detail::emplace_iterator_base< Derived, EmplaceImpl, true >::operator= (std::tuple< Args... > & args) inline
Special output operator for arguments packed into a std::tuple. Unpacks the tuple and performs variadic call to container's emplace function.
Definition at line 343 of file Iterator.h.
References testing::Args().
{
     return this->unpackAndEmplace(args, index_sequence_for<Args...>{});
   }
template<typename Derived , typename EmplaceImpl > template<typename... Args> Derived& folly::detail::emplace_iterator_base< Derived, EmplaceImpl, true >::operator= (const std::tuple< Args... > & args) inline
Definition at line 347 of file Iterator.h.
References testing::Args().
{
     return this->unpackAndEmplace(args, index_sequence_for<Args...>{});
   }
template<typename Derived , typename EmplaceImpl > template<typename... Args> Derived& folly::detail::emplace_iterator_base< Derived, EmplaceImpl, true >::operator= (std::tuple< Args... > && args) inline
Definition at line 351 of file Iterator.h.
References folly::gen::move, and folly::pushmi::__adl::noexcept().
{
     return this->unpackAndEmplace(
         std::move(args), index_sequence_for<Args...>{});
   }
template<typename Derived , typename EmplaceImpl > emplace_iterator_base& folly::detail::emplace_iterator_base< Derived, EmplaceImpl, true >::operator= (emplace_iterator_base< Derived, EmplaceImpl, true > &) default
template<typename Derived , typename EmplaceImpl > emplace_iterator_base& folly::detail::emplace_iterator_base< Derived, EmplaceImpl, true >::operator= (const emplace_iterator_base< Derived, EmplaceImpl, true > &) default
template<typename Derived , typename EmplaceImpl > emplace_iterator_base& folly::detail::emplace_iterator_base< Derived, EmplaceImpl, true >::operator= (emplace_iterator_base< Derived, EmplaceImpl, true > &&) default noexcept
The documentation for this class was generated from the following file:
proxygen/folly/folly/container/Iterator.h