proxygen: folly::SimpleQuantileEstimator< ClockT > Class Template Reference
folly::SimpleQuantileEstimator< ClockT > Class Template Reference
#include <QuantileEstimator.h>
Public Types
using TimePoint = typename ClockT::time_point
Public Member Functions
SimpleQuantileEstimator ()
QuantileEstimates estimateQuantiles (Range< const double * > quantiles, TimePoint now=ClockT::now())
void addValue (double value, TimePoint now=ClockT::now())
void flush ()
Flush buffered values.
Private Attributes
detail::BufferedDigest< TDigest, ClockT > bufferedDigest_
Detailed Description
template<typename ClockT = std::chrono::steady_clock>
class folly::SimpleQuantileEstimator< ClockT >
Definition at line 36 of file QuantileEstimator.h.
Member Typedef Documentation
template<typename ClockT = std::chrono::steady_clock> using folly::SimpleQuantileEstimator< ClockT >::TimePoint = typename ClockT::time_point
Definition at line 38 of file QuantileEstimator.h.
Constructor & Destructor Documentation
template<typename ClockT > folly::SimpleQuantileEstimator< ClockT >::SimpleQuantileEstimator ()
Definition at line 33 of file QuantileEstimator-defs.h.
     : bufferedDigest_(std::chrono::seconds{1}, 1000, 100) {}
Member Function Documentation
template<typename ClockT > void folly::SimpleQuantileEstimator< ClockT >::addValue (double value, TimePoint now = ClockT::now())
Definition at line 45 of file QuantileEstimator-defs.h.
References folly::SimpleQuantileEstimator< ClockT >::bufferedDigest_.
Referenced by TEST().
{
   bufferedDigest_.append(value, now);
 }
template<typename ClockT > QuantileEstimates folly::SimpleQuantileEstimator< ClockT >::estimateQuantiles (Range< const double * > quantiles, TimePoint now = ClockT::now())
Definition at line 37 of file QuantileEstimator-defs.h.
References folly::SimpleQuantileEstimator< ClockT >::bufferedDigest_, and folly::detail::estimatesFromDigest().
Referenced by TEST().
                    {
   auto digest = bufferedDigest_.get(now);
   return detail::estimatesFromDigest(digest, quantiles);
 }
template<typename ClockT = std::chrono::steady_clock> void folly::SimpleQuantileEstimator< ClockT >::flush () inline
Flush buffered values.
Definition at line 49 of file QuantileEstimator.h.
                {
     bufferedDigest_.flush();
   }
Member Data Documentation
template<typename ClockT = std::chrono::steady_clock> detail::BufferedDigest<TDigest, ClockT> folly::SimpleQuantileEstimator< ClockT >::bufferedDigest_ private
Definition at line 54 of file QuantileEstimator.h.
Referenced by folly::SimpleQuantileEstimator< ClockT >::addValue(), and folly::SimpleQuantileEstimator< ClockT >::estimateQuantiles().
The documentation for this class was generated from the following files:
proxygen/folly/folly/stats/QuantileEstimator.h
proxygen/folly/folly/stats/QuantileEstimator-defs.h