proxygen: folly::detail::BufferedSlidingWindow< DigestT, ClockT > Class Template Reference
folly::detail::BufferedSlidingWindow< DigestT, ClockT > Class Template Reference
#include <BufferedStat.h>
Public Types
using TimePoint = typename ClockT::time_point
Public Types inherited from folly::detail::BufferedStat< DigestT, ClockT >
using TimePoint = typename ClockT::time_point
Public Member Functions
BufferedSlidingWindow (size_t nBuckets, typename ClockT::duration bufferDuration, size_t bufferSize, size_t digestSize)
std::vector< DigestT > get (TimePoint now=ClockT::now())
void onNewDigest (DigestT digest, TimePoint newExpiry, TimePoint oldExpiry, const std::unique_lock< SharedMutex > &g) final
Public Member Functions inherited from folly::detail::BufferedStat< DigestT, ClockT >
BufferedStat ()=delete
BufferedStat (typename ClockT::duration bufferDuration, size_t bufferSize, size_t digestSize)
virtual ~BufferedStat ()
void append (double value, TimePoint now=ClockT::now())
void flush ()
Private Attributes
SlidingWindow< DigestT > slidingWindow_
Additional Inherited Members
Protected Member Functions inherited from folly::detail::BufferedStat< DigestT, ClockT >
std::unique_lock< SharedMutex > updateIfExpired (TimePoint now)
std::unique_lock< SharedMutex > update ()
Protected Attributes inherited from folly::detail::BufferedStat< DigestT, ClockT >
const ClockT::duration bufferDuration_
std::atomic< TimePointHolder > expiry_
SharedMutex mutex_
Detailed Description
template<typename DigestT, typename ClockT>
class folly::detail::BufferedSlidingWindow< DigestT, ClockT >
Definition at line 126 of file BufferedStat.h.
Member Typedef Documentation
template<typename DigestT, typename ClockT> using folly::detail::BufferedSlidingWindow< DigestT, ClockT >::TimePoint = typename ClockT::time_point
Definition at line 128 of file BufferedStat.h.
Constructor & Destructor Documentation
template<typename DigestT , typename ClockT> folly::detail::BufferedSlidingWindow< DigestT, ClockT >::BufferedSlidingWindow (size_t nBuckets, typename ClockT::duration bufferDuration, size_t bufferSize, size_t digestSize)
Definition at line 112 of file BufferedStat-defs.h.
     : BufferedStat<DigestT, ClockT>(bufferDuration, bufferSize, digestSize),
       slidingWindow_([=]() { return DigestT(digestSize); }, nBuckets) {}
Member Function Documentation
template<typename DigestT , typename ClockT > std::vector< DigestT > folly::detail::BufferedSlidingWindow< DigestT, ClockT >::get (TimePoint now = ClockT::now())
Definition at line 121 of file BufferedStat-defs.h.
References g(), folly::detail::SlidingWindow< BucketT >::get(), folly::detail::BufferedSlidingWindow< DigestT, ClockT >::slidingWindow_, and folly::detail::BufferedStat< DigestT, ClockT >::updateIfExpired().
                    {
   std::vector<DigestT> digests;
   {
     auto g = this->updateIfExpired(now);
     digests = slidingWindow_.get();
   }
   digests.erase(
       std::remove_if(
           digests.begin(),
           digests.end(),
           [](const DigestT& digest) { return digest.empty(); }),
       digests.end());
   return digests;
 }
template<typename DigestT, typename ClockT > void folly::detail::BufferedSlidingWindow< DigestT, ClockT >::onNewDigest (DigestT digest, TimePoint newExpiry, TimePoint oldExpiry, const std::unique_lock< SharedMutex > & g) final virtual
Implements folly::detail::BufferedStat< DigestT, ClockT >.
Definition at line 138 of file BufferedStat-defs.h.
References a, folly::detail::BufferedStat< DigestT, ClockT >::bufferDuration_, diff(), folly::detail::SlidingWindow< BucketT >::front(), merge(), folly::gen::move, folly::detail::SlidingWindow< BucketT >::set(), folly::detail::SlidingWindow< BucketT >::slide(), and folly::detail::BufferedSlidingWindow< DigestT, ClockT >::slidingWindow_.
{
   if (newExpiry > oldExpiry) {
     auto diff = newExpiry - oldExpiry;
     slidingWindow_.slide(diff / this->bufferDuration_);
     diff -= this->bufferDuration_;
     slidingWindow_.set(diff / this->bufferDuration_, std::move(digest));
   } else {
     // just update current window
     std::array<DigestT, 2> a{{slidingWindow_.front(), std::move(digest)}};
     slidingWindow_.set(0 /* current window */, DigestT::merge(a));
   }
 }
Member Data Documentation
template<typename DigestT, typename ClockT> SlidingWindow<DigestT> folly::detail::BufferedSlidingWindow< DigestT, ClockT >::slidingWindow_ private
Definition at line 145 of file BufferedStat.h.
Referenced by folly::detail::BufferedSlidingWindow< DigestT, ClockT >::get(), and folly::detail::BufferedSlidingWindow< DigestT, ClockT >::onNewDigest().
The documentation for this class was generated from the following files:
proxygen/folly/folly/stats/detail/BufferedStat.h
proxygen/folly/folly/stats/detail/BufferedStat-defs.h