proxygen: testing::internal::ThreadLocal< T > Class Template Reference
testing::internal::ThreadLocal< T > Class Template Reference
#include <gtest-port.h>
Public Member Functions
ThreadLocal ()
ThreadLocal (const T &value)
T * pointer ()
const T * pointer () const
const T & get () const
void set (const T &value)
ThreadLocal ()
ThreadLocal (const T &value)
T * pointer ()
const T * pointer () const
const T & get () const
void set (const T &value)
ThreadLocal ()
ThreadLocal (const T &value)
T * pointer ()
const T * pointer () const
const T & get () const
void set (const T &value)
Private Attributes
T value_
Detailed Description
template<typename T>
class testing::internal::ThreadLocal< T >
Definition at line 2162 of file gtest-port.h.
Constructor & Destructor Documentation
template<typename T> testing::internal::ThreadLocal< T >::ThreadLocal () inline
Definition at line 2164 of file gtest-port.h.
 : value_() {}
template<typename T> testing::internal::ThreadLocal< T >::ThreadLocal (const T & value) inline explicit
Definition at line 2165 of file gtest-port.h.
 : value_(value) {}
template<typename T> testing::internal::ThreadLocal< T >::ThreadLocal () inline
Definition at line 2164 of file gtest-port.h.
 : value_() {}
template<typename T> testing::internal::ThreadLocal< T >::ThreadLocal (const T & value) inline explicit
Definition at line 2165 of file gtest-port.h.
 : value_(value) {}
template<typename T> testing::internal::ThreadLocal< T >::ThreadLocal () inline
Definition at line 2164 of file gtest-port.h.
 : value_() {}
template<typename T> testing::internal::ThreadLocal< T >::ThreadLocal (const T & value) inline explicit
Definition at line 2165 of file gtest-port.h.
 : value_(value) {}
Member Function Documentation
template<typename T> const T& testing::internal::ThreadLocal< T >::get () const inline
Definition at line 2168 of file gtest-port.h.
Referenced by testing::internal::NoDefaultContructor::NoDefaultContructor(), testing::internal::TEST(), and testing::internal::To::To().
 { return value_; }
template<typename T> const T& testing::internal::ThreadLocal< T >::get () const inline
Definition at line 2168 of file gtest-port.h.
 { return value_; }
template<typename T> const T& testing::internal::ThreadLocal< T >::get () const inline
Definition at line 2168 of file gtest-port.h.
 { return value_; }
template<typename T> T* testing::internal::ThreadLocal< T >::pointer () inline
Definition at line 2166 of file gtest-port.h.
 { return &value_; }
template<typename T> T* testing::internal::ThreadLocal< T >::pointer () inline
Definition at line 2166 of file gtest-port.h.
 { return &value_; }
template<typename T> T* testing::internal::ThreadLocal< T >::pointer () inline
Definition at line 2166 of file gtest-port.h.
Referenced by testing::internal::NoDefaultContructor::NoDefaultContructor(), and testing::internal::TEST().
 { return &value_; }
template<typename T> const T* testing::internal::ThreadLocal< T >::pointer () const inline
Definition at line 2167 of file gtest-port.h.
 { return &value_; }
template<typename T> const T* testing::internal::ThreadLocal< T >::pointer () const inline
Definition at line 2167 of file gtest-port.h.
 { return &value_; }
template<typename T> const T* testing::internal::ThreadLocal< T >::pointer () const inline
Definition at line 2167 of file gtest-port.h.
 { return &value_; }
template<typename T> void testing::internal::ThreadLocal< T >::set (const T & value) inline
Definition at line 2169 of file gtest-port.h.
 { value_ = value; }
template<typename T> void testing::internal::ThreadLocal< T >::set (const T & value) inline
Definition at line 2169 of file gtest-port.h.
Referenced by testing::internal::NoDefaultContructor::NoDefaultContructor(), and testing::internal::TEST().
 { value_ = value; }
template<typename T> void testing::internal::ThreadLocal< T >::set (const T & value) inline
Definition at line 2169 of file gtest-port.h.
 { value_ = value; }
Member Data Documentation
template<typename T> T testing::internal::ThreadLocal< T >::value_ private
Definition at line 2171 of file gtest-port.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h