proxygen: testing::StringMatchResultListener Class Reference
testing::StringMatchResultListener Class Reference
#include <gmock-matchers.h>
Public Member Functions
StringMatchResultListener ()
internal::string str () const
void Clear ()
StringMatchResultListener ()
internal::string str () const
void Clear ()
StringMatchResultListener ()
internal::string str () const
void Clear ()
Public Member Functions inherited from testing::MatchResultListener
MatchResultListener (::std::ostream *os)
virtual ~MatchResultListener ()=0
template<typename T >
MatchResultListener & operator<< (const T &x)
::std::ostream * stream ()
bool IsInterested () const
MatchResultListener (::std::ostream *os)
virtual ~MatchResultListener ()=0
template<typename T >
MatchResultListener & operator<< (const T &x)
::std::ostream * stream ()
bool IsInterested () const
MatchResultListener (::std::ostream *os)
virtual ~MatchResultListener ()=0
template<typename T >
MatchResultListener & operator<< (const T &x)
::std::ostream * stream ()
bool IsInterested () const
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (StringMatchResultListener)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (StringMatchResultListener)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (StringMatchResultListener)
Private Attributes
::std::stringstream ss_
Detailed Description
Definition at line 184 of file gmock-matchers.h.
Constructor & Destructor Documentation
testing::StringMatchResultListener::StringMatchResultListener () inline
Definition at line 186 of file gmock-matchers.h.
 : MatchResultListener(&ss_) {}
testing::StringMatchResultListener::StringMatchResultListener () inline
Definition at line 186 of file gmock-matchers.h.
 : MatchResultListener(&ss_) {}
testing::StringMatchResultListener::StringMatchResultListener () inline
Definition at line 186 of file gmock-matchers.h.
 : MatchResultListener(&ss_) {}
Member Function Documentation
void testing::StringMatchResultListener::Clear () inline
Definition at line 192 of file gmock-matchers.h.
Referenced by testing::gmock_matchers_test::GreaterThanMatcher::MatchAndExplain(), and testing::gmock_matchers_test::TEST().
 { ss_.str(""); }
void testing::StringMatchResultListener::Clear () inline
Definition at line 192 of file gmock-matchers.h.
References testing::MatchResultListener::GTEST_DISALLOW_COPY_AND_ASSIGN_().
 { ss_.str(""); }
void testing::StringMatchResultListener::Clear () inline
Definition at line 192 of file gmock-matchers.h.
References testing::MatchResultListener::GTEST_DISALLOW_COPY_AND_ASSIGN_().
 { ss_.str(""); }
testing::StringMatchResultListener::GTEST_DISALLOW_COPY_AND_ASSIGN_ (StringMatchResultListener) private
testing::StringMatchResultListener::GTEST_DISALLOW_COPY_AND_ASSIGN_ (StringMatchResultListener) private
testing::StringMatchResultListener::GTEST_DISALLOW_COPY_AND_ASSIGN_ (StringMatchResultListener) private
internal::string testing::StringMatchResultListener::str () const inline
Definition at line 189 of file gmock-matchers.h.
 { return ss_.str(); }
internal::string testing::StringMatchResultListener::str () const inline
Definition at line 189 of file gmock-matchers.h.
Referenced by testing::SafeMatcherCastImpl< T >::Cast(), testing::gmock_matchers_test::NewEvenMatcherImpl::DescribeTo(), testing::gmock_matchers_test::EMString(), testing::gmock_matchers_test::Explain(), testing::internal::TypedExpectation< F >::ExplainMatchResultTo(), testing::gmock_matchers_test::GreaterThanMatcher::MatchAndExplain(), testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::MatchAndExplain(), testing::internal::BothOfMatcherImpl< T >::MatchAndExplain(), testing::internal::EitherOfMatcherImpl< T >::MatchAndExplain(), testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::MatchAndExplain(), testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::MatchAndExplain(), testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::MatchAndExplain(), testing::internal::KeyMatcherImpl< PairType >::MatchAndExplain(), testing::internal::PairMatcherImpl< PairType >::MatchAndExplain(), testing::internal::ElementsAreMatcherImpl< Container >::MatchAndExplain(), testing::internal::QuantifierMatcherImpl< Container >::MatchAndExplainImpl(), testing::internal::MatchPrintAndExplain(), testing::gmock_matchers_test::ConvertibleToBool::operator bool(), testing::gmock_matchers_test::TEST(), and testing::gmock_matchers_test::TEST_F().
 { return ss_.str(); }
internal::string testing::StringMatchResultListener::str () const inline
Definition at line 189 of file gmock-matchers.h.
 { return ss_.str(); }
Member Data Documentation
std::stringstream testing::StringMatchResultListener::ss_ private
Definition at line 195 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h