proxygen: EventHandlerTest Class Reference
EventHandlerTest Class Reference
Public Member Functions
void SetUp () override
void TearDown () override
void efd_write (uint64_t val)
uint64_t efd_read ()
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Public Attributes
int efd = 0
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Protected Member Functions inherited from testing::Test
Test ()
Test ()
Test ()
Detailed Description
Definition at line 58 of file EventHandlerTest.cpp.
Member Function Documentation
uint64_t EventHandlerTest::efd_read () inline
Definition at line 78 of file EventHandlerTest.cpp.
References fizz::detail::read(), uint64_t, and val.
                       {
     uint64_t val = 0;
     read(efd, &val, sizeof(val));
     return val;
   }
void EventHandlerTest::efd_write (uint64_t val) inline
Definition at line 74 of file EventHandlerTest.cpp.
References fizz::detail::write().
{
     write(efd, &val, sizeof(val));
   }
void EventHandlerTest::SetUp () inline override virtual
Reimplemented from testing::Test.
Definition at line 62 of file EventHandlerTest.cpp.
References ASSERT_THAT, EFD_SEMAPHORE, eventfd, and testing::Gt().
{
     efd = eventfd(0, EFD_SEMAPHORE);
     ASSERT_THAT(efd, Gt(0));
   }
void EventHandlerTest::TearDown () inline override virtual
Reimplemented from testing::Test.
Definition at line 67 of file EventHandlerTest.cpp.
References folly::netops::close().
{
     if (efd > 0) {
       close(efd);
     }
     efd = 0;
   }
Member Data Documentation
int EventHandlerTest::efd = 0
Definition at line 60 of file EventHandlerTest.cpp.
The documentation for this class was generated from the following file:
proxygen/folly/folly/io/async/test/EventHandlerTest.cpp