proxygen: testing::internal::TestPropertyKeyIs Class Reference
testing::internal::TestPropertyKeyIs Class Reference
#include <gtest-internal-inl.h>
Public Member Functions
TestPropertyKeyIs (const std::string &key)
bool operator() (const TestProperty &test_property) const
TestPropertyKeyIs (const std::string &key)
bool operator() (const TestProperty &test_property) const
TestPropertyKeyIs (const std::string &key)
bool operator() (const TestProperty &test_property) const
Private Attributes
std::string key_
Detailed Description
Definition at line 347 of file gtest-internal-inl.h.
Constructor & Destructor Documentation
testing::internal::TestPropertyKeyIs::TestPropertyKeyIs (const std::string & key) inline explicit
Definition at line 352 of file gtest-internal-inl.h.
 : key_(key) {}
testing::internal::TestPropertyKeyIs::TestPropertyKeyIs (const std::string & key) inline explicit
Definition at line 352 of file gtest-internal-inl.h.
 : key_(key) {}
testing::internal::TestPropertyKeyIs::TestPropertyKeyIs (const std::string & key) inline explicit
Definition at line 352 of file gtest-internal-inl.h.
 : key_(key) {}
Member Function Documentation
bool testing::internal::TestPropertyKeyIs::operator() (const TestProperty & test_property) const inline
Definition at line 355 of file gtest-internal-inl.h.
References testing::TestProperty::key().
{
     return test_property.key() == key_;
   }
bool testing::internal::TestPropertyKeyIs::operator() (const TestProperty & test_property) const inline
Definition at line 355 of file gtest-internal-inl.h.
References folly::pushmi::operators::filter, testing::internal::GetCurrentExecutableName(), GTEST_API_, testing::TestProperty::key(), name, and string.
{
     return test_property.key() == key_;
   }
bool testing::internal::TestPropertyKeyIs::operator() (const TestProperty & test_property) const inline
Definition at line 355 of file gtest-internal-inl.h.
References folly::pushmi::operators::filter, testing::internal::GetCurrentExecutableName(), GTEST_API_, testing::TestProperty::key(), name, and string.
{
     return test_property.key() == key_;
   }
Member Data Documentation
std::string testing::internal::TestPropertyKeyIs::key_ private
Definition at line 360 of file gtest-internal-inl.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest-internal-inl.h