proxygen: upload.VersionControlSystem Class Reference
upload.VersionControlSystem Class Reference
Public Member Functions
def __init__ (self, options)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def CheckForUnknownFiles (self)
def GetBaseFile (self, filename)
def GetBaseFiles (self, diff)
def UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
def IsImage (self, filename)
def __init__ (self, options)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def CheckForUnknownFiles (self)
def GetBaseFile (self, filename)
def GetBaseFiles (self, diff)
def UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
def IsImage (self, filename)
def __init__ (self, options)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def CheckForUnknownFiles (self)
def GetBaseFile (self, filename)
def GetBaseFiles (self, diff)
def UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
def IsImage (self, filename)
def __init__ (self, options)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def CheckForUnknownFiles (self)
def GetBaseFile (self, filename)
def GetBaseFiles (self, diff)
def UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
def IsImage (self, filename)
def __init__ (self, options)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def CheckForUnknownFiles (self)
def GetBaseFile (self, filename)
def GetBaseFiles (self, diff)
def UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
def IsImage (self, filename)
def __init__ (self, options)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def CheckForUnknownFiles (self)
def GetBaseFile (self, filename)
def GetBaseFiles (self, diff)
def UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
def IsImage (self, filename)
Public Attributes
options
Detailed Description
Abstract base class providing an interface to the VCS.
Definition at line 588 of file upload.py.
Constructor & Destructor Documentation
def upload.VersionControlSystem.__init__ (self, options)
Constructor.
Args:
  options: Command line options.
Definition at line 591 of file upload.py.
Referenced by upload.VersionControlSystem.__init__().
   def __init__(self, options):
     """Constructor.
     Args:
       options: Command line options.
     """
     self.options = options
def upload.VersionControlSystem.__init__ (self, options)
Constructor.
Args:
  options: Command line options.
Definition at line 591 of file upload.py.
References upload.VersionControlSystem.__init__(), and upload.VersionControlSystem.options.
   def __init__(self, options):
     """Constructor.
     Args:
       options: Command line options.
     """
     self.options = options
def upload.VersionControlSystem.__init__ (self, options)
Constructor.
Args:
  options: Command line options.
Definition at line 591 of file upload.py.
References upload.VersionControlSystem.__init__(), and upload.VersionControlSystem.options.
   def __init__(self, options):
     """Constructor.
     Args:
       options: Command line options.
     """
     self.options = options
def upload.VersionControlSystem.__init__ (self, options)
Constructor.
Args:
  options: Command line options.
Definition at line 591 of file upload.py.
References upload.VersionControlSystem.__init__(), and upload.VersionControlSystem.options.
   def __init__(self, options):
     """Constructor.
     Args:
       options: Command line options.
     """
     self.options = options
def upload.VersionControlSystem.__init__ (self, options)
Constructor.
Args:
  options: Command line options.
Definition at line 591 of file upload.py.
References upload.VersionControlSystem.__init__(), and upload.VersionControlSystem.options.
   def __init__(self, options):
     """Constructor.
     Args:
       options: Command line options.
     """
     self.options = options
def upload.VersionControlSystem.__init__ (self, options)
Constructor.
Args:
  options: Command line options.
Definition at line 591 of file upload.py.
References upload.VersionControlSystem.__init__(), and upload.VersionControlSystem.options.
   def __init__(self, options):
     """Constructor.
     Args:
       options: Command line options.
     """
     self.options = options
Member Function Documentation
def upload.VersionControlSystem.CheckForUnknownFiles (self)
Show an "are you sure?" prompt if there are unknown files.
Definition at line 613 of file upload.py.
References upload.ErrorExit(), upload.VersionControlSystem.GetUnknownFiles(), and folly::detail::distributed_mutex.strip().
Referenced by upload.VersionControlSystem.CheckForUnknownFiles().
   def CheckForUnknownFiles(self):
     """Show an "are you sure?" prompt if there are unknown files."""
     unknown_files = self.GetUnknownFiles()
     if unknown_files:
       print "The following files are not added to version control:"
       for line in unknown_files:
         print line
       prompt = "Are you sure to continue?(y/N) "
       answer = raw_input(prompt).strip()
       if answer != "y":
         ErrorExit("User aborted")
def upload.VersionControlSystem.CheckForUnknownFiles (self)
Show an "are you sure?" prompt if there are unknown files.
Definition at line 613 of file upload.py.
References upload.VersionControlSystem.CheckForUnknownFiles(), upload.ErrorExit(), upload.VersionControlSystem.GetUnknownFiles(), and folly::detail::distributed_mutex.strip().
   def CheckForUnknownFiles(self):
     """Show an "are you sure?" prompt if there are unknown files."""
     unknown_files = self.GetUnknownFiles()
     if unknown_files:
       print "The following files are not added to version control:"
       for line in unknown_files:
         print line
       prompt = "Are you sure to continue?(y/N) "
       answer = raw_input(prompt).strip()
       if answer != "y":
         ErrorExit("User aborted")
def upload.VersionControlSystem.CheckForUnknownFiles (self)
Show an "are you sure?" prompt if there are unknown files.
Definition at line 613 of file upload.py.
References upload.VersionControlSystem.CheckForUnknownFiles(), upload.ErrorExit(), upload.VersionControlSystem.GetUnknownFiles(), and folly::detail::distributed_mutex.strip().
   def CheckForUnknownFiles(self):
     """Show an "are you sure?" prompt if there are unknown files."""
     unknown_files = self.GetUnknownFiles()
     if unknown_files:
       print "The following files are not added to version control:"
       for line in unknown_files:
         print line
       prompt = "Are you sure to continue?(y/N) "
       answer = raw_input(prompt).strip()
       if answer != "y":
         ErrorExit("User aborted")
def upload.VersionControlSystem.CheckForUnknownFiles (self)
Show an "are you sure?" prompt if there are unknown files.
Definition at line 613 of file upload.py.
References upload.VersionControlSystem.CheckForUnknownFiles(), upload.ErrorExit(), upload.VersionControlSystem.GetUnknownFiles(), and folly::detail::distributed_mutex.strip().
   def CheckForUnknownFiles(self):
     """Show an "are you sure?" prompt if there are unknown files."""
     unknown_files = self.GetUnknownFiles()
     if unknown_files:
       print "The following files are not added to version control:"
       for line in unknown_files:
         print line
       prompt = "Are you sure to continue?(y/N) "
       answer = raw_input(prompt).strip()
       if answer != "y":
         ErrorExit("User aborted")
def upload.VersionControlSystem.CheckForUnknownFiles (self)
Show an "are you sure?" prompt if there are unknown files.
Definition at line 613 of file upload.py.
References upload.VersionControlSystem.CheckForUnknownFiles(), upload.ErrorExit(), upload.VersionControlSystem.GetUnknownFiles(), and folly::detail::distributed_mutex.strip().
   def CheckForUnknownFiles(self):
     """Show an "are you sure?" prompt if there are unknown files."""
     unknown_files = self.GetUnknownFiles()
     if unknown_files:
       print "The following files are not added to version control:"
       for line in unknown_files:
         print line
       prompt = "Are you sure to continue?(y/N) "
       answer = raw_input(prompt).strip()
       if answer != "y":
         ErrorExit("User aborted")
def upload.VersionControlSystem.CheckForUnknownFiles (self)
Show an "are you sure?" prompt if there are unknown files.
Definition at line 613 of file upload.py.
References upload.VersionControlSystem.CheckForUnknownFiles(), upload.ErrorExit(), upload.VersionControlSystem.GetUnknownFiles(), and folly::detail::distributed_mutex.strip().
   def CheckForUnknownFiles(self):
     """Show an "are you sure?" prompt if there are unknown files."""
     unknown_files = self.GetUnknownFiles()
     if unknown_files:
       print "The following files are not added to version control:"
       for line in unknown_files:
         print line
       prompt = "Are you sure to continue?(y/N) "
       answer = raw_input(prompt).strip()
       if answer != "y":
         ErrorExit("User aborted")
def upload.VersionControlSystem.GenerateDiff (self, args)
Return the current diff as a string.
Args:
  args: Extra arguments to pass to the diff command.
Definition at line 599 of file upload.py.
References upload.VersionControlSystem.GenerateDiff().
   def GenerateDiff(self, args):
     """Return the current diff as a string.
     Args:
       args: Extra arguments to pass to the diff command.
     """
     raise NotImplementedError(
         "abstract method -- subclass %s must override" % self.__class__)
def upload.VersionControlSystem.GenerateDiff (self, args)
Return the current diff as a string.
Args:
  args: Extra arguments to pass to the diff command.
Definition at line 599 of file upload.py.
References upload.VersionControlSystem.GenerateDiff().
   def GenerateDiff(self, args):
     """Return the current diff as a string.
     Args:
       args: Extra arguments to pass to the diff command.
     """
     raise NotImplementedError(
         "abstract method -- subclass %s must override" % self.__class__)
def upload.VersionControlSystem.GenerateDiff (self, args)
Return the current diff as a string.
Args:
  args: Extra arguments to pass to the diff command.
Definition at line 599 of file upload.py.
References upload.VersionControlSystem.GenerateDiff().
   def GenerateDiff(self, args):
     """Return the current diff as a string.
     Args:
       args: Extra arguments to pass to the diff command.
     """
     raise NotImplementedError(
         "abstract method -- subclass %s must override" % self.__class__)
def upload.VersionControlSystem.GenerateDiff (self, args)
Return the current diff as a string.
Args:
  args: Extra arguments to pass to the diff command.
Definition at line 599 of file upload.py.
Referenced by upload.VersionControlSystem.GenerateDiff().
   def GenerateDiff(self, args):
     """Return the current diff as a string.
     Args:
       args: Extra arguments to pass to the diff command.
     """
     raise NotImplementedError(
         "abstract method -- subclass %s must override" % self.__class__)
def upload.VersionControlSystem.GenerateDiff (self, args)
Return the current diff as a string.
Args:
  args: Extra arguments to pass to the diff command.
Definition at line 599 of file upload.py.
References upload.VersionControlSystem.GenerateDiff().
   def GenerateDiff(self, args):
     """Return the current diff as a string.
     Args:
       args: Extra arguments to pass to the diff command.
     """
     raise NotImplementedError(
         "abstract method -- subclass %s must override" % self.__class__)
def upload.VersionControlSystem.GenerateDiff (self, args)
Return the current diff as a string.
Args:
  args: Extra arguments to pass to the diff command.
Definition at line 599 of file upload.py.
References upload.VersionControlSystem.GenerateDiff().
   def GenerateDiff(self, args):
     """Return the current diff as a string.
     Args:
       args: Extra arguments to pass to the diff command.
     """
     raise NotImplementedError(
         "abstract method -- subclass %s must override" % self.__class__)
def upload.VersionControlSystem.GetBaseFile (self, filename)
Get the content of the upstream version of a file.
Returns:
  A tuple (base_content, new_content, is_binary, status)
base_content: The contents of the base file.
new_content: For text files, this is empty.  For binary files, this is
  the contents of the new file, since the diff output won't contain
  information to reconstruct the current file.
is_binary: True iff the file is binary.
status: The status of the file.
Definition at line 625 of file upload.py.
Referenced by upload.VersionControlSystem.GetBaseFile(), and upload.VersionControlSystem.GetBaseFiles().
   def GetBaseFile(self, filename):
     """Get the content of the upstream version of a file.
     Returns:
       A tuple (base_content, new_content, is_binary, status)
         base_content: The contents of the base file.
         new_content: For text files, this is empty.  For binary files, this is
           the contents of the new file, since the diff output won't contain
           information to reconstruct the current file.
         is_binary: True iff the file is binary.
         status: The status of the file.
     """
     raise NotImplementedError(
         "abstract method -- subclass %s must override" % self.__class__)
def upload.VersionControlSystem.GetBaseFile (self, filename)
Get the content of the upstream version of a file.
Returns:
  A tuple (base_content, new_content, is_binary, status)
base_content: The contents of the base file.
new_content: For text files, this is empty.  For binary files, this is
  the contents of the new file, since the diff output won't contain
  information to reconstruct the current file.
is_binary: True iff the file is binary.
status: The status of the file.
Definition at line 625 of file upload.py.
References upload.VersionControlSystem.GetBaseFile().
   def GetBaseFile(self, filename):
     """Get the content of the upstream version of a file.
     Returns:
       A tuple (base_content, new_content, is_binary, status)
         base_content: The contents of the base file.
         new_content: For text files, this is empty.  For binary files, this is
           the contents of the new file, since the diff output won't contain
           information to reconstruct the current file.
         is_binary: True iff the file is binary.
         status: The status of the file.
     """
     raise NotImplementedError(
         "abstract method -- subclass %s must override" % self.__class__)
def upload.VersionControlSystem.GetBaseFile (self, filename)
Get the content of the upstream version of a file.
Returns:
  A tuple (base_content, new_content, is_binary, status)
base_content: The contents of the base file.
new_content: For text files, this is empty.  For binary files, this is
  the contents of the new file, since the diff output won't contain
  information to reconstruct the current file.
is_binary: True iff the file is binary.
status: The status of the file.
Definition at line 625 of file upload.py.
References upload.VersionControlSystem.GetBaseFile().
   def GetBaseFile(self, filename):
     """Get the content of the upstream version of a file.
     Returns:
       A tuple (base_content, new_content, is_binary, status)
         base_content: The contents of the base file.
         new_content: For text files, this is empty.  For binary files, this is
           the contents of the new file, since the diff output won't contain
           information to reconstruct the current file.
         is_binary: True iff the file is binary.
         status: The status of the file.
     """
     raise NotImplementedError(
         "abstract method -- subclass %s must override" % self.__class__)
def upload.VersionControlSystem.GetBaseFile (self, filename)
Get the content of the upstream version of a file.
Returns:
  A tuple (base_content, new_content, is_binary, status)
base_content: The contents of the base file.
new_content: For text files, this is empty.  For binary files, this is
  the contents of the new file, since the diff output won't contain
  information to reconstruct the current file.
is_binary: True iff the file is binary.
status: The status of the file.
Definition at line 625 of file upload.py.
References upload.VersionControlSystem.GetBaseFile().
   def GetBaseFile(self, filename):
     """Get the content of the upstream version of a file.
     Returns:
       A tuple (base_content, new_content, is_binary, status)
         base_content: The contents of the base file.
         new_content: For text files, this is empty.  For binary files, this is
           the contents of the new file, since the diff output won't contain
           information to reconstruct the current file.
         is_binary: True iff the file is binary.
         status: The status of the file.
     """
     raise NotImplementedError(
         "abstract method -- subclass %s must override" % self.__class__)
def upload.VersionControlSystem.GetBaseFile (self, filename)
Get the content of the upstream version of a file.
Returns:
  A tuple (base_content, new_content, is_binary, status)
base_content: The contents of the base file.
new_content: For text files, this is empty.  For binary files, this is
  the contents of the new file, since the diff output won't contain
  information to reconstruct the current file.
is_binary: True iff the file is binary.
status: The status of the file.
Definition at line 625 of file upload.py.
References upload.VersionControlSystem.GetBaseFile().
   def GetBaseFile(self, filename):
     """Get the content of the upstream version of a file.
     Returns:
       A tuple (base_content, new_content, is_binary, status)
         base_content: The contents of the base file.
         new_content: For text files, this is empty.  For binary files, this is
           the contents of the new file, since the diff output won't contain
           information to reconstruct the current file.
         is_binary: True iff the file is binary.
         status: The status of the file.
     """
     raise NotImplementedError(
         "abstract method -- subclass %s must override" % self.__class__)
def upload.VersionControlSystem.GetBaseFile (self, filename)
Get the content of the upstream version of a file.
Returns:
  A tuple (base_content, new_content, is_binary, status)
base_content: The contents of the base file.
new_content: For text files, this is empty.  For binary files, this is
  the contents of the new file, since the diff output won't contain
  information to reconstruct the current file.
is_binary: True iff the file is binary.
status: The status of the file.
Definition at line 625 of file upload.py.
References upload.VersionControlSystem.GetBaseFile().
   def GetBaseFile(self, filename):
     """Get the content of the upstream version of a file.
     Returns:
       A tuple (base_content, new_content, is_binary, status)
         base_content: The contents of the base file.
         new_content: For text files, this is empty.  For binary files, this is
           the contents of the new file, since the diff output won't contain
           information to reconstruct the current file.
         is_binary: True iff the file is binary.
         status: The status of the file.
     """
     raise NotImplementedError(
         "abstract method -- subclass %s must override" % self.__class__)
def upload.VersionControlSystem.GetBaseFiles (self, diff)
Helper that calls GetBase file for each file in the patch.
Returns:
  A dictionary that maps from filename to GetBaseFile's tuple.  Filenames
  are retrieved based on lines that start with "Index:" or
  "Property changes on:".
Definition at line 642 of file upload.py.
References upload.VersionControlSystem.GetBaseFile(), upload.VersionControlSystem.GetBaseFiles(), replace(), and upload.VersionControlSystem.UploadBaseFiles().
   def GetBaseFiles(self, diff):
     """Helper that calls GetBase file for each file in the patch.
     Returns:
       A dictionary that maps from filename to GetBaseFile's tuple.  Filenames
       are retrieved based on lines that start with "Index:" or
       "Property changes on:".
     """
     files = {}
     for line in diff.splitlines(True):
       if line.startswith('Index:') or line.startswith('Property changes on:'):
         unused, filename = line.split(':', 1)
         # On Windows if a file has property changes its filename uses '\'
         # instead of '/'.
         filename = filename.strip().replace('\\', '/')
         files[filename] = self.GetBaseFile(filename)
     return files
def upload.VersionControlSystem.GetBaseFiles (self, diff)
Helper that calls GetBase file for each file in the patch.
Returns:
  A dictionary that maps from filename to GetBaseFile's tuple.  Filenames
  are retrieved based on lines that start with "Index:" or
  "Property changes on:".
Definition at line 642 of file upload.py.
References upload.VersionControlSystem.GetBaseFile(), replace(), and upload.VersionControlSystem.UploadBaseFiles().
Referenced by upload.VersionControlSystem.GetBaseFiles().
   def GetBaseFiles(self, diff):
     """Helper that calls GetBase file for each file in the patch.
     Returns:
       A dictionary that maps from filename to GetBaseFile's tuple.  Filenames
       are retrieved based on lines that start with "Index:" or
       "Property changes on:".
     """
     files = {}
     for line in diff.splitlines(True):
       if line.startswith('Index:') or line.startswith('Property changes on:'):
         unused, filename = line.split(':', 1)
         # On Windows if a file has property changes its filename uses '\'
         # instead of '/'.
         filename = filename.strip().replace('\\', '/')
         files[filename] = self.GetBaseFile(filename)
     return files
def upload.VersionControlSystem.GetBaseFiles (self, diff)
Helper that calls GetBase file for each file in the patch.
Returns:
  A dictionary that maps from filename to GetBaseFile's tuple.  Filenames
  are retrieved based on lines that start with "Index:" or
  "Property changes on:".
Definition at line 642 of file upload.py.
References upload.VersionControlSystem.GetBaseFile(), upload.VersionControlSystem.GetBaseFiles(), replace(), and upload.VersionControlSystem.UploadBaseFiles().
   def GetBaseFiles(self, diff):
     """Helper that calls GetBase file for each file in the patch.
     Returns:
       A dictionary that maps from filename to GetBaseFile's tuple.  Filenames
       are retrieved based on lines that start with "Index:" or
       "Property changes on:".
     """
     files = {}
     for line in diff.splitlines(True):
       if line.startswith('Index:') or line.startswith('Property changes on:'):
         unused, filename = line.split(':', 1)
         # On Windows if a file has property changes its filename uses '\'
         # instead of '/'.
         filename = filename.strip().replace('\\', '/')
         files[filename] = self.GetBaseFile(filename)
     return files
def upload.VersionControlSystem.GetBaseFiles (self, diff)
Helper that calls GetBase file for each file in the patch.
Returns:
  A dictionary that maps from filename to GetBaseFile's tuple.  Filenames
  are retrieved based on lines that start with "Index:" or
  "Property changes on:".
Definition at line 642 of file upload.py.
References upload.VersionControlSystem.GetBaseFile(), upload.VersionControlSystem.GetBaseFiles(), replace(), and upload.VersionControlSystem.UploadBaseFiles().
   def GetBaseFiles(self, diff):
     """Helper that calls GetBase file for each file in the patch.
     Returns:
       A dictionary that maps from filename to GetBaseFile's tuple.  Filenames
       are retrieved based on lines that start with "Index:" or
       "Property changes on:".
     """
     files = {}
     for line in diff.splitlines(True):
       if line.startswith('Index:') or line.startswith('Property changes on:'):
         unused, filename = line.split(':', 1)
         # On Windows if a file has property changes its filename uses '\'
         # instead of '/'.
         filename = filename.strip().replace('\\', '/')
         files[filename] = self.GetBaseFile(filename)
     return files
def upload.VersionControlSystem.GetBaseFiles (self, diff)
Helper that calls GetBase file for each file in the patch.
Returns:
  A dictionary that maps from filename to GetBaseFile's tuple.  Filenames
  are retrieved based on lines that start with "Index:" or
  "Property changes on:".
Definition at line 642 of file upload.py.
References upload.VersionControlSystem.GetBaseFile(), upload.VersionControlSystem.GetBaseFiles(), replace(), and upload.VersionControlSystem.UploadBaseFiles().
   def GetBaseFiles(self, diff):
     """Helper that calls GetBase file for each file in the patch.
     Returns:
       A dictionary that maps from filename to GetBaseFile's tuple.  Filenames
       are retrieved based on lines that start with "Index:" or
       "Property changes on:".
     """
     files = {}
     for line in diff.splitlines(True):
       if line.startswith('Index:') or line.startswith('Property changes on:'):
         unused, filename = line.split(':', 1)
         # On Windows if a file has property changes its filename uses '\'
         # instead of '/'.
         filename = filename.strip().replace('\\', '/')
         files[filename] = self.GetBaseFile(filename)
     return files
def upload.VersionControlSystem.GetBaseFiles (self, diff)
Helper that calls GetBase file for each file in the patch.
Returns:
  A dictionary that maps from filename to GetBaseFile's tuple.  Filenames
  are retrieved based on lines that start with "Index:" or
  "Property changes on:".
Definition at line 642 of file upload.py.
References upload.VersionControlSystem.GetBaseFile(), upload.VersionControlSystem.GetBaseFiles(), replace(), and upload.VersionControlSystem.UploadBaseFiles().
   def GetBaseFiles(self, diff):
     """Helper that calls GetBase file for each file in the patch.
     Returns:
       A dictionary that maps from filename to GetBaseFile's tuple.  Filenames
       are retrieved based on lines that start with "Index:" or
       "Property changes on:".
     """
     files = {}
     for line in diff.splitlines(True):
       if line.startswith('Index:') or line.startswith('Property changes on:'):
         unused, filename = line.split(':', 1)
         # On Windows if a file has property changes its filename uses '\'
         # instead of '/'.
         filename = filename.strip().replace('\\', '/')
         files[filename] = self.GetBaseFile(filename)
     return files
def upload.VersionControlSystem.GetUnknownFiles (self)
Return a list of files unknown to the VCS.
Definition at line 608 of file upload.py.
References upload.VersionControlSystem.GetUnknownFiles().
   def GetUnknownFiles(self):
     """Return a list of files unknown to the VCS."""
     raise NotImplementedError(
         "abstract method -- subclass %s must override" % self.__class__)
def upload.VersionControlSystem.GetUnknownFiles (self)
Return a list of files unknown to the VCS.
Definition at line 608 of file upload.py.
Referenced by upload.VersionControlSystem.CheckForUnknownFiles(), and upload.VersionControlSystem.GetUnknownFiles().
   def GetUnknownFiles(self):
     """Return a list of files unknown to the VCS."""
     raise NotImplementedError(
         "abstract method -- subclass %s must override" % self.__class__)
def upload.VersionControlSystem.GetUnknownFiles (self)
Return a list of files unknown to the VCS.
Definition at line 608 of file upload.py.
References upload.VersionControlSystem.GetUnknownFiles().
   def GetUnknownFiles(self):
     """Return a list of files unknown to the VCS."""
     raise NotImplementedError(
         "abstract method -- subclass %s must override" % self.__class__)
def upload.VersionControlSystem.GetUnknownFiles (self)
Return a list of files unknown to the VCS.
Definition at line 608 of file upload.py.
References upload.VersionControlSystem.GetUnknownFiles().
   def GetUnknownFiles(self):
     """Return a list of files unknown to the VCS."""
     raise NotImplementedError(
         "abstract method -- subclass %s must override" % self.__class__)
def upload.VersionControlSystem.GetUnknownFiles (self)
Return a list of files unknown to the VCS.
Definition at line 608 of file upload.py.
References upload.VersionControlSystem.GetUnknownFiles().
   def GetUnknownFiles(self):
     """Return a list of files unknown to the VCS."""
     raise NotImplementedError(
         "abstract method -- subclass %s must override" % self.__class__)
def upload.VersionControlSystem.GetUnknownFiles (self)
Return a list of files unknown to the VCS.
Definition at line 608 of file upload.py.
References upload.VersionControlSystem.GetUnknownFiles().
   def GetUnknownFiles(self):
     """Return a list of files unknown to the VCS."""
     raise NotImplementedError(
         "abstract method -- subclass %s must override" % self.__class__)
def upload.VersionControlSystem.IsImage (self, filename)
Returns true if the filename has an image extension.
Definition at line 713 of file upload.py.
Referenced by upload.SubversionVCS.GetBaseFile(), upload.MercurialVCS.GetBaseFile(), and upload.VersionControlSystem.IsImage().
   def IsImage(self, filename):
     """Returns true if the filename has an image extension."""
     mimetype =  mimetypes.guess_type(filename)[0]
     if not mimetype:
       return False
     return mimetype.startswith("image/")
def upload.VersionControlSystem.IsImage (self, filename)
Returns true if the filename has an image extension.
Definition at line 713 of file upload.py.
References upload.VersionControlSystem.IsImage().
   def IsImage(self, filename):
     """Returns true if the filename has an image extension."""
     mimetype =  mimetypes.guess_type(filename)[0]
     if not mimetype:
       return False
     return mimetype.startswith("image/")
def upload.VersionControlSystem.IsImage (self, filename)
Returns true if the filename has an image extension.
Definition at line 713 of file upload.py.
References upload.VersionControlSystem.IsImage().
   def IsImage(self, filename):
     """Returns true if the filename has an image extension."""
     mimetype =  mimetypes.guess_type(filename)[0]
     if not mimetype:
       return False
     return mimetype.startswith("image/")
def upload.VersionControlSystem.IsImage (self, filename)
Returns true if the filename has an image extension.
Definition at line 713 of file upload.py.
References upload.VersionControlSystem.IsImage().
   def IsImage(self, filename):
     """Returns true if the filename has an image extension."""
     mimetype =  mimetypes.guess_type(filename)[0]
     if not mimetype:
       return False
     return mimetype.startswith("image/")
def upload.VersionControlSystem.IsImage (self, filename)
Returns true if the filename has an image extension.
Definition at line 713 of file upload.py.
References upload.VersionControlSystem.IsImage().
   def IsImage(self, filename):
     """Returns true if the filename has an image extension."""
     mimetype =  mimetypes.guess_type(filename)[0]
     if not mimetype:
       return False
     return mimetype.startswith("image/")
def upload.VersionControlSystem.IsImage (self, filename)
Returns true if the filename has an image extension.
Definition at line 713 of file upload.py.
References upload.VersionControlSystem.IsImage().
   def IsImage(self, filename):
     """Returns true if the filename has an image extension."""
     mimetype =  mimetypes.guess_type(filename)[0]
     if not mimetype:
       return False
     return mimetype.startswith("image/")
def upload.VersionControlSystem.UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
Uploads the base files (and if necessary, the current ones as well).
Definition at line 662 of file upload.py.
References upload.EncodeMultipartFormData(), and upload.StatusUpdate().
                       files):
     """Uploads the base files (and if necessary, the current ones as well)."""
     def UploadFile(filename, file_id, content, is_binary, status, is_base):
       """Uploads a file to the server."""
       file_too_large = False
       if is_base:
         type = "base"
       else:
         type = "current"
       if len(content) > MAX_UPLOAD_SIZE:
         print ("Not uploading the %s file for %s because it's too large." %
                (type, filename))
         file_too_large = True
         content = ""
       checksum = md5.new(content).hexdigest()
       if options.verbose > 0 and not file_too_large:
         print "Uploading %s file for %s" % (type, filename)
       url = "/%d/upload_content/%d/%d" % (int(issue), int(patchset), file_id)
       form_fields = [("filename", filename),
                      ("status", status),
                      ("checksum", checksum),
                      ("is_binary", str(is_binary)),
                      ("is_current", str(not is_base)),
                     ]
       if file_too_large:
         form_fields.append(("file_too_large", "1"))
       if options.email:
         form_fields.append(("user", options.email))
       ctype, body = EncodeMultipartFormData(form_fields,
                                             [("data", filename, content)])
       response_body = rpc_server.Send(url, body,
                                       content_type=ctype)
       if not response_body.startswith("OK"):
         StatusUpdate("  --> %s" % response_body)
         sys.exit(1)
     patches = dict()
     [patches.setdefault(v, k) for k, v in patch_list]
     for filename in patches.keys():
       base_content, new_content, is_binary, status = files[filename]
       file_id_str = patches.get(filename)
       if file_id_str.find("nobase") != -1:
         base_content = None
         file_id_str = file_id_str[file_id_str.rfind("_") + 1:]
       file_id = int(file_id_str)
       if base_content != None:
         UploadFile(filename, file_id, base_content, is_binary, status, True)
       if new_content != None:
         UploadFile(filename, file_id, new_content, is_binary, status, False)
def upload.VersionControlSystem.UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
Uploads the base files (and if necessary, the current ones as well).
Definition at line 662 of file upload.py.
References upload.EncodeMultipartFormData(), and upload.StatusUpdate().
Referenced by upload.VersionControlSystem.GetBaseFiles().
                       files):
     """Uploads the base files (and if necessary, the current ones as well)."""
     def UploadFile(filename, file_id, content, is_binary, status, is_base):
       """Uploads a file to the server."""
       file_too_large = False
       if is_base:
         type = "base"
       else:
         type = "current"
       if len(content) > MAX_UPLOAD_SIZE:
         print ("Not uploading the %s file for %s because it's too large." %
                (type, filename))
         file_too_large = True
         content = ""
       checksum = md5.new(content).hexdigest()
       if options.verbose > 0 and not file_too_large:
         print "Uploading %s file for %s" % (type, filename)
       url = "/%d/upload_content/%d/%d" % (int(issue), int(patchset), file_id)
       form_fields = [("filename", filename),
                      ("status", status),
                      ("checksum", checksum),
                      ("is_binary", str(is_binary)),
                      ("is_current", str(not is_base)),
                     ]
       if file_too_large:
         form_fields.append(("file_too_large", "1"))
       if options.email:
         form_fields.append(("user", options.email))
       ctype, body = EncodeMultipartFormData(form_fields,
                                             [("data", filename, content)])
       response_body = rpc_server.Send(url, body,
                                       content_type=ctype)
       if not response_body.startswith("OK"):
         StatusUpdate("  --> %s" % response_body)
         sys.exit(1)
     patches = dict()
     [patches.setdefault(v, k) for k, v in patch_list]
     for filename in patches.keys():
       base_content, new_content, is_binary, status = files[filename]
       file_id_str = patches.get(filename)
       if file_id_str.find("nobase") != -1:
         base_content = None
         file_id_str = file_id_str[file_id_str.rfind("_") + 1:]
       file_id = int(file_id_str)
       if base_content != None:
         UploadFile(filename, file_id, base_content, is_binary, status, True)
       if new_content != None:
         UploadFile(filename, file_id, new_content, is_binary, status, False)
def upload.VersionControlSystem.UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
Uploads the base files (and if necessary, the current ones as well).
Definition at line 662 of file upload.py.
References upload.EncodeMultipartFormData(), and upload.StatusUpdate().
                       files):
     """Uploads the base files (and if necessary, the current ones as well)."""
     def UploadFile(filename, file_id, content, is_binary, status, is_base):
       """Uploads a file to the server."""
       file_too_large = False
       if is_base:
         type = "base"
       else:
         type = "current"
       if len(content) > MAX_UPLOAD_SIZE:
         print ("Not uploading the %s file for %s because it's too large." %
                (type, filename))
         file_too_large = True
         content = ""
       checksum = md5.new(content).hexdigest()
       if options.verbose > 0 and not file_too_large:
         print "Uploading %s file for %s" % (type, filename)
       url = "/%d/upload_content/%d/%d" % (int(issue), int(patchset), file_id)
       form_fields = [("filename", filename),
                      ("status", status),
                      ("checksum", checksum),
                      ("is_binary", str(is_binary)),
                      ("is_current", str(not is_base)),
                     ]
       if file_too_large:
         form_fields.append(("file_too_large", "1"))
       if options.email:
         form_fields.append(("user", options.email))
       ctype, body = EncodeMultipartFormData(form_fields,
                                             [("data", filename, content)])
       response_body = rpc_server.Send(url, body,
                                       content_type=ctype)
       if not response_body.startswith("OK"):
         StatusUpdate("  --> %s" % response_body)
         sys.exit(1)
     patches = dict()
     [patches.setdefault(v, k) for k, v in patch_list]
     for filename in patches.keys():
       base_content, new_content, is_binary, status = files[filename]
       file_id_str = patches.get(filename)
       if file_id_str.find("nobase") != -1:
         base_content = None
         file_id_str = file_id_str[file_id_str.rfind("_") + 1:]
       file_id = int(file_id_str)
       if base_content != None:
         UploadFile(filename, file_id, base_content, is_binary, status, True)
       if new_content != None:
         UploadFile(filename, file_id, new_content, is_binary, status, False)
def upload.VersionControlSystem.UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
Uploads the base files (and if necessary, the current ones as well).
Definition at line 662 of file upload.py.
References upload.EncodeMultipartFormData(), and upload.StatusUpdate().
                       files):
     """Uploads the base files (and if necessary, the current ones as well)."""
     def UploadFile(filename, file_id, content, is_binary, status, is_base):
       """Uploads a file to the server."""
       file_too_large = False
       if is_base:
         type = "base"
       else:
         type = "current"
       if len(content) > MAX_UPLOAD_SIZE:
         print ("Not uploading the %s file for %s because it's too large." %
                (type, filename))
         file_too_large = True
         content = ""
       checksum = md5.new(content).hexdigest()
       if options.verbose > 0 and not file_too_large:
         print "Uploading %s file for %s" % (type, filename)
       url = "/%d/upload_content/%d/%d" % (int(issue), int(patchset), file_id)
       form_fields = [("filename", filename),
                      ("status", status),
                      ("checksum", checksum),
                      ("is_binary", str(is_binary)),
                      ("is_current", str(not is_base)),
                     ]
       if file_too_large:
         form_fields.append(("file_too_large", "1"))
       if options.email:
         form_fields.append(("user", options.email))
       ctype, body = EncodeMultipartFormData(form_fields,
                                             [("data", filename, content)])
       response_body = rpc_server.Send(url, body,
                                       content_type=ctype)
       if not response_body.startswith("OK"):
         StatusUpdate("  --> %s" % response_body)
         sys.exit(1)
     patches = dict()
     [patches.setdefault(v, k) for k, v in patch_list]
     for filename in patches.keys():
       base_content, new_content, is_binary, status = files[filename]
       file_id_str = patches.get(filename)
       if file_id_str.find("nobase") != -1:
         base_content = None
         file_id_str = file_id_str[file_id_str.rfind("_") + 1:]
       file_id = int(file_id_str)
       if base_content != None:
         UploadFile(filename, file_id, base_content, is_binary, status, True)
       if new_content != None:
         UploadFile(filename, file_id, new_content, is_binary, status, False)
def upload.VersionControlSystem.UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
Uploads the base files (and if necessary, the current ones as well).
Definition at line 662 of file upload.py.
References upload.EncodeMultipartFormData(), and upload.StatusUpdate().
                       files):
     """Uploads the base files (and if necessary, the current ones as well)."""
     def UploadFile(filename, file_id, content, is_binary, status, is_base):
       """Uploads a file to the server."""
       file_too_large = False
       if is_base:
         type = "base"
       else:
         type = "current"
       if len(content) > MAX_UPLOAD_SIZE:
         print ("Not uploading the %s file for %s because it's too large." %
                (type, filename))
         file_too_large = True
         content = ""
       checksum = md5.new(content).hexdigest()
       if options.verbose > 0 and not file_too_large:
         print "Uploading %s file for %s" % (type, filename)
       url = "/%d/upload_content/%d/%d" % (int(issue), int(patchset), file_id)
       form_fields = [("filename", filename),
                      ("status", status),
                      ("checksum", checksum),
                      ("is_binary", str(is_binary)),
                      ("is_current", str(not is_base)),
                     ]
       if file_too_large:
         form_fields.append(("file_too_large", "1"))
       if options.email:
         form_fields.append(("user", options.email))
       ctype, body = EncodeMultipartFormData(form_fields,
                                             [("data", filename, content)])
       response_body = rpc_server.Send(url, body,
                                       content_type=ctype)
       if not response_body.startswith("OK"):
         StatusUpdate("  --> %s" % response_body)
         sys.exit(1)
     patches = dict()
     [patches.setdefault(v, k) for k, v in patch_list]
     for filename in patches.keys():
       base_content, new_content, is_binary, status = files[filename]
       file_id_str = patches.get(filename)
       if file_id_str.find("nobase") != -1:
         base_content = None
         file_id_str = file_id_str[file_id_str.rfind("_") + 1:]
       file_id = int(file_id_str)
       if base_content != None:
         UploadFile(filename, file_id, base_content, is_binary, status, True)
       if new_content != None:
         UploadFile(filename, file_id, new_content, is_binary, status, False)
def upload.VersionControlSystem.UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
Uploads the base files (and if necessary, the current ones as well).
Definition at line 662 of file upload.py.
References upload.EncodeMultipartFormData(), and upload.StatusUpdate().
                       files):
     """Uploads the base files (and if necessary, the current ones as well)."""
     def UploadFile(filename, file_id, content, is_binary, status, is_base):
       """Uploads a file to the server."""
       file_too_large = False
       if is_base:
         type = "base"
       else:
         type = "current"
       if len(content) > MAX_UPLOAD_SIZE:
         print ("Not uploading the %s file for %s because it's too large." %
                (type, filename))
         file_too_large = True
         content = ""
       checksum = md5.new(content).hexdigest()
       if options.verbose > 0 and not file_too_large:
         print "Uploading %s file for %s" % (type, filename)
       url = "/%d/upload_content/%d/%d" % (int(issue), int(patchset), file_id)
       form_fields = [("filename", filename),
                      ("status", status),
                      ("checksum", checksum),
                      ("is_binary", str(is_binary)),
                      ("is_current", str(not is_base)),
                     ]
       if file_too_large:
         form_fields.append(("file_too_large", "1"))
       if options.email:
         form_fields.append(("user", options.email))
       ctype, body = EncodeMultipartFormData(form_fields,
                                             [("data", filename, content)])
       response_body = rpc_server.Send(url, body,
                                       content_type=ctype)
       if not response_body.startswith("OK"):
         StatusUpdate("  --> %s" % response_body)
         sys.exit(1)
     patches = dict()
     [patches.setdefault(v, k) for k, v in patch_list]
     for filename in patches.keys():
       base_content, new_content, is_binary, status = files[filename]
       file_id_str = patches.get(filename)
       if file_id_str.find("nobase") != -1:
         base_content = None
         file_id_str = file_id_str[file_id_str.rfind("_") + 1:]
       file_id = int(file_id_str)
       if base_content != None:
         UploadFile(filename, file_id, base_content, is_binary, status, True)
       if new_content != None:
         UploadFile(filename, file_id, new_content, is_binary, status, False)
Member Data Documentation
upload.VersionControlSystem.options
Definition at line 597 of file upload.py.
Referenced by upload.VersionControlSystem.__init__().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/scripts/upload.py