proxygen: folly::test::WriteFileAtomic Class Reference
folly::test::WriteFileAtomic Class Reference
Protected Member Functions
WriteFileAtomic ()
std::set< std::string > listTmpDir () const
std::string readData (const string &path) const
struct stat statFile (const string &path) const
mode_t getPerms (const string &path)
string tmpPath (StringPiece name)
void setDirPerms (mode_t mode)
Protected Member Functions inherited from testing::Test
Test ()
virtual void SetUp ()
virtual void TearDown ()
Test ()
virtual void SetUp ()
virtual void TearDown ()
Test ()
virtual void SetUp ()
virtual void TearDown ()
Protected Attributes
TemporaryDirectory tmpDir_ {"folly_file_test"}
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Detailed Description
Definition at line 351 of file FileUtilTest.cpp.
Constructor & Destructor Documentation
folly::test::WriteFileAtomic::WriteFileAtomic () inline protected
Definition at line 353 of file FileUtilTest.cpp.
 {}
Member Function Documentation
mode_t folly::test::WriteFileAtomic::getPerms (const string & path) inline protected
Definition at line 378 of file FileUtilTest.cpp.
{
     return (statFile(path).st_mode & 0777);
   }
std::set<std::string> folly::test::WriteFileAtomic::listTmpDir () const inline protected
Definition at line 355 of file FileUtilTest.cpp.
{
     std::set<std::string> entries;
     for (auto& entry : fs::directory_iterator(tmpDir_.path())) {
       entries.insert(entry.path().filename().string());
     }
     return entries;
   }
std::string folly::test::WriteFileAtomic::readData (const string & path) const inline protected
Definition at line 363 of file FileUtilTest.cpp.
References folly::data(), folly::readFile(), and folly::throwSystemError().
{
     string data;
     if (!readFile(path.c_str(), data)) {
       throwSystemError("failed to read ", path);
     }
     return data;
   }
void folly::test::WriteFileAtomic::setDirPerms (mode_t mode) inline protected
Definition at line 386 of file FileUtilTest.cpp.
References folly::checkUnixError(), and mode.
{
     auto rc = chmod(tmpDir_.path().string().c_str(), mode);
     checkUnixError(rc, "failed to set permissions on tmp dir");
   }
struct stat folly::test::WriteFileAtomic::statFile (const string & path) const inline protected
Definition at line 371 of file FileUtilTest.cpp.
References folly::checkUnixError(), and s.
{
     struct stat s;
     auto rc = stat(path.c_str(), &s);
     checkUnixError(rc, "failed to stat() ", path);
     return s;
   }
string folly::test::WriteFileAtomic::tmpPath (StringPiece name) inline protected
Definition at line 382 of file FileUtilTest.cpp.
References folly::Range< Iter >::str().
{
     return tmpDir_.path().string() + "/" + name.str();
   }
Member Data Documentation
TemporaryDirectory folly::test::WriteFileAtomic::tmpDir_ {"folly_file_test"} protected
Definition at line 391 of file FileUtilTest.cpp.
The documentation for this class was generated from the following file:
proxygen/folly/folly/test/FileUtilTest.cpp