proxygen: wangle::OutboundContextImpl< H > Class Template Reference
wangle::OutboundContextImpl< H > Class Template Reference
#include <HandlerContext-inl.h>
Public Types
typedef H::rin Rin
typedef H::rout Rout
typedef H::win Win
typedef H::wout Wout
Public Member Functions
OutboundContextImpl (std::weak_ptr< PipelineBase > pipeline, std::shared_ptr< H > handler)
OutboundContextImpl ()
~OutboundContextImpl () override=default
folly::Future< folly::Unit > fireWrite (Wout msg) override
folly::Future< folly::Unit > fireWriteException (folly::exception_wrapper e) override
folly::Future< folly::Unit > fireClose () override
PipelineBase * getPipeline () override
std::shared_ptr< PipelineBase > getPipelineShared () override
folly::Future< folly::Unit > write (Win msg) override
folly::Future< folly::Unit > writeException (folly::exception_wrapper e) override
folly::Future< folly::Unit > close () override
Public Member Functions inherited from wangle::OutboundHandlerContext< H::wout >
virtual ~OutboundHandlerContext ()=default
std::shared_ptr< folly::AsyncTransport > getTransport ()
Public Member Functions inherited from wangle::OutboundLink< H::win >
virtual ~OutboundLink ()=default
Public Member Functions inherited from wangle::ContextImplBase< H, OutboundHandlerContext< H::wout > >
~ContextImplBase () override=default
H * getHandler ()
void initialize (std::weak_ptr< PipelineBase > pipeline, std::shared_ptr< H > handler)
void attachPipeline () override
void detachPipeline () override
void setNextIn (PipelineContext *ctx) override
void setNextOut (PipelineContext *ctx) override
HandlerDir getDirection () override
Public Member Functions inherited from wangle::PipelineContext
virtual ~PipelineContext ()=default
template<class H , class HandlerContext >
void attachContext (H *handler, HandlerContext *ctx)
template<class H , class HandlerContext >
void detachContext (H *handler, HandlerContext *)
Static Public Attributes
static const HandlerDir dir = HandlerDir::OUT
Additional Inherited Members
Protected Attributes inherited from wangle::ContextImplBase< H, OutboundHandlerContext< H::wout > >
OutboundHandlerContext< H::wout > * impl_
std::weak_ptr< PipelineBase > pipelineWeak_
PipelineBase * pipelineRaw_
std::shared_ptr< H > handler_
InboundLink< typename H::rout > * nextIn_
OutboundLink< typename H::wout > * nextOut_
Detailed Description
template<class H>
class wangle::OutboundContextImpl< H >
Definition at line 426 of file HandlerContext-inl.h.
Member Typedef Documentation
template<class H > typedef H::rin wangle::OutboundContextImpl< H >::Rin
Definition at line 431 of file HandlerContext-inl.h.
template<class H > typedef H::rout wangle::OutboundContextImpl< H >::Rout
Definition at line 432 of file HandlerContext-inl.h.
template<class H > typedef H::win wangle::OutboundContextImpl< H >::Win
Definition at line 433 of file HandlerContext-inl.h.
template<class H > typedef H::wout wangle::OutboundContextImpl< H >::Wout
Definition at line 434 of file HandlerContext-inl.h.
Constructor & Destructor Documentation
template<class H > wangle::OutboundContextImpl< H >::OutboundContextImpl (std::weak_ptr< PipelineBase > pipeline, std::shared_ptr< H > handler) inline explicit
Definition at line 437 of file HandlerContext-inl.h.
References folly::gen::move.
{
     this->impl_ = this;
     this->initialize(pipeline, std::move(handler));
   }
template<class H > wangle::OutboundContextImpl< H >::OutboundContextImpl () inline
Definition at line 445 of file HandlerContext-inl.h.
{
     this->impl_ = this;
   }
template<class H > wangle::OutboundContextImpl< H >::~OutboundContextImpl () override default
Member Function Documentation
template<class H > folly::Future<folly::Unit> wangle::OutboundContextImpl< H >::close () inline override virtual
Implements wangle::OutboundLink< H::win >.
Definition at line 503 of file HandlerContext-inl.h.
References folly::gen::guard().
{
     auto guard = this->pipelineWeak_.lock();
     return this->handler_->close(this);
   }
template<class H > folly::Future<folly::Unit> wangle::OutboundContextImpl< H >::fireClose () inline override virtual
Implements wangle::OutboundHandlerContext< H::wout >.
Definition at line 473 of file HandlerContext-inl.h.
References folly::gen::guard(), folly::makeFuture(), and folly::WARNING.
{
     auto guard = this->pipelineWeak_.lock();
     if (this->nextOut_) {
       return this->nextOut_->close();
     } else {
       LOG(WARNING) << "close reached end of pipeline";
       return folly::makeFuture();
     }
   }
template<class H > folly::Future<folly::Unit> wangle::OutboundContextImpl< H >::fireWrite (Wout msg) inline override virtual
Implements wangle::OutboundHandlerContext< H::wout >.
Definition at line 452 of file HandlerContext-inl.h.
References folly::gen::guard(), folly::makeFuture(), and folly::WARNING.
{
     auto guard = this->pipelineWeak_.lock();
     if (this->nextOut_) {
       return this->nextOut_->write(std::forward<Wout>(msg));
     } else {
       LOG(WARNING) << "write reached end of pipeline";
       return folly::makeFuture();
     }
   }
template<class H > folly::Future<folly::Unit> wangle::OutboundContextImpl< H >::fireWriteException (folly::exception_wrapper e) inline override virtual
Implements wangle::OutboundHandlerContext< H::wout >.
Definition at line 462 of file HandlerContext-inl.h.
References folly::gen::guard(), folly::makeFuture(), folly::gen::move, and folly::WARNING.
{
     auto guard = this->pipelineWeak_.lock();
     if (this->nextOut_) {
       return this->nextOut_->writeException(std::move(e));
     } else {
       LOG(WARNING) << "close reached end of pipeline";
       return folly::makeFuture();
     }
   }
template<class H > PipelineBase* wangle::OutboundContextImpl< H >::getPipeline () inline override virtual
Implements wangle::OutboundHandlerContext< H::wout >.
Definition at line 483 of file HandlerContext-inl.h.
{
     return this->pipelineRaw_;
   }
template<class H > std::shared_ptr<PipelineBase> wangle::OutboundContextImpl< H >::getPipelineShared () inline override virtual
Implements wangle::OutboundHandlerContext< H::wout >.
Definition at line 487 of file HandlerContext-inl.h.
{
     return this->pipelineWeak_.lock();
   }
template<class H > folly::Future<folly::Unit> wangle::OutboundContextImpl< H >::write (Win msg) inline override virtual
Implements wangle::OutboundLink< H::win >.
Definition at line 492 of file HandlerContext-inl.h.
References folly::gen::guard().
{
     auto guard = this->pipelineWeak_.lock();
     return this->handler_->write(this, std::forward<Win>(msg));
   }
template<class H > folly::Future<folly::Unit> wangle::OutboundContextImpl< H >::writeException (folly::exception_wrapper e) inline override virtual
Implements wangle::OutboundLink< H::win >.
Definition at line 497 of file HandlerContext-inl.h.
References folly::gen::guard(), and folly::gen::move.
{
     auto guard = this->pipelineWeak_.lock();
     return this->handler_->writeException(this, std::move(e));
   }
Member Data Documentation
template<class H > const HandlerDir wangle::OutboundContextImpl< H >::dir = HandlerDir::OUT static
Definition at line 435 of file HandlerContext-inl.h.
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/channel/HandlerContext-inl.h