proxygen: testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer > Class Template Reference
testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer > Class Template Reference
#include <gmock-matchers.h>
Public Types
typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(LhsContainer)> LhsView
typedef LhsView::type LhsStlContainer
typedef LhsView::const_reference LhsStlContainerReference
typedef RemoveConstFromKey< typename LhsStlContainer::value_type >::type LhsValue
typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(LhsContainer)> LhsView
typedef LhsView::type LhsStlContainer
typedef LhsView::const_reference LhsStlContainerReference
typedef RemoveConstFromKey< typename LhsStlContainer::value_type >::type LhsValue
typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(LhsContainer)> LhsView
typedef LhsView::type LhsStlContainer
typedef LhsView::const_reference LhsStlContainerReference
typedef RemoveConstFromKey< typename LhsStlContainer::value_type >::type LhsValue
Public Member Functions
Impl (const Comparator &comparator, const ContainerMatcher &matcher)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (LhsContainer lhs, MatchResultListener *listener) const
Impl (const Comparator &comparator, const ContainerMatcher &matcher)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (LhsContainer lhs, MatchResultListener *listener) const
Impl (const Comparator &comparator, const ContainerMatcher &matcher)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (LhsContainer lhs, MatchResultListener *listener) const
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
virtual ~MatcherDescriberInterface ()
virtual ~MatcherDescriberInterface ()
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (Impl)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (Impl)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (Impl)
Private Attributes
const Comparator comparator_
const Matcher< const ::std::vector< LhsValue > & > matcher_
Detailed Description
template<typename Comparator, typename ContainerMatcher>
template<typename LhsContainer>
class testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >
Definition at line 2625 of file gmock-matchers.h.
Member Typedef Documentation
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > typedef LhsView::type testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::LhsStlContainer
Definition at line 2629 of file gmock-matchers.h.
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > typedef LhsView::type testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::LhsStlContainer
Definition at line 2629 of file gmock-matchers.h.
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > typedef LhsView::type testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::LhsStlContainer
Definition at line 2629 of file gmock-matchers.h.
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > typedef LhsView::const_reference testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::LhsStlContainerReference
Definition at line 2630 of file gmock-matchers.h.
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > typedef LhsView::const_reference testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::LhsStlContainerReference
Definition at line 2630 of file gmock-matchers.h.
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > typedef LhsView::const_reference testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::LhsStlContainerReference
Definition at line 2630 of file gmock-matchers.h.
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > typedef RemoveConstFromKey< typename LhsStlContainer::value_type>::type testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::LhsValue
Definition at line 2634 of file gmock-matchers.h.
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > typedef RemoveConstFromKey< typename LhsStlContainer::value_type>::type testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::LhsValue
Definition at line 2634 of file gmock-matchers.h.
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > typedef RemoveConstFromKey< typename LhsStlContainer::value_type>::type testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::LhsValue
Definition at line 2634 of file gmock-matchers.h.
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(LhsContainer)> testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::LhsView
Definition at line 2628 of file gmock-matchers.h.
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(LhsContainer)> testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::LhsView
Definition at line 2628 of file gmock-matchers.h.
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(LhsContainer)> testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::LhsView
Definition at line 2628 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::Impl (const Comparator & comparator, const ContainerMatcher & matcher) inline
Definition at line 2636 of file gmock-matchers.h.
         : comparator_(comparator), matcher_(matcher) {}
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::Impl (const Comparator & comparator, const ContainerMatcher & matcher) inline
Definition at line 2636 of file gmock-matchers.h.
         : comparator_(comparator), matcher_(matcher) {}
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::Impl (const Comparator & comparator, const ContainerMatcher & matcher) inline
Definition at line 2636 of file gmock-matchers.h.
         : comparator_(comparator), matcher_(matcher) {}
Member Function Documentation
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > virtual void testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 2644 of file gmock-matchers.h.
{
       *os << "(when sorted) ";
       matcher_.DescribeNegationTo(os);
     }
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > virtual void testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 2644 of file gmock-matchers.h.
{
       *os << "(when sorted) ";
       matcher_.DescribeNegationTo(os);
     }
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > virtual void testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 2644 of file gmock-matchers.h.
{
       *os << "(when sorted) ";
       matcher_.DescribeNegationTo(os);
     }
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > virtual void testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 2639 of file gmock-matchers.h.
{
       *os << "(when sorted) ";
       matcher_.DescribeTo(os);
     }
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > virtual void testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 2639 of file gmock-matchers.h.
{
       *os << "(when sorted) ";
       matcher_.DescribeTo(os);
     }
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > virtual void testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 2639 of file gmock-matchers.h.
{
       *os << "(when sorted) ";
       matcher_.DescribeTo(os);
     }
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::GTEST_DISALLOW_COPY_AND_ASSIGN_ (Impl< LhsContainer >) private
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::GTEST_DISALLOW_COPY_AND_ASSIGN_ (Impl< LhsContainer >) private
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::GTEST_DISALLOW_COPY_AND_ASSIGN_ (Impl< LhsContainer >) private
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > virtual bool testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::MatchAndExplain (LhsContainer lhs, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< LhsContainer >.
Definition at line 2649 of file gmock-matchers.h.
References testing::MatchResultListener::IsInterested(), testing::internal::PrintIfNotEmpty(), testing::StringMatchResultListener::str(), testing::MatchResultListener::stream(), and testing::internal::UniversalPrint().
{
       LhsStlContainerReference lhs_stl_container = LhsView::ConstReference(lhs);
       ::std::vector<LhsValue> sorted_container(lhs_stl_container.begin(),
                                                lhs_stl_container.end());
       ::std::sort(
            sorted_container.begin(), sorted_container.end(), comparator_);
       if (!listener->IsInterested()) {
         // If the listener is not interested, we do not need to
         // construct the inner explanation.
         return matcher_.Matches(sorted_container);
       }
       *listener << "which is ";
       UniversalPrint(sorted_container, listener->stream());
       *listener << " when sorted";
       StringMatchResultListener inner_listener;
       const bool match = matcher_.MatchAndExplain(sorted_container,
                                                   &inner_listener);
       PrintIfNotEmpty(inner_listener.str(), listener->stream());
       return match;
     }
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > virtual bool testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::MatchAndExplain (LhsContainer lhs, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< LhsContainer >.
Definition at line 2649 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, testing::MatchResultListener::GTEST_DISALLOW_COPY_AND_ASSIGN_(), testing::internal::PrintIfNotEmpty(), testing::StringMatchResultListener::str(), and testing::internal::UniversalPrint().
{
       LhsStlContainerReference lhs_stl_container = LhsView::ConstReference(lhs);
       ::std::vector<LhsValue> sorted_container(lhs_stl_container.begin(),
                                                lhs_stl_container.end());
       ::std::sort(
            sorted_container.begin(), sorted_container.end(), comparator_);
       if (!listener->IsInterested()) {
         // If the listener is not interested, we do not need to
         // construct the inner explanation.
         return matcher_.Matches(sorted_container);
       }
       *listener << "which is ";
       UniversalPrint(sorted_container, listener->stream());
       *listener << " when sorted";
       StringMatchResultListener inner_listener;
       const bool match = matcher_.MatchAndExplain(sorted_container,
                                                   &inner_listener);
       PrintIfNotEmpty(inner_listener.str(), listener->stream());
       return match;
     }
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > virtual bool testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::MatchAndExplain (LhsContainer lhs, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< LhsContainer >.
Definition at line 2649 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, testing::MatchResultListener::GTEST_DISALLOW_COPY_AND_ASSIGN_(), testing::internal::PrintIfNotEmpty(), testing::StringMatchResultListener::str(), and testing::internal::UniversalPrint().
{
       LhsStlContainerReference lhs_stl_container = LhsView::ConstReference(lhs);
       ::std::vector<LhsValue> sorted_container(lhs_stl_container.begin(),
                                                lhs_stl_container.end());
       ::std::sort(
            sorted_container.begin(), sorted_container.end(), comparator_);
       if (!listener->IsInterested()) {
         // If the listener is not interested, we do not need to
         // construct the inner explanation.
         return matcher_.Matches(sorted_container);
       }
       *listener << "which is ";
       UniversalPrint(sorted_container, listener->stream());
       *listener << " when sorted";
       StringMatchResultListener inner_listener;
       const bool match = matcher_.MatchAndExplain(sorted_container,
                                                   &inner_listener);
       PrintIfNotEmpty(inner_listener.str(), listener->stream());
       return match;
     }
Member Data Documentation
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > const Comparator testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::comparator_ private
Definition at line 2675 of file gmock-matchers.h.
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > const Matcher< const ::std::vector< LhsValue > & > testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::matcher_ private
Definition at line 2676 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h