proxygen: upload.SubversionVCS Class Reference
upload.SubversionVCS Class Reference
Public Member Functions
def __init__ (self, options)
def GuessBase (self, required)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def ReadFile (self, filename)
def GetStatus (self, filename)
def GetBaseFile (self, filename)
def __init__ (self, options)
def GuessBase (self, required)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def ReadFile (self, filename)
def GetStatus (self, filename)
def GetBaseFile (self, filename)
def __init__ (self, options)
def GuessBase (self, required)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def ReadFile (self, filename)
def GetStatus (self, filename)
def GetBaseFile (self, filename)
def __init__ (self, options)
def GuessBase (self, required)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def ReadFile (self, filename)
def GetStatus (self, filename)
def GetBaseFile (self, filename)
def __init__ (self, options)
def GuessBase (self, required)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def ReadFile (self, filename)
def GetStatus (self, filename)
def GetBaseFile (self, filename)
def __init__ (self, options)
def GuessBase (self, required)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def ReadFile (self, filename)
def GetStatus (self, filename)
def GetBaseFile (self, filename)
Public Member Functions inherited from upload.VersionControlSystem
def __init__ (self, options)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def CheckForUnknownFiles (self)
def GetBaseFile (self, filename)
def GetBaseFiles (self, diff)
def UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
def IsImage (self, filename)
def __init__ (self, options)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def CheckForUnknownFiles (self)
def GetBaseFile (self, filename)
def GetBaseFiles (self, diff)
def UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
def IsImage (self, filename)
def __init__ (self, options)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def CheckForUnknownFiles (self)
def GetBaseFile (self, filename)
def GetBaseFiles (self, diff)
def UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
def IsImage (self, filename)
def __init__ (self, options)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def CheckForUnknownFiles (self)
def GetBaseFile (self, filename)
def GetBaseFiles (self, diff)
def UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
def IsImage (self, filename)
def __init__ (self, options)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def CheckForUnknownFiles (self)
def GetBaseFile (self, filename)
def GetBaseFiles (self, diff)
def UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
def IsImage (self, filename)
def __init__ (self, options)
def GenerateDiff (self, args)
def GetUnknownFiles (self)
def CheckForUnknownFiles (self)
def GetBaseFile (self, filename)
def GetBaseFiles (self, diff)
def UploadBaseFiles (self, issue, rpc_server, patch_list, patchset, options, files)
def IsImage (self, filename)
Public Attributes
rev_start
rev_end
svnls_cache
svn_base
Public Attributes inherited from upload.VersionControlSystem
options
Private Member Functions
def _GuessBase (self, required)
def _CollapseKeywords (self, content, keyword_str)
def _GuessBase (self, required)
def _CollapseKeywords (self, content, keyword_str)
def _GuessBase (self, required)
def _CollapseKeywords (self, content, keyword_str)
def _GuessBase (self, required)
def _CollapseKeywords (self, content, keyword_str)
def _GuessBase (self, required)
def _CollapseKeywords (self, content, keyword_str)
def _GuessBase (self, required)
def _CollapseKeywords (self, content, keyword_str)
Detailed Description
Implementation of the VersionControlSystem interface for Subversion.
Definition at line 721 of file upload.py.
Constructor & Destructor Documentation
def upload.SubversionVCS.__init__ (self, options)
Definition at line 724 of file upload.py.
References upload.ErrorExit().
Referenced by upload.SubversionVCS.__init__().
   def __init__(self, options):
     super(SubversionVCS, self).__init__(options)
     if self.options.revision:
       match = re.match(r"(\d+)(:(\d+))?", self.options.revision)
       if not match:
         ErrorExit("Invalid Subversion revision %s." % self.options.revision)
       self.rev_start = match.group(1)
       self.rev_end = match.group(3)
     else:
       self.rev_start = self.rev_end = None
     # Cache output from "svn list -r REVNO dirname".
     # Keys: dirname, Values: 2-tuple (ouput for start rev and end rev).
     self.svnls_cache = {}
     # SVN base URL is required to fetch files deleted in an older revision.
     # Result is cached to not guess it over and over again in GetBaseFile().
     required = self.options.download_base or self.options.revision is not None
     self.svn_base = self._GuessBase(required)
def upload.SubversionVCS.__init__ (self, options)
Definition at line 724 of file upload.py.
References upload.SubversionVCS.__init__(), upload.SubversionVCS._GuessBase(), upload.ErrorExit(), upload.SubversionVCS.rev_end, upload.SubversionVCS.rev_start, upload.SubversionVCS.svn_base, and upload.SubversionVCS.svnls_cache.
   def __init__(self, options):
     super(SubversionVCS, self).__init__(options)
     if self.options.revision:
       match = re.match(r"(\d+)(:(\d+))?", self.options.revision)
       if not match:
         ErrorExit("Invalid Subversion revision %s." % self.options.revision)
       self.rev_start = match.group(1)
       self.rev_end = match.group(3)
     else:
       self.rev_start = self.rev_end = None
     # Cache output from "svn list -r REVNO dirname".
     # Keys: dirname, Values: 2-tuple (ouput for start rev and end rev).
     self.svnls_cache = {}
     # SVN base URL is required to fetch files deleted in an older revision.
     # Result is cached to not guess it over and over again in GetBaseFile().
     required = self.options.download_base or self.options.revision is not None
     self.svn_base = self._GuessBase(required)
def upload.SubversionVCS.__init__ (self, options)
Definition at line 724 of file upload.py.
References upload.SubversionVCS.__init__(), upload.SubversionVCS._GuessBase(), upload.ErrorExit(), upload.SubversionVCS.rev_end, upload.SubversionVCS.rev_start, upload.SubversionVCS.svn_base, and upload.SubversionVCS.svnls_cache.
   def __init__(self, options):
     super(SubversionVCS, self).__init__(options)
     if self.options.revision:
       match = re.match(r"(\d+)(:(\d+))?", self.options.revision)
       if not match:
         ErrorExit("Invalid Subversion revision %s." % self.options.revision)
       self.rev_start = match.group(1)
       self.rev_end = match.group(3)
     else:
       self.rev_start = self.rev_end = None
     # Cache output from "svn list -r REVNO dirname".
     # Keys: dirname, Values: 2-tuple (ouput for start rev and end rev).
     self.svnls_cache = {}
     # SVN base URL is required to fetch files deleted in an older revision.
     # Result is cached to not guess it over and over again in GetBaseFile().
     required = self.options.download_base or self.options.revision is not None
     self.svn_base = self._GuessBase(required)
def upload.SubversionVCS.__init__ (self, options)
Definition at line 724 of file upload.py.
References upload.SubversionVCS.__init__(), upload.SubversionVCS._GuessBase(), upload.ErrorExit(), upload.SubversionVCS.rev_end, upload.SubversionVCS.rev_start, upload.SubversionVCS.svn_base, and upload.SubversionVCS.svnls_cache.
   def __init__(self, options):
     super(SubversionVCS, self).__init__(options)
     if self.options.revision:
       match = re.match(r"(\d+)(:(\d+))?", self.options.revision)
       if not match:
         ErrorExit("Invalid Subversion revision %s." % self.options.revision)
       self.rev_start = match.group(1)
       self.rev_end = match.group(3)
     else:
       self.rev_start = self.rev_end = None
     # Cache output from "svn list -r REVNO dirname".
     # Keys: dirname, Values: 2-tuple (ouput for start rev and end rev).
     self.svnls_cache = {}
     # SVN base URL is required to fetch files deleted in an older revision.
     # Result is cached to not guess it over and over again in GetBaseFile().
     required = self.options.download_base or self.options.revision is not None
     self.svn_base = self._GuessBase(required)
def upload.SubversionVCS.__init__ (self, options)
Definition at line 724 of file upload.py.
References upload.SubversionVCS.__init__(), upload.SubversionVCS._GuessBase(), upload.ErrorExit(), upload.SubversionVCS.rev_end, upload.SubversionVCS.rev_start, upload.SubversionVCS.svn_base, and upload.SubversionVCS.svnls_cache.
   def __init__(self, options):
     super(SubversionVCS, self).__init__(options)
     if self.options.revision:
       match = re.match(r"(\d+)(:(\d+))?", self.options.revision)
       if not match:
         ErrorExit("Invalid Subversion revision %s." % self.options.revision)
       self.rev_start = match.group(1)
       self.rev_end = match.group(3)
     else:
       self.rev_start = self.rev_end = None
     # Cache output from "svn list -r REVNO dirname".
     # Keys: dirname, Values: 2-tuple (ouput for start rev and end rev).
     self.svnls_cache = {}
     # SVN base URL is required to fetch files deleted in an older revision.
     # Result is cached to not guess it over and over again in GetBaseFile().
     required = self.options.download_base or self.options.revision is not None
     self.svn_base = self._GuessBase(required)
def upload.SubversionVCS.__init__ (self, options)
Definition at line 724 of file upload.py.
References upload.SubversionVCS.__init__(), upload.SubversionVCS._GuessBase(), upload.ErrorExit(), upload.SubversionVCS.rev_end, upload.SubversionVCS.rev_start, upload.SubversionVCS.svn_base, and upload.SubversionVCS.svnls_cache.
   def __init__(self, options):
     super(SubversionVCS, self).__init__(options)
     if self.options.revision:
       match = re.match(r"(\d+)(:(\d+))?", self.options.revision)
       if not match:
         ErrorExit("Invalid Subversion revision %s." % self.options.revision)
       self.rev_start = match.group(1)
       self.rev_end = match.group(3)
     else:
       self.rev_start = self.rev_end = None
     # Cache output from "svn list -r REVNO dirname".
     # Keys: dirname, Values: 2-tuple (ouput for start rev and end rev).
     self.svnls_cache = {}
     # SVN base URL is required to fetch files deleted in an older revision.
     # Result is cached to not guess it over and over again in GetBaseFile().
     required = self.options.download_base or self.options.revision is not None
     self.svn_base = self._GuessBase(required)
Member Function Documentation
def upload.SubversionVCS._CollapseKeywords (self, content, keyword_str) private
Collapses SVN keywords.
Definition at line 805 of file upload.py.
References join.
Referenced by upload.SubversionVCS._CollapseKeywords(), and upload.SubversionVCS.GetBaseFile().
   def _CollapseKeywords(self, content, keyword_str):
     """Collapses SVN keywords."""
     # svn cat translates keywords but svn diff doesn't. As a result of this
     # behavior patching.PatchChunks() fails with a chunk mismatch error.
     # This part was originally written by the Review Board development team
     # who had the same problem (http://reviews.review-board.org/r/276/).
     # Mapping of keywords to known aliases
     svn_keywords = {
       # Standard keywords
       'Date':                ['Date', 'LastChangedDate'],
       'Revision':            ['Revision', 'LastChangedRevision', 'Rev'],
       'Author':              ['Author', 'LastChangedBy'],
       'HeadURL':             ['HeadURL', 'URL'],
       'Id':                  ['Id'],
       # Aliases
       'LastChangedDate':     ['LastChangedDate', 'Date'],
       'LastChangedRevision': ['LastChangedRevision', 'Rev', 'Revision'],
       'LastChangedBy':       ['LastChangedBy', 'Author'],
       'URL':                 ['URL', 'HeadURL'],
     }
     def repl(m):
        if m.group(2):
          return "$%s::%s$" % (m.group(1), " " * len(m.group(3)))
        return "$%s$" % m.group(1)
     keywords = [keyword
                 for name in keyword_str.split(" ")
                 for keyword in svn_keywords.get(name, [])]
     return re.sub(r"\$(%s):(:?)([^\$]+)\$" % '|'.join(keywords), repl, content)
def upload.SubversionVCS._CollapseKeywords (self, content, keyword_str) private
Collapses SVN keywords.
Definition at line 805 of file upload.py.
References upload.SubversionVCS._CollapseKeywords(), and join.
   def _CollapseKeywords(self, content, keyword_str):
     """Collapses SVN keywords."""
     # svn cat translates keywords but svn diff doesn't. As a result of this
     # behavior patching.PatchChunks() fails with a chunk mismatch error.
     # This part was originally written by the Review Board development team
     # who had the same problem (http://reviews.review-board.org/r/276/).
     # Mapping of keywords to known aliases
     svn_keywords = {
       # Standard keywords
       'Date':                ['Date', 'LastChangedDate'],
       'Revision':            ['Revision', 'LastChangedRevision', 'Rev'],
       'Author':              ['Author', 'LastChangedBy'],
       'HeadURL':             ['HeadURL', 'URL'],
       'Id':                  ['Id'],
       # Aliases
       'LastChangedDate':     ['LastChangedDate', 'Date'],
       'LastChangedRevision': ['LastChangedRevision', 'Rev', 'Revision'],
       'LastChangedBy':       ['LastChangedBy', 'Author'],
       'URL':                 ['URL', 'HeadURL'],
     }
     def repl(m):
        if m.group(2):
          return "$%s::%s$" % (m.group(1), " " * len(m.group(3)))
        return "$%s$" % m.group(1)
     keywords = [keyword
                 for name in keyword_str.split(" ")
                 for keyword in svn_keywords.get(name, [])]
     return re.sub(r"\$(%s):(:?)([^\$]+)\$" % '|'.join(keywords), repl, content)
def upload.SubversionVCS._CollapseKeywords (self, content, keyword_str) private
Collapses SVN keywords.
Definition at line 805 of file upload.py.
References upload.SubversionVCS._CollapseKeywords(), and join.
   def _CollapseKeywords(self, content, keyword_str):
     """Collapses SVN keywords."""
     # svn cat translates keywords but svn diff doesn't. As a result of this
     # behavior patching.PatchChunks() fails with a chunk mismatch error.
     # This part was originally written by the Review Board development team
     # who had the same problem (http://reviews.review-board.org/r/276/).
     # Mapping of keywords to known aliases
     svn_keywords = {
       # Standard keywords
       'Date':                ['Date', 'LastChangedDate'],
       'Revision':            ['Revision', 'LastChangedRevision', 'Rev'],
       'Author':              ['Author', 'LastChangedBy'],
       'HeadURL':             ['HeadURL', 'URL'],
       'Id':                  ['Id'],
       # Aliases
       'LastChangedDate':     ['LastChangedDate', 'Date'],
       'LastChangedRevision': ['LastChangedRevision', 'Rev', 'Revision'],
       'LastChangedBy':       ['LastChangedBy', 'Author'],
       'URL':                 ['URL', 'HeadURL'],
     }
     def repl(m):
        if m.group(2):
          return "$%s::%s$" % (m.group(1), " " * len(m.group(3)))
        return "$%s$" % m.group(1)
     keywords = [keyword
                 for name in keyword_str.split(" ")
                 for keyword in svn_keywords.get(name, [])]
     return re.sub(r"\$(%s):(:?)([^\$]+)\$" % '|'.join(keywords), repl, content)
def upload.SubversionVCS._CollapseKeywords (self, content, keyword_str) private
Collapses SVN keywords.
Definition at line 805 of file upload.py.
References upload.SubversionVCS._CollapseKeywords(), and join.
   def _CollapseKeywords(self, content, keyword_str):
     """Collapses SVN keywords."""
     # svn cat translates keywords but svn diff doesn't. As a result of this
     # behavior patching.PatchChunks() fails with a chunk mismatch error.
     # This part was originally written by the Review Board development team
     # who had the same problem (http://reviews.review-board.org/r/276/).
     # Mapping of keywords to known aliases
     svn_keywords = {
       # Standard keywords
       'Date':                ['Date', 'LastChangedDate'],
       'Revision':            ['Revision', 'LastChangedRevision', 'Rev'],
       'Author':              ['Author', 'LastChangedBy'],
       'HeadURL':             ['HeadURL', 'URL'],
       'Id':                  ['Id'],
       # Aliases
       'LastChangedDate':     ['LastChangedDate', 'Date'],
       'LastChangedRevision': ['LastChangedRevision', 'Rev', 'Revision'],
       'LastChangedBy':       ['LastChangedBy', 'Author'],
       'URL':                 ['URL', 'HeadURL'],
     }
     def repl(m):
        if m.group(2):
          return "$%s::%s$" % (m.group(1), " " * len(m.group(3)))
        return "$%s$" % m.group(1)
     keywords = [keyword
                 for name in keyword_str.split(" ")
                 for keyword in svn_keywords.get(name, [])]
     return re.sub(r"\$(%s):(:?)([^\$]+)\$" % '|'.join(keywords), repl, content)
def upload.SubversionVCS._CollapseKeywords (self, content, keyword_str) private
Collapses SVN keywords.
Definition at line 805 of file upload.py.
References upload.SubversionVCS._CollapseKeywords(), and join.
   def _CollapseKeywords(self, content, keyword_str):
     """Collapses SVN keywords."""
     # svn cat translates keywords but svn diff doesn't. As a result of this
     # behavior patching.PatchChunks() fails with a chunk mismatch error.
     # This part was originally written by the Review Board development team
     # who had the same problem (http://reviews.review-board.org/r/276/).
     # Mapping of keywords to known aliases
     svn_keywords = {
       # Standard keywords
       'Date':                ['Date', 'LastChangedDate'],
       'Revision':            ['Revision', 'LastChangedRevision', 'Rev'],
       'Author':              ['Author', 'LastChangedBy'],
       'HeadURL':             ['HeadURL', 'URL'],
       'Id':                  ['Id'],
       # Aliases
       'LastChangedDate':     ['LastChangedDate', 'Date'],
       'LastChangedRevision': ['LastChangedRevision', 'Rev', 'Revision'],
       'LastChangedBy':       ['LastChangedBy', 'Author'],
       'URL':                 ['URL', 'HeadURL'],
     }
     def repl(m):
        if m.group(2):
          return "$%s::%s$" % (m.group(1), " " * len(m.group(3)))
        return "$%s$" % m.group(1)
     keywords = [keyword
                 for name in keyword_str.split(" ")
                 for keyword in svn_keywords.get(name, [])]
     return re.sub(r"\$(%s):(:?)([^\$]+)\$" % '|'.join(keywords), repl, content)
def upload.SubversionVCS._CollapseKeywords (self, content, keyword_str) private
Collapses SVN keywords.
Definition at line 805 of file upload.py.
References upload.SubversionVCS._CollapseKeywords(), and join.
   def _CollapseKeywords(self, content, keyword_str):
     """Collapses SVN keywords."""
     # svn cat translates keywords but svn diff doesn't. As a result of this
     # behavior patching.PatchChunks() fails with a chunk mismatch error.
     # This part was originally written by the Review Board development team
     # who had the same problem (http://reviews.review-board.org/r/276/).
     # Mapping of keywords to known aliases
     svn_keywords = {
       # Standard keywords
       'Date':                ['Date', 'LastChangedDate'],
       'Revision':            ['Revision', 'LastChangedRevision', 'Rev'],
       'Author':              ['Author', 'LastChangedBy'],
       'HeadURL':             ['HeadURL', 'URL'],
       'Id':                  ['Id'],
       # Aliases
       'LastChangedDate':     ['LastChangedDate', 'Date'],
       'LastChangedRevision': ['LastChangedRevision', 'Rev', 'Revision'],
       'LastChangedBy':       ['LastChangedBy', 'Author'],
       'URL':                 ['URL', 'HeadURL'],
     }
     def repl(m):
        if m.group(2):
          return "$%s::%s$" % (m.group(1), " " * len(m.group(3)))
        return "$%s$" % m.group(1)
     keywords = [keyword
                 for name in keyword_str.split(" ")
                 for keyword in svn_keywords.get(name, [])]
     return re.sub(r"\$(%s):(:?)([^\$]+)\$" % '|'.join(keywords), repl, content)
def upload.SubversionVCS._GuessBase (self, required) private
Returns the SVN base URL.
Args:
  required: If true, exits if the url can't be guessed, otherwise None is
returned.
Definition at line 746 of file upload.py.
References upload.SubversionVCS._GuessBase(), upload.ErrorExit(), and upload.RunShell().
   def _GuessBase(self, required):
     """Returns the SVN base URL.
     Args:
       required: If true, exits if the url can't be guessed, otherwise None is
         returned.
     """
     info = RunShell(["svn", "info"])
     for line in info.splitlines():
       words = line.split()
       if len(words) == 2 and words[0] == "URL:":
         url = words[1]
         scheme, netloc, path, params, query, fragment = urlparse.urlparse(url)
         username, netloc = urllib.splituser(netloc)
         if username:
           logging.info("Removed username from base URL")
         if netloc.endswith("svn.python.org"):
           if netloc == "svn.python.org":
             if path.startswith("/projects/"):
               path = path[9:]
           elif netloc != "pythondev@svn.python.org":
             ErrorExit("Unrecognized Python URL: %s" % url)
           base = "http://svn.python.org/view/*checkout*%s/" % path
           logging.info("Guessed Python base = %s", base)
         elif netloc.endswith("svn.collab.net"):
           if path.startswith("/repos/"):
             path = path[6:]
           base = "http://svn.collab.net/viewvc/*checkout*%s/" % path
           logging.info("Guessed CollabNet base = %s", base)
         elif netloc.endswith(".googlecode.com"):
           path = path + "/"
           base = urlparse.urlunparse(("http", netloc, path, params,
                                       query, fragment))
           logging.info("Guessed Google Code base = %s", base)
         else:
           path = path + "/"
           base = urlparse.urlunparse((scheme, netloc, path, params,
                                       query, fragment))
           logging.info("Guessed base = %s", base)
         return base
     if required:
       ErrorExit("Can't find URL in output from svn info")
     return None
def upload.SubversionVCS._GuessBase (self, required) private
Returns the SVN base URL.
Args:
  required: If true, exits if the url can't be guessed, otherwise None is
returned.
Definition at line 746 of file upload.py.
References upload.SubversionVCS._GuessBase(), upload.ErrorExit(), and upload.RunShell().
   def _GuessBase(self, required):
     """Returns the SVN base URL.
     Args:
       required: If true, exits if the url can't be guessed, otherwise None is
         returned.
     """
     info = RunShell(["svn", "info"])
     for line in info.splitlines():
       words = line.split()
       if len(words) == 2 and words[0] == "URL:":
         url = words[1]
         scheme, netloc, path, params, query, fragment = urlparse.urlparse(url)
         username, netloc = urllib.splituser(netloc)
         if username:
           logging.info("Removed username from base URL")
         if netloc.endswith("svn.python.org"):
           if netloc == "svn.python.org":
             if path.startswith("/projects/"):
               path = path[9:]
           elif netloc != "pythondev@svn.python.org":
             ErrorExit("Unrecognized Python URL: %s" % url)
           base = "http://svn.python.org/view/*checkout*%s/" % path
           logging.info("Guessed Python base = %s", base)
         elif netloc.endswith("svn.collab.net"):
           if path.startswith("/repos/"):
             path = path[6:]
           base = "http://svn.collab.net/viewvc/*checkout*%s/" % path
           logging.info("Guessed CollabNet base = %s", base)
         elif netloc.endswith(".googlecode.com"):
           path = path + "/"
           base = urlparse.urlunparse(("http", netloc, path, params,
                                       query, fragment))
           logging.info("Guessed Google Code base = %s", base)
         else:
           path = path + "/"
           base = urlparse.urlunparse((scheme, netloc, path, params,
                                       query, fragment))
           logging.info("Guessed base = %s", base)
         return base
     if required:
       ErrorExit("Can't find URL in output from svn info")
     return None
def upload.SubversionVCS._GuessBase (self, required) private
Returns the SVN base URL.
Args:
  required: If true, exits if the url can't be guessed, otherwise None is
returned.
Definition at line 746 of file upload.py.
References upload.SubversionVCS._GuessBase(), upload.ErrorExit(), and upload.RunShell().
   def _GuessBase(self, required):
     """Returns the SVN base URL.
     Args:
       required: If true, exits if the url can't be guessed, otherwise None is
         returned.
     """
     info = RunShell(["svn", "info"])
     for line in info.splitlines():
       words = line.split()
       if len(words) == 2 and words[0] == "URL:":
         url = words[1]
         scheme, netloc, path, params, query, fragment = urlparse.urlparse(url)
         username, netloc = urllib.splituser(netloc)
         if username:
           logging.info("Removed username from base URL")
         if netloc.endswith("svn.python.org"):
           if netloc == "svn.python.org":
             if path.startswith("/projects/"):
               path = path[9:]
           elif netloc != "pythondev@svn.python.org":
             ErrorExit("Unrecognized Python URL: %s" % url)
           base = "http://svn.python.org/view/*checkout*%s/" % path
           logging.info("Guessed Python base = %s", base)
         elif netloc.endswith("svn.collab.net"):
           if path.startswith("/repos/"):
             path = path[6:]
           base = "http://svn.collab.net/viewvc/*checkout*%s/" % path
           logging.info("Guessed CollabNet base = %s", base)
         elif netloc.endswith(".googlecode.com"):
           path = path + "/"
           base = urlparse.urlunparse(("http", netloc, path, params,
                                       query, fragment))
           logging.info("Guessed Google Code base = %s", base)
         else:
           path = path + "/"
           base = urlparse.urlunparse((scheme, netloc, path, params,
                                       query, fragment))
           logging.info("Guessed base = %s", base)
         return base
     if required:
       ErrorExit("Can't find URL in output from svn info")
     return None
def upload.SubversionVCS._GuessBase (self, required) private
Returns the SVN base URL.
Args:
  required: If true, exits if the url can't be guessed, otherwise None is
returned.
Definition at line 746 of file upload.py.
References upload.SubversionVCS._GuessBase(), upload.ErrorExit(), and upload.RunShell().
   def _GuessBase(self, required):
     """Returns the SVN base URL.
     Args:
       required: If true, exits if the url can't be guessed, otherwise None is
         returned.
     """
     info = RunShell(["svn", "info"])
     for line in info.splitlines():
       words = line.split()
       if len(words) == 2 and words[0] == "URL:":
         url = words[1]
         scheme, netloc, path, params, query, fragment = urlparse.urlparse(url)
         username, netloc = urllib.splituser(netloc)
         if username:
           logging.info("Removed username from base URL")
         if netloc.endswith("svn.python.org"):
           if netloc == "svn.python.org":
             if path.startswith("/projects/"):
               path = path[9:]
           elif netloc != "pythondev@svn.python.org":
             ErrorExit("Unrecognized Python URL: %s" % url)
           base = "http://svn.python.org/view/*checkout*%s/" % path
           logging.info("Guessed Python base = %s", base)
         elif netloc.endswith("svn.collab.net"):
           if path.startswith("/repos/"):
             path = path[6:]
           base = "http://svn.collab.net/viewvc/*checkout*%s/" % path
           logging.info("Guessed CollabNet base = %s", base)
         elif netloc.endswith(".googlecode.com"):
           path = path + "/"
           base = urlparse.urlunparse(("http", netloc, path, params,
                                       query, fragment))
           logging.info("Guessed Google Code base = %s", base)
         else:
           path = path + "/"
           base = urlparse.urlunparse((scheme, netloc, path, params,
                                       query, fragment))
           logging.info("Guessed base = %s", base)
         return base
     if required:
       ErrorExit("Can't find URL in output from svn info")
     return None
def upload.SubversionVCS._GuessBase (self, required) private
Returns the SVN base URL.
Args:
  required: If true, exits if the url can't be guessed, otherwise None is
returned.
Definition at line 746 of file upload.py.
References upload.ErrorExit(), and upload.RunShell().
Referenced by upload.SubversionVCS.__init__(), and upload.SubversionVCS._GuessBase().
   def _GuessBase(self, required):
     """Returns the SVN base URL.
     Args:
       required: If true, exits if the url can't be guessed, otherwise None is
         returned.
     """
     info = RunShell(["svn", "info"])
     for line in info.splitlines():
       words = line.split()
       if len(words) == 2 and words[0] == "URL:":
         url = words[1]
         scheme, netloc, path, params, query, fragment = urlparse.urlparse(url)
         username, netloc = urllib.splituser(netloc)
         if username:
           logging.info("Removed username from base URL")
         if netloc.endswith("svn.python.org"):
           if netloc == "svn.python.org":
             if path.startswith("/projects/"):
               path = path[9:]
           elif netloc != "pythondev@svn.python.org":
             ErrorExit("Unrecognized Python URL: %s" % url)
           base = "http://svn.python.org/view/*checkout*%s/" % path
           logging.info("Guessed Python base = %s", base)
         elif netloc.endswith("svn.collab.net"):
           if path.startswith("/repos/"):
             path = path[6:]
           base = "http://svn.collab.net/viewvc/*checkout*%s/" % path
           logging.info("Guessed CollabNet base = %s", base)
         elif netloc.endswith(".googlecode.com"):
           path = path + "/"
           base = urlparse.urlunparse(("http", netloc, path, params,
                                       query, fragment))
           logging.info("Guessed Google Code base = %s", base)
         else:
           path = path + "/"
           base = urlparse.urlunparse((scheme, netloc, path, params,
                                       query, fragment))
           logging.info("Guessed base = %s", base)
         return base
     if required:
       ErrorExit("Can't find URL in output from svn info")
     return None
def upload.SubversionVCS._GuessBase (self, required) private
Returns the SVN base URL.
Args:
  required: If true, exits if the url can't be guessed, otherwise None is
returned.
Definition at line 746 of file upload.py.
References upload.SubversionVCS._GuessBase(), upload.ErrorExit(), and upload.RunShell().
   def _GuessBase(self, required):
     """Returns the SVN base URL.
     Args:
       required: If true, exits if the url can't be guessed, otherwise None is
         returned.
     """
     info = RunShell(["svn", "info"])
     for line in info.splitlines():
       words = line.split()
       if len(words) == 2 and words[0] == "URL:":
         url = words[1]
         scheme, netloc, path, params, query, fragment = urlparse.urlparse(url)
         username, netloc = urllib.splituser(netloc)
         if username:
           logging.info("Removed username from base URL")
         if netloc.endswith("svn.python.org"):
           if netloc == "svn.python.org":
             if path.startswith("/projects/"):
               path = path[9:]
           elif netloc != "pythondev@svn.python.org":
             ErrorExit("Unrecognized Python URL: %s" % url)
           base = "http://svn.python.org/view/*checkout*%s/" % path
           logging.info("Guessed Python base = %s", base)
         elif netloc.endswith("svn.collab.net"):
           if path.startswith("/repos/"):
             path = path[6:]
           base = "http://svn.collab.net/viewvc/*checkout*%s/" % path
           logging.info("Guessed CollabNet base = %s", base)
         elif netloc.endswith(".googlecode.com"):
           path = path + "/"
           base = urlparse.urlunparse(("http", netloc, path, params,
                                       query, fragment))
           logging.info("Guessed Google Code base = %s", base)
         else:
           path = path + "/"
           base = urlparse.urlunparse((scheme, netloc, path, params,
                                       query, fragment))
           logging.info("Guessed base = %s", base)
         return base
     if required:
       ErrorExit("Can't find URL in output from svn info")
     return None
def upload.SubversionVCS.GenerateDiff (self, args)
Definition at line 790 of file upload.py.
References upload.ErrorExit(), upload.SubversionVCS.GenerateDiff(), and upload.RunShell().
   def GenerateDiff(self, args):
     cmd = ["svn", "diff"]
     if self.options.revision:
       cmd += ["-r", self.options.revision]
     cmd.extend(args)
     data = RunShell(cmd)
     count = 0
     for line in data.splitlines():
       if line.startswith("Index:") or line.startswith("Property changes on:"):
         count += 1
         logging.info(line)
     if not count:
       ErrorExit("No valid patches found in output from svn diff")
     return data
def upload.SubversionVCS.GenerateDiff (self, args)
Definition at line 790 of file upload.py.
References upload.ErrorExit(), upload.SubversionVCS.GenerateDiff(), and upload.RunShell().
   def GenerateDiff(self, args):
     cmd = ["svn", "diff"]
     if self.options.revision:
       cmd += ["-r", self.options.revision]
     cmd.extend(args)
     data = RunShell(cmd)
     count = 0
     for line in data.splitlines():
       if line.startswith("Index:") or line.startswith("Property changes on:"):
         count += 1
         logging.info(line)
     if not count:
       ErrorExit("No valid patches found in output from svn diff")
     return data
def upload.SubversionVCS.GenerateDiff (self, args)
Definition at line 790 of file upload.py.
References upload.ErrorExit(), upload.SubversionVCS.GenerateDiff(), and upload.RunShell().
   def GenerateDiff(self, args):
     cmd = ["svn", "diff"]
     if self.options.revision:
       cmd += ["-r", self.options.revision]
     cmd.extend(args)
     data = RunShell(cmd)
     count = 0
     for line in data.splitlines():
       if line.startswith("Index:") or line.startswith("Property changes on:"):
         count += 1
         logging.info(line)
     if not count:
       ErrorExit("No valid patches found in output from svn diff")
     return data
def upload.SubversionVCS.GenerateDiff (self, args)
Definition at line 790 of file upload.py.
References upload.ErrorExit(), upload.SubversionVCS.GenerateDiff(), and upload.RunShell().
   def GenerateDiff(self, args):
     cmd = ["svn", "diff"]
     if self.options.revision:
       cmd += ["-r", self.options.revision]
     cmd.extend(args)
     data = RunShell(cmd)
     count = 0
     for line in data.splitlines():
       if line.startswith("Index:") or line.startswith("Property changes on:"):
         count += 1
         logging.info(line)
     if not count:
       ErrorExit("No valid patches found in output from svn diff")
     return data
def upload.SubversionVCS.GenerateDiff (self, args)
Definition at line 790 of file upload.py.
References upload.ErrorExit(), and upload.RunShell().
Referenced by upload.SubversionVCS.GenerateDiff().
   def GenerateDiff(self, args):
     cmd = ["svn", "diff"]
     if self.options.revision:
       cmd += ["-r", self.options.revision]
     cmd.extend(args)
     data = RunShell(cmd)
     count = 0
     for line in data.splitlines():
       if line.startswith("Index:") or line.startswith("Property changes on:"):
         count += 1
         logging.info(line)
     if not count:
       ErrorExit("No valid patches found in output from svn diff")
     return data
def upload.SubversionVCS.GenerateDiff (self, args)
Definition at line 790 of file upload.py.
References upload.ErrorExit(), upload.SubversionVCS.GenerateDiff(), and upload.RunShell().
   def GenerateDiff(self, args):
     cmd = ["svn", "diff"]
     if self.options.revision:
       cmd += ["-r", self.options.revision]
     cmd.extend(args)
     data = RunShell(cmd)
     count = 0
     for line in data.splitlines():
       if line.startswith("Index:") or line.startswith("Property changes on:"):
         count += 1
         logging.info(line)
     if not count:
       ErrorExit("No valid patches found in output from svn diff")
     return data
def upload.SubversionVCS.GetBaseFile (self, filename)
Definition at line 898 of file upload.py.
References upload.SubversionVCS._CollapseKeywords(), upload.SubversionVCS.GetBaseFile(), upload.SubversionVCS.GetStatus(), upload.VersionControlSystem.IsImage(), upload.SubversionVCS.ReadFile(), upload.SubversionVCS.rev_end, upload.SubversionVCS.rev_start, upload.RunShell(), upload.RunShellWithReturnCode(), upload.StatusUpdate(), and upload.SubversionVCS.svn_base.
   def GetBaseFile(self, filename):
     status = self.GetStatus(filename)
     base_content = None
     new_content = None
     # If a file is copied its status will be "A  +", which signifies
     # "addition-with-history".  See "svn st" for more information.  We need to
     # upload the original file or else diff parsing will fail if the file was
     # edited.
     if status[0] == "A" and status[3] != "+":
       # We'll need to upload the new content if we're adding a binary file
       # since diff's output won't contain it.
       mimetype = RunShell(["svn", "propget", "svn:mime-type", filename],
                           silent_ok=True)
       base_content = ""
       is_binary = mimetype and not mimetype.startswith("text/")
       if is_binary and self.IsImage(filename):
         new_content = self.ReadFile(filename)
     elif (status[0] in ("M", "D", "R") or
           (status[0] == "A" and status[3] == "+") or  # Copied file.
           (status[0] == " " and status[1] == "M")):  # Property change.
       args = []
       if self.options.revision:
         url = "%s/%s@%s" % (self.svn_base, filename, self.rev_start)
       else:
         # Don't change filename, it's needed later.
         url = filename
         args += ["-r", "BASE"]
       cmd = ["svn"] + args + ["propget", "svn:mime-type", url]
       mimetype, returncode = RunShellWithReturnCode(cmd)
       if returncode:
         # File does not exist in the requested revision.
         # Reset mimetype, it contains an error message.
         mimetype = ""
       get_base = False
       is_binary = mimetype and not mimetype.startswith("text/")
       if status[0] == " ":
         # Empty base content just to force an upload.
         base_content = ""
       elif is_binary:
         if self.IsImage(filename):
           get_base = True
           if status[0] == "M":
             if not self.rev_end:
               new_content = self.ReadFile(filename)
             else:
               url = "%s/%s@%s" % (self.svn_base, filename, self.rev_end)
               new_content = RunShell(["svn", "cat", url],
                                      universal_newlines=True, silent_ok=True)
         else:
           base_content = ""
       else:
         get_base = True
       if get_base:
         if is_binary:
           universal_newlines = False
         else:
           universal_newlines = True
         if self.rev_start:
           # "svn cat -r REV delete_file.txt" doesn't work. cat requires
           # the full URL with "@REV" appended instead of using "-r" option.
           url = "%s/%s@%s" % (self.svn_base, filename, self.rev_start)
           base_content = RunShell(["svn", "cat", url],
                                   universal_newlines=universal_newlines,
                                   silent_ok=True)
         else:
           base_content = RunShell(["svn", "cat", filename],
                                   universal_newlines=universal_newlines,
                                   silent_ok=True)
         if not is_binary:
           args = []
           if self.rev_start:
             url = "%s/%s@%s" % (self.svn_base, filename, self.rev_start)
           else:
             url = filename
             args += ["-r", "BASE"]
           cmd = ["svn"] + args + ["propget", "svn:keywords", url]
           keywords, returncode = RunShellWithReturnCode(cmd)
           if keywords and not returncode:
             base_content = self._CollapseKeywords(base_content, keywords)
     else:
       StatusUpdate("svn status returned unexpected output: %s" % status)
       sys.exit(1)
     return base_content, new_content, is_binary, status[0:5]
def upload.SubversionVCS.GetBaseFile (self, filename)
Definition at line 898 of file upload.py.
References upload.SubversionVCS._CollapseKeywords(), upload.SubversionVCS.GetBaseFile(), upload.SubversionVCS.GetStatus(), upload.VersionControlSystem.IsImage(), upload.SubversionVCS.ReadFile(), upload.SubversionVCS.rev_end, upload.SubversionVCS.rev_start, upload.RunShell(), upload.RunShellWithReturnCode(), upload.StatusUpdate(), and upload.SubversionVCS.svn_base.
   def GetBaseFile(self, filename):
     status = self.GetStatus(filename)
     base_content = None
     new_content = None
     # If a file is copied its status will be "A  +", which signifies
     # "addition-with-history".  See "svn st" for more information.  We need to
     # upload the original file or else diff parsing will fail if the file was
     # edited.
     if status[0] == "A" and status[3] != "+":
       # We'll need to upload the new content if we're adding a binary file
       # since diff's output won't contain it.
       mimetype = RunShell(["svn", "propget", "svn:mime-type", filename],
                           silent_ok=True)
       base_content = ""
       is_binary = mimetype and not mimetype.startswith("text/")
       if is_binary and self.IsImage(filename):
         new_content = self.ReadFile(filename)
     elif (status[0] in ("M", "D", "R") or
           (status[0] == "A" and status[3] == "+") or  # Copied file.
           (status[0] == " " and status[1] == "M")):  # Property change.
       args = []
       if self.options.revision:
         url = "%s/%s@%s" % (self.svn_base, filename, self.rev_start)
       else:
         # Don't change filename, it's needed later.
         url = filename
         args += ["-r", "BASE"]
       cmd = ["svn"] + args + ["propget", "svn:mime-type", url]
       mimetype, returncode = RunShellWithReturnCode(cmd)
       if returncode:
         # File does not exist in the requested revision.
         # Reset mimetype, it contains an error message.
         mimetype = ""
       get_base = False
       is_binary = mimetype and not mimetype.startswith("text/")
       if status[0] == " ":
         # Empty base content just to force an upload.
         base_content = ""
       elif is_binary:
         if self.IsImage(filename):
           get_base = True
           if status[0] == "M":
             if not self.rev_end:
               new_content = self.ReadFile(filename)
             else:
               url = "%s/%s@%s" % (self.svn_base, filename, self.rev_end)
               new_content = RunShell(["svn", "cat", url],
                                      universal_newlines=True, silent_ok=True)
         else:
           base_content = ""
       else:
         get_base = True
       if get_base:
         if is_binary:
           universal_newlines = False
         else:
           universal_newlines = True
         if self.rev_start:
           # "svn cat -r REV delete_file.txt" doesn't work. cat requires
           # the full URL with "@REV" appended instead of using "-r" option.
           url = "%s/%s@%s" % (self.svn_base, filename, self.rev_start)
           base_content = RunShell(["svn", "cat", url],
                                   universal_newlines=universal_newlines,
                                   silent_ok=True)
         else:
           base_content = RunShell(["svn", "cat", filename],
                                   universal_newlines=universal_newlines,
                                   silent_ok=True)
         if not is_binary:
           args = []
           if self.rev_start:
             url = "%s/%s@%s" % (self.svn_base, filename, self.rev_start)
           else:
             url = filename
             args += ["-r", "BASE"]
           cmd = ["svn"] + args + ["propget", "svn:keywords", url]
           keywords, returncode = RunShellWithReturnCode(cmd)
           if keywords and not returncode:
             base_content = self._CollapseKeywords(base_content, keywords)
     else:
       StatusUpdate("svn status returned unexpected output: %s" % status)
       sys.exit(1)
     return base_content, new_content, is_binary, status[0:5]
def upload.SubversionVCS.GetBaseFile (self, filename)
Definition at line 898 of file upload.py.
References upload.SubversionVCS._CollapseKeywords(), upload.SubversionVCS.GetStatus(), upload.VersionControlSystem.IsImage(), upload.SubversionVCS.ReadFile(), upload.SubversionVCS.rev_end, upload.SubversionVCS.rev_start, upload.RunShell(), upload.RunShellWithReturnCode(), upload.StatusUpdate(), and upload.SubversionVCS.svn_base.
Referenced by upload.SubversionVCS.GetBaseFile().
   def GetBaseFile(self, filename):
     status = self.GetStatus(filename)
     base_content = None
     new_content = None
     # If a file is copied its status will be "A  +", which signifies
     # "addition-with-history".  See "svn st" for more information.  We need to
     # upload the original file or else diff parsing will fail if the file was
     # edited.
     if status[0] == "A" and status[3] != "+":
       # We'll need to upload the new content if we're adding a binary file
       # since diff's output won't contain it.
       mimetype = RunShell(["svn", "propget", "svn:mime-type", filename],
                           silent_ok=True)
       base_content = ""
       is_binary = mimetype and not mimetype.startswith("text/")
       if is_binary and self.IsImage(filename):
         new_content = self.ReadFile(filename)
     elif (status[0] in ("M", "D", "R") or
           (status[0] == "A" and status[3] == "+") or  # Copied file.
           (status[0] == " " and status[1] == "M")):  # Property change.
       args = []
       if self.options.revision:
         url = "%s/%s@%s" % (self.svn_base, filename, self.rev_start)
       else:
         # Don't change filename, it's needed later.
         url = filename
         args += ["-r", "BASE"]
       cmd = ["svn"] + args + ["propget", "svn:mime-type", url]
       mimetype, returncode = RunShellWithReturnCode(cmd)
       if returncode:
         # File does not exist in the requested revision.
         # Reset mimetype, it contains an error message.
         mimetype = ""
       get_base = False
       is_binary = mimetype and not mimetype.startswith("text/")
       if status[0] == " ":
         # Empty base content just to force an upload.
         base_content = ""
       elif is_binary:
         if self.IsImage(filename):
           get_base = True
           if status[0] == "M":
             if not self.rev_end:
               new_content = self.ReadFile(filename)
             else:
               url = "%s/%s@%s" % (self.svn_base, filename, self.rev_end)
               new_content = RunShell(["svn", "cat", url],
                                      universal_newlines=True, silent_ok=True)
         else:
           base_content = ""
       else:
         get_base = True
       if get_base:
         if is_binary:
           universal_newlines = False
         else:
           universal_newlines = True
         if self.rev_start:
           # "svn cat -r REV delete_file.txt" doesn't work. cat requires
           # the full URL with "@REV" appended instead of using "-r" option.
           url = "%s/%s@%s" % (self.svn_base, filename, self.rev_start)
           base_content = RunShell(["svn", "cat", url],
                                   universal_newlines=universal_newlines,
                                   silent_ok=True)
         else:
           base_content = RunShell(["svn", "cat", filename],
                                   universal_newlines=universal_newlines,
                                   silent_ok=True)
         if not is_binary:
           args = []
           if self.rev_start:
             url = "%s/%s@%s" % (self.svn_base, filename, self.rev_start)
           else:
             url = filename
             args += ["-r", "BASE"]
           cmd = ["svn"] + args + ["propget", "svn:keywords", url]
           keywords, returncode = RunShellWithReturnCode(cmd)
           if keywords and not returncode:
             base_content = self._CollapseKeywords(base_content, keywords)
     else:
       StatusUpdate("svn status returned unexpected output: %s" % status)
       sys.exit(1)
     return base_content, new_content, is_binary, status[0:5]
def upload.SubversionVCS.GetBaseFile (self, filename)
Definition at line 898 of file upload.py.
References upload.SubversionVCS._CollapseKeywords(), upload.SubversionVCS.GetBaseFile(), upload.SubversionVCS.GetStatus(), upload.VersionControlSystem.IsImage(), upload.SubversionVCS.ReadFile(), upload.SubversionVCS.rev_end, upload.SubversionVCS.rev_start, upload.RunShell(), upload.RunShellWithReturnCode(), upload.StatusUpdate(), and upload.SubversionVCS.svn_base.
   def GetBaseFile(self, filename):
     status = self.GetStatus(filename)
     base_content = None
     new_content = None
     # If a file is copied its status will be "A  +", which signifies
     # "addition-with-history".  See "svn st" for more information.  We need to
     # upload the original file or else diff parsing will fail if the file was
     # edited.
     if status[0] == "A" and status[3] != "+":
       # We'll need to upload the new content if we're adding a binary file
       # since diff's output won't contain it.
       mimetype = RunShell(["svn", "propget", "svn:mime-type", filename],
                           silent_ok=True)
       base_content = ""
       is_binary = mimetype and not mimetype.startswith("text/")
       if is_binary and self.IsImage(filename):
         new_content = self.ReadFile(filename)
     elif (status[0] in ("M", "D", "R") or
           (status[0] == "A" and status[3] == "+") or  # Copied file.
           (status[0] == " " and status[1] == "M")):  # Property change.
       args = []
       if self.options.revision:
         url = "%s/%s@%s" % (self.svn_base, filename, self.rev_start)
       else:
         # Don't change filename, it's needed later.
         url = filename
         args += ["-r", "BASE"]
       cmd = ["svn"] + args + ["propget", "svn:mime-type", url]
       mimetype, returncode = RunShellWithReturnCode(cmd)
       if returncode:
         # File does not exist in the requested revision.
         # Reset mimetype, it contains an error message.
         mimetype = ""
       get_base = False
       is_binary = mimetype and not mimetype.startswith("text/")
       if status[0] == " ":
         # Empty base content just to force an upload.
         base_content = ""
       elif is_binary:
         if self.IsImage(filename):
           get_base = True
           if status[0] == "M":
             if not self.rev_end:
               new_content = self.ReadFile(filename)
             else:
               url = "%s/%s@%s" % (self.svn_base, filename, self.rev_end)
               new_content = RunShell(["svn", "cat", url],
                                      universal_newlines=True, silent_ok=True)
         else:
           base_content = ""
       else:
         get_base = True
       if get_base:
         if is_binary:
           universal_newlines = False
         else:
           universal_newlines = True
         if self.rev_start:
           # "svn cat -r REV delete_file.txt" doesn't work. cat requires
           # the full URL with "@REV" appended instead of using "-r" option.
           url = "%s/%s@%s" % (self.svn_base, filename, self.rev_start)
           base_content = RunShell(["svn", "cat", url],
                                   universal_newlines=universal_newlines,
                                   silent_ok=True)
         else:
           base_content = RunShell(["svn", "cat", filename],
                                   universal_newlines=universal_newlines,
                                   silent_ok=True)
         if not is_binary:
           args = []
           if self.rev_start:
             url = "%s/%s@%s" % (self.svn_base, filename, self.rev_start)
           else:
             url = filename
             args += ["-r", "BASE"]
           cmd = ["svn"] + args + ["propget", "svn:keywords", url]
           keywords, returncode = RunShellWithReturnCode(cmd)
           if keywords and not returncode:
             base_content = self._CollapseKeywords(base_content, keywords)
     else:
       StatusUpdate("svn status returned unexpected output: %s" % status)
       sys.exit(1)
     return base_content, new_content, is_binary, status[0:5]
def upload.SubversionVCS.GetBaseFile (self, filename)
Definition at line 898 of file upload.py.
References upload.SubversionVCS._CollapseKeywords(), upload.SubversionVCS.GetBaseFile(), upload.SubversionVCS.GetStatus(), upload.VersionControlSystem.IsImage(), upload.SubversionVCS.ReadFile(), upload.SubversionVCS.rev_end, upload.SubversionVCS.rev_start, upload.RunShell(), upload.RunShellWithReturnCode(), upload.StatusUpdate(), and upload.SubversionVCS.svn_base.
   def GetBaseFile(self, filename):
     status = self.GetStatus(filename)
     base_content = None
     new_content = None
     # If a file is copied its status will be "A  +", which signifies
     # "addition-with-history".  See "svn st" for more information.  We need to
     # upload the original file or else diff parsing will fail if the file was
     # edited.
     if status[0] == "A" and status[3] != "+":
       # We'll need to upload the new content if we're adding a binary file
       # since diff's output won't contain it.
       mimetype = RunShell(["svn", "propget", "svn:mime-type", filename],
                           silent_ok=True)
       base_content = ""
       is_binary = mimetype and not mimetype.startswith("text/")
       if is_binary and self.IsImage(filename):
         new_content = self.ReadFile(filename)
     elif (status[0] in ("M", "D", "R") or
           (status[0] == "A" and status[3] == "+") or  # Copied file.
           (status[0] == " " and status[1] == "M")):  # Property change.
       args = []
       if self.options.revision:
         url = "%s/%s@%s" % (self.svn_base, filename, self.rev_start)
       else:
         # Don't change filename, it's needed later.
         url = filename
         args += ["-r", "BASE"]
       cmd = ["svn"] + args + ["propget", "svn:mime-type", url]
       mimetype, returncode = RunShellWithReturnCode(cmd)
       if returncode:
         # File does not exist in the requested revision.
         # Reset mimetype, it contains an error message.
         mimetype = ""
       get_base = False
       is_binary = mimetype and not mimetype.startswith("text/")
       if status[0] == " ":
         # Empty base content just to force an upload.
         base_content = ""
       elif is_binary:
         if self.IsImage(filename):
           get_base = True
           if status[0] == "M":
             if not self.rev_end:
               new_content = self.ReadFile(filename)
             else:
               url = "%s/%s@%s" % (self.svn_base, filename, self.rev_end)
               new_content = RunShell(["svn", "cat", url],
                                      universal_newlines=True, silent_ok=True)
         else:
           base_content = ""
       else:
         get_base = True
       if get_base:
         if is_binary:
           universal_newlines = False
         else:
           universal_newlines = True
         if self.rev_start:
           # "svn cat -r REV delete_file.txt" doesn't work. cat requires
           # the full URL with "@REV" appended instead of using "-r" option.
           url = "%s/%s@%s" % (self.svn_base, filename, self.rev_start)
           base_content = RunShell(["svn", "cat", url],
                                   universal_newlines=universal_newlines,
                                   silent_ok=True)
         else:
           base_content = RunShell(["svn", "cat", filename],
                                   universal_newlines=universal_newlines,
                                   silent_ok=True)
         if not is_binary:
           args = []
           if self.rev_start:
             url = "%s/%s@%s" % (self.svn_base, filename, self.rev_start)
           else:
             url = filename
             args += ["-r", "BASE"]
           cmd = ["svn"] + args + ["propget", "svn:keywords", url]
           keywords, returncode = RunShellWithReturnCode(cmd)
           if keywords and not returncode:
             base_content = self._CollapseKeywords(base_content, keywords)
     else:
       StatusUpdate("svn status returned unexpected output: %s" % status)
       sys.exit(1)
     return base_content, new_content, is_binary, status[0:5]
def upload.SubversionVCS.GetBaseFile (self, filename)
Definition at line 898 of file upload.py.
References upload.SubversionVCS._CollapseKeywords(), upload.SubversionVCS.GetBaseFile(), upload.SubversionVCS.GetStatus(), upload.VersionControlSystem.IsImage(), upload.SubversionVCS.ReadFile(), upload.SubversionVCS.rev_end, upload.SubversionVCS.rev_start, upload.RunShell(), upload.RunShellWithReturnCode(), upload.StatusUpdate(), and upload.SubversionVCS.svn_base.
   def GetBaseFile(self, filename):
     status = self.GetStatus(filename)
     base_content = None
     new_content = None
     # If a file is copied its status will be "A  +", which signifies
     # "addition-with-history".  See "svn st" for more information.  We need to
     # upload the original file or else diff parsing will fail if the file was
     # edited.
     if status[0] == "A" and status[3] != "+":
       # We'll need to upload the new content if we're adding a binary file
       # since diff's output won't contain it.
       mimetype = RunShell(["svn", "propget", "svn:mime-type", filename],
                           silent_ok=True)
       base_content = ""
       is_binary = mimetype and not mimetype.startswith("text/")
       if is_binary and self.IsImage(filename):
         new_content = self.ReadFile(filename)
     elif (status[0] in ("M", "D", "R") or
           (status[0] == "A" and status[3] == "+") or  # Copied file.
           (status[0] == " " and status[1] == "M")):  # Property change.
       args = []
       if self.options.revision:
         url = "%s/%s@%s" % (self.svn_base, filename, self.rev_start)
       else:
         # Don't change filename, it's needed later.
         url = filename
         args += ["-r", "BASE"]
       cmd = ["svn"] + args + ["propget", "svn:mime-type", url]
       mimetype, returncode = RunShellWithReturnCode(cmd)
       if returncode:
         # File does not exist in the requested revision.
         # Reset mimetype, it contains an error message.
         mimetype = ""
       get_base = False
       is_binary = mimetype and not mimetype.startswith("text/")
       if status[0] == " ":
         # Empty base content just to force an upload.
         base_content = ""
       elif is_binary:
         if self.IsImage(filename):
           get_base = True
           if status[0] == "M":
             if not self.rev_end:
               new_content = self.ReadFile(filename)
             else:
               url = "%s/%s@%s" % (self.svn_base, filename, self.rev_end)
               new_content = RunShell(["svn", "cat", url],
                                      universal_newlines=True, silent_ok=True)
         else:
           base_content = ""
       else:
         get_base = True
       if get_base:
         if is_binary:
           universal_newlines = False
         else:
           universal_newlines = True
         if self.rev_start:
           # "svn cat -r REV delete_file.txt" doesn't work. cat requires
           # the full URL with "@REV" appended instead of using "-r" option.
           url = "%s/%s@%s" % (self.svn_base, filename, self.rev_start)
           base_content = RunShell(["svn", "cat", url],
                                   universal_newlines=universal_newlines,
                                   silent_ok=True)
         else:
           base_content = RunShell(["svn", "cat", filename],
                                   universal_newlines=universal_newlines,
                                   silent_ok=True)
         if not is_binary:
           args = []
           if self.rev_start:
             url = "%s/%s@%s" % (self.svn_base, filename, self.rev_start)
           else:
             url = filename
             args += ["-r", "BASE"]
           cmd = ["svn"] + args + ["propget", "svn:keywords", url]
           keywords, returncode = RunShellWithReturnCode(cmd)
           if keywords and not returncode:
             base_content = self._CollapseKeywords(base_content, keywords)
     else:
       StatusUpdate("svn status returned unexpected output: %s" % status)
       sys.exit(1)
     return base_content, new_content, is_binary, status[0:5]
def upload.SubversionVCS.GetStatus (self, filename)
Returns the status of a file.
Definition at line 854 of file upload.py.
References upload.ErrorExit(), upload.SubversionVCS.GetStatus(), upload.SubversionVCS.rev_end, upload.SubversionVCS.rev_start, upload.RunShell(), upload.RunShellWithReturnCode(), and upload.SubversionVCS.svnls_cache.
   def GetStatus(self, filename):
     """Returns the status of a file."""
     if not self.options.revision:
       status = RunShell(["svn", "status", "--ignore-externals", filename])
       if not status:
         ErrorExit("svn status returned no output for %s" % filename)
       status_lines = status.splitlines()
       # If file is in a cl, the output will begin with
       # "\n--- Changelist 'cl_name':\n".  See
       # http://svn.collab.net/repos/svn/trunk/notes/changelist-design.txt
       if (len(status_lines) == 3 and
           not status_lines[0] and
           status_lines[1].startswith("--- Changelist")):
         status = status_lines[2]
       else:
         status = status_lines[0]
     # If we have a revision to diff against we need to run "svn list"
     # for the old and the new revision and compare the results to get
     # the correct status for a file.
     else:
       dirname, relfilename = os.path.split(filename)
       if dirname not in self.svnls_cache:
         cmd = ["svn", "list", "-r", self.rev_start, dirname or "."]
         out, returncode = RunShellWithReturnCode(cmd)
         if returncode:
           ErrorExit("Failed to get status for %s." % filename)
         old_files = out.splitlines()
         args = ["svn", "list"]
         if self.rev_end:
           args += ["-r", self.rev_end]
         cmd = args + [dirname or "."]
         out, returncode = RunShellWithReturnCode(cmd)
         if returncode:
           ErrorExit("Failed to run command %s" % cmd)
         self.svnls_cache[dirname] = (old_files, out.splitlines())
       old_files, new_files = self.svnls_cache[dirname]
       if relfilename in old_files and relfilename not in new_files:
         status = "D   "
       elif relfilename in old_files and relfilename in new_files:
         status = "M   "
       else:
         status = "A   "
     return status
def upload.SubversionVCS.GetStatus (self, filename)
Returns the status of a file.
Definition at line 854 of file upload.py.
References upload.ErrorExit(), upload.SubversionVCS.GetStatus(), upload.SubversionVCS.rev_end, upload.SubversionVCS.rev_start, upload.RunShell(), upload.RunShellWithReturnCode(), and upload.SubversionVCS.svnls_cache.
   def GetStatus(self, filename):
     """Returns the status of a file."""
     if not self.options.revision:
       status = RunShell(["svn", "status", "--ignore-externals", filename])
       if not status:
         ErrorExit("svn status returned no output for %s" % filename)
       status_lines = status.splitlines()
       # If file is in a cl, the output will begin with
       # "\n--- Changelist 'cl_name':\n".  See
       # http://svn.collab.net/repos/svn/trunk/notes/changelist-design.txt
       if (len(status_lines) == 3 and
           not status_lines[0] and
           status_lines[1].startswith("--- Changelist")):
         status = status_lines[2]
       else:
         status = status_lines[0]
     # If we have a revision to diff against we need to run "svn list"
     # for the old and the new revision and compare the results to get
     # the correct status for a file.
     else:
       dirname, relfilename = os.path.split(filename)
       if dirname not in self.svnls_cache:
         cmd = ["svn", "list", "-r", self.rev_start, dirname or "."]
         out, returncode = RunShellWithReturnCode(cmd)
         if returncode:
           ErrorExit("Failed to get status for %s." % filename)
         old_files = out.splitlines()
         args = ["svn", "list"]
         if self.rev_end:
           args += ["-r", self.rev_end]
         cmd = args + [dirname or "."]
         out, returncode = RunShellWithReturnCode(cmd)
         if returncode:
           ErrorExit("Failed to run command %s" % cmd)
         self.svnls_cache[dirname] = (old_files, out.splitlines())
       old_files, new_files = self.svnls_cache[dirname]
       if relfilename in old_files and relfilename not in new_files:
         status = "D   "
       elif relfilename in old_files and relfilename in new_files:
         status = "M   "
       else:
         status = "A   "
     return status
def upload.SubversionVCS.GetStatus (self, filename)
Returns the status of a file.
Definition at line 854 of file upload.py.
References upload.ErrorExit(), upload.SubversionVCS.GetStatus(), upload.SubversionVCS.rev_end, upload.SubversionVCS.rev_start, upload.RunShell(), upload.RunShellWithReturnCode(), and upload.SubversionVCS.svnls_cache.
   def GetStatus(self, filename):
     """Returns the status of a file."""
     if not self.options.revision:
       status = RunShell(["svn", "status", "--ignore-externals", filename])
       if not status:
         ErrorExit("svn status returned no output for %s" % filename)
       status_lines = status.splitlines()
       # If file is in a cl, the output will begin with
       # "\n--- Changelist 'cl_name':\n".  See
       # http://svn.collab.net/repos/svn/trunk/notes/changelist-design.txt
       if (len(status_lines) == 3 and
           not status_lines[0] and
           status_lines[1].startswith("--- Changelist")):
         status = status_lines[2]
       else:
         status = status_lines[0]
     # If we have a revision to diff against we need to run "svn list"
     # for the old and the new revision and compare the results to get
     # the correct status for a file.
     else:
       dirname, relfilename = os.path.split(filename)
       if dirname not in self.svnls_cache:
         cmd = ["svn", "list", "-r", self.rev_start, dirname or "."]
         out, returncode = RunShellWithReturnCode(cmd)
         if returncode:
           ErrorExit("Failed to get status for %s." % filename)
         old_files = out.splitlines()
         args = ["svn", "list"]
         if self.rev_end:
           args += ["-r", self.rev_end]
         cmd = args + [dirname or "."]
         out, returncode = RunShellWithReturnCode(cmd)
         if returncode:
           ErrorExit("Failed to run command %s" % cmd)
         self.svnls_cache[dirname] = (old_files, out.splitlines())
       old_files, new_files = self.svnls_cache[dirname]
       if relfilename in old_files and relfilename not in new_files:
         status = "D   "
       elif relfilename in old_files and relfilename in new_files:
         status = "M   "
       else:
         status = "A   "
     return status
def upload.SubversionVCS.GetStatus (self, filename)
Returns the status of a file.
Definition at line 854 of file upload.py.
References upload.ErrorExit(), upload.SubversionVCS.GetStatus(), upload.SubversionVCS.rev_end, upload.SubversionVCS.rev_start, upload.RunShell(), upload.RunShellWithReturnCode(), and upload.SubversionVCS.svnls_cache.
   def GetStatus(self, filename):
     """Returns the status of a file."""
     if not self.options.revision:
       status = RunShell(["svn", "status", "--ignore-externals", filename])
       if not status:
         ErrorExit("svn status returned no output for %s" % filename)
       status_lines = status.splitlines()
       # If file is in a cl, the output will begin with
       # "\n--- Changelist 'cl_name':\n".  See
       # http://svn.collab.net/repos/svn/trunk/notes/changelist-design.txt
       if (len(status_lines) == 3 and
           not status_lines[0] and
           status_lines[1].startswith("--- Changelist")):
         status = status_lines[2]
       else:
         status = status_lines[0]
     # If we have a revision to diff against we need to run "svn list"
     # for the old and the new revision and compare the results to get
     # the correct status for a file.
     else:
       dirname, relfilename = os.path.split(filename)
       if dirname not in self.svnls_cache:
         cmd = ["svn", "list", "-r", self.rev_start, dirname or "."]
         out, returncode = RunShellWithReturnCode(cmd)
         if returncode:
           ErrorExit("Failed to get status for %s." % filename)
         old_files = out.splitlines()
         args = ["svn", "list"]
         if self.rev_end:
           args += ["-r", self.rev_end]
         cmd = args + [dirname or "."]
         out, returncode = RunShellWithReturnCode(cmd)
         if returncode:
           ErrorExit("Failed to run command %s" % cmd)
         self.svnls_cache[dirname] = (old_files, out.splitlines())
       old_files, new_files = self.svnls_cache[dirname]
       if relfilename in old_files and relfilename not in new_files:
         status = "D   "
       elif relfilename in old_files and relfilename in new_files:
         status = "M   "
       else:
         status = "A   "
     return status
def upload.SubversionVCS.GetStatus (self, filename)
Returns the status of a file.
Definition at line 854 of file upload.py.
References upload.ErrorExit(), upload.SubversionVCS.rev_end, upload.SubversionVCS.rev_start, upload.RunShell(), upload.RunShellWithReturnCode(), and upload.SubversionVCS.svnls_cache.
Referenced by upload.SubversionVCS.GetBaseFile(), and upload.SubversionVCS.GetStatus().
   def GetStatus(self, filename):
     """Returns the status of a file."""
     if not self.options.revision:
       status = RunShell(["svn", "status", "--ignore-externals", filename])
       if not status:
         ErrorExit("svn status returned no output for %s" % filename)
       status_lines = status.splitlines()
       # If file is in a cl, the output will begin with
       # "\n--- Changelist 'cl_name':\n".  See
       # http://svn.collab.net/repos/svn/trunk/notes/changelist-design.txt
       if (len(status_lines) == 3 and
           not status_lines[0] and
           status_lines[1].startswith("--- Changelist")):
         status = status_lines[2]
       else:
         status = status_lines[0]
     # If we have a revision to diff against we need to run "svn list"
     # for the old and the new revision and compare the results to get
     # the correct status for a file.
     else:
       dirname, relfilename = os.path.split(filename)
       if dirname not in self.svnls_cache:
         cmd = ["svn", "list", "-r", self.rev_start, dirname or "."]
         out, returncode = RunShellWithReturnCode(cmd)
         if returncode:
           ErrorExit("Failed to get status for %s." % filename)
         old_files = out.splitlines()
         args = ["svn", "list"]
         if self.rev_end:
           args += ["-r", self.rev_end]
         cmd = args + [dirname or "."]
         out, returncode = RunShellWithReturnCode(cmd)
         if returncode:
           ErrorExit("Failed to run command %s" % cmd)
         self.svnls_cache[dirname] = (old_files, out.splitlines())
       old_files, new_files = self.svnls_cache[dirname]
       if relfilename in old_files and relfilename not in new_files:
         status = "D   "
       elif relfilename in old_files and relfilename in new_files:
         status = "M   "
       else:
         status = "A   "
     return status
def upload.SubversionVCS.GetStatus (self, filename)
Returns the status of a file.
Definition at line 854 of file upload.py.
References upload.ErrorExit(), upload.SubversionVCS.GetStatus(), upload.SubversionVCS.rev_end, upload.SubversionVCS.rev_start, upload.RunShell(), upload.RunShellWithReturnCode(), and upload.SubversionVCS.svnls_cache.
   def GetStatus(self, filename):
     """Returns the status of a file."""
     if not self.options.revision:
       status = RunShell(["svn", "status", "--ignore-externals", filename])
       if not status:
         ErrorExit("svn status returned no output for %s" % filename)
       status_lines = status.splitlines()
       # If file is in a cl, the output will begin with
       # "\n--- Changelist 'cl_name':\n".  See
       # http://svn.collab.net/repos/svn/trunk/notes/changelist-design.txt
       if (len(status_lines) == 3 and
           not status_lines[0] and
           status_lines[1].startswith("--- Changelist")):
         status = status_lines[2]
       else:
         status = status_lines[0]
     # If we have a revision to diff against we need to run "svn list"
     # for the old and the new revision and compare the results to get
     # the correct status for a file.
     else:
       dirname, relfilename = os.path.split(filename)
       if dirname not in self.svnls_cache:
         cmd = ["svn", "list", "-r", self.rev_start, dirname or "."]
         out, returncode = RunShellWithReturnCode(cmd)
         if returncode:
           ErrorExit("Failed to get status for %s." % filename)
         old_files = out.splitlines()
         args = ["svn", "list"]
         if self.rev_end:
           args += ["-r", self.rev_end]
         cmd = args + [dirname or "."]
         out, returncode = RunShellWithReturnCode(cmd)
         if returncode:
           ErrorExit("Failed to run command %s" % cmd)
         self.svnls_cache[dirname] = (old_files, out.splitlines())
       old_files, new_files = self.svnls_cache[dirname]
       if relfilename in old_files and relfilename not in new_files:
         status = "D   "
       elif relfilename in old_files and relfilename in new_files:
         status = "M   "
       else:
         status = "A   "
     return status
def upload.SubversionVCS.GetUnknownFiles (self)
Definition at line 836 of file upload.py.
References upload.SubversionVCS.GetUnknownFiles(), and upload.RunShell().
   def GetUnknownFiles(self):
     status = RunShell(["svn", "status", "--ignore-externals"], silent_ok=True)
     unknown_files = []
     for line in status.split("\n"):
       if line and line[0] == "?":
         unknown_files.append(line)
     return unknown_files
def upload.SubversionVCS.GetUnknownFiles (self)
Definition at line 836 of file upload.py.
References upload.RunShell().
Referenced by upload.SubversionVCS.GetUnknownFiles().
   def GetUnknownFiles(self):
     status = RunShell(["svn", "status", "--ignore-externals"], silent_ok=True)
     unknown_files = []
     for line in status.split("\n"):
       if line and line[0] == "?":
         unknown_files.append(line)
     return unknown_files
def upload.SubversionVCS.GetUnknownFiles (self)
Definition at line 836 of file upload.py.
References upload.SubversionVCS.GetUnknownFiles(), and upload.RunShell().
   def GetUnknownFiles(self):
     status = RunShell(["svn", "status", "--ignore-externals"], silent_ok=True)
     unknown_files = []
     for line in status.split("\n"):
       if line and line[0] == "?":
         unknown_files.append(line)
     return unknown_files
def upload.SubversionVCS.GetUnknownFiles (self)
Definition at line 836 of file upload.py.
References upload.SubversionVCS.GetUnknownFiles(), and upload.RunShell().
   def GetUnknownFiles(self):
     status = RunShell(["svn", "status", "--ignore-externals"], silent_ok=True)
     unknown_files = []
     for line in status.split("\n"):
       if line and line[0] == "?":
         unknown_files.append(line)
     return unknown_files
def upload.SubversionVCS.GetUnknownFiles (self)
Definition at line 836 of file upload.py.
References upload.SubversionVCS.GetUnknownFiles(), and upload.RunShell().
   def GetUnknownFiles(self):
     status = RunShell(["svn", "status", "--ignore-externals"], silent_ok=True)
     unknown_files = []
     for line in status.split("\n"):
       if line and line[0] == "?":
         unknown_files.append(line)
     return unknown_files
def upload.SubversionVCS.GetUnknownFiles (self)
Definition at line 836 of file upload.py.
References upload.SubversionVCS.GetUnknownFiles(), and upload.RunShell().
   def GetUnknownFiles(self):
     status = RunShell(["svn", "status", "--ignore-externals"], silent_ok=True)
     unknown_files = []
     for line in status.split("\n"):
       if line and line[0] == "?":
         unknown_files.append(line)
     return unknown_files
def upload.SubversionVCS.GuessBase (self, required)
Wrapper for _GuessBase.
Definition at line 742 of file upload.py.
References upload.SubversionVCS.GuessBase(), and upload.SubversionVCS.svn_base.
   def GuessBase(self, required):
     """Wrapper for _GuessBase."""
     return self.svn_base
def upload.SubversionVCS.GuessBase (self, required)
Wrapper for _GuessBase.
Definition at line 742 of file upload.py.
References upload.SubversionVCS.svn_base.
Referenced by upload.SubversionVCS.GuessBase().
   def GuessBase(self, required):
     """Wrapper for _GuessBase."""
     return self.svn_base
def upload.SubversionVCS.GuessBase (self, required)
Wrapper for _GuessBase.
Definition at line 742 of file upload.py.
References upload.SubversionVCS.GuessBase(), and upload.SubversionVCS.svn_base.
   def GuessBase(self, required):
     """Wrapper for _GuessBase."""
     return self.svn_base
def upload.SubversionVCS.GuessBase (self, required)
Wrapper for _GuessBase.
Definition at line 742 of file upload.py.
References upload.SubversionVCS.GuessBase(), and upload.SubversionVCS.svn_base.
   def GuessBase(self, required):
     """Wrapper for _GuessBase."""
     return self.svn_base
def upload.SubversionVCS.GuessBase (self, required)
Wrapper for _GuessBase.
Definition at line 742 of file upload.py.
References upload.SubversionVCS.GuessBase(), and upload.SubversionVCS.svn_base.
   def GuessBase(self, required):
     """Wrapper for _GuessBase."""
     return self.svn_base
def upload.SubversionVCS.GuessBase (self, required)
Wrapper for _GuessBase.
Definition at line 742 of file upload.py.
References upload.SubversionVCS.GuessBase(), and upload.SubversionVCS.svn_base.
   def GuessBase(self, required):
     """Wrapper for _GuessBase."""
     return self.svn_base
def upload.SubversionVCS.ReadFile (self, filename)
Returns the contents of a file.
Definition at line 844 of file upload.py.
References upload.SubversionVCS.ReadFile().
   def ReadFile(self, filename):
     """Returns the contents of a file."""
     file = open(filename, 'rb')
     result = ""
     try:
       result = file.read()
     finally:
       file.close()
     return result
def upload.SubversionVCS.ReadFile (self, filename)
Returns the contents of a file.
Definition at line 844 of file upload.py.
References upload.SubversionVCS.ReadFile().
   def ReadFile(self, filename):
     """Returns the contents of a file."""
     file = open(filename, 'rb')
     result = ""
     try:
       result = file.read()
     finally:
       file.close()
     return result
def upload.SubversionVCS.ReadFile (self, filename)
Returns the contents of a file.
Definition at line 844 of file upload.py.
References upload.SubversionVCS.ReadFile().
   def ReadFile(self, filename):
     """Returns the contents of a file."""
     file = open(filename, 'rb')
     result = ""
     try:
       result = file.read()
     finally:
       file.close()
     return result
def upload.SubversionVCS.ReadFile (self, filename)
Returns the contents of a file.
Definition at line 844 of file upload.py.
Referenced by upload.SubversionVCS.GetBaseFile(), and upload.SubversionVCS.ReadFile().
   def ReadFile(self, filename):
     """Returns the contents of a file."""
     file = open(filename, 'rb')
     result = ""
     try:
       result = file.read()
     finally:
       file.close()
     return result
def upload.SubversionVCS.ReadFile (self, filename)
Returns the contents of a file.
Definition at line 844 of file upload.py.
References upload.SubversionVCS.ReadFile().
   def ReadFile(self, filename):
     """Returns the contents of a file."""
     file = open(filename, 'rb')
     result = ""
     try:
       result = file.read()
     finally:
       file.close()
     return result
def upload.SubversionVCS.ReadFile (self, filename)
Returns the contents of a file.
Definition at line 844 of file upload.py.
References upload.SubversionVCS.ReadFile().
   def ReadFile(self, filename):
     """Returns the contents of a file."""
     file = open(filename, 'rb')
     result = ""
     try:
       result = file.read()
     finally:
       file.close()
     return result
Member Data Documentation
upload.SubversionVCS.rev_end
Definition at line 731 of file upload.py.
Referenced by upload.SubversionVCS.__init__(), upload.SubversionVCS.GetBaseFile(), and upload.SubversionVCS.GetStatus().
upload.SubversionVCS.rev_start
Definition at line 730 of file upload.py.
Referenced by upload.SubversionVCS.__init__(), upload.SubversionVCS.GetBaseFile(), and upload.SubversionVCS.GetStatus().
upload.SubversionVCS.svn_base
Definition at line 740 of file upload.py.
Referenced by upload.SubversionVCS.__init__(), upload.SubversionVCS.GetBaseFile(), and upload.SubversionVCS.GuessBase().
upload.SubversionVCS.svnls_cache
Definition at line 736 of file upload.py.
Referenced by upload.SubversionVCS.__init__(), and upload.SubversionVCS.GetStatus().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/scripts/upload.py