proxygen: release_docs.WikiBrancher Class Reference
release_docs.WikiBrancher Class Reference
Public Member Functions
def __init__ (self, dot_version)
def GetFilesToBranch (self)
def BranchFiles (self)
def UpdateLinksInBranchedFiles (self)
def __init__ (self, dot_version)
def GetFilesToBranch (self)
def BranchFiles (self)
def UpdateLinksInBranchedFiles (self)
def __init__ (self, dot_version)
def GetFilesToBranch (self)
def BranchFiles (self)
def UpdateLinksInBranchedFiles (self)
Public Attributes
wiki_dir
version_prefix
files_to_branch
search_for_re
replace_with
project
Detailed Description
Branches ...
Definition at line 89 of file release_docs.py.
Constructor & Destructor Documentation
def release_docs.WikiBrancher.__init__ (self, dot_version)
Definition at line 92 of file release_docs.py.
References common.GetSvnInfo(), and release_docs.WikiBrancher.project.
Referenced by release_docs.WikiBrancher.__init__().
   def __init__(self, dot_version):
     self.project, svn_root_path = common.GetSvnInfo()
     if self.project not in ('googletest', 'googlemock'):
       sys.exit('This script must be run in a gtest or gmock SVN workspace.')
     self.wiki_dir = svn_root_path + '/wiki'
     # Turn '2.6' to 'V2_6_'.
     self.version_prefix = 'V' + dot_version.replace('.', '_') + '_'
     self.files_to_branch = self.GetFilesToBranch()
     page_names = [DropWikiSuffix(f) for f in self.files_to_branch]
     # A link to Foo.wiki is in one of the following forms:
     #   [Foo words]
     #   [Foo#Anchor words]
     #   [http://code.google.com/.../wiki/Foo words]
     #   [http://code.google.com/.../wiki/Foo#Anchor words]
     # We want to replace 'Foo' with 'V2_6_Foo' in the above cases.
     self.search_for_re = re.compile(
         # This regex matches either
         #   [Foo
         # or
         #   /wiki/Foo
         # followed by a space or a #, where Foo is the name of an
         # unversioned wiki page.
         r'(\[|/wiki/)(%s)([ #])' % '|'.join(page_names))
     self.replace_with = r'\1%s\2\3' % (self.version_prefix,)
def release_docs.WikiBrancher.__init__ (self, dot_version)
Definition at line 92 of file release_docs.py.
References release_docs.WikiBrancher.__init__(), release_docs.DropWikiSuffix(), release_docs.WikiBrancher.files_to_branch, release_docs.WikiBrancher.GetFilesToBranch(), common.GetSvnInfo(), join, release_docs.WikiBrancher.project, release_docs.WikiBrancher.replace_with, release_docs.WikiBrancher.search_for_re, release_docs.WikiBrancher.version_prefix, and release_docs.WikiBrancher.wiki_dir.
   def __init__(self, dot_version):
     self.project, svn_root_path = common.GetSvnInfo()
     if self.project not in ('googletest', 'googlemock'):
       sys.exit('This script must be run in a gtest or gmock SVN workspace.')
     self.wiki_dir = svn_root_path + '/wiki'
     # Turn '2.6' to 'V2_6_'.
     self.version_prefix = 'V' + dot_version.replace('.', '_') + '_'
     self.files_to_branch = self.GetFilesToBranch()
     page_names = [DropWikiSuffix(f) for f in self.files_to_branch]
     # A link to Foo.wiki is in one of the following forms:
     #   [Foo words]
     #   [Foo#Anchor words]
     #   [http://code.google.com/.../wiki/Foo words]
     #   [http://code.google.com/.../wiki/Foo#Anchor words]
     # We want to replace 'Foo' with 'V2_6_Foo' in the above cases.
     self.search_for_re = re.compile(
         # This regex matches either
         #   [Foo
         # or
         #   /wiki/Foo
         # followed by a space or a #, where Foo is the name of an
         # unversioned wiki page.
         r'(\[|/wiki/)(%s)([ #])' % '|'.join(page_names))
     self.replace_with = r'\1%s\2\3' % (self.version_prefix,)
def release_docs.WikiBrancher.__init__ (self, dot_version)
Definition at line 92 of file release_docs.py.
References release_docs.WikiBrancher.__init__(), release_docs.DropWikiSuffix(), release_docs.WikiBrancher.files_to_branch, release_docs.WikiBrancher.GetFilesToBranch(), common.GetSvnInfo(), join, release_docs.WikiBrancher.project, release_docs.WikiBrancher.replace_with, release_docs.WikiBrancher.search_for_re, release_docs.WikiBrancher.version_prefix, and release_docs.WikiBrancher.wiki_dir.
   def __init__(self, dot_version):
     self.project, svn_root_path = common.GetSvnInfo()
     if self.project not in ('googletest', 'googlemock'):
       sys.exit('This script must be run in a gtest or gmock SVN workspace.')
     self.wiki_dir = svn_root_path + '/wiki'
     # Turn '2.6' to 'V2_6_'.
     self.version_prefix = 'V' + dot_version.replace('.', '_') + '_'
     self.files_to_branch = self.GetFilesToBranch()
     page_names = [DropWikiSuffix(f) for f in self.files_to_branch]
     # A link to Foo.wiki is in one of the following forms:
     #   [Foo words]
     #   [Foo#Anchor words]
     #   [http://code.google.com/.../wiki/Foo words]
     #   [http://code.google.com/.../wiki/Foo#Anchor words]
     # We want to replace 'Foo' with 'V2_6_Foo' in the above cases.
     self.search_for_re = re.compile(
         # This regex matches either
         #   [Foo
         # or
         #   /wiki/Foo
         # followed by a space or a #, where Foo is the name of an
         # unversioned wiki page.
         r'(\[|/wiki/)(%s)([ #])' % '|'.join(page_names))
     self.replace_with = r'\1%s\2\3' % (self.version_prefix,)
Member Function Documentation
def release_docs.WikiBrancher.BranchFiles (self)
Branches the .wiki files needed to be branched.
Definition at line 127 of file release_docs.py.
References release_docs.WikiBrancher.files_to_branch, release_docs.WikiBrancher.version_prefix, and release_docs.WikiBrancher.wiki_dir.
Referenced by release_docs.WikiBrancher.BranchFiles().
   def BranchFiles(self):
     """Branches the .wiki files needed to be branched."""
     print 'Branching %d .wiki files:' % (len(self.files_to_branch),)
     os.chdir(self.wiki_dir)
     for f in self.files_to_branch:
       command = 'svn cp %s %s%s' % (f, self.version_prefix, f)
       print command
       os.system(command)
def release_docs.WikiBrancher.BranchFiles (self)
Branches the .wiki files needed to be branched.
Definition at line 127 of file release_docs.py.
References release_docs.WikiBrancher.BranchFiles(), release_docs.WikiBrancher.files_to_branch, release_docs.WikiBrancher.version_prefix, and release_docs.WikiBrancher.wiki_dir.
   def BranchFiles(self):
     """Branches the .wiki files needed to be branched."""
     print 'Branching %d .wiki files:' % (len(self.files_to_branch),)
     os.chdir(self.wiki_dir)
     for f in self.files_to_branch:
       command = 'svn cp %s %s%s' % (f, self.version_prefix, f)
       print command
       os.system(command)
def release_docs.WikiBrancher.BranchFiles (self)
Branches the .wiki files needed to be branched.
Definition at line 127 of file release_docs.py.
References release_docs.WikiBrancher.BranchFiles(), release_docs.WikiBrancher.files_to_branch, release_docs.WikiBrancher.version_prefix, and release_docs.WikiBrancher.wiki_dir.
   def BranchFiles(self):
     """Branches the .wiki files needed to be branched."""
     print 'Branching %d .wiki files:' % (len(self.files_to_branch),)
     os.chdir(self.wiki_dir)
     for f in self.files_to_branch:
       command = 'svn cp %s %s%s' % (f, self.version_prefix, f)
       print command
       os.system(command)
def release_docs.WikiBrancher.GetFilesToBranch (self)
Returns a list of .wiki file names that need to be branched.
Definition at line 117 of file release_docs.py.
References release_docs.WikiBrancher.GetFilesToBranch(), release_docs.WikiBrancher.project, and release_docs.WikiBrancher.wiki_dir.
   def GetFilesToBranch(self):
     """Returns a list of .wiki file names that need to be branched."""
     unversioned_wikis = (GTEST_UNVERSIONED_WIKIS if self.project == 'googletest'
                          else GMOCK_UNVERSIONED_WIKIS)
     return [f for f in os.listdir(self.wiki_dir)
             if (f.endswith('.wiki') and
                 not re.match(r'^V\d', f) and  # Excluded versioned .wiki files.
                 f not in unversioned_wikis)]
def release_docs.WikiBrancher.GetFilesToBranch (self)
Returns a list of .wiki file names that need to be branched.
Definition at line 117 of file release_docs.py.
Referenced by release_docs.WikiBrancher.__init__(), and release_docs.WikiBrancher.GetFilesToBranch().
   def GetFilesToBranch(self):
     """Returns a list of .wiki file names that need to be branched."""
     unversioned_wikis = (GTEST_UNVERSIONED_WIKIS if self.project == 'googletest'
                          else GMOCK_UNVERSIONED_WIKIS)
     return [f for f in os.listdir(self.wiki_dir)
             if (f.endswith('.wiki') and
                 not re.match(r'^V\d', f) and  # Excluded versioned .wiki files.
                 f not in unversioned_wikis)]
def release_docs.WikiBrancher.GetFilesToBranch (self)
Returns a list of .wiki file names that need to be branched.
Definition at line 117 of file release_docs.py.
References release_docs.WikiBrancher.GetFilesToBranch(), release_docs.WikiBrancher.project, and release_docs.WikiBrancher.wiki_dir.
   def GetFilesToBranch(self):
     """Returns a list of .wiki file names that need to be branched."""
     unversioned_wikis = (GTEST_UNVERSIONED_WIKIS if self.project == 'googletest'
                          else GMOCK_UNVERSIONED_WIKIS)
     return [f for f in os.listdir(self.wiki_dir)
             if (f.endswith('.wiki') and
                 not re.match(r'^V\d', f) and  # Excluded versioned .wiki files.
                 f not in unversioned_wikis)]
def release_docs.WikiBrancher.UpdateLinksInBranchedFiles (self)
Definition at line 137 of file release_docs.py.
References release_docs.WikiBrancher.files_to_branch, release_docs.main(), release_docs.WikiBrancher.replace_with, release_docs.WikiBrancher.UpdateLinksInBranchedFiles(), release_docs.WikiBrancher.version_prefix, release_docs.WikiBrancher.wiki_dir, and fizz::detail.write().
   def UpdateLinksInBranchedFiles(self):
     for f in self.files_to_branch:
       source_file = os.path.join(self.wiki_dir, f)
       versioned_file = os.path.join(self.wiki_dir, self.version_prefix + f)
       print 'Updating links in %s.' % (versioned_file,)
       text = file(source_file, 'r').read()
       new_text = self.search_for_re.sub(self.replace_with, text)
       file(versioned_file, 'w').write(new_text)
def release_docs.WikiBrancher.UpdateLinksInBranchedFiles (self)
Definition at line 137 of file release_docs.py.
References release_docs.WikiBrancher.files_to_branch, release_docs.WikiBrancher.replace_with, release_docs.WikiBrancher.version_prefix, release_docs.WikiBrancher.wiki_dir, and fizz::detail.write().
Referenced by release_docs.WikiBrancher.UpdateLinksInBranchedFiles().
   def UpdateLinksInBranchedFiles(self):
     for f in self.files_to_branch:
       source_file = os.path.join(self.wiki_dir, f)
       versioned_file = os.path.join(self.wiki_dir, self.version_prefix + f)
       print 'Updating links in %s.' % (versioned_file,)
       text = file(source_file, 'r').read()
       new_text = self.search_for_re.sub(self.replace_with, text)
       file(versioned_file, 'w').write(new_text)
def release_docs.WikiBrancher.UpdateLinksInBranchedFiles (self)
Definition at line 137 of file release_docs.py.
References release_docs.WikiBrancher.files_to_branch, release_docs.main(), release_docs.WikiBrancher.replace_with, release_docs.WikiBrancher.UpdateLinksInBranchedFiles(), release_docs.WikiBrancher.version_prefix, release_docs.WikiBrancher.wiki_dir, and fizz::detail.write().
   def UpdateLinksInBranchedFiles(self):
     for f in self.files_to_branch:
       source_file = os.path.join(self.wiki_dir, f)
       versioned_file = os.path.join(self.wiki_dir, self.version_prefix + f)
       print 'Updating links in %s.' % (versioned_file,)
       text = file(source_file, 'r').read()
       new_text = self.search_for_re.sub(self.replace_with, text)
       file(versioned_file, 'w').write(new_text)
Member Data Documentation
release_docs.WikiBrancher.files_to_branch
Definition at line 99 of file release_docs.py.
Referenced by release_docs.WikiBrancher.__init__(), release_docs.WikiBrancher.BranchFiles(), and release_docs.WikiBrancher.UpdateLinksInBranchedFiles().
release_docs.WikiBrancher.project
Definition at line 120 of file release_docs.py.
Referenced by release_docs.WikiBrancher.__init__(), and release_docs.WikiBrancher.GetFilesToBranch().
release_docs.WikiBrancher.replace_with
Definition at line 115 of file release_docs.py.
Referenced by release_docs.WikiBrancher.__init__(), and release_docs.WikiBrancher.UpdateLinksInBranchedFiles().
release_docs.WikiBrancher.search_for_re
Definition at line 107 of file release_docs.py.
Referenced by release_docs.WikiBrancher.__init__().
release_docs.WikiBrancher.version_prefix
Definition at line 98 of file release_docs.py.
Referenced by release_docs.WikiBrancher.__init__(), release_docs.WikiBrancher.BranchFiles(), and release_docs.WikiBrancher.UpdateLinksInBranchedFiles().
release_docs.WikiBrancher.wiki_dir
Definition at line 96 of file release_docs.py.
Referenced by release_docs.WikiBrancher.__init__(), release_docs.WikiBrancher.BranchFiles(), release_docs.WikiBrancher.GetFilesToBranch(), and release_docs.WikiBrancher.UpdateLinksInBranchedFiles().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/scripts/release_docs.py