proxygen: folly::AsyncSocketException Class Reference
folly::AsyncSocketException Class Reference
#include <AsyncSocketException.h>
Public Types
enum AsyncSocketExceptionType {
UNKNOWN = 0, NOT_OPEN = 1, ALREADY_OPEN = 2, TIMED_OUT = 3,
END_OF_FILE = 4, INTERRUPTED = 5, BAD_ARGS = 6, CORRUPTED_DATA = 7,
INTERNAL_ERROR = 8, NOT_SUPPORTED = 9, INVALID_STATE = 10, SSL_ERROR = 12,
COULD_NOT_BIND = 13, SASL_HANDSHAKE_TIMEOUT = 14, NETWORK_ERROR = 15, EARLY_DATA_REJECTED = 16
}
Public Member Functions
AsyncSocketException (AsyncSocketExceptionType type, const std::string &message, int errnoCopy=0)
AsyncSocketExceptionType getType () const noexcept
int getErrno () const noexcept
Static Protected Member Functions
static folly::StringPiece getExceptionTypeString (AsyncSocketExceptionType type)
static std::string getMessage (AsyncSocketExceptionType type, const std::string &message, int errnoCopy)
Protected Attributes
AsyncSocketExceptionType type_
int errno_
Detailed Description
Definition at line 26 of file AsyncSocketException.h.
Member Enumeration Documentation
enum folly::AsyncSocketException::AsyncSocketExceptionType
Enumerator
UNKNOWN
NOT_OPEN
ALREADY_OPEN
TIMED_OUT
END_OF_FILE
INTERRUPTED
BAD_ARGS
CORRUPTED_DATA
INTERNAL_ERROR
NOT_SUPPORTED
INVALID_STATE
SSL_ERROR
COULD_NOT_BIND
SASL_HANDSHAKE_TIMEOUT
NETWORK_ERROR
EARLY_DATA_REJECTED
Definition at line 28 of file AsyncSocketException.h.
{
     UNKNOWN = 0,
     NOT_OPEN = 1,
     ALREADY_OPEN = 2,
     TIMED_OUT = 3,
     END_OF_FILE = 4,
     INTERRUPTED = 5,
     BAD_ARGS = 6,
     CORRUPTED_DATA = 7,
     INTERNAL_ERROR = 8,
     NOT_SUPPORTED = 9,
     INVALID_STATE = 10,
     SSL_ERROR = 12,
     COULD_NOT_BIND = 13,
     SASL_HANDSHAKE_TIMEOUT = 14,
     NETWORK_ERROR = 15,
     EARLY_DATA_REJECTED = 16,
   };
Constructor & Destructor Documentation
folly::AsyncSocketException::AsyncSocketException (AsyncSocketExceptionType type, const std::string & message, int errnoCopy = 0) inline
Definition at line 47 of file AsyncSocketException.h.
       : std::runtime_error(getMessage(type, message, errnoCopy)),
         type_(type),
         errno_(errnoCopy) {}
Member Function Documentation
int folly::AsyncSocketException::getErrno () const inline noexcept
Definition at line 59 of file AsyncSocketException.h.
References string, and type.
Referenced by folly::TEST().
{
     return errno_;
   }
StringPiece folly::AsyncSocketException::getExceptionTypeString (AsyncSocketExceptionType type) static protected
get the string of exception type
Definition at line 24 of file AsyncSocketException.cpp.
References ALREADY_OPEN, BAD_ARGS, CORRUPTED_DATA, COULD_NOT_BIND, EARLY_DATA_REJECTED, END_OF_FILE, INTERNAL_ERROR, INTERRUPTED, INVALID_STATE, NETWORK_ERROR, NOT_OPEN, NOT_SUPPORTED, SASL_HANDSHAKE_TIMEOUT, SSL_ERROR, TIMED_OUT, and UNKNOWN.
Referenced by getMessage().
{
   switch (type) {
     case UNKNOWN:
       return "Unknown async socket exception";
     case NOT_OPEN:
       return "Socket not open";
     case ALREADY_OPEN:
       return "Socket already open";
     case TIMED_OUT:
       return "Timed out";
     case END_OF_FILE:
       return "End of file";
     case INTERRUPTED:
       return "Interrupted";
     case BAD_ARGS:
       return "Invalid arguments";
     case CORRUPTED_DATA:
       return "Corrupted Data";
     case INTERNAL_ERROR:
       return "Internal error";
     case NOT_SUPPORTED:
       return "Not supported";
     case INVALID_STATE:
       return "Invalid state";
     case SSL_ERROR:
       return "SSL error";
     case COULD_NOT_BIND:
       return "Could not bind";
     case SASL_HANDSHAKE_TIMEOUT:
       return "SASL handshake timeout";
     case NETWORK_ERROR:
       return "Network error";
     case EARLY_DATA_REJECTED:
       return "Early data rejected";
     default:
       return "(Invalid exception type)";
   }
 }
std::string folly::AsyncSocketException::getMessage (AsyncSocketExceptionType type, const std::string & message, int errnoCopy) static protected
Return a message based on the input.
Definition at line 64 of file AsyncSocketException.cpp.
References folly::errnoStr(), getExceptionTypeString(), and folly::sformat().
                    {
   if (errnoCopy != 0) {
     return sformat(
         "AsyncSocketException: {}, type = {}, errno = {} ({})",
         message,
         getExceptionTypeString(type),
         errnoCopy,
         errnoStr(errnoCopy));
   } else {
     return sformat(
         "AsyncSocketException: {}, type = {}",
         message,
         getExceptionTypeString(type));
   }
 }
AsyncSocketExceptionType folly::AsyncSocketException::getType () const inline noexcept
Definition at line 55 of file AsyncSocketException.h.
References type_.
Referenced by fizz::AsyncFizzBase::deliverError(), fizz::test::HandshakeTest::expectEarlyDataRejectError(), folly::TEST(), TEST(), fizz::test::TEST_F(), and fizz::client::test::TEST_F().
{
     return type_;
   }
Member Data Documentation
int folly::AsyncSocketException::errno_ protected
A copy of the errno.
Definition at line 78 of file AsyncSocketException.h.
AsyncSocketExceptionType folly::AsyncSocketException::type_ protected
Error code
Definition at line 75 of file AsyncSocketException.h.
The documentation for this class was generated from the following files:
proxygen/folly/folly/io/async/AsyncSocketException.h
proxygen/folly/folly/io/async/AsyncSocketException.cpp