proxygen: MoveToFbStringTest Class Reference
MoveToFbStringTest Class Reference
Protected Member Functions
void SetUp () override
std::unique_ptr< IOBuf > makeBuf ()
void check (std::unique_ptr< IOBuf > &buf)
Protected Attributes
int elementSize_
int elementCount_
bool shared_
BufType type_
std::unique_ptr< IOBuf > buf_
std::unique_ptr< IOBuf > buf2_
std::vector< std::unique_ptr< uint8_t[]> > ownedBuffers_
Detailed Description
Definition at line 852 of file IOBufTest.cpp.
Member Function Documentation
void MoveToFbStringTest::check (std::unique_ptr< IOBuf > & buf) inline protected
Definition at line 907 of file IOBufTest.cpp.
References folly::IOBuf::computeChainDataLength(), folly::IOBuf::countChainElements(), EXPECT_EQ, EXPECT_FALSE, folly::IOBuf::isChained(), folly::IOBuf::length(), and folly::IOBuf::moveToFbString().
{
     fbstring str = buf->moveToFbString();
     EXPECT_EQ(elementCount_ * elementSize_, str.size());
     EXPECT_EQ(elementCount_ * elementSize_, strspn(str.c_str(), "x"));
     EXPECT_EQ(0, buf->length());
     EXPECT_EQ(1, buf->countChainElements());
     EXPECT_EQ(0, buf->computeChainDataLength());
     EXPECT_FALSE(buf->isChained());
   }
std::unique_ptr<IOBuf> MoveToFbStringTest::makeBuf () inline protected
Definition at line 874 of file IOBufTest.cpp.
References folly::IOBuf::append(), CREATE, data, folly::gen::move, TAKE_OWNERSHIP_CUSTOM, TAKE_OWNERSHIP_MALLOC, testFreeFn(), type_, uint8_t, USER_OWNED, and folly::IOBuf::writableData().
{
     unique_ptr<IOBuf> buf;
     switch (type_) {
       case CREATE:
         buf = IOBuf::create(elementSize_);
         buf->append(elementSize_);
         break;
       case TAKE_OWNERSHIP_MALLOC: {
         void* data = malloc(elementSize_);
         if (!data) {
           throw std::bad_alloc();
         }
         buf = IOBuf::takeOwnership(data, elementSize_);
         break;
       }
       case TAKE_OWNERSHIP_CUSTOM: {
         uint8_t* data = new uint8_t[elementSize_];
         buf = IOBuf::takeOwnership(data, elementSize_, testFreeFn);
         break;
       }
       case USER_OWNED: {
         unique_ptr<uint8_t[]> data(new uint8_t[elementSize_]);
         buf = IOBuf::wrapBuffer(data.get(), elementSize_);
         ownedBuffers_.emplace_back(std::move(data));
         break;
       }
       default:
         throw std::invalid_argument("unexpected buffer type parameter");
     }
     memset(buf->writableData(), 'x', elementSize_);
     return buf;
   }
void MoveToFbStringTest::SetUp () inline override protected
Definition at line 855 of file IOBufTest.cpp.
References EXPECT_EQ, i, makeBuf(), and type_.
{
     elementSize_ = std::get<0>(GetParam());
     elementCount_ = std::get<1>(GetParam());
     shared_ = std::get<2>(GetParam());
     type_ = std::get<3>(GetParam());
     buf_ = makeBuf();
     for (int i = 0; i < elementCount_ - 1; ++i) {
       buf_->prependChain(makeBuf());
     }
     EXPECT_EQ(elementCount_, buf_->countChainElements());
     EXPECT_EQ(elementCount_ * elementSize_, buf_->computeChainDataLength());
     if (shared_) {
       buf2_ = buf_->clone();
       EXPECT_EQ(elementCount_, buf2_->countChainElements());
       EXPECT_EQ(elementCount_ * elementSize_, buf2_->computeChainDataLength());
     }
   }
Member Data Documentation
std::unique_ptr<IOBuf> MoveToFbStringTest::buf2_ protected
Definition at line 922 of file IOBufTest.cpp.
std::unique_ptr<IOBuf> MoveToFbStringTest::buf_ protected
Definition at line 921 of file IOBufTest.cpp.
int MoveToFbStringTest::elementCount_ protected
Definition at line 918 of file IOBufTest.cpp.
int MoveToFbStringTest::elementSize_ protected
Definition at line 917 of file IOBufTest.cpp.
std::vector<std::unique_ptr<uint8_t[]> > MoveToFbStringTest::ownedBuffers_ protected
Definition at line 923 of file IOBufTest.cpp.
bool MoveToFbStringTest::shared_ protected
Definition at line 919 of file IOBufTest.cpp.
BufType MoveToFbStringTest::type_ protected
Definition at line 920 of file IOBufTest.cpp.
The documentation for this class was generated from the following file:
proxygen/folly/folly/io/test/IOBufTest.cpp