proxygen: folly::pushmi::receiver< VF, EF, DF > Class Template Reference
folly::pushmi::receiver< VF, EF, DF > Class Template Reference
#include <receiver.h>
Public Types
using properties = property_set< is_receiver<>>
Public Member Functions
receiver ()=default
constexpr receiver (VF vf)
constexpr receiver (EF ef)
constexpr receiver (DF df)
constexpr receiver (EF ef, DF df)
constexpr receiver (VF vf, EF ef, DF df=DF{})
requires Invocable< VF &, VN... > void value (VN &&...vn)
requires Invocable< EF &, E > void error (E e) noexcept
void done ()
Private Attributes
bool done_ = false
VF vf_
EF ef_
DF df_
Detailed Description
template<class VF, class EF, class DF>
class folly::pushmi::receiver< VF, EF, DF >
Definition at line 170 of file receiver.h.
Member Typedef Documentation
template<class VF , class EF , class DF > using folly::pushmi::receiver< VF, EF, DF >::properties = property_set<is_receiver<>>
Definition at line 187 of file receiver.h.
Constructor & Destructor Documentation
template<class VF , class EF , class DF > folly::pushmi::receiver< VF, EF, DF >::receiver () default
template<class VF , class EF , class DF > constexpr folly::pushmi::receiver< VF, EF, DF >::receiver (VF vf) inline explicit
Definition at line 190 of file receiver.h.
 : receiver(std::move(vf), EF{}, DF{}) {}
template<class VF , class EF , class DF > constexpr folly::pushmi::receiver< VF, EF, DF >::receiver (EF ef) inline explicit
Definition at line 191 of file receiver.h.
References folly::gen::move.
 : receiver(VF{}, std::move(ef), DF{}) {}
template<class VF , class EF , class DF > constexpr folly::pushmi::receiver< VF, EF, DF >::receiver (DF df) inline explicit
Definition at line 192 of file receiver.h.
References folly::gen::move.
 : receiver(VF{}, EF{}, std::move(df)) {}
template<class VF , class EF , class DF > constexpr folly::pushmi::receiver< VF, EF, DF >::receiver (EF ef, DF df) inline
Definition at line 193 of file receiver.h.
       : done_(false), vf_(), ef_(std::move(ef)), df_(std::move(df)) {}
template<class VF , class EF , class DF > constexpr folly::pushmi::receiver< VF, EF, DF >::receiver (VF vf, EF ef, DF df = DF{}) inline
Definition at line 195 of file receiver.h.
References folly::pushmi::any_receiver< E, VN >::done_, folly::gen::move, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
                                              {})
       : done_(false),
         vf_(std::move(vf)),
         ef_(std::move(ef)),
         df_(std::move(df)) {}
Member Function Documentation
template<class VF , class EF , class DF > void folly::pushmi::receiver< VF, EF, DF >::done () inline
Definition at line 219 of file receiver.h.
References PUSHMI_TYPE_CONSTRAINT, and folly::pushmi::requires().
               {
     if (!done_) {
       done_ = true;
       df_();
     }
   }
template<class VF , class EF , class DF > requires Invocable<EF&, E> void folly::pushmi::receiver< VF, EF, DF >::error (E e) inline noexcept
Definition at line 212 of file receiver.h.
References folly::gen::move.
{
     static_assert(NothrowInvocable<EF&, E>, "error function must be noexcept");
     if (!done_) {
       done_ = true;
       ef_(std::move(e));
     }
   }
template<class VF , class EF , class DF > requires Invocable<VF&, VN...> void folly::pushmi::receiver< VF, EF, DF >::value (VN &&... vn) inline
Definition at line 203 of file receiver.h.
References folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     if (done_) {
       return;
     }
     // done_ = true;
     vf_((VN &&) vn...);
   }
Member Data Documentation
template<class VF , class EF , class DF > DF folly::pushmi::receiver< VF, EF, DF >::df_ private
Definition at line 174 of file receiver.h.
template<class VF , class EF , class DF > bool folly::pushmi::receiver< VF, EF, DF >::done_ = false private
Definition at line 171 of file receiver.h.
template<class VF , class EF , class DF > EF folly::pushmi::receiver< VF, EF, DF >::ef_ private
Definition at line 173 of file receiver.h.
template<class VF , class EF , class DF > VF folly::pushmi::receiver< VF, EF, DF >::vf_ private
Definition at line 172 of file receiver.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/pushmi/receiver.h