proxygen: testing::internal::RefMatcher< T & > Class Template Reference
testing::internal::RefMatcher< T & > Class Template Reference
#include <gmock-matchers.h>
Classes
class Impl
Public Member Functions
RefMatcher (T &x)
template<typename Super >
operator Matcher< Super & > () const
RefMatcher (T &x)
template<typename Super >
operator Matcher< Super & > () const
RefMatcher (T &x)
template<typename Super >
operator Matcher< Super & > () const
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (RefMatcher)
GTEST_DISALLOW_ASSIGN_ (RefMatcher)
GTEST_DISALLOW_ASSIGN_ (RefMatcher)
Private Attributes
T & object_
Detailed Description
template<typename T>
class testing::internal::RefMatcher< T & >
Definition at line 1032 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename T > testing::internal::RefMatcher< T & >::RefMatcher (T & x) inline explicit
Definition at line 1042 of file gmock-matchers.h.
 : object_(x) {}  // NOLINT
template<typename T > testing::internal::RefMatcher< T & >::RefMatcher (T & x) inline explicit
Definition at line 1042 of file gmock-matchers.h.
 : object_(x) {}  // NOLINT
template<typename T > testing::internal::RefMatcher< T & >::RefMatcher (T & x) inline explicit
Definition at line 1042 of file gmock-matchers.h.
 : object_(x) {}  // NOLINT
Member Function Documentation
template<typename T > testing::internal::RefMatcher< T & >::GTEST_DISALLOW_ASSIGN_ (RefMatcher< T & >) private
template<typename T > testing::internal::RefMatcher< T & >::GTEST_DISALLOW_ASSIGN_ (RefMatcher< T & >) private
template<typename T > testing::internal::RefMatcher< T & >::GTEST_DISALLOW_ASSIGN_ (RefMatcher< T & >) private
template<typename T > template<typename Super > testing::internal::RefMatcher< T & >::operator Matcher< Super & > () const inline
Definition at line 1045 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     // By passing object_ (type T&) to Impl(), which expects a Super&,
     // we make sure that Super is a super type of T.  In particular,
     // this catches using Ref(const_value) as a matcher for a
     // non-const reference, as you cannot implicitly convert a const
     // reference to a non-const reference.
     return MakeMatcher(new Impl<Super>(object_));
   }
template<typename T > template<typename Super > testing::internal::RefMatcher< T & >::operator Matcher< Super & > () const inline
Definition at line 1045 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     // By passing object_ (type T&) to Impl(), which expects a Super&,
     // we make sure that Super is a super type of T.  In particular,
     // this catches using Ref(const_value) as a matcher for a
     // non-const reference, as you cannot implicitly convert a const
     // reference to a non-const reference.
     return MakeMatcher(new Impl<Super>(object_));
   }
template<typename T > template<typename Super > testing::internal::RefMatcher< T & >::operator Matcher< Super & > () const inline
Definition at line 1045 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     // By passing object_ (type T&) to Impl(), which expects a Super&,
     // we make sure that Super is a super type of T.  In particular,
     // this catches using Ref(const_value) as a matcher for a
     // non-const reference, as you cannot implicitly convert a const
     // reference to a non-const reference.
     return MakeMatcher(new Impl<Super>(object_));
   }
Member Data Documentation
template<typename T > T & testing::internal::RefMatcher< T & >::object_ private
Definition at line 1084 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h