proxygen: wangle::ClientHelloExtStats Class Reference
wangle::ClientHelloExtStats Class Reference abstract
#include <ClientHelloExtStats.h>
Public Member Functions
virtual ~ClientHelloExtStats () noexcept
virtual void recordAbsentHostname () noexcept=0
virtual void recordMatch () noexcept=0
virtual void recordNotMatch () noexcept=0
virtual void recordCertCrypto (CertCrypto requested, CertCrypto served) noexcept=0
Detailed Description
Definition at line 22 of file ClientHelloExtStats.h.
Constructor & Destructor Documentation
virtual wangle::ClientHelloExtStats::~ClientHelloExtStats () inline virtual noexcept
Definition at line 24 of file ClientHelloExtStats.h.
References folly::pushmi::__adl::noexcept(), recordAbsentHostname(), recordCertCrypto(), recordMatch(), and recordNotMatch().
 {}
Member Function Documentation
virtual void wangle::ClientHelloExtStats::recordAbsentHostname () pure virtual noexcept
Referenced by wangle::SSLContextManager::addSSLContextConfig(), and ~ClientHelloExtStats().
virtual void wangle::ClientHelloExtStats::recordCertCrypto (CertCrypto requested, CertCrypto served) pure virtual noexcept
Referenced by wangle::SSLContextManager::addSSLContextConfig(), and ~ClientHelloExtStats().
virtual void wangle::ClientHelloExtStats::recordMatch () pure virtual noexcept
Referenced by wangle::SSLContextManager::addSSLContextConfig(), and ~ClientHelloExtStats().
virtual void wangle::ClientHelloExtStats::recordNotMatch () pure virtual noexcept
Referenced by wangle::SSLContextManager::addSSLContextConfig(), and ~ClientHelloExtStats().
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/ssl/ClientHelloExtStats.h