proxygen: HTTP2UpstreamSessionWithVirtualNodesTest Class Reference
HTTP2UpstreamSessionWithVirtualNodesTest Class Reference
Public Member Functions
void SetUp () override
void commonSetUp (unique_ptr< HTTPCodec > codec)
void TearDown () override
Public Member Functions inherited from HTTPUpstreamTest< MockHTTPCodecPair >
HTTPUpstreamTest (std::vector< int64_t > flowControl={-1,-1,-1})
void resumeWrites ()
virtual void onWriteChain (folly::AsyncTransportWrapper::WriteCallback *callback, std::shared_ptr< IOBuf > iob, WriteFlags)
void handleWrite (folly::AsyncTransportWrapper::WriteCallback *callback)
void SetUp () override
void commonSetUp (unique_ptr< HTTPCodec > codec)
unique_ptr< typename MockHTTPCodecPair::Codec > makeServerCodec ()
void enableExHeader (typename MockHTTPCodecPair::Codec *serverCodec)
void parseOutput (HTTPCodec &serverCodec)
void readAndLoop (const std::string &input)
void readAndLoop (IOBuf *buf)
void readAndLoop (const uint8_t *input, size_t length)
void testBasicRequest ()
void testBasicRequestHttp10 (bool keepalive)
void onCreate (const HTTPSessionBase &) override
void onDestroy (const HTTPSessionBase &) override
void onSettingsOutgoingStreamsFull (const HTTPSessionBase &) override
void onSettingsOutgoingStreamsNotFull (const HTTPSessionBase &) override
void TearDown () override
std::unique_ptr< StrictMock< MockHTTPHandler > > openTransaction (bool expectStartPaused=false)
std::unique_ptr< NiceMock< MockHTTPHandler > > openNiceTransaction (bool expectStartPaused=false)
void testSimpleUpgrade (const std::string &upgradeReqHeader, const std::string &upgradeRespHeader, CodecProtocol respCodecVersion)
MockByteEventTracker * setMockByteEventTracker ()
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Protected Attributes
MockHTTPCodec * codecPtr_ {nullptr}
HTTPCodec::Callback * codecCb_ {nullptr}
uint32_t nextOutgoingTxn_ {1}
std::vector< HTTPCodec::StreamID > dependencies
uint8_t level_ {3}
std::shared_ptr< TestPriorityMapBuilder > builder_
Protected Attributes inherited from HTTPUpstreamTest< MockHTTPCodecPair >
bool sessionCreated_
bool sessionDestroyed_
bool transactionsFull_
bool transportGood_
EventBase eventBase_
EventBase * eventBasePtr_
MockAsyncTransport * transport_
folly::AsyncTransportWrapper::ReadCallback * readCallback_
folly::AsyncTransport::ReplaySafetyCallback * replaySafetyCallback_
folly::HHWheelTimer::UniquePtr transactionTimeouts_
std::vector< int64_t > flowControl_
wangle::TransportInfo mockTransportInfo_
SocketAddress localAddr_
SocketAddress peerAddr_
HTTPUpstreamSession * httpSession_
IOBufQueue writes_
std::vector< folly::AsyncTransportWrapper::WriteCallback * > cbs_
bool failWrites_
bool pauseWrites_
bool writeInLoop_
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Protected Member Functions inherited from testing::Test
Test ()
Test ()
Test ()
Detailed Description
Definition at line 861 of file HTTPUpstreamSessionTest.cpp.
Member Function Documentation
void HTTP2UpstreamSessionWithVirtualNodesTest::commonSetUp (unique_ptr< HTTPCodec > codec) inline
Definition at line 884 of file HTTPUpstreamSessionTest.cpp.
References testing::_, ASSERT_EQ, testing::Assign(), EXPECT_CALL, folly::getEventBase(), testing::Invoke(), folly::gen::move, testing::Return(), and transport_.
{
     HTTPSession::setDefaultReadBufferLimit(65536);
     HTTPSession::setDefaultWriteBufferLimit(65536);
     EXPECT_CALL(*transport_, writeChain(_, _, _))
       .WillRepeatedly(Invoke(
             this,
             &HTTPUpstreamTest<MockHTTPCodecPair>::onWriteChain));
     EXPECT_CALL(*transport_, setReadCB(_))
       .WillRepeatedly(SaveArg<0>(&readCallback_));
     EXPECT_CALL(*transport_, getReadCB())
       .WillRepeatedly(Return(readCallback_));
     EXPECT_CALL(*transport_, getEventBase())
       .WillRepeatedly(Return(&eventBase_));
     EXPECT_CALL(*transport_, good())
       .WillRepeatedly(ReturnPointee(&transportGood_));
     EXPECT_CALL(*transport_, closeNow())
       .WillRepeatedly(Assign(&transportGood_, false));
     AsyncTransportWrapper::UniquePtr transportPtr(transport_);
     httpSession_ = new HTTPUpstreamSession(
       transactionTimeouts_.get(),
       std::move(transportPtr),
       localAddr_, peerAddr_,
       std::move(codec),
       mockTransportInfo_,
       this,
       level_,
       builder_);
     eventBase_.loop();
     ASSERT_EQ(this->sessionDestroyed_, false);
   }
void HTTP2UpstreamSessionWithVirtualNodesTest::SetUp () inline override virtual
Reimplemented from testing::Test.
Definition at line 864 of file HTTPUpstreamSessionTest.cpp.
References testing::_, codec, EXPECT_CALL, testing::Invoke(), folly::gen::move, and testing::Return().
{
     auto codec = std::make_unique<NiceMock<MockHTTPCodec>>();
     codecPtr_ = codec.get();
     EXPECT_CALL(*codec, supportsParallelRequests())
       .WillRepeatedly(Return(true));
     EXPECT_CALL(*codec, getTransportDirection())
       .WillRepeatedly(Return(TransportDirection::UPSTREAM));
     EXPECT_CALL(*codec, getProtocol())
       .WillRepeatedly(Return(CodecProtocol::HTTP_2));
     EXPECT_CALL(*codec, setCallback(_))
       .WillRepeatedly(SaveArg<0>(&codecCb_));
     EXPECT_CALL(*codec, createStream())
       .WillRepeatedly(Invoke([&] {
             auto ret = nextOutgoingTxn_;
             nextOutgoingTxn_ += 2;
             return ret;
           }));
     commonSetUp(std::move(codec));
   }
void HTTP2UpstreamSessionWithVirtualNodesTest::TearDown () inline override virtual
Reimplemented from testing::Test.
Definition at line 915 of file HTTPUpstreamSessionTest.cpp.
References EXPECT_TRUE.
{
     EXPECT_TRUE(sessionDestroyed_);
   }
Member Data Documentation
std::shared_ptr<TestPriorityMapBuilder> HTTP2UpstreamSessionWithVirtualNodesTest::builder_ protected
Definition at line 925 of file HTTPUpstreamSessionTest.cpp.
HTTPCodec::Callback* HTTP2UpstreamSessionWithVirtualNodesTest::codecCb_ {nullptr} protected
Definition at line 921 of file HTTPUpstreamSessionTest.cpp.
MockHTTPCodec* HTTP2UpstreamSessionWithVirtualNodesTest::codecPtr_ {nullptr} protected
Definition at line 920 of file HTTPUpstreamSessionTest.cpp.
std::vector<HTTPCodec::StreamID> HTTP2UpstreamSessionWithVirtualNodesTest::dependencies protected
Definition at line 923 of file HTTPUpstreamSessionTest.cpp.
uint8_t HTTP2UpstreamSessionWithVirtualNodesTest::level_ {3} protected
Definition at line 924 of file HTTPUpstreamSessionTest.cpp.
uint32_t HTTP2UpstreamSessionWithVirtualNodesTest::nextOutgoingTxn_ {1} protected
Definition at line 922 of file HTTPUpstreamSessionTest.cpp.
The documentation for this class was generated from the following file:
proxygen/lib/http/session/test/HTTPUpstreamSessionTest.cpp