proxygen: folly::detail::partial::Partial< F, Tuple > Class Template Reference
folly::detail::partial::Partial< F, Tuple > Class Template Reference
#include <Partial.h>
Public Member Functions
template<typename Callable , typename... Args>
Partial (PartialConstructFromCallable, Callable &&callable, Args &&...args)
template<typename... CArgs>
auto operator() (CArgs &&...cargs)&-> decltype(invokeForward(std::declval< Partial & >(), Indexes
std::declval ()...))
template<typename... CArgs>
auto operator() (CArgs &&...cargs) const &-> decltype(invokeForward(std::declval< const Partial & >(), Indexes
std::declval ()...))
template<typename... As>
auto operator() (As &&...a)&&-> decltype(invokeForward(std::declval< Partial && >(), Indexes
std::declval ()...))
template<typename... As>
auto operator() (As &&...as) const &&-> decltype(invokeForward(std::declval< const Partial && >(), Indexes
std::declval ()...))
Private Types
using Indexes = make_index_sequence< std::tuple_size< Tuple >{}>
Static Private Member Functions
template<typename Self , std::size_t... I, typename... Args>
static auto invokeForward (Self &&self, index_sequence< I... >, Args &&...args) -> decltype(invoke(std::declval< Self >().f_, std::get< I >(std::declval< Self >().stored_args_)..., std::declval< Args >()...))
Private Attributes
F f_
Tuple stored_args_
Detailed Description
template<typename F, typename Tuple>
class folly::detail::partial::Partial< F, Tuple >
Definition at line 35 of file Partial.h.
Member Typedef Documentation
template<typename F , typename Tuple > using folly::detail::partial::Partial< F, Tuple >::Indexes = make_index_sequence<std::tuple_size<Tuple>{}> private
Definition at line 36 of file Partial.h.
Constructor & Destructor Documentation
template<typename F , typename Tuple > template<typename Callable , typename... Args> folly::detail::partial::Partial< F, Tuple >::Partial (PartialConstructFromCallable , Callable && callable, Args &&... args) inline
Definition at line 52 of file Partial.h.
       : f_(std::forward<Callable>(callable)),
         stored_args_(std::forward<Args>(args)...) {}
Member Function Documentation
template<typename F , typename Tuple > template<typename Self , std::size_t... I, typename... Args> static auto folly::detail::partial::Partial< F, Tuple >::invokeForward (Self && self, index_sequence< I... > , Args &&... args) -> decltype(invoke(std::declval<Self>().f_, std::get<I>(std::declval<Self>().stored_args_)..., std::declval<Args>()...)) inline static private
Definition at line 39 of file Partial.h.
References testing::Args(), and folly::invoke().
{
     return invoke(
         std::forward<Self>(self).f_,
         std::get<I>(std::forward<Self>(self).stored_args_)...,
         std::forward<Args>(args)...);
   }
template<typename F , typename Tuple > template<typename... CArgs> auto folly::detail::partial::Partial< F, Tuple >::operator() (CArgs &&... cargs) -> decltype(invokeForward(std::declval<Partial&>(), Indexes inline
Definition at line 57 of file Partial.h.
              {},
template<typename F , typename Tuple > template<typename... CArgs> auto folly::detail::partial::Partial< F, Tuple >::operator() (CArgs &&... cargs) const -> decltype(invokeForward(std::declval<const Partial&>(), Indexes inline
Definition at line 64 of file Partial.h.
              {},
template<typename F , typename Tuple > template<typename... As> auto folly::detail::partial::Partial< F, Tuple >::operator() (As &&... a) -> decltype(invokeForward(std::declval<Partial&&>(), Indexes inline
Definition at line 71 of file Partial.h.
              {},
template<typename F , typename Tuple > template<typename... As> auto folly::detail::partial::Partial< F, Tuple >::operator() (As &&... as) const -> decltype(invokeForward(std::declval<const Partial&&>(), Indexes inline
Definition at line 78 of file Partial.h.
              {},
template<typename F , typename Tuple > folly::detail::partial::Partial< F, Tuple >::std::declval () inline
Definition at line 60 of file Partial.h.
{
     return invokeForward(*this, Indexes{}, std::forward<CArgs>(cargs)...);
   }
template<typename F , typename Tuple > folly::detail::partial::Partial< F, Tuple >::std::declval () inline
Definition at line 67 of file Partial.h.
{
     return invokeForward(*this, Indexes{}, std::forward<CArgs>(cargs)...);
   }
template<typename F , typename Tuple > folly::detail::partial::Partial< F, Tuple >::std::declval () inline
Definition at line 74 of file Partial.h.
References a, and folly::gen::move.
{
     return invokeForward(std::move(*this), Indexes{}, std::forward<As>(a)...);
   }
template<typename F , typename Tuple > folly::detail::partial::Partial< F, Tuple >::std::declval () inline
Definition at line 81 of file Partial.h.
References folly::gen::as(), and folly::gen::move.
{
     return invokeForward(std::move(*this), Indexes{}, std::forward<As>(as)...);
   }
Member Data Documentation
template<typename F , typename Tuple > F folly::detail::partial::Partial< F, Tuple >::f_ private
Definition at line 87 of file Partial.h.
template<typename F , typename Tuple > Tuple folly::detail::partial::Partial< F, Tuple >::stored_args_ private
Definition at line 90 of file Partial.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/functional/Partial.h