proxygen: folly::fibers::Fiber::LocalData Class Reference
folly::fibers::Fiber::LocalData Class Reference
Public Member Functions
LocalData ()
~LocalData ()
LocalData (const LocalData &other)
LocalData & operator= (const LocalData &other)
template<typename T >
T & get ()
void reset ()
template<typename T >
FOLLY_NOINLINE T & getSlow ()
template<typename T >
T & getSlow ()
Static Public Member Functions
static void * allocateHeapBuffer (size_t size)
static void freeHeapBuffer (void *buffer)
template<typename T >
static void dataCopyConstructor (void *, const void *)
template<typename T >
static void dataBufferDestructor (void *)
template<typename T >
static void dataHeapDestructor (void *)
Public Attributes
std::aligned_storage< kBufferSize >::type buffer_
size_t dataSize_
const std::type_info * dataType_
void(* dataDestructor_)(void *)
void(* dataCopyConstructor_)(void *, const void *)
void * data_ {nullptr}
Static Public Attributes
static constexpr size_t kBufferSize = 128
Detailed Description
Definition at line 131 of file Fiber.h.
Constructor & Destructor Documentation
folly::fibers::Fiber::LocalData::LocalData () inline
Definition at line 133 of file Fiber.h.
References operator=(), and ~LocalData().
 {}
folly::fibers::Fiber::LocalData::~LocalData ()
Definition at line 197 of file Fiber.cpp.
Referenced by LocalData().
{
   reset();
 }
folly::fibers::Fiber::LocalData::LocalData (const LocalData & other)
Definition at line 201 of file Fiber.cpp.
                                                 : data_(nullptr) {
   *this = other;
 }
Member Function Documentation
void * folly::fibers::Fiber::LocalData::allocateHeapBuffer (size_t size) static
Definition at line 236 of file Fiber.cpp.
References folly::size().
Referenced by get(), and operator=().
{
   return new char[size];
 }
template<typename T > void folly::fibers::Fiber::LocalData::dataBufferDestructor (void * ptr) static
Definition at line 66 of file Fiber-inl.h.
References ptr, and folly::T.
Referenced by get().
{
   reinterpret_cast<T*>(ptr)->~T();
 }
template<typename T > void folly::fibers::Fiber::LocalData::dataCopyConstructor (void * ptr, const void * other) static
Definition at line 61 of file Fiber-inl.h.
References ptr, and folly::T.
Referenced by get().
{
   new (reinterpret_cast<T*>(ptr)) T(*reinterpret_cast<const T*>(other));
 }
template<typename T > void folly::fibers::Fiber::LocalData::dataHeapDestructor (void * ptr) static
Definition at line 71 of file Fiber-inl.h.
References ptr, and folly::T.
Referenced by get().
{
   reinterpret_cast<T*>(ptr)->~T();
   freeHeapBuffer(ptr);
 }
void folly::fibers::Fiber::LocalData::freeHeapBuffer (void * buffer) static
Definition at line 240 of file Fiber.cpp.
References buffer().
Referenced by get().
{
   delete[] reinterpret_cast<char*>(buffer);
 }
template<typename T > T& folly::fibers::Fiber::LocalData::get () inline
Definition at line 139 of file Fiber.h.
References allocateHeapBuffer(), buffer(), data_, dataBufferDestructor(), dataCopyConstructor(), dataHeapDestructor(), dataType_, FOLLY_NOINLINE, freeHeapBuffer(), getSlow(), reset(), folly::size(), and folly::T.
Referenced by folly::fibers::FiberManager::local().
              {
       if (data_) {
         assert(*dataType_ == typeid(T));
         return *reinterpret_cast<T*>(data_);
       }
       return getSlow<T>();
     }
template<typename T > T& folly::fibers::Fiber::LocalData::getSlow ()
Definition at line 43 of file Fiber-inl.h.
References buffer_, data_, kBufferSize, and folly::T.
{
   dataSize_ = sizeof(T);
   dataType_ = &typeid(T);
   if (sizeof(T) <= kBufferSize) {
     dataDestructor_ = dataBufferDestructor<T>;
     data_ = &buffer_;
   } else {
     dataDestructor_ = dataHeapDestructor<T>;
     data_ = allocateHeapBuffer(dataSize_);
   }
   dataCopyConstructor_ = dataCopyConstructor<T>;
   new (reinterpret_cast<T*>(data_)) T();
   return *reinterpret_cast<T*>(data_);
 }
template<typename T > FOLLY_NOINLINE T& folly::fibers::Fiber::LocalData::getSlow ()
Referenced by get().
Fiber::LocalData & folly::fibers::Fiber::LocalData::operator= (const LocalData & other)
Definition at line 205 of file Fiber.cpp.
References allocateHeapBuffer(), buffer_, data_, dataCopyConstructor_, dataDestructor_, dataSize_, dataType_, kBufferSize, and reset().
Referenced by LocalData().
{
   reset();
   if (!other.data_) {
     return *this;
   }
   dataSize_ = other.dataSize_;
   dataType_ = other.dataType_;
   dataDestructor_ = other.dataDestructor_;
   dataCopyConstructor_ = other.dataCopyConstructor_;
   if (dataSize_ <= kBufferSize) {
     data_ = &buffer_;
   } else {
     data_ = allocateHeapBuffer(dataSize_);
   }
   dataCopyConstructor_(data_, other.data_);
   return *this;
 }
void folly::fibers::Fiber::LocalData::reset ()
Definition at line 227 of file Fiber.cpp.
References data_, and dataDestructor_.
Referenced by get(), operator=(), and folly::fibers::FiberManager::runReadyFiber().
{
   if (!data_) {
     return;
   }
   dataDestructor_(data_);
   data_ = nullptr;
 }
Member Data Documentation
std::aligned_storage<kBufferSize>::type folly::fibers::Fiber::LocalData::buffer_
Definition at line 164 of file Fiber.h.
Referenced by operator=().
void* folly::fibers::Fiber::LocalData::data_ {nullptr}
Definition at line 170 of file Fiber.h.
Referenced by get(), operator=(), and reset().
void(* folly::fibers::Fiber::LocalData::dataCopyConstructor_) (void *, const void *)
Definition at line 169 of file Fiber.h.
Referenced by operator=().
void(* folly::fibers::Fiber::LocalData::dataDestructor_) (void *)
Definition at line 168 of file Fiber.h.
Referenced by operator=(), and reset().
size_t folly::fibers::Fiber::LocalData::dataSize_
Definition at line 165 of file Fiber.h.
Referenced by operator=().
const std::type_info* folly::fibers::Fiber::LocalData::dataType_
Definition at line 167 of file Fiber.h.
Referenced by get(), and operator=().
constexpr size_t folly::fibers::Fiber::LocalData::kBufferSize = 128 static
Definition at line 163 of file Fiber.h.
Referenced by operator=().
The documentation for this class was generated from the following files:
proxygen/folly/folly/fibers/Fiber.h
proxygen/folly/folly/fibers/Fiber-inl.h
proxygen/folly/folly/fibers/Fiber.cpp