proxygen: testing::internal::TestEventListenersAccessor Class Reference
testing::internal::TestEventListenersAccessor Class Reference
Static Public Member Functions
static TestEventListener * GetRepeater (TestEventListeners *listeners)
static void SetDefaultResultPrinter (TestEventListeners *listeners, TestEventListener *listener)
static void SetDefaultXmlGenerator (TestEventListeners *listeners, TestEventListener *listener)
static bool EventForwardingEnabled (const TestEventListeners &listeners)
static void SuppressEventForwarding (TestEventListeners *listeners)
static TestEventListener * GetRepeater (TestEventListeners *listeners)
static void SetDefaultResultPrinter (TestEventListeners *listeners, TestEventListener *listener)
static void SetDefaultXmlGenerator (TestEventListeners *listeners, TestEventListener *listener)
static bool EventForwardingEnabled (const TestEventListeners &listeners)
static void SuppressEventForwarding (TestEventListeners *listeners)
static TestEventListener * GetRepeater (TestEventListeners *listeners)
static void SetDefaultResultPrinter (TestEventListeners *listeners, TestEventListener *listener)
static void SetDefaultXmlGenerator (TestEventListeners *listeners, TestEventListener *listener)
static bool EventForwardingEnabled (const TestEventListeners &listeners)
static void SuppressEventForwarding (TestEventListeners *listeners)
Detailed Description
Definition at line 160 of file gtest_unittest.cc.
Member Function Documentation
static bool testing::internal::TestEventListenersAccessor::EventForwardingEnabled (const TestEventListeners & listeners) inline static
Definition at line 175 of file gtest_unittest.cc.
References testing::TestEventListeners::EventForwardingEnabled().
Referenced by TEST().
{
     return listeners.EventForwardingEnabled();
   }
static bool testing::internal::TestEventListenersAccessor::EventForwardingEnabled (const TestEventListeners & listeners) inline static
Definition at line 175 of file gtest_unittest.cc.
References testing::TestEventListeners::EventForwardingEnabled().
{
     return listeners.EventForwardingEnabled();
   }
static bool testing::internal::TestEventListenersAccessor::EventForwardingEnabled (const TestEventListeners & listeners) inline static
Definition at line 175 of file gtest_unittest.cc.
References testing::TestEventListeners::EventForwardingEnabled().
{
     return listeners.EventForwardingEnabled();
   }
static TestEventListener* testing::internal::TestEventListenersAccessor::GetRepeater (TestEventListeners * listeners) inline static
Definition at line 162 of file gtest_unittest.cc.
References testing::TestEventListeners::repeater().
Referenced by TEST().
{
     return listeners->repeater();
   }
static TestEventListener* testing::internal::TestEventListenersAccessor::GetRepeater (TestEventListeners * listeners) inline static
Definition at line 162 of file gtest_unittest.cc.
References testing::TestEventListeners::repeater().
{
     return listeners->repeater();
   }
static TestEventListener* testing::internal::TestEventListenersAccessor::GetRepeater (TestEventListeners * listeners) inline static
Definition at line 162 of file gtest_unittest.cc.
References testing::TestEventListeners::repeater().
{
     return listeners->repeater();
   }
static void testing::internal::TestEventListenersAccessor::SetDefaultResultPrinter (TestEventListeners * listeners, TestEventListener * listener) inline static
Definition at line 166 of file gtest_unittest.cc.
References testing::TestEventListeners::SetDefaultResultPrinter().
Referenced by TEST().
{
     listeners->SetDefaultResultPrinter(listener);
   }
static void testing::internal::TestEventListenersAccessor::SetDefaultResultPrinter (TestEventListeners * listeners, TestEventListener * listener) inline static
Definition at line 166 of file gtest_unittest.cc.
References testing::TestEventListeners::SetDefaultResultPrinter().
{
     listeners->SetDefaultResultPrinter(listener);
   }
static void testing::internal::TestEventListenersAccessor::SetDefaultResultPrinter (TestEventListeners * listeners, TestEventListener * listener) inline static
Definition at line 166 of file gtest_unittest.cc.
References testing::TestEventListeners::SetDefaultResultPrinter().
{
     listeners->SetDefaultResultPrinter(listener);
   }
static void testing::internal::TestEventListenersAccessor::SetDefaultXmlGenerator (TestEventListeners * listeners, TestEventListener * listener) inline static
Definition at line 170 of file gtest_unittest.cc.
References testing::TestEventListeners::SetDefaultXmlGenerator().
Referenced by TEST().
{
     listeners->SetDefaultXmlGenerator(listener);
   }
static void testing::internal::TestEventListenersAccessor::SetDefaultXmlGenerator (TestEventListeners * listeners, TestEventListener * listener) inline static
Definition at line 170 of file gtest_unittest.cc.
References testing::TestEventListeners::SetDefaultXmlGenerator().
{
     listeners->SetDefaultXmlGenerator(listener);
   }
static void testing::internal::TestEventListenersAccessor::SetDefaultXmlGenerator (TestEventListeners * listeners, TestEventListener * listener) inline static
Definition at line 170 of file gtest_unittest.cc.
References testing::TestEventListeners::SetDefaultXmlGenerator().
{
     listeners->SetDefaultXmlGenerator(listener);
   }
static void testing::internal::TestEventListenersAccessor::SuppressEventForwarding (TestEventListeners * listeners) inline static
Definition at line 179 of file gtest_unittest.cc.
References testing::TestEventListeners::SuppressEventForwarding().
{
     listeners->SuppressEventForwarding();
   }
static void testing::internal::TestEventListenersAccessor::SuppressEventForwarding (TestEventListeners * listeners) inline static
Definition at line 179 of file gtest_unittest.cc.
References testing::TestEventListeners::SuppressEventForwarding().
{
     listeners->SuppressEventForwarding();
   }
static void testing::internal::TestEventListenersAccessor::SuppressEventForwarding (TestEventListeners * listeners) inline static
Definition at line 179 of file gtest_unittest.cc.
References testing::TestEventListeners::SuppressEventForwarding().
Referenced by TEST().
{
     listeners->SuppressEventForwarding();
   }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest_unittest.cc