proxygen: folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor Class Reference
folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor Class Reference
#include <ThreadLocal.h>
Classes
class Iterator
Public Member Functions
~Accessor ()
Iterator begin () const
Iterator end () const
Accessor (const Accessor &)=delete
Accessor & operator= (const Accessor &)=delete
Accessor (Accessor &&other) noexcept
Accessor & operator= (Accessor &&other) noexcept
Accessor ()
Private Member Functions
Accessor (uint32_t id)
void release ()
Private Attributes
threadlocal_detail::StaticMetaBase & meta_
SharedMutex * accessAllThreadsLock_
std::mutex * lock_
uint32_t id_
Friends
class ThreadLocalPtr< T, Tag, AccessMode >
class Iterator
Detailed Description
template<class T, class Tag = void, class AccessMode = void>
class folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor
Definition at line 247 of file ThreadLocal.h.
Constructor & Destructor Documentation
template<class T, class Tag = void, class AccessMode = void> folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::~Accessor () inline
Definition at line 367 of file ThreadLocal.h.
                 {
       release();
     }
template<class T, class Tag = void, class AccessMode = void> folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Accessor (const Accessor &) delete
template<class T, class Tag = void, class AccessMode = void> folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Accessor (Accessor && other) inline noexcept
Definition at line 382 of file ThreadLocal.h.
         : meta_(other.meta_),
           accessAllThreadsLock_(other.accessAllThreadsLock_),
           lock_(other.lock_),
           id_(other.id_) {
       other.id_ = 0;
       other.accessAllThreadsLock_ = nullptr;
       other.lock_ = nullptr;
     }
template<class T, class Tag = void, class AccessMode = void> folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Accessor () inline
Definition at line 407 of file ThreadLocal.h.
         : meta_(threadlocal_detail::StaticMeta<Tag, AccessMode>::instance()),
           accessAllThreadsLock_(nullptr),
           lock_(nullptr),
           id_(0) {}
template<class T, class Tag = void, class AccessMode = void> folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Accessor (uint32_t id) inline explicit private
Definition at line 414 of file ThreadLocal.h.
References folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::lock().
         : meta_(threadlocal_detail::StaticMeta<Tag, AccessMode>::instance()),
           accessAllThreadsLock_(&meta_.accessAllThreadsLock_),
           lock_(&meta_.lock_) {
       accessAllThreadsLock_->lock();
       lock_->lock();
       id_ = id;
     }
Member Function Documentation
template<class T, class Tag = void, class AccessMode = void> Iterator folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::begin () const inline
Definition at line 371 of file ThreadLocal.h.
{
       return ++Iterator(this);
     }
template<class T, class Tag = void, class AccessMode = void> Iterator folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::end () const inline
Definition at line 375 of file ThreadLocal.h.
References folly::ThreadLocal< T, Tag, AccessMode >::operator=().
{
       return Iterator(this);
     }
template<class T, class Tag = void, class AccessMode = void> Accessor& folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::operator= (const Accessor &) delete
template<class T, class Tag = void, class AccessMode = void> Accessor& folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::operator= (Accessor && other) inline noexcept
Definition at line 392 of file ThreadLocal.h.
References folly::f14::swap(), and folly::swap().
{
       // Each Tag has its own unique meta, and accessors with different Tags
       // have different types.  So either *this is empty, or this and other
       // have the same tag.  But if they have the same tag, they have the same
       // meta (and lock), so they'd both hold the lock at the same time,
       // which is impossible, which leaves only one possible scenario --
       // *this is empty.  Assert it.
       assert(&meta_ == &other.meta_);
       assert(lock_ == nullptr);
       using std::swap;
       swap(accessAllThreadsLock_, other.accessAllThreadsLock_);
       swap(lock_, other.lock_);
       swap(id_, other.id_);
     }
template<class T, class Tag = void, class AccessMode = void> void folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::release () inline private
Definition at line 423 of file ThreadLocal.h.
References folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::unlock().
                    {
       if (lock_) {
         lock_->unlock();
         DCHECK(accessAllThreadsLock_ != nullptr);
         accessAllThreadsLock_->unlock();
         id_ = 0;
         lock_ = nullptr;
         accessAllThreadsLock_ = nullptr;
       }
     }
Friends And Related Function Documentation
template<class T, class Tag = void, class AccessMode = void> friend class Iterator friend
Definition at line 256 of file ThreadLocal.h.
template<class T, class Tag = void, class AccessMode = void> friend class ThreadLocalPtr< T, Tag, AccessMode > friend
Definition at line 248 of file ThreadLocal.h.
Member Data Documentation
template<class T, class Tag = void, class AccessMode = void> SharedMutex* folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::accessAllThreadsLock_ private
Definition at line 251 of file ThreadLocal.h.
template<class T, class Tag = void, class AccessMode = void> uint32_t folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::id_ private
Definition at line 253 of file ThreadLocal.h.
Referenced by folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::decrementToValid(), folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::dereference(), folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::equal(), folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::incrementToValid(), and folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::valid().
template<class T, class Tag = void, class AccessMode = void> std::mutex* folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::lock_ private
Definition at line 252 of file ThreadLocal.h.
template<class T, class Tag = void, class AccessMode = void> threadlocal_detail::StaticMetaBase& folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::meta_ private
Definition at line 250 of file ThreadLocal.h.
Referenced by folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::decrementToValid(), and folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::incrementToValid().
The documentation for this class was generated from the following file:
proxygen/folly/folly/ThreadLocal.h