proxygen: testing::InitGoogleTestTest Class Reference
testing::InitGoogleTestTest Class Reference
Protected Member Functions
virtual void SetUp ()
virtual void SetUp ()
virtual void SetUp ()
Protected Member Functions inherited from testing::Test
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Static Protected Member Functions
template<typename CharType >
static void AssertStringArrayEq (size_t size1, CharType **array1, size_t size2, CharType **array2)
static void CheckFlags (const Flags &expected)
template<typename CharType >
static void TestParsingFlags (int argc1, const CharType **argv1, int argc2, const CharType **argv2, const Flags &expected, bool should_print_help)
template<typename CharType >
static void AssertStringArrayEq (size_t size1, CharType **array1, size_t size2, CharType **array2)
static void CheckFlags (const Flags &expected)
template<typename CharType >
static void TestParsingFlags (int argc1, const CharType **argv1, int argc2, const CharType **argv2, const Flags &expected, bool should_print_help)
template<typename CharType >
static void AssertStringArrayEq (size_t size1, CharType **array1, size_t size2, CharType **array2)
static void CheckFlags (const Flags &expected)
template<typename CharType >
static void TestParsingFlags (int argc1, const CharType **argv1, int argc2, const CharType **argv2, const Flags &expected, bool should_print_help)
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Detailed Description
Definition at line 5605 of file gtest_unittest.cc.
Member Function Documentation
template<typename CharType > static void testing::InitGoogleTestTest::AssertStringArrayEq (size_t size1, CharType ** array1, size_t size2, CharType ** array2) inline static protected
Definition at line 5627 of file gtest_unittest.cc.
References ASSERT_EQ, ASSERT_STREQ, and i.
{
     ASSERT_EQ(size1, size2) << " Array sizes different.";
     for (size_t i = 0; i != size1; i++) {
       ASSERT_STREQ(array1[i], array2[i]) << " where i == " << i;
     }
   }
template<typename CharType > static void testing::InitGoogleTestTest::AssertStringArrayEq (size_t size1, CharType ** array1, size_t size2, CharType ** array2) inline static protected
Definition at line 5627 of file gtest_unittest.cc.
References ASSERT_EQ, ASSERT_STREQ, and i.
{
     ASSERT_EQ(size1, size2) << " Array sizes different.";
     for (size_t i = 0; i != size1; i++) {
       ASSERT_STREQ(array1[i], array2[i]) << " where i == " << i;
     }
   }
template<typename CharType > static void testing::InitGoogleTestTest::AssertStringArrayEq (size_t size1, CharType ** array1, size_t size2, CharType ** array2) inline static protected
Definition at line 5627 of file gtest_unittest.cc.
References ASSERT_EQ, ASSERT_STREQ, and i.
{
     ASSERT_EQ(size1, size2) << " Array sizes different.";
     for (size_t i = 0; i != size1; i++) {
       ASSERT_STREQ(array1[i], array2[i]) << " where i == " << i;
     }
   }
static void testing::InitGoogleTestTest::CheckFlags (const Flags & expected) inline static protected
Definition at line 5637 of file gtest_unittest.cc.
References testing::Flags::also_run_disabled_tests, testing::Flags::break_on_failure, testing::Flags::catch_exceptions, testing::Flags::death_test_use_fork, EXPECT_EQ, EXPECT_STREQ, folly::pushmi::operators::filter, testing::Flags::filter, GTEST_FLAG, testing::Flags::list_tests, gmock_output_test::output, testing::Flags::output, testing::Flags::print_time, testing::Flags::random_seed, repeat(), testing::Flags::repeat, testing::Flags::shuffle, testing::Flags::stack_trace_depth, testing::Flags::stream_result_to, and testing::Flags::throw_on_failure.
{
     EXPECT_EQ(expected.also_run_disabled_tests,
               GTEST_FLAG(also_run_disabled_tests));
     EXPECT_EQ(expected.break_on_failure, GTEST_FLAG(break_on_failure));
     EXPECT_EQ(expected.catch_exceptions, GTEST_FLAG(catch_exceptions));
     EXPECT_EQ(expected.death_test_use_fork, GTEST_FLAG(death_test_use_fork));
     EXPECT_STREQ(expected.filter, GTEST_FLAG(filter).c_str());
     EXPECT_EQ(expected.list_tests, GTEST_FLAG(list_tests));
     EXPECT_STREQ(expected.output, GTEST_FLAG(output).c_str());
     EXPECT_EQ(expected.print_time, GTEST_FLAG(print_time));
     EXPECT_EQ(expected.random_seed, GTEST_FLAG(random_seed));
     EXPECT_EQ(expected.repeat, GTEST_FLAG(repeat));
     EXPECT_EQ(expected.shuffle, GTEST_FLAG(shuffle));
     EXPECT_EQ(expected.stack_trace_depth, GTEST_FLAG(stack_trace_depth));
     EXPECT_STREQ(expected.stream_result_to,
                  GTEST_FLAG(stream_result_to).c_str());
     EXPECT_EQ(expected.throw_on_failure, GTEST_FLAG(throw_on_failure));
   }
static void testing::InitGoogleTestTest::CheckFlags (const Flags & expected) inline static protected
Definition at line 5637 of file gtest_unittest.cc.
References testing::Flags::also_run_disabled_tests, testing::Flags::break_on_failure, testing::Flags::catch_exceptions, testing::Flags::death_test_use_fork, EXPECT_EQ, EXPECT_STREQ, folly::pushmi::operators::filter, testing::Flags::filter, GTEST_FLAG, testing::Flags::list_tests, gmock_output_test::output, testing::Flags::output, testing::Flags::print_time, testing::Flags::random_seed, repeat(), testing::Flags::repeat, testing::Flags::shuffle, testing::Flags::stack_trace_depth, testing::Flags::stream_result_to, and testing::Flags::throw_on_failure.
{
     EXPECT_EQ(expected.also_run_disabled_tests,
               GTEST_FLAG(also_run_disabled_tests));
     EXPECT_EQ(expected.break_on_failure, GTEST_FLAG(break_on_failure));
     EXPECT_EQ(expected.catch_exceptions, GTEST_FLAG(catch_exceptions));
     EXPECT_EQ(expected.death_test_use_fork, GTEST_FLAG(death_test_use_fork));
     EXPECT_STREQ(expected.filter, GTEST_FLAG(filter).c_str());
     EXPECT_EQ(expected.list_tests, GTEST_FLAG(list_tests));
     EXPECT_STREQ(expected.output, GTEST_FLAG(output).c_str());
     EXPECT_EQ(expected.print_time, GTEST_FLAG(print_time));
     EXPECT_EQ(expected.random_seed, GTEST_FLAG(random_seed));
     EXPECT_EQ(expected.repeat, GTEST_FLAG(repeat));
     EXPECT_EQ(expected.shuffle, GTEST_FLAG(shuffle));
     EXPECT_EQ(expected.stack_trace_depth, GTEST_FLAG(stack_trace_depth));
     EXPECT_STREQ(expected.stream_result_to,
                  GTEST_FLAG(stream_result_to).c_str());
     EXPECT_EQ(expected.throw_on_failure, GTEST_FLAG(throw_on_failure));
   }
static void testing::InitGoogleTestTest::CheckFlags (const Flags & expected) inline static protected
Definition at line 5637 of file gtest_unittest.cc.
References testing::Flags::also_run_disabled_tests, testing::Flags::break_on_failure, testing::Flags::catch_exceptions, testing::Flags::death_test_use_fork, EXPECT_EQ, EXPECT_STREQ, folly::pushmi::operators::filter, testing::Flags::filter, GTEST_FLAG, testing::Flags::list_tests, gmock_output_test::output, testing::Flags::output, testing::Flags::print_time, testing::Flags::random_seed, repeat(), testing::Flags::repeat, testing::Flags::shuffle, testing::Flags::stack_trace_depth, testing::Flags::stream_result_to, and testing::Flags::throw_on_failure.
{
     EXPECT_EQ(expected.also_run_disabled_tests,
               GTEST_FLAG(also_run_disabled_tests));
     EXPECT_EQ(expected.break_on_failure, GTEST_FLAG(break_on_failure));
     EXPECT_EQ(expected.catch_exceptions, GTEST_FLAG(catch_exceptions));
     EXPECT_EQ(expected.death_test_use_fork, GTEST_FLAG(death_test_use_fork));
     EXPECT_STREQ(expected.filter, GTEST_FLAG(filter).c_str());
     EXPECT_EQ(expected.list_tests, GTEST_FLAG(list_tests));
     EXPECT_STREQ(expected.output, GTEST_FLAG(output).c_str());
     EXPECT_EQ(expected.print_time, GTEST_FLAG(print_time));
     EXPECT_EQ(expected.random_seed, GTEST_FLAG(random_seed));
     EXPECT_EQ(expected.repeat, GTEST_FLAG(repeat));
     EXPECT_EQ(expected.shuffle, GTEST_FLAG(shuffle));
     EXPECT_EQ(expected.stack_trace_depth, GTEST_FLAG(stack_trace_depth));
     EXPECT_STREQ(expected.stream_result_to,
                  GTEST_FLAG(stream_result_to).c_str());
     EXPECT_EQ(expected.throw_on_failure, GTEST_FLAG(throw_on_failure));
   }
virtual void testing::InitGoogleTestTest::SetUp () inline protected virtual
Reimplemented from testing::Test.
Definition at line 5608 of file gtest_unittest.cc.
References folly::pushmi::operators::filter, GTEST_FLAG, testing::kMaxStackTraceDepth, gmock_output_test::output, and repeat().
{
     GTEST_FLAG(also_run_disabled_tests) = false;
     GTEST_FLAG(break_on_failure) = false;
     GTEST_FLAG(catch_exceptions) = false;
     GTEST_FLAG(death_test_use_fork) = false;
     GTEST_FLAG(filter) = "";
     GTEST_FLAG(list_tests) = false;
     GTEST_FLAG(output) = "";
     GTEST_FLAG(print_time) = true;
     GTEST_FLAG(random_seed) = 0;
     GTEST_FLAG(repeat) = 1;
     GTEST_FLAG(shuffle) = false;
     GTEST_FLAG(stack_trace_depth) = kMaxStackTraceDepth;
     GTEST_FLAG(stream_result_to) = "";
     GTEST_FLAG(throw_on_failure) = false;
   }
virtual void testing::InitGoogleTestTest::SetUp () inline protected virtual
Reimplemented from testing::Test.
Definition at line 5608 of file gtest_unittest.cc.
References folly::pushmi::operators::filter, GTEST_FLAG, testing::kMaxStackTraceDepth, gmock_output_test::output, and repeat().
{
     GTEST_FLAG(also_run_disabled_tests) = false;
     GTEST_FLAG(break_on_failure) = false;
     GTEST_FLAG(catch_exceptions) = false;
     GTEST_FLAG(death_test_use_fork) = false;
     GTEST_FLAG(filter) = "";
     GTEST_FLAG(list_tests) = false;
     GTEST_FLAG(output) = "";
     GTEST_FLAG(print_time) = true;
     GTEST_FLAG(random_seed) = 0;
     GTEST_FLAG(repeat) = 1;
     GTEST_FLAG(shuffle) = false;
     GTEST_FLAG(stack_trace_depth) = kMaxStackTraceDepth;
     GTEST_FLAG(stream_result_to) = "";
     GTEST_FLAG(throw_on_failure) = false;
   }
virtual void testing::InitGoogleTestTest::SetUp () inline protected virtual
Reimplemented from testing::Test.
Definition at line 5608 of file gtest_unittest.cc.
References folly::pushmi::operators::filter, GTEST_FLAG, testing::kMaxStackTraceDepth, gmock_output_test::output, and repeat().
Referenced by testing::TEST_F().
{
     GTEST_FLAG(also_run_disabled_tests) = false;
     GTEST_FLAG(break_on_failure) = false;
     GTEST_FLAG(catch_exceptions) = false;
     GTEST_FLAG(death_test_use_fork) = false;
     GTEST_FLAG(filter) = "";
     GTEST_FLAG(list_tests) = false;
     GTEST_FLAG(output) = "";
     GTEST_FLAG(print_time) = true;
     GTEST_FLAG(random_seed) = 0;
     GTEST_FLAG(repeat) = 1;
     GTEST_FLAG(shuffle) = false;
     GTEST_FLAG(stack_trace_depth) = kMaxStackTraceDepth;
     GTEST_FLAG(stream_result_to) = "";
     GTEST_FLAG(throw_on_failure) = false;
   }
template<typename CharType > static void testing::InitGoogleTestTest::TestParsingFlags (int argc1, const CharType ** argv1, int argc2, const CharType ** argv2, const Flags & expected, bool should_print_help) inline static protected
Definition at line 5660 of file gtest_unittest.cc.
References testing::internal::CaptureStdout(), EXPECT_EQ, EXPECT_PRED_FORMAT2, testing::internal::g_help_flag, testing::internal::GetCapturedStdout(), testing::IsNotSubstring(), testing::IsSubstring(), testing::internal::ParseGoogleTestFlagsOnly(), and string.
{
     const bool saved_help_flag = ::testing::internal::g_help_flag;
     ::testing::internal::g_help_flag = false;
 #if GTEST_HAS_STREAM_REDIRECTION
     CaptureStdout();
 #endif
     // Parses the command line.
     internal::ParseGoogleTestFlagsOnly(&argc1, const_cast<CharType**>(argv1));
 #if GTEST_HAS_STREAM_REDIRECTION
     const std::string captured_stdout = GetCapturedStdout();
 #endif
     // Verifies the flag values.
     CheckFlags(expected);
     // Verifies that the recognized flags are removed from the command
     // line.
     AssertStringArrayEq(argc1 + 1, argv1, argc2 + 1, argv2);
     // ParseGoogleTestFlagsOnly should neither set g_help_flag nor print the
     // help message for the flags it recognizes.
     EXPECT_EQ(should_print_help, ::testing::internal::g_help_flag);
 #if GTEST_HAS_STREAM_REDIRECTION
     const char* const expected_help_fragment =
         "This program contains tests written using";
     if (should_print_help) {
       EXPECT_PRED_FORMAT2(IsSubstring, expected_help_fragment, captured_stdout);
     } else {
       EXPECT_PRED_FORMAT2(IsNotSubstring,
                           expected_help_fragment, captured_stdout);
     }
 #endif  // GTEST_HAS_STREAM_REDIRECTION
     ::testing::internal::g_help_flag = saved_help_flag;
   }
template<typename CharType > static void testing::InitGoogleTestTest::TestParsingFlags (int argc1, const CharType ** argv1, int argc2, const CharType ** argv2, const Flags & expected, bool should_print_help) inline static protected
Definition at line 5660 of file gtest_unittest.cc.
References testing::internal::CaptureStdout(), EXPECT_EQ, EXPECT_PRED_FORMAT2, testing::internal::g_help_flag, testing::internal::GetCapturedStdout(), testing::IsNotSubstring(), testing::IsSubstring(), testing::internal::ParseGoogleTestFlagsOnly(), and string.
{
     const bool saved_help_flag = ::testing::internal::g_help_flag;
     ::testing::internal::g_help_flag = false;
 #if GTEST_HAS_STREAM_REDIRECTION
     CaptureStdout();
 #endif
     // Parses the command line.
     internal::ParseGoogleTestFlagsOnly(&argc1, const_cast<CharType**>(argv1));
 #if GTEST_HAS_STREAM_REDIRECTION
     const std::string captured_stdout = GetCapturedStdout();
 #endif
     // Verifies the flag values.
     CheckFlags(expected);
     // Verifies that the recognized flags are removed from the command
     // line.
     AssertStringArrayEq(argc1 + 1, argv1, argc2 + 1, argv2);
     // ParseGoogleTestFlagsOnly should neither set g_help_flag nor print the
     // help message for the flags it recognizes.
     EXPECT_EQ(should_print_help, ::testing::internal::g_help_flag);
 #if GTEST_HAS_STREAM_REDIRECTION
     const char* const expected_help_fragment =
         "This program contains tests written using";
     if (should_print_help) {
       EXPECT_PRED_FORMAT2(IsSubstring, expected_help_fragment, captured_stdout);
     } else {
       EXPECT_PRED_FORMAT2(IsNotSubstring,
                           expected_help_fragment, captured_stdout);
     }
 #endif  // GTEST_HAS_STREAM_REDIRECTION
     ::testing::internal::g_help_flag = saved_help_flag;
   }
template<typename CharType > static void testing::InitGoogleTestTest::TestParsingFlags (int argc1, const CharType ** argv1, int argc2, const CharType ** argv2, const Flags & expected, bool should_print_help) inline static protected
Definition at line 5660 of file gtest_unittest.cc.
References testing::internal::CaptureStdout(), EXPECT_EQ, EXPECT_PRED_FORMAT2, testing::internal::g_help_flag, testing::internal::GetCapturedStdout(), testing::IsNotSubstring(), testing::IsSubstring(), testing::internal::ParseGoogleTestFlagsOnly(), and string.
{
     const bool saved_help_flag = ::testing::internal::g_help_flag;
     ::testing::internal::g_help_flag = false;
 #if GTEST_HAS_STREAM_REDIRECTION
     CaptureStdout();
 #endif
     // Parses the command line.
     internal::ParseGoogleTestFlagsOnly(&argc1, const_cast<CharType**>(argv1));
 #if GTEST_HAS_STREAM_REDIRECTION
     const std::string captured_stdout = GetCapturedStdout();
 #endif
     // Verifies the flag values.
     CheckFlags(expected);
     // Verifies that the recognized flags are removed from the command
     // line.
     AssertStringArrayEq(argc1 + 1, argv1, argc2 + 1, argv2);
     // ParseGoogleTestFlagsOnly should neither set g_help_flag nor print the
     // help message for the flags it recognizes.
     EXPECT_EQ(should_print_help, ::testing::internal::g_help_flag);
 #if GTEST_HAS_STREAM_REDIRECTION
     const char* const expected_help_fragment =
         "This program contains tests written using";
     if (should_print_help) {
       EXPECT_PRED_FORMAT2(IsSubstring, expected_help_fragment, captured_stdout);
     } else {
       EXPECT_PRED_FORMAT2(IsNotSubstring,
                           expected_help_fragment, captured_stdout);
     }
 #endif  // GTEST_HAS_STREAM_REDIRECTION
     ::testing::internal::g_help_flag = saved_help_flag;
   }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest_unittest.cc