proxygen: folly::test::TemporaryDirectory Class Reference
folly::test::TemporaryDirectory Class Reference
#include <TestUtil.h>
Public Types
enum Scope { Scope::PERMANENT, Scope::DELETE_ON_DESTRUCTION }
Public Member Functions
TemporaryDirectory (StringPiece namePrefix=StringPiece(), fs::path dir=fs::path(), Scope scope=Scope::DELETE_ON_DESTRUCTION)
~TemporaryDirectory ()
TemporaryDirectory (TemporaryDirectory &&)=default
TemporaryDirectory & operator= (TemporaryDirectory &&)=default
const fs::path & path () const
Private Attributes
Scope scope_
std::unique_ptr< fs::path > path_
Detailed Description
Temporary directory.
By default, the temporary directory is created in a system-specific location (the value of the TMPDIR environment variable, or /tmp), but you can override that with a non-empty directory passed to the constructor.
By default, the directory is recursively deleted when the TemporaryDirectory object is destroyed, but that can be overridden with an argument to the constructor.
Definition at line 100 of file TestUtil.h.
Member Enumeration Documentation
enum folly::test::TemporaryDirectory::Scope strong
Enumerator
PERMANENT
DELETE_ON_DESTRUCTION
Definition at line 102 of file TestUtil.h.
                    {
     PERMANENT,
     DELETE_ON_DESTRUCTION,
   };
Constructor & Destructor Documentation
folly::test::TemporaryDirectory::TemporaryDirectory (StringPiece namePrefix = StringPiece(), fs::path dir = fs::path(), Scope scope = Scope::DELETE_ON_DESTRUCTION) explicit
Definition at line 113 of file TestUtil.cpp.
References path().
     : scope_(scope),
       path_(std::make_unique<fs::path>(
           generateUniquePath(std::move(dir), namePrefix))) {
   fs::create_directory(path());
 }
folly::test::TemporaryDirectory::~TemporaryDirectory ()
Definition at line 123 of file TestUtil.cpp.
References DELETE_ON_DESTRUCTION, path(), path_, scope_, and folly::WARNING.
{
   if (scope_ == Scope::DELETE_ON_DESTRUCTION && path_ != nullptr) {
     boost::system::error_code ec;
     fs::remove_all(path(), ec);
     if (ec) {
       LOG(WARNING) << "recursive delete on destruction failed: " << ec;
     }
   }
 }
folly::test::TemporaryDirectory::TemporaryDirectory (TemporaryDirectory &&) default
Member Function Documentation
TemporaryDirectory& folly::test::TemporaryDirectory::operator= (TemporaryDirectory &&) default
const fs::path& folly::test::TemporaryDirectory::path () const inline
Definition at line 116 of file TestUtil.h.
References folly::test::TemporaryFile::path_.
Referenced by folly::test::ChangeToTempDir::ChangeToTempDir(), expectTempdirExists(), TemporaryDirectory(), folly::test::TEST(), TEST(), testTemporaryDirectory(), and ~TemporaryDirectory().
{
     return *path_;
   }
Member Data Documentation
std::unique_ptr<fs::path> folly::test::TemporaryDirectory::path_ private
Definition at line 122 of file TestUtil.h.
Referenced by ~TemporaryDirectory().
Scope folly::test::TemporaryDirectory::scope_ private
Definition at line 121 of file TestUtil.h.
Referenced by ~TemporaryDirectory().
The documentation for this class was generated from the following files:
proxygen/folly/folly/experimental/TestUtil.h
proxygen/folly/folly/experimental/TestUtil.cpp