proxygen: GenericFilterTest< Owned > Class Template Reference
GenericFilterTest< Owned > Class Template Reference
Public Member Functions
void basicTest ()
void testFilters (const std::deque< TestFilter< Owned > * > &filters, MockTesterCallback *expectedCb)
void SetUp () override
FilterChain< TesterInterface, TesterInterface::Callback, TestFilter< Owned >,&TesterInterface::setCallback, Owned > & chain ()
template<typename FilterT >
std::enable_if<!Owned, FilterT * >::type getFilter ()
template<typename FilterT >
std::enable_if< Owned, unique_ptr< FilterT > >::type getFilter ()
template<typename FilterT >
void addFilterToChain (std::deque< TestFilter< Owned > * > &refs)
std::deque< TestFilter< Owned > * > getRandomFilters (unsigned num)
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Public Attributes
MockTesterCallback callback_
unique_ptr< FilterChain< TesterInterface, TesterInterface::Callback, TestFilter< Owned >,&TesterInterface::setCallback, Owned > > chain_
MockTester * actor_ {nullptr}
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Protected Member Functions inherited from testing::Test
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Detailed Description
template<bool Owned>
class GenericFilterTest< Owned >
Definition at line 132 of file GenericFilterTest.cpp.
Member Function Documentation
template<bool Owned> template<typename FilterT > void GenericFilterTest< Owned >::addFilterToChain (std::deque< TestFilter< Owned > * > & refs) inline
Definition at line 165 of file GenericFilterTest.cpp.
References f, detail::get_pointer(), folly::gen::move, and refs.
{
     auto f = getFilter<FilterT>();
     refs.push_front(::detail::get_pointer(f));
     chain().addFilters(std::move(f));
   }
template<bool Owned> void GenericFilterTest< Owned >::basicTest ()
Definition at line 198 of file GenericFilterTest.cpp.
References callback_, and EXPECT_CALL.
{
   InSequence enforceOrder;
   // Test call side
   EXPECT_CALL(*actor_, doA());
   chain()->doA();
   // Now poke the callback side
   EXPECT_CALL(callback_, onA());
   CHECK_NOTNULL(actor_->cb_);
   actor_->cb_->onA();
 }
template<bool Owned> FilterChain<TesterInterface, TesterInterface::Callback, TestFilter<Owned>, &TesterInterface::setCallback, Owned>& GenericFilterTest< Owned >::chain () inline
Definition at line 150 of file GenericFilterTest.cpp.
{
     return *chain_;
   }
template<bool Owned> template<typename FilterT > std::enable_if<!Owned, FilterT*>::type GenericFilterTest< Owned >::getFilter () inline
Definition at line 155 of file GenericFilterTest.cpp.
{
     return new FilterT();
   }
template<bool Owned> template<typename FilterT > std::enable_if<Owned, unique_ptr<FilterT> >::type GenericFilterTest< Owned >::getFilter () inline
Definition at line 160 of file GenericFilterTest.cpp.
{
     return std::make_unique<FilterT>();
   }
template<bool Owned> std::deque<TestFilter<Owned>*> GenericFilterTest< Owned >::getRandomFilters (unsigned num) inline
Definition at line 171 of file GenericFilterTest.cpp.
References folly::basicTest(), and i.
{
     std::deque<TestFilter<Owned>*> filters;
     srand(0);
     for (unsigned i = 0; i < num; ++i) {
       auto r = rand() % 4;
       if (r == 0) {
         addFilterToChain<TestFilter<Owned>>(filters);
       } else if (r == 1) {
         addFilterToChain<TestFilterNoCall<Owned>>(filters);
       } else if (r == 2) {
         addFilterToChain<TestFilterNoCallback<Owned>>(filters);
       } else if (r == 3) {
         addFilterToChain<TestFilterNoCallbackNoCall<Owned>>(filters);
       }
       basicTest();
     }
     return filters;
   }
template<bool Owned> void GenericFilterTest< Owned >::SetUp () inline override virtual
Reimplemented from testing::Test.
Definition at line 139 of file GenericFilterTest.cpp.
References callback_, folly::make_unique(), and TesterInterface::setCallback().
{
     chain_ = std::make_unique<
       FilterChain<TesterInterface, TesterInterface::Callback,
                   TestFilter<Owned>,
                   &TesterInterface::setCallback,
                   Owned>>(getTester<Owned>());
     chain().setCallback(&callback_);
     actor_ = CHECK_NOTNULL(static_cast<MockTester*>(chain_->call()));
   }
template<bool Owned> void GenericFilterTest< Owned >::testFilters (const std::deque< TestFilter< Owned > * > & filters, MockTesterCallback * expectedCb)
Definition at line 211 of file GenericFilterTest.cpp.
References EXPECT_CALL, EXPECT_EQ, and f.
{
   for (auto f: filters) {
     f->do_ = 0;
     f->on_ = 0;
   }
   // Call
   EXPECT_CALL(*actor_, doA());
   chain()->doA();
   // Callback
   if (expectedCb) {
     EXPECT_CALL(*expectedCb, onA());
     CHECK_NOTNULL(actor_->cb_);
     actor_->cb_->onA();
   }
   for (auto f: filters) {
     if (f->kWantsCalls_) {
       EXPECT_EQ(f->do_, 1);
     } else {
       EXPECT_EQ(f->do_, 0);
     }
     if (f->kWantsCallbacks_) {
       EXPECT_EQ(f->on_, expectedCb ? 1 : 0);
     } else {
       EXPECT_EQ(f->on_, 0);
     }
   }
 }
Member Data Documentation
template<bool Owned> MockTester* GenericFilterTest< Owned >::actor_ {nullptr}
Definition at line 194 of file GenericFilterTest.cpp.
template<bool Owned> MockTesterCallback GenericFilterTest< Owned >::callback_
Definition at line 190 of file GenericFilterTest.cpp.
template<bool Owned> unique_ptr<FilterChain<TesterInterface, TesterInterface::Callback, TestFilter<Owned>, &TesterInterface::setCallback, Owned> > GenericFilterTest< Owned >::chain_
Definition at line 193 of file GenericFilterTest.cpp.
The documentation for this class was generated from the following file:
proxygen/lib/utils/test/GenericFilterTest.cpp