proxygen: folly::FormatValue< detail::DefaultValueWrapper< dynamic, V > > Class Template Reference
folly::FormatValue< detail::DefaultValueWrapper< dynamic, V > > Class Template Reference
#include <dynamic-inl.h>
Public Member Functions
FormatValue (const detail::DefaultValueWrapper< dynamic, V > &val)
template<class FormatCallback >
void format (FormatArg &arg, FormatCallback &cb) const
Private Attributes
const detail::DefaultValueWrapper< dynamic, V > & val_
Detailed Description
template<class V>
class folly::FormatValue< detail::DefaultValueWrapper< dynamic, V > >
Definition at line 1203 of file dynamic-inl.h.
Constructor & Destructor Documentation
template<class V > folly::FormatValue< detail::DefaultValueWrapper< dynamic, V > >::FormatValue (const detail::DefaultValueWrapper< dynamic, V > & val) inline explicit
Definition at line 1205 of file dynamic-inl.h.
       : val_(val) {}
Member Function Documentation
template<class V > template<class FormatCallback > void folly::FormatValue< detail::DefaultValueWrapper< dynamic, V > >::format (FormatArg & arg, FormatCallback & cb) const inline
Definition at line 1209 of file dynamic-inl.h.
References folly::dynamic::ARRAY, folly::dynamic::BOOL, c, folly::dynamic::DOUBLE, folly::format(), folly::dynamic::INT64, folly::dynamic::NULLT, folly::dynamic::OBJECT, folly::FormatArg::splitIntKey(), folly::FormatArg::splitKey(), and folly::dynamic::STRING.
{
     auto& c = val_.container;
     switch (c.type()) {
       case dynamic::NULLT:
       case dynamic::BOOL:
       case dynamic::INT64:
       case dynamic::STRING:
       case dynamic::DOUBLE:
         FormatValue<dynamic>(c).format(arg, cb);
         break;
       case dynamic::ARRAY: {
         int key = arg.splitIntKey();
         if (key >= 0 && size_t(key) < c.size()) {
           FormatValue<dynamic>(c.at(key)).format(arg, cb);
         } else {
           FormatValue<V>(val_.defaultValue).format(arg, cb);
         }
         break;
       }
       case dynamic::OBJECT: {
         auto pos = c.find(arg.splitKey());
         if (pos != c.items().end()) {
           FormatValue<dynamic>(pos->second).format(arg, cb);
         } else {
           FormatValue<V>(val_.defaultValue).format(arg, cb);
         }
         break;
       }
     }
   }
Member Data Documentation
template<class V > const detail::DefaultValueWrapper<dynamic, V>& folly::FormatValue< detail::DefaultValueWrapper< dynamic, V > >::val_ private
Definition at line 1241 of file dynamic-inl.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/dynamic-inl.h