proxygen: testing::internal::RE Class Reference
testing::internal::RE Class Reference
#include <gtest-port.h>
Public Member Functions
RE (const RE &other)
RE (const ::std::string &regex)
RE (const char *regex)
~RE ()
const char * pattern () const
RE (const RE &other)
RE (const ::std::string &regex)
RE (const char *regex)
~RE ()
const char * pattern () const
RE (const RE &other)
RE (const ::std::string &regex)
RE (const char *regex)
~RE ()
const char * pattern () const
Static Public Member Functions
static bool FullMatch (const ::std::string &str, const RE &re)
static bool PartialMatch (const ::std::string &str, const RE &re)
static bool FullMatch (const char *str, const RE &re)
static bool PartialMatch (const char *str, const RE &re)
static bool FullMatch (const ::std::string &str, const RE &re)
static bool PartialMatch (const ::std::string &str, const RE &re)
static bool FullMatch (const char *str, const RE &re)
static bool PartialMatch (const char *str, const RE &re)
static bool FullMatch (const ::std::string &str, const RE &re)
static bool PartialMatch (const ::std::string &str, const RE &re)
static bool FullMatch (const char *str, const RE &re)
static bool PartialMatch (const char *str, const RE &re)
Private Member Functions
void Init (const char *regex)
void operator= (RE const &)
void Init (const char *regex)
void operator= (RE const &)
void Init (const char *regex)
void operator= (RE const &)
Private Attributes
const char * pattern_
bool is_valid_
regex_t full_regex_
regex_t partial_regex_
Detailed Description
Definition at line 1156 of file gtest-port.h.
Constructor & Destructor Documentation
testing::internal::RE::RE (const RE & other) inline
Definition at line 1160 of file gtest-port.h.
References pattern().
 { Init(other.pattern()); }
testing::internal::RE::RE (const ::std::string & regex) inline
Definition at line 1163 of file gtest-port.h.
References regex, and string.
 { Init(regex.c_str()); }  // NOLINT
testing::internal::RE::RE (const char * regex) inline
Definition at line 1171 of file gtest-port.h.
 { Init(regex); }  // NOLINT
testing::internal::RE::~RE ()
Referenced by testing::internal::GetThreadCount().
testing::internal::RE::RE (const RE & other) inline
Definition at line 1160 of file gtest-port.h.
References pattern().
 { Init(other.pattern()); }
testing::internal::RE::RE (const ::std::string & regex) inline
Definition at line 1163 of file gtest-port.h.
References regex, and string.
 { Init(regex.c_str()); }  // NOLINT
testing::internal::RE::RE (const char * regex) inline
Definition at line 1171 of file gtest-port.h.
 { Init(regex); }  // NOLINT
testing::internal::RE::~RE ()
testing::internal::RE::RE (const RE & other) inline
Definition at line 1160 of file gtest-port.h.
References pattern().
 { Init(other.pattern()); }
testing::internal::RE::RE (const ::std::string & regex) inline
Definition at line 1163 of file gtest-port.h.
References regex, and string.
 { Init(regex.c_str()); }  // NOLINT
testing::internal::RE::RE (const char * regex) inline
Definition at line 1171 of file gtest-port.h.
 { Init(regex); }  // NOLINT
testing::internal::RE::~RE ()
Member Function Documentation
static bool testing::internal::RE::FullMatch (const ::std::string & str, const RE & re) inline static
Definition at line 1184 of file gtest-port.h.
Referenced by testing::internal::GetThreadCount(), testing::internal::TEST(), and testing::internal::To::To().
{
     return FullMatch(str.c_str(), re);
   }
static bool testing::internal::RE::FullMatch (const ::std::string & str, const RE & re) inline static
Definition at line 1184 of file gtest-port.h.
{
     return FullMatch(str.c_str(), re);
   }
static bool testing::internal::RE::FullMatch (const ::std::string & str, const RE & re) inline static
Definition at line 1184 of file gtest-port.h.
{
     return FullMatch(str.c_str(), re);
   }
static bool testing::internal::RE::FullMatch (const char * str, const RE & re) static
static bool testing::internal::RE::FullMatch (const char * str, const RE & re) static
static bool testing::internal::RE::FullMatch (const char * str, const RE & re) static
void testing::internal::RE::Init (const char * regex) private
void testing::internal::RE::Init (const char * regex) private
Referenced by testing::internal::GetThreadCount().
void testing::internal::RE::Init (const char * regex) private
void testing::internal::RE::operator= (RE const &) private
void testing::internal::RE::operator= (RE const &) private
void testing::internal::RE::operator= (RE const &) private
static bool testing::internal::RE::PartialMatch (const ::std::string & str, const RE & re) inline static
Definition at line 1187 of file gtest-port.h.
References testing::internal::FormatCompilerIndependentFileLocation(), testing::internal::FormatFileLocation(), GTEST_DISALLOW_ASSIGN_, and string.
{
     return PartialMatch(str.c_str(), re);
   }
static bool testing::internal::RE::PartialMatch (const ::std::string & str, const RE & re) inline static
Definition at line 1187 of file gtest-port.h.
References testing::internal::FormatCompilerIndependentFileLocation(), testing::internal::FormatFileLocation(), GTEST_DISALLOW_ASSIGN_, and string.
{
     return PartialMatch(str.c_str(), re);
   }
static bool testing::internal::RE::PartialMatch (const ::std::string & str, const RE & re) inline static
Definition at line 1187 of file gtest-port.h.
References string.
Referenced by testing::internal::GetThreadCount(), testing::internal::TEST(), and testing::internal::To::To().
{
     return PartialMatch(str.c_str(), re);
   }
static bool testing::internal::RE::PartialMatch (const char * str, const RE & re) static
static bool testing::internal::RE::PartialMatch (const char * str, const RE & re) static
static bool testing::internal::RE::PartialMatch (const char * str, const RE & re) static
const char* testing::internal::RE::pattern () const inline
Definition at line 1175 of file gtest-port.h.
 { return pattern_; }
const char* testing::internal::RE::pattern () const inline
Definition at line 1175 of file gtest-port.h.
Referenced by RE(), testing::internal::TEST(), and testing::internal::To::To().
 { return pattern_; }
const char* testing::internal::RE::pattern () const inline
Definition at line 1175 of file gtest-port.h.
 { return pattern_; }
Member Data Documentation
regex_t testing::internal::RE::full_regex_ private
Definition at line 1216 of file gtest-port.h.
Referenced by testing::internal::GetThreadCount().
bool testing::internal::RE::is_valid_ private
Definition at line 1212 of file gtest-port.h.
Referenced by testing::internal::GetThreadCount().
regex_t testing::internal::RE::partial_regex_ private
Definition at line 1217 of file gtest-port.h.
Referenced by testing::internal::GetThreadCount().
const char * testing::internal::RE::pattern_ private
Definition at line 1211 of file gtest-port.h.
Referenced by testing::internal::GetThreadCount().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h