proxygen: HTTP2FramerTest Class Reference
HTTP2FramerTest Class Reference
Public Member Functions
HTTP2FramerTest ()
template<typename ParseFunc , typename... Args>
void parse (ParseFunc &&parseFn, FrameHeader &outHeader, Args &&...outArgs)
template<typename ParseFunc , typename... Args>
void parse (const IOBuf *data, ParseFunc &&parseFn, FrameHeader &outHeader, Args &&...outArgs)
void dataFrameTest (uint32_t dataLen, folly::Optional< uint8_t > padLen)
void dataFrameTest (IOBuf *body, uint32_t dataLen, folly::Optional< uint8_t > padLen)
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Public Attributes
IOBufQueue queue_ {IOBufQueue::cacheChainLength()}
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Protected Member Functions inherited from testing::Test
Test ()
virtual void SetUp ()
virtual void TearDown ()
Test ()
virtual void SetUp ()
virtual void TearDown ()
Test ()
virtual void SetUp ()
virtual void TearDown ()
Detailed Description
Definition at line 36 of file HTTP2FramerTest.cpp.
Constructor & Destructor Documentation
HTTP2FramerTest::HTTP2FramerTest () inline
Definition at line 38 of file HTTP2FramerTest.cpp.
References testing::Args().
 {}
Member Function Documentation
void HTTP2FramerTest::dataFrameTest (uint32_t dataLen, folly::Optional< uint8_t > padLen) inline
Definition at line 55 of file HTTP2FramerTest.cpp.
References makeBuf().
{
     auto body = makeBuf(dataLen);
     dataFrameTest(body.get(), dataLen, padLen);
   }
void HTTP2FramerTest::dataFrameTest (IOBuf * body, uint32_t dataLen, folly::Optional< uint8_t > padLen) inline
Definition at line 60 of file HTTP2FramerTest.cpp.
References folly::IOBuf::clone(), EXPECT_DEATH_NO_CORE, EXPECT_EQ, proxygen::http2::kMaxFramePayloadLength, folly::IOBuf::moveToFbString(), parse(), proxygen::http2::parseData(), uint16_t, uint32_t, and proxygen::http2::writeData().
{
     uint32_t frameLen = uint32_t(dataLen);
     if (padLen) {
       frameLen += 1 + *padLen;
     }
     if (frameLen > kMaxFramePayloadLength) {
       EXPECT_DEATH_NO_CORE(writeData(queue_, body->clone(), 1, padLen,
                                      false, true), ".*");
     } else {
       writeData(queue_, body->clone(), 1, padLen, false, true);
       FrameHeader outHeader;
       std::unique_ptr<IOBuf> outBuf;
       uint16_t padding = 0;
       parse(&parseData, outHeader, outBuf, padding);
       EXPECT_EQ(outBuf->moveToFbString(), body->moveToFbString());
       EXPECT_EQ(padding, padLen ? (*padLen + 1) : 0);
     }
     queue_.move(); // reset everything
   }
template<typename ParseFunc , typename... Args> void HTTP2FramerTest::parse (ParseFunc && parseFn, FrameHeader & outHeader, Args &&... outArgs) inline
Definition at line 41 of file HTTP2FramerTest.cpp.
References testing::Args(), and parse().
{
     parse(queue_.front(), parseFn, outHeader, std::forward<Args>(outArgs)...);
   }
template<typename ParseFunc , typename... Args> void HTTP2FramerTest::parse (const IOBuf * data, ParseFunc && parseFn, FrameHeader & outHeader, Args &&... outArgs) inline
Definition at line 46 of file HTTP2FramerTest.cpp.
References ASSERT_EQ, and proxygen::http2::parseFrameHeader().
{
     Cursor cursor(data);
     auto ret1 = parseFrameHeader(cursor, outHeader);
     ASSERT_EQ(ret1, ErrorCode::NO_ERROR);
     auto ret2 = (*parseFn)(cursor, outHeader, std::forward<Args>(outArgs)...);
     ASSERT_EQ(ret2, ErrorCode::NO_ERROR);
   }
Member Data Documentation
IOBufQueue HTTP2FramerTest::queue_ {IOBufQueue::cacheChainLength()}
Definition at line 83 of file HTTP2FramerTest.cpp.
The documentation for this class was generated from the following file:
proxygen/lib/http/codec/test/HTTP2FramerTest.cpp