proxygen: testing::internal::StlContainerView< RawContainer > Class Template Reference
testing::internal::StlContainerView< RawContainer > Class Template Reference
#include <gmock-internal-utils.h>
Public Types
typedef RawContainer type
typedef const type & const_reference
typedef RawContainer type
typedef const type & const_reference
typedef RawContainer type
typedef const type & const_reference
Static Public Member Functions
static const_reference ConstReference (const RawContainer &container)
static type Copy (const RawContainer &container)
static const_reference ConstReference (const RawContainer &container)
static type Copy (const RawContainer &container)
static const_reference ConstReference (const RawContainer &container)
static type Copy (const RawContainer &container)
Detailed Description
template<class RawContainer>
class testing::internal::StlContainerView< RawContainer >
Definition at line 406 of file gmock-internal-utils.h.
Member Typedef Documentation
template<class RawContainer> typedef const type& testing::internal::StlContainerView< RawContainer >::const_reference
Definition at line 409 of file gmock-internal-utils.h.
template<class RawContainer> typedef const type& testing::internal::StlContainerView< RawContainer >::const_reference
Definition at line 409 of file gmock-internal-utils.h.
template<class RawContainer> typedef const type& testing::internal::StlContainerView< RawContainer >::const_reference
Definition at line 409 of file gmock-internal-utils.h.
template<class RawContainer> typedef RawContainer testing::internal::StlContainerView< RawContainer >::type
Definition at line 408 of file gmock-internal-utils.h.
template<class RawContainer> typedef RawContainer testing::internal::StlContainerView< RawContainer >::type
Definition at line 408 of file gmock-internal-utils.h.
template<class RawContainer> typedef RawContainer testing::internal::StlContainerView< RawContainer >::type
Definition at line 408 of file gmock-internal-utils.h.
Member Function Documentation
template<class RawContainer> static const_reference testing::internal::StlContainerView< RawContainer >::ConstReference (const RawContainer & container) inline static
Definition at line 411 of file gmock-internal-utils.h.
References GTEST_REMOVE_CONST_, and testing::StaticAssertTypeEq().
{
     // Ensures that RawContainer is not a const type.
     testing::StaticAssertTypeEq<RawContainer,
         GTEST_REMOVE_CONST_(RawContainer)>();
     return container;
   }
template<class RawContainer> static const_reference testing::internal::StlContainerView< RawContainer >::ConstReference (const RawContainer & container) inline static
Definition at line 411 of file gmock-internal-utils.h.
References GTEST_REMOVE_CONST_, and testing::StaticAssertTypeEq().
{
     // Ensures that RawContainer is not a const type.
     testing::StaticAssertTypeEq<RawContainer,
         GTEST_REMOVE_CONST_(RawContainer)>();
     return container;
   }
template<class RawContainer> static const_reference testing::internal::StlContainerView< RawContainer >::ConstReference (const RawContainer & container) inline static
Definition at line 411 of file gmock-internal-utils.h.
References GTEST_REMOVE_CONST_, and testing::StaticAssertTypeEq().
{
     // Ensures that RawContainer is not a const type.
     testing::StaticAssertTypeEq<RawContainer,
         GTEST_REMOVE_CONST_(RawContainer)>();
     return container;
   }
template<class RawContainer> static type testing::internal::StlContainerView< RawContainer >::Copy (const RawContainer & container) inline static
Definition at line 417 of file gmock-internal-utils.h.
References GTEST_REMOVE_CONST_.
 { return container; }
template<class RawContainer> static type testing::internal::StlContainerView< RawContainer >::Copy (const RawContainer & container) inline static
Definition at line 417 of file gmock-internal-utils.h.
 { return container; }
template<class RawContainer> static type testing::internal::StlContainerView< RawContainer >::Copy (const RawContainer & container) inline static
Definition at line 417 of file gmock-internal-utils.h.
References GTEST_REMOVE_CONST_.
 { return container; }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/internal/gmock-internal-utils.h