proxygen: testing::internal::StrEqualityMatcher< StringType > Class Template Reference
testing::internal::StrEqualityMatcher< StringType > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
StrEqualityMatcher (const StringType &str, bool expect_eq, bool case_sensitive)
template<typename CharType >
bool MatchAndExplain (CharType *s, MatchResultListener *listener) const
template<typename MatcheeStringType >
bool MatchAndExplain (const MatcheeStringType &s, MatchResultListener *) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
StrEqualityMatcher (const StringType &str, bool expect_eq, bool case_sensitive)
template<typename CharType >
bool MatchAndExplain (CharType *s, MatchResultListener *listener) const
template<typename MatcheeStringType >
bool MatchAndExplain (const MatcheeStringType &s, MatchResultListener *) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
StrEqualityMatcher (const StringType &str, bool expect_eq, bool case_sensitive)
template<typename CharType >
bool MatchAndExplain (CharType *s, MatchResultListener *listener) const
template<typename MatcheeStringType >
bool MatchAndExplain (const MatcheeStringType &s, MatchResultListener *) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
Private Member Functions
void DescribeToHelper (bool expect_eq,::std::ostream *os) const
GTEST_DISALLOW_ASSIGN_ (StrEqualityMatcher)
void DescribeToHelper (bool expect_eq,::std::ostream *os) const
GTEST_DISALLOW_ASSIGN_ (StrEqualityMatcher)
void DescribeToHelper (bool expect_eq,::std::ostream *os) const
GTEST_DISALLOW_ASSIGN_ (StrEqualityMatcher)
Private Attributes
const StringType string_
const bool expect_eq_
const bool case_sensitive_
Detailed Description
template<typename StringType>
class testing::internal::StrEqualityMatcher< StringType >
Definition at line 1126 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename StringType > testing::internal::StrEqualityMatcher< StringType >::StrEqualityMatcher (const StringType & str, bool expect_eq, bool case_sensitive) inline
Definition at line 1128 of file gmock-matchers.h.
       : string_(str), expect_eq_(expect_eq), case_sensitive_(case_sensitive) {}
template<typename StringType > testing::internal::StrEqualityMatcher< StringType >::StrEqualityMatcher (const StringType & str, bool expect_eq, bool case_sensitive) inline
Definition at line 1128 of file gmock-matchers.h.
       : string_(str), expect_eq_(expect_eq), case_sensitive_(case_sensitive) {}
template<typename StringType > testing::internal::StrEqualityMatcher< StringType >::StrEqualityMatcher (const StringType & str, bool expect_eq, bool case_sensitive) inline
Definition at line 1128 of file gmock-matchers.h.
       : string_(str), expect_eq_(expect_eq), case_sensitive_(case_sensitive) {}
Member Function Documentation
template<typename StringType > void testing::internal::StrEqualityMatcher< StringType >::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 1162 of file gmock-matchers.h.
{
     DescribeToHelper(!expect_eq_, os);
   }
template<typename StringType > void testing::internal::StrEqualityMatcher< StringType >::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 1162 of file gmock-matchers.h.
{
     DescribeToHelper(!expect_eq_, os);
   }
template<typename StringType > void testing::internal::StrEqualityMatcher< StringType >::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 1162 of file gmock-matchers.h.
{
     DescribeToHelper(!expect_eq_, os);
   }
template<typename StringType > void testing::internal::StrEqualityMatcher< StringType >::DescribeTo (::std::ostream * os) const inline
Definition at line 1158 of file gmock-matchers.h.
{
     DescribeToHelper(expect_eq_, os);
   }
template<typename StringType > void testing::internal::StrEqualityMatcher< StringType >::DescribeTo (::std::ostream * os) const inline
Definition at line 1158 of file gmock-matchers.h.
{
     DescribeToHelper(expect_eq_, os);
   }
template<typename StringType > void testing::internal::StrEqualityMatcher< StringType >::DescribeTo (::std::ostream * os) const inline
Definition at line 1158 of file gmock-matchers.h.
{
     DescribeToHelper(expect_eq_, os);
   }
template<typename StringType > void testing::internal::StrEqualityMatcher< StringType >::DescribeToHelper (bool expect_eq, ::std::ostream * os) const inline private
Definition at line 1167 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, and testing::internal::UniversalPrint().
{
     *os << (expect_eq ? "is " : "isn't ");
     *os << "equal to ";
     if (!case_sensitive_) {
       *os << "(ignoring case) ";
     }
     UniversalPrint(string_, os);
   }
template<typename StringType > void testing::internal::StrEqualityMatcher< StringType >::DescribeToHelper (bool expect_eq, ::std::ostream * os) const inline private
Definition at line 1167 of file gmock-matchers.h.
References testing::internal::UniversalPrint().
{
     *os << (expect_eq ? "is " : "isn't ");
     *os << "equal to ";
     if (!case_sensitive_) {
       *os << "(ignoring case) ";
     }
     UniversalPrint(string_, os);
   }
template<typename StringType > void testing::internal::StrEqualityMatcher< StringType >::DescribeToHelper (bool expect_eq, ::std::ostream * os) const inline private
Definition at line 1167 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, and testing::internal::UniversalPrint().
{
     *os << (expect_eq ? "is " : "isn't ");
     *os << "equal to ";
     if (!case_sensitive_) {
       *os << "(ignoring case) ";
     }
     UniversalPrint(string_, os);
   }
template<typename StringType > testing::internal::StrEqualityMatcher< StringType >::GTEST_DISALLOW_ASSIGN_ (StrEqualityMatcher< StringType >) private
template<typename StringType > testing::internal::StrEqualityMatcher< StringType >::GTEST_DISALLOW_ASSIGN_ (StrEqualityMatcher< StringType >) private
template<typename StringType > testing::internal::StrEqualityMatcher< StringType >::GTEST_DISALLOW_ASSIGN_ (StrEqualityMatcher< StringType >) private
template<typename StringType > template<typename CharType > bool testing::internal::StrEqualityMatcher< StringType >::MatchAndExplain (CharType * s, MatchResultListener * listener) const inline
Definition at line 1138 of file gmock-matchers.h.
{
     if (s == NULL) {
       return !expect_eq_;
     }
     return MatchAndExplain(StringType(s), listener);
   }
template<typename StringType > template<typename CharType > bool testing::internal::StrEqualityMatcher< StringType >::MatchAndExplain (CharType * s, MatchResultListener * listener) const inline
Definition at line 1138 of file gmock-matchers.h.
{
     if (s == NULL) {
       return !expect_eq_;
     }
     return MatchAndExplain(StringType(s), listener);
   }
template<typename StringType > template<typename CharType > bool testing::internal::StrEqualityMatcher< StringType >::MatchAndExplain (CharType * s, MatchResultListener * listener) const inline
Definition at line 1138 of file gmock-matchers.h.
{
     if (s == NULL) {
       return !expect_eq_;
     }
     return MatchAndExplain(StringType(s), listener);
   }
template<typename StringType > template<typename MatcheeStringType > bool testing::internal::StrEqualityMatcher< StringType >::MatchAndExplain (const MatcheeStringType & s, MatchResultListener *) const inline
Definition at line 1150 of file gmock-matchers.h.
References testing::internal::CaseInsensitiveStringEquals().
{
     const StringType& s2(s);
     const bool eq = case_sensitive_ ? s2 == string_ :
         CaseInsensitiveStringEquals(s2, string_);
     return expect_eq_ == eq;
   }
template<typename StringType > template<typename MatcheeStringType > bool testing::internal::StrEqualityMatcher< StringType >::MatchAndExplain (const MatcheeStringType & s, MatchResultListener *) const inline
Definition at line 1150 of file gmock-matchers.h.
References testing::internal::CaseInsensitiveStringEquals().
{
     const StringType& s2(s);
     const bool eq = case_sensitive_ ? s2 == string_ :
         CaseInsensitiveStringEquals(s2, string_);
     return expect_eq_ == eq;
   }
template<typename StringType > template<typename MatcheeStringType > bool testing::internal::StrEqualityMatcher< StringType >::MatchAndExplain (const MatcheeStringType & s, MatchResultListener *) const inline
Definition at line 1150 of file gmock-matchers.h.
References testing::internal::CaseInsensitiveStringEquals().
{
     const StringType& s2(s);
     const bool eq = case_sensitive_ ? s2 == string_ :
         CaseInsensitiveStringEquals(s2, string_);
     return expect_eq_ == eq;
   }
Member Data Documentation
template<typename StringType > const bool testing::internal::StrEqualityMatcher< StringType >::case_sensitive_ private
Definition at line 1178 of file gmock-matchers.h.
template<typename StringType > const bool testing::internal::StrEqualityMatcher< StringType >::expect_eq_ private
Definition at line 1177 of file gmock-matchers.h.
template<typename StringType > const StringType testing::internal::StrEqualityMatcher< StringType >::string_ private
Definition at line 1176 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h