proxygen: fizz::server::test::AsyncFizzServerTest Class Reference
fizz::server::test::AsyncFizzServerTest Class Reference
Public Member Functions
void SetUp () override
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Protected Member Functions
void expectTransportReadCallback ()
void expectAppClose ()
void accept ()
void fullHandshakeSuccess (std::shared_ptr< const Cert > clientCert=nullptr, std::shared_ptr< const Cert > serverCert=nullptr)
void completeHandshake ()
Protected Member Functions inherited from testing::Test
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Protected Attributes
AsyncFizzServerT< MockServerStateMachineInstance >::UniquePtr server_
std::shared_ptr< FizzServerContext > context_
MockAsyncTransport * socket_
MockServerStateMachineInstance * machine_
AsyncTransportWrapper::ReadCallback * socketReadCallback_
MockHandshakeCallbackT< MockServerStateMachineInstance > handshakeCallback_
MockReadCallback readCallback_
MockWriteCallback writeCallback_
EventBase evb_
CipherSuite negotiatedCipher_ = CipherSuite::TLS_AES_128_GCM_SHA256
ProtocolVersion protocolVersion_ = ProtocolVersion::tls_1_3
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Detailed Description
Definition at line 41 of file AsyncFizzServerTest.cpp.
Member Function Documentation
void fizz::server::test::AsyncFizzServerTest::accept () inline protected
Definition at line 77 of file AsyncFizzServerTest.cpp.
References testing::_, fizz::server::test::actions(), evb_, EXPECT_CALL, folly::getEventBase(), testing::InvokeWithoutArgs(), testing::Return(), and socket_.
                 {
     expectTransportReadCallback();
     EXPECT_CALL(*socket_, getEventBase()).WillOnce(Return(&evb_));
     EXPECT_CALL(*machine_, _processAccept(_, &evb_, _, _))
         .WillOnce(InvokeWithoutArgs([]() { return actions(); }));
     server_->accept(&handshakeCallback_);
   }
void fizz::server::test::AsyncFizzServerTest::completeHandshake () inline protected
Definition at line 110 of file AsyncFizzServerTest.cpp.
References folly::netops::accept(), and EXPECT_CALL.
{
     accept();
     EXPECT_CALL(handshakeCallback_, _fizzHandshakeSuccess());
     fullHandshakeSuccess();
   }
void fizz::server::test::AsyncFizzServerTest::expectAppClose () inline protected
Definition at line 62 of file AsyncFizzServerTest.cpp.
References testing::_, fizz::server::detail::actions(), fizz::alert, fizz::WriteToSocket::contents, fizz::TLSContent::contentType, folly::IOBuf::copyBuffer(), fizz::TLSContent::data, fizz::TLSContent::encryptionLevel, fizz::server::Error, EXPECT_CALL, fizz::Handshake, testing::InvokeWithoutArgs(), folly::gen::move, fizz::server::State::state(), and fizz::detail::write().
{
     EXPECT_CALL(*machine_, _processAppClose(_))
         .WillOnce(InvokeWithoutArgs([]() {
           WriteToSocket write;
           TLSContent record;
           record.contentType = ContentType::alert;
           record.encryptionLevel = EncryptionLevel::Handshake;
           record.data = IOBuf::copyBuffer("closenotify");
           write.contents.emplace_back(std::move(record));
           return detail::actions(
               [](State& newState) { newState.state() = StateEnum::Error; },
               std::move(write));
         }));
   }
void fizz::server::test::AsyncFizzServerTest::expectTransportReadCallback () inline protected
Definition at line 57 of file AsyncFizzServerTest.cpp.
References testing::_, EXPECT_CALL, and socket_.
{
     EXPECT_CALL(*socket_, setReadCB(_))
         .WillRepeatedly(SaveArg<0>(&socketReadCallback_));
   }
void fizz::server::test::AsyncFizzServerTest::fullHandshakeSuccess (std::shared_ptr< const Cert > clientCert = nullptr, std::shared_ptr< const Cert > serverCert = nullptr) inline protected
Definition at line 85 of file AsyncFizzServerTest.cpp.
References testing::_, fizz::server::test::actions(), cipher, clientCert, folly::IOBuf::copyBuffer(), EXPECT_CALL, testing::InvokeWithoutArgs(), folly::gen::move, and serverCert.
{
     EXPECT_CALL(*machine_, _processSocketData(_, _))
         .WillOnce(InvokeWithoutArgs([clientCert,
                                      serverCert,
                                      cipher = negotiatedCipher_,
                                      protocolVersion = protocolVersion_]() {
           auto addExporterToState = [=](State& newState) {
             auto exporterMaster =
                 folly::IOBuf::copyBuffer("12345678901234567890123456789012");
             newState.exporterMasterSecret() = std::move(exporterMaster);
             newState.cipher() = cipher;
             newState.version() = protocolVersion;
             newState.clientCert() = clientCert;
             newState.serverCert() = serverCert;
           };
           return actions(
               std::move(addExporterToState),
               ReportHandshakeSuccess(),
               WaitForData());
         }));
     socketReadCallback_->readBufferAvailable(IOBuf::copyBuffer("ClientHello"));
   }
void fizz::server::test::AsyncFizzServerTest::SetUp () inline override virtual
Reimplemented from testing::Test.
Definition at line 43 of file AsyncFizzServerTest.cpp.
References fizz::server::test::MockServerStateMachineInstance::instance, folly::gen::move, ON_CALL, testing::Return(), and socket_.
{
     context_ = std::make_shared<FizzServerContext>();
     socket_ = new MockAsyncTransport();
     auto transport = AsyncTransportWrapper::UniquePtr(socket_);
     server_.reset(new AsyncFizzServerT<MockServerStateMachineInstance>(
         std::move(transport),
         context_,
         std::make_shared<MockServerExtensions>()));
     machine_ = MockServerStateMachineInstance::instance;
     ON_CALL(*socket_, good()).WillByDefault(Return(true));
     ON_CALL(readCallback_, isBufferMovable_()).WillByDefault(Return(true));
   }
Member Data Documentation
std::shared_ptr<FizzServerContext> fizz::server::test::AsyncFizzServerTest::context_ protected
Definition at line 117 of file AsyncFizzServerTest.cpp.
EventBase fizz::server::test::AsyncFizzServerTest::evb_ protected
Definition at line 124 of file AsyncFizzServerTest.cpp.
MockHandshakeCallbackT<MockServerStateMachineInstance> fizz::server::test::AsyncFizzServerTest::handshakeCallback_ protected
Definition at line 121 of file AsyncFizzServerTest.cpp.
MockServerStateMachineInstance* fizz::server::test::AsyncFizzServerTest::machine_ protected
Definition at line 119 of file AsyncFizzServerTest.cpp.
CipherSuite fizz::server::test::AsyncFizzServerTest::negotiatedCipher_ = CipherSuite::TLS_AES_128_GCM_SHA256 protected
Definition at line 125 of file AsyncFizzServerTest.cpp.
ProtocolVersion fizz::server::test::AsyncFizzServerTest::protocolVersion_ = ProtocolVersion::tls_1_3 protected
Definition at line 126 of file AsyncFizzServerTest.cpp.
MockReadCallback fizz::server::test::AsyncFizzServerTest::readCallback_ protected
Definition at line 122 of file AsyncFizzServerTest.cpp.
AsyncFizzServerT<MockServerStateMachineInstance>::UniquePtr fizz::server::test::AsyncFizzServerTest::server_ protected
Definition at line 116 of file AsyncFizzServerTest.cpp.
MockAsyncTransport* fizz::server::test::AsyncFizzServerTest::socket_ protected
Definition at line 118 of file AsyncFizzServerTest.cpp.
AsyncTransportWrapper::ReadCallback* fizz::server::test::AsyncFizzServerTest::socketReadCallback_ protected
Definition at line 120 of file AsyncFizzServerTest.cpp.
MockWriteCallback fizz::server::test::AsyncFizzServerTest::writeCallback_ protected
Definition at line 123 of file AsyncFizzServerTest.cpp.
The documentation for this class was generated from the following file:
proxygen/fizz/fizz/server/test/AsyncFizzServerTest.cpp