proxygen: fizz::server::State Class Reference
fizz::server::State Class Reference
#include <State.h>
Public Member Functions
StateEnum state () const
folly::Executor * executor () const
const FizzServerContext * context () const
std::shared_ptr< const Cert > serverCert () const
const std::shared_ptr< const Cert > & clientCert () const
folly::Optional< ProtocolVersion > version () const
folly::Optional< CipherSuite > cipher () const
folly::Optional< NamedGroup > group () const
folly::Optional< SignatureScheme > sigScheme () const
folly::Optional< PskType > pskType () const
folly::Optional< PskKeyExchangeMode > pskMode () const
folly::Optional< KeyExchangeType > keyExchangeType () const
folly::Optional< EarlyDataType > earlyDataType () const
folly::Optional< ReplayCacheResult > replayCacheResult () const
const folly::Optional< std::string > & alpn () const
folly::Optional< std::chrono::milliseconds > clientClockSkew () const
const AppTokenValidator * appTokenValidator () const
HandshakeLogging * handshakeLogging () const
KeyScheduler * keyScheduler () const
ReadRecordLayer * readRecordLayer () const
const WriteRecordLayer * writeRecordLayer () const
const Buf & clientHandshakeSecret () const
ServerExtensions * extensions () const
const std::vector< uint8_t > & resumptionMasterSecret () const
const folly::Optional< std::vector< std::shared_ptr< const PeerCert > > > & unverifiedCertChain () const
const folly::Optional< CertificateCompressionAlgorithm > & serverCertCompAlgo () const
const folly::Optional< Buf > & earlyExporterMasterSecret () const
const folly::Optional< Buf > & exporterMasterSecret () const
auto & state ()
auto & executor ()
auto & context ()
auto & keyScheduler ()
auto & readRecordLayer ()
auto & writeRecordLayer ()
auto & handshakeReadRecordLayer () const
auto & handshakeContext () const
auto & serverCert ()
auto & clientCert ()
auto & serverCertCompAlgo ()
auto & unverifiedCertChain ()
auto & version ()
auto & cipher ()
auto & group ()
auto & sigScheme ()
auto & pskType ()
auto & pskMode ()
auto & keyExchangeType ()
auto & earlyDataType ()
auto & replayCacheResult ()
auto & clientHandshakeSecret ()
auto & alpn ()
auto & clientClockSkew ()
auto & appTokenValidator ()
auto & handshakeLogging ()
auto & extensions ()
auto & resumptionMasterSecret ()
auto & earlyExporterMasterSecret ()
auto & exporterMasterSecret ()
Private Attributes
StateEnum state_ {StateEnum::Uninitialized}
folly::Executor * executor_
std::shared_ptr< const FizzServerContext > context_
std::unique_ptr< KeyScheduler > keyScheduler_
std::unique_ptr< ReadRecordLayer > readRecordLayer_
std::unique_ptr< WriteRecordLayer > writeRecordLayer_
std::unique_ptr< EncryptedReadRecordLayer > handshakeReadRecordLayer_
std::unique_ptr< HandshakeContext > handshakeContext_
std::shared_ptr< const Cert > serverCert_
std::shared_ptr< const Cert > clientCert_
folly::Optional< CertificateCompressionAlgorithm > serverCertCompAlgo_
folly::Optional< std::vector< std::shared_ptr< const PeerCert > > > unverifiedCertChain_
folly::Optional< ProtocolVersion > version_
folly::Optional< CipherSuite > cipher_
folly::Optional< NamedGroup > group_
folly::Optional< SignatureScheme > sigScheme_
folly::Optional< PskType > pskType_
folly::Optional< PskKeyExchangeMode > pskMode_
folly::Optional< KeyExchangeType > keyExchangeType_
folly::Optional< EarlyDataType > earlyDataType_
folly::Optional< ReplayCacheResult > replayCacheResult_
folly::Optional< Buf > clientHandshakeSecret_
folly::Optional< std::string > alpn_
folly::Optional< std::chrono::milliseconds > clientClockSkew_
std::unique_ptr< AppTokenValidator > appTokenValidator_
std::shared_ptr< ServerExtensions > extensions_
std::vector< uint8_t > resumptionMasterSecret_
std::unique_ptr< HandshakeLogging > handshakeLogging_
folly::Optional< Buf > earlyExporterMasterSecret_
folly::Optional< Buf > exporterMasterSecret_
Detailed Description
Definition at line 64 of file State.h.
Member Function Documentation
const folly::Optional<std::string>& fizz::server::State::alpn () const inline
Application protocol negotiated on this connection.
Definition at line 168 of file State.h.
Referenced by fizz::sm::generateTicket(), and fizz::server::AsyncFizzServerT< SM >::getApplicationProtocol().
{
     return alpn_;
   }
auto& fizz::server::State::alpn () inline
Definition at line 355 of file State.h.
                {
     return alpn_;
   }
const AppTokenValidator* fizz::server::State::appTokenValidator () const inline
Callback to application that validates appToken from ResumptionState. If this function returns false, early data should be rejected.
Definition at line 184 of file State.h.
Referenced by fizz::sm::getCertificateRequest().
{
     return appTokenValidator_.get();
   }
auto& fizz::server::State::appTokenValidator () inline
Definition at line 361 of file State.h.
{
     return appTokenValidator_;
   }
folly::Optional<CipherSuite> fizz::server::State::cipher () const inline
Cipher suite nogotiated on this connection.
Definition at line 111 of file State.h.
Referenced by fizz::sm::generateTicket(), fizz::sm::getCertificateRequest(), and fizz::server::AsyncFizzServerT< SM >::getCipher().
{
     return cipher_;
   }
auto& fizz::server::State::cipher () inline
Definition at line 328 of file State.h.
                  {
     return cipher_;
   }
const std::shared_ptr<const Cert>& fizz::server::State::clientCert () const inline
The certificate used by the client for authentication. May be null.
Definition at line 97 of file State.h.
Referenced by fizz::sm::generateTicket(), and fizz::server::AsyncFizzServerT< SM >::getPeerCertificate().
{
     return clientCert_;
   }
auto& fizz::server::State::clientCert () inline
Definition at line 316 of file State.h.
                      {
     return clientCert_;
   }
folly::Optional<std::chrono::milliseconds> fizz::server::State::clientClockSkew () const inline
How much the client ticket age was off (on a PSK connection). Negative if the client was behind.
Definition at line 176 of file State.h.
{
     return clientClockSkew_;
   }
auto& fizz::server::State::clientClockSkew () inline
Definition at line 358 of file State.h.
{
     return clientClockSkew_;
   }
const Buf& fizz::server::State::clientHandshakeSecret () const inline
Client handshake secret.
Should not be used outside of the state machine.
Definition at line 232 of file State.h.
Referenced by fizz::sm::generateTicket().
{
     return *clientHandshakeSecret_;
   }
auto& fizz::server::State::clientHandshakeSecret () inline
Definition at line 352 of file State.h.
{
     return clientHandshakeSecret_;
   }
const FizzServerContext* fizz::server::State::context () const inline
The FizzServerContext used on this connection.
Definition at line 83 of file State.h.
Referenced by fizz::sm::generateTicket(), fizz::sm::getCertificateRequest(), and fizz::server::AsyncFizzServerT< SM >::getSupportedSigSchemes().
{
     return context_.get();
   }
auto& fizz::server::State::context () inline
Definition at line 295 of file State.h.
                   {
     return context_;
   }
folly::Optional<EarlyDataType> fizz::server::State::earlyDataType () const inline
Whether early data was used on this connection.
Definition at line 154 of file State.h.
Referenced by fizz::sm::getCertificateRequest().
{
     return earlyDataType_;
   }
auto& fizz::server::State::earlyDataType () inline
Definition at line 346 of file State.h.
{
     return earlyDataType_;
   }
const folly::Optional<Buf>& fizz::server::State::earlyExporterMasterSecret () const inline
Get the early exporter master secret. Only available if early data was accepted.
Definition at line 275 of file State.h.
Referenced by fizz::sm::getCertificateRequest().
{
     return earlyExporterMasterSecret_;
   }
auto& fizz::server::State::earlyExporterMasterSecret () inline
Definition at line 373 of file State.h.
{
     return earlyExporterMasterSecret_;
   }
folly::Executor* fizz::server::State::executor () const inline
The executor this conenction is running on.
Definition at line 76 of file State.h.
Referenced by fizz::server::AsyncFizzServerT< SM >::attachEventBase(), fizz::sm::generateTicket(), and fizz::sm::getCertificateRequest().
{
     return executor_;
   }
auto& fizz::server::State::executor () inline
Definition at line 292 of file State.h.
                    {
     return executor_;
   }
const folly::Optional<Buf>& fizz::server::State::exporterMasterSecret () const inline
Get the exporter master secret.
Definition at line 282 of file State.h.
{
     return exporterMasterSecret_;
   }
auto& fizz::server::State::exporterMasterSecret () inline
Definition at line 376 of file State.h.
{
     return exporterMasterSecret_;
   }
ServerExtensions* fizz::server::State::extensions () const inline
Get the extensions interface in order to parse extensions on ClientHello
Should not be used outside of the state machine.
Definition at line 241 of file State.h.
Referenced by fizz::sm::getCertificateRequest().
{
     return extensions_.get();
   }
auto& fizz::server::State::extensions () inline
Definition at line 367 of file State.h.
                      {
     return extensions_;
   }
folly::Optional<NamedGroup> fizz::server::State::group () const inline
The named group used if (EC)DH key exchange was used.
Definition at line 118 of file State.h.
Referenced by fizz::sm::getCertificateRequest().
{
     return group_;
   }
auto& fizz::server::State::group () inline
Definition at line 331 of file State.h.
                 {
     return group_;
   }
auto& fizz::server::State::handshakeContext () const inline
Definition at line 310 of file State.h.
Referenced by fizz::sm::generateTicket(), and fizz::sm::getCertificateRequest().
{
     return handshakeContext_;
   }
HandshakeLogging* fizz::server::State::handshakeLogging () const inline
Handshake logging struct containing information on the client hello, etc. This data should only be used for logging and is not guaranteed to be present.
Definition at line 193 of file State.h.
Referenced by fizz::sm::addHandshakeLogging().
{
     return handshakeLogging_.get();
   }
auto& fizz::server::State::handshakeLogging () inline
Definition at line 364 of file State.h.
{
     return handshakeLogging_;
   }
auto& fizz::server::State::handshakeReadRecordLayer () const inline
Definition at line 307 of file State.h.
Referenced by fizz::sm::getCertificateRequest().
{
     return handshakeReadRecordLayer_;
   }
folly::Optional<KeyExchangeType> fizz::server::State::keyExchangeType () const inline
Key exchange flow used on this connection (none, normal, or hello retry).
Definition at line 147 of file State.h.
Referenced by fizz::sm::getCertificateRequest().
{
     return keyExchangeType_;
   }
auto& fizz::server::State::keyExchangeType () inline
Definition at line 343 of file State.h.
{
     return keyExchangeType_;
   }
KeyScheduler* fizz::server::State::keyScheduler () const inline
Key scheduler used on this connection.
The state of the key scheduler may change outside of state mutators. Should not be used outside of the state machine.
Definition at line 203 of file State.h.
Referenced by fizz::sm::generateTicket().
{
     return keyScheduler_.get();
   }
auto& fizz::server::State::keyScheduler () inline
Definition at line 298 of file State.h.
{
     return keyScheduler_;
   }
folly::Optional<PskKeyExchangeMode> fizz::server::State::pskMode () const inline
Psk key exchange mode used on this connection, if a psk was accepted.
Definition at line 140 of file State.h.
{
     return pskMode_;
   }
auto& fizz::server::State::pskMode () inline
Definition at line 340 of file State.h.
                   {
     return pskMode_;
   }
folly::Optional<PskType> fizz::server::State::pskType () const inline
Psk handshake flow used on this connection (psk not sent, psk rejected, psk accepted, etc.).
Definition at line 133 of file State.h.
Referenced by fizz::sm::generateTicket().
{
     return pskType_;
   }
auto& fizz::server::State::pskType () inline
Definition at line 337 of file State.h.
                   {
     return pskType_;
   }
ReadRecordLayer* fizz::server::State::readRecordLayer () const inline
Current read record layer. May be null.
The state of the read record layer may change outside of state mutators. Should not be used outside of the state machine.
Definition at line 213 of file State.h.
Referenced by fizz::sm::addHandshakeLogging(), fizz::sm::generateTicket(), fizz::sm::getCertificateRequest(), and fizz::server::ServerStateMachine::processSocketData().
{
     return readRecordLayer_.get();
   }
auto& fizz::server::State::readRecordLayer () inline
Definition at line 301 of file State.h.
{
     return readRecordLayer_;
   }
folly::Optional<ReplayCacheResult> fizz::server::State::replayCacheResult () const inline
What the replay cache replied with (if checked).
Definition at line 161 of file State.h.
Referenced by fizz::sm::getCertificateRequest().
{
     return replayCacheResult_;
   }
auto& fizz::server::State::replayCacheResult () inline
Definition at line 349 of file State.h.
{
     return replayCacheResult_;
   }
const std::vector<uint8_t>& fizz::server::State::resumptionMasterSecret () const inline
Resumption master secret.
Definition at line 248 of file State.h.
Referenced by fizz::sm::generateTicket().
{
     return resumptionMasterSecret_;
   }
auto& fizz::server::State::resumptionMasterSecret () inline
Definition at line 370 of file State.h.
{
     return resumptionMasterSecret_;
   }
std::shared_ptr<const Cert> fizz::server::State::serverCert () const inline
The certificate used to authenticate the server. May be null.
Definition at line 90 of file State.h.
Referenced by fizz::sm::generateTicket(), and fizz::server::AsyncFizzServerT< SM >::getSelfCertificate().
{
     return serverCert_;
   }
auto& fizz::server::State::serverCert () inline
Definition at line 313 of file State.h.
                      {
     return serverCert_;
   }
const folly::Optional<CertificateCompressionAlgorithm>& fizz::server::State::serverCertCompAlgo () const inline
Get the certificate compression algorithm used for the sent certificate (if any).
Definition at line 266 of file State.h.
             {
     return serverCertCompAlgo_;
   }
auto& fizz::server::State::serverCertCompAlgo () inline
Definition at line 319 of file State.h.
{
     return serverCertCompAlgo_;
   }
folly::Optional<SignatureScheme> fizz::server::State::sigScheme () const inline
The signature scheme used if server authentication was used.
Definition at line 125 of file State.h.
{
     return sigScheme_;
   }
auto& fizz::server::State::sigScheme () inline
Definition at line 334 of file State.h.
                     {
     return sigScheme_;
   }
StateEnum fizz::server::State::state () const inline
The current state of the connection.
Definition at line 69 of file State.h.
Referenced by fizz::server::test::AsyncFizzServerTest::expectAppClose(), fizz::server::detail::handleError(), fizz::server::detail::handleInvalidEvent(), fizz::server::FizzServer< ActionMoveVisitor, SM >::newTransportData(), fizz::server::detail::processEvent(), and fizz::server::test::TEST_F().
{
     return state_;
   }
auto& fizz::server::State::state () inline
Definition at line 289 of file State.h.
                 {
     return state_;
   }
const folly::Optional<std::vector<std::shared_ptr<const PeerCert> > >& fizz::server::State::unverifiedCertChain () const inline
The certificate chain sent by the client pre-verification
Should not be used outside of the state machine.
Definition at line 258 of file State.h.
Referenced by fizz::sm::generateTicket().
{
     return unverifiedCertChain_;
   }
auto& fizz::server::State::unverifiedCertChain () inline
Definition at line 322 of file State.h.
{
     return unverifiedCertChain_;
   }
folly::Optional<ProtocolVersion> fizz::server::State::version () const inline
Protocol version negotiated on this connection.
Definition at line 104 of file State.h.
Referenced by fizz::sm::generateTicket(), and fizz::sm::getCertificateRequest().
{
     return version_;
   }
auto& fizz::server::State::version () inline
Definition at line 325 of file State.h.
                   {
     return version_;
   }
const WriteRecordLayer* fizz::server::State::writeRecordLayer () const inline
Current write record layer. May be null.
The state of the write record layer may change outside of state mutators. Should not be used outside of the state machine.
Definition at line 223 of file State.h.
Referenced by fizz::sm::generateTicket(), fizz::sm::getCertificateRequest(), fizz::server::detail::handleAppClose(), and fizz::server::detail::handleError().
{
     return writeRecordLayer_.get();
   }
auto& fizz::server::State::writeRecordLayer () inline
Definition at line 304 of file State.h.
{
     return writeRecordLayer_;
   }
Member Data Documentation
folly::Optional<std::string> fizz::server::State::alpn_ private
Definition at line 413 of file State.h.
std::unique_ptr<AppTokenValidator> fizz::server::State::appTokenValidator_ private
Definition at line 415 of file State.h.
folly::Optional<CipherSuite> fizz::server::State::cipher_ private
Definition at line 404 of file State.h.
std::shared_ptr<const Cert> fizz::server::State::clientCert_ private
Definition at line 397 of file State.h.
folly::Optional<std::chrono::milliseconds> fizz::server::State::clientClockSkew_ private
Definition at line 414 of file State.h.
folly::Optional<Buf> fizz::server::State::clientHandshakeSecret_ private
Definition at line 412 of file State.h.
std::shared_ptr<const FizzServerContext> fizz::server::State::context_ private
Definition at line 385 of file State.h.
folly::Optional<EarlyDataType> fizz::server::State::earlyDataType_ private
Definition at line 410 of file State.h.
folly::Optional<Buf> fizz::server::State::earlyExporterMasterSecret_ private
Definition at line 421 of file State.h.
folly::Executor* fizz::server::State::executor_ private
Definition at line 383 of file State.h.
folly::Optional<Buf> fizz::server::State::exporterMasterSecret_ private
Definition at line 422 of file State.h.
std::shared_ptr<ServerExtensions> fizz::server::State::extensions_ private
Definition at line 416 of file State.h.
folly::Optional<NamedGroup> fizz::server::State::group_ private
Definition at line 405 of file State.h.
std::unique_ptr<HandshakeContext> fizz::server::State::handshakeContext_ mutable private
Definition at line 394 of file State.h.
std::unique_ptr<HandshakeLogging> fizz::server::State::handshakeLogging_ private
Definition at line 419 of file State.h.
std::unique_ptr<EncryptedReadRecordLayer> fizz::server::State::handshakeReadRecordLayer_ mutable private
Definition at line 393 of file State.h.
folly::Optional<KeyExchangeType> fizz::server::State::keyExchangeType_ private
Definition at line 409 of file State.h.
std::unique_ptr<KeyScheduler> fizz::server::State::keyScheduler_ private
Definition at line 387 of file State.h.
folly::Optional<PskKeyExchangeMode> fizz::server::State::pskMode_ private
Definition at line 408 of file State.h.
folly::Optional<PskType> fizz::server::State::pskType_ private
Definition at line 407 of file State.h.
std::unique_ptr<ReadRecordLayer> fizz::server::State::readRecordLayer_ private
Definition at line 389 of file State.h.
folly::Optional<ReplayCacheResult> fizz::server::State::replayCacheResult_ private
Definition at line 411 of file State.h.
std::vector<uint8_t> fizz::server::State::resumptionMasterSecret_ private
Definition at line 417 of file State.h.
std::shared_ptr<const Cert> fizz::server::State::serverCert_ private
Definition at line 396 of file State.h.
folly::Optional<CertificateCompressionAlgorithm> fizz::server::State::serverCertCompAlgo_ private
Definition at line 398 of file State.h.
folly::Optional<SignatureScheme> fizz::server::State::sigScheme_ private
Definition at line 406 of file State.h.
StateEnum fizz::server::State::state_ {StateEnum::Uninitialized} private
Definition at line 381 of file State.h.
folly::Optional<std::vector<std::shared_ptr<const PeerCert> > > fizz::server::State::unverifiedCertChain_ private
Definition at line 401 of file State.h.
folly::Optional<ProtocolVersion> fizz::server::State::version_ private
Definition at line 403 of file State.h.
std::unique_ptr<WriteRecordLayer> fizz::server::State::writeRecordLayer_ private
Definition at line 390 of file State.h.
The documentation for this class was generated from the following file:
proxygen/fizz/fizz/server/State.h