proxygen: testing::AssertionResult Class Reference
testing::AssertionResult Class Reference
#include <gtest.h>
Public Member Functions
AssertionResult (const AssertionResult &other)
template<typename T >
AssertionResult (const T &success, typename internal::EnableIf< !internal::ImplicitlyConvertible< T, AssertionResult >::value >::type *=NULL)
AssertionResult & operator= (AssertionResult other)
operator bool () const
AssertionResult operator! () const
const char * message () const
const char * failure_message () const
template<typename T >
AssertionResult & operator<< (const T &value)
AssertionResult & operator<< (::std::ostream &(*basic_manipulator)(::std::ostream &stream))
AssertionResult (const AssertionResult &other)
template<typename T >
AssertionResult (const T &success, typename internal::EnableIf< !internal::ImplicitlyConvertible< T, AssertionResult >::value >::type *=NULL)
AssertionResult & operator= (AssertionResult other)
operator bool () const
AssertionResult operator! () const
const char * message () const
const char * failure_message () const
template<typename T >
AssertionResult & operator<< (const T &value)
AssertionResult & operator<< (::std::ostream &(*basic_manipulator)(::std::ostream &stream))
AssertionResult (const AssertionResult &other)
template<typename T >
AssertionResult (const T &success, typename internal::EnableIf< !internal::ImplicitlyConvertible< T, AssertionResult >::value >::type *=NULL)
AssertionResult & operator= (AssertionResult other)
operator bool () const
AssertionResult operator! () const
const char * message () const
const char * failure_message () const
template<typename T >
AssertionResult & operator<< (const T &value)
AssertionResult & operator<< (::std::ostream &(*basic_manipulator)(::std::ostream &stream))
Private Member Functions
void AppendMessage (const Message &a_message)
void swap (AssertionResult &other)
void AppendMessage (const Message &a_message)
void swap (AssertionResult &other)
void AppendMessage (const Message &a_message)
void swap (AssertionResult &other)
Private Attributes
bool success_
internal::scoped_ptr< ::std::string > message_
Detailed Description
Definition at line 256 of file gtest.h.
Constructor & Destructor Documentation
testing::AssertionResult::AssertionResult (const AssertionResult & other)
Definition at line 987 of file gtest.cc.
Referenced by testing::AssertionFailure(), testing::AssertionSuccess(), and testing::internal::ShouldRunTestCase().
     : success_(other.success_),
       message_(other.message_.get() != NULL ?
                new ::std::string(*other.message_) :
                static_cast< ::std::string*>(NULL)) {
 }
template<typename T > testing::AssertionResult::AssertionResult (const T & success, typename internal::EnableIf< !internal::ImplicitlyConvertible< T, AssertionResult >::value >::type * = NULL) inline explicit
Definition at line 272 of file gtest.h.
References GTEST_DISABLE_MSC_WARNINGS_POP_.
       : success_(success) {}
testing::AssertionResult::AssertionResult (const AssertionResult & other)
template<typename T > testing::AssertionResult::AssertionResult (const T & success, typename internal::EnableIf< !internal::ImplicitlyConvertible< T, AssertionResult >::value >::type * = NULL) inline explicit
Definition at line 272 of file gtest.h.
References GTEST_DISABLE_MSC_WARNINGS_POP_.
       : success_(success) {}
testing::AssertionResult::AssertionResult (const AssertionResult & other)
template<typename T > testing::AssertionResult::AssertionResult (const T & success, typename internal::EnableIf< !internal::ImplicitlyConvertible< T, AssertionResult >::value >::type * = NULL) inline explicit
Definition at line 272 of file gtest.h.
References GTEST_DISABLE_MSC_WARNINGS_POP_.
       : success_(success) {}
Member Function Documentation
void testing::AssertionResult::AppendMessage (const Message & a_message) inline private
Definition at line 320 of file gtest.h.
References testing::Message::GetString(), string, and folly::f14::swap().
{
     if (message_.get() == NULL)
       message_.reset(new ::std::string);
     message_->append(a_message.GetString().c_str());
   }
void testing::AssertionResult::AppendMessage (const Message & a_message) inline private
Definition at line 320 of file gtest.h.
References testing::AssertionFailure(), testing::AssertionSuccess(), testing::Message::GetString(), GTEST_API_, string, and folly::f14::swap().
{
     if (message_.get() == NULL)
       message_.reset(new ::std::string);
     message_->append(a_message.GetString().c_str());
   }
void testing::AssertionResult::AppendMessage (const Message & a_message) inline private
Definition at line 320 of file gtest.h.
References testing::AssertionFailure(), testing::AssertionSuccess(), testing::Message::GetString(), GTEST_API_, string, and folly::f14::swap().
{
     if (message_.get() == NULL)
       message_.reset(new ::std::string);
     message_->append(a_message.GetString().c_str());
   }
const char* testing::AssertionResult::failure_message () const inline
Definition at line 302 of file gtest.h.
References message.
 { return message(); }
const char* testing::AssertionResult::failure_message () const inline
Definition at line 302 of file gtest.h.
References message.
 { return message(); }
const char* testing::AssertionResult::failure_message () const inline
Definition at line 302 of file gtest.h.
References message.
 { return message(); }
const char* testing::AssertionResult::message () const inline
Definition at line 297 of file gtest.h.
Referenced by testing::AssertionFailure(), testing::internal::GetBoolAssertionFailureMessage(), and TEST().
{
     return message_.get() != NULL ?  message_->c_str() : "";
   }
const char* testing::AssertionResult::message () const inline
Definition at line 297 of file gtest.h.
{
     return message_.get() != NULL ?  message_->c_str() : "";
   }
const char* testing::AssertionResult::message () const inline
Definition at line 297 of file gtest.h.
{
     return message_.get() != NULL ?  message_->c_str() : "";
   }
testing::AssertionResult::operator bool () const inline
Definition at line 288 of file gtest.h.
References proxygen::operator!().
 { return success_; }  // NOLINT
testing::AssertionResult::operator bool () const inline
Definition at line 288 of file gtest.h.
References proxygen::operator!().
 { return success_; }  // NOLINT
testing::AssertionResult::operator bool () const inline
Definition at line 288 of file gtest.h.
References proxygen::operator!().
 { return success_; }  // NOLINT
AssertionResult testing::AssertionResult::operator! () const
AssertionResult testing::AssertionResult::operator! () const
AssertionResult testing::AssertionResult::operator! () const
Definition at line 1002 of file gtest.cc.
References testing::internal::scoped_ptr< T >::get(), message_, and success_.
Referenced by testing::internal::ShouldRunTestCase().
{
   AssertionResult negation(!success_);
   if (message_.get() != NULL)
     negation << *message_;
   return negation;
 }
template<typename T > AssertionResult& testing::AssertionResult::operator<< (const T & value) inline
Definition at line 305 of file gtest.h.
{
     AppendMessage(Message() << value);
     return *this;
   }
template<typename T > AssertionResult& testing::AssertionResult::operator<< (const T & value) inline
Definition at line 305 of file gtest.h.
{
     AppendMessage(Message() << value);
     return *this;
   }
template<typename T > AssertionResult& testing::AssertionResult::operator<< (const T & value) inline
Definition at line 305 of file gtest.h.
{
     AppendMessage(Message() << value);
     return *this;
   }
AssertionResult& testing::AssertionResult::operator<< (::std::ostream &(*)(::std::ostream &stream) basic_manipulator) inline
Definition at line 312 of file gtest.h.
{
     AppendMessage(Message() << basic_manipulator);
     return *this;
   }
AssertionResult& testing::AssertionResult::operator<< (::std::ostream &(*)(::std::ostream &stream) basic_manipulator) inline
Definition at line 312 of file gtest.h.
{
     AppendMessage(Message() << basic_manipulator);
     return *this;
   }
AssertionResult& testing::AssertionResult::operator<< (::std::ostream &(*)(::std::ostream &stream) basic_manipulator) inline
Definition at line 312 of file gtest.h.
{
     AppendMessage(Message() << basic_manipulator);
     return *this;
   }
AssertionResult& testing::AssertionResult::operator= (AssertionResult other) inline
Definition at line 282 of file gtest.h.
References folly::f14::swap().
{
     swap(other);
     return *this;
   }
AssertionResult& testing::AssertionResult::operator= (AssertionResult other) inline
Definition at line 282 of file gtest.h.
References folly::f14::swap().
{
     swap(other);
     return *this;
   }
AssertionResult& testing::AssertionResult::operator= (AssertionResult other) inline
Definition at line 282 of file gtest.h.
References folly::f14::swap().
{
     swap(other);
     return *this;
   }
void testing::AssertionResult::swap (AssertionResult & other) private
void testing::AssertionResult::swap (AssertionResult & other) private
Definition at line 995 of file gtest.cc.
References message_, success_, and folly::f14::swap().
Referenced by testing::internal::ShouldRunTestCase().
{
   using std::swap;
   swap(success_, other.success_);
   swap(message_, other.message_);
 }
void testing::AssertionResult::swap (AssertionResult & other) private
Member Data Documentation
internal::scoped_ptr<::std::string > testing::AssertionResult::message_ private
Definition at line 335 of file gtest.h.
Referenced by operator!(), testing::internal::ShouldRunTestCase(), and swap().
bool testing::AssertionResult::success_ private
Definition at line 330 of file gtest.h.
Referenced by operator!(), testing::internal::ShouldRunTestCase(), and swap().
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/gtest.h
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest.cc