proxygen: folly::AutoTimer< Logger, Clock > Class Template Reference
folly::AutoTimer< Logger, Clock > Class Template Reference final
#include <AutoTimer.h>
Public Types
using DoubleSeconds = std::chrono::duration< double >
Public Member Functions
AutoTimer (std::string &&msg="", const DoubleSeconds &minTimetoLog=DoubleSeconds::zero(), Logger &&logger=Logger())
AutoTimer (const AutoTimer &)=delete
AutoTimer (AutoTimer &&)=default
AutoTimer & operator= (const AutoTimer &)=delete
AutoTimer & operator= (AutoTimer &&)=default
~AutoTimer ()
DoubleSeconds log (StringPiece msg="")
template<typename... Args>
DoubleSeconds log (Args &&...args)
template<typename... Args>
DoubleSeconds logFormat (Args &&...args)
Private Member Functions
DoubleSeconds logImpl (std::chrono::time_point< Clock > now, StringPiece msg)
Private Attributes
Optional< std::string > destructionMessage_
std::chrono::time_point< Clock > start_ = Clock::now()
DoubleSeconds minTimeToLog_
Logger logger_
Detailed Description
template<class Logger = GoogleLogger<GoogleLoggerStyle::PRETTY>, class Clock = std::chrono::high_resolution_clock>
class folly::AutoTimer< Logger, Clock >
Automatically times a block of code, printing a specified log message on destruction or whenever the log() method is called. For example:
AutoTimer t("Foo() completed"); doWork(); t.log("Do work finished"); doMoreWork();
This would print something like: "Do work finished in 1.2 seconds" "Foo() completed in 4.3 seconds"
You can customize what you use as the logger and clock. The logger needs to have an operator()(StringPiece, std::chrono::duration<double>) that gets a message and a duration. The clock needs to model Clock from std::chrono.
The default logger logs usings glog. It only logs if the message is non-empty, so you can also just use this class for timing, e.g.:
AutoTimer t; doWork() const auto how_long = t.log();
Definition at line 63 of file AutoTimer.h.
Member Typedef Documentation
template<class Logger = GoogleLogger<GoogleLoggerStyle::PRETTY>, class Clock = std::chrono::high_resolution_clock> using folly::AutoTimer< Logger, Clock >::DoubleSeconds = std::chrono::duration<double>
Definition at line 65 of file AutoTimer.h.
Constructor & Destructor Documentation
template<class Logger = GoogleLogger<GoogleLoggerStyle::PRETTY>, class Clock = std::chrono::high_resolution_clock> folly::AutoTimer< Logger, Clock >::AutoTimer (std::string && msg = "", const DoubleSeconds & minTimetoLog = DoubleSeconds::zero(), Logger && logger = Logger()) inline explicit
Definition at line 67 of file AutoTimer.h.
       : destructionMessage_(std::move(msg)),
         minTimeToLog_(minTimetoLog),
         logger_(std::move(logger)) {}
template<class Logger = GoogleLogger<GoogleLoggerStyle::PRETTY>, class Clock = std::chrono::high_resolution_clock> folly::AutoTimer< Logger, Clock >::AutoTimer (const AutoTimer< Logger, Clock > &) delete
template<class Logger = GoogleLogger<GoogleLoggerStyle::PRETTY>, class Clock = std::chrono::high_resolution_clock> folly::AutoTimer< Logger, Clock >::AutoTimer (AutoTimer< Logger, Clock > &&) default
template<class Logger = GoogleLogger<GoogleLoggerStyle::PRETTY>, class Clock = std::chrono::high_resolution_clock> folly::AutoTimer< Logger, Clock >::~AutoTimer () inline
Definition at line 82 of file AutoTimer.h.
                {
     if (destructionMessage_) {
       log(destructionMessage_.value());
     }
   }
Member Function Documentation
template<class Logger = GoogleLogger<GoogleLoggerStyle::PRETTY>, class Clock = std::chrono::high_resolution_clock> DoubleSeconds folly::AutoTimer< Logger, Clock >::log (StringPiece msg = "") inline
Definition at line 88 of file AutoTimer.h.
References testing::Args(), and now().
Referenced by TEST().
{
     return logImpl(Clock::now(), msg);
   }
template<class Logger = GoogleLogger<GoogleLoggerStyle::PRETTY>, class Clock = std::chrono::high_resolution_clock> template<typename... Args> DoubleSeconds folly::AutoTimer< Logger, Clock >::log (Args &&... args) inline
Definition at line 93 of file AutoTimer.h.
References testing::Args(), and now().
{
     auto now = Clock::now();
     return logImpl(now, to<std::string>(std::forward<Args>(args)...));
   }
template<class Logger = GoogleLogger<GoogleLoggerStyle::PRETTY>, class Clock = std::chrono::high_resolution_clock> template<typename... Args> DoubleSeconds folly::AutoTimer< Logger, Clock >::logFormat (Args &&... args) inline
Definition at line 99 of file AutoTimer.h.
References folly::format(), and now().
Referenced by TEST().
{
     auto now = Clock::now();
     return logImpl(now, format(std::forward<Args>(args)...).str());
   }
template<class Logger = GoogleLogger<GoogleLoggerStyle::PRETTY>, class Clock = std::chrono::high_resolution_clock> DoubleSeconds folly::AutoTimer< Logger, Clock >::logImpl (std::chrono::time_point< Clock > now, StringPiece msg) inline private
Definition at line 107 of file AutoTimer.h.
References now(), and start_.
{
     auto duration = now - start_;
     if (duration >= minTimeToLog_) {
       logger_(msg, duration);
     }
     start_ = Clock::now(); // Don't measure logging time
     return duration;
   }
template<class Logger = GoogleLogger<GoogleLoggerStyle::PRETTY>, class Clock = std::chrono::high_resolution_clock> AutoTimer& folly::AutoTimer< Logger, Clock >::operator= (const AutoTimer< Logger, Clock > &) delete
template<class Logger = GoogleLogger<GoogleLoggerStyle::PRETTY>, class Clock = std::chrono::high_resolution_clock> AutoTimer& folly::AutoTimer< Logger, Clock >::operator= (AutoTimer< Logger, Clock > &&) default
Member Data Documentation
template<class Logger = GoogleLogger<GoogleLoggerStyle::PRETTY>, class Clock = std::chrono::high_resolution_clock> Optional<std::string> folly::AutoTimer< Logger, Clock >::destructionMessage_ private
Definition at line 116 of file AutoTimer.h.
template<class Logger = GoogleLogger<GoogleLoggerStyle::PRETTY>, class Clock = std::chrono::high_resolution_clock> Logger folly::AutoTimer< Logger, Clock >::logger_ private
Definition at line 119 of file AutoTimer.h.
template<class Logger = GoogleLogger<GoogleLoggerStyle::PRETTY>, class Clock = std::chrono::high_resolution_clock> DoubleSeconds folly::AutoTimer< Logger, Clock >::minTimeToLog_ private
Definition at line 118 of file AutoTimer.h.
template<class Logger = GoogleLogger<GoogleLoggerStyle::PRETTY>, class Clock = std::chrono::high_resolution_clock> std::chrono::time_point<Clock> folly::AutoTimer< Logger, Clock >::start_ = Clock::now() private
Definition at line 117 of file AutoTimer.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/AutoTimer.h