proxygen: upload.HttpRpcServer Class Reference
upload.HttpRpcServer Class Reference
elif e.code >= 500 and e.code < 600:
Server Error - try again.
Public Attributes
cookie_file
cookie_jar
authenticated
Public Attributes inherited from upload.AbstractRpcServer
host
host_override
auth_function
authenticated
extra_headers
save_cookies
opener
Private Member Functions
def _Authenticate (self)
def _GetOpener (self)
def _Authenticate (self)
def _GetOpener (self)
def _Authenticate (self)
def _GetOpener (self)
def _Authenticate (self)
def _GetOpener (self)
def _Authenticate (self)
def _GetOpener (self)
def _Authenticate (self)
def _GetOpener (self)
Additional Inherited Members
Public Member Functions inherited from upload.AbstractRpcServer
def __init__ (self, host, auth_function, host_override=None, extra_headers={}, save_cookies=False)
def Send (self, request_path, payload=None, content_type="application/octet-stream", timeout=None, kwargs)
def __init__ (self, host, auth_function, host_override=None, extra_headers={}, save_cookies=False)
def Send (self, request_path, payload=None, content_type="application/octet-stream", timeout=None, kwargs)
def __init__ (self, host, auth_function, host_override=None, extra_headers={}, save_cookies=False)
def Send (self, request_path, payload=None, content_type="application/octet-stream", timeout=None, kwargs)
def __init__ (self, host, auth_function, host_override=None, extra_headers={}, save_cookies=False)
def Send (self, request_path, payload=None, content_type="application/octet-stream", timeout=None, kwargs)
def __init__ (self, host, auth_function, host_override=None, extra_headers={}, save_cookies=False)
def Send (self, request_path, payload=None, content_type="application/octet-stream", timeout=None, kwargs)
def __init__ (self, host, auth_function, host_override=None, extra_headers={}, save_cookies=False)
def Send (self, request_path, payload=None, content_type="application/octet-stream", timeout=None, kwargs)
Detailed Description
elif e.code >= 500 and e.code < 600:
Server Error - try again.
continue
Provides a simplified RPC-style interface for HTTP requests.
Definition at line 344 of file upload.py.
Member Function Documentation
def upload.HttpRpcServer._Authenticate (self) private
Save the cookie jar after authentication.
Definition at line 347 of file upload.py.
References upload.HttpRpcServer.cookie_file, upload.AbstractRpcServer.save_cookies, and upload.StatusUpdate().
Referenced by upload.HttpRpcServer._Authenticate().
   def _Authenticate(self):
     """Save the cookie jar after authentication."""
     super(HttpRpcServer, self)._Authenticate()
     if self.save_cookies:
       StatusUpdate("Saving authentication cookies to %s" % self.cookie_file)
       self.cookie_jar.save()
def upload.HttpRpcServer._Authenticate (self) private
Save the cookie jar after authentication.
Definition at line 347 of file upload.py.
References upload.HttpRpcServer._Authenticate(), upload.HttpRpcServer.cookie_file, upload.AbstractRpcServer.save_cookies, and upload.StatusUpdate().
   def _Authenticate(self):
     """Save the cookie jar after authentication."""
     super(HttpRpcServer, self)._Authenticate()
     if self.save_cookies:
       StatusUpdate("Saving authentication cookies to %s" % self.cookie_file)
       self.cookie_jar.save()
def upload.HttpRpcServer._Authenticate (self) private
Save the cookie jar after authentication.
Definition at line 347 of file upload.py.
References upload.HttpRpcServer._Authenticate(), upload.HttpRpcServer.cookie_file, upload.AbstractRpcServer.save_cookies, and upload.StatusUpdate().
   def _Authenticate(self):
     """Save the cookie jar after authentication."""
     super(HttpRpcServer, self)._Authenticate()
     if self.save_cookies:
       StatusUpdate("Saving authentication cookies to %s" % self.cookie_file)
       self.cookie_jar.save()
def upload.HttpRpcServer._Authenticate (self) private
Save the cookie jar after authentication.
Definition at line 347 of file upload.py.
References upload.HttpRpcServer._Authenticate(), upload.HttpRpcServer.cookie_file, upload.AbstractRpcServer.save_cookies, and upload.StatusUpdate().
   def _Authenticate(self):
     """Save the cookie jar after authentication."""
     super(HttpRpcServer, self)._Authenticate()
     if self.save_cookies:
       StatusUpdate("Saving authentication cookies to %s" % self.cookie_file)
       self.cookie_jar.save()
def upload.HttpRpcServer._Authenticate (self) private
Save the cookie jar after authentication.
Definition at line 347 of file upload.py.
References upload.HttpRpcServer._Authenticate(), upload.HttpRpcServer.cookie_file, upload.AbstractRpcServer.save_cookies, and upload.StatusUpdate().
   def _Authenticate(self):
     """Save the cookie jar after authentication."""
     super(HttpRpcServer, self)._Authenticate()
     if self.save_cookies:
       StatusUpdate("Saving authentication cookies to %s" % self.cookie_file)
       self.cookie_jar.save()
def upload.HttpRpcServer._Authenticate (self) private
Save the cookie jar after authentication.
Definition at line 347 of file upload.py.
References upload.HttpRpcServer._Authenticate(), upload.HttpRpcServer.cookie_file, upload.AbstractRpcServer.save_cookies, and upload.StatusUpdate().
   def _Authenticate(self):
     """Save the cookie jar after authentication."""
     super(HttpRpcServer, self)._Authenticate()
     if self.save_cookies:
       StatusUpdate("Saving authentication cookies to %s" % self.cookie_file)
       self.cookie_jar.save()
def upload.HttpRpcServer._GetOpener (self) private
Returns an OpenerDirector that supports cookies and ignores redirects.
Returns:
  A urllib2.OpenerDirector object.
Definition at line 354 of file upload.py.
References upload.HttpRpcServer._GetOpener(), upload.AbstractRpcServer.authenticated, upload.HttpRpcServer.cookie_file, upload.HttpRpcServer.cookie_jar, upload.EncodeMultipartFormData(), upload.ErrorExit(), upload.GetContentType(), upload.GetEmail(), upload.GetRpcServer(), join, object, upload.RunShell(), upload.RunShellWithReturnCode(), upload.AbstractRpcServer.save_cookies, and upload.StatusUpdate().
   def _GetOpener(self):
     """Returns an OpenerDirector that supports cookies and ignores redirects.
     Returns:
       A urllib2.OpenerDirector object.
     """
     opener = urllib2.OpenerDirector()
     opener.add_handler(urllib2.ProxyHandler())
     opener.add_handler(urllib2.UnknownHandler())
     opener.add_handler(urllib2.HTTPHandler())
     opener.add_handler(urllib2.HTTPDefaultErrorHandler())
     opener.add_handler(urllib2.HTTPSHandler())
     opener.add_handler(urllib2.HTTPErrorProcessor())
     if self.save_cookies:
       self.cookie_file = os.path.expanduser("~/.codereview_upload_cookies")
       self.cookie_jar = cookielib.MozillaCookieJar(self.cookie_file)
       if os.path.exists(self.cookie_file):
         try:
           self.cookie_jar.load()
           self.authenticated = True
           StatusUpdate("Loaded authentication cookies from %s" %
                        self.cookie_file)
         except (cookielib.LoadError, IOError):
           # Failed to load cookies - just ignore them.
           pass
       else:
         # Create an empty cookie file with mode 600
         fd = os.open(self.cookie_file, os.O_CREAT, 0600)
         os.close(fd)
       # Always chmod the cookie file
       os.chmod(self.cookie_file, 0600)
     else:
       # Don't save cookies across runs of update.py.
       self.cookie_jar = cookielib.CookieJar()
     opener.add_handler(urllib2.HTTPCookieProcessor(self.cookie_jar))
     return opener
def upload.HttpRpcServer._GetOpener (self) private
Returns an OpenerDirector that supports cookies and ignores redirects.
Returns:
  A urllib2.OpenerDirector object.
Definition at line 354 of file upload.py.
References upload.HttpRpcServer._GetOpener(), upload.AbstractRpcServer.authenticated, upload.HttpRpcServer.cookie_file, upload.HttpRpcServer.cookie_jar, upload.EncodeMultipartFormData(), upload.ErrorExit(), upload.GetContentType(), upload.GetEmail(), upload.GetRpcServer(), join, object, upload.RunShell(), upload.RunShellWithReturnCode(), upload.AbstractRpcServer.save_cookies, and upload.StatusUpdate().
   def _GetOpener(self):
     """Returns an OpenerDirector that supports cookies and ignores redirects.
     Returns:
       A urllib2.OpenerDirector object.
     """
     opener = urllib2.OpenerDirector()
     opener.add_handler(urllib2.ProxyHandler())
     opener.add_handler(urllib2.UnknownHandler())
     opener.add_handler(urllib2.HTTPHandler())
     opener.add_handler(urllib2.HTTPDefaultErrorHandler())
     opener.add_handler(urllib2.HTTPSHandler())
     opener.add_handler(urllib2.HTTPErrorProcessor())
     if self.save_cookies:
       self.cookie_file = os.path.expanduser("~/.codereview_upload_cookies")
       self.cookie_jar = cookielib.MozillaCookieJar(self.cookie_file)
       if os.path.exists(self.cookie_file):
         try:
           self.cookie_jar.load()
           self.authenticated = True
           StatusUpdate("Loaded authentication cookies from %s" %
                        self.cookie_file)
         except (cookielib.LoadError, IOError):
           # Failed to load cookies - just ignore them.
           pass
       else:
         # Create an empty cookie file with mode 600
         fd = os.open(self.cookie_file, os.O_CREAT, 0600)
         os.close(fd)
       # Always chmod the cookie file
       os.chmod(self.cookie_file, 0600)
     else:
       # Don't save cookies across runs of update.py.
       self.cookie_jar = cookielib.CookieJar()
     opener.add_handler(urllib2.HTTPCookieProcessor(self.cookie_jar))
     return opener
def upload.HttpRpcServer._GetOpener (self) private
Returns an OpenerDirector that supports cookies and ignores redirects.
Returns:
  A urllib2.OpenerDirector object.
Definition at line 354 of file upload.py.
References upload.AbstractRpcServer.save_cookies.
Referenced by upload.HttpRpcServer._GetOpener().
   def _GetOpener(self):
     """Returns an OpenerDirector that supports cookies and ignores redirects.
     Returns:
       A urllib2.OpenerDirector object.
     """
     opener = urllib2.OpenerDirector()
     opener.add_handler(urllib2.ProxyHandler())
     opener.add_handler(urllib2.UnknownHandler())
     opener.add_handler(urllib2.HTTPHandler())
     opener.add_handler(urllib2.HTTPDefaultErrorHandler())
     opener.add_handler(urllib2.HTTPSHandler())
     opener.add_handler(urllib2.HTTPErrorProcessor())
     if self.save_cookies:
       self.cookie_file = os.path.expanduser("~/.codereview_upload_cookies")
       self.cookie_jar = cookielib.MozillaCookieJar(self.cookie_file)
       if os.path.exists(self.cookie_file):
         try:
           self.cookie_jar.load()
           self.authenticated = True
           StatusUpdate("Loaded authentication cookies from %s" %
                        self.cookie_file)
         except (cookielib.LoadError, IOError):
           # Failed to load cookies - just ignore them.
           pass
       else:
         # Create an empty cookie file with mode 600
         fd = os.open(self.cookie_file, os.O_CREAT, 0600)
         os.close(fd)
       # Always chmod the cookie file
       os.chmod(self.cookie_file, 0600)
     else:
       # Don't save cookies across runs of update.py.
       self.cookie_jar = cookielib.CookieJar()
     opener.add_handler(urllib2.HTTPCookieProcessor(self.cookie_jar))
     return opener
def upload.HttpRpcServer._GetOpener (self) private
Returns an OpenerDirector that supports cookies and ignores redirects.
Returns:
  A urllib2.OpenerDirector object.
Definition at line 354 of file upload.py.
References upload.HttpRpcServer._GetOpener(), upload.AbstractRpcServer.authenticated, upload.HttpRpcServer.cookie_file, upload.HttpRpcServer.cookie_jar, upload.EncodeMultipartFormData(), upload.ErrorExit(), upload.GetContentType(), upload.GetEmail(), upload.GetRpcServer(), join, object, upload.RunShell(), upload.RunShellWithReturnCode(), upload.AbstractRpcServer.save_cookies, and upload.StatusUpdate().
   def _GetOpener(self):
     """Returns an OpenerDirector that supports cookies and ignores redirects.
     Returns:
       A urllib2.OpenerDirector object.
     """
     opener = urllib2.OpenerDirector()
     opener.add_handler(urllib2.ProxyHandler())
     opener.add_handler(urllib2.UnknownHandler())
     opener.add_handler(urllib2.HTTPHandler())
     opener.add_handler(urllib2.HTTPDefaultErrorHandler())
     opener.add_handler(urllib2.HTTPSHandler())
     opener.add_handler(urllib2.HTTPErrorProcessor())
     if self.save_cookies:
       self.cookie_file = os.path.expanduser("~/.codereview_upload_cookies")
       self.cookie_jar = cookielib.MozillaCookieJar(self.cookie_file)
       if os.path.exists(self.cookie_file):
         try:
           self.cookie_jar.load()
           self.authenticated = True
           StatusUpdate("Loaded authentication cookies from %s" %
                        self.cookie_file)
         except (cookielib.LoadError, IOError):
           # Failed to load cookies - just ignore them.
           pass
       else:
         # Create an empty cookie file with mode 600
         fd = os.open(self.cookie_file, os.O_CREAT, 0600)
         os.close(fd)
       # Always chmod the cookie file
       os.chmod(self.cookie_file, 0600)
     else:
       # Don't save cookies across runs of update.py.
       self.cookie_jar = cookielib.CookieJar()
     opener.add_handler(urllib2.HTTPCookieProcessor(self.cookie_jar))
     return opener
def upload.HttpRpcServer._GetOpener (self) private
Returns an OpenerDirector that supports cookies and ignores redirects.
Returns:
  A urllib2.OpenerDirector object.
Definition at line 354 of file upload.py.
References upload.HttpRpcServer._GetOpener(), upload.AbstractRpcServer.authenticated, upload.HttpRpcServer.cookie_file, upload.HttpRpcServer.cookie_jar, upload.EncodeMultipartFormData(), upload.ErrorExit(), upload.GetContentType(), upload.GetEmail(), upload.GetRpcServer(), join, object, upload.RunShell(), upload.RunShellWithReturnCode(), upload.AbstractRpcServer.save_cookies, and upload.StatusUpdate().
   def _GetOpener(self):
     """Returns an OpenerDirector that supports cookies and ignores redirects.
     Returns:
       A urllib2.OpenerDirector object.
     """
     opener = urllib2.OpenerDirector()
     opener.add_handler(urllib2.ProxyHandler())
     opener.add_handler(urllib2.UnknownHandler())
     opener.add_handler(urllib2.HTTPHandler())
     opener.add_handler(urllib2.HTTPDefaultErrorHandler())
     opener.add_handler(urllib2.HTTPSHandler())
     opener.add_handler(urllib2.HTTPErrorProcessor())
     if self.save_cookies:
       self.cookie_file = os.path.expanduser("~/.codereview_upload_cookies")
       self.cookie_jar = cookielib.MozillaCookieJar(self.cookie_file)
       if os.path.exists(self.cookie_file):
         try:
           self.cookie_jar.load()
           self.authenticated = True
           StatusUpdate("Loaded authentication cookies from %s" %
                        self.cookie_file)
         except (cookielib.LoadError, IOError):
           # Failed to load cookies - just ignore them.
           pass
       else:
         # Create an empty cookie file with mode 600
         fd = os.open(self.cookie_file, os.O_CREAT, 0600)
         os.close(fd)
       # Always chmod the cookie file
       os.chmod(self.cookie_file, 0600)
     else:
       # Don't save cookies across runs of update.py.
       self.cookie_jar = cookielib.CookieJar()
     opener.add_handler(urllib2.HTTPCookieProcessor(self.cookie_jar))
     return opener
def upload.HttpRpcServer._GetOpener (self) private
Returns an OpenerDirector that supports cookies and ignores redirects.
Returns:
  A urllib2.OpenerDirector object.
Definition at line 354 of file upload.py.
References upload.HttpRpcServer._GetOpener(), upload.AbstractRpcServer.authenticated, upload.HttpRpcServer.cookie_file, upload.HttpRpcServer.cookie_jar, upload.EncodeMultipartFormData(), upload.ErrorExit(), upload.GetContentType(), upload.GetEmail(), upload.GetRpcServer(), join, object, upload.RunShell(), upload.RunShellWithReturnCode(), upload.AbstractRpcServer.save_cookies, and upload.StatusUpdate().
   def _GetOpener(self):
     """Returns an OpenerDirector that supports cookies and ignores redirects.
     Returns:
       A urllib2.OpenerDirector object.
     """
     opener = urllib2.OpenerDirector()
     opener.add_handler(urllib2.ProxyHandler())
     opener.add_handler(urllib2.UnknownHandler())
     opener.add_handler(urllib2.HTTPHandler())
     opener.add_handler(urllib2.HTTPDefaultErrorHandler())
     opener.add_handler(urllib2.HTTPSHandler())
     opener.add_handler(urllib2.HTTPErrorProcessor())
     if self.save_cookies:
       self.cookie_file = os.path.expanduser("~/.codereview_upload_cookies")
       self.cookie_jar = cookielib.MozillaCookieJar(self.cookie_file)
       if os.path.exists(self.cookie_file):
         try:
           self.cookie_jar.load()
           self.authenticated = True
           StatusUpdate("Loaded authentication cookies from %s" %
                        self.cookie_file)
         except (cookielib.LoadError, IOError):
           # Failed to load cookies - just ignore them.
           pass
       else:
         # Create an empty cookie file with mode 600
         fd = os.open(self.cookie_file, os.O_CREAT, 0600)
         os.close(fd)
       # Always chmod the cookie file
       os.chmod(self.cookie_file, 0600)
     else:
       # Don't save cookies across runs of update.py.
       self.cookie_jar = cookielib.CookieJar()
     opener.add_handler(urllib2.HTTPCookieProcessor(self.cookie_jar))
     return opener
Member Data Documentation
upload.HttpRpcServer.authenticated
Definition at line 373 of file upload.py.
upload.HttpRpcServer.cookie_file
Definition at line 368 of file upload.py.
Referenced by upload.HttpRpcServer._Authenticate(), and upload.HttpRpcServer._GetOpener().
upload.HttpRpcServer.cookie_jar
Definition at line 369 of file upload.py.
Referenced by upload.HttpRpcServer._GetOpener().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/scripts/upload.py