proxygen: wangle::ThreadSafeSSLSessionCache Class Reference
wangle::ThreadSafeSSLSessionCache Class Reference
#include <ThreadSafeSSLSessionCache.h>
Public Member Functions
ThreadSafeSSLSessionCache (std::unique_ptr< SSLSessionCallbacks > delegate)
void setSSLSession (const std::string &identity, SSLSessionPtr session) noexceptoverride
SSLSessionPtr getSSLSession (const std::string &identity) const noexceptoverride
bool removeSSLSession (const std::string &identity) noexceptoverride
bool supportsPersistence () const noexceptoverride
size_t size () const override
Public Member Functions inherited from wangle::SSLSessionCallbacks
virtual ~SSLSessionCallbacks ()
Private Attributes
std::unique_ptr< SSLSessionCallbacks > delegate_
folly::SharedMutex mutex_
Additional Inherited Members
Static Public Member Functions inherited from wangle::SSLSessionCallbacks
static void attachCallbacksToContext (SSL_CTX *ctx, SSLSessionCallbacks *callbacks)
static void detachCallbacksFromContext (SSL_CTX *ctx, SSLSessionCallbacks *callbacks)
static SSLSessionCallbacks * getCacheFromContext (SSL_CTX *ctx)
Detailed Description
A SSL session cache that can be used safely across threads. This is useful for clients who cannot avoid sharing the cache across threads. It uses a read/write lock for efficiency.
Definition at line 30 of file ThreadSafeSSLSessionCache.h.
Constructor & Destructor Documentation
wangle::ThreadSafeSSLSessionCache::ThreadSafeSSLSessionCache (std::unique_ptr< SSLSessionCallbacks > delegate) inline explicit
Definition at line 32 of file ThreadSafeSSLSessionCache.h.
References getSSLSession(), folly::pushmi::__adl::noexcept(), removeSSLSession(), setSSLSession(), size(), string, and supportsPersistence().
                                                     :
      delegate_(std::move(delegate)) {}
Member Function Documentation
SSLSessionPtr wangle::ThreadSafeSSLSessionCache::getSSLSession (const std::string & identity) const override virtual noexcept
Implements wangle::SSLSessionCallbacks.
Definition at line 29 of file ThreadSafeSSLSessionCache.cpp.
References folly::detail::lock(), and mutex_.
Referenced by ThreadSafeSSLSessionCache().
{
   SharedMutex::ReadHolder lock(mutex_);
   return delegate_->getSSLSession(identity);
 }
bool wangle::ThreadSafeSSLSessionCache::removeSSLSession (const std::string & identity) override virtual noexcept
Implements wangle::SSLSessionCallbacks.
Definition at line 35 of file ThreadSafeSSLSessionCache.cpp.
References folly::detail::lock(), and mutex_.
Referenced by ThreadSafeSSLSessionCache().
{
   SharedMutex::WriteHolder lock(mutex_);
   return delegate_->removeSSLSession(identity);
 }
void wangle::ThreadSafeSSLSessionCache::setSSLSession (const std::string & identity, SSLSessionPtr session) override virtual noexcept
Implements wangle::SSLSessionCallbacks.
Definition at line 22 of file ThreadSafeSSLSessionCache.cpp.
References folly::detail::lock(), folly::gen::move, and mutex_.
Referenced by ThreadSafeSSLSessionCache().
{
   SharedMutex::WriteHolder lock(mutex_);
   delegate_->setSSLSession(identity, std::move(session));
 }
size_t wangle::ThreadSafeSSLSessionCache::size () const override virtual
Reimplemented from wangle::SSLSessionCallbacks.
Definition at line 46 of file ThreadSafeSSLSessionCache.cpp.
References delegate_, folly::detail::lock(), and mutex_.
Referenced by ThreadSafeSSLSessionCache().
{
   SharedMutex::ReadHolder lock(mutex_);
   return delegate_->size();
 }
bool wangle::ThreadSafeSSLSessionCache::supportsPersistence () const override virtual noexcept
Reimplemented from wangle::SSLSessionCallbacks.
Definition at line 41 of file ThreadSafeSSLSessionCache.cpp.
References delegate_, folly::detail::lock(), and mutex_.
Referenced by ThreadSafeSSLSessionCache().
{
   SharedMutex::ReadHolder lock(mutex_);
   return delegate_->supportsPersistence();
 }
Member Data Documentation
std::unique_ptr<SSLSessionCallbacks> wangle::ThreadSafeSSLSessionCache::delegate_ private
Definition at line 46 of file ThreadSafeSSLSessionCache.h.
Referenced by size(), and supportsPersistence().
folly::SharedMutex wangle::ThreadSafeSSLSessionCache::mutex_ mutable private
Definition at line 47 of file ThreadSafeSSLSessionCache.h.
Referenced by size(), and supportsPersistence().
The documentation for this class was generated from the following files:
proxygen/wangle/wangle/client/ssl/ThreadSafeSSLSessionCache.h
proxygen/wangle/wangle/client/ssl/ThreadSafeSSLSessionCache.cpp