proxygen: fizz::CertDecompressionManager Class Reference
fizz::CertDecompressionManager Class Reference
#include <CertDecompressionManager.h>
Public Member Functions
CertDecompressionManager ()
CertDecompressionManager (std::vector< std::shared_ptr< CertificateDecompressor >> decompressors)
void setDecompressors (std::vector< std::shared_ptr< CertificateDecompressor >> decompressors)
std::vector< CertificateCompressionAlgorithm > getSupportedAlgorithms () const
std::shared_ptr< CertificateDecompressor > getDecompressor (CertificateCompressionAlgorithm algo) const
Private Attributes
std::map< CertificateCompressionAlgorithm, std::shared_ptr< CertificateDecompressor > > decompressors_
std::vector< CertificateCompressionAlgorithm > supportedAlgos_
Detailed Description
Definition at line 18 of file CertDecompressionManager.h.
Constructor & Destructor Documentation
fizz::CertDecompressionManager::CertDecompressionManager ()
Can be constructed empty with no arguments or initialized with the decompressors provided.
Definition at line 13 of file CertDecompressionManager.cpp.
 {}
fizz::CertDecompressionManager::CertDecompressionManager (std::vector< std::shared_ptr< CertificateDecompressor >> decompressors) explicit
Definition at line 15 of file CertDecompressionManager.cpp.
References folly::gen::move, and setDecompressors().
{
   setDecompressors(std::move(decompressors));
 }
Member Function Documentation
std::shared_ptr< CertificateDecompressor > fizz::CertDecompressionManager::getDecompressor (CertificateCompressionAlgorithm algo) const
Returns the decompressor for a given algorithm. If not found, returns nullptr;
Definition at line 38 of file CertDecompressionManager.cpp.
References decompressors_, and fizz::toString().
{
   try {
     return decompressors_.at(algo);
   } catch (const std::out_of_range&) {
     VLOG(4) << "Requested unknown algorithm: " << toString(algo);
     return nullptr;
   }
 }
std::vector< CertificateCompressionAlgorithm > fizz::CertDecompressionManager::getSupportedAlgorithms () const
Return supported decompression algorithms.
Definition at line 33 of file CertDecompressionManager.cpp.
References supportedAlgos_.
{
   return supportedAlgos_;
 }
void fizz::CertDecompressionManager::setDecompressors (std::vector< std::shared_ptr< CertificateDecompressor >> decompressors)
Explicitly sets the decompressors. Clears the internal storage before using the new list.
Definition at line 20 of file CertDecompressionManager.cpp.
References decompressors_, and supportedAlgos_.
Referenced by CertDecompressionManager().
{
   decompressors_.clear();
   for (const auto& decompressor : decompressors) {
     decompressors_[decompressor->getAlgorithm()] = decompressor;
   }
   supportedAlgos_.clear();
   for (const auto& pair : decompressors_) {
     supportedAlgos_.push_back(pair.first);
   }
 }
Member Data Documentation
std::map< CertificateCompressionAlgorithm, std::shared_ptr<CertificateDecompressor> > fizz::CertDecompressionManager::decompressors_ private
Definition at line 51 of file CertDecompressionManager.h.
Referenced by getDecompressor(), and setDecompressors().
std::vector<CertificateCompressionAlgorithm> fizz::CertDecompressionManager::supportedAlgos_ private
Definition at line 53 of file CertDecompressionManager.h.
Referenced by getSupportedAlgorithms(), and setDecompressors().
The documentation for this class was generated from the following files:
proxygen/fizz/fizz/protocol/CertDecompressionManager.h
proxygen/fizz/fizz/protocol/CertDecompressionManager.cpp