proxygen: folly::symbolizer::Dwarf::Path Class Reference
folly::symbolizer::Dwarf::Path Class Reference
#include <Dwarf.h>
Public Member Functions
Path ()
Path (folly::StringPiece baseDir, folly::StringPiece subDir, folly::StringPiece file)
folly::StringPiece baseDir () const
folly::StringPiece subDir () const
folly::StringPiece file () const
size_t size () const
size_t toBuffer (char *buf, size_t bufSize) const
void toString (std::string &dest) const
std::string toString () const
Private Attributes
folly::StringPiece baseDir_
folly::StringPiece subDir_
folly::StringPiece file_
Detailed Description
Represent a file path a s collection of three parts (base directory, subdirectory, and file).
Definition at line 64 of file Dwarf.h.
Constructor & Destructor Documentation
folly::symbolizer::Dwarf::Path::Path () inline
Definition at line 66 of file Dwarf.h.
References baseDir(), file(), and subDir().
Referenced by folly::symbolizer::Dwarf::findLocation().
 {}
folly::symbolizer::Dwarf::Path::Path (folly::StringPiece baseDir, folly::StringPiece subDir, folly::StringPiece file)
Definition at line 167 of file Dwarf.cpp.
References baseDir_, folly::Range< Iter >::clear(), folly::Range< Iter >::empty(), file_, subDir_, folly::f14::swap(), and folly::swap().
     : baseDir_(baseDir), subDir_(subDir), file_(file) {
   using std::swap;
   // Normalize
   if (file_.empty()) {
     baseDir_.clear();
     subDir_.clear();
     return;
   }
   if (file_[0] == '/') {
     // file_ is absolute
     baseDir_.clear();
     subDir_.clear();
   }
   if (!subDir_.empty() && subDir_[0] == '/') {
     baseDir_.clear(); // subDir_ is absolute
   }
   simplifyPath(baseDir_);
   simplifyPath(subDir_);
   simplifyPath(file_);
   // Make sure it's never the case that baseDir_ is empty, but subDir_ isn't.
   if (baseDir_.empty()) {
     swap(baseDir_, subDir_);
   }
 }
Member Function Documentation
folly::StringPiece folly::symbolizer::Dwarf::Path::baseDir () const inline
Definition at line 73 of file Dwarf.h.
References baseDir_.
Referenced by Path().
{
       return baseDir_;
     }
folly::StringPiece folly::symbolizer::Dwarf::Path::file () const inline
Definition at line 79 of file Dwarf.h.
References upload::dest, file_, size(), string, toBuffer(), and toString().
Referenced by Path().
{
       return file_;
     }
size_t folly::symbolizer::Dwarf::Path::size () const
Definition at line 201 of file Dwarf.cpp.
References baseDir_, folly::Range< Iter >::empty(), folly::Range< Iter >::endsWith(), file_, folly::Range< Iter >::size(), and subDir_.
Referenced by file(), toBuffer(), and toString().
{
   size_t size = 0;
   bool needsSlash = false;
   if (!baseDir_.empty()) {
     size += baseDir_.size();
     needsSlash = !baseDir_.endsWith('/');
   }
   if (!subDir_.empty()) {
     size += needsSlash;
     size += subDir_.size();
     needsSlash = !subDir_.endsWith('/');
   }
   if (!file_.empty()) {
     size += needsSlash;
     size += file_.size();
   }
   return size;
 }
folly::StringPiece folly::symbolizer::Dwarf::Path::subDir () const inline
Definition at line 76 of file Dwarf.h.
References subDir_.
Referenced by Path().
{
       return subDir_;
     }
size_t folly::symbolizer::Dwarf::Path::toBuffer (char * buf, size_t bufSize) const
Copy the Path to a buffer of size bufSize.
toBuffer behaves like snprintf: It will always null-terminate the buffer (so it will copy at most bufSize-1 bytes), and it will return the number of bytes that would have been written if there had been enough room, so, if toBuffer returns a value >= bufSize, the output was truncated.
Definition at line 224 of file Dwarf.cpp.
References append(), baseDir_, folly::Range< Iter >::empty(), folly::Range< Iter >::endsWith(), file_, min, size(), and subDir_.
Referenced by file(), and folly::symbolizer::SymbolizePrinter::print().
{
   size_t totalSize = 0;
   bool needsSlash = false;
   auto append = [&](folly::StringPiece sp) {
     if (bufSize >= 2) {
       size_t toCopy = std::min(sp.size(), bufSize - 1);
       memcpy(buf, sp.data(), toCopy);
       buf += toCopy;
       bufSize -= toCopy;
     }
     totalSize += sp.size();
   };
   if (!baseDir_.empty()) {
     append(baseDir_);
     needsSlash = !baseDir_.endsWith('/');
   }
   if (!subDir_.empty()) {
     if (needsSlash) {
       append("/");
     }
     append(subDir_);
     needsSlash = !subDir_.endsWith('/');
   }
   if (!file_.empty()) {
     if (needsSlash) {
       append("/");
     }
     append(file_);
   }
   if (bufSize) {
     *buf = '\0';
   }
   assert(totalSize == size());
   return totalSize;
 }
void folly::symbolizer::Dwarf::Path::toString (std::string & dest) const
Definition at line 262 of file Dwarf.cpp.
References baseDir_, folly::Range< Iter >::begin(), folly::Range< Iter >::empty(), folly::Range< Iter >::end(), file_, size(), and subDir_.
Referenced by folly::symbolizer::operator<<(), and folly::symbolizer::test::TEST().
{
   size_t initialSize = dest.size();
   dest.reserve(initialSize + size());
   if (!baseDir_.empty()) {
     dest.append(baseDir_.begin(), baseDir_.end());
   }
   if (!subDir_.empty()) {
     if (!dest.empty() && dest.back() != '/') {
       dest.push_back('/');
     }
     dest.append(subDir_.begin(), subDir_.end());
   }
   if (!file_.empty()) {
     if (!dest.empty() && dest.back() != '/') {
       dest.push_back('/');
     }
     dest.append(file_.begin(), file_.end());
   }
   assert(dest.size() == initialSize + size());
 }
std::string folly::symbolizer::Dwarf::Path::toString () const inline
Definition at line 97 of file Dwarf.h.
References s, and string.
Referenced by file().
{
       std::string s;
       toString(s);
       return s;
     }
Member Data Documentation
folly::StringPiece folly::symbolizer::Dwarf::Path::baseDir_ private
Definition at line 106 of file Dwarf.h.
Referenced by baseDir(), Path(), size(), toBuffer(), and toString().
folly::StringPiece folly::symbolizer::Dwarf::Path::file_ private
Definition at line 108 of file Dwarf.h.
Referenced by file(), Path(), size(), toBuffer(), and toString().
folly::StringPiece folly::symbolizer::Dwarf::Path::subDir_ private
Definition at line 107 of file Dwarf.h.
Referenced by Path(), size(), subDir(), toBuffer(), and toString().
The documentation for this class was generated from the following files:
proxygen/folly/folly/experimental/symbolizer/Dwarf.h
proxygen/folly/folly/experimental/symbolizer/Dwarf.cpp