proxygen: testing::internal::FilePath Class Reference
testing::internal::FilePath Class Reference
#include <gtest-filepath.h>
Public Member Functions
FilePath ()
FilePath (const FilePath &rhs)
FilePath (const std::string &pathname)
FilePath & operator= (const FilePath &rhs)
void Set (const FilePath &rhs)
const std::string & string () const
const char * c_str () const
bool IsEmpty () const
FilePath RemoveTrailingPathSeparator () const
FilePath RemoveDirectoryName () const
FilePath RemoveFileName () const
FilePath RemoveExtension (const char *extension) const
bool CreateDirectoriesRecursively () const
bool CreateFolder () const
bool FileOrDirectoryExists () const
bool DirectoryExists () const
bool IsDirectory () const
bool IsRootDirectory () const
bool IsAbsolutePath () const
FilePath ()
FilePath (const FilePath &rhs)
FilePath (const std::string &pathname)
FilePath & operator= (const FilePath &rhs)
void Set (const FilePath &rhs)
const std::string & string () const
const char * c_str () const
bool IsEmpty () const
FilePath RemoveTrailingPathSeparator () const
FilePath RemoveDirectoryName () const
FilePath RemoveFileName () const
FilePath RemoveExtension (const char *extension) const
bool CreateDirectoriesRecursively () const
bool CreateFolder () const
bool FileOrDirectoryExists () const
bool DirectoryExists () const
bool IsDirectory () const
bool IsRootDirectory () const
bool IsAbsolutePath () const
FilePath ()
FilePath (const FilePath &rhs)
FilePath (const std::string &pathname)
FilePath & operator= (const FilePath &rhs)
void Set (const FilePath &rhs)
const std::string & string () const
const char * c_str () const
bool IsEmpty () const
FilePath RemoveTrailingPathSeparator () const
FilePath RemoveDirectoryName () const
FilePath RemoveFileName () const
FilePath RemoveExtension (const char *extension) const
bool CreateDirectoriesRecursively () const
bool CreateFolder () const
bool FileOrDirectoryExists () const
bool DirectoryExists () const
bool IsDirectory () const
bool IsRootDirectory () const
bool IsAbsolutePath () const
Static Public Member Functions
static FilePath GetCurrentDir ()
static FilePath MakeFileName (const FilePath &directory, const FilePath &base_name, int number, const char *extension)
static FilePath ConcatPaths (const FilePath &directory, const FilePath &relative_path)
static FilePath GenerateUniqueFileName (const FilePath &directory, const FilePath &base_name, const char *extension)
static FilePath GetCurrentDir ()
static FilePath MakeFileName (const FilePath &directory, const FilePath &base_name, int number, const char *extension)
static FilePath ConcatPaths (const FilePath &directory, const FilePath &relative_path)
static FilePath GenerateUniqueFileName (const FilePath &directory, const FilePath &base_name, const char *extension)
static FilePath GetCurrentDir ()
static FilePath MakeFileName (const FilePath &directory, const FilePath &base_name, int number, const char *extension)
static FilePath ConcatPaths (const FilePath &directory, const FilePath &relative_path)
static FilePath GenerateUniqueFileName (const FilePath &directory, const FilePath &base_name, const char *extension)
Private Member Functions
void Normalize ()
const char * FindLastPathSeparator () const
void Normalize ()
const char * FindLastPathSeparator () const
void Normalize ()
const char * FindLastPathSeparator () const
Private Attributes
std::string pathname_
Detailed Description
Definition at line 59 of file gtest-filepath.h.
Constructor & Destructor Documentation
testing::internal::FilePath::FilePath () inline
Definition at line 61 of file gtest-filepath.h.
Referenced by ConcatPaths(), GetCurrentDir(), testing::internal::IsPathSeparator(), MakeFileName(), RemoveDirectoryName(), RemoveExtension(), RemoveFileName(), and RemoveTrailingPathSeparator().
 : pathname_("") { }
testing::internal::FilePath::FilePath (const FilePath & rhs) inline
Definition at line 62 of file gtest-filepath.h.
 : pathname_(rhs.pathname_) { }
testing::internal::FilePath::FilePath (const std::string & pathname) inline explicit
Definition at line 64 of file gtest-filepath.h.
                                                : pathname_(pathname) {
     Normalize();
   }
testing::internal::FilePath::FilePath () inline
Definition at line 61 of file gtest-filepath.h.
 : pathname_("") { }
testing::internal::FilePath::FilePath (const FilePath & rhs) inline
Definition at line 62 of file gtest-filepath.h.
 : pathname_(rhs.pathname_) { }
testing::internal::FilePath::FilePath (const std::string & pathname) inline explicit
Definition at line 64 of file gtest-filepath.h.
                                                : pathname_(pathname) {
     Normalize();
   }
testing::internal::FilePath::FilePath () inline
Definition at line 61 of file gtest-filepath.h.
 : pathname_("") { }
testing::internal::FilePath::FilePath (const FilePath & rhs) inline
Definition at line 62 of file gtest-filepath.h.
 : pathname_(rhs.pathname_) { }
testing::internal::FilePath::FilePath (const std::string & pathname) inline explicit
Definition at line 64 of file gtest-filepath.h.
                                                : pathname_(pathname) {
     Normalize();
   }
Member Function Documentation
const char* testing::internal::FilePath::c_str () const inline
Definition at line 78 of file gtest-filepath.h.
References number.
Referenced by CreateFolder(), DirectoryExists(), FindLastPathSeparator(), testing::internal::IsPathSeparator(), RemoveFileName(), and testing::TEST_F().
 { return pathname_.c_str(); }
const char* testing::internal::FilePath::c_str () const inline
Definition at line 78 of file gtest-filepath.h.
References number.
 { return pathname_.c_str(); }
const char* testing::internal::FilePath::c_str () const inline
Definition at line 78 of file gtest-filepath.h.
References number.
 { return pathname_.c_str(); }
FilePath testing::internal::FilePath::ConcatPaths (const FilePath & directory, const FilePath & relative_path) static
Definition at line 199 of file gtest-filepath.cc.
References FilePath(), IsEmpty(), RemoveTrailingPathSeparator(), and string().
Referenced by testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile(), testing::internal::IsPathSeparator(), MakeFileName(), and testing::internal::ShouldRunTestCase().
{
   if (directory.IsEmpty())
     return relative_path;
   const FilePath dir(directory.RemoveTrailingPathSeparator());
   return FilePath(dir.string() + kPathSeparator + relative_path.string());
 }
static FilePath testing::internal::FilePath::ConcatPaths (const FilePath & directory, const FilePath & relative_path) static
static FilePath testing::internal::FilePath::ConcatPaths (const FilePath & directory, const FilePath & relative_path) static
bool testing::internal::FilePath::CreateDirectoriesRecursively () const
bool testing::internal::FilePath::CreateDirectoriesRecursively () const
Definition at line 308 of file gtest-filepath.cc.
References CreateDirectoriesRecursively(), CreateFolder(), DirectoryExists(), IsDirectory(), parent, pathname_, RemoveFileName(), and RemoveTrailingPathSeparator().
Referenced by CreateDirectoriesRecursively(), and testing::internal::IsPathSeparator().
{
   if (!this->IsDirectory()) {
     return false;
   }
   if (pathname_.length() == 0 || this->DirectoryExists()) {
     return true;
   }
   const FilePath parent(this->RemoveTrailingPathSeparator().RemoveFileName());
   return parent.CreateDirectoriesRecursively() && this->CreateFolder();
 }
bool testing::internal::FilePath::CreateDirectoriesRecursively () const
bool testing::internal::FilePath::CreateFolder () const
bool testing::internal::FilePath::CreateFolder () const
bool testing::internal::FilePath::CreateFolder () const
Definition at line 325 of file gtest-filepath.cc.
References c_str(), DirectoryExists(), pathname_, and RemoveTrailingPathSeparator().
Referenced by CreateDirectoriesRecursively(), and testing::internal::IsPathSeparator().
{
 #if GTEST_OS_WINDOWS_MOBILE
   FilePath removed_sep(this->RemoveTrailingPathSeparator());
   LPCWSTR unicode = String::AnsiToUtf16(removed_sep.c_str());
   int result = CreateDirectory(unicode, NULL) ? 0 : -1;
   delete [] unicode;
 #elif GTEST_OS_WINDOWS
   int result = _mkdir(pathname_.c_str());
 #else
   int result = mkdir(pathname_.c_str(), 0777);
 #endif  // GTEST_OS_WINDOWS_MOBILE
   if (result == -1) {
     return this->DirectoryExists();  // An error is OK if the directory exists.
   }
   return true;  // No error.
 }
bool testing::internal::FilePath::DirectoryExists () const
Definition at line 223 of file gtest-filepath.cc.
References c_str(), testing::internal::posix::IsDir(), IsRootDirectory(), RemoveTrailingPathSeparator(), and testing::internal::posix::Stat().
Referenced by CreateDirectoriesRecursively(), CreateFolder(), and testing::internal::IsPathSeparator().
{
   bool result = false;
 #if GTEST_OS_WINDOWS
   // Don't strip off trailing separator if path is a root directory on
   // Windows (like "C:\\").
   const FilePath& path(IsRootDirectory() ? *this :
                                            RemoveTrailingPathSeparator());
 #else
   const FilePath& path(*this);
 #endif
 #if GTEST_OS_WINDOWS_MOBILE
   LPCWSTR unicode = String::AnsiToUtf16(path.c_str());
   const DWORD attributes = GetFileAttributes(unicode);
   delete [] unicode;
   if ((attributes != kInvalidFileAttributes) &&
       (attributes & FILE_ATTRIBUTE_DIRECTORY)) {
     result = true;
   }
 #else
   posix::StatStruct file_stat;
   result = posix::Stat(path.c_str(), &file_stat) == 0 &&
       posix::IsDir(file_stat);
 #endif  // GTEST_OS_WINDOWS_MOBILE
   return result;
 }
bool testing::internal::FilePath::DirectoryExists () const
bool testing::internal::FilePath::DirectoryExists () const
bool testing::internal::FilePath::FileOrDirectoryExists () const
Definition at line 209 of file gtest-filepath.cc.
References pathname_, and testing::internal::posix::Stat().
Referenced by GenerateUniqueFileName(), and testing::internal::IsPathSeparator().
{
 #if GTEST_OS_WINDOWS_MOBILE
   LPCWSTR unicode = String::AnsiToUtf16(pathname_.c_str());
   const DWORD attributes = GetFileAttributes(unicode);
   delete [] unicode;
   return attributes != kInvalidFileAttributes;
 #else
   posix::StatStruct file_stat;
   return posix::Stat(pathname_.c_str(), &file_stat) == 0;
 #endif  // GTEST_OS_WINDOWS_MOBILE
 }
bool testing::internal::FilePath::FileOrDirectoryExists () const
bool testing::internal::FilePath::FileOrDirectoryExists () const
const char* testing::internal::FilePath::FindLastPathSeparator () const private
const char * testing::internal::FilePath::FindLastPathSeparator () const private
Definition at line 136 of file gtest-filepath.cc.
References c_str().
Referenced by testing::internal::IsPathSeparator(), RemoveDirectoryName(), and RemoveFileName().
{
   const char* const last_sep = strrchr(c_str(), kPathSeparator);
 #if GTEST_HAS_ALT_PATH_SEP_
   const char* const last_alt_sep = strrchr(c_str(), kAlternatePathSeparator);
   // Comparing two pointers of which only one is NULL is undefined.
   if (last_alt_sep != NULL &&
       (last_sep == NULL || last_alt_sep > last_sep)) {
     return last_alt_sep;
   }
 #endif
   return last_sep;
 }
const char* testing::internal::FilePath::FindLastPathSeparator () const private
FilePath testing::internal::FilePath::GenerateUniqueFileName (const FilePath & directory, const FilePath & base_name, const char * extension) static
Definition at line 286 of file gtest-filepath.cc.
References FileOrDirectoryExists(), MakeFileName(), number, and Set().
Referenced by testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile(), testing::internal::IsPathSeparator(), testing::internal::ShouldRunTestCase(), and testing::TEST_F().
{
   FilePath full_pathname;
   int number = 0;
   do {
     full_pathname.Set(MakeFileName(directory, base_name, number++, extension));
   } while (full_pathname.FileOrDirectoryExists());
   return full_pathname;
 }
static FilePath testing::internal::FilePath::GenerateUniqueFileName (const FilePath & directory, const FilePath & base_name, const char * extension) static
static FilePath testing::internal::FilePath::GenerateUniqueFileName (const FilePath & directory, const FilePath & base_name, const char * extension) static
FilePath testing::internal::FilePath::GetCurrentDir () static
Definition at line 99 of file gtest-filepath.cc.
References FilePath(), and GTEST_PATH_MAX_.
Referenced by testing::internal::UnitTestImpl::AddTestInfo(), and testing::internal::IsPathSeparator().
{
 #if GTEST_OS_WINDOWS_MOBILE || GTEST_OS_WINDOWS_PHONE || GTEST_OS_WINDOWS_RT
   // Windows CE doesn't have a current directory, so we just return
   // something reasonable.
   return FilePath(kCurrentDirectoryString);
 #elif GTEST_OS_WINDOWS
   char cwd[GTEST_PATH_MAX_ + 1] = { '\0' };
   return FilePath(_getcwd(cwd, sizeof(cwd)) == NULL ? "" : cwd);
 #else
   char cwd[GTEST_PATH_MAX_ + 1] = { '\0' };
   char* result = getcwd(cwd, sizeof(cwd));
 # if GTEST_OS_NACL
   // getcwd will likely fail in NaCl due to the sandbox, so return something
   // reasonable. The user may have provided a shim implementation for getcwd,
   // however, so fallback only when failure is detected.
   return FilePath(result == NULL ? kCurrentDirectoryString : cwd);
 # endif  // GTEST_OS_NACL
   return FilePath(result == NULL ? "" : cwd);
 #endif  // GTEST_OS_WINDOWS_MOBILE
 }
static FilePath testing::internal::FilePath::GetCurrentDir () static
static FilePath testing::internal::FilePath::GetCurrentDir () static
bool testing::internal::FilePath::IsAbsolutePath () const
bool testing::internal::FilePath::IsAbsolutePath () const
bool testing::internal::FilePath::IsAbsolutePath () const
Definition at line 265 of file gtest-filepath.cc.
References testing::internal::IsPathSeparator(), name, and pathname_.
Referenced by testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile(), testing::internal::IsPathSeparator(), IsRootDirectory(), and testing::internal::ShouldRunTestCase().
{
   const char* const name = pathname_.c_str();
 #if GTEST_OS_WINDOWS
   return pathname_.length() >= 3 &&
      ((name[0] >= 'a' && name[0] <= 'z') ||
       (name[0] >= 'A' && name[0] <= 'Z')) &&
      name[1] == ':' &&
      IsPathSeparator(name[2]);
 #else
   return IsPathSeparator(name[0]);
 #endif
 }
bool testing::internal::FilePath::IsDirectory () const
Definition at line 300 of file gtest-filepath.cc.
References testing::internal::IsPathSeparator(), and pathname_.
Referenced by CreateDirectoriesRecursively(), testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile(), testing::internal::IsPathSeparator(), RemoveTrailingPathSeparator(), and testing::internal::ShouldRunTestCase().
{
   return !pathname_.empty() &&
          IsPathSeparator(pathname_.c_str()[pathname_.length() - 1]);
 }
bool testing::internal::FilePath::IsDirectory () const
bool testing::internal::FilePath::IsDirectory () const
bool testing::internal::FilePath::IsEmpty () const inline
Definition at line 111 of file gtest-filepath.h.
Referenced by ConcatPaths(), and testing::internal::IsPathSeparator().
 { return pathname_.empty(); }
bool testing::internal::FilePath::IsEmpty () const inline
Definition at line 111 of file gtest-filepath.h.
References string.
 { return pathname_.empty(); }
bool testing::internal::FilePath::IsEmpty () const inline
Definition at line 111 of file gtest-filepath.h.
References string.
 { return pathname_.empty(); }
bool testing::internal::FilePath::IsRootDirectory () const
Definition at line 253 of file gtest-filepath.cc.
References IsAbsolutePath(), testing::internal::IsPathSeparator(), and pathname_.
Referenced by DirectoryExists(), and testing::internal::IsPathSeparator().
{
 #if GTEST_OS_WINDOWS
   // TODO(wan@google.com): on Windows a network share like
   // \\server\share can be a root directory, although it cannot be the
   // current directory.  Handle this properly.
   return pathname_.length() == 3 && IsAbsolutePath();
 #else
   return pathname_.length() == 1 && IsPathSeparator(pathname_.c_str()[0]);
 #endif
 }
bool testing::internal::FilePath::IsRootDirectory () const
bool testing::internal::FilePath::IsRootDirectory () const
FilePath testing::internal::FilePath::MakeFileName (const FilePath & directory, const FilePath & base_name, int number, const char * extension) static
Definition at line 183 of file gtest-filepath.cc.
References ConcatPaths(), FilePath(), testing::internal::StreamableToString(), string(), and string.
Referenced by GenerateUniqueFileName(), and testing::internal::IsPathSeparator().
{
   std::string file;
   if (number == 0) {
     file = base_name.string() + "." + extension;
   } else {
     file = base_name.string() + "_" + StreamableToString(number)
         + "." + extension;
   }
   return ConcatPaths(directory, FilePath(file));
 }
static FilePath testing::internal::FilePath::MakeFileName (const FilePath & directory, const FilePath & base_name, int number, const char * extension) static
static FilePath testing::internal::FilePath::MakeFileName (const FilePath & directory, const FilePath & base_name, int number, const char * extension) static
void testing::internal::FilePath::Normalize () private
void testing::internal::FilePath::Normalize () private
void testing::internal::FilePath::Normalize () private
Definition at line 356 of file gtest-filepath.cc.
References upload::dest, testing::internal::IsPathSeparator(), testing::internal::kPathSeparator, and pathname_.
Referenced by testing::internal::IsPathSeparator().
{
   if (pathname_.c_str() == NULL) {
     pathname_ = "";
     return;
   }
   const char* src = pathname_.c_str();
   char* const dest = new char[pathname_.length() + 1];
   char* dest_ptr = dest;
   memset(dest_ptr, 0, pathname_.length() + 1);
   while (*src != '\0') {
     *dest_ptr = *src;
     if (!IsPathSeparator(*src)) {
       src++;
     } else {
 #if GTEST_HAS_ALT_PATH_SEP_
       if (*dest_ptr == kAlternatePathSeparator) {
         *dest_ptr = kPathSeparator;
       }
 #endif
       while (IsPathSeparator(*src))
         src++;
     }
     dest_ptr++;
   }
   *dest_ptr = '\0';
   pathname_ = dest;
   delete[] dest;
 }
FilePath& testing::internal::FilePath::operator= (const FilePath & rhs) inline
Definition at line 68 of file gtest-filepath.h.
{
     Set(rhs);
     return *this;
   }
FilePath& testing::internal::FilePath::operator= (const FilePath & rhs) inline
Definition at line 68 of file gtest-filepath.h.
{
     Set(rhs);
     return *this;
   }
FilePath& testing::internal::FilePath::operator= (const FilePath & rhs) inline
Definition at line 68 of file gtest-filepath.h.
{
     Set(rhs);
     return *this;
   }
FilePath testing::internal::FilePath::RemoveDirectoryName () const
FilePath testing::internal::FilePath::RemoveDirectoryName () const
Definition at line 155 of file gtest-filepath.cc.
References FilePath(), and FindLastPathSeparator().
Referenced by testing::internal::GetCurrentExecutableName(), testing::internal::IsPathSeparator(), and testing::internal::ShouldRunTestCase().
{
   const char* const last_sep = FindLastPathSeparator();
   return last_sep ? FilePath(last_sep + 1) : *this;
 }
FilePath testing::internal::FilePath::RemoveDirectoryName () const
FilePath testing::internal::FilePath::RemoveExtension (const char * extension) const
FilePath testing::internal::FilePath::RemoveExtension (const char * extension) const
Definition at line 124 of file gtest-filepath.cc.
References testing::internal::String::EndsWithCaseInsensitive(), FilePath(), pathname_, and string.
Referenced by testing::internal::IsPathSeparator().
{
   const std::string dot_extension = std::string(".") + extension;
   if (String::EndsWithCaseInsensitive(pathname_, dot_extension)) {
     return FilePath(pathname_.substr(
         0, pathname_.length() - dot_extension.length()));
   }
   return *this;
 }
FilePath testing::internal::FilePath::RemoveExtension (const char * extension) const
FilePath testing::internal::FilePath::RemoveFileName () const
FilePath testing::internal::FilePath::RemoveFileName () const
Definition at line 166 of file gtest-filepath.cc.
References c_str(), FilePath(), FindLastPathSeparator(), testing::internal::kCurrentDirectoryString, and string.
Referenced by CreateDirectoriesRecursively(), testing::internal::XmlUnitTestResultPrinter::EscapeXmlText(), testing::internal::IsPathSeparator(), and testing::internal::XmlUnitTestResultPrinter::OnTestIterationEnd().
{
   const char* const last_sep = FindLastPathSeparator();
   std::string dir;
   if (last_sep) {
     dir = std::string(c_str(), last_sep + 1 - c_str());
   } else {
     dir = kCurrentDirectoryString;
   }
   return FilePath(dir);
 }
FilePath testing::internal::FilePath::RemoveFileName () const
FilePath testing::internal::FilePath::RemoveTrailingPathSeparator () const
FilePath testing::internal::FilePath::RemoveTrailingPathSeparator () const
Definition at line 346 of file gtest-filepath.cc.
References FilePath(), IsDirectory(), and pathname_.
Referenced by ConcatPaths(), CreateDirectoriesRecursively(), CreateFolder(), DirectoryExists(), and testing::internal::IsPathSeparator().
{
   return IsDirectory()
       ? FilePath(pathname_.substr(0, pathname_.length() - 1))
       : *this;
 }
FilePath testing::internal::FilePath::RemoveTrailingPathSeparator () const
void testing::internal::FilePath::Set (const FilePath & rhs) inline
Definition at line 73 of file gtest-filepath.h.
References pathname_.
{
     pathname_ = rhs.pathname_;
   }
void testing::internal::FilePath::Set (const FilePath & rhs) inline
Definition at line 73 of file gtest-filepath.h.
References pathname_.
Referenced by GenerateUniqueFileName(), testing::internal::GetCurrentExecutableName(), testing::internal::IsPathSeparator(), and testing::internal::ShouldRunTestCase().
{
     pathname_ = rhs.pathname_;
   }
void testing::internal::FilePath::Set (const FilePath & rhs) inline
Definition at line 73 of file gtest-filepath.h.
References pathname_.
{
     pathname_ = rhs.pathname_;
   }
const std::string& testing::internal::FilePath::string () const inline
Definition at line 77 of file gtest-filepath.h.
Referenced by ConcatPaths(), testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile(), testing::internal::IsPathSeparator(), MakeFileName(), and testing::internal::ShouldRunTestCase().
 { return pathname_; }
const std::string& testing::internal::FilePath::string () const inline
Definition at line 77 of file gtest-filepath.h.
 { return pathname_; }
const std::string& testing::internal::FilePath::string () const inline
Definition at line 77 of file gtest-filepath.h.
 { return pathname_; }
Member Data Documentation
std::string testing::internal::FilePath::pathname_ private
Definition at line 200 of file gtest-filepath.h.
Referenced by CreateDirectoriesRecursively(), CreateFolder(), FileOrDirectoryExists(), IsAbsolutePath(), IsDirectory(), testing::internal::IsPathSeparator(), IsRootDirectory(), Normalize(), RemoveExtension(), RemoveTrailingPathSeparator(), and Set().
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/internal/gtest-filepath.h
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest-filepath.cc