proxygen: testing::NiceMock< MockClass > Class Template Reference
testing::NiceMock< MockClass > Class Template Reference
#include <gmock-generated-nice-strict.h>
Inherits MockClass, MockClass, and MockClass.
Public Member Functions
NiceMock ()
template<typename A1 >
NiceMock (const A1 &a1)
template<typename A1 , typename A2 >
NiceMock (const A1 &a1, const A2 &a2)
template<typename A1 , typename A2 , typename A3 >
NiceMock (const A1 &a1, const A2 &a2, const A3 &a3)
template<typename A1 , typename A2 , typename A3 , typename A4 >
NiceMock (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4)
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 >
NiceMock (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5)
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 >
NiceMock (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6)
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 >
NiceMock (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7)
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 >
NiceMock (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7, const A8 &a8)
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 >
NiceMock (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7, const A8 &a8, const A9 &a9)
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 , typename A10 >
NiceMock (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7, const A8 &a8, const A9 &a9, const A10 &a10)
virtual ~NiceMock ()
NiceMock ()
template<typename A1 >
NiceMock (const A1 &a1)
template<typename A1 , typename A2 >
NiceMock (const A1 &a1, const A2 &a2)
template<typename A1 , typename A2 , typename A3 >
NiceMock (const A1 &a1, const A2 &a2, const A3 &a3)
template<typename A1 , typename A2 , typename A3 , typename A4 >
NiceMock (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4)
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 >
NiceMock (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5)
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 >
NiceMock (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6)
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 >
NiceMock (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7)
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 >
NiceMock (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7, const A8 &a8)
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 >
NiceMock (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7, const A8 &a8, const A9 &a9)
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 , typename A10 >
NiceMock (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7, const A8 &a8, const A9 &a9, const A10 &a10)
virtual ~NiceMock ()
NiceMock ()
template<typename A1 >
NiceMock (const A1 &a1)
template<typename A1 , typename A2 >
NiceMock (const A1 &a1, const A2 &a2)
template<typename A1 , typename A2 , typename A3 >
NiceMock (const A1 &a1, const A2 &a2, const A3 &a3)
template<typename A1 , typename A2 , typename A3 , typename A4 >
NiceMock (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4)
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 >
NiceMock (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5)
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 >
NiceMock (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6)
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 >
NiceMock (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7)
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 >
NiceMock (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7, const A8 &a8)
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 >
NiceMock (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7, const A8 &a8, const A9 &a9)
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 , typename A10 >
NiceMock (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7, const A8 &a8, const A9 &a9, const A10 &a10)
virtual ~NiceMock ()
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (NiceMock)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (NiceMock)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (NiceMock)
Detailed Description
template<class MockClass>
class testing::NiceMock< MockClass >
Definition at line 80 of file gmock-generated-nice-strict.h.
Constructor & Destructor Documentation
template<class MockClass> testing::NiceMock< MockClass >::NiceMock () inline
Definition at line 84 of file gmock-generated-nice-strict.h.
              {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1) inline explicit
Definition at line 92 of file gmock-generated-nice-strict.h.
                                   : MockClass(a1) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 , typename A2 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1, const A2 & a2) inline
Definition at line 97 of file gmock-generated-nice-strict.h.
                                        : MockClass(a1, a2) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 , typename A2 , typename A3 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1, const A2 & a2, const A3 & a3) inline
Definition at line 103 of file gmock-generated-nice-strict.h.
                                                      : MockClass(a1, a2, a3) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 , typename A2 , typename A3 , typename A4 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4) inline
Definition at line 109 of file gmock-generated-nice-strict.h.
                     : MockClass(a1, a2, a3, a4) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5) inline
Definition at line 116 of file gmock-generated-nice-strict.h.
                     : MockClass(a1, a2, a3, a4, a5) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6) inline
Definition at line 124 of file gmock-generated-nice-strict.h.
                                   : MockClass(a1, a2, a3, a4, a5, a6) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7) inline
Definition at line 132 of file gmock-generated-nice-strict.h.
                                                 : MockClass(a1, a2, a3, a4, a5,
       a6, a7) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7, const A8 & a8) inline
Definition at line 141 of file gmock-generated-nice-strict.h.
                                                               : MockClass(a1,
       a2, a3, a4, a5, a6, a7, a8) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7, const A8 & a8, const A9 & a9) inline
Definition at line 150 of file gmock-generated-nice-strict.h.
                     : MockClass(a1, a2, a3, a4, a5, a6, a7, a8, a9) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 , typename A10 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7, const A8 & a8, const A9 & a9, const A10 & a10) inline
Definition at line 159 of file gmock-generated-nice-strict.h.
                       : MockClass(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> virtual testing::NiceMock< MockClass >::~NiceMock () inline virtual
Definition at line 166 of file gmock-generated-nice-strict.h.
                       {
     ::testing::Mock::UnregisterCallReaction(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> testing::NiceMock< MockClass >::NiceMock () inline
Definition at line 84 of file gmock-generated-nice-strict.h.
              {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1) inline explicit
Definition at line 92 of file gmock-generated-nice-strict.h.
                                   : MockClass(a1) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 , typename A2 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1, const A2 & a2) inline
Definition at line 97 of file gmock-generated-nice-strict.h.
                                        : MockClass(a1, a2) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 , typename A2 , typename A3 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1, const A2 & a2, const A3 & a3) inline
Definition at line 103 of file gmock-generated-nice-strict.h.
                                                      : MockClass(a1, a2, a3) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 , typename A2 , typename A3 , typename A4 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4) inline
Definition at line 109 of file gmock-generated-nice-strict.h.
                     : MockClass(a1, a2, a3, a4) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5) inline
Definition at line 116 of file gmock-generated-nice-strict.h.
                     : MockClass(a1, a2, a3, a4, a5) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6) inline
Definition at line 124 of file gmock-generated-nice-strict.h.
                                   : MockClass(a1, a2, a3, a4, a5, a6) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7) inline
Definition at line 132 of file gmock-generated-nice-strict.h.
                                                 : MockClass(a1, a2, a3, a4, a5,
       a6, a7) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7, const A8 & a8) inline
Definition at line 141 of file gmock-generated-nice-strict.h.
                                                               : MockClass(a1,
       a2, a3, a4, a5, a6, a7, a8) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7, const A8 & a8, const A9 & a9) inline
Definition at line 150 of file gmock-generated-nice-strict.h.
                     : MockClass(a1, a2, a3, a4, a5, a6, a7, a8, a9) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 , typename A10 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7, const A8 & a8, const A9 & a9, const A10 & a10) inline
Definition at line 159 of file gmock-generated-nice-strict.h.
                       : MockClass(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> virtual testing::NiceMock< MockClass >::~NiceMock () inline virtual
Definition at line 166 of file gmock-generated-nice-strict.h.
                       {
     ::testing::Mock::UnregisterCallReaction(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> testing::NiceMock< MockClass >::NiceMock () inline
Definition at line 84 of file gmock-generated-nice-strict.h.
              {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1) inline explicit
Definition at line 92 of file gmock-generated-nice-strict.h.
                                   : MockClass(a1) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 , typename A2 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1, const A2 & a2) inline
Definition at line 97 of file gmock-generated-nice-strict.h.
                                        : MockClass(a1, a2) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 , typename A2 , typename A3 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1, const A2 & a2, const A3 & a3) inline
Definition at line 103 of file gmock-generated-nice-strict.h.
                                                      : MockClass(a1, a2, a3) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 , typename A2 , typename A3 , typename A4 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4) inline
Definition at line 109 of file gmock-generated-nice-strict.h.
                     : MockClass(a1, a2, a3, a4) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5) inline
Definition at line 116 of file gmock-generated-nice-strict.h.
                     : MockClass(a1, a2, a3, a4, a5) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6) inline
Definition at line 124 of file gmock-generated-nice-strict.h.
                                   : MockClass(a1, a2, a3, a4, a5, a6) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7) inline
Definition at line 132 of file gmock-generated-nice-strict.h.
                                                 : MockClass(a1, a2, a3, a4, a5,
       a6, a7) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7, const A8 & a8) inline
Definition at line 141 of file gmock-generated-nice-strict.h.
                                                               : MockClass(a1,
       a2, a3, a4, a5, a6, a7, a8) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7, const A8 & a8, const A9 & a9) inline
Definition at line 150 of file gmock-generated-nice-strict.h.
                     : MockClass(a1, a2, a3, a4, a5, a6, a7, a8, a9) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 , typename A10 > testing::NiceMock< MockClass >::NiceMock (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7, const A8 & a8, const A9 & a9, const A10 & a10) inline
Definition at line 159 of file gmock-generated-nice-strict.h.
                       : MockClass(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10) {
     ::testing::Mock::AllowUninterestingCalls(
         internal::ImplicitCast_<MockClass*>(this));
   }
template<class MockClass> virtual testing::NiceMock< MockClass >::~NiceMock () inline virtual
Definition at line 166 of file gmock-generated-nice-strict.h.
                       {
     ::testing::Mock::UnregisterCallReaction(
         internal::ImplicitCast_<MockClass*>(this));
   }
Member Function Documentation
template<class MockClass> testing::NiceMock< MockClass >::GTEST_DISALLOW_COPY_AND_ASSIGN_ (NiceMock< MockClass >) private
Referenced by testing::NaggyMock< MockFoo >::~NaggyMock(), testing::NiceMock< MockSubscriber< int, std::string > >::~NiceMock(), and testing::StrictMock< fizz::test::ConcreteReadRecordLayer >::~StrictMock().
template<class MockClass> testing::NiceMock< MockClass >::GTEST_DISALLOW_COPY_AND_ASSIGN_ (NiceMock< MockClass >) private
template<class MockClass> testing::NiceMock< MockClass >::GTEST_DISALLOW_COPY_AND_ASSIGN_ (NiceMock< MockClass >) private
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-generated-nice-strict.h