proxygen: testing::internal::EndsWithMatcher< StringType > Class Template Reference
testing::internal::EndsWithMatcher< StringType > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
EndsWithMatcher (const StringType &suffix)
template<typename CharType >
bool MatchAndExplain (CharType *s, MatchResultListener *listener) const
template<typename MatcheeStringType >
bool MatchAndExplain (const MatcheeStringType &s, MatchResultListener *) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
EndsWithMatcher (const StringType &suffix)
template<typename CharType >
bool MatchAndExplain (CharType *s, MatchResultListener *listener) const
template<typename MatcheeStringType >
bool MatchAndExplain (const MatcheeStringType &s, MatchResultListener *) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
EndsWithMatcher (const StringType &suffix)
template<typename CharType >
bool MatchAndExplain (CharType *s, MatchResultListener *listener) const
template<typename MatcheeStringType >
bool MatchAndExplain (const MatcheeStringType &s, MatchResultListener *) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (EndsWithMatcher)
GTEST_DISALLOW_ASSIGN_ (EndsWithMatcher)
GTEST_DISALLOW_ASSIGN_ (EndsWithMatcher)
Private Attributes
const StringType suffix_
Detailed Description
template<typename StringType>
class testing::internal::EndsWithMatcher< StringType >
Definition at line 1281 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename StringType > testing::internal::EndsWithMatcher< StringType >::EndsWithMatcher (const StringType & suffix) inline explicit
Definition at line 1283 of file gmock-matchers.h.
 : suffix_(suffix) {}
template<typename StringType > testing::internal::EndsWithMatcher< StringType >::EndsWithMatcher (const StringType & suffix) inline explicit
Definition at line 1283 of file gmock-matchers.h.
 : suffix_(suffix) {}
template<typename StringType > testing::internal::EndsWithMatcher< StringType >::EndsWithMatcher (const StringType & suffix) inline explicit
Definition at line 1283 of file gmock-matchers.h.
 : suffix_(suffix) {}
Member Function Documentation
template<typename StringType > void testing::internal::EndsWithMatcher< StringType >::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 1312 of file gmock-matchers.h.
References testing::internal::UniversalPrint().
{
     *os << "doesn't end with ";
     UniversalPrint(suffix_, os);
   }
template<typename StringType > void testing::internal::EndsWithMatcher< StringType >::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 1312 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, and testing::internal::UniversalPrint().
{
     *os << "doesn't end with ";
     UniversalPrint(suffix_, os);
   }
template<typename StringType > void testing::internal::EndsWithMatcher< StringType >::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 1312 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, and testing::internal::UniversalPrint().
{
     *os << "doesn't end with ";
     UniversalPrint(suffix_, os);
   }
template<typename StringType > void testing::internal::EndsWithMatcher< StringType >::DescribeTo (::std::ostream * os) const inline
Definition at line 1307 of file gmock-matchers.h.
References testing::internal::UniversalPrint().
{
     *os << "ends with ";
     UniversalPrint(suffix_, os);
   }
template<typename StringType > void testing::internal::EndsWithMatcher< StringType >::DescribeTo (::std::ostream * os) const inline
Definition at line 1307 of file gmock-matchers.h.
References testing::internal::UniversalPrint().
{
     *os << "ends with ";
     UniversalPrint(suffix_, os);
   }
template<typename StringType > void testing::internal::EndsWithMatcher< StringType >::DescribeTo (::std::ostream * os) const inline
Definition at line 1307 of file gmock-matchers.h.
References testing::internal::UniversalPrint().
{
     *os << "ends with ";
     UniversalPrint(suffix_, os);
   }
template<typename StringType > testing::internal::EndsWithMatcher< StringType >::GTEST_DISALLOW_ASSIGN_ (EndsWithMatcher< StringType >) private
template<typename StringType > testing::internal::EndsWithMatcher< StringType >::GTEST_DISALLOW_ASSIGN_ (EndsWithMatcher< StringType >) private
template<typename StringType > testing::internal::EndsWithMatcher< StringType >::GTEST_DISALLOW_ASSIGN_ (EndsWithMatcher< StringType >) private
template<typename StringType > template<typename CharType > bool testing::internal::EndsWithMatcher< StringType >::MatchAndExplain (CharType * s, MatchResultListener * listener) const inline
Definition at line 1291 of file gmock-matchers.h.
{
     return s != NULL && MatchAndExplain(StringType(s), listener);
   }
template<typename StringType > template<typename CharType > bool testing::internal::EndsWithMatcher< StringType >::MatchAndExplain (CharType * s, MatchResultListener * listener) const inline
Definition at line 1291 of file gmock-matchers.h.
{
     return s != NULL && MatchAndExplain(StringType(s), listener);
   }
template<typename StringType > template<typename CharType > bool testing::internal::EndsWithMatcher< StringType >::MatchAndExplain (CharType * s, MatchResultListener * listener) const inline
Definition at line 1291 of file gmock-matchers.h.
{
     return s != NULL && MatchAndExplain(StringType(s), listener);
   }
template<typename StringType > template<typename MatcheeStringType > bool testing::internal::EndsWithMatcher< StringType >::MatchAndExplain (const MatcheeStringType & s, MatchResultListener *) const inline
Definition at line 1300 of file gmock-matchers.h.
{
     const StringType& s2(s);
     return s2.length() >= suffix_.length() &&
         s2.substr(s2.length() - suffix_.length()) == suffix_;
   }
template<typename StringType > template<typename MatcheeStringType > bool testing::internal::EndsWithMatcher< StringType >::MatchAndExplain (const MatcheeStringType & s, MatchResultListener *) const inline
Definition at line 1300 of file gmock-matchers.h.
{
     const StringType& s2(s);
     return s2.length() >= suffix_.length() &&
         s2.substr(s2.length() - suffix_.length()) == suffix_;
   }
template<typename StringType > template<typename MatcheeStringType > bool testing::internal::EndsWithMatcher< StringType >::MatchAndExplain (const MatcheeStringType & s, MatchResultListener *) const inline
Definition at line 1300 of file gmock-matchers.h.
{
     const StringType& s2(s);
     return s2.length() >= suffix_.length() &&
         s2.substr(s2.length() - suffix_.length()) == suffix_;
   }
Member Data Documentation
template<typename StringType > const StringType testing::internal::EndsWithMatcher< StringType >::suffix_ private
Definition at line 1318 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h