proxygen: cpp.gmock_class_test.GenerateMethodsTest Class Reference
cpp.gmock_class_test.GenerateMethodsTest Class Reference
Public Member Functions
def GenerateMethodSource (self, cpp_source)
def testSimpleMethod (self)
def testSimpleConstructorsAndDestructor (self)
def testVirtualDestructor (self)
def testExplicitlyDefaultedConstructorsAndDestructor (self)
def testExplicitlyDeletedConstructorsAndDestructor (self)
def testSimpleOverrideMethod (self)
def testSimpleConstMethod (self)
def testExplicitVoid (self)
def testStrangeNewlineInParameter (self)
def testDefaultParameters (self)
def testMultipleDefaultParameters (self)
def testRemovesCommentsWhenDefaultsArePresent (self)
def testDoubleSlashCommentsInParameterListAreRemoved (self)
def testCStyleCommentsInParameterListAreNotRemoved (self)
def testArgsOfTemplateTypes (self)
def testReturnTypeWithOneTemplateArg (self)
def testReturnTypeWithManyTemplateArgs (self)
def testSimpleMethodInTemplatedClass (self)
def testPointerArgWithoutNames (self)
def testReferenceArgWithoutNames (self)
def testArrayArgWithoutNames (self)
def GenerateMethodSource (self, cpp_source)
def testSimpleMethod (self)
def testSimpleConstructorsAndDestructor (self)
def testVirtualDestructor (self)
def testExplicitlyDefaultedConstructorsAndDestructor (self)
def testExplicitlyDeletedConstructorsAndDestructor (self)
def testSimpleOverrideMethod (self)
def testSimpleConstMethod (self)
def testExplicitVoid (self)
def testStrangeNewlineInParameter (self)
def testDefaultParameters (self)
def testMultipleDefaultParameters (self)
def testRemovesCommentsWhenDefaultsArePresent (self)
def testDoubleSlashCommentsInParameterListAreRemoved (self)
def testCStyleCommentsInParameterListAreNotRemoved (self)
def testArgsOfTemplateTypes (self)
def testReturnTypeWithOneTemplateArg (self)
def testReturnTypeWithManyTemplateArgs (self)
def testSimpleMethodInTemplatedClass (self)
def testPointerArgWithoutNames (self)
def testReferenceArgWithoutNames (self)
def testArrayArgWithoutNames (self)
def GenerateMethodSource (self, cpp_source)
def testSimpleMethod (self)
def testSimpleConstructorsAndDestructor (self)
def testVirtualDestructor (self)
def testExplicitlyDefaultedConstructorsAndDestructor (self)
def testExplicitlyDeletedConstructorsAndDestructor (self)
def testSimpleOverrideMethod (self)
def testSimpleConstMethod (self)
def testExplicitVoid (self)
def testStrangeNewlineInParameter (self)
def testDefaultParameters (self)
def testMultipleDefaultParameters (self)
def testRemovesCommentsWhenDefaultsArePresent (self)
def testDoubleSlashCommentsInParameterListAreRemoved (self)
def testCStyleCommentsInParameterListAreNotRemoved (self)
def testArgsOfTemplateTypes (self)
def testReturnTypeWithOneTemplateArg (self)
def testReturnTypeWithManyTemplateArgs (self)
def testSimpleMethodInTemplatedClass (self)
def testPointerArgWithoutNames (self)
def testReferenceArgWithoutNames (self)
def testArrayArgWithoutNames (self)
Public Member Functions inherited from cpp.gmock_class_test.TestCase
def StripLeadingWhitespace (self, lines)
def assertEqualIgnoreLeadingWhitespace (self, expected_lines, lines)
def StripLeadingWhitespace (self, lines)
def assertEqualIgnoreLeadingWhitespace (self, expected_lines, lines)
def StripLeadingWhitespace (self, lines)
def assertEqualIgnoreLeadingWhitespace (self, expected_lines, lines)
Detailed Description
Definition at line 46 of file gmock_class_test.py.
Member Function Documentation
def cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource (self, cpp_source)
Convert C++ source to Google Mock output source lines.
Definition at line 48 of file gmock_class_test.py.
References join, and bm.list.
Referenced by cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), cpp.gmock_class_test.GenerateMethodsTest.testArgsOfTemplateTypes(), cpp.gmock_class_test.GenerateMethodsTest.testArrayArgWithoutNames(), cpp.gmock_class_test.GenerateMethodsTest.testCStyleCommentsInParameterListAreNotRemoved(), cpp.gmock_class_test.GenerateMethodsTest.testDefaultParameters(), cpp.gmock_class_test.GenerateMethodsTest.testDoubleSlashCommentsInParameterListAreRemoved(), cpp.gmock_class_test.GenerateMethodsTest.testExplicitlyDefaultedConstructorsAndDestructor(), cpp.gmock_class_test.GenerateMethodsTest.testExplicitlyDeletedConstructorsAndDestructor(), cpp.gmock_class_test.GenerateMethodsTest.testExplicitVoid(), cpp.gmock_class_test.GenerateMethodsTest.testMultipleDefaultParameters(), cpp.gmock_class_test.GenerateMethodsTest.testPointerArgWithoutNames(), cpp.gmock_class_test.GenerateMethodsTest.testReferenceArgWithoutNames(), cpp.gmock_class_test.GenerateMethodsTest.testRemovesCommentsWhenDefaultsArePresent(), cpp.gmock_class_test.GenerateMethodsTest.testReturnTypeWithManyTemplateArgs(), cpp.gmock_class_test.GenerateMethodsTest.testReturnTypeWithOneTemplateArg(), cpp.gmock_class_test.GenerateMethodsTest.testSimpleConstMethod(), cpp.gmock_class_test.GenerateMethodsTest.testSimpleConstructorsAndDestructor(), cpp.gmock_class_test.GenerateMethodsTest.testSimpleMethod(), cpp.gmock_class_test.GenerateMethodsTest.testSimpleMethodInTemplatedClass(), cpp.gmock_class_test.GenerateMethodsTest.testSimpleOverrideMethod(), cpp.gmock_class_test.GenerateMethodsTest.testStrangeNewlineInParameter(), and cpp.gmock_class_test.GenerateMethodsTest.testVirtualDestructor().
   def GenerateMethodSource(self, cpp_source):
     """Convert C++ source to Google Mock output source lines."""
     method_source_lines = []
     # <test> is a pseudo-filename, it is not read or written.
     builder = ast.BuilderFromSource(cpp_source, '<test>')
     ast_list = list(builder.Generate())
     gmock_class._GenerateMethods(method_source_lines, cpp_source, ast_list[0])
     return '\n'.join(method_source_lines)
def cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource (self, cpp_source)
Convert C++ source to Google Mock output source lines.
Definition at line 48 of file gmock_class_test.py.
References cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), join, and bm.list.
   def GenerateMethodSource(self, cpp_source):
     """Convert C++ source to Google Mock output source lines."""
     method_source_lines = []
     # <test> is a pseudo-filename, it is not read or written.
     builder = ast.BuilderFromSource(cpp_source, '<test>')
     ast_list = list(builder.Generate())
     gmock_class._GenerateMethods(method_source_lines, cpp_source, ast_list[0])
     return '\n'.join(method_source_lines)
def cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource (self, cpp_source)
Convert C++ source to Google Mock output source lines.
Definition at line 48 of file gmock_class_test.py.
References cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), join, and bm.list.
   def GenerateMethodSource(self, cpp_source):
     """Convert C++ source to Google Mock output source lines."""
     method_source_lines = []
     # <test> is a pseudo-filename, it is not read or written.
     builder = ast.BuilderFromSource(cpp_source, '<test>')
     ast_list = list(builder.Generate())
     gmock_class._GenerateMethods(method_source_lines, cpp_source, ast_list[0])
     return '\n'.join(method_source_lines)
def cpp.gmock_class_test.GenerateMethodsTest.testArgsOfTemplateTypes (self)
Definition at line 236 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testArgsOfTemplateTypes().
   def testArgsOfTemplateTypes(self):
     source = """
 class Foo {
  public:
   virtual int Bar(const vector<int>& v, map<int, string>* output);
 };"""
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD2(Bar,\n'
         'int(const vector<int>& v, map<int, string>* output));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testArgsOfTemplateTypes (self)
Definition at line 236 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), and cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource().
Referenced by cpp.gmock_class_test.GenerateMethodsTest.testArgsOfTemplateTypes().
   def testArgsOfTemplateTypes(self):
     source = """
 class Foo {
  public:
   virtual int Bar(const vector<int>& v, map<int, string>* output);
 };"""
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD2(Bar,\n'
         'int(const vector<int>& v, map<int, string>* output));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testArgsOfTemplateTypes (self)
Definition at line 236 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testArgsOfTemplateTypes().
   def testArgsOfTemplateTypes(self):
     source = """
 class Foo {
  public:
   virtual int Bar(const vector<int>& v, map<int, string>* output);
 };"""
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD2(Bar,\n'
         'int(const vector<int>& v, map<int, string>* output));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testArrayArgWithoutNames (self)
Definition at line 304 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testArrayArgWithoutNames().
   def testArrayArgWithoutNames(self):
     source = """
 class Foo {
   virtual int Bar(C[]);
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD1(Bar,\nint(C[]));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testArrayArgWithoutNames (self)
Definition at line 304 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), and cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource().
Referenced by cpp.gmock_class_test.GenerateMethodsTest.testArrayArgWithoutNames().
   def testArrayArgWithoutNames(self):
     source = """
 class Foo {
   virtual int Bar(C[]);
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD1(Bar,\nint(C[]));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testArrayArgWithoutNames (self)
Definition at line 304 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testArrayArgWithoutNames().
   def testArrayArgWithoutNames(self):
     source = """
 class Foo {
   virtual int Bar(C[]);
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD1(Bar,\nint(C[]));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testCStyleCommentsInParameterListAreNotRemoved (self)
Definition at line 222 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testCStyleCommentsInParameterListAreNotRemoved().
   def testCStyleCommentsInParameterListAreNotRemoved(self):
     # NOTE(nnorwitz): I'm not sure if it's the best behavior to keep these
     # comments.  Also note that C style comments after the last parameter
     # are still elided.
     source = """
 class Foo {
  public:
   virtual const string& Bar(int /* keeper */, int b);
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD2(Bar,\nconst string&(int /* keeper */, int b));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testCStyleCommentsInParameterListAreNotRemoved (self)
Definition at line 222 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), and cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource().
Referenced by cpp.gmock_class_test.GenerateMethodsTest.testCStyleCommentsInParameterListAreNotRemoved().
   def testCStyleCommentsInParameterListAreNotRemoved(self):
     # NOTE(nnorwitz): I'm not sure if it's the best behavior to keep these
     # comments.  Also note that C style comments after the last parameter
     # are still elided.
     source = """
 class Foo {
  public:
   virtual const string& Bar(int /* keeper */, int b);
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD2(Bar,\nconst string&(int /* keeper */, int b));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testCStyleCommentsInParameterListAreNotRemoved (self)
Definition at line 222 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testCStyleCommentsInParameterListAreNotRemoved().
   def testCStyleCommentsInParameterListAreNotRemoved(self):
     # NOTE(nnorwitz): I'm not sure if it's the best behavior to keep these
     # comments.  Also note that C style comments after the last parameter
     # are still elided.
     source = """
 class Foo {
  public:
   virtual const string& Bar(int /* keeper */, int b);
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD2(Bar,\nconst string&(int /* keeper */, int b));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testDefaultParameters (self)
Definition at line 175 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testDefaultParameters().
   def testDefaultParameters(self):
     source = """
 class Foo {
  public:
   virtual void Bar(int a, char c = 'x') = 0;
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD2(Bar,\nvoid(int, char));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testDefaultParameters (self)
Definition at line 175 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), and cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource().
Referenced by cpp.gmock_class_test.GenerateMethodsTest.testDefaultParameters().
   def testDefaultParameters(self):
     source = """
 class Foo {
  public:
   virtual void Bar(int a, char c = 'x') = 0;
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD2(Bar,\nvoid(int, char));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testDefaultParameters (self)
Definition at line 175 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testDefaultParameters().
   def testDefaultParameters(self):
     source = """
 class Foo {
  public:
   virtual void Bar(int a, char c = 'x') = 0;
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD2(Bar,\nvoid(int, char));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testDoubleSlashCommentsInParameterListAreRemoved (self)
Definition at line 209 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testDoubleSlashCommentsInParameterListAreRemoved().
   def testDoubleSlashCommentsInParameterListAreRemoved(self):
     source = """
 class Foo {
  public:
   virtual void Bar(int a,  // inline comments should be elided.
                    int b   // inline comments should be elided.
                    ) const = 0;
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_CONST_METHOD2(Bar,\nvoid(int a, int b));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testDoubleSlashCommentsInParameterListAreRemoved (self)
Definition at line 209 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), and cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource().
Referenced by cpp.gmock_class_test.GenerateMethodsTest.testDoubleSlashCommentsInParameterListAreRemoved().
   def testDoubleSlashCommentsInParameterListAreRemoved(self):
     source = """
 class Foo {
  public:
   virtual void Bar(int a,  // inline comments should be elided.
                    int b   // inline comments should be elided.
                    ) const = 0;
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_CONST_METHOD2(Bar,\nvoid(int a, int b));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testDoubleSlashCommentsInParameterListAreRemoved (self)
Definition at line 209 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testDoubleSlashCommentsInParameterListAreRemoved().
   def testDoubleSlashCommentsInParameterListAreRemoved(self):
     source = """
 class Foo {
  public:
   virtual void Bar(int a,  // inline comments should be elided.
                    int b   // inline comments should be elided.
                    ) const = 0;
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_CONST_METHOD2(Bar,\nvoid(int a, int b));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testExplicitlyDefaultedConstructorsAndDestructor (self)
Definition at line 98 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), and cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource().
Referenced by cpp.gmock_class_test.GenerateMethodsTest.testExplicitlyDefaultedConstructorsAndDestructor().
   def testExplicitlyDefaultedConstructorsAndDestructor(self):
     source = """
 class Foo {
  public:
   Foo() = default;
   Foo(const Foo& f) = default;
   Foo(Foo&& f) = default;
   ~Foo() = default;
   virtual int Bar() = 0;
 };
 """
     # The constructors and destructor should be ignored.
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD0(Bar,\nint());',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testExplicitlyDefaultedConstructorsAndDestructor (self)
Definition at line 98 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testExplicitlyDefaultedConstructorsAndDestructor().
   def testExplicitlyDefaultedConstructorsAndDestructor(self):
     source = """
 class Foo {
  public:
   Foo() = default;
   Foo(const Foo& f) = default;
   Foo(Foo&& f) = default;
   ~Foo() = default;
   virtual int Bar() = 0;
 };
 """
     # The constructors and destructor should be ignored.
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD0(Bar,\nint());',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testExplicitlyDefaultedConstructorsAndDestructor (self)
Definition at line 98 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testExplicitlyDefaultedConstructorsAndDestructor().
   def testExplicitlyDefaultedConstructorsAndDestructor(self):
     source = """
 class Foo {
  public:
   Foo() = default;
   Foo(const Foo& f) = default;
   Foo(Foo&& f) = default;
   ~Foo() = default;
   virtual int Bar() = 0;
 };
 """
     # The constructors and destructor should be ignored.
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD0(Bar,\nint());',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testExplicitlyDeletedConstructorsAndDestructor (self)
Definition at line 114 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testExplicitlyDeletedConstructorsAndDestructor().
   def testExplicitlyDeletedConstructorsAndDestructor(self):
     source = """
 class Foo {
  public:
   Foo() = delete;
   Foo(const Foo& f) = delete;
   Foo(Foo&& f) = delete;
   ~Foo() = delete;
   virtual int Bar() = 0;
 };
 """
     # The constructors and destructor should be ignored.
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD0(Bar,\nint());',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testExplicitlyDeletedConstructorsAndDestructor (self)
Definition at line 114 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testExplicitlyDeletedConstructorsAndDestructor().
   def testExplicitlyDeletedConstructorsAndDestructor(self):
     source = """
 class Foo {
  public:
   Foo() = delete;
   Foo(const Foo& f) = delete;
   Foo(Foo&& f) = delete;
   ~Foo() = delete;
   virtual int Bar() = 0;
 };
 """
     # The constructors and destructor should be ignored.
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD0(Bar,\nint());',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testExplicitlyDeletedConstructorsAndDestructor (self)
Definition at line 114 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), and cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource().
Referenced by cpp.gmock_class_test.GenerateMethodsTest.testExplicitlyDeletedConstructorsAndDestructor().
   def testExplicitlyDeletedConstructorsAndDestructor(self):
     source = """
 class Foo {
  public:
   Foo() = delete;
   Foo(const Foo& f) = delete;
   Foo(Foo&& f) = delete;
   ~Foo() = delete;
   virtual int Bar() = 0;
 };
 """
     # The constructors and destructor should be ignored.
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD0(Bar,\nint());',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testExplicitVoid (self)
Definition at line 152 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), and cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource().
Referenced by cpp.gmock_class_test.GenerateMethodsTest.testExplicitVoid().
   def testExplicitVoid(self):
     source = """
 class Foo {
  public:
   virtual int Bar(void);
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD0(Bar,\nint(void));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testExplicitVoid (self)
Definition at line 152 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testExplicitVoid().
   def testExplicitVoid(self):
     source = """
 class Foo {
  public:
   virtual int Bar(void);
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD0(Bar,\nint(void));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testExplicitVoid (self)
Definition at line 152 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testExplicitVoid().
   def testExplicitVoid(self):
     source = """
 class Foo {
  public:
   virtual int Bar(void);
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD0(Bar,\nint(void));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testMultipleDefaultParameters (self)
Definition at line 186 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testMultipleDefaultParameters().
   def testMultipleDefaultParameters(self):
     source = """
 class Foo {
  public:
   virtual void Bar(int a = 42, char c = 'x') = 0;
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD2(Bar,\nvoid(int, char));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testMultipleDefaultParameters (self)
Definition at line 186 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), and cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource().
Referenced by cpp.gmock_class_test.GenerateMethodsTest.testMultipleDefaultParameters().
   def testMultipleDefaultParameters(self):
     source = """
 class Foo {
  public:
   virtual void Bar(int a = 42, char c = 'x') = 0;
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD2(Bar,\nvoid(int, char));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testMultipleDefaultParameters (self)
Definition at line 186 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testMultipleDefaultParameters().
   def testMultipleDefaultParameters(self):
     source = """
 class Foo {
  public:
   virtual void Bar(int a = 42, char c = 'x') = 0;
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD2(Bar,\nvoid(int, char));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testPointerArgWithoutNames (self)
Definition at line 284 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testPointerArgWithoutNames().
   def testPointerArgWithoutNames(self):
     source = """
 class Foo {
   virtual int Bar(C*);
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD1(Bar,\nint(C*));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testPointerArgWithoutNames (self)
Definition at line 284 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), and cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource().
Referenced by cpp.gmock_class_test.GenerateMethodsTest.testPointerArgWithoutNames().
   def testPointerArgWithoutNames(self):
     source = """
 class Foo {
   virtual int Bar(C*);
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD1(Bar,\nint(C*));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testPointerArgWithoutNames (self)
Definition at line 284 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testPointerArgWithoutNames().
   def testPointerArgWithoutNames(self):
     source = """
 class Foo {
   virtual int Bar(C*);
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD1(Bar,\nint(C*));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testReferenceArgWithoutNames (self)
Definition at line 294 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testReferenceArgWithoutNames().
   def testReferenceArgWithoutNames(self):
     source = """
 class Foo {
   virtual int Bar(C&);
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD1(Bar,\nint(C&));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testReferenceArgWithoutNames (self)
Definition at line 294 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testReferenceArgWithoutNames().
   def testReferenceArgWithoutNames(self):
     source = """
 class Foo {
   virtual int Bar(C&);
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD1(Bar,\nint(C&));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testReferenceArgWithoutNames (self)
Definition at line 294 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), and cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource().
Referenced by cpp.gmock_class_test.GenerateMethodsTest.testReferenceArgWithoutNames().
   def testReferenceArgWithoutNames(self):
     source = """
 class Foo {
   virtual int Bar(C&);
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD1(Bar,\nint(C&));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testRemovesCommentsWhenDefaultsArePresent (self)
Definition at line 197 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testRemovesCommentsWhenDefaultsArePresent().
   def testRemovesCommentsWhenDefaultsArePresent(self):
     source = """
 class Foo {
  public:
   virtual void Bar(int a = 42 /* a comment */,
                    char /* other comment */ c= 'x') = 0;
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD2(Bar,\nvoid(int, char));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testRemovesCommentsWhenDefaultsArePresent (self)
Definition at line 197 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), and cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource().
Referenced by cpp.gmock_class_test.GenerateMethodsTest.testRemovesCommentsWhenDefaultsArePresent().
   def testRemovesCommentsWhenDefaultsArePresent(self):
     source = """
 class Foo {
  public:
   virtual void Bar(int a = 42 /* a comment */,
                    char /* other comment */ c= 'x') = 0;
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD2(Bar,\nvoid(int, char));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testRemovesCommentsWhenDefaultsArePresent (self)
Definition at line 197 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testRemovesCommentsWhenDefaultsArePresent().
   def testRemovesCommentsWhenDefaultsArePresent(self):
     source = """
 class Foo {
  public:
   virtual void Bar(int a = 42 /* a comment */,
                    char /* other comment */ c= 'x') = 0;
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD2(Bar,\nvoid(int, char));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testReturnTypeWithManyTemplateArgs (self)
Definition at line 257 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), and cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource().
Referenced by cpp.gmock_class_test.GenerateMethodsTest.testReturnTypeWithManyTemplateArgs().
   def testReturnTypeWithManyTemplateArgs(self):
     source = """
 class Foo {
  public:
   virtual map<int, string> Bar();
 };"""
     # Comparing the comment text is brittle - we'll think of something
     # better in case this gets annoying, but for now let's keep it simple.
     self.assertEqualIgnoreLeadingWhitespace(
         '// The following line won\'t really compile, as the return\n'
         '// type has multiple template arguments.  To fix it, use a\n'
         '// typedef for the return type.\n'
         'MOCK_METHOD0(Bar,\nmap<int, string>());',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testReturnTypeWithManyTemplateArgs (self)
Definition at line 257 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testReturnTypeWithManyTemplateArgs().
   def testReturnTypeWithManyTemplateArgs(self):
     source = """
 class Foo {
  public:
   virtual map<int, string> Bar();
 };"""
     # Comparing the comment text is brittle - we'll think of something
     # better in case this gets annoying, but for now let's keep it simple.
     self.assertEqualIgnoreLeadingWhitespace(
         '// The following line won\'t really compile, as the return\n'
         '// type has multiple template arguments.  To fix it, use a\n'
         '// typedef for the return type.\n'
         'MOCK_METHOD0(Bar,\nmap<int, string>());',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testReturnTypeWithManyTemplateArgs (self)
Definition at line 257 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testReturnTypeWithManyTemplateArgs().
   def testReturnTypeWithManyTemplateArgs(self):
     source = """
 class Foo {
  public:
   virtual map<int, string> Bar();
 };"""
     # Comparing the comment text is brittle - we'll think of something
     # better in case this gets annoying, but for now let's keep it simple.
     self.assertEqualIgnoreLeadingWhitespace(
         '// The following line won\'t really compile, as the return\n'
         '// type has multiple template arguments.  To fix it, use a\n'
         '// typedef for the return type.\n'
         'MOCK_METHOD0(Bar,\nmap<int, string>());',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testReturnTypeWithOneTemplateArg (self)
Definition at line 247 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), and cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource().
Referenced by cpp.gmock_class_test.GenerateMethodsTest.testReturnTypeWithOneTemplateArg().
   def testReturnTypeWithOneTemplateArg(self):
     source = """
 class Foo {
  public:
   virtual vector<int>* Bar(int n);
 };"""
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD1(Bar,\nvector<int>*(int n));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testReturnTypeWithOneTemplateArg (self)
Definition at line 247 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testReturnTypeWithOneTemplateArg().
   def testReturnTypeWithOneTemplateArg(self):
     source = """
 class Foo {
  public:
   virtual vector<int>* Bar(int n);
 };"""
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD1(Bar,\nvector<int>*(int n));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testReturnTypeWithOneTemplateArg (self)
Definition at line 247 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testReturnTypeWithOneTemplateArg().
   def testReturnTypeWithOneTemplateArg(self):
     source = """
 class Foo {
  public:
   virtual vector<int>* Bar(int n);
 };"""
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD1(Bar,\nvector<int>*(int n));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testSimpleConstMethod (self)
Definition at line 141 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), and cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource().
Referenced by cpp.gmock_class_test.GenerateMethodsTest.testSimpleConstMethod().
   def testSimpleConstMethod(self):
     source = """
 class Foo {
  public:
   virtual void Bar(bool flag) const;
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_CONST_METHOD1(Bar,\nvoid(bool flag));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testSimpleConstMethod (self)
Definition at line 141 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testSimpleConstMethod().
   def testSimpleConstMethod(self):
     source = """
 class Foo {
  public:
   virtual void Bar(bool flag) const;
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_CONST_METHOD1(Bar,\nvoid(bool flag));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testSimpleConstMethod (self)
Definition at line 141 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testSimpleConstMethod().
   def testSimpleConstMethod(self):
     source = """
 class Foo {
  public:
   virtual void Bar(bool flag) const;
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_CONST_METHOD1(Bar,\nvoid(bool flag));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testSimpleConstructorsAndDestructor (self)
Definition at line 68 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), and cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource().
Referenced by cpp.gmock_class_test.GenerateMethodsTest.testSimpleConstructorsAndDestructor().
   def testSimpleConstructorsAndDestructor(self):
     source = """
 class Foo {
  public:
   Foo();
   Foo(int x);
   Foo(const Foo& f);
   Foo(Foo&& f);
   ~Foo();
   virtual int Bar() = 0;
 };
 """
     # The constructors and destructor should be ignored.
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD0(Bar,\nint());',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testSimpleConstructorsAndDestructor (self)
Definition at line 68 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testSimpleConstructorsAndDestructor().
   def testSimpleConstructorsAndDestructor(self):
     source = """
 class Foo {
  public:
   Foo();
   Foo(int x);
   Foo(const Foo& f);
   Foo(Foo&& f);
   ~Foo();
   virtual int Bar() = 0;
 };
 """
     # The constructors and destructor should be ignored.
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD0(Bar,\nint());',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testSimpleConstructorsAndDestructor (self)
Definition at line 68 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testSimpleConstructorsAndDestructor().
   def testSimpleConstructorsAndDestructor(self):
     source = """
 class Foo {
  public:
   Foo();
   Foo(int x);
   Foo(const Foo& f);
   Foo(Foo&& f);
   ~Foo();
   virtual int Bar() = 0;
 };
 """
     # The constructors and destructor should be ignored.
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD0(Bar,\nint());',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testSimpleMethod (self)
Definition at line 57 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testSimpleMethod().
   def testSimpleMethod(self):
     source = """
 class Foo {
  public:
   virtual int Bar();
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD0(Bar,\nint());',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testSimpleMethod (self)
Definition at line 57 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testSimpleMethod().
   def testSimpleMethod(self):
     source = """
 class Foo {
  public:
   virtual int Bar();
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD0(Bar,\nint());',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testSimpleMethod (self)
Definition at line 57 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), and cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource().
Referenced by cpp.gmock_class_test.GenerateMethodsTest.testSimpleMethod().
   def testSimpleMethod(self):
     source = """
 class Foo {
  public:
   virtual int Bar();
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD0(Bar,\nint());',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testSimpleMethodInTemplatedClass (self)
Definition at line 272 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testSimpleMethodInTemplatedClass().
   def testSimpleMethodInTemplatedClass(self):
     source = """
 template<class T>
 class Foo {
  public:
   virtual int Bar();
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD0_T(Bar,\nint());',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testSimpleMethodInTemplatedClass (self)
Definition at line 272 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testSimpleMethodInTemplatedClass().
   def testSimpleMethodInTemplatedClass(self):
     source = """
 template<class T>
 class Foo {
  public:
   virtual int Bar();
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD0_T(Bar,\nint());',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testSimpleMethodInTemplatedClass (self)
Definition at line 272 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), and cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource().
Referenced by cpp.gmock_class_test.GenerateMethodsTest.testSimpleMethodInTemplatedClass().
   def testSimpleMethodInTemplatedClass(self):
     source = """
 template<class T>
 class Foo {
  public:
   virtual int Bar();
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD0_T(Bar,\nint());',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testSimpleOverrideMethod (self)
Definition at line 130 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), and cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource().
Referenced by cpp.gmock_class_test.GenerateMethodsTest.testSimpleOverrideMethod().
   def testSimpleOverrideMethod(self):
     source = """
 class Foo {
  public:
   int Bar() override;
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD0(Bar,\nint());',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testSimpleOverrideMethod (self)
Definition at line 130 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testSimpleOverrideMethod().
   def testSimpleOverrideMethod(self):
     source = """
 class Foo {
  public:
   int Bar() override;
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD0(Bar,\nint());',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testSimpleOverrideMethod (self)
Definition at line 130 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testSimpleOverrideMethod().
   def testSimpleOverrideMethod(self):
     source = """
 class Foo {
  public:
   int Bar() override;
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD0(Bar,\nint());',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testStrangeNewlineInParameter (self)
Definition at line 163 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testStrangeNewlineInParameter().
   def testStrangeNewlineInParameter(self):
     source = """
 class Foo {
  public:
   virtual void Bar(int
 a) = 0;
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD1(Bar,\nvoid(int a));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testStrangeNewlineInParameter (self)
Definition at line 163 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testStrangeNewlineInParameter().
   def testStrangeNewlineInParameter(self):
     source = """
 class Foo {
  public:
   virtual void Bar(int
 a) = 0;
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD1(Bar,\nvoid(int a));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testStrangeNewlineInParameter (self)
Definition at line 163 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), and cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource().
Referenced by cpp.gmock_class_test.GenerateMethodsTest.testStrangeNewlineInParameter().
   def testStrangeNewlineInParameter(self):
     source = """
 class Foo {
  public:
   virtual void Bar(int
 a) = 0;
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD1(Bar,\nvoid(int a));',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testVirtualDestructor (self)
Definition at line 85 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), and cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource().
Referenced by cpp.gmock_class_test.GenerateMethodsTest.testVirtualDestructor().
   def testVirtualDestructor(self):
     source = """
 class Foo {
  public:
   virtual ~Foo();
   virtual int Bar() = 0;
 };
 """
     # The destructor should be ignored.
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD0(Bar,\nint());',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testVirtualDestructor (self)
Definition at line 85 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testVirtualDestructor().
   def testVirtualDestructor(self):
     source = """
 class Foo {
  public:
   virtual ~Foo();
   virtual int Bar() = 0;
 };
 """
     # The destructor should be ignored.
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD0(Bar,\nint());',
         self.GenerateMethodSource(source))
def cpp.gmock_class_test.GenerateMethodsTest.testVirtualDestructor (self)
Definition at line 85 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMethodsTest.GenerateMethodSource(), and cpp.gmock_class_test.GenerateMethodsTest.testVirtualDestructor().
   def testVirtualDestructor(self):
     source = """
 class Foo {
  public:
   virtual ~Foo();
   virtual int Bar() = 0;
 };
 """
     # The destructor should be ignored.
     self.assertEqualIgnoreLeadingWhitespace(
         'MOCK_METHOD0(Bar,\nint());',
         self.GenerateMethodSource(source))
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/scripts/generator/cpp/gmock_class_test.py