proxygen: wangle::MockObservingPipelineFactory Class Reference
wangle::MockObservingPipelineFactory Class Reference
#include <Mocks.h>
Public Member Functions
MockObservingPipelineFactory (std::shared_ptr< ServerPool< std::string >> serverPool, std::shared_ptr< BroadcastPipelineFactory< int, std::string >> broadcastPipelineFactory)
ObservingPipeline< int >::Ptr newPipeline (std::shared_ptr< folly::AsyncTransportWrapper >, const std::string &routingData, RoutingDataHandler< std::string > *, std::shared_ptr< TransportInfo >) override
Public Member Functions inherited from wangle::ObservingPipelineFactory< int, std::string >
ObservingPipelineFactory (std::shared_ptr< ServerPool< std::string, DefaultPipeline >> serverPool, std::shared_ptr< BroadcastPipelineFactory< int, std::string >> broadcastPipelineFactory)
ObservingPipeline< int >::Ptr newPipeline (std::shared_ptr< folly::AsyncTransportWrapper > socket, const std::string &routingData, RoutingDataHandler< std::string > *, std::shared_ptr< TransportInfo > transportInfo) override
virtual BroadcastPool< int, std::string, DefaultPipeline > * broadcastPool (std::shared_ptr< BaseClientBootstrapFactory<>> clientFactory=nullptr)
Public Member Functions inherited from wangle::RoutingDataPipelineFactory< ObservingPipeline< int >, std::string >
virtual ~RoutingDataPipelineFactory ()
Additional Inherited Members
Protected Attributes inherited from wangle::ObservingPipelineFactory< int, std::string >
std::shared_ptr< ServerPool< std::string, DefaultPipeline > > serverPool_
std::shared_ptr< BroadcastPipelineFactory< int, std::string > > broadcastPipelineFactory_
folly::ThreadLocalPtr< BroadcastPool< int, std::string, DefaultPipeline > > broadcastPool_
Detailed Description
Definition at line 147 of file Mocks.h.
Constructor & Destructor Documentation
wangle::MockObservingPipelineFactory::MockObservingPipelineFactory (std::shared_ptr< ServerPool< std::string >> serverPool, std::shared_ptr< BroadcastPipelineFactory< int, std::string >> broadcastPipelineFactory) inline
Definition at line 150 of file Mocks.h.
       : ObservingPipelineFactory(serverPool, broadcastPipelineFactory) {}
Member Function Documentation
ObservingPipeline<int>::Ptr wangle::MockObservingPipelineFactory::newPipeline (std::shared_ptr< folly::AsyncTransportWrapper > , const std::string & routingData, RoutingDataHandler< std::string > * , std::shared_ptr< TransportInfo >) inline override virtual
Implements wangle::RoutingDataPipelineFactory< ObservingPipeline< int >, std::string >.
Definition at line 156 of file Mocks.h.
References wangle::Pipeline< R, W >::create(), handler(), and wangle::Subscriber< T, R >::routingData().
Referenced by TEST_F().
{
     auto pipeline = ObservingPipeline<int>::create();
     pipeline->addBack(std::make_shared<wangle::BytesToBytesHandler>());
     pipeline->addBack(std::make_shared<MockMessageToByteEncoder<int>>());
     auto handler = std::make_shared<ObservingHandler<int, std::string>>(
         routingData, broadcastPool());
     pipeline->addBack(handler);
     pipeline->finalize();
     return pipeline;
   }
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/channel/broadcast/test/Mocks.h