proxygen: cpp.gmock_class_test.GenerateMocksTest Class Reference
cpp.gmock_class_test.GenerateMocksTest Class Reference
Public Member Functions
def GenerateMocks (self, cpp_source)
def testNamespaces (self)
def testClassWithStorageSpecifierMacro (self)
def testTemplatedForwardDeclaration (self)
def testTemplatedClass (self)
def testTemplateInATemplateTypedef (self)
def testTemplateInATemplateTypedefWithComma (self)
def GenerateMocks (self, cpp_source)
def testNamespaces (self)
def testClassWithStorageSpecifierMacro (self)
def testTemplatedForwardDeclaration (self)
def testTemplatedClass (self)
def testTemplateInATemplateTypedef (self)
def testTemplateInATemplateTypedefWithComma (self)
def GenerateMocks (self, cpp_source)
def testNamespaces (self)
def testClassWithStorageSpecifierMacro (self)
def testTemplatedForwardDeclaration (self)
def testTemplatedClass (self)
def testTemplateInATemplateTypedef (self)
def testTemplateInATemplateTypedefWithComma (self)
Public Member Functions inherited from cpp.gmock_class_test.TestCase
def StripLeadingWhitespace (self, lines)
def assertEqualIgnoreLeadingWhitespace (self, expected_lines, lines)
def StripLeadingWhitespace (self, lines)
def assertEqualIgnoreLeadingWhitespace (self, expected_lines, lines)
def StripLeadingWhitespace (self, lines)
def assertEqualIgnoreLeadingWhitespace (self, expected_lines, lines)
Detailed Description
Definition at line 315 of file gmock_class_test.py.
Member Function Documentation
def cpp.gmock_class_test.GenerateMocksTest.GenerateMocks (self, cpp_source)
Convert C++ source to complete Google Mock output source.
Definition at line 317 of file gmock_class_test.py.
References join, and bm.list.
Referenced by cpp.gmock_class_test.GenerateMocksTest.GenerateMocks(), cpp.gmock_class_test.GenerateMocksTest.testClassWithStorageSpecifierMacro(), cpp.gmock_class_test.GenerateMocksTest.testNamespaces(), cpp.gmock_class_test.GenerateMocksTest.testTemplatedClass(), cpp.gmock_class_test.GenerateMocksTest.testTemplatedForwardDeclaration(), cpp.gmock_class_test.GenerateMocksTest.testTemplateInATemplateTypedef(), and cpp.gmock_class_test.GenerateMocksTest.testTemplateInATemplateTypedefWithComma().
   def GenerateMocks(self, cpp_source):
     """Convert C++ source to complete Google Mock output source."""
     # <test> is a pseudo-filename, it is not read or written.
     filename = '<test>'
     builder = ast.BuilderFromSource(cpp_source, filename)
     ast_list = list(builder.Generate())
     lines = gmock_class._GenerateMocks(filename, cpp_source, ast_list, None)
     return '\n'.join(lines)
def cpp.gmock_class_test.GenerateMocksTest.GenerateMocks (self, cpp_source)
Convert C++ source to complete Google Mock output source.
Definition at line 317 of file gmock_class_test.py.
References cpp.gmock_class_test.GenerateMocksTest.GenerateMocks(), join, and bm.list.
   def GenerateMocks(self, cpp_source):
     """Convert C++ source to complete Google Mock output source."""
     # <test> is a pseudo-filename, it is not read or written.
     filename = '<test>'
     builder = ast.BuilderFromSource(cpp_source, filename)
     ast_list = list(builder.Generate())
     lines = gmock_class._GenerateMocks(filename, cpp_source, ast_list, None)
     return '\n'.join(lines)
def cpp.gmock_class_test.GenerateMocksTest.GenerateMocks (self, cpp_source)
Convert C++ source to complete Google Mock output source.
Definition at line 317 of file gmock_class_test.py.
References cpp.gmock_class_test.GenerateMocksTest.GenerateMocks(), join, and bm.list.
   def GenerateMocks(self, cpp_source):
     """Convert C++ source to complete Google Mock output source."""
     # <test> is a pseudo-filename, it is not read or written.
     filename = '<test>'
     builder = ast.BuilderFromSource(cpp_source, filename)
     ast_list = list(builder.Generate())
     lines = gmock_class._GenerateMocks(filename, cpp_source, ast_list, None)
     return '\n'.join(lines)
def cpp.gmock_class_test.GenerateMocksTest.testClassWithStorageSpecifierMacro (self)
Definition at line 356 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMocksTest.GenerateMocks(), and cpp.gmock_class_test.GenerateMocksTest.testClassWithStorageSpecifierMacro().
   def testClassWithStorageSpecifierMacro(self):
     source = """
 class STORAGE_SPECIFIER Test {
  public:
   virtual void Foo();
 };
 """
     expected = """\
 class MockTest : public Test {
 public:
 MOCK_METHOD0(Foo,
 void());
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         expected, self.GenerateMocks(source))
def cpp.gmock_class_test.GenerateMocksTest.testClassWithStorageSpecifierMacro (self)
Definition at line 356 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMocksTest.GenerateMocks(), and cpp.gmock_class_test.GenerateMocksTest.testClassWithStorageSpecifierMacro().
   def testClassWithStorageSpecifierMacro(self):
     source = """
 class STORAGE_SPECIFIER Test {
  public:
   virtual void Foo();
 };
 """
     expected = """\
 class MockTest : public Test {
 public:
 MOCK_METHOD0(Foo,
 void());
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         expected, self.GenerateMocks(source))
def cpp.gmock_class_test.GenerateMocksTest.testClassWithStorageSpecifierMacro (self)
Definition at line 356 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), and cpp.gmock_class_test.GenerateMocksTest.GenerateMocks().
Referenced by cpp.gmock_class_test.GenerateMocksTest.testClassWithStorageSpecifierMacro().
   def testClassWithStorageSpecifierMacro(self):
     source = """
 class STORAGE_SPECIFIER Test {
  public:
   virtual void Foo();
 };
 """
     expected = """\
 class MockTest : public Test {
 public:
 MOCK_METHOD0(Foo,
 void());
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         expected, self.GenerateMocks(source))
def cpp.gmock_class_test.GenerateMocksTest.testNamespaces (self)
Definition at line 326 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), and cpp.gmock_class_test.GenerateMocksTest.GenerateMocks().
Referenced by cpp.gmock_class_test.GenerateMocksTest.testNamespaces().
   def testNamespaces(self):
     source = """
 namespace Foo {
 namespace Bar { class Forward; }
 namespace Baz {
 class Test {
  public:
   virtual void Foo();
 };
 }  // namespace Baz
 }  // namespace Foo
 """
     expected = """\
 namespace Foo {
 namespace Baz {
 class MockTest : public Test {
 public:
 MOCK_METHOD0(Foo,
 void());
 };
 }  // namespace Baz
 }  // namespace Foo
 """
     self.assertEqualIgnoreLeadingWhitespace(
         expected, self.GenerateMocks(source))
def cpp.gmock_class_test.GenerateMocksTest.testNamespaces (self)
Definition at line 326 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMocksTest.GenerateMocks(), and cpp.gmock_class_test.GenerateMocksTest.testNamespaces().
   def testNamespaces(self):
     source = """
 namespace Foo {
 namespace Bar { class Forward; }
 namespace Baz {
 class Test {
  public:
   virtual void Foo();
 };
 }  // namespace Baz
 }  // namespace Foo
 """
     expected = """\
 namespace Foo {
 namespace Baz {
 class MockTest : public Test {
 public:
 MOCK_METHOD0(Foo,
 void());
 };
 }  // namespace Baz
 }  // namespace Foo
 """
     self.assertEqualIgnoreLeadingWhitespace(
         expected, self.GenerateMocks(source))
def cpp.gmock_class_test.GenerateMocksTest.testNamespaces (self)
Definition at line 326 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMocksTest.GenerateMocks(), and cpp.gmock_class_test.GenerateMocksTest.testNamespaces().
   def testNamespaces(self):
     source = """
 namespace Foo {
 namespace Bar { class Forward; }
 namespace Baz {
 class Test {
  public:
   virtual void Foo();
 };
 }  // namespace Baz
 }  // namespace Foo
 """
     expected = """\
 namespace Foo {
 namespace Baz {
 class MockTest : public Test {
 public:
 MOCK_METHOD0(Foo,
 void());
 };
 }  // namespace Baz
 }  // namespace Foo
 """
     self.assertEqualIgnoreLeadingWhitespace(
         expected, self.GenerateMocks(source))
def cpp.gmock_class_test.GenerateMocksTest.testTemplatedClass (self)
Definition at line 391 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMocksTest.GenerateMocks(), and cpp.gmock_class_test.GenerateMocksTest.testTemplatedClass().
   def testTemplatedClass(self):
     source = """
 template <typename S, typename T>
 class Test {
  public:
   virtual void Foo();
 };
 """
     expected = """\
 template <typename T0, typename T1>
 class MockTest : public Test<T0, T1> {
 public:
 MOCK_METHOD0_T(Foo,
 void());
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         expected, self.GenerateMocks(source))
def cpp.gmock_class_test.GenerateMocksTest.testTemplatedClass (self)
Definition at line 391 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), and cpp.gmock_class_test.GenerateMocksTest.GenerateMocks().
Referenced by cpp.gmock_class_test.GenerateMocksTest.testTemplatedClass().
   def testTemplatedClass(self):
     source = """
 template <typename S, typename T>
 class Test {
  public:
   virtual void Foo();
 };
 """
     expected = """\
 template <typename T0, typename T1>
 class MockTest : public Test<T0, T1> {
 public:
 MOCK_METHOD0_T(Foo,
 void());
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         expected, self.GenerateMocks(source))
def cpp.gmock_class_test.GenerateMocksTest.testTemplatedClass (self)
Definition at line 391 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMocksTest.GenerateMocks(), and cpp.gmock_class_test.GenerateMocksTest.testTemplatedClass().
   def testTemplatedClass(self):
     source = """
 template <typename S, typename T>
 class Test {
  public:
   virtual void Foo();
 };
 """
     expected = """\
 template <typename T0, typename T1>
 class MockTest : public Test<T0, T1> {
 public:
 MOCK_METHOD0_T(Foo,
 void());
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         expected, self.GenerateMocks(source))
def cpp.gmock_class_test.GenerateMocksTest.testTemplatedForwardDeclaration (self)
Definition at line 373 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMocksTest.GenerateMocks(), and cpp.gmock_class_test.GenerateMocksTest.testTemplatedForwardDeclaration().
   def testTemplatedForwardDeclaration(self):
     source = """
 template <class T> class Forward;  // Forward declaration should be ignored.
 class Test {
  public:
   virtual void Foo();
 };
 """
     expected = """\
 class MockTest : public Test {
 public:
 MOCK_METHOD0(Foo,
 void());
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         expected, self.GenerateMocks(source))
def cpp.gmock_class_test.GenerateMocksTest.testTemplatedForwardDeclaration (self)
Definition at line 373 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), and cpp.gmock_class_test.GenerateMocksTest.GenerateMocks().
Referenced by cpp.gmock_class_test.GenerateMocksTest.testTemplatedForwardDeclaration().
   def testTemplatedForwardDeclaration(self):
     source = """
 template <class T> class Forward;  // Forward declaration should be ignored.
 class Test {
  public:
   virtual void Foo();
 };
 """
     expected = """\
 class MockTest : public Test {
 public:
 MOCK_METHOD0(Foo,
 void());
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         expected, self.GenerateMocks(source))
def cpp.gmock_class_test.GenerateMocksTest.testTemplatedForwardDeclaration (self)
Definition at line 373 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMocksTest.GenerateMocks(), and cpp.gmock_class_test.GenerateMocksTest.testTemplatedForwardDeclaration().
   def testTemplatedForwardDeclaration(self):
     source = """
 template <class T> class Forward;  // Forward declaration should be ignored.
 class Test {
  public:
   virtual void Foo();
 };
 """
     expected = """\
 class MockTest : public Test {
 public:
 MOCK_METHOD0(Foo,
 void());
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         expected, self.GenerateMocks(source))
def cpp.gmock_class_test.GenerateMocksTest.testTemplateInATemplateTypedef (self)
Definition at line 410 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMocksTest.GenerateMocks(), and cpp.gmock_class_test.GenerateMocksTest.testTemplateInATemplateTypedef().
   def testTemplateInATemplateTypedef(self):
     source = """
 class Test {
  public:
   typedef std::vector<std::list<int>> FooType;
   virtual void Bar(const FooType& test_arg);
 };
 """
     expected = """\
 class MockTest : public Test {
 public:
 MOCK_METHOD1(Bar,
 void(const FooType& test_arg));
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         expected, self.GenerateMocks(source))
def cpp.gmock_class_test.GenerateMocksTest.testTemplateInATemplateTypedef (self)
Definition at line 410 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), and cpp.gmock_class_test.GenerateMocksTest.GenerateMocks().
Referenced by cpp.gmock_class_test.GenerateMocksTest.testTemplateInATemplateTypedef().
   def testTemplateInATemplateTypedef(self):
     source = """
 class Test {
  public:
   typedef std::vector<std::list<int>> FooType;
   virtual void Bar(const FooType& test_arg);
 };
 """
     expected = """\
 class MockTest : public Test {
 public:
 MOCK_METHOD1(Bar,
 void(const FooType& test_arg));
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         expected, self.GenerateMocks(source))
def cpp.gmock_class_test.GenerateMocksTest.testTemplateInATemplateTypedef (self)
Definition at line 410 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMocksTest.GenerateMocks(), and cpp.gmock_class_test.GenerateMocksTest.testTemplateInATemplateTypedef().
   def testTemplateInATemplateTypedef(self):
     source = """
 class Test {
  public:
   typedef std::vector<std::list<int>> FooType;
   virtual void Bar(const FooType& test_arg);
 };
 """
     expected = """\
 class MockTest : public Test {
 public:
 MOCK_METHOD1(Bar,
 void(const FooType& test_arg));
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         expected, self.GenerateMocks(source))
def cpp.gmock_class_test.GenerateMocksTest.testTemplateInATemplateTypedefWithComma (self)
Definition at line 428 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMocksTest.GenerateMocks(), and cpp.gmock_class_test.GenerateMocksTest.testTemplateInATemplateTypedefWithComma().
   def testTemplateInATemplateTypedefWithComma(self):
     source = """
 class Test {
  public:
   typedef std::function<void(
       const vector<std::list<int>>&, int> FooType;
   virtual void Bar(const FooType& test_arg);
 };
 """
     expected = """\
 class MockTest : public Test {
 public:
 MOCK_METHOD1(Bar,
 void(const FooType& test_arg));
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         expected, self.GenerateMocks(source))
def cpp.gmock_class_test.GenerateMocksTest.testTemplateInATemplateTypedefWithComma (self)
Definition at line 428 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), cpp.gmock_class_test.GenerateMocksTest.GenerateMocks(), and cpp.gmock_class_test.GenerateMocksTest.testTemplateInATemplateTypedefWithComma().
   def testTemplateInATemplateTypedefWithComma(self):
     source = """
 class Test {
  public:
   typedef std::function<void(
       const vector<std::list<int>>&, int> FooType;
   virtual void Bar(const FooType& test_arg);
 };
 """
     expected = """\
 class MockTest : public Test {
 public:
 MOCK_METHOD1(Bar,
 void(const FooType& test_arg));
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         expected, self.GenerateMocks(source))
def cpp.gmock_class_test.GenerateMocksTest.testTemplateInATemplateTypedefWithComma (self)
Definition at line 428 of file gmock_class_test.py.
References cpp.gmock_class_test.TestCase.assertEqualIgnoreLeadingWhitespace(), and cpp.gmock_class_test.GenerateMocksTest.GenerateMocks().
Referenced by cpp.gmock_class_test.GenerateMocksTest.testTemplateInATemplateTypedefWithComma().
   def testTemplateInATemplateTypedefWithComma(self):
     source = """
 class Test {
  public:
   typedef std::function<void(
       const vector<std::list<int>>&, int> FooType;
   virtual void Bar(const FooType& test_arg);
 };
 """
     expected = """\
 class MockTest : public Test {
 public:
 MOCK_METHOD1(Bar,
 void(const FooType& test_arg));
 };
 """
     self.assertEqualIgnoreLeadingWhitespace(
         expected, self.GenerateMocks(source))
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/scripts/generator/cpp/gmock_class_test.py