proxygen: testing::internal::To Class Reference
testing::internal::To Class Reference
Public Member Functions
To (bool *converted)
To (bool *converted)
To (bool *converted)
Detailed Description
Definition at line 202 of file gtest-port_test.cc.
Constructor & Destructor Documentation
testing::internal::To::To (bool * converted) inline
Definition at line 204 of file gtest-port_test.cc.
 { *converted = true; }  // NOLINT
testing::internal::To::To (bool * converted) inline
Definition at line 204 of file gtest-port_test.cc.
References testing::internal::AlwaysFalse(), testing::internal::AlwaysTrue(), ASSERT_EQ, ASSERT_FALSE, testing::internal::CaptureStderr(), testing::internal::CaptureStdout(), data, dummy(), folly::empty(), EXPECT_DEATH_IF_SUPPORTED, EXPECT_EQ, EXPECT_FALSE, EXPECT_NONFATAL_FAILURE, EXPECT_PRED1, EXPECT_PRED_FORMAT2, EXPECT_STREQ, EXPECT_TRUE, testing::internal::FormatCompilerIndependentFileLocation(), testing::internal::FormatFileLocation(), testing::internal::RE::FullMatch(), testing::internal::ThreadLocal< T >::get(), testing::internal::GetCapturedStderr(), testing::internal::GetCapturedStdout(), testing::internal::GetThreadCount(), GTEST_CHECK_, GTEST_USES_POSIX_RE, i, testing::IsSubstring(), folly::detail::lock(), testing::internal::Mutex::Lock(), mutex, testing::internal::RE::PartialMatch(), testing::internal::RE::pattern(), regex, simple, testing::StaticAssertTypeEq(), string, testing::internal::TEST(), folly::to(), testing::TYPED_TEST(), testing::TYPED_TEST_CASE(), and testing::internal::Mutex::Unlock().
 { *converted = true; }  // NOLINT
testing::internal::To::To (bool * converted) inline
Definition at line 204 of file gtest-port_test.cc.
References testing::internal::AlwaysFalse(), testing::internal::AlwaysTrue(), ASSERT_EQ, ASSERT_FALSE, testing::internal::CaptureStderr(), testing::internal::CaptureStdout(), data, dummy(), folly::empty(), EXPECT_DEATH_IF_SUPPORTED, EXPECT_EQ, EXPECT_FALSE, EXPECT_NONFATAL_FAILURE, EXPECT_PRED1, EXPECT_PRED_FORMAT2, EXPECT_STREQ, EXPECT_TRUE, testing::internal::FormatCompilerIndependentFileLocation(), testing::internal::FormatFileLocation(), testing::internal::RE::FullMatch(), testing::internal::ThreadLocal< T >::get(), testing::internal::GetCapturedStderr(), testing::internal::GetCapturedStdout(), testing::internal::GetThreadCount(), GTEST_CHECK_, GTEST_USES_POSIX_RE, i, testing::IsSubstring(), folly::detail::lock(), testing::internal::Mutex::Lock(), mutex, testing::internal::RE::PartialMatch(), testing::internal::RE::pattern(), regex, simple, testing::StaticAssertTypeEq(), string, testing::internal::TEST(), folly::to(), testing::TYPED_TEST(), testing::TYPED_TEST_CASE(), and testing::internal::Mutex::Unlock().
 { *converted = true; }  // NOLINT
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest-port_test.cc