proxygen: folly::observer::detail::ObserverCreatorContext< Observable, Traits > Class Template Reference
folly::observer::detail::ObserverCreatorContext< Observable, Traits > Class Template Reference
#include <Observable-inl.h>
Public Member Functions
template<typename... Args>
ObserverCreatorContext (Args &&...args)
~ObserverCreatorContext ()
void setCore (observer_detail::Core::WeakPtr coreWeak)
std::shared_ptr< const T > get ()
void update ()
template<typename F >
void subscribe (F &&callback)
Private Types
using T = typename Traits::element_type
Private Member Functions
bool updateValue ()
Private Attributes
folly::Synchronized< std::shared_ptr< const T > > value_
std::atomic< bool > updateRequested_ {false}
observer_detail::Core::WeakPtr coreWeak_
Observable observable_
std::mutex updateMutex_
Detailed Description
template<typename Observable, typename Traits>
class folly::observer::detail::ObserverCreatorContext< Observable, Traits >
Definition at line 24 of file Observable-inl.h.
Member Typedef Documentation
template<typename Observable , typename Traits > using folly::observer::detail::ObserverCreatorContext< Observable, Traits >::T = typename Traits::element_type private
Definition at line 25 of file Observable-inl.h.
Constructor & Destructor Documentation
template<typename Observable , typename Traits > template<typename... Args> folly::observer::detail::ObserverCreatorContext< Observable, Traits >::ObserverCreatorContext (Args &&... args) inline
Definition at line 29 of file Observable-inl.h.
References folly::observer::detail::ObserverCreatorContext< Observable, Traits >::updateValue().
       : observable_(std::forward<Args>(args)...) {
     updateValue();
   }
template<typename Observable , typename Traits > folly::observer::detail::ObserverCreatorContext< Observable, Traits >::~ObserverCreatorContext () inline
Definition at line 34 of file Observable-inl.h.
References folly::Synchronized< T, Mutex >::copy(), folly::observer::detail::ObserverCreatorContext< Observable, Traits >::observable_, and folly::observer::detail::ObserverCreatorContext< Observable, Traits >::value_.
{
     if (value_.copy()) {
       Traits::unsubscribe(observable_);
     }
   }
Member Function Documentation
template<typename Observable , typename Traits > std::shared_ptr<const T> folly::observer::detail::ObserverCreatorContext< Observable, Traits >::get () inline
Definition at line 44 of file Observable-inl.h.
References folly::Synchronized< T, Mutex >::copy(), folly::observer::detail::ObserverCreatorContext< Observable, Traits >::updateRequested_, and folly::observer::detail::ObserverCreatorContext< Observable, Traits >::value_.
Referenced by folly::observer::ObserverCreator< Observable, Traits >::getObserver().
{
     updateRequested_ = false;
     return value_.copy();
   }
template<typename Observable , typename Traits > void folly::observer::detail::ObserverCreatorContext< Observable, Traits >::setCore (observer_detail::Core::WeakPtr coreWeak) inline
Definition at line 40 of file Observable-inl.h.
References folly::observer::detail::ObserverCreatorContext< Observable, Traits >::coreWeak_, and folly::gen::move.
{
     coreWeak_ = std::move(coreWeak);
   }
template<typename Observable , typename Traits > template<typename F > void folly::observer::detail::ObserverCreatorContext< Observable, Traits >::subscribe (F && callback) inline
Definition at line 69 of file Observable-inl.h.
References folly::observer::detail::ObserverCreatorContext< Observable, Traits >::observable_, and subscribe().
{
     Traits::subscribe(observable_, std::forward<F>(callback));
   }
template<typename Observable , typename Traits > void folly::observer::detail::ObserverCreatorContext< Observable, Traits >::update () inline
Definition at line 49 of file Observable-inl.h.
References folly::observer::detail::ObserverCreatorContext< Observable, Traits >::coreWeak_, folly::observer_detail::ObserverManager::scheduleRefreshNewVersion(), folly::observer::detail::ObserverCreatorContext< Observable, Traits >::updateMutex_, folly::observer::detail::ObserverCreatorContext< Observable, Traits >::updateRequested_, and folly::observer::detail::ObserverCreatorContext< Observable, Traits >::updateValue().
                 {
     // This mutex ensures there's no race condition between initial update()
     // call and update() calls from the subsciption callback.
     //
     // Additionally it helps avoid races between two different subscription
     // callbacks (getting new value from observable and storing it into value_
     // is not atomic).
     std::lock_guard<std::mutex> lg(updateMutex_);
     if (!updateValue()) {
       // Value didn't change, so we can skip the version update.
       return;
     }
     bool expected = false;
     if (updateRequested_.compare_exchange_strong(expected, true)) {
       observer_detail::ObserverManager::scheduleRefreshNewVersion(coreWeak_);
     }
   }
template<typename Observable , typename Traits > bool folly::observer::detail::ObserverCreatorContext< Observable, Traits >::updateValue () inline private
Definition at line 74 of file Observable-inl.h.
References folly::pushmi::operators::get, folly::observer::detail::ObserverCreatorContext< Observable, Traits >::observable_, folly::Synchronized< T, Mutex >::swap(), and folly::observer::detail::ObserverCreatorContext< Observable, Traits >::value_.
Referenced by folly::observer::detail::ObserverCreatorContext< Observable, Traits >::ObserverCreatorContext(), and folly::observer::detail::ObserverCreatorContext< Observable, Traits >::update().
                      {
     auto newValue = Traits::get(observable_);
     auto newValuePtr = newValue.get();
     if (!newValue) {
       throw std::logic_error("Observable returned nullptr.");
     }
     value_.swap(newValue);
     return newValuePtr != newValue.get();
   }
Member Data Documentation
template<typename Observable , typename Traits > observer_detail::Core::WeakPtr folly::observer::detail::ObserverCreatorContext< Observable, Traits >::coreWeak_ private
Definition at line 87 of file Observable-inl.h.
Referenced by folly::observer::detail::ObserverCreatorContext< Observable, Traits >::setCore(), and folly::observer::detail::ObserverCreatorContext< Observable, Traits >::update().
template<typename Observable , typename Traits > Observable folly::observer::detail::ObserverCreatorContext< Observable, Traits >::observable_ private
Definition at line 89 of file Observable-inl.h.
Referenced by folly::observer::detail::ObserverCreatorContext< Observable, Traits >::subscribe(), folly::observer::detail::ObserverCreatorContext< Observable, Traits >::updateValue(), and folly::observer::detail::ObserverCreatorContext< Observable, Traits >::~ObserverCreatorContext().
template<typename Observable , typename Traits > std::mutex folly::observer::detail::ObserverCreatorContext< Observable, Traits >::updateMutex_ private
Definition at line 91 of file Observable-inl.h.
Referenced by folly::observer::detail::ObserverCreatorContext< Observable, Traits >::update().
template<typename Observable , typename Traits > std::atomic<bool> folly::observer::detail::ObserverCreatorContext< Observable, Traits >::updateRequested_ {false} private
Definition at line 85 of file Observable-inl.h.
Referenced by folly::observer::detail::ObserverCreatorContext< Observable, Traits >::get(), and folly::observer::detail::ObserverCreatorContext< Observable, Traits >::update().
template<typename Observable , typename Traits > folly::Synchronized<std::shared_ptr<const T> > folly::observer::detail::ObserverCreatorContext< Observable, Traits >::value_ private
Definition at line 84 of file Observable-inl.h.
Referenced by folly::observer::detail::ObserverCreatorContext< Observable, Traits >::get(), folly::observer::detail::ObserverCreatorContext< Observable, Traits >::updateValue(), and folly::observer::detail::ObserverCreatorContext< Observable, Traits >::~ObserverCreatorContext().
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/observer/Observable-inl.h