proxygen: testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::Impl< T > Class Template Reference
testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::Impl< T > Class Template Reference
Public Types
typedef ::testing::tuple< T, Second > ArgTuple
typedef ::testing::tuple< T, Second > ArgTuple
typedef ::testing::tuple< T, Second > ArgTuple
Public Member Functions
Impl (const Tuple2Matcher &tm, const Second &second)
virtual void DescribeTo (::std::ostream *os) const
virtual bool MatchAndExplain (T x, MatchResultListener *listener) const
Impl (const Tuple2Matcher &tm, const Second &second)
virtual void DescribeTo (::std::ostream *os) const
virtual bool MatchAndExplain (T x, MatchResultListener *listener) const
Impl (const Tuple2Matcher &tm, const Second &second)
virtual void DescribeTo (::std::ostream *os) const
virtual bool MatchAndExplain (T x, MatchResultListener *listener) const
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
virtual void DescribeNegationTo (::std::ostream *os) const
virtual ~MatcherDescriberInterface ()
virtual void DescribeNegationTo (::std::ostream *os) const
virtual ~MatcherDescriberInterface ()
virtual void DescribeNegationTo (::std::ostream *os) const
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (Impl)
GTEST_DISALLOW_ASSIGN_ (Impl)
GTEST_DISALLOW_ASSIGN_ (Impl)
Private Attributes
const Matcher< const ArgTuple & > mono_tuple2_matcher_
const Second second_value_
Detailed Description
template<typename Tuple2Matcher, typename Second>
template<typename T>
class testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::Impl< T >
Definition at line 3576 of file gmock-matchers.h.
Member Typedef Documentation
template<typename Tuple2Matcher, typename Second> template<typename T > typedef ::testing::tuple<T, Second> testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::Impl< T >::ArgTuple
Definition at line 3578 of file gmock-matchers.h.
template<typename Tuple2Matcher, typename Second> template<typename T > typedef ::testing::tuple<T, Second> testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::Impl< T >::ArgTuple
Definition at line 3578 of file gmock-matchers.h.
template<typename Tuple2Matcher, typename Second> template<typename T > typedef ::testing::tuple<T, Second> testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::Impl< T >::ArgTuple
Definition at line 3578 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename Tuple2Matcher, typename Second> template<typename T > testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::Impl< T >::Impl (const Tuple2Matcher & tm, const Second & second) inline
Definition at line 3580 of file gmock-matchers.h.
         : mono_tuple2_matcher_(SafeMatcherCast<const ArgTuple&>(tm)),
           second_value_(second) {}
template<typename Tuple2Matcher, typename Second> template<typename T > testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::Impl< T >::Impl (const Tuple2Matcher & tm, const Second & second) inline
Definition at line 3580 of file gmock-matchers.h.
         : mono_tuple2_matcher_(SafeMatcherCast<const ArgTuple&>(tm)),
           second_value_(second) {}
template<typename Tuple2Matcher, typename Second> template<typename T > testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::Impl< T >::Impl (const Tuple2Matcher & tm, const Second & second) inline
Definition at line 3580 of file gmock-matchers.h.
         : mono_tuple2_matcher_(SafeMatcherCast<const ArgTuple&>(tm)),
           second_value_(second) {}
Member Function Documentation
template<typename Tuple2Matcher, typename Second> template<typename T > virtual void testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::Impl< T >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 3584 of file gmock-matchers.h.
References testing::internal::UniversalPrint().
{
       *os << "and ";
       UniversalPrint(second_value_, os);
       *os << " ";
       mono_tuple2_matcher_.DescribeTo(os);
     }
template<typename Tuple2Matcher, typename Second> template<typename T > virtual void testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::Impl< T >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 3584 of file gmock-matchers.h.
References testing::internal::UniversalPrint().
{
       *os << "and ";
       UniversalPrint(second_value_, os);
       *os << " ";
       mono_tuple2_matcher_.DescribeTo(os);
     }
template<typename Tuple2Matcher, typename Second> template<typename T > virtual void testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::Impl< T >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 3584 of file gmock-matchers.h.
References testing::internal::UniversalPrint().
{
       *os << "and ";
       UniversalPrint(second_value_, os);
       *os << " ";
       mono_tuple2_matcher_.DescribeTo(os);
     }
template<typename Tuple2Matcher, typename Second> template<typename T > testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::Impl< T >::GTEST_DISALLOW_ASSIGN_ (Impl< T >) private
template<typename Tuple2Matcher, typename Second> template<typename T > testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::Impl< T >::GTEST_DISALLOW_ASSIGN_ (Impl< T >) private
template<typename Tuple2Matcher, typename Second> template<typename T > testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::Impl< T >::GTEST_DISALLOW_ASSIGN_ (Impl< T >) private
template<typename Tuple2Matcher, typename Second> template<typename T > virtual bool testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::Impl< T >::MatchAndExplain (T x, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< T >.
Definition at line 3591 of file gmock-matchers.h.
{
       return mono_tuple2_matcher_.MatchAndExplain(ArgTuple(x, second_value_),
                                                   listener);
     }
template<typename Tuple2Matcher, typename Second> template<typename T > virtual bool testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::Impl< T >::MatchAndExplain (T x, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< T >.
Definition at line 3591 of file gmock-matchers.h.
References testing::_, testing::A(), testing::AllArgs(), testing::AllOf(), testing::An(), testing::AnyOf(), testing::Args(), testing::BeginEndDistanceIs(), folly::symbolizer::test::comparator(), testing::ContainerEq(), testing::Contains(), testing::ContainsRegex(), count, testing::DoubleEq(), testing::DoubleNear(), testing::Each(), testing::ElementsAreArray(), testing::EndsWith(), testing::Eq(), testing::ExplainMatchResult(), folly::gen::field(), testing::Field(), folly::gen::first, testing::FloatEq(), testing::FloatNear(), testing::internal::FormatMatcherDescription(), testing::Ge(), testing::Gt(), GTEST_API_, GTEST_DISALLOW_ASSIGN_, GTEST_REFERENCE_TO_CONST_, GTEST_REMOVE_CONST_, testing::HasSubstr(), testing::IsNull(), gen_gtest_pred_impl::Iter(), testing::Key(), testing::Le(), testing::Lt(), m, M, testing::MakeMatcher(), testing::MakePolymorphicMatcher(), testing::Matcher< T >::Matcher(), testing::internal::MatcherBindSecond(), testing::MatcherCast(), testing::Matches(), testing::MatchesRegex(), testing::NanSensitiveDoubleEq(), testing::NanSensitiveDoubleNear(), testing::NanSensitiveFloatEq(), testing::NanSensitiveFloatNear(), testing::Ne(), testing::Not(), testing::NotNull(), testing::Pair(), testing::Pointee(), testing::Pointwise(), prefix(), testing::Property(), testing::Ref(), regex, testing::ResultOf(), folly::detail::rhs, testing::SizeIs(), testing::StartsWith(), testing::StrCaseEq(), testing::StrCaseNe(), testing::StrEq(), testing::StrNe(), suffix, T, testing::Truly(), type, testing::TypedEq(), testing::UnorderedElementsAreArray(), testing::UnorderedPointwise(), value, testing::Value(), testing::WhenDynamicCastTo(), testing::WhenSorted(), testing::WhenSortedBy(), and x.
{
       return mono_tuple2_matcher_.MatchAndExplain(ArgTuple(x, second_value_),
                                                   listener);
     }
template<typename Tuple2Matcher, typename Second> template<typename T > virtual bool testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::Impl< T >::MatchAndExplain (T x, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< T >.
Definition at line 3591 of file gmock-matchers.h.
References testing::_, testing::A(), testing::AllArgs(), testing::AllOf(), testing::An(), testing::AnyOf(), testing::Args(), testing::BeginEndDistanceIs(), folly::symbolizer::test::comparator(), testing::ContainerEq(), testing::Contains(), testing::ContainsRegex(), count, testing::DoubleEq(), testing::DoubleNear(), testing::Each(), testing::ElementsAreArray(), testing::EndsWith(), testing::Eq(), testing::ExplainMatchResult(), folly::gen::field(), testing::Field(), folly::gen::first, testing::FloatEq(), testing::FloatNear(), testing::internal::FormatMatcherDescription(), testing::Ge(), testing::Gt(), GTEST_API_, GTEST_DISALLOW_ASSIGN_, GTEST_REFERENCE_TO_CONST_, GTEST_REMOVE_CONST_, testing::HasSubstr(), testing::IsNull(), gen_gtest_pred_impl::Iter(), testing::Key(), testing::Le(), testing::Lt(), m, M, testing::MakeMatcher(), testing::MakePolymorphicMatcher(), testing::Matcher< T >::Matcher(), testing::internal::MatcherBindSecond(), testing::MatcherCast(), testing::Matches(), testing::MatchesRegex(), testing::NanSensitiveDoubleEq(), testing::NanSensitiveDoubleNear(), testing::NanSensitiveFloatEq(), testing::NanSensitiveFloatNear(), testing::Ne(), testing::Not(), testing::NotNull(), testing::Pair(), testing::Pointee(), testing::Pointwise(), prefix(), testing::Property(), testing::Ref(), regex, testing::ResultOf(), folly::detail::rhs, testing::SizeIs(), testing::StartsWith(), testing::StrCaseEq(), testing::StrCaseNe(), testing::StrEq(), testing::StrNe(), suffix, T, testing::Truly(), type, testing::TypedEq(), testing::UnorderedElementsAreArray(), testing::UnorderedPointwise(), value, testing::Value(), testing::WhenDynamicCastTo(), testing::WhenSorted(), testing::WhenSortedBy(), and x.
{
       return mono_tuple2_matcher_.MatchAndExplain(ArgTuple(x, second_value_),
                                                   listener);
     }
Member Data Documentation
template<typename Tuple2Matcher, typename Second> template<typename T > const Matcher< const ArgTuple & > testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::Impl< T >::mono_tuple2_matcher_ private
Definition at line 3597 of file gmock-matchers.h.
template<typename Tuple2Matcher, typename Second> template<typename T > const Second testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::Impl< T >::second_value_ private
Definition at line 3598 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h