proxygen: TestTimeout Class Reference
TestTimeout Class Reference
Public Member Functions
TestTimeout (EventBase *eventBase)
void timeoutExpired () noexceptoverride
TestTimeout ()
TestTimeout (HHWheelTimer *t, milliseconds timeout)
void timeoutExpired () noexceptoverride
void callbackCanceled () noexceptoverride
TestTimeout ()
TestTimeout (HHWheelTimer *t, milliseconds timeout)
void timeoutExpired () noexceptoverride
void callbackCanceled () noexceptoverride
template<typename... Args>
TestTimeout (Args &&...args)
TestTimeout ()
void addTimeout (AsyncTimeoutSet *set)
template<typename... Args>
void addTimeout (AsyncTimeoutSet *set, Args &&...args)
void timeoutExpired () noexceptoverride
void _scheduleNext ()
Public Member Functions inherited from proxygen::AsyncTimeoutSet::Callback
Callback ()
virtual ~Callback ()
void cancelTimeout ()
bool isScheduled () const
Public Member Functions inherited from folly::AsyncTimeout
AsyncTimeout (TimeoutManager *timeoutManager)
AsyncTimeout (EventBase *eventBase)
AsyncTimeout (TimeoutManager *timeoutManager, InternalEnum internal)
AsyncTimeout (EventBase *eventBase, InternalEnum internal)
AsyncTimeout ()
virtual ~AsyncTimeout ()
bool scheduleTimeout (uint32_t milliseconds)
bool scheduleTimeout (TimeoutManager::timeout_type timeout)
void cancelTimeout ()
bool isScheduled () const
void attachTimeoutManager (TimeoutManager *timeoutManager, InternalEnum internal=InternalEnum::NORMAL)
void attachEventBase (EventBase *eventBase, InternalEnum internal=InternalEnum::NORMAL)
void detachTimeoutManager ()
void detachEventBase ()
const TimeoutManager * getTimeoutManager ()
struct event * getEvent ()
Static Public Member Functions
static void setTimeoutClock (MockTimeoutClock &clock)
Static Public Member Functions inherited from folly::AsyncTimeout
template<typename TCallback >
static std::unique_ptr< AsyncTimeout > make (TimeoutManager &manager, TCallback &&callback)
template<typename TCallback >
static std::unique_ptr< AsyncTimeout > schedule (TimeoutManager::timeout_type timeout, TimeoutManager &manager, TCallback &&callback)
Public Attributes
TimePoint timestamp
std::deque< TimePoint > timestamps
std::deque< TimePoint > canceledTimestamps
std::function< void()> fn
std::deque< milliseconds > timestamps
Private Attributes
std::deque< AsyncTimeoutSet * > nextSets_
Static Private Attributes
static MockTimeoutClock * clock_ = nullptr
Additional Inherited Members
Public Types inherited from folly::AsyncTimeout
typedef TimeoutManager::InternalEnum InternalEnum
Detailed Description
Definition at line 893 of file EventBaseTest.cpp.
Constructor & Destructor Documentation
TestTimeout::TestTimeout (EventBase * eventBase) inline explicit
Definition at line 895 of file EventBaseTest.cpp.
       : AsyncTimeout(eventBase), timestamp(false) {}
TestTimeout::TestTimeout () inline
Definition at line 33 of file HHWheelTimerSlowTests.cpp.
 {}
TestTimeout::TestTimeout (HHWheelTimer * t, milliseconds timeout) inline
Definition at line 34 of file HHWheelTimerSlowTests.cpp.
References folly::HHWheelTimer::scheduleTimeout().
{
     t->scheduleTimeout(this, timeout);
   }
TestTimeout::TestTimeout () inline
Definition at line 30 of file HHWheelTimerTest.cpp.
 {}
TestTimeout::TestTimeout (HHWheelTimer * t, milliseconds timeout) inline
Definition at line 31 of file HHWheelTimerTest.cpp.
References folly::HHWheelTimer::scheduleTimeout().
{
     t->scheduleTimeout(this, timeout);
   }
template<typename... Args> TestTimeout::TestTimeout (Args &&... args) inline explicit
Definition at line 40 of file AsyncTimeoutSetTest.cpp.
{
     addTimeout(std::forward<Args>(args)...);
     _scheduleNext();
   }
TestTimeout::TestTimeout () inline
Definition at line 44 of file AsyncTimeoutSetTest.cpp.
 {}
Member Function Documentation
void TestTimeout::_scheduleNext () inline
Definition at line 64 of file AsyncTimeoutSetTest.cpp.
References proxygen::AsyncTimeoutSet::front(), and proxygen::AsyncTimeoutSet::scheduleTimeout().
{
     if (nextSets_.empty()) {
       return;
     }
     AsyncTimeoutSet* nextSet = nextSets_.front();
     nextSets_.pop_front();
     nextSet->scheduleTimeout(this);
   }
void TestTimeout::addTimeout (AsyncTimeoutSet * set) inline
Definition at line 46 of file AsyncTimeoutSetTest.cpp.
{
     nextSets_.push_back(set);
   }
template<typename... Args> void TestTimeout::addTimeout (AsyncTimeoutSet * set, Args &&... args) inline
Definition at line 51 of file AsyncTimeoutSetTest.cpp.
{
     addTimeout(set);
     addTimeout(std::forward<Args>(args)...);
   }
void TestTimeout::callbackCanceled () inline override noexcept
Definition at line 42 of file HHWheelTimerTest.cpp.
{
     canceledTimestamps.emplace_back();
     if (fn) {
       fn();
     }
   }
void TestTimeout::callbackCanceled () inline override noexcept
Definition at line 45 of file HHWheelTimerSlowTests.cpp.
{
     canceledTimestamps.emplace_back();
     if (fn) {
       fn();
     }
   }
static void TestTimeout::setTimeoutClock (MockTimeoutClock & clock) inline static
Definition at line 76 of file AsyncTimeoutSetTest.cpp.
Referenced by TimeoutTest::SetUp().
{
     clock_ = &clock;
   }
void TestTimeout::timeoutExpired () inline override virtual noexcept
timeoutExpired() is invoked when the timeout period has expired.
Implements folly::AsyncTimeout.
Definition at line 35 of file HHWheelTimerTest.cpp.
{
     timestamps.emplace_back();
     if (fn) {
       fn();
     }
   }
void TestTimeout::timeoutExpired () inline override virtual noexcept
timeoutExpired() is invoked when the timeout period has expired.
Implements folly::AsyncTimeout.
Definition at line 38 of file HHWheelTimerSlowTests.cpp.
{
     timestamps.emplace_back();
     if (fn) {
       fn();
     }
   }
void TestTimeout::timeoutExpired () inline override virtual noexcept
timeoutExpired() is invoked when the timeout period has expired.
Implements folly::AsyncTimeout.
Definition at line 56 of file AsyncTimeoutSetTest.cpp.
{
     timestamps.emplace_back(clock_->millisecondsSinceEpoch());
     _scheduleNext();
     if (fn) {
       fn();
     }
   }
void TestTimeout::timeoutExpired () inline override virtual noexcept
timeoutExpired() is invoked when the timeout period has expired.
Implements folly::AsyncTimeout.
Definition at line 898 of file EventBaseTest.cpp.
{
     timestamp.reset();
   }
Member Data Documentation
std::deque< TimePoint > TestTimeout::canceledTimestamps
Definition at line 53 of file HHWheelTimerSlowTests.cpp.
Referenced by TEST_F().
MockTimeoutClock * TestTimeout::clock_ = nullptr static private
Definition at line 81 of file AsyncTimeoutSetTest.cpp.
std::function< void()> TestTimeout::fn
Definition at line 54 of file HHWheelTimerSlowTests.cpp.
Referenced by TEST_F().
std::deque<AsyncTimeoutSet*> TestTimeout::nextSets_ private
Definition at line 82 of file AsyncTimeoutSetTest.cpp.
TimePoint TestTimeout::timestamp
Definition at line 902 of file EventBaseTest.cpp.
Referenced by TEST().
std::deque< TimePoint > TestTimeout::timestamps
Definition at line 52 of file HHWheelTimerSlowTests.cpp.
Referenced by TEST_F().
std::deque<milliseconds> TestTimeout::timestamps
Definition at line 73 of file AsyncTimeoutSetTest.cpp.
The documentation for this class was generated from the following files:
proxygen/folly/folly/io/async/test/EventBaseTest.cpp
proxygen/folly/folly/io/async/test/HHWheelTimerSlowTests.cpp
proxygen/folly/folly/io/async/test/HHWheelTimerTest.cpp
proxygen/lib/utils/test/AsyncTimeoutSetTest.cpp