proxygen: folly::FakeAllPowerfulAssertingMutex Class Reference
folly::FakeAllPowerfulAssertingMutex Class Reference
Public Member Functions
void lock ()
void unlock ()
void lock_shared ()
void unlock_shared ()
void lock_upgrade ()
void unlock_upgrade ()
void unlock_upgrade_and_lock ()
void unlock_and_lock_upgrade ()
void unlock_and_lock_shared ()
void unlock_upgrade_and_lock_shared ()
template<class Rep , class Period >
bool try_lock_for (const std::chrono::duration< Rep, Period > &arg)
template<class Rep , class Period >
bool try_lock_upgrade_for (const std::chrono::duration< Rep, Period > &arg)
template<class Rep , class Period >
bool try_unlock_upgrade_and_lock_for (const std::chrono::duration< Rep, Period > &arg)
~FakeAllPowerfulAssertingMutex ()
Detailed Description
Definition at line 286 of file SynchronizedTest.cpp.
Constructor & Destructor Documentation
folly::FakeAllPowerfulAssertingMutex::~FakeAllPowerfulAssertingMutex () inline
Definition at line 337 of file SynchronizedTest.cpp.
{
     globalAllPowerfulAssertingMutex = FakeAllPowerfulAssertingMutexInternal{};
   }
Member Function Documentation
void folly::FakeAllPowerfulAssertingMutex::lock () inline
Definition at line 288 of file SynchronizedTest.cpp.
References folly::FakeAllPowerfulAssertingMutexInternal::lock().
               {
     globalAllPowerfulAssertingMutex.lock();
   }
void folly::FakeAllPowerfulAssertingMutex::lock_shared () inline
Definition at line 294 of file SynchronizedTest.cpp.
References folly::FakeAllPowerfulAssertingMutexInternal::lock_shared().
                      {
     globalAllPowerfulAssertingMutex.lock_shared();
   }
void folly::FakeAllPowerfulAssertingMutex::lock_upgrade () inline
Definition at line 300 of file SynchronizedTest.cpp.
References folly::FakeAllPowerfulAssertingMutexInternal::lock_upgrade().
                       {
     globalAllPowerfulAssertingMutex.lock_upgrade();
   }
template<class Rep , class Period > bool folly::FakeAllPowerfulAssertingMutex::try_lock_for (const std::chrono::duration< Rep, Period > & arg) inline
Definition at line 321 of file SynchronizedTest.cpp.
References folly::FakeAllPowerfulAssertingMutexInternal::try_lock_for().
{
     return globalAllPowerfulAssertingMutex.try_lock_for(arg);
   }
template<class Rep , class Period > bool folly::FakeAllPowerfulAssertingMutex::try_lock_upgrade_for (const std::chrono::duration< Rep, Period > & arg) inline
Definition at line 326 of file SynchronizedTest.cpp.
References folly::FakeAllPowerfulAssertingMutexInternal::try_lock_upgrade_for().
{
     return globalAllPowerfulAssertingMutex.try_lock_upgrade_for(arg);
   }
template<class Rep , class Period > bool folly::FakeAllPowerfulAssertingMutex::try_unlock_upgrade_and_lock_for (const std::chrono::duration< Rep, Period > & arg) inline
Definition at line 331 of file SynchronizedTest.cpp.
References folly::FakeAllPowerfulAssertingMutexInternal::try_unlock_upgrade_and_lock_for().
{
     return globalAllPowerfulAssertingMutex.try_unlock_upgrade_and_lock_for(arg);
   }
void folly::FakeAllPowerfulAssertingMutex::unlock () inline
Definition at line 291 of file SynchronizedTest.cpp.
References folly::FakeAllPowerfulAssertingMutexInternal::unlock().
                 {
     globalAllPowerfulAssertingMutex.unlock();
   }
void folly::FakeAllPowerfulAssertingMutex::unlock_and_lock_shared () inline
Definition at line 313 of file SynchronizedTest.cpp.
References folly::FakeAllPowerfulAssertingMutexInternal::unlock_and_lock_shared().
{
     globalAllPowerfulAssertingMutex.unlock_and_lock_shared();
   }
void folly::FakeAllPowerfulAssertingMutex::unlock_and_lock_upgrade () inline
Definition at line 310 of file SynchronizedTest.cpp.
References folly::FakeAllPowerfulAssertingMutexInternal::unlock_and_lock_upgrade().
{
     globalAllPowerfulAssertingMutex.unlock_and_lock_upgrade();
   }
void folly::FakeAllPowerfulAssertingMutex::unlock_shared () inline
Definition at line 297 of file SynchronizedTest.cpp.
References folly::FakeAllPowerfulAssertingMutexInternal::unlock_shared().
{
     globalAllPowerfulAssertingMutex.unlock_shared();
   }
void folly::FakeAllPowerfulAssertingMutex::unlock_upgrade () inline
Definition at line 303 of file SynchronizedTest.cpp.
References folly::FakeAllPowerfulAssertingMutexInternal::unlock_upgrade().
{
     globalAllPowerfulAssertingMutex.unlock_upgrade();
   }
void folly::FakeAllPowerfulAssertingMutex::unlock_upgrade_and_lock () inline
Definition at line 307 of file SynchronizedTest.cpp.
References folly::FakeAllPowerfulAssertingMutexInternal::unlock_upgrade_and_lock().
{
     globalAllPowerfulAssertingMutex.unlock_upgrade_and_lock();
   }
void folly::FakeAllPowerfulAssertingMutex::unlock_upgrade_and_lock_shared () inline
Definition at line 316 of file SynchronizedTest.cpp.
References folly::FakeAllPowerfulAssertingMutexInternal::unlock_upgrade_and_lock_shared().
{
     globalAllPowerfulAssertingMutex.unlock_upgrade_and_lock_shared();
   }
The documentation for this class was generated from the following file:
proxygen/folly/folly/test/SynchronizedTest.cpp