proxygen: ClientRunner Class Reference
ClientRunner Class Reference
Public Member Functions
ClientRunner ()
void run ()
Public Attributes
int reqs
int hits
int miss
int num
Detailed Description
Definition at line 40 of file SSLCacheTest.cpp.
Constructor & Destructor Documentation
ClientRunner::ClientRunner () inline
Definition at line 43 of file SSLCacheTest.cpp.
References folly::run().
 : reqs(0), hits(0), miss(0), num(tnum++) {}
Member Function Documentation
void ClientRunner::run ()
Definition at line 161 of file SSLCacheTest.cpp.
References c, i, folly::EventBase::loop(), and SSLCacheClient::start().
Referenced by main().
 {
   EventBase eb;
   std::list<SSLCacheClient *> clients;
   SSL_SESSION* session = nullptr;
   for (int i = 0; i < FLAGS_clients; i++) {
     SSLCacheClient* c = new SSLCacheClient(&eb, &session, this);
     c->start();
     clients.push_back(c);
   }
   eb.loop();
   for (auto it = clients.begin(); it != clients.end(); it++) {
     delete* it;
   }
   reqs += hits + miss;
 }
Member Data Documentation
int ClientRunner::hits
Definition at line 47 of file SSLCacheTest.cpp.
Referenced by SSLCacheClient::handshakeSuc(), and main().
int ClientRunner::miss
Definition at line 48 of file SSLCacheTest.cpp.
Referenced by SSLCacheClient::handshakeSuc(), and main().
int ClientRunner::num
Definition at line 49 of file SSLCacheTest.cpp.
Referenced by SSLCacheClient::handshakeSuc().
int ClientRunner::reqs
Definition at line 46 of file SSLCacheTest.cpp.
Referenced by main().
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/ssl/test/SSLCacheTest.cpp