proxygen: BaselinePQ< T, PriorityQueue, Mutex > Class Template Reference
BaselinePQ< T, PriorityQueue, Mutex > Class Template Reference
Public Member Functions
template<typename... PQArgs, typename = decltype(PriorityQueue(std::declval<PQArgs>()...))>
BaselinePQ (size_t maxSize=0, PQArgs...args)
bool empty () const
size_t size () const
bool try_push (const T &val)
bool try_pop (T &val)
bool try_peek (T &val)
Private Attributes
Mutex m_
size_t maxSize_
PriorityQueue pq_
std::condition_variable notempty_
std::condition_variable notfull_
Detailed Description
template<typename T, typename PriorityQueue = std::priority_queue<T>, typename Mutex = std::mutex>
class BaselinePQ< T, PriorityQueue, Mutex >
Baseline implementation represents a conventional single-lock implementation that supports cond var blocking.
Definition at line 46 of file FlatCombiningPriorityQueueTest.cpp.
Constructor & Destructor Documentation
template<typename T , typename PriorityQueue = std::priority_queue<T>, typename Mutex = std::mutex> template<typename... PQArgs, typename = decltype(PriorityQueue(std::declval<PQArgs>()...))> BaselinePQ< T, PriorityQueue, Mutex >::BaselinePQ (size_t maxSize = 0, PQArgs... args) inline explicit
Definition at line 51 of file FlatCombiningPriorityQueueTest.cpp.
       : maxSize_(maxSize), pq_(std::forward<PQArgs>(args)...) {}
Member Function Documentation
template<typename T , typename PriorityQueue = std::priority_queue<T>, typename Mutex = std::mutex> bool BaselinePQ< T, PriorityQueue, Mutex >::empty () const inline
Definition at line 54 of file FlatCombiningPriorityQueueTest.cpp.
References g(), BaselinePQ< T, PriorityQueue, Mutex >::m_, and BaselinePQ< T, PriorityQueue, Mutex >::pq_.
                      {
     std::lock_guard<Mutex> g(m_);
     return pq_.empty();
   }
template<typename T , typename PriorityQueue = std::priority_queue<T>, typename Mutex = std::mutex> size_t BaselinePQ< T, PriorityQueue, Mutex >::size () const inline
Definition at line 59 of file FlatCombiningPriorityQueueTest.cpp.
References g(), BaselinePQ< T, PriorityQueue, Mutex >::m_, and BaselinePQ< T, PriorityQueue, Mutex >::pq_.
Referenced by run_once().
                       {
     std::lock_guard<Mutex> g(m_);
     return pq_.size();
   }
template<typename T , typename PriorityQueue = std::priority_queue<T>, typename Mutex = std::mutex> bool BaselinePQ< T, PriorityQueue, Mutex >::try_peek (T & val) inline
Definition at line 90 of file FlatCombiningPriorityQueueTest.cpp.
References g(), BaselinePQ< T, PriorityQueue, Mutex >::m_, and BaselinePQ< T, PriorityQueue, Mutex >::pq_.
{
     std::lock_guard<Mutex> g(m_);
     if (!pq_.empty()) {
       val = pq_.top();
       return true;
     }
     return false;
   }
template<typename T , typename PriorityQueue = std::priority_queue<T>, typename Mutex = std::mutex> bool BaselinePQ< T, PriorityQueue, Mutex >::try_pop (T & val) inline
Definition at line 79 of file FlatCombiningPriorityQueueTest.cpp.
References g(), BaselinePQ< T, PriorityQueue, Mutex >::m_, BaselinePQ< T, PriorityQueue, Mutex >::notfull_, and BaselinePQ< T, PriorityQueue, Mutex >::pq_.
Referenced by test().
{
     std::lock_guard<Mutex> g(m_);
     if (!pq_.empty()) {
       val = pq_.top();
       pq_.pop();
       notfull_.notify_one();
       return true;
     }
     return false;
   }
template<typename T , typename PriorityQueue = std::priority_queue<T>, typename Mutex = std::mutex> bool BaselinePQ< T, PriorityQueue, Mutex >::try_push (const T & val) inline
Definition at line 64 of file FlatCombiningPriorityQueueTest.cpp.
References g(), BaselinePQ< T, PriorityQueue, Mutex >::m_, BaselinePQ< T, PriorityQueue, Mutex >::maxSize_, BaselinePQ< T, PriorityQueue, Mutex >::notempty_, and BaselinePQ< T, PriorityQueue, Mutex >::pq_.
Referenced by test().
{
     std::lock_guard<Mutex> g(m_);
     if (maxSize_ > 0 && pq_.size() == maxSize_) {
       return false;
     }
     DCHECK(maxSize_ == 0 || pq_.size() < maxSize_);
     try {
       pq_.push(val);
       notempty_.notify_one();
       return true;
     } catch (const std::bad_alloc&) {
       return false;
     }
   }
Member Data Documentation
template<typename T , typename PriorityQueue = std::priority_queue<T>, typename Mutex = std::mutex> Mutex BaselinePQ< T, PriorityQueue, Mutex >::m_ private
Definition at line 100 of file FlatCombiningPriorityQueueTest.cpp.
Referenced by BaselinePQ< T, PriorityQueue, Mutex >::empty(), BaselinePQ< T, PriorityQueue, Mutex >::size(), BaselinePQ< T, PriorityQueue, Mutex >::try_peek(), BaselinePQ< T, PriorityQueue, Mutex >::try_pop(), and BaselinePQ< T, PriorityQueue, Mutex >::try_push().
template<typename T , typename PriorityQueue = std::priority_queue<T>, typename Mutex = std::mutex> size_t BaselinePQ< T, PriorityQueue, Mutex >::maxSize_ private
Definition at line 101 of file FlatCombiningPriorityQueueTest.cpp.
Referenced by BaselinePQ< T, PriorityQueue, Mutex >::try_push().
template<typename T , typename PriorityQueue = std::priority_queue<T>, typename Mutex = std::mutex> std::condition_variable BaselinePQ< T, PriorityQueue, Mutex >::notempty_ private
Definition at line 103 of file FlatCombiningPriorityQueueTest.cpp.
Referenced by BaselinePQ< T, PriorityQueue, Mutex >::try_push().
template<typename T , typename PriorityQueue = std::priority_queue<T>, typename Mutex = std::mutex> std::condition_variable BaselinePQ< T, PriorityQueue, Mutex >::notfull_ private
Definition at line 104 of file FlatCombiningPriorityQueueTest.cpp.
Referenced by BaselinePQ< T, PriorityQueue, Mutex >::try_pop().
template<typename T , typename PriorityQueue = std::priority_queue<T>, typename Mutex = std::mutex> PriorityQueue BaselinePQ< T, PriorityQueue, Mutex >::pq_ private
Definition at line 102 of file FlatCombiningPriorityQueueTest.cpp.
Referenced by BaselinePQ< T, PriorityQueue, Mutex >::empty(), BaselinePQ< T, PriorityQueue, Mutex >::size(), BaselinePQ< T, PriorityQueue, Mutex >::try_peek(), BaselinePQ< T, PriorityQueue, Mutex >::try_pop(), and BaselinePQ< T, PriorityQueue, Mutex >::try_push().
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/test/FlatCombiningPriorityQueueTest.cpp