proxygen: testing::gmock_matchers_test::Derived Class Reference
testing::gmock_matchers_test::Derived Class Reference
Public Member Functions
Derived ()
Derived ()
Derived ()
Public Member Functions inherited from testing::gmock_matchers_test::Base
virtual ~Base ()
Base ()
virtual ~Base ()
Base ()
virtual ~Base ()
Base ()
Public Attributes
int i
Detailed Description
Definition at line 667 of file gmock-matchers_test.cc.
Constructor & Destructor Documentation
testing::gmock_matchers_test::Derived::Derived () inline
Definition at line 669 of file gmock-matchers_test.cc.
 : Base() {}
testing::gmock_matchers_test::Derived::Derived () inline
Definition at line 669 of file gmock-matchers_test.cc.
References testing::_, testing::gmock_matchers_test::Describe(), testing::DoubleEq(), testing::Eq(), EXPECT_EQ, EXPECT_FALSE, EXPECT_THAT, EXPECT_TRUE, i, testing::internal::MatcherBase< T >::Matches(), testing::Ref(), and testing::internal::TEST().
 : Base() {}
testing::gmock_matchers_test::Derived::Derived () inline
Definition at line 669 of file gmock-matchers_test.cc.
References testing::_, testing::gmock_matchers_test::Describe(), testing::DoubleEq(), testing::Eq(), EXPECT_EQ, EXPECT_FALSE, EXPECT_THAT, EXPECT_TRUE, i, testing::internal::MatcherBase< T >::Matches(), testing::Ref(), and testing::internal::TEST().
 : Base() {}
Member Data Documentation
int Derived::i
Definition at line 670 of file gmock-matchers_test.cc.
Referenced by testing::gmock_matchers_test::MATCHER_P(), and testing::gmock_matchers_test::FloatingPointNearTest< RawType >::TestNearMatches().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-matchers_test.cc