proxygen: gtest_catch_exceptions_test.CatchCxxExceptionsTest Class Reference
gtest_catch_exceptions_test.CatchCxxExceptionsTest Class Reference
Public Member Functions
def testCatchesCxxExceptionsInFixtureConstructor (self)
def testCatchesCxxExceptionsInFixtureDestructor (self)
def testCatchesCxxExceptionsInSetUpTestCase (self)
def testCatchesCxxExceptionsInTearDownTestCase (self)
def testCatchesCxxExceptionsInSetUp (self)
def testCatchesCxxExceptionsInTearDown (self)
def testCatchesCxxExceptionsInTestBody (self)
def testCatchesNonStdCxxExceptions (self)
def testUnhandledCxxExceptionsAbortTheProgram (self)
def testCatchesCxxExceptionsInFixtureConstructor (self)
def testCatchesCxxExceptionsInFixtureDestructor (self)
def testCatchesCxxExceptionsInSetUpTestCase (self)
def testCatchesCxxExceptionsInTearDownTestCase (self)
def testCatchesCxxExceptionsInSetUp (self)
def testCatchesCxxExceptionsInTearDown (self)
def testCatchesCxxExceptionsInTestBody (self)
def testCatchesNonStdCxxExceptions (self)
def testUnhandledCxxExceptionsAbortTheProgram (self)
def testCatchesCxxExceptionsInFixtureConstructor (self)
def testCatchesCxxExceptionsInFixtureDestructor (self)
def testCatchesCxxExceptionsInSetUpTestCase (self)
def testCatchesCxxExceptionsInTearDownTestCase (self)
def testCatchesCxxExceptionsInSetUp (self)
def testCatchesCxxExceptionsInTearDown (self)
def testCatchesCxxExceptionsInTestBody (self)
def testCatchesNonStdCxxExceptions (self)
def testUnhandledCxxExceptionsAbortTheProgram (self)
Detailed Description
Tests C++ exception-catching behavior.
   Tests in this test case verify that:
   * C++ exceptions are caught and logged as C++ (not SEH) exceptions
   * Exception thrown affect the remainder of the test work flow in the
     expected manner.
Definition at line 114 of file gtest_catch_exceptions_test.py.
Member Function Documentation
def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureConstructor (self)
Definition at line 123 of file gtest_catch_exceptions_test.py.
Referenced by gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureConstructor().
   def testCatchesCxxExceptionsInFixtureConstructor(self):
     self.assert_('C++ exception with description '
                  '"Standard C++ exception" thrown '
                  'in the test fixture\'s constructor'
                  in EX_BINARY_OUTPUT)
     self.assert_('unexpected' not in EX_BINARY_OUTPUT,
                  'This failure belongs in this test only if '
                  '"CxxExceptionInConstructorTest" (no quotes) '
                  'appears on the same line as words "called unexpectedly"')
def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureConstructor (self)
Definition at line 123 of file gtest_catch_exceptions_test.py.
References gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureConstructor().
   def testCatchesCxxExceptionsInFixtureConstructor(self):
     self.assert_('C++ exception with description '
                  '"Standard C++ exception" thrown '
                  'in the test fixture\'s constructor'
                  in EX_BINARY_OUTPUT)
     self.assert_('unexpected' not in EX_BINARY_OUTPUT,
                  'This failure belongs in this test only if '
                  '"CxxExceptionInConstructorTest" (no quotes) '
                  'appears on the same line as words "called unexpectedly"')
def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureConstructor (self)
Definition at line 123 of file gtest_catch_exceptions_test.py.
References gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureConstructor().
   def testCatchesCxxExceptionsInFixtureConstructor(self):
     self.assert_('C++ exception with description '
                  '"Standard C++ exception" thrown '
                  'in the test fixture\'s constructor'
                  in EX_BINARY_OUTPUT)
     self.assert_('unexpected' not in EX_BINARY_OUTPUT,
                  'This failure belongs in this test only if '
                  '"CxxExceptionInConstructorTest" (no quotes) '
                  'appears on the same line as words "called unexpectedly"')
def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureDestructor (self)
Definition at line 136 of file gtest_catch_exceptions_test.py.
Referenced by gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureDestructor().
     def testCatchesCxxExceptionsInFixtureDestructor(self):
       self.assert_('C++ exception with description '
                    '"Standard C++ exception" thrown '
                    'in the test fixture\'s destructor'
                    in EX_BINARY_OUTPUT)
       self.assert_('CxxExceptionInDestructorTest::TearDownTestCase() '
                    'called as expected.'
                    in EX_BINARY_OUTPUT)
def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureDestructor (self)
Definition at line 136 of file gtest_catch_exceptions_test.py.
References gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureDestructor().
     def testCatchesCxxExceptionsInFixtureDestructor(self):
       self.assert_('C++ exception with description '
                    '"Standard C++ exception" thrown '
                    'in the test fixture\'s destructor'
                    in EX_BINARY_OUTPUT)
       self.assert_('CxxExceptionInDestructorTest::TearDownTestCase() '
                    'called as expected.'
                    in EX_BINARY_OUTPUT)
def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureDestructor (self)
Definition at line 136 of file gtest_catch_exceptions_test.py.
References gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureDestructor().
     def testCatchesCxxExceptionsInFixtureDestructor(self):
       self.assert_('C++ exception with description '
                    '"Standard C++ exception" thrown '
                    'in the test fixture\'s destructor'
                    in EX_BINARY_OUTPUT)
       self.assert_('CxxExceptionInDestructorTest::TearDownTestCase() '
                    'called as expected.'
                    in EX_BINARY_OUTPUT)
def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUp (self)
Definition at line 173 of file gtest_catch_exceptions_test.py.
Referenced by gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUp().
   def testCatchesCxxExceptionsInSetUp(self):
     self.assert_('C++ exception with description "Standard C++ exception"'
                  ' thrown in SetUp()'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInSetUpTest::TearDownTestCase() '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInSetUpTest destructor '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInSetUpTest::TearDown() '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('unexpected' not in EX_BINARY_OUTPUT,
                  'This failure belongs in this test only if '
                  '"CxxExceptionInSetUpTest" (no quotes) '
                  'appears on the same line as words "called unexpectedly"')
def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUp (self)
Definition at line 173 of file gtest_catch_exceptions_test.py.
References gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUp().
   def testCatchesCxxExceptionsInSetUp(self):
     self.assert_('C++ exception with description "Standard C++ exception"'
                  ' thrown in SetUp()'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInSetUpTest::TearDownTestCase() '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInSetUpTest destructor '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInSetUpTest::TearDown() '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('unexpected' not in EX_BINARY_OUTPUT,
                  'This failure belongs in this test only if '
                  '"CxxExceptionInSetUpTest" (no quotes) '
                  'appears on the same line as words "called unexpectedly"')
def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUp (self)
Definition at line 173 of file gtest_catch_exceptions_test.py.
References gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUp().
   def testCatchesCxxExceptionsInSetUp(self):
     self.assert_('C++ exception with description "Standard C++ exception"'
                  ' thrown in SetUp()'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInSetUpTest::TearDownTestCase() '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInSetUpTest destructor '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInSetUpTest::TearDown() '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('unexpected' not in EX_BINARY_OUTPUT,
                  'This failure belongs in this test only if '
                  '"CxxExceptionInSetUpTest" (no quotes) '
                  'appears on the same line as words "called unexpectedly"')
def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUpTestCase (self)
Definition at line 145 of file gtest_catch_exceptions_test.py.
References gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUpTestCase().
   def testCatchesCxxExceptionsInSetUpTestCase(self):
     self.assert_('C++ exception with description "Standard C++ exception"'
                  ' thrown in SetUpTestCase()'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInConstructorTest::TearDownTestCase() '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInSetUpTestCaseTest constructor '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInSetUpTestCaseTest destructor '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInSetUpTestCaseTest::SetUp() '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInSetUpTestCaseTest::TearDown() '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInSetUpTestCaseTest test body '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUpTestCase (self)
Definition at line 145 of file gtest_catch_exceptions_test.py.
References gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUpTestCase().
   def testCatchesCxxExceptionsInSetUpTestCase(self):
     self.assert_('C++ exception with description "Standard C++ exception"'
                  ' thrown in SetUpTestCase()'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInConstructorTest::TearDownTestCase() '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInSetUpTestCaseTest constructor '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInSetUpTestCaseTest destructor '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInSetUpTestCaseTest::SetUp() '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInSetUpTestCaseTest::TearDown() '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInSetUpTestCaseTest test body '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUpTestCase (self)
Definition at line 145 of file gtest_catch_exceptions_test.py.
Referenced by gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUpTestCase().
   def testCatchesCxxExceptionsInSetUpTestCase(self):
     self.assert_('C++ exception with description "Standard C++ exception"'
                  ' thrown in SetUpTestCase()'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInConstructorTest::TearDownTestCase() '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInSetUpTestCaseTest constructor '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInSetUpTestCaseTest destructor '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInSetUpTestCaseTest::SetUp() '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInSetUpTestCaseTest::TearDown() '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInSetUpTestCaseTest test body '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDown (self)
Definition at line 191 of file gtest_catch_exceptions_test.py.
References gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDown().
   def testCatchesCxxExceptionsInTearDown(self):
     self.assert_('C++ exception with description "Standard C++ exception"'
                  ' thrown in TearDown()'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInTearDownTest::TearDownTestCase() '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInTearDownTest destructor '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDown (self)
Definition at line 191 of file gtest_catch_exceptions_test.py.
Referenced by gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDown().
   def testCatchesCxxExceptionsInTearDown(self):
     self.assert_('C++ exception with description "Standard C++ exception"'
                  ' thrown in TearDown()'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInTearDownTest::TearDownTestCase() '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInTearDownTest destructor '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDown (self)
Definition at line 191 of file gtest_catch_exceptions_test.py.
References gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDown().
   def testCatchesCxxExceptionsInTearDown(self):
     self.assert_('C++ exception with description "Standard C++ exception"'
                  ' thrown in TearDown()'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInTearDownTest::TearDownTestCase() '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInTearDownTest destructor '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDownTestCase (self)
Definition at line 168 of file gtest_catch_exceptions_test.py.
Referenced by gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDownTestCase().
   def testCatchesCxxExceptionsInTearDownTestCase(self):
     self.assert_('C++ exception with description "Standard C++ exception"'
                  ' thrown in TearDownTestCase()'
                  in EX_BINARY_OUTPUT)
def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDownTestCase (self)
Definition at line 168 of file gtest_catch_exceptions_test.py.
References gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDownTestCase().
   def testCatchesCxxExceptionsInTearDownTestCase(self):
     self.assert_('C++ exception with description "Standard C++ exception"'
                  ' thrown in TearDownTestCase()'
                  in EX_BINARY_OUTPUT)
def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDownTestCase (self)
Definition at line 168 of file gtest_catch_exceptions_test.py.
References gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDownTestCase().
   def testCatchesCxxExceptionsInTearDownTestCase(self):
     self.assert_('C++ exception with description "Standard C++ exception"'
                  ' thrown in TearDownTestCase()'
                  in EX_BINARY_OUTPUT)
def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTestBody (self)
Definition at line 202 of file gtest_catch_exceptions_test.py.
References gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTestBody().
   def testCatchesCxxExceptionsInTestBody(self):
     self.assert_('C++ exception with description "Standard C++ exception"'
                  ' thrown in the test body'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInTestBodyTest::TearDownTestCase() '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInTestBodyTest destructor '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInTestBodyTest::TearDown() '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTestBody (self)
Definition at line 202 of file gtest_catch_exceptions_test.py.
References gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTestBody().
   def testCatchesCxxExceptionsInTestBody(self):
     self.assert_('C++ exception with description "Standard C++ exception"'
                  ' thrown in the test body'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInTestBodyTest::TearDownTestCase() '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInTestBodyTest destructor '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInTestBodyTest::TearDown() '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTestBody (self)
Definition at line 202 of file gtest_catch_exceptions_test.py.
Referenced by gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTestBody().
   def testCatchesCxxExceptionsInTestBody(self):
     self.assert_('C++ exception with description "Standard C++ exception"'
                  ' thrown in the test body'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInTestBodyTest::TearDownTestCase() '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInTestBodyTest destructor '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
     self.assert_('CxxExceptionInTestBodyTest::TearDown() '
                  'called as expected.'
                  in EX_BINARY_OUTPUT)
def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesNonStdCxxExceptions (self)
Definition at line 216 of file gtest_catch_exceptions_test.py.
Referenced by gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesNonStdCxxExceptions().
   def testCatchesNonStdCxxExceptions(self):
     self.assert_('Unknown C++ exception thrown in the test body'
                  in EX_BINARY_OUTPUT)
def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesNonStdCxxExceptions (self)
Definition at line 216 of file gtest_catch_exceptions_test.py.
References gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesNonStdCxxExceptions().
   def testCatchesNonStdCxxExceptions(self):
     self.assert_('Unknown C++ exception thrown in the test body'
                  in EX_BINARY_OUTPUT)
def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesNonStdCxxExceptions (self)
Definition at line 216 of file gtest_catch_exceptions_test.py.
References gtest_catch_exceptions_test.CatchCxxExceptionsTest.testCatchesNonStdCxxExceptions().
   def testCatchesNonStdCxxExceptions(self):
     self.assert_('Unknown C++ exception thrown in the test body'
                  in EX_BINARY_OUTPUT)
def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testUnhandledCxxExceptionsAbortTheProgram (self)
Definition at line 220 of file gtest_catch_exceptions_test.py.
References gtest_test_utils.Main(), and gtest_catch_exceptions_test.CatchCxxExceptionsTest.testUnhandledCxxExceptionsAbortTheProgram().
   def testUnhandledCxxExceptionsAbortTheProgram(self):
     # Filters out SEH exception tests on Windows. Unhandled SEH exceptions
     # cause tests to show pop-up windows there.
     FITLER_OUT_SEH_TESTS_FLAG = FILTER_FLAG + '=-*Seh*'
     # By default, Google Test doesn't catch the exceptions.
     uncaught_exceptions_ex_binary_output = gtest_test_utils.Subprocess(
         [EX_EXE_PATH,
          NO_CATCH_EXCEPTIONS_FLAG,
          FITLER_OUT_SEH_TESTS_FLAG],
         env=environ).output
     self.assert_('Unhandled C++ exception terminating the program'
                  in uncaught_exceptions_ex_binary_output)
     self.assert_('unexpected' not in uncaught_exceptions_ex_binary_output)
def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testUnhandledCxxExceptionsAbortTheProgram (self)
Definition at line 220 of file gtest_catch_exceptions_test.py.
References gtest_test_utils.Main().
Referenced by gtest_catch_exceptions_test.CatchCxxExceptionsTest.testUnhandledCxxExceptionsAbortTheProgram().
   def testUnhandledCxxExceptionsAbortTheProgram(self):
     # Filters out SEH exception tests on Windows. Unhandled SEH exceptions
     # cause tests to show pop-up windows there.
     FITLER_OUT_SEH_TESTS_FLAG = FILTER_FLAG + '=-*Seh*'
     # By default, Google Test doesn't catch the exceptions.
     uncaught_exceptions_ex_binary_output = gtest_test_utils.Subprocess(
         [EX_EXE_PATH,
          NO_CATCH_EXCEPTIONS_FLAG,
          FITLER_OUT_SEH_TESTS_FLAG],
         env=environ).output
     self.assert_('Unhandled C++ exception terminating the program'
                  in uncaught_exceptions_ex_binary_output)
     self.assert_('unexpected' not in uncaught_exceptions_ex_binary_output)
def gtest_catch_exceptions_test.CatchCxxExceptionsTest.testUnhandledCxxExceptionsAbortTheProgram (self)
Definition at line 220 of file gtest_catch_exceptions_test.py.
References gtest_test_utils.Main(), and gtest_catch_exceptions_test.CatchCxxExceptionsTest.testUnhandledCxxExceptionsAbortTheProgram().
   def testUnhandledCxxExceptionsAbortTheProgram(self):
     # Filters out SEH exception tests on Windows. Unhandled SEH exceptions
     # cause tests to show pop-up windows there.
     FITLER_OUT_SEH_TESTS_FLAG = FILTER_FLAG + '=-*Seh*'
     # By default, Google Test doesn't catch the exceptions.
     uncaught_exceptions_ex_binary_output = gtest_test_utils.Subprocess(
         [EX_EXE_PATH,
          NO_CATCH_EXCEPTIONS_FLAG,
          FITLER_OUT_SEH_TESTS_FLAG],
         env=environ).output
     self.assert_('Unhandled C++ exception terminating the program'
                  in uncaught_exceptions_ex_binary_output)
     self.assert_('unexpected' not in uncaught_exceptions_ex_binary_output)
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest_catch_exceptions_test.py