proxygen: testing::TestInfo Class Reference
testing::TestInfo Class Reference
#include <gtest.h>
Public Member Functions
~TestInfo ()
const char * test_case_name () const
const char * name () const
const char * type_param () const
const char * value_param () const
const char * file () const
int line () const
bool should_run () const
bool is_reportable () const
const TestResult * result () const
~TestInfo ()
const char * test_case_name () const
const char * name () const
const char * type_param () const
const char * value_param () const
const char * file () const
int line () const
bool should_run () const
bool is_reportable () const
const TestResult * result () const
~TestInfo ()
const char * test_case_name () const
const char * name () const
const char * type_param () const
const char * value_param () const
const char * file () const
int line () const
bool should_run () const
bool is_reportable () const
const TestResult * result () const
Private Member Functions
TestInfo (const std::string &test_case_name, const std::string &name, const char *a_type_param, const char *a_value_param, internal::CodeLocation a_code_location, internal::TypeId fixture_class_id, internal::TestFactoryBase *factory)
int increment_death_test_count ()
void Run ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestInfo)
TestInfo (const std::string &test_case_name, const std::string &name, const char *a_type_param, const char *a_value_param, internal::CodeLocation a_code_location, internal::TypeId fixture_class_id, internal::TestFactoryBase *factory)
int increment_death_test_count ()
void Run ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestInfo)
TestInfo (const std::string &test_case_name, const std::string &name, const char *a_type_param, const char *a_value_param, internal::CodeLocation a_code_location, internal::TypeId fixture_class_id, internal::TestFactoryBase *factory)
int increment_death_test_count ()
void Run ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestInfo)
Static Private Member Functions
static void ClearTestResult (TestInfo *test_info)
static void ClearTestResult (TestInfo *test_info)
static void ClearTestResult (TestInfo *test_info)
Private Attributes
const std::string test_case_name_
const std::string name_
const internal::scoped_ptr< const ::std::string > type_param_
const internal::scoped_ptr< const ::std::string > value_param_
internal::CodeLocation location_
const internal::TypeId fixture_class_id_
bool should_run_
bool is_disabled_
bool matches_filter_
internal::TestFactoryBase *const factory_
TestResult result_
Friends
class Test
class TestCase
class internal::UnitTestImpl
class internal::StreamingListenerTest
TestInfo * internal::MakeAndRegisterTestInfo (const char *test_case_name, const char *name, const char *type_param, const char *value_param, internal::CodeLocation code_location, internal::TypeId fixture_class_id, Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc, internal::TestFactoryBase *factory)
TestInfo * internal::MakeAndRegisterTestInfo (const char *test_case_name, const char *name, const char *type_param, const char *value_param, internal::CodeLocation code_location, internal::TypeId fixture_class_id, Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc, internal::TestFactoryBase *factory)
TestInfo * internal::MakeAndRegisterTestInfo (const char *test_case_name, const char *name, const char *type_param, const char *value_param, internal::CodeLocation code_location, internal::TypeId fixture_class_id, Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc, internal::TestFactoryBase *factory)
Detailed Description
Definition at line 644 of file gtest.h.
Constructor & Destructor Documentation
testing::TestInfo::~TestInfo ()
Definition at line 2521 of file gtest.cc.
References factory_.
Referenced by testing::TestPartNonfatallyFailed().
 { delete factory_; }
testing::TestInfo::TestInfo (const std::string & test_case_name, const std::string & name, const char * a_type_param, const char * a_value_param, internal::CodeLocation a_code_location, internal::TypeId fixture_class_id, internal::TestFactoryBase * factory) private
Definition at line 2501 of file gtest.cc.
Referenced by testing::internal::MakeAndRegisterTestInfo(), and testing::TestPartNonfatallyFailed().
     : test_case_name_(a_test_case_name),
       name_(a_name),
       type_param_(a_type_param ? new std::string(a_type_param) : NULL),
       value_param_(a_value_param ? new std::string(a_value_param) : NULL),
       location_(a_code_location),
       fixture_class_id_(fixture_class_id),
       should_run_(false),
       is_disabled_(false),
       matches_filter_(false),
       factory_(factory),
       result_() {}
testing::TestInfo::~TestInfo ()
testing::TestInfo::TestInfo (const std::string & test_case_name, const std::string & name, const char * a_type_param, const char * a_value_param, internal::CodeLocation a_code_location, internal::TypeId fixture_class_id, internal::TestFactoryBase * factory) private
testing::TestInfo::~TestInfo ()
testing::TestInfo::TestInfo (const std::string & test_case_name, const std::string & name, const char * a_type_param, const char * a_value_param, internal::CodeLocation a_code_location, internal::TypeId fixture_class_id, internal::TestFactoryBase * factory) private
Member Function Documentation
static void testing::TestInfo::ClearTestResult (TestInfo * test_info) inline static private
Definition at line 746 of file gtest.h.
References testing::TestResult::Clear(), and result_.
Referenced by testing::TestCase::ClearResult().
{
     test_info->result_.Clear();
   }
static void testing::TestInfo::ClearTestResult (TestInfo * test_info) inline static private
Definition at line 746 of file gtest.h.
References testing::TestResult::Clear(), GTEST_API_, GTEST_DISALLOW_COPY_AND_ASSIGN_, name, name_, result_, string, and gmock_test_utils::TestCase.
{
     test_info->result_.Clear();
   }
static void testing::TestInfo::ClearTestResult (TestInfo * test_info) inline static private
Definition at line 746 of file gtest.h.
References testing::TestResult::Clear(), GTEST_API_, GTEST_DISALLOW_COPY_AND_ASSIGN_, name, name_, result_, string, and gmock_test_utils::TestCase.
{
     test_info->result_.Clear();
   }
const char* testing::TestInfo::file () const inline
Definition at line 673 of file gtest.h.
 { return location_.file.c_str(); }
const char* testing::TestInfo::file () const inline
Definition at line 673 of file gtest.h.
 { return location_.file.c_str(); }
const char* testing::TestInfo::file () const inline
Definition at line 673 of file gtest.h.
 { return location_.file.c_str(); }
testing::TestInfo::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestInfo) private
testing::TestInfo::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestInfo) private
testing::TestInfo::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestInfo) private
int testing::TestInfo::increment_death_test_count () inline private
Definition at line 738 of file gtest.h.
References Run().
{
     return result_.increment_death_test_count();
   }
int testing::TestInfo::increment_death_test_count () inline private
Definition at line 738 of file gtest.h.
References Run().
{
     return result_.increment_death_test_count();
   }
int testing::TestInfo::increment_death_test_count () inline private
Definition at line 738 of file gtest.h.
References Run().
{
     return result_.increment_death_test_count();
   }
bool testing::TestInfo::is_reportable () const inline
Definition at line 697 of file gtest.h.
{
     // For now, the XML report includes all tests matching the filter.
     // In the future, we may trim tests that are excluded because of
     // sharding.
     return matches_filter_;
   }
bool testing::TestInfo::is_reportable () const inline
Definition at line 697 of file gtest.h.
{
     // For now, the XML report includes all tests matching the filter.
     // In the future, we may trim tests that are excluded because of
     // sharding.
     return matches_filter_;
   }
bool testing::TestInfo::is_reportable () const inline
Definition at line 697 of file gtest.h.
Referenced by testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PortableLocaltime(), testing::TestCase::TestReportable(), and testing::TestCase::TestReportableDisabled().
{
     // For now, the XML report includes all tests matching the filter.
     // In the future, we may trim tests that are excluded because of
     // sharding.
     return matches_filter_;
   }
int testing::TestInfo::line () const inline
Definition at line 676 of file gtest.h.
 { return location_.line; }
int testing::TestInfo::line () const inline
Definition at line 676 of file gtest.h.
 { return location_.line; }
int testing::TestInfo::line () const inline
Definition at line 676 of file gtest.h.
 { return location_.line; }
const char* testing::TestInfo::name () const inline
Definition at line 654 of file gtest.h.
References name_.
Referenced by HTTPParallelCodecTest::dumpToFile(), testing::internal::UnitTestImpl::FilterTests(), testing::TestInfoTest::GetTestInfo(), testing::TestInfoTest::GetTestResult(), testing::Test::HasSameFixtureClass(), testing::internal::UnitTestImpl::ListTestsMatchingFilter(), testing::internal::MakeAndRegisterTestInfo(), testing::internal::PrettyUnitTestResultPrinter::OnTestEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestStart(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PortableLocaltime(), testing::internal::PrettyUnitTestResultPrinter::PrintFailedTests(), testing::internal::PrintOnOneLine(), CommonTest< T >::TearDown(), testing::internal::TearDownEnvironment(), testing::CurrentTestInfoTest::TearDownTestCase(), testing::TEST_F(), testing::internal::TestResultAccessor::test_part_results(), and testing::TestPartNonfatallyFailed().
 { return name_.c_str(); }
const char* testing::TestInfo::name () const inline
Definition at line 654 of file gtest.h.
References name_.
 { return name_.c_str(); }
const char* testing::TestInfo::name () const inline
Definition at line 654 of file gtest.h.
References name_.
 { return name_.c_str(); }
const TestResult* testing::TestInfo::result () const inline
Definition at line 705 of file gtest.h.
References testing::internal::MakeAndRegisterTestInfo(), name, and string.
 { return &result_; }
const TestResult* testing::TestInfo::result () const inline
Definition at line 705 of file gtest.h.
References testing::internal::MakeAndRegisterTestInfo(), name, and string.
 { return &result_; }
const TestResult* testing::TestInfo::result () const inline
Definition at line 705 of file gtest.h.
Referenced by testing::TestInfoTest::GetTestResult(), testing::internal::PrettyUnitTestResultPrinter::OnTestEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PortableLocaltime(), testing::internal::PrettyUnitTestResultPrinter::PrintFailedTests(), testing::internal::FinalSuccessChecker::TearDown(), testing::internal::TestResultAccessor::test_part_results(), testing::TestCase::TestFailed(), and testing::TestCase::TestPassed().
 { return &result_; }
void testing::TestInfo::Run () private
void testing::TestInfo::Run () private
Definition at line 2630 of file gtest.cc.
References testing::internal::TestFactoryBase::CreateTest(), testing::Test::DeleteSelf_(), factory_, testing::UnitTest::GetInstance(), testing::internal::GetTimeInMillis(), testing::internal::GetUnitTestImpl(), testing::internal::HandleExceptionsInMethodIfSupported(), testing::Test::HasFatalFailure(), testing::UnitTest::listeners(), testing::TestEventListener::OnTestEnd(), testing::TestEventListener::OnTestStart(), testing::internal::UnitTestImpl::os_stack_trace_getter(), testing::TestEventListeners::repeater(), result_, testing::Test::Run(), testing::internal::UnitTestImpl::set_current_test_info(), testing::TestResult::set_elapsed_time(), should_run_, start, and testing::internal::OsStackTraceGetterInterface::UponLeavingGTest().
Referenced by testing::TestCase::Run().
                    {
   if (!should_run_) return;
   // Tells UnitTest where to store test result.
   internal::UnitTestImpl* const impl = internal::GetUnitTestImpl();
   impl->set_current_test_info(this);
   TestEventListener* repeater = UnitTest::GetInstance()->listeners().repeater();
   // Notifies the unit test event listeners that a test is about to start.
   repeater->OnTestStart(*this);
   const TimeInMillis start = internal::GetTimeInMillis();
   impl->os_stack_trace_getter()->UponLeavingGTest();
   // Creates the test object.
   Test* const test = internal::HandleExceptionsInMethodIfSupported(
       factory_, &internal::TestFactoryBase::CreateTest,
       "the test fixture's constructor");
   // Runs the test only if the test object was created and its
   // constructor didn't generate a fatal failure.
   if ((test != NULL) && !Test::HasFatalFailure()) {
     // This doesn't throw as all user code that can throw are wrapped into
     // exception handling code.
     test->Run();
   }
   // Deletes the test object.
   impl->os_stack_trace_getter()->UponLeavingGTest();
   internal::HandleExceptionsInMethodIfSupported(
       test, &Test::DeleteSelf_, "the test fixture's destructor");
   result_.set_elapsed_time(internal::GetTimeInMillis() - start);
   // Notifies the unit test event listener that a test has just finished.
   repeater->OnTestEnd(*this);
   // Tells UnitTest to stop associating assertion results to this
   // test.
   impl->set_current_test_info(NULL);
 }
void testing::TestInfo::Run () private
bool testing::TestInfo::should_run () const inline
Definition at line 694 of file gtest.h.
 { return should_run_; }
bool testing::TestInfo::should_run () const inline
Definition at line 694 of file gtest.h.
Referenced by testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PortableLocaltime(), testing::internal::PrettyUnitTestResultPrinter::PrintFailedTests(), testing::TestCase::ShouldRunTest(), testing::TestCase::TestFailed(), and testing::TestCase::TestPassed().
 { return should_run_; }
bool testing::TestInfo::should_run () const inline
Definition at line 694 of file gtest.h.
 { return should_run_; }
const char* testing::TestInfo::test_case_name () const inline
Definition at line 651 of file gtest.h.
 { return test_case_name_.c_str(); }
const char* testing::TestInfo::test_case_name () const inline
Definition at line 651 of file gtest.h.
Referenced by testing::internal::UnitTestImpl::AddTestInfo(), testing::TestInfoTest::GetTestResult(), testing::Test::HasSameFixtureClass(), testing::internal::MakeAndRegisterTestInfo(), testing::internal::PrettyUnitTestResultPrinter::OnTestEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestStart(), testing::CurrentTestInfoTest::TearDownTestCase(), testing::TEST_F(), and testing::TestPartNonfatallyFailed().
 { return test_case_name_.c_str(); }
const char* testing::TestInfo::test_case_name () const inline
Definition at line 651 of file gtest.h.
 { return test_case_name_.c_str(); }
const char* testing::TestInfo::type_param () const inline
Definition at line 658 of file gtest.h.
{
     if (type_param_.get() != NULL)
       return type_param_->c_str();
     return NULL;
   }
const char* testing::TestInfo::type_param () const inline
Definition at line 658 of file gtest.h.
{
     if (type_param_.get() != NULL)
       return type_param_->c_str();
     return NULL;
   }
const char* testing::TestInfo::type_param () const inline
Definition at line 658 of file gtest.h.
Referenced by testing::internal::UnitTestImpl::AddTestInfo(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PortableLocaltime(), and testing::internal::PrintFullTestCommentIfPresent().
{
     if (type_param_.get() != NULL)
       return type_param_->c_str();
     return NULL;
   }
const char* testing::TestInfo::value_param () const inline
Definition at line 666 of file gtest.h.
Referenced by testing::internal::UnitTestImpl::ListTestsMatchingFilter(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PortableLocaltime(), testing::internal::PrintFullTestCommentIfPresent(), and testing::internal::PrintOnOneLine().
{
     if (value_param_.get() != NULL)
       return value_param_->c_str();
     return NULL;
   }
const char* testing::TestInfo::value_param () const inline
Definition at line 666 of file gtest.h.
{
     if (value_param_.get() != NULL)
       return value_param_->c_str();
     return NULL;
   }
const char* testing::TestInfo::value_param () const inline
Definition at line 666 of file gtest.h.
{
     if (value_param_.get() != NULL)
       return value_param_->c_str();
     return NULL;
   }
Friends And Related Function Documentation
TestInfo* internal::MakeAndRegisterTestInfo (const char * test_case_name, const char * name, const char * type_param, const char * value_param, internal::CodeLocation code_location, internal::TypeId fixture_class_id, Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc, internal::TestFactoryBase * factory) friend
TestInfo* internal::MakeAndRegisterTestInfo (const char * test_case_name, const char * name, const char * type_param, const char * value_param, internal::CodeLocation code_location, internal::TypeId fixture_class_id, Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc, internal::TestFactoryBase * factory) friend
TestInfo* internal::MakeAndRegisterTestInfo (const char * test_case_name, const char * name, const char * type_param, const char * value_param, internal::CodeLocation code_location, internal::TypeId fixture_class_id, Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc, internal::TestFactoryBase * factory) friend
internal::StreamingListenerTest friend
Definition at line 714 of file gtest.h.
internal::UnitTestImpl friend
Definition at line 713 of file gtest.h.
Test friend
Definition at line 711 of file gtest.h.
TestCase friend
Definition at line 712 of file gtest.h.
Member Data Documentation
internal::TestFactoryBase *const testing::TestInfo::factory_ private
Definition at line 765 of file gtest.h.
Referenced by Run(), and ~TestInfo().
const internal::TypeId testing::TestInfo::fixture_class_id_ private
Definition at line 760 of file gtest.h.
Referenced by testing::Test::HasSameFixtureClass(), and testing::TestPartNonfatallyFailed().
bool testing::TestInfo::is_disabled_ private
Definition at line 762 of file gtest.h.
Referenced by testing::internal::UnitTestImpl::FilterTests(), testing::internal::TearDownEnvironment(), testing::TestCase::TestDisabled(), and testing::TestCase::TestReportableDisabled().
internal::CodeLocation testing::TestInfo::location_ private
Definition at line 759 of file gtest.h.
bool testing::TestInfo::matches_filter_ private
Definition at line 763 of file gtest.h.
Referenced by testing::internal::UnitTestImpl::FilterTests(), testing::internal::UnitTestImpl::ListTestsMatchingFilter(), testing::internal::PrintOnOneLine(), and testing::internal::TearDownEnvironment().
const std::string testing::TestInfo::name_ private
Definition at line 752 of file gtest.h.
Referenced by testing::internal::MakeAndRegisterTestInfo().
TestResult testing::TestInfo::result_ private
Definition at line 770 of file gtest.h.
Referenced by ClearTestResult(), testing::internal::UnitTestImpl::current_test_result(), testing::internal::UnitTestImpl::RecordProperty(), and Run().
bool testing::TestInfo::should_run_ private
Definition at line 761 of file gtest.h.
Referenced by testing::internal::UnitTestImpl::FilterTests(), Run(), and testing::internal::TearDownEnvironment().
const std::string testing::TestInfo::test_case_name_ private
Definition at line 751 of file gtest.h.
const internal::scoped_ptr< const ::std::string > testing::TestInfo::type_param_ private
Definition at line 755 of file gtest.h.
const internal::scoped_ptr< const ::std::string > testing::TestInfo::value_param_ private
Definition at line 758 of file gtest.h.
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/gtest.h
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest.cc