proxygen: testing::internal::MatchesRegexMatcher Class Reference
testing::internal::MatchesRegexMatcher Class Reference
#include <gmock-matchers.h>
Public Member Functions
MatchesRegexMatcher (const RE *regex, bool full_match)
template<typename CharType >
bool MatchAndExplain (CharType *s, MatchResultListener *listener) const
template<class MatcheeStringType >
bool MatchAndExplain (const MatcheeStringType &s, MatchResultListener *) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
MatchesRegexMatcher (const RE *regex, bool full_match)
template<typename CharType >
bool MatchAndExplain (CharType *s, MatchResultListener *listener) const
template<class MatcheeStringType >
bool MatchAndExplain (const MatcheeStringType &s, MatchResultListener *) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
MatchesRegexMatcher (const RE *regex, bool full_match)
template<typename CharType >
bool MatchAndExplain (CharType *s, MatchResultListener *listener) const
template<class MatcheeStringType >
bool MatchAndExplain (const MatcheeStringType &s, MatchResultListener *) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (MatchesRegexMatcher)
GTEST_DISALLOW_ASSIGN_ (MatchesRegexMatcher)
GTEST_DISALLOW_ASSIGN_ (MatchesRegexMatcher)
Private Attributes
const internal::linked_ptr< const RE > regex_
const bool full_match_
Detailed Description
Definition at line 1326 of file gmock-matchers.h.
Constructor & Destructor Documentation
testing::internal::MatchesRegexMatcher::MatchesRegexMatcher (const RE * regex, bool full_match) inline
Definition at line 1328 of file gmock-matchers.h.
       : regex_(regex), full_match_(full_match) {}
testing::internal::MatchesRegexMatcher::MatchesRegexMatcher (const RE * regex, bool full_match) inline
Definition at line 1328 of file gmock-matchers.h.
       : regex_(regex), full_match_(full_match) {}
testing::internal::MatchesRegexMatcher::MatchesRegexMatcher (const RE * regex, bool full_match) inline
Definition at line 1328 of file gmock-matchers.h.
       : regex_(regex), full_match_(full_match) {}
Member Function Documentation
void testing::internal::MatchesRegexMatcher::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 1359 of file gmock-matchers.h.
References testing::gtest_printers_test::Print(), and regex_.
{
     *os << "doesn't " << (full_match_ ? "match" : "contain")
         << " regular expression ";
     UniversalPrinter<internal::string>::Print(regex_->pattern(), os);
   }
void testing::internal::MatchesRegexMatcher::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 1359 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, testing::gtest_printers_test::Print(), and regex_.
{
     *os << "doesn't " << (full_match_ ? "match" : "contain")
         << " regular expression ";
     UniversalPrinter<internal::string>::Print(regex_->pattern(), os);
   }
void testing::internal::MatchesRegexMatcher::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 1359 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, testing::gtest_printers_test::Print(), and regex_.
{
     *os << "doesn't " << (full_match_ ? "match" : "contain")
         << " regular expression ";
     UniversalPrinter<internal::string>::Print(regex_->pattern(), os);
   }
void testing::internal::MatchesRegexMatcher::DescribeTo (::std::ostream * os) const inline
Definition at line 1353 of file gmock-matchers.h.
References testing::gtest_printers_test::Print(), and regex_.
{
     *os << (full_match_ ? "matches" : "contains")
         << " regular expression ";
     UniversalPrinter<internal::string>::Print(regex_->pattern(), os);
   }
void testing::internal::MatchesRegexMatcher::DescribeTo (::std::ostream * os) const inline
Definition at line 1353 of file gmock-matchers.h.
References testing::gtest_printers_test::Print(), and regex_.
{
     *os << (full_match_ ? "matches" : "contains")
         << " regular expression ";
     UniversalPrinter<internal::string>::Print(regex_->pattern(), os);
   }
void testing::internal::MatchesRegexMatcher::DescribeTo (::std::ostream * os) const inline
Definition at line 1353 of file gmock-matchers.h.
References testing::gtest_printers_test::Print(), and regex_.
{
     *os << (full_match_ ? "matches" : "contains")
         << " regular expression ";
     UniversalPrinter<internal::string>::Print(regex_->pattern(), os);
   }
testing::internal::MatchesRegexMatcher::GTEST_DISALLOW_ASSIGN_ (MatchesRegexMatcher) private
testing::internal::MatchesRegexMatcher::GTEST_DISALLOW_ASSIGN_ (MatchesRegexMatcher) private
testing::internal::MatchesRegexMatcher::GTEST_DISALLOW_ASSIGN_ (MatchesRegexMatcher) private
template<typename CharType > bool testing::internal::MatchesRegexMatcher::MatchAndExplain (CharType * s, MatchResultListener * listener) const inline
Definition at line 1337 of file gmock-matchers.h.
{
     return s != NULL && MatchAndExplain(internal::string(s), listener);
   }
template<typename CharType > bool testing::internal::MatchesRegexMatcher::MatchAndExplain (CharType * s, MatchResultListener * listener) const inline
Definition at line 1337 of file gmock-matchers.h.
{
     return s != NULL && MatchAndExplain(internal::string(s), listener);
   }
template<typename CharType > bool testing::internal::MatchesRegexMatcher::MatchAndExplain (CharType * s, MatchResultListener * listener) const inline
Definition at line 1337 of file gmock-matchers.h.
{
     return s != NULL && MatchAndExplain(internal::string(s), listener);
   }
template<class MatcheeStringType > bool testing::internal::MatchesRegexMatcher::MatchAndExplain (const MatcheeStringType & s, MatchResultListener *) const inline
Definition at line 1346 of file gmock-matchers.h.
References regex_.
{
     const internal::string& s2(s);
     return full_match_ ? RE::FullMatch(s2, *regex_) :
         RE::PartialMatch(s2, *regex_);
   }
template<class MatcheeStringType > bool testing::internal::MatchesRegexMatcher::MatchAndExplain (const MatcheeStringType & s, MatchResultListener *) const inline
Definition at line 1346 of file gmock-matchers.h.
References regex_.
{
     const internal::string& s2(s);
     return full_match_ ? RE::FullMatch(s2, *regex_) :
         RE::PartialMatch(s2, *regex_);
   }
template<class MatcheeStringType > bool testing::internal::MatchesRegexMatcher::MatchAndExplain (const MatcheeStringType & s, MatchResultListener *) const inline
Definition at line 1346 of file gmock-matchers.h.
References regex_.
{
     const internal::string& s2(s);
     return full_match_ ? RE::FullMatch(s2, *regex_) :
         RE::PartialMatch(s2, *regex_);
   }
Member Data Documentation
const bool testing::internal::MatchesRegexMatcher::full_match_ private
Definition at line 1367 of file gmock-matchers.h.
const internal::linked_ptr< const RE > testing::internal::MatchesRegexMatcher::regex_ private
Definition at line 1366 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h