proxygen: folly::ReadMostlySharedPtr< T, RefCount > Class Template Reference
folly::ReadMostlySharedPtr< T, RefCount > Class Template Reference
#include <ReadMostlySharedPtr.h>
Public Member Functions
ReadMostlySharedPtr ()
ReadMostlySharedPtr (const ReadMostlyWeakPtr< T, RefCount > &weakPtr)
ReadMostlySharedPtr (const ReadMostlyMainPtr< T, RefCount > &mainPtr)
ReadMostlySharedPtr (const ReadMostlySharedPtr &other)
ReadMostlySharedPtr & operator= (const ReadMostlySharedPtr &other)
ReadMostlySharedPtr & operator= (const ReadMostlyWeakPtr< T, RefCount > &other)
ReadMostlySharedPtr & operator= (const ReadMostlyMainPtr< T, RefCount > &other)
ReadMostlySharedPtr (ReadMostlySharedPtr &&other) noexcept
~ReadMostlySharedPtr () noexcept
ReadMostlySharedPtr & operator= (ReadMostlySharedPtr &&other) noexcept
bool operator== (const ReadMostlyMainPtr< T, RefCount > &other) const
bool operator== (T *other) const
bool operator== (const ReadMostlySharedPtr< T, RefCount > &other) const
void reset ()
T * get () const
std::shared_ptr< T > getStdShared () const
T & operator* () const
T * operator-> () const
size_t use_count () const
bool unique () const
operator bool () const
Private Member Functions
void reset (detail::ReadMostlySharedPtrCore< T, RefCount > *impl)
Private Attributes
T * ptr_ {nullptr}
detail::ReadMostlySharedPtrCore< T, RefCount > * impl_ {nullptr}
Friends
class ReadMostlyWeakPtr< T, RefCount >
Detailed Description
template<typename T, typename RefCount = DefaultRefCount>
class folly::ReadMostlySharedPtr< T, RefCount >
Definition at line 30 of file ReadMostlySharedPtr.h.
Constructor & Destructor Documentation
template<typename T, typename RefCount = DefaultRefCount> folly::ReadMostlySharedPtr< T, RefCount >::ReadMostlySharedPtr () inline
Definition at line 254 of file ReadMostlySharedPtr.h.
 {}
template<typename T, typename RefCount = DefaultRefCount> folly::ReadMostlySharedPtr< T, RefCount >::ReadMostlySharedPtr (const ReadMostlyWeakPtr< T, RefCount > & weakPtr) inline explicit
Definition at line 256 of file ReadMostlySharedPtr.h.
{
     reset(weakPtr.impl_);
   }
template<typename T, typename RefCount = DefaultRefCount> folly::ReadMostlySharedPtr< T, RefCount >::ReadMostlySharedPtr (const ReadMostlyMainPtr< T, RefCount > & mainPtr) inline explicit
Definition at line 261 of file ReadMostlySharedPtr.h.
{
     reset(mainPtr.impl_);
   }
template<typename T, typename RefCount = DefaultRefCount> folly::ReadMostlySharedPtr< T, RefCount >::ReadMostlySharedPtr (const ReadMostlySharedPtr< T, RefCount > & other) inline
Definition at line 265 of file ReadMostlySharedPtr.h.
{
     *this = other;
   }
template<typename T, typename RefCount = DefaultRefCount> folly::ReadMostlySharedPtr< T, RefCount >::ReadMostlySharedPtr (ReadMostlySharedPtr< T, RefCount > && other) inline noexcept
Definition at line 284 of file ReadMostlySharedPtr.h.
{
     *this = std::move(other);
   }
template<typename T, typename RefCount = DefaultRefCount> folly::ReadMostlySharedPtr< T, RefCount >::~ReadMostlySharedPtr () inline noexcept
Definition at line 288 of file ReadMostlySharedPtr.h.
{
     reset(nullptr);
   }
Member Function Documentation
template<typename T, typename RefCount = DefaultRefCount> T* folly::ReadMostlySharedPtr< T, RefCount >::get () const inline
Definition at line 314 of file ReadMostlySharedPtr.h.
Referenced by folly::ReadMostlyMainPtr< T >::operator==(), folly::ReadMostlySharedPtr< T >::operator==(), folly::operator==(), and TEST().
                  {
     return ptr_;
   }
template<typename T, typename RefCount = DefaultRefCount> std::shared_ptr<T> folly::ReadMostlySharedPtr< T, RefCount >::getStdShared () const inline
Definition at line 318 of file ReadMostlySharedPtr.h.
{
     if (impl_) {
       return impl_->getShared();
     } else {
       return {};
     }
   }
template<typename T, typename RefCount = DefaultRefCount> folly::ReadMostlySharedPtr< T, RefCount >::operator bool () const inline explicit
Definition at line 342 of file ReadMostlySharedPtr.h.
{
     return impl_ != nullptr;
   }
template<typename T, typename RefCount = DefaultRefCount> T& folly::ReadMostlySharedPtr< T, RefCount >::operator* () const inline
Definition at line 326 of file ReadMostlySharedPtr.h.
{
     return *get();
   }
template<typename T, typename RefCount = DefaultRefCount> T* folly::ReadMostlySharedPtr< T, RefCount >::operator-> () const inline
Definition at line 330 of file ReadMostlySharedPtr.h.
{
     return get();
   }
template<typename T, typename RefCount = DefaultRefCount> ReadMostlySharedPtr& folly::ReadMostlySharedPtr< T, RefCount >::operator= (const ReadMostlySharedPtr< T, RefCount > & other) inline
Definition at line 269 of file ReadMostlySharedPtr.h.
{
     reset(other.impl_);
     return *this;
   }
template<typename T, typename RefCount = DefaultRefCount> ReadMostlySharedPtr& folly::ReadMostlySharedPtr< T, RefCount >::operator= (const ReadMostlyWeakPtr< T, RefCount > & other) inline
Definition at line 274 of file ReadMostlySharedPtr.h.
{
     reset(other.impl_);
     return *this;
   }
template<typename T, typename RefCount = DefaultRefCount> ReadMostlySharedPtr& folly::ReadMostlySharedPtr< T, RefCount >::operator= (const ReadMostlyMainPtr< T, RefCount > & other) inline
Definition at line 279 of file ReadMostlySharedPtr.h.
{
     reset(other.impl_);
     return *this;
   }
template<typename T, typename RefCount = DefaultRefCount> ReadMostlySharedPtr& folly::ReadMostlySharedPtr< T, RefCount >::operator= (ReadMostlySharedPtr< T, RefCount > && other) inline noexcept
Definition at line 292 of file ReadMostlySharedPtr.h.
{
     std::swap(ptr_, other.ptr_);
     std::swap(impl_, other.impl_);
     return *this;
   }
template<typename T, typename RefCount = DefaultRefCount> bool folly::ReadMostlySharedPtr< T, RefCount >::operator== (const ReadMostlyMainPtr< T, RefCount > & other) const inline
Definition at line 298 of file ReadMostlySharedPtr.h.
{
     return get() == other.get();
   }
template<typename T, typename RefCount = DefaultRefCount> bool folly::ReadMostlySharedPtr< T, RefCount >::operator== (T * other) const inline
Definition at line 302 of file ReadMostlySharedPtr.h.
{
     return get() == other;
   }
template<typename T, typename RefCount = DefaultRefCount> bool folly::ReadMostlySharedPtr< T, RefCount >::operator== (const ReadMostlySharedPtr< T, RefCount > & other) const inline
Definition at line 306 of file ReadMostlySharedPtr.h.
{
     return get() == other.get();
   }
template<typename T, typename RefCount = DefaultRefCount> void folly::ReadMostlySharedPtr< T, RefCount >::reset () inline
Definition at line 310 of file ReadMostlySharedPtr.h.
Referenced by TEST_F().
                {
     reset(nullptr);
   }
template<typename T, typename RefCount = DefaultRefCount> void folly::ReadMostlySharedPtr< T, RefCount >::reset (detail::ReadMostlySharedPtrCore< T, RefCount > * impl) inline private
Definition at line 349 of file ReadMostlySharedPtr.h.
{
     if (impl_) {
       impl_->decref();
       impl_ = nullptr;
       ptr_ = nullptr;
     }
     if (impl && impl->incref()) {
       impl_ = impl;
       ptr_ = impl->get();
     }
   }
template<typename T, typename RefCount = DefaultRefCount> bool folly::ReadMostlySharedPtr< T, RefCount >::unique () const inline
Definition at line 338 of file ReadMostlySharedPtr.h.
                       {
     return use_count() == 1;
   }
template<typename T, typename RefCount = DefaultRefCount> size_t folly::ReadMostlySharedPtr< T, RefCount >::use_count () const inline
Definition at line 334 of file ReadMostlySharedPtr.h.
{
     return impl_->useCount();
   }
Friends And Related Function Documentation
template<typename T, typename RefCount = DefaultRefCount> friend class ReadMostlyWeakPtr< T, RefCount > friend
Definition at line 347 of file ReadMostlySharedPtr.h.
Member Data Documentation
template<typename T, typename RefCount = DefaultRefCount> detail::ReadMostlySharedPtrCore<T, RefCount>* folly::ReadMostlySharedPtr< T, RefCount >::impl_ {nullptr} private
Definition at line 363 of file ReadMostlySharedPtr.h.
Referenced by folly::ReadMostlySharedPtr< T >::operator=(), and folly::ReadMostlyWeakPtr< T >::ReadMostlyWeakPtr().
template<typename T, typename RefCount = DefaultRefCount> T* folly::ReadMostlySharedPtr< T, RefCount >::ptr_ {nullptr} private
Definition at line 362 of file ReadMostlySharedPtr.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/ReadMostlySharedPtr.h