proxygen: wangle::SocketPeeker::Callback Class Reference
wangle::SocketPeeker::Callback Class Reference abstract
#include <SocketPeeker.h>
Public Member Functions
virtual ~Callback ()=default
virtual void peekSuccess (std::vector< uint8_t > data) noexcept=0
virtual void peekError (const folly::AsyncSocketException &ex) noexcept=0
Detailed Description
Definition at line 30 of file SocketPeeker.h.
Constructor & Destructor Documentation
virtual wangle::SocketPeeker::Callback::~Callback () virtual default
Member Function Documentation
virtual void wangle::SocketPeeker::Callback::peekError (const folly::AsyncSocketException & ex) pure virtual noexcept
Implemented in wangle::PeekingAcceptorHandshakeHelper, and MockSocketPeekerCallback.
Referenced by wangle::SocketPeeker::readErr().
virtual void wangle::SocketPeeker::Callback::peekSuccess (std::vector< uint8_t > data) pure virtual noexcept
Implemented in wangle::PeekingAcceptorHandshakeHelper, and MockSocketPeekerCallback.
Referenced by wangle::SocketPeeker::readDataAvailable(), and wangle::SocketPeeker::start().
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/acceptor/SocketPeeker.h