proxygen: wangle::TLSPlaintextPeekingCallback Class Reference
wangle::TLSPlaintextPeekingCallback Class Reference
#include <TLSPlaintextPeekingCallback.h>
Public Member Functions
TLSPlaintextPeekingCallback ()
AcceptorHandshakeHelper::UniquePtr getHelper (const std::vector< uint8_t > &bytes, const folly::SocketAddress &clientAddr, std::chrono::steady_clock::time_point acceptTime, TransportInfo &tinfo) override
Public Member Functions inherited from wangle::PeekingAcceptorHandshakeHelper::PeekCallback
PeekCallback (size_t bytesRequired)
virtual ~PeekCallback ()=default
size_t getBytesRequired () const
Private Types
enum { kPeekCount = 9 }
Static Private Member Functions
static bool looksLikeTLS (const std::vector< uint8_t > &peekBytes)
Detailed Description
A peeking callback that makes it convenient to create a server that will accept both TLS and plaintext traffic.
Definition at line 28 of file TLSPlaintextPeekingCallback.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
kPeekCount
Definition at line 30 of file TLSPlaintextPeekingCallback.h.
 { kPeekCount = 9 };
Constructor & Destructor Documentation
wangle::TLSPlaintextPeekingCallback::TLSPlaintextPeekingCallback () inline
Definition at line 32 of file TLSPlaintextPeekingCallback.h.
References getHelper(), and looksLikeTLS().
                                :
     PeekingAcceptorHandshakeHelper::PeekCallback(kPeekCount) {}
Member Function Documentation
AcceptorHandshakeHelper::UniquePtr wangle::TLSPlaintextPeekingCallback::getHelper (const std::vector< uint8_t > & bytes, const folly::SocketAddress & clientAddr, std::chrono::steady_clock::time_point acceptTime, TransportInfo & tinfo) override virtual
Implements wangle::PeekingAcceptorHandshakeHelper::PeekCallback.
Definition at line 36 of file TLSPlaintextPeekingCallback.cpp.
References looksLikeTLS().
Referenced by TLSPlaintextPeekingCallback().
                     {
   if (!TLSPlaintextPeekingCallback::looksLikeTLS(bytes)) {
     return AcceptorHandshakeHelper::UniquePtr(
         new UnencryptedAcceptorHandshakeHelper());
   }
   return nullptr;
 }
bool wangle::TLSPlaintextPeekingCallback::looksLikeTLS (const std::vector< uint8_t > & peekBytes) static private
Definition at line 20 of file TLSPlaintextPeekingCallback.cpp.
References kPeekCount.
Referenced by getHelper(), and TLSPlaintextPeekingCallback().
{
   CHECK_GE(bytes.size(), kPeekCount);
   // TLS starts with
   // 0: 0x16 - handshake magic
   // 1: 0x03 - SSL major version
   // 2: 0x00 to 0x03 - minor version
   // 3-4: Length
   // 5: 0x01 - Handshake type (Client Hello)
   if (bytes[0] != 0x16 || bytes[1] != 0x03 || bytes[5] != 0x01) {
     return false;
   }
   return true;
 }
The documentation for this class was generated from the following files:
proxygen/wangle/wangle/acceptor/TLSPlaintextPeekingCallback.h
proxygen/wangle/wangle/acceptor/TLSPlaintextPeekingCallback.cpp