proxygen: gtest_help_test.GTestHelpTest Class Reference
gtest_help_test.GTestHelpTest Class Reference
Public Member Functions
def TestHelpFlag (self, flag)
def TestNonHelpFlag (self, flag)
def testPrintsHelpWithFullFlag (self)
def testPrintsHelpWithShortFlag (self)
def testPrintsHelpWithQuestionFlag (self)
def testPrintsHelpWithWindowsStyleQuestionFlag (self)
def testPrintsHelpWithUnrecognizedGoogleTestFlag (self)
def testPrintsHelpWithIncorrectFlagStyle (self)
def testRunsTestsWithoutHelpFlag (self)
def testRunsTestsWithGtestInternalFlag (self)
def TestHelpFlag (self, flag)
def TestNonHelpFlag (self, flag)
def testPrintsHelpWithFullFlag (self)
def testPrintsHelpWithShortFlag (self)
def testPrintsHelpWithQuestionFlag (self)
def testPrintsHelpWithWindowsStyleQuestionFlag (self)
def testPrintsHelpWithUnrecognizedGoogleTestFlag (self)
def testPrintsHelpWithIncorrectFlagStyle (self)
def testRunsTestsWithoutHelpFlag (self)
def testRunsTestsWithGtestInternalFlag (self)
def TestHelpFlag (self, flag)
def TestNonHelpFlag (self, flag)
def testPrintsHelpWithFullFlag (self)
def testPrintsHelpWithShortFlag (self)
def testPrintsHelpWithQuestionFlag (self)
def testPrintsHelpWithWindowsStyleQuestionFlag (self)
def testPrintsHelpWithUnrecognizedGoogleTestFlag (self)
def testPrintsHelpWithIncorrectFlagStyle (self)
def testRunsTestsWithoutHelpFlag (self)
def testRunsTestsWithGtestInternalFlag (self)
Detailed Description
Tests the --help flag and its equivalent forms.
Definition at line 98 of file gtest_help_test.py.
Member Function Documentation
def gtest_help_test.GTestHelpTest.TestHelpFlag (self, flag)
Verifies correct behavior when help flag is specified.
The right message must be printed and the tests must
skipped when the given flag is specified.
Args:
  flag:  A flag to pass to the binary or None.
Definition at line 101 of file gtest_help_test.py.
References gtest_help_test.RunWithFlag().
Referenced by gtest_help_test.GTestHelpTest.TestHelpFlag(), gtest_help_test.GTestHelpTest.testPrintsHelpWithFullFlag(), gtest_help_test.GTestHelpTest.testPrintsHelpWithIncorrectFlagStyle(), gtest_help_test.GTestHelpTest.testPrintsHelpWithQuestionFlag(), gtest_help_test.GTestHelpTest.testPrintsHelpWithShortFlag(), gtest_help_test.GTestHelpTest.testPrintsHelpWithUnrecognizedGoogleTestFlag(), and gtest_help_test.GTestHelpTest.testPrintsHelpWithWindowsStyleQuestionFlag().
   def TestHelpFlag(self, flag):
     """Verifies correct behavior when help flag is specified.
     The right message must be printed and the tests must
     skipped when the given flag is specified.
     Args:
       flag:  A flag to pass to the binary or None.
     """
     exit_code, output = RunWithFlag(flag)
     self.assertEquals(0, exit_code)
     self.assert_(HELP_REGEX.search(output), output)
     if IS_LINUX:
       self.assert_(STREAM_RESULT_TO_FLAG in output, output)
     else:
       self.assert_(STREAM_RESULT_TO_FLAG not in output, output)
     if SUPPORTS_DEATH_TESTS and not IS_WINDOWS:
       self.assert_(DEATH_TEST_STYLE_FLAG in output, output)
     else:
       self.assert_(DEATH_TEST_STYLE_FLAG not in output, output)
def gtest_help_test.GTestHelpTest.TestHelpFlag (self, flag)
Verifies correct behavior when help flag is specified.
The right message must be printed and the tests must
skipped when the given flag is specified.
Args:
  flag:  A flag to pass to the binary or None.
Definition at line 101 of file gtest_help_test.py.
References gtest_help_test.RunWithFlag(), and gtest_help_test.GTestHelpTest.TestHelpFlag().
   def TestHelpFlag(self, flag):
     """Verifies correct behavior when help flag is specified.
     The right message must be printed and the tests must
     skipped when the given flag is specified.
     Args:
       flag:  A flag to pass to the binary or None.
     """
     exit_code, output = RunWithFlag(flag)
     self.assertEquals(0, exit_code)
     self.assert_(HELP_REGEX.search(output), output)
     if IS_LINUX:
       self.assert_(STREAM_RESULT_TO_FLAG in output, output)
     else:
       self.assert_(STREAM_RESULT_TO_FLAG not in output, output)
     if SUPPORTS_DEATH_TESTS and not IS_WINDOWS:
       self.assert_(DEATH_TEST_STYLE_FLAG in output, output)
     else:
       self.assert_(DEATH_TEST_STYLE_FLAG not in output, output)
def gtest_help_test.GTestHelpTest.TestHelpFlag (self, flag)
Verifies correct behavior when help flag is specified.
The right message must be printed and the tests must
skipped when the given flag is specified.
Args:
  flag:  A flag to pass to the binary or None.
Definition at line 101 of file gtest_help_test.py.
References gtest_help_test.RunWithFlag(), and gtest_help_test.GTestHelpTest.TestHelpFlag().
   def TestHelpFlag(self, flag):
     """Verifies correct behavior when help flag is specified.
     The right message must be printed and the tests must
     skipped when the given flag is specified.
     Args:
       flag:  A flag to pass to the binary or None.
     """
     exit_code, output = RunWithFlag(flag)
     self.assertEquals(0, exit_code)
     self.assert_(HELP_REGEX.search(output), output)
     if IS_LINUX:
       self.assert_(STREAM_RESULT_TO_FLAG in output, output)
     else:
       self.assert_(STREAM_RESULT_TO_FLAG not in output, output)
     if SUPPORTS_DEATH_TESTS and not IS_WINDOWS:
       self.assert_(DEATH_TEST_STYLE_FLAG in output, output)
     else:
       self.assert_(DEATH_TEST_STYLE_FLAG not in output, output)
def gtest_help_test.GTestHelpTest.TestNonHelpFlag (self, flag)
Verifies correct behavior when no help flag is specified.
Verifies that when no help flag is specified, the tests are run
and the help message is not printed.
Args:
  flag:  A flag to pass to the binary or None.
Definition at line 125 of file gtest_help_test.py.
References gtest_help_test.RunWithFlag().
Referenced by gtest_help_test.GTestHelpTest.TestNonHelpFlag(), gtest_help_test.GTestHelpTest.testRunsTestsWithGtestInternalFlag(), and gtest_help_test.GTestHelpTest.testRunsTestsWithoutHelpFlag().
   def TestNonHelpFlag(self, flag):
     """Verifies correct behavior when no help flag is specified.
     Verifies that when no help flag is specified, the tests are run
     and the help message is not printed.
     Args:
       flag:  A flag to pass to the binary or None.
     """
     exit_code, output = RunWithFlag(flag)
     self.assert_(exit_code != 0)
     self.assert_(not HELP_REGEX.search(output), output)
def gtest_help_test.GTestHelpTest.TestNonHelpFlag (self, flag)
Verifies correct behavior when no help flag is specified.
Verifies that when no help flag is specified, the tests are run
and the help message is not printed.
Args:
  flag:  A flag to pass to the binary or None.
Definition at line 125 of file gtest_help_test.py.
References gtest_help_test.RunWithFlag(), and gtest_help_test.GTestHelpTest.TestNonHelpFlag().
   def TestNonHelpFlag(self, flag):
     """Verifies correct behavior when no help flag is specified.
     Verifies that when no help flag is specified, the tests are run
     and the help message is not printed.
     Args:
       flag:  A flag to pass to the binary or None.
     """
     exit_code, output = RunWithFlag(flag)
     self.assert_(exit_code != 0)
     self.assert_(not HELP_REGEX.search(output), output)
def gtest_help_test.GTestHelpTest.TestNonHelpFlag (self, flag)
Verifies correct behavior when no help flag is specified.
Verifies that when no help flag is specified, the tests are run
and the help message is not printed.
Args:
  flag:  A flag to pass to the binary or None.
Definition at line 125 of file gtest_help_test.py.
References gtest_help_test.RunWithFlag(), and gtest_help_test.GTestHelpTest.TestNonHelpFlag().
   def TestNonHelpFlag(self, flag):
     """Verifies correct behavior when no help flag is specified.
     Verifies that when no help flag is specified, the tests are run
     and the help message is not printed.
     Args:
       flag:  A flag to pass to the binary or None.
     """
     exit_code, output = RunWithFlag(flag)
     self.assert_(exit_code != 0)
     self.assert_(not HELP_REGEX.search(output), output)
def gtest_help_test.GTestHelpTest.testPrintsHelpWithFullFlag (self)
Definition at line 139 of file gtest_help_test.py.
References gtest_help_test.GTestHelpTest.TestHelpFlag(), and gtest_help_test.GTestHelpTest.testPrintsHelpWithFullFlag().
   def testPrintsHelpWithFullFlag(self):
     self.TestHelpFlag('--help')
def gtest_help_test.GTestHelpTest.testPrintsHelpWithFullFlag (self)
Definition at line 139 of file gtest_help_test.py.
References gtest_help_test.GTestHelpTest.TestHelpFlag().
Referenced by gtest_help_test.GTestHelpTest.testPrintsHelpWithFullFlag().
   def testPrintsHelpWithFullFlag(self):
     self.TestHelpFlag('--help')
def gtest_help_test.GTestHelpTest.testPrintsHelpWithFullFlag (self)
Definition at line 139 of file gtest_help_test.py.
References gtest_help_test.GTestHelpTest.TestHelpFlag(), and gtest_help_test.GTestHelpTest.testPrintsHelpWithFullFlag().
   def testPrintsHelpWithFullFlag(self):
     self.TestHelpFlag('--help')
def gtest_help_test.GTestHelpTest.testPrintsHelpWithIncorrectFlagStyle (self)
Definition at line 154 of file gtest_help_test.py.
References gtest_help_test.GTestHelpTest.TestHelpFlag().
Referenced by gtest_help_test.GTestHelpTest.testPrintsHelpWithIncorrectFlagStyle().
   def testPrintsHelpWithIncorrectFlagStyle(self):
     for incorrect_flag in INCORRECT_FLAG_VARIANTS:
       self.TestHelpFlag(incorrect_flag)
def gtest_help_test.GTestHelpTest.testPrintsHelpWithIncorrectFlagStyle (self)
Definition at line 154 of file gtest_help_test.py.
References gtest_help_test.GTestHelpTest.TestHelpFlag(), and gtest_help_test.GTestHelpTest.testPrintsHelpWithIncorrectFlagStyle().
   def testPrintsHelpWithIncorrectFlagStyle(self):
     for incorrect_flag in INCORRECT_FLAG_VARIANTS:
       self.TestHelpFlag(incorrect_flag)
def gtest_help_test.GTestHelpTest.testPrintsHelpWithIncorrectFlagStyle (self)
Definition at line 154 of file gtest_help_test.py.
References gtest_help_test.GTestHelpTest.TestHelpFlag(), and gtest_help_test.GTestHelpTest.testPrintsHelpWithIncorrectFlagStyle().
   def testPrintsHelpWithIncorrectFlagStyle(self):
     for incorrect_flag in INCORRECT_FLAG_VARIANTS:
       self.TestHelpFlag(incorrect_flag)
def gtest_help_test.GTestHelpTest.testPrintsHelpWithQuestionFlag (self)
Definition at line 145 of file gtest_help_test.py.
References gtest_help_test.GTestHelpTest.TestHelpFlag().
Referenced by gtest_help_test.GTestHelpTest.testPrintsHelpWithQuestionFlag().
   def testPrintsHelpWithQuestionFlag(self):
     self.TestHelpFlag('-?')
def gtest_help_test.GTestHelpTest.testPrintsHelpWithQuestionFlag (self)
Definition at line 145 of file gtest_help_test.py.
References gtest_help_test.GTestHelpTest.TestHelpFlag(), and gtest_help_test.GTestHelpTest.testPrintsHelpWithQuestionFlag().
   def testPrintsHelpWithQuestionFlag(self):
     self.TestHelpFlag('-?')
def gtest_help_test.GTestHelpTest.testPrintsHelpWithQuestionFlag (self)
Definition at line 145 of file gtest_help_test.py.
References gtest_help_test.GTestHelpTest.TestHelpFlag(), and gtest_help_test.GTestHelpTest.testPrintsHelpWithQuestionFlag().
   def testPrintsHelpWithQuestionFlag(self):
     self.TestHelpFlag('-?')
def gtest_help_test.GTestHelpTest.testPrintsHelpWithShortFlag (self)
Definition at line 142 of file gtest_help_test.py.
References gtest_help_test.GTestHelpTest.TestHelpFlag().
Referenced by gtest_help_test.GTestHelpTest.testPrintsHelpWithShortFlag().
   def testPrintsHelpWithShortFlag(self):
     self.TestHelpFlag('-h')
def gtest_help_test.GTestHelpTest.testPrintsHelpWithShortFlag (self)
Definition at line 142 of file gtest_help_test.py.
References gtest_help_test.GTestHelpTest.TestHelpFlag(), and gtest_help_test.GTestHelpTest.testPrintsHelpWithShortFlag().
   def testPrintsHelpWithShortFlag(self):
     self.TestHelpFlag('-h')
def gtest_help_test.GTestHelpTest.testPrintsHelpWithShortFlag (self)
Definition at line 142 of file gtest_help_test.py.
References gtest_help_test.GTestHelpTest.TestHelpFlag(), and gtest_help_test.GTestHelpTest.testPrintsHelpWithShortFlag().
   def testPrintsHelpWithShortFlag(self):
     self.TestHelpFlag('-h')
def gtest_help_test.GTestHelpTest.testPrintsHelpWithUnrecognizedGoogleTestFlag (self)
Definition at line 151 of file gtest_help_test.py.
References gtest_help_test.GTestHelpTest.TestHelpFlag().
Referenced by gtest_help_test.GTestHelpTest.testPrintsHelpWithUnrecognizedGoogleTestFlag().
   def testPrintsHelpWithUnrecognizedGoogleTestFlag(self):
     self.TestHelpFlag(UNKNOWN_FLAG)
def gtest_help_test.GTestHelpTest.testPrintsHelpWithUnrecognizedGoogleTestFlag (self)
Definition at line 151 of file gtest_help_test.py.
References gtest_help_test.GTestHelpTest.TestHelpFlag(), and gtest_help_test.GTestHelpTest.testPrintsHelpWithUnrecognizedGoogleTestFlag().
   def testPrintsHelpWithUnrecognizedGoogleTestFlag(self):
     self.TestHelpFlag(UNKNOWN_FLAG)
def gtest_help_test.GTestHelpTest.testPrintsHelpWithUnrecognizedGoogleTestFlag (self)
Definition at line 151 of file gtest_help_test.py.
References gtest_help_test.GTestHelpTest.TestHelpFlag(), and gtest_help_test.GTestHelpTest.testPrintsHelpWithUnrecognizedGoogleTestFlag().
   def testPrintsHelpWithUnrecognizedGoogleTestFlag(self):
     self.TestHelpFlag(UNKNOWN_FLAG)
def gtest_help_test.GTestHelpTest.testPrintsHelpWithWindowsStyleQuestionFlag (self)
Definition at line 148 of file gtest_help_test.py.
References gtest_help_test.GTestHelpTest.TestHelpFlag(), and gtest_help_test.GTestHelpTest.testPrintsHelpWithWindowsStyleQuestionFlag().
   def testPrintsHelpWithWindowsStyleQuestionFlag(self):
     self.TestHelpFlag('/?')
def gtest_help_test.GTestHelpTest.testPrintsHelpWithWindowsStyleQuestionFlag (self)
Definition at line 148 of file gtest_help_test.py.
References gtest_help_test.GTestHelpTest.TestHelpFlag(), and gtest_help_test.GTestHelpTest.testPrintsHelpWithWindowsStyleQuestionFlag().
   def testPrintsHelpWithWindowsStyleQuestionFlag(self):
     self.TestHelpFlag('/?')
def gtest_help_test.GTestHelpTest.testPrintsHelpWithWindowsStyleQuestionFlag (self)
Definition at line 148 of file gtest_help_test.py.
References gtest_help_test.GTestHelpTest.TestHelpFlag().
Referenced by gtest_help_test.GTestHelpTest.testPrintsHelpWithWindowsStyleQuestionFlag().
   def testPrintsHelpWithWindowsStyleQuestionFlag(self):
     self.TestHelpFlag('/?')
def gtest_help_test.GTestHelpTest.testRunsTestsWithGtestInternalFlag (self)
Verifies that the tests are run and no help message is printed when
a flag starting with Google Test prefix and 'internal_' is supplied.
Definition at line 164 of file gtest_help_test.py.
References gtest_test_utils.Main(), gtest_help_test.GTestHelpTest.TestNonHelpFlag(), and gtest_help_test.GTestHelpTest.testRunsTestsWithGtestInternalFlag().
   def testRunsTestsWithGtestInternalFlag(self):
     """Verifies that the tests are run and no help message is printed when
     a flag starting with Google Test prefix and 'internal_' is supplied."""
     self.TestNonHelpFlag(INTERNAL_FLAG_FOR_TESTING)
def gtest_help_test.GTestHelpTest.testRunsTestsWithGtestInternalFlag (self)
Verifies that the tests are run and no help message is printed when
a flag starting with Google Test prefix and 'internal_' is supplied.
Definition at line 164 of file gtest_help_test.py.
References gtest_test_utils.Main(), gtest_help_test.GTestHelpTest.TestNonHelpFlag(), and gtest_help_test.GTestHelpTest.testRunsTestsWithGtestInternalFlag().
   def testRunsTestsWithGtestInternalFlag(self):
     """Verifies that the tests are run and no help message is printed when
     a flag starting with Google Test prefix and 'internal_' is supplied."""
     self.TestNonHelpFlag(INTERNAL_FLAG_FOR_TESTING)
def gtest_help_test.GTestHelpTest.testRunsTestsWithGtestInternalFlag (self)
Verifies that the tests are run and no help message is printed when
a flag starting with Google Test prefix and 'internal_' is supplied.
Definition at line 164 of file gtest_help_test.py.
References gtest_test_utils.Main(), and gtest_help_test.GTestHelpTest.TestNonHelpFlag().
Referenced by gtest_help_test.GTestHelpTest.testRunsTestsWithGtestInternalFlag().
   def testRunsTestsWithGtestInternalFlag(self):
     """Verifies that the tests are run and no help message is printed when
     a flag starting with Google Test prefix and 'internal_' is supplied."""
     self.TestNonHelpFlag(INTERNAL_FLAG_FOR_TESTING)
def gtest_help_test.GTestHelpTest.testRunsTestsWithoutHelpFlag (self)
Verifies that when no help flag is specified, the tests are run
and the help message is not printed.
Definition at line 158 of file gtest_help_test.py.
References gtest_help_test.GTestHelpTest.TestNonHelpFlag(), and gtest_help_test.GTestHelpTest.testRunsTestsWithoutHelpFlag().
   def testRunsTestsWithoutHelpFlag(self):
     """Verifies that when no help flag is specified, the tests are run
     and the help message is not printed."""
     self.TestNonHelpFlag(None)
def gtest_help_test.GTestHelpTest.testRunsTestsWithoutHelpFlag (self)
Verifies that when no help flag is specified, the tests are run
and the help message is not printed.
Definition at line 158 of file gtest_help_test.py.
References gtest_help_test.GTestHelpTest.TestNonHelpFlag(), and gtest_help_test.GTestHelpTest.testRunsTestsWithoutHelpFlag().
   def testRunsTestsWithoutHelpFlag(self):
     """Verifies that when no help flag is specified, the tests are run
     and the help message is not printed."""
     self.TestNonHelpFlag(None)
def gtest_help_test.GTestHelpTest.testRunsTestsWithoutHelpFlag (self)
Verifies that when no help flag is specified, the tests are run
and the help message is not printed.
Definition at line 158 of file gtest_help_test.py.
References gtest_help_test.GTestHelpTest.TestNonHelpFlag().
Referenced by gtest_help_test.GTestHelpTest.testRunsTestsWithoutHelpFlag().
   def testRunsTestsWithoutHelpFlag(self):
     """Verifies that when no help flag is specified, the tests are run
     and the help message is not printed."""
     self.TestNonHelpFlag(None)
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest_help_test.py