proxygen: folly::symbolizer::ElfCache Class Reference
folly::symbolizer::ElfCache Class Reference
#include <ElfCache.h>
Classes
struct Entry
Public Member Functions
ElfCache (size_t capacity)
std::shared_ptr< ElfFile > getFile (StringPiece path) override
Public Member Functions inherited from folly::symbolizer::ElfCacheBase
virtual ~ElfCacheBase ()
Private Types
typedef boost::intrusive::list_member_hook LruLink
typedef boost::intrusive::list< Entry, boost::intrusive::member_hook< Entry, LruLink,&Entry::lruLink >, boost::intrusive::constant_time_size< false > > LruList
Static Private Member Functions
static std::shared_ptr< ElfFile > filePtr (const std::shared_ptr< Entry > &e)
Private Attributes
std::mutex mutex_
size_t capacity_
std::unordered_map< StringPiece, std::shared_ptr< Entry >, Hash > files_
LruList lruList_
Detailed Description
General-purpose ELF file cache.
LRU of given capacity. MT-safe (uses locking). Not async-signal-safe.
Definition at line 118 of file ElfCache.h.
Member Typedef Documentation
typedef boost::intrusive::list_member_hook folly::symbolizer::ElfCache::LruLink private
Definition at line 127 of file ElfCache.h.
typedef boost::intrusive::list< Entry, boost::intrusive::member_hook<Entry, LruLink, &Entry::lruLink>, boost::intrusive::constant_time_size<false> > folly::symbolizer::ElfCache::LruList private
Definition at line 144 of file ElfCache.h.
Constructor & Destructor Documentation
folly::symbolizer::ElfCache::ElfCache (size_t capacity) explicit
Definition at line 92 of file ElfCache.cpp.
 : capacity_(capacity) {}
Member Function Documentation
std::shared_ptr< ElfFile > folly::symbolizer::ElfCache::filePtr (const std::shared_ptr< Entry > & e) static private
Definition at line 129 of file ElfCache.cpp.
Referenced by getFile().
{
   // share ownership
   return std::shared_ptr<ElfFile>(e, &e->file);
 }
std::shared_ptr< ElfFile > folly::symbolizer::ElfCache::getFile (StringPiece path) override virtual
Implements folly::symbolizer::ElfCacheBase.
Definition at line 94 of file ElfCache.cpp.
References capacity_, filePtr(), files_, folly::symbolizer::ElfFile::kSuccess, folly::lock(), lruList_, mutex_, and folly::Range< Iter >::str().
{
   std::lock_guard<std::mutex> lock(mutex_);
   auto pos = files_.find(p);
   if (pos != files_.end()) {
     // Found, move to back (MRU)
     auto& entry = pos->second;
     lruList_.erase(lruList_.iterator_to(*entry));
     lruList_.push_back(*entry);
     return filePtr(entry);
   }
   auto entry = std::make_shared<Entry>();
   entry->path = p.str();
   auto& path = entry->path;
   // No negative caching
   const char* msg = "";
   int r = entry->file.openAndFollow(path.c_str(), true, &msg);
   if (r != ElfFile::kSuccess) {
     return nullptr;
   }
   if (files_.size() == capacity_) {
     auto& e = lruList_.front();
     lruList_.pop_front();
     files_.erase(e.path);
   }
   files_.emplace(entry->path, entry);
   lruList_.push_back(*entry);
   return filePtr(entry);
 }
Member Data Documentation
size_t folly::symbolizer::ElfCache::capacity_ private
Definition at line 137 of file ElfCache.h.
Referenced by getFile().
std::unordered_map<StringPiece, std::shared_ptr<Entry>, Hash> folly::symbolizer::ElfCache::files_ private
Definition at line 138 of file ElfCache.h.
Referenced by getFile().
LruList folly::symbolizer::ElfCache::lruList_ private
Definition at line 145 of file ElfCache.h.
Referenced by getFile().
std::mutex folly::symbolizer::ElfCache::mutex_ private
Definition at line 125 of file ElfCache.h.
Referenced by getFile().
The documentation for this class was generated from the following files:
proxygen/folly/folly/experimental/symbolizer/ElfCache.h
proxygen/folly/folly/experimental/symbolizer/ElfCache.cpp