proxygen: fizz::test::AuthenticatorTest Class Reference
fizz::test::AuthenticatorTest Class Reference
Public Member Functions
void SetUp () override
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Protected Attributes
std::unique_ptr< KeyDerivation > deriver_
std::vector< SignatureScheme > schemes_
Buf authrequest_
Buf handshakeContext_
Buf finishedKey_
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Protected Member Functions inherited from testing::Test
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Detailed Description
Definition at line 65 of file ExportedAuthenticatorTest.cpp.
Member Function Documentation
void fizz::test::AuthenticatorTest::SetUp () inline override virtual
Reimplemented from testing::Test.
Definition at line 67 of file ExportedAuthenticatorTest.cpp.
References fizz::CertificateRequest::certificate_request_context, cipher, folly::IOBuf::copyBuffer(), fizz::encode< CertificateRequest >(), fizz::encodeExtension(), fizz::CertificateRequest::extensions, folly::ssl::init(), fizz::Factory::makeKeyDeriver(), folly::gen::move, and fizz::SignatureAlgorithms::supported_signature_algorithms.
{
     folly::ssl::init();
     CertificateRequest cr;
     cr.certificate_request_context =
         folly::IOBuf::copyBuffer("0123456789abcdefghij");
     SignatureAlgorithms sigAlgs;
     sigAlgs.supported_signature_algorithms.push_back(
         SignatureScheme::ecdsa_secp256r1_sha256);
     cr.extensions.push_back(encodeExtension(std::move(sigAlgs)));
     auto authRequest = encode<CertificateRequest>(std::move(cr));
     authrequest_ = std::move(authRequest);
     CipherSuite cipher = CipherSuite::TLS_AES_128_GCM_SHA256;
     deriver_ = Factory().makeKeyDeriver(cipher);
     handshakeContext_ =
         folly::IOBuf::copyBuffer("12345678901234567890123456789012");
     finishedKey_ = folly::IOBuf::copyBuffer("12345678901234567890123456789012");
     schemes_.push_back(SignatureScheme::ecdsa_secp256r1_sha256);
   }
Member Data Documentation
Buf fizz::test::AuthenticatorTest::authrequest_ protected
Definition at line 89 of file ExportedAuthenticatorTest.cpp.
std::unique_ptr<KeyDerivation> fizz::test::AuthenticatorTest::deriver_ protected
Definition at line 87 of file ExportedAuthenticatorTest.cpp.
Buf fizz::test::AuthenticatorTest::finishedKey_ protected
Definition at line 91 of file ExportedAuthenticatorTest.cpp.
Buf fizz::test::AuthenticatorTest::handshakeContext_ protected
Definition at line 90 of file ExportedAuthenticatorTest.cpp.
std::vector<SignatureScheme> fizz::test::AuthenticatorTest::schemes_ protected
Definition at line 88 of file ExportedAuthenticatorTest.cpp.
The documentation for this class was generated from the following file:
proxygen/fizz/fizz/extensions/exportedauth/test/ExportedAuthenticatorTest.cpp