proxygen: testing::internal2::TypeWithoutFormatter< T, kTypeKind > Class Template Reference
testing::internal2::TypeWithoutFormatter< T, kTypeKind > Class Template Reference
#include <gtest-printers.h>
Static Public Member Functions
static void PrintValue (const T &value,::std::ostream *os)
static void PrintValue (const T &value,::std::ostream *os)
static void PrintValue (const T &value,::std::ostream *os)
Detailed Description
template<typename T, TypeKind kTypeKind>
class testing::internal2::TypeWithoutFormatter< T, kTypeKind >
Definition at line 136 of file gtest-printers.h.
Member Function Documentation
template<typename T , TypeKind kTypeKind> static void testing::internal2::TypeWithoutFormatter< T, kTypeKind >::PrintValue (const T & value, ::std::ostream * os) inline static
Definition at line 139 of file gtest-printers.h.
References testing::internal2::PrintBytesInObjectTo().
Referenced by testing::internal2::operator<<(), and testing::internal2::TypeWithoutFormatter< T, kConvertibleToInteger >::PrintValue().
{
     PrintBytesInObjectTo(reinterpret_cast<const unsigned char*>(&value),
                          sizeof(value), os);
   }
template<typename T , TypeKind kTypeKind> static void testing::internal2::TypeWithoutFormatter< T, kTypeKind >::PrintValue (const T & value, ::std::ostream * os) inline static
Definition at line 139 of file gtest-printers.h.
References testing::internal2::kProtobufOneLinerMaxLength, and testing::internal2::PrintBytesInObjectTo().
{
     PrintBytesInObjectTo(reinterpret_cast<const unsigned char*>(&value),
                          sizeof(value), os);
   }
template<typename T , TypeKind kTypeKind> static void testing::internal2::TypeWithoutFormatter< T, kTypeKind >::PrintValue (const T & value, ::std::ostream * os) inline static
Definition at line 139 of file gtest-printers.h.
References testing::internal2::kProtobufOneLinerMaxLength, and testing::internal2::PrintBytesInObjectTo().
{
     PrintBytesInObjectTo(reinterpret_cast<const unsigned char*>(&value),
                          sizeof(value), os);
   }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/gtest-printers.h