proxygen: wangle::LRUInMemoryCache< K, V, MutexT > Class Template Reference
wangle::LRUInMemoryCache< K, V, MutexT > Class Template Reference
#include <LRUInMemoryCache.h>
Public Member Functions
LRUInMemoryCache (size_t capacity)
~LRUInMemoryCache ()=default
folly::Optional< V > get (const K &key)
void put (const K &key, const V &val)
bool remove (const K &key)
size_t size () const
void clear ()
CacheDataVersion getVersion () const
CacheDataVersion loadData (const folly::dynamic &kvPairs) noexcept
folly::Optional< std::pair< folly::dynamic, CacheDataVersion > > convertToKeyValuePairs () noexcept
bool hasChangedSince (CacheDataVersion version) const
Private Member Functions
void incrementVersion ()
Private Attributes
folly::EvictingCacheMap< K, V > cache_
CacheDataVersion version_ {1}
MutexT cacheLock_
Detailed Description
template<typename K, typename V, typename MutexT>
class wangle::LRUInMemoryCache< K, V, MutexT >
A threadsafe cache map that delegates to an EvictingCacheMap and maintains a version of the data.
Definition at line 32 of file LRUInMemoryCache.h.
Constructor & Destructor Documentation
template<typename K, typename V, typename MutexT> wangle::LRUInMemoryCache< K, V, MutexT >::LRUInMemoryCache (size_t capacity) inline explicit
Create with the specified capacity.
Definition at line 37 of file LRUInMemoryCache.h.
 : cache_(capacity) {}
template<typename K, typename V, typename MutexT> wangle::LRUInMemoryCache< K, V, MutexT >::~LRUInMemoryCache () default
Referenced by wangle::LRUInMemoryCache< K, V, M >::LRUInMemoryCache().
Member Function Documentation
template<typename K , typename V , typename M > void wangle::LRUInMemoryCache< K, V, M >::clear ()
Definition at line 59 of file LRUInMemoryCache-inl.h.
Referenced by wangle::LRUInMemoryCache< K, V, M >::LRUInMemoryCache().
{
   typename wangle::CacheLockGuard<M>::Write writeLock(cacheLock_);
   if (cache_.empty()) {
     return;
   }
   cache_.clear();
   incrementVersion();
 }
template<typename K , typename V , typename M > folly::Optional< std::pair< folly::dynamic, CacheDataVersion > > wangle::LRUInMemoryCache< K, V, M >::convertToKeyValuePairs () noexcept
Get the cache data as a list of kv pairs along with the version
Definition at line 105 of file LRUInMemoryCache-inl.h.
References folly::dynamic::array(), folly::gen::move, folly::none, folly::dynamic::push_back(), and folly::toDynamic().
Referenced by wangle::LRUInMemoryCache< K, V, M >::LRUInMemoryCache().
{
   typename wangle::CacheLockGuard<M>::Read readLock(cacheLock_);
   try {
     folly::dynamic dynObj = folly::dynamic::array;
     for (const auto& kv : cache_) {
       dynObj.push_back(folly::toDynamic(std::make_pair(kv.first, kv.second)));
     }
     return std::make_pair(std::move(dynObj), version_);
   } catch (const std::exception& err) {
     LOG(ERROR) << "Converting cache to folly::dynamic failed with error: "
                << err.what();
   }
   return folly::none;
 }
template<typename K, typename V , typename M > folly::Optional< V > wangle::LRUInMemoryCache< K, V, M >::get (const K & key)
Definition at line 24 of file LRUInMemoryCache-inl.h.
References folly::none.
{
   // need to take a write lock since get modifies the LRU
   typename wangle::CacheLockGuard<M>::Write writeLock(cacheLock_);
   auto itr = cache_.find(key);
   if (itr != cache_.end()) {
     return folly::Optional<V>(itr->second);
   }
   return folly::none;
 }
template<typename K , typename V , typename M > CacheDataVersion wangle::LRUInMemoryCache< K, V, M >::getVersion () const
Definition at line 69 of file LRUInMemoryCache-inl.h.
Referenced by wangle::LRUInMemoryCache< K, V, M >::hasChangedSince(), and wangle::LRUInMemoryCache< K, V, M >::LRUInMemoryCache().
{
   typename wangle::CacheLockGuard<M>::Read readLock(cacheLock_);
   return version_;
 }
template<typename K, typename V, typename MutexT> bool wangle::LRUInMemoryCache< K, V, MutexT >::hasChangedSince (CacheDataVersion version) const inline
Determine if the cache has changed since the specified version
Definition at line 63 of file LRUInMemoryCache.h.
{
     return getVersion() != version;
   }
template<typename K, typename V, typename MutexT> void wangle::LRUInMemoryCache< K, V, MutexT >::incrementVersion () inline private
Definition at line 70 of file LRUInMemoryCache.h.
{
     ++version_;
     // if a uint64_t is incremented a billion times a second, it will still take
     // 585 years to wrap around, so don't bother
   }
template<typename K , typename V , typename M > CacheDataVersion wangle::LRUInMemoryCache< K, V, M >::loadData (const folly::dynamic & kvPairs) noexcept
Loads the list of kv pairs into the cache and bumps version. Returns the new cache version.
Definition at line 76 of file LRUInMemoryCache-inl.h.
References data.
Referenced by wangle::LRUInMemoryCache< K, V, M >::LRUInMemoryCache().
{
   bool updated = false;
   typename wangle::CacheLockGuard<M>::Write writeLock(cacheLock_);
   try {
     for (const auto& kv : data) {
       cache_.set(
         folly::convertTo<K>(kv[0]),
         folly::convertTo<V>(kv[1]));
       updated = true;
     }
   } catch (const folly::TypeError& err) {
     LOG(ERROR) << "Load cache failed with type error: "
                 << err.what();
   } catch (const std::out_of_range& err) {
     LOG(ERROR) << "Load cache failed with key error: "
                 << err.what();
   } catch (const std::exception& err) {
     LOG(ERROR) << "Load cache failed with error: "
                 << err.what();
   }
   if (updated) {
     // we still need to increment the version
     incrementVersion();
   }
   return version_;
 }
template<typename K, typename V, typename M > void wangle::LRUInMemoryCache< K, V, M >::put (const K & key, const V & val)
Definition at line 35 of file LRUInMemoryCache-inl.h.
Referenced by wangle::LRUInMemoryCache< K, V, M >::LRUInMemoryCache().
{
   typename wangle::CacheLockGuard<M>::Write writeLock(cacheLock_);
   cache_.set(key, val);
   incrementVersion();
 }
template<typename K, typename V , typename M > bool wangle::LRUInMemoryCache< K, V, M >::remove (const K & key)
Definition at line 42 of file LRUInMemoryCache-inl.h.
{
   typename wangle::CacheLockGuard<M>::Write writeLock(cacheLock_);
   size_t nErased = cache_.erase(key);
   if (nErased > 0) {
     incrementVersion();
     return true;
   }
   return false;
 }
template<typename K , typename V , typename M > size_t wangle::LRUInMemoryCache< K, V, M >::size () const
Definition at line 53 of file LRUInMemoryCache-inl.h.
Referenced by wangle::LRUInMemoryCache< K, V, M >::LRUInMemoryCache().
{
   typename wangle::CacheLockGuard<M>::Read readLock(cacheLock_);
   return cache_.size();
 }
Member Data Documentation
template<typename K, typename V, typename MutexT> folly::EvictingCacheMap<K, V> wangle::LRUInMemoryCache< K, V, MutexT >::cache_ private
Definition at line 76 of file LRUInMemoryCache.h.
template<typename K, typename V, typename MutexT> MutexT wangle::LRUInMemoryCache< K, V, MutexT >::cacheLock_ mutable private
Definition at line 80 of file LRUInMemoryCache.h.
template<typename K, typename V, typename MutexT> CacheDataVersion wangle::LRUInMemoryCache< K, V, MutexT >::version_ {1} private
Definition at line 78 of file LRUInMemoryCache.h.
Referenced by wangle::LRUInMemoryCache< K, V, M >::incrementVersion().
The documentation for this class was generated from the following files:
proxygen/wangle/wangle/client/persistence/LRUInMemoryCache.h
proxygen/wangle/wangle/client/persistence/LRUInMemoryCache-inl.h