proxygen: testing::TestPartResultArray Class Reference
testing::TestPartResultArray Class Reference
#include <gtest-test-part.h>
Public Member Functions
TestPartResultArray ()
void Append (const TestPartResult &result)
const TestPartResult & GetTestPartResult (int index) const
int size () const
TestPartResultArray ()
void Append (const TestPartResult &result)
const TestPartResult & GetTestPartResult (int index) const
int size () const
TestPartResultArray ()
void Append (const TestPartResult &result)
const TestPartResult & GetTestPartResult (int index) const
int size () const
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestPartResultArray)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestPartResultArray)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestPartResultArray)
Private Attributes
std::vector< TestPartResult > array_
Detailed Description
Definition at line 126 of file gtest-test-part.h.
Constructor & Destructor Documentation
testing::TestPartResultArray::TestPartResultArray () inline
Definition at line 128 of file gtest-test-part.h.
References folly::size().
 {}
testing::TestPartResultArray::TestPartResultArray () inline
Definition at line 128 of file gtest-test-part.h.
References GTEST_DISALLOW_COPY_AND_ASSIGN_, and folly::size().
 {}
testing::TestPartResultArray::TestPartResultArray () inline
Definition at line 128 of file gtest-test-part.h.
References GTEST_DISALLOW_COPY_AND_ASSIGN_, and folly::size().
 {}
Member Function Documentation
void testing::TestPartResultArray::Append (const TestPartResult & result)
Definition at line 68 of file gtest-test-part.cc.
Referenced by testing::ScopedFakeTestPartResultReporter::ReportTestPartResult().
{
   array_.push_back(result);
 }
void testing::TestPartResultArray::Append (const TestPartResult & result)
void testing::TestPartResultArray::Append (const TestPartResult & result)
const TestPartResult & testing::TestPartResultArray::GetTestPartResult (int index) const
Definition at line 73 of file gtest-test-part.cc.
References testing::internal::posix::Abort(), and folly::size().
Referenced by testing::internal::HasOneFailure(), operator<<(), and testing::internal::ShouldRunTestCase().
{
   if (index < 0 || index >= size()) {
     printf("\nInvalid index (%d) into TestPartResultArray.\n", index);
     internal::posix::Abort();
   }
   return array_[index];
 }
const TestPartResult& testing::TestPartResultArray::GetTestPartResult (int index) const
const TestPartResult& testing::TestPartResultArray::GetTestPartResult (int index) const
testing::TestPartResultArray::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestPartResultArray) private
testing::TestPartResultArray::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestPartResultArray) private
testing::TestPartResultArray::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestPartResultArray) private
int testing::TestPartResultArray::size () const
int testing::TestPartResultArray::size () const
int testing::TestPartResultArray::size () const
Definition at line 83 of file gtest-test-part.cc.
Referenced by testing::internal::HasOneFailure(), operator<<(), and testing::internal::ShouldRunTestCase().
{
   return static_cast<int>(array_.size());
 }
Member Data Documentation
std::vector< TestPartResult > testing::TestPartResultArray::array_ private
Definition at line 140 of file gtest-test-part.h.
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/gtest-test-part.h
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest-test-part.cc