proxygen: testing::internal::SizeIsMatcher< SizeMatcher > Class Template Reference
testing::internal::SizeIsMatcher< SizeMatcher > Class Template Reference
#include <gmock-matchers.h>
Classes
class Impl
Public Member Functions
SizeIsMatcher (const SizeMatcher &size_matcher)
template<typename Container >
operator Matcher< Container > () const
SizeIsMatcher (const SizeMatcher &size_matcher)
template<typename Container >
operator Matcher< Container > () const
SizeIsMatcher (const SizeMatcher &size_matcher)
template<typename Container >
operator Matcher< Container > () const
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (SizeIsMatcher)
GTEST_DISALLOW_ASSIGN_ (SizeIsMatcher)
GTEST_DISALLOW_ASSIGN_ (SizeIsMatcher)
Private Attributes
const SizeMatcher size_matcher_
Detailed Description
template<typename SizeMatcher>
class testing::internal::SizeIsMatcher< SizeMatcher >
Definition at line 2399 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename SizeMatcher > testing::internal::SizeIsMatcher< SizeMatcher >::SizeIsMatcher (const SizeMatcher & size_matcher) inline explicit
Definition at line 2401 of file gmock-matchers.h.
        : size_matcher_(size_matcher) {
   }
template<typename SizeMatcher > testing::internal::SizeIsMatcher< SizeMatcher >::SizeIsMatcher (const SizeMatcher & size_matcher) inline explicit
Definition at line 2401 of file gmock-matchers.h.
        : size_matcher_(size_matcher) {
   }
template<typename SizeMatcher > testing::internal::SizeIsMatcher< SizeMatcher >::SizeIsMatcher (const SizeMatcher & size_matcher) inline explicit
Definition at line 2401 of file gmock-matchers.h.
        : size_matcher_(size_matcher) {
   }
Member Function Documentation
template<typename SizeMatcher > testing::internal::SizeIsMatcher< SizeMatcher >::GTEST_DISALLOW_ASSIGN_ (SizeIsMatcher< SizeMatcher >) private
template<typename SizeMatcher > testing::internal::SizeIsMatcher< SizeMatcher >::GTEST_DISALLOW_ASSIGN_ (SizeIsMatcher< SizeMatcher >) private
template<typename SizeMatcher > testing::internal::SizeIsMatcher< SizeMatcher >::GTEST_DISALLOW_ASSIGN_ (SizeIsMatcher< SizeMatcher >) private
template<typename SizeMatcher > template<typename Container > testing::internal::SizeIsMatcher< SizeMatcher >::operator Matcher< Container > () const inline
Definition at line 2406 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(new Impl<Container>(size_matcher_));
   }
template<typename SizeMatcher > template<typename Container > testing::internal::SizeIsMatcher< SizeMatcher >::operator Matcher< Container > () const inline
Definition at line 2406 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(new Impl<Container>(size_matcher_));
   }
template<typename SizeMatcher > template<typename Container > testing::internal::SizeIsMatcher< SizeMatcher >::operator Matcher< Container > () const inline
Definition at line 2406 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(new Impl<Container>(size_matcher_));
   }
Member Data Documentation
template<typename SizeMatcher > const SizeMatcher testing::internal::SizeIsMatcher< SizeMatcher >::size_matcher_ private
Definition at line 2445 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h