proxygen: testing::internal::ResultOfMatcher< Callable >::Impl< T > Class Template Reference
testing::internal::ResultOfMatcher< Callable >::Impl< T > Class Template Reference
Public Member Functions
Impl (CallableStorageType callable, const Matcher< ResultType > &matcher)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (T obj, MatchResultListener *listener) const
Impl (CallableStorageType callable, const Matcher< ResultType > &matcher)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (T obj, MatchResultListener *listener) const
Impl (CallableStorageType callable, const Matcher< ResultType > &matcher)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (T obj, MatchResultListener *listener) const
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
virtual ~MatcherDescriberInterface ()
virtual ~MatcherDescriberInterface ()
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (Impl)
GTEST_DISALLOW_ASSIGN_ (Impl)
GTEST_DISALLOW_ASSIGN_ (Impl)
Private Attributes
CallableStorageType callable_
const Matcher< ResultType > matcher_
Detailed Description
template<typename Callable>
template<typename T>
class testing::internal::ResultOfMatcher< Callable >::Impl< T >
Definition at line 2355 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename Callable> template<typename T > testing::internal::ResultOfMatcher< Callable >::Impl< T >::Impl (CallableStorageType callable, const Matcher< ResultType > & matcher) inline
Definition at line 2357 of file gmock-matchers.h.
         : callable_(callable), matcher_(matcher) {}
template<typename Callable> template<typename T > testing::internal::ResultOfMatcher< Callable >::Impl< T >::Impl (CallableStorageType callable, const Matcher< ResultType > & matcher) inline
Definition at line 2357 of file gmock-matchers.h.
         : callable_(callable), matcher_(matcher) {}
template<typename Callable> template<typename T > testing::internal::ResultOfMatcher< Callable >::Impl< T >::Impl (CallableStorageType callable, const Matcher< ResultType > & matcher) inline
Definition at line 2357 of file gmock-matchers.h.
         : callable_(callable), matcher_(matcher) {}
Member Function Documentation
template<typename Callable> template<typename T > virtual void testing::internal::ResultOfMatcher< Callable >::Impl< T >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 2365 of file gmock-matchers.h.
{
       *os << "is mapped by the given callable to a value that ";
       matcher_.DescribeNegationTo(os);
     }
template<typename Callable> template<typename T > virtual void testing::internal::ResultOfMatcher< Callable >::Impl< T >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 2365 of file gmock-matchers.h.
{
       *os << "is mapped by the given callable to a value that ";
       matcher_.DescribeNegationTo(os);
     }
template<typename Callable> template<typename T > virtual void testing::internal::ResultOfMatcher< Callable >::Impl< T >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 2365 of file gmock-matchers.h.
{
       *os << "is mapped by the given callable to a value that ";
       matcher_.DescribeNegationTo(os);
     }
template<typename Callable> template<typename T > virtual void testing::internal::ResultOfMatcher< Callable >::Impl< T >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 2360 of file gmock-matchers.h.
{
       *os << "is mapped by the given callable to a value that ";
       matcher_.DescribeTo(os);
     }
template<typename Callable> template<typename T > virtual void testing::internal::ResultOfMatcher< Callable >::Impl< T >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 2360 of file gmock-matchers.h.
{
       *os << "is mapped by the given callable to a value that ";
       matcher_.DescribeTo(os);
     }
template<typename Callable> template<typename T > virtual void testing::internal::ResultOfMatcher< Callable >::Impl< T >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 2360 of file gmock-matchers.h.
{
       *os << "is mapped by the given callable to a value that ";
       matcher_.DescribeTo(os);
     }
template<typename Callable> template<typename T > testing::internal::ResultOfMatcher< Callable >::Impl< T >::GTEST_DISALLOW_ASSIGN_ (Impl< T >) private
template<typename Callable> template<typename T > testing::internal::ResultOfMatcher< Callable >::Impl< T >::GTEST_DISALLOW_ASSIGN_ (Impl< T >) private
template<typename Callable> template<typename T > testing::internal::ResultOfMatcher< Callable >::Impl< T >::GTEST_DISALLOW_ASSIGN_ (Impl< T >) private
template<typename Callable> template<typename T > virtual bool testing::internal::ResultOfMatcher< Callable >::Impl< T >::MatchAndExplain (T obj, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< T >.
Definition at line 2370 of file gmock-matchers.h.
References testing::internal::MatchPrintAndExplain().
{
       *listener << "which is mapped by the given callable to ";
       // Cannot pass the return value (for example, int) to
       // MatchPrintAndExplain, which takes a non-const reference as argument.
       ResultType result =
           CallableTraits<Callable>::template Invoke<T>(callable_, obj);
       return MatchPrintAndExplain(result, matcher_, listener);
     }
template<typename Callable> template<typename T > virtual bool testing::internal::ResultOfMatcher< Callable >::Impl< T >::MatchAndExplain (T obj, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< T >.
Definition at line 2370 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, and testing::internal::MatchPrintAndExplain().
{
       *listener << "which is mapped by the given callable to ";
       // Cannot pass the return value (for example, int) to
       // MatchPrintAndExplain, which takes a non-const reference as argument.
       ResultType result =
           CallableTraits<Callable>::template Invoke<T>(callable_, obj);
       return MatchPrintAndExplain(result, matcher_, listener);
     }
template<typename Callable> template<typename T > virtual bool testing::internal::ResultOfMatcher< Callable >::Impl< T >::MatchAndExplain (T obj, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< T >.
Definition at line 2370 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, and testing::internal::MatchPrintAndExplain().
{
       *listener << "which is mapped by the given callable to ";
       // Cannot pass the return value (for example, int) to
       // MatchPrintAndExplain, which takes a non-const reference as argument.
       ResultType result =
           CallableTraits<Callable>::template Invoke<T>(callable_, obj);
       return MatchPrintAndExplain(result, matcher_, listener);
     }
Member Data Documentation
template<typename Callable> template<typename T > CallableStorageType testing::internal::ResultOfMatcher< Callable >::Impl< T >::callable_ mutable private
Definition at line 2385 of file gmock-matchers.h.
template<typename Callable> template<typename T > const Matcher< ResultType > testing::internal::ResultOfMatcher< Callable >::Impl< T >::matcher_ private
Definition at line 2386 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h