proxygen: testing::gmock_generated_actions_test::SubstractAction Class Reference
testing::gmock_generated_actions_test::SubstractAction Class Reference
Public Member Functions
virtual int Perform (const tuple< int, int > &args)
virtual int Perform (const tuple< int, int > &args)
virtual int Perform (const tuple< int, int > &args)
Public Member Functions inherited from testing::ActionInterface< F >
ActionInterface ()
virtual ~ActionInterface ()
virtual Result Perform (const ArgumentTuple &args)=0
ActionInterface ()
virtual ~ActionInterface ()
virtual Result Perform (const ArgumentTuple &args)=0
ActionInterface ()
virtual ~ActionInterface ()
virtual Result Perform (const ArgumentTuple &args)=0
Additional Inherited Members
Public Types inherited from testing::ActionInterface< F >
typedef internal::Function< F >::Result Result
typedef internal::Function< F >::ArgumentTuple ArgumentTuple
typedef internal::Function< F >::Result Result
typedef internal::Function< F >::ArgumentTuple ArgumentTuple
typedef internal::Function< F >::Result Result
typedef internal::Function< F >::ArgumentTuple ArgumentTuple
Detailed Description
Definition at line 369 of file gmock-generated-actions_test.cc.
Member Function Documentation
virtual int testing::gmock_generated_actions_test::SubstractAction::Perform (const tuple< int, int > & args) inline virtual
Definition at line 371 of file gmock-generated-actions_test.cc.
{
     return get<0>(args) - get<1>(args);
   }
virtual int testing::gmock_generated_actions_test::SubstractAction::Perform (const tuple< int, int > & args) inline virtual
Definition at line 371 of file gmock-generated-actions_test.cc.
References a, upload::action, testing::gmock_generated_actions_test::ACTION(), testing::gmock_generated_actions_test::ACTION_P(), testing::gmock_generated_actions_test::ACTION_P10(), testing::gmock_generated_actions_test::ACTION_P2(), testing::gmock_generated_actions_test::ACTION_P3(), testing::gmock_generated_actions_test::ACTION_P4(), testing::gmock_generated_actions_test::ACTION_P5(), testing::gmock_generated_actions_test::ACTION_P6(), testing::gmock_generated_actions_test::ACTION_P7(), testing::gmock_generated_actions_test::ACTION_P8(), testing::gmock_generated_actions_test::ACTION_P9(), b, testing::gmock_generated_actions_test::Binary(), c, ch, testing::gmock_generated_actions_test::Char(), testing::gmock_generated_actions_test::CharPtr(), testing::gmock_generated_actions_test::Concat(), testing::DoAll(), dummy(), testing::gmock_generated_actions_test::Dummy(), folly::empty(), EXPECT_DOUBLE_EQ, EXPECT_EQ, EXPECT_STREQ, EXPECT_TRUE, flag, g(), GTEST_INTENTIONAL_CONST_COND_POP_, GTEST_INTENTIONAL_CONST_COND_PUSH_, testing::Invoke(), k, m, std::tr1::make_tuple(), testing::MakeAction(), testing::Action< F >::Perform(), testing::gmock_generated_actions_test::Plus1(), prefix(), testing::Return(), s, testing::gmock_generated_actions_test::Short(), string, suffix, testing::gmock_generated_actions_test::SumOf4(), shell_builder::temp, testing::gmock_generated_actions_test::Ternary(), testing::gmock_generated_actions_test::TEST(), testing::gmock_generated_actions_test::VoidBinary(), and x.
{
     return get<0>(args) - get<1>(args);
   }
virtual int testing::gmock_generated_actions_test::SubstractAction::Perform (const tuple< int, int > & args) inline virtual
Definition at line 371 of file gmock-generated-actions_test.cc.
References a, upload::action, testing::gmock_generated_actions_test::ACTION(), testing::gmock_generated_actions_test::ACTION_P(), testing::gmock_generated_actions_test::ACTION_P10(), testing::gmock_generated_actions_test::ACTION_P2(), testing::gmock_generated_actions_test::ACTION_P3(), testing::gmock_generated_actions_test::ACTION_P4(), testing::gmock_generated_actions_test::ACTION_P5(), testing::gmock_generated_actions_test::ACTION_P6(), testing::gmock_generated_actions_test::ACTION_P7(), testing::gmock_generated_actions_test::ACTION_P8(), testing::gmock_generated_actions_test::ACTION_P9(), b, testing::gmock_generated_actions_test::Binary(), c, ch, testing::gmock_generated_actions_test::Char(), testing::gmock_generated_actions_test::CharPtr(), testing::gmock_generated_actions_test::Concat(), testing::DoAll(), dummy(), testing::gmock_generated_actions_test::Dummy(), folly::empty(), EXPECT_DOUBLE_EQ, EXPECT_EQ, EXPECT_STREQ, EXPECT_TRUE, flag, g(), GTEST_INTENTIONAL_CONST_COND_POP_, GTEST_INTENTIONAL_CONST_COND_PUSH_, testing::Invoke(), k, m, std::tr1::make_tuple(), testing::MakeAction(), testing::Action< F >::Perform(), testing::gmock_generated_actions_test::Plus1(), prefix(), testing::Return(), s, testing::gmock_generated_actions_test::Short(), string, suffix, testing::gmock_generated_actions_test::SumOf4(), shell_builder::temp, testing::gmock_generated_actions_test::Ternary(), testing::gmock_generated_actions_test::TEST(), testing::gmock_generated_actions_test::VoidBinary(), and x.
{
     return get<0>(args) - get<1>(args);
   }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-generated-actions_test.cc