proxygen: testing::internal::ComparisonBase< D, Rhs, Op >::Impl< Lhs > Class Template Reference
testing::internal::ComparisonBase< D, Rhs, Op >::Impl< Lhs > Class Template Reference
Public Member Functions
Impl (const Rhs &rhs)
virtual bool MatchAndExplain (Lhs lhs, MatchResultListener *) const
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
Impl (const Rhs &rhs)
virtual bool MatchAndExplain (Lhs lhs, MatchResultListener *) const
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
Impl (const Rhs &rhs)
virtual bool MatchAndExplain (Lhs lhs, MatchResultListener *) const
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
virtual ~MatcherDescriberInterface ()
virtual ~MatcherDescriberInterface ()
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (Impl)
GTEST_DISALLOW_ASSIGN_ (Impl)
GTEST_DISALLOW_ASSIGN_ (Impl)
Private Attributes
Rhs rhs_
Detailed Description
template<typename D, typename Rhs, typename Op>
template<typename Lhs>
class testing::internal::ComparisonBase< D, Rhs, Op >::Impl< Lhs >
Definition at line 903 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename D, typename Rhs, typename Op> template<typename Lhs > testing::internal::ComparisonBase< D, Rhs, Op >::Impl< Lhs >::Impl (const Rhs & rhs) inline explicit
Definition at line 905 of file gmock-matchers.h.
 : rhs_(rhs) {}
template<typename D, typename Rhs, typename Op> template<typename Lhs > testing::internal::ComparisonBase< D, Rhs, Op >::Impl< Lhs >::Impl (const Rhs & rhs) inline explicit
Definition at line 905 of file gmock-matchers.h.
 : rhs_(rhs) {}
template<typename D, typename Rhs, typename Op> template<typename Lhs > testing::internal::ComparisonBase< D, Rhs, Op >::Impl< Lhs >::Impl (const Rhs & rhs) inline explicit
Definition at line 905 of file gmock-matchers.h.
 : rhs_(rhs) {}
Member Function Documentation
template<typename D, typename Rhs, typename Op> template<typename Lhs > virtual void testing::internal::ComparisonBase< D, Rhs, Op >::Impl< Lhs >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 914 of file gmock-matchers.h.
References testing::internal::UniversalPrint().
{
       *os << D::NegatedDesc() <<  " ";
       UniversalPrint(rhs_, os);
     }
template<typename D, typename Rhs, typename Op> template<typename Lhs > virtual void testing::internal::ComparisonBase< D, Rhs, Op >::Impl< Lhs >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 914 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, and testing::internal::UniversalPrint().
{
       *os << D::NegatedDesc() <<  " ";
       UniversalPrint(rhs_, os);
     }
template<typename D, typename Rhs, typename Op> template<typename Lhs > virtual void testing::internal::ComparisonBase< D, Rhs, Op >::Impl< Lhs >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 914 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, and testing::internal::UniversalPrint().
{
       *os << D::NegatedDesc() <<  " ";
       UniversalPrint(rhs_, os);
     }
template<typename D, typename Rhs, typename Op> template<typename Lhs > virtual void testing::internal::ComparisonBase< D, Rhs, Op >::Impl< Lhs >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 910 of file gmock-matchers.h.
References testing::internal::UniversalPrint().
{
       *os << D::Desc() << " ";
       UniversalPrint(rhs_, os);
     }
template<typename D, typename Rhs, typename Op> template<typename Lhs > virtual void testing::internal::ComparisonBase< D, Rhs, Op >::Impl< Lhs >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 910 of file gmock-matchers.h.
References testing::internal::UniversalPrint().
{
       *os << D::Desc() << " ";
       UniversalPrint(rhs_, os);
     }
template<typename D, typename Rhs, typename Op> template<typename Lhs > virtual void testing::internal::ComparisonBase< D, Rhs, Op >::Impl< Lhs >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 910 of file gmock-matchers.h.
References testing::internal::UniversalPrint().
{
       *os << D::Desc() << " ";
       UniversalPrint(rhs_, os);
     }
template<typename D, typename Rhs, typename Op> template<typename Lhs > testing::internal::ComparisonBase< D, Rhs, Op >::Impl< Lhs >::GTEST_DISALLOW_ASSIGN_ (Impl< Lhs >) private
template<typename D, typename Rhs, typename Op> template<typename Lhs > testing::internal::ComparisonBase< D, Rhs, Op >::Impl< Lhs >::GTEST_DISALLOW_ASSIGN_ (Impl< Lhs >) private
template<typename D, typename Rhs, typename Op> template<typename Lhs > testing::internal::ComparisonBase< D, Rhs, Op >::Impl< Lhs >::GTEST_DISALLOW_ASSIGN_ (Impl< Lhs >) private
template<typename D, typename Rhs, typename Op> template<typename Lhs > virtual bool testing::internal::ComparisonBase< D, Rhs, Op >::Impl< Lhs >::MatchAndExplain (Lhs lhs, MatchResultListener *) const inline virtual
Implements testing::MatcherInterface< Lhs >.
Definition at line 906 of file gmock-matchers.h.
{
       return Op()(lhs, rhs_);
     }
template<typename D, typename Rhs, typename Op> template<typename Lhs > virtual bool testing::internal::ComparisonBase< D, Rhs, Op >::Impl< Lhs >::MatchAndExplain (Lhs lhs, MatchResultListener *) const inline virtual
Implements testing::MatcherInterface< Lhs >.
Definition at line 906 of file gmock-matchers.h.
{
       return Op()(lhs, rhs_);
     }
template<typename D, typename Rhs, typename Op> template<typename Lhs > virtual bool testing::internal::ComparisonBase< D, Rhs, Op >::Impl< Lhs >::MatchAndExplain (Lhs lhs, MatchResultListener *) const inline virtual
Implements testing::MatcherInterface< Lhs >.
Definition at line 906 of file gmock-matchers.h.
{
       return Op()(lhs, rhs_);
     }
Member Data Documentation
template<typename D, typename Rhs, typename Op> template<typename Lhs > Rhs testing::internal::ComparisonBase< D, Rhs, Op >::Impl< Lhs >::rhs_ private
Definition at line 919 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h