proxygen: folly::hazptr_obj_list< Atom > Class Template Reference
folly::hazptr_obj_list< Atom > Class Template Reference
#include <Hazptr-fwd.h>
Public Member Functions
hazptr_obj_list () noexcept
hazptr_obj_list (hazptr_obj< Atom > *obj) noexcept
hazptr_obj_list (hazptr_obj< Atom > *head, hazptr_obj< Atom > *tail, int count) noexcept
hazptr_obj< Atom > * head ()
hazptr_obj< Atom > * tail ()
int count ()
void push (hazptr_obj< Atom > *obj)
void splice (hazptr_obj_list< Atom > &l)
void clear ()
Private Attributes
hazptr_obj< Atom > * head_
hazptr_obj< Atom > * tail_
int count_
Detailed Description
template<template< typename > class Atom>
class folly::hazptr_obj_list< Atom >
hazptr_obj_list
hazptr_obj_list
List of hazptr_obj-s.
Definition at line 55 of file Hazptr-fwd.h.
Constructor & Destructor Documentation
template<template< typename > class Atom> folly::hazptr_obj_list< Atom >::hazptr_obj_list () inline noexcept
Definition at line 137 of file HazptrObj.h.
 : head_(nullptr), tail_(nullptr), count_(0) {}
template<template< typename > class Atom> folly::hazptr_obj_list< Atom >::hazptr_obj_list (hazptr_obj< Atom > * obj) inline explicit noexcept
Definition at line 139 of file HazptrObj.h.
       : head_(obj), tail_(obj), count_(1) {}
template<template< typename > class Atom> folly::hazptr_obj_list< Atom >::hazptr_obj_list (hazptr_obj< Atom > * head, hazptr_obj< Atom > * tail, int count) inline explicit noexcept
Definition at line 142 of file HazptrObj.h.
       : head_(head), tail_(tail), count_(count) {}
Member Function Documentation
template<template< typename > class Atom> void folly::hazptr_obj_list< Atom >::clear () inline
Definition at line 183 of file HazptrObj.h.
Referenced by folly::hazptr_obj_list< Atom >::splice().
                {
     head_ = nullptr;
     tail_ = nullptr;
     count_ = 0;
   }
template<template< typename > class Atom> int folly::hazptr_obj_list< Atom >::count () inline
Definition at line 156 of file HazptrObj.h.
Referenced by folly::hazptr_domain< DeterministicAtomic >::bulk_lookup_and_reclaim(), folly::hazptr_domain< DeterministicAtomic >::push_retired(), folly::hazptr_domain< DeterministicAtomic >::reclaim_all_objects(), and folly::hazptr_obj_list< Atom >::splice().
               {
     return count_;
   }
template<template< typename > class Atom> hazptr_obj<Atom>* folly::hazptr_obj_list< Atom >::head () inline
Definition at line 148 of file HazptrObj.h.
Referenced by folly::hazptr_domain< DeterministicAtomic >::push_retired(), and folly::hazptr_obj_list< Atom >::splice().
{
     return head_;
   }
template<template< typename > class Atom> void folly::hazptr_obj_list< Atom >::push (hazptr_obj< Atom > * obj) inline
Definition at line 160 of file HazptrObj.h.
Referenced by folly::hazptr_domain< DeterministicAtomic >::bulk_lookup_and_reclaim(), and folly::hazptr_obj_base_linked< NodeAuto< Atom >, Atom >::release_retire_mutable_children().
{
     obj->set_next(head_);
     head_ = obj;
     if (tail_ == nullptr) {
       tail_ = obj;
     }
     ++count_;
   }
template<template< typename > class Atom> void folly::hazptr_obj_list< Atom >::splice (hazptr_obj_list< Atom > & l) inline
Definition at line 169 of file HazptrObj.h.
References folly::hazptr_obj_list< Atom >::clear(), folly::hazptr_obj_list< Atom >::count(), count, folly::hazptr_obj_list< Atom >::head(), and folly::hazptr_obj_list< Atom >::tail().
Referenced by folly::hazptr_domain< DeterministicAtomic >::bulk_lookup_and_reclaim().
{
     if (l.count() == 0) {
       return;
     }
     if (count() == 0) {
       head_ = l.head();
     } else {
       tail_->set_next(l.head());
     }
     tail_ = l.tail();
     count_ += l.count();
     l.clear();
   }
template<template< typename > class Atom> hazptr_obj<Atom>* folly::hazptr_obj_list< Atom >::tail () inline
Definition at line 152 of file HazptrObj.h.
Referenced by folly::hazptr_domain< DeterministicAtomic >::push_retired(), and folly::hazptr_obj_list< Atom >::splice().
{
     return tail_;
   }
Member Data Documentation
template<template< typename > class Atom> int folly::hazptr_obj_list< Atom >::count_ private
Definition at line 134 of file HazptrObj.h.
template<template< typename > class Atom> hazptr_obj<Atom>* folly::hazptr_obj_list< Atom >::head_ private
Definition at line 132 of file HazptrObj.h.
template<template< typename > class Atom> hazptr_obj<Atom>* folly::hazptr_obj_list< Atom >::tail_ private
Definition at line 133 of file HazptrObj.h.
The documentation for this class was generated from the following files:
proxygen/folly/folly/synchronization/Hazptr-fwd.h
proxygen/folly/folly/synchronization/HazptrObj.h