proxygen: fizz::client::test::AsyncFizzClientTest Class Reference
fizz::client::test::AsyncFizzClientTest Class Reference
Public Member Functions
void SetUp () override
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Protected Member Functions
void expectTransportReadCallback ()
void expectAppClose ()
void connect ()
void fullHandshakeSuccess (bool acceptEarlyData, std::string alpn="h2", std::shared_ptr< const Cert > clientCert=nullptr, std::shared_ptr< const Cert > serverCert=nullptr, bool pskResumed=false)
void completeHandshake ()
void completeEarlyHandshake (EarlyDataParams params=getEarlyDataParams())
Protected Member Functions inherited from testing::Test
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Static Protected Member Functions
static EarlyDataParams getEarlyDataParams ()
Protected Attributes
AsyncFizzClientT< MockClientStateMachineInstance >::UniquePtr client_
std::shared_ptr< FizzClientContext > context_
std::shared_ptr< MockPskCache > mockPskCache_
MockAsyncTransport * socket_
MockClientStateMachineInstance * machine_
AsyncTransportWrapper::ReadCallback * socketReadCallback_
MockHandshakeCallbackT< MockClientStateMachineInstance > handshakeCallback_
MockReadCallback readCallback_
MockWriteCallback writeCallback_
EventBase evb_
MockReplaySafetyCallback mockReplayCallback_
folly::Optional< std::string > pskIdentity_ {"pskIdentity"}
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Detailed Description
Definition at line 52 of file AsyncFizzClientTest.cpp.
Member Function Documentation
void fizz::client::test::AsyncFizzClientTest::completeEarlyHandshake (EarlyDataParams params = getEarlyDataParams()) inline protected
Definition at line 145 of file AsyncFizzClientTest.cpp.
References testing::_, fizz::client::detail::actions(), folly::netops::connect(), folly::IOBuf::copyBuffer(), EXPECT_CALL, EXPECT_FALSE, testing::InvokeWithoutArgs(), fizz::client::ReportEarlyHandshakeSuccess::maxEarlyDataSize, folly::gen::move, and params.
{
     connect();
     EXPECT_CALL(*machine_, _processSocketData(_, _))
         .WillOnce(InvokeWithoutArgs([&params]() {
           auto addParamsToState =
               [params = std::move(params)](State& newState) mutable {
                 newState.earlyDataParams() = std::move(params);
               };
           ReportEarlyHandshakeSuccess reportSuccess;
           reportSuccess.maxEarlyDataSize = 1000;
           return detail::actions(
               std::move(addParamsToState),
               std::move(reportSuccess),
               WaitForData());
         }));
     EXPECT_CALL(handshakeCallback_, _fizzHandshakeSuccess());
     socketReadCallback_->readBufferAvailable(IOBuf::copyBuffer("ServerData"));
     EXPECT_FALSE(client_->isReplaySafe());
   }
void fizz::client::test::AsyncFizzClientTest::completeHandshake () inline protected
Definition at line 131 of file AsyncFizzClientTest.cpp.
References folly::netops::connect(), and EXPECT_CALL.
{
     connect();
     EXPECT_CALL(handshakeCallback_, _fizzHandshakeSuccess());
     fullHandshakeSuccess(false);
   }
void fizz::client::test::AsyncFizzClientTest::connect () inline protected
Definition at line 89 of file AsyncFizzClientTest.cpp.
References testing::_, EXPECT_CALL, testing::InvokeWithoutArgs(), sni, and string.
                  {
     expectTransportReadCallback();
     EXPECT_CALL(*machine_, _processConnect(_, _, _, _, _, _))
         .WillOnce(InvokeWithoutArgs([]() { return Actions(); }));
     const auto sni = std::string("www.example.com");
     client_->connect(&handshakeCallback_, nullptr, sni, pskIdentity_);
   }
void fizz::client::test::AsyncFizzClientTest::expectAppClose () inline protected
Definition at line 74 of file AsyncFizzClientTest.cpp.
References testing::_, fizz::client::detail::actions(), fizz::WriteToSocket::contents, fizz::TLSContent::contentType, folly::IOBuf::copyBuffer(), fizz::TLSContent::data, fizz::TLSContent::encryptionLevel, fizz::client::Error, EXPECT_CALL, fizz::Handshake, fizz::handshake, testing::InvokeWithoutArgs(), folly::gen::move, fizz::test::State::state(), and fizz::detail::write().
{
     EXPECT_CALL(*machine_, _processAppClose(_))
         .WillOnce(InvokeWithoutArgs([]() {
           TLSContent record;
           record.contentType = ContentType::handshake;
           record.data = IOBuf::copyBuffer("closenotify");
           record.encryptionLevel = EncryptionLevel::Handshake;
           WriteToSocket write;
           write.contents.emplace_back(std::move(record));
           return detail::actions(
               [](State& newState) { newState.state() = StateEnum::Error; },
               std::move(write));
         }));
   }
void fizz::client::test::AsyncFizzClientTest::expectTransportReadCallback () inline protected
Definition at line 69 of file AsyncFizzClientTest.cpp.
References testing::_, EXPECT_CALL, and socket_.
{
     EXPECT_CALL(*socket_, setReadCB(_))
         .WillRepeatedly(SaveArg<0>(&socketReadCallback_));
   }
void fizz::client::test::AsyncFizzClientTest::fullHandshakeSuccess (bool acceptEarlyData, std::string alpn = "h2", std::shared_ptr< const Cert > clientCert = nullptr, std::shared_ptr< const Cert > serverCert = nullptr, bool pskResumed = false) inline protected
Definition at line 97 of file AsyncFizzClientTest.cpp.
References testing::_, fizz::client::detail::actions(), alpn, clientCert, folly::IOBuf::copyBuffer(), fizz::client::ReportHandshakeSuccess::earlyDataAccepted, folly::Range< Iter >::empty(), EXPECT_CALL, testing::InvokeWithoutArgs(), folly::gen::move, folly::none, fizz::psk_ke, fizz::Resumption, serverCert, fizz::tls_1_3, and fizz::TLS_AES_128_GCM_SHA256.
{
     EXPECT_CALL(*machine_, _processSocketData(_, _))
         .WillOnce(InvokeWithoutArgs([=]() {
           auto addToState = [=](State& newState) {
             newState.exporterMasterSecret() =
                 folly::IOBuf::copyBuffer("12345678901234567890123456789012");
             newState.cipher() = CipherSuite::TLS_AES_128_GCM_SHA256;
             newState.version() = ProtocolVersion::tls_1_3;
             if (alpn.empty()) {
               newState.alpn() = none;
             } else {
               newState.alpn() = alpn;
             }
             newState.clientCert() = clientCert;
             newState.serverCert() = serverCert;
             if (acceptEarlyData || pskResumed) {
               newState.pskMode() = PskKeyExchangeMode::psk_ke;
               newState.pskType() = PskType::Resumption;
             }
           };
           ReportHandshakeSuccess reportSuccess;
           reportSuccess.earlyDataAccepted = acceptEarlyData;
           return detail::actions(
               std::move(addToState), std::move(reportSuccess), WaitForData());
         }));
     socketReadCallback_->readBufferAvailable(IOBuf::copyBuffer("ServerData"));
   }
static EarlyDataParams fizz::client::test::AsyncFizzClientTest::getEarlyDataParams () inline static protected
Definition at line 137 of file AsyncFizzClientTest.cpp.
References fizz::client::EarlyDataParams::alpn, fizz::client::EarlyDataParams::cipher, params, fizz::tls_1_3, fizz::TLS_AES_128_GCM_SHA256, and fizz::client::EarlyDataParams::version.
{
     EarlyDataParams params;
     params.version = ProtocolVersion::tls_1_3;
     params.cipher = CipherSuite::TLS_AES_128_GCM_SHA256;
     params.alpn = "h2";
     return params;
   }
void fizz::client::test::AsyncFizzClientTest::SetUp () inline override virtual
Reimplemented from testing::Test.
Definition at line 54 of file AsyncFizzClientTest.cpp.
References fizz::client::test::MockClientStateMachineInstance::instance, folly::gen::move, ON_CALL, testing::Return(), and socket_.
{
     context_ = std::make_shared<FizzClientContext>();
     context_->setSendEarlyData(true);
     mockPskCache_ = std::make_shared<MockPskCache>();
     context_->setPskCache(mockPskCache_);
     socket_ = new MockAsyncTransport();
     auto transport = AsyncTransportWrapper::UniquePtr(socket_);
     client_.reset(new AsyncFizzClientT<MockClientStateMachineInstance>(
         std::move(transport), context_));
     machine_ = MockClientStateMachineInstance::instance;
     ON_CALL(*socket_, good()).WillByDefault(Return(true));
     ON_CALL(readCallback_, isBufferMovable_()).WillByDefault(Return(true));
   }
Member Data Documentation
AsyncFizzClientT<MockClientStateMachineInstance>::UniquePtr fizz::client::test::AsyncFizzClientTest::client_ protected
Definition at line 165 of file AsyncFizzClientTest.cpp.
std::shared_ptr<FizzClientContext> fizz::client::test::AsyncFizzClientTest::context_ protected
Definition at line 166 of file AsyncFizzClientTest.cpp.
EventBase fizz::client::test::AsyncFizzClientTest::evb_ protected
Definition at line 174 of file AsyncFizzClientTest.cpp.
MockHandshakeCallbackT<MockClientStateMachineInstance> fizz::client::test::AsyncFizzClientTest::handshakeCallback_ protected
Definition at line 171 of file AsyncFizzClientTest.cpp.
MockClientStateMachineInstance* fizz::client::test::AsyncFizzClientTest::machine_ protected
Definition at line 169 of file AsyncFizzClientTest.cpp.
std::shared_ptr<MockPskCache> fizz::client::test::AsyncFizzClientTest::mockPskCache_ protected
Definition at line 167 of file AsyncFizzClientTest.cpp.
MockReplaySafetyCallback fizz::client::test::AsyncFizzClientTest::mockReplayCallback_ protected
Definition at line 175 of file AsyncFizzClientTest.cpp.
folly::Optional<std::string> fizz::client::test::AsyncFizzClientTest::pskIdentity_ {"pskIdentity"} protected
Definition at line 176 of file AsyncFizzClientTest.cpp.
MockReadCallback fizz::client::test::AsyncFizzClientTest::readCallback_ protected
Definition at line 172 of file AsyncFizzClientTest.cpp.
MockAsyncTransport* fizz::client::test::AsyncFizzClientTest::socket_ protected
Definition at line 168 of file AsyncFizzClientTest.cpp.
AsyncTransportWrapper::ReadCallback* fizz::client::test::AsyncFizzClientTest::socketReadCallback_ protected
Definition at line 170 of file AsyncFizzClientTest.cpp.
MockWriteCallback fizz::client::test::AsyncFizzClientTest::writeCallback_ protected
Definition at line 173 of file AsyncFizzClientTest.cpp.
The documentation for this class was generated from the following file:
proxygen/fizz/fizz/client/test/AsyncFizzClientTest.cpp