proxygen: folly::gen::detail::FileWriter Class Reference
folly::gen::detail::FileWriter Class Reference
#include <File-inl.h>
Public Member Functions
FileWriter (File file, std::unique_ptr< IOBuf > buffer)
template<class Source , class Value >
void compose (const GenImpl< Value, Source > &source) const
Public Member Functions inherited from folly::gen::Operator< FileWriter >
ResultGen compose (const GenImpl< Value, Source > &source) const
Public Member Functions inherited from folly::gen::FBounded< Self >
const Self & self () const
Self & self ()
Private Member Functions
void write (ByteRange v) const
void flushBuffer () const
Private Attributes
File file_
std::unique_ptr< IOBuf > buffer_
Additional Inherited Members
Protected Member Functions inherited from folly::gen::Operator< FileWriter >
Operator ()=default
Operator (Operator &&) noexcept=default
Operator (const Operator &)=default
Operator & operator= (Operator &&) noexcept=default
Operator & operator= (const Operator &)=default
Detailed Description
Definition at line 64 of file File-inl.h.
Constructor & Destructor Documentation
folly::gen::detail::FileWriter::FileWriter (File file, std::unique_ptr< IOBuf > buffer) inline
Definition at line 66 of file File-inl.h.
References folly::gen::detail::FileReader::buffer_.
       : file_(std::move(file)), buffer_(std::move(buffer)) {
     if (buffer_) {
       buffer_->clear();
     }
   }
Member Function Documentation
template<class Source , class Value > void folly::gen::detail::FileWriter::compose (const GenImpl< Value, Source > & source) const inline
Definition at line 74 of file File-inl.h.
References folly::gen::detail::FileReader::buffer_, folly::File::close(), folly::gen::detail::FileReader::file_, folly::gen::GenImpl< Value, Self >::foreach(), folly::gen::move, v, and fizz::detail::write().
{
     auto fn = [&](ByteRange v) {
       if (!this->buffer_ || v.size() >= this->buffer_->capacity()) {
         this->flushBuffer();
         this->write(v);
       } else {
         if (v.size() > this->buffer_->tailroom()) {
           this->flushBuffer();
         }
         memcpy(this->buffer_->writableTail(), v.data(), v.size());
         this->buffer_->append(v.size());
       }
     };
     // Iterate
     source.foreach(std::move(fn));
     flushBuffer();
     file_.close();
   }
void folly::gen::detail::FileWriter::flushBuffer () const inline private
Definition at line 110 of file File-inl.h.
References folly::gen::detail::FileReader::buffer_, and fizz::detail::write().
{
     if (buffer_ && buffer_->length() != 0) {
       write(ByteRange(buffer_->data(), buffer_->length()));
       buffer_->clear();
     }
   }
void folly::gen::detail::FileWriter::write (ByteRange v) const inline private
Definition at line 96 of file File-inl.h.
References folly::Range< Iter >::advance(), folly::Range< Iter >::data(), folly::Range< Iter >::empty(), folly::File::fd(), folly::gen::detail::FileReader::file_, folly::Range< Iter >::size(), and fizz::detail::write().
{
     ssize_t n;
     while (!v.empty()) {
       do {
         n = ::write(file_.fd(), v.data(), v.size());
       } while (n == -1 && errno == EINTR);
       if (n == -1) {
         throw std::system_error(
             errno, std::system_category(), "write() failed");
       }
       v.advance(size_t(n));
     }
   }
Member Data Documentation
std::unique_ptr<IOBuf> folly::gen::detail::FileWriter::buffer_ private
Definition at line 118 of file File-inl.h.
File folly::gen::detail::FileWriter::file_ mutable private
Definition at line 117 of file File-inl.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/gen/File-inl.h