proxygen: folly::FutureExecutor< ExecutorImpl > Class Template Reference
folly::FutureExecutor< ExecutorImpl > Class Template Reference
#include <FutureExecutor.h>
Public Member Functions
template<typename... Args>
FutureExecutor (Args &&...args)
template<typename F >
std::enable_if< folly::isFuture< invoke_result_t< F > >::value, invoke_result_t< F > >::type addFuture (F func)
template<typename F >
std::enable_if< !folly::isFuture< invoke_result_t< F > >::value, folly::Future< typename folly::lift_unit< invoke_result_t< F > >::type > >::type addFuture (F func)
Detailed Description
template<typename ExecutorImpl>
class folly::FutureExecutor< ExecutorImpl >
Definition at line 25 of file FutureExecutor.h.
Constructor & Destructor Documentation
template<typename ExecutorImpl> template<typename... Args> folly::FutureExecutor< ExecutorImpl >::FutureExecutor (Args &&... args) inline explicit
Definition at line 28 of file FutureExecutor.h.
References type, and folly::value().
       : ExecutorImpl(std::forward<Args>(args)...) {}
Member Function Documentation
template<typename ExecutorImpl> template<typename F > std::enable_if< folly::isFuture<invoke_result_t<F> >::value, invoke_result_t<F> >::type folly::FutureExecutor< ExecutorImpl >::addFuture (F func) inline
Definition at line 44 of file FutureExecutor.h.
References add, folly::Promise< T >::getFuture(), folly::gen::move, folly::Promise< T >::setTry(), folly::pushmi::detail::t, folly::T, type, and folly::value().
Referenced by futureExecutor().
                     {
     using T = typename invoke_result_t<F>::value_type;
     folly::Promise<T> promise;
     auto future = promise.getFuture();
     ExecutorImpl::add([promise = std::move(promise),
                        func = std::move(func)]() mutable {
       func().then([promise = std::move(promise)](folly::Try<T>&& t) mutable {
         promise.setTry(std::move(t));
       });
     });
     return future;
   }
template<typename ExecutorImpl> template<typename F > std::enable_if< !folly::isFuture<invoke_result_t<F> >::value, folly::Future<typename folly::lift_unit<invoke_result_t<F> >::type> >::type folly::FutureExecutor< ExecutorImpl >::addFuture (F func) inline
Definition at line 69 of file FutureExecutor.h.
References add, folly::Promise< T >::getFuture(), folly::gen::move, folly::Promise< T >::setWith(), folly::T, and type.
                     {
     using T = typename folly::lift_unit<invoke_result_t<F>>::type;
     folly::Promise<T> promise;
     auto future = promise.getFuture();
     ExecutorImpl::add(
         [promise = std::move(promise), func = std::move(func)]() mutable {
           promise.setWith(std::move(func));
         });
     return future;
   }
The documentation for this class was generated from the following file:
proxygen/folly/folly/executors/FutureExecutor.h