proxygen: folly::io::test::CompressionVarintTest Class Reference
folly::io::test::CompressionVarintTest Class Reference
Protected Member Functions
void SetUp () override
void runSimpleTest (const DataHolder &dh)
Protected Attributes
uint64_t uncompressedLength_
std::unique_ptr< Codec > codec_
Detailed Description
Definition at line 310 of file CompressionTest.cpp.
Member Function Documentation
void folly::io::test::CompressionVarintTest::runSimpleTest (const DataHolder & dh) protected
Definition at line 332 of file CompressionTest.cpp.
References codec_, folly::IOBuf::copyBuffer(), folly::io::test::DataHolder::data(), EXPECT_EQ, folly::io::test::DataHolder::hash(), folly::io::test::hashIOBuf(), max, min, folly::gen::move, folly::io::test::oneBasedMsbPos(), folly::Random::rand64(), uint64_t, and folly::IOBuf::wrapBuffer().
{
   auto original = IOBuf::wrapBuffer(dh.data(uncompressedLength_));
   auto compressed = codec_->compress(original.get());
   auto breakPoint =
       1UL +
       Random::rand64(
           std::max(uint64_t(9), oneBasedMsbPos(uncompressedLength_)) / 9UL);
   auto tinyBuf = IOBuf::copyBuffer(
       compressed->data(), std::min(compressed->length(), breakPoint));
   compressed->trimStart(breakPoint);
   tinyBuf->prependChain(std::move(compressed));
   compressed = std::move(tinyBuf);
   auto uncompressed = codec_->uncompress(compressed.get());
   EXPECT_EQ(uncompressedLength_, uncompressed->computeChainDataLength());
   EXPECT_EQ(dh.hash(uncompressedLength_), hashIOBuf(uncompressed.get()));
 }
void folly::io::test::CompressionVarintTest::SetUp () inline override protected
Definition at line 313 of file CompressionTest.cpp.
References codec_, folly::io::getCodec(), and uint64_t.
{
     auto tup = GetParam();
     uncompressedLength_ = uint64_t(1) << std::get<0>(tup);
     codec_ = getCodec(std::get<1>(tup));
   }
Member Data Documentation
std::unique_ptr<Codec> folly::io::test::CompressionVarintTest::codec_ protected
Definition at line 322 of file CompressionTest.cpp.
uint64_t folly::io::test::CompressionVarintTest::uncompressedLength_ protected
Definition at line 321 of file CompressionTest.cpp.
The documentation for this class was generated from the following file:
proxygen/folly/folly/compression/test/CompressionTest.cpp