proxygen: wangle::SSLSessionCallbacks Class Reference
wangle::SSLSessionCallbacks Class Reference abstract
#include <SSLSessionCallbacks.h>
Public Member Functions
virtual void setSSLSession (const std::string &identity, SSLSessionPtr session) noexcept=0
virtual SSLSessionPtr getSSLSession (const std::string &identity) const noexcept=0
virtual bool removeSSLSession (const std::string &identity) noexcept=0
virtual bool supportsPersistence () const noexcept
virtual size_t size () const
virtual ~SSLSessionCallbacks ()
Static Public Member Functions
static void attachCallbacksToContext (SSL_CTX *ctx, SSLSessionCallbacks *callbacks)
static void detachCallbacksFromContext (SSL_CTX *ctx, SSLSessionCallbacks *callbacks)
static SSLSessionCallbacks * getCacheFromContext (SSL_CTX *ctx)
Static Private Member Functions
static std::string getSessionKeyFromSSL (SSL *ssl)
static int newSessionCallback (SSL *ssl, SSL_SESSION *session)
static void removeSessionCallback (SSL_CTX *ctx, SSL_SESSION *session)
static int32_t & getCacheIndex ()
Detailed Description
Callbacks related to SSL session cache
This class contains three methods, setSSLSession() to store existing SSL session data to cache, getSSLSession() to retreive cached session data in cache, and removeSSLSession() to remove session data from cache.
Definition at line 41 of file SSLSessionCallbacks.h.
Constructor & Destructor Documentation
virtual wangle::SSLSessionCallbacks::~SSLSessionCallbacks () inline virtual
Definition at line 69 of file SSLSessionCallbacks.h.
References attachCallbacksToContext(), detachCallbacksFromContext(), getCacheFromContext(), getSessionKeyFromSSL(), newSessionCallback(), removeSessionCallback(), and string.
 {}
Member Function Documentation
void wangle::SSLSessionCallbacks::attachCallbacksToContext (SSL_CTX * ctx, SSLSessionCallbacks * callbacks) static
Sets up SSL Session callbacks on a context. The application is responsible for detaching the callbacks from the context.
Definition at line 24 of file SSLSessionCallbacks.cpp.
Referenced by main(), TEST(), and ~SSLSessionCallbacks().
{
   SSL_CTX_set_session_cache_mode(
       ctx,
       SSL_SESS_CACHE_NO_INTERNAL | SSL_SESS_CACHE_CLIENT |
           SSL_SESS_CACHE_NO_AUTO_CLEAR);
   // Only initializes the cache index the first time.
   SSLUtil::getSSLCtxExIndex(&getCacheIndex());
   SSL_CTX_set_ex_data(ctx, getCacheIndex(), callbacks);
   SSL_CTX_sess_set_new_cb(ctx, SSLSessionCallbacks::newSessionCallback);
   SSL_CTX_sess_set_remove_cb(ctx, SSLSessionCallbacks::removeSessionCallback);
 }
void wangle::SSLSessionCallbacks::detachCallbacksFromContext (SSL_CTX * ctx, SSLSessionCallbacks * callbacks) static
Detach the passed in callbacks from the context. If the callbacks are not set on the context, it is unchanged.
Definition at line 39 of file SSLSessionCallbacks.cpp.
Referenced by TEST(), and ~SSLSessionCallbacks().
{
   auto sslSessionCache = getCacheFromContext(ctx);
   if (sslSessionCache != callbacks) {
     return;
   }
   // We don't unset flags here because we cannot assume that we are the only
   // code that sets the cache flags.
   SSL_CTX_set_ex_data(ctx, getCacheIndex(), nullptr);
   SSL_CTX_sess_set_new_cb(ctx, nullptr);
   SSL_CTX_sess_set_remove_cb(ctx, nullptr);
 }
SSLSessionCallbacks * wangle::SSLSessionCallbacks::getCacheFromContext (SSL_CTX * ctx) static
Definition at line 54 of file SSLSessionCallbacks.cpp.
Referenced by TEST(), and ~SSLSessionCallbacks().
{
   return static_cast<SSLSessionCallbacks*>(
       SSL_CTX_get_ex_data(ctx, getCacheIndex()));
 }
static int32_t& wangle::SSLSessionCallbacks::getCacheIndex () inline static private
Definition at line 95 of file SSLSessionCallbacks.h.
References int32_t.
{
     static int32_t sExDataIndex = -1;
     return sExDataIndex;
   }
std::string wangle::SSLSessionCallbacks::getSessionKeyFromSSL (SSL * ssl) static private
Definition at line 60 of file SSLSessionCallbacks.cpp.
References folly::AsyncSSLSocket::getFromSSL().
Referenced by ~SSLSessionCallbacks().
{
   auto sock = folly::AsyncSSLSocket::getFromSSL(ssl);
   return sock ? sock->getSessionKey() : "";
 }
virtual SSLSessionPtr wangle::SSLSessionCallbacks::getSSLSession (const std::string & identity) const pure virtual noexcept
Implemented in wangle::SSLSessionPersistentCacheBase< K >, wangle::SSLSessionPersistentCacheBase< std::string >, wangle::ThreadSafeSSLSessionCache, FakeSessionCallbacks, FakeSessionCallbacks, and wangle::MockSSLSessionCallbacks.
int wangle::SSLSessionCallbacks::newSessionCallback (SSL * ssl, SSL_SESSION * session) static private
Definition at line 66 of file SSLSessionCallbacks.cpp.
References folly::AsyncSSLSocket::getSSLServerNameFromSSL(), folly::gen::move, name, wangle::setSessionServiceIdentity(), and string.
Referenced by ~SSLSessionCallbacks().
{
   SSLSessionPtr sessionPtr(session);
   SSL_CTX* ctx = SSL_get_SSL_CTX(ssl);
   auto sslSessionCache = getCacheFromContext(ctx);
   std::string sessionKey = getSessionKeyFromSSL(ssl);
   if (sessionKey.empty()) {
     const char* name = folly::AsyncSSLSocket::getSSLServerNameFromSSL(ssl);
     sessionKey = name ? name : "";
   }
   if (!sessionKey.empty()) {
     setSessionServiceIdentity(session, sessionKey);
     sslSessionCache->setSSLSession(sessionKey, std::move(sessionPtr));
     return 1;
   }
   return -1;
 }
void wangle::SSLSessionCallbacks::removeSessionCallback (SSL_CTX * ctx, SSL_SESSION * session) static private
Definition at line 84 of file SSLSessionCallbacks.cpp.
References wangle::getSessionServiceIdentity(), folly::portability::ssl::SSL_SESSION_get0_hostname(), and string.
Referenced by ~SSLSessionCallbacks().
{
   auto sslSessionCache = getCacheFromContext(ctx);
   auto identity = getSessionServiceIdentity(session);
   if (identity && !identity->empty()) {
     sslSessionCache->removeSSLSession(*identity);
   }
 #if OPENSSL_TICKETS
   else {
     auto hostname = SSL_SESSION_get0_hostname(session);
     if (hostname) {
       sslSessionCache->removeSSLSession(std::string(hostname));
     }
   }
 #endif
 }
virtual bool wangle::SSLSessionCallbacks::removeSSLSession (const std::string & identity) pure virtual noexcept
Implemented in wangle::SSLSessionPersistentCacheBase< K >, wangle::SSLSessionPersistentCacheBase< std::string >, FakeSessionCallbacks, FakeSessionCallbacks, wangle::MockSSLSessionCallbacks, and wangle::ThreadSafeSSLSessionCache.
virtual void wangle::SSLSessionCallbacks::setSSLSession (const std::string & identity, SSLSessionPtr session) pure virtual noexcept
Implemented in wangle::SSLSessionPersistentCacheBase< K >, wangle::SSLSessionPersistentCacheBase< std::string >, wangle::ThreadSafeSSLSessionCache, wangle::MockSSLSessionCallbacks, FakeSessionCallbacks, and FakeSessionCallbacks.
virtual size_t wangle::SSLSessionCallbacks::size () const inline virtual
Reimplemented in wangle::SSLSessionPersistentCacheBase< K >, wangle::SSLSessionPersistentCacheBase< std::string >, FakeSessionCallbacks, and wangle::ThreadSafeSSLSessionCache.
Definition at line 65 of file SSLSessionCallbacks.h.
{
     return 0;
   }
virtual bool wangle::SSLSessionCallbacks::supportsPersistence () const inline virtual noexcept
Reimplemented in wangle::SSLSessionPersistentCacheBase< K >, wangle::SSLSessionPersistentCacheBase< std::string >, and wangle::ThreadSafeSSLSessionCache.
Definition at line 61 of file SSLSessionCallbacks.h.
{
     return false;
   }
The documentation for this class was generated from the following files:
proxygen/wangle/wangle/client/ssl/SSLSessionCallbacks.h
proxygen/wangle/wangle/client/ssl/SSLSessionCallbacks.cpp