proxygen: folly::EventBase::LoopCallback Class Reference
folly::EventBase::LoopCallback Class Reference abstract
#include <EventBase.h>
Public Member Functions
virtual ~LoopCallback ()=default
virtual void runLoopCallback () noexcept=0
void cancelLoopCallback ()
bool isLoopCallbackScheduled () const
Private Types
typedef boost::intrusive::list< LoopCallback, boost::intrusive::constant_time_size< false > > List
Private Attributes
std::shared_ptr< RequestContext > context_
Friends
class EventBase
class VirtualEventBase
Detailed Description
A callback interface to use with runInLoop()
Derive from this class if you need to delay some code execution until the next iteration of the event loop. This allows you to schedule code to be invoked from the top-level of the loop, after your immediate callers have returned.
If a LoopCallback object is destroyed while it is scheduled to be run in the next loop iteration, it will automatically be cancelled.
Definition at line 148 of file EventBase.h.
Member Typedef Documentation
typedef boost::intrusive:: list<LoopCallback, boost::intrusive::constant_time_size<false> > folly::EventBase::LoopCallback::List private
Definition at line 167 of file EventBase.h.
Constructor & Destructor Documentation
virtual folly::EventBase::LoopCallback::~LoopCallback () virtual default
Member Function Documentation
void folly::EventBase::LoopCallback::cancelLoopCallback () inline
Definition at line 155 of file EventBase.h.
Referenced by proxygen::HTTPSession::cancelLoopCallbacks(), wangle::OutputBufferingHandler::cleanUp(), wangle::OutputBufferingHandler::close(), folly::AsyncSocket::closeNow(), proxygen::HTTPSession::immediateShutdown(), folly::EventBase::runBeforeLoop(), folly::EventBase::runInLoop(), folly::VirtualEventBase::runOnDestruction(), folly::EventBase::runOnDestruction(), folly::AsyncSocket::setReadCB(), proxygen::HTTPSession::shutdownTransportWithReset(), folly::AsyncSocket::startFail(), TEST(), and folly::fibers::EventBaseLoopController::~EventBaseLoopController().
{
       context_.reset();
       unlink();
     }
bool folly::EventBase::LoopCallback::isLoopCallbackScheduled () const inline
Definition at line 160 of file EventBase.h.
Referenced by proxygen::HTTPSession::cancelLoopCallbacks(), proxygen::HTTPSession::checkForShutdown(), wangle::OutputBufferingHandler::cleanUp(), wangle::OutputBufferingHandler::close(), folly::AsyncSocket::closeNow(), proxygen::HTTPSession::immediateShutdown(), proxygen::HTTPSession::notifyEgressBodyBuffered(), proxygen::HTTPSession::rescheduleLoopCallbacks(), proxygen::HTTPSession::resumeReadsImpl(), proxygen::HTTPSession::scheduleWrite(), folly::AsyncSocket::setReadCB(), proxygen::HTTPSession::shutdownTransportWithReset(), folly::AsyncSocket::startFail(), and wangle::OutputBufferingHandler::write().
{
       return is_linked();
     }
virtual void folly::EventBase::LoopCallback::runLoopCallback () pure virtual noexcept
Implemented in TerminateTestCallback, CountedLoopCallback, folly::AsyncSocket::ImmediateReadCB, proxygen::HTTPSession::ShutdownTransportCallback, proxygen::HTTPSession, proxygen::compress::QMINScheme, wangle::ConnectionManager::DrainHelper, folly::EventBase::StackFunctionLoopCallback, folly::EventBase::FunctionLoopCallback, proxygen::compress::CompressionScheme, wangle::OutputBufferingHandler, folly::fibers::EventBaseLoopController::ControllerCallback, folly::MemoryIdlerTimeout, and CountedLoopCallback.
Referenced by folly::EventBase::runLoopCallbacks(), and folly::EventBase::~EventBase().
Friends And Related Function Documentation
friend class EventBase friend
Definition at line 170 of file EventBase.h.
friend class VirtualEventBase friend
Definition at line 171 of file EventBase.h.
Member Data Documentation
std::shared_ptr<RequestContext> folly::EventBase::LoopCallback::context_ private
Definition at line 172 of file EventBase.h.
Referenced by folly::EventBase::runInLoop(), and folly::EventBase::runLoopCallbacks().
The documentation for this class was generated from the following file:
proxygen/folly/folly/io/async/EventBase.h