proxygen: fizz::extensions::test::TokenBindingConstructorTest Class Reference
fizz::extensions::test::TokenBindingConstructorTest Class Reference
Public Member Functions
void SetUp () override
Buf getBuf (StringPiece hex)
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Public Attributes
EvpPkeyUniquePtr key_
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Protected Member Functions inherited from testing::Test
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Detailed Description
Definition at line 27 of file TokenBindingConstructorTest.cpp.
Member Function Documentation
Buf fizz::extensions::test::TokenBindingConstructorTest::getBuf (StringPiece hex) inline
Definition at line 44 of file TokenBindingConstructorTest.cpp.
References folly::IOBuf::copyBuffer(), folly::data(), and folly::unhexlify().
{
     auto data = unhexlify(hex);
     return folly::IOBuf::copyBuffer(data.data(), data.size());
   }
void fizz::extensions::test::TokenBindingConstructorTest::SetUp () inline override virtual
Reimplemented from testing::Test.
Definition at line 29 of file TokenBindingConstructorTest.cpp.
{
     OpenSSL_add_all_algorithms();
     EcKeyUniquePtr ecKey(EC_KEY_new_by_curve_name(NID_X9_62_prime256v1));
     key_ = EvpPkeyUniquePtr(EVP_PKEY_new());
     if (!ecKey || !key_) {
       throw std::runtime_error("Unable to initialize key");
     }
     if (EC_KEY_generate_key(ecKey.get()) != 1) {
       throw std::runtime_error("Unable to generate EC Key");
     }
     if (EVP_PKEY_set1_EC_KEY(key_.get(), ecKey.get()) != 1) {
       throw std::runtime_error("Unable to set EC key");
     }
   }
Member Data Documentation
EvpPkeyUniquePtr fizz::extensions::test::TokenBindingConstructorTest::key_
Definition at line 49 of file TokenBindingConstructorTest.cpp.
The documentation for this class was generated from the following file:
proxygen/fizz/fizz/extensions/tokenbinding/test/TokenBindingConstructorTest.cpp