proxygen: LoggerTest Class Reference
LoggerTest Class Reference
Protected Member Functions
void SetUp () override
Protected Member Functions inherited from testing::Test
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Static Protected Member Functions
static StringPiece pathBasename (StringPiece path)
Protected Attributes
LoggerDB db_ {LoggerDB::TESTING}
Logger logger_ {&db_, "test"}
std::shared_ptr< TestLogHandler > handler_
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Detailed Description
Definition at line 30 of file LoggerTest.cpp.
Member Function Documentation
static StringPiece LoggerTest::pathBasename (StringPiece path) inline static protected
Definition at line 40 of file LoggerTest.cpp.
References folly::Range< const char * >::npos, folly::Range< Iter >::rfind(), folly::Range< Iter >::str(), and folly::Range< Iter >::subpiece().
{
     auto idx = path.rfind('/');
     if (idx == StringPiece::npos) {
       return path.str();
     }
     return path.subpiece(idx + 1);
   }
void LoggerTest::SetUp () inline override protected virtual
Reimplemented from testing::Test.
Definition at line 32 of file LoggerTest.cpp.
References folly::DBG.
{
     auto* category = logger_.getCategory();
     handler_ = make_shared<TestLogHandler>();
     category->addHandler(handler_);
     category->setLevel(LogLevel::DBG, true);
   }
Member Data Documentation
LoggerDB LoggerTest::db_ {LoggerDB::TESTING} protected
Definition at line 48 of file LoggerTest.cpp.
std::shared_ptr<TestLogHandler> LoggerTest::handler_ protected
Definition at line 50 of file LoggerTest.cpp.
Logger LoggerTest::logger_ {&db_, "test"} protected
Definition at line 49 of file LoggerTest.cpp.
The documentation for this class was generated from the following file:
proxygen/folly/folly/logging/test/LoggerTest.cpp