proxygen: testing::internal::UnorderedElementsAreArrayMatcher< T > Class Template Reference
testing::internal::UnorderedElementsAreArrayMatcher< T > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
UnorderedElementsAreArrayMatcher ()
template<typename Iter >
UnorderedElementsAreArrayMatcher (Iter first, Iter last)
template<typename Container >
operator Matcher< Container > () const
UnorderedElementsAreArrayMatcher ()
template<typename Iter >
UnorderedElementsAreArrayMatcher (Iter first, Iter last)
template<typename Container >
operator Matcher< Container > () const
UnorderedElementsAreArrayMatcher ()
template<typename Iter >
UnorderedElementsAreArrayMatcher (Iter first, Iter last)
template<typename Container >
operator Matcher< Container > () const
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (UnorderedElementsAreArrayMatcher)
GTEST_DISALLOW_ASSIGN_ (UnorderedElementsAreArrayMatcher)
GTEST_DISALLOW_ASSIGN_ (UnorderedElementsAreArrayMatcher)
Private Attributes
::std::vector< T > matchers_
Detailed Description
template<typename T>
class testing::internal::UnorderedElementsAreArrayMatcher< T >
Definition at line 3502 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename T> testing::internal::UnorderedElementsAreArrayMatcher< T >::UnorderedElementsAreArrayMatcher () inline
Definition at line 3504 of file gmock-matchers.h.
 {}
template<typename T> template<typename Iter > testing::internal::UnorderedElementsAreArrayMatcher< T >::UnorderedElementsAreArrayMatcher (Iter first, Iter last) inline
Definition at line 3507 of file gmock-matchers.h.
       : matchers_(first, last) {}
template<typename T> testing::internal::UnorderedElementsAreArrayMatcher< T >::UnorderedElementsAreArrayMatcher () inline
Definition at line 3504 of file gmock-matchers.h.
 {}
template<typename T> template<typename Iter > testing::internal::UnorderedElementsAreArrayMatcher< T >::UnorderedElementsAreArrayMatcher (Iter first, Iter last) inline
Definition at line 3507 of file gmock-matchers.h.
       : matchers_(first, last) {}
template<typename T> testing::internal::UnorderedElementsAreArrayMatcher< T >::UnorderedElementsAreArrayMatcher () inline
Definition at line 3504 of file gmock-matchers.h.
 {}
template<typename T> template<typename Iter > testing::internal::UnorderedElementsAreArrayMatcher< T >::UnorderedElementsAreArrayMatcher (Iter first, Iter last) inline
Definition at line 3507 of file gmock-matchers.h.
       : matchers_(first, last) {}
Member Function Documentation
template<typename T> testing::internal::UnorderedElementsAreArrayMatcher< T >::GTEST_DISALLOW_ASSIGN_ (UnorderedElementsAreArrayMatcher< T >) private
template<typename T> testing::internal::UnorderedElementsAreArrayMatcher< T >::GTEST_DISALLOW_ASSIGN_ (UnorderedElementsAreArrayMatcher< T >) private
template<typename T> testing::internal::UnorderedElementsAreArrayMatcher< T >::GTEST_DISALLOW_ASSIGN_ (UnorderedElementsAreArrayMatcher< T >) private
template<typename T> template<typename Container > testing::internal::UnorderedElementsAreArrayMatcher< T >::operator Matcher< Container > () const inline
Definition at line 3511 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(
         new UnorderedElementsAreMatcherImpl<Container>(matchers_.begin(),
                                                        matchers_.end()));
   }
template<typename T> template<typename Container > testing::internal::UnorderedElementsAreArrayMatcher< T >::operator Matcher< Container > () const inline
Definition at line 3511 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, and testing::MakeMatcher().
{
     return MakeMatcher(
         new UnorderedElementsAreMatcherImpl<Container>(matchers_.begin(),
                                                        matchers_.end()));
   }
template<typename T> template<typename Container > testing::internal::UnorderedElementsAreArrayMatcher< T >::operator Matcher< Container > () const inline
Definition at line 3511 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, and testing::MakeMatcher().
{
     return MakeMatcher(
         new UnorderedElementsAreMatcherImpl<Container>(matchers_.begin(),
                                                        matchers_.end()));
   }
Member Data Documentation
template<typename T> std::vector< T > testing::internal::UnorderedElementsAreArrayMatcher< T >::matchers_ private
Definition at line 3518 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h