proxygen: folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all > Class Template Reference
folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all > Class Template Reference
Public Member Functions
Executor (size_t threads, const Ops *ops)
~Executor ()
void closeInputProducer ()
void closeOutputConsumer ()
bool writeUnlessClosed (Input &&input)
bool writeUnlessFull (Input &&input)
bool readUnlessClosed (OutputDecayed &output)
bool readUnlessEmpty (OutputDecayed &output)
Private Member Functions
void work ()
Private Attributes
InQueue inQueue_
OutQueue outQueue_
Puller puller_
Pusher< all > pusher_
std::vector< std::thread > workers_
const Ops * ops_
Detailed Description
template<class Ops>
template<class Input, class Source, class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type>
template<bool all = false>
class folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >
Definition at line 230 of file Parallel-inl.h.
Constructor & Destructor Documentation
template<class Ops > template<class Input , class Source , class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type> template<bool all = false> folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >::Executor (size_t threads, const Ops * ops) inline
Definition at line 243 of file Parallel-inl.h.
References folly::gen::detail::ClosableMPMCQueue< T >::closeInputProducer(), folly::gen::detail::ClosableMPMCQueue< T >::closeOutputConsumer(), folly::gen::detail::ClosableMPMCQueue< T >::openConsumer(), folly::gen::detail::ClosableMPMCQueue< T >::openProducer(), SCOPE_EXIT, folly::pushmi::detail::t, and threads.
           : inQueue_(threads * 4),
             outQueue_(threads * 4),
             puller_(&inQueue_),
             pusher_(&outQueue_),
             ops_(ops) {
         inQueue_.openProducer();
         outQueue_.openConsumer();
         for (size_t t = 0; t < threads; ++t) {
           inQueue_.openConsumer();
           outQueue_.openProducer();
           workers_.emplace_back([this] {
             SCOPE_EXIT {
               inQueue_.closeOutputConsumer();
               outQueue_.closeInputProducer();
             };
             this->work();
           });
         }
       }
template<class Ops > template<class Input , class Source , class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type> template<bool all = false> folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >::~Executor () inline
Definition at line 264 of file Parallel-inl.h.
References folly::gen::detail::ClosableMPMCQueue< T >::closeInputProducer(), folly::gen::detail::ClosableMPMCQueue< T >::closeOutputConsumer(), folly::gen::detail::ClosableMPMCQueue< T >::consumers(), and folly::gen::detail::ClosableMPMCQueue< T >::producers().
                   {
         if (inQueue_.producers()) {
           inQueue_.closeInputProducer();
         }
         if (outQueue_.consumers()) {
           outQueue_.closeOutputConsumer();
         }
         while (!workers_.empty()) {
           workers_.back().join();
           workers_.pop_back();
         }
         CHECK(!inQueue_.consumers());
         CHECK(!outQueue_.producers());
       }
Member Function Documentation
template<class Ops > template<class Input , class Source , class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type> template<bool all = false> void folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >::closeInputProducer () inline
Definition at line 279 of file Parallel-inl.h.
References folly::gen::detail::ClosableMPMCQueue< T >::closeInputProducer().
Referenced by folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::apply(), and folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::foreach().
{
         inQueue_.closeInputProducer();
       }
template<class Ops > template<class Input , class Source , class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type> template<bool all = false> void folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >::closeOutputConsumer () inline
Definition at line 283 of file Parallel-inl.h.
References folly::gen::detail::ClosableMPMCQueue< T >::closeOutputConsumer().
Referenced by folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::apply(), and folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::foreach().
{
         outQueue_.closeOutputConsumer();
       }
template<class Ops > template<class Input , class Source , class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type> template<bool all = false> bool folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >::readUnlessClosed (OutputDecayed & output) inline
Definition at line 295 of file Parallel-inl.h.
References folly::gen::detail::ClosableMPMCQueue< T >::readUnlessClosed().
Referenced by folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::apply(), and folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::foreach().
{
         return outQueue_.readUnlessClosed(output);
       }
template<class Ops > template<class Input , class Source , class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type> template<bool all = false> bool folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >::readUnlessEmpty (OutputDecayed & output) inline
Definition at line 299 of file Parallel-inl.h.
References folly::gen::detail::ClosableMPMCQueue< T >::readUnlessEmpty().
Referenced by folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::apply(), and folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::foreach().
{
         return outQueue_.readUnlessEmpty(output);
       }
template<class Ops > template<class Input , class Source , class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type> template<bool all = false> void folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >::work () inline private
Definition at line 238 of file Parallel-inl.h.
                   {
         puller_ | *ops_ | pusher_;
       }
template<class Ops > template<class Input , class Source , class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type> template<bool all = false> bool folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >::writeUnlessClosed (Input && input) inline
Definition at line 287 of file Parallel-inl.h.
References folly::gen::detail::ClosableMPMCQueue< T >::writeUnlessClosed().
Referenced by folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::apply(), and folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::foreach().
{
         return inQueue_.writeUnlessClosed(std::forward<Input>(input));
       }
template<class Ops > template<class Input , class Source , class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type> template<bool all = false> bool folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >::writeUnlessFull (Input && input) inline
Definition at line 291 of file Parallel-inl.h.
References folly::gen::detail::ClosableMPMCQueue< T >::writeUnlessFull().
Referenced by folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::apply(), and folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::foreach().
{
         return inQueue_.writeUnlessFull(std::forward<Input>(input));
       }
Member Data Documentation
template<class Ops > template<class Input , class Source , class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type> template<bool all = false> InQueue folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >::inQueue_ private
Definition at line 231 of file Parallel-inl.h.
template<class Ops > template<class Input , class Source , class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type> template<bool all = false> const Ops* folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >::ops_ private
Definition at line 236 of file Parallel-inl.h.
template<class Ops > template<class Input , class Source , class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type> template<bool all = false> OutQueue folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >::outQueue_ private
Definition at line 232 of file Parallel-inl.h.
template<class Ops > template<class Input , class Source , class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type> template<bool all = false> Puller folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >::puller_ private
Definition at line 233 of file Parallel-inl.h.
template<class Ops > template<class Input , class Source , class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type> template<bool all = false> Pusher<all> folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >::pusher_ private
Definition at line 234 of file Parallel-inl.h.
template<class Ops > template<class Input , class Source , class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type> template<bool all = false> std::vector<std::thread> folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >::workers_ private
Definition at line 235 of file Parallel-inl.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/gen/Parallel-inl.h