proxygen: gtest_test_utils.Subprocess Class Reference
gtest_test_utils.Subprocess Class Reference
Public Member Functions
def __init__ (self, command, working_dir=None, capture_stderr=True, env=None)
def __init__ (self, command, working_dir=None, capture_stderr=True, env=None)
def __init__ (self, command, working_dir=None, capture_stderr=True, env=None)
Public Attributes
output
terminated_by_signal
exited
signal
exit_code
Private Attributes
_return_code
Detailed Description
Definition at line 207 of file gtest_test_utils.py.
Constructor & Destructor Documentation
def gtest_test_utils.Subprocess.__init__ (self, command, working_dir = None, capture_stderr = True, env = None)
Changes into a specified directory, if provided, and executes a command.
Restores the old directory afterwards.
Args:
  command:        The command to run, in the form of sys.argv.
  working_dir:    The directory to change into.
  capture_stderr: Determines whether to capture stderr in the output member
              or to discard it.
  env:            Dictionary with environment to pass to the subprocess.
Returns:
  An object that represents outcome of the executed process. It has the
  following attributes:
terminated_by_signal   True iff the child process has been terminated
                       by a signal.
signal                 Sygnal that terminated the child process.
exited                 True iff the child process exited normally.
exit_code              The code with which the child process exited.
output                 Child process's stdout and stderr output
                       combined in a string.
Definition at line 208 of file gtest_test_utils.py.
Referenced by gtest_test_utils.Subprocess.__init__().
   def __init__(self, command, working_dir=None, capture_stderr=True, env=None):
     """Changes into a specified directory, if provided, and executes a command.
     Restores the old directory afterwards.
     Args:
       command:        The command to run, in the form of sys.argv.
       working_dir:    The directory to change into.
       capture_stderr: Determines whether to capture stderr in the output member
                       or to discard it.
       env:            Dictionary with environment to pass to the subprocess.
     Returns:
       An object that represents outcome of the executed process. It has the
       following attributes:
         terminated_by_signal   True iff the child process has been terminated
                                by a signal.
         signal                 Sygnal that terminated the child process.
         exited                 True iff the child process exited normally.
         exit_code              The code with which the child process exited.
         output                 Child process's stdout and stderr output
                                combined in a string.
     """
     # The subprocess module is the preferrable way of running programs
     # since it is available and behaves consistently on all platforms,
     # including Windows. But it is only available starting in python 2.4.
     # In earlier python versions, we revert to the popen2 module, which is
     # available in python 2.0 and later but doesn't provide required
     # functionality (Popen4) under Windows. This allows us to support Mac
     # OS X 10.4 Tiger, which has python 2.3 installed.
     if _SUBPROCESS_MODULE_AVAILABLE:
       if capture_stderr:
         stderr = subprocess.STDOUT
       else:
         stderr = subprocess.PIPE
       p = subprocess.Popen(command,
                            stdout=subprocess.PIPE, stderr=stderr,
                            cwd=working_dir, universal_newlines=True, env=env)
       # communicate returns a tuple with the file obect for the child's
       # output.
       self.output = p.communicate()[0]
       self._return_code = p.returncode
     else:
       old_dir = os.getcwd()
       def _ReplaceEnvDict(dest, src):
         # Changes made by os.environ.clear are not inheritable by child
         # processes until Python 2.6. To produce inheritable changes we have
         # to delete environment items with the del statement.
         for key in dest.keys():
           del dest[key]
         dest.update(src)
       # When 'env' is not None, backup the environment variables and replace
       # them with the passed 'env'. When 'env' is None, we simply use the
       # current 'os.environ' for compatibility with the subprocess.Popen
       # semantics used above.
       if env is not None:
         old_environ = os.environ.copy()
         _ReplaceEnvDict(os.environ, env)
       try:
         if working_dir is not None:
           os.chdir(working_dir)
         if capture_stderr:
           p = popen2.Popen4(command)
         else:
           p = popen2.Popen3(command)
         p.tochild.close()
         self.output = p.fromchild.read()
         ret_code = p.wait()
       finally:
         os.chdir(old_dir)
         # Restore the old environment variables
         # if they were replaced.
         if env is not None:
           _ReplaceEnvDict(os.environ, old_environ)
       # Converts ret_code to match the semantics of
       # subprocess.Popen.returncode.
       if os.WIFSIGNALED(ret_code):
         self._return_code = -os.WTERMSIG(ret_code)
       else:  # os.WIFEXITED(ret_code) should return True here.
         self._return_code = os.WEXITSTATUS(ret_code)
     if self._return_code < 0:
       self.terminated_by_signal = True
       self.exited = False
       self.signal = -self._return_code
     else:
       self.terminated_by_signal = False
       self.exited = True
       self.exit_code = self._return_code
def gtest_test_utils.Subprocess.__init__ (self, command, working_dir = None, capture_stderr = True, env = None)
Changes into a specified directory, if provided, and executes a command.
Restores the old directory afterwards.
Args:
  command:        The command to run, in the form of sys.argv.
  working_dir:    The directory to change into.
  capture_stderr: Determines whether to capture stderr in the output member
              or to discard it.
  env:            Dictionary with environment to pass to the subprocess.
Returns:
  An object that represents outcome of the executed process. It has the
  following attributes:
terminated_by_signal   True iff the child process has been terminated
                       by a signal.
signal                 Sygnal that terminated the child process.
exited                 True iff the child process exited normally.
exit_code              The code with which the child process exited.
output                 Child process's stdout and stderr output
                       combined in a string.
Definition at line 208 of file gtest_test_utils.py.
References gtest_test_utils.Subprocess.__init__(), gtest_test_utils._ParseAndStripGTestFlags(), gtest_test_utils.Subprocess._return_code, gtest_test_utils.Subprocess.exit_code, gtest_test_utils.Subprocess.exited, gtest_test_utils.Main(), gtest_test_utils.Subprocess.output, gtest_test_utils.Subprocess.signal, and gtest_test_utils.Subprocess.terminated_by_signal.
   def __init__(self, command, working_dir=None, capture_stderr=True, env=None):
     """Changes into a specified directory, if provided, and executes a command.
     Restores the old directory afterwards.
     Args:
       command:        The command to run, in the form of sys.argv.
       working_dir:    The directory to change into.
       capture_stderr: Determines whether to capture stderr in the output member
                       or to discard it.
       env:            Dictionary with environment to pass to the subprocess.
     Returns:
       An object that represents outcome of the executed process. It has the
       following attributes:
         terminated_by_signal   True iff the child process has been terminated
                                by a signal.
         signal                 Sygnal that terminated the child process.
         exited                 True iff the child process exited normally.
         exit_code              The code with which the child process exited.
         output                 Child process's stdout and stderr output
                                combined in a string.
     """
     # The subprocess module is the preferrable way of running programs
     # since it is available and behaves consistently on all platforms,
     # including Windows. But it is only available starting in python 2.4.
     # In earlier python versions, we revert to the popen2 module, which is
     # available in python 2.0 and later but doesn't provide required
     # functionality (Popen4) under Windows. This allows us to support Mac
     # OS X 10.4 Tiger, which has python 2.3 installed.
     if _SUBPROCESS_MODULE_AVAILABLE:
       if capture_stderr:
         stderr = subprocess.STDOUT
       else:
         stderr = subprocess.PIPE
       p = subprocess.Popen(command,
                            stdout=subprocess.PIPE, stderr=stderr,
                            cwd=working_dir, universal_newlines=True, env=env)
       # communicate returns a tuple with the file obect for the child's
       # output.
       self.output = p.communicate()[0]
       self._return_code = p.returncode
     else:
       old_dir = os.getcwd()
       def _ReplaceEnvDict(dest, src):
         # Changes made by os.environ.clear are not inheritable by child
         # processes until Python 2.6. To produce inheritable changes we have
         # to delete environment items with the del statement.
         for key in dest.keys():
           del dest[key]
         dest.update(src)
       # When 'env' is not None, backup the environment variables and replace
       # them with the passed 'env'. When 'env' is None, we simply use the
       # current 'os.environ' for compatibility with the subprocess.Popen
       # semantics used above.
       if env is not None:
         old_environ = os.environ.copy()
         _ReplaceEnvDict(os.environ, env)
       try:
         if working_dir is not None:
           os.chdir(working_dir)
         if capture_stderr:
           p = popen2.Popen4(command)
         else:
           p = popen2.Popen3(command)
         p.tochild.close()
         self.output = p.fromchild.read()
         ret_code = p.wait()
       finally:
         os.chdir(old_dir)
         # Restore the old environment variables
         # if they were replaced.
         if env is not None:
           _ReplaceEnvDict(os.environ, old_environ)
       # Converts ret_code to match the semantics of
       # subprocess.Popen.returncode.
       if os.WIFSIGNALED(ret_code):
         self._return_code = -os.WTERMSIG(ret_code)
       else:  # os.WIFEXITED(ret_code) should return True here.
         self._return_code = os.WEXITSTATUS(ret_code)
     if self._return_code < 0:
       self.terminated_by_signal = True
       self.exited = False
       self.signal = -self._return_code
     else:
       self.terminated_by_signal = False
       self.exited = True
       self.exit_code = self._return_code
def gtest_test_utils.Subprocess.__init__ (self, command, working_dir = None, capture_stderr = True, env = None)
Changes into a specified directory, if provided, and executes a command.
Restores the old directory afterwards.
Args:
  command:        The command to run, in the form of sys.argv.
  working_dir:    The directory to change into.
  capture_stderr: Determines whether to capture stderr in the output member
              or to discard it.
  env:            Dictionary with environment to pass to the subprocess.
Returns:
  An object that represents outcome of the executed process. It has the
  following attributes:
terminated_by_signal   True iff the child process has been terminated
                       by a signal.
signal                 Sygnal that terminated the child process.
exited                 True iff the child process exited normally.
exit_code              The code with which the child process exited.
output                 Child process's stdout and stderr output
                       combined in a string.
Definition at line 208 of file gtest_test_utils.py.
References gtest_test_utils.Subprocess.__init__(), gtest_test_utils._ParseAndStripGTestFlags(), gtest_test_utils.Subprocess._return_code, gtest_test_utils.Subprocess.exit_code, gtest_test_utils.Subprocess.exited, gtest_test_utils.Main(), gtest_test_utils.Subprocess.output, gtest_test_utils.Subprocess.signal, and gtest_test_utils.Subprocess.terminated_by_signal.
   def __init__(self, command, working_dir=None, capture_stderr=True, env=None):
     """Changes into a specified directory, if provided, and executes a command.
     Restores the old directory afterwards.
     Args:
       command:        The command to run, in the form of sys.argv.
       working_dir:    The directory to change into.
       capture_stderr: Determines whether to capture stderr in the output member
                       or to discard it.
       env:            Dictionary with environment to pass to the subprocess.
     Returns:
       An object that represents outcome of the executed process. It has the
       following attributes:
         terminated_by_signal   True iff the child process has been terminated
                                by a signal.
         signal                 Sygnal that terminated the child process.
         exited                 True iff the child process exited normally.
         exit_code              The code with which the child process exited.
         output                 Child process's stdout and stderr output
                                combined in a string.
     """
     # The subprocess module is the preferrable way of running programs
     # since it is available and behaves consistently on all platforms,
     # including Windows. But it is only available starting in python 2.4.
     # In earlier python versions, we revert to the popen2 module, which is
     # available in python 2.0 and later but doesn't provide required
     # functionality (Popen4) under Windows. This allows us to support Mac
     # OS X 10.4 Tiger, which has python 2.3 installed.
     if _SUBPROCESS_MODULE_AVAILABLE:
       if capture_stderr:
         stderr = subprocess.STDOUT
       else:
         stderr = subprocess.PIPE
       p = subprocess.Popen(command,
                            stdout=subprocess.PIPE, stderr=stderr,
                            cwd=working_dir, universal_newlines=True, env=env)
       # communicate returns a tuple with the file obect for the child's
       # output.
       self.output = p.communicate()[0]
       self._return_code = p.returncode
     else:
       old_dir = os.getcwd()
       def _ReplaceEnvDict(dest, src):
         # Changes made by os.environ.clear are not inheritable by child
         # processes until Python 2.6. To produce inheritable changes we have
         # to delete environment items with the del statement.
         for key in dest.keys():
           del dest[key]
         dest.update(src)
       # When 'env' is not None, backup the environment variables and replace
       # them with the passed 'env'. When 'env' is None, we simply use the
       # current 'os.environ' for compatibility with the subprocess.Popen
       # semantics used above.
       if env is not None:
         old_environ = os.environ.copy()
         _ReplaceEnvDict(os.environ, env)
       try:
         if working_dir is not None:
           os.chdir(working_dir)
         if capture_stderr:
           p = popen2.Popen4(command)
         else:
           p = popen2.Popen3(command)
         p.tochild.close()
         self.output = p.fromchild.read()
         ret_code = p.wait()
       finally:
         os.chdir(old_dir)
         # Restore the old environment variables
         # if they were replaced.
         if env is not None:
           _ReplaceEnvDict(os.environ, old_environ)
       # Converts ret_code to match the semantics of
       # subprocess.Popen.returncode.
       if os.WIFSIGNALED(ret_code):
         self._return_code = -os.WTERMSIG(ret_code)
       else:  # os.WIFEXITED(ret_code) should return True here.
         self._return_code = os.WEXITSTATUS(ret_code)
     if self._return_code < 0:
       self.terminated_by_signal = True
       self.exited = False
       self.signal = -self._return_code
     else:
       self.terminated_by_signal = False
       self.exited = True
       self.exit_code = self._return_code
Member Data Documentation
gtest_test_utils.Subprocess._return_code private
Definition at line 251 of file gtest_test_utils.py.
Referenced by gtest_test_utils.Subprocess.__init__().
gtest_test_utils.Subprocess.exit_code
Definition at line 303 of file gtest_test_utils.py.
Referenced by gtest_test_utils.Subprocess.__init__().
gtest_test_utils.Subprocess.exited
Definition at line 298 of file gtest_test_utils.py.
Referenced by gtest_test_utils.Subprocess.__init__().
gtest_test_utils.Subprocess.output
Definition at line 250 of file gtest_test_utils.py.
Referenced by gtest_test_utils.Subprocess.__init__().
gtest_test_utils.Subprocess.signal
Definition at line 299 of file gtest_test_utils.py.
Referenced by gtest_test_utils.Subprocess.__init__().
gtest_test_utils.Subprocess.terminated_by_signal
Definition at line 297 of file gtest_test_utils.py.
Referenced by gtest_test_utils.Subprocess.__init__().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest_test_utils.py