proxygen: folly::gen::detail::GroupByAdjacent< Selector >::Generator< Value, Source, ValueDecayed, Key, KeyDecayed > Class Template Reference
folly::gen::detail::GroupByAdjacent< Selector >::Generator< Value, Source, ValueDecayed, Key, KeyDecayed > Class Template Reference
#include <Base-inl.h>
Public Types
typedef Group< KeyDecayed, ValueDecayed > GroupType
Public Types inherited from folly::gen::GenImpl< Group< KeyDecayed, ValueDecayed > &&, Generator< Value, Source, ValueDecayed, Key, KeyDecayed > >
typedef Group< KeyDecayed, ValueDecayed > && ValueType
typedef std::decay< Group< KeyDecayed, ValueDecayed > && >::type StorageType
Public Member Functions
Generator (Source source, Selector selector)
template<class Handler >
bool apply (Handler &&handler) const
Public Member Functions inherited from folly::gen::GenImpl< Group< KeyDecayed, ValueDecayed > &&, Generator< Value, Source, ValueDecayed, Key, KeyDecayed > >
bool apply (Handler &&handler) const
void foreach (Body &&body) const
Public Member Functions inherited from folly::gen::FBounded< Self >
const Self & self () const
Self & self ()
Static Public Attributes
static constexpr bool infinite = Source::infinite
Static Public Attributes inherited from folly::gen::GenImpl< Group< KeyDecayed, ValueDecayed > &&, Generator< Value, Source, ValueDecayed, Key, KeyDecayed > >
static constexpr bool infinite
Private Attributes
Source source_
Selector selector_
Additional Inherited Members
Protected Member Functions inherited from folly::gen::GenImpl< Group< KeyDecayed, ValueDecayed > &&, Generator< Value, Source, ValueDecayed, Key, KeyDecayed > >
GenImpl ()=default
GenImpl (GenImpl &&)=default
GenImpl (const GenImpl &)=default
GenImpl & operator= (GenImpl &&)=default
GenImpl & operator= (const GenImpl &)=default
Detailed Description
template<class Selector>
template<class Value, class Source, class ValueDecayed = typename std::decay<Value>::type, class Key = invoke_result_t<Selector, Value>, class KeyDecayed = typename std::decay<Key>::type>
class folly::gen::detail::GroupByAdjacent< Selector >::Generator< Value, Source, ValueDecayed, Key, KeyDecayed >
Definition at line 1236 of file Base-inl.h.
Member Typedef Documentation
template<class Selector > template<class Value , class Source , class ValueDecayed = typename std::decay<Value>::type, class Key = invoke_result_t<Selector, Value>, class KeyDecayed = typename std::decay<Key>::type> typedef Group<KeyDecayed, ValueDecayed> folly::gen::detail::GroupByAdjacent< Selector >::Generator< Value, Source, ValueDecayed, Key, KeyDecayed >::GroupType
Definition at line 1247 of file Base-inl.h.
Constructor & Destructor Documentation
template<class Selector > template<class Value , class Source , class ValueDecayed = typename std::decay<Value>::type, class Key = invoke_result_t<Selector, Value>, class KeyDecayed = typename std::decay<Key>::type> folly::gen::detail::GroupByAdjacent< Selector >::Generator< Value, Source, ValueDecayed, Key, KeyDecayed >::Generator (Source source, Selector selector) inline
Definition at line 1244 of file Base-inl.h.
         : source_(std::move(source)), selector_(std::move(selector)) {}
Member Function Documentation
template<class Selector > template<class Value , class Source , class ValueDecayed = typename std::decay<Value>::type, class Key = invoke_result_t<Selector, Value>, class KeyDecayed = typename std::decay<Key>::type> template<class Handler > bool folly::gen::detail::GroupByAdjacent< Selector >::Generator< Value, Source, ValueDecayed, Key, KeyDecayed >::apply (Handler && handler) const inline
Definition at line 1250 of file Base-inl.h.
References folly::Optional< Value >::emplace(), group, handler(), folly::Optional< Value >::hasValue(), folly::gen::move, folly::none, value, folly::Optional< Value >::value(), testing::Value(), and values().
{
       Optional<KeyDecayed> key = none;
       typename GroupType::VectorType values;
       bool result = source_.apply([&](Value value) mutable {
         KeyDecayed newKey = selector_(value);
         // start the first group
         if (!key.hasValue()) {
           key.emplace(newKey);
         }
         if (key == newKey) {
           // grow the current group
           values.push_back(value);
         } else {
           // flush the current group
           GroupType group(key.value(), std::move(values));
           if (!handler(std::move(group))) {
             return false;
           }
           // start a new group
           key.emplace(newKey);
           values.clear();
           values.push_back(value);
         }
         return true;
       });
       if (!result) {
         return false;
       }
       if (!key.hasValue()) {
         return true;
       }
       // flush the final group
       GroupType group(key.value(), std::move(values));
       return handler(std::move(group));
     }
Member Data Documentation
template<class Selector > template<class Value , class Source , class ValueDecayed = typename std::decay<Value>::type, class Key = invoke_result_t<Selector, Value>, class KeyDecayed = typename std::decay<Key>::type> constexpr bool folly::gen::detail::GroupByAdjacent< Selector >::Generator< Value, Source, ValueDecayed, Key, KeyDecayed >::infinite = Source::infinite static
Definition at line 1293 of file Base-inl.h.
template<class Selector > template<class Value , class Source , class ValueDecayed = typename std::decay<Value>::type, class Key = invoke_result_t<Selector, Value>, class KeyDecayed = typename std::decay<Key>::type> Selector folly::gen::detail::GroupByAdjacent< Selector >::Generator< Value, Source, ValueDecayed, Key, KeyDecayed >::selector_ private
Definition at line 1241 of file Base-inl.h.
template<class Selector > template<class Value , class Source , class ValueDecayed = typename std::decay<Value>::type, class Key = invoke_result_t<Selector, Value>, class KeyDecayed = typename std::decay<Key>::type> Source folly::gen::detail::GroupByAdjacent< Selector >::Generator< Value, Source, ValueDecayed, Key, KeyDecayed >::source_ private
Definition at line 1240 of file Base-inl.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/gen/Base-inl.h