proxygen: testing::gtest_printers_test::AllowsGenericStreamingAndImplicitConversionTemplate< T > Class Template Reference
testing::gtest_printers_test::AllowsGenericStreamingAndImplicitConversionTemplate< T > Class Template Reference
Public Member Functions
operator bool () const
operator bool () const
operator bool () const
Detailed Description
template<typename T>
class testing::gtest_printers_test::AllowsGenericStreamingAndImplicitConversionTemplate< T >
Definition at line 768 of file gtest-printers_test.cc.
Member Function Documentation
template<typename T> testing::gtest_printers_test::AllowsGenericStreamingAndImplicitConversionTemplate< T >::operator bool () const inline
Definition at line 770 of file gtest-printers_test.cc.
 { return false; }
template<typename T> testing::gtest_printers_test::AllowsGenericStreamingAndImplicitConversionTemplate< T >::operator bool () const inline
Definition at line 770 of file gtest-printers_test.cc.
References a, ASSERT_EQ, ASSERT_NE, b, folly::empty(), EXPECT_EQ, EXPECT_TRUE, i, std::tr1::make_tuple(), operator<<(), testing::Pair(), testing::gtest_printers_test::Print(), testing::gtest_printers_test::PrintPointer(), strings, testing::gtest_printers_test::TEST(), v, and x.
 { return false; }
template<typename T> testing::gtest_printers_test::AllowsGenericStreamingAndImplicitConversionTemplate< T >::operator bool () const inline
Definition at line 770 of file gtest-printers_test.cc.
References a, ASSERT_EQ, ASSERT_NE, b, folly::empty(), EXPECT_EQ, EXPECT_TRUE, i, std::tr1::make_tuple(), operator<<(), testing::Pair(), testing::gtest_printers_test::Print(), testing::gtest_printers_test::PrintPointer(), strings, testing::gtest_printers_test::TEST(), v, and x.
 { return false; }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest-printers_test.cc