proxygen: testing::internal::scoped_ptr< T > Class Template Reference
testing::internal::scoped_ptr< T > Class Template Reference
#include <gtest-port.h>
Public Types
typedef T element_type
typedef T element_type
typedef T element_type
Public Member Functions
scoped_ptr (T *p=NULL)
~scoped_ptr ()
T & operator* () const
T * operator-> () const
T * get () const
T * release ()
void reset (T *p=NULL)
scoped_ptr (T *p=NULL)
~scoped_ptr ()
T & operator* () const
T * operator-> () const
T * get () const
T * release ()
void reset (T *p=NULL)
scoped_ptr (T *p=NULL)
~scoped_ptr ()
T & operator* () const
T * operator-> () const
T * get () const
T * release ()
void reset (T *p=NULL)
Private Member Functions
scoped_ptr (scoped_ptr const &)
void operator= (scoped_ptr const &)
scoped_ptr (scoped_ptr const &)
void operator= (scoped_ptr const &)
scoped_ptr (scoped_ptr const &)
void operator= (scoped_ptr const &)
Private Attributes
T * ptr_
Friends
void swap (scoped_ptr &a, scoped_ptr &b)
void swap (scoped_ptr &a, scoped_ptr &b)
void swap (scoped_ptr &a, scoped_ptr &b)
Detailed Description
template<typename T>
class testing::internal::scoped_ptr< T >
Definition at line 1115 of file gtest-port.h.
Member Typedef Documentation
template<typename T> typedef T testing::internal::scoped_ptr< T >::element_type
Definition at line 1117 of file gtest-port.h.
template<typename T> typedef T testing::internal::scoped_ptr< T >::element_type
Definition at line 1117 of file gtest-port.h.
template<typename T> typedef T testing::internal::scoped_ptr< T >::element_type
Definition at line 1117 of file gtest-port.h.
Constructor & Destructor Documentation
template<typename T> testing::internal::scoped_ptr< T >::scoped_ptr (T * p = NULL) inline explicit
Definition at line 1119 of file gtest-port.h.
 : ptr_(p) {}
template<typename T> testing::internal::scoped_ptr< T >::~scoped_ptr () inline
Definition at line 1120 of file gtest-port.h.
 { reset(); }
template<typename T> testing::internal::scoped_ptr< T >::scoped_ptr (scoped_ptr< T > const &) private
template<typename T> testing::internal::scoped_ptr< T >::scoped_ptr (T * p = NULL) inline explicit
Definition at line 1119 of file gtest-port.h.
 : ptr_(p) {}
template<typename T> testing::internal::scoped_ptr< T >::~scoped_ptr () inline
Definition at line 1120 of file gtest-port.h.
 { reset(); }
template<typename T> testing::internal::scoped_ptr< T >::scoped_ptr (scoped_ptr< T > const &) private
template<typename T> testing::internal::scoped_ptr< T >::scoped_ptr (T * p = NULL) inline explicit
Definition at line 1119 of file gtest-port.h.
 : ptr_(p) {}
template<typename T> testing::internal::scoped_ptr< T >::~scoped_ptr () inline
Definition at line 1120 of file gtest-port.h.
 { reset(); }
template<typename T> testing::internal::scoped_ptr< T >::scoped_ptr (scoped_ptr< T > const &) private
Member Function Documentation
template<typename T> T* testing::internal::scoped_ptr< T >::get () const inline
Definition at line 1124 of file gtest-port.h.
Referenced by testing::Message::GetString(), testing::AssertionResult::operator!(), and testing::internal::ShouldRunTestCase().
 { return ptr_; }
template<typename T> T* testing::internal::scoped_ptr< T >::get () const inline
Definition at line 1124 of file gtest-port.h.
 { return ptr_; }
template<typename T> T* testing::internal::scoped_ptr< T >::get () const inline
Definition at line 1124 of file gtest-port.h.
 { return ptr_; }
template<typename T> T& testing::internal::scoped_ptr< T >::operator* () const inline
Definition at line 1122 of file gtest-port.h.
 { return *ptr_; }
template<typename T> T& testing::internal::scoped_ptr< T >::operator* () const inline
Definition at line 1122 of file gtest-port.h.
 { return *ptr_; }
template<typename T> T& testing::internal::scoped_ptr< T >::operator* () const inline
Definition at line 1122 of file gtest-port.h.
 { return *ptr_; }
template<typename T> T* testing::internal::scoped_ptr< T >::operator-> () const inline
Definition at line 1123 of file gtest-port.h.
 { return ptr_; }
template<typename T> T* testing::internal::scoped_ptr< T >::operator-> () const inline
Definition at line 1123 of file gtest-port.h.
 { return ptr_; }
template<typename T> T* testing::internal::scoped_ptr< T >::operator-> () const inline
Definition at line 1123 of file gtest-port.h.
 { return ptr_; }
template<typename T> void testing::internal::scoped_ptr< T >::operator= (scoped_ptr< T > const &) private
template<typename T> void testing::internal::scoped_ptr< T >::operator= (scoped_ptr< T > const &) private
template<typename T> void testing::internal::scoped_ptr< T >::operator= (scoped_ptr< T > const &) private
template<typename T> T* testing::internal::scoped_ptr< T >::release () inline
Definition at line 1126 of file gtest-port.h.
                {
     T* const ptr = ptr_;
     ptr_ = NULL;
     return ptr;
   }
template<typename T> T* testing::internal::scoped_ptr< T >::release () inline
Definition at line 1126 of file gtest-port.h.
                {
     T* const ptr = ptr_;
     ptr_ = NULL;
     return ptr;
   }
template<typename T> T* testing::internal::scoped_ptr< T >::release () inline
Definition at line 1126 of file gtest-port.h.
                {
     T* const ptr = ptr_;
     ptr_ = NULL;
     return ptr;
   }
template<typename T> void testing::internal::scoped_ptr< T >::reset (T * p = NULL) inline
Definition at line 1132 of file gtest-port.h.
{
     if (p != ptr_) {
       if (IsTrue(sizeof(T) > 0)) {  // Makes sure T is a complete type.
         delete ptr_;
       }
       ptr_ = p;
     }
   }
template<typename T> void testing::internal::scoped_ptr< T >::reset (T * p = NULL) inline
Definition at line 1132 of file gtest-port.h.
Referenced by testing::internal::NoDefaultContructor::NoDefaultContructor(), and testing::internal::TEST().
{
     if (p != ptr_) {
       if (IsTrue(sizeof(T) > 0)) {  // Makes sure T is a complete type.
         delete ptr_;
       }
       ptr_ = p;
     }
   }
template<typename T> void testing::internal::scoped_ptr< T >::reset (T * p = NULL) inline
Definition at line 1132 of file gtest-port.h.
{
     if (p != ptr_) {
       if (IsTrue(sizeof(T) > 0)) {  // Makes sure T is a complete type.
         delete ptr_;
       }
       ptr_ = p;
     }
   }
Friends And Related Function Documentation
template<typename T> void swap (scoped_ptr< T > & a, scoped_ptr< T > & b) friend
Definition at line 1141 of file gtest-port.h.
{
     using std::swap;
     swap(a.ptr_, b.ptr_);
   }
template<typename T> void swap (scoped_ptr< T > & a, scoped_ptr< T > & b) friend
Definition at line 1141 of file gtest-port.h.
{
     using std::swap;
     swap(a.ptr_, b.ptr_);
   }
template<typename T> void swap (scoped_ptr< T > & a, scoped_ptr< T > & b) friend
Definition at line 1141 of file gtest-port.h.
{
     using std::swap;
     swap(a.ptr_, b.ptr_);
   }
Member Data Documentation
template<typename T> T * testing::internal::scoped_ptr< T >::ptr_ private
Definition at line 1147 of file gtest-port.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h