proxygen: fizz::server::FizzServer< ActionMoveVisitor, SM > Class Template Reference
fizz::server::FizzServer< ActionMoveVisitor, SM > Class Template Reference
#include <FizzServer.h>
Public Member Functions
void accept (folly::Executor *executor, std::shared_ptr< const FizzServerContext > context, std::shared_ptr< ServerExtensions > extensions=nullptr)
void newTransportData ()
Buf getEarlyEkm (folly::StringPiece label, const Buf &context, uint16_t length) const
Public Member Functions inherited from fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >
FizzBase (const typename StateMachine::StateType &state, folly::IOBufQueue &transportReadBuf, ActionMoveVisitor &visitor, folly::DelayedDestructionBase *owner)
void writeNewSessionTicket (WriteNewSessionTicket writeNewSessionTicket)
void appWrite (AppWrite appWrite)
void earlyAppWrite (EarlyAppWrite appWrite)
void appClose ()
void waitForData ()
void newTransportData ()
void moveToErrorState (const folly::AsyncSocketException &ex)
bool inErrorState () const
bool actionProcessing () const
Buf getEkm (folly::StringPiece label, const Buf &context, uint16_t length) const
Private Member Functions
void startActions (AsyncActions actions)
Private Attributes
bool checkV2Hello_ {false}
Friends
class FizzBase< FizzServer< ActionMoveVisitor, SM >, ActionMoveVisitor, SM >
Additional Inherited Members
Protected Member Functions inherited from fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >
void processActions (typename StateMachine::CompletedActions actions)
void addProcessingActions (typename StateMachine::ProcessingActions actions)
Protected Attributes inherited from fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >
StateMachine machine_
const StateMachine::StateType & state_
folly::IOBufQueue & transportReadBuf_
Detailed Description
template<typename ActionMoveVisitor, typename SM = ServerStateMachine>
class fizz::server::FizzServer< ActionMoveVisitor, SM >
Definition at line 21 of file FizzServer.h.
Member Function Documentation
template<typename ActionMoveVisitor , typename SM > void fizz::server::FizzServer< ActionMoveVisitor, SM >::accept (folly::Executor * executor, std::shared_ptr< const FizzServerContext > context, std::shared_ptr< ServerExtensions > extensions = nullptr)
Definition at line 13 of file FizzServer-inl.h.
References folly::gen::move.
{
   checkV2Hello_ = context->getVersionFallbackEnabled();
   this->addProcessingActions(this->machine_.processAccept(
       this->state_, executor, std::move(context), std::move(extensions)));
 }
template<typename ActionMoveVisitor , typename SM > Buf fizz::server::FizzServer< ActionMoveVisitor, SM >::getEarlyEkm (folly::StringPiece label, const Buf & context, uint16_t length) const
Returns an exported key material derived from the early secret of the TLS connection. Throws if the early secret is not available.
Definition at line 46 of file FizzServer-inl.h.
References fizz::Exporter::getEkm(), and fizz::test::label.
{
   if (!this->state_.earlyExporterMasterSecret()) {
     throw std::runtime_error("early ekm not available");
   }
   return Exporter::getEkm(
       *this->state_.cipher(),
       (*this->state_.earlyExporterMasterSecret())->coalesce(),
       label,
       context ? context->clone() : nullptr,
       length);
 }
template<typename ActionMoveVisitor , typename SM > void fizz::server::FizzServer< ActionMoveVisitor, SM >::newTransportData ()
Definition at line 23 of file FizzServer-inl.h.
References fizz::server::detail::actions(), fizz::server::AttemptVersionFallback::clientHello, fizz::server::Error, fizz::server::looksLikeV2ClientHello(), folly::gen::move, and fizz::server::State::state().
{
   // If the first data we receive looks like an SSLv2 Client Hello we trigger
   // fallback immediately. This uses the same check as OpenSSL, and OpenSSL
   // does not allow extensions in an SSLv2 Client Hello, so this should not
   // add additional downgrade concerns.
   if (checkV2Hello_) {
     if (!this->actionProcessing() &&
         looksLikeV2ClientHello(this->transportReadBuf_)) {
       VLOG(3) << "Attempting fallback due to V2 ClientHello";
       AttemptVersionFallback fallback;
       fallback.clientHello = this->transportReadBuf_.move();
       return this->addProcessingActions(detail::actions(
           [](State& newState) { newState.state() = StateEnum::Error; },
           std::move(fallback)));
     }
     checkV2Hello_ = false;
   }
   FizzBase<FizzServer<ActionMoveVisitor, SM>, ActionMoveVisitor, SM>::
       newTransportData();
 }
template<typename ActionMoveVisitor , typename SM > void fizz::server::FizzServer< ActionMoveVisitor, SM >::startActions (AsyncActions actions) private
Definition at line 62 of file FizzServer-inl.h.
References folly::gen::move, fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::processActions(), and folly::variant_match().
{
   folly::variant_match(
       actions,
       [this](folly::Future<Actions>& futureActions) {
         std::move(futureActions)
             .then(
                 &FizzServer::processActions,
                 static_cast<FizzBase<
                     FizzServer<ActionMoveVisitor, SM>,
                     ActionMoveVisitor,
                     SM>*>(this));
       },
       [this](Actions& immediateActions) {
         this->processActions(std::move(immediateActions));
       });
 }
Friends And Related Function Documentation
template<typename ActionMoveVisitor, typename SM = ServerStateMachine> friend class FizzBase< FizzServer< ActionMoveVisitor, SM >,ActionMoveVisitor,SM > friend
Definition at line 47 of file FizzServer.h.
Member Data Documentation
template<typename ActionMoveVisitor, typename SM = ServerStateMachine> bool fizz::server::FizzServer< ActionMoveVisitor, SM >::checkV2Hello_ {false} private
Definition at line 51 of file FizzServer.h.
The documentation for this class was generated from the following files:
proxygen/fizz/fizz/server/FizzServer.h
proxygen/fizz/fizz/server/FizzServer-inl.h