proxygen: fizz::OpenSSLSignature< T > Class Template Reference
fizz::OpenSSLSignature< T > Class Template Reference
#include <Signature.h>
Public Member Functions
void setKey (folly::ssl::EvpPkeyUniquePtr pkey)
template<SignatureScheme Scheme>
std::unique_ptr< folly::IOBuf > sign (folly::ByteRange data) const
template<SignatureScheme Scheme>
void verify (folly::ByteRange data, folly::ByteRange signature) const
template<>
void setKey (folly::ssl::EvpPkeyUniquePtr pkey)
template<>
void setKey (folly::ssl::EvpPkeyUniquePtr pkey)
template<>
void setKey (folly::ssl::EvpPkeyUniquePtr pkey)
template<>
void setKey (folly::ssl::EvpPkeyUniquePtr pkey)
Private Attributes
folly::ssl::EvpPkeyUniquePtr pkey_
Detailed Description
template<KeyType T>
class fizz::OpenSSLSignature< T >
Signature implementation using OpenSSL.
Definition at line 23 of file Signature.h.
Member Function Documentation
template<KeyType T> void fizz::OpenSSLSignature< T >::setKey (folly::ssl::EvpPkeyUniquePtr pkey)
Referenced by fizz::test::TEST_F(), and fizz::testing::TEST_P().
template<> void fizz::OpenSSLSignature< KeyType::P256 >::setKey (folly::ssl::EvpPkeyUniquePtr pkey) inline
Definition at line 102 of file Signature-inl.h.
References folly::gen::move, and fizz::detail::validateECKey().
{
   detail::validateECKey(pkey, NID_X9_62_prime256v1);
   pkey_ = std::move(pkey);
 }
template<> void fizz::OpenSSLSignature< KeyType::P384 >::setKey (folly::ssl::EvpPkeyUniquePtr pkey) inline
Definition at line 109 of file Signature-inl.h.
References folly::gen::move, and fizz::detail::validateECKey().
{
   detail::validateECKey(pkey, NID_secp384r1);
   pkey_ = std::move(pkey);
 }
template<> void fizz::OpenSSLSignature< KeyType::P521 >::setKey (folly::ssl::EvpPkeyUniquePtr pkey) inline
Definition at line 116 of file Signature-inl.h.
References folly::gen::move, and fizz::detail::validateECKey().
{
   detail::validateECKey(pkey, NID_secp521r1);
   pkey_ = std::move(pkey);
 }
template<> void fizz::OpenSSLSignature< KeyType::RSA >::setKey (folly::ssl::EvpPkeyUniquePtr pkey) inline
Definition at line 123 of file Signature-inl.h.
References folly::gen::move.
{
   if (EVP_PKEY_id(pkey.get()) != EVP_PKEY_RSA) {
     throw std::runtime_error("key not rsa");
   }
   pkey_ = std::move(pkey);
 }
template<KeyType Type> template<SignatureScheme Scheme> std::unique_ptr< folly::IOBuf > fizz::OpenSSLSignature< Type >::sign (folly::ByteRange data) const inline
Returns a signature of data.
Only valid for SignatureSchemes that are compatible with KeyType.
setKey() must be called before with a private key.
Definition at line 69 of file Signature-inl.h.
References folly::assume_unreachable(), fizz::detail::ecSign(), fizz::P256, fizz::P384, fizz::P521, fizz::RSA, and fizz::detail::rsaPssSign().
Referenced by fizz::test::TEST_F(), and fizz::testing::TEST_P().
{
   static_assert(
       SigAlg<Scheme>::type == Type, "Called with mismatched type and scheme");
   switch (Type) {
     case KeyType::P256:
     case KeyType::P384:
     case KeyType::P521:
       return detail::ecSign(data, pkey_, SigAlg<Scheme>::HashNid);
     case KeyType::RSA:
       return detail::rsaPssSign(data, pkey_, SigAlg<Scheme>::HashNid);
   }
   folly::assume_unreachable();
 }
template<KeyType Type> template<SignatureScheme Scheme> void fizz::OpenSSLSignature< Type >::verify (folly::ByteRange data, folly::ByteRange signature) const inline
Verifies that signature is a valid signature over data. Throws if it's not.
Only valid for SignatureSchemes that are compatible with KeyType.
setKey() must be called before.
Definition at line 86 of file Signature-inl.h.
References folly::assume_unreachable(), fizz::detail::ecVerify(), fizz::P256, fizz::P384, fizz::P521, fizz::RSA, and fizz::detail::rsaPssVerify().
Referenced by fizz::test::TEST_F(), and fizz::testing::TEST_P().
{
   switch (Type) {
     case KeyType::P256:
     case KeyType::P384:
     case KeyType::P521:
       return detail::ecVerify(data, signature, pkey_, SigAlg<Scheme>::HashNid);
     case KeyType::RSA:
       return detail::rsaPssVerify(
           data, signature, pkey_, SigAlg<Scheme>::HashNid);
   }
   folly::assume_unreachable();
 }
Member Data Documentation
template<KeyType T> folly::ssl::EvpPkeyUniquePtr fizz::OpenSSLSignature< T >::pkey_ private
Definition at line 48 of file Signature.h.
The documentation for this class was generated from the following files:
proxygen/fizz/fizz/crypto/signature/Signature.h
proxygen/fizz/fizz/crypto/signature/Signature-inl.h