proxygen: folly::ThreadLocal< T, Tag, AccessMode > Class Template Reference
folly::ThreadLocal< T, Tag, AccessMode > Class Template Reference
#include <ThreadLocal.h>
Public Types
typedef ThreadLocalPtr< T, Tag, AccessMode >::Accessor Accessor
Public Member Functions
constexpr ThreadLocal ()
template<typename F , _t< std::enable_if< is_invocable_r< T *, F >::value, int >> = 0>
ThreadLocal (F &&constructor)
FOLLY_ALWAYS_INLINE FOLLY_ATTR_VISIBILITY_HIDDEN T * get () const
T * operator-> () const
T & operator* () const
void reset (T *newPtr=nullptr)
Accessor accessAllThreads () const
ThreadLocal (ThreadLocal &&)=default
ThreadLocal & operator= (ThreadLocal &&)=default
Private Member Functions
ThreadLocal (const ThreadLocal &)=delete
ThreadLocal & operator= (const ThreadLocal &)=delete
FOLLY_NOINLINE T * makeTlp () const
Private Attributes
ThreadLocalPtr< T, Tag, AccessMode > tlp_
std::function< T *()> constructor_
Detailed Description
template<class T, class Tag = void, class AccessMode = void>
class folly::ThreadLocal< T, Tag, AccessMode >
Definition at line 59 of file ThreadLocal.h.
Member Typedef Documentation
template<class T, class Tag = void, class AccessMode = void> typedef ThreadLocalPtr<T, Tag, AccessMode>::Accessor folly::ThreadLocal< T, Tag, AccessMode >::Accessor
Definition at line 86 of file ThreadLocal.h.
Constructor & Destructor Documentation
template<class T, class Tag = void, class AccessMode = void> constexpr folly::ThreadLocal< T, Tag, AccessMode >::ThreadLocal () inline
Definition at line 61 of file ThreadLocal.h.
Referenced by folly::ThreadLocal< std::queue< folly::Function > >::accessAllThreads().
 : constructor_([]() { return new T(); }) {}
template<class T, class Tag = void, class AccessMode = void> template<typename F , _t< std::enable_if< is_invocable_r< T *, F >::value, int >> = 0> folly::ThreadLocal< T, Tag, AccessMode >::ThreadLocal (F && constructor) inline explicit
Definition at line 66 of file ThreadLocal.h.
       : constructor_(std::forward<F>(constructor)) {}
template<class T, class Tag = void, class AccessMode = void> folly::ThreadLocal< T, Tag, AccessMode >::ThreadLocal (ThreadLocal< T, Tag, AccessMode > &&) default
template<class T, class Tag = void, class AccessMode = void> folly::ThreadLocal< T, Tag, AccessMode >::ThreadLocal (const ThreadLocal< T, Tag, AccessMode > &) private delete
Member Function Documentation
template<class T, class Tag = void, class AccessMode = void> Accessor folly::ThreadLocal< T, Tag, AccessMode >::accessAllThreads () const inline
Definition at line 87 of file ThreadLocal.h.
Referenced by folly::SingletonThreadLocal< T, Tag, Make, TLTag >::accessAllThreads(), SimpleThreadCachedInt::read(), and TEST().
{
     return tlp_.accessAllThreads();
   }
template<class T, class Tag = void, class AccessMode = void> FOLLY_ALWAYS_INLINE FOLLY_ATTR_VISIBILITY_HIDDEN T* folly::ThreadLocal< T, Tag, AccessMode >::get () const inline
Definition at line 69 of file ThreadLocal.h.
Referenced by TEST().
{
     auto const ptr = tlp_.get();
     return FOLLY_LIKELY(!!ptr) ? ptr : makeTlp();
   }
template<class T, class Tag = void, class AccessMode = void> FOLLY_NOINLINE T* folly::ThreadLocal< T, Tag, AccessMode >::makeTlp () const inline private
Definition at line 100 of file ThreadLocal.h.
Referenced by folly::ThreadLocal< std::queue< folly::Function > >::get().
{
     auto const ptr = constructor_();
     tlp_.reset(ptr);
     return ptr;
   }
template<class T, class Tag = void, class AccessMode = void> T& folly::ThreadLocal< T, Tag, AccessMode >::operator* () const inline
Definition at line 78 of file ThreadLocal.h.
{
     return *get();
   }
template<class T, class Tag = void, class AccessMode = void> T* folly::ThreadLocal< T, Tag, AccessMode >::operator-> () const inline
Definition at line 74 of file ThreadLocal.h.
{
     return get();
   }
template<class T, class Tag = void, class AccessMode = void> ThreadLocal& folly::ThreadLocal< T, Tag, AccessMode >::operator= (ThreadLocal< T, Tag, AccessMode > &&) default
Referenced by folly::ThreadLocal< std::queue< folly::Function > >::accessAllThreads(), folly::ThreadLocalPtr< SubscriberMap >::destroy(), and folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::end().
template<class T, class Tag = void, class AccessMode = void> ThreadLocal& folly::ThreadLocal< T, Tag, AccessMode >::operator= (const ThreadLocal< T, Tag, AccessMode > &) private delete
template<class T, class Tag = void, class AccessMode = void> void folly::ThreadLocal< T, Tag, AccessMode >::reset (T * newPtr = nullptr) inline
Definition at line 82 of file ThreadLocal.h.
Referenced by folly::ThreadLocalPtr< SubscriberMap >::reset(), and TEST().
{
     tlp_.reset(newPtr);
   }
Member Data Documentation
template<class T, class Tag = void, class AccessMode = void> std::function<T*()> folly::ThreadLocal< T, Tag, AccessMode >::constructor_ private
Definition at line 107 of file ThreadLocal.h.
Referenced by folly::ThreadLocal< std::queue< folly::Function > >::makeTlp().
template<class T, class Tag = void, class AccessMode = void> ThreadLocalPtr<T, Tag, AccessMode> folly::ThreadLocal< T, Tag, AccessMode >::tlp_ mutable private
Definition at line 106 of file ThreadLocal.h.
Referenced by folly::ThreadLocal< std::queue< folly::Function > >::accessAllThreads(), folly::ThreadLocal< std::queue< folly::Function > >::get(), folly::ThreadLocal< std::queue< folly::Function > >::makeTlp(), and folly::ThreadLocal< std::queue< folly::Function > >::reset().
The documentation for this class was generated from the following file:
proxygen/folly/folly/ThreadLocal.h