proxygen: folly::FakeAllPowerfulAssertingMutexInternal Class Reference
folly::FakeAllPowerfulAssertingMutexInternal Class Reference
Public Types
enum CurrentLockState { CurrentLockState::UNLOCKED, CurrentLockState::SHARED, CurrentLockState::UPGRADE, CurrentLockState::UNIQUE }
Public Member Functions
void lock ()
void unlock ()
void lock_shared ()
void unlock_shared ()
void lock_upgrade ()
void unlock_upgrade ()
void unlock_upgrade_and_lock ()
void unlock_and_lock_upgrade ()
void unlock_and_lock_shared ()
void unlock_upgrade_and_lock_shared ()
template<class Rep , class Period >
bool try_lock_for (const std::chrono::duration< Rep, Period > &)
template<class Rep , class Period >
bool try_lock_upgrade_for (const std::chrono::duration< Rep, Period > &)
template<class Rep , class Period >
bool try_unlock_upgrade_and_lock_for (const std::chrono::duration< Rep, Period > &)
Public Attributes
CurrentLockState lock_state {CurrentLockState::UNLOCKED}
Detailed Description
Test mutex to help to automate assertions, taken from LockTraitsTest.cpp
Definition at line 204 of file SynchronizedTest.cpp.
Member Enumeration Documentation
enum folly::FakeAllPowerfulAssertingMutexInternal::CurrentLockState strong
Enumerator
UNLOCKED
SHARED
UPGRADE
UNIQUE
Definition at line 206 of file SynchronizedTest.cpp.
 { UNLOCKED, SHARED, UPGRADE, UNIQUE };
Member Function Documentation
void folly::FakeAllPowerfulAssertingMutexInternal::lock () inline
Definition at line 208 of file SynchronizedTest.cpp.
References EXPECT_EQ.
Referenced by folly::FakeAllPowerfulAssertingMutex::lock().
               {
     EXPECT_EQ(this->lock_state, CurrentLockState::UNLOCKED);
     this->lock_state = CurrentLockState::UNIQUE;
   }
void folly::FakeAllPowerfulAssertingMutexInternal::lock_shared () inline
Definition at line 216 of file SynchronizedTest.cpp.
References EXPECT_EQ.
Referenced by folly::FakeAllPowerfulAssertingMutex::lock_shared().
                      {
     EXPECT_EQ(this->lock_state, CurrentLockState::UNLOCKED);
     this->lock_state = CurrentLockState::SHARED;
   }
void folly::FakeAllPowerfulAssertingMutexInternal::lock_upgrade () inline
Definition at line 224 of file SynchronizedTest.cpp.
References EXPECT_EQ, and UPGRADE.
Referenced by folly::FakeAllPowerfulAssertingMutex::lock_upgrade().
                       {
     EXPECT_EQ(this->lock_state, CurrentLockState::UNLOCKED);
     this->lock_state = CurrentLockState::UPGRADE;
   }
template<class Rep , class Period > bool folly::FakeAllPowerfulAssertingMutexInternal::try_lock_for (const std::chrono::duration< Rep, Period > &) inline
Definition at line 251 of file SynchronizedTest.cpp.
References EXPECT_EQ.
Referenced by folly::FakeAllPowerfulAssertingMutex::try_lock_for().
{
     EXPECT_EQ(this->lock_state, CurrentLockState::UNLOCKED);
     this->lock_state = CurrentLockState::UNIQUE;
     return true;
   }
template<class Rep , class Period > bool folly::FakeAllPowerfulAssertingMutexInternal::try_lock_upgrade_for (const std::chrono::duration< Rep, Period > &) inline
Definition at line 258 of file SynchronizedTest.cpp.
References EXPECT_EQ, and UPGRADE.
Referenced by folly::FakeAllPowerfulAssertingMutex::try_lock_upgrade_for().
{
     EXPECT_EQ(this->lock_state, CurrentLockState::UNLOCKED);
     this->lock_state = CurrentLockState::UPGRADE;
     return true;
   }
template<class Rep , class Period > bool folly::FakeAllPowerfulAssertingMutexInternal::try_unlock_upgrade_and_lock_for (const std::chrono::duration< Rep, Period > &) inline
Definition at line 265 of file SynchronizedTest.cpp.
References EXPECT_EQ, and UPGRADE.
Referenced by folly::FakeAllPowerfulAssertingMutex::try_unlock_upgrade_and_lock_for().
{
     EXPECT_EQ(this->lock_state, CurrentLockState::UPGRADE);
     this->lock_state = CurrentLockState::UNIQUE;
     return true;
   }
void folly::FakeAllPowerfulAssertingMutexInternal::unlock () inline
Definition at line 212 of file SynchronizedTest.cpp.
References EXPECT_EQ.
Referenced by folly::FakeAllPowerfulAssertingMutex::unlock().
                 {
     EXPECT_EQ(this->lock_state, CurrentLockState::UNIQUE);
     this->lock_state = CurrentLockState::UNLOCKED;
   }
void folly::FakeAllPowerfulAssertingMutexInternal::unlock_and_lock_shared () inline
Definition at line 241 of file SynchronizedTest.cpp.
References EXPECT_EQ.
Referenced by folly::FakeAllPowerfulAssertingMutex::unlock_and_lock_shared().
{
     EXPECT_EQ(this->lock_state, CurrentLockState::UNIQUE);
     this->lock_state = CurrentLockState::SHARED;
   }
void folly::FakeAllPowerfulAssertingMutexInternal::unlock_and_lock_upgrade () inline
Definition at line 237 of file SynchronizedTest.cpp.
References EXPECT_EQ, and UPGRADE.
Referenced by folly::FakeAllPowerfulAssertingMutex::unlock_and_lock_upgrade().
{
     EXPECT_EQ(this->lock_state, CurrentLockState::UNIQUE);
     this->lock_state = CurrentLockState::UPGRADE;
   }
void folly::FakeAllPowerfulAssertingMutexInternal::unlock_shared () inline
Definition at line 220 of file SynchronizedTest.cpp.
References EXPECT_EQ.
Referenced by folly::FakeAllPowerfulAssertingMutex::unlock_shared().
{
     EXPECT_EQ(this->lock_state, CurrentLockState::SHARED);
     this->lock_state = CurrentLockState::UNLOCKED;
   }
void folly::FakeAllPowerfulAssertingMutexInternal::unlock_upgrade () inline
Definition at line 228 of file SynchronizedTest.cpp.
References EXPECT_EQ, and UPGRADE.
Referenced by folly::FakeAllPowerfulAssertingMutex::unlock_upgrade().
{
     EXPECT_EQ(this->lock_state, CurrentLockState::UPGRADE);
     this->lock_state = CurrentLockState::UNLOCKED;
   }
void folly::FakeAllPowerfulAssertingMutexInternal::unlock_upgrade_and_lock () inline
Definition at line 233 of file SynchronizedTest.cpp.
References EXPECT_EQ, and UPGRADE.
Referenced by folly::FakeAllPowerfulAssertingMutex::unlock_upgrade_and_lock().
{
     EXPECT_EQ(this->lock_state, CurrentLockState::UPGRADE);
     this->lock_state = CurrentLockState::UNIQUE;
   }
void folly::FakeAllPowerfulAssertingMutexInternal::unlock_upgrade_and_lock_shared () inline
Definition at line 245 of file SynchronizedTest.cpp.
References EXPECT_EQ, and UPGRADE.
Referenced by folly::FakeAllPowerfulAssertingMutex::unlock_upgrade_and_lock_shared().
{
     EXPECT_EQ(this->lock_state, CurrentLockState::UPGRADE);
     this->lock_state = CurrentLockState::SHARED;
   }
Member Data Documentation
CurrentLockState folly::FakeAllPowerfulAssertingMutexInternal::lock_state {CurrentLockState::UNLOCKED}
Definition at line 275 of file SynchronizedTest.cpp.
Referenced by folly::TEST_F().
The documentation for this class was generated from the following file:
proxygen/folly/folly/test/SynchronizedTest.cpp