proxygen: folly::gen::detail::Skip::Generator< Value, Source > Class Template Reference
folly::gen::detail::Skip::Generator< Value, Source > Class Template Reference
#include <Base-inl.h>
Public Member Functions
Generator (Source source, size_t count)
template<class Body >
void foreach (Body &&body) const
template<class Handler >
bool apply (Handler &&handler) const
Public Member Functions inherited from folly::gen::GenImpl< Value, Generator< Value, Source > >
bool apply (Handler &&handler) const
void foreach (Body &&body) const
Public Member Functions inherited from folly::gen::FBounded< Self >
const Self & self () const
Self & self ()
Static Public Attributes
static constexpr bool infinite = Source::infinite
Static Public Attributes inherited from folly::gen::GenImpl< Value, Generator< Value, Source > >
static constexpr bool infinite
Private Attributes
Source source_
size_t count_
Additional Inherited Members
Public Types inherited from folly::gen::GenImpl< Value, Generator< Value, Source > >
typedef Value ValueType
typedef std::decay< Value >::type StorageType
Protected Member Functions inherited from folly::gen::GenImpl< Value, Generator< Value, Source > >
GenImpl ()=default
GenImpl (GenImpl &&)=default
GenImpl (const GenImpl &)=default
GenImpl & operator= (GenImpl &&)=default
GenImpl & operator= (const GenImpl &)=default
Detailed Description
template<class Value, class Source>
class folly::gen::detail::Skip::Generator< Value, Source >
Definition at line 971 of file Base-inl.h.
Constructor & Destructor Documentation
template<class Value , class Source > folly::gen::detail::Skip::Generator< Value, Source >::Generator (Source source, size_t count) inline explicit
Definition at line 976 of file Base-inl.h.
         : source_(std::move(source)), count_(count) {}
Member Function Documentation
template<class Value , class Source > template<class Handler > bool folly::gen::detail::Skip::Generator< Value, Source >::apply (Handler && handler) const inline
Definition at line 996 of file Base-inl.h.
References handler(), value, and testing::Value().
{
       if (count_ == 0) {
         return source_.apply(std::forward<Handler>(handler));
       }
       size_t n = 0;
       return source_.apply([&](Value value) -> bool {
         if (n < count_) {
           ++n;
           return true;
         }
         return handler(std::forward<Value>(value));
       });
     }
template<class Value , class Source > template<class Body > void folly::gen::detail::Skip::Generator< Value, Source >::foreach (Body && body) const inline
Definition at line 980 of file Base-inl.h.
References value, and testing::Value().
{
       if (count_ == 0) {
         source_.foreach(body);
         return;
       }
       size_t n = 0;
       source_.foreach([&](Value value) {
         if (n < count_) {
           ++n;
         } else {
           body(std::forward<Value>(value));
         }
       });
     }
Member Data Documentation
template<class Value , class Source > size_t folly::gen::detail::Skip::Generator< Value, Source >::count_ private
Definition at line 973 of file Base-inl.h.
template<class Value , class Source > constexpr bool folly::gen::detail::Skip::Generator< Value, Source >::infinite = Source::infinite static
Definition at line 1011 of file Base-inl.h.
template<class Value , class Source > Source folly::gen::detail::Skip::Generator< Value, Source >::source_ private
Definition at line 972 of file Base-inl.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/gen/Base-inl.h