proxygen: folly::hazptr_obj_linked< Atom > Class Template Reference
folly::hazptr_obj_linked< Atom > Class Template Reference
#include <Hazptr-fwd.h>
Public Member Functions
void acquire_link () noexcept
void acquire_link_safe () noexcept
void acquire_ref () noexcept
void acquire_ref_safe () noexcept
Public Member Functions inherited from folly::hazptr_obj< Atom >
hazptr_obj () noexcept
hazptr_obj (const hazptr_obj< Atom > &) noexcept
hazptr_obj (hazptr_obj< Atom > &&) noexcept
hazptr_obj< Atom > & operator= (const hazptr_obj< Atom > &) noexcept
hazptr_obj< Atom > & operator= (hazptr_obj< Atom > &&) noexcept
Private Types
using Count = uint32_t
Private Member Functions
Count count () const noexcept
void count_set (Count val) noexcept
void count_inc (Count add) noexcept
void count_inc_safe (Count add) noexcept
bool count_cas (Count &oldval, Count newval) noexcept
bool release_link () noexcept
bool release_ref () noexcept
bool downgrade_link () noexcept
Private Attributes
Atom< Count > count_ {0}
Static Private Attributes
static constexpr Count kRef = 1u
static constexpr Count kLink = 1u << 16
static constexpr Count kRefMask = kLink - 1u
static constexpr Count kLinkMask = ~kRefMask
Friends
template<typename , template< typename > class, typename >
class hazptr_obj_base_linked
Detailed Description
template<template< typename > class Atom>
class folly::hazptr_obj_linked< Atom >
hazptr_obj_linked
hazptr_obj_linked
Base class template for link counted objects. Supports:
Protecting descendants of protected objects.
One-pass reclamation of long immutable chains of objects.
Automatic reclamation of acyclic structures.
Two inbound link counts are maintained per object:
Link count: Represents the number of links from mutable paths.
Ref count: Represents the number of links from immutable paths. [Note: The ref count is one less than such links plus one if the object hasn't gone through matching with hazard pointers without finding a match. That is, a new object without inbound links has a ref count of 0 and an about-to-be-reclaimed object can be viewed to have a ref count of -1.]
User code can increment the link and ref counts by calling acquire_link and acquire_ref or their variants that require the user to guarantee thread safety. There are no public functions to decrement the counts explicitly. Counts are decremented implicitly as described in hazptr_obj_base_linked.
Definition at line 79 of file Hazptr-fwd.h.
Member Typedef Documentation
template<template< typename > class Atom> using folly::hazptr_obj_linked< Atom >::Count = uint32_t private
Definition at line 92 of file HazptrObjLinked.h.
Member Function Documentation
template<template< typename > class Atom> void folly::hazptr_obj_linked< Atom >::acquire_link () inline noexcept
Definition at line 102 of file HazptrObjLinked.h.
{
     count_inc(kLink);
   }
template<template< typename > class Atom> void folly::hazptr_obj_linked< Atom >::acquire_link_safe () inline noexcept
Definition at line 106 of file HazptrObjLinked.h.
Referenced by auto_retire_test(), and basic_objects_test().
{
     count_inc_safe(kLink);
   }
template<template< typename > class Atom> void folly::hazptr_obj_linked< Atom >::acquire_ref () inline noexcept
Definition at line 110 of file HazptrObjLinked.h.
{
     count_inc(kRef);
   }
template<template< typename > class Atom> void folly::hazptr_obj_linked< Atom >::acquire_ref_safe () inline noexcept
Definition at line 114 of file HazptrObjLinked.h.
{
     count_inc_safe(kRef);
   }
template<template< typename > class Atom> Count folly::hazptr_obj_linked< Atom >::count () const inline private noexcept
Definition at line 122 of file HazptrObjLinked.h.
{
     return count_.load(std::memory_order_acquire);
   }
template<template< typename > class Atom> bool folly::hazptr_obj_linked< Atom >::count_cas (Count & oldval, Count newval) inline private noexcept
Definition at line 143 of file HazptrObjLinked.h.
{
     return count_.compare_exchange_weak(
         oldval, newval, std::memory_order_acq_rel, std::memory_order_acquire);
   }
template<template< typename > class Atom> void folly::hazptr_obj_linked< Atom >::count_inc (Count add) inline private noexcept
Definition at line 130 of file HazptrObjLinked.h.
References add.
{
     auto oldval = count_.fetch_add(add, std::memory_order_acq_rel);
     DCHECK_LT(oldval & kLinkMask, kLinkMask);
     DCHECK_LT(oldval & kRefMask, kRefMask);
   }
template<template< typename > class Atom> void folly::hazptr_obj_linked< Atom >::count_inc_safe (Count add) inline private noexcept
Definition at line 136 of file HazptrObjLinked.h.
References add, and count.
{
     auto oldval = count();
     count_set(oldval + add);
     DCHECK_LT(oldval & kLinkMask, kLinkMask);
     DCHECK_LT(oldval & kRefMask, kRefMask);
   }
template<template< typename > class Atom> void folly::hazptr_obj_linked< Atom >::count_set (Count val) inline private noexcept
Definition at line 126 of file HazptrObjLinked.h.
References val.
{
     count_.store(val, std::memory_order_release);
   }
template<template< typename > class Atom> bool folly::hazptr_obj_linked< Atom >::downgrade_link () inline private noexcept
Definition at line 180 of file HazptrObjLinked.h.
References Atom, count, D, and folly::gen::sub().
{
     auto oldval = count();
     auto sub = kLink - kRef;
     while (true) {
       if (oldval == kLink) {
         count_set(kRef);
         return true;
       }
       if (count_cas(oldval, oldval - sub)) {
         return (oldval & kLinkMask) == kLink;
       }
     }
   }
template<template< typename > class Atom> bool folly::hazptr_obj_linked< Atom >::release_link () inline private noexcept
Definition at line 148 of file HazptrObjLinked.h.
References count, and folly::gen::sub().
{
     auto sub = kLink;
     auto oldval = count();
     while (true) {
       DCHECK_GT(oldval & kLinkMask, 0u);
       if (oldval == kLink) {
         count_set(0u);
         return true;
       }
       if (count_cas(oldval, oldval - sub)) {
         return false;
       }
     }
   }
template<template< typename > class Atom> bool folly::hazptr_obj_linked< Atom >::release_ref () inline private noexcept
Definition at line 163 of file HazptrObjLinked.h.
References count, folly::kIsDebug, and folly::gen::sub().
{
     auto sub = kRef;
     auto oldval = count();
     while (true) {
       if (oldval == 0u) {
         if (kIsDebug) {
           count_set(kRefMask);
         }
         return true;
       }
       DCHECK_GT(oldval & kRefMask, 0u);
       if (count_cas(oldval, oldval - sub)) {
         return false;
       }
     }
   }
Friends And Related Function Documentation
template<template< typename > class Atom> template<typename , template< typename > class, typename > friend class hazptr_obj_base_linked friend
Definition at line 120 of file HazptrObjLinked.h.
Member Data Documentation
template<template< typename > class Atom> Atom<Count> folly::hazptr_obj_linked< Atom >::count_ {0} private
Definition at line 99 of file HazptrObjLinked.h.
template<template< typename > class Atom> constexpr Count folly::hazptr_obj_linked< Atom >::kLink = 1u << 16 static private
Definition at line 95 of file HazptrObjLinked.h.
template<template< typename > class Atom> constexpr Count folly::hazptr_obj_linked< Atom >::kLinkMask = ~kRefMask static private
Definition at line 97 of file HazptrObjLinked.h.
template<template< typename > class Atom> constexpr Count folly::hazptr_obj_linked< Atom >::kRef = 1u static private
Definition at line 94 of file HazptrObjLinked.h.
template<template< typename > class Atom> constexpr Count folly::hazptr_obj_linked< Atom >::kRefMask = kLink - 1u static private
Definition at line 96 of file HazptrObjLinked.h.
The documentation for this class was generated from the following files:
proxygen/folly/folly/synchronization/Hazptr-fwd.h
proxygen/folly/folly/synchronization/HazptrObjLinked.h