proxygen: folly::ReadCallback::Buffer Class Reference
folly::ReadCallback::Buffer Class Reference
#include <AsyncSSLSocketTest.h>
Public Member Functions
Buffer ()
Buffer (char *buf, size_t len)
void reset ()
void allocate (size_t len)
void free ()
Public Attributes
char * buffer
size_t length
Detailed Description
Definition at line 351 of file AsyncSSLSocketTest.h.
Constructor & Destructor Documentation
folly::ReadCallback::Buffer::Buffer () inline
Definition at line 353 of file AsyncSSLSocketTest.h.
 : buffer(nullptr), length(0) {}
folly::ReadCallback::Buffer::Buffer (char * buf, size_t len) inline
Definition at line 354 of file AsyncSSLSocketTest.h.
 : buffer(buf), length(len) {}
Member Function Documentation
void folly::ReadCallback::Buffer::allocate (size_t len) inline
Definition at line 360 of file AsyncSSLSocketTest.h.
References buffer().
{
       assert(buffer == nullptr);
       this->buffer = static_cast<char*>(malloc(len));
       this->length = len;
     }
void folly::ReadCallback::Buffer::free () inline
Definition at line 365 of file AsyncSSLSocketTest.h.
References buffer(), and bm::free().
                 {
       ::free(buffer);
       reset();
     }
void folly::ReadCallback::Buffer::reset () inline
Definition at line 356 of file AsyncSSLSocketTest.h.
References buffer().
                  {
       buffer = nullptr;
       length = 0;
     }
Member Data Documentation
char* folly::ReadCallback::Buffer::buffer
Definition at line 370 of file AsyncSSLSocketTest.h.
size_t folly::ReadCallback::Buffer::length
Definition at line 371 of file AsyncSSLSocketTest.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/io/async/test/AsyncSSLSocketTest.h