proxygen: folly::AsyncSSLSocket::Timeout Class Reference
folly::AsyncSSLSocket::Timeout Class Reference
#include <AsyncSSLSocket.h>
Public Member Functions
Timeout (AsyncSSLSocket *sslSocket, EventBase *eventBase)
bool scheduleTimeout (TimeoutManager::timeout_type timeout)
bool scheduleTimeout (uint32_t timeoutMs)
TimeoutManager::timeout_type getTimeout ()
void timeoutExpired () noexceptoverride
Public Member Functions inherited from folly::AsyncTimeout
AsyncTimeout (TimeoutManager *timeoutManager)
AsyncTimeout (EventBase *eventBase)
AsyncTimeout (TimeoutManager *timeoutManager, InternalEnum internal)
AsyncTimeout (EventBase *eventBase, InternalEnum internal)
AsyncTimeout ()
virtual ~AsyncTimeout ()
bool scheduleTimeout (uint32_t milliseconds)
bool scheduleTimeout (TimeoutManager::timeout_type timeout)
void cancelTimeout ()
bool isScheduled () const
void attachTimeoutManager (TimeoutManager *timeoutManager, InternalEnum internal=InternalEnum::NORMAL)
void attachEventBase (EventBase *eventBase, InternalEnum internal=InternalEnum::NORMAL)
void detachTimeoutManager ()
void detachEventBase ()
const TimeoutManager * getTimeoutManager ()
struct event * getEvent ()
Private Attributes
AsyncSSLSocket * sslSocket_
TimeoutManager::timeout_type timeout_
Additional Inherited Members
Public Types inherited from folly::AsyncTimeout
typedef TimeoutManager::InternalEnum InternalEnum
Static Public Member Functions inherited from folly::AsyncTimeout
template<typename TCallback >
static std::unique_ptr< AsyncTimeout > make (TimeoutManager &manager, TCallback &&callback)
template<typename TCallback >
static std::unique_ptr< AsyncTimeout > schedule (TimeoutManager::timeout_type timeout, TimeoutManager &manager, TCallback &&callback)
Detailed Description
Definition at line 126 of file AsyncSSLSocket.h.
Constructor & Destructor Documentation
folly::AsyncSSLSocket::Timeout::Timeout (AsyncSSLSocket * sslSocket, EventBase * eventBase) inline
Definition at line 128 of file AsyncSSLSocket.h.
         : AsyncTimeout(eventBase), sslSocket_(sslSocket) {}
Member Function Documentation
TimeoutManager::timeout_type folly::AsyncSSLSocket::Timeout::getTimeout () inline
Definition at line 140 of file AsyncSSLSocket.h.
{
       return timeout_;
     }
bool folly::AsyncSSLSocket::Timeout::scheduleTimeout (TimeoutManager::timeout_type timeout) inline
Definition at line 131 of file AsyncSSLSocket.h.
References folly::AsyncTimeout::scheduleTimeout().
Referenced by folly::AsyncSSLSocket::scheduleConnectTimeout(), folly::test::MockAsyncSSLSocket::sslAccept(), folly::AsyncSSLSocket::sslAccept(), folly::test::MockAsyncSSLSocket::sslConn(), and folly::AsyncSSLSocket::startSSLConnect().
{
       timeout_ = timeout;
       return AsyncTimeout::scheduleTimeout(timeout);
     }
bool folly::AsyncSSLSocket::Timeout::scheduleTimeout (uint32_t timeoutMs) inline
Definition at line 136 of file AsyncSSLSocket.h.
{
       return scheduleTimeout(std::chrono::milliseconds{timeoutMs});
     }
void folly::AsyncSSLSocket::Timeout::timeoutExpired () inline override virtual noexcept
timeoutExpired() is invoked when the timeout period has expired.
Implements folly::AsyncTimeout.
Definition at line 144 of file AsyncSSLSocket.h.
References sslSocket_.
{
       sslSocket_->timeoutExpired(timeout_);
     }
Member Data Documentation
AsyncSSLSocket* folly::AsyncSSLSocket::Timeout::sslSocket_ private
Definition at line 149 of file AsyncSSLSocket.h.
TimeoutManager::timeout_type folly::AsyncSSLSocket::Timeout::timeout_ private
Definition at line 150 of file AsyncSSLSocket.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/io/async/AsyncSSLSocket.h