proxygen: testing::internal::InvokeMethodAction< Class, MethodPtr > Class Template Reference
testing::internal::InvokeMethodAction< Class, MethodPtr > Class Template Reference
#include <gmock-more-actions.h>
Public Member Functions
InvokeMethodAction (Class *obj_ptr, MethodPtr method_ptr)
template<typename Result , typename ArgumentTuple >
Result Perform (const ArgumentTuple &args) const
InvokeMethodAction (Class *obj_ptr, MethodPtr method_ptr)
template<typename Result , typename ArgumentTuple >
Result Perform (const ArgumentTuple &args) const
InvokeMethodAction (Class *obj_ptr, MethodPtr method_ptr)
template<typename Result , typename ArgumentTuple >
Result Perform (const ArgumentTuple &args) const
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (InvokeMethodAction)
GTEST_DISALLOW_ASSIGN_ (InvokeMethodAction)
GTEST_DISALLOW_ASSIGN_ (InvokeMethodAction)
Private Attributes
const MethodPtr method_ptr_
Class *const obj_ptr_
Detailed Description
template<class Class, typename MethodPtr>
class testing::internal::InvokeMethodAction< Class, MethodPtr >
Definition at line 72 of file gmock-more-actions.h.
Constructor & Destructor Documentation
template<class Class , typename MethodPtr > testing::internal::InvokeMethodAction< Class, MethodPtr >::InvokeMethodAction (Class * obj_ptr, MethodPtr method_ptr) inline
Definition at line 74 of file gmock-more-actions.h.
       : method_ptr_(method_ptr), obj_ptr_(obj_ptr) {}
template<class Class , typename MethodPtr > testing::internal::InvokeMethodAction< Class, MethodPtr >::InvokeMethodAction (Class * obj_ptr, MethodPtr method_ptr) inline
Definition at line 74 of file gmock-more-actions.h.
       : method_ptr_(method_ptr), obj_ptr_(obj_ptr) {}
template<class Class , typename MethodPtr > testing::internal::InvokeMethodAction< Class, MethodPtr >::InvokeMethodAction (Class * obj_ptr, MethodPtr method_ptr) inline
Definition at line 74 of file gmock-more-actions.h.
       : method_ptr_(method_ptr), obj_ptr_(obj_ptr) {}
Member Function Documentation
template<class Class , typename MethodPtr > testing::internal::InvokeMethodAction< Class, MethodPtr >::GTEST_DISALLOW_ASSIGN_ (InvokeMethodAction< Class, MethodPtr >) private
template<class Class , typename MethodPtr > testing::internal::InvokeMethodAction< Class, MethodPtr >::GTEST_DISALLOW_ASSIGN_ (InvokeMethodAction< Class, MethodPtr >) private
template<class Class , typename MethodPtr > testing::internal::InvokeMethodAction< Class, MethodPtr >::GTEST_DISALLOW_ASSIGN_ (InvokeMethodAction< Class, MethodPtr >) private
template<class Class , typename MethodPtr > template<typename Result , typename ArgumentTuple > Result testing::internal::InvokeMethodAction< Class, MethodPtr >::Perform (const ArgumentTuple & args) const inline
Definition at line 78 of file gmock-more-actions.h.
{
     return InvokeHelper<Result, ArgumentTuple>::InvokeMethod(
         obj_ptr_, method_ptr_, args);
   }
template<class Class , typename MethodPtr > template<typename Result , typename ArgumentTuple > Result testing::internal::InvokeMethodAction< Class, MethodPtr >::Perform (const ArgumentTuple & args) const inline
Definition at line 78 of file gmock-more-actions.h.
References upload::action, testing::ACTION_P(), testing::ACTION_TEMPLATE(), folly::copy(), testing::internal::CopyElements(), folly::gen::first, GTEST_COMPILE_ASSERT_, testing::internal::InvokeAction< FunctionImpl >::GTEST_DISALLOW_ASSIGN_(), testing::Invoke(), k, testing::MakePolymorphicAction(), gmock_output_test::output, type, value, testing::WithArg(), and testing::WithoutArgs().
{
     return InvokeHelper<Result, ArgumentTuple>::InvokeMethod(
         obj_ptr_, method_ptr_, args);
   }
template<class Class , typename MethodPtr > template<typename Result , typename ArgumentTuple > Result testing::internal::InvokeMethodAction< Class, MethodPtr >::Perform (const ArgumentTuple & args) const inline
Definition at line 78 of file gmock-more-actions.h.
References upload::action, testing::ACTION_P(), testing::ACTION_TEMPLATE(), folly::copy(), testing::internal::CopyElements(), folly::gen::first, GTEST_COMPILE_ASSERT_, testing::internal::InvokeAction< FunctionImpl >::GTEST_DISALLOW_ASSIGN_(), testing::Invoke(), k, testing::MakePolymorphicAction(), gmock_output_test::output, type, value, testing::WithArg(), and testing::WithoutArgs().
{
     return InvokeHelper<Result, ArgumentTuple>::InvokeMethod(
         obj_ptr_, method_ptr_, args);
   }
Member Data Documentation
template<class Class , typename MethodPtr > const MethodPtr testing::internal::InvokeMethodAction< Class, MethodPtr >::method_ptr_ private
Definition at line 87 of file gmock-more-actions.h.
template<class Class , typename MethodPtr > Class *const testing::internal::InvokeMethodAction< Class, MethodPtr >::obj_ptr_ private
Definition at line 88 of file gmock-more-actions.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-more-actions.h