proxygen: testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer > Class Template Reference
testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer > Class Template Reference
#include <gmock-matchers.h>
Classes
class Impl
Public Types
typedef internal::StlContainerView< RhsContainer > RhsView
typedef RhsView::type RhsStlContainer
typedef RhsStlContainer::value_type RhsValue
typedef internal::StlContainerView< RhsContainer > RhsView
typedef RhsView::type RhsStlContainer
typedef RhsStlContainer::value_type RhsValue
typedef internal::StlContainerView< RhsContainer > RhsView
typedef RhsView::type RhsStlContainer
typedef RhsStlContainer::value_type RhsValue
Public Member Functions
PointwiseMatcher (const TupleMatcher &tuple_matcher, const RhsContainer &rhs)
template<typename LhsContainer >
operator Matcher< LhsContainer > () const
PointwiseMatcher (const TupleMatcher &tuple_matcher, const RhsContainer &rhs)
template<typename LhsContainer >
operator Matcher< LhsContainer > () const
PointwiseMatcher (const TupleMatcher &tuple_matcher, const RhsContainer &rhs)
template<typename LhsContainer >
operator Matcher< LhsContainer > () const
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (PointwiseMatcher)
GTEST_DISALLOW_ASSIGN_ (PointwiseMatcher)
GTEST_DISALLOW_ASSIGN_ (PointwiseMatcher)
Private Attributes
const TupleMatcher tuple_matcher_
const RhsStlContainer rhs_
Detailed Description
template<typename TupleMatcher, typename RhsContainer>
class testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >
Definition at line 2693 of file gmock-matchers.h.
Member Typedef Documentation
template<typename TupleMatcher, typename RhsContainer> typedef RhsView::type testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::RhsStlContainer
Definition at line 2696 of file gmock-matchers.h.
template<typename TupleMatcher, typename RhsContainer> typedef RhsView::type testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::RhsStlContainer
Definition at line 2696 of file gmock-matchers.h.
template<typename TupleMatcher, typename RhsContainer> typedef RhsView::type testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::RhsStlContainer
Definition at line 2696 of file gmock-matchers.h.
template<typename TupleMatcher, typename RhsContainer> typedef RhsStlContainer::value_type testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::RhsValue
Definition at line 2697 of file gmock-matchers.h.
template<typename TupleMatcher, typename RhsContainer> typedef RhsStlContainer::value_type testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::RhsValue
Definition at line 2697 of file gmock-matchers.h.
template<typename TupleMatcher, typename RhsContainer> typedef RhsStlContainer::value_type testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::RhsValue
Definition at line 2697 of file gmock-matchers.h.
template<typename TupleMatcher, typename RhsContainer> typedef internal::StlContainerView<RhsContainer> testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::RhsView
Definition at line 2695 of file gmock-matchers.h.
template<typename TupleMatcher, typename RhsContainer> typedef internal::StlContainerView<RhsContainer> testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::RhsView
Definition at line 2695 of file gmock-matchers.h.
template<typename TupleMatcher, typename RhsContainer> typedef internal::StlContainerView<RhsContainer> testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::RhsView
Definition at line 2695 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename TupleMatcher, typename RhsContainer> testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::PointwiseMatcher (const TupleMatcher & tuple_matcher, const RhsContainer & rhs) inline
Definition at line 2701 of file gmock-matchers.h.
References GTEST_REMOVE_REFERENCE_AND_CONST_, and testing::StaticAssertTypeEq().
       : tuple_matcher_(tuple_matcher), rhs_(RhsView::Copy(rhs)) {
     // Makes sure the user doesn't instantiate this class template
     // with a const or reference type.
     (void)testing::StaticAssertTypeEq<RhsContainer,
         GTEST_REMOVE_REFERENCE_AND_CONST_(RhsContainer)>();
   }
template<typename TupleMatcher, typename RhsContainer> testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::PointwiseMatcher (const TupleMatcher & tuple_matcher, const RhsContainer & rhs) inline
Definition at line 2701 of file gmock-matchers.h.
References GTEST_REMOVE_REFERENCE_AND_CONST_, and testing::StaticAssertTypeEq().
       : tuple_matcher_(tuple_matcher), rhs_(RhsView::Copy(rhs)) {
     // Makes sure the user doesn't instantiate this class template
     // with a const or reference type.
     (void)testing::StaticAssertTypeEq<RhsContainer,
         GTEST_REMOVE_REFERENCE_AND_CONST_(RhsContainer)>();
   }
template<typename TupleMatcher, typename RhsContainer> testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::PointwiseMatcher (const TupleMatcher & tuple_matcher, const RhsContainer & rhs) inline
Definition at line 2701 of file gmock-matchers.h.
References GTEST_REMOVE_REFERENCE_AND_CONST_, and testing::StaticAssertTypeEq().
       : tuple_matcher_(tuple_matcher), rhs_(RhsView::Copy(rhs)) {
     // Makes sure the user doesn't instantiate this class template
     // with a const or reference type.
     (void)testing::StaticAssertTypeEq<RhsContainer,
         GTEST_REMOVE_REFERENCE_AND_CONST_(RhsContainer)>();
   }
Member Function Documentation
template<typename TupleMatcher, typename RhsContainer> testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::GTEST_DISALLOW_ASSIGN_ (PointwiseMatcher< TupleMatcher, RhsContainer >) private
template<typename TupleMatcher, typename RhsContainer> testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::GTEST_DISALLOW_ASSIGN_ (PointwiseMatcher< TupleMatcher, RhsContainer >) private
template<typename TupleMatcher, typename RhsContainer> testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::GTEST_DISALLOW_ASSIGN_ (PointwiseMatcher< TupleMatcher, RhsContainer >) private
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::operator Matcher< LhsContainer > () const inline
Definition at line 2710 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(new Impl<LhsContainer>(tuple_matcher_, rhs_));
   }
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::operator Matcher< LhsContainer > () const inline
Definition at line 2710 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(new Impl<LhsContainer>(tuple_matcher_, rhs_));
   }
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::operator Matcher< LhsContainer > () const inline
Definition at line 2710 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(new Impl<LhsContainer>(tuple_matcher_, rhs_));
   }
Member Data Documentation
template<typename TupleMatcher, typename RhsContainer> const RhsStlContainer testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::rhs_ private
Definition at line 2793 of file gmock-matchers.h.
template<typename TupleMatcher, typename RhsContainer> const TupleMatcher testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::tuple_matcher_ private
Definition at line 2792 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h