proxygen: upload.AbstractRpcServer Class Reference
upload.AbstractRpcServer Class Reference
Public Member Functions
def __init__ (self, host, auth_function, host_override=None, extra_headers={}, save_cookies=False)
def Send (self, request_path, payload=None, content_type="application/octet-stream", timeout=None, kwargs)
def __init__ (self, host, auth_function, host_override=None, extra_headers={}, save_cookies=False)
def Send (self, request_path, payload=None, content_type="application/octet-stream", timeout=None, kwargs)
def __init__ (self, host, auth_function, host_override=None, extra_headers={}, save_cookies=False)
def Send (self, request_path, payload=None, content_type="application/octet-stream", timeout=None, kwargs)
def __init__ (self, host, auth_function, host_override=None, extra_headers={}, save_cookies=False)
def Send (self, request_path, payload=None, content_type="application/octet-stream", timeout=None, kwargs)
def __init__ (self, host, auth_function, host_override=None, extra_headers={}, save_cookies=False)
def Send (self, request_path, payload=None, content_type="application/octet-stream", timeout=None, kwargs)
def __init__ (self, host, auth_function, host_override=None, extra_headers={}, save_cookies=False)
def Send (self, request_path, payload=None, content_type="application/octet-stream", timeout=None, kwargs)
Public Attributes
host
host_override
auth_function
authenticated
extra_headers
save_cookies
opener
Private Member Functions
def _GetOpener (self)
def _CreateRequest (self, url, data=None)
def _GetAuthToken (self, email, password)
def _GetAuthCookie (self, auth_token)
def _Authenticate (self)
def _GetOpener (self)
def _CreateRequest (self, url, data=None)
def _GetAuthToken (self, email, password)
def _GetAuthCookie (self, auth_token)
def _Authenticate (self)
def _GetOpener (self)
def _CreateRequest (self, url, data=None)
def _GetAuthToken (self, email, password)
def _GetAuthCookie (self, auth_token)
def _Authenticate (self)
def _GetOpener (self)
def _CreateRequest (self, url, data=None)
def _GetAuthToken (self, email, password)
def _GetAuthCookie (self, auth_token)
def _Authenticate (self)
def _GetOpener (self)
def _CreateRequest (self, url, data=None)
def _GetAuthToken (self, email, password)
def _GetAuthCookie (self, auth_token)
def _Authenticate (self)
def _GetOpener (self)
def _CreateRequest (self, url, data=None)
def _GetAuthToken (self, email, password)
def _GetAuthCookie (self, auth_token)
def _Authenticate (self)
Detailed Description
Provides a common interface for a simple RPC server.
Definition at line 124 of file upload.py.
Constructor & Destructor Documentation
def upload.AbstractRpcServer.__init__ (self, host, auth_function, host_override = None, extra_headers = {}, save_cookies = False)
Creates a new HttpRpcServer.
Args:
  host: The host to send requests to.
  auth_function: A function that takes no arguments and returns an
(email, password) tuple when called. Will be called if authentication
is required.
  host_override: The host header to send to the server (defaults to host).
  extra_headers: A dict of extra headers to append to every request.
  save_cookies: If True, save the authentication cookies to local disk.
If False, use an in-memory cookiejar instead.  Subclasses must
implement this functionality.  Defaults to False.
Definition at line 128 of file upload.py.
                save_cookies=False):
     """Creates a new HttpRpcServer.
     Args:
       host: The host to send requests to.
       auth_function: A function that takes no arguments and returns an
         (email, password) tuple when called. Will be called if authentication
         is required.
       host_override: The host header to send to the server (defaults to host).
       extra_headers: A dict of extra headers to append to every request.
       save_cookies: If True, save the authentication cookies to local disk.
         If False, use an in-memory cookiejar instead.  Subclasses must
         implement this functionality.  Defaults to False.
     """
     self.host = host
     self.host_override = host_override
     self.auth_function = auth_function
     self.authenticated = False
     self.extra_headers = extra_headers
     self.save_cookies = save_cookies
     self.opener = self._GetOpener()
     if self.host_override:
       logging.info("Server: %s; Host: %s", self.host, self.host_override)
     else:
       logging.info("Server: %s", self.host)
def upload.AbstractRpcServer.__init__ (self, host, auth_function, host_override = None, extra_headers = {}, save_cookies = False)
Creates a new HttpRpcServer.
Args:
  host: The host to send requests to.
  auth_function: A function that takes no arguments and returns an
(email, password) tuple when called. Will be called if authentication
is required.
  host_override: The host header to send to the server (defaults to host).
  extra_headers: A dict of extra headers to append to every request.
  save_cookies: If True, save the authentication cookies to local disk.
If False, use an in-memory cookiejar instead.  Subclasses must
implement this functionality.  Defaults to False.
Definition at line 128 of file upload.py.
References upload.AbstractRpcServer._GetOpener(), upload.AbstractRpcServer.auth_function, upload.AbstractRpcServer.authenticated, upload.AbstractRpcServer.extra_headers, upload.AbstractRpcServer.host, upload.AbstractRpcServer.host_override, upload.AbstractRpcServer.opener, and upload.AbstractRpcServer.save_cookies.
                save_cookies=False):
     """Creates a new HttpRpcServer.
     Args:
       host: The host to send requests to.
       auth_function: A function that takes no arguments and returns an
         (email, password) tuple when called. Will be called if authentication
         is required.
       host_override: The host header to send to the server (defaults to host).
       extra_headers: A dict of extra headers to append to every request.
       save_cookies: If True, save the authentication cookies to local disk.
         If False, use an in-memory cookiejar instead.  Subclasses must
         implement this functionality.  Defaults to False.
     """
     self.host = host
     self.host_override = host_override
     self.auth_function = auth_function
     self.authenticated = False
     self.extra_headers = extra_headers
     self.save_cookies = save_cookies
     self.opener = self._GetOpener()
     if self.host_override:
       logging.info("Server: %s; Host: %s", self.host, self.host_override)
     else:
       logging.info("Server: %s", self.host)
def upload.AbstractRpcServer.__init__ (self, host, auth_function, host_override = None, extra_headers = {}, save_cookies = False)
Creates a new HttpRpcServer.
Args:
  host: The host to send requests to.
  auth_function: A function that takes no arguments and returns an
(email, password) tuple when called. Will be called if authentication
is required.
  host_override: The host header to send to the server (defaults to host).
  extra_headers: A dict of extra headers to append to every request.
  save_cookies: If True, save the authentication cookies to local disk.
If False, use an in-memory cookiejar instead.  Subclasses must
implement this functionality.  Defaults to False.
Definition at line 128 of file upload.py.
References upload.AbstractRpcServer._GetOpener(), upload.AbstractRpcServer.auth_function, upload.AbstractRpcServer.authenticated, upload.AbstractRpcServer.extra_headers, upload.AbstractRpcServer.host, upload.AbstractRpcServer.host_override, upload.AbstractRpcServer.opener, and upload.AbstractRpcServer.save_cookies.
                save_cookies=False):
     """Creates a new HttpRpcServer.
     Args:
       host: The host to send requests to.
       auth_function: A function that takes no arguments and returns an
         (email, password) tuple when called. Will be called if authentication
         is required.
       host_override: The host header to send to the server (defaults to host).
       extra_headers: A dict of extra headers to append to every request.
       save_cookies: If True, save the authentication cookies to local disk.
         If False, use an in-memory cookiejar instead.  Subclasses must
         implement this functionality.  Defaults to False.
     """
     self.host = host
     self.host_override = host_override
     self.auth_function = auth_function
     self.authenticated = False
     self.extra_headers = extra_headers
     self.save_cookies = save_cookies
     self.opener = self._GetOpener()
     if self.host_override:
       logging.info("Server: %s; Host: %s", self.host, self.host_override)
     else:
       logging.info("Server: %s", self.host)
def upload.AbstractRpcServer.__init__ (self, host, auth_function, host_override = None, extra_headers = {}, save_cookies = False)
Creates a new HttpRpcServer.
Args:
  host: The host to send requests to.
  auth_function: A function that takes no arguments and returns an
(email, password) tuple when called. Will be called if authentication
is required.
  host_override: The host header to send to the server (defaults to host).
  extra_headers: A dict of extra headers to append to every request.
  save_cookies: If True, save the authentication cookies to local disk.
If False, use an in-memory cookiejar instead.  Subclasses must
implement this functionality.  Defaults to False.
Definition at line 128 of file upload.py.
References upload.AbstractRpcServer._GetOpener(), upload.AbstractRpcServer.auth_function, upload.AbstractRpcServer.authenticated, upload.AbstractRpcServer.extra_headers, upload.AbstractRpcServer.host, upload.AbstractRpcServer.host_override, upload.AbstractRpcServer.opener, and upload.AbstractRpcServer.save_cookies.
                save_cookies=False):
     """Creates a new HttpRpcServer.
     Args:
       host: The host to send requests to.
       auth_function: A function that takes no arguments and returns an
         (email, password) tuple when called. Will be called if authentication
         is required.
       host_override: The host header to send to the server (defaults to host).
       extra_headers: A dict of extra headers to append to every request.
       save_cookies: If True, save the authentication cookies to local disk.
         If False, use an in-memory cookiejar instead.  Subclasses must
         implement this functionality.  Defaults to False.
     """
     self.host = host
     self.host_override = host_override
     self.auth_function = auth_function
     self.authenticated = False
     self.extra_headers = extra_headers
     self.save_cookies = save_cookies
     self.opener = self._GetOpener()
     if self.host_override:
       logging.info("Server: %s; Host: %s", self.host, self.host_override)
     else:
       logging.info("Server: %s", self.host)
def upload.AbstractRpcServer.__init__ (self, host, auth_function, host_override = None, extra_headers = {}, save_cookies = False)
Creates a new HttpRpcServer.
Args:
  host: The host to send requests to.
  auth_function: A function that takes no arguments and returns an
(email, password) tuple when called. Will be called if authentication
is required.
  host_override: The host header to send to the server (defaults to host).
  extra_headers: A dict of extra headers to append to every request.
  save_cookies: If True, save the authentication cookies to local disk.
If False, use an in-memory cookiejar instead.  Subclasses must
implement this functionality.  Defaults to False.
Definition at line 128 of file upload.py.
References upload.AbstractRpcServer._GetOpener(), upload.AbstractRpcServer.auth_function, upload.AbstractRpcServer.authenticated, upload.AbstractRpcServer.extra_headers, upload.AbstractRpcServer.host, upload.AbstractRpcServer.host_override, upload.AbstractRpcServer.opener, and upload.AbstractRpcServer.save_cookies.
                save_cookies=False):
     """Creates a new HttpRpcServer.
     Args:
       host: The host to send requests to.
       auth_function: A function that takes no arguments and returns an
         (email, password) tuple when called. Will be called if authentication
         is required.
       host_override: The host header to send to the server (defaults to host).
       extra_headers: A dict of extra headers to append to every request.
       save_cookies: If True, save the authentication cookies to local disk.
         If False, use an in-memory cookiejar instead.  Subclasses must
         implement this functionality.  Defaults to False.
     """
     self.host = host
     self.host_override = host_override
     self.auth_function = auth_function
     self.authenticated = False
     self.extra_headers = extra_headers
     self.save_cookies = save_cookies
     self.opener = self._GetOpener()
     if self.host_override:
       logging.info("Server: %s; Host: %s", self.host, self.host_override)
     else:
       logging.info("Server: %s", self.host)
def upload.AbstractRpcServer.__init__ (self, host, auth_function, host_override = None, extra_headers = {}, save_cookies = False)
Creates a new HttpRpcServer.
Args:
  host: The host to send requests to.
  auth_function: A function that takes no arguments and returns an
(email, password) tuple when called. Will be called if authentication
is required.
  host_override: The host header to send to the server (defaults to host).
  extra_headers: A dict of extra headers to append to every request.
  save_cookies: If True, save the authentication cookies to local disk.
If False, use an in-memory cookiejar instead.  Subclasses must
implement this functionality.  Defaults to False.
Definition at line 128 of file upload.py.
References upload.AbstractRpcServer._GetOpener(), upload.AbstractRpcServer.auth_function, upload.AbstractRpcServer.authenticated, upload.AbstractRpcServer.extra_headers, upload.AbstractRpcServer.host, upload.AbstractRpcServer.host_override, upload.AbstractRpcServer.opener, and upload.AbstractRpcServer.save_cookies.
                save_cookies=False):
     """Creates a new HttpRpcServer.
     Args:
       host: The host to send requests to.
       auth_function: A function that takes no arguments and returns an
         (email, password) tuple when called. Will be called if authentication
         is required.
       host_override: The host header to send to the server (defaults to host).
       extra_headers: A dict of extra headers to append to every request.
       save_cookies: If True, save the authentication cookies to local disk.
         If False, use an in-memory cookiejar instead.  Subclasses must
         implement this functionality.  Defaults to False.
     """
     self.host = host
     self.host_override = host_override
     self.auth_function = auth_function
     self.authenticated = False
     self.extra_headers = extra_headers
     self.save_cookies = save_cookies
     self.opener = self._GetOpener()
     if self.host_override:
       logging.info("Server: %s; Host: %s", self.host, self.host_override)
     else:
       logging.info("Server: %s", self.host)
Member Function Documentation
def upload.AbstractRpcServer._Authenticate (self) private
Authenticates the user.
The authentication process works as follows:
 1) We get a username and password from the user
 2) We use ClientLogin to obtain an AUTH token for the user
(see http://code.google.com/apis/accounts/AuthForInstalledApps.html).
 3) We pass the auth token to /_ah/login on the server to obtain an
authentication cookie. If login was successful, it tries to redirect
us to the URL we provided.
If we attempt to access the upload API without first obtaining an
authentication cookie, it returns a 401 response and directs us to
authenticate ourselves with ClientLogin.
Definition at line 239 of file upload.py.
References upload.AbstractRpcServer._GetAuthCookie(), upload.AbstractRpcServer._GetAuthToken(), upload.AbstractRpcServer.auth_function, folly::gen.range(), and upload.AbstractRpcServer.Send().
Referenced by upload.AbstractRpcServer._Authenticate(), and upload.AbstractRpcServer.Send().
   def _Authenticate(self):
     """Authenticates the user.
     The authentication process works as follows:
      1) We get a username and password from the user
      2) We use ClientLogin to obtain an AUTH token for the user
         (see http://code.google.com/apis/accounts/AuthForInstalledApps.html).
      3) We pass the auth token to /_ah/login on the server to obtain an
         authentication cookie. If login was successful, it tries to redirect
         us to the URL we provided.
     If we attempt to access the upload API without first obtaining an
     authentication cookie, it returns a 401 response and directs us to
     authenticate ourselves with ClientLogin.
     """
     for i in range(3):
       credentials = self.auth_function()
       try:
         auth_token = self._GetAuthToken(credentials[0], credentials[1])
       except ClientLoginError, e:
         if e.reason == "BadAuthentication":
           print >>sys.stderr, "Invalid username or password."
           continue
         if e.reason == "CaptchaRequired":
           print >>sys.stderr, (
               "Please go to\n"
               "https://www.google.com/accounts/DisplayUnlockCaptcha\n"
               "and verify you are a human.  Then try again.")
           break
         if e.reason == "NotVerified":
           print >>sys.stderr, "Account not verified."
           break
         if e.reason == "TermsNotAgreed":
           print >>sys.stderr, "User has not agreed to TOS."
           break
         if e.reason == "AccountDeleted":
           print >>sys.stderr, "The user account has been deleted."
           break
         if e.reason == "AccountDisabled":
           print >>sys.stderr, "The user account has been disabled."
           break
         if e.reason == "ServiceDisabled":
           print >>sys.stderr, ("The user's access to the service has been "
                                "disabled.")
           break
         if e.reason == "ServiceUnavailable":
           print >>sys.stderr, "The service is not available; try again later."
           break
         raise
       self._GetAuthCookie(auth_token)
       return
def upload.AbstractRpcServer._Authenticate (self) private
Authenticates the user.
The authentication process works as follows:
 1) We get a username and password from the user
 2) We use ClientLogin to obtain an AUTH token for the user
(see http://code.google.com/apis/accounts/AuthForInstalledApps.html).
 3) We pass the auth token to /_ah/login on the server to obtain an
authentication cookie. If login was successful, it tries to redirect
us to the URL we provided.
If we attempt to access the upload API without first obtaining an
authentication cookie, it returns a 401 response and directs us to
authenticate ourselves with ClientLogin.
Definition at line 239 of file upload.py.
References upload.AbstractRpcServer._Authenticate(), upload.AbstractRpcServer._GetAuthCookie(), upload.AbstractRpcServer._GetAuthToken(), upload.AbstractRpcServer.auth_function, folly::gen.range(), and upload.AbstractRpcServer.Send().
   def _Authenticate(self):
     """Authenticates the user.
     The authentication process works as follows:
      1) We get a username and password from the user
      2) We use ClientLogin to obtain an AUTH token for the user
         (see http://code.google.com/apis/accounts/AuthForInstalledApps.html).
      3) We pass the auth token to /_ah/login on the server to obtain an
         authentication cookie. If login was successful, it tries to redirect
         us to the URL we provided.
     If we attempt to access the upload API without first obtaining an
     authentication cookie, it returns a 401 response and directs us to
     authenticate ourselves with ClientLogin.
     """
     for i in range(3):
       credentials = self.auth_function()
       try:
         auth_token = self._GetAuthToken(credentials[0], credentials[1])
       except ClientLoginError, e:
         if e.reason == "BadAuthentication":
           print >>sys.stderr, "Invalid username or password."
           continue
         if e.reason == "CaptchaRequired":
           print >>sys.stderr, (
               "Please go to\n"
               "https://www.google.com/accounts/DisplayUnlockCaptcha\n"
               "and verify you are a human.  Then try again.")
           break
         if e.reason == "NotVerified":
           print >>sys.stderr, "Account not verified."
           break
         if e.reason == "TermsNotAgreed":
           print >>sys.stderr, "User has not agreed to TOS."
           break
         if e.reason == "AccountDeleted":
           print >>sys.stderr, "The user account has been deleted."
           break
         if e.reason == "AccountDisabled":
           print >>sys.stderr, "The user account has been disabled."
           break
         if e.reason == "ServiceDisabled":
           print >>sys.stderr, ("The user's access to the service has been "
                                "disabled.")
           break
         if e.reason == "ServiceUnavailable":
           print >>sys.stderr, "The service is not available; try again later."
           break
         raise
       self._GetAuthCookie(auth_token)
       return
def upload.AbstractRpcServer._Authenticate (self) private
Authenticates the user.
The authentication process works as follows:
 1) We get a username and password from the user
 2) We use ClientLogin to obtain an AUTH token for the user
(see http://code.google.com/apis/accounts/AuthForInstalledApps.html).
 3) We pass the auth token to /_ah/login on the server to obtain an
authentication cookie. If login was successful, it tries to redirect
us to the URL we provided.
If we attempt to access the upload API without first obtaining an
authentication cookie, it returns a 401 response and directs us to
authenticate ourselves with ClientLogin.
Definition at line 239 of file upload.py.
References upload.AbstractRpcServer._Authenticate(), upload.AbstractRpcServer._GetAuthCookie(), upload.AbstractRpcServer._GetAuthToken(), upload.AbstractRpcServer.auth_function, folly::gen.range(), and upload.AbstractRpcServer.Send().
   def _Authenticate(self):
     """Authenticates the user.
     The authentication process works as follows:
      1) We get a username and password from the user
      2) We use ClientLogin to obtain an AUTH token for the user
         (see http://code.google.com/apis/accounts/AuthForInstalledApps.html).
      3) We pass the auth token to /_ah/login on the server to obtain an
         authentication cookie. If login was successful, it tries to redirect
         us to the URL we provided.
     If we attempt to access the upload API without first obtaining an
     authentication cookie, it returns a 401 response and directs us to
     authenticate ourselves with ClientLogin.
     """
     for i in range(3):
       credentials = self.auth_function()
       try:
         auth_token = self._GetAuthToken(credentials[0], credentials[1])
       except ClientLoginError, e:
         if e.reason == "BadAuthentication":
           print >>sys.stderr, "Invalid username or password."
           continue
         if e.reason == "CaptchaRequired":
           print >>sys.stderr, (
               "Please go to\n"
               "https://www.google.com/accounts/DisplayUnlockCaptcha\n"
               "and verify you are a human.  Then try again.")
           break
         if e.reason == "NotVerified":
           print >>sys.stderr, "Account not verified."
           break
         if e.reason == "TermsNotAgreed":
           print >>sys.stderr, "User has not agreed to TOS."
           break
         if e.reason == "AccountDeleted":
           print >>sys.stderr, "The user account has been deleted."
           break
         if e.reason == "AccountDisabled":
           print >>sys.stderr, "The user account has been disabled."
           break
         if e.reason == "ServiceDisabled":
           print >>sys.stderr, ("The user's access to the service has been "
                                "disabled.")
           break
         if e.reason == "ServiceUnavailable":
           print >>sys.stderr, "The service is not available; try again later."
           break
         raise
       self._GetAuthCookie(auth_token)
       return
def upload.AbstractRpcServer._Authenticate (self) private
Authenticates the user.
The authentication process works as follows:
 1) We get a username and password from the user
 2) We use ClientLogin to obtain an AUTH token for the user
(see http://code.google.com/apis/accounts/AuthForInstalledApps.html).
 3) We pass the auth token to /_ah/login on the server to obtain an
authentication cookie. If login was successful, it tries to redirect
us to the URL we provided.
If we attempt to access the upload API without first obtaining an
authentication cookie, it returns a 401 response and directs us to
authenticate ourselves with ClientLogin.
Definition at line 239 of file upload.py.
References upload.AbstractRpcServer._Authenticate(), upload.AbstractRpcServer._GetAuthCookie(), upload.AbstractRpcServer._GetAuthToken(), upload.AbstractRpcServer.auth_function, folly::gen.range(), and upload.AbstractRpcServer.Send().
   def _Authenticate(self):
     """Authenticates the user.
     The authentication process works as follows:
      1) We get a username and password from the user
      2) We use ClientLogin to obtain an AUTH token for the user
         (see http://code.google.com/apis/accounts/AuthForInstalledApps.html).
      3) We pass the auth token to /_ah/login on the server to obtain an
         authentication cookie. If login was successful, it tries to redirect
         us to the URL we provided.
     If we attempt to access the upload API without first obtaining an
     authentication cookie, it returns a 401 response and directs us to
     authenticate ourselves with ClientLogin.
     """
     for i in range(3):
       credentials = self.auth_function()
       try:
         auth_token = self._GetAuthToken(credentials[0], credentials[1])
       except ClientLoginError, e:
         if e.reason == "BadAuthentication":
           print >>sys.stderr, "Invalid username or password."
           continue
         if e.reason == "CaptchaRequired":
           print >>sys.stderr, (
               "Please go to\n"
               "https://www.google.com/accounts/DisplayUnlockCaptcha\n"
               "and verify you are a human.  Then try again.")
           break
         if e.reason == "NotVerified":
           print >>sys.stderr, "Account not verified."
           break
         if e.reason == "TermsNotAgreed":
           print >>sys.stderr, "User has not agreed to TOS."
           break
         if e.reason == "AccountDeleted":
           print >>sys.stderr, "The user account has been deleted."
           break
         if e.reason == "AccountDisabled":
           print >>sys.stderr, "The user account has been disabled."
           break
         if e.reason == "ServiceDisabled":
           print >>sys.stderr, ("The user's access to the service has been "
                                "disabled.")
           break
         if e.reason == "ServiceUnavailable":
           print >>sys.stderr, "The service is not available; try again later."
           break
         raise
       self._GetAuthCookie(auth_token)
       return
def upload.AbstractRpcServer._Authenticate (self) private
Authenticates the user.
The authentication process works as follows:
 1) We get a username and password from the user
 2) We use ClientLogin to obtain an AUTH token for the user
(see http://code.google.com/apis/accounts/AuthForInstalledApps.html).
 3) We pass the auth token to /_ah/login on the server to obtain an
authentication cookie. If login was successful, it tries to redirect
us to the URL we provided.
If we attempt to access the upload API without first obtaining an
authentication cookie, it returns a 401 response and directs us to
authenticate ourselves with ClientLogin.
Definition at line 239 of file upload.py.
References upload.AbstractRpcServer._Authenticate(), upload.AbstractRpcServer._GetAuthCookie(), upload.AbstractRpcServer._GetAuthToken(), upload.AbstractRpcServer.auth_function, folly::gen.range(), and upload.AbstractRpcServer.Send().
   def _Authenticate(self):
     """Authenticates the user.
     The authentication process works as follows:
      1) We get a username and password from the user
      2) We use ClientLogin to obtain an AUTH token for the user
         (see http://code.google.com/apis/accounts/AuthForInstalledApps.html).
      3) We pass the auth token to /_ah/login on the server to obtain an
         authentication cookie. If login was successful, it tries to redirect
         us to the URL we provided.
     If we attempt to access the upload API without first obtaining an
     authentication cookie, it returns a 401 response and directs us to
     authenticate ourselves with ClientLogin.
     """
     for i in range(3):
       credentials = self.auth_function()
       try:
         auth_token = self._GetAuthToken(credentials[0], credentials[1])
       except ClientLoginError, e:
         if e.reason == "BadAuthentication":
           print >>sys.stderr, "Invalid username or password."
           continue
         if e.reason == "CaptchaRequired":
           print >>sys.stderr, (
               "Please go to\n"
               "https://www.google.com/accounts/DisplayUnlockCaptcha\n"
               "and verify you are a human.  Then try again.")
           break
         if e.reason == "NotVerified":
           print >>sys.stderr, "Account not verified."
           break
         if e.reason == "TermsNotAgreed":
           print >>sys.stderr, "User has not agreed to TOS."
           break
         if e.reason == "AccountDeleted":
           print >>sys.stderr, "The user account has been deleted."
           break
         if e.reason == "AccountDisabled":
           print >>sys.stderr, "The user account has been disabled."
           break
         if e.reason == "ServiceDisabled":
           print >>sys.stderr, ("The user's access to the service has been "
                                "disabled.")
           break
         if e.reason == "ServiceUnavailable":
           print >>sys.stderr, "The service is not available; try again later."
           break
         raise
       self._GetAuthCookie(auth_token)
       return
def upload.AbstractRpcServer._Authenticate (self) private
Authenticates the user.
The authentication process works as follows:
 1) We get a username and password from the user
 2) We use ClientLogin to obtain an AUTH token for the user
(see http://code.google.com/apis/accounts/AuthForInstalledApps.html).
 3) We pass the auth token to /_ah/login on the server to obtain an
authentication cookie. If login was successful, it tries to redirect
us to the URL we provided.
If we attempt to access the upload API without first obtaining an
authentication cookie, it returns a 401 response and directs us to
authenticate ourselves with ClientLogin.
Definition at line 239 of file upload.py.
References upload.AbstractRpcServer._Authenticate(), upload.AbstractRpcServer._GetAuthCookie(), upload.AbstractRpcServer._GetAuthToken(), upload.AbstractRpcServer.auth_function, folly::gen.range(), and upload.AbstractRpcServer.Send().
   def _Authenticate(self):
     """Authenticates the user.
     The authentication process works as follows:
      1) We get a username and password from the user
      2) We use ClientLogin to obtain an AUTH token for the user
         (see http://code.google.com/apis/accounts/AuthForInstalledApps.html).
      3) We pass the auth token to /_ah/login on the server to obtain an
         authentication cookie. If login was successful, it tries to redirect
         us to the URL we provided.
     If we attempt to access the upload API without first obtaining an
     authentication cookie, it returns a 401 response and directs us to
     authenticate ourselves with ClientLogin.
     """
     for i in range(3):
       credentials = self.auth_function()
       try:
         auth_token = self._GetAuthToken(credentials[0], credentials[1])
       except ClientLoginError, e:
         if e.reason == "BadAuthentication":
           print >>sys.stderr, "Invalid username or password."
           continue
         if e.reason == "CaptchaRequired":
           print >>sys.stderr, (
               "Please go to\n"
               "https://www.google.com/accounts/DisplayUnlockCaptcha\n"
               "and verify you are a human.  Then try again.")
           break
         if e.reason == "NotVerified":
           print >>sys.stderr, "Account not verified."
           break
         if e.reason == "TermsNotAgreed":
           print >>sys.stderr, "User has not agreed to TOS."
           break
         if e.reason == "AccountDeleted":
           print >>sys.stderr, "The user account has been deleted."
           break
         if e.reason == "AccountDisabled":
           print >>sys.stderr, "The user account has been disabled."
           break
         if e.reason == "ServiceDisabled":
           print >>sys.stderr, ("The user's access to the service has been "
                                "disabled.")
           break
         if e.reason == "ServiceUnavailable":
           print >>sys.stderr, "The service is not available; try again later."
           break
         raise
       self._GetAuthCookie(auth_token)
       return
def upload.AbstractRpcServer._CreateRequest (self, url, data = None) private
Creates a new urllib request.
Definition at line 162 of file upload.py.
References upload.AbstractRpcServer._CreateRequest(), and upload.AbstractRpcServer.host_override.
   def _CreateRequest(self, url, data=None):
     """Creates a new urllib request."""
     logging.debug("Creating request for: '%s' with payload:\n%s", url, data)
     req = urllib2.Request(url, data=data)
     if self.host_override:
       req.add_header("Host", self.host_override)
     for key, value in self.extra_headers.iteritems():
       req.add_header(key, value)
     return req
def upload.AbstractRpcServer._CreateRequest (self, url, data = None) private
Creates a new urllib request.
Definition at line 162 of file upload.py.
References upload.AbstractRpcServer._CreateRequest(), and upload.AbstractRpcServer.host_override.
   def _CreateRequest(self, url, data=None):
     """Creates a new urllib request."""
     logging.debug("Creating request for: '%s' with payload:\n%s", url, data)
     req = urllib2.Request(url, data=data)
     if self.host_override:
       req.add_header("Host", self.host_override)
     for key, value in self.extra_headers.iteritems():
       req.add_header(key, value)
     return req
def upload.AbstractRpcServer._CreateRequest (self, url, data = None) private
Creates a new urllib request.
Definition at line 162 of file upload.py.
References upload.AbstractRpcServer._CreateRequest(), and upload.AbstractRpcServer.host_override.
   def _CreateRequest(self, url, data=None):
     """Creates a new urllib request."""
     logging.debug("Creating request for: '%s' with payload:\n%s", url, data)
     req = urllib2.Request(url, data=data)
     if self.host_override:
       req.add_header("Host", self.host_override)
     for key, value in self.extra_headers.iteritems():
       req.add_header(key, value)
     return req
def upload.AbstractRpcServer._CreateRequest (self, url, data = None) private
Creates a new urllib request.
Definition at line 162 of file upload.py.
References upload.AbstractRpcServer.host_override.
Referenced by upload.AbstractRpcServer._CreateRequest(), upload.AbstractRpcServer._GetAuthCookie(), upload.AbstractRpcServer._GetAuthToken(), and upload.AbstractRpcServer.Send().
   def _CreateRequest(self, url, data=None):
     """Creates a new urllib request."""
     logging.debug("Creating request for: '%s' with payload:\n%s", url, data)
     req = urllib2.Request(url, data=data)
     if self.host_override:
       req.add_header("Host", self.host_override)
     for key, value in self.extra_headers.iteritems():
       req.add_header(key, value)
     return req
def upload.AbstractRpcServer._CreateRequest (self, url, data = None) private
Creates a new urllib request.
Definition at line 162 of file upload.py.
References upload.AbstractRpcServer._CreateRequest(), and upload.AbstractRpcServer.host_override.
   def _CreateRequest(self, url, data=None):
     """Creates a new urllib request."""
     logging.debug("Creating request for: '%s' with payload:\n%s", url, data)
     req = urllib2.Request(url, data=data)
     if self.host_override:
       req.add_header("Host", self.host_override)
     for key, value in self.extra_headers.iteritems():
       req.add_header(key, value)
     return req
def upload.AbstractRpcServer._CreateRequest (self, url, data = None) private
Creates a new urllib request.
Definition at line 162 of file upload.py.
References upload.AbstractRpcServer._CreateRequest(), and upload.AbstractRpcServer.host_override.
   def _CreateRequest(self, url, data=None):
     """Creates a new urllib request."""
     logging.debug("Creating request for: '%s' with payload:\n%s", url, data)
     req = urllib2.Request(url, data=data)
     if self.host_override:
       req.add_header("Host", self.host_override)
     for key, value in self.extra_headers.iteritems():
       req.add_header(key, value)
     return req
def upload.AbstractRpcServer._GetAuthCookie (self, auth_token) private
Fetches authentication cookies for an authentication token.
Args:
  auth_token: The authentication token returned by ClientLogin.
Raises:
  HTTPError: If there was an error fetching the authentication cookies.
Definition at line 215 of file upload.py.
References upload.AbstractRpcServer._CreateRequest(), upload.AbstractRpcServer._GetAuthCookie(), upload.AbstractRpcServer.authenticated, and upload.AbstractRpcServer.host.
   def _GetAuthCookie(self, auth_token):
     """Fetches authentication cookies for an authentication token.
     Args:
       auth_token: The authentication token returned by ClientLogin.
     Raises:
       HTTPError: If there was an error fetching the authentication cookies.
     """
     # This is a dummy value to allow us to identify when we're successful.
     continue_location = "http://localhost/"
     args = {"continue": continue_location, "auth": auth_token}
     req = self._CreateRequest("http://%s/_ah/login?%s" %
                               (self.host, urllib.urlencode(args)))
     try:
       response = self.opener.open(req)
     except urllib2.HTTPError, e:
       response = e
     if (response.code != 302 or
         response.info()["location"] != continue_location):
       raise urllib2.HTTPError(req.get_full_url(), response.code, response.msg,
                               response.headers, response.fp)
     self.authenticated = True
def upload.AbstractRpcServer._GetAuthCookie (self, auth_token) private
Fetches authentication cookies for an authentication token.
Args:
  auth_token: The authentication token returned by ClientLogin.
Raises:
  HTTPError: If there was an error fetching the authentication cookies.
Definition at line 215 of file upload.py.
References upload.AbstractRpcServer._CreateRequest(), upload.AbstractRpcServer._GetAuthCookie(), upload.AbstractRpcServer.authenticated, and upload.AbstractRpcServer.host.
   def _GetAuthCookie(self, auth_token):
     """Fetches authentication cookies for an authentication token.
     Args:
       auth_token: The authentication token returned by ClientLogin.
     Raises:
       HTTPError: If there was an error fetching the authentication cookies.
     """
     # This is a dummy value to allow us to identify when we're successful.
     continue_location = "http://localhost/"
     args = {"continue": continue_location, "auth": auth_token}
     req = self._CreateRequest("http://%s/_ah/login?%s" %
                               (self.host, urllib.urlencode(args)))
     try:
       response = self.opener.open(req)
     except urllib2.HTTPError, e:
       response = e
     if (response.code != 302 or
         response.info()["location"] != continue_location):
       raise urllib2.HTTPError(req.get_full_url(), response.code, response.msg,
                               response.headers, response.fp)
     self.authenticated = True
def upload.AbstractRpcServer._GetAuthCookie (self, auth_token) private
Fetches authentication cookies for an authentication token.
Args:
  auth_token: The authentication token returned by ClientLogin.
Raises:
  HTTPError: If there was an error fetching the authentication cookies.
Definition at line 215 of file upload.py.
References upload.AbstractRpcServer._CreateRequest(), upload.AbstractRpcServer._GetAuthCookie(), upload.AbstractRpcServer.authenticated, and upload.AbstractRpcServer.host.
   def _GetAuthCookie(self, auth_token):
     """Fetches authentication cookies for an authentication token.
     Args:
       auth_token: The authentication token returned by ClientLogin.
     Raises:
       HTTPError: If there was an error fetching the authentication cookies.
     """
     # This is a dummy value to allow us to identify when we're successful.
     continue_location = "http://localhost/"
     args = {"continue": continue_location, "auth": auth_token}
     req = self._CreateRequest("http://%s/_ah/login?%s" %
                               (self.host, urllib.urlencode(args)))
     try:
       response = self.opener.open(req)
     except urllib2.HTTPError, e:
       response = e
     if (response.code != 302 or
         response.info()["location"] != continue_location):
       raise urllib2.HTTPError(req.get_full_url(), response.code, response.msg,
                               response.headers, response.fp)
     self.authenticated = True
def upload.AbstractRpcServer._GetAuthCookie (self, auth_token) private
Fetches authentication cookies for an authentication token.
Args:
  auth_token: The authentication token returned by ClientLogin.
Raises:
  HTTPError: If there was an error fetching the authentication cookies.
Definition at line 215 of file upload.py.
References upload.AbstractRpcServer._CreateRequest(), upload.AbstractRpcServer._GetAuthCookie(), upload.AbstractRpcServer.authenticated, and upload.AbstractRpcServer.host.
   def _GetAuthCookie(self, auth_token):
     """Fetches authentication cookies for an authentication token.
     Args:
       auth_token: The authentication token returned by ClientLogin.
     Raises:
       HTTPError: If there was an error fetching the authentication cookies.
     """
     # This is a dummy value to allow us to identify when we're successful.
     continue_location = "http://localhost/"
     args = {"continue": continue_location, "auth": auth_token}
     req = self._CreateRequest("http://%s/_ah/login?%s" %
                               (self.host, urllib.urlencode(args)))
     try:
       response = self.opener.open(req)
     except urllib2.HTTPError, e:
       response = e
     if (response.code != 302 or
         response.info()["location"] != continue_location):
       raise urllib2.HTTPError(req.get_full_url(), response.code, response.msg,
                               response.headers, response.fp)
     self.authenticated = True
def upload.AbstractRpcServer._GetAuthCookie (self, auth_token) private
Fetches authentication cookies for an authentication token.
Args:
  auth_token: The authentication token returned by ClientLogin.
Raises:
  HTTPError: If there was an error fetching the authentication cookies.
Definition at line 215 of file upload.py.
References upload.AbstractRpcServer._CreateRequest(), upload.AbstractRpcServer.authenticated, and upload.AbstractRpcServer.host.
Referenced by upload.AbstractRpcServer._Authenticate(), and upload.AbstractRpcServer._GetAuthCookie().
   def _GetAuthCookie(self, auth_token):
     """Fetches authentication cookies for an authentication token.
     Args:
       auth_token: The authentication token returned by ClientLogin.
     Raises:
       HTTPError: If there was an error fetching the authentication cookies.
     """
     # This is a dummy value to allow us to identify when we're successful.
     continue_location = "http://localhost/"
     args = {"continue": continue_location, "auth": auth_token}
     req = self._CreateRequest("http://%s/_ah/login?%s" %
                               (self.host, urllib.urlencode(args)))
     try:
       response = self.opener.open(req)
     except urllib2.HTTPError, e:
       response = e
     if (response.code != 302 or
         response.info()["location"] != continue_location):
       raise urllib2.HTTPError(req.get_full_url(), response.code, response.msg,
                               response.headers, response.fp)
     self.authenticated = True
def upload.AbstractRpcServer._GetAuthCookie (self, auth_token) private
Fetches authentication cookies for an authentication token.
Args:
  auth_token: The authentication token returned by ClientLogin.
Raises:
  HTTPError: If there was an error fetching the authentication cookies.
Definition at line 215 of file upload.py.
References upload.AbstractRpcServer._CreateRequest(), upload.AbstractRpcServer._GetAuthCookie(), upload.AbstractRpcServer.authenticated, and upload.AbstractRpcServer.host.
   def _GetAuthCookie(self, auth_token):
     """Fetches authentication cookies for an authentication token.
     Args:
       auth_token: The authentication token returned by ClientLogin.
     Raises:
       HTTPError: If there was an error fetching the authentication cookies.
     """
     # This is a dummy value to allow us to identify when we're successful.
     continue_location = "http://localhost/"
     args = {"continue": continue_location, "auth": auth_token}
     req = self._CreateRequest("http://%s/_ah/login?%s" %
                               (self.host, urllib.urlencode(args)))
     try:
       response = self.opener.open(req)
     except urllib2.HTTPError, e:
       response = e
     if (response.code != 302 or
         response.info()["location"] != continue_location):
       raise urllib2.HTTPError(req.get_full_url(), response.code, response.msg,
                               response.headers, response.fp)
     self.authenticated = True
def upload.AbstractRpcServer._GetAuthToken (self, email, password) private
Uses ClientLogin to authenticate the user, returning an auth token.
Args:
  email:    The user's email address
  password: The user's password
Raises:
  ClientLoginError: If there was an error authenticating with ClientLogin.
  HTTPError: If there was some other form of HTTP error.
Returns:
  The authentication token returned by ClientLogin.
Definition at line 172 of file upload.py.
References upload.AbstractRpcServer._CreateRequest(), and upload.AbstractRpcServer._GetAuthToken().
   def _GetAuthToken(self, email, password):
     """Uses ClientLogin to authenticate the user, returning an auth token.
     Args:
       email:    The user's email address
       password: The user's password
     Raises:
       ClientLoginError: If there was an error authenticating with ClientLogin.
       HTTPError: If there was some other form of HTTP error.
     Returns:
       The authentication token returned by ClientLogin.
     """
     account_type = "GOOGLE"
     if self.host.endswith(".google.com"):
       # Needed for use inside Google.
       account_type = "HOSTED"
     req = self._CreateRequest(
         url="https://www.google.com/accounts/ClientLogin",
         data=urllib.urlencode({
             "Email": email,
             "Passwd": password,
             "service": "ah",
             "source": "rietveld-codereview-upload",
             "accountType": account_type,
         }),
     )
     try:
       response = self.opener.open(req)
       response_body = response.read()
       response_dict = dict(x.split("=")
                            for x in response_body.split("\n") if x)
       return response_dict["Auth"]
     except urllib2.HTTPError, e:
       if e.code == 403:
         body = e.read()
         response_dict = dict(x.split("=", 1) for x in body.split("\n") if x)
         raise ClientLoginError(req.get_full_url(), e.code, e.msg,
                                e.headers, response_dict)
       else:
         raise
def upload.AbstractRpcServer._GetAuthToken (self, email, password) private
Uses ClientLogin to authenticate the user, returning an auth token.
Args:
  email:    The user's email address
  password: The user's password
Raises:
  ClientLoginError: If there was an error authenticating with ClientLogin.
  HTTPError: If there was some other form of HTTP error.
Returns:
  The authentication token returned by ClientLogin.
Definition at line 172 of file upload.py.
References upload.AbstractRpcServer._CreateRequest(), and upload.AbstractRpcServer._GetAuthToken().
   def _GetAuthToken(self, email, password):
     """Uses ClientLogin to authenticate the user, returning an auth token.
     Args:
       email:    The user's email address
       password: The user's password
     Raises:
       ClientLoginError: If there was an error authenticating with ClientLogin.
       HTTPError: If there was some other form of HTTP error.
     Returns:
       The authentication token returned by ClientLogin.
     """
     account_type = "GOOGLE"
     if self.host.endswith(".google.com"):
       # Needed for use inside Google.
       account_type = "HOSTED"
     req = self._CreateRequest(
         url="https://www.google.com/accounts/ClientLogin",
         data=urllib.urlencode({
             "Email": email,
             "Passwd": password,
             "service": "ah",
             "source": "rietveld-codereview-upload",
             "accountType": account_type,
         }),
     )
     try:
       response = self.opener.open(req)
       response_body = response.read()
       response_dict = dict(x.split("=")
                            for x in response_body.split("\n") if x)
       return response_dict["Auth"]
     except urllib2.HTTPError, e:
       if e.code == 403:
         body = e.read()
         response_dict = dict(x.split("=", 1) for x in body.split("\n") if x)
         raise ClientLoginError(req.get_full_url(), e.code, e.msg,
                                e.headers, response_dict)
       else:
         raise
def upload.AbstractRpcServer._GetAuthToken (self, email, password) private
Uses ClientLogin to authenticate the user, returning an auth token.
Args:
  email:    The user's email address
  password: The user's password
Raises:
  ClientLoginError: If there was an error authenticating with ClientLogin.
  HTTPError: If there was some other form of HTTP error.
Returns:
  The authentication token returned by ClientLogin.
Definition at line 172 of file upload.py.
References upload.AbstractRpcServer._CreateRequest().
Referenced by upload.AbstractRpcServer._Authenticate(), and upload.AbstractRpcServer._GetAuthToken().
   def _GetAuthToken(self, email, password):
     """Uses ClientLogin to authenticate the user, returning an auth token.
     Args:
       email:    The user's email address
       password: The user's password
     Raises:
       ClientLoginError: If there was an error authenticating with ClientLogin.
       HTTPError: If there was some other form of HTTP error.
     Returns:
       The authentication token returned by ClientLogin.
     """
     account_type = "GOOGLE"
     if self.host.endswith(".google.com"):
       # Needed for use inside Google.
       account_type = "HOSTED"
     req = self._CreateRequest(
         url="https://www.google.com/accounts/ClientLogin",
         data=urllib.urlencode({
             "Email": email,
             "Passwd": password,
             "service": "ah",
             "source": "rietveld-codereview-upload",
             "accountType": account_type,
         }),
     )
     try:
       response = self.opener.open(req)
       response_body = response.read()
       response_dict = dict(x.split("=")
                            for x in response_body.split("\n") if x)
       return response_dict["Auth"]
     except urllib2.HTTPError, e:
       if e.code == 403:
         body = e.read()
         response_dict = dict(x.split("=", 1) for x in body.split("\n") if x)
         raise ClientLoginError(req.get_full_url(), e.code, e.msg,
                                e.headers, response_dict)
       else:
         raise
def upload.AbstractRpcServer._GetAuthToken (self, email, password) private
Uses ClientLogin to authenticate the user, returning an auth token.
Args:
  email:    The user's email address
  password: The user's password
Raises:
  ClientLoginError: If there was an error authenticating with ClientLogin.
  HTTPError: If there was some other form of HTTP error.
Returns:
  The authentication token returned by ClientLogin.
Definition at line 172 of file upload.py.
References upload.AbstractRpcServer._CreateRequest(), and upload.AbstractRpcServer._GetAuthToken().
   def _GetAuthToken(self, email, password):
     """Uses ClientLogin to authenticate the user, returning an auth token.
     Args:
       email:    The user's email address
       password: The user's password
     Raises:
       ClientLoginError: If there was an error authenticating with ClientLogin.
       HTTPError: If there was some other form of HTTP error.
     Returns:
       The authentication token returned by ClientLogin.
     """
     account_type = "GOOGLE"
     if self.host.endswith(".google.com"):
       # Needed for use inside Google.
       account_type = "HOSTED"
     req = self._CreateRequest(
         url="https://www.google.com/accounts/ClientLogin",
         data=urllib.urlencode({
             "Email": email,
             "Passwd": password,
             "service": "ah",
             "source": "rietveld-codereview-upload",
             "accountType": account_type,
         }),
     )
     try:
       response = self.opener.open(req)
       response_body = response.read()
       response_dict = dict(x.split("=")
                            for x in response_body.split("\n") if x)
       return response_dict["Auth"]
     except urllib2.HTTPError, e:
       if e.code == 403:
         body = e.read()
         response_dict = dict(x.split("=", 1) for x in body.split("\n") if x)
         raise ClientLoginError(req.get_full_url(), e.code, e.msg,
                                e.headers, response_dict)
       else:
         raise
def upload.AbstractRpcServer._GetAuthToken (self, email, password) private
Uses ClientLogin to authenticate the user, returning an auth token.
Args:
  email:    The user's email address
  password: The user's password
Raises:
  ClientLoginError: If there was an error authenticating with ClientLogin.
  HTTPError: If there was some other form of HTTP error.
Returns:
  The authentication token returned by ClientLogin.
Definition at line 172 of file upload.py.
References upload.AbstractRpcServer._CreateRequest(), and upload.AbstractRpcServer._GetAuthToken().
   def _GetAuthToken(self, email, password):
     """Uses ClientLogin to authenticate the user, returning an auth token.
     Args:
       email:    The user's email address
       password: The user's password
     Raises:
       ClientLoginError: If there was an error authenticating with ClientLogin.
       HTTPError: If there was some other form of HTTP error.
     Returns:
       The authentication token returned by ClientLogin.
     """
     account_type = "GOOGLE"
     if self.host.endswith(".google.com"):
       # Needed for use inside Google.
       account_type = "HOSTED"
     req = self._CreateRequest(
         url="https://www.google.com/accounts/ClientLogin",
         data=urllib.urlencode({
             "Email": email,
             "Passwd": password,
             "service": "ah",
             "source": "rietveld-codereview-upload",
             "accountType": account_type,
         }),
     )
     try:
       response = self.opener.open(req)
       response_body = response.read()
       response_dict = dict(x.split("=")
                            for x in response_body.split("\n") if x)
       return response_dict["Auth"]
     except urllib2.HTTPError, e:
       if e.code == 403:
         body = e.read()
         response_dict = dict(x.split("=", 1) for x in body.split("\n") if x)
         raise ClientLoginError(req.get_full_url(), e.code, e.msg,
                                e.headers, response_dict)
       else:
         raise
def upload.AbstractRpcServer._GetAuthToken (self, email, password) private
Uses ClientLogin to authenticate the user, returning an auth token.
Args:
  email:    The user's email address
  password: The user's password
Raises:
  ClientLoginError: If there was an error authenticating with ClientLogin.
  HTTPError: If there was some other form of HTTP error.
Returns:
  The authentication token returned by ClientLogin.
Definition at line 172 of file upload.py.
References upload.AbstractRpcServer._CreateRequest(), and upload.AbstractRpcServer._GetAuthToken().
   def _GetAuthToken(self, email, password):
     """Uses ClientLogin to authenticate the user, returning an auth token.
     Args:
       email:    The user's email address
       password: The user's password
     Raises:
       ClientLoginError: If there was an error authenticating with ClientLogin.
       HTTPError: If there was some other form of HTTP error.
     Returns:
       The authentication token returned by ClientLogin.
     """
     account_type = "GOOGLE"
     if self.host.endswith(".google.com"):
       # Needed for use inside Google.
       account_type = "HOSTED"
     req = self._CreateRequest(
         url="https://www.google.com/accounts/ClientLogin",
         data=urllib.urlencode({
             "Email": email,
             "Passwd": password,
             "service": "ah",
             "source": "rietveld-codereview-upload",
             "accountType": account_type,
         }),
     )
     try:
       response = self.opener.open(req)
       response_body = response.read()
       response_dict = dict(x.split("=")
                            for x in response_body.split("\n") if x)
       return response_dict["Auth"]
     except urllib2.HTTPError, e:
       if e.code == 403:
         body = e.read()
         response_dict = dict(x.split("=", 1) for x in body.split("\n") if x)
         raise ClientLoginError(req.get_full_url(), e.code, e.msg,
                                e.headers, response_dict)
       else:
         raise
def upload.AbstractRpcServer._GetOpener (self) private
Returns an OpenerDirector for making HTTP requests.
Returns:
  A urllib2.OpenerDirector object.
Definition at line 154 of file upload.py.
References upload.AbstractRpcServer._GetOpener().
   def _GetOpener(self):
     """Returns an OpenerDirector for making HTTP requests.
     Returns:
       A urllib2.OpenerDirector object.
     """
     raise NotImplementedError()
def upload.AbstractRpcServer._GetOpener (self) private
Returns an OpenerDirector for making HTTP requests.
Returns:
  A urllib2.OpenerDirector object.
Definition at line 154 of file upload.py.
References upload.AbstractRpcServer._GetOpener().
   def _GetOpener(self):
     """Returns an OpenerDirector for making HTTP requests.
     Returns:
       A urllib2.OpenerDirector object.
     """
     raise NotImplementedError()
def upload.AbstractRpcServer._GetOpener (self) private
Returns an OpenerDirector for making HTTP requests.
Returns:
  A urllib2.OpenerDirector object.
Definition at line 154 of file upload.py.
References upload.AbstractRpcServer._GetOpener().
   def _GetOpener(self):
     """Returns an OpenerDirector for making HTTP requests.
     Returns:
       A urllib2.OpenerDirector object.
     """
     raise NotImplementedError()
def upload.AbstractRpcServer._GetOpener (self) private
Returns an OpenerDirector for making HTTP requests.
Returns:
  A urllib2.OpenerDirector object.
Definition at line 154 of file upload.py.
References upload.AbstractRpcServer._GetOpener().
   def _GetOpener(self):
     """Returns an OpenerDirector for making HTTP requests.
     Returns:
       A urllib2.OpenerDirector object.
     """
     raise NotImplementedError()
def upload.AbstractRpcServer._GetOpener (self) private
Returns an OpenerDirector for making HTTP requests.
Returns:
  A urllib2.OpenerDirector object.
Definition at line 154 of file upload.py.
Referenced by upload.AbstractRpcServer.__init__(), and upload.AbstractRpcServer._GetOpener().
   def _GetOpener(self):
     """Returns an OpenerDirector for making HTTP requests.
     Returns:
       A urllib2.OpenerDirector object.
     """
     raise NotImplementedError()
def upload.AbstractRpcServer._GetOpener (self) private
Returns an OpenerDirector for making HTTP requests.
Returns:
  A urllib2.OpenerDirector object.
Definition at line 154 of file upload.py.
References upload.AbstractRpcServer._GetOpener().
   def _GetOpener(self):
     """Returns an OpenerDirector for making HTTP requests.
     Returns:
       A urllib2.OpenerDirector object.
     """
     raise NotImplementedError()
def upload.AbstractRpcServer.Send (self, request_path, payload = None, content_type = "application/octet-stream", timeout = None, kwargs)
Sends an RPC and returns the response.
Args:
  request_path: The path to send the request to, eg /api/appversion/create.
  payload: The body of the request, or None to send an empty request.
  content_type: The Content-Type header to use.
  timeout: timeout in seconds; default None i.e. no timeout.
(Note: for large requests on OS X, the timeout doesn't work right.)
  kwargs: Any keyword arguments are converted into query string parameters.
Returns:
  The response body, as a string.
Definition at line 294 of file upload.py.
References upload.AbstractRpcServer._Authenticate(), upload.AbstractRpcServer._CreateRequest(), upload.AbstractRpcServer.authenticated, and upload.AbstractRpcServer.host.
Referenced by upload.AbstractRpcServer._Authenticate().
            **kwargs):
     """Sends an RPC and returns the response.
     Args:
       request_path: The path to send the request to, eg /api/appversion/create.
       payload: The body of the request, or None to send an empty request.
       content_type: The Content-Type header to use.
       timeout: timeout in seconds; default None i.e. no timeout.
         (Note: for large requests on OS X, the timeout doesn't work right.)
       kwargs: Any keyword arguments are converted into query string parameters.
     Returns:
       The response body, as a string.
     """
     # TODO: Don't require authentication.  Let the server say
     # whether it is necessary.
     if not self.authenticated:
       self._Authenticate()
     old_timeout = socket.getdefaulttimeout()
     socket.setdefaulttimeout(timeout)
     try:
       tries = 0
       while True:
         tries += 1
         args = dict(kwargs)
         url = "http://%s%s" % (self.host, request_path)
         if args:
           url += "?" + urllib.urlencode(args)
         req = self._CreateRequest(url=url, data=payload)
         req.add_header("Content-Type", content_type)
         try:
           f = self.opener.open(req)
           response = f.read()
           f.close()
           return response
         except urllib2.HTTPError, e:
           if tries > 3:
             raise
           elif e.code == 401:
             self._Authenticate()
def upload.AbstractRpcServer.Send (self, request_path, payload = None, content_type = "application/octet-stream", timeout = None, kwargs)
Sends an RPC and returns the response.
Args:
  request_path: The path to send the request to, eg /api/appversion/create.
  payload: The body of the request, or None to send an empty request.
  content_type: The Content-Type header to use.
  timeout: timeout in seconds; default None i.e. no timeout.
(Note: for large requests on OS X, the timeout doesn't work right.)
  kwargs: Any keyword arguments are converted into query string parameters.
Returns:
  The response body, as a string.
Definition at line 294 of file upload.py.
References upload.AbstractRpcServer._Authenticate(), upload.AbstractRpcServer._CreateRequest(), upload.AbstractRpcServer.authenticated, and upload.AbstractRpcServer.host.
            **kwargs):
     """Sends an RPC and returns the response.
     Args:
       request_path: The path to send the request to, eg /api/appversion/create.
       payload: The body of the request, or None to send an empty request.
       content_type: The Content-Type header to use.
       timeout: timeout in seconds; default None i.e. no timeout.
         (Note: for large requests on OS X, the timeout doesn't work right.)
       kwargs: Any keyword arguments are converted into query string parameters.
     Returns:
       The response body, as a string.
     """
     # TODO: Don't require authentication.  Let the server say
     # whether it is necessary.
     if not self.authenticated:
       self._Authenticate()
     old_timeout = socket.getdefaulttimeout()
     socket.setdefaulttimeout(timeout)
     try:
       tries = 0
       while True:
         tries += 1
         args = dict(kwargs)
         url = "http://%s%s" % (self.host, request_path)
         if args:
           url += "?" + urllib.urlencode(args)
         req = self._CreateRequest(url=url, data=payload)
         req.add_header("Content-Type", content_type)
         try:
           f = self.opener.open(req)
           response = f.read()
           f.close()
           return response
         except urllib2.HTTPError, e:
           if tries > 3:
             raise
           elif e.code == 401:
             self._Authenticate()
def upload.AbstractRpcServer.Send (self, request_path, payload = None, content_type = "application/octet-stream", timeout = None, kwargs)
Sends an RPC and returns the response.
Args:
  request_path: The path to send the request to, eg /api/appversion/create.
  payload: The body of the request, or None to send an empty request.
  content_type: The Content-Type header to use.
  timeout: timeout in seconds; default None i.e. no timeout.
(Note: for large requests on OS X, the timeout doesn't work right.)
  kwargs: Any keyword arguments are converted into query string parameters.
Returns:
  The response body, as a string.
Definition at line 294 of file upload.py.
References upload.AbstractRpcServer._Authenticate(), upload.AbstractRpcServer._CreateRequest(), upload.AbstractRpcServer.authenticated, and upload.AbstractRpcServer.host.
            **kwargs):
     """Sends an RPC and returns the response.
     Args:
       request_path: The path to send the request to, eg /api/appversion/create.
       payload: The body of the request, or None to send an empty request.
       content_type: The Content-Type header to use.
       timeout: timeout in seconds; default None i.e. no timeout.
         (Note: for large requests on OS X, the timeout doesn't work right.)
       kwargs: Any keyword arguments are converted into query string parameters.
     Returns:
       The response body, as a string.
     """
     # TODO: Don't require authentication.  Let the server say
     # whether it is necessary.
     if not self.authenticated:
       self._Authenticate()
     old_timeout = socket.getdefaulttimeout()
     socket.setdefaulttimeout(timeout)
     try:
       tries = 0
       while True:
         tries += 1
         args = dict(kwargs)
         url = "http://%s%s" % (self.host, request_path)
         if args:
           url += "?" + urllib.urlencode(args)
         req = self._CreateRequest(url=url, data=payload)
         req.add_header("Content-Type", content_type)
         try:
           f = self.opener.open(req)
           response = f.read()
           f.close()
           return response
         except urllib2.HTTPError, e:
           if tries > 3:
             raise
           elif e.code == 401:
             self._Authenticate()
def upload.AbstractRpcServer.Send (self, request_path, payload = None, content_type = "application/octet-stream", timeout = None, kwargs)
Sends an RPC and returns the response.
Args:
  request_path: The path to send the request to, eg /api/appversion/create.
  payload: The body of the request, or None to send an empty request.
  content_type: The Content-Type header to use.
  timeout: timeout in seconds; default None i.e. no timeout.
(Note: for large requests on OS X, the timeout doesn't work right.)
  kwargs: Any keyword arguments are converted into query string parameters.
Returns:
  The response body, as a string.
Definition at line 294 of file upload.py.
References upload.AbstractRpcServer._Authenticate(), upload.AbstractRpcServer._CreateRequest(), upload.AbstractRpcServer.authenticated, and upload.AbstractRpcServer.host.
            **kwargs):
     """Sends an RPC and returns the response.
     Args:
       request_path: The path to send the request to, eg /api/appversion/create.
       payload: The body of the request, or None to send an empty request.
       content_type: The Content-Type header to use.
       timeout: timeout in seconds; default None i.e. no timeout.
         (Note: for large requests on OS X, the timeout doesn't work right.)
       kwargs: Any keyword arguments are converted into query string parameters.
     Returns:
       The response body, as a string.
     """
     # TODO: Don't require authentication.  Let the server say
     # whether it is necessary.
     if not self.authenticated:
       self._Authenticate()
     old_timeout = socket.getdefaulttimeout()
     socket.setdefaulttimeout(timeout)
     try:
       tries = 0
       while True:
         tries += 1
         args = dict(kwargs)
         url = "http://%s%s" % (self.host, request_path)
         if args:
           url += "?" + urllib.urlencode(args)
         req = self._CreateRequest(url=url, data=payload)
         req.add_header("Content-Type", content_type)
         try:
           f = self.opener.open(req)
           response = f.read()
           f.close()
           return response
         except urllib2.HTTPError, e:
           if tries > 3:
             raise
           elif e.code == 401:
             self._Authenticate()
def upload.AbstractRpcServer.Send (self, request_path, payload = None, content_type = "application/octet-stream", timeout = None, kwargs)
Sends an RPC and returns the response.
Args:
  request_path: The path to send the request to, eg /api/appversion/create.
  payload: The body of the request, or None to send an empty request.
  content_type: The Content-Type header to use.
  timeout: timeout in seconds; default None i.e. no timeout.
(Note: for large requests on OS X, the timeout doesn't work right.)
  kwargs: Any keyword arguments are converted into query string parameters.
Returns:
  The response body, as a string.
Definition at line 294 of file upload.py.
References upload.AbstractRpcServer._Authenticate(), upload.AbstractRpcServer._CreateRequest(), upload.AbstractRpcServer.authenticated, and upload.AbstractRpcServer.host.
            **kwargs):
     """Sends an RPC and returns the response.
     Args:
       request_path: The path to send the request to, eg /api/appversion/create.
       payload: The body of the request, or None to send an empty request.
       content_type: The Content-Type header to use.
       timeout: timeout in seconds; default None i.e. no timeout.
         (Note: for large requests on OS X, the timeout doesn't work right.)
       kwargs: Any keyword arguments are converted into query string parameters.
     Returns:
       The response body, as a string.
     """
     # TODO: Don't require authentication.  Let the server say
     # whether it is necessary.
     if not self.authenticated:
       self._Authenticate()
     old_timeout = socket.getdefaulttimeout()
     socket.setdefaulttimeout(timeout)
     try:
       tries = 0
       while True:
         tries += 1
         args = dict(kwargs)
         url = "http://%s%s" % (self.host, request_path)
         if args:
           url += "?" + urllib.urlencode(args)
         req = self._CreateRequest(url=url, data=payload)
         req.add_header("Content-Type", content_type)
         try:
           f = self.opener.open(req)
           response = f.read()
           f.close()
           return response
         except urllib2.HTTPError, e:
           if tries > 3:
             raise
           elif e.code == 401:
             self._Authenticate()
def upload.AbstractRpcServer.Send (self, request_path, payload = None, content_type = "application/octet-stream", timeout = None, kwargs)
Sends an RPC and returns the response.
Args:
  request_path: The path to send the request to, eg /api/appversion/create.
  payload: The body of the request, or None to send an empty request.
  content_type: The Content-Type header to use.
  timeout: timeout in seconds; default None i.e. no timeout.
(Note: for large requests on OS X, the timeout doesn't work right.)
  kwargs: Any keyword arguments are converted into query string parameters.
Returns:
  The response body, as a string.
Definition at line 294 of file upload.py.
References upload.AbstractRpcServer._Authenticate(), upload.AbstractRpcServer._CreateRequest(), upload.AbstractRpcServer.authenticated, and upload.AbstractRpcServer.host.
            **kwargs):
     """Sends an RPC and returns the response.
     Args:
       request_path: The path to send the request to, eg /api/appversion/create.
       payload: The body of the request, or None to send an empty request.
       content_type: The Content-Type header to use.
       timeout: timeout in seconds; default None i.e. no timeout.
         (Note: for large requests on OS X, the timeout doesn't work right.)
       kwargs: Any keyword arguments are converted into query string parameters.
     Returns:
       The response body, as a string.
     """
     # TODO: Don't require authentication.  Let the server say
     # whether it is necessary.
     if not self.authenticated:
       self._Authenticate()
     old_timeout = socket.getdefaulttimeout()
     socket.setdefaulttimeout(timeout)
     try:
       tries = 0
       while True:
         tries += 1
         args = dict(kwargs)
         url = "http://%s%s" % (self.host, request_path)
         if args:
           url += "?" + urllib.urlencode(args)
         req = self._CreateRequest(url=url, data=payload)
         req.add_header("Content-Type", content_type)
         try:
           f = self.opener.open(req)
           response = f.read()
           f.close()
           return response
         except urllib2.HTTPError, e:
           if tries > 3:
             raise
           elif e.code == 401:
             self._Authenticate()
Member Data Documentation
upload.AbstractRpcServer.auth_function
Definition at line 144 of file upload.py.
Referenced by upload.AbstractRpcServer.__init__(), and upload.AbstractRpcServer._Authenticate().
upload.AbstractRpcServer.authenticated
Definition at line 145 of file upload.py.
Referenced by upload.AbstractRpcServer.__init__(), upload.AbstractRpcServer._GetAuthCookie(), upload.HttpRpcServer._GetOpener(), and upload.AbstractRpcServer.Send().
upload.AbstractRpcServer.extra_headers
Definition at line 146 of file upload.py.
Referenced by upload.AbstractRpcServer.__init__().
upload.AbstractRpcServer.host
Definition at line 142 of file upload.py.
Referenced by upload.AbstractRpcServer.__init__(), upload.AbstractRpcServer._GetAuthCookie(), and upload.AbstractRpcServer.Send().
upload.AbstractRpcServer.host_override
Definition at line 143 of file upload.py.
Referenced by upload.AbstractRpcServer.__init__(), and upload.AbstractRpcServer._CreateRequest().
upload.AbstractRpcServer.opener
Definition at line 148 of file upload.py.
Referenced by upload.AbstractRpcServer.__init__().
upload.AbstractRpcServer.save_cookies
Definition at line 147 of file upload.py.
Referenced by upload.AbstractRpcServer.__init__(), upload.HttpRpcServer._Authenticate(), and upload.HttpRpcServer._GetOpener().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/scripts/upload.py