proxygen: folly::AsyncIOQueue Class Reference
folly::AsyncIOQueue Class Reference
#include <AsyncIO.h>
Public Types
typedef std::function< AsyncIOOp *()> OpFactory
Public Member Functions
AsyncIOQueue (AsyncIO *asyncIO)
~AsyncIOQueue ()
size_t queued () const
void submit (AsyncIOOp *op)
void submit (OpFactory op)
Private Member Functions
void onCompleted (AsyncIOOp *op)
void maybeDequeue ()
Private Attributes
AsyncIO * asyncIO_
std::deque< OpFactory > queue_
Detailed Description
Wrapper around AsyncIO that allows you to schedule more requests than the AsyncIO's object capacity. Other requests are queued and processed in a FIFO order.
Definition at line 242 of file AsyncIO.h.
Member Typedef Documentation
typedef std::function<AsyncIOOp*()> folly::AsyncIOQueue::OpFactory
Submit a delayed op to the AsyncIO queue; this allows you to postpone creation of the Op (which may require allocating memory, etc) until the AsyncIO object has room.
Definition at line 267 of file AsyncIO.h.
Constructor & Destructor Documentation
folly::AsyncIOQueue::AsyncIOQueue (AsyncIO * asyncIO) explicit
Create a queue, using the given AsyncIO object. The AsyncIO object may not be used by anything else until the queue is destroyed.
Definition at line 276 of file AsyncIO.cpp.
 : asyncIO_(asyncIO) {}
folly::AsyncIOQueue::~AsyncIOQueue ()
Definition at line 278 of file AsyncIO.cpp.
References asyncIO_, and folly::AsyncIO::pending().
{
   CHECK_EQ(asyncIO_->pending(), 0);
 }
Member Function Documentation
void folly::AsyncIOQueue::maybeDequeue () private
Definition at line 295 of file AsyncIO.cpp.
References asyncIO_, folly::AsyncIO::capacity(), onCompleted(), folly::AsyncIO::pending(), queue_, and folly::AsyncIO::submit().
Referenced by onCompleted(), and submit().
{
   while (!queue_.empty() && asyncIO_->pending() < asyncIO_->capacity()) {
     auto& opFactory = queue_.front();
     auto op = opFactory();
     queue_.pop_front();
     // Interpose our completion callback
     auto& nextCb = op->notificationCallback();
     op->setNotificationCallback([this, nextCb](AsyncIOOp* op2) {
       this->onCompleted(op2);
       if (nextCb) {
         nextCb(op2);
       }
     });
     asyncIO_->submit(op);
   }
 }
void folly::AsyncIOQueue::onCompleted (AsyncIOOp * op) private
Definition at line 291 of file AsyncIO.cpp.
References maybeDequeue().
Referenced by maybeDequeue().
{
   maybeDequeue();
 }
size_t folly::AsyncIOQueue::queued () const inline
Definition at line 252 of file AsyncIO.h.
References submit.
{
     return queue_.size();
   }
void folly::AsyncIOQueue::submit (AsyncIOOp * op)
Submit an op to the AsyncIO queue. The op will be queued until the AsyncIO object has room.
Definition at line 282 of file AsyncIO.cpp.
{
   submit([op]() { return op; });
 }
void folly::AsyncIOQueue::submit (OpFactory op)
Definition at line 286 of file AsyncIO.cpp.
References maybeDequeue(), and queue_.
{
   queue_.push_back(op);
   maybeDequeue();
 }
Member Data Documentation
AsyncIO* folly::AsyncIOQueue::asyncIO_ private
Definition at line 274 of file AsyncIO.h.
Referenced by maybeDequeue(), and ~AsyncIOQueue().
std::deque<OpFactory> folly::AsyncIOQueue::queue_ private
Definition at line 276 of file AsyncIO.h.
Referenced by maybeDequeue(), and submit().
The documentation for this class was generated from the following files:
proxygen/folly/folly/experimental/io/AsyncIO.h
proxygen/folly/folly/experimental/io/AsyncIO.cpp