proxygen: testing::internal::HasSubstrMatcher< StringType > Class Template Reference
testing::internal::HasSubstrMatcher< StringType > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
HasSubstrMatcher (const StringType &substring)
template<typename CharType >
bool MatchAndExplain (CharType *s, MatchResultListener *listener) const
template<typename MatcheeStringType >
bool MatchAndExplain (const MatcheeStringType &s, MatchResultListener *) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
HasSubstrMatcher (const StringType &substring)
template<typename CharType >
bool MatchAndExplain (CharType *s, MatchResultListener *listener) const
template<typename MatcheeStringType >
bool MatchAndExplain (const MatcheeStringType &s, MatchResultListener *) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
HasSubstrMatcher (const StringType &substring)
template<typename CharType >
bool MatchAndExplain (CharType *s, MatchResultListener *listener) const
template<typename MatcheeStringType >
bool MatchAndExplain (const MatcheeStringType &s, MatchResultListener *) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (HasSubstrMatcher)
GTEST_DISALLOW_ASSIGN_ (HasSubstrMatcher)
GTEST_DISALLOW_ASSIGN_ (HasSubstrMatcher)
Private Attributes
const StringType substring_
Detailed Description
template<typename StringType>
class testing::internal::HasSubstrMatcher< StringType >
Definition at line 1187 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename StringType > testing::internal::HasSubstrMatcher< StringType >::HasSubstrMatcher (const StringType & substring) inline explicit
Definition at line 1189 of file gmock-matchers.h.
       : substring_(substring) {}
template<typename StringType > testing::internal::HasSubstrMatcher< StringType >::HasSubstrMatcher (const StringType & substring) inline explicit
Definition at line 1189 of file gmock-matchers.h.
       : substring_(substring) {}
template<typename StringType > testing::internal::HasSubstrMatcher< StringType >::HasSubstrMatcher (const StringType & substring) inline explicit
Definition at line 1189 of file gmock-matchers.h.
       : substring_(substring) {}
Member Function Documentation
template<typename StringType > void testing::internal::HasSubstrMatcher< StringType >::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 1219 of file gmock-matchers.h.
References testing::internal::UniversalPrint().
{
     *os << "has no substring ";
     UniversalPrint(substring_, os);
   }
template<typename StringType > void testing::internal::HasSubstrMatcher< StringType >::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 1219 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, and testing::internal::UniversalPrint().
{
     *os << "has no substring ";
     UniversalPrint(substring_, os);
   }
template<typename StringType > void testing::internal::HasSubstrMatcher< StringType >::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 1219 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, and testing::internal::UniversalPrint().
{
     *os << "has no substring ";
     UniversalPrint(substring_, os);
   }
template<typename StringType > void testing::internal::HasSubstrMatcher< StringType >::DescribeTo (::std::ostream * os) const inline
Definition at line 1214 of file gmock-matchers.h.
References testing::internal::UniversalPrint().
{
     *os << "has substring ";
     UniversalPrint(substring_, os);
   }
template<typename StringType > void testing::internal::HasSubstrMatcher< StringType >::DescribeTo (::std::ostream * os) const inline
Definition at line 1214 of file gmock-matchers.h.
References testing::internal::UniversalPrint().
{
     *os << "has substring ";
     UniversalPrint(substring_, os);
   }
template<typename StringType > void testing::internal::HasSubstrMatcher< StringType >::DescribeTo (::std::ostream * os) const inline
Definition at line 1214 of file gmock-matchers.h.
References testing::internal::UniversalPrint().
{
     *os << "has substring ";
     UniversalPrint(substring_, os);
   }
template<typename StringType > testing::internal::HasSubstrMatcher< StringType >::GTEST_DISALLOW_ASSIGN_ (HasSubstrMatcher< StringType >) private
template<typename StringType > testing::internal::HasSubstrMatcher< StringType >::GTEST_DISALLOW_ASSIGN_ (HasSubstrMatcher< StringType >) private
template<typename StringType > testing::internal::HasSubstrMatcher< StringType >::GTEST_DISALLOW_ASSIGN_ (HasSubstrMatcher< StringType >) private
template<typename StringType > template<typename CharType > bool testing::internal::HasSubstrMatcher< StringType >::MatchAndExplain (CharType * s, MatchResultListener * listener) const inline
Definition at line 1198 of file gmock-matchers.h.
{
     return s != NULL && MatchAndExplain(StringType(s), listener);
   }
template<typename StringType > template<typename CharType > bool testing::internal::HasSubstrMatcher< StringType >::MatchAndExplain (CharType * s, MatchResultListener * listener) const inline
Definition at line 1198 of file gmock-matchers.h.
{
     return s != NULL && MatchAndExplain(StringType(s), listener);
   }
template<typename StringType > template<typename CharType > bool testing::internal::HasSubstrMatcher< StringType >::MatchAndExplain (CharType * s, MatchResultListener * listener) const inline
Definition at line 1198 of file gmock-matchers.h.
{
     return s != NULL && MatchAndExplain(StringType(s), listener);
   }
template<typename StringType > template<typename MatcheeStringType > bool testing::internal::HasSubstrMatcher< StringType >::MatchAndExplain (const MatcheeStringType & s, MatchResultListener *) const inline
Definition at line 1207 of file gmock-matchers.h.
{
     const StringType& s2(s);
     return s2.find(substring_) != StringType::npos;
   }
template<typename StringType > template<typename MatcheeStringType > bool testing::internal::HasSubstrMatcher< StringType >::MatchAndExplain (const MatcheeStringType & s, MatchResultListener *) const inline
Definition at line 1207 of file gmock-matchers.h.
{
     const StringType& s2(s);
     return s2.find(substring_) != StringType::npos;
   }
template<typename StringType > template<typename MatcheeStringType > bool testing::internal::HasSubstrMatcher< StringType >::MatchAndExplain (const MatcheeStringType & s, MatchResultListener *) const inline
Definition at line 1207 of file gmock-matchers.h.
{
     const StringType& s2(s);
     return s2.find(substring_) != StringType::npos;
   }
Member Data Documentation
template<typename StringType > const StringType testing::internal::HasSubstrMatcher< StringType >::substring_ private
Definition at line 1225 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h