proxygen: folly::python::GILAwareManualExecutor Class Reference
folly::python::GILAwareManualExecutor Class Reference
#include <GILAwareManualExecutor.h>
Public Member Functions
void add (Func) override
void drive () override
Public Member Functions inherited from folly::DrivableExecutor
~DrivableExecutor () override=default
Public Member Functions inherited from folly::Executor
virtual ~Executor ()
virtual void addWithPriority (Func, int8_t priority)
virtual uint8_t getNumPriorities () const
Private Member Functions
void waitBeforeDrive ()
void driveImpl ()
Private Attributes
std::mutex lock_
std::queue< Func > funcs_
std::condition_variable cv_
Additional Inherited Members
Static Public Member Functions inherited from folly::Executor
template<typename ExecutorT >
static KeepAlive< ExecutorT > getKeepAliveToken (ExecutorT *executor)
template<typename ExecutorT >
static KeepAlive< ExecutorT > getKeepAliveToken (ExecutorT &executor)
Static Public Attributes inherited from folly::Executor
static const int8_t LO_PRI = SCHAR_MIN
static const int8_t MID_PRI = 0
static const int8_t HI_PRI = SCHAR_MAX
Protected Member Functions inherited from folly::Executor
virtual bool keepAliveAcquire ()
virtual void keepAliveRelease ()
Static Protected Member Functions inherited from folly::Executor
template<typename ExecutorT >
static bool isKeepAliveDummy (const KeepAlive< ExecutorT > &keepAlive)
template<typename ExecutorT >
static KeepAlive< ExecutorT > makeKeepAlive (ExecutorT *executor)
Detailed Description
A simple ManualExecutor intended to be run directly on a Python thread. It releases Python GIL while waiting for tasks to execute.
Definition at line 34 of file GILAwareManualExecutor.h.
Member Function Documentation
void folly::python::GILAwareManualExecutor::add (Func) override virtual
Enqueue a function to executed by this executor. This and all variants must be threadsafe.
Implements folly::Executor.
Definition at line 26 of file GILAwareManualExecutor.cpp.
References cv_, funcs_, folly::lock(), lock_, and folly::gen::move.
{
   {
     std::lock_guard<std::mutex> lock(lock_);
     funcs_.emplace(std::move(callback));
   }
   cv_.notify_one();
 }
void folly::python::GILAwareManualExecutor::drive () inline override virtual
Implements folly::DrivableExecutor.
Definition at line 39 of file GILAwareManualExecutor.h.
References driveImpl(), and waitBeforeDrive().
{
     waitBeforeDrive();
     driveImpl();
   }
void folly::python::GILAwareManualExecutor::driveImpl () private
Definition at line 51 of file GILAwareManualExecutor.cpp.
References funcs_, folly::lock(), lock_, and folly::gen::move.
Referenced by drive().
{
   Func func;
   while (true) {
     {
       std::lock_guard<std::mutex> lock(lock_);
       if (funcs_.empty()) {
         break;
       }
       func = std::move(funcs_.front());
       funcs_.pop();
     }
     func();
   }
 }
void folly::python::GILAwareManualExecutor::waitBeforeDrive () private
Definition at line 34 of file GILAwareManualExecutor.cpp.
References cv_, funcs_, folly::lock(), lock_, and SCOPE_EXIT.
Referenced by drive().
{
   std::unique_lock<std::mutex> lock(lock_);
   if (!funcs_.empty()) {
     return;
   }
   // Release GIL before waiting on lock
   auto* pyThreadState = PyEval_SaveThread();
   SCOPE_EXIT {
     // Release lock before re-acquiring GIL,
     // to avoid deadlock if another GIL-owning thread is calling add
     lock.unlock();
     PyEval_RestoreThread(pyThreadState);
   };
   cv_.wait(lock, [&] { return !funcs_.empty(); });
 }
Member Data Documentation
std::condition_variable folly::python::GILAwareManualExecutor::cv_ private
Definition at line 50 of file GILAwareManualExecutor.h.
Referenced by add(), and waitBeforeDrive().
std::queue<Func> folly::python::GILAwareManualExecutor::funcs_ private
Definition at line 49 of file GILAwareManualExecutor.h.
Referenced by add(), driveImpl(), and waitBeforeDrive().
std::mutex folly::python::GILAwareManualExecutor::lock_ private
Definition at line 48 of file GILAwareManualExecutor.h.
Referenced by add(), driveImpl(), and waitBeforeDrive().
The documentation for this class was generated from the following files:
proxygen/folly/folly/python/GILAwareManualExecutor.h
proxygen/folly/folly/python/GILAwareManualExecutor.cpp