proxygen: Validator Class Reference
Validator Class Reference
Public Member Functions
Validator (int expectedCount, const std::string &msg)
~Validator ()
void validate ()
Private Attributes
const int32_t expectedCount_
const std::string msg_
Detailed Description
Definition at line 27 of file UncaughtExceptionsTest.cpp.
Constructor & Destructor Documentation
Validator::Validator (int expectedCount, const std::string & msg) inline
Definition at line 29 of file UncaughtExceptionsTest.cpp.
       : expectedCount_(expectedCount), msg_(msg) {}
Validator::~Validator () inline
Definition at line 33 of file UncaughtExceptionsTest.cpp.
References validate().
                {
     validate();
   }
Member Function Documentation
void Validator::validate () inline
Definition at line 38 of file UncaughtExceptionsTest.cpp.
References EXPECT_EQ, expectedCount_, msg_, and folly::uncaught_exceptions().
Referenced by TEST(), and ~Validator().
                   {
     LOG(INFO) << msg_ << ", expected " << expectedCount_ << ", is "
               << folly::uncaught_exceptions();
     EXPECT_EQ(expectedCount_, folly::uncaught_exceptions()) << msg_;
   }
Member Data Documentation
const int32_t Validator::expectedCount_ private
Definition at line 45 of file UncaughtExceptionsTest.cpp.
Referenced by validate().
const std::string Validator::msg_ private
Definition at line 46 of file UncaughtExceptionsTest.cpp.
Referenced by validate().
The documentation for this class was generated from the following file:
proxygen/folly/folly/lang/test/UncaughtExceptionsTest.cpp