proxygen: folly::gen::detail::Zip< Container >::Generator< Value1, Source, Value2, Result > Class Template Reference
folly::gen::detail::Zip< Container >::Generator< Value1, Source, Value2, Result > Class Template Reference
#include <Combine-inl.h>
Public Member Functions
Generator (Source source, const std::shared_ptr< const Container > container)
template<class Handler >
bool apply (Handler &&handler) const
Public Member Functions inherited from folly::gen::GenImpl< Result, Generator< Value1, Source, Value2, Result > >
bool apply (Handler &&handler) const
void foreach (Body &&body) const
Public Member Functions inherited from folly::gen::FBounded< Self >
const Self & self () const
Self & self ()
Private Attributes
Source source_
const std::shared_ptr< const Container > container_
Additional Inherited Members
Public Types inherited from folly::gen::GenImpl< Result, Generator< Value1, Source, Value2, Result > >
typedef Result ValueType
typedef std::decay< Result >::type StorageType
Static Public Attributes inherited from folly::gen::GenImpl< Result, Generator< Value1, Source, Value2, Result > >
static constexpr bool infinite
Protected Member Functions inherited from folly::gen::GenImpl< Result, Generator< Value1, Source, Value2, Result > >
GenImpl ()=default
GenImpl (GenImpl &&)=default
GenImpl (const GenImpl &)=default
GenImpl & operator= (GenImpl &&)=default
GenImpl & operator= (const GenImpl &)=default
Detailed Description
template<class Container>
template<class Value1, class Source, class Value2 = decltype(*std::begin(*container_)), class Result = std::tuple< typename std::decay<Value1>::type, typename std::decay<Value2>::type>>
class folly::gen::detail::Zip< Container >::Generator< Value1, Source, Value2, Result >
Definition at line 114 of file Combine-inl.h.
Constructor & Destructor Documentation
template<class Container > template<class Value1 , class Source , class Value2 = decltype(*std::begin(*container_)), class Result = std::tuple< typename std::decay<Value1>::type, typename std::decay<Value2>::type>> folly::gen::detail::Zip< Container >::Generator< Value1, Source, Value2, Result >::Generator (Source source, const std::shared_ptr< const Container > container) inline explicit
Definition at line 120 of file Combine-inl.h.
         : source_(std::move(source)), container_(container) {}
Member Function Documentation
template<class Container > template<class Value1 , class Source , class Value2 = decltype(*std::begin(*container_)), class Result = std::tuple< typename std::decay<Value1>::type, typename std::decay<Value2>::type>> template<class Handler > bool folly::gen::detail::Zip< Container >::Generator< Value1, Source, Value2, Result >::apply (Handler && handler) const inline
Definition at line 126 of file Combine-inl.h.
References handler(), if(), std::tr1::make_tuple(), and folly::value().
{
       auto iter = container_->begin();
       return (source_.apply([&](Value1 value) -> bool {
         if (iter == container_->end()) {
           return false;
         }
         if (!handler(std::make_tuple(std::forward<Value1>(value), *iter))) {
           return false;
         }
         ++iter;
         return true;
       }));
     }
Member Data Documentation
template<class Container > template<class Value1 , class Source , class Value2 = decltype(*std::begin(*container_)), class Result = std::tuple< typename std::decay<Value1>::type, typename std::decay<Value2>::type>> const std::shared_ptr<const Container> folly::gen::detail::Zip< Container >::Generator< Value1, Source, Value2, Result >::container_ private
Definition at line 117 of file Combine-inl.h.
template<class Container > template<class Value1 , class Source , class Value2 = decltype(*std::begin(*container_)), class Result = std::tuple< typename std::decay<Value1>::type, typename std::decay<Value2>::type>> Source folly::gen::detail::Zip< Container >::Generator< Value1, Source, Value2, Result >::source_ private
Definition at line 116 of file Combine-inl.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/gen/Combine-inl.h