proxygen: testing::internal::ReferenceWrapper< T > Class Template Reference
testing::internal::ReferenceWrapper< T > Class Template Reference
#include <gmock-actions.h>
Public Member Functions
ReferenceWrapper (T &l_value)
operator T & () const
ReferenceWrapper (T &l_value)
operator T & () const
ReferenceWrapper (T &l_value)
operator T & () const
Private Attributes
T * pointer_
Detailed Description
template<typename T>
class testing::internal::ReferenceWrapper< T >
Definition at line 950 of file gmock-actions.h.
Constructor & Destructor Documentation
template<typename T> testing::internal::ReferenceWrapper< T >::ReferenceWrapper (T & l_value) inline explicit
Definition at line 953 of file gmock-actions.h.
 : pointer_(&l_value) {}  // NOLINT
template<typename T> testing::internal::ReferenceWrapper< T >::ReferenceWrapper (T & l_value) inline explicit
Definition at line 953 of file gmock-actions.h.
 : pointer_(&l_value) {}  // NOLINT
template<typename T> testing::internal::ReferenceWrapper< T >::ReferenceWrapper (T & l_value) inline explicit
Definition at line 953 of file gmock-actions.h.
 : pointer_(&l_value) {}  // NOLINT
Member Function Documentation
template<typename T> testing::internal::ReferenceWrapper< T >::operator T & () const inline
Definition at line 957 of file gmock-actions.h.
 { return *pointer_; }
template<typename T> testing::internal::ReferenceWrapper< T >::operator T & () const inline
Definition at line 957 of file gmock-actions.h.
References testing::internal::UniversalPrinter< T >::Print(), testing::internal::PrintTo(), and value.
 { return *pointer_; }
template<typename T> testing::internal::ReferenceWrapper< T >::operator T & () const inline
Definition at line 957 of file gmock-actions.h.
References testing::internal::UniversalPrinter< T >::Print(), testing::internal::PrintTo(), and value.
 { return *pointer_; }
Member Data Documentation
template<typename T> T * testing::internal::ReferenceWrapper< T >::pointer_ private
Definition at line 959 of file gmock-actions.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-actions.h