proxygen: folly::io::test::AutomaticCodecTest Class Reference
folly::io::test::AutomaticCodecTest Class Reference
Protected Member Functions
void SetUp () override
void runSimpleTest (const DataHolder &dh)
std::unique_ptr< Codec > getTerminalCodec ()
Protected Attributes
std::unique_ptr< Codec > codec_
std::unique_ptr< Codec > auto_
CodecType codecType_
bool autoType_
Detailed Description
Definition at line 1010 of file CompressionTest.cpp.
Member Function Documentation
std::unique_ptr<Codec> folly::io::test::AutomaticCodecTest::getTerminalCodec () inline protected
Definition at line 1026 of file CompressionTest.cpp.
References folly::io::getCodec().
{
     return (autoType_ ? nullptr : getCodec(codecType_));
   }
void folly::io::test::AutomaticCodecTest::runSimpleTest (const DataHolder & dh) protected
Definition at line 1037 of file CompressionTest.cpp.
References ASSERT_GE, codec_, folly::io::test::DataHolder::data(), EXPECT_EQ, folly::io::test::DataHolder::hash(), folly::io::test::hashIOBuf(), i, folly::gen::move, folly::split(), uint64_t, and folly::IOBuf::wrapBuffer().
{
   constexpr uint64_t uncompressedLength = 1000;
   auto original = IOBuf::wrapBuffer(dh.data(uncompressedLength));
   auto compressed = codec_->compress(original.get());
   if (!codec_->needsUncompressedLength()) {
     auto uncompressed = auto_->uncompress(compressed.get());
     EXPECT_EQ(uncompressedLength, uncompressed->computeChainDataLength());
     EXPECT_EQ(dh.hash(uncompressedLength), hashIOBuf(uncompressed.get()));
   }
   {
     auto uncompressed = auto_->uncompress(compressed.get(), uncompressedLength);
     EXPECT_EQ(uncompressedLength, uncompressed->computeChainDataLength());
     EXPECT_EQ(dh.hash(uncompressedLength), hashIOBuf(uncompressed.get()));
   }
   ASSERT_GE(compressed->computeChainDataLength(), 8);
   for (size_t i = 0; i < 8; ++i) {
     auto split = compressed->clone();
     auto rest = compressed->clone();
     split->trimEnd(split->length() - i);
     rest->trimStart(i);
     split->appendChain(std::move(rest));
     auto uncompressed = auto_->uncompress(split.get(), uncompressedLength);
     EXPECT_EQ(uncompressedLength, uncompressed->computeChainDataLength());
     EXPECT_EQ(dh.hash(uncompressedLength), hashIOBuf(uncompressed.get()));
   }
 }
void folly::io::test::AutomaticCodecTest::SetUp () inline override protected
Definition at line 1012 of file CompressionTest.cpp.
References codec_, folly::io::getAutoUncompressionCodec(), and folly::io::getCodec().
{
     codecType_ = GetParam();
     codec_ = getCodec(codecType_);
     autoType_ = std::any_of(
         autoUncompressionCodecTypes.begin(),
         autoUncompressionCodecTypes.end(),
         [&](CodecType o) { return codecType_ == o; });
     // Add the codec with type codecType_ as the terminal codec if it is not in
     // autoUncompressionCodecTypes.
     auto_ = getAutoUncompressionCodec({}, getTerminalCodec());
   }
Member Data Documentation
std::unique_ptr<Codec> folly::io::test::AutomaticCodecTest::auto_ protected
Definition at line 1031 of file CompressionTest.cpp.
bool folly::io::test::AutomaticCodecTest::autoType_ protected
Definition at line 1034 of file CompressionTest.cpp.
std::unique_ptr<Codec> folly::io::test::AutomaticCodecTest::codec_ protected
Definition at line 1030 of file CompressionTest.cpp.
CodecType folly::io::test::AutomaticCodecTest::codecType_ protected
Definition at line 1032 of file CompressionTest.cpp.
The documentation for this class was generated from the following file:
proxygen/folly/folly/compression/test/CompressionTest.cpp