proxygen: testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 > Class Template Reference
testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 > Class Template Reference
#include <gmock-generated-matchers.h>
Public Types
typedef internal::TupleFields< RawArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::type SelectedArgs
typedef Matcher< const SelectedArgs & > MonomorphicInnerMatcher
typedef internal::TupleFields< RawArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::type SelectedArgs
typedef Matcher< const SelectedArgs & > MonomorphicInnerMatcher
typedef internal::TupleFields< RawArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::type SelectedArgs
typedef Matcher< const SelectedArgs & > MonomorphicInnerMatcher
Public Member Functions
typedef GTEST_REMOVE_REFERENCE_AND_CONST_ (ArgsTuple) RawArgsTuple
template<typename InnerMatcher >
ArgsMatcherImpl (const InnerMatcher &inner_matcher)
virtual bool MatchAndExplain (ArgsTuple args, MatchResultListener *listener) const
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
typedef GTEST_REMOVE_REFERENCE_AND_CONST_ (ArgsTuple) RawArgsTuple
template<typename InnerMatcher >
ArgsMatcherImpl (const InnerMatcher &inner_matcher)
virtual bool MatchAndExplain (ArgsTuple args, MatchResultListener *listener) const
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
typedef GTEST_REMOVE_REFERENCE_AND_CONST_ (ArgsTuple) RawArgsTuple
template<typename InnerMatcher >
ArgsMatcherImpl (const InnerMatcher &inner_matcher)
virtual bool MatchAndExplain (ArgsTuple args, MatchResultListener *listener) const
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
virtual ~MatcherDescriberInterface ()
virtual ~MatcherDescriberInterface ()
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (ArgsMatcherImpl)
GTEST_DISALLOW_ASSIGN_ (ArgsMatcherImpl)
GTEST_DISALLOW_ASSIGN_ (ArgsMatcherImpl)
Static Private Member Functions
static SelectedArgs GetSelectedArgs (ArgsTuple args)
static void PrintIndices (::std::ostream *os)
static SelectedArgs GetSelectedArgs (ArgsTuple args)
static void PrintIndices (::std::ostream *os)
static SelectedArgs GetSelectedArgs (ArgsTuple args)
static void PrintIndices (::std::ostream *os)
Private Attributes
const MonomorphicInnerMatcher inner_matcher_
Detailed Description
template<class ArgsTuple, int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1>
class testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >
Definition at line 211 of file gmock-generated-matchers.h.
Member Typedef Documentation
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> typedef Matcher<const SelectedArgs&> testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::MonomorphicInnerMatcher
Definition at line 217 of file gmock-generated-matchers.h.
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> typedef Matcher<const SelectedArgs&> testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::MonomorphicInnerMatcher
Definition at line 217 of file gmock-generated-matchers.h.
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> typedef Matcher<const SelectedArgs&> testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::MonomorphicInnerMatcher
Definition at line 217 of file gmock-generated-matchers.h.
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> typedef internal::TupleFields<RawArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9>::type testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::SelectedArgs
Definition at line 216 of file gmock-generated-matchers.h.
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> typedef internal::TupleFields<RawArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9>::type testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::SelectedArgs
Definition at line 216 of file gmock-generated-matchers.h.
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> typedef internal::TupleFields<RawArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9>::type testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::SelectedArgs
Definition at line 216 of file gmock-generated-matchers.h.
Constructor & Destructor Documentation
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> template<typename InnerMatcher > testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::ArgsMatcherImpl (const InnerMatcher & inner_matcher) inline explicit
Definition at line 220 of file gmock-generated-matchers.h.
       : inner_matcher_(SafeMatcherCast<const SelectedArgs&>(inner_matcher)) {}
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> template<typename InnerMatcher > testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::ArgsMatcherImpl (const InnerMatcher & inner_matcher) inline explicit
Definition at line 220 of file gmock-generated-matchers.h.
       : inner_matcher_(SafeMatcherCast<const SelectedArgs&>(inner_matcher)) {}
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> template<typename InnerMatcher > testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::ArgsMatcherImpl (const InnerMatcher & inner_matcher) inline explicit
Definition at line 220 of file gmock-generated-matchers.h.
       : inner_matcher_(SafeMatcherCast<const SelectedArgs&>(inner_matcher)) {}
Member Function Documentation
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> virtual void testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 245 of file gmock-generated-matchers.h.
{
     *os << "are a tuple ";
     PrintIndices(os);
     inner_matcher_.DescribeNegationTo(os);
   }
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> virtual void testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 245 of file gmock-generated-matchers.h.
{
     *os << "are a tuple ";
     PrintIndices(os);
     inner_matcher_.DescribeNegationTo(os);
   }
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> virtual void testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 245 of file gmock-generated-matchers.h.
{
     *os << "are a tuple ";
     PrintIndices(os);
     inner_matcher_.DescribeNegationTo(os);
   }
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> virtual void testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 239 of file gmock-generated-matchers.h.
{
     *os << "are a tuple ";
     PrintIndices(os);
     inner_matcher_.DescribeTo(os);
   }
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> virtual void testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 239 of file gmock-generated-matchers.h.
{
     *os << "are a tuple ";
     PrintIndices(os);
     inner_matcher_.DescribeTo(os);
   }
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> virtual void testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 239 of file gmock-generated-matchers.h.
{
     *os << "are a tuple ";
     PrintIndices(os);
     inner_matcher_.DescribeTo(os);
   }
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> static SelectedArgs testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::GetSelectedArgs (ArgsTuple args) inline static private
Definition at line 252 of file gmock-generated-matchers.h.
References testing::internal::TupleFields< Tuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::GetSelectedFields().
{
     return TupleFields<RawArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8,
         k9>::GetSelectedFields(args);
   }
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> static SelectedArgs testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::GetSelectedArgs (ArgsTuple args) inline static private
Definition at line 252 of file gmock-generated-matchers.h.
References testing::internal::TupleFields< Tuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::GetSelectedFields().
{
     return TupleFields<RawArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8,
         k9>::GetSelectedFields(args);
   }
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> static SelectedArgs testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::GetSelectedArgs (ArgsTuple args) inline static private
Definition at line 252 of file gmock-generated-matchers.h.
References testing::internal::TupleFields< Tuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::GetSelectedFields().
{
     return TupleFields<RawArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8,
         k9>::GetSelectedFields(args);
   }
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::GTEST_DISALLOW_ASSIGN_ (ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >) private
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::GTEST_DISALLOW_ASSIGN_ (ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >) private
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::GTEST_DISALLOW_ASSIGN_ (ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >) private
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> typedef testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::GTEST_REMOVE_REFERENCE_AND_CONST_ (ArgsTuple)
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> typedef testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::GTEST_REMOVE_REFERENCE_AND_CONST_ (ArgsTuple)
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> typedef testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::GTEST_REMOVE_REFERENCE_AND_CONST_ (ArgsTuple)
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> virtual bool testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::MatchAndExplain (ArgsTuple args, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< ArgsTuple >.
Definition at line 223 of file gmock-generated-matchers.h.
References testing::MatchResultListener::IsInterested(), testing::internal::PrintIfNotEmpty(), testing::PrintToString(), testing::StringMatchResultListener::str(), and testing::MatchResultListener::stream().
{
     const SelectedArgs& selected_args = GetSelectedArgs(args);
     if (!listener->IsInterested())
       return inner_matcher_.Matches(selected_args);
     PrintIndices(listener->stream());
     *listener << "are " << PrintToString(selected_args);
     StringMatchResultListener inner_listener;
     const bool match = inner_matcher_.MatchAndExplain(selected_args,
                                                       &inner_listener);
     PrintIfNotEmpty(inner_listener.str(), listener->stream());
     return match;
   }
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> virtual bool testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::MatchAndExplain (ArgsTuple args, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< ArgsTuple >.
Definition at line 223 of file gmock-generated-matchers.h.
References testing::MatchResultListener::IsInterested(), testing::internal::PrintIfNotEmpty(), testing::PrintToString(), testing::StringMatchResultListener::str(), and testing::MatchResultListener::stream().
{
     const SelectedArgs& selected_args = GetSelectedArgs(args);
     if (!listener->IsInterested())
       return inner_matcher_.Matches(selected_args);
     PrintIndices(listener->stream());
     *listener << "are " << PrintToString(selected_args);
     StringMatchResultListener inner_listener;
     const bool match = inner_matcher_.MatchAndExplain(selected_args,
                                                       &inner_listener);
     PrintIfNotEmpty(inner_listener.str(), listener->stream());
     return match;
   }
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> virtual bool testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::MatchAndExplain (ArgsTuple args, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< ArgsTuple >.
Definition at line 223 of file gmock-generated-matchers.h.
References testing::MatchResultListener::IsInterested(), testing::internal::PrintIfNotEmpty(), testing::PrintToString(), testing::StringMatchResultListener::str(), and testing::MatchResultListener::stream().
{
     const SelectedArgs& selected_args = GetSelectedArgs(args);
     if (!listener->IsInterested())
       return inner_matcher_.Matches(selected_args);
     PrintIndices(listener->stream());
     *listener << "are " << PrintToString(selected_args);
     StringMatchResultListener inner_listener;
     const bool match = inner_matcher_.MatchAndExplain(selected_args,
                                                       &inner_listener);
     PrintIfNotEmpty(inner_listener.str(), listener->stream());
     return match;
   }
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> static void testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::PrintIndices (::std::ostream * os) inline static private
Definition at line 258 of file gmock-generated-matchers.h.
References i.
{
     *os << "whose fields (";
     const int indices[10] = { k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 };
     for (int i = 0; i < 10; i++) {
       if (indices[i] < 0)
         break;
       if (i >= 1)
         *os << ", ";
       *os << "#" << indices[i];
     }
     *os << ") ";
   }
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> static void testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::PrintIndices (::std::ostream * os) inline static private
Definition at line 258 of file gmock-generated-matchers.h.
References GTEST_DISALLOW_ASSIGN_, and i.
{
     *os << "whose fields (";
     const int indices[10] = { k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 };
     for (int i = 0; i < 10; i++) {
       if (indices[i] < 0)
         break;
       if (i >= 1)
         *os << ", ";
       *os << "#" << indices[i];
     }
     *os << ") ";
   }
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> static void testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::PrintIndices (::std::ostream * os) inline static private
Definition at line 258 of file gmock-generated-matchers.h.
References GTEST_DISALLOW_ASSIGN_, and i.
{
     *os << "whose fields (";
     const int indices[10] = { k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 };
     for (int i = 0; i < 10; i++) {
       if (indices[i] < 0)
         break;
       if (i >= 1)
         *os << ", ";
       *os << "#" << indices[i];
     }
     *os << ") ";
   }
Member Data Documentation
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> const MonomorphicInnerMatcher testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::inner_matcher_ private
Definition at line 273 of file gmock-generated-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-generated-matchers.h