proxygen: testing::Test Class Reference
testing::Test Class Reference abstract
#include <gtest.h>
Classes
struct Setup_should_be_spelled_SetUp
Public Types
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Public Member Functions
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Static Public Member Functions
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Protected Member Functions
Test ()
virtual void SetUp ()
virtual void TearDown ()
Test ()
virtual void SetUp ()
virtual void TearDown ()
Test ()
virtual void SetUp ()
virtual void TearDown ()
Private Member Functions
virtual void TestBody ()=0
void Run ()
void DeleteSelf_ ()
virtual Setup_should_be_spelled_SetUp * Setup ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (Test)
virtual void TestBody ()=0
void Run ()
void DeleteSelf_ ()
virtual Setup_should_be_spelled_SetUp * Setup ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (Test)
virtual void TestBody ()=0
void Run ()
void DeleteSelf_ ()
virtual Setup_should_be_spelled_SetUp * Setup ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (Test)
Static Private Member Functions
static bool HasSameFixtureClass ()
static bool HasSameFixtureClass ()
static bool HasSameFixtureClass ()
Private Attributes
const internal::scoped_ptr< GTEST_FLAG_SAVER_ > gtest_flag_saver_
Friends
class TestInfo
Detailed Description
Definition at line 371 of file gtest.h.
Member Typedef Documentation
typedef internal::SetUpTestCaseFunc testing::Test::SetUpTestCaseFunc
Definition at line 377 of file gtest.h.
typedef internal::SetUpTestCaseFunc testing::Test::SetUpTestCaseFunc
Definition at line 377 of file gtest.h.
typedef internal::SetUpTestCaseFunc testing::Test::SetUpTestCaseFunc
Definition at line 377 of file gtest.h.
typedef internal::TearDownTestCaseFunc testing::Test::TearDownTestCaseFunc
Definition at line 378 of file gtest.h.
typedef internal::TearDownTestCaseFunc testing::Test::TearDownTestCaseFunc
Definition at line 378 of file gtest.h.
typedef internal::TearDownTestCaseFunc testing::Test::TearDownTestCaseFunc
Definition at line 378 of file gtest.h.
Constructor & Destructor Documentation
Test::~Test () virtual
Definition at line 2221 of file gtest.cc.
Referenced by testing::TestPartNonfatallyFailed().
             {
 }
Test::Test () protected
Definition at line 2214 of file gtest.cc.
Referenced by TEST_P(), and testing::TestPartNonfatallyFailed().
     : gtest_flag_saver_(new GTEST_FLAG_SAVER_) {
 }
virtual testing::Test::~Test () virtual
testing::Test::Test () protected
virtual testing::Test::~Test () virtual
testing::Test::Test () protected
Member Function Documentation
void testing::Test::DeleteSelf_ () inline private
Definition at line 453 of file gtest.h.
Referenced by testing::TestInfo::Run().
 { delete this; }
void testing::Test::DeleteSelf_ () inline private
Definition at line 453 of file gtest.h.
 { delete this; }
void testing::Test::DeleteSelf_ () inline private
Definition at line 453 of file gtest.h.
 { delete this; }
testing::Test::GTEST_DISALLOW_COPY_AND_ASSIGN_ (Test) private
testing::Test::GTEST_DISALLOW_COPY_AND_ASSIGN_ (Test) private
testing::Test::GTEST_DISALLOW_COPY_AND_ASSIGN_ (Test) private
static bool testing::Test::HasFailure () inline static
Definition at line 407 of file gtest.h.
References Run(), string, and value.
 { return HasFatalFailure() || HasNonfatalFailure(); }
static bool testing::Test::HasFailure () inline static
Definition at line 407 of file gtest.h.
References Run(), string, and value.
 { return HasFatalFailure() || HasNonfatalFailure(); }
static bool testing::Test::HasFailure () inline static
Definition at line 407 of file gtest.h.
References Run(), string, and value.
Referenced by HasFailureHelper(), and folly::TEST().
 { return HasFatalFailure() || HasNonfatalFailure(); }
static bool testing::Test::HasFatalFailure () static
static bool testing::Test::HasFatalFailure () static
bool Test::HasFatalFailure () static
Definition at line 2487 of file gtest.cc.
References testing::internal::UnitTestImpl::current_test_result(), testing::internal::GetUnitTestImpl(), and testing::TestResult::HasFatalFailure().
Referenced by Run(), testing::TestInfo::Run(), testing::internal::UnitTestImpl::RunAllTests(), testing::internal::TearDownEnvironment(), testing::TestPartNonfatallyFailed(), TryTestSubroutine(), and verify().
{
   return internal::GetUnitTestImpl()->current_test_result()->HasFatalFailure();
 }
static bool testing::Test::HasNonfatalFailure () static
static bool testing::Test::HasNonfatalFailure () static
bool Test::HasNonfatalFailure () static
Definition at line 2492 of file gtest.cc.
References testing::internal::UnitTestImpl::current_test_result(), and testing::internal::GetUnitTestImpl().
Referenced by HasNonfatalFailureHelper(), and testing::TestPartNonfatallyFailed().
{
   return internal::GetUnitTestImpl()->current_test_result()->
       HasNonfatalFailure();
 }
bool Test::HasSameFixtureClass () static private
Definition at line 2269 of file gtest.cc.
References ADD_FAILURE, testing::internal::UnitTestImpl::current_test_case(), testing::internal::UnitTestImpl::current_test_info(), description, testing::TestInfo::fixture_class_id_, testing::Message::GetString(), testing::internal::GetTestTypeId(), testing::internal::GetUnitTestImpl(), message, testing::TestInfo::name(), testing::internal::PrintTestPartResultToString(), string, testing::TestInfo::test_case_name(), and testing::TestCase::test_info_list().
Referenced by Run(), and testing::TestPartNonfatallyFailed().
{
   internal::UnitTestImpl* const impl = internal::GetUnitTestImpl();
   const TestCase* const test_case = impl->current_test_case();
   // Info about the first test in the current test case.
   const TestInfo* const first_test_info = test_case->test_info_list()[0];
   const internal::TypeId first_fixture_id = first_test_info->fixture_class_id_;
   const char* const first_test_name = first_test_info->name();
   // Info about the current test.
   const TestInfo* const this_test_info = impl->current_test_info();
   const internal::TypeId this_fixture_id = this_test_info->fixture_class_id_;
   const char* const this_test_name = this_test_info->name();
   if (this_fixture_id != first_fixture_id) {
     // Is the first test defined using TEST?
     const bool first_is_TEST = first_fixture_id == internal::GetTestTypeId();
     // Is this test defined using TEST?
     const bool this_is_TEST = this_fixture_id == internal::GetTestTypeId();
     if (first_is_TEST || this_is_TEST) {
       // Both TEST and TEST_F appear in same test case, which is incorrect.
       // Tell the user how to fix this.
       // Gets the name of the TEST and the name of the TEST_F.  Note
       // that first_is_TEST and this_is_TEST cannot both be true, as
       // the fixture IDs are different for the two tests.
       const char* const TEST_name =
           first_is_TEST ? first_test_name : this_test_name;
       const char* const TEST_F_name =
           first_is_TEST ? this_test_name : first_test_name;
       ADD_FAILURE()
           << "All tests in the same test case must use the same test fixture\n"
           << "class, so mixing TEST_F and TEST in the same test case is\n"
           << "illegal.  In test case " << this_test_info->test_case_name()
           << ",\n"
           << "test " << TEST_F_name << " is defined using TEST_F but\n"
           << "test " << TEST_name << " is defined using TEST.  You probably\n"
           << "want to change the TEST to TEST_F or move it to another test\n"
           << "case.";
     } else {
       // Two fixture classes with the same name appear in two different
       // namespaces, which is not allowed. Tell the user how to fix this.
       ADD_FAILURE()
           << "All tests in the same test case must use the same test fixture\n"
           << "class.  However, in test case "
           << this_test_info->test_case_name() << ",\n"
           << "you defined test " << first_test_name
           << " and test " << this_test_name << "\n"
           << "using two different test fixture classes.  This can happen if\n"
           << "the two classes are from different namespaces or translation\n"
           << "units and have the same name.  You should probably rename one\n"
           << "of the classes to put the tests into different test cases.";
     }
     return false;
   }
   return true;
 }
static bool testing::Test::HasSameFixtureClass () static private
static bool testing::Test::HasSameFixtureClass () static private
static void testing::Test::RecordProperty (const std::string & key, const std::string & value) static
static void testing::Test::RecordProperty (const std::string & key, const std::string & value) static
void Test::RecordProperty (const std::string & key, const std::string & value) static
Definition at line 2237 of file gtest.cc.
References testing::UnitTest::GetInstance(), and testing::UnitTest::RecordProperty().
Referenced by ExternalUtilityThatCallsRecordProperty(), main(), RecordProperty(), PropertyOne::SetUp(), PropertyTwo::SetUp(), PropertyOne::TearDown(), PropertyTwo::TearDown(), TEST_F(), and testing::TestPartNonfatallyFailed().
{
   UnitTest::GetInstance()->RecordProperty(key, value);
 }
static void testing::Test::RecordProperty (const std::string & key, int value) static
static void testing::Test::RecordProperty (const std::string & key, int value) static
void Test::RecordProperty (const std::string & key, int value) static
Definition at line 2242 of file gtest.cc.
References testing::Message::GetString(), RecordProperty(), and value.
{
   Message value_message;
   value_message << value;
   RecordProperty(key, value_message.GetString().c_str());
 }
void Test::Run () private
Definition at line 2465 of file gtest.cc.
References testing::internal::GetUnitTestImpl(), testing::internal::HandleExceptionsInMethodIfSupported(), HasFatalFailure(), HasSameFixtureClass(), testing::internal::UnitTestImpl::os_stack_trace_getter(), SetUp(), TearDown(), TestBody(), and testing::internal::OsStackTraceGetterInterface::UponLeavingGTest().
Referenced by testing::TestInfo::Run(), and testing::TestPartNonfatallyFailed().
                {
   if (!HasSameFixtureClass()) return;
   internal::UnitTestImpl* const impl = internal::GetUnitTestImpl();
   impl->os_stack_trace_getter()->UponLeavingGTest();
   internal::HandleExceptionsInMethodIfSupported(this, &Test::SetUp, "SetUp()");
   // We will run the test only if SetUp() was successful.
   if (!HasFatalFailure()) {
     impl->os_stack_trace_getter()->UponLeavingGTest();
     internal::HandleExceptionsInMethodIfSupported(
         this, &Test::TestBody, "the test body");
   }
   // However, we want to clean up as much as possible.  Hence we will
   // always call TearDown(), even if SetUp() or the test body has
   // failed.
   impl->os_stack_trace_getter()->UponLeavingGTest();
   internal::HandleExceptionsInMethodIfSupported(
       this, &Test::TearDown, "TearDown()");
 }
void testing::Test::Run () private
void testing::Test::Run () private
void Test::SetUp () protected virtual
Reimplemented in ProtectedFixtureMethodsTest, ProtectedFixtureMethodsTest, ProtectedFixtureMethodsTest, testing::InitGoogleTestTest, testing::InitGoogleTestTest, testing::InitGoogleTestTest, testing::SetUpTestCaseTest, testing::SetUpTestCaseTest, testing::SetUpTestCaseTest, Predicate5Test, Predicate5Test, Predicate5Test, MockHTTP2UpstreamTest, MockHTTPUpstreamTest, Predicate4Test, Predicate4Test, Predicate4Test, Predicate3Test, Predicate3Test, Predicate3Test, HTTP2UpstreamSessionWithVirtualNodesTest, ScopedServerTest, Predicate2Test, Predicate2Test, Predicate2Test, AsyncUDPSocketTest, FatalFailureInSetUpTest, FatalFailureInSetUpTest, FatalFailureInSetUpTest, NonFatalFailureInSetUpTest, NonFatalFailureInSetUpTest, NonFatalFailureInSetUpTest, FatalFailureInFixtureConstructorTest, FatalFailureInFixtureConstructorTest, FatalFailureInFixtureConstructorTest, NonFatalFailureInFixtureConstructorTest, NonFatalFailureInFixtureConstructorTest, NonFatalFailureInFixtureConstructorTest, AsyncSocketIntegrationTest, folly::test::ReadFileFd, AsyncSocketGSOIntegrationTest, folly::SynchronizedLockTest, fizz::test::ZlibCertificateCompressorTest, HTTPUpstreamTest< C >, HTTPUpstreamTest< MockHTTPCodecPair >, HTTPUpstreamTest< SPDY3CodecPair >, StructPaddedConstTest, BufferedSlidingWindowTest, MockCodecDownstreamTest, proxygen::RFC1867Test, fizz::test::ValidateAuthenticatorTest, testing::internal::ListenerTest, testing::internal::ListenerTest, testing::internal::ListenerTest, QueueTest, QueueTest, QueueTest, HTTPDownstreamTest< C >, HTTPDownstreamTest< SPDY3_1CodecPair >, GenericFilterTest< Owned >, Predicate1Test, Predicate1Test, Predicate1Test, fizz::test::CertTestTyped< T >, LRUPersistentCacheTest< MutexT >, TimeoutTest, IntPaddedConstTest, BufferedDigestTest, fizz::server::test::AeadTicketCipherTest, folly::symbolizer::test::ElfCacheTest, QueueTest, QueueTest, QueueTest, CommonTest< T >, CommonTest< T >, CommonTest< T >, QuickTest, fizz::test::AuthenticatorTest, QuickTest, QuickTest, wangle::AcceptorTest, EventHandlerTest, FlowControlFilterTest< initSize >, ThreadSafeSSLSessionCacheTest, folly::SSLSessionTest, fizz::test::HandshakeTest, fizz::server::test::FizzServerTest, PeekingAcceptorHandshakeHelperTest, wangle::SSLSessionPersistentCacheTest, fizz::client::test::AsyncFizzClientTest, HTTPChecksTest, HTTP2CodecTest, fizz::server::test::GetCookieStateTest, RequestContextTest, fizz::client::test::FizzClientTest, SocketPeekerTest, fizz::server::test::AsyncFizzServerTest, fizz::server::test::AeadCookieCipherTest, AcceptRoutingHandlerTest, MultiFilePollerTest, PropertyOne, PropertyTwo, PropertyOne, PropertyTwo, PropertyOne, PropertyTwo, EvbHandshakeHelperTest, ZlibServerFilterTest, fizz::extensions::test::ValidatorTest, BroadcastHandlerTest, SSLSessionCacheDataTest, ByteEventTrackerTest, DownstreamTransactionTest, ObservingHandlerTest, ProcessTicketTest, fizz::server::test::ServerProtocolTest, LoggerTest, fizz::client::test::ClientProtocolTest, fizz::extensions::test::TokenBindingServerExtensionTest, fizz::extensions::test::TokenBindingConstructorTest, SlidingWindowTest, EchoHandlerFixture, BroadcastPoolTest, fizz::test::EncryptedRecordTest, fizz::client::test::SynchronizedLruPskCacheTest, fizz::test::DefaultCertificateVerifierTest, fizz::test::KeySchedulerTest, HTTPParallelCodecTest, fizz::extensions::test::TokenBindingClientExtensionTest, fizz::test::CertDecompressionManagerTest, and fizz::test::RSAPSSTest.
Definition at line 2227 of file gtest.cc.
Referenced by Run(), ProtectedFixtureMethodsTest::SetUp(), and testing::TestPartNonfatallyFailed().
                  {
 }
virtual void testing::Test::SetUp () protected virtual
Reimplemented in ProtectedFixtureMethodsTest, ProtectedFixtureMethodsTest, ProtectedFixtureMethodsTest, testing::InitGoogleTestTest, testing::InitGoogleTestTest, testing::InitGoogleTestTest, testing::SetUpTestCaseTest, testing::SetUpTestCaseTest, testing::SetUpTestCaseTest, Predicate5Test, Predicate5Test, Predicate5Test, MockHTTP2UpstreamTest, MockHTTPUpstreamTest, Predicate4Test, Predicate4Test, Predicate4Test, Predicate3Test, Predicate3Test, Predicate3Test, HTTP2UpstreamSessionWithVirtualNodesTest, ScopedServerTest, Predicate2Test, Predicate2Test, Predicate2Test, AsyncUDPSocketTest, FatalFailureInSetUpTest, FatalFailureInSetUpTest, FatalFailureInSetUpTest, NonFatalFailureInSetUpTest, NonFatalFailureInSetUpTest, NonFatalFailureInSetUpTest, FatalFailureInFixtureConstructorTest, FatalFailureInFixtureConstructorTest, FatalFailureInFixtureConstructorTest, NonFatalFailureInFixtureConstructorTest, NonFatalFailureInFixtureConstructorTest, NonFatalFailureInFixtureConstructorTest, AsyncSocketIntegrationTest, folly::test::ReadFileFd, AsyncSocketGSOIntegrationTest, folly::SynchronizedLockTest, fizz::test::ZlibCertificateCompressorTest, HTTPUpstreamTest< C >, HTTPUpstreamTest< MockHTTPCodecPair >, HTTPUpstreamTest< SPDY3CodecPair >, StructPaddedConstTest, BufferedSlidingWindowTest, MockCodecDownstreamTest, proxygen::RFC1867Test, fizz::test::ValidateAuthenticatorTest, testing::internal::ListenerTest, testing::internal::ListenerTest, testing::internal::ListenerTest, QueueTest, QueueTest, QueueTest, HTTPDownstreamTest< C >, HTTPDownstreamTest< SPDY3_1CodecPair >, GenericFilterTest< Owned >, Predicate1Test, Predicate1Test, Predicate1Test, fizz::test::CertTestTyped< T >, LRUPersistentCacheTest< MutexT >, TimeoutTest, IntPaddedConstTest, BufferedDigestTest, fizz::server::test::AeadTicketCipherTest, folly::symbolizer::test::ElfCacheTest, QueueTest, QueueTest, QueueTest, CommonTest< T >, CommonTest< T >, CommonTest< T >, QuickTest, fizz::test::AuthenticatorTest, QuickTest, QuickTest, wangle::AcceptorTest, EventHandlerTest, FlowControlFilterTest< initSize >, ThreadSafeSSLSessionCacheTest, folly::SSLSessionTest, fizz::test::HandshakeTest, fizz::server::test::FizzServerTest, PeekingAcceptorHandshakeHelperTest, wangle::SSLSessionPersistentCacheTest, fizz::client::test::AsyncFizzClientTest, HTTPChecksTest, HTTP2CodecTest, fizz::server::test::GetCookieStateTest, RequestContextTest, fizz::client::test::FizzClientTest, SocketPeekerTest, fizz::server::test::AsyncFizzServerTest, fizz::server::test::AeadCookieCipherTest, AcceptRoutingHandlerTest, MultiFilePollerTest, PropertyOne, PropertyTwo, PropertyOne, PropertyTwo, PropertyOne, PropertyTwo, EvbHandshakeHelperTest, ZlibServerFilterTest, fizz::extensions::test::ValidatorTest, BroadcastHandlerTest, SSLSessionCacheDataTest, ByteEventTrackerTest, DownstreamTransactionTest, ObservingHandlerTest, ProcessTicketTest, fizz::server::test::ServerProtocolTest, LoggerTest, fizz::client::test::ClientProtocolTest, fizz::extensions::test::TokenBindingServerExtensionTest, fizz::extensions::test::TokenBindingConstructorTest, SlidingWindowTest, EchoHandlerFixture, BroadcastPoolTest, fizz::test::EncryptedRecordTest, fizz::client::test::SynchronizedLruPskCacheTest, fizz::test::DefaultCertificateVerifierTest, fizz::test::KeySchedulerTest, HTTPParallelCodecTest, fizz::extensions::test::TokenBindingClientExtensionTest, fizz::test::CertDecompressionManagerTest, and fizz::test::RSAPSSTest.
virtual void testing::Test::SetUp () protected virtual
Reimplemented in ProtectedFixtureMethodsTest, ProtectedFixtureMethodsTest, ProtectedFixtureMethodsTest, testing::InitGoogleTestTest, testing::InitGoogleTestTest, testing::InitGoogleTestTest, testing::SetUpTestCaseTest, testing::SetUpTestCaseTest, testing::SetUpTestCaseTest, Predicate5Test, Predicate5Test, Predicate5Test, MockHTTP2UpstreamTest, MockHTTPUpstreamTest, Predicate4Test, Predicate4Test, Predicate4Test, Predicate3Test, Predicate3Test, Predicate3Test, HTTP2UpstreamSessionWithVirtualNodesTest, ScopedServerTest, Predicate2Test, Predicate2Test, Predicate2Test, AsyncUDPSocketTest, FatalFailureInSetUpTest, FatalFailureInSetUpTest, FatalFailureInSetUpTest, NonFatalFailureInSetUpTest, NonFatalFailureInSetUpTest, NonFatalFailureInSetUpTest, FatalFailureInFixtureConstructorTest, FatalFailureInFixtureConstructorTest, FatalFailureInFixtureConstructorTest, NonFatalFailureInFixtureConstructorTest, NonFatalFailureInFixtureConstructorTest, NonFatalFailureInFixtureConstructorTest, AsyncSocketIntegrationTest, folly::test::ReadFileFd, AsyncSocketGSOIntegrationTest, folly::SynchronizedLockTest, fizz::test::ZlibCertificateCompressorTest, HTTPUpstreamTest< C >, HTTPUpstreamTest< MockHTTPCodecPair >, HTTPUpstreamTest< SPDY3CodecPair >, StructPaddedConstTest, BufferedSlidingWindowTest, MockCodecDownstreamTest, proxygen::RFC1867Test, fizz::test::ValidateAuthenticatorTest, testing::internal::ListenerTest, testing::internal::ListenerTest, testing::internal::ListenerTest, QueueTest, QueueTest, QueueTest, HTTPDownstreamTest< C >, HTTPDownstreamTest< SPDY3_1CodecPair >, GenericFilterTest< Owned >, Predicate1Test, Predicate1Test, Predicate1Test, fizz::test::CertTestTyped< T >, LRUPersistentCacheTest< MutexT >, TimeoutTest, IntPaddedConstTest, BufferedDigestTest, fizz::server::test::AeadTicketCipherTest, folly::symbolizer::test::ElfCacheTest, QueueTest, QueueTest, QueueTest, CommonTest< T >, CommonTest< T >, CommonTest< T >, QuickTest, fizz::test::AuthenticatorTest, QuickTest, QuickTest, wangle::AcceptorTest, EventHandlerTest, FlowControlFilterTest< initSize >, ThreadSafeSSLSessionCacheTest, folly::SSLSessionTest, fizz::test::HandshakeTest, fizz::server::test::FizzServerTest, PeekingAcceptorHandshakeHelperTest, wangle::SSLSessionPersistentCacheTest, fizz::client::test::AsyncFizzClientTest, HTTPChecksTest, HTTP2CodecTest, fizz::server::test::GetCookieStateTest, RequestContextTest, fizz::client::test::FizzClientTest, SocketPeekerTest, fizz::server::test::AsyncFizzServerTest, fizz::server::test::AeadCookieCipherTest, AcceptRoutingHandlerTest, MultiFilePollerTest, PropertyOne, PropertyTwo, PropertyOne, PropertyTwo, PropertyOne, PropertyTwo, EvbHandshakeHelperTest, ZlibServerFilterTest, fizz::extensions::test::ValidatorTest, BroadcastHandlerTest, SSLSessionCacheDataTest, ByteEventTrackerTest, DownstreamTransactionTest, ObservingHandlerTest, ProcessTicketTest, fizz::server::test::ServerProtocolTest, LoggerTest, fizz::client::test::ClientProtocolTest, fizz::extensions::test::TokenBindingServerExtensionTest, fizz::extensions::test::TokenBindingConstructorTest, SlidingWindowTest, EchoHandlerFixture, BroadcastPoolTest, fizz::test::EncryptedRecordTest, fizz::client::test::SynchronizedLruPskCacheTest, fizz::test::DefaultCertificateVerifierTest, fizz::test::KeySchedulerTest, HTTPParallelCodecTest, fizz::extensions::test::TokenBindingClientExtensionTest, fizz::test::CertDecompressionManagerTest, and fizz::test::RSAPSSTest.
virtual Setup_should_be_spelled_SetUp* testing::Test::Setup () inline private virtual
Definition at line 474 of file gtest.h.
References GTEST_DISALLOW_COPY_AND_ASSIGN_.
 { return NULL; }
virtual Setup_should_be_spelled_SetUp* testing::Test::Setup () inline private virtual
Definition at line 474 of file gtest.h.
References GTEST_DISALLOW_COPY_AND_ASSIGN_.
 { return NULL; }
virtual Setup_should_be_spelled_SetUp* testing::Test::Setup () inline private virtual
Definition at line 474 of file gtest.h.
References GTEST_DISALLOW_COPY_AND_ASSIGN_.
 { return NULL; }
static void testing::Test::SetUpTestCase () inline static
Definition at line 389 of file gtest.h.
 {}
static void testing::Test::SetUpTestCase () inline static
Definition at line 389 of file gtest.h.
 {}
static void testing::Test::SetUpTestCase () inline static
Definition at line 389 of file gtest.h.
 {}
virtual void testing::Test::TearDown () protected virtual
Reimplemented in ProtectedFixtureMethodsTest, ProtectedFixtureMethodsTest, ProtectedFixtureMethodsTest, Predicate5Test, Predicate5Test, Predicate5Test, MockHTTPUpstreamTest, Predicate4Test, Predicate4Test, Predicate4Test, Predicate3Test, Predicate3Test, Predicate3Test, HTTP2UpstreamSessionWithVirtualNodesTest, Predicate2Test, Predicate2Test, Predicate2Test, FatalFailureInSetUpTest, FatalFailureInSetUpTest, FatalFailureInSetUpTest, NonFatalFailureInSetUpTest, NonFatalFailureInSetUpTest, NonFatalFailureInSetUpTest, FatalFailureInFixtureConstructorTest, FatalFailureInFixtureConstructorTest, FatalFailureInFixtureConstructorTest, NonFatalFailureInFixtureConstructorTest, NonFatalFailureInFixtureConstructorTest, NonFatalFailureInFixtureConstructorTest, AsyncSocketIntegrationTest, AsyncSocketGSOIntegrationTest, HTTPUpstreamTest< C >, HTTPUpstreamTest< MockHTTPCodecPair >, HTTPUpstreamTest< SPDY3CodecPair >, fizz::test::ZlibCertificateCompressorTest, testing::internal::ListenerTest, testing::internal::ListenerTest, testing::internal::ListenerTest, AcceptRoutingHandlerTest, Predicate1Test, Predicate1Test, Predicate1Test, PeekingAcceptorHandshakeHelperTest, CommonTest< T >, CommonTest< T >, CommonTest< T >, QuickTest, QuickTest, QuickTest, wangle::SSLSessionPersistentCacheTest, EventHandlerTest, folly::SSLSessionTest, EvbHandshakeHelperTest, BroadcastHandlerTest, SocketPeekerTest, ObservingHandlerTest, ZlibServerFilterTest, BroadcastPoolTest, PropertyOne, PropertyTwo, PropertyOne, PropertyTwo, PropertyOne, PropertyTwo, ProcessTicketTest, SSLSessionCacheDataTest, MallctlHelperTest, fizz::test::AsyncFizzBaseTest, fizz::test::DefaultCertificateVerifierTest, EchoHandlerFixture, and fizz::test::CertDecompressionManagerTest.
virtual void testing::Test::TearDown () protected virtual
Reimplemented in ProtectedFixtureMethodsTest, ProtectedFixtureMethodsTest, ProtectedFixtureMethodsTest, Predicate5Test, Predicate5Test, Predicate5Test, MockHTTPUpstreamTest, Predicate4Test, Predicate4Test, Predicate4Test, Predicate3Test, Predicate3Test, Predicate3Test, HTTP2UpstreamSessionWithVirtualNodesTest, Predicate2Test, Predicate2Test, Predicate2Test, FatalFailureInSetUpTest, FatalFailureInSetUpTest, FatalFailureInSetUpTest, NonFatalFailureInSetUpTest, NonFatalFailureInSetUpTest, NonFatalFailureInSetUpTest, FatalFailureInFixtureConstructorTest, FatalFailureInFixtureConstructorTest, FatalFailureInFixtureConstructorTest, NonFatalFailureInFixtureConstructorTest, NonFatalFailureInFixtureConstructorTest, NonFatalFailureInFixtureConstructorTest, AsyncSocketIntegrationTest, AsyncSocketGSOIntegrationTest, HTTPUpstreamTest< C >, HTTPUpstreamTest< MockHTTPCodecPair >, HTTPUpstreamTest< SPDY3CodecPair >, fizz::test::ZlibCertificateCompressorTest, testing::internal::ListenerTest, testing::internal::ListenerTest, testing::internal::ListenerTest, AcceptRoutingHandlerTest, Predicate1Test, Predicate1Test, Predicate1Test, PeekingAcceptorHandshakeHelperTest, CommonTest< T >, CommonTest< T >, CommonTest< T >, QuickTest, QuickTest, QuickTest, wangle::SSLSessionPersistentCacheTest, EventHandlerTest, folly::SSLSessionTest, EvbHandshakeHelperTest, BroadcastHandlerTest, SocketPeekerTest, ObservingHandlerTest, ZlibServerFilterTest, BroadcastPoolTest, PropertyOne, PropertyTwo, PropertyOne, PropertyTwo, PropertyOne, PropertyTwo, ProcessTicketTest, SSLSessionCacheDataTest, MallctlHelperTest, fizz::test::AsyncFizzBaseTest, fizz::test::DefaultCertificateVerifierTest, EchoHandlerFixture, and fizz::test::CertDecompressionManagerTest.
void Test::TearDown () protected virtual
Reimplemented in ProtectedFixtureMethodsTest, ProtectedFixtureMethodsTest, ProtectedFixtureMethodsTest, Predicate5Test, Predicate5Test, Predicate5Test, MockHTTPUpstreamTest, Predicate4Test, Predicate4Test, Predicate4Test, Predicate3Test, Predicate3Test, Predicate3Test, HTTP2UpstreamSessionWithVirtualNodesTest, Predicate2Test, Predicate2Test, Predicate2Test, FatalFailureInSetUpTest, FatalFailureInSetUpTest, FatalFailureInSetUpTest, NonFatalFailureInSetUpTest, NonFatalFailureInSetUpTest, NonFatalFailureInSetUpTest, FatalFailureInFixtureConstructorTest, FatalFailureInFixtureConstructorTest, FatalFailureInFixtureConstructorTest, NonFatalFailureInFixtureConstructorTest, NonFatalFailureInFixtureConstructorTest, NonFatalFailureInFixtureConstructorTest, AsyncSocketIntegrationTest, AsyncSocketGSOIntegrationTest, HTTPUpstreamTest< C >, HTTPUpstreamTest< MockHTTPCodecPair >, HTTPUpstreamTest< SPDY3CodecPair >, fizz::test::ZlibCertificateCompressorTest, testing::internal::ListenerTest, testing::internal::ListenerTest, testing::internal::ListenerTest, AcceptRoutingHandlerTest, Predicate1Test, Predicate1Test, Predicate1Test, PeekingAcceptorHandshakeHelperTest, CommonTest< T >, CommonTest< T >, CommonTest< T >, QuickTest, QuickTest, QuickTest, wangle::SSLSessionPersistentCacheTest, EventHandlerTest, folly::SSLSessionTest, EvbHandshakeHelperTest, BroadcastHandlerTest, SocketPeekerTest, ObservingHandlerTest, ZlibServerFilterTest, BroadcastPoolTest, PropertyOne, PropertyTwo, PropertyOne, PropertyTwo, PropertyOne, PropertyTwo, ProcessTicketTest, SSLSessionCacheDataTest, MallctlHelperTest, fizz::test::AsyncFizzBaseTest, fizz::test::DefaultCertificateVerifierTest, EchoHandlerFixture, and fizz::test::CertDecompressionManagerTest.
Definition at line 2233 of file gtest.cc.
Referenced by Run(), ProtectedFixtureMethodsTest::TearDown(), testing::TEST_F(), and testing::TestPartNonfatallyFailed().
                     {
 }
static void testing::Test::TearDownTestCase () inline static
Definition at line 397 of file gtest.h.
 {}
static void testing::Test::TearDownTestCase () inline static
Definition at line 397 of file gtest.h.
 {}
static void testing::Test::TearDownTestCase () inline static
Definition at line 397 of file gtest.h.
 {}
virtual void testing::Test::TestBody () private pure virtual
virtual void testing::Test::TestBody () private pure virtual
virtual void testing::Test::TestBody () private pure virtual
Referenced by Run(), and testing::TestPartNonfatallyFailed().
Friends And Related Function Documentation
TestInfo friend
Definition at line 373 of file gtest.h.
Member Data Documentation
const internal::scoped_ptr< GTEST_FLAG_SAVER_ > Test::gtest_flag_saver_ private
Definition at line 455 of file gtest.h.
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/gtest.h
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest.cc