proxygen: wangle::SSLStats Class Reference
wangle::SSLStats Class Reference abstract
#include <SSLStats.h>
Public Member Functions
virtual ~SSLStats () noexcept
virtual void recordSSLAcceptLatency (int64_t latency) noexcept=0
virtual void recordTLSTicket (bool ticketNew, bool ticketHit) noexcept=0
virtual void recordSSLSession (bool sessionNew, bool sessionHit, bool foreign) noexcept=0
virtual void recordSSLSessionRemove () noexcept=0
virtual void recordSSLSessionFree (uint32_t freed) noexcept=0
virtual void recordSSLSessionSetError (uint32_t err) noexcept=0
virtual void recordSSLSessionGetError (uint32_t err) noexcept=0
virtual void recordClientRenegotiation () noexcept=0
virtual void recordSSLClientCertificateMismatch () noexcept=0
virtual void recordTLSTicketRotation (bool valid) noexcept=0
virtual void recordSSLUpstreamConnection (bool handshake) noexcept=0
virtual void recordSSLUpstreamConnectionError (bool verifyError) noexcept=0
Detailed Description
Definition at line 22 of file SSLStats.h.
Constructor & Destructor Documentation
virtual wangle::SSLStats::~SSLStats () inline virtual noexcept
Definition at line 24 of file SSLStats.h.
References freed, int64_t, folly::pushmi::__adl::noexcept(), recordClientRenegotiation(), recordSSLAcceptLatency(), recordSSLClientCertificateMismatch(), recordSSLSession(), recordSSLSessionFree(), recordSSLSessionGetError(), recordSSLSessionRemove(), recordSSLSessionSetError(), recordSSLUpstreamConnection(), recordSSLUpstreamConnectionError(), recordTLSTicket(), recordTLSTicketRotation(), and uint32_t.
 {}
Member Function Documentation
virtual void wangle::SSLStats::recordClientRenegotiation () pure virtual noexcept
Implemented in MockSSLStats.
Referenced by ~SSLStats().
virtual void wangle::SSLStats::recordSSLAcceptLatency (int64_t latency) pure virtual noexcept
Implemented in MockSSLStats.
Referenced by ~SSLStats().
virtual void wangle::SSLStats::recordSSLClientCertificateMismatch () pure virtual noexcept
Implemented in MockSSLStats.
Referenced by ~SSLStats().
virtual void wangle::SSLStats::recordSSLSession (bool sessionNew, bool sessionHit, bool foreign) pure virtual noexcept
Implemented in MockSSLStats.
Referenced by wangle::SSLSessionCacheManager::getSession(), wangle::SSLSessionCacheManager::newSession(), and ~SSLStats().
virtual void wangle::SSLStats::recordSSLSessionFree (uint32_t freed) pure virtual noexcept
Implemented in MockSSLStats.
Referenced by wangle::ShardedLocalSSLSessionCache::storeSession(), and ~SSLStats().
virtual void wangle::SSLStats::recordSSLSessionGetError (uint32_t err) pure virtual noexcept
Implemented in MockSSLStats.
Referenced by ~SSLStats().
virtual void wangle::SSLStats::recordSSLSessionRemove () pure virtual noexcept
Implemented in MockSSLStats.
Referenced by wangle::SSLSessionCacheManager::removeSession(), and ~SSLStats().
virtual void wangle::SSLStats::recordSSLSessionSetError (uint32_t err) pure virtual noexcept
Implemented in MockSSLStats.
Referenced by ~SSLStats().
virtual void wangle::SSLStats::recordSSLUpstreamConnection (bool handshake) pure virtual noexcept
Implemented in MockSSLStats.
Referenced by ~SSLStats().
virtual void wangle::SSLStats::recordSSLUpstreamConnectionError (bool verifyError) pure virtual noexcept
Implemented in MockSSLStats.
Referenced by ~SSLStats().
virtual void wangle::SSLStats::recordTLSTicket (bool ticketNew, bool ticketHit) pure virtual noexcept
Implemented in MockSSLStats.
Referenced by ~SSLStats().
virtual void wangle::SSLStats::recordTLSTicketRotation (bool valid) pure virtual noexcept
Referenced by TEST(), and ~SSLStats().
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/ssl/SSLStats.h