proxygen: gtest_uninitialized_test.GTestUninitializedTest Class Reference
gtest_uninitialized_test.GTestUninitializedTest Class Reference
Public Member Functions
def testExitCodeAndOutput (self)
def testExitCodeAndOutput (self)
def testExitCodeAndOutput (self)
Detailed Description
Definition at line 64 of file gtest_uninitialized_test.py.
Member Function Documentation
def gtest_uninitialized_test.GTestUninitializedTest.testExitCodeAndOutput (self)
Definition at line 65 of file gtest_uninitialized_test.py.
References gtest_test_utils.Main(), and gtest_uninitialized_test.TestExitCodeAndOutput().
Referenced by gtest_uninitialized_test.GTestUninitializedTest.testExitCodeAndOutput().
   def testExitCodeAndOutput(self):
     TestExitCodeAndOutput(COMMAND)
def gtest_uninitialized_test.GTestUninitializedTest.testExitCodeAndOutput (self)
Definition at line 65 of file gtest_uninitialized_test.py.
References gtest_test_utils.Main(), gtest_uninitialized_test.TestExitCodeAndOutput(), and gtest_uninitialized_test.GTestUninitializedTest.testExitCodeAndOutput().
   def testExitCodeAndOutput(self):
     TestExitCodeAndOutput(COMMAND)
def gtest_uninitialized_test.GTestUninitializedTest.testExitCodeAndOutput (self)
Definition at line 65 of file gtest_uninitialized_test.py.
References gtest_test_utils.Main(), gtest_uninitialized_test.TestExitCodeAndOutput(), and gtest_uninitialized_test.GTestUninitializedTest.testExitCodeAndOutput().
   def testExitCodeAndOutput(self):
     TestExitCodeAndOutput(COMMAND)
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest_uninitialized_test.py