proxygen: folly::fibers::CacheManager Class Reference
folly::fibers::CacheManager Class Reference
Public Member Functions
std::unique_ptr< StackCacheEntry > getStackCache (size_t stackSize)
Static Public Member Functions
static CacheManager & instance ()
Private Member Functions
void giveBack (std::unique_ptr< StackCache >)
Private Attributes
folly::SpinLock lock_
size_t inUse_ {0}
Friends
class StackCacheEntry
Detailed Description
Definition at line 236 of file GuardPageAllocator.cpp.
Member Function Documentation
std::unique_ptr<StackCacheEntry> folly::fibers::CacheManager::getStackCache (size_t stackSize) inline
Definition at line 243 of file GuardPageAllocator.cpp.
References folly::fibers::StackCache::lock_.
Referenced by folly::fibers::GuardPageAllocator::allocate().
{
     std::lock_guard<folly::SpinLock> lg(lock_);
     if (inUse_ < kMaxInUse) {
       ++inUse_;
       return std::make_unique<StackCacheEntry>(stackSize);
     }
     return nullptr;
   }
void folly::fibers::CacheManager::giveBack (std::unique_ptr< StackCache >) inline private
Definition at line 259 of file GuardPageAllocator.cpp.
Referenced by folly::fibers::StackCacheEntry::~StackCacheEntry().
{
     assert(inUse_ > 0);
     --inUse_;
     /* Note: we can add a free list for each size bucket
        if stack re-use is important.
        In this case this needs to be a folly::Singleton
        to make sure the free list is cleaned up on fork.
        TODO(t7351705): fix Singleton destruction order
     */
   }
static CacheManager& folly::fibers::CacheManager::instance () inline static
Definition at line 238 of file GuardPageAllocator.cpp.
Referenced by folly::fibers::GuardPageAllocator::allocate(), and folly::fibers::StackCacheEntry::~StackCacheEntry().
{
     static auto inst = new CacheManager();
     return *inst;
   }
Friends And Related Function Documentation
friend class StackCacheEntry friend
Definition at line 257 of file GuardPageAllocator.cpp.
Member Data Documentation
size_t folly::fibers::CacheManager::inUse_ {0} private
Definition at line 255 of file GuardPageAllocator.cpp.
folly::SpinLock folly::fibers::CacheManager::lock_ private
Definition at line 254 of file GuardPageAllocator.cpp.
The documentation for this class was generated from the following file:
proxygen/folly/folly/fibers/GuardPageAllocator.cpp