proxygen: folly::MultiLevelTimeSeries< VT, CT > Class Template Reference
folly::MultiLevelTimeSeries< VT, CT > Class Template Reference
#include <MultiLevelTimeSeries.h>
Public Types
using ValueType = VT
using Clock = CT
using Duration = typename Clock::duration
using TimePoint = typename Clock::time_point
using Level = folly::BucketedTimeSeries< ValueType, Clock >
Public Member Functions
MultiLevelTimeSeries (size_t numBuckets, size_t numLevels, const Duration levelDurations[])
MultiLevelTimeSeries (size_t numBuckets, std::initializer_list< Duration > durations)
size_t numBuckets () const
size_t numLevels () const
const Level & getLevel (size_t level) const
const Level & getLevel (TimePoint start) const
const Level & getLevelByDuration (Duration duration) const
ValueType sum (size_t level) const
template<typename ReturnType = double>
ReturnType avg (size_t level) const
template<typename ReturnType = double, typename Interval = Duration>
ReturnType rate (size_t level) const
uint64_t count (size_t level) const
template<typename ReturnType = double, typename Interval = Duration>
ReturnType countRate (size_t level) const
ValueType sum (Duration duration) const
template<typename ReturnType = double>
ReturnType avg (Duration duration) const
template<typename ReturnType = double, typename Interval = Duration>
ReturnType rate (Duration duration) const
uint64_t count (Duration duration) const
template<typename ReturnType = double, typename Interval = Duration>
ReturnType countRate (Duration duration) const
ValueType sum (TimePoint start, TimePoint end) const
template<typename ReturnType = double>
ReturnType avg (TimePoint start, TimePoint end) const
template<typename ReturnType = double>
ReturnType rate (TimePoint start, TimePoint end) const
uint64_t count (TimePoint start, TimePoint end) const
void addValue (TimePoint now, const ValueType &val)
void addValue (TimePoint now, const ValueType &val, uint64_t times)
void addValueAggregated (TimePoint now, const ValueType &total, uint64_t nsamples)
void update (TimePoint now)
void clear ()
void flush ()
void update (Duration now)
void addValue (Duration now, const ValueType &value)
void addValue (Duration now, const ValueType &value, uint64_t times)
void addValueAggregated (Duration now, const ValueType &total, uint64_t nsamples)
Private Attributes
std::vector< Level > levels_
TimePoint cachedTime_
ValueType cachedSum_
uint64_t cachedCount_
Detailed Description
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>>
class folly::MultiLevelTimeSeries< VT, CT >
Definition at line 53 of file MultiLevelTimeSeries.h.
Member Typedef Documentation
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> using folly::MultiLevelTimeSeries< VT, CT >::Clock = CT
Definition at line 56 of file MultiLevelTimeSeries.h.
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> using folly::MultiLevelTimeSeries< VT, CT >::Duration = typename Clock::duration
Definition at line 57 of file MultiLevelTimeSeries.h.
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> using folly::MultiLevelTimeSeries< VT, CT >::Level = folly::BucketedTimeSeries<ValueType, Clock>
Definition at line 59 of file MultiLevelTimeSeries.h.
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> using folly::MultiLevelTimeSeries< VT, CT >::TimePoint = typename Clock::time_point
Definition at line 58 of file MultiLevelTimeSeries.h.
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> using folly::MultiLevelTimeSeries< VT, CT >::ValueType = VT
Definition at line 55 of file MultiLevelTimeSeries.h.
Constructor & Destructor Documentation
template<typename VT , typename CT > folly::MultiLevelTimeSeries< VT, CT >::MultiLevelTimeSeries (size_t numBuckets, size_t numLevels, const Duration levelDurations[])
Definition at line 25 of file MultiLevelTimeSeries-defs.h.
References i, and folly::MultiLevelTimeSeries< VT, CT >::levels_.
     : cachedTime_(), cachedSum_(0), cachedCount_(0) {
   CHECK_GT(nLevels, 0u);
   CHECK(levelDurations);
   levels_.reserve(nLevels);
   for (size_t i = 0; i < nLevels; ++i) {
     if (levelDurations[i] == Duration(0)) {
       CHECK_EQ(i, nLevels - 1);
     } else if (i > 0) {
       CHECK(levelDurations[i - 1] < levelDurations[i]);
     }
     levels_.emplace_back(nBuckets, levelDurations[i]);
   }
 }
template<typename VT , typename CT > folly::MultiLevelTimeSeries< VT, CT >::MultiLevelTimeSeries (size_t numBuckets, std::initializer_list< Duration > durations)
Definition at line 45 of file MultiLevelTimeSeries-defs.h.
References i, and folly::MultiLevelTimeSeries< VT, CT >::levels_.
     : cachedTime_(), cachedSum_(0), cachedCount_(0) {
   CHECK_GT(durations.size(), 0u);
   levels_.reserve(durations.size());
   size_t i = 0;
   Duration prev{0};
   for (auto dur : durations) {
     if (dur == Duration(0)) {
       CHECK_EQ(i, durations.size() - 1);
     } else if (i > 0) {
       CHECK(prev < dur);
     }
     levels_.emplace_back(nBuckets, dur);
     prev = dur;
     i++;
   }
 }
Member Function Documentation
template<typename VT , typename CT > void folly::MultiLevelTimeSeries< VT, CT >::addValue (TimePoint now, const ValueType & val)
Definition at line 67 of file MultiLevelTimeSeries-defs.h.
References folly::MultiLevelTimeSeries< VT, CT >::addValueAggregated().
Referenced by folly::MultiLevelTimeSeries< VT, CT >::addValue(), folly::MultiLevelTimeSeries< VT, CT >::count(), and TEST().
{
   addValueAggregated(now, val, 1);
 }
template<typename VT , typename CT > void folly::MultiLevelTimeSeries< VT, CT >::addValue (TimePoint now, const ValueType & val, uint64_t times)
Definition at line 74 of file MultiLevelTimeSeries-defs.h.
References folly::MultiLevelTimeSeries< VT, CT >::addValueAggregated().
                     {
   addValueAggregated(now, val * ValueType(times), times);
 }
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> void folly::MultiLevelTimeSeries< VT, CT >::addValue (Duration now, const ValueType & value) inline
Definition at line 418 of file MultiLevelTimeSeries.h.
References folly::MultiLevelTimeSeries< VT, CT >::addValue().
{
     addValue(TimePoint(now), value);
   }
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> void folly::MultiLevelTimeSeries< VT, CT >::addValue (Duration now, const ValueType & value, uint64_t times) inline
Definition at line 421 of file MultiLevelTimeSeries.h.
References folly::MultiLevelTimeSeries< VT, CT >::addValue().
{
     addValue(TimePoint(now), value, times);
   }
template<typename VT , typename CT > void folly::MultiLevelTimeSeries< VT, CT >::addValueAggregated (TimePoint now, const ValueType & total, uint64_t nsamples)
Definition at line 82 of file MultiLevelTimeSeries-defs.h.
References folly::MultiLevelTimeSeries< VT, CT >::cachedCount_, folly::MultiLevelTimeSeries< VT, CT >::cachedSum_, folly::MultiLevelTimeSeries< VT, CT >::cachedTime_, folly::MultiLevelTimeSeries< VT, CT >::flush(), and now().
Referenced by folly::MultiLevelTimeSeries< VT, CT >::addValue(), folly::MultiLevelTimeSeries< VT, CT >::addValueAggregated(), and folly::MultiLevelTimeSeries< VT, CT >::count().
{
   if (cachedTime_ != now) {
     flush();
     cachedTime_ = now;
   }
   cachedSum_ += total;
   cachedCount_ += nsamples;
 }
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> void folly::MultiLevelTimeSeries< VT, CT >::addValueAggregated (Duration now, const ValueType & total, uint64_t nsamples) inline
Definition at line 425 of file MultiLevelTimeSeries.h.
References folly::MultiLevelTimeSeries< VT, CT >::addValueAggregated().
{
     addValueAggregated(TimePoint(now), total, nsamples);
   }
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> template<typename ReturnType = double> ReturnType folly::MultiLevelTimeSeries< VT, CT >::avg (size_t level) const inline
Definition at line 178 of file MultiLevelTimeSeries.h.
References folly::MultiLevelTimeSeries< VT, CT >::getLevel().
Referenced by TEST().
{
     return getLevel(level).template avg<ReturnType>();
   }
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> template<typename ReturnType = double> ReturnType folly::MultiLevelTimeSeries< VT, CT >::avg (Duration duration) const inline
Definition at line 244 of file MultiLevelTimeSeries.h.
References folly::MultiLevelTimeSeries< VT, CT >::getLevelByDuration().
{
     return getLevelByDuration(duration).template avg<ReturnType>();
   }
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> template<typename ReturnType = double> ReturnType folly::MultiLevelTimeSeries< VT, CT >::avg (TimePoint start, TimePoint end) const inline
Definition at line 327 of file MultiLevelTimeSeries.h.
References folly::test::end(), folly::MultiLevelTimeSeries< VT, CT >::getLevel(), and start.
{
     return getLevel(start).template avg<ReturnType>(start, end);
   }
template<typename VT , typename CT > void folly::MultiLevelTimeSeries< VT, CT >::clear ()
Definition at line 115 of file MultiLevelTimeSeries-defs.h.
References folly::MultiLevelTimeSeries< VT, CT >::cachedCount_, folly::MultiLevelTimeSeries< VT, CT >::cachedSum_, folly::MultiLevelTimeSeries< VT, CT >::cachedTime_, and folly::MultiLevelTimeSeries< VT, CT >::levels_.
Referenced by folly::MultiLevelTimeSeries< VT, CT >::count(), and TEST().
{
   for (auto& level : levels_) {
     level.clear();
   }
   cachedTime_ = TimePoint();
   cachedSum_ = 0;
   cachedCount_ = 0;
 }
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> uint64_t folly::MultiLevelTimeSeries< VT, CT >::count (size_t level) const inline
Definition at line 202 of file MultiLevelTimeSeries.h.
References folly::BucketedTimeSeries< VT, CT >::count(), and folly::MultiLevelTimeSeries< VT, CT >::getLevel().
Referenced by TEST().
{
     return getLevel(level).count();
   }
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> uint64_t folly::MultiLevelTimeSeries< VT, CT >::count (Duration duration) const inline
Definition at line 274 of file MultiLevelTimeSeries.h.
References folly::BucketedTimeSeries< VT, CT >::count(), and folly::MultiLevelTimeSeries< VT, CT >::getLevelByDuration().
{
     return getLevelByDuration(duration).count();
   }
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> uint64_t folly::MultiLevelTimeSeries< VT, CT >::count (TimePoint start, TimePoint end) const inline
Definition at line 356 of file MultiLevelTimeSeries.h.
References folly::MultiLevelTimeSeries< VT, CT >::addValue(), folly::MultiLevelTimeSeries< VT, CT >::addValueAggregated(), folly::MultiLevelTimeSeries< VT, CT >::clear(), folly::BucketedTimeSeries< VT, CT >::count(), folly::MultiLevelTimeSeries< VT, CT >::flush(), folly::MultiLevelTimeSeries< VT, CT >::getLevel(), now(), folly::times(), uint64_t, folly::MultiLevelTimeSeries< VT, CT >::update(), and val.
{
     return getLevel(start).count(start, end);
   }
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> template<typename ReturnType = double, typename Interval = Duration> ReturnType folly::MultiLevelTimeSeries< VT, CT >::countRate (size_t level) const inline
Definition at line 214 of file MultiLevelTimeSeries.h.
References folly::MultiLevelTimeSeries< VT, CT >::getLevel().
{
     return getLevel(level).template countRate<ReturnType, Interval>();
   }
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> template<typename ReturnType = double, typename Interval = Duration> ReturnType folly::MultiLevelTimeSeries< VT, CT >::countRate (Duration duration) const inline
Definition at line 289 of file MultiLevelTimeSeries.h.
References folly::MultiLevelTimeSeries< VT, CT >::getLevelByDuration().
{
     return getLevelByDuration(duration)
         .template countRate<ReturnType, Interval>();
   }
template<typename VT , typename CT > void folly::MultiLevelTimeSeries< VT, CT >::flush ()
Definition at line 103 of file MultiLevelTimeSeries-defs.h.
References folly::MultiLevelTimeSeries< VT, CT >::cachedCount_, folly::MultiLevelTimeSeries< VT, CT >::cachedSum_, folly::MultiLevelTimeSeries< VT, CT >::cachedTime_, i, and folly::MultiLevelTimeSeries< VT, CT >::levels_.
Referenced by folly::MultiLevelTimeSeries< VT, CT >::addValueAggregated(), folly::MultiLevelTimeSeries< VT, CT >::count(), TEST(), and folly::MultiLevelTimeSeries< VT, CT >::update().
{
   // update all the underlying levels
   if (cachedCount_ > 0) {
     for (size_t i = 0; i < levels_.size(); ++i) {
       levels_[i].addValueAggregated(cachedTime_, cachedSum_, cachedCount_);
     }
     cachedCount_ = 0;
     cachedSum_ = 0;
   }
 }
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> const Level& folly::MultiLevelTimeSeries< VT, CT >::getLevel (size_t level) const inline
Definition at line 103 of file MultiLevelTimeSeries.h.
References folly::MultiLevelTimeSeries< VT, CT >::levels_.
Referenced by folly::MultiLevelTimeSeries< VT, CT >::avg(), folly::MultiLevelTimeSeries< VT, CT >::count(), folly::MultiLevelTimeSeries< VT, CT >::countRate(), folly::MultiLevelTimeSeries< VT, CT >::rate(), folly::MultiLevelTimeSeries< VT, CT >::sum(), and TEST().
{
     CHECK_LT(level, levels_.size());
     return levels_[level];
   }
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> const Level& folly::MultiLevelTimeSeries< VT, CT >::getLevel (TimePoint start) const inline
Definition at line 116 of file MultiLevelTimeSeries.h.
References folly::BucketedTimeSeries< VT, CT >::count(), folly::FATAL, folly::MultiLevelTimeSeries< VT, CT >::levels_, and start.
{
     for (const auto& level : levels_) {
       if (level.isAllTime()) {
         return level;
       }
       // Note that we use duration() here rather than elapsed().
       // If duration is large enough to contain the start time then this level
       // is good enough, even if elapsed() indicates that no data was recorded
       // before the specified start time.
       if (level.getLatestTime() - level.duration() <= start) {
         return level;
       }
     }
     // We should always have an all-time level, so this is never reached.
     LOG(FATAL) << "No level of timeseries covers internval"
                << " from " << start.time_since_epoch().count() << " to now";
     return levels_.back();
   }
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> const Level& folly::MultiLevelTimeSeries< VT, CT >::getLevelByDuration (Duration duration) const inline
Definition at line 142 of file MultiLevelTimeSeries.h.
References folly::MultiLevelTimeSeries< VT, CT >::levels_.
Referenced by folly::MultiLevelTimeSeries< VT, CT >::avg(), folly::MultiLevelTimeSeries< VT, CT >::count(), folly::MultiLevelTimeSeries< VT, CT >::countRate(), folly::MultiLevelTimeSeries< VT, CT >::rate(), and folly::MultiLevelTimeSeries< VT, CT >::sum().
{
     // since the number of levels is expected to be small (less than 5 in most
     // cases), a simple linear scan would be efficient and is intentionally
     // chosen here over other alternatives for lookup.
     for (const auto& level : levels_) {
       if (level.duration() == duration) {
         return level;
       }
     }
     throw std::out_of_range(folly::to<std::string>(
         "No level of duration ", duration.count(), " found"));
   }
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> size_t folly::MultiLevelTimeSeries< VT, CT >::numBuckets () const inline
Definition at line 84 of file MultiLevelTimeSeries.h.
References folly::MultiLevelTimeSeries< VT, CT >::levels_.
{
     // The constructor ensures that levels_ has at least one item
     return levels_[0].numBuckets();
   }
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> size_t folly::MultiLevelTimeSeries< VT, CT >::numLevels () const inline
Definition at line 92 of file MultiLevelTimeSeries.h.
References folly::MultiLevelTimeSeries< VT, CT >::levels_.
Referenced by TEST().
{
     return levels_.size();
   }
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> template<typename ReturnType = double, typename Interval = Duration> ReturnType folly::MultiLevelTimeSeries< VT, CT >::rate (size_t level) const inline
Definition at line 191 of file MultiLevelTimeSeries.h.
References folly::MultiLevelTimeSeries< VT, CT >::getLevel().
Referenced by TEST().
{
     return getLevel(level).template rate<ReturnType, Interval>();
   }
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> template<typename ReturnType = double, typename Interval = Duration> ReturnType folly::MultiLevelTimeSeries< VT, CT >::rate (Duration duration) const inline
Definition at line 260 of file MultiLevelTimeSeries.h.
References folly::MultiLevelTimeSeries< VT, CT >::getLevelByDuration().
{
     return getLevelByDuration(duration).template rate<ReturnType, Interval>();
   }
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> template<typename ReturnType = double> ReturnType folly::MultiLevelTimeSeries< VT, CT >::rate (TimePoint start, TimePoint end) const inline
Definition at line 342 of file MultiLevelTimeSeries.h.
References folly::test::end(), folly::MultiLevelTimeSeries< VT, CT >::getLevel(), and start.
{
     return getLevel(start).template rate<ReturnType>(start, end);
   }
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> ValueType folly::MultiLevelTimeSeries< VT, CT >::sum (size_t level) const inline
Definition at line 162 of file MultiLevelTimeSeries.h.
References folly::MultiLevelTimeSeries< VT, CT >::getLevel(), and folly::BucketedTimeSeries< VT, CT >::sum().
Referenced by TEST().
{
     return getLevel(level).sum();
   }
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> ValueType folly::MultiLevelTimeSeries< VT, CT >::sum (Duration duration) const inline
Definition at line 228 of file MultiLevelTimeSeries.h.
References folly::MultiLevelTimeSeries< VT, CT >::getLevelByDuration(), and folly::BucketedTimeSeries< VT, CT >::sum().
{
     return getLevelByDuration(duration).sum();
   }
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> ValueType folly::MultiLevelTimeSeries< VT, CT >::sum (TimePoint start, TimePoint end) const inline
Definition at line 312 of file MultiLevelTimeSeries.h.
References folly::MultiLevelTimeSeries< VT, CT >::getLevel(), and folly::BucketedTimeSeries< VT, CT >::sum().
{
     return getLevel(start).sum(start, end);
   }
template<typename VT , typename CT > void folly::MultiLevelTimeSeries< VT, CT >::update (TimePoint now)
Definition at line 95 of file MultiLevelTimeSeries-defs.h.
References folly::MultiLevelTimeSeries< VT, CT >::flush(), i, and folly::MultiLevelTimeSeries< VT, CT >::levels_.
Referenced by folly::MultiLevelTimeSeries< VT, CT >::count(), and folly::MultiLevelTimeSeries< VT, CT >::update().
{
   flush();
   for (size_t i = 0; i < levels_.size(); ++i) {
     levels_[i].update(now);
   }
 }
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> void folly::MultiLevelTimeSeries< VT, CT >::update (Duration now) inline
Definition at line 415 of file MultiLevelTimeSeries.h.
References folly::MultiLevelTimeSeries< VT, CT >::update().
{
     update(TimePoint(now));
   }
Member Data Documentation
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> uint64_t folly::MultiLevelTimeSeries< VT, CT >::cachedCount_ private
Definition at line 437 of file MultiLevelTimeSeries.h.
Referenced by folly::MultiLevelTimeSeries< VT, CT >::addValueAggregated(), folly::MultiLevelTimeSeries< VT, CT >::clear(), and folly::MultiLevelTimeSeries< VT, CT >::flush().
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> ValueType folly::MultiLevelTimeSeries< VT, CT >::cachedSum_ private
Definition at line 436 of file MultiLevelTimeSeries.h.
Referenced by folly::MultiLevelTimeSeries< VT, CT >::addValueAggregated(), folly::MultiLevelTimeSeries< VT, CT >::clear(), and folly::MultiLevelTimeSeries< VT, CT >::flush().
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> TimePoint folly::MultiLevelTimeSeries< VT, CT >::cachedTime_ private
Definition at line 435 of file MultiLevelTimeSeries.h.
Referenced by folly::MultiLevelTimeSeries< VT, CT >::addValueAggregated(), folly::MultiLevelTimeSeries< VT, CT >::clear(), and folly::MultiLevelTimeSeries< VT, CT >::flush().
template<typename VT, typename CT = LegacyStatsClock<std::chrono::seconds>> std::vector<Level> folly::MultiLevelTimeSeries< VT, CT >::levels_ private
Definition at line 430 of file MultiLevelTimeSeries.h.
Referenced by folly::MultiLevelTimeSeries< VT, CT >::clear(), folly::MultiLevelTimeSeries< VT, CT >::flush(), folly::MultiLevelTimeSeries< VT, CT >::getLevel(), folly::MultiLevelTimeSeries< VT, CT >::getLevelByDuration(), folly::MultiLevelTimeSeries< VT, CT >::MultiLevelTimeSeries(), folly::MultiLevelTimeSeries< VT, CT >::numBuckets(), folly::MultiLevelTimeSeries< VT, CT >::numLevels(), and folly::MultiLevelTimeSeries< VT, CT >::update().
The documentation for this class was generated from the following files:
proxygen/folly/folly/stats/MultiLevelTimeSeries.h
proxygen/folly/folly/stats/MultiLevelTimeSeries-defs.h