proxygen: testing::SafeMatcherCastImpl< T > Class Template Reference
testing::SafeMatcherCastImpl< T > Class Template Reference
#include <gmock-matchers.h>
Static Public Member Functions
template<typename M >
static Matcher< T > Cast (const M &polymorphic_matcher_or_value)
template<typename U >
static Matcher< T > Cast (const Matcher< U > &matcher)
template<typename M >
static Matcher< T > Cast (const M &polymorphic_matcher_or_value)
template<typename U >
static Matcher< T > Cast (const Matcher< U > &matcher)
template<typename M >
static Matcher< T > Cast (const M &polymorphic_matcher_or_value)
template<typename U >
static Matcher< T > Cast (const Matcher< U > &matcher)
Detailed Description
template<typename T>
class testing::SafeMatcherCastImpl< T >
Definition at line 622 of file gmock-matchers.h.
Member Function Documentation
template<typename T > template<typename M > static Matcher<T> testing::SafeMatcherCastImpl< T >::Cast (const M & polymorphic_matcher_or_value) inline static
Definition at line 627 of file gmock-matchers.h.
References testing::internal::MatcherCastImpl< T, M >::Cast().
Referenced by testing::SafeMatcherCastImpl< T >::Cast(), and testing::SafeMatcherCast().
{
     return internal::MatcherCastImpl<T, M>::Cast(polymorphic_matcher_or_value);
   }
template<typename T > template<typename M > static Matcher<T> testing::SafeMatcherCastImpl< T >::Cast (const M & polymorphic_matcher_or_value) inline static
Definition at line 627 of file gmock-matchers.h.
References testing::internal::MatcherCastImpl< T, M >::Cast().
{
     return internal::MatcherCastImpl<T, M>::Cast(polymorphic_matcher_or_value);
   }
template<typename T > template<typename M > static Matcher<T> testing::SafeMatcherCastImpl< T >::Cast (const M & polymorphic_matcher_or_value) inline static
Definition at line 627 of file gmock-matchers.h.
References testing::internal::MatcherCastImpl< T, M >::Cast().
{
     return internal::MatcherCastImpl<T, M>::Cast(polymorphic_matcher_or_value);
   }
template<typename T > template<typename U > static Matcher<T> testing::SafeMatcherCastImpl< T >::Cast (const Matcher< U > & matcher) inline static
Definition at line 641 of file gmock-matchers.h.
References testing::A(), testing::SafeMatcherCastImpl< T >::Cast(), GMOCK_KIND_OF_, GTEST_COMPILE_ASSERT_, GTEST_REMOVE_REFERENCE_AND_CONST_, testing::internal::IsReadableTypeName(), testing::internal::kOther, M, testing::internal::MatcherBase< T >::MatchAndExplain(), testing::internal::MatcherBase< T >::Matches(), testing::internal::MatchPrintAndExplain(), testing::internal::PrintIfNotEmpty(), testing::SafeMatcherCast(), testing::StringMatchResultListener::str(), T, testing::internal::UniversalPrint(), value, and testing::Value().
{
     // Enforce that T can be implicitly converted to U.
     GTEST_COMPILE_ASSERT_((internal::ImplicitlyConvertible<T, U>::value),
                           T_must_be_implicitly_convertible_to_U);
     // Enforce that we are not converting a non-reference type T to a reference
     // type U.
     GTEST_COMPILE_ASSERT_(
         internal::is_reference<T>::value || !internal::is_reference<U>::value,
         cannot_convert_non_referentce_arg_to_reference);
     // In case both T and U are arithmetic types, enforce that the
     // conversion is not lossy.
     typedef GTEST_REMOVE_REFERENCE_AND_CONST_(T) RawT;
     typedef GTEST_REMOVE_REFERENCE_AND_CONST_(U) RawU;
     const bool kTIsOther = GMOCK_KIND_OF_(RawT) == internal::kOther;
     const bool kUIsOther = GMOCK_KIND_OF_(RawU) == internal::kOther;
     GTEST_COMPILE_ASSERT_(
         kTIsOther || kUIsOther ||
         (internal::LosslessArithmeticConvertible<RawT, RawU>::value),
         conversion_of_arithmetic_types_must_be_lossless);
     return MatcherCast<T>(matcher);
   }
template<typename T > template<typename U > static Matcher<T> testing::SafeMatcherCastImpl< T >::Cast (const Matcher< U > & matcher) inline static
Definition at line 641 of file gmock-matchers.h.
References GMOCK_KIND_OF_, GTEST_COMPILE_ASSERT_, GTEST_REMOVE_REFERENCE_AND_CONST_, testing::internal::kOther, T, and value.
{
     // Enforce that T can be implicitly converted to U.
     GTEST_COMPILE_ASSERT_((internal::ImplicitlyConvertible<T, U>::value),
                           T_must_be_implicitly_convertible_to_U);
     // Enforce that we are not converting a non-reference type T to a reference
     // type U.
     GTEST_COMPILE_ASSERT_(
         internal::is_reference<T>::value || !internal::is_reference<U>::value,
         cannot_convert_non_referentce_arg_to_reference);
     // In case both T and U are arithmetic types, enforce that the
     // conversion is not lossy.
     typedef GTEST_REMOVE_REFERENCE_AND_CONST_(T) RawT;
     typedef GTEST_REMOVE_REFERENCE_AND_CONST_(U) RawU;
     const bool kTIsOther = GMOCK_KIND_OF_(RawT) == internal::kOther;
     const bool kUIsOther = GMOCK_KIND_OF_(RawU) == internal::kOther;
     GTEST_COMPILE_ASSERT_(
         kTIsOther || kUIsOther ||
         (internal::LosslessArithmeticConvertible<RawT, RawU>::value),
         conversion_of_arithmetic_types_must_be_lossless);
     return MatcherCast<T>(matcher);
   }
template<typename T > template<typename U > static Matcher<T> testing::SafeMatcherCastImpl< T >::Cast (const Matcher< U > & matcher) inline static
Definition at line 641 of file gmock-matchers.h.
References testing::A(), testing::SafeMatcherCastImpl< T >::Cast(), GMOCK_KIND_OF_, GTEST_COMPILE_ASSERT_, GTEST_REMOVE_REFERENCE_AND_CONST_, testing::internal::IsReadableTypeName(), testing::internal::kOther, M, testing::internal::MatcherBase< T >::MatchAndExplain(), testing::internal::MatcherBase< T >::Matches(), testing::internal::MatchPrintAndExplain(), testing::internal::PrintIfNotEmpty(), testing::SafeMatcherCast(), testing::StringMatchResultListener::str(), T, testing::internal::UniversalPrint(), value, and testing::Value().
{
     // Enforce that T can be implicitly converted to U.
     GTEST_COMPILE_ASSERT_((internal::ImplicitlyConvertible<T, U>::value),
                           T_must_be_implicitly_convertible_to_U);
     // Enforce that we are not converting a non-reference type T to a reference
     // type U.
     GTEST_COMPILE_ASSERT_(
         internal::is_reference<T>::value || !internal::is_reference<U>::value,
         cannot_convert_non_referentce_arg_to_reference);
     // In case both T and U are arithmetic types, enforce that the
     // conversion is not lossy.
     typedef GTEST_REMOVE_REFERENCE_AND_CONST_(T) RawT;
     typedef GTEST_REMOVE_REFERENCE_AND_CONST_(U) RawU;
     const bool kTIsOther = GMOCK_KIND_OF_(RawT) == internal::kOther;
     const bool kUIsOther = GMOCK_KIND_OF_(RawU) == internal::kOther;
     GTEST_COMPILE_ASSERT_(
         kTIsOther || kUIsOther ||
         (internal::LosslessArithmeticConvertible<RawT, RawU>::value),
         conversion_of_arithmetic_types_must_be_lossless);
     return MatcherCast<T>(matcher);
   }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h