proxygen: folly::SocketAddressTestHelper Class Reference
folly::SocketAddressTestHelper Class Reference
#include <SocketAddressTestHelper.h>
Static Public Member Functions
static bool isIPv4Enabled ()
static bool isIPv6Enabled ()
Static Public Attributes
static constexpr const char * kLoopbackAddrIPv4 = "127.0.0.1"
static constexpr const char * kLoopbackAddrIPv6 = "::1"
static constexpr const char * kGooglePublicDnsAName
static constexpr const char * kGooglePublicDnsBName
static constexpr const char * kGooglePublicDnsAAddrIPv4 = "8.8.8.8"
static constexpr const char * kGooglePublicDnsBAddrIPv4 = "8.8.4.4"
static constexpr const char * kGooglePublicDnsAAddrIPv6
static constexpr const char * kGooglePublicDnsBAddrIPv6
Static Private Member Functions
static bool isFamilyOfAddrEnabled (const char *addr)
Detailed Description
Definition at line 21 of file SocketAddressTestHelper.h.
Member Function Documentation
bool folly::SocketAddressTestHelper::isFamilyOfAddrEnabled (const char * addr) static private
Definition at line 41 of file SocketAddressTestHelper.cpp.
Referenced by isIPv4Enabled(), and isIPv6Enabled().
{
   struct addrinfo hints {};
   hints.ai_flags = AI_ADDRCONFIG;
   struct addrinfo* resultsp = nullptr;
   int err = getaddrinfo(addr, nullptr, &hints, &resultsp);
   freeaddrinfo(resultsp);
   return !err;
 }
bool folly::SocketAddressTestHelper::isIPv4Enabled () static
Definition at line 33 of file SocketAddressTestHelper.cpp.
References isFamilyOfAddrEnabled(), and kLoopbackAddrIPv4.
Referenced by TEST().
{
   return isFamilyOfAddrEnabled(kLoopbackAddrIPv4);
 }
bool folly::SocketAddressTestHelper::isIPv6Enabled () static
Definition at line 37 of file SocketAddressTestHelper.cpp.
References isFamilyOfAddrEnabled(), and kLoopbackAddrIPv6.
Referenced by TEST().
{
   return isFamilyOfAddrEnabled(kLoopbackAddrIPv6);
 }
Member Data Documentation
constexpr const char * folly::SocketAddressTestHelper::kGooglePublicDnsAAddrIPv4 = "8.8.8.8" static
Definition at line 31 of file SocketAddressTestHelper.h.
Referenced by TEST().
constexpr const char * folly::SocketAddressTestHelper::kGooglePublicDnsAAddrIPv6 static
Initial value:
=
      "2001:4860:4860::8888"
Definition at line 33 of file SocketAddressTestHelper.h.
Referenced by TEST().
constexpr const char * folly::SocketAddressTestHelper::kGooglePublicDnsAName static
Initial value:
=
      "google-public-dns-a.google.com"
Definition at line 27 of file SocketAddressTestHelper.h.
constexpr const char * folly::SocketAddressTestHelper::kGooglePublicDnsBAddrIPv4 = "8.8.4.4" static
Definition at line 32 of file SocketAddressTestHelper.h.
constexpr const char * folly::SocketAddressTestHelper::kGooglePublicDnsBAddrIPv6 static
Initial value:
=
      "2001:4860:4860::8844"
Definition at line 35 of file SocketAddressTestHelper.h.
constexpr const char * folly::SocketAddressTestHelper::kGooglePublicDnsBName static
Initial value:
=
      "google-public-dns-b.google.com"
Definition at line 29 of file SocketAddressTestHelper.h.
constexpr const char * folly::SocketAddressTestHelper::kLoopbackAddrIPv4 = "127.0.0.1" static
Definition at line 23 of file SocketAddressTestHelper.h.
Referenced by isIPv4Enabled().
constexpr const char * folly::SocketAddressTestHelper::kLoopbackAddrIPv6 = "::1" static
Definition at line 24 of file SocketAddressTestHelper.h.
Referenced by isIPv6Enabled().
The documentation for this class was generated from the following files:
proxygen/folly/folly/test/SocketAddressTestHelper.h
proxygen/folly/folly/test/SocketAddressTestHelper.cpp