proxygen: wangle::PipelineContext Class Reference
wangle::PipelineContext Class Reference abstract
#include <HandlerContext-inl.h>
Public Member Functions
virtual ~PipelineContext ()=default
virtual void attachPipeline ()=0
virtual void detachPipeline ()=0
template<class H , class HandlerContext >
void attachContext (H *handler, HandlerContext *ctx)
template<class H , class HandlerContext >
void detachContext (H *handler, HandlerContext *)
virtual void setNextIn (PipelineContext *ctx)=0
virtual void setNextOut (PipelineContext *ctx)=0
virtual HandlerDir getDirection ()=0
Detailed Description
Definition at line 23 of file HandlerContext-inl.h.
Constructor & Destructor Documentation
virtual wangle::PipelineContext::~PipelineContext () virtual default
Member Function Documentation
template<class H , class HandlerContext > void wangle::PipelineContext::attachContext (H * handler, HandlerContext * ctx) inline
Definition at line 31 of file HandlerContext-inl.h.
Referenced by wangle::ContextImplBase< H, InboundHandlerContext< H::rout > >::attachPipeline().
{
     if (++handler->attachCount_ == 1) {
       handler->ctx_ = ctx;
     } else {
       handler->ctx_ = nullptr;
     }
   }
virtual void wangle::PipelineContext::attachPipeline () pure virtual
Implemented in wangle::ContextImplBase< H, Context >, wangle::ContextImplBase< H, HandlerContext< H::rout, H::wout > >, wangle::ContextImplBase< H, OutboundHandlerContext< H::wout > >, and wangle::ContextImplBase< H, InboundHandlerContext< H::rout > >.
template<class H , class HandlerContext > void wangle::PipelineContext::detachContext (H * handler, HandlerContext *) inline
Definition at line 40 of file HandlerContext-inl.h.
References getDirection(), setNextIn(), and setNextOut().
Referenced by wangle::ContextImplBase< H, InboundHandlerContext< H::rout > >::detachPipeline().
{
     if (handler->attachCount_ >= 1) {
       --handler->attachCount_;
     }
     handler->ctx_ = nullptr;
   }
virtual void wangle::PipelineContext::detachPipeline () pure virtual
Implemented in wangle::ContextImplBase< H, Context >, wangle::ContextImplBase< H, HandlerContext< H::rout, H::wout > >, wangle::ContextImplBase< H, OutboundHandlerContext< H::wout > >, and wangle::ContextImplBase< H, InboundHandlerContext< H::rout > >.
virtual HandlerDir wangle::PipelineContext::getDirection () pure virtual
Implemented in wangle::ContextImplBase< H, Context >, wangle::ContextImplBase< H, HandlerContext< H::rout, H::wout > >, wangle::ContextImplBase< H, OutboundHandlerContext< H::wout > >, and wangle::ContextImplBase< H, InboundHandlerContext< H::rout > >.
Referenced by detachContext().
virtual void wangle::PipelineContext::setNextIn (PipelineContext * ctx) pure virtual
Implemented in wangle::ContextImplBase< H, Context >, wangle::ContextImplBase< H, HandlerContext< H::rout, H::wout > >, wangle::ContextImplBase< H, OutboundHandlerContext< H::wout > >, and wangle::ContextImplBase< H, InboundHandlerContext< H::rout > >.
Referenced by detachContext().
virtual void wangle::PipelineContext::setNextOut (PipelineContext * ctx) pure virtual
Implemented in wangle::ContextImplBase< H, Context >, wangle::ContextImplBase< H, HandlerContext< H::rout, H::wout > >, wangle::ContextImplBase< H, OutboundHandlerContext< H::wout > >, and wangle::ContextImplBase< H, InboundHandlerContext< H::rout > >.
Referenced by detachContext().
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/channel/HandlerContext-inl.h