proxygen: gtest_env_var_test.GTestEnvVarTest Class Reference
gtest_env_var_test.GTestEnvVarTest Class Reference
Public Member Functions
def testEnvVarAffectsFlag (self)
def testXmlOutputFile (self)
def testXmlOutputFileOverride (self)
def testEnvVarAffectsFlag (self)
def testXmlOutputFile (self)
def testXmlOutputFileOverride (self)
def testEnvVarAffectsFlag (self)
def testXmlOutputFile (self)
def testXmlOutputFileOverride (self)
Detailed Description
Definition at line 83 of file gtest_env_var_test.py.
Member Function Documentation
def gtest_env_var_test.GTestEnvVarTest.testEnvVarAffectsFlag (self)
Tests that environment variable should affect the corresponding flag.
Definition at line 84 of file gtest_env_var_test.py.
References gtest_env_var_test.SetEnvVar(), and gtest_env_var_test.TestFlag().
Referenced by gtest_env_var_test.GTestEnvVarTest.testEnvVarAffectsFlag().
   def testEnvVarAffectsFlag(self):
     """Tests that environment variable should affect the corresponding flag."""
     TestFlag('break_on_failure', '1', '0')
     TestFlag('color', 'yes', 'auto')
     TestFlag('filter', 'FooTest.Bar', '*')
     SetEnvVar('XML_OUTPUT_FILE', None) # For 'output' test
     TestFlag('output', 'xml:tmp/foo.xml', '')
     TestFlag('print_time', '0', '1')
     TestFlag('repeat', '999', '1')
     TestFlag('throw_on_failure', '1', '0')
     TestFlag('death_test_style', 'threadsafe', 'fast')
     TestFlag('catch_exceptions', '0', '1')
     if IS_LINUX:
       TestFlag('death_test_use_fork', '1', '0')
       TestFlag('stack_trace_depth', '0', '100')
def gtest_env_var_test.GTestEnvVarTest.testEnvVarAffectsFlag (self)
Tests that environment variable should affect the corresponding flag.
Definition at line 84 of file gtest_env_var_test.py.
References gtest_env_var_test.SetEnvVar(), gtest_env_var_test.GTestEnvVarTest.testEnvVarAffectsFlag(), and gtest_env_var_test.TestFlag().
   def testEnvVarAffectsFlag(self):
     """Tests that environment variable should affect the corresponding flag."""
     TestFlag('break_on_failure', '1', '0')
     TestFlag('color', 'yes', 'auto')
     TestFlag('filter', 'FooTest.Bar', '*')
     SetEnvVar('XML_OUTPUT_FILE', None) # For 'output' test
     TestFlag('output', 'xml:tmp/foo.xml', '')
     TestFlag('print_time', '0', '1')
     TestFlag('repeat', '999', '1')
     TestFlag('throw_on_failure', '1', '0')
     TestFlag('death_test_style', 'threadsafe', 'fast')
     TestFlag('catch_exceptions', '0', '1')
     if IS_LINUX:
       TestFlag('death_test_use_fork', '1', '0')
       TestFlag('stack_trace_depth', '0', '100')
def gtest_env_var_test.GTestEnvVarTest.testEnvVarAffectsFlag (self)
Tests that environment variable should affect the corresponding flag.
Definition at line 84 of file gtest_env_var_test.py.
References gtest_env_var_test.SetEnvVar(), gtest_env_var_test.GTestEnvVarTest.testEnvVarAffectsFlag(), and gtest_env_var_test.TestFlag().
   def testEnvVarAffectsFlag(self):
     """Tests that environment variable should affect the corresponding flag."""
     TestFlag('break_on_failure', '1', '0')
     TestFlag('color', 'yes', 'auto')
     TestFlag('filter', 'FooTest.Bar', '*')
     SetEnvVar('XML_OUTPUT_FILE', None) # For 'output' test
     TestFlag('output', 'xml:tmp/foo.xml', '')
     TestFlag('print_time', '0', '1')
     TestFlag('repeat', '999', '1')
     TestFlag('throw_on_failure', '1', '0')
     TestFlag('death_test_style', 'threadsafe', 'fast')
     TestFlag('catch_exceptions', '0', '1')
     if IS_LINUX:
       TestFlag('death_test_use_fork', '1', '0')
       TestFlag('stack_trace_depth', '0', '100')
def gtest_env_var_test.GTestEnvVarTest.testXmlOutputFile (self)
Tests that $XML_OUTPUT_FILE affects the output flag.
Definition at line 102 of file gtest_env_var_test.py.
References gtest_env_var_test.AssertEq(), gtest_env_var_test.GetFlag(), and gtest_env_var_test.SetEnvVar().
Referenced by gtest_env_var_test.GTestEnvVarTest.testXmlOutputFile().
   def testXmlOutputFile(self):
     """Tests that $XML_OUTPUT_FILE affects the output flag."""
     SetEnvVar('GTEST_OUTPUT', None)
     SetEnvVar('XML_OUTPUT_FILE', 'tmp/bar.xml')
     AssertEq('xml:tmp/bar.xml', GetFlag('output'))
def gtest_env_var_test.GTestEnvVarTest.testXmlOutputFile (self)
Tests that $XML_OUTPUT_FILE affects the output flag.
Definition at line 102 of file gtest_env_var_test.py.
References gtest_env_var_test.AssertEq(), gtest_env_var_test.GetFlag(), gtest_env_var_test.SetEnvVar(), and gtest_env_var_test.GTestEnvVarTest.testXmlOutputFile().
   def testXmlOutputFile(self):
     """Tests that $XML_OUTPUT_FILE affects the output flag."""
     SetEnvVar('GTEST_OUTPUT', None)
     SetEnvVar('XML_OUTPUT_FILE', 'tmp/bar.xml')
     AssertEq('xml:tmp/bar.xml', GetFlag('output'))
def gtest_env_var_test.GTestEnvVarTest.testXmlOutputFile (self)
Tests that $XML_OUTPUT_FILE affects the output flag.
Definition at line 102 of file gtest_env_var_test.py.
References gtest_env_var_test.AssertEq(), gtest_env_var_test.GetFlag(), gtest_env_var_test.SetEnvVar(), and gtest_env_var_test.GTestEnvVarTest.testXmlOutputFile().
   def testXmlOutputFile(self):
     """Tests that $XML_OUTPUT_FILE affects the output flag."""
     SetEnvVar('GTEST_OUTPUT', None)
     SetEnvVar('XML_OUTPUT_FILE', 'tmp/bar.xml')
     AssertEq('xml:tmp/bar.xml', GetFlag('output'))
def gtest_env_var_test.GTestEnvVarTest.testXmlOutputFileOverride (self)
Tests that $XML_OUTPUT_FILE is overridden by $GTEST_OUTPUT
Definition at line 109 of file gtest_env_var_test.py.
References gtest_env_var_test.AssertEq(), gtest_env_var_test.GetFlag(), gtest_test_utils.Main(), and gtest_env_var_test.SetEnvVar().
Referenced by gtest_env_var_test.GTestEnvVarTest.testXmlOutputFileOverride().
   def testXmlOutputFileOverride(self):
     """Tests that $XML_OUTPUT_FILE is overridden by $GTEST_OUTPUT"""
     SetEnvVar('GTEST_OUTPUT', 'xml:tmp/foo.xml')
     SetEnvVar('XML_OUTPUT_FILE', 'tmp/bar.xml')
     AssertEq('xml:tmp/foo.xml', GetFlag('output'))
def gtest_env_var_test.GTestEnvVarTest.testXmlOutputFileOverride (self)
Tests that $XML_OUTPUT_FILE is overridden by $GTEST_OUTPUT
Definition at line 109 of file gtest_env_var_test.py.
References gtest_env_var_test.AssertEq(), gtest_env_var_test.GetFlag(), gtest_test_utils.Main(), gtest_env_var_test.SetEnvVar(), and gtest_env_var_test.GTestEnvVarTest.testXmlOutputFileOverride().
   def testXmlOutputFileOverride(self):
     """Tests that $XML_OUTPUT_FILE is overridden by $GTEST_OUTPUT"""
     SetEnvVar('GTEST_OUTPUT', 'xml:tmp/foo.xml')
     SetEnvVar('XML_OUTPUT_FILE', 'tmp/bar.xml')
     AssertEq('xml:tmp/foo.xml', GetFlag('output'))
def gtest_env_var_test.GTestEnvVarTest.testXmlOutputFileOverride (self)
Tests that $XML_OUTPUT_FILE is overridden by $GTEST_OUTPUT
Definition at line 109 of file gtest_env_var_test.py.
References gtest_env_var_test.AssertEq(), gtest_env_var_test.GetFlag(), gtest_test_utils.Main(), gtest_env_var_test.SetEnvVar(), and gtest_env_var_test.GTestEnvVarTest.testXmlOutputFileOverride().
   def testXmlOutputFileOverride(self):
     """Tests that $XML_OUTPUT_FILE is overridden by $GTEST_OUTPUT"""
     SetEnvVar('GTEST_OUTPUT', 'xml:tmp/foo.xml')
     SetEnvVar('XML_OUTPUT_FILE', 'tmp/bar.xml')
     AssertEq('xml:tmp/foo.xml', GetFlag('output'))
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest_env_var_test.py