proxygen: folly::test::IovecBuffers Class Reference
folly::test::IovecBuffers Class Reference
Public Member Functions
IovecBuffers (std::initializer_list< size_t > sizes)
IovecBuffers (std::vector< size_t > sizes)
std::vector< iovec > iov () const
std::string join () const
size_t size () const
Private Attributes
std::vector< std::string > buffers_
std::vector< iovec > iov_
Detailed Description
Definition at line 183 of file FileUtilTest.cpp.
Constructor & Destructor Documentation
folly::test::IovecBuffers::IovecBuffers (std::initializer_list< size_t > sizes) explicit
Definition at line 201 of file FileUtilTest.cpp.
References b, s, and string.
{
   iov_.reserve(sizes.size());
   for (auto& s : sizes) {
     buffers_.push_back(std::string(s, '\0'));
   }
   for (auto& b : buffers_) {
     iovec iov;
     iov.iov_base = &b[0];
     iov.iov_len = b.size();
     iov_.push_back(iov);
   }
 }
folly::test::IovecBuffers::IovecBuffers (std::vector< size_t > sizes) explicit
Definition at line 214 of file FileUtilTest.cpp.
References b, s, and string.
{
   iov_.reserve(sizes.size());
   for (auto s : sizes) {
     buffers_.push_back(std::string(s, '\0'));
   }
   for (auto& b : buffers_) {
     iovec iov;
     iov.iov_base = &b[0];
     iov.iov_len = b.size();
     iov_.push_back(iov);
   }
 }
Member Function Documentation
std::vector<iovec> folly::test::IovecBuffers::iov () const inline
Definition at line 188 of file FileUtilTest.cpp.
Referenced by folly::test::TEST().
{
     return iov_;
   } // yes, make a copy
std::string folly::test::IovecBuffers::join () const inline
Definition at line 191 of file FileUtilTest.cpp.
References folly::join(), and folly::size().
{
     return folly::join("", buffers_);
   }
size_t folly::test::IovecBuffers::size () const
Definition at line 227 of file FileUtilTest.cpp.
References b, and s.
Referenced by folly::test::TEST().
{
   size_t s = 0;
   for (auto& b : buffers_) {
     s += b.size();
   }
   return s;
 }
Member Data Documentation
std::vector<std::string> folly::test::IovecBuffers::buffers_ private
Definition at line 197 of file FileUtilTest.cpp.
std::vector<iovec> folly::test::IovecBuffers::iov_ private
Definition at line 198 of file FileUtilTest.cpp.
The documentation for this class was generated from the following file:
proxygen/folly/folly/test/FileUtilTest.cpp