proxygen: MyString Class Reference
MyString Class Reference
#include <sample2.h>
Public Member Functions
MyString ()
MyString (const char *a_c_string)
MyString (const MyString &string)
~MyString ()
const char * c_string () const
size_t Length () const
void Set (const char *c_string)
MyString ()
MyString (const char *a_c_string)
MyString (const MyString &string)
~MyString ()
const char * c_string () const
size_t Length () const
void Set (const char *c_string)
MyString ()
MyString (const char *a_c_string)
MyString (const MyString &string)
~MyString ()
const char * c_string () const
size_t Length () const
void Set (const char *c_string)
Static Public Member Functions
static const char * CloneCString (const char *a_c_string)
static const char * CloneCString (const char *a_c_string)
static const char * CloneCString (const char *a_c_string)
Private Member Functions
const MyString & operator= (const MyString &rhs)
const MyString & operator= (const MyString &rhs)
const MyString & operator= (const MyString &rhs)
Private Attributes
const char * c_string_
Detailed Description
Definition at line 41 of file sample2.h.
Constructor & Destructor Documentation
MyString::MyString () inline
Definition at line 55 of file sample2.h.
 : c_string_(NULL) {}
MyString::MyString (const char * a_c_string) inline explicit
Definition at line 58 of file sample2.h.
References Set().
                                             : c_string_(NULL) {
     Set(a_c_string);
   }
MyString::MyString (const MyString & string) inline
Definition at line 63 of file sample2.h.
References Set().
                                    : c_string_(NULL) {
     Set(string.c_string_);
   }
MyString::~MyString () inline
Definition at line 71 of file sample2.h.
References c_string_.
 { delete[] c_string_; }
MyString::MyString () inline
Definition at line 55 of file sample2.h.
 : c_string_(NULL) {}
MyString::MyString (const char * a_c_string) inline explicit
Definition at line 58 of file sample2.h.
References Set().
                                             : c_string_(NULL) {
     Set(a_c_string);
   }
MyString::MyString (const MyString & string) inline
Definition at line 63 of file sample2.h.
References Set().
                                    : c_string_(NULL) {
     Set(string.c_string_);
   }
MyString::~MyString () inline
Definition at line 71 of file sample2.h.
References c_string_.
 { delete[] c_string_; }
MyString::MyString () inline
Definition at line 55 of file sample2.h.
 : c_string_(NULL) {}
MyString::MyString (const char * a_c_string) inline explicit
Definition at line 58 of file sample2.h.
References Set().
                                             : c_string_(NULL) {
     Set(a_c_string);
   }
MyString::MyString (const MyString & string) inline
Definition at line 63 of file sample2.h.
References Set().
                                    : c_string_(NULL) {
     Set(string.c_string_);
   }
MyString::~MyString () inline
Definition at line 71 of file sample2.h.
References c_string_.
 { delete[] c_string_; }
Member Function Documentation
const char* MyString::c_string () const inline
Definition at line 74 of file sample2.h.
References c_string_.
Referenced by Length(), and TEST().
 { return c_string_; }
const char* MyString::c_string () const inline
Definition at line 74 of file sample2.h.
References c_string_.
 { return c_string_; }
const char* MyString::c_string () const inline
Definition at line 74 of file sample2.h.
References c_string_.
 { return c_string_; }
const char * MyString::CloneCString (const char * a_c_string) static
Definition at line 39 of file sample2.cc.
Referenced by Set().
{
   if (a_c_string == NULL) return NULL;
   const size_t len = strlen(a_c_string);
   char* const clone = new char[ len + 1 ];
   memcpy(clone, a_c_string, len + 1);
   return clone;
 }
static const char* MyString::CloneCString (const char * a_c_string) static
static const char* MyString::CloneCString (const char * a_c_string) static
size_t MyString::Length () const inline
Definition at line 76 of file sample2.h.
References c_string(), and Set().
Referenced by TEST().
{
     return c_string_ == NULL ? 0 : strlen(c_string_);
   }
size_t MyString::Length () const inline
Definition at line 76 of file sample2.h.
References c_string(), and Set().
{
     return c_string_ == NULL ? 0 : strlen(c_string_);
   }
size_t MyString::Length () const inline
Definition at line 76 of file sample2.h.
References c_string(), and Set().
{
     return c_string_ == NULL ? 0 : strlen(c_string_);
   }
const MyString& MyString::operator= (const MyString & rhs) private
const MyString& MyString::operator= (const MyString & rhs) private
const MyString& MyString::operator= (const MyString & rhs) private
void MyString::Set (const char * c_string)
void MyString::Set (const char * c_string)
void MyString::Set (const char * c_string)
Definition at line 51 of file sample2.cc.
References c_string_, CloneCString(), and shell_builder::temp.
Referenced by Length(), MyString(), and TEST().
{
   // Makes sure this works when c_string == c_string_
   const char* const temp = MyString::CloneCString(a_c_string);
   delete[] c_string_;
   c_string_ = temp;
 }
Member Data Documentation
const char * MyString::c_string_ private
Definition at line 43 of file sample2.h.
Referenced by c_string(), Set(), and ~MyString().
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googletest/samples/sample2.h
proxygen/fizz/build_/gtest/src/gtest/googletest/samples/sample2.cc