proxygen: folly::pushmi::receiver< Data, DVF, DEF, DDF > Class Template Reference
folly::pushmi::receiver< Data, DVF, DEF, DDF > Class Template Reference
#include <receiver.h>
Public Types
using properties = property_set_insert_t< properties_t< Data >, property_set< is_receiver<>>>
Public Member Functions
constexpr receiver (Data d)
constexpr receiver (Data d, DDF df)
constexpr receiver (Data d, DEF ef, DDF df=DDF{})
constexpr receiver (Data d, DVF vf, DEF ef=DEF{}, DDF df=DDF{})
Data & data ()
requires Invocable< DVF &, Data &, VN... > void value (VN &&...vn)
requires Invocable< DEF &, Data &, E > void error (E e) noexcept
void done ()
Private Attributes
bool done_ = false
Data data_
DVF vf_
DEF ef_
DDF df_
Detailed Description
template<PUSHMI_TYPE_CONSTRAINT(Receiver) Data, class DVF, class DEF, class DDF>
class folly::pushmi::receiver< Data, DVF, DEF, DDF >
Definition at line 235 of file receiver.h.
Member Typedef Documentation
template<PUSHMI_TYPE_CONSTRAINT(Receiver) Data, class DVF , class DEF , class DDF > using folly::pushmi::receiver< Data, DVF, DEF, DDF >::properties = property_set_insert_t<properties_t<Data>, property_set<is_receiver<>>>
Definition at line 257 of file receiver.h.
Constructor & Destructor Documentation
template<PUSHMI_TYPE_CONSTRAINT(Receiver) Data, class DVF , class DEF , class DDF > constexpr folly::pushmi::receiver< Data, DVF, DEF, DDF >::receiver (Data d) inline explicit
Definition at line 259 of file receiver.h.
       : receiver(std::move(d), DVF{}, DEF{}, DDF{}) {}
template<PUSHMI_TYPE_CONSTRAINT(Receiver) Data, class DVF , class DEF , class DDF > constexpr folly::pushmi::receiver< Data, DVF, DEF, DDF >::receiver (Data d, DDF df) inline
Definition at line 261 of file receiver.h.
       : done_(false), data_(std::move(d)), vf_(), ef_(), df_(df) {}
template<PUSHMI_TYPE_CONSTRAINT(Receiver) Data, class DVF , class DEF , class DDF > constexpr folly::pushmi::receiver< Data, DVF, DEF, DDF >::receiver (Data d, DEF ef, DDF df = DDF{}) inline
Definition at line 263 of file receiver.h.
References folly::pushmi::any_receiver< E, VN >::data_, folly::pushmi::any_receiver< E, VN >::done_, and folly::gen::move.
                                                  {})
       : done_(false), data_(std::move(d)), vf_(), ef_(ef), df_(df) {}
template<PUSHMI_TYPE_CONSTRAINT(Receiver) Data, class DVF , class DEF , class DDF > constexpr folly::pushmi::receiver< Data, DVF, DEF, DDF >::receiver (Data d, DVF vf, DEF ef = DEF{}, DDF df = DDF{}) inline
Definition at line 265 of file receiver.h.
References folly::pushmi::any_receiver< E, VN >::data_, folly::pushmi::any_receiver< E, VN >::done_, and folly::gen::move.
                                                  {}, DDF df = DDF{})
       : done_(false), data_(std::move(d)), vf_(vf), ef_(ef), df_(df) {}
Member Function Documentation
template<PUSHMI_TYPE_CONSTRAINT(Receiver) Data, class DVF , class DEF , class DDF > Data& folly::pushmi::receiver< Data, DVF, DEF, DDF >::data () inline
Definition at line 268 of file receiver.h.
References folly::pushmi::any_receiver< E, VN >::data_, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
                {
     return data_;
   }
template<PUSHMI_TYPE_CONSTRAINT(Receiver) Data, class DVF , class DEF , class DDF > void folly::pushmi::receiver< Data, DVF, DEF, DDF >::done () inline
Definition at line 290 of file receiver.h.
               {
     if (!done_) {
       done_ = true;
       df_(data_);
     }
   }
template<PUSHMI_TYPE_CONSTRAINT(Receiver) Data, class DVF , class DEF , class DDF > requires Invocable<DEF&, Data&, E> void folly::pushmi::receiver< Data, DVF, DEF, DDF >::error (E e) inline noexcept
Definition at line 282 of file receiver.h.
References folly::gen::move.
{
     static_assert(
         NothrowInvocable<DEF&, Data&, E>, "error function must be noexcept");
     if (!done_) {
       done_ = true;
       ef_(data_, std::move(e));
     }
   }
template<PUSHMI_TYPE_CONSTRAINT(Receiver) Data, class DVF , class DEF , class DDF > requires Invocable<DVF&, Data&, VN...> void folly::pushmi::receiver< Data, DVF, DEF, DDF >::value (VN &&... vn) inline
Definition at line 274 of file receiver.h.
References folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     if (!done_) {
       // done_ = true;
       vf_(data_, (VN &&) vn...);
     }
   }
Member Data Documentation
template<PUSHMI_TYPE_CONSTRAINT(Receiver) Data, class DVF , class DEF , class DDF > Data folly::pushmi::receiver< Data, DVF, DEF, DDF >::data_ private
Definition at line 237 of file receiver.h.
template<PUSHMI_TYPE_CONSTRAINT(Receiver) Data, class DVF , class DEF , class DDF > DDF folly::pushmi::receiver< Data, DVF, DEF, DDF >::df_ private
Definition at line 240 of file receiver.h.
template<PUSHMI_TYPE_CONSTRAINT(Receiver) Data, class DVF , class DEF , class DDF > bool folly::pushmi::receiver< Data, DVF, DEF, DDF >::done_ = false private
Definition at line 236 of file receiver.h.
template<PUSHMI_TYPE_CONSTRAINT(Receiver) Data, class DVF , class DEF , class DDF > DEF folly::pushmi::receiver< Data, DVF, DEF, DDF >::ef_ private
Definition at line 239 of file receiver.h.
template<PUSHMI_TYPE_CONSTRAINT(Receiver) Data, class DVF , class DEF , class DDF > DVF folly::pushmi::receiver< Data, DVF, DEF, DDF >::vf_ private
Definition at line 238 of file receiver.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/pushmi/receiver.h