proxygen: wangle::AcceptorHandshakeHelper::Callback Class Reference
wangle::AcceptorHandshakeHelper::Callback Class Reference abstract
#include <AcceptorHandshakeManager.h>
Public Member Functions
virtual ~Callback ()=default
virtual void connectionReady (folly::AsyncTransportWrapper::UniquePtr transport, std::string nextProtocol, SecureTransportType secureTransportType, folly::Optional< SSLErrorEnum > sslErr) noexcept=0
virtual void connectionError (folly::AsyncTransportWrapper *transport, folly::exception_wrapper ex, folly::Optional< SSLErrorEnum > sslErr) noexcept=0
Detailed Description
Definition at line 37 of file AcceptorHandshakeManager.h.
Constructor & Destructor Documentation
virtual wangle::AcceptorHandshakeHelper::Callback::~Callback () virtual default
Member Function Documentation
virtual void wangle::AcceptorHandshakeHelper::Callback::connectionError (folly::AsyncTransportWrapper * transport, folly::exception_wrapper ex, folly::Optional< SSLErrorEnum > sslErr) pure virtual noexcept
Called if an error was encountered while performing handshake.
If sslErr is set, Acceptor::updateSSLStats will be called.
Implemented in wangle::AcceptorHandshakeManager, wangle::EvbHandshakeHelper, MockHandshakeHelperCallback< UniquePtrTranslationPolicy >, MockHandshakeHelperCallback<>, and MockHandshakeHelperCallback< UseOwnedRawPtrPolicy >.
Referenced by wangle::EvbHandshakeHelper::connectionError(), wangle::EvbHandshakeHelper::dropConnection(), wangle::AcceptorHandshakeManager::dumpConnectionState(), and wangle::PeekingAcceptorHandshakeHelper::peekError().
virtual void wangle::AcceptorHandshakeHelper::Callback::connectionReady (folly::AsyncTransportWrapper::UniquePtr transport, std::string nextProtocol, SecureTransportType secureTransportType, folly::Optional< SSLErrorEnum > sslErr) pure virtual noexcept
Called after handshake has been completed successfully.
If sslErr is set, Acceptor::updateSSLStats will be called.
Implemented in wangle::AcceptorHandshakeManager, and wangle::EvbHandshakeHelper.
Referenced by wangle::EvbHandshakeHelper::connectionReady(), and wangle::AcceptorHandshakeManager::dumpConnectionState().
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/acceptor/AcceptorHandshakeManager.h