proxygen: wangle::AcceptorHandshakeHelper Class Reference
wangle::AcceptorHandshakeHelper Class Reference abstract
#include <AcceptorHandshakeManager.h>
Classes
class Callback
Public Types
using UniquePtr = std::unique_ptr< AcceptorHandshakeHelper, folly::DelayedDestruction::Destructor >
Public Member Functions
virtual void start (folly::AsyncSSLSocket::UniquePtr sock, AcceptorHandshakeHelper::Callback *callback) noexcept=0
virtual void dropConnection (SSLErrorEnum reason=SSLErrorEnum::NO_ERROR)=0
Public Member Functions inherited from folly::DelayedDestruction
virtual void destroy ()
bool getDestroyPending () const
Public Member Functions inherited from folly::DelayedDestructionBase
virtual ~DelayedDestructionBase ()=default
Additional Inherited Members
Protected Member Functions inherited from folly::DelayedDestruction
~DelayedDestruction () override=default
DelayedDestruction ()
Protected Member Functions inherited from folly::DelayedDestructionBase
DelayedDestructionBase ()
uint32_t getDestructorGuardCount () const
Detailed Description
Definition at line 32 of file AcceptorHandshakeManager.h.
Member Typedef Documentation
using wangle::AcceptorHandshakeHelper::UniquePtr = std::unique_ptr< AcceptorHandshakeHelper, folly::DelayedDestruction::Destructor>
Definition at line 35 of file AcceptorHandshakeManager.h.
Member Function Documentation
virtual void wangle::AcceptorHandshakeHelper::dropConnection (SSLErrorEnum reason = SSLErrorEnum::NO_ERROR) pure virtual
Implemented in wangle::PeekingAcceptorHandshakeHelper, wangle::FizzAcceptorHandshakeHelper, wangle::EvbHandshakeHelper, wangle::SSLAcceptorHandshakeHelper, and wangle::UnencryptedAcceptorHandshakeHelper.
Referenced by wangle::AcceptorHandshakeManager::dropConnection(), and wangle::AcceptorHandshakeManager::timeoutExpired().
virtual void wangle::AcceptorHandshakeHelper::start (folly::AsyncSSLSocket::UniquePtr sock, AcceptorHandshakeHelper::Callback * callback) pure virtual noexcept
Implemented in wangle::PeekingAcceptorHandshakeHelper, wangle::FizzAcceptorHandshakeHelper, wangle::EvbHandshakeHelper, wangle::SSLAcceptorHandshakeHelper, and wangle::UnencryptedAcceptorHandshakeHelper.
Referenced by wangle::AcceptorHandshakeManager::AcceptorHandshakeManager().
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/acceptor/AcceptorHandshakeManager.h