proxygen: UDPServer Class Reference
UDPServer Class Reference
Public Member Functions
UDPServer (EventBase *evb, folly::SocketAddress addr, int n)
void start ()
folly::SocketAddress address () const
void shutdown ()
void pauseAccepting ()
void resumeAccepting ()
UDPServer (EventBase *evb, folly::SocketAddress addr, int n)
void start ()
folly::SocketAddress address () const
void shutdown ()
void pauseAccepting ()
void resumeAccepting ()
void setChangePortForWrites (bool changePortForWrites)
Private Attributes
EventBase *const evb_ {nullptr}
const folly::SocketAddress addr_
std::unique_ptr< AsyncUDPServerSocket > socket_
std::vector< std::thread > threads_
std::vector< folly::EventBase > evbs_
std::vector< UDPAcceptor > acceptors_
bool changePortForWrites_ {true}
Detailed Description
Definition at line 115 of file AsyncUDPSocketGSOTest.cpp.
Constructor & Destructor Documentation
UDPServer::UDPServer (EventBase * evb, folly::SocketAddress addr, int n) inline
Definition at line 117 of file AsyncUDPSocketGSOTest.cpp.
       : evb_(evb), addr_(addr), evbs_(n) {}
UDPServer::UDPServer (EventBase * evb, folly::SocketAddress addr, int n) inline
Definition at line 91 of file AsyncUDPSocketTest.cpp.
       : evb_(evb), addr_(addr), evbs_(n) {}
Member Function Documentation
folly::SocketAddress UDPServer::address () const inline
Definition at line 126 of file AsyncUDPSocketTest.cpp.
References socket_.
{
     return socket_->address();
   }
folly::SocketAddress UDPServer::address () const inline
Definition at line 152 of file AsyncUDPSocketGSOTest.cpp.
References socket_.
{
     return socket_->address();
   }
void UDPServer::pauseAccepting () inline
Definition at line 144 of file AsyncUDPSocketTest.cpp.
References socket_.
{
     socket_->pauseAccepting();
   }
void UDPServer::pauseAccepting () inline
Definition at line 170 of file AsyncUDPSocketGSOTest.cpp.
References socket_.
{
     socket_->pauseAccepting();
   }
void UDPServer::resumeAccepting () inline
Definition at line 148 of file AsyncUDPSocketTest.cpp.
References socket_.
{
     socket_->resumeAccepting();
   }
void UDPServer::resumeAccepting () inline
Definition at line 174 of file AsyncUDPSocketGSOTest.cpp.
References socket_.
{
     socket_->resumeAccepting();
   }
void UDPServer::setChangePortForWrites (bool changePortForWrites) inline
Definition at line 153 of file AsyncUDPSocketTest.cpp.
References evb_, and socket_.
{
     changePortForWrites_ = changePortForWrites;
   }
void UDPServer::shutdown () inline
Definition at line 130 of file AsyncUDPSocketTest.cpp.
References evb_, folly::EventBase::isInEventBaseThread(), socket_, and folly::pushmi::detail::t.
                   {
     CHECK(evb_->isInEventBaseThread());
     socket_->close();
     socket_.reset();
     for (auto& evb : evbs_) {
       evb.terminateLoopSoon();
     }
     for (auto& t : threads_) {
       t.join();
     }
   }
void UDPServer::shutdown () inline
Definition at line 156 of file AsyncUDPSocketGSOTest.cpp.
References evb_, folly::EventBase::isInEventBaseThread(), socket_, and folly::pushmi::detail::t.
                   {
     CHECK(evb_->isInEventBaseThread());
     socket_->close();
     socket_.reset();
     for (auto& evb : evbs_) {
       evb.terminateLoopSoon();
     }
     for (auto& t : threads_) {
       t.join();
     }
   }
void UDPServer::start () inline
Definition at line 94 of file AsyncUDPSocketTest.cpp.
References evb_, i, folly::EventBase::isInEventBaseThread(), folly::gen::move, socket_, and folly::pushmi::detail::t.
                {
     CHECK(evb_->isInEventBaseThread());
     socket_ = std::make_unique<AsyncUDPServerSocket>(evb_, 1500);
     try {
       socket_->bind(addr_);
       VLOG(4) << "Server listening on " << socket_->address().describe();
     } catch (const std::exception& ex) {
       LOG(FATAL) << ex.what();
     }
     acceptors_.reserve(evbs_.size());
     threads_.reserve(evbs_.size());
     // Add numWorkers thread
     int i = 0;
     for (auto& evb : evbs_) {
       acceptors_.emplace_back(&evb, i, changePortForWrites_);
       std::thread t([&]() { evb.loopForever(); });
       evb.waitUntilRunning();
       socket_->addListener(&evb, &acceptors_[i]);
       threads_.emplace_back(std::move(t));
       ++i;
     }
     socket_->listen();
   }
void UDPServer::start () inline
Definition at line 120 of file AsyncUDPSocketGSOTest.cpp.
References evb_, i, folly::EventBase::isInEventBaseThread(), folly::gen::move, socket_, and folly::pushmi::detail::t.
                {
     CHECK(evb_->isInEventBaseThread());
     socket_ = std::make_unique<AsyncUDPServerSocket>(evb_, 1500);
     try {
       socket_->bind(addr_);
       VLOG(4) << "Server listening on " << socket_->address().describe();
     } catch (const std::exception& ex) {
       LOG(FATAL) << ex.what();
     }
     acceptors_.reserve(evbs_.size());
     threads_.reserve(evbs_.size());
     // Add numWorkers thread
     int i = 0;
     for (auto& evb : evbs_) {
       acceptors_.emplace_back(&evb);
       std::thread t([&]() { evb.loopForever(); });
       evb.waitUntilRunning();
       socket_->addListener(&evb, &acceptors_[i]);
       threads_.emplace_back(std::move(t));
       ++i;
     }
     socket_->listen();
   }
Member Data Documentation
std::vector< UDPAcceptor > UDPServer::acceptors_ private
Definition at line 185 of file AsyncUDPSocketGSOTest.cpp.
const folly::SocketAddress UDPServer::addr_ private
Definition at line 180 of file AsyncUDPSocketGSOTest.cpp.
bool UDPServer::changePortForWrites_ {true} private
Definition at line 165 of file AsyncUDPSocketTest.cpp.
EventBase *const UDPServer::evb_ {nullptr} private
Definition at line 179 of file AsyncUDPSocketGSOTest.cpp.
std::vector< folly::EventBase > UDPServer::evbs_ private
Definition at line 184 of file AsyncUDPSocketGSOTest.cpp.
std::unique_ptr< AsyncUDPServerSocket > UDPServer::socket_ private
Definition at line 182 of file AsyncUDPSocketGSOTest.cpp.
std::vector< std::thread > UDPServer::threads_ private
Definition at line 183 of file AsyncUDPSocketGSOTest.cpp.
The documentation for this class was generated from the following files:
proxygen/folly/folly/io/async/test/AsyncUDPSocketGSOTest.cpp
proxygen/folly/folly/io/async/test/AsyncUDPSocketTest.cpp