proxygen: testing::internal::KeyMatcherImpl< PairType > Class Template Reference
testing::internal::KeyMatcherImpl< PairType > Class Template Reference
#include <gmock-matchers.h>
Public Types
typedef RawPairType::first_type KeyType
typedef RawPairType::first_type KeyType
typedef RawPairType::first_type KeyType
Public Member Functions
typedef GTEST_REMOVE_REFERENCE_AND_CONST_ (PairType) RawPairType
template<typename InnerMatcher >
KeyMatcherImpl (InnerMatcher inner_matcher)
virtual bool MatchAndExplain (PairType key_value, MatchResultListener *listener) const
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
typedef GTEST_REMOVE_REFERENCE_AND_CONST_ (PairType) RawPairType
template<typename InnerMatcher >
KeyMatcherImpl (InnerMatcher inner_matcher)
virtual bool MatchAndExplain (PairType key_value, MatchResultListener *listener) const
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
typedef GTEST_REMOVE_REFERENCE_AND_CONST_ (PairType) RawPairType
template<typename InnerMatcher >
KeyMatcherImpl (InnerMatcher inner_matcher)
virtual bool MatchAndExplain (PairType key_value, MatchResultListener *listener) const
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
virtual ~MatcherDescriberInterface ()
virtual ~MatcherDescriberInterface ()
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (KeyMatcherImpl)
GTEST_DISALLOW_ASSIGN_ (KeyMatcherImpl)
GTEST_DISALLOW_ASSIGN_ (KeyMatcherImpl)
Private Attributes
const Matcher< const KeyType & > inner_matcher_
Detailed Description
template<typename PairType>
class testing::internal::KeyMatcherImpl< PairType >
Definition at line 2939 of file gmock-matchers.h.
Member Typedef Documentation
template<typename PairType > typedef RawPairType::first_type testing::internal::KeyMatcherImpl< PairType >::KeyType
Definition at line 2942 of file gmock-matchers.h.
template<typename PairType > typedef RawPairType::first_type testing::internal::KeyMatcherImpl< PairType >::KeyType
Definition at line 2942 of file gmock-matchers.h.
template<typename PairType > typedef RawPairType::first_type testing::internal::KeyMatcherImpl< PairType >::KeyType
Definition at line 2942 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename PairType > template<typename InnerMatcher > testing::internal::KeyMatcherImpl< PairType >::KeyMatcherImpl (InnerMatcher inner_matcher) inline explicit
Definition at line 2945 of file gmock-matchers.h.
       : inner_matcher_(
           testing::SafeMatcherCast<const KeyType&>(inner_matcher)) {
   }
template<typename PairType > template<typename InnerMatcher > testing::internal::KeyMatcherImpl< PairType >::KeyMatcherImpl (InnerMatcher inner_matcher) inline explicit
Definition at line 2945 of file gmock-matchers.h.
       : inner_matcher_(
           testing::SafeMatcherCast<const KeyType&>(inner_matcher)) {
   }
template<typename PairType > template<typename InnerMatcher > testing::internal::KeyMatcherImpl< PairType >::KeyMatcherImpl (InnerMatcher inner_matcher) inline explicit
Definition at line 2945 of file gmock-matchers.h.
       : inner_matcher_(
           testing::SafeMatcherCast<const KeyType&>(inner_matcher)) {
   }
Member Function Documentation
template<typename PairType > virtual void testing::internal::KeyMatcherImpl< PairType >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 2970 of file gmock-matchers.h.
{
     *os << "doesn't have a key that ";
     inner_matcher_.DescribeTo(os);
   }
template<typename PairType > virtual void testing::internal::KeyMatcherImpl< PairType >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 2970 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_.
{
     *os << "doesn't have a key that ";
     inner_matcher_.DescribeTo(os);
   }
template<typename PairType > virtual void testing::internal::KeyMatcherImpl< PairType >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 2970 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_.
{
     *os << "doesn't have a key that ";
     inner_matcher_.DescribeTo(os);
   }
template<typename PairType > virtual void testing::internal::KeyMatcherImpl< PairType >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 2964 of file gmock-matchers.h.
{
     *os << "has a key that ";
     inner_matcher_.DescribeTo(os);
   }
template<typename PairType > virtual void testing::internal::KeyMatcherImpl< PairType >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 2964 of file gmock-matchers.h.
{
     *os << "has a key that ";
     inner_matcher_.DescribeTo(os);
   }
template<typename PairType > virtual void testing::internal::KeyMatcherImpl< PairType >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 2964 of file gmock-matchers.h.
{
     *os << "has a key that ";
     inner_matcher_.DescribeTo(os);
   }
template<typename PairType > testing::internal::KeyMatcherImpl< PairType >::GTEST_DISALLOW_ASSIGN_ (KeyMatcherImpl< PairType >) private
template<typename PairType > testing::internal::KeyMatcherImpl< PairType >::GTEST_DISALLOW_ASSIGN_ (KeyMatcherImpl< PairType >) private
template<typename PairType > testing::internal::KeyMatcherImpl< PairType >::GTEST_DISALLOW_ASSIGN_ (KeyMatcherImpl< PairType >) private
template<typename PairType > typedef testing::internal::KeyMatcherImpl< PairType >::GTEST_REMOVE_REFERENCE_AND_CONST_ (PairType)
template<typename PairType > typedef testing::internal::KeyMatcherImpl< PairType >::GTEST_REMOVE_REFERENCE_AND_CONST_ (PairType)
template<typename PairType > typedef testing::internal::KeyMatcherImpl< PairType >::GTEST_REMOVE_REFERENCE_AND_CONST_ (PairType)
template<typename PairType > virtual bool testing::internal::KeyMatcherImpl< PairType >::MatchAndExplain (PairType key_value, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< PairType >.
Definition at line 2951 of file gmock-matchers.h.
References testing::StringMatchResultListener::str().
{
     StringMatchResultListener inner_listener;
     const bool match = inner_matcher_.MatchAndExplain(key_value.first,
                                                       &inner_listener);
     const internal::string explanation = inner_listener.str();
     if (explanation != "") {
       *listener << "whose first field is a value " << explanation;
     }
     return match;
   }
template<typename PairType > virtual bool testing::internal::KeyMatcherImpl< PairType >::MatchAndExplain (PairType key_value, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< PairType >.
Definition at line 2951 of file gmock-matchers.h.
References testing::StringMatchResultListener::str().
{
     StringMatchResultListener inner_listener;
     const bool match = inner_matcher_.MatchAndExplain(key_value.first,
                                                       &inner_listener);
     const internal::string explanation = inner_listener.str();
     if (explanation != "") {
       *listener << "whose first field is a value " << explanation;
     }
     return match;
   }
template<typename PairType > virtual bool testing::internal::KeyMatcherImpl< PairType >::MatchAndExplain (PairType key_value, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< PairType >.
Definition at line 2951 of file gmock-matchers.h.
References testing::StringMatchResultListener::str().
{
     StringMatchResultListener inner_listener;
     const bool match = inner_matcher_.MatchAndExplain(key_value.first,
                                                       &inner_listener);
     const internal::string explanation = inner_listener.str();
     if (explanation != "") {
       *listener << "whose first field is a value " << explanation;
     }
     return match;
   }
Member Data Documentation
template<typename PairType > const Matcher< const KeyType & > testing::internal::KeyMatcherImpl< PairType >::inner_matcher_ private
Definition at line 2976 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h