proxygen: folly::RequestEventBase Class Reference
folly::RequestEventBase Class Reference
#include <EventBase.h>
Public Member Functions
bool hasCallback () override
Public Member Functions inherited from folly::RequestData
virtual ~RequestData ()=default
virtual void onSet ()
virtual void onUnset ()
Static Public Member Functions
static EventBase * get ()
static void set (EventBase *eb)
Private Member Functions
RequestEventBase (EventBase *eb)
Private Attributes
EventBase * eb_
Static Private Attributes
static constexpr const char * kContextDataName {"EventBase"}
Detailed Description
Definition at line 81 of file EventBase.h.
Constructor & Destructor Documentation
folly::RequestEventBase::RequestEventBase (EventBase * eb) inline explicit private
Definition at line 103 of file EventBase.h.
 : eb_(eb) {}
Member Function Documentation
static EventBase* folly::RequestEventBase::get () inline static
Definition at line 83 of file EventBase.h.
References folly::data(), folly::RequestContext::get(), and folly::RequestContext::getContextData().
{
     auto data = dynamic_cast<RequestEventBase*>(
         RequestContext::get()->getContextData(kContextDataName));
     if (!data) {
       return nullptr;
     }
     return data->eb_;
   }
bool folly::RequestEventBase::hasCallback () inline override virtual
Implements folly::RequestData.
Definition at line 98 of file EventBase.h.
{
     return false;
   }
static void folly::RequestEventBase::set (EventBase * eb) inline static
Definition at line 92 of file EventBase.h.
References folly::RequestContext::get(), and folly::RequestContext::setContextData().
{
     RequestContext::get()->setContextData(
         kContextDataName,
         std::unique_ptr<RequestEventBase>(new RequestEventBase(eb)));
   }
Member Data Documentation
EventBase* folly::RequestEventBase::eb_ private
Definition at line 104 of file EventBase.h.
constexpr const char* folly::RequestEventBase::kContextDataName {"EventBase"} static private
Definition at line 105 of file EventBase.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/io/async/EventBase.h