proxygen: folly::pushmi::strand_queue< E, Executor > Class Template Reference
folly::pushmi::strand_queue< E, Executor > Class Template Reference
#include <strand.h>
Public Member Functions
~strand_queue ()
strand_queue (Executor ex)
void dispatch () override
auto shared_from_that ()
template<class Exec >
void value (Exec &&)
template<class AE >
void error (AE e) noexcept
void done ()
Public Member Functions inherited from folly::pushmi::strand_queue_base< E >
virtual ~strand_queue_base ()
strand_item< E > & front ()
Public Attributes
Executor ex_
Public Attributes inherited from folly::pushmi::strand_queue_base< E >
std::mutex lock_
size_t remaining_ = 0
std::queue< strand_item< E > > items_
Detailed Description
template<class E, class Executor>
class folly::pushmi::strand_queue< E, Executor >
Definition at line 84 of file strand.h.
Constructor & Destructor Documentation
template<class E , class Executor > folly::pushmi::strand_queue< E, Executor >::~strand_queue () inline
Definition at line 86 of file strand.h.
 {}
template<class E , class Executor > folly::pushmi::strand_queue< E, Executor >::strand_queue (Executor ex) inline
Definition at line 87 of file strand.h.
 : ex_(std::move(ex)) {}
Member Function Documentation
template<class E , class Executor > void folly::pushmi::strand_queue< E, Executor >::dispatch () override virtual
Implements folly::pushmi::strand_queue_base< E >.
Definition at line 169 of file strand.h.
References folly::pushmi::submit.
{
   submit(ex_, strand_queue_receiver<E, Executor>{shared_from_that()});
 }
template<class E , class Executor > void folly::pushmi::strand_queue< E, Executor >::done () inline
Definition at line 142 of file strand.h.
References folly::gen::guard(), and folly::pushmi::submit.
               {
     std::unique_lock<std::mutex> guard{this->lock_};
     // only allow one at a time
     if (this->remaining_ > 0) {
       return;
     }
     // skip when empty
     if (this->items_.empty()) {
       return;
     }
     auto that = shared_from_that();
     submit(ex_, strand_queue_receiver<E, Executor>{that});
   }
template<class E , class Executor > template<class AE > void folly::pushmi::strand_queue< E, Executor >::error (AE e) inline noexcept
Definition at line 129 of file strand.h.
References folly::pushmi::detail::as_const, folly::gen::guard(), folly::gen::move, folly::pushmi::set_error, and folly::pushmi::strand_item< E >::what.
{
     std::unique_lock<std::mutex> guard{this->lock_};
     this->remaining_ = 0;
     while (!this->items_.empty()) {
       auto what{std::move(this->front().what)};
       this->items_.pop();
       guard.unlock();
       set_error(what, detail::as_const(e));
       guard.lock();
     }
   }
template<class E , class Executor > auto folly::pushmi::strand_queue< E, Executor >::shared_from_that () inline
Definition at line 92 of file strand.h.
{
     return std::static_pointer_cast<strand_queue<E, Executor>>(
         this->shared_from_this());
   }
template<class E , class Executor > template<class Exec > void folly::pushmi::strand_queue< E, Executor >::value (Exec &&) inline
Definition at line 98 of file strand.h.
References folly::gen::guard(), folly::gen::move, folly::pushmi::set_done, and folly::pushmi::set_value.
                      {
     //
     // pull ready items from the queue in order.
     std::unique_lock<std::mutex> guard{this->lock_};
     // only allow one at a time
     if (this->remaining_ > 0) {
       return;
     }
     // skip when empty
     if (this->items_.empty()) {
       return;
     }
     // do not allow recursive queueing to block this executor
     this->remaining_ = this->items_.size();
     auto that = shared_from_that();
     auto subEx = strand_executor<E, Executor>{that};
     while (!this->items_.empty() && --this->remaining_ >= 0) {
       auto item{std::move(this->front())};
       this->items_.pop();
       guard.unlock();
       set_value(item.what, any_executor_ref<E>{subEx});
       set_done(item.what);
       guard.lock();
     }
   }
Member Data Documentation
template<class E , class Executor > Executor folly::pushmi::strand_queue< E, Executor >::ex_
Definition at line 88 of file strand.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/pushmi/strand.h