proxygen: folly::FileWriterFactory Class Reference
folly::FileWriterFactory Class Reference
#include <FileWriterFactory.h>
Public Member Functions
bool processOption (StringPiece name, StringPiece value)
std::shared_ptr< LogWriter > createWriter (File file)
Private Attributes
bool async_ {true}
Optional< size_t > maxBufferSize_
Detailed Description
A helper class for creating an AsyncFileWriter or ImmediateFileWriter based on log handler options settings.
This is used by StreamHandlerFactory and FileHandlerFactory.
Definition at line 33 of file FileWriterFactory.h.
Member Function Documentation
std::shared_ptr< LogWriter > folly::FileWriterFactory::createWriter (File file)
Definition at line 44 of file FileWriterFactory.cpp.
References async_, folly::Optional< Value >::hasValue(), maxBufferSize_, folly::gen::move, and folly::Optional< Value >::value().
Referenced by folly::StreamHandlerFactory::WriterFactory::createWriter(), and folly::FileHandlerFactory::WriterFactory::createWriter().
{
   // Determine whether we should use ImmediateFileWriter or AsyncFileWriter
   if (async_) {
     auto asyncWriter = make_shared<AsyncFileWriter>(std::move(file));
     if (maxBufferSize_.hasValue()) {
       asyncWriter->setMaxBufferSize(maxBufferSize_.value());
     }
     return asyncWriter;
   } else {
     if (maxBufferSize_.hasValue()) {
       throw std::invalid_argument(to<string>(
           "the \"max_buffer_size\" option is only valid for async file "
           "handlers"));
     }
     return make_shared<ImmediateFileWriter>(std::move(file));
   }
 }
bool folly::FileWriterFactory::processOption (StringPiece name, StringPiece value)
Definition at line 28 of file FileWriterFactory.cpp.
References async_, maxBufferSize_, folly::size(), and folly::value().
Referenced by folly::FileHandlerFactory::WriterFactory::processOption(), and folly::StreamHandlerFactory::WriterFactory::processOption().
{
   if (name == "async") {
     async_ = to<bool>(value);
     return true;
   } else if (name == "max_buffer_size") {
     auto size = to<size_t>(value);
     if (size == 0) {
       throw std::invalid_argument(to<string>("must be a positive integer"));
     }
     maxBufferSize_ = size;
     return true;
   } else {
     return false;
   }
 }
Member Data Documentation
bool folly::FileWriterFactory::async_ {true} private
Definition at line 39 of file FileWriterFactory.h.
Referenced by createWriter(), and processOption().
Optional<size_t> folly::FileWriterFactory::maxBufferSize_ private
Definition at line 40 of file FileWriterFactory.h.
Referenced by createWriter(), and processOption().
The documentation for this class was generated from the following files:
proxygen/folly/folly/logging/FileWriterFactory.h
proxygen/folly/folly/logging/FileWriterFactory.cpp