proxygen: fizz::EncryptedReadRecordLayer Class Reference
fizz::EncryptedReadRecordLayer Class Reference
#include <EncryptedRecordLayer.h>
Public Member Functions
~EncryptedReadRecordLayer () override=default
EncryptedReadRecordLayer (EncryptionLevel encryptionLevel)
folly::Optional< TLSMessage > read (folly::IOBufQueue &buf) override
virtual void setAead (folly::ByteRange, std::unique_ptr< Aead > aead)
virtual void setSkipFailedDecryption (bool enabled)
void setProtocolVersion (ProtocolVersion version)
EncryptionLevel getEncryptionLevel () const override
Public Member Functions inherited from fizz::ReadRecordLayer
virtual ~ReadRecordLayer ()=default
virtual folly::Optional< Param > readEvent (folly::IOBufQueue &socketBuf)
virtual bool hasUnparsedHandshakeData () const
Private Member Functions
folly::Optional< Buf > getDecryptedBuf (folly::IOBufQueue &buf)
Private Attributes
EncryptionLevel encryptionLevel_
std::unique_ptr< Aead > aead_
bool skipFailedDecryption_ {false}
bool useAdditionalData_ {true}
uint64_t seqNum_ {0}
Additional Inherited Members
Static Public Member Functions inherited from fizz::ReadRecordLayer
static folly::Optional< Param > decodeHandshakeMessage (folly::IOBufQueue &buf)
Detailed Description
Definition at line 20 of file EncryptedRecordLayer.h.
Constructor & Destructor Documentation
fizz::EncryptedReadRecordLayer::~EncryptedReadRecordLayer () override default
fizz::EncryptedReadRecordLayer::EncryptedReadRecordLayer (EncryptionLevel encryptionLevel) explicit
Definition at line 21 of file EncryptedRecordLayer.cpp.
     : encryptionLevel_(encryptionLevel) {}
Member Function Documentation
folly::Optional< Buf > fizz::EncryptedReadRecordLayer::getDecryptedBuf (folly::IOBufQueue & buf) private
Definition at line 25 of file EncryptedRecordLayer.cpp.
References aead_, fizz::alert, folly::IOBufQueue::chainLength(), fizz::change_cipher_spec, folly::IOBuf::coalesce(), folly::IOBuf::data(), folly::IOBufQueue::empty(), folly::IOBufQueue::front(), fizz::illegal_parameter, folly::IOBuf::length(), max, folly::gen::move, folly::none, folly::io::detail::CursorBase< Derived, BufType >::pull(), folly::range(), seqNum_, skipFailedDecryption_, fizz::toString(), folly::IOBufQueue::trimStart(), uint16_t, useAdditionalData_, and folly::IOBuf::wrapBufferAsValue().
Referenced by read(), and setProtocolVersion().
{
   while (true) {
     folly::io::Cursor cursor(buf.front());
     if (buf.empty() || !cursor.canAdvance(kEncryptedHeaderSize)) {
       return folly::none;
     }
     std::array<uint8_t, kEncryptedHeaderSize> ad;
     folly::io::Cursor adCursor(cursor);
     adCursor.pull(ad.data(), ad.size());
     folly::IOBuf adBuf{folly::IOBuf::wrapBufferAsValue(folly::range(ad))};
     auto contentType =
         static_cast<ContentType>(cursor.readBE<ContentTypeType>());
     cursor.skip(sizeof(ProtocolVersion));
     auto length = cursor.readBE<uint16_t>();
     if (length == 0) {
       throw std::runtime_error("received 0 length encrypted record");
     }
     if (length > kMaxEncryptedRecordSize) {
       throw std::runtime_error("received too long encrypted record");
     }
     if (buf.chainLength() < (cursor - buf.front()) + length) {
       return folly::none;
     }
     if (contentType == ContentType::alert && length == 2) {
       auto alert = decode<Alert>(cursor);
       throw std::runtime_error(folly::to<std::string>(
           "received plaintext alert in encrypted record: ",
           toString(alert.description)));
     }
     std::unique_ptr<folly::IOBuf> encrypted;
     cursor.clone(encrypted, length);
     buf.trimStart(cursor - buf.front());
     if (contentType == ContentType::change_cipher_spec) {
       encrypted->coalesce();
       if (encrypted->length() == 1 && *encrypted->data() == 0x01) {
         continue;
       } else {
         throw FizzException(
             "received ccs", AlertDescription::illegal_parameter);
       }
     }
     TLSMessage msg;
     if (seqNum_ == std::numeric_limits<uint64_t>::max()) {
       throw std::runtime_error("max read seq num");
     }
     if (skipFailedDecryption_) {
       auto decryptAttempt = aead_->tryDecrypt(
           std::move(encrypted), useAdditionalData_ ? &adBuf : nullptr, seqNum_);
       if (decryptAttempt) {
         seqNum_++;
         skipFailedDecryption_ = false;
         return decryptAttempt;
       } else {
         continue;
       }
     } else {
       return aead_->decrypt(
           std::move(encrypted),
           useAdditionalData_ ? &adBuf : nullptr,
           seqNum_++);
     }
   }
 }
EncryptionLevel fizz::EncryptedReadRecordLayer::getEncryptionLevel () const override virtual
Returns the current encryption level of the data that the read record layer can process.
Implements fizz::ReadRecordLayer.
Definition at line 139 of file EncryptedRecordLayer.cpp.
References encryptionLevel_.
Referenced by fizz::EncryptedWriteRecordLayer::setMinDesiredRecord(), and setProtocolVersion().
{
   return encryptionLevel_;
 }
folly::Optional< TLSMessage > fizz::EncryptedReadRecordLayer::read (folly::IOBufQueue & buf) override virtual
Reads a fragment from the record layer. Returns an empty optional if insuficient data available. Throws if data malformed. On success, advances buf the amount read.
Implements fizz::ReadRecordLayer.
Definition at line 98 of file EncryptedRecordLayer.cpp.
References folly::io::detail::CursorBase< Derived, BufType >::advanceToEnd(), fizz::alert, folly::IOBufQueue::append(), fizz::application_data, folly::IOBuf::create(), data, fizz::TLSMessage::fragment, folly::IOBufQueue::front(), getDecryptedBuf(), fizz::handshake, folly::IOBufQueue::move(), folly::gen::move, folly::none, folly::IOBufQueue::trimEnd(), and fizz::TLSMessage::type.
{
   auto decryptedBuf = getDecryptedBuf(buf);
   if (!decryptedBuf) {
     return folly::none;
   }
   folly::IOBufQueue decrypted;
   decrypted.append(std::move(*decryptedBuf));
   folly::io::Cursor paddingCursor(decrypted.front());
   paddingCursor.advanceToEnd();
   while (!*(paddingCursor -= 1).data()) {
   }
   TLSMessage msg;
   msg.type = static_cast<ContentType>(paddingCursor.readBE<ContentTypeType>());
   decrypted.trimEnd(paddingCursor.totalLength() + sizeof(ContentType));
   msg.fragment = decrypted.move();
   switch (msg.type) {
     case ContentType::handshake:
     case ContentType::alert:
     case ContentType::application_data:
       break;
     default:
       throw std::runtime_error(folly::to<std::string>(
           "received encrypted content type ",
           static_cast<ContentTypeType>(msg.type)));
   }
   if (!msg.fragment) {
     if (msg.type == ContentType::application_data) {
       msg.fragment = folly::IOBuf::create(0);
     } else {
       throw std::runtime_error("received empty fragment");
     }
   }
   return std::move(msg);
 }
virtual void fizz::EncryptedReadRecordLayer::setAead (folly::ByteRange , std::unique_ptr< Aead > aead) inline virtual
Reimplemented in fizz::MockEncryptedReadRecordLayer.
Definition at line 28 of file EncryptedRecordLayer.h.
References aead_, folly::gen::move, and seqNum_.
{
     if (seqNum_ != 0) {
       throw std::runtime_error("aead set after read");
     }
     aead_ = std::move(aead);
   }
void fizz::EncryptedReadRecordLayer::setProtocolVersion (ProtocolVersion version) inline
Definition at line 41 of file EncryptedRecordLayer.h.
References getDecryptedBuf(), getEncryptionLevel(), fizz::getRealDraftVersion(), fizz::tls_1_3_20, fizz::tls_1_3_21, fizz::tls_1_3_22, fizz::tls_1_3_23, and useAdditionalData_.
{
     auto realVersion = getRealDraftVersion(version);
     if (realVersion == ProtocolVersion::tls_1_3_23 ||
         realVersion == ProtocolVersion::tls_1_3_22 ||
         realVersion == ProtocolVersion::tls_1_3_21 ||
         realVersion == ProtocolVersion::tls_1_3_20) {
       useAdditionalData_ = false;
     } else {
       useAdditionalData_ = true;
     }
   }
virtual void fizz::EncryptedReadRecordLayer::setSkipFailedDecryption (bool enabled) inline virtual
Definition at line 37 of file EncryptedRecordLayer.h.
References skipFailedDecryption_.
{
     skipFailedDecryption_ = enabled;
   }
Member Data Documentation
std::unique_ptr<Aead> fizz::EncryptedReadRecordLayer::aead_ private
Definition at line 59 of file EncryptedRecordLayer.h.
Referenced by getDecryptedBuf(), setAead(), and fizz::EncryptedWriteRecordLayer::setAead().
EncryptionLevel fizz::EncryptedReadRecordLayer::encryptionLevel_ private
Definition at line 58 of file EncryptedRecordLayer.h.
Referenced by getEncryptionLevel().
uint64_t fizz::EncryptedReadRecordLayer::seqNum_ {0} mutable private
Definition at line 64 of file EncryptedRecordLayer.h.
Referenced by getDecryptedBuf(), setAead(), and fizz::EncryptedWriteRecordLayer::setAead().
bool fizz::EncryptedReadRecordLayer::skipFailedDecryption_ {false} private
Definition at line 60 of file EncryptedRecordLayer.h.
Referenced by getDecryptedBuf(), and setSkipFailedDecryption().
bool fizz::EncryptedReadRecordLayer::useAdditionalData_ {true} private
Definition at line 62 of file EncryptedRecordLayer.h.
Referenced by getDecryptedBuf(), and setProtocolVersion().
The documentation for this class was generated from the following files:
proxygen/fizz/fizz/record/EncryptedRecordLayer.h
proxygen/fizz/fizz/record/EncryptedRecordLayer.cpp