proxygen: folly::FutureSplitter< T > Class Template Reference
folly::FutureSplitter< T > Class Template Reference
#include <Future.h>
Public Member Functions
FutureSplitter ()=default
FutureSplitter (Future< T > &&future)
Future< T > getFuture ()
SemiFuture< T > getSemiFuture ()
Static Private Member Functions
static Executor * getExecutorFrom (Future< T > &f)
Private Attributes
std::shared_ptr< SharedPromise< T > > promise_
Executor * e_ = nullptr
int8_t priority_ {-1}
Detailed Description
template<class T>
class folly::FutureSplitter< T >
Definition at line 110 of file Future.h.
Constructor & Destructor Documentation
template<class T> folly::FutureSplitter< T >::FutureSplitter () default
Default constructor for convenience only. It is an error to call getFuture() on a default-constructed FutureSplitter which has not had a correctly-constructed FutureSplitter copy- or move-assigned into it.
template<class T> folly::FutureSplitter< T >::FutureSplitter (Future< T > && future) inline explicit
Provide a way to split a Future<T>.
Definition at line 52 of file FutureSplitter.h.
References folly::gen::move, and promise_.
       : promise_(std::make_shared<SharedPromise<T>>()),
         e_(getExecutorFrom(future)),
         priority_(future.getPriority()) {
     std::move(future).thenTry([promise = promise_](Try<T>&& theTry) {
       promise->setTry(std::move(theTry));
     });
   }
Member Function Documentation
template<class T> static Executor* folly::FutureSplitter< T >::getExecutorFrom (Future< T > & f) inline static private
Definition at line 86 of file FutureSplitter.h.
References folly::futures::detail::FutureBase< T >::getExecutor(), and folly::InlineExecutor::instance().
{
     // If the passed future had a null executor, use an inline executor
     // to ensure that .via is safe
     auto* e = f.getExecutor();
     return e ? e : &InlineExecutor::instance();
   }
template<class T> Future<T> folly::FutureSplitter< T >::getFuture () inline
This can be called an unlimited number of times per FutureSplitter.
Definition at line 64 of file FutureSplitter.h.
References promise_.
Referenced by TEST().
{
     if (promise_ == nullptr) {
       throw_exception<FutureSplitterInvalid>();
     }
     return promise_->getSemiFuture().via(e_, priority_);
   }
template<class T> SemiFuture<T> folly::FutureSplitter< T >::getSemiFuture () inline
This can be called an unlimited number of times per FutureSplitter.
Definition at line 74 of file FutureSplitter.h.
References promise_.
Referenced by TEST().
{
     if (promise_ == nullptr) {
       throw_exception<FutureSplitterInvalid>();
     }
     return promise_->getSemiFuture();
   }
Member Data Documentation
template<class T> Executor* folly::FutureSplitter< T >::e_ = nullptr private
Definition at line 83 of file FutureSplitter.h.
template<class T> int8_t folly::FutureSplitter< T >::priority_ {-1} private
Definition at line 84 of file FutureSplitter.h.
template<class T> std::shared_ptr<SharedPromise<T> > folly::FutureSplitter< T >::promise_ private
Definition at line 82 of file FutureSplitter.h.
The documentation for this class was generated from the following files:
proxygen/folly/folly/futures/Future.h
proxygen/folly/folly/futures/FutureSplitter.h