proxygen: folly::ExpectWriteErrorCallback Class Reference
folly::ExpectWriteErrorCallback Class Reference
#include <AsyncSSLSocketTest.h>
Public Member Functions
ExpectWriteErrorCallback (SendMsgParamsCallbackBase *mcb=nullptr)
~ExpectWriteErrorCallback () override
Public Member Functions inherited from folly::WriteCallbackBase
WriteCallbackBase (SendMsgParamsCallbackBase *mcb=nullptr)
~WriteCallbackBase () override
virtual void setSocket (const std::shared_ptr< AsyncSSLSocket > &socket)
void writeSuccess () noexceptoverride
void writeErr (size_t nBytesWritten, const AsyncSocketException &ex) noexceptoverride
Public Member Functions inherited from folly::AsyncWriter::WriteCallback
virtual ~WriteCallback ()=default
Additional Inherited Members
Public Attributes inherited from folly::WriteCallbackBase
std::shared_ptr< AsyncSSLSocket > socket_
StateEnum state
size_t bytesWritten
AsyncSocketException exception
SendMsgParamsCallbackBase * mcb_
Detailed Description
Definition at line 172 of file AsyncSSLSocketTest.h.
Constructor & Destructor Documentation
folly::ExpectWriteErrorCallback::ExpectWriteErrorCallback (SendMsgParamsCallbackBase * mcb = nullptr) inline explicit
Definition at line 174 of file AsyncSSLSocketTest.h.
       : WriteCallbackBase(mcb) {}
folly::ExpectWriteErrorCallback::~ExpectWriteErrorCallback () inline override
Definition at line 177 of file AsyncSSLSocketTest.h.
References folly::AsyncSocket::OptionKey::apply(), folly::data(), EXPECT_EQ, EXPECT_NE, EXPECT_TRUE, folly::AsyncSocketException::INTERNAL_ERROR, folly::pushmi::__adl::noexcept(), folly::netops::recvmsg(), folly::SendMsgParamsCallbackBase::setSocket(), folly::WriteCallbackBase::setSocket(), folly::netops::socket(), folly::SendMsgParamsCallbackBase::socket_, folly::STATE_FAILED, and folly::STATE_SUCCEEDED.
{
     EXPECT_EQ(STATE_FAILED, state);
     EXPECT_EQ(
         exception.getType(),
         AsyncSocketException::AsyncSocketExceptionType::NETWORK_ERROR);
     EXPECT_EQ(exception.getErrno(), 22);
     // Suppress the assert in  ~WriteCallbackBase()
     state = STATE_SUCCEEDED;
   }
The documentation for this class was generated from the following file:
proxygen/folly/folly/io/async/test/AsyncSSLSocketTest.h