proxygen: ServerSerializeHandler Class Reference
ServerSerializeHandler Class Reference
#include <ServerSerializeHandler.h>
Public Member Functions
void read (Context *ctx, std::unique_ptr< folly::IOBuf > msg) override
folly::Future< folly::Unit > write (Context *ctx, thrift::test::Xtruct b) override
Public Member Functions inherited from wangle::Handler< std::unique_ptr< folly::IOBuf >, thrift::test::Bonk, thrift::test::Xtruct, std::unique_ptr< folly::IOBuf > >
~Handler () override=default
virtual void readEOF (Context *ctx)
virtual void readException (Context *ctx, folly::exception_wrapper e)
virtual void transportActive (Context *ctx)
virtual void transportInactive (Context *ctx)
virtual folly::Future< folly::Unit > writeException (Context *ctx, folly::exception_wrapper e)
virtual folly::Future< folly::Unit > close (Context *ctx)
Public Member Functions inherited from wangle::HandlerBase< HandlerContext< thrift::test::Bonk, std::unique_ptr< folly::IOBuf > > >
virtual ~HandlerBase ()=default
virtual void attachPipeline (HandlerContext< thrift::test::Bonk, std::unique_ptr< folly::IOBuf > > *)
virtual void detachPipeline (HandlerContext< thrift::test::Bonk, std::unique_ptr< folly::IOBuf > > *)
HandlerContext< thrift::test::Bonk, std::unique_ptr< folly::IOBuf > > * getContext ()
Additional Inherited Members
Public Types inherited from wangle::Handler< std::unique_ptr< folly::IOBuf >, thrift::test::Bonk, thrift::test::Xtruct, std::unique_ptr< folly::IOBuf > >
typedef std::unique_ptr< folly::IOBuf > rin
typedef thrift::test::Bonk rout
typedef thrift::test::Xtruct win
typedef std::unique_ptr< folly::IOBuf > wout
typedef HandlerContext< thrift::test::Bonk, std::unique_ptr< folly::IOBuf > > Context
Static Public Attributes inherited from wangle::Handler< std::unique_ptr< folly::IOBuf >, thrift::test::Bonk, thrift::test::Xtruct, std::unique_ptr< folly::IOBuf > >
static const HandlerDir dir
Detailed Description
Definition at line 25 of file ServerSerializeHandler.h.
Member Function Documentation
void ServerSerializeHandler::read (Context * ctx, std::unique_ptr< folly::IOBuf > msg) inline override virtual
Implements wangle::Handler< std::unique_ptr< folly::IOBuf >, thrift::test::Bonk, thrift::test::Xtruct, std::unique_ptr< folly::IOBuf > >.
Definition at line 29 of file ServerSerializeHandler.h.
References wangle::HandlerContext< In, Out >::fireRead().
{
     thrift::test::Bonk received =
         apache::thrift::CompactSerializer::deserialize<thrift::test::Bonk>(
             msg.get());
     ctx->fireRead(received);
   }
folly::Future<folly::Unit> ServerSerializeHandler::write (Context * ctx, thrift::test::Xtruct b) inline override virtual
Implements wangle::Handler< std::unique_ptr< folly::IOBuf >, thrift::test::Bonk, thrift::test::Xtruct, std::unique_ptr< folly::IOBuf > >.
Definition at line 36 of file ServerSerializeHandler.h.
References folly::IOBuf::copyBuffer(), wangle::HandlerContext< In, Out >::fireWrite(), folly::json::serialize(), and string.
                {
     std::string out;
     apache::thrift::CompactSerializer::serialize(b, &out);
     return ctx->fireWrite(folly::IOBuf::copyBuffer(out));
   }
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/example/rpc/ServerSerializeHandler.h