proxygen: folly::detail::IteratorFacade< D, V, Tag > Class Template Reference
folly::detail::IteratorFacade< D, V, Tag > Class Template Reference
#include <Iterators.h>
Public Types
using value_type = V
using reference = value_type &
using pointer = value_type *
using difference_type = ssize_t
using iterator_category = Tag
Public Member Functions
bool operator== (D const &rhs) const
bool operator!= (D const &rhs) const
template<class D2 >
std::enable_if< std::is_convertible< D, D2 >::value, bool >::type operator== (D2 const &rhs) const
template<class D2 >
bool operator!= (D2 const &rhs) const
V & operator* () const
V * operator-> () const
D & operator++ ()
D operator++ (int)
D & operator-- ()
D operator-- (int)
Private Member Functions
D & asDerived ()
D const & asDerivedConst () const
Detailed Description
template<class D, class V, class Tag>
class folly::detail::IteratorFacade< D, V, Tag >
Currently this only supports forward and bidirectional iteration. The derived class must must have definitions for these methods:
void increment(); void decrement(); // optional, to be used with bidirectional reference dereference() const; bool equal([appropriate iterator type] const& rhs) const;
These names are consistent with those used by the Boost iterator facade / adaptor classes to ease migration classes in this file.
Template parameters: D: the deriving class (CRTP) V: value type Tag: the iterator category, one of: std::forward_iterator_tag std::bidirectional_iterator_tag
Definition at line 72 of file Iterators.h.
Member Typedef Documentation
template<class D, class V, class Tag> using folly::detail::IteratorFacade< D, V, Tag >::difference_type = ssize_t
Definition at line 77 of file Iterators.h.
template<class D, class V, class Tag> using folly::detail::IteratorFacade< D, V, Tag >::iterator_category = Tag
Definition at line 78 of file Iterators.h.
template<class D, class V, class Tag> using folly::detail::IteratorFacade< D, V, Tag >::pointer = value_type*
Definition at line 76 of file Iterators.h.
template<class D, class V, class Tag> using folly::detail::IteratorFacade< D, V, Tag >::reference = value_type&
Definition at line 75 of file Iterators.h.
template<class D, class V, class Tag> using folly::detail::IteratorFacade< D, V, Tag >::value_type = V
Definition at line 74 of file Iterators.h.
Member Function Documentation
template<class D, class V, class Tag> D& folly::detail::IteratorFacade< D, V, Tag >::asDerived () inline private
Definition at line 138 of file Iterators.h.
Referenced by folly::detail::IteratorFacade< dynamic::const_key_iterator, dynamic const , std::forward_iterator_tag >::operator++(), and folly::detail::IteratorFacade< dynamic::const_key_iterator, dynamic const , std::forward_iterator_tag >::operator--().
                  {
     return static_cast<D&>(*this);
   }
template<class D, class V, class Tag> D const& folly::detail::IteratorFacade< D, V, Tag >::asDerivedConst () const inline private
Definition at line 142 of file Iterators.h.
Referenced by folly::detail::IteratorFacade< dynamic::const_key_iterator, dynamic const , std::forward_iterator_tag >::operator*(), and folly::detail::IteratorFacade< dynamic::const_key_iterator, dynamic const , std::forward_iterator_tag >::operator==().
{
     return static_cast<D const&>(*this);
   }
template<class D, class V, class Tag> bool folly::detail::IteratorFacade< D, V, Tag >::operator!= (D const & rhs) const inline
Definition at line 84 of file Iterators.h.
{
     return !operator==(rhs);
   }
template<class D, class V, class Tag> template<class D2 > bool folly::detail::IteratorFacade< D, V, Tag >::operator!= (D2 const & rhs) const inline
Definition at line 103 of file Iterators.h.
{
     return !operator==(rhs);
   }
template<class D, class V, class Tag> V& folly::detail::IteratorFacade< D, V, Tag >::operator* () const inline
Definition at line 107 of file Iterators.h.
{
     return asDerivedConst().dereference();
   }
template<class D, class V, class Tag> D& folly::detail::IteratorFacade< D, V, Tag >::operator++ () inline
Definition at line 115 of file Iterators.h.
                   {
     asDerived().increment();
     return asDerived();
   }
template<class D, class V, class Tag> D folly::detail::IteratorFacade< D, V, Tag >::operator++ (int) inline
Definition at line 120 of file Iterators.h.
                     {
     auto ret = asDerived(); // copy
     asDerived().increment();
     return ret;
   }
template<class D, class V, class Tag> D& folly::detail::IteratorFacade< D, V, Tag >::operator-- () inline
Definition at line 126 of file Iterators.h.
                   {
     asDerived().decrement();
     return asDerived();
   }
template<class D, class V, class Tag> D folly::detail::IteratorFacade< D, V, Tag >::operator-- (int) inline
Definition at line 131 of file Iterators.h.
                     {
     auto ret = asDerived(); // copy
     asDerived().decrement();
     return ret;
   }
template<class D, class V, class Tag> V* folly::detail::IteratorFacade< D, V, Tag >::operator-> () const inline
Definition at line 111 of file Iterators.h.
{
     return std::addressof(operator*());
   }
template<class D, class V, class Tag> bool folly::detail::IteratorFacade< D, V, Tag >::operator== (D const & rhs) const inline
Definition at line 80 of file Iterators.h.
Referenced by folly::detail::IteratorFacade< dynamic::const_key_iterator, dynamic const , std::forward_iterator_tag >::operator!=().
{
     return asDerivedConst().equal(rhs);
   }
template<class D, class V, class Tag> template<class D2 > std::enable_if<std::is_convertible<D, D2>::value, bool>::type folly::detail::IteratorFacade< D, V, Tag >::operator== (D2 const & rhs) const inline
Definition at line 98 of file Iterators.h.
{
     return D2(asDerivedConst()) == rhs;
   }
The documentation for this class was generated from the following file:
proxygen/folly/folly/detail/Iterators.h