proxygen: wangle::ExpiringFilter< Req, Resp > Class Template Reference
wangle::ExpiringFilter< Req, Resp > Class Template Reference
#include <ExpiringFilter.h>
Public Member Functions
ExpiringFilter (std::shared_ptr< Service< Req, Resp >> service, std::chrono::milliseconds idleTimeoutTime=std::chrono::milliseconds(0), std::chrono::milliseconds maxTime=std::chrono::milliseconds(0), folly::Timekeeper *timekeeper=nullptr)
~ExpiringFilter () override
void startIdleTimer ()
folly::Future< Resp > operator() (Req req) override
Public Member Functions inherited from wangle::ServiceFilter< Req, Resp >
ServiceFilter (std::shared_ptr< Service< Req, Resp >> service)
~ServiceFilter () override=default
folly::Future< folly::Unit > close () override
bool isAvailable () override
Public Member Functions inherited from wangle::Service< Req, Resp >
virtual ~Service ()=default
Private Attributes
folly::Future< folly::Unit > idleTimeout_
folly::Future< folly::Unit > maxTimeout_
std::chrono::milliseconds idleTimeoutTime_ {0}
std::chrono::milliseconds maxTime_ {0}
folly::Timekeeper * timekeeper_
uint32_t requests_ {0}
Additional Inherited Members
Protected Attributes inherited from wangle::ServiceFilter< Req, Resp >
std::shared_ptr< Service< Req, Resp > > service_
Detailed Description
template<typename Req, typename Resp = Req>
class wangle::ExpiringFilter< Req, Resp >
A service filter that expires the self service after a certain amount of idle time, or after a maximum amount of time total. Idle timeout is cancelled when any requests are outstanding.
Definition at line 28 of file ExpiringFilter.h.
Constructor & Destructor Documentation
template<typename Req, typename Resp = Req> wangle::ExpiringFilter< Req, Resp >::ExpiringFilter (std::shared_ptr< Service< Req, Resp >> service, std::chrono::milliseconds idleTimeoutTime = std::chrono::milliseconds(0), std::chrono::milliseconds maxTime = std::chrono::milliseconds(0), folly::Timekeeper * timekeeper = nullptr) inline explicit
Definition at line 30 of file ExpiringFilter.h.
References wangle::ServiceFilter< Req, Resp >::close(), wangle::ExpiringFilter< Req, Resp >::maxTime_, wangle::ExpiringFilter< Req, Resp >::maxTimeout_, folly::gen::move, folly::futures::sleep(), wangle::ExpiringFilter< Req, Resp >::startIdleTimer(), and wangle::ExpiringFilter< Req, Resp >::timekeeper_.
   : ServiceFilter<Req, Resp>(service)
   , idleTimeoutTime_(idleTimeoutTime)
   , maxTime_(maxTime)
   , timekeeper_(timekeeper) {
     if (maxTime_ > std::chrono::milliseconds(0)) {
       maxTimeout_ = folly::futures::sleep(maxTime_, timekeeper_);
       std::move(maxTimeout_).thenValue([this](auto&&) { this->close(); });
     }
     startIdleTimer();
   }
template<typename Req, typename Resp = Req> wangle::ExpiringFilter< Req, Resp >::~ExpiringFilter () inline override
Definition at line 48 of file ExpiringFilter.h.
References wangle::ExpiringFilter< Req, Resp >::idleTimeout_, and wangle::ExpiringFilter< Req, Resp >::maxTimeout_.
{
     if (!idleTimeout_.isReady()) {
       idleTimeout_.cancel();
     }
     if (!maxTimeout_.isReady()) {
       maxTimeout_.cancel();
     }
   }
Member Function Documentation
template<typename Req, typename Resp = Req> folly::Future<Resp> wangle::ExpiringFilter< Req, Resp >::operator() (Req req) inline override virtual
Implements wangle::Service< Req, Resp >.
Definition at line 67 of file ExpiringFilter.h.
References wangle::ExpiringFilter< Req, Resp >::idleTimeout_, folly::gen::move, wangle::ExpiringFilter< Req, Resp >::requests_, wangle::ServiceFilter< Req, Resp >::service_, and wangle::ExpiringFilter< Req, Resp >::startIdleTimer().
{
     if (!idleTimeout_.isReady()) {
       idleTimeout_.cancel();
     }
     requests_++;
     return (*this->service_)(std::move(req)).ensure([this](){
         requests_--;
         startIdleTimer();
     });
   }
template<typename Req, typename Resp = Req> void wangle::ExpiringFilter< Req, Resp >::startIdleTimer () inline
Definition at line 57 of file ExpiringFilter.h.
References wangle::ServiceFilter< Req, Resp >::close(), wangle::ExpiringFilter< Req, Resp >::idleTimeout_, wangle::ExpiringFilter< Req, Resp >::idleTimeoutTime_, folly::gen::move, wangle::ExpiringFilter< Req, Resp >::requests_, folly::futures::sleep(), and wangle::ExpiringFilter< Req, Resp >::timekeeper_.
Referenced by wangle::ExpiringFilter< Req, Resp >::ExpiringFilter(), and wangle::ExpiringFilter< Req, Resp >::operator()().
{
     if (requests_ != 0) {
       return;
     }
     if (idleTimeoutTime_ > std::chrono::milliseconds(0)) {
       idleTimeout_ = folly::futures::sleep(idleTimeoutTime_, timekeeper_);
       std::move(idleTimeout_).thenValue([this](auto&&) { this->close(); });
     }
   }
Member Data Documentation
template<typename Req, typename Resp = Req> folly::Future<folly::Unit> wangle::ExpiringFilter< Req, Resp >::idleTimeout_ private
Definition at line 79 of file ExpiringFilter.h.
Referenced by wangle::ExpiringFilter< Req, Resp >::operator()(), wangle::ExpiringFilter< Req, Resp >::startIdleTimer(), and wangle::ExpiringFilter< Req, Resp >::~ExpiringFilter().
template<typename Req, typename Resp = Req> std::chrono::milliseconds wangle::ExpiringFilter< Req, Resp >::idleTimeoutTime_ {0} private
Definition at line 81 of file ExpiringFilter.h.
Referenced by wangle::ExpiringFilter< Req, Resp >::startIdleTimer().
template<typename Req, typename Resp = Req> std::chrono::milliseconds wangle::ExpiringFilter< Req, Resp >::maxTime_ {0} private
Definition at line 82 of file ExpiringFilter.h.
Referenced by wangle::ExpiringFilter< Req, Resp >::ExpiringFilter().
template<typename Req, typename Resp = Req> folly::Future<folly::Unit> wangle::ExpiringFilter< Req, Resp >::maxTimeout_ private
Definition at line 80 of file ExpiringFilter.h.
Referenced by wangle::ExpiringFilter< Req, Resp >::ExpiringFilter(), and wangle::ExpiringFilter< Req, Resp >::~ExpiringFilter().
template<typename Req, typename Resp = Req> uint32_t wangle::ExpiringFilter< Req, Resp >::requests_ {0} private
Definition at line 84 of file ExpiringFilter.h.
Referenced by wangle::ExpiringFilter< Req, Resp >::operator()(), and wangle::ExpiringFilter< Req, Resp >::startIdleTimer().
template<typename Req, typename Resp = Req> folly::Timekeeper* wangle::ExpiringFilter< Req, Resp >::timekeeper_ private
Definition at line 83 of file ExpiringFilter.h.
Referenced by wangle::ExpiringFilter< Req, Resp >::ExpiringFilter(), and wangle::ExpiringFilter< Req, Resp >::startIdleTimer().
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/service/ExpiringFilter.h