proxygen: wangle::Subscriber< T, R > Class Template Reference
wangle::Subscriber< T, R > Class Template Reference abstract
#include <Subscriber.h>
Public Member Functions
virtual ~Subscriber ()
virtual void onNext (const T &)=0
virtual void onError (folly::exception_wrapper ex)=0
virtual void onCompleted ()=0
virtual R & routingData ()=0
Detailed Description
template<typename T, typename R>
class wangle::Subscriber< T, R >
Subscriber interface for listening to a stream.
Definition at line 26 of file Subscriber.h.
Constructor & Destructor Documentation
template<typename T, typename R> virtual wangle::Subscriber< T, R >::~Subscriber () inline virtual
Definition at line 28 of file Subscriber.h.
 {}
Member Function Documentation
template<typename T, typename R> virtual void wangle::Subscriber< T, R >::onCompleted () pure virtual
Implemented in wangle::ObservingHandler< T, R, P >, and wangle::ObservingHandler< int, std::string >.
Referenced by wangle::BroadcastHandler< T, R >::readEOF(), and wangle::Subscriber< std::string, std::string >::~Subscriber().
template<typename T, typename R> virtual void wangle::Subscriber< T, R >::onError (folly::exception_wrapper ex) pure virtual
Implemented in wangle::ObservingHandler< T, R, P >, and wangle::ObservingHandler< int, std::string >.
Referenced by wangle::BroadcastHandler< T, R >::readException(), and wangle::Subscriber< std::string, std::string >::~Subscriber().
template<typename T, typename R> virtual void wangle::Subscriber< T, R >::onNext (const T &) pure virtual
Implemented in wangle::ObservingHandler< T, R, P >, and wangle::ObservingHandler< int, std::string >.
Referenced by wangle::BroadcastHandler< T, R >::read(), and wangle::Subscriber< std::string, std::string >::~Subscriber().
template<typename T, typename R> virtual R& wangle::Subscriber< T, R >::routingData () pure virtual
Implemented in wangle::ObservingHandler< T, R, P >, and wangle::ObservingHandler< int, std::string >.
Referenced by wangle::MockObservingPipelineFactory::newPipeline(), and wangle::Subscriber< std::string, std::string >::~Subscriber().
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/channel/broadcast/Subscriber.h