proxygen: testing::gmock_matchers_test::IsHalfOfMatcher Class Reference
testing::gmock_matchers_test::IsHalfOfMatcher Class Reference
Public Member Functions
template<typename T1 , typename T2 >
bool MatchAndExplain (const tuple< T1, T2 > &a_pair, MatchResultListener *listener) const
void DescribeTo (ostream *os) const
void DescribeNegationTo (ostream *os) const
template<typename T1 , typename T2 >
bool MatchAndExplain (const tuple< T1, T2 > &a_pair, MatchResultListener *listener) const
void DescribeTo (ostream *os) const
void DescribeNegationTo (ostream *os) const
template<typename T1 , typename T2 >
bool MatchAndExplain (const tuple< T1, T2 > &a_pair, MatchResultListener *listener) const
void DescribeTo (ostream *os) const
void DescribeNegationTo (ostream *os) const
Detailed Description
Definition at line 5410 of file gmock-matchers_test.cc.
Member Function Documentation
void testing::gmock_matchers_test::IsHalfOfMatcher::DescribeNegationTo (ostream * os) const inline
Definition at line 5428 of file gmock-matchers_test.cc.
{
     *os << "are a pair where the first isn't half of the second";
   }
void testing::gmock_matchers_test::IsHalfOfMatcher::DescribeNegationTo (ostream * os) const inline
Definition at line 5428 of file gmock-matchers_test.cc.
References testing::gmock_matchers_test::Describe(), testing::gmock_matchers_test::DescribeNegation(), EXPECT_EQ, EXPECT_THAT, testing::gmock_matchers_test::Explain(), testing::Gt(), testing::gmock_matchers_test::IsHalfOf(), testing::Lt(), testing::MakePolymorphicMatcher(), testing::Not(), testing::Pointwise(), folly::detail::rhs, testing::internal::TEST(), and testing::UnorderedPointwise().
{
     *os << "are a pair where the first isn't half of the second";
   }
void testing::gmock_matchers_test::IsHalfOfMatcher::DescribeNegationTo (ostream * os) const inline
Definition at line 5428 of file gmock-matchers_test.cc.
References testing::gmock_matchers_test::Describe(), testing::gmock_matchers_test::DescribeNegation(), EXPECT_EQ, EXPECT_THAT, testing::gmock_matchers_test::Explain(), testing::Gt(), testing::gmock_matchers_test::IsHalfOf(), testing::Lt(), testing::MakePolymorphicMatcher(), testing::Not(), testing::Pointwise(), folly::detail::rhs, testing::internal::TEST(), and testing::UnorderedPointwise().
{
     *os << "are a pair where the first isn't half of the second";
   }
void testing::gmock_matchers_test::IsHalfOfMatcher::DescribeTo (ostream * os) const inline
Definition at line 5424 of file gmock-matchers_test.cc.
{
     *os << "are a pair where the first is half of the second";
   }
void testing::gmock_matchers_test::IsHalfOfMatcher::DescribeTo (ostream * os) const inline
Definition at line 5424 of file gmock-matchers_test.cc.
{
     *os << "are a pair where the first is half of the second";
   }
void testing::gmock_matchers_test::IsHalfOfMatcher::DescribeTo (ostream * os) const inline
Definition at line 5424 of file gmock-matchers_test.cc.
{
     *os << "are a pair where the first is half of the second";
   }
template<typename T1 , typename T2 > bool testing::gmock_matchers_test::IsHalfOfMatcher::MatchAndExplain (const tuple< T1, T2 > & a_pair, MatchResultListener * listener) const inline
Definition at line 5413 of file gmock-matchers_test.cc.
{
     if (get<0>(a_pair) == get<1>(a_pair)/2) {
       *listener << "where the second is " << get<1>(a_pair);
       return true;
     } else {
       *listener << "where the second/2 is " << get<1>(a_pair)/2;
       return false;
     }
   }
template<typename T1 , typename T2 > bool testing::gmock_matchers_test::IsHalfOfMatcher::MatchAndExplain (const tuple< T1, T2 > & a_pair, MatchResultListener * listener) const inline
Definition at line 5413 of file gmock-matchers_test.cc.
{
     if (get<0>(a_pair) == get<1>(a_pair)/2) {
       *listener << "where the second is " << get<1>(a_pair);
       return true;
     } else {
       *listener << "where the second/2 is " << get<1>(a_pair)/2;
       return false;
     }
   }
template<typename T1 , typename T2 > bool testing::gmock_matchers_test::IsHalfOfMatcher::MatchAndExplain (const tuple< T1, T2 > & a_pair, MatchResultListener * listener) const inline
Definition at line 5413 of file gmock-matchers_test.cc.
{
     if (get<0>(a_pair) == get<1>(a_pair)/2) {
       *listener << "where the second is " << get<1>(a_pair);
       return true;
     } else {
       *listener << "where the second/2 is " << get<1>(a_pair)/2;
       return false;
     }
   }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-matchers_test.cc