proxygen: wangle::ContextImpl< H > Class Template Reference
wangle::ContextImpl< H > Class Template Reference
#include <HandlerContext-inl.h>
Public Types
typedef H::rin Rin
typedef H::rout Rout
typedef H::win Win
typedef H::wout Wout
Public Member Functions
ContextImpl (std::weak_ptr< PipelineBase > pipeline, std::shared_ptr< H > handler)
ContextImpl ()
~ContextImpl () override=default
void fireRead (Rout msg) override
void fireReadEOF () override
void fireReadException (folly::exception_wrapper e) override
void fireTransportActive () override
void fireTransportInactive () override
folly::Future< folly::Unit > fireWrite (Wout msg) override
folly::Future< folly::Unit > fireWriteException (folly::exception_wrapper e) override
folly::Future< folly::Unit > fireClose () override
PipelineBase * getPipeline () override
std::shared_ptr< PipelineBase > getPipelineShared () override
void setWriteFlags (folly::WriteFlags flags) override
folly::WriteFlags getWriteFlags () override
void setReadBufferSettings (uint64_t minAvailable, uint64_t allocationSize) override
std::pair< uint64_t, uint64_t > getReadBufferSettings () override
void read (Rin msg) override
void readEOF () override
void readException (folly::exception_wrapper e) override
void transportActive () override
void transportInactive () override
folly::Future< folly::Unit > write (Win msg) override
folly::Future< folly::Unit > writeException (folly::exception_wrapper e) override
folly::Future< folly::Unit > close () override
Public Member Functions inherited from wangle::HandlerContext< H::rout, H::wout >
virtual ~HandlerContext ()=default
std::shared_ptr< folly::AsyncTransport > getTransport ()
Public Member Functions inherited from wangle::InboundLink< H::rin >
virtual ~InboundLink ()=default
Public Member Functions inherited from wangle::OutboundLink< H::win >
virtual ~OutboundLink ()=default
Public Member Functions inherited from wangle::ContextImplBase< H, HandlerContext< H::rout, H::wout > >
~ContextImplBase () override=default
H * getHandler ()
void initialize (std::weak_ptr< PipelineBase > pipeline, std::shared_ptr< H > handler)
void attachPipeline () override
void detachPipeline () override
void setNextIn (PipelineContext *ctx) override
void setNextOut (PipelineContext *ctx) override
HandlerDir getDirection () override
Public Member Functions inherited from wangle::PipelineContext
virtual ~PipelineContext ()=default
template<class H , class HandlerContext >
void attachContext (H *handler, HandlerContext *ctx)
template<class H , class HandlerContext >
void detachContext (H *handler, HandlerContext *)
Static Public Attributes
static const HandlerDir dir = HandlerDir::BOTH
Additional Inherited Members
Protected Attributes inherited from wangle::ContextImplBase< H, HandlerContext< H::rout, H::wout > >
HandlerContext< H::rout, H::wout > * impl_
std::weak_ptr< PipelineBase > pipelineWeak_
PipelineBase * pipelineRaw_
std::shared_ptr< H > handler_
InboundLink< typename H::rout > * nextIn_
OutboundLink< typename H::wout > * nextOut_
Detailed Description
template<class H>
class wangle::ContextImpl< H >
Definition at line 151 of file HandlerContext-inl.h.
Member Typedef Documentation
template<class H > typedef H::rin wangle::ContextImpl< H >::Rin
Definition at line 159 of file HandlerContext-inl.h.
template<class H > typedef H::rout wangle::ContextImpl< H >::Rout
Definition at line 160 of file HandlerContext-inl.h.
template<class H > typedef H::win wangle::ContextImpl< H >::Win
Definition at line 161 of file HandlerContext-inl.h.
template<class H > typedef H::wout wangle::ContextImpl< H >::Wout
Definition at line 162 of file HandlerContext-inl.h.
Constructor & Destructor Documentation
template<class H > wangle::ContextImpl< H >::ContextImpl (std::weak_ptr< PipelineBase > pipeline, std::shared_ptr< H > handler) inline explicit
Definition at line 165 of file HandlerContext-inl.h.
References folly::gen::move.
{
     this->impl_ = this;
     this->initialize(pipeline, std::move(handler));
   }
template<class H > wangle::ContextImpl< H >::ContextImpl () inline
Definition at line 173 of file HandlerContext-inl.h.
                 {
     this->impl_ = this;
   }
template<class H > wangle::ContextImpl< H >::~ContextImpl () override default
Member Function Documentation
template<class H > folly::Future<folly::Unit> wangle::ContextImpl< H >::close () inline override virtual
Implements wangle::OutboundLink< H::win >.
Definition at line 316 of file HandlerContext-inl.h.
References folly::gen::guard().
{
     auto guard = this->pipelineWeak_.lock();
     return this->handler_->close(this);
   }
template<class H > folly::Future<folly::Unit> wangle::ContextImpl< H >::fireClose () inline override virtual
Implements wangle::HandlerContext< H::rout, H::wout >.
Definition at line 242 of file HandlerContext-inl.h.
References folly::gen::guard(), folly::makeFuture(), and folly::WARNING.
{
     auto guard = this->pipelineWeak_.lock();
     if (this->nextOut_) {
       return this->nextOut_->close();
     } else {
       LOG(WARNING) << "close reached end of pipeline";
       return folly::makeFuture();
     }
   }
template<class H > void wangle::ContextImpl< H >::fireRead (Rout msg) inline override virtual
Implements wangle::HandlerContext< H::rout, H::wout >.
Definition at line 180 of file HandlerContext-inl.h.
References folly::gen::guard(), and folly::WARNING.
{
     auto guard = this->pipelineWeak_.lock();
     if (this->nextIn_) {
       this->nextIn_->read(std::forward<Rout>(msg));
     } else {
       LOG(WARNING) << "read reached end of pipeline";
     }
   }
template<class H > void wangle::ContextImpl< H >::fireReadEOF () inline override virtual
Implements wangle::HandlerContext< H::rout, H::wout >.
Definition at line 189 of file HandlerContext-inl.h.
References folly::gen::guard(), and folly::WARNING.
{
     auto guard = this->pipelineWeak_.lock();
     if (this->nextIn_) {
       this->nextIn_->readEOF();
     } else {
       LOG(WARNING) << "readEOF reached end of pipeline";
     }
   }
template<class H > void wangle::ContextImpl< H >::fireReadException (folly::exception_wrapper e) inline override virtual
Implements wangle::HandlerContext< H::rout, H::wout >.
Definition at line 198 of file HandlerContext-inl.h.
References folly::gen::guard(), folly::gen::move, and folly::WARNING.
{
     auto guard = this->pipelineWeak_.lock();
     if (this->nextIn_) {
       this->nextIn_->readException(std::move(e));
     } else {
       LOG(WARNING) << "readException reached end of pipeline";
     }
   }
template<class H > void wangle::ContextImpl< H >::fireTransportActive () inline override virtual
Implements wangle::HandlerContext< H::rout, H::wout >.
Definition at line 207 of file HandlerContext-inl.h.
References folly::gen::guard().
{
     auto guard = this->pipelineWeak_.lock();
     if (this->nextIn_) {
       this->nextIn_->transportActive();
     }
   }
template<class H > void wangle::ContextImpl< H >::fireTransportInactive () inline override virtual
Implements wangle::HandlerContext< H::rout, H::wout >.
Definition at line 214 of file HandlerContext-inl.h.
References folly::gen::guard().
{
     auto guard = this->pipelineWeak_.lock();
     if (this->nextIn_) {
       this->nextIn_->transportInactive();
     }
   }
template<class H > folly::Future<folly::Unit> wangle::ContextImpl< H >::fireWrite (Wout msg) inline override virtual
Implements wangle::HandlerContext< H::rout, H::wout >.
Definition at line 221 of file HandlerContext-inl.h.
References folly::gen::guard(), folly::makeFuture(), and folly::WARNING.
{
     auto guard = this->pipelineWeak_.lock();
     if (this->nextOut_) {
       return this->nextOut_->write(std::forward<Wout>(msg));
     } else {
       LOG(WARNING) << "write reached end of pipeline";
       return folly::makeFuture();
     }
   }
template<class H > folly::Future<folly::Unit> wangle::ContextImpl< H >::fireWriteException (folly::exception_wrapper e) inline override virtual
Implements wangle::HandlerContext< H::rout, H::wout >.
Definition at line 231 of file HandlerContext-inl.h.
References folly::gen::guard(), folly::makeFuture(), folly::gen::move, and folly::WARNING.
{
     auto guard = this->pipelineWeak_.lock();
     if (this->nextOut_) {
       return this->nextOut_->writeException(std::move(e));
     } else {
       LOG(WARNING) << "close reached end of pipeline";
       return folly::makeFuture();
     }
   }
template<class H > PipelineBase* wangle::ContextImpl< H >::getPipeline () inline override virtual
Implements wangle::HandlerContext< H::rout, H::wout >.
Definition at line 252 of file HandlerContext-inl.h.
{
     return this->pipelineRaw_;
   }
template<class H > std::shared_ptr<PipelineBase> wangle::ContextImpl< H >::getPipelineShared () inline override virtual
Implements wangle::HandlerContext< H::rout, H::wout >.
Definition at line 256 of file HandlerContext-inl.h.
{
     return this->pipelineWeak_.lock();
   }
template<class H > std::pair<uint64_t, uint64_t> wangle::ContextImpl< H >::getReadBufferSettings () inline override virtual
Implements wangle::HandlerContext< H::rout, H::wout >.
Definition at line 274 of file HandlerContext-inl.h.
{
     return this->pipelineRaw_->getReadBufferSettings();
   }
template<class H > folly::WriteFlags wangle::ContextImpl< H >::getWriteFlags () inline override virtual
Implements wangle::HandlerContext< H::rout, H::wout >.
Definition at line 264 of file HandlerContext-inl.h.
{
     return this->pipelineRaw_->getWriteFlags();
   }
template<class H > void wangle::ContextImpl< H >::read (Rin msg) inline override virtual
Implements wangle::InboundLink< H::rin >.
Definition at line 279 of file HandlerContext-inl.h.
References folly::gen::guard().
{
     auto guard = this->pipelineWeak_.lock();
     this->handler_->read(this, std::forward<Rin>(msg));
   }
template<class H > void wangle::ContextImpl< H >::readEOF () inline override virtual
Implements wangle::InboundLink< H::rin >.
Definition at line 284 of file HandlerContext-inl.h.
References folly::gen::guard().
{
     auto guard = this->pipelineWeak_.lock();
     this->handler_->readEOF(this);
   }
template<class H > void wangle::ContextImpl< H >::readException (folly::exception_wrapper e) inline override virtual
Implements wangle::InboundLink< H::rin >.
Definition at line 289 of file HandlerContext-inl.h.
References folly::gen::guard(), and folly::gen::move.
{
     auto guard = this->pipelineWeak_.lock();
     this->handler_->readException(this, std::move(e));
   }
template<class H > void wangle::ContextImpl< H >::setReadBufferSettings (uint64_t minAvailable, uint64_t allocationSize) inline override virtual
Implements wangle::HandlerContext< H::rout, H::wout >.
Definition at line 268 of file HandlerContext-inl.h.
{
     this->pipelineRaw_->setReadBufferSettings(minAvailable, allocationSize);
   }
template<class H > void wangle::ContextImpl< H >::setWriteFlags (folly::WriteFlags flags) inline override virtual
Implements wangle::HandlerContext< H::rout, H::wout >.
Definition at line 260 of file HandlerContext-inl.h.
{
     this->pipelineRaw_->setWriteFlags(flags);
   }
template<class H > void wangle::ContextImpl< H >::transportActive () inline override virtual
Implements wangle::InboundLink< H::rin >.
Definition at line 294 of file HandlerContext-inl.h.
References folly::gen::guard().
{
     auto guard = this->pipelineWeak_.lock();
     this->handler_->transportActive(this);
   }
template<class H > void wangle::ContextImpl< H >::transportInactive () inline override virtual
Implements wangle::InboundLink< H::rin >.
Definition at line 299 of file HandlerContext-inl.h.
References folly::gen::guard().
{
     auto guard = this->pipelineWeak_.lock();
     this->handler_->transportInactive(this);
   }
template<class H > folly::Future<folly::Unit> wangle::ContextImpl< H >::write (Win msg) inline override virtual
Implements wangle::OutboundLink< H::win >.
Definition at line 305 of file HandlerContext-inl.h.
References folly::gen::guard().
{
     auto guard = this->pipelineWeak_.lock();
     return this->handler_->write(this, std::forward<Win>(msg));
   }
template<class H > folly::Future<folly::Unit> wangle::ContextImpl< H >::writeException (folly::exception_wrapper e) inline override virtual
Implements wangle::OutboundLink< H::win >.
Definition at line 310 of file HandlerContext-inl.h.
References folly::gen::guard(), and folly::gen::move.
{
     auto guard = this->pipelineWeak_.lock();
     return this->handler_->writeException(this, std::move(e));
   }
Member Data Documentation
template<class H > const HandlerDir wangle::ContextImpl< H >::dir = HandlerDir::BOTH static
Definition at line 163 of file HandlerContext-inl.h.
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/channel/HandlerContext-inl.h