proxygen: testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher > Class Template Reference
testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher > Class Template Reference
#include <gmock-matchers.h>
Classes
class Impl
Public Member Functions
WhenSortedByMatcher (const Comparator &comparator, const ContainerMatcher &matcher)
template<typename LhsContainer >
operator Matcher< LhsContainer > () const
WhenSortedByMatcher (const Comparator &comparator, const ContainerMatcher &matcher)
template<typename LhsContainer >
operator Matcher< LhsContainer > () const
WhenSortedByMatcher (const Comparator &comparator, const ContainerMatcher &matcher)
template<typename LhsContainer >
operator Matcher< LhsContainer > () const
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (WhenSortedByMatcher)
GTEST_DISALLOW_ASSIGN_ (WhenSortedByMatcher)
GTEST_DISALLOW_ASSIGN_ (WhenSortedByMatcher)
Private Attributes
const Comparator comparator_
const ContainerMatcher matcher_
Detailed Description
template<typename Comparator, typename ContainerMatcher>
class testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >
Definition at line 2613 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename Comparator, typename ContainerMatcher> testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::WhenSortedByMatcher (const Comparator & comparator, const ContainerMatcher & matcher) inline
Definition at line 2615 of file gmock-matchers.h.
       : comparator_(comparator), matcher_(matcher) {}
template<typename Comparator, typename ContainerMatcher> testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::WhenSortedByMatcher (const Comparator & comparator, const ContainerMatcher & matcher) inline
Definition at line 2615 of file gmock-matchers.h.
       : comparator_(comparator), matcher_(matcher) {}
template<typename Comparator, typename ContainerMatcher> testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::WhenSortedByMatcher (const Comparator & comparator, const ContainerMatcher & matcher) inline
Definition at line 2615 of file gmock-matchers.h.
       : comparator_(comparator), matcher_(matcher) {}
Member Function Documentation
template<typename Comparator, typename ContainerMatcher> testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::GTEST_DISALLOW_ASSIGN_ (WhenSortedByMatcher< Comparator, ContainerMatcher >) private
template<typename Comparator, typename ContainerMatcher> testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::GTEST_DISALLOW_ASSIGN_ (WhenSortedByMatcher< Comparator, ContainerMatcher >) private
template<typename Comparator, typename ContainerMatcher> testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::GTEST_DISALLOW_ASSIGN_ (WhenSortedByMatcher< Comparator, ContainerMatcher >) private
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::operator Matcher< LhsContainer > () const inline
Definition at line 2620 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(new Impl<LhsContainer>(comparator_, matcher_));
   }
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::operator Matcher< LhsContainer > () const inline
Definition at line 2620 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(new Impl<LhsContainer>(comparator_, matcher_));
   }
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::operator Matcher< LhsContainer > () const inline
Definition at line 2620 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(new Impl<LhsContainer>(comparator_, matcher_));
   }
Member Data Documentation
template<typename Comparator, typename ContainerMatcher> const Comparator testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::comparator_ private
Definition at line 2682 of file gmock-matchers.h.
template<typename Comparator, typename ContainerMatcher> const ContainerMatcher testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::matcher_ private
Definition at line 2683 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h