proxygen: folly::symbolizer::AddressFormatter Class Reference
folly::symbolizer::AddressFormatter Class Reference
#include <Symbolizer.h>
Public Member Functions
AddressFormatter ()
StringPiece format (uintptr_t address)
Private Attributes
char buf_ [sizeof(bufTemplate)]
Static Private Attributes
static constexpr char bufTemplate [] = " @ 0000000000000000"
Detailed Description
Format one address in the way it's usually printed by SymbolizePrinter. Async-signal-safe.
Definition at line 163 of file Symbolizer.h.
Constructor & Destructor Documentation
folly::symbolizer::AddressFormatter::AddressFormatter ()
Definition at line 190 of file Symbolizer.cpp.
{
   memcpy(buf_, bufTemplate, sizeof(buf_));
 }
Member Function Documentation
folly::StringPiece folly::symbolizer::AddressFormatter::format (uintptr_t address)
Format the address. Returns an internal buffer.
Definition at line 194 of file Symbolizer.cpp.
References folly::test::end().
Referenced by folly::symbolizer::SymbolizePrinter::print(), folly::symbolizer::SafeStackTracePrinter::printStackTrace(), and folly::symbolizer::FastStackTracePrinter::printStackTrace().
{
   // Can't use sprintf, not async-signal-safe
   static_assert(sizeof(uintptr_t) <= 8, "huge uintptr_t?");
   char* end = buf_ + sizeof(buf_) - 1 - (16 - 2 * sizeof(uintptr_t));
   char* p = end;
   *p-- = '\0';
   while (address != 0) {
     *p-- = kHexChars[address & 0xf];
     address >>= 4;
   }
   return folly::StringPiece(buf_, end);
 }
Member Data Documentation
char folly::symbolizer::AddressFormatter::buf_[sizeof(bufTemplate)] private
Definition at line 174 of file Symbolizer.h.
constexpr char folly::symbolizer::AddressFormatter::bufTemplate = " @ 0000000000000000" static private
Definition at line 173 of file Symbolizer.h.
Referenced by folly::symbolizer::Symbolizer::symbolize().
The documentation for this class was generated from the following files:
proxygen/folly/folly/experimental/symbolizer/Symbolizer.h
proxygen/folly/folly/experimental/symbolizer/Symbolizer.cpp