proxygen: wangle::AsyncServerSocketFactory Class Reference
wangle::AsyncServerSocketFactory Class Reference
#include <ServerSocketFactory.h>
Classes
class ThreadSafeDestructor
Public Member Functions
std::shared_ptr< folly::AsyncSocketBase > newSocket (folly::SocketAddress address, int, bool reuse, const ServerSocketConfig &config) override
void removeAcceptCB (std::shared_ptr< folly::AsyncSocketBase > s, Acceptor *callback, folly::EventBase *base) override
void addAcceptCB (std::shared_ptr< folly::AsyncSocketBase > s, Acceptor *callback, folly::EventBase *base) override
Public Member Functions inherited from wangle::ServerSocketFactory
virtual ~ServerSocketFactory ()=default
Detailed Description
Definition at line 45 of file ServerSocketFactory.h.
Member Function Documentation
void wangle::AsyncServerSocketFactory::addAcceptCB (std::shared_ptr< folly::AsyncSocketBase > s, Acceptor * callback, folly::EventBase * base) inline override virtual
Implements wangle::ServerSocketFactory.
Definition at line 76 of file ServerSocketFactory.h.
References s, and folly::netops::socket().
{
     auto socket = std::dynamic_pointer_cast<folly::AsyncServerSocket>(s);
     CHECK(socket);
     socket->addAcceptCallback(callback, base);
   }
std::shared_ptr<folly::AsyncSocketBase> wangle::AsyncServerSocketFactory::newSocket (folly::SocketAddress address, int , bool reuse, const ServerSocketConfig & config) inline override virtual
Implements wangle::ServerSocketFactory.
Definition at line 47 of file ServerSocketFactory.h.
References wangle::ServerSocketConfig::acceptBacklog, wangle::ServerSocketConfig::enableTCPFastOpen, wangle::ServerSocketConfig::fastOpenQueueSize, folly::EventBaseManager::get(), folly::EventBaseManager::getEventBase(), wangle::ServerSocketConfig::maxNumPendingConnectionsPerWorker, and folly::netops::socket().
{
     auto* evb = folly::EventBaseManager::get()->getEventBase();
     std::shared_ptr<folly::AsyncServerSocket> socket(
         new folly::AsyncServerSocket(evb),
         ThreadSafeDestructor());
     socket->setMaxNumMessagesInQueue(
         config.maxNumPendingConnectionsPerWorker);
     socket->setReusePortEnabled(reuse);
     if (config.enableTCPFastOpen) {
       socket->setTFOEnabled(true, config.fastOpenQueueSize);
     }
     socket->bind(address);
     socket->listen(config.acceptBacklog);
     socket->startAccepting();
     return socket;
   }
void wangle::AsyncServerSocketFactory::removeAcceptCB (std::shared_ptr< folly::AsyncSocketBase > s, Acceptor * callback, folly::EventBase * base) inline override virtual
Implements wangle::ServerSocketFactory.
Definition at line 69 of file ServerSocketFactory.h.
References s, and folly::netops::socket().
{
     auto socket = std::dynamic_pointer_cast<folly::AsyncServerSocket>(s);
     CHECK(socket);
     socket->removeAcceptCallback(callback, base);
   }
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/bootstrap/ServerSocketFactory.h