proxygen: folly::detail::EventBaseLocalBase Class Reference
folly::detail::EventBaseLocalBase Class Reference
#include <EventBaseLocal.h>
Public Member Functions
EventBaseLocalBase ()
~EventBaseLocalBase () override
void erase (EventBase &evb)
void onEventBaseDestruction (EventBase &evb) override
Public Member Functions inherited from folly::detail::EventBaseLocalBaseBase
virtual ~EventBaseLocalBaseBase ()=default
Protected Member Functions
void setVoid (EventBase &evb, std::shared_ptr< void > &&ptr)
void * getVoid (EventBase &evb)
Protected Attributes
folly::Synchronized< std::unordered_set< EventBase * > > eventBases_
std::size_t key_ {keyCounter_++}
Static Protected Attributes
static std::atomic< std::size_t > keyCounter_ {0}
Detailed Description
Definition at line 31 of file EventBaseLocal.h.
Constructor & Destructor Documentation
folly::detail::EventBaseLocalBase::EventBaseLocalBase () inline
Definition at line 33 of file EventBaseLocal.h.
References erase(), getVoid(), onEventBaseDestruction(), ptr, setVoid(), and ~EventBaseLocalBase().
 {}
folly::detail::EventBaseLocalBase::~EventBaseLocalBase () override
Definition at line 25 of file EventBaseLocal.cpp.
References eventBases_, and key_.
Referenced by EventBaseLocalBase().
{
   auto locked = eventBases_.rlock();
   for (auto* evb : *locked) {
     evb->runInEventBaseThread([this, evb, key = key_] {
       evb->localStorage_.erase(key);
       evb->localStorageToDtor_.erase(this);
     });
   }
 }
Member Function Documentation
void folly::detail::EventBaseLocalBase::erase (EventBase & evb)
Definition at line 41 of file EventBaseLocal.cpp.
References folly::EventBase::dcheckIsInEventBaseThread(), eventBases_, key_, folly::EventBase::localStorage_, and folly::EventBase::localStorageToDtor_.
Referenced by EventBaseLocalBase(), and TEST().
{
   evb.dcheckIsInEventBaseThread();
   evb.localStorage_.erase(key_);
   evb.localStorageToDtor_.erase(this);
   eventBases_.wlock()->erase(&evb);
 }
void * folly::detail::EventBaseLocalBase::getVoid (EventBase & evb) protected
Definition at line 35 of file EventBaseLocal.cpp.
References folly::EventBase::dcheckIsInEventBaseThread(), folly::get_default(), key_, and folly::EventBase::localStorage_.
Referenced by EventBaseLocalBase(), folly::EventBaseLocal< T >::get(), folly::EventBaseLocal< T >::getOrCreate(), and folly::EventBaseLocal< T >::getOrCreateFn().
{
   evb.dcheckIsInEventBaseThread();
   return folly::get_default(evb.localStorage_, key_, {}).get();
 }
void folly::detail::EventBaseLocalBase::onEventBaseDestruction (EventBase & evb) override virtual
Implements folly::detail::EventBaseLocalBaseBase.
Definition at line 50 of file EventBaseLocal.cpp.
References folly::EventBase::dcheckIsInEventBaseThread(), and eventBases_.
Referenced by EventBaseLocalBase().
{
   evb.dcheckIsInEventBaseThread();
   eventBases_.wlock()->erase(&evb);
 }
void folly::detail::EventBaseLocalBase::setVoid (EventBase & evb, std::shared_ptr< void > && ptr) protected
Definition at line 56 of file EventBaseLocal.cpp.
References folly::EventBase::dcheckIsInEventBaseThread(), eventBases_, key_, keyCounter_, folly::EventBase::localStorage_, folly::EventBase::localStorageToDtor_, folly::gen::move, and ptr.
Referenced by folly::EventBaseLocal< T >::emplace(), EventBaseLocalBase(), folly::EventBaseLocal< T >::getOrCreate(), and folly::EventBaseLocal< T >::getOrCreateFn().
{
   evb.dcheckIsInEventBaseThread();
   auto alreadyExists = evb.localStorage_.find(key_) != evb.localStorage_.end();
   evb.localStorage_.emplace(key_, std::move(ptr));
   if (!alreadyExists) {
     eventBases_.wlock()->insert(&evb);
     evb.localStorageToDtor_.insert(this);
   }
 }
Member Data Documentation
folly::Synchronized<std::unordered_set<EventBase*> > folly::detail::EventBaseLocalBase::eventBases_ protected
Definition at line 42 of file EventBaseLocal.h.
Referenced by erase(), onEventBaseDestruction(), setVoid(), and ~EventBaseLocalBase().
std::size_t folly::detail::EventBaseLocalBase::key_ {keyCounter_++} protected
Definition at line 44 of file EventBaseLocal.h.
Referenced by erase(), getVoid(), setVoid(), and ~EventBaseLocalBase().
std::atomic< std::size_t > folly::detail::EventBaseLocalBase::keyCounter_ {0} static protected
Definition at line 43 of file EventBaseLocal.h.
Referenced by setVoid().
The documentation for this class was generated from the following files:
proxygen/folly/folly/io/async/EventBaseLocal.h
proxygen/folly/folly/io/async/EventBaseLocal.cpp