proxygen: testing::gmock_matchers_test::FloatingPointTest< RawType > Class Template Reference
testing::gmock_matchers_test::FloatingPointTest< RawType > Class Template Reference
Protected Types
typedef testing::internal::FloatingPoint< RawType > Floating
typedef Floating::Bits Bits
typedef testing::internal::FloatingPoint< RawType > Floating
typedef Floating::Bits Bits
typedef testing::internal::FloatingPoint< RawType > Floating
typedef Floating::Bits Bits
Protected Member Functions
FloatingPointTest ()
void TestSize ()
void TestMatches (testing::internal::FloatingEqMatcher< RawType >(*matcher_maker)(RawType))
FloatingPointTest ()
void TestSize ()
void TestMatches (testing::internal::FloatingEqMatcher< RawType >(*matcher_maker)(RawType))
FloatingPointTest ()
void TestSize ()
void TestMatches (testing::internal::FloatingEqMatcher< RawType >(*matcher_maker)(RawType))
Protected Member Functions inherited from testing::Test
Test ()
virtual void SetUp ()
virtual void TearDown ()
Test ()
virtual void SetUp ()
virtual void TearDown ()
Test ()
virtual void SetUp ()
virtual void TearDown ()
Protected Attributes
const size_t max_ulps_
const Bits zero_bits_
const Bits one_bits_
const Bits infinity_bits_
const RawType close_to_positive_zero_
const RawType close_to_negative_zero_
const RawType further_from_negative_zero_
const RawType close_to_one_
const RawType further_from_one_
const RawType infinity_
const RawType close_to_infinity_
const RawType further_from_infinity_
const RawType max_
const RawType nan1_
const RawType nan2_
Static Private Member Functions
template<typename T >
static RawType AsBits (T value)
template<typename T >
static RawType AsBits (T value)
template<typename T >
static RawType AsBits (T value)
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Detailed Description
template<typename RawType>
class testing::gmock_matchers_test::FloatingPointTest< RawType >
Definition at line 2705 of file gmock-matchers_test.cc.
Member Typedef Documentation
template<typename RawType > typedef Floating::Bits testing::gmock_matchers_test::FloatingPointTest< RawType >::Bits protected
Definition at line 2708 of file gmock-matchers_test.cc.
template<typename RawType > typedef Floating::Bits testing::gmock_matchers_test::FloatingPointTest< RawType >::Bits protected
Definition at line 2708 of file gmock-matchers_test.cc.
template<typename RawType > typedef Floating::Bits testing::gmock_matchers_test::FloatingPointTest< RawType >::Bits protected
Definition at line 2708 of file gmock-matchers_test.cc.
template<typename RawType > typedef testing::internal::FloatingPoint<RawType> testing::gmock_matchers_test::FloatingPointTest< RawType >::Floating protected
Definition at line 2707 of file gmock-matchers_test.cc.
template<typename RawType > typedef testing::internal::FloatingPoint<RawType> testing::gmock_matchers_test::FloatingPointTest< RawType >::Floating protected
Definition at line 2707 of file gmock-matchers_test.cc.
template<typename RawType > typedef testing::internal::FloatingPoint<RawType> testing::gmock_matchers_test::FloatingPointTest< RawType >::Floating protected
Definition at line 2707 of file gmock-matchers_test.cc.
Constructor & Destructor Documentation
template<typename RawType > testing::gmock_matchers_test::FloatingPointTest< RawType >::FloatingPointTest () inline protected
Definition at line 2710 of file gmock-matchers_test.cc.
       : max_ulps_(Floating::kMaxUlps),
         zero_bits_(Floating(0).bits()),
         one_bits_(Floating(1).bits()),
         infinity_bits_(Floating(Floating::Infinity()).bits()),
         close_to_positive_zero_(AsBits(zero_bits_ + max_ulps_/2)),
         close_to_negative_zero_(AsBits(zero_bits_ + max_ulps_ - max_ulps_/2)),
         further_from_negative_zero_(-AsBits(
             zero_bits_ + max_ulps_ + 1 - max_ulps_/2)),
         close_to_one_(AsBits(one_bits_ + max_ulps_)),
         further_from_one_(AsBits(one_bits_ + max_ulps_ + 1)),
         infinity_(Floating::Infinity()),
         close_to_infinity_(AsBits(infinity_bits_ - max_ulps_)),
         further_from_infinity_(AsBits(infinity_bits_ - max_ulps_ - 1)),
         max_(Floating::Max()),
         nan1_(AsBits(Floating::kExponentBitMask | 1)),
         nan2_(AsBits(Floating::kExponentBitMask | 200)) {
   }
template<typename RawType > testing::gmock_matchers_test::FloatingPointTest< RawType >::FloatingPointTest () inline protected
Definition at line 2710 of file gmock-matchers_test.cc.
       : max_ulps_(Floating::kMaxUlps),
         zero_bits_(Floating(0).bits()),
         one_bits_(Floating(1).bits()),
         infinity_bits_(Floating(Floating::Infinity()).bits()),
         close_to_positive_zero_(AsBits(zero_bits_ + max_ulps_/2)),
         close_to_negative_zero_(AsBits(zero_bits_ + max_ulps_ - max_ulps_/2)),
         further_from_negative_zero_(-AsBits(
             zero_bits_ + max_ulps_ + 1 - max_ulps_/2)),
         close_to_one_(AsBits(one_bits_ + max_ulps_)),
         further_from_one_(AsBits(one_bits_ + max_ulps_ + 1)),
         infinity_(Floating::Infinity()),
         close_to_infinity_(AsBits(infinity_bits_ - max_ulps_)),
         further_from_infinity_(AsBits(infinity_bits_ - max_ulps_ - 1)),
         max_(Floating::Max()),
         nan1_(AsBits(Floating::kExponentBitMask | 1)),
         nan2_(AsBits(Floating::kExponentBitMask | 200)) {
   }
template<typename RawType > testing::gmock_matchers_test::FloatingPointTest< RawType >::FloatingPointTest () inline protected
Definition at line 2710 of file gmock-matchers_test.cc.
       : max_ulps_(Floating::kMaxUlps),
         zero_bits_(Floating(0).bits()),
         one_bits_(Floating(1).bits()),
         infinity_bits_(Floating(Floating::Infinity()).bits()),
         close_to_positive_zero_(AsBits(zero_bits_ + max_ulps_/2)),
         close_to_negative_zero_(AsBits(zero_bits_ + max_ulps_ - max_ulps_/2)),
         further_from_negative_zero_(-AsBits(
             zero_bits_ + max_ulps_ + 1 - max_ulps_/2)),
         close_to_one_(AsBits(one_bits_ + max_ulps_)),
         further_from_one_(AsBits(one_bits_ + max_ulps_ + 1)),
         infinity_(Floating::Infinity()),
         close_to_infinity_(AsBits(infinity_bits_ - max_ulps_)),
         further_from_infinity_(AsBits(infinity_bits_ - max_ulps_ - 1)),
         max_(Floating::Max()),
         nan1_(AsBits(Floating::kExponentBitMask | 1)),
         nan2_(AsBits(Floating::kExponentBitMask | 200)) {
   }
Member Function Documentation
template<typename RawType > template<typename T > static RawType testing::gmock_matchers_test::FloatingPointTest< RawType >::AsBits (T value) inline static private
Definition at line 2810 of file gmock-matchers_test.cc.
{
     return Floating::ReinterpretBits(static_cast<Bits>(value));
   }
template<typename RawType > template<typename T > static RawType testing::gmock_matchers_test::FloatingPointTest< RawType >::AsBits (T value) inline static private
Definition at line 2810 of file gmock-matchers_test.cc.
{
     return Floating::ReinterpretBits(static_cast<Bits>(value));
   }
template<typename RawType > template<typename T > static RawType testing::gmock_matchers_test::FloatingPointTest< RawType >::AsBits (T value) inline static private
Definition at line 2810 of file gmock-matchers_test.cc.
{
     return Floating::ReinterpretBits(static_cast<Bits>(value));
   }
template<typename RawType > void testing::gmock_matchers_test::FloatingPointTest< RawType >::TestMatches (testing::internal::FloatingEqMatcher< RawType >(*)(RawType) matcher_maker) inline protected
Definition at line 2735 of file gmock-matchers_test.cc.
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and max_.
{
     Matcher<RawType> m1 = matcher_maker(0.0);
     EXPECT_TRUE(m1.Matches(-0.0));
     EXPECT_TRUE(m1.Matches(close_to_positive_zero_));
     EXPECT_TRUE(m1.Matches(close_to_negative_zero_));
     EXPECT_FALSE(m1.Matches(1.0));
     Matcher<RawType> m2 = matcher_maker(close_to_positive_zero_);
     EXPECT_FALSE(m2.Matches(further_from_negative_zero_));
     Matcher<RawType> m3 = matcher_maker(1.0);
     EXPECT_TRUE(m3.Matches(close_to_one_));
     EXPECT_FALSE(m3.Matches(further_from_one_));
     // Test commutativity: matcher_maker(0.0).Matches(1.0) was tested above.
     EXPECT_FALSE(m3.Matches(0.0));
     Matcher<RawType> m4 = matcher_maker(-infinity_);
     EXPECT_TRUE(m4.Matches(-close_to_infinity_));
     Matcher<RawType> m5 = matcher_maker(infinity_);
     EXPECT_TRUE(m5.Matches(close_to_infinity_));
     // This is interesting as the representations of infinity_ and nan1_
     // are only 1 DLP apart.
     EXPECT_FALSE(m5.Matches(nan1_));
     // matcher_maker can produce a Matcher<const RawType&>, which is needed in
     // some cases.
     Matcher<const RawType&> m6 = matcher_maker(0.0);
     EXPECT_TRUE(m6.Matches(-0.0));
     EXPECT_TRUE(m6.Matches(close_to_positive_zero_));
     EXPECT_FALSE(m6.Matches(1.0));
     // matcher_maker can produce a Matcher<RawType&>, which is needed in some
     // cases.
     Matcher<RawType&> m7 = matcher_maker(0.0);
     RawType x = 0.0;
     EXPECT_TRUE(m7.Matches(x));
     x = 0.01f;
     EXPECT_FALSE(m7.Matches(x));
   }
template<typename RawType > void testing::gmock_matchers_test::FloatingPointTest< RawType >::TestMatches (testing::internal::FloatingEqMatcher< RawType >(*)(RawType) matcher_maker) inline protected
Definition at line 2735 of file gmock-matchers_test.cc.
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and max_.
{
     Matcher<RawType> m1 = matcher_maker(0.0);
     EXPECT_TRUE(m1.Matches(-0.0));
     EXPECT_TRUE(m1.Matches(close_to_positive_zero_));
     EXPECT_TRUE(m1.Matches(close_to_negative_zero_));
     EXPECT_FALSE(m1.Matches(1.0));
     Matcher<RawType> m2 = matcher_maker(close_to_positive_zero_);
     EXPECT_FALSE(m2.Matches(further_from_negative_zero_));
     Matcher<RawType> m3 = matcher_maker(1.0);
     EXPECT_TRUE(m3.Matches(close_to_one_));
     EXPECT_FALSE(m3.Matches(further_from_one_));
     // Test commutativity: matcher_maker(0.0).Matches(1.0) was tested above.
     EXPECT_FALSE(m3.Matches(0.0));
     Matcher<RawType> m4 = matcher_maker(-infinity_);
     EXPECT_TRUE(m4.Matches(-close_to_infinity_));
     Matcher<RawType> m5 = matcher_maker(infinity_);
     EXPECT_TRUE(m5.Matches(close_to_infinity_));
     // This is interesting as the representations of infinity_ and nan1_
     // are only 1 DLP apart.
     EXPECT_FALSE(m5.Matches(nan1_));
     // matcher_maker can produce a Matcher<const RawType&>, which is needed in
     // some cases.
     Matcher<const RawType&> m6 = matcher_maker(0.0);
     EXPECT_TRUE(m6.Matches(-0.0));
     EXPECT_TRUE(m6.Matches(close_to_positive_zero_));
     EXPECT_FALSE(m6.Matches(1.0));
     // matcher_maker can produce a Matcher<RawType&>, which is needed in some
     // cases.
     Matcher<RawType&> m7 = matcher_maker(0.0);
     RawType x = 0.0;
     EXPECT_TRUE(m7.Matches(x));
     x = 0.01f;
     EXPECT_FALSE(m7.Matches(x));
   }
template<typename RawType > void testing::gmock_matchers_test::FloatingPointTest< RawType >::TestMatches (testing::internal::FloatingEqMatcher< RawType >(*)(RawType) matcher_maker) inline protected
Definition at line 2735 of file gmock-matchers_test.cc.
References EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
{
     Matcher<RawType> m1 = matcher_maker(0.0);
     EXPECT_TRUE(m1.Matches(-0.0));
     EXPECT_TRUE(m1.Matches(close_to_positive_zero_));
     EXPECT_TRUE(m1.Matches(close_to_negative_zero_));
     EXPECT_FALSE(m1.Matches(1.0));
     Matcher<RawType> m2 = matcher_maker(close_to_positive_zero_);
     EXPECT_FALSE(m2.Matches(further_from_negative_zero_));
     Matcher<RawType> m3 = matcher_maker(1.0);
     EXPECT_TRUE(m3.Matches(close_to_one_));
     EXPECT_FALSE(m3.Matches(further_from_one_));
     // Test commutativity: matcher_maker(0.0).Matches(1.0) was tested above.
     EXPECT_FALSE(m3.Matches(0.0));
     Matcher<RawType> m4 = matcher_maker(-infinity_);
     EXPECT_TRUE(m4.Matches(-close_to_infinity_));
     Matcher<RawType> m5 = matcher_maker(infinity_);
     EXPECT_TRUE(m5.Matches(close_to_infinity_));
     // This is interesting as the representations of infinity_ and nan1_
     // are only 1 DLP apart.
     EXPECT_FALSE(m5.Matches(nan1_));
     // matcher_maker can produce a Matcher<const RawType&>, which is needed in
     // some cases.
     Matcher<const RawType&> m6 = matcher_maker(0.0);
     EXPECT_TRUE(m6.Matches(-0.0));
     EXPECT_TRUE(m6.Matches(close_to_positive_zero_));
     EXPECT_FALSE(m6.Matches(1.0));
     // matcher_maker can produce a Matcher<RawType&>, which is needed in some
     // cases.
     Matcher<RawType&> m7 = matcher_maker(0.0);
     RawType x = 0.0;
     EXPECT_TRUE(m7.Matches(x));
     x = 0.01f;
     EXPECT_FALSE(m7.Matches(x));
   }
template<typename RawType > void testing::gmock_matchers_test::FloatingPointTest< RawType >::TestSize () inline protected
Definition at line 2729 of file gmock-matchers_test.cc.
References EXPECT_EQ.
                   {
     EXPECT_EQ(sizeof(RawType), sizeof(Bits));
   }
template<typename RawType > void testing::gmock_matchers_test::FloatingPointTest< RawType >::TestSize () inline protected
Definition at line 2729 of file gmock-matchers_test.cc.
References EXPECT_EQ.
                   {
     EXPECT_EQ(sizeof(RawType), sizeof(Bits));
   }
template<typename RawType > void testing::gmock_matchers_test::FloatingPointTest< RawType >::TestSize () inline protected
Definition at line 2729 of file gmock-matchers_test.cc.
References EXPECT_EQ.
                   {
     EXPECT_EQ(sizeof(RawType), sizeof(Bits));
   }
Member Data Documentation
template<typename RawType > const RawType testing::gmock_matchers_test::FloatingPointTest< RawType >::close_to_infinity_ protected
Definition at line 2798 of file gmock-matchers_test.cc.
template<typename RawType > const RawType testing::gmock_matchers_test::FloatingPointTest< RawType >::close_to_negative_zero_ protected
Definition at line 2789 of file gmock-matchers_test.cc.
template<typename RawType > const RawType testing::gmock_matchers_test::FloatingPointTest< RawType >::close_to_one_ protected
Definition at line 2793 of file gmock-matchers_test.cc.
template<typename RawType > const RawType testing::gmock_matchers_test::FloatingPointTest< RawType >::close_to_positive_zero_ protected
Definition at line 2788 of file gmock-matchers_test.cc.
template<typename RawType > const RawType testing::gmock_matchers_test::FloatingPointTest< RawType >::further_from_infinity_ protected
Definition at line 2799 of file gmock-matchers_test.cc.
template<typename RawType > const RawType testing::gmock_matchers_test::FloatingPointTest< RawType >::further_from_negative_zero_ protected
Definition at line 2790 of file gmock-matchers_test.cc.
template<typename RawType > const RawType testing::gmock_matchers_test::FloatingPointTest< RawType >::further_from_one_ protected
Definition at line 2794 of file gmock-matchers_test.cc.
template<typename RawType > const RawType testing::gmock_matchers_test::FloatingPointTest< RawType >::infinity_ protected
Definition at line 2797 of file gmock-matchers_test.cc.
template<typename RawType > const Bits testing::gmock_matchers_test::FloatingPointTest< RawType >::infinity_bits_ protected
Definition at line 2785 of file gmock-matchers_test.cc.
template<typename RawType > const RawType testing::gmock_matchers_test::FloatingPointTest< RawType >::max_ protected
Definition at line 2802 of file gmock-matchers_test.cc.
template<typename RawType > const size_t testing::gmock_matchers_test::FloatingPointTest< RawType >::max_ulps_ protected
Definition at line 2781 of file gmock-matchers_test.cc.
template<typename RawType > const RawType testing::gmock_matchers_test::FloatingPointTest< RawType >::nan1_ protected
Definition at line 2805 of file gmock-matchers_test.cc.
template<typename RawType > const RawType testing::gmock_matchers_test::FloatingPointTest< RawType >::nan2_ protected
Definition at line 2806 of file gmock-matchers_test.cc.
template<typename RawType > const Bits testing::gmock_matchers_test::FloatingPointTest< RawType >::one_bits_ protected
Definition at line 2784 of file gmock-matchers_test.cc.
template<typename RawType > const Bits testing::gmock_matchers_test::FloatingPointTest< RawType >::zero_bits_ protected
Definition at line 2783 of file gmock-matchers_test.cc.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-matchers_test.cc