proxygen: folly::TimeseriesHistogram< T, CT, C > Class Template Reference
folly::TimeseriesHistogram< T, CT, C > Class Template Reference
#include <TimeseriesHistogram.h>
Classes
struct AvgFromInterval
struct AvgFromLevel
struct CountFromInterval
struct CountFromLevel
Public Types
using ValueType = T
using ContainerType = C
using Clock = CT
using Duration = typename Clock::duration
using TimePoint = typename Clock::time_point
Public Member Functions
TimeseriesHistogram (ValueType bucketSize, ValueType min, ValueType max, const ContainerType &defaultContainer)
ValueType getBucketSize () const
ValueType getMin () const
ValueType getMax () const
size_t getNumLevels () const
size_t getNumBuckets () const
ValueType getBucketMin (size_t bucketIdx) const
const ContainerType & getBucket (size_t bucketIdx) const
uint64_t count (size_t level) const
uint64_t count (TimePoint start, TimePoint end) const
ValueType sum (size_t level) const
ValueType sum (TimePoint start, TimePoint end) const
template<typename ReturnType = double>
ReturnType avg (size_t level) const
template<typename ReturnType = double>
ReturnType avg (TimePoint start, TimePoint end) const
template<typename ReturnType = double>
ReturnType rate (size_t level) const
template<typename ReturnType = double>
ReturnType rate (TimePoint start, TimePoint end) const
void update (TimePoint now)
void clear ()
void addValue (TimePoint now, const ValueType &value)
void addValue (TimePoint now, const ValueType &value, uint64_t times)
void addValues (TimePoint now, const folly::Histogram< ValueType > &values)
ValueType getPercentileEstimate (double pct, size_t level) const
ValueType getPercentileEstimate (double pct, TimePoint start, TimePoint end) const
size_t getPercentileBucketIdx (double pct, size_t level) const
size_t getPercentileBucketIdx (double pct, TimePoint start, TimePoint end) const
ValueType getPercentileBucketMin (double pct, size_t level) const
ValueType getPercentileBucketMin (double pct, TimePoint start, TimePoint end) const
std::string getString (size_t level) const
std::string getString (TimePoint start, TimePoint end) const
void update (Duration now)
void addValue (Duration now, const ValueType &value)
void addValue (Duration now, const ValueType &value, uint64_t times)
void addValues (Duration now, const folly::Histogram< ValueType > &values)
Private Types
typedef ContainerType Bucket
Private Member Functions
void maybeHandleSingleUniqueValue (const ValueType &value)
void computeAvgData (ValueType *total, uint64_t *nsamples, size_t level) const
void computeAvgData (ValueType *total, uint64_t *nsamples, TimePoint start, TimePoint end) const
void computeRateData (ValueType *total, Duration *elapsed, size_t level) const
void computeRateData (ValueType *total, Duration *elapsed, TimePoint start, TimePoint end) const
Private Attributes
folly::detail::HistogramBuckets< ValueType, ContainerType > buckets_
bool haveNotSeenValue_
bool singleUniqueValue_
ValueType firstValue_
Detailed Description
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>>
class folly::TimeseriesHistogram< T, CT, C >
Definition at line 54 of file TimeseriesHistogram.h.
Member Typedef Documentation
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> typedef ContainerType folly::TimeseriesHistogram< T, CT, C >::Bucket private
Definition at line 323 of file TimeseriesHistogram.h.
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> using folly::TimeseriesHistogram< T, CT, C >::Clock = CT
Definition at line 65 of file TimeseriesHistogram.h.
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> using folly::TimeseriesHistogram< T, CT, C >::ContainerType = C
Definition at line 63 of file TimeseriesHistogram.h.
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> using folly::TimeseriesHistogram< T, CT, C >::Duration = typename Clock::duration
Definition at line 66 of file TimeseriesHistogram.h.
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> using folly::TimeseriesHistogram< T, CT, C >::TimePoint = typename Clock::time_point
Definition at line 67 of file TimeseriesHistogram.h.
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> using folly::TimeseriesHistogram< T, CT, C >::ValueType = T
Definition at line 61 of file TimeseriesHistogram.h.
Constructor & Destructor Documentation
template<typename T , typename CT , typename C > folly::TimeseriesHistogram< T, CT, C >::TimeseriesHistogram (ValueType bucketSize, ValueType min, ValueType max, const ContainerType & defaultContainer)
Definition at line 28 of file TimeseriesHistogram-defs.h.
     : buckets_(bucketSize, min, max, copyMe),
       haveNotSeenValue_(true),
       singleUniqueValue_(false) {}
Member Function Documentation
template<typename T , typename CT , typename C > void folly::TimeseriesHistogram< T, CT, C >::addValue (TimePoint now, const ValueType & value)
Definition at line 38 of file TimeseriesHistogram-defs.h.
References folly::TimeseriesHistogram< T, CT, C >::buckets_, folly::detail::HistogramBuckets< T, BucketT >::getByValue(), and folly::TimeseriesHistogram< T, CT, C >::maybeHandleSingleUniqueValue().
Referenced by folly::TimeseriesHistogram< T, CT, C >::addValue(), folly::TimeseriesHistogram< T, CT, C >::rate(), and TEST().
{
   buckets_.getByValue(value).addValue(now, value);
   maybeHandleSingleUniqueValue(value);
 }
template<typename T , typename CT , typename C > void folly::TimeseriesHistogram< T, CT, C >::addValue (TimePoint now, const ValueType & value, uint64_t times)
Definition at line 46 of file TimeseriesHistogram-defs.h.
References folly::TimeseriesHistogram< T, CT, C >::buckets_, folly::detail::HistogramBuckets< T, BucketT >::getByValue(), and folly::TimeseriesHistogram< T, CT, C >::maybeHandleSingleUniqueValue().
                     {
   buckets_.getByValue(value).addValue(now, value, times);
   maybeHandleSingleUniqueValue(value);
 }
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> void folly::TimeseriesHistogram< T, CT, C >::addValue (Duration now, const ValueType & value) inline
Definition at line 312 of file TimeseriesHistogram.h.
References folly::TimeseriesHistogram< T, CT, C >::addValue().
{
     addValue(TimePoint(now), value);
   }
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> void folly::TimeseriesHistogram< T, CT, C >::addValue (Duration now, const ValueType & value, uint64_t times) inline
Definition at line 315 of file TimeseriesHistogram.h.
References folly::TimeseriesHistogram< T, CT, C >::addValue().
{
     addValue(TimePoint(now), value, times);
   }
template<typename T , typename CT , typename C > void folly::TimeseriesHistogram< T, CT, C >::addValues (TimePoint now, const folly::Histogram< ValueType > & values)
Definition at line 55 of file TimeseriesHistogram-defs.h.
References folly::TimeseriesHistogram< T, CT, C >::buckets_, folly::detail::Bucket< T >::count, folly::Histogram< T >::getBucketByIndex(), folly::TimeseriesHistogram< T, CT, C >::getBucketSize(), folly::Histogram< T >::getBucketSize(), folly::detail::HistogramBuckets< T, BucketT >::getByIndex(), folly::TimeseriesHistogram< T, CT, C >::getMax(), folly::Histogram< T >::getMax(), folly::TimeseriesHistogram< T, CT, C >::getMin(), folly::Histogram< T >::getMin(), folly::TimeseriesHistogram< T, CT, C >::getNumBuckets(), folly::Histogram< T >::getNumBuckets(), folly::TimeseriesHistogram< T, CT, C >::haveNotSeenValue_, folly::TimeseriesHistogram< T, CT, C >::singleUniqueValue_, and folly::detail::Bucket< T >::sum.
Referenced by folly::TimeseriesHistogram< T, CT, C >::addValues(), and folly::TimeseriesHistogram< T, CT, C >::rate().
{
   CHECK_EQ(hist.getMin(), getMin());
   CHECK_EQ(hist.getMax(), getMax());
   CHECK_EQ(hist.getBucketSize(), getBucketSize());
   CHECK_EQ(hist.getNumBuckets(), getNumBuckets());
   for (size_t n = 0; n < hist.getNumBuckets(); ++n) {
     const typename folly::Histogram<ValueType>::Bucket& histBucket =
         hist.getBucketByIndex(n);
     Bucket& myBucket = buckets_.getByIndex(n);
     myBucket.addValueAggregated(now, histBucket.sum, histBucket.count);
   }
   // We don't bother with the singleUniqueValue_ tracking.
   haveNotSeenValue_ = false;
   singleUniqueValue_ = false;
 }
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> void folly::TimeseriesHistogram< T, CT, C >::addValues (Duration now, const folly::Histogram< ValueType > & values) inline
Definition at line 318 of file TimeseriesHistogram.h.
References folly::TimeseriesHistogram< T, CT, C >::addValues().
{
     addValues(TimePoint(now), values);
   }
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> template<typename ReturnType = double> ReturnType folly::TimeseriesHistogram< T, CT, C >::avg (size_t level) const inline
Definition at line 166 of file TimeseriesHistogram.h.
References folly::TimeseriesHistogram< T, CT, C >::computeAvgData(), and uint64_t.
Referenced by TEST().
{
     auto total = ValueType();
     uint64_t nsamples = 0;
     computeAvgData(&total, &nsamples, level);
     return folly::detail::avgHelper<ReturnType>(total, nsamples);
   }
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> template<typename ReturnType = double> ReturnType folly::TimeseriesHistogram< T, CT, C >::avg (TimePoint start, TimePoint end) const inline
Definition at line 175 of file TimeseriesHistogram.h.
References folly::TimeseriesHistogram< T, CT, C >::computeAvgData(), and uint64_t.
{
     auto total = ValueType();
     uint64_t nsamples = 0;
     computeAvgData(&total, &nsamples, start, end);
     return folly::detail::avgHelper<ReturnType>(total, nsamples);
   }
template<typename T , typename CT , typename C > void folly::TimeseriesHistogram< T, CT, C >::clear ()
Definition at line 132 of file TimeseriesHistogram-defs.h.
References folly::TimeseriesHistogram< T, CT, C >::buckets_, folly::detail::HistogramBuckets< T, BucketT >::getByIndex(), folly::detail::HistogramBuckets< T, BucketT >::getNumBuckets(), and i.
Referenced by folly::TimeseriesHistogram< T, CT, C >::rate(), and TEST().
{
   for (size_t i = 0; i < buckets_.getNumBuckets(); i++) {
     buckets_.getByIndex(i).clear();
   }
 }
template<class T , class CT , class C > void folly::TimeseriesHistogram< T, CT, C >::computeAvgData (ValueType * total, uint64_t * nsamples, size_t level) const private
Definition at line 190 of file TimeseriesHistogram-defs.h.
References b, folly::TimeseriesHistogram< T, CT, C >::buckets_, folly::detail::HistogramBuckets< T, BucketT >::getByIndex(), and folly::detail::HistogramBuckets< T, BucketT >::getNumBuckets().
Referenced by folly::TimeseriesHistogram< T, CT, C >::avg().
{
   for (size_t b = 0; b < buckets_.getNumBuckets(); ++b) {
     const auto& levelObj = buckets_.getByIndex(b).getLevel(level);
     *total += levelObj.sum();
     *nsamples += levelObj.count();
   }
 }
template<class T , class CT , class C > void folly::TimeseriesHistogram< T, CT, C >::computeAvgData (ValueType * total, uint64_t * nsamples, TimePoint start, TimePoint end) const private
Definition at line 202 of file TimeseriesHistogram-defs.h.
References b, folly::TimeseriesHistogram< T, CT, C >::buckets_, folly::detail::HistogramBuckets< T, BucketT >::getByIndex(), and folly::detail::HistogramBuckets< T, BucketT >::getNumBuckets().
{
   for (size_t b = 0; b < buckets_.getNumBuckets(); ++b) {
     const auto& levelObj = buckets_.getByIndex(b).getLevel(start);
     *total += levelObj.sum(start, end);
     *nsamples += levelObj.count(start, end);
   }
 }
template<typename T , typename CT , typename C > void folly::TimeseriesHistogram< T, CT, C >::computeRateData (ValueType * total, Duration * elapsed, size_t level) const private
Definition at line 215 of file TimeseriesHistogram-defs.h.
References b, folly::TimeseriesHistogram< T, CT, C >::buckets_, folly::detail::HistogramBuckets< T, BucketT >::getByIndex(), folly::detail::HistogramBuckets< T, BucketT >::getNumBuckets(), and max.
Referenced by folly::TimeseriesHistogram< T, CT, C >::rate().
{
   for (size_t b = 0; b < buckets_.getNumBuckets(); ++b) {
     const auto& levelObj = buckets_.getByIndex(b).getLevel(level);
     *total += levelObj.sum();
     *elapsed = std::max(*elapsed, levelObj.elapsed());
   }
 }
template<class T , class CT , class C > void folly::TimeseriesHistogram< T, CT, C >::computeRateData (ValueType * total, Duration * elapsed, TimePoint start, TimePoint end) const private
Definition at line 227 of file TimeseriesHistogram-defs.h.
References b, folly::TimeseriesHistogram< T, CT, C >::buckets_, folly::detail::HistogramBuckets< T, BucketT >::getByIndex(), folly::detail::HistogramBuckets< T, BucketT >::getNumBuckets(), and max.
{
   for (size_t b = 0; b < buckets_.getNumBuckets(); ++b) {
     const auto& level = buckets_.getByIndex(b).getLevel(start);
     *total += level.sum(start, end);
     *elapsed = std::max(*elapsed, level.elapsed(start, end));
   }
 }
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> uint64_t folly::TimeseriesHistogram< T, CT, C >::count (size_t level) const inline
Definition at line 129 of file TimeseriesHistogram.h.
References b, folly::TimeseriesHistogram< T, CT, C >::buckets_, folly::detail::HistogramBuckets< T, BucketT >::getByIndex(), folly::detail::HistogramBuckets< T, BucketT >::getNumBuckets(), and uint64_t.
Referenced by TEST().
{
     uint64_t total = 0;
     for (size_t b = 0; b < buckets_.getNumBuckets(); ++b) {
       total += buckets_.getByIndex(b).count(level);
     }
     return total;
   }
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> uint64_t folly::TimeseriesHistogram< T, CT, C >::count (TimePoint start, TimePoint end) const inline
Definition at line 138 of file TimeseriesHistogram.h.
References b, folly::TimeseriesHistogram< T, CT, C >::buckets_, folly::detail::HistogramBuckets< T, BucketT >::getByIndex(), folly::detail::HistogramBuckets< T, BucketT >::getNumBuckets(), and uint64_t.
{
     uint64_t total = 0;
     for (size_t b = 0; b < buckets_.getNumBuckets(); ++b) {
       total += buckets_.getByIndex(b).count(start, end);
     }
     return total;
   }
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> const ContainerType& folly::TimeseriesHistogram< T, CT, C >::getBucket (size_t bucketIdx) const inline
Definition at line 124 of file TimeseriesHistogram.h.
References folly::TimeseriesHistogram< T, CT, C >::buckets_, and folly::detail::HistogramBuckets< T, BucketT >::getByIndex().
Referenced by TEST().
{
     return buckets_.getByIndex(bucketIdx);
   }
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> ValueType folly::TimeseriesHistogram< T, CT, C >::getBucketMin (size_t bucketIdx) const inline
Definition at line 119 of file TimeseriesHistogram.h.
References folly::TimeseriesHistogram< T, CT, C >::buckets_, and folly::detail::HistogramBuckets< T, BucketT >::getBucketMin().
Referenced by folly::TimeseriesHistogram< T, CT, C >::getPercentileBucketMin().
{
     return buckets_.getBucketMin(bucketIdx);
   }
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> ValueType folly::TimeseriesHistogram< T, CT, C >::getBucketSize () const inline
Definition at line 90 of file TimeseriesHistogram.h.
References folly::TimeseriesHistogram< T, CT, C >::buckets_, and folly::detail::HistogramBuckets< T, BucketT >::getBucketSize().
Referenced by folly::TimeseriesHistogram< T, CT, C >::addValues(), and TEST().
{
     return buckets_.getBucketSize();
   }
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> ValueType folly::TimeseriesHistogram< T, CT, C >::getMax () const inline
Definition at line 100 of file TimeseriesHistogram.h.
References folly::TimeseriesHistogram< T, CT, C >::buckets_, and folly::detail::HistogramBuckets< T, BucketT >::getMax().
Referenced by folly::TimeseriesHistogram< T, CT, C >::addValues(), and TEST().
{
     return buckets_.getMax();
   }
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> ValueType folly::TimeseriesHistogram< T, CT, C >::getMin () const inline
Definition at line 95 of file TimeseriesHistogram.h.
References folly::TimeseriesHistogram< T, CT, C >::buckets_, and folly::detail::HistogramBuckets< T, BucketT >::getMin().
Referenced by folly::TimeseriesHistogram< T, CT, C >::addValues(), and TEST().
{
     return buckets_.getMin();
   }
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> size_t folly::TimeseriesHistogram< T, CT, C >::getNumBuckets () const inline
Definition at line 110 of file TimeseriesHistogram.h.
References folly::TimeseriesHistogram< T, CT, C >::buckets_, and folly::detail::HistogramBuckets< T, BucketT >::getNumBuckets().
Referenced by folly::TimeseriesHistogram< T, CT, C >::addValues(), and TEST().
{
     return buckets_.getNumBuckets();
   }
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> size_t folly::TimeseriesHistogram< T, CT, C >::getNumLevels () const inline
Definition at line 105 of file TimeseriesHistogram.h.
References folly::TimeseriesHistogram< T, CT, C >::buckets_, and folly::detail::HistogramBuckets< T, BucketT >::getByIndex().
Referenced by TEST().
{
     return buckets_.getByIndex(0).numLevels();
   }
template<typename T , typename CT , typename C > size_t folly::TimeseriesHistogram< T, CT, C >::getPercentileBucketIdx (double pct, size_t level) const
Definition at line 116 of file TimeseriesHistogram-defs.h.
References folly::TimeseriesHistogram< T, CT, C >::buckets_, and folly::detail::HistogramBuckets< T, BucketT >::getPercentileBucketIdx().
Referenced by folly::TimeseriesHistogram< T, CT, C >::getPercentileBucketMin(), and folly::TimeseriesHistogram< T, CT, C >::rate().
{
   return buckets_.getPercentileBucketIdx(pct / 100.0, CountFromLevel(level));
 }
template<typename T , typename CT , typename C > size_t folly::TimeseriesHistogram< T, CT, C >::getPercentileBucketIdx (double pct, TimePoint start, TimePoint end) const
Definition at line 123 of file TimeseriesHistogram-defs.h.
References folly::TimeseriesHistogram< T, CT, C >::buckets_, and folly::detail::HistogramBuckets< T, BucketT >::getPercentileBucketIdx().
{
   return buckets_.getPercentileBucketIdx(
       pct / 100.0, CountFromInterval(start, end));
 }
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> ValueType folly::TimeseriesHistogram< T, CT, C >::getPercentileBucketMin (double pct, size_t level) const inline
Definition at line 280 of file TimeseriesHistogram.h.
References folly::TimeseriesHistogram< T, CT, C >::getBucketMin(), and folly::TimeseriesHistogram< T, CT, C >::getPercentileBucketIdx().
Referenced by TEST().
{
     return getBucketMin(getPercentileBucketIdx(pct, level));
   }
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> ValueType folly::TimeseriesHistogram< T, CT, C >::getPercentileBucketMin (double pct, TimePoint start, TimePoint end) const inline
Definition at line 284 of file TimeseriesHistogram.h.
References folly::TimeseriesHistogram< T, CT, C >::getBucketMin(), folly::TimeseriesHistogram< T, CT, C >::getPercentileBucketIdx(), folly::TimeseriesHistogram< T, CT, C >::getString(), and string.
             {
     return getBucketMin(getPercentileBucketIdx(pct, start, end));
   }
template<typename T , typename CT , typename C > T folly::TimeseriesHistogram< T, CT, C >::getPercentileEstimate (double pct, size_t level) const
Definition at line 90 of file TimeseriesHistogram-defs.h.
References folly::TimeseriesHistogram< T, CT, C >::buckets_, folly::TimeseriesHistogram< T, CT, C >::firstValue_, folly::detail::HistogramBuckets< T, BucketT >::getPercentileEstimate(), and folly::TimeseriesHistogram< T, CT, C >::singleUniqueValue_.
Referenced by folly::TimeseriesHistogram< T, CT, C >::rate(), and TEST().
           {
   if (singleUniqueValue_) {
     return firstValue_;
   }
   return buckets_.getPercentileEstimate(
       pct / 100.0, CountFromLevel(level), AvgFromLevel(level));
 }
template<typename T , typename CT , typename C > T folly::TimeseriesHistogram< T, CT, C >::getPercentileEstimate (double pct, TimePoint start, TimePoint end) const
Definition at line 101 of file TimeseriesHistogram-defs.h.
References folly::TimeseriesHistogram< T, CT, C >::buckets_, folly::TimeseriesHistogram< T, CT, C >::firstValue_, folly::detail::HistogramBuckets< T, BucketT >::getPercentileEstimate(), and folly::TimeseriesHistogram< T, CT, C >::singleUniqueValue_.
{
   if (singleUniqueValue_) {
     return firstValue_;
   }
   return buckets_.getPercentileEstimate(
       pct / 100.0,
       CountFromInterval(start, end),
       AvgFromInterval<T>(start, end));
 }
template<typename T , typename CT , typename C > std::string folly::TimeseriesHistogram< T, CT, C >::getString (size_t level) const
Definition at line 146 of file TimeseriesHistogram-defs.h.
References folly::TimeseriesHistogram< T, CT, C >::buckets_, folly::detail::HistogramBuckets< T, BucketT >::getBucketMin(), folly::detail::HistogramBuckets< T, BucketT >::getByIndex(), folly::detail::HistogramBuckets< T, BucketT >::getNumBuckets(), i, string, and folly::toAppend().
Referenced by folly::TimeseriesHistogram< T, CT, C >::getPercentileBucketMin(), and TEST().
{
   std::string result;
   for (size_t i = 0; i < buckets_.getNumBuckets(); i++) {
     if (i > 0) {
       toAppend(",", &result);
     }
     const ContainerType& cont = buckets_.getByIndex(i);
     toAppend(
         buckets_.getBucketMin(i),
         ":",
         cont.count(level),
         ":",
         cont.template avg<ValueType>(level),
         &result);
   }
   return result;
 }
template<typename T , typename CT , typename C > std::string folly::TimeseriesHistogram< T, CT, C >::getString (TimePoint start, TimePoint end) const
Definition at line 167 of file TimeseriesHistogram-defs.h.
References folly::TimeseriesHistogram< T, CT, C >::buckets_, folly::detail::HistogramBuckets< T, BucketT >::getBucketMin(), folly::detail::HistogramBuckets< T, BucketT >::getByIndex(), folly::detail::HistogramBuckets< T, BucketT >::getNumBuckets(), i, string, and folly::toAppend().
{
   std::string result;
   for (size_t i = 0; i < buckets_.getNumBuckets(); i++) {
     if (i > 0) {
       toAppend(",", &result);
     }
     const ContainerType& cont = buckets_.getByIndex(i);
     toAppend(
         buckets_.getBucketMin(i),
         ":",
         cont.count(start, end),
         ":",
         cont.avg(start, end),
         &result);
   }
   return result;
 }
template<typename T , typename CT , typename C > void folly::TimeseriesHistogram< T, CT, C >::maybeHandleSingleUniqueValue (const ValueType & value) private
Definition at line 76 of file TimeseriesHistogram-defs.h.
References folly::TimeseriesHistogram< T, CT, C >::firstValue_, folly::TimeseriesHistogram< T, CT, C >::haveNotSeenValue_, folly::TimeseriesHistogram< T, CT, C >::singleUniqueValue_, and folly::value().
Referenced by folly::TimeseriesHistogram< T, CT, C >::addValue().
{
   if (haveNotSeenValue_) {
     firstValue_ = value;
     singleUniqueValue_ = true;
     haveNotSeenValue_ = false;
   } else if (singleUniqueValue_) {
     if (value != firstValue_) {
       singleUniqueValue_ = false;
     }
   }
 }
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> template<typename ReturnType = double> ReturnType folly::TimeseriesHistogram< T, CT, C >::rate (size_t level) const inline
Definition at line 187 of file TimeseriesHistogram.h.
References folly::TimeseriesHistogram< T, CT, C >::computeRateData().
Referenced by TEST().
{
     auto total = ValueType();
     Duration elapsed(0);
     computeRateData(&total, &elapsed, level);
     return folly::detail::rateHelper<ReturnType, Duration, Duration>(
         total, elapsed);
   }
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> template<typename ReturnType = double> ReturnType folly::TimeseriesHistogram< T, CT, C >::rate (TimePoint start, TimePoint end) const inline
Definition at line 200 of file TimeseriesHistogram.h.
References folly::TimeseriesHistogram< T, CT, C >::addValue(), folly::TimeseriesHistogram< T, CT, C >::addValues(), folly::TimeseriesHistogram< T, CT, C >::clear(), folly::TimeseriesHistogram< T, CT, C >::computeRateData(), folly::test::end(), folly::TimeseriesHistogram< T, CT, C >::getPercentileBucketIdx(), folly::TimeseriesHistogram< T, CT, C >::getPercentileEstimate(), now(), start, folly::times(), uint64_t, folly::TimeseriesHistogram< T, CT, C >::update(), folly::value(), and values().
{
     auto total = ValueType();
     Duration elapsed(0);
     computeRateData(&total, &elapsed, start, end);
     return folly::detail::rateHelper<ReturnType, Duration, Duration>(
         total, elapsed);
   }
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> ValueType folly::TimeseriesHistogram< T, CT, C >::sum (size_t level) const inline
Definition at line 147 of file TimeseriesHistogram.h.
References b, folly::TimeseriesHistogram< T, CT, C >::buckets_, folly::detail::HistogramBuckets< T, BucketT >::getByIndex(), and folly::detail::HistogramBuckets< T, BucketT >::getNumBuckets().
Referenced by TEST().
{
     ValueType total = ValueType();
     for (size_t b = 0; b < buckets_.getNumBuckets(); ++b) {
       total += buckets_.getByIndex(b).sum(level);
     }
     return total;
   }
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> ValueType folly::TimeseriesHistogram< T, CT, C >::sum (TimePoint start, TimePoint end) const inline
Definition at line 156 of file TimeseriesHistogram.h.
References b, folly::TimeseriesHistogram< T, CT, C >::buckets_, folly::detail::HistogramBuckets< T, BucketT >::getByIndex(), and folly::detail::HistogramBuckets< T, BucketT >::getNumBuckets().
{
     ValueType total = ValueType();
     for (size_t b = 0; b < buckets_.getNumBuckets(); ++b) {
       total += buckets_.getByIndex(b).sum(start, end);
     }
     return total;
   }
template<typename T , typename CT , typename C > void folly::TimeseriesHistogram< T, CT, C >::update (TimePoint now)
Definition at line 139 of file TimeseriesHistogram-defs.h.
References folly::TimeseriesHistogram< T, CT, C >::buckets_, folly::detail::HistogramBuckets< T, BucketT >::getByIndex(), folly::detail::HistogramBuckets< T, BucketT >::getNumBuckets(), and i.
Referenced by folly::TimeseriesHistogram< T, CT, C >::rate(), TEST(), and folly::TimeseriesHistogram< T, CT, C >::update().
{
   for (size_t i = 0; i < buckets_.getNumBuckets(); i++) {
     buckets_.getByIndex(i).update(now);
   }
 }
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> void folly::TimeseriesHistogram< T, CT, C >::update (Duration now) inline
Definition at line 309 of file TimeseriesHistogram.h.
References folly::TimeseriesHistogram< T, CT, C >::update().
{
     update(TimePoint(now));
   }
Member Data Documentation
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> folly::detail::HistogramBuckets<ValueType, ContainerType> folly::TimeseriesHistogram< T, CT, C >::buckets_ private
Definition at line 393 of file TimeseriesHistogram.h.
Referenced by folly::TimeseriesHistogram< T, CT, C >::addValue(), folly::TimeseriesHistogram< T, CT, C >::addValues(), folly::TimeseriesHistogram< T, CT, C >::clear(), folly::TimeseriesHistogram< T, CT, C >::computeAvgData(), folly::TimeseriesHistogram< T, CT, C >::computeRateData(), folly::TimeseriesHistogram< T, CT, C >::count(), folly::TimeseriesHistogram< T, CT, C >::getBucket(), folly::TimeseriesHistogram< T, CT, C >::getBucketMin(), folly::TimeseriesHistogram< T, CT, C >::getBucketSize(), folly::TimeseriesHistogram< T, CT, C >::getMax(), folly::TimeseriesHistogram< T, CT, C >::getMin(), folly::TimeseriesHistogram< T, CT, C >::getNumBuckets(), folly::TimeseriesHistogram< T, CT, C >::getNumLevels(), folly::TimeseriesHistogram< T, CT, C >::getPercentileBucketIdx(), folly::TimeseriesHistogram< T, CT, C >::getPercentileEstimate(), folly::TimeseriesHistogram< T, CT, C >::getString(), folly::TimeseriesHistogram< T, CT, C >::sum(), and folly::TimeseriesHistogram< T, CT, C >::update().
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> ValueType folly::TimeseriesHistogram< T, CT, C >::firstValue_ private
Definition at line 396 of file TimeseriesHistogram.h.
Referenced by folly::TimeseriesHistogram< T, CT, C >::getPercentileEstimate(), and folly::TimeseriesHistogram< T, CT, C >::maybeHandleSingleUniqueValue().
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> bool folly::TimeseriesHistogram< T, CT, C >::haveNotSeenValue_ private
Definition at line 394 of file TimeseriesHistogram.h.
Referenced by folly::TimeseriesHistogram< T, CT, C >::addValues(), and folly::TimeseriesHistogram< T, CT, C >::maybeHandleSingleUniqueValue().
template<class T, class CT = LegacyStatsClock<std::chrono::seconds>, class C = folly::MultiLevelTimeSeries<T, CT>> bool folly::TimeseriesHistogram< T, CT, C >::singleUniqueValue_ private
Definition at line 395 of file TimeseriesHistogram.h.
Referenced by folly::TimeseriesHistogram< T, CT, C >::addValues(), folly::TimeseriesHistogram< T, CT, C >::getPercentileEstimate(), and folly::TimeseriesHistogram< T, CT, C >::maybeHandleSingleUniqueValue().
The documentation for this class was generated from the following files:
proxygen/folly/folly/stats/TimeseriesHistogram.h
proxygen/folly/folly/stats/TimeseriesHistogram-defs.h