proxygen: folly::detail::MPMCPipelineStageImpl< T > Class Template Reference
folly::detail::MPMCPipelineStageImpl< T > Class Template Reference
#include <MPMCPipelineDetail.h>
Public Types
typedef T value_type
Public Member Functions
MPMCPipelineStageImpl (size_t capacity)
MPMCPipelineStageImpl ()
template<class... Args>
void blockingWrite (Args &&...args) noexcept
template<class... Args>
bool write (Args &&...args) noexcept
template<class... Args>
void blockingWriteWithTicket (uint64_t ticket, Args &&...args) noexcept
uint64_t blockingRead (T &elem) noexcept
bool read (T &elem) noexcept
template<class... Args>
bool readAndGetTicket (uint64_t &ticket, T &elem) noexcept
uint64_t writeCount () const noexcept
uint64_t readCount () const noexcept
Private Attributes
MPMCQueue< T > queue_
Friends
template<class U , class... Stages>
class MPMCPipeline
Detailed Description
template<class T>
class folly::detail::MPMCPipelineStageImpl< T >
Wrapper around MPMCQueue (friend) that keeps track of tickets.
Definition at line 55 of file MPMCPipelineDetail.h.
Member Typedef Documentation
template<class T > typedef T folly::detail::MPMCPipelineStageImpl< T >::value_type
Definition at line 57 of file MPMCPipelineDetail.h.
Constructor & Destructor Documentation
template<class T > folly::detail::MPMCPipelineStageImpl< T >::MPMCPipelineStageImpl (size_t capacity) inline
Definition at line 62 of file MPMCPipelineDetail.h.
 : queue_(capacity) {}
template<class T > folly::detail::MPMCPipelineStageImpl< T >::MPMCPipelineStageImpl () inline
Definition at line 63 of file MPMCPipelineDetail.h.
References testing::Args().
 {}
Member Function Documentation
template<class T > uint64_t folly::detail::MPMCPipelineStageImpl< T >::blockingRead (T & elem) inline noexcept
Definition at line 82 of file MPMCPipelineDetail.h.
References ticket, and uint64_t.
{
     uint64_t ticket;
     queue_.blockingReadWithTicket(ticket, elem);
     return ticket;
   }
template<class T > template<class... Args> void folly::detail::MPMCPipelineStageImpl< T >::blockingWrite (Args &&... args) inline noexcept
Definition at line 68 of file MPMCPipelineDetail.h.
References testing::Args().
{
     queue_.blockingWrite(std::forward<Args>(args)...);
   }
template<class T > template<class... Args> void folly::detail::MPMCPipelineStageImpl< T >::blockingWriteWithTicket (uint64_t ticket, Args &&... args) inline noexcept
Definition at line 78 of file MPMCPipelineDetail.h.
{
     queue_.enqueueWithTicket(ticket, std::forward<Args>(args)...);
   }
template<class T > bool folly::detail::MPMCPipelineStageImpl< T >::read (T & elem) inline noexcept
Definition at line 88 of file MPMCPipelineDetail.h.
References testing::Args().
                               { // only use on last stage, won't track ticket
     return queue_.read(elem);
   }
template<class T > template<class... Args> bool folly::detail::MPMCPipelineStageImpl< T >::readAndGetTicket (uint64_t & ticket, T & elem) inline noexcept
Definition at line 93 of file MPMCPipelineDetail.h.
References ticket.
{
     return queue_.readAndGetTicket(ticket, elem);
   }
template<class T > uint64_t folly::detail::MPMCPipelineStageImpl< T >::readCount () const inline noexcept
Definition at line 102 of file MPMCPipelineDetail.h.
{
     return queue_.readCount();
   }
template<class T > template<class... Args> bool folly::detail::MPMCPipelineStageImpl< T >::write (Args &&... args) inline noexcept
Definition at line 73 of file MPMCPipelineDetail.h.
References testing::Args().
{
     return queue_.write(std::forward<Args>(args)...);
   }
template<class T > uint64_t folly::detail::MPMCPipelineStageImpl< T >::writeCount () const inline noexcept
Definition at line 98 of file MPMCPipelineDetail.h.
{
     return queue_.writeCount();
   }
Friends And Related Function Documentation
template<class T > template<class U , class... Stages> friend class MPMCPipeline friend
Definition at line 59 of file MPMCPipelineDetail.h.
Member Data Documentation
template<class T > MPMCQueue<T> folly::detail::MPMCPipelineStageImpl< T >::queue_ private
Definition at line 107 of file MPMCPipelineDetail.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/detail/MPMCPipelineDetail.h