proxygen: folly::ReadMostlyMainPtrDeleter< RefCount > Class Template Reference
folly::ReadMostlyMainPtrDeleter< RefCount > Class Template Reference
#include <ReadMostlySharedPtr.h>
Public Member Functions
~ReadMostlyMainPtrDeleter () noexcept
template<typename T >
void add (ReadMostlyMainPtr< T, RefCount > ptr) noexcept
Private Attributes
std::vector< RefCount * > refCounts_
std::vector< folly::Function< void()> > decrefs_
Detailed Description
template<typename RefCount = DefaultRefCount>
class folly::ReadMostlyMainPtrDeleter< RefCount >
This can be used to destroy multiple ReadMostlyMainPtrs at once.
Definition at line 32 of file ReadMostlySharedPtr.h.
Constructor & Destructor Documentation
template<typename RefCount = DefaultRefCount> folly::ReadMostlyMainPtrDeleter< RefCount >::~ReadMostlyMainPtrDeleter () inline noexcept
Definition at line 372 of file ReadMostlySharedPtr.h.
References folly::detail::ReadMostlySharedPtrCore< T, RefCount >::decref().
{
     RefCount::useGlobal(refCounts_);
     for (auto& decref : decrefs_) {
       decref();
     }
   }
Member Function Documentation
template<typename RefCount = DefaultRefCount> template<typename T > void folly::ReadMostlyMainPtrDeleter< RefCount >::add (ReadMostlyMainPtr< T, RefCount > ptr) inline noexcept
Definition at line 380 of file ReadMostlySharedPtr.h.
References ptr.
Referenced by folly::detail::SingletonHolder< T >::preDestroyInstance(), and TEST_F().
{
     if (!ptr.impl_) {
       return;
     }
     refCounts_.push_back(&ptr.impl_->count_);
     refCounts_.push_back(&ptr.impl_->weakCount_);
     decrefs_.push_back([impl = ptr.impl_] { impl->decref(); });
     ptr.impl_ = nullptr;
   }
Member Data Documentation
template<typename RefCount = DefaultRefCount> std::vector<folly::Function<void()> > folly::ReadMostlyMainPtrDeleter< RefCount >::decrefs_ private
Definition at line 393 of file ReadMostlySharedPtr.h.
template<typename RefCount = DefaultRefCount> std::vector<RefCount*> folly::ReadMostlyMainPtrDeleter< RefCount >::refCounts_ private
Definition at line 392 of file ReadMostlySharedPtr.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/ReadMostlySharedPtr.h