proxygen: folly::symbolizer::FastStackTracePrinter Class Reference
folly::symbolizer::FastStackTracePrinter Class Reference
#include <Symbolizer.h>
Public Member Functions
FastStackTracePrinter (std::unique_ptr< SymbolizePrinter > printer, size_t elfCacheSize=0, size_t symbolCacheSize=kDefaultSymbolCacheSize)
~FastStackTracePrinter ()
FOLLY_NOINLINE void printStackTrace (bool symbolize)
void flush ()
Static Public Attributes
static constexpr size_t kDefaultSymbolCacheSize = 10000
Private Attributes
const std::unique_ptr< ElfCache > elfCache_
const std::unique_ptr< SymbolizePrinter > printer_
Symbolizer symbolizer_
Static Private Attributes
static constexpr size_t kMaxStackTraceDepth = 100
Detailed Description
Use this class to print a stack trace from normal code. It will malloc and won't flush or sync.
These methods are thread safe, through locking. However, they are not signal safe.
Definition at line 397 of file Symbolizer.h.
Constructor & Destructor Documentation
folly::symbolizer::FastStackTracePrinter::FastStackTracePrinter (std::unique_ptr< SymbolizePrinter > printer, size_t elfCacheSize = 0, size_t symbolCacheSize = kDefaultSymbolCacheSize) explicit
Definition at line 463 of file Symbolizer.cpp.
References folly::symbolizer::countLoadedElfFiles(), elfCache_, folly::symbolizer::Dwarf::FULL, max, folly::gen::move, printer_, and symbolizer_.
     : elfCache_(
           elfCacheSize == 0
               ? nullptr
               : new ElfCache{std::max(countLoadedElfFiles(), elfCacheSize)}),
       printer_(std::move(printer)),
       symbolizer_(
           elfCache_ ? elfCache_.get() : defaultElfCache(),
           Dwarf::LocationInfoMode::FULL,
           symbolCacheSize) {}
folly::symbolizer::FastStackTracePrinter::~FastStackTracePrinter ()
Definition at line 477 of file Symbolizer.cpp.
 {}
Member Function Documentation
void folly::symbolizer::FastStackTracePrinter::flush ()
Definition at line 505 of file Symbolizer.cpp.
References addr, and printer_.
{
   printer_->flush();
 }
void folly::symbolizer::FastStackTracePrinter::printStackTrace (bool symbolize)
This is NOINLINE to make sure it shows up in the stack we grab, which makes it easy to skip printing it.
Definition at line 479 of file Symbolizer.cpp.
References folly::symbolizer::FrameArray< N >::addresses, folly::symbolizer::AddressFormatter::format(), folly::symbolizer::FrameArray< N >::frameCount, folly::symbolizer::getStackTraceSafe(), i, printer_, SCOPE_EXIT, folly::symbolizer::Symbolizer::symbolize(), and symbolizer_.
{
   SCOPE_EXIT {
     printer_->flush();
   };
   FrameArray<kMaxStackTraceDepth> addresses;
   if (!getStackTraceSafe(addresses)) {
     printer_->print("(error retrieving stack trace)\n");
   } else if (symbolize) {
     symbolizer_.symbolize(addresses);
     // Skip the top 2 frames:
     // getStackTraceSafe
     // FastStackTracePrinter::printStackTrace (here)
     printer_->println(addresses, 2);
   } else {
     printer_->print("(safe mode, symbolizer not available)\n");
     AddressFormatter formatter;
     for (size_t i = 0; i < addresses.frameCount; ++i) {
       printer_->print(formatter.format(addresses.addresses[i]));
       printer_->print("\n");
     }
   }
 }
Member Data Documentation
const std::unique_ptr<ElfCache> folly::symbolizer::FastStackTracePrinter::elfCache_ private
Definition at line 419 of file Symbolizer.h.
Referenced by FastStackTracePrinter().
constexpr size_t folly::symbolizer::FastStackTracePrinter::kDefaultSymbolCacheSize = 10000 static
Definition at line 399 of file Symbolizer.h.
constexpr size_t folly::symbolizer::FastStackTracePrinter::kMaxStackTraceDepth = 100 static private
Definition at line 417 of file Symbolizer.h.
const std::unique_ptr<SymbolizePrinter> folly::symbolizer::FastStackTracePrinter::printer_ private
Definition at line 420 of file Symbolizer.h.
Referenced by FastStackTracePrinter(), flush(), and printStackTrace().
Symbolizer folly::symbolizer::FastStackTracePrinter::symbolizer_ private
Definition at line 421 of file Symbolizer.h.
Referenced by FastStackTracePrinter(), and printStackTrace().
The documentation for this class was generated from the following files:
proxygen/folly/folly/experimental/symbolizer/Symbolizer.h
proxygen/folly/folly/experimental/symbolizer/Symbolizer.cpp