proxygen: testing::gmock_more_actions_test::VoidNullaryFunctor Class Reference
testing::gmock_more_actions_test::VoidNullaryFunctor Class Reference
Public Member Functions
void operator() ()
void operator() ()
void operator() ()
Detailed Description
Definition at line 86 of file gmock-more-actions_test.cc.
Member Function Documentation
void testing::gmock_more_actions_test::VoidNullaryFunctor::operator() () inline
Definition at line 88 of file gmock-more-actions_test.cc.
 { g_done = true; }
void testing::gmock_more_actions_test::VoidNullaryFunctor::operator() () inline
Definition at line 88 of file gmock-more-actions_test.cc.
References testing::gmock_more_actions_test::ByConstRef(), testing::gmock_more_actions_test::ByNonConstRef(), testing::gmock_more_actions_test::g_double, testing::gmock_more_actions_test::Plus1(), testing::gmock_more_actions_test::ReferencesGlobalDouble(), s, testing::gmock_more_actions_test::Unary(), and testing::gmock_more_actions_test::VoidUnary().
 { g_done = true; }
void testing::gmock_more_actions_test::VoidNullaryFunctor::operator() () inline
Definition at line 88 of file gmock-more-actions_test.cc.
References testing::gmock_more_actions_test::ByConstRef(), testing::gmock_more_actions_test::ByNonConstRef(), testing::gmock_more_actions_test::g_double, testing::gmock_more_actions_test::Plus1(), testing::gmock_more_actions_test::ReferencesGlobalDouble(), s, testing::gmock_more_actions_test::Unary(), and testing::gmock_more_actions_test::VoidUnary().
 { g_done = true; }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-more-actions_test.cc