proxygen: testing::gmock_matchers_test::ReferencesBarOrIsZeroImpl Class Reference
testing::gmock_matchers_test::ReferencesBarOrIsZeroImpl Class Reference
Public Member Functions
template<typename T >
bool MatchAndExplain (const T &x, MatchResultListener *) const
void DescribeTo (ostream *os) const
void DescribeNegationTo (ostream *os) const
template<typename T >
bool MatchAndExplain (const T &x, MatchResultListener *) const
void DescribeTo (ostream *os) const
void DescribeNegationTo (ostream *os) const
template<typename T >
bool MatchAndExplain (const T &x, MatchResultListener *) const
void DescribeTo (ostream *os) const
void DescribeNegationTo (ostream *os) const
Detailed Description
Definition at line 440 of file gmock-matchers_test.cc.
Member Function Documentation
void testing::gmock_matchers_test::ReferencesBarOrIsZeroImpl::DescribeNegationTo (ostream * os) const inline
Definition at line 451 of file gmock-matchers_test.cc.
{
     *os << "doesn't reference g_bar and is not zero";
   }
void testing::gmock_matchers_test::ReferencesBarOrIsZeroImpl::DescribeNegationTo (ostream * os) const inline
Definition at line 451 of file gmock-matchers_test.cc.
References testing::gmock_matchers_test::Describe(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testing::MakePolymorphicMatcher(), testing::internal::MatcherBase< T >::Matches(), testing::gmock_matchers_test::ReferencesBarOrIsZero(), and testing::internal::TEST().
{
     *os << "doesn't reference g_bar and is not zero";
   }
void testing::gmock_matchers_test::ReferencesBarOrIsZeroImpl::DescribeNegationTo (ostream * os) const inline
Definition at line 451 of file gmock-matchers_test.cc.
References testing::gmock_matchers_test::Describe(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testing::MakePolymorphicMatcher(), testing::internal::MatcherBase< T >::Matches(), testing::gmock_matchers_test::ReferencesBarOrIsZero(), and testing::internal::TEST().
{
     *os << "doesn't reference g_bar and is not zero";
   }
void testing::gmock_matchers_test::ReferencesBarOrIsZeroImpl::DescribeTo (ostream * os) const inline
Definition at line 449 of file gmock-matchers_test.cc.
 { *os << "g_bar or zero"; }
void testing::gmock_matchers_test::ReferencesBarOrIsZeroImpl::DescribeTo (ostream * os) const inline
Definition at line 449 of file gmock-matchers_test.cc.
 { *os << "g_bar or zero"; }
void testing::gmock_matchers_test::ReferencesBarOrIsZeroImpl::DescribeTo (ostream * os) const inline
Definition at line 449 of file gmock-matchers_test.cc.
 { *os << "g_bar or zero"; }
template<typename T > bool testing::gmock_matchers_test::ReferencesBarOrIsZeroImpl::MatchAndExplain (const T & x, MatchResultListener *) const inline
Definition at line 443 of file gmock-matchers_test.cc.
References x.
{
     const void* p = &x;
     return p == &g_bar || x == 0;
   }
template<typename T > bool testing::gmock_matchers_test::ReferencesBarOrIsZeroImpl::MatchAndExplain (const T & x, MatchResultListener *) const inline
Definition at line 443 of file gmock-matchers_test.cc.
References x.
{
     const void* p = &x;
     return p == &g_bar || x == 0;
   }
template<typename T > bool testing::gmock_matchers_test::ReferencesBarOrIsZeroImpl::MatchAndExplain (const T & x, MatchResultListener *) const inline
Definition at line 443 of file gmock-matchers_test.cc.
References x.
{
     const void* p = &x;
     return p == &g_bar || x == 0;
   }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-matchers_test.cc