proxygen: FlowControlFilterTest< initSize > Class Template Reference
FlowControlFilterTest< initSize > Class Template Reference
Public Member Functions
void SetUp () override
Public Member Functions inherited from FilterTest
FilterTest ()
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Public Attributes
StrictMock< MockFlowControlCallback > flowCallback_
FlowControlFilter * filter_
int recvWindow_ {initSize}
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Protected Member Functions inherited from testing::Test
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Protected Attributes inherited from FilterTest
MockHTTPCodec * codec_
HTTPCodec::Callback * callbackStart_
HTTPCodecFilterChain chain_
MockHTTPCodecCallback callback_
folly::IOBufQueue writeBuf_ {folly::IOBufQueue::cacheChainLength()}
Detailed Description
template<int initSize>
class FlowControlFilterTest< initSize >
Definition at line 60 of file FilterTests.cpp.
Member Function Documentation
template<int initSize> void FlowControlFilterTest< initSize >::SetUp () inline override virtual
Reimplemented from testing::Test.
Definition at line 62 of file FilterTests.cpp.
References testing::_, folly::IOBufQueue::append(), codec_, EXPECT_CALL, testing::Invoke(), testing::InvokeWithoutArgs(), proxygen::makeBuf(), testing::Return(), and fizz::detail::writeBuf().
{
     EXPECT_CALL(*codec_, getDefaultWindowSize())
       .WillRepeatedly(Return(kInitialCapacity));
     if (initSize > kInitialCapacity) {
       // If the initial size is bigger than the default, a window update
       // will immediately be generated
       EXPECT_CALL(*codec_, generateWindowUpdate(_, 0, initSize -
                                                 kInitialCapacity))
         .WillOnce(InvokeWithoutArgs([this] () {
               writeBuf_.append(makeBuf(10));
               return 10;
             }));
     }
     EXPECT_CALL(*codec_, generateBody(_, _, _, _, _))
         .WillRepeatedly(Invoke([](folly::IOBufQueue& writeBuf,
                                   HTTPCodec::StreamID /*stream*/,
                                   std::shared_ptr<folly::IOBuf> chain,
                                   folly::Optional<uint8_t> /*padding*/,
                                   bool /*eom*/) {
           auto len = chain->computeChainDataLength() + 4;
           writeBuf.append(makeBuf(len));
           return len;
         }));
     EXPECT_CALL(*codec_, isReusable()).WillRepeatedly(Return(true));
     // Construct flow control filter with capacity of 0, which will be
     // overridden to the codec default, which is the minimum
     filter_ = new FlowControlFilter(flowCallback_, writeBuf_, codec_,
                                     initSize);
     chain_.addFilters(std::unique_ptr<FlowControlFilter>(filter_));
   }
Member Data Documentation
template<int initSize> FlowControlFilter* FlowControlFilterTest< initSize >::filter_
Definition at line 95 of file FilterTests.cpp.
template<int initSize> StrictMock<MockFlowControlCallback> FlowControlFilterTest< initSize >::flowCallback_
Definition at line 94 of file FilterTests.cpp.
template<int initSize> int FlowControlFilterTest< initSize >::recvWindow_ {initSize}
Definition at line 96 of file FilterTests.cpp.
The documentation for this class was generated from the following file:
proxygen/lib/http/codec/test/FilterTests.cpp