proxygen: folly::detail::SlidingWindow< BucketT > Class Template Reference
folly::detail::SlidingWindow< BucketT > Class Template Reference
#include <SlidingWindow.h>
Public Member Functions
SlidingWindow (Function< BucketT(void)> fn, size_t numBuckets)
SlidingWindow (SlidingWindow &&rhs)
std::vector< BucketT > get () const
void set (size_t idx, BucketT bucket)
BucketT front () const
void slide (size_t nBuckets)
Private Attributes
Function< BucketT(void)> fn_
std::vector< BucketT > buckets_
size_t curHead_
Detailed Description
template<typename BucketT>
class folly::detail::SlidingWindow< BucketT >
Definition at line 33 of file SlidingWindow.h.
Constructor & Destructor Documentation
template<typename BucketT> folly::detail::SlidingWindow< BucketT >::SlidingWindow (Function< BucketT(void)> fn, size_t numBuckets)
Definition at line 27 of file SlidingWindow-defs.h.
References folly::detail::SlidingWindow< BucketT >::buckets_, folly::detail::SlidingWindow< BucketT >::fn_, and i.
     : fn_(std::move(fn)), curHead_(0) {
   buckets_.reserve(numBuckets);
   for (size_t i = 0; i < numBuckets; ++i) {
     buckets_.push_back(fn_());
   }
   std::reverse(buckets_.begin(), buckets_.end());
 }
template<typename BucketT> folly::detail::SlidingWindow< BucketT >::SlidingWindow (SlidingWindow< BucketT > && rhs)
Definition at line 39 of file SlidingWindow-defs.h.
     : fn_(std::move(rhs.fn_)),
       buckets_(std::move(rhs.buckets_)),
       curHead_(rhs.curHead_) {}
Member Function Documentation
template<typename BucketT > BucketT folly::detail::SlidingWindow< BucketT >::front () const
Definition at line 54 of file SlidingWindow-defs.h.
References folly::detail::SlidingWindow< BucketT >::buckets_, and folly::detail::SlidingWindow< BucketT >::curHead_.
Referenced by folly::detail::BufferedSlidingWindow< DigestT, ClockT >::onNewDigest().
{
   return buckets_[curHead_];
 }
template<typename BucketT > std::vector< BucketT > folly::detail::SlidingWindow< BucketT >::get () const
Definition at line 45 of file SlidingWindow-defs.h.
References folly::detail::SlidingWindow< BucketT >::buckets_, and folly::detail::SlidingWindow< BucketT >::curHead_.
Referenced by folly::detail::BufferedSlidingWindow< DigestT, ClockT >::get().
{
   std::vector<BucketT> buckets;
   buckets.reserve(buckets_.size());
   buckets.insert(buckets.end(), buckets_.begin() + curHead_, buckets_.end());
   buckets.insert(buckets.end(), buckets_.begin(), buckets_.begin() + curHead_);
   return buckets;
 }
template<typename BucketT> void folly::detail::SlidingWindow< BucketT >::set (size_t idx, BucketT bucket)
Definition at line 59 of file SlidingWindow-defs.h.
References folly::detail::SlidingWindow< BucketT >::buckets_, folly::detail::SlidingWindow< BucketT >::curHead_, and folly::gen::move.
Referenced by folly::detail::BufferedSlidingWindow< DigestT, ClockT >::onNewDigest().
{
   if (idx < buckets_.size()) {
     idx = (curHead_ + idx) % buckets_.size();
     buckets_[idx] = std::move(bucket);
   }
 }
template<typename BucketT > void folly::detail::SlidingWindow< BucketT >::slide (size_t nBuckets)
Definition at line 67 of file SlidingWindow-defs.h.
References folly::detail::SlidingWindow< BucketT >::buckets_, folly::detail::SlidingWindow< BucketT >::curHead_, folly::detail::SlidingWindow< BucketT >::fn_, i, and min.
Referenced by folly::detail::BufferedSlidingWindow< DigestT, ClockT >::onNewDigest().
{
   nBuckets = std::min(nBuckets, buckets_.size());
   for (size_t i = 0; i < nBuckets; ++i) {
     if (curHead_ == 0) {
       curHead_ = buckets_.size() - 1;
     } else {
       curHead_--;
     }
     buckets_[curHead_] = fn_();
   }
 }
Member Data Documentation
template<typename BucketT> std::vector<BucketT> folly::detail::SlidingWindow< BucketT >::buckets_ private
Definition at line 53 of file SlidingWindow.h.
Referenced by folly::detail::SlidingWindow< BucketT >::front(), folly::detail::SlidingWindow< BucketT >::get(), folly::detail::SlidingWindow< BucketT >::set(), folly::detail::SlidingWindow< BucketT >::slide(), and folly::detail::SlidingWindow< BucketT >::SlidingWindow().
template<typename BucketT> size_t folly::detail::SlidingWindow< BucketT >::curHead_ private
Definition at line 54 of file SlidingWindow.h.
Referenced by folly::detail::SlidingWindow< BucketT >::front(), folly::detail::SlidingWindow< BucketT >::get(), folly::detail::SlidingWindow< BucketT >::set(), and folly::detail::SlidingWindow< BucketT >::slide().
template<typename BucketT> Function<BucketT(void)> folly::detail::SlidingWindow< BucketT >::fn_ private
Definition at line 52 of file SlidingWindow.h.
Referenced by folly::detail::SlidingWindow< BucketT >::slide(), and folly::detail::SlidingWindow< BucketT >::SlidingWindow().
The documentation for this class was generated from the following files:
proxygen/folly/folly/stats/detail/SlidingWindow.h
proxygen/folly/folly/stats/detail/SlidingWindow-defs.h