proxygen: wangle::FilePersistentCache< K, V, M > Class Template Reference
wangle::FilePersistentCache< K, V, M > Class Template Reference
#include <FilePersistentCache.h>
Public Member Functions
FilePersistentCache (const std::string &file, std::size_t cacheCapacity, std::chrono::seconds syncInterval=std::chrono::duration_cast< std::chrono::seconds >(client::persistence::DEFAULT_CACHE_SYNC_INTERVAL), int nSyncRetries=client::persistence::DEFAULT_CACHE_SYNC_RETRIES)
FilePersistentCache (std::shared_ptr< folly::Executor > executor, const std::string &file, std::size_t cacheCapacity, std::chrono::seconds syncInterval, int nSyncRetries)
~FilePersistentCache () override
folly::Optional< V > get (const K &key) override
void put (const K &key, const V &val) override
bool remove (const K &key) override
void clear (bool clearPersistence=false) override
size_t size () override
void setSyncOnDestroy (bool syncOnDestroy)
Public Member Functions inherited from wangle::PersistentCache< K, V >
virtual ~PersistentCache ()
Private Attributes
LRUPersistentCache< K, V, M >::Ptr cache_
Detailed Description
template<typename K, typename V, typename M = std::mutex>
class wangle::FilePersistentCache< K, V, M >
A PersistentCache implementation that used a regular file for storage. In memory structure fronts the file and the cache operations happen on it. Loading from and syncing to file are hidden from clients. Sync to file happens asynchronously on a separate thread at a configurable interval. Syncs to file on destruction as well.
NOTE NOTE NOTE: Although this class aims to be a cache for arbitrary, it relies heavily on folly::toJson, folly::dynamic and convertTo for serialization and deserialization. So It may not suit your need until true support arbitrary types is written.
Definition at line 40 of file FilePersistentCache.h.
Constructor & Destructor Documentation
template<typename K , typename V , typename M > wangle::FilePersistentCache< K, V, M >::FilePersistentCache (const std::string & file, std::size_t cacheCapacity, std::chrono::seconds syncInterval = std::chrono::duration_cast<std::chrono::seconds>(client::persistence::DEFAULT_CACHE_SYNC_INTERVAL), int nSyncRetries = client::persistence::DEFAULT_CACHE_SYNC_RETRIES)
Definition at line 114 of file FilePersistentCache-inl.h.
     : cache_(std::make_shared<LRUPersistentCache<K, V, M>>(
           cacheCapacity,
           std::chrono::duration_cast<std::chrono::milliseconds>(syncInterval),
           nSyncRetries,
           std::make_unique<FilePersistenceLayer<K, V>>(file))) {}
template<typename K , typename V , typename M > wangle::FilePersistentCache< K, V, M >::FilePersistentCache (std::shared_ptr< folly::Executor > executor, const std::string & file, std::size_t cacheCapacity, std::chrono::seconds syncInterval, int nSyncRetries)
Definition at line 126 of file FilePersistentCache-inl.h.
     : cache_(std::make_shared<LRUPersistentCache<K, V, M>>(
           std::move(executor),
           cacheCapacity,
           std::chrono::duration_cast<std::chrono::milliseconds>(syncInterval),
           nSyncRetries,
           std::make_unique<FilePersistenceLayer<K, V>>(file))) {}
template<typename K, typename V, typename M = std::mutex> wangle::FilePersistentCache< K, V, M >::~FilePersistentCache () inline override
Definition at line 58 of file FilePersistentCache.h.
 {}
Member Function Documentation
template<typename K, typename V, typename M = std::mutex> void wangle::FilePersistentCache< K, V, M >::clear (bool clearPersistence = false) inline override virtual
Empty the contents of the cache
Implements wangle::PersistentCache< K, V >.
Definition at line 75 of file FilePersistentCache.h.
References wangle::FilePersistentCache< K, V, M >::cache_, and wangle::LRUPersistentCache< K, V, MutexT >::clear().
{
     cache_->clear(clearPersistence);
   }
template<typename K, typename V, typename M = std::mutex> folly::Optional<V> wangle::FilePersistentCache< K, V, M >::get (const K & key) inline override virtual
PersistentCache operations
Implements wangle::PersistentCache< K, V >.
Definition at line 63 of file FilePersistentCache.h.
References wangle::FilePersistentCache< K, V, M >::cache_, and wangle::LRUPersistentCache< K, V, MutexT >::get().
Referenced by TYPED_TEST().
{
     return cache_->get(key);
   }
template<typename K, typename V, typename M = std::mutex> void wangle::FilePersistentCache< K, V, M >::put (const K & key, const V & val) inline override virtual
Set a value corresponding to a key
Parameters
key string, the key to set
val string, the value to set
overwrites value if key has a value associated in the cache
Implements wangle::PersistentCache< K, V >.
Definition at line 67 of file FilePersistentCache.h.
References wangle::FilePersistentCache< K, V, M >::cache_, and wangle::LRUPersistentCache< K, V, MutexT >::put().
Referenced by TYPED_TEST().
{
     cache_->put(key, val);
   }
template<typename K, typename V, typename M = std::mutex> bool wangle::FilePersistentCache< K, V, M >::remove (const K & key) inline override virtual
Clear a cache entry associated with a key
Parameters
key string, the key to lookup and clear
Returns
boolean true if any elements are removed, else false
Implements wangle::PersistentCache< K, V >.
Definition at line 71 of file FilePersistentCache.h.
References wangle::FilePersistentCache< K, V, M >::cache_, and wangle::LRUPersistentCache< K, V, MutexT >::remove().
{
     return cache_->remove(key);
   }
template<typename K, typename V, typename M = std::mutex> void wangle::FilePersistentCache< K, V, M >::setSyncOnDestroy (bool syncOnDestroy) inline
Definition at line 83 of file FilePersistentCache.h.
References wangle::FilePersistentCache< K, V, M >::cache_, and wangle::LRUPersistentCache< K, V, MutexT >::setSyncOnDestroy().
{
     cache_->setSyncOnDestroy(syncOnDestroy);
   }
template<typename K, typename V, typename M = std::mutex> size_t wangle::FilePersistentCache< K, V, M >::size () inline override virtual
return the size of the cache
Returns
size_t, the size of the cache
Implements wangle::PersistentCache< K, V >.
Definition at line 79 of file FilePersistentCache.h.
References wangle::FilePersistentCache< K, V, M >::cache_, and wangle::LRUPersistentCache< K, V, MutexT >::size().
Referenced by TYPED_TEST().
{
     return cache_->size();
   }
Member Data Documentation
template<typename K, typename V, typename M = std::mutex> LRUPersistentCache<K, V, M>::Ptr wangle::FilePersistentCache< K, V, M >::cache_ private
Definition at line 88 of file FilePersistentCache.h.
Referenced by wangle::FilePersistentCache< K, V, M >::clear(), wangle::FilePersistentCache< K, V, M >::get(), wangle::FilePersistentCache< K, V, M >::put(), wangle::FilePersistentCache< K, V, M >::remove(), wangle::FilePersistentCache< K, V, M >::setSyncOnDestroy(), and wangle::FilePersistentCache< K, V, M >::size().
The documentation for this class was generated from the following files:
proxygen/wangle/wangle/client/persistence/FilePersistentCache.h
proxygen/wangle/wangle/client/persistence/FilePersistentCache-inl.h