proxygen: testing::internal::PrettyUnitTestResultPrinter Class Reference
testing::internal::PrettyUnitTestResultPrinter Class Reference
Public Member Functions
PrettyUnitTestResultPrinter ()
virtual void OnTestProgramStart (const UnitTest &)
virtual void OnTestIterationStart (const UnitTest &unit_test, int iteration)
virtual void OnEnvironmentsSetUpStart (const UnitTest &unit_test)
virtual void OnEnvironmentsSetUpEnd (const UnitTest &)
virtual void OnTestCaseStart (const TestCase &test_case)
virtual void OnTestStart (const TestInfo &test_info)
virtual void OnTestPartResult (const TestPartResult &result)
virtual void OnTestEnd (const TestInfo &test_info)
virtual void OnTestCaseEnd (const TestCase &test_case)
virtual void OnEnvironmentsTearDownStart (const UnitTest &unit_test)
virtual void OnEnvironmentsTearDownEnd (const UnitTest &)
virtual void OnTestIterationEnd (const UnitTest &unit_test, int iteration)
virtual void OnTestProgramEnd (const UnitTest &)
PrettyUnitTestResultPrinter ()
virtual void OnTestProgramStart (const UnitTest &)
virtual void OnTestIterationStart (const UnitTest &unit_test, int iteration)
virtual void OnEnvironmentsSetUpStart (const UnitTest &unit_test)
virtual void OnEnvironmentsSetUpEnd (const UnitTest &)
virtual void OnTestCaseStart (const TestCase &test_case)
virtual void OnTestStart (const TestInfo &test_info)
virtual void OnTestPartResult (const TestPartResult &result)
virtual void OnTestEnd (const TestInfo &test_info)
virtual void OnTestCaseEnd (const TestCase &test_case)
virtual void OnEnvironmentsTearDownStart (const UnitTest &unit_test)
virtual void OnEnvironmentsTearDownEnd (const UnitTest &)
virtual void OnTestIterationEnd (const UnitTest &unit_test, int iteration)
virtual void OnTestProgramEnd (const UnitTest &)
PrettyUnitTestResultPrinter ()
virtual void OnTestProgramStart (const UnitTest &)
virtual void OnTestIterationStart (const UnitTest &unit_test, int iteration)
virtual void OnEnvironmentsSetUpStart (const UnitTest &unit_test)
virtual void OnEnvironmentsSetUpEnd (const UnitTest &)
virtual void OnTestCaseStart (const TestCase &test_case)
virtual void OnTestStart (const TestInfo &test_info)
virtual void OnTestPartResult (const TestPartResult &result)
virtual void OnTestEnd (const TestInfo &test_info)
virtual void OnTestCaseEnd (const TestCase &test_case)
virtual void OnEnvironmentsTearDownStart (const UnitTest &unit_test)
virtual void OnEnvironmentsTearDownEnd (const UnitTest &)
virtual void OnTestIterationEnd (const UnitTest &unit_test, int iteration)
virtual void OnTestProgramEnd (const UnitTest &)
Public Member Functions inherited from testing::TestEventListener
virtual ~TestEventListener ()
virtual ~TestEventListener ()
virtual ~TestEventListener ()
Static Public Member Functions
static void PrintTestName (const char *test_case, const char *test)
static void PrintTestName (const char *test_case, const char *test)
static void PrintTestName (const char *test_case, const char *test)
Static Private Member Functions
static void PrintFailedTests (const UnitTest &unit_test)
static void PrintFailedTests (const UnitTest &unit_test)
static void PrintFailedTests (const UnitTest &unit_test)
Detailed Description
Definition at line 3029 of file gtest.cc.
Constructor & Destructor Documentation
testing::internal::PrettyUnitTestResultPrinter::PrettyUnitTestResultPrinter () inline
Definition at line 3031 of file gtest.cc.
 {}
testing::internal::PrettyUnitTestResultPrinter::PrettyUnitTestResultPrinter () inline
Definition at line 3031 of file gtest.cc.
 {}
testing::internal::PrettyUnitTestResultPrinter::PrettyUnitTestResultPrinter () inline
Definition at line 3031 of file gtest.cc.
 {}
Member Function Documentation
virtual void testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsSetUpEnd (const UnitTest &) inline virtual
Implements testing::TestEventListener.
Definition at line 3040 of file gtest.cc.
 {}
virtual void testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsSetUpEnd (const UnitTest &) inline virtual
Implements testing::TestEventListener.
Definition at line 3040 of file gtest.cc.
 {}
virtual void testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsSetUpEnd (const UnitTest &) inline virtual
Implements testing::TestEventListener.
Definition at line 3040 of file gtest.cc.
 {}
virtual void testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsSetUpStart (const UnitTest & unit_test) virtual
Implements testing::TestEventListener.
virtual void testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsSetUpStart (const UnitTest & unit_test) virtual
Implements testing::TestEventListener.
void testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsSetUpStart (const UnitTest & unit_test) virtual
Implements testing::TestEventListener.
Definition at line 3091 of file gtest.cc.
References testing::internal::COLOR_GREEN, and testing::internal::ColoredPrintf().
Referenced by OnTestProgramEnd().
{
   ColoredPrintf(COLOR_GREEN,  "[----------] ");
   printf("Global test environment set-up.\n");
   fflush(stdout);
 }
virtual void testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsTearDownEnd (const UnitTest &) inline virtual
Implements testing::TestEventListener.
Definition at line 3047 of file gtest.cc.
 {}
virtual void testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsTearDownEnd (const UnitTest &) inline virtual
Implements testing::TestEventListener.
Definition at line 3047 of file gtest.cc.
 {}
virtual void testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsTearDownEnd (const UnitTest &) inline virtual
Implements testing::TestEventListener.
Definition at line 3047 of file gtest.cc.
 {}
virtual void testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsTearDownStart (const UnitTest & unit_test) virtual
Implements testing::TestEventListener.
void testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsTearDownStart (const UnitTest & unit_test) virtual
Implements testing::TestEventListener.
Definition at line 3161 of file gtest.cc.
References testing::internal::COLOR_GREEN, and testing::internal::ColoredPrintf().
Referenced by OnTestProgramEnd().
{
   ColoredPrintf(COLOR_GREEN,  "[----------] ");
   printf("Global test environment tear-down\n");
   fflush(stdout);
 }
virtual void testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsTearDownStart (const UnitTest & unit_test) virtual
Implements testing::TestEventListener.
virtual void testing::internal::PrettyUnitTestResultPrinter::OnTestCaseEnd (const TestCase & test_case) virtual
Implements testing::TestEventListener.
void testing::internal::PrettyUnitTestResultPrinter::OnTestCaseEnd (const TestCase & test_case) virtual
Implements testing::TestEventListener.
Definition at line 3149 of file gtest.cc.
References testing::internal::COLOR_GREEN, testing::internal::ColoredPrintf(), testing::TestCase::elapsed_time(), testing::FormatCountableNoun(), GTEST_FLAG, testing::TestCase::name(), testing::internal::StreamableToString(), string, and testing::TestCase::test_to_run_count().
Referenced by OnTestProgramEnd().
{
   if (!GTEST_FLAG(print_time)) return;
   const std::string counts =
       FormatCountableNoun(test_case.test_to_run_count(), "test", "tests");
   ColoredPrintf(COLOR_GREEN, "[----------] ");
   printf("%s from %s (%s ms total)\n\n",
          counts.c_str(), test_case.name(),
          internal::StreamableToString(test_case.elapsed_time()).c_str());
   fflush(stdout);
 }
virtual void testing::internal::PrettyUnitTestResultPrinter::OnTestCaseEnd (const TestCase & test_case) virtual
Implements testing::TestEventListener.
virtual void testing::internal::PrettyUnitTestResultPrinter::OnTestCaseStart (const TestCase & test_case) virtual
Implements testing::TestEventListener.
virtual void testing::internal::PrettyUnitTestResultPrinter::OnTestCaseStart (const TestCase & test_case) virtual
Implements testing::TestEventListener.
void testing::internal::PrettyUnitTestResultPrinter::OnTestCaseStart (const TestCase & test_case) virtual
Implements testing::TestEventListener.
Definition at line 3098 of file gtest.cc.
References testing::internal::COLOR_GREEN, testing::internal::ColoredPrintf(), testing::FormatCountableNoun(), testing::TestCase::name(), string, testing::TestCase::test_to_run_count(), and testing::TestCase::type_param().
Referenced by OnTestProgramEnd().
{
   const std::string counts =
       FormatCountableNoun(test_case.test_to_run_count(), "test", "tests");
   ColoredPrintf(COLOR_GREEN, "[----------] ");
   printf("%s from %s", counts.c_str(), test_case.name());
   if (test_case.type_param() == NULL) {
     printf("\n");
   } else {
     printf(", where %s = %s\n", kTypeParamLabel, test_case.type_param());
   }
   fflush(stdout);
 }
void testing::internal::PrettyUnitTestResultPrinter::OnTestEnd (const TestInfo & test_info) virtual
Implements testing::TestEventListener.
Definition at line 3130 of file gtest.cc.
References testing::internal::COLOR_GREEN, testing::internal::COLOR_RED, testing::internal::ColoredPrintf(), testing::TestResult::elapsed_time(), testing::TestResult::Failed(), GTEST_FLAG, testing::TestInfo::name(), testing::TestResult::Passed(), testing::internal::PrintFullTestCommentIfPresent(), testing::TestInfo::result(), testing::internal::StreamableToString(), and testing::TestInfo::test_case_name().
Referenced by OnTestProgramEnd().
{
   if (test_info.result()->Passed()) {
     ColoredPrintf(COLOR_GREEN, "[       OK ] ");
   } else {
     ColoredPrintf(COLOR_RED, "[  FAILED  ] ");
   }
   PrintTestName(test_info.test_case_name(), test_info.name());
   if (test_info.result()->Failed())
     PrintFullTestCommentIfPresent(test_info);
   if (GTEST_FLAG(print_time)) {
     printf(" (%s ms)\n", internal::StreamableToString(
            test_info.result()->elapsed_time()).c_str());
   } else {
     printf("\n");
   }
   fflush(stdout);
 }
virtual void testing::internal::PrettyUnitTestResultPrinter::OnTestEnd (const TestInfo & test_info) virtual
Implements testing::TestEventListener.
virtual void testing::internal::PrettyUnitTestResultPrinter::OnTestEnd (const TestInfo & test_info) virtual
Implements testing::TestEventListener.
virtual void testing::internal::PrettyUnitTestResultPrinter::OnTestIterationEnd (const UnitTest & unit_test, int iteration) virtual
Implements testing::TestEventListener.
void testing::internal::PrettyUnitTestResultPrinter::OnTestIterationEnd (const UnitTest & unit_test, int iteration) virtual
Implements testing::TestEventListener.
Definition at line 3193 of file gtest.cc.
References testing::internal::COLOR_GREEN, testing::internal::COLOR_RED, testing::internal::COLOR_YELLOW, testing::internal::ColoredPrintf(), testing::UnitTest::elapsed_time(), testing::TestCase::failed_test_count(), testing::UnitTest::failed_test_count(), testing::FormatTestCaseCount(), testing::FormatTestCount(), GTEST_FLAG, testing::UnitTest::Passed(), testing::UnitTest::reportable_disabled_test_count(), testing::internal::StreamableToString(), testing::UnitTest::successful_test_count(), testing::UnitTest::test_case_to_run_count(), and testing::UnitTest::test_to_run_count().
Referenced by OnTestProgramEnd().
{
   ColoredPrintf(COLOR_GREEN,  "[==========] ");
   printf("%s from %s ran.",
          FormatTestCount(unit_test.test_to_run_count()).c_str(),
          FormatTestCaseCount(unit_test.test_case_to_run_count()).c_str());
   if (GTEST_FLAG(print_time)) {
     printf(" (%s ms total)",
            internal::StreamableToString(unit_test.elapsed_time()).c_str());
   }
   printf("\n");
   ColoredPrintf(COLOR_GREEN,  "[  PASSED  ] ");
   printf("%s.\n", FormatTestCount(unit_test.successful_test_count()).c_str());
   int num_failures = unit_test.failed_test_count();
   if (!unit_test.Passed()) {
     const int failed_test_count = unit_test.failed_test_count();
     ColoredPrintf(COLOR_RED,  "[  FAILED  ] ");
     printf("%s, listed below:\n", FormatTestCount(failed_test_count).c_str());
     PrintFailedTests(unit_test);
     printf("\n%2d FAILED %s\n", num_failures,
                         num_failures == 1 ? "TEST" : "TESTS");
   }
   int num_disabled = unit_test.reportable_disabled_test_count();
   if (num_disabled && !GTEST_FLAG(also_run_disabled_tests)) {
     if (!num_failures) {
       printf("\n");  // Add a spacer if no FAILURE banner is displayed.
     }
     ColoredPrintf(COLOR_YELLOW,
                   "  YOU HAVE %d DISABLED %s\n\n",
                   num_disabled,
                   num_disabled == 1 ? "TEST" : "TESTS");
   }
   // Ensure that Google Test output is printed before, e.g., heapchecker output.
   fflush(stdout);
 }
virtual void testing::internal::PrettyUnitTestResultPrinter::OnTestIterationEnd (const UnitTest & unit_test, int iteration) virtual
Implements testing::TestEventListener.
virtual void testing::internal::PrettyUnitTestResultPrinter::OnTestIterationStart (const UnitTest & unit_test, int iteration) virtual
Implements testing::TestEventListener.
void testing::internal::PrettyUnitTestResultPrinter::OnTestIterationStart (const UnitTest & unit_test, int iteration) virtual
Implements testing::TestEventListener.
Definition at line 3056 of file gtest.cc.
References testing::internal::COLOR_GREEN, testing::internal::COLOR_YELLOW, testing::internal::ColoredPrintf(), folly::pushmi::operators::filter, testing::FormatTestCaseCount(), testing::FormatTestCount(), testing::internal::posix::GetEnv(), GTEST_FLAG, GTEST_NAME_, testing::internal::Int32FromEnvOrDie(), testing::UnitTest::random_seed(), repeat(), testing::internal::ShouldShard(), testing::UnitTest::test_case_to_run_count(), and testing::UnitTest::test_to_run_count().
Referenced by OnTestProgramEnd().
{
   if (GTEST_FLAG(repeat) != 1)
     printf("\nRepeating all tests (iteration %d) . . .\n\n", iteration + 1);
   const char* const filter = GTEST_FLAG(filter).c_str();
   // Prints the filter if it's not *.  This reminds the user that some
   // tests may be skipped.
   if (!String::CStringEquals(filter, kUniversalFilter)) {
     ColoredPrintf(COLOR_YELLOW,
                   "Note: %s filter = %s\n", GTEST_NAME_, filter);
   }
   if (internal::ShouldShard(kTestTotalShards, kTestShardIndex, false)) {
     const Int32 shard_index = Int32FromEnvOrDie(kTestShardIndex, -1);
     ColoredPrintf(COLOR_YELLOW,
                   "Note: This is test shard %d of %s.\n",
                   static_cast<int>(shard_index) + 1,
                   internal::posix::GetEnv(kTestTotalShards));
   }
   if (GTEST_FLAG(shuffle)) {
     ColoredPrintf(COLOR_YELLOW,
                   "Note: Randomizing tests' orders with a seed of %d .\n",
                   unit_test.random_seed());
   }
   ColoredPrintf(COLOR_GREEN,  "[==========] ");
   printf("Running %s from %s.\n",
          FormatTestCount(unit_test.test_to_run_count()).c_str(),
          FormatTestCaseCount(unit_test.test_case_to_run_count()).c_str());
   fflush(stdout);
 }
virtual void testing::internal::PrettyUnitTestResultPrinter::OnTestIterationStart (const UnitTest & unit_test, int iteration) virtual
Implements testing::TestEventListener.
void testing::internal::PrettyUnitTestResultPrinter::OnTestPartResult (const TestPartResult & result) virtual
Implements testing::TestEventListener.
Definition at line 3119 of file gtest.cc.
References testing::TestPartResult::kSuccess, testing::internal::PrintTestPartResult(), and testing::TestPartResult::type().
Referenced by OnTestProgramEnd().
{
   // If the test part succeeded, we don't need to do anything.
   if (result.type() == TestPartResult::kSuccess)
     return;
   // Print failure message from the assertion (e.g. expected this and got that).
   PrintTestPartResult(result);
   fflush(stdout);
 }
virtual void testing::internal::PrettyUnitTestResultPrinter::OnTestPartResult (const TestPartResult & result) virtual
Implements testing::TestEventListener.
virtual void testing::internal::PrettyUnitTestResultPrinter::OnTestPartResult (const TestPartResult & result) virtual
Implements testing::TestEventListener.
virtual void testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd (const UnitTest &) inline virtual
Implements testing::TestEventListener.
Definition at line 3049 of file gtest.cc.
References testing::internal::COLOR_GREEN, testing::internal::COLOR_RED, testing::internal::ColoredPrintf(), testing::internal::String::CStringEquals(), testing::TestResult::elapsed_time(), testing::TestCase::elapsed_time(), testing::UnitTest::elapsed_time(), testing::TestResult::Failed(), testing::TestCase::failed_test_count(), testing::UnitTest::failed_test_count(), folly::pushmi::operators::filter, testing::FormatCountableNoun(), testing::FormatTestCaseCount(), testing::FormatTestCount(), testing::internal::posix::GetEnv(), testing::UnitTest::GetTestCase(), testing::TestCase::GetTestInfo(), GTEST_FLAG, GTEST_NAME_, i, testing::internal::Int32FromEnvOrDie(), testing::TestPartResult::kSuccess, testing::TestInfo::name(), testing::TestCase::name(), OnEnvironmentsSetUpStart(), OnEnvironmentsTearDownStart(), OnTestCaseEnd(), OnTestCaseStart(), OnTestEnd(), OnTestIterationEnd(), OnTestIterationStart(), OnTestPartResult(), OnTestStart(), testing::TestResult::Passed(), testing::UnitTest::Passed(), PrintFailedTests(), testing::internal::PrintFullTestCommentIfPresent(), testing::internal::PrintTestPartResult(), testing::UnitTest::random_seed(), repeat(), testing::UnitTest::reportable_disabled_test_count(), testing::TestInfo::result(), testing::TestInfo::should_run(), testing::TestCase::should_run(), testing::internal::ShouldShard(), testing::internal::StreamableToString(), string, testing::UnitTest::successful_test_count(), testing::TestInfo::test_case_name(), testing::UnitTest::test_case_to_run_count(), testing::TestCase::test_to_run_count(), testing::UnitTest::test_to_run_count(), testing::UnitTest::total_test_case_count(), testing::TestCase::total_test_count(), testing::TestPartResult::type(), and testing::TestCase::type_param().
 {}
virtual void testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd (const UnitTest &) inline virtual
Implements testing::TestEventListener.
Definition at line 3049 of file gtest.cc.
References testing::internal::COLOR_GREEN, testing::internal::COLOR_RED, testing::internal::ColoredPrintf(), testing::internal::String::CStringEquals(), testing::TestResult::elapsed_time(), testing::TestCase::elapsed_time(), testing::UnitTest::elapsed_time(), testing::TestResult::Failed(), testing::TestCase::failed_test_count(), testing::UnitTest::failed_test_count(), folly::pushmi::operators::filter, testing::FormatCountableNoun(), testing::FormatTestCaseCount(), testing::FormatTestCount(), testing::internal::posix::GetEnv(), testing::UnitTest::GetTestCase(), testing::TestCase::GetTestInfo(), GTEST_FLAG, GTEST_NAME_, i, testing::internal::Int32FromEnvOrDie(), testing::TestPartResult::kSuccess, testing::TestInfo::name(), testing::TestCase::name(), OnEnvironmentsSetUpStart(), OnEnvironmentsTearDownStart(), OnTestCaseEnd(), OnTestCaseStart(), OnTestEnd(), OnTestIterationEnd(), OnTestIterationStart(), OnTestPartResult(), OnTestStart(), testing::TestResult::Passed(), testing::UnitTest::Passed(), PrintFailedTests(), testing::internal::PrintFullTestCommentIfPresent(), testing::internal::PrintTestPartResult(), testing::UnitTest::random_seed(), repeat(), testing::UnitTest::reportable_disabled_test_count(), testing::TestInfo::result(), testing::TestInfo::should_run(), testing::TestCase::should_run(), testing::internal::ShouldShard(), testing::internal::StreamableToString(), string, testing::UnitTest::successful_test_count(), testing::TestInfo::test_case_name(), testing::UnitTest::test_case_to_run_count(), testing::TestCase::test_to_run_count(), testing::UnitTest::test_to_run_count(), testing::UnitTest::total_test_case_count(), testing::TestCase::total_test_count(), testing::TestPartResult::type(), and testing::TestCase::type_param().
 {}
virtual void testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd (const UnitTest &) inline virtual
Implements testing::TestEventListener.
Definition at line 3049 of file gtest.cc.
 {}
virtual void testing::internal::PrettyUnitTestResultPrinter::OnTestProgramStart (const UnitTest &) inline virtual
Implements testing::TestEventListener.
Definition at line 3037 of file gtest.cc.
 {}
virtual void testing::internal::PrettyUnitTestResultPrinter::OnTestProgramStart (const UnitTest &) inline virtual
Implements testing::TestEventListener.
Definition at line 3037 of file gtest.cc.
 {}
virtual void testing::internal::PrettyUnitTestResultPrinter::OnTestProgramStart (const UnitTest &) inline virtual
Implements testing::TestEventListener.
Definition at line 3037 of file gtest.cc.
 {}
void testing::internal::PrettyUnitTestResultPrinter::OnTestStart (const TestInfo & test_info) virtual
Implements testing::TestEventListener.
Definition at line 3111 of file gtest.cc.
References testing::internal::COLOR_GREEN, testing::internal::ColoredPrintf(), testing::TestInfo::name(), and testing::TestInfo::test_case_name().
Referenced by OnTestProgramEnd().
{
   ColoredPrintf(COLOR_GREEN,  "[ RUN      ] ");
   PrintTestName(test_info.test_case_name(), test_info.name());
   printf("\n");
   fflush(stdout);
 }
virtual void testing::internal::PrettyUnitTestResultPrinter::OnTestStart (const TestInfo & test_info) virtual
Implements testing::TestEventListener.
virtual void testing::internal::PrettyUnitTestResultPrinter::OnTestStart (const TestInfo & test_info) virtual
Implements testing::TestEventListener.
void testing::internal::PrettyUnitTestResultPrinter::PrintFailedTests (const UnitTest & unit_test) static private
Definition at line 3169 of file gtest.cc.
References testing::internal::COLOR_RED, testing::internal::ColoredPrintf(), testing::TestCase::failed_test_count(), testing::UnitTest::failed_test_count(), testing::UnitTest::GetTestCase(), testing::TestCase::GetTestInfo(), i, testing::TestInfo::name(), testing::TestCase::name(), testing::TestResult::Passed(), testing::internal::PrintFullTestCommentIfPresent(), testing::TestInfo::result(), testing::TestInfo::should_run(), testing::TestCase::should_run(), testing::UnitTest::total_test_case_count(), and testing::TestCase::total_test_count().
Referenced by OnTestProgramEnd().
{
   const int failed_test_count = unit_test.failed_test_count();
   if (failed_test_count == 0) {
     return;
   }
   for (int i = 0; i < unit_test.total_test_case_count(); ++i) {
     const TestCase& test_case = *unit_test.GetTestCase(i);
     if (!test_case.should_run() || (test_case.failed_test_count() == 0)) {
       continue;
     }
     for (int j = 0; j < test_case.total_test_count(); ++j) {
       const TestInfo& test_info = *test_case.GetTestInfo(j);
       if (!test_info.should_run() || test_info.result()->Passed()) {
         continue;
       }
       ColoredPrintf(COLOR_RED, "[  FAILED  ] ");
       printf("%s.%s", test_case.name(), test_info.name());
       PrintFullTestCommentIfPresent(test_info);
       printf("\n");
     }
   }
 }
static void testing::internal::PrettyUnitTestResultPrinter::PrintFailedTests (const UnitTest & unit_test) static private
static void testing::internal::PrettyUnitTestResultPrinter::PrintFailedTests (const UnitTest & unit_test) static private
static void testing::internal::PrettyUnitTestResultPrinter::PrintTestName (const char * test_case, const char * test) inline static
Definition at line 3032 of file gtest.cc.
{
     printf("%s.%s", test_case, test);
   }
static void testing::internal::PrettyUnitTestResultPrinter::PrintTestName (const char * test_case, const char * test) inline static
Definition at line 3032 of file gtest.cc.
{
     printf("%s.%s", test_case, test);
   }
static void testing::internal::PrettyUnitTestResultPrinter::PrintTestName (const char * test_case, const char * test) inline static
Definition at line 3032 of file gtest.cc.
{
     printf("%s.%s", test_case, test);
   }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest.cc