proxygen: TestPipelineFactory Class Reference
TestPipelineFactory Class Reference
Public Member Functions
BytesPipeline::Ptr newPipeline (std::shared_ptr< AsyncTransportWrapper >) override
BytesPipeline::Ptr newPipeline (std::shared_ptr< AsyncTransportWrapper >) override
Public Member Functions inherited from wangle::PipelineFactory< BytesPipeline >
virtual BytesPipeline::Ptr newPipeline (std::shared_ptr< folly::AsyncUDPSocket >, const folly::SocketAddress &)
virtual ~PipelineFactory ()=default
Public Attributes
std::atomic< int > pipelines {0}
std::atomic< int > pipelines_ {0}
Detailed Description
Definition at line 54 of file BootstrapTest.cpp.
Member Function Documentation
BytesPipeline::Ptr TestPipelineFactory::newPipeline (std::shared_ptr< AsyncTransportWrapper >) inline override virtual
Implements wangle::PipelineFactory< BytesPipeline >.
Reimplemented in CustomPipelineFactory.
Definition at line 46 of file ObservingClientPipelineTest.cpp.
References wangle::Pipeline< R, W >::create().
{
     pipelines_++;
     auto pipeline = BytesPipeline::create();
     pipeline->addBack(new BytesToBytesHandler());
     pipeline->finalize();
     return pipeline;
   }
BytesPipeline::Ptr TestPipelineFactory::newPipeline (std::shared_ptr< AsyncTransportWrapper >) inline override virtual
Implements wangle::PipelineFactory< BytesPipeline >.
Reimplemented in CustomPipelineFactory.
Definition at line 56 of file BootstrapTest.cpp.
References wangle::Pipeline< R, W >::create().
Referenced by CustomPipelineFactory::newPipeline().
{
     pipelines++;
     auto pipeline = BytesPipeline::create();
     pipeline->addBack(new BytesToBytesHandler());
     pipeline->finalize();
     return pipeline;
   }
Member Data Documentation
std::atomic<int> TestPipelineFactory::pipelines {0}
Definition at line 64 of file BootstrapTest.cpp.
std::atomic<int> TestPipelineFactory::pipelines_ {0}
Definition at line 54 of file ObservingClientPipelineTest.cpp.
The documentation for this class was generated from the following files:
proxygen/wangle/wangle/bootstrap/test/BootstrapTest.cpp
proxygen/wangle/wangle/channel/broadcast/test/ObservingClientPipelineTest.cpp