proxygen: folly::detail::ThreadCachedInts< Tag >::Integer Class Reference
folly::detail::ThreadCachedInts< Tag >::Integer Class Reference
Public Member Functions
constexpr Integer (ThreadCachedInts *ints) noexcept
~Integer () noexcept
Public Attributes
ThreadCachedInts * ints_
std::atomic< int64_t > inc_ [2]
std::atomic< int64_t > dec_ [2]
Integer *& cache_
Detailed Description
template<typename Tag>
class folly::detail::ThreadCachedInts< Tag >::Integer
Definition at line 43 of file ThreadCachedInts.h.
Constructor & Destructor Documentation
template<typename Tag> constexpr folly::detail::ThreadCachedInts< Tag >::Integer::Integer (ThreadCachedInts * ints) inline noexcept
Definition at line 46 of file ThreadCachedInts.h.
References folly::detail::ThreadCachedInts< Tag >::Integer::cache_, and folly::detail::ThreadCachedInts< Tag >::Integer::dec_.
Referenced by folly::detail::ThreadCachedInts< folly::detail::folly::detail::Tag >::init().
         : ints_(ints), inc_{}, dec_{}, cache_(ints->int_cache_) {}
template<typename Tag> folly::detail::ThreadCachedInts< Tag >::Integer::~Integer () inline noexcept
Definition at line 51 of file ThreadCachedInts.h.
References folly::asymmetricLightBarrier(), folly::detail::futexWake(), deadlock::load(), folly::detail::ThreadCachedInts< Tag >::orphan_dec_, folly::detail::ThreadCachedInts< Tag >::orphan_inc_, and folly::detail::ThreadCachedInts< Tag >::waiting_.
{
       // Increment counts must be set before decrement counts
       ints_->orphan_inc_[0].fetch_add(
           inc_[0].load(std::memory_order_relaxed), std::memory_order_relaxed);
       ints_->orphan_inc_[1].fetch_add(
           inc_[1].load(std::memory_order_relaxed), std::memory_order_relaxed);
       folly::asymmetricLightBarrier(); // B
       ints_->orphan_dec_[0].fetch_add(
           dec_[0].load(std::memory_order_relaxed), std::memory_order_relaxed);
       ints_->orphan_dec_[1].fetch_add(
           dec_[1].load(std::memory_order_relaxed), std::memory_order_relaxed);
       ints_->waiting_.store(0, std::memory_order_release);
       detail::futexWake(&ints_->waiting_);
       // reset the cache_ on destructor so we can handle the delete/recreate
       cache_ = nullptr;
     }
Member Data Documentation
template<typename Tag> Integer*& folly::detail::ThreadCachedInts< Tag >::Integer::cache_
Definition at line 50 of file ThreadCachedInts.h.
Referenced by folly::detail::ThreadCachedInts< Tag >::Integer::Integer().
template<typename Tag> std::atomic<int64_t> folly::detail::ThreadCachedInts< Tag >::Integer::dec_[2]
Definition at line 49 of file ThreadCachedInts.h.
Referenced by folly::detail::ThreadCachedInts< Tag >::Integer::Integer().
template<typename Tag> std::atomic<int64_t> folly::detail::ThreadCachedInts< Tag >::Integer::inc_[2]
Definition at line 48 of file ThreadCachedInts.h.
template<typename Tag> ThreadCachedInts* folly::detail::ThreadCachedInts< Tag >::Integer::ints_
Definition at line 45 of file ThreadCachedInts.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/synchronization/detail/ThreadCachedInts.h