proxygen: fizz::server::AsyncFizzServerT< SM > Class Template Reference
fizz::server::AsyncFizzServerT< SM > Class Template Reference
#include <AsyncFizzServer.h>
Classes
class ActionMoveVisitor
class HandshakeCallback
Public Types
using UniquePtr = std::unique_ptr< AsyncFizzServerT, folly::DelayedDestruction::Destructor >
Public Types inherited from fizz::AsyncFizzBase
using UniquePtr = std::unique_ptr< AsyncFizzBase, folly::DelayedDestruction::Destructor >
using ReadCallback = folly::AsyncTransportWrapper::ReadCallback
Public Types inherited from folly::AsyncTransportWrapper
using UniquePtr = std::unique_ptr< AsyncTransportWrapper, Destructor >
using ReadCallback = AsyncReader::ReadCallback
using WriteCallback = AsyncWriter::WriteCallback
Public Types inherited from folly::AsyncTransport
typedef std::unique_ptr< AsyncTransport, Destructor > UniquePtr
Public Member Functions
AsyncFizzServerT (folly::AsyncTransportWrapper::UniquePtr socket, const std::shared_ptr< FizzServerContext > &fizzContext, const std::shared_ptr< ServerExtensions > &extensions=nullptr)
virtual void accept (HandshakeCallback *callback)
bool good () const override
bool readable () const override
bool connecting () const override
bool error () const override
bool isDetachable () const override
void attachEventBase (folly::EventBase *evb) override
folly::ssl::X509UniquePtr getPeerCert () const override
const X509 * getSelfCert () const override
bool isReplaySafe () const override
void setReplaySafetyCallback (folly::AsyncTransport::ReplaySafetyCallback *callback) override
std::string getApplicationProtocol () const noexceptoverride
void close () override
void closeWithReset () override
void closeNow () override
const State & getState () const
folly::Optional< CipherSuite > getCipher () const override
std::vector< SignatureScheme > getSupportedSigSchemes () const override
Buf getEkm (folly::StringPiece label, const Buf &hashedContext, uint16_t length) const override
virtual Buf getEarlyEkm (folly::StringPiece label, const Buf &hashedContext, uint16_t length) const
const Cert * getPeerCertificate () const override
const Cert * getSelfCertificate () const override
Public Member Functions inherited from fizz::AsyncFizzBase
AsyncFizzBase (folly::AsyncTransportWrapper::UniquePtr transport)
~AsyncFizzBase () override
ReadCallback * getReadCallback () const override
void setReadCB (ReadCallback *callback) override
void writeChain (folly::AsyncTransportWrapper::WriteCallback *callback, std::unique_ptr< folly::IOBuf > &&buf, folly::WriteFlags flags=folly::WriteFlags::NONE) override
size_t getAppBytesWritten () const override
size_t getAppBytesReceived () const override
void destroy () override
std::string getSecurityProtocol () const override
void attachTimeoutManager (folly::TimeoutManager *manager)
void detachTimeoutManager ()
void detachEventBase () override
Public Member Functions inherited from folly::WriteChainAsyncTransportWrapper< folly::AsyncTransportWrapper >
void write (folly::AsyncTransportWrapper::WriteCallback *callback, const void *buf, size_t bytes, folly::WriteFlags flags=folly::WriteFlags::NONE) override
void writev (folly::AsyncTransportWrapper::WriteCallback *callback, const iovec *vec, size_t count, folly::WriteFlags flags=folly::WriteFlags::NONE) override
Public Member Functions inherited from folly::DecoratedAsyncTransportWrapper< folly::AsyncTransportWrapper >
DecoratedAsyncTransportWrapper (typename folly::AsyncTransportWrapper::UniquePtr transport)
const AsyncTransportWrapper * getWrappedTransport () const override
ReadCallback * getReadCallback () const override
void setReadCB (folly::AsyncTransportWrapper::ReadCallback *callback) override
folly::EventBase * getEventBase () const override
void attachEventBase (folly::EventBase *eventBase) override
void close () override
void closeNow () override
void closeWithReset () override
bool connecting () const override
void detachEventBase () override
bool error () const override
size_t getAppBytesReceived () const override
size_t getAppBytesWritten () const override
void getLocalAddress (folly::SocketAddress *address) const override
void getPeerAddress (folly::SocketAddress *address) const override
folly::ssl::X509UniquePtr getPeerCert () const override
size_t getRawBytesReceived () const override
size_t getRawBytesWritten () const override
uint32_t getSendTimeout () const override
bool good () const override
bool isDetachable () const override
bool isEorTrackingEnabled () const override
bool readable () const override
bool writable () const override
void setEorTracking (bool track) override
void setSendTimeout (uint32_t timeoutInMs) override
void shutdownWrite () override
void shutdownWriteNow () override
std::string getApplicationProtocol () const noexceptoverride
std::string getSecurityProtocol () const override
bool isReplaySafe () const override
void setReplaySafetyCallback (folly::AsyncTransport::ReplaySafetyCallback *callback) override
const AsyncTransportCertificate * getPeerCertificate () const override
const AsyncTransportCertificate * getSelfCertificate () const override
Public Member Functions inherited from folly::AsyncTransportWrapper
template<class T >
const T * getUnderlyingTransport () const
template<class T >
T * getUnderlyingTransport ()
Public Member Functions inherited from folly::AsyncTransport
virtual bool isPending () const
SocketAddress getLocalAddress () const
void getAddress (SocketAddress *address) const override
SocketAddress getPeerAddress () const
Public Member Functions inherited from folly::DelayedDestruction
bool getDestroyPending () const
Public Member Functions inherited from folly::DelayedDestructionBase
virtual ~DelayedDestructionBase ()=default
Public Member Functions inherited from folly::AsyncSocketBase
virtual ~AsyncSocketBase ()=default
Protected Member Functions
void writeAppData (folly::AsyncTransportWrapper::WriteCallback *callback, std::unique_ptr< folly::IOBuf > &&buf, folly::WriteFlags flags=folly::WriteFlags::NONE) override
void transportError (const folly::AsyncSocketException &ex) override
void transportDataAvailable () override
Protected Member Functions inherited from fizz::AsyncFizzBase
virtual void startTransportReads ()
virtual void startHandshakeTimeout (std::chrono::milliseconds)
virtual void cancelHandshakeTimeout ()
virtual void deliverAppData (std::unique_ptr< folly::IOBuf > buf)
virtual void deliverError (const folly::AsyncSocketException &ex, bool closeTransport=true)
Protected Member Functions inherited from folly::DecoratedAsyncTransportWrapper< folly::AsyncTransportWrapper >
~DecoratedAsyncTransportWrapper () override
Protected Member Functions inherited from folly::AsyncTransport
~AsyncTransport () override=default
Protected Member Functions inherited from folly::DelayedDestruction
~DelayedDestruction () override=default
DelayedDestruction ()
Protected Member Functions inherited from folly::DelayedDestructionBase
DelayedDestructionBase ()
uint32_t getDestructorGuardCount () const
Protected Member Functions inherited from folly::AsyncReader
virtual ~AsyncReader ()=default
Protected Member Functions inherited from folly::AsyncWriter
virtual ~AsyncWriter ()=default
Protected Member Functions inherited from folly::AsyncWriter::WriteCallback
virtual ~WriteCallback ()=default
Private Member Functions
void deliverAllErrors (const folly::AsyncSocketException &ex, bool closeTransport=true)
void deliverHandshakeError (folly::exception_wrapper ex)
Private Attributes
HandshakeCallback * handshakeCallback_ {nullptr}
std::shared_ptr< FizzServerContext > fizzContext_
std::shared_ptr< ServerExtensions > extensions_
State state_
ActionMoveVisitor visitor_
FizzServer< ActionMoveVisitor, SM > fizzServer_
Additional Inherited Members
Protected Attributes inherited from fizz::AsyncFizzBase
folly::IOBufQueue transportReadBuf_ {folly::IOBufQueue::cacheChainLength()}
Protected Attributes inherited from folly::DecoratedAsyncTransportWrapper< folly::AsyncTransportWrapper >
folly::AsyncTransportWrapper::UniquePtr transport_
Detailed Description
template<typename SM>
class fizz::server::AsyncFizzServerT< SM >
Definition at line 21 of file AsyncFizzServer.h.
Member Typedef Documentation
template<typename SM> using fizz::server::AsyncFizzServerT< SM >::UniquePtr = std::unique_ptr<AsyncFizzServerT, folly::DelayedDestruction::Destructor>
Definition at line 38 of file AsyncFizzServer.h.
Constructor & Destructor Documentation
template<typename SM > fizz::server::AsyncFizzServerT< SM >::AsyncFizzServerT (folly::AsyncTransportWrapper::UniquePtr socket, const std::shared_ptr< FizzServerContext > & fizzContext, const std::shared_ptr< ServerExtensions > & extensions = nullptr)
Definition at line 15 of file AsyncFizzServer-inl.h.
     : AsyncFizzBase(std::move(socket)),
       fizzContext_(fizzContext),
       extensions_(extensions),
       visitor_(*this),
       fizzServer_(state_, transportReadBuf_, visitor_, this) {}
Member Function Documentation
template<typename SM > void fizz::server::AsyncFizzServerT< SM >::accept (HandshakeCallback * callback) virtual
Definition at line 26 of file AsyncFizzServer-inl.h.
References fizz::server::AsyncFizzServerT< SM >::extensions_, fizz::server::AsyncFizzServerT< SM >::fizzContext_, fizz::server::AsyncFizzServerT< SM >::fizzServer_, fizz::server::AsyncFizzServerT< SM >::handshakeCallback_, fizz::AsyncFizzBase::startTransportReads(), and folly::DecoratedAsyncTransportWrapper< folly::AsyncTransportWrapper >::transport_.
{
   handshakeCallback_ = callback;
   fizzServer_.accept(transport_->getEventBase(), fizzContext_, extensions_);
   startTransportReads();
 }
template<typename SM > void fizz::server::AsyncFizzServerT< SM >::attachEventBase (folly::EventBase * eventBase) override virtual
Attach the transport to a EventBase.
This may only be called if the transport is not currently attached to a EventBase (by an earlier call to detachEventBase()).
This method must be invoked in the EventBase's thread.
Reimplemented from fizz::AsyncFizzBase.
Definition at line 59 of file AsyncFizzServer-inl.h.
References fizz::AsyncFizzBase::attachEventBase(), fizz::server::State::executor(), and fizz::server::AsyncFizzServerT< SM >::state_.
{
   state_.executor() = evb;
   AsyncFizzBase::attachEventBase(evb);
 }
template<typename SM > void fizz::server::AsyncFizzServerT< SM >::close () override virtual
Close the transport.
This gracefully closes the transport, waiting for all pending write requests to complete before actually closing the underlying transport.
If a read callback is set, readEOF() will be called immediately. If there are outstanding write requests, the close will be delayed until all remaining writes have completed. No new writes may be started after close() has been called.
Implements folly::AsyncTransport.
Definition at line 116 of file AsyncFizzServer-inl.h.
References fizz::server::AsyncFizzServerT< SM >::deliverAllErrors(), folly::AsyncSocketException::END_OF_FILE, fizz::server::AsyncFizzServerT< SM >::fizzServer_, and folly::DecoratedAsyncTransportWrapper< folly::AsyncTransportWrapper >::transport_.
{
   if (transport_->good()) {
     fizzServer_.appClose();
   } else {
     DelayedDestruction::DestructorGuard dg(this);
     folly::AsyncSocketException ase(
         folly::AsyncSocketException::END_OF_FILE, "socket closed locally");
     deliverAllErrors(ase, false);
     transport_->close();
   }
 }
template<typename SM > void fizz::server::AsyncFizzServerT< SM >::closeNow () override virtual
Close the transport immediately.
This closes the transport immediately, dropping any outstanding data waiting to be written.
If a read callback is set, readEOF() will be called immediately. If there are outstanding write requests, these requests will be aborted and writeError() will be invoked immediately on all outstanding write callbacks.
Implements folly::AsyncTransport.
Definition at line 141 of file AsyncFizzServer-inl.h.
References fizz::server::AsyncFizzServerT< SM >::deliverAllErrors(), folly::AsyncSocketException::END_OF_FILE, fizz::server::AsyncFizzServerT< SM >::fizzServer_, and folly::DecoratedAsyncTransportWrapper< folly::AsyncTransportWrapper >::transport_.
{
   DelayedDestruction::DestructorGuard dg(this);
   if (transport_->good()) {
     fizzServer_.appClose();
   }
   folly::AsyncSocketException ase(
       folly::AsyncSocketException::END_OF_FILE, "socket closed locally");
   deliverAllErrors(ase, false);
   transport_->closeNow();
 }
template<typename SM > void fizz::server::AsyncFizzServerT< SM >::closeWithReset () override virtual
Reset the transport immediately.
This closes the transport immediately, sending a reset to the remote peer if possible to indicate abnormal shutdown.
Note that not all subclasses implement this reset functionality: some subclasses may treat reset() the same as closeNow(). Subclasses that use TCP transports should terminate the connection with a TCP reset.
Reimplemented from folly::AsyncTransport.
Definition at line 129 of file AsyncFizzServer-inl.h.
References fizz::server::AsyncFizzServerT< SM >::deliverAllErrors(), folly::AsyncSocketException::END_OF_FILE, fizz::server::AsyncFizzServerT< SM >::fizzServer_, and folly::DecoratedAsyncTransportWrapper< folly::AsyncTransportWrapper >::transport_.
{
   DelayedDestruction::DestructorGuard dg(this);
   if (transport_->good()) {
     fizzServer_.appClose();
   }
   folly::AsyncSocketException ase(
       folly::AsyncSocketException::END_OF_FILE, "socket closed locally");
   deliverAllErrors(ase, false);
   transport_->closeWithReset();
 }
template<typename SM > bool fizz::server::AsyncFizzServerT< SM >::connecting () const override virtual
Determine if transport is connected to the endpoint
Returns
false iff the transport is connected, otherwise true
Implements fizz::AsyncFizzBase.
Definition at line 44 of file AsyncFizzServer-inl.h.
References fizz::server::AsyncFizzServerT< SM >::handshakeCallback_, and folly::DecoratedAsyncTransportWrapper< folly::AsyncTransportWrapper >::transport_.
{
   return handshakeCallback_ || transport_->connecting();
 }
template<typename SM > void fizz::server::AsyncFizzServerT< SM >::deliverAllErrors (const folly::AsyncSocketException & ex, bool closeTransport = true) private
Definition at line 215 of file AsyncFizzServer-inl.h.
References fizz::AsyncFizzBase::deliverError(), fizz::server::AsyncFizzServerT< SM >::deliverHandshakeError(), and fizz::server::AsyncFizzServerT< SM >::fizzServer_.
Referenced by fizz::server::AsyncFizzServerT< SM >::close(), fizz::server::AsyncFizzServerT< SM >::closeNow(), fizz::server::AsyncFizzServerT< SM >::closeWithReset(), fizz::server::AsyncFizzServerT< fizz::server::test::MockServerStateMachineInstance >::getState(), and fizz::server::AsyncFizzServerT< SM >::transportError().
{
   deliverHandshakeError(ex);
   fizzServer_.moveToErrorState(ex);
   deliverError(ex, closeTransport);
 }
template<typename SM > void fizz::server::AsyncFizzServerT< SM >::deliverHandshakeError (folly::exception_wrapper ex) private
Definition at line 224 of file AsyncFizzServer-inl.h.
References fizz::server::AsyncFizzServerT< SM >::HandshakeCallback::fizzHandshakeError(), fizz::server::AsyncFizzServerT< SM >::handshakeCallback_, and folly::gen::move.
Referenced by fizz::server::AsyncFizzServerT< SM >::deliverAllErrors(), and fizz::server::AsyncFizzServerT< fizz::server::test::MockServerStateMachineInstance >::getState().
{
   if (handshakeCallback_) {
     auto callback = handshakeCallback_;
     handshakeCallback_ = nullptr;
     callback->fizzHandshakeError(this, std::move(ex));
   }
 }
template<typename SM > bool fizz::server::AsyncFizzServerT< SM >::error () const override virtual
Determine if an error has occurred with this transport.
Returns
true iff an error has occurred (not EOF).
Implements fizz::AsyncFizzBase.
Definition at line 49 of file AsyncFizzServer-inl.h.
References fizz::server::AsyncFizzServerT< SM >::fizzServer_, and folly::DecoratedAsyncTransportWrapper< folly::AsyncTransportWrapper >::transport_.
Referenced by fizz::server::AsyncFizzServerT< SM >::good(), and fizz::server::AsyncFizzServerT< SM >::writeAppData().
{
   return transport_->error() || fizzServer_.inErrorState();
 }
template<typename SM > std::string fizz::server::AsyncFizzServerT< SM >::getApplicationProtocol () const override virtual noexcept
Return the application protocol being used by the underlying transport protocol. This is useful for transports which are used to tunnel other protocols.
Implements fizz::AsyncFizzBase.
Definition at line 107 of file AsyncFizzServer-inl.h.
References alpn, fizz::server::State::alpn(), and fizz::server::AsyncFizzServerT< SM >::getState().
{
   if (getState().alpn()) {
     return *getState().alpn();
   } else {
     return "";
   }
 }
template<typename SM > folly::Optional< CipherSuite > fizz::server::AsyncFizzServerT< SM >::getCipher () const override virtual
Get the CipherSuite negotiated in this transport.
Implements fizz::AsyncFizzBase.
Definition at line 153 of file AsyncFizzServer-inl.h.
References fizz::server::State::cipher(), and fizz::server::AsyncFizzServerT< SM >::getState().
Referenced by fizz::server::AsyncFizzServerT< fizz::server::test::MockServerStateMachineInstance >::getState().
{
   return getState().cipher();
 }
template<typename SM > Buf fizz::server::AsyncFizzServerT< SM >::getEarlyEkm (folly::StringPiece label, const Buf & hashedContext, uint16_t length) const virtual
Definition at line 172 of file AsyncFizzServer-inl.h.
References fizz::server::AsyncFizzServerT< SM >::fizzServer_.
Referenced by fizz::server::AsyncFizzServerT< fizz::server::test::MockServerStateMachineInstance >::getState().
{
   return fizzServer_.getEarlyEkm(label, context, length);
 }
template<typename SM > Buf fizz::server::AsyncFizzServerT< SM >::getEkm (folly::StringPiece label, const Buf & context, uint16_t length) const override virtual
Get the exported material.
Implements fizz::AsyncFizzBase.
Definition at line 164 of file AsyncFizzServer-inl.h.
References fizz::server::AsyncFizzServerT< SM >::fizzServer_.
Referenced by fizz::server::AsyncFizzServerT< fizz::server::test::MockServerStateMachineInstance >::getState().
{
   return fizzServer_.getEkm(label, context, length);
 }
template<typename SM > folly::ssl::X509UniquePtr fizz::server::AsyncFizzServerT< SM >::getPeerCert () const override virtual
Information about the current security state. To be implemented by derived classes.
Implements fizz::AsyncFizzBase.
Definition at line 65 of file AsyncFizzServer-inl.h.
References fizz::server::AsyncFizzServerT< SM >::getPeerCertificate().
{
   auto cert = getPeerCertificate();
   if (cert) {
     return cert->getX509();
   } else {
     return nullptr;
   }
 }
template<typename SM > const Cert * fizz::server::AsyncFizzServerT< SM >::getPeerCertificate () const override virtual
Get the certificates in fizz::Cert form.
Implements fizz::AsyncFizzBase.
Definition at line 85 of file AsyncFizzServer-inl.h.
References fizz::server::State::clientCert(), and fizz::server::AsyncFizzServerT< SM >::getState().
Referenced by fizz::server::AsyncFizzServerT< SM >::getPeerCert(), and fizz::server::AsyncFizzServerT< fizz::server::test::MockServerStateMachineInstance >::getState().
{
   return getState().clientCert().get();
 }
template<typename SM > const X509 * fizz::server::AsyncFizzServerT< SM >::getSelfCert () const override virtual
The local certificate used for this connection. May be null
Implements fizz::AsyncFizzBase.
Definition at line 75 of file AsyncFizzServer-inl.h.
References fizz::server::AsyncFizzServerT< SM >::getSelfCertificate().
{
   auto cert = getSelfCertificate();
   if (cert) {
     return cert->getX509().get();
   } else {
     return nullptr;
   }
 }
template<typename SM > const Cert * fizz::server::AsyncFizzServerT< SM >::getSelfCertificate () const override virtual
Get the certificate information of this transport, if any
Implements fizz::AsyncFizzBase.
Definition at line 90 of file AsyncFizzServer-inl.h.
References fizz::server::AsyncFizzServerT< SM >::getState(), and fizz::server::State::serverCert().
Referenced by fizz::server::AsyncFizzServerT< SM >::getSelfCert(), and fizz::server::AsyncFizzServerT< fizz::server::test::MockServerStateMachineInstance >::getState().
{
   return getState().serverCert().get();
 }
template<typename SM> const State& fizz::server::AsyncFizzServerT< SM >::getState () const inline
Internal state access for logging/testing.
Definition at line 68 of file AsyncFizzServer.h.
Referenced by fizz::server::AsyncFizzServerT< SM >::getApplicationProtocol(), fizz::server::AsyncFizzServerT< SM >::getCipher(), fizz::server::AsyncFizzServerT< SM >::getPeerCertificate(), fizz::server::AsyncFizzServerT< SM >::getSelfCertificate(), and fizz::server::AsyncFizzServerT< SM >::getSupportedSigSchemes().
{
     return state_;
   }
template<typename SM > std::vector< SignatureScheme > fizz::server::AsyncFizzServerT< SM >::getSupportedSigSchemes () const override virtual
Get the supported signature schemes in this transport.
Implements fizz::AsyncFizzBase.
Definition at line 158 of file AsyncFizzServer-inl.h.
References fizz::server::State::context(), fizz::server::AsyncFizzServerT< SM >::getState(), and fizz::server::FizzServerContext::getSupportedSigSchemes().
Referenced by fizz::server::AsyncFizzServerT< fizz::server::test::MockServerStateMachineInstance >::getState().
           {
   return getState().context()->getSupportedSigSchemes();
 }
template<typename SM > bool fizz::server::AsyncFizzServerT< SM >::good () const override virtual
Information about the current transport state. To be implemented by derived classes.
Implements fizz::AsyncFizzBase.
Definition at line 34 of file AsyncFizzServer-inl.h.
References fizz::server::AsyncFizzServerT< SM >::error(), and folly::DecoratedAsyncTransportWrapper< folly::AsyncTransportWrapper >::transport_.
{
   return !error() && transport_->good();
 }
template<typename SM > bool fizz::server::AsyncFizzServerT< SM >::isDetachable () const override virtual
Determine if the transport can be detached.
This method must be called from the current EventBase's thread.
Reimplemented from fizz::AsyncFizzBase.
Definition at line 54 of file AsyncFizzServer-inl.h.
References fizz::server::AsyncFizzServerT< SM >::fizzServer_, and fizz::AsyncFizzBase::isDetachable().
{
   return !fizzServer_.actionProcessing() && AsyncFizzBase::isDetachable();
 }
template<typename SM > bool fizz::server::AsyncFizzServerT< SM >::isReplaySafe () const override virtual
False if the transport does not have replay protection, but will in the future.
Implements fizz::AsyncFizzBase.
Definition at line 95 of file AsyncFizzServer-inl.h.
{
   // Server always provides replay protection.
   return true;
 }
template<typename SM > bool fizz::server::AsyncFizzServerT< SM >::readable () const override virtual
Determine if the transport is readable or not.
Returns
true iff the transport is readable, false otherwise.
Implements fizz::AsyncFizzBase.
Definition at line 39 of file AsyncFizzServer-inl.h.
References folly::DecoratedAsyncTransportWrapper< folly::AsyncTransportWrapper >::transport_.
{
   return transport_->readable();
 }
template<typename SM > void fizz::server::AsyncFizzServerT< SM >::setReplaySafetyCallback (folly::AsyncTransport::ReplaySafetyCallback * callback) override virtual
Set the ReplaySafeCallback on this transport.
This should only be called if isReplaySafe() returns false.
Implements fizz::AsyncFizzBase.
Definition at line 101 of file AsyncFizzServer-inl.h.
{
   LOG(FATAL) << "setReplaySafetyCallback() called on replay safe transport";
 }
template<typename SM > void fizz::server::AsyncFizzServerT< SM >::transportDataAvailable () override protected virtual
Alert the derived class that additional data is available in transportReadBuf_.
Implements fizz::AsyncFizzBase.
Definition at line 210 of file AsyncFizzServer-inl.h.
References fizz::server::AsyncFizzServerT< SM >::fizzServer_.
Referenced by fizz::server::AsyncFizzServerT< fizz::server::test::MockServerStateMachineInstance >::getState().
{
   fizzServer_.newTransportData();
 }
template<typename SM > void fizz::server::AsyncFizzServerT< SM >::transportError (const folly::AsyncSocketException & ex) override protected virtual
Alert the derived class that a transport error occured.
Implements fizz::AsyncFizzBase.
Definition at line 203 of file AsyncFizzServer-inl.h.
References fizz::server::AsyncFizzServerT< SM >::deliverAllErrors().
Referenced by fizz::server::AsyncFizzServerT< fizz::server::test::MockServerStateMachineInstance >::getState().
{
   DelayedDestruction::DestructorGuard dg(this);
   deliverAllErrors(ex);
 }
template<typename SM > void fizz::server::AsyncFizzServerT< SM >::writeAppData (folly::AsyncTransportWrapper::WriteCallback * callback, std::unique_ptr< folly::IOBuf > && buf, folly::WriteFlags flags = folly::WriteFlags::NONE) override protected virtual
Interface for the derived class to implement to receive app data from the app layer.
Implements fizz::AsyncFizzBase.
Definition at line 180 of file AsyncFizzServer-inl.h.
References fizz::AppWrite::callback, fizz::AppWrite::data, fizz::server::AsyncFizzServerT< SM >::error(), fizz::server::AsyncFizzServerT< SM >::fizzServer_, fizz::AppWrite::flags, folly::AsyncSocketException::INVALID_STATE, folly::gen::move, folly::WriteChainAsyncTransportWrapper< folly::AsyncTransportWrapper >::write(), and folly::AsyncWriter::WriteCallback::writeErr().
Referenced by fizz::server::AsyncFizzServerT< fizz::server::test::MockServerStateMachineInstance >::getState().
{
   if (error()) {
     if (callback) {
       callback->writeErr(
           0,
           folly::AsyncSocketException(
               folly::AsyncSocketException::INVALID_STATE,
               "fizz app write in error state"));
     }
     return;
   }
   AppWrite write;
   write.callback = callback;
   write.data = std::move(buf);
   write.flags = flags;
   fizzServer_.appWrite(std::move(write));
 }
Member Data Documentation
template<typename SM> std::shared_ptr<ServerExtensions> fizz::server::AsyncFizzServerT< SM >::extensions_ private
Definition at line 127 of file AsyncFizzServer.h.
Referenced by fizz::server::AsyncFizzServerT< SM >::accept().
template<typename SM> std::shared_ptr<FizzServerContext> fizz::server::AsyncFizzServerT< SM >::fizzContext_ private
Definition at line 125 of file AsyncFizzServer.h.
Referenced by fizz::server::AsyncFizzServerT< SM >::accept().
template<typename SM> FizzServer<ActionMoveVisitor, SM> fizz::server::AsyncFizzServerT< SM >::fizzServer_ private
Definition at line 133 of file AsyncFizzServer.h.
Referenced by fizz::server::AsyncFizzServerT< SM >::accept(), fizz::server::AsyncFizzServerT< SM >::close(), fizz::server::AsyncFizzServerT< SM >::closeNow(), fizz::server::AsyncFizzServerT< SM >::closeWithReset(), fizz::server::AsyncFizzServerT< SM >::deliverAllErrors(), fizz::server::AsyncFizzServerT< SM >::error(), fizz::server::AsyncFizzServerT< SM >::getEarlyEkm(), fizz::server::AsyncFizzServerT< SM >::getEkm(), fizz::server::AsyncFizzServerT< SM >::isDetachable(), fizz::server::AsyncFizzServerT< SM >::transportDataAvailable(), and fizz::server::AsyncFizzServerT< SM >::writeAppData().
template<typename SM> HandshakeCallback* fizz::server::AsyncFizzServerT< SM >::handshakeCallback_ {nullptr} private
Definition at line 123 of file AsyncFizzServer.h.
Referenced by fizz::server::AsyncFizzServerT< SM >::accept(), fizz::server::AsyncFizzServerT< SM >::connecting(), and fizz::server::AsyncFizzServerT< SM >::deliverHandshakeError().
template<typename SM> State fizz::server::AsyncFizzServerT< SM >::state_ private
Definition at line 129 of file AsyncFizzServer.h.
Referenced by fizz::server::AsyncFizzServerT< SM >::attachEventBase(), and fizz::server::AsyncFizzServerT< fizz::server::test::MockServerStateMachineInstance >::getState().
template<typename SM> ActionMoveVisitor fizz::server::AsyncFizzServerT< SM >::visitor_ private
Definition at line 131 of file AsyncFizzServer.h.
The documentation for this class was generated from the following files:
proxygen/fizz/fizz/server/AsyncFizzServer.h
proxygen/fizz/fizz/server/AsyncFizzServer-inl.h