proxygen: wangle::OutboundHandlerContext< Out > Class Template Reference
wangle::OutboundHandlerContext< Out > Class Template Reference abstract
#include <HandlerContext.h>
Public Member Functions
virtual ~OutboundHandlerContext ()=default
virtual folly::Future< folly::Unit > fireWrite (Out msg)=0
virtual folly::Future< folly::Unit > fireWriteException (folly::exception_wrapper e)=0
virtual folly::Future< folly::Unit > fireClose ()=0
virtual PipelineBase * getPipeline ()=0
virtual std::shared_ptr< PipelineBase > getPipelineShared ()=0
std::shared_ptr< folly::AsyncTransport > getTransport ()
Detailed Description
template<class Out>
class wangle::OutboundHandlerContext< Out >
Definition at line 91 of file HandlerContext.h.
Constructor & Destructor Documentation
template<class Out> virtual wangle::OutboundHandlerContext< Out >::~OutboundHandlerContext () virtual default
Member Function Documentation
template<class Out> virtual folly::Future<folly::Unit> wangle::OutboundHandlerContext< Out >::fireClose () pure virtual
Implemented in wangle::OutboundContextImpl< H >.
Referenced by wangle::EventBaseHandler::close(), wangle::OutputBufferingHandler::close(), and wangle::OutboundHandler< std::string, std::unique_ptr< folly::IOBuf > >::close().
template<class Out> virtual folly::Future<folly::Unit> wangle::OutboundHandlerContext< Out >::fireWrite (Out msg) pure virtual
Implemented in wangle::OutboundContextImpl< H >.
Referenced by wangle::OutputBufferingHandler::runLoopCallback(), wangle::EventBaseHandler::write(), wangle::MessageToByteEncoder< T >::write(), wangle::OutputBufferingHandler::write(), and wangle::LengthFieldPrepender::write().
template<class Out> virtual folly::Future<folly::Unit> wangle::OutboundHandlerContext< Out >::fireWriteException (folly::exception_wrapper e) pure virtual
Implemented in wangle::OutboundContextImpl< H >.
Referenced by wangle::OutboundHandler< std::string, std::unique_ptr< folly::IOBuf > >::writeException().
template<class Out> virtual PipelineBase* wangle::OutboundHandlerContext< Out >::getPipeline () pure virtual
Implemented in wangle::OutboundContextImpl< H >.
template<class Out> virtual std::shared_ptr<PipelineBase> wangle::OutboundHandlerContext< Out >::getPipelineShared () pure virtual
Implemented in wangle::OutboundContextImpl< H >.
template<class Out> std::shared_ptr<folly::AsyncTransport> wangle::OutboundHandlerContext< Out >::getTransport () inline
Definition at line 102 of file HandlerContext.h.
Referenced by wangle::EventBaseHandler::close(), wangle::EventBaseHandler::write(), and wangle::OutputBufferingHandler::write().
{
     return getPipeline()->getTransport();
   }
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/channel/HandlerContext.h