proxygen: fizz::ZlibCertificateDecompressor Class Reference
fizz::ZlibCertificateDecompressor Class Reference
#include <ZlibCertificateDecompressor.h>
Public Member Functions
~ZlibCertificateDecompressor () override=default
CertificateCompressionAlgorithm getAlgorithm () const override
CertificateMsg decompress (const CompressedCertificate &) override
Public Member Functions inherited from fizz::CertificateDecompressor
virtual ~CertificateDecompressor ()=default
Detailed Description
Definition at line 15 of file ZlibCertificateDecompressor.h.
Constructor & Destructor Documentation
fizz::ZlibCertificateDecompressor::~ZlibCertificateDecompressor () override default
Member Function Documentation
CertificateMsg fizz::ZlibCertificateDecompressor::decompress (const CompressedCertificate & cc) override virtual
Implements fizz::CertificateDecompressor.
Definition at line 20 of file ZlibCertificateDecompressor.cpp.
References fizz::CompressedCertificate::algorithm, fizz::CompressedCertificate::compressed_certificate_message, folly::IOBuf::create(), fizz::kMaxHandshakeSize, folly::gen::move, folly::size(), fizz::toString(), and fizz::CompressedCertificate::uncompressed_length.
{
   if (cc.algorithm != getAlgorithm()) {
     throw std::runtime_error(
         "Compressed certificate uses non-zlib algorithm: " +
         toString(cc.algorithm));
   }
   if (cc.uncompressed_length > kMaxHandshakeSize) {
     throw std::runtime_error(
         "Compressed certificate exceeds maximum certificate message size");
   }
   auto rawCertMessage = IOBuf::create(cc.uncompressed_length);
   unsigned long size = cc.uncompressed_length;
   auto compRange = cc.compressed_certificate_message->coalesce();
   auto status = ::uncompress(
       rawCertMessage->writableData(),
       &size,
       compRange.data(),
       compRange.size());
   switch (status) {
     case Z_OK:
       if (size != cc.uncompressed_length) {
         throw std::runtime_error("Uncompressed length incorrect");
       }
       break;
     case Z_MEM_ERROR:
       throw std::runtime_error("Insufficient memory to decompress cert");
     case Z_BUF_ERROR:
       throw std::runtime_error(
           "The uncompressed length given is too small to hold uncompressed data");
     case Z_DATA_ERROR:
       throw std::runtime_error(
           "The compressed certificate data was incomplete or invalid");
     default:
       throw std::runtime_error(
           "Failed to decompress: " + to<std::string>(status));
   }
   rawCertMessage->append(size);
   return decode<CertificateMsg>(std::move(rawCertMessage));
 }
CertificateCompressionAlgorithm fizz::ZlibCertificateDecompressor::getAlgorithm () const override virtual
Implements fizz::CertificateDecompressor.
Definition at line 15 of file ZlibCertificateDecompressor.cpp.
           {
   return CertificateCompressionAlgorithm::zlib;
 }
The documentation for this class was generated from the following files:
proxygen/fizz/fizz/protocol/ZlibCertificateDecompressor.h
proxygen/fizz/fizz/protocol/ZlibCertificateDecompressor.cpp