proxygen: folly::futures::detail::WaitExecutor Class Reference
folly::futures::detail::WaitExecutor Class Reference final
#include <Future-inl.h>
Classes
struct Queue
Public Types
using Clock = std::chrono::steady_clock
Public Member Functions
void add (Func func) override
void drive ()
bool driveUntil (Clock::time_point deadline)
void detach ()
Public Member Functions inherited from folly::Executor
virtual ~Executor ()
virtual void addWithPriority (Func, int8_t priority)
virtual uint8_t getNumPriorities () const
Static Public Member Functions
static KeepAlive< WaitExecutor > create ()
Static Public Member Functions inherited from folly::Executor
template<typename ExecutorT >
static KeepAlive< ExecutorT > getKeepAliveToken (ExecutorT *executor)
template<typename ExecutorT >
static KeepAlive< ExecutorT > getKeepAliveToken (ExecutorT &executor)
Private Member Functions
WaitExecutor ()
bool keepAliveAcquire () override
void keepAliveRelease () override
Private Attributes
folly::Synchronized< Queue > queue_
FutureBatonType baton_
std::atomic< ssize_t > keepAliveCount_ {1}
Additional Inherited Members
Static Public Attributes inherited from folly::Executor
static const int8_t LO_PRI = SCHAR_MIN
static const int8_t MID_PRI = 0
static const int8_t HI_PRI = SCHAR_MAX
Static Protected Member Functions inherited from folly::Executor
template<typename ExecutorT >
static bool isKeepAliveDummy (const KeepAlive< ExecutorT > &keepAlive)
template<typename ExecutorT >
static KeepAlive< ExecutorT > makeKeepAlive (ExecutorT *executor)
Detailed Description
Definition at line 610 of file Future-inl.h.
Member Typedef Documentation
using folly::futures::detail::WaitExecutor::Clock = std::chrono::steady_clock
Definition at line 633 of file Future-inl.h.
Constructor & Destructor Documentation
folly::futures::detail::WaitExecutor::WaitExecutor () inline private
Definition at line 661 of file Future-inl.h.
 {}
Member Function Documentation
void folly::futures::detail::WaitExecutor::add (Func) inline override virtual
Enqueue a function to executed by this executor. This and all variants must be threadsafe.
Implements folly::Executor.
Definition at line 612 of file Future-inl.h.
References folly::empty(), and folly::gen::move.
{
     auto wQueue = queue_.wlock();
     if (wQueue->detached) {
       return;
     }
     bool empty = wQueue->funcs.empty();
     wQueue->funcs.push_back(std::move(func));
     if (empty) {
       baton_.post();
     }
   }
static KeepAlive<WaitExecutor> folly::futures::detail::WaitExecutor::create () inline static
Definition at line 656 of file Future-inl.h.
Referenced by folly::SemiFuture< T >::wait().
{
     return makeKeepAlive<WaitExecutor>(new WaitExecutor());
   }
void folly::futures::detail::WaitExecutor::detach () inline
Definition at line 647 of file Future-inl.h.
References folly::gen::move.
                 {
     // Make sure we don't hold the lock while destroying funcs.
     [&] {
       auto wQueue = queue_.wlock();
       wQueue->detached = true;
       return std::move(wQueue->funcs);
     }();
   }
void folly::futures::detail::WaitExecutor::drive () inline
Definition at line 624 of file Future-inl.h.
References folly::exchange(), and folly::gen::move.
                {
     baton_.wait();
     baton_.reset();
     auto funcs = std::move(queue_.wlock()->funcs);
     for (auto& func : funcs) {
       std::exchange(func, nullptr)();
     }
   }
bool folly::futures::detail::WaitExecutor::driveUntil (Clock::time_point deadline) inline
Definition at line 635 of file Future-inl.h.
References folly::exchange(), and folly::gen::move.
{
     if (!baton_.try_wait_until(deadline)) {
       return false;
     }
     baton_.reset();
     auto funcs = std::move(queue_.wlock()->funcs);
     for (auto& func : funcs) {
       std::exchange(func, nullptr)();
     }
     return true;
   }
bool folly::futures::detail::WaitExecutor::keepAliveAcquire () inline override private virtual
Reimplemented from folly::Executor.
Definition at line 663 of file Future-inl.h.
{
     auto keepAliveCount =
         keepAliveCount_.fetch_add(1, std::memory_order_relaxed);
     DCHECK(keepAliveCount > 0);
     return true;
   }
void folly::futures::detail::WaitExecutor::keepAliveRelease () inline override private virtual
Reimplemented from folly::Executor.
Definition at line 670 of file Future-inl.h.
{
     auto keepAliveCount =
         keepAliveCount_.fetch_sub(1, std::memory_order_acq_rel);
     DCHECK(keepAliveCount > 0);
     if (keepAliveCount == 1) {
       delete this;
     }
   }
Member Data Documentation
FutureBatonType folly::futures::detail::WaitExecutor::baton_ private
Definition at line 685 of file Future-inl.h.
std::atomic<ssize_t> folly::futures::detail::WaitExecutor::keepAliveCount_ {1} private
Definition at line 687 of file Future-inl.h.
folly::Synchronized<Queue> folly::futures::detail::WaitExecutor::queue_ private
Definition at line 684 of file Future-inl.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/futures/Future-inl.h