proxygen: wangle::FilePersistenceLayer< K, V > Class Template Reference
wangle::FilePersistenceLayer< K, V > Class Template Reference
#include <FilePersistentCache-inl.h>
Public Member Functions
FilePersistenceLayer (const std::string &file)
~FilePersistenceLayer () override
bool persist (const folly::dynamic &arrayOfKvPairs) noexceptoverride
folly::Optional< folly::dynamic > load () noexceptoverride
void clear () override
Public Member Functions inherited from wangle::CachePersistence< K, V >
CachePersistence ()
virtual ~CachePersistence ()=default
bool persistVersionedData (const folly::dynamic &kvPairs, const CacheDataVersion &version)
virtual CacheDataVersion getLastPersistedVersion () const
virtual void setPersistedVersion (CacheDataVersion version) noexcept
Private Attributes
std::string file_
Detailed Description
template<typename K, typename V>
class wangle::FilePersistenceLayer< K, V >
Definition at line 26 of file FilePersistentCache-inl.h.
Constructor & Destructor Documentation
template<typename K , typename V > wangle::FilePersistenceLayer< K, V >::FilePersistenceLayer (const std::string & file) inline explicit
Definition at line 28 of file FilePersistentCache-inl.h.
 : file_(file) {}
template<typename K , typename V > wangle::FilePersistenceLayer< K, V >::~FilePersistenceLayer () inline override
Definition at line 29 of file FilePersistentCache-inl.h.
References wangle::FilePersistenceLayer< K, V >::clear(), wangle::FilePersistenceLayer< K, V >::load(), folly::pushmi::__adl::noexcept(), and wangle::FilePersistenceLayer< K, V >::persist().
 {}
Member Function Documentation
template<typename K , typename V > void wangle::FilePersistenceLayer< K, V >::clear () override virtual
Clears Persistent cache
Implements wangle::CachePersistence< K, V >.
Definition at line 108 of file FilePersistentCache-inl.h.
References wangle::FilePersistenceLayer< K, V >::file_.
Referenced by wangle::FilePersistenceLayer< K, V >::~FilePersistenceLayer().
{
   // This may fail but it's ok
   ::unlink(file_.c_str());
 }
template<typename K , typename V > folly::Optional< folly::dynamic > wangle::FilePersistenceLayer< K, V >::load () override virtual noexcept
Returns a list of key value pairs that are present in this persistence store.
Implements wangle::CachePersistence< K, V >.
Definition at line 87 of file FilePersistentCache-inl.h.
References folly::json::serialization_opts::allow_non_string_keys, wangle::FilePersistenceLayer< K, V >::file_, folly::none, folly::parseJson(), folly::readFile(), and string.
Referenced by wangle::FilePersistenceLayer< K, V >::~FilePersistenceLayer().
{
   std::string serializedCache;
   // not being able to read the backing storage means we just
   // start with an empty cache. Failing to deserialize, or write,
   // is a real error so we report errors there.
   if (!folly::readFile(file_.c_str(), serializedCache)) {
     return folly::none;
   }
   try {
     folly::json::serialization_opts opts;
     opts.allow_non_string_keys = true;
     return folly::parseJson(serializedCache, opts);
   } catch (const std::exception& err) {
     LOG(ERROR) << "Deserialization of cache file " << file_
                << " failed with parse error: " << err.what();
   }
   return folly::none;
 }
template<typename K , typename V > bool wangle::FilePersistenceLayer< K, V >::persist (const folly::dynamic & kvPairs) override virtual noexcept
Persist a folly::dynamic array of key value pairs. Returns true on success.
Implements wangle::CachePersistence< K, V >.
Definition at line 42 of file FilePersistentCache-inl.h.
References folly::json::serialization_opts::allow_non_string_keys, folly::closeNoInt(), folly::fdatasyncNoInt(), wangle::FilePersistenceLayer< K, V >::file_, folly::openNoInt(), folly::json::serialize(), string, and folly::writeFull().
Referenced by wangle::FilePersistenceLayer< K, V >::~FilePersistenceLayer().
{
   std::string serializedCache;
   try {
     folly::json::serialization_opts opts;
     opts.allow_non_string_keys = true;
     serializedCache = folly::json::serialize(dynObj, opts);
   } catch (const std::exception& err) {
     LOG(ERROR) << "Serializing to JSON failed with error: " << err.what();
     return false;
   }
   bool persisted = false;
   const auto fd = folly::openNoInt(
     file_.c_str(),
     O_WRONLY | O_CREAT | O_TRUNC,
     S_IRUSR | S_IWUSR
   );
   if (fd == -1) {
     return false;
   }
   const auto nWritten = folly::writeFull(
     fd,
     serializedCache.data(),
     serializedCache.size()
   );
   persisted = nWritten >= 0 &&
     (static_cast<size_t>(nWritten) == serializedCache.size());
   if (!persisted) {
     LOG(ERROR) << "Failed to write to " << file_ << ":";
     if (nWritten == -1) {
       LOG(ERROR) << "write failed with errno " << errno;
     }
   }
   if (folly::fdatasyncNoInt(fd) != 0) {
     LOG(ERROR) << "Failed to sync " << file_ << ": errno " << errno;
     persisted = false;
   }
   if (folly::closeNoInt(fd) != 0) {
     LOG(ERROR) << "Failed to close " << file_ << ": errno " << errno;
     persisted = false;
   }
   return persisted;
 }
Member Data Documentation
template<typename K , typename V > std::string wangle::FilePersistenceLayer< K, V >::file_ private
Definition at line 38 of file FilePersistentCache-inl.h.
Referenced by wangle::FilePersistenceLayer< K, V >::clear(), wangle::FilePersistenceLayer< K, V >::load(), and wangle::FilePersistenceLayer< K, V >::persist().
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/client/persistence/FilePersistentCache-inl.h