proxygen: Queue< E > Class Template Reference
Queue< E > Class Template Reference
#include <sample3-inl.h>
Public Member Functions
Queue ()
~Queue ()
void Clear ()
size_t Size () const
QueueNode< E > * Head ()
const QueueNode< E > * Head () const
QueueNode< E > * Last ()
const QueueNode< E > * Last () const
void Enqueue (const E &element)
E * Dequeue ()
template<typename F >
Queue * Map (F function) const
void push (const T &val)
void pop (T &val)
Queue ()
~Queue ()
void Clear ()
size_t Size () const
QueueNode< E > * Head ()
const QueueNode< E > * Head () const
QueueNode< E > * Last ()
const QueueNode< E > * Last () const
void Enqueue (const E &element)
E * Dequeue ()
template<typename F >
Queue * Map (F function) const
Queue ()
~Queue ()
void Clear ()
size_t Size () const
QueueNode< E > * Head ()
const QueueNode< E > * Head () const
QueueNode< E > * Last ()
const QueueNode< E > * Last () const
void Enqueue (const E &element)
E * Dequeue ()
template<typename F >
Queue * Map (F function) const
Private Member Functions
Queue (const Queue &)
const Queue & operator= (const Queue &)
Queue (const Queue &)
const Queue & operator= (const Queue &)
Queue (const Queue &)
const Queue & operator= (const Queue &)
Private Attributes
QueueNode< E > * head_
QueueNode< E > * last_
size_t size_
std::queue< T > q_
Detailed Description
template<typename E>
class Queue< E >
Definition at line 44 of file sample3-inl.h.
Constructor & Destructor Documentation
template<typename E> Queue< E >::Queue () inline
Definition at line 77 of file sample3-inl.h.
 : head_(NULL), last_(NULL), size_(0) {}
template<typename E> Queue< E >::~Queue () inline
Definition at line 80 of file sample3-inl.h.
 { Clear(); }
template<typename E> Queue< E >::Queue (const Queue< E > &) private
template<typename E> Queue< E >::Queue () inline
Definition at line 77 of file sample3-inl.h.
 : head_(NULL), last_(NULL), size_(0) {}
template<typename E> Queue< E >::~Queue () inline
Definition at line 80 of file sample3-inl.h.
 { Clear(); }
template<typename E> Queue< E >::Queue (const Queue< E > &) private
template<typename E> Queue< E >::Queue () inline
Definition at line 77 of file sample3-inl.h.
 : head_(NULL), last_(NULL), size_(0) {}
template<typename E> Queue< E >::~Queue () inline
Definition at line 80 of file sample3-inl.h.
 { Clear(); }
template<typename E> Queue< E >::Queue (const Queue< E > &) private
Member Function Documentation
template<typename E> void Queue< E >::Clear () inline
Definition at line 83 of file sample3-inl.h.
                {
     if (size_ > 0) {
       // 1. Deletes every node.
       QueueNode<E>* node = head_;
       QueueNode<E>* next = node->next();
       for (; ;) {
         delete node;
         node = next;
         if (node == NULL) break;
         next = node->next();
       }
       // 2. Resets the member variables.
       head_ = last_ = NULL;
       size_ = 0;
     }
   }
template<typename E> void Queue< E >::Clear () inline
Definition at line 83 of file sample3-inl.h.
                {
     if (size_ > 0) {
       // 1. Deletes every node.
       QueueNode<E>* node = head_;
       QueueNode<E>* next = node->next();
       for (; ;) {
         delete node;
         node = next;
         if (node == NULL) break;
         next = node->next();
       }
       // 2. Resets the member variables.
       head_ = last_ = NULL;
       size_ = 0;
     }
   }
template<typename E> void Queue< E >::Clear () inline
Definition at line 83 of file sample3-inl.h.
                {
     if (size_ > 0) {
       // 1. Deletes every node.
       QueueNode<E>* node = head_;
       QueueNode<E>* next = node->next();
       for (; ;) {
         delete node;
         node = next;
         if (node == NULL) break;
         next = node->next();
       }
       // 2. Resets the member variables.
       head_ = last_ = NULL;
       size_ = 0;
     }
   }
template<typename E> E* Queue< E >::Dequeue () inline
Definition at line 131 of file sample3-inl.h.
Referenced by TEST_F().
                {
     if (size_ == 0) {
       return NULL;
     }
     const QueueNode<E>* const old_head = head_;
     head_ = head_->next_;
     size_--;
     if (size_ == 0) {
       last_ = NULL;
     }
     E* element = new E(old_head->element());
     delete old_head;
     return element;
   }
template<typename E> E* Queue< E >::Dequeue () inline
Definition at line 131 of file sample3-inl.h.
                {
     if (size_ == 0) {
       return NULL;
     }
     const QueueNode<E>* const old_head = head_;
     head_ = head_->next_;
     size_--;
     if (size_ == 0) {
       last_ = NULL;
     }
     E* element = new E(old_head->element());
     delete old_head;
     return element;
   }
template<typename E> E* Queue< E >::Dequeue () inline
Definition at line 131 of file sample3-inl.h.
                {
     if (size_ == 0) {
       return NULL;
     }
     const QueueNode<E>* const old_head = head_;
     head_ = head_->next_;
     size_--;
     if (size_ == 0) {
       last_ = NULL;
     }
     E* element = new E(old_head->element());
     delete old_head;
     return element;
   }
template<typename E> void Queue< E >::Enqueue (const E & element) inline
Definition at line 116 of file sample3-inl.h.
{
     QueueNode<E>* new_node = new QueueNode<E>(element);
     if (size_ == 0) {
       head_ = last_ = new_node;
       size_ = 1;
     } else {
       last_->next_ = new_node;
       last_ = new_node;
       size_++;
     }
   }
template<typename E> void Queue< E >::Enqueue (const E & element) inline
Definition at line 116 of file sample3-inl.h.
Referenced by Queue< int >::Map(), and QueueTest::SetUp().
{
     QueueNode<E>* new_node = new QueueNode<E>(element);
     if (size_ == 0) {
       head_ = last_ = new_node;
       size_ = 1;
     } else {
       last_->next_ = new_node;
       last_ = new_node;
       size_++;
     }
   }
template<typename E> void Queue< E >::Enqueue (const E & element) inline
Definition at line 116 of file sample3-inl.h.
{
     QueueNode<E>* new_node = new QueueNode<E>(element);
     if (size_ == 0) {
       head_ = last_ = new_node;
       size_ = 1;
     } else {
       last_->next_ = new_node;
       last_ = new_node;
       size_++;
     }
   }
template<typename E> QueueNode<E>* Queue< E >::Head () inline
Definition at line 105 of file sample3-inl.h.
 { return head_; }
template<typename E> QueueNode<E>* Queue< E >::Head () inline
Definition at line 105 of file sample3-inl.h.
Referenced by QueueTest::MapTester().
 { return head_; }
template<typename E> QueueNode<E>* Queue< E >::Head () inline
Definition at line 105 of file sample3-inl.h.
 { return head_; }
template<typename E> const QueueNode<E>* Queue< E >::Head () const inline
Definition at line 106 of file sample3-inl.h.
 { return head_; }
template<typename E> const QueueNode<E>* Queue< E >::Head () const inline
Definition at line 106 of file sample3-inl.h.
 { return head_; }
template<typename E> const QueueNode<E>* Queue< E >::Head () const inline
Definition at line 106 of file sample3-inl.h.
 { return head_; }
template<typename E> QueueNode<E>* Queue< E >::Last () inline
Definition at line 109 of file sample3-inl.h.
 { return last_; }
template<typename E> QueueNode<E>* Queue< E >::Last () inline
Definition at line 109 of file sample3-inl.h.
 { return last_; }
template<typename E> QueueNode<E>* Queue< E >::Last () inline
Definition at line 109 of file sample3-inl.h.
 { return last_; }
template<typename E> const QueueNode<E>* Queue< E >::Last () const inline
Definition at line 110 of file sample3-inl.h.
 { return last_; }
template<typename E> const QueueNode<E>* Queue< E >::Last () const inline
Definition at line 110 of file sample3-inl.h.
 { return last_; }
template<typename E> const QueueNode<E>* Queue< E >::Last () const inline
Definition at line 110 of file sample3-inl.h.
 { return last_; }
template<typename E> template<typename F > Queue* Queue< E >::Map (F function) const inline
Definition at line 153 of file sample3-inl.h.
Referenced by QueueTest::MapTester().
{
     Queue* new_queue = new Queue();
     for (const QueueNode<E>* node = head_; node != NULL; node = node->next_) {
       new_queue->Enqueue(function(node->element()));
     }
     return new_queue;
   }
template<typename E> template<typename F > Queue* Queue< E >::Map (F function) const inline
Definition at line 153 of file sample3-inl.h.
{
     Queue* new_queue = new Queue();
     for (const QueueNode<E>* node = head_; node != NULL; node = node->next_) {
       new_queue->Enqueue(function(node->element()));
     }
     return new_queue;
   }
template<typename E> template<typename F > Queue* Queue< E >::Map (F function) const inline
Definition at line 153 of file sample3-inl.h.
{
     Queue* new_queue = new Queue();
     for (const QueueNode<E>* node = head_; node != NULL; node = node->next_) {
       new_queue->Enqueue(function(node->element()));
     }
     return new_queue;
   }
template<typename E> const Queue& Queue< E >::operator= (const Queue< E > &) private
template<typename E> const Queue& Queue< E >::operator= (const Queue< E > &) private
template<typename E> const Queue& Queue< E >::operator= (const Queue< E > &) private
template<typename E> void Queue< E >::pop (T & val) inline
Definition at line 838 of file RelaxedConcurrentPriorityQueueTest.cpp.
                    {
     val = q_.front();
     q_.pop();
   }
template<typename E> void Queue< E >::push (const T & val) inline
Definition at line 835 of file RelaxedConcurrentPriorityQueueTest.cpp.
{
     q_.push(val);
   }
template<typename E> size_t Queue< E >::Size () const inline
Definition at line 102 of file sample3-inl.h.
 { return size_; }
template<typename E> size_t Queue< E >::Size () const inline
Definition at line 102 of file sample3-inl.h.
 { return size_; }
template<typename E> size_t Queue< E >::Size () const inline
Definition at line 102 of file sample3-inl.h.
Referenced by QueueTest::MapTester(), and TEST_F().
 { return size_; }
Member Data Documentation
template<typename E> QueueNode< E > * Queue< E >::head_ private
Definition at line 163 of file sample3-inl.h.
template<typename E> QueueNode< E > * Queue< E >::last_ private
Definition at line 164 of file sample3-inl.h.
template<typename E> std::queue<T> Queue< E >::q_ private
Definition at line 832 of file RelaxedConcurrentPriorityQueueTest.cpp.
template<typename E> size_t Queue< E >::size_ private
Definition at line 165 of file sample3-inl.h.
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googletest/samples/sample3-inl.h
proxygen/folly/folly/experimental/test/RelaxedConcurrentPriorityQueueTest.cpp