proxygen: fizz::PlaintextReadRecordLayer Class Reference
fizz::PlaintextReadRecordLayer Class Reference
#include <PlaintextRecordLayer.h>
Public Member Functions
~PlaintextReadRecordLayer () override=default
virtual void setSkipEncryptedRecords (bool enabled)
folly::Optional< TLSMessage > read (folly::IOBufQueue &buf) override
folly::Optional< ProtocolVersion > getReceivedRecordVersion () const
EncryptionLevel getEncryptionLevel () const override
Public Member Functions inherited from fizz::ReadRecordLayer
virtual ~ReadRecordLayer ()=default
virtual folly::Optional< Param > readEvent (folly::IOBufQueue &socketBuf)
virtual bool hasUnparsedHandshakeData () const
Private Attributes
bool skipEncryptedRecords_ {false}
folly::Optional< ProtocolVersion > receivedRecordVersion_
Additional Inherited Members
Static Public Member Functions inherited from fizz::ReadRecordLayer
static folly::Optional< Param > decodeHandshakeMessage (folly::IOBufQueue &buf)
Detailed Description
Definition at line 15 of file PlaintextRecordLayer.h.
Constructor & Destructor Documentation
fizz::PlaintextReadRecordLayer::~PlaintextReadRecordLayer () override default
Member Function Documentation
EncryptionLevel fizz::PlaintextReadRecordLayer::getEncryptionLevel () const override virtual
Returns the current encryption level of the data that the read record layer can process.
Implements fizz::ReadRecordLayer.
Definition at line 97 of file PlaintextRecordLayer.cpp.
References fizz::Plaintext.
Referenced by getReceivedRecordVersion().
{
   return EncryptionLevel::Plaintext;
 }
folly::Optional<ProtocolVersion> fizz::PlaintextReadRecordLayer::getReceivedRecordVersion () const inline
Get the record protocol version of the most recent received record. Should only be used for logging.
Definition at line 32 of file PlaintextRecordLayer.h.
References getEncryptionLevel(), and receivedRecordVersion_.
{
     return receivedRecordVersion_;
   }
folly::Optional< TLSMessage > fizz::PlaintextReadRecordLayer::read (folly::IOBufQueue & buf) override virtual
Reads a fragment from the record layer. Returns an empty optional if insuficient data available. Throws if data malformed. On success, advances buf the amount read.
Implements fizz::ReadRecordLayer.
Definition at line 23 of file PlaintextRecordLayer.cpp.
References fizz::alert, fizz::application_data, folly::IOBufQueue::chainLength(), fizz::change_cipher_spec, folly::IOBufQueue::empty(), fizz::TLSMessage::fragment, folly::IOBufQueue::front(), fizz::handshake, folly::hexlify(), fizz::illegal_parameter, folly::gen::move, folly::none, receivedRecordVersion_, skipEncryptedRecords_, folly::IOBufQueue::splitAtMost(), folly::IOBufQueue::trimStart(), fizz::TLSMessage::type, and uint16_t.
Referenced by setSkipEncryptedRecords().
{
   while (true) {
     folly::io::Cursor cursor(buf.front());
     if (buf.empty() || !cursor.canAdvance(kPlaintextHeaderSize)) {
       return folly::none;
     }
     TLSMessage msg;
     msg.type = static_cast<ContentType>(cursor.readBE<ContentTypeType>());
     if (skipEncryptedRecords_) {
       if (msg.type == ContentType::application_data) {
         cursor.skip(sizeof(ProtocolVersion));
         auto length = cursor.readBE<uint16_t>();
         if (buf.chainLength() < (cursor - buf.front()) + length) {
           return folly::none;
         }
         length +=
             sizeof(ContentType) + sizeof(ProtocolVersion) + sizeof(uint16_t);
         buf.trimStart(length);
         continue;
       } else if (msg.type != ContentType::change_cipher_spec) {
         skipEncryptedRecords_ = false;
       }
     }
     switch (msg.type) {
       case ContentType::handshake:
       case ContentType::alert:
         break;
       case ContentType::change_cipher_spec:
         break;
       default:
         throw std::runtime_error(folly::to<std::string>(
             "received plaintext content type ",
             static_cast<ContentTypeType>(msg.type),
             ", header: ",
             folly::hexlify(buf.splitAtMost(10)->coalesce())));
     }
     receivedRecordVersion_ =
         static_cast<ProtocolVersion>(cursor.readBE<ProtocolVersionType>());
     auto length = cursor.readBE<uint16_t>();
     if (length > kMaxPlaintextRecordSize) {
       throw std::runtime_error("received too long plaintext record");
     }
     if (length == 0) {
       throw std::runtime_error("received empty plaintext record");
     }
     if (buf.chainLength() < (cursor - buf.front()) + length) {
       return folly::none;
     }
     cursor.clone(msg.fragment, length);
     buf.trimStart(cursor - buf.front());
     if (msg.type == ContentType::change_cipher_spec) {
       msg.fragment->coalesce();
       if (msg.fragment->length() == 1 && *msg.fragment->data() == 0x01) {
         continue;
       } else {
         throw FizzException(
             "received ccs", AlertDescription::illegal_parameter);
       }
     }
     return std::move(msg);
   }
 }
virtual void fizz::PlaintextReadRecordLayer::setSkipEncryptedRecords (bool enabled) inline virtual
Skip over received encrypted records until a plaintext record is received.
Definition at line 22 of file PlaintextRecordLayer.h.
References read(), and skipEncryptedRecords_.
{
     skipEncryptedRecords_ = enabled;
   }
Member Data Documentation
folly::Optional<ProtocolVersion> fizz::PlaintextReadRecordLayer::receivedRecordVersion_ private
Definition at line 41 of file PlaintextRecordLayer.h.
Referenced by getReceivedRecordVersion(), and read().
bool fizz::PlaintextReadRecordLayer::skipEncryptedRecords_ {false} private
Definition at line 39 of file PlaintextRecordLayer.h.
Referenced by read(), and setSkipEncryptedRecords().
The documentation for this class was generated from the following files:
proxygen/fizz/fizz/record/PlaintextRecordLayer.h
proxygen/fizz/fizz/record/PlaintextRecordLayer.cpp