proxygen: proxygen::HTTPSession::FlowControlTimeout Class Reference
proxygen::HTTPSession::FlowControlTimeout Class Reference
Public Member Functions
FlowControlTimeout (HTTPSession *session)
~FlowControlTimeout () override
void timeoutExpired () noexceptoverride
std::chrono::milliseconds getTimeoutDuration () const
void setTimeoutDuration (std::chrono::milliseconds duration)
Public Member Functions inherited from folly::HHWheelTimer::Callback
Callback ()=default
virtual ~Callback ()
virtual void callbackCanceled () noexcept
void cancelTimeout ()
bool isScheduled () const
std::chrono::milliseconds getTimeRemaining ()
Private Attributes
HTTPSession * session_
std::chrono::milliseconds duration_ {std::chrono::milliseconds(0)}
Additional Inherited Members
Protected Member Functions inherited from folly::HHWheelTimer::Callback
virtual std::chrono::steady_clock::time_point getCurTime ()
Detailed Description
Definition at line 1000 of file HTTPSession.h.
Constructor & Destructor Documentation
proxygen::HTTPSession::FlowControlTimeout::FlowControlTimeout (HTTPSession * session) inline explicit
Definition at line 1002 of file HTTPSession.h.
 : session_(session) {}
proxygen::HTTPSession::FlowControlTimeout::~FlowControlTimeout () inline override
Definition at line 1003 of file HTTPSession.h.
 {}
Member Function Documentation
std::chrono::milliseconds proxygen::HTTPSession::FlowControlTimeout::getTimeoutDuration () const inline
Definition at line 1009 of file HTTPSession.h.
Referenced by proxygen::HTTPSession::onConnectionSendWindowClosed().
{
       return duration_;
     }
void proxygen::HTTPSession::FlowControlTimeout::setTimeoutDuration (std::chrono::milliseconds duration) inline
Definition at line 1013 of file HTTPSession.h.
Referenced by proxygen::HTTPSession::WriteSegment::writeErr().
{
       duration_ = duration;
     }
void proxygen::HTTPSession::FlowControlTimeout::timeoutExpired () inline override virtual noexcept
timeoutExpired() is invoked when the timeout has expired.
Implements folly::HHWheelTimer::Callback.
Definition at line 1005 of file HTTPSession.h.
References proxygen::HTTPSession::flowControlTimeoutExpired(), and proxygen::HTTPSession::WriteTimeout::session_.
{
       session_->flowControlTimeoutExpired();
     }
Member Data Documentation
std::chrono::milliseconds proxygen::HTTPSession::FlowControlTimeout::duration_ {std::chrono::milliseconds(0)} private
Definition at line 1018 of file HTTPSession.h.
HTTPSession* proxygen::HTTPSession::FlowControlTimeout::session_ private
Definition at line 1017 of file HTTPSession.h.
The documentation for this class was generated from the following file:
proxygen/lib/http/session/HTTPSession.h