proxygen: testing::gmock_matchers_test::ConvertibleToBool Class Reference
testing::gmock_matchers_test::ConvertibleToBool Class Reference
Public Member Functions
ConvertibleToBool (int number)
operator bool () const
ConvertibleToBool (int number)
operator bool () const
ConvertibleToBool (int number)
operator bool () const
Private Attributes
int number_
Detailed Description
Definition at line 2476 of file gmock-matchers_test.cc.
Constructor & Destructor Documentation
testing::gmock_matchers_test::ConvertibleToBool::ConvertibleToBool (int number) inline explicit
Definition at line 2478 of file gmock-matchers_test.cc.
 : number_(number) {}
testing::gmock_matchers_test::ConvertibleToBool::ConvertibleToBool (int number) inline explicit
Definition at line 2478 of file gmock-matchers_test.cc.
 : number_(number) {}
testing::gmock_matchers_test::ConvertibleToBool::ConvertibleToBool (int number) inline explicit
Definition at line 2478 of file gmock-matchers_test.cc.
 : number_(number) {}
Member Function Documentation
testing::gmock_matchers_test::ConvertibleToBool::operator bool () const inline
Definition at line 2479 of file gmock-matchers_test.cc.
 { return number_ != 0; }
testing::gmock_matchers_test::ConvertibleToBool::operator bool () const inline
Definition at line 2479 of file gmock-matchers_test.cc.
References testing::AllArgs(), testing::AllOf(), testing::gmock_matchers_test::Describe(), testing::Eq(), EXPECT_EQ, EXPECT_FALSE, EXPECT_THAT, EXPECT_TRUE, testing::ExplainMatchResult(), testing::Ge(), testing::Gt(), testing::gmock_matchers_test::IsNotZero(), testing::gmock_matchers_test::IsPositive(), testing::Lt(), std::tr1::make_tuple(), testing::gmock_matchers_test::MATCHER_P(), testing::internal::MatcherBase< T >::Matches(), testing::Matches(), testing::Not(), number, testing::gmock_matchers_test::PolymorphicIsEven(), testing::Ref(), testing::gmock_matchers_test::ReferencesFooAndIsZero(), testing::StartsWith(), testing::StringMatchResultListener::str(), testing::internal::TEST(), testing::Truly(), and testing::Value().
 { return number_ != 0; }
testing::gmock_matchers_test::ConvertibleToBool::operator bool () const inline
Definition at line 2479 of file gmock-matchers_test.cc.
References testing::AllArgs(), testing::AllOf(), testing::gmock_matchers_test::Describe(), testing::Eq(), EXPECT_EQ, EXPECT_FALSE, EXPECT_THAT, EXPECT_TRUE, testing::ExplainMatchResult(), testing::Ge(), testing::Gt(), testing::gmock_matchers_test::IsNotZero(), testing::gmock_matchers_test::IsPositive(), testing::Lt(), std::tr1::make_tuple(), testing::gmock_matchers_test::MATCHER_P(), testing::internal::MatcherBase< T >::Matches(), testing::Matches(), testing::Not(), number, testing::gmock_matchers_test::PolymorphicIsEven(), testing::Ref(), testing::gmock_matchers_test::ReferencesFooAndIsZero(), testing::StartsWith(), testing::StringMatchResultListener::str(), testing::internal::TEST(), testing::Truly(), and testing::Value().
 { return number_ != 0; }
Member Data Documentation
int testing::gmock_matchers_test::ConvertibleToBool::number_ private
Definition at line 2482 of file gmock-matchers_test.cc.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-matchers_test.cc