proxygen: folly::futures::Barrier Class Reference
folly::futures::Barrier Class Reference
#include <Barrier.h>
Classes
struct ControlBlock
struct ControlBlockAndPromise
Public Member Functions
Barrier (uint32_t n)
~Barrier ()
folly::Future< bool > wait ()
Private Types
typedef folly::Promise< bool > BoolPromise
Private Member Functions
ControlBlock * allocateControlBlock ()
void freeControlBlock (ControlBlock *b)
Static Private Member Functions
static BoolPromise * promises (ControlBlock *cb)
static size_t controlBlockSize (size_t n)
Private Attributes
uint32_t size_
std::atomic< ControlBlock * > controlBlock_
Static Private Attributes
static constexpr uint64_t kReaderShift = 32
static constexpr uint64_t kReader = uint64_t(1) << kReaderShift
static constexpr uint64_t kValueMask = kReader - 1
Detailed Description
Definition at line 45 of file Barrier.h.
Member Typedef Documentation
typedef folly::Promise<bool> folly::futures::Barrier::BoolPromise private
Definition at line 53 of file Barrier.h.
Constructor & Destructor Documentation
folly::futures::Barrier::Barrier (uint32_t n) explicit
Definition at line 23 of file Barrier.cpp.
     : size_(n), controlBlock_(allocateControlBlock()) {}
folly::futures::Barrier::~Barrier ()
Definition at line 26 of file Barrier.cpp.
References controlBlock_, freeControlBlock(), i, kReaderShift, kValueMask, promises(), uint32_t, and val.
                   {
   auto block = controlBlock_.load(std::memory_order_relaxed);
   auto prev = block->valueAndReaderCount.load(std::memory_order_relaxed);
   DCHECK_EQ(prev >> kReaderShift, 0u);
   auto val = prev & kValueMask;
   auto p = promises(block);
   for (uint32_t i = 0; i < val; ++i) {
     p[i].setException(
         folly::make_exception_wrapper<std::runtime_error>("Barrier destroyed"));
   }
   freeControlBlock(controlBlock_);
 }
Member Function Documentation
auto folly::futures::Barrier::allocateControlBlock () private
Definition at line 41 of file Barrier.cpp.
References controlBlockSize(), i, promises(), size_, and uint32_t.
Referenced by controlBlockSize(), and wait().
{
   auto storage = malloc(controlBlockSize(size_));
   if (!storage) {
     throw_exception<std::bad_alloc>();
   }
   auto block = ::new (storage) ControlBlock();
   auto p = promises(block);
   uint32_t i = 0;
   try {
     for (i = 0; i < size_; ++i) {
       new (p + i) BoolPromise();
     }
   } catch (...) {
     for (; i != 0; --i) {
       p[i - 1].~BoolPromise();
     }
     throw;
   }
   return block;
 }
static size_t folly::futures::Barrier::controlBlockSize (size_t n) inline static private
Definition at line 86 of file Barrier.h.
References allocateControlBlock(), b, freeControlBlock(), and promises().
Referenced by allocateControlBlock().
{
     return offsetof(ControlBlockAndPromise, promises) + n * sizeof(BoolPromise);
   }
void folly::futures::Barrier::freeControlBlock (ControlBlock * b) private
Definition at line 64 of file Barrier.cpp.
References bm::free(), i, promises(), size_, and uint32_t.
Referenced by controlBlockSize(), wait(), and ~Barrier().
{
   auto p = promises(block);
   for (uint32_t i = size_; i != 0; --i) {
     p[i - 1].~BoolPromise();
   }
   free(block);
 }
static BoolPromise* folly::futures::Barrier::promises (ControlBlock * cb) inline static private
Definition at line 82 of file Barrier.h.
Referenced by allocateControlBlock(), controlBlockSize(), freeControlBlock(), wait(), and ~Barrier().
{
     return reinterpret_cast<ControlBlockAndPromise*>(cb)->promises;
   }
folly::Future< bool > folly::futures::Barrier::wait ()
Definition at line 72 of file Barrier.cpp.
References allocateControlBlock(), controlBlock_, freeControlBlock(), i, kReader, kValueMask, promises(), size_, uint32_t, and uint64_t.
Referenced by folly::futures::test::TEST(), TEST_F(), and TYPED_TEST().
{
   // Load the current control block first. As we know there is at least
   // one thread in the current epoch (us), this means that the value is
   // < size_, so controlBlock_ can't change until we bump the value below.
   auto block = controlBlock_.load(std::memory_order_acquire);
   auto p = promises(block);
   // Bump the value and record ourselves as reader.
   // This ensures that block stays allocated, as the reader count is > 0.
   auto prev = block->valueAndReaderCount.fetch_add(
       kReader + 1, std::memory_order_acquire);
   auto prevValue = static_cast<uint32_t>(prev & kValueMask);
   DCHECK_LT(prevValue, size_);
   auto future = p[prevValue].getFuture();
   if (prevValue + 1 == size_) {
     // Need to reset the barrier before fulfilling any futures. This is
     // when the epoch is flipped to the next.
     controlBlock_.store(allocateControlBlock(), std::memory_order_release);
     p[0].setValue(true);
     for (uint32_t i = 1; i < size_; ++i) {
       p[i].setValue(false);
     }
   }
   // Free the control block if we're the last reader at max value.
   prev =
       block->valueAndReaderCount.fetch_sub(kReader, std::memory_order_acq_rel);
   if (prev == (kReader | uint64_t(size_))) {
     freeControlBlock(block);
   }
   return future;
 }
Member Data Documentation
std::atomic<ControlBlock*> folly::futures::Barrier::controlBlock_ private
Definition at line 94 of file Barrier.h.
Referenced by wait(), and ~Barrier().
constexpr uint64_t folly::futures::Barrier::kReader = uint64_t(1) << kReaderShift static private
Definition at line 56 of file Barrier.h.
Referenced by wait().
constexpr uint64_t folly::futures::Barrier::kReaderShift = 32 static private
Definition at line 55 of file Barrier.h.
Referenced by ~Barrier().
constexpr uint64_t folly::futures::Barrier::kValueMask = kReader - 1 static private
Definition at line 57 of file Barrier.h.
Referenced by wait(), and ~Barrier().
uint32_t folly::futures::Barrier::size_ private
Definition at line 93 of file Barrier.h.
Referenced by allocateControlBlock(), freeControlBlock(), and wait().
The documentation for this class was generated from the following files:
proxygen/folly/folly/futures/Barrier.h
proxygen/folly/folly/futures/Barrier.cpp