proxygen: folly::io::detail::Writable< Derived > Class Template Reference
folly::io::detail::Writable< Derived > Class Template Reference
#include <Cursor.h>
Public Member Functions
template<class T >
std::enable_if< std::is_arithmetic< T >::value >::type write (T value)
template<class T >
void writeBE (T value)
template<class T >
void writeLE (T value)
void push (const uint8_t *buf, size_t len)
void push (ByteRange buf)
size_t pushAtMost (ByteRange buf)
void push (Cursor cursor, size_t len)
size_t pushAtMost (Cursor cursor, size_t len)
Detailed Description
template<class Derived>
class folly::io::detail::Writable< Derived >
Definition at line 734 of file Cursor.h.
Member Function Documentation
template<class Derived> void folly::io::detail::Writable< Derived >::push (const uint8_t * buf, size_t len) inline
Definition at line 755 of file Cursor.h.
Referenced by proxygen::HPACKEncodeBuffer::append(), folly::bser::bserEncodeString(), proxygen::huffman::HuffTree::encode(), proxygen::HPACKEncodeBuffer::encodeLiteral(), fizz::server::AeadTokenCipher< AeadType, HkdfType >::encrypt(), runPushBenchmark(), TEST(), fizz::transformBufferBlocks(), fizz::detail::Writer< Random >::write(), proxygen::http2::writeAltSvc(), fizz::detail::writeBits24(), fizz::detail::writeBuf(), fizz::detail::writeBuf< bits24 >(), and fizz::detail::writeVector().
{
     Derived* d = static_cast<Derived*>(this);
     if (d->pushAtMost(buf, len) != len) {
       throw_exception<std::out_of_range>("overflow");
     }
   }
template<class Derived> void folly::io::detail::Writable< Derived >::push (ByteRange buf) inline
Definition at line 762 of file Cursor.h.
{
     if (this->pushAtMost(buf) != buf.size()) {
       throw_exception<std::out_of_range>("overflow");
     }
   }
template<class Derived> void folly::io::detail::Writable< Derived >::push (Cursor cursor, size_t len) inline
push len bytes of data from input cursor, data could be in an IOBuf chain. If input cursor contains less than len bytes, or this cursor has less than len bytes writable space, an out_of_range exception will be thrown.
Definition at line 778 of file Cursor.h.
{
     if (this->pushAtMost(cursor, len) != len) {
       throw_exception<std::out_of_range>("overflow");
     }
   }
template<class Derived> size_t folly::io::detail::Writable< Derived >::pushAtMost (ByteRange buf) inline
Definition at line 768 of file Cursor.h.
{
     Derived* d = static_cast<Derived*>(this);
     return d->pushAtMost(buf.data(), buf.size());
   }
template<class Derived> size_t folly::io::detail::Writable< Derived >::pushAtMost (Cursor cursor, size_t len) inline
Definition at line 784 of file Cursor.h.
{
     size_t written = 0;
     for (;;) {
       auto currentBuffer = cursor.peekBytes();
       const uint8_t* crtData = currentBuffer.data();
       size_t available = currentBuffer.size();
       if (available == 0) {
         // end of buffer chain
         return written;
       }
       // all data is in current buffer
       if (available >= len) {
         this->push(crtData, len);
         cursor.skip(len);
         return written + len;
       }
       // write the whole current IOBuf
       this->push(crtData, available);
       cursor.skip(available);
       written += available;
       len -= available;
     }
   }
template<class Derived> template<class T > std::enable_if<std::is_arithmetic<T>::value>::type folly::io::detail::Writable< Derived >::write (T value) inline
Definition at line 737 of file Cursor.h.
Referenced by makeBuf(), proxygen::makeBuf(), TEST(), and folly::TEST().
{
     const uint8_t* u8 = reinterpret_cast<const uint8_t*>(&value);
     Derived* d = static_cast<Derived*>(this);
     d->push(u8, sizeof(T));
   }
template<class Derived> template<class T > void folly::io::detail::Writable< Derived >::writeBE (T value) inline
Definition at line 744 of file Cursor.h.
Referenced by fizz::extensions::Validator::constructEcKeyFromBuf(), proxygen::SecondaryAuthManager::createAuthRequest(), proxygen::compress::QPACKScheme::encode(), proxygen::huffman::HuffTree::encode(), proxygen::SPDYCodec::generateDataFrame(), proxygen::SPDYCodec::generateGoaway(), proxygen::SPDYCodec::generatePingCommon(), proxygen::SPDYCodec::generateRstStream(), proxygen::SPDYCodec::generateSettings(), proxygen::SPDYCodec::generateWindowUpdate(), TEST(), TEST_F(), fizz::PlaintextWriteRecordLayer::write(), fizz::detail::Writer< U >::write(), fizz::EncryptedWriteRecordLayer::write(), fizz::detail::write< Extension >(), proxygen::http2::writeAltSvc(), proxygen::http2::writeCertificate(), proxygen::http2::writeCertificateRequest(), proxygen::http2::writeExHeaders(), writeFrameHeaderManual(), proxygen::http2::writeGoaway(), proxygen::http2::writePushPromise(), proxygen::http2::writeRstStream(), proxygen::http2::writeSettings(), fizz::detail::WriterVector< N, T >::writeVector(), fizz::detail::writeVector(), and proxygen::http2::writeWindowUpdate().
{
     Derived* d = static_cast<Derived*>(this);
     d->write(Endian::big(value));
   }
template<class Derived> template<class T > void folly::io::detail::Writable< Derived >::writeLE (T value) inline
Definition at line 750 of file Cursor.h.
Referenced by proxygen::SPDYCodec::generateSettings(), and TEST().
{
     Derived* d = static_cast<Derived*>(this);
     d->write(Endian::little(value));
   }
The documentation for this class was generated from the following file:
proxygen/folly/folly/io/Cursor.h