proxygen: folly::SubprocessSpawnError Class Reference
folly::SubprocessSpawnError Class Reference
#include <Subprocess.h>
Public Member Functions
SubprocessSpawnError (const char *executable, int errCode, int errnoValue)
~SubprocessSpawnError () override=default throw ()
int errnoValue () const
Private Attributes
int errnoValue_
Detailed Description
Exception thrown if the subprocess cannot be started.
Definition at line 254 of file Subprocess.h.
Constructor & Destructor Documentation
folly::SubprocessSpawnError::SubprocessSpawnError (const char * executable, int errCode, int errnoValue)
Definition at line 142 of file Subprocess.cpp.
References folly::ProcessReturnCode::EXITED, folly::ProcessReturnCode::exitStatus(), i, returnCode(), s, and folly::ProcessReturnCode::state().
Referenced by folly::Subprocess::readChildErrorPipe().
     : SubprocessError(
           toSubprocessSpawnErrorMessage(executable, errCode, errnoValue)),
       errnoValue_(errnoValue) {}
folly::SubprocessSpawnError::~SubprocessSpawnError () throw () override default
Member Function Documentation
int folly::SubprocessSpawnError::errnoValue () const inline
Definition at line 258 of file Subprocess.h.
Referenced by folly::Subprocess::spawnInternal(), and TEST().
{
     return errnoValue_;
   }
Member Data Documentation
int folly::SubprocessSpawnError::errnoValue_ private
Definition at line 263 of file Subprocess.h.
The documentation for this class was generated from the following files:
proxygen/folly/folly/Subprocess.h
proxygen/folly/folly/Subprocess.cpp