proxygen: folly::gen::detail::Min< Selector, Comparer > Class Template Reference
folly::gen::detail::Min< Selector, Comparer > Class Template Reference
#include <Base-inl.h>
Public Member Functions
Min ()=default
Min (Selector selector)
Min (Selector selector, Comparer comparer)
template<class Value , class Source , class StorageType = typename std::decay<Value>::type, class Key = typename std::decay<invoke_result_t<Selector, Value>>::type>
Optional< StorageType > compose (const GenImpl< Value, Source > &source) const
Public Member Functions inherited from folly::gen::Operator< Min< Selector, Comparer > >
ResultGen compose (const GenImpl< Value, Source > &source) const
Public Member Functions inherited from folly::gen::FBounded< Self >
const Self & self () const
Self & self ()
Private Member Functions
template<typename T >
const T & asConst (const T &t) const
Private Attributes
Selector selector_
Comparer comparer_
Additional Inherited Members
Protected Member Functions inherited from folly::gen::Operator< Min< Selector, Comparer > >
Operator ()=default
Operator (Operator &&) noexcept=default
Operator (const Operator &)=default
Operator & operator= (Operator &&) noexcept=default
Operator & operator= (const Operator &)=default
Detailed Description
template<class Selector, class Comparer>
class folly::gen::detail::Min< Selector, Comparer >
Min - For a value which minimizes a key, where the key is determined by a given selector, and compared by given comparer.
This type is usually used through the singletone 'min' or through the helper functions 'minBy' and 'maxBy'.
auto oldest = from(people) | minBy([](Person& p) { return p.dateOfBirth; });
Definition at line 2213 of file Base-inl.h.
Constructor & Destructor Documentation
template<class Selector , class Comparer > folly::gen::detail::Min< Selector, Comparer >::Min () default
template<class Selector , class Comparer > folly::gen::detail::Min< Selector, Comparer >::Min (Selector selector) inline explicit
Definition at line 2225 of file Base-inl.h.
 : selector_(std::move(selector)) {}
template<class Selector , class Comparer > folly::gen::detail::Min< Selector, Comparer >::Min (Selector selector, Comparer comparer) inline
Definition at line 2227 of file Base-inl.h.
References testing::Key(), type, and testing::Value().
       : selector_(std::move(selector)), comparer_(std::move(comparer)) {}
Member Function Documentation
template<class Selector , class Comparer > template<typename T > const T& folly::gen::detail::Min< Selector, Comparer >::asConst (const T & t) const inline private
Definition at line 2218 of file Base-inl.h.
References folly::pushmi::detail::t.
{
     return t;
   }
template<class Selector , class Comparer > template<class Value , class Source , class StorageType = typename std::decay<Value>::type, class Key = typename std::decay<invoke_result_t<Selector, Value>>::type> Optional<StorageType> folly::gen::detail::Min< Selector, Comparer >::compose (const GenImpl< Value, Source > & source) const inline
Definition at line 2235 of file Base-inl.h.
References folly::Optional< Value >::get_pointer(), min, folly::gen::move, v, and testing::Value().
{
     static_assert(
         !Source::infinite,
         "Calling min or max on an infinite source will cause "
         "an infinite loop.");
     Optional<StorageType> min;
     Optional<Key> minKey;
     source | [&](Value v) {
       Key key = selector_(asConst(v)); // so that selector_ cannot mutate v
       if (auto lastKey = minKey.get_pointer()) {
         if (!comparer_(key, *lastKey)) {
           return;
         }
       }
       minKey = std::move(key);
       min = std::forward<Value>(v);
     };
     return min;
   }
Member Data Documentation
template<class Selector , class Comparer > Comparer folly::gen::detail::Min< Selector, Comparer >::comparer_ private
Definition at line 2215 of file Base-inl.h.
template<class Selector , class Comparer > Selector folly::gen::detail::Min< Selector, Comparer >::selector_ private
Definition at line 2214 of file Base-inl.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/gen/Base-inl.h