proxygen: folly::fibers::Baton::TimeoutHandler Class Reference
folly::fibers::Baton::TimeoutHandler Class Reference
#include <Baton.h>
Public Member Functions
void scheduleTimeout (TimeoutController::Duration timeoutMs)
Private Member Functions
void cancelTimeout ()
Private Attributes
std::function< void()> timeoutFunc_ {nullptr}
FiberManager * fiberManager_ {nullptr}
intptr_t timeoutPtr_ {0}
Friends
class Baton
Detailed Description
Provides a way to schedule a wakeup for a wait()ing fiber. A TimeoutHandler must be passed to Baton::wait(TimeoutHandler&) before a timeout is scheduled. It is only safe to use the TimeoutHandler on the same thread as the wait()ing fiber. scheduleTimeout() may only be called once prior to the end of the associated Baton's life.
Definition at line 218 of file Baton.h.
Member Function Documentation
void folly::fibers::Baton::TimeoutHandler::cancelTimeout () private
Definition at line 204 of file Baton.cpp.
Referenced by folly::fibers::Baton::wait().
{
   if (timeoutPtr_) {
     fiberManager_->timeoutManager_->cancel(timeoutPtr_);
   }
 }
void folly::fibers::Baton::TimeoutHandler::scheduleTimeout (TimeoutController::Duration timeoutMs)
Definition at line 192 of file Baton.cpp.
Referenced by TEST().
{
   assert(fiberManager_ != nullptr);
   assert(timeoutFunc_ != nullptr);
   assert(timeoutPtr_ == 0);
   if (timeout.count() > 0) {
     timeoutPtr_ =
         fiberManager_->timeoutManager_->registerTimeout(timeoutFunc_, timeout);
   }
 }
Friends And Related Function Documentation
friend class Baton friend
Definition at line 223 of file Baton.h.
Member Data Documentation
FiberManager* folly::fibers::Baton::TimeoutHandler::fiberManager_ {nullptr} private
Definition at line 228 of file Baton.h.
Referenced by folly::fibers::Baton::wait().
std::function<void()> folly::fibers::Baton::TimeoutHandler::timeoutFunc_ {nullptr} private
Definition at line 227 of file Baton.h.
Referenced by folly::fibers::Baton::wait().
intptr_t folly::fibers::Baton::TimeoutHandler::timeoutPtr_ {0} private
Definition at line 230 of file Baton.h.
Referenced by folly::fibers::Baton::wait().
The documentation for this class was generated from the following files:
proxygen/folly/folly/fibers/Baton.h
proxygen/folly/folly/fibers/Baton.cpp