proxygen: testing::internal::MatcherBase< T > Class Template Reference
testing::internal::MatcherBase< T > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
bool MatchAndExplain (T x, MatchResultListener *listener) const
bool Matches (T x) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
void ExplainMatchResultTo (T x,::std::ostream *os) const
const MatcherDescriberInterface * GetDescriber () const
bool MatchAndExplain (T x, MatchResultListener *listener) const
bool Matches (T x) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
void ExplainMatchResultTo (T x,::std::ostream *os) const
const MatcherDescriberInterface * GetDescriber () const
bool MatchAndExplain (T x, MatchResultListener *listener) const
bool Matches (T x) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
void ExplainMatchResultTo (T x,::std::ostream *os) const
const MatcherDescriberInterface * GetDescriber () const
Protected Member Functions
MatcherBase ()
MatcherBase (const MatcherInterface< T > *impl)
virtual ~MatcherBase ()
MatcherBase ()
MatcherBase (const MatcherInterface< T > *impl)
virtual ~MatcherBase ()
MatcherBase ()
MatcherBase (const MatcherInterface< T > *impl)
virtual ~MatcherBase ()
Private Attributes
::testing::internal::linked_ptr< const MatcherInterface< T > > impl_
Detailed Description
template<typename T>
class testing::internal::MatcherBase< T >
Definition at line 252 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename T> testing::internal::MatcherBase< T >::MatcherBase () inline protected
Definition at line 288 of file gmock-matchers.h.
 {}
template<typename T> testing::internal::MatcherBase< T >::MatcherBase (const MatcherInterface< T > * impl) inline explicit protected
Definition at line 291 of file gmock-matchers.h.
       : impl_(impl) {}
template<typename T> virtual testing::internal::MatcherBase< T >::~MatcherBase () inline protected virtual
Definition at line 294 of file gmock-matchers.h.
 {}
template<typename T> testing::internal::MatcherBase< T >::MatcherBase () inline protected
Definition at line 288 of file gmock-matchers.h.
 {}
template<typename T> testing::internal::MatcherBase< T >::MatcherBase (const MatcherInterface< T > * impl) inline explicit protected
Definition at line 291 of file gmock-matchers.h.
       : impl_(impl) {}
template<typename T> virtual testing::internal::MatcherBase< T >::~MatcherBase () inline protected virtual
Definition at line 294 of file gmock-matchers.h.
 {}
template<typename T> testing::internal::MatcherBase< T >::MatcherBase () inline protected
Definition at line 288 of file gmock-matchers.h.
 {}
template<typename T> testing::internal::MatcherBase< T >::MatcherBase (const MatcherInterface< T > * impl) inline explicit protected
Definition at line 291 of file gmock-matchers.h.
       : impl_(impl) {}
template<typename T> virtual testing::internal::MatcherBase< T >::~MatcherBase () inline protected virtual
Definition at line 294 of file gmock-matchers.h.
 {}
Member Function Documentation
template<typename T> void testing::internal::MatcherBase< T >::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 270 of file gmock-matchers.h.
Referenced by testing::gmock_matchers_test::DescribeNegation(), and testing::gmock_matchers_test::GreaterThanMatcher::MatchAndExplain().
{
     impl_->DescribeNegationTo(os);
   }
template<typename T> void testing::internal::MatcherBase< T >::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 270 of file gmock-matchers.h.
{
     impl_->DescribeNegationTo(os);
   }
template<typename T> void testing::internal::MatcherBase< T >::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 270 of file gmock-matchers.h.
{
     impl_->DescribeNegationTo(os);
   }
template<typename T> void testing::internal::MatcherBase< T >::DescribeTo (::std::ostream * os) const inline
Definition at line 267 of file gmock-matchers.h.
 { impl_->DescribeTo(os); }
template<typename T> void testing::internal::MatcherBase< T >::DescribeTo (::std::ostream * os) const inline
Definition at line 267 of file gmock-matchers.h.
Referenced by testing::gmock_matchers_test::Describe(), testing::gmock_matchers_test::GreaterThanMatcher::MatchAndExplain(), and testing::internal::PredicateFormatterFromMatcher< M >::operator()().
 { impl_->DescribeTo(os); }
template<typename T> void testing::internal::MatcherBase< T >::DescribeTo (::std::ostream * os) const inline
Definition at line 267 of file gmock-matchers.h.
 { impl_->DescribeTo(os); }
template<typename T> void testing::internal::MatcherBase< T >::ExplainMatchResultTo (T x, ::std::ostream * os) const inline
Definition at line 275 of file gmock-matchers.h.
{
     StreamMatchResultListener listener(os);
     MatchAndExplain(x, &listener);
   }
template<typename T> void testing::internal::MatcherBase< T >::ExplainMatchResultTo (T x, ::std::ostream * os) const inline
Definition at line 275 of file gmock-matchers.h.
{
     StreamMatchResultListener listener(os);
     MatchAndExplain(x, &listener);
   }
template<typename T> void testing::internal::MatcherBase< T >::ExplainMatchResultTo (T x, ::std::ostream * os) const inline
Definition at line 275 of file gmock-matchers.h.
{
     StreamMatchResultListener listener(os);
     MatchAndExplain(x, &listener);
   }
template<typename T> const MatcherDescriberInterface* testing::internal::MatcherBase< T >::GetDescriber () const inline
Definition at line 283 of file gmock-matchers.h.
{
     return impl_.get();
   }
template<typename T> const MatcherDescriberInterface* testing::internal::MatcherBase< T >::GetDescriber () const inline
Definition at line 283 of file gmock-matchers.h.
{
     return impl_.get();
   }
template<typename T> const MatcherDescriberInterface* testing::internal::MatcherBase< T >::GetDescriber () const inline
Definition at line 283 of file gmock-matchers.h.
{
     return impl_.get();
   }
template<typename T> bool testing::internal::MatcherBase< T >::MatchAndExplain (T x, MatchResultListener * listener) const inline
Definition at line 256 of file gmock-matchers.h.
{
     return impl_->MatchAndExplain(x, listener);
   }
template<typename T> bool testing::internal::MatcherBase< T >::MatchAndExplain (T x, MatchResultListener * listener) const inline
Definition at line 256 of file gmock-matchers.h.
{
     return impl_->MatchAndExplain(x, listener);
   }
template<typename T> bool testing::internal::MatcherBase< T >::MatchAndExplain (T x, MatchResultListener * listener) const inline
Definition at line 256 of file gmock-matchers.h.
Referenced by testing::SafeMatcherCastImpl< T >::Cast(), testing::gmock_matchers_test::NewEvenMatcherImpl::DescribeTo(), testing::internal::MatchPrintAndExplain(), and testing::gmock_matchers_test::TEST().
{
     return impl_->MatchAndExplain(x, listener);
   }
template<typename T> bool testing::internal::MatcherBase< T >::Matches (T x) const inline
Definition at line 261 of file gmock-matchers.h.
{
     DummyMatchResultListener dummy;
     return MatchAndExplain(x, &dummy);
   }
template<typename T> bool testing::internal::MatcherBase< T >::Matches (T x) const inline
Definition at line 261 of file gmock-matchers.h.
{
     DummyMatchResultListener dummy;
     return MatchAndExplain(x, &dummy);
   }
template<typename T> bool testing::internal::MatcherBase< T >::Matches (T x) const inline
Definition at line 261 of file gmock-matchers.h.
Referenced by testing::gmock_matchers_test::AllOfMatches(), testing::gmock_matchers_test::AnyOfMatches(), testing::gmock_matchers_test::AStruct::AStruct(), testing::SafeMatcherCastImpl< T >::Cast(), testing::gmock_matchers_test::ConvertibleFromAny::ConvertibleFromAny(), testing::gmock_matchers_test::Derived::Derived(), testing::gmock_matchers_test::ReferencesBarOrIsZeroImpl::DescribeNegationTo(), testing::gmock_matchers_test::NewEvenMatcherImpl::DescribeTo(), testing::gmock_matchers_test::IntReferenceWrapper::IntReferenceWrapper(), testing::gmock_matchers_test::Type< T >::IsTypeOf(), testing::gmock_matchers_test::DerivedClass::k(), testing::gmock_matchers_test::PolymorphicIsEvenImpl::MatchAndExplain(), testing::gmock_matchers_test::MATCHER_P(), testing::internal::MatchPrintAndExplain(), testing::gmock_matchers_test::ConvertibleToBool::operator bool(), testing::gmock_matchers_test::IsGreaterThan::operator()(), testing::gmock_matchers_test::Functor::operator()(), testing::gmock_matchers_test::PolymorphicFunctor::operator()(), testing::gmock_matchers_test::ReferencingFunctor::operator()(), testing::gmock_matchers_test::ConstPropagatingPtr< T >::operator*(), testing::gmock_matchers_test::NotCopyable::operator>=(), testing::gmock_matchers_test::TEST(), TEST(), testing::gmock_matchers_test::TEST_F(), testing::gmock_matchers_test::FloatingPointTest< RawType >::TestMatches(), testing::gmock_matchers_test::FloatingPointNearTest< RawType >::TestNearMatches(), testing::gmock_matchers_test::Unprintable::Unprintable(), and testing::gmock_matchers_test::IntValue::value().
{
     DummyMatchResultListener dummy;
     return MatchAndExplain(x, &dummy);
   }
Member Data Documentation
template<typename T> testing::internal::linked_ptr< const MatcherInterface< T > > testing::internal::MatcherBase< T >::impl_ private
Definition at line 308 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h