proxygen: folly::f14::detail::F14BasicSet< K, H, E, A > Class Template Reference
folly::f14::detail::F14BasicSet< K, H, E, A > Class Template Reference
#include <F14Set.h>
Public Member Functions
F14BasicSet ()=default
std::size_t getAllocatedMemorySize () const
template<typename V >
void visitAllocationClasses (V &&visitor) const
template<typename V >
void visitContiguousRanges (V &&visitor) const
Private Types
using Super = std::unordered_set< K, H, E, A >
Detailed Description
template<typename K, typename H, typename E, typename A>
class folly::f14::detail::F14BasicSet< K, H, E, A >
Definition at line 49 of file F14Set.h.
Member Typedef Documentation
template<typename K, typename H, typename E, typename A> using folly::f14::detail::F14BasicSet< K, H, E, A >::Super = std::unordered_set<K, H, E, A> private
Definition at line 50 of file F14Set.h.
Constructor & Destructor Documentation
template<typename K, typename H, typename E, typename A> folly::f14::detail::F14BasicSet< K, H, E, A >::F14BasicSet () default
Referenced by folly::F14VectorSet< Key, Hasher, KeyEqual, Alloc >::operator=().
Member Function Documentation
template<typename K, typename H, typename E, typename A> std::size_t folly::f14::detail::F14BasicSet< K, H, E, A >::getAllocatedMemorySize () const inline
Definition at line 63 of file F14Set.h.
Referenced by folly::F14VectorSet< Key, Hasher, KeyEqual, Alloc >::operator=().
{
     std::size_t rv = 0;
     visitAllocationClasses(
         [&](std::size_t bytes, std::size_t n) { rv += bytes * n; });
     return rv;
   }
template<typename K, typename H, typename E, typename A> template<typename V > void folly::f14::detail::F14BasicSet< K, H, E, A >::visitAllocationClasses (V && visitor) const inline
Definition at line 72 of file F14Set.h.
Referenced by folly::f14::detail::F14BasicSet< Key, Hasher, KeyEqual, Alloc >::getAllocatedMemorySize(), and folly::F14VectorSet< Key, Hasher, KeyEqual, Alloc >::operator=().
{
     auto bc = this->bucket_count();
     if (bc > 1) {
       visitor(bc * sizeof(pointer), 1);
     }
     if (this->size() > 0) {
       visitor(sizeof(StdNodeReplica<K, value_type, H>), this->size());
     }
   }
template<typename K, typename H, typename E, typename A> template<typename V > void folly::f14::detail::F14BasicSet< K, H, E, A >::visitContiguousRanges (V && visitor) const inline
Definition at line 83 of file F14Set.h.
Referenced by folly::F14VectorSet< Key, Hasher, KeyEqual, Alloc >::operator=().
{
     for (value_type const& entry : *this) {
       value_type const* b = std::addressof(entry);
       visitor(b, b + 1);
     }
   }
The documentation for this class was generated from the following file:
proxygen/folly/folly/container/F14Set.h