proxygen: wangle::FilePoller Class Reference
wangle::FilePoller Class Reference
#include <FilePoller.h>
Classes
struct FileData
struct FileModificationData
class ThreadProtector
Public Types
using Cob = std::function< void()>
using Condition = std::function< bool(const FileModificationData &, const FileModificationData &)>
Public Member Functions
FilePoller (std::chrono::milliseconds pollInterval=kDefaultPollInterval)
virtual ~FilePoller ()
FilePoller (const FilePoller &other)=delete
FilePoller & operator= (const FilePoller &other)=delete
FilePoller (FilePoller &&other)=delete
FilePoller && operator= (FilePoller &&other)=delete
void addFileToTrack (const std::string &fileName, Cob yCob, Cob nCob=nullptr, Condition condition=fileTouchedCondInternal)
void removeFileToTrack (const std::string &fileName)
void stop ()
Static Public Member Functions
static Condition fileTouchedWithinCond (std::chrono::seconds expireTime)
static Condition doAlwaysCond ()
static Condition fileTouchedCond ()
Protected Member Functions
virtual FileModificationData getFileModData (const std::string &path) noexcept
Private Types
using FileDatas = std::unordered_map< std::string, FileData >
Private Member Functions
void checkFiles () noexcept
void initFileData (const std::string &fName, FileData &fData) noexcept
void init (std::chrono::milliseconds pollInterval)
Static Private Member Functions
static bool fileTouchedWithinCondInternal (const FilePoller::FileModificationData &, const FilePoller::FileModificationData &fModData, std::chrono::seconds expireTime)
static bool doAlwaysCondInternal (const FileModificationData &, const FileModificationData &)
static bool fileTouchedCondInternal (const FileModificationData &oldModData, const FileModificationData &modData)
Private Attributes
FileDatas fileDatum_
std::mutex filesMutex_
uint64_t pollerId_ {0}
std::shared_ptr< folly::FunctionScheduler > scheduler_
Static Private Attributes
static constexpr std::chrono::milliseconds kDefaultPollInterval
Detailed Description
Polls for updates in the files. This poller uses modified times to track changes in the files, so it is the responsibility of the caller to check whether the contents have actually changed. It also assumes that when the file is modified, the modfied time changes. This is a reasonable assumption to make, so it should not be used in situations where files may be modified without changing the modified time.
Definition at line 41 of file FilePoller.h.
Member Typedef Documentation
using wangle::FilePoller::Cob = std::function<void()>
Definition at line 50 of file FilePoller.h.
using wangle::FilePoller::Condition = std::function< bool(const FileModificationData&, const FileModificationData&)>
Definition at line 54 of file FilePoller.h.
using wangle::FilePoller::FileDatas = std::unordered_map<std::string, FileData> private
Definition at line 113 of file FilePoller.h.
Constructor & Destructor Documentation
wangle::FilePoller::FilePoller (std::chrono::milliseconds pollInterval = kDefaultPollInterval) explicit
Definition at line 65 of file FilePoller.cpp.
References folly::init().
{
   init(pollInterval);
 }
wangle::FilePoller::~FilePoller () virtual
Definition at line 69 of file FilePoller.cpp.
References stop().
 { stop(); }
wangle::FilePoller::FilePoller (const FilePoller & other) delete
wangle::FilePoller::FilePoller (FilePoller && other) delete
Member Function Documentation
void wangle::FilePoller::addFileToTrack (const std::string & fileName, Cob yCob, Cob nCob = nullptr, Condition condition = fileTouchedCondInternal)
Definition at line 115 of file FilePoller.cpp.
Referenced by wangle::MultiFilePoller::registerFiles(), and TEST_F().
{
   if (fileName.empty()) {
     // ignore empty file paths
     return;
   }
   if (ThreadProtector::inPollerThread()) {
     LOG(ERROR) << "Adding files from a callback is disallowed";
     return;
   }
   std::lock_guard<std::mutex> lg(filesMutex_);
   fileDatum_[fileName] = FileData(yCob, nCob, condition);
   initFileData(fileName, fileDatum_[fileName]);
 }
void wangle::FilePoller::checkFiles () private noexcept
Definition at line 92 of file FilePoller.cpp.
References folly::pushmi::__adl::tp.
Referenced by fileTouchedCondInternal().
{
   std::lock_guard<std::mutex> lg(filesMutex_);
   ThreadProtector tp;
   for (auto& fData : fileDatum_) {
     auto modData = getFileModData(fData.first);
     auto& fileData = fData.second;
     if (fileData.condition(fileData.modData, modData) && fileData.yCob) {
       fileData.yCob();
     } else if (fileData.nCob) {
       fileData.nCob();
     }
     fileData.modData = modData;
   }
 }
static Condition wangle::FilePoller::doAlwaysCond () inline static
Definition at line 88 of file FilePoller.h.
References doAlwaysCondInternal().
{
     return doAlwaysCondInternal;
   }
static bool wangle::FilePoller::doAlwaysCondInternal (const FileModificationData & , const FileModificationData &) inline static private
Definition at line 123 of file FilePoller.h.
Referenced by doAlwaysCond().
{
     return true;
   }
static Condition wangle::FilePoller::fileTouchedCond () inline static
Definition at line 92 of file FilePoller.h.
References fileTouchedCondInternal(), getFileModData(), folly::pushmi::__adl::noexcept(), and string.
{
     return fileTouchedCondInternal;
   }
static bool wangle::FilePoller::fileTouchedCondInternal (const FileModificationData & oldModData, const FileModificationData & modData) inline static private
Definition at line 129 of file FilePoller.h.
References checkFiles(), wangle::FilePoller::FileModificationData::exists, init(), initFileData(), wangle::FilePoller::FileModificationData::modTime, folly::pushmi::__adl::noexcept(), and string.
Referenced by fileTouchedCond().
{
     const bool fileStillExists = oldModData.exists && modData.exists;
     const bool fileTouched = modData.modTime != oldModData.modTime;
     const bool fileCreated = !oldModData.exists && modData.exists;
     return (fileStillExists && fileTouched) || fileCreated;
   }
static Condition wangle::FilePoller::fileTouchedWithinCond (std::chrono::seconds expireTime) inline static
Definition at line 80 of file FilePoller.h.
References folly::netops::bind(), and fileTouchedWithinCondInternal().
{
     return std::bind(
         fileTouchedWithinCondInternal,
         std::placeholders::_1,
         std::placeholders::_2,
         expireTime);
   }
static bool wangle::FilePoller::fileTouchedWithinCondInternal (const FilePoller::FileModificationData & , const FilePoller::FileModificationData & fModData, std::chrono::seconds expireTime) inline static private
Definition at line 115 of file FilePoller.h.
References wangle::FilePoller::FileModificationData::exists, wangle::FilePoller::FileModificationData::modTime, and folly::detail::distributed_mutex::time().
Referenced by fileTouchedWithinCond().
{
     return fModData.exists &&
         (time(nullptr) < fModData.modTime + expireTime.count());
   }
FilePoller::FileModificationData wangle::FilePoller::getFileModData (const std::string & path) protected virtual noexcept
Reimplemented in NoDiskPoller.
Definition at line 146 of file FilePoller.cpp.
References deadlock::info().
Referenced by fileTouchedCond().
{
   struct stat info;
   int ret = stat(path.c_str(), &info);
   if (ret != 0) {
     return FileModificationData{false, 0};
   }
   return FileModificationData{true, info.st_mtime};
 }
void wangle::FilePoller::init (std::chrono::milliseconds pollInterval) private
Definition at line 71 of file FilePoller.cpp.
References context.
Referenced by fileTouchedCondInternal().
{
   auto context = contextSingleton.try_get();
   if (!context) {
     LOG(ERROR) << "Poller context requested after destruction.";
     return;
   }
   pollerId_ = context->getNextId();
   scheduler_ = context->getScheduler();
   scheduler_->addFunction(
       [this] { this->checkFiles(); },
       pollInterval,
       folly::to<std::string>(pollerId_));
 }
void wangle::FilePoller::initFileData (const std::string & fName, FileData & fData) private noexcept
Definition at line 107 of file FilePoller.cpp.
Referenced by fileTouchedCondInternal().
{
   auto modData = getFileModData(fName);
   fData.modData.exists = modData.exists;
   fData.modData.modTime = modData.modTime;
 }
FilePoller& wangle::FilePoller::operator= (const FilePoller & other) delete
FilePoller&& wangle::FilePoller::operator= (FilePoller && other) delete
void wangle::FilePoller::removeFileToTrack (const std::string & fileName)
Definition at line 133 of file FilePoller.cpp.
Referenced by wangle::MultiFilePoller::cancelCallback().
{
   if (fileName.empty()) {
     // ignore
     return;
   }
   if (ThreadProtector::inPollerThread()) {
     LOG(ERROR) << "Adding files from a callback is disallowed";
     return;
   }
   std::lock_guard<std::mutex> lg(filesMutex_);
   fileDatum_.erase(fileName);
 }
void wangle::FilePoller::stop ()
Definition at line 85 of file FilePoller.cpp.
                       {
   if (scheduler_) {
     scheduler_->cancelFunctionAndWait(
         folly::to<std::string>(pollerId_));
   }
 }
Member Data Documentation
FileDatas wangle::FilePoller::fileDatum_ private
Definition at line 143 of file FilePoller.h.
std::mutex wangle::FilePoller::filesMutex_ private
Definition at line 146 of file FilePoller.h.
constexpr std::chrono::milliseconds wangle::FilePoller::kDefaultPollInterval static private
Initial value:
=
        std::chrono::milliseconds(10000)
Definition at line 100 of file FilePoller.h.
uint64_t wangle::FilePoller::pollerId_ {0} private
Definition at line 148 of file FilePoller.h.
std::shared_ptr<folly::FunctionScheduler> wangle::FilePoller::scheduler_ private
Definition at line 153 of file FilePoller.h.
The documentation for this class was generated from the following files:
proxygen/wangle/wangle/util/FilePoller.h
proxygen/wangle/wangle/util/FilePoller.cpp