proxygen: folly::test::Server Class Reference
folly::test::Server Class Reference
Public Member Functions
Server ()
void stop (bool abortive)
void join ()
int port () const
int closeClients (bool abortive)
Private Types
enum StopMode { NO_STOP, ORDERLY, ABORTIVE }
Private Attributes
int acceptSocket_
int port_
std::atomic< StopMode > stop_
std::thread serverThread_
std::vector< int > fds_
Detailed Description
Definition at line 36 of file ShutdownSocketSetTest.cpp.
Member Enumeration Documentation
enum folly::test::Server::StopMode private
Enumerator
NO_STOP
ORDERLY
ABORTIVE
Definition at line 50 of file ShutdownSocketSetTest.cpp.
 { NO_STOP, ORDERLY, ABORTIVE };
Constructor & Destructor Documentation
folly::test::Server::Server ()
Definition at line 56 of file ShutdownSocketSetTest.cpp.
References ABORTIVE, folly::netops::accept(), acceptSocket_, folly::ShutdownSocketSet::add(), addr, folly::netops::bind(), folly::ShutdownSocketSet::close(), closeClients(), fds_, folly::netops::getsockname(), folly::netops::listen(), NO_STOP, port_, serverThread_, folly::netops::socket(), and stop_.
                : acceptSocket_(-1), port_(0), stop_(NO_STOP) {
   acceptSocket_ = fsp::socket(PF_INET, SOCK_STREAM, 0);
   CHECK_ERR(acceptSocket_);
   shutdownSocketSet.add(acceptSocket_);
   sockaddr_in addr;
   addr.sin_family = AF_INET;
   addr.sin_port = 0;
   addr.sin_addr.s_addr = INADDR_ANY;
   CHECK_ERR(bind(
       acceptSocket_, reinterpret_cast<const sockaddr*>(&addr), sizeof(addr)));
   CHECK_ERR(listen(acceptSocket_, 10));
   socklen_t addrLen = sizeof(addr);
   CHECK_ERR(
       getsockname(acceptSocket_, reinterpret_cast<sockaddr*>(&addr), &addrLen));
   port_ = ntohs(addr.sin_port);
   serverThread_ = std::thread([this] {
     while (stop_ == NO_STOP) {
       sockaddr_in peer;
       socklen_t peerLen = sizeof(peer);
       int fd =
           accept(acceptSocket_, reinterpret_cast<sockaddr*>(&peer), &peerLen);
       if (fd == -1) {
         if (errno == EINTR) {
           continue;
         }
         if (errno == EINVAL || errno == ENOTSOCK) { // socket broken
           break;
         }
       }
       CHECK_ERR(fd);
       shutdownSocketSet.add(fd);
       fds_.push_back(fd);
     }
     if (stop_ != NO_STOP) {
       closeClients(stop_ == ABORTIVE);
     }
     shutdownSocketSet.close(acceptSocket_);
     acceptSocket_ = -1;
     port_ = 0;
   });
 }
Member Function Documentation
int folly::test::Server::closeClients (bool abortive)
Definition at line 105 of file ShutdownSocketSetTest.cpp.
References folly::ShutdownSocketSet::close(), fds_, and folly::netops::setsockopt().
Referenced by port(), folly::test::runCloseTest(), folly::test::runKillTest(), and Server().
{
   for (int fd : fds_) {
     if (abortive) {
       struct linger l = {1, 0};
       CHECK_ERR(setsockopt(fd, SOL_SOCKET, SO_LINGER, &l, sizeof(l)));
     }
     shutdownSocketSet.close(fd);
   }
   int n = fds_.size();
   fds_.clear();
   return n;
 }
void folly::test::Server::join ()
Definition at line 123 of file ShutdownSocketSetTest.cpp.
References serverThread_.
Referenced by folly::test::runCloseTest(), and folly::test::runKillTest().
                   {
   serverThread_.join();
 }
int folly::test::Server::port () const inline
Definition at line 42 of file ShutdownSocketSetTest.cpp.
References closeClients(), and port_.
Referenced by folly::test::runCloseTest(), and folly::test::runKillTest().
                    {
     return port_;
   }
void folly::test::Server::stop (bool abortive)
Definition at line 118 of file ShutdownSocketSetTest.cpp.
References ABORTIVE, acceptSocket_, ORDERLY, folly::shutdown(), and stop_.
Referenced by folly::test::runCloseTest().
{
   stop_ = abortive ? ABORTIVE : ORDERLY;
   shutdown(acceptSocket_, SHUT_RDWR);
 }
Member Data Documentation
int folly::test::Server::acceptSocket_ private
Definition at line 48 of file ShutdownSocketSetTest.cpp.
Referenced by Server(), and stop().
std::vector<int> folly::test::Server::fds_ private
Definition at line 53 of file ShutdownSocketSetTest.cpp.
Referenced by closeClients(), and Server().
int folly::test::Server::port_ private
Definition at line 49 of file ShutdownSocketSetTest.cpp.
Referenced by port(), and Server().
std::thread folly::test::Server::serverThread_ private
Definition at line 52 of file ShutdownSocketSetTest.cpp.
Referenced by join(), and Server().
std::atomic<StopMode> folly::test::Server::stop_ private
Definition at line 51 of file ShutdownSocketSetTest.cpp.
Referenced by Server(), and stop().
The documentation for this class was generated from the following file:
proxygen/folly/folly/io/test/ShutdownSocketSetTest.cpp