proxygen: folly::symbolizer::Dwarf::LineNumberVM Class Reference
folly::symbolizer::Dwarf::LineNumberVM Class Reference
Classes
struct FileName
Public Member Functions
LineNumberVM (folly::StringPiece data, folly::StringPiece compilationDirectory)
bool findAddress (uintptr_t address, Path &file, uint64_t &line)
Private Types
enum StepResult { CONTINUE, COMMIT, END }
Private Member Functions
void init ()
void reset ()
bool next (folly::StringPiece &program)
StepResult step (folly::StringPiece &program)
FileName getFileName (uint64_t index) const
folly::StringPiece getIncludeDirectory (uint64_t index) const
bool nextDefineFile (folly::StringPiece &program, FileName &fn) const
Static Private Member Functions
static bool readFileName (folly::StringPiece &sp, FileName &fn)
Private Attributes
bool is64Bit_
folly::StringPiece data_
folly::StringPiece compilationDirectory_
uint16_t version_
uint8_t minLength_
bool defaultIsStmt_
int8_t lineBase_
uint8_t lineRange_
uint8_t opcodeBase_
const uint8_t * standardOpcodeLengths_
folly::StringPiece includeDirectories_
size_t includeDirectoryCount_
folly::StringPiece fileNames_
size_t fileNameCount_
uint64_t address_
uint64_t file_
uint64_t line_
uint64_t column_
bool isStmt_
bool basicBlock_
bool endSequence_
bool prologueEnd_
bool epilogueBegin_
uint64_t isa_
uint64_t discriminator_
Detailed Description
Definition at line 187 of file Dwarf.h.
Member Enumeration Documentation
enum folly::symbolizer::Dwarf::LineNumberVM::StepResult private
Enumerator
CONTINUE
COMMIT
END
Definition at line 201 of file Dwarf.h.
                     {
       CONTINUE, // Continue feeding opcodes
       COMMIT, // Commit new <address, file, line> tuple
       END, // End of sequence
     };
Constructor & Destructor Documentation
folly::symbolizer::Dwarf::LineNumberVM::LineNumberVM (folly::StringPiece data, folly::StringPiece compilationDirectory)
Definition at line 620 of file Dwarf.cpp.
References data_, FOLLY_SAFE_CHECK, init(), folly::symbolizer::Dwarf::Section::is64Bit(), is64Bit_, folly::symbolizer::Dwarf::Section::next(), and reset().
     : compilationDirectory_(compilationDirectory) {
   Section section(data);
   FOLLY_SAFE_CHECK(section.next(data_), "invalid line number VM");
   is64Bit_ = section.is64Bit();
   init();
   reset();
 }
Member Function Documentation
bool folly::symbolizer::Dwarf::LineNumberVM::findAddress (uintptr_t address, Path & file, uint64_t & line)
Definition at line 906 of file Dwarf.cpp.
References address_, compilationDirectory_, data_, folly::Range< Iter >::empty(), file_, getFileName(), getIncludeDirectory(), line_, next(), reset(), and uint64_t.
Referenced by folly::symbolizer::Dwarf::findLocation().
                     {
   folly::StringPiece program = data_;
   // Within each sequence of instructions, the address may only increase.
   // Unfortunately, within the same compilation unit, sequences may appear
   // in any order.  So any sequence is a candidate if it starts at an address
   // <= the target address, and we know we've found the target address if
   // a candidate crosses the target address.
   enum State {
     START,
     LOW_SEQ, // candidate
     HIGH_SEQ
   };
   State state = START;
   reset();
   uint64_t prevFile = 0;
   uint64_t prevLine = 0;
   while (!program.empty()) {
     bool seqEnd = !next(program);
     if (state == START) {
       if (!seqEnd) {
         state = address_ <= target ? LOW_SEQ : HIGH_SEQ;
       }
     }
     if (state == LOW_SEQ) {
       if (address_ > target) {
         // Found it!  Note that ">" is indeed correct (not ">="), as each
         // sequence is guaranteed to have one entry past-the-end (emitted by
         // DW_LNE_end_sequence)
         if (prevFile == 0) {
           return false;
         }
         auto fn = getFileName(prevFile);
         file = Path(
             compilationDirectory_,
             getIncludeDirectory(fn.directoryIndex),
             fn.relativeName);
         line = prevLine;
         return true;
       }
       prevFile = file_;
       prevLine = line_;
     }
     if (seqEnd) {
       state = START;
       reset();
     }
   }
   return false;
 }
Dwarf::LineNumberVM::FileName folly::symbolizer::Dwarf::LineNumberVM::getFileName (uint64_t index) const private
Definition at line 697 of file Dwarf.cpp.
References data_, fileNameCount_, fileNames_, FOLLY_SAFE_CHECK, nextDefineFile(), and readFileName().
Referenced by findAddress().
{
   FOLLY_SAFE_CHECK(index != 0, "invalid file index 0");
   FileName fn;
   if (index <= fileNameCount_) {
     folly::StringPiece fileNames = fileNames_;
     for (; index; --index) {
       if (!readFileName(fileNames, fn)) {
         abort();
       }
     }
     return fn;
   }
   index -= fileNameCount_;
   folly::StringPiece program = data_;
   for (; index; --index) {
     FOLLY_SAFE_CHECK(nextDefineFile(program, fn), "invalid file index");
   }
   return fn;
 }
folly::StringPiece folly::symbolizer::Dwarf::LineNumberVM::getIncludeDirectory (uint64_t index) const private
Definition at line 722 of file Dwarf.cpp.
References folly::Range< Iter >::empty(), FOLLY_SAFE_CHECK, includeDirectories_, and includeDirectoryCount_.
Referenced by findAddress().
{
   if (index == 0) {
     return folly::StringPiece();
   }
   FOLLY_SAFE_CHECK(
       index <= includeDirectoryCount_, "invalid include directory");
   folly::StringPiece includeDirectories = includeDirectories_;
   folly::StringPiece dir;
   for (; index; --index) {
     dir = readNullTerminated(includeDirectories);
     if (dir.empty()) {
       abort(); // BUG
     }
   }
   return dir;
 }
void folly::symbolizer::Dwarf::LineNumberVM::init () private
Definition at line 645 of file Dwarf.cpp.
References folly::Range< Iter >::assign(), folly::Range< Iter >::data(), data_, defaultIsStmt_, folly::empty(), folly::Range< Iter >::end(), fileNameCount_, fileNames_, FOLLY_SAFE_CHECK, includeDirectories_, includeDirectoryCount_, is64Bit_, lineBase_, lineRange_, minLength_, opcodeBase_, readFileName(), folly::Range< Iter >::size(), standardOpcodeLengths_, uint64_t, uint8_t, and version_.
Referenced by LineNumberVM().
{
   version_ = read<uint16_t>(data_);
   FOLLY_SAFE_CHECK(
       version_ >= 2 && version_ <= 4, "invalid version in line number VM");
   uint64_t headerLength = readOffset(data_, is64Bit_);
   FOLLY_SAFE_CHECK(
       headerLength <= data_.size(), "invalid line number VM header length");
   folly::StringPiece header(data_.data(), headerLength);
   data_.assign(header.end(), data_.end());
   minLength_ = read<uint8_t>(header);
   if (version_ == 4) { // Version 2 and 3 records don't have this
     uint8_t maxOpsPerInstruction = read<uint8_t>(header);
     FOLLY_SAFE_CHECK(maxOpsPerInstruction == 1, "VLIW not supported");
   }
   defaultIsStmt_ = read<uint8_t>(header);
   lineBase_ = read<int8_t>(header); // yes, signed
   lineRange_ = read<uint8_t>(header);
   opcodeBase_ = read<uint8_t>(header);
   FOLLY_SAFE_CHECK(opcodeBase_ != 0, "invalid opcode base");
   standardOpcodeLengths_ = reinterpret_cast<const uint8_t*>(header.data());
   header.advance(opcodeBase_ - 1);
   // We don't want to use heap, so we don't keep an unbounded amount of state.
   // We'll just skip over include directories and file names here, and
   // we'll loop again when we actually need to retrieve one.
   folly::StringPiece sp;
   const char* tmp = header.data();
   includeDirectoryCount_ = 0;
   while (!(sp = readNullTerminated(header)).empty()) {
     ++includeDirectoryCount_;
   }
   includeDirectories_.assign(tmp, header.data());
   tmp = header.data();
   FileName fn;
   fileNameCount_ = 0;
   while (readFileName(header, fn)) {
     ++fileNameCount_;
   }
   fileNames_.assign(tmp, header.data());
 }
bool folly::symbolizer::Dwarf::LineNumberVM::next (folly::StringPiece & program) private
Definition at line 688 of file Dwarf.cpp.
References COMMIT, CONTINUE, and step().
Referenced by findAddress().
{
   Dwarf::LineNumberVM::StepResult ret;
   do {
     ret = step(program);
   } while (ret == CONTINUE);
   return (ret == COMMIT);
 }
bool folly::symbolizer::Dwarf::LineNumberVM::nextDefineFile (folly::StringPiece & program, FileName & fn) const private
Definition at line 757 of file Dwarf.cpp.
References folly::Range< Iter >::advance(), folly::Range< Iter >::empty(), FOLLY_SAFE_CHECK, opcodeBase_, readFileName(), standardOpcodeLengths_, and uint8_t.
Referenced by getFileName().
{
   while (!program.empty()) {
     auto opcode = read<uint8_t>(program);
     if (opcode >= opcodeBase_) { // special opcode
       continue;
     }
     if (opcode != 0) { // standard opcode
       // Skip, slurp the appropriate number of LEB arguments
       uint8_t argCount = standardOpcodeLengths_[opcode - 1];
       while (argCount--) {
         readULEB(program);
       }
       continue;
     }
     // Extended opcode
     auto length = readULEB(program);
     // the opcode itself should be included in the length, so length >= 1
     FOLLY_SAFE_CHECK(length != 0, "invalid extended opcode length");
     read<uint8_t>(program); // extended opcode
     --length;
     if (opcode == DW_LNE_define_file) {
       FOLLY_SAFE_CHECK(
           readFileName(program, fn),
           "invalid empty file in DW_LNE_define_file");
       return true;
     }
     program.advance(length);
     continue;
   }
   return false;
 }
bool folly::symbolizer::Dwarf::LineNumberVM::readFileName (folly::StringPiece & sp, FileName & fn) static private
Definition at line 743 of file Dwarf.cpp.
References folly::symbolizer::Dwarf::LineNumberVM::FileName::directoryIndex, folly::Range< Iter >::empty(), and folly::symbolizer::Dwarf::LineNumberVM::FileName::relativeName.
Referenced by getFileName(), init(), and nextDefineFile().
                   {
   fn.relativeName = readNullTerminated(program);
   if (fn.relativeName.empty()) {
     return false;
   }
   fn.directoryIndex = readULEB(program);
   // Skip over file size and last modified time
   readULEB(program);
   readULEB(program);
   return true;
 }
void folly::symbolizer::Dwarf::LineNumberVM::reset () private
Definition at line 631 of file Dwarf.cpp.
References address_, basicBlock_, column_, defaultIsStmt_, discriminator_, endSequence_, epilogueBegin_, file_, isa_, isStmt_, line_, and prologueEnd_.
Referenced by findAddress(), and LineNumberVM().
{
   address_ = 0;
   file_ = 1;
   line_ = 1;
   column_ = 0;
   isStmt_ = defaultIsStmt_;
   basicBlock_ = false;
   endSequence_ = false;
   prologueEnd_ = false;
   epilogueBegin_ = false;
   isa_ = 0;
   discriminator_ = 0;
 }
Dwarf::LineNumberVM::StepResult folly::symbolizer::Dwarf::LineNumberVM::step (folly::StringPiece & program) private
Definition at line 797 of file Dwarf.cpp.
References address_, folly::Range< Iter >::advance(), basicBlock_, column_, COMMIT, CONTINUE, discriminator_, END, epilogueBegin_, file_, FOLLY_SAFE_CHECK, isa_, isStmt_, line_, lineBase_, lineRange_, minLength_, opcodeBase_, prologueEnd_, standardOpcodeLengths_, uint8_t, and version_.
Referenced by next().
{
   auto opcode = read<uint8_t>(program);
   if (opcode >= opcodeBase_) { // special opcode
     uint8_t adjustedOpcode = opcode - opcodeBase_;
     uint8_t opAdvance = adjustedOpcode / lineRange_;
     address_ += minLength_ * opAdvance;
     line_ += lineBase_ + adjustedOpcode % lineRange_;
     basicBlock_ = false;
     prologueEnd_ = false;
     epilogueBegin_ = false;
     discriminator_ = 0;
     return COMMIT;
   }
   if (opcode != 0) { // standard opcode
     // Only interpret opcodes that are recognized by the version we're parsing;
     // the others are vendor extensions and we should ignore them.
     switch (opcode) {
       case DW_LNS_copy:
         basicBlock_ = false;
         prologueEnd_ = false;
         epilogueBegin_ = false;
         discriminator_ = 0;
         return COMMIT;
       case DW_LNS_advance_pc:
         address_ += minLength_ * readULEB(program);
         return CONTINUE;
       case DW_LNS_advance_line:
         line_ += readSLEB(program);
         return CONTINUE;
       case DW_LNS_set_file:
         file_ = readULEB(program);
         return CONTINUE;
       case DW_LNS_set_column:
         column_ = readULEB(program);
         return CONTINUE;
       case DW_LNS_negate_stmt:
         isStmt_ = !isStmt_;
         return CONTINUE;
       case DW_LNS_set_basic_block:
         basicBlock_ = true;
         return CONTINUE;
       case DW_LNS_const_add_pc:
         address_ += minLength_ * ((255 - opcodeBase_) / lineRange_);
         return CONTINUE;
       case DW_LNS_fixed_advance_pc:
         address_ += read<uint16_t>(program);
         return CONTINUE;
       case DW_LNS_set_prologue_end:
         if (version_ == 2) {
           break; // not supported in version 2
         }
         prologueEnd_ = true;
         return CONTINUE;
       case DW_LNS_set_epilogue_begin:
         if (version_ == 2) {
           break; // not supported in version 2
         }
         epilogueBegin_ = true;
         return CONTINUE;
       case DW_LNS_set_isa:
         if (version_ == 2) {
           break; // not supported in version 2
         }
         isa_ = readULEB(program);
         return CONTINUE;
     }
     // Unrecognized standard opcode, slurp the appropriate number of LEB
     // arguments.
     uint8_t argCount = standardOpcodeLengths_[opcode - 1];
     while (argCount--) {
       readULEB(program);
     }
     return CONTINUE;
   }
   // Extended opcode
   auto length = readULEB(program);
   // the opcode itself should be included in the length, so length >= 1
   FOLLY_SAFE_CHECK(length != 0, "invalid extended opcode length");
   auto extendedOpcode = read<uint8_t>(program);
   --length;
   switch (extendedOpcode) {
     case DW_LNE_end_sequence:
       return END;
     case DW_LNE_set_address:
       address_ = read<uintptr_t>(program);
       return CONTINUE;
     case DW_LNE_define_file:
       // We can't process DW_LNE_define_file here, as it would require us to
       // use unbounded amounts of state (ie. use the heap).  We'll do a second
       // pass (using nextDefineFile()) if necessary.
       break;
     case DW_LNE_set_discriminator:
       discriminator_ = readULEB(program);
       return CONTINUE;
   }
   // Unrecognized extended opcode
   program.advance(length);
   return CONTINUE;
 }
Member Data Documentation
uint64_t folly::symbolizer::Dwarf::LineNumberVM::address_ private
Definition at line 251 of file Dwarf.h.
Referenced by findAddress(), reset(), and step().
bool folly::symbolizer::Dwarf::LineNumberVM::basicBlock_ private
Definition at line 256 of file Dwarf.h.
Referenced by reset(), and step().
uint64_t folly::symbolizer::Dwarf::LineNumberVM::column_ private
Definition at line 254 of file Dwarf.h.
Referenced by reset(), and step().
folly::StringPiece folly::symbolizer::Dwarf::LineNumberVM::compilationDirectory_ private
Definition at line 233 of file Dwarf.h.
Referenced by findAddress().
folly::StringPiece folly::symbolizer::Dwarf::LineNumberVM::data_ private
Definition at line 232 of file Dwarf.h.
Referenced by findAddress(), getFileName(), init(), and LineNumberVM().
bool folly::symbolizer::Dwarf::LineNumberVM::defaultIsStmt_ private
Definition at line 238 of file Dwarf.h.
Referenced by init(), and reset().
uint64_t folly::symbolizer::Dwarf::LineNumberVM::discriminator_ private
Definition at line 261 of file Dwarf.h.
Referenced by reset(), and step().
bool folly::symbolizer::Dwarf::LineNumberVM::endSequence_ private
Definition at line 257 of file Dwarf.h.
Referenced by reset().
bool folly::symbolizer::Dwarf::LineNumberVM::epilogueBegin_ private
Definition at line 259 of file Dwarf.h.
Referenced by reset(), and step().
uint64_t folly::symbolizer::Dwarf::LineNumberVM::file_ private
Definition at line 252 of file Dwarf.h.
Referenced by findAddress(), reset(), and step().
size_t folly::symbolizer::Dwarf::LineNumberVM::fileNameCount_ private
Definition at line 248 of file Dwarf.h.
Referenced by getFileName(), and init().
folly::StringPiece folly::symbolizer::Dwarf::LineNumberVM::fileNames_ private
Definition at line 247 of file Dwarf.h.
Referenced by getFileName(), and init().
folly::StringPiece folly::symbolizer::Dwarf::LineNumberVM::includeDirectories_ private
Definition at line 244 of file Dwarf.h.
Referenced by getIncludeDirectory(), and init().
size_t folly::symbolizer::Dwarf::LineNumberVM::includeDirectoryCount_ private
Definition at line 245 of file Dwarf.h.
Referenced by getIncludeDirectory(), and init().
bool folly::symbolizer::Dwarf::LineNumberVM::is64Bit_ private
Definition at line 231 of file Dwarf.h.
Referenced by init(), and LineNumberVM().
uint64_t folly::symbolizer::Dwarf::LineNumberVM::isa_ private
Definition at line 260 of file Dwarf.h.
Referenced by reset(), and step().
bool folly::symbolizer::Dwarf::LineNumberVM::isStmt_ private
Definition at line 255 of file Dwarf.h.
Referenced by reset(), and step().
uint64_t folly::symbolizer::Dwarf::LineNumberVM::line_ private
Definition at line 253 of file Dwarf.h.
Referenced by findAddress(), reset(), and step().
int8_t folly::symbolizer::Dwarf::LineNumberVM::lineBase_ private
Definition at line 239 of file Dwarf.h.
Referenced by init(), and step().
uint8_t folly::symbolizer::Dwarf::LineNumberVM::lineRange_ private
Definition at line 240 of file Dwarf.h.
Referenced by init(), and step().
uint8_t folly::symbolizer::Dwarf::LineNumberVM::minLength_ private
Definition at line 237 of file Dwarf.h.
Referenced by init(), and step().
uint8_t folly::symbolizer::Dwarf::LineNumberVM::opcodeBase_ private
Definition at line 241 of file Dwarf.h.
Referenced by init(), nextDefineFile(), and step().
bool folly::symbolizer::Dwarf::LineNumberVM::prologueEnd_ private
Definition at line 258 of file Dwarf.h.
Referenced by reset(), and step().
const uint8_t* folly::symbolizer::Dwarf::LineNumberVM::standardOpcodeLengths_ private
Definition at line 242 of file Dwarf.h.
Referenced by init(), nextDefineFile(), and step().
uint16_t folly::symbolizer::Dwarf::LineNumberVM::version_ private
Definition at line 236 of file Dwarf.h.
Referenced by init(), and step().
The documentation for this class was generated from the following files:
proxygen/folly/folly/experimental/symbolizer/Dwarf.h
proxygen/folly/folly/experimental/symbolizer/Dwarf.cpp