proxygen: folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor Class Reference
folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor Class Reference
#include <ConcurrentSkipList.h>
Public Types
typedef T value_type
typedef T key_type
typedef T & reference
typedef T * pointer
typedef const T & const_reference
typedef const T * const_pointer
typedef size_t size_type
typedef Comp key_compare
typedef Comp value_compare
typedef SkipListType::iterator iterator
typedef SkipListType::const_iterator const_iterator
typedef SkipListType::Skipper Skipper
Public Member Functions
Accessor (std::shared_ptr< ConcurrentSkipList > skip_list)
Accessor (ConcurrentSkipList *skip_list)
Accessor (const Accessor &accessor)
Accessor & operator= (const Accessor &accessor)
~Accessor ()
bool empty () const
size_t size () const
size_type max_size () const
iterator find (const key_type &value)
const_iterator find (const key_type &value) const
size_type count (const key_type &data) const
iterator begin () const
iterator end () const
const_iterator cbegin () const
const_iterator cend () const
template<typename U , typename = typename std::enable_if<std::is_convertible<U, T>::value>::type>
std::pair< iterator, bool > insert (U &&data)
size_t erase (const key_type &data)
iterator lower_bound (const key_type &data) const
size_t height () const
const key_type * first () const
const key_type * last () const
bool pop_back ()
std::pair< key_type *, bool > addOrGetData (const key_type &data)
SkipListType * skiplist () const
bool contains (const key_type &data) const
bool add (const key_type &data)
bool remove (const key_type &data)
Private Types
typedef detail::SkipListNode< T > NodeType
typedef ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT > SkipListType
Private Attributes
SkipListType * sl_
std::shared_ptr< SkipListType > slHolder_
Detailed Description
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24>
class folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor
Definition at line 545 of file ConcurrentSkipList.h.
Member Typedef Documentation
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> typedef SkipListType::const_iterator folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::const_iterator
Definition at line 561 of file ConcurrentSkipList.h.
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> typedef const T* folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::const_pointer
Definition at line 555 of file ConcurrentSkipList.h.
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> typedef const T& folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::const_reference
Definition at line 554 of file ConcurrentSkipList.h.
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> typedef SkipListType::iterator folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::iterator
Definition at line 560 of file ConcurrentSkipList.h.
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> typedef Comp folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::key_compare
Definition at line 557 of file ConcurrentSkipList.h.
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> typedef T folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::key_type
Definition at line 551 of file ConcurrentSkipList.h.
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> typedef detail::SkipListNode<T> folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::NodeType private
Definition at line 546 of file ConcurrentSkipList.h.
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> typedef T* folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::pointer
Definition at line 553 of file ConcurrentSkipList.h.
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> typedef T& folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::reference
Definition at line 552 of file ConcurrentSkipList.h.
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> typedef size_t folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::size_type
Definition at line 556 of file ConcurrentSkipList.h.
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> typedef ConcurrentSkipList<T, Comp, NodeAlloc, MAX_HEIGHT> folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::SkipListType private
Definition at line 547 of file ConcurrentSkipList.h.
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> typedef SkipListType::Skipper folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::Skipper
Definition at line 562 of file ConcurrentSkipList.h.
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> typedef Comp folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::value_compare
Definition at line 558 of file ConcurrentSkipList.h.
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> typedef T folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::value_type
Definition at line 550 of file ConcurrentSkipList.h.
Constructor & Destructor Documentation
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::Accessor (std::shared_ptr< ConcurrentSkipList > skip_list) inline explicit
Definition at line 564 of file ConcurrentSkipList.h.
       : slHolder_(std::move(skip_list)) {
     sl_ = slHolder_.get();
     DCHECK(sl_ != nullptr);
     sl_->recycler_.addRef();
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::Accessor (ConcurrentSkipList * skip_list) inline explicit
Definition at line 573 of file ConcurrentSkipList.h.
                                                    : sl_(skip_list) {
     DCHECK(sl_ != nullptr);
     sl_->recycler_.addRef();
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::Accessor (const Accessor & accessor) inline
Definition at line 578 of file ConcurrentSkipList.h.
       : sl_(accessor.sl_), slHolder_(accessor.slHolder_) {
     sl_->recycler_.addRef();
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::~Accessor () inline
Definition at line 593 of file ConcurrentSkipList.h.
               {
     sl_->recycler_.releaseRef();
   }
Member Function Documentation
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> bool folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::add (const key_type & data) inline
Definition at line 698 of file ConcurrentSkipList.h.
{
     return sl_->addOrGetData(data).second;
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> std::pair<key_type*, bool> folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::addOrGetData (const key_type & data) inline
Definition at line 682 of file ConcurrentSkipList.h.
{
     auto ret = sl_->addOrGetData(data);
     return std::make_pair(&ret.first->data(), ret.second);
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> iterator folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::begin () const inline
Definition at line 620 of file ConcurrentSkipList.h.
References folly::detail::SkipListNode< T >::next().
{
     NodeType* head = sl_->head_.load(std::memory_order_consume);
     return iterator(head->next());
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> const_iterator folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::cbegin () const inline
Definition at line 627 of file ConcurrentSkipList.h.
References folly::test::begin().
{
     return begin();
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> const_iterator folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::cend () const inline
Definition at line 630 of file ConcurrentSkipList.h.
References folly::test::end(), type, and value.
{
     return end();
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> bool folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::contains (const key_type & data) const inline
Definition at line 695 of file ConcurrentSkipList.h.
{
     return sl_->find(data);
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> size_type folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::count (const key_type & data) const inline
Definition at line 616 of file ConcurrentSkipList.h.
References folly::gen::contains().
{
     return contains(data);
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> bool folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::empty () const inline
Definition at line 597 of file ConcurrentSkipList.h.
                      {
     return sl_->size() == 0;
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> iterator folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::end () const inline
Definition at line 624 of file ConcurrentSkipList.h.
{
     return iterator(nullptr);
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> size_t folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::erase (const key_type & data) inline
Definition at line 642 of file ConcurrentSkipList.h.
References folly::data().
{
     return remove(data);
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> iterator folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::find (const key_type & value) inline
Definition at line 610 of file ConcurrentSkipList.h.
{
     return iterator(sl_->find(value));
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> const_iterator folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::find (const key_type & value) const inline
Definition at line 613 of file ConcurrentSkipList.h.
{
     return iterator(sl_->find(value));
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> const key_type* folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::first () const inline
Definition at line 665 of file ConcurrentSkipList.h.
{
     return sl_->first();
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> size_t folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::height () const inline
Definition at line 650 of file ConcurrentSkipList.h.
{
     return sl_->height();
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> template<typename U , typename = typename std::enable_if<std::is_convertible<U, T>::value>::type> std::pair<iterator, bool> folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::insert (U && data) inline
Definition at line 638 of file ConcurrentSkipList.h.
References folly::data().
{
     auto ret = sl_->addOrGetData(std::forward<U>(data));
     return std::make_pair(iterator(ret.first), ret.second);
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> const key_type* folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::last () const inline
Definition at line 668 of file ConcurrentSkipList.h.
{
     return sl_->last();
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> iterator folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::lower_bound (const key_type & data) const inline
Definition at line 646 of file ConcurrentSkipList.h.
{
     return iterator(sl_->lower_bound(data));
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> size_type folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::max_size () const inline
Definition at line 603 of file ConcurrentSkipList.h.
References max.
{
     return std::numeric_limits<size_type>::max();
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> Accessor& folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::operator= (const Accessor & accessor) inline
Definition at line 583 of file ConcurrentSkipList.h.
References folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::recycler_, folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::sl_, and folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::slHolder_.
{
     if (this != &accessor) {
       slHolder_ = accessor.slHolder_;
       sl_->recycler_.releaseRef();
       sl_ = accessor.sl_;
       sl_->recycler_.addRef();
     }
     return *this;
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> bool folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::pop_back () inline
Definition at line 677 of file ConcurrentSkipList.h.
References folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::last().
                   {
     auto last = sl_->last();
     return last ? sl_->remove(*last) : false;
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> bool folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::remove (const key_type & data) inline
Definition at line 701 of file ConcurrentSkipList.h.
References folly::data().
{
     return sl_->remove(data);
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> size_t folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::size () const inline
Definition at line 600 of file ConcurrentSkipList.h.
                       {
     return sl_->size();
   }
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> SkipListType* folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::skiplist () const inline
Definition at line 687 of file ConcurrentSkipList.h.
{
     return sl_;
   }
Member Data Documentation
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> SkipListType* folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::sl_ private
Definition at line 706 of file ConcurrentSkipList.h.
Referenced by folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::operator=().
template<typename T, typename Comp = std::less<T>, typename NodeAlloc = SysAllocator<void>, int MAX_HEIGHT = 24> std::shared_ptr<SkipListType> folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::slHolder_ private
Definition at line 707 of file ConcurrentSkipList.h.
Referenced by folly::ConcurrentSkipList< T, Comp, NodeAlloc, MAX_HEIGHT >::Accessor::operator=().
The documentation for this class was generated from the following file:
proxygen/folly/folly/ConcurrentSkipList.h