proxygen: folly::coro::detail::TaskPromiseBase Class Reference
folly::coro::detail::TaskPromiseBase Class Reference
#include <Task.h>
Classes
class FinalAwaiter
Public Member Functions
std::experimental::suspend_always initial_suspend () noexcept
FinalAwaiter final_suspend () noexcept
template<typename U >
auto await_transform (Task< U > &&t) noexcept
template<typename Awaitable >
auto await_transform (Awaitable &&awaitable) noexcept
auto await_transform (folly::coro::getCurrentExecutor) noexcept
template<typename T >
auto await_transform (Task< T > &&t) noexcept
Protected Member Functions
TaskPromiseBase () noexcept
Private Attributes
std::experimental::coroutine_handle continuation_
folly::Executor * executor_
Friends
class FinalAwaiter
template<typename T >
class folly::coro::TaskWithExecutor
template<typename T >
class folly::coro::Task
Detailed Description
Definition at line 45 of file Task.h.
Constructor & Destructor Documentation
folly::coro::detail::TaskPromiseBase::TaskPromiseBase () inline protected noexcept
Definition at line 65 of file Task.h.
 : executor_(nullptr) {}
Member Function Documentation
template<typename U > auto folly::coro::detail::TaskPromiseBase::await_transform (Task< U > && t) noexcept
template<typename Awaitable > auto folly::coro::detail::TaskPromiseBase::await_transform (Awaitable && awaitable) inline noexcept
Definition at line 80 of file Task.h.
References folly::coro::co_viaIfAsync().
{
     using folly::coro::co_viaIfAsync;
     return co_viaIfAsync(executor_, static_cast<Awaitable&&>(awaitable));
   }
auto folly::coro::detail::TaskPromiseBase::await_transform (folly::coro::getCurrentExecutor) inline noexcept
Definition at line 85 of file Task.h.
{
     return AwaitableReady<folly::Executor*>{executor_};
   }
template<typename T > auto folly::coro::detail::TaskPromiseBase::await_transform (Task< T > && t) noexcept
Definition at line 309 of file Task.h.
References destroy(), folly::exchange(), SCOPE_EXIT, and folly::pushmi::detail::t.
{
   class Awaiter {
     using handle_t =
         std::experimental::coroutine_handle<detail::TaskPromise<T>>;
    public:
     explicit Awaiter(handle_t coro) noexcept : coro_(coro) {}
     Awaiter(Awaiter&& other) noexcept : coro_(std::exchange(other.coro_, {})) {}
     Awaiter(const Awaiter&) = delete;
     ~Awaiter() {
       if (coro_) {
         coro_.destroy();
       }
     }
     bool await_ready() noexcept {
       return false;
     }
     handle_t await_suspend(
         std::experimental::coroutine_handle<> continuation) noexcept {
       coro_.promise().continuation_ = continuation;
       return coro_;
     }
     decltype(auto) await_resume() {
       SCOPE_EXIT {
         std::exchange(coro_, {}).destroy();
       };
       return coro_.promise().getResult();
     }
    private:
     handle_t coro_;
   };
   t.coro_.promise().executor_ = executor_;
   return Awaiter{std::exchange(t.coro_, {})};
 }
FinalAwaiter folly::coro::detail::TaskPromiseBase::final_suspend () inline noexcept
Definition at line 72 of file Task.h.
References folly::pushmi::__adl::noexcept(), and folly::pushmi::detail::t.
{
     return {};
   }
std::experimental::suspend_always folly::coro::detail::TaskPromiseBase::initial_suspend () inline noexcept
Definition at line 68 of file Task.h.
{
     return {};
   }
Friends And Related Function Documentation
friend class FinalAwaiter friend
Definition at line 62 of file Task.h.
template<typename T > friend class folly::coro::Task friend
Definition at line 94 of file Task.h.
template<typename T > friend class folly::coro::TaskWithExecutor friend
Definition at line 91 of file Task.h.
Member Data Documentation
std::experimental::coroutine_handle folly::coro::detail::TaskPromiseBase::continuation_ private
Definition at line 96 of file Task.h.
Referenced by folly::coro::detail::TaskPromiseBase::FinalAwaiter::await_suspend().
folly::Executor* folly::coro::detail::TaskPromiseBase::executor_ private
Definition at line 97 of file Task.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/coro/Task.h