proxygen: ImmediateFlowSingleSender Class Reference
ImmediateFlowSingleSender Class Reference
Protected Member Functions
auto make_producer ()
template<class F >
auto make_consumer (F f)
Protected Member Functions inherited from testing::Test
Test ()
virtual void SetUp ()
virtual void TearDown ()
Test ()
virtual void SetUp ()
virtual void TearDown ()
Test ()
virtual void SetUp ()
virtual void TearDown ()
Protected Attributes
int signals_ {0}
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Detailed Description
Definition at line 45 of file FlowTest.cpp.
Member Function Documentation
template<class F > auto ImmediateFlowSingleSender::make_consumer (F f) inline protected
Definition at line 91 of file FlowTest.cpp.
References f, MAKE, folly::gen::move, folly::pushmi::__adl::noexcept(), folly::pushmi::on_done(), folly::pushmi::on_error(), folly::pushmi::on_starting(), and folly::pushmi::on_value().
{
     return mi::MAKE(flow_receiver)(
         mi::on_value([&](int) { signals_ += 100; }),
         mi::on_error([&](auto) noexcept { signals_ += 1000; }),
         mi::on_done([&]() { signals_ += 1; }),
         mi::on_starting([&, f](auto up) {
           signals_ += 10;
           f(std::move(up));
         }));
   }
auto ImmediateFlowSingleSender::make_producer () inline protected
Definition at line 47 of file FlowTest.cpp.
References data, folly::pushmi::lock_both(), MAKE, folly::gen::move, folly::pushmi::__adl::noexcept(), folly::pushmi::on_done(), folly::pushmi::set_done, folly::pushmi::set_starting, folly::pushmi::set_value, folly::pushmi::shared_entangle(), stop(), and tokens.
{
     return mi::MAKE(flow_single_sender)([&](auto out) {
       // boolean cancellation
       bool stop = false;
       auto set_stop = [](auto& stop) {
         if (!!stop) {
           *stop = true;
         }
       };
       auto tokens = mi::shared_entangle(stop, set_stop);
       using Stopper = decltype(tokens.second);
       struct Data : mi::receiver<> {
         explicit Data(Stopper stopper) : stopper(std::move(stopper)) {}
         Stopper stopper;
       };
       auto up = mi::MAKE(receiver)(
           Data{std::move(tokens.second)},
           [&](auto& data, auto) noexcept {
             signals_ += 100000;
             auto both = lock_both(data.stopper);
             (*(both.first))(both.second);
           },
           mi::on_done([&](auto& data) {
             signals_ += 10000;
             auto both = lock_both(data.stopper);
             (*(both.first))(both.second);
           }));
       // pass reference for cancellation.
       ::mi::set_starting(out, std::move(up));
       // check boolean to select signal
       auto both = lock_both(tokens.first);
       if (!!both.first && !*(both.first)) {
         ::mi::set_value(out, 42);
       } else {
         // cancellation is not an error
         ::mi::set_done(out);
       }
     });
   }
Member Data Documentation
int ImmediateFlowSingleSender::signals_ {0} protected
Definition at line 102 of file FlowTest.cpp.
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/pushmi/test/FlowTest.cpp