proxygen: testing::internal::SingleFailureChecker Class Reference
testing::internal::SingleFailureChecker Class Reference
#include <gtest-spi.h>
Public Member Functions
SingleFailureChecker (const TestPartResultArray *results, TestPartResult::Type type, const string &substr)
~SingleFailureChecker ()
SingleFailureChecker (const TestPartResultArray *results, TestPartResult::Type type, const string &substr)
~SingleFailureChecker ()
SingleFailureChecker (const TestPartResultArray *results, TestPartResult::Type type, const string &substr)
~SingleFailureChecker ()
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (SingleFailureChecker)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (SingleFailureChecker)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (SingleFailureChecker)
Private Attributes
const TestPartResultArray *const results_
const TestPartResult::Type type_
const string substr_
Detailed Description
Definition at line 96 of file gtest-spi.h.
Constructor & Destructor Documentation
testing::internal::SingleFailureChecker::SingleFailureChecker (const TestPartResultArray * results, TestPartResult::Type type, const string & substr)
Definition at line 670 of file gtest.cc.
Referenced by testing::internal::ShouldRunTestCase().
     : results_(results),
       type_(type),
       substr_(substr) {}
testing::internal::SingleFailureChecker::~SingleFailureChecker ()
Definition at line 682 of file gtest.cc.
References EXPECT_PRED_FORMAT3, testing::internal::HasOneFailure(), results_, substr_, and type_.
Referenced by testing::internal::ShouldRunTestCase().
{
   EXPECT_PRED_FORMAT3(HasOneFailure, *results_, type_, substr_);
 }
testing::internal::SingleFailureChecker::SingleFailureChecker (const TestPartResultArray * results, TestPartResult::Type type, const string & substr)
testing::internal::SingleFailureChecker::~SingleFailureChecker ()
testing::internal::SingleFailureChecker::SingleFailureChecker (const TestPartResultArray * results, TestPartResult::Type type, const string & substr)
testing::internal::SingleFailureChecker::~SingleFailureChecker ()
Member Function Documentation
testing::internal::SingleFailureChecker::GTEST_DISALLOW_COPY_AND_ASSIGN_ (SingleFailureChecker) private
testing::internal::SingleFailureChecker::GTEST_DISALLOW_COPY_AND_ASSIGN_ (SingleFailureChecker) private
testing::internal::SingleFailureChecker::GTEST_DISALLOW_COPY_AND_ASSIGN_ (SingleFailureChecker) private
Member Data Documentation
const TestPartResultArray *const testing::internal::SingleFailureChecker::results_ private
Definition at line 104 of file gtest-spi.h.
Referenced by ~SingleFailureChecker().
const string testing::internal::SingleFailureChecker::substr_ private
Definition at line 106 of file gtest-spi.h.
Referenced by ~SingleFailureChecker().
const TestPartResult::Type testing::internal::SingleFailureChecker::type_ private
Definition at line 105 of file gtest-spi.h.
Referenced by ~SingleFailureChecker().
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/gtest-spi.h
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest.cc