proxygen: folly::ThreadPoolExecutor::StoppedThreadQueue Class Reference
folly::ThreadPoolExecutor::StoppedThreadQueue Class Reference
#include <ThreadPoolExecutor.h>
Public Member Functions
BlockingQueueAddResult add (ThreadPtr item) override
ThreadPtr take () override
size_t size () override
folly::Optional< ThreadPtr > try_take_for (std::chrono::milliseconds) override
Public Member Functions inherited from folly::BlockingQueue< ThreadPtr >
virtual ~BlockingQueue ()=default
virtual BlockingQueueAddResult add (ThreadPtritem)=0
virtual BlockingQueueAddResult addWithPriority (ThreadPtritem, int8_t)
virtual uint8_t getNumPriorities ()
Private Attributes
folly::LifoSem sem_
std::mutex mutex_
std::queue< ThreadPtr > queue_
Detailed Description
Definition at line 273 of file ThreadPoolExecutor.h.
Member Function Documentation
BlockingQueueAddResult folly::ThreadPoolExecutor::StoppedThreadQueue::add (ThreadPoolExecutor::ThreadPtr item) override
Definition at line 305 of file ThreadPoolExecutor.cpp.
References folly::gen::guard(), folly::gen::move, and mutex_.
Referenced by folly::IOThreadPoolExecutor::stopThreads(), and folly::CPUThreadPoolExecutor::threadRun().
{
   std::lock_guard<std::mutex> guard(mutex_);
   queue_.push(std::move(item));
   return sem_.post();
 }
size_t folly::ThreadPoolExecutor::StoppedThreadQueue::size () override virtual
Implements folly::BlockingQueue< ThreadPtr >.
Definition at line 344 of file ThreadPoolExecutor.cpp.
References folly::gen::guard(), and mutex_.
Referenced by folly::ThreadPoolExecutor::join(), and folly::ThreadPoolExecutor::stop().
{
   std::lock_guard<std::mutex> guard(mutex_);
   return queue_.size();
 }
ThreadPoolExecutor::ThreadPtr folly::ThreadPoolExecutor::StoppedThreadQueue::take () override virtual
Implements folly::BlockingQueue< ThreadPtr >.
Definition at line 312 of file ThreadPoolExecutor.cpp.
References folly::gen::guard(), folly::gen::move, and mutex_.
Referenced by folly::ThreadPoolExecutor::joinStoppedThreads().
{
   while (true) {
     {
       std::lock_guard<std::mutex> guard(mutex_);
       if (queue_.size() > 0) {
         auto item = std::move(queue_.front());
         queue_.pop();
         return item;
       }
     }
     sem_.wait();
   }
 }
folly::Optional< ThreadPoolExecutor::ThreadPtr > folly::ThreadPoolExecutor::StoppedThreadQueue::try_take_for (std::chrono::milliseconds time) override virtual
Implements folly::BlockingQueue< ThreadPtr >.
Definition at line 327 of file ThreadPoolExecutor.cpp.
References folly::gen::guard(), folly::gen::move, mutex_, and folly::none.
{
   while (true) {
     {
       std::lock_guard<std::mutex> guard(mutex_);
       if (queue_.size() > 0) {
         auto item = std::move(queue_.front());
         queue_.pop();
         return item;
       }
     }
     if (!sem_.try_wait_for(time)) {
       return folly::none;
     }
   }
 }
Member Data Documentation
std::mutex folly::ThreadPoolExecutor::StoppedThreadQueue::mutex_ private
Definition at line 283 of file ThreadPoolExecutor.h.
std::queue<ThreadPtr> folly::ThreadPoolExecutor::StoppedThreadQueue::queue_ private
Definition at line 284 of file ThreadPoolExecutor.h.
folly::LifoSem folly::ThreadPoolExecutor::StoppedThreadQueue::sem_ private
Definition at line 282 of file ThreadPoolExecutor.h.
The documentation for this class was generated from the following files:
proxygen/folly/folly/executors/ThreadPoolExecutor.h
proxygen/folly/folly/executors/ThreadPoolExecutor.cpp