proxygen: testing::ScopedFakeTestPartResultReporter Class Reference
testing::ScopedFakeTestPartResultReporter Class Reference
#include <gtest-spi.h>
Public Types
enum InterceptMode {
INTERCEPT_ONLY_CURRENT_THREAD, INTERCEPT_ALL_THREADS, INTERCEPT_ONLY_CURRENT_THREAD, INTERCEPT_ALL_THREADS,
INTERCEPT_ONLY_CURRENT_THREAD, INTERCEPT_ALL_THREADS
}
enum InterceptMode {
INTERCEPT_ONLY_CURRENT_THREAD, INTERCEPT_ALL_THREADS, INTERCEPT_ONLY_CURRENT_THREAD, INTERCEPT_ALL_THREADS,
INTERCEPT_ONLY_CURRENT_THREAD, INTERCEPT_ALL_THREADS
}
enum InterceptMode {
INTERCEPT_ONLY_CURRENT_THREAD, INTERCEPT_ALL_THREADS, INTERCEPT_ONLY_CURRENT_THREAD, INTERCEPT_ALL_THREADS,
INTERCEPT_ONLY_CURRENT_THREAD, INTERCEPT_ALL_THREADS
}
Public Member Functions
ScopedFakeTestPartResultReporter (TestPartResultArray *result)
ScopedFakeTestPartResultReporter (InterceptMode intercept_mode, TestPartResultArray *result)
virtual ~ScopedFakeTestPartResultReporter ()
virtual void ReportTestPartResult (const TestPartResult &result)
ScopedFakeTestPartResultReporter (TestPartResultArray *result)
ScopedFakeTestPartResultReporter (InterceptMode intercept_mode, TestPartResultArray *result)
virtual ~ScopedFakeTestPartResultReporter ()
virtual void ReportTestPartResult (const TestPartResult &result)
ScopedFakeTestPartResultReporter (TestPartResultArray *result)
ScopedFakeTestPartResultReporter (InterceptMode intercept_mode, TestPartResultArray *result)
virtual ~ScopedFakeTestPartResultReporter ()
virtual void ReportTestPartResult (const TestPartResult &result)
Public Member Functions inherited from testing::TestPartResultReporterInterface
virtual ~TestPartResultReporterInterface ()
virtual ~TestPartResultReporterInterface ()
virtual ~TestPartResultReporterInterface ()
Private Member Functions
void Init ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (ScopedFakeTestPartResultReporter)
void Init ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (ScopedFakeTestPartResultReporter)
void Init ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (ScopedFakeTestPartResultReporter)
Private Attributes
const InterceptMode intercept_mode_
TestPartResultReporterInterface * old_reporter_
TestPartResultArray *const result_
Detailed Description
Definition at line 51 of file gtest-spi.h.
Member Enumeration Documentation
enum testing::ScopedFakeTestPartResultReporter::InterceptMode
Enumerator
INTERCEPT_ONLY_CURRENT_THREAD
INTERCEPT_ALL_THREADS
INTERCEPT_ONLY_CURRENT_THREAD
INTERCEPT_ALL_THREADS
INTERCEPT_ONLY_CURRENT_THREAD
INTERCEPT_ALL_THREADS
Definition at line 55 of file gtest-spi.h.
                      {
     INTERCEPT_ONLY_CURRENT_THREAD,  // Intercepts only thread local failures.
     INTERCEPT_ALL_THREADS           // Intercepts all failures.
   };
enum testing::ScopedFakeTestPartResultReporter::InterceptMode
Enumerator
INTERCEPT_ONLY_CURRENT_THREAD
INTERCEPT_ALL_THREADS
INTERCEPT_ONLY_CURRENT_THREAD
INTERCEPT_ALL_THREADS
INTERCEPT_ONLY_CURRENT_THREAD
INTERCEPT_ALL_THREADS
Definition at line 55 of file gtest-spi.h.
                      {
     INTERCEPT_ONLY_CURRENT_THREAD,  // Intercepts only thread local failures.
     INTERCEPT_ALL_THREADS           // Intercepts all failures.
   };
enum testing::ScopedFakeTestPartResultReporter::InterceptMode
Enumerator
INTERCEPT_ONLY_CURRENT_THREAD
INTERCEPT_ALL_THREADS
INTERCEPT_ONLY_CURRENT_THREAD
INTERCEPT_ALL_THREADS
INTERCEPT_ONLY_CURRENT_THREAD
INTERCEPT_ALL_THREADS
Definition at line 55 of file gtest-spi.h.
                      {
     INTERCEPT_ONLY_CURRENT_THREAD,  // Intercepts only thread local failures.
     INTERCEPT_ALL_THREADS           // Intercepts all failures.
   };
Constructor & Destructor Documentation
testing::ScopedFakeTestPartResultReporter::ScopedFakeTestPartResultReporter (TestPartResultArray * result) explicit
Definition at line 563 of file gtest.cc.
References Init().
Referenced by testing::internal::ShouldRunTestCase().
     : intercept_mode_(INTERCEPT_ONLY_CURRENT_THREAD),
       result_(result) {
   Init();
 }
testing::ScopedFakeTestPartResultReporter::ScopedFakeTestPartResultReporter (InterceptMode intercept_mode, TestPartResultArray * result)
Definition at line 573 of file gtest.cc.
References Init().
     : intercept_mode_(intercept_mode),
       result_(result) {
   Init();
 }
testing::ScopedFakeTestPartResultReporter::~ScopedFakeTestPartResultReporter () virtual
Definition at line 593 of file gtest.cc.
References testing::internal::GetUnitTestImpl(), INTERCEPT_ALL_THREADS, intercept_mode_, old_reporter_, testing::internal::UnitTestImpl::SetGlobalTestPartResultReporter(), and testing::internal::UnitTestImpl::SetTestPartResultReporterForCurrentThread().
Referenced by testing::internal::ShouldRunTestCase().
{
   internal::UnitTestImpl* const impl = internal::GetUnitTestImpl();
   if (intercept_mode_ == INTERCEPT_ALL_THREADS) {
     impl->SetGlobalTestPartResultReporter(old_reporter_);
   } else {
     impl->SetTestPartResultReporterForCurrentThread(old_reporter_);
   }
 }
testing::ScopedFakeTestPartResultReporter::ScopedFakeTestPartResultReporter (TestPartResultArray * result) explicit
testing::ScopedFakeTestPartResultReporter::ScopedFakeTestPartResultReporter (InterceptMode intercept_mode, TestPartResultArray * result)
virtual testing::ScopedFakeTestPartResultReporter::~ScopedFakeTestPartResultReporter () virtual
testing::ScopedFakeTestPartResultReporter::ScopedFakeTestPartResultReporter (TestPartResultArray * result) explicit
testing::ScopedFakeTestPartResultReporter::ScopedFakeTestPartResultReporter (InterceptMode intercept_mode, TestPartResultArray * result)
virtual testing::ScopedFakeTestPartResultReporter::~ScopedFakeTestPartResultReporter () virtual
Member Function Documentation
testing::ScopedFakeTestPartResultReporter::GTEST_DISALLOW_COPY_AND_ASSIGN_ (ScopedFakeTestPartResultReporter) private
testing::ScopedFakeTestPartResultReporter::GTEST_DISALLOW_COPY_AND_ASSIGN_ (ScopedFakeTestPartResultReporter) private
testing::ScopedFakeTestPartResultReporter::GTEST_DISALLOW_COPY_AND_ASSIGN_ (ScopedFakeTestPartResultReporter) private
void testing::ScopedFakeTestPartResultReporter::Init () private
void testing::ScopedFakeTestPartResultReporter::Init () private
void testing::ScopedFakeTestPartResultReporter::Init () private
Definition at line 580 of file gtest.cc.
References testing::internal::UnitTestImpl::GetGlobalTestPartResultReporter(), testing::internal::UnitTestImpl::GetTestPartResultReporterForCurrentThread(), testing::internal::GetUnitTestImpl(), INTERCEPT_ALL_THREADS, intercept_mode_, old_reporter_, testing::internal::UnitTestImpl::SetGlobalTestPartResultReporter(), and testing::internal::UnitTestImpl::SetTestPartResultReporterForCurrentThread().
Referenced by ScopedFakeTestPartResultReporter(), and testing::internal::ShouldRunTestCase().
{
   internal::UnitTestImpl* const impl = internal::GetUnitTestImpl();
   if (intercept_mode_ == INTERCEPT_ALL_THREADS) {
     old_reporter_ = impl->GetGlobalTestPartResultReporter();
     impl->SetGlobalTestPartResultReporter(this);
   } else {
     old_reporter_ = impl->GetTestPartResultReporterForCurrentThread();
     impl->SetTestPartResultReporterForCurrentThread(this);
   }
 }
virtual void testing::ScopedFakeTestPartResultReporter::ReportTestPartResult (const TestPartResult & result) virtual
Implements testing::TestPartResultReporterInterface.
void testing::ScopedFakeTestPartResultReporter::ReportTestPartResult (const TestPartResult & result) virtual
Implements testing::TestPartResultReporterInterface.
Definition at line 604 of file gtest.cc.
References testing::TestPartResultArray::Append(), and result_.
Referenced by testing::internal::ShouldRunTestCase().
{
   result_->Append(result);
 }
virtual void testing::ScopedFakeTestPartResultReporter::ReportTestPartResult (const TestPartResult & result) virtual
Implements testing::TestPartResultReporterInterface.
Member Data Documentation
const InterceptMode testing::ScopedFakeTestPartResultReporter::intercept_mode_ private
Definition at line 82 of file gtest-spi.h.
Referenced by Init(), and ~ScopedFakeTestPartResultReporter().
TestPartResultReporterInterface * testing::ScopedFakeTestPartResultReporter::old_reporter_ private
Definition at line 83 of file gtest-spi.h.
Referenced by Init(), and ~ScopedFakeTestPartResultReporter().
TestPartResultArray *const testing::ScopedFakeTestPartResultReporter::result_ private
Definition at line 84 of file gtest-spi.h.
Referenced by ReportTestPartResult().
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/gtest-spi.h
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest.cc