proxygen: folly::ssl::OpenSSLHash Class Reference
folly::ssl::OpenSSLHash Class Reference
#include <OpenSSLHash.h>
Classes
class Digest
class Hmac
Static Public Member Functions
static void hash (MutableByteRange out, const EVP_MD *md, ByteRange data)
static void hash (MutableByteRange out, const EVP_MD *md, const IOBuf &data)
static void sha1 (MutableByteRange out, ByteRange data)
static void sha1 (MutableByteRange out, const IOBuf &data)
static void sha256 (MutableByteRange out, ByteRange data)
static void sha256 (MutableByteRange out, const IOBuf &data)
static void hmac (MutableByteRange out, const EVP_MD *md, ByteRange key, ByteRange data)
static void hmac (MutableByteRange out, const EVP_MD *md, ByteRange key, const IOBuf &data)
static void hmac_sha1 (MutableByteRange out, ByteRange key, ByteRange data)
static void hmac_sha1 (MutableByteRange out, ByteRange key, const IOBuf &data)
static void hmac_sha256 (MutableByteRange out, ByteRange key, ByteRange data)
static void hmac_sha256 (MutableByteRange out, ByteRange key, const IOBuf &data)
Static Private Member Functions
static void check_out_size (size_t size, MutableByteRange out)
static void check_out_size_throw (size_t size, MutableByteRange out)
static void check_libssl_result (int expected, int result)
Detailed Description
Warning: These functions are not thread-safe unless you initialize OpenSSL.
Definition at line 29 of file OpenSSLHash.h.
Member Function Documentation
static void folly::ssl::OpenSSLHash::check_libssl_result (int expected, int result) inline static private
Definition at line 176 of file OpenSSLHash.h.
References LIKELY.
Referenced by folly::ssl::OpenSSLHash::Digest::Digest(), folly::ssl::OpenSSLHash::Digest::hash_final(), folly::ssl::OpenSSLHash::Hmac::hash_final(), folly::ssl::OpenSSLHash::Digest::hash_init(), folly::ssl::OpenSSLHash::Hmac::hash_init(), folly::ssl::OpenSSLHash::Digest::hash_update(), and folly::ssl::OpenSSLHash::Hmac::hash_update().
{
     if (LIKELY(result == expected)) {
       return;
     }
     throw_exception<std::runtime_error>("openssl crypto function failed");
   }
static void folly::ssl::OpenSSLHash::check_out_size (size_t size, MutableByteRange out) inline static private
Definition at line 166 of file OpenSSLHash.h.
References check_out_size_throw(), LIKELY, folly::size(), and folly::Range< Iter >::size().
Referenced by folly::ssl::OpenSSLHash::Digest::hash_final(), and folly::ssl::OpenSSLHash::Hmac::hash_final().
{
     if (LIKELY(size == out.size())) {
       return;
     }
     check_out_size_throw(size, out);
   }
void folly::ssl::OpenSSLHash::check_out_size_throw (size_t size, MutableByteRange out) static private
Definition at line 24 of file OpenSSLHash.cpp.
References folly::sformat(), and folly::Range< Iter >::size().
Referenced by check_out_size().
{
   throw std::invalid_argument(folly::sformat(
       "expected out of size {} but was of size {}", size, out.size()));
 }
static void folly::ssl::OpenSSLHash::hash (MutableByteRange out, const EVP_MD * md, ByteRange data) inline static
Definition at line 76 of file OpenSSLHash.h.
References folly::ssl::OpenSSLHash::Digest::hash_final(), folly::ssl::OpenSSLHash::Digest::hash_init(), and folly::ssl::OpenSSLHash::Digest::hash_update().
Referenced by fizz::Sha< T >::hash(), hash(), sha1(), and sha256().
{
     Digest hash;
     hash.hash_init(md);
     hash.hash_update(data);
     hash.hash_final(out);
   }
static void folly::ssl::OpenSSLHash::hash (MutableByteRange out, const EVP_MD * md, const IOBuf & data) inline static
Definition at line 82 of file OpenSSLHash.h.
References hash(), folly::ssl::OpenSSLHash::Digest::hash_final(), folly::ssl::OpenSSLHash::Digest::hash_init(), and folly::ssl::OpenSSLHash::Digest::hash_update().
{
     Digest hash;
     hash.hash_init(md);
     hash.hash_update(data);
     hash.hash_final(out);
   }
static void folly::ssl::OpenSSLHash::hmac (MutableByteRange out, const EVP_MD * md, ByteRange key, ByteRange data) inline static
Definition at line 134 of file OpenSSLHash.h.
References folly::ssl::OpenSSLHash::Hmac::hash_final(), folly::ssl::OpenSSLHash::Hmac::hash_init(), and folly::ssl::OpenSSLHash::Hmac::hash_update().
Referenced by fizz::Sha< T >::hmac(), hmac(), hmac_sha1(), and hmac_sha256().
{
     Hmac hmac;
     hmac.hash_init(md, key);
     hmac.hash_update(data);
     hmac.hash_final(out);
   }
static void folly::ssl::OpenSSLHash::hmac (MutableByteRange out, const EVP_MD * md, ByteRange key, const IOBuf & data) inline static
Definition at line 140 of file OpenSSLHash.h.
References folly::ssl::OpenSSLHash::Hmac::hash_final(), folly::ssl::OpenSSLHash::Hmac::hash_init(), folly::ssl::OpenSSLHash::Hmac::hash_update(), and hmac().
{
     Hmac hmac;
     hmac.hash_init(md, key);
     hmac.hash_update(data);
     hmac.hash_final(out);
   }
static void folly::ssl::OpenSSLHash::hmac_sha1 (MutableByteRange out, ByteRange key, ByteRange data) inline static
Definition at line 150 of file OpenSSLHash.h.
References hmac().
{
     hmac(out, EVP_sha1(), key, data);
   }
static void folly::ssl::OpenSSLHash::hmac_sha1 (MutableByteRange out, ByteRange key, const IOBuf & data) inline static
Definition at line 154 of file OpenSSLHash.h.
References hmac().
{
     hmac(out, EVP_sha1(), key, data);
   }
static void folly::ssl::OpenSSLHash::hmac_sha256 (MutableByteRange out, ByteRange key, ByteRange data) inline static
Definition at line 157 of file OpenSSLHash.h.
References hmac().
{
     hmac(out, EVP_sha256(), key, data);
   }
static void folly::ssl::OpenSSLHash::hmac_sha256 (MutableByteRange out, ByteRange key, const IOBuf & data) inline static
Definition at line 161 of file OpenSSLHash.h.
References hmac().
{
     hmac(out, EVP_sha256(), key, data);
   }
static void folly::ssl::OpenSSLHash::sha1 (MutableByteRange out, ByteRange data) inline static
Definition at line 88 of file OpenSSLHash.h.
References hash().
{
     hash(out, EVP_sha1(), data);
   }
static void folly::ssl::OpenSSLHash::sha1 (MutableByteRange out, const IOBuf & data) inline static
Definition at line 91 of file OpenSSLHash.h.
References hash().
{
     hash(out, EVP_sha1(), data);
   }
static void folly::ssl::OpenSSLHash::sha256 (MutableByteRange out, ByteRange data) inline static
Definition at line 94 of file OpenSSLHash.h.
References hash().
{
     hash(out, EVP_sha256(), data);
   }
static void folly::ssl::OpenSSLHash::sha256 (MutableByteRange out, const IOBuf & data) inline static
Definition at line 97 of file OpenSSLHash.h.
References hash().
{
     hash(out, EVP_sha256(), data);
   }
The documentation for this class was generated from the following files:
proxygen/folly/folly/ssl/OpenSSLHash.h
proxygen/folly/folly/ssl/OpenSSLHash.cpp