proxygen: testing::Expectation Class Reference
testing::Expectation Class Reference
#include <gmock-spec-builders.h>
Classes
class Less
Public Member Functions
Expectation ()
~Expectation ()
Expectation (internal::ExpectationBase &exp)
bool operator== (const Expectation &rhs) const
bool operator!= (const Expectation &rhs) const
Expectation ()
~Expectation ()
Expectation (internal::ExpectationBase &exp)
bool operator== (const Expectation &rhs) const
bool operator!= (const Expectation &rhs) const
Expectation ()
~Expectation ()
Expectation (internal::ExpectationBase &exp)
bool operator== (const Expectation &rhs) const
bool operator!= (const Expectation &rhs) const
Private Types
typedef ::std::set< Expectation, Less > Set
typedef ::std::set< Expectation, Less > Set
typedef ::std::set< Expectation, Less > Set
Private Member Functions
Expectation (const internal::linked_ptr< internal::ExpectationBase > &expectation_base)
const internal::linked_ptr< internal::ExpectationBase > & expectation_base () const
Expectation (const internal::linked_ptr< internal::ExpectationBase > &expectation_base)
const internal::linked_ptr< internal::ExpectationBase > & expectation_base () const
Expectation (const internal::linked_ptr< internal::ExpectationBase > &expectation_base)
const internal::linked_ptr< internal::ExpectationBase > & expectation_base () const
Private Attributes
internal::linked_ptr< internal::ExpectationBase > expectation_base_
Friends
class ExpectationSet
class Sequence
class ::testing::internal::ExpectationBase
class ::testing::internal::UntypedFunctionMockerBase
template<typename F >
class ::testing::internal::FunctionMockerBase
template<typename F >
class ::testing::internal::TypedExpectation
Detailed Description
Definition at line 487 of file gmock-spec-builders.h.
Member Typedef Documentation
typedef ::std::set<Expectation, Less> testing::Expectation::Set private
Definition at line 535 of file gmock-spec-builders.h.
typedef ::std::set<Expectation, Less> testing::Expectation::Set private
Definition at line 535 of file gmock-spec-builders.h.
typedef ::std::set<Expectation, Less> testing::Expectation::Set private
Definition at line 535 of file gmock-spec-builders.h.
Constructor & Destructor Documentation
testing::Expectation::Expectation ()
Definition at line 785 of file gmock-spec-builders.cc.
Referenced by testing::internal::FunctionMockerBase< R(A1, A2)>::PrintTriedExpectationsLocked().
 {}
testing::Expectation::~Expectation ()
Definition at line 791 of file gmock-spec-builders.cc.
 {}
testing::Expectation::Expectation (internal::ExpectationBase & exp) inline
Definition at line 1829 of file gmock-spec-builders.h.
     : expectation_base_(exp.GetHandle().expectation_base()) {}
testing::Expectation::Expectation (const internal::linked_ptr< internal::ExpectationBase > & expectation_base) private
Definition at line 787 of file gmock-spec-builders.cc.
     : expectation_base_(an_expectation_base) {}
testing::Expectation::Expectation ()
testing::Expectation::~Expectation ()
testing::Expectation::Expectation (internal::ExpectationBase & exp)
testing::Expectation::Expectation (const internal::linked_ptr< internal::ExpectationBase > & expectation_base) private
testing::Expectation::Expectation ()
testing::Expectation::~Expectation ()
testing::Expectation::Expectation (internal::ExpectationBase & exp)
testing::Expectation::Expectation (const internal::linked_ptr< internal::ExpectationBase > & expectation_base) private
Member Function Documentation
const internal::linked_ptr<internal::ExpectationBase>& testing::Expectation::expectation_base () const inline private
Definition at line 542 of file gmock-spec-builders.h.
Referenced by testing::Sequence::AddExpectation(), and testing::internal::FunctionMockerBase< R(A1, A2)>::PrintTriedExpectationsLocked().
{
     return expectation_base_;
   }
const internal::linked_ptr<internal::ExpectationBase>& testing::Expectation::expectation_base () const inline private
Definition at line 542 of file gmock-spec-builders.h.
{
     return expectation_base_;
   }
const internal::linked_ptr<internal::ExpectationBase>& testing::Expectation::expectation_base () const inline private
Definition at line 542 of file gmock-spec-builders.h.
{
     return expectation_base_;
   }
bool testing::Expectation::operator!= (const Expectation & rhs) const inline
Definition at line 513 of file gmock-spec-builders.h.
References folly::detail::rhs.
 { return !(*this == rhs); }
bool testing::Expectation::operator!= (const Expectation & rhs) const inline
Definition at line 513 of file gmock-spec-builders.h.
References folly::detail::rhs.
 { return !(*this == rhs); }
bool testing::Expectation::operator!= (const Expectation & rhs) const inline
Definition at line 513 of file gmock-spec-builders.h.
References folly::detail::rhs.
 { return !(*this == rhs); }
bool testing::Expectation::operator== (const Expectation & rhs) const inline
Definition at line 509 of file gmock-spec-builders.h.
References expectation_base_.
{
     return expectation_base_ == rhs.expectation_base_;
   }
bool testing::Expectation::operator== (const Expectation & rhs) const inline
Definition at line 509 of file gmock-spec-builders.h.
References expectation_base_.
{
     return expectation_base_ == rhs.expectation_base_;
   }
bool testing::Expectation::operator== (const Expectation & rhs) const inline
Definition at line 509 of file gmock-spec-builders.h.
References expectation_base_.
{
     return expectation_base_ == rhs.expectation_base_;
   }
Friends And Related Function Documentation
friend class ::testing::internal::ExpectationBase friend
Definition at line 518 of file gmock-spec-builders.h.
template<typename F > friend class ::testing::internal::FunctionMockerBase friend
Definition at line 522 of file gmock-spec-builders.h.
template<typename F > friend class ::testing::internal::TypedExpectation friend
Definition at line 525 of file gmock-spec-builders.h.
friend class ::testing::internal::UntypedFunctionMockerBase friend
Definition at line 519 of file gmock-spec-builders.h.
ExpectationSet friend
Definition at line 516 of file gmock-spec-builders.h.
Sequence friend
Definition at line 517 of file gmock-spec-builders.h.
Member Data Documentation
internal::linked_ptr< internal::ExpectationBase > testing::Expectation::expectation_base_ private
Definition at line 547 of file gmock-spec-builders.h.
Referenced by testing::Expectation::Less::operator()(), and operator==().
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-spec-builders.h
proxygen/fizz/build_/gtest/src/gtest/googlemock/src/gmock-spec-builders.cc