proxygen: folly::gen::detail::Distinct< Selector >::Generator< Value, Source > Class Template Reference
folly::gen::detail::Distinct< Selector >::Generator< Value, Source > Class Template Reference
#include <Base-inl.h>
Public Member Functions
Generator (Source source, Selector selector)
template<class Body >
void foreach (Body &&body) const
template<class Handler >
bool apply (Handler &&handler) const
Public Member Functions inherited from folly::gen::GenImpl< Value, Generator< Value, Source > >
bool apply (Handler &&handler) const
void foreach (Body &&body) const
Public Member Functions inherited from folly::gen::FBounded< Self >
const Self & self () const
Self & self ()
Static Public Attributes
static constexpr bool infinite = Source::infinite
Static Public Attributes inherited from folly::gen::GenImpl< Value, Generator< Value, Source > >
static constexpr bool infinite
Private Types
typedef std::decay< Value >::type StorageType
typedef const StorageType & ParamType
typedef invoke_result_t< Selector, ParamType > KeyType
typedef std::decay< KeyType >::type KeyStorageType
Private Attributes
Source source_
Selector selector_
Additional Inherited Members
Public Types inherited from folly::gen::GenImpl< Value, Generator< Value, Source > >
typedef Value ValueType
typedef std::decay< Value >::type StorageType
Protected Member Functions inherited from folly::gen::GenImpl< Value, Generator< Value, Source > >
GenImpl ()=default
GenImpl (GenImpl &&)=default
GenImpl (const GenImpl &)=default
GenImpl & operator= (GenImpl &&)=default
GenImpl & operator= (const GenImpl &)=default
Detailed Description
template<class Selector>
template<class Value, class Source>
class folly::gen::detail::Distinct< Selector >::Generator< Value, Source >
Definition at line 1356 of file Base-inl.h.
Member Typedef Documentation
template<class Selector > template<class Value , class Source > typedef std::decay<KeyType>::type folly::gen::detail::Distinct< Selector >::Generator< Value, Source >::KeyStorageType private
Definition at line 1367 of file Base-inl.h.
template<class Selector > template<class Value , class Source > typedef invoke_result_t<Selector, ParamType> folly::gen::detail::Distinct< Selector >::Generator< Value, Source >::KeyType private
Definition at line 1366 of file Base-inl.h.
template<class Selector > template<class Value , class Source > typedef const StorageType& folly::gen::detail::Distinct< Selector >::Generator< Value, Source >::ParamType private
Definition at line 1364 of file Base-inl.h.
template<class Selector > template<class Value , class Source > typedef std::decay<Value>::type folly::gen::detail::Distinct< Selector >::Generator< Value, Source >::StorageType private
Definition at line 1360 of file Base-inl.h.
Constructor & Destructor Documentation
template<class Selector > template<class Value , class Source > folly::gen::detail::Distinct< Selector >::Generator< Value, Source >::Generator (Source source, Selector selector) inline
Definition at line 1370 of file Base-inl.h.
         : source_(std::move(source)), selector_(std::move(selector)) {}
Member Function Documentation
template<class Selector > template<class Value , class Source > template<class Handler > bool folly::gen::detail::Distinct< Selector >::Generator< Value, Source >::apply (Handler && handler) const inline
Definition at line 1384 of file Base-inl.h.
References handler(), value, and testing::Value().
{
       std::unordered_set<KeyStorageType> keysSeen;
       return source_.apply([&](Value value) -> bool {
         if (keysSeen.insert(selector_(ParamType(value))).second) {
           return handler(std::forward<Value>(value));
         }
         return true;
       });
     }
template<class Selector > template<class Value , class Source > template<class Body > void folly::gen::detail::Distinct< Selector >::Generator< Value, Source >::foreach (Body && body) const inline
Definition at line 1374 of file Base-inl.h.
References value, and testing::Value().
{
       std::unordered_set<KeyStorageType> keysSeen;
       source_.foreach([&](Value value) {
         if (keysSeen.insert(selector_(ParamType(value))).second) {
           body(std::forward<Value>(value));
         }
       });
     }
Member Data Documentation
template<class Selector > template<class Value , class Source > constexpr bool folly::gen::detail::Distinct< Selector >::Generator< Value, Source >::infinite = Source::infinite static
Definition at line 1396 of file Base-inl.h.
template<class Selector > template<class Value , class Source > Selector folly::gen::detail::Distinct< Selector >::Generator< Value, Source >::selector_ private
Definition at line 1358 of file Base-inl.h.
template<class Selector > template<class Value , class Source > Source folly::gen::detail::Distinct< Selector >::Generator< Value, Source >::source_ private
Definition at line 1357 of file Base-inl.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/gen/Base-inl.h