proxygen: testing::gmock_generated_function_mockers_test::MockOverloadedOnArgNumber Class Reference
testing::gmock_generated_function_mockers_test::MockOverloadedOnArgNumber Class Reference
Public Member Functions
MockOverloadedOnArgNumber ()
MOCK_METHOD0 (Overloaded, void())
MOCK_CONST_METHOD1 (Overloaded, int(int n))
MOCK_METHOD2 (Overloaded, bool(bool f, int n))
MockOverloadedOnArgNumber ()
MOCK_METHOD0 (Overloaded, void())
MOCK_CONST_METHOD1 (Overloaded, int(int n))
MOCK_METHOD2 (Overloaded, bool(bool f, int n))
MockOverloadedOnArgNumber ()
MOCK_METHOD0 (Overloaded, void())
MOCK_CONST_METHOD1 (Overloaded, int(int n))
MOCK_METHOD2 (Overloaded, bool(bool f, int n))
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockOverloadedOnArgNumber)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockOverloadedOnArgNumber)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockOverloadedOnArgNumber)
Detailed Description
Definition at line 510 of file gmock-generated-function-mockers_test.cc.
Constructor & Destructor Documentation
testing::gmock_generated_function_mockers_test::MockOverloadedOnArgNumber::MockOverloadedOnArgNumber () inline
Definition at line 512 of file gmock-generated-function-mockers_test.cc.
References GTEST_DISALLOW_COPY_AND_ASSIGN_, and MY_MOCK_METHODS1_.
 {}
testing::gmock_generated_function_mockers_test::MockOverloadedOnArgNumber::MockOverloadedOnArgNumber () inline
Definition at line 512 of file gmock-generated-function-mockers_test.cc.
References EXPECT_CALL, EXPECT_EQ, EXPECT_TRUE, GTEST_DISALLOW_COPY_AND_ASSIGN_, MY_MOCK_METHODS1_, testing::Return(), and testing::gmock_generated_function_mockers_test::TEST().
 {}
testing::gmock_generated_function_mockers_test::MockOverloadedOnArgNumber::MockOverloadedOnArgNumber () inline
Definition at line 512 of file gmock-generated-function-mockers_test.cc.
References EXPECT_CALL, EXPECT_EQ, EXPECT_TRUE, GTEST_DISALLOW_COPY_AND_ASSIGN_, MY_MOCK_METHODS1_, testing::Return(), and testing::gmock_generated_function_mockers_test::TEST().
 {}
Member Function Documentation
testing::gmock_generated_function_mockers_test::MockOverloadedOnArgNumber::GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockOverloadedOnArgNumber) private
testing::gmock_generated_function_mockers_test::MockOverloadedOnArgNumber::GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockOverloadedOnArgNumber) private
testing::gmock_generated_function_mockers_test::MockOverloadedOnArgNumber::GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockOverloadedOnArgNumber) private
testing::gmock_generated_function_mockers_test::MockOverloadedOnArgNumber::MOCK_CONST_METHOD1 (Overloaded , int(int n))
testing::gmock_generated_function_mockers_test::MockOverloadedOnArgNumber::MOCK_CONST_METHOD1 (Overloaded , int(int n))
testing::gmock_generated_function_mockers_test::MockOverloadedOnArgNumber::MOCK_CONST_METHOD1 (Overloaded , int(int n))
testing::gmock_generated_function_mockers_test::MockOverloadedOnArgNumber::MOCK_METHOD0 (Overloaded , void())
testing::gmock_generated_function_mockers_test::MockOverloadedOnArgNumber::MOCK_METHOD0 (Overloaded , void())
testing::gmock_generated_function_mockers_test::MockOverloadedOnArgNumber::MOCK_METHOD0 (Overloaded , void())
testing::gmock_generated_function_mockers_test::MockOverloadedOnArgNumber::MOCK_METHOD2 (Overloaded , bool(bool f, int n))
testing::gmock_generated_function_mockers_test::MockOverloadedOnArgNumber::MOCK_METHOD2 (Overloaded , bool(bool f, int n))
testing::gmock_generated_function_mockers_test::MockOverloadedOnArgNumber::MOCK_METHOD2 (Overloaded , bool(bool f, int n))
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-generated-function-mockers_test.cc