proxygen: wangle::SSLSessionPersistentCacheTest Class Reference
wangle::SSLSessionPersistentCacheTest Class Reference
Public Member Functions
SSLSessionPersistentCacheTest ()
void SetUp () override
void TearDown () override
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Protected Member Functions
void verifyEntryInCache (const std::string &hostname, std::pair< SSL_SESSION *, size_t > session, bool inCache=true)
Protected Member Functions inherited from testing::Test
Test ()
Test ()
Test ()
Protected Attributes
std::string filename_
MockTimeUtil * mockTimeUtil_
std::unique_ptr< SSLSessionPersistentCache > cache_
std::vector< std::pair< SSL_SESSION *, size_t > > sessions_
std::pair< SSL_SESSION *, size_t > sessionWithTicket_
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Detailed Description
Definition at line 50 of file SSLSessionPersistentCacheTest.cpp.
Constructor & Destructor Documentation
wangle::SSLSessionPersistentCacheTest::SSLSessionPersistentCacheTest () inline
Definition at line 52 of file SSLSessionPersistentCacheTest.cpp.
                                  :
     filename_(getPersistentCacheFilename()) {}
Member Function Documentation
void wangle::SSLSessionPersistentCacheTest::SetUp () inline override virtual
Reimplemented from testing::Test.
Definition at line 55 of file SSLSessionPersistentCacheTest.cpp.
References wangle::getSessions(), and wangle::getSessionWithTicket().
{
     for (auto& it : getSessions()) {
       sessions_.emplace_back(it.first, it.second);
     }
     sessionWithTicket_ = getSessionWithTicket();
     sessions_.emplace_back(sessionWithTicket_.first, sessionWithTicket_.second);
     // Create the cache fresh for each test
     mockTimeUtil_ = new MockTimeUtil();
     cache_.reset(new SSLSessionPersistentCache(filename_,
                                       50, std::chrono::seconds(150)));
     cache_->setTimeUtil(
         std::unique_ptr<SSLSessionPersistentCache::TimeUtil>(mockTimeUtil_));
   }
void wangle::SSLSessionPersistentCacheTest::TearDown () inline override virtual
Reimplemented from testing::Test.
Definition at line 70 of file SSLSessionPersistentCacheTest.cpp.
References EXPECT_TRUE.
{
     for (const auto& it : sessions_) {
       SSL_SESSION_free(it.first);
     }
     sessions_.clear();
     cache_.reset();
     EXPECT_TRUE(unlink(filename_.c_str()) != -1);
   }
void wangle::SSLSessionPersistentCacheTest::verifyEntryInCache (const std::string & hostname, std::pair< SSL_SESSION *, size_t > session, bool inCache = true) inline protected
Definition at line 80 of file SSLSessionPersistentCacheTest.cpp.
References ASSERT_FALSE, ASSERT_TRUE, wangle::isSameSession(), and s.
{
     auto s = cache_->getSSLSession(hostname);
     if (inCache) {
       ASSERT_TRUE(s != nullptr);
       ASSERT_TRUE(
           isSameSession(
             session,
             std::make_pair(s.get(), session.second)));
     } else {
       ASSERT_FALSE(s);
     }
   }
Member Data Documentation
std::unique_ptr<SSLSessionPersistentCache> wangle::SSLSessionPersistentCacheTest::cache_ protected
Definition at line 98 of file SSLSessionPersistentCacheTest.cpp.
std::string wangle::SSLSessionPersistentCacheTest::filename_ protected
Definition at line 96 of file SSLSessionPersistentCacheTest.cpp.
MockTimeUtil* wangle::SSLSessionPersistentCacheTest::mockTimeUtil_ protected
Definition at line 97 of file SSLSessionPersistentCacheTest.cpp.
std::vector<std::pair<SSL_SESSION*, size_t> > wangle::SSLSessionPersistentCacheTest::sessions_ protected
Definition at line 99 of file SSLSessionPersistentCacheTest.cpp.
std::pair<SSL_SESSION*, size_t> wangle::SSLSessionPersistentCacheTest::sessionWithTicket_ protected
Definition at line 100 of file SSLSessionPersistentCacheTest.cpp.
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/client/ssl/test/SSLSessionPersistentCacheTest.cpp