proxygen: folly::futures::detail::CoreCallbackState< T, F > Class Template Reference
folly::futures::detail::CoreCallbackState< T, F > Class Template Reference
#include <Future-inl.h>
Public Member Functions
CoreCallbackState (Promise< T > &&promise, F &&func) noexcept(noexcept(DF(std::declval< F && >())))
CoreCallbackState (CoreCallbackState &&that) noexcept(noexcept(DF(std::declval< F && >())))
CoreCallbackState & operator= (CoreCallbackState &&)=delete
~CoreCallbackState ()
template<typename... Args>
auto invoke (Args &&...args) noexcept(noexcept(std::declval< F && >()(std::declval< Args && >()...)))
template<typename... Args>
auto tryInvoke (Args &&...args) noexcept
void setTry (Try< T > &&t)
void setException (exception_wrapper &&ew)
Promise< T > stealPromise () noexcept
Private Types
using DF = _t< std::decay< F >>
Private Member Functions
bool before_barrier () const noexcept
Private Attributes
union {
DF func_
};
Promise< T > promise_ {Promise<T>::makeEmpty()}
Detailed Description
template<typename T, typename F>
class folly::futures::detail::CoreCallbackState< T, F >
Definition at line 61 of file Future-inl.h.
Member Typedef Documentation
template<typename T , typename F > using folly::futures::detail::CoreCallbackState< T, F >::DF = _t<std::decay<F>> private
Definition at line 62 of file Future-inl.h.
Constructor & Destructor Documentation
template<typename T , typename F > folly::futures::detail::CoreCallbackState< T, F >::CoreCallbackState (Promise< T > && promise, F && func) inline noexcept
Definition at line 65 of file Future-inl.h.
       : func_(std::forward<F>(func)), promise_(std::move(promise)) {
     assert(before_barrier());
   }
template<typename T , typename F > folly::futures::detail::CoreCallbackState< T, F >::CoreCallbackState (CoreCallbackState< T, F > && that) inline noexcept
Definition at line 71 of file Future-inl.h.
References promise_.
{
     if (that.before_barrier()) {
       new (&func_) DF(std::forward<F>(that.func_));
       promise_ = that.stealPromise();
     }
   }
template<typename T , typename F > folly::futures::detail::CoreCallbackState< T, F >::~CoreCallbackState () inline
Definition at line 81 of file Future-inl.h.
References testing::Args().
{
     if (before_barrier()) {
       stealPromise();
     }
   }
Member Function Documentation
template<typename T , typename F > bool folly::futures::detail::CoreCallbackState< T, F >::before_barrier () const inline private noexcept
Definition at line 114 of file Future-inl.h.
References promise_.
{
     return !promise_.isFulfilled();
   }
template<typename T , typename F > template<typename... Args> auto folly::futures::detail::CoreCallbackState< T, F >::invoke (Args &&... args) inline noexcept
Definition at line 88 of file Future-inl.h.
References testing::Args().
{
     assert(before_barrier());
     return std::forward<F>(func_)(std::forward<Args>(args)...);
   }
template<typename T , typename F > CoreCallbackState& folly::futures::detail::CoreCallbackState< T, F >::operator= (CoreCallbackState< T, F > &&) delete
template<typename T , typename F > void folly::futures::detail::CoreCallbackState< T, F >::setException (exception_wrapper && ew) inline
Definition at line 103 of file Future-inl.h.
References folly::gen::move.
{
     stealPromise().setException(std::move(ew));
   }
template<typename T , typename F > void folly::futures::detail::CoreCallbackState< T, F >::setTry (Try< T > && t) inline
Definition at line 99 of file Future-inl.h.
References folly::gen::move, and folly::pushmi::detail::t.
{
     stealPromise().setTry(std::move(t));
   }
template<typename T , typename F > Promise<T> folly::futures::detail::CoreCallbackState< T, F >::stealPromise () inline noexcept
Definition at line 107 of file Future-inl.h.
References folly::gen::move, and promise_.
{
     assert(before_barrier());
     func_.~DF();
     return std::move(promise_);
   }
template<typename T , typename F > template<typename... Args> auto folly::futures::detail::CoreCallbackState< T, F >::tryInvoke (Args &&... args) inline noexcept
Definition at line 95 of file Future-inl.h.
References folly::invoke(), and folly::makeTryWith().
{
     return makeTryWith([&] { return invoke(std::forward<Args>(args)...); });
   }
Member Data Documentation
union { ... }
template<typename T , typename F > DF folly::futures::detail::CoreCallbackState< T, F >::func_
Definition at line 119 of file Future-inl.h.
template<typename T , typename F > Promise<T> folly::futures::detail::CoreCallbackState< T, F >::promise_ {Promise<T>::makeEmpty()} private
Definition at line 121 of file Future-inl.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/futures/Future-inl.h