proxygen: folly::ssl::OpenSSLHash::Digest Class Reference
folly::ssl::OpenSSLHash::Digest Class Reference
#include <OpenSSLHash.h>
Public Member Functions
Digest ()
Digest (const Digest &other)
Digest & operator= (const Digest &other)
void hash_init (const EVP_MD *md)
void hash_update (ByteRange data)
void hash_update (const IOBuf &data)
void hash_final (MutableByteRange out)
Private Attributes
const EVP_MD * md_ = nullptr
EvpMdCtxUniquePtr ctx_ {nullptr}
Detailed Description
Definition at line 31 of file OpenSSLHash.h.
Constructor & Destructor Documentation
folly::ssl::OpenSSLHash::Digest::Digest () inline
Definition at line 33 of file OpenSSLHash.h.
Referenced by operator=().
 : ctx_(EVP_MD_CTX_new()) {}
folly::ssl::OpenSSLHash::Digest::Digest (const Digest & other) inline
Definition at line 35 of file OpenSSLHash.h.
References folly::ssl::OpenSSLHash::check_libssl_result(), ctx_, folly::portability::ssl::EVP_MD_CTX_new(), hash_init(), and md_.
{
       ctx_ = EvpMdCtxUniquePtr(EVP_MD_CTX_new());
       if (other.md_ != nullptr) {
         hash_init(other.md_);
         check_libssl_result(
             1, EVP_MD_CTX_copy_ex(ctx_.get(), other.ctx_.get()));
       }
     }
Member Function Documentation
void folly::ssl::OpenSSLHash::Digest::hash_final (MutableByteRange out) inline
Definition at line 62 of file OpenSSLHash.h.
References folly::ssl::OpenSSLHash::check_libssl_result(), folly::ssl::OpenSSLHash::check_out_size(), ctx_, folly::Range< Iter >::data(), md_, and folly::size().
Referenced by proxygen::HTTP1xCodec::generateWebsocketAccept(), fizz::HandshakeContextImpl< Hash >::getHandshakeContext(), folly::ssl::OpenSSLHash::hash(), and TEST_F().
{
       const auto size = EVP_MD_size(md_);
       check_out_size(size_t(size), out);
       unsigned int len = 0;
       check_libssl_result(1, EVP_DigestFinal_ex(ctx_.get(), out.data(), &len));
       check_libssl_result(size, int(len));
       md_ = nullptr;
     }
void folly::ssl::OpenSSLHash::Digest::hash_init (const EVP_MD * md) inline
Definition at line 49 of file OpenSSLHash.h.
References folly::ssl::OpenSSLHash::check_libssl_result(), ctx_, and md_.
Referenced by Digest(), proxygen::HTTP1xCodec::generateWebsocketAccept(), fizz::HandshakeContextImpl< Hash >::HandshakeContextImpl(), folly::ssl::OpenSSLHash::hash(), and TEST_F().
{
       md_ = md;
       check_libssl_result(1, EVP_DigestInit_ex(ctx_.get(), md, nullptr));
     }
void folly::ssl::OpenSSLHash::Digest::hash_update (ByteRange data) inline
Definition at line 53 of file OpenSSLHash.h.
References folly::ssl::OpenSSLHash::check_libssl_result(), ctx_, folly::Range< Iter >::data(), and folly::Range< Iter >::size().
Referenced by fizz::HandshakeContextImpl< Hash >::appendToTranscript(), proxygen::HTTP1xCodec::generateWebsocketAccept(), folly::ssl::OpenSSLHash::hash(), hash_update(), folly::ssl::OpenSSLHash::Hmac::hash_update(), and TEST_F().
{
       check_libssl_result(
           1, EVP_DigestUpdate(ctx_.get(), data.data(), data.size()));
     }
void folly::ssl::OpenSSLHash::Digest::hash_update (const IOBuf & data) inline
Definition at line 57 of file OpenSSLHash.h.
References hash_update().
{
       for (auto r : data) {
         hash_update(r);
       }
     }
Digest& folly::ssl::OpenSSLHash::Digest::operator= (const Digest & other) inline
Definition at line 44 of file OpenSSLHash.h.
References Digest().
{
       this->~Digest();
       return *new (this) Digest(other);
     }
Member Data Documentation
EvpMdCtxUniquePtr folly::ssl::OpenSSLHash::Digest::ctx_ {nullptr} private
Definition at line 73 of file OpenSSLHash.h.
Referenced by Digest(), hash_final(), folly::ssl::OpenSSLHash::Hmac::hash_final(), hash_init(), folly::ssl::OpenSSLHash::Hmac::hash_init(), hash_update(), and folly::ssl::OpenSSLHash::Hmac::hash_update().
const EVP_MD* folly::ssl::OpenSSLHash::Digest::md_ = nullptr private
Definition at line 72 of file OpenSSLHash.h.
Referenced by Digest(), hash_final(), folly::ssl::OpenSSLHash::Hmac::hash_final(), hash_init(), and folly::ssl::OpenSSLHash::Hmac::hash_init().
The documentation for this class was generated from the following file:
proxygen/folly/folly/ssl/OpenSSLHash.h