proxygen: cpp.ast.Node Class Reference
cpp.ast.Node Class Reference
Public Member Functions
def __init__ (self, start, end)
def IsDeclaration (self)
def IsDefinition (self)
def IsExportable (self)
def Requires (self, node)
def XXX__str__ (self)
def __repr__ (self)
def __init__ (self, start, end)
def IsDeclaration (self)
def IsDefinition (self)
def IsExportable (self)
def Requires (self, node)
def XXX__str__ (self)
def __repr__ (self)
def __init__ (self, start, end)
def IsDeclaration (self)
def IsDefinition (self)
def IsExportable (self)
def Requires (self, node)
def XXX__str__ (self)
def __repr__ (self)
Public Attributes
start
end
Private Member Functions
def _StringHelper (self, name, suffix)
def _StringHelper (self, name, suffix)
def _StringHelper (self, name, suffix)
Detailed Description
Base AST node.
Definition at line 109 of file ast.py.
Constructor & Destructor Documentation
def cpp.ast.Node.__init__ (self, start, end)
Definition at line 112 of file ast.py.
Referenced by cpp.ast.Node.__init__().
     def __init__(self, start, end):
         self.start = start
         self.end = end
def cpp.ast.Node.__init__ (self, start, end)
Definition at line 112 of file ast.py.
References cpp.ast.Node.__init__(), cpp.ast.Node.end, and cpp.ast.Node.start.
     def __init__(self, start, end):
         self.start = start
         self.end = end
def cpp.ast.Node.__init__ (self, start, end)
Definition at line 112 of file ast.py.
References cpp.ast.Node.__init__(), cpp.ast.Node.end, and cpp.ast.Node.start.
     def __init__(self, start, end):
         self.start = start
         self.end = end
Member Function Documentation
def cpp.ast.Node.__repr__ (self)
Definition at line 140 of file ast.py.
Referenced by cpp.ast.Node.__repr__().
     def __repr__(self):
         return str(self)
def cpp.ast.Node.__repr__ (self)
Definition at line 140 of file ast.py.
References cpp.ast.Node.__repr__().
     def __repr__(self):
         return str(self)
def cpp.ast.Node.__repr__ (self)
Definition at line 140 of file ast.py.
References cpp.ast.Node.__repr__().
     def __repr__(self):
         return str(self)
def cpp.ast.Node._StringHelper (self, name, suffix) private
Definition at line 135 of file ast.py.
References cpp.ast.Node._StringHelper(), cpp.ast.Node.end, and cpp.ast.Node.start.
     def _StringHelper(self, name, suffix):
         if not utils.DEBUG:
             return '%s(%s)' % (name, suffix)
         return '%s(%d, %d, %s)' % (name, self.start, self.end, suffix)
def cpp.ast.Node._StringHelper (self, name, suffix) private
Definition at line 135 of file ast.py.
References cpp.ast.Node._StringHelper(), cpp.ast.Node.end, and cpp.ast.Node.start.
     def _StringHelper(self, name, suffix):
         if not utils.DEBUG:
             return '%s(%s)' % (name, suffix)
         return '%s(%d, %d, %s)' % (name, self.start, self.end, suffix)
def cpp.ast.Node._StringHelper (self, name, suffix) private
Definition at line 135 of file ast.py.
References cpp.ast.Node.end, and cpp.ast.Node.start.
Referenced by cpp.ast.Define.__str__(), cpp.ast.Include.__str__(), cpp.ast.Goto.__str__(), cpp.ast.Expr.__str__(), cpp.ast.Using.__str__(), cpp.ast.Parameter.__str__(), cpp.ast.VariableDeclaration.__str__(), cpp.ast.Node._StringHelper(), cpp.ast._GenericDeclaration._TypeStringHelper(), and cpp.ast.Node.XXX__str__().
     def _StringHelper(self, name, suffix):
         if not utils.DEBUG:
             return '%s(%s)' % (name, suffix)
         return '%s(%d, %d, %s)' % (name, self.start, self.end, suffix)
def cpp.ast.Node.IsDeclaration (self)
Returns bool if this node is a declaration.
Definition at line 116 of file ast.py.
References cpp.ast.Node.IsDeclaration().
     def IsDeclaration(self):
         """Returns bool if this node is a declaration."""
         return False
def cpp.ast.Node.IsDeclaration (self)
Returns bool if this node is a declaration.
Definition at line 116 of file ast.py.
Referenced by cpp.ast.Node.IsDeclaration(), cpp.ast.Class.IsDefinition(), and cpp.ast.Class.IsExportable().
     def IsDeclaration(self):
         """Returns bool if this node is a declaration."""
         return False
def cpp.ast.Node.IsDeclaration (self)
Returns bool if this node is a declaration.
Definition at line 116 of file ast.py.
References cpp.ast.Node.IsDeclaration().
     def IsDeclaration(self):
         """Returns bool if this node is a declaration."""
         return False
def cpp.ast.Node.IsDefinition (self)
Returns bool if this node is a definition.
Definition at line 120 of file ast.py.
Referenced by cpp.ast.Node.IsDefinition().
     def IsDefinition(self):
         """Returns bool if this node is a definition."""
         return False
def cpp.ast.Node.IsDefinition (self)
Returns bool if this node is a definition.
Definition at line 120 of file ast.py.
References cpp.ast.Node.IsDefinition().
     def IsDefinition(self):
         """Returns bool if this node is a definition."""
         return False
def cpp.ast.Node.IsDefinition (self)
Returns bool if this node is a definition.
Definition at line 120 of file ast.py.
References cpp.ast.Node.IsDefinition().
     def IsDefinition(self):
         """Returns bool if this node is a definition."""
         return False
def cpp.ast.Node.IsExportable (self)
Returns bool if this node exportable from a header file.
Definition at line 124 of file ast.py.
References cpp.ast.Node.IsExportable().
     def IsExportable(self):
         """Returns bool if this node exportable from a header file."""
         return False
def cpp.ast.Node.IsExportable (self)
Returns bool if this node exportable from a header file.
Definition at line 124 of file ast.py.
Referenced by cpp.ast.Node.IsExportable().
     def IsExportable(self):
         """Returns bool if this node exportable from a header file."""
         return False
def cpp.ast.Node.IsExportable (self)
Returns bool if this node exportable from a header file.
Definition at line 124 of file ast.py.
References cpp.ast.Node.IsExportable().
     def IsExportable(self):
         """Returns bool if this node exportable from a header file."""
         return False
def cpp.ast.Node.Requires (self, node)
Does this AST node require the definition of the node passed in?
Definition at line 128 of file ast.py.
Referenced by cpp.ast.Node.Requires().
     def Requires(self, node):
         """Does this AST node require the definition of the node passed in?"""
         return False
def cpp.ast.Node.Requires (self, node)
Does this AST node require the definition of the node passed in?
Definition at line 128 of file ast.py.
References cpp.ast.Node.Requires().
     def Requires(self, node):
         """Does this AST node require the definition of the node passed in?"""
         return False
def cpp.ast.Node.Requires (self, node)
Does this AST node require the definition of the node passed in?
Definition at line 128 of file ast.py.
References cpp.ast.Node.Requires().
     def Requires(self, node):
         """Does this AST node require the definition of the node passed in?"""
         return False
def cpp.ast.Node.XXX__str__ (self)
Definition at line 132 of file ast.py.
References cpp.ast.Node._StringHelper(), and cpp.ast.Node.XXX__str__().
     def XXX__str__(self):
         return self._StringHelper(self.__class__.__name__, '')
def cpp.ast.Node.XXX__str__ (self)
Definition at line 132 of file ast.py.
References cpp.ast.Node._StringHelper().
Referenced by cpp.ast.Node.XXX__str__().
     def XXX__str__(self):
         return self._StringHelper(self.__class__.__name__, '')
def cpp.ast.Node.XXX__str__ (self)
Definition at line 132 of file ast.py.
References cpp.ast.Node._StringHelper(), and cpp.ast.Node.XXX__str__().
     def XXX__str__(self):
         return self._StringHelper(self.__class__.__name__, '')
Member Data Documentation
cpp.ast.Node.end
Definition at line 114 of file ast.py.
Referenced by cpp.tokenize.Token.__init__(), cpp.ast.Node.__init__(), pump.Token.__init__(), cpp.tokenize.Token.__str__(), and cpp.ast.Node._StringHelper().
cpp.ast.Node.start
Definition at line 113 of file ast.py.
Referenced by cpp.tokenize.Token.__init__(), cpp.ast.Node.__init__(), pump.Token.__init__(), cpp.tokenize.Token.__str__(), pump.Token.__str__(), and cpp.ast.Node._StringHelper().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/scripts/generator/cpp/ast.py