proxygen: testing::DefaultValue< T > Class Template Reference
testing::DefaultValue< T > Class Template Reference
#include <gmock-actions.h>
Classes
class FactoryValueProducer
class FixedValueProducer
class ValueProducer
Public Types
typedef T(* FactoryFunction) ()
typedef T(* FactoryFunction) ()
typedef T(* FactoryFunction) ()
Static Public Member Functions
static void Set (T x)
static void SetFactory (FactoryFunction factory)
static void Clear ()
static bool IsSet ()
static bool Exists ()
static T Get ()
static void Set (T x)
static void SetFactory (FactoryFunction factory)
static void Clear ()
static bool IsSet ()
static bool Exists ()
static T Get ()
static void Set (T x)
static void SetFactory (FactoryFunction factory)
static void Clear ()
static bool IsSet ()
static bool Exists ()
static T Get ()
Static Private Attributes
static ValueProducer * producer_ = NULL
Detailed Description
template<typename T>
class testing::DefaultValue< T >
Definition at line 200 of file gmock-actions.h.
Member Typedef Documentation
template<typename T > typedef T(* testing::DefaultValue< T >::FactoryFunction) ()
Definition at line 212 of file gmock-actions.h.
template<typename T > typedef T(* testing::DefaultValue< T >::FactoryFunction) ()
Definition at line 212 of file gmock-actions.h.
template<typename T > typedef T(* testing::DefaultValue< T >::FactoryFunction) ()
Definition at line 212 of file gmock-actions.h.
Member Function Documentation
template<typename T > static void testing::DefaultValue< T >::Clear () inline static
Definition at line 219 of file gmock-actions.h.
                       {
     delete producer_;
     producer_ = NULL;
   }
template<typename T > static void testing::DefaultValue< T >::Clear () inline static
Definition at line 219 of file gmock-actions.h.
                       {
     delete producer_;
     producer_ = NULL;
   }
template<typename T > static void testing::DefaultValue< T >::Clear () inline static
Definition at line 219 of file gmock-actions.h.
                       {
     delete producer_;
     producer_ = NULL;
   }
template<typename T > static bool testing::DefaultValue< T >::Exists () inline static
Definition at line 229 of file gmock-actions.h.
References testing::internal::BuiltInDefaultValue< T >::Exists().
{
     return IsSet() || internal::BuiltInDefaultValue<T>::Exists();
   }
template<typename T > static bool testing::DefaultValue< T >::Exists () inline static
Definition at line 229 of file gmock-actions.h.
References testing::internal::BuiltInDefaultValue< T >::Exists().
{
     return IsSet() || internal::BuiltInDefaultValue<T>::Exists();
   }
template<typename T > static bool testing::DefaultValue< T >::Exists () inline static
Definition at line 229 of file gmock-actions.h.
References testing::internal::BuiltInDefaultValue< T >::Exists().
{
     return IsSet() || internal::BuiltInDefaultValue<T>::Exists();
   }
template<typename T > static T testing::DefaultValue< T >::Get () inline static
Definition at line 236 of file gmock-actions.h.
References testing::internal::BuiltInDefaultValue< T >::Get().
                  {
     return producer_ == NULL ?
         internal::BuiltInDefaultValue<T>::Get() : producer_->Produce();
   }
template<typename T > static T testing::DefaultValue< T >::Get () inline static
Definition at line 236 of file gmock-actions.h.
References testing::internal::BuiltInDefaultValue< T >::Get().
                  {
     return producer_ == NULL ?
         internal::BuiltInDefaultValue<T>::Get() : producer_->Produce();
   }
template<typename T > static T testing::DefaultValue< T >::Get () inline static
Definition at line 236 of file gmock-actions.h.
References testing::internal::BuiltInDefaultValue< T >::Get().
Referenced by testing::internal::FunctionMockerBase< R(A1, A2)>::PerformDefaultAction().
                  {
     return producer_ == NULL ?
         internal::BuiltInDefaultValue<T>::Get() : producer_->Produce();
   }
template<typename T > static bool testing::DefaultValue< T >::IsSet () inline static
Definition at line 225 of file gmock-actions.h.
 { return producer_ != NULL; }
template<typename T > static bool testing::DefaultValue< T >::IsSet () inline static
Definition at line 225 of file gmock-actions.h.
 { return producer_ != NULL; }
template<typename T > static bool testing::DefaultValue< T >::IsSet () inline static
Definition at line 225 of file gmock-actions.h.
 { return producer_ != NULL; }
template<typename T > static void testing::DefaultValue< T >::Set (T x) inline static
Definition at line 204 of file gmock-actions.h.
{
     delete producer_;
     producer_ = new FixedValueProducer(x);
   }
template<typename T > static void testing::DefaultValue< T >::Set (T x) inline static
Definition at line 204 of file gmock-actions.h.
{
     delete producer_;
     producer_ = new FixedValueProducer(x);
   }
template<typename T > static void testing::DefaultValue< T >::Set (T x) inline static
Definition at line 204 of file gmock-actions.h.
{
     delete producer_;
     producer_ = new FixedValueProducer(x);
   }
template<typename T > static void testing::DefaultValue< T >::SetFactory (FactoryFunction factory) inline static
Definition at line 213 of file gmock-actions.h.
{
     delete producer_;
     producer_ = new FactoryValueProducer(factory);
   }
template<typename T > static void testing::DefaultValue< T >::SetFactory (FactoryFunction factory) inline static
Definition at line 213 of file gmock-actions.h.
{
     delete producer_;
     producer_ = new FactoryValueProducer(factory);
   }
template<typename T > static void testing::DefaultValue< T >::SetFactory (FactoryFunction factory) inline static
Definition at line 213 of file gmock-actions.h.
{
     delete producer_;
     producer_ = new FactoryValueProducer(factory);
   }
Member Data Documentation
template<typename T > DefaultValue< T >::ValueProducer * testing::DefaultValue< T >::producer_ = NULL static private
Definition at line 269 of file gmock-actions.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-actions.h