proxygen: testing::internal::String Class Reference
testing::internal::String Class Reference
#include <gtest-string.h>
Static Public Member Functions
static const char * CloneCString (const char *c_str)
static bool CStringEquals (const char *lhs, const char *rhs)
static std::string ShowWideCString (const wchar_t *wide_c_str)
static bool WideCStringEquals (const wchar_t *lhs, const wchar_t *rhs)
static bool CaseInsensitiveCStringEquals (const char *lhs, const char *rhs)
static bool CaseInsensitiveWideCStringEquals (const wchar_t *lhs, const wchar_t *rhs)
static bool EndsWithCaseInsensitive (const std::string &str, const std::string &suffix)
static std::string FormatIntWidth2 (int value)
static std::string FormatHexInt (int value)
static std::string FormatByte (unsigned char value)
static const char * CloneCString (const char *c_str)
static bool CStringEquals (const char *lhs, const char *rhs)
static std::string ShowWideCString (const wchar_t *wide_c_str)
static bool WideCStringEquals (const wchar_t *lhs, const wchar_t *rhs)
static bool CaseInsensitiveCStringEquals (const char *lhs, const char *rhs)
static bool CaseInsensitiveWideCStringEquals (const wchar_t *lhs, const wchar_t *rhs)
static bool EndsWithCaseInsensitive (const std::string &str, const std::string &suffix)
static std::string FormatIntWidth2 (int value)
static std::string FormatHexInt (int value)
static std::string FormatByte (unsigned char value)
static const char * CloneCString (const char *c_str)
static bool CStringEquals (const char *lhs, const char *rhs)
static std::string ShowWideCString (const wchar_t *wide_c_str)
static bool WideCStringEquals (const wchar_t *lhs, const wchar_t *rhs)
static bool CaseInsensitiveCStringEquals (const char *lhs, const char *rhs)
static bool CaseInsensitiveWideCStringEquals (const wchar_t *lhs, const wchar_t *rhs)
static bool EndsWithCaseInsensitive (const std::string &str, const std::string &suffix)
static std::string FormatIntWidth2 (int value)
static std::string FormatHexInt (int value)
static std::string FormatByte (unsigned char value)
Private Member Functions
String ()
String ()
String ()
Detailed Description
Definition at line 58 of file gtest-string.h.
Constructor & Destructor Documentation
testing::internal::String::String () private
testing::internal::String::String () private
testing::internal::String::String () private
Member Function Documentation
bool testing::internal::String::CaseInsensitiveCStringEquals (const char * lhs, const char * rhs) static
Definition at line 1905 of file gtest.cc.
References testing::internal::posix::StrCaseCmp().
{
   if (lhs == NULL)
     return rhs == NULL;
   if (rhs == NULL)
     return false;
   return posix::StrCaseCmp(lhs, rhs) == 0;
 }
static bool testing::internal::String::CaseInsensitiveCStringEquals (const char * lhs, const char * rhs) static
static bool testing::internal::String::CaseInsensitiveCStringEquals (const char * lhs, const char * rhs) static
static bool testing::internal::String::CaseInsensitiveWideCStringEquals (const wchar_t * lhs, const wchar_t * rhs) static
static bool testing::internal::String::CaseInsensitiveWideCStringEquals (const wchar_t * lhs, const wchar_t * rhs) static
bool testing::internal::String::CaseInsensitiveWideCStringEquals (const wchar_t * lhs, const wchar_t * rhs) static
Definition at line 1925 of file gtest.cc.
Referenced by operator<<().
{
   if (lhs == NULL) return rhs == NULL;
   if (rhs == NULL) return false;
 #if GTEST_OS_WINDOWS
   return _wcsicmp(lhs, rhs) == 0;
 #elif GTEST_OS_LINUX && !GTEST_OS_LINUX_ANDROID
   return wcscasecmp(lhs, rhs) == 0;
 #else
   // Android, Mac OS X and Cygwin don't define wcscasecmp.
   // Other unknown OSes may not define it either.
   wint_t left, right;
   do {
     left = towlower(*lhs++);
     right = towlower(*rhs++);
   } while (left && left == right);
   return left == right;
 #endif  // OS selector
 }
static const char* testing::internal::String::CloneCString (const char * c_str) static
static const char* testing::internal::String::CloneCString (const char * c_str) static
static const char* testing::internal::String::CloneCString (const char * c_str) static
bool testing::internal::String::CStringEquals (const char * lhs, const char * rhs) static
Definition at line 894 of file gtest.cc.
References i.
Referenced by testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), and testing::internal::ShouldRunTestCase().
{
   if ( lhs == NULL ) return rhs == NULL;
   if ( rhs == NULL ) return false;
   return strcmp(lhs, rhs) == 0;
 }
static bool testing::internal::String::CStringEquals (const char * lhs, const char * rhs) static
static bool testing::internal::String::CStringEquals (const char * lhs, const char * rhs) static
static bool testing::internal::String::EndsWithCaseInsensitive (const std::string & str, const std::string & suffix) static
static bool testing::internal::String::EndsWithCaseInsensitive (const std::string & str, const std::string & suffix) static
bool testing::internal::String::EndsWithCaseInsensitive (const std::string & str, const std::string & suffix) static
Definition at line 1949 of file gtest.cc.
References testing::internal::CaseInsensitiveCStringEquals().
Referenced by testing::internal::IsPathSeparator(), operator<<(), and testing::internal::FilePath::RemoveExtension().
{
   const size_t str_len = str.length();
   const size_t suffix_len = suffix.length();
   return (str_len >= suffix_len) &&
          CaseInsensitiveCStringEquals(str.c_str() + str_len - suffix_len,
                                       suffix.c_str());
 }
static std::string testing::internal::String::FormatByte (unsigned char value) static
std::string testing::internal::String::FormatByte (unsigned char value) static
Definition at line 1973 of file gtest.cc.
References value.
Referenced by testing::internal::XmlUnitTestResultPrinter::EscapeXml(), testing::internal::XmlUnitTestResultPrinter::EscapeXmlText(), testing::internal::PortableLocaltime(), and testing::internal::XmlUnitTestResultPrinter::TestPropertiesAsXmlAttributes().
{
   std::stringstream ss;
   ss << std::setfill('0') << std::setw(2) << std::hex << std::uppercase
      << static_cast<unsigned int>(value);
   return ss.str();
 }
static std::string testing::internal::String::FormatByte (unsigned char value) static
std::string testing::internal::String::FormatHexInt (int value) static
Definition at line 1966 of file gtest.cc.
References value.
{
   std::stringstream ss;
   ss << std::hex << std::uppercase << value;
   return ss.str();
 }
static std::string testing::internal::String::FormatHexInt (int value) static
static std::string testing::internal::String::FormatHexInt (int value) static
static std::string testing::internal::String::FormatIntWidth2 (int value) static
std::string testing::internal::String::FormatIntWidth2 (int value) static
Definition at line 1959 of file gtest.cc.
References value.
Referenced by testing::internal::FormatEpochTimeInMillisAsIso8601(), and testing::internal::PortableLocaltime().
{
   std::stringstream ss;
   ss << std::setfill('0') << std::setw(2) << value;
   return ss.str();
 }
static std::string testing::internal::String::FormatIntWidth2 (int value) static
static std::string testing::internal::String::ShowWideCString (const wchar_t * wide_c_str) static
std::string testing::internal::String::ShowWideCString (const wchar_t * wide_c_str) static
Definition at line 1848 of file gtest.cc.
References testing::internal::WideStringToUtf8().
Referenced by testing::Message::operator<<(), operator<<(), and testing::internal::ShouldRunTestCase().
{
   if (wide_c_str == NULL)  return "(null)";
   return internal::WideStringToUtf8(wide_c_str, -1);
 }
static std::string testing::internal::String::ShowWideCString (const wchar_t * wide_c_str) static
static bool testing::internal::String::WideCStringEquals (const wchar_t * lhs, const wchar_t * rhs) static
bool testing::internal::String::WideCStringEquals (const wchar_t * lhs, const wchar_t * rhs) static
Definition at line 1860 of file gtest.cc.
{
   if (lhs == NULL) return rhs == NULL;
   if (rhs == NULL) return false;
   return wcscmp(lhs, rhs) == 0;
 }
static bool testing::internal::String::WideCStringEquals (const wchar_t * lhs, const wchar_t * rhs) static
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/internal/gtest-string.h
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest.cc