proxygen: folly::detail::StringPieceLite Class Reference
folly::detail::StringPieceLite Class Reference
#include <RangeCommon.h>
Public Member Functions
StringPieceLite (const char *b, const char *e)
template<typename Range >
StringPieceLite (const Range &r)
const char * data () const
const char * begin () const
const char * end () const
size_t size () const
bool empty () const
const char & operator[] (size_t i) const
template<typename Range >
operator Range () const
Private Attributes
const char * b_
const char * e_
Detailed Description
Definition at line 37 of file RangeCommon.h.
Constructor & Destructor Documentation
folly::detail::StringPieceLite::StringPieceLite (const char * b, const char * e) inline
Definition at line 39 of file RangeCommon.h.
 : b_(b), e_(e) {}
template<typename Range > folly::detail::StringPieceLite::StringPieceLite (const Range & r) inline
Definition at line 41 of file RangeCommon.h.
       : StringPieceLite(r.data(), r.data() + r.size()) {}
Member Function Documentation
const char* folly::detail::StringPieceLite::begin () const inline
Definition at line 46 of file RangeCommon.h.
References b_.
Referenced by operator Range(), and folly::detail::qfind_first_byte_of_std().
{
     return b_;
   }
const char* folly::detail::StringPieceLite::data () const inline
Definition at line 43 of file RangeCommon.h.
References b_.
Referenced by folly::detail::qfind_first_byte_of_sse42().
{
     return b_;
   }
bool folly::detail::StringPieceLite::empty () const inline
Definition at line 55 of file RangeCommon.h.
References size().
Referenced by folly::detail::qfind_first_byte_of_nosse(), and folly::detail::qfind_first_byte_of_sse42().
                      {
     return size() == 0;
   }
const char* folly::detail::StringPieceLite::end () const inline
Definition at line 49 of file RangeCommon.h.
References e_.
Referenced by operator Range(), folly::detail::qfind_first_byte_of_sse42(), and folly::detail::qfind_first_byte_of_std().
{
     return e_;
   }
template<typename Range > folly::detail::StringPieceLite::operator Range () const inline explicit
Definition at line 63 of file RangeCommon.h.
References begin(), and end().
{
     return Range(begin(), end());
   }
const char& folly::detail::StringPieceLite::operator[] (size_t i) const inline
Definition at line 58 of file RangeCommon.h.
References b_, i, and size().
{
     DCHECK_GT(size(), i);
     return b_[i];
   }
size_t folly::detail::StringPieceLite::size () const inline
Definition at line 52 of file RangeCommon.h.
References b_, and e_.
Referenced by empty(), operator[](), folly::detail::qfind_first_byte_of_bitset(), folly::detail::qfind_first_byte_of_byteset(), folly::detail::qfind_first_byte_of_nosse(), and folly::detail::qfind_first_byte_of_sse42().
                       {
     return size_t(e_ - b_);
   }
Member Data Documentation
const char* folly::detail::StringPieceLite::b_ private
Definition at line 68 of file RangeCommon.h.
Referenced by begin(), data(), operator[](), and size().
const char* folly::detail::StringPieceLite::e_ private
Definition at line 69 of file RangeCommon.h.
Referenced by end(), and size().
The documentation for this class was generated from the following file:
proxygen/folly/folly/detail/RangeCommon.h