proxygen: folly::RWSpinLock::UpgradedHolder Class Reference
folly::RWSpinLock::UpgradedHolder Class Reference
#include <RWSpinLock.h>
Public Member Functions
UpgradedHolder (RWSpinLock *lock)
UpgradedHolder (RWSpinLock &lock)
UpgradedHolder (WriteHolder &&writer)
UpgradedHolder (UpgradedHolder &&other) noexcept
UpgradedHolder & operator= (UpgradedHolder &&other)
UpgradedHolder (const UpgradedHolder &other)=delete
UpgradedHolder & operator= (const UpgradedHolder &other)=delete
~UpgradedHolder ()
void reset (RWSpinLock *lock=nullptr)
void swap (UpgradedHolder *other)
Private Attributes
RWSpinLock * lock_
Friends
class WriteHolder
class ReadHolder
Detailed Description
Definition at line 383 of file RWSpinLock.h.
Constructor & Destructor Documentation
folly::RWSpinLock::UpgradedHolder::UpgradedHolder (RWSpinLock * lock) inline explicit
Definition at line 385 of file RWSpinLock.h.
References folly::RWSpinLock::ReadHolder::lock_, and folly::RWSpinLock::lock_upgrade().
                                               : lock_(lock) {
       if (lock_) {
         lock_->lock_upgrade();
       }
     }
folly::RWSpinLock::UpgradedHolder::UpgradedHolder (RWSpinLock & lock) inline explicit
Definition at line 391 of file RWSpinLock.h.
References folly::RWSpinLock::ReadHolder::lock_, and folly::RWSpinLock::lock_upgrade().
                                               : lock_(&lock) {
       lock_->lock_upgrade();
     }
folly::RWSpinLock::UpgradedHolder::UpgradedHolder (WriteHolder && writer) inline explicit
Definition at line 395 of file RWSpinLock.h.
References folly::RWSpinLock::ReadHolder::lock_, and folly::RWSpinLock::unlock_and_lock_upgrade().
{
       lock_ = writer.lock_;
       writer.lock_ = nullptr;
       if (lock_) {
         lock_->unlock_and_lock_upgrade();
       }
     }
folly::RWSpinLock::UpgradedHolder::UpgradedHolder (UpgradedHolder && other) inline noexcept
Definition at line 403 of file RWSpinLock.h.
                                                     : lock_(other.lock_) {
       other.lock_ = nullptr;
     }
folly::RWSpinLock::UpgradedHolder::UpgradedHolder (const UpgradedHolder & other) delete
folly::RWSpinLock::UpgradedHolder::~UpgradedHolder () inline
Definition at line 416 of file RWSpinLock.h.
References folly::RWSpinLock::ReadHolder::lock_, and folly::RWSpinLock::unlock_upgrade().
                       {
       if (lock_) {
         lock_->unlock_upgrade();
       }
     }
Member Function Documentation
UpgradedHolder& folly::RWSpinLock::UpgradedHolder::operator= (UpgradedHolder && other) inline
Definition at line 407 of file RWSpinLock.h.
References folly::RWSpinLock::ReadHolder::lock_, folly::RWSpinLock::ReadHolder::operator=(), folly::RWSpinLock::ReadHolder::swap(), folly::f14::swap(), and folly::RWSpinLock::ReadHolder::UpgradedHolder.
{
       using std::swap;
       swap(lock_, other.lock_);
       return *this;
     }
UpgradedHolder& folly::RWSpinLock::UpgradedHolder::operator= (const UpgradedHolder & other) delete
void folly::RWSpinLock::UpgradedHolder::reset (RWSpinLock * lock = nullptr) inline
Definition at line 422 of file RWSpinLock.h.
References folly::RWSpinLock::lock(), folly::RWSpinLock::ReadHolder::lock_, folly::RWSpinLock::lock_upgrade(), and folly::RWSpinLock::unlock_upgrade().
{
       if (lock == lock_) {
         return;
       }
       if (lock_) {
         lock_->unlock_upgrade();
       }
       lock_ = lock;
       if (lock_) {
         lock_->lock_upgrade();
       }
     }
void folly::RWSpinLock::UpgradedHolder::swap (UpgradedHolder * other) inline
Definition at line 435 of file RWSpinLock.h.
References folly::RWSpinLock::ReadHolder::lock_, lock_, folly::RWSpinLock::ReadHolder::swap(), and folly::f14::swap().
{
       using std::swap;
       swap(lock_, other->lock_);
     }
Friends And Related Function Documentation
friend class ReadHolder friend
Definition at line 442 of file RWSpinLock.h.
friend class WriteHolder friend
Definition at line 441 of file RWSpinLock.h.
Member Data Documentation
RWSpinLock* folly::RWSpinLock::UpgradedHolder::lock_ private
Definition at line 443 of file RWSpinLock.h.
Referenced by swap().
The documentation for this class was generated from the following file:
proxygen/folly/folly/synchronization/RWSpinLock.h