proxygen: testing::TestEventListeners Class Reference
testing::TestEventListeners Class Reference
#include <gtest.h>
Public Member Functions
TestEventListeners ()
~TestEventListeners ()
void Append (TestEventListener *listener)
TestEventListener * Release (TestEventListener *listener)
TestEventListener * default_result_printer () const
TestEventListener * default_xml_generator () const
TestEventListeners ()
~TestEventListeners ()
void Append (TestEventListener *listener)
TestEventListener * Release (TestEventListener *listener)
TestEventListener * default_result_printer () const
TestEventListener * default_xml_generator () const
TestEventListeners ()
~TestEventListeners ()
void Append (TestEventListener *listener)
TestEventListener * Release (TestEventListener *listener)
TestEventListener * default_result_printer () const
TestEventListener * default_xml_generator () const
Private Member Functions
TestEventListener * repeater ()
void SetDefaultResultPrinter (TestEventListener *listener)
void SetDefaultXmlGenerator (TestEventListener *listener)
bool EventForwardingEnabled () const
void SuppressEventForwarding ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestEventListeners)
TestEventListener * repeater ()
void SetDefaultResultPrinter (TestEventListener *listener)
void SetDefaultXmlGenerator (TestEventListener *listener)
bool EventForwardingEnabled () const
void SuppressEventForwarding ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestEventListeners)
TestEventListener * repeater ()
void SetDefaultResultPrinter (TestEventListener *listener)
void SetDefaultXmlGenerator (TestEventListener *listener)
bool EventForwardingEnabled () const
void SuppressEventForwarding ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestEventListeners)
Private Attributes
internal::TestEventRepeater * repeater_
TestEventListener * default_result_printer_
TestEventListener * default_xml_generator_
Friends
class TestCase
class TestInfo
class internal::DefaultGlobalTestPartResultReporter
class internal::NoExecDeathTest
class internal::TestEventListenersAccessor
class internal::UnitTestImpl
Detailed Description
Definition at line 1064 of file gtest.h.
Constructor & Destructor Documentation
testing::TestEventListeners::TestEventListeners ()
Definition at line 3890 of file gtest.cc.
Referenced by testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
     : repeater_(new internal::TestEventRepeater()),
       default_result_printer_(NULL),
       default_xml_generator_(NULL) {
 }
testing::TestEventListeners::~TestEventListeners ()
Definition at line 3896 of file gtest.cc.
References repeater_.
Referenced by testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
 { delete repeater_; }
testing::TestEventListeners::TestEventListeners ()
testing::TestEventListeners::~TestEventListeners ()
testing::TestEventListeners::TestEventListeners ()
testing::TestEventListeners::~TestEventListeners ()
Member Function Documentation
void testing::TestEventListeners::Append (TestEventListener * listener)
Definition at line 3902 of file gtest.cc.
References testing::internal::TestEventRepeater::Append(), and repeater_.
Referenced by testing::internal::UnitTestImpl::ConfigureXmlOutput(), main(), testing::internal::UnitTestImpl::PostFlagParsingInit(), SetDefaultResultPrinter(), SetDefaultXmlGenerator(), TEST(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   repeater_->Append(listener);
 }
void testing::TestEventListeners::Append (TestEventListener * listener)
void testing::TestEventListeners::Append (TestEventListener * listener)
TestEventListener* testing::TestEventListeners::default_result_printer () const inline
Definition at line 1084 of file gtest.h.
{
     return default_result_printer_;
   }
TestEventListener* testing::TestEventListeners::default_result_printer () const inline
Definition at line 1084 of file gtest.h.
Referenced by TEST().
{
     return default_result_printer_;
   }
TestEventListener* testing::TestEventListeners::default_result_printer () const inline
Definition at line 1084 of file gtest.h.
{
     return default_result_printer_;
   }
TestEventListener* testing::TestEventListeners::default_xml_generator () const inline
Definition at line 1095 of file gtest.h.
Referenced by TEST().
{
     return default_xml_generator_;
   }
TestEventListener* testing::TestEventListeners::default_xml_generator () const inline
Definition at line 1095 of file gtest.h.
References GTEST_API_, GTEST_DISALLOW_COPY_AND_ASSIGN_, GTEST_LOCK_EXCLUDED_, GTEST_MUST_USE_RESULT_, i, mutex_, Run(), string, and value.
{
     return default_xml_generator_;
   }
TestEventListener* testing::TestEventListeners::default_xml_generator () const inline
Definition at line 1095 of file gtest.h.
References GTEST_API_, GTEST_DISALLOW_COPY_AND_ASSIGN_, GTEST_LOCK_EXCLUDED_, GTEST_MUST_USE_RESULT_, i, mutex_, Run(), string, and value.
{
     return default_xml_generator_;
   }
bool testing::TestEventListeners::EventForwardingEnabled () const private
Definition at line 3955 of file gtest.cc.
References testing::internal::TestEventRepeater::forwarding_enabled(), and repeater_.
Referenced by testing::internal::TestEventListenersAccessor::EventForwardingEnabled(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   return repeater_->forwarding_enabled();
 }
bool testing::TestEventListeners::EventForwardingEnabled () const private
bool testing::TestEventListeners::EventForwardingEnabled () const private
testing::TestEventListeners::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestEventListeners) private
testing::TestEventListeners::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestEventListeners) private
testing::TestEventListeners::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestEventListeners) private
TestEventListener* testing::TestEventListeners::Release (TestEventListener * listener)
TestEventListener * testing::TestEventListeners::Release (TestEventListener * listener)
Definition at line 3909 of file gtest.cc.
References default_result_printer_, default_xml_generator_, testing::internal::TestEventRepeater::Release(), and repeater_.
Referenced by SetDefaultResultPrinter(), SetDefaultXmlGenerator(), TEST(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   if (listener == default_result_printer_)
     default_result_printer_ = NULL;
   else if (listener == default_xml_generator_)
     default_xml_generator_ = NULL;
   return repeater_->Release(listener);
 }
TestEventListener* testing::TestEventListeners::Release (TestEventListener * listener)
TestEventListener * testing::TestEventListeners::repeater () private
Definition at line 3919 of file gtest.cc.
References repeater_.
Referenced by testing::internal::TestEventListenersAccessor::GetRepeater(), testing::internal::DefaultGlobalTestPartResultReporter::ReportTestPartResult(), testing::TestInfo::Run(), testing::TestCase::Run(), testing::internal::UnitTestImpl::RunAllTests(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
 { return repeater_; }
TestEventListener* testing::TestEventListeners::repeater () private
TestEventListener* testing::TestEventListeners::repeater () private
void testing::TestEventListeners::SetDefaultResultPrinter (TestEventListener * listener) private
void testing::TestEventListeners::SetDefaultResultPrinter (TestEventListener * listener) private
void testing::TestEventListeners::SetDefaultResultPrinter (TestEventListener * listener) private
Definition at line 3926 of file gtest.cc.
References Append(), default_result_printer_, and Release().
Referenced by testing::internal::TestEventListenersAccessor::SetDefaultResultPrinter(), testing::internal::UnitTestImpl::UnitTestImpl(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   if (default_result_printer_ != listener) {
     // It is an error to pass this method a listener that is already in the
     // list.
     delete Release(default_result_printer_);
     default_result_printer_ = listener;
     if (listener != NULL)
       Append(listener);
   }
 }
void testing::TestEventListeners::SetDefaultXmlGenerator (TestEventListener * listener) private
void testing::TestEventListeners::SetDefaultXmlGenerator (TestEventListener * listener) private
Definition at line 3942 of file gtest.cc.
References Append(), default_xml_generator_, and Release().
Referenced by testing::internal::UnitTestImpl::ConfigureXmlOutput(), testing::internal::TestEventListenersAccessor::SetDefaultXmlGenerator(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   if (default_xml_generator_ != listener) {
     // It is an error to pass this method a listener that is already in the
     // list.
     delete Release(default_xml_generator_);
     default_xml_generator_ = listener;
     if (listener != NULL)
       Append(listener);
   }
 }
void testing::TestEventListeners::SetDefaultXmlGenerator (TestEventListener * listener) private
void testing::TestEventListeners::SuppressEventForwarding () private
void testing::TestEventListeners::SuppressEventForwarding () private
Definition at line 3959 of file gtest.cc.
References repeater_, and testing::internal::TestEventRepeater::set_forwarding_enabled().
Referenced by testing::internal::UnitTestImpl::RecordProperty(), testing::internal::TestEventListenersAccessor::SuppressEventForwarding(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   repeater_->set_forwarding_enabled(false);
 }
void testing::TestEventListeners::SuppressEventForwarding () private
Friends And Related Function Documentation
internal::DefaultGlobalTestPartResultReporter friend
Definition at line 1102 of file gtest.h.
internal::NoExecDeathTest friend
Definition at line 1103 of file gtest.h.
internal::TestEventListenersAccessor friend
Definition at line 1104 of file gtest.h.
internal::UnitTestImpl friend
Definition at line 1105 of file gtest.h.
TestCase friend
Definition at line 1100 of file gtest.h.
TestInfo friend
Definition at line 1101 of file gtest.h.
Member Data Documentation
TestEventListener * testing::TestEventListeners::default_result_printer_ private
Definition at line 1133 of file gtest.h.
Referenced by Release(), and SetDefaultResultPrinter().
TestEventListener * testing::TestEventListeners::default_xml_generator_ private
Definition at line 1135 of file gtest.h.
Referenced by Release(), and SetDefaultXmlGenerator().
internal::TestEventRepeater * testing::TestEventListeners::repeater_ private
Definition at line 1131 of file gtest.h.
Referenced by Append(), EventForwardingEnabled(), Release(), repeater(), SuppressEventForwarding(), and ~TestEventListeners().
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/gtest.h
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest.cc