proxygen: testing::internal::RefMatcher< T & >::Impl< Super > Class Template Reference
testing::internal::RefMatcher< T & >::Impl< Super > Class Template Reference
Public Member Functions
Impl (Super &x)
virtual bool MatchAndExplain (Super &x, MatchResultListener *listener) const
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
Impl (Super &x)
virtual bool MatchAndExplain (Super &x, MatchResultListener *listener) const
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
Impl (Super &x)
virtual bool MatchAndExplain (Super &x, MatchResultListener *listener) const
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
virtual ~MatcherDescriberInterface ()
virtual ~MatcherDescriberInterface ()
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (Impl)
GTEST_DISALLOW_ASSIGN_ (Impl)
GTEST_DISALLOW_ASSIGN_ (Impl)
Private Attributes
const Super & object_
Detailed Description
template<typename T>
template<typename Super>
class testing::internal::RefMatcher< T & >::Impl< Super >
Definition at line 1056 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename T > template<typename Super > testing::internal::RefMatcher< T & >::Impl< Super >::Impl (Super & x) inline explicit
Definition at line 1058 of file gmock-matchers.h.
 : object_(x) {}  // NOLINT
template<typename T > template<typename Super > testing::internal::RefMatcher< T & >::Impl< Super >::Impl (Super & x) inline explicit
Definition at line 1058 of file gmock-matchers.h.
 : object_(x) {}  // NOLINT
template<typename T > template<typename Super > testing::internal::RefMatcher< T & >::Impl< Super >::Impl (Super & x) inline explicit
Definition at line 1058 of file gmock-matchers.h.
 : object_(x) {}  // NOLINT
Member Function Documentation
template<typename T > template<typename Super > virtual void testing::internal::RefMatcher< T & >::Impl< Super >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 1073 of file gmock-matchers.h.
References testing::gtest_printers_test::Print().
{
       *os << "does not reference the variable ";
       UniversalPrinter<Super&>::Print(object_, os);
     }
template<typename T > template<typename Super > virtual void testing::internal::RefMatcher< T & >::Impl< Super >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 1073 of file gmock-matchers.h.
References testing::internal::CaseInsensitiveCStringEquals(), testing::internal::CaseInsensitiveStringEquals(), GTEST_DISALLOW_ASSIGN_, testing::gtest_printers_test::Print(), and folly::detail::rhs.
{
       *os << "does not reference the variable ";
       UniversalPrinter<Super&>::Print(object_, os);
     }
template<typename T > template<typename Super > virtual void testing::internal::RefMatcher< T & >::Impl< Super >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 1073 of file gmock-matchers.h.
References testing::internal::CaseInsensitiveCStringEquals(), testing::internal::CaseInsensitiveStringEquals(), GTEST_DISALLOW_ASSIGN_, testing::gtest_printers_test::Print(), and folly::detail::rhs.
{
       *os << "does not reference the variable ";
       UniversalPrinter<Super&>::Print(object_, os);
     }
template<typename T > template<typename Super > virtual void testing::internal::RefMatcher< T & >::Impl< Super >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 1068 of file gmock-matchers.h.
References testing::gtest_printers_test::Print().
{
       *os << "references the variable ";
       UniversalPrinter<Super&>::Print(object_, os);
     }
template<typename T > template<typename Super > virtual void testing::internal::RefMatcher< T & >::Impl< Super >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 1068 of file gmock-matchers.h.
References testing::gtest_printers_test::Print().
{
       *os << "references the variable ";
       UniversalPrinter<Super&>::Print(object_, os);
     }
template<typename T > template<typename Super > virtual void testing::internal::RefMatcher< T & >::Impl< Super >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 1068 of file gmock-matchers.h.
References testing::gtest_printers_test::Print().
{
       *os << "references the variable ";
       UniversalPrinter<Super&>::Print(object_, os);
     }
template<typename T > template<typename Super > testing::internal::RefMatcher< T & >::Impl< Super >::GTEST_DISALLOW_ASSIGN_ (Impl) private
template<typename T > template<typename Super > testing::internal::RefMatcher< T & >::Impl< Super >::GTEST_DISALLOW_ASSIGN_ (Impl) private
template<typename T > template<typename Super > testing::internal::RefMatcher< T & >::Impl< Super >::GTEST_DISALLOW_ASSIGN_ (Impl) private
template<typename T > template<typename Super > virtual bool testing::internal::RefMatcher< T & >::Impl< Super >::MatchAndExplain (Super & x, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< Super & >.
Definition at line 1062 of file gmock-matchers.h.
References x.
{
       *listener << "which is located @" << static_cast<const void*>(&x);
       return &x == &object_;
     }
template<typename T > template<typename Super > virtual bool testing::internal::RefMatcher< T & >::Impl< Super >::MatchAndExplain (Super & x, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< Super & >.
Definition at line 1062 of file gmock-matchers.h.
References x.
{
       *listener << "which is located @" << static_cast<const void*>(&x);
       return &x == &object_;
     }
template<typename T > template<typename Super > virtual bool testing::internal::RefMatcher< T & >::Impl< Super >::MatchAndExplain (Super & x, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< Super & >.
Definition at line 1062 of file gmock-matchers.h.
References x.
{
       *listener << "which is located @" << static_cast<const void*>(&x);
       return &x == &object_;
     }
Member Data Documentation
template<typename T > template<typename Super > const Super & testing::internal::RefMatcher< T & >::Impl< Super >::object_ private
Definition at line 1079 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h