proxygen: fizz::test::RecordTest Class Reference
fizz::test::RecordTest Class Reference
Static Protected Member Functions
static Buf getBuf (const std::string &hex)
static void expectSame (const Buf &buf, const std::string &hex)
Protected Attributes
StrictMock< ConcreteReadRecordLayer > read_
StrictMock< ConcreteWriteRecordLayer > write_
IOBufQueue queue_ {IOBufQueue::cacheChainLength()}
IOBufEqualTo eq_
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Protected Member Functions inherited from testing::Test
Test ()
virtual void SetUp ()
virtual void TearDown ()
Test ()
virtual void SetUp ()
virtual void TearDown ()
Test ()
virtual void SetUp ()
virtual void TearDown ()
Detailed Description
Definition at line 39 of file RecordTest.cpp.
Member Function Documentation
static void fizz::test::RecordTest::expectSame (const Buf & buf, const std::string & hex) inline static protected
Definition at line 53 of file RecordTest.cpp.
References EXPECT_EQ, and folly::hexlify().
{
     auto str = buf->moveToFbString().toStdString();
     EXPECT_EQ(hexlify(str), hex);
   }
static Buf fizz::test::RecordTest::getBuf (const std::string & hex) inline static protected
Definition at line 48 of file RecordTest.cpp.
References folly::IOBuf::copyBuffer(), folly::data(), and folly::unhexlify().
{
     auto data = unhexlify(hex);
     return IOBuf::copyBuffer(data.data(), data.size());
   }
Member Data Documentation
IOBufEqualTo fizz::test::RecordTest::eq_ protected
Definition at line 46 of file RecordTest.cpp.
IOBufQueue fizz::test::RecordTest::queue_ {IOBufQueue::cacheChainLength()} protected
Definition at line 44 of file RecordTest.cpp.
StrictMock<ConcreteReadRecordLayer> fizz::test::RecordTest::read_ protected
Definition at line 41 of file RecordTest.cpp.
StrictMock<ConcreteWriteRecordLayer> fizz::test::RecordTest::write_ protected
Definition at line 42 of file RecordTest.cpp.
The documentation for this class was generated from the following file:
proxygen/fizz/fizz/record/test/RecordTest.cpp