proxygen: testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer > Class Template Reference
testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer > Class Template Reference
#include <gmock-matchers.h>
Public Types
typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(LhsContainer)> LhsView
typedef LhsView::type LhsStlContainer
typedef LhsView::const_reference LhsStlContainerReference
typedef LhsStlContainer::value_type LhsValue
typedef ::testing::tuple< const LhsValue &, const RhsValue & > InnerMatcherArg
typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(LhsContainer)> LhsView
typedef LhsView::type LhsStlContainer
typedef LhsView::const_reference LhsStlContainerReference
typedef LhsStlContainer::value_type LhsValue
typedef ::testing::tuple< const LhsValue &, const RhsValue & > InnerMatcherArg
typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(LhsContainer)> LhsView
typedef LhsView::type LhsStlContainer
typedef LhsView::const_reference LhsStlContainerReference
typedef LhsStlContainer::value_type LhsValue
typedef ::testing::tuple< const LhsValue &, const RhsValue & > InnerMatcherArg
Public Member Functions
Impl (const TupleMatcher &tuple_matcher, const RhsStlContainer &rhs)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (LhsContainer lhs, MatchResultListener *listener) const
Impl (const TupleMatcher &tuple_matcher, const RhsStlContainer &rhs)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (LhsContainer lhs, MatchResultListener *listener) const
Impl (const TupleMatcher &tuple_matcher, const RhsStlContainer &rhs)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (LhsContainer lhs, MatchResultListener *listener) const
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
virtual ~MatcherDescriberInterface ()
virtual ~MatcherDescriberInterface ()
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (Impl)
GTEST_DISALLOW_ASSIGN_ (Impl)
GTEST_DISALLOW_ASSIGN_ (Impl)
Private Attributes
const Matcher< InnerMatcherArg > mono_tuple_matcher_
const RhsStlContainer rhs_
Detailed Description
template<typename TupleMatcher, typename RhsContainer>
template<typename LhsContainer>
class testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >
Definition at line 2715 of file gmock-matchers.h.
Member Typedef Documentation
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > typedef ::testing::tuple<const LhsValue&, const RhsValue&> testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::InnerMatcherArg
Definition at line 2726 of file gmock-matchers.h.
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > typedef ::testing::tuple<const LhsValue&, const RhsValue&> testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::InnerMatcherArg
Definition at line 2726 of file gmock-matchers.h.
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > typedef ::testing::tuple<const LhsValue&, const RhsValue&> testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::InnerMatcherArg
Definition at line 2726 of file gmock-matchers.h.
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > typedef LhsView::type testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::LhsStlContainer
Definition at line 2719 of file gmock-matchers.h.
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > typedef LhsView::type testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::LhsStlContainer
Definition at line 2719 of file gmock-matchers.h.
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > typedef LhsView::type testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::LhsStlContainer
Definition at line 2719 of file gmock-matchers.h.
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > typedef LhsView::const_reference testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::LhsStlContainerReference
Definition at line 2720 of file gmock-matchers.h.
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > typedef LhsView::const_reference testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::LhsStlContainerReference
Definition at line 2720 of file gmock-matchers.h.
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > typedef LhsView::const_reference testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::LhsStlContainerReference
Definition at line 2720 of file gmock-matchers.h.
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > typedef LhsStlContainer::value_type testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::LhsValue
Definition at line 2721 of file gmock-matchers.h.
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > typedef LhsStlContainer::value_type testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::LhsValue
Definition at line 2721 of file gmock-matchers.h.
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > typedef LhsStlContainer::value_type testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::LhsValue
Definition at line 2721 of file gmock-matchers.h.
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(LhsContainer)> testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::LhsView
Definition at line 2718 of file gmock-matchers.h.
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(LhsContainer)> testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::LhsView
Definition at line 2718 of file gmock-matchers.h.
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(LhsContainer)> testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::LhsView
Definition at line 2718 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::Impl (const TupleMatcher & tuple_matcher, const RhsStlContainer & rhs) inline
Definition at line 2728 of file gmock-matchers.h.
         : mono_tuple_matcher_(SafeMatcherCast<InnerMatcherArg>(tuple_matcher)),
           rhs_(rhs) {}
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::Impl (const TupleMatcher & tuple_matcher, const RhsStlContainer & rhs) inline
Definition at line 2728 of file gmock-matchers.h.
         : mono_tuple_matcher_(SafeMatcherCast<InnerMatcherArg>(tuple_matcher)),
           rhs_(rhs) {}
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::Impl (const TupleMatcher & tuple_matcher, const RhsStlContainer & rhs) inline
Definition at line 2728 of file gmock-matchers.h.
         : mono_tuple_matcher_(SafeMatcherCast<InnerMatcherArg>(tuple_matcher)),
           rhs_(rhs) {}
Member Function Documentation
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > virtual void testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 2740 of file gmock-matchers.h.
References testing::internal::UniversalPrint().
{
       *os << "doesn't contain exactly " << rhs_.size()
           << " values, or contains a value x at some index i"
           << " where x and the i-th value of ";
       UniversalPrint(rhs_, os);
       *os << " ";
       mono_tuple_matcher_.DescribeNegationTo(os);
     }
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > virtual void testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 2740 of file gmock-matchers.h.
References testing::internal::UniversalPrint().
{
       *os << "doesn't contain exactly " << rhs_.size()
           << " values, or contains a value x at some index i"
           << " where x and the i-th value of ";
       UniversalPrint(rhs_, os);
       *os << " ";
       mono_tuple_matcher_.DescribeNegationTo(os);
     }
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > virtual void testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 2740 of file gmock-matchers.h.
References testing::internal::UniversalPrint().
{
       *os << "doesn't contain exactly " << rhs_.size()
           << " values, or contains a value x at some index i"
           << " where x and the i-th value of ";
       UniversalPrint(rhs_, os);
       *os << " ";
       mono_tuple_matcher_.DescribeNegationTo(os);
     }
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > virtual void testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 2733 of file gmock-matchers.h.
References testing::gtest_printers_test::Print().
{
       *os << "contains " << rhs_.size()
           << " values, where each value and its corresponding value in ";
       UniversalPrinter<RhsStlContainer>::Print(rhs_, os);
       *os << " ";
       mono_tuple_matcher_.DescribeTo(os);
     }
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > virtual void testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 2733 of file gmock-matchers.h.
References testing::gtest_printers_test::Print().
{
       *os << "contains " << rhs_.size()
           << " values, where each value and its corresponding value in ";
       UniversalPrinter<RhsStlContainer>::Print(rhs_, os);
       *os << " ";
       mono_tuple_matcher_.DescribeTo(os);
     }
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > virtual void testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 2733 of file gmock-matchers.h.
References testing::gtest_printers_test::Print().
{
       *os << "contains " << rhs_.size()
           << " values, where each value and its corresponding value in ";
       UniversalPrinter<RhsStlContainer>::Print(rhs_, os);
       *os << " ";
       mono_tuple_matcher_.DescribeTo(os);
     }
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::GTEST_DISALLOW_ASSIGN_ (Impl< LhsContainer >) private
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::GTEST_DISALLOW_ASSIGN_ (Impl< LhsContainer >) private
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::GTEST_DISALLOW_ASSIGN_ (Impl< LhsContainer >) private
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > virtual bool testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::MatchAndExplain (LhsContainer lhs, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< LhsContainer >.
Definition at line 2749 of file gmock-matchers.h.
References i, testing::MatchResultListener::IsInterested(), testing::internal::PrintIfNotEmpty(), testing::StringMatchResultListener::str(), testing::MatchResultListener::stream(), and testing::internal::UniversalPrint().
{
       LhsStlContainerReference lhs_stl_container = LhsView::ConstReference(lhs);
       const size_t actual_size = lhs_stl_container.size();
       if (actual_size != rhs_.size()) {
         *listener << "which contains " << actual_size << " values";
         return false;
       }
       typename LhsStlContainer::const_iterator left = lhs_stl_container.begin();
       typename RhsStlContainer::const_iterator right = rhs_.begin();
       for (size_t i = 0; i != actual_size; ++i, ++left, ++right) {
         const InnerMatcherArg value_pair(*left, *right);
         if (listener->IsInterested()) {
           StringMatchResultListener inner_listener;
           if (!mono_tuple_matcher_.MatchAndExplain(
                   value_pair, &inner_listener)) {
             *listener << "where the value pair (";
             UniversalPrint(*left, listener->stream());
             *listener << ", ";
             UniversalPrint(*right, listener->stream());
             *listener << ") at index #" << i << " don't match";
             PrintIfNotEmpty(inner_listener.str(), listener->stream());
             return false;
           }
         } else {
           if (!mono_tuple_matcher_.Matches(value_pair))
             return false;
         }
       }
       return true;
     }
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > virtual bool testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::MatchAndExplain (LhsContainer lhs, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< LhsContainer >.
Definition at line 2749 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, GTEST_REMOVE_REFERENCE_AND_CONST_, i, testing::internal::PrintIfNotEmpty(), testing::StringMatchResultListener::str(), and testing::internal::UniversalPrint().
{
       LhsStlContainerReference lhs_stl_container = LhsView::ConstReference(lhs);
       const size_t actual_size = lhs_stl_container.size();
       if (actual_size != rhs_.size()) {
         *listener << "which contains " << actual_size << " values";
         return false;
       }
       typename LhsStlContainer::const_iterator left = lhs_stl_container.begin();
       typename RhsStlContainer::const_iterator right = rhs_.begin();
       for (size_t i = 0; i != actual_size; ++i, ++left, ++right) {
         const InnerMatcherArg value_pair(*left, *right);
         if (listener->IsInterested()) {
           StringMatchResultListener inner_listener;
           if (!mono_tuple_matcher_.MatchAndExplain(
                   value_pair, &inner_listener)) {
             *listener << "where the value pair (";
             UniversalPrint(*left, listener->stream());
             *listener << ", ";
             UniversalPrint(*right, listener->stream());
             *listener << ") at index #" << i << " don't match";
             PrintIfNotEmpty(inner_listener.str(), listener->stream());
             return false;
           }
         } else {
           if (!mono_tuple_matcher_.Matches(value_pair))
             return false;
         }
       }
       return true;
     }
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > virtual bool testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::MatchAndExplain (LhsContainer lhs, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< LhsContainer >.
Definition at line 2749 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, GTEST_REMOVE_REFERENCE_AND_CONST_, i, testing::internal::PrintIfNotEmpty(), testing::StringMatchResultListener::str(), and testing::internal::UniversalPrint().
{
       LhsStlContainerReference lhs_stl_container = LhsView::ConstReference(lhs);
       const size_t actual_size = lhs_stl_container.size();
       if (actual_size != rhs_.size()) {
         *listener << "which contains " << actual_size << " values";
         return false;
       }
       typename LhsStlContainer::const_iterator left = lhs_stl_container.begin();
       typename RhsStlContainer::const_iterator right = rhs_.begin();
       for (size_t i = 0; i != actual_size; ++i, ++left, ++right) {
         const InnerMatcherArg value_pair(*left, *right);
         if (listener->IsInterested()) {
           StringMatchResultListener inner_listener;
           if (!mono_tuple_matcher_.MatchAndExplain(
                   value_pair, &inner_listener)) {
             *listener << "where the value pair (";
             UniversalPrint(*left, listener->stream());
             *listener << ", ";
             UniversalPrint(*right, listener->stream());
             *listener << ") at index #" << i << " don't match";
             PrintIfNotEmpty(inner_listener.str(), listener->stream());
             return false;
           }
         } else {
           if (!mono_tuple_matcher_.Matches(value_pair))
             return false;
         }
       }
       return true;
     }
Member Data Documentation
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > const Matcher< InnerMatcherArg > testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::mono_tuple_matcher_ private
Definition at line 2785 of file gmock-matchers.h.
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > const RhsStlContainer testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::rhs_ private
Definition at line 2786 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h