proxygen: Node< Atom > Class Template Reference
Node< Atom > Class Template Reference
Public Member Functions
Node (int v=0, Node *n=nullptr, bool=false) noexcept
~Node ()
int value () const noexcept
Node< Atom > * next () const noexcept
Atom< Node< Atom > * > * ptr_next () noexcept
Public Member Functions inherited from folly::hazptr_obj_base< Node< Atom >, Atom >
void retire (D deleter={}, hazptr_domain< Atom > &domain=default_hazptr_domain< Atom >())
void retire (hazptr_domain< Atom > &domain)
Public Member Functions inherited from folly::hazptr_obj< Atom >
hazptr_obj () noexcept
hazptr_obj (const hazptr_obj< Atom > &) noexcept
hazptr_obj (hazptr_obj< Atom > &&) noexcept
hazptr_obj< Atom > & operator= (const hazptr_obj< Atom > &) noexcept
hazptr_obj< Atom > & operator= (hazptr_obj< Atom > &&) noexcept
Public Member Functions inherited from folly::hazptr_deleter< Node< Atom >, D >
void set_deleter (D d={})
void delete_obj (Node< Atom > *p)
Private Attributes
int val_
Atom< Node< Atom > * > next_
Detailed Description
template<template< typename > class Atom = std::atomic>
class Node< Atom >
Node
Definition at line 98 of file HazptrTest.cpp.
Constructor & Destructor Documentation
template<template< typename > class Atom = std::atomic> Node< Atom >::Node (int v = 0, Node< Atom > * n = nullptr, bool = false) inline explicit noexcept
Definition at line 103 of file HazptrTest.cpp.
References Count::inc_ctors().
Referenced by folly::HazptrLockFreeLIFO< T, Atom >::push().
       : val_(v), next_(n) {
     c_.inc_ctors();
   }
template<template< typename > class Atom = std::atomic> Node< Atom >::~Node () inline
Definition at line 108 of file HazptrTest.cpp.
References Count::inc_dtors().
Referenced by folly::detail::concurrenthashmap::HazptrDeleter< Allocator >::operator()().
           {
     c_.inc_dtors();
   }
Member Function Documentation
template<template< typename > class Atom = std::atomic> Node<Atom>* Node< Atom >::next () const inline noexcept
Definition at line 116 of file HazptrTest.cpp.
{
     return next_.load(std::memory_order_acquire);
   }
template<template< typename > class Atom = std::atomic> Atom<Node<Atom>*>* Node< Atom >::ptr_next () inline noexcept
Definition at line 120 of file HazptrTest.cpp.
References Atom.
{
     return &next_;
   }
template<template< typename > class Atom = std::atomic> int Node< Atom >::value () const inline noexcept
Definition at line 112 of file HazptrTest.cpp.
{
     return val_;
   }
Member Data Documentation
template<template< typename > class Atom = std::atomic> Atom<Node<Atom>*> Node< Atom >::next_ private
Definition at line 100 of file HazptrTest.cpp.
template<template< typename > class Atom = std::atomic> int Node< Atom >::val_ private
Definition at line 99 of file HazptrTest.cpp.
The documentation for this class was generated from the following file:
proxygen/folly/folly/synchronization/test/HazptrTest.cpp