proxygen: folly::LogStreamVoidify< true > Class Template Reference
folly::LogStreamVoidify< true > Class Template Reference
#include <LogStreamProcessor.h>
Public Member Functions
void operator& (std::ostream &)
Detailed Description
template<>
class folly::LogStreamVoidify< true >
Definition at line 487 of file LogStreamProcessor.h.
Member Function Documentation
void folly::LogStreamVoidify< true >::operator& (std::ostream & stream)
A specialized noreturn version of operator&() for fatal log statements.
Definition at line 214 of file LogStreamProcessor.cpp.
References folly::LogStream::getProcessor(), folly::LogStreamProcessor::logNow(), and folly::LogStreamProcessor::stream().
{
   // Non-fatal log messages wait until the LogStreamProcessor destructor to log
   // the message.  However for fatal messages we log immediately in the &
   // operator, since it is marked noreturn.
   //
   // This does result in slightly larger emitted code for fatal log messages
   // (since the operator & call cannot be completely omitted).  However, fatal
   // log messages should typically be much more rare than non-fatal messages,
   // so the small amount of extra overhead shouldn't be a big deal.
   auto& logStream = static_cast<LogStream&>(stream);
   logStream.getProcessor()->logNow();
   abort();
 }
The documentation for this class was generated from the following files:
proxygen/folly/folly/logging/LogStreamProcessor.h
proxygen/folly/folly/logging/LogStreamProcessor.cpp