proxygen: folly::test::MovableInt Class Reference
folly::test::MovableInt Class Reference
Public Member Functions
MovableInt (int value)
int value () const
MovableInt (MovableInt &&)=default
MovableInt & operator= (MovableInt &&)=default
MovableInt (const MovableInt &)=delete
MovableInt & operator= (const MovableInt &)=delete
Private Attributes
int value_
Detailed Description
Definition at line 42 of file TupleOpsTest.cpp.
Constructor & Destructor Documentation
folly::test::MovableInt::MovableInt (int value) inline explicit
Definition at line 44 of file TupleOpsTest.cpp.
Referenced by folly::test::TEST(), and value().
 : value_(value) {}
folly::test::MovableInt::MovableInt (MovableInt &&) default
folly::test::MovableInt::MovableInt (const MovableInt &) delete
Member Function Documentation
MovableInt& folly::test::MovableInt::operator= (MovableInt &&) default
Referenced by value().
MovableInt& folly::test::MovableInt::operator= (const MovableInt &) delete
int folly::test::MovableInt::value () const inline
Definition at line 45 of file TupleOpsTest.cpp.
References MovableInt(), operator=(), and value_.
Referenced by folly::test::operator==().
                     {
     return value_;
   }
Member Data Documentation
int folly::test::MovableInt::value_ private
Definition at line 55 of file TupleOpsTest.cpp.
Referenced by value().
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/test/TupleOpsTest.cpp