proxygen: testing::internal::GTestLog Class Reference
testing::internal::GTestLog Class Reference
#include <gtest-port.h>
Public Member Functions
GTestLog (GTestLogSeverity severity, const char *file, int line)
~GTestLog ()
::std::ostream & GetStream ()
GTestLog (GTestLogSeverity severity, const char *file, int line)
~GTestLog ()
::std::ostream & GetStream ()
GTestLog (GTestLogSeverity severity, const char *file, int line)
~GTestLog ()
::std::ostream & GetStream ()
Private Member Functions
GTestLog (GTestLog const &)
void operator= (GTestLog const &)
GTestLog (GTestLog const &)
void operator= (GTestLog const &)
GTestLog (GTestLog const &)
void operator= (GTestLog const &)
Private Attributes
const GTestLogSeverity severity_
Detailed Description
Definition at line 1254 of file gtest-port.h.
Constructor & Destructor Documentation
testing::internal::GTestLog::GTestLog (GTestLogSeverity severity, const char * file, int line)
Definition at line 908 of file gtest-port.cc.
References testing::internal::FormatFileLocation(), GetStream(), testing::internal::GTEST_ERROR, testing::internal::GTEST_INFO, and testing::internal::GTEST_WARNING.
     : severity_(severity) {
   const char* const marker =
       severity == GTEST_INFO ?    "[  INFO ]" :
       severity == GTEST_WARNING ? "[WARNING]" :
       severity == GTEST_ERROR ?   "[ ERROR ]" : "[ FATAL ]";
   GetStream() << ::std::endl << marker << " "
               << FormatFileLocation(file, line).c_str() << ": ";
 }
testing::internal::GTestLog::~GTestLog ()
Definition at line 919 of file gtest-port.cc.
References testing::internal::posix::Abort(), testing::internal::CaptureStderr(), testing::internal::CaptureStdout(), folly::netops::close(), testing::internal::posix::FClose(), FILE, testing::internal::posix::FOpen(), testing::internal::GetCapturedStderr(), testing::internal::GetCapturedStdout(), GetStream(), GTEST_CHECK_, GTEST_DISABLE_MSC_WARNINGS_POP_, GTEST_DISABLE_MSC_WARNINGS_PUSH_, GTEST_DISALLOW_COPY_AND_ASSIGN_, testing::internal::GTEST_FATAL, GTEST_LOG_, testing::internal::ReadEntireFile(), severity_, and string.
                     {
   GetStream() << ::std::endl;
   if (severity_ == GTEST_FATAL) {
     fflush(stderr);
     posix::Abort();
   }
 }
testing::internal::GTestLog::GTestLog (GTestLog const &) private
testing::internal::GTestLog::GTestLog (GTestLogSeverity severity, const char * file, int line)
testing::internal::GTestLog::~GTestLog ()
testing::internal::GTestLog::GTestLog (GTestLog const &) private
testing::internal::GTestLog::GTestLog (GTestLogSeverity severity, const char * file, int line)
testing::internal::GTestLog::~GTestLog ()
testing::internal::GTestLog::GTestLog (GTestLog const &) private
Member Function Documentation
::std::ostream& testing::internal::GTestLog::GetStream () inline
Definition at line 1261 of file gtest-port.h.
Referenced by GTestLog(), and ~GTestLog().
 { return ::std::cerr; }
::std::ostream& testing::internal::GTestLog::GetStream () inline
Definition at line 1261 of file gtest-port.h.
References GTEST_DISALLOW_COPY_AND_ASSIGN_.
 { return ::std::cerr; }
::std::ostream& testing::internal::GTestLog::GetStream () inline
Definition at line 1261 of file gtest-port.h.
References GTEST_DISALLOW_COPY_AND_ASSIGN_.
 { return ::std::cerr; }
void testing::internal::GTestLog::operator= (GTestLog const &) private
void testing::internal::GTestLog::operator= (GTestLog const &) private
void testing::internal::GTestLog::operator= (GTestLog const &) private
Member Data Documentation
const GTestLogSeverity testing::internal::GTestLog::severity_ private
Definition at line 1264 of file gtest-port.h.
Referenced by ~GTestLog().
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/internal/gtest-port.h
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest-port.cc