proxygen: testing::gmock_generated_function_mockers_test::FooInterface Class Reference
testing::gmock_generated_function_mockers_test::FooInterface Class Reference abstract
Public Member Functions
virtual ~FooInterface ()
virtual void VoidReturning (int x)=0
virtual int Nullary ()=0
virtual bool Unary (int x)=0
virtual long Binary (short x, int y)=0
virtual int Decimal (bool b, char c, short d, int e, long f, float g, double h, unsigned i, char *j, const string &k)=0
virtual bool TakesNonConstReference (int &n)=0
virtual string TakesConstReference (const int &n)=0
virtual bool TakesConst (const int x)=0
virtual int OverloadedOnArgumentNumber ()=0
virtual int OverloadedOnArgumentNumber (int n)=0
virtual int OverloadedOnArgumentType (int n)=0
virtual char OverloadedOnArgumentType (char c)=0
virtual int OverloadedOnConstness ()=0
virtual char OverloadedOnConstness () const =0
virtual int TypeWithHole (int(*func)())=0
virtual int TypeWithComma (const std::map< int, string > &a_map)=0
virtual ~FooInterface ()
virtual void VoidReturning (int x)=0
virtual int Nullary ()=0
virtual bool Unary (int x)=0
virtual long Binary (short x, int y)=0
virtual int Decimal (bool b, char c, short d, int e, long f, float g, double h, unsigned i, char *j, const string &k)=0
virtual bool TakesNonConstReference (int &n)=0
virtual string TakesConstReference (const int &n)=0
virtual bool TakesConst (const int x)=0
virtual int OverloadedOnArgumentNumber ()=0
virtual int OverloadedOnArgumentNumber (int n)=0
virtual int OverloadedOnArgumentType (int n)=0
virtual char OverloadedOnArgumentType (char c)=0
virtual int OverloadedOnConstness ()=0
virtual char OverloadedOnConstness () const =0
virtual int TypeWithHole (int(*func)())=0
virtual int TypeWithComma (const std::map< int, string > &a_map)=0
virtual ~FooInterface ()
virtual void VoidReturning (int x)=0
virtual int Nullary ()=0
virtual bool Unary (int x)=0
virtual long Binary (short x, int y)=0
virtual int Decimal (bool b, char c, short d, int e, long f, float g, double h, unsigned i, char *j, const string &k)=0
virtual bool TakesNonConstReference (int &n)=0
virtual string TakesConstReference (const int &n)=0
virtual bool TakesConst (const int x)=0
virtual int OverloadedOnArgumentNumber ()=0
virtual int OverloadedOnArgumentNumber (int n)=0
virtual int OverloadedOnArgumentType (int n)=0
virtual char OverloadedOnArgumentType (char c)=0
virtual int OverloadedOnConstness ()=0
virtual char OverloadedOnConstness () const =0
virtual int TypeWithHole (int(*func)())=0
virtual int TypeWithComma (const std::map< int, string > &a_map)=0
Detailed Description
Definition at line 75 of file gmock-generated-function-mockers_test.cc.
Constructor & Destructor Documentation
virtual testing::gmock_generated_function_mockers_test::FooInterface::~FooInterface () inline virtual
Definition at line 77 of file gmock-generated-function-mockers_test.cc.
References b, Binary(), c, Decimal(), f, g(), h, i, k, Nullary(), OverloadedOnArgumentNumber(), OverloadedOnArgumentType(), OverloadedOnConstness(), TakesConst(), TakesConstReference(), TakesNonConstReference(), TypeWithComma(), TypeWithHole(), Unary(), VoidReturning(), and x.
 {}
virtual testing::gmock_generated_function_mockers_test::FooInterface::~FooInterface () inline virtual
Definition at line 77 of file gmock-generated-function-mockers_test.cc.
References b, Binary(), c, Decimal(), f, g(), h, i, k, Nullary(), OverloadedOnArgumentNumber(), OverloadedOnArgumentType(), OverloadedOnConstness(), TakesConst(), TakesConstReference(), TakesNonConstReference(), TypeWithComma(), TypeWithHole(), Unary(), VoidReturning(), and x.
 {}
virtual testing::gmock_generated_function_mockers_test::FooInterface::~FooInterface () inline virtual
Definition at line 77 of file gmock-generated-function-mockers_test.cc.
References b, Binary(), c, Decimal(), f, g(), h, i, k, Nullary(), OverloadedOnArgumentNumber(), OverloadedOnArgumentType(), OverloadedOnConstness(), TakesConst(), TakesConstReference(), TakesNonConstReference(), TypeWithComma(), TypeWithHole(), Unary(), VoidReturning(), and x.
 {}
Member Function Documentation
virtual long testing::gmock_generated_function_mockers_test::FooInterface::Binary (short x, int y) pure virtual
Referenced by testing::gmock_generated_function_mockers_test::FunctionMockerTest::FunctionMockerTest(), testing::gmock_generated_function_mockers_test::MockFoo::MockFoo(), testing::gmock_generated_function_mockers_test::TEST_F(), and ~FooInterface().
virtual long testing::gmock_generated_function_mockers_test::FooInterface::Binary (short x, int y) pure virtual
virtual long testing::gmock_generated_function_mockers_test::FooInterface::Binary (short x, int y) pure virtual
virtual int testing::gmock_generated_function_mockers_test::FooInterface::Decimal (bool b, char c, short d, int e, long f, float g, double h, unsigned i, char * j, const string & k) pure virtual
virtual int testing::gmock_generated_function_mockers_test::FooInterface::Decimal (bool b, char c, short d, int e, long f, float g, double h, unsigned i, char * j, const string & k) pure virtual
Referenced by testing::gmock_generated_function_mockers_test::FunctionMockerTest::FunctionMockerTest(), testing::gmock_generated_function_mockers_test::MockFoo::MockFoo(), testing::gmock_generated_function_mockers_test::TEST_F(), and ~FooInterface().
virtual int testing::gmock_generated_function_mockers_test::FooInterface::Decimal (bool b, char c, short d, int e, long f, float g, double h, unsigned i, char * j, const string & k) pure virtual
virtual int testing::gmock_generated_function_mockers_test::FooInterface::Nullary () pure virtual
virtual int testing::gmock_generated_function_mockers_test::FooInterface::Nullary () pure virtual
virtual int testing::gmock_generated_function_mockers_test::FooInterface::Nullary () pure virtual
Referenced by testing::gmock_generated_function_mockers_test::FunctionMockerTest::FunctionMockerTest(), testing::gmock_generated_function_mockers_test::MockFoo::MockFoo(), testing::gmock_generated_function_mockers_test::TEST_F(), and ~FooInterface().
virtual int testing::gmock_generated_function_mockers_test::FooInterface::OverloadedOnArgumentNumber () pure virtual
Referenced by testing::gmock_generated_function_mockers_test::FunctionMockerTest::FunctionMockerTest(), testing::gmock_generated_function_mockers_test::MockFoo::MockFoo(), testing::gmock_generated_function_mockers_test::TEST_F(), and ~FooInterface().
virtual int testing::gmock_generated_function_mockers_test::FooInterface::OverloadedOnArgumentNumber () pure virtual
virtual int testing::gmock_generated_function_mockers_test::FooInterface::OverloadedOnArgumentNumber () pure virtual
virtual int testing::gmock_generated_function_mockers_test::FooInterface::OverloadedOnArgumentNumber (int n) pure virtual
virtual int testing::gmock_generated_function_mockers_test::FooInterface::OverloadedOnArgumentNumber (int n) pure virtual
virtual int testing::gmock_generated_function_mockers_test::FooInterface::OverloadedOnArgumentNumber (int n) pure virtual
virtual int testing::gmock_generated_function_mockers_test::FooInterface::OverloadedOnArgumentType (int n) pure virtual
virtual int testing::gmock_generated_function_mockers_test::FooInterface::OverloadedOnArgumentType (int n) pure virtual
Referenced by testing::gmock_generated_function_mockers_test::FunctionMockerTest::FunctionMockerTest(), testing::gmock_generated_function_mockers_test::MockFoo::MockFoo(), testing::gmock_generated_function_mockers_test::TEST_F(), and ~FooInterface().
virtual int testing::gmock_generated_function_mockers_test::FooInterface::OverloadedOnArgumentType (int n) pure virtual
virtual char testing::gmock_generated_function_mockers_test::FooInterface::OverloadedOnArgumentType (char c) pure virtual
virtual char testing::gmock_generated_function_mockers_test::FooInterface::OverloadedOnArgumentType (char c) pure virtual
virtual char testing::gmock_generated_function_mockers_test::FooInterface::OverloadedOnArgumentType (char c) pure virtual
virtual int testing::gmock_generated_function_mockers_test::FooInterface::OverloadedOnConstness () pure virtual
virtual int testing::gmock_generated_function_mockers_test::FooInterface::OverloadedOnConstness () pure virtual
Referenced by testing::gmock_generated_function_mockers_test::FunctionMockerTest::FunctionMockerTest(), testing::gmock_generated_function_mockers_test::MockFoo::MockFoo(), testing::gmock_generated_function_mockers_test::TEST_F(), and ~FooInterface().
virtual int testing::gmock_generated_function_mockers_test::FooInterface::OverloadedOnConstness () pure virtual
virtual char testing::gmock_generated_function_mockers_test::FooInterface::OverloadedOnConstness () const pure virtual
virtual char testing::gmock_generated_function_mockers_test::FooInterface::OverloadedOnConstness () const pure virtual
virtual char testing::gmock_generated_function_mockers_test::FooInterface::OverloadedOnConstness () const pure virtual
virtual bool testing::gmock_generated_function_mockers_test::FooInterface::TakesConst (const int x) pure virtual
Referenced by testing::gmock_generated_function_mockers_test::FunctionMockerTest::FunctionMockerTest(), testing::gmock_generated_function_mockers_test::MockFoo::MockFoo(), testing::gmock_generated_function_mockers_test::TEST_F(), and ~FooInterface().
virtual bool testing::gmock_generated_function_mockers_test::FooInterface::TakesConst (const int x) pure virtual
virtual bool testing::gmock_generated_function_mockers_test::FooInterface::TakesConst (const int x) pure virtual
virtual string testing::gmock_generated_function_mockers_test::FooInterface::TakesConstReference (const int & n) pure virtual
virtual string testing::gmock_generated_function_mockers_test::FooInterface::TakesConstReference (const int & n) pure virtual
virtual string testing::gmock_generated_function_mockers_test::FooInterface::TakesConstReference (const int & n) pure virtual
Referenced by testing::gmock_generated_function_mockers_test::FunctionMockerTest::FunctionMockerTest(), testing::gmock_generated_function_mockers_test::MockFoo::MockFoo(), testing::gmock_generated_function_mockers_test::TEST_F(), and ~FooInterface().
virtual bool testing::gmock_generated_function_mockers_test::FooInterface::TakesNonConstReference (int & n) pure virtual
virtual bool testing::gmock_generated_function_mockers_test::FooInterface::TakesNonConstReference (int & n) pure virtual
Referenced by testing::gmock_generated_function_mockers_test::FunctionMockerTest::FunctionMockerTest(), testing::gmock_generated_function_mockers_test::MockFoo::MockFoo(), testing::gmock_generated_function_mockers_test::TEST_F(), and ~FooInterface().
virtual bool testing::gmock_generated_function_mockers_test::FooInterface::TakesNonConstReference (int & n) pure virtual
virtual int testing::gmock_generated_function_mockers_test::FooInterface::TypeWithComma (const std::map< int, string > & a_map) pure virtual
virtual int testing::gmock_generated_function_mockers_test::FooInterface::TypeWithComma (const std::map< int, string > & a_map) pure virtual
Referenced by testing::gmock_generated_function_mockers_test::MockFoo::MockFoo(), and ~FooInterface().
virtual int testing::gmock_generated_function_mockers_test::FooInterface::TypeWithComma (const std::map< int, string > & a_map) pure virtual
virtual int testing::gmock_generated_function_mockers_test::FooInterface::TypeWithHole (int(*)() func) pure virtual
virtual int testing::gmock_generated_function_mockers_test::FooInterface::TypeWithHole (int(*)() func) pure virtual
virtual int testing::gmock_generated_function_mockers_test::FooInterface::TypeWithHole (int(*)() func) pure virtual
Referenced by testing::gmock_generated_function_mockers_test::MockFoo::MockFoo(), and ~FooInterface().
virtual bool testing::gmock_generated_function_mockers_test::FooInterface::Unary (int x) pure virtual
virtual bool testing::gmock_generated_function_mockers_test::FooInterface::Unary (int x) pure virtual
virtual bool testing::gmock_generated_function_mockers_test::FooInterface::Unary (int x) pure virtual
Referenced by testing::gmock_generated_function_mockers_test::FunctionMockerTest::FunctionMockerTest(), testing::gmock_generated_function_mockers_test::MockFoo::MockFoo(), testing::gmock_generated_function_mockers_test::TEST_F(), and ~FooInterface().
virtual void testing::gmock_generated_function_mockers_test::FooInterface::VoidReturning (int x) pure virtual
Referenced by testing::gmock_generated_function_mockers_test::FunctionMockerTest::FunctionMockerTest(), testing::gmock_generated_function_mockers_test::MockFoo::MockFoo(), testing::gmock_generated_function_mockers_test::TEST_F(), and ~FooInterface().
virtual void testing::gmock_generated_function_mockers_test::FooInterface::VoidReturning (int x) pure virtual
virtual void testing::gmock_generated_function_mockers_test::FooInterface::VoidReturning (int x) pure virtual
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-generated-function-mockers_test.cc