proxygen: wangle::OutboundLink< Out > Class Template Reference
wangle::OutboundLink< Out > Class Template Reference abstract
#include <HandlerContext-inl.h>
Public Member Functions
virtual ~OutboundLink ()=default
virtual folly::Future< folly::Unit > write (Out msg)=0
virtual folly::Future< folly::Unit > writeException (folly::exception_wrapper e)=0
virtual folly::Future< folly::Unit > close ()=0
Detailed Description
template<class Out>
class wangle::OutboundLink< Out >
Definition at line 65 of file HandlerContext-inl.h.
Constructor & Destructor Documentation
template<class Out> virtual wangle::OutboundLink< Out >::~OutboundLink () virtual default
Member Function Documentation
template<class Out> virtual folly::Future<folly::Unit> wangle::OutboundLink< Out >::close () pure virtual
Implemented in wangle::OutboundContextImpl< H >, and wangle::ContextImpl< H >.
Referenced by wangle::Pipeline< R, W >::close().
template<class Out> virtual folly::Future<folly::Unit> wangle::OutboundLink< Out >::write (Out msg) pure virtual
Implemented in wangle::OutboundContextImpl< H >, and wangle::ContextImpl< H >.
Referenced by wangle::Pipeline< R, W >::write().
template<class Out> virtual folly::Future<folly::Unit> wangle::OutboundLink< Out >::writeException (folly::exception_wrapper e) pure virtual
Implemented in wangle::OutboundContextImpl< H >, and wangle::ContextImpl< H >.
Referenced by wangle::Pipeline< R, W >::writeException().
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/channel/HandlerContext-inl.h