proxygen: folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Puller Class Reference
folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Puller Class Reference
Public Member Functions
Puller (InQueue *queue)
template<class Handler >
bool apply (Handler &&handler) const
template<class Body >
void foreach (Body &&body) const
Public Member Functions inherited from folly::gen::GenImpl< InputDecayed &&, Puller >
bool apply (Handler &&handler) const
void foreach (Body &&body) const
Public Member Functions inherited from folly::gen::FBounded< Self >
const Self & self () const
Self & self ()
Private Attributes
InQueue * queue_
Additional Inherited Members
Public Types inherited from folly::gen::GenImpl< InputDecayed &&, Puller >
typedef InputDecayed && ValueType
typedef std::decay< InputDecayed && >::type StorageType
Static Public Attributes inherited from folly::gen::GenImpl< InputDecayed &&, Puller >
static constexpr bool infinite
Protected Member Functions inherited from folly::gen::GenImpl< InputDecayed &&, Puller >
GenImpl ()=default
GenImpl (GenImpl &&)=default
GenImpl (const GenImpl &)=default
GenImpl & operator= (GenImpl &&)=default
GenImpl & operator= (const GenImpl &)=default
Detailed Description
template<class Ops>
template<class Input, class Source, class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type>
class folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Puller
Definition at line 182 of file Parallel-inl.h.
Constructor & Destructor Documentation
template<class Ops > template<class Input , class Source , class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type> folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Puller::Puller (InQueue * queue) inline explicit
Definition at line 186 of file Parallel-inl.h.
 : queue_(queue) {}
Member Function Documentation
template<class Ops > template<class Input , class Source , class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type> template<class Handler > bool folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Puller::apply (Handler && handler) const inline
Definition at line 189 of file Parallel-inl.h.
References handler(), folly::gen::move, and folly::gen::detail::ClosableMPMCQueue< T >::readUnlessClosed().
{
         InputDecayed input;
         while (queue_->readUnlessClosed(input)) {
           if (!handler(std::move(input))) {
             return false;
           }
         }
         return true;
       }
template<class Ops > template<class Input , class Source , class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type> template<class Body > void folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Puller::foreach (Body && body) const inline
Definition at line 200 of file Parallel-inl.h.
References folly::gen::move, and folly::gen::detail::ClosableMPMCQueue< T >::readUnlessClosed().
{
         InputDecayed input;
         while (queue_->readUnlessClosed(input)) {
           body(std::move(input));
         }
       }
Member Data Documentation
template<class Ops > template<class Input , class Source , class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type> InQueue* folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Puller::queue_ private
Definition at line 183 of file Parallel-inl.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/gen/Parallel-inl.h