proxygen: testing::internal::StreamMatchResultListener Class Reference
testing::internal::StreamMatchResultListener Class Reference
#include <gmock-matchers.h>
Public Member Functions
StreamMatchResultListener (::std::ostream *os)
StreamMatchResultListener (::std::ostream *os)
StreamMatchResultListener (::std::ostream *os)
Public Member Functions inherited from testing::MatchResultListener
MatchResultListener (::std::ostream *os)
virtual ~MatchResultListener ()=0
template<typename T >
MatchResultListener & operator<< (const T &x)
::std::ostream * stream ()
bool IsInterested () const
MatchResultListener (::std::ostream *os)
virtual ~MatchResultListener ()=0
template<typename T >
MatchResultListener & operator<< (const T &x)
::std::ostream * stream ()
bool IsInterested () const
MatchResultListener (::std::ostream *os)
virtual ~MatchResultListener ()=0
template<typename T >
MatchResultListener & operator<< (const T &x)
::std::ostream * stream ()
bool IsInterested () const
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (StreamMatchResultListener)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (StreamMatchResultListener)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (StreamMatchResultListener)
Detailed Description
Definition at line 239 of file gmock-matchers.h.
Constructor & Destructor Documentation
testing::internal::StreamMatchResultListener::StreamMatchResultListener (::std::ostream * os) inline explicit
Definition at line 241 of file gmock-matchers.h.
References testing::MatchResultListener::GTEST_DISALLOW_COPY_AND_ASSIGN_().
       : MatchResultListener(os) {}
testing::internal::StreamMatchResultListener::StreamMatchResultListener (::std::ostream * os) inline explicit
Definition at line 241 of file gmock-matchers.h.
References testing::MatchResultListener::GTEST_DISALLOW_COPY_AND_ASSIGN_().
       : MatchResultListener(os) {}
testing::internal::StreamMatchResultListener::StreamMatchResultListener (::std::ostream * os) inline explicit
Definition at line 241 of file gmock-matchers.h.
References testing::MatchResultListener::GTEST_DISALLOW_COPY_AND_ASSIGN_().
       : MatchResultListener(os) {}
Member Function Documentation
testing::internal::StreamMatchResultListener::GTEST_DISALLOW_COPY_AND_ASSIGN_ (StreamMatchResultListener) private
testing::internal::StreamMatchResultListener::GTEST_DISALLOW_COPY_AND_ASSIGN_ (StreamMatchResultListener) private
testing::internal::StreamMatchResultListener::GTEST_DISALLOW_COPY_AND_ASSIGN_ (StreamMatchResultListener) private
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h