proxygen: proxygen::MockHTTPPushHandler Class Reference
proxygen::MockHTTPPushHandler Class Reference
#include <HTTPSessionMocks.h>
Public Member Functions
MockHTTPPushHandler ()
MockHTTPPushHandler (HTTPTransaction &txn, HTTPMessage *msg, const folly::SocketAddress &)
GMOCK_METHOD1_ (, noexcept,, setTransaction, void(HTTPTransaction *txn))
GMOCK_METHOD0_ (, noexcept,, detachTransaction, void())
GMOCK_METHOD1_ (, noexcept,, onError, void(const HTTPException &error))
GMOCK_METHOD1_ (, noexcept,, onGoaway, void(ErrorCode))
GMOCK_METHOD0_ (, noexcept,, onEgressPaused, void())
GMOCK_METHOD0_ (, noexcept,, onEgressResumed, void())
void sendPushHeaders (const std::string &path, const std::string &host, uint32_t content_length, http2::PriorityUpdate pri)
Public Member Functions inherited from proxygen::HTTPHandlerBase
HTTPHandlerBase ()
HTTPHandlerBase (HTTPTransaction *txn, HTTPMessage *msg)
void terminate ()
void sendRequest ()
void sendRequest (HTTPMessage req)
void sendHeaders (uint32_t code, uint32_t content_length, bool keepalive=true, HeaderMap headers=HeaderMap())
void sendReply ()
void sendReplyCode (uint32_t code)
void sendBody (uint32_t content_length)
void sendBodyWithLastByteTracking (uint32_t content_length)
void sendReplyWithBody (uint32_t code, uint32_t content_length, bool keepalive=true, bool sendEOM=true, bool hasTrailers=false)
void sendEOM ()
void sendChunkedReplyWithBody (uint32_t code, uint32_t content_length, uint32_t chunkSize, bool hasTrailers, bool sendEOM=true)
Public Member Functions inherited from proxygen::HTTPPushTransactionHandler
~HTTPPushTransactionHandler () override
void onHeadersComplete (std::unique_ptr< HTTPMessage >) noexceptfinal
void onBody (std::unique_ptr< folly::IOBuf >) noexceptfinal
void onChunkHeader (size_t) noexceptfinal
void onChunkComplete () noexceptfinal
void onTrailers (std::unique_ptr< HTTPHeaders >) noexceptfinal
void onEOM () noexceptfinal
void onUpgrade (UpgradeProtocol) noexceptfinal
void onPushedTransaction (HTTPTransaction *) noexceptfinal
Public Member Functions inherited from proxygen::HTTPTransactionHandler
virtual void setTransaction (HTTPTransaction *txn) noexcept=0
virtual void detachTransaction () noexcept=0
virtual void onError (const HTTPException &error) noexcept=0
virtual void onEgressPaused () noexcept=0
virtual void onEgressResumed () noexcept=0
virtual void onExTransaction (HTTPTransaction *) noexcept
virtual void onGoaway (ErrorCode) noexcept
virtual ~HTTPTransactionHandler ()
Additional Inherited Members
Public Types inherited from proxygen::HTTPHandlerBase
using HeaderMap = std::map< std::string, std::string >
Public Attributes inherited from proxygen::HTTPHandlerBase
HTTPTransaction * txn_ {nullptr}
std::shared_ptr< HTTPMessage > msg_
Detailed Description
Definition at line 321 of file HTTPSessionMocks.h.
Constructor & Destructor Documentation
proxygen::MockHTTPPushHandler::MockHTTPPushHandler () inline
Definition at line 325 of file HTTPSessionMocks.h.
{
   }
proxygen::MockHTTPPushHandler::MockHTTPPushHandler (HTTPTransaction & txn, HTTPMessage * msg, const folly::SocketAddress &) inline
Definition at line 327 of file HTTPSessionMocks.h.
References GMOCK_NOEXCEPT_METHOD0, and GMOCK_NOEXCEPT_METHOD1.
       : HTTPHandlerBase(&txn, msg) {
   }
Member Function Documentation
proxygen::MockHTTPPushHandler::GMOCK_METHOD0_ (noexcept , detachTransaction , void())
proxygen::MockHTTPPushHandler::GMOCK_METHOD0_ (noexcept , onEgressPaused , void())
proxygen::MockHTTPPushHandler::GMOCK_METHOD0_ (noexcept , onEgressResumed , void())
proxygen::MockHTTPPushHandler::GMOCK_METHOD1_ (noexcept , setTransaction , void(HTTPTransaction *txn))
proxygen::MockHTTPPushHandler::GMOCK_METHOD1_ (noexcept , onError , void(const HTTPException &error))
proxygen::MockHTTPPushHandler::GMOCK_METHOD1_ (noexcept , onGoaway , void(ErrorCode))
void proxygen::MockHTTPPushHandler::sendPushHeaders (const std::string & path, const std::string & host, uint32_t content_length, http2::PriorityUpdate pri) inline
Definition at line 345 of file HTTPSessionMocks.h.
References proxygen::HTTPHeaders::add(), proxygen::http2::PriorityUpdate::exclusive, proxygen::HTTPMessage::getHeaders(), proxygen::HTTP_HEADER_CONTENT_LENGTH, proxygen::HTTP_HEADER_HOST, std::tr1::make_tuple(), proxygen::HTTPTransaction::sendHeaders(), proxygen::HTTPHeaders::set(), proxygen::HTTPMessage::setHTTP2Priority(), proxygen::HTTPMessage::setURL(), proxygen::http2::PriorityUpdate::streamDependency, proxygen::HTTPHandlerBase::txn_, and proxygen::http2::PriorityUpdate::weight.
Referenced by TEST_F().
{
     HTTPMessage push;
     push.setURL(path);
     push.getHeaders().set(HTTP_HEADER_HOST, host);
     push.getHeaders().add(HTTP_HEADER_CONTENT_LENGTH,
                           folly::to<std::string>(content_length));
     push.setHTTP2Priority(
         std::make_tuple(pri.streamDependency, pri.exclusive, pri.weight));
     txn_->sendHeaders(push);
   }
The documentation for this class was generated from the following file:
proxygen/lib/http/session/test/HTTPSessionMocks.h