proxygen: testing::internal::XmlUnitTestResultPrinter Class Reference
testing::internal::XmlUnitTestResultPrinter Class Reference
Public Member Functions
XmlUnitTestResultPrinter (const char *output_file)
virtual void OnTestIterationEnd (const UnitTest &unit_test, int iteration)
XmlUnitTestResultPrinter (const char *output_file)
virtual void OnTestIterationEnd (const UnitTest &unit_test, int iteration)
XmlUnitTestResultPrinter (const char *output_file)
virtual void OnTestIterationEnd (const UnitTest &unit_test, int iteration)
Public Member Functions inherited from testing::EmptyTestEventListener
virtual void OnTestProgramStart (const UnitTest &)
virtual void OnTestIterationStart (const UnitTest &, int)
virtual void OnEnvironmentsSetUpStart (const UnitTest &)
virtual void OnEnvironmentsSetUpEnd (const UnitTest &)
virtual void OnTestCaseStart (const TestCase &)
virtual void OnTestStart (const TestInfo &)
virtual void OnTestPartResult (const TestPartResult &)
virtual void OnTestEnd (const TestInfo &)
virtual void OnTestCaseEnd (const TestCase &)
virtual void OnEnvironmentsTearDownStart (const UnitTest &)
virtual void OnEnvironmentsTearDownEnd (const UnitTest &)
virtual void OnTestProgramEnd (const UnitTest &)
virtual void OnTestProgramStart (const UnitTest &)
virtual void OnTestIterationStart (const UnitTest &, int)
virtual void OnEnvironmentsSetUpStart (const UnitTest &)
virtual void OnEnvironmentsSetUpEnd (const UnitTest &)
virtual void OnTestCaseStart (const TestCase &)
virtual void OnTestStart (const TestInfo &)
virtual void OnTestPartResult (const TestPartResult &)
virtual void OnTestEnd (const TestInfo &)
virtual void OnTestCaseEnd (const TestCase &)
virtual void OnEnvironmentsTearDownStart (const UnitTest &)
virtual void OnEnvironmentsTearDownEnd (const UnitTest &)
virtual void OnTestProgramEnd (const UnitTest &)
virtual void OnTestProgramStart (const UnitTest &)
virtual void OnTestIterationStart (const UnitTest &, int)
virtual void OnEnvironmentsSetUpStart (const UnitTest &)
virtual void OnEnvironmentsSetUpEnd (const UnitTest &)
virtual void OnTestCaseStart (const TestCase &)
virtual void OnTestStart (const TestInfo &)
virtual void OnTestPartResult (const TestPartResult &)
virtual void OnTestEnd (const TestInfo &)
virtual void OnTestCaseEnd (const TestCase &)
virtual void OnEnvironmentsTearDownStart (const UnitTest &)
virtual void OnEnvironmentsTearDownEnd (const UnitTest &)
virtual void OnTestProgramEnd (const UnitTest &)
Public Member Functions inherited from testing::TestEventListener
virtual ~TestEventListener ()
virtual ~TestEventListener ()
virtual ~TestEventListener ()
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (XmlUnitTestResultPrinter)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (XmlUnitTestResultPrinter)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (XmlUnitTestResultPrinter)
Static Private Member Functions
static bool IsNormalizableWhitespace (char c)
static bool IsValidXmlCharacter (char c)
static std::string EscapeXml (const std::string &str, bool is_attribute)
static std::string RemoveInvalidXmlCharacters (const std::string &str)
static std::string EscapeXmlAttribute (const std::string &str)
static std::string EscapeXmlText (const char *str)
static void OutputXmlAttribute (std::ostream *stream, const std::string &element_name, const std::string &name, const std::string &value)
static void OutputXmlCDataSection (::std::ostream *stream, const char *data)
static void OutputXmlTestInfo (::std::ostream *stream, const char *test_case_name, const TestInfo &test_info)
static void PrintXmlTestCase (::std::ostream *stream, const TestCase &test_case)
static void PrintXmlUnitTest (::std::ostream *stream, const UnitTest &unit_test)
static std::string TestPropertiesAsXmlAttributes (const TestResult &result)
static bool IsNormalizableWhitespace (char c)
static bool IsValidXmlCharacter (char c)
static std::string EscapeXml (const std::string &str, bool is_attribute)
static std::string RemoveInvalidXmlCharacters (const std::string &str)
static std::string EscapeXmlAttribute (const std::string &str)
static std::string EscapeXmlText (const char *str)
static void OutputXmlAttribute (std::ostream *stream, const std::string &element_name, const std::string &name, const std::string &value)
static void OutputXmlCDataSection (::std::ostream *stream, const char *data)
static void OutputXmlTestInfo (::std::ostream *stream, const char *test_case_name, const TestInfo &test_info)
static void PrintXmlTestCase (::std::ostream *stream, const TestCase &test_case)
static void PrintXmlUnitTest (::std::ostream *stream, const UnitTest &unit_test)
static std::string TestPropertiesAsXmlAttributes (const TestResult &result)
static bool IsNormalizableWhitespace (char c)
static bool IsValidXmlCharacter (char c)
static std::string EscapeXml (const std::string &str, bool is_attribute)
static std::string RemoveInvalidXmlCharacters (const std::string &str)
static std::string EscapeXmlAttribute (const std::string &str)
static std::string EscapeXmlText (const char *str)
static void OutputXmlAttribute (std::ostream *stream, const std::string &element_name, const std::string &name, const std::string &value)
static void OutputXmlCDataSection (::std::ostream *stream, const char *data)
static void OutputXmlTestInfo (::std::ostream *stream, const char *test_case_name, const TestInfo &test_info)
static void PrintXmlTestCase (::std::ostream *stream, const TestCase &test_case)
static void PrintXmlUnitTest (::std::ostream *stream, const UnitTest &unit_test)
static std::string TestPropertiesAsXmlAttributes (const TestResult &result)
Private Attributes
const std::string output_file_
Detailed Description
Definition at line 3349 of file gtest.cc.
Constructor & Destructor Documentation
testing::internal::XmlUnitTestResultPrinter::XmlUnitTestResultPrinter (const char * output_file) explicit
Definition at line 3422 of file gtest.cc.
References output_file_.
Referenced by EscapeXmlText().
     : output_file_(output_file) {
   if (output_file_.c_str() == NULL || output_file_.empty()) {
     fprintf(stderr, "XML output file may not be null\n");
     fflush(stderr);
     exit(EXIT_FAILURE);
   }
 }
testing::internal::XmlUnitTestResultPrinter::XmlUnitTestResultPrinter (const char * output_file) explicit
testing::internal::XmlUnitTestResultPrinter::XmlUnitTestResultPrinter (const char * output_file) explicit
Member Function Documentation
std::string testing::internal::XmlUnitTestResultPrinter::EscapeXml (const std::string & str, bool is_attribute) static private
Definition at line 3476 of file gtest.cc.
References ch, testing::internal::String::FormatByte(), testing::Message::GetString(), i, IsNormalizableWhitespace(), IsValidXmlCharacter(), and m.
Referenced by EscapeXmlText().
{
   Message m;
   for (size_t i = 0; i < str.size(); ++i) {
     const char ch = str[i];
     switch (ch) {
       case '<':
         m << "&lt;";
         break;
       case '>':
         m << "&gt;";
         break;
       case '&':
         m << "&amp;";
         break;
       case '\'':
         if (is_attribute)
           m << "&apos;";
         else
           m << '\'';
         break;
       case '"':
         if (is_attribute)
           m << "&quot;";
         else
           m << '"';
         break;
       default:
         if (IsValidXmlCharacter(ch)) {
           if (is_attribute && IsNormalizableWhitespace(ch))
             m << "&#x" << String::FormatByte(static_cast<unsigned char>(ch))
               << ";";
           else
             m << ch;
         }
         break;
     }
   }
   return m.GetString();
 }
static std::string testing::internal::XmlUnitTestResultPrinter::EscapeXml (const std::string & str, bool is_attribute) static private
static std::string testing::internal::XmlUnitTestResultPrinter::EscapeXml (const std::string & str, bool is_attribute) static private
static std::string testing::internal::XmlUnitTestResultPrinter::EscapeXmlAttribute (const std::string & str) inline static private
Definition at line 3377 of file gtest.cc.
{
     return EscapeXml(str, true);
   }
static std::string testing::internal::XmlUnitTestResultPrinter::EscapeXmlAttribute (const std::string & str) inline static private
Definition at line 3377 of file gtest.cc.
{
     return EscapeXml(str, true);
   }
static std::string testing::internal::XmlUnitTestResultPrinter::EscapeXmlAttribute (const std::string & str) inline static private
Definition at line 3377 of file gtest.cc.
Referenced by OutputXmlAttribute(), OutputXmlTestInfo(), and TestPropertiesAsXmlAttributes().
{
     return EscapeXml(str, true);
   }
static std::string testing::internal::XmlUnitTestResultPrinter::EscapeXmlText (const char * str) inline static private
Definition at line 3382 of file gtest.cc.
References ch, data, EscapeXml(), FILE, testing::internal::posix::FOpen(), testing::internal::String::FormatByte(), testing::internal::FormatTimeInMillisAsSeconds(), testing::Message::GetString(), GTEST_DISALLOW_COPY_AND_ASSIGN_, i, m, name, OnTestIterationEnd(), gmock_output_test::output, versiongenerate::output_dir, testing::internal::FilePath::RemoveFileName(), RemoveInvalidXmlCharacters(), stream, string, testing::internal::StringStreamToString(), and XmlUnitTestResultPrinter().
{
     return EscapeXml(str, false);
   }
static std::string testing::internal::XmlUnitTestResultPrinter::EscapeXmlText (const char * str) inline static private
Definition at line 3382 of file gtest.cc.
References ch, data, EscapeXml(), FILE, testing::internal::posix::FOpen(), testing::internal::String::FormatByte(), testing::internal::FormatTimeInMillisAsSeconds(), testing::Message::GetString(), GTEST_DISALLOW_COPY_AND_ASSIGN_, i, m, name, OnTestIterationEnd(), gmock_output_test::output, versiongenerate::output_dir, testing::internal::FilePath::RemoveFileName(), RemoveInvalidXmlCharacters(), stream, string, testing::internal::StringStreamToString(), and XmlUnitTestResultPrinter().
{
     return EscapeXml(str, false);
   }
static std::string testing::internal::XmlUnitTestResultPrinter::EscapeXmlText (const char * str) inline static private
Definition at line 3382 of file gtest.cc.
References data, testing::TestCase::name(), string, and value.
{
     return EscapeXml(str, false);
   }
testing::internal::XmlUnitTestResultPrinter::GTEST_DISALLOW_COPY_AND_ASSIGN_ (XmlUnitTestResultPrinter) private
testing::internal::XmlUnitTestResultPrinter::GTEST_DISALLOW_COPY_AND_ASSIGN_ (XmlUnitTestResultPrinter) private
testing::internal::XmlUnitTestResultPrinter::GTEST_DISALLOW_COPY_AND_ASSIGN_ (XmlUnitTestResultPrinter) private
static bool testing::internal::XmlUnitTestResultPrinter::IsNormalizableWhitespace (char c) inline static private
Definition at line 3358 of file gtest.cc.
Referenced by EscapeXml().
{
     return c == 0x9 || c == 0xA || c == 0xD;
   }
static bool testing::internal::XmlUnitTestResultPrinter::IsNormalizableWhitespace (char c) inline static private
Definition at line 3358 of file gtest.cc.
{
     return c == 0x9 || c == 0xA || c == 0xD;
   }
static bool testing::internal::XmlUnitTestResultPrinter::IsNormalizableWhitespace (char c) inline static private
Definition at line 3358 of file gtest.cc.
{
     return c == 0x9 || c == 0xA || c == 0xD;
   }
static bool testing::internal::XmlUnitTestResultPrinter::IsValidXmlCharacter (char c) inline static private
Definition at line 3363 of file gtest.cc.
References string.
{
     return IsNormalizableWhitespace(c) || c >= 0x20;
   }
static bool testing::internal::XmlUnitTestResultPrinter::IsValidXmlCharacter (char c) inline static private
Definition at line 3363 of file gtest.cc.
References string.
Referenced by EscapeXml(), and RemoveInvalidXmlCharacters().
{
     return IsNormalizableWhitespace(c) || c >= 0x20;
   }
static bool testing::internal::XmlUnitTestResultPrinter::IsValidXmlCharacter (char c) inline static private
Definition at line 3363 of file gtest.cc.
References string.
{
     return IsNormalizableWhitespace(c) || c >= 0x20;
   }
void testing::internal::XmlUnitTestResultPrinter::OnTestIterationEnd (const UnitTest & unit_test, int iteration) virtual
Reimplemented from testing::EmptyTestEventListener.
Definition at line 3432 of file gtest.cc.
References FILE, testing::internal::posix::FOpen(), versiongenerate::output_dir, output_file_, PrintXmlUnitTest(), testing::internal::FilePath::RemoveFileName(), stream, and testing::internal::StringStreamToString().
Referenced by EscapeXmlText().
{
   FILE* xmlout = NULL;
   FilePath output_file(output_file_);
   FilePath output_dir(output_file.RemoveFileName());
   if (output_dir.CreateDirectoriesRecursively()) {
     xmlout = posix::FOpen(output_file_.c_str(), "w");
   }
   if (xmlout == NULL) {
     // TODO(wan): report the reason of the failure.
     //
     // We don't do it for now as:
     //
     //   1. There is no urgent need for it.
     //   2. It's a bit involved to make the errno variable thread-safe on
     //      all three operating systems (Linux, Windows, and Mac OS).
     //   3. To interpret the meaning of errno in a thread-safe way,
     //      we need the strerror_r() function, which is not available on
     //      Windows.
     fprintf(stderr,
             "Unable to open file \"%s\"\n",
             output_file_.c_str());
     fflush(stderr);
     exit(EXIT_FAILURE);
   }
   std::stringstream stream;
   PrintXmlUnitTest(&stream, unit_test);
   fprintf(xmlout, "%s", StringStreamToString(&stream).c_str());
   fclose(xmlout);
 }
virtual void testing::internal::XmlUnitTestResultPrinter::OnTestIterationEnd (const UnitTest & unit_test, int iteration) virtual
Reimplemented from testing::EmptyTestEventListener.
virtual void testing::internal::XmlUnitTestResultPrinter::OnTestIterationEnd (const UnitTest & unit_test, int iteration) virtual
Reimplemented from testing::EmptyTestEventListener.
void testing::internal::XmlUnitTestResultPrinter::OutputXmlAttribute (std::ostream * stream, const std::string & element_name, const std::string & name, const std::string & value) static private
Definition at line 3607 of file gtest.cc.
References EscapeXmlAttribute(), testing::GetReservedAttributesForElement(), GTEST_CHECK_, and name.
Referenced by OutputXmlTestInfo(), and testing::internal::PortableLocaltime().
{
   const std::vector<std::string>& allowed_names =
       GetReservedAttributesForElement(element_name);
   GTEST_CHECK_(std::find(allowed_names.begin(), allowed_names.end(), name) !=
                    allowed_names.end())
       << "Attribute " << name << " is not allowed for element <" << element_name
       << ">.";
   *stream << " " << name << "=\"" << EscapeXmlAttribute(value) << "\"";
 }
static void testing::internal::XmlUnitTestResultPrinter::OutputXmlAttribute (std::ostream * stream, const std::string & element_name, const std::string & name, const std::string & value) static private
static void testing::internal::XmlUnitTestResultPrinter::OutputXmlAttribute (std::ostream * stream, const std::string & element_name, const std::string & name, const std::string & value) static private
static void testing::internal::XmlUnitTestResultPrinter::OutputXmlCDataSection (::std::ostream * stream, const char * data) static private
void testing::internal::XmlUnitTestResultPrinter::OutputXmlCDataSection (::std::ostream * stream, const char * data) static private
Definition at line 3588 of file gtest.cc.
References data.
Referenced by OutputXmlTestInfo(), and testing::internal::PortableLocaltime().
{
   const char* segment = data;
   *stream << "<![CDATA[";
   for (;;) {
     const char* const next_segment = strstr(segment, "]]>");
     if (next_segment != NULL) {
       stream->write(
           segment, static_cast<std::streamsize>(next_segment - segment));
       *stream << "]]>]]&gt;<![CDATA[";
       segment = next_segment + strlen("]]>");
     } else {
       *stream << segment;
       break;
     }
   }
   *stream << "]]>";
 }
static void testing::internal::XmlUnitTestResultPrinter::OutputXmlCDataSection (::std::ostream * stream, const char * data) static private
static void testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo (::std::ostream * stream, const char * test_case_name, const TestInfo & test_info) static private
void testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo (::std::ostream * stream, const char * test_case_name, const TestInfo & test_info) static private
Definition at line 3625 of file gtest.cc.
References testing::TestCase::ad_hoc_test_result(), testing::UnitTest::ad_hoc_test_result(), testing::TestResult::elapsed_time(), testing::TestCase::elapsed_time(), testing::UnitTest::elapsed_time(), EscapeXmlAttribute(), testing::TestPartResult::failed(), testing::TestCase::failed_test_count(), testing::UnitTest::failed_test_count(), testing::TestPartResult::file_name(), testing::internal::FormatCompilerIndependentFileLocation(), testing::internal::FormatEpochTimeInMillisAsIso8601(), testing::internal::FormatTimeInMillisAsSeconds(), testing::UnitTest::GetTestCase(), testing::TestCase::GetTestInfo(), testing::TestResult::GetTestPartResult(), GTEST_FLAG, i, testing::TestInfo::is_reportable(), testing::TestPartResult::line_number(), testing::TestPartResult::message(), testing::TestInfo::name(), testing::TestCase::name(), OutputXmlAttribute(), OutputXmlCDataSection(), PrintXmlTestCase(), PrintXmlUnitTest(), testing::UnitTest::random_seed(), RemoveInvalidXmlCharacters(), testing::TestCase::reportable_disabled_test_count(), testing::UnitTest::reportable_disabled_test_count(), testing::TestCase::reportable_test_count(), testing::UnitTest::reportable_test_count(), testing::TestInfo::result(), testing::TestInfo::should_run(), testing::UnitTest::start_timestamp(), testing::internal::StreamableToString(), string, testing::TestPartResult::summary(), TestPropertiesAsXmlAttributes(), testing::TestResult::total_part_count(), testing::UnitTest::total_test_case_count(), testing::TestCase::total_test_count(), testing::TestInfo::type_param(), and testing::TestInfo::value_param().
Referenced by testing::internal::PortableLocaltime().
{
   const TestResult& result = *test_info.result();
   const std::string kTestcase = "testcase";
   *stream << "    <testcase";
   OutputXmlAttribute(stream, kTestcase, "name", test_info.name());
   if (test_info.value_param() != NULL) {
     OutputXmlAttribute(stream, kTestcase, "value_param",
                        test_info.value_param());
   }
   if (test_info.type_param() != NULL) {
     OutputXmlAttribute(stream, kTestcase, "type_param", test_info.type_param());
   }
   OutputXmlAttribute(stream, kTestcase, "status",
                      test_info.should_run() ? "run" : "notrun");
   OutputXmlAttribute(stream, kTestcase, "time",
                      FormatTimeInMillisAsSeconds(result.elapsed_time()));
   OutputXmlAttribute(stream, kTestcase, "classname", test_case_name);
   *stream << TestPropertiesAsXmlAttributes(result);
   int failures = 0;
   for (int i = 0; i < result.total_part_count(); ++i) {
     const TestPartResult& part = result.GetTestPartResult(i);
     if (part.failed()) {
       if (++failures == 1) {
         *stream << ">\n";
       }
       const string location = internal::FormatCompilerIndependentFileLocation(
           part.file_name(), part.line_number());
       const string summary = location + "\n" + part.summary();
       *stream << "      <failure message=\""
               << EscapeXmlAttribute(summary.c_str())
               << "\" type=\"\">";
       const string detail = location + "\n" + part.message();
       OutputXmlCDataSection(stream, RemoveInvalidXmlCharacters(detail).c_str());
       *stream << "</failure>\n";
     }
   }
   if (failures == 0)
     *stream << " />\n";
   else
     *stream << "    </testcase>\n";
 }
static void testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo (::std::ostream * stream, const char * test_case_name, const TestInfo & test_info) static private
static void testing::internal::XmlUnitTestResultPrinter::PrintXmlTestCase (::std::ostream * stream, const TestCase & test_case) static private
static void testing::internal::XmlUnitTestResultPrinter::PrintXmlTestCase (::std::ostream * stream, const TestCase & test_case) static private
Referenced by OutputXmlTestInfo(), and testing::internal::PortableLocaltime().
static void testing::internal::XmlUnitTestResultPrinter::PrintXmlTestCase (::std::ostream * stream, const TestCase & test_case) static private
static void testing::internal::XmlUnitTestResultPrinter::PrintXmlUnitTest (::std::ostream * stream, const UnitTest & unit_test) static private
static void testing::internal::XmlUnitTestResultPrinter::PrintXmlUnitTest (::std::ostream * stream, const UnitTest & unit_test) static private
static void testing::internal::XmlUnitTestResultPrinter::PrintXmlUnitTest (::std::ostream * stream, const UnitTest & unit_test) static private
Referenced by OnTestIterationEnd(), OutputXmlTestInfo(), and testing::internal::PortableLocaltime().
static std::string testing::internal::XmlUnitTestResultPrinter::RemoveInvalidXmlCharacters (const std::string & str) static private
std::string testing::internal::XmlUnitTestResultPrinter::RemoveInvalidXmlCharacters (const std::string & str) static private
Definition at line 3522 of file gtest.cc.
References IsValidXmlCharacter(), gmock_output_test::output, and string.
Referenced by EscapeXmlText(), and OutputXmlTestInfo().
{
   std::string output;
   output.reserve(str.size());
   for (std::string::const_iterator it = str.begin(); it != str.end(); ++it)
     if (IsValidXmlCharacter(*it))
       output.push_back(*it);
   return output;
 }
static std::string testing::internal::XmlUnitTestResultPrinter::RemoveInvalidXmlCharacters (const std::string & str) static private
static std::string testing::internal::XmlUnitTestResultPrinter::TestPropertiesAsXmlAttributes (const TestResult & result) static private
static std::string testing::internal::XmlUnitTestResultPrinter::TestPropertiesAsXmlAttributes (const TestResult & result) static private
std::string testing::internal::XmlUnitTestResultPrinter::TestPropertiesAsXmlAttributes (const TestResult & result) static private
Definition at line 3741 of file gtest.cc.
References ch, folly::netops::close(), folly::netops::connect(), EscapeXmlAttribute(), testing::internal::String::FormatByte(), testing::Message::GetString(), testing::TestResult::GetTestProperty(), GTEST_CHECK_, GTEST_LOG_, i, folly::netops::socket(), and testing::TestResult::test_property_count().
Referenced by OutputXmlTestInfo(), and testing::internal::PortableLocaltime().
{
   Message attributes;
   for (int i = 0; i < result.test_property_count(); ++i) {
     const TestProperty& property = result.GetTestProperty(i);
     attributes << " " << property.key() << "="
         << "\"" << EscapeXmlAttribute(property.value()) << "\"";
   }
   return attributes.GetString();
 }
Member Data Documentation
const std::string testing::internal::XmlUnitTestResultPrinter::output_file_ private
Definition at line 3416 of file gtest.cc.
Referenced by OnTestIterationEnd(), and XmlUnitTestResultPrinter().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest.cc