proxygen: testing::gmock_generated_function_mockers_test::MockStack< T > Class Template Reference
testing::gmock_generated_function_mockers_test::MockStack< T > Class Template Reference
Public Member Functions
MockStack ()
MOCK_METHOD1_T (Push, void(const T &elem))
MOCK_METHOD0_T (Pop, void())
MOCK_CONST_METHOD0_T (GetSize, int())
MOCK_CONST_METHOD0_T (GetTop, const T &())
MOCK_METHOD0_T (ReturnTypeWithComma, std::map< int, int >())
MOCK_CONST_METHOD1_T (ReturnTypeWithComma, std::map< int, int >(int))
MockStack ()
MOCK_METHOD1_T (Push, void(const T &elem))
MOCK_METHOD0_T (Pop, void())
MOCK_CONST_METHOD0_T (GetSize, int())
MOCK_CONST_METHOD0_T (GetTop, const T &())
MOCK_METHOD0_T (ReturnTypeWithComma, std::map< int, int >())
MOCK_CONST_METHOD1_T (ReturnTypeWithComma, std::map< int, int >(int))
MockStack ()
MOCK_METHOD1_T (Push, void(const T &elem))
MOCK_METHOD0_T (Pop, void())
MOCK_CONST_METHOD0_T (GetSize, int())
MOCK_CONST_METHOD0_T (GetTop, const T &())
MOCK_METHOD0_T (ReturnTypeWithComma, std::map< int, int >())
MOCK_CONST_METHOD1_T (ReturnTypeWithComma, std::map< int, int >(int))
Public Member Functions inherited from testing::gmock_generated_function_mockers_test::StackInterface< T >
virtual ~StackInterface ()
virtual void Push (const T &value)=0
virtual void Pop ()=0
virtual int GetSize () const =0
virtual const T & GetTop () const =0
virtual ~StackInterface ()
virtual void Push (const T &value)=0
virtual void Pop ()=0
virtual int GetSize () const =0
virtual const T & GetTop () const =0
virtual ~StackInterface ()
virtual void Push (const T &value)=0
virtual void Pop ()=0
virtual int GetSize () const =0
virtual const T & GetTop () const =0
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockStack)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockStack)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockStack)
Detailed Description
template<typename T>
class testing::gmock_generated_function_mockers_test::MockStack< T >
Definition at line 398 of file gmock-generated-function-mockers_test.cc.
Constructor & Destructor Documentation
template<typename T> testing::gmock_generated_function_mockers_test::MockStack< T >::MockStack () inline
Definition at line 400 of file gmock-generated-function-mockers_test.cc.
References GTEST_DISALLOW_COPY_AND_ASSIGN_, MOCK_CONST_METHOD0_T, MOCK_CONST_METHOD1_T, MOCK_METHOD0_T, MOCK_METHOD1_T, Push, and T.
 {}
template<typename T> testing::gmock_generated_function_mockers_test::MockStack< T >::MockStack () inline
Definition at line 400 of file gmock-generated-function-mockers_test.cc.
References testing::_, testing::AnyNumber(), EXPECT_CALL, EXPECT_EQ, testing::gmock_generated_function_mockers_test::StackInterface< T >::GetSize(), testing::gmock_generated_function_mockers_test::StackInterface< T >::GetTop(), GTEST_DISALLOW_COPY_AND_ASSIGN_, MOCK_CONST_METHOD0_T, MOCK_CONST_METHOD0_T_WITH_CALLTYPE, MOCK_CONST_METHOD1_T, MOCK_METHOD0_T, MOCK_METHOD0_T_WITH_CALLTYPE, MOCK_METHOD1_T, MOCK_METHOD1_T_WITH_CALLTYPE, testing::gmock_generated_function_mockers_test::StackInterface< T >::Pop(), Push, testing::gmock_generated_function_mockers_test::StackInterface< T >::Push(), testing::Return(), testing::ReturnRef(), T, testing::gmock_generated_function_mockers_test::TEST(), and value.
 {}
template<typename T> testing::gmock_generated_function_mockers_test::MockStack< T >::MockStack () inline
Definition at line 400 of file gmock-generated-function-mockers_test.cc.
References testing::_, testing::AnyNumber(), EXPECT_CALL, EXPECT_EQ, testing::gmock_generated_function_mockers_test::StackInterface< T >::GetSize(), testing::gmock_generated_function_mockers_test::StackInterface< T >::GetTop(), GTEST_DISALLOW_COPY_AND_ASSIGN_, MOCK_CONST_METHOD0_T, MOCK_CONST_METHOD0_T_WITH_CALLTYPE, MOCK_CONST_METHOD1_T, MOCK_METHOD0_T, MOCK_METHOD0_T_WITH_CALLTYPE, MOCK_METHOD1_T, MOCK_METHOD1_T_WITH_CALLTYPE, testing::gmock_generated_function_mockers_test::StackInterface< T >::Pop(), Push, testing::gmock_generated_function_mockers_test::StackInterface< T >::Push(), testing::Return(), testing::ReturnRef(), T, testing::gmock_generated_function_mockers_test::TEST(), and value.
 {}
Member Function Documentation
template<typename T> testing::gmock_generated_function_mockers_test::MockStack< T >::GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockStack< T >) private
template<typename T> testing::gmock_generated_function_mockers_test::MockStack< T >::GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockStack< T >) private
template<typename T> testing::gmock_generated_function_mockers_test::MockStack< T >::GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockStack< T >) private
template<typename T> testing::gmock_generated_function_mockers_test::MockStack< T >::MOCK_CONST_METHOD0_T (GetSize , int())
template<typename T> testing::gmock_generated_function_mockers_test::MockStack< T >::MOCK_CONST_METHOD0_T (GetSize , int())
template<typename T> testing::gmock_generated_function_mockers_test::MockStack< T >::MOCK_CONST_METHOD0_T (GetSize , int())
template<typename T> testing::gmock_generated_function_mockers_test::MockStack< T >::MOCK_CONST_METHOD0_T (GetTop , const T & ())
template<typename T> testing::gmock_generated_function_mockers_test::MockStack< T >::MOCK_CONST_METHOD0_T (GetTop , const T & ())
template<typename T> testing::gmock_generated_function_mockers_test::MockStack< T >::MOCK_CONST_METHOD0_T (GetTop , const T & ())
template<typename T> testing::gmock_generated_function_mockers_test::MockStack< T >::MOCK_CONST_METHOD1_T (ReturnTypeWithComma , std::map< int, int > int)
template<typename T> testing::gmock_generated_function_mockers_test::MockStack< T >::MOCK_CONST_METHOD1_T (ReturnTypeWithComma , std::map< int, int > int)
template<typename T> testing::gmock_generated_function_mockers_test::MockStack< T >::MOCK_CONST_METHOD1_T (ReturnTypeWithComma , std::map< int, int > int)
template<typename T> testing::gmock_generated_function_mockers_test::MockStack< T >::MOCK_METHOD0_T (Pop , void())
template<typename T> testing::gmock_generated_function_mockers_test::MockStack< T >::MOCK_METHOD0_T (Pop , void())
template<typename T> testing::gmock_generated_function_mockers_test::MockStack< T >::MOCK_METHOD0_T (Pop , void())
template<typename T> testing::gmock_generated_function_mockers_test::MockStack< T >::MOCK_METHOD0_T (ReturnTypeWithComma , std::map< int, int > ())
template<typename T> testing::gmock_generated_function_mockers_test::MockStack< T >::MOCK_METHOD0_T (ReturnTypeWithComma , std::map< int, int > ())
template<typename T> testing::gmock_generated_function_mockers_test::MockStack< T >::MOCK_METHOD0_T (ReturnTypeWithComma , std::map< int, int > ())
template<typename T> testing::gmock_generated_function_mockers_test::MockStack< T >::MOCK_METHOD1_T (Push , void(const T &elem))
template<typename T> testing::gmock_generated_function_mockers_test::MockStack< T >::MOCK_METHOD1_T (Push , void(const T &elem))
template<typename T> testing::gmock_generated_function_mockers_test::MockStack< T >::MOCK_METHOD1_T (Push , void(const T &elem))
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-generated-function-mockers_test.cc