proxygen: folly::fibers::SimpleLoopController Class Reference
folly::fibers::SimpleLoopController Class Reference
#include <SimpleLoopController.h>
Public Member Functions
SimpleLoopController ()
~SimpleLoopController ()
void setTimeFunc (Function< TimePoint()> timeFunc)
template<typename F >
void loop (F &&func)
void stop ()
int remoteScheduleCalled () const
void runLoop () override
void schedule () override
void timedSchedule (std::function< void()> func, TimePoint time) override
Public Member Functions inherited from folly::fibers::LoopController
virtual ~LoopController ()
virtual void timedSchedule (std::function< void()> func, TimePoint time)=0
Private Member Functions
void setFiberManager (FiberManager *fm) override
void scheduleThreadSafe () override
Private Attributes
FiberManager * fm_
std::atomic< bool > scheduled_ {false}
bool stopRequested_
std::atomic< int > remoteScheduleCalled_ {0}
int remoteLoopRun_ {0}
std::vector< std::pair< TimePoint, std::function< void()> > > scheduledFuncs_
Function< TimePoint()> timeFunc_ {[] { return Clock::now(); }}
Friends
class FiberManager
Additional Inherited Members
Public Types inherited from folly::fibers::LoopController
typedef std::chrono::steady_clock Clock
typedef std::chrono::time_point< Clock > TimePoint
Detailed Description
Definition at line 31 of file SimpleLoopController.h.
Constructor & Destructor Documentation
folly::fibers::SimpleLoopController::SimpleLoopController () inline
Definition at line 33 of file SimpleLoopController.h.
 : fm_(nullptr), stopRequested_(false) {}
folly::fibers::SimpleLoopController::~SimpleLoopController () inline
Definition at line 35 of file SimpleLoopController.h.
References scheduled_.
{
     scheduled_ = false;
   }
Member Function Documentation
template<typename F > void folly::fibers::SimpleLoopController::loop (F && func) inline
Run FiberManager loop; if no ready task are present, run provided function. Stops after both stop() has been called and no waiting tasks remain.
Definition at line 49 of file SimpleLoopController.h.
References folly::gen::first, fm_, folly::fibers::FiberManager::hasTasks(), i, LIKELY, runLoop(), scheduled_, scheduledFuncs_, stopRequested_, folly::swap(), folly::detail::distributed_mutex::time(), and timeFunc_.
Referenced by main().
                       {
     bool waiting = false;
     stopRequested_ = false;
     while (LIKELY(waiting || !stopRequested_)) {
       func();
       auto time = timeFunc_();
       for (size_t i = 0; i < scheduledFuncs_.size(); ++i) {
         if (scheduledFuncs_[i].first <= time) {
           scheduledFuncs_[i].second();
           swap(scheduledFuncs_[i], scheduledFuncs_.back());
           scheduledFuncs_.pop_back();
           --i;
         }
       }
       if (scheduled_) {
         scheduled_ = false;
         runLoop();
         waiting = fm_->hasTasks();
       }
     }
   }
int folly::fibers::SimpleLoopController::remoteScheduleCalled () const inline
Definition at line 82 of file SimpleLoopController.h.
References remoteScheduleCalled_.
{
     return remoteScheduleCalled_;
   }
void folly::fibers::SimpleLoopController::runLoop () inline override virtual
Run FiberManager loopUntilNoReadyImpl(). May have additional logic specific to a LoopController.
Implements folly::fibers::LoopController.
Definition at line 86 of file SimpleLoopController.h.
References fm_, folly::fibers::FiberManager::loopUntilNoReadyImpl(), remoteLoopRun_, remoteScheduleCalled_, and folly::fibers::FiberManager::shouldRunLoopRemote().
Referenced by loop().
{
     do {
       if (remoteLoopRun_ < remoteScheduleCalled_) {
         for (; remoteLoopRun_ < remoteScheduleCalled_; ++remoteLoopRun_) {
           if (fm_->shouldRunLoopRemote()) {
             fm_->loopUntilNoReadyImpl();
           }
         }
       } else {
         fm_->loopUntilNoReadyImpl();
       }
     } while (remoteLoopRun_ < remoteScheduleCalled_);
   }
void folly::fibers::SimpleLoopController::schedule () inline override virtual
Called by FiberManager to schedule the loop function run at some point in the futufre.
Implements folly::fibers::LoopController.
Definition at line 100 of file SimpleLoopController.h.
References scheduled_.
{
     scheduled_ = true;
   }
void folly::fibers::SimpleLoopController::scheduleThreadSafe () inline override private virtual
Same as schedule(), but safe to call from any thread.
Implements folly::fibers::LoopController.
Definition at line 123 of file SimpleLoopController.h.
References remoteScheduleCalled_, and scheduled_.
{
     ++remoteScheduleCalled_;
     scheduled_ = true;
   }
void folly::fibers::SimpleLoopController::setFiberManager (FiberManager *) inline override private virtual
Called by FiberManager to associate itself with the LoopController.
Implements folly::fibers::LoopController.
Definition at line 119 of file SimpleLoopController.h.
{
     fm_ = fm;
   }
void folly::fibers::SimpleLoopController::setTimeFunc (Function< TimePoint()> timeFunc) inline
Definition at line 39 of file SimpleLoopController.h.
References folly::gen::move, and timeFunc_.
{
     timeFunc_ = std::move(timeFunc);
   }
void folly::fibers::SimpleLoopController::stop () inline
Requests exit from loop() as soon as all waiting tasks complete.
Definition at line 78 of file SimpleLoopController.h.
References stopRequested_.
Referenced by Application::loop().
               {
     stopRequested_ = true;
   }
void folly::fibers::SimpleLoopController::timedSchedule (std::function< void()> func, TimePoint time) inline override
Definition at line 104 of file SimpleLoopController.h.
References folly::gen::move, and scheduledFuncs_.
{
     scheduledFuncs_.emplace_back(time, std::move(func));
   }
Friends And Related Function Documentation
friend class FiberManager friend
Definition at line 128 of file SimpleLoopController.h.
Member Data Documentation
FiberManager* folly::fibers::SimpleLoopController::fm_ private
Definition at line 109 of file SimpleLoopController.h.
Referenced by loop(), and runLoop().
int folly::fibers::SimpleLoopController::remoteLoopRun_ {0} private
Definition at line 113 of file SimpleLoopController.h.
Referenced by runLoop().
std::atomic<int> folly::fibers::SimpleLoopController::remoteScheduleCalled_ {0} private
Definition at line 112 of file SimpleLoopController.h.
Referenced by remoteScheduleCalled(), runLoop(), and scheduleThreadSafe().
std::atomic<bool> folly::fibers::SimpleLoopController::scheduled_ {false} private
Definition at line 110 of file SimpleLoopController.h.
Referenced by loop(), schedule(), scheduleThreadSafe(), and ~SimpleLoopController().
std::vector<std::pair<TimePoint, std::function<void()> > > folly::fibers::SimpleLoopController::scheduledFuncs_ private
Definition at line 114 of file SimpleLoopController.h.
Referenced by loop(), and timedSchedule().
bool folly::fibers::SimpleLoopController::stopRequested_ private
Definition at line 111 of file SimpleLoopController.h.
Referenced by loop(), and stop().
Function<TimePoint()> folly::fibers::SimpleLoopController::timeFunc_ {[] { return Clock::now(); }} private
Definition at line 115 of file SimpleLoopController.h.
Referenced by loop(), and setTimeFunc().
The documentation for this class was generated from the following file:
proxygen/folly/folly/fibers/SimpleLoopController.h