proxygen: DataState< Vector > Class Template Reference
DataState< Vector > Class Template Reference
Public Member Functions
DataState (const Vector &v)
~DataState ()
bool operator== (const DataState &o) const
int operator[] (size_type i)
size_type size ()
Private Types
typedef Vector::size_type size_type
Private Attributes
size_type size_
int * data_
Detailed Description
template<class Vector>
class DataState< Vector >
Definition at line 1545 of file StlVectorTest.cpp.
Member Typedef Documentation
template<class Vector> typedef Vector::size_type DataState< Vector >::size_type private
Definition at line 1546 of file StlVectorTest.cpp.
Constructor & Destructor Documentation
template<class Vector> DataState< Vector >::DataState (const Vector & v) inline
Definition at line 1551 of file StlVectorTest.cpp.
References convertToInt(), and i.
{
     size_ = v.size();
     if (size_ != 0) {
       data_ = new int[size_];
       for (size_type i = 0; i < size_; ++i) {
         data_[i] = convertToInt(v.data()[i]);
       }
     } else {
       data_ = nullptr;
     }
   }
template<class Vector> DataState< Vector >::~DataState () inline
Definition at line 1562 of file StlVectorTest.cpp.
References data_.
                {
     delete[] data_;
   }
Member Function Documentation
template<class Vector> bool DataState< Vector >::operator== (const DataState< Vector > & o) const inline
Definition at line 1566 of file StlVectorTest.cpp.
References DataState< Vector >::data_, i, and DataState< Vector >::size_.
{
     if (size_ != o.size_) {
       return false;
     }
     for (size_type i = 0; i < size_; ++i) {
       if (data_[i] != o.data_[i]) {
         return false;
       }
     }
     return true;
   }
template<class Vector> int DataState< Vector >::operator[] (size_type i) inline
Definition at line 1578 of file StlVectorTest.cpp.
References i.
{
     if (i >= size_) {
       cerr << "trying to access DataState out of bounds" << endl;
       exit(1);
     }
     return data_[i];
   }
template<class Vector> size_type DataState< Vector >::size () inline
Definition at line 1586 of file StlVectorTest.cpp.
Referenced by eraseCheck(), insertItCheck(), insertNTCheck(), test_I_emplaceBack3(), test_popBack3(), test_pushBack3(), and test_pushBackRV3().
                    {
     return size_;
   }
Member Data Documentation
template<class Vector> int* DataState< Vector >::data_ private
Definition at line 1548 of file StlVectorTest.cpp.
Referenced by DataState< Vector >::operator==().
template<class Vector> size_type DataState< Vector >::size_ private
Definition at line 1547 of file StlVectorTest.cpp.
Referenced by DataState< Vector >::operator==().
The documentation for this class was generated from the following file:
proxygen/folly/folly/test/stl_tests/StlVectorTest.cpp