proxygen: fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine > Class Template Reference
fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine > Class Template Reference
#include <FizzBase.h>
Public Member Functions
FizzBase (const typename StateMachine::StateType &state, folly::IOBufQueue &transportReadBuf, ActionMoveVisitor &visitor, folly::DelayedDestructionBase *owner)
void writeNewSessionTicket (WriteNewSessionTicket writeNewSessionTicket)
void appWrite (AppWrite appWrite)
void earlyAppWrite (EarlyAppWrite appWrite)
void appClose ()
void waitForData ()
void newTransportData ()
void moveToErrorState (const folly::AsyncSocketException &ex)
bool inErrorState () const
bool actionProcessing () const
Buf getEkm (folly::StringPiece label, const Buf &context, uint16_t length) const
Protected Member Functions
void processActions (typename StateMachine::CompletedActions actions)
void addProcessingActions (typename StateMachine::ProcessingActions actions)
Protected Attributes
StateMachine machine_
const StateMachine::StateType & state_
folly::IOBufQueue & transportReadBuf_
Private Types
using PendingEvent = boost::variant< AppWrite, EarlyAppWrite, AppClose, WriteNewSessionTicket >
Private Member Functions
void processPendingEvents ()
Private Attributes
ActionMoveVisitor & visitor_
folly::DelayedDestructionBase * owner_
std::deque< PendingEvent > pendingEvents_
bool waitForData_ {true}
folly::Optional< folly::DelayedDestruction::DestructorGuard > actionGuard_
bool inProcessPendingEvents_ {false}
bool inErrorState_ {false}
Detailed Description
template<typename Derived, typename ActionMoveVisitor, typename StateMachine>
class fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >
FizzBase defines an async method of communicating with the fizz state machine. Given a const reference to state, and a reference to transportReadBuf, FizzBase will consume the transportReadBuf and process events as applicable. visitor is variant visitor that is expected to process Actions as they are received. A DestructorGuard on owner will be taken when async actions are in flight, during which time this class must not be deleted.
Definition at line 26 of file FizzBase.h.
Member Typedef Documentation
template<typename Derived, typename ActionMoveVisitor, typename StateMachine> using fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::PendingEvent = boost::variant<AppWrite, EarlyAppWrite, AppClose, WriteNewSessionTicket> private
Definition at line 112 of file FizzBase.h.
Constructor & Destructor Documentation
template<typename Derived, typename ActionMoveVisitor, typename StateMachine> fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::FizzBase (const typename StateMachine::StateType & state, folly::IOBufQueue & transportReadBuf, ActionMoveVisitor & visitor, folly::DelayedDestructionBase * owner) inline
Definition at line 28 of file FizzBase.h.
       : state_(state),
         transportReadBuf_(transportReadBuf),
         visitor_(visitor),
         owner_(owner) {}
Member Function Documentation
template<typename Derived , typename ActionMoveVisitor , typename StateMachine > bool fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::actionProcessing () const
Returns true if the state machine is actively processing an event or action.
Definition at line 81 of file FizzBase-inl.h.
Referenced by fizz::FizzBase< FizzServer< ActionMoveVisitor, SM >, ActionMoveVisitor, SM >::FizzBase().
           {
   return actionGuard_.hasValue();
 }
template<typename Derived , typename ActionMoveVisitor , typename StateMachine> void fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::addProcessingActions (typename StateMachine::ProcessingActions actions) protected
Definition at line 102 of file FizzBase-inl.h.
References folly::gen::move, and fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::processPendingEvents().
Referenced by fizz::FizzBase< FizzServer< ActionMoveVisitor, SM >, ActionMoveVisitor, SM >::FizzBase().
{
   if (actionGuard_) {
     throw std::runtime_error("actions already processing");
   }
   actionGuard_ = folly::DelayedDestruction::DestructorGuard(owner_);
   static_cast<Derived*>(this)->startActions(std::move(actions));
 }
template<typename Derived , typename ActionMoveVisitor , typename StateMachine > void fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::appClose ()
Called when the application wants to close the connection.
Definition at line 34 of file FizzBase-inl.h.
Referenced by fizz::FizzBase< FizzServer< ActionMoveVisitor, SM >, ActionMoveVisitor, SM >::FizzBase().
{
   pendingEvents_.push_back(AppClose());
   processPendingEvents();
 }
template<typename Derived , typename ActionMoveVisitor , typename StateMachine > void fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::appWrite (AppWrite appWrite)
Called to write application data.
Definition at line 21 of file FizzBase-inl.h.
References folly::gen::move.
Referenced by fizz::FizzBase< FizzServer< ActionMoveVisitor, SM >, ActionMoveVisitor, SM >::FizzBase().
{
   pendingEvents_.push_back(std::move(w));
   processPendingEvents();
 }
template<typename Derived , typename ActionMoveVisitor , typename StateMachine > void fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::earlyAppWrite (EarlyAppWrite appWrite)
Called to write early application data.
Definition at line 27 of file FizzBase-inl.h.
References folly::gen::move.
Referenced by fizz::FizzBase< FizzServer< ActionMoveVisitor, SM >, ActionMoveVisitor, SM >::FizzBase().
                      {
   pendingEvents_.push_back(std::move(w));
   processPendingEvents();
 }
template<typename Derived , typename ActionMoveVisitor , typename StateMachine > Buf fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::getEkm (folly::StringPiece label, const Buf & context, uint16_t length) const
Returns an exported key material derived from the 1-RTT secret of the TLS connection.
Definition at line 159 of file FizzBase-inl.h.
References fizz::Exporter::getEkm(), and fizz::test::label.
Referenced by fizz::FizzBase< FizzServer< ActionMoveVisitor, SM >, ActionMoveVisitor, SM >::FizzBase().
{
   return Exporter::getEkm(
       *state_.cipher(),
       (*state_.exporterMasterSecret())->coalesce(),
       label,
       context ? context->clone() : nullptr,
       length);
 }
template<typename Derived , typename ActionMoveVisitor , typename StateMachine > bool fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::inErrorState () const
Returns true if in error state where no further events will be processed.
Definition at line 76 of file FizzBase-inl.h.
Referenced by fizz::FizzBase< FizzServer< ActionMoveVisitor, SM >, ActionMoveVisitor, SM >::FizzBase().
{
   return inErrorState_ || state_.state() == decltype(state_.state())::Error;
 }
template<typename Derived , typename ActionMoveVisitor , typename StateMachine > void fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::moveToErrorState (const folly::AsyncSocketException & ex)
Calls error callbacks on any pending events and prevents any further events from being processed. Should be called when an error is received from either the state machine or the transport that will cause the connection to abort. Note that this does not stop a currently processing event.
Definition at line 51 of file FizzBase-inl.h.
References fizz::AppWrite::callback, folly::gen::move, folly::variant_match(), fizz::detail::write(), and folly::AsyncWriter::WriteCallback::writeErr().
Referenced by fizz::FizzBase< FizzServer< ActionMoveVisitor, SM >, ActionMoveVisitor, SM >::FizzBase().
{
   // We use a separate flag here rather than just moving the state to Error
   // since there may be a currently processing action.
   inErrorState_ = true;
   while (!pendingEvents_.empty()) {
     auto event = std::move(pendingEvents_.front());
     pendingEvents_.pop_front();
     folly::variant_match(
         event,
         [&ex](AppWrite& write) {
           if (write.callback) {
             write.callback->writeErr(0, ex);
           }
         },
         [&ex](EarlyAppWrite& write) {
           if (write.callback) {
             write.callback->writeErr(0, ex);
           }
         },
         [](auto&) {});
   }
 }
template<typename Derived , typename ActionMoveVisitor , typename StateMachine > void fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::newTransportData ()
Called to notify that new transport data is available in transportReadBuf.
Definition at line 45 of file FizzBase-inl.h.
Referenced by fizz::FizzBase< FizzServer< ActionMoveVisitor, SM >, ActionMoveVisitor, SM >::FizzBase().
{
   waitForData_ = false;
   processPendingEvents();
 }
template<typename Derived , typename ActionMoveVisitor , typename StateMachine> void fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::processActions (typename StateMachine::CompletedActions actions) protected
Definition at line 87 of file FizzBase-inl.h.
References upload::action, and folly::apply_visitor().
Referenced by fizz::FizzBase< FizzServer< ActionMoveVisitor, SM >, ActionMoveVisitor, SM >::FizzBase(), and fizz::server::FizzServer< ActionMoveVisitor, SM >::startActions().
{
   // This extra DestructorGuard is needed due to the gap between clearing
   // actionGuard_ and potentially processing another action.
   folly::DelayedDestruction::DestructorGuard dg(owner_);
   for (auto& action : actions) {
     boost::apply_visitor(visitor_, action);
   }
   actionGuard_.clear();
   processPendingEvents();
 }
template<typename Derived , typename ActionMoveVisitor , typename StateMachine > void fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::processPendingEvents () private
Definition at line 115 of file FizzBase-inl.h.
References fizz::client::detail::actions(), folly::gen::move, SCOPE_EXIT, folly::variant_match(), and fizz::detail::write().
Referenced by fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::addProcessingActions().
{
   if (inProcessPendingEvents_) {
     return;
   }
   folly::DelayedDestruction::DestructorGuard dg(owner_);
   inProcessPendingEvents_ = true;
   SCOPE_EXIT {
     inProcessPendingEvents_ = false;
   };
   while (!actionGuard_ && !inErrorState()) {
     folly::Optional<typename StateMachine::ProcessingActions> actions;
     actionGuard_ = folly::DelayedDestruction::DestructorGuard(owner_);
     if (!waitForData_) {
       actions = machine_.processSocketData(state_, transportReadBuf_);
     } else if (!pendingEvents_.empty()) {
       auto event = std::move(pendingEvents_.front());
       pendingEvents_.pop_front();
       folly::variant_match(
           event,
           [&actions, this](WriteNewSessionTicket& write) {
             actions =
                 machine_.processWriteNewSessionTicket(state_, std::move(write));
           },
           [&actions, this](AppWrite& write) {
             actions = machine_.processAppWrite(state_, std::move(write));
           },
           [&actions, this](EarlyAppWrite& write) {
             actions = machine_.processEarlyAppWrite(state_, std::move(write));
           },
           [&actions, this](AppClose&) {
             actions = machine_.processAppClose(state_);
           });
     } else {
       actionGuard_.clear();
       return;
     }
     static_cast<Derived*>(this)->startActions(std::move(*actions));
   }
 }
template<typename Derived , typename ActionMoveVisitor , typename StateMachine > void fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::waitForData ()
Called to pause processing of transportReadBuf until new data is available.
Call newTransportData() to resume processing.
Definition at line 40 of file FizzBase-inl.h.
Referenced by fizz::FizzBase< FizzServer< ActionMoveVisitor, SM >, ActionMoveVisitor, SM >::FizzBase().
{
   waitForData_ = true;
 }
template<typename Derived , typename ActionMoveVisitor , typename StateMachine > void fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::writeNewSessionTicket (WriteNewSessionTicket writeNewSessionTicket)
Server only: Called to write new session ticket to client.
Definition at line 14 of file FizzBase-inl.h.
References folly::gen::move.
Referenced by fizz::FizzBase< FizzServer< ActionMoveVisitor, SM >, ActionMoveVisitor, SM >::FizzBase().
{
   pendingEvents_.push_back(std::move(w));
   processPendingEvents();
 }
Member Data Documentation
template<typename Derived, typename ActionMoveVisitor, typename StateMachine> folly::Optional<folly::DelayedDestruction::DestructorGuard> fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::actionGuard_ private
Definition at line 115 of file FizzBase.h.
template<typename Derived, typename ActionMoveVisitor, typename StateMachine> bool fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::inErrorState_ {false} private
Definition at line 117 of file FizzBase.h.
template<typename Derived, typename ActionMoveVisitor, typename StateMachine> bool fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::inProcessPendingEvents_ {false} private
Definition at line 116 of file FizzBase.h.
template<typename Derived, typename ActionMoveVisitor, typename StateMachine> StateMachine fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::machine_ protected
Definition at line 101 of file FizzBase.h.
template<typename Derived, typename ActionMoveVisitor, typename StateMachine> folly::DelayedDestructionBase* fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::owner_ private
Definition at line 109 of file FizzBase.h.
template<typename Derived, typename ActionMoveVisitor, typename StateMachine> std::deque<PendingEvent> fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::pendingEvents_ private
Definition at line 113 of file FizzBase.h.
template<typename Derived, typename ActionMoveVisitor, typename StateMachine> const StateMachine::StateType& fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::state_ protected
Definition at line 102 of file FizzBase.h.
template<typename Derived, typename ActionMoveVisitor, typename StateMachine> folly::IOBufQueue& fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::transportReadBuf_ protected
Definition at line 103 of file FizzBase.h.
template<typename Derived, typename ActionMoveVisitor, typename StateMachine> ActionMoveVisitor& fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::visitor_ private
Definition at line 108 of file FizzBase.h.
template<typename Derived, typename ActionMoveVisitor, typename StateMachine> bool fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::waitForData_ {true} private
Definition at line 114 of file FizzBase.h.
The documentation for this class was generated from the following files:
proxygen/fizz/fizz/protocol/FizzBase.h
proxygen/fizz/fizz/protocol/FizzBase-inl.h