proxygen: folly::HandshakeCallback Class Reference
folly::HandshakeCallback Class Reference
#include <AsyncSSLSocketTest.h>
Public Types
enum ExpectType { EXPECT_SUCCESS, EXPECT_ERROR }
Public Member Functions
HandshakeCallback (ReadCallbackBase *rcb, ExpectType expect=EXPECT_SUCCESS)
void setSocket (const std::shared_ptr< AsyncSSLSocket > &socket)
void setState (StateEnum s)
void handshakeSuc (AsyncSSLSocket *sock) noexceptoverride
void handshakeErr (AsyncSSLSocket *, const AsyncSocketException &ex) noexceptoverride
void waitForHandshake ()
~HandshakeCallback () override
void closeSocket ()
std::shared_ptr< AsyncSSLSocket > getSocket ()
Public Member Functions inherited from folly::AsyncSSLSocket::HandshakeCB
virtual ~HandshakeCB ()=default
virtual bool handshakeVer (AsyncSSLSocket *, bool preverifyOk, X509_STORE_CTX *) noexcept
Public Attributes
StateEnum state
std::shared_ptr< AsyncSSLSocket > socket_
ReadCallbackBase * rcb_
ExpectType expect_
std::mutex mutex_
std::condition_variable cv_
std::string errorString_
Detailed Description
Definition at line 478 of file AsyncSSLSocketTest.h.
Member Enumeration Documentation
enum folly::HandshakeCallback::ExpectType
Enumerator
EXPECT_SUCCESS
EXPECT_ERROR
Definition at line 480 of file AsyncSSLSocketTest.h.
 { EXPECT_SUCCESS, EXPECT_ERROR };
Constructor & Destructor Documentation
folly::HandshakeCallback::HandshakeCallback (ReadCallbackBase * rcb, ExpectType expect = EXPECT_SUCCESS) inline explicit
Definition at line 482 of file AsyncSSLSocketTest.h.
       : state(STATE_WAITING), rcb_(rcb), expect_(expect) {}
folly::HandshakeCallback::~HandshakeCallback () inline override
Definition at line 525 of file AsyncSSLSocketTest.h.
References EXPECT_EQ, and folly::STATE_SUCCEEDED.
{
     EXPECT_EQ(STATE_SUCCEEDED, state);
   }
Member Function Documentation
void folly::HandshakeCallback::closeSocket () inline
Definition at line 529 of file AsyncSSLSocketTest.h.
References folly::SendMsgParamsCallbackBase::socket_, and folly::STATE_SUCCEEDED.
Referenced by folly::TEST().
                      {
     socket_->close();
     state = STATE_SUCCEEDED;
   }
std::shared_ptr<AsyncSSLSocket> folly::HandshakeCallback::getSocket () inline
Definition at line 534 of file AsyncSSLSocketTest.h.
References folly::SendMsgParamsCallbackBase::socket_.
Referenced by folly::TEST().
{
     return socket_;
   }
void folly::HandshakeCallback::handshakeErr (AsyncSSLSocket * sock, const AsyncSocketException & ex) inline override virtual noexcept
handshakeErr() is called if an error occurs while establishing the SSL connection.
The HandshakeCB will be uninstalled before handshakeErr() is called.
Parameters
sock SSL socket on which the handshake was initiated
ex An exception representing the error.
Implements folly::AsyncSSLSocket::HandshakeCB.
Definition at line 506 of file AsyncSSLSocketTest.h.
References cv_, g(), mutex_, folly::STATE_FAILED, and folly::STATE_SUCCEEDED.
{
     std::lock_guard<std::mutex> g(mutex_);
     cv_.notify_all();
     std::cerr << "HandshakeCallback::handshakeError " << ex.what() << std::endl;
     state = (expect_ == EXPECT_ERROR) ? STATE_SUCCEEDED : STATE_FAILED;
     if (expect_ == EXPECT_ERROR) {
       // rcb will never be invoked
       rcb_->setState(STATE_SUCCEEDED);
     }
     errorString_ = ex.what();
   }
void folly::HandshakeCallback::handshakeSuc (AsyncSSLSocket * sock) inline override virtual noexcept
handshakeSuc() is called when a new SSL connection is established, i.e., after SSL_accept/connect() returns successfully.
The HandshakeCB will be uninstalled before handshakeSuc() is called.
Parameters
sock SSL socket on which the handshake was initiated
Implements folly::AsyncSSLSocket::HandshakeCB.
Definition at line 497 of file AsyncSSLSocketTest.h.
References cv_, EXPECT_EQ, g(), mutex_, folly::SendMsgParamsCallbackBase::socket_, folly::STATE_FAILED, and folly::STATE_SUCCEEDED.
{
     std::lock_guard<std::mutex> g(mutex_);
     cv_.notify_all();
     EXPECT_EQ(sock, socket_.get());
     std::cerr << "HandshakeCallback::connectionAccepted" << std::endl;
     rcb_->setSocket(socket_);
     sock->setReadCB(rcb_);
     state = (expect_ == EXPECT_SUCCESS) ? STATE_SUCCEEDED : STATE_FAILED;
   }
void folly::HandshakeCallback::setSocket (const std::shared_ptr< AsyncSSLSocket > & socket) inline
Definition at line 487 of file AsyncSSLSocketTest.h.
References folly::netops::socket(), and folly::SendMsgParamsCallbackBase::socket_.
{
     socket_ = socket;
   }
void folly::HandshakeCallback::setState (StateEnum s) inline
Definition at line 491 of file AsyncSSLSocketTest.h.
References s.
{
     state = s;
     rcb_->setState(s);
   }
void folly::HandshakeCallback::waitForHandshake () inline
Definition at line 520 of file AsyncSSLSocketTest.h.
References cv_, folly::lock(), mutex_, and folly::STATE_WAITING.
Referenced by folly::TEST().
{
     std::unique_lock<std::mutex> lock(mutex_);
     cv_.wait(lock, [this] { return state != STATE_WAITING; });
   }
Member Data Documentation
std::condition_variable folly::HandshakeCallback::cv_
Definition at line 543 of file AsyncSSLSocketTest.h.
std::string folly::HandshakeCallback::errorString_
Definition at line 544 of file AsyncSSLSocketTest.h.
Referenced by folly::TEST().
ExpectType folly::HandshakeCallback::expect_
Definition at line 541 of file AsyncSSLSocketTest.h.
std::mutex folly::HandshakeCallback::mutex_
Definition at line 542 of file AsyncSSLSocketTest.h.
ReadCallbackBase* folly::HandshakeCallback::rcb_
Definition at line 540 of file AsyncSSLSocketTest.h.
std::shared_ptr<AsyncSSLSocket> folly::HandshakeCallback::socket_
Definition at line 539 of file AsyncSSLSocketTest.h.
StateEnum folly::HandshakeCallback::state
Definition at line 538 of file AsyncSSLSocketTest.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/io/async/test/AsyncSSLSocketTest.h