proxygen: gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest Class Reference
gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest Class Reference
Public Member Functions
def RunAndVerify (self, env_var_value, flag_value, expect_seg_fault)
def testDefaultBehavior (self)
def testEnvVar (self)
def testFlag (self)
def testFlagOverridesEnvVar (self)
def testBreakOnFailureOverridesThrowOnFailure (self)
def testCatchExceptionsDoesNotInterfere (self)
def RunAndVerify (self, env_var_value, flag_value, expect_seg_fault)
def testDefaultBehavior (self)
def testEnvVar (self)
def testFlag (self)
def testFlagOverridesEnvVar (self)
def testBreakOnFailureOverridesThrowOnFailure (self)
def testCatchExceptionsDoesNotInterfere (self)
def RunAndVerify (self, env_var_value, flag_value, expect_seg_fault)
def testDefaultBehavior (self)
def testEnvVar (self)
def testFlag (self)
def testFlagOverridesEnvVar (self)
def testBreakOnFailureOverridesThrowOnFailure (self)
def testCatchExceptionsDoesNotInterfere (self)
Detailed Description
Tests using the GTEST_BREAK_ON_FAILURE environment variable or
the --gtest_break_on_failure flag to turn assertion failures into
segmentation faults.
Definition at line 93 of file gtest_break_on_failure_unittest.py.
Member Function Documentation
def gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.RunAndVerify (self, env_var_value, flag_value, expect_seg_fault)
Runs gtest_break_on_failure_unittest_ and verifies that it does
(or does not) have a seg-fault.
Args:
  env_var_value:    value of the GTEST_BREAK_ON_FAILURE environment
                variable; None if the variable should be unset.
  flag_value:       value of the --gtest_break_on_failure flag;
                None if the flag should not be present.
  expect_seg_fault: 1 if the program is expected to generate a seg-fault;
                0 otherwise.
Definition at line 99 of file gtest_break_on_failure_unittest.py.
References join, gtest_break_on_failure_unittest.Run(), and gtest_break_on_failure_unittest.SetEnvVar.
Referenced by gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.RunAndVerify(), gtest_filter_unittest.GTestFilterUnitTest.testBadFilter(), gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testBreakOnFailureOverridesThrowOnFailure(), gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testCatchExceptionsDoesNotInterfere(), gtest_throw_on_failure_test.ThrowOnFailureTest.testDefaultBehavior(), gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testDefaultBehavior(), gtest_list_tests_unittest.GTestListTestsUnitTest.testDefaultBehavior(), gtest_filter_unittest.GTestFilterUnitTest.testDefaultBehavior(), gtest_filter_unittest.GTestFilterUnitTest.testEmptyFilter(), gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testEnvVar(), gtest_filter_unittest.GTestFilterUnitTest.testFilterByTest(), gtest_filter_unittest.GTestFilterUnitTest.testFilterByTestCase(), gtest_filter_unittest.GTestFilterUnitTest.testFilterDisabledTests(), gtest_filter_unittest.GTestFilterUnitTest.testFilterWithoutDot(), gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testFlag(), gtest_list_tests_unittest.GTestListTestsUnitTest.testFlag(), gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testFlagOverridesEnvVar(), gtest_filter_unittest.GTestFilterUnitTest.testFullName(), gtest_filter_unittest.GTestFilterUnitTest.testNegativeFilters(), gtest_list_tests_unittest.GTestListTestsUnitTest.testOverrideNonFilterFlags(), gtest_filter_unittest.GTestFilterUnitTest.testThreePatterns(), gtest_throw_on_failure_test.ThrowOnFailureTest.testThrowOnFailureEnvVar(), gtest_throw_on_failure_test.ThrowOnFailureTest.testThrowOnFailureFlag(), gtest_throw_on_failure_test.ThrowOnFailureTest.testThrowOnFailureFlagOverridesEnvVar(), gtest_filter_unittest.GTestFilterUnitTest.testTwoPatterns(), gtest_filter_unittest.GTestFilterUnitTest.testUniversalFilters(), gtest_filter_unittest.GTestFilterUnitTest.testWildcardInTestCaseName(), gtest_filter_unittest.GTestFilterUnitTest.testWildcardInTestName(), and gtest_list_tests_unittest.GTestListTestsUnitTest.testWithFilterFlags().
   def RunAndVerify(self, env_var_value, flag_value, expect_seg_fault):
     """Runs gtest_break_on_failure_unittest_ and verifies that it does
     (or does not) have a seg-fault.
     Args:
       env_var_value:    value of the GTEST_BREAK_ON_FAILURE environment
                         variable; None if the variable should be unset.
       flag_value:       value of the --gtest_break_on_failure flag;
                         None if the flag should not be present.
       expect_seg_fault: 1 if the program is expected to generate a seg-fault;
                         0 otherwise.
     """
     SetEnvVar(BREAK_ON_FAILURE_ENV_VAR, env_var_value)
     if env_var_value is None:
       env_var_value_msg = ' is not set'
     else:
       env_var_value_msg = '=' + env_var_value
     if flag_value is None:
       flag = ''
     elif flag_value == '0':
       flag = '--%s=0' % BREAK_ON_FAILURE_FLAG
     else:
       flag = '--%s' % BREAK_ON_FAILURE_FLAG
     command = [EXE_PATH]
     if flag:
       command.append(flag)
     if expect_seg_fault:
       should_or_not = 'should'
     else:
       should_or_not = 'should not'
     has_seg_fault = Run(command)
     SetEnvVar(BREAK_ON_FAILURE_ENV_VAR, None)
     msg = ('when %s%s, an assertion failure in "%s" %s cause a seg-fault.' %
            (BREAK_ON_FAILURE_ENV_VAR, env_var_value_msg, ' '.join(command),
             should_or_not))
     self.assert_(has_seg_fault == expect_seg_fault, msg)
def gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.RunAndVerify (self, env_var_value, flag_value, expect_seg_fault)
Runs gtest_break_on_failure_unittest_ and verifies that it does
(or does not) have a seg-fault.
Args:
  env_var_value:    value of the GTEST_BREAK_ON_FAILURE environment
                variable; None if the variable should be unset.
  flag_value:       value of the --gtest_break_on_failure flag;
                None if the flag should not be present.
  expect_seg_fault: 1 if the program is expected to generate a seg-fault;
                0 otherwise.
Definition at line 99 of file gtest_break_on_failure_unittest.py.
References join, gtest_break_on_failure_unittest.Run(), gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.RunAndVerify(), and gtest_break_on_failure_unittest.SetEnvVar.
   def RunAndVerify(self, env_var_value, flag_value, expect_seg_fault):
     """Runs gtest_break_on_failure_unittest_ and verifies that it does
     (or does not) have a seg-fault.
     Args:
       env_var_value:    value of the GTEST_BREAK_ON_FAILURE environment
                         variable; None if the variable should be unset.
       flag_value:       value of the --gtest_break_on_failure flag;
                         None if the flag should not be present.
       expect_seg_fault: 1 if the program is expected to generate a seg-fault;
                         0 otherwise.
     """
     SetEnvVar(BREAK_ON_FAILURE_ENV_VAR, env_var_value)
     if env_var_value is None:
       env_var_value_msg = ' is not set'
     else:
       env_var_value_msg = '=' + env_var_value
     if flag_value is None:
       flag = ''
     elif flag_value == '0':
       flag = '--%s=0' % BREAK_ON_FAILURE_FLAG
     else:
       flag = '--%s' % BREAK_ON_FAILURE_FLAG
     command = [EXE_PATH]
     if flag:
       command.append(flag)
     if expect_seg_fault:
       should_or_not = 'should'
     else:
       should_or_not = 'should not'
     has_seg_fault = Run(command)
     SetEnvVar(BREAK_ON_FAILURE_ENV_VAR, None)
     msg = ('when %s%s, an assertion failure in "%s" %s cause a seg-fault.' %
            (BREAK_ON_FAILURE_ENV_VAR, env_var_value_msg, ' '.join(command),
             should_or_not))
     self.assert_(has_seg_fault == expect_seg_fault, msg)
def gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.RunAndVerify (self, env_var_value, flag_value, expect_seg_fault)
Runs gtest_break_on_failure_unittest_ and verifies that it does
(or does not) have a seg-fault.
Args:
  env_var_value:    value of the GTEST_BREAK_ON_FAILURE environment
                variable; None if the variable should be unset.
  flag_value:       value of the --gtest_break_on_failure flag;
                None if the flag should not be present.
  expect_seg_fault: 1 if the program is expected to generate a seg-fault;
                0 otherwise.
Definition at line 99 of file gtest_break_on_failure_unittest.py.
References join, gtest_break_on_failure_unittest.Run(), gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.RunAndVerify(), and gtest_break_on_failure_unittest.SetEnvVar.
   def RunAndVerify(self, env_var_value, flag_value, expect_seg_fault):
     """Runs gtest_break_on_failure_unittest_ and verifies that it does
     (or does not) have a seg-fault.
     Args:
       env_var_value:    value of the GTEST_BREAK_ON_FAILURE environment
                         variable; None if the variable should be unset.
       flag_value:       value of the --gtest_break_on_failure flag;
                         None if the flag should not be present.
       expect_seg_fault: 1 if the program is expected to generate a seg-fault;
                         0 otherwise.
     """
     SetEnvVar(BREAK_ON_FAILURE_ENV_VAR, env_var_value)
     if env_var_value is None:
       env_var_value_msg = ' is not set'
     else:
       env_var_value_msg = '=' + env_var_value
     if flag_value is None:
       flag = ''
     elif flag_value == '0':
       flag = '--%s=0' % BREAK_ON_FAILURE_FLAG
     else:
       flag = '--%s' % BREAK_ON_FAILURE_FLAG
     command = [EXE_PATH]
     if flag:
       command.append(flag)
     if expect_seg_fault:
       should_or_not = 'should'
     else:
       should_or_not = 'should not'
     has_seg_fault = Run(command)
     SetEnvVar(BREAK_ON_FAILURE_ENV_VAR, None)
     msg = ('when %s%s, an assertion failure in "%s" %s cause a seg-fault.' %
            (BREAK_ON_FAILURE_ENV_VAR, env_var_value_msg, ' '.join(command),
             should_or_not))
     self.assert_(has_seg_fault == expect_seg_fault, msg)
def gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testBreakOnFailureOverridesThrowOnFailure (self)
Tests that gtest_break_on_failure overrides gtest_throw_on_failure.
Definition at line 187 of file gtest_break_on_failure_unittest.py.
References gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.RunAndVerify(), gtest_break_on_failure_unittest.SetEnvVar, and gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testBreakOnFailureOverridesThrowOnFailure().
   def testBreakOnFailureOverridesThrowOnFailure(self):
     """Tests that gtest_break_on_failure overrides gtest_throw_on_failure."""
     SetEnvVar(THROW_ON_FAILURE_ENV_VAR, '1')
     try:
       self.RunAndVerify(env_var_value=None,
                         flag_value='1',
                         expect_seg_fault=1)
     finally:
       SetEnvVar(THROW_ON_FAILURE_ENV_VAR, None)
def gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testBreakOnFailureOverridesThrowOnFailure (self)
Tests that gtest_break_on_failure overrides gtest_throw_on_failure.
Definition at line 187 of file gtest_break_on_failure_unittest.py.
References gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.RunAndVerify(), gtest_break_on_failure_unittest.SetEnvVar, and gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testBreakOnFailureOverridesThrowOnFailure().
   def testBreakOnFailureOverridesThrowOnFailure(self):
     """Tests that gtest_break_on_failure overrides gtest_throw_on_failure."""
     SetEnvVar(THROW_ON_FAILURE_ENV_VAR, '1')
     try:
       self.RunAndVerify(env_var_value=None,
                         flag_value='1',
                         expect_seg_fault=1)
     finally:
       SetEnvVar(THROW_ON_FAILURE_ENV_VAR, None)
def gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testBreakOnFailureOverridesThrowOnFailure (self)
Tests that gtest_break_on_failure overrides gtest_throw_on_failure.
Definition at line 187 of file gtest_break_on_failure_unittest.py.
References gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.RunAndVerify(), and gtest_break_on_failure_unittest.SetEnvVar.
Referenced by gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testBreakOnFailureOverridesThrowOnFailure().
   def testBreakOnFailureOverridesThrowOnFailure(self):
     """Tests that gtest_break_on_failure overrides gtest_throw_on_failure."""
     SetEnvVar(THROW_ON_FAILURE_ENV_VAR, '1')
     try:
       self.RunAndVerify(env_var_value=None,
                         flag_value='1',
                         expect_seg_fault=1)
     finally:
       SetEnvVar(THROW_ON_FAILURE_ENV_VAR, None)
def gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testCatchExceptionsDoesNotInterfere (self)
Tests that gtest_catch_exceptions doesn't interfere.
Definition at line 199 of file gtest_break_on_failure_unittest.py.
References gtest_test_utils.Main(), gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.RunAndVerify(), gtest_break_on_failure_unittest.SetEnvVar, and gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testCatchExceptionsDoesNotInterfere().
     def testCatchExceptionsDoesNotInterfere(self):
       """Tests that gtest_catch_exceptions doesn't interfere."""
       SetEnvVar(CATCH_EXCEPTIONS_ENV_VAR, '1')
       try:
         self.RunAndVerify(env_var_value='1',
                           flag_value='1',
                           expect_seg_fault=1)
       finally:
         SetEnvVar(CATCH_EXCEPTIONS_ENV_VAR, None)
def gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testCatchExceptionsDoesNotInterfere (self)
Tests that gtest_catch_exceptions doesn't interfere.
Definition at line 199 of file gtest_break_on_failure_unittest.py.
References gtest_test_utils.Main(), gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.RunAndVerify(), gtest_break_on_failure_unittest.SetEnvVar, and gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testCatchExceptionsDoesNotInterfere().
     def testCatchExceptionsDoesNotInterfere(self):
       """Tests that gtest_catch_exceptions doesn't interfere."""
       SetEnvVar(CATCH_EXCEPTIONS_ENV_VAR, '1')
       try:
         self.RunAndVerify(env_var_value='1',
                           flag_value='1',
                           expect_seg_fault=1)
       finally:
         SetEnvVar(CATCH_EXCEPTIONS_ENV_VAR, None)
def gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testCatchExceptionsDoesNotInterfere (self)
Tests that gtest_catch_exceptions doesn't interfere.
Definition at line 199 of file gtest_break_on_failure_unittest.py.
References gtest_test_utils.Main(), gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.RunAndVerify(), and gtest_break_on_failure_unittest.SetEnvVar.
Referenced by gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testCatchExceptionsDoesNotInterfere().
     def testCatchExceptionsDoesNotInterfere(self):
       """Tests that gtest_catch_exceptions doesn't interfere."""
       SetEnvVar(CATCH_EXCEPTIONS_ENV_VAR, '1')
       try:
         self.RunAndVerify(env_var_value='1',
                           flag_value='1',
                           expect_seg_fault=1)
       finally:
         SetEnvVar(CATCH_EXCEPTIONS_ENV_VAR, None)
def gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testDefaultBehavior (self)
Tests the behavior of the default mode.
Definition at line 144 of file gtest_break_on_failure_unittest.py.
References gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.RunAndVerify().
Referenced by gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testDefaultBehavior().
   def testDefaultBehavior(self):
     """Tests the behavior of the default mode."""
     self.RunAndVerify(env_var_value=None,
                       flag_value=None,
                       expect_seg_fault=0)
def gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testDefaultBehavior (self)
Tests the behavior of the default mode.
Definition at line 144 of file gtest_break_on_failure_unittest.py.
References gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.RunAndVerify(), and gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testDefaultBehavior().
   def testDefaultBehavior(self):
     """Tests the behavior of the default mode."""
     self.RunAndVerify(env_var_value=None,
                       flag_value=None,
                       expect_seg_fault=0)
def gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testDefaultBehavior (self)
Tests the behavior of the default mode.
Definition at line 144 of file gtest_break_on_failure_unittest.py.
References gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.RunAndVerify(), and gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testDefaultBehavior().
   def testDefaultBehavior(self):
     """Tests the behavior of the default mode."""
     self.RunAndVerify(env_var_value=None,
                       flag_value=None,
                       expect_seg_fault=0)
def gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testEnvVar (self)
Tests using the GTEST_BREAK_ON_FAILURE environment variable.
Definition at line 151 of file gtest_break_on_failure_unittest.py.
References gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.RunAndVerify(), and gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testEnvVar().
   def testEnvVar(self):
     """Tests using the GTEST_BREAK_ON_FAILURE environment variable."""
     self.RunAndVerify(env_var_value='0',
                       flag_value=None,
                       expect_seg_fault=0)
     self.RunAndVerify(env_var_value='1',
                       flag_value=None,
                       expect_seg_fault=1)
def gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testEnvVar (self)
Tests using the GTEST_BREAK_ON_FAILURE environment variable.
Definition at line 151 of file gtest_break_on_failure_unittest.py.
References gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.RunAndVerify().
Referenced by gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testEnvVar().
   def testEnvVar(self):
     """Tests using the GTEST_BREAK_ON_FAILURE environment variable."""
     self.RunAndVerify(env_var_value='0',
                       flag_value=None,
                       expect_seg_fault=0)
     self.RunAndVerify(env_var_value='1',
                       flag_value=None,
                       expect_seg_fault=1)
def gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testEnvVar (self)
Tests using the GTEST_BREAK_ON_FAILURE environment variable.
Definition at line 151 of file gtest_break_on_failure_unittest.py.
References gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.RunAndVerify(), and gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testEnvVar().
   def testEnvVar(self):
     """Tests using the GTEST_BREAK_ON_FAILURE environment variable."""
     self.RunAndVerify(env_var_value='0',
                       flag_value=None,
                       expect_seg_fault=0)
     self.RunAndVerify(env_var_value='1',
                       flag_value=None,
                       expect_seg_fault=1)
def gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testFlag (self)
Tests using the --gtest_break_on_failure flag.
Definition at line 161 of file gtest_break_on_failure_unittest.py.
References gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.RunAndVerify().
Referenced by gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testFlag().
   def testFlag(self):
     """Tests using the --gtest_break_on_failure flag."""
     self.RunAndVerify(env_var_value=None,
                       flag_value='0',
                       expect_seg_fault=0)
     self.RunAndVerify(env_var_value=None,
                       flag_value='1',
                       expect_seg_fault=1)
def gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testFlag (self)
Tests using the --gtest_break_on_failure flag.
Definition at line 161 of file gtest_break_on_failure_unittest.py.
References gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.RunAndVerify(), and gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testFlag().
   def testFlag(self):
     """Tests using the --gtest_break_on_failure flag."""
     self.RunAndVerify(env_var_value=None,
                       flag_value='0',
                       expect_seg_fault=0)
     self.RunAndVerify(env_var_value=None,
                       flag_value='1',
                       expect_seg_fault=1)
def gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testFlag (self)
Tests using the --gtest_break_on_failure flag.
Definition at line 161 of file gtest_break_on_failure_unittest.py.
References gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.RunAndVerify(), and gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testFlag().
   def testFlag(self):
     """Tests using the --gtest_break_on_failure flag."""
     self.RunAndVerify(env_var_value=None,
                       flag_value='0',
                       expect_seg_fault=0)
     self.RunAndVerify(env_var_value=None,
                       flag_value='1',
                       expect_seg_fault=1)
def gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testFlagOverridesEnvVar (self)
Tests that the flag overrides the environment variable.
Definition at line 171 of file gtest_break_on_failure_unittest.py.
References gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.RunAndVerify(), and gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testFlagOverridesEnvVar().
   def testFlagOverridesEnvVar(self):
     """Tests that the flag overrides the environment variable."""
     self.RunAndVerify(env_var_value='0',
                       flag_value='0',
                       expect_seg_fault=0)
     self.RunAndVerify(env_var_value='0',
                       flag_value='1',
                       expect_seg_fault=1)
     self.RunAndVerify(env_var_value='1',
                       flag_value='0',
                       expect_seg_fault=0)
     self.RunAndVerify(env_var_value='1',
                       flag_value='1',
                       expect_seg_fault=1)
def gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testFlagOverridesEnvVar (self)
Tests that the flag overrides the environment variable.
Definition at line 171 of file gtest_break_on_failure_unittest.py.
References gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.RunAndVerify().
Referenced by gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testFlagOverridesEnvVar().
   def testFlagOverridesEnvVar(self):
     """Tests that the flag overrides the environment variable."""
     self.RunAndVerify(env_var_value='0',
                       flag_value='0',
                       expect_seg_fault=0)
     self.RunAndVerify(env_var_value='0',
                       flag_value='1',
                       expect_seg_fault=1)
     self.RunAndVerify(env_var_value='1',
                       flag_value='0',
                       expect_seg_fault=0)
     self.RunAndVerify(env_var_value='1',
                       flag_value='1',
                       expect_seg_fault=1)
def gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testFlagOverridesEnvVar (self)
Tests that the flag overrides the environment variable.
Definition at line 171 of file gtest_break_on_failure_unittest.py.
References gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.RunAndVerify(), and gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testFlagOverridesEnvVar().
   def testFlagOverridesEnvVar(self):
     """Tests that the flag overrides the environment variable."""
     self.RunAndVerify(env_var_value='0',
                       flag_value='0',
                       expect_seg_fault=0)
     self.RunAndVerify(env_var_value='0',
                       flag_value='1',
                       expect_seg_fault=1)
     self.RunAndVerify(env_var_value='1',
                       flag_value='0',
                       expect_seg_fault=0)
     self.RunAndVerify(env_var_value='1',
                       flag_value='1',
                       expect_seg_fault=1)
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest_break_on_failure_unittest.py