proxygen: folly::gen::detail::SplitStringSource< DelimiterType > Class Template Reference
folly::gen::detail::SplitStringSource< DelimiterType > Class Template Reference
#include <String-inl.h>
Public Member Functions
SplitStringSource (const StringPiece source, DelimiterType delimiter)
template<class Body >
bool apply (Body &&body) const
Public Member Functions inherited from folly::gen::GenImpl< StringPiece, SplitStringSource< DelimiterType > >
bool apply (Handler &&handler) const
void foreach (Body &&body) const
Public Member Functions inherited from folly::gen::FBounded< Self >
const Self & self () const
Self & self ()
Private Attributes
StringPiece source_
DelimiterType delimiter_
Additional Inherited Members
Public Types inherited from folly::gen::GenImpl< StringPiece, SplitStringSource< DelimiterType > >
typedef StringPiece ValueType
typedef std::decay< StringPiece >::type StorageType
Static Public Attributes inherited from folly::gen::GenImpl< StringPiece, SplitStringSource< DelimiterType > >
static constexpr bool infinite
Protected Member Functions inherited from folly::gen::GenImpl< StringPiece, SplitStringSource< DelimiterType > >
GenImpl ()=default
GenImpl (GenImpl &&)=default
GenImpl (const GenImpl &)=default
GenImpl & operator= (GenImpl &&)=default
GenImpl & operator= (const GenImpl &)=default
Detailed Description
template<class DelimiterType = char>
class folly::gen::detail::SplitStringSource< DelimiterType >
Definition at line 269 of file String-inl.h.
Constructor & Destructor Documentation
template<class DelimiterType = char> folly::gen::detail::SplitStringSource< DelimiterType >::SplitStringSource (const StringPiece source, DelimiterType delimiter) inline
Definition at line 275 of file String-inl.h.
       : source_(source), delimiter_(std::move(delimiter)) {}
Member Function Documentation
template<class DelimiterType = char> template<class Body > bool folly::gen::detail::SplitStringSource< DelimiterType >::apply (Body && body) const inline
Definition at line 279 of file String-inl.h.
References folly::Range< Iter >::empty(), prefix(), folly::gen::detail::splitPrefix(), and folly::Range< Iter >::subtract().
{
     StringPiece rest(source_);
     StringPiece prefix;
     while (size_t delim_len = splitPrefix(rest, prefix, this->delimiter_)) {
       prefix.subtract(delim_len); // Remove the delimiter
       if (!body(prefix)) {
         return false;
       }
     }
     if (!rest.empty()) {
       if (!body(rest)) {
         return false;
       }
     }
     return true;
   }
Member Data Documentation
template<class DelimiterType = char> DelimiterType folly::gen::detail::SplitStringSource< DelimiterType >::delimiter_ private
Definition at line 272 of file String-inl.h.
template<class DelimiterType = char> StringPiece folly::gen::detail::SplitStringSource< DelimiterType >::source_ private
Definition at line 271 of file String-inl.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/gen/String-inl.h