proxygen: folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false > Class Template Reference
folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false > Class Template Reference
#include <Iterator.h>
Public Types
using iterator_category = std::output_iterator_tag
using value_type = void
using difference_type = void
using pointer = void
using reference = void
using container_type = std::remove_reference_t< decltype(*EmplaceImpl::container)>
Public Member Functions
template<typename T >
Derived & operator= (T &&arg)
template<typename... Args>
Derived & operator= (emplace_args< Args... > &args)
template<typename... Args>
Derived & operator= (const emplace_args< Args... > &args)
template<typename... Args>
Derived & operator= (emplace_args< Args... > &&args)
Derived & operator* ()
Derived & operator++ ()
Derived & operator++ (int)
emplace_iterator_base (const emplace_iterator_base &)=default
emplace_iterator_base (emplace_iterator_base &&) noexcept=default
emplace_iterator_base & operator= (emplace_iterator_base &)=default
emplace_iterator_base & operator= (const emplace_iterator_base &)=default
emplace_iterator_base & operator= (emplace_iterator_base &&) noexcept=default
Protected Member Functions
template<typename Args , std::size_t... I>
Derived & unpackAndEmplace (Args &args, index_sequence< I... >)
template<typename Args , std::size_t... I>
Derived & unpackAndEmplace (const Args &args, index_sequence< I... >)
template<typename Args , std::size_t... I>
Derived & unpackAndEmplace (Args &&args, index_sequence< I... >)
Detailed Description
template<typename Derived, typename EmplaceImpl>
class folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false >
Partial specialization of emplace_iterator_base with implicit unpacking disabled.
Definition at line 225 of file Iterator.h.
Member Typedef Documentation
template<typename Derived , typename EmplaceImpl > using folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false >::container_type = std::remove_reference_t<decltype(*EmplaceImpl::container)>
Definition at line 235 of file Iterator.h.
template<typename Derived , typename EmplaceImpl > using folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false >::difference_type = void
Definition at line 231 of file Iterator.h.
template<typename Derived , typename EmplaceImpl > using folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false >::iterator_category = std::output_iterator_tag
Definition at line 229 of file Iterator.h.
template<typename Derived , typename EmplaceImpl > using folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false >::pointer = void
Definition at line 232 of file Iterator.h.
template<typename Derived , typename EmplaceImpl > using folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false >::reference = void
Definition at line 233 of file Iterator.h.
template<typename Derived , typename EmplaceImpl > using folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false >::value_type = void
Definition at line 230 of file Iterator.h.
Constructor & Destructor Documentation
template<typename Derived , typename EmplaceImpl > folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false >::emplace_iterator_base (const emplace_iterator_base< Derived, EmplaceImpl, false > &) default
template<typename Derived , typename EmplaceImpl > folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false >::emplace_iterator_base (emplace_iterator_base< Derived, EmplaceImpl, false > &&) default noexcept
Member Function Documentation
template<typename Derived , typename EmplaceImpl > Derived& folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false >::operator* () inline
Definition at line 267 of file Iterator.h.
{
     return static_cast<Derived&>(*this);
   }
template<typename Derived , typename EmplaceImpl > Derived& folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false >::operator++ () inline
Definition at line 270 of file Iterator.h.
{
     return static_cast<Derived&>(*this);
   }
template<typename Derived , typename EmplaceImpl > Derived& folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false >::operator++ (int) inline
Definition at line 273 of file Iterator.h.
References testing::Args(), and folly::pushmi::__adl::noexcept().
{
     return static_cast<Derived&>(*this);
   }
template<typename Derived , typename EmplaceImpl > template<typename T > Derived& folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false >::operator= (T && arg) inline
Canonical output operator. Forwards single argument straight to container's emplace function.
Definition at line 244 of file Iterator.h.
References testing::Args().
{
     this->emplace(std::forward<T>(arg));
     return static_cast<Derived&>(*this);
   }
template<typename Derived , typename EmplaceImpl > template<typename... Args> Derived& folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false >::operator= (emplace_args< Args... > & args) inline
Special output operator for packed arguments. Unpacks args and performs variadic call to container's emplace function.
Definition at line 254 of file Iterator.h.
References testing::Args().
{
     return unpackAndEmplace(args, index_sequence_for<Args...>{});
   }
template<typename Derived , typename EmplaceImpl > template<typename... Args> Derived& folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false >::operator= (const emplace_args< Args... > & args) inline
Definition at line 258 of file Iterator.h.
References testing::Args().
{
     return unpackAndEmplace(args, index_sequence_for<Args...>{});
   }
template<typename Derived , typename EmplaceImpl > template<typename... Args> Derived& folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false >::operator= (emplace_args< Args... > && args) inline
Definition at line 262 of file Iterator.h.
References folly::gen::move.
{
     return unpackAndEmplace(std::move(args), index_sequence_for<Args...>{});
   }
template<typename Derived , typename EmplaceImpl > emplace_iterator_base& folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false >::operator= (emplace_iterator_base< Derived, EmplaceImpl, false > &) default
template<typename Derived , typename EmplaceImpl > emplace_iterator_base& folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false >::operator= (const emplace_iterator_base< Derived, EmplaceImpl, false > &) default
template<typename Derived , typename EmplaceImpl > emplace_iterator_base& folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false >::operator= (emplace_iterator_base< Derived, EmplaceImpl, false > &&) default noexcept
template<typename Derived , typename EmplaceImpl > template<typename Args , std::size_t... I> Derived& folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false >::unpackAndEmplace (Args & args, index_sequence< I... >) inline protected
Definition at line 287 of file Iterator.h.
References testing::Args().
{
     this->emplace(get_emplace_arg<I>(args)...);
     return static_cast<Derived&>(*this);
   }
template<typename Derived , typename EmplaceImpl > template<typename Args , std::size_t... I> Derived& folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false >::unpackAndEmplace (const Args & args, index_sequence< I... >) inline protected
Definition at line 292 of file Iterator.h.
References testing::Args().
{
     this->emplace(get_emplace_arg<I>(args)...);
     return static_cast<Derived&>(*this);
   }
template<typename Derived , typename EmplaceImpl > template<typename Args , std::size_t... I> Derived& folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false >::unpackAndEmplace (Args && args, index_sequence< I... >) inline protected
Definition at line 297 of file Iterator.h.
References folly::gen::move.
{
     this->emplace(get_emplace_arg<I>(std::move(args))...);
     return static_cast<Derived&>(*this);
   }
The documentation for this class was generated from the following file:
proxygen/folly/folly/container/Iterator.h