proxygen: testing::ExpectationSet Class Reference
testing::ExpectationSet Class Reference
#include <gmock-spec-builders.h>
Public Types
typedef Expectation::Set::const_iterator const_iterator
typedef Expectation::Set::value_type value_type
typedef Expectation::Set::const_iterator const_iterator
typedef Expectation::Set::value_type value_type
typedef Expectation::Set::const_iterator const_iterator
typedef Expectation::Set::value_type value_type
Public Member Functions
ExpectationSet ()
ExpectationSet (internal::ExpectationBase &exp)
ExpectationSet (const Expectation &e)
bool operator== (const ExpectationSet &rhs) const
bool operator!= (const ExpectationSet &rhs) const
ExpectationSet & operator+= (const Expectation &e)
int size () const
const_iterator begin () const
const_iterator end () const
ExpectationSet ()
ExpectationSet (internal::ExpectationBase &exp)
ExpectationSet (const Expectation &e)
bool operator== (const ExpectationSet &rhs) const
bool operator!= (const ExpectationSet &rhs) const
ExpectationSet & operator+= (const Expectation &e)
int size () const
const_iterator begin () const
const_iterator end () const
ExpectationSet ()
ExpectationSet (internal::ExpectationBase &exp)
ExpectationSet (const Expectation &e)
bool operator== (const ExpectationSet &rhs) const
bool operator!= (const ExpectationSet &rhs) const
ExpectationSet & operator+= (const Expectation &e)
int size () const
const_iterator begin () const
const_iterator end () const
Private Attributes
Expectation::Set expectations_
Detailed Description
Definition at line 563 of file gmock-spec-builders.h.
Member Typedef Documentation
typedef Expectation::Set::const_iterator testing::ExpectationSet::const_iterator
Definition at line 566 of file gmock-spec-builders.h.
typedef Expectation::Set::const_iterator testing::ExpectationSet::const_iterator
Definition at line 566 of file gmock-spec-builders.h.
typedef Expectation::Set::const_iterator testing::ExpectationSet::const_iterator
Definition at line 566 of file gmock-spec-builders.h.
typedef Expectation::Set::value_type testing::ExpectationSet::value_type
Definition at line 569 of file gmock-spec-builders.h.
typedef Expectation::Set::value_type testing::ExpectationSet::value_type
Definition at line 569 of file gmock-spec-builders.h.
typedef Expectation::Set::value_type testing::ExpectationSet::value_type
Definition at line 569 of file gmock-spec-builders.h.
Constructor & Destructor Documentation
testing::ExpectationSet::ExpectationSet () inline
Definition at line 572 of file gmock-spec-builders.h.
 {}
testing::ExpectationSet::ExpectationSet (internal::ExpectationBase & exp) inline
Definition at line 577 of file gmock-spec-builders.h.
                                                {  // NOLINT
     *this += Expectation(exp);
   }
testing::ExpectationSet::ExpectationSet (const Expectation & e) inline
Definition at line 584 of file gmock-spec-builders.h.
                                        {  // NOLINT
     *this += e;
   }
testing::ExpectationSet::ExpectationSet () inline
Definition at line 572 of file gmock-spec-builders.h.
 {}
testing::ExpectationSet::ExpectationSet (internal::ExpectationBase & exp) inline
Definition at line 577 of file gmock-spec-builders.h.
                                                {  // NOLINT
     *this += Expectation(exp);
   }
testing::ExpectationSet::ExpectationSet (const Expectation & e) inline
Definition at line 584 of file gmock-spec-builders.h.
                                        {  // NOLINT
     *this += e;
   }
testing::ExpectationSet::ExpectationSet () inline
Definition at line 572 of file gmock-spec-builders.h.
 {}
testing::ExpectationSet::ExpectationSet (internal::ExpectationBase & exp) inline
Definition at line 577 of file gmock-spec-builders.h.
                                                {  // NOLINT
     *this += Expectation(exp);
   }
testing::ExpectationSet::ExpectationSet (const Expectation & e) inline
Definition at line 584 of file gmock-spec-builders.h.
                                        {  // NOLINT
     *this += e;
   }
Member Function Documentation
const_iterator testing::ExpectationSet::begin () const inline
Definition at line 608 of file gmock-spec-builders.h.
Referenced by testing::internal::TypedExpectation< F >::After(), testing::internal::ExpectationBase::AllPrerequisitesAreSatisfied(), testing::internal::TypedExpectation< F >::ExplainMatchResultTo(), testing::internal::ExpectationBase::FindUnsatisfiedPrerequisites(), and testing::internal::ExpectationBase::RetireAllPreRequisites().
 { return expectations_.begin(); }
const_iterator testing::ExpectationSet::begin () const inline
Definition at line 608 of file gmock-spec-builders.h.
 { return expectations_.begin(); }
const_iterator testing::ExpectationSet::begin () const inline
Definition at line 608 of file gmock-spec-builders.h.
 { return expectations_.begin(); }
const_iterator testing::ExpectationSet::end () const inline
Definition at line 609 of file gmock-spec-builders.h.
References GTEST_API_.
 { return expectations_.end(); }
const_iterator testing::ExpectationSet::end () const inline
Definition at line 609 of file gmock-spec-builders.h.
Referenced by testing::internal::TypedExpectation< F >::After(), testing::internal::ExpectationBase::AllPrerequisitesAreSatisfied(), testing::internal::TypedExpectation< F >::ExplainMatchResultTo(), testing::internal::ExpectationBase::FindUnsatisfiedPrerequisites(), and testing::internal::ExpectationBase::RetireAllPreRequisites().
 { return expectations_.end(); }
const_iterator testing::ExpectationSet::end () const inline
Definition at line 609 of file gmock-spec-builders.h.
References GTEST_API_.
 { return expectations_.end(); }
bool testing::ExpectationSet::operator!= (const ExpectationSet & rhs) const inline
Definition at line 597 of file gmock-spec-builders.h.
References folly::detail::rhs.
 { return !(*this == rhs); }
bool testing::ExpectationSet::operator!= (const ExpectationSet & rhs) const inline
Definition at line 597 of file gmock-spec-builders.h.
References folly::detail::rhs.
 { return !(*this == rhs); }
bool testing::ExpectationSet::operator!= (const ExpectationSet & rhs) const inline
Definition at line 597 of file gmock-spec-builders.h.
References folly::detail::rhs.
 { return !(*this == rhs); }
ExpectationSet& testing::ExpectationSet::operator+= (const Expectation & e) inline
Definition at line 601 of file gmock-spec-builders.h.
{
     expectations_.insert(e);
     return *this;
   }
ExpectationSet& testing::ExpectationSet::operator+= (const Expectation & e) inline
Definition at line 601 of file gmock-spec-builders.h.
{
     expectations_.insert(e);
     return *this;
   }
ExpectationSet& testing::ExpectationSet::operator+= (const Expectation & e) inline
Definition at line 601 of file gmock-spec-builders.h.
{
     expectations_.insert(e);
     return *this;
   }
bool testing::ExpectationSet::operator== (const ExpectationSet & rhs) const inline
Definition at line 593 of file gmock-spec-builders.h.
References expectations_.
{
     return expectations_ == rhs.expectations_;
   }
bool testing::ExpectationSet::operator== (const ExpectationSet & rhs) const inline
Definition at line 593 of file gmock-spec-builders.h.
References expectations_.
{
     return expectations_ == rhs.expectations_;
   }
bool testing::ExpectationSet::operator== (const ExpectationSet & rhs) const inline
Definition at line 593 of file gmock-spec-builders.h.
References expectations_.
{
     return expectations_ == rhs.expectations_;
   }
int testing::ExpectationSet::size () const inline
Definition at line 606 of file gmock-spec-builders.h.
 { return static_cast<int>(expectations_.size()); }
int testing::ExpectationSet::size () const inline
Definition at line 606 of file gmock-spec-builders.h.
 { return static_cast<int>(expectations_.size()); }
int testing::ExpectationSet::size () const inline
Definition at line 606 of file gmock-spec-builders.h.
 { return static_cast<int>(expectations_.size()); }
Member Data Documentation
Expectation::Set testing::ExpectationSet::expectations_ private
Definition at line 612 of file gmock-spec-builders.h.
Referenced by operator==().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-spec-builders.h