proxygen: OnTheFlyPrimeTable Class Reference
OnTheFlyPrimeTable Class Reference
#include <prime_tables.h>
Public Member Functions
virtual bool IsPrime (int n) const
virtual int GetNextPrime (int p) const
virtual bool IsPrime (int n) const
virtual int GetNextPrime (int p) const
virtual bool IsPrime (int n) const
virtual int GetNextPrime (int p) const
Public Member Functions inherited from PrimeTable
virtual ~PrimeTable ()
virtual ~PrimeTable ()
virtual ~PrimeTable ()
Detailed Description
Definition at line 56 of file prime_tables.h.
Member Function Documentation
virtual int OnTheFlyPrimeTable::GetNextPrime (int p) const inline virtual
Implements PrimeTable.
Definition at line 69 of file prime_tables.h.
References PrimeTable::IsPrime().
{
     for (int n = p + 1; n > 0; n++) {
       if (IsPrime(n)) return n;
     }
     return -1;
   }
virtual int OnTheFlyPrimeTable::GetNextPrime (int p) const inline virtual
Implements PrimeTable.
Definition at line 69 of file prime_tables.h.
References PrimeTable::IsPrime().
{
     for (int n = p + 1; n > 0; n++) {
       if (IsPrime(n)) return n;
     }
     return -1;
   }
virtual int OnTheFlyPrimeTable::GetNextPrime (int p) const inline virtual
Implements PrimeTable.
Definition at line 69 of file prime_tables.h.
References PrimeTable::IsPrime().
{
     for (int n = p + 1; n > 0; n++) {
       if (IsPrime(n)) return n;
     }
     return -1;
   }
virtual bool OnTheFlyPrimeTable::IsPrime (int n) const inline virtual
Implements PrimeTable.
Definition at line 58 of file prime_tables.h.
References i.
{
     if (n <= 1) return false;
     for (int i = 2; i*i <= n; i++) {
       // n is divisible by an integer other than 1 and itself.
       if ((n % i) == 0) return false;
     }
     return true;
   }
virtual bool OnTheFlyPrimeTable::IsPrime (int n) const inline virtual
Implements PrimeTable.
Definition at line 58 of file prime_tables.h.
References i.
{
     if (n <= 1) return false;
     for (int i = 2; i*i <= n; i++) {
       // n is divisible by an integer other than 1 and itself.
       if ((n % i) == 0) return false;
     }
     return true;
   }
virtual bool OnTheFlyPrimeTable::IsPrime (int n) const inline virtual
Implements PrimeTable.
Definition at line 58 of file prime_tables.h.
References i.
{
     if (n <= 1) return false;
     for (int i = 2; i*i <= n; i++) {
       // n is divisible by an integer other than 1 and itself.
       if ((n % i) == 0) return false;
     }
     return true;
   }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/samples/prime_tables.h