proxygen: folly::EventUtil Class Reference
folly::EventUtil Class Reference
#include <EventUtil.h>
Static Public Member Functions
static bool isEventRegistered (const struct event *ev)
Detailed Description
low-level libevent utility functions
Definition at line 49 of file EventUtil.h.
Member Function Documentation
static bool folly::EventUtil::isEventRegistered (const struct event * ev) inline static
Definition at line 51 of file EventUtil.h.
References folly::event_ref_flags().
Referenced by folly::EventBase::cancelTimeout(), folly::EventHandler::isHandlerRegistered(), and folly::AsyncTimeout::isScheduled().
{
     // If any of these flags are set, the event is registered.
     enum {
       EVLIST_REGISTERED =
           (EVLIST_INSERTED | EVLIST_ACTIVE | EVLIST_TIMEOUT | EVLIST_SIGNAL)
     };
     return (event_ref_flags(ev) & EVLIST_REGISTERED);
   }
The documentation for this class was generated from the following file:
proxygen/folly/folly/io/async/EventUtil.h