proxygen: fizz::ZlibCertificateCompressor Class Reference
fizz::ZlibCertificateCompressor Class Reference
#include <ZlibCertificateCompressor.h>
Public Member Functions
ZlibCertificateCompressor (int compressLevel)
~ZlibCertificateCompressor () override=default
CertificateCompressionAlgorithm getAlgorithm () const override
CompressedCertificate compress (const CertificateMsg &) override
Public Member Functions inherited from fizz::CertificateCompressor
virtual ~CertificateCompressor ()=default
Private Attributes
const int level_
Detailed Description
Definition at line 15 of file ZlibCertificateCompressor.h.
Constructor & Destructor Documentation
fizz::ZlibCertificateCompressor::ZlibCertificateCompressor (int compressLevel) explicit
Definition at line 15 of file ZlibCertificateCompressor.cpp.
     : level_(compressLevel) {
   if (compressLevel != Z_DEFAULT_COMPRESSION &&
       !(compressLevel >= Z_NO_COMPRESSION &&
         compressLevel <= Z_BEST_COMPRESSION)) {
     throw std::runtime_error(
         "Invalid compression level requested:" +
         to<std::string>(compressLevel));
   }
 }
fizz::ZlibCertificateCompressor::~ZlibCertificateCompressor () override default
Member Function Documentation
CompressedCertificate fizz::ZlibCertificateCompressor::compress (const CertificateMsg & cert) override virtual
Implements fizz::CertificateCompressor.
Definition at line 31 of file ZlibCertificateCompressor.cpp.
References fizz::CompressedCertificate::algorithm, cc, fizz::CompressedCertificate::compressed_certificate_message, fizz::encode(), getAlgorithm(), level_, folly::gen::move, folly::size(), and fizz::CompressedCertificate::uncompressed_length.
{
   auto encoded = encode(cert);
   auto certRange = encoded->coalesce();
   auto compressedCert = IOBuf::create(compressBound(certRange.size()));
   unsigned long size = compressedCert->capacity();
   int status = ::compress2(
       compressedCert->writableData(),
       &size,
       certRange.data(),
       certRange.size(),
       level_);
   switch (status) {
     case Z_OK:
       compressedCert->append(size);
       break;
     case Z_MEM_ERROR:
       throw std::runtime_error("Insufficient memory to compress cert");
     case Z_BUF_ERROR:
       throw std::runtime_error("Buffer too small for compressed cert");
     case Z_STREAM_ERROR:
       throw std::runtime_error(
           "Compression level invalid: " + to<std::string>(level_));
     default:
       throw std::runtime_error(
           "Failed to compress: " + to<std::string>(status));
   }
   CompressedCertificate cc;
   cc.uncompressed_length = certRange.size();
   cc.algorithm = getAlgorithm();
   cc.compressed_certificate_message = std::move(compressedCert);
   return cc;
 }
CertificateCompressionAlgorithm fizz::ZlibCertificateCompressor::getAlgorithm () const override virtual
Implements fizz::CertificateCompressor.
Definition at line 26 of file ZlibCertificateCompressor.cpp.
References fizz::zlib.
Referenced by compress().
           {
   return CertificateCompressionAlgorithm::zlib;
 }
Member Data Documentation
const int fizz::ZlibCertificateCompressor::level_ private
Definition at line 25 of file ZlibCertificateCompressor.h.
Referenced by compress().
The documentation for this class was generated from the following files:
proxygen/fizz/fizz/protocol/ZlibCertificateCompressor.h
proxygen/fizz/fizz/protocol/ZlibCertificateCompressor.cpp