proxygen: testing::gmock_matchers_test::Unprintable Class Reference
testing::gmock_matchers_test::Unprintable Class Reference
Public Member Functions
Unprintable ()
Unprintable ()
Unprintable ()
Private Attributes
char c_
Detailed Description
Definition at line 866 of file gmock-matchers_test.cc.
Constructor & Destructor Documentation
testing::gmock_matchers_test::Unprintable::Unprintable () inline
Definition at line 868 of file gmock-matchers_test.cc.
 : c_('a') {}
testing::gmock_matchers_test::Unprintable::Unprintable () inline
Definition at line 868 of file gmock-matchers_test.cc.
References c_, testing::gmock_matchers_test::Describe(), testing::Eq(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), testing::internal::operator==(), and testing::internal::TEST().
 : c_('a') {}
testing::gmock_matchers_test::Unprintable::Unprintable () inline
Definition at line 868 of file gmock-matchers_test.cc.
References c_, testing::gmock_matchers_test::Describe(), testing::Eq(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), testing::internal::operator==(), and testing::internal::TEST().
 : c_('a') {}
Member Data Documentation
char testing::gmock_matchers_test::Unprintable::c_ private
Definition at line 871 of file gmock-matchers_test.cc.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-matchers_test.cc