proxygen: wangle::OutputBufferingHandler Class Reference
wangle::OutputBufferingHandler Class Reference
#include <OutputBufferingHandler.h>
Public Member Functions
folly::Future< folly::Unit > write (Context *ctx, std::unique_ptr< folly::IOBuf > buf) override
void runLoopCallback () noexceptoverride
void cleanUp ()
folly::Future< folly::Unit > close (Context *ctx) override
Public Member Functions inherited from wangle::OutboundHandler< Win, Wout >
~OutboundHandler () override=default
virtual folly::Future< folly::Unit > write (Context *ctx, Win msg)=0
virtual folly::Future< folly::Unit > writeException (Context *ctx, folly::exception_wrapper e)
Public Member Functions inherited from wangle::HandlerBase< OutboundHandlerContext< Wout > >
virtual ~HandlerBase ()=default
virtual void attachPipeline (OutboundHandlerContext< Wout > *)
virtual void detachPipeline (OutboundHandlerContext< Wout > *)
OutboundHandlerContext< Wout > * getContext ()
Public Attributes
folly::SharedPromise< folly::Unit > sharedPromise_
std::unique_ptr< folly::IOBuf > sends_ {nullptr}
bool queueSends_ {true}
Additional Inherited Members
Public Types inherited from wangle::OutboundHandler< Win, Wout >
typedef folly::Unit rin
typedef folly::Unit rout
typedef Win win
typedef Wout wout
typedef OutboundHandlerContext< Wout > Context
Static Public Attributes inherited from wangle::OutboundHandler< Win, Wout >
static const HandlerDir dir = HandlerDir::OUT
Protected Member Functions inherited from folly::EventBase::LoopCallback
virtual ~LoopCallback ()=default
void cancelLoopCallback ()
bool isLoopCallbackScheduled () const
Detailed Description
Definition at line 34 of file OutputBufferingHandler.h.
Member Function Documentation
void wangle::OutputBufferingHandler::cleanUp () inline
Definition at line 69 of file OutputBufferingHandler.h.
References folly::EventBase::LoopCallback::cancelLoopCallback(), folly::EventBase::LoopCallback::isLoopCallbackScheduled(), sends_, and sharedPromise_.
                  {
     if (isLoopCallbackScheduled()) {
       cancelLoopCallback();
     }
     sends_.reset();
     sharedPromise_ = folly::SharedPromise<folly::Unit>();
   }
folly::Future<folly::Unit> wangle::OutputBufferingHandler::close (Context * ctx) inline override virtual
Reimplemented from wangle::OutboundHandler< Win, Wout >.
Definition at line 78 of file OutputBufferingHandler.h.
References folly::EventBase::LoopCallback::cancelLoopCallback(), wangle::OutboundHandlerContext< Out >::fireClose(), folly::EventBase::LoopCallback::isLoopCallbackScheduled(), sends_, folly::SharedPromise< T >::setException(), and sharedPromise_.
{
     if (isLoopCallbackScheduled()) {
       cancelLoopCallback();
     }
     // If there are sends queued, cancel them
     sharedPromise_.setException(
       folly::make_exception_wrapper<std::runtime_error>(
         "close() called while sends still pending"));
     sends_.reset();
     sharedPromise_ = folly::SharedPromise<folly::Unit>();
     return ctx->fireClose();
   }
void wangle::OutputBufferingHandler::runLoopCallback () inline override virtual noexcept
Implements folly::EventBase::LoopCallback.
Definition at line 58 of file OutputBufferingHandler.h.
References wangle::OutboundHandlerContext< Out >::fireWrite(), wangle::HandlerBase< OutboundHandlerContext< Wout > >::getContext(), folly::gen::move, sends_, folly::SharedPromise< T >::setTry(), sharedPromise_, folly::f14::swap(), and folly::pushmi::detail::t.
{
     folly::SharedPromise<folly::Unit> sharedPromise;
     std::swap(sharedPromise, sharedPromise_);
     getContext()
         ->fireWrite(std::move(sends_))
         .thenTry([sharedPromise = std::move(sharedPromise)](
                      folly::Try<folly::Unit> t) mutable {
           sharedPromise.setTry(std::move(t));
         });
   }
folly::Future<folly::Unit> wangle::OutputBufferingHandler::write (Context * ctx, std::unique_ptr< folly::IOBuf > buf) inline override
Definition at line 37 of file OutputBufferingHandler.h.
References wangle::OutboundHandlerContext< Out >::fireWrite(), folly::SharedPromise< T >::getFuture(), wangle::OutboundHandlerContext< Out >::getTransport(), folly::EventBase::LoopCallback::isLoopCallbackScheduled(), folly::gen::move, queueSends_, sends_, and sharedPromise_.
{
     CHECK(buf);
     if (!queueSends_) {
       return ctx->fireWrite(std::move(buf));
     } else {
       // Delay sends to optimize for fewer syscalls
       if (!sends_) {
         DCHECK(!isLoopCallbackScheduled());
         // Buffer all the sends, and call writev once per event loop.
         sends_ = std::move(buf);
         ctx->getTransport()->getEventBase()->runInLoop(this);
       } else {
         DCHECK(isLoopCallbackScheduled());
         sends_->prependChain(std::move(buf));
       }
       return sharedPromise_.getFuture();
     }
   }
Member Data Documentation
bool wangle::OutputBufferingHandler::queueSends_ {true}
Definition at line 94 of file OutputBufferingHandler.h.
Referenced by write().
std::unique_ptr<folly::IOBuf> wangle::OutputBufferingHandler::sends_ {nullptr}
Definition at line 93 of file OutputBufferingHandler.h.
Referenced by cleanUp(), close(), runLoopCallback(), and write().
folly::SharedPromise<folly::Unit> wangle::OutputBufferingHandler::sharedPromise_
Definition at line 92 of file OutputBufferingHandler.h.
Referenced by cleanUp(), close(), runLoopCallback(), and write().
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/channel/OutputBufferingHandler.h