proxygen: fizz::HkdfImpl< Hash > Class Template Reference
fizz::HkdfImpl< Hash > Class Template Reference
#include <Hkdf.h>
Public Member Functions
std::vector< uint8_t > extract (folly::ByteRange salt, folly::ByteRange ikm) const override
std::unique_ptr< folly::IOBuf > expand (folly::ByteRange extractedKey, const folly::IOBuf &info, size_t outputBytes) const override
std::unique_ptr< folly::IOBuf > hkdf (folly::ByteRange ikm, folly::ByteRange salt, const folly::IOBuf &info, size_t outputBytes) const override
size_t hashLength () const override
Public Member Functions inherited from fizz::Hkdf
virtual ~Hkdf ()=default
Static Public Attributes
static constexpr size_t HashLen = Hash::HashLen
Detailed Description
template<typename Hash>
class fizz::HkdfImpl< Hash >
HKDF implementation using a templated HMAC implementation.
The template struct requires the following parameters:
HashLen: length of the hash digest
hmac(ByteRange key, const IOBuf& in, MutableByteRange out)
Definition at line 54 of file Hkdf.h.
Member Function Documentation
template<typename Hash > std::unique_ptr< folly::IOBuf > fizz::HkdfImpl< Hash >::expand (folly::ByteRange extractedKey, const folly::IOBuf & info, size_t outputBytes) const inline override virtual
Implements fizz::Hkdf.
Definition at line 25 of file Hkdf-inl.h.
References folly::IOBuf::clone(), folly::IOBuf::create(), folly::gen::move, folly::range(), folly::chrono::round(), folly::Range< Iter >::size(), and UNLIKELY.
{
   CHECK_EQ(extractedKey.size(), Hash::HashLen);
   if (UNLIKELY(outputBytes > 255 * Hash::HashLen)) {
     throw std::runtime_error("Output too long");
   }
   // HDKF expansion step.
   size_t numRounds = (outputBytes + Hash::HashLen - 1) / Hash::HashLen;
   auto expanded = folly::IOBuf::create(numRounds * Hash::HashLen);
   auto in = folly::IOBuf::create(0);
   for (size_t round = 1; round <= numRounds; ++round) {
     in->prependChain(info.clone());
     // We're guaranteed that the round num will fit in
     // one byte because of the check at the beginning of
     // the method.
     auto roundNum = folly::IOBuf::create(1);
     roundNum->append(1);
     roundNum->writableData()[0] = round;
     in->prependChain(std::move(roundNum));
     size_t outputStartIdx = (round - 1) * Hash::HashLen;
     Hash::hmac(
         folly::range(extractedKey),
         *in,
         {expanded->writableData() + outputStartIdx, Hash::HashLen});
     expanded->append(Hash::HashLen);
     in = expanded->clone();
     in->trimStart(outputStartIdx);
   }
   expanded->trimEnd(numRounds * Hash::HashLen - outputBytes);
   return expanded;
 }
template<typename Hash > std::vector< uint8_t > fizz::HkdfImpl< Hash >::extract (folly::ByteRange salt, folly::ByteRange ikm) const inline override virtual
Implements fizz::Hkdf.
Definition at line 12 of file Hkdf-inl.h.
References folly::Range< Iter >::empty(), folly::range(), and folly::IOBuf::wrapBufferAsValue().
{
   auto zeros = std::vector<uint8_t>(Hash::HashLen, 0);
   // Extraction step HMAC-HASH(salt, IKM)
   std::vector<uint8_t> extractedKey(Hash::HashLen);
   salt = salt.empty() ? folly::range(zeros) : salt;
   Hash::hmac(
       salt, folly::IOBuf::wrapBufferAsValue(ikm), folly::range(extractedKey));
   return extractedKey;
 }
template<typename Hash> size_t fizz::HkdfImpl< Hash >::hashLength () const inline override virtual
Implements fizz::Hkdf.
Definition at line 72 of file Hkdf.h.
{
     return HashLen;
   }
template<typename Hash > std::unique_ptr< folly::IOBuf > fizz::HkdfImpl< Hash >::hkdf (folly::ByteRange ikm, folly::ByteRange salt, const folly::IOBuf & info, size_t outputBytes) const inline override virtual
Implements fizz::Hkdf.
Definition at line 63 of file Hkdf-inl.h.
References folly::range().
{
   return expand(folly::range(extract(salt, ikm)), info, outputBytes);
 }
Member Data Documentation
template<typename Hash> constexpr size_t fizz::HkdfImpl< Hash >::HashLen = Hash::HashLen static
Definition at line 56 of file Hkdf.h.
The documentation for this class was generated from the following files:
proxygen/fizz/fizz/crypto/Hkdf.h
proxygen/fizz/fizz/crypto/Hkdf-inl.h