proxygen: cpp.ast.Expr Class Reference
cpp.ast.Expr Class Reference
Public Member Functions
def __init__ (self, start, end, expr)
def Requires (self, node)
def __str__ (self)
def __init__ (self, start, end, expr)
def Requires (self, node)
def __str__ (self)
def __init__ (self, start, end, expr)
def Requires (self, node)
def __str__ (self)
Public Member Functions inherited from cpp.ast.Node
def __init__ (self, start, end)
def IsDeclaration (self)
def IsDefinition (self)
def IsExportable (self)
def Requires (self, node)
def XXX__str__ (self)
def __repr__ (self)
def __init__ (self, start, end)
def IsDeclaration (self)
def IsDefinition (self)
def IsExportable (self)
def Requires (self, node)
def XXX__str__ (self)
def __repr__ (self)
def __init__ (self, start, end)
def IsDeclaration (self)
def IsDefinition (self)
def IsExportable (self)
def Requires (self, node)
def XXX__str__ (self)
def __repr__ (self)
Public Attributes
expr
Public Attributes inherited from cpp.ast.Node
start
end
Detailed Description
Definition at line 177 of file ast.py.
Constructor & Destructor Documentation
def cpp.ast.Expr.__init__ (self, start, end, expr)
Definition at line 178 of file ast.py.
Referenced by cpp.ast.Expr.__init__().
     def __init__(self, start, end, expr):
         Node.__init__(self, start, end)
         self.expr = expr
def cpp.ast.Expr.__init__ (self, start, end, expr)
Definition at line 178 of file ast.py.
References cpp.ast.Expr.__init__(), and cpp.ast.Expr.expr.
     def __init__(self, start, end, expr):
         Node.__init__(self, start, end)
         self.expr = expr
def cpp.ast.Expr.__init__ (self, start, end, expr)
Definition at line 178 of file ast.py.
References cpp.ast.Expr.__init__(), and cpp.ast.Expr.expr.
     def __init__(self, start, end, expr):
         Node.__init__(self, start, end)
         self.expr = expr
Member Function Documentation
def cpp.ast.Expr.__str__ (self)
Definition at line 186 of file ast.py.
References cpp.ast.Node._StringHelper(), and cpp.ast.Expr.expr.
Referenced by cpp.ast.Expr.__str__().
     def __str__(self):
         return self._StringHelper(self.__class__.__name__, str(self.expr))
def cpp.ast.Expr.__str__ (self)
Definition at line 186 of file ast.py.
References cpp.ast.Expr.__str__(), cpp.ast.Node._StringHelper(), and cpp.ast.Expr.expr.
     def __str__(self):
         return self._StringHelper(self.__class__.__name__, str(self.expr))
def cpp.ast.Expr.__str__ (self)
Definition at line 186 of file ast.py.
References cpp.ast.Expr.__str__(), cpp.ast.Node._StringHelper(), and cpp.ast.Expr.expr.
     def __str__(self):
         return self._StringHelper(self.__class__.__name__, str(self.expr))
def cpp.ast.Expr.Requires (self, node)
Definition at line 182 of file ast.py.
Referenced by cpp.ast.Expr.Requires().
     def Requires(self, node):
         # TODO(nnorwitz): impl.
         return False
def cpp.ast.Expr.Requires (self, node)
Definition at line 182 of file ast.py.
References cpp.ast.Expr.Requires().
     def Requires(self, node):
         # TODO(nnorwitz): impl.
         return False
def cpp.ast.Expr.Requires (self, node)
Definition at line 182 of file ast.py.
References cpp.ast.Expr.Requires().
     def Requires(self, node):
         # TODO(nnorwitz): impl.
         return False
Member Data Documentation
cpp.ast.Expr.expr
Definition at line 180 of file ast.py.
Referenced by cpp.ast.Expr.__init__(), and cpp.ast.Expr.__str__().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/scripts/generator/cpp/ast.py