proxygen: folly::observer_detail::ObserverManager::CurrentQueue Class Reference
folly::observer_detail::ObserverManager::CurrentQueue Class Reference
Public Member Functions
CurrentQueue ()
~CurrentQueue ()
void add (Function< void()> task)
Private Attributes
MPMCQueue< Function< void()> > queue_
std::vector< std::thread > threads_
Detailed Description
Definition at line 45 of file ObserverManager.cpp.
Constructor & Destructor Documentation
folly::observer_detail::ObserverManager::CurrentQueue::CurrentQueue () inline
Definition at line 47 of file ObserverManager.cpp.
References folly::exceptionStr(), i, folly::observer_detail::ObserverManager::inManagerThread_, int32_t, folly::observer_detail::kObserverManagerThreadNamePrefix, queue_, folly::setThreadName(), folly::sformat(), and threads_.
                  : queue_(kCurrentQueueSize) {
     if (FLAGS_observer_manager_pool_size < 1) {
       LOG(ERROR) << "--observer_manager_pool_size should be >= 1";
       FLAGS_observer_manager_pool_size = 1;
     }
     for (int32_t i = 0; i < FLAGS_observer_manager_pool_size; ++i) {
       threads_.emplace_back([this, i]() {
         folly::setThreadName(
             folly::sformat("{}{}", kObserverManagerThreadNamePrefix, i));
         ObserverManager::inManagerThread_ = true;
         while (true) {
           Function<void()> task;
           queue_.blockingRead(task);
           if (!task) {
             return;
           }
           try {
             task();
           } catch (...) {
             LOG(ERROR) << "Exception while running CurrentQueue task: "
                        << exceptionStr(std::current_exception());
           }
         }
       });
     }
   }
folly::observer_detail::ObserverManager::CurrentQueue::~CurrentQueue () inline
Definition at line 77 of file ObserverManager.cpp.
References i, queue_, and threads_.
                   {
     for (size_t i = 0; i < threads_.size(); ++i) {
       queue_.blockingWrite(nullptr);
     }
     for (auto& thread : threads_) {
       thread.join();
     }
     CHECK(queue_.isEmpty());
   }
Member Function Documentation
void folly::observer_detail::ObserverManager::CurrentQueue::add (Function< void()> task) inline
Definition at line 89 of file ObserverManager.cpp.
References folly::observer_detail::ObserverManager::inManagerThread(), folly::gen::move, and queue_.
{
     if (ObserverManager::inManagerThread()) {
       if (!queue_.write(std::move(task))) {
         throw std::runtime_error("Too many Observers scheduled for update.");
       }
     } else {
       queue_.blockingWrite(std::move(task));
     }
   }
Member Data Documentation
MPMCQueue<Function<void()> > folly::observer_detail::ObserverManager::CurrentQueue::queue_ private
Definition at line 100 of file ObserverManager.cpp.
Referenced by add(), folly::observer_detail::ObserverManager::NextQueue::add(), CurrentQueue(), folly::observer_detail::ObserverManager::NextQueue::NextQueue(), ~CurrentQueue(), and folly::observer_detail::ObserverManager::NextQueue::~NextQueue().
std::vector<std::thread> folly::observer_detail::ObserverManager::CurrentQueue::threads_ private
Definition at line 101 of file ObserverManager.cpp.
Referenced by CurrentQueue(), and ~CurrentQueue().
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/observer/detail/ObserverManager.cpp