proxygen: folly::dummy_fbstring_core< Char > Class Template Reference
folly::dummy_fbstring_core< Char > Class Template Reference
#include <FBString.h>
Public Member Functions
dummy_fbstring_core ()
dummy_fbstring_core (const dummy_fbstring_core &another)
dummy_fbstring_core (const Char *s, size_t n)
void swap (dummy_fbstring_core &rhs)
const Char * data () const
Char * mutableData ()
void shrink (size_t delta)
Char * expandNoinit (size_t delta)
void push_back (Char c)
size_t size () const
size_t capacity () const
bool isShared () const
void reserve (size_t minCapacity)
Private Attributes
std::basic_string< Char > backend_
Detailed Description
template<class Char>
class folly::dummy_fbstring_core< Char >
Dummy fbstring core that uses an actual std::string. This doesn't make any sense - it's just for testing purposes.
Definition at line 1011 of file FBString.h.
Constructor & Destructor Documentation
template<class Char > folly::dummy_fbstring_core< Char >::dummy_fbstring_core () inline
Definition at line 1013 of file FBString.h.
 {}
template<class Char > folly::dummy_fbstring_core< Char >::dummy_fbstring_core (const dummy_fbstring_core< Char > & another) inline
Definition at line 1014 of file FBString.h.
       : backend_(another.backend_) {}
template<class Char > folly::dummy_fbstring_core< Char >::dummy_fbstring_core (const Char * s, size_t n) inline
Definition at line 1016 of file FBString.h.
 : backend_(s, n) {}
Member Function Documentation
template<class Char > size_t folly::dummy_fbstring_core< Char >::capacity () const inline
Definition at line 1041 of file FBString.h.
{
     return backend_.capacity();
   }
template<class Char > const Char* folly::dummy_fbstring_core< Char >::data () const inline
Definition at line 1020 of file FBString.h.
{
     return backend_.data();
   }
template<class Char > Char* folly::dummy_fbstring_core< Char >::expandNoinit (size_t delta) inline
Definition at line 1030 of file FBString.h.
References folly::size().
{
     auto const sz = size();
     backend_.resize(size() + delta);
     return backend_.data() + sz;
   }
template<class Char > bool folly::dummy_fbstring_core< Char >::isShared () const inline
Definition at line 1044 of file FBString.h.
{
     return false;
   }
template<class Char > Char* folly::dummy_fbstring_core< Char >::mutableData () inline
Definition at line 1023 of file FBString.h.
References testing::gmock_generated_actions_test::Char().
                       {
     return const_cast<Char*>(backend_.data());
   }
template<class Char > void folly::dummy_fbstring_core< Char >::push_back (Char c) inline
Definition at line 1035 of file FBString.h.
{
     backend_.push_back(c);
   }
template<class Char > void folly::dummy_fbstring_core< Char >::reserve (size_t minCapacity) inline
Definition at line 1047 of file FBString.h.
{
     backend_.reserve(minCapacity);
   }
template<class Char > void folly::dummy_fbstring_core< Char >::shrink (size_t delta) inline
Definition at line 1026 of file FBString.h.
References FBSTRING_ASSERT, and folly::size().
{
     FBSTRING_ASSERT(delta <= size());
     backend_.resize(size() - delta);
   }
template<class Char > size_t folly::dummy_fbstring_core< Char >::size () const inline
Definition at line 1038 of file FBString.h.
                       {
     return backend_.size();
   }
template<class Char > void folly::dummy_fbstring_core< Char >::swap (dummy_fbstring_core< Char > & rhs) inline
Definition at line 1017 of file FBString.h.
References folly::dummy_fbstring_core< Char >::backend_.
{
     backend_.swap(rhs.backend_);
   }
Member Data Documentation
template<class Char > std::basic_string<Char> folly::dummy_fbstring_core< Char >::backend_ private
Definition at line 1052 of file FBString.h.
Referenced by folly::dummy_fbstring_core< Char >::swap().
The documentation for this class was generated from the following file:
proxygen/folly/folly/FBString.h