proxygen: TerminateTestCallback Class Reference
TerminateTestCallback Class Reference
Public Member Functions
TerminateTestCallback (EventBase *eventBase, int fd)
void reset (uint32_t maxLoopInvocations, uint32_t maxEventInvocations)
void handlerReady (uint16_t) noexceptoverride
void runLoopCallback () noexceptoverride
uint32_t getLoopInvocations () const
uint32_t getEventInvocations () const
Public Member Functions inherited from folly::EventBase::LoopCallback
virtual ~LoopCallback ()=default
void cancelLoopCallback ()
bool isLoopCallbackScheduled () const
Public Member Functions inherited from folly::EventHandler
EventHandler (EventBase *eventBase, int fd)
EventHandler (EventBase *eventBase=nullptr, NetworkSocket fd=NetworkSocket())
virtual ~EventHandler ()
bool registerHandler (uint16_t events)
void unregisterHandler ()
bool isHandlerRegistered () const
void attachEventBase (EventBase *eventBase)
void detachEventBase ()
void changeHandlerFD (int fd)
void changeHandlerFD (NetworkSocket fd)
void initHandler (EventBase *eventBase, int fd)
void initHandler (EventBase *eventBase, NetworkSocket fd)
uint16_t getRegisteredEvents () const
bool registerInternalHandler (uint16_t events)
bool isPending () const
Private Attributes
EventBase * eventBase_
uint32_t loopInvocations_
uint32_t maxLoopInvocations_
uint32_t eventInvocations_
uint32_t maxEventInvocations_
Additional Inherited Members
Public Types inherited from folly::EventHandler
enum EventFlags {
NONE = 0, READ = EV_READ, WRITE = EV_WRITE, READ_WRITE = (READ | WRITE),
PERSIST = EV_PERSIST
}
Detailed Description
Definition at line 1468 of file EventBaseTest.cpp.
Constructor & Destructor Documentation
TerminateTestCallback::TerminateTestCallback (EventBase * eventBase, int fd) inline
Definition at line 1471 of file EventBaseTest.cpp.
       : EventHandler(eventBase, fd),
         eventBase_(eventBase),
         loopInvocations_(0),
         maxLoopInvocations_(0),
         eventInvocations_(0),
         maxEventInvocations_(0) {}
Member Function Documentation
uint32_t TerminateTestCallback::getEventInvocations () const inline
Definition at line 1513 of file EventBaseTest.cpp.
Referenced by TEST().
{
     return eventInvocations_;
   }
uint32_t TerminateTestCallback::getLoopInvocations () const inline
Definition at line 1510 of file EventBaseTest.cpp.
Referenced by TEST().
{
     return loopInvocations_;
   }
void TerminateTestCallback::handlerReady (uint16_t events) inline override virtual noexcept
handlerReady() is invoked when the handler is ready.
Parameters
events A bitset indicating the events that are ready.
Implements folly::EventHandler.
Definition at line 1489 of file EventBaseTest.cpp.
References ASSERT_FALSE.
{
     // We didn't register with PERSIST, so we will have been automatically
     // unregistered already.
     ASSERT_FALSE(isHandlerRegistered());
     ++eventInvocations_;
     if (eventInvocations_ >= maxEventInvocations_) {
       return;
     }
     eventBase_->runInLoop(this);
   }
void TerminateTestCallback::reset (uint32_t maxLoopInvocations, uint32_t maxEventInvocations) inline
Definition at line 1479 of file EventBaseTest.cpp.
Referenced by TEST().
{
     loopInvocations_ = 0;
     maxLoopInvocations_ = maxLoopInvocations;
     eventInvocations_ = 0;
     maxEventInvocations_ = maxEventInvocations;
     cancelLoopCallback();
     unregisterHandler();
   }
void TerminateTestCallback::runLoopCallback () inline override virtual noexcept
Implements folly::EventBase::LoopCallback.
Definition at line 1501 of file EventBaseTest.cpp.
{
     ++loopInvocations_;
     if (loopInvocations_ >= maxLoopInvocations_) {
       return;
     }
     registerHandler(READ);
   }
Member Data Documentation
EventBase* TerminateTestCallback::eventBase_ private
Definition at line 1518 of file EventBaseTest.cpp.
uint32_t TerminateTestCallback::eventInvocations_ private
Definition at line 1521 of file EventBaseTest.cpp.
uint32_t TerminateTestCallback::loopInvocations_ private
Definition at line 1519 of file EventBaseTest.cpp.
uint32_t TerminateTestCallback::maxEventInvocations_ private
Definition at line 1522 of file EventBaseTest.cpp.
uint32_t TerminateTestCallback::maxLoopInvocations_ private
Definition at line 1520 of file EventBaseTest.cpp.
The documentation for this class was generated from the following file:
proxygen/folly/folly/io/async/test/EventBaseTest.cpp