proxygen: Count Class Reference
Count Class Reference
Public Member Functions
void clear () noexcept
int ctors () const noexcept
int dtors () const noexcept
int retires () const noexcept
void inc_ctors () noexcept
void inc_dtors () noexcept
void inc_retires () noexcept
Private Attributes
std::atomic< int > ctors_ {0}
std::atomic< int > dtors_ {0}
std::atomic< int > retires_ {0}
Detailed Description
Count
Definition at line 57 of file HazptrTest.cpp.
Member Function Documentation
void Count::clear () inline noexcept
Definition at line 63 of file HazptrTest.cpp.
References ctors_, dtors_, and retires_.
Referenced by auto_retire_test(), basic_objects_test(), basic_protection_test(), cleanup_test(), folly::padded::Adaptor< IntNodeVec >::clear(), linked_test(), mt_linked_test(), priv_dtor_test(), and TEST().
{
     ctors_.store(0);
     dtors_.store(0);
     retires_.store(0);
   }
int Count::ctors () const inline noexcept
Definition at line 69 of file HazptrTest.cpp.
References ctors_.
Referenced by auto_retire_test(), basic_objects_test(), basic_protection_test(), cleanup_test(), linked_test(), mt_linked_test(), and priv_dtor_test().
{
     return ctors_.load();
   }
int Count::dtors () const inline noexcept
Definition at line 73 of file HazptrTest.cpp.
References dtors_.
Referenced by auto_retire_test(), basic_objects_test(), basic_protection_test(), cleanup_test(), linked_test(), mt_linked_test(), priv_dtor_test(), and TEST().
{
     return dtors_.load();
   }
void Count::inc_ctors () inline noexcept
Definition at line 81 of file HazptrTest.cpp.
References ctors_.
Referenced by Node< Atom >::Node(), NodeAuto< Atom >::NodeAuto(), and NodeRC< Mutable, Atom >::NodeRC().
{
     ctors_.fetch_add(1);
   }
void Count::inc_dtors () inline noexcept
Definition at line 85 of file HazptrTest.cpp.
References dtors_.
Referenced by Node< Atom >::~Node(), NodeAuto< Atom >::~NodeAuto(), and NodeRC< Mutable, Atom >::~NodeRC().
{
     dtors_.fetch_add(1);
   }
void Count::inc_retires () inline noexcept
Definition at line 89 of file HazptrTest.cpp.
References retires_.
{
     retires_.fetch_add(1);
   }
int Count::retires () const inline noexcept
Definition at line 77 of file HazptrTest.cpp.
References retires_.
{
     return retires_.load();
   }
Member Data Documentation
std::atomic<int> Count::ctors_ {0} private
Definition at line 58 of file HazptrTest.cpp.
Referenced by clear(), ctors(), and inc_ctors().
std::atomic<int> Count::dtors_ {0} private
Definition at line 59 of file HazptrTest.cpp.
Referenced by clear(), dtors(), and inc_dtors().
std::atomic<int> Count::retires_ {0} private
Definition at line 60 of file HazptrTest.cpp.
Referenced by clear(), inc_retires(), and retires().
The documentation for this class was generated from the following file:
proxygen/folly/folly/synchronization/test/HazptrTest.cpp