proxygen: folly::ssl::SSLSession Class Reference
folly::ssl::SSLSession Class Reference
#include <SSLSession.h>
Public Member Functions
SSLSession (SSL_SESSION *session, bool takeOwnership=true)
SSLSession (const std::string &serializedSession)
std::string serialize () const
std::string getSessionID () const
const SSL_SESSION * getRawSSLSession () const
SSL_SESSION * getRawSSLSessionDangerous ()
Private Attributes
std::unique_ptr< detail::SSLSessionImpl > impl_
Detailed Description
Definition at line 26 of file SSLSession.h.
Constructor & Destructor Documentation
folly::ssl::SSLSession::SSLSession (SSL_SESSION * session, bool takeOwnership = true) inline explicit
Definition at line 29 of file SSLSession.h.
       : impl_(
             std::make_unique<detail::SSLSessionImpl>(session, takeOwnership)) {}
folly::ssl::SSLSession::SSLSession (const std::string & serializedSession) inline explicit
Definition at line 34 of file SSLSession.h.
       : impl_(std::make_unique<detail::SSLSessionImpl>(serializedSession)) {}
Member Function Documentation
const SSL_SESSION* folly::ssl::SSLSession::getRawSSLSession () const inline
Definition at line 49 of file SSLSession.h.
References impl_.
{
     return impl_->getRawSSLSession();
   }
SSL_SESSION* folly::ssl::SSLSession::getRawSSLSessionDangerous () inline
Definition at line 56 of file SSLSession.h.
References impl_.
Referenced by folly::TEST_F().
{
     return impl_->getRawSSLSessionDangerous();
   }
std::string folly::ssl::SSLSession::getSessionID () const inline
Definition at line 43 of file SSLSession.h.
References impl_.
Referenced by folly::TEST_F().
{
     return impl_->getSessionID();
   }
std::string folly::ssl::SSLSession::serialize () const inline
Definition at line 38 of file SSLSession.h.
References impl_.
Referenced by folly::TEST_F().
{
     return impl_->serialize();
   }
Member Data Documentation
std::unique_ptr<detail::SSLSessionImpl> folly::ssl::SSLSession::impl_ private
Definition at line 61 of file SSLSession.h.
Referenced by getRawSSLSession(), getRawSSLSessionDangerous(), getSessionID(), and serialize().
The documentation for this class was generated from the following file:
proxygen/folly/folly/ssl/SSLSession.h