proxygen: testing::TestPartResult Class Reference
testing::TestPartResult Class Reference
#include <gtest-test-part.h>
Public Types
enum Type {
kSuccess, kNonFatalFailure, kFatalFailure, kSuccess,
kNonFatalFailure, kFatalFailure, kSuccess, kNonFatalFailure,
kFatalFailure
}
enum Type {
kSuccess, kNonFatalFailure, kFatalFailure, kSuccess,
kNonFatalFailure, kFatalFailure, kSuccess, kNonFatalFailure,
kFatalFailure
}
enum Type {
kSuccess, kNonFatalFailure, kFatalFailure, kSuccess,
kNonFatalFailure, kFatalFailure, kSuccess, kNonFatalFailure,
kFatalFailure
}
Public Member Functions
TestPartResult (Type a_type, const char *a_file_name, int a_line_number, const char *a_message)
Type type () const
const char * file_name () const
int line_number () const
const char * summary () const
const char * message () const
bool passed () const
bool failed () const
bool nonfatally_failed () const
bool fatally_failed () const
TestPartResult (Type a_type, const char *a_file_name, int a_line_number, const char *a_message)
Type type () const
const char * file_name () const
int line_number () const
const char * summary () const
const char * message () const
bool passed () const
bool failed () const
bool nonfatally_failed () const
bool fatally_failed () const
TestPartResult (Type a_type, const char *a_file_name, int a_line_number, const char *a_message)
Type type () const
const char * file_name () const
int line_number () const
const char * summary () const
const char * message () const
bool passed () const
bool failed () const
bool nonfatally_failed () const
bool fatally_failed () const
Static Private Member Functions
static std::string ExtractSummary (const char *message)
static std::string ExtractSummary (const char *message)
static std::string ExtractSummary (const char *message)
Private Attributes
Type type_
std::string file_name_
int line_number_
std::string summary_
std::string message_
Detailed Description
Definition at line 47 of file gtest-test-part.h.
Member Enumeration Documentation
enum testing::TestPartResult::Type
Enumerator
kSuccess
kNonFatalFailure
kFatalFailure
kSuccess
kNonFatalFailure
kFatalFailure
kSuccess
kNonFatalFailure
kFatalFailure
Definition at line 51 of file gtest-test-part.h.
             {
     kSuccess,          // Succeeded.
     kNonFatalFailure,  // Failed but the test can continue.
     kFatalFailure      // Failed and the test should be terminated.
   };
enum testing::TestPartResult::Type
Enumerator
kSuccess
kNonFatalFailure
kFatalFailure
kSuccess
kNonFatalFailure
kFatalFailure
kSuccess
kNonFatalFailure
kFatalFailure
Definition at line 51 of file gtest-test-part.h.
             {
     kSuccess,          // Succeeded.
     kNonFatalFailure,  // Failed but the test can continue.
     kFatalFailure      // Failed and the test should be terminated.
   };
enum testing::TestPartResult::Type
Enumerator
kSuccess
kNonFatalFailure
kFatalFailure
kSuccess
kNonFatalFailure
kFatalFailure
kSuccess
kNonFatalFailure
kFatalFailure
Definition at line 51 of file gtest-test-part.h.
             {
     kSuccess,          // Succeeded.
     kNonFatalFailure,  // Failed but the test can continue.
     kFatalFailure      // Failed and the test should be terminated.
   };
Constructor & Destructor Documentation
testing::TestPartResult::TestPartResult (Type a_type, const char * a_file_name, int a_line_number, const char * a_message) inline
Definition at line 60 of file gtest-test-part.h.
       : type_(a_type),
         file_name_(a_file_name == NULL ? "" : a_file_name),
         line_number_(a_line_number),
         summary_(ExtractSummary(a_message)),
         message_(a_message) {
   }
testing::TestPartResult::TestPartResult (Type a_type, const char * a_file_name, int a_line_number, const char * a_message) inline
Definition at line 60 of file gtest-test-part.h.
       : type_(a_type),
         file_name_(a_file_name == NULL ? "" : a_file_name),
         line_number_(a_line_number),
         summary_(ExtractSummary(a_message)),
         message_(a_message) {
   }
testing::TestPartResult::TestPartResult (Type a_type, const char * a_file_name, int a_line_number, const char * a_message) inline
Definition at line 60 of file gtest-test-part.h.
       : type_(a_type),
         file_name_(a_file_name == NULL ? "" : a_file_name),
         line_number_(a_line_number),
         summary_(ExtractSummary(a_message)),
         message_(a_message) {
   }
Member Function Documentation
std::string testing::TestPartResult::ExtractSummary (const char * message) static private
Definition at line 51 of file gtest-test-part.cc.
References testing::internal::kStackTraceMarker, and string.
{
   const char* const stack_trace = strstr(message, internal::kStackTraceMarker);
   return stack_trace == NULL ? message :
       std::string(message, stack_trace);
 }
static std::string testing::TestPartResult::ExtractSummary (const char * message) static private
static std::string testing::TestPartResult::ExtractSummary (const char * message) static private
bool testing::TestPartResult::failed () const inline
Definition at line 94 of file gtest-test-part.h.
References type_.
 { return type_ != kSuccess; }
bool testing::TestPartResult::failed () const inline
Definition at line 94 of file gtest-test-part.h.
References type_.
Referenced by testing::TestResult::Failed(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), and testing::internal::PortableLocaltime().
 { return type_ != kSuccess; }
bool testing::TestPartResult::failed () const inline
Definition at line 94 of file gtest-test-part.h.
References type_.
 { return type_ != kSuccess; }
bool testing::TestPartResult::fatally_failed () const inline
Definition at line 100 of file gtest-test-part.h.
References GTEST_API_, testing::operator<<(), string, and type_.
 { return type_ == kFatalFailure; }
bool testing::TestPartResult::fatally_failed () const inline
Definition at line 100 of file gtest-test-part.h.
References type_.
Referenced by operator<<(), testing::internal::HasNewFatalFailureHelper::ReportTestPartResult(), and testing::TestPartFatallyFailed().
 { return type_ == kFatalFailure; }
bool testing::TestPartResult::fatally_failed () const inline
Definition at line 100 of file gtest-test-part.h.
References GTEST_API_, testing::operator<<(), string, and type_.
 { return type_ == kFatalFailure; }
const char* testing::TestPartResult::file_name () const inline
Definition at line 76 of file gtest-test-part.h.
{
     return file_name_.empty() ? NULL : file_name_.c_str();
   }
const char* testing::TestPartResult::file_name () const inline
Definition at line 76 of file gtest-test-part.h.
Referenced by testing::operator<<(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PortableLocaltime(), testing::internal::PrintTestPartResultToString(), and testing::internal::TestResultAccessor::test_part_results().
{
     return file_name_.empty() ? NULL : file_name_.c_str();
   }
const char* testing::TestPartResult::file_name () const inline
Definition at line 76 of file gtest-test-part.h.
{
     return file_name_.empty() ? NULL : file_name_.c_str();
   }
int testing::TestPartResult::line_number () const inline
Definition at line 82 of file gtest-test-part.h.
 { return line_number_; }
int testing::TestPartResult::line_number () const inline
Definition at line 82 of file gtest-test-part.h.
 { return line_number_; }
int testing::TestPartResult::line_number () const inline
Definition at line 82 of file gtest-test-part.h.
Referenced by testing::operator<<(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PortableLocaltime(), testing::internal::PrintTestPartResultToString(), and testing::internal::TestResultAccessor::test_part_results().
 { return line_number_; }
const char* testing::TestPartResult::message () const inline
Definition at line 88 of file gtest-test-part.h.
Referenced by testing::internal::HasOneFailure(), testing::operator<<(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PortableLocaltime(), testing::internal::PrintTestPartResultToString(), testing::internal::ShouldRunTestCase(), and testing::internal::TestResultAccessor::test_part_results().
 { return message_.c_str(); }
const char* testing::TestPartResult::message () const inline
Definition at line 88 of file gtest-test-part.h.
 { return message_.c_str(); }
const char* testing::TestPartResult::message () const inline
Definition at line 88 of file gtest-test-part.h.
 { return message_.c_str(); }
bool testing::TestPartResult::nonfatally_failed () const inline
Definition at line 97 of file gtest-test-part.h.
References type_.
 { return type_ == kNonFatalFailure; }
bool testing::TestPartResult::nonfatally_failed () const inline
Definition at line 97 of file gtest-test-part.h.
References type_.
Referenced by operator<<(), and testing::TestPartNonfatallyFailed().
 { return type_ == kNonFatalFailure; }
bool testing::TestPartResult::nonfatally_failed () const inline
Definition at line 97 of file gtest-test-part.h.
References type_.
 { return type_ == kNonFatalFailure; }
bool testing::TestPartResult::passed () const inline
Definition at line 91 of file gtest-test-part.h.
References type_.
 { return type_ == kSuccess; }
bool testing::TestPartResult::passed () const inline
Definition at line 91 of file gtest-test-part.h.
References type_.
 { return type_ == kSuccess; }
bool testing::TestPartResult::passed () const inline
Definition at line 91 of file gtest-test-part.h.
References type_.
 { return type_ == kSuccess; }
const char* testing::TestPartResult::summary () const inline
Definition at line 85 of file gtest-test-part.h.
Referenced by testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), and testing::internal::PortableLocaltime().
 { return summary_.c_str(); }
const char* testing::TestPartResult::summary () const inline
Definition at line 85 of file gtest-test-part.h.
 { return summary_.c_str(); }
const char* testing::TestPartResult::summary () const inline
Definition at line 85 of file gtest-test-part.h.
 { return summary_.c_str(); }
Type testing::TestPartResult::type () const inline
Definition at line 72 of file gtest-test-part.h.
References type_.
Referenced by testing::internal::HasOneFailure(), testing::internal::PrettyUnitTestResultPrinter::OnTestPartResult(), testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), testing::operator<<(), testing::internal::PrintTestPartResultToString(), and testing::internal::ShouldRunTestCase().
 { return type_; }
Type testing::TestPartResult::type () const inline
Definition at line 72 of file gtest-test-part.h.
References type_.
 { return type_; }
Type testing::TestPartResult::type () const inline
Definition at line 72 of file gtest-test-part.h.
References type_.
 { return type_; }
Member Data Documentation
std::string testing::TestPartResult::file_name_ private
Definition at line 111 of file gtest-test-part.h.
int testing::TestPartResult::line_number_ private
Definition at line 114 of file gtest-test-part.h.
std::string testing::TestPartResult::message_ private
Definition at line 116 of file gtest-test-part.h.
std::string testing::TestPartResult::summary_ private
Definition at line 115 of file gtest-test-part.h.
Type testing::TestPartResult::type_ private
Definition at line 103 of file gtest-test-part.h.
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/gtest-test-part.h
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest-test-part.cc