proxygen: pump.Env Class Reference
pump.Env Class Reference
Public Member Functions
def __init__ (self)
def Clone (self)
def PushVariable (self, var, value)
def PopVariable (self)
def PushRange (self, var, lower, upper)
def PopRange (self)
def GetValue (self, identifier)
def EvalExp (self, exp)
def GetRange (self, identifier)
def __init__ (self)
def Clone (self)
def PushVariable (self, var, value)
def PopVariable (self)
def PushRange (self, var, lower, upper)
def PopRange (self)
def GetValue (self, identifier)
def EvalExp (self, exp)
def GetRange (self, identifier)
def __init__ (self)
def Clone (self)
def PushVariable (self, var, value)
def PopVariable (self)
def PushRange (self, var, lower, upper)
def PopRange (self)
def GetValue (self, identifier)
def EvalExp (self, exp)
def GetRange (self, identifier)
Public Attributes
variables
ranges
Detailed Description
Definition at line 584 of file pump.py.
Constructor & Destructor Documentation
def pump.Env.__init__ (self)
Definition at line 585 of file pump.py.
Referenced by pump.Env.__init__().
   def __init__(self):
     self.variables = []
     self.ranges = []
def pump.Env.__init__ (self)
Definition at line 585 of file pump.py.
References pump.Env.__init__(), pump.Env.ranges, and pump.Env.variables.
   def __init__(self):
     self.variables = []
     self.ranges = []
def pump.Env.__init__ (self)
Definition at line 585 of file pump.py.
References pump.Env.__init__(), pump.Env.ranges, and pump.Env.variables.
   def __init__(self):
     self.variables = []
     self.ranges = []
Member Function Documentation
def pump.Env.Clone (self)
Definition at line 589 of file pump.py.
References pump.Env.ranges, and pump.Env.variables.
Referenced by pump.Env.Clone().
   def Clone(self):
     clone = Env()
     clone.variables = self.variables[:]
     clone.ranges = self.ranges[:]
     return clone
def pump.Env.Clone (self)
Definition at line 589 of file pump.py.
References pump.Env.Clone(), pump.Env.ranges, and pump.Env.variables.
   def Clone(self):
     clone = Env()
     clone.variables = self.variables[:]
     clone.ranges = self.ranges[:]
     return clone
def pump.Env.Clone (self)
Definition at line 589 of file pump.py.
References pump.Env.Clone(), pump.Env.ranges, and pump.Env.variables.
   def Clone(self):
     clone = Env()
     clone.variables = self.variables[:]
     clone.ranges = self.ranges[:]
     return clone
def pump.Env.EvalExp (self, exp)
Definition at line 622 of file pump.py.
References pump.Env.EvalExp().
   def EvalExp(self, exp):
     try:
       result = eval(exp.python_exp)
     except Exception, e:
       print 'ERROR: caught exception %s: %s' % (e.__class__.__name__, e)
       print ('ERROR: failed to evaluate meta expression %s at %s' %
              (exp.python_exp, exp.token.start))
       sys.exit(1)
     return result
def pump.Env.EvalExp (self, exp)
Definition at line 622 of file pump.py.
Referenced by pump.Env.EvalExp().
   def EvalExp(self, exp):
     try:
       result = eval(exp.python_exp)
     except Exception, e:
       print 'ERROR: caught exception %s: %s' % (e.__class__.__name__, e)
       print ('ERROR: failed to evaluate meta expression %s at %s' %
              (exp.python_exp, exp.token.start))
       sys.exit(1)
     return result
def pump.Env.EvalExp (self, exp)
Definition at line 622 of file pump.py.
References pump.Env.EvalExp().
   def EvalExp(self, exp):
     try:
       result = eval(exp.python_exp)
     except Exception, e:
       print 'ERROR: caught exception %s: %s' % (e.__class__.__name__, e)
       print ('ERROR: failed to evaluate meta expression %s at %s' %
              (exp.python_exp, exp.token.start))
       sys.exit(1)
     return result
def pump.Env.GetRange (self, identifier)
Definition at line 632 of file pump.py.
References pump.Env.ranges.
Referenced by pump.Env.GetRange().
   def GetRange(self, identifier):
     for (var, lower, upper) in self.ranges:
       if identifier == var:
         return (lower, upper)
     print 'ERROR: range %s is undefined.' % (identifier,)
     sys.exit(1)
def pump.Env.GetRange (self, identifier)
Definition at line 632 of file pump.py.
References pump.Env.GetRange(), and pump.Env.ranges.
   def GetRange(self, identifier):
     for (var, lower, upper) in self.ranges:
       if identifier == var:
         return (lower, upper)
     print 'ERROR: range %s is undefined.' % (identifier,)
     sys.exit(1)
def pump.Env.GetRange (self, identifier)
Definition at line 632 of file pump.py.
References pump.Env.GetRange(), and pump.Env.ranges.
   def GetRange(self, identifier):
     for (var, lower, upper) in self.ranges:
       if identifier == var:
         return (lower, upper)
     print 'ERROR: range %s is undefined.' % (identifier,)
     sys.exit(1)
def pump.Env.GetValue (self, identifier)
Definition at line 614 of file pump.py.
References pump.Env.GetValue(), and pump.Env.variables.
   def GetValue(self, identifier):
     for (var, value) in self.variables:
       if identifier == var:
         return value
     print 'ERROR: meta variable %s is undefined.' % (identifier,)
     sys.exit(1)
def pump.Env.GetValue (self, identifier)
Definition at line 614 of file pump.py.
References pump.Env.GetValue(), and pump.Env.variables.
   def GetValue(self, identifier):
     for (var, value) in self.variables:
       if identifier == var:
         return value
     print 'ERROR: meta variable %s is undefined.' % (identifier,)
     sys.exit(1)
def pump.Env.GetValue (self, identifier)
Definition at line 614 of file pump.py.
References pump.Env.variables.
Referenced by pump.Env.GetValue().
   def GetValue(self, identifier):
     for (var, value) in self.variables:
       if identifier == var:
         return value
     print 'ERROR: meta variable %s is undefined.' % (identifier,)
     sys.exit(1)
def pump.Env.PopRange (self)
Definition at line 611 of file pump.py.
References pump.Env.ranges.
Referenced by pump.Env.PopRange().
   def PopRange(self):
     self.ranges[:1] = []
def pump.Env.PopRange (self)
Definition at line 611 of file pump.py.
References pump.Env.PopRange(), and pump.Env.ranges.
   def PopRange(self):
     self.ranges[:1] = []
def pump.Env.PopRange (self)
Definition at line 611 of file pump.py.
References pump.Env.PopRange(), and pump.Env.ranges.
   def PopRange(self):
     self.ranges[:1] = []
def pump.Env.PopVariable (self)
Definition at line 605 of file pump.py.
References pump.Env.PopVariable(), and pump.Env.variables.
   def PopVariable(self):
     self.variables[:1] = []
def pump.Env.PopVariable (self)
Definition at line 605 of file pump.py.
References pump.Env.PopVariable(), and pump.Env.variables.
   def PopVariable(self):
     self.variables[:1] = []
def pump.Env.PopVariable (self)
Definition at line 605 of file pump.py.
References pump.Env.variables.
Referenced by pump.Env.PopVariable().
   def PopVariable(self):
     self.variables[:1] = []
def pump.Env.PushRange (self, var, lower, upper)
Definition at line 608 of file pump.py.
References pump.Env.ranges.
Referenced by pump.Env.PushRange().
   def PushRange(self, var, lower, upper):
     self.ranges[:0] = [(var, lower, upper)]
def pump.Env.PushRange (self, var, lower, upper)
Definition at line 608 of file pump.py.
References pump.Env.PushRange(), and pump.Env.ranges.
   def PushRange(self, var, lower, upper):
     self.ranges[:0] = [(var, lower, upper)]
def pump.Env.PushRange (self, var, lower, upper)
Definition at line 608 of file pump.py.
References pump.Env.PushRange(), and pump.Env.ranges.
   def PushRange(self, var, lower, upper):
     self.ranges[:0] = [(var, lower, upper)]
def pump.Env.PushVariable (self, var, value)
Definition at line 595 of file pump.py.
References pump.Env.variables.
Referenced by pump.Env.PushVariable().
   def PushVariable(self, var, value):
     # If value looks like an int, store it as an int.
     try:
       int_value = int(value)
       if ('%s' % int_value) == value:
         value = int_value
     except Exception:
       pass
     self.variables[:0] = [(var, value)]
def pump.Env.PushVariable (self, var, value)
Definition at line 595 of file pump.py.
References pump.Env.PushVariable(), and pump.Env.variables.
   def PushVariable(self, var, value):
     # If value looks like an int, store it as an int.
     try:
       int_value = int(value)
       if ('%s' % int_value) == value:
         value = int_value
     except Exception:
       pass
     self.variables[:0] = [(var, value)]
def pump.Env.PushVariable (self, var, value)
Definition at line 595 of file pump.py.
References pump.Env.PushVariable(), and pump.Env.variables.
   def PushVariable(self, var, value):
     # If value looks like an int, store it as an int.
     try:
       int_value = int(value)
       if ('%s' % int_value) == value:
         value = int_value
     except Exception:
       pass
     self.variables[:0] = [(var, value)]
Member Data Documentation
pump.Env.ranges
Definition at line 587 of file pump.py.
Referenced by pump.Env.__init__(), pump.Env.Clone(), pump.Env.GetRange(), pump.Env.PopRange(), and pump.Env.PushRange().
pump.Env.variables
Definition at line 586 of file pump.py.
Referenced by pump.Env.__init__(), pump.Env.Clone(), pump.Env.GetValue(), pump.Env.PopVariable(), and pump.Env.PushVariable().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/scripts/pump.py