proxygen: ConnectedWriteUDPClient Class Reference
ConnectedWriteUDPClient Class Reference
Public Member Functions
~ConnectedWriteUDPClient () override=default
ConnectedWriteUDPClient (EventBase *evb)
void writePing (std::unique_ptr< folly::IOBuf > buf) override
Public Member Functions inherited from UDPClient
UDPClient (EventBase *evb, TestData &testData)
void start (const folly::SocketAddress &server)
void connect ()
void shutdown ()
void sendPing ()
virtual void writePing (std::unique_ptr< folly::IOBuf > buf, int gso)
void getReadBuffer (void **buf, size_t *len) noexceptoverride
void onDataAvailable (const folly::SocketAddress &, size_t len, bool) noexceptoverride
void onReadError (const folly::AsyncSocketException &ex) noexceptoverride
void onReadClosed () noexceptoverride
void timeoutExpired () noexceptoverride
AsyncUDPSocket & getSocket ()
void setShouldConnect (const folly::SocketAddress &connectAddr)
UDPClient (EventBase *evb)
void start (const folly::SocketAddress &server, int n)
void connect ()
void shutdown ()
void sendPing ()
void getReadBuffer (void **buf, size_t *len) noexceptoverride
void onDataAvailable (const folly::SocketAddress &client, size_t len, bool truncated) noexceptoverride
void onReadError (const folly::AsyncSocketException &ex) noexceptoverride
void onReadClosed () noexceptoverride
void timeoutExpired () noexceptoverride
int pongRecvd () const
AsyncUDPSocket & getSocket ()
void setShouldConnect (const folly::SocketAddress &connectAddr)
Additional Inherited Members
Protected Attributes inherited from UDPClient
folly::Optional< folly::SocketAddress > connectAddr_
EventBase *const evb_ {nullptr}
folly::SocketAddress server_
std::unique_ptr< AsyncUDPSocket > socket_
Detailed Description
Definition at line 287 of file AsyncUDPSocketTest.cpp.
Constructor & Destructor Documentation
ConnectedWriteUDPClient::~ConnectedWriteUDPClient () override default
ConnectedWriteUDPClient::ConnectedWriteUDPClient (EventBase * evb) inline
Definition at line 291 of file AsyncUDPSocketTest.cpp.
 : UDPClient(evb) {}
Member Function Documentation
void ConnectedWriteUDPClient::writePing (std::unique_ptr< folly::IOBuf > buf) inline override virtual
Reimplemented from UDPClient.
Definition at line 295 of file AsyncUDPSocketTest.cpp.
References folly::IOBuf::coalesce(), folly::netops::connect(), folly::IOBuf::data(), folly::IOBuf::fillIov(), folly::IOBuf::length(), folly::AsyncSocketException::NOT_OPEN, folly::netops::sendmsg(), socket_, uint8_t, and UNLIKELY.
{
     iovec vec[16];
     size_t iovec_len = buf->fillIov(vec, sizeof(vec) / sizeof(vec[0]));
     if (UNLIKELY(iovec_len == 0)) {
       buf->coalesce();
       vec[0].iov_base = const_cast<uint8_t*>(buf->data());
       vec[0].iov_len = buf->length();
       iovec_len = 1;
     }
     struct msghdr msg;
     msg.msg_name = nullptr;
     msg.msg_namelen = 0;
     msg.msg_iov = const_cast<struct iovec*>(vec);
     msg.msg_iovlen = iovec_len;
     msg.msg_control = nullptr;
     msg.msg_controllen = 0;
     msg.msg_flags = 0;
     ssize_t ret = ::sendmsg(socket_->getFD(), &msg, 0);
     if (ret == -1) {
       if (errno != EAGAIN || errno != EWOULDBLOCK) {
         throw folly::AsyncSocketException(
             folly::AsyncSocketException::NOT_OPEN, "WriteFail", errno);
       }
     }
     connect();
   }
The documentation for this class was generated from the following file:
proxygen/folly/folly/io/async/test/AsyncUDPSocketTest.cpp