proxygen: folly::detail::BufferedStat< DigestT, ClockT > Class Template Reference
folly::detail::BufferedStat< DigestT, ClockT > Class Template Reference abstract
#include <BufferedStat.h>
Classes
struct TimePointHolder
Public Types
using TimePoint = typename ClockT::time_point
Public Member Functions
BufferedStat ()=delete
BufferedStat (typename ClockT::duration bufferDuration, size_t bufferSize, size_t digestSize)
virtual ~BufferedStat ()
void append (double value, TimePoint now=ClockT::now())
void flush ()
Protected Member Functions
virtual void onNewDigest (DigestT digest, TimePoint newExpiry, TimePoint oldExpiry, const std::unique_lock< SharedMutex > &g)=0
std::unique_lock< SharedMutex > updateIfExpired (TimePoint now)
std::unique_lock< SharedMutex > update ()
Protected Attributes
const ClockT::duration bufferDuration_
std::atomic< TimePointHolder > expiry_
SharedMutex mutex_
Private Types
enum UpdateMode { UpdateMode::OnExpiry, UpdateMode::Now }
Private Member Functions
void doUpdate (TimePoint now, const std::unique_lock< SharedMutex > &g, UpdateMode updateMode)
TimePoint roundUp (TimePoint t)
Private Attributes
DigestBuilder< DigestT > digestBuilder_
Detailed Description
template<typename DigestT, typename ClockT>
class folly::detail::BufferedStat< DigestT, ClockT >
Definition at line 32 of file BufferedStat.h.
Member Typedef Documentation
template<typename DigestT, typename ClockT> using folly::detail::BufferedStat< DigestT, ClockT >::TimePoint = typename ClockT::time_point
Definition at line 34 of file BufferedStat.h.
Member Enumeration Documentation
template<typename DigestT, typename ClockT> enum folly::detail::BufferedStat::UpdateMode strong private
Enumerator
OnExpiry
Now
Definition at line 81 of file BufferedStat.h.
{
     OnExpiry,
     Now,
   };
Constructor & Destructor Documentation
template<typename DigestT, typename ClockT> folly::detail::BufferedStat< DigestT, ClockT >::BufferedStat () delete
template<typename DigestT , typename ClockT> folly::detail::BufferedStat< DigestT, ClockT >::BufferedStat (typename ClockT::duration bufferDuration, size_t bufferSize, size_t digestSize)
Definition at line 28 of file BufferedStat-defs.h.
References folly::detail::BufferedStat< DigestT, ClockT >::expiry_, now(), and folly::detail::BufferedStat< DigestT, ClockT >::roundUp().
     : bufferDuration_(bufferDuration), digestBuilder_(bufferSize, digestSize) {
   expiry_.store(
       TimePointHolder(roundUp(ClockT::now())), std::memory_order_relaxed);
 }
template<typename DigestT, typename ClockT> virtual folly::detail::BufferedStat< DigestT, ClockT >::~BufferedStat () inline virtual
Definition at line 43 of file BufferedStat.h.
 {}
Member Function Documentation
template<typename DigestT , typename ClockT > void folly::detail::BufferedStat< DigestT, ClockT >::append (double value, TimePoint now = ClockT::now())
Definition at line 38 of file BufferedStat-defs.h.
References folly::detail::BufferedStat< DigestT, ClockT >::digestBuilder_, folly::detail::BufferedStat< DigestT, ClockT >::doUpdate(), folly::detail::BufferedStat< DigestT, ClockT >::expiry_, g(), folly::detail::BufferedStat< DigestT, ClockT >::mutex_, folly::detail::BufferedStat< DigestT, ClockT >::OnExpiry, and UNLIKELY.
Referenced by folly::detail::BufferedStat< folly::TDigest, ClockT >::~BufferedStat().
{
   if (UNLIKELY(now > expiry_.load(std::memory_order_relaxed).tp)) {
     std::unique_lock<SharedMutex> g(mutex_, std::try_to_lock_t());
     if (g.owns_lock()) {
       doUpdate(now, g, UpdateMode::OnExpiry);
     }
   }
   digestBuilder_.append(value);
 }
template<typename DigestT , typename ClockT > void folly::detail::BufferedStat< DigestT, ClockT >::doUpdate (TimePoint now, const std::unique_lock< SharedMutex > & g, UpdateMode updateMode) private
Definition at line 73 of file BufferedStat-defs.h.
References folly::detail::BufferedStat< DigestT, ClockT >::digestBuilder_, folly::detail::BufferedStat< DigestT, ClockT >::expiry_, g(), now(), folly::detail::BufferedStat< DigestT, ClockT >::Now, folly::detail::BufferedStat< DigestT, ClockT >::onNewDigest(), and folly::detail::BufferedStat< DigestT, ClockT >::roundUp().
Referenced by folly::detail::BufferedStat< DigestT, ClockT >::append(), folly::detail::BufferedStat< DigestT, ClockT >::flush(), and folly::detail::BufferedStat< DigestT, ClockT >::updateIfExpired().
{
   DCHECK(g.owns_lock());
   // Check that no other thread has performed the slide after the check
   auto oldExpiry = expiry_.load(std::memory_order_relaxed).tp;
   if (now > oldExpiry || updateMode == UpdateMode::Now) {
     now = roundUp(now);
     expiry_.store(TimePointHolder(now), std::memory_order_relaxed);
     onNewDigest(digestBuilder_.build(), now, oldExpiry, g);
   }
 }
template<typename DigestT , typename ClockT > void folly::detail::BufferedStat< DigestT, ClockT >::flush ()
Definition at line 67 of file BufferedStat-defs.h.
References folly::detail::BufferedStat< DigestT, ClockT >::doUpdate(), g(), folly::detail::BufferedStat< DigestT, ClockT >::mutex_, now(), and folly::detail::BufferedStat< DigestT, ClockT >::Now.
Referenced by folly::detail::BufferedStat< folly::TDigest, ClockT >::~BufferedStat().
{
   std::unique_lock<SharedMutex> g(mutex_);
   doUpdate(ClockT::now(), g, UpdateMode::Now);
 }
template<typename DigestT, typename ClockT> virtual void folly::detail::BufferedStat< DigestT, ClockT >::onNewDigest (DigestT digest, TimePoint newExpiry, TimePoint oldExpiry, const std::unique_lock< SharedMutex > & g) protected pure virtual
Implemented in folly::detail::BufferedSlidingWindow< DigestT, ClockT >, folly::detail::BufferedSlidingWindow< folly::TDigest, ClockT >, folly::detail::BufferedDigest< DigestT, ClockT >, and folly::detail::BufferedDigest< folly::TDigest, ClockT >.
Referenced by folly::detail::BufferedStat< DigestT, ClockT >::doUpdate().
template<typename DigestT , typename ClockT > BufferedStat< DigestT, ClockT >::TimePoint folly::detail::BufferedStat< DigestT, ClockT >::roundUp (TimePoint t) private
Definition at line 50 of file BufferedStat-defs.h.
References folly::detail::BufferedStat< DigestT, ClockT >::bufferDuration_, and folly::pushmi::detail::t.
Referenced by folly::detail::BufferedStat< DigestT, ClockT >::BufferedStat(), and folly::detail::BufferedStat< DigestT, ClockT >::doUpdate().
{
   auto remainder = t.time_since_epoch() % bufferDuration_;
   if (remainder.count() != 0) {
     return t + bufferDuration_ - remainder;
   }
   return t;
 }
template<typename DigestT, typename ClockT> std::unique_lock<SharedMutex> folly::detail::BufferedStat< DigestT, ClockT >::update () protected
template<typename DigestT , typename ClockT > std::unique_lock< SharedMutex > folly::detail::BufferedStat< DigestT, ClockT >::updateIfExpired (TimePoint now) protected
Definition at line 59 of file BufferedStat-defs.h.
References folly::detail::BufferedStat< DigestT, ClockT >::doUpdate(), g(), folly::detail::BufferedStat< DigestT, ClockT >::mutex_, and folly::detail::BufferedStat< DigestT, ClockT >::OnExpiry.
Referenced by folly::detail::BufferedDigest< DigestT, ClockT >::get(), and folly::detail::BufferedSlidingWindow< DigestT, ClockT >::get().
                    {
   std::unique_lock<SharedMutex> g(mutex_);
   doUpdate(now, g, UpdateMode::OnExpiry);
   return g;
 }
Member Data Documentation
template<typename DigestT, typename ClockT> const ClockT::duration folly::detail::BufferedStat< DigestT, ClockT >::bufferDuration_ protected
Definition at line 61 of file BufferedStat.h.
Referenced by folly::detail::BufferedSlidingWindow< DigestT, ClockT >::onNewDigest(), and folly::detail::BufferedStat< DigestT, ClockT >::roundUp().
template<typename DigestT, typename ClockT> DigestBuilder<DigestT> folly::detail::BufferedStat< DigestT, ClockT >::digestBuilder_ private
Definition at line 78 of file BufferedStat.h.
Referenced by folly::detail::BufferedStat< DigestT, ClockT >::append(), and folly::detail::BufferedStat< DigestT, ClockT >::doUpdate().
template<typename DigestT, typename ClockT> std::atomic<TimePointHolder> folly::detail::BufferedStat< DigestT, ClockT >::expiry_ protected
Definition at line 62 of file BufferedStat.h.
Referenced by folly::detail::BufferedStat< DigestT, ClockT >::append(), folly::detail::BufferedStat< DigestT, ClockT >::BufferedStat(), and folly::detail::BufferedStat< DigestT, ClockT >::doUpdate().
template<typename DigestT, typename ClockT> SharedMutex folly::detail::BufferedStat< DigestT, ClockT >::mutex_ protected
Definition at line 63 of file BufferedStat.h.
Referenced by folly::detail::BufferedStat< DigestT, ClockT >::append(), folly::detail::BufferedStat< DigestT, ClockT >::flush(), and folly::detail::BufferedStat< DigestT, ClockT >::updateIfExpired().
The documentation for this class was generated from the following files:
proxygen/folly/folly/stats/detail/BufferedStat.h
proxygen/folly/folly/stats/detail/BufferedStat-defs.h