proxygen: testing::internal::DoBothAction< Action1, Action2 >::Impl< F > Class Template Reference
testing::internal::DoBothAction< Action1, Action2 >::Impl< F > Class Template Reference
Public Types
typedef Function< F >::Result Result
typedef Function< F >::ArgumentTuple ArgumentTuple
typedef Function< F >::MakeResultVoid VoidResult
typedef Function< F >::Result Result
typedef Function< F >::ArgumentTuple ArgumentTuple
typedef Function< F >::MakeResultVoid VoidResult
typedef Function< F >::Result Result
typedef Function< F >::ArgumentTuple ArgumentTuple
typedef Function< F >::MakeResultVoid VoidResult
Public Types inherited from testing::ActionInterface< F >
typedef internal::Function< F >::Result Result
typedef internal::Function< F >::ArgumentTuple ArgumentTuple
typedef internal::Function< F >::Result Result
typedef internal::Function< F >::ArgumentTuple ArgumentTuple
typedef internal::Function< F >::Result Result
typedef internal::Function< F >::ArgumentTuple ArgumentTuple
Public Member Functions
Impl (const Action< VoidResult > &action1, const Action< F > &action2)
virtual Result Perform (const ArgumentTuple &args)
Impl (const Action< VoidResult > &action1, const Action< F > &action2)
virtual Result Perform (const ArgumentTuple &args)
Impl (const Action< VoidResult > &action1, const Action< F > &action2)
virtual Result Perform (const ArgumentTuple &args)
Public Member Functions inherited from testing::ActionInterface< F >
ActionInterface ()
virtual ~ActionInterface ()
ActionInterface ()
virtual ~ActionInterface ()
ActionInterface ()
virtual ~ActionInterface ()
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (Impl)
GTEST_DISALLOW_ASSIGN_ (Impl)
GTEST_DISALLOW_ASSIGN_ (Impl)
Private Attributes
const Action< VoidResult > action1_
const Action< F > action2_
Detailed Description
template<typename Action1, typename Action2>
template<typename F>
class testing::internal::DoBothAction< Action1, Action2 >::Impl< F >
Definition at line 987 of file gmock-actions.h.
Member Typedef Documentation
template<typename Action1, typename Action2> template<typename F > typedef Function<F>::ArgumentTuple testing::internal::DoBothAction< Action1, Action2 >::Impl< F >::ArgumentTuple
Definition at line 990 of file gmock-actions.h.
template<typename Action1, typename Action2> template<typename F > typedef Function<F>::ArgumentTuple testing::internal::DoBothAction< Action1, Action2 >::Impl< F >::ArgumentTuple
Definition at line 990 of file gmock-actions.h.
template<typename Action1, typename Action2> template<typename F > typedef Function<F>::ArgumentTuple testing::internal::DoBothAction< Action1, Action2 >::Impl< F >::ArgumentTuple
Definition at line 990 of file gmock-actions.h.
template<typename Action1, typename Action2> template<typename F > typedef Function<F>::Result testing::internal::DoBothAction< Action1, Action2 >::Impl< F >::Result
Definition at line 989 of file gmock-actions.h.
template<typename Action1, typename Action2> template<typename F > typedef Function<F>::Result testing::internal::DoBothAction< Action1, Action2 >::Impl< F >::Result
Definition at line 989 of file gmock-actions.h.
template<typename Action1, typename Action2> template<typename F > typedef Function<F>::Result testing::internal::DoBothAction< Action1, Action2 >::Impl< F >::Result
Definition at line 989 of file gmock-actions.h.
template<typename Action1, typename Action2> template<typename F > typedef Function<F>::MakeResultVoid testing::internal::DoBothAction< Action1, Action2 >::Impl< F >::VoidResult
Definition at line 991 of file gmock-actions.h.
template<typename Action1, typename Action2> template<typename F > typedef Function<F>::MakeResultVoid testing::internal::DoBothAction< Action1, Action2 >::Impl< F >::VoidResult
Definition at line 991 of file gmock-actions.h.
template<typename Action1, typename Action2> template<typename F > typedef Function<F>::MakeResultVoid testing::internal::DoBothAction< Action1, Action2 >::Impl< F >::VoidResult
Definition at line 991 of file gmock-actions.h.
Constructor & Destructor Documentation
template<typename Action1, typename Action2> template<typename F > testing::internal::DoBothAction< Action1, Action2 >::Impl< F >::Impl (const Action< VoidResult > & action1, const Action< F > & action2) inline
Definition at line 993 of file gmock-actions.h.
         : action1_(action1), action2_(action2) {}
template<typename Action1, typename Action2> template<typename F > testing::internal::DoBothAction< Action1, Action2 >::Impl< F >::Impl (const Action< VoidResult > & action1, const Action< F > & action2) inline
Definition at line 993 of file gmock-actions.h.
         : action1_(action1), action2_(action2) {}
template<typename Action1, typename Action2> template<typename F > testing::internal::DoBothAction< Action1, Action2 >::Impl< F >::Impl (const Action< VoidResult > & action1, const Action< F > & action2) inline
Definition at line 993 of file gmock-actions.h.
         : action1_(action1), action2_(action2) {}
Member Function Documentation
template<typename Action1, typename Action2> template<typename F > testing::internal::DoBothAction< Action1, Action2 >::Impl< F >::GTEST_DISALLOW_ASSIGN_ (Impl< F >) private
template<typename Action1, typename Action2> template<typename F > testing::internal::DoBothAction< Action1, Action2 >::Impl< F >::GTEST_DISALLOW_ASSIGN_ (Impl< F >) private
template<typename Action1, typename Action2> template<typename F > testing::internal::DoBothAction< Action1, Action2 >::Impl< F >::GTEST_DISALLOW_ASSIGN_ (Impl< F >) private
template<typename Action1, typename Action2> template<typename F > virtual Result testing::internal::DoBothAction< Action1, Action2 >::Impl< F >::Perform (const ArgumentTuple & args) inline virtual
Implements testing::ActionInterface< F >.
Definition at line 996 of file gmock-actions.h.
{
       action1_.Perform(args);
       return action2_.Perform(args);
     }
template<typename Action1, typename Action2> template<typename F > virtual Result testing::internal::DoBothAction< Action1, Action2 >::Impl< F >::Perform (const ArgumentTuple & args) inline virtual
Implements testing::ActionInterface< F >.
Definition at line 996 of file gmock-actions.h.
References testing::A(), testing::Action< F >::Action(), testing::Assign(), testing::ByMove(), testing::ByRef(), testing::DoDefault(), folly::pushmi::operators::from, GTEST_DISALLOW_ASSIGN_, testing::IgnoreResult(), testing::InvokeWithoutArgs(), testing::MakePolymorphicAction(), testing::internal::move(), ptr, testing::Return(), testing::ReturnNull(), testing::ReturnRef(), testing::ReturnRefOfCopy(), testing::SetArgPointee(), testing::SetArgumentPointee(), testing::SetErrnoAndReturn(), T, val, value, and x.
{
       action1_.Perform(args);
       return action2_.Perform(args);
     }
template<typename Action1, typename Action2> template<typename F > virtual Result testing::internal::DoBothAction< Action1, Action2 >::Impl< F >::Perform (const ArgumentTuple & args) inline virtual
Implements testing::ActionInterface< F >.
Definition at line 996 of file gmock-actions.h.
References testing::A(), testing::Action< F >::Action(), testing::Assign(), testing::ByMove(), testing::ByRef(), testing::DoDefault(), folly::pushmi::operators::from, GTEST_DISALLOW_ASSIGN_, testing::IgnoreResult(), testing::InvokeWithoutArgs(), testing::MakePolymorphicAction(), testing::internal::move(), ptr, testing::Return(), testing::ReturnNull(), testing::ReturnRef(), testing::ReturnRefOfCopy(), testing::SetArgPointee(), testing::SetArgumentPointee(), testing::SetErrnoAndReturn(), T, val, value, and x.
{
       action1_.Perform(args);
       return action2_.Perform(args);
     }
Member Data Documentation
template<typename Action1, typename Action2> template<typename F > const Action< VoidResult > testing::internal::DoBothAction< Action1, Action2 >::Impl< F >::action1_ private
Definition at line 1002 of file gmock-actions.h.
template<typename Action1, typename Action2> template<typename F > const Action< F > testing::internal::DoBothAction< Action1, Action2 >::Impl< F >::action2_ private
Definition at line 1003 of file gmock-actions.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-actions.h