proxygen: folly::Random Class Reference
folly::Random Class Reference
#include <Random.h>
Classes
class SecureRNG
Public Types
typedef std::mt19937 DefaultGenerator
Public Member Functions
template<class RNG , class >
auto create () -> RNG
Static Public Member Functions
static void secureRandom (void *data, size_t len)
template<class T >
static std::enable_if< std::is_integral< T >::value &&!std::is_same< T, bool >::value, T >::type secureRandom ()
static uint32_t secureRand32 ()
static uint32_t secureRand32 (uint32_t max)
static uint32_t secureRand32 (uint32_t min, uint32_t max)
static uint64_t secureRand64 ()
static uint64_t secureRand64 (uint64_t max)
static uint64_t secureRand64 (uint64_t min, uint64_t max)
static bool secureOneIn (uint32_t n)
static double secureRandDouble01 ()
static double secureRandDouble (double min, double max)
template<class RNG = DefaultGenerator, class = ValidRNG<RNG>>
static void seed (RNG &rng)
template<class RNG = DefaultGenerator, class = ValidRNG<RNG>>
static RNG create ()
static uint32_t rand32 ()
template<class RNG , class = ValidRNG<RNG>>
static uint32_t rand32 (RNG &&rng)
static uint32_t rand32 (uint32_t max)
template<class RNG = ThreadLocalPRNG, class = ValidRNG<RNG>>
static uint32_t rand32 (uint32_t max, RNG &&rng)
static uint32_t rand32 (uint32_t min, uint32_t max)
template<class RNG = ThreadLocalPRNG, class = ValidRNG<RNG>>
static uint32_t rand32 (uint32_t min, uint32_t max, RNG &&rng)
static uint64_t rand64 ()
template<class RNG = ThreadLocalPRNG, class = ValidRNG<RNG>>
static uint64_t rand64 (RNG &&rng)
static uint64_t rand64 (uint64_t max)
template<class RNG = ThreadLocalPRNG, class = ValidRNG<RNG>>
static uint64_t rand64 (uint64_t max, RNG &&rng)
static uint64_t rand64 (uint64_t min, uint64_t max)
template<class RNG = ThreadLocalPRNG, class = ValidRNG<RNG>>
static uint64_t rand64 (uint64_t min, uint64_t max, RNG &&rng)
static bool oneIn (uint32_t n)
template<class RNG = ThreadLocalPRNG, class = ValidRNG<RNG>>
static bool oneIn (uint32_t n, RNG &&rng)
static double randDouble01 ()
template<class RNG = ThreadLocalPRNG, class = ValidRNG<RNG>>
static double randDouble01 (RNG &&rng)
static double randDouble (double min, double max)
template<class RNG = ThreadLocalPRNG, class = ValidRNG<RNG>>
static double randDouble (double min, double max, RNG &&rng)
Private Types
template<class RNG >
using ValidRNG = typename std::enable_if< std::is_unsigned< invoke_result_t< RNG & >>::value, RNG >::type
Detailed Description
Definition at line 66 of file Random.h.
Member Typedef Documentation
typedef std::mt19937 folly::Random::DefaultGenerator
Definition at line 97 of file Random.h.
template<class RNG > using folly::Random::ValidRNG = typename std:: enable_if<std::is_unsigned<invoke_result_t<RNG&>>::value, RNG>::type private
Definition at line 70 of file Random.h.
Member Function Documentation
template<class RNG , class > auto folly::Random::create () -> RNG
Definition at line 80 of file Random-inl.h.
References folly::test::begin(), folly::test::end(), s, and folly::detail::SeedData< RNG >::seedData.
{
   detail::SeedData<RNG> sd;
   std::seed_seq s(std::begin(sd.seedData), std::end(sd.seedData));
   return RNG(s);
 }
template<class RNG = DefaultGenerator, class = ValidRNG<RNG>> static RNG folly::Random::create () static
Create a new RNG, seeded with a good seed.
Note that you should usually use ThreadLocalPRNG unless you need reproducibility (such as during a test), in which case you'd want to create a RNG with a good seed in production, and seed it yourself in test.
Referenced by folly::ThreadLocalPRNG::operator()().
static bool folly::Random::oneIn (uint32_t n) inline static
Returns true 1/n of the time. If n == 0, always returns false
Definition at line 311 of file Random.h.
Referenced by BENCHMARK(), folly::io::Codec::compress(), and folly::io::Codec::uncompress().
{
     return oneIn(n, ThreadLocalPRNG());
   }
template<class RNG = ThreadLocalPRNG, class = ValidRNG<RNG>> static bool folly::Random::oneIn (uint32_t n, RNG && rng) inline static
Returns true 1/n of the time. If n == 0, always returns false
Definition at line 319 of file Random.h.
{
     if (n == 0) {
       return false;
     }
     return rand32(0, n, rng) == 0;
   }
static uint32_t folly::Random::rand32 () inline static
Returns a random uint32_t
Definition at line 213 of file Random.h.
Referenced by accuracy_test(), folly::AtomicUnorderedInsertMap< Key, Value, Hash, KeyEqual, SkipKeyValueDeletion, Atom, IndexType, Allocator >::allocationAttempt(), alwaysInlineTestFunc(), arrayTestFunc(), BENCHMARK(), branchTestFunc(), concurrentOps(), concurrentPopforSharedBuffer(), concurrentPush(), concurrentSizeTest(), contendedRW(), DSchedMixedTest(), folly::test::DeterministicSchedule::getRandNumber(), makeBuf(), proxygen::makeBuf(), makeRandom(), manyArgTypesTestFunc(), folly::RelaxedConcurrentPriorityQueue< T, MayBlock, SupportsSize, PopBatch, ListTargetSize, Mutex, Atom >::moundPush(), multiPusherPopper(), pointerTestFunc(), AtomicBatchDispatcherTesting::Job::preprocess(), producer_consumer_test(), folly::randomNumberSeed(), setupCharVecBenchmark(), singleThreadTest(), structTestFunc(), folly::futures::test::TEST(), folly::TEST(), TEST(), TEST_F(), testRandom(), and throughtput_test().
{
     return rand32(ThreadLocalPRNG());
   }
template<class RNG , class = ValidRNG<RNG>> static uint32_t folly::Random::rand32 (RNG && rng) inline static
Returns a random uint32_t given a specific RNG
Definition at line 221 of file Random.h.
References rng.
{
     return rng();
   }
static uint32_t folly::Random::rand32 (uint32_t max) inline static
Returns a random uint32_t in [0, max). If max == 0, returns 0.
Definition at line 228 of file Random.h.
{
     return rand32(0, max, ThreadLocalPRNG());
   }
template<class RNG = ThreadLocalPRNG, class = ValidRNG<RNG>> static uint32_t folly::Random::rand32 (uint32_t max, RNG && rng) inline static
Returns a random uint32_t in [0, max) given a specific RNG. If max == 0, returns 0.
Definition at line 237 of file Random.h.
{
     return rand32(0, max, rng);
   }
static uint32_t folly::Random::rand32 (uint32_t min, uint32_t max) inline static
Returns a random uint32_t in [min, max). If min == max, returns 0.
Definition at line 244 of file Random.h.
{
     return rand32(min, max, ThreadLocalPRNG());
   }
template<class RNG = ThreadLocalPRNG, class = ValidRNG<RNG>> static uint32_t folly::Random::rand32 (uint32_t min, uint32_t max, RNG && rng) inline static
Returns a random uint32_t in [min, max) given a specific RNG. If min == max, returns 0.
Definition at line 253 of file Random.h.
References folly::ThreadLocalPRNG::min().
{
     if (min == max) {
       return 0;
     }
     return std::uniform_int_distribution<uint32_t>(min, max - 1)(rng);
   }
static uint64_t folly::Random::rand64 () inline static
Returns a random uint64_t
Definition at line 263 of file Random.h.
Referenced by folly::AtomicUnorderedInsertMap< Key, Value, Hash, KeyEqual, SkipKeyValueDeletion, Atom, IndexType, Allocator >::allocationAttempt(), BENCHMARK(), proxygen::HTTP2Codec::generatePingRequest(), fizz::server::test::generateRandomString(), main(), makeBuf(), proxygen::makeBuf(), folly::io::test::CompressionVarintTest::runSimpleTest(), folly::io::test::CompressionTest::split(), TEST(), and TEST_F().
{
     return rand64(ThreadLocalPRNG());
   }
template<class RNG = ThreadLocalPRNG, class = ValidRNG<RNG>> static uint64_t folly::Random::rand64 (RNG && rng) inline static
Returns a random uint64_t
Definition at line 271 of file Random.h.
References rng, and uint64_t.
{
     return ((uint64_t)rng() << 32) | rng();
   }
static uint64_t folly::Random::rand64 (uint64_t max) inline static
Returns a random uint64_t in [0, max). If max == 0, returns 0.
Definition at line 278 of file Random.h.
{
     return rand64(0, max, ThreadLocalPRNG());
   }
template<class RNG = ThreadLocalPRNG, class = ValidRNG<RNG>> static uint64_t folly::Random::rand64 (uint64_t max, RNG && rng) inline static
Returns a random uint64_t in [0, max). If max == 0, returns 0.
Definition at line 286 of file Random.h.
{
     return rand64(0, max, rng);
   }
static uint64_t folly::Random::rand64 (uint64_t min, uint64_t max) inline static
Returns a random uint64_t in [min, max). If min == max, returns 0.
Definition at line 293 of file Random.h.
{
     return rand64(min, max, ThreadLocalPRNG());
   }
template<class RNG = ThreadLocalPRNG, class = ValidRNG<RNG>> static uint64_t folly::Random::rand64 (uint64_t min, uint64_t max, RNG && rng) inline static
Returns a random uint64_t in [min, max). If min == max, returns 0.
Definition at line 301 of file Random.h.
References folly::ThreadLocalPRNG::min().
{
     if (min == max) {
       return 0;
     }
     return std::uniform_int_distribution<uint64_t>(min, max - 1)(rng);
   }
static double folly::Random::randDouble (double min, double max) inline static
Returns a double in [min, max), if min == max, returns 0.
Definition at line 345 of file Random.h.
Referenced by TEST().
{
     return randDouble(min, max, ThreadLocalPRNG());
   }
template<class RNG = ThreadLocalPRNG, class = ValidRNG<RNG>> static double folly::Random::randDouble (double min, double max, RNG && rng) inline static
Returns a double in [min, max), if min == max, returns 0.
Definition at line 353 of file Random.h.
References folly::ThreadLocalPRNG::max(), and folly::ThreadLocalPRNG::min().
{
     if (std::fabs(max - min) < std::numeric_limits<double>::epsilon()) {
       return 0;
     }
     return std::uniform_real_distribution<double>(min, max)(rng);
   }
static double folly::Random::randDouble01 () inline static
Returns a double in [0, 1)
Definition at line 329 of file Random.h.
Referenced by BENCHMARK().
{
     return randDouble01(ThreadLocalPRNG());
   }
template<class RNG = ThreadLocalPRNG, class = ValidRNG<RNG>> static double folly::Random::randDouble01 (RNG && rng) inline static
Returns a double in [0, 1)
Definition at line 337 of file Random.h.
References rng.
{
     return std::generate_canonical<double, std::numeric_limits<double>::digits>(
         rng);
   }
static bool folly::Random::secureOneIn (uint32_t n) inline static
Returns true 1/n of the time. If n == 0, always returns false
Definition at line 167 of file Random.h.
{
     SecureRNG<uint32_t> srng;
     return rand32(0, n, srng) == 0;
   }
static uint32_t folly::Random::secureRand32 () inline static
Returns a secure random uint32_t
Definition at line 121 of file Random.h.
{
     return secureRandom<uint32_t>();
   }
static uint32_t folly::Random::secureRand32 (uint32_t max) inline static
Returns a secure random uint32_t in [0, max). If max == 0, returns 0.
Definition at line 128 of file Random.h.
{
     SecureRNG<uint32_t> srng;
     return rand32(max, srng);
   }
static uint32_t folly::Random::secureRand32 (uint32_t min, uint32_t max) inline static
Returns a secure random uint32_t in [min, max). If min == max, returns 0.
Definition at line 136 of file Random.h.
{
     SecureRNG<uint32_t> srng;
     return rand32(min, max, srng);
   }
static uint64_t folly::Random::secureRand64 () inline static
Returns a secure random uint64_t
Definition at line 144 of file Random.h.
{
     return secureRandom<uint64_t>();
   }
static uint64_t folly::Random::secureRand64 (uint64_t max) inline static
Returns a secure random uint64_t in [0, max). If max == 0, returns 0.
Definition at line 151 of file Random.h.
{
     SecureRNG<uint64_t> srng;
     return rand64(max, srng);
   }
static uint64_t folly::Random::secureRand64 (uint64_t min, uint64_t max) inline static
Returns a secure random uint64_t in [min, max). If min == max, returns 0.
Definition at line 159 of file Random.h.
{
     SecureRNG<uint64_t> srng;
     return rand64(min, max, srng);
   }
static double folly::Random::secureRandDouble (double min, double max) inline static
Returns a secure double in [min, max), if min == max, returns 0.
Definition at line 183 of file Random.h.
References rng, and seed.
{
     SecureRNG<uint64_t> srng;
     return randDouble(min, max, srng);
   }
static double folly::Random::secureRandDouble01 () inline static
Returns a secure double in [0, 1)
Definition at line 175 of file Random.h.
{
     SecureRNG<uint64_t> srng;
     return randDouble01(srng);
   }
void Random::secureRandom (void * data, size_t len) static
Get secure random bytes. (On Linux and OSX, this means /dev/urandom).
Definition at line 159 of file Random.cpp.
References folly::pushmi::operators::get.
{
   using Single = SingletonThreadLocal<BufferedRandomDevice, RandomTag>;
   Single::get().get(data, size);
 }
template<class T > static std::enable_if< std::is_integral<T>::value && !std::is_same<T, bool>::value, T>::type folly::Random::secureRandom () inline static
Shortcut to get a secure random value of integral type.
Definition at line 112 of file Random.h.
References folly::T, and val.
Referenced by BENCHMARK(), proxygen::HTTP1xCodec::generateWebsocketKey(), folly::detail::SeedData< RNG >::SeedData(), wangle::ServerSocketConfig::ServerSocketConfig(), and TEST().
                  {
     T val;
     secureRandom(&val, sizeof(val));
     return val;
   }
template<class RNG , class > void Random::seed (RNG & rng) static
(Re-)Seed an existing RNG with a good seed.
Note that you should usually use ThreadLocalPRNG unless you need reproducibility (such as during a test), in which case you'd want to create a RNG with a good seed in production, and seed it yourself in test.
Definition at line 73 of file Random-inl.h.
References folly::test::begin(), folly::test::end(), s, and folly::detail::SeedData< RNG >::seedData.
{
   detail::SeedData<RNG> sd;
   std::seed_seq s(std::begin(sd.seedData), std::end(sd.seedData));
   rng.seed(s);
 }
The documentation for this class was generated from the following files:
proxygen/folly/folly/Random.h
proxygen/folly/folly/Random-inl.h
proxygen/folly/folly/Random.cpp