proxygen: QueueConsumer Class Reference
QueueConsumer Class Reference
Public Member Functions
QueueConsumer ()
void messageAvailable (int &&value) noexceptoverride
Public Member Functions inherited from folly::NotificationQueue< MessageT >::Consumer
Consumer ()
virtual void messageAvailable (MessageT &&message) noexcept=0
void startConsuming (EventBase *eventBase, NotificationQueue *queue)
void startConsumingInternal (EventBase *eventBase, NotificationQueue *queue)
void stopConsuming ()
bool consumeUntilDrained (size_t *numConsumed=nullptr) noexcept
NotificationQueue * getCurrentQueue () const
void setMaxReadAtOnce (uint32_t maxAtOnce)
uint32_t getMaxReadAtOnce () const
EventBase * getEventBase ()
void handlerReady (uint16_t events) noexceptoverride
template<typename TCallback >
std::unique_ptr< typename NotificationQueue< MessageT >::Consumer, DelayedDestruction::Destructor > make (TCallback &&callback)
Public Member Functions inherited from folly::DelayedDestruction
bool getDestroyPending () const
Public Member Functions inherited from folly::DelayedDestructionBase
virtual ~DelayedDestructionBase ()=default
Public Attributes
std::function< void(int)> fn
std::deque< int > messages
Additional Inherited Members
Public Types inherited from folly::NotificationQueue< MessageT >::Consumer
enum : uint16_t { kDefaultMaxReadAtOnce = 10 }
Static Public Member Functions inherited from folly::NotificationQueue< MessageT >::Consumer
template<typename TCallback >
static std::unique_ptr< Consumer, DelayedDestruction::Destructor > make (TCallback &&callback)
Protected Member Functions inherited from folly::NotificationQueue< MessageT >::Consumer
void destroy () override
~Consumer () override
Protected Member Functions inherited from folly::DelayedDestruction
~DelayedDestruction () override=default
DelayedDestruction ()
Protected Member Functions inherited from folly::DelayedDestructionBase
DelayedDestructionBase ()
uint32_t getDestructorGuardCount () const
Detailed Description
Definition at line 38 of file NotificationQueueTest.cpp.
Constructor & Destructor Documentation
QueueConsumer::QueueConsumer () inline
Definition at line 40 of file NotificationQueueTest.cpp.
 {}
Member Function Documentation
void QueueConsumer::messageAvailable (int && value) inline override noexcept
Definition at line 42 of file NotificationQueueTest.cpp.
References messages, and value.
{
     messages.push_back(value);
     if (fn) {
       fn(value);
     }
   }
Member Data Documentation
std::function<void(int)> QueueConsumer::fn
Definition at line 49 of file NotificationQueueTest.cpp.
Referenced by QueueTest::maxReadAtOnce(), QueueTest::multiConsumer(), QueueTest::putMessages(), QueueTest::sendOne(), and TEST().
std::deque<int> QueueConsumer::messages
Definition at line 50 of file NotificationQueueTest.cpp.
Referenced by QueueTest::maxReadAtOnce(), QueueTest::putMessages(), QueueTest::sendOne(), and TEST().
The documentation for this class was generated from the following file:
proxygen/folly/folly/io/async/test/NotificationQueueTest.cpp