proxygen: testing::gmock_matchers_test::Uncopyable Class Reference
testing::gmock_matchers_test::Uncopyable Class Reference
Public Member Functions
Uncopyable ()
Uncopyable (int a_value)
int value () const
void set_value (int i)
Uncopyable ()
Uncopyable (int a_value)
int value () const
void set_value (int i)
Uncopyable ()
Uncopyable (int a_value)
int value () const
void set_value (int i)
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (Uncopyable)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (Uncopyable)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (Uncopyable)
Private Attributes
int value_
Detailed Description
Definition at line 3357 of file gmock-matchers_test.cc.
Constructor & Destructor Documentation
testing::gmock_matchers_test::Uncopyable::Uncopyable () inline
Definition at line 3359 of file gmock-matchers_test.cc.
 : value_(-1) {}
testing::gmock_matchers_test::Uncopyable::Uncopyable (int a_value) inline explicit
Definition at line 3360 of file gmock-matchers_test.cc.
 : value_(a_value) {}
testing::gmock_matchers_test::Uncopyable::Uncopyable () inline
Definition at line 3359 of file gmock-matchers_test.cc.
 : value_(-1) {}
testing::gmock_matchers_test::Uncopyable::Uncopyable (int a_value) inline explicit
Definition at line 3360 of file gmock-matchers_test.cc.
 : value_(a_value) {}
testing::gmock_matchers_test::Uncopyable::Uncopyable () inline
Definition at line 3359 of file gmock-matchers_test.cc.
 : value_(-1) {}
testing::gmock_matchers_test::Uncopyable::Uncopyable (int a_value) inline explicit
Definition at line 3360 of file gmock-matchers_test.cc.
 : value_(a_value) {}
Member Function Documentation
testing::gmock_matchers_test::Uncopyable::GTEST_DISALLOW_COPY_AND_ASSIGN_ (Uncopyable) private
testing::gmock_matchers_test::Uncopyable::GTEST_DISALLOW_COPY_AND_ASSIGN_ (Uncopyable) private
testing::gmock_matchers_test::Uncopyable::GTEST_DISALLOW_COPY_AND_ASSIGN_ (Uncopyable) private
void testing::gmock_matchers_test::Uncopyable::set_value (int i) inline
Definition at line 3363 of file gmock-matchers_test.cc.
References testing::ExplainMatchResult(), GTEST_DISALLOW_COPY_AND_ASSIGN_, i, testing::gmock_matchers_test::MATCHER_P(), value(), and testing::gmock_matchers_test::ValueIsPositive().
 { value_ = i; }
void testing::gmock_matchers_test::Uncopyable::set_value (int i) inline
Definition at line 3363 of file gmock-matchers_test.cc.
References testing::ExplainMatchResult(), GTEST_DISALLOW_COPY_AND_ASSIGN_, i, testing::gmock_matchers_test::MATCHER_P(), value(), and testing::gmock_matchers_test::ValueIsPositive().
 { value_ = i; }
void testing::gmock_matchers_test::Uncopyable::set_value (int i) inline
Definition at line 3363 of file gmock-matchers_test.cc.
References i.
Referenced by testing::gmock_matchers_test::TEST(), and testing::gmock_matchers_test::TEST_F().
 { value_ = i; }
int testing::gmock_matchers_test::Uncopyable::value () const inline
Definition at line 3362 of file gmock-matchers_test.cc.
 { return value_; }
int testing::gmock_matchers_test::Uncopyable::value () const inline
Definition at line 3362 of file gmock-matchers_test.cc.
Referenced by set_value(), and testing::gmock_matchers_test::ValueIsPositive().
 { return value_; }
int testing::gmock_matchers_test::Uncopyable::value () const inline
Definition at line 3362 of file gmock-matchers_test.cc.
 { return value_; }
Member Data Documentation
int testing::gmock_matchers_test::Uncopyable::value_ private
Definition at line 3366 of file gmock-matchers_test.cc.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-matchers_test.cc