proxygen: folly::fibers::TaskIterator< T > Class Template Reference
folly::fibers::TaskIterator< T > Class Template Reference
#include <AddTasks.h>
Classes
struct Context
Public Types
typedef T value_type
Public Member Functions
TaskIterator ()
TaskIterator (const TaskIterator &other)=delete
TaskIterator & operator= (const TaskIterator &other)=delete
TaskIterator (TaskIterator &&other) noexcept
TaskIterator & operator= (TaskIterator &&other)=delete
template<typename F >
void addTask (F &&func)
bool hasCompleted () const
bool hasPending () const
bool hasNext () const
T awaitNext ()
void reserve (size_t n)
size_t getTaskID () const
template<>
void awaitNext ()
Private Member Functions
folly::Try< T > awaitNextResult ()
Private Attributes
std::shared_ptr< Context > context_ {std::make_shared<Context>()}
size_t id_ {std::numeric_limits<size_t>::max()}
FiberManager & fm_
Friends
template<class InputIterator >
TaskIterator< invoke_result_t< typename std::iterator_traits< InputIterator >::value_type > > addTasks (InputIterator first, InputIterator last)
Detailed Description
template<typename T>
class folly::fibers::TaskIterator< T >
Definition at line 30 of file AddTasks.h.
Member Typedef Documentation
template<typename T> typedef T folly::fibers::TaskIterator< T >::value_type
Definition at line 51 of file AddTasks.h.
Constructor & Destructor Documentation
template<typename T> folly::fibers::TaskIterator< T >::TaskIterator () inline
Definition at line 53 of file AddTasks.h.
References folly::fibers::TaskIterator< T >::addTask(), folly::fibers::TaskIterator< T >::addTasks, folly::fibers::TaskIterator< T >::awaitNext(), folly::gen::first, folly::fibers::TaskIterator< T >::getTaskID(), folly::fibers::TaskIterator< T >::hasCompleted(), folly::fibers::TaskIterator< T >::hasNext(), folly::fibers::TaskIterator< T >::hasPending(), folly::pushmi::__adl::noexcept(), folly::fibers::TaskIterator< T >::operator=(), folly::fibers::TaskIterator< T >::reserve(), and folly::T.
 : fm_(FiberManager::getFiberManager()) {}
template<typename T> folly::fibers::TaskIterator< T >::TaskIterator (const TaskIterator< T > & other) delete
template<typename T > folly::fibers::TaskIterator< T >::TaskIterator (TaskIterator< T > && other) noexcept
Definition at line 23 of file AddTasks-inl.h.
     : context_(std::move(other.context_)), id_(other.id_), fm_(other.fm_) {}
Member Function Documentation
template<typename T > template<typename F > void folly::fibers::TaskIterator< T >::addTask (F && func)
Add one more task to the TaskIterator.
Parameters
func task to be added, will be scheduled on current FiberManager
Definition at line 89 of file AddTasks-inl.h.
References context, folly::makeTryWith(), folly::gen::move, folly::T, and folly::value().
Referenced by folly::fibers::addTasks(), folly::fibers::TaskIterator< T >::TaskIterator(), and TEST().
{
   static_assert(
       std::is_convertible<invoke_result_t<F>, T>::value,
       "TaskIterator<T>: T must be convertible from func()'s return type");
   auto taskId = context_->totalTasks++;
   fm_.addTask(
       [taskId, context = context_, func = std::forward<F>(func)]() mutable {
         context->results.emplace_back(
             taskId, folly::makeTryWith(std::move(func)));
         // Check for awaiting iterator.
         if (context->promise.hasValue()) {
           if (--context->tasksToFulfillPromise == 0) {
             context->promise->setValue();
             context->promise.clear();
           }
         }
       });
 }
template<> void folly::fibers::TaskIterator< void >::awaitNext () inline
Definition at line 57 of file AddTasks-inl.h.
{
   awaitNextResult().value();
 }
template<typename T > T folly::fibers::TaskIterator< T >::awaitNext () inline
Await for another task to complete. Will not await if the result is already available.
Returns
result of the task completed.
Exceptions
exception thrown by the task.
Definition at line 52 of file AddTasks-inl.h.
References folly::gen::move, and folly::value().
Referenced by folly::fibers::TaskIterator< T >::TaskIterator(), and TEST().
{
   return std::move(awaitNextResult().value());
 }
template<typename T > folly::Try< T > folly::fibers::TaskIterator< T >::awaitNextResult () private
Definition at line 42 of file AddTasks-inl.h.
References i, folly::gen::move, and folly::reserve.
{
   assert(hasCompleted() || hasPending());
   reserve(1);
   size_t i = context_->tasksConsumed++;
   id_ = context_->results[i].first;
   return std::move(context_->results[i].second);
 }
template<typename T > size_t folly::fibers::TaskIterator< T >::getTaskID () const inline
Returns
id of the last task that was processed by awaitNext().
Definition at line 82 of file AddTasks-inl.h.
Referenced by folly::fibers::TaskIterator< T >::TaskIterator().
{
   assert(id_ != static_cast<size_t>(-1));
   return id_;
 }
template<typename T > bool folly::fibers::TaskIterator< T >::hasCompleted () const inline
Returns
True if there are tasks immediately available to be consumed (no need to await on them).
Definition at line 27 of file AddTasks-inl.h.
Referenced by folly::fibers::TaskIterator< T >::TaskIterator().
{
   return context_->tasksConsumed < context_->results.size();
 }
template<typename T > bool folly::fibers::TaskIterator< T >::hasNext () const inline
Returns
True if there are any tasks (hasCompleted() || hasPending()).
Definition at line 37 of file AddTasks-inl.h.
Referenced by folly::fibers::TaskIterator< T >::TaskIterator().
{
   return hasPending() || hasCompleted();
 }
template<typename T > bool folly::fibers::TaskIterator< T >::hasPending () const inline
Returns
True if there are tasks pending execution (need to awaited on).
Definition at line 32 of file AddTasks-inl.h.
Referenced by folly::fibers::TaskIterator< T >::TaskIterator().
{
   return !context_.unique();
 }
template<typename T> TaskIterator& folly::fibers::TaskIterator< T >::operator= (const TaskIterator< T > & other) delete
Referenced by folly::fibers::TaskIterator< T >::TaskIterator().
template<typename T> TaskIterator& folly::fibers::TaskIterator< T >::operator= (TaskIterator< T > && other) delete
template<typename T > void folly::fibers::TaskIterator< T >::reserve (size_t n) inline
Await until the specified number of tasks completes or there are no tasks left to await for. Note: Will not await if there are already the specified number of tasks available.
Parameters
n Number of tasks to await for completition.
Definition at line 62 of file AddTasks-inl.h.
References folly::fibers::await(), min, and folly::gen::move.
Referenced by folly::fibers::TaskIterator< T >::TaskIterator().
{
   size_t tasksReady = context_->results.size() - context_->tasksConsumed;
   // we don't need to do anything if there are already n or more tasks complete
   // or if we have no tasks left to execute.
   if (!hasPending() || tasksReady >= n) {
     return;
   }
   n -= tasksReady;
   size_t tasksLeft = context_->totalTasks - context_->results.size();
   n = std::min(n, tasksLeft);
   await([this, n](Promise<void> promise) {
     context_->tasksToFulfillPromise = n;
     context_->promise.assign(std::move(promise));
   });
 }
Friends And Related Function Documentation
template<typename T> template<class InputIterator > TaskIterator< invoke_result_t<typename std::iterator_traits<InputIterator>::value_type> > addTasks (InputIterator first, InputIterator last) friend
Schedules several tasks and immediately returns an iterator, that allow one to traverse tasks in the order of their completion. All results and exceptions thrown are stored alongside with the task id and are accessible via iterator.
Parameters
first Range of tasks to be scheduled
last
Returns
movable, non-copyable iterator
Definition at line 114 of file AddTasks-inl.h.
Referenced by folly::fibers::TaskIterator< T >::TaskIterator().
{
   typedef invoke_result_t<
       typename std::iterator_traits<InputIterator>::value_type>
       ResultType;
   typedef TaskIterator<ResultType> IteratorType;
   IteratorType iterator;
   for (; first != last; ++first) {
     iterator.addTask(std::move(*first));
   }
   iterator.context_->results.reserve(iterator.context_->totalTasks);
   return std::move(iterator);
 }
Member Data Documentation
template<typename T> std::shared_ptr<Context> folly::fibers::TaskIterator< T >::context_ {std::make_shared<Context>()} private
Definition at line 125 of file AddTasks.h.
template<typename T> FiberManager& folly::fibers::TaskIterator< T >::fm_ private
Definition at line 127 of file AddTasks.h.
template<typename T> size_t folly::fibers::TaskIterator< T >::id_ {std::numeric_limits<size_t>::max()} private
Definition at line 126 of file AddTasks.h.
The documentation for this class was generated from the following files:
proxygen/folly/folly/fibers/AddTasks.h
proxygen/folly/folly/fibers/AddTasks-inl.h