proxygen: testing::internal::UnitTestImpl Class Reference
testing::internal::UnitTestImpl Class Reference
#include <gtest-internal-inl.h>
Public Types
enum ReactionToSharding {
HONOR_SHARDING_PROTOCOL, IGNORE_SHARDING_PROTOCOL, HONOR_SHARDING_PROTOCOL, IGNORE_SHARDING_PROTOCOL,
HONOR_SHARDING_PROTOCOL, IGNORE_SHARDING_PROTOCOL
}
enum ReactionToSharding {
HONOR_SHARDING_PROTOCOL, IGNORE_SHARDING_PROTOCOL, HONOR_SHARDING_PROTOCOL, IGNORE_SHARDING_PROTOCOL,
HONOR_SHARDING_PROTOCOL, IGNORE_SHARDING_PROTOCOL
}
enum ReactionToSharding {
HONOR_SHARDING_PROTOCOL, IGNORE_SHARDING_PROTOCOL, HONOR_SHARDING_PROTOCOL, IGNORE_SHARDING_PROTOCOL,
HONOR_SHARDING_PROTOCOL, IGNORE_SHARDING_PROTOCOL
}
Public Member Functions
UnitTestImpl (UnitTest *parent)
virtual ~UnitTestImpl ()
TestPartResultReporterInterface * GetGlobalTestPartResultReporter ()
void SetGlobalTestPartResultReporter (TestPartResultReporterInterface *reporter)
TestPartResultReporterInterface * GetTestPartResultReporterForCurrentThread ()
void SetTestPartResultReporterForCurrentThread (TestPartResultReporterInterface *reporter)
int successful_test_case_count () const
int failed_test_case_count () const
int total_test_case_count () const
int test_case_to_run_count () const
int successful_test_count () const
int failed_test_count () const
int reportable_disabled_test_count () const
int disabled_test_count () const
int reportable_test_count () const
int total_test_count () const
int test_to_run_count () const
TimeInMillis start_timestamp () const
TimeInMillis elapsed_time () const
bool Passed () const
bool Failed () const
const TestCase * GetTestCase (int i) const
TestCase * GetMutableTestCase (int i)
TestEventListeners * listeners ()
TestResult * current_test_result ()
const TestResult * ad_hoc_test_result () const
void set_os_stack_trace_getter (OsStackTraceGetterInterface *getter)
OsStackTraceGetterInterface * os_stack_trace_getter ()
std::string CurrentOsStackTraceExceptTop (int skip_count) GTEST_NO_INLINE_
TestCase * GetTestCase (const char *test_case_name, const char *type_param, Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc)
void AddTestInfo (Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc, TestInfo *test_info)
void set_current_test_case (TestCase *a_current_test_case)
void set_current_test_info (TestInfo *a_current_test_info)
void RegisterParameterizedTests ()
bool RunAllTests ()
void ClearNonAdHocTestResult ()
void ClearAdHocTestResult ()
void RecordProperty (const TestProperty &test_property)
int FilterTests (ReactionToSharding shard_tests)
void ListTestsMatchingFilter ()
const TestCase * current_test_case () const
TestInfo * current_test_info ()
const TestInfo * current_test_info () const
std::vector< Environment * > & environments ()
std::vector< TraceInfo > & gtest_trace_stack ()
const std::vector< TraceInfo > & gtest_trace_stack () const
void ConfigureXmlOutput ()
void PostFlagParsingInit ()
int random_seed () const
internal::Random * random ()
void ShuffleTests ()
void UnshuffleTests ()
bool catch_exceptions () const
UnitTestImpl (UnitTest *parent)
virtual ~UnitTestImpl ()
TestPartResultReporterInterface * GetGlobalTestPartResultReporter ()
void SetGlobalTestPartResultReporter (TestPartResultReporterInterface *reporter)
TestPartResultReporterInterface * GetTestPartResultReporterForCurrentThread ()
void SetTestPartResultReporterForCurrentThread (TestPartResultReporterInterface *reporter)
int successful_test_case_count () const
int failed_test_case_count () const
int total_test_case_count () const
int test_case_to_run_count () const
int successful_test_count () const
int failed_test_count () const
int reportable_disabled_test_count () const
int disabled_test_count () const
int reportable_test_count () const
int total_test_count () const
int test_to_run_count () const
TimeInMillis start_timestamp () const
TimeInMillis elapsed_time () const
bool Passed () const
bool Failed () const
const TestCase * GetTestCase (int i) const
TestCase * GetMutableTestCase (int i)
TestEventListeners * listeners ()
TestResult * current_test_result ()
const TestResult * ad_hoc_test_result () const
void set_os_stack_trace_getter (OsStackTraceGetterInterface *getter)
OsStackTraceGetterInterface * os_stack_trace_getter ()
std::string CurrentOsStackTraceExceptTop (int skip_count) GTEST_NO_INLINE_
TestCase * GetTestCase (const char *test_case_name, const char *type_param, Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc)
void AddTestInfo (Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc, TestInfo *test_info)
void set_current_test_case (TestCase *a_current_test_case)
void set_current_test_info (TestInfo *a_current_test_info)
void RegisterParameterizedTests ()
bool RunAllTests ()
void ClearNonAdHocTestResult ()
void ClearAdHocTestResult ()
void RecordProperty (const TestProperty &test_property)
int FilterTests (ReactionToSharding shard_tests)
void ListTestsMatchingFilter ()
const TestCase * current_test_case () const
TestInfo * current_test_info ()
const TestInfo * current_test_info () const
std::vector< Environment * > & environments ()
std::vector< TraceInfo > & gtest_trace_stack ()
const std::vector< TraceInfo > & gtest_trace_stack () const
void ConfigureXmlOutput ()
void PostFlagParsingInit ()
int random_seed () const
internal::Random * random ()
void ShuffleTests ()
void UnshuffleTests ()
bool catch_exceptions () const
UnitTestImpl (UnitTest *parent)
virtual ~UnitTestImpl ()
TestPartResultReporterInterface * GetGlobalTestPartResultReporter ()
void SetGlobalTestPartResultReporter (TestPartResultReporterInterface *reporter)
TestPartResultReporterInterface * GetTestPartResultReporterForCurrentThread ()
void SetTestPartResultReporterForCurrentThread (TestPartResultReporterInterface *reporter)
int successful_test_case_count () const
int failed_test_case_count () const
int total_test_case_count () const
int test_case_to_run_count () const
int successful_test_count () const
int failed_test_count () const
int reportable_disabled_test_count () const
int disabled_test_count () const
int reportable_test_count () const
int total_test_count () const
int test_to_run_count () const
TimeInMillis start_timestamp () const
TimeInMillis elapsed_time () const
bool Passed () const
bool Failed () const
const TestCase * GetTestCase (int i) const
TestCase * GetMutableTestCase (int i)
TestEventListeners * listeners ()
TestResult * current_test_result ()
const TestResult * ad_hoc_test_result () const
void set_os_stack_trace_getter (OsStackTraceGetterInterface *getter)
OsStackTraceGetterInterface * os_stack_trace_getter ()
std::string CurrentOsStackTraceExceptTop (int skip_count) GTEST_NO_INLINE_
TestCase * GetTestCase (const char *test_case_name, const char *type_param, Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc)
void AddTestInfo (Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc, TestInfo *test_info)
void set_current_test_case (TestCase *a_current_test_case)
void set_current_test_info (TestInfo *a_current_test_info)
void RegisterParameterizedTests ()
bool RunAllTests ()
void ClearNonAdHocTestResult ()
void ClearAdHocTestResult ()
void RecordProperty (const TestProperty &test_property)
int FilterTests (ReactionToSharding shard_tests)
void ListTestsMatchingFilter ()
const TestCase * current_test_case () const
TestInfo * current_test_info ()
const TestInfo * current_test_info () const
std::vector< Environment * > & environments ()
std::vector< TraceInfo > & gtest_trace_stack ()
const std::vector< TraceInfo > & gtest_trace_stack () const
void ConfigureXmlOutput ()
void PostFlagParsingInit ()
int random_seed () const
internal::Random * random ()
void ShuffleTests ()
void UnshuffleTests ()
bool catch_exceptions () const
Private Member Functions
void set_catch_exceptions (bool value)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (UnitTestImpl)
void set_catch_exceptions (bool value)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (UnitTestImpl)
void set_catch_exceptions (bool value)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (UnitTestImpl)
Private Attributes
UnitTest *const parent_
internal::FilePath original_working_dir_
DefaultGlobalTestPartResultReporter default_global_test_part_result_reporter_
DefaultPerThreadTestPartResultReporter default_per_thread_test_part_result_reporter_
TestPartResultReporterInterface * global_test_part_result_repoter_
internal::Mutex global_test_part_result_reporter_mutex_
internal::ThreadLocal< TestPartResultReporterInterface * > per_thread_test_part_result_reporter_
std::vector< Environment * > environments_
std::vector< TestCase * > test_cases_
std::vector< int > test_case_indices_
int last_death_test_case_
TestCase * current_test_case_
TestInfo * current_test_info_
TestResult ad_hoc_test_result_
TestEventListeners listeners_
OsStackTraceGetterInterface * os_stack_trace_getter_
bool post_flag_parse_init_performed_
int random_seed_
internal::Random random_
TimeInMillis start_timestamp_
TimeInMillis elapsed_time_
internal::ThreadLocal< std::vector< TraceInfo > > gtest_trace_stack_
bool catch_exceptions_
Friends
class ::testing::UnitTest
Detailed Description
Definition at line 499 of file gtest-internal-inl.h.
Member Enumeration Documentation
enum testing::internal::UnitTestImpl::ReactionToSharding
Enumerator
HONOR_SHARDING_PROTOCOL
IGNORE_SHARDING_PROTOCOL
HONOR_SHARDING_PROTOCOL
IGNORE_SHARDING_PROTOCOL
HONOR_SHARDING_PROTOCOL
IGNORE_SHARDING_PROTOCOL
Definition at line 717 of file gtest-internal-inl.h.
{
     HONOR_SHARDING_PROTOCOL,
     IGNORE_SHARDING_PROTOCOL
   };
enum testing::internal::UnitTestImpl::ReactionToSharding
Enumerator
HONOR_SHARDING_PROTOCOL
IGNORE_SHARDING_PROTOCOL
HONOR_SHARDING_PROTOCOL
IGNORE_SHARDING_PROTOCOL
HONOR_SHARDING_PROTOCOL
IGNORE_SHARDING_PROTOCOL
Definition at line 717 of file gtest-internal-inl.h.
{
     HONOR_SHARDING_PROTOCOL,
     IGNORE_SHARDING_PROTOCOL
   };
enum testing::internal::UnitTestImpl::ReactionToSharding
Enumerator
HONOR_SHARDING_PROTOCOL
IGNORE_SHARDING_PROTOCOL
HONOR_SHARDING_PROTOCOL
IGNORE_SHARDING_PROTOCOL
HONOR_SHARDING_PROTOCOL
IGNORE_SHARDING_PROTOCOL
Definition at line 717 of file gtest-internal-inl.h.
{
     HONOR_SHARDING_PROTOCOL,
     IGNORE_SHARDING_PROTOCOL
   };
Constructor & Destructor Documentation
testing::internal::UnitTestImpl::UnitTestImpl (UnitTest * parent) explicit
Definition at line 4325 of file gtest.cc.
References listeners(), and testing::TestEventListeners::SetDefaultResultPrinter().
Referenced by testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
     : parent_(parent),
       GTEST_DISABLE_MSC_WARNINGS_PUSH_(4355 /* using this in initializer */)
       default_global_test_part_result_reporter_(this),
       default_per_thread_test_part_result_reporter_(this),
       GTEST_DISABLE_MSC_WARNINGS_POP_()
       global_test_part_result_repoter_(
           &default_global_test_part_result_reporter_),
       per_thread_test_part_result_reporter_(
           &default_per_thread_test_part_result_reporter_),
 #if GTEST_HAS_PARAM_TEST
       parameterized_test_registry_(),
       parameterized_tests_registered_(false),
 #endif  // GTEST_HAS_PARAM_TEST
       last_death_test_case_(-1),
       current_test_case_(NULL),
       current_test_info_(NULL),
       ad_hoc_test_result_(),
       os_stack_trace_getter_(NULL),
       post_flag_parse_init_performed_(false),
       random_seed_(0),  // Will be overridden by the flag before first use.
       random_(0),  // Will be reseeded before first use.
       start_timestamp_(0),
       elapsed_time_(0),
 #if GTEST_HAS_DEATH_TEST
       death_test_factory_(new DefaultDeathTestFactory),
 #endif
       // Will be overridden by the flag before first use.
       catch_exceptions_(false) {
   listeners()->SetDefaultResultPrinter(new PrettyUnitTestResultPrinter);
 }
testing::internal::UnitTestImpl::~UnitTestImpl () virtual
Definition at line 4357 of file gtest.cc.
References environments_, testing::internal::ForEach(), os_stack_trace_getter_, and test_cases_.
Referenced by testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   // Deletes every TestCase.
   ForEach(test_cases_, internal::Delete<TestCase>);
   // Deletes every Environment.
   ForEach(environments_, internal::Delete<Environment>);
   delete os_stack_trace_getter_;
 }
testing::internal::UnitTestImpl::UnitTestImpl (UnitTest * parent) explicit
virtual testing::internal::UnitTestImpl::~UnitTestImpl () virtual
testing::internal::UnitTestImpl::UnitTestImpl (UnitTest * parent) explicit
virtual testing::internal::UnitTestImpl::~UnitTestImpl () virtual
Member Function Documentation
const TestResult* testing::internal::UnitTestImpl::ad_hoc_test_result () const inline
Definition at line 597 of file gtest-internal-inl.h.
References GTEST_NO_INLINE_, and string.
 { return &ad_hoc_test_result_; }
const TestResult* testing::internal::UnitTestImpl::ad_hoc_test_result () const inline
Definition at line 597 of file gtest-internal-inl.h.
References GTEST_NO_INLINE_, and string.
 { return &ad_hoc_test_result_; }
const TestResult* testing::internal::UnitTestImpl::ad_hoc_test_result () const inline
Definition at line 597 of file gtest-internal-inl.h.
References GTEST_NO_INLINE_, and string.
 { return &ad_hoc_test_result_; }
void testing::internal::UnitTestImpl::AddTestInfo (Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc, TestInfo * test_info) inline
Definition at line 645 of file gtest-internal-inl.h.
References testing::internal::FilePath::GetCurrentDir(), GTEST_CHECK_, original_working_dir_, testing::TestInfo::test_case_name(), and testing::TestInfo::type_param().
{
     // In order to support thread-safe death tests, we need to
     // remember the original working directory when the test program
     // was first invoked.  We cannot do this in RUN_ALL_TESTS(), as
     // the user may have changed the current directory before calling
     // RUN_ALL_TESTS().  Therefore we capture the current directory in
     // AddTestInfo(), which is called to register a TEST or TEST_F
     // before main() is reached.
     if (original_working_dir_.IsEmpty()) {
       original_working_dir_.Set(FilePath::GetCurrentDir());
       GTEST_CHECK_(!original_working_dir_.IsEmpty())
           << "Failed to get the current working directory.";
     }
     GetTestCase(test_info->test_case_name(),
                 test_info->type_param(),
                 set_up_tc,
                 tear_down_tc)->AddTestInfo(test_info);
   }
void testing::internal::UnitTestImpl::AddTestInfo (Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc, TestInfo * test_info) inline
Definition at line 645 of file gtest-internal-inl.h.
References testing::internal::FilePath::GetCurrentDir(), GTEST_CHECK_, original_working_dir_, testing::TestInfo::test_case_name(), and testing::TestInfo::type_param().
{
     // In order to support thread-safe death tests, we need to
     // remember the original working directory when the test program
     // was first invoked.  We cannot do this in RUN_ALL_TESTS(), as
     // the user may have changed the current directory before calling
     // RUN_ALL_TESTS().  Therefore we capture the current directory in
     // AddTestInfo(), which is called to register a TEST or TEST_F
     // before main() is reached.
     if (original_working_dir_.IsEmpty()) {
       original_working_dir_.Set(FilePath::GetCurrentDir());
       GTEST_CHECK_(!original_working_dir_.IsEmpty())
           << "Failed to get the current working directory.";
     }
     GetTestCase(test_info->test_case_name(),
                 test_info->type_param(),
                 set_up_tc,
                 tear_down_tc)->AddTestInfo(test_info);
   }
void testing::internal::UnitTestImpl::AddTestInfo (Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc, TestInfo * test_info) inline
Definition at line 645 of file gtest-internal-inl.h.
References testing::internal::FilePath::GetCurrentDir(), GTEST_CHECK_, original_working_dir_, testing::TestInfo::test_case_name(), and testing::TestInfo::type_param().
Referenced by testing::internal::MakeAndRegisterTestInfo(), and testing::TestPartNonfatallyFailed().
{
     // In order to support thread-safe death tests, we need to
     // remember the original working directory when the test program
     // was first invoked.  We cannot do this in RUN_ALL_TESTS(), as
     // the user may have changed the current directory before calling
     // RUN_ALL_TESTS().  Therefore we capture the current directory in
     // AddTestInfo(), which is called to register a TEST or TEST_F
     // before main() is reached.
     if (original_working_dir_.IsEmpty()) {
       original_working_dir_.Set(FilePath::GetCurrentDir());
       GTEST_CHECK_(!original_working_dir_.IsEmpty())
           << "Failed to get the current working directory.";
     }
     GetTestCase(test_info->test_case_name(),
                 test_info->type_param(),
                 set_up_tc,
                 tear_down_tc)->AddTestInfo(test_info);
   }
bool testing::internal::UnitTestImpl::catch_exceptions () const inline
Definition at line 803 of file gtest-internal-inl.h.
References testing::internal::GTestFlagSaver::catch_exceptions_.
 { return catch_exceptions_; }
bool testing::internal::UnitTestImpl::catch_exceptions () const inline
Definition at line 803 of file gtest-internal-inl.h.
References testing::internal::GTestFlagSaver::catch_exceptions_.
Referenced by testing::internal::ParseGoogleTestFlag().
 { return catch_exceptions_; }
bool testing::internal::UnitTestImpl::catch_exceptions () const inline
Definition at line 803 of file gtest-internal-inl.h.
References testing::internal::GTestFlagSaver::catch_exceptions_.
 { return catch_exceptions_; }
void testing::internal::UnitTestImpl::ClearAdHocTestResult () inline
Definition at line 707 of file gtest-internal-inl.h.
{
     ad_hoc_test_result_.Clear();
   }
void testing::internal::UnitTestImpl::ClearAdHocTestResult () inline
Definition at line 707 of file gtest-internal-inl.h.
{
     ad_hoc_test_result_.Clear();
   }
void testing::internal::UnitTestImpl::ClearAdHocTestResult () inline
Definition at line 707 of file gtest-internal-inl.h.
{
     ad_hoc_test_result_.Clear();
   }
void testing::internal::UnitTestImpl::ClearNonAdHocTestResult () inline
Definition at line 702 of file gtest-internal-inl.h.
References testing::TestCase::ClearTestCaseResult(), and testing::internal::ForEach().
{
     ForEach(test_cases_, TestCase::ClearTestCaseResult);
   }
void testing::internal::UnitTestImpl::ClearNonAdHocTestResult () inline
Definition at line 702 of file gtest-internal-inl.h.
References testing::TestCase::ClearTestCaseResult(), and testing::internal::ForEach().
Referenced by RunAllTests().
{
     ForEach(test_cases_, TestCase::ClearTestCaseResult);
   }
void testing::internal::UnitTestImpl::ClearNonAdHocTestResult () inline
Definition at line 702 of file gtest-internal-inl.h.
References testing::TestCase::ClearTestCaseResult(), and testing::internal::ForEach().
{
     ForEach(test_cases_, TestCase::ClearTestCaseResult);
   }
void testing::internal::UnitTestImpl::ConfigureXmlOutput ()
void testing::internal::UnitTestImpl::ConfigureXmlOutput ()
Definition at line 4400 of file gtest.cc.
References testing::TestEventListeners::Append(), testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile(), testing::internal::UnitTestOptions::GetOutputFormat(), GTEST_FLAG, listeners(), testing::TestEventListeners::SetDefaultXmlGenerator(), and string.
Referenced by PostFlagParsingInit(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   const std::string& output_format = UnitTestOptions::GetOutputFormat();
   if (output_format == "xml") {
     listeners()->SetDefaultXmlGenerator(new XmlUnitTestResultPrinter(
         UnitTestOptions::GetAbsolutePathToOutputFile().c_str()));
   } else if (output_format != "") {
     printf("WARNING: unrecognized output format \"%s\" ignored.\n",
            output_format.c_str());
     fflush(stdout);
   }
 }
void testing::internal::UnitTestImpl::ConfigureXmlOutput ()
const TestCase* testing::internal::UnitTestImpl::current_test_case () const inline
Definition at line 733 of file gtest-internal-inl.h.
 { return current_test_case_; }
const TestCase* testing::internal::UnitTestImpl::current_test_case () const inline
Definition at line 733 of file gtest-internal-inl.h.
Referenced by testing::Test::HasSameFixtureClass(), and testing::TestPartNonfatallyFailed().
 { return current_test_case_; }
const TestCase* testing::internal::UnitTestImpl::current_test_case () const inline
Definition at line 733 of file gtest-internal-inl.h.
 { return current_test_case_; }
TestInfo* testing::internal::UnitTestImpl::current_test_info () inline
Definition at line 734 of file gtest-internal-inl.h.
 { return current_test_info_; }
TestInfo* testing::internal::UnitTestImpl::current_test_info () inline
Definition at line 734 of file gtest-internal-inl.h.
Referenced by testing::Test::HasSameFixtureClass(), and testing::TestPartNonfatallyFailed().
 { return current_test_info_; }
TestInfo* testing::internal::UnitTestImpl::current_test_info () inline
Definition at line 734 of file gtest-internal-inl.h.
 { return current_test_info_; }
const TestInfo* testing::internal::UnitTestImpl::current_test_info () const inline
Definition at line 735 of file gtest-internal-inl.h.
 { return current_test_info_; }
const TestInfo* testing::internal::UnitTestImpl::current_test_info () const inline
Definition at line 735 of file gtest-internal-inl.h.
 { return current_test_info_; }
const TestInfo* testing::internal::UnitTestImpl::current_test_info () const inline
Definition at line 735 of file gtest-internal-inl.h.
 { return current_test_info_; }
TestResult* testing::internal::UnitTestImpl::current_test_result ()
TestResult* testing::internal::UnitTestImpl::current_test_result ()
TestResult * testing::internal::UnitTestImpl::current_test_result ()
Definition at line 4932 of file gtest.cc.
References ad_hoc_test_result_, current_test_info_, and testing::TestInfo::result_.
Referenced by testing::Test::HasFatalFailure(), testing::Test::HasNonfatalFailure(), testing::internal::PrintOnOneLine(), testing::internal::DefaultGlobalTestPartResultReporter::ReportTestPartResult(), and testing::TestPartNonfatallyFailed().
{
   return current_test_info_ ?
       &(current_test_info_->result_) : &ad_hoc_test_result_;
 }
std::string testing::internal::UnitTestImpl::CurrentOsStackTraceExceptTop (int skip_count)
std::string testing::internal::UnitTestImpl::CurrentOsStackTraceExceptTop (int skip_count)
std::string testing::internal::UnitTestImpl::CurrentOsStackTraceExceptTop (int skip_count)
Definition at line 796 of file gtest.cc.
References GTEST_FLAG.
Referenced by testing::internal::GetCurrentOsStackTraceExceptTop(), testing::internal::AssertHelper::operator=(), testing::internal::PrintOnOneLine(), and testing::internal::ShouldRunTestCase().
{
   return os_stack_trace_getter()->CurrentStackTrace(
       static_cast<int>(GTEST_FLAG(stack_trace_depth)),
       skip_count + 1
       // Skips the user-specified number of frames plus this function
       // itself.
       );  // NOLINT
 }
int testing::internal::UnitTestImpl::disabled_test_count () const
Definition at line 767 of file gtest.cc.
References testing::TestCase::disabled_test_count(), and testing::internal::SumOverTestCaseList().
Referenced by testing::internal::ShouldRunTestCase().
{
   return SumOverTestCaseList(test_cases_, &TestCase::disabled_test_count);
 }
int testing::internal::UnitTestImpl::disabled_test_count () const
int testing::internal::UnitTestImpl::disabled_test_count () const
TimeInMillis testing::internal::UnitTestImpl::elapsed_time () const inline
Definition at line 564 of file gtest-internal-inl.h.
 { return elapsed_time_; }
TimeInMillis testing::internal::UnitTestImpl::elapsed_time () const inline
Definition at line 564 of file gtest-internal-inl.h.
 { return elapsed_time_; }
TimeInMillis testing::internal::UnitTestImpl::elapsed_time () const inline
Definition at line 564 of file gtest-internal-inl.h.
 { return elapsed_time_; }
std::vector<Environment*>& testing::internal::UnitTestImpl::environments () inline
Definition at line 739 of file gtest-internal-inl.h.
 { return environments_; }
std::vector<Environment*>& testing::internal::UnitTestImpl::environments () inline
Definition at line 739 of file gtest-internal-inl.h.
 { return environments_; }
std::vector<Environment*>& testing::internal::UnitTestImpl::environments () inline
Definition at line 739 of file gtest-internal-inl.h.
 { return environments_; }
bool testing::internal::UnitTestImpl::Failed () const inline
Definition at line 571 of file gtest-internal-inl.h.
                       {
     return failed_test_case_count() > 0 || ad_hoc_test_result()->Failed();
   }
bool testing::internal::UnitTestImpl::Failed () const inline
Definition at line 571 of file gtest-internal-inl.h.
                       {
     return failed_test_case_count() > 0 || ad_hoc_test_result()->Failed();
   }
bool testing::internal::UnitTestImpl::Failed () const inline
Definition at line 571 of file gtest-internal-inl.h.
                       {
     return failed_test_case_count() > 0 || ad_hoc_test_result()->Failed();
   }
int testing::internal::UnitTestImpl::failed_test_case_count () const
Definition at line 735 of file gtest.cc.
References testing::internal::CountIf(), and testing::internal::TestCaseFailed().
Referenced by testing::internal::ShouldRunTestCase().
{
   return CountIf(test_cases_, TestCaseFailed);
 }
int testing::internal::UnitTestImpl::failed_test_case_count () const
int testing::internal::UnitTestImpl::failed_test_case_count () const
int testing::internal::UnitTestImpl::failed_test_count () const
Definition at line 756 of file gtest.cc.
References testing::TestCase::failed_test_count(), and testing::internal::SumOverTestCaseList().
Referenced by testing::internal::ShouldRunTestCase().
{
   return SumOverTestCaseList(test_cases_, &TestCase::failed_test_count);
 }
int testing::internal::UnitTestImpl::failed_test_count () const
int testing::internal::UnitTestImpl::failed_test_count () const
int testing::internal::UnitTestImpl::FilterTests (ReactionToSharding shard_tests)
int testing::internal::UnitTestImpl::FilterTests (ReactionToSharding shard_tests)
Definition at line 4789 of file gtest.cc.
References testing::internal::UnitTestOptions::FilterMatchesTest(), GTEST_FLAG, HONOR_SHARDING_PROTOCOL, i, IGNORE_SHARDING_PROTOCOL, testing::internal::Int32FromEnvOrDie(), testing::TestInfo::is_disabled_, testing::TestInfo::matches_filter_, testing::internal::UnitTestOptions::MatchesFilter(), testing::TestInfo::name(), testing::TestCase::name(), testing::TestCase::set_should_run(), testing::TestCase::should_run(), testing::TestInfo::should_run_, testing::internal::ShouldRunTestOnShard(), string, test_cases_, and testing::TestCase::test_info_list().
Referenced by RunAllTests(), and testing::internal::TearDownEnvironment().
{
   const Int32 total_shards = shard_tests == HONOR_SHARDING_PROTOCOL ?
       Int32FromEnvOrDie(kTestTotalShards, -1) : -1;
   const Int32 shard_index = shard_tests == HONOR_SHARDING_PROTOCOL ?
       Int32FromEnvOrDie(kTestShardIndex, -1) : -1;
   // num_runnable_tests are the number of tests that will
   // run across all shards (i.e., match filter and are not disabled).
   // num_selected_tests are the number of tests to be run on
   // this shard.
   int num_runnable_tests = 0;
   int num_selected_tests = 0;
   for (size_t i = 0; i < test_cases_.size(); i++) {
     TestCase* const test_case = test_cases_[i];
     const std::string &test_case_name = test_case->name();
     test_case->set_should_run(false);
     for (size_t j = 0; j < test_case->test_info_list().size(); j++) {
       TestInfo* const test_info = test_case->test_info_list()[j];
       const std::string test_name(test_info->name());
       // A test is disabled if test case name or test name matches
       // kDisableTestFilter.
       const bool is_disabled =
           internal::UnitTestOptions::MatchesFilter(test_case_name,
                                                    kDisableTestFilter) ||
           internal::UnitTestOptions::MatchesFilter(test_name,
                                                    kDisableTestFilter);
       test_info->is_disabled_ = is_disabled;
       const bool matches_filter =
           internal::UnitTestOptions::FilterMatchesTest(test_case_name,
                                                        test_name);
       test_info->matches_filter_ = matches_filter;
       const bool is_runnable =
           (GTEST_FLAG(also_run_disabled_tests) || !is_disabled) &&
           matches_filter;
       const bool is_selected = is_runnable &&
           (shard_tests == IGNORE_SHARDING_PROTOCOL ||
            ShouldRunTestOnShard(total_shards, shard_index,
                                 num_runnable_tests));
       num_runnable_tests += is_runnable;
       num_selected_tests += is_selected;
       test_info->should_run_ = is_selected;
       test_case->set_should_run(test_case->should_run() || is_selected);
     }
   }
   return num_selected_tests;
 }
int testing::internal::UnitTestImpl::FilterTests (ReactionToSharding shard_tests)
TestPartResultReporterInterface * testing::internal::UnitTestImpl::GetGlobalTestPartResultReporter ()
Definition at line 705 of file gtest.cc.
References folly::detail::lock().
Referenced by testing::ScopedFakeTestPartResultReporter::Init(), testing::internal::DefaultPerThreadTestPartResultReporter::ReportTestPartResult(), and testing::internal::ShouldRunTestCase().
{
   internal::MutexLock lock(&global_test_part_result_reporter_mutex_);
   return global_test_part_result_repoter_;
 }
TestPartResultReporterInterface* testing::internal::UnitTestImpl::GetGlobalTestPartResultReporter ()
TestPartResultReporterInterface* testing::internal::UnitTestImpl::GetGlobalTestPartResultReporter ()
TestCase* testing::internal::UnitTestImpl::GetMutableTestCase (int i) inline
Definition at line 584 of file gtest-internal-inl.h.
References testing::internal::GetElementOr().
{
     const int index = GetElementOr(test_case_indices_, i, -1);
     return index < 0 ? NULL : test_cases_[index];
   }
TestCase* testing::internal::UnitTestImpl::GetMutableTestCase (int i) inline
Definition at line 584 of file gtest-internal-inl.h.
References testing::internal::GetElementOr().
Referenced by RunAllTests().
{
     const int index = GetElementOr(test_case_indices_, i, -1);
     return index < 0 ? NULL : test_cases_[index];
   }
TestCase* testing::internal::UnitTestImpl::GetMutableTestCase (int i) inline
Definition at line 584 of file gtest-internal-inl.h.
References testing::internal::GetElementOr().
{
     const int index = GetElementOr(test_case_indices_, i, -1);
     return index < 0 ? NULL : test_cases_[index];
   }
const TestCase* testing::internal::UnitTestImpl::GetTestCase (int i) const inline
Definition at line 577 of file gtest-internal-inl.h.
References testing::internal::GetElementOr(), and i.
{
     const int index = GetElementOr(test_case_indices_, i, -1);
     return index < 0 ? NULL : test_cases_[i];
   }
const TestCase* testing::internal::UnitTestImpl::GetTestCase (int i) const inline
Definition at line 577 of file gtest-internal-inl.h.
References testing::internal::GetElementOr(), and i.
Referenced by testing::internal::TestCaseNameIs::operator()().
{
     const int index = GetElementOr(test_case_indices_, i, -1);
     return index < 0 ? NULL : test_cases_[i];
   }
const TestCase* testing::internal::UnitTestImpl::GetTestCase (int i) const inline
Definition at line 577 of file gtest-internal-inl.h.
References testing::internal::GetElementOr(), and i.
{
     const int index = GetElementOr(test_case_indices_, i, -1);
     return index < 0 ? NULL : test_cases_[i];
   }
TestCase* testing::internal::UnitTestImpl::GetTestCase (const char * test_case_name, const char * type_param, Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc)
TestCase* testing::internal::UnitTestImpl::GetTestCase (const char * test_case_name, const char * type_param, Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc)
TestCase * testing::internal::UnitTestImpl::GetTestCase (const char * test_case_name, const char * type_param, Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc)
Definition at line 4502 of file gtest.cc.
References last_death_test_case_, testing::internal::UnitTestOptions::MatchesFilter(), test_case_indices_, test_cases_, and gmock_test_utils::TestCase.
{
   // Can we find a TestCase with the given name?
   const std::vector<TestCase*>::const_iterator test_case =
       std::find_if(test_cases_.begin(), test_cases_.end(),
                    TestCaseNameIs(test_case_name));
   if (test_case != test_cases_.end())
     return *test_case;
   // No.  Let's create one.
   TestCase* const new_test_case =
       new TestCase(test_case_name, type_param, set_up_tc, tear_down_tc);
   // Is this a death test case?
   if (internal::UnitTestOptions::MatchesFilter(test_case_name,
                                                kDeathTestCaseFilter)) {
     // Yes.  Inserts the test case after the last death test case
     // defined so far.  This only works when the test cases haven't
     // been shuffled.  Otherwise we may end up running a death test
     // after a non-death test.
     ++last_death_test_case_;
     test_cases_.insert(test_cases_.begin() + last_death_test_case_,
                        new_test_case);
   } else {
     // No.  Appends to the end of the list.
     test_cases_.push_back(new_test_case);
   }
   test_case_indices_.push_back(static_cast<int>(test_case_indices_.size()));
   return new_test_case;
 }
TestPartResultReporterInterface * testing::internal::UnitTestImpl::GetTestPartResultReporterForCurrentThread ()
Definition at line 719 of file gtest.cc.
Referenced by testing::ScopedFakeTestPartResultReporter::Init(), and testing::internal::ShouldRunTestCase().
{
   return per_thread_test_part_result_reporter_.get();
 }
TestPartResultReporterInterface* testing::internal::UnitTestImpl::GetTestPartResultReporterForCurrentThread ()
TestPartResultReporterInterface* testing::internal::UnitTestImpl::GetTestPartResultReporterForCurrentThread ()
testing::internal::UnitTestImpl::GTEST_DISALLOW_COPY_AND_ASSIGN_ (UnitTestImpl) private
testing::internal::UnitTestImpl::GTEST_DISALLOW_COPY_AND_ASSIGN_ (UnitTestImpl) private
testing::internal::UnitTestImpl::GTEST_DISALLOW_COPY_AND_ASSIGN_ (UnitTestImpl) private
std::vector<TraceInfo>& testing::internal::UnitTestImpl::gtest_trace_stack () inline
Definition at line 742 of file gtest-internal-inl.h.
{
     return *(gtest_trace_stack_.pointer());
   }
std::vector<TraceInfo>& testing::internal::UnitTestImpl::gtest_trace_stack () inline
Definition at line 742 of file gtest-internal-inl.h.
{
     return *(gtest_trace_stack_.pointer());
   }
std::vector<TraceInfo>& testing::internal::UnitTestImpl::gtest_trace_stack () inline
Definition at line 742 of file gtest-internal-inl.h.
{
     return *(gtest_trace_stack_.pointer());
   }
const std::vector<TraceInfo>& testing::internal::UnitTestImpl::gtest_trace_stack () const inline
Definition at line 745 of file gtest-internal-inl.h.
{
     return gtest_trace_stack_.get();
   }
const std::vector<TraceInfo>& testing::internal::UnitTestImpl::gtest_trace_stack () const inline
Definition at line 745 of file gtest-internal-inl.h.
{
     return gtest_trace_stack_.get();
   }
const std::vector<TraceInfo>& testing::internal::UnitTestImpl::gtest_trace_stack () const inline
Definition at line 745 of file gtest-internal-inl.h.
{
     return gtest_trace_stack_.get();
   }
TestEventListeners* testing::internal::UnitTestImpl::listeners () inline
Definition at line 590 of file gtest-internal-inl.h.
 { return &listeners_; }
TestEventListeners* testing::internal::UnitTestImpl::listeners () inline
Definition at line 590 of file gtest-internal-inl.h.
 { return &listeners_; }
TestEventListeners* testing::internal::UnitTestImpl::listeners () inline
Definition at line 590 of file gtest-internal-inl.h.
Referenced by ConfigureXmlOutput(), PostFlagParsingInit(), RecordProperty(), testing::internal::DefaultGlobalTestPartResultReporter::ReportTestPartResult(), RunAllTests(), and UnitTestImpl().
 { return &listeners_; }
void testing::internal::UnitTestImpl::ListTestsMatchingFilter ()
Definition at line 4865 of file gtest.cc.
References i, testing::TestInfo::matches_filter_, testing::TestInfo::name(), testing::TestCase::name(), testing::internal::PrintOnOneLine(), test_cases_, testing::TestCase::test_info_list(), testing::TestCase::type_param(), and testing::TestInfo::value_param().
Referenced by testing::internal::PrintOnOneLine(), and RunAllTests().
{
   // Print at most this many characters for each type/value parameter.
   const int kMaxParamLength = 250;
   for (size_t i = 0; i < test_cases_.size(); i++) {
     const TestCase* const test_case = test_cases_[i];
     bool printed_test_case_name = false;
     for (size_t j = 0; j < test_case->test_info_list().size(); j++) {
       const TestInfo* const test_info =
           test_case->test_info_list()[j];
       if (test_info->matches_filter_) {
         if (!printed_test_case_name) {
           printed_test_case_name = true;
           printf("%s.", test_case->name());
           if (test_case->type_param() != NULL) {
             printf("  # %s = ", kTypeParamLabel);
             // We print the type parameter on a single line to make
             // the output easy to parse by a program.
             PrintOnOneLine(test_case->type_param(), kMaxParamLength);
           }
           printf("\n");
         }
         printf("  %s", test_info->name());
         if (test_info->value_param() != NULL) {
           printf("  # %s = ", kValueParamLabel);
           // We print the value parameter on a single line to make the
           // output easy to parse by a program.
           PrintOnOneLine(test_info->value_param(), kMaxParamLength);
         }
         printf("\n");
       }
     }
   }
   fflush(stdout);
 }
void testing::internal::UnitTestImpl::ListTestsMatchingFilter ()
void testing::internal::UnitTestImpl::ListTestsMatchingFilter ()
OsStackTraceGetterInterface* testing::internal::UnitTestImpl::os_stack_trace_getter ()
OsStackTraceGetterInterface* testing::internal::UnitTestImpl::os_stack_trace_getter ()
OsStackTraceGetterInterface * testing::internal::UnitTestImpl::os_stack_trace_getter ()
Definition at line 4918 of file gtest.cc.
References os_stack_trace_getter_.
Referenced by testing::internal::PrintOnOneLine(), testing::Test::Run(), testing::TestInfo::Run(), testing::TestCase::Run(), and testing::TestPartNonfatallyFailed().
{
   if (os_stack_trace_getter_ == NULL) {
 #ifdef GTEST_OS_STACK_TRACE_GETTER_
     os_stack_trace_getter_ = new GTEST_OS_STACK_TRACE_GETTER_;
 #else
     os_stack_trace_getter_ = new OsStackTraceGetter;
 #endif  // GTEST_OS_STACK_TRACE_GETTER_
   }
   return os_stack_trace_getter_;
 }
bool testing::internal::UnitTestImpl::Passed () const inline
Definition at line 567 of file gtest-internal-inl.h.
Referenced by RunAllTests().
 { return !Failed(); }
bool testing::internal::UnitTestImpl::Passed () const inline
Definition at line 567 of file gtest-internal-inl.h.
 { return !Failed(); }
bool testing::internal::UnitTestImpl::Passed () const inline
Definition at line 567 of file gtest-internal-inl.h.
 { return !Failed(); }
void testing::internal::UnitTestImpl::PostFlagParsingInit ()
Definition at line 4436 of file gtest.cc.
References testing::TestEventListeners::Append(), ConfigureXmlOutput(), listeners(), post_flag_parse_init_performed_, and RegisterParameterizedTests().
Referenced by testing::internal::InitGoogleTestImpl(), RunAllTests(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   // Ensures that this function does not execute more than once.
   if (!post_flag_parse_init_performed_) {
     post_flag_parse_init_performed_ = true;
 #if defined(GTEST_CUSTOM_TEST_EVENT_LISTENER_)
     // Register to send notifications about key process state changes.
     listeners()->Append(new GTEST_CUSTOM_TEST_EVENT_LISTENER_());
 #endif  // defined(GTEST_CUSTOM_TEST_EVENT_LISTENER_)
 #if GTEST_HAS_DEATH_TEST
     InitDeathTestSubprocessControlInfo();
     SuppressTestEventsIfInSubprocess();
 #endif  // GTEST_HAS_DEATH_TEST
     // Registers parameterized tests. This makes parameterized tests
     // available to the UnitTest reflection API without running
     // RUN_ALL_TESTS.
     RegisterParameterizedTests();
     // Configures listeners for XML output. This makes it possible for users
     // to shut down the default XML output before invoking RUN_ALL_TESTS.
     ConfigureXmlOutput();
 #if GTEST_CAN_STREAM_RESULTS_
     // Configures listeners for streaming test results to the specified server.
     ConfigureStreamingOutput();
 #endif  // GTEST_CAN_STREAM_RESULTS_
   }
 }
void testing::internal::UnitTestImpl::PostFlagParsingInit ()
void testing::internal::UnitTestImpl::PostFlagParsingInit ()
internal::Random* testing::internal::UnitTestImpl::random () inline
Definition at line 792 of file gtest-internal-inl.h.
 { return &random_; }
internal::Random* testing::internal::UnitTestImpl::random () inline
Definition at line 792 of file gtest-internal-inl.h.
Referenced by RunAllTests(), and ShuffleTests().
 { return &random_; }
internal::Random* testing::internal::UnitTestImpl::random () inline
Definition at line 792 of file gtest-internal-inl.h.
 { return &random_; }
int testing::internal::UnitTestImpl::random_seed () const inline
Definition at line 789 of file gtest-internal-inl.h.
References testing::internal::GTestFlagSaver::random_seed_.
 { return random_seed_; }
int testing::internal::UnitTestImpl::random_seed () const inline
Definition at line 789 of file gtest-internal-inl.h.
References testing::internal::GTestFlagSaver::random_seed_.
Referenced by testing::internal::ParseGoogleTestFlag(), and RunAllTests().
 { return random_seed_; }
int testing::internal::UnitTestImpl::random_seed () const inline
Definition at line 789 of file gtest-internal-inl.h.
References testing::internal::GTestFlagSaver::random_seed_.
 { return random_seed_; }
void testing::internal::UnitTestImpl::RecordProperty (const TestProperty & test_property)
void testing::internal::UnitTestImpl::RecordProperty (const TestProperty & test_property)
Definition at line 4372 of file gtest.cc.
References ad_hoc_test_result_, testing::TestCase::ad_hoc_test_result_, current_test_case_, current_test_info_, listeners(), testing::TestResult::RecordProperty(), testing::TestInfo::result_, string, and testing::TestEventListeners::SuppressEventForwarding().
Referenced by testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   std::string xml_element;
   TestResult* test_result;  // TestResult appropriate for property recording.
   if (current_test_info_ != NULL) {
     xml_element = "testcase";
     test_result = &(current_test_info_->result_);
   } else if (current_test_case_ != NULL) {
     xml_element = "testsuite";
     test_result = &(current_test_case_->ad_hoc_test_result_);
   } else {
     xml_element = "testsuites";
     test_result = &ad_hoc_test_result_;
   }
   test_result->RecordProperty(xml_element, test_property);
 }
void testing::internal::UnitTestImpl::RecordProperty (const TestProperty & test_property)
void testing::internal::UnitTestImpl::RegisterParameterizedTests ()
void testing::internal::UnitTestImpl::RegisterParameterizedTests ()
Definition at line 2617 of file gtest.cc.
Referenced by PostFlagParsingInit().
{
 #if GTEST_HAS_PARAM_TEST
   if (!parameterized_tests_registered_) {
     parameterized_test_registry_.RegisterTests();
     parameterized_tests_registered_ = true;
   }
 #endif
 }
void testing::internal::UnitTestImpl::RegisterParameterizedTests ()
int testing::internal::UnitTestImpl::reportable_disabled_test_count () const
int testing::internal::UnitTestImpl::reportable_disabled_test_count () const
int testing::internal::UnitTestImpl::reportable_disabled_test_count () const
Definition at line 761 of file gtest.cc.
References testing::TestCase::reportable_disabled_test_count(), and testing::internal::SumOverTestCaseList().
Referenced by testing::internal::ShouldRunTestCase().
{
   return SumOverTestCaseList(test_cases_,
                              &TestCase::reportable_disabled_test_count);
 }
int testing::internal::UnitTestImpl::reportable_test_count () const
int testing::internal::UnitTestImpl::reportable_test_count () const
Definition at line 772 of file gtest.cc.
References testing::TestCase::reportable_test_count(), and testing::internal::SumOverTestCaseList().
Referenced by testing::internal::ShouldRunTestCase().
{
   return SumOverTestCaseList(test_cases_, &TestCase::reportable_test_count);
 }
int testing::internal::UnitTestImpl::reportable_test_count () const
bool testing::internal::UnitTestImpl::RunAllTests ()
Definition at line 4551 of file gtest.cc.
References ClearNonAdHocTestResult(), elapsed_time_, environments_, failed, FilterTests(), for_each(), testing::internal::ForEach(), forever, testing::internal::g_help_flag, GetMutableTestCase(), testing::internal::GetNextRandomSeed(), testing::internal::GetRandomSeedFromFlag(), testing::internal::GetTimeInMillis(), GTEST_FLAG, testing::internal::GTestIsInitialized(), testing::Test::HasFatalFailure(), HONOR_SHARDING_PROTOCOL, i, IGNORE_SHARDING_PROTOCOL, listeners(), ListTestsMatchingFilter(), testing::TestEventListener::OnEnvironmentsSetUpEnd(), testing::TestEventListener::OnEnvironmentsSetUpStart(), testing::TestEventListener::OnEnvironmentsTearDownEnd(), testing::TestEventListener::OnEnvironmentsTearDownStart(), testing::TestEventListener::OnTestIterationEnd(), testing::TestEventListener::OnTestIterationStart(), testing::TestEventListener::OnTestProgramEnd(), testing::TestEventListener::OnTestProgramStart(), parent_, Passed(), PostFlagParsingInit(), random(), random_seed(), random_seed_, repeat(), testing::TestEventListeners::repeater(), testing::internal::Random::Reseed(), testing::TestCase::Run(), testing::internal::SetUpEnvironment(), testing::internal::ShouldShard(), ShuffleTests(), start, start_timestamp_, testing::internal::TearDownEnvironment(), total_test_case_count(), UnshuffleTests(), and testing::internal::WriteToShardStatusFileIfNeeded().
Referenced by testing::UnitTest::Run(), testing::internal::TearDownEnvironment(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   // Makes sure InitGoogleTest() was called.
   if (!GTestIsInitialized()) {
     printf("%s",
            "\nThis test program did NOT call ::testing::InitGoogleTest "
            "before calling RUN_ALL_TESTS().  Please fix it.\n");
     return false;
   }
   // Do not run any test if the --help flag was specified.
   if (g_help_flag)
     return true;
   // Repeats the call to the post-flag parsing initialization in case the
   // user didn't call InitGoogleTest.
   PostFlagParsingInit();
   // Even if sharding is not on, test runners may want to use the
   // GTEST_SHARD_STATUS_FILE to query whether the test supports the sharding
   // protocol.
   internal::WriteToShardStatusFileIfNeeded();
   // True iff we are in a subprocess for running a thread-safe-style
   // death test.
   bool in_subprocess_for_death_test = false;
 #if GTEST_HAS_DEATH_TEST
   in_subprocess_for_death_test = (internal_run_death_test_flag_.get() != NULL);
 # if defined(GTEST_EXTRA_DEATH_TEST_CHILD_SETUP_)
   if (in_subprocess_for_death_test) {
     GTEST_EXTRA_DEATH_TEST_CHILD_SETUP_();
   }
 # endif  // defined(GTEST_EXTRA_DEATH_TEST_CHILD_SETUP_)
 #endif  // GTEST_HAS_DEATH_TEST
   const bool should_shard = ShouldShard(kTestTotalShards, kTestShardIndex,
                                         in_subprocess_for_death_test);
   // Compares the full test names with the filter to decide which
   // tests to run.
   const bool has_tests_to_run = FilterTests(should_shard
                                               ? HONOR_SHARDING_PROTOCOL
                                               : IGNORE_SHARDING_PROTOCOL) > 0;
   // Lists the tests and exits if the --gtest_list_tests flag was specified.
   if (GTEST_FLAG(list_tests)) {
     // This must be called *after* FilterTests() has been called.
     ListTestsMatchingFilter();
     return true;
   }
   random_seed_ = GTEST_FLAG(shuffle) ?
       GetRandomSeedFromFlag(GTEST_FLAG(random_seed)) : 0;
   // True iff at least one test has failed.
   bool failed = false;
   TestEventListener* repeater = listeners()->repeater();
   start_timestamp_ = GetTimeInMillis();
   repeater->OnTestProgramStart(*parent_);
   // How many times to repeat the tests?  We don't want to repeat them
   // when we are inside the subprocess of a death test.
   const int repeat = in_subprocess_for_death_test ? 1 : GTEST_FLAG(repeat);
   // Repeats forever if the repeat count is negative.
   const bool forever = repeat < 0;
   for (int i = 0; forever || i != repeat; i++) {
     // We want to preserve failures generated by ad-hoc test
     // assertions executed before RUN_ALL_TESTS().
     ClearNonAdHocTestResult();
     const TimeInMillis start = GetTimeInMillis();
     // Shuffles test cases and tests if requested.
     if (has_tests_to_run && GTEST_FLAG(shuffle)) {
       random()->Reseed(random_seed_);
       // This should be done before calling OnTestIterationStart(),
       // such that a test event listener can see the actual test order
       // in the event.
       ShuffleTests();
     }
     // Tells the unit test event listeners that the tests are about to start.
     repeater->OnTestIterationStart(*parent_, i);
     // Runs each test case if there is at least one test to run.
     if (has_tests_to_run) {
       // Sets up all environments beforehand.
       repeater->OnEnvironmentsSetUpStart(*parent_);
       ForEach(environments_, SetUpEnvironment);
       repeater->OnEnvironmentsSetUpEnd(*parent_);
       // Runs the tests only if there was no fatal failure during global
       // set-up.
       if (!Test::HasFatalFailure()) {
         for (int test_index = 0; test_index < total_test_case_count();
              test_index++) {
           GetMutableTestCase(test_index)->Run();
         }
       }
       // Tears down all environments in reverse order afterwards.
       repeater->OnEnvironmentsTearDownStart(*parent_);
       std::for_each(environments_.rbegin(), environments_.rend(),
                     TearDownEnvironment);
       repeater->OnEnvironmentsTearDownEnd(*parent_);
     }
     elapsed_time_ = GetTimeInMillis() - start;
     // Tells the unit test event listener that the tests have just finished.
     repeater->OnTestIterationEnd(*parent_, i);
     // Gets the result and clears it.
     if (!Passed()) {
       failed = true;
     }
     // Restores the original test order after the iteration.  This
     // allows the user to quickly repro a failure that happens in the
     // N-th iteration without repeating the first (N - 1) iterations.
     // This is not enclosed in "if (GTEST_FLAG(shuffle)) { ... }", in
     // case the user somehow changes the value of the flag somewhere
     // (it's always safe to unshuffle the tests).
     UnshuffleTests();
     if (GTEST_FLAG(shuffle)) {
       // Picks a new random seed for each iteration.
       random_seed_ = GetNextRandomSeed(random_seed_);
     }
   }
   repeater->OnTestProgramEnd(*parent_);
   return !failed;
 }
bool testing::internal::UnitTestImpl::RunAllTests ()
bool testing::internal::UnitTestImpl::RunAllTests ()
void testing::internal::UnitTestImpl::set_catch_exceptions (bool value) inline private
Definition at line 810 of file gtest-internal-inl.h.
References argv, testing::internal::GTestFlagSaver::catch_exceptions_, ch, folly::test::end(), testing::UnitTest::GetInstance(), testing::internal::GetUnitTestImpl(), GTEST_API_, GTEST_CHECK_, GTEST_DISALLOW_COPY_AND_ASSIGN_, testing::UnitTest::impl(), testing::internal::IsDigit(), number, original_working_dir_, testing::internal::ParseGoogleTestFlagsOnly(), testing::internal::GTestFlagSaver::random_seed_, regex, repeat(), string, and value.
 { catch_exceptions_ = value; }
void testing::internal::UnitTestImpl::set_catch_exceptions (bool value) inline private
Definition at line 810 of file gtest-internal-inl.h.
References argv, testing::internal::GTestFlagSaver::catch_exceptions_, ch, folly::test::end(), testing::UnitTest::GetInstance(), testing::internal::GetUnitTestImpl(), GTEST_API_, GTEST_CHECK_, GTEST_DISALLOW_COPY_AND_ASSIGN_, testing::UnitTest::impl(), testing::internal::IsDigit(), number, original_working_dir_, testing::internal::ParseGoogleTestFlagsOnly(), testing::internal::GTestFlagSaver::random_seed_, regex, repeat(), string, and value.
 { catch_exceptions_ = value; }
void testing::internal::UnitTestImpl::set_catch_exceptions (bool value) inline private
Definition at line 810 of file gtest-internal-inl.h.
References testing::internal::GTestFlagSaver::catch_exceptions_, and value.
 { catch_exceptions_ = value; }
void testing::internal::UnitTestImpl::set_current_test_case (TestCase * a_current_test_case) inline
Definition at line 676 of file gtest-internal-inl.h.
{
     current_test_case_ = a_current_test_case;
   }
void testing::internal::UnitTestImpl::set_current_test_case (TestCase * a_current_test_case) inline
Definition at line 676 of file gtest-internal-inl.h.
{
     current_test_case_ = a_current_test_case;
   }
void testing::internal::UnitTestImpl::set_current_test_case (TestCase * a_current_test_case) inline
Definition at line 676 of file gtest-internal-inl.h.
Referenced by testing::TestCase::Run().
{
     current_test_case_ = a_current_test_case;
   }
void testing::internal::UnitTestImpl::set_current_test_info (TestInfo * a_current_test_info) inline
Definition at line 683 of file gtest-internal-inl.h.
References RunAllTests().
Referenced by testing::TestInfo::Run().
{
     current_test_info_ = a_current_test_info;
   }
void testing::internal::UnitTestImpl::set_current_test_info (TestInfo * a_current_test_info) inline
Definition at line 683 of file gtest-internal-inl.h.
References RunAllTests().
{
     current_test_info_ = a_current_test_info;
   }
void testing::internal::UnitTestImpl::set_current_test_info (TestInfo * a_current_test_info) inline
Definition at line 683 of file gtest-internal-inl.h.
References RunAllTests().
{
     current_test_info_ = a_current_test_info;
   }
void testing::internal::UnitTestImpl::set_os_stack_trace_getter (OsStackTraceGetterInterface * getter)
Definition at line 4907 of file gtest.cc.
References os_stack_trace_getter_.
Referenced by testing::internal::PrintOnOneLine().
{
   if (os_stack_trace_getter_ != getter) {
     delete os_stack_trace_getter_;
     os_stack_trace_getter_ = getter;
   }
 }
void testing::internal::UnitTestImpl::set_os_stack_trace_getter (OsStackTraceGetterInterface * getter)
void testing::internal::UnitTestImpl::set_os_stack_trace_getter (OsStackTraceGetterInterface * getter)
void testing::internal::UnitTestImpl::SetGlobalTestPartResultReporter (TestPartResultReporterInterface * reporter)
Definition at line 711 of file gtest.cc.
References folly::detail::lock().
Referenced by testing::ScopedFakeTestPartResultReporter::Init(), testing::internal::ShouldRunTestCase(), and testing::ScopedFakeTestPartResultReporter::~ScopedFakeTestPartResultReporter().
{
   internal::MutexLock lock(&global_test_part_result_reporter_mutex_);
   global_test_part_result_repoter_ = reporter;
 }
void testing::internal::UnitTestImpl::SetGlobalTestPartResultReporter (TestPartResultReporterInterface * reporter)
void testing::internal::UnitTestImpl::SetGlobalTestPartResultReporter (TestPartResultReporterInterface * reporter)
void testing::internal::UnitTestImpl::SetTestPartResultReporterForCurrentThread (TestPartResultReporterInterface * reporter)
Definition at line 724 of file gtest.cc.
Referenced by testing::internal::HasNewFatalFailureHelper::HasNewFatalFailureHelper(), testing::ScopedFakeTestPartResultReporter::Init(), testing::internal::ShouldRunTestCase(), testing::internal::HasNewFatalFailureHelper::~HasNewFatalFailureHelper(), and testing::ScopedFakeTestPartResultReporter::~ScopedFakeTestPartResultReporter().
{
   per_thread_test_part_result_reporter_.set(reporter);
 }
void testing::internal::UnitTestImpl::SetTestPartResultReporterForCurrentThread (TestPartResultReporterInterface * reporter)
void testing::internal::UnitTestImpl::SetTestPartResultReporterForCurrentThread (TestPartResultReporterInterface * reporter)
void testing::internal::UnitTestImpl::ShuffleTests ()
Definition at line 4939 of file gtest.cc.
References i, last_death_test_case_, random(), testing::internal::ShuffleRange(), test_case_indices_, and test_cases_.
Referenced by testing::internal::PrintOnOneLine(), and RunAllTests().
{
   // Shuffles the death test cases.
   ShuffleRange(random(), 0, last_death_test_case_ + 1, &test_case_indices_);
   // Shuffles the non-death test cases.
   ShuffleRange(random(), last_death_test_case_ + 1,
                static_cast<int>(test_cases_.size()), &test_case_indices_);
   // Shuffles the tests inside each test case.
   for (size_t i = 0; i < test_cases_.size(); i++) {
     test_cases_[i]->ShuffleTests(random());
   }
 }
void testing::internal::UnitTestImpl::ShuffleTests ()
void testing::internal::UnitTestImpl::ShuffleTests ()
TimeInMillis testing::internal::UnitTestImpl::start_timestamp () const inline
Definition at line 561 of file gtest-internal-inl.h.
 { return start_timestamp_; }
TimeInMillis testing::internal::UnitTestImpl::start_timestamp () const inline
Definition at line 561 of file gtest-internal-inl.h.
 { return start_timestamp_; }
TimeInMillis testing::internal::UnitTestImpl::start_timestamp () const inline
Definition at line 561 of file gtest-internal-inl.h.
 { return start_timestamp_; }
int testing::internal::UnitTestImpl::successful_test_case_count () const
int testing::internal::UnitTestImpl::successful_test_case_count () const
Definition at line 730 of file gtest.cc.
References testing::internal::CountIf(), and testing::internal::TestCasePassed().
Referenced by testing::internal::ShouldRunTestCase().
{
   return CountIf(test_cases_, TestCasePassed);
 }
int testing::internal::UnitTestImpl::successful_test_case_count () const
int testing::internal::UnitTestImpl::successful_test_count () const
Definition at line 751 of file gtest.cc.
References testing::TestCase::successful_test_count(), and testing::internal::SumOverTestCaseList().
Referenced by testing::internal::ShouldRunTestCase().
{
   return SumOverTestCaseList(test_cases_, &TestCase::successful_test_count);
 }
int testing::internal::UnitTestImpl::successful_test_count () const
int testing::internal::UnitTestImpl::successful_test_count () const
int testing::internal::UnitTestImpl::test_case_to_run_count () const
Definition at line 746 of file gtest.cc.
References testing::internal::CountIf(), and testing::internal::ShouldRunTestCase().
Referenced by testing::internal::ShouldRunTestCase().
{
   return CountIf(test_cases_, ShouldRunTestCase);
 }
int testing::internal::UnitTestImpl::test_case_to_run_count () const
int testing::internal::UnitTestImpl::test_case_to_run_count () const
int testing::internal::UnitTestImpl::test_to_run_count () const
int testing::internal::UnitTestImpl::test_to_run_count () const
int testing::internal::UnitTestImpl::test_to_run_count () const
Definition at line 782 of file gtest.cc.
References testing::internal::SumOverTestCaseList(), and testing::TestCase::test_to_run_count().
Referenced by testing::internal::ShouldRunTestCase().
{
   return SumOverTestCaseList(test_cases_, &TestCase::test_to_run_count);
 }
int testing::internal::UnitTestImpl::total_test_case_count () const
int testing::internal::UnitTestImpl::total_test_case_count () const
Definition at line 740 of file gtest.cc.
Referenced by RunAllTests(), and testing::internal::ShouldRunTestCase().
{
   return static_cast<int>(test_cases_.size());
 }
int testing::internal::UnitTestImpl::total_test_case_count () const
int testing::internal::UnitTestImpl::total_test_count () const
Definition at line 777 of file gtest.cc.
References testing::internal::SumOverTestCaseList(), and testing::TestCase::total_test_count().
Referenced by testing::internal::ShouldRunTestCase().
{
   return SumOverTestCaseList(test_cases_, &TestCase::total_test_count);
 }
int testing::internal::UnitTestImpl::total_test_count () const
int testing::internal::UnitTestImpl::total_test_count () const
void testing::internal::UnitTestImpl::UnshuffleTests ()
Definition at line 4954 of file gtest.cc.
References i, test_case_indices_, and test_cases_.
Referenced by testing::internal::PrintOnOneLine(), and RunAllTests().
{
   for (size_t i = 0; i < test_cases_.size(); i++) {
     // Unshuffles the tests in each test case.
     test_cases_[i]->UnshuffleTests();
     // Resets the index of each test case.
     test_case_indices_[i] = static_cast<int>(i);
   }
 }
void testing::internal::UnitTestImpl::UnshuffleTests ()
void testing::internal::UnitTestImpl::UnshuffleTests ()
Friends And Related Function Documentation
friend class ::testing::UnitTest friend
Definition at line 806 of file gtest-internal-inl.h.
Member Data Documentation
TestResult testing::internal::UnitTestImpl::ad_hoc_test_result_ private
Definition at line 880 of file gtest-internal-inl.h.
Referenced by current_test_result(), and RecordProperty().
bool testing::internal::UnitTestImpl::catch_exceptions_ private
Definition at line 920 of file gtest-internal-inl.h.
TestCase * testing::internal::UnitTestImpl::current_test_case_ private
Definition at line 864 of file gtest-internal-inl.h.
Referenced by RecordProperty().
TestInfo * testing::internal::UnitTestImpl::current_test_info_ private
Definition at line 870 of file gtest-internal-inl.h.
Referenced by current_test_result(), and RecordProperty().
DefaultGlobalTestPartResultReporter testing::internal::UnitTestImpl::default_global_test_part_result_reporter_ private
Definition at line 820 of file gtest-internal-inl.h.
DefaultPerThreadTestPartResultReporter testing::internal::UnitTestImpl::default_per_thread_test_part_result_reporter_ private
Definition at line 822 of file gtest-internal-inl.h.
TimeInMillis testing::internal::UnitTestImpl::elapsed_time_ private
Definition at line 906 of file gtest-internal-inl.h.
Referenced by RunAllTests().
std::vector< Environment * > testing::internal::UnitTestImpl::environments_ private
Definition at line 836 of file gtest-internal-inl.h.
Referenced by RunAllTests(), and ~UnitTestImpl().
internal::Mutex testing::internal::UnitTestImpl::global_test_part_result_reporter_mutex_ private
Definition at line 828 of file gtest-internal-inl.h.
TestPartResultReporterInterface * testing::internal::UnitTestImpl::global_test_part_result_repoter_ private
Definition at line 825 of file gtest-internal-inl.h.
internal::ThreadLocal< std::vector< TraceInfo > > testing::internal::UnitTestImpl::gtest_trace_stack_ private
Definition at line 916 of file gtest-internal-inl.h.
int testing::internal::UnitTestImpl::last_death_test_case_ private
Definition at line 858 of file gtest-internal-inl.h.
Referenced by GetTestCase(), and ShuffleTests().
TestEventListeners testing::internal::UnitTestImpl::listeners_ private
Definition at line 884 of file gtest-internal-inl.h.
internal::FilePath testing::internal::UnitTestImpl::original_working_dir_ private
Definition at line 817 of file gtest-internal-inl.h.
OsStackTraceGetterInterface * testing::internal::UnitTestImpl::os_stack_trace_getter_ private
Definition at line 890 of file gtest-internal-inl.h.
Referenced by os_stack_trace_getter(), set_os_stack_trace_getter(), and ~UnitTestImpl().
UnitTest *const testing::internal::UnitTestImpl::parent_ private
Definition at line 813 of file gtest-internal-inl.h.
Referenced by RunAllTests().
internal::ThreadLocal< TestPartResultReporterInterface * > testing::internal::UnitTestImpl::per_thread_test_part_result_reporter_ private
Definition at line 832 of file gtest-internal-inl.h.
bool testing::internal::UnitTestImpl::post_flag_parse_init_performed_ private
Definition at line 893 of file gtest-internal-inl.h.
Referenced by PostFlagParsingInit().
internal::Random testing::internal::UnitTestImpl::random_ private
Definition at line 899 of file gtest-internal-inl.h.
int testing::internal::UnitTestImpl::random_seed_ private
Definition at line 896 of file gtest-internal-inl.h.
Referenced by RunAllTests().
TimeInMillis testing::internal::UnitTestImpl::start_timestamp_ private
Definition at line 903 of file gtest-internal-inl.h.
Referenced by RunAllTests().
std::vector< int > testing::internal::UnitTestImpl::test_case_indices_ private
Definition at line 846 of file gtest-internal-inl.h.
Referenced by GetTestCase(), ShuffleTests(), and UnshuffleTests().
std::vector< TestCase * > testing::internal::UnitTestImpl::test_cases_ private
Definition at line 840 of file gtest-internal-inl.h.
Referenced by FilterTests(), GetTestCase(), ListTestsMatchingFilter(), ShuffleTests(), UnshuffleTests(), and ~UnitTestImpl().
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest-internal-inl.h
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest.cc