proxygen: testing::gmock_nice_strict_test::MockFoo Class Reference
testing::gmock_nice_strict_test::MockFoo Class Reference
Public Member Functions
MockFoo ()
void Delete ()
MOCK_METHOD0 (DoThis, void())
MOCK_METHOD1 (DoThat, int(bool flag))
MockFoo ()
void Delete ()
MOCK_METHOD0 (DoThis, void())
MOCK_METHOD1 (DoThat, int(bool flag))
MockFoo ()
void Delete ()
MOCK_METHOD0 (DoThis, void())
MOCK_METHOD1 (DoThat, int(bool flag))
Public Member Functions inherited from testing::gmock_nice_strict_test::Foo
virtual ~Foo ()
virtual void DoThis ()=0
virtual int DoThat (bool flag)=0
virtual ~Foo ()
virtual void DoThis ()=0
virtual int DoThat (bool flag)=0
virtual ~Foo ()
virtual void DoThis ()=0
virtual int DoThat (bool flag)=0
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockFoo)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockFoo)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockFoo)
Detailed Description
Definition at line 76 of file gmock-nice-strict_test.cc.
Constructor & Destructor Documentation
testing::gmock_nice_strict_test::MockFoo::MockFoo () inline
Definition at line 78 of file gmock-nice-strict_test.cc.
 {}
testing::gmock_nice_strict_test::MockFoo::MockFoo () inline
Definition at line 78 of file gmock-nice-strict_test.cc.
 {}
testing::gmock_nice_strict_test::MockFoo::MockFoo () inline
Definition at line 78 of file gmock-nice-strict_test.cc.
 {}
Member Function Documentation
void testing::gmock_nice_strict_test::MockFoo::Delete () inline
Definition at line 79 of file gmock-nice-strict_test.cc.
References flag, Mock::GTEST_DISALLOW_COPY_AND_ASSIGN_(), Mock::MOCK_METHOD0(), and Mock::MOCK_METHOD1().
 { delete this; }
void testing::gmock_nice_strict_test::MockFoo::Delete () inline
Definition at line 79 of file gmock-nice-strict_test.cc.
References flag, Mock::GTEST_DISALLOW_COPY_AND_ASSIGN_(), Mock::MOCK_METHOD0(), and Mock::MOCK_METHOD1().
 { delete this; }
void testing::gmock_nice_strict_test::MockFoo::Delete () inline
Definition at line 79 of file gmock-nice-strict_test.cc.
References flag, Mock::GTEST_DISALLOW_COPY_AND_ASSIGN_(), Mock::MOCK_METHOD0(), and Mock::MOCK_METHOD1().
 { delete this; }
testing::gmock_nice_strict_test::MockFoo::GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockFoo) private
testing::gmock_nice_strict_test::MockFoo::GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockFoo) private
testing::gmock_nice_strict_test::MockFoo::GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockFoo) private
testing::gmock_nice_strict_test::MockFoo::MOCK_METHOD0 (DoThis , void())
testing::gmock_nice_strict_test::MockFoo::MOCK_METHOD0 (DoThis , void())
testing::gmock_nice_strict_test::MockFoo::MOCK_METHOD0 (DoThis , void())
testing::gmock_nice_strict_test::MockFoo::MOCK_METHOD1 (DoThat , int(bool flag))
testing::gmock_nice_strict_test::MockFoo::MOCK_METHOD1 (DoThat , int(bool flag))
testing::gmock_nice_strict_test::MockFoo::MOCK_METHOD1 (DoThat , int(bool flag))
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-nice-strict_test.cc