proxygen: folly::IPAddressV4 Class Reference
folly::IPAddressV4 Class Reference
#include <IPAddressV4.h>
Classes
union AddressStorage
Public Member Functions
ByteRange toBinary () const
IPAddressV4 ()
IPAddressV4 (StringPiece ip)
IPAddressV4 (const ByteArray4 &src) noexcept
IPAddressV4 (const in_addr src) noexcept
IPAddressV6 createIPv6 () const
IPAddressV6 getIPv6For6To4 () const
uint32_t toLong () const
uint32_t toLongHBO () const
std::string toJson () const
size_t hash () const
bool inSubnet (StringPiece cidrNetwork) const
bool inSubnet (const IPAddressV4 &subnet, uint8_t cidr) const
bool inSubnetWithMask (const IPAddressV4 &subnet, const ByteArray4 mask) const
bool isLoopback () const
bool isLinkLocal () const
bool isNonroutable () const
bool isPrivate () const
bool isMulticast () const
bool isZero () const
bool isLinkLocalBroadcast () const
IPAddressV4 mask (size_t numBits) const
std::string str () const
std::string toInverseArpaName () const
in_addr toAddr () const
sockaddr_in toSockAddr () const
ByteArray4 toByteArray () const
std::string toFullyQualified () const
void toFullyQualifiedAppend (std::string &out) const
uint8_t version () const
bool getNthMSBit (size_t bitIndex) const
uint8_t getNthMSByte (size_t byteIndex) const
bool getNthLSBit (size_t bitIndex) const
uint8_t getNthLSByte (size_t byteIndex) const
const unsigned char * bytes () const
Static Public Member Functions
static bool validate (StringPiece ip) noexcept
static IPAddressV4 fromLong (uint32_t src)
static IPAddressV4 fromLongHBO (uint32_t src)
static IPAddressV4 fromBinary (ByteRange bytes)
static Expected< IPAddressV4, IPAddressFormatError > tryFromBinary (ByteRange bytes) noexcept
static Expected< IPAddressV4, IPAddressFormatError > tryFromString (StringPiece str) noexcept
static IPAddressV4 fromInverseArpaName (const std::string &arpaname)
static uint32_t toLong (StringPiece ip)
static uint32_t toLongHBO (StringPiece ip)
static constexpr size_t bitCount ()
static const ByteArray4 fetchMask (size_t numBits)
static CIDRNetworkV4 longestCommonPrefix (const CIDRNetworkV4 &one, const CIDRNetworkV4 &two)
static size_t byteCount ()
Static Public Attributes
static constexpr size_t kMaxToFullyQualifiedSize
Private Member Functions
Expected< Unit, IPAddressFormatError > trySetFromBinary (ByteRange bytes) noexcept
Private Attributes
union folly::IPAddressV4::AddressStorage addr_
Detailed Description
IPv4 variation of IPAddress.
Added methods: toLong, toLongHBO and createIPv6
Note
toLong/fromLong deal in network byte order, use toLongHBO/fromLongHBO if working in host byte order.
See also
IPAddress
Definition at line 58 of file IPAddressV4.h.
Constructor & Destructor Documentation
folly::IPAddressV4::IPAddressV4 ()
Default constructor for IPAddressV4.
The address value will be 0.0.0.0
Definition at line 81 of file IPAddressV4.cpp.
Referenced by fromInverseArpaName(), fromLong(), fromLongHBO(), longestCommonPrefix(), mask(), toBinary(), and tryFromString().
 {}
folly::IPAddressV4::IPAddressV4 (StringPiece ip) explicit
Definition at line 87 of file IPAddressV4.cpp.
References folly::gen::move, and tryFromString().
                                          : addr_() {
   auto maybeIp = tryFromString(addr);
   if (maybeIp.hasError()) {
     throw IPAddressFormatException(
         to<std::string>("Invalid IPv4 address '", addr, "'"));
   }
   *this = std::move(maybeIp.value());
 }
folly::IPAddressV4::IPAddressV4 (const ByteArray4 & src) explicit noexcept
Definition at line 84 of file IPAddressV4.cpp.
 : addr_(src) {}
folly::IPAddressV4::IPAddressV4 (const in_addr src) explicit noexcept
Definition at line 106 of file IPAddressV4.cpp.
 : addr_(src) {}
Member Function Documentation
static constexpr size_t folly::IPAddressV4::bitCount () inline static
See also
IPAddress::bitCount
Returns
32
Definition at line 156 of file IPAddressV4.h.
References string, and toJson().
Referenced by fetchMask(), getNthLSBit(), mask(), and TEST().
{
     return 32;
   }
static size_t folly::IPAddressV4::byteCount () inline static
Definition at line 262 of file IPAddressV4.h.
Referenced by getNthLSByte(), and getNthMSByte().
{
     return 4;
   }
const unsigned char* folly::IPAddressV4::bytes () const inline
Definition at line 280 of file IPAddressV4.h.
References addr_, and folly::IPAddressV4::AddressStorage::bytes_.
Referenced by folly::IPAddressV4::AddressStorage::AddressStorage(), createIPv6(), getIPv6For6To4(), getNthMSByte(), isZero(), toByteArray(), tryFromBinary(), and trySetFromBinary().
{
     return addr_.bytes_.data();
   }
IPAddressV6 folly::IPAddressV4::createIPv6 () const
Definition at line 153 of file IPAddressV4.cpp.
References bytes().
Referenced by toBinary().
{
   ByteArray16 ba{};
   ba[10] = 0xff;
   ba[11] = 0xff;
   std::memcpy(&ba[12], bytes(), 4);
   return IPAddressV6(ba);
 }
const ByteArray4 folly::IPAddressV4::fetchMask (size_t numBits) static
Return the mask associated with the given number of bits. If for instance numBits was 24 (e.g. /24) then the V4 mask returned should be {0xff, 0xff, 0xff, 0x00}.
Parameters
[in] numBits bitmask to retrieve
Exceptions
abort if numBits == 0 or numBits > bitCount()
Returns
mask associated with numBits
Definition at line 282 of file IPAddressV4.cpp.
References folly::Endian::big(), bitCount(), uint32_t, uint64_t, and val.
Referenced by inSubnet(), isLinkLocal(), isLoopback(), mask(), TEST(), and version().
{
   static const size_t bits = bitCount();
   if (numBits > bits) {
     throw IPAddressFormatException("IPv4 addresses are 32 bits");
   }
   auto const val = Endian::big(uint32_t(~uint64_t(0) << (32 - numBits)));
   ByteArray4 arr;
   std::memcpy(arr.data(), &val, sizeof(val));
   return arr;
 }
IPAddressV4 folly::IPAddressV4::fromBinary (ByteRange bytes) static
Create a new IPAddress instance from the provided binary data.
Exceptions
IPAddressFormatException if the input length is not 4 bytes.
Definition at line 108 of file IPAddressV4.cpp.
References folly::Range< Iter >::size(), and tryFromBinary().
Referenced by TEST(), TEST_P(), and folly::toAppend().
{
   auto maybeIp = tryFromBinary(bytes);
   if (maybeIp.hasError()) {
     throw IPAddressFormatException(to<std::string>(
         "Invalid IPv4 binary data: length must be 4 bytes, got ",
         bytes.size()));
   }
   return maybeIp.value();
 }
IPAddressV4 folly::IPAddressV4::fromInverseArpaName (const std::string & arpaname) static
Create a new IPAddress instance from the in-addr.arpa representation.
Exceptions
IPAddressFormatException if the input is not a valid in-addr.arpa representation
Definition at line 138 of file IPAddressV4.cpp.
References IPAddressV4(), folly::join(), folly::sformat(), and folly::split().
Referenced by TEST(), and toBinary().
{
   auto piece = StringPiece(arpaname);
   // input must be something like 1.0.168.192.in-addr.arpa
   if (!piece.removeSuffix(".in-addr.arpa")) {
     throw IPAddressFormatException(
         sformat("input does not end with '.in-addr.arpa': '{}'", arpaname));
   }
   std::vector<StringPiece> pieces;
   split(".", piece, pieces);
   if (pieces.size() != 4) {
     throw IPAddressFormatException(sformat("Invalid input. Got {}", piece));
   }
   // reverse 1.0.168.192 -> 192.168.0.1
   return IPAddressV4(join(".", pieces.rbegin(), pieces.rend()));
 }
IPAddressV4 folly::IPAddressV4::fromLong (uint32_t src) static
Definition at line 52 of file IPAddressV4.cpp.
References addr, and IPAddressV4().
Referenced by folly::toAppend().
{
   in_addr addr;
   addr.s_addr = src;
   return IPAddressV4(addr);
 }
IPAddressV4 folly::IPAddressV4::fromLongHBO (uint32_t src) static
Definition at line 58 of file IPAddressV4.cpp.
References addr, and IPAddressV4().
Referenced by folly::toAppend().
{
   in_addr addr;
   addr.s_addr = htonl(src);
   return IPAddressV4(addr);
 }
IPAddressV6 folly::IPAddressV4::getIPv6For6To4 () const
Return a V6 address in the format of an 6To4 address.
Definition at line 162 of file IPAddressV4.cpp.
References bytes(), folly::IPAddressV6::PREFIX_6TO4, and uint8_t.
Referenced by TEST(), and toBinary().
{
   ByteArray16 ba{};
   ba[0] = (uint8_t)((IPAddressV6::PREFIX_6TO4 & 0xFF00) >> 8);
   ba[1] = (uint8_t)(IPAddressV6::PREFIX_6TO4 & 0x00FF);
   std::memcpy(&ba[2], bytes(), 4);
   return IPAddressV6(ba);
 }
bool folly::IPAddressV4::getNthLSBit (size_t bitIndex) const inline
Definition at line 272 of file IPAddressV4.h.
References bitCount(), and getNthMSBit().
{
     return getNthMSBit(bitCount() - bitIndex - 1);
   }
uint8_t folly::IPAddressV4::getNthLSByte (size_t byteIndex) const inline
Definition at line 276 of file IPAddressV4.h.
References byteCount(), and getNthMSByte().
{
     return getNthMSByte(byteCount() - byteIndex - 1);
   }
bool folly::IPAddressV4::getNthMSBit (size_t bitIndex) const inline
Definition at line 266 of file IPAddressV4.h.
References folly::detail::getNthMSBitImpl(), getNthMSByte(), and uint8_t.
Referenced by getNthLSBit().
{
     return detail::getNthMSBitImpl(*this, bitIndex, AF_INET);
   }
uint8_t folly::IPAddressV4::getNthMSByte (size_t byteIndex) const
Definition at line 271 of file IPAddressV4.cpp.
References byteCount(), bytes(), folly::detail::familyNameStr(), and folly::sformat().
Referenced by getNthLSByte(), and getNthMSBit().
{
   const auto highestIndex = byteCount() - 1;
   if (byteIndex > highestIndex) {
     throw std::invalid_argument(sformat(
         "Byte index must be <= {} for addresses of type: {}",
         highestIndex,
         detail::familyNameStr(AF_INET)));
   }
   return bytes()[byteIndex];
 }
size_t folly::IPAddressV4::hash () const inline
Definition at line 165 of file IPAddressV4.h.
References addr_, folly::hash::fnv32_buf(), folly::hash::hash_combine(), inSubnet(), seed, and uint32_t.
Referenced by folly::hash_value(), std::hash< folly::IPAddressV4 >::operator()(), and toJson().
                       {
     static const uint32_t seed = AF_INET;
     uint32_t hashed = hash::fnv32_buf(&addr_, 4);
     return hash::hash_combine(seed, hashed);
   }
bool folly::IPAddressV4::inSubnet (StringPiece cidrNetwork) const
Definition at line 176 of file IPAddressV4.cpp.
References addr, fetchMask(), inSubnetWithMask(), and folly::sformat().
Referenced by hash(), and folly::toAppend().
{
   auto subnetInfo = IPAddress::createNetwork(cidrNetwork);
   auto addr = subnetInfo.first;
   if (!addr.isV4()) {
     throw IPAddressFormatException(
         sformat("Address '{}' is not a V4 address", addr.toJson()));
   }
   return inSubnetWithMask(addr.asV4(), fetchMask(subnetInfo.second));
 }
bool folly::IPAddressV4::inSubnet (const IPAddressV4 & subnet, uint8_t cidr) const inline
Definition at line 176 of file IPAddressV4.h.
References fetchMask(), inSubnetWithMask(), isLinkLocal(), isLoopback(), isMulticast(), isNonroutable(), isPrivate(), and mask().
{
     return inSubnetWithMask(subnet, fetchMask(cidr));
   }
bool folly::IPAddressV4::inSubnetWithMask (const IPAddressV4 & subnet, const ByteArray4 mask) const
Definition at line 187 of file IPAddressV4.cpp.
References folly::detail::Bytes::mask(), mask(), and toByteArray().
Referenced by inSubnet(), isLinkLocal(), isLoopback(), and folly::toAppend().
{
   const auto mask = detail::Bytes::mask(toByteArray(), cidrMask);
   const auto subMask = detail::Bytes::mask(subnet.toByteArray(), cidrMask);
   return (mask == subMask);
 }
bool folly::IPAddressV4::isLinkLocal () const
Definition at line 202 of file IPAddressV4.cpp.
References fetchMask(), and inSubnetWithMask().
Referenced by inSubnet().
{
   static IPAddressV4 linklocal_addr("169.254.0.0");
   return inSubnetWithMask(linklocal_addr, fetchMask(16));
 }
bool folly::IPAddressV4::isLinkLocalBroadcast () const inline
Definition at line 202 of file IPAddressV4.h.
References mask(), str(), string, toInverseArpaName(), and toLongHBO().
{
     return (INADDR_BROADCAST == toLongHBO());
   }
bool folly::IPAddressV4::isLoopback () const
Definition at line 196 of file IPAddressV4.cpp.
References fetchMask(), and inSubnetWithMask().
Referenced by inSubnet().
{
   static IPAddressV4 loopback_addr("127.0.0.0");
   return inSubnetWithMask(loopback_addr, fetchMask(8));
 }
bool folly::IPAddressV4::isMulticast () const
Definition at line 234 of file IPAddressV4.cpp.
References toLongHBO().
Referenced by inSubnet().
{
   return (toLongHBO() & 0xf0000000) == 0xe0000000;
 }
bool folly::IPAddressV4::isNonroutable () const
Definition at line 208 of file IPAddressV4.cpp.
References isPrivate(), and toLongHBO().
Referenced by inSubnet().
{
   auto ip = toLongHBO();
   return isPrivate() ||
       (/* align */ true && ip <= 0x00FFFFFF) || // 0.0.0.0-0.255.255.255
       (ip >= 0xC0000000 && ip <= 0xC00000FF) || // 192.0.0.0-192.0.0.255
       (ip >= 0xC0000200 && ip <= 0xC00002FF) || // 192.0.2.0-192.0.2.255
       (ip >= 0xC6120000 && ip <= 0xC613FFFF) || // 198.18.0.0-198.19.255.255
       (ip >= 0xC6336400 && ip <= 0xC63364FF) || // 198.51.100.0-198.51.100.255
       (ip >= 0xCB007100 && ip <= 0xCB0071FF) || // 203.0.113.0-203.0.113.255
       (ip >= 0xE0000000 && ip <= 0xFFFFFFFF) || // 224.0.0.0-255.255.255.255
       false;
 }
bool folly::IPAddressV4::isPrivate () const
Definition at line 222 of file IPAddressV4.cpp.
References toLongHBO().
Referenced by inSubnet(), and isNonroutable().
{
   auto ip = toLongHBO();
   return // some ranges below
       (ip >= 0x0A000000 && ip <= 0x0AFFFFFF) || // 10.0.0.0-10.255.255.255
       (ip >= 0x7F000000 && ip <= 0x7FFFFFFF) || // 127.0.0.0-127.255.255.255
       (ip >= 0xA9FE0000 && ip <= 0xA9FEFFFF) || // 169.254.0.0-169.254.255.255
       (ip >= 0xAC100000 && ip <= 0xAC1FFFFF) || // 172.16.0.0-172.31.255.255
       (ip >= 0xC0A80000 && ip <= 0xC0A8FFFF) || // 192.168.0.0-192.168.255.255
       false;
 }
bool folly::IPAddressV4::isZero () const inline
Definition at line 197 of file IPAddressV4.h.
References bytes().
                       {
     constexpr auto zero = ByteArray4{{}};
     return 0 == std::memcmp(bytes(), zero.data(), zero.size());
   }
CIDRNetworkV4 folly::IPAddressV4::longestCommonPrefix (const CIDRNetworkV4 & one, const CIDRNetworkV4 & two) static
Definition at line 293 of file IPAddressV4.cpp.
References IPAddressV4(), folly::detail::Bytes::longestCommonPrefix(), and prefix().
Referenced by folly::operator<(), TEST(), and version().
{
   auto prefix = detail::Bytes::longestCommonPrefix(
       one.first.addr_.bytes_, one.second, two.first.addr_.bytes_, two.second);
   return {IPAddressV4(prefix.first), prefix.second};
 }
IPAddressV4 folly::IPAddressV4::mask (size_t numBits) const
Definition at line 239 of file IPAddressV4.cpp.
References addr_, bitCount(), folly::IPAddressV4::AddressStorage::bytes_, fetchMask(), IPAddressV4(), folly::detail::Bytes::mask(), and folly::sformat().
Referenced by inSubnet(), inSubnetWithMask(), and isLinkLocalBroadcast().
{
   static const auto bits = bitCount();
   if (numBits > bits) {
     throw IPAddressFormatException(
         sformat("numBits({}) > bitsCount({})", numBits, bits));
   }
   ByteArray4 ba = detail::Bytes::mask(fetchMask(numBits), addr_.bytes_);
   return IPAddressV4(ba);
 }
string folly::IPAddressV4::str () const
Definition at line 251 of file IPAddressV4.cpp.
References addr_, folly::detail::fastIpv4ToString(), and folly::IPAddressV4::AddressStorage::inAddr_.
Referenced by isLinkLocalBroadcast(), folly::operator<<(), folly::toAppend(), toFullyQualified(), toJson(), toLong(), and tryFromString().
{
   return detail::fastIpv4ToString(addr_.inAddr_);
 }
in_addr folly::IPAddressV4::toAddr () const inline
Definition at line 215 of file IPAddressV4.h.
References addr_, and folly::IPAddressV4::AddressStorage::inAddr_.
Referenced by BENCHMARK(), and toLong().
{
     return addr_.inAddr_;
   }
ByteRange folly::IPAddressV4::toBinary () const inline
Returns the address as a Range.
Definition at line 95 of file IPAddressV4.h.
References addr_, createIPv6(), fromInverseArpaName(), getIPv6For6To4(), folly::IPAddressV4::AddressStorage::inAddr_, IPAddressV4(), folly::pushmi::__adl::noexcept(), string, toLong(), toLongHBO(), and uint32_t.
{
     return ByteRange((const unsigned char*)&addr_.inAddr_.s_addr, 4);
   }
ByteArray4 folly::IPAddressV4::toByteArray () const inline
Definition at line 227 of file IPAddressV4.h.
References bytes().
Referenced by inSubnetWithMask().
{
     ByteArray4 ba{{0}};
     std::memcpy(ba.data(), bytes(), 4);
     return ba;
   }
std::string folly::IPAddressV4::toFullyQualified () const inline
Definition at line 234 of file IPAddressV4.h.
References str(), string, and toFullyQualifiedAppend().
Referenced by BENCHMARK(), and BENCHMARK_RELATIVE().
{
     return str();
   }
void folly::IPAddressV4::toFullyQualifiedAppend (std::string & out) const
Definition at line 256 of file IPAddressV4.cpp.
References addr_, folly::detail::fastIpv4AppendToString(), and folly::IPAddressV4::AddressStorage::inAddr_.
Referenced by BENCHMARK_RELATIVE(), and toFullyQualified().
{
   detail::fastIpv4AppendToString(addr_.inAddr_, out);
 }
string folly::IPAddressV4::toInverseArpaName () const
Definition at line 261 of file IPAddressV4.cpp.
References addr_, folly::IPAddressV4::AddressStorage::bytes_, and folly::sformat().
Referenced by isLinkLocalBroadcast(), and TEST().
{
   return sformat(
       "{}.{}.{}.{}.in-addr.arpa",
       addr_.bytes_[3],
       addr_.bytes_[2],
       addr_.bytes_[1],
       addr_.bytes_[0]);
 }
string folly::IPAddressV4::toJson () const
IPAddress::toJson
Definition at line 171 of file IPAddressV4.cpp.
References hash(), folly::sformat(), and str().
Referenced by bitCount().
{
   return sformat("{{family:'AF_INET', addr:'{}', hash:{}}}", str(), hash());
 }
uint32_t folly::IPAddressV4::toLong (StringPiece ip) static
Convert a IPv4 address string to a long in network byte order.
Parameters
[in] ip the address to convert
Returns
the long representation of the address
Definition at line 65 of file IPAddressV4.cpp.
References addr, folly::sformat(), str(), and folly::Range< Iter >::str().
Referenced by folly::operator==().
{
   auto str = ip.str();
   in_addr addr;
   if (inet_pton(AF_INET, str.c_str(), &addr) != 1) {
     throw IPAddressFormatException(
         sformat("Can't convert invalid IP '{}' to long", ip));
   }
   return addr.s_addr;
 }
uint32_t folly::IPAddressV4::toLong () const inline
Definition at line 142 of file IPAddressV4.h.
References toAddr().
Referenced by toBinary(), and toLongHBO().
{
     return toAddr().s_addr;
   }
uint32_t folly::IPAddressV4::toLongHBO (StringPiece ip) static
Definition at line 76 of file IPAddressV4.cpp.
References toLong().
Referenced by folly::operator<().
{
   return ntohl(IPAddressV4::toLong(ip));
 }
uint32_t folly::IPAddressV4::toLongHBO () const inline
Definition at line 148 of file IPAddressV4.h.
References toLong().
Referenced by isLinkLocalBroadcast(), isMulticast(), isNonroutable(), isPrivate(), and toBinary().
{
     return ntohl(toLong());
   }
sockaddr_in folly::IPAddressV4::toSockAddr () const inline
Definition at line 219 of file IPAddressV4.h.
References addr, addr_, and folly::IPAddressV4::AddressStorage::inAddr_.
{
     sockaddr_in addr;
     memset(&addr, 0, sizeof(sockaddr_in));
     addr.sin_family = AF_INET;
     memcpy(&addr.sin_addr, &addr_.inAddr_, sizeof(in_addr));
     return addr;
   }
Expected< IPAddressV4, IPAddressFormatError > folly::IPAddressV4::tryFromBinary (ByteRange bytes) static noexcept
Non-throwing version of fromBinary(). On failure returns IPAddressFormatError.
Definition at line 118 of file IPAddressV4.cpp.
References addr, bytes(), folly::makeUnexpected(), folly::gen::move, and trySetFromBinary().
Referenced by fromBinary(), TEST(), TEST_P(), and folly::toAppend().
{
   IPAddressV4 addr;
   auto setResult = addr.trySetFromBinary(bytes);
   if (setResult.hasError()) {
     return makeUnexpected(std::move(setResult.error()));
   }
   return addr;
 }
Expected< IPAddressV4, IPAddressFormatError > folly::IPAddressV4::tryFromString (StringPiece str) static noexcept
Tries to create a new IPAddressV4 instance from provided string and returns it on success. Returns IPAddressFormatError on failure.
Definition at line 96 of file IPAddressV4.cpp.
References folly::INVALID_IP, IPAddressV4(), folly::makeUnexpected(), and str().
Referenced by IPAddressV4(), TEST_P(), and folly::toAppend().
{
   struct in_addr inAddr;
   if (inet_pton(AF_INET, str.str().c_str(), &inAddr) != 1) {
     return makeUnexpected(IPAddressFormatError::INVALID_IP);
   }
   return IPAddressV4(inAddr);
 }
Expected< Unit, IPAddressFormatError > folly::IPAddressV4::trySetFromBinary (ByteRange bytes) private noexcept
Set the current IPAddressV4 object to have the address specified by bytes. Returns IPAddressFormatError if bytes.size() is not 4.
Definition at line 128 of file IPAddressV4.cpp.
References addr_, bytes(), folly::IPAddressV4::AddressStorage::inAddr_, folly::INVALID_IP, folly::makeUnexpected(), and folly::unit.
Referenced by folly::IPAddressV4::AddressStorage::AddressStorage(), and tryFromBinary().
{
   if (bytes.size() != 4) {
     return makeUnexpected(IPAddressFormatError::INVALID_IP);
   }
   memcpy(&addr_.inAddr_.s_addr, bytes.data(), sizeof(in_addr));
   return folly::unit;
 }
bool folly::IPAddressV4::validate (StringPiece ip) static noexcept
Definition at line 47 of file IPAddressV4.cpp.
Referenced by TEST(), and folly::toAppend().
{
   return tryFromString(ip).hasValue();
 }
uint8_t folly::IPAddressV4::version () const inline
Definition at line 242 of file IPAddressV4.h.
References fetchMask(), and longestCommonPrefix().
{
     return 4;
   }
Member Data Documentation
union folly::IPAddressV4::AddressStorage folly::IPAddressV4::addr_ private
Referenced by folly::IPAddressV4::AddressStorage::AddressStorage(), bytes(), hash(), mask(), str(), toAddr(), toBinary(), toFullyQualifiedAppend(), toInverseArpaName(), toSockAddr(), and trySetFromBinary().
constexpr size_t folly::IPAddressV4::kMaxToFullyQualifiedSize static
Initial value:
=
      4  * 3  + 3
Definition at line 61 of file IPAddressV4.h.
Referenced by BENCHMARK_RELATIVE(), and TEST().
The documentation for this class was generated from the following files:
proxygen/folly/folly/IPAddressV4.h
proxygen/folly/folly/IPAddressV4.cpp