proxygen: fizz::client::State Class Reference
fizz::client::State Class Reference
#include <State.h>
Public Member Functions
StateEnum state () const
const FizzClientContext * context () const
std::shared_ptr< const Cert > serverCert () const
std::shared_ptr< const Cert > clientCert () const
folly::Optional< ClientAuthType > clientAuthRequested () const
folly::Optional< SignatureScheme > clientAuthSigScheme () const
folly::Optional< ProtocolVersion > version () const
folly::Optional< CipherSuite > cipher () const
folly::Optional< NamedGroup > group () const
folly::Optional< SignatureScheme > sigScheme () const
folly::Optional< PskType > pskType () const
folly::Optional< PskKeyExchangeMode > pskMode () const
folly::Optional< KeyExchangeType > keyExchangeType () const
folly::Optional< EarlyDataType > earlyDataType () const
const folly::Optional< EarlyDataParams > & earlyDataParams () const
const folly::Optional< std::string > & alpn () const
const folly::Optional< std::string > & sni () const
const folly::Optional< CertificateCompressionAlgorithm > & serverCertCompAlgo () const
const CertificateVerifier * verifier () const
const Random & clientRandom () const
const Buf & legacySessionId () const
bool sentCCS () const
KeyScheduler * keyScheduler () const
ReadRecordLayer * readRecordLayer () const
const WriteRecordLayer * writeRecordLayer () const
const WriteRecordLayer * earlyWriteRecordLayer () const
const Buf & encodedClientHello () const
const folly::Optional< std::vector< ExtensionType > > & requestedExtensions () const
const Buf & clientHandshakeSecret () const
const Buf & serverHandshakeSecret () const
const Buf & resumptionSecret () const
const std::vector< std::shared_ptr< const PeerCert > > & unverifiedCertChain () const
std::shared_ptr< const SelfCert > selectedClientCert () const
const folly::Optional< Buf > & exporterMasterSecret () const
const folly::Optional< CachedPsk > & attemptedPsk () const
ClientExtensions * extensions () const
auto & state ()
auto & context ()
auto & verifier ()
auto & keyScheduler ()
auto & readRecordLayer ()
auto & writeRecordLayer ()
auto & earlyWriteRecordLayer ()
auto & handshakeContext () const
auto & serverCert ()
auto & clientCert ()
auto & selectedClientCert ()
auto & clientAuthRequested ()
auto & clientAuthSigScheme ()
auto & version ()
auto & cipher ()
auto & group ()
auto & sigScheme ()
auto & pskType ()
auto & pskMode ()
auto & keyExchangeType ()
auto & earlyDataType ()
auto & earlyDataParams ()
auto & alpn ()
auto & sni ()
auto & serverCertCompAlgo ()
auto & clientRandom ()
auto & legacySessionId ()
auto & sentCCS ()
auto & encodedClientHello ()
auto & keyExchangers () const
auto & requestedExtensions ()
auto & clientHandshakeSecret ()
auto & serverHandshakeSecret ()
auto & resumptionSecret ()
auto & unverifiedCertChain ()
auto & attemptedPsk ()
auto & exporterMasterSecret ()
auto & extensions ()
Private Attributes
StateEnum state_ {StateEnum::Uninitialized}
std::shared_ptr< const FizzClientContext > context_
std::shared_ptr< const CertificateVerifier > verifier_
std::unique_ptr< KeyScheduler > keyScheduler_
std::unique_ptr< ReadRecordLayer > readRecordLayer_
std::unique_ptr< WriteRecordLayer > writeRecordLayer_
std::unique_ptr< EncryptedWriteRecordLayer > earlyWriteRecordLayer_
std::unique_ptr< HandshakeContext > handshakeContext_
std::shared_ptr< const Cert > serverCert_
std::shared_ptr< const Cert > clientCert_
std::shared_ptr< const SelfCert > selectedClientCert_
folly::Optional< ClientAuthType > clientAuthRequested_
folly::Optional< SignatureScheme > clientAuthSigScheme_
folly::Optional< ProtocolVersion > version_
folly::Optional< CipherSuite > cipher_
folly::Optional< NamedGroup > group_
folly::Optional< SignatureScheme > sigScheme_
folly::Optional< PskType > pskType_
folly::Optional< PskKeyExchangeMode > pskMode_
folly::Optional< KeyExchangeType > keyExchangeType_
folly::Optional< EarlyDataType > earlyDataType_
folly::Optional< std::string > alpn_
folly::Optional< std::string > sni_
folly::Optional< CertificateCompressionAlgorithm > serverCertCompAlgo_
folly::Optional< EarlyDataParams > earlyDataParams_
folly::Optional< Random > clientRandom_
folly::Optional< Buf > legacySessionId_
bool sentCCS_ {false}
folly::Optional< Buf > encodedClientHello_
folly::Optional< std::map< NamedGroup, std::unique_ptr< KeyExchange > > > keyExchangers_
folly::Optional< std::vector< ExtensionType > > requestedExtensions_
folly::Optional< Buf > clientHandshakeSecret_
folly::Optional< Buf > serverHandshakeSecret_
folly::Optional< Buf > resumptionSecret_
folly::Optional< std::vector< std::shared_ptr< const PeerCert > > > unverifiedCertChain_
folly::Optional< CachedPsk > attemptedPsk_
folly::Optional< Buf > exporterMasterSecret_
std::shared_ptr< ClientExtensions > extensions_
Detailed Description
Definition at line 58 of file State.h.
Member Function Documentation
const folly::Optional<std::string>& fizz::client::State::alpn () const inline
Application protocol negotiated on this connection.
Definition at line 170 of file State.h.
Referenced by fizz::client::earlyParametersMatch(), fizz::client::AsyncFizzClientT< SM >::getApplicationProtocol(), and fizz::sm::getMaxEarlyDataSize().
{
     return alpn_;
   }
auto& fizz::client::State::alpn () inline
Definition at line 436 of file State.h.
                {
     return alpn_;
   }
const folly::Optional<CachedPsk>& fizz::client::State::attemptedPsk () const inline
CachedPsk that we are attempting to use.
Should not be used outside of the state machine.
Definition at line 336 of file State.h.
Referenced by fizz::sm::getHrrKeyExchangers(), fizz::sm::negotiatePsk(), and fizz::sm::validateAcceptedEarly().
{
     return attemptedPsk_;
   }
auto& fizz::client::State::attemptedPsk () inline
Definition at line 488 of file State.h.
{
     return attemptedPsk_;
   }
folly::Optional<CipherSuite> fizz::client::State::cipher () const inline
Cipher suite nogotiated on this connection.
Definition at line 113 of file State.h.
Referenced by fizz::client::earlyParametersMatch(), fizz::client::AsyncFizzClientT< SM >::getCipher(), fizz::sm::getHrrKeyExchangers(), fizz::sm::getMaxEarlyDataSize(), fizz::sm::handleCertMsg(), fizz::sm::validateAcceptedEarly(), and fizz::sm::validateNegotiationConsistency().
{
     return cipher_;
   }
auto& fizz::client::State::cipher () inline
Definition at line 404 of file State.h.
                  {
     return cipher_;
   }
folly::Optional<ClientAuthType> fizz::client::State::clientAuthRequested () const inline
Whether or not the server requested client authentication and whether a cert matched if authentication was requested.
Definition at line 92 of file State.h.
Referenced by fizz::sm::getClientCert(), and fizz::sm::handleCertMsg().
{
     return clientAuthRequested_;
   }
auto& fizz::client::State::clientAuthRequested () inline
Definition at line 392 of file State.h.
{
     return clientAuthRequested_;
   }
folly::Optional<SignatureScheme> fizz::client::State::clientAuthSigScheme () const inline
Signature scheme selected for client authentication
Definition at line 99 of file State.h.
Referenced by fizz::sm::handleCertMsg().
{
     return clientAuthSigScheme_;
   }
auto& fizz::client::State::clientAuthSigScheme () inline
Definition at line 396 of file State.h.
{
     return clientAuthSigScheme_;
   }
std::shared_ptr<const Cert> fizz::client::State::clientCert () const inline
The certificate used by the client for authentication.
Definition at line 84 of file State.h.
Referenced by fizz::client::earlyParametersMatch(), fizz::sm::getMaxEarlyDataSize(), fizz::client::AsyncFizzClientT< SM >::getSelfCertificate(), and fizz::sm::handleCertMsg().
{
     return clientCert_;
   }
auto& fizz::client::State::clientCert () inline
Definition at line 384 of file State.h.
                      {
     return clientCert_;
   }
const Buf& fizz::client::State::clientHandshakeSecret () const inline
Client handshake secret.
Should not be used outside of the state machine.
Definition at line 283 of file State.h.
Referenced by fizz::sm::handleCertMsg().
{
     return *clientHandshakeSecret_;
   }
auto& fizz::client::State::clientHandshakeSecret () inline
Definition at line 472 of file State.h.
{
     return clientHandshakeSecret_;
   }
const Random& fizz::client::State::clientRandom () const inline
Random sent by the client.
Definition at line 200 of file State.h.
Referenced by fizz::sm::getHrrKeyExchangers().
{
     return *clientRandom_;
   }
auto& fizz::client::State::clientRandom () inline
Definition at line 448 of file State.h.
{
     return clientRandom_;
   }
const FizzClientContext* fizz::client::State::context () const inline
The FizzClientContext used on this connection.
Definition at line 70 of file State.h.
Referenced by fizz::sm::getClientCert(), fizz::sm::getHrrKeyExchangers(), fizz::sm::getMaxEarlyDataSize(), fizz::client::AsyncFizzClientT< SM >::getSupportedSigSchemes(), fizz::sm::handleCertMsg(), fizz::sm::handleEarlyAppWrite(), fizz::sm::negotiatePsk(), and fizz::sm::validateAcceptedEarly().
{
     return context_.get();
   }
auto& fizz::client::State::context () inline
Definition at line 352 of file State.h.
                   {
     return context_;
   }
const folly::Optional<EarlyDataParams>& fizz::client::State::earlyDataParams () const inline
Connection parameters for data sent as early data.
Definition at line 163 of file State.h.
Referenced by fizz::client::earlyParametersMatch(), fizz::client::AsyncFizzClientT< SM >::getApplicationProtocol(), fizz::sm::getEarlyDataParams(), fizz::client::AsyncFizzClientT< SM >::getPeerCertificate(), fizz::client::AsyncFizzClientT< SM >::getSelfCertificate(), and fizz::sm::validateAcceptedEarly().
{
     return earlyDataParams_;
   }
auto& fizz::client::State::earlyDataParams () inline
Definition at line 432 of file State.h.
{
     return earlyDataParams_;
   }
folly::Optional<EarlyDataType> fizz::client::State::earlyDataType () const inline
Whether early data is used on this connection.
Definition at line 156 of file State.h.
Referenced by fizz::sm::getHrrKeyExchangers(), fizz::sm::handleCertMsg(), fizz::sm::handleEarlyAppWrite(), fizz::sm::ignoreEarlyAppWrite(), and fizz::sm::validateAcceptedEarly().
{
     return earlyDataType_;
   }
auto& fizz::client::State::earlyDataType () inline
Definition at line 428 of file State.h.
{
     return earlyDataType_;
   }
const WriteRecordLayer* fizz::client::State::earlyWriteRecordLayer () const inline
Record layer for writing early data. May be null.
Should not be used outside of the state machine.
Definition at line 254 of file State.h.
Referenced by fizz::sm::getEarlyDataParams(), fizz::sm::getHrrKeyExchangers(), fizz::sm::handleCertMsg(), fizz::sm::handleEarlyAppWrite(), and fizz::sm::validateAcceptedEarly().
{
     return earlyWriteRecordLayer_.get();
   }
auto& fizz::client::State::earlyWriteRecordLayer () inline
Definition at line 372 of file State.h.
{
     return earlyWriteRecordLayer_;
   }
const Buf& fizz::client::State::encodedClientHello () const inline
Contains the client hello that was sent on the wire.
Should not be used outside of the state machine.
Definition at line 263 of file State.h.
Referenced by fizz::sm::getHrrKeyExchangers(), and fizz::sm::negotiatePsk().
{
     return *encodedClientHello_;
   }
auto& fizz::client::State::encodedClientHello () inline
Definition at line 460 of file State.h.
{
     return encodedClientHello_;
   }
const folly::Optional<Buf>& fizz::client::State::exporterMasterSecret () const inline
Get the exporter master secret - needed for EKM
Definition at line 327 of file State.h.
Referenced by fizz::sm::handleCertMsg().
{
     return exporterMasterSecret_;
   }
auto& fizz::client::State::exporterMasterSecret () inline
Definition at line 492 of file State.h.
{
     return exporterMasterSecret_;
   }
ClientExtensions* fizz::client::State::extensions () const inline
Definition at line 344 of file State.h.
Referenced by fizz::sm::getHrrKeyExchangers(), and fizz::sm::validateAcceptedEarly().
{
     return extensions_.get();
   }
auto& fizz::client::State::extensions () inline
Definition at line 496 of file State.h.
                      {
     return extensions_;
   }
folly::Optional<NamedGroup> fizz::client::State::group () const inline
The named group used if (EC)DH key exchange was used.
Definition at line 120 of file State.h.
Referenced by fizz::sm::getMaxEarlyDataSize().
{
     return group_;
   }
auto& fizz::client::State::group () inline
Definition at line 408 of file State.h.
                 {
     return group_;
   }
auto& fizz::client::State::handshakeContext () const inline
Definition at line 376 of file State.h.
Referenced by fizz::sm::getClientCert(), fizz::sm::getHrrKeyExchangers(), fizz::sm::handleCertMsg(), fizz::sm::negotiatePsk(), and fizz::sm::validateAcceptedEarly().
{
     return handshakeContext_;
   }
auto& fizz::client::State::keyExchangers () const inline
Definition at line 464 of file State.h.
Referenced by fizz::sm::getHrrKeyExchangers(), and fizz::sm::negotiatePsk().
{
     return keyExchangers_;
   }
folly::Optional<KeyExchangeType> fizz::client::State::keyExchangeType () const inline
Key exchange flow used on this connection (none, normal, or hello retry).
Definition at line 149 of file State.h.
Referenced by fizz::sm::getHrrKeyExchangers(), and fizz::sm::negotiatePsk().
{
     return keyExchangeType_;
   }
auto& fizz::client::State::keyExchangeType () inline
Definition at line 424 of file State.h.
{
     return keyExchangeType_;
   }
KeyScheduler* fizz::client::State::keyScheduler () const inline
Key scheduler used on this connection.
The state of the key scheduler may change outside of state mutators. Should not be used outside of the state machine.
Definition at line 225 of file State.h.
Referenced by fizz::sm::getMaxEarlyDataSize(), and fizz::sm::handleCertMsg().
{
     return keyScheduler_.get();
   }
auto& fizz::client::State::keyScheduler () inline
Definition at line 360 of file State.h.
{
     return keyScheduler_;
   }
const Buf& fizz::client::State::legacySessionId () const inline
Legacy session ID sent by the client. Will be empty unless compatibility mode is in use.
Definition at line 208 of file State.h.
Referenced by fizz::sm::getHrrKeyExchangers(), and fizz::sm::negotiatePsk().
{
     return *legacySessionId_;
   }
auto& fizz::client::State::legacySessionId () inline
Definition at line 452 of file State.h.
{
     return legacySessionId_;
   }
folly::Optional<PskKeyExchangeMode> fizz::client::State::pskMode () const inline
Psk key exchange mode used on this connection, if a psk was accepted.
Definition at line 142 of file State.h.
Referenced by fizz::client::AsyncFizzClientT< SM >::pskResumed().
{
     return pskMode_;
   }
auto& fizz::client::State::pskMode () inline
Definition at line 420 of file State.h.
                   {
     return pskMode_;
   }
folly::Optional<PskType> fizz::client::State::pskType () const inline
Psk handshake flow used on this connection (psk not sent, psk rejected, psk accepted, etc.).
Definition at line 135 of file State.h.
Referenced by fizz::sm::validateAcceptedEarly().
{
     return pskType_;
   }
auto& fizz::client::State::pskType () inline
Definition at line 416 of file State.h.
                   {
     return pskType_;
   }
ReadRecordLayer* fizz::client::State::readRecordLayer () const inline
Current read record layer. May be null.
The state of the read record layer may change outside of state mutators. Should not be used outside of the state machine.
Definition at line 235 of file State.h.
Referenced by fizz::sm::getMaxEarlyDataSize(), fizz::sm::handleCertMsg(), fizz::sm::negotiatePsk(), and fizz::client::ClientStateMachine::processSocketData().
{
     return readRecordLayer_.get();
   }
auto& fizz::client::State::readRecordLayer () inline
Definition at line 364 of file State.h.
{
     return readRecordLayer_;
   }
const folly::Optional<std::vector<ExtensionType> >& fizz::client::State::requestedExtensions () const inline
Contains the extensions requested in the initial ClientHello. Used to later verify extensions sent by the server.
Should not be used outside of the state machine.
Definition at line 273 of file State.h.
Referenced by fizz::sm::getHrrKeyExchangers(), fizz::sm::negotiatePsk(), and fizz::sm::validateAcceptedEarly().
             {
     return requestedExtensions_;
   }
auto& fizz::client::State::requestedExtensions () inline
Definition at line 468 of file State.h.
{
     return requestedExtensions_;
   }
const Buf& fizz::client::State::resumptionSecret () const inline
Resumption secret.
Shoiuld not
Definition at line 301 of file State.h.
Referenced by fizz::sm::getMaxEarlyDataSize(), and fizz::sm::handleCertMsg().
{
     return *resumptionSecret_;
   }
auto& fizz::client::State::resumptionSecret () inline
Definition at line 480 of file State.h.
{
     return resumptionSecret_;
   }
std::shared_ptr<const SelfCert> fizz::client::State::selectedClientCert () const inline
The certificate selected for client authentication (prior to being sent).
Should not be used outside of the state machine.
Definition at line 320 of file State.h.
Referenced by fizz::sm::handleCertMsg().
{
     return selectedClientCert_;
   }
auto& fizz::client::State::selectedClientCert () inline
Definition at line 388 of file State.h.
{
     return selectedClientCert_;
   }
bool fizz::client::State::sentCCS () const inline
Whether we sent a CCS due to compatibility mode.
Definition at line 215 of file State.h.
Referenced by fizz::sm::getHrrKeyExchangers(), fizz::sm::handleCertMsg(), and fizz::sm::handleEarlyAppWrite().
{
     return sentCCS_;
   }
auto& fizz::client::State::sentCCS () inline
Definition at line 456 of file State.h.
                   {
     return sentCCS_;
   }
std::shared_ptr<const Cert> fizz::client::State::serverCert () const inline
The certificate used by the server for authentication.
Definition at line 77 of file State.h.
Referenced by fizz::client::earlyParametersMatch(), fizz::sm::getMaxEarlyDataSize(), fizz::client::AsyncFizzClientT< SM >::getPeerCertificate(), and fizz::sm::validateAcceptedEarly().
{
     return serverCert_;
   }
auto& fizz::client::State::serverCert () inline
Definition at line 380 of file State.h.
                      {
     return serverCert_;
   }
const folly::Optional<CertificateCompressionAlgorithm>& fizz::client::State::serverCertCompAlgo () const inline
Compression algorithm used for server certificates (if any).
Definition at line 184 of file State.h.
             {
     return serverCertCompAlgo_;
   }
auto& fizz::client::State::serverCertCompAlgo () inline
Definition at line 444 of file State.h.
{
     return serverCertCompAlgo_;
   }
const Buf& fizz::client::State::serverHandshakeSecret () const inline
Server handshake secret.
Should not be used outside of the state machine.
Definition at line 292 of file State.h.
Referenced by fizz::sm::handleCertMsg().
{
     return *serverHandshakeSecret_;
   }
auto& fizz::client::State::serverHandshakeSecret () inline
Definition at line 476 of file State.h.
{
     return serverHandshakeSecret_;
   }
folly::Optional<SignatureScheme> fizz::client::State::sigScheme () const inline
The signature scheme used if server authentication was used.
Definition at line 127 of file State.h.
{
     return sigScheme_;
   }
auto& fizz::client::State::sigScheme () inline
Definition at line 412 of file State.h.
                     {
     return sigScheme_;
   }
const folly::Optional<std::string>& fizz::client::State::sni () const inline
Server name that was sent in the SNI extensions.
Definition at line 177 of file State.h.
References sni_.
Referenced by fizz::sm::getHrrKeyExchangers().
{
     return sni_;
   }
auto& fizz::client::State::sni () inline
Definition at line 440 of file State.h.
References sni_.
               {
     return sni_;
   }
StateEnum fizz::client::State::state () const inline
Current state of the connection.
Definition at line 63 of file State.h.
Referenced by fizz::client::detail::handleError(), fizz::client::detail::handleInvalidEvent(), and fizz::client::detail::processEvent().
{
     return state_;
   }
auto& fizz::client::State::state () inline
Definition at line 348 of file State.h.
                 {
     return state_;
   }
const std::vector<std::shared_ptr<const PeerCert> >& fizz::client::State::unverifiedCertChain () const inline
Server certificate chain that has not yet been verified.
Should not be used outside of the state machine.
Definition at line 310 of file State.h.
Referenced by fizz::sm::handleCertMsg().
             {
     return *unverifiedCertChain_;
   }
auto& fizz::client::State::unverifiedCertChain () inline
Definition at line 484 of file State.h.
{
     return unverifiedCertChain_;
   }
const CertificateVerifier* fizz::client::State::verifier () const inline
Certificate verifier to be used to verify server certificates on this connection.
Definition at line 193 of file State.h.
References verifier_.
Referenced by fizz::sm::handleCertMsg().
{
     return verifier_.get();
   }
auto& fizz::client::State::verifier () inline
Definition at line 356 of file State.h.
References verifier_.
                    {
     return verifier_;
   }
folly::Optional<ProtocolVersion> fizz::client::State::version () const inline
Protocol version negotiated on this connection.
Definition at line 106 of file State.h.
Referenced by fizz::client::earlyParametersMatch(), fizz::sm::getHrrKeyExchangers(), fizz::sm::getMaxEarlyDataSize(), fizz::sm::handleCertMsg(), and fizz::sm::validateNegotiationConsistency().
{
     return version_;
   }
auto& fizz::client::State::version () inline
Definition at line 400 of file State.h.
                   {
     return version_;
   }
const WriteRecordLayer* fizz::client::State::writeRecordLayer () const inline
Current write record layer. May be null.
The state of the write record layer may change outside of state mutators. Should not be used outside of the state machine.
Definition at line 245 of file State.h.
Referenced by fizz::sm::getHrrKeyExchangers(), fizz::sm::getMaxEarlyDataSize(), fizz::client::detail::handleAppClose(), fizz::sm::handleCertMsg(), fizz::sm::handleEarlyAppWrite(), and fizz::client::detail::handleError().
{
     return writeRecordLayer_.get();
   }
auto& fizz::client::State::writeRecordLayer () inline
Definition at line 368 of file State.h.
{
     return writeRecordLayer_;
   }
Member Data Documentation
folly::Optional<std::string> fizz::client::State::alpn_ private
Definition at line 530 of file State.h.
folly::Optional<CachedPsk> fizz::client::State::attemptedPsk_ private
Definition at line 550 of file State.h.
folly::Optional<CipherSuite> fizz::client::State::cipher_ private
Definition at line 523 of file State.h.
folly::Optional<ClientAuthType> fizz::client::State::clientAuthRequested_ private
Definition at line 519 of file State.h.
folly::Optional<SignatureScheme> fizz::client::State::clientAuthSigScheme_ private
Definition at line 520 of file State.h.
std::shared_ptr<const Cert> fizz::client::State::clientCert_ private
Definition at line 516 of file State.h.
folly::Optional<Buf> fizz::client::State::clientHandshakeSecret_ private
Definition at line 544 of file State.h.
folly::Optional<Random> fizz::client::State::clientRandom_ private
Definition at line 536 of file State.h.
std::shared_ptr<const FizzClientContext> fizz::client::State::context_ private
Definition at line 503 of file State.h.
folly::Optional<EarlyDataParams> fizz::client::State::earlyDataParams_ private
Definition at line 534 of file State.h.
folly::Optional<EarlyDataType> fizz::client::State::earlyDataType_ private
Definition at line 529 of file State.h.
std::unique_ptr<EncryptedWriteRecordLayer> fizz::client::State::earlyWriteRecordLayer_ private
Definition at line 511 of file State.h.
folly::Optional<Buf> fizz::client::State::encodedClientHello_ private
Definition at line 539 of file State.h.
folly::Optional<Buf> fizz::client::State::exporterMasterSecret_ private
Definition at line 551 of file State.h.
std::shared_ptr<ClientExtensions> fizz::client::State::extensions_ private
Definition at line 552 of file State.h.
folly::Optional<NamedGroup> fizz::client::State::group_ private
Definition at line 524 of file State.h.
std::unique_ptr<HandshakeContext> fizz::client::State::handshakeContext_ mutable private
Definition at line 513 of file State.h.
folly::Optional<std::map<NamedGroup, std::unique_ptr<KeyExchange> > > fizz::client::State::keyExchangers_ mutable private
Definition at line 541 of file State.h.
folly::Optional<KeyExchangeType> fizz::client::State::keyExchangeType_ private
Definition at line 528 of file State.h.
std::unique_ptr<KeyScheduler> fizz::client::State::keyScheduler_ private
Definition at line 507 of file State.h.
folly::Optional<Buf> fizz::client::State::legacySessionId_ private
Definition at line 537 of file State.h.
folly::Optional<PskKeyExchangeMode> fizz::client::State::pskMode_ private
Definition at line 527 of file State.h.
folly::Optional<PskType> fizz::client::State::pskType_ private
Definition at line 526 of file State.h.
std::unique_ptr<ReadRecordLayer> fizz::client::State::readRecordLayer_ private
Definition at line 509 of file State.h.
folly::Optional<std::vector<ExtensionType> > fizz::client::State::requestedExtensions_ private
Definition at line 542 of file State.h.
folly::Optional<Buf> fizz::client::State::resumptionSecret_ private
Definition at line 546 of file State.h.
std::shared_ptr<const SelfCert> fizz::client::State::selectedClientCert_ private
Definition at line 517 of file State.h.
bool fizz::client::State::sentCCS_ {false} private
Definition at line 538 of file State.h.
std::shared_ptr<const Cert> fizz::client::State::serverCert_ private
Definition at line 515 of file State.h.
folly::Optional<CertificateCompressionAlgorithm> fizz::client::State::serverCertCompAlgo_ private
Definition at line 532 of file State.h.
folly::Optional<Buf> fizz::client::State::serverHandshakeSecret_ private
Definition at line 545 of file State.h.
folly::Optional<SignatureScheme> fizz::client::State::sigScheme_ private
Definition at line 525 of file State.h.
folly::Optional<std::string> fizz::client::State::sni_ private
Definition at line 531 of file State.h.
StateEnum fizz::client::State::state_ {StateEnum::Uninitialized} private
Definition at line 501 of file State.h.
folly::Optional<std::vector<std::shared_ptr<const PeerCert> > > fizz::client::State::unverifiedCertChain_ private
Definition at line 549 of file State.h.
std::shared_ptr<const CertificateVerifier> fizz::client::State::verifier_ private
Definition at line 505 of file State.h.
folly::Optional<ProtocolVersion> fizz::client::State::version_ private
Definition at line 522 of file State.h.
std::unique_ptr<WriteRecordLayer> fizz::client::State::writeRecordLayer_ private
Definition at line 510 of file State.h.
The documentation for this class was generated from the following file:
proxygen/fizz/fizz/client/State.h