proxygen: folly::detail::TypeDescriptor Class Reference
folly::detail::TypeDescriptor Class Reference
#include <Singleton.h>
Public Member Functions
TypeDescriptor (const std::type_info &ti, const std::type_info &tag_ti)
TypeDescriptor (const TypeDescriptor &other)
TypeDescriptor & operator= (const TypeDescriptor &other)
std::string name () const
bool operator== (const TypeDescriptor &other) const
Private Attributes
std::type_index ti_
std::type_index tag_ti_
Friends
class TypeDescriptorHasher
Detailed Description
Definition at line 189 of file Singleton.h.
Constructor & Destructor Documentation
folly::detail::TypeDescriptor::TypeDescriptor (const std::type_info & ti, const std::type_info & tag_ti) inline
Definition at line 191 of file Singleton.h.
       : ti_(ti), tag_ti_(tag_ti) {}
folly::detail::TypeDescriptor::TypeDescriptor (const TypeDescriptor & other) inline
Definition at line 194 of file Singleton.h.
       : ti_(other.ti_), tag_ti_(other.tag_ti_) {}
Member Function Documentation
std::string folly::detail::TypeDescriptor::name () const
Definition at line 67 of file Singleton.cpp.
References folly::demangle(), and folly::basic_fbstring< E, T, A, Storage >::toStdString().
Referenced by operator=(), folly::detail::singletonPrintDestructionStackTrace(), folly::detail::singletonThrowGetInvokedAfterDestruction(), folly::detail::singletonWarnCreateBeforeRegistrationCompleteAndAbort(), folly::detail::singletonWarnCreateCircularDependencyAndAbort(), folly::detail::singletonWarnCreateUnregisteredAndAbort(), folly::detail::singletonWarnDestroyInstanceLeak(), folly::detail::singletonWarnDoubleRegistrationAndAbort(), folly::detail::singletonWarnLeakyDoubleRegistrationAndAbort(), folly::detail::singletonWarnLeakyInstantiatingNotRegisteredAndAbort(), and folly::detail::singletonWarnRegisterMockEarlyAndAbort().
{
   auto ret = demangle(ti_.name());
   if (tag_ti_ != std::type_index(typeid(DefaultTag))) {
     ret += "/";
     ret += demangle(tag_ti_.name());
   }
   return ret.toStdString();
 }
TypeDescriptor& folly::detail::TypeDescriptor::operator= (const TypeDescriptor & other) inline
Definition at line 197 of file Singleton.h.
References name(), string, tag_ti_, and ti_.
Referenced by folly::LeakySingleton< T, Tag >::Entry::Entry().
{
     if (this != &other) {
       ti_ = other.ti_;
       tag_ti_ = other.tag_ti_;
     }
     return *this;
   }
bool folly::detail::TypeDescriptor::operator== (const TypeDescriptor & other) const inline
Definition at line 210 of file Singleton.h.
References tag_ti_, and ti_.
{
     return ti_ == other.ti_ && tag_ti_ == other.tag_ti_;
   }
Friends And Related Function Documentation
friend class TypeDescriptorHasher friend
Definition at line 208 of file Singleton.h.
Member Data Documentation
std::type_index folly::detail::TypeDescriptor::tag_ti_ private
Definition at line 216 of file Singleton.h.
Referenced by folly::detail::TypeDescriptorHasher::operator()(), operator=(), and operator==().
std::type_index folly::detail::TypeDescriptor::ti_ private
Definition at line 215 of file Singleton.h.
Referenced by folly::detail::TypeDescriptorHasher::operator()(), operator=(), and operator==().
The documentation for this class was generated from the following files:
proxygen/folly/folly/Singleton.h
proxygen/folly/folly/Singleton.cpp