proxygen: wangle::ManagedConnection Class Reference
wangle::ManagedConnection Class Reference abstract
#include <ManagedConnection.h>
Classes
class Callback
Public Member Functions
ManagedConnection ()
void timeoutExpired () noexceptoverride=0
virtual void describe (std::ostream &os) const =0
virtual bool isBusy () const =0
virtual std::chrono::milliseconds getIdleTime () const
virtual void notifyPendingShutdown ()=0
void fireNotifyPendingShutdown ()
virtual void closeWhenIdle ()=0
void fireCloseWhenIdle (bool force_to_close=false)
virtual void dropConnection ()=0
virtual void dumpConnectionState (uint8_t loglevel)=0
virtual void resetTimeout ()
void resetTimeoutTo (std::chrono::milliseconds)
virtual void scheduleTimeout (folly::HHWheelTimer::Callback *callback, std::chrono::milliseconds timeout)
ConnectionManager * getConnectionManager ()
Public Member Functions inherited from folly::HHWheelTimer::Callback
Callback ()=default
virtual ~Callback ()
virtual void callbackCanceled () noexcept
void cancelTimeout ()
bool isScheduled () const
std::chrono::milliseconds getTimeRemaining ()
Public Member Functions inherited from folly::DelayedDestruction
virtual void destroy ()
bool getDestroyPending () const
Public Member Functions inherited from folly::DelayedDestructionBase
virtual ~DelayedDestructionBase ()=default
Protected Member Functions
~ManagedConnection () override
Protected Member Functions inherited from folly::HHWheelTimer::Callback
virtual std::chrono::steady_clock::time_point getCurTime ()
Protected Member Functions inherited from folly::DelayedDestruction
~DelayedDestruction () override=default
DelayedDestruction ()
Protected Member Functions inherited from folly::DelayedDestructionBase
DelayedDestructionBase ()
uint32_t getDestructorGuardCount () const
Private Types
enum DrainState { DrainState::NONE, DrainState::SENT_NOTIFY_PENDING_SHUTDOWN, DrainState::SENT_CLOSE_WHEN_IDLE }
Private Member Functions
void setConnectionManager (ConnectionManager *mgr)
Private Attributes
DrainState state_ {DrainState::NONE}
ConnectionManager * connectionManager_
folly::SafeIntrusiveListHook listHook_
Friends
class ConnectionManager
Detailed Description
Interface describing a connection that can be managed by a container such as an Acceptor.
Definition at line 32 of file ManagedConnection.h.
Member Enumeration Documentation
enum wangle::ManagedConnection::DrainState strong private
Enumerator
NONE
SENT_NOTIFY_PENDING_SHUTDOWN
SENT_CLOSE_WHEN_IDLE
Definition at line 141 of file ManagedConnection.h.
{
     NONE,
     SENT_NOTIFY_PENDING_SHUTDOWN,
     SENT_CLOSE_WHEN_IDLE,
   };
Constructor & Destructor Documentation
wangle::ManagedConnection::ManagedConnection ()
Definition at line 23 of file ManagedConnection.cpp.
   : connectionManager_(nullptr) {
 }
wangle::ManagedConnection::~ManagedConnection () override protected
Definition at line 27 of file ManagedConnection.cpp.
References connectionManager_, and wangle::ConnectionManager::removeConnection().
Referenced by getConnectionManager().
{
   if (connectionManager_) {
     connectionManager_->removeConnection(this);
   }
 }
Member Function Documentation
virtual void wangle::ManagedConnection::closeWhenIdle () pure virtual
Instruct the connection that it should shutdown as soon as it is safe. This is called after notifyPendingShutdown().
Implemented in proxygen::HTTPSession, wangle::AcceptorHandshakeManager, wangle::ServerAcceptor< Pipeline >::ServerConnection, and TestConnection.
Referenced by fireCloseWhenIdle(), and fireNotifyPendingShutdown().
virtual void wangle::ManagedConnection::describe (std::ostream & os) const pure virtual
Print a human-readable description of the connection.
Parameters
os Destination stream.
Implemented in proxygen::HTTPSession, wangle::AcceptorHandshakeManager, wangle::ServerAcceptor< Pipeline >::ServerConnection, and TestConnection.
Referenced by wangle::operator<<().
virtual void wangle::ManagedConnection::dropConnection () pure virtual
Forcibly drop a connection.
If a request is in progress, this should cause the connection to be closed with a reset.
Implemented in proxygen::HTTPSession, wangle::AcceptorHandshakeManager, wangle::ServerAcceptor< Pipeline >::ServerConnection, and TestConnection.
Referenced by wangle::ConnectionManager::dropAllConnections(), wangle::ConnectionManager::dropConnections(), wangle::ConnectionManager::dropIdleConnections(), and fireCloseWhenIdle().
virtual void wangle::ManagedConnection::dumpConnectionState (uint8_t loglevel) pure virtual
Dump the state of the connection to the log
Implemented in proxygen::HTTPSession, wangle::AcceptorHandshakeManager, wangle::ServerAcceptor< Pipeline >::ServerConnection, and TestConnection.
Referenced by wangle::ConnectionManager::dropAllConnections(), and fireCloseWhenIdle().
void wangle::ManagedConnection::fireCloseWhenIdle (bool force_to_close = false) inline
Definition at line 91 of file ManagedConnection.h.
References closeWhenIdle(), dropConnection(), dumpConnectionState(), resetTimeout(), resetTimeoutTo(), scheduleTimeout(), SENT_CLOSE_WHEN_IDLE, SENT_NOTIFY_PENDING_SHUTDOWN, state_, folly::detail::timeout, and uint8_t.
Referenced by wangle::ConnectionManager::addConnection(), and wangle::ConnectionManager::DrainHelper::drainConnections().
{
     if (force_to_close || state_ == DrainState::SENT_NOTIFY_PENDING_SHUTDOWN) {
       state_ = DrainState::SENT_CLOSE_WHEN_IDLE;
       closeWhenIdle();
     }
   }
void wangle::ManagedConnection::fireNotifyPendingShutdown () inline
Definition at line 78 of file ManagedConnection.h.
References closeWhenIdle(), NONE, notifyPendingShutdown(), SENT_NOTIFY_PENDING_SHUTDOWN, and state_.
Referenced by wangle::ConnectionManager::addConnection(), and wangle::ConnectionManager::DrainHelper::drainConnections().
{
     if (state_ == DrainState::NONE) {
       state_ = DrainState::SENT_NOTIFY_PENDING_SHUTDOWN;
       notifyPendingShutdown();
     }
   }
ConnectionManager* wangle::ManagedConnection::getConnectionManager () inline
Definition at line 133 of file ManagedConnection.h.
References connectionManager_, and ~ManagedConnection().
Referenced by wangle::ConnectionManager::addConnection(), proxygen::HTTPSession::createTransaction(), proxygen::HTTPSession::detach(), proxygen::HTTPUpstreamSession::detachThreadLocals(), and wangle::ConnectionManager::removeConnection().
{
     return connectionManager_;
   }
virtual std::chrono::milliseconds wangle::ManagedConnection::getIdleTime () const inline virtual
Get the idle time of the connection. If it returning 0, that means the idle connections will never be dropped during pre load shedding stage.
Reimplemented in proxygen::HTTPSessionBase.
Definition at line 68 of file ManagedConnection.h.
References notifyPendingShutdown().
{
     return std::chrono::milliseconds(0);
   }
virtual bool wangle::ManagedConnection::isBusy () const pure virtual
Check whether the connection has any requests outstanding.
Implemented in proxygen::HTTPSession, wangle::AcceptorHandshakeManager, wangle::ServerAcceptor< Pipeline >::ServerConnection, and TestConnection.
Referenced by wangle::ConnectionManager::DrainHelper::drainConnections().
virtual void wangle::ManagedConnection::notifyPendingShutdown () pure virtual
Notify the connection that a shutdown is pending. This method will be called at the beginning of graceful shutdown.
Implemented in proxygen::HTTPSession, wangle::AcceptorHandshakeManager, wangle::ServerAcceptor< Pipeline >::ServerConnection, and TestConnection.
Referenced by fireNotifyPendingShutdown(), and getIdleTime().
void wangle::ManagedConnection::resetTimeout () virtual
If the connection has a connection manager, reset the timeout countdown to connection manager's default timeout.
Note
If the connection manager doesn't have the connection scheduled for a timeout already, this method will schedule one. If the connection manager does have the connection connection scheduled for a timeout, this method will push back the timeout to N msec from now, where N is the connection manager's timer interval.
Definition at line 34 of file ManagedConnection.cpp.
References connectionManager_, wangle::ConnectionManager::getDefaultTimeout(), and resetTimeoutTo().
Referenced by proxygen::HTTPSession::detach(), fireCloseWhenIdle(), proxygen::HTTPSession::readBufferAvailable(), proxygen::HTTPSession::readDataAvailable(), proxygen::HTTPSession::readTimeoutExpired(), and proxygen::HTTPSession::resumeReadsImpl().
{
   if (connectionManager_) {
     resetTimeoutTo(connectionManager_->getDefaultTimeout());
   }
 }
void wangle::ManagedConnection::resetTimeoutTo (std::chrono::milliseconds timeout)
If the connection has a connection manager, reset the timeout countdown to user specified timeout.
Definition at line 41 of file ManagedConnection.cpp.
References connectionManager_, and wangle::ConnectionManager::scheduleTimeout().
Referenced by fireCloseWhenIdle(), and resetTimeout().
{
   if (connectionManager_) {
     connectionManager_->scheduleTimeout(this, timeout);
   }
 }
void wangle::ManagedConnection::scheduleTimeout (folly::HHWheelTimer::Callback * callback, std::chrono::milliseconds timeout) virtual
Definition at line 48 of file ManagedConnection.cpp.
References connectionManager_, and wangle::ConnectionManager::scheduleTimeout().
Referenced by fireCloseWhenIdle().
{
   if (connectionManager_) {
     connectionManager_->scheduleTimeout(callback, timeout);
   }
 }
void wangle::ManagedConnection::setConnectionManager (ConnectionManager * mgr) inline private
Definition at line 151 of file ManagedConnection.h.
References connectionManager_.
Referenced by wangle::ConnectionManager::addConnection(), wangle::ConnectionManager::dropAllConnections(), and wangle::ConnectionManager::removeConnection().
{
     connectionManager_ = mgr;
   }
void wangle::ManagedConnection::timeoutExpired () override pure virtual noexcept
timeoutExpired() is invoked when the timeout has expired.
Implements folly::HHWheelTimer::Callback.
Implemented in proxygen::HTTPSession, wangle::AcceptorHandshakeManager, wangle::ServerAcceptor< Pipeline >::ServerConnection, and TestConnection.
Friends And Related Function Documentation
friend class ConnectionManager friend
Definition at line 149 of file ManagedConnection.h.
Member Data Documentation
ConnectionManager* wangle::ManagedConnection::connectionManager_ private
Definition at line 155 of file ManagedConnection.h.
Referenced by getConnectionManager(), resetTimeout(), resetTimeoutTo(), scheduleTimeout(), setConnectionManager(), and ~ManagedConnection().
folly::SafeIntrusiveListHook wangle::ManagedConnection::listHook_ private
Definition at line 157 of file ManagedConnection.h.
Referenced by wangle::ConnectionManager::addConnection().
DrainState wangle::ManagedConnection::state_ {DrainState::NONE} private
Definition at line 147 of file ManagedConnection.h.
Referenced by fireCloseWhenIdle(), and fireNotifyPendingShutdown().
The documentation for this class was generated from the following files:
proxygen/wangle/wangle/acceptor/ManagedConnection.h
proxygen/wangle/wangle/acceptor/ManagedConnection.cpp