proxygen: MockFoo Class Reference
MockFoo Class Reference
Inherits FooInterface, FooInterface, and FooInterface.
Public Member Functions
MockFoo ()
MOCK_METHOD3 (Bar, char(const std::string &s, int i, double x))
MOCK_METHOD2 (Bar2, bool(int x, int y))
MOCK_METHOD2 (Bar3, void(int x, int y))
MockFoo ()
MOCK_METHOD3 (Bar, char(const std::string &s, int i, double x))
MOCK_METHOD2 (Bar2, bool(int x, int y))
MOCK_METHOD2 (Bar3, void(int x, int y))
MockFoo ()
MOCK_METHOD3 (Bar, char(const std::string &s, int i, double x))
MOCK_METHOD2 (Bar2, bool(int x, int y))
MOCK_METHOD2 (Bar3, void(int x, int y))
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockFoo)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockFoo)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockFoo)
Detailed Description
Definition at line 51 of file gmock_output_test_.cc.
Constructor & Destructor Documentation
MockFoo::MockFoo () inline
Definition at line 53 of file gmock_output_test_.cc.
References GTEST_DISALLOW_COPY_AND_ASSIGN_, i, MOCK_METHOD2, MOCK_METHOD3, MockFoo(), s, and string.
Referenced by MockFoo().
 {}
MockFoo::MockFoo () inline
Definition at line 53 of file gmock_output_test_.cc.
References GTEST_DISALLOW_COPY_AND_ASSIGN_, i, MOCK_METHOD2, MOCK_METHOD3, MockFoo(), s, and string.
 {}
MockFoo::MockFoo () inline
Definition at line 53 of file gmock_output_test_.cc.
References GTEST_DISALLOW_COPY_AND_ASSIGN_, i, MOCK_METHOD2, MOCK_METHOD3, MockFoo(), s, and string.
 {}
Member Function Documentation
MockFoo::GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockFoo) private
MockFoo::GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockFoo) private
MockFoo::GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockFoo) private
MockFoo::MOCK_METHOD2 (Bar2 , bool(int x, int y))
MockFoo::MOCK_METHOD2 (Bar2 , bool(int x, int y))
MockFoo::MOCK_METHOD2 (Bar2 , bool(int x, int y))
MockFoo::MOCK_METHOD2 (Bar3 , void(int x, int y))
MockFoo::MOCK_METHOD2 (Bar3 , void(int x, int y))
MockFoo::MOCK_METHOD2 (Bar3 , void(int x, int y))
MockFoo::MOCK_METHOD3 (Bar , char(const std::string &s, int i, double x))
MockFoo::MOCK_METHOD3 (Bar , char(const std::string &s, int i, double x))
MockFoo::MOCK_METHOD3 (Bar , char(const std::string &s, int i, double x))
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock_output_test_.cc