proxygen: TestClientPipelineFactory Class Reference
TestClientPipelineFactory Class Reference
Public Member Functions
DefaultPipeline::Ptr newPipeline (std::shared_ptr< AsyncTransportWrapper > socket) override
BytesPipeline::Ptr newPipeline (std::shared_ptr< AsyncTransportWrapper > sock) override
Public Member Functions inherited from wangle::PipelineFactory< BytesPipeline >
virtual BytesPipeline::Ptr newPipeline (std::shared_ptr< folly::AsyncUDPSocket >, const folly::SocketAddress &)
virtual ~PipelineFactory ()=default
Public Member Functions inherited from wangle::PipelineFactory< DefaultPipeline >
virtual DefaultPipeline::Ptr newPipeline (std::shared_ptr< folly::AsyncUDPSocket >, const folly::SocketAddress &)
virtual ~PipelineFactory ()=default
Detailed Description
Definition at line 25 of file AcceptRoutingHandlerTest.cpp.
Member Function Documentation
DefaultPipeline::Ptr TestClientPipelineFactory::newPipeline (std::shared_ptr< AsyncTransportWrapper > socket) inline override virtual
Implements wangle::PipelineFactory< DefaultPipeline >.
Definition at line 27 of file AcceptRoutingHandlerTest.cpp.
References EXPECT_TRUE.
{
     // Socket should be connected already
     EXPECT_TRUE(socket->good());
     auto pipeline = DefaultPipeline::create();
     pipeline->addBack(wangle::AsyncSocketHandler(socket));
     pipeline->finalize();
     return pipeline;
   }
BytesPipeline::Ptr TestClientPipelineFactory::newPipeline (std::shared_ptr< AsyncTransportWrapper > sock) inline override virtual
Implements wangle::PipelineFactory< DefaultPipeline >.
Definition at line 37 of file BootstrapTest.cpp.
References wangle::Pipeline< R, W >::create(), EXPECT_TRUE, folly::EventBaseManager::get(), folly::EventBaseManager::getEventBase(), and folly::TimeoutManager::tryRunAfterDelay().
{
     // Socket should be connected already
     EXPECT_TRUE(sock->good());
     // Check after a small delay that socket is readable
     EventBaseManager::get()->getEventBase()->tryRunAfterDelay([sock](){
       EXPECT_TRUE(sock->readable());
     }, 100);
     auto pipeline = BytesPipeline::create();
     pipeline->addBack(new BytesToBytesHandler());
     pipeline->finalize();
     return pipeline;
   }
The documentation for this class was generated from the following files:
proxygen/wangle/wangle/bootstrap/test/AcceptRoutingHandlerTest.cpp
proxygen/wangle/wangle/bootstrap/test/BootstrapTest.cpp