proxygen: ThreadPrintingHandler Class Reference
ThreadPrintingHandler Class Reference
Public Member Functions
ThreadPrintingHandler (const char &routingData)
void transportActive (Context *ctx) override
Public Member Functions inherited from wangle::HandlerAdapter< R, W >
void read (Context *ctx, R msg) override
folly::Future< folly::Unit > write (Context *ctx, W msg) override
Public Member Functions inherited from wangle::Handler< R, R, W, W >
~Handler () override=default
virtual void read (Context *ctx, Rmsg)=0
virtual void readEOF (Context *ctx)
virtual void readException (Context *ctx, folly::exception_wrapper e)
virtual void transportActive (Context *ctx)
virtual void transportInactive (Context *ctx)
virtual folly::Future< folly::Unit > write (Context *ctx, Wmsg)=0
virtual folly::Future< folly::Unit > writeException (Context *ctx, folly::exception_wrapper e)
virtual folly::Future< folly::Unit > close (Context *ctx)
Public Member Functions inherited from wangle::HandlerBase< HandlerContext< R, W > >
virtual ~HandlerBase ()=default
virtual void attachPipeline (HandlerContext< R, W > *)
virtual void detachPipeline (HandlerContext< R, W > *)
HandlerContext< R, W > * getContext ()
Private Attributes
char routingData_
Additional Inherited Members
Public Types inherited from wangle::HandlerAdapter< R, W >
typedef Handler< R, R, W, W >::Context Context
Public Types inherited from wangle::Handler< R, R, W, W >
typedef R rin
typedef R rout
typedef W win
typedef W wout
typedef HandlerContext< R, W > Context
Static Public Attributes inherited from wangle::Handler< R, R, W, W >
static const HandlerDir dir
Detailed Description
Definition at line 64 of file accept_steering_server.cpp.
Constructor & Destructor Documentation
ThreadPrintingHandler::ThreadPrintingHandler (const char & routingData) inline explicit
Definition at line 66 of file accept_steering_server.cpp.
       : routingData_(routingData) {}
Member Function Documentation
void ThreadPrintingHandler::transportActive (Context * ctx) inline override
Definition at line 69 of file accept_steering_server.cpp.
References folly::netops::close(), folly::IOBuf::copyBuffer(), and fizz::detail::write().
{
     std::stringstream out;
     out << "You were hashed to thread " << std::this_thread::get_id()
         << " based on '" << routingData_ << "'" << std::endl;
     write(ctx, IOBuf::copyBuffer(out.str()));
     close(ctx);
   }
Member Data Documentation
char ThreadPrintingHandler::routingData_ private
Definition at line 78 of file accept_steering_server.cpp.
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/example/accept_steering/accept_steering_server.cpp