proxygen: testing::internal::EventRecordingListener Class Reference
testing::internal::EventRecordingListener Class Reference
Public Member Functions
EventRecordingListener (const char *name)
EventRecordingListener (const char *name)
EventRecordingListener (const char *name)
Public Member Functions inherited from testing::TestEventListener
virtual ~TestEventListener ()
virtual ~TestEventListener ()
virtual ~TestEventListener ()
Protected Member Functions
virtual void OnTestProgramStart (const UnitTest &)
virtual void OnTestIterationStart (const UnitTest &, int iteration)
virtual void OnEnvironmentsSetUpStart (const UnitTest &)
virtual void OnEnvironmentsSetUpEnd (const UnitTest &)
virtual void OnTestCaseStart (const TestCase &)
virtual void OnTestStart (const TestInfo &)
virtual void OnTestPartResult (const TestPartResult &)
virtual void OnTestEnd (const TestInfo &)
virtual void OnTestCaseEnd (const TestCase &)
virtual void OnEnvironmentsTearDownStart (const UnitTest &)
virtual void OnEnvironmentsTearDownEnd (const UnitTest &)
virtual void OnTestIterationEnd (const UnitTest &, int iteration)
virtual void OnTestProgramEnd (const UnitTest &)
virtual void OnTestProgramStart (const UnitTest &)
virtual void OnTestIterationStart (const UnitTest &, int iteration)
virtual void OnEnvironmentsSetUpStart (const UnitTest &)
virtual void OnEnvironmentsSetUpEnd (const UnitTest &)
virtual void OnTestCaseStart (const TestCase &)
virtual void OnTestStart (const TestInfo &)
virtual void OnTestPartResult (const TestPartResult &)
virtual void OnTestEnd (const TestInfo &)
virtual void OnTestCaseEnd (const TestCase &)
virtual void OnEnvironmentsTearDownStart (const UnitTest &)
virtual void OnEnvironmentsTearDownEnd (const UnitTest &)
virtual void OnTestIterationEnd (const UnitTest &, int iteration)
virtual void OnTestProgramEnd (const UnitTest &)
virtual void OnTestProgramStart (const UnitTest &)
virtual void OnTestIterationStart (const UnitTest &, int iteration)
virtual void OnEnvironmentsSetUpStart (const UnitTest &)
virtual void OnEnvironmentsSetUpEnd (const UnitTest &)
virtual void OnTestCaseStart (const TestCase &)
virtual void OnTestStart (const TestInfo &)
virtual void OnTestPartResult (const TestPartResult &)
virtual void OnTestEnd (const TestInfo &)
virtual void OnTestCaseEnd (const TestCase &)
virtual void OnEnvironmentsTearDownStart (const UnitTest &)
virtual void OnEnvironmentsTearDownEnd (const UnitTest &)
virtual void OnTestIterationEnd (const UnitTest &, int iteration)
virtual void OnTestProgramEnd (const UnitTest &)
Private Member Functions
std::string GetFullMethodName (const char *name)
std::string GetFullMethodName (const char *name)
std::string GetFullMethodName (const char *name)
Private Attributes
std::string name_
Detailed Description
Definition at line 55 of file gtest-listener_test.cc.
Constructor & Destructor Documentation
testing::internal::EventRecordingListener::EventRecordingListener (const char * name) inline explicit
Definition at line 57 of file gtest-listener_test.cc.
Referenced by main().
 : name_(name) {}
testing::internal::EventRecordingListener::EventRecordingListener (const char * name) inline explicit
Definition at line 57 of file gtest-listener_test.cc.
 : name_(name) {}
testing::internal::EventRecordingListener::EventRecordingListener (const char * name) inline explicit
Definition at line 57 of file gtest-listener_test.cc.
 : name_(name) {}
Member Function Documentation
std::string testing::internal::EventRecordingListener::GetFullMethodName (const char * name) inline private
Definition at line 121 of file gtest-listener_test.cc.
References name, and name_.
Referenced by OnEnvironmentsSetUpEnd(), OnEnvironmentsSetUpStart(), OnEnvironmentsTearDownEnd(), OnEnvironmentsTearDownStart(), OnTestCaseEnd(), OnTestCaseStart(), OnTestEnd(), OnTestIterationEnd(), OnTestIterationStart(), OnTestPartResult(), OnTestProgramEnd(), OnTestProgramStart(), and OnTestStart().
{
     return name_ + "." + name;
   }
std::string testing::internal::EventRecordingListener::GetFullMethodName (const char * name) inline private
Definition at line 121 of file gtest-listener_test.cc.
References name, name_, and string.
{
     return name_ + "." + name;
   }
std::string testing::internal::EventRecordingListener::GetFullMethodName (const char * name) inline private
Definition at line 121 of file gtest-listener_test.cc.
References name, name_, and string.
{
     return name_ + "." + name;
   }
virtual void testing::internal::EventRecordingListener::OnEnvironmentsSetUpEnd (const UnitTest &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 76 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnEnvironmentsSetUpEnd"));
   }
virtual void testing::internal::EventRecordingListener::OnEnvironmentsSetUpEnd (const UnitTest &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 76 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnEnvironmentsSetUpEnd"));
   }
virtual void testing::internal::EventRecordingListener::OnEnvironmentsSetUpEnd (const UnitTest &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 76 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnEnvironmentsSetUpEnd"));
   }
virtual void testing::internal::EventRecordingListener::OnEnvironmentsSetUpStart (const UnitTest &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 72 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnEnvironmentsSetUpStart"));
   }
virtual void testing::internal::EventRecordingListener::OnEnvironmentsSetUpStart (const UnitTest &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 72 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnEnvironmentsSetUpStart"));
   }
virtual void testing::internal::EventRecordingListener::OnEnvironmentsSetUpStart (const UnitTest &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 72 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnEnvironmentsSetUpStart"));
   }
virtual void testing::internal::EventRecordingListener::OnEnvironmentsTearDownEnd (const UnitTest &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 104 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnEnvironmentsTearDownEnd"));
   }
virtual void testing::internal::EventRecordingListener::OnEnvironmentsTearDownEnd (const UnitTest &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 104 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnEnvironmentsTearDownEnd"));
   }
virtual void testing::internal::EventRecordingListener::OnEnvironmentsTearDownEnd (const UnitTest &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 104 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnEnvironmentsTearDownEnd"));
   }
virtual void testing::internal::EventRecordingListener::OnEnvironmentsTearDownStart (const UnitTest &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 100 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnEnvironmentsTearDownStart"));
   }
virtual void testing::internal::EventRecordingListener::OnEnvironmentsTearDownStart (const UnitTest &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 100 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnEnvironmentsTearDownStart"));
   }
virtual void testing::internal::EventRecordingListener::OnEnvironmentsTearDownStart (const UnitTest &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 100 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnEnvironmentsTearDownStart"));
   }
virtual void testing::internal::EventRecordingListener::OnTestCaseEnd (const TestCase &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 96 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnTestCaseEnd"));
   }
virtual void testing::internal::EventRecordingListener::OnTestCaseEnd (const TestCase &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 96 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnTestCaseEnd"));
   }
virtual void testing::internal::EventRecordingListener::OnTestCaseEnd (const TestCase &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 96 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnTestCaseEnd"));
   }
virtual void testing::internal::EventRecordingListener::OnTestCaseStart (const TestCase &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 80 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnTestCaseStart"));
   }
virtual void testing::internal::EventRecordingListener::OnTestCaseStart (const TestCase &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 80 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnTestCaseStart"));
   }
virtual void testing::internal::EventRecordingListener::OnTestCaseStart (const TestCase &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 80 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnTestCaseStart"));
   }
virtual void testing::internal::EventRecordingListener::OnTestEnd (const TestInfo &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 92 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnTestEnd"));
   }
virtual void testing::internal::EventRecordingListener::OnTestEnd (const TestInfo &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 92 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnTestEnd"));
   }
virtual void testing::internal::EventRecordingListener::OnTestEnd (const TestInfo &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 92 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnTestEnd"));
   }
virtual void testing::internal::EventRecordingListener::OnTestIterationEnd (const UnitTest & , int iteration) inline protected virtual
Implements testing::TestEventListener.
Definition at line 108 of file gtest-listener_test.cc.
References GetFullMethodName(), testing::Message::GetString(), and message.
{
     Message message;
     message << GetFullMethodName("OnTestIterationEnd")
             << "("  << iteration << ")";
     g_events->push_back(message.GetString());
   }
virtual void testing::internal::EventRecordingListener::OnTestIterationEnd (const UnitTest & , int iteration) inline protected virtual
Implements testing::TestEventListener.
Definition at line 108 of file gtest-listener_test.cc.
References GetFullMethodName(), testing::Message::GetString(), and message.
{
     Message message;
     message << GetFullMethodName("OnTestIterationEnd")
             << "("  << iteration << ")";
     g_events->push_back(message.GetString());
   }
virtual void testing::internal::EventRecordingListener::OnTestIterationEnd (const UnitTest & , int iteration) inline protected virtual
Implements testing::TestEventListener.
Definition at line 108 of file gtest-listener_test.cc.
References GetFullMethodName(), testing::Message::GetString(), and message.
{
     Message message;
     message << GetFullMethodName("OnTestIterationEnd")
             << "("  << iteration << ")";
     g_events->push_back(message.GetString());
   }
virtual void testing::internal::EventRecordingListener::OnTestIterationStart (const UnitTest & , int iteration) inline protected virtual
Implements testing::TestEventListener.
Definition at line 64 of file gtest-listener_test.cc.
References GetFullMethodName(), testing::Message::GetString(), and message.
{
     Message message;
     message << GetFullMethodName("OnTestIterationStart")
             << "(" << iteration << ")";
     g_events->push_back(message.GetString());
   }
virtual void testing::internal::EventRecordingListener::OnTestIterationStart (const UnitTest & , int iteration) inline protected virtual
Implements testing::TestEventListener.
Definition at line 64 of file gtest-listener_test.cc.
References GetFullMethodName(), testing::Message::GetString(), and message.
{
     Message message;
     message << GetFullMethodName("OnTestIterationStart")
             << "(" << iteration << ")";
     g_events->push_back(message.GetString());
   }
virtual void testing::internal::EventRecordingListener::OnTestIterationStart (const UnitTest & , int iteration) inline protected virtual
Implements testing::TestEventListener.
Definition at line 64 of file gtest-listener_test.cc.
References GetFullMethodName(), testing::Message::GetString(), and message.
{
     Message message;
     message << GetFullMethodName("OnTestIterationStart")
             << "(" << iteration << ")";
     g_events->push_back(message.GetString());
   }
virtual void testing::internal::EventRecordingListener::OnTestPartResult (const TestPartResult &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 88 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnTestPartResult"));
   }
virtual void testing::internal::EventRecordingListener::OnTestPartResult (const TestPartResult &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 88 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnTestPartResult"));
   }
virtual void testing::internal::EventRecordingListener::OnTestPartResult (const TestPartResult &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 88 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnTestPartResult"));
   }
virtual void testing::internal::EventRecordingListener::OnTestProgramEnd (const UnitTest &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 116 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnTestProgramEnd"));
   }
virtual void testing::internal::EventRecordingListener::OnTestProgramEnd (const UnitTest &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 116 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnTestProgramEnd"));
   }
virtual void testing::internal::EventRecordingListener::OnTestProgramEnd (const UnitTest &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 116 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnTestProgramEnd"));
   }
virtual void testing::internal::EventRecordingListener::OnTestProgramStart (const UnitTest &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 60 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnTestProgramStart"));
   }
virtual void testing::internal::EventRecordingListener::OnTestProgramStart (const UnitTest &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 60 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnTestProgramStart"));
   }
virtual void testing::internal::EventRecordingListener::OnTestProgramStart (const UnitTest &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 60 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnTestProgramStart"));
   }
virtual void testing::internal::EventRecordingListener::OnTestStart (const TestInfo &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 84 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnTestStart"));
   }
virtual void testing::internal::EventRecordingListener::OnTestStart (const TestInfo &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 84 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnTestStart"));
   }
virtual void testing::internal::EventRecordingListener::OnTestStart (const TestInfo &) inline protected virtual
Implements testing::TestEventListener.
Definition at line 84 of file gtest-listener_test.cc.
References GetFullMethodName().
{
     g_events->push_back(GetFullMethodName("OnTestStart"));
   }
Member Data Documentation
std::string testing::internal::EventRecordingListener::name_ private
Definition at line 125 of file gtest-listener_test.cc.
Referenced by GetFullMethodName().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest-listener_test.cc