proxygen: folly::TimePoint Class Reference
folly::TimePoint Class Reference
#include <TimeUtil.h>
Public Member Functions
TimePoint (bool set=true)
void reset ()
bool isUnset () const
std::chrono::steady_clock::time_point getTime () const
std::chrono::steady_clock::time_point getTimeStart () const
std::chrono::steady_clock::time_point getTimeEnd () const
std::chrono::nanoseconds getTimeWaiting () const
pid_t getTid () const
Private Attributes
std::chrono::steady_clock::time_point timeStart_
std::chrono::steady_clock::time_point timeEnd_
std::chrono::nanoseconds timeWaiting_ {0}
pid_t tid_
Detailed Description
A class for tracking time durations in test code.
This is primarily useful for testing timeout functionality. When comparing the differences between two TimePoints, it can exclude time spent waiting on the OS scheduler. This helps avoid spurious test failures when timeouts are exceeded by longer than expected simply because the underlying system was busy and could not schedule this thread in time.
Definition at line 34 of file TimeUtil.h.
Constructor & Destructor Documentation
folly::TimePoint::TimePoint (bool set = true) inline explicit
Definition at line 36 of file TimeUtil.h.
References reset().
                                       : tid_(0) {
     if (set) {
       reset();
     }
   }
Member Function Documentation
pid_t folly::TimePoint::getTid () const inline
Definition at line 66 of file TimeUtil.h.
References tid_.
Referenced by folly::checkTimeout(), and std::chrono::PrintTo().
{
     return tid_;
   }
std::chrono::steady_clock::time_point folly::TimePoint::getTime () const inline
Definition at line 50 of file TimeUtil.h.
References timeStart_.
Referenced by TEST(), and TEST_F().
{
     return timeStart_;
   }
std::chrono::steady_clock::time_point folly::TimePoint::getTimeEnd () const inline
Definition at line 58 of file TimeUtil.h.
References timeStart_.
Referenced by folly::checkTimeout(), folly::operator<<(), and TEST_F().
{
     return timeStart_;
   }
std::chrono::steady_clock::time_point folly::TimePoint::getTimeStart () const inline
Definition at line 54 of file TimeUtil.h.
References timeStart_.
Referenced by folly::checkTimeout(), folly::operator<<(), std::chrono::PrintTo(), and TEST_F().
{
     return timeStart_;
   }
std::chrono::nanoseconds folly::TimePoint::getTimeWaiting () const inline
Definition at line 62 of file TimeUtil.h.
References timeWaiting_.
Referenced by folly::checkTimeout(), folly::operator<<(), std::chrono::PrintTo(), and TEST_F().
{
     return timeWaiting_;
   }
bool folly::TimePoint::isUnset () const inline
Definition at line 44 of file TimeUtil.h.
References timeEnd_, timeStart_, and timeWaiting_.
Referenced by TEST().
{
     return (
         timeStart_.time_since_epoch().count() == 0 &&
         timeEnd_.time_since_epoch().count() == 0 && timeWaiting_.count() == 0);
   }
void folly::TimePoint::reset ()
Definition at line 221 of file TimeUtil.cpp.
References folly::getOSThreadID(), folly::getSchedTimeWaiting(), now(), and tid_.
Referenced by TEST(), TEST_F(), and TimePoint().
                       {
   // Remember the current time
   timeStart_ = steady_clock::now();
   // Remember how long this process has spent waiting to be scheduled
   tid_ = getOSThreadID();
   timeWaiting_ = getSchedTimeWaiting(tid_);
   // In case it took a while to read the schedstat info,
   // also record the time after the schedstat check
   timeEnd_ = steady_clock::now();
 }
Member Data Documentation
pid_t folly::TimePoint::tid_ private
Definition at line 74 of file TimeUtil.h.
Referenced by getTid().
std::chrono::steady_clock::time_point folly::TimePoint::timeEnd_ private
Definition at line 72 of file TimeUtil.h.
Referenced by isUnset().
std::chrono::steady_clock::time_point folly::TimePoint::timeStart_ private
Definition at line 71 of file TimeUtil.h.
Referenced by getTime(), getTimeEnd(), getTimeStart(), and isUnset().
std::chrono::nanoseconds folly::TimePoint::timeWaiting_ {0} private
Definition at line 73 of file TimeUtil.h.
Referenced by getTimeWaiting(), and isUnset().
The documentation for this class was generated from the following files:
proxygen/folly/folly/io/async/test/TimeUtil.h
proxygen/folly/folly/io/async/test/TimeUtil.cpp