proxygen: folly::BaseFormatter< Derived, containerMode, Args > Class Template Reference
folly::BaseFormatter< Derived, containerMode, Args > Class Template Reference
#include <Format.h>
Public Types
typedef detail::FormatterTag IsFormatter
typedef BaseFormatter BaseType
Public Member Functions
template<class Output >
void operator() (Output &out) const
template<class Str >
std::enable_if< IsSomeString< Str >::value >::type appendTo (Str &str) const
std::string str () const
fbstring fbstr () const
Private Types
typedef std::tuple< Args... > ValueTuple
Private Member Functions
Derived const & asDerived () const
template<size_t K, class Callback >
std::enable_if< K==valueCount >::type doFormatFrom (size_t i, FormatArg &arg, Callback &) const
template<size_t K, class Callback >
std::enable_if<(K< valueCount)>::type doFormatFrom (size_t i, FormatArg &arg, Callback &cb) const
template<class Callback >
void doFormat (size_t i, FormatArg &arg, Callback &cb) const
template<size_t K>
std::enable_if< K==valueCount, int >::type getSizeArgFrom (size_t i, const FormatArg &arg) const
template<class T >
std::enable_if< std::is_integral< T >::value &&!std::is_same< T, bool >::value, int >::type getValue (const FormatValue< T > &format, const FormatArg &) const
template<class T >
std::enable_if< !std::is_integral< T >::value||std::is_same< T, bool >::value, int >::type getValue (const FormatValue< T > &, const FormatArg &arg) const
Static Private Attributes
static constexpr size_t valueCount = std::tuple_size<ValueTuple>::value
Detailed Description
template<class Derived, bool containerMode, class... Args>
class folly::BaseFormatter< Derived, containerMode, Args >
Formatter class.
Note that this class is tricky, as it keeps references to its lvalue arguments (while it takes ownership of the temporaries), and it doesn't copy the passed-in format string. Thankfully, you can't use this directly, you have to use format(...) below.
Definition at line 72 of file Format.h.
Member Typedef Documentation
template<class Derived, bool containerMode, class... Args> typedef BaseFormatter folly::BaseFormatter< Derived, containerMode, Args >::BaseType
Definition at line 112 of file Format.h.
template<class Derived, bool containerMode, class... Args> typedef detail::FormatterTag folly::BaseFormatter< Derived, containerMode, Args >::IsFormatter
Metadata to identify generated children of BaseFormatter
Definition at line 111 of file Format.h.
template<class Derived, bool containerMode, class... Args> typedef std::tuple<Args...> folly::BaseFormatter< Derived, containerMode, Args >::ValueTuple private
Definition at line 115 of file Format.h.
Member Function Documentation
template<class Derived, bool containerMode, class... Args> template<class Str > std::enable_if<IsSomeString<Str>::value>::type folly::BaseFormatter< Derived, containerMode, Args >::appendTo (Str & str) const inline
Append to a string.
Definition at line 84 of file Format.h.
                       {
     auto appender = [&str](StringPiece s) { str.append(s.data(), s.size()); };
     (*this)(appender);
   }
template<class Derived, bool containerMode, class... Args> Derived const& folly::BaseFormatter< Derived, containerMode, Args >::asDerived () const inline private
Definition at line 118 of file Format.h.
{
     return *static_cast<const Derived*>(this);
   }
template<class Derived, bool containerMode, class... Args> template<class Callback > void folly::BaseFormatter< Derived, containerMode, Args >::doFormat (size_t i, FormatArg & arg, Callback & cb) const inline private
Definition at line 139 of file Format.h.
{
     return doFormatFrom<0>(i, arg, cb);
   }
template<class Derived, bool containerMode, class... Args> template<size_t K, class Callback > std::enable_if<K == valueCount>::type folly::BaseFormatter< Derived, containerMode, Args >::doFormatFrom (size_t i, FormatArg & arg, Callback &) const inline private
Definition at line 124 of file Format.h.
{
     arg.error("argument index out of range, max=", i);
   }
template<class Derived, bool containerMode, class... Args> template<size_t K, class Callback > std::enable_if<(K < valueCount)>::type folly::BaseFormatter< Derived, containerMode, Args >::doFormatFrom (size_t i, FormatArg & arg, Callback & cb) const inline private
Definition at line 130 of file Format.h.
{
     if (i == K) {
       asDerived().template doFormatArg<K>(arg, cb);
     } else {
       doFormatFrom<K + 1>(i, arg, cb);
     }
   }
template<class Derived, bool containerMode, class... Args> fbstring folly::BaseFormatter< Derived, containerMode, Args >::fbstr () const inline
Conversion to fbstring
Definition at line 102 of file Format.h.
Referenced by folly::format_value::formatFormatter().
{
     fbstring s;
     appendTo(s);
     return s;
   }
template<class Derived, bool containerMode, class... Args> template<size_t K> std::enable_if<K == valueCount, int>::type folly::BaseFormatter< Derived, containerMode, Args >::getSizeArgFrom (size_t i, const FormatArg & arg) const inline private
Definition at line 144 of file Format.h.
{
     arg.error("argument index out of range, max=", i);
   }
template<class Derived, bool containerMode, class... Args> template<class T > std::enable_if< std::is_integral<T>::value && !std::is_same<T, bool>::value, int>::type folly::BaseFormatter< Derived, containerMode, Args >::getValue (const FormatValue< T > & format, const FormatArg &) const inline private
Definition at line 154 of file Format.h.
{
     return static_cast<int>(format.getValue());
   }
template<class Derived, bool containerMode, class... Args> template<class T > std::enable_if< !std::is_integral<T>::value || std::is_same<T, bool>::value, int>::type folly::BaseFormatter< Derived, containerMode, Args >::getValue (const FormatValue< T > & , const FormatArg & arg) const inline private
Definition at line 162 of file Format.h.
{
     arg.error("dynamic field width argument must be integral");
   }
template<class Derived , bool containerMode, class... Args> template<class Output > void folly::BaseFormatter< Derived, containerMode, Args >::operator() (Output & out) const
Append to output. out(StringPiece sp) may be called (more than once)
Definition at line 169 of file Format-inl.h.
References testing::Args(), folly::test::end(), and s.
{
   // Copy raw string (without format specifiers) to output;
   // not as simple as we'd like, as we still need to translate "}}" to "}"
   // and throw if we see any lone "}"
   auto outputString = [&out](StringPiece s) {
     auto p = s.begin();
     auto end = s.end();
     while (p != end) {
       auto q = static_cast<const char*>(memchr(p, '}', size_t(end - p)));
       if (!q) {
         out(StringPiece(p, end));
         break;
       }
       ++q;
       out(StringPiece(p, q));
       p = q;
       if (p == end || *p != '}') {
         throw_exception<BadFormatArg>(
             "folly::format: single '}' in format string");
       }
       ++p;
     }
   };
   auto p = str_.begin();
   auto end = str_.end();
   int nextArg = 0;
   bool hasDefaultArgIndex = false;
   bool hasExplicitArgIndex = false;
   while (p != end) {
     auto q = static_cast<const char*>(memchr(p, '{', size_t(end - p)));
     if (!q) {
       outputString(StringPiece(p, end));
       break;
     }
     outputString(StringPiece(p, q));
     p = q + 1;
     if (p == end) {
       throw_exception<BadFormatArg>(
           "folly::format: '}' at end of format string");
     }
     // "{{" -> "{"
     if (*p == '{') {
       out(StringPiece(p, 1));
       ++p;
       continue;
     }
     // Format string
     q = static_cast<const char*>(memchr(p, '}', size_t(end - p)));
     if (q == nullptr) {
       throw_exception<BadFormatArg>("folly::format: missing ending '}'");
     }
     FormatArg arg(StringPiece(p, q));
     p = q + 1;
     int argIndex = 0;
     auto piece = arg.splitKey<true>(); // empty key component is okay
     if (containerMode) { // static
       arg.enforce(
           arg.width != FormatArg::kDynamicWidth,
           "dynamic field width not supported in vformat()");
       if (piece.empty()) {
         arg.setNextIntKey(nextArg++);
         hasDefaultArgIndex = true;
       } else {
         arg.setNextKey(piece);
         hasExplicitArgIndex = true;
       }
     } else {
       if (piece.empty()) {
         if (arg.width == FormatArg::kDynamicWidth) {
           arg.enforce(
               arg.widthIndex == FormatArg::kNoIndex,
               "cannot provide width arg index without value arg index");
           int sizeArg = nextArg++;
           arg.width = asDerived().getSizeArg(size_t(sizeArg), arg);
         }
         argIndex = nextArg++;
         hasDefaultArgIndex = true;
       } else {
         if (arg.width == FormatArg::kDynamicWidth) {
           arg.enforce(
               arg.widthIndex != FormatArg::kNoIndex,
               "cannot provide value arg index without width arg index");
           arg.width = asDerived().getSizeArg(size_t(arg.widthIndex), arg);
         }
         try {
           argIndex = to<int>(piece);
         } catch (const std::out_of_range&) {
           arg.error("argument index must be integer");
         }
         arg.enforce(argIndex >= 0, "argument index must be non-negative");
         hasExplicitArgIndex = true;
       }
     }
     if (hasDefaultArgIndex && hasExplicitArgIndex) {
       throw_exception<BadFormatArg>(
           "folly::format: may not have both default and explicit arg indexes");
     }
     asDerived().doFormat(size_t(argIndex), arg, out);
   }
 }
template<class Derived, bool containerMode, class... Args> std::string folly::BaseFormatter< Derived, containerMode, Args >::str () const inline
Conversion to string
Definition at line 93 of file Format.h.
{
     std::string s;
     appendTo(s);
     return s;
   }
Member Data Documentation
template<class Derived, bool containerMode, class... Args> constexpr size_t folly::BaseFormatter< Derived, containerMode, Args >::valueCount = std::tuple_size<ValueTuple>::value static private
Definition at line 116 of file Format.h.
The documentation for this class was generated from the following files:
proxygen/folly/folly/Format.h
proxygen/folly/folly/Format-inl.h