proxygen: folly::settings::detail::SettingCore< T > Class Template Reference
folly::settings::detail::SettingCore< T > Class Template Reference
#include <SettingsImpl.h>
Public Types
using Contents = SettingContents< T >
Public Member Functions
void setFromString (StringPiece newValue, StringPiece reason, SnapshotBase *snapshot) override
std::pair< std::string, std::string > getAsString (const SnapshotBase *snapshot) const override
void resetToDefault (SnapshotBase *snapshot) override
const SettingMetadata & meta () const override
std::conditional_t< IsSmallPOD< T >::value, T, const T & > getWithHint (std::atomic< uint64_t > &trivialStorage) const
const SettingContents< T > & getSlow () const
T getImpl (std::true_type, std::atomic< uint64_t > &trivialStorage) const
const T & getImpl (std::false_type, std::atomic< uint64_t > &) const
void set (const T &t, StringPiece reason, SnapshotBase *snapshot=nullptr)
const T & defaultValue () const
SettingCore (SettingMetadata meta, T defaultValue, std::atomic< uint64_t > &trivialStorage)
Private Member Functions
FOLLY_ALWAYS_INLINE const std::shared_ptr< Contents > & tlValue () const
FOLLY_NOINLINE const std::shared_ptr< Contents > & tlValueSlow () const
Private Attributes
SettingMetadata meta_
const T defaultValue_
SharedMutex globalLock_
std::shared_ptr< Contents > globalValue_
std::atomic< uint64_t > & trivialStorage_
CachelinePadded< std::atomic< Version > > settingVersion_ {1}
ThreadLocal< CachelinePadded< std::pair< Version, std::shared_ptr< Contents > > > > localValue_
Detailed Description
template<class T>
class folly::settings::detail::SettingCore< T >
Definition at line 249 of file SettingsImpl.h.
Member Typedef Documentation
template<class T> using folly::settings::detail::SettingCore< T >::Contents = SettingContents<T>
Definition at line 251 of file SettingsImpl.h.
Constructor & Destructor Documentation
template<class T> folly::settings::detail::SettingCore< T >::SettingCore (SettingMetadata meta, T defaultValue, std::atomic< uint64_t > & trivialStorage) inline
Definition at line 334 of file SettingsImpl.h.
References folly::settings::detail::registerSetting().
       : meta_(std::move(meta)),
         defaultValue_(std::move(defaultValue)),
         trivialStorage_(trivialStorage),
         localValue_([]() {
           return new CachelinePadded<
               std::pair<Version, std::shared_ptr<Contents>>>(0, nullptr);
         }) {
     set(defaultValue_, "default");
     registerSetting(*this);
   }
Member Function Documentation
template<class T> const T& folly::settings::detail::SettingCore< T >::defaultValue () const inline
Definition at line 330 of file SettingsImpl.h.
{
     return defaultValue_;
   }
template<class T> std::pair<std::string, std::string> folly::settings::detail::SettingCore< T >::getAsString (const SnapshotBase * snapshot) const inline override
Definition at line 260 of file SettingsImpl.h.
References folly::settings::detail::getSlow().
{
     auto& contents = snapshot ? snapshot->get(*this) : getSlow();
     return std::make_pair(
         to<std::string>(contents.value), contents.updateReason);
   }
template<class T> T folly::settings::detail::SettingCore< T >::getImpl (std::true_type , std::atomic< uint64_t > & trivialStorage) const inline
Definition at line 291 of file SettingsImpl.h.
References folly::pushmi::detail::t, and uint64_t.
{
     uint64_t v = trivialStorage.load();
     T t;
     std::memcpy(&t, &v, sizeof(T));
     return t;
   }
template<class T> const T& folly::settings::detail::SettingCore< T >::getImpl (std::false_type , std::atomic< uint64_t > &) const inline
Non-SmallPOD version: read the thread local shared_ptr
Definition at line 301 of file SettingsImpl.h.
             {
     return const_cast<SettingCore*>(this)->tlValue()->value;
   }
template<class T> const SettingContents<T>& folly::settings::detail::SettingCore< T >::getSlow () const inline
Definition at line 285 of file SettingsImpl.h.
{
     return *tlValue();
   }
template<class T> std::conditional_t<IsSmallPOD<T>::value, T, const T&> folly::settings::detail::SettingCore< T >::getWithHint (std::atomic< uint64_t > & trivialStorage) const inline
Parameters
trivialStorage must refer to the same location as the internal trivialStorage_. This hint will generate better inlined code since the address is known at compile time at the callsite.
Definition at line 281 of file SettingsImpl.h.
{
     return getImpl(IsSmallPOD<T>(), trivialStorage);
   }
template<class T> const SettingMetadata& folly::settings::detail::SettingCore< T >::meta () const inline override
Definition at line 271 of file SettingsImpl.h.
{
     return meta_;
   }
template<class T> void folly::settings::detail::SettingCore< T >::resetToDefault (SnapshotBase * snapshot) inline override
Definition at line 267 of file SettingsImpl.h.
{
     set(defaultValue_, "default", snapshot);
   }
template<class T> void folly::settings::detail::SettingCore< T >::set (const T & t, StringPiece reason, SnapshotBase * snapshot = nullptr) inline
Definition at line 306 of file SettingsImpl.h.
References getKey(), folly::settings::detail::nextGlobalVersion(), folly::settings::detail::saveValueForOutstandingSnapshots(), folly::settings::detail::SettingCore< T >::set(), folly::pushmi::detail::t, uint64_t, and value.
Referenced by folly::settings::detail::SettingCore< T >::set().
{
     /* Check that we can still display it (will throw otherwise) */
     to<std::string>(t);
     if (snapshot) {
       snapshot->set(*this, t, reason);
       return;
     }
     SharedMutex::WriteHolder lg(globalLock_);
     if (globalValue_) {
       saveValueForOutstandingSnapshots(
           getKey(), *settingVersion_, BoxedValue(*globalValue_));
     }
     globalValue_ = std::make_shared<Contents>(reason.str(), t);
     if (IsSmallPOD<T>::value) {
       uint64_t v = 0;
       std::memcpy(&v, &t, sizeof(T));
       trivialStorage_.store(v);
     }
     *settingVersion_ = nextGlobalVersion();
   }
template<class T> void folly::settings::detail::SettingCore< T >::setFromString (StringPiece newValue, StringPiece reason, SnapshotBase * snapshot) inline override
Definition at line 253 of file SettingsImpl.h.
References folly::Range< Iter >::str().
{
     set(convertOrConstruct<T>(newValue), reason.str(), snapshot);
   }
template<class T> FOLLY_ALWAYS_INLINE const std::shared_ptr<Contents>& folly::settings::detail::SettingCore< T >::tlValue () const inline private
Definition at line 365 of file SettingsImpl.h.
References LIKELY, and folly::value().
{
     auto& value = **localValue_;
     if (LIKELY(value.first == *settingVersion_)) {
       return value.second;
     }
     return tlValueSlow();
   }
template<class T> FOLLY_NOINLINE const std::shared_ptr<Contents>& folly::settings::detail::SettingCore< T >::tlValueSlow () const inline private
Definition at line 372 of file SettingsImpl.h.
References folly::value().
{
     auto& value = **localValue_;
     while (value.first < *settingVersion_) {
       /* If this destroys the old value, do it without holding the lock */
       value.second.reset();
       SharedMutex::ReadHolder lg(globalLock_);
       value.first = *settingVersion_;
       value.second = globalValue_;
     }
     return value.second;
   }
Member Data Documentation
template<class T> const T folly::settings::detail::SettingCore< T >::defaultValue_ private
Definition at line 351 of file SettingsImpl.h.
template<class T> SharedMutex folly::settings::detail::SettingCore< T >::globalLock_ private
Definition at line 353 of file SettingsImpl.h.
template<class T> std::shared_ptr<Contents> folly::settings::detail::SettingCore< T >::globalValue_ private
Definition at line 354 of file SettingsImpl.h.
template<class T> ThreadLocal<CachelinePadded<std::pair<Version, std::shared_ptr<Contents> > > > folly::settings::detail::SettingCore< T >::localValue_ private
Definition at line 363 of file SettingsImpl.h.
template<class T> SettingMetadata folly::settings::detail::SettingCore< T >::meta_ private
Definition at line 350 of file SettingsImpl.h.
template<class T> CachelinePadded<std::atomic<Version> > folly::settings::detail::SettingCore< T >::settingVersion_ {1} private
Definition at line 360 of file SettingsImpl.h.
template<class T> std::atomic<uint64_t>& folly::settings::detail::SettingCore< T >::trivialStorage_ private
Definition at line 356 of file SettingsImpl.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/settings/detail/SettingsImpl.h