proxygen: folly::detail::SingletonHolderBase Class Reference
folly::detail::SingletonHolderBase Class Reference abstract
#include <Singleton.h>
Public Member Functions
SingletonHolderBase (TypeDescriptor typeDesc)
virtual ~SingletonHolderBase ()=default
TypeDescriptor type () const
virtual bool hasLiveInstance ()=0
virtual void createInstance ()=0
virtual bool creationStarted ()=0
virtual void preDestroyInstance (ReadMostlyMainPtrDeleter<> &)=0
virtual void destroyInstance ()=0
Private Attributes
TypeDescriptor type_
Detailed Description
Definition at line 280 of file Singleton.h.
Constructor & Destructor Documentation
folly::detail::SingletonHolderBase::SingletonHolderBase (TypeDescriptor typeDesc) inline explicit
Definition at line 282 of file Singleton.h.
 : type_(typeDesc) {}
virtual folly::detail::SingletonHolderBase::~SingletonHolderBase () virtual default
Member Function Documentation
virtual void folly::detail::SingletonHolderBase::createInstance () pure virtual
Implemented in folly::detail::SingletonHolder< T >.
virtual bool folly::detail::SingletonHolderBase::creationStarted () pure virtual
Implemented in folly::detail::SingletonHolder< T >.
virtual void folly::detail::SingletonHolderBase::destroyInstance () pure virtual
Implemented in folly::detail::SingletonHolder< T >.
virtual bool folly::detail::SingletonHolderBase::hasLiveInstance () pure virtual
Implemented in folly::detail::SingletonHolder< T >.
virtual void folly::detail::SingletonHolderBase::preDestroyInstance (ReadMostlyMainPtrDeleter<> &) pure virtual
Implemented in folly::detail::SingletonHolder< T >.
TypeDescriptor folly::detail::SingletonHolderBase::type () const inline
Definition at line 285 of file Singleton.h.
References type_.
Referenced by folly::SingletonVault::addEagerInitSingleton(), folly::detail::SingletonHolder< T >::createInstance(), and folly::SingletonVault::registerSingleton().
{
     return type_;
   }
Member Data Documentation
TypeDescriptor folly::detail::SingletonHolderBase::type_ private
Definition at line 295 of file Singleton.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/Singleton.h