proxygen: wangle::PipelineBase Class Reference
wangle::PipelineBase Class Reference abstract
#include <Pipeline.h>
Public Member Functions
virtual ~PipelineBase ()=default
void setPipelineManager (PipelineManager *manager)
PipelineManager * getPipelineManager ()
void deletePipeline ()
void setTransport (std::shared_ptr< folly::AsyncTransport > transport)
std::shared_ptr< folly::AsyncTransport > getTransport ()
void setWriteFlags (folly::WriteFlags flags)
folly::WriteFlags getWriteFlags ()
void setReadBufferSettings (uint64_t minAvailable, uint64_t allocationSize)
std::pair< uint64_t, uint64_t > getReadBufferSettings ()
void setTransportInfo (std::shared_ptr< TransportInfo > tInfo)
std::shared_ptr< TransportInfo > getTransportInfo ()
template<class H >
PipelineBase & addBack (std::shared_ptr< H > handler)
template<class H >
PipelineBase & addBack (H &&handler)
template<class H >
PipelineBase & addBack (H *handler)
template<class H >
PipelineBase & addFront (std::shared_ptr< H > handler)
template<class H >
PipelineBase & addFront (H &&handler)
template<class H >
PipelineBase & addFront (H *handler)
template<class H >
PipelineBase & remove (H *handler)
template<class H >
PipelineBase & remove ()
PipelineBase & removeFront ()
PipelineBase & removeBack ()
template<class H >
H * getHandler (int i)
template<class H >
H * getHandler ()
template<class H >
ContextType< H >::type * getContext (int i)
template<class H >
ContextType< H >::type * getContext ()
template<class H >
bool setOwner (H *handler)
virtual void finalize ()=0
size_t numHandlers () const
Protected Member Functions
template<class Context >
void addContextFront (Context *ctx)
void detachHandlers ()
Protected Attributes
std::vector< std::shared_ptr< PipelineContext > > ctxs_
std::vector< PipelineContext * > inCtxs_
std::vector< PipelineContext * > outCtxs_
Private Types
typedef std::vector< std::shared_ptr< PipelineContext > >::iterator ContextIterator
Private Member Functions
template<class Context >
PipelineBase & addHelper (std::shared_ptr< Context > &&ctx, bool front)
template<class H >
PipelineBase & removeHelper (H *handler, bool checkEqual)
ContextIterator removeAt (const ContextIterator &it)
Private Attributes
PipelineManager * manager_ {nullptr}
std::shared_ptr< folly::AsyncTransport > transport_
std::shared_ptr< TransportInfo > transportInfo_
folly::WriteFlags writeFlags_ {folly::WriteFlags::NONE}
std::pair< uint64_t, uint64_t > readBufferSettings_ {2048, 2048}
std::shared_ptr< PipelineContext > owner_
Detailed Description
Definition at line 43 of file Pipeline.h.
Member Typedef Documentation
typedef std::vector<std::shared_ptr<PipelineContext> >::iterator wangle::PipelineBase::ContextIterator private
Definition at line 151 of file Pipeline.h.
Constructor & Destructor Documentation
virtual wangle::PipelineBase::~PipelineBase () virtual default
Member Function Documentation
template<class H > PipelineBase & wangle::PipelineBase::addBack (std::shared_ptr< H > handler)
Definition at line 39 of file Pipeline-inl.h.
References addHelper(), and folly::gen::move.
Referenced by addBack(), and wangle::ClientDispatcherBase< wangle::Pipeline, folly::Req, Resp >::setPipeline().
{
   typedef typename ContextType<H>::type Context;
   return addHelper(
       std::make_shared<Context>(shared_from_this(), std::move(handler)),
       false);
 }
template<class H > PipelineBase & wangle::PipelineBase::addBack (H && handler)
Definition at line 47 of file Pipeline-inl.h.
References addBack(), and handler().
{
   return addBack(std::make_shared<H>(std::forward<H>(handler)));
 }
template<class H > PipelineBase & wangle::PipelineBase::addBack (H * handler)
Definition at line 52 of file Pipeline-inl.h.
References addBack().
{
   return addBack(std::shared_ptr<H>(handler, [](H*){}));
 }
template<class Context > void wangle::PipelineBase::addContextFront (Context * ctx) protected
Definition at line 150 of file Pipeline-inl.h.
References addHelper().
Referenced by wangle::StaticPipeline< R, W, Handler, Handlers... >::StaticPipeline().
{
   addHelper(std::shared_ptr<Context>(ctx, [](Context*){}), true);
 }
template<class H > PipelineBase & wangle::PipelineBase::addFront (std::shared_ptr< H > handler)
Definition at line 57 of file Pipeline-inl.h.
References addHelper(), and folly::gen::move.
Referenced by addFront().
{
   typedef typename ContextType<H>::type Context;
   return addHelper(
       std::make_shared<Context>(shared_from_this(), std::move(handler)),
       true);
 }
template<class H > PipelineBase & wangle::PipelineBase::addFront (H && handler)
Definition at line 65 of file Pipeline-inl.h.
References addFront(), and handler().
{
   return addFront(std::make_shared<H>(std::forward<H>(handler)));
 }
template<class H > PipelineBase & wangle::PipelineBase::addFront (H * handler)
Definition at line 70 of file Pipeline-inl.h.
References addFront().
{
   return addFront(std::shared_ptr<H>(handler, [](H*){}));
 }
template<class Context > PipelineBase & wangle::PipelineBase::addHelper (std::shared_ptr< Context > && ctx, bool front) private
Definition at line 155 of file Pipeline-inl.h.
References wangle::BOTH, ctxs_, wangle::IN, inCtxs_, wangle::OUT, and outCtxs_.
Referenced by addBack(), addContextFront(), and addFront().
                 {
   ctxs_.insert(front ? ctxs_.begin() : ctxs_.end(), ctx);
   if (Context::dir == HandlerDir::BOTH || Context::dir == HandlerDir::IN) {
     inCtxs_.insert(front ? inCtxs_.begin() : inCtxs_.end(), ctx.get());
   }
   if (Context::dir == HandlerDir::BOTH || Context::dir == HandlerDir::OUT) {
     outCtxs_.insert(front ? outCtxs_.begin() : outCtxs_.end(), ctx.get());
   }
   return *this;
 }
void wangle::PipelineBase::deletePipeline () inline
Definition at line 55 of file Pipeline.h.
{
     if (manager_) {
       manager_->deletePipeline(this);
     }
   }
void wangle::PipelineBase::detachHandlers () protected
Definition at line 85 of file Pipeline.cpp.
References ctxs_, and owner_.
Referenced by wangle::Pipeline< R, W >::~Pipeline(), and wangle::StaticPipeline< R, W, Handler, Handlers... >::~StaticPipeline().
{
   for (auto& ctx : ctxs_) {
     if (ctx != owner_) {
       ctx->detachPipeline();
     }
   }
 }
virtual void wangle::PipelineBase::finalize () pure virtual
Implemented in wangle::Pipeline< R, W >, and wangle::Pipeline< int >.
Referenced by wangle::ClientDispatcherBase< wangle::Pipeline, folly::Req, Resp >::~ClientDispatcherBase().
template<class H > ContextType< H >::type * wangle::PipelineBase::getContext (int i)
Definition at line 119 of file Pipeline-inl.h.
References ctxs_, and i.
{
   auto ctx = dynamic_cast<typename ContextType<H>::type*>(ctxs_[i].get());
   CHECK(ctx);
   return ctx;
 }
template<class H > ContextType< H >::type * wangle::PipelineBase::getContext ()
Definition at line 126 of file Pipeline-inl.h.
References ctxs_.
{
   for (auto pipelineCtx : ctxs_) {
     auto ctx = dynamic_cast<typename ContextType<H>::type*>(pipelineCtx.get());
     if (ctx) {
       return ctx;
     }
   }
   return nullptr;
 }
template<class H > H * wangle::PipelineBase::getHandler (int i)
Definition at line 108 of file Pipeline-inl.h.
References getHandler(), and i.
{
   return getContext<H>(i)->getHandler();
 }
template<class H > H * wangle::PipelineBase::getHandler ()
Definition at line 113 of file Pipeline-inl.h.
Referenced by getHandler().
{
   auto ctx = getContext<H>();
   return ctx ? ctx->getHandler() : nullptr;
 }
PipelineManager* wangle::PipelineBase::getPipelineManager () inline
Definition at line 51 of file Pipeline.h.
Referenced by wangle::AsyncSocketHandler::refreshTimeout().
{
     return manager_;
   }
std::pair< uint64_t, uint64_t > wangle::PipelineBase::getReadBufferSettings ()
Definition at line 37 of file Pipeline.cpp.
References readBufferSettings_.
{
   return readBufferSettings_;
 }
std::shared_ptr<folly::AsyncTransport> wangle::PipelineBase::getTransport () inline
Definition at line 65 of file Pipeline.h.
References handler(), i, transport_, and uint64_t.
Referenced by wangle::HandlerContext< thrift::test::Bonk, std::unique_ptr< folly::IOBuf > >::getTransport(), wangle::InboundHandlerContext< M >::getTransport(), wangle::OutboundHandlerContext< Wout >::getTransport(), and TEST_F().
{
     return transport_;
   }
std::shared_ptr< TransportInfo > wangle::PipelineBase::getTransportInfo ()
Definition at line 45 of file Pipeline.cpp.
References transportInfo_.
{
   return transportInfo_;
 }
WriteFlags wangle::PipelineBase::getWriteFlags ()
Definition at line 27 of file Pipeline.cpp.
References writeFlags_.
{
   return writeFlags_;
 }
size_t wangle::PipelineBase::numHandlers () const
Definition at line 93 of file Pipeline.cpp.
References ctxs_.
{
   return ctxs_.size();
 }
template<class H > PipelineBase & wangle::PipelineBase::remove (H * handler)
Definition at line 103 of file Pipeline-inl.h.
References handler().
Referenced by wangle::ClientDispatcherBase< wangle::Pipeline, folly::Req, Resp >::~ClientDispatcherBase().
{
   return removeHelper<H>(handler, true);
 }
template<class H > PipelineBase & wangle::PipelineBase::remove ()
Definition at line 98 of file Pipeline-inl.h.
{
   return removeHelper<H>(nullptr, false);
 }
PipelineBase::ContextIterator wangle::PipelineBase::removeAt (const ContextIterator & it) private
Definition at line 49 of file Pipeline.cpp.
References wangle::BOTH, ctxs_, wangle::IN, inCtxs_, wangle::OUT, and outCtxs_.
Referenced by removeBack(), removeFront(), and removeHelper().
{
   (*it)->detachPipeline();
   const auto dir = (*it)->getDirection();
   if (dir == HandlerDir::BOTH || dir == HandlerDir::IN) {
     auto it2 = std::find(inCtxs_.begin(), inCtxs_.end(), it->get());
     CHECK(it2 != inCtxs_.end());
     inCtxs_.erase(it2);
   }
   if (dir == HandlerDir::BOTH || dir == HandlerDir::OUT) {
     auto it2 = std::find(outCtxs_.begin(), outCtxs_.end(), it->get());
     CHECK(it2 != outCtxs_.end());
     outCtxs_.erase(it2);
   }
   return ctxs_.erase(it);
 }
PipelineBase & wangle::PipelineBase::removeBack ()
Definition at line 77 of file Pipeline.cpp.
References ctxs_, and removeAt().
{
   if (ctxs_.empty()) {
     throw std::invalid_argument("No handlers in pipeline");
   }
   removeAt(--ctxs_.end());
   return *this;
 }
PipelineBase & wangle::PipelineBase::removeFront ()
Definition at line 69 of file Pipeline.cpp.
References ctxs_, and removeAt().
{
   if (ctxs_.empty()) {
     throw std::invalid_argument("No handlers in pipeline");
   }
   removeAt(ctxs_.begin());
   return *this;
 }
template<class H > PipelineBase & wangle::PipelineBase::removeHelper (H * handler, bool checkEqual) private
Definition at line 75 of file Pipeline-inl.h.
References ctxs_, handler(), and removeAt().
{
   typedef typename ContextType<H>::type Context;
   bool removed = false;
   auto it = ctxs_.begin();
   while (it != ctxs_.end()) {
     auto ctx = std::dynamic_pointer_cast<Context>(*it);
     if (ctx && (!checkEqual || ctx->getHandler() == handler)) {
       it = removeAt(it);
       removed = true;
     } else {
       it++;
     }
   }
   if (!removed) {
     throw std::invalid_argument("No such handler in pipeline");
   }
   return *this;
 }
template<class H > bool wangle::PipelineBase::setOwner (H * handler)
Definition at line 137 of file Pipeline-inl.h.
References ctxs_, handler(), and owner_.
{
   typedef typename ContextType<H>::type Context;
   for (auto& ctx : ctxs_) {
     auto ctxImpl = dynamic_cast<Context*>(ctx.get());
     if (ctxImpl && ctxImpl->getHandler() == handler) {
       owner_ = ctx;
       return true;
     }
   }
   return false;
 }
void wangle::PipelineBase::setPipelineManager (PipelineManager * manager) inline
Definition at line 47 of file Pipeline.h.
Referenced by wangle::BroadcastPool< T, R, P >::BroadcastManager::getHandler().
{
     manager_ = manager;
   }
void wangle::PipelineBase::setReadBufferSettings (uint64_t minAvailable, uint64_t allocationSize)
Definition at line 31 of file Pipeline.cpp.
References readBufferSettings_.
{
   readBufferSettings_ = std::make_pair(minAvailable, allocationSize);
 }
void wangle::PipelineBase::setTransport (std::shared_ptr< folly::AsyncTransport > transport) inline
Definition at line 61 of file Pipeline.h.
References transport_.
{
     transport_ = transport;
   }
void wangle::PipelineBase::setTransportInfo (std::shared_ptr< TransportInfo > tInfo)
Definition at line 41 of file Pipeline.cpp.
References transportInfo_.
{
   transportInfo_ = tInfo;
 }
void wangle::PipelineBase::setWriteFlags (folly::WriteFlags flags)
Definition at line 23 of file Pipeline.cpp.
References writeFlags_.
{
   writeFlags_ = flags;
 }
Member Data Documentation
std::vector<std::shared_ptr<PipelineContext> > wangle::PipelineBase::ctxs_ protected
Definition at line 135 of file Pipeline.h.
Referenced by addHelper(), detachHandlers(), wangle::Pipeline< R, W >::finalize(), getContext(), numHandlers(), removeAt(), removeBack(), removeFront(), removeHelper(), and setOwner().
std::vector<PipelineContext*> wangle::PipelineBase::inCtxs_ protected
Definition at line 136 of file Pipeline.h.
Referenced by addHelper(), wangle::Pipeline< R, W >::finalize(), and removeAt().
PipelineManager* wangle::PipelineBase::manager_ {nullptr} private
Definition at line 140 of file Pipeline.h.
std::vector<PipelineContext*> wangle::PipelineBase::outCtxs_ protected
Definition at line 137 of file Pipeline.h.
Referenced by addHelper(), wangle::Pipeline< R, W >::finalize(), and removeAt().
std::shared_ptr<PipelineContext> wangle::PipelineBase::owner_ private
Definition at line 158 of file Pipeline.h.
Referenced by detachHandlers(), and setOwner().
std::pair<uint64_t, uint64_t> wangle::PipelineBase::readBufferSettings_ {2048, 2048} private
Definition at line 156 of file Pipeline.h.
Referenced by getReadBufferSettings(), and setReadBufferSettings().
std::shared_ptr<folly::AsyncTransport> wangle::PipelineBase::transport_ private
Definition at line 141 of file Pipeline.h.
std::shared_ptr<TransportInfo> wangle::PipelineBase::transportInfo_ private
Definition at line 142 of file Pipeline.h.
Referenced by getTransportInfo(), and setTransportInfo().
folly::WriteFlags wangle::PipelineBase::writeFlags_ {folly::WriteFlags::NONE} private
Definition at line 155 of file Pipeline.h.
Referenced by getWriteFlags(), and setWriteFlags().
The documentation for this class was generated from the following files:
proxygen/wangle/wangle/channel/Pipeline.h
proxygen/wangle/wangle/channel/Pipeline-inl.h
proxygen/wangle/wangle/channel/Pipeline.cpp