proxygen: wangle::AsyncUDPServerSocketFactory Class Reference
wangle::AsyncUDPServerSocketFactory Class Reference
#include <ServerSocketFactory.h>
Classes
class ThreadSafeDestructor
Public Member Functions
std::shared_ptr< folly::AsyncSocketBase > newSocket (folly::SocketAddress address, int, bool reuse, const ServerSocketConfig &) override
void removeAcceptCB (std::shared_ptr< folly::AsyncSocketBase >, Acceptor *, folly::EventBase *) override
void addAcceptCB (std::shared_ptr< folly::AsyncSocketBase > s, Acceptor *callback, folly::EventBase *base) override
Public Member Functions inherited from wangle::ServerSocketFactory
virtual ~ServerSocketFactory ()=default
Detailed Description
Definition at line 98 of file ServerSocketFactory.h.
Member Function Documentation
void wangle::AsyncUDPServerSocketFactory::addAcceptCB (std::shared_ptr< folly::AsyncSocketBase > s, Acceptor * callback, folly::EventBase * base) inline override virtual
Implements wangle::ServerSocketFactory.
Definition at line 120 of file ServerSocketFactory.h.
References s, and folly::netops::socket().
{
     auto socket = std::dynamic_pointer_cast<folly::AsyncUDPServerSocket>(s);
     DCHECK(socket);
     socket->addListener(base, callback);
   }
std::shared_ptr<folly::AsyncSocketBase> wangle::AsyncUDPServerSocketFactory::newSocket (folly::SocketAddress address, int , bool reuse, const ServerSocketConfig &) inline override virtual
Implements wangle::ServerSocketFactory.
Definition at line 100 of file ServerSocketFactory.h.
References folly::EventBaseManager::get(), folly::EventBaseManager::getEventBase(), and folly::netops::socket().
{
     folly::EventBase* evb = folly::EventBaseManager::get()->getEventBase();
     std::shared_ptr<folly::AsyncUDPServerSocket> socket(
         new folly::AsyncUDPServerSocket(evb),
         ThreadSafeDestructor());
     socket->setReusePort(reuse);
     socket->bind(address);
     socket->listen();
     return socket;
   }
void wangle::AsyncUDPServerSocketFactory::removeAcceptCB (std::shared_ptr< folly::AsyncSocketBase > , Acceptor * , folly::EventBase *) inline override virtual
Implements wangle::ServerSocketFactory.
Definition at line 115 of file ServerSocketFactory.h.
{
   }
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/bootstrap/ServerSocketFactory.h