proxygen: folly::gen::detail::RangeConcat::Generator< Range, Source, InnerValue > Class Template Reference
folly::gen::detail::RangeConcat::Generator< Range, Source, InnerValue > Class Template Reference
#include <Base-inl.h>
Public Member Functions
Generator (Source source)
template<class Body >
void foreach (Body &&body) const
template<class Handler >
bool apply (Handler &&handler) const
Public Member Functions inherited from folly::gen::GenImpl< InnerValue, Generator< Range, Source, InnerValue > >
bool apply (Handler &&handler) const
void foreach (Body &&body) const
Public Member Functions inherited from folly::gen::FBounded< Self >
const Self & self () const
Self & self ()
Static Public Attributes
static constexpr bool infinite = Source::infinite
Static Public Attributes inherited from folly::gen::GenImpl< InnerValue, Generator< Range, Source, InnerValue > >
static constexpr bool infinite
Private Attributes
Source source_
Additional Inherited Members
Public Types inherited from folly::gen::GenImpl< InnerValue, Generator< Range, Source, InnerValue > >
typedef InnerValue ValueType
typedef std::decay< InnerValue >::type StorageType
Protected Member Functions inherited from folly::gen::GenImpl< InnerValue, Generator< Range, Source, InnerValue > >
GenImpl ()=default
GenImpl (GenImpl &&)=default
GenImpl (const GenImpl &)=default
GenImpl & operator= (GenImpl &&)=default
GenImpl & operator= (const GenImpl &)=default
Detailed Description
template<class Range, class Source, class InnerValue = typename ValueTypeOfRange<Range>::RefType>
class folly::gen::detail::RangeConcat::Generator< Range, Source, InnerValue >
Definition at line 1686 of file Base-inl.h.
Constructor & Destructor Documentation
template<class Range , class Source , class InnerValue = typename ValueTypeOfRange<Range>::RefType> folly::gen::detail::RangeConcat::Generator< Range, Source, InnerValue >::Generator (Source source) inline explicit
Definition at line 1691 of file Base-inl.h.
 : source_(std::move(source)) {}
Member Function Documentation
template<class Range , class Source , class InnerValue = typename ValueTypeOfRange<Range>::RefType> template<class Handler > bool folly::gen::detail::RangeConcat::Generator< Range, Source, InnerValue >::apply (Handler && handler) const inline
Definition at line 1703 of file Base-inl.h.
References handler(), folly::gen::range(), and value.
{
       return source_.apply([&](Range range) -> bool {
         for (auto& value : range) {
           if (!handler(value)) {
             return false;
           }
         }
         return true;
       });
     }
template<class Range , class Source , class InnerValue = typename ValueTypeOfRange<Range>::RefType> template<class Body > void folly::gen::detail::RangeConcat::Generator< Range, Source, InnerValue >::foreach (Body && body) const inline
Definition at line 1694 of file Base-inl.h.
References folly::gen::range(), and value.
{
       source_.foreach([&](Range range) {
         for (auto& value : range) {
           body(value);
         }
       });
     }
Member Data Documentation
template<class Range , class Source , class InnerValue = typename ValueTypeOfRange<Range>::RefType> constexpr bool folly::gen::detail::RangeConcat::Generator< Range, Source, InnerValue >::infinite = Source::infinite static
Definition at line 1716 of file Base-inl.h.
template<class Range , class Source , class InnerValue = typename ValueTypeOfRange<Range>::RefType> Source folly::gen::detail::RangeConcat::Generator< Range, Source, InnerValue >::source_ private
Definition at line 1688 of file Base-inl.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/gen/Base-inl.h