proxygen: folly::LeakySingleton< T, Tag > Class Template Reference
folly::LeakySingleton< T, Tag > Class Template Reference
#include <Singleton.h>
Classes
struct Entry
Public Types
using CreateFunc = std::function< T *()>
Public Member Functions
LeakySingleton ()
LeakySingleton (CreateFunc createFunc)
Static Public Member Functions
static T & get ()
static void make_mock (std::nullptr_t=nullptr)
static void make_mock (CreateFunc createFunc)
Private Types
enum State { State::NotRegistered, State::Dead, State::Living }
Static Private Member Functions
static Entry & entryInstance ()
static T & instance ()
static void createInstance ()
Detailed Description
template<typename T, typename Tag = detail::DefaultTag>
class folly::LeakySingleton< T, Tag >
Definition at line 695 of file Singleton.h.
Member Typedef Documentation
template<typename T , typename Tag = detail::DefaultTag> using folly::LeakySingleton< T, Tag >::CreateFunc = std::function<T*()>
Definition at line 697 of file Singleton.h.
Member Enumeration Documentation
template<typename T , typename Tag = detail::DefaultTag> enum folly::LeakySingleton::State strong private
Enumerator
NotRegistered
Dead
Living
Definition at line 733 of file Singleton.h.
 { NotRegistered, Dead, Living };
Constructor & Destructor Documentation
template<typename T , typename Tag = detail::DefaultTag> folly::LeakySingleton< T, Tag >::LeakySingleton () inline
Definition at line 699 of file Singleton.h.
References folly::T.
 : LeakySingleton([] { return new T(); }) {}
template<typename T , typename Tag = detail::DefaultTag> folly::LeakySingleton< T, Tag >::LeakySingleton (CreateFunc createFunc) inline explicit
Definition at line 701 of file Singleton.h.
References folly::detail::singletonWarnLeakyDoubleRegistrationAndAbort().
{
     auto& entry = entryInstance();
     if (entry.state != State::NotRegistered) {
       detail::singletonWarnLeakyDoubleRegistrationAndAbort(entry.type_);
     }
     entry.createFunc = createFunc;
     entry.state = State::Dead;
   }
Member Function Documentation
template<typename T , typename Tag = detail::DefaultTag> static void folly::LeakySingleton< T, Tag >::createInstance () inline static private
Definition at line 762 of file Singleton.h.
References folly::detail::singletonWarnLeakyInstantiatingNotRegisteredAndAbort().
{
     auto& entry = entryInstance();
     std::lock_guard<std::mutex> lg(entry.mutex);
     if (entry.state == State::Living) {
       return;
     }
     if (entry.state == State::NotRegistered) {
       detail::singletonWarnLeakyInstantiatingNotRegisteredAndAbort(entry.type_);
     }
     entry.ptr = entry.createFunc();
     entry.state = State::Living;
   }
template<typename T , typename Tag = detail::DefaultTag> static Entry& folly::LeakySingleton< T, Tag >::entryInstance () inline static private
Definition at line 748 of file Singleton.h.
{
     /* library-local */ static auto entry = detail::createGlobal<Entry, Tag>();
     return *entry;
   }
template<typename T , typename Tag = detail::DefaultTag> static T& folly::LeakySingleton< T, Tag >::get () inline static
Definition at line 710 of file Singleton.h.
                   {
     return instance();
   }
template<typename T , typename Tag = detail::DefaultTag> static T& folly::LeakySingleton< T, Tag >::instance () inline static private
Definition at line 753 of file Singleton.h.
References UNLIKELY.
{
     auto& entry = entryInstance();
     if (UNLIKELY(entry.state != State::Living)) {
       createInstance();
     }
     return *entry.ptr;
   }
template<typename T , typename Tag = detail::DefaultTag> static void folly::LeakySingleton< T, Tag >::make_mock (std::nullptr_t = nullptr) inline static
Definition at line 714 of file Singleton.h.
References folly::T.
{
     make_mock([]() { return new T; });
   }
template<typename T , typename Tag = detail::DefaultTag> static void folly::LeakySingleton< T, Tag >::make_mock (CreateFunc createFunc) inline static
Definition at line 718 of file Singleton.h.
References folly::exchange(), folly::detail::singletonThrowNullCreator(), and folly::T.
{
     if (createFunc == nullptr) {
       detail::singletonThrowNullCreator(typeid(T));
     }
     auto& entry = entryInstance();
     if (entry.ptr) {
       // Make sure existing pointer doesn't get reported as a leak by LSAN.
       entry.leakedPtrs.push_back(std::exchange(entry.ptr, nullptr));
     }
     entry.createFunc = createFunc;
     entry.state = State::Dead;
   }
The documentation for this class was generated from the following file:
proxygen/folly/folly/Singleton.h