proxygen: folly::coro::detail::ViaCoroutine Class Reference
folly::coro::detail::ViaCoroutine Class Reference
#include <ViaIfAsync.h>
Classes
class promise_type
Public Member Functions
ViaCoroutine (ViaCoroutine &&other) noexcept
~ViaCoroutine ()
ViaCoroutine & operator= (ViaCoroutine other) noexcept
void swap (ViaCoroutine &other) noexcept
std::experimental::coroutine_handle getWrappedCoroutine (std::experimental::coroutine_handle<> continuation) noexcept
void destroy ()
Static Public Member Functions
static ViaCoroutine create (folly::Executor *executor)
static ViaCoroutine createInline () noexcept
Private Member Functions
ViaCoroutine (std::experimental::coroutine_handle< promise_type > coro) noexcept
Private Attributes
std::experimental::coroutine_handle< promise_type > coro_
Friends
class promise_type
Detailed Description
Definition at line 34 of file ViaIfAsync.h.
Constructor & Destructor Documentation
folly::coro::detail::ViaCoroutine::ViaCoroutine (ViaCoroutine && other) inline noexcept
Definition at line 84 of file ViaIfAsync.h.
       : coro_(std::exchange(other.coro_, {})) {}
folly::coro::detail::ViaCoroutine::~ViaCoroutine () inline
Definition at line 87 of file ViaIfAsync.h.
References destroy().
                   {
     destroy();
   }
folly::coro::detail::ViaCoroutine::ViaCoroutine (std::experimental::coroutine_handle< promise_type > coro) inline explicit private noexcept
Definition at line 127 of file ViaIfAsync.h.
       : coro_(coro) {}
Member Function Documentation
static ViaCoroutine folly::coro::detail::ViaCoroutine::create (folly::Executor * executor) inline static
Definition at line 116 of file ViaIfAsync.h.
{
     co_return;
   }
static ViaCoroutine folly::coro::detail::ViaCoroutine::createInline () inline static noexcept
Definition at line 120 of file ViaIfAsync.h.
{
     return ViaCoroutine{std::experimental::coroutine_handle<promise_type>{}};
   }
void folly::coro::detail::ViaCoroutine::destroy () inline
Definition at line 110 of file ViaIfAsync.h.
References coro_, and folly::exchange().
Referenced by ~ViaCoroutine().
                  {
     if (coro_) {
       std::exchange(coro_, {}).destroy();
     }
   }
std::experimental::coroutine_handle folly::coro::detail::ViaCoroutine::getWrappedCoroutine (std::experimental::coroutine_handle<> continuation) inline noexcept
Definition at line 100 of file ViaIfAsync.h.
References coro_.
{
     if (coro_) {
       coro_.promise().setContinuation(continuation);
       return coro_;
     } else {
       return continuation;
     }
   }
ViaCoroutine& folly::coro::detail::ViaCoroutine::operator= (ViaCoroutine other) inline noexcept
Definition at line 91 of file ViaIfAsync.h.
References swap().
{
     swap(other);
     return *this;
   }
void folly::coro::detail::ViaCoroutine::swap (ViaCoroutine & other) inline noexcept
Definition at line 96 of file ViaIfAsync.h.
References coro_, and folly::f14::swap().
Referenced by operator=().
{
     std::swap(coro_, other.coro_);
   }
Friends And Related Function Documentation
friend class promise_type friend
Definition at line 125 of file ViaIfAsync.h.
Member Data Documentation
std::experimental::coroutine_handle<promise_type> folly::coro::detail::ViaCoroutine::coro_ private
Definition at line 131 of file ViaIfAsync.h.
Referenced by destroy(), getWrappedCoroutine(), and swap().
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/coro/ViaIfAsync.h