proxygen: fizz::AsyncFizzBase::HandshakeTimeout Class Reference
fizz::AsyncFizzBase::HandshakeTimeout Class Reference
#include <AsyncFizzBase.h>
Public Member Functions
HandshakeTimeout (AsyncFizzBase &transport, folly::EventBase *eventBase)
~HandshakeTimeout () override=default
void timeoutExpired () noexceptoverride
Public Member Functions inherited from folly::AsyncTimeout
AsyncTimeout (TimeoutManager *timeoutManager)
AsyncTimeout (EventBase *eventBase)
AsyncTimeout (TimeoutManager *timeoutManager, InternalEnum internal)
AsyncTimeout (EventBase *eventBase, InternalEnum internal)
AsyncTimeout ()
virtual ~AsyncTimeout ()
bool scheduleTimeout (uint32_t milliseconds)
bool scheduleTimeout (TimeoutManager::timeout_type timeout)
void cancelTimeout ()
bool isScheduled () const
void attachTimeoutManager (TimeoutManager *timeoutManager, InternalEnum internal=InternalEnum::NORMAL)
void attachEventBase (EventBase *eventBase, InternalEnum internal=InternalEnum::NORMAL)
void detachTimeoutManager ()
void detachEventBase ()
const TimeoutManager * getTimeoutManager ()
struct event * getEvent ()
Private Attributes
AsyncFizzBase & transport_
Additional Inherited Members
Public Types inherited from folly::AsyncTimeout
typedef TimeoutManager::InternalEnum InternalEnum
Static Public Member Functions inherited from folly::AsyncTimeout
template<typename TCallback >
static std::unique_ptr< AsyncTimeout > make (TimeoutManager &manager, TCallback &&callback)
template<typename TCallback >
static std::unique_ptr< AsyncTimeout > schedule (TimeoutManager::timeout_type timeout, TimeoutManager &manager, TCallback &&callback)
Detailed Description
Definition at line 33 of file AsyncFizzBase.h.
Constructor & Destructor Documentation
fizz::AsyncFizzBase::HandshakeTimeout::HandshakeTimeout (AsyncFizzBase & transport, folly::EventBase * eventBase) inline
Definition at line 35 of file AsyncFizzBase.h.
References ~HandshakeTimeout().
         : folly::AsyncTimeout(eventBase), transport_(transport) {}
fizz::AsyncFizzBase::HandshakeTimeout::~HandshakeTimeout () override default
Referenced by HandshakeTimeout().
Member Function Documentation
void fizz::AsyncFizzBase::HandshakeTimeout::timeoutExpired () inline override virtual noexcept
timeoutExpired() is invoked when the timeout period has expired.
Implements folly::AsyncTimeout.
Definition at line 40 of file AsyncFizzBase.h.
References fizz::AsyncFizzBase::handshakeTimeoutExpired(), and transport_.
{
       transport_.handshakeTimeoutExpired();
     }
Member Data Documentation
AsyncFizzBase& fizz::AsyncFizzBase::HandshakeTimeout::transport_ private
Definition at line 45 of file AsyncFizzBase.h.
Referenced by fizz::AsyncFizzBase::attachEventBase(), fizz::AsyncFizzBase::detachEventBase(), fizz::AsyncFizzBase::isDetachable(), and timeoutExpired().
The documentation for this class was generated from the following file:
proxygen/fizz/fizz/protocol/AsyncFizzBase.h