proxygen: AcceptRoutingHandlerTest Class Reference
AcceptRoutingHandlerTest Class Reference
Public Member Functions
void SetUp () override
EventBase * getEventBase ()
Future< DefaultPipeline * > clientConnect ()
Future< DefaultPipeline * > clientConnectAndWrite ()
Future< DefaultPipeline * > clientConnectAndCleanClose ()
Future< DefaultPipeline * > justClientConnect ()
void sendClientException (DefaultPipeline *clientPipeline)
void TearDown () override
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Protected Attributes
std::unique_ptr< TestServer > server_
std::shared_ptr< MockAcceptPipelineFactory > acceptPipelineFactory_
AcceptPipeline::Ptr acceptPipeline_
DefaultPipeline::Ptr routingPipeline_
std::shared_ptr< MockRoutingDataHandlerFactory > routingDataHandlerFactory_
MockRoutingDataHandler * routingDataHandler_
MockAcceptRoutingHandler * acceptRoutingHandler_
MockBytesToBytesHandler * downstreamHandler_
std::shared_ptr< MockDownstreamPipelineFactory > downstreamPipelineFactory_
SocketAddress address_
RoutingDataHandler< char >::RoutingData routingData_
std::shared_ptr< TestClient > client_
int kConnId0 {0}
int kNumIOThreads {1}
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Protected Member Functions inherited from testing::Test
Test ()
Test ()
Test ()
Detailed Description
Definition at line 39 of file AcceptRoutingHandlerTest.cpp.
Member Function Documentation
Future<DefaultPipeline*> AcceptRoutingHandlerTest::clientConnect () inline
Definition at line 85 of file AcceptRoutingHandlerTest.cpp.
{
     client_ = std::make_shared<TestClient>();
     client_->pipelineFactory(std::make_shared<TestClientPipelineFactory>());
     client_->group(server_->getIOGroup());
     return client_->connect(address_);
   }
Future<DefaultPipeline*> AcceptRoutingHandlerTest::clientConnectAndCleanClose () inline
Definition at line 111 of file AcceptRoutingHandlerTest.cpp.
References wangle::Pipeline< R, W >::close(), folly::getEventBase(), and folly::EventBase::runInEventBaseThread().
{
     auto clientPipelinePromise =
         std::make_shared<folly::Promise<DefaultPipeline*>>();
     getEventBase()->runInEventBaseThread([=]() {
       clientConnectAndWrite().thenValue([=](DefaultPipeline* clientPipeline) {
         VLOG(4) << "Client close";
         clientPipeline->close().thenValue(
             [=](auto&&) { clientPipelinePromise->setValue(clientPipeline); });
       });
     });
     return clientPipelinePromise->getFuture();
   }
Future<DefaultPipeline*> AcceptRoutingHandlerTest::clientConnectAndWrite () inline
Definition at line 92 of file AcceptRoutingHandlerTest.cpp.
References folly::IOBuf::create(), folly::data(), folly::getEventBase(), folly::gen::move, folly::EventBase::runInEventBaseThread(), and wangle::Pipeline< R, W >::write().
{
     auto clientPipelinePromise =
         std::make_shared<folly::Promise<DefaultPipeline*>>();
     getEventBase()->runInEventBaseThread([=]() {
       clientConnect().thenValue([=](DefaultPipeline* clientPipeline) {
         VLOG(4) << "Client connected. Send data.";
         auto data = IOBuf::create(1);
         data->append(1);
         *(data->writableData()) = 'a';
         clientPipeline->write(std::move(data)).thenValue([=](auto&&) {
           clientPipelinePromise->setValue(clientPipeline);
         });
       });
     });
     return clientPipelinePromise->getFuture();
   }
EventBase* AcceptRoutingHandlerTest::getEventBase () inline
Definition at line 81 of file AcceptRoutingHandlerTest.cpp.
References folly::EventBase::getEventBase().
{
     return server_->getIOGroup()->getEventBase();
   }
Future<DefaultPipeline*> AcceptRoutingHandlerTest::justClientConnect () inline
Definition at line 126 of file AcceptRoutingHandlerTest.cpp.
References folly::getEventBase(), and folly::EventBase::runInEventBaseThread().
{
     auto clientPipelinePromise =
         std::make_shared<folly::Promise<DefaultPipeline*>>();
     getEventBase()->runInEventBaseThread([=]() {
       clientConnect().thenValue([=](DefaultPipeline* clientPipeline) {
         clientPipelinePromise->setValue(clientPipeline);
       });
     });
     return clientPipelinePromise->getFuture();
   }
void AcceptRoutingHandlerTest::sendClientException (DefaultPipeline * clientPipeline) inline
Definition at line 138 of file AcceptRoutingHandlerTest.cpp.
References folly::getEventBase(), folly::EventBase::runInEventBaseThread(), and wangle::Pipeline< R, W >::writeException().
{
     getEventBase()->runInEventBaseThread([=]() {
       clientPipeline->writeException(
           std::runtime_error("Client socket exception, right after connect."));
     });
   }
void AcceptRoutingHandlerTest::SetUp () inline override virtual
Reimplemented from testing::Test.
Definition at line 41 of file AcceptRoutingHandlerTest.cpp.
{
     routingData_.routingData = 'A';
     downstreamHandler_ = new MockBytesToBytesHandler();
     downstreamPipelineFactory_ =
         std::make_shared<MockDownstreamPipelineFactory>(downstreamHandler_);
     server_ = std::make_unique<TestServer>();
     // A routing pipeline with a mock routing handler that we can set
     // expectations on.
     routingPipeline_ = DefaultPipeline::create();
     routingDataHandlerFactory_ =
         std::make_shared<MockRoutingDataHandlerFactory>();
     acceptRoutingHandler_ = new MockAcceptRoutingHandler(
         server_.get(),
         routingDataHandlerFactory_,
         downstreamPipelineFactory_,
         routingPipeline_);
     routingDataHandler_ =
         new MockRoutingDataHandler(kConnId0, acceptRoutingHandler_);
     routingDataHandlerFactory_->setRoutingDataHandler(routingDataHandler_);
     acceptPipeline_ = AcceptPipeline::create();
     acceptPipeline_->addBack(
         std::shared_ptr<MockAcceptRoutingHandler>(acceptRoutingHandler_));
     acceptPipeline_->finalize();
     // A single threaded IOGroup shared between client and server for a
     // deterministic event list.
     auto ioGroup = std::make_shared<IOThreadPoolExecutor>(kNumIOThreads);
     acceptPipelineFactory_ =
         std::make_shared<MockAcceptPipelineFactory>(acceptPipeline_);
     server_->pipeline(acceptPipelineFactory_)->group(ioGroup, ioGroup)->bind(0);
     server_->getSockets()[0]->getAddress(&address_);
     VLOG(4) << "Start server at " << address_;
   }
void AcceptRoutingHandlerTest::TearDown () inline override virtual
Reimplemented from testing::Test.
Definition at line 145 of file AcceptRoutingHandlerTest.cpp.
{
     acceptPipeline_.reset();
     acceptPipelineFactory_->cleanup();
   }
Member Data Documentation
AcceptPipeline::Ptr AcceptRoutingHandlerTest::acceptPipeline_ protected
Definition at line 153 of file AcceptRoutingHandlerTest.cpp.
std::shared_ptr<MockAcceptPipelineFactory> AcceptRoutingHandlerTest::acceptPipelineFactory_ protected
Definition at line 152 of file AcceptRoutingHandlerTest.cpp.
MockAcceptRoutingHandler* AcceptRoutingHandlerTest::acceptRoutingHandler_ protected
Definition at line 158 of file AcceptRoutingHandlerTest.cpp.
SocketAddress AcceptRoutingHandlerTest::address_ protected
Definition at line 161 of file AcceptRoutingHandlerTest.cpp.
std::shared_ptr<TestClient> AcceptRoutingHandlerTest::client_ protected
Definition at line 164 of file AcceptRoutingHandlerTest.cpp.
MockBytesToBytesHandler* AcceptRoutingHandlerTest::downstreamHandler_ protected
Definition at line 159 of file AcceptRoutingHandlerTest.cpp.
std::shared_ptr<MockDownstreamPipelineFactory> AcceptRoutingHandlerTest::downstreamPipelineFactory_ protected
Definition at line 160 of file AcceptRoutingHandlerTest.cpp.
int AcceptRoutingHandlerTest::kConnId0 {0} protected
Definition at line 166 of file AcceptRoutingHandlerTest.cpp.
int AcceptRoutingHandlerTest::kNumIOThreads {1} protected
Definition at line 167 of file AcceptRoutingHandlerTest.cpp.
RoutingDataHandler<char>::RoutingData AcceptRoutingHandlerTest::routingData_ protected
Definition at line 162 of file AcceptRoutingHandlerTest.cpp.
MockRoutingDataHandler* AcceptRoutingHandlerTest::routingDataHandler_ protected
Definition at line 156 of file AcceptRoutingHandlerTest.cpp.
std::shared_ptr<MockRoutingDataHandlerFactory> AcceptRoutingHandlerTest::routingDataHandlerFactory_ protected
Definition at line 155 of file AcceptRoutingHandlerTest.cpp.
DefaultPipeline::Ptr AcceptRoutingHandlerTest::routingPipeline_ protected
Definition at line 154 of file AcceptRoutingHandlerTest.cpp.
std::unique_ptr<TestServer> AcceptRoutingHandlerTest::server_ protected
Definition at line 151 of file AcceptRoutingHandlerTest.cpp.
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/bootstrap/test/AcceptRoutingHandlerTest.cpp