proxygen: folly::Executor Class Reference
folly::Executor Class Reference abstract
#include <Executor.h>
Classes
class KeepAlive
Public Member Functions
virtual ~Executor ()
virtual void add (Func)=0
virtual void addWithPriority (Func, int8_t priority)
virtual uint8_t getNumPriorities () const
Static Public Member Functions
template<typename ExecutorT >
static KeepAlive< ExecutorT > getKeepAliveToken (ExecutorT *executor)
template<typename ExecutorT >
static KeepAlive< ExecutorT > getKeepAliveToken (ExecutorT &executor)
Static Public Attributes
static const int8_t LO_PRI = SCHAR_MIN
static const int8_t MID_PRI = 0
static const int8_t HI_PRI = SCHAR_MAX
Protected Member Functions
virtual bool keepAliveAcquire ()
virtual void keepAliveRelease ()
Static Protected Member Functions
template<typename ExecutorT >
static bool isKeepAliveDummy (const KeepAlive< ExecutorT > &keepAlive)
template<typename ExecutorT >
static KeepAlive< ExecutorT > makeKeepAlive (ExecutorT *executor)
Static Private Member Functions
template<typename ExecutorT >
static KeepAlive< ExecutorT > makeKeepAliveDummy (ExecutorT *executor)
Detailed Description
An Executor accepts units of work with add(), which should be threadsafe.
Definition at line 31 of file Executor.h.
Constructor & Destructor Documentation
virtual folly::Executor::~Executor () inline virtual
Definition at line 34 of file Executor.h.
References add(), addWithPriority(), and int8_t.
 {}
Member Function Documentation
virtual void folly::Executor::add (Func) pure virtual
Enqueue a function to executed by this executor. This and all variants must be threadsafe.
Implemented in folly::EventBase, folly::futures::detail::WaitExecutor, folly::futures::detail::DeferredExecutor, folly::fibers::FiberManager, folly::VirtualEventBase, folly::CPUThreadPoolExecutor, folly::SerialExecutor, folly::VirtualExecutor, folly::ThreadedExecutor, folly::ThreadPoolExecutor, folly::TimedDrivableExecutor, folly::IOThreadPoolExecutor, folly::DefaultKeepAliveExecutor::WeakRef, folly::ScopedEventBaseThread, ThrowingExecutor, folly::ManualExecutor, folly::FiberIOExecutor, folly::InlineExecutor, folly::python::AsyncioExecutor, folly::ScheduledExecutor, folly::python::GILAwareManualExecutor, folly::TestExecutor, folly::QueuedImmediateExecutor, and folly::KeepAliveTestExecutor.
Referenced by folly::SingletonVault::doEagerInitVia(), folly::isSequencedExecutor(), folly::fibers::ExecutorLoopController::schedule(), folly::fibers::ExecutorLoopController::scheduleThreadSafe(), and ~Executor().
void folly::Executor::addWithPriority (Func , int8_t priority) virtual
Enqueue a function with a given priority, where 0 is the medium priority This is up to the implementation to enforce
Reimplemented in folly::CPUThreadPoolExecutor, folly::SerialExecutor, folly::VirtualExecutor, and folly::DefaultKeepAliveExecutor::WeakRef.
Definition at line 25 of file Executor.cpp.
Referenced by TEST(), and ~Executor().
{
   throw std::runtime_error(
       "addWithPriority() is not implemented for this Executor");
 }
template<typename ExecutorT > static KeepAlive<ExecutorT> folly::Executor::getKeepAliveToken (ExecutorT * executor) inline static
Definition at line 138 of file Executor.h.
References folly::pushmi::executor, keepAliveAcquire(), and value.
Referenced by folly::SerialExecutor::add(), folly::SerialExecutor::addWithPriority(), folly::Executor::KeepAlive< folly::VirtualEventBase >::copy(), folly::SerialExecutor::createUnique(), getKeepAliveToken(), folly::getKeepAliveToken(), folly::isSequencedExecutor(), folly::VirtualEventBase::runInEventBaseThread(), folly::TEST(), and folly::VirtualExecutor::wrapFunc().
{
     static_assert(
         std::is_base_of<Executor, ExecutorT>::value,
         "getKeepAliveToken only works for folly::Executor implementations.");
     if (!executor) {
       return {};
     }
     folly::Executor* executorPtr = executor;
     if (executorPtr->keepAliveAcquire()) {
       return makeKeepAlive<ExecutorT>(executor);
     }
     return makeKeepAliveDummy<ExecutorT>(executor);
   }
template<typename ExecutorT > static KeepAlive<ExecutorT> folly::Executor::getKeepAliveToken (ExecutorT & executor) inline static
Definition at line 153 of file Executor.h.
References getKeepAliveToken(), and value.
{
     static_assert(
         std::is_base_of<Executor, ExecutorT>::value,
         "getKeepAliveToken only works for folly::Executor implementations.");
     return getKeepAliveToken(&executor);
   }
virtual uint8_t folly::Executor::getNumPriorities () const inline virtual
Reimplemented in PriorityExecutor, folly::CPUThreadPoolExecutor, folly::SerialExecutor, folly::DefaultKeepAliveExecutor::WeakRef, and folly::VirtualExecutor.
Definition at line 44 of file Executor.h.
{
     return 1;
   }
template<typename ExecutorT > static bool folly::Executor::isKeepAliveDummy (const KeepAlive< ExecutorT > & keepAlive) inline static protected
Returns true if the KeepAlive is constructed from an executor that does not support the keep alive ref-counting functionality
Definition at line 166 of file Executor.h.
References folly::Executor::KeepAlive< ExecutorT >::executorAndDummyFlag_, keepAliveAcquire(), and keepAliveRelease().
Referenced by folly::VirtualExecutor::VirtualExecutor().
{
     return reinterpret_cast<intptr_t>(keepAlive.executorAndDummyFlag_) &
         KeepAlive<ExecutorT>::kDummyFlag;
   }
bool folly::Executor::keepAliveAcquire () protected virtual
Reimplemented in folly::EventBase, folly::futures::detail::WaitExecutor, folly::futures::detail::DeferredExecutor, folly::DefaultKeepAliveExecutor, folly::VirtualEventBase, folly::SerialExecutor, folly::DefaultKeepAliveExecutor::WeakRef, folly::python::AsyncioExecutor, and folly::KeepAliveTestExecutor.
Definition at line 30 of file Executor.cpp.
Referenced by getKeepAliveToken(), and isKeepAliveDummy().
{
   return false;
 }
void folly::Executor::keepAliveRelease () protected virtual
Reimplemented in folly::EventBase, folly::futures::detail::WaitExecutor, folly::futures::detail::DeferredExecutor, folly::VirtualEventBase, folly::DefaultKeepAliveExecutor, folly::SerialExecutor, folly::DefaultKeepAliveExecutor::WeakRef, folly::python::AsyncioExecutor, and folly::KeepAliveTestExecutor.
Definition at line 34 of file Executor.cpp.
References folly::FATAL.
Referenced by isKeepAliveDummy().
{
   LOG(FATAL) << __func__ << "() should not be called for folly::Executor types "
              << "which do not override keepAliveAcquire()";
 }
template<typename ExecutorT > static KeepAlive<ExecutorT> folly::Executor::makeKeepAlive (ExecutorT * executor) inline static protected
Definition at line 179 of file Executor.h.
References folly::pushmi::executor, and value.
Referenced by folly::DefaultKeepAliveExecutor::WeakRef::create(), and folly::DefaultKeepAliveExecutor::WeakRef::lock().
{
     static_assert(
         std::is_base_of<Executor, ExecutorT>::value,
         "makeKeepAlive only works for folly::Executor implementations.");
     return KeepAlive<ExecutorT>{executor, false};
   }
template<typename ExecutorT > static KeepAlive<ExecutorT> folly::Executor::makeKeepAliveDummy (ExecutorT * executor) inline static private
Definition at line 188 of file Executor.h.
References folly::pushmi::executor, and value.
{
     static_assert(
         std::is_base_of<Executor, ExecutorT>::value,
         "makeKeepAliveDummy only works for folly::Executor implementations.");
     return KeepAlive<ExecutorT>{executor, true};
   }
Member Data Documentation
const int8_t folly::Executor::HI_PRI = SCHAR_MAX static
Definition at line 50 of file Executor.h.
Referenced by TEST().
const int8_t folly::Executor::LO_PRI = SCHAR_MIN static
Definition at line 48 of file Executor.h.
Referenced by folly::CPUThreadPoolExecutor::stopThreads(), and TEST().
const int8_t folly::Executor::MID_PRI = 0 static
Definition at line 49 of file Executor.h.
Referenced by folly::PriorityLifoSemMPMCQueue< T, kBehavior >::add(), folly::Future< folly::folly::Unit >::Future(), folly::futures::map(), folly::SemiFuture< T >::SemiFuture(), and TEST().
The documentation for this class was generated from the following files:
proxygen/folly/folly/Executor.h
proxygen/folly/folly/Executor.cpp