proxygen: testing::internal::OsStackTraceGetterInterface Class Reference
testing::internal::OsStackTraceGetterInterface Class Reference abstract
#include <gtest-internal-inl.h>
Public Member Functions
OsStackTraceGetterInterface ()
virtual ~OsStackTraceGetterInterface ()
virtual string CurrentStackTrace (int max_depth, int skip_count)=0
virtual void UponLeavingGTest ()=0
OsStackTraceGetterInterface ()
virtual ~OsStackTraceGetterInterface ()
virtual string CurrentStackTrace (int max_depth, int skip_count)=0
virtual void UponLeavingGTest ()=0
OsStackTraceGetterInterface ()
virtual ~OsStackTraceGetterInterface ()
virtual string CurrentStackTrace (int max_depth, int skip_count)=0
virtual void UponLeavingGTest ()=0
Static Public Attributes
static const char *const kElidedFramesMarker
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (OsStackTraceGetterInterface)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (OsStackTraceGetterInterface)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (OsStackTraceGetterInterface)
Detailed Description
Definition at line 418 of file gtest-internal-inl.h.
Constructor & Destructor Documentation
testing::internal::OsStackTraceGetterInterface::OsStackTraceGetterInterface () inline
Definition at line 420 of file gtest-internal-inl.h.
 {}
virtual testing::internal::OsStackTraceGetterInterface::~OsStackTraceGetterInterface () inline virtual
Definition at line 421 of file gtest-internal-inl.h.
 {}
testing::internal::OsStackTraceGetterInterface::OsStackTraceGetterInterface () inline
Definition at line 420 of file gtest-internal-inl.h.
 {}
virtual testing::internal::OsStackTraceGetterInterface::~OsStackTraceGetterInterface () inline virtual
Definition at line 421 of file gtest-internal-inl.h.
References GTEST_DISALLOW_COPY_AND_ASSIGN_.
 {}
testing::internal::OsStackTraceGetterInterface::OsStackTraceGetterInterface () inline
Definition at line 420 of file gtest-internal-inl.h.
 {}
virtual testing::internal::OsStackTraceGetterInterface::~OsStackTraceGetterInterface () inline virtual
Definition at line 421 of file gtest-internal-inl.h.
References GTEST_DISALLOW_COPY_AND_ASSIGN_.
 {}
Member Function Documentation
virtual string testing::internal::OsStackTraceGetterInterface::CurrentStackTrace (int max_depth, int skip_count) pure virtual
Implemented in testing::internal::OsStackTraceGetter, testing::internal::OsStackTraceGetter, and testing::internal::OsStackTraceGetter.
virtual string testing::internal::OsStackTraceGetterInterface::CurrentStackTrace (int max_depth, int skip_count) pure virtual
Implemented in testing::internal::OsStackTraceGetter, testing::internal::OsStackTraceGetter, and testing::internal::OsStackTraceGetter.
virtual string testing::internal::OsStackTraceGetterInterface::CurrentStackTrace (int max_depth, int skip_count) pure virtual
Implemented in testing::internal::OsStackTraceGetter, testing::internal::OsStackTraceGetter, and testing::internal::OsStackTraceGetter.
testing::internal::OsStackTraceGetterInterface::GTEST_DISALLOW_COPY_AND_ASSIGN_ (OsStackTraceGetterInterface) private
testing::internal::OsStackTraceGetterInterface::GTEST_DISALLOW_COPY_AND_ASSIGN_ (OsStackTraceGetterInterface) private
testing::internal::OsStackTraceGetterInterface::GTEST_DISALLOW_COPY_AND_ASSIGN_ (OsStackTraceGetterInterface) private
virtual void testing::internal::OsStackTraceGetterInterface::UponLeavingGTest () pure virtual
Implemented in testing::internal::OsStackTraceGetter, testing::internal::OsStackTraceGetter, and testing::internal::OsStackTraceGetter.
Referenced by testing::Test::Run(), testing::TestInfo::Run(), testing::TestCase::Run(), and testing::TestPartNonfatallyFailed().
virtual void testing::internal::OsStackTraceGetterInterface::UponLeavingGTest () pure virtual
Implemented in testing::internal::OsStackTraceGetter, testing::internal::OsStackTraceGetter, and testing::internal::OsStackTraceGetter.
virtual void testing::internal::OsStackTraceGetterInterface::UponLeavingGTest () pure virtual
Implemented in testing::internal::OsStackTraceGetter, testing::internal::OsStackTraceGetter, and testing::internal::OsStackTraceGetter.
Member Data Documentation
const char *const testing::internal::OsStackTraceGetterInterface::kElidedFramesMarker static
Initial value:
=
    "... " GTEST_NAME_ " internal frames ..."
Definition at line 438 of file gtest-internal-inl.h.
Referenced by testing::internal::PortableLocaltime(), and testing::internal::ScopedTrace::~ScopedTrace().
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest-internal-inl.h
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest.cc