proxygen: testing::TestInfoTest Class Reference
testing::TestInfoTest Class Reference
Static Protected Member Functions
static const TestInfo * GetTestInfo (const char *test_name)
static const TestResult * GetTestResult (const TestInfo *test_info)
static const TestInfo * GetTestInfo (const char *test_name)
static const TestResult * GetTestResult (const TestInfo *test_info)
static const TestInfo * GetTestInfo (const char *test_name)
static const TestResult * GetTestResult (const TestInfo *test_info)
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Protected Member Functions inherited from testing::Test
Test ()
virtual void SetUp ()
virtual void TearDown ()
Test ()
virtual void SetUp ()
virtual void TearDown ()
Test ()
virtual void SetUp ()
virtual void TearDown ()
Detailed Description
Definition at line 5298 of file gtest_unittest.cc.
Member Function Documentation
static const TestInfo* testing::TestInfoTest::GetTestInfo (const char * test_name) inline static protected
Definition at line 5300 of file gtest_unittest.cc.
References testing::TestCase::GetTestInfo(), testing::internal::GetUnitTestImpl(), i, testing::TestInfo::name(), and testing::TestCase::total_test_count().
{
     const TestCase* const test_case = GetUnitTestImpl()->
         GetTestCase("TestInfoTest", "", NULL, NULL);
     for (int i = 0; i < test_case->total_test_count(); ++i) {
       const TestInfo* const test_info = test_case->GetTestInfo(i);
       if (strcmp(test_name, test_info->name()) == 0)
         return test_info;
     }
     return NULL;
   }
static const TestInfo* testing::TestInfoTest::GetTestInfo (const char * test_name) inline static protected
Definition at line 5300 of file gtest_unittest.cc.
References testing::TestCase::GetTestInfo(), testing::internal::GetUnitTestImpl(), i, testing::TestInfo::name(), and testing::TestCase::total_test_count().
{
     const TestCase* const test_case = GetUnitTestImpl()->
         GetTestCase("TestInfoTest", "", NULL, NULL);
     for (int i = 0; i < test_case->total_test_count(); ++i) {
       const TestInfo* const test_info = test_case->GetTestInfo(i);
       if (strcmp(test_name, test_info->name()) == 0)
         return test_info;
     }
     return NULL;
   }
static const TestInfo* testing::TestInfoTest::GetTestInfo (const char * test_name) inline static protected
Definition at line 5300 of file gtest_unittest.cc.
References testing::TestCase::GetTestInfo(), testing::internal::GetUnitTestImpl(), i, testing::TestInfo::name(), and testing::TestCase::total_test_count().
{
     const TestCase* const test_case = GetUnitTestImpl()->
         GetTestCase("TestInfoTest", "", NULL, NULL);
     for (int i = 0; i < test_case->total_test_count(); ++i) {
       const TestInfo* const test_info = test_case->GetTestInfo(i);
       if (strcmp(test_name, test_info->name()) == 0)
         return test_info;
     }
     return NULL;
   }
static const TestResult* testing::TestInfoTest::GetTestResult (const TestInfo * test_info) inline static protected
Definition at line 5312 of file gtest_unittest.cc.
References ASSERT_EQ, ASSERT_STREQ, testing::TestInfo::name(), testing::TestInfo::result(), testing::TestInfo::test_case_name(), and testing::internal::TEST_F().
{
     return test_info->result();
   }
static const TestResult* testing::TestInfoTest::GetTestResult (const TestInfo * test_info) inline static protected
Definition at line 5312 of file gtest_unittest.cc.
References testing::TestInfo::result().
{
     return test_info->result();
   }
static const TestResult* testing::TestInfoTest::GetTestResult (const TestInfo * test_info) inline static protected
Definition at line 5312 of file gtest_unittest.cc.
References ASSERT_EQ, ASSERT_STREQ, testing::TestInfo::name(), testing::TestInfo::result(), testing::TestInfo::test_case_name(), and testing::internal::TEST_F().
{
     return test_info->result();
   }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest_unittest.cc