proxygen: folly::fibers::ExecutorLoopController Class Reference
folly::fibers::ExecutorLoopController Class Reference
#include <ExecutorLoopController.h>
Public Member Functions
ExecutorLoopController (folly::Executor *executor)
~ExecutorLoopController () override
Public Member Functions inherited from folly::fibers::LoopController
virtual ~LoopController ()
Private Member Functions
void setFiberManager (fibers::FiberManager *fm) override
void schedule () override
void runLoop () override
void scheduleThreadSafe () override
void timedSchedule (std::function< void()> func, TimePoint time) override
Private Attributes
folly::Executor * executor_
Executor::KeepAlive executorKeepAlive_
fibers::FiberManager * fm_ {nullptr}
Friends
class fibers::FiberManager
Additional Inherited Members
Public Types inherited from folly::fibers::LoopController
typedef std::chrono::steady_clock Clock
typedef std::chrono::time_point< Clock > TimePoint
Detailed Description
A fiber loop controller that works for arbitrary folly::Executor
Definition at line 31 of file ExecutorLoopController.h.
Constructor & Destructor Documentation
folly::fibers::ExecutorLoopController::ExecutorLoopController (folly::Executor * executor) inline explicit
Definition at line 22 of file ExecutorLoopController-inl.h.
     : executor_(executor) {}
folly::fibers::ExecutorLoopController::~ExecutorLoopController () inline override
Definition at line 25 of file ExecutorLoopController-inl.h.
 {}
Member Function Documentation
void folly::fibers::ExecutorLoopController::runLoop () inline override private virtual
Run FiberManager loopUntilNoReadyImpl(). May have additional logic specific to a LoopController.
Implements folly::fibers::LoopController.
Definition at line 39 of file ExecutorLoopController-inl.h.
References executor_, executorKeepAlive_, fm_, folly::getKeepAliveToken(), folly::fibers::FiberManager::hasTasks(), folly::fibers::FiberManager::loopUntilNoReadyImpl(), and folly::Executor::KeepAlive< ExecutorT >::reset().
Referenced by schedule(), and scheduleThreadSafe().
{
   if (!executorKeepAlive_) {
     if (!fm_->hasTasks()) {
       return;
     }
     executorKeepAlive_ = getKeepAliveToken(executor_);
   }
   fm_->loopUntilNoReadyImpl();
   if (!fm_->hasTasks()) {
     executorKeepAlive_.reset();
   }
 }
void folly::fibers::ExecutorLoopController::schedule () inline override private virtual
Called by FiberManager to schedule the loop function run at some point in the futufre.
Implements folly::fibers::LoopController.
Definition at line 31 of file ExecutorLoopController-inl.h.
References folly::Executor::add(), executor_, executorKeepAlive_, folly::getKeepAliveToken(), and runLoop().
{
   // add() is thread-safe, so this isn't properly optimized for addTask()
   if (!executorKeepAlive_) {
     executorKeepAlive_ = getKeepAliveToken(executor_);
   }
   executor_->add([this]() { return runLoop(); });
 }
void folly::fibers::ExecutorLoopController::scheduleThreadSafe () inline override private virtual
Same as schedule(), but safe to call from any thread.
Implements folly::fibers::LoopController.
Definition at line 52 of file ExecutorLoopController-inl.h.
References folly::Executor::add(), executor_, fm_, folly::getKeepAliveToken(), runLoop(), and folly::fibers::FiberManager::shouldRunLoopRemote().
{
   executor_->add(
       [this, executorKeepAlive = getKeepAliveToken(executor_)]() mutable {
         if (fm_->shouldRunLoopRemote()) {
           return runLoop();
         }
       });
 }
void folly::fibers::ExecutorLoopController::setFiberManager (fibers::FiberManager *) inline override private virtual
Called by FiberManager to associate itself with the LoopController.
Implements folly::fibers::LoopController.
Definition at line 27 of file ExecutorLoopController-inl.h.
References fm_.
{
   fm_ = fm;
 }
void folly::fibers::ExecutorLoopController::timedSchedule (std::function< void()> func, TimePoint time) inline override private virtual
Called by FiberManager to schedule some function to be run at some time.
Implements folly::fibers::LoopController.
Definition at line 61 of file ExecutorLoopController-inl.h.
                {
   throw std::logic_error("Time schedule isn't supported by asyncio executor");
 }
Friends And Related Function Documentation
friend class fibers::FiberManager friend
Definition at line 47 of file ExecutorLoopController.h.
Member Data Documentation
folly::Executor* folly::fibers::ExecutorLoopController::executor_ private
Definition at line 37 of file ExecutorLoopController.h.
Referenced by runLoop(), schedule(), and scheduleThreadSafe().
Executor::KeepAlive folly::fibers::ExecutorLoopController::executorKeepAlive_ private
Definition at line 38 of file ExecutorLoopController.h.
Referenced by runLoop(), and schedule().
fibers::FiberManager* folly::fibers::ExecutorLoopController::fm_ {nullptr} private
Definition at line 39 of file ExecutorLoopController.h.
Referenced by runLoop(), scheduleThreadSafe(), and setFiberManager().
The documentation for this class was generated from the following files:
proxygen/folly/folly/fibers/ExecutorLoopController.h
proxygen/folly/folly/fibers/ExecutorLoopController-inl.h