proxygen: testing::internal::linked_ptr< T > Class Template Reference
testing::internal::linked_ptr< T > Class Template Reference
#include <gtest-linked_ptr.h>
Public Types
typedef T element_type
typedef T element_type
typedef T element_type
Public Member Functions
linked_ptr (T *ptr=NULL)
~linked_ptr ()
template<typename U >
linked_ptr (linked_ptr< U > const &ptr)
linked_ptr (linked_ptr const &ptr)
template<typename U >
linked_ptr & operator= (linked_ptr< U > const &ptr)
linked_ptr & operator= (linked_ptr const &ptr)
void reset (T *ptr=NULL)
T * get () const
T * operator-> () const
T & operator* () const
bool operator== (T *p) const
bool operator!= (T *p) const
template<typename U >
bool operator== (linked_ptr< U > const &ptr) const
template<typename U >
bool operator!= (linked_ptr< U > const &ptr) const
linked_ptr (T *ptr=NULL)
~linked_ptr ()
template<typename U >
linked_ptr (linked_ptr< U > const &ptr)
linked_ptr (linked_ptr const &ptr)
template<typename U >
linked_ptr & operator= (linked_ptr< U > const &ptr)
linked_ptr & operator= (linked_ptr const &ptr)
void reset (T *ptr=NULL)
T * get () const
T * operator-> () const
T & operator* () const
bool operator== (T *p) const
bool operator!= (T *p) const
template<typename U >
bool operator== (linked_ptr< U > const &ptr) const
template<typename U >
bool operator!= (linked_ptr< U > const &ptr) const
linked_ptr (T *ptr=NULL)
~linked_ptr ()
template<typename U >
linked_ptr (linked_ptr< U > const &ptr)
linked_ptr (linked_ptr const &ptr)
template<typename U >
linked_ptr & operator= (linked_ptr< U > const &ptr)
linked_ptr & operator= (linked_ptr const &ptr)
void reset (T *ptr=NULL)
T * get () const
T * operator-> () const
T & operator* () const
bool operator== (T *p) const
bool operator!= (T *p) const
template<typename U >
bool operator== (linked_ptr< U > const &ptr) const
template<typename U >
bool operator!= (linked_ptr< U > const &ptr) const
Private Member Functions
void depart ()
void capture (T *ptr)
template<typename U >
void copy (linked_ptr< U > const *ptr)
void depart ()
void capture (T *ptr)
template<typename U >
void copy (linked_ptr< U > const *ptr)
void depart ()
void capture (T *ptr)
template<typename U >
void copy (linked_ptr< U > const *ptr)
Private Attributes
T * value_
linked_ptr_internal link_
Friends
template<typename U >
class linked_ptr
template<typename U>
class linked_ptr
template<typename U>
class linked_ptr
Detailed Description
template<typename T>
class testing::internal::linked_ptr< T >
Definition at line 146 of file gtest-linked_ptr.h.
Member Typedef Documentation
template<typename T> typedef T testing::internal::linked_ptr< T >::element_type
Definition at line 148 of file gtest-linked_ptr.h.
template<typename T> typedef T testing::internal::linked_ptr< T >::element_type
Definition at line 148 of file gtest-linked_ptr.h.
template<typename T> typedef T testing::internal::linked_ptr< T >::element_type
Definition at line 148 of file gtest-linked_ptr.h.
Constructor & Destructor Documentation
template<typename T> testing::internal::linked_ptr< T >::linked_ptr (T * ptr = NULL) inline explicit
Definition at line 152 of file gtest-linked_ptr.h.
 { capture(ptr); }
template<typename T> testing::internal::linked_ptr< T >::~linked_ptr () inline
Definition at line 153 of file gtest-linked_ptr.h.
 { depart(); }
template<typename T> template<typename U > testing::internal::linked_ptr< T >::linked_ptr (linked_ptr< U > const & ptr) inline
Definition at line 156 of file gtest-linked_ptr.h.
 { copy(&ptr); }
template<typename T> testing::internal::linked_ptr< T >::linked_ptr (linked_ptr< T > const & ptr) inline
Definition at line 157 of file gtest-linked_ptr.h.
                                     {  // NOLINT
     assert(&ptr != this);
     copy(&ptr);
   }
template<typename T> testing::internal::linked_ptr< T >::linked_ptr (T * ptr = NULL) inline explicit
Definition at line 152 of file gtest-linked_ptr.h.
 { capture(ptr); }
template<typename T> testing::internal::linked_ptr< T >::~linked_ptr () inline
Definition at line 153 of file gtest-linked_ptr.h.
 { depart(); }
template<typename T> template<typename U > testing::internal::linked_ptr< T >::linked_ptr (linked_ptr< U > const & ptr) inline
Definition at line 156 of file gtest-linked_ptr.h.
 { copy(&ptr); }
template<typename T> testing::internal::linked_ptr< T >::linked_ptr (linked_ptr< T > const & ptr) inline
Definition at line 157 of file gtest-linked_ptr.h.
                                     {  // NOLINT
     assert(&ptr != this);
     copy(&ptr);
   }
template<typename T> testing::internal::linked_ptr< T >::linked_ptr (T * ptr = NULL) inline explicit
Definition at line 152 of file gtest-linked_ptr.h.
 { capture(ptr); }
template<typename T> testing::internal::linked_ptr< T >::~linked_ptr () inline
Definition at line 153 of file gtest-linked_ptr.h.
 { depart(); }
template<typename T> template<typename U > testing::internal::linked_ptr< T >::linked_ptr (linked_ptr< U > const & ptr) inline
Definition at line 156 of file gtest-linked_ptr.h.
 { copy(&ptr); }
template<typename T> testing::internal::linked_ptr< T >::linked_ptr (linked_ptr< T > const & ptr) inline
Definition at line 157 of file gtest-linked_ptr.h.
                                     {  // NOLINT
     assert(&ptr != this);
     copy(&ptr);
   }
Member Function Documentation
template<typename T> void testing::internal::linked_ptr< T >::capture (T * ptr) inline private
Definition at line 208 of file gtest-linked_ptr.h.
{
     value_ = ptr;
     link_.join_new();
   }
template<typename T> void testing::internal::linked_ptr< T >::capture (T * ptr) inline private
Definition at line 208 of file gtest-linked_ptr.h.
{
     value_ = ptr;
     link_.join_new();
   }
template<typename T> void testing::internal::linked_ptr< T >::capture (T * ptr) inline private
Definition at line 208 of file gtest-linked_ptr.h.
{
     value_ = ptr;
     link_.join_new();
   }
template<typename T> template<typename U > void testing::internal::linked_ptr< T >::copy (linked_ptr< U > const * ptr) inline private
Definition at line 213 of file gtest-linked_ptr.h.
{
     value_ = ptr->get();
     if (value_)
       link_.join(&ptr->link_);
     else
       link_.join_new();
   }
template<typename T> template<typename U > void testing::internal::linked_ptr< T >::copy (linked_ptr< U > const * ptr) inline private
Definition at line 213 of file gtest-linked_ptr.h.
{
     value_ = ptr->get();
     if (value_)
       link_.join(&ptr->link_);
     else
       link_.join_new();
   }
template<typename T> template<typename U > void testing::internal::linked_ptr< T >::copy (linked_ptr< U > const * ptr) inline private
Definition at line 213 of file gtest-linked_ptr.h.
{
     value_ = ptr->get();
     if (value_)
       link_.join(&ptr->link_);
     else
       link_.join_new();
   }
template<typename T> void testing::internal::linked_ptr< T >::depart () inline private
Definition at line 204 of file gtest-linked_ptr.h.
                 {
     if (link_.depart()) delete value_;
   }
template<typename T> void testing::internal::linked_ptr< T >::depart () inline private
Definition at line 204 of file gtest-linked_ptr.h.
                 {
     if (link_.depart()) delete value_;
   }
template<typename T> void testing::internal::linked_ptr< T >::depart () inline private
Definition at line 204 of file gtest-linked_ptr.h.
                 {
     if (link_.depart()) delete value_;
   }
template<typename T> T* testing::internal::linked_ptr< T >::get () const inline
Definition at line 182 of file gtest-linked_ptr.h.
 { return value_; }
template<typename T> T* testing::internal::linked_ptr< T >::get () const inline
Definition at line 182 of file gtest-linked_ptr.h.
Referenced by testing::internal::linked_ptr< const testing::MatcherInterface< const internal::string & > >::copy(), testing::internal::linked_ptr< const testing::MatcherInterface< const internal::string & > >::operator!=(), testing::internal::operator!=(), testing::Expectation::Less::operator()(), testing::internal::linked_ptr< const testing::MatcherInterface< const internal::string & > >::operator==(), and testing::internal::operator==().
 { return value_; }
template<typename T> T* testing::internal::linked_ptr< T >::get () const inline
Definition at line 182 of file gtest-linked_ptr.h.
 { return value_; }
template<typename T> bool testing::internal::linked_ptr< T >::operator!= (T * p) const inline
Definition at line 187 of file gtest-linked_ptr.h.
 { return value_ != p; }
template<typename T> bool testing::internal::linked_ptr< T >::operator!= (T * p) const inline
Definition at line 187 of file gtest-linked_ptr.h.
 { return value_ != p; }
template<typename T> bool testing::internal::linked_ptr< T >::operator!= (T * p) const inline
Definition at line 187 of file gtest-linked_ptr.h.
 { return value_ != p; }
template<typename T> template<typename U > bool testing::internal::linked_ptr< T >::operator!= (linked_ptr< U > const & ptr) const inline
Definition at line 193 of file gtest-linked_ptr.h.
{
     return value_ != ptr.get();
   }
template<typename T> template<typename U > bool testing::internal::linked_ptr< T >::operator!= (linked_ptr< U > const & ptr) const inline
Definition at line 193 of file gtest-linked_ptr.h.
{
     return value_ != ptr.get();
   }
template<typename T> template<typename U > bool testing::internal::linked_ptr< T >::operator!= (linked_ptr< U > const & ptr) const inline
Definition at line 193 of file gtest-linked_ptr.h.
{
     return value_ != ptr.get();
   }
template<typename T> T& testing::internal::linked_ptr< T >::operator* () const inline
Definition at line 184 of file gtest-linked_ptr.h.
 { return *value_; }
template<typename T> T& testing::internal::linked_ptr< T >::operator* () const inline
Definition at line 184 of file gtest-linked_ptr.h.
 { return *value_; }
template<typename T> T& testing::internal::linked_ptr< T >::operator* () const inline
Definition at line 184 of file gtest-linked_ptr.h.
 { return *value_; }
template<typename T> T* testing::internal::linked_ptr< T >::operator-> () const inline
Definition at line 183 of file gtest-linked_ptr.h.
 { return value_; }
template<typename T> T* testing::internal::linked_ptr< T >::operator-> () const inline
Definition at line 183 of file gtest-linked_ptr.h.
 { return value_; }
template<typename T> T* testing::internal::linked_ptr< T >::operator-> () const inline
Definition at line 183 of file gtest-linked_ptr.h.
 { return value_; }
template<typename T> template<typename U > linked_ptr& testing::internal::linked_ptr< T >::operator= (linked_ptr< U > const & ptr) inline
Definition at line 163 of file gtest-linked_ptr.h.
{
     depart();
     copy(&ptr);
     return *this;
   }
template<typename T> template<typename U > linked_ptr& testing::internal::linked_ptr< T >::operator= (linked_ptr< U > const & ptr) inline
Definition at line 163 of file gtest-linked_ptr.h.
{
     depart();
     copy(&ptr);
     return *this;
   }
template<typename T> template<typename U > linked_ptr& testing::internal::linked_ptr< T >::operator= (linked_ptr< U > const & ptr) inline
Definition at line 163 of file gtest-linked_ptr.h.
{
     depart();
     copy(&ptr);
     return *this;
   }
template<typename T> linked_ptr& testing::internal::linked_ptr< T >::operator= (linked_ptr< T > const & ptr) inline
Definition at line 169 of file gtest-linked_ptr.h.
{
     if (&ptr != this) {
       depart();
       copy(&ptr);
     }
     return *this;
   }
template<typename T> linked_ptr& testing::internal::linked_ptr< T >::operator= (linked_ptr< T > const & ptr) inline
Definition at line 169 of file gtest-linked_ptr.h.
{
     if (&ptr != this) {
       depart();
       copy(&ptr);
     }
     return *this;
   }
template<typename T> linked_ptr& testing::internal::linked_ptr< T >::operator= (linked_ptr< T > const & ptr) inline
Definition at line 169 of file gtest-linked_ptr.h.
{
     if (&ptr != this) {
       depart();
       copy(&ptr);
     }
     return *this;
   }
template<typename T> bool testing::internal::linked_ptr< T >::operator== (T * p) const inline
Definition at line 186 of file gtest-linked_ptr.h.
 { return value_ == p; }
template<typename T> bool testing::internal::linked_ptr< T >::operator== (T * p) const inline
Definition at line 186 of file gtest-linked_ptr.h.
 { return value_ == p; }
template<typename T> bool testing::internal::linked_ptr< T >::operator== (T * p) const inline
Definition at line 186 of file gtest-linked_ptr.h.
 { return value_ == p; }
template<typename T> template<typename U > bool testing::internal::linked_ptr< T >::operator== (linked_ptr< U > const & ptr) const inline
Definition at line 189 of file gtest-linked_ptr.h.
{
     return value_ == ptr.get();
   }
template<typename T> template<typename U > bool testing::internal::linked_ptr< T >::operator== (linked_ptr< U > const & ptr) const inline
Definition at line 189 of file gtest-linked_ptr.h.
{
     return value_ == ptr.get();
   }
template<typename T> template<typename U > bool testing::internal::linked_ptr< T >::operator== (linked_ptr< U > const & ptr) const inline
Definition at line 189 of file gtest-linked_ptr.h.
{
     return value_ == ptr.get();
   }
template<typename T> void testing::internal::linked_ptr< T >::reset (T * ptr = NULL) inline
Definition at line 178 of file gtest-linked_ptr.h.
{
     depart();
     capture(ptr);
   }
template<typename T> void testing::internal::linked_ptr< T >::reset (T * ptr = NULL) inline
Definition at line 178 of file gtest-linked_ptr.h.
{
     depart();
     capture(ptr);
   }
template<typename T> void testing::internal::linked_ptr< T >::reset (T * ptr = NULL) inline
Definition at line 178 of file gtest-linked_ptr.h.
{
     depart();
     capture(ptr);
   }
Friends And Related Function Documentation
template<typename T> template<typename U > friend class linked_ptr friend
Definition at line 199 of file gtest-linked_ptr.h.
template<typename T> template<typename U> class linked_ptr () friend
Definition at line 199 of file gtest-linked_ptr.h.
template<typename T> template<typename U> class linked_ptr () friend
Definition at line 199 of file gtest-linked_ptr.h.
Member Data Documentation
template<typename T> linked_ptr_internal testing::internal::linked_ptr< T >::link_ private
Definition at line 202 of file gtest-linked_ptr.h.
Referenced by testing::internal::linked_ptr< const testing::MatcherInterface< const internal::string & > >::copy().
template<typename T> T * testing::internal::linked_ptr< T >::value_ private
Definition at line 201 of file gtest-linked_ptr.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/internal/gtest-linked_ptr.h