proxygen: MockPersistenceLayer Class Reference
MockPersistenceLayer Class Reference
Public Member Functions
~MockPersistenceLayer () override
bool persist (const dynamic &obj) noexceptoverride
Optional< dynamic > load () noexceptoverride
CacheDataVersion getLastPersistedVersionConcrete () const
void setPersistedVersionConcrete (CacheDataVersion version)
MOCK_METHOD0 (clear, void())
MOCK_METHOD1 (persist_, bool(const dynamic &))
MOCK_METHOD0 (load_, Optional< dynamic >())
MOCK_CONST_METHOD0 (getLastPersistedVersion, CacheDataVersion())
GMOCK_METHOD1_ (, noexcept,, setPersistedVersion, void(CacheDataVersion))
Public Member Functions inherited from wangle::CachePersistence< K, V >
CachePersistence ()
virtual ~CachePersistence ()=default
bool persistVersionedData (const folly::dynamic &kvPairs, const CacheDataVersion &version)
virtual CacheDataVersion getLastPersistedVersion () const
virtual void setPersistedVersion (CacheDataVersion version) noexcept
virtual void clear ()=0
Detailed Description
Definition at line 67 of file LRUPersistentCacheTest.cpp.
Constructor & Destructor Documentation
MockPersistenceLayer::~MockPersistenceLayer () inline override
Definition at line 69 of file LRUPersistentCacheTest.cpp.
{
       LOG(ERROR) << "ok.";
     }
Member Function Documentation
CacheDataVersion MockPersistenceLayer::getLastPersistedVersionConcrete () const inline
Definition at line 78 of file LRUPersistentCacheTest.cpp.
References wangle::CachePersistence< K, V >::getLastPersistedVersion().
Referenced by LRUPersistentCacheTest< MutexT >::SetUp(), and TYPED_TEST().
{
       return TestPersistenceLayer::getLastPersistedVersion();
     }
MockPersistenceLayer::GMOCK_METHOD1_ (noexcept , setPersistedVersion , void(CacheDataVersion))
Optional<dynamic> MockPersistenceLayer::load () inline override virtual noexcept
Returns a list of key value pairs that are present in this persistence store.
Implements wangle::CachePersistence< K, V >.
Definition at line 75 of file LRUPersistentCacheTest.cpp.
{
       return load_();
     }
MockPersistenceLayer::MOCK_CONST_METHOD0 (getLastPersistedVersion , CacheDataVersion())
MockPersistenceLayer::MOCK_METHOD0 (clear , void())
MockPersistenceLayer::MOCK_METHOD0 (load_ , Optional< dynamic > ())
MockPersistenceLayer::MOCK_METHOD1 (persist_ , bool(const dynamic &))
bool MockPersistenceLayer::persist (const dynamic & kvPairs) inline override virtual noexcept
Persist a folly::dynamic array of key value pairs. Returns true on success.
Implements wangle::CachePersistence< K, V >.
Definition at line 72 of file LRUPersistentCacheTest.cpp.
{
       return persist_(obj);
     }
void MockPersistenceLayer::setPersistedVersionConcrete (CacheDataVersion version) inline
Definition at line 81 of file LRUPersistentCacheTest.cpp.
References GMOCK_METHOD1_, MOCK_CONST_METHOD0, MOCK_METHOD0, MOCK_METHOD1, folly::pushmi::__adl::noexcept(), and wangle::CachePersistence< K, V >::setPersistedVersion().
Referenced by LRUPersistentCacheTest< MutexT >::SetUp(), and TYPED_TEST().
{
       TestPersistenceLayer::setPersistedVersion(version);
     }
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/client/persistence/test/LRUPersistentCacheTest.cpp