proxygen: folly::ssl::OpenSSLHash::Hmac Class Reference
folly::ssl::OpenSSLHash::Hmac Class Reference
#include <OpenSSLHash.h>
Public Member Functions
Hmac ()
void hash_init (const EVP_MD *md, ByteRange key)
void hash_update (ByteRange data)
void hash_update (const IOBuf &data)
void hash_final (MutableByteRange out)
Private Attributes
const EVP_MD * md_ = nullptr
HmacCtxUniquePtr ctx_ {nullptr}
Detailed Description
Definition at line 101 of file OpenSSLHash.h.
Constructor & Destructor Documentation
folly::ssl::OpenSSLHash::Hmac::Hmac () inline
Definition at line 103 of file OpenSSLHash.h.
 : ctx_(HMAC_CTX_new()) {}
Member Function Documentation
void folly::ssl::OpenSSLHash::Hmac::hash_final (MutableByteRange out) inline
Definition at line 119 of file OpenSSLHash.h.
References folly::ssl::OpenSSLHash::check_libssl_result(), folly::ssl::OpenSSLHash::check_out_size(), folly::ssl::OpenSSLHash::Digest::ctx_, folly::Range< Iter >::data(), folly::ssl::OpenSSLHash::Digest::md_, and folly::size().
Referenced by folly::ssl::OpenSSLHash::hmac().
{
       const auto size = EVP_MD_size(md_);
       check_out_size(size_t(size), out);
       unsigned int len = 0;
       check_libssl_result(1, HMAC_Final(ctx_.get(), out.data(), &len));
       check_libssl_result(size, int(len));
       md_ = nullptr;
     }
void folly::ssl::OpenSSLHash::Hmac::hash_init (const EVP_MD * md, ByteRange key) inline
Definition at line 105 of file OpenSSLHash.h.
References folly::ssl::OpenSSLHash::check_libssl_result(), folly::ssl::OpenSSLHash::Digest::ctx_, folly::Range< Iter >::data(), folly::ssl::OpenSSLHash::Digest::md_, and folly::Range< Iter >::size().
Referenced by folly::ssl::OpenSSLHash::hmac().
{
       md_ = md;
       check_libssl_result(
           1,
           HMAC_Init_ex(ctx_.get(), key.data(), int(key.size()), md_, nullptr));
     }
void folly::ssl::OpenSSLHash::Hmac::hash_update (ByteRange data) inline
Definition at line 111 of file OpenSSLHash.h.
References folly::ssl::OpenSSLHash::check_libssl_result(), folly::ssl::OpenSSLHash::Digest::ctx_, folly::Range< Iter >::data(), and folly::Range< Iter >::size().
Referenced by folly::ssl::OpenSSLHash::hmac().
{
       check_libssl_result(1, HMAC_Update(ctx_.get(), data.data(), data.size()));
     }
void folly::ssl::OpenSSLHash::Hmac::hash_update (const IOBuf & data) inline
Definition at line 114 of file OpenSSLHash.h.
References folly::ssl::OpenSSLHash::Digest::hash_update().
{
       for (auto r : data) {
         hash_update(r);
       }
     }
Member Data Documentation
HmacCtxUniquePtr folly::ssl::OpenSSLHash::Hmac::ctx_ {nullptr} private
Definition at line 130 of file OpenSSLHash.h.
const EVP_MD* folly::ssl::OpenSSLHash::Hmac::md_ = nullptr private
Definition at line 129 of file OpenSSLHash.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/ssl/OpenSSLHash.h