proxygen: folly::detail::DigestBuilder< DigestT > Class Template Reference
folly::detail::DigestBuilder< DigestT > Class Template Reference
#include <DigestBuilder.h>
Classes
struct CpuLocalBuffer
Public Member Functions
DigestBuilder (size_t bufferSize, size_t digestSize)
DigestT build ()
void append (double value)
Private Attributes
std::vector< CpuLocalBuffer > cpuLocalBuffers_
size_t bufferSize_
size_t digestSize_
Detailed Description
template<typename DigestT>
class folly::detail::DigestBuilder< DigestT >
Definition at line 40 of file DigestBuilder.h.
Constructor & Destructor Documentation
template<typename DigestT > folly::detail::DigestBuilder< DigestT >::DigestBuilder (size_t bufferSize, size_t digestSize) explicit
Definition at line 31 of file DigestBuilder-defs.h.
References folly::detail::DigestBuilder< DigestT >::cpuLocalBuffers_, and folly::CacheLocality::system().
     : bufferSize_(bufferSize), digestSize_(digestSize) {
   auto& cl = CacheLocality::system();
   cpuLocalBuffers_.resize(cl.numCachesByLevel[0]);
 }
Member Function Documentation
template<typename DigestT > void folly::detail::DigestBuilder< DigestT >::append (double value)
Definition at line 74 of file DigestBuilder-defs.h.
References folly::detail::DigestBuilder< DigestT >::bufferSize_, folly::detail::DigestBuilder< DigestT >::cpuLocalBuffers_, folly::AccessSpreader< Atom >::current(), folly::detail::DigestBuilder< DigestT >::digestSize_, g(), and folly::detail::tls_lastCpuBufferSlot.
Referenced by TEST().
{
   auto& which = tls_lastCpuBufferSlot;
   auto cpuLocalBuf = &cpuLocalBuffers_[which];
   std::unique_lock<SpinLock> g(cpuLocalBuf->mutex, std::try_to_lock_t());
   if (!g.owns_lock()) {
     which = AccessSpreader<>::current(cpuLocalBuffers_.size());
     cpuLocalBuf = &cpuLocalBuffers_[which];
     g = std::unique_lock<SpinLock>(cpuLocalBuf->mutex);
   }
   cpuLocalBuf->buffer.push_back(value);
   if (cpuLocalBuf->buffer.size() == bufferSize_) {
     if (!cpuLocalBuf->digest) {
       cpuLocalBuf->digest = std::make_unique<DigestT>(digestSize_);
     }
     *cpuLocalBuf->digest = cpuLocalBuf->digest->merge(cpuLocalBuf->buffer);
     cpuLocalBuf->buffer.clear();
   }
 }
template<typename DigestT > DigestT folly::detail::DigestBuilder< DigestT >::build ()
Definition at line 38 of file DigestBuilder-defs.h.
References count, folly::detail::DigestBuilder< DigestT >::cpuLocalBuffers_, folly::detail::DigestBuilder< DigestT >::digestSize_, g(), merge(), folly::gen::move, and values().
Referenced by TEST().
{
   std::vector<std::vector<double>> valuesVec;
   std::vector<std::unique_ptr<DigestT>> digestPtrs;
   valuesVec.reserve(cpuLocalBuffers_.size());
   digestPtrs.reserve(cpuLocalBuffers_.size());
   for (auto& cpuLocalBuffer : cpuLocalBuffers_) {
     SpinLockGuard g(cpuLocalBuffer.mutex);
     valuesVec.push_back(std::move(cpuLocalBuffer.buffer));
     if (cpuLocalBuffer.digest) {
       digestPtrs.push_back(std::move(cpuLocalBuffer.digest));
     }
   }
   std::vector<DigestT> digests;
   for (auto& digestPtr : digestPtrs) {
     digests.push_back(std::move(*digestPtr));
   }
   size_t count = 0;
   for (const auto& vec : valuesVec) {
     count += vec.size();
   }
   if (count) {
     std::vector<double> values;
     values.reserve(count);
     for (const auto& vec : valuesVec) {
       values.insert(values.end(), vec.begin(), vec.end());
     }
     DigestT digest(digestSize_);
     digests.push_back(digest.merge(values));
   }
   return DigestT::merge(digests);
 }
Member Data Documentation
template<typename DigestT> size_t folly::detail::DigestBuilder< DigestT >::bufferSize_ private
Definition at line 64 of file DigestBuilder.h.
Referenced by folly::detail::DigestBuilder< DigestT >::append().
template<typename DigestT> std::vector<CpuLocalBuffer> folly::detail::DigestBuilder< DigestT >::cpuLocalBuffers_ private
Definition at line 63 of file DigestBuilder.h.
Referenced by folly::detail::DigestBuilder< DigestT >::append(), folly::detail::DigestBuilder< DigestT >::build(), and folly::detail::DigestBuilder< DigestT >::DigestBuilder().
template<typename DigestT> size_t folly::detail::DigestBuilder< DigestT >::digestSize_ private
Definition at line 65 of file DigestBuilder.h.
Referenced by folly::detail::DigestBuilder< DigestT >::append(), and folly::detail::DigestBuilder< DigestT >::build().
The documentation for this class was generated from the following files:
proxygen/folly/folly/stats/detail/DigestBuilder.h
proxygen/folly/folly/stats/detail/DigestBuilder-defs.h