proxygen: testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container > Class Template Reference
testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container > Class Template Reference
#include <gmock-matchers.h>
Public Types
typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(Container)> ContainerView
typedef std::iterator_traits< typename ContainerView::type::const_iterator >::difference_type DistanceType
typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(Container)> ContainerView
typedef std::iterator_traits< typename ContainerView::type::const_iterator >::difference_type DistanceType
typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(Container)> ContainerView
typedef std::iterator_traits< typename ContainerView::type::const_iterator >::difference_type DistanceType
Public Member Functions
Impl (const DistanceMatcher &distance_matcher)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (Container container, MatchResultListener *listener) const
Impl (const DistanceMatcher &distance_matcher)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (Container container, MatchResultListener *listener) const
Impl (const DistanceMatcher &distance_matcher)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (Container container, MatchResultListener *listener) const
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
virtual ~MatcherDescriberInterface ()
virtual ~MatcherDescriberInterface ()
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (Impl)
GTEST_DISALLOW_ASSIGN_ (Impl)
GTEST_DISALLOW_ASSIGN_ (Impl)
Private Attributes
const Matcher< DistanceType > distance_matcher_
Detailed Description
template<typename DistanceMatcher>
template<typename Container>
class testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >
Definition at line 2463 of file gmock-matchers.h.
Member Typedef Documentation
template<typename DistanceMatcher > template<typename Container > typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(Container)> testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::ContainerView
Definition at line 2466 of file gmock-matchers.h.
template<typename DistanceMatcher > template<typename Container > typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(Container)> testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::ContainerView
Definition at line 2466 of file gmock-matchers.h.
template<typename DistanceMatcher > template<typename Container > typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(Container)> testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::ContainerView
Definition at line 2466 of file gmock-matchers.h.
template<typename DistanceMatcher > template<typename Container > typedef std::iterator_traits< typename ContainerView::type::const_iterator>::difference_type testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::DistanceType
Definition at line 2469 of file gmock-matchers.h.
template<typename DistanceMatcher > template<typename Container > typedef std::iterator_traits< typename ContainerView::type::const_iterator>::difference_type testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::DistanceType
Definition at line 2469 of file gmock-matchers.h.
template<typename DistanceMatcher > template<typename Container > typedef std::iterator_traits< typename ContainerView::type::const_iterator>::difference_type testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::DistanceType
Definition at line 2469 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename DistanceMatcher > template<typename Container > testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::Impl (const DistanceMatcher & distance_matcher) inline explicit
Definition at line 2470 of file gmock-matchers.h.
         : distance_matcher_(MatcherCast<DistanceType>(distance_matcher)) {}
template<typename DistanceMatcher > template<typename Container > testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::Impl (const DistanceMatcher & distance_matcher) inline explicit
Definition at line 2470 of file gmock-matchers.h.
         : distance_matcher_(MatcherCast<DistanceType>(distance_matcher)) {}
template<typename DistanceMatcher > template<typename Container > testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::Impl (const DistanceMatcher & distance_matcher) inline explicit
Definition at line 2470 of file gmock-matchers.h.
         : distance_matcher_(MatcherCast<DistanceType>(distance_matcher)) {}
Member Function Documentation
template<typename DistanceMatcher > template<typename Container > virtual void testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 2477 of file gmock-matchers.h.
{
       *os << "distance between begin() and end() ";
       distance_matcher_.DescribeNegationTo(os);
     }
template<typename DistanceMatcher > template<typename Container > virtual void testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 2477 of file gmock-matchers.h.
{
       *os << "distance between begin() and end() ";
       distance_matcher_.DescribeNegationTo(os);
     }
template<typename DistanceMatcher > template<typename Container > virtual void testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 2477 of file gmock-matchers.h.
{
       *os << "distance between begin() and end() ";
       distance_matcher_.DescribeNegationTo(os);
     }
template<typename DistanceMatcher > template<typename Container > virtual void testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 2473 of file gmock-matchers.h.
{
       *os << "distance between begin() and end() ";
       distance_matcher_.DescribeTo(os);
     }
template<typename DistanceMatcher > template<typename Container > virtual void testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 2473 of file gmock-matchers.h.
{
       *os << "distance between begin() and end() ";
       distance_matcher_.DescribeTo(os);
     }
template<typename DistanceMatcher > template<typename Container > virtual void testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 2473 of file gmock-matchers.h.
{
       *os << "distance between begin() and end() ";
       distance_matcher_.DescribeTo(os);
     }
template<typename DistanceMatcher > template<typename Container > testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::GTEST_DISALLOW_ASSIGN_ (Impl< Container >) private
template<typename DistanceMatcher > template<typename Container > testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::GTEST_DISALLOW_ASSIGN_ (Impl< Container >) private
template<typename DistanceMatcher > template<typename Container > testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::GTEST_DISALLOW_ASSIGN_ (Impl< Container >) private
template<typename DistanceMatcher > template<typename Container > virtual bool testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::MatchAndExplain (Container container, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< Container >.
Definition at line 2482 of file gmock-matchers.h.
References folly::test::begin(), folly::test::end(), testing::internal::PrintIfNotEmpty(), and testing::MatchResultListener::stream().
{
 #if GTEST_HAS_STD_BEGIN_AND_END_
       using std::begin;
       using std::end;
       DistanceType distance = std::distance(begin(container), end(container));
 #else
       DistanceType distance = std::distance(container.begin(), container.end());
 #endif
       StringMatchResultListener distance_listener;
       const bool result =
           distance_matcher_.MatchAndExplain(distance, &distance_listener);
       *listener << "whose distance between begin() and end() " << distance
                 << (result ? " matches" : " doesn't match");
       PrintIfNotEmpty(distance_listener.str(), listener->stream());
       return result;
     }
template<typename DistanceMatcher > template<typename Container > virtual bool testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::MatchAndExplain (Container container, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< Container >.
Definition at line 2482 of file gmock-matchers.h.
References folly::test::begin(), folly::test::end(), GTEST_DISALLOW_ASSIGN_, and testing::internal::PrintIfNotEmpty().
{
 #if GTEST_HAS_STD_BEGIN_AND_END_
       using std::begin;
       using std::end;
       DistanceType distance = std::distance(begin(container), end(container));
 #else
       DistanceType distance = std::distance(container.begin(), container.end());
 #endif
       StringMatchResultListener distance_listener;
       const bool result =
           distance_matcher_.MatchAndExplain(distance, &distance_listener);
       *listener << "whose distance between begin() and end() " << distance
                 << (result ? " matches" : " doesn't match");
       PrintIfNotEmpty(distance_listener.str(), listener->stream());
       return result;
     }
template<typename DistanceMatcher > template<typename Container > virtual bool testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::MatchAndExplain (Container container, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< Container >.
Definition at line 2482 of file gmock-matchers.h.
References folly::test::begin(), folly::test::end(), GTEST_DISALLOW_ASSIGN_, and testing::internal::PrintIfNotEmpty().
{
 #if GTEST_HAS_STD_BEGIN_AND_END_
       using std::begin;
       using std::end;
       DistanceType distance = std::distance(begin(container), end(container));
 #else
       DistanceType distance = std::distance(container.begin(), container.end());
 #endif
       StringMatchResultListener distance_listener;
       const bool result =
           distance_matcher_.MatchAndExplain(distance, &distance_listener);
       *listener << "whose distance between begin() and end() " << distance
                 << (result ? " matches" : " doesn't match");
       PrintIfNotEmpty(distance_listener.str(), listener->stream());
       return result;
     }
Member Data Documentation
template<typename DistanceMatcher > template<typename Container > const Matcher< DistanceType > testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::distance_matcher_ private
Definition at line 2501 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h