proxygen: testing::internal::ElementsAreMatcher< MatcherTuple > Class Template Reference
testing::internal::ElementsAreMatcher< MatcherTuple > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
ElementsAreMatcher (const MatcherTuple &args)
template<typename Container >
operator Matcher< Container > () const
ElementsAreMatcher (const MatcherTuple &args)
template<typename Container >
operator Matcher< Container > () const
ElementsAreMatcher (const MatcherTuple &args)
template<typename Container >
operator Matcher< Container > () const
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (ElementsAreMatcher)
GTEST_DISALLOW_ASSIGN_ (ElementsAreMatcher)
GTEST_DISALLOW_ASSIGN_ (ElementsAreMatcher)
Private Attributes
const MatcherTuple matchers_
Detailed Description
template<typename MatcherTuple>
class testing::internal::ElementsAreMatcher< MatcherTuple >
Definition at line 3477 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename MatcherTuple> testing::internal::ElementsAreMatcher< MatcherTuple >::ElementsAreMatcher (const MatcherTuple & args) inline explicit
Definition at line 3479 of file gmock-matchers.h.
 : matchers_(args) {}
template<typename MatcherTuple> testing::internal::ElementsAreMatcher< MatcherTuple >::ElementsAreMatcher (const MatcherTuple & args) inline explicit
Definition at line 3479 of file gmock-matchers.h.
 : matchers_(args) {}
template<typename MatcherTuple> testing::internal::ElementsAreMatcher< MatcherTuple >::ElementsAreMatcher (const MatcherTuple & args) inline explicit
Definition at line 3479 of file gmock-matchers.h.
 : matchers_(args) {}
Member Function Documentation
template<typename MatcherTuple> testing::internal::ElementsAreMatcher< MatcherTuple >::GTEST_DISALLOW_ASSIGN_ (ElementsAreMatcher< MatcherTuple >) private
template<typename MatcherTuple> testing::internal::ElementsAreMatcher< MatcherTuple >::GTEST_DISALLOW_ASSIGN_ (ElementsAreMatcher< MatcherTuple >) private
template<typename MatcherTuple> testing::internal::ElementsAreMatcher< MatcherTuple >::GTEST_DISALLOW_ASSIGN_ (ElementsAreMatcher< MatcherTuple >) private
template<typename MatcherTuple> template<typename Container > testing::internal::ElementsAreMatcher< MatcherTuple >::operator Matcher< Container > () const inline
Definition at line 3482 of file gmock-matchers.h.
References GTEST_REMOVE_REFERENCE_AND_CONST_, testing::MakeMatcher(), testing::internal::TransformTupleValues(), and value.
{
     typedef GTEST_REMOVE_REFERENCE_AND_CONST_(Container) RawContainer;
     typedef typename internal::StlContainerView<RawContainer>::type View;
     typedef typename View::value_type Element;
     typedef ::std::vector<Matcher<const Element&> > MatcherVec;
     MatcherVec matchers;
     matchers.reserve(::testing::tuple_size<MatcherTuple>::value);
     TransformTupleValues(CastAndAppendTransform<const Element&>(), matchers_,
                          ::std::back_inserter(matchers));
     return MakeMatcher(new ElementsAreMatcherImpl<Container>(
                            matchers.begin(), matchers.end()));
   }
template<typename MatcherTuple> template<typename Container > testing::internal::ElementsAreMatcher< MatcherTuple >::operator Matcher< Container > () const inline
Definition at line 3482 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, GTEST_REMOVE_REFERENCE_AND_CONST_, testing::MakeMatcher(), testing::internal::TransformTupleValues(), and value.
{
     typedef GTEST_REMOVE_REFERENCE_AND_CONST_(Container) RawContainer;
     typedef typename internal::StlContainerView<RawContainer>::type View;
     typedef typename View::value_type Element;
     typedef ::std::vector<Matcher<const Element&> > MatcherVec;
     MatcherVec matchers;
     matchers.reserve(::testing::tuple_size<MatcherTuple>::value);
     TransformTupleValues(CastAndAppendTransform<const Element&>(), matchers_,
                          ::std::back_inserter(matchers));
     return MakeMatcher(new ElementsAreMatcherImpl<Container>(
                            matchers.begin(), matchers.end()));
   }
template<typename MatcherTuple> template<typename Container > testing::internal::ElementsAreMatcher< MatcherTuple >::operator Matcher< Container > () const inline
Definition at line 3482 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, GTEST_REMOVE_REFERENCE_AND_CONST_, testing::MakeMatcher(), testing::internal::TransformTupleValues(), and value.
{
     typedef GTEST_REMOVE_REFERENCE_AND_CONST_(Container) RawContainer;
     typedef typename internal::StlContainerView<RawContainer>::type View;
     typedef typename View::value_type Element;
     typedef ::std::vector<Matcher<const Element&> > MatcherVec;
     MatcherVec matchers;
     matchers.reserve(::testing::tuple_size<MatcherTuple>::value);
     TransformTupleValues(CastAndAppendTransform<const Element&>(), matchers_,
                          ::std::back_inserter(matchers));
     return MakeMatcher(new ElementsAreMatcherImpl<Container>(
                            matchers.begin(), matchers.end()));
   }
Member Data Documentation
template<typename MatcherTuple> const MatcherTuple testing::internal::ElementsAreMatcher< MatcherTuple >::matchers_ private
Definition at line 3496 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h