proxygen: folly::AsyncSocket::SendMsgParamsCallback Class Reference
folly::AsyncSocket::SendMsgParamsCallback Class Reference
#include <AsyncSocket.h>
Public Member Functions
virtual ~SendMsgParamsCallback ()=default
int getFlags (folly::WriteFlags flags, bool zeroCopyEnabled) noexcept
virtual void getAncillaryData (folly::WriteFlags, void *) noexcept
virtual uint32_t getAncillaryDataSize (folly::WriteFlags) noexcept
Static Public Attributes
static const size_t maxAncillaryDataSize {0x5000}
Private Member Functions
virtual int getFlagsImpl (folly::WriteFlags, int defaultFlags)
int getDefaultFlags (folly::WriteFlags flags, bool zeroCopyEnabled) noexcept
Detailed Description
Definition at line 143 of file AsyncSocket.h.
Constructor & Destructor Documentation
virtual folly::AsyncSocket::SendMsgParamsCallback::~SendMsgParamsCallback () virtual default
Member Function Documentation
virtual void folly::AsyncSocket::SendMsgParamsCallback::getAncillaryData (folly::WriteFlags , void *) inline virtual noexcept
getAncillaryData() will be invoked to initialize ancillary data buffer referred by "msg_control" field of msghdr structure passed to sendmsg() system call. The function assumes that the size of buffer is not smaller than the value returned by getAncillaryDataSize() method for the same combination of flags.
Parameters
flags Write flags requested for the given write operation
data Pointer to ancillary data buffer to initialize.
Reimplemented in TestSendMsgParamsCallback, folly::SendMsgDataCallback, and folly::SendMsgParamsCallbackBase.
Definition at line 170 of file AsyncSocket.h.
Referenced by folly::SendMsgParamsCallbackBase::getAncillaryData(), folly::SendMsgDataCallback::getAncillaryData(), and folly::AsyncSocket::performWrite().
                           {}
virtual uint32_t folly::AsyncSocket::SendMsgParamsCallback::getAncillaryDataSize (folly::WriteFlags) inline virtual noexcept
getAncillaryDataSize() will be invoked to retrieve the size of ancillary data buffer which should be passed to sendmsg() system call
Parameters
flags Write flags requested for the given write operation
Reimplemented in TestSendMsgParamsCallback, folly::SendMsgDataCallback, and folly::SendMsgParamsCallbackBase.
Definition at line 180 of file AsyncSocket.h.
Referenced by folly::SendMsgParamsCallbackBase::getAncillaryDataSize(), folly::SendMsgDataCallback::getAncillaryDataSize(), and folly::AsyncSocket::performWrite().
{
       return 0;
     }
int folly::AsyncSocket::SendMsgParamsCallback::getDefaultFlags (folly::WriteFlags flags, bool zeroCopyEnabled) private noexcept
getDefaultFlags() will be invoked by getFlags(folly::WriteFlags flags) to retrieve the default set of flags, and pass them to getFlagsImpl(...)
Parameters
flags Write flags requested for the given write operation
Definition at line 225 of file AsyncSocket.cpp.
References folly::CORK, folly::EOR, folly::isSet(), MSG_ZEROCOPY, folly::netops::setsockopt(), and folly::WRITE_MSG_ZEROCOPY.
{
   int msg_flags = MSG_DONTWAIT;
 #ifdef MSG_NOSIGNAL // Linux-only
   msg_flags |= MSG_NOSIGNAL;
 #ifdef MSG_MORE
   if (isSet(flags, WriteFlags::CORK)) {
     // MSG_MORE tells the kernel we have more data to send, so wait for us to
     // give it the rest of the data rather than immediately sending a partial
     // frame, even when TCP_NODELAY is enabled.
     msg_flags |= MSG_MORE;
   }
 #endif // MSG_MORE
 #endif // MSG_NOSIGNAL
   if (isSet(flags, WriteFlags::EOR)) {
     // marks that this is the last byte of a record (response)
     msg_flags |= MSG_EOR;
   }
   if (zeroCopyEnabled && isSet(flags, WriteFlags::WRITE_MSG_ZEROCOPY)) {
     msg_flags |= MSG_ZEROCOPY;
   }
   return msg_flags;
 }
int folly::AsyncSocket::SendMsgParamsCallback::getFlags (folly::WriteFlags flags, bool zeroCopyEnabled) inline noexcept
getFlags() will be invoked to retrieve the desired flags to be passed to sendmsg() system call. This method was intentionally declared non-virtual, so there is no way to override it. Instead feel free to override getFlagsImpl(flags, defaultFlags) method instead, and enjoy the convenience of defaultFlags passed there.
Parameters
flags Write flags requested for the given write operation
Definition at line 156 of file AsyncSocket.h.
Referenced by folly::SendMsgParamsCallbackBase::getFlagsImpl(), folly::SendMsgFlagsCallback::getFlagsImpl(), and folly::AsyncSocket::performWrite().
{
       return getFlagsImpl(flags, getDefaultFlags(flags, zeroCopyEnabled));
     }
virtual int folly::AsyncSocket::SendMsgParamsCallback::getFlagsImpl (folly::WriteFlags , int defaultFlags) inline private virtual
getFlagsImpl() will be invoked by getFlags(folly::WriteFlags flags) method to retrieve the flags to be passed to sendmsg() system call. SendMsgParamsCallback::getFlags() is calling this method, and returns its results directly to the caller in AsyncSocket. Classes inheriting from SendMsgParamsCallback are welcome to override this method to force SendMsgParamsCallback to return its own set of flags.
Parameters
flags Write flags requested for the given write operation
defaultflags A set of message flags returned by getDefaultFlags() method for the given "flags" mask.
Reimplemented in TestSendMsgParamsCallback, folly::SendMsgFlagsCallback, and folly::SendMsgParamsCallbackBase.
Definition at line 201 of file AsyncSocket.h.
References folly::AsyncSocket::AsyncSocket(), folly::pushmi::__adl::noexcept(), folly::AsyncSocket::setShutdownSocketSet(), string, uint16_t, and uint32_t.
{
       return defaultFlags;
     }
Member Data Documentation
const size_t folly::AsyncSocket::SendMsgParamsCallback::maxAncillaryDataSize {0x5000} static
Definition at line 185 of file AsyncSocket.h.
Referenced by folly::AsyncSSLSocket::bioWrite(), and folly::AsyncSocket::performWrite().
The documentation for this class was generated from the following files:
proxygen/folly/folly/io/async/AsyncSocket.h
proxygen/folly/folly/io/async/AsyncSocket.cpp