proxygen: testing::TestResult Class Reference
testing::TestResult Class Reference
#include <gtest.h>
Public Member Functions
TestResult ()
~TestResult ()
int total_part_count () const
int test_property_count () const
bool Passed () const
bool Failed () const
bool HasFatalFailure () const
bool HasNonfatalFailure () const
TimeInMillis elapsed_time () const
const TestPartResult & GetTestPartResult (int i) const
const TestProperty & GetTestProperty (int i) const
TestResult ()
~TestResult ()
int total_part_count () const
int test_property_count () const
bool Passed () const
bool Failed () const
bool HasFatalFailure () const
bool HasNonfatalFailure () const
TimeInMillis elapsed_time () const
const TestPartResult & GetTestPartResult (int i) const
const TestProperty & GetTestProperty (int i) const
TestResult ()
~TestResult ()
int total_part_count () const
int test_property_count () const
bool Passed () const
bool Failed () const
bool HasFatalFailure () const
bool HasNonfatalFailure () const
TimeInMillis elapsed_time () const
const TestPartResult & GetTestPartResult (int i) const
const TestProperty & GetTestProperty (int i) const
Private Member Functions
const std::vector< TestPartResult > & test_part_results () const
const std::vector< TestProperty > & test_properties () const
void set_elapsed_time (TimeInMillis elapsed)
void RecordProperty (const std::string &xml_element, const TestProperty &test_property)
void AddTestPartResult (const TestPartResult &test_part_result)
int death_test_count () const
int increment_death_test_count ()
void ClearTestPartResults ()
void Clear ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestResult)
const std::vector< TestPartResult > & test_part_results () const
const std::vector< TestProperty > & test_properties () const
void set_elapsed_time (TimeInMillis elapsed)
void RecordProperty (const std::string &xml_element, const TestProperty &test_property)
void AddTestPartResult (const TestPartResult &test_part_result)
int death_test_count () const
int increment_death_test_count ()
void ClearTestPartResults ()
void Clear ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestResult)
const std::vector< TestPartResult > & test_part_results () const
const std::vector< TestProperty > & test_properties () const
void set_elapsed_time (TimeInMillis elapsed)
void RecordProperty (const std::string &xml_element, const TestProperty &test_property)
void AddTestPartResult (const TestPartResult &test_part_result)
int death_test_count () const
int increment_death_test_count ()
void ClearTestPartResults ()
void Clear ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestResult)
Static Private Member Functions
static bool ValidateTestProperty (const std::string &xml_element, const TestProperty &test_property)
static bool ValidateTestProperty (const std::string &xml_element, const TestProperty &test_property)
static bool ValidateTestProperty (const std::string &xml_element, const TestProperty &test_property)
Private Attributes
internal::Mutex test_properites_mutex_
std::vector< TestPartResult > test_part_results_
std::vector< TestProperty > test_properties_
int death_test_count_
TimeInMillis elapsed_time_
Friends
class TestInfo
class TestCase
class UnitTest
class internal::DefaultGlobalTestPartResultReporter
class internal::ExecDeathTest
class internal::TestResultAccessor
class internal::UnitTestImpl
class internal::WindowsDeathTest
Detailed Description
Definition at line 523 of file gtest.h.
Constructor & Destructor Documentation
testing::TestResult::TestResult ()
Definition at line 2017 of file gtest.cc.
     : death_test_count_(0),
       elapsed_time_(0) {
 }
testing::TestResult::~TestResult ()
Definition at line 2023 of file gtest.cc.
{
 }
testing::TestResult::TestResult ()
testing::TestResult::~TestResult ()
testing::TestResult::TestResult ()
testing::TestResult::~TestResult ()
Member Function Documentation
void testing::TestResult::AddTestPartResult (const TestPartResult & test_part_result) private
Definition at line 2050 of file gtest.cc.
References test_part_results_.
Referenced by testing::internal::DefaultGlobalTestPartResultReporter::ReportTestPartResult().
{
   test_part_results_.push_back(test_part_result);
 }
void testing::TestResult::AddTestPartResult (const TestPartResult & test_part_result) private
void testing::TestResult::AddTestPartResult (const TestPartResult & test_part_result) private
void testing::TestResult::Clear () private
Definition at line 2162 of file gtest.cc.
References death_test_count_, elapsed_time_, test_part_results_, and test_properties_.
Referenced by testing::TestCase::ClearResult(), testing::TestInfo::ClearTestResult(), and testing::FormatWordList().
{
   test_part_results_.clear();
   test_properties_.clear();
   death_test_count_ = 0;
   elapsed_time_ = 0;
 }
void testing::TestResult::Clear () private
void testing::TestResult::Clear () private
void testing::TestResult::ClearTestPartResults () private
Definition at line 2045 of file gtest.cc.
References test_part_results_.
Referenced by testing::internal::TestResultAccessor::ClearTestPartResults().
{
   test_part_results_.clear();
 }
void testing::TestResult::ClearTestPartResults () private
void testing::TestResult::ClearTestPartResults () private
int testing::TestResult::death_test_count () const inline private
Definition at line 605 of file gtest.h.
 { return death_test_count_; }
int testing::TestResult::death_test_count () const inline private
Definition at line 605 of file gtest.h.
 { return death_test_count_; }
int testing::TestResult::death_test_count () const inline private
Definition at line 605 of file gtest.h.
 { return death_test_count_; }
TimeInMillis testing::TestResult::elapsed_time () const inline
Definition at line 551 of file gtest.h.
References i.
 { return elapsed_time_; }
TimeInMillis testing::TestResult::elapsed_time () const inline
Definition at line 551 of file gtest.h.
References i.
Referenced by testing::internal::PrettyUnitTestResultPrinter::OnTestEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), and testing::internal::PortableLocaltime().
 { return elapsed_time_; }
TimeInMillis testing::TestResult::elapsed_time () const inline
Definition at line 551 of file gtest.h.
References i.
 { return elapsed_time_; }
bool testing::TestResult::Failed () const
bool testing::TestResult::Failed () const
bool testing::TestResult::Failed () const
Definition at line 2170 of file gtest.cc.
References testing::TestPartResult::failed(), GetTestPartResult(), i, and total_part_count().
Referenced by testing::FormatWordList(), testing::internal::PrettyUnitTestResultPrinter::OnTestEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), and testing::TestCase::TestFailed().
{
   for (int i = 0; i < total_part_count(); ++i) {
     if (GetTestPartResult(i).failed())
       return true;
   }
   return false;
 }
const TestPartResult & testing::TestResult::GetTestPartResult (int i) const
Definition at line 2029 of file gtest.cc.
References testing::internal::posix::Abort(), test_part_results_, and total_part_count().
Referenced by Failed(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), and testing::internal::PortableLocaltime().
{
   if (i < 0 || i >= total_part_count())
     internal::posix::Abort();
   return test_part_results_.at(i);
 }
const TestPartResult& testing::TestResult::GetTestPartResult (int i) const
const TestPartResult& testing::TestResult::GetTestPartResult (int i) const
const TestProperty& testing::TestResult::GetTestProperty (int i) const
const TestProperty & testing::TestResult::GetTestProperty (int i) const
Definition at line 2038 of file gtest.cc.
References testing::internal::posix::Abort(), test_properties_, and test_property_count().
Referenced by testing::internal::PortableLocaltime(), testing::internal::FinalSuccessChecker::TearDown(), and testing::internal::XmlUnitTestResultPrinter::TestPropertiesAsXmlAttributes().
{
   if (i < 0 || i >= test_property_count())
     internal::posix::Abort();
   return test_properties_.at(i);
 }
const TestProperty& testing::TestResult::GetTestProperty (int i) const
testing::TestResult::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestResult) private
testing::TestResult::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestResult) private
testing::TestResult::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestResult) private
bool testing::TestResult::HasFatalFailure () const
Definition at line 2184 of file gtest.cc.
References testing::internal::CountIf(), test_part_results_, and testing::TestPartFatallyFailed().
Referenced by testing::Test::HasFatalFailure(), testing::TestPartFatallyFailed(), and testing::TestPartNonfatallyFailed().
{
   return CountIf(test_part_results_, TestPartFatallyFailed) > 0;
 }
bool testing::TestResult::HasFatalFailure () const
bool testing::TestResult::HasFatalFailure () const
bool testing::TestResult::HasNonfatalFailure () const
bool testing::TestResult::HasNonfatalFailure () const
bool testing::TestResult::HasNonfatalFailure () const
Definition at line 2194 of file gtest.cc.
References testing::internal::CountIf(), test_part_results_, and testing::TestPartNonfatallyFailed().
Referenced by testing::TestPartNonfatallyFailed().
{
   return CountIf(test_part_results_, TestPartNonfatallyFailed) > 0;
 }
int testing::TestResult::increment_death_test_count () inline private
Definition at line 608 of file gtest.h.
 { return ++death_test_count_; }
int testing::TestResult::increment_death_test_count () inline private
Definition at line 608 of file gtest.h.
References GTEST_API_, and GTEST_DISALLOW_COPY_AND_ASSIGN_.
 { return ++death_test_count_; }
int testing::TestResult::increment_death_test_count () inline private
Definition at line 608 of file gtest.h.
References GTEST_API_, and GTEST_DISALLOW_COPY_AND_ASSIGN_.
 { return ++death_test_count_; }
bool testing::TestResult::Passed () const inline
Definition at line 539 of file gtest.h.
Referenced by testing::internal::PrettyUnitTestResultPrinter::OnTestEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), testing::internal::PrettyUnitTestResultPrinter::PrintFailedTests(), and testing::TestCase::TestPassed().
 { return !Failed(); }
bool testing::TestResult::Passed () const inline
Definition at line 539 of file gtest.h.
 { return !Failed(); }
bool testing::TestResult::Passed () const inline
Definition at line 539 of file gtest.h.
 { return !Failed(); }
void testing::TestResult::RecordProperty (const std::string & xml_element, const TestProperty & test_property) private
void testing::TestResult::RecordProperty (const std::string & xml_element, const TestProperty & test_property) private
Definition at line 2057 of file gtest.cc.
References testing::TestProperty::key(), folly::detail::lock(), test_properites_mutex_, test_properties_, ValidateTestProperty(), and testing::TestProperty::value().
Referenced by testing::internal::UnitTestImpl::RecordProperty(), testing::internal::TestResultAccessor::RecordProperty(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   if (!ValidateTestProperty(xml_element, test_property)) {
     return;
   }
   internal::MutexLock lock(&test_properites_mutex_);
   const std::vector<TestProperty>::iterator property_with_matching_key =
       std::find_if(test_properties_.begin(), test_properties_.end(),
                    internal::TestPropertyKeyIs(test_property.key()));
   if (property_with_matching_key == test_properties_.end()) {
     test_properties_.push_back(test_property);
     return;
   }
   property_with_matching_key->SetValue(test_property.value());
 }
void testing::TestResult::RecordProperty (const std::string & xml_element, const TestProperty & test_property) private
void testing::TestResult::set_elapsed_time (TimeInMillis elapsed) inline private
Definition at line 584 of file gtest.h.
References string.
 { elapsed_time_ = elapsed; }
void testing::TestResult::set_elapsed_time (TimeInMillis elapsed) inline private
Definition at line 584 of file gtest.h.
References string.
 { elapsed_time_ = elapsed; }
void testing::TestResult::set_elapsed_time (TimeInMillis elapsed) inline private
Definition at line 584 of file gtest.h.
References string.
Referenced by testing::TestInfo::Run().
 { elapsed_time_ = elapsed; }
const std::vector<TestPartResult>& testing::TestResult::test_part_results () const inline private
Definition at line 574 of file gtest.h.
Referenced by testing::internal::TestResultAccessor::test_part_results().
{
     return test_part_results_;
   }
const std::vector<TestPartResult>& testing::TestResult::test_part_results () const inline private
Definition at line 574 of file gtest.h.
{
     return test_part_results_;
   }
const std::vector<TestPartResult>& testing::TestResult::test_part_results () const inline private
Definition at line 574 of file gtest.h.
{
     return test_part_results_;
   }
const std::vector<TestProperty>& testing::TestResult::test_properties () const inline private
Definition at line 579 of file gtest.h.
{
     return test_properties_;
   }
const std::vector<TestProperty>& testing::TestResult::test_properties () const inline private
Definition at line 579 of file gtest.h.
{
     return test_properties_;
   }
const std::vector<TestProperty>& testing::TestResult::test_properties () const inline private
Definition at line 579 of file gtest.h.
{
     return test_properties_;
   }
int testing::TestResult::test_property_count () const
int testing::TestResult::test_property_count () const
int testing::TestResult::test_property_count () const
Definition at line 2205 of file gtest.cc.
References test_properties_.
Referenced by GetTestProperty(), testing::internal::PortableLocaltime(), testing::TestPartNonfatallyFailed(), and testing::internal::XmlUnitTestResultPrinter::TestPropertiesAsXmlAttributes().
{
   return static_cast<int>(test_properties_.size());
 }
int testing::TestResult::total_part_count () const
int testing::TestResult::total_part_count () const
int testing::TestResult::total_part_count () const
Definition at line 2200 of file gtest.cc.
References test_part_results_.
Referenced by Failed(), GetTestPartResult(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PortableLocaltime(), and testing::TestPartNonfatallyFailed().
{
   return static_cast<int>(test_part_results_.size());
 }
static bool testing::TestResult::ValidateTestProperty (const std::string & xml_element, const TestProperty & test_property) static private
bool testing::TestResult::ValidateTestProperty (const std::string & xml_element, const TestProperty & test_property) static private
Definition at line 2155 of file gtest.cc.
References testing::GetReservedAttributesForElement(), testing::TestProperty::key(), and testing::ValidateTestPropertyName().
Referenced by testing::FormatWordList(), and RecordProperty().
{
   return ValidateTestPropertyName(test_property.key(),
                                   GetReservedAttributesForElement(xml_element));
 }
static bool testing::TestResult::ValidateTestProperty (const std::string & xml_element, const TestProperty & test_property) static private
Friends And Related Function Documentation
internal::DefaultGlobalTestPartResultReporter friend
Definition at line 567 of file gtest.h.
internal::ExecDeathTest friend
Definition at line 568 of file gtest.h.
internal::TestResultAccessor friend
Definition at line 569 of file gtest.h.
internal::UnitTestImpl friend
Definition at line 570 of file gtest.h.
internal::WindowsDeathTest friend
Definition at line 571 of file gtest.h.
TestCase friend
Definition at line 565 of file gtest.h.
TestInfo friend
Definition at line 564 of file gtest.h.
UnitTest friend
Definition at line 566 of file gtest.h.
Member Data Documentation
int testing::TestResult::death_test_count_ private
Definition at line 625 of file gtest.h.
Referenced by Clear().
TimeInMillis testing::TestResult::elapsed_time_ private
Definition at line 627 of file gtest.h.
Referenced by Clear().
std::vector< TestPartResult > testing::TestResult::test_part_results_ private
Definition at line 621 of file gtest.h.
Referenced by AddTestPartResult(), Clear(), ClearTestPartResults(), GetTestPartResult(), HasFatalFailure(), HasNonfatalFailure(), and total_part_count().
internal::Mutex testing::TestResult::test_properites_mutex_ private
Definition at line 618 of file gtest.h.
Referenced by RecordProperty().
std::vector< TestProperty > testing::TestResult::test_properties_ private
Definition at line 623 of file gtest.h.
Referenced by Clear(), GetTestProperty(), RecordProperty(), and test_property_count().
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/gtest.h
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest.cc