proxygen: wangle::ConnectionManager::DrainHelper Class Reference
wangle::ConnectionManager::DrainHelper Class Reference
Public Member Functions
DrainHelper (ConnectionManager &manager)
ShutdownState getShutdownState ()
void setShutdownState (ShutdownState state)
void startDrainPartial (double pct, std::chrono::milliseconds idleGrace)
void startDrainAll (std::chrono::milliseconds idleGrace)
void runLoopCallback () noexceptoverride
void timeoutExpired () noexceptoverride
void drainConnections ()
void idleGracefulTimeoutExpired ()
void startDrain (std::chrono::milliseconds idleGrace)
ConnectionIterator drainStartIterator () const
Public Member Functions inherited from folly::EventBase::LoopCallback
virtual ~LoopCallback ()=default
void cancelLoopCallback ()
bool isLoopCallbackScheduled () const
Public Member Functions inherited from folly::AsyncTimeout
AsyncTimeout (TimeoutManager *timeoutManager)
AsyncTimeout (EventBase *eventBase)
AsyncTimeout (TimeoutManager *timeoutManager, InternalEnum internal)
AsyncTimeout (EventBase *eventBase, InternalEnum internal)
AsyncTimeout ()
virtual ~AsyncTimeout ()
bool scheduleTimeout (uint32_t milliseconds)
bool scheduleTimeout (TimeoutManager::timeout_type timeout)
void cancelTimeout ()
bool isScheduled () const
void attachTimeoutManager (TimeoutManager *timeoutManager, InternalEnum internal=InternalEnum::NORMAL)
void attachEventBase (EventBase *eventBase, InternalEnum internal=InternalEnum::NORMAL)
void detachTimeoutManager ()
void detachEventBase ()
const TimeoutManager * getTimeoutManager ()
struct event * getEvent ()
Private Attributes
bool all_ {true}
double pct_ {1.0}
ConnectionManager & manager_
ShutdownState shutdownState_ {ShutdownState::NONE}
Additional Inherited Members
Public Types inherited from folly::AsyncTimeout
typedef TimeoutManager::InternalEnum InternalEnum
Static Public Member Functions inherited from folly::AsyncTimeout
template<typename TCallback >
static std::unique_ptr< AsyncTimeout > make (TimeoutManager &manager, TCallback &&callback)
template<typename TCallback >
static std::unique_ptr< AsyncTimeout > schedule (TimeoutManager::timeout_type timeout, TimeoutManager &manager, TCallback &&callback)
Detailed Description
Definition at line 186 of file ConnectionManager.h.
Constructor & Destructor Documentation
wangle::ConnectionManager::DrainHelper::DrainHelper (ConnectionManager & manager) inline explicit
Definition at line 190 of file ConnectionManager.h.
         : folly::AsyncTimeout(manager.eventBase_),
           manager_(manager) {}
Member Function Documentation
void wangle::ConnectionManager::DrainHelper::drainConnections ()
Definition at line 184 of file ConnectionManager.cpp.
References wangle::ManagedConnection::fireCloseWhenIdle(), wangle::ManagedConnection::fireNotifyPendingShutdown(), g(), and wangle::ManagedConnection::isBusy().
{
   DestructorGuard g(&manager_);
   size_t numCleared = 0;
   size_t numKept = 0;
   auto it = manager_.drainIterator_;
   CHECK(shutdownState_ == ShutdownState::NOTIFY_PENDING_SHUTDOWN ||
         shutdownState_ == ShutdownState::CLOSE_WHEN_IDLE);
   while (it != manager_.conns_.end() && (numKept + numCleared) < 64) {
     ManagedConnection& conn = *it++;
     if (shutdownState_ == ShutdownState::NOTIFY_PENDING_SHUTDOWN) {
       conn.fireNotifyPendingShutdown();
       numKept++;
     } else { // CLOSE_WHEN_IDLE
       // Second time around: close idle sessions. If they aren't idle yet,
       // have them close when they are idle
       if (conn.isBusy()) {
         numKept++;
       } else {
         numCleared++;
       }
       conn.fireCloseWhenIdle(!manager_.notifyPendingShutdown_);
     }
   }
   if (shutdownState_ == ShutdownState::CLOSE_WHEN_IDLE) {
     VLOG(2) << "Idle connections cleared: " << numCleared <<
       ", busy conns kept: " << numKept;
   } else {
     VLOG(3) << this << " notified n=" << numKept;
   }
   manager_.drainIterator_ = it;
   if (it != manager_.conns_.end()) {
     manager_.eventBase_->runInLoop(this);
   } else {
     if (shutdownState_ == ShutdownState::NOTIFY_PENDING_SHUTDOWN) {
       VLOG(3) << this << " finished notify_pending_shutdown";
       shutdownState_ = ShutdownState::NOTIFY_PENDING_SHUTDOWN_COMPLETE;
       if (!isScheduled()) {
         // The idle grace timer already fired, start over immediately
         shutdownState_ = ShutdownState::CLOSE_WHEN_IDLE;
         manager_.drainIterator_ = drainStartIterator();
         manager_.eventBase_->runInLoop(this);
       }
     } else {
       shutdownState_ = ShutdownState::CLOSE_WHEN_IDLE_COMPLETE;
     }
   }
 }
ConnectionIterator wangle::ConnectionManager::DrainHelper::drainStartIterator () const inline
Definition at line 225 of file ConnectionManager.h.
{
       if (all_) {
         return manager_.conns_.begin();
       }
       auto it = manager_.conns_.begin();
       const auto conns_size = manager_.conns_.size();
       const auto numToDrain =
         std::max<size_t>(0, std::min<size_t>(conns_size, conns_size * pct_));
       std::advance(it, conns_size - numToDrain);
       return it;
     }
ShutdownState wangle::ConnectionManager::DrainHelper::getShutdownState () inline
Definition at line 194 of file ConnectionManager.h.
References wangle::ConnectionManager::NONE.
{
       // only cares about full shutdown state
       if (!all_) {
         return ShutdownState::NONE;
       }
       return shutdownState_;
     }
void wangle::ConnectionManager::DrainHelper::idleGracefulTimeoutExpired ()
Definition at line 236 of file ConnectionManager.cpp.
{
   VLOG(2) << this << " idleGracefulTimeoutExpired";
   if (shutdownState_ ==
       ShutdownState::NOTIFY_PENDING_SHUTDOWN_COMPLETE) {
     shutdownState_ = ShutdownState::CLOSE_WHEN_IDLE;
     manager_.drainIterator_ = drainStartIterator();
     drainConnections();
   } else {
     VLOG(4) << this << " idleGracefulTimeoutExpired during "
       "NOTIFY_PENDING_SHUTDOWN, ignoring";
   }
 }
void wangle::ConnectionManager::DrainHelper::runLoopCallback () inline override virtual noexcept
Implements folly::EventBase::LoopCallback.
Definition at line 209 of file ConnectionManager.h.
References wangle::ConnectionManager::drainConnections().
{
       VLOG(3) << "Draining more conns from loop callback";
       drainConnections();
     }
void wangle::ConnectionManager::DrainHelper::setShutdownState (ShutdownState state) inline
Definition at line 202 of file ConnectionManager.h.
{
       shutdownState_ = state;
     }
void wangle::ConnectionManager::DrainHelper::startDrain (std::chrono::milliseconds idleGrace)
Definition at line 168 of file ConnectionManager.cpp.
{
   if (idleGrace.count() > 0) {
     shutdownState_ = ShutdownState::NOTIFY_PENDING_SHUTDOWN;
     scheduleTimeout(idleGrace);
     VLOG(3) << "Scheduling idle grace period of " << idleGrace.count() << "ms";
   } else {
     manager_.notifyPendingShutdown_ = false;
     shutdownState_ = ShutdownState::CLOSE_WHEN_IDLE;
     VLOG(3) << "proceeding directly to closing idle connections";
   }
   manager_.drainIterator_ = drainStartIterator();
   drainConnections();
 }
void wangle::ConnectionManager::DrainHelper::startDrainAll (std::chrono::milliseconds idleGrace)
Definition at line 157 of file ConnectionManager.cpp.
{
   all_ = true;
   pct_ = 1.0;
   if (isScheduled()) {
     // if we are in the middle of a partial, abort and convert to all
     cancelTimeout();
   }
   startDrain(idleGrace);
 }
void wangle::ConnectionManager::DrainHelper::startDrainPartial (double pct, std::chrono::milliseconds idleGrace)
Definition at line 150 of file ConnectionManager.cpp.
{
   all_ = false;
   pct_ = pct;
   startDrain(idleGrace);
 }
void wangle::ConnectionManager::DrainHelper::timeoutExpired () inline override virtual noexcept
timeoutExpired() is invoked when the timeout period has expired.
Implements folly::AsyncTimeout.
Definition at line 214 of file ConnectionManager.h.
References wangle::ConnectionManager::drainConnections(), and wangle::ConnectionManager::idleGracefulTimeoutExpired().
{
       VLOG(3) << "Idle grace expired";
       idleGracefulTimeoutExpired();
     }
Member Data Documentation
bool wangle::ConnectionManager::DrainHelper::all_ {true} private
Definition at line 238 of file ConnectionManager.h.
ConnectionManager& wangle::ConnectionManager::DrainHelper::manager_ private
Definition at line 240 of file ConnectionManager.h.
double wangle::ConnectionManager::DrainHelper::pct_ {1.0} private
Definition at line 239 of file ConnectionManager.h.
ShutdownState wangle::ConnectionManager::DrainHelper::shutdownState_ {ShutdownState::NONE} private
Definition at line 241 of file ConnectionManager.h.
The documentation for this class was generated from the following files:
proxygen/wangle/wangle/acceptor/ConnectionManager.h
proxygen/wangle/wangle/acceptor/ConnectionManager.cpp