proxygen: fizz::KeyDerivationImpl< Hash > Class Template Reference
fizz::KeyDerivationImpl< Hash > Class Template Reference
#include <KeyDerivation.h>
Public Member Functions
~KeyDerivationImpl () override=default
KeyDerivationImpl (const std::string &labelPrefix)
size_t hashLength () const override
void hash (const folly::IOBuf &in, folly::MutableByteRange out) override
void hmac (folly::ByteRange key, const folly::IOBuf &in, folly::MutableByteRange out) override
folly::ByteRange blankHash () const override
Buf expandLabel (folly::ByteRange secret, folly::StringPiece label, Buf hashValue, uint16_t length) override
std::vector< uint8_t > deriveSecret (folly::ByteRange secret, folly::StringPiece label, folly::ByteRange messageHash) override
virtual Buf hkdfExpand (folly::ByteRange secret, Buf info, uint16_t length) override
std::vector< uint8_t > hkdfExtract (folly::ByteRange salt, folly::ByteRange ikm) override
Public Member Functions inherited from fizz::KeyDerivation
virtual ~KeyDerivation ()=default
Private Attributes
std::string labelPrefix_
Detailed Description
template<typename Hash>
class fizz::KeyDerivationImpl< Hash >
Definition at line 60 of file KeyDerivation.h.
Constructor & Destructor Documentation
template<typename Hash> fizz::KeyDerivationImpl< Hash >::~KeyDerivationImpl () override default
template<typename Hash > fizz::KeyDerivationImpl< Hash >::KeyDerivationImpl (const std::string & labelPrefix)
Definition at line 12 of file KeyDerivation-inl.h.
     : labelPrefix_(labelPrefix) {}
Member Function Documentation
template<typename Hash> folly::ByteRange fizz::KeyDerivationImpl< Hash >::blankHash () const inline override virtual
Returns the hash of a blank input (ie Hash("")).
Implements fizz::KeyDerivation.
Definition at line 81 of file KeyDerivation.h.
References fizz::KeyDerivation::deriveSecret(), fizz::KeyDerivation::expandLabel(), fizz::KeyDerivation::hkdfExpand(), deadlock::info(), fizz::test::label, secret, and uint16_t.
{
     return Hash::BlankHash;
   }
template<typename Hash > std::vector< uint8_t > fizz::KeyDerivationImpl< Hash >::deriveSecret (folly::ByteRange secret, folly::StringPiece label, folly::ByteRange messageHash) override virtual
Implements fizz::KeyDerivation.
Definition at line 36 of file KeyDerivation-inl.h.
References folly::IOBuf::copyBuffer(), fizz::KeyDerivationImpl< Hash >::expandLabel(), min, folly::gen::move, and folly::Range< Iter >::size().
{
   CHECK_EQ(secret.size(), Hash::HashLen);
   CHECK_EQ(messageHash.size(), Hash::HashLen);
   // Copying the buffer to avoid violating constness of the data.
   auto hashBuf = folly::IOBuf::copyBuffer(messageHash);
   auto out = expandLabel(secret, label, std::move(hashBuf), Hash::HashLen);
   std::vector<uint8_t> prk(Hash::HashLen);
   size_t offset = 0;
   for (auto buf : *out) {
     size_t remaining = Hash::HashLen - offset;
     size_t length = std::min(buf.size(), remaining);
     memcpy(prk.data() + offset, buf.data(), length);
     offset += length;
   }
   return prk;
 }
template<typename Hash > Buf fizz::KeyDerivationImpl< Hash >::expandLabel (folly::ByteRange secret, folly::StringPiece label, Buf hashValue, uint16_t length) override virtual
Implements fizz::KeyDerivation.
Definition at line 16 of file KeyDerivation-inl.h.
References folly::Range< Iter >::begin(), fizz::encodeHkdfLabel(), folly::Range< Iter >::end(), fizz::KeyDerivationImpl< Hash >::labelPrefix_, folly::gen::move, and string.
Referenced by fizz::KeyDerivationImpl< Hash >::deriveSecret().
                      {
   HkdfLabel hkdfLabel = {
       length, std::string(label.begin(), label.end()), std::move(hashValue)};
   return HkdfImpl<Hash>().expand(
       secret, *encodeHkdfLabel(std::move(hkdfLabel), labelPrefix_), length);
 }
template<typename Hash> void fizz::KeyDerivationImpl< Hash >::hash (const folly::IOBuf & in, folly::MutableByteRange out) inline override virtual
Implements fizz::KeyDerivation.
Definition at line 70 of file KeyDerivation.h.
{
     Hash::hash(in, out);
   }
template<typename Hash> size_t fizz::KeyDerivationImpl< Hash >::hashLength () const inline override virtual
Implements fizz::KeyDerivation.
Definition at line 66 of file KeyDerivation.h.
{
     return Hash::HashLen;
   }
template<typename Hash > Buf fizz::KeyDerivationImpl< Hash >::hkdfExpand (folly::ByteRange secret, Buf info, uint16_t length) override virtual
Performs HDKF expansion.
Implements fizz::KeyDerivation.
Definition at line 28 of file KeyDerivation-inl.h.
                      {
   return HkdfImpl<Hash>().expand(secret, *info, length);
 }
template<typename Hash> std::vector<uint8_t> fizz::KeyDerivationImpl< Hash >::hkdfExtract (folly::ByteRange salt, folly::ByteRange ikm) inline override virtual
Implements fizz::KeyDerivation.
Definition at line 99 of file KeyDerivation.h.
                {
     return HkdfImpl<Hash>().extract(salt, ikm);
   }
template<typename Hash> void fizz::KeyDerivationImpl< Hash >::hmac (folly::ByteRange key, const folly::IOBuf & in, folly::MutableByteRange out) inline override virtual
Implements fizz::KeyDerivation.
Definition at line 74 of file KeyDerivation.h.
{
     Hash::hmac(key, in, out);
   }
Member Data Documentation
template<typename Hash> std::string fizz::KeyDerivationImpl< Hash >::labelPrefix_ private
Definition at line 105 of file KeyDerivation.h.
Referenced by fizz::KeyDerivationImpl< Hash >::expandLabel().
The documentation for this class was generated from the following files:
proxygen/fizz/fizz/crypto/KeyDerivation.h
proxygen/fizz/fizz/crypto/KeyDerivation-inl.h