proxygen: folly::ShutdownSocketSet Class Reference
folly::ShutdownSocketSet Class Reference
#include <ShutdownSocketSet.h>
Classes
struct Free
Public Member Functions
ShutdownSocketSet (int maxFd=1<< 18)
void add (int fd)
void remove (int fd)
int close (int fd)
void shutdown (int fd, bool abortive=false)
void shutdownAll (bool abortive=false)
Private Types
enum State : uint8_t {
FREE = 0, IN_USE, IN_SHUTDOWN, SHUT_DOWN,
MUST_CLOSE
}
Private Member Functions
void doShutdown (int fd, bool abortive)
Private Attributes
const int maxFd_
std::unique_ptr< std::atomic< uint8_t >[], Free > data_
folly::File nullFile_
Detailed Description
Set of sockets that allows immediate, take-no-prisoners abort.
Definition at line 32 of file ShutdownSocketSet.h.
Member Enumeration Documentation
enum folly::ShutdownSocketSet::State : uint8_t private
Enumerator
FREE
IN_USE
IN_SHUTDOWN
SHUT_DOWN
MUST_CLOSE
Definition at line 124 of file ShutdownSocketSet.h.
              : uint8_t {
     FREE = 0,
     IN_USE,
     IN_SHUTDOWN,
     SHUT_DOWN,
     MUST_CLOSE,
   };
Constructor & Destructor Documentation
folly::ShutdownSocketSet::ShutdownSocketSet (int maxFd = 1 << 18) explicit
Create a socket set that can handle file descriptors < maxFd. The default value (256Ki) is high enough for just about all applications, even if you increased the number of file descriptors on your system.
Definition at line 29 of file ShutdownSocketSet.cpp.
     : maxFd_(maxFd),
       data_(static_cast<std::atomic<uint8_t>*>(
           folly::checkedCalloc(size_t(maxFd), sizeof(std::atomic<uint8_t>)))),
       nullFile_("/dev/null", O_RDWR) {}
Member Function Documentation
void folly::ShutdownSocketSet::add (int fd)
Add an already open socket to the list of sockets managed by ShutdownSocketSet. You MUST close the socket by calling ShutdownSocketSet::close (which will, as a side effect, also handle EINTR properly) and not by calling close() on the file descriptor.
Definition at line 35 of file ShutdownSocketSet.cpp.
References data_, FREE, IN_USE, maxFd_, and uint8_t.
Referenced by folly::AsyncSocket::connect(), folly::test::Server::Server(), and folly::AsyncServerSocket::setupSocket().
{
   // Silently ignore any fds >= maxFd_, very unlikely
   DCHECK_GE(fd, 0);
   if (fd >= maxFd_) {
     return;
   }
   auto& sref = data_[size_t(fd)];
   uint8_t prevState = FREE;
   CHECK(sref.compare_exchange_strong(
       prevState, IN_USE, std::memory_order_relaxed))
       << "Invalid prev state for fd " << fd << ": " << int(prevState);
 }
int folly::ShutdownSocketSet::close (int fd)
Close a socket managed by ShutdownSocketSet. Returns the same return code as close() (and sets errno accordingly).
Definition at line 73 of file ShutdownSocketSet.cpp.
References folly::closeNoInt(), data_, folly::FATAL, FREE, IN_SHUTDOWN, IN_USE, maxFd_, MUST_CLOSE, SHUT_DOWN, and uint8_t.
Referenced by folly::AsyncServerSocket::bind(), folly::test::Server::closeClients(), folly::AsyncSocket::doClose(), folly::test::Server::Server(), and folly::AsyncServerSocket::stopAccepting().
{
   DCHECK_GE(fd, 0);
   if (fd >= maxFd_) {
     return folly::closeNoInt(fd);
   }
   auto& sref = data_[size_t(fd)];
   uint8_t prevState = sref.load(std::memory_order_relaxed);
   uint8_t newState = 0;
   do {
     switch (prevState) {
       case IN_USE:
       case SHUT_DOWN:
         newState = FREE;
         break;
       case IN_SHUTDOWN:
         newState = MUST_CLOSE;
         break;
       default:
         LOG(FATAL) << "Invalid prev state for fd " << fd << ": "
                    << int(prevState);
     }
   } while (!sref.compare_exchange_weak(
       prevState, newState, std::memory_order_relaxed));
   return newState == FREE ? folly::closeNoInt(fd) : 0;
 }
void folly::ShutdownSocketSet::doShutdown (int fd, bool abortive) private
Definition at line 143 of file ShutdownSocketSet.cpp.
References folly::dup2NoInt(), folly::File::fd(), nullFile_, folly::netops::setsockopt(), and folly::shutdownNoInt().
Referenced by shutdown().
{
   // shutdown() the socket first, to awaken any threads blocked on the fd
   // (subsequent IO will fail because it's been shutdown); close()ing the
   // socket does not wake up blockers, see
   // http://stackoverflow.com/a/3624545/1736339
   folly::shutdownNoInt(fd, SHUT_RDWR);
   // If abortive shutdown is desired, we'll set the SO_LINGER option on
   // the socket with a timeout of 0; this will cause RST to be sent on
   // close.
   if (abortive) {
     struct linger l = {1, 0};
     if (setsockopt(fd, SOL_SOCKET, SO_LINGER, &l, sizeof(l)) != 0) {
       // Probably not a socket, ignore.
       return;
     }
   }
   // We can't close() the socket, as that would be dangerous; a new file
   // could be opened and get the same file descriptor, and then code assuming
   // the old fd would do IO in the wrong place. We'll (atomically) dup2
   // /dev/null onto the fd instead.
   folly::dup2NoInt(nullFile_.fd(), fd);
 }
void folly::ShutdownSocketSet::remove (int fd)
Remove a socket from the list of sockets managed by ShutdownSocketSet. Note that remove() might block! (which we lamely implement by sleep()-ing) in the extremely rare case that the fd is currently being shutdown().
Definition at line 49 of file ShutdownSocketSet.cpp.
References data_, folly::FATAL, FREE, IN_SHUTDOWN, maxFd_, and uint8_t.
Referenced by folly::AsyncSocket::setShutdownSocketSet(), and folly::AsyncServerSocket::setShutdownSocketSet().
{
   DCHECK_GE(fd, 0);
   if (fd >= maxFd_) {
     return;
   }
   auto& sref = data_[size_t(fd)];
   uint8_t prevState = 0;
   prevState = sref.load(std::memory_order_relaxed);
   do {
     switch (prevState) {
       case IN_SHUTDOWN:
         std::this_thread::sleep_for(std::chrono::milliseconds(1));
         prevState = sref.load(std::memory_order_relaxed);
         continue;
       case FREE:
         LOG(FATAL) << "Invalid prev state for fd " << fd << ": "
                    << int(prevState);
     }
   } while (
       !sref.compare_exchange_weak(prevState, FREE, std::memory_order_relaxed));
 }
void folly::ShutdownSocketSet::shutdown (int fd, bool abortive = false)
Shut down a socket. If abortive is true, we perform an abortive shutdown (send RST rather than FIN). Note that we might still end up sending FIN due to the rather interesting implementation.
This is async-signal-safe and ignores errors. Obviously, subsequent read() and write() operations to the socket will fail. During normal operation, just call shutdown() on the socket.
Definition at line 102 of file ShutdownSocketSet.cpp.
References folly::closeNoInt(), data_, doShutdown(), FREE, IN_SHUTDOWN, IN_USE, maxFd_, MUST_CLOSE, SHUT_DOWN, and uint8_t.
Referenced by shutdownAll().
{
   DCHECK_GE(fd, 0);
   if (fd >= maxFd_) {
     doShutdown(fd, abortive);
     return;
   }
   auto& sref = data_[size_t(fd)];
   uint8_t prevState = IN_USE;
   if (!sref.compare_exchange_strong(
           prevState, IN_SHUTDOWN, std::memory_order_relaxed)) {
     return;
   }
   doShutdown(fd, abortive);
   prevState = IN_SHUTDOWN;
   if (sref.compare_exchange_strong(
           prevState, SHUT_DOWN, std::memory_order_relaxed)) {
     return;
   }
   CHECK_EQ(prevState, MUST_CLOSE)
       << "Invalid prev state for fd " << fd << ": " << int(prevState);
   folly::closeNoInt(fd); // ignore errors, nothing to do
   CHECK(
       sref.compare_exchange_strong(prevState, FREE, std::memory_order_relaxed))
       << "Invalid prev state for fd " << fd << ": " << int(prevState);
 }
void folly::ShutdownSocketSet::shutdownAll (bool abortive = false)
Immediate shutdown of all connections. This is a hard-hitting hammer; all reads and writes will return errors and no new connections will be accepted.
To be used only in dire situations. We're using it from the failure signal handler to close all connections quickly, even though the server might take multiple seconds to finish crashing.
The optional bool parameter indicates whether to set the active connections in to not linger. The effect of that includes RST packets being immediately sent to clients which will result in errors (and not normal EOF) on the client side. This also causes the local (ip, tcp port number) tuple to be reusable immediately, instead of having to wait the standard amount of time. For full details see the shutdown method of ShutdownSocketSet (incl. notes about the abortive parameter).
This is async-signal-safe and ignores errors.
Definition at line 134 of file ShutdownSocketSet.cpp.
References data_, i, IN_USE, maxFd_, and shutdown().
Referenced by folly::test::runKillTest().
{
   for (int i = 0; i < maxFd_; ++i) {
     auto& sref = data_[size_t(i)];
     if (sref.load(std::memory_order_relaxed) == IN_USE) {
       shutdown(i, abortive);
     }
   }
 }
Member Data Documentation
std::unique_ptr<std::atomic<uint8_t>[], Free> folly::ShutdownSocketSet::data_ private
Definition at line 140 of file ShutdownSocketSet.h.
Referenced by add(), close(), remove(), shutdown(), and shutdownAll().
const int folly::ShutdownSocketSet::maxFd_ private
Definition at line 139 of file ShutdownSocketSet.h.
Referenced by add(), close(), remove(), shutdown(), and shutdownAll().
folly::File folly::ShutdownSocketSet::nullFile_ private
Definition at line 141 of file ShutdownSocketSet.h.
Referenced by doShutdown().
The documentation for this class was generated from the following files:
proxygen/folly/folly/io/ShutdownSocketSet.h
proxygen/folly/folly/io/ShutdownSocketSet.cpp