proxygen: testing::internal::NativeArray< Element > Class Template Reference
testing::internal::NativeArray< Element > Class Template Reference
#include <gtest-internal.h>
Public Types
typedef Element value_type
typedef Element * iterator
typedef const Element * const_iterator
typedef Element value_type
typedef Element * iterator
typedef const Element * const_iterator
typedef Element value_type
typedef Element * iterator
typedef const Element * const_iterator
Public Member Functions
NativeArray (const Element *array, size_t count, RelationToSourceReference)
NativeArray (const Element *array, size_t count, RelationToSourceCopy)
NativeArray (const NativeArray &rhs)
~NativeArray ()
size_t size () const
const_iterator begin () const
const_iterator end () const
bool operator== (const NativeArray &rhs) const
NativeArray (const Element *array, size_t count, RelationToSourceReference)
NativeArray (const Element *array, size_t count, RelationToSourceCopy)
NativeArray (const NativeArray &rhs)
~NativeArray ()
size_t size () const
const_iterator begin () const
const_iterator end () const
bool operator== (const NativeArray &rhs) const
NativeArray (const Element *array, size_t count, RelationToSourceReference)
NativeArray (const Element *array, size_t count, RelationToSourceCopy)
NativeArray (const NativeArray &rhs)
~NativeArray ()
size_t size () const
const_iterator begin () const
const_iterator end () const
bool operator== (const NativeArray &rhs) const
Private Types
enum { kCheckTypeIsNotConstOrAReference }
enum { kCheckTypeIsNotConstOrAReference }
enum { kCheckTypeIsNotConstOrAReference }
Private Member Functions
void InitCopy (const Element *array, size_t a_size)
void InitRef (const Element *array, size_t a_size)
GTEST_DISALLOW_ASSIGN_ (NativeArray)
void InitCopy (const Element *array, size_t a_size)
void InitRef (const Element *array, size_t a_size)
GTEST_DISALLOW_ASSIGN_ (NativeArray)
void InitCopy (const Element *array, size_t a_size)
void InitRef (const Element *array, size_t a_size)
GTEST_DISALLOW_ASSIGN_ (NativeArray)
Private Attributes
const Element * array_
size_t size_
void(NativeArray::* clone_)(const Element *, size_t)
Detailed Description
template<typename Element>
class testing::internal::NativeArray< Element >
Definition at line 1034 of file gtest-internal.h.
Member Typedef Documentation
template<typename Element> typedef const Element* testing::internal::NativeArray< Element >::const_iterator
Definition at line 1039 of file gtest-internal.h.
template<typename Element> typedef const Element* testing::internal::NativeArray< Element >::const_iterator
Definition at line 1039 of file gtest-internal.h.
template<typename Element> typedef const Element* testing::internal::NativeArray< Element >::const_iterator
Definition at line 1039 of file gtest-internal.h.
template<typename Element> typedef Element* testing::internal::NativeArray< Element >::iterator
Definition at line 1038 of file gtest-internal.h.
template<typename Element> typedef Element* testing::internal::NativeArray< Element >::iterator
Definition at line 1038 of file gtest-internal.h.
template<typename Element> typedef Element* testing::internal::NativeArray< Element >::iterator
Definition at line 1038 of file gtest-internal.h.
template<typename Element> typedef Element testing::internal::NativeArray< Element >::value_type
Definition at line 1037 of file gtest-internal.h.
template<typename Element> typedef Element testing::internal::NativeArray< Element >::value_type
Definition at line 1037 of file gtest-internal.h.
template<typename Element> typedef Element testing::internal::NativeArray< Element >::value_type
Definition at line 1037 of file gtest-internal.h.
Member Enumeration Documentation
template<typename Element> anonymous enum private
Enumerator
kCheckTypeIsNotConstOrAReference
Definition at line 1071 of file gtest-internal.h.
        {
     kCheckTypeIsNotConstOrAReference = StaticAssertTypeEqHelper<
         Element, GTEST_REMOVE_REFERENCE_AND_CONST_(Element)>::value,
   };
template<typename Element> anonymous enum private
Enumerator
kCheckTypeIsNotConstOrAReference
Definition at line 1071 of file gtest-internal.h.
        {
     kCheckTypeIsNotConstOrAReference = StaticAssertTypeEqHelper<
         Element, GTEST_REMOVE_REFERENCE_AND_CONST_(Element)>::value,
   };
template<typename Element> anonymous enum private
Enumerator
kCheckTypeIsNotConstOrAReference
Definition at line 1071 of file gtest-internal.h.
        {
     kCheckTypeIsNotConstOrAReference = StaticAssertTypeEqHelper<
         Element, GTEST_REMOVE_REFERENCE_AND_CONST_(Element)>::value,
   };
Constructor & Destructor Documentation
template<typename Element> testing::internal::NativeArray< Element >::NativeArray (const Element * array, size_t count, RelationToSourceReference) inline
Definition at line 1042 of file gtest-internal.h.
{
     InitRef(array, count);
   }
template<typename Element> testing::internal::NativeArray< Element >::NativeArray (const Element * array, size_t count, RelationToSourceCopy) inline
Definition at line 1047 of file gtest-internal.h.
{
     InitCopy(array, count);
   }
template<typename Element> testing::internal::NativeArray< Element >::NativeArray (const NativeArray< Element > & rhs) inline
Definition at line 1052 of file gtest-internal.h.
References testing::internal::NativeArray< Element >::array_, testing::internal::NativeArray< Element >::clone_, and testing::internal::NativeArray< Element >::size_.
{
     (this->*rhs.clone_)(rhs.array_, rhs.size_);
   }
template<typename Element> testing::internal::NativeArray< Element >::~NativeArray () inline
Definition at line 1056 of file gtest-internal.h.
                  {
     if (clone_ != &NativeArray::InitRef)
       delete[] array_;
   }
template<typename Element> testing::internal::NativeArray< Element >::NativeArray (const Element * array, size_t count, RelationToSourceReference) inline
Definition at line 1042 of file gtest-internal.h.
{
     InitRef(array, count);
   }
template<typename Element> testing::internal::NativeArray< Element >::NativeArray (const Element * array, size_t count, RelationToSourceCopy) inline
Definition at line 1047 of file gtest-internal.h.
{
     InitCopy(array, count);
   }
template<typename Element> testing::internal::NativeArray< Element >::NativeArray (const NativeArray< Element > & rhs) inline
Definition at line 1052 of file gtest-internal.h.
References testing::internal::NativeArray< Element >::array_, testing::internal::NativeArray< Element >::clone_, and testing::internal::NativeArray< Element >::size_.
{
     (this->*rhs.clone_)(rhs.array_, rhs.size_);
   }
template<typename Element> testing::internal::NativeArray< Element >::~NativeArray () inline
Definition at line 1056 of file gtest-internal.h.
                  {
     if (clone_ != &NativeArray::InitRef)
       delete[] array_;
   }
template<typename Element> testing::internal::NativeArray< Element >::NativeArray (const Element * array, size_t count, RelationToSourceReference) inline
Definition at line 1042 of file gtest-internal.h.
{
     InitRef(array, count);
   }
template<typename Element> testing::internal::NativeArray< Element >::NativeArray (const Element * array, size_t count, RelationToSourceCopy) inline
Definition at line 1047 of file gtest-internal.h.
{
     InitCopy(array, count);
   }
template<typename Element> testing::internal::NativeArray< Element >::NativeArray (const NativeArray< Element > & rhs) inline
Definition at line 1052 of file gtest-internal.h.
References testing::internal::NativeArray< Element >::array_, testing::internal::NativeArray< Element >::clone_, and testing::internal::NativeArray< Element >::size_.
{
     (this->*rhs.clone_)(rhs.array_, rhs.size_);
   }
template<typename Element> testing::internal::NativeArray< Element >::~NativeArray () inline
Definition at line 1056 of file gtest-internal.h.
                  {
     if (clone_ != &NativeArray::InitRef)
       delete[] array_;
   }
Member Function Documentation
template<typename Element> const_iterator testing::internal::NativeArray< Element >::begin () const inline
Definition at line 1063 of file gtest-internal.h.
Referenced by testing::internal::NativeArray< Element >::operator==(), and TEST().
 { return array_; }
template<typename Element> const_iterator testing::internal::NativeArray< Element >::begin () const inline
Definition at line 1063 of file gtest-internal.h.
 { return array_; }
template<typename Element> const_iterator testing::internal::NativeArray< Element >::begin () const inline
Definition at line 1063 of file gtest-internal.h.
 { return array_; }
template<typename Element> const_iterator testing::internal::NativeArray< Element >::end () const inline
Definition at line 1064 of file gtest-internal.h.
 { return array_ + size_; }
template<typename Element> const_iterator testing::internal::NativeArray< Element >::end () const inline
Definition at line 1064 of file gtest-internal.h.
 { return array_ + size_; }
template<typename Element> const_iterator testing::internal::NativeArray< Element >::end () const inline
Definition at line 1064 of file gtest-internal.h.
Referenced by TEST().
 { return array_ + size_; }
template<typename Element> testing::internal::NativeArray< Element >::GTEST_DISALLOW_ASSIGN_ (NativeArray< Element >) private
template<typename Element> testing::internal::NativeArray< Element >::GTEST_DISALLOW_ASSIGN_ (NativeArray< Element >) private
template<typename Element> testing::internal::NativeArray< Element >::GTEST_DISALLOW_ASSIGN_ (NativeArray< Element >) private
template<typename Element> void testing::internal::NativeArray< Element >::InitCopy (const Element * array, size_t a_size) inline private
Definition at line 1077 of file gtest-internal.h.
References folly::copy(), and testing::internal::CopyArray().
{
     Element* const copy = new Element[a_size];
     CopyArray(array, a_size, copy);
     array_ = copy;
     size_ = a_size;
     clone_ = &NativeArray::InitCopy;
   }
template<typename Element> void testing::internal::NativeArray< Element >::InitCopy (const Element * array, size_t a_size) inline private
Definition at line 1077 of file gtest-internal.h.
References folly::copy(), and testing::internal::CopyArray().
{
     Element* const copy = new Element[a_size];
     CopyArray(array, a_size, copy);
     array_ = copy;
     size_ = a_size;
     clone_ = &NativeArray::InitCopy;
   }
template<typename Element> void testing::internal::NativeArray< Element >::InitCopy (const Element * array, size_t a_size) inline private
Definition at line 1077 of file gtest-internal.h.
References folly::copy(), and testing::internal::CopyArray().
{
     Element* const copy = new Element[a_size];
     CopyArray(array, a_size, copy);
     array_ = copy;
     size_ = a_size;
     clone_ = &NativeArray::InitCopy;
   }
template<typename Element> void testing::internal::NativeArray< Element >::InitRef (const Element * array, size_t a_size) inline private
Definition at line 1086 of file gtest-internal.h.
References GTEST_DISALLOW_ASSIGN_.
{
     array_ = array;
     size_ = a_size;
     clone_ = &NativeArray::InitRef;
   }
template<typename Element> void testing::internal::NativeArray< Element >::InitRef (const Element * array, size_t a_size) inline private
Definition at line 1086 of file gtest-internal.h.
References GTEST_DISALLOW_ASSIGN_.
{
     array_ = array;
     size_ = a_size;
     clone_ = &NativeArray::InitRef;
   }
template<typename Element> void testing::internal::NativeArray< Element >::InitRef (const Element * array, size_t a_size) inline private
Definition at line 1086 of file gtest-internal.h.
{
     array_ = array;
     size_ = a_size;
     clone_ = &NativeArray::InitRef;
   }
template<typename Element> bool testing::internal::NativeArray< Element >::operator== (const NativeArray< Element > & rhs) const inline
Definition at line 1065 of file gtest-internal.h.
References testing::internal::ArrayEq(), folly::test::begin(), testing::internal::NativeArray< Element >::begin(), folly::size(), and testing::internal::NativeArray< Element >::size().
{
     return size() == rhs.size() &&
         ArrayEq(begin(), size(), rhs.begin());
   }
template<typename Element> bool testing::internal::NativeArray< Element >::operator== (const NativeArray< Element > & rhs) const inline
Definition at line 1065 of file gtest-internal.h.
References testing::internal::ArrayEq(), folly::test::begin(), testing::internal::NativeArray< Element >::begin(), GTEST_REMOVE_REFERENCE_AND_CONST_, folly::size(), testing::internal::NativeArray< Element >::size(), and value.
{
     return size() == rhs.size() &&
         ArrayEq(begin(), size(), rhs.begin());
   }
template<typename Element> bool testing::internal::NativeArray< Element >::operator== (const NativeArray< Element > & rhs) const inline
Definition at line 1065 of file gtest-internal.h.
References testing::internal::ArrayEq(), folly::test::begin(), testing::internal::NativeArray< Element >::begin(), GTEST_REMOVE_REFERENCE_AND_CONST_, folly::size(), testing::internal::NativeArray< Element >::size(), and value.
{
     return size() == rhs.size() &&
         ArrayEq(begin(), size(), rhs.begin());
   }
template<typename Element> size_t testing::internal::NativeArray< Element >::size () const inline
Definition at line 1062 of file gtest-internal.h.
Referenced by testing::internal::NativeArray< Element >::operator==(), and TEST().
 { return size_; }
template<typename Element> size_t testing::internal::NativeArray< Element >::size () const inline
Definition at line 1062 of file gtest-internal.h.
 { return size_; }
template<typename Element> size_t testing::internal::NativeArray< Element >::size () const inline
Definition at line 1062 of file gtest-internal.h.
 { return size_; }
Member Data Documentation
template<typename Element> const Element * testing::internal::NativeArray< Element >::array_ private
Definition at line 1092 of file gtest-internal.h.
Referenced by testing::internal::NativeArray< Element >::NativeArray().
template<typename Element> void(NativeArray::* testing::internal::NativeArray< Element >::clone_)(const Element *, size_t) private
Definition at line 1094 of file gtest-internal.h.
Referenced by testing::internal::NativeArray< Element >::NativeArray().
template<typename Element> size_t testing::internal::NativeArray< Element >::size_ private
Definition at line 1093 of file gtest-internal.h.
Referenced by testing::internal::NativeArray< Element >::NativeArray().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/internal/gtest-internal.h