proxygen: testing::internal::TestEventRepeater Class Reference
testing::internal::TestEventRepeater Class Reference
Public Member Functions
TestEventRepeater ()
virtual ~TestEventRepeater ()
void Append (TestEventListener *listener)
TestEventListener * Release (TestEventListener *listener)
bool forwarding_enabled () const
void set_forwarding_enabled (bool enable)
virtual void OnTestProgramStart (const UnitTest &unit_test)
virtual void OnTestIterationStart (const UnitTest &unit_test, int iteration)
virtual void OnEnvironmentsSetUpStart (const UnitTest &unit_test)
virtual void OnEnvironmentsSetUpEnd (const UnitTest &unit_test)
virtual void OnTestCaseStart (const TestCase &test_case)
virtual void OnTestStart (const TestInfo &test_info)
virtual void OnTestPartResult (const TestPartResult &result)
virtual void OnTestEnd (const TestInfo &test_info)
virtual void OnTestCaseEnd (const TestCase &test_case)
virtual void OnEnvironmentsTearDownStart (const UnitTest &unit_test)
virtual void OnEnvironmentsTearDownEnd (const UnitTest &unit_test)
virtual void OnTestIterationEnd (const UnitTest &unit_test, int iteration)
virtual void OnTestProgramEnd (const UnitTest &unit_test)
TestEventRepeater ()
virtual ~TestEventRepeater ()
void Append (TestEventListener *listener)
TestEventListener * Release (TestEventListener *listener)
bool forwarding_enabled () const
void set_forwarding_enabled (bool enable)
virtual void OnTestProgramStart (const UnitTest &unit_test)
virtual void OnTestIterationStart (const UnitTest &unit_test, int iteration)
virtual void OnEnvironmentsSetUpStart (const UnitTest &unit_test)
virtual void OnEnvironmentsSetUpEnd (const UnitTest &unit_test)
virtual void OnTestCaseStart (const TestCase &test_case)
virtual void OnTestStart (const TestInfo &test_info)
virtual void OnTestPartResult (const TestPartResult &result)
virtual void OnTestEnd (const TestInfo &test_info)
virtual void OnTestCaseEnd (const TestCase &test_case)
virtual void OnEnvironmentsTearDownStart (const UnitTest &unit_test)
virtual void OnEnvironmentsTearDownEnd (const UnitTest &unit_test)
virtual void OnTestIterationEnd (const UnitTest &unit_test, int iteration)
virtual void OnTestProgramEnd (const UnitTest &unit_test)
TestEventRepeater ()
virtual ~TestEventRepeater ()
void Append (TestEventListener *listener)
TestEventListener * Release (TestEventListener *listener)
bool forwarding_enabled () const
void set_forwarding_enabled (bool enable)
virtual void OnTestProgramStart (const UnitTest &unit_test)
virtual void OnTestIterationStart (const UnitTest &unit_test, int iteration)
virtual void OnEnvironmentsSetUpStart (const UnitTest &unit_test)
virtual void OnEnvironmentsSetUpEnd (const UnitTest &unit_test)
virtual void OnTestCaseStart (const TestCase &test_case)
virtual void OnTestStart (const TestInfo &test_info)
virtual void OnTestPartResult (const TestPartResult &result)
virtual void OnTestEnd (const TestInfo &test_info)
virtual void OnTestCaseEnd (const TestCase &test_case)
virtual void OnEnvironmentsTearDownStart (const UnitTest &unit_test)
virtual void OnEnvironmentsTearDownEnd (const UnitTest &unit_test)
virtual void OnTestIterationEnd (const UnitTest &unit_test, int iteration)
virtual void OnTestProgramEnd (const UnitTest &unit_test)
Public Member Functions inherited from testing::TestEventListener
virtual ~TestEventListener ()
virtual ~TestEventListener ()
virtual ~TestEventListener ()
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestEventRepeater)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestEventRepeater)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestEventRepeater)
Private Attributes
bool forwarding_enabled_
std::vector< TestEventListener * > listeners_
Detailed Description
Definition at line 3236 of file gtest.cc.
Constructor & Destructor Documentation
testing::internal::TestEventRepeater::TestEventRepeater () inline
Definition at line 3238 of file gtest.cc.
 : forwarding_enabled_(true) {}
testing::internal::TestEventRepeater::~TestEventRepeater () virtual
Definition at line 3272 of file gtest.cc.
References testing::internal::ForEach().
Referenced by set_forwarding_enabled().
{
   ForEach(listeners_, Delete<TestEventListener>);
 }
testing::internal::TestEventRepeater::TestEventRepeater () inline
Definition at line 3238 of file gtest.cc.
 : forwarding_enabled_(true) {}
virtual testing::internal::TestEventRepeater::~TestEventRepeater () virtual
testing::internal::TestEventRepeater::TestEventRepeater () inline
Definition at line 3238 of file gtest.cc.
 : forwarding_enabled_(true) {}
virtual testing::internal::TestEventRepeater::~TestEventRepeater () virtual
Member Function Documentation
void testing::internal::TestEventRepeater::Append (TestEventListener * listener)
Definition at line 3276 of file gtest.cc.
Referenced by testing::TestEventListeners::Append(), and set_forwarding_enabled().
{
   listeners_.push_back(listener);
 }
void testing::internal::TestEventRepeater::Append (TestEventListener * listener)
void testing::internal::TestEventRepeater::Append (TestEventListener * listener)
bool testing::internal::TestEventRepeater::forwarding_enabled () const inline
Definition at line 3245 of file gtest.cc.
 { return forwarding_enabled_; }
bool testing::internal::TestEventRepeater::forwarding_enabled () const inline
Definition at line 3245 of file gtest.cc.
 { return forwarding_enabled_; }
bool testing::internal::TestEventRepeater::forwarding_enabled () const inline
Definition at line 3245 of file gtest.cc.
Referenced by testing::TestEventListeners::EventForwardingEnabled().
 { return forwarding_enabled_; }
testing::internal::TestEventRepeater::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestEventRepeater) private
testing::internal::TestEventRepeater::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestEventRepeater) private
testing::internal::TestEventRepeater::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestEventRepeater) private
void testing::internal::TestEventRepeater::OnEnvironmentsSetUpEnd (const UnitTest & unit_test) virtual
Implements testing::TestEventListener.
Definition at line 3319 of file gtest.cc.
virtual void testing::internal::TestEventRepeater::OnEnvironmentsSetUpEnd (const UnitTest & unit_test) virtual
Implements testing::TestEventListener.
virtual void testing::internal::TestEventRepeater::OnEnvironmentsSetUpEnd (const UnitTest & unit_test) virtual
Implements testing::TestEventListener.
virtual void testing::internal::TestEventRepeater::OnEnvironmentsSetUpStart (const UnitTest & unit_test) virtual
Implements testing::TestEventListener.
virtual void testing::internal::TestEventRepeater::OnEnvironmentsSetUpStart (const UnitTest & unit_test) virtual
Implements testing::TestEventListener.
void testing::internal::TestEventRepeater::OnEnvironmentsSetUpStart (const UnitTest & unit_test) virtual
Implements testing::TestEventListener.
Definition at line 3314 of file gtest.cc.
virtual void testing::internal::TestEventRepeater::OnEnvironmentsTearDownEnd (const UnitTest & unit_test) virtual
Implements testing::TestEventListener.
virtual void testing::internal::TestEventRepeater::OnEnvironmentsTearDownEnd (const UnitTest & unit_test) virtual
Implements testing::TestEventListener.
void testing::internal::TestEventRepeater::OnEnvironmentsTearDownEnd (const UnitTest & unit_test) virtual
Implements testing::TestEventListener.
Definition at line 3320 of file gtest.cc.
virtual void testing::internal::TestEventRepeater::OnEnvironmentsTearDownStart (const UnitTest & unit_test) virtual
Implements testing::TestEventListener.
virtual void testing::internal::TestEventRepeater::OnEnvironmentsTearDownStart (const UnitTest & unit_test) virtual
Implements testing::TestEventListener.
void testing::internal::TestEventRepeater::OnEnvironmentsTearDownStart (const UnitTest & unit_test) virtual
Implements testing::TestEventListener.
Definition at line 3318 of file gtest.cc.
void testing::internal::TestEventRepeater::OnTestCaseEnd (const TestCase & test_case) virtual
Implements testing::TestEventListener.
Definition at line 3322 of file gtest.cc.
virtual void testing::internal::TestEventRepeater::OnTestCaseEnd (const TestCase & test_case) virtual
Implements testing::TestEventListener.
virtual void testing::internal::TestEventRepeater::OnTestCaseEnd (const TestCase & test_case) virtual
Implements testing::TestEventListener.
virtual void testing::internal::TestEventRepeater::OnTestCaseStart (const TestCase & test_case) virtual
Implements testing::TestEventListener.
void testing::internal::TestEventRepeater::OnTestCaseStart (const TestCase & test_case) virtual
Implements testing::TestEventListener.
Definition at line 3315 of file gtest.cc.
virtual void testing::internal::TestEventRepeater::OnTestCaseStart (const TestCase & test_case) virtual
Implements testing::TestEventListener.
virtual void testing::internal::TestEventRepeater::OnTestEnd (const TestInfo & test_info) virtual
Implements testing::TestEventListener.
void testing::internal::TestEventRepeater::OnTestEnd (const TestInfo & test_info) virtual
Implements testing::TestEventListener.
Definition at line 3321 of file gtest.cc.
virtual void testing::internal::TestEventRepeater::OnTestEnd (const TestInfo & test_info) virtual
Implements testing::TestEventListener.
void testing::internal::TestEventRepeater::OnTestIterationEnd (const UnitTest & unit_test, int iteration) virtual
Implements testing::TestEventListener.
Definition at line 3337 of file gtest.cc.
References i.
{
   if (forwarding_enabled_) {
     for (int i = static_cast<int>(listeners_.size()) - 1; i >= 0; i--) {
       listeners_[i]->OnTestIterationEnd(unit_test, iteration);
     }
   }
 }
virtual void testing::internal::TestEventRepeater::OnTestIterationEnd (const UnitTest & unit_test, int iteration) virtual
Implements testing::TestEventListener.
virtual void testing::internal::TestEventRepeater::OnTestIterationEnd (const UnitTest & unit_test, int iteration) virtual
Implements testing::TestEventListener.
virtual void testing::internal::TestEventRepeater::OnTestIterationStart (const UnitTest & unit_test, int iteration) virtual
Implements testing::TestEventListener.
virtual void testing::internal::TestEventRepeater::OnTestIterationStart (const UnitTest & unit_test, int iteration) virtual
Implements testing::TestEventListener.
void testing::internal::TestEventRepeater::OnTestIterationStart (const UnitTest & unit_test, int iteration) virtual
Implements testing::TestEventListener.
Definition at line 3328 of file gtest.cc.
References i.
{
   if (forwarding_enabled_) {
     for (size_t i = 0; i < listeners_.size(); i++) {
       listeners_[i]->OnTestIterationStart(unit_test, iteration);
     }
   }
 }
void testing::internal::TestEventRepeater::OnTestPartResult (const TestPartResult & result) virtual
Implements testing::TestEventListener.
Definition at line 3317 of file gtest.cc.
virtual void testing::internal::TestEventRepeater::OnTestPartResult (const TestPartResult & result) virtual
Implements testing::TestEventListener.
virtual void testing::internal::TestEventRepeater::OnTestPartResult (const TestPartResult & result) virtual
Implements testing::TestEventListener.
virtual void testing::internal::TestEventRepeater::OnTestProgramEnd (const UnitTest & unit_test) virtual
Implements testing::TestEventListener.
void testing::internal::TestEventRepeater::OnTestProgramEnd (const UnitTest & unit_test) virtual
Implements testing::TestEventListener.
Definition at line 3323 of file gtest.cc.
virtual void testing::internal::TestEventRepeater::OnTestProgramEnd (const UnitTest & unit_test) virtual
Implements testing::TestEventListener.
void testing::internal::TestEventRepeater::OnTestProgramStart (const UnitTest & unit_test) virtual
Implements testing::TestEventListener.
Definition at line 3313 of file gtest.cc.
virtual void testing::internal::TestEventRepeater::OnTestProgramStart (const UnitTest & unit_test) virtual
Implements testing::TestEventListener.
virtual void testing::internal::TestEventRepeater::OnTestProgramStart (const UnitTest & unit_test) virtual
Implements testing::TestEventListener.
virtual void testing::internal::TestEventRepeater::OnTestStart (const TestInfo & test_info) virtual
Implements testing::TestEventListener.
virtual void testing::internal::TestEventRepeater::OnTestStart (const TestInfo & test_info) virtual
Implements testing::TestEventListener.
void testing::internal::TestEventRepeater::OnTestStart (const TestInfo & test_info) virtual
Implements testing::TestEventListener.
Definition at line 3316 of file gtest.cc.
TestEventListener * testing::internal::TestEventRepeater::Release (TestEventListener * listener)
Definition at line 3281 of file gtest.cc.
References i.
Referenced by testing::TestEventListeners::Release(), and set_forwarding_enabled().
{
   for (size_t i = 0; i < listeners_.size(); ++i) {
     if (listeners_[i] == listener) {
       listeners_.erase(listeners_.begin() + i);
       return listener;
     }
   }
   return NULL;
 }
TestEventListener* testing::internal::TestEventRepeater::Release (TestEventListener * listener)
TestEventListener* testing::internal::TestEventRepeater::Release (TestEventListener * listener)
void testing::internal::TestEventRepeater::set_forwarding_enabled (bool enable) inline
Definition at line 3246 of file gtest.cc.
Referenced by testing::TestEventListeners::SuppressEventForwarding().
 { forwarding_enabled_ = enable; }
void testing::internal::TestEventRepeater::set_forwarding_enabled (bool enable) inline
Definition at line 3246 of file gtest.cc.
References Append(), testing::internal::ForEach(), GTEST_DISALLOW_COPY_AND_ASSIGN_, i, Release(), and ~TestEventRepeater().
 { forwarding_enabled_ = enable; }
void testing::internal::TestEventRepeater::set_forwarding_enabled (bool enable) inline
Definition at line 3246 of file gtest.cc.
References Append(), testing::internal::ForEach(), GTEST_DISALLOW_COPY_AND_ASSIGN_, i, Release(), and ~TestEventRepeater().
 { forwarding_enabled_ = enable; }
Member Data Documentation
bool testing::internal::TestEventRepeater::forwarding_enabled_ private
Definition at line 3265 of file gtest.cc.
std::vector< TestEventListener * > testing::internal::TestEventRepeater::listeners_ private
Definition at line 3267 of file gtest.cc.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest.cc