proxygen: deadlock.Deadlock Class Reference
deadlock.Deadlock Class Reference
Public Member Functions
def __init__ (self)
def invoke (self, arg, from_tty)
Detailed Description
Detects deadlocks
Definition at line 397 of file deadlock.py.
Constructor & Destructor Documentation
def deadlock.Deadlock.__init__ (self)
Definition at line 400 of file deadlock.py.
     def __init__(self):
         super(Deadlock, self).__init__('deadlock', gdb.COMMAND_NONE)
Member Function Documentation
def deadlock.Deadlock.invoke (self, arg, from_tty)
Prints the threads and mutexes in a deadlock, if it exists.
Definition at line 403 of file deadlock.py.
References deadlock.find_cycle(), deadlock.get_thread_info(), and deadlock.print_cycle().
     def invoke(self, arg, from_tty):
         '''Prints the threads and mutexes in a deadlock, if it exists.'''
         lwp_to_thread_id, blocked_threads = get_thread_info()
         # Nodes represent threads. Edge (A,B) exists if thread A
         # is waiting on a mutex held by thread B.
         graph = DiGraph()
         # Go through all the blocked threads and see which threads
         # they are blocked on, and build the thread wait graph.
         for thread_lwp, mutex_type in blocked_threads.items():
             get_owner_and_address_func = \
                 MutexType.get_mutex_owner_and_address_func_for_type(mutex_type)
             if not get_owner_and_address_func:
                 continue
             mutex_owner_lwp, mutex_address = get_owner_and_address_func(
                 lwp_to_thread_id, thread_lwp
             )
             if mutex_owner_lwp and mutex_address:
                 graph.add_edge(
                     thread_lwp,
                     mutex_owner_lwp,
                     mutex=mutex_address,
                     mutex_type=mutex_type
                 )
         # A deadlock exists if there is a cycle in the graph.
         cycle = find_cycle(graph)
         if cycle:
             print('Found deadlock!')
             print_cycle(graph, lwp_to_thread_id, cycle)
         else:
             print(
                 'No deadlock detected. '
                 'Do you have debug symbols installed?'
             )
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/gdb/deadlock.py