proxygen: fizz::test::KeySchedulerTest Class Reference
fizz::test::KeySchedulerTest Class Reference
Public Member Functions
void SetUp () override
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Protected Attributes
StringPiece transcript_ {"hash"}
MockKeyDerivation * kd_
std::unique_ptr< KeyScheduler > ks_
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Protected Member Functions inherited from testing::Test
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Detailed Description
Definition at line 21 of file KeySchedulerTest.cpp.
Member Function Documentation
void fizz::test::KeySchedulerTest::SetUp () inline override virtual
Reimplemented from testing::Test.
Definition at line 23 of file KeySchedulerTest.cpp.
References testing::_, folly::IOBuf::create(), testing::InvokeWithoutArgs(), folly::gen::move, ON_CALL, and testing::Return().
{
     auto kd = std::make_unique<MockKeyDerivation>();
     kd_ = kd.get();
     ON_CALL(*kd_, hashLength()).WillByDefault(Return(4));
     ON_CALL(*kd_, _expandLabel(_, _, _, _))
         .WillByDefault(InvokeWithoutArgs([]() { return IOBuf::create(0); }));
     ks_ = std::make_unique<KeyScheduler>(std::move(kd));
   }
Member Data Documentation
MockKeyDerivation* fizz::test::KeySchedulerTest::kd_ protected
Definition at line 34 of file KeySchedulerTest.cpp.
std::unique_ptr<KeyScheduler> fizz::test::KeySchedulerTest::ks_ protected
Definition at line 35 of file KeySchedulerTest.cpp.
StringPiece fizz::test::KeySchedulerTest::transcript_ {"hash"} protected
Definition at line 33 of file KeySchedulerTest.cpp.
The documentation for this class was generated from the following file:
proxygen/fizz/fizz/protocol/test/KeySchedulerTest.cpp