proxygen: wangle::InboundContextImpl< H > Class Template Reference
wangle::InboundContextImpl< H > Class Template Reference
#include <HandlerContext-inl.h>
Public Types
typedef H::rin Rin
typedef H::rout Rout
typedef H::win Win
typedef H::wout Wout
Public Member Functions
InboundContextImpl (std::weak_ptr< PipelineBase > pipeline, std::shared_ptr< H > handler)
InboundContextImpl ()
~InboundContextImpl () override=default
void fireRead (Rout msg) override
void fireReadEOF () override
void fireReadException (folly::exception_wrapper e) override
void fireTransportActive () override
void fireTransportInactive () override
PipelineBase * getPipeline () override
std::shared_ptr< PipelineBase > getPipelineShared () override
void read (Rin msg) override
void readEOF () override
void readException (folly::exception_wrapper e) override
void transportActive () override
void transportInactive () override
Public Member Functions inherited from wangle::InboundHandlerContext< H::rout >
virtual ~InboundHandlerContext ()=default
std::shared_ptr< folly::AsyncTransport > getTransport ()
Public Member Functions inherited from wangle::InboundLink< H::rin >
virtual ~InboundLink ()=default
Public Member Functions inherited from wangle::ContextImplBase< H, InboundHandlerContext< H::rout > >
~ContextImplBase () override=default
H * getHandler ()
void initialize (std::weak_ptr< PipelineBase > pipeline, std::shared_ptr< H > handler)
void attachPipeline () override
void detachPipeline () override
void setNextIn (PipelineContext *ctx) override
void setNextOut (PipelineContext *ctx) override
HandlerDir getDirection () override
Public Member Functions inherited from wangle::PipelineContext
virtual ~PipelineContext ()=default
template<class H , class HandlerContext >
void attachContext (H *handler, HandlerContext *ctx)
template<class H , class HandlerContext >
void detachContext (H *handler, HandlerContext *)
Static Public Attributes
static const HandlerDir dir = HandlerDir::IN
Additional Inherited Members
Protected Attributes inherited from wangle::ContextImplBase< H, InboundHandlerContext< H::rout > >
InboundHandlerContext< H::rout > * impl_
std::weak_ptr< PipelineBase > pipelineWeak_
PipelineBase * pipelineRaw_
std::shared_ptr< H > handler_
InboundLink< typename H::rout > * nextIn_
OutboundLink< typename H::wout > * nextOut_
Detailed Description
template<class H>
class wangle::InboundContextImpl< H >
Definition at line 323 of file HandlerContext-inl.h.
Member Typedef Documentation
template<class H > typedef H::rin wangle::InboundContextImpl< H >::Rin
Definition at line 328 of file HandlerContext-inl.h.
template<class H > typedef H::rout wangle::InboundContextImpl< H >::Rout
Definition at line 329 of file HandlerContext-inl.h.
template<class H > typedef H::win wangle::InboundContextImpl< H >::Win
Definition at line 330 of file HandlerContext-inl.h.
template<class H > typedef H::wout wangle::InboundContextImpl< H >::Wout
Definition at line 331 of file HandlerContext-inl.h.
Constructor & Destructor Documentation
template<class H > wangle::InboundContextImpl< H >::InboundContextImpl (std::weak_ptr< PipelineBase > pipeline, std::shared_ptr< H > handler) inline explicit
Definition at line 334 of file HandlerContext-inl.h.
References folly::gen::move.
{
     this->impl_ = this;
     this->initialize(pipeline, std::move(handler));
   }
template<class H > wangle::InboundContextImpl< H >::InboundContextImpl () inline
Definition at line 342 of file HandlerContext-inl.h.
{
     this->impl_ = this;
   }
template<class H > wangle::InboundContextImpl< H >::~InboundContextImpl () override default
Member Function Documentation
template<class H > void wangle::InboundContextImpl< H >::fireRead (Rout msg) inline override virtual
Implements wangle::InboundHandlerContext< H::rout >.
Definition at line 349 of file HandlerContext-inl.h.
References folly::gen::guard(), and folly::WARNING.
{
     auto guard = this->pipelineWeak_.lock();
     if (this->nextIn_) {
       this->nextIn_->read(std::forward<Rout>(msg));
     } else {
       LOG(WARNING) << "read reached end of pipeline";
     }
   }
template<class H > void wangle::InboundContextImpl< H >::fireReadEOF () inline override virtual
Implements wangle::InboundHandlerContext< H::rout >.
Definition at line 358 of file HandlerContext-inl.h.
References folly::gen::guard(), and folly::WARNING.
{
     auto guard = this->pipelineWeak_.lock();
     if (this->nextIn_) {
       this->nextIn_->readEOF();
     } else {
       LOG(WARNING) << "readEOF reached end of pipeline";
     }
   }
template<class H > void wangle::InboundContextImpl< H >::fireReadException (folly::exception_wrapper e) inline override virtual
Implements wangle::InboundHandlerContext< H::rout >.
Definition at line 367 of file HandlerContext-inl.h.
References folly::gen::guard(), folly::gen::move, and folly::WARNING.
{
     auto guard = this->pipelineWeak_.lock();
     if (this->nextIn_) {
       this->nextIn_->readException(std::move(e));
     } else {
       LOG(WARNING) << "readException reached end of pipeline";
     }
   }
template<class H > void wangle::InboundContextImpl< H >::fireTransportActive () inline override virtual
Implements wangle::InboundHandlerContext< H::rout >.
Definition at line 376 of file HandlerContext-inl.h.
References folly::gen::guard().
{
     auto guard = this->pipelineWeak_.lock();
     if (this->nextIn_) {
       this->nextIn_->transportActive();
     }
   }
template<class H > void wangle::InboundContextImpl< H >::fireTransportInactive () inline override virtual
Implements wangle::InboundHandlerContext< H::rout >.
Definition at line 383 of file HandlerContext-inl.h.
References folly::gen::guard().
{
     auto guard = this->pipelineWeak_.lock();
     if (this->nextIn_) {
       this->nextIn_->transportInactive();
     }
   }
template<class H > PipelineBase* wangle::InboundContextImpl< H >::getPipeline () inline override virtual
Implements wangle::InboundHandlerContext< H::rout >.
Definition at line 390 of file HandlerContext-inl.h.
{
     return this->pipelineRaw_;
   }
template<class H > std::shared_ptr<PipelineBase> wangle::InboundContextImpl< H >::getPipelineShared () inline override virtual
Implements wangle::InboundHandlerContext< H::rout >.
Definition at line 394 of file HandlerContext-inl.h.
{
     return this->pipelineWeak_.lock();
   }
template<class H > void wangle::InboundContextImpl< H >::read (Rin msg) inline override virtual
Implements wangle::InboundLink< H::rin >.
Definition at line 399 of file HandlerContext-inl.h.
References folly::gen::guard().
{
     auto guard = this->pipelineWeak_.lock();
     this->handler_->read(this, std::forward<Rin>(msg));
   }
template<class H > void wangle::InboundContextImpl< H >::readEOF () inline override virtual
Implements wangle::InboundLink< H::rin >.
Definition at line 404 of file HandlerContext-inl.h.
References folly::gen::guard().
{
     auto guard = this->pipelineWeak_.lock();
     this->handler_->readEOF(this);
   }
template<class H > void wangle::InboundContextImpl< H >::readException (folly::exception_wrapper e) inline override virtual
Implements wangle::InboundLink< H::rin >.
Definition at line 409 of file HandlerContext-inl.h.
References folly::gen::guard(), and folly::gen::move.
{
     auto guard = this->pipelineWeak_.lock();
     this->handler_->readException(this, std::move(e));
   }
template<class H > void wangle::InboundContextImpl< H >::transportActive () inline override virtual
Implements wangle::InboundLink< H::rin >.
Definition at line 414 of file HandlerContext-inl.h.
References folly::gen::guard().
{
     auto guard = this->pipelineWeak_.lock();
     this->handler_->transportActive(this);
   }
template<class H > void wangle::InboundContextImpl< H >::transportInactive () inline override virtual
Implements wangle::InboundLink< H::rin >.
Definition at line 419 of file HandlerContext-inl.h.
References folly::gen::guard().
{
     auto guard = this->pipelineWeak_.lock();
     this->handler_->transportInactive(this);
   }
Member Data Documentation
template<class H > const HandlerDir wangle::InboundContextImpl< H >::dir = HandlerDir::IN static
Definition at line 332 of file HandlerContext-inl.h.
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/channel/HandlerContext-inl.h