proxygen: folly::coro::detail::BlockingWaitPromise< T & > Class Template Reference
folly::coro::detail::BlockingWaitPromise< T & > Class Template Reference final
#include <BlockingWait.h>
Public Member Functions
BlockingWaitPromise () noexcept=default
~BlockingWaitPromise ()=default
BlockingWaitTask< T & > get_return_object () noexcept
void unhandled_exception () noexcept
auto yield_value (T &&value) noexcept
auto yield_value (T &value) noexcept
void return_void ()
folly::Try< std::reference_wrapper< T > > getAsTry ()
T & get ()
Public Member Functions inherited from folly::coro::detail::BlockingWaitPromiseBase
BlockingWaitPromiseBase () noexcept=default
std::experimental::suspend_always initial_suspend ()
FinalAwaiter final_suspend () noexcept
Private Attributes
folly::Try< std::reference_wrapper< T > > * result_
Additional Inherited Members
Protected Member Functions inherited from folly::coro::detail::BlockingWaitPromiseBase
void wait () noexcept
Detailed Description
template<typename T>
class folly::coro::detail::BlockingWaitPromise< T & >
Definition at line 112 of file BlockingWait.h.
Constructor & Destructor Documentation
template<typename T > folly::coro::detail::BlockingWaitPromise< T & >::BlockingWaitPromise () default noexcept
template<typename T > folly::coro::detail::BlockingWaitPromise< T & >::~BlockingWaitPromise () default
Member Function Documentation
template<typename T > T& folly::coro::detail::BlockingWaitPromise< T & >::get () inline
Definition at line 159 of file BlockingWait.h.
            {
     return getAsTry().value();
   }
template<typename T > BlockingWaitTask< T & > folly::coro::detail::BlockingWaitPromise< T & >::get_return_object () inline noexcept
Definition at line 240 of file BlockingWait.h.
{
   return BlockingWaitTask<T&>{std::experimental::coroutine_handle<
       BlockingWaitPromise<T&>>::from_promise(*this)};
 }
template<typename T > folly::Try<std::reference_wrapper<T> > folly::coro::detail::BlockingWaitPromise< T & >::getAsTry () inline
Definition at line 149 of file BlockingWait.h.
References folly::coro::detail::BlockingWaitPromiseBase::wait().
{
     folly::Try<std::reference_wrapper<T>> result;
     result_ = &result;
     std::experimental::coroutine_handle<BlockingWaitPromise<T&>>::from_promise(
         *this)
         .resume();
     this->wait();
     return result;
   }
template<typename T > void folly::coro::detail::BlockingWaitPromise< T & >::return_void () inline
Definition at line 141 of file BlockingWait.h.
                      {
     // This should never be reachable.
     // The coroutine should either have suspended at co_yield or should have
     // thrown an exception and skipped over the implicit co_return and
     // gone straight to unhandled_exception().
     std::abort();
   }
template<typename T > void folly::coro::detail::BlockingWaitPromise< T & >::unhandled_exception () inline noexcept
Definition at line 120 of file BlockingWait.h.
References folly::exception_wrapper::from_exception_ptr().
{
     result_->emplaceException(
         folly::exception_wrapper::from_exception_ptr(std::current_exception()));
   }
template<typename T > auto folly::coro::detail::BlockingWaitPromise< T & >::yield_value (T && value) inline noexcept
Definition at line 125 of file BlockingWait.h.
References folly::coro::detail::BlockingWaitPromiseBase::final_suspend(), and folly::value().
{
     result_->emplace(std::ref(value));
     return final_suspend();
   }
template<typename T > auto folly::coro::detail::BlockingWaitPromise< T & >::yield_value (T & value) inline noexcept
Definition at line 130 of file BlockingWait.h.
References folly::coro::detail::BlockingWaitPromiseBase::final_suspend(), folly::T, and folly::value().
{
     result_->emplace(std::ref(value));
     return final_suspend();
   }
Member Data Documentation
template<typename T > folly::Try<std::reference_wrapper<T> >* folly::coro::detail::BlockingWaitPromise< T & >::result_ private
Definition at line 164 of file BlockingWait.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/coro/BlockingWait.h