proxygen: folly::VirtualExecutor Class Reference
folly::VirtualExecutor Class Reference
#include <VirtualExecutor.h>
Public Member Functions
VirtualExecutor (KeepAlive<> executor)
VirtualExecutor (Executor *executor)
VirtualExecutor (Executor &executor)
VirtualExecutor (const VirtualExecutor &)=delete
VirtualExecutor & operator= (const VirtualExecutor &)=delete
uint8_t getNumPriorities () const override
void add (Func f) override
void addWithPriority (Func f, int8_t priority) override
~VirtualExecutor () override
Public Member Functions inherited from folly::DefaultKeepAliveExecutor
DefaultKeepAliveExecutor ()
virtual ~DefaultKeepAliveExecutor ()
folly::Executor::KeepAlive weakRef ()
Public Member Functions inherited from folly::Executor
virtual ~Executor ()
Private Member Functions
auto wrapFunc (Func f)
Private Attributes
const KeepAlive executor_
Additional Inherited Members
Static Public Member Functions inherited from folly::Executor
template<typename ExecutorT >
static KeepAlive< ExecutorT > getKeepAliveToken (ExecutorT *executor)
template<typename ExecutorT >
static KeepAlive< ExecutorT > getKeepAliveToken (ExecutorT &executor)
Static Public Attributes inherited from folly::Executor
static const int8_t LO_PRI = SCHAR_MIN
static const int8_t MID_PRI = 0
static const int8_t HI_PRI = SCHAR_MAX
Protected Member Functions inherited from folly::DefaultKeepAliveExecutor
void joinKeepAlive ()
Static Protected Member Functions inherited from folly::Executor
template<typename ExecutorT >
static bool isKeepAliveDummy (const KeepAlive< ExecutorT > &keepAlive)
template<typename ExecutorT >
static KeepAlive< ExecutorT > makeKeepAlive (ExecutorT *executor)
Detailed Description
VirtualExecutor implements a light-weight view onto existing Executor.
Multiple VirtualExecutors can be backed by a single Executor.
VirtualExecutor's destructor blocks until all tasks scheduled through it are complete. Executor's destructor also blocks until all VirtualExecutors backed by it are released.
Definition at line 32 of file VirtualExecutor.h.
Constructor & Destructor Documentation
folly::VirtualExecutor::VirtualExecutor (KeepAlive<> executor) inline explicit
Definition at line 52 of file VirtualExecutor.h.
References executor_, and folly::Executor::isKeepAliveDummy().
Referenced by VirtualExecutor().
       : executor_(std::move(executor)) {
     assert(!isKeepAliveDummy(executor_));
   }
folly::VirtualExecutor::VirtualExecutor (Executor * executor) inline explicit
Definition at line 57 of file VirtualExecutor.h.
       : VirtualExecutor(getKeepAliveToken(executor)) {}
folly::VirtualExecutor::VirtualExecutor (Executor & executor) inline explicit
Definition at line 60 of file VirtualExecutor.h.
References operator=(), and VirtualExecutor().
       : VirtualExecutor(getKeepAliveToken(executor)) {}
folly::VirtualExecutor::VirtualExecutor (const VirtualExecutor &) delete
folly::VirtualExecutor::~VirtualExecutor () inline override
Definition at line 78 of file VirtualExecutor.h.
References folly::DefaultKeepAliveExecutor::joinKeepAlive().
{
     joinKeepAlive();
   }
Member Function Documentation
void folly::VirtualExecutor::add (Func) inline override virtual
Enqueue a function to executed by this executor. This and all variants must be threadsafe.
Implements folly::Executor.
Definition at line 70 of file VirtualExecutor.h.
References executor_, folly::gen::move, and wrapFunc().
Referenced by virtualExecutorTest().
{
     executor_->add(wrapFunc(std::move(f)));
   }
void folly::VirtualExecutor::addWithPriority (Func , int8_t priority) inline override virtual
Enqueue a function with a given priority, where 0 is the medium priority This is up to the implementation to enforce
Reimplemented from folly::Executor.
Definition at line 74 of file VirtualExecutor.h.
References executor_, folly::gen::move, and wrapFunc().
Referenced by TEST().
{
     executor_->addWithPriority(wrapFunc(std::move(f)), priority);
   }
uint8_t folly::VirtualExecutor::getNumPriorities () const inline override virtual
Reimplemented from folly::Executor.
Definition at line 66 of file VirtualExecutor.h.
References executor_.
{
     return executor_->getNumPriorities();
   }
VirtualExecutor& folly::VirtualExecutor::operator= (const VirtualExecutor &) delete
Referenced by VirtualExecutor().
auto folly::VirtualExecutor::wrapFunc (Func f) inline private
Definition at line 33 of file VirtualExecutor.h.
References folly::pushmi::executor, folly::Executor::getKeepAliveToken(), folly::DefaultKeepAliveExecutor::keepAlive_, and folly::gen::move.
Referenced by add(), and addWithPriority().
{
     class FuncAndKeepAlive {
      public:
       FuncAndKeepAlive(Func&& f, VirtualExecutor* executor)
           : keepAlive_(getKeepAliveToken(executor)), f_(std::move(f)) {}
       void operator()() {
         f_();
       }
      private:
       Executor::KeepAlive<VirtualExecutor> keepAlive_;
       Func f_;
     };
     return FuncAndKeepAlive(std::move(f), this);
   }
Member Data Documentation
const KeepAlive folly::VirtualExecutor::executor_ private
Definition at line 83 of file VirtualExecutor.h.
Referenced by add(), addWithPriority(), getNumPriorities(), and VirtualExecutor().
The documentation for this class was generated from the following file:
proxygen/folly/folly/VirtualExecutor.h