proxygen: SequenceTestingListener Class Reference
SequenceTestingListener Class Reference
Public Member Functions
SequenceTestingListener (std::vector< std::string > *vector, const char *id)
SequenceTestingListener (std::vector< std::string > *vector, const char *id)
SequenceTestingListener (std::vector< std::string > *vector, const char *id)
Public Member Functions inherited from testing::EmptyTestEventListener
virtual void OnEnvironmentsSetUpStart (const UnitTest &)
virtual void OnEnvironmentsSetUpEnd (const UnitTest &)
virtual void OnTestCaseStart (const TestCase &)
virtual void OnTestStart (const TestInfo &)
virtual void OnTestPartResult (const TestPartResult &)
virtual void OnTestEnd (const TestInfo &)
virtual void OnTestCaseEnd (const TestCase &)
virtual void OnEnvironmentsTearDownStart (const UnitTest &)
virtual void OnEnvironmentsTearDownEnd (const UnitTest &)
virtual void OnEnvironmentsSetUpStart (const UnitTest &)
virtual void OnEnvironmentsSetUpEnd (const UnitTest &)
virtual void OnTestCaseStart (const TestCase &)
virtual void OnTestStart (const TestInfo &)
virtual void OnTestPartResult (const TestPartResult &)
virtual void OnTestEnd (const TestInfo &)
virtual void OnTestCaseEnd (const TestCase &)
virtual void OnEnvironmentsTearDownStart (const UnitTest &)
virtual void OnEnvironmentsTearDownEnd (const UnitTest &)
virtual void OnEnvironmentsSetUpStart (const UnitTest &)
virtual void OnEnvironmentsSetUpEnd (const UnitTest &)
virtual void OnTestCaseStart (const TestCase &)
virtual void OnTestStart (const TestInfo &)
virtual void OnTestPartResult (const TestPartResult &)
virtual void OnTestEnd (const TestInfo &)
virtual void OnTestCaseEnd (const TestCase &)
virtual void OnEnvironmentsTearDownStart (const UnitTest &)
virtual void OnEnvironmentsTearDownEnd (const UnitTest &)
Public Member Functions inherited from testing::TestEventListener
virtual ~TestEventListener ()
virtual ~TestEventListener ()
virtual ~TestEventListener ()
Protected Member Functions
virtual void OnTestProgramStart (const UnitTest &)
virtual void OnTestProgramEnd (const UnitTest &)
virtual void OnTestIterationStart (const UnitTest &, int)
virtual void OnTestIterationEnd (const UnitTest &, int)
virtual void OnTestProgramStart (const UnitTest &)
virtual void OnTestProgramEnd (const UnitTest &)
virtual void OnTestIterationStart (const UnitTest &, int)
virtual void OnTestIterationEnd (const UnitTest &, int)
virtual void OnTestProgramStart (const UnitTest &)
virtual void OnTestProgramEnd (const UnitTest &)
virtual void OnTestIterationStart (const UnitTest &, int)
virtual void OnTestIterationEnd (const UnitTest &, int)
Private Member Functions
std::string GetEventDescription (const char *method)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (SequenceTestingListener)
std::string GetEventDescription (const char *method)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (SequenceTestingListener)
std::string GetEventDescription (const char *method)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (SequenceTestingListener)
Private Attributes
std::vector< std::string > * vector_
const char *const id_
Detailed Description
Definition at line 7060 of file gtest_unittest.cc.
Constructor & Destructor Documentation
SequenceTestingListener::SequenceTestingListener (std::vector< std::string > * vector, const char * id) inline
Definition at line 7062 of file gtest_unittest.cc.
       : vector_(vector), id_(id) {}
SequenceTestingListener::SequenceTestingListener (std::vector< std::string > * vector, const char * id) inline
Definition at line 7062 of file gtest_unittest.cc.
       : vector_(vector), id_(id) {}
SequenceTestingListener::SequenceTestingListener (std::vector< std::string > * vector, const char * id) inline
Definition at line 7062 of file gtest_unittest.cc.
       : vector_(vector), id_(id) {}
Member Function Documentation
std::string SequenceTestingListener::GetEventDescription (const char * method) inline private
Definition at line 7085 of file gtest_unittest.cc.
References testing::Message::GetString(), and message.
{
     Message message;
     message << id_ << "." << method;
     return message.GetString();
   }
std::string SequenceTestingListener::GetEventDescription (const char * method) inline private
Definition at line 7085 of file gtest_unittest.cc.
References testing::Message::GetString(), GTEST_DISALLOW_COPY_AND_ASSIGN_, and message.
{
     Message message;
     message << id_ << "." << method;
     return message.GetString();
   }
std::string SequenceTestingListener::GetEventDescription (const char * method) inline private
Definition at line 7085 of file gtest_unittest.cc.
References testing::Message::GetString(), GTEST_DISALLOW_COPY_AND_ASSIGN_, and message.
{
     Message message;
     message << id_ << "." << method;
     return message.GetString();
   }
SequenceTestingListener::GTEST_DISALLOW_COPY_AND_ASSIGN_ (SequenceTestingListener) private
SequenceTestingListener::GTEST_DISALLOW_COPY_AND_ASSIGN_ (SequenceTestingListener) private
SequenceTestingListener::GTEST_DISALLOW_COPY_AND_ASSIGN_ (SequenceTestingListener) private
virtual void SequenceTestingListener::OnTestIterationEnd (const UnitTest & , int) inline protected virtual
Reimplemented from testing::EmptyTestEventListener.
Definition at line 7079 of file gtest_unittest.cc.
{
     vector_->push_back(GetEventDescription("OnTestIterationEnd"));
   }
virtual void SequenceTestingListener::OnTestIterationEnd (const UnitTest & , int) inline protected virtual
Reimplemented from testing::EmptyTestEventListener.
Definition at line 7079 of file gtest_unittest.cc.
{
     vector_->push_back(GetEventDescription("OnTestIterationEnd"));
   }
virtual void SequenceTestingListener::OnTestIterationEnd (const UnitTest & , int) inline protected virtual
Reimplemented from testing::EmptyTestEventListener.
Definition at line 7079 of file gtest_unittest.cc.
{
     vector_->push_back(GetEventDescription("OnTestIterationEnd"));
   }
virtual void SequenceTestingListener::OnTestIterationStart (const UnitTest & , int) inline protected virtual
Reimplemented from testing::EmptyTestEventListener.
Definition at line 7074 of file gtest_unittest.cc.
{
     vector_->push_back(GetEventDescription("OnTestIterationStart"));
   }
virtual void SequenceTestingListener::OnTestIterationStart (const UnitTest & , int) inline protected virtual
Reimplemented from testing::EmptyTestEventListener.
Definition at line 7074 of file gtest_unittest.cc.
{
     vector_->push_back(GetEventDescription("OnTestIterationStart"));
   }
virtual void SequenceTestingListener::OnTestIterationStart (const UnitTest & , int) inline protected virtual
Reimplemented from testing::EmptyTestEventListener.
Definition at line 7074 of file gtest_unittest.cc.
{
     vector_->push_back(GetEventDescription("OnTestIterationStart"));
   }
virtual void SequenceTestingListener::OnTestProgramEnd (const UnitTest &) inline protected virtual
Reimplemented from testing::EmptyTestEventListener.
Definition at line 7070 of file gtest_unittest.cc.
{
     vector_->push_back(GetEventDescription("OnTestProgramEnd"));
   }
virtual void SequenceTestingListener::OnTestProgramEnd (const UnitTest &) inline protected virtual
Reimplemented from testing::EmptyTestEventListener.
Definition at line 7070 of file gtest_unittest.cc.
{
     vector_->push_back(GetEventDescription("OnTestProgramEnd"));
   }
virtual void SequenceTestingListener::OnTestProgramEnd (const UnitTest &) inline protected virtual
Reimplemented from testing::EmptyTestEventListener.
Definition at line 7070 of file gtest_unittest.cc.
{
     vector_->push_back(GetEventDescription("OnTestProgramEnd"));
   }
virtual void SequenceTestingListener::OnTestProgramStart (const UnitTest &) inline protected virtual
Reimplemented from testing::EmptyTestEventListener.
Definition at line 7066 of file gtest_unittest.cc.
{
     vector_->push_back(GetEventDescription("OnTestProgramStart"));
   }
virtual void SequenceTestingListener::OnTestProgramStart (const UnitTest &) inline protected virtual
Reimplemented from testing::EmptyTestEventListener.
Definition at line 7066 of file gtest_unittest.cc.
{
     vector_->push_back(GetEventDescription("OnTestProgramStart"));
   }
virtual void SequenceTestingListener::OnTestProgramStart (const UnitTest &) inline protected virtual
Reimplemented from testing::EmptyTestEventListener.
Definition at line 7066 of file gtest_unittest.cc.
{
     vector_->push_back(GetEventDescription("OnTestProgramStart"));
   }
Member Data Documentation
const char *const SequenceTestingListener::id_ private
Definition at line 7092 of file gtest_unittest.cc.
std::vector< std::string > * SequenceTestingListener::vector_ private
Definition at line 7091 of file gtest_unittest.cc.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest_unittest.cc