proxygen: testing::TestCase Class Reference
testing::TestCase Class Reference
#include <gtest.h>
Public Member Functions
TestCase (const char *name, const char *a_type_param, Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc)
virtual ~TestCase ()
const char * name () const
const char * type_param () const
bool should_run () const
int successful_test_count () const
int failed_test_count () const
int reportable_disabled_test_count () const
int disabled_test_count () const
int reportable_test_count () const
int test_to_run_count () const
int total_test_count () const
bool Passed () const
bool Failed () const
TimeInMillis elapsed_time () const
const TestInfo * GetTestInfo (int i) const
const TestResult & ad_hoc_test_result () const
TestCase (const char *name, const char *a_type_param, Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc)
virtual ~TestCase ()
const char * name () const
const char * type_param () const
bool should_run () const
int successful_test_count () const
int failed_test_count () const
int reportable_disabled_test_count () const
int disabled_test_count () const
int reportable_test_count () const
int test_to_run_count () const
int total_test_count () const
bool Passed () const
bool Failed () const
TimeInMillis elapsed_time () const
const TestInfo * GetTestInfo (int i) const
const TestResult & ad_hoc_test_result () const
TestCase (const char *name, const char *a_type_param, Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc)
virtual ~TestCase ()
const char * name () const
const char * type_param () const
bool should_run () const
int successful_test_count () const
int failed_test_count () const
int reportable_disabled_test_count () const
int disabled_test_count () const
int reportable_test_count () const
int test_to_run_count () const
int total_test_count () const
bool Passed () const
bool Failed () const
TimeInMillis elapsed_time () const
const TestInfo * GetTestInfo (int i) const
const TestResult & ad_hoc_test_result () const
Private Member Functions
std::vector< TestInfo * > & test_info_list ()
const std::vector< TestInfo * > & test_info_list () const
TestInfo * GetMutableTestInfo (int i)
void set_should_run (bool should)
void AddTestInfo (TestInfo *test_info)
void ClearResult ()
void Run ()
void RunSetUpTestCase ()
void RunTearDownTestCase ()
void ShuffleTests (internal::Random *random)
void UnshuffleTests ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestCase)
std::vector< TestInfo * > & test_info_list ()
const std::vector< TestInfo * > & test_info_list () const
TestInfo * GetMutableTestInfo (int i)
void set_should_run (bool should)
void AddTestInfo (TestInfo *test_info)
void ClearResult ()
void Run ()
void RunSetUpTestCase ()
void RunTearDownTestCase ()
void ShuffleTests (internal::Random *random)
void UnshuffleTests ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestCase)
std::vector< TestInfo * > & test_info_list ()
const std::vector< TestInfo * > & test_info_list () const
TestInfo * GetMutableTestInfo (int i)
void set_should_run (bool should)
void AddTestInfo (TestInfo *test_info)
void ClearResult ()
void Run ()
void RunSetUpTestCase ()
void RunTearDownTestCase ()
void ShuffleTests (internal::Random *random)
void UnshuffleTests ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestCase)
Static Private Member Functions
static void ClearTestCaseResult (TestCase *test_case)
static bool TestPassed (const TestInfo *test_info)
static bool TestFailed (const TestInfo *test_info)
static bool TestReportableDisabled (const TestInfo *test_info)
static bool TestDisabled (const TestInfo *test_info)
static bool TestReportable (const TestInfo *test_info)
static bool ShouldRunTest (const TestInfo *test_info)
static void ClearTestCaseResult (TestCase *test_case)
static bool TestPassed (const TestInfo *test_info)
static bool TestFailed (const TestInfo *test_info)
static bool TestReportableDisabled (const TestInfo *test_info)
static bool TestDisabled (const TestInfo *test_info)
static bool TestReportable (const TestInfo *test_info)
static bool ShouldRunTest (const TestInfo *test_info)
static void ClearTestCaseResult (TestCase *test_case)
static bool TestPassed (const TestInfo *test_info)
static bool TestFailed (const TestInfo *test_info)
static bool TestReportableDisabled (const TestInfo *test_info)
static bool TestDisabled (const TestInfo *test_info)
static bool TestReportable (const TestInfo *test_info)
static bool ShouldRunTest (const TestInfo *test_info)
Private Attributes
std::string name_
const internal::scoped_ptr< const ::std::string > type_param_
std::vector< TestInfo * > test_info_list_
std::vector< int > test_indices_
Test::SetUpTestCaseFunc set_up_tc_
Test::TearDownTestCaseFunc tear_down_tc_
bool should_run_
TimeInMillis elapsed_time_
TestResult ad_hoc_test_result_
Friends
class Test
class internal::UnitTestImpl
Detailed Description
Definition at line 778 of file gtest.h.
Constructor & Destructor Documentation
testing::TestCase::TestCase (const char * name, const char * a_type_param, Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc)
Definition at line 2720 of file gtest.cc.
     : name_(a_name),
       type_param_(a_type_param ? new std::string(a_type_param) : NULL),
       set_up_tc_(set_up_tc),
       tear_down_tc_(tear_down_tc),
       should_run_(false),
       elapsed_time_(0) {
 }
testing::TestCase::~TestCase () virtual
Definition at line 2732 of file gtest.cc.
References testing::internal::ForEach(), and test_info_list_.
                     {
   // Deletes every Test in the collection.
   ForEach(test_info_list_, internal::Delete<TestInfo>);
 }
testing::TestCase::TestCase (const char * name, const char * a_type_param, Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc)
virtual testing::TestCase::~TestCase () virtual
testing::TestCase::TestCase (const char * name, const char * a_type_param, Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc)
virtual testing::TestCase::~TestCase () virtual
Member Function Documentation
const TestResult& testing::TestCase::ad_hoc_test_result () const inline
Definition at line 849 of file gtest.h.
Referenced by testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), and testing::internal::PortableLocaltime().
 { return ad_hoc_test_result_; }
const TestResult& testing::TestCase::ad_hoc_test_result () const inline
Definition at line 849 of file gtest.h.
 { return ad_hoc_test_result_; }
const TestResult& testing::TestCase::ad_hoc_test_result () const inline
Definition at line 849 of file gtest.h.
 { return ad_hoc_test_result_; }
void testing::TestCase::AddTestInfo (TestInfo * test_info) private
Definition at line 2753 of file gtest.cc.
References test_indices_, and test_info_list_.
{
   test_info_list_.push_back(test_info);
   test_indices_.push_back(static_cast<int>(test_indices_.size()));
 }
void testing::TestCase::AddTestInfo (TestInfo * test_info) private
void testing::TestCase::AddTestInfo (TestInfo * test_info) private
void testing::TestCase::ClearResult () private
Definition at line 2787 of file gtest.cc.
References ad_hoc_test_result_, testing::TestResult::Clear(), testing::TestInfo::ClearTestResult(), testing::internal::ForEach(), and test_info_list_.
Referenced by ClearTestCaseResult().
{
   ad_hoc_test_result_.Clear();
   ForEach(test_info_list_, TestInfo::ClearTestResult);
 }
void testing::TestCase::ClearResult () private
void testing::TestCase::ClearResult () private
static void testing::TestCase::ClearTestCaseResult (TestCase * test_case) inline static private
Definition at line 878 of file gtest.h.
References ClearResult(), and Run().
Referenced by testing::internal::UnitTestImpl::ClearNonAdHocTestResult().
{
     test_case->ClearResult();
   }
static void testing::TestCase::ClearTestCaseResult (TestCase * test_case) inline static private
Definition at line 878 of file gtest.h.
References ClearResult(), and Run().
{
     test_case->ClearResult();
   }
static void testing::TestCase::ClearTestCaseResult (TestCase * test_case) inline static private
Definition at line 878 of file gtest.h.
References ClearResult(), and Run().
{
     test_case->ClearResult();
   }
int testing::TestCase::disabled_test_count () const
int testing::TestCase::disabled_test_count () const
int testing::TestCase::disabled_test_count () const
Definition at line 2692 of file gtest.cc.
References testing::internal::CountIf().
Referenced by testing::internal::UnitTestImpl::disabled_test_count(), testing::internal::UnitTestHelper::GetSortedTests(), testing::internal::ShouldRunTestCase(), and testing::internal::TEST().
{
   return CountIf(test_info_list_, TestDisabled);
 }
TimeInMillis testing::TestCase::elapsed_time () const inline
Definition at line 841 of file gtest.h.
References i.
 { return elapsed_time_; }
TimeInMillis testing::TestCase::elapsed_time () const inline
Definition at line 841 of file gtest.h.
References i.
 { return elapsed_time_; }
TimeInMillis testing::TestCase::elapsed_time () const inline
Definition at line 841 of file gtest.h.
References i.
Referenced by testing::internal::PrettyUnitTestResultPrinter::OnTestCaseEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PortableLocaltime(), and testing::internal::TestResultAccessor::test_part_results().
 { return elapsed_time_; }
bool testing::TestCase::Failed () const inline
Definition at line 838 of file gtest.h.
 { return failed_test_count() > 0; }
bool testing::TestCase::Failed () const inline
Definition at line 838 of file gtest.h.
 { return failed_test_count() > 0; }
bool testing::TestCase::Failed () const inline
Definition at line 838 of file gtest.h.
Referenced by testing::internal::TestCaseFailed().
 { return failed_test_count() > 0; }
int testing::TestCase::failed_test_count () const
int testing::TestCase::failed_test_count () const
int testing::TestCase::failed_test_count () const
Definition at line 2682 of file gtest.cc.
References testing::internal::CountIf().
Referenced by testing::internal::UnitTestImpl::failed_test_count(), testing::internal::PrettyUnitTestResultPrinter::OnTestIterationEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PortableLocaltime(), testing::internal::PrettyUnitTestResultPrinter::PrintFailedTests(), and testing::internal::ShouldRunTestCase().
{
   return CountIf(test_info_list_, TestFailed);
 }
TestInfo * testing::TestCase::GetMutableTestInfo (int i) private
Definition at line 2746 of file gtest.cc.
References testing::internal::GetElementOr(), test_indices_, and test_info_list_.
Referenced by Run().
{
   const int index = GetElementOr(test_indices_, i, -1);
   return index < 0 ? NULL : test_info_list_[index];
 }
TestInfo* testing::TestCase::GetMutableTestInfo (int i) private
TestInfo* testing::TestCase::GetMutableTestInfo (int i) private
const TestInfo* testing::TestCase::GetTestInfo (int i) const
const TestInfo* testing::TestCase::GetTestInfo (int i) const
const TestInfo * testing::TestCase::GetTestInfo (int i) const
Definition at line 2739 of file gtest.cc.
References testing::internal::GetElementOr(), test_indices_, and test_info_list_.
Referenced by testing::internal::UnitTestHelper::GetSortedTests(), testing::TestInfoTest::GetTestInfo(), testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PortableLocaltime(), testing::internal::PrettyUnitTestResultPrinter::PrintFailedTests(), and testing::internal::TEST().
{
   const int index = GetElementOr(test_indices_, i, -1);
   return index < 0 ? NULL : test_info_list_[index];
 }
testing::TestCase::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestCase) private
testing::TestCase::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestCase) private
testing::TestCase::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestCase) private
const char* testing::TestCase::name () const inline
Definition at line 800 of file gtest.h.
References name_.
Referenced by testing::internal::XmlUnitTestResultPrinter::EscapeXmlText(), testing::internal::UnitTestImpl::FilterTests(), testing::internal::UnitTestHelper::FindTestCase(), testing::internal::UnitTestHelper::GetSortedTests(), testing::internal::UnitTestImpl::ListTestsMatchingFilter(), testing::internal::PrettyUnitTestResultPrinter::OnTestCaseEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestCaseStart(), testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), testing::internal::TestCaseNameIs::operator()(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PortableLocaltime(), testing::internal::PrettyUnitTestResultPrinter::PrintFailedTests(), testing::internal::PrintOnOneLine(), testing::internal::TearDownEnvironment(), testing::internal::TEST(), and testing::internal::TestResultAccessor::test_part_results().
 { return name_.c_str(); }
const char* testing::TestCase::name () const inline
Definition at line 800 of file gtest.h.
References name_.
 { return name_.c_str(); }
const char* testing::TestCase::name () const inline
Definition at line 800 of file gtest.h.
References name_.
 { return name_.c_str(); }
bool testing::TestCase::Passed () const inline
Definition at line 835 of file gtest.h.
 { return !Failed(); }
bool testing::TestCase::Passed () const inline
Definition at line 835 of file gtest.h.
Referenced by testing::internal::TestResultAccessor::test_part_results(), and testing::internal::TestCasePassed().
 { return !Failed(); }
bool testing::TestCase::Passed () const inline
Definition at line 835 of file gtest.h.
 { return !Failed(); }
int testing::TestCase::reportable_disabled_test_count () const
int testing::TestCase::reportable_disabled_test_count () const
int testing::TestCase::reportable_disabled_test_count () const
Definition at line 2687 of file gtest.cc.
References testing::internal::CountIf().
Referenced by testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PortableLocaltime(), testing::internal::UnitTestImpl::reportable_disabled_test_count(), and testing::internal::ShouldRunTestCase().
{
   return CountIf(test_info_list_, TestReportableDisabled);
 }
int testing::TestCase::reportable_test_count () const
int testing::TestCase::reportable_test_count () const
Definition at line 2697 of file gtest.cc.
References testing::internal::CountIf().
Referenced by testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PortableLocaltime(), testing::internal::UnitTestImpl::reportable_test_count(), and testing::internal::ShouldRunTestCase().
{
   return CountIf(test_info_list_, TestReportable);
 }
int testing::TestCase::reportable_test_count () const
void testing::TestCase::Run () private
void testing::TestCase::Run () private
Definition at line 2759 of file gtest.cc.
References elapsed_time_, testing::UnitTest::GetInstance(), GetMutableTestInfo(), testing::internal::GetTimeInMillis(), testing::internal::GetUnitTestImpl(), testing::internal::HandleExceptionsInMethodIfSupported(), i, testing::UnitTest::listeners(), testing::TestEventListener::OnTestCaseEnd(), testing::TestEventListener::OnTestCaseStart(), testing::internal::UnitTestImpl::os_stack_trace_getter(), testing::TestEventListeners::repeater(), testing::TestInfo::Run(), RunSetUpTestCase(), RunTearDownTestCase(), testing::internal::UnitTestImpl::set_current_test_case(), should_run_, start, total_test_count(), and testing::internal::OsStackTraceGetterInterface::UponLeavingGTest().
Referenced by testing::internal::UnitTestImpl::RunAllTests().
                    {
   if (!should_run_) return;
   internal::UnitTestImpl* const impl = internal::GetUnitTestImpl();
   impl->set_current_test_case(this);
   TestEventListener* repeater = UnitTest::GetInstance()->listeners().repeater();
   repeater->OnTestCaseStart(*this);
   impl->os_stack_trace_getter()->UponLeavingGTest();
   internal::HandleExceptionsInMethodIfSupported(
       this, &TestCase::RunSetUpTestCase, "SetUpTestCase()");
   const internal::TimeInMillis start = internal::GetTimeInMillis();
   for (int i = 0; i < total_test_count(); i++) {
     GetMutableTestInfo(i)->Run();
   }
   elapsed_time_ = internal::GetTimeInMillis() - start;
   impl->os_stack_trace_getter()->UponLeavingGTest();
   internal::HandleExceptionsInMethodIfSupported(
       this, &TestCase::RunTearDownTestCase, "TearDownTestCase()");
   repeater->OnTestCaseEnd(*this);
   impl->set_current_test_case(NULL);
 }
void testing::TestCase::Run () private
void testing::TestCase::RunSetUpTestCase () inline private
Definition at line 887 of file gtest.h.
 { (*set_up_tc_)(); }
void testing::TestCase::RunSetUpTestCase () inline private
Definition at line 887 of file gtest.h.
Referenced by Run().
 { (*set_up_tc_)(); }
void testing::TestCase::RunSetUpTestCase () inline private
Definition at line 887 of file gtest.h.
 { (*set_up_tc_)(); }
void testing::TestCase::RunTearDownTestCase () inline private
Definition at line 891 of file gtest.h.
 { (*tear_down_tc_)(); }
void testing::TestCase::RunTearDownTestCase () inline private
Definition at line 891 of file gtest.h.
Referenced by Run().
 { (*tear_down_tc_)(); }
void testing::TestCase::RunTearDownTestCase () inline private
Definition at line 891 of file gtest.h.
 { (*tear_down_tc_)(); }
void testing::TestCase::set_should_run (bool should) inline private
Definition at line 868 of file gtest.h.
Referenced by testing::internal::UnitTestImpl::FilterTests(), and testing::internal::TearDownEnvironment().
 { should_run_ = should; }
void testing::TestCase::set_should_run (bool should) inline private
Definition at line 868 of file gtest.h.
 { should_run_ = should; }
void testing::TestCase::set_should_run (bool should) inline private
Definition at line 868 of file gtest.h.
 { should_run_ = should; }
bool testing::TestCase::should_run () const inline
Definition at line 811 of file gtest.h.
 { return should_run_; }
bool testing::TestCase::should_run () const inline
Definition at line 811 of file gtest.h.
 { return should_run_; }
bool testing::TestCase::should_run () const inline
Definition at line 811 of file gtest.h.
Referenced by testing::internal::UnitTestImpl::FilterTests(), testing::internal::UnitTestHelper::GetSortedTests(), testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), testing::internal::PrettyUnitTestResultPrinter::PrintFailedTests(), testing::internal::ShouldRunTestCase(), testing::internal::TearDownEnvironment(), testing::internal::TEST(), testing::internal::TestCaseFailed(), and testing::internal::TestCasePassed().
 { return should_run_; }
static bool testing::TestCase::ShouldRunTest (const TestInfo * test_info) inline static private
Definition at line 920 of file gtest.h.
References GTEST_DISALLOW_COPY_AND_ASSIGN_, name_, random(), testing::TestInfo::should_run(), and string.
{
     return test_info->should_run();
   }
static bool testing::TestCase::ShouldRunTest (const TestInfo * test_info) inline static private
Definition at line 920 of file gtest.h.
References GTEST_DISALLOW_COPY_AND_ASSIGN_, name_, random(), testing::TestInfo::should_run(), and string.
{
     return test_info->should_run();
   }
static bool testing::TestCase::ShouldRunTest (const TestInfo * test_info) inline static private
Definition at line 920 of file gtest.h.
References random(), and testing::TestInfo::should_run().
{
     return test_info->should_run();
   }
void testing::TestCase::ShuffleTests (internal::Random * random) private
void testing::TestCase::ShuffleTests (internal::Random * random) private
Definition at line 2793 of file gtest.cc.
References testing::internal::Shuffle(), and test_indices_.
{
   Shuffle(random, &test_indices_);
 }
void testing::TestCase::ShuffleTests (internal::Random * random) private
int testing::TestCase::successful_test_count () const
int testing::TestCase::successful_test_count () const
int testing::TestCase::successful_test_count () const
Definition at line 2677 of file gtest.cc.
References testing::internal::CountIf().
Referenced by testing::internal::ShouldRunTestCase(), and testing::internal::UnitTestImpl::successful_test_count().
{
   return CountIf(test_info_list_, TestPassed);
 }
std::vector<TestInfo*>& testing::TestCase::test_info_list () inline private
Definition at line 856 of file gtest.h.
Referenced by testing::internal::UnitTestImpl::FilterTests(), testing::Test::HasSameFixtureClass(), testing::internal::UnitTestImpl::ListTestsMatchingFilter(), testing::internal::PrintOnOneLine(), testing::internal::TearDownEnvironment(), and testing::TestPartNonfatallyFailed().
 { return test_info_list_; }
std::vector<TestInfo*>& testing::TestCase::test_info_list () inline private
Definition at line 856 of file gtest.h.
 { return test_info_list_; }
std::vector<TestInfo*>& testing::TestCase::test_info_list () inline private
Definition at line 856 of file gtest.h.
 { return test_info_list_; }
const std::vector<TestInfo*>& testing::TestCase::test_info_list () const inline private
Definition at line 859 of file gtest.h.
{
     return test_info_list_;
   }
const std::vector<TestInfo*>& testing::TestCase::test_info_list () const inline private
Definition at line 859 of file gtest.h.
{
     return test_info_list_;
   }
const std::vector<TestInfo*>& testing::TestCase::test_info_list () const inline private
Definition at line 859 of file gtest.h.
{
     return test_info_list_;
   }
int testing::TestCase::test_to_run_count () const
int testing::TestCase::test_to_run_count () const
Definition at line 2702 of file gtest.cc.
References testing::internal::CountIf().
Referenced by testing::internal::UnitTestHelper::GetSortedTests(), testing::internal::PrettyUnitTestResultPrinter::OnTestCaseEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestCaseStart(), testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), testing::internal::ShouldRunTestCase(), testing::internal::TEST(), and testing::internal::UnitTestImpl::test_to_run_count().
{
   return CountIf(test_info_list_, ShouldRunTest);
 }
int testing::TestCase::test_to_run_count () const
static bool testing::TestCase::TestDisabled (const TestInfo * test_info) inline static private
Definition at line 910 of file gtest.h.
References testing::TestInfo::is_disabled_.
{
     return test_info->is_disabled_;
   }
static bool testing::TestCase::TestDisabled (const TestInfo * test_info) inline static private
Definition at line 910 of file gtest.h.
References testing::TestInfo::is_disabled_.
{
     return test_info->is_disabled_;
   }
static bool testing::TestCase::TestDisabled (const TestInfo * test_info) inline static private
Definition at line 910 of file gtest.h.
References testing::TestInfo::is_disabled_.
{
     return test_info->is_disabled_;
   }
static bool testing::TestCase::TestFailed (const TestInfo * test_info) inline static private
Definition at line 899 of file gtest.h.
References testing::TestResult::Failed(), testing::TestInfo::result(), and testing::TestInfo::should_run().
{
     return test_info->should_run() && test_info->result()->Failed();
   }
static bool testing::TestCase::TestFailed (const TestInfo * test_info) inline static private
Definition at line 899 of file gtest.h.
References testing::TestResult::Failed(), testing::TestInfo::result(), and testing::TestInfo::should_run().
{
     return test_info->should_run() && test_info->result()->Failed();
   }
static bool testing::TestCase::TestFailed (const TestInfo * test_info) inline static private
Definition at line 899 of file gtest.h.
References testing::TestResult::Failed(), testing::TestInfo::result(), and testing::TestInfo::should_run().
{
     return test_info->should_run() && test_info->result()->Failed();
   }
static bool testing::TestCase::TestPassed (const TestInfo * test_info) inline static private
Definition at line 894 of file gtest.h.
References testing::TestResult::Passed(), testing::TestInfo::result(), and testing::TestInfo::should_run().
{
     return test_info->should_run() && test_info->result()->Passed();
   }
static bool testing::TestCase::TestPassed (const TestInfo * test_info) inline static private
Definition at line 894 of file gtest.h.
References testing::TestResult::Passed(), testing::TestInfo::result(), and testing::TestInfo::should_run().
{
     return test_info->should_run() && test_info->result()->Passed();
   }
static bool testing::TestCase::TestPassed (const TestInfo * test_info) inline static private
Definition at line 894 of file gtest.h.
References testing::TestResult::Passed(), testing::TestInfo::result(), and testing::TestInfo::should_run().
{
     return test_info->should_run() && test_info->result()->Passed();
   }
static bool testing::TestCase::TestReportable (const TestInfo * test_info) inline static private
Definition at line 915 of file gtest.h.
References testing::TestInfo::is_reportable().
{
     return test_info->is_reportable();
   }
static bool testing::TestCase::TestReportable (const TestInfo * test_info) inline static private
Definition at line 915 of file gtest.h.
References testing::TestInfo::is_reportable().
{
     return test_info->is_reportable();
   }
static bool testing::TestCase::TestReportable (const TestInfo * test_info) inline static private
Definition at line 915 of file gtest.h.
References testing::TestInfo::is_reportable().
{
     return test_info->is_reportable();
   }
static bool testing::TestCase::TestReportableDisabled (const TestInfo * test_info) inline static private
Definition at line 905 of file gtest.h.
References testing::TestInfo::is_disabled_, and testing::TestInfo::is_reportable().
{
     return test_info->is_reportable() && test_info->is_disabled_;
   }
static bool testing::TestCase::TestReportableDisabled (const TestInfo * test_info) inline static private
Definition at line 905 of file gtest.h.
References testing::TestInfo::is_disabled_, and testing::TestInfo::is_reportable().
{
     return test_info->is_reportable() && test_info->is_disabled_;
   }
static bool testing::TestCase::TestReportableDisabled (const TestInfo * test_info) inline static private
Definition at line 905 of file gtest.h.
References testing::TestInfo::is_disabled_, and testing::TestInfo::is_reportable().
{
     return test_info->is_reportable() && test_info->is_disabled_;
   }
int testing::TestCase::total_test_count () const
int testing::TestCase::total_test_count () const
Definition at line 2707 of file gtest.cc.
Referenced by testing::internal::UnitTestHelper::GetSortedTests(), testing::TestInfoTest::GetTestInfo(), testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PortableLocaltime(), testing::internal::PrettyUnitTestResultPrinter::PrintFailedTests(), Run(), testing::internal::ShouldRunTestCase(), testing::internal::TEST(), and testing::internal::UnitTestImpl::total_test_count().
{
   return static_cast<int>(test_info_list_.size());
 }
int testing::TestCase::total_test_count () const
const char* testing::TestCase::type_param () const inline
Definition at line 804 of file gtest.h.
Referenced by testing::internal::UnitTestHelper::GetSortedTests(), testing::internal::UnitTestImpl::ListTestsMatchingFilter(), testing::internal::PrettyUnitTestResultPrinter::OnTestCaseStart(), testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), testing::internal::PrintFullTestCommentIfPresent(), testing::internal::PrintOnOneLine(), and testing::internal::TEST().
{
     if (type_param_.get() != NULL)
       return type_param_->c_str();
     return NULL;
   }
const char* testing::TestCase::type_param () const inline
Definition at line 804 of file gtest.h.
{
     if (type_param_.get() != NULL)
       return type_param_->c_str();
     return NULL;
   }
const char* testing::TestCase::type_param () const inline
Definition at line 804 of file gtest.h.
{
     if (type_param_.get() != NULL)
       return type_param_->c_str();
     return NULL;
   }
void testing::TestCase::UnshuffleTests () private
Definition at line 2798 of file gtest.cc.
References i, and test_indices_.
{
   for (size_t i = 0; i < test_indices_.size(); i++) {
     test_indices_[i] = static_cast<int>(i);
   }
 }
void testing::TestCase::UnshuffleTests () private
void testing::TestCase::UnshuffleTests () private
Friends And Related Function Documentation
internal::UnitTestImpl friend
Definition at line 853 of file gtest.h.
Test friend
Definition at line 852 of file gtest.h.
Member Data Documentation
TestResult testing::TestCase::ad_hoc_test_result_ private
Definition at line 952 of file gtest.h.
Referenced by ClearResult(), and testing::internal::UnitTestImpl::RecordProperty().
TimeInMillis testing::TestCase::elapsed_time_ private
Definition at line 949 of file gtest.h.
Referenced by Run().
std::string testing::TestCase::name_ private
Definition at line 931 of file gtest.h.
Test::SetUpTestCaseFunc testing::TestCase::set_up_tc_ private
Definition at line 943 of file gtest.h.
bool testing::TestCase::should_run_ private
Definition at line 947 of file gtest.h.
Referenced by Run().
Test::TearDownTestCaseFunc testing::TestCase::tear_down_tc_ private
Definition at line 945 of file gtest.h.
std::vector< int > testing::TestCase::test_indices_ private
Definition at line 941 of file gtest.h.
Referenced by AddTestInfo(), GetMutableTestInfo(), GetTestInfo(), ShuffleTests(), and UnshuffleTests().
std::vector< TestInfo * > testing::TestCase::test_info_list_ private
Definition at line 937 of file gtest.h.
Referenced by AddTestInfo(), ClearResult(), GetMutableTestInfo(), GetTestInfo(), and ~TestCase().
const internal::scoped_ptr< const ::std::string > testing::TestCase::type_param_ private
Definition at line 934 of file gtest.h.
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/gtest.h
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest.cc