proxygen: testing::internal::PredicateFormatterFromMatcher< M > Class Template Reference
testing::internal::PredicateFormatterFromMatcher< M > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
PredicateFormatterFromMatcher (M m)
template<typename T >
AssertionResult operator() (const char *value_text, const T &x) const
PredicateFormatterFromMatcher (M m)
template<typename T >
AssertionResult operator() (const char *value_text, const T &x) const
PredicateFormatterFromMatcher (M m)
template<typename T >
AssertionResult operator() (const char *value_text, const T &x) const
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (PredicateFormatterFromMatcher)
GTEST_DISALLOW_ASSIGN_ (PredicateFormatterFromMatcher)
GTEST_DISALLOW_ASSIGN_ (PredicateFormatterFromMatcher)
Private Attributes
const M matcher_
Detailed Description
template<typename M>
class testing::internal::PredicateFormatterFromMatcher< M >
Definition at line 1834 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename M > testing::internal::PredicateFormatterFromMatcher< M >::PredicateFormatterFromMatcher (M m) inline explicit
Definition at line 1836 of file gmock-matchers.h.
 : matcher_(internal::move(m)) {}
template<typename M > testing::internal::PredicateFormatterFromMatcher< M >::PredicateFormatterFromMatcher (M m) inline explicit
Definition at line 1836 of file gmock-matchers.h.
 : matcher_(internal::move(m)) {}
template<typename M > testing::internal::PredicateFormatterFromMatcher< M >::PredicateFormatterFromMatcher (M m) inline explicit
Definition at line 1836 of file gmock-matchers.h.
 : matcher_(internal::move(m)) {}
Member Function Documentation
template<typename M > testing::internal::PredicateFormatterFromMatcher< M >::GTEST_DISALLOW_ASSIGN_ (PredicateFormatterFromMatcher< M >) private
template<typename M > testing::internal::PredicateFormatterFromMatcher< M >::GTEST_DISALLOW_ASSIGN_ (PredicateFormatterFromMatcher< M >) private
template<typename M > testing::internal::PredicateFormatterFromMatcher< M >::GTEST_DISALLOW_ASSIGN_ (PredicateFormatterFromMatcher< M >) private
template<typename M > template<typename T > AssertionResult testing::internal::PredicateFormatterFromMatcher< M >::operator() (const char * value_text, const T & x) const inline
Definition at line 1842 of file gmock-matchers.h.
References testing::AssertionFailure(), testing::AssertionSuccess(), testing::internal::MatcherBase< T >::DescribeTo(), and testing::internal::MatchPrintAndExplain().
{
     // We convert matcher_ to a Matcher<const T&> *now* instead of
     // when the PredicateFormatterFromMatcher object was constructed,
     // as matcher_ may be polymorphic (e.g. NotNull()) and we won't
     // know which type to instantiate it to until we actually see the
     // type of x here.
     //
     // We write SafeMatcherCast<const T&>(matcher_) instead of
     // Matcher<const T&>(matcher_), as the latter won't compile when
     // matcher_ has type Matcher<T> (e.g. An<int>()).
     // We don't write MatcherCast<const T&> either, as that allows
     // potentially unsafe downcasting of the matcher argument.
     const Matcher<const T&> matcher = SafeMatcherCast<const T&>(matcher_);
     StringMatchResultListener listener;
     if (MatchPrintAndExplain(x, matcher, &listener))
       return AssertionSuccess();
     ::std::stringstream ss;
     ss << "Value of: " << value_text << "\n"
        << "Expected: ";
     matcher.DescribeTo(&ss);
     ss << "\n  Actual: " << listener.str();
     return AssertionFailure() << ss.str();
   }
template<typename M > template<typename T > AssertionResult testing::internal::PredicateFormatterFromMatcher< M >::operator() (const char * value_text, const T & x) const inline
Definition at line 1842 of file gmock-matchers.h.
References testing::AssertionFailure(), testing::AssertionSuccess(), testing::internal::MatcherBase< T >::DescribeTo(), GTEST_DISALLOW_ASSIGN_, M, testing::internal::MakePredicateFormatterFromMatcher(), testing::internal::MatchPrintAndExplain(), and testing::internal::move().
{
     // We convert matcher_ to a Matcher<const T&> *now* instead of
     // when the PredicateFormatterFromMatcher object was constructed,
     // as matcher_ may be polymorphic (e.g. NotNull()) and we won't
     // know which type to instantiate it to until we actually see the
     // type of x here.
     //
     // We write SafeMatcherCast<const T&>(matcher_) instead of
     // Matcher<const T&>(matcher_), as the latter won't compile when
     // matcher_ has type Matcher<T> (e.g. An<int>()).
     // We don't write MatcherCast<const T&> either, as that allows
     // potentially unsafe downcasting of the matcher argument.
     const Matcher<const T&> matcher = SafeMatcherCast<const T&>(matcher_);
     StringMatchResultListener listener;
     if (MatchPrintAndExplain(x, matcher, &listener))
       return AssertionSuccess();
     ::std::stringstream ss;
     ss << "Value of: " << value_text << "\n"
        << "Expected: ";
     matcher.DescribeTo(&ss);
     ss << "\n  Actual: " << listener.str();
     return AssertionFailure() << ss.str();
   }
template<typename M > template<typename T > AssertionResult testing::internal::PredicateFormatterFromMatcher< M >::operator() (const char * value_text, const T & x) const inline
Definition at line 1842 of file gmock-matchers.h.
References testing::AssertionFailure(), testing::AssertionSuccess(), testing::internal::MatcherBase< T >::DescribeTo(), GTEST_DISALLOW_ASSIGN_, M, testing::internal::MakePredicateFormatterFromMatcher(), testing::internal::MatchPrintAndExplain(), and testing::internal::move().
{
     // We convert matcher_ to a Matcher<const T&> *now* instead of
     // when the PredicateFormatterFromMatcher object was constructed,
     // as matcher_ may be polymorphic (e.g. NotNull()) and we won't
     // know which type to instantiate it to until we actually see the
     // type of x here.
     //
     // We write SafeMatcherCast<const T&>(matcher_) instead of
     // Matcher<const T&>(matcher_), as the latter won't compile when
     // matcher_ has type Matcher<T> (e.g. An<int>()).
     // We don't write MatcherCast<const T&> either, as that allows
     // potentially unsafe downcasting of the matcher argument.
     const Matcher<const T&> matcher = SafeMatcherCast<const T&>(matcher_);
     StringMatchResultListener listener;
     if (MatchPrintAndExplain(x, matcher, &listener))
       return AssertionSuccess();
     ::std::stringstream ss;
     ss << "Value of: " << value_text << "\n"
        << "Expected: ";
     matcher.DescribeTo(&ss);
     ss << "\n  Actual: " << listener.str();
     return AssertionFailure() << ss.str();
   }
Member Data Documentation
template<typename M > const M testing::internal::PredicateFormatterFromMatcher< M >::matcher_ private
Definition at line 1868 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h