proxygen: testing::internal::ArgsMatcher< InnerMatcher, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 > Class Template Reference
testing::internal::ArgsMatcher< InnerMatcher, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 > Class Template Reference
#include <gmock-generated-matchers.h>
Public Member Functions
ArgsMatcher (const InnerMatcher &inner_matcher)
template<typename ArgsTuple >
operator Matcher< ArgsTuple > () const
ArgsMatcher (const InnerMatcher &inner_matcher)
template<typename ArgsTuple >
operator Matcher< ArgsTuple > () const
ArgsMatcher (const InnerMatcher &inner_matcher)
template<typename ArgsTuple >
operator Matcher< ArgsTuple > () const
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (ArgsMatcher)
GTEST_DISALLOW_ASSIGN_ (ArgsMatcher)
GTEST_DISALLOW_ASSIGN_ (ArgsMatcher)
Private Attributes
const InnerMatcher inner_matcher_
Detailed Description
template<class InnerMatcher, int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1>
class testing::internal::ArgsMatcher< InnerMatcher, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >
Definition at line 281 of file gmock-generated-matchers.h.
Constructor & Destructor Documentation
template<class InnerMatcher, int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> testing::internal::ArgsMatcher< InnerMatcher, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::ArgsMatcher (const InnerMatcher & inner_matcher) inline explicit
Definition at line 283 of file gmock-generated-matchers.h.
       : inner_matcher_(inner_matcher) {}
template<class InnerMatcher, int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> testing::internal::ArgsMatcher< InnerMatcher, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::ArgsMatcher (const InnerMatcher & inner_matcher) inline explicit
Definition at line 283 of file gmock-generated-matchers.h.
       : inner_matcher_(inner_matcher) {}
template<class InnerMatcher, int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> testing::internal::ArgsMatcher< InnerMatcher, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::ArgsMatcher (const InnerMatcher & inner_matcher) inline explicit
Definition at line 283 of file gmock-generated-matchers.h.
       : inner_matcher_(inner_matcher) {}
Member Function Documentation
template<class InnerMatcher, int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> testing::internal::ArgsMatcher< InnerMatcher, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::GTEST_DISALLOW_ASSIGN_ (ArgsMatcher< InnerMatcher, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >) private
template<class InnerMatcher, int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> testing::internal::ArgsMatcher< InnerMatcher, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::GTEST_DISALLOW_ASSIGN_ (ArgsMatcher< InnerMatcher, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >) private
template<class InnerMatcher, int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> testing::internal::ArgsMatcher< InnerMatcher, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::GTEST_DISALLOW_ASSIGN_ (ArgsMatcher< InnerMatcher, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >) private
template<class InnerMatcher, int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> template<typename ArgsTuple > testing::internal::ArgsMatcher< InnerMatcher, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::operator Matcher< ArgsTuple > () const inline
Definition at line 287 of file gmock-generated-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(new ArgsMatcherImpl<ArgsTuple, k0, k1, k2, k3, k4, k5,
         k6, k7, k8, k9>(inner_matcher_));
   }
template<class InnerMatcher, int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> template<typename ArgsTuple > testing::internal::ArgsMatcher< InnerMatcher, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::operator Matcher< ArgsTuple > () const inline
Definition at line 287 of file gmock-generated-matchers.h.
References GTEST_DISALLOW_ASSIGN_, and testing::MakeMatcher().
{
     return MakeMatcher(new ArgsMatcherImpl<ArgsTuple, k0, k1, k2, k3, k4, k5,
         k6, k7, k8, k9>(inner_matcher_));
   }
template<class InnerMatcher, int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> template<typename ArgsTuple > testing::internal::ArgsMatcher< InnerMatcher, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::operator Matcher< ArgsTuple > () const inline
Definition at line 287 of file gmock-generated-matchers.h.
References GTEST_DISALLOW_ASSIGN_, and testing::MakeMatcher().
{
     return MakeMatcher(new ArgsMatcherImpl<ArgsTuple, k0, k1, k2, k3, k4, k5,
         k6, k7, k8, k9>(inner_matcher_));
   }
Member Data Documentation
template<class InnerMatcher, int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> const InnerMatcher testing::internal::ArgsMatcher< InnerMatcher, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::inner_matcher_ private
Definition at line 293 of file gmock-generated-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-generated-matchers.h