proxygen: folly::LogConfig Class Reference
folly::LogConfig Class Reference
#include <LogConfig.h>
Public Types
using CategoryConfigMap = std::unordered_map< std::string, LogCategoryConfig >
using HandlerConfigMap = std::unordered_map< std::string, LogHandlerConfig >
Public Member Functions
LogConfig ()=default
LogConfig (HandlerConfigMap handlerConfigs, CategoryConfigMap catConfigs)
const CategoryConfigMap & getCategoryConfigs () const
const HandlerConfigMap & getHandlerConfigs () const
bool operator== (const LogConfig &other) const
bool operator!= (const LogConfig &other) const
void update (const LogConfig &other)
Private Attributes
HandlerConfigMap handlerConfigs_
CategoryConfigMap categoryConfigs_
Detailed Description
LogConfig contains configuration for the LoggerDB.
This includes information about the log levels for log categories, as well as what log handlers are configured and which categories they are attached to.
Definition at line 33 of file LogConfig.h.
Member Typedef Documentation
using folly::LogConfig::CategoryConfigMap = std::unordered_map<std::string, LogCategoryConfig>
Definition at line 35 of file LogConfig.h.
using folly::LogConfig::HandlerConfigMap = std::unordered_map<std::string, LogHandlerConfig>
Definition at line 36 of file LogConfig.h.
Constructor & Destructor Documentation
folly::LogConfig::LogConfig () default
folly::LogConfig::LogConfig (HandlerConfigMap handlerConfigs, CategoryConfigMap catConfigs) inline explicit
Definition at line 39 of file LogConfig.h.
References categoryConfigs_, and folly::gen::move.
       : handlerConfigs_{std::move(handlerConfigs)},
         categoryConfigs_{std::move(catConfigs)} {}
Member Function Documentation
const CategoryConfigMap& folly::LogConfig::getCategoryConfigs () const inline
Definition at line 45 of file LogConfig.h.
References categoryConfigs_.
Referenced by folly::logConfigToDynamic(), folly::operator<<(), folly::LoggerDB::resetConfig(), folly::LoggerDB::startConfigUpdate(), and folly::LoggerDB::updateConfig().
{
     return categoryConfigs_;
   }
const HandlerConfigMap& folly::LogConfig::getHandlerConfigs () const inline
Definition at line 48 of file LogConfig.h.
References handlerConfigs_, operator!=(), operator==(), and update().
Referenced by folly::logConfigToDynamic(), folly::operator<<(), and folly::LoggerDB::startConfigUpdate().
{
     return handlerConfigs_;
   }
bool folly::LogConfig::operator!= (const LogConfig & other) const
Definition at line 27 of file LogConfig.cpp.
Referenced by getHandlerConfigs().
{
   return !(*this == other);
 }
bool folly::LogConfig::operator== (const LogConfig & other) const
Definition at line 22 of file LogConfig.cpp.
References categoryConfigs_, and handlerConfigs_.
Referenced by getHandlerConfigs().
{
   return handlerConfigs_ == other.handlerConfigs_ &&
       categoryConfigs_ == other.categoryConfigs_;
 }
void folly::LogConfig::update (const LogConfig & other)
Update this LogConfig object by merging in settings from another LogConfig.
All LogHandler settings from the other LogConfig will be inserted into this LogConfig. If a log handler with the same name was already defined in this LogConfig it will be replaced with the new settings.
All LogCategory settings from the other LogConfig will be inserted into this LogConfig. If a log category with the same name was already defined in this LogConfig, its settings will be updated with settings from the other LogConfig. However, if the other LogConfig does not define handler settings for the category it will retain its current handler settings.
This method allows LogConfig objects to be combined before applying them. Using LogConfig::update() will produce the same results as if LoggerDB::updateConfig() had been called with both configs sequentially. In other words, this operation:
configA.update(configB); loggerDB.updateConfig(configA);
will produce the same results as:
loggerDB.updateConfig(configA); loggerDB.updateConfig(configA);
Definition at line 31 of file LogConfig.cpp.
References categoryConfigs_, handlerConfigs_, and folly::gen::move.
Referenced by getHandlerConfigs(), and folly::initLogging().
{
   // Update handlerConfigs_ with all of the entries from the other LogConfig.
   // Any entries already present in our handlerConfigs_ are replaced wholesale.
   for (const auto& entry : other.handlerConfigs_) {
     if (entry.second.type.hasValue()) {
       // This is a complete LogHandlerConfig that should be inserted
       // or completely replace an existing handler config with this name.
       auto result = handlerConfigs_.insert(entry);
       if (!result.second) {
         result.first->second = entry.second;
       }
     } else {
       // This config is updating an existing LogHandlerConfig rather than
       // completely replacing it.
       auto iter = handlerConfigs_.find(entry.first);
       if (iter == handlerConfigs_.end()) {
         throw std::invalid_argument(to<std::string>(
             "cannot update configuration for unknown log handler \"",
             entry.first,
             "\""));
       }
       iter->second.update(entry.second);
     }
   }
   // Update categoryConfigs_ with all of the entries from the other LogConfig.
   //
   // Any entries already present in our categoryConfigs_ are merged: if the new
   // configuration does not include handler settings our entry's settings are
   // maintained.
   for (const auto& entry : other.categoryConfigs_) {
     auto result = categoryConfigs_.insert(entry);
     if (!result.second) {
       auto* existingEntry = &result.first->second;
       auto oldHandlers = std::move(existingEntry->handlers);
       *existingEntry = entry.second;
       if (!existingEntry->handlers.hasValue()) {
         existingEntry->handlers = std::move(oldHandlers);
       }
     }
   }
 }
Member Data Documentation
CategoryConfigMap folly::LogConfig::categoryConfigs_ private
Definition at line 86 of file LogConfig.h.
Referenced by getCategoryConfigs(), LogConfig(), operator==(), and update().
HandlerConfigMap folly::LogConfig::handlerConfigs_ private
Definition at line 85 of file LogConfig.h.
Referenced by getHandlerConfigs(), operator==(), and update().
The documentation for this class was generated from the following files:
proxygen/folly/folly/logging/LogConfig.h
proxygen/folly/folly/logging/LogConfig.cpp