proxygen: folly::UnboundedBlockingQueue< T > Class Template Reference
folly::UnboundedBlockingQueue< T > Class Template Reference
#include <UnboundedBlockingQueue.h>
Public Member Functions
virtual ~UnboundedBlockingQueue ()
BlockingQueueAddResult add (T item) override
T take () override
folly::Optional< T > try_take_for (std::chrono::milliseconds time) override
size_t size () override
Public Member Functions inherited from folly::BlockingQueue< T >
virtual ~BlockingQueue ()=default
virtual BlockingQueueAddResult addWithPriority (T item, int8_t)
virtual uint8_t getNumPriorities ()
Private Attributes
LifoSem sem_
UMPMCQueue< T, false, 6 > queue_
Detailed Description
template<class T>
class folly::UnboundedBlockingQueue< T >
Definition at line 26 of file UnboundedBlockingQueue.h.
Constructor & Destructor Documentation
template<class T> virtual folly::UnboundedBlockingQueue< T >::~UnboundedBlockingQueue () inline virtual
Definition at line 28 of file UnboundedBlockingQueue.h.
 {}
Member Function Documentation
template<class T> BlockingQueueAddResult folly::UnboundedBlockingQueue< T >::add (T item) inline override virtual
Implements folly::BlockingQueue< T >.
Definition at line 30 of file UnboundedBlockingQueue.h.
References folly::gen::move, folly::detail::LifoSemBase< Handoff, Atom >::post(), folly::UnboundedBlockingQueue< T >::queue_, and folly::UnboundedBlockingQueue< T >::sem_.
Referenced by TEST().
{
     queue_.enqueue(std::move(item));
     return sem_.post();
   }
template<class T> size_t folly::UnboundedBlockingQueue< T >::size () inline override virtual
Implements folly::BlockingQueue< T >.
Definition at line 53 of file UnboundedBlockingQueue.h.
References folly::UnboundedBlockingQueue< T >::queue_.
Referenced by TEST().
{
     return queue_.size();
   }
template<class T> T folly::UnboundedBlockingQueue< T >::take () inline override virtual
Implements folly::BlockingQueue< T >.
Definition at line 35 of file UnboundedBlockingQueue.h.
References folly::UnboundedBlockingQueue< T >::queue_, folly::UnboundedBlockingQueue< T >::sem_, folly::T, and folly::detail::LifoSemBase< Handoff, Atom >::wait().
Referenced by TEST().
                     {
     T item;
     while (!queue_.try_dequeue(item)) {
       sem_.wait();
     }
     return item;
   }
template<class T> folly::Optional<T> folly::UnboundedBlockingQueue< T >::try_take_for (std::chrono::milliseconds time) inline override virtual
Implements folly::BlockingQueue< T >.
Definition at line 43 of file UnboundedBlockingQueue.h.
References folly::gen::move, folly::none, folly::UnboundedBlockingQueue< T >::queue_, folly::UnboundedBlockingQueue< T >::sem_, folly::T, and folly::detail::LifoSemBase< Handoff, Atom >::try_wait_for().
{
     T item;
     while (!queue_.try_dequeue(item)) {
       if (!sem_.try_wait_for(time)) {
         return folly::none;
       }
     }
     return std::move(item);
   }
Member Data Documentation
template<class T> UMPMCQueue<T, false, 6> folly::UnboundedBlockingQueue< T >::queue_ private
Definition at line 59 of file UnboundedBlockingQueue.h.
Referenced by folly::UnboundedBlockingQueue< T >::add(), folly::UnboundedBlockingQueue< T >::size(), folly::UnboundedBlockingQueue< T >::take(), and folly::UnboundedBlockingQueue< T >::try_take_for().
template<class T> LifoSem folly::UnboundedBlockingQueue< T >::sem_ private
Definition at line 58 of file UnboundedBlockingQueue.h.
Referenced by folly::UnboundedBlockingQueue< T >::add(), folly::UnboundedBlockingQueue< T >::take(), and folly::UnboundedBlockingQueue< T >::try_take_for().
The documentation for this class was generated from the following file:
proxygen/folly/folly/executors/task_queue/UnboundedBlockingQueue.h