proxygen: folly::observer_detail::ObserverManager::DependencyRecorder Class Reference
folly::observer_detail::ObserverManager::DependencyRecorder Class Reference
#include <ObserverManager.h>
Classes
struct Dependencies
Public Types
using DependencySet = std::unordered_set< Core::Ptr >
Public Member Functions
DependencyRecorder (const Core &core)
DependencySet release ()
~DependencyRecorder ()
Static Public Member Functions
static void markDependency (Core::Ptr dependency)
static void markRefreshDependency (const Core &core)
static void unmarkRefreshDependency (const Core &core)
Private Attributes
Dependencies dependencies_
Dependencies * previousDepedencies_
Static Private Attributes
static FOLLY_TLS Dependencies * currentDependencies_ {nullptr}
Detailed Description
Definition at line 137 of file ObserverManager.h.
Member Typedef Documentation
using folly::observer_detail::ObserverManager::DependencyRecorder::DependencySet = std::unordered_set<Core::Ptr>
Definition at line 139 of file ObserverManager.h.
Constructor & Destructor Documentation
folly::observer_detail::ObserverManager::DependencyRecorder::DependencyRecorder (const Core & core) inline explicit
Definition at line 147 of file ObserverManager.h.
References currentDependencies_, dependencies_, folly::observer_detail::ObserverManager::inManagerThread(), and previousDepedencies_.
                                                   : dependencies_(core) {
       DCHECK(inManagerThread());
       previousDepedencies_ = currentDependencies_;
       currentDependencies_ = &dependencies_;
     }
folly::observer_detail::ObserverManager::DependencyRecorder::~DependencyRecorder () inline
Definition at line 197 of file ObserverManager.h.
References currentDependencies_, dependencies_, and release().
{
       if (currentDependencies_ == &dependencies_) {
         release();
       }
     }
Member Function Documentation
static void folly::observer_detail::ObserverManager::DependencyRecorder::markDependency (Core::Ptr dependency) inline static
Definition at line 154 of file ObserverManager.h.
References currentDependencies_, folly::observer_detail::ObserverManager::DependencyRecorder::Dependencies::dependencies, folly::observer_detail::ObserverManager::inManagerThread(), and folly::gen::move.
Referenced by folly::observer_detail::Core::getData().
{
       DCHECK(inManagerThread());
       DCHECK(currentDependencies_);
       currentDependencies_->dependencies.insert(std::move(dependency));
     }
static void folly::observer_detail::ObserverManager::DependencyRecorder::markRefreshDependency (const Core & core) inline static
Definition at line 161 of file ObserverManager.h.
References folly::observer_detail::GraphCycleDetector< NodeId >::addEdge(), folly::observer_detail::ObserverManager::DependencyRecorder::Dependencies::core, currentDependencies_, and folly::observer_detail::ObserverManager::getInstance().
Referenced by folly::observer_detail::Core::refresh().
{
       if (!currentDependencies_) {
         return;
       }
       if (auto instance = getInstance()) {
         instance->cycleDetector_.withLock([&](CycleDetector& cycleDetector) {
           bool hasCycle =
               !cycleDetector.addEdge(&currentDependencies_->core, &core);
           if (hasCycle) {
             throw std::logic_error("Observer cycle detected.");
           }
         });
       }
     }
DependencySet folly::observer_detail::ObserverManager::DependencyRecorder::release () inline
Definition at line 189 of file ObserverManager.h.
References currentDependencies_, folly::observer_detail::ObserverManager::DependencyRecorder::Dependencies::dependencies, dependencies_, folly::gen::move, previousDepedencies_, and folly::f14::swap().
Referenced by folly::observer_detail::Core::refresh(), and ~DependencyRecorder().
{
       DCHECK(currentDependencies_ == &dependencies_);
       std::swap(currentDependencies_, previousDepedencies_);
       previousDepedencies_ = nullptr;
       return std::move(dependencies_.dependencies);
     }
static void folly::observer_detail::ObserverManager::DependencyRecorder::unmarkRefreshDependency (const Core & core) inline static
Definition at line 177 of file ObserverManager.h.
References folly::observer_detail::ObserverManager::DependencyRecorder::Dependencies::core, currentDependencies_, folly::observer_detail::ObserverManager::getInstance(), and folly::observer_detail::GraphCycleDetector< NodeId >::removeEdge().
Referenced by folly::observer_detail::Core::refresh().
{
       if (!currentDependencies_) {
         return;
       }
       if (auto instance = getInstance()) {
         instance->cycleDetector_.withLock([&](CycleDetector& cycleDetector) {
           cycleDetector.removeEdge(&currentDependencies_->core, &core);
         });
       }
     }
Member Data Documentation
FOLLY_TLS ObserverManager::DependencyRecorder::Dependencies * folly::observer_detail::ObserverManager::DependencyRecorder::currentDependencies_ {nullptr} static private
Definition at line 207 of file ObserverManager.h.
Referenced by DependencyRecorder(), markDependency(), markRefreshDependency(), release(), unmarkRefreshDependency(), and ~DependencyRecorder().
Dependencies folly::observer_detail::ObserverManager::DependencyRecorder::dependencies_ private
Definition at line 204 of file ObserverManager.h.
Referenced by DependencyRecorder(), release(), and ~DependencyRecorder().
Dependencies* folly::observer_detail::ObserverManager::DependencyRecorder::previousDepedencies_ private
Definition at line 205 of file ObserverManager.h.
Referenced by DependencyRecorder(), and release().
The documentation for this class was generated from the following files:
proxygen/folly/folly/experimental/observer/detail/ObserverManager.h
proxygen/folly/folly/experimental/observer/detail/ObserverManager.cpp