proxygen: TestData Class Reference
TestData Class Reference
Public Member Functions
TestData (int data)
~TestData () override
bool hasCallback () override
TestData (int data)
~TestData () override
bool hasCallback () override
TestData (int gso, bool useSocketGSO, int *in, size_t inLen, int *expected, size_t expectedLen)
bool checkIn () const
bool checkOut () const
bool appendOut (int num)
std::unique_ptr< folly::IOBuf > getInBuf ()
TestData (int data)
~TestData () override
bool hasCallback () override
void onSet () override
void onUnset () override
Public Member Functions inherited from folly::RequestData
virtual ~RequestData ()=default
Public Attributes
int data_
int gso_ {0}
bool useSocketGSO_ {false}
std::vector< int > in_
std::vector< int > expected_
int expectedSize_
std::vector< int > out_
int outSize_ {0}
int set_ = 0
int unset_ = 0
Detailed Description
Definition at line 547 of file ThreadPoolExecutorTest.cpp.
Constructor & Destructor Documentation
TestData::TestData (int data) inline explicit
Definition at line 549 of file ThreadPoolExecutorTest.cpp.
 : data_(data) {}
TestData::~TestData () inline override
Definition at line 550 of file ThreadPoolExecutorTest.cpp.
 {}
TestData::TestData (int data) inline explicit
Definition at line 26 of file ContextTest.cpp.
 : data_(data) {}
TestData::~TestData () inline override
Definition at line 27 of file ContextTest.cpp.
 {}
TestData::TestData (int gso, bool useSocketGSO, int * in, size_t inLen, int * expected, size_t expectedLen) inline
Definition at line 39 of file AsyncUDPSocketGSOTest.cpp.
References folly::f14::accumulate(), and in_.
       : gso_(gso), useSocketGSO_(useSocketGSO) {
     in_.assign(in, in + inLen);
     expected_.assign(expected, expected + expectedLen);
     expectedSize_ = std::accumulate(expected_.begin(), expected_.end(), 0);
   }
TestData::TestData (int data) inline explicit
Definition at line 30 of file RequestContextTest.cpp.
 : data_(data) {}
TestData::~TestData () inline override
Definition at line 31 of file RequestContextTest.cpp.
 {}
Member Function Documentation
bool TestData::appendOut (int num) inline
Definition at line 61 of file AsyncUDPSocketGSOTest.cpp.
References out_.
{
     out_.push_back(num);
     outSize_ += num;
     return (outSize_ >= expectedSize_);
   }
bool TestData::checkIn () const inline
Definition at line 53 of file AsyncUDPSocketGSOTest.cpp.
References folly::f14::accumulate(), and in_.
{
     return (expectedSize_ == std::accumulate(in_.begin(), in_.end(), 0));
   }
bool TestData::checkOut () const inline
Definition at line 57 of file AsyncUDPSocketGSOTest.cpp.
References folly::f14::accumulate(), and out_.
{
     return (expectedSize_ == std::accumulate(out_.begin(), out_.end(), 0));
   }
std::unique_ptr<folly::IOBuf> TestData::getInBuf () inline
Definition at line 68 of file AsyncUDPSocketGSOTest.cpp.
References folly::IOBuf::copyBuffer(), i, in_, folly::IOBuf::prependChain(), and string.
{
     if (!in_.size()) {
       return nullptr;
     }
     std::string str(in_[0], 'A');
     std::unique_ptr<folly::IOBuf> ret =
         folly::IOBuf::copyBuffer(str.data(), str.size());
     for (size_t i = 1; i < in_.size(); i++) {
       str = std::string(in_[i], 'A');
       ret->prependChain(folly::IOBuf::copyBuffer(str.data(), str.size()));
     }
     return ret;
   }
bool TestData::hasCallback () inline override virtual
Implements folly::RequestData.
Definition at line 29 of file ContextTest.cpp.
References data_.
{
     return false;
   }
bool TestData::hasCallback () inline override virtual
Implements folly::RequestData.
Definition at line 33 of file RequestContextTest.cpp.
{
     return true;
   }
bool TestData::hasCallback () inline override virtual
Implements folly::RequestData.
Definition at line 552 of file ThreadPoolExecutorTest.cpp.
{
     return false;
   }
void TestData::onSet () inline override virtual
Reimplemented from folly::RequestData.
Definition at line 37 of file RequestContextTest.cpp.
{
     set_++;
   }
void TestData::onUnset () inline override virtual
Reimplemented from folly::RequestData.
Definition at line 41 of file RequestContextTest.cpp.
{
     unset_++;
   }
Member Data Documentation
int TestData::data_
Definition at line 556 of file ThreadPoolExecutorTest.cpp.
std::vector<int> TestData::expected_
Definition at line 88 of file AsyncUDPSocketGSOTest.cpp.
int TestData::expectedSize_
Definition at line 89 of file AsyncUDPSocketGSOTest.cpp.
int TestData::gso_ {0}
Definition at line 85 of file AsyncUDPSocketGSOTest.cpp.
std::vector<int> TestData::in_
Definition at line 87 of file AsyncUDPSocketGSOTest.cpp.
std::vector<int> TestData::out_
Definition at line 90 of file AsyncUDPSocketGSOTest.cpp.
int TestData::outSize_ {0}
Definition at line 91 of file AsyncUDPSocketGSOTest.cpp.
int TestData::set_ = 0
Definition at line 45 of file RequestContextTest.cpp.
int TestData::unset_ = 0
Definition at line 45 of file RequestContextTest.cpp.
bool TestData::useSocketGSO_ {false}
Definition at line 86 of file AsyncUDPSocketGSOTest.cpp.
The documentation for this class was generated from the following files:
proxygen/folly/folly/executors/test/ThreadPoolExecutorTest.cpp
proxygen/folly/folly/futures/test/ContextTest.cpp
proxygen/folly/folly/io/async/test/AsyncUDPSocketGSOTest.cpp
proxygen/folly/folly/io/async/test/RequestContextTest.cpp