proxygen: testing::TestEventListener Class Reference
testing::TestEventListener Class Reference abstract
#include <gtest.h>
Public Member Functions
virtual ~TestEventListener ()
virtual void OnTestProgramStart (const UnitTest &unit_test)=0
virtual void OnTestIterationStart (const UnitTest &unit_test, int iteration)=0
virtual void OnEnvironmentsSetUpStart (const UnitTest &unit_test)=0
virtual void OnEnvironmentsSetUpEnd (const UnitTest &unit_test)=0
virtual void OnTestCaseStart (const TestCase &test_case)=0
virtual void OnTestStart (const TestInfo &test_info)=0
virtual void OnTestPartResult (const TestPartResult &test_part_result)=0
virtual void OnTestEnd (const TestInfo &test_info)=0
virtual void OnTestCaseEnd (const TestCase &test_case)=0
virtual void OnEnvironmentsTearDownStart (const UnitTest &unit_test)=0
virtual void OnEnvironmentsTearDownEnd (const UnitTest &unit_test)=0
virtual void OnTestIterationEnd (const UnitTest &unit_test, int iteration)=0
virtual void OnTestProgramEnd (const UnitTest &unit_test)=0
virtual ~TestEventListener ()
virtual void OnTestProgramStart (const UnitTest &unit_test)=0
virtual void OnTestIterationStart (const UnitTest &unit_test, int iteration)=0
virtual void OnEnvironmentsSetUpStart (const UnitTest &unit_test)=0
virtual void OnEnvironmentsSetUpEnd (const UnitTest &unit_test)=0
virtual void OnTestCaseStart (const TestCase &test_case)=0
virtual void OnTestStart (const TestInfo &test_info)=0
virtual void OnTestPartResult (const TestPartResult &test_part_result)=0
virtual void OnTestEnd (const TestInfo &test_info)=0
virtual void OnTestCaseEnd (const TestCase &test_case)=0
virtual void OnEnvironmentsTearDownStart (const UnitTest &unit_test)=0
virtual void OnEnvironmentsTearDownEnd (const UnitTest &unit_test)=0
virtual void OnTestIterationEnd (const UnitTest &unit_test, int iteration)=0
virtual void OnTestProgramEnd (const UnitTest &unit_test)=0
virtual ~TestEventListener ()
virtual void OnTestProgramStart (const UnitTest &unit_test)=0
virtual void OnTestIterationStart (const UnitTest &unit_test, int iteration)=0
virtual void OnEnvironmentsSetUpStart (const UnitTest &unit_test)=0
virtual void OnEnvironmentsSetUpEnd (const UnitTest &unit_test)=0
virtual void OnTestCaseStart (const TestCase &test_case)=0
virtual void OnTestStart (const TestInfo &test_info)=0
virtual void OnTestPartResult (const TestPartResult &test_part_result)=0
virtual void OnTestEnd (const TestInfo &test_info)=0
virtual void OnTestCaseEnd (const TestCase &test_case)=0
virtual void OnEnvironmentsTearDownStart (const UnitTest &unit_test)=0
virtual void OnEnvironmentsTearDownEnd (const UnitTest &unit_test)=0
virtual void OnTestIterationEnd (const UnitTest &unit_test, int iteration)=0
virtual void OnTestProgramEnd (const UnitTest &unit_test)=0
Detailed Description
Definition at line 991 of file gtest.h.
Constructor & Destructor Documentation
virtual testing::TestEventListener::~TestEventListener () inline virtual
Definition at line 993 of file gtest.h.
 {}
virtual testing::TestEventListener::~TestEventListener () inline virtual
Definition at line 993 of file gtest.h.
 {}
virtual testing::TestEventListener::~TestEventListener () inline virtual
Definition at line 993 of file gtest.h.
 {}
Member Function Documentation
virtual void testing::TestEventListener::OnEnvironmentsSetUpEnd (const UnitTest & unit_test) pure virtual
Implemented in testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
Referenced by testing::internal::UnitTestImpl::RunAllTests(), and testing::internal::TearDownEnvironment().
virtual void testing::TestEventListener::OnEnvironmentsSetUpEnd (const UnitTest & unit_test) pure virtual
Implemented in testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
virtual void testing::TestEventListener::OnEnvironmentsSetUpEnd (const UnitTest & unit_test) pure virtual
Implemented in testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
virtual void testing::TestEventListener::OnEnvironmentsSetUpStart (const UnitTest & unit_test) pure virtual
Implemented in testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
Referenced by testing::internal::UnitTestImpl::RunAllTests(), and testing::internal::TearDownEnvironment().
virtual void testing::TestEventListener::OnEnvironmentsSetUpStart (const UnitTest & unit_test) pure virtual
Implemented in testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
virtual void testing::TestEventListener::OnEnvironmentsSetUpStart (const UnitTest & unit_test) pure virtual
Implemented in testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
virtual void testing::TestEventListener::OnEnvironmentsTearDownEnd (const UnitTest & unit_test) pure virtual
Implemented in testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
virtual void testing::TestEventListener::OnEnvironmentsTearDownEnd (const UnitTest & unit_test) pure virtual
Implemented in testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
Referenced by testing::internal::UnitTestImpl::RunAllTests(), and testing::internal::TearDownEnvironment().
virtual void testing::TestEventListener::OnEnvironmentsTearDownEnd (const UnitTest & unit_test) pure virtual
Implemented in testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
virtual void testing::TestEventListener::OnEnvironmentsTearDownStart (const UnitTest & unit_test) pure virtual
Implemented in testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
virtual void testing::TestEventListener::OnEnvironmentsTearDownStart (const UnitTest & unit_test) pure virtual
Implemented in testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
Referenced by testing::internal::UnitTestImpl::RunAllTests(), and testing::internal::TearDownEnvironment().
virtual void testing::TestEventListener::OnEnvironmentsTearDownStart (const UnitTest & unit_test) pure virtual
Implemented in testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
virtual void testing::TestEventListener::OnTestCaseEnd (const TestCase & test_case) pure virtual
Implemented in testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
Referenced by testing::TestCase::Run().
virtual void testing::TestEventListener::OnTestCaseEnd (const TestCase & test_case) pure virtual
Implemented in testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
virtual void testing::TestEventListener::OnTestCaseEnd (const TestCase & test_case) pure virtual
Implemented in testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
virtual void testing::TestEventListener::OnTestCaseStart (const TestCase & test_case) pure virtual
Implemented in testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
virtual void testing::TestEventListener::OnTestCaseStart (const TestCase & test_case) pure virtual
Implemented in testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
Referenced by testing::TestCase::Run().
virtual void testing::TestEventListener::OnTestCaseStart (const TestCase & test_case) pure virtual
Implemented in testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
virtual void testing::TestEventListener::OnTestEnd (const TestInfo & test_info) pure virtual
Implemented in testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
Referenced by testing::TestInfo::Run().
virtual void testing::TestEventListener::OnTestEnd (const TestInfo & test_info) pure virtual
Implemented in testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
virtual void testing::TestEventListener::OnTestEnd (const TestInfo & test_info) pure virtual
Implemented in testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
virtual void testing::TestEventListener::OnTestIterationEnd (const UnitTest & unit_test, int iteration) pure virtual
Implemented in SequenceTestingListener, SequenceTestingListener, SequenceTestingListener, testing::internal::XmlUnitTestResultPrinter, testing::internal::XmlUnitTestResultPrinter, testing::internal::XmlUnitTestResultPrinter, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
virtual void testing::TestEventListener::OnTestIterationEnd (const UnitTest & unit_test, int iteration) pure virtual
Implemented in SequenceTestingListener, SequenceTestingListener, SequenceTestingListener, testing::internal::XmlUnitTestResultPrinter, testing::internal::XmlUnitTestResultPrinter, testing::internal::XmlUnitTestResultPrinter, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
Referenced by testing::internal::UnitTestImpl::RunAllTests(), testing::internal::TearDownEnvironment(), and TEST().
virtual void testing::TestEventListener::OnTestIterationEnd (const UnitTest & unit_test, int iteration) pure virtual
Implemented in SequenceTestingListener, SequenceTestingListener, SequenceTestingListener, testing::internal::XmlUnitTestResultPrinter, testing::internal::XmlUnitTestResultPrinter, testing::internal::XmlUnitTestResultPrinter, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
virtual void testing::TestEventListener::OnTestIterationStart (const UnitTest & unit_test, int iteration) pure virtual
Implemented in SequenceTestingListener, SequenceTestingListener, SequenceTestingListener, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
Referenced by testing::internal::UnitTestImpl::RunAllTests(), testing::internal::TearDownEnvironment(), and TEST().
virtual void testing::TestEventListener::OnTestIterationStart (const UnitTest & unit_test, int iteration) pure virtual
Implemented in SequenceTestingListener, SequenceTestingListener, SequenceTestingListener, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
virtual void testing::TestEventListener::OnTestIterationStart (const UnitTest & unit_test, int iteration) pure virtual
Implemented in SequenceTestingListener, SequenceTestingListener, SequenceTestingListener, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
virtual void testing::TestEventListener::OnTestPartResult (const TestPartResult & test_part_result) pure virtual
Implemented in testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
virtual void testing::TestEventListener::OnTestPartResult (const TestPartResult & test_part_result) pure virtual
Implemented in testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
virtual void testing::TestEventListener::OnTestPartResult (const TestPartResult & test_part_result) pure virtual
Implemented in testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
Referenced by testing::internal::DefaultGlobalTestPartResultReporter::ReportTestPartResult().
virtual void testing::TestEventListener::OnTestProgramEnd (const UnitTest & unit_test) pure virtual
Implemented in SequenceTestingListener, SequenceTestingListener, SequenceTestingListener, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
virtual void testing::TestEventListener::OnTestProgramEnd (const UnitTest & unit_test) pure virtual
Implemented in SequenceTestingListener, SequenceTestingListener, SequenceTestingListener, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
Referenced by testing::internal::UnitTestImpl::RunAllTests(), testing::internal::TearDownEnvironment(), and TEST().
virtual void testing::TestEventListener::OnTestProgramEnd (const UnitTest & unit_test) pure virtual
Implemented in SequenceTestingListener, SequenceTestingListener, SequenceTestingListener, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
virtual void testing::TestEventListener::OnTestProgramStart (const UnitTest & unit_test) pure virtual
Implemented in SequenceTestingListener, SequenceTestingListener, SequenceTestingListener, TestListener, TestListener, TestListener, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
virtual void testing::TestEventListener::OnTestProgramStart (const UnitTest & unit_test) pure virtual
Implemented in SequenceTestingListener, SequenceTestingListener, SequenceTestingListener, TestListener, TestListener, TestListener, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
virtual void testing::TestEventListener::OnTestProgramStart (const UnitTest & unit_test) pure virtual
Implemented in SequenceTestingListener, SequenceTestingListener, SequenceTestingListener, TestListener, TestListener, TestListener, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
Referenced by testing::internal::UnitTestImpl::RunAllTests(), testing::internal::TearDownEnvironment(), and TEST().
virtual void testing::TestEventListener::OnTestStart (const TestInfo & test_info) pure virtual
Implemented in testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
virtual void testing::TestEventListener::OnTestStart (const TestInfo & test_info) pure virtual
Implemented in testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
Referenced by testing::TestInfo::Run().
virtual void testing::TestEventListener::OnTestStart (const TestInfo & test_info) pure virtual
Implemented in testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::TestEventRepeater, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::internal::PrettyUnitTestResultPrinter, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::EmptyTestEventListener, testing::internal::EventRecordingListener, testing::internal::EventRecordingListener, and testing::internal::EventRecordingListener.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/gtest.h