proxygen: fizz::test::ExtensionsTest Class Reference
fizz::test::ExtensionsTest Class Reference
#include <ExtensionTestsBase.h>
Protected Member Functions
Buf getBuf (folly::StringPiece hex)
std::vector< Extension > getExtensions (folly::StringPiece hex)
template<class T >
void checkEncode (T &&ext, folly::StringPiece expectedHex)
Protected Member Functions inherited from testing::Test
Test ()
virtual void SetUp ()
virtual void TearDown ()
Test ()
virtual void SetUp ()
virtual void TearDown ()
Test ()
virtual void SetUp ()
virtual void TearDown ()
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Detailed Description
Definition at line 20 of file ExtensionTestsBase.h.
Member Function Documentation
template<class T > void fizz::test::ExtensionsTest::checkEncode (T && ext, folly::StringPiece expectedHex) inline protected
Definition at line 39 of file ExtensionTestsBase.h.
References folly::IOBuf::create(), fizz::encodeExtension(), EXPECT_TRUE, getBuf(), and fizz::detail::write().
{
     auto encoded = encodeExtension(std::forward<T>(ext));
     auto buf = folly::IOBuf::create(0);
     folly::io::Appender appender(buf.get(), 10);
     detail::write(encoded, appender);
     EXPECT_TRUE(folly::IOBufEqualTo()(buf, getBuf(expectedHex)));
   }
Buf fizz::test::ExtensionsTest::getBuf (folly::StringPiece hex) inline protected
Definition at line 22 of file ExtensionTestsBase.h.
References folly::IOBuf::copyBuffer(), data, and folly::unhexlify().
Referenced by checkEncode(), and getExtensions().
{
     auto data = unhexlify(hex);
     return folly::IOBuf::copyBuffer(data.data(), data.size());
   }
std::vector<Extension> fizz::test::ExtensionsTest::getExtensions (folly::StringPiece hex) inline protected
Definition at line 27 of file ExtensionTestsBase.h.
References EXPECT_EQ, EXPECT_TRUE, getBuf(), folly::gen::move, and fizz::detail::read().
{
     auto buf = ExtensionsTest::getBuf(hex);
     folly::io::Cursor cursor(buf.get());
     Extension ext;
     EXPECT_EQ(detail::read(ext, cursor), buf->computeChainDataLength());
     EXPECT_TRUE(cursor.isAtEnd());
     std::vector<Extension> exts;
     exts.push_back(std::move(ext));
     return exts;
   }
The documentation for this class was generated from the following file:
proxygen/fizz/fizz/record/test/ExtensionTestsBase.h