proxygen: folly::io::test::CompressionCorruptionTest Class Reference
folly::io::test::CompressionCorruptionTest Class Reference
Protected Member Functions
void SetUp () override
void runSimpleTest (const DataHolder &dh)
Protected Attributes
std::unique_ptr< Codec > codec_
Detailed Description
Definition at line 381 of file CompressionTest.cpp.
Member Function Documentation
void folly::io::test::CompressionCorruptionTest::runSimpleTest (const DataHolder & dh) protected
Definition at line 392 of file CompressionTest.cpp.
References codec_, folly::io::test::DataHolder::data(), EXPECT_EQ, EXPECT_THROW, folly::io::test::DataHolder::hash(), folly::io::test::hashIOBuf(), uint64_t, and folly::IOBuf::wrapBuffer().
{
   constexpr uint64_t uncompressedLength = 42;
   auto original = IOBuf::wrapBuffer(dh.data(uncompressedLength));
   auto compressed = codec_->compress(original.get());
   if (!codec_->needsUncompressedLength()) {
     auto uncompressed = codec_->uncompress(compressed.get());
     EXPECT_EQ(uncompressedLength, uncompressed->computeChainDataLength());
     EXPECT_EQ(dh.hash(uncompressedLength), hashIOBuf(uncompressed.get()));
   }
   {
     auto uncompressed =
         codec_->uncompress(compressed.get(), uncompressedLength);
     EXPECT_EQ(uncompressedLength, uncompressed->computeChainDataLength());
     EXPECT_EQ(dh.hash(uncompressedLength), hashIOBuf(uncompressed.get()));
   }
   EXPECT_THROW(
       codec_->uncompress(compressed.get(), uncompressedLength + 1),
       std::runtime_error);
   auto corrupted = compressed->clone();
   corrupted->unshare();
   // Truncate the last character
   corrupted->prev()->trimEnd(1);
   if (!codec_->needsUncompressedLength()) {
     EXPECT_THROW(codec_->uncompress(corrupted.get()), std::runtime_error);
   }
   EXPECT_THROW(
       codec_->uncompress(corrupted.get(), uncompressedLength),
       std::runtime_error);
   corrupted = compressed->clone();
   corrupted->unshare();
   // Corrupt the first character
   ++(corrupted->writableData()[0]);
   if (!codec_->needsUncompressedLength()) {
     EXPECT_THROW(codec_->uncompress(corrupted.get()), std::runtime_error);
   }
   EXPECT_THROW(
       codec_->uncompress(corrupted.get(), uncompressedLength),
       std::runtime_error);
 }
void folly::io::test::CompressionCorruptionTest::SetUp () inline override protected
Definition at line 383 of file CompressionTest.cpp.
References codec_, and folly::io::getCodec().
{
     codec_ = getCodec(GetParam());
   }
Member Data Documentation
std::unique_ptr<Codec> folly::io::test::CompressionCorruptionTest::codec_ protected
Definition at line 389 of file CompressionTest.cpp.
The documentation for this class was generated from the following file:
proxygen/folly/folly/compression/test/CompressionTest.cpp