proxygen: cpp.ast.Using Class Reference
cpp.ast.Using Class Reference
Public Member Functions
def __init__ (self, start, end, names)
def __str__ (self)
def __init__ (self, start, end, names)
def __str__ (self)
def __init__ (self, start, end, names)
def __str__ (self)
Public Member Functions inherited from cpp.ast.Node
def __init__ (self, start, end)
def IsDeclaration (self)
def IsDefinition (self)
def IsExportable (self)
def Requires (self, node)
def XXX__str__ (self)
def __repr__ (self)
def __init__ (self, start, end)
def IsDeclaration (self)
def IsDefinition (self)
def IsExportable (self)
def Requires (self, node)
def XXX__str__ (self)
def __repr__ (self)
def __init__ (self, start, end)
def IsDeclaration (self)
def IsDefinition (self)
def IsExportable (self)
def Requires (self, node)
def XXX__str__ (self)
def __repr__ (self)
Public Attributes
names
Public Attributes inherited from cpp.ast.Node
start
end
Detailed Description
Definition at line 204 of file ast.py.
Constructor & Destructor Documentation
def cpp.ast.Using.__init__ (self, start, end, names)
Definition at line 205 of file ast.py.
Referenced by cpp.ast.Using.__init__().
     def __init__(self, start, end, names):
         Node.__init__(self, start, end)
         self.names = names
def cpp.ast.Using.__init__ (self, start, end, names)
Definition at line 205 of file ast.py.
References cpp.ast.Using.__init__(), and cpp.ast.Using.names.
     def __init__(self, start, end, names):
         Node.__init__(self, start, end)
         self.names = names
def cpp.ast.Using.__init__ (self, start, end, names)
Definition at line 205 of file ast.py.
References cpp.ast.Using.__init__(), and cpp.ast.Using.names.
     def __init__(self, start, end, names):
         Node.__init__(self, start, end)
         self.names = names
Member Function Documentation
def cpp.ast.Using.__str__ (self)
Definition at line 209 of file ast.py.
References cpp.ast.Node._StringHelper(), and cpp.ast.Using.names.
Referenced by cpp.ast.Using.__str__().
     def __str__(self):
         return self._StringHelper(self.__class__.__name__, str(self.names))
def cpp.ast.Using.__str__ (self)
Definition at line 209 of file ast.py.
References cpp.ast.Using.__str__(), cpp.ast.Node._StringHelper(), and cpp.ast.Using.names.
     def __str__(self):
         return self._StringHelper(self.__class__.__name__, str(self.names))
def cpp.ast.Using.__str__ (self)
Definition at line 209 of file ast.py.
References cpp.ast.Using.__str__(), cpp.ast.Node._StringHelper(), and cpp.ast.Using.names.
     def __str__(self):
         return self._StringHelper(self.__class__.__name__, str(self.names))
Member Data Documentation
cpp.ast.Using.names
Definition at line 207 of file ast.py.
Referenced by cpp.ast.Using.__init__(), and cpp.ast.Using.__str__().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/scripts/generator/cpp/ast.py