proxygen: folly::DelayedDestructionBase::DestructorGuard Class Reference
folly::DelayedDestructionBase::DestructorGuard Class Reference
#include <DelayedDestructionBase.h>
Public Member Functions
DestructorGuard (DelayedDestructionBase *dd)
DestructorGuard (const DestructorGuard &dg)
DestructorGuard (DestructorGuard &&dg) noexcept
DestructorGuard & operator= (DestructorGuard dg) noexcept
DestructorGuard & operator= (DelayedDestructionBase *dd)
~DestructorGuard ()
DelayedDestructionBase * get () const
operator bool () const
Private Attributes
DelayedDestructionBase * dd_
Detailed Description
Classes should create a DestructorGuard object on the stack in any function that may invoke callback functions.
The DestructorGuard prevents the guarded class from being destroyed while it exists. Without this, the callback function could delete the guarded object, causing problems when the callback function returns and the guarded object's method resumes execution.
Definition at line 62 of file DelayedDestructionBase.h.
Constructor & Destructor Documentation
folly::DelayedDestructionBase::DestructorGuard::DestructorGuard (DelayedDestructionBase * dd) inline explicit
Definition at line 64 of file DelayedDestructionBase.h.
References dd_, and folly::DelayedDestructionBase::guardCount_.
Referenced by operator=().
                                                          : dd_(dd) {
       if (dd_ != nullptr) {
         ++dd_->guardCount_;
         assert(dd_->guardCount_ > 0); // check for wrapping
       }
     }
folly::DelayedDestructionBase::DestructorGuard::DestructorGuard (const DestructorGuard & dg) inline
Definition at line 71 of file DelayedDestructionBase.h.
 : DestructorGuard(dg.dd_) {}
folly::DelayedDestructionBase::DestructorGuard::DestructorGuard (DestructorGuard && dg) inline noexcept
Definition at line 73 of file DelayedDestructionBase.h.
         : dd_(std::exchange(dg.dd_, nullptr)) {}
folly::DelayedDestructionBase::DestructorGuard::~DestructorGuard () inline
Definition at line 86 of file DelayedDestructionBase.h.
References dd_, folly::DelayedDestructionBase::guardCount_, and folly::DelayedDestructionBase::onDelayedDestroy().
{
       if (dd_ != nullptr) {
         assert(dd_->guardCount_ > 0);
         --dd_->guardCount_;
         if (dd_->guardCount_ == 0) {
           dd_->onDelayedDestroy(true);
         }
       }
     }
Member Function Documentation
DelayedDestructionBase* folly::DelayedDestructionBase::DestructorGuard::get () const inline
Definition at line 96 of file DelayedDestructionBase.h.
References dd_.
Referenced by folly::DelayedDestructionBase::IntrusivePtr< AliasType >::get(), folly::operator!=(), and folly::operator==().
{
       return dd_;
     }
folly::DelayedDestructionBase::DestructorGuard::operator bool () const inline explicit
Definition at line 100 of file DelayedDestructionBase.h.
References dd_.
{
       return dd_ != nullptr;
     }
DestructorGuard& folly::DelayedDestructionBase::DestructorGuard::operator= (DestructorGuard dg) inline noexcept
Definition at line 76 of file DelayedDestructionBase.h.
References dd_, and folly::f14::swap().
Referenced by folly::DelayedDestructionBase::IntrusivePtr< AliasType >::IntrusivePtr(), and folly::DelayedDestructionBase::IntrusivePtr< AliasType >::operator=().
{
       std::swap(dd_, dg.dd_);
       return *this;
     }
DestructorGuard& folly::DelayedDestructionBase::DestructorGuard::operator= (DelayedDestructionBase * dd) inline
Definition at line 81 of file DelayedDestructionBase.h.
References DestructorGuard().
{
       *this = DestructorGuard(dd);
       return *this;
     }
Member Data Documentation
DelayedDestructionBase* folly::DelayedDestructionBase::DestructorGuard::dd_ private
Definition at line 105 of file DelayedDestructionBase.h.
Referenced by DestructorGuard(), get(), operator bool(), operator=(), and ~DestructorGuard().
The documentation for this class was generated from the following file:
proxygen/folly/folly/io/async/DelayedDestructionBase.h