proxygen: folly::SSLClient Class Reference
folly::SSLClient Class Reference
#include <AsyncSSLSocketTest.h>
Public Member Functions
SSLClient (EventBase *eventBase, const folly::SocketAddress &address, uint32_t requests, uint32_t timeout=0)
~SSLClient () override
uint32_t getHit () const
uint32_t getMiss () const
uint32_t getErrors () const
uint32_t getWriteAfterConnectErrors () const
void connect (bool writeNow=false)
void connectSuccess () noexceptoverride
void connectErr (const AsyncSocketException &ex) noexceptoverride
void writeSuccess () noexceptoverride
void writeErr (size_t, const AsyncSocketException &ex) noexceptoverride
void getReadBuffer (void **bufReturn, size_t *lenReturn) override
void readEOF () noexceptoverride
void readErr (const AsyncSocketException &ex) noexceptoverride
void readDataAvailable (size_t len) noexceptoverride
Public Member Functions inherited from folly::AsyncSocket::ConnectCallback
virtual ~ConnectCallback ()=default
Public Member Functions inherited from folly::AsyncWriter::WriteCallback
virtual ~WriteCallback ()=default
Public Member Functions inherited from folly::AsyncReader::ReadCallback
virtual ~ReadCallback ()=default
virtual bool isBufferMovable () noexcept
virtual size_t maxBufferSize () const
virtual void readBufferAvailable (std::unique_ptr< IOBuf >) noexcept
Private Attributes
EventBase * eventBase_
std::shared_ptr< AsyncSSLSocket > sslSocket_
SSL_SESSION * session_
std::shared_ptr< folly::SSLContext > ctx_
uint32_t requests_
folly::SocketAddress address_
uint32_t timeout_
char buf_ [128]
char readbuf_ [128]
uint32_t bytesRead_
uint32_t hit_
uint32_t miss_
uint32_t errors_
uint32_t writeAfterConnectErrors_
Static Private Attributes
static constexpr size_t kMaxReadsPerEvent = 2
static constexpr size_t kMaxReadBufferSz
Detailed Description
Definition at line 1117 of file AsyncSSLSocketTest.h.
Constructor & Destructor Documentation
folly::SSLClient::SSLClient (EventBase * eventBase, const folly::SocketAddress & address, uint32_t requests, uint32_t timeout = 0) inline
Definition at line 1145 of file AsyncSSLSocketTest.h.
References folly::SocketAddress::reset(), and folly::detail::timeout.
       : eventBase_(eventBase),
         session_(nullptr),
         requests_(requests),
         address_(address),
         timeout_(timeout),
         bytesRead_(0),
         hit_(0),
         miss_(0),
         errors_(0),
         writeAfterConnectErrors_(0) {
     ctx_.reset(new folly::SSLContext());
     ctx_->setOptions(SSL_OP_NO_TICKET);
     ctx_->ciphers("ALL:!ADH:!LOW:!EXP:!MD5:@STRENGTH");
     memset(buf_, 'a', sizeof(buf_));
   }
folly::SSLClient::~SSLClient () inline override
Definition at line 1166 of file AsyncSSLSocketTest.h.
References EXPECT_EQ.
{
     if (session_) {
       SSL_SESSION_free(session_);
     }
     if (errors_ == 0) {
       EXPECT_EQ(bytesRead_, sizeof(buf_));
     }
   }
Member Function Documentation
void folly::SSLClient::connect (bool writeNow = false) inline
Definition at line 1191 of file AsyncSSLSocketTest.h.
References folly::AsyncSSLSocket::newSocket().
{
     sslSocket_ = AsyncSSLSocket::newSocket(ctx_, eventBase_);
     if (session_ != nullptr) {
       sslSocket_->setSSLSession(session_);
     }
     requests_--;
     sslSocket_->connect(this, address_, timeout_);
     if (sslSocket_ && writeNow) {
       // write some junk, used in an error test
       sslSocket_->write(this, buf_, sizeof(buf_));
     }
   }
void folly::SSLClient::connectErr (const AsyncSocketException & ex) inline override virtual noexcept
connectErr() will be invoked if the connection attempt fails.
Parameters
ex An exception describing the error that occurred.
Implements folly::AsyncSocket::ConnectCallback.
Definition at line 1224 of file AsyncSSLSocketTest.h.
{
     std::cerr << "SSLClient::connectError: " << ex.what() << std::endl;
     errors_++;
     sslSocket_.reset();
   }
void folly::SSLClient::connectSuccess () inline override virtual noexcept
connectSuccess() will be invoked when the connection has been successfully established.
Implements folly::AsyncSocket::ConnectCallback.
Definition at line 1204 of file AsyncSSLSocketTest.h.
{
     std::cerr << "client SSL socket connected" << std::endl;
     if (sslSocket_->getSSLSessionReused()) {
       hit_++;
     } else {
       miss_++;
       if (session_ != nullptr) {
         SSL_SESSION_free(session_);
       }
       session_ = sslSocket_->getSSLSession();
     }
     // write()
     sslSocket_->setMaxReadsPerEvent(kMaxReadsPerEvent);
     sslSocket_->write(this, buf_, sizeof(buf_));
     sslSocket_->setReadCB(this);
     memset(readbuf_, 'b', sizeof(readbuf_));
     bytesRead_ = 0;
   }
uint32_t folly::SSLClient::getErrors () const inline
Definition at line 1183 of file AsyncSSLSocketTest.h.
{
     return errors_;
   }
uint32_t folly::SSLClient::getHit () const inline
Definition at line 1175 of file AsyncSSLSocketTest.h.
{
     return hit_;
   }
uint32_t folly::SSLClient::getMiss () const inline
Definition at line 1179 of file AsyncSSLSocketTest.h.
{
     return miss_;
   }
void folly::SSLClient::getReadBuffer (void ** bufReturn, size_t * lenReturn) inline override virtual
When data becomes available, getReadBuffer() will be invoked to get the buffer into which data should be read.
This method allows the ReadCallback to delay buffer allocation until data becomes available. This allows applications to manage large numbers of idle connections, without having to maintain a separate read buffer for each idle connection.
It is possible that in some cases, getReadBuffer() may be called multiple times before readDataAvailable() is invoked. In this case, the data will be written to the buffer returned from the most recent call to readDataAvailable(). If the previous calls to readDataAvailable() returned different buffers, the ReadCallback is responsible for ensuring that they are not leaked.
If getReadBuffer() throws an exception, returns a nullptr buffer, or returns a 0 length, the ReadCallback will be uninstalled and its readError() method will be invoked.
getReadBuffer() is not allowed to change the transport state before it returns. (For example, it should never uninstall the read callback, or set a different read callback.)
Parameters
bufReturn getReadBuffer() should update *bufReturn to contain the address of the read buffer. This parameter will never be nullptr.
lenReturn getReadBuffer() should update *lenReturn to contain the maximum number of bytes that may be written to the read buffer. This parameter will never be nullptr.
Implements folly::AsyncReader::ReadCallback.
Definition at line 1243 of file AsyncSSLSocketTest.h.
References min.
{
     *bufReturn = readbuf_ + bytesRead_;
     *lenReturn = std::min(kMaxReadBufferSz, sizeof(readbuf_) - bytesRead_);
   }
uint32_t folly::SSLClient::getWriteAfterConnectErrors () const inline
Definition at line 1187 of file AsyncSSLSocketTest.h.
{
     return writeAfterConnectErrors_;
   }
void folly::SSLClient::readDataAvailable (size_t len) inline override virtual noexcept
readDataAvailable() will be invoked when data has been successfully read into the buffer returned by the last call to getReadBuffer().
The read callback remains installed after readDataAvailable() returns. It must be explicitly uninstalled to stop receiving read events. getReadBuffer() will be called at least once before each call to readDataAvailable(). getReadBuffer() will also be called before any call to readEOF().
Parameters
len The number of bytes placed in the buffer.
Implements folly::AsyncReader::ReadCallback.
Definition at line 1256 of file AsyncSSLSocketTest.h.
References folly::netops::connect(), and EXPECT_EQ.
{
     std::cerr << "client read data: " << len << std::endl;
     bytesRead_ += len;
     if (bytesRead_ == sizeof(buf_)) {
       EXPECT_EQ(memcmp(buf_, readbuf_, bytesRead_), 0);
       sslSocket_->closeNow();
       sslSocket_.reset();
       if (requests_ != 0) {
         connect();
       }
     }
   }
void folly::SSLClient::readEOF () inline override virtual noexcept
readEOF() will be invoked when the transport is closed.
The read callback will be automatically uninstalled immediately before readEOF() is invoked.
Implements folly::AsyncReader::ReadCallback.
Definition at line 1248 of file AsyncSSLSocketTest.h.
{
     std::cerr << "client readEOF" << std::endl;
   }
void folly::SSLClient::readErr (const AsyncSocketException & ex) inline override virtual noexcept
readError() will be invoked if an error occurs reading from the transport.
The read callback will be automatically uninstalled immediately before readError() is invoked.
Parameters
ex An exception describing the error that occurred.
Implements folly::AsyncReader::ReadCallback.
Definition at line 1252 of file AsyncSSLSocketTest.h.
{
     std::cerr << "client readError: " << ex.what() << std::endl;
   }
void folly::SSLClient::writeErr (size_t bytesWritten, const AsyncSocketException & ex) inline override virtual noexcept
writeError() will be invoked if an error occurs writing the data.
Parameters
bytesWritten The number of bytes that were successfull
ex An exception describing the error that occurred.
Implements folly::AsyncWriter::WriteCallback.
Definition at line 1234 of file AsyncSSLSocketTest.h.
{
     std::cerr << "client writeError: " << ex.what() << std::endl;
     if (!sslSocket_) {
       writeAfterConnectErrors_++;
     }
   }
void folly::SSLClient::writeSuccess () inline override virtual noexcept
writeSuccess() will be invoked when all of the data has been successfully written.
Note that this mainly signals that the buffer containing the data to write is no longer needed and may be freed or re-used. It does not guarantee that the data has been fully transmitted to the remote endpoint. For example, on socket-based transports, writeSuccess() only indicates that the data has been given to the kernel for eventual transmission.
Implements folly::AsyncWriter::WriteCallback.
Definition at line 1230 of file AsyncSSLSocketTest.h.
{
     std::cerr << "client write success" << std::endl;
   }
Member Data Documentation
folly::SocketAddress folly::SSLClient::address_ private
Definition at line 1126 of file AsyncSSLSocketTest.h.
char folly::SSLClient::buf_[128] private
Definition at line 1128 of file AsyncSSLSocketTest.h.
uint32_t folly::SSLClient::bytesRead_ private
Definition at line 1130 of file AsyncSSLSocketTest.h.
std::shared_ptr<folly::SSLContext> folly::SSLClient::ctx_ private
Definition at line 1124 of file AsyncSSLSocketTest.h.
uint32_t folly::SSLClient::errors_ private
Definition at line 1133 of file AsyncSSLSocketTest.h.
EventBase* folly::SSLClient::eventBase_ private
Definition at line 1121 of file AsyncSSLSocketTest.h.
uint32_t folly::SSLClient::hit_ private
Definition at line 1131 of file AsyncSSLSocketTest.h.
constexpr size_t folly::SSLClient::kMaxReadBufferSz static private
Initial value:
=
      sizeof(decltype(readbuf_)) / kMaxReadsPerEvent / 2
Definition at line 1141 of file AsyncSSLSocketTest.h.
constexpr size_t folly::SSLClient::kMaxReadsPerEvent = 2 static private
Definition at line 1139 of file AsyncSSLSocketTest.h.
uint32_t folly::SSLClient::miss_ private
Definition at line 1132 of file AsyncSSLSocketTest.h.
char folly::SSLClient::readbuf_[128] private
Definition at line 1129 of file AsyncSSLSocketTest.h.
uint32_t folly::SSLClient::requests_ private
Definition at line 1125 of file AsyncSSLSocketTest.h.
SSL_SESSION* folly::SSLClient::session_ private
Definition at line 1123 of file AsyncSSLSocketTest.h.
std::shared_ptr<AsyncSSLSocket> folly::SSLClient::sslSocket_ private
Definition at line 1122 of file AsyncSSLSocketTest.h.
uint32_t folly::SSLClient::timeout_ private
Definition at line 1127 of file AsyncSSLSocketTest.h.
uint32_t folly::SSLClient::writeAfterConnectErrors_ private
Definition at line 1134 of file AsyncSSLSocketTest.h.
The documentation for this class was generated from the following files:
proxygen/folly/folly/io/async/test/AsyncSSLSocketTest.h
proxygen/folly/folly/io/async/test/AsyncSSLSocketTest.cpp