proxygen: proxygen::StructuredHeadersStandardTest Class Reference
proxygen::StructuredHeadersStandardTest Class Reference
Public Member Functions
bool decode32 (std::string input, std::string &output)
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Private Member Functions
std::string convertBase32ToBinary (const std::string &input)
bool decode32Block (std::string input, uint32_t blockNum, std::string &outputBuffer)
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Protected Member Functions inherited from testing::Test
Test ()
virtual void SetUp ()
virtual void TearDown ()
Test ()
virtual void SetUp ()
virtual void TearDown ()
Test ()
virtual void SetUp ()
virtual void TearDown ()
Detailed Description
Definition at line 86 of file StructuredHeadersStandardTest.cpp.
Member Function Documentation
std::string proxygen::StructuredHeadersStandardTest::convertBase32ToBinary (const std::string & input) inline private
Definition at line 130 of file StructuredHeadersStandardTest.cpp.
References c, gmock_output_test::output, and string.
Referenced by decode32Block().
{
     std::string base32CharSet("ABCDEFGHIJKLMNOPQRSTUVWXYZ234567");
     std::string output;
     for (char c : input) {
       auto it = base32CharSet.find(c);
       if (it == std::string::npos) {
         return "";
       } else {
         // foundCharacter is the position within the base32CharSet where c
         // was found
         char foundCharacter = char(it);
         output.push_back(foundCharacter);
       }
     }
     return output;
   }
bool proxygen::StructuredHeadersStandardTest::decode32 (std::string input, std::string & output) inline
Definition at line 89 of file StructuredHeadersStandardTest.cpp.
References decode32Block(), i, string, and uint32_t.
Referenced by proxygen::TEST_P().
{
     uint32_t numBlocks = input.length() / 8;
     uint32_t blockRemainder = input.length() % 8;
     std::string outputBuffer(5, '\0');
     // decode each whole block of the input
     for (uint32_t j = 0; j < numBlocks; j++) {
       if (!decode32Block(input, j, outputBuffer)) {
         return false;
       }
       output += outputBuffer;
     }
     std::string padding(8, '\0');
     // set the initial bytes of the padding to be the trailing bytes of the
     // input string that have been left over
     for (uint32_t i = 0; i < blockRemainder; i++) {
       padding[i] = input[input.size() - blockRemainder + i];
     }
     if (!decode32Block(padding, 0, outputBuffer)) {
       return false;
     }
     // The second argument to the function is the size of the decoded content,
     // where the encoded content is of size (blockRemainder * 5) / 8
     outputBuffer = outputBuffer.substr(0, (blockRemainder * 5) / 8);
     output += outputBuffer;
     return true;
   }
bool proxygen::StructuredHeadersStandardTest::decode32Block (std::string input, uint32_t blockNum, std::string & outputBuffer) inline private
Definition at line 156 of file StructuredHeadersStandardTest.cpp.
References buffer(), c, convertBase32ToBinary(), i, and int64_t.
Referenced by decode32().
{
     // Remove any padding and make each character of the input represent the
     // byte value of that character, as per the rfc4648 encoding
     boost::trim_right_if(input, [](char c){return c == '=';});
     input = convertBase32ToBinary(input);
     // 8 byte buffer
     int64_t buffer = 0;
     for(int i = 0; i < 8; i++) {
       if(input[i + blockNum * 8] >= 32) {
         // a base32 value cannot be greater than or equal to 32
         return false;
       }
       buffer = (buffer << 5);
       buffer = buffer | input[i + blockNum * 8];
     }
     // set the contents of outputBuffer to contain the contents of buffer
     for (int i = 0; i < 5; i++) {
       outputBuffer[i] = char(buffer & 0xFF);
       buffer = buffer >> 8;
     }
     // we perform a reversal because outputBuffer has the contents of buffer
     // but in reverse order
     std::reverse(outputBuffer.begin(), outputBuffer.end());
     return true;
   }
The documentation for this class was generated from the following file:
proxygen/lib/http/structuredheaders/test/StructuredHeadersStandardTest.cpp