proxygen: gtest_output_test.GTestOutputTest Class Reference
gtest_output_test.GTestOutputTest Class Reference
Public Member Functions
def RemoveUnsupportedTests (self, test_output)
def testOutput (self)
def RemoveUnsupportedTests (self, test_output)
def testOutput (self)
def RemoveUnsupportedTests (self, test_output)
def testOutput (self)
Detailed Description
Definition at line 259 of file gtest_output_test.py.
Member Function Documentation
def gtest_output_test.GTestOutputTest.RemoveUnsupportedTests (self, test_output)
Definition at line 260 of file gtest_output_test.py.
References gtest_output_test.RemoveMatchingTests(), and gtest_output_test.RemoveStackTraces().
Referenced by gtest_output_test.GTestOutputTest.RemoveUnsupportedTests(), and gtest_output_test.GTestOutputTest.testOutput().
   def RemoveUnsupportedTests(self, test_output):
     if not SUPPORTS_DEATH_TESTS:
       test_output = RemoveMatchingTests(test_output, 'DeathTest')
     if not SUPPORTS_TYPED_TESTS:
       test_output = RemoveMatchingTests(test_output, 'TypedTest')
       test_output = RemoveMatchingTests(test_output, 'TypedDeathTest')
       test_output = RemoveMatchingTests(test_output, 'TypeParamDeathTest')
     if not SUPPORTS_THREADS:
       test_output = RemoveMatchingTests(test_output,
                                         'ExpectFailureWithThreadsTest')
       test_output = RemoveMatchingTests(test_output,
                                         'ScopedFakeTestPartResultReporterTest')
       test_output = RemoveMatchingTests(test_output,
                                         'WorksConcurrently')
     if not SUPPORTS_STACK_TRACES:
       test_output = RemoveStackTraces(test_output)
     return test_output
def gtest_output_test.GTestOutputTest.RemoveUnsupportedTests (self, test_output)
Definition at line 260 of file gtest_output_test.py.
References gtest_output_test.RemoveMatchingTests(), gtest_output_test.RemoveStackTraces(), and gtest_output_test.GTestOutputTest.RemoveUnsupportedTests().
   def RemoveUnsupportedTests(self, test_output):
     if not SUPPORTS_DEATH_TESTS:
       test_output = RemoveMatchingTests(test_output, 'DeathTest')
     if not SUPPORTS_TYPED_TESTS:
       test_output = RemoveMatchingTests(test_output, 'TypedTest')
       test_output = RemoveMatchingTests(test_output, 'TypedDeathTest')
       test_output = RemoveMatchingTests(test_output, 'TypeParamDeathTest')
     if not SUPPORTS_THREADS:
       test_output = RemoveMatchingTests(test_output,
                                         'ExpectFailureWithThreadsTest')
       test_output = RemoveMatchingTests(test_output,
                                         'ScopedFakeTestPartResultReporterTest')
       test_output = RemoveMatchingTests(test_output,
                                         'WorksConcurrently')
     if not SUPPORTS_STACK_TRACES:
       test_output = RemoveStackTraces(test_output)
     return test_output
def gtest_output_test.GTestOutputTest.RemoveUnsupportedTests (self, test_output)
Definition at line 260 of file gtest_output_test.py.
References gtest_output_test.RemoveMatchingTests(), gtest_output_test.RemoveStackTraces(), and gtest_output_test.GTestOutputTest.RemoveUnsupportedTests().
   def RemoveUnsupportedTests(self, test_output):
     if not SUPPORTS_DEATH_TESTS:
       test_output = RemoveMatchingTests(test_output, 'DeathTest')
     if not SUPPORTS_TYPED_TESTS:
       test_output = RemoveMatchingTests(test_output, 'TypedTest')
       test_output = RemoveMatchingTests(test_output, 'TypedDeathTest')
       test_output = RemoveMatchingTests(test_output, 'TypeParamDeathTest')
     if not SUPPORTS_THREADS:
       test_output = RemoveMatchingTests(test_output,
                                         'ExpectFailureWithThreadsTest')
       test_output = RemoveMatchingTests(test_output,
                                         'ScopedFakeTestPartResultReporterTest')
       test_output = RemoveMatchingTests(test_output,
                                         'WorksConcurrently')
     if not SUPPORTS_STACK_TRACES:
       test_output = RemoveStackTraces(test_output)
     return test_output
def gtest_output_test.GTestOutputTest.testOutput (self)
Definition at line 279 of file gtest_output_test.py.
References gtest_output_test.GetOutputOfAllCommands(), gtest_test_utils.GetSourceDir(), join, gtest_test_utils.Main(), gtest_output_test.NormalizeToCurrentPlatform(), gtest_output_test.RemoveTestCounts(), gtest_output_test.RemoveTypeInfoDetails(), gtest_output_test.GTestOutputTest.RemoveUnsupportedTests(), gtest_output_test.GTestOutputTest.testOutput(), gtest_output_test.ToUnixLineEnding(), and fizz::detail.write().
   def testOutput(self):
     output = GetOutputOfAllCommands()
     golden_file = open(GOLDEN_PATH, 'r')
     # A mis-configured source control system can cause \r appear in EOL
     # sequences when we read the golden file irrespective of an operating
     # system used. Therefore, we need to strip those \r's from newlines
     # unconditionally.
     golden = ToUnixLineEnding(golden_file.read())
     golden_file.close()
     # We want the test to pass regardless of certain features being
     # supported or not.
     # We still have to remove type name specifics in all cases.
     normalized_actual = RemoveTypeInfoDetails(output)
     normalized_golden = RemoveTypeInfoDetails(golden)
     if CAN_GENERATE_GOLDEN_FILE:
       self.assertEqual(normalized_golden, normalized_actual,
                        '\n'.join(difflib.unified_diff(
                            normalized_golden.split('\n'),
                            normalized_actual.split('\n'),
                            'golden', 'actual')))
     else:
       normalized_actual = NormalizeToCurrentPlatform(
           RemoveTestCounts(normalized_actual))
       normalized_golden = NormalizeToCurrentPlatform(
           RemoveTestCounts(self.RemoveUnsupportedTests(normalized_golden)))
       # This code is very handy when debugging golden file differences:
       if os.getenv('DEBUG_GTEST_OUTPUT_TEST'):
         open(os.path.join(
             gtest_test_utils.GetSourceDir(),
             '_gtest_output_test_normalized_actual.txt'), 'wb').write(
                 normalized_actual)
         open(os.path.join(
             gtest_test_utils.GetSourceDir(),
             '_gtest_output_test_normalized_golden.txt'), 'wb').write(
                 normalized_golden)
       self.assertEqual(normalized_golden, normalized_actual)
def gtest_output_test.GTestOutputTest.testOutput (self)
Definition at line 279 of file gtest_output_test.py.
References gtest_output_test.GetOutputOfAllCommands(), gtest_test_utils.GetSourceDir(), join, gtest_output_test.NormalizeToCurrentPlatform(), gtest_output_test.RemoveTestCounts(), gtest_output_test.RemoveTypeInfoDetails(), gtest_output_test.GTestOutputTest.RemoveUnsupportedTests(), gtest_output_test.ToUnixLineEnding(), and fizz::detail.write().
Referenced by gtest_output_test.GTestOutputTest.testOutput().
   def testOutput(self):
     output = GetOutputOfAllCommands()
     golden_file = open(GOLDEN_PATH, 'r')
     # A mis-configured source control system can cause \r appear in EOL
     # sequences when we read the golden file irrespective of an operating
     # system used. Therefore, we need to strip those \r's from newlines
     # unconditionally.
     golden = ToUnixLineEnding(golden_file.read())
     golden_file.close()
     # We want the test to pass regardless of certain features being
     # supported or not.
     # We still have to remove type name specifics in all cases.
     normalized_actual = RemoveTypeInfoDetails(output)
     normalized_golden = RemoveTypeInfoDetails(golden)
     if CAN_GENERATE_GOLDEN_FILE:
       self.assertEqual(normalized_golden, normalized_actual,
                        '\n'.join(difflib.unified_diff(
                            normalized_golden.split('\n'),
                            normalized_actual.split('\n'),
                            'golden', 'actual')))
     else:
       normalized_actual = NormalizeToCurrentPlatform(
           RemoveTestCounts(normalized_actual))
       normalized_golden = NormalizeToCurrentPlatform(
           RemoveTestCounts(self.RemoveUnsupportedTests(normalized_golden)))
       # This code is very handy when debugging golden file differences:
       if os.getenv('DEBUG_GTEST_OUTPUT_TEST'):
         open(os.path.join(
             gtest_test_utils.GetSourceDir(),
             '_gtest_output_test_normalized_actual.txt'), 'wb').write(
                 normalized_actual)
         open(os.path.join(
             gtest_test_utils.GetSourceDir(),
             '_gtest_output_test_normalized_golden.txt'), 'wb').write(
                 normalized_golden)
       self.assertEqual(normalized_golden, normalized_actual)
def gtest_output_test.GTestOutputTest.testOutput (self)
Definition at line 279 of file gtest_output_test.py.
References gtest_output_test.GetOutputOfAllCommands(), gtest_test_utils.GetSourceDir(), join, gtest_test_utils.Main(), gtest_output_test.NormalizeToCurrentPlatform(), gtest_output_test.RemoveTestCounts(), gtest_output_test.RemoveTypeInfoDetails(), gtest_output_test.GTestOutputTest.RemoveUnsupportedTests(), gtest_output_test.GTestOutputTest.testOutput(), gtest_output_test.ToUnixLineEnding(), and fizz::detail.write().
   def testOutput(self):
     output = GetOutputOfAllCommands()
     golden_file = open(GOLDEN_PATH, 'r')
     # A mis-configured source control system can cause \r appear in EOL
     # sequences when we read the golden file irrespective of an operating
     # system used. Therefore, we need to strip those \r's from newlines
     # unconditionally.
     golden = ToUnixLineEnding(golden_file.read())
     golden_file.close()
     # We want the test to pass regardless of certain features being
     # supported or not.
     # We still have to remove type name specifics in all cases.
     normalized_actual = RemoveTypeInfoDetails(output)
     normalized_golden = RemoveTypeInfoDetails(golden)
     if CAN_GENERATE_GOLDEN_FILE:
       self.assertEqual(normalized_golden, normalized_actual,
                        '\n'.join(difflib.unified_diff(
                            normalized_golden.split('\n'),
                            normalized_actual.split('\n'),
                            'golden', 'actual')))
     else:
       normalized_actual = NormalizeToCurrentPlatform(
           RemoveTestCounts(normalized_actual))
       normalized_golden = NormalizeToCurrentPlatform(
           RemoveTestCounts(self.RemoveUnsupportedTests(normalized_golden)))
       # This code is very handy when debugging golden file differences:
       if os.getenv('DEBUG_GTEST_OUTPUT_TEST'):
         open(os.path.join(
             gtest_test_utils.GetSourceDir(),
             '_gtest_output_test_normalized_actual.txt'), 'wb').write(
                 normalized_actual)
         open(os.path.join(
             gtest_test_utils.GetSourceDir(),
             '_gtest_output_test_normalized_golden.txt'), 'wb').write(
                 normalized_golden)
       self.assertEqual(normalized_golden, normalized_actual)
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest_output_test.py