proxygen: wangle::RoutingDataHandler< R > Class Template Reference
wangle::RoutingDataHandler< R > Class Template Reference abstract
#include <RoutingDataHandler.h>
Classes
class Callback
struct RoutingData
Public Member Functions
RoutingDataHandler (uint64_t connId, Callback *cob)
~RoutingDataHandler () override
void read (Context *ctx, folly::IOBufQueue &q) override
void readEOF (Context *ctx) override
void readException (Context *ctx, folly::exception_wrapper ex) override
virtual bool parseRoutingData (folly::IOBufQueue &bufQueue, RoutingData &routingData)=0
Public Member Functions inherited from wangle::HandlerAdapter< R, W >
void read (Context *ctx, R msg) override
folly::Future< folly::Unit > write (Context *ctx, W msg) override
Public Member Functions inherited from wangle::Handler< R, R, W, W >
~Handler () override=default
virtual void read (Context *ctx, Rmsg)=0
virtual void readEOF (Context *ctx)
virtual void readException (Context *ctx, folly::exception_wrapper e)
virtual void transportActive (Context *ctx)
virtual void transportInactive (Context *ctx)
virtual folly::Future< folly::Unit > write (Context *ctx, Wmsg)=0
virtual folly::Future< folly::Unit > writeException (Context *ctx, folly::exception_wrapper e)
virtual folly::Future< folly::Unit > close (Context *ctx)
Public Member Functions inherited from wangle::HandlerBase< HandlerContext< R, W > >
virtual ~HandlerBase ()=default
virtual void attachPipeline (HandlerContext< R, W > *)
virtual void detachPipeline (HandlerContext< R, W > *)
HandlerContext< R, W > * getContext ()
Private Attributes
uint64_t connId_
Callback * cob_ {nullptr}
Additional Inherited Members
Public Types inherited from wangle::HandlerAdapter< R, W >
typedef Handler< R, R, W, W >::Context Context
Public Types inherited from wangle::Handler< R, R, W, W >
typedef R rin
typedef R rout
typedef W win
typedef W wout
typedef HandlerContext< R, W > Context
Static Public Attributes inherited from wangle::Handler< R, R, W, W >
static const HandlerDir dir
Detailed Description
template<typename R>
class wangle::RoutingDataHandler< R >
Definition at line 23 of file RoutingDataHandler.h.
Constructor & Destructor Documentation
template<typename R > wangle::RoutingDataHandler< R >::RoutingDataHandler (uint64_t connId, Callback * cob)
Definition at line 21 of file RoutingDataHandler-inl.h.
Referenced by wangle::RoutingDataHandler< R >::Callback::~Callback().
     : connId_(connId), cob_(CHECK_NOTNULL(cob)) {}
template<typename R> wangle::RoutingDataHandler< R >::~RoutingDataHandler () inline override
Definition at line 40 of file RoutingDataHandler.h.
 {}
Member Function Documentation
template<typename R> virtual bool wangle::RoutingDataHandler< R >::parseRoutingData (folly::IOBufQueue & bufQueue, RoutingData & routingData) pure virtual
Parse the routing data from bufQueue into routingData. This will be used to compute the hash for choosing the worker thread.
Bytes that need to be passed into the child pipeline (such as additional bytes left in bufQueue not used for parsing) should be moved into RoutingData::bufQueue.
Returns
bool - True on success, false if bufQueue doesn't have sufficient bytes for parsing
Implemented in ClientIPRoutingDataHandler, and NaiveRoutingDataHandler.
Referenced by wangle::RoutingDataHandler< R >::read(), and wangle::RoutingDataHandler< char >::~RoutingDataHandler().
template<typename R > void wangle::RoutingDataHandler< R >::read (Context * ctx, folly::IOBufQueue & q) override
Definition at line 25 of file RoutingDataHandler-inl.h.
References wangle::RoutingDataHandler< R >::cob_, wangle::RoutingDataHandler< R >::connId_, wangle::RoutingDataHandler< R >::Callback::onRoutingData(), and wangle::RoutingDataHandler< R >::parseRoutingData().
Referenced by wangle::RoutingDataHandler< char >::~RoutingDataHandler().
{
   RoutingData routingData;
   if (parseRoutingData(q, routingData)) {
     cob_->onRoutingData(connId_, routingData);
   }
 }
template<typename R > void wangle::RoutingDataHandler< R >::readEOF (Context * ctx) override
Definition at line 33 of file RoutingDataHandler-inl.h.
References wangle::RoutingDataHandler< R >::cob_, wangle::RoutingDataHandler< R >::connId_, folly::AsyncSocketException::END_OF_FILE, and wangle::RoutingDataHandler< R >::Callback::onError().
Referenced by wangle::RoutingDataHandler< char >::~RoutingDataHandler().
{
   const auto& ex = folly::make_exception_wrapper<folly::AsyncSocketException>(
       folly::AsyncSocketException::END_OF_FILE,
       "Received EOF before parsing routing data");
   cob_->onError(connId_, ex);
 }
template<typename R > void wangle::RoutingDataHandler< R >::readException (Context * ctx, folly::exception_wrapper ex) override
Definition at line 41 of file RoutingDataHandler-inl.h.
References wangle::RoutingDataHandler< R >::cob_, wangle::RoutingDataHandler< R >::connId_, and wangle::RoutingDataHandler< R >::Callback::onError().
Referenced by wangle::RoutingDataHandler< char >::~RoutingDataHandler().
{
   cob_->onError(connId_, ex);
 }
Member Data Documentation
template<typename R> Callback* wangle::RoutingDataHandler< R >::cob_ {nullptr} private
Definition at line 63 of file RoutingDataHandler.h.
Referenced by wangle::RoutingDataHandler< R >::read(), wangle::RoutingDataHandler< R >::readEOF(), and wangle::RoutingDataHandler< R >::readException().
template<typename R> uint64_t wangle::RoutingDataHandler< R >::connId_ private
Definition at line 62 of file RoutingDataHandler.h.
Referenced by wangle::RoutingDataHandler< R >::read(), wangle::RoutingDataHandler< R >::readEOF(), and wangle::RoutingDataHandler< R >::readException().
The documentation for this class was generated from the following files:
proxygen/wangle/wangle/bootstrap/RoutingDataHandler.h
proxygen/wangle/wangle/bootstrap/RoutingDataHandler-inl.h