proxygen: testing::gmock_matchers_test::NewEvenMatcherImpl Class Reference
testing::gmock_matchers_test::NewEvenMatcherImpl Class Reference
Public Member Functions
virtual bool MatchAndExplain (int x, MatchResultListener *listener) const
virtual void DescribeTo (ostream *os) const
virtual bool MatchAndExplain (int x, MatchResultListener *listener) const
virtual void DescribeTo (ostream *os) const
virtual bool MatchAndExplain (int x, MatchResultListener *listener) const
virtual void DescribeTo (ostream *os) const
Public Member Functions inherited from testing::MatcherInterface< T >
virtual bool MatchAndExplain (T x, MatchResultListener *listener) const =0
virtual bool MatchAndExplain (T x, MatchResultListener *listener) const =0
virtual bool MatchAndExplain (T x, MatchResultListener *listener) const =0
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
virtual void DescribeTo (::std::ostream *os) const =0
virtual void DescribeNegationTo (::std::ostream *os) const
virtual ~MatcherDescriberInterface ()
virtual void DescribeTo (::std::ostream *os) const =0
virtual void DescribeNegationTo (::std::ostream *os) const
virtual ~MatcherDescriberInterface ()
virtual void DescribeTo (::std::ostream *os) const =0
virtual void DescribeNegationTo (::std::ostream *os) const
Detailed Description
Definition at line 280 of file gmock-matchers_test.cc.
Member Function Documentation
virtual void testing::gmock_matchers_test::NewEvenMatcherImpl::DescribeTo (ostream * os) const inline virtual
Definition at line 294 of file gmock-matchers_test.cc.
{
     *os << "is an even number";
   }
virtual void testing::gmock_matchers_test::NewEvenMatcherImpl::DescribeTo (ostream * os) const inline virtual
Definition at line 294 of file gmock-matchers_test.cc.
References testing::gmock_matchers_test::Describe(), testing::Eq(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testing::gmock_matchers_test::Explain(), testing::gmock_matchers_test::g_bar, testing::gmock_matchers_test::GreaterThan(), m, testing::MakeMatcher(), testing::internal::MatcherBase< T >::MatchAndExplain(), testing::internal::MatcherBase< T >::Matches(), testing::StringMatchResultListener::str(), and testing::internal::TEST().
{
     *os << "is an even number";
   }
virtual void testing::gmock_matchers_test::NewEvenMatcherImpl::DescribeTo (ostream * os) const inline virtual
Definition at line 294 of file gmock-matchers_test.cc.
References testing::gmock_matchers_test::Describe(), testing::Eq(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testing::gmock_matchers_test::Explain(), testing::gmock_matchers_test::g_bar, testing::gmock_matchers_test::GreaterThan(), m, testing::MakeMatcher(), testing::internal::MatcherBase< T >::MatchAndExplain(), testing::internal::MatcherBase< T >::Matches(), testing::StringMatchResultListener::str(), and testing::internal::TEST().
{
     *os << "is an even number";
   }
virtual bool testing::gmock_matchers_test::NewEvenMatcherImpl::MatchAndExplain (int x, MatchResultListener * listener) const inline virtual
Definition at line 282 of file gmock-matchers_test.cc.
References testing::MatchResultListener::stream().
{
     const bool match = x % 2 == 0;
     // Verifies that we can stream to a listener directly.
     *listener << "value % " << 2;
     if (listener->stream() != NULL) {
       // Verifies that we can stream to a listener's underlying stream
       // too.
       *listener->stream() << " == " << (x % 2);
     }
     return match;
   }
virtual bool testing::gmock_matchers_test::NewEvenMatcherImpl::MatchAndExplain (int x, MatchResultListener * listener) const inline virtual
Definition at line 282 of file gmock-matchers_test.cc.
References testing::MatchResultListener::stream().
{
     const bool match = x % 2 == 0;
     // Verifies that we can stream to a listener directly.
     *listener << "value % " << 2;
     if (listener->stream() != NULL) {
       // Verifies that we can stream to a listener's underlying stream
       // too.
       *listener->stream() << " == " << (x % 2);
     }
     return match;
   }
virtual bool testing::gmock_matchers_test::NewEvenMatcherImpl::MatchAndExplain (int x, MatchResultListener * listener) const inline virtual
Definition at line 282 of file gmock-matchers_test.cc.
References testing::MatchResultListener::stream().
{
     const bool match = x % 2 == 0;
     // Verifies that we can stream to a listener directly.
     *listener << "value % " << 2;
     if (listener->stream() != NULL) {
       // Verifies that we can stream to a listener's underlying stream
       // too.
       *listener->stream() << " == " << (x % 2);
     }
     return match;
   }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-matchers_test.cc