proxygen: wangle::ClientBootstrap< Pipeline > Class Template Reference
wangle::ClientBootstrap< Pipeline > Class Template Reference
#include <ClientBootstrap.h>
Classes
class ConnectCallback
Public Member Functions
ClientBootstrap ()
ClientBootstrap * group (std::shared_ptr< folly::IOThreadPoolExecutor > group)
ClientBootstrap * bind (int port)
folly::Future< Pipeline * > connect (const folly::SocketAddress &address, std::chrono::milliseconds timeout=std::chrono::milliseconds(0)) override
~ClientBootstrap () override=default
Public Member Functions inherited from wangle::BaseClientBootstrap< Pipeline >
BaseClientBootstrap ()
virtual ~BaseClientBootstrap ()=default
BaseClientBootstrap< Pipeline > * pipelineFactory (std::shared_ptr< PipelineFactory< Pipeline >> factory) noexcept
Pipeline * getPipeline ()
BaseClientBootstrap * sslContext (folly::SSLContextPtr sslContext)
BaseClientBootstrap * sslSession (SSL_SESSION *sslSession)
BaseClientBootstrap * serverName (const std::string &sni)
BaseClientBootstrap * sslSessionEstablishedCallback (SSLSessionEstablishedCallbackUniquePtr sslSessionEstablishedCallback)
BaseClientBootstrap * deferSecurityNegotiation (bool deferSecurityNegotiation)
void setPipeline (const typename Pipeline::Ptr &pipeline)
virtual void makePipeline (std::shared_ptr< folly::AsyncTransportWrapper > socket)
Public Member Functions inherited from folly::DestructorCheck
virtual ~DestructorCheck ()
Protected Attributes
int port_
std::shared_ptr< folly::IOThreadPoolExecutor > group_
Protected Attributes inherited from wangle::BaseClientBootstrap< Pipeline >
std::shared_ptr< PipelineFactory< Pipeline > > pipelineFactory_
Pipeline::Ptr pipeline_
folly::SSLContextPtr sslContext_
SSL_SESSION * sslSession_
std::string sni_
bool deferSecurityNegotiation_
SSLSessionEstablishedCallbackUniquePtr sslSessionEstablishedCallback_
Additional Inherited Members
Public Types inherited from wangle::BaseClientBootstrap< Pipeline >
using Ptr = std::unique_ptr< BaseClientBootstrap >
Detailed Description
template<typename Pipeline>
class wangle::ClientBootstrap< Pipeline >
Definition at line 35 of file ClientBootstrap.h.
Constructor & Destructor Documentation
template<typename Pipeline> wangle::ClientBootstrap< Pipeline >::ClientBootstrap () inline
Definition at line 85 of file ClientBootstrap.h.
                     {
   }
template<typename Pipeline> wangle::ClientBootstrap< Pipeline >::~ClientBootstrap () override default
Referenced by wangle::ClientBootstrap< DefaultPipeline >::connect().
Member Function Documentation
template<typename Pipeline> ClientBootstrap* wangle::ClientBootstrap< Pipeline >::bind (int port) inline
Definition at line 94 of file ClientBootstrap.h.
{
     port_ = port;
     return this;
   }
template<typename Pipeline> folly::Future<Pipeline*> wangle::ClientBootstrap< Pipeline >::connect (const folly::SocketAddress & address, std::chrono::milliseconds timeout = std::chrono::milliseconds(0)) inline override virtual
Implements wangle::BaseClientBootstrap< Pipeline >.
Definition at line 99 of file ClientBootstrap.h.
Referenced by main(), and TEST().
{
     auto base = (group_)
       ? group_->getEventBase()
       : folly::EventBaseManager::get()->getEventBase();
     folly::Future<Pipeline*> retval((Pipeline*)nullptr);
     base->runImmediatelyOrRunInEventBaseThreadAndWait([&](){
       std::shared_ptr<folly::AsyncSocket> socket;
       if (this->sslContext_) {
         auto sslSocket = folly::AsyncSSLSocket::newSocket(
             this->sslContext_, base, this->deferSecurityNegotiation_);
         if (!this->sni_.empty()) {
           sslSocket->setServerName(this->sni_);
         }
         if (this->sslSession_) {
           sslSocket->setSSLSession(this->sslSession_, true);
         }
         socket = sslSocket;
       } else {
         socket = folly::AsyncSocket::newSocket(base);
       }
       folly::Promise<Pipeline*> promise;
       retval = promise.getFuture();
       socket->connect(
           new ConnectCallback(
               std::move(promise),
               this,
               socket,
               std::move(this->sslSessionEstablishedCallback_)),
           address,
           timeout.count());
     });
     return retval;
   }
template<typename Pipeline> ClientBootstrap* wangle::ClientBootstrap< Pipeline >::group (std::shared_ptr< folly::IOThreadPoolExecutor > group) inline
Definition at line 88 of file ClientBootstrap.h.
Referenced by wangle::ClientBootstrap< DefaultPipeline >::group(), and main().
{
     group_ = group;
     return this;
   }
Member Data Documentation
template<typename Pipeline> std::shared_ptr<folly::IOThreadPoolExecutor> wangle::ClientBootstrap< Pipeline >::group_ protected
Definition at line 140 of file ClientBootstrap.h.
Referenced by wangle::ClientBootstrap< DefaultPipeline >::connect(), and wangle::ClientBootstrap< DefaultPipeline >::group().
template<typename Pipeline> int wangle::ClientBootstrap< Pipeline >::port_ protected
Definition at line 139 of file ClientBootstrap.h.
Referenced by wangle::ClientBootstrap< DefaultPipeline >::bind().
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/bootstrap/ClientBootstrap.h