proxygen: deadlock.DiGraph Class Reference
deadlock.DiGraph Class Reference
Public Member Functions
def __init__ (self)
def neighbors (self, node)
def edges (self)
def nodes (self)
def attributes (self, node1, node2)
def add_edge (self, node1, node2, kwargs)
def remove_node (self, node)
def subgraph (self, nodes)
def node_link_data (self)
Public Attributes
adjacency_map
attributes_map
Detailed Description
Adapted from networkx: http://networkx.github.io/
Represents a directed graph. Edges can store (key, value) attributes.
Definition at line 9 of file deadlock.py.
Constructor & Destructor Documentation
def deadlock.DiGraph.__init__ (self)
Definition at line 15 of file deadlock.py.
     def __init__(self):
         # Map of node -> set of nodes
         self.adjacency_map = {}
         # Map of (node1, node2) -> map string -> arbitrary attribute
         # This will not be copied in subgraph()
         self.attributes_map = {}
Member Function Documentation
def deadlock.DiGraph.add_edge (self, node1, node2, kwargs)
Definition at line 38 of file deadlock.py.
References add, deadlock.DiGraph.adjacency_map, and deadlock.DiGraph.attributes_map.
     def add_edge(self, node1, node2, **kwargs):
         if node1 not in self.adjacency_map:
             self.adjacency_map[node1] = set()
         if node2 not in self.adjacency_map:
             self.adjacency_map[node2] = set()
         self.adjacency_map[node1].add(node2)
         self.attributes_map[(node1, node2)] = kwargs
def deadlock.DiGraph.attributes (self, node1, node2)
Definition at line 35 of file deadlock.py.
References deadlock.DiGraph.attributes_map.
     def attributes(self, node1, node2):
         return self.attributes_map[(node1, node2)]
def deadlock.DiGraph.edges (self)
Definition at line 25 of file deadlock.py.
     def edges(self):
         edges = []
         for node, neighbors in self.adjacency_map.items():
             for neighbor in neighbors:
                 edges.append((node, neighbor))
         return edges
def deadlock.DiGraph.neighbors (self, node)
Definition at line 22 of file deadlock.py.
Referenced by deadlock.DiGraph.subgraph().
     def neighbors(self, node):
         return self.adjacency_map.get(node, set())
def deadlock.DiGraph.node_link_data (self)
Returns the graph as a dictionary in a format that can be
serialized.
Definition at line 59 of file deadlock.py.
References append(), deadlock.DiGraph.attributes_map, and folly.copy().
     def node_link_data(self):
         '''
         Returns the graph as a dictionary in a format that can be
         serialized.
         '''
         data = {
             'directed': True,
             'multigraph': False,
             'graph': {},
             'links': [],
             'nodes': [],
         }
         # Do one pass to build a map of node -> position in nodes
         node_to_number = {}
         for node in self.adjacency_map.keys():
             node_to_number[node] = len(data['nodes'])
             data['nodes'].append({'id': node})
         # Do another pass to build the link information
         for node, neighbors in self.adjacency_map.items():
             for neighbor in neighbors:
                 link = self.attributes_map[(node, neighbor)].copy()
                 link['source'] = node_to_number[node]
                 link['target'] = node_to_number[neighbor]
                 data['links'].append(link)
         return data
def deadlock.DiGraph.nodes (self)
Definition at line 32 of file deadlock.py.
     def nodes(self):
         return self.adjacency_map.keys()
def deadlock.DiGraph.remove_node (self, node)
Definition at line 46 of file deadlock.py.
     def remove_node(self, node):
         self.adjacency_map.pop(node, None)
         for _, neighbors in self.adjacency_map.items():
             neighbors.discard(node)
def deadlock.DiGraph.subgraph (self, nodes)
Definition at line 51 of file deadlock.py.
References deadlock.DiGraph.neighbors().
     def subgraph(self, nodes):
         graph = DiGraph()
         for node in nodes:
             for neighbor in self.neighbors(node):
                 if neighbor in nodes:
                     graph.add_edge(node, neighbor)
         return graph
Member Data Documentation
deadlock.DiGraph.adjacency_map
Definition at line 17 of file deadlock.py.
Referenced by deadlock.DiGraph.add_edge().
deadlock.DiGraph.attributes_map
Definition at line 20 of file deadlock.py.
Referenced by deadlock.DiGraph.add_edge(), deadlock.DiGraph.attributes(), and deadlock.DiGraph.node_link_data().
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/gdb/deadlock.py