proxygen: folly::DefaultKeepAliveExecutor Class Reference
folly::DefaultKeepAliveExecutor Class Reference
#include <DefaultKeepAliveExecutor.h>
Classes
struct ControlBlock
class WeakRef
Public Member Functions
DefaultKeepAliveExecutor ()
virtual ~DefaultKeepAliveExecutor ()
folly::Executor::KeepAlive weakRef ()
Public Member Functions inherited from folly::Executor
virtual ~Executor ()
virtual void add (Func)=0
virtual void addWithPriority (Func, int8_t priority)
virtual uint8_t getNumPriorities () const
Protected Member Functions
void joinKeepAlive ()
Private Member Functions
bool keepAliveAcquire () override
void keepAliveRelease () override
Private Attributes
std::shared_ptr< ControlBlock > controlBlock_ {std::make_shared<ControlBlock>()}
Baton keepAliveReleaseBaton_
KeepAlive< DefaultKeepAliveExecutor > keepAlive_
Additional Inherited Members
Static Public Member Functions inherited from folly::Executor
template<typename ExecutorT >
static KeepAlive< ExecutorT > getKeepAliveToken (ExecutorT *executor)
template<typename ExecutorT >
static KeepAlive< ExecutorT > getKeepAliveToken (ExecutorT &executor)
Static Public Attributes inherited from folly::Executor
static const int8_t LO_PRI = SCHAR_MIN
static const int8_t MID_PRI = 0
static const int8_t HI_PRI = SCHAR_MAX
Static Protected Member Functions inherited from folly::Executor
template<typename ExecutorT >
static bool isKeepAliveDummy (const KeepAlive< ExecutorT > &keepAlive)
template<typename ExecutorT >
static KeepAlive< ExecutorT > makeKeepAlive (ExecutorT *executor)
Detailed Description
An Executor accepts units of work with add(), which should be threadsafe.
Definition at line 30 of file DefaultKeepAliveExecutor.h.
Constructor & Destructor Documentation
folly::DefaultKeepAliveExecutor::DefaultKeepAliveExecutor () inline
Definition at line 32 of file DefaultKeepAliveExecutor.h.
 : Executor() {}
virtual folly::DefaultKeepAliveExecutor::~DefaultKeepAliveExecutor () inline virtual
Definition at line 34 of file DefaultKeepAliveExecutor.h.
References keepAlive_.
{
     DCHECK(!keepAlive_);
   }
Member Function Documentation
void folly::DefaultKeepAliveExecutor::joinKeepAlive () inline protected
Definition at line 43 of file DefaultKeepAliveExecutor.h.
References keepAlive_, keepAliveReleaseBaton_, and folly::Baton< MayBlock, Atom >::wait().
Referenced by folly::ThreadPoolExecutor::joinKeepAliveOnce(), and folly::VirtualExecutor::~VirtualExecutor().
{
     DCHECK(keepAlive_);
     keepAlive_.reset();
     keepAliveReleaseBaton_.wait();
   }
bool folly::DefaultKeepAliveExecutor::keepAliveAcquire () inline override private virtual
Reimplemented from folly::Executor.
Definition at line 126 of file DefaultKeepAliveExecutor.h.
References controlBlock_.
{
     auto keepAliveCount =
         controlBlock_->keepAliveCount_.fetch_add(1, std::memory_order_relaxed);
     // We should never increment from 0
     DCHECK(keepAliveCount > 0);
     return true;
   }
void folly::DefaultKeepAliveExecutor::keepAliveRelease () inline override private virtual
Reimplemented from folly::Executor.
Definition at line 134 of file DefaultKeepAliveExecutor.h.
References controlBlock_, keepAliveReleaseBaton_, and folly::Baton< MayBlock, Atom >::post().
{
     auto keepAliveCount =
         controlBlock_->keepAliveCount_.fetch_sub(1, std::memory_order_acquire);
     DCHECK(keepAliveCount >= 1);
     if (keepAliveCount == 1) {
       keepAliveReleaseBaton_.post(); // std::memory_order_release
     }
   }
folly::Executor::KeepAlive folly::DefaultKeepAliveExecutor::weakRef () inline
Definition at line 38 of file DefaultKeepAliveExecutor.h.
References controlBlock_, and folly::DefaultKeepAliveExecutor::WeakRef::create().
{
     return WeakRef::create(controlBlock_, this);
   }
Member Data Documentation
std::shared_ptr<ControlBlock> folly::DefaultKeepAliveExecutor::controlBlock_ {std::make_shared<ControlBlock>()} private
Definition at line 144 of file DefaultKeepAliveExecutor.h.
Referenced by keepAliveAcquire(), keepAliveRelease(), folly::DefaultKeepAliveExecutor::WeakRef::lock(), and weakRef().
KeepAlive<DefaultKeepAliveExecutor> folly::DefaultKeepAliveExecutor::keepAlive_ private
Initial value:
{
      makeKeepAlive<DefaultKeepAliveExecutor>(this)}
Definition at line 146 of file DefaultKeepAliveExecutor.h.
Referenced by joinKeepAlive(), folly::VirtualExecutor::wrapFunc(), and ~DefaultKeepAliveExecutor().
Baton folly::DefaultKeepAliveExecutor::keepAliveReleaseBaton_ private
Definition at line 145 of file DefaultKeepAliveExecutor.h.
Referenced by joinKeepAlive(), and keepAliveRelease().
The documentation for this class was generated from the following file:
proxygen/folly/folly/DefaultKeepAliveExecutor.h