proxygen: fizz::server::test::ServerProtocolTest Class Reference
fizz::server::test::ServerProtocolTest Class Reference
Public Member Functions
void SetUp () override
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Protected Member Functions
Actions getActions (AsyncActions asyncActions, bool immediate=true)
void setMockRecord ()
void setMockAppRecord ()
void setMockKeyScheduler ()
void setMockHandshakeContext ()
void acceptEarlyData ()
void acceptCookies ()
void expectCookie ()
void setUpExpectingClientHello ()
void setUpExpectingClientHelloRetry ()
void setUpExpectingFinished ()
void setUpExpectingCertificate ()
void setUpExpectingCertificateVerify ()
void setUpAcceptingEarlyData ()
void setUpAcceptingData ()
Protected Member Functions inherited from fizz::test::ProtocolTest< ServerTypes, Actions >
void expectActions (const Actions &actions)
T expectAction (Actions &actions)
T expectSingleAction (Actions actions)
void processStateMutations (Actions &actions)
uint32_t getNumActions (const Actions &actions, bool expectNonZero)
uint32_t getNumActions (const Actions &actions, bool expectNonZero)
void expectExceptionType (Actions &actions)
void expectError (Actions &actions, folly::Optional< AlertDescription > alert, std::string msg="")
void expectAeadCreation (std::map< std::string, MockAead ** > keys)
void expectAeadCreation (MockAead **clientAead, MockAead **serverAead)
void expectEncryptedReadRecordLayerCreation (MockEncryptedReadRecordLayer **recordLayer, MockAead **readAead, folly::ByteRange expectedBaseSecret, folly::Optional< bool > skipFailedDecryption=folly::none, Sequence *s=nullptr)
void expectEncryptedWriteRecordLayerCreation (MockEncryptedWriteRecordLayer **recordLayer, MockAead **writeAead, folly::ByteRange expectedBaseSecret, std::function< TLSContent(TLSMessage &, MockEncryptedWriteRecordLayer *)> expectedWrite=nullptr, Sequence *s=nullptr)
Protected Member Functions inherited from testing::Test
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Static Protected Member Functions
static std::unique_ptr< IOBuf > getEncryptedHandshakeWrite (EncryptedExtensions encryptedExt, CertificateMsg certificate, CertificateVerify verify, Finished finished)
static std::unique_ptr< IOBuf > getEncryptedHandshakeWrite (EncryptedExtensions encryptedExt, CertificateRequest request, CertificateMsg certificate, CertificateVerify verify, Finished finished)
static std::unique_ptr< IOBuf > getEncryptedHandshakeWrite (EncryptedExtensions encryptedExt, CompressedCertificate certificate, CertificateVerify verify, Finished finished)
static std::unique_ptr< IOBuf > getEncryptedHandshakeWrite (EncryptedExtensions encryptedExt, Finished finished)
Protected Attributes
ManualExecutor executor_
MockPlaintextReadRecordLayer * mockRead_
MockPlaintextWriteRecordLayer * mockWrite_
MockEncryptedReadRecordLayer * appRead_
MockEncryptedWriteRecordLayer * appWrite_
MockHandshakeContext * mockHandshakeContext_
MockKeyScheduler * mockKeyScheduler_
std::shared_ptr< MockTicketCipher > mockTicketCipher_
std::shared_ptr< MockCookieCipher > mockCookieCipher_
std::shared_ptr< FizzServerContext > context_
std::shared_ptr< MockSelfCert > cert_
std::shared_ptr< MockPeerCert > clientIntCert_
std::shared_ptr< MockPeerCert > clientLeafCert_
std::shared_ptr< MockCertificateVerifier > certVerifier_
MockCertManager * certManager_
std::shared_ptr< MockServerExtensions > extensions_
std::shared_ptr< MockReplayCache > replayCache_
bool addExtensions_ = true
Protected Attributes inherited from fizz::test::ProtocolTest< ServerTypes, Actions >
ServerTypes::State state_
MockFactory * factory_
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Protected Types inherited from fizz::test::ProtocolTest< ServerTypes, Actions >
using MutateState = folly::Function< void(typename ServerTypes::State &)>
Detailed Description
Definition at line 30 of file ServerProtocolTest.cpp.
Member Function Documentation
void fizz::server::test::ServerProtocolTest::acceptCookies () inline protected
Definition at line 158 of file ServerProtocolTest.cpp.
{
     mockCookieCipher_ = std::make_shared<MockCookieCipher>();
     context_->setCookieCipher(mockCookieCipher_);
   }
void fizz::server::test::ServerProtocolTest::acceptEarlyData () inline protected
Definition at line 146 of file ServerProtocolTest.cpp.
References testing::_, check(), testing::InvokeWithoutArgs(), folly::makeFuture(), fizz::server::NotReplay, and ON_CALL.
{
     replayCache_ = std::make_shared<MockReplayCache>();
     ON_CALL(*replayCache_, check(_)).WillByDefault(InvokeWithoutArgs([] {
       return folly::makeFuture(ReplayCacheResult::NotReplay);
     }));
     context_->setEarlyDataSettings(
         true,
         {std::chrono::milliseconds(-1000000),
          std::chrono::milliseconds(1000000)},
         replayCache_);
   }
void fizz::server::test::ServerProtocolTest::expectCookie () inline protected
Definition at line 163 of file ServerProtocolTest.cpp.
References testing::_, fizz::server::CookieState::appToken, fizz::server::CookieState::chloHash, fizz::server::CookieState::cipher, cookie, folly::IOBuf::copyBuffer(), folly::IOBuf::create(), EXPECT_CALL, testing::Invoke(), folly::gen::move, fizz::test::TestProtocolVersion, fizz::TLS_AES_128_GCM_SHA256, and fizz::server::CookieState::version.
                       {
     acceptCookies();
     EXPECT_CALL(*mockCookieCipher_, _decrypt(_))
         .WillOnce(Invoke([](Buf& cookie) {
           if (IOBufEqualTo()(cookie, IOBuf::copyBuffer("cookie"))) {
             CookieState cs;
             cs.version = TestProtocolVersion;
             cs.cipher = CipherSuite::TLS_AES_128_GCM_SHA256;
             cs.chloHash = IOBuf::copyBuffer("chlohash");
             cs.appToken = IOBuf::create(0);
             return folly::Optional<CookieState>(std::move(cs));
           } else {
             return folly::Optional<CookieState>();
           }
         }));
   }
Actions fizz::server::test::ServerProtocolTest::getActions (AsyncActions asyncActions, bool immediate = true) inline protected
Definition at line 58 of file ServerProtocolTest.cpp.
References EXPECT_TRUE, folly::futures::detail::FutureBase< T >::hasValue(), folly::gen::move, and folly::variant_match().
{
     while (executor_.run())
       ;
     return folly::variant_match(
         asyncActions,
         [immediate](folly::Future<Actions>& futureActions) {
           if (immediate) {
             EXPECT_TRUE(futureActions.hasValue());
           }
           return std::move(futureActions).get();
         },
         [](Actions& immediateActions) { return std::move(immediateActions); });
   }
static std::unique_ptr<IOBuf> fizz::server::test::ServerProtocolTest::getEncryptedHandshakeWrite (EncryptedExtensions encryptedExt, CertificateMsg certificate, CertificateVerify verify, Finished finished) inline static protected
Definition at line 72 of file ServerProtocolTest.cpp.
References fizz::encodeHandshake(), and folly::gen::move.
{
     auto buf = encodeHandshake(std::move(encryptedExt));
     buf->prependChain(encodeHandshake(std::move(certificate)));
     buf->prependChain(encodeHandshake(std::move(verify)));
     buf->prependChain(encodeHandshake(std::move(finished)));
     return buf;
   }
static std::unique_ptr<IOBuf> fizz::server::test::ServerProtocolTest::getEncryptedHandshakeWrite (EncryptedExtensions encryptedExt, CertificateRequest request, CertificateMsg certificate, CertificateVerify verify, Finished finished) inline static protected
Definition at line 84 of file ServerProtocolTest.cpp.
References fizz::encodeHandshake(), and folly::gen::move.
{
     auto buf = encodeHandshake(std::move(encryptedExt));
     buf->prependChain(encodeHandshake(std::move(request)));
     buf->prependChain(encodeHandshake(std::move(certificate)));
     buf->prependChain(encodeHandshake(std::move(verify)));
     buf->prependChain(encodeHandshake(std::move(finished)));
     return buf;
   }
static std::unique_ptr<IOBuf> fizz::server::test::ServerProtocolTest::getEncryptedHandshakeWrite (EncryptedExtensions encryptedExt, CompressedCertificate certificate, CertificateVerify verify, Finished finished) inline static protected
Definition at line 98 of file ServerProtocolTest.cpp.
References fizz::encodeHandshake(), and folly::gen::move.
{
     auto buf = encodeHandshake(std::move(encryptedExt));
     buf->prependChain(encodeHandshake(std::move(certificate)));
     buf->prependChain(encodeHandshake(std::move(verify)));
     buf->prependChain(encodeHandshake(std::move(finished)));
     return buf;
   }
static std::unique_ptr<IOBuf> fizz::server::test::ServerProtocolTest::getEncryptedHandshakeWrite (EncryptedExtensions encryptedExt, Finished finished) inline static protected
Definition at line 110 of file ServerProtocolTest.cpp.
References fizz::encodeHandshake(), and folly::gen::move.
{
     auto buf = encodeHandshake(std::move(encryptedExt));
     buf->prependChain(encodeHandshake(std::move(finished)));
     return buf;
   }
void fizz::server::test::ServerProtocolTest::setMockAppRecord () inline protected
Definition at line 126 of file ServerProtocolTest.cpp.
References fizz::AppTraffic.
{
     appRead_ = new MockEncryptedReadRecordLayer(EncryptionLevel::AppTraffic);
     appWrite_ = new MockEncryptedWriteRecordLayer(EncryptionLevel::AppTraffic);
     appWrite_->setDefaults();
     state_.readRecordLayer().reset(appRead_);
     state_.writeRecordLayer().reset(appWrite_);
   }
void fizz::server::test::ServerProtocolTest::setMockHandshakeContext () inline protected
Definition at line 140 of file ServerProtocolTest.cpp.
{
     mockHandshakeContext_ = new MockHandshakeContext();
     mockHandshakeContext_->setDefaults();
     state_.handshakeContext().reset(mockHandshakeContext_);
   }
void fizz::server::test::ServerProtocolTest::setMockKeyScheduler () inline protected
Definition at line 134 of file ServerProtocolTest.cpp.
{
     mockKeyScheduler_ = new MockKeyScheduler();
     mockKeyScheduler_->setDefaults();
     state_.keyScheduler().reset(mockKeyScheduler_);
   }
void fizz::server::test::ServerProtocolTest::setMockRecord () inline protected
Definition at line 118 of file ServerProtocolTest.cpp.
{
     mockRead_ = new MockPlaintextReadRecordLayer();
     mockWrite_ = new MockPlaintextWriteRecordLayer();
     mockWrite_->setDefaults();
     state_.readRecordLayer().reset(mockRead_);
     state_.writeRecordLayer().reset(mockWrite_);
   }
void fizz::server::test::ServerProtocolTest::SetUp () inline override virtual
Reimplemented from testing::Test.
Definition at line 32 of file ServerProtocolTest.cpp.
References testing::_, fizz::ecdsa_secp256r1_sha256, fizz::test::getCert(), folly::gen::move, ON_CALL, testing::Return(), and fizz::tls_1_3.
{
     context_ = std::make_shared<FizzServerContext>();
     context_->setSupportedVersions({ProtocolVersion::tls_1_3});
     auto mockFactory = std::make_unique<MockFactory>();
     mockFactory->setDefaults();
     factory_ = mockFactory.get();
     context_->setFactory(std::move(mockFactory));
     cert_ = std::make_shared<MockSelfCert>();
     auto certManager = std::make_unique<MockCertManager>();
     certManager_ = certManager.get();
     certVerifier_ = std::make_shared<MockCertificateVerifier>();
     context_->setClientCertVerifier(certVerifier_);
     context_->setCertManager(std::move(certManager));
     context_->setSupportedAlpns({"h2", "h3"});
     mockTicketCipher_ = std::make_shared<MockTicketCipher>();
     mockTicketCipher_->setDefaults();
     context_->setTicketCipher(mockTicketCipher_);
     extensions_ = std::make_shared<MockServerExtensions>();
     ON_CALL(*certManager_, getCert(_, _, _))
         .WillByDefault(Return(CertManager::CertMatch(
             std::make_pair(cert_, SignatureScheme::ecdsa_secp256r1_sha256))));
     ON_CALL(*certManager_, getCert(_)).WillByDefault(Return(cert_));
   }
void fizz::server::test::ServerProtocolTest::setUpAcceptingData () inline protected
Definition at line 272 of file ServerProtocolTest.cpp.
References fizz::NotAttempted, fizz::test::TestProtocolVersion, and fizz::TLS_AES_128_GCM_SHA256.
{
     setMockAppRecord();
     setMockKeyScheduler();
     setMockHandshakeContext();
     state_.executor() = &executor_;
     state_.version() = TestProtocolVersion;
     state_.cipher() = CipherSuite::TLS_AES_128_GCM_SHA256;
     state_.context() = context_;
     state_.executor() = &executor_;
     state_.state() = StateEnum::AcceptingData;
     state_.serverCert() = cert_;
     state_.pskType() = PskType::NotAttempted;
     state_.alpn() = "h2";
   }
void fizz::server::test::ServerProtocolTest::setUpAcceptingEarlyData () inline protected
Definition at line 260 of file ServerProtocolTest.cpp.
References fizz::Handshake, fizz::test::TestProtocolVersion, and fizz::TLS_AES_128_GCM_SHA256.
{
     setMockRecord();
     setMockKeyScheduler();
     setMockHandshakeContext();
     state_.handshakeReadRecordLayer().reset(
         new MockEncryptedReadRecordLayer(EncryptionLevel::Handshake));
     state_.version() = TestProtocolVersion;
     state_.cipher() = CipherSuite::TLS_AES_128_GCM_SHA256;
     state_.executor() = &executor_;
     state_.state() = StateEnum::AcceptingEarlyData;
   }
void fizz::server::test::ServerProtocolTest::setUpExpectingCertificate () inline protected
Definition at line 221 of file ServerProtocolTest.cpp.
References folly::IOBuf::copyBuffer(), fizz::NotAttempted, fizz::test::TestProtocolVersion, and fizz::TLS_AES_128_GCM_SHA256.
{
     setMockRecord();
     setMockKeyScheduler();
     setMockHandshakeContext();
     state_.executor() = &executor_;
     state_.context() = context_;
     state_.clientHandshakeSecret() = IOBuf::copyBuffer("clihandsec");
     state_.exporterMasterSecret() = IOBuf::copyBuffer("exportermaster");
     state_.version() = TestProtocolVersion;
     state_.cipher() = CipherSuite::TLS_AES_128_GCM_SHA256;
     state_.state() = StateEnum::ExpectingCertificate;
     state_.serverCert() = cert_;
     state_.pskType() = PskType::NotAttempted;
     state_.alpn() = "h2";
     context_->setClientAuthMode(ClientAuthMode::Required);
   }
void fizz::server::test::ServerProtocolTest::setUpExpectingCertificateVerify () inline protected
Definition at line 238 of file ServerProtocolTest.cpp.
References folly::IOBuf::copyBuffer(), folly::gen::move, fizz::NotAttempted, fizz::test::TestProtocolVersion, and fizz::TLS_AES_128_GCM_SHA256.
{
     setMockRecord();
     setMockKeyScheduler();
     setMockHandshakeContext();
     state_.executor() = &executor_;
     state_.context() = context_;
     state_.clientHandshakeSecret() = IOBuf::copyBuffer("clihandsec");
     state_.exporterMasterSecret() = IOBuf::copyBuffer("exportermaster");
     state_.version() = TestProtocolVersion;
     state_.cipher() = CipherSuite::TLS_AES_128_GCM_SHA256;
     state_.state() = StateEnum::ExpectingCertificateVerify;
     state_.serverCert() = cert_;
     clientIntCert_ = std::make_shared<MockPeerCert>();
     clientLeafCert_ = std::make_shared<MockPeerCert>();
     std::vector<std::shared_ptr<const PeerCert>> clientCerts = {clientLeafCert_,
                                                                 clientIntCert_};
     state_.unverifiedCertChain() = std::move(clientCerts);
     state_.pskType() = PskType::NotAttempted;
     state_.alpn() = "h2";
     context_->setClientAuthMode(ClientAuthMode::Required);
   }
void fizz::server::test::ServerProtocolTest::setUpExpectingClientHello () inline protected
Definition at line 180 of file ServerProtocolTest.cpp.
{
     setMockRecord();
     state_.executor() = &executor_;
     state_.context() = context_;
     state_.state() = StateEnum::ExpectingClientHello;
     if (addExtensions_) {
       state_.extensions() = extensions_;
     }
   }
void fizz::server::test::ServerProtocolTest::setUpExpectingClientHelloRetry () inline protected
Definition at line 190 of file ServerProtocolTest.cpp.
References fizz::HelloRetryRequest, fizz::test::TestProtocolVersion, fizz::TLS_AES_128_GCM_SHA256, and fizz::x25519.
{
     setMockRecord();
     setMockHandshakeContext();
     state_.executor() = &executor_;
     state_.context() = context_;
     state_.version() = TestProtocolVersion;
     state_.cipher() = CipherSuite::TLS_AES_128_GCM_SHA256;
     state_.group() = NamedGroup::x25519;
     state_.keyExchangeType() = KeyExchangeType::HelloRetryRequest;
     state_.state() = StateEnum::ExpectingClientHello;
     if (addExtensions_) {
       state_.extensions() = extensions_;
     }
   }
void fizz::server::test::ServerProtocolTest::setUpExpectingFinished () inline protected
Definition at line 205 of file ServerProtocolTest.cpp.
References folly::IOBuf::copyBuffer(), fizz::NotAttempted, fizz::test::TestProtocolVersion, and fizz::TLS_AES_128_GCM_SHA256.
{
     setMockRecord();
     setMockKeyScheduler();
     setMockHandshakeContext();
     state_.executor() = &executor_;
     state_.context() = context_;
     state_.clientHandshakeSecret() = IOBuf::copyBuffer("clihandsec");
     state_.exporterMasterSecret() = IOBuf::copyBuffer("exportermaster");
     state_.version() = TestProtocolVersion;
     state_.cipher() = CipherSuite::TLS_AES_128_GCM_SHA256;
     state_.state() = StateEnum::ExpectingFinished;
     state_.serverCert() = cert_;
     state_.pskType() = PskType::NotAttempted;
     state_.alpn() = "h2";
   }
Member Data Documentation
bool fizz::server::test::ServerProtocolTest::addExtensions_ = true protected
Definition at line 304 of file ServerProtocolTest.cpp.
MockEncryptedReadRecordLayer* fizz::server::test::ServerProtocolTest::appRead_ protected
Definition at line 290 of file ServerProtocolTest.cpp.
MockEncryptedWriteRecordLayer* fizz::server::test::ServerProtocolTest::appWrite_ protected
Definition at line 291 of file ServerProtocolTest.cpp.
std::shared_ptr<MockSelfCert> fizz::server::test::ServerProtocolTest::cert_ protected
Definition at line 297 of file ServerProtocolTest.cpp.
MockCertManager* fizz::server::test::ServerProtocolTest::certManager_ protected
Definition at line 301 of file ServerProtocolTest.cpp.
std::shared_ptr<MockCertificateVerifier> fizz::server::test::ServerProtocolTest::certVerifier_ protected
Definition at line 300 of file ServerProtocolTest.cpp.
std::shared_ptr<MockPeerCert> fizz::server::test::ServerProtocolTest::clientIntCert_ protected
Definition at line 298 of file ServerProtocolTest.cpp.
std::shared_ptr<MockPeerCert> fizz::server::test::ServerProtocolTest::clientLeafCert_ protected
Definition at line 299 of file ServerProtocolTest.cpp.
std::shared_ptr<FizzServerContext> fizz::server::test::ServerProtocolTest::context_ protected
Definition at line 296 of file ServerProtocolTest.cpp.
ManualExecutor fizz::server::test::ServerProtocolTest::executor_ protected
Definition at line 287 of file ServerProtocolTest.cpp.
std::shared_ptr<MockServerExtensions> fizz::server::test::ServerProtocolTest::extensions_ protected
Definition at line 302 of file ServerProtocolTest.cpp.
std::shared_ptr<MockCookieCipher> fizz::server::test::ServerProtocolTest::mockCookieCipher_ protected
Definition at line 295 of file ServerProtocolTest.cpp.
MockHandshakeContext* fizz::server::test::ServerProtocolTest::mockHandshakeContext_ protected
Definition at line 292 of file ServerProtocolTest.cpp.
MockKeyScheduler* fizz::server::test::ServerProtocolTest::mockKeyScheduler_ protected
Definition at line 293 of file ServerProtocolTest.cpp.
MockPlaintextReadRecordLayer* fizz::server::test::ServerProtocolTest::mockRead_ protected
Definition at line 288 of file ServerProtocolTest.cpp.
std::shared_ptr<MockTicketCipher> fizz::server::test::ServerProtocolTest::mockTicketCipher_ protected
Definition at line 294 of file ServerProtocolTest.cpp.
MockPlaintextWriteRecordLayer* fizz::server::test::ServerProtocolTest::mockWrite_ protected
Definition at line 289 of file ServerProtocolTest.cpp.
std::shared_ptr<MockReplayCache> fizz::server::test::ServerProtocolTest::replayCache_ protected
Definition at line 303 of file ServerProtocolTest.cpp.
The documentation for this class was generated from the following file:
proxygen/fizz/fizz/server/test/ServerProtocolTest.cpp