proxygen: fizz::test::ZlibCertificateCompressorTest Class Reference
fizz::test::ZlibCertificateCompressorTest Class Reference
Public Member Functions
void SetUp () override
void TearDown () override
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Protected Member Functions
template<class T >
T decodeHex (const std::string &hex)
template<class T >
std::string encodeHex (T &&msg)
Protected Member Functions inherited from testing::Test
Test ()
Test ()
Test ()
Protected Attributes
std::unique_ptr< ZlibCertificateCompressor > compressor_
std::unique_ptr< ZlibCertificateDecompressor > decompressor_
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Detailed Description
Definition at line 186 of file ZlibCertificateCompressorTest.cpp.
Member Function Documentation
template<class T > T fizz::test::ZlibCertificateCompressorTest::decodeHex (const std::string & hex) inline protected
Definition at line 198 of file ZlibCertificateCompressorTest.cpp.
References folly::IOBuf::copyBuffer(), folly::data(), folly::gen::move, and folly::unhexlify().
{
     auto data = unhexlify(hex);
     auto buf = IOBuf::copyBuffer(data.data(), data.size());
     return decode<T>(std::move(buf));
   }
template<class T > std::string fizz::test::ZlibCertificateCompressorTest::encodeHex (T && msg) inline protected
Definition at line 205 of file ZlibCertificateCompressorTest.cpp.
References encode(), and folly::hexlify().
{
     auto buf = encode(std::forward<T>(msg));
     auto str = buf->moveToFbString().toStdString();
     return hexlify(str);
   }
void fizz::test::ZlibCertificateCompressorTest::SetUp () inline override virtual
Reimplemented from testing::Test.
Definition at line 188 of file ZlibCertificateCompressorTest.cpp.
{
     OpenSSL_add_all_algorithms();
     compressor_ = std::make_unique<ZlibCertificateCompressor>(9);
     decompressor_ = std::make_unique<ZlibCertificateDecompressor>();
   }
void fizz::test::ZlibCertificateCompressorTest::TearDown () inline override virtual
Reimplemented from testing::Test.
Definition at line 194 of file ZlibCertificateCompressorTest.cpp.
 {}
Member Data Documentation
std::unique_ptr<ZlibCertificateCompressor> fizz::test::ZlibCertificateCompressorTest::compressor_ protected
Definition at line 210 of file ZlibCertificateCompressorTest.cpp.
std::unique_ptr<ZlibCertificateDecompressor> fizz::test::ZlibCertificateCompressorTest::decompressor_ protected
Definition at line 211 of file ZlibCertificateCompressorTest.cpp.
The documentation for this class was generated from the following file:
proxygen/fizz/fizz/protocol/test/ZlibCertificateCompressorTest.cpp