proxygen: UDPClient Class Reference
UDPClient Class Reference
Public Member Functions
UDPClient (EventBase *evb, TestData &testData)
void start (const folly::SocketAddress &server)
void connect ()
void shutdown ()
void sendPing ()
virtual void writePing (std::unique_ptr< folly::IOBuf > buf, int gso)
void getReadBuffer (void **buf, size_t *len) noexceptoverride
void onDataAvailable (const folly::SocketAddress &, size_t len, bool) noexceptoverride
void onReadError (const folly::AsyncSocketException &ex) noexceptoverride
void onReadClosed () noexceptoverride
void timeoutExpired () noexceptoverride
AsyncUDPSocket & getSocket ()
void setShouldConnect (const folly::SocketAddress &connectAddr)
UDPClient (EventBase *evb)
void start (const folly::SocketAddress &server, int n)
void connect ()
void shutdown ()
void sendPing ()
virtual void writePing (std::unique_ptr< folly::IOBuf > buf)
void getReadBuffer (void **buf, size_t *len) noexceptoverride
void onDataAvailable (const folly::SocketAddress &client, size_t len, bool truncated) noexceptoverride
void onReadError (const folly::AsyncSocketException &ex) noexceptoverride
void onReadClosed () noexceptoverride
void timeoutExpired () noexceptoverride
int pongRecvd () const
AsyncUDPSocket & getSocket ()
void setShouldConnect (const folly::SocketAddress &connectAddr)
Protected Attributes
folly::Optional< folly::SocketAddress > connectAddr_
EventBase *const evb_ {nullptr}
folly::SocketAddress server_
std::unique_ptr< AsyncUDPSocket > socket_
Private Attributes
char buf_ [2048]
TestData & testData_
int pongRecvd_ {0}
int n_ {0}
Additional Inherited Members
Private Types inherited from folly::AsyncTimeout
typedef TimeoutManager::InternalEnum InternalEnum
Private Member Functions inherited from folly::AsyncTimeout
AsyncTimeout (TimeoutManager *timeoutManager)
AsyncTimeout (EventBase *eventBase)
AsyncTimeout (TimeoutManager *timeoutManager, InternalEnum internal)
AsyncTimeout (EventBase *eventBase, InternalEnum internal)
AsyncTimeout ()
virtual ~AsyncTimeout ()
bool scheduleTimeout (uint32_t milliseconds)
bool scheduleTimeout (TimeoutManager::timeout_type timeout)
void cancelTimeout ()
bool isScheduled () const
void attachTimeoutManager (TimeoutManager *timeoutManager, InternalEnum internal=InternalEnum::NORMAL)
void attachEventBase (EventBase *eventBase, InternalEnum internal=InternalEnum::NORMAL)
void detachTimeoutManager ()
void detachEventBase ()
const TimeoutManager * getTimeoutManager ()
struct event * getEvent ()
Static Private Member Functions inherited from folly::AsyncTimeout
template<typename TCallback >
static std::unique_ptr< AsyncTimeout > make (TimeoutManager &manager, TCallback &&callback)
template<typename TCallback >
static std::unique_ptr< AsyncTimeout > schedule (TimeoutManager::timeout_type timeout, TimeoutManager &manager, TCallback &&callback)
Detailed Description
Definition at line 188 of file AsyncUDPSocketGSOTest.cpp.
Constructor & Destructor Documentation
UDPClient::UDPClient (EventBase * evb, TestData & testData) inline explicit
Definition at line 190 of file AsyncUDPSocketGSOTest.cpp.
       : AsyncTimeout(evb), evb_(evb), testData_(testData) {}
UDPClient::UDPClient (EventBase * evb) inline explicit
Definition at line 170 of file AsyncUDPSocketTest.cpp.
 : AsyncTimeout(evb), evb_(evb) {}
Member Function Documentation
void UDPClient::connect () inline
Definition at line 195 of file AsyncUDPSocketTest.cpp.
References folly::AsyncSocketException::NOT_OPEN, and socket_.
                  {
     int ret = socket_->connect(*connectAddr_);
     if (ret != 0) {
       throw folly::AsyncSocketException(
           folly::AsyncSocketException::NOT_OPEN, "ConnectFail", errno);
     }
     VLOG(2) << "Client connected to address=" << *connectAddr_;
   }
void UDPClient::connect () inline
Definition at line 228 of file AsyncUDPSocketGSOTest.cpp.
References folly::AsyncSocketException::NOT_OPEN, and socket_.
                  {
     int ret = socket_->connect(*connectAddr_);
     if (ret != 0) {
       throw folly::AsyncSocketException(
           folly::AsyncSocketException::NOT_OPEN, "ConnectFail", errno);
     }
     VLOG(2) << "Client connected to address=" << *connectAddr_;
   }
void UDPClient::getReadBuffer (void ** buf, size_t * len) inline override noexcept
Definition at line 227 of file AsyncUDPSocketTest.cpp.
{
     *buf = buf_;
     *len = 1024;
   }
void UDPClient::getReadBuffer (void ** buf, size_t * len) inline override noexcept
Definition at line 255 of file AsyncUDPSocketGSOTest.cpp.
{
     *buf = buf_;
     *len = sizeof(buf_);
   }
AsyncUDPSocket& UDPClient::getSocket () inline
Definition at line 265 of file AsyncUDPSocketTest.cpp.
References socket_.
{
     return *socket_;
   }
AsyncUDPSocket& UDPClient::getSocket () inline
Definition at line 286 of file AsyncUDPSocketGSOTest.cpp.
References socket_.
{
     return *socket_;
   }
void UDPClient::onDataAvailable (const folly::SocketAddress & client, size_t len, bool truncated) inline override noexcept
Definition at line 232 of file AsyncUDPSocketTest.cpp.
References string.
{
     VLOG(4) << "Read " << len << " bytes (trun:" << truncated << ") from "
             << client.describe() << " - " << std::string(buf_, len);
     VLOG(4) << n_ << " left";
     ++pongRecvd_;
     sendPing();
   }
void UDPClient::onDataAvailable (const folly::SocketAddress & , size_t len, bool) inline override noexcept
Definition at line 260 of file AsyncUDPSocketGSOTest.cpp.
References folly::shutdown().
{
     VLOG(0) << "Got " << len << " bytes";
     if (testData_.appendOut(len)) {
       shutdown();
     }
   }
void UDPClient::onReadClosed () inline override noexcept
Definition at line 252 of file AsyncUDPSocketTest.cpp.
{
     CHECK(false) << "We unregister reads before closing";
   }
void UDPClient::onReadClosed () inline override noexcept
Definition at line 277 of file AsyncUDPSocketGSOTest.cpp.
{
     CHECK(false) << "We unregister reads before closing";
   }
void UDPClient::onReadError (const folly::AsyncSocketException & ex) inline override noexcept
Definition at line 245 of file AsyncUDPSocketTest.cpp.
References socket_.
{
     VLOG(4) << ex.what();
     // Start listening for next PONG
     socket_->resumeRead(this);
   }
void UDPClient::onReadError (const folly::AsyncSocketException & ex) inline override noexcept
Definition at line 270 of file AsyncUDPSocketGSOTest.cpp.
References socket_.
{
     VLOG(4) << ex.what();
     // Start listening for next PONG
     socket_->resumeRead(this);
   }
int UDPClient::pongRecvd () const inline
Definition at line 261 of file AsyncUDPSocketTest.cpp.
{
     return pongRecvd_;
   }
void UDPClient::sendPing () inline
Definition at line 212 of file AsyncUDPSocketTest.cpp.
References folly::IOBuf::copyBuffer(), folly::shutdown(), and proxygen::http2::writePing().
                   {
     if (n_ == 0) {
       shutdown();
       return;
     }
     --n_;
     scheduleTimeout(5);
     writePing(folly::IOBuf::copyBuffer(folly::to<std::string>("PING ", n_)));
   }
void UDPClient::sendPing () inline
Definition at line 245 of file AsyncUDPSocketGSOTest.cpp.
References proxygen::http2::writePing().
                   {
     scheduleTimeout(5);
     writePing(
         testData_.getInBuf(), testData_.useSocketGSO_ ? -1 : testData_.gso_);
   }
void UDPClient::setShouldConnect (const folly::SocketAddress & connectAddr) inline
Definition at line 269 of file AsyncUDPSocketTest.cpp.
References evb_, and socket_.
{
     connectAddr_ = connectAddr;
   }
void UDPClient::setShouldConnect (const folly::SocketAddress & connectAddr) inline
Definition at line 290 of file AsyncUDPSocketGSOTest.cpp.
{
     connectAddr_ = connectAddr;
   }
void UDPClient::shutdown () inline
Definition at line 204 of file AsyncUDPSocketTest.cpp.
References evb_, folly::EventBase::isInEventBaseThread(), socket_, and folly::EventBase::terminateLoopSoon().
                   {
     CHECK(evb_->isInEventBaseThread());
     socket_->pauseRead();
     socket_->close();
     socket_.reset();
     evb_->terminateLoopSoon();
   }
void UDPClient::shutdown () inline
Definition at line 237 of file AsyncUDPSocketGSOTest.cpp.
References evb_, folly::EventBase::isInEventBaseThread(), socket_, and folly::EventBase::terminateLoopSoon().
                   {
     CHECK(evb_->isInEventBaseThread());
     socket_->pauseRead();
     socket_->close();
     socket_.reset();
     evb_->terminateLoopSoon();
   }
void UDPClient::start (const folly::SocketAddress & server, int n) inline
Definition at line 172 of file AsyncUDPSocketTest.cpp.
References folly::netops::connect(), evb_, folly::EventBase::isInEventBaseThread(), and socket_.
{
     CHECK(evb_->isInEventBaseThread());
     server_ = server;
     socket_ = std::make_unique<AsyncUDPSocket>(evb_);
     try {
       socket_->bind(folly::SocketAddress("127.0.0.1", 0));
       if (connectAddr_) {
         connect();
       }
       VLOG(2) << "Client bound to " << socket_->address().describe();
     } catch (const std::exception& ex) {
       LOG(FATAL) << ex.what();
     }
     socket_->resumeRead(this);
     n_ = n;
     // Start playing ping pong
     sendPing();
   }
void UDPClient::start (const folly::SocketAddress & server) inline
Definition at line 193 of file AsyncUDPSocketGSOTest.cpp.
References folly::netops::connect(), evb_, folly::EventBase::isInEventBaseThread(), folly::shutdown(), and socket_.
{
     CHECK(evb_->isInEventBaseThread());
     server_ = server;
     socket_ = std::make_unique<AsyncUDPSocket>(evb_);
     try {
       socket_->bind(folly::SocketAddress("127.0.0.1", 0));
       if (connectAddr_) {
         connect();
       }
       VLOG(2) << "Client bound to " << socket_->address().describe();
     } catch (const std::exception& ex) {
       LOG(FATAL) << ex.what();
     }
     // succeed if GSO not available
     if (socket_->getGSO() < 0) {
       LOG(INFO) << "GSO  not supported";
       testData_.out_ = testData_.expected_;
       shutdown();
       return;
     }
     if (testData_.useSocketGSO_) {
       socket_->setGSO(testData_.gso_);
     } else {
       socket_->setGSO(0);
     }
     socket_->resumeRead(this);
     // Start playing ping pong
     sendPing();
   }
void UDPClient::timeoutExpired () inline override virtual noexcept
timeoutExpired() is invoked when the timeout period has expired.
Implements folly::AsyncTimeout.
Definition at line 256 of file AsyncUDPSocketTest.cpp.
{
     VLOG(4) << "Timeout expired";
     sendPing();
   }
void UDPClient::timeoutExpired () inline override virtual noexcept
timeoutExpired() is invoked when the timeout period has expired.
Implements folly::AsyncTimeout.
Definition at line 281 of file AsyncUDPSocketGSOTest.cpp.
References folly::shutdown().
{
     VLOG(4) << "Timeout expired";
     shutdown();
   }
virtual void UDPClient::writePing (std::unique_ptr< folly::IOBuf > buf) inline virtual
Reimplemented in ConnectedWriteUDPClient.
Definition at line 223 of file AsyncUDPSocketTest.cpp.
References folly::gen::move, and socket_.
{
     socket_->write(server_, std::move(buf));
   }
virtual void UDPClient::writePing (std::unique_ptr< folly::IOBuf > buf, int gso) inline virtual
Definition at line 251 of file AsyncUDPSocketGSOTest.cpp.
References folly::gen::move, and socket_.
{
     socket_->writeGSO(server_, std::move(buf), gso);
   }
Member Data Documentation
char UDPClient::buf_ private
Definition at line 302 of file AsyncUDPSocketGSOTest.cpp.
folly::Optional< folly::SocketAddress > UDPClient::connectAddr_ protected
Definition at line 295 of file AsyncUDPSocketGSOTest.cpp.
EventBase *const UDPClient::evb_ {nullptr} protected
Definition at line 296 of file AsyncUDPSocketGSOTest.cpp.
int UDPClient::n_ {0} private
Definition at line 283 of file AsyncUDPSocketTest.cpp.
int UDPClient::pongRecvd_ {0} private
Definition at line 281 of file AsyncUDPSocketTest.cpp.
folly::SocketAddress UDPClient::server_ protected
Definition at line 298 of file AsyncUDPSocketGSOTest.cpp.
std::unique_ptr< AsyncUDPSocket > UDPClient::socket_ protected
Definition at line 299 of file AsyncUDPSocketGSOTest.cpp.
TestData& UDPClient::testData_ private
Definition at line 303 of file AsyncUDPSocketGSOTest.cpp.
The documentation for this class was generated from the following files:
proxygen/folly/folly/io/async/test/AsyncUDPSocketGSOTest.cpp
proxygen/folly/folly/io/async/test/AsyncUDPSocketTest.cpp