proxygen: folly::rvalue_reference_wrapper< T > Class Template Reference
folly::rvalue_reference_wrapper< T > Class Template Reference
#include <RValueReferenceWrapper.h>
Public Types
using type = T
Public Member Functions
rvalue_reference_wrapper () noexcept
rvalue_reference_wrapper (T &&ref) noexcept
rvalue_reference_wrapper (T &) noexcept=delete
rvalue_reference_wrapper (rvalue_reference_wrapper< T > &&other) noexcept
rvalue_reference_wrapper & operator= (rvalue_reference_wrapper &&other) noexcept
operator T && ()&&noexcept
T && get ()&&noexcept
template<class... Args>
decltype(auto) operator() (Args &&...args)&&noexcept(noexcept(std::declval< T >()(std::forward< Args >(args)...)))
bool valid () const noexcept
Private Member Functions
rvalue_reference_wrapper (const rvalue_reference_wrapper &)=delete
rvalue_reference_wrapper & operator= (const rvalue_reference_wrapper &)=delete
Private Attributes
T * ptr_
Detailed Description
template<class T>
class folly::rvalue_reference_wrapper< T >
Class template that wraps a reference to an rvalue. Similar to std::reference_wrapper but with three important differences:
1) folly::rvalue_reference_wrappers can only be moved, not copied; 2) the get() function and the conversion-to-T operator are destructive and not const, they invalidate the wrapper; 3) the constructor-from-T is explicit.
These restrictions are designed to make it harder to accidentally create a a dangling rvalue reference, or to use an rvalue reference multiple times. (Using an rvalue reference typically implies invalidation of the target object, such as move-assignment to another object.)
folly::rref
Examples:
/facebook/proxygen/proxygen/folly/folly/container/Iterator.h.
Definition at line 42 of file RValueReferenceWrapper.h.
Member Typedef Documentation
template<class T> using folly::rvalue_reference_wrapper< T >::type = T
Examples:
/facebook/proxygen/proxygen/folly/folly/lang/RValueReferenceWrapper.h.
Definition at line 44 of file RValueReferenceWrapper.h.
Constructor & Destructor Documentation
template<class T> folly::rvalue_reference_wrapper< T >::rvalue_reference_wrapper () inline noexcept
Default constructor. Creates an invalid reference. Must be move-assigned to in order to be come valid.
Examples:
/facebook/proxygen/proxygen/folly/folly/lang/RValueReferenceWrapper.h.
Definition at line 50 of file RValueReferenceWrapper.h.
Referenced by folly::rvalue_reference_wrapper< T >::rvalue_reference_wrapper(), and folly::rvalue_reference_wrapper< T >::valid().
 : ptr_(nullptr) {}
template<class T> folly::rvalue_reference_wrapper< T >::rvalue_reference_wrapper (T && ref) inline explicit noexcept
Explicit constructor to make it harder to accidentally create a dangling reference to a temporary.
Definition at line 56 of file RValueReferenceWrapper.h.
References folly::pushmi::__adl::noexcept(), folly::rvalue_reference_wrapper< T >::rvalue_reference_wrapper(), and folly::T.
       : ptr_(std::addressof(ref)) {}
template<class T> folly::rvalue_reference_wrapper< T >::rvalue_reference_wrapper (T &) explicit delete noexcept
No construction from lvalue reference. Use std::move.
template<class T> folly::rvalue_reference_wrapper< T >::rvalue_reference_wrapper (rvalue_reference_wrapper< T > && other) inline noexcept
Destructive move construction.
Definition at line 67 of file RValueReferenceWrapper.h.
       : ptr_(other.ptr_) {
     other.ptr_ = nullptr;
   }
template<class T> folly::rvalue_reference_wrapper< T >::rvalue_reference_wrapper (const rvalue_reference_wrapper< T > &) private delete
Member Function Documentation
template<class T> T&& folly::rvalue_reference_wrapper< T >::get () inline noexcept
Explicit unwrap. Destructive.
Definition at line 92 of file RValueReferenceWrapper.h.
References testing::Args(), folly::rvalue_reference_wrapper< T >::ptr_, folly::T, and folly::rvalue_reference_wrapper< T >::valid().
Referenced by folly::rvalue_reference_wrapper< T >::operator T &&(), and folly::rvalue_reference_wrapper< T >::operator()().
{
     assert(valid());
     T& ref = *ptr_;
     ptr_ = nullptr;
     return static_cast<T&&>(ref);
   }
template<class T> folly::rvalue_reference_wrapper< T >::operator T && () inline noexcept
Implicit conversion to raw reference. Destructive.
Definition at line 85 of file RValueReferenceWrapper.h.
References folly::rvalue_reference_wrapper< T >::get().
{
     return static_cast<rvalue_reference_wrapper&&>(*this).get();
   }
template<class T> template<class... Args> decltype(auto) folly::rvalue_reference_wrapper< T >::operator() (Args &&... args) inline noexcept
Calls the callable object to whom reference is stored. Only available if the wrapped reference points to a callable object. Destructive.
Examples:
/facebook/proxygen/proxygen/folly/folly/lang/RValueReferenceWrapper.h.
Definition at line 104 of file RValueReferenceWrapper.h.
References folly::rvalue_reference_wrapper< T >::get().
{
     return static_cast<rvalue_reference_wrapper&&>(*this).get()(
         std::forward<Args>(args)...);
   }
template<class T> rvalue_reference_wrapper& folly::rvalue_reference_wrapper< T >::operator= (rvalue_reference_wrapper< T > && other) inline noexcept
Destructive move assignment.
Examples:
/facebook/proxygen/proxygen/folly/folly/lang/RValueReferenceWrapper.h.
Definition at line 75 of file RValueReferenceWrapper.h.
References folly::rvalue_reference_wrapper< T >::ptr_.
Referenced by folly::rvalue_reference_wrapper< T >::valid().
{
     ptr_ = other.ptr_;
     other.ptr_ = nullptr;
     return *this;
   }
template<class T> rvalue_reference_wrapper& folly::rvalue_reference_wrapper< T >::operator= (const rvalue_reference_wrapper< T > &) private delete
template<class T> bool folly::rvalue_reference_wrapper< T >::valid () const inline noexcept
Check whether wrapped reference is valid.
Examples:
/facebook/proxygen/proxygen/folly/folly/lang/RValueReferenceWrapper.h.
Definition at line 113 of file RValueReferenceWrapper.h.
References folly::rvalue_reference_wrapper< T >::operator=(), folly::rvalue_reference_wrapper< T >::ptr_, and folly::rvalue_reference_wrapper< T >::rvalue_reference_wrapper().
Referenced by folly::rvalue_reference_wrapper< T >::get().
{
     return ptr_ != nullptr;
   }
Member Data Documentation
template<class T> T* folly::rvalue_reference_wrapper< T >::ptr_ private
Examples:
/facebook/proxygen/proxygen/folly/folly/lang/RValueReferenceWrapper.h.
Definition at line 123 of file RValueReferenceWrapper.h.
Referenced by folly::rvalue_reference_wrapper< T >::get(), folly::rvalue_reference_wrapper< T >::operator=(), and folly::rvalue_reference_wrapper< T >::valid().
The documentation for this class was generated from the following file:
proxygen/folly/folly/lang/RValueReferenceWrapper.h