proxygen: gtest_color_test.GTestColorTest Class Reference
gtest_color_test.GTestColorTest Class Reference
Public Member Functions
def testNoEnvVarNoFlag (self)
def testFlagOnly (self)
def testEnvVarOnly (self)
def testEnvVarAndFlag (self)
def testAliasesOfYesAndNo (self)
def testNoEnvVarNoFlag (self)
def testFlagOnly (self)
def testEnvVarOnly (self)
def testEnvVarAndFlag (self)
def testAliasesOfYesAndNo (self)
def testNoEnvVarNoFlag (self)
def testFlagOnly (self)
def testEnvVarOnly (self)
def testEnvVarAndFlag (self)
def testAliasesOfYesAndNo (self)
Detailed Description
Definition at line 70 of file gtest_color_test.py.
Member Function Documentation
def gtest_color_test.GTestColorTest.testAliasesOfYesAndNo (self)
Tests using aliases in specifying --gtest_color.
Definition at line 115 of file gtest_color_test.py.
References gtest_test_utils.Main(), and gtest_color_test.UsesColor().
Referenced by gtest_color_test.GTestColorTest.testAliasesOfYesAndNo().
   def testAliasesOfYesAndNo(self):
     """Tests using aliases in specifying --gtest_color."""
     self.assert_(UsesColor('dumb', None, 'true'))
     self.assert_(UsesColor('dumb', None, 'YES'))
     self.assert_(UsesColor('dumb', None, 'T'))
     self.assert_(UsesColor('dumb', None, '1'))
     self.assert_(not UsesColor('xterm', None, 'f'))
     self.assert_(not UsesColor('xterm', None, 'false'))
     self.assert_(not UsesColor('xterm', None, '0'))
     self.assert_(not UsesColor('xterm', None, 'unknown'))
def gtest_color_test.GTestColorTest.testAliasesOfYesAndNo (self)
Tests using aliases in specifying --gtest_color.
Definition at line 115 of file gtest_color_test.py.
References gtest_test_utils.Main(), gtest_color_test.GTestColorTest.testAliasesOfYesAndNo(), and gtest_color_test.UsesColor().
   def testAliasesOfYesAndNo(self):
     """Tests using aliases in specifying --gtest_color."""
     self.assert_(UsesColor('dumb', None, 'true'))
     self.assert_(UsesColor('dumb', None, 'YES'))
     self.assert_(UsesColor('dumb', None, 'T'))
     self.assert_(UsesColor('dumb', None, '1'))
     self.assert_(not UsesColor('xterm', None, 'f'))
     self.assert_(not UsesColor('xterm', None, 'false'))
     self.assert_(not UsesColor('xterm', None, '0'))
     self.assert_(not UsesColor('xterm', None, 'unknown'))
def gtest_color_test.GTestColorTest.testAliasesOfYesAndNo (self)
Tests using aliases in specifying --gtest_color.
Definition at line 115 of file gtest_color_test.py.
References gtest_test_utils.Main(), gtest_color_test.GTestColorTest.testAliasesOfYesAndNo(), and gtest_color_test.UsesColor().
   def testAliasesOfYesAndNo(self):
     """Tests using aliases in specifying --gtest_color."""
     self.assert_(UsesColor('dumb', None, 'true'))
     self.assert_(UsesColor('dumb', None, 'YES'))
     self.assert_(UsesColor('dumb', None, 'T'))
     self.assert_(UsesColor('dumb', None, '1'))
     self.assert_(not UsesColor('xterm', None, 'f'))
     self.assert_(not UsesColor('xterm', None, 'false'))
     self.assert_(not UsesColor('xterm', None, '0'))
     self.assert_(not UsesColor('xterm', None, 'unknown'))
def gtest_color_test.GTestColorTest.testEnvVarAndFlag (self)
Tests the case when there are both GTEST_COLOR and --gtest_color.
Definition at line 108 of file gtest_color_test.py.
References gtest_color_test.GTestColorTest.testEnvVarAndFlag(), and gtest_color_test.UsesColor().
   def testEnvVarAndFlag(self):
     """Tests the case when there are both GTEST_COLOR and --gtest_color."""
     self.assert_(not UsesColor('xterm-color', 'no', 'no'))
     self.assert_(UsesColor('dumb', 'no', 'yes'))
     self.assert_(UsesColor('xterm-color', 'no', 'auto'))
def gtest_color_test.GTestColorTest.testEnvVarAndFlag (self)
Tests the case when there are both GTEST_COLOR and --gtest_color.
Definition at line 108 of file gtest_color_test.py.
References gtest_color_test.UsesColor().
Referenced by gtest_color_test.GTestColorTest.testEnvVarAndFlag().
   def testEnvVarAndFlag(self):
     """Tests the case when there are both GTEST_COLOR and --gtest_color."""
     self.assert_(not UsesColor('xterm-color', 'no', 'no'))
     self.assert_(UsesColor('dumb', 'no', 'yes'))
     self.assert_(UsesColor('xterm-color', 'no', 'auto'))
def gtest_color_test.GTestColorTest.testEnvVarAndFlag (self)
Tests the case when there are both GTEST_COLOR and --gtest_color.
Definition at line 108 of file gtest_color_test.py.
References gtest_color_test.GTestColorTest.testEnvVarAndFlag(), and gtest_color_test.UsesColor().
   def testEnvVarAndFlag(self):
     """Tests the case when there are both GTEST_COLOR and --gtest_color."""
     self.assert_(not UsesColor('xterm-color', 'no', 'no'))
     self.assert_(UsesColor('dumb', 'no', 'yes'))
     self.assert_(UsesColor('xterm-color', 'no', 'auto'))
def gtest_color_test.GTestColorTest.testEnvVarOnly (self)
Tests the case when there's GTEST_COLOR but not --gtest_color.
Definition at line 97 of file gtest_color_test.py.
References gtest_color_test.GTestColorTest.testEnvVarOnly(), and gtest_color_test.UsesColor().
   def testEnvVarOnly(self):
     """Tests the case when there's GTEST_COLOR but not --gtest_color."""
     self.assert_(not UsesColor('dumb', 'no', None))
     self.assert_(not UsesColor('xterm-color', 'no', None))
     if not IS_WINDOWS:
       self.assert_(not UsesColor('dumb', 'auto', None))
     self.assert_(UsesColor('xterm-color', 'auto', None))
     self.assert_(UsesColor('dumb', 'yes', None))
     self.assert_(UsesColor('xterm-color', 'yes', None))
def gtest_color_test.GTestColorTest.testEnvVarOnly (self)
Tests the case when there's GTEST_COLOR but not --gtest_color.
Definition at line 97 of file gtest_color_test.py.
References gtest_color_test.GTestColorTest.testEnvVarOnly(), and gtest_color_test.UsesColor().
   def testEnvVarOnly(self):
     """Tests the case when there's GTEST_COLOR but not --gtest_color."""
     self.assert_(not UsesColor('dumb', 'no', None))
     self.assert_(not UsesColor('xterm-color', 'no', None))
     if not IS_WINDOWS:
       self.assert_(not UsesColor('dumb', 'auto', None))
     self.assert_(UsesColor('xterm-color', 'auto', None))
     self.assert_(UsesColor('dumb', 'yes', None))
     self.assert_(UsesColor('xterm-color', 'yes', None))
def gtest_color_test.GTestColorTest.testEnvVarOnly (self)
Tests the case when there's GTEST_COLOR but not --gtest_color.
Definition at line 97 of file gtest_color_test.py.
References gtest_color_test.UsesColor().
Referenced by gtest_color_test.GTestColorTest.testEnvVarOnly().
   def testEnvVarOnly(self):
     """Tests the case when there's GTEST_COLOR but not --gtest_color."""
     self.assert_(not UsesColor('dumb', 'no', None))
     self.assert_(not UsesColor('xterm-color', 'no', None))
     if not IS_WINDOWS:
       self.assert_(not UsesColor('dumb', 'auto', None))
     self.assert_(UsesColor('xterm-color', 'auto', None))
     self.assert_(UsesColor('dumb', 'yes', None))
     self.assert_(UsesColor('xterm-color', 'yes', None))
def gtest_color_test.GTestColorTest.testFlagOnly (self)
Tests the case when there's --gtest_color but not GTEST_COLOR.
Definition at line 86 of file gtest_color_test.py.
References gtest_color_test.GTestColorTest.testFlagOnly(), and gtest_color_test.UsesColor().
   def testFlagOnly(self):
     """Tests the case when there's --gtest_color but not GTEST_COLOR."""
     self.assert_(not UsesColor('dumb', None, 'no'))
     self.assert_(not UsesColor('xterm-color', None, 'no'))
     if not IS_WINDOWS:
       self.assert_(not UsesColor('emacs', None, 'auto'))
     self.assert_(UsesColor('xterm', None, 'auto'))
     self.assert_(UsesColor('dumb', None, 'yes'))
     self.assert_(UsesColor('xterm', None, 'yes'))
def gtest_color_test.GTestColorTest.testFlagOnly (self)
Tests the case when there's --gtest_color but not GTEST_COLOR.
Definition at line 86 of file gtest_color_test.py.
References gtest_color_test.GTestColorTest.testFlagOnly(), and gtest_color_test.UsesColor().
   def testFlagOnly(self):
     """Tests the case when there's --gtest_color but not GTEST_COLOR."""
     self.assert_(not UsesColor('dumb', None, 'no'))
     self.assert_(not UsesColor('xterm-color', None, 'no'))
     if not IS_WINDOWS:
       self.assert_(not UsesColor('emacs', None, 'auto'))
     self.assert_(UsesColor('xterm', None, 'auto'))
     self.assert_(UsesColor('dumb', None, 'yes'))
     self.assert_(UsesColor('xterm', None, 'yes'))
def gtest_color_test.GTestColorTest.testFlagOnly (self)
Tests the case when there's --gtest_color but not GTEST_COLOR.
Definition at line 86 of file gtest_color_test.py.
References gtest_color_test.UsesColor().
Referenced by gtest_color_test.GTestColorTest.testFlagOnly().
   def testFlagOnly(self):
     """Tests the case when there's --gtest_color but not GTEST_COLOR."""
     self.assert_(not UsesColor('dumb', None, 'no'))
     self.assert_(not UsesColor('xterm-color', None, 'no'))
     if not IS_WINDOWS:
       self.assert_(not UsesColor('emacs', None, 'auto'))
     self.assert_(UsesColor('xterm', None, 'auto'))
     self.assert_(UsesColor('dumb', None, 'yes'))
     self.assert_(UsesColor('xterm', None, 'yes'))
def gtest_color_test.GTestColorTest.testNoEnvVarNoFlag (self)
Tests the case when there's neither GTEST_COLOR nor --gtest_color.
Definition at line 71 of file gtest_color_test.py.
References gtest_color_test.UsesColor().
Referenced by gtest_color_test.GTestColorTest.testNoEnvVarNoFlag().
   def testNoEnvVarNoFlag(self):
     """Tests the case when there's neither GTEST_COLOR nor --gtest_color."""
     if not IS_WINDOWS:
       self.assert_(not UsesColor('dumb', None, None))
       self.assert_(not UsesColor('emacs', None, None))
       self.assert_(not UsesColor('xterm-mono', None, None))
       self.assert_(not UsesColor('unknown', None, None))
       self.assert_(not UsesColor(None, None, None))
     self.assert_(UsesColor('linux', None, None))
     self.assert_(UsesColor('cygwin', None, None))
     self.assert_(UsesColor('xterm', None, None))
     self.assert_(UsesColor('xterm-color', None, None))
     self.assert_(UsesColor('xterm-256color', None, None))
def gtest_color_test.GTestColorTest.testNoEnvVarNoFlag (self)
Tests the case when there's neither GTEST_COLOR nor --gtest_color.
Definition at line 71 of file gtest_color_test.py.
References gtest_color_test.GTestColorTest.testNoEnvVarNoFlag(), and gtest_color_test.UsesColor().
   def testNoEnvVarNoFlag(self):
     """Tests the case when there's neither GTEST_COLOR nor --gtest_color."""
     if not IS_WINDOWS:
       self.assert_(not UsesColor('dumb', None, None))
       self.assert_(not UsesColor('emacs', None, None))
       self.assert_(not UsesColor('xterm-mono', None, None))
       self.assert_(not UsesColor('unknown', None, None))
       self.assert_(not UsesColor(None, None, None))
     self.assert_(UsesColor('linux', None, None))
     self.assert_(UsesColor('cygwin', None, None))
     self.assert_(UsesColor('xterm', None, None))
     self.assert_(UsesColor('xterm-color', None, None))
     self.assert_(UsesColor('xterm-256color', None, None))
def gtest_color_test.GTestColorTest.testNoEnvVarNoFlag (self)
Tests the case when there's neither GTEST_COLOR nor --gtest_color.
Definition at line 71 of file gtest_color_test.py.
References gtest_color_test.GTestColorTest.testNoEnvVarNoFlag(), and gtest_color_test.UsesColor().
   def testNoEnvVarNoFlag(self):
     """Tests the case when there's neither GTEST_COLOR nor --gtest_color."""
     if not IS_WINDOWS:
       self.assert_(not UsesColor('dumb', None, None))
       self.assert_(not UsesColor('emacs', None, None))
       self.assert_(not UsesColor('xterm-mono', None, None))
       self.assert_(not UsesColor('unknown', None, None))
       self.assert_(not UsesColor(None, None, None))
     self.assert_(UsesColor('linux', None, None))
     self.assert_(UsesColor('cygwin', None, None))
     self.assert_(UsesColor('xterm', None, None))
     self.assert_(UsesColor('xterm-color', None, None))
     self.assert_(UsesColor('xterm-256color', None, None))
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest_color_test.py