proxygen: folly::detail::BufferedDigest< DigestT, ClockT > Class Template Reference
folly::detail::BufferedDigest< DigestT, ClockT > Class Template Reference
#include <BufferedStat.h>
Public Types
using TimePoint = typename ClockT::time_point
Public Types inherited from folly::detail::BufferedStat< DigestT, ClockT >
using TimePoint = typename ClockT::time_point
Public Member Functions
BufferedDigest (typename ClockT::duration bufferDuration, size_t bufferSize, size_t digestSize)
DigestT get (TimePoint now=ClockT::now())
void onNewDigest (DigestT digest, TimePoint newExpiry, TimePoint oldExpiry, const std::unique_lock< SharedMutex > &g) final
Public Member Functions inherited from folly::detail::BufferedStat< DigestT, ClockT >
BufferedStat ()=delete
BufferedStat (typename ClockT::duration bufferDuration, size_t bufferSize, size_t digestSize)
virtual ~BufferedStat ()
void append (double value, TimePoint now=ClockT::now())
void flush ()
Private Attributes
DigestT digest_
Additional Inherited Members
Protected Member Functions inherited from folly::detail::BufferedStat< DigestT, ClockT >
std::unique_lock< SharedMutex > updateIfExpired (TimePoint now)
std::unique_lock< SharedMutex > update ()
Protected Attributes inherited from folly::detail::BufferedStat< DigestT, ClockT >
const ClockT::duration bufferDuration_
std::atomic< TimePointHolder > expiry_
SharedMutex mutex_
Detailed Description
template<typename DigestT, typename ClockT>
class folly::detail::BufferedDigest< DigestT, ClockT >
Definition at line 100 of file BufferedStat.h.
Member Typedef Documentation
template<typename DigestT, typename ClockT> using folly::detail::BufferedDigest< DigestT, ClockT >::TimePoint = typename ClockT::time_point
Definition at line 102 of file BufferedStat.h.
Constructor & Destructor Documentation
template<typename DigestT , typename ClockT> folly::detail::BufferedDigest< DigestT, ClockT >::BufferedDigest (typename ClockT::duration bufferDuration, size_t bufferSize, size_t digestSize)
Definition at line 88 of file BufferedStat-defs.h.
     : BufferedStat<DigestT, ClockT>(bufferDuration, bufferSize, digestSize),
       digest_(digestSize) {}
Member Function Documentation
template<typename DigestT , typename ClockT > DigestT folly::detail::BufferedDigest< DigestT, ClockT >::get (TimePoint now = ClockT::now())
Definition at line 96 of file BufferedStat-defs.h.
References folly::detail::BufferedDigest< DigestT, ClockT >::digest_, g(), and folly::detail::BufferedStat< DigestT, ClockT >::updateIfExpired().
{
   auto g = this->updateIfExpired(now);
   return digest_;
 }
template<typename DigestT, typename ClockT > void folly::detail::BufferedDigest< DigestT, ClockT >::onNewDigest (DigestT digest, TimePoint newExpiry, TimePoint oldExpiry, const std::unique_lock< SharedMutex > & g) final virtual
Implements folly::detail::BufferedStat< DigestT, ClockT >.
Definition at line 102 of file BufferedStat-defs.h.
References a, folly::detail::BufferedDigest< DigestT, ClockT >::digest_, merge(), and folly::gen::move.
{
   std::array<DigestT, 2> a{{digest_, std::move(digest)}};
   digest_ = DigestT::merge(a);
 }
Member Data Documentation
template<typename DigestT, typename ClockT> DigestT folly::detail::BufferedDigest< DigestT, ClockT >::digest_ private
Definition at line 118 of file BufferedStat.h.
Referenced by folly::detail::BufferedDigest< DigestT, ClockT >::get(), and folly::detail::BufferedDigest< DigestT, ClockT >::onNewDigest().
The documentation for this class was generated from the following files:
proxygen/folly/folly/stats/detail/BufferedStat.h
proxygen/folly/folly/stats/detail/BufferedStat-defs.h