proxygen: testing::internal::TypedExpectation< F > Class Template Reference
testing::internal::TypedExpectation< F > Class Template Reference
#include <gmock-spec-builders.h>
Public Types
typedef Function< F >::ArgumentTuple ArgumentTuple
typedef Function< F >::ArgumentMatcherTuple ArgumentMatcherTuple
typedef Function< F >::Result Result
typedef Function< F >::ArgumentTuple ArgumentTuple
typedef Function< F >::ArgumentMatcherTuple ArgumentMatcherTuple
typedef Function< F >::Result Result
typedef Function< F >::ArgumentTuple ArgumentTuple
typedef Function< F >::ArgumentMatcherTuple ArgumentMatcherTuple
typedef Function< F >::Result Result
Public Member Functions
TypedExpectation (FunctionMockerBase< F > *owner, const char *a_file, int a_line, const string &a_source_text, const ArgumentMatcherTuple &m)
virtual ~TypedExpectation ()
TypedExpectation & With (const Matcher< const ArgumentTuple & > &m)
TypedExpectation & Times (const Cardinality &a_cardinality)
TypedExpectation & Times (int n)
TypedExpectation & InSequence (const Sequence &s)
TypedExpectation & InSequence (const Sequence &s1, const Sequence &s2)
TypedExpectation & InSequence (const Sequence &s1, const Sequence &s2, const Sequence &s3)
TypedExpectation & InSequence (const Sequence &s1, const Sequence &s2, const Sequence &s3, const Sequence &s4)
TypedExpectation & InSequence (const Sequence &s1, const Sequence &s2, const Sequence &s3, const Sequence &s4, const Sequence &s5)
TypedExpectation & After (const ExpectationSet &s)
TypedExpectation & After (const ExpectationSet &s1, const ExpectationSet &s2)
TypedExpectation & After (const ExpectationSet &s1, const ExpectationSet &s2, const ExpectationSet &s3)
TypedExpectation & After (const ExpectationSet &s1, const ExpectationSet &s2, const ExpectationSet &s3, const ExpectationSet &s4)
TypedExpectation & After (const ExpectationSet &s1, const ExpectationSet &s2, const ExpectationSet &s3, const ExpectationSet &s4, const ExpectationSet &s5)
TypedExpectation & WillOnce (const Action< F > &action)
TypedExpectation & WillRepeatedly (const Action< F > &action)
TypedExpectation & RetiresOnSaturation ()
const ArgumentMatcherTuple & matchers () const
const Matcher< const ArgumentTuple & > & extra_matcher () const
const Action< F > & repeated_action () const
virtual void MaybeDescribeExtraMatcherTo (::std::ostream *os)
TypedExpectation (FunctionMockerBase< F > *owner, const char *a_file, int a_line, const string &a_source_text, const ArgumentMatcherTuple &m)
virtual ~TypedExpectation ()
TypedExpectation & With (const Matcher< const ArgumentTuple & > &m)
TypedExpectation & Times (const Cardinality &a_cardinality)
TypedExpectation & Times (int n)
TypedExpectation & InSequence (const Sequence &s)
TypedExpectation & InSequence (const Sequence &s1, const Sequence &s2)
TypedExpectation & InSequence (const Sequence &s1, const Sequence &s2, const Sequence &s3)
TypedExpectation & InSequence (const Sequence &s1, const Sequence &s2, const Sequence &s3, const Sequence &s4)
TypedExpectation & InSequence (const Sequence &s1, const Sequence &s2, const Sequence &s3, const Sequence &s4, const Sequence &s5)
TypedExpectation & After (const ExpectationSet &s)
TypedExpectation & After (const ExpectationSet &s1, const ExpectationSet &s2)
TypedExpectation & After (const ExpectationSet &s1, const ExpectationSet &s2, const ExpectationSet &s3)
TypedExpectation & After (const ExpectationSet &s1, const ExpectationSet &s2, const ExpectationSet &s3, const ExpectationSet &s4)
TypedExpectation & After (const ExpectationSet &s1, const ExpectationSet &s2, const ExpectationSet &s3, const ExpectationSet &s4, const ExpectationSet &s5)
TypedExpectation & WillOnce (const Action< F > &action)
TypedExpectation & WillRepeatedly (const Action< F > &action)
TypedExpectation & RetiresOnSaturation ()
const ArgumentMatcherTuple & matchers () const
const Matcher< const ArgumentTuple & > & extra_matcher () const
const Action< F > & repeated_action () const
virtual void MaybeDescribeExtraMatcherTo (::std::ostream *os)
TypedExpectation (FunctionMockerBase< F > *owner, const char *a_file, int a_line, const string &a_source_text, const ArgumentMatcherTuple &m)
virtual ~TypedExpectation ()
TypedExpectation & With (const Matcher< const ArgumentTuple & > &m)
TypedExpectation & Times (const Cardinality &a_cardinality)
TypedExpectation & Times (int n)
TypedExpectation & InSequence (const Sequence &s)
TypedExpectation & InSequence (const Sequence &s1, const Sequence &s2)
TypedExpectation & InSequence (const Sequence &s1, const Sequence &s2, const Sequence &s3)
TypedExpectation & InSequence (const Sequence &s1, const Sequence &s2, const Sequence &s3, const Sequence &s4)
TypedExpectation & InSequence (const Sequence &s1, const Sequence &s2, const Sequence &s3, const Sequence &s4, const Sequence &s5)
TypedExpectation & After (const ExpectationSet &s)
TypedExpectation & After (const ExpectationSet &s1, const ExpectationSet &s2)
TypedExpectation & After (const ExpectationSet &s1, const ExpectationSet &s2, const ExpectationSet &s3)
TypedExpectation & After (const ExpectationSet &s1, const ExpectationSet &s2, const ExpectationSet &s3, const ExpectationSet &s4)
TypedExpectation & After (const ExpectationSet &s1, const ExpectationSet &s2, const ExpectationSet &s3, const ExpectationSet &s4, const ExpectationSet &s5)
TypedExpectation & WillOnce (const Action< F > &action)
TypedExpectation & WillRepeatedly (const Action< F > &action)
TypedExpectation & RetiresOnSaturation ()
const ArgumentMatcherTuple & matchers () const
const Matcher< const ArgumentTuple & > & extra_matcher () const
const Action< F > & repeated_action () const
virtual void MaybeDescribeExtraMatcherTo (::std::ostream *os)
Public Member Functions inherited from testing::internal::ExpectationBase
ExpectationBase (const char *file, int line, const string &source_text)
virtual ~ExpectationBase ()
const char * file () const
int line () const
const char * source_text () const
const Cardinality & cardinality () const
void DescribeLocationTo (::std::ostream *os) const
void DescribeCallCountTo (::std::ostream *os) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
ExpectationBase (const char *file, int line, const string &source_text)
virtual ~ExpectationBase ()
const char * file () const
int line () const
const char * source_text () const
const Cardinality & cardinality () const
void DescribeLocationTo (::std::ostream *os) const
void DescribeCallCountTo (::std::ostream *os) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
ExpectationBase (const char *file, int line, const string &source_text)
virtual ~ExpectationBase ()
const char * file () const
int line () const
const char * source_text () const
const Cardinality & cardinality () const
void DescribeLocationTo (::std::ostream *os) const
void DescribeCallCountTo (::std::ostream *os) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
Private Member Functions
virtual Expectation GetHandle ()
bool Matches (const ArgumentTuple &args) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool ShouldHandleArguments (const ArgumentTuple &args) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void ExplainMatchResultTo (const ArgumentTuple &args,::std::ostream *os) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
const Action< F > & GetCurrentAction (const FunctionMockerBase< F > *mocker, const ArgumentTuple &args) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
const Action< F > * GetActionForArguments (const FunctionMockerBase< F > *mocker, const ArgumentTuple &args,::std::ostream *what,::std::ostream *why) GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TypedExpectation)
virtual Expectation GetHandle ()
bool Matches (const ArgumentTuple &args) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool ShouldHandleArguments (const ArgumentTuple &args) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void ExplainMatchResultTo (const ArgumentTuple &args,::std::ostream *os) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
const Action< F > & GetCurrentAction (const FunctionMockerBase< F > *mocker, const ArgumentTuple &args) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
const Action< F > * GetActionForArguments (const FunctionMockerBase< F > *mocker, const ArgumentTuple &args,::std::ostream *what,::std::ostream *why) GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TypedExpectation)
virtual Expectation GetHandle ()
bool Matches (const ArgumentTuple &args) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool ShouldHandleArguments (const ArgumentTuple &args) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void ExplainMatchResultTo (const ArgumentTuple &args,::std::ostream *os) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
const Action< F > & GetCurrentAction (const FunctionMockerBase< F > *mocker, const ArgumentTuple &args) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
const Action< F > * GetActionForArguments (const FunctionMockerBase< F > *mocker, const ArgumentTuple &args,::std::ostream *what,::std::ostream *why) GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TypedExpectation)
Private Attributes
FunctionMockerBase< F > *const owner_
ArgumentMatcherTuple matchers_
Matcher< const ArgumentTuple & > extra_matcher_
Action< F > repeated_action_
Friends
template<typename Function >
class FunctionMockerBase
template<typename Function >
class FunctionMockerBase
template<typename Function >
class FunctionMockerBase
Additional Inherited Members
Protected Types inherited from testing::internal::ExpectationBase
enum Clause {
kNone, kWith, kTimes, kInSequence,
kAfter, kWillOnce, kWillRepeatedly, kRetiresOnSaturation,
kNone, kWith, kTimes, kInSequence,
kAfter, kWillOnce, kWillRepeatedly, kRetiresOnSaturation,
kNone, kWith, kTimes, kInSequence,
kAfter, kWillOnce, kWillRepeatedly, kRetiresOnSaturation
}
enum Clause {
kNone, kWith, kTimes, kInSequence,
kAfter, kWillOnce, kWillRepeatedly, kRetiresOnSaturation,
kNone, kWith, kTimes, kInSequence,
kAfter, kWillOnce, kWillRepeatedly, kRetiresOnSaturation,
kNone, kWith, kTimes, kInSequence,
kAfter, kWillOnce, kWillRepeatedly, kRetiresOnSaturation
}
enum Clause {
kNone, kWith, kTimes, kInSequence,
kAfter, kWillOnce, kWillRepeatedly, kRetiresOnSaturation,
kNone, kWith, kTimes, kInSequence,
kAfter, kWillOnce, kWillRepeatedly, kRetiresOnSaturation,
kNone, kWith, kTimes, kInSequence,
kAfter, kWillOnce, kWillRepeatedly, kRetiresOnSaturation
}
typedef std::vector< const void * > UntypedActions
typedef std::vector< const void * > UntypedActions
typedef std::vector< const void * > UntypedActions
Protected Member Functions inherited from testing::internal::ExpectationBase
void AssertSpecProperty (bool property, const string &failure_message) const
void ExpectSpecProperty (bool property, const string &failure_message) const
void SpecifyCardinality (const Cardinality &cardinality)
bool cardinality_specified () const
void set_cardinality (const Cardinality &a_cardinality)
void RetireAllPreRequisites () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool is_retired () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void Retire () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool IsSatisfied () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool IsSaturated () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool IsOverSaturated () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool AllPrerequisitesAreSatisfied () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void FindUnsatisfiedPrerequisites (ExpectationSet *result) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
int call_count () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void IncrementCallCount () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void CheckActionCountIfNotDone () const GTEST_LOCK_EXCLUDED_(mutex_)
void UntypedTimes (const Cardinality &a_cardinality)
GTEST_DISALLOW_ASSIGN_ (ExpectationBase)
void AssertSpecProperty (bool property, const string &failure_message) const
void ExpectSpecProperty (bool property, const string &failure_message) const
void SpecifyCardinality (const Cardinality &cardinality)
bool cardinality_specified () const
void set_cardinality (const Cardinality &a_cardinality)
void RetireAllPreRequisites () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool is_retired () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void Retire () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool IsSatisfied () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool IsSaturated () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool IsOverSaturated () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool AllPrerequisitesAreSatisfied () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void FindUnsatisfiedPrerequisites (ExpectationSet *result) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
int call_count () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void IncrementCallCount () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void CheckActionCountIfNotDone () const GTEST_LOCK_EXCLUDED_(mutex_)
void UntypedTimes (const Cardinality &a_cardinality)
GTEST_DISALLOW_ASSIGN_ (ExpectationBase)
void AssertSpecProperty (bool property, const string &failure_message) const
void ExpectSpecProperty (bool property, const string &failure_message) const
void SpecifyCardinality (const Cardinality &cardinality)
bool cardinality_specified () const
void set_cardinality (const Cardinality &a_cardinality)
void RetireAllPreRequisites () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool is_retired () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void Retire () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool IsSatisfied () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool IsSaturated () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool IsOverSaturated () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool AllPrerequisitesAreSatisfied () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void FindUnsatisfiedPrerequisites (ExpectationSet *result) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
int call_count () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void IncrementCallCount () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void CheckActionCountIfNotDone () const GTEST_LOCK_EXCLUDED_(mutex_)
void UntypedTimes (const Cardinality &a_cardinality)
GTEST_DISALLOW_ASSIGN_ (ExpectationBase)
Protected Attributes inherited from testing::internal::ExpectationBase
const char * file_
int line_
const string source_text_
bool cardinality_specified_
Cardinality cardinality_
ExpectationSet immediate_prerequisites_
int call_count_
bool retired_
UntypedActions untyped_actions_
bool extra_matcher_specified_
bool repeated_action_specified_
bool retires_on_saturation_
Clause last_clause_
bool action_count_checked_
Mutex mutex_
Detailed Description
template<typename F>
class testing::internal::TypedExpectation< F >
Definition at line 99 of file gmock-spec-builders.h.
Member Typedef Documentation
template<typename F> typedef Function<F>::ArgumentMatcherTuple testing::internal::TypedExpectation< F >::ArgumentMatcherTuple
Definition at line 880 of file gmock-spec-builders.h.
template<typename F> typedef Function<F>::ArgumentMatcherTuple testing::internal::TypedExpectation< F >::ArgumentMatcherTuple
Definition at line 880 of file gmock-spec-builders.h.
template<typename F> typedef Function<F>::ArgumentMatcherTuple testing::internal::TypedExpectation< F >::ArgumentMatcherTuple
Definition at line 880 of file gmock-spec-builders.h.
template<typename F> typedef Function<F>::ArgumentTuple testing::internal::TypedExpectation< F >::ArgumentTuple
Definition at line 879 of file gmock-spec-builders.h.
template<typename F> typedef Function<F>::ArgumentTuple testing::internal::TypedExpectation< F >::ArgumentTuple
Definition at line 879 of file gmock-spec-builders.h.
template<typename F> typedef Function<F>::ArgumentTuple testing::internal::TypedExpectation< F >::ArgumentTuple
Definition at line 879 of file gmock-spec-builders.h.
template<typename F> typedef Function<F>::Result testing::internal::TypedExpectation< F >::Result
Definition at line 881 of file gmock-spec-builders.h.
template<typename F> typedef Function<F>::Result testing::internal::TypedExpectation< F >::Result
Definition at line 881 of file gmock-spec-builders.h.
template<typename F> typedef Function<F>::Result testing::internal::TypedExpectation< F >::Result
Definition at line 881 of file gmock-spec-builders.h.
Constructor & Destructor Documentation
template<typename F> testing::internal::TypedExpectation< F >::TypedExpectation (FunctionMockerBase< F > * owner, const char * a_file, int a_line, const string & a_source_text, const ArgumentMatcherTuple & m) inline
Definition at line 883 of file gmock-spec-builders.h.
       : ExpectationBase(a_file, a_line, a_source_text),
         owner_(owner),
         matchers_(m),
         // By default, extra_matcher_ should match anything.  However,
         // we cannot initialize it with _ as that triggers a compiler
         // bug in Symbian's C++ compiler (cannot decide between two
         // overloaded constructors of Matcher<const ArgumentTuple&>).
         extra_matcher_(A<const ArgumentTuple&>()),
         repeated_action_(DoDefault()) {}
template<typename F> virtual testing::internal::TypedExpectation< F >::~TypedExpectation () inline virtual
Definition at line 896 of file gmock-spec-builders.h.
{
     // Check the validity of the action count if it hasn't been done
     // yet (for example, if the expectation was never used).
     CheckActionCountIfNotDone();
     for (UntypedActions::const_iterator it = untyped_actions_.begin();
          it != untyped_actions_.end(); ++it) {
       delete static_cast<const Action<F>*>(*it);
     }
   }
template<typename F> testing::internal::TypedExpectation< F >::TypedExpectation (FunctionMockerBase< F > * owner, const char * a_file, int a_line, const string & a_source_text, const ArgumentMatcherTuple & m) inline
Definition at line 883 of file gmock-spec-builders.h.
       : ExpectationBase(a_file, a_line, a_source_text),
         owner_(owner),
         matchers_(m),
         // By default, extra_matcher_ should match anything.  However,
         // we cannot initialize it with _ as that triggers a compiler
         // bug in Symbian's C++ compiler (cannot decide between two
         // overloaded constructors of Matcher<const ArgumentTuple&>).
         extra_matcher_(A<const ArgumentTuple&>()),
         repeated_action_(DoDefault()) {}
template<typename F> virtual testing::internal::TypedExpectation< F >::~TypedExpectation () inline virtual
Definition at line 896 of file gmock-spec-builders.h.
{
     // Check the validity of the action count if it hasn't been done
     // yet (for example, if the expectation was never used).
     CheckActionCountIfNotDone();
     for (UntypedActions::const_iterator it = untyped_actions_.begin();
          it != untyped_actions_.end(); ++it) {
       delete static_cast<const Action<F>*>(*it);
     }
   }
template<typename F> testing::internal::TypedExpectation< F >::TypedExpectation (FunctionMockerBase< F > * owner, const char * a_file, int a_line, const string & a_source_text, const ArgumentMatcherTuple & m) inline
Definition at line 883 of file gmock-spec-builders.h.
       : ExpectationBase(a_file, a_line, a_source_text),
         owner_(owner),
         matchers_(m),
         // By default, extra_matcher_ should match anything.  However,
         // we cannot initialize it with _ as that triggers a compiler
         // bug in Symbian's C++ compiler (cannot decide between two
         // overloaded constructors of Matcher<const ArgumentTuple&>).
         extra_matcher_(A<const ArgumentTuple&>()),
         repeated_action_(DoDefault()) {}
template<typename F> virtual testing::internal::TypedExpectation< F >::~TypedExpectation () inline virtual
Definition at line 896 of file gmock-spec-builders.h.
{
     // Check the validity of the action count if it hasn't been done
     // yet (for example, if the expectation was never used).
     CheckActionCountIfNotDone();
     for (UntypedActions::const_iterator it = untyped_actions_.begin();
          it != untyped_actions_.end(); ++it) {
       delete static_cast<const Action<F>*>(*it);
     }
   }
Member Function Documentation
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::After (const ExpectationSet & s) inline
Definition at line 964 of file gmock-spec-builders.h.
References testing::ExpectationSet::begin(), and testing::ExpectationSet::end().
Referenced by testing::internal::TypedExpectation< F >::After().
{
     ExpectSpecProperty(last_clause_ <= kAfter,
                        ".After() cannot appear after .WillOnce(),"
                        " .WillRepeatedly(), or "
                        ".RetiresOnSaturation().");
     last_clause_ = kAfter;
     for (ExpectationSet::const_iterator it = s.begin(); it != s.end(); ++it) {
       immediate_prerequisites_ += *it;
     }
     return *this;
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::After (const ExpectationSet & s) inline
Definition at line 964 of file gmock-spec-builders.h.
References testing::ExpectationSet::begin(), and testing::ExpectationSet::end().
{
     ExpectSpecProperty(last_clause_ <= kAfter,
                        ".After() cannot appear after .WillOnce(),"
                        " .WillRepeatedly(), or "
                        ".RetiresOnSaturation().");
     last_clause_ = kAfter;
     for (ExpectationSet::const_iterator it = s.begin(); it != s.end(); ++it) {
       immediate_prerequisites_ += *it;
     }
     return *this;
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::After (const ExpectationSet & s) inline
Definition at line 964 of file gmock-spec-builders.h.
References testing::ExpectationSet::begin(), and testing::ExpectationSet::end().
{
     ExpectSpecProperty(last_clause_ <= kAfter,
                        ".After() cannot appear after .WillOnce(),"
                        " .WillRepeatedly(), or "
                        ".RetiresOnSaturation().");
     last_clause_ = kAfter;
     for (ExpectationSet::const_iterator it = s.begin(); it != s.end(); ++it) {
       immediate_prerequisites_ += *it;
     }
     return *this;
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::After (const ExpectationSet & s1, const ExpectationSet & s2) inline
Definition at line 976 of file gmock-spec-builders.h.
References testing::internal::TypedExpectation< F >::After().
{
     return After(s1).After(s2);
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::After (const ExpectationSet & s1, const ExpectationSet & s2) inline
Definition at line 976 of file gmock-spec-builders.h.
References testing::internal::TypedExpectation< F >::After().
{
     return After(s1).After(s2);
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::After (const ExpectationSet & s1, const ExpectationSet & s2) inline
Definition at line 976 of file gmock-spec-builders.h.
References testing::internal::TypedExpectation< F >::After().
{
     return After(s1).After(s2);
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::After (const ExpectationSet & s1, const ExpectationSet & s2, const ExpectationSet & s3) inline
Definition at line 979 of file gmock-spec-builders.h.
References testing::internal::TypedExpectation< F >::After().
{
     return After(s1, s2).After(s3);
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::After (const ExpectationSet & s1, const ExpectationSet & s2, const ExpectationSet & s3) inline
Definition at line 979 of file gmock-spec-builders.h.
References testing::internal::TypedExpectation< F >::After().
{
     return After(s1, s2).After(s3);
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::After (const ExpectationSet & s1, const ExpectationSet & s2, const ExpectationSet & s3) inline
Definition at line 979 of file gmock-spec-builders.h.
References testing::internal::TypedExpectation< F >::After().
{
     return After(s1, s2).After(s3);
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::After (const ExpectationSet & s1, const ExpectationSet & s2, const ExpectationSet & s3, const ExpectationSet & s4) inline
Definition at line 983 of file gmock-spec-builders.h.
References testing::internal::TypedExpectation< F >::After().
{
     return After(s1, s2, s3).After(s4);
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::After (const ExpectationSet & s1, const ExpectationSet & s2, const ExpectationSet & s3, const ExpectationSet & s4) inline
Definition at line 983 of file gmock-spec-builders.h.
References testing::internal::TypedExpectation< F >::After().
{
     return After(s1, s2, s3).After(s4);
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::After (const ExpectationSet & s1, const ExpectationSet & s2, const ExpectationSet & s3, const ExpectationSet & s4) inline
Definition at line 983 of file gmock-spec-builders.h.
References testing::internal::TypedExpectation< F >::After().
{
     return After(s1, s2, s3).After(s4);
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::After (const ExpectationSet & s1, const ExpectationSet & s2, const ExpectationSet & s3, const ExpectationSet & s4, const ExpectationSet & s5) inline
Definition at line 987 of file gmock-spec-builders.h.
References testing::internal::TypedExpectation< F >::After().
{
     return After(s1, s2, s3, s4).After(s5);
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::After (const ExpectationSet & s1, const ExpectationSet & s2, const ExpectationSet & s3, const ExpectationSet & s4, const ExpectationSet & s5) inline
Definition at line 987 of file gmock-spec-builders.h.
References testing::internal::TypedExpectation< F >::After().
{
     return After(s1, s2, s3, s4).After(s5);
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::After (const ExpectationSet & s1, const ExpectationSet & s2, const ExpectationSet & s3, const ExpectationSet & s4, const ExpectationSet & s5) inline
Definition at line 987 of file gmock-spec-builders.h.
References testing::internal::TypedExpectation< F >::After().
{
     return After(s1, s2, s3, s4).After(s5);
   }
template<typename F> void testing::internal::TypedExpectation< F >::ExplainMatchResultTo (const ArgumentTuple & args, ::std::ostream * os) const inline private
Definition at line 1106 of file gmock-spec-builders.h.
References testing::ExpectationSet::begin(), testing::ExpectationSet::end(), testing::internal::ExplainMatchFailureTupleTo(), i, testing::Matches(), testing::internal::PrintIfNotEmpty(), testing::StringMatchResultListener::str(), and testing::internal::TupleMatches().
{
     g_gmock_mutex.AssertHeld();
     if (is_retired()) {
       *os << "         Expected: the expectation is active\n"
           << "           Actual: it is retired\n";
     } else if (!Matches(args)) {
       if (!TupleMatches(matchers_, args)) {
         ExplainMatchFailureTupleTo(matchers_, args, os);
       }
       StringMatchResultListener listener;
       if (!extra_matcher_.MatchAndExplain(args, &listener)) {
         *os << "    Expected args: ";
         extra_matcher_.DescribeTo(os);
         *os << "\n           Actual: don't match";
         internal::PrintIfNotEmpty(listener.str(), os);
         *os << "\n";
       }
     } else if (!AllPrerequisitesAreSatisfied()) {
       *os << "         Expected: all pre-requisites are satisfied\n"
           << "           Actual: the following immediate pre-requisites "
           << "are not satisfied:\n";
       ExpectationSet unsatisfied_prereqs;
       FindUnsatisfiedPrerequisites(&unsatisfied_prereqs);
       int i = 0;
       for (ExpectationSet::const_iterator it = unsatisfied_prereqs.begin();
            it != unsatisfied_prereqs.end(); ++it) {
         it->expectation_base()->DescribeLocationTo(os);
         *os << "pre-requisite #" << i++ << "\n";
       }
       *os << "                   (end of pre-requisites)\n";
     } else {
       // This line is here just for completeness' sake.  It will never
       // be executed as currently the ExplainMatchResultTo() function
       // is called only when the mock function call does NOT match the
       // expectation.
       *os << "The call matches the expectation.\n";
     }
   }
template<typename F> void testing::internal::TypedExpectation< F >::ExplainMatchResultTo (const ArgumentTuple & args, ::std::ostream * os) const inline private
Definition at line 1106 of file gmock-spec-builders.h.
References testing::ExpectationSet::begin(), testing::ExpectationSet::end(), testing::internal::ExplainMatchFailureTupleTo(), i, testing::Matches(), testing::internal::PrintIfNotEmpty(), testing::StringMatchResultListener::str(), and testing::internal::TupleMatches().
Referenced by testing::internal::FunctionMockerBase< R(A1, A2)>::PrintTriedExpectationsLocked().
{
     g_gmock_mutex.AssertHeld();
     if (is_retired()) {
       *os << "         Expected: the expectation is active\n"
           << "           Actual: it is retired\n";
     } else if (!Matches(args)) {
       if (!TupleMatches(matchers_, args)) {
         ExplainMatchFailureTupleTo(matchers_, args, os);
       }
       StringMatchResultListener listener;
       if (!extra_matcher_.MatchAndExplain(args, &listener)) {
         *os << "    Expected args: ";
         extra_matcher_.DescribeTo(os);
         *os << "\n           Actual: don't match";
         internal::PrintIfNotEmpty(listener.str(), os);
         *os << "\n";
       }
     } else if (!AllPrerequisitesAreSatisfied()) {
       *os << "         Expected: all pre-requisites are satisfied\n"
           << "           Actual: the following immediate pre-requisites "
           << "are not satisfied:\n";
       ExpectationSet unsatisfied_prereqs;
       FindUnsatisfiedPrerequisites(&unsatisfied_prereqs);
       int i = 0;
       for (ExpectationSet::const_iterator it = unsatisfied_prereqs.begin();
            it != unsatisfied_prereqs.end(); ++it) {
         it->expectation_base()->DescribeLocationTo(os);
         *os << "pre-requisite #" << i++ << "\n";
       }
       *os << "                   (end of pre-requisites)\n";
     } else {
       // This line is here just for completeness' sake.  It will never
       // be executed as currently the ExplainMatchResultTo() function
       // is called only when the mock function call does NOT match the
       // expectation.
       *os << "The call matches the expectation.\n";
     }
   }
template<typename F> void testing::internal::TypedExpectation< F >::ExplainMatchResultTo (const ArgumentTuple & args, ::std::ostream * os) const inline private
Definition at line 1106 of file gmock-spec-builders.h.
References testing::ExpectationSet::begin(), testing::ExpectationSet::end(), testing::internal::ExplainMatchFailureTupleTo(), i, testing::Matches(), testing::internal::PrintIfNotEmpty(), testing::StringMatchResultListener::str(), and testing::internal::TupleMatches().
{
     g_gmock_mutex.AssertHeld();
     if (is_retired()) {
       *os << "         Expected: the expectation is active\n"
           << "           Actual: it is retired\n";
     } else if (!Matches(args)) {
       if (!TupleMatches(matchers_, args)) {
         ExplainMatchFailureTupleTo(matchers_, args, os);
       }
       StringMatchResultListener listener;
       if (!extra_matcher_.MatchAndExplain(args, &listener)) {
         *os << "    Expected args: ";
         extra_matcher_.DescribeTo(os);
         *os << "\n           Actual: don't match";
         internal::PrintIfNotEmpty(listener.str(), os);
         *os << "\n";
       }
     } else if (!AllPrerequisitesAreSatisfied()) {
       *os << "         Expected: all pre-requisites are satisfied\n"
           << "           Actual: the following immediate pre-requisites "
           << "are not satisfied:\n";
       ExpectationSet unsatisfied_prereqs;
       FindUnsatisfiedPrerequisites(&unsatisfied_prereqs);
       int i = 0;
       for (ExpectationSet::const_iterator it = unsatisfied_prereqs.begin();
            it != unsatisfied_prereqs.end(); ++it) {
         it->expectation_base()->DescribeLocationTo(os);
         *os << "pre-requisite #" << i++ << "\n";
       }
       *os << "                   (end of pre-requisites)\n";
     } else {
       // This line is here just for completeness' sake.  It will never
       // be executed as currently the ExplainMatchResultTo() function
       // is called only when the mock function call does NOT match the
       // expectation.
       *os << "The call matches the expectation.\n";
     }
   }
template<typename F> const Matcher<const ArgumentTuple&>& testing::internal::TypedExpectation< F >::extra_matcher () const inline
Definition at line 1053 of file gmock-spec-builders.h.
{
     return extra_matcher_;
   }
template<typename F> const Matcher<const ArgumentTuple&>& testing::internal::TypedExpectation< F >::extra_matcher () const inline
Definition at line 1053 of file gmock-spec-builders.h.
{
     return extra_matcher_;
   }
template<typename F> const Matcher<const ArgumentTuple&>& testing::internal::TypedExpectation< F >::extra_matcher () const inline
Definition at line 1053 of file gmock-spec-builders.h.
{
     return extra_matcher_;
   }
template<typename F> const Action<F>* testing::internal::TypedExpectation< F >::GetActionForArguments (const FunctionMockerBase< F > * mocker, const ArgumentTuple & args, ::std::ostream * what, ::std::ostream * why) inline private
Definition at line 1188 of file gmock-spec-builders.h.
References GTEST_API_, GTEST_DISALLOW_COPY_AND_ASSIGN_, and testing::internal::LogWithLocation().
{
     g_gmock_mutex.AssertHeld();
     if (IsSaturated()) {
       // We have an excessive call.
       IncrementCallCount();
       *what << "Mock function called more times than expected - ";
       mocker->DescribeDefaultActionTo(args, what);
       DescribeCallCountTo(why);
       // TODO(wan@google.com): allow the user to control whether
       // unexpected calls should fail immediately or continue using a
       // flag --gmock_unexpected_calls_are_fatal.
       return NULL;
     }
     IncrementCallCount();
     RetireAllPreRequisites();
     if (retires_on_saturation_ && IsSaturated()) {
       Retire();
     }
     // Must be done after IncrementCount()!
     *what << "Mock function call matches " << source_text() <<"...\n";
     return &(GetCurrentAction(mocker, args));
   }
template<typename F> const Action<F>* testing::internal::TypedExpectation< F >::GetActionForArguments (const FunctionMockerBase< F > * mocker, const ArgumentTuple & args, ::std::ostream * what, ::std::ostream * why) inline private
Definition at line 1188 of file gmock-spec-builders.h.
Referenced by testing::internal::FunctionMockerBase< R(A1, A2)>::UntypedFindMatchingExpectation().
{
     g_gmock_mutex.AssertHeld();
     if (IsSaturated()) {
       // We have an excessive call.
       IncrementCallCount();
       *what << "Mock function called more times than expected - ";
       mocker->DescribeDefaultActionTo(args, what);
       DescribeCallCountTo(why);
       // TODO(wan@google.com): allow the user to control whether
       // unexpected calls should fail immediately or continue using a
       // flag --gmock_unexpected_calls_are_fatal.
       return NULL;
     }
     IncrementCallCount();
     RetireAllPreRequisites();
     if (retires_on_saturation_ && IsSaturated()) {
       Retire();
     }
     // Must be done after IncrementCount()!
     *what << "Mock function call matches " << source_text() <<"...\n";
     return &(GetCurrentAction(mocker, args));
   }
template<typename F> const Action<F>* testing::internal::TypedExpectation< F >::GetActionForArguments (const FunctionMockerBase< F > * mocker, const ArgumentTuple & args, ::std::ostream * what, ::std::ostream * why) inline private
Definition at line 1188 of file gmock-spec-builders.h.
References GTEST_API_, GTEST_DISALLOW_COPY_AND_ASSIGN_, and testing::internal::LogWithLocation().
{
     g_gmock_mutex.AssertHeld();
     if (IsSaturated()) {
       // We have an excessive call.
       IncrementCallCount();
       *what << "Mock function called more times than expected - ";
       mocker->DescribeDefaultActionTo(args, what);
       DescribeCallCountTo(why);
       // TODO(wan@google.com): allow the user to control whether
       // unexpected calls should fail immediately or continue using a
       // flag --gmock_unexpected_calls_are_fatal.
       return NULL;
     }
     IncrementCallCount();
     RetireAllPreRequisites();
     if (retires_on_saturation_ && IsSaturated()) {
       Retire();
     }
     // Must be done after IncrementCount()!
     *what << "Mock function call matches " << source_text() <<"...\n";
     return &(GetCurrentAction(mocker, args));
   }
template<typename F> const Action<F>& testing::internal::TypedExpectation< F >::GetCurrentAction (const FunctionMockerBase< F > * mocker, const ArgumentTuple & args) const inline private
Definition at line 1151 of file gmock-spec-builders.h.
References testing::internal::Assert(), count, testing::internal::kWarning, and testing::internal::Log().
{
     g_gmock_mutex.AssertHeld();
     const int count = call_count();
     Assert(count >= 1, __FILE__, __LINE__,
            "call_count() is <= 0 when GetCurrentAction() is "
            "called - this should never happen.");
     const int action_count = static_cast<int>(untyped_actions_.size());
     if (action_count > 0 && !repeated_action_specified_ &&
         count > action_count) {
       // If there is at least one WillOnce() and no WillRepeatedly(),
       // we warn the user when the WillOnce() clauses ran out.
       ::std::stringstream ss;
       DescribeLocationTo(&ss);
       ss << "Actions ran out in " << source_text() << "...\n"
          << "Called " << count << " times, but only "
          << action_count << " WillOnce()"
          << (action_count == 1 ? " is" : "s are") << " specified - ";
       mocker->DescribeDefaultActionTo(args, &ss);
       Log(kWarning, ss.str(), 1);
     }
     return count <= action_count ?
         *static_cast<const Action<F>*>(untyped_actions_[count - 1]) :
         repeated_action();
   }
template<typename F> const Action<F>& testing::internal::TypedExpectation< F >::GetCurrentAction (const FunctionMockerBase< F > * mocker, const ArgumentTuple & args) const inline private
Definition at line 1151 of file gmock-spec-builders.h.
References testing::internal::Assert(), count, testing::internal::kWarning, and testing::internal::Log().
{
     g_gmock_mutex.AssertHeld();
     const int count = call_count();
     Assert(count >= 1, __FILE__, __LINE__,
            "call_count() is <= 0 when GetCurrentAction() is "
            "called - this should never happen.");
     const int action_count = static_cast<int>(untyped_actions_.size());
     if (action_count > 0 && !repeated_action_specified_ &&
         count > action_count) {
       // If there is at least one WillOnce() and no WillRepeatedly(),
       // we warn the user when the WillOnce() clauses ran out.
       ::std::stringstream ss;
       DescribeLocationTo(&ss);
       ss << "Actions ran out in " << source_text() << "...\n"
          << "Called " << count << " times, but only "
          << action_count << " WillOnce()"
          << (action_count == 1 ? " is" : "s are") << " specified - ";
       mocker->DescribeDefaultActionTo(args, &ss);
       Log(kWarning, ss.str(), 1);
     }
     return count <= action_count ?
         *static_cast<const Action<F>*>(untyped_actions_[count - 1]) :
         repeated_action();
   }
template<typename F> const Action<F>& testing::internal::TypedExpectation< F >::GetCurrentAction (const FunctionMockerBase< F > * mocker, const ArgumentTuple & args) const inline private
Definition at line 1151 of file gmock-spec-builders.h.
References testing::internal::Assert(), count, testing::internal::kWarning, and testing::internal::Log().
{
     g_gmock_mutex.AssertHeld();
     const int count = call_count();
     Assert(count >= 1, __FILE__, __LINE__,
            "call_count() is <= 0 when GetCurrentAction() is "
            "called - this should never happen.");
     const int action_count = static_cast<int>(untyped_actions_.size());
     if (action_count > 0 && !repeated_action_specified_ &&
         count > action_count) {
       // If there is at least one WillOnce() and no WillRepeatedly(),
       // we warn the user when the WillOnce() clauses ran out.
       ::std::stringstream ss;
       DescribeLocationTo(&ss);
       ss << "Actions ran out in " << source_text() << "...\n"
          << "Called " << count << " times, but only "
          << action_count << " WillOnce()"
          << (action_count == 1 ? " is" : "s are") << " specified - ";
       mocker->DescribeDefaultActionTo(args, &ss);
       Log(kWarning, ss.str(), 1);
     }
     return count <= action_count ?
         *static_cast<const Action<F>*>(untyped_actions_[count - 1]) :
         repeated_action();
   }
template<typename F> virtual Expectation testing::internal::TypedExpectation< F >::GetHandle () inline private virtual
Implements testing::internal::ExpectationBase.
Definition at line 1076 of file gmock-spec-builders.h.
{
     return owner_->GetHandleOf(this);
   }
template<typename F> virtual Expectation testing::internal::TypedExpectation< F >::GetHandle () inline private virtual
Implements testing::internal::ExpectationBase.
Definition at line 1076 of file gmock-spec-builders.h.
{
     return owner_->GetHandleOf(this);
   }
template<typename F> virtual Expectation testing::internal::TypedExpectation< F >::GetHandle () inline private virtual
Implements testing::internal::ExpectationBase.
Definition at line 1076 of file gmock-spec-builders.h.
{
     return owner_->GetHandleOf(this);
   }
template<typename F> testing::internal::TypedExpectation< F >::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TypedExpectation< F >) private
template<typename F> testing::internal::TypedExpectation< F >::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TypedExpectation< F >) private
template<typename F> testing::internal::TypedExpectation< F >::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TypedExpectation< F >) private
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::InSequence (const Sequence & s) inline
Definition at line 936 of file gmock-spec-builders.h.
References testing::Sequence::AddExpectation().
{
     ExpectSpecProperty(last_clause_ <= kInSequence,
                        ".InSequence() cannot appear after .After(),"
                        " .WillOnce(), .WillRepeatedly(), or "
                        ".RetiresOnSaturation().");
     last_clause_ = kInSequence;
     s.AddExpectation(GetHandle());
     return *this;
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::InSequence (const Sequence & s) inline
Definition at line 936 of file gmock-spec-builders.h.
References testing::Sequence::AddExpectation().
{
     ExpectSpecProperty(last_clause_ <= kInSequence,
                        ".InSequence() cannot appear after .After(),"
                        " .WillOnce(), .WillRepeatedly(), or "
                        ".RetiresOnSaturation().");
     last_clause_ = kInSequence;
     s.AddExpectation(GetHandle());
     return *this;
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::InSequence (const Sequence & s) inline
Definition at line 936 of file gmock-spec-builders.h.
References testing::Sequence::AddExpectation().
{
     ExpectSpecProperty(last_clause_ <= kInSequence,
                        ".InSequence() cannot appear after .After(),"
                        " .WillOnce(), .WillRepeatedly(), or "
                        ".RetiresOnSaturation().");
     last_clause_ = kInSequence;
     s.AddExpectation(GetHandle());
     return *this;
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::InSequence (const Sequence & s1, const Sequence & s2) inline
Definition at line 946 of file gmock-spec-builders.h.
{
     return InSequence(s1).InSequence(s2);
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::InSequence (const Sequence & s1, const Sequence & s2) inline
Definition at line 946 of file gmock-spec-builders.h.
References testing::InSequence::InSequence().
{
     return InSequence(s1).InSequence(s2);
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::InSequence (const Sequence & s1, const Sequence & s2) inline
Definition at line 946 of file gmock-spec-builders.h.
{
     return InSequence(s1).InSequence(s2);
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::InSequence (const Sequence & s1, const Sequence & s2, const Sequence & s3) inline
Definition at line 949 of file gmock-spec-builders.h.
{
     return InSequence(s1, s2).InSequence(s3);
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::InSequence (const Sequence & s1, const Sequence & s2, const Sequence & s3) inline
Definition at line 949 of file gmock-spec-builders.h.
References testing::InSequence::InSequence().
{
     return InSequence(s1, s2).InSequence(s3);
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::InSequence (const Sequence & s1, const Sequence & s2, const Sequence & s3) inline
Definition at line 949 of file gmock-spec-builders.h.
{
     return InSequence(s1, s2).InSequence(s3);
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::InSequence (const Sequence & s1, const Sequence & s2, const Sequence & s3, const Sequence & s4) inline
Definition at line 953 of file gmock-spec-builders.h.
{
     return InSequence(s1, s2, s3).InSequence(s4);
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::InSequence (const Sequence & s1, const Sequence & s2, const Sequence & s3, const Sequence & s4) inline
Definition at line 953 of file gmock-spec-builders.h.
{
     return InSequence(s1, s2, s3).InSequence(s4);
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::InSequence (const Sequence & s1, const Sequence & s2, const Sequence & s3, const Sequence & s4) inline
Definition at line 953 of file gmock-spec-builders.h.
References testing::InSequence::InSequence().
{
     return InSequence(s1, s2, s3).InSequence(s4);
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::InSequence (const Sequence & s1, const Sequence & s2, const Sequence & s3, const Sequence & s4, const Sequence & s5) inline
Definition at line 957 of file gmock-spec-builders.h.
{
     return InSequence(s1, s2, s3, s4).InSequence(s5);
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::InSequence (const Sequence & s1, const Sequence & s2, const Sequence & s3, const Sequence & s4, const Sequence & s5) inline
Definition at line 957 of file gmock-spec-builders.h.
References testing::InSequence::InSequence().
{
     return InSequence(s1, s2, s3, s4).InSequence(s5);
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::InSequence (const Sequence & s1, const Sequence & s2, const Sequence & s3, const Sequence & s4, const Sequence & s5) inline
Definition at line 957 of file gmock-spec-builders.h.
{
     return InSequence(s1, s2, s3, s4).InSequence(s5);
   }
template<typename F> const ArgumentMatcherTuple& testing::internal::TypedExpectation< F >::matchers () const inline
Definition at line 1048 of file gmock-spec-builders.h.
{
     return matchers_;
   }
template<typename F> const ArgumentMatcherTuple& testing::internal::TypedExpectation< F >::matchers () const inline
Definition at line 1048 of file gmock-spec-builders.h.
{
     return matchers_;
   }
template<typename F> const ArgumentMatcherTuple& testing::internal::TypedExpectation< F >::matchers () const inline
Definition at line 1048 of file gmock-spec-builders.h.
{
     return matchers_;
   }
template<typename F> bool testing::internal::TypedExpectation< F >::Matches (const ArgumentTuple & args) const inline private
Definition at line 1085 of file gmock-spec-builders.h.
References testing::internal::TupleMatches().
{
     g_gmock_mutex.AssertHeld();
     return TupleMatches(matchers_, args) && extra_matcher_.Matches(args);
   }
template<typename F> bool testing::internal::TypedExpectation< F >::Matches (const ArgumentTuple & args) const inline private
Definition at line 1085 of file gmock-spec-builders.h.
References testing::internal::TupleMatches().
{
     g_gmock_mutex.AssertHeld();
     return TupleMatches(matchers_, args) && extra_matcher_.Matches(args);
   }
template<typename F> bool testing::internal::TypedExpectation< F >::Matches (const ArgumentTuple & args) const inline private
Definition at line 1085 of file gmock-spec-builders.h.
References testing::internal::TupleMatches().
{
     g_gmock_mutex.AssertHeld();
     return TupleMatches(matchers_, args) && extra_matcher_.Matches(args);
   }
template<typename F> virtual void testing::internal::TypedExpectation< F >::MaybeDescribeExtraMatcherTo (::std::ostream * os) inline virtual
Implements testing::internal::ExpectationBase.
Definition at line 1062 of file gmock-spec-builders.h.
{
     if (extra_matcher_specified_) {
       *os << "    Expected args: ";
       extra_matcher_.DescribeTo(os);
       *os << "\n";
     }
   }
template<typename F> virtual void testing::internal::TypedExpectation< F >::MaybeDescribeExtraMatcherTo (::std::ostream * os) inline virtual
Implements testing::internal::ExpectationBase.
Definition at line 1062 of file gmock-spec-builders.h.
{
     if (extra_matcher_specified_) {
       *os << "    Expected args: ";
       extra_matcher_.DescribeTo(os);
       *os << "\n";
     }
   }
template<typename F> virtual void testing::internal::TypedExpectation< F >::MaybeDescribeExtraMatcherTo (::std::ostream * os) inline virtual
Implements testing::internal::ExpectationBase.
Definition at line 1062 of file gmock-spec-builders.h.
{
     if (extra_matcher_specified_) {
       *os << "    Expected args: ";
       extra_matcher_.DescribeTo(os);
       *os << "\n";
     }
   }
template<typename F> const Action<F>& testing::internal::TypedExpectation< F >::repeated_action () const inline
Definition at line 1058 of file gmock-spec-builders.h.
 { return repeated_action_; }
template<typename F> const Action<F>& testing::internal::TypedExpectation< F >::repeated_action () const inline
Definition at line 1058 of file gmock-spec-builders.h.
 { return repeated_action_; }
template<typename F> const Action<F>& testing::internal::TypedExpectation< F >::repeated_action () const inline
Definition at line 1058 of file gmock-spec-builders.h.
 { return repeated_action_; }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::RetiresOnSaturation () inline
Definition at line 1033 of file gmock-spec-builders.h.
{
     ExpectSpecProperty(last_clause_ < kRetiresOnSaturation,
                        ".RetiresOnSaturation() cannot appear "
                        "more than once.");
     last_clause_ = kRetiresOnSaturation;
     retires_on_saturation_ = true;
     // Now that no more action clauses can be specified, we check
     // whether their count makes sense.
     CheckActionCountIfNotDone();
     return *this;
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::RetiresOnSaturation () inline
Definition at line 1033 of file gmock-spec-builders.h.
{
     ExpectSpecProperty(last_clause_ < kRetiresOnSaturation,
                        ".RetiresOnSaturation() cannot appear "
                        "more than once.");
     last_clause_ = kRetiresOnSaturation;
     retires_on_saturation_ = true;
     // Now that no more action clauses can be specified, we check
     // whether their count makes sense.
     CheckActionCountIfNotDone();
     return *this;
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::RetiresOnSaturation () inline
Definition at line 1033 of file gmock-spec-builders.h.
{
     ExpectSpecProperty(last_clause_ < kRetiresOnSaturation,
                        ".RetiresOnSaturation() cannot appear "
                        "more than once.");
     last_clause_ = kRetiresOnSaturation;
     retires_on_saturation_ = true;
     // Now that no more action clauses can be specified, we check
     // whether their count makes sense.
     CheckActionCountIfNotDone();
     return *this;
   }
template<typename F> bool testing::internal::TypedExpectation< F >::ShouldHandleArguments (const ArgumentTuple & args) const inline private
Definition at line 1092 of file gmock-spec-builders.h.
References testing::Matches().
{
     g_gmock_mutex.AssertHeld();
     // In case the action count wasn't checked when the expectation
     // was defined (e.g. if this expectation has no WillRepeatedly()
     // or RetiresOnSaturation() clause), we check it when the
     // expectation is used for the first time.
     CheckActionCountIfNotDone();
     return !is_retired() && AllPrerequisitesAreSatisfied() && Matches(args);
   }
template<typename F> bool testing::internal::TypedExpectation< F >::ShouldHandleArguments (const ArgumentTuple & args) const inline private
Definition at line 1092 of file gmock-spec-builders.h.
References testing::Matches().
{
     g_gmock_mutex.AssertHeld();
     // In case the action count wasn't checked when the expectation
     // was defined (e.g. if this expectation has no WillRepeatedly()
     // or RetiresOnSaturation() clause), we check it when the
     // expectation is used for the first time.
     CheckActionCountIfNotDone();
     return !is_retired() && AllPrerequisitesAreSatisfied() && Matches(args);
   }
template<typename F> bool testing::internal::TypedExpectation< F >::ShouldHandleArguments (const ArgumentTuple & args) const inline private
Definition at line 1092 of file gmock-spec-builders.h.
References testing::Matches().
Referenced by testing::internal::FunctionMockerBase< R(A1, A2)>::FindMatchingExpectationLocked().
{
     g_gmock_mutex.AssertHeld();
     // In case the action count wasn't checked when the expectation
     // was defined (e.g. if this expectation has no WillRepeatedly()
     // or RetiresOnSaturation() clause), we check it when the
     // expectation is used for the first time.
     CheckActionCountIfNotDone();
     return !is_retired() && AllPrerequisitesAreSatisfied() && Matches(args);
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::Times (const Cardinality & a_cardinality) inline
Definition at line 925 of file gmock-spec-builders.h.
References testing::internal::ExpectationBase::UntypedTimes().
{
     ExpectationBase::UntypedTimes(a_cardinality);
     return *this;
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::Times (const Cardinality & a_cardinality) inline
Definition at line 925 of file gmock-spec-builders.h.
References testing::internal::ExpectationBase::UntypedTimes().
{
     ExpectationBase::UntypedTimes(a_cardinality);
     return *this;
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::Times (const Cardinality & a_cardinality) inline
Definition at line 925 of file gmock-spec-builders.h.
References testing::internal::ExpectationBase::UntypedTimes().
{
     ExpectationBase::UntypedTimes(a_cardinality);
     return *this;
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::Times (int n) inline
Definition at line 931 of file gmock-spec-builders.h.
References testing::Exactly().
{
     return Times(Exactly(n));
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::Times (int n) inline
Definition at line 931 of file gmock-spec-builders.h.
References testing::Exactly().
{
     return Times(Exactly(n));
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::Times (int n) inline
Definition at line 931 of file gmock-spec-builders.h.
References testing::Exactly().
{
     return Times(Exactly(n));
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::WillOnce (const Action< F > & action) inline
Definition at line 994 of file gmock-spec-builders.h.
References testing::Exactly().
{
     ExpectSpecProperty(last_clause_ <= kWillOnce,
                        ".WillOnce() cannot appear after "
                        ".WillRepeatedly() or .RetiresOnSaturation().");
     last_clause_ = kWillOnce;
     untyped_actions_.push_back(new Action<F>(action));
     if (!cardinality_specified()) {
       set_cardinality(Exactly(static_cast<int>(untyped_actions_.size())));
     }
     return *this;
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::WillOnce (const Action< F > & action) inline
Definition at line 994 of file gmock-spec-builders.h.
References testing::Exactly().
{
     ExpectSpecProperty(last_clause_ <= kWillOnce,
                        ".WillOnce() cannot appear after "
                        ".WillRepeatedly() or .RetiresOnSaturation().");
     last_clause_ = kWillOnce;
     untyped_actions_.push_back(new Action<F>(action));
     if (!cardinality_specified()) {
       set_cardinality(Exactly(static_cast<int>(untyped_actions_.size())));
     }
     return *this;
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::WillOnce (const Action< F > & action) inline
Definition at line 994 of file gmock-spec-builders.h.
References testing::Exactly().
{
     ExpectSpecProperty(last_clause_ <= kWillOnce,
                        ".WillOnce() cannot appear after "
                        ".WillRepeatedly() or .RetiresOnSaturation().");
     last_clause_ = kWillOnce;
     untyped_actions_.push_back(new Action<F>(action));
     if (!cardinality_specified()) {
       set_cardinality(Exactly(static_cast<int>(untyped_actions_.size())));
     }
     return *this;
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::WillRepeatedly (const Action< F > & action) inline
Definition at line 1008 of file gmock-spec-builders.h.
References upload::action, and testing::AtLeast().
{
     if (last_clause_ == kWillRepeatedly) {
       ExpectSpecProperty(false,
                          ".WillRepeatedly() cannot appear "
                          "more than once in an EXPECT_CALL().");
     } else {
       ExpectSpecProperty(last_clause_ < kWillRepeatedly,
                          ".WillRepeatedly() cannot appear "
                          "after .RetiresOnSaturation().");
     }
     last_clause_ = kWillRepeatedly;
     repeated_action_specified_ = true;
     repeated_action_ = action;
     if (!cardinality_specified()) {
       set_cardinality(AtLeast(static_cast<int>(untyped_actions_.size())));
     }
     // Now that no more action clauses can be specified, we check
     // whether their count makes sense.
     CheckActionCountIfNotDone();
     return *this;
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::WillRepeatedly (const Action< F > & action) inline
Definition at line 1008 of file gmock-spec-builders.h.
References upload::action, and testing::AtLeast().
{
     if (last_clause_ == kWillRepeatedly) {
       ExpectSpecProperty(false,
                          ".WillRepeatedly() cannot appear "
                          "more than once in an EXPECT_CALL().");
     } else {
       ExpectSpecProperty(last_clause_ < kWillRepeatedly,
                          ".WillRepeatedly() cannot appear "
                          "after .RetiresOnSaturation().");
     }
     last_clause_ = kWillRepeatedly;
     repeated_action_specified_ = true;
     repeated_action_ = action;
     if (!cardinality_specified()) {
       set_cardinality(AtLeast(static_cast<int>(untyped_actions_.size())));
     }
     // Now that no more action clauses can be specified, we check
     // whether their count makes sense.
     CheckActionCountIfNotDone();
     return *this;
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::WillRepeatedly (const Action< F > & action) inline
Definition at line 1008 of file gmock-spec-builders.h.
References upload::action, and testing::AtLeast().
{
     if (last_clause_ == kWillRepeatedly) {
       ExpectSpecProperty(false,
                          ".WillRepeatedly() cannot appear "
                          "more than once in an EXPECT_CALL().");
     } else {
       ExpectSpecProperty(last_clause_ < kWillRepeatedly,
                          ".WillRepeatedly() cannot appear "
                          "after .RetiresOnSaturation().");
     }
     last_clause_ = kWillRepeatedly;
     repeated_action_specified_ = true;
     repeated_action_ = action;
     if (!cardinality_specified()) {
       set_cardinality(AtLeast(static_cast<int>(untyped_actions_.size())));
     }
     // Now that no more action clauses can be specified, we check
     // whether their count makes sense.
     CheckActionCountIfNotDone();
     return *this;
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::With (const Matcher< const ArgumentTuple & > & m) inline
Definition at line 907 of file gmock-spec-builders.h.
References m.
{
     if (last_clause_ == kWith) {
       ExpectSpecProperty(false,
                          ".With() cannot appear "
                          "more than once in an EXPECT_CALL().");
     } else {
       ExpectSpecProperty(last_clause_ < kWith,
                          ".With() must be the first "
                          "clause in an EXPECT_CALL().");
     }
     last_clause_ = kWith;
     extra_matcher_ = m;
     extra_matcher_specified_ = true;
     return *this;
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::With (const Matcher< const ArgumentTuple & > & m) inline
Definition at line 907 of file gmock-spec-builders.h.
References m.
{
     if (last_clause_ == kWith) {
       ExpectSpecProperty(false,
                          ".With() cannot appear "
                          "more than once in an EXPECT_CALL().");
     } else {
       ExpectSpecProperty(last_clause_ < kWith,
                          ".With() must be the first "
                          "clause in an EXPECT_CALL().");
     }
     last_clause_ = kWith;
     extra_matcher_ = m;
     extra_matcher_specified_ = true;
     return *this;
   }
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::With (const Matcher< const ArgumentTuple & > & m) inline
Definition at line 907 of file gmock-spec-builders.h.
References m.
{
     if (last_clause_ == kWith) {
       ExpectSpecProperty(false,
                          ".With() cannot appear "
                          "more than once in an EXPECT_CALL().");
     } else {
       ExpectSpecProperty(last_clause_ < kWith,
                          ".With() must be the first "
                          "clause in an EXPECT_CALL().");
     }
     last_clause_ = kWith;
     extra_matcher_ = m;
     extra_matcher_specified_ = true;
     return *this;
   }
Friends And Related Function Documentation
template<typename F> template<typename Function > friend class FunctionMockerBase friend
Definition at line 1072 of file gmock-spec-builders.h.
template<typename F> template<typename Function > class FunctionMockerBase () friend
Definition at line 1072 of file gmock-spec-builders.h.
template<typename F> template<typename Function > class FunctionMockerBase () friend
Definition at line 1072 of file gmock-spec-builders.h.
Member Data Documentation
template<typename F> Matcher< const ArgumentTuple & > testing::internal::TypedExpectation< F >::extra_matcher_ private
Definition at line 1224 of file gmock-spec-builders.h.
template<typename F> ArgumentMatcherTuple testing::internal::TypedExpectation< F >::matchers_ private
Definition at line 1223 of file gmock-spec-builders.h.
template<typename F> FunctionMockerBase< F > *const testing::internal::TypedExpectation< F >::owner_ private
Definition at line 1222 of file gmock-spec-builders.h.
template<typename F> Action< F > testing::internal::TypedExpectation< F >::repeated_action_ private
Definition at line 1225 of file gmock-spec-builders.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-spec-builders.h