proxygen: ProxyFrontendHandler Class Reference
ProxyFrontendHandler Class Reference
Public Member Functions
ProxyFrontendHandler (SocketAddress remoteAddress)
void read (Context *, IOBufQueue &q) override
void readEOF (Context *ctx) override
void readException (Context *ctx, exception_wrapper e) override
void transportActive (Context *ctx) override
Public Member Functions inherited from wangle::HandlerAdapter< R, W >
void read (Context *ctx, R msg) override
folly::Future< folly::Unit > write (Context *ctx, W msg) override
Public Member Functions inherited from wangle::Handler< R, R, W, W >
~Handler () override=default
virtual void read (Context *ctx, Rmsg)=0
virtual void readEOF (Context *ctx)
virtual void readException (Context *ctx, folly::exception_wrapper e)
virtual void transportActive (Context *ctx)
virtual void transportInactive (Context *ctx)
virtual folly::Future< folly::Unit > write (Context *ctx, Wmsg)=0
virtual folly::Future< folly::Unit > writeException (Context *ctx, folly::exception_wrapper e)
virtual folly::Future< folly::Unit > close (Context *ctx)
Public Member Functions inherited from wangle::HandlerBase< HandlerContext< R, W > >
virtual ~HandlerBase ()=default
virtual void attachPipeline (HandlerContext< R, W > *)
virtual void detachPipeline (HandlerContext< R, W > *)
HandlerContext< R, W > * getContext ()
Private Attributes
SocketAddress remoteAddress_
ClientBootstrap< DefaultPipeline > client_
DefaultPipeline * backendPipeline_ {nullptr}
folly::IOBufQueue buffer_ {folly::IOBufQueue::cacheChainLength()}
Additional Inherited Members
Public Types inherited from wangle::HandlerAdapter< R, W >
typedef Handler< R, R, W, W >::Context Context
Public Types inherited from wangle::Handler< R, R, W, W >
typedef R rin
typedef R rout
typedef W win
typedef W wout
typedef HandlerContext< R, W > Context
Static Public Attributes inherited from wangle::Handler< R, R, W, W >
static const HandlerDir dir
Detailed Description
Definition at line 72 of file Proxy.cpp.
Constructor & Destructor Documentation
ProxyFrontendHandler::ProxyFrontendHandler (SocketAddress remoteAddress) inline explicit
Definition at line 74 of file Proxy.cpp.
                                                              :
       remoteAddress_(remoteAddress) {}
Member Function Documentation
void ProxyFrontendHandler::read (Context * , IOBufQueue & q) inline override
Definition at line 77 of file Proxy.cpp.
References buffer_.
{
     buffer_.append(q);
     if (!backendPipeline_) {
       return;
     }
     backendPipeline_->write(buffer_.move());
   }
void ProxyFrontendHandler::readEOF (Context * ctx) inline override
Definition at line 86 of file Proxy.cpp.
References folly::netops::close(), and folly::INFO.
{
     LOG(INFO) << "Connection closed by local host";
     if (!backendPipeline_) {
       return;
     }
     backendPipeline_->close().thenValue([this, ctx](auto&&){
       this->close(ctx);
     });
   }
void ProxyFrontendHandler::readException (Context * ctx, exception_wrapper e) inline override
Definition at line 96 of file Proxy.cpp.
References folly::netops::close(), and folly::exceptionStr().
{
     LOG(ERROR) << "Local error: " << exceptionStr(e);
     if (!backendPipeline_) {
       return;
     }
     backendPipeline_->close().thenValue([this, ctx](auto&&){
       this->close(ctx);
     });
   }
void ProxyFrontendHandler::transportActive (Context * ctx) inline override
Definition at line 106 of file Proxy.cpp.
References folly::netops::close(), folly::exceptionStr(), wangle::Pipeline< R, W >::transportActive(), and wangle::Pipeline< R, W >::transportInactive().
{
     if (backendPipeline_) {
       // Already connected
       return;
     }
     // Pause reading from the socket until remote connection succeeds
     auto frontendPipeline = dynamic_cast<DefaultPipeline*>(ctx->getPipeline());
     frontendPipeline->transportInactive();
     client_.pipelineFactory(
         std::make_shared<ProxyBackendPipelineFactory>(frontendPipeline));
     client_.connect(remoteAddress_)
       .thenValue([this, frontendPipeline](DefaultPipeline* pipeline){
         backendPipeline_ = pipeline;
         // Resume read
         frontendPipeline->transportActive();
       })
       .onError([this, ctx](const std::exception& e){
         LOG(ERROR) << "Connect error: " << exceptionStr(e);
         this->close(ctx);
       });
   }
Member Data Documentation
DefaultPipeline* ProxyFrontendHandler::backendPipeline_ {nullptr} private
Definition at line 133 of file Proxy.cpp.
folly::IOBufQueue ProxyFrontendHandler::buffer_ {folly::IOBufQueue::cacheChainLength()} private
Definition at line 134 of file Proxy.cpp.
ClientBootstrap<DefaultPipeline> ProxyFrontendHandler::client_ private
Definition at line 132 of file Proxy.cpp.
SocketAddress ProxyFrontendHandler::remoteAddress_ private
Definition at line 131 of file Proxy.cpp.
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/example/proxy/Proxy.cpp