proxygen: folly::fibers::LoopController Class Reference
folly::fibers::LoopController Class Reference abstract
#include <LoopController.h>
Public Types
typedef std::chrono::steady_clock Clock
typedef std::chrono::time_point< Clock > TimePoint
Public Member Functions
virtual ~LoopController ()
virtual void setFiberManager (FiberManager *)=0
virtual void schedule ()=0
virtual void runLoop ()=0
virtual void scheduleThreadSafe ()=0
virtual void timedSchedule (std::function< void()> func, TimePoint time)=0
Detailed Description
Definition at line 26 of file LoopController.h.
Member Typedef Documentation
typedef std::chrono::steady_clock folly::fibers::LoopController::Clock
Definition at line 28 of file LoopController.h.
typedef std::chrono::time_point<Clock> folly::fibers::LoopController::TimePoint
Definition at line 29 of file LoopController.h.
Constructor & Destructor Documentation
virtual folly::fibers::LoopController::~LoopController () inline virtual
Definition at line 31 of file LoopController.h.
References runLoop(), schedule(), scheduleThreadSafe(), setFiberManager(), folly::detail::distributed_mutex::time(), and timedSchedule().
 {}
Member Function Documentation
virtual void folly::fibers::LoopController::runLoop () pure virtual
Run FiberManager loopUntilNoReadyImpl(). May have additional logic specific to a LoopController.
Implemented in folly::fibers::SimpleLoopController, folly::fibers::EventBaseLoopController, and folly::fibers::ExecutorLoopController.
Referenced by ~LoopController().
virtual void folly::fibers::LoopController::schedule () pure virtual
Called by FiberManager to schedule the loop function run at some point in the futufre.
Implemented in folly::fibers::SimpleLoopController, folly::fibers::EventBaseLoopController, and folly::fibers::ExecutorLoopController.
Referenced by ~LoopController().
virtual void folly::fibers::LoopController::scheduleThreadSafe () pure virtual
Same as schedule(), but safe to call from any thread.
Implemented in folly::fibers::SimpleLoopController, folly::fibers::EventBaseLoopController, and folly::fibers::ExecutorLoopController.
Referenced by ~LoopController().
virtual void folly::fibers::LoopController::setFiberManager (FiberManager *) pure virtual
Called by FiberManager to associate itself with the LoopController.
Implemented in folly::fibers::SimpleLoopController, folly::fibers::EventBaseLoopController, and folly::fibers::ExecutorLoopController.
Referenced by ~LoopController().
virtual void folly::fibers::LoopController::timedSchedule (std::function< void()> func, TimePoint time) pure virtual
Called by FiberManager to schedule some function to be run at some time.
Implemented in folly::fibers::EventBaseLoopController, and folly::fibers::ExecutorLoopController.
Referenced by folly::fibers::TimeoutController::scheduleRun(), and ~LoopController().
The documentation for this class was generated from the following file:
proxygen/folly/folly/fibers/LoopController.h