proxygen: proxygen::HTTPCommonHeaders Class Reference
proxygen::HTTPCommonHeaders Class Reference
#include <HTTPCommonHeaders.h>
Static Public Member Functions
static FB_EXPORT HTTPHeaderCode hash (const char *name, size_t len)
static FB_EXPORT HTTPHeaderCode hash (const std::string &name)
static FB_EXPORT std::string * initHeaderNames (HTTPCommonHeaderTableType type)
static const std::string * getPointerToCommonHeaderTable (HTTPCommonHeaderTableType type)
static const std::string * getPointerToHeaderName (HTTPHeaderCode code, HTTPCommonHeaderTableType type=TABLE_CAMELCASE)
static bool isHeaderNameFromTable (const std::string *headerName, HTTPCommonHeaderTableType type)
static HTTPHeaderCode getHeaderCodeFromTableCommonHeaderName (const std::string *headerName, HTTPCommonHeaderTableType type)
static FB_EXPORT HTTPHeaderCode hash (const char *name, size_t len)
static FB_EXPORT HTTPHeaderCode hash (const std::string &name)
static FB_EXPORT std::string * initHeaderNames (HTTPCommonHeaderTableType type)
static const std::string * getPointerToCommonHeaderTable (HTTPCommonHeaderTableType type)
static const std::string * getPointerToHeaderName (HTTPHeaderCode code, HTTPCommonHeaderTableType type=TABLE_CAMELCASE)
static bool isHeaderNameFromTable (const std::string *headerName, HTTPCommonHeaderTableType type)
static HTTPHeaderCode getHeaderCodeFromTableCommonHeaderName (const std::string *headerName, HTTPCommonHeaderTableType type)
Static Public Attributes
static constexpr uint64_t num_header_codes = 94
Detailed Description
Definition at line 142 of file HTTPCommonHeaders.h.
Member Function Documentation
static HTTPHeaderCode proxygen::HTTPCommonHeaders::getHeaderCodeFromTableCommonHeaderName (const std::string * headerName, HTTPCommonHeaderTableType type) inline static
Definition at line 81 of file HTTPCommonHeaders.template.h.
References diff(), getPointerToCommonHeaderTable(), proxygen::HTTP_HEADER_NONE, proxygen::HTTP_HEADER_OTHER, and num_header_codes.
{
     if (headerName == nullptr) {
       return HTTP_HEADER_NONE;
     } else {
       auto diff = headerName - getPointerToCommonHeaderTable(type);
       if (diff >= HTTPHeaderCodeCommonOffset && diff < (long)num_header_codes) {
         return static_cast<HTTPHeaderCode>(diff);
       } else {
         return HTTP_HEADER_OTHER;
       }
     }
   }
static HTTPHeaderCode proxygen::HTTPCommonHeaders::getHeaderCodeFromTableCommonHeaderName (const std::string * headerName, HTTPCommonHeaderTableType type) inline static
Definition at line 172 of file HTTPCommonHeaders.h.
References diff(), getPointerToCommonHeaderTable(), proxygen::HTTP_HEADER_NONE, and proxygen::HTTP_HEADER_OTHER.
Referenced by proxygen::HPACKHeaderName::getHeaderCode(), isHeaderNameFromTable(), and TEST_F().
{
     if (headerName == nullptr) {
       return HTTP_HEADER_NONE;
     } else {
       auto diff = headerName - getPointerToCommonHeaderTable(type);
       if (diff >= HTTPHeaderCodeCommonOffset && diff < (long)num_header_codes) {
         return static_cast<HTTPHeaderCode>(diff);
       } else {
         return HTTP_HEADER_OTHER;
       }
     }
   }
static const std::string* proxygen::HTTPCommonHeaders::getPointerToCommonHeaderTable (HTTPCommonHeaderTableType type) static
const std::string * proxygen::HTTPCommonHeaders::getPointerToCommonHeaderTable (HTTPCommonHeaderTableType type) static
Definition at line 369 of file HTTPCommonHeaders.cpp.
References string, proxygen::TABLE_CAMELCASE, and proxygen::TABLE_LOWERCASE.
Referenced by getHeaderCodeFromTableCommonHeaderName(), getPointerToHeaderName(), and hash().
{
   // The actual common header tables are static and initialized here in source
   // so as to prevent duplicate initializations that could occur through the
   // use of inline semantics or compilation unit referencing if defined in a
   // header
   switch(type) {
     case TABLE_CAMELCASE:
       static const std::string* camelcaseTable = initHeaderNames(type);
       return camelcaseTable;
     case TABLE_LOWERCASE:
       static const std::string* lowercaseTable = initHeaderNames(type);
       return lowercaseTable;
     default:
       // Controlled abort here so its clear from a crash stack this method
       // was called with a table type for which there is no current
       // implementation
       CHECK(false);
       return nullptr;
   }
 }
static const std::string* proxygen::HTTPCommonHeaders::getPointerToHeaderName (HTTPHeaderCode code, HTTPCommonHeaderTableType type = TABLE_CAMELCASE) inline static
Definition at line 66 of file HTTPCommonHeaders.template.h.
References getPointerToCommonHeaderTable().
{
     return getPointerToCommonHeaderTable(type) + code;
   }
static const std::string* proxygen::HTTPCommonHeaders::getPointerToHeaderName (HTTPHeaderCode code, HTTPCommonHeaderTableType type = TABLE_CAMELCASE) inline static
Definition at line 157 of file HTTPCommonHeaders.h.
References getPointerToCommonHeaderTable().
Referenced by proxygen::HTTPHeaders::add(), proxygen::HTTPHeaders::addFromCodec(), proxygen::HPACKHeaderName::storeAddress(), and TEST_F().
{
     return getPointerToCommonHeaderTable(type) + code;
   }
static FB_EXPORT HTTPHeaderCode proxygen::HTTPCommonHeaders::hash (const char * name, size_t len) static
static FB_EXPORT HTTPHeaderCode proxygen::HTTPCommonHeaders::hash (const std::string & name) inline static
Definition at line 56 of file HTTPCommonHeaders.template.h.
References FB_EXPORT, getPointerToCommonHeaderTable(), hash(), initHeaderNames(), string, and type.
{
     return hash(name.data(), name.length());
   }
HTTPHeaderCode proxygen::HTTPCommonHeaders::hash (const char * name, size_t len) static
Definition at line 343 of file HTTPCommonHeaders.cpp.
References proxygen::HTTPCommonHeaderName::code, proxygen::HTTP_HEADER_OTHER, and proxygen::HTTPCommonHeadersInternal::in_word_set().
Referenced by proxygen::HTTPHeaders::add(), proxygen::HTTPHeaders::addFromCodec(), proxygen::HTTPHeaders::exists(), proxygen::HTTPHeaders::forEachValueOfHeader(), hash(), proxygen::HTTPHeaders::remove(), proxygen::HPACKHeaderName::storeAddress(), TEST(), TEST_F(), and proxygen::HTTPHeaders::transferHeaderIfPresent().
{
   const HTTPCommonHeaderName* match =
     HTTPCommonHeadersInternal::in_word_set(name, len);
   return (match == nullptr) ? HTTP_HEADER_OTHER : match->code;
 }
static FB_EXPORT HTTPHeaderCode proxygen::HTTPCommonHeaders::hash (const std::string & name) inline static
Definition at line 147 of file HTTPCommonHeaders.h.
References FB_EXPORT, hash(), initHeaderNames(), string, and type.
{
     return hash(name.data(), name.length());
   }
static FB_EXPORT std::string* proxygen::HTTPCommonHeaders::initHeaderNames (HTTPCommonHeaderTableType type) static
std::string * proxygen::HTTPCommonHeaders::initHeaderNames (HTTPCommonHeaderTableType type) static
Definition at line 349 of file HTTPCommonHeaders.cpp.
References proxygen::HTTPCommonHeaderName::code, data, proxygen::MAX_HASH_VALUE, proxygen::MIN_HASH_VALUE, proxygen::HTTPCommonHeaderName::name, num_header_codes, folly::size(), string, proxygen::TABLE_LOWERCASE, folly::toLowerAscii(), proxygen::TOTAL_KEYWORDS, and uint8_t.
Referenced by hash().
{
   auto headerNames = new std::string[HTTPCommonHeaders::num_header_codes];
   for (int j = MIN_HASH_VALUE; j <= MAX_HASH_VALUE; ++j) {
     uint8_t code = wordlist[j].code;
     const uint8_t OFFSET = 2; // first 2 values are reserved for special cases
     if (code >= OFFSET && code < TOTAL_KEYWORDS + OFFSET
                        && wordlist[j].name[0] != '\0') {
       DCHECK_EQ(headerNames[code], std::string());
       // this would mean a duplicate header code in the .gperf file
       headerNames[code] = wordlist[j].name;
       if (type == TABLE_LOWERCASE) {
         folly::toLowerAscii(const_cast<char*>(headerNames[code].data()),
                                               headerNames[code].size());
       }
     }
   }
   return headerNames;
 }
static bool proxygen::HTTPCommonHeaders::isHeaderNameFromTable (const std::string * headerName, HTTPCommonHeaderTableType type) inline static
Definition at line 71 of file HTTPCommonHeaders.template.h.
References getHeaderCodeFromTableCommonHeaderName(), and proxygen::HTTPHeaderCodeCommonOffset.
{
     return getHeaderCodeFromTableCommonHeaderName(headerName, type) >=
       HTTPHeaderCodeCommonOffset;
   }
static bool proxygen::HTTPCommonHeaders::isHeaderNameFromTable (const std::string * headerName, HTTPCommonHeaderTableType type) inline static
Definition at line 162 of file HTTPCommonHeaders.h.
References getHeaderCodeFromTableCommonHeaderName(), and proxygen::HTTPHeaderCodeCommonOffset.
Referenced by proxygen::HPACKHeaderName::isAllocated(), proxygen::HPACKHeaderName::isCommonHeader(), and TEST_F().
{
     return getHeaderCodeFromTableCommonHeaderName(headerName, type) >=
       HTTPHeaderCodeCommonOffset;
   }
Member Data Documentation
constexpr uint64_t proxygen::HTTPCommonHeaders::num_header_codes = 94 static
Definition at line 152 of file HTTPCommonHeaders.h.
Referenced by getHeaderCodeFromTableCommonHeaderName(), initHeaderNames(), and TEST_F().
The documentation for this class was generated from the following files:
proxygen/lib/http/HTTPCommonHeaders.h
proxygen/lib/http/HTTPCommonHeaders.template.h
proxygen/lib/http/HTTPCommonHeaders.cpp