proxygen: gtest_xml_outfiles_test.GTestXMLOutFilesTest Class Reference
gtest_xml_outfiles_test.GTestXMLOutFilesTest Class Reference
Public Member Functions
def setUp (self)
def tearDown (self)
def DeleteFilesAndDir (self)
def testOutfile1 (self)
def testOutfile2 (self)
def setUp (self)
def tearDown (self)
def DeleteFilesAndDir (self)
def testOutfile1 (self)
def testOutfile2 (self)
def setUp (self)
def tearDown (self)
def DeleteFilesAndDir (self)
def testOutfile1 (self)
def testOutfile2 (self)
Public Member Functions inherited from gtest_xml_test_utils.GTestXMLTestCase
def AssertEquivalentNodes (self, expected_node, actual_node)
def NormalizeXml (self, element)
def AssertEquivalentNodes (self, expected_node, actual_node)
def NormalizeXml (self, element)
def AssertEquivalentNodes (self, expected_node, actual_node)
def NormalizeXml (self, element)
Public Attributes
output_dir_
Private Member Functions
def _TestOutFile (self, test_name, expected_xml)
def _TestOutFile (self, test_name, expected_xml)
def _TestOutFile (self, test_name, expected_xml)
Additional Inherited Members
Static Public Attributes inherited from gtest_xml_test_utils.GTestXMLTestCase
dictionary identifying_attribute
Detailed Description
Unit test for Google Test's XML output functionality.
Definition at line 64 of file gtest_xml_outfiles_test.py.
Member Function Documentation
def gtest_xml_outfiles_test.GTestXMLOutFilesTest._TestOutFile (self, test_name, expected_xml) private
Definition at line 98 of file gtest_xml_outfiles_test.py.
References gtest_xml_test_utils.GTestXMLTestCase.AssertEquivalentNodes(), gtest_test_utils.GetTempDir(), gtest_test_utils.GetTestExecutablePath(), gtest_test_utils.Main(), gtest_xml_test_utils.GTestXMLTestCase.NormalizeXml(), and gtest_xml_outfiles_test.GTestXMLOutFilesTest.output_dir_.
Referenced by gtest_xml_outfiles_test.GTestXMLOutFilesTest._TestOutFile(), gtest_xml_outfiles_test.GTestXMLOutFilesTest.testOutfile1(), and gtest_xml_outfiles_test.GTestXMLOutFilesTest.testOutfile2().
   def _TestOutFile(self, test_name, expected_xml):
     gtest_prog_path = gtest_test_utils.GetTestExecutablePath(test_name)
     command = [gtest_prog_path, "--gtest_output=xml:%s" % self.output_dir_]
     p = gtest_test_utils.Subprocess(command,
                                     working_dir=gtest_test_utils.GetTempDir())
     self.assert_(p.exited)
     self.assertEquals(0, p.exit_code)
     # TODO(wan@google.com): libtool causes the built test binary to be
     #   named lt-gtest_xml_outfiles_test_ instead of
     #   gtest_xml_outfiles_test_.  To account for this possibillity, we
     #   allow both names in the following code.  We should remove this
     #   hack when Chandler Carruth's libtool replacement tool is ready.
     output_file_name1 = test_name + ".xml"
     output_file1 = os.path.join(self.output_dir_, output_file_name1)
     output_file_name2 = 'lt-' + output_file_name1
     output_file2 = os.path.join(self.output_dir_, output_file_name2)
     self.assert_(os.path.isfile(output_file1) or os.path.isfile(output_file2),
                  output_file1)
     expected = minidom.parseString(expected_xml)
     if os.path.isfile(output_file1):
       actual = minidom.parse(output_file1)
     else:
       actual = minidom.parse(output_file2)
     self.NormalizeXml(actual.documentElement)
     self.AssertEquivalentNodes(expected.documentElement,
                                actual.documentElement)
     expected.unlink()
     actual.unlink()
def gtest_xml_outfiles_test.GTestXMLOutFilesTest._TestOutFile (self, test_name, expected_xml) private
Definition at line 98 of file gtest_xml_outfiles_test.py.
References gtest_xml_outfiles_test.GTestXMLOutFilesTest._TestOutFile(), gtest_xml_test_utils.GTestXMLTestCase.AssertEquivalentNodes(), gtest_test_utils.GetTempDir(), gtest_test_utils.GetTestExecutablePath(), gtest_test_utils.Main(), gtest_xml_test_utils.GTestXMLTestCase.NormalizeXml(), and gtest_xml_outfiles_test.GTestXMLOutFilesTest.output_dir_.
   def _TestOutFile(self, test_name, expected_xml):
     gtest_prog_path = gtest_test_utils.GetTestExecutablePath(test_name)
     command = [gtest_prog_path, "--gtest_output=xml:%s" % self.output_dir_]
     p = gtest_test_utils.Subprocess(command,
                                     working_dir=gtest_test_utils.GetTempDir())
     self.assert_(p.exited)
     self.assertEquals(0, p.exit_code)
     # TODO(wan@google.com): libtool causes the built test binary to be
     #   named lt-gtest_xml_outfiles_test_ instead of
     #   gtest_xml_outfiles_test_.  To account for this possibillity, we
     #   allow both names in the following code.  We should remove this
     #   hack when Chandler Carruth's libtool replacement tool is ready.
     output_file_name1 = test_name + ".xml"
     output_file1 = os.path.join(self.output_dir_, output_file_name1)
     output_file_name2 = 'lt-' + output_file_name1
     output_file2 = os.path.join(self.output_dir_, output_file_name2)
     self.assert_(os.path.isfile(output_file1) or os.path.isfile(output_file2),
                  output_file1)
     expected = minidom.parseString(expected_xml)
     if os.path.isfile(output_file1):
       actual = minidom.parse(output_file1)
     else:
       actual = minidom.parse(output_file2)
     self.NormalizeXml(actual.documentElement)
     self.AssertEquivalentNodes(expected.documentElement,
                                actual.documentElement)
     expected.unlink()
     actual.unlink()
def gtest_xml_outfiles_test.GTestXMLOutFilesTest._TestOutFile (self, test_name, expected_xml) private
Definition at line 98 of file gtest_xml_outfiles_test.py.
References gtest_xml_outfiles_test.GTestXMLOutFilesTest._TestOutFile(), gtest_xml_test_utils.GTestXMLTestCase.AssertEquivalentNodes(), gtest_test_utils.GetTempDir(), gtest_test_utils.GetTestExecutablePath(), gtest_test_utils.Main(), gtest_xml_test_utils.GTestXMLTestCase.NormalizeXml(), and gtest_xml_outfiles_test.GTestXMLOutFilesTest.output_dir_.
   def _TestOutFile(self, test_name, expected_xml):
     gtest_prog_path = gtest_test_utils.GetTestExecutablePath(test_name)
     command = [gtest_prog_path, "--gtest_output=xml:%s" % self.output_dir_]
     p = gtest_test_utils.Subprocess(command,
                                     working_dir=gtest_test_utils.GetTempDir())
     self.assert_(p.exited)
     self.assertEquals(0, p.exit_code)
     # TODO(wan@google.com): libtool causes the built test binary to be
     #   named lt-gtest_xml_outfiles_test_ instead of
     #   gtest_xml_outfiles_test_.  To account for this possibillity, we
     #   allow both names in the following code.  We should remove this
     #   hack when Chandler Carruth's libtool replacement tool is ready.
     output_file_name1 = test_name + ".xml"
     output_file1 = os.path.join(self.output_dir_, output_file_name1)
     output_file_name2 = 'lt-' + output_file_name1
     output_file2 = os.path.join(self.output_dir_, output_file_name2)
     self.assert_(os.path.isfile(output_file1) or os.path.isfile(output_file2),
                  output_file1)
     expected = minidom.parseString(expected_xml)
     if os.path.isfile(output_file1):
       actual = minidom.parse(output_file1)
     else:
       actual = minidom.parse(output_file2)
     self.NormalizeXml(actual.documentElement)
     self.AssertEquivalentNodes(expected.documentElement,
                                actual.documentElement)
     expected.unlink()
     actual.unlink()
def gtest_xml_outfiles_test.GTestXMLOutFilesTest.DeleteFilesAndDir (self)
Definition at line 78 of file gtest_xml_outfiles_test.py.
References gtest_xml_outfiles_test.GTestXMLOutFilesTest.DeleteFilesAndDir(), and gtest_xml_outfiles_test.GTestXMLOutFilesTest.output_dir_.
   def DeleteFilesAndDir(self):
     try:
       os.remove(os.path.join(self.output_dir_, GTEST_OUTPUT_1_TEST + ".xml"))
     except os.error:
       pass
     try:
       os.remove(os.path.join(self.output_dir_, GTEST_OUTPUT_2_TEST + ".xml"))
     except os.error:
       pass
     try:
       os.rmdir(self.output_dir_)
     except os.error:
       pass
def gtest_xml_outfiles_test.GTestXMLOutFilesTest.DeleteFilesAndDir (self)
Definition at line 78 of file gtest_xml_outfiles_test.py.
References gtest_xml_outfiles_test.GTestXMLOutFilesTest.output_dir_.
Referenced by gtest_xml_outfiles_test.GTestXMLOutFilesTest.DeleteFilesAndDir(), gtest_xml_outfiles_test.GTestXMLOutFilesTest.setUp(), and gtest_xml_outfiles_test.GTestXMLOutFilesTest.tearDown().
   def DeleteFilesAndDir(self):
     try:
       os.remove(os.path.join(self.output_dir_, GTEST_OUTPUT_1_TEST + ".xml"))
     except os.error:
       pass
     try:
       os.remove(os.path.join(self.output_dir_, GTEST_OUTPUT_2_TEST + ".xml"))
     except os.error:
       pass
     try:
       os.rmdir(self.output_dir_)
     except os.error:
       pass
def gtest_xml_outfiles_test.GTestXMLOutFilesTest.DeleteFilesAndDir (self)
Definition at line 78 of file gtest_xml_outfiles_test.py.
References gtest_xml_outfiles_test.GTestXMLOutFilesTest.DeleteFilesAndDir(), and gtest_xml_outfiles_test.GTestXMLOutFilesTest.output_dir_.
   def DeleteFilesAndDir(self):
     try:
       os.remove(os.path.join(self.output_dir_, GTEST_OUTPUT_1_TEST + ".xml"))
     except os.error:
       pass
     try:
       os.remove(os.path.join(self.output_dir_, GTEST_OUTPUT_2_TEST + ".xml"))
     except os.error:
       pass
     try:
       os.rmdir(self.output_dir_)
     except os.error:
       pass
def gtest_xml_outfiles_test.GTestXMLOutFilesTest.setUp (self)
Definition at line 67 of file gtest_xml_outfiles_test.py.
Referenced by gtest_xml_outfiles_test.GTestXMLOutFilesTest.setUp().
   def setUp(self):
     # We want the trailing '/' that the last "" provides in os.path.join, for
     # telling Google Test to create an output directory instead of a single file
     # for xml output.
     self.output_dir_ = os.path.join(gtest_test_utils.GetTempDir(),
                                     GTEST_OUTPUT_SUBDIR, "")
     self.DeleteFilesAndDir()
def gtest_xml_outfiles_test.GTestXMLOutFilesTest.setUp (self)
Definition at line 67 of file gtest_xml_outfiles_test.py.
References gtest_xml_outfiles_test.GTestXMLOutFilesTest.DeleteFilesAndDir(), gtest_test_utils.GetTempDir(), gtest_xml_outfiles_test.GTestXMLOutFilesTest.output_dir_, and gtest_xml_outfiles_test.GTestXMLOutFilesTest.setUp().
   def setUp(self):
     # We want the trailing '/' that the last "" provides in os.path.join, for
     # telling Google Test to create an output directory instead of a single file
     # for xml output.
     self.output_dir_ = os.path.join(gtest_test_utils.GetTempDir(),
                                     GTEST_OUTPUT_SUBDIR, "")
     self.DeleteFilesAndDir()
def gtest_xml_outfiles_test.GTestXMLOutFilesTest.setUp (self)
Definition at line 67 of file gtest_xml_outfiles_test.py.
References gtest_xml_outfiles_test.GTestXMLOutFilesTest.DeleteFilesAndDir(), gtest_test_utils.GetTempDir(), gtest_xml_outfiles_test.GTestXMLOutFilesTest.output_dir_, and gtest_xml_outfiles_test.GTestXMLOutFilesTest.setUp().
   def setUp(self):
     # We want the trailing '/' that the last "" provides in os.path.join, for
     # telling Google Test to create an output directory instead of a single file
     # for xml output.
     self.output_dir_ = os.path.join(gtest_test_utils.GetTempDir(),
                                     GTEST_OUTPUT_SUBDIR, "")
     self.DeleteFilesAndDir()
def gtest_xml_outfiles_test.GTestXMLOutFilesTest.tearDown (self)
Definition at line 75 of file gtest_xml_outfiles_test.py.
References gtest_xml_outfiles_test.GTestXMLOutFilesTest.DeleteFilesAndDir(), and gtest_xml_outfiles_test.GTestXMLOutFilesTest.tearDown().
   def tearDown(self):
     self.DeleteFilesAndDir()
def gtest_xml_outfiles_test.GTestXMLOutFilesTest.tearDown (self)
Definition at line 75 of file gtest_xml_outfiles_test.py.
References gtest_xml_outfiles_test.GTestXMLOutFilesTest.DeleteFilesAndDir().
Referenced by gtest_xml_outfiles_test.GTestXMLOutFilesTest.tearDown().
   def tearDown(self):
     self.DeleteFilesAndDir()
def gtest_xml_outfiles_test.GTestXMLOutFilesTest.tearDown (self)
Definition at line 75 of file gtest_xml_outfiles_test.py.
References gtest_xml_outfiles_test.GTestXMLOutFilesTest.DeleteFilesAndDir(), and gtest_xml_outfiles_test.GTestXMLOutFilesTest.tearDown().
   def tearDown(self):
     self.DeleteFilesAndDir()
def gtest_xml_outfiles_test.GTestXMLOutFilesTest.testOutfile1 (self)
Definition at line 92 of file gtest_xml_outfiles_test.py.
References gtest_xml_outfiles_test.GTestXMLOutFilesTest._TestOutFile(), and gtest_xml_outfiles_test.GTestXMLOutFilesTest.testOutfile1().
   def testOutfile1(self):
     self._TestOutFile(GTEST_OUTPUT_1_TEST, EXPECTED_XML_1)
def gtest_xml_outfiles_test.GTestXMLOutFilesTest.testOutfile1 (self)
Definition at line 92 of file gtest_xml_outfiles_test.py.
References gtest_xml_outfiles_test.GTestXMLOutFilesTest._TestOutFile().
Referenced by gtest_xml_outfiles_test.GTestXMLOutFilesTest.testOutfile1().
   def testOutfile1(self):
     self._TestOutFile(GTEST_OUTPUT_1_TEST, EXPECTED_XML_1)
def gtest_xml_outfiles_test.GTestXMLOutFilesTest.testOutfile1 (self)
Definition at line 92 of file gtest_xml_outfiles_test.py.
References gtest_xml_outfiles_test.GTestXMLOutFilesTest._TestOutFile(), and gtest_xml_outfiles_test.GTestXMLOutFilesTest.testOutfile1().
   def testOutfile1(self):
     self._TestOutFile(GTEST_OUTPUT_1_TEST, EXPECTED_XML_1)
def gtest_xml_outfiles_test.GTestXMLOutFilesTest.testOutfile2 (self)
Definition at line 95 of file gtest_xml_outfiles_test.py.
References gtest_xml_outfiles_test.GTestXMLOutFilesTest._TestOutFile(), and gtest_xml_outfiles_test.GTestXMLOutFilesTest.testOutfile2().
   def testOutfile2(self):
     self._TestOutFile(GTEST_OUTPUT_2_TEST, EXPECTED_XML_2)
def gtest_xml_outfiles_test.GTestXMLOutFilesTest.testOutfile2 (self)
Definition at line 95 of file gtest_xml_outfiles_test.py.
References gtest_xml_outfiles_test.GTestXMLOutFilesTest._TestOutFile().
Referenced by gtest_xml_outfiles_test.GTestXMLOutFilesTest.testOutfile2().
   def testOutfile2(self):
     self._TestOutFile(GTEST_OUTPUT_2_TEST, EXPECTED_XML_2)
def gtest_xml_outfiles_test.GTestXMLOutFilesTest.testOutfile2 (self)
Definition at line 95 of file gtest_xml_outfiles_test.py.
References gtest_xml_outfiles_test.GTestXMLOutFilesTest._TestOutFile(), and gtest_xml_outfiles_test.GTestXMLOutFilesTest.testOutfile2().
   def testOutfile2(self):
     self._TestOutFile(GTEST_OUTPUT_2_TEST, EXPECTED_XML_2)
Member Data Documentation
gtest_xml_outfiles_test.GTestXMLOutFilesTest.output_dir_
Definition at line 71 of file gtest_xml_outfiles_test.py.
Referenced by gtest_xml_outfiles_test.GTestXMLOutFilesTest._TestOutFile(), gtest_xml_outfiles_test.GTestXMLOutFilesTest.DeleteFilesAndDir(), and gtest_xml_outfiles_test.GTestXMLOutFilesTest.setUp().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest_xml_outfiles_test.py