proxygen: folly::coro::TimedWaitAwaitable< Awaitable >::SharedState Class Reference
folly::coro::TimedWaitAwaitable< Awaitable >::SharedState Class Reference
Public Member Functions
SharedState (std::experimental::coroutine_handle<> ch, Try< await_resume_return_type > &storage)
void setValue (await_resume_return_type &&value)
void setException (exception_wrapper e)
void setTimeout ()
Private Attributes
std::atomic< bool > first_ {false}
std::experimental::coroutine_handle ch_
Try< await_resume_return_type > & storage_
Detailed Description
template<typename Awaitable>
class folly::coro::TimedWaitAwaitable< Awaitable >::SharedState
Definition at line 95 of file Utils.h.
Constructor & Destructor Documentation
template<typename Awaitable > folly::coro::TimedWaitAwaitable< Awaitable >::SharedState::SharedState (std::experimental::coroutine_handle<> ch, Try< await_resume_return_type > & storage) inline
Definition at line 97 of file Utils.h.
         : ch_(std::move(ch)), storage_(storage) {}
Member Function Documentation
template<typename Awaitable > void folly::coro::TimedWaitAwaitable< Awaitable >::SharedState::setException (exception_wrapper e) inline
Definition at line 111 of file Utils.h.
References folly::assume(), and folly::gen::move.
{
       if (first_.exchange(true, std::memory_order_relaxed)) {
         return;
       }
       assume(!storage_.hasValue() && !storage_.hasException());
       storage_.emplaceException(std::move(e));
       ch_();
     }
template<typename Awaitable > void folly::coro::TimedWaitAwaitable< Awaitable >::SharedState::setTimeout () inline
Definition at line 120 of file Utils.h.
                       {
       if (first_.exchange(true, std::memory_order_relaxed)) {
         return;
       }
       ch_();
     }
template<typename Awaitable > void folly::coro::TimedWaitAwaitable< Awaitable >::SharedState::setValue (await_resume_return_type && value) inline
Definition at line 102 of file Utils.h.
References folly::assume(), folly::tryEmplace(), and folly::value().
{
       if (first_.exchange(true, std::memory_order_relaxed)) {
         return;
       }
       assume(!storage_.hasValue() && !storage_.hasException());
       tryEmplace(storage_, static_cast<await_resume_return_type&&>(value));
       ch_();
     }
Member Data Documentation
template<typename Awaitable > std::experimental::coroutine_handle folly::coro::TimedWaitAwaitable< Awaitable >::SharedState::ch_ private
Definition at line 129 of file Utils.h.
template<typename Awaitable > std::atomic<bool> folly::coro::TimedWaitAwaitable< Awaitable >::SharedState::first_ {false} private
Definition at line 128 of file Utils.h.
template<typename Awaitable > Try<await_resume_return_type>& folly::coro::TimedWaitAwaitable< Awaitable >::SharedState::storage_ private
Definition at line 130 of file Utils.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/coro/Utils.h