proxygen: folly::RWSpinLock::WriteHolder Class Reference
folly::RWSpinLock::WriteHolder Class Reference
#include <RWSpinLock.h>
Public Member Functions
WriteHolder (RWSpinLock *lock)
WriteHolder (RWSpinLock &lock)
WriteHolder (UpgradedHolder &&upgraded)
WriteHolder (WriteHolder &&other) noexcept
WriteHolder & operator= (WriteHolder &&other)
WriteHolder (const WriteHolder &other)=delete
WriteHolder & operator= (const WriteHolder &other)=delete
~WriteHolder ()
void reset (RWSpinLock *lock=nullptr)
void swap (WriteHolder *other)
Private Attributes
RWSpinLock * lock_
Friends
class ReadHolder
class UpgradedHolder
Detailed Description
Definition at line 446 of file RWSpinLock.h.
Constructor & Destructor Documentation
folly::RWSpinLock::WriteHolder::WriteHolder (RWSpinLock * lock) inline explicit
Definition at line 448 of file RWSpinLock.h.
References folly::RWSpinLock::lock(), and folly::RWSpinLock::ReadHolder::lock_.
                                            : lock_(lock) {
       if (lock_) {
         lock_->lock();
       }
     }
folly::RWSpinLock::WriteHolder::WriteHolder (RWSpinLock & lock) inline explicit
Definition at line 454 of file RWSpinLock.h.
References folly::RWSpinLock::lock(), and folly::RWSpinLock::ReadHolder::lock_.
                                            : lock_(&lock) {
       lock_->lock();
     }
folly::RWSpinLock::WriteHolder::WriteHolder (UpgradedHolder && upgraded) inline explicit
Definition at line 459 of file RWSpinLock.h.
References folly::RWSpinLock::ReadHolder::lock_, and folly::RWSpinLock::unlock_upgrade_and_lock().
{
       lock_ = upgraded.lock_;
       upgraded.lock_ = nullptr;
       if (lock_) {
         lock_->unlock_upgrade_and_lock();
       }
     }
folly::RWSpinLock::WriteHolder::WriteHolder (WriteHolder && other) inline noexcept
Definition at line 467 of file RWSpinLock.h.
                                               : lock_(other.lock_) {
       other.lock_ = nullptr;
     }
folly::RWSpinLock::WriteHolder::WriteHolder (const WriteHolder & other) delete
folly::RWSpinLock::WriteHolder::~WriteHolder () inline
Definition at line 480 of file RWSpinLock.h.
References folly::RWSpinLock::ReadHolder::lock_, and folly::RWSpinLock::unlock().
                    {
       if (lock_) {
         lock_->unlock();
       }
     }
Member Function Documentation
WriteHolder& folly::RWSpinLock::WriteHolder::operator= (WriteHolder && other) inline
Definition at line 471 of file RWSpinLock.h.
References folly::RWSpinLock::ReadHolder::lock_, folly::RWSpinLock::ReadHolder::operator=(), folly::RWSpinLock::ReadHolder::swap(), folly::f14::swap(), and folly::RWSpinLock::ReadHolder::WriteHolder.
{
       using std::swap;
       swap(lock_, other.lock_);
       return *this;
     }
WriteHolder& folly::RWSpinLock::WriteHolder::operator= (const WriteHolder & other) delete
void folly::RWSpinLock::WriteHolder::reset (RWSpinLock * lock = nullptr) inline
Definition at line 486 of file RWSpinLock.h.
References folly::RWSpinLock::lock(), folly::RWSpinLock::ReadHolder::lock_, and folly::RWSpinLock::unlock().
{
       if (lock == lock_) {
         return;
       }
       if (lock_) {
         lock_->unlock();
       }
       lock_ = lock;
       if (lock_) {
         lock_->lock();
       }
     }
void folly::RWSpinLock::WriteHolder::swap (WriteHolder * other) inline
Definition at line 499 of file RWSpinLock.h.
References folly::RWSpinLock::ReadHolder::lock_, lock_, folly::RWSpinLock::ReadHolder::swap(), and folly::f14::swap().
{
       using std::swap;
       swap(lock_, other->lock_);
     }
Friends And Related Function Documentation
friend class ReadHolder friend
Definition at line 505 of file RWSpinLock.h.
friend class UpgradedHolder friend
Definition at line 506 of file RWSpinLock.h.
Member Data Documentation
RWSpinLock* folly::RWSpinLock::WriteHolder::lock_ private
Definition at line 507 of file RWSpinLock.h.
Referenced by swap().
The documentation for this class was generated from the following file:
proxygen/folly/folly/synchronization/RWSpinLock.h