proxygen: folly::detail::SynchronizedLocker< Synchronized, LockFunc, TryLockFunc, Args > Class Template Reference
folly::detail::SynchronizedLocker< Synchronized, LockFunc, TryLockFunc, Args > Class Template Reference
#include <Synchronized.h>
Public Types
using LockedPtr = invoke_result_t< LockFunc &, Synchronized &, const Args &... >
Public Member Functions
template<typename LockFuncType , typename TryLockFuncType , typename... As>
SynchronizedLocker (Synchronized &sync, LockFuncType &&lockFunc, TryLockFuncType tryLockFunc, As &&...as)
auto lock () const
auto tryLock () const
Private Attributes
Synchronized & synchronized
LockFunc lockFunc_
TryLockFunc tryLockFunc_
std::tuple< Args... > args_
Detailed Description
template<typename Synchronized, typename LockFunc, typename TryLockFunc, typename... Args>
class folly::detail::SynchronizedLocker< Synchronized, LockFunc, TryLockFunc, Args >
Definition at line 802 of file Synchronized.h.
Member Typedef Documentation
template<typename Synchronized , typename LockFunc , typename TryLockFunc , typename... Args> using folly::detail::SynchronizedLocker< Synchronized, LockFunc, TryLockFunc, Args >::LockedPtr = invoke_result_t<LockFunc&, Synchronized&, const Args&...>
Definition at line 804 of file Synchronized.h.
Constructor & Destructor Documentation
template<typename Synchronized , typename LockFunc , typename TryLockFunc , typename... Args> template<typename LockFuncType , typename TryLockFuncType , typename... As> folly::detail::SynchronizedLocker< Synchronized, LockFunc, TryLockFunc, Args >::SynchronizedLocker (Synchronized & sync, LockFuncType && lockFunc, TryLockFuncType tryLockFunc, As &&... as) inline
Definition at line 807 of file Synchronized.h.
References folly::gen::as().
       : synchronized{sync},
         lockFunc_{std::forward<LockFuncType>(lockFunc)},
         tryLockFunc_{std::forward<TryLockFuncType>(tryLockFunc)},
         args_{std::forward<As>(as)...} {}
Member Function Documentation
template<typename Synchronized , typename LockFunc , typename TryLockFunc , typename... Args> auto folly::detail::SynchronizedLocker< Synchronized, LockFunc, TryLockFunc, Args >::lock () const inline
Definition at line 817 of file Synchronized.h.
References folly::apply(), and testing::Args().
                     {
     auto args = std::tuple<const Args&...>{args_};
     return apply(lockFunc_, std::tuple_cat(std::tie(synchronized), args));
   }
template<typename Synchronized , typename LockFunc , typename TryLockFunc , typename... Args> auto folly::detail::SynchronizedLocker< Synchronized, LockFunc, TryLockFunc, Args >::tryLock () const inline
Definition at line 821 of file Synchronized.h.
{
     return tryLockFunc_(synchronized);
   }
Member Data Documentation
template<typename Synchronized , typename LockFunc , typename TryLockFunc , typename... Args> std::tuple<Args...> folly::detail::SynchronizedLocker< Synchronized, LockFunc, TryLockFunc, Args >::args_ private
Definition at line 829 of file Synchronized.h.
template<typename Synchronized , typename LockFunc , typename TryLockFunc , typename... Args> LockFunc folly::detail::SynchronizedLocker< Synchronized, LockFunc, TryLockFunc, Args >::lockFunc_ private
Definition at line 827 of file Synchronized.h.
template<typename Synchronized , typename LockFunc , typename TryLockFunc , typename... Args> Synchronized& folly::detail::SynchronizedLocker< Synchronized, LockFunc, TryLockFunc, Args >::synchronized private
Definition at line 826 of file Synchronized.h.
template<typename Synchronized , typename LockFunc , typename TryLockFunc , typename... Args> TryLockFunc folly::detail::SynchronizedLocker< Synchronized, LockFunc, TryLockFunc, Args >::tryLockFunc_ private
Definition at line 828 of file Synchronized.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/Synchronized.h