proxygen: fizz::detail::OpenSSLECKeyExchange< T > Class Template Reference
fizz::detail::OpenSSLECKeyExchange< T > Class Template Reference
#include <OpenSSLKeyExchange-inl.h>
Public Member Functions
void generateKeyPair ()
void setPrivateKey (folly::ssl::EvpPkeyUniquePtr privateKey)
const folly::ssl::EvpPkeyUniquePtr & getKey () const
std::unique_ptr< folly::IOBuf > generateSharedSecret (const folly::ssl::EvpPkeyUniquePtr &peerKey) const
Private Attributes
folly::ssl::EvpPkeyUniquePtr key_
Detailed Description
template<class T>
class fizz::detail::OpenSSLECKeyExchange< T >
Definition at line 13 of file OpenSSLKeyExchange-inl.h.
Member Function Documentation
template<class T> void fizz::detail::OpenSSLECKeyExchange< T >::generateKeyPair () inline
Definition at line 15 of file OpenSSLKeyExchange-inl.h.
References fizz::detail::generateECKeyPair(), and fizz::detail::OpenSSLECKeyExchange< T >::key_.
{
     key_ = generateECKeyPair(T::curveNid);
   }
template<class T> std::unique_ptr<folly::IOBuf> fizz::detail::OpenSSLECKeyExchange< T >::generateSharedSecret (const folly::ssl::EvpPkeyUniquePtr & peerKey) const inline
Definition at line 28 of file OpenSSLKeyExchange-inl.h.
References fizz::detail::generateEvpSharedSecret(), and fizz::detail::OpenSSLECKeyExchange< T >::key_.
Referenced by fizz::test::TEST_P().
{
     if (!key_) {
       throw std::runtime_error("Key not generated");
     }
     return generateEvpSharedSecret(key_, peerKey);
   }
template<class T> const folly::ssl::EvpPkeyUniquePtr& fizz::detail::OpenSSLECKeyExchange< T >::getKey () const inline
Definition at line 24 of file OpenSSLKeyExchange-inl.h.
References fizz::detail::OpenSSLECKeyExchange< T >::key_.
{
     return key_;
   }
template<class T> void fizz::detail::OpenSSLECKeyExchange< T >::setPrivateKey (folly::ssl::EvpPkeyUniquePtr privateKey) inline
Definition at line 19 of file OpenSSLKeyExchange-inl.h.
References fizz::detail::OpenSSLECKeyExchange< T >::key_, folly::gen::move, and fizz::detail::validateECKey().
Referenced by fizz::test::TEST_P().
{
     validateECKey(privateKey, T::curveNid);
     key_ = std::move(privateKey);
   }
Member Data Documentation
template<class T> folly::ssl::EvpPkeyUniquePtr fizz::detail::OpenSSLECKeyExchange< T >::key_ private
Definition at line 37 of file OpenSSLKeyExchange-inl.h.
Referenced by fizz::detail::OpenSSLECKeyExchange< T >::generateKeyPair(), fizz::detail::OpenSSLECKeyExchange< T >::generateSharedSecret(), fizz::detail::OpenSSLECKeyExchange< T >::getKey(), and fizz::detail::OpenSSLECKeyExchange< T >::setPrivateKey().
The documentation for this class was generated from the following file:
proxygen/fizz/fizz/crypto/exchange/OpenSSLKeyExchange-inl.h