proxygen: folly::AsyncUDPServerSocket::Callback Class Reference
folly::AsyncUDPServerSocket::Callback Class Reference abstract
#include <AsyncUDPServerSocket.h>
Public Member Functions
virtual void onListenStarted () noexcept=0
virtual void onListenStopped () noexcept=0
virtual void onListenPaused () noexcept
virtual void onListenResumed () noexcept
virtual void onDataAvailable (std::shared_ptr< AsyncUDPSocket > socket, const folly::SocketAddress &addr, std::unique_ptr< folly::IOBuf > buf, bool truncated) noexcept=0
virtual ~Callback ()=default
Detailed Description
Definition at line 41 of file AsyncUDPServerSocket.h.
Constructor & Destructor Documentation
virtual folly::AsyncUDPServerSocket::Callback::~Callback () virtual default
Referenced by onListenResumed().
Member Function Documentation
virtual void folly::AsyncUDPServerSocket::Callback::onDataAvailable (std::shared_ptr< AsyncUDPSocket > socket, const folly::SocketAddress & addr, std::unique_ptr< folly::IOBuf > buf, bool truncated) pure virtual noexcept
Invoked when a new packet is received
Implemented in wangle::Acceptor, and wangle::ServerAcceptor< Pipeline >.
Referenced by onListenResumed().
virtual void folly::AsyncUDPServerSocket::Callback::onListenPaused () inline virtual noexcept
Invoked when the server socket is paused. It is invoked in each acceptors/listeners event base thread.
Definition at line 59 of file AsyncUDPServerSocket.h.
 {}
virtual void folly::AsyncUDPServerSocket::Callback::onListenResumed () inline virtual noexcept
Invoked when the server socket is resumed. It is invoked in each acceptors/listeners event base thread.
Definition at line 65 of file AsyncUDPServerSocket.h.
References addr, onDataAvailable(), folly::netops::socket(), and ~Callback().
 {}
virtual void folly::AsyncUDPServerSocket::Callback::onListenStarted () pure virtual noexcept
Invoked when we start reading data from socket. It is invoked in each acceptors/listeners event base thread.
Implemented in wangle::Acceptor.
virtual void folly::AsyncUDPServerSocket::Callback::onListenStopped () pure virtual noexcept
Invoked when the server socket is closed. It is invoked in each acceptors/listeners event base thread.
Implemented in wangle::Acceptor.
The documentation for this class was generated from the following file:
proxygen/folly/folly/io/async/AsyncUDPServerSocket.h