proxygen: wangle::BroadcastPool< T, R, P >::BroadcastManager Class Reference
wangle::BroadcastPool< T, R, P >::BroadcastManager Class Reference
#include <BroadcastPool.h>
Public Types
using UniquePtr = std::unique_ptr< BroadcastManager, folly::DelayedDestruction::Destructor >
Public Member Functions
BroadcastManager (BroadcastPool< T, R, P > *broadcastPool, const R &routingData)
~BroadcastManager () override
folly::Future< BroadcastHandler< T, R > * > getHandler ()
void deletePipeline (PipelineBase *pipeline) override
Public Member Functions inherited from wangle::PipelineManager
virtual ~PipelineManager ()=default
virtual void refreshTimeout ()
Public Member Functions inherited from folly::DelayedDestruction
virtual void destroy ()
bool getDestroyPending () const
Public Member Functions inherited from folly::DelayedDestructionBase
virtual ~DelayedDestructionBase ()=default
Private Member Functions
void handleConnectError (const std::exception &ex) noexcept
Private Attributes
BroadcastPool< T, R, P > * broadcastPool_ {nullptr}
R routingData_
std::unique_ptr< BaseClientBootstrap< P > > client_
bool connectStarted_ {false}
bool deletingBroadcast_ {false}
folly::SharedPromise< BroadcastHandler< T, R > * > sharedPromise_
Additional Inherited Members
Protected Member Functions inherited from folly::DelayedDestruction
~DelayedDestruction () override=default
DelayedDestruction ()
Protected Member Functions inherited from folly::DelayedDestructionBase
DelayedDestructionBase ()
uint32_t getDestructorGuardCount () const
Detailed Description
template<typename T, typename R, typename P = DefaultPipeline>
class wangle::BroadcastPool< T, R, P >::BroadcastManager
Definition at line 52 of file BroadcastPool.h.
Member Typedef Documentation
template<typename T, typename R, typename P = DefaultPipeline> using wangle::BroadcastPool< T, R, P >::BroadcastManager::UniquePtr = std::unique_ptr< BroadcastManager, folly::DelayedDestruction::Destructor>
Definition at line 56 of file BroadcastPool.h.
Constructor & Destructor Documentation
template<typename T, typename R, typename P = DefaultPipeline> wangle::BroadcastPool< T, R, P >::BroadcastManager::BroadcastManager (BroadcastPool< T, R, P > * broadcastPool, const R & routingData) inline
Definition at line 58 of file BroadcastPool.h.
Referenced by wangle::BroadcastPool< T, R, P >::getHandler().
         : broadcastPool_(broadcastPool),
           routingData_(routingData),
           client_(broadcastPool_->clientBootstrapFactory_->newClient()) {
       client_->pipelineFactory(broadcastPool_->broadcastPipelineFactory_);
     }
template<typename T, typename R, typename P = DefaultPipeline> wangle::BroadcastPool< T, R, P >::BroadcastManager::~BroadcastManager () inline override
Definition at line 67 of file BroadcastPool.h.
References folly::pushmi::__adl::noexcept().
{
       if (client_->getPipeline()) {
         client_->getPipeline()->setPipelineManager(nullptr);
       }
     }
Member Function Documentation
template<typename T , typename R , typename P > void wangle::BroadcastPool< T, R, P >::BroadcastManager::deletePipeline (PipelineBase * pipeline) override virtual
Implements wangle::PipelineManager.
Definition at line 77 of file BroadcastPool-inl.h.
References wangle::BroadcastPool< T, R, P >::BroadcastManager::broadcastPool_, wangle::BroadcastPool< T, R, P >::BroadcastManager::client_, wangle::BroadcastPool< T, R, P >::BroadcastManager::deletingBroadcast_, and wangle::BroadcastPool< T, R, P >::BroadcastManager::routingData_.
{
   CHECK(client_->getPipeline() == pipeline);
   deletingBroadcast_ = true;
   broadcastPool_->deleteBroadcast(routingData_);
 }
template<typename T , typename R , typename P > folly::Future< BroadcastHandler< T, R > * > wangle::BroadcastPool< T, R, P >::BroadcastManager::getHandler ()
Definition at line 22 of file BroadcastPool-inl.h.
References wangle::BroadcastPool< T, R, P >::BroadcastManager::broadcastPool_, wangle::BroadcastPool< T, R, P >::BroadcastManager::client_, wangle::BroadcastPool< T, R, P >::BroadcastManager::connectStarted_, wangle::BroadcastPool< T, R, P >::BroadcastManager::deletingBroadcast_, wangle::BroadcastPool< T, R, P >::BroadcastManager::handleConnectError(), handler(), folly::InlineExecutor::instance(), wangle::BroadcastPool< T, R, P >::BroadcastManager::routingData_, wangle::PipelineBase::setPipelineManager(), and wangle::BroadcastPool< T, R, P >::BroadcastManager::sharedPromise_.
{
   // getFuture() returns a completed future if we are already connected
   // Set the executor to the InlineExecutor because subsequent code depends
   // on the future callback being called inline to ensure that the handler
   // is not garbage collected before use.
   auto future = sharedPromise_.getFuture().via(
     &folly::InlineExecutor::instance());
   if (connectStarted_) {
     // Either already connected, in which case the future has the handler,
     // or there's an outstanding connect request and the promise will be
     // fulfilled when the connect request completes.
     return future;
   }
   // Kickoff connect request and fulfill all pending promises on completion
   connectStarted_ = true;
   broadcastPool_->serverPool_->connect(client_.get(), routingData_)
       .thenValue([this](DefaultPipeline* pipeline) {
         DestructorGuard dg(this);
         pipeline->setPipelineManager(this);
         auto pipelineFactory = broadcastPool_->broadcastPipelineFactory_;
         try {
           pipelineFactory->setRoutingData(pipeline, routingData_);
         } catch (const std::exception& ex) {
           handleConnectError(ex);
           return;
         }
         if (deletingBroadcast_) {
           // setRoutingData() could result in an error that would cause the
           // BroadcastPipeline to get deleted.
           handleConnectError(std::runtime_error(
               "Broadcast deleted due to upstream connection error"));
           return;
         }
         auto handler = pipelineFactory->getBroadcastHandler(pipeline);
         CHECK(handler);
         sharedPromise_.setValue(handler);
         // If all the observers go away before connect returns, then the
         // BroadcastHandler will be idle without any subscribers. Close
         // the pipeline and remove the broadcast from the pool so that
         // connections are not leaked.
         handler->closeIfIdle();
       })
       .onError([this](const std::exception& ex) { handleConnectError(ex); });
   return future;
 }
template<typename T , typename R , typename P > void wangle::BroadcastPool< T, R, P >::BroadcastManager::handleConnectError (const std::exception & ex) private noexcept
Definition at line 85 of file BroadcastPool-inl.h.
References wangle::BroadcastPool< T, R, P >::BroadcastManager::broadcastPool_, folly::gen::move, wangle::BroadcastPool< T, R, P >::BroadcastManager::routingData_, and wangle::BroadcastPool< T, R, P >::BroadcastManager::sharedPromise_.
Referenced by wangle::BroadcastPool< T, R, P >::BroadcastManager::getHandler().
{
   LOG(ERROR) << "Error connecting to upstream: " << ex.what();
   auto sharedPromise = std::move(sharedPromise_);
   broadcastPool_->deleteBroadcast(routingData_);
   sharedPromise.setException(folly::make_exception_wrapper<std::exception>(ex));
 }
Member Data Documentation
template<typename T, typename R, typename P = DefaultPipeline> BroadcastPool<T, R, P>* wangle::BroadcastPool< T, R, P >::BroadcastManager::broadcastPool_ {nullptr} private
Definition at line 81 of file BroadcastPool.h.
Referenced by wangle::BroadcastPool< T, R, P >::BroadcastManager::deletePipeline(), wangle::BroadcastPool< T, R, P >::BroadcastManager::getHandler(), and wangle::BroadcastPool< T, R, P >::BroadcastManager::handleConnectError().
template<typename T, typename R, typename P = DefaultPipeline> std::unique_ptr<BaseClientBootstrap<P> > wangle::BroadcastPool< T, R, P >::BroadcastManager::client_ private
Definition at line 84 of file BroadcastPool.h.
Referenced by wangle::BroadcastPool< T, R, P >::BroadcastManager::deletePipeline(), and wangle::BroadcastPool< T, R, P >::BroadcastManager::getHandler().
template<typename T, typename R, typename P = DefaultPipeline> bool wangle::BroadcastPool< T, R, P >::BroadcastManager::connectStarted_ {false} private
Definition at line 86 of file BroadcastPool.h.
Referenced by wangle::BroadcastPool< T, R, P >::BroadcastManager::getHandler().
template<typename T, typename R, typename P = DefaultPipeline> bool wangle::BroadcastPool< T, R, P >::BroadcastManager::deletingBroadcast_ {false} private
Definition at line 87 of file BroadcastPool.h.
Referenced by wangle::BroadcastPool< T, R, P >::BroadcastManager::deletePipeline(), and wangle::BroadcastPool< T, R, P >::BroadcastManager::getHandler().
template<typename T, typename R, typename P = DefaultPipeline> R wangle::BroadcastPool< T, R, P >::BroadcastManager::routingData_ private
Definition at line 82 of file BroadcastPool.h.
Referenced by wangle::BroadcastPool< T, R, P >::BroadcastManager::deletePipeline(), wangle::BroadcastPool< T, R, P >::BroadcastManager::getHandler(), and wangle::BroadcastPool< T, R, P >::BroadcastManager::handleConnectError().
template<typename T, typename R, typename P = DefaultPipeline> folly::SharedPromise<BroadcastHandler<T, R>*> wangle::BroadcastPool< T, R, P >::BroadcastManager::sharedPromise_ private
Definition at line 88 of file BroadcastPool.h.
Referenced by wangle::BroadcastPool< T, R, P >::BroadcastManager::getHandler(), and wangle::BroadcastPool< T, R, P >::BroadcastManager::handleConnectError().
The documentation for this class was generated from the following files:
proxygen/wangle/wangle/channel/broadcast/BroadcastPool.h
proxygen/wangle/wangle/channel/broadcast/BroadcastPool-inl.h