proxygen: wangle::SSLSessionPersistentCacheBase< K > Class Template Reference
wangle::SSLSessionPersistentCacheBase< K > Class Template Reference abstract
#include <SSLSessionPersistentCache.h>
Classes
class TimeUtil
Public Member Functions
SSLSessionPersistentCacheBase (std::shared_ptr< PersistentCache< K, SSLSessionCacheData >> cache)
SSLSessionPersistentCacheBase (std::shared_ptr< folly::Executor > executor, const std::string &filename, std::size_t cacheCapacity, std::chrono::seconds syncInterval)
SSLSessionPersistentCacheBase (const std::string &filename, std::size_t cacheCapacity, std::chrono::seconds syncInterval)
void setSSLSession (const std::string &identity, SSLSessionPtr session) noexceptoverride
SSLSessionPtr getSSLSession (const std::string &identity) const noexceptoverride
bool removeSSLSession (const std::string &identity) noexceptoverride
bool supportsPersistence () const noexceptoverride
void setTimeUtil (std::unique_ptr< TimeUtil > timeUtil) noexcept
size_t size () const override
Public Member Functions inherited from wangle::SSLSessionCallbacks
virtual ~SSLSessionCallbacks ()
Protected Member Functions
virtual K getKey (const std::string &identity) const =0
Protected Attributes
std::shared_ptr< PersistentCache< K, SSLSessionCacheData > > persistentCache_
std::unique_ptr< TimeUtil > timeUtil_
Additional Inherited Members
Static Public Member Functions inherited from wangle::SSLSessionCallbacks
static void attachCallbacksToContext (SSL_CTX *ctx, SSLSessionCallbacks *callbacks)
static void detachCallbacksFromContext (SSL_CTX *ctx, SSLSessionCallbacks *callbacks)
static SSLSessionCallbacks * getCacheFromContext (SSL_CTX *ctx)
Detailed Description
template<typename K>
class wangle::SSLSessionPersistentCacheBase< K >
This cache is as threadsafe as the underlying PersistentCache used. Multiple instances may delegate to the same persistence layer
Definition at line 38 of file SSLSessionPersistentCache.h.
Constructor & Destructor Documentation
template<typename K> wangle::SSLSessionPersistentCacheBase< K >::SSLSessionPersistentCacheBase (std::shared_ptr< PersistentCache< K, SSLSessionCacheData >> cache) explicit
Definition at line 28 of file SSLSessionPersistentCache-inl.h.
Referenced by wangle::SSLSessionPersistentCacheBase< K >::TimeUtil::now().
                                                                   :
   persistentCache_(cache),
   timeUtil_(new TimeUtil()) {}
template<typename K> wangle::SSLSessionPersistentCacheBase< K >::SSLSessionPersistentCacheBase (std::shared_ptr< folly::Executor > executor, const std::string & filename, std::size_t cacheCapacity, std::chrono::seconds syncInterval)
Definition at line 34 of file SSLSessionPersistentCache-inl.h.
     : SSLSessionPersistentCacheBase(
           std::make_shared<FilePersistentCache<K, SSLSessionCacheData>>(
               std::move(executor),
               filename,
               cacheCapacity,
               syncInterval,
               client::persistence::DEFAULT_CACHE_SYNC_RETRIES)) {}
template<typename K> wangle::SSLSessionPersistentCacheBase< K >::SSLSessionPersistentCacheBase (const std::string & filename, std::size_t cacheCapacity, std::chrono::seconds syncInterval)
Definition at line 48 of file SSLSessionPersistentCache-inl.h.
     : SSLSessionPersistentCacheBase(
           std::make_shared<FilePersistentCache<K, SSLSessionCacheData>>(
               filename,
               cacheCapacity,
               syncInterval)) {}
Member Function Documentation
template<typename K> virtual K wangle::SSLSessionPersistentCacheBase< K >::getKey (const std::string & identity) const protected pure virtual
Implemented in wangle::SSLSessionPersistentCache.
Referenced by wangle::SSLSessionPersistentCacheBase< K >::getSSLSession(), wangle::SSLSessionPersistentCacheBase< K >::removeSSLSession(), wangle::SSLSessionPersistentCacheBase< K >::setSSLSession(), and wangle::SSLSessionPersistentCacheBase< std::string >::setTimeUtil().
template<typename K > SSLSessionPtr wangle::SSLSessionPersistentCacheBase< K >::getSSLSession (const std::string & identity) const override virtual noexcept
Implements wangle::SSLSessionCallbacks.
Definition at line 76 of file SSLSessionPersistentCache-inl.h.
References wangle::SSLSessionPersistentCacheBase< K >::getKey(), wangle::getSessionFromCacheData(), now(), wangle::SSLSessionPersistentCacheBase< K >::persistentCache_, folly::portability::ssl::SSL_SESSION_get_ticket_lifetime_hint(), folly::portability::ssl::SSL_SESSION_has_ticket(), wangle::SSLSessionPersistentCacheBase< K >::timeUtil_, and value.
Referenced by wangle::SSLSessionPersistentCacheBase< K >::TimeUtil::now().
{
   auto key = getKey(identity);
   auto hit = persistentCache_->get(key);
   if (!hit) {
     return nullptr;
   }
   // Create a SSL_SESSION and return. In failure it returns nullptr.
   auto& value = hit.value();
   auto sess = SSLSessionPtr(getSessionFromCacheData(value));
 #if OPENSSL_TICKETS
   if (sess &&
       SSL_SESSION_has_ticket(sess.get()) &&
       SSL_SESSION_get_ticket_lifetime_hint(sess.get()) > 0) {
     auto now = timeUtil_->now();
     auto secsBetween =
       std::chrono::duration_cast<std::chrono::seconds>(now - value.addedTime);
     if (secsBetween >= std::chrono::seconds(SSL_SESSION_get_ticket_lifetime_hint(sess.get()))) {
       return nullptr;
     }
   }
 #endif
   return sess;
 }
template<typename K > bool wangle::SSLSessionPersistentCacheBase< K >::removeSSLSession (const std::string & identity) override virtual noexcept
Implements wangle::SSLSessionCallbacks.
Definition at line 105 of file SSLSessionPersistentCache-inl.h.
References wangle::SSLSessionPersistentCacheBase< K >::getKey(), and wangle::SSLSessionPersistentCacheBase< K >::persistentCache_.
Referenced by wangle::SSLSessionPersistentCacheBase< K >::TimeUtil::now().
{
   auto key = getKey(identity);
   return persistentCache_->remove(key);
 }
template<typename K > void wangle::SSLSessionPersistentCacheBase< K >::setSSLSession (const std::string & identity, SSLSessionPtr session) override virtual noexcept
Implements wangle::SSLSessionCallbacks.
Definition at line 59 of file SSLSessionPersistentCache-inl.h.
References wangle::getCacheDataForSession(), wangle::SSLSessionPersistentCacheBase< K >::getKey(), wangle::SSLSessionPersistentCacheBase< K >::persistentCache_, and wangle::SSLSessionPersistentCacheBase< K >::timeUtil_.
Referenced by wangle::SSLSessionPersistentCacheBase< K >::TimeUtil::now().
{
   if (!session) {
     return;
   }
   // We do not cache the session itself, but cache the session data from it in
   // order to recreate a new session later.
   auto sessionCacheData = getCacheDataForSession(session.get());
   if (sessionCacheData) {
     auto key = getKey(identity);
     sessionCacheData->addedTime = timeUtil_->now();
     persistentCache_->put(key, *sessionCacheData);
   }
 }
template<typename K> void wangle::SSLSessionPersistentCacheBase< K >::setTimeUtil (std::unique_ptr< TimeUtil > timeUtil) inline noexcept
Definition at line 86 of file SSLSessionPersistentCache.h.
{
     timeUtil_ = std::move(timeUtil);
   }
template<typename K > size_t wangle::SSLSessionPersistentCacheBase< K >::size () const override virtual
Reimplemented from wangle::SSLSessionCallbacks.
Definition at line 112 of file SSLSessionPersistentCache-inl.h.
References wangle::SSLSessionPersistentCacheBase< K >::persistentCache_.
Referenced by wangle::SSLSessionPersistentCacheBase< std::string >::setTimeUtil().
{
   return persistentCache_->size();
 }
template<typename K> bool wangle::SSLSessionPersistentCacheBase< K >::supportsPersistence () const inline override virtual noexcept
Reimplemented from wangle::SSLSessionCallbacks.
Definition at line 82 of file SSLSessionPersistentCache.h.
{
     return true;
   }
Member Data Documentation
template<typename K> std::shared_ptr<PersistentCache<K, SSLSessionCacheData> > wangle::SSLSessionPersistentCacheBase< K >::persistentCache_ protected
Definition at line 98 of file SSLSessionPersistentCache.h.
Referenced by wangle::SSLSessionPersistentCacheBase< K >::getSSLSession(), wangle::SSLSessionPersistentCacheBase< K >::removeSSLSession(), wangle::SSLSessionPersistentCacheBase< K >::setSSLSession(), and wangle::SSLSessionPersistentCacheBase< K >::size().
template<typename K> std::unique_ptr<TimeUtil> wangle::SSLSessionPersistentCacheBase< K >::timeUtil_ protected
Definition at line 99 of file SSLSessionPersistentCache.h.
Referenced by wangle::SSLSessionPersistentCacheBase< K >::getSSLSession(), wangle::SSLSessionPersistentCacheBase< K >::setSSLSession(), and wangle::SSLSessionPersistentCacheBase< std::string >::setTimeUtil().
The documentation for this class was generated from the following files:
proxygen/wangle/wangle/client/ssl/SSLSessionPersistentCache.h
proxygen/wangle/wangle/client/ssl/SSLSessionPersistentCache-inl.h