proxygen: folly::TestSSLServer Class Reference
folly::TestSSLServer Class Reference
#include <TestSSLServer.h>
Public Member Functions
TestSSLServer (SSLServerAcceptCallbackBase *acb, bool enableTFO=false)
TestSSLServer (SSLServerAcceptCallbackBase *acb, std::shared_ptr< SSLContext > ctx, bool enableTFO=false)
virtual ~TestSSLServer ()
EventBase & getEventBase ()
void loadTestCerts ()
const SocketAddress & getAddress () const
Protected Attributes
EventBase evb_
std::shared_ptr< SSLContext > ctx_
SSLServerAcceptCallbackBase * acb_
std::shared_ptr< AsyncServerSocket > socket_
SocketAddress address_
std::thread thread_
Private Member Functions
void init (bool)
Detailed Description
Definition at line 101 of file TestSSLServer.h.
Constructor & Destructor Documentation
folly::TestSSLServer::TestSSLServer (SSLServerAcceptCallbackBase * acb, bool enableTFO = false) explicit
Definition at line 36 of file TestSSLServer.cpp.
References ctx_, and init().
     : acb_(acb) {
   // Set up a default SSL context
   ctx_ = std::make_shared<SSLContext>();
   ctx_->loadCertificate(kTestCert);
   ctx_->loadPrivateKey(kTestKey);
   ctx_->ciphers("ALL:!ADH:!LOW:!EXP:!MD5:@STRENGTH");
   init(enableTFO);
 }
folly::TestSSLServer::TestSSLServer (SSLServerAcceptCallbackBase * acb, std::shared_ptr< SSLContext > ctx, bool enableTFO = false) explicit
Definition at line 52 of file TestSSLServer.cpp.
References init().
     : ctx_(ctx), acb_(acb) {
   init(enableTFO);
 }
folly::TestSSLServer::~TestSSLServer () virtual
Definition at line 28 of file TestSSLServer.cpp.
References evb_, folly::INFO, folly::EventBase::runInEventBaseThread(), socket_, and thread_.
{
   if (thread_.joinable()) {
     evb_.runInEventBaseThread([&]() { socket_->stopAccepting(); });
     LOG(INFO) << "Waiting for server thread to exit";
     thread_.join();
   }
 }
Member Function Documentation
const SocketAddress& folly::TestSSLServer::getAddress () const inline
Definition at line 122 of file TestSSLServer.h.
Referenced by folly::TEST().
{
     return address_;
   }
EventBase& folly::TestSSLServer::getEventBase () inline
Definition at line 116 of file TestSSLServer.h.
References evb_.
Referenced by folly::TEST().
{
     return evb_;
   }
void folly::TestSSLServer::init (bool enableTFO) private
Definition at line 60 of file TestSSLServer.cpp.
References acb_, address_, folly::SSLServerAcceptCallbackBase::base_, folly::SSLServerAcceptCallbackBase::ctx_, ctx_, folly::SSLServerAcceptCallbackBase::detach(), evb_, folly::INFO, folly::EventBase::loop(), folly::AsyncServerSocket::newSocket(), socket_, and thread_.
Referenced by TestSSLServer().
{
   socket_ = AsyncServerSocket::newSocket(&evb_);
   acb_->ctx_ = ctx_;
   acb_->base_ = &evb_;
   // Enable TFO
   if (enableTFO) {
     LOG(INFO) << "server TFO enabled";
     socket_->setTFOEnabled(true, 1000);
   }
   // set up the listening socket
   socket_->bind(0);
   socket_->getAddress(&address_);
   socket_->listen(100);
   socket_->addAcceptCallback(acb_, &evb_);
   socket_->startAccepting();
   thread_ = std::thread([&] {
     evb_.loop();
     acb_->detach();
     LOG(INFO) << "Server thread exited event loop";
   });
   LOG(INFO) << "Accepting connections on " << address_;
 }
void folly::TestSSLServer::loadTestCerts ()
Definition at line 47 of file TestSSLServer.cpp.
References ctx_.
{
   ctx_->loadCertificate(kTestCert);
   ctx_->loadPrivateKey(kTestKey);
 }
Member Data Documentation
SSLServerAcceptCallbackBase* folly::TestSSLServer::acb_ protected
Definition at line 129 of file TestSSLServer.h.
Referenced by init().
SocketAddress folly::TestSSLServer::address_ protected
Definition at line 131 of file TestSSLServer.h.
Referenced by init().
std::shared_ptr<SSLContext> folly::TestSSLServer::ctx_ protected
Definition at line 128 of file TestSSLServer.h.
Referenced by init(), loadTestCerts(), and TestSSLServer().
EventBase folly::TestSSLServer::evb_ protected
Definition at line 127 of file TestSSLServer.h.
Referenced by init(), and ~TestSSLServer().
std::shared_ptr<AsyncServerSocket> folly::TestSSLServer::socket_ protected
Definition at line 130 of file TestSSLServer.h.
Referenced by init(), and ~TestSSLServer().
std::thread folly::TestSSLServer::thread_ protected
Definition at line 132 of file TestSSLServer.h.
Referenced by init(), and ~TestSSLServer().
The documentation for this class was generated from the following files:
proxygen/folly/folly/io/async/test/TestSSLServer.h
proxygen/folly/folly/io/async/test/TestSSLServer.cpp