proxygen: folly::ScopedEventBaseThread Class Reference
folly::ScopedEventBaseThread Class Reference
#include <ScopedEventBaseThread.h>
Public Member Functions
ScopedEventBaseThread ()
ScopedEventBaseThread (const StringPiece &name)
ScopedEventBaseThread (EventBaseManager *ebm)
ScopedEventBaseThread (EventBaseManager *ebm, const StringPiece &name)
~ScopedEventBaseThread ()
EventBase * getEventBase () const
EventBase * getEventBase () override
std::thread::id getThreadId () const
void add (Func func) override
Public Member Functions inherited from folly::IOExecutor
~IOExecutor () override=default
Public Member Functions inherited from folly::Executor
virtual ~Executor ()
virtual void addWithPriority (Func, int8_t priority)
virtual uint8_t getNumPriorities () const
Private Member Functions
ScopedEventBaseThread (ScopedEventBaseThread &&other)=delete
ScopedEventBaseThread & operator= (ScopedEventBaseThread &&other)=delete
ScopedEventBaseThread (const ScopedEventBaseThread &other)=delete
ScopedEventBaseThread & operator= (const ScopedEventBaseThread &other)=delete
Private Attributes
EventBaseManager * ebm_
union {
EventBase eb_
};
std::thread th_
folly::Baton stop_
Additional Inherited Members
Static Public Member Functions inherited from folly::Executor
template<typename ExecutorT >
static KeepAlive< ExecutorT > getKeepAliveToken (ExecutorT *executor)
template<typename ExecutorT >
static KeepAlive< ExecutorT > getKeepAliveToken (ExecutorT &executor)
Static Public Attributes inherited from folly::Executor
static const int8_t LO_PRI = SCHAR_MIN
static const int8_t MID_PRI = 0
static const int8_t HI_PRI = SCHAR_MAX
Protected Member Functions inherited from folly::Executor
virtual bool keepAliveAcquire ()
virtual void keepAliveRelease ()
Static Protected Member Functions inherited from folly::Executor
template<typename ExecutorT >
static bool isKeepAliveDummy (const KeepAlive< ExecutorT > &keepAlive)
template<typename ExecutorT >
static KeepAlive< ExecutorT > makeKeepAlive (ExecutorT *executor)
Detailed Description
A helper class to start a new thread running a EventBase loop.
The new thread will be started by the ScopedEventBaseThread constructor. When the ScopedEventBaseThread object is destroyed, the thread will be stopped.
Definition at line 39 of file ScopedEventBaseThread.h.
Constructor & Destructor Documentation
folly::ScopedEventBaseThread::ScopedEventBaseThread ()
Definition at line 50 of file ScopedEventBaseThread.cpp.
Referenced by add().
     : ScopedEventBaseThread(nullptr, "") {}
folly::ScopedEventBaseThread::ScopedEventBaseThread (const StringPiece & name) explicit
Definition at line 53 of file ScopedEventBaseThread.cpp.
     : ScopedEventBaseThread(nullptr, name) {}
folly::ScopedEventBaseThread::ScopedEventBaseThread (EventBaseManager * ebm) explicit
Definition at line 56 of file ScopedEventBaseThread.cpp.
     : ScopedEventBaseThread(ebm, "") {}
folly::ScopedEventBaseThread::ScopedEventBaseThread (EventBaseManager * ebm, const StringPiece & name) explicit
Definition at line 59 of file ScopedEventBaseThread.cpp.
References eb_, ebm_, folly::run(), stop_, th_, and folly::EventBase::waitUntilRunning().
     : ebm_(ebm ? ebm : EventBaseManager::get()) {
   new (&eb_) EventBase();
   th_ = thread(run, ebm_, &eb_, &stop_, name);
   eb_.waitUntilRunning();
 }
folly::ScopedEventBaseThread::~ScopedEventBaseThread ()
Definition at line 68 of file ScopedEventBaseThread.cpp.
References eb_, folly::Baton< MayBlock, Atom >::post(), stop_, folly::EventBase::terminateLoopSoon(), and th_.
{
   eb_.terminateLoopSoon();
   stop_.post();
   th_.join();
 }
folly::ScopedEventBaseThread::ScopedEventBaseThread (ScopedEventBaseThread && other) private delete
folly::ScopedEventBaseThread::ScopedEventBaseThread (const ScopedEventBaseThread & other) private delete
Member Function Documentation
void folly::ScopedEventBaseThread::add (Func) inline override virtual
Enqueue a function to executed by this executor. This and all variants must be threadsafe.
Implements folly::Executor.
Definition at line 61 of file ScopedEventBaseThread.h.
References folly::EventBase::add(), getEventBase(), folly::gen::move, operator=(), and ScopedEventBaseThread().
{
     getEventBase()->add(std::move(func));
   }
EventBase* folly::ScopedEventBaseThread::getEventBase () const inline
Definition at line 49 of file ScopedEventBaseThread.h.
References eb_.
Referenced by add(), folly::EvbAndContext::getEventBase(), QueueTest::sendOne(), folly::TEST(), TEST(), and TEST_F().
{
     return &eb_;
   }
EventBase* folly::ScopedEventBaseThread::getEventBase () inline override virtual
Implements folly::IOExecutor.
Definition at line 53 of file ScopedEventBaseThread.h.
References eb_.
{
     return &eb_;
   }
std::thread::id folly::ScopedEventBaseThread::getThreadId () const inline
Definition at line 57 of file ScopedEventBaseThread.h.
References th_.
Referenced by TEST_F().
{
     return th_.get_id();
   }
ScopedEventBaseThread& folly::ScopedEventBaseThread::operator= (ScopedEventBaseThread && other) private delete
Referenced by add().
ScopedEventBaseThread& folly::ScopedEventBaseThread::operator= (const ScopedEventBaseThread & other) private delete
Member Data Documentation
union { ... }
EventBase folly::ScopedEventBaseThread::eb_ mutable
Definition at line 74 of file ScopedEventBaseThread.h.
Referenced by getEventBase(), ScopedEventBaseThread(), and ~ScopedEventBaseThread().
EventBaseManager* folly::ScopedEventBaseThread::ebm_ private
Definition at line 72 of file ScopedEventBaseThread.h.
Referenced by ScopedEventBaseThread().
folly::Baton folly::ScopedEventBaseThread::stop_ private
Definition at line 77 of file ScopedEventBaseThread.h.
Referenced by ScopedEventBaseThread(), and ~ScopedEventBaseThread().
std::thread folly::ScopedEventBaseThread::th_ private
Definition at line 76 of file ScopedEventBaseThread.h.
Referenced by getThreadId(), ScopedEventBaseThread(), and ~ScopedEventBaseThread().
The documentation for this class was generated from the following files:
proxygen/folly/folly/io/async/ScopedEventBaseThread.h
proxygen/folly/folly/io/async/ScopedEventBaseThread.cpp