proxygen: fizz::server::ServerStateMachine Class Reference
fizz::server::ServerStateMachine Class Reference
#include <ServerProtocol.h>
Public Types
using StateType = State
using ProcessingActions = AsyncActions
using CompletedActions = Actions
Public Member Functions
virtual ~ServerStateMachine ()=default
virtual AsyncActions processAccept (const State &, folly::Executor *executor, std::shared_ptr< const FizzServerContext > context, const std::shared_ptr< ServerExtensions > &extensions)
virtual AsyncActions processSocketData (const State &, folly::IOBufQueue &)
virtual AsyncActions processWriteNewSessionTicket (const State &, WriteNewSessionTicket)
virtual AsyncActions processAppWrite (const State &, AppWrite)
virtual AsyncActions processEarlyAppWrite (const State &, EarlyAppWrite)
virtual Actions processAppClose (const State &)
Detailed Description
Definition at line 25 of file ServerProtocol.h.
Member Typedef Documentation
using fizz::server::ServerStateMachine::CompletedActions = Actions
Definition at line 29 of file ServerProtocol.h.
using fizz::server::ServerStateMachine::ProcessingActions = AsyncActions
Definition at line 28 of file ServerProtocol.h.
using fizz::server::ServerStateMachine::StateType = State
Definition at line 27 of file ServerProtocol.h.
Constructor & Destructor Documentation
virtual fizz::server::ServerStateMachine::~ServerStateMachine () virtual default
Member Function Documentation
AsyncActions fizz::server::ServerStateMachine::processAccept (const State & state, folly::Executor * executor, std::shared_ptr< const FizzServerContext > context, const std::shared_ptr< ServerExtensions > & extensions) virtual
Reimplemented in fizz::server::test::MockServerStateMachine.
Definition at line 121 of file ServerProtocol.cpp.
References folly::netops::accept(), fizz::Accept::context, fizz::Accept::executor, folly::pushmi::executor, fizz::Accept::extensions, folly::gen::move, and fizz::server::detail::processEvent().
{
   Accept accept;
   accept.executor = executor;
   accept.context = std::move(context);
   accept.extensions = extensions;
   return detail::processEvent(state, std::move(accept));
 }
Actions fizz::server::ServerStateMachine::processAppClose (const State & state) virtual
Reimplemented in fizz::server::test::MockServerStateMachine.
Definition at line 174 of file ServerProtocol.cpp.
References fizz::server::detail::handleAppClose().
Referenced by fizz::server::test::TEST_F().
{
   return detail::handleAppClose(state);
 }
AsyncActions fizz::server::ServerStateMachine::processAppWrite (const State & state, AppWrite write) virtual
Reimplemented in fizz::server::test::MockServerStateMachine.
Definition at line 162 of file ServerProtocol.cpp.
References folly::gen::move, and fizz::server::detail::processEvent().
                     {
   return detail::processEvent(state, std::move(write));
 }
AsyncActions fizz::server::ServerStateMachine::processEarlyAppWrite (const State & state, EarlyAppWrite write) virtual
Reimplemented in fizz::server::test::MockServerStateMachine.
Definition at line 168 of file ServerProtocol.cpp.
References folly::gen::move, and fizz::server::detail::processEvent().
{
   return detail::processEvent(state, std::move(write));
 }
AsyncActions fizz::server::ServerStateMachine::processSocketData (const State & state, folly::IOBufQueue & buf) virtual
Reimplemented in fizz::server::test::MockServerStateMachine.
Definition at line 133 of file ServerProtocol.cpp.
References fizz::server::detail::actions(), fizz::decode_error, fizz::server::detail::handleError(), folly::gen::move, folly::none, fizz::server::detail::processEvent(), fizz::ReadRecordLayer::readEvent(), and fizz::server::State::readRecordLayer().
{
   try {
     if (!state.readRecordLayer()) {
       return detail::handleError(
           state,
           ReportError("attempting to process data without record layer"),
           folly::none);
     }
     auto param = state.readRecordLayer()->readEvent(buf);
     if (!param.hasValue()) {
       return actions(WaitForData());
     }
     return detail::processEvent(state, std::move(*param));
   } catch (const std::exception& e) {
     return detail::handleError(
         state,
         ReportError(folly::exception_wrapper(std::current_exception(), e)),
         AlertDescription::decode_error);
   }
 }
AsyncActions fizz::server::ServerStateMachine::processWriteNewSessionTicket (const State & state, WriteNewSessionTicket write) virtual
Reimplemented in fizz::server::test::MockServerStateMachine.
Definition at line 156 of file ServerProtocol.cpp.
References folly::gen::move, and fizz::server::detail::processEvent().
{
   return detail::processEvent(state, std::move(write));
 }
The documentation for this class was generated from the following files:
proxygen/fizz/fizz/server/ServerProtocol.h
proxygen/fizz/fizz/server/ServerProtocol.cpp