proxygen: counted_ptr< T, Atom > Class Template Reference
counted_ptr< T, Atom > Class Template Reference
#include <AtomicSharedPtrCounted.h>
Public Member Functions
counted_ptr ()
counted_ptr (counted_shared_tag, T *p)
counted_ptr (const counted_ptr &o)
counted_ptr & operator= (const counted_ptr &o)
counted_ptr (T *p)
~counted_ptr ()
std::add_lvalue_reference< T >::type operator* () const
T * get () const
T * operator-> () const
operator bool () const
bool operator== (const counted_ptr< T, Atom > &p) const
Public Attributes
T * p_
Additional Inherited Members
Static Protected Member Functions inherited from counted_ptr_base< Atom >
static intrusive_shared_count< Atom > * getRef (void *pt)
Detailed Description
template<typename T, template< typename > class Atom = std::atomic>
class counted_ptr< T, Atom >
Definition at line 47 of file AtomicSharedPtrCounted.h.
Constructor & Destructor Documentation
template<typename T, template< typename > class Atom = std::atomic> counted_ptr< T, Atom >::counted_ptr () inline
Definition at line 50 of file AtomicSharedPtrCounted.h.
 : p_(nullptr) {}
template<typename T, template< typename > class Atom = std::atomic> counted_ptr< T, Atom >::counted_ptr (counted_shared_tag , T * p) inline
Definition at line 51 of file AtomicSharedPtrCounted.h.
References counted_ptr_base< Atom >::getRef().
                                         : p_(p) {
     if (p_) {
       counted_ptr_base<Atom>::getRef(p_)->add_ref();
     }
   }
template<typename T, template< typename > class Atom = std::atomic> counted_ptr< T, Atom >::counted_ptr (const counted_ptr< T, Atom > & o) inline
Definition at line 57 of file AtomicSharedPtrCounted.h.
References counted_ptr_base< Atom >::getRef().
                                     : p_(o.p_) {
     if (p_) {
       counted_ptr_base<Atom>::getRef(p_)->add_ref();
     }
   }
template<typename T, template< typename > class Atom = std::atomic> counted_ptr< T, Atom >::counted_ptr (T * p) inline explicit
Definition at line 73 of file AtomicSharedPtrCounted.h.
                              : p_(p) {
     CHECK(!p);
   }
template<typename T, template< typename > class Atom = std::atomic> counted_ptr< T, Atom >::~counted_ptr () inline
Definition at line 76 of file AtomicSharedPtrCounted.h.
References bm::free().
                  {
     if (p_ && counted_ptr_base<Atom>::getRef(p_)->release_ref() == 1) {
       p_->~T();
       free(counted_ptr_base<Atom>::getRef(p_));
     }
   }
Member Function Documentation
template<typename T, template< typename > class Atom = std::atomic> T* counted_ptr< T, Atom >::get () const inline
Definition at line 86 of file AtomicSharedPtrCounted.h.
Referenced by counted_ptr< T, Atom >::operator==().
                  {
     return p_;
   }
template<typename T, template< typename > class Atom = std::atomic> counted_ptr< T, Atom >::operator bool () const inline explicit
Definition at line 92 of file AtomicSharedPtrCounted.h.
{
     return p_ == nullptr ? false : true;
   }
template<typename T, template< typename > class Atom = std::atomic> std::add_lvalue_reference<T>::type counted_ptr< T, Atom >::operator* () const inline
Definition at line 82 of file AtomicSharedPtrCounted.h.
{
     return *p_;
   }
template<typename T, template< typename > class Atom = std::atomic> T* counted_ptr< T, Atom >::operator-> () const inline
Definition at line 89 of file AtomicSharedPtrCounted.h.
{
     return p_;
   }
template<typename T, template< typename > class Atom = std::atomic> counted_ptr& counted_ptr< T, Atom >::operator= (const counted_ptr< T, Atom > & o) inline
Definition at line 62 of file AtomicSharedPtrCounted.h.
References bm::free(), counted_ptr_base< Atom >::getRef(), and counted_ptr< T, Atom >::p_.
{
     if (p_ && counted_ptr_base<Atom>::getRef(p_)->release_ref() == 1) {
       p_->~T();
       free(counted_ptr_base<Atom>::getRef(p_));
     }
     p_ = o.p_;
     if (p_) {
       counted_ptr_base<Atom>::getRef(p_)->add_ref();
     }
     return *this;
   }
template<typename T, template< typename > class Atom = std::atomic> bool counted_ptr< T, Atom >::operator== (const counted_ptr< T, Atom > & p) const inline
Definition at line 95 of file AtomicSharedPtrCounted.h.
References testing::Args(), Atom, counted_ptr< T, Atom >::get(), and T.
{
     return get() == p.get();
   }
Member Data Documentation
template<typename T, template< typename > class Atom = std::atomic> T* counted_ptr< T, Atom >::p_
Definition at line 49 of file AtomicSharedPtrCounted.h.
Referenced by counted_ptr_internals< Atom >::get_counted_base(), counted_ptr< T, Atom >::operator=(), and counted_ptr_internals< Atom >::release_ptr().
The documentation for this class was generated from the following file:
proxygen/folly/folly/concurrency/test/AtomicSharedPtrCounted.h