proxygen: fizz::Factory Class Reference
fizz::Factory Class Reference
#include <Factory.h>
Public Member Functions
virtual ~Factory ()=default
virtual std::unique_ptr< PlaintextReadRecordLayer > makePlaintextReadRecordLayer () const
virtual std::unique_ptr< PlaintextWriteRecordLayer > makePlaintextWriteRecordLayer () const
virtual std::unique_ptr< EncryptedReadRecordLayer > makeEncryptedReadRecordLayer (EncryptionLevel encryptionLevel) const
virtual std::unique_ptr< EncryptedWriteRecordLayer > makeEncryptedWriteRecordLayer (EncryptionLevel encryptionLevel) const
virtual std::unique_ptr< KeyScheduler > makeKeyScheduler (CipherSuite cipher) const
virtual std::unique_ptr< KeyDerivation > makeKeyDeriver (CipherSuite cipher) const
virtual std::unique_ptr< HandshakeContext > makeHandshakeContext (CipherSuite cipher) const
virtual std::unique_ptr< KeyExchange > makeKeyExchange (NamedGroup group) const
virtual std::unique_ptr< Aead > makeAead (CipherSuite cipher) const
virtual Random makeRandom () const
virtual uint32_t makeTicketAgeAdd () const
virtual std::shared_ptr< PeerCert > makePeerCert (Buf certData) const
virtual std::string getHkdfPrefix () const
Detailed Description
This class instantiates various objects to facilitate testing.
Definition at line 32 of file Factory.h.
Constructor & Destructor Documentation
virtual fizz::Factory::~Factory () virtual default
Member Function Documentation
virtual std::string fizz::Factory::getHkdfPrefix () const inline virtual
Definition at line 132 of file Factory.h.
References fizz::kHkdfLabelPrefix, and folly::Range< Iter >::str().
Referenced by makeHandshakeContext(), and makeKeyDeriver().
{
     return kHkdfLabelPrefix.str();
   }
virtual std::unique_ptr<Aead> fizz::Factory::makeAead (CipherSuite cipher) const inline virtual
Definition at line 105 of file Factory.h.
References fizz::TLS_AES_128_GCM_SHA256, fizz::TLS_AES_128_OCB_SHA256_EXPERIMENTAL, fizz::TLS_AES_256_GCM_SHA384, and fizz::TLS_CHACHA20_POLY1305_SHA256.
Referenced by fizz::Protocol::setAead().
{
     switch (cipher) {
       case CipherSuite::TLS_CHACHA20_POLY1305_SHA256:
         return std::make_unique<OpenSSLEVPCipher<ChaCha20Poly1305>>();
       case CipherSuite::TLS_AES_128_GCM_SHA256:
         return std::make_unique<OpenSSLEVPCipher<AESGCM128>>();
       case CipherSuite::TLS_AES_256_GCM_SHA384:
         return std::make_unique<OpenSSLEVPCipher<AESGCM256>>();
       case CipherSuite::TLS_AES_128_OCB_SHA256_EXPERIMENTAL:
         return std::make_unique<OpenSSLEVPCipher<AESOCB128>>();
       default:
         throw std::runtime_error("aead: not implemented");
     }
   }
virtual std::unique_ptr<EncryptedReadRecordLayer> fizz::Factory::makeEncryptedReadRecordLayer (EncryptionLevel encryptionLevel) const inline virtual
Definition at line 47 of file Factory.h.
Referenced by fizz::sm::generateTicket(), fizz::sm::getCertificateRequest(), fizz::sm::getMaxEarlyDataSize(), fizz::sm::handleCertMsg(), and fizz::sm::negotiatePsk().
{
     return std::make_unique<EncryptedReadRecordLayer>(encryptionLevel);
   }
virtual std::unique_ptr<EncryptedWriteRecordLayer> fizz::Factory::makeEncryptedWriteRecordLayer (EncryptionLevel encryptionLevel) const inline virtual
Definition at line 52 of file Factory.h.
Referenced by fizz::sm::generateTicket(), fizz::sm::getCertificateRequest(), fizz::sm::getMaxEarlyDataSize(), fizz::sm::handleCertMsg(), and fizz::sm::negotiatePsk().
{
     return std::make_unique<EncryptedWriteRecordLayer>(encryptionLevel);
   }
virtual std::unique_ptr<HandshakeContext> fizz::Factory::makeHandshakeContext (CipherSuite cipher) const inline virtual
Definition at line 76 of file Factory.h.
References getHkdfPrefix(), fizz::TLS_AES_128_GCM_SHA256, fizz::TLS_AES_128_OCB_SHA256_EXPERIMENTAL, fizz::TLS_AES_256_GCM_SHA384, and fizz::TLS_CHACHA20_POLY1305_SHA256.
Referenced by fizz::sm::getCertificateRequest(), fizz::server::getCookieState(), fizz::sm::getHrrKeyExchangers(), fizz::sm::negotiatePsk(), and fizz::sm::setupSchedulerAndContext().
{
     switch (cipher) {
       case CipherSuite::TLS_CHACHA20_POLY1305_SHA256:
       case CipherSuite::TLS_AES_128_GCM_SHA256:
       case CipherSuite::TLS_AES_128_OCB_SHA256_EXPERIMENTAL:
         return std::make_unique<HandshakeContextImpl<Sha256>>(getHkdfPrefix());
       case CipherSuite::TLS_AES_256_GCM_SHA384:
         return std::make_unique<HandshakeContextImpl<Sha384>>(getHkdfPrefix());
       default:
         throw std::runtime_error("hs: not implemented");
     }
   }
virtual std::unique_ptr<KeyDerivation> fizz::Factory::makeKeyDeriver (CipherSuite cipher) const inline virtual
Definition at line 62 of file Factory.h.
References getHkdfPrefix(), fizz::TLS_AES_128_GCM_SHA256, fizz::TLS_AES_128_OCB_SHA256_EXPERIMENTAL, fizz::TLS_AES_256_GCM_SHA384, and fizz::TLS_CHACHA20_POLY1305_SHA256.
Referenced by fizz::ExportedAuthenticator::getAuthenticator(), fizz::Exporter::getEkm(), fizz::LoggingFactory::makeKeyScheduler(), makeKeyScheduler(), fizz::test::AuthenticatorTest::SetUp(), fizz::test::ValidateAuthenticatorTest::SetUp(), and fizz::ExportedAuthenticator::validateAuthenticator().
{
     switch (cipher) {
       case CipherSuite::TLS_CHACHA20_POLY1305_SHA256:
       case CipherSuite::TLS_AES_128_GCM_SHA256:
       case CipherSuite::TLS_AES_128_OCB_SHA256_EXPERIMENTAL:
         return std::make_unique<KeyDerivationImpl<Sha256>>(getHkdfPrefix());
       case CipherSuite::TLS_AES_256_GCM_SHA384:
         return std::make_unique<KeyDerivationImpl<Sha384>>(getHkdfPrefix());
       default:
         throw std::runtime_error("ks: not implemented");
     }
   }
virtual std::unique_ptr<KeyExchange> fizz::Factory::makeKeyExchange (NamedGroup group) const inline virtual
Definition at line 90 of file Factory.h.
References fizz::secp256r1, fizz::secp384r1, fizz::secp521r1, and fizz::x25519.
Referenced by fizz::sm::doKex(), and fizz::sm::getKeyExchangers().
{
     switch (group) {
       case NamedGroup::secp256r1:
         return std::make_unique<OpenSSLKeyExchange<P256>>();
       case NamedGroup::secp384r1:
         return std::make_unique<OpenSSLKeyExchange<P384>>();
       case NamedGroup::secp521r1:
         return std::make_unique<OpenSSLKeyExchange<P521>>();
       case NamedGroup::x25519:
         return std::make_unique<X25519KeyExchange>();
       default:
         throw std::runtime_error("ke: not implemented");
     }
   }
virtual std::unique_ptr<KeyScheduler> fizz::Factory::makeKeyScheduler (CipherSuite cipher) const inline virtual
Reimplemented in fizz::LoggingFactory.
Definition at line 56 of file Factory.h.
References makeKeyDeriver(), and folly::gen::move.
Referenced by fizz::sm::getHrrKeyExchangers(), fizz::sm::negotiatePsk(), and fizz::sm::setupSchedulerAndContext().
{
     auto keyDer = makeKeyDeriver(cipher);
     return std::make_unique<KeyScheduler>(std::move(keyDer));
   }
virtual std::shared_ptr<PeerCert> fizz::Factory::makePeerCert (Buf certData) const inline virtual
Reimplemented in fizz::test::MockFactory, and fizz::JavaCryptoFactory.
Definition at line 128 of file Factory.h.
References fizz::CertUtils::makePeerCert(), and folly::gen::move.
Referenced by fizz::sm::generateTicket(), and fizz::sm::handleCertMsg().
{
     return CertUtils::makePeerCert(std::move(certData));
   }
virtual std::unique_ptr<PlaintextReadRecordLayer> fizz::Factory::makePlaintextReadRecordLayer () const inline virtual
Definition at line 37 of file Factory.h.
Referenced by fizz::sm::getCertificateRequest().
{
     return std::make_unique<PlaintextReadRecordLayer>();
   }
virtual std::unique_ptr<PlaintextWriteRecordLayer> fizz::Factory::makePlaintextWriteRecordLayer () const inline virtual
Definition at line 42 of file Factory.h.
{
     return std::make_unique<PlaintextWriteRecordLayer>();
   }
virtual Random fizz::Factory::makeRandom () const inline virtual
Definition at line 120 of file Factory.h.
Referenced by fizz::sm::getCertificateRequest().
{
     return RandomGenerator<Random().size()>().generateRandom();
   }
virtual uint32_t fizz::Factory::makeTicketAgeAdd () const inline virtual
Definition at line 124 of file Factory.h.
Referenced by fizz::sm::generateTicket().
{
     return RandomNumGenerator<uint32_t>().generateRandom();
   }
The documentation for this class was generated from the following file:
proxygen/fizz/fizz/protocol/Factory.h