proxygen: gtest_catch_exceptions_test.CatchSehExceptionsTest Class Reference
gtest_catch_exceptions_test.CatchSehExceptionsTest Class Reference
Public Member Functions
def TestSehExceptions (self, test_output)
def testCatchesSehExceptionsWithCxxExceptionsEnabled (self)
def testCatchesSehExceptionsWithCxxExceptionsDisabled (self)
def TestSehExceptions (self, test_output)
def testCatchesSehExceptionsWithCxxExceptionsEnabled (self)
def testCatchesSehExceptionsWithCxxExceptionsDisabled (self)
def TestSehExceptions (self, test_output)
def testCatchesSehExceptionsWithCxxExceptionsEnabled (self)
def testCatchesSehExceptionsWithCxxExceptionsDisabled (self)
Detailed Description
Tests exception-catching behavior.
Definition at line 85 of file gtest_catch_exceptions_test.py.
Member Function Documentation
def gtest_catch_exceptions_test.CatchSehExceptionsTest.testCatchesSehExceptionsWithCxxExceptionsDisabled (self)
Definition at line 110 of file gtest_catch_exceptions_test.py.
References gtest_catch_exceptions_test.CatchSehExceptionsTest.TestSehExceptions().
Referenced by gtest_catch_exceptions_test.CatchSehExceptionsTest.testCatchesSehExceptionsWithCxxExceptionsDisabled().
     def testCatchesSehExceptionsWithCxxExceptionsDisabled(self):
       self.TestSehExceptions(BINARY_OUTPUT)
def gtest_catch_exceptions_test.CatchSehExceptionsTest.testCatchesSehExceptionsWithCxxExceptionsDisabled (self)
Definition at line 110 of file gtest_catch_exceptions_test.py.
References gtest_test_utils.TestCase, gtest_catch_exceptions_test.CatchSehExceptionsTest.testCatchesSehExceptionsWithCxxExceptionsDisabled(), and gtest_catch_exceptions_test.CatchSehExceptionsTest.TestSehExceptions().
     def testCatchesSehExceptionsWithCxxExceptionsDisabled(self):
       self.TestSehExceptions(BINARY_OUTPUT)
def gtest_catch_exceptions_test.CatchSehExceptionsTest.testCatchesSehExceptionsWithCxxExceptionsDisabled (self)
Definition at line 110 of file gtest_catch_exceptions_test.py.
References gtest_test_utils.TestCase, gtest_catch_exceptions_test.CatchSehExceptionsTest.testCatchesSehExceptionsWithCxxExceptionsDisabled(), and gtest_catch_exceptions_test.CatchSehExceptionsTest.TestSehExceptions().
     def testCatchesSehExceptionsWithCxxExceptionsDisabled(self):
       self.TestSehExceptions(BINARY_OUTPUT)
def gtest_catch_exceptions_test.CatchSehExceptionsTest.testCatchesSehExceptionsWithCxxExceptionsEnabled (self)
Definition at line 107 of file gtest_catch_exceptions_test.py.
References gtest_catch_exceptions_test.CatchSehExceptionsTest.testCatchesSehExceptionsWithCxxExceptionsEnabled(), and gtest_catch_exceptions_test.CatchSehExceptionsTest.TestSehExceptions().
     def testCatchesSehExceptionsWithCxxExceptionsEnabled(self):
       self.TestSehExceptions(EX_BINARY_OUTPUT)
def gtest_catch_exceptions_test.CatchSehExceptionsTest.testCatchesSehExceptionsWithCxxExceptionsEnabled (self)
Definition at line 107 of file gtest_catch_exceptions_test.py.
References gtest_catch_exceptions_test.CatchSehExceptionsTest.testCatchesSehExceptionsWithCxxExceptionsEnabled(), and gtest_catch_exceptions_test.CatchSehExceptionsTest.TestSehExceptions().
     def testCatchesSehExceptionsWithCxxExceptionsEnabled(self):
       self.TestSehExceptions(EX_BINARY_OUTPUT)
def gtest_catch_exceptions_test.CatchSehExceptionsTest.testCatchesSehExceptionsWithCxxExceptionsEnabled (self)
Definition at line 107 of file gtest_catch_exceptions_test.py.
References gtest_catch_exceptions_test.CatchSehExceptionsTest.TestSehExceptions().
Referenced by gtest_catch_exceptions_test.CatchSehExceptionsTest.testCatchesSehExceptionsWithCxxExceptionsEnabled().
     def testCatchesSehExceptionsWithCxxExceptionsEnabled(self):
       self.TestSehExceptions(EX_BINARY_OUTPUT)
def gtest_catch_exceptions_test.CatchSehExceptionsTest.TestSehExceptions (self, test_output)
Definition at line 89 of file gtest_catch_exceptions_test.py.
References gtest_catch_exceptions_test.CatchSehExceptionsTest.TestSehExceptions().
     def TestSehExceptions(self, test_output):
       self.assert_('SEH exception with code 0x2a thrown '
                    'in the test fixture\'s constructor'
                    in test_output)
       self.assert_('SEH exception with code 0x2a thrown '
                    'in the test fixture\'s destructor'
                    in test_output)
       self.assert_('SEH exception with code 0x2a thrown in SetUpTestCase()'
                    in test_output)
       self.assert_('SEH exception with code 0x2a thrown in TearDownTestCase()'
                    in test_output)
       self.assert_('SEH exception with code 0x2a thrown in SetUp()'
                    in test_output)
       self.assert_('SEH exception with code 0x2a thrown in TearDown()'
                    in test_output)
       self.assert_('SEH exception with code 0x2a thrown in the test body'
                    in test_output)
def gtest_catch_exceptions_test.CatchSehExceptionsTest.TestSehExceptions (self, test_output)
Definition at line 89 of file gtest_catch_exceptions_test.py.
Referenced by gtest_catch_exceptions_test.CatchSehExceptionsTest.testCatchesSehExceptionsWithCxxExceptionsDisabled(), gtest_catch_exceptions_test.CatchSehExceptionsTest.testCatchesSehExceptionsWithCxxExceptionsEnabled(), and gtest_catch_exceptions_test.CatchSehExceptionsTest.TestSehExceptions().
     def TestSehExceptions(self, test_output):
       self.assert_('SEH exception with code 0x2a thrown '
                    'in the test fixture\'s constructor'
                    in test_output)
       self.assert_('SEH exception with code 0x2a thrown '
                    'in the test fixture\'s destructor'
                    in test_output)
       self.assert_('SEH exception with code 0x2a thrown in SetUpTestCase()'
                    in test_output)
       self.assert_('SEH exception with code 0x2a thrown in TearDownTestCase()'
                    in test_output)
       self.assert_('SEH exception with code 0x2a thrown in SetUp()'
                    in test_output)
       self.assert_('SEH exception with code 0x2a thrown in TearDown()'
                    in test_output)
       self.assert_('SEH exception with code 0x2a thrown in the test body'
                    in test_output)
def gtest_catch_exceptions_test.CatchSehExceptionsTest.TestSehExceptions (self, test_output)
Definition at line 89 of file gtest_catch_exceptions_test.py.
References gtest_catch_exceptions_test.CatchSehExceptionsTest.TestSehExceptions().
     def TestSehExceptions(self, test_output):
       self.assert_('SEH exception with code 0x2a thrown '
                    'in the test fixture\'s constructor'
                    in test_output)
       self.assert_('SEH exception with code 0x2a thrown '
                    'in the test fixture\'s destructor'
                    in test_output)
       self.assert_('SEH exception with code 0x2a thrown in SetUpTestCase()'
                    in test_output)
       self.assert_('SEH exception with code 0x2a thrown in TearDownTestCase()'
                    in test_output)
       self.assert_('SEH exception with code 0x2a thrown in SetUp()'
                    in test_output)
       self.assert_('SEH exception with code 0x2a thrown in TearDown()'
                    in test_output)
       self.assert_('SEH exception with code 0x2a thrown in the test body'
                    in test_output)
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest_catch_exceptions_test.py