proxygen: testing::internal::PointeeMatcher< InnerMatcher > Class Template Reference
testing::internal::PointeeMatcher< InnerMatcher > Class Template Reference
#include <gmock-matchers.h>
Classes
class Impl
Public Member Functions
PointeeMatcher (const InnerMatcher &matcher)
template<typename Pointer >
operator Matcher< Pointer > () const
PointeeMatcher (const InnerMatcher &matcher)
template<typename Pointer >
operator Matcher< Pointer > () const
PointeeMatcher (const InnerMatcher &matcher)
template<typename Pointer >
operator Matcher< Pointer > () const
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (PointeeMatcher)
GTEST_DISALLOW_ASSIGN_ (PointeeMatcher)
GTEST_DISALLOW_ASSIGN_ (PointeeMatcher)
Private Attributes
const InnerMatcher matcher_
Detailed Description
template<typename InnerMatcher>
class testing::internal::PointeeMatcher< InnerMatcher >
Definition at line 2043 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename InnerMatcher > testing::internal::PointeeMatcher< InnerMatcher >::PointeeMatcher (const InnerMatcher & matcher) inline explicit
Definition at line 2045 of file gmock-matchers.h.
 : matcher_(matcher) {}
template<typename InnerMatcher > testing::internal::PointeeMatcher< InnerMatcher >::PointeeMatcher (const InnerMatcher & matcher) inline explicit
Definition at line 2045 of file gmock-matchers.h.
 : matcher_(matcher) {}
template<typename InnerMatcher > testing::internal::PointeeMatcher< InnerMatcher >::PointeeMatcher (const InnerMatcher & matcher) inline explicit
Definition at line 2045 of file gmock-matchers.h.
 : matcher_(matcher) {}
Member Function Documentation
template<typename InnerMatcher > testing::internal::PointeeMatcher< InnerMatcher >::GTEST_DISALLOW_ASSIGN_ (PointeeMatcher< InnerMatcher >) private
template<typename InnerMatcher > testing::internal::PointeeMatcher< InnerMatcher >::GTEST_DISALLOW_ASSIGN_ (PointeeMatcher< InnerMatcher >) private
template<typename InnerMatcher > testing::internal::PointeeMatcher< InnerMatcher >::GTEST_DISALLOW_ASSIGN_ (PointeeMatcher< InnerMatcher >) private
template<typename InnerMatcher > template<typename Pointer > testing::internal::PointeeMatcher< InnerMatcher >::operator Matcher< Pointer > () const inline
Definition at line 2056 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(new Impl<Pointer>(matcher_));
   }
template<typename InnerMatcher > template<typename Pointer > testing::internal::PointeeMatcher< InnerMatcher >::operator Matcher< Pointer > () const inline
Definition at line 2056 of file gmock-matchers.h.
References GTEST_REMOVE_CONST_, and testing::MakeMatcher().
{
     return MakeMatcher(new Impl<Pointer>(matcher_));
   }
template<typename InnerMatcher > template<typename Pointer > testing::internal::PointeeMatcher< InnerMatcher >::operator Matcher< Pointer > () const inline
Definition at line 2056 of file gmock-matchers.h.
References GTEST_REMOVE_CONST_, and testing::MakeMatcher().
{
     return MakeMatcher(new Impl<Pointer>(matcher_));
   }
Member Data Documentation
template<typename InnerMatcher > const InnerMatcher testing::internal::PointeeMatcher< InnerMatcher >::matcher_ private
Definition at line 2096 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h