proxygen: fizz::test::MockFactory Class Reference
fizz::test::MockFactory Class Reference
#include <Mocks.h>
Public Member Functions
MOCK_CONST_METHOD0 (makePlaintextReadRecordLayer, std::unique_ptr< PlaintextReadRecordLayer >())
MOCK_CONST_METHOD0 (makePlaintextWriteRecordLayer, std::unique_ptr< PlaintextWriteRecordLayer >())
MOCK_CONST_METHOD1 (makeEncryptedReadRecordLayer, std::unique_ptr< EncryptedReadRecordLayer >(EncryptionLevel encryptionLevel))
MOCK_CONST_METHOD1 (makeEncryptedWriteRecordLayer, std::unique_ptr< EncryptedWriteRecordLayer >(EncryptionLevel encryptionLevel))
MOCK_CONST_METHOD1 (makeKeyScheduler, std::unique_ptr< KeyScheduler >(CipherSuite cipher))
MOCK_CONST_METHOD1 (makeHandshakeContext, std::unique_ptr< HandshakeContext >(CipherSuite cipher))
MOCK_CONST_METHOD1 (makeKeyExchange, std::unique_ptr< KeyExchange >(NamedGroup group))
MOCK_CONST_METHOD1 (makeAead, std::unique_ptr< Aead >(CipherSuite cipher))
MOCK_CONST_METHOD0 (makeRandom, Random())
MOCK_CONST_METHOD0 (makeTicketAgeAdd, uint32_t())
MOCK_CONST_METHOD1 (_makePeerCert, std::shared_ptr< PeerCert >(Buf &))
std::shared_ptr< PeerCert > makePeerCert (Buf certData) const override
void setDefaults ()
Public Member Functions inherited from fizz::Factory
virtual ~Factory ()=default
virtual std::unique_ptr< PlaintextReadRecordLayer > makePlaintextReadRecordLayer () const
virtual std::unique_ptr< PlaintextWriteRecordLayer > makePlaintextWriteRecordLayer () const
virtual std::unique_ptr< EncryptedReadRecordLayer > makeEncryptedReadRecordLayer (EncryptionLevel encryptionLevel) const
virtual std::unique_ptr< EncryptedWriteRecordLayer > makeEncryptedWriteRecordLayer (EncryptionLevel encryptionLevel) const
virtual std::unique_ptr< KeyScheduler > makeKeyScheduler (CipherSuite cipher) const
virtual std::unique_ptr< KeyDerivation > makeKeyDeriver (CipherSuite cipher) const
virtual std::unique_ptr< HandshakeContext > makeHandshakeContext (CipherSuite cipher) const
virtual std::unique_ptr< KeyExchange > makeKeyExchange (NamedGroup group) const
virtual std::unique_ptr< Aead > makeAead (CipherSuite cipher) const
virtual Random makeRandom () const
virtual uint32_t makeTicketAgeAdd () const
virtual std::string getHkdfPrefix () const
Detailed Description
Definition at line 144 of file Mocks.h.
Member Function Documentation
std::shared_ptr<PeerCert> fizz::test::MockFactory::makePeerCert (Buf certData) const inline override virtual
Reimplemented from fizz::Factory.
Definition at line 174 of file Mocks.h.
{
     return _makePeerCert(certData);
   }
fizz::test::MockFactory::MOCK_CONST_METHOD0 (makePlaintextReadRecordLayer , std::unique_ptr< PlaintextReadRecordLayer > ())
fizz::test::MockFactory::MOCK_CONST_METHOD0 (makePlaintextWriteRecordLayer , std::unique_ptr< PlaintextWriteRecordLayer > ())
fizz::test::MockFactory::MOCK_CONST_METHOD0 (makeRandom , Random())
fizz::test::MockFactory::MOCK_CONST_METHOD0 (makeTicketAgeAdd , uint32_t())
fizz::test::MockFactory::MOCK_CONST_METHOD1 (makeEncryptedReadRecordLayer , std::unique_ptr< EncryptedReadRecordLayer > EncryptionLevel encryptionLevel)
fizz::test::MockFactory::MOCK_CONST_METHOD1 (makeEncryptedWriteRecordLayer , std::unique_ptr< EncryptedWriteRecordLayer > EncryptionLevel encryptionLevel)
fizz::test::MockFactory::MOCK_CONST_METHOD1 (makeKeyScheduler , std::unique_ptr< KeyScheduler > CipherSuite cipher)
fizz::test::MockFactory::MOCK_CONST_METHOD1 (makeHandshakeContext , std::unique_ptr< HandshakeContext > CipherSuite cipher)
fizz::test::MockFactory::MOCK_CONST_METHOD1 (makeKeyExchange , std::unique_ptr< KeyExchange > NamedGroup group)
fizz::test::MockFactory::MOCK_CONST_METHOD1 (makeAead , std::unique_ptr< Aead > CipherSuite cipher)
fizz::test::MockFactory::MOCK_CONST_METHOD1 (_makePeerCert , std::shared_ptr< PeerCert > Buf &)
void fizz::test::MockFactory::setDefaults () inline
Definition at line 178 of file Mocks.h.
References testing::_, testing::Invoke(), testing::InvokeWithoutArgs(), makeRandom(), ON_CALL, and random().
                      {
     ON_CALL(*this, makePlaintextReadRecordLayer())
         .WillByDefault(InvokeWithoutArgs(
             []() { return std::make_unique<MockPlaintextReadRecordLayer>(); }));
     ON_CALL(*this, makePlaintextWriteRecordLayer())
         .WillByDefault(InvokeWithoutArgs([]() {
           auto ret = std::make_unique<MockPlaintextWriteRecordLayer>();
           ret->setDefaults();
           return ret;
         }));
     ON_CALL(*this, makeEncryptedReadRecordLayer(_))
         .WillByDefault(Invoke([](EncryptionLevel encryptionLevel) {
           return std::make_unique<MockEncryptedReadRecordLayer>(
               encryptionLevel);
         }));
     ON_CALL(*this, makeEncryptedWriteRecordLayer(_))
         .WillByDefault(Invoke([](EncryptionLevel encryptionLevel) {
           auto ret =
               std::make_unique<MockEncryptedWriteRecordLayer>(encryptionLevel);
           ret->setDefaults();
           return ret;
         }));
     ON_CALL(*this, makeKeyScheduler(_)).WillByDefault(InvokeWithoutArgs([]() {
       auto ret = std::make_unique<MockKeyScheduler>();
       ret->setDefaults();
       return ret;
     }));
     ON_CALL(*this, makeHandshakeContext(_))
         .WillByDefault(InvokeWithoutArgs([]() {
           auto ret = std::make_unique<MockHandshakeContext>();
           ret->setDefaults();
           return ret;
         }));
     ON_CALL(*this, makeKeyExchange(_)).WillByDefault(InvokeWithoutArgs([]() {
       auto ret = std::make_unique<MockKeyExchange>();
       ret->setDefaults();
       return ret;
     }));
     ON_CALL(*this, makeAead(_)).WillByDefault(InvokeWithoutArgs([]() {
       auto ret = std::make_unique<MockAead>();
       ret->setDefaults();
       return ret;
     }));
     ON_CALL(*this, makeRandom()).WillByDefault(InvokeWithoutArgs([]() {
       Random random;
       random.fill(0x44);
       return random;
     }));
     ON_CALL(*this, makeTicketAgeAdd()).WillByDefault(InvokeWithoutArgs([]() {
       return 0x44444444;
     }));
     ON_CALL(*this, _makePeerCert(_)).WillByDefault(InvokeWithoutArgs([]() {
       return std::make_unique<MockPeerCert>();
     }));
   }
The documentation for this class was generated from the following file:
proxygen/fizz/fizz/protocol/test/Mocks.h