proxygen: testing::internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8, k9, k10 > Class Template Reference
testing::internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8, k9, k10 > Class Template Reference
#include <gmock-generated-actions.h>
Classes
class Impl
Public Member Functions
WithArgsAction (const InnerAction &action)
template<typename F >
operator Action< F > () const
WithArgsAction (const InnerAction &action)
template<typename F >
operator Action< F > () const
WithArgsAction (const InnerAction &action)
template<typename F >
operator Action< F > () const
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (WithArgsAction)
GTEST_DISALLOW_ASSIGN_ (WithArgsAction)
GTEST_DISALLOW_ASSIGN_ (WithArgsAction)
Private Attributes
const InnerAction action_
Detailed Description
template<typename InnerAction, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1, int k10 = -1>
class testing::internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8, k9, k10 >
Definition at line 461 of file gmock-generated-actions.h.
Constructor & Destructor Documentation
template<typename InnerAction, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1, int k10 = -1> testing::internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8, k9, k10 >::WithArgsAction (const InnerAction & action) inline explicit
Definition at line 463 of file gmock-generated-actions.h.
 : action_(action) {}
template<typename InnerAction, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1, int k10 = -1> testing::internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8, k9, k10 >::WithArgsAction (const InnerAction & action) inline explicit
Definition at line 463 of file gmock-generated-actions.h.
 : action_(action) {}
template<typename InnerAction, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1, int k10 = -1> testing::internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8, k9, k10 >::WithArgsAction (const InnerAction & action) inline explicit
Definition at line 463 of file gmock-generated-actions.h.
 : action_(action) {}
Member Function Documentation
template<typename InnerAction, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1, int k10 = -1> testing::internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8, k9, k10 >::GTEST_DISALLOW_ASSIGN_ (WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8, k9, k10 >) private
template<typename InnerAction, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1, int k10 = -1> testing::internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8, k9, k10 >::GTEST_DISALLOW_ASSIGN_ (WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8, k9, k10 >) private
template<typename InnerAction, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1, int k10 = -1> testing::internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8, k9, k10 >::GTEST_DISALLOW_ASSIGN_ (WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8, k9, k10 >) private
template<typename InnerAction, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1, int k10 = -1> template<typename F > testing::internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8, k9, k10 >::operator Action< F > () const inline
Definition at line 466 of file gmock-generated-actions.h.
References testing::MakeAction().
 { return MakeAction(new Impl<F>(action_)); }
template<typename InnerAction, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1, int k10 = -1> template<typename F > testing::internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8, k9, k10 >::operator Action< F > () const inline
Definition at line 466 of file gmock-generated-actions.h.
References testing::MakeAction().
 { return MakeAction(new Impl<F>(action_)); }
template<typename InnerAction, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1, int k10 = -1> template<typename F > testing::internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8, k9, k10 >::operator Action< F > () const inline
Definition at line 466 of file gmock-generated-actions.h.
References testing::MakeAction().
 { return MakeAction(new Impl<F>(action_)); }
Member Data Documentation
template<typename InnerAction, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1, int k10 = -1> const InnerAction testing::internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8, k9, k10 >::action_ private
Definition at line 489 of file gmock-generated-actions.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-generated-actions.h