proxygen: testing::internal::UntypedFunctionMockerBase Class Reference
testing::internal::UntypedFunctionMockerBase Class Reference abstract
#include <gmock-spec-builders.h>
Public Member Functions
UntypedFunctionMockerBase ()
virtual ~UntypedFunctionMockerBase ()
bool VerifyAndClearExpectationsLocked () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
virtual void ClearDefaultActionsLocked () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)=0
virtual UntypedActionResultHolderBase * UntypedPerformDefaultAction (const void *untyped_args, const string &call_description) const =0
virtual UntypedActionResultHolderBase * UntypedPerformAction (const void *untyped_action, const void *untyped_args) const =0
virtual void UntypedDescribeUninterestingCall (const void *untyped_args,::std::ostream *os) const GTEST_LOCK_EXCLUDED_(g_gmock_mutex)=0
virtual const ExpectationBase * UntypedFindMatchingExpectation (const void *untyped_args, const void **untyped_action, bool *is_excessive,::std::ostream *what,::std::ostream *why) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)=0
virtual void UntypedPrintArgs (const void *untyped_args,::std::ostream *os) const =0
void RegisterOwner (const void *mock_obj) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
void SetOwnerAndName (const void *mock_obj, const char *name) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
const void * MockObject () const GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
const char * Name () const GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
UntypedActionResultHolderBase * UntypedInvokeWith (const void *untyped_args) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
UntypedFunctionMockerBase ()
virtual ~UntypedFunctionMockerBase ()
bool VerifyAndClearExpectationsLocked () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
virtual void ClearDefaultActionsLocked () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)=0
virtual UntypedActionResultHolderBase * UntypedPerformDefaultAction (const void *untyped_args, const string &call_description) const =0
virtual UntypedActionResultHolderBase * UntypedPerformAction (const void *untyped_action, const void *untyped_args) const =0
virtual void UntypedDescribeUninterestingCall (const void *untyped_args,::std::ostream *os) const GTEST_LOCK_EXCLUDED_(g_gmock_mutex)=0
virtual const ExpectationBase * UntypedFindMatchingExpectation (const void *untyped_args, const void **untyped_action, bool *is_excessive,::std::ostream *what,::std::ostream *why) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)=0
virtual void UntypedPrintArgs (const void *untyped_args,::std::ostream *os) const =0
void RegisterOwner (const void *mock_obj) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
void SetOwnerAndName (const void *mock_obj, const char *name) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
const void * MockObject () const GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
const char * Name () const GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
UntypedActionResultHolderBase * UntypedInvokeWith (const void *untyped_args) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
UntypedFunctionMockerBase ()
virtual ~UntypedFunctionMockerBase ()
bool VerifyAndClearExpectationsLocked () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
virtual void ClearDefaultActionsLocked () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)=0
virtual UntypedActionResultHolderBase * UntypedPerformDefaultAction (const void *untyped_args, const string &call_description) const =0
virtual UntypedActionResultHolderBase * UntypedPerformAction (const void *untyped_action, const void *untyped_args) const =0
virtual void UntypedDescribeUninterestingCall (const void *untyped_args,::std::ostream *os) const GTEST_LOCK_EXCLUDED_(g_gmock_mutex)=0
virtual const ExpectationBase * UntypedFindMatchingExpectation (const void *untyped_args, const void **untyped_action, bool *is_excessive,::std::ostream *what,::std::ostream *why) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)=0
virtual void UntypedPrintArgs (const void *untyped_args,::std::ostream *os) const =0
void RegisterOwner (const void *mock_obj) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
void SetOwnerAndName (const void *mock_obj, const char *name) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
const void * MockObject () const GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
const char * Name () const GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
UntypedActionResultHolderBase * UntypedInvokeWith (const void *untyped_args) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
Protected Types
typedef std::vector< const void * > UntypedOnCallSpecs
typedef std::vector< internal::linked_ptr< ExpectationBase > > UntypedExpectations
typedef std::vector< const void * > UntypedOnCallSpecs
typedef std::vector< internal::linked_ptr< ExpectationBase > > UntypedExpectations
typedef std::vector< const void * > UntypedOnCallSpecs
typedef std::vector< internal::linked_ptr< ExpectationBase > > UntypedExpectations
Protected Member Functions
Expectation GetHandleOf (ExpectationBase *exp)
Expectation GetHandleOf (ExpectationBase *exp)
Expectation GetHandleOf (ExpectationBase *exp)
Protected Attributes
const void * mock_obj_
const char * name_
UntypedOnCallSpecs untyped_on_call_specs_
UntypedExpectations untyped_expectations_
Detailed Description
Definition at line 126 of file gmock-spec-builders.h.
Member Typedef Documentation
typedef std::vector<internal::linked_ptr<ExpectationBase> > testing::internal::UntypedFunctionMockerBase::UntypedExpectations protected
Definition at line 222 of file gmock-spec-builders.h.
typedef std::vector<internal::linked_ptr<ExpectationBase> > testing::internal::UntypedFunctionMockerBase::UntypedExpectations protected
Definition at line 222 of file gmock-spec-builders.h.
typedef std::vector<internal::linked_ptr<ExpectationBase> > testing::internal::UntypedFunctionMockerBase::UntypedExpectations protected
Definition at line 222 of file gmock-spec-builders.h.
typedef std::vector<const void*> testing::internal::UntypedFunctionMockerBase::UntypedOnCallSpecs protected
Definition at line 219 of file gmock-spec-builders.h.
typedef std::vector<const void*> testing::internal::UntypedFunctionMockerBase::UntypedOnCallSpecs protected
Definition at line 219 of file gmock-spec-builders.h.
typedef std::vector<const void*> testing::internal::UntypedFunctionMockerBase::UntypedOnCallSpecs protected
Definition at line 219 of file gmock-spec-builders.h.
Constructor & Destructor Documentation
testing::internal::UntypedFunctionMockerBase::UntypedFunctionMockerBase ()
Definition at line 270 of file gmock-spec-builders.cc.
     : mock_obj_(NULL), name_("") {}
testing::internal::UntypedFunctionMockerBase::~UntypedFunctionMockerBase () virtual
Definition at line 273 of file gmock-spec-builders.cc.
 {}
testing::internal::UntypedFunctionMockerBase::UntypedFunctionMockerBase ()
virtual testing::internal::UntypedFunctionMockerBase::~UntypedFunctionMockerBase () virtual
testing::internal::UntypedFunctionMockerBase::UntypedFunctionMockerBase ()
virtual testing::internal::UntypedFunctionMockerBase::~UntypedFunctionMockerBase () virtual
Member Function Documentation
virtual void testing::internal::UntypedFunctionMockerBase::ClearDefaultActionsLocked () pure virtual
Implemented in testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2)>, testing::internal::FunctionMockerBase< R(A1, A2)>, and testing::internal::FunctionMockerBase< R(A1, A2)>.
virtual void testing::internal::UntypedFunctionMockerBase::ClearDefaultActionsLocked () pure virtual
Implemented in testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2)>, testing::internal::FunctionMockerBase< R(A1, A2)>, and testing::internal::FunctionMockerBase< R(A1, A2)>.
virtual void testing::internal::UntypedFunctionMockerBase::ClearDefaultActionsLocked () pure virtual
Implemented in testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2)>, testing::internal::FunctionMockerBase< R(A1, A2)>, and testing::internal::FunctionMockerBase< R(A1, A2)>.
Expectation testing::internal::UntypedFunctionMockerBase::GetHandleOf (ExpectationBase * exp) protected
Expectation testing::internal::UntypedFunctionMockerBase::GetHandleOf (ExpectationBase * exp) protected
Expectation testing::internal::UntypedFunctionMockerBase::GetHandleOf (ExpectationBase * exp) protected
Definition at line 449 of file gmock-spec-builders.cc.
References testing::internal::Assert(), and untyped_expectations_.
{
   for (UntypedExpectations::const_iterator it =
            untyped_expectations_.begin();
        it != untyped_expectations_.end(); ++it) {
     if (it->get() == exp) {
       return Expectation(*it);
     }
   }
   Assert(false, __FILE__, __LINE__, "Cannot find expectation.");
   return Expectation();
   // The above statement is just to make the code compile, and will
   // never be executed.
 }
const void * testing::internal::UntypedFunctionMockerBase::MockObject () const
Definition at line 303 of file gmock-spec-builders.cc.
References testing::internal::Assert(), and mock_obj_.
Referenced by UntypedInvokeWith().
{
   const void* mock_obj;
   {
     // We protect mock_obj_ under g_gmock_mutex in case this mock
     // function is called from two threads concurrently.
     MutexLock l(&g_gmock_mutex);
     Assert(mock_obj_ != NULL, __FILE__, __LINE__,
            "MockObject() must not be called before RegisterOwner() or "
            "SetOwnerAndName() has been called.");
     mock_obj = mock_obj_;
   }
   return mock_obj;
 }
const void* testing::internal::UntypedFunctionMockerBase::MockObject () const
const void* testing::internal::UntypedFunctionMockerBase::MockObject () const
const char* testing::internal::UntypedFunctionMockerBase::Name () const
const char * testing::internal::UntypedFunctionMockerBase::Name () const
Definition at line 320 of file gmock-spec-builders.cc.
References testing::internal::Assert(), name, and name_.
Referenced by UntypedInvokeWith().
{
   const char* name;
   {
     // We protect name_ under g_gmock_mutex in case this mock
     // function is called from two threads concurrently.
     MutexLock l(&g_gmock_mutex);
     Assert(name_ != NULL, __FILE__, __LINE__,
            "Name() must not be called before SetOwnerAndName() has "
            "been called.");
     name = name_;
   }
   return name;
 }
const char* testing::internal::UntypedFunctionMockerBase::Name () const
void testing::internal::UntypedFunctionMockerBase::RegisterOwner (const void * mock_obj)
void testing::internal::UntypedFunctionMockerBase::RegisterOwner (const void * mock_obj)
void testing::internal::UntypedFunctionMockerBase::RegisterOwner (const void * mock_obj)
Definition at line 279 of file gmock-spec-builders.cc.
References mock_obj_.
{
   {
     MutexLock l(&g_gmock_mutex);
     mock_obj_ = mock_obj;
   }
   Mock::Register(mock_obj, this);
 }
void testing::internal::UntypedFunctionMockerBase::SetOwnerAndName (const void * mock_obj, const char * name)
Definition at line 291 of file gmock-spec-builders.cc.
References mock_obj_, name, and name_.
{
   // We protect name_ under g_gmock_mutex in case this mock function
   // is called from two threads concurrently.
   MutexLock l(&g_gmock_mutex);
   mock_obj_ = mock_obj;
   name_ = name;
 }
void testing::internal::UntypedFunctionMockerBase::SetOwnerAndName (const void * mock_obj, const char * name)
void testing::internal::UntypedFunctionMockerBase::SetOwnerAndName (const void * mock_obj, const char * name)
virtual void testing::internal::UntypedFunctionMockerBase::UntypedDescribeUninterestingCall (const void * untyped_args, ::std::ostream * os) const pure virtual
Implemented in testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2)>, testing::internal::FunctionMockerBase< R(A1, A2)>, and testing::internal::FunctionMockerBase< R(A1, A2)>.
Referenced by UntypedInvokeWith().
virtual void testing::internal::UntypedFunctionMockerBase::UntypedDescribeUninterestingCall (const void * untyped_args, ::std::ostream * os) const pure virtual
Implemented in testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2)>, testing::internal::FunctionMockerBase< R(A1, A2)>, and testing::internal::FunctionMockerBase< R(A1, A2)>.
virtual void testing::internal::UntypedFunctionMockerBase::UntypedDescribeUninterestingCall (const void * untyped_args, ::std::ostream * os) const pure virtual
Implemented in testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2)>, testing::internal::FunctionMockerBase< R(A1, A2)>, and testing::internal::FunctionMockerBase< R(A1, A2)>.
virtual const ExpectationBase* testing::internal::UntypedFunctionMockerBase::UntypedFindMatchingExpectation (const void * untyped_args, const void ** untyped_action, bool * is_excessive, ::std::ostream * what, ::std::ostream * why) pure virtual
Implemented in testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2)>, testing::internal::FunctionMockerBase< R(A1, A2)>, and testing::internal::FunctionMockerBase< R(A1, A2)>.
virtual const ExpectationBase* testing::internal::UntypedFunctionMockerBase::UntypedFindMatchingExpectation (const void * untyped_args, const void ** untyped_action, bool * is_excessive, ::std::ostream * what, ::std::ostream * why) pure virtual
Implemented in testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2)>, testing::internal::FunctionMockerBase< R(A1, A2)>, and testing::internal::FunctionMockerBase< R(A1, A2)>.
Referenced by UntypedInvokeWith().
virtual const ExpectationBase* testing::internal::UntypedFunctionMockerBase::UntypedFindMatchingExpectation (const void * untyped_args, const void ** untyped_action, bool * is_excessive, ::std::ostream * what, ::std::ostream * why) pure virtual
Implemented in testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2)>, testing::internal::FunctionMockerBase< R(A1, A2)>, and testing::internal::FunctionMockerBase< R(A1, A2)>.
UntypedActionResultHolderBase * testing::internal::UntypedFunctionMockerBase::UntypedInvokeWith (const void * untyped_args)
Definition at line 339 of file gmock-spec-builders.cc.
References testing::internal::ExpectationBase::DescribeLocationTo(), testing::internal::Expect(), testing::internal::ExpectationBase::file(), testing::internal::kAllow, testing::internal::kInfo, testing::internal::kWarn, testing::internal::kWarning, testing::internal::ExpectationBase::line(), testing::internal::Log(), testing::internal::LogIsVisible(), MockObject(), Name(), testing::internal::UntypedActionResultHolderBase::PrintAsActionResult(), testing::internal::ReportUninterestingCall(), untyped_expectations_, UntypedDescribeUninterestingCall(), UntypedFindMatchingExpectation(), UntypedPerformAction(), UntypedPerformDefaultAction(), and UntypedPrintArgs().
{
   if (untyped_expectations_.size() == 0) {
     // No expectation is set on this mock method - we have an
     // uninteresting call.
     // We must get Google Mock's reaction on uninteresting calls
     // made on this mock object BEFORE performing the action,
     // because the action may DELETE the mock object and make the
     // following expression meaningless.
     const CallReaction reaction =
         Mock::GetReactionOnUninterestingCalls(MockObject());
     // True iff we need to print this call's arguments and return
     // value.  This definition must be kept in sync with
     // the behavior of ReportUninterestingCall().
     const bool need_to_report_uninteresting_call =
         // If the user allows this uninteresting call, we print it
         // only when he wants informational messages.
         reaction == kAllow ? LogIsVisible(kInfo) :
         // If the user wants this to be a warning, we print it only
         // when he wants to see warnings.
         reaction == kWarn ? LogIsVisible(kWarning) :
         // Otherwise, the user wants this to be an error, and we
         // should always print detailed information in the error.
         true;
     if (!need_to_report_uninteresting_call) {
       // Perform the action without printing the call information.
       return this->UntypedPerformDefaultAction(untyped_args, "");
     }
     // Warns about the uninteresting call.
     ::std::stringstream ss;
     this->UntypedDescribeUninterestingCall(untyped_args, &ss);
     // Calculates the function result.
     UntypedActionResultHolderBase* const result =
         this->UntypedPerformDefaultAction(untyped_args, ss.str());
     // Prints the function result.
     if (result != NULL)
       result->PrintAsActionResult(&ss);
     ReportUninterestingCall(reaction, ss.str());
     return result;
   }
   bool is_excessive = false;
   ::std::stringstream ss;
   ::std::stringstream why;
   ::std::stringstream loc;
   const void* untyped_action = NULL;
   // The UntypedFindMatchingExpectation() function acquires and
   // releases g_gmock_mutex.
   const ExpectationBase* const untyped_expectation =
       this->UntypedFindMatchingExpectation(
           untyped_args, &untyped_action, &is_excessive,
           &ss, &why);
   const bool found = untyped_expectation != NULL;
   // True iff we need to print the call's arguments and return value.
   // This definition must be kept in sync with the uses of Expect()
   // and Log() in this function.
   const bool need_to_report_call =
       !found || is_excessive || LogIsVisible(kInfo);
   if (!need_to_report_call) {
     // Perform the action without printing the call information.
     return
         untyped_action == NULL ?
         this->UntypedPerformDefaultAction(untyped_args, "") :
         this->UntypedPerformAction(untyped_action, untyped_args);
   }
   ss << "    Function call: " << Name();
   this->UntypedPrintArgs(untyped_args, &ss);
   // In case the action deletes a piece of the expectation, we
   // generate the message beforehand.
   if (found && !is_excessive) {
     untyped_expectation->DescribeLocationTo(&loc);
   }
   UntypedActionResultHolderBase* const result =
       untyped_action == NULL ?
       this->UntypedPerformDefaultAction(untyped_args, ss.str()) :
       this->UntypedPerformAction(untyped_action, untyped_args);
   if (result != NULL)
     result->PrintAsActionResult(&ss);
   ss << "\n" << why.str();
   if (!found) {
     // No expectation matches this call - reports a failure.
     Expect(false, NULL, -1, ss.str());
   } else if (is_excessive) {
     // We had an upper-bound violation and the failure message is in ss.
     Expect(false, untyped_expectation->file(),
            untyped_expectation->line(), ss.str());
   } else {
     // We had an expected call and the matching expectation is
     // described in ss.
     Log(kInfo, loc.str() + ss.str(), 2);
   }
   return result;
 }
UntypedActionResultHolderBase* testing::internal::UntypedFunctionMockerBase::UntypedInvokeWith (const void * untyped_args)
UntypedActionResultHolderBase* testing::internal::UntypedFunctionMockerBase::UntypedInvokeWith (const void * untyped_args)
virtual UntypedActionResultHolderBase* testing::internal::UntypedFunctionMockerBase::UntypedPerformAction (const void * untyped_action, const void * untyped_args) const pure virtual
Implemented in testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2)>, testing::internal::FunctionMockerBase< R(A1, A2)>, and testing::internal::FunctionMockerBase< R(A1, A2)>.
virtual UntypedActionResultHolderBase* testing::internal::UntypedFunctionMockerBase::UntypedPerformAction (const void * untyped_action, const void * untyped_args) const pure virtual
Implemented in testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2)>, testing::internal::FunctionMockerBase< R(A1, A2)>, and testing::internal::FunctionMockerBase< R(A1, A2)>.
virtual UntypedActionResultHolderBase* testing::internal::UntypedFunctionMockerBase::UntypedPerformAction (const void * untyped_action, const void * untyped_args) const pure virtual
Implemented in testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2)>, testing::internal::FunctionMockerBase< R(A1, A2)>, and testing::internal::FunctionMockerBase< R(A1, A2)>.
Referenced by UntypedInvokeWith().
virtual UntypedActionResultHolderBase* testing::internal::UntypedFunctionMockerBase::UntypedPerformDefaultAction (const void * untyped_args, const string & call_description) const pure virtual
Implemented in testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2)>, testing::internal::FunctionMockerBase< R(A1, A2)>, and testing::internal::FunctionMockerBase< R(A1, A2)>.
virtual UntypedActionResultHolderBase* testing::internal::UntypedFunctionMockerBase::UntypedPerformDefaultAction (const void * untyped_args, const string & call_description) const pure virtual
Implemented in testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2)>, testing::internal::FunctionMockerBase< R(A1, A2)>, and testing::internal::FunctionMockerBase< R(A1, A2)>.
virtual UntypedActionResultHolderBase* testing::internal::UntypedFunctionMockerBase::UntypedPerformDefaultAction (const void * untyped_args, const string & call_description) const pure virtual
Implemented in testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2)>, testing::internal::FunctionMockerBase< R(A1, A2)>, and testing::internal::FunctionMockerBase< R(A1, A2)>.
Referenced by UntypedInvokeWith().
virtual void testing::internal::UntypedFunctionMockerBase::UntypedPrintArgs (const void * untyped_args, ::std::ostream * os) const pure virtual
Implemented in testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2)>, testing::internal::FunctionMockerBase< R(A1, A2)>, and testing::internal::FunctionMockerBase< R(A1, A2)>.
virtual void testing::internal::UntypedFunctionMockerBase::UntypedPrintArgs (const void * untyped_args, ::std::ostream * os) const pure virtual
Implemented in testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2)>, testing::internal::FunctionMockerBase< R(A1, A2)>, and testing::internal::FunctionMockerBase< R(A1, A2)>.
virtual void testing::internal::UntypedFunctionMockerBase::UntypedPrintArgs (const void * untyped_args, ::std::ostream * os) const pure virtual
Implemented in testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< F >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R(A1, A2) >, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R()>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5) >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R() >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4)>, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >, testing::internal::FunctionMockerBase< R(A1, A2)>, testing::internal::FunctionMockerBase< R(A1, A2)>, and testing::internal::FunctionMockerBase< R(A1, A2)>.
Referenced by UntypedInvokeWith().
bool testing::internal::UntypedFunctionMockerBase::VerifyAndClearExpectationsLocked ()
Definition at line 467 of file gmock-spec-builders.cc.
References testing::internal::ExpectationBase::DescribeCallCountTo(), testing::internal::Expect(), testing::internal::ExpectationBase::file(), first_used_file, first_used_line, testing::internal::ExpectationBase::IsOverSaturated(), testing::internal::ExpectationBase::IsSatisfied(), leakable, testing::internal::ExpectationBase::line(), testing::internal::ExpectationBase::MaybeDescribeExtraMatcherTo(), testing::internal::ExpectationBase::source_text(), and untyped_expectations_.
{
   g_gmock_mutex.AssertHeld();
   bool expectations_met = true;
   for (UntypedExpectations::const_iterator it =
            untyped_expectations_.begin();
        it != untyped_expectations_.end(); ++it) {
     ExpectationBase* const untyped_expectation = it->get();
     if (untyped_expectation->IsOverSaturated()) {
       // There was an upper-bound violation.  Since the error was
       // already reported when it occurred, there is no need to do
       // anything here.
       expectations_met = false;
     } else if (!untyped_expectation->IsSatisfied()) {
       expectations_met = false;
       ::std::stringstream ss;
       ss  << "Actual function call count doesn't match "
           << untyped_expectation->source_text() << "...\n";
       // No need to show the source file location of the expectation
       // in the description, as the Expect() call that follows already
       // takes care of it.
       untyped_expectation->MaybeDescribeExtraMatcherTo(&ss);
       untyped_expectation->DescribeCallCountTo(&ss);
       Expect(false, untyped_expectation->file(),
              untyped_expectation->line(), ss.str());
     }
   }
   // Deleting our expectations may trigger other mock objects to be deleted, for
   // example if an action contains a reference counted smart pointer to that
   // mock object, and that is the last reference. So if we delete our
   // expectations within the context of the global mutex we may deadlock when
   // this method is called again. Instead, make a copy of the set of
   // expectations to delete, clear our set within the mutex, and then clear the
   // copied set outside of it.
   UntypedExpectations expectations_to_delete;
   untyped_expectations_.swap(expectations_to_delete);
   g_gmock_mutex.Unlock();
   expectations_to_delete.clear();
   g_gmock_mutex.Lock();
   return expectations_met;
 }
bool testing::internal::UntypedFunctionMockerBase::VerifyAndClearExpectationsLocked ()
bool testing::internal::UntypedFunctionMockerBase::VerifyAndClearExpectationsLocked ()
Member Data Documentation
const void * testing::internal::UntypedFunctionMockerBase::mock_obj_ protected
Definition at line 231 of file gmock-spec-builders.h.
Referenced by MockObject(), RegisterOwner(), and SetOwnerAndName().
const char * testing::internal::UntypedFunctionMockerBase::name_ protected
Definition at line 235 of file gmock-spec-builders.h.
Referenced by Name(), and SetOwnerAndName().
UntypedExpectations testing::internal::UntypedFunctionMockerBase::untyped_expectations_ protected
Definition at line 241 of file gmock-spec-builders.h.
Referenced by GetHandleOf(), UntypedInvokeWith(), and VerifyAndClearExpectationsLocked().
UntypedOnCallSpecs testing::internal::UntypedFunctionMockerBase::untyped_on_call_specs_ protected
Definition at line 238 of file gmock-spec-builders.h.
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-spec-builders.h
proxygen/fizz/build_/gtest/src/gtest/googlemock/src/gmock-spec-builders.cc