proxygen: BroadcastHandlerTest Class Reference
BroadcastHandlerTest Class Reference
Classes
class MockBroadcastHandler
Public Member Functions
void SetUp () override
void TearDown () override
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Protected Attributes
DefaultPipeline::Ptr pipeline
StrictMock< MockBytesToBytesHandler > * prevHandler {nullptr}
StrictMock< MockByteToMessageDecoder< std::string > > * decoder {nullptr}
StrictMock< MockBroadcastHandler > * handler {nullptr}
StrictMock< MockSubscriber< std::string, std::string > > subscriber0
StrictMock< MockSubscriber< std::string, std::string > > subscriber1
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Protected Member Functions inherited from testing::Test
Test ()
Test ()
Test ()
Detailed Description
Definition at line 23 of file BroadcastHandlerTest.cpp.
Member Function Documentation
void BroadcastHandlerTest::SetUp () inline override virtual
Reimplemented from testing::Test.
Definition at line 36 of file BroadcastHandlerTest.cpp.
References testing::_, wangle::Pipeline< R, W >::create(), EXPECT_CALL, handler(), testing::Invoke(), and fizz::detail::read().
{
     prevHandler = new StrictMock<MockBytesToBytesHandler>();
     EXPECT_CALL(*prevHandler, read(_, _))
         .WillRepeatedly(Invoke([&](MockBytesToBytesHandler::Context* ctx,
                                    IOBufQueue& q) { ctx->fireRead(q); }));
     decoder = new StrictMock<MockByteToMessageDecoder<std::string>>();
     handler = new StrictMock<MockBroadcastHandler>();
     pipeline = DefaultPipeline::create();
     pipeline->addBack(
         std::shared_ptr<StrictMock<MockBytesToBytesHandler>>(prevHandler));
     pipeline->addBack(
         std::shared_ptr<StrictMock<MockByteToMessageDecoder<std::string>>>(
             decoder));
     pipeline->addBack(
         std::shared_ptr<StrictMock<MockBroadcastHandler>>(handler));
     pipeline->finalize();
   }
void BroadcastHandlerTest::TearDown () inline override virtual
Reimplemented from testing::Test.
Definition at line 56 of file BroadcastHandlerTest.cpp.
{
     Mock::VerifyAndClear(&subscriber0);
     Mock::VerifyAndClear(&subscriber1);
     pipeline.reset();
   }
Member Data Documentation
StrictMock<MockByteToMessageDecoder<std::string> >* BroadcastHandlerTest::decoder {nullptr} protected
Definition at line 67 of file BroadcastHandlerTest.cpp.
StrictMock<MockBroadcastHandler>* BroadcastHandlerTest::handler {nullptr} protected
Definition at line 68 of file BroadcastHandlerTest.cpp.
DefaultPipeline::Ptr BroadcastHandlerTest::pipeline protected
Definition at line 64 of file BroadcastHandlerTest.cpp.
StrictMock<MockBytesToBytesHandler>* BroadcastHandlerTest::prevHandler {nullptr} protected
Definition at line 66 of file BroadcastHandlerTest.cpp.
StrictMock<MockSubscriber<std::string, std::string> > BroadcastHandlerTest::subscriber0 protected
Definition at line 70 of file BroadcastHandlerTest.cpp.
StrictMock<MockSubscriber<std::string, std::string> > BroadcastHandlerTest::subscriber1 protected
Definition at line 71 of file BroadcastHandlerTest.cpp.
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/channel/broadcast/test/BroadcastHandlerTest.cpp