proxygen: folly::LogHandlerConfig Class Reference
folly::LogHandlerConfig Class Reference
#include <LogHandlerConfig.h>
Public Types
using Options = std::unordered_map< std::string, std::string >
Public Member Functions
LogHandlerConfig ()
LogHandlerConfig (StringPiece type)
LogHandlerConfig (Optional< StringPiece > type)
LogHandlerConfig (StringPiece type, Options options)
LogHandlerConfig (Optional< StringPiece > type, Options options)
void update (const LogHandlerConfig &other)
bool operator== (const LogHandlerConfig &other) const
bool operator!= (const LogHandlerConfig &other) const
Public Attributes
Optional< std::string > type
Options options
Detailed Description
Configuration for a LogHandler
Definition at line 29 of file LogHandlerConfig.h.
Member Typedef Documentation
using folly::LogHandlerConfig::Options = std::unordered_map<std::string, std::string>
Definition at line 31 of file LogHandlerConfig.h.
Constructor & Destructor Documentation
folly::LogHandlerConfig::LogHandlerConfig ()
Definition at line 24 of file LogHandlerConfig.cpp.
 {}
folly::LogHandlerConfig::LogHandlerConfig (StringPiece type) explicit
Definition at line 26 of file LogHandlerConfig.cpp.
References folly::Range< Iter >::str().
 : type{t.str()} {}
folly::LogHandlerConfig::LogHandlerConfig (Optional< StringPiece > type) explicit
Definition at line 28 of file LogHandlerConfig.cpp.
References folly::Optional< Value >::hasValue().
     : type{t.hasValue() ? Optional<string>{t->str()} : Optional<string>{}} {}
folly::LogHandlerConfig::LogHandlerConfig (StringPiece type, Options options)
Definition at line 31 of file LogHandlerConfig.cpp.
References folly::gen::move, options, and folly::Range< Iter >::str().
     : type{t.str()}, options{std::move(opts)} {}
folly::LogHandlerConfig::LogHandlerConfig (Optional< StringPiece > type, Options options)
Definition at line 34 of file LogHandlerConfig.cpp.
References folly::Optional< Value >::hasValue(), folly::gen::move, and options.
     : type{t.hasValue() ? Optional<string>{t->str()} : Optional<string>{}},
       options{std::move(opts)} {}
Member Function Documentation
bool folly::LogHandlerConfig::operator!= (const LogHandlerConfig & other) const
Definition at line 50 of file LogHandlerConfig.cpp.
{
   return !(*this == other);
 }
bool folly::LogHandlerConfig::operator== (const LogHandlerConfig & other) const
Definition at line 46 of file LogHandlerConfig.cpp.
References options, and type.
{
   return type == other.type && options == other.options;
 }
void folly::LogHandlerConfig::update (const LogHandlerConfig & other)
Update this LogHandlerConfig object by merging in settings from another LogConfig.
The other LogHandlerConfig must not have a type set.
Definition at line 38 of file LogHandlerConfig.cpp.
References FOLLY_SAFE_DCHECK, folly::Optional< Value >::hasValue(), option(), options, and type.
Referenced by folly::LoggerDB::startConfigUpdate().
{
   FOLLY_SAFE_DCHECK(
       !other.type.hasValue(), "LogHandlerConfig type cannot be updated");
   for (const auto& option : other.options) {
     options[option.first] = option.second;
   }
 }
Member Data Documentation
Options folly::LogHandlerConfig::options
Definition at line 59 of file LogHandlerConfig.h.
Referenced by folly::logConfigToDynamic(), LogHandlerConfig(), folly::operator<<(), operator==(), folly::TestLogHandler::setOptions(), folly::LoggerDB::startConfigUpdate(), and update().
Optional<std::string> folly::LogHandlerConfig::type
The handler type name.
If this field is unset than this configuration object is intended to be used to update an existing LogHandler object. This field must always be set in the configuration for all existing LogHandler objects.
Definition at line 57 of file LogHandlerConfig.h.
Referenced by folly::logConfigToDynamic(), folly::operator<<(), operator==(), folly::LoggerDB::startConfigUpdate(), and update().
The documentation for this class was generated from the following files:
proxygen/folly/folly/logging/LogHandlerConfig.h
proxygen/folly/folly/logging/LogHandlerConfig.cpp