proxygen: folly::FlatCombining< T, Mutex, Atom, Req >::Rec Class Reference
folly::FlatCombining< T, Mutex, Atom, Req >::Rec Class Reference
Combining request record.
#include <FlatCombining.h>
Public Member Functions
Rec ()
void setValid ()
void clearValid ()
bool isValid () const
void setDone ()
void clearDone ()
bool isDone () const
void awaitDone ()
void setDisconnected ()
void clearDisconnected ()
bool isDisconnected () const
void setIndex (const size_t index)
size_t getIndex () const
void setNext (const size_t next)
size_t getNext () const
void setLast (const uint64_t pass)
uint64_t getLast () const
Req & getReq ()
template<typename Func >
void setFn (Func &&fn)
void clearFn ()
SavedFn & getFn ()
void complete ()
Private Attributes
folly::SaturatingSemaphore< false, Atom > valid_
folly::SaturatingSemaphore< false, Atom > done_
folly::SaturatingSemaphore< false, Atom > disconnected_
size_t index_
size_t next_
uint64_t last_
Req req_
SavedFn fn_
Detailed Description
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool>
class folly::FlatCombining< T, Mutex, Atom, Req >::Rec
Combining request record.
Definition at line 114 of file FlatCombining.h.
Constructor & Destructor Documentation
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> folly::FlatCombining< T, Mutex, Atom, Req >::Rec::Rec () inline
Definition at line 126 of file FlatCombining.h.
References folly::FlatCombining< T, Mutex, Atom, Req >::Rec::setDisconnected(), and folly::FlatCombining< T, Mutex, Atom, Req >::Rec::setDone().
Referenced by folly::FlatCombining< FcSimpleExample< Mutex, Atom >, Mutex, Atom >::allocRec(), folly::FlatCombining< FcSimpleExample< Mutex, Atom >, Mutex, Atom >::combiningPass(), folly::FlatCombining< FcSimpleExample< Mutex, Atom >, Mutex, Atom >::drainAll(), and folly::FlatCombining< FcSimpleExample< Mutex, Atom >, Mutex, Atom >::pushRec().
           {
       setDone();
       setDisconnected();
     }
Member Function Documentation
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> void folly::FlatCombining< T, Mutex, Atom, Req >::Rec::awaitDone () inline
Definition at line 155 of file FlatCombining.h.
References folly::SaturatingSemaphore< MayBlock, Atom >::wait().
Referenced by folly::FlatCombining< FcSimpleExample< Mutex, Atom >, Mutex, Atom >::drainAll(), and folly::FlatCombining< FcSimpleExample< Mutex, Atom >, Mutex, Atom >::requestOp().
                      {
       done_.wait();
     }
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> void folly::FlatCombining< T, Mutex, Atom, Req >::Rec::clearDisconnected () inline
Definition at line 163 of file FlatCombining.h.
References folly::SaturatingSemaphore< MayBlock, Atom >::reset().
{
       disconnected_.reset();
     }
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> void folly::FlatCombining< T, Mutex, Atom, Req >::Rec::clearDone () inline
Definition at line 147 of file FlatCombining.h.
References folly::SaturatingSemaphore< MayBlock, Atom >::reset().
                      {
       done_.reset();
     }
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> void folly::FlatCombining< T, Mutex, Atom, Req >::Rec::clearFn () inline
Definition at line 213 of file FlatCombining.h.
                    {
       fn_ = {};
       assert(!fn_);
     }
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> void folly::FlatCombining< T, Mutex, Atom, Req >::Rec::clearValid () inline
Definition at line 135 of file FlatCombining.h.
References folly::SaturatingSemaphore< MayBlock, Atom >::reset(), and folly::FlatCombining< T, Mutex, Atom, Req >::Rec::valid_.
Referenced by folly::FlatCombining< T, Mutex, Atom, Req >::Rec::complete().
                       {
       valid_.reset();
     }
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> void folly::FlatCombining< T, Mutex, Atom, Req >::Rec::complete () inline
Definition at line 222 of file FlatCombining.h.
References folly::FlatCombining< T, Mutex, Atom, Req >::Rec::clearValid(), folly::FlatCombining< T, Mutex, Atom, Req >::Rec::isDone(), and folly::FlatCombining< T, Mutex, Atom, Req >::Rec::setDone().
                     {
       clearValid();
       assert(!isDone());
       setDone();
     }
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> SavedFn& folly::FlatCombining< T, Mutex, Atom, Req >::Rec::getFn () inline
Definition at line 218 of file FlatCombining.h.
References folly::FlatCombining< T, Mutex, Atom, Req >::Rec::fn_.
                      {
       return fn_;
     }
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> size_t folly::FlatCombining< T, Mutex, Atom, Req >::Rec::getIndex () const inline
Definition at line 175 of file FlatCombining.h.
References folly::FlatCombining< T, Mutex, Atom, Req >::Rec::index_.
{
       return index_;
     }
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> uint64_t folly::FlatCombining< T, Mutex, Atom, Req >::Rec::getLast () const inline
Definition at line 191 of file FlatCombining.h.
References folly::FlatCombining< T, Mutex, Atom, Req >::Rec::last_.
{
       return last_;
     }
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> size_t folly::FlatCombining< T, Mutex, Atom, Req >::Rec::getNext () const inline
Definition at line 183 of file FlatCombining.h.
References folly::FlatCombining< T, Mutex, Atom, Req >::Rec::next_.
{
       return next_;
     }
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> Req& folly::FlatCombining< T, Mutex, Atom, Req >::Rec::getReq () inline
Definition at line 195 of file FlatCombining.h.
References folly::FlatCombining< T, Mutex, Atom, Req >::Rec::req_.
                   {
       return req_;
     }
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> bool folly::FlatCombining< T, Mutex, Atom, Req >::Rec::isDisconnected () const inline
Definition at line 167 of file FlatCombining.h.
References folly::SaturatingSemaphore< MayBlock, Atom >::ready().
{
       return disconnected_.ready();
     }
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> bool folly::FlatCombining< T, Mutex, Atom, Req >::Rec::isDone () const inline
Definition at line 151 of file FlatCombining.h.
References folly::SaturatingSemaphore< MayBlock, Atom >::ready().
Referenced by folly::FlatCombining< T, Mutex, Atom, Req >::Rec::complete().
{
       return done_.ready();
     }
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> bool folly::FlatCombining< T, Mutex, Atom, Req >::Rec::isValid () const inline
Definition at line 139 of file FlatCombining.h.
References folly::SaturatingSemaphore< MayBlock, Atom >::ready(), and folly::FlatCombining< T, Mutex, Atom, Req >::Rec::valid_.
{
       return valid_.ready();
     }
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> void folly::FlatCombining< T, Mutex, Atom, Req >::Rec::setDisconnected () inline
Definition at line 159 of file FlatCombining.h.
References folly::SaturatingSemaphore< MayBlock, Atom >::post().
Referenced by folly::FlatCombining< T, Mutex, Atom, Req >::Rec::Rec().
{
       disconnected_.post();
     }
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> void folly::FlatCombining< T, Mutex, Atom, Req >::Rec::setDone () inline
Definition at line 143 of file FlatCombining.h.
References folly::SaturatingSemaphore< MayBlock, Atom >::post().
Referenced by folly::FlatCombining< T, Mutex, Atom, Req >::Rec::complete(), and folly::FlatCombining< T, Mutex, Atom, Req >::Rec::Rec().
                    {
       done_.post();
     }
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> template<typename Func > void folly::FlatCombining< T, Mutex, Atom, Req >::Rec::setFn (Func && fn) inline
Definition at line 200 of file FlatCombining.h.
References folly::value().
{
       static_assert(
           std::is_nothrow_constructible<
               folly::Function<void()>,
               _t<std::decay<Func>>>::value,
           "Try using a smaller function object that can fit in folly::Function "
           "without allocation, or use the custom interface of requestFC() to "
           "manage the requested function's arguments and results explicitly "
           "in a custom request structure without allocation.");
       fn_ = std::forward<Func>(fn);
       assert(fn_);
     }
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> void folly::FlatCombining< T, Mutex, Atom, Req >::Rec::setIndex (const size_t index) inline
Definition at line 171 of file FlatCombining.h.
{
       index_ = index;
     }
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> void folly::FlatCombining< T, Mutex, Atom, Req >::Rec::setLast (const uint64_t pass) inline
Definition at line 187 of file FlatCombining.h.
{
       last_ = pass;
     }
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> void folly::FlatCombining< T, Mutex, Atom, Req >::Rec::setNext (const size_t next) inline
Definition at line 179 of file FlatCombining.h.
References cpp.ast::next().
{
       next_ = next;
     }
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> void folly::FlatCombining< T, Mutex, Atom, Req >::Rec::setValid () inline
Definition at line 131 of file FlatCombining.h.
References folly::SaturatingSemaphore< MayBlock, Atom >::post(), and folly::FlatCombining< T, Mutex, Atom, Req >::Rec::valid_.
                     {
       valid_.post();
     }
Member Data Documentation
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> folly::SaturatingSemaphore<false, Atom> folly::FlatCombining< T, Mutex, Atom, Req >::Rec::disconnected_ private
Definition at line 118 of file FlatCombining.h.
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> folly::SaturatingSemaphore<false, Atom> folly::FlatCombining< T, Mutex, Atom, Req >::Rec::done_ private
Definition at line 117 of file FlatCombining.h.
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> SavedFn folly::FlatCombining< T, Mutex, Atom, Req >::Rec::fn_ private
Definition at line 123 of file FlatCombining.h.
Referenced by folly::FlatCombining< T, Mutex, Atom, Req >::Rec::getFn().
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> size_t folly::FlatCombining< T, Mutex, Atom, Req >::Rec::index_ private
Definition at line 119 of file FlatCombining.h.
Referenced by folly::FlatCombining< T, Mutex, Atom, Req >::Rec::getIndex().
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> uint64_t folly::FlatCombining< T, Mutex, Atom, Req >::Rec::last_ private
Definition at line 121 of file FlatCombining.h.
Referenced by folly::FlatCombining< T, Mutex, Atom, Req >::Rec::getLast().
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> size_t folly::FlatCombining< T, Mutex, Atom, Req >::Rec::next_ private
Definition at line 120 of file FlatCombining.h.
Referenced by folly::FlatCombining< T, Mutex, Atom, Req >::Rec::getNext().
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> Req folly::FlatCombining< T, Mutex, Atom, Req >::Rec::req_ private
Definition at line 122 of file FlatCombining.h.
Referenced by folly::FlatCombining< T, Mutex, Atom, Req >::Rec::getReq().
template<typename T, typename Mutex = std::mutex, template< typename > class Atom = std::atomic, typename Req = bool> folly::SaturatingSemaphore<false, Atom> folly::FlatCombining< T, Mutex, Atom, Req >::Rec::valid_ private
Definition at line 116 of file FlatCombining.h.
Referenced by folly::FlatCombining< T, Mutex, Atom, Req >::Rec::clearValid(), folly::FlatCombining< T, Mutex, Atom, Req >::Rec::isValid(), and folly::FlatCombining< T, Mutex, Atom, Req >::Rec::setValid().
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/flat_combining/FlatCombining.h