proxygen: HTTPParallelCodecTest Class Reference
HTTPParallelCodecTest Class Reference
#include <HTTPParallelCodecTest.h>
Public Member Functions
HTTPParallelCodecTest (proxygen::HTTPParallelCodec &upstreamCodec, proxygen::HTTPParallelCodec &downstreamCodec)
void SetUp () override
void SetUpUpstreamTest ()
bool parse (std::function< void(folly::IOBuf *)> hackIngress=std::function< void(folly::IOBuf *)>())
bool parseUpstream (std::function< void(folly::IOBuf *)> hackIngress=std::function< void(folly::IOBuf *)>())
bool parseImpl (proxygen::HTTPParallelCodec &codec, std::function< void(folly::IOBuf *)> hackIngress)
void dumpToFile (bool isUpstream=false)
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Protected Attributes
proxygen::FakeHTTPCodecCallback callbacks_
proxygen::HTTPParallelCodec & upstreamCodec_
proxygen::HTTPParallelCodec & downstreamCodec_
folly::IOBufQueue output_ {folly::IOBufQueue::cacheChainLength()}
const testing::TestInfo * testInfo_ {testing::UnitTest::GetInstance()->current_test_info()}
bool dump_ {false}
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Protected Member Functions inherited from testing::Test
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Detailed Description
Definition at line 16 of file HTTPParallelCodecTest.h.
Constructor & Destructor Documentation
HTTPParallelCodecTest::HTTPParallelCodecTest (proxygen::HTTPParallelCodec & upstreamCodec, proxygen::HTTPParallelCodec & downstreamCodec) inline
Definition at line 18 of file HTTPParallelCodecTest.h.
     : upstreamCodec_(upstreamCodec),
     downstreamCodec_(downstreamCodec) {}
Member Function Documentation
void HTTPParallelCodecTest::dumpToFile (bool isUpstream = false) inline
Definition at line 68 of file HTTPParallelCodecTest.h.
References dump_, proxygen::dumpBinToFile(), folly::IOBufQueue::front(), testing::TestInfo::name(), output_, and testInfo_.
Referenced by parseImpl().
{
     if (!dump_) {
       return;
     }
     auto endpoint = isUpstream ? "client" : "server";
     auto filename = folly::to<std::string>(
         "/tmp/parallel_", endpoint, "_", testInfo_->name(), ".bin");
     proxygen::dumpBinToFile(filename, output_.front());
   }
bool HTTPParallelCodecTest::parse (std::function< void(folly::IOBuf *)> hackIngress = std::function<void(folly::IOBuf*)>()) inline
Definition at line 37 of file HTTPParallelCodecTest.h.
References downstreamCodec_, and parseImpl().
{
     return parseImpl(downstreamCodec_, hackIngress);
   }
bool HTTPParallelCodecTest::parseImpl (proxygen::HTTPParallelCodec & codec, std::function< void(folly::IOBuf *)> hackIngress) inline
Definition at line 51 of file HTTPParallelCodecTest.h.
References dumpToFile(), proxygen::HTTPParallelCodec::getTransportDirection(), folly::IOBufQueue::move(), proxygen::HTTPCodec::onIngress(), output_, and proxygen::UPSTREAM.
Referenced by parse(), and parseUpstream().
{
     dumpToFile(codec.getTransportDirection() ==
                proxygen::TransportDirection::UPSTREAM);
     auto ingress = output_.move();
     if (hackIngress) {
       hackIngress(ingress.get());
     }
     size_t parsed = codec.onIngress(*ingress);
     return (parsed == ingress->computeChainDataLength());
   }
bool HTTPParallelCodecTest::parseUpstream (std::function< void(folly::IOBuf *)> hackIngress = std::function<void(folly::IOBuf*)>()) inline
Definition at line 42 of file HTTPParallelCodecTest.h.
References parseImpl(), and upstreamCodec_.
{
     return parseImpl(upstreamCodec_, hackIngress);
   }
void HTTPParallelCodecTest::SetUp () inline override virtual
Reimplemented from testing::Test.
Definition at line 23 of file HTTPParallelCodecTest.h.
References callbacks_, downstreamCodec_, proxygen::HTTPCodec::generateConnectionPreface(), output_, proxygen::HTTPParallelCodec::setCallback(), and upstreamCodec_.
Referenced by HTTP2CodecTest::SetUp().
{
     downstreamCodec_.setCallback(&callbacks_);
     upstreamCodec_.setCallback(&callbacks_);
     // Most tests are downstream tests, so generate the upstream conn preface
     // by default
     upstreamCodec_.generateConnectionPreface(output_);
   }
void HTTPParallelCodecTest::SetUpUpstreamTest () inline
Definition at line 31 of file HTTPParallelCodecTest.h.
References downstreamCodec_, proxygen::HTTPCodec::generateConnectionPreface(), proxygen::HTTPCodec::generateSettings(), folly::IOBufQueue::move(), and output_.
{
     output_.move();
     downstreamCodec_.generateConnectionPreface(output_); // no-op
     downstreamCodec_.generateSettings(output_);
   }
Member Data Documentation
proxygen::FakeHTTPCodecCallback HTTPParallelCodecTest::callbacks_ protected
Definition at line 79 of file HTTPParallelCodecTest.h.
Referenced by SetUp().
proxygen::HTTPParallelCodec& HTTPParallelCodecTest::downstreamCodec_ protected
Definition at line 81 of file HTTPParallelCodecTest.h.
Referenced by parse(), SetUp(), and SetUpUpstreamTest().
bool HTTPParallelCodecTest::dump_ {false} protected
Definition at line 85 of file HTTPParallelCodecTest.h.
Referenced by dumpToFile().
folly::IOBufQueue HTTPParallelCodecTest::output_ {folly::IOBufQueue::cacheChainLength()} protected
Definition at line 82 of file HTTPParallelCodecTest.h.
Referenced by dumpToFile(), parseImpl(), SetUp(), and SetUpUpstreamTest().
const testing::TestInfo* HTTPParallelCodecTest::testInfo_ {testing::UnitTest::GetInstance()->current_test_info()} protected
Definition at line 84 of file HTTPParallelCodecTest.h.
Referenced by dumpToFile().
proxygen::HTTPParallelCodec& HTTPParallelCodecTest::upstreamCodec_ protected
Definition at line 80 of file HTTPParallelCodecTest.h.
Referenced by parseUpstream(), and SetUp().
The documentation for this class was generated from the following file:
proxygen/lib/http/codec/test/HTTPParallelCodecTest.h