proxygen: testing::Message Class Reference
testing::Message Class Reference
#include <gtest-message.h>
Public Member Functions
Message ()
Message (const Message &msg)
Message (const char *str)
template<typename T >
Message & operator<< (const T &val)
template<typename T >
Message & operator<< (T *const &pointer)
Message & operator<< (BasicNarrowIoManip val)
Message & operator<< (bool b)
Message & operator<< (const wchar_t *wide_c_str)
Message & operator<< (wchar_t *wide_c_str)
std::string GetString () const
Message ()
Message (const Message &msg)
Message (const char *str)
template<typename T >
Message & operator<< (const T &val)
template<typename T >
Message & operator<< (T *const &pointer)
Message & operator<< (BasicNarrowIoManip val)
Message & operator<< (bool b)
Message & operator<< (const wchar_t *wide_c_str)
Message & operator<< (wchar_t *wide_c_str)
std::string GetString () const
Message ()
Message (const Message &msg)
Message (const char *str)
template<typename T >
Message & operator<< (const T &val)
template<typename T >
Message & operator<< (T *const &pointer)
Message & operator<< (BasicNarrowIoManip val)
Message & operator<< (bool b)
Message & operator<< (const wchar_t *wide_c_str)
Message & operator<< (wchar_t *wide_c_str)
std::string GetString () const
Private Types
typedef std::ostream &(* BasicNarrowIoManip) (std::ostream &)
typedef std::ostream &(* BasicNarrowIoManip) (std::ostream &)
typedef std::ostream &(* BasicNarrowIoManip) (std::ostream &)
Private Member Functions
void operator= (const Message &)
void operator= (const Message &)
void operator= (const Message &)
Private Attributes
const internal::scoped_ptr< ::std::stringstream > ss_
Detailed Description
Definition at line 85 of file gtest-message.h.
Member Typedef Documentation
typedef std::ostream&(* testing::Message::BasicNarrowIoManip) (std::ostream &) private
Definition at line 89 of file gtest-message.h.
typedef std::ostream&(* testing::Message::BasicNarrowIoManip) (std::ostream &) private
Definition at line 89 of file gtest-message.h.
typedef std::ostream&(* testing::Message::BasicNarrowIoManip) (std::ostream &) private
Definition at line 89 of file gtest-message.h.
Constructor & Destructor Documentation
testing::Message::Message ()
Definition at line 946 of file gtest.cc.
References folly::digits10().
Referenced by testing::internal::ShouldRunTestCase().
                  : ss_(new ::std::stringstream) {
   // By default, we want there to be enough precision when printing
   // a double to a Message.
   *ss_ << std::setprecision(std::numeric_limits<double>::digits10 + 2);
 }
testing::Message::Message (const Message & msg) inline
Definition at line 96 of file gtest-message.h.
References GetString().
                               : ss_(new ::std::stringstream) {  // NOLINT
     *ss_ << msg.GetString();
   }
testing::Message::Message (const char * str) inline explicit
Definition at line 101 of file gtest-message.h.
References testing::operator<<(), T, and value.
                                     : ss_(new ::std::stringstream) {
     *ss_ << str;
   }
testing::Message::Message ()
testing::Message::Message (const Message & msg) inline
Definition at line 96 of file gtest-message.h.
References GetString().
                               : ss_(new ::std::stringstream) {  // NOLINT
     *ss_ << msg.GetString();
   }
testing::Message::Message (const char * str) inline explicit
Definition at line 101 of file gtest-message.h.
References testing::operator<<(), T, and value.
                                     : ss_(new ::std::stringstream) {
     *ss_ << str;
   }
testing::Message::Message ()
testing::Message::Message (const Message & msg) inline
Definition at line 96 of file gtest-message.h.
References GetString().
                               : ss_(new ::std::stringstream) {  // NOLINT
     *ss_ << msg.GetString();
   }
testing::Message::Message (const char * str) inline explicit
Definition at line 101 of file gtest-message.h.
References testing::operator<<(), T, and value.
                                     : ss_(new ::std::stringstream) {
     *ss_ << str;
   }
Member Function Documentation
std::string testing::Message::GetString () const
Definition at line 981 of file gtest.cc.
References testing::internal::scoped_ptr< T >::get(), ss_, and testing::internal::StringStreamToString().
Referenced by testing::UnitTest::AddTestPartResult(), testing::AssertionResult::AppendMessage(), testing::internal::AppendUserMessage(), testing::internal::XmlUnitTestResultPrinter::EscapeXml(), testing::internal::XmlUnitTestResultPrinter::EscapeXmlText(), testing::internal::FlagToEnvVar(), testing::FormatWordList(), testing::internal::GetBoolAssertionFailureMessage(), SequenceTestingListener::GetEventDescription(), testing::Test::HasSameFixtureClass(), testing::internal::MakeAndRegisterTestInfo(), Message(), testing::internal::EventRecordingListener::OnTestIterationEnd(), testing::internal::EventRecordingListener::OnTestIterationStart(), operator<<(), testing::operator<<(), testing::internal::ParseInt32(), testing::internal::PortableLocaltime(), testing::Test::RecordProperty(), testing::internal::ShouldRunTestCase(), testing::internal::ShouldShard(), testing::internal::TearDownEnvironment(), TEST(), testing::TestPartNonfatallyFailed(), testing::internal::XmlUnitTestResultPrinter::TestPropertiesAsXmlAttributes(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
   return internal::StringStreamToString(ss_.get());
 }
std::string testing::Message::GetString () const
std::string testing::Message::GetString () const
template<typename T > Message& testing::Message::operator<< (const T & val) inline
Definition at line 115 of file gtest-message.h.
References val.
{
     // Some libraries overload << for STL containers.  These
     // overloads are defined in the global namespace instead of ::std.
     //
     // C++'s symbol lookup rule (i.e. Koenig lookup) says that these
     // overloads are visible in either the std namespace or the global
     // namespace, but not other namespaces, including the testing
     // namespace which Google Test's Message class is in.
     //
     // To allow STL containers (and other types that has a << operator
     // defined in the global namespace) to be used in Google Test
     // assertions, testing::Message must access the custom << operator
     // from the global namespace.  With this using declaration,
     // overloads of << defined in the global namespace and those
     // visible via Koenig lookup are both exposed in this function.
     using ::operator <<;
     *ss_ << val;
     return *this;
   }
template<typename T > Message& testing::Message::operator<< (const T & val) inline
Definition at line 115 of file gtest-message.h.
References val.
{
     // Some libraries overload << for STL containers.  These
     // overloads are defined in the global namespace instead of ::std.
     //
     // C++'s symbol lookup rule (i.e. Koenig lookup) says that these
     // overloads are visible in either the std namespace or the global
     // namespace, but not other namespaces, including the testing
     // namespace which Google Test's Message class is in.
     //
     // To allow STL containers (and other types that has a << operator
     // defined in the global namespace) to be used in Google Test
     // assertions, testing::Message must access the custom << operator
     // from the global namespace.  With this using declaration,
     // overloads of << defined in the global namespace and those
     // visible via Koenig lookup are both exposed in this function.
     using ::operator <<;
     *ss_ << val;
     return *this;
   }
template<typename T > Message& testing::Message::operator<< (const T & val) inline
Definition at line 115 of file gtest-message.h.
References val.
Referenced by operator<<(), and testing::internal::ShouldRunTestCase().
{
     // Some libraries overload << for STL containers.  These
     // overloads are defined in the global namespace instead of ::std.
     //
     // C++'s symbol lookup rule (i.e. Koenig lookup) says that these
     // overloads are visible in either the std namespace or the global
     // namespace, but not other namespaces, including the testing
     // namespace which Google Test's Message class is in.
     //
     // To allow STL containers (and other types that has a << operator
     // defined in the global namespace) to be used in Google Test
     // assertions, testing::Message must access the custom << operator
     // from the global namespace.  With this using declaration,
     // overloads of << defined in the global namespace and those
     // visible via Koenig lookup are both exposed in this function.
     using ::operator <<;
     *ss_ << val;
     return *this;
   }
template<typename T > Message& testing::Message::operator<< (T *const & pointer) inline
Definition at line 149 of file gtest-message.h.
                                                  {  // NOLINT
     if (pointer == NULL) {
       *ss_ << "(null)";
     } else {
       *ss_ << pointer;
     }
     return *this;
   }
template<typename T > Message& testing::Message::operator<< (T *const & pointer) inline
Definition at line 149 of file gtest-message.h.
                                                  {  // NOLINT
     if (pointer == NULL) {
       *ss_ << "(null)";
     } else {
       *ss_ << pointer;
     }
     return *this;
   }
template<typename T > Message& testing::Message::operator<< (T *const & pointer) inline
Definition at line 149 of file gtest-message.h.
                                                  {  // NOLINT
     if (pointer == NULL) {
       *ss_ << "(null)";
     } else {
       *ss_ << pointer;
     }
     return *this;
   }
Message& testing::Message::operator<< (BasicNarrowIoManip val) inline
Definition at line 165 of file gtest-message.h.
References val.
{
     *ss_ << val;
     return *this;
   }
Message& testing::Message::operator<< (BasicNarrowIoManip val) inline
Definition at line 165 of file gtest-message.h.
References val.
{
     *ss_ << val;
     return *this;
   }
Message& testing::Message::operator<< (BasicNarrowIoManip val) inline
Definition at line 165 of file gtest-message.h.
References val.
{
     *ss_ << val;
     return *this;
   }
Message& testing::Message::operator<< (bool b) inline
Definition at line 171 of file gtest-message.h.
References testing::operator<<(), string, T, and value.
{
     return *this << (b ? "true" : "false");
   }
Message& testing::Message::operator<< (bool b) inline
Definition at line 171 of file gtest-message.h.
References GetString(), testing::operator<<(), testing::internal::StreamableToString(), string, T, and value.
{
     return *this << (b ? "true" : "false");
   }
Message& testing::Message::operator<< (bool b) inline
Definition at line 171 of file gtest-message.h.
References GetString(), testing::operator<<(), testing::internal::StreamableToString(), string, T, and value.
{
     return *this << (b ? "true" : "false");
   }
Message& testing::Message::operator<< (const wchar_t * wide_c_str)
Message& testing::Message::operator<< (const wchar_t * wide_c_str)
Message & testing::Message::operator<< (const wchar_t * wide_c_str)
Definition at line 954 of file gtest.cc.
References testing::internal::String::ShowWideCString().
{
   return *this << internal::String::ShowWideCString(wide_c_str);
 }
Message& testing::Message::operator<< (wchar_t * wide_c_str)
Message & testing::Message::operator<< (wchar_t * wide_c_str)
Definition at line 957 of file gtest.cc.
References operator<<(), and testing::internal::String::ShowWideCString().
{
   return *this << internal::String::ShowWideCString(wide_c_str);
 }
Message& testing::Message::operator<< (wchar_t * wide_c_str)
void testing::Message::operator= (const Message &) private
void testing::Message::operator= (const Message &) private
void testing::Message::operator= (const Message &) private
Member Data Documentation
const internal::scoped_ptr<::std::stringstream > testing::Message::ss_ private
Definition at line 224 of file gtest-message.h.
Referenced by GetString().
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/gtest-message.h
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest.cc