proxygen: CommonTest< T > Class Template Reference
CommonTest< T > Class Template Reference
Static Public Member Functions
static void SetUpTestCase ()
static void TearDownTestCase ()
static void SetUpTestCase ()
static void TearDownTestCase ()
static void SetUpTestCase ()
static void TearDownTestCase ()
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Protected Types
typedef std::vector< T > Vector
typedef std::set< int > IntSet
typedef std::vector< T > Vector
typedef std::set< int > IntSet
typedef std::vector< T > Vector
typedef std::set< int > IntSet
Protected Member Functions
CommonTest ()
virtual ~CommonTest ()
virtual void SetUp ()
virtual void TearDown ()
CommonTest ()
virtual ~CommonTest ()
virtual void SetUp ()
virtual void TearDown ()
CommonTest ()
virtual ~CommonTest ()
virtual void SetUp ()
virtual void TearDown ()
Protected Member Functions inherited from testing::Test
Test ()
Test ()
Test ()
Protected Attributes
T value_
Static Protected Attributes
static T * shared_ = NULL
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Detailed Description
template<typename T>
class CommonTest< T >
Definition at line 45 of file gtest-typed-test_test.cc.
Member Typedef Documentation
template<typename T > typedef std::set<int> CommonTest< T >::IntSet protected
Definition at line 64 of file gtest-typed-test_test.cc.
template<typename T > typedef std::set<int> CommonTest< T >::IntSet protected
Definition at line 64 of file gtest-typed-test_test.cc.
template<typename T > typedef std::set<int> CommonTest< T >::IntSet protected
Definition at line 64 of file gtest-typed-test_test.cc.
template<typename T > typedef std::vector<T> CommonTest< T >::Vector protected
Definition at line 63 of file gtest-typed-test_test.cc.
template<typename T > typedef std::vector<T> CommonTest< T >::Vector protected
Definition at line 63 of file gtest-typed-test_test.cc.
template<typename T > typedef std::vector<T> CommonTest< T >::Vector protected
Definition at line 63 of file gtest-typed-test_test.cc.
Constructor & Destructor Documentation
template<typename T > CommonTest< T >::CommonTest () inline protected
Definition at line 66 of file gtest-typed-test_test.cc.
 : value_(1) {}
template<typename T > virtual CommonTest< T >::~CommonTest () inline protected virtual
Definition at line 68 of file gtest-typed-test_test.cc.
References EXPECT_EQ, and CommonTest< T >::value_.
 { EXPECT_EQ(3, value_); }
template<typename T > CommonTest< T >::CommonTest () inline protected
Definition at line 66 of file gtest-typed-test_test.cc.
 : value_(1) {}
template<typename T > virtual CommonTest< T >::~CommonTest () inline protected virtual
Definition at line 68 of file gtest-typed-test_test.cc.
References EXPECT_EQ, and CommonTest< T >::value_.
 { EXPECT_EQ(3, value_); }
template<typename T > CommonTest< T >::CommonTest () inline protected
Definition at line 66 of file gtest-typed-test_test.cc.
 : value_(1) {}
template<typename T > virtual CommonTest< T >::~CommonTest () inline protected virtual
Definition at line 68 of file gtest-typed-test_test.cc.
References EXPECT_EQ, and CommonTest< T >::value_.
 { EXPECT_EQ(3, value_); }
Member Function Documentation
template<typename T > virtual void CommonTest< T >::SetUp () inline protected virtual
Reimplemented from testing::Test.
Definition at line 70 of file gtest-typed-test_test.cc.
References EXPECT_EQ, and CommonTest< T >::value_.
Referenced by CommonTest< T >::TearDown().
{
     EXPECT_EQ(1, value_);
     value_++;
   }
template<typename T > virtual void CommonTest< T >::SetUp () inline protected virtual
Reimplemented from testing::Test.
Definition at line 70 of file gtest-typed-test_test.cc.
References EXPECT_EQ, and CommonTest< T >::value_.
{
     EXPECT_EQ(1, value_);
     value_++;
   }
template<typename T > virtual void CommonTest< T >::SetUp () inline protected virtual
Reimplemented from testing::Test.
Definition at line 70 of file gtest-typed-test_test.cc.
References EXPECT_EQ, and CommonTest< T >::value_.
{
     EXPECT_EQ(1, value_);
     value_++;
   }
template<typename T > static void CommonTest< T >::SetUpTestCase () inline static
Definition at line 49 of file gtest-typed-test_test.cc.
References CommonTest< T >::shared_, and T.
{
     shared_ = new T(5);
   }
template<typename T > static void CommonTest< T >::SetUpTestCase () inline static
Definition at line 49 of file gtest-typed-test_test.cc.
References CommonTest< T >::shared_, and T.
{
     shared_ = new T(5);
   }
template<typename T > static void CommonTest< T >::SetUpTestCase () inline static
Definition at line 49 of file gtest-typed-test_test.cc.
References CommonTest< T >::shared_, and T.
{
     shared_ = new T(5);
   }
template<typename T > virtual void CommonTest< T >::TearDown () inline protected virtual
Reimplemented from testing::Test.
Definition at line 75 of file gtest-typed-test_test.cc.
References EXPECT_EQ, and CommonTest< T >::value_.
{
     EXPECT_EQ(2, value_);
     value_++;
   }
template<typename T > virtual void CommonTest< T >::TearDown () inline protected virtual
Reimplemented from testing::Test.
Definition at line 75 of file gtest-typed-test_test.cc.
References ASSERT_TRUE, B, testing::UnitTest::current_test_info(), folly::empty(), EXPECT_DEATH_IF_SUPPORTED, EXPECT_EQ, EXPECT_LT, EXPECT_STREQ, testing::UnitTest::GetInstance(), INSTANTIATE_TYPED_TEST_CASE_P(), testing::TestInfo::name(), REGISTER_TYPED_TEST_CASE_P(), CommonTest< T >::SetUp(), CommonTest< T >::shared_, T, TEST_F, TYPED_TEST(), TYPED_TEST_CASE(), TYPED_TEST_CASE_P(), TYPED_TEST_P(), and CommonTest< T >::value_.
{
     EXPECT_EQ(2, value_);
     value_++;
   }
template<typename T > virtual void CommonTest< T >::TearDown () inline protected virtual
Reimplemented from testing::Test.
Definition at line 75 of file gtest-typed-test_test.cc.
References ASSERT_TRUE, B, testing::UnitTest::current_test_info(), folly::empty(), EXPECT_DEATH_IF_SUPPORTED, EXPECT_EQ, EXPECT_LT, EXPECT_STREQ, testing::UnitTest::GetInstance(), INSTANTIATE_TYPED_TEST_CASE_P(), testing::TestInfo::name(), REGISTER_TYPED_TEST_CASE_P(), CommonTest< T >::SetUp(), CommonTest< T >::shared_, T, TEST_F, TYPED_TEST(), TYPED_TEST_CASE(), TYPED_TEST_CASE_P(), TYPED_TEST_P(), and CommonTest< T >::value_.
{
     EXPECT_EQ(2, value_);
     value_++;
   }
template<typename T > static void CommonTest< T >::TearDownTestCase () inline static
Definition at line 53 of file gtest-typed-test_test.cc.
References CommonTest< T >::shared_.
{
     delete shared_;
     shared_ = NULL;
   }
template<typename T > static void CommonTest< T >::TearDownTestCase () inline static
Definition at line 53 of file gtest-typed-test_test.cc.
References CommonTest< T >::shared_.
{
     delete shared_;
     shared_ = NULL;
   }
template<typename T > static void CommonTest< T >::TearDownTestCase () inline static
Definition at line 53 of file gtest-typed-test_test.cc.
References CommonTest< T >::shared_.
{
     delete shared_;
     shared_ = NULL;
   }
Member Data Documentation
template<typename T > T * CommonTest< T >::shared_ = NULL static protected
Definition at line 81 of file gtest-typed-test_test.cc.
Referenced by CommonTest< T >::SetUpTestCase(), CommonTest< T >::TearDown(), and CommonTest< T >::TearDownTestCase().
template<typename T > T CommonTest< T >::value_ protected
Definition at line 80 of file gtest-typed-test_test.cc.
Referenced by CommonTest< T >::SetUp(), CommonTest< T >::TearDown(), and CommonTest< T >::~CommonTest().
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest-typed-test_test.cc