proxygen: testing::internal::ActionResultHolder< void > Class Template Reference
testing::internal::ActionResultHolder< void > Class Template Reference
#include <gmock-spec-builders.h>
Public Member Functions
void Unwrap ()
virtual void PrintAsActionResult (::std::ostream *) const
void Unwrap ()
virtual void PrintAsActionResult (::std::ostream *) const
void Unwrap ()
virtual void PrintAsActionResult (::std::ostream *) const
Public Member Functions inherited from testing::internal::UntypedActionResultHolderBase
virtual ~UntypedActionResultHolderBase ()
virtual ~UntypedActionResultHolderBase ()
virtual ~UntypedActionResultHolderBase ()
Static Public Member Functions
template<typename F >
static ActionResultHolder * PerformDefaultAction (const FunctionMockerBase< F > *func_mocker, const typename Function< F >::ArgumentTuple &args, const string &call_description)
template<typename F >
static ActionResultHolder * PerformAction (const Action< F > &action, const typename Function< F >::ArgumentTuple &args)
template<typename F >
static ActionResultHolder * PerformDefaultAction (const FunctionMockerBase< F > *func_mocker, const typename Function< F >::ArgumentTuple &args, const string &call_description)
template<typename F >
static ActionResultHolder * PerformAction (const Action< F > &action, const typename Function< F >::ArgumentTuple &args)
template<typename F >
static ActionResultHolder * PerformDefaultAction (const FunctionMockerBase< F > *func_mocker, const typename Function< F >::ArgumentTuple &args, const string &call_description)
template<typename F >
static ActionResultHolder * PerformAction (const Action< F > &action, const typename Function< F >::ArgumentTuple &args)
Private Member Functions
ActionResultHolder ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (ActionResultHolder)
ActionResultHolder ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (ActionResultHolder)
ActionResultHolder ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (ActionResultHolder)
Detailed Description
template<>
class testing::internal::ActionResultHolder< void >
Definition at line 1420 of file gmock-spec-builders.h.
Constructor & Destructor Documentation
testing::internal::ActionResultHolder< void >::ActionResultHolder () inline private
Definition at line 1448 of file gmock-spec-builders.h.
References GTEST_DISALLOW_COPY_AND_ASSIGN_.
 {}
testing::internal::ActionResultHolder< void >::ActionResultHolder () inline private
Definition at line 1448 of file gmock-spec-builders.h.
References GTEST_DISALLOW_COPY_AND_ASSIGN_.
 {}
testing::internal::ActionResultHolder< void >::ActionResultHolder () inline private
Definition at line 1448 of file gmock-spec-builders.h.
References GTEST_DISALLOW_COPY_AND_ASSIGN_.
 {}
Member Function Documentation
testing::internal::ActionResultHolder< void >::GTEST_DISALLOW_COPY_AND_ASSIGN_ (ActionResultHolder< void >) private
testing::internal::ActionResultHolder< void >::GTEST_DISALLOW_COPY_AND_ASSIGN_ (ActionResultHolder< void >) private
testing::internal::ActionResultHolder< void >::GTEST_DISALLOW_COPY_AND_ASSIGN_ (ActionResultHolder< void >) private
template<typename F > static ActionResultHolder* testing::internal::ActionResultHolder< void >::PerformAction (const Action< F > & action, const typename Function< F >::ArgumentTuple & args) inline static
Definition at line 1440 of file gmock-spec-builders.h.
References testing::Action< F >::Perform().
{
     action.Perform(args);
     return new ActionResultHolder;
   }
template<typename F > static ActionResultHolder* testing::internal::ActionResultHolder< void >::PerformAction (const Action< F > & action, const typename Function< F >::ArgumentTuple & args) inline static
Definition at line 1440 of file gmock-spec-builders.h.
References testing::Action< F >::Perform().
{
     action.Perform(args);
     return new ActionResultHolder;
   }
template<typename F > static ActionResultHolder* testing::internal::ActionResultHolder< void >::PerformAction (const Action< F > & action, const typename Function< F >::ArgumentTuple & args) inline static
Definition at line 1440 of file gmock-spec-builders.h.
References testing::Action< F >::Perform().
{
     action.Perform(args);
     return new ActionResultHolder;
   }
template<typename F > static ActionResultHolder* testing::internal::ActionResultHolder< void >::PerformDefaultAction (const FunctionMockerBase< F > * func_mocker, const typename Function< F >::ArgumentTuple & args, const string & call_description) inline static
Definition at line 1429 of file gmock-spec-builders.h.
References testing::internal::FunctionMockerBase< F >::PerformDefaultAction().
{
     func_mocker->PerformDefaultAction(args, call_description);
     return new ActionResultHolder;
   }
template<typename F > static ActionResultHolder* testing::internal::ActionResultHolder< void >::PerformDefaultAction (const FunctionMockerBase< F > * func_mocker, const typename Function< F >::ArgumentTuple & args, const string & call_description) inline static
Definition at line 1429 of file gmock-spec-builders.h.
References testing::internal::FunctionMockerBase< F >::PerformDefaultAction().
{
     func_mocker->PerformDefaultAction(args, call_description);
     return new ActionResultHolder;
   }
template<typename F > static ActionResultHolder* testing::internal::ActionResultHolder< void >::PerformDefaultAction (const FunctionMockerBase< F > * func_mocker, const typename Function< F >::ArgumentTuple & args, const string & call_description) inline static
Definition at line 1429 of file gmock-spec-builders.h.
References testing::internal::FunctionMockerBase< F >::PerformDefaultAction().
{
     func_mocker->PerformDefaultAction(args, call_description);
     return new ActionResultHolder;
   }
virtual void testing::internal::ActionResultHolder< void >::PrintAsActionResult (::std::ostream *) const inline virtual
Implements testing::internal::UntypedActionResultHolderBase.
Definition at line 1424 of file gmock-spec-builders.h.
 {}
virtual void testing::internal::ActionResultHolder< void >::PrintAsActionResult (::std::ostream *) const inline virtual
Implements testing::internal::UntypedActionResultHolderBase.
Definition at line 1424 of file gmock-spec-builders.h.
 {}
virtual void testing::internal::ActionResultHolder< void >::PrintAsActionResult (::std::ostream *) const inline virtual
Implements testing::internal::UntypedActionResultHolderBase.
Definition at line 1424 of file gmock-spec-builders.h.
 {}
void testing::internal::ActionResultHolder< void >::Unwrap () inline
Definition at line 1422 of file gmock-spec-builders.h.
 { }
void testing::internal::ActionResultHolder< void >::Unwrap () inline
Definition at line 1422 of file gmock-spec-builders.h.
 { }
void testing::internal::ActionResultHolder< void >::Unwrap () inline
Definition at line 1422 of file gmock-spec-builders.h.
 { }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-spec-builders.h