proxygen: Coordinator Class Reference
Coordinator Class Reference
Public Member Functions
void requestAndWait ()
void waitForRequest ()
void completed ()
Private Attributes
folly::Baton requestBaton_
folly::Baton completeBaton_
Detailed Description
Definition at line 60 of file ReadMostlySharedPtrTest.cpp.
Member Function Documentation
void Coordinator::completed () inline
Definition at line 71 of file ReadMostlySharedPtrTest.cpp.
Referenced by TEST_F().
                    {
     completeBaton_.post();
   }
void Coordinator::requestAndWait () inline
Definition at line 62 of file ReadMostlySharedPtrTest.cpp.
Referenced by TEST_F().
{
     requestBaton_.post();
     completeBaton_.wait();
   }
void Coordinator::waitForRequest () inline
Definition at line 67 of file ReadMostlySharedPtrTest.cpp.
Referenced by TEST_F().
{
     requestBaton_.wait();
   }
Member Data Documentation
folly::Baton Coordinator::completeBaton_ private
Definition at line 77 of file ReadMostlySharedPtrTest.cpp.
folly::Baton Coordinator::requestBaton_ private
Definition at line 76 of file ReadMostlySharedPtrTest.cpp.
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/test/ReadMostlySharedPtrTest.cpp