proxygen: folly::SSLServerAcceptCallbackDelay Class Reference
folly::SSLServerAcceptCallbackDelay Class Reference
#include <AsyncSSLSocketTest.h>
Public Member Functions
SSLServerAcceptCallbackDelay (HandshakeCallback *hcb)
void connAccepted (const std::shared_ptr< folly::AsyncSSLSocket > &s) noexceptoverride
Public Member Functions inherited from folly::SSLServerAcceptCallback
SSLServerAcceptCallback (HandshakeCallback *hcb, uint32_t timeout=0)
~SSLServerAcceptCallback () override
Public Member Functions inherited from folly::SSLServerAcceptCallbackBase
SSLServerAcceptCallbackBase (HandshakeCallback *hcb)
~SSLServerAcceptCallbackBase () override
void acceptError (const std::exception &ex) noexceptoverride
void connectionAccepted (int fd, const SocketAddress &) noexceptoverride
void detach ()
Public Member Functions inherited from folly::AsyncServerSocket::AcceptCallback
virtual ~AcceptCallback ()=default
virtual void acceptStarted () noexcept
virtual void acceptStopped () noexcept
Additional Inherited Members
Public Attributes inherited from folly::SSLServerAcceptCallback
uint32_t timeout_
Public Attributes inherited from folly::SSLServerAcceptCallbackBase
StateEnum state
HandshakeCallback * hcb_
std::shared_ptr< SSLContext > ctx_
std::shared_ptr< AsyncSSLSocket > socket_
EventBase * base_
Detailed Description
Definition at line 575 of file AsyncSSLSocketTest.h.
Constructor & Destructor Documentation
folly::SSLServerAcceptCallbackDelay::SSLServerAcceptCallbackDelay (HandshakeCallback * hcb) inline explicit
Definition at line 577 of file AsyncSSLSocketTest.h.
       : SSLServerAcceptCallback(hcb) {}
Member Function Documentation
void folly::SSLServerAcceptCallbackDelay::connAccepted (const std::shared_ptr< folly::AsyncSSLSocket > & s) inline override virtual noexcept
Reimplemented from folly::SSLServerAcceptCallback.
Definition at line 580 of file AsyncSSLSocketTest.h.
References folly::SSLServerAcceptCallback::connAccepted(), EXPECT_EQ, folly::AsyncSocket::getFd(), folly::netops::getsockopt(), s, folly::netops::setsockopt(), and folly::value().
{
     auto sock = std::static_pointer_cast<AsyncSSLSocket>(s);
     std::cerr << "SSLServerAcceptCallbackDelay::connAccepted" << std::endl;
     int fd = sock->getFd();
 #ifndef TCP_NOPUSH
     {
       // The accepted connection should already have TCP_NODELAY set
       int value;
       socklen_t valueLength = sizeof(value);
       int rc = getsockopt(fd, IPPROTO_TCP, TCP_NODELAY, &value, &valueLength);
       EXPECT_EQ(rc, 0);
       EXPECT_EQ(value, 1);
     }
 #endif
     // Unset the TCP_NODELAY option.
     int value = 0;
     socklen_t valueLength = sizeof(value);
     int rc = setsockopt(fd, IPPROTO_TCP, TCP_NODELAY, &value, valueLength);
     EXPECT_EQ(rc, 0);
     rc = getsockopt(fd, IPPROTO_TCP, TCP_NODELAY, &value, &valueLength);
     EXPECT_EQ(rc, 0);
     EXPECT_EQ(value, 0);
     SSLServerAcceptCallback::connAccepted(sock);
   }
The documentation for this class was generated from the following file:
proxygen/folly/folly/io/async/test/AsyncSSLSocketTest.h