proxygen: testing::internal::HasNewFatalFailureHelper Class Reference
testing::internal::HasNewFatalFailureHelper Class Reference
#include <gtest-test-part.h>
Public Member Functions
HasNewFatalFailureHelper ()
virtual ~HasNewFatalFailureHelper ()
virtual void ReportTestPartResult (const TestPartResult &result)
bool has_new_fatal_failure () const
HasNewFatalFailureHelper ()
virtual ~HasNewFatalFailureHelper ()
virtual void ReportTestPartResult (const TestPartResult &result)
bool has_new_fatal_failure () const
HasNewFatalFailureHelper ()
virtual ~HasNewFatalFailureHelper ()
virtual void ReportTestPartResult (const TestPartResult &result)
bool has_new_fatal_failure () const
Public Member Functions inherited from testing::TestPartResultReporterInterface
virtual ~TestPartResultReporterInterface ()
virtual ~TestPartResultReporterInterface ()
virtual ~TestPartResultReporterInterface ()
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (HasNewFatalFailureHelper)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (HasNewFatalFailureHelper)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (HasNewFatalFailureHelper)
Private Attributes
bool has_new_fatal_failure_
TestPartResultReporterInterface * original_reporter_
Detailed Description
Definition at line 161 of file gtest-test-part.h.
Constructor & Destructor Documentation
testing::internal::HasNewFatalFailureHelper::HasNewFatalFailureHelper ()
Definition at line 89 of file gtest-test-part.cc.
References testing::internal::GetUnitTestImpl(), and testing::internal::UnitTestImpl::SetTestPartResultReporterForCurrentThread().
     : has_new_fatal_failure_(false),
       original_reporter_(GetUnitTestImpl()->
                          GetTestPartResultReporterForCurrentThread()) {
   GetUnitTestImpl()->SetTestPartResultReporterForCurrentThread(this);
 }
testing::internal::HasNewFatalFailureHelper::~HasNewFatalFailureHelper () virtual
Definition at line 96 of file gtest-test-part.cc.
References testing::internal::GetUnitTestImpl(), original_reporter_, and testing::internal::UnitTestImpl::SetTestPartResultReporterForCurrentThread().
{
   GetUnitTestImpl()->SetTestPartResultReporterForCurrentThread(
       original_reporter_);
 }
testing::internal::HasNewFatalFailureHelper::HasNewFatalFailureHelper ()
virtual testing::internal::HasNewFatalFailureHelper::~HasNewFatalFailureHelper () virtual
testing::internal::HasNewFatalFailureHelper::HasNewFatalFailureHelper ()
virtual testing::internal::HasNewFatalFailureHelper::~HasNewFatalFailureHelper () virtual
Member Function Documentation
testing::internal::HasNewFatalFailureHelper::GTEST_DISALLOW_COPY_AND_ASSIGN_ (HasNewFatalFailureHelper) private
testing::internal::HasNewFatalFailureHelper::GTEST_DISALLOW_COPY_AND_ASSIGN_ (HasNewFatalFailureHelper) private
testing::internal::HasNewFatalFailureHelper::GTEST_DISALLOW_COPY_AND_ASSIGN_ (HasNewFatalFailureHelper) private
bool testing::internal::HasNewFatalFailureHelper::has_new_fatal_failure () const inline
Definition at line 167 of file gtest-test-part.h.
References GTEST_DISALLOW_COPY_AND_ASSIGN_.
 { return has_new_fatal_failure_; }
bool testing::internal::HasNewFatalFailureHelper::has_new_fatal_failure () const inline
Definition at line 167 of file gtest-test-part.h.
References GTEST_DISALLOW_COPY_AND_ASSIGN_.
 { return has_new_fatal_failure_; }
bool testing::internal::HasNewFatalFailureHelper::has_new_fatal_failure () const inline
Definition at line 167 of file gtest-test-part.h.
 { return has_new_fatal_failure_; }
virtual void testing::internal::HasNewFatalFailureHelper::ReportTestPartResult (const TestPartResult & result) virtual
Implements testing::TestPartResultReporterInterface.
void testing::internal::HasNewFatalFailureHelper::ReportTestPartResult (const TestPartResult & result) virtual
Implements testing::TestPartResultReporterInterface.
Definition at line 101 of file gtest-test-part.cc.
References testing::TestPartResult::fatally_failed(), has_new_fatal_failure_, original_reporter_, and testing::TestPartResultReporterInterface::ReportTestPartResult().
{
   if (result.fatally_failed())
     has_new_fatal_failure_ = true;
   original_reporter_->ReportTestPartResult(result);
 }
virtual void testing::internal::HasNewFatalFailureHelper::ReportTestPartResult (const TestPartResult & result) virtual
Implements testing::TestPartResultReporterInterface.
Member Data Documentation
bool testing::internal::HasNewFatalFailureHelper::has_new_fatal_failure_ private
Definition at line 169 of file gtest-test-part.h.
Referenced by ReportTestPartResult().
TestPartResultReporterInterface * testing::internal::HasNewFatalFailureHelper::original_reporter_ private
Definition at line 170 of file gtest-test-part.h.
Referenced by ReportTestPartResult(), and ~HasNewFatalFailureHelper().
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/gtest-test-part.h
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest-test-part.cc