proxygen: testing::gmock_generated_actions_test::NullaryConstructorClass Class Reference
testing::gmock_generated_actions_test::NullaryConstructorClass Class Reference
Public Member Functions
NullaryConstructorClass ()
NullaryConstructorClass ()
NullaryConstructorClass ()
Public Attributes
int value_
Detailed Description
Definition at line 1007 of file gmock-generated-actions_test.cc.
Constructor & Destructor Documentation
testing::gmock_generated_actions_test::NullaryConstructorClass::NullaryConstructorClass () inline
Definition at line 1009 of file gmock-generated-actions_test.cc.
 : value_(123) {}
testing::gmock_generated_actions_test::NullaryConstructorClass::NullaryConstructorClass () inline
Definition at line 1009 of file gmock-generated-actions_test.cc.
References c, EXPECT_EQ, std::tr1::make_tuple(), testing::Action< F >::Perform(), and testing::gmock_generated_actions_test::TEST().
 : value_(123) {}
testing::gmock_generated_actions_test::NullaryConstructorClass::NullaryConstructorClass () inline
Definition at line 1009 of file gmock-generated-actions_test.cc.
References c, EXPECT_EQ, std::tr1::make_tuple(), testing::Action< F >::Perform(), and testing::gmock_generated_actions_test::TEST().
 : value_(123) {}
Member Data Documentation
int testing::gmock_generated_actions_test::NullaryConstructorClass::value_
Definition at line 1010 of file gmock-generated-actions_test.cc.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-generated-actions_test.cc