proxygen: testing::internal::ContainerEqMatcher< Container > Class Template Reference
testing::internal::ContainerEqMatcher< Container > Class Template Reference
#include <gmock-matchers.h>
Public Types
typedef internal::StlContainerView< Container > View
typedef View::type StlContainer
typedef View::const_reference StlContainerReference
typedef internal::StlContainerView< Container > View
typedef View::type StlContainer
typedef View::const_reference StlContainerReference
typedef internal::StlContainerView< Container > View
typedef View::type StlContainer
typedef View::const_reference StlContainerReference
Public Member Functions
ContainerEqMatcher (const Container &expected)
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
template<typename LhsContainer >
bool MatchAndExplain (const LhsContainer &lhs, MatchResultListener *listener) const
ContainerEqMatcher (const Container &expected)
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
template<typename LhsContainer >
bool MatchAndExplain (const LhsContainer &lhs, MatchResultListener *listener) const
ContainerEqMatcher (const Container &expected)
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
template<typename LhsContainer >
bool MatchAndExplain (const LhsContainer &lhs, MatchResultListener *listener) const
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (ContainerEqMatcher)
GTEST_DISALLOW_ASSIGN_ (ContainerEqMatcher)
GTEST_DISALLOW_ASSIGN_ (ContainerEqMatcher)
Private Attributes
const StlContainer expected_
Detailed Description
template<typename Container>
class testing::internal::ContainerEqMatcher< Container >
Definition at line 2521 of file gmock-matchers.h.
Member Typedef Documentation
template<typename Container > typedef View::type testing::internal::ContainerEqMatcher< Container >::StlContainer
Definition at line 2524 of file gmock-matchers.h.
template<typename Container > typedef View::type testing::internal::ContainerEqMatcher< Container >::StlContainer
Definition at line 2524 of file gmock-matchers.h.
template<typename Container > typedef View::type testing::internal::ContainerEqMatcher< Container >::StlContainer
Definition at line 2524 of file gmock-matchers.h.
template<typename Container > typedef View::const_reference testing::internal::ContainerEqMatcher< Container >::StlContainerReference
Definition at line 2525 of file gmock-matchers.h.
template<typename Container > typedef View::const_reference testing::internal::ContainerEqMatcher< Container >::StlContainerReference
Definition at line 2525 of file gmock-matchers.h.
template<typename Container > typedef View::const_reference testing::internal::ContainerEqMatcher< Container >::StlContainerReference
Definition at line 2525 of file gmock-matchers.h.
template<typename Container > typedef internal::StlContainerView<Container> testing::internal::ContainerEqMatcher< Container >::View
Definition at line 2523 of file gmock-matchers.h.
template<typename Container > typedef internal::StlContainerView<Container> testing::internal::ContainerEqMatcher< Container >::View
Definition at line 2523 of file gmock-matchers.h.
template<typename Container > typedef internal::StlContainerView<Container> testing::internal::ContainerEqMatcher< Container >::View
Definition at line 2523 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename Container > testing::internal::ContainerEqMatcher< Container >::ContainerEqMatcher (const Container & expected) inline explicit
Definition at line 2529 of file gmock-matchers.h.
References GTEST_REMOVE_REFERENCE_AND_CONST_, and testing::StaticAssertTypeEq().
       : expected_(View::Copy(expected)) {
     // Makes sure the user doesn't instantiate this class template
     // with a const or reference type.
     (void)testing::StaticAssertTypeEq<Container,
         GTEST_REMOVE_REFERENCE_AND_CONST_(Container)>();
   }
template<typename Container > testing::internal::ContainerEqMatcher< Container >::ContainerEqMatcher (const Container & expected) inline explicit
Definition at line 2529 of file gmock-matchers.h.
References GTEST_REMOVE_REFERENCE_AND_CONST_, and testing::StaticAssertTypeEq().
       : expected_(View::Copy(expected)) {
     // Makes sure the user doesn't instantiate this class template
     // with a const or reference type.
     (void)testing::StaticAssertTypeEq<Container,
         GTEST_REMOVE_REFERENCE_AND_CONST_(Container)>();
   }
template<typename Container > testing::internal::ContainerEqMatcher< Container >::ContainerEqMatcher (const Container & expected) inline explicit
Definition at line 2529 of file gmock-matchers.h.
References GTEST_REMOVE_REFERENCE_AND_CONST_, and testing::StaticAssertTypeEq().
       : expected_(View::Copy(expected)) {
     // Makes sure the user doesn't instantiate this class template
     // with a const or reference type.
     (void)testing::StaticAssertTypeEq<Container,
         GTEST_REMOVE_REFERENCE_AND_CONST_(Container)>();
   }
Member Function Documentation
template<typename Container > void testing::internal::ContainerEqMatcher< Container >::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 2541 of file gmock-matchers.h.
References testing::internal::UniversalPrint().
{
     *os << "does not equal ";
     UniversalPrint(expected_, os);
   }
template<typename Container > void testing::internal::ContainerEqMatcher< Container >::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 2541 of file gmock-matchers.h.
References testing::internal::UniversalPrint().
{
     *os << "does not equal ";
     UniversalPrint(expected_, os);
   }
template<typename Container > void testing::internal::ContainerEqMatcher< Container >::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 2541 of file gmock-matchers.h.
References testing::internal::UniversalPrint().
{
     *os << "does not equal ";
     UniversalPrint(expected_, os);
   }
template<typename Container > void testing::internal::ContainerEqMatcher< Container >::DescribeTo (::std::ostream * os) const inline
Definition at line 2537 of file gmock-matchers.h.
References testing::internal::UniversalPrint().
{
     *os << "equals ";
     UniversalPrint(expected_, os);
   }
template<typename Container > void testing::internal::ContainerEqMatcher< Container >::DescribeTo (::std::ostream * os) const inline
Definition at line 2537 of file gmock-matchers.h.
References testing::internal::UniversalPrint().
{
     *os << "equals ";
     UniversalPrint(expected_, os);
   }
template<typename Container > void testing::internal::ContainerEqMatcher< Container >::DescribeTo (::std::ostream * os) const inline
Definition at line 2537 of file gmock-matchers.h.
References testing::internal::UniversalPrint().
{
     *os << "equals ";
     UniversalPrint(expected_, os);
   }
template<typename Container > testing::internal::ContainerEqMatcher< Container >::GTEST_DISALLOW_ASSIGN_ (ContainerEqMatcher< Container >) private
template<typename Container > testing::internal::ContainerEqMatcher< Container >::GTEST_DISALLOW_ASSIGN_ (ContainerEqMatcher< Container >) private
template<typename Container > testing::internal::ContainerEqMatcher< Container >::GTEST_DISALLOW_ASSIGN_ (ContainerEqMatcher< Container >) private
template<typename Container > template<typename LhsContainer > bool testing::internal::ContainerEqMatcher< Container >::MatchAndExplain (const LhsContainer & lhs, MatchResultListener * listener) const inline
Definition at line 2547 of file gmock-matchers.h.
References testing::internal::ArrayAwareFind(), testing::MatchResultListener::stream(), type, and testing::internal::UniversalPrint().
{
     // GTEST_REMOVE_CONST_() is needed to work around an MSVC 8.0 bug
     // that causes LhsContainer to be a const type sometimes.
     typedef internal::StlContainerView<GTEST_REMOVE_CONST_(LhsContainer)>
         LhsView;
     typedef typename LhsView::type LhsStlContainer;
     StlContainerReference lhs_stl_container = LhsView::ConstReference(lhs);
     if (lhs_stl_container == expected_)
       return true;
     ::std::ostream* const os = listener->stream();
     if (os != NULL) {
       // Something is different. Check for extra values first.
       bool printed_header = false;
       for (typename LhsStlContainer::const_iterator it =
                lhs_stl_container.begin();
            it != lhs_stl_container.end(); ++it) {
         if (internal::ArrayAwareFind(expected_.begin(), expected_.end(), *it) ==
             expected_.end()) {
           if (printed_header) {
             *os << ", ";
           } else {
             *os << "which has these unexpected elements: ";
             printed_header = true;
           }
           UniversalPrint(*it, os);
         }
       }
       // Now check for missing values.
       bool printed_header2 = false;
       for (typename StlContainer::const_iterator it = expected_.begin();
            it != expected_.end(); ++it) {
         if (internal::ArrayAwareFind(
                 lhs_stl_container.begin(), lhs_stl_container.end(), *it) ==
             lhs_stl_container.end()) {
           if (printed_header2) {
             *os << ", ";
           } else {
             *os << (printed_header ? ",\nand" : "which")
                 << " doesn't have these expected elements: ";
             printed_header2 = true;
           }
           UniversalPrint(*it, os);
         }
       }
     }
     return false;
   }
template<typename Container > template<typename LhsContainer > bool testing::internal::ContainerEqMatcher< Container >::MatchAndExplain (const LhsContainer & lhs, MatchResultListener * listener) const inline
Definition at line 2547 of file gmock-matchers.h.
References testing::internal::ArrayAwareFind(), GTEST_DISALLOW_ASSIGN_, type, and testing::internal::UniversalPrint().
{
     // GTEST_REMOVE_CONST_() is needed to work around an MSVC 8.0 bug
     // that causes LhsContainer to be a const type sometimes.
     typedef internal::StlContainerView<GTEST_REMOVE_CONST_(LhsContainer)>
         LhsView;
     typedef typename LhsView::type LhsStlContainer;
     StlContainerReference lhs_stl_container = LhsView::ConstReference(lhs);
     if (lhs_stl_container == expected_)
       return true;
     ::std::ostream* const os = listener->stream();
     if (os != NULL) {
       // Something is different. Check for extra values first.
       bool printed_header = false;
       for (typename LhsStlContainer::const_iterator it =
                lhs_stl_container.begin();
            it != lhs_stl_container.end(); ++it) {
         if (internal::ArrayAwareFind(expected_.begin(), expected_.end(), *it) ==
             expected_.end()) {
           if (printed_header) {
             *os << ", ";
           } else {
             *os << "which has these unexpected elements: ";
             printed_header = true;
           }
           UniversalPrint(*it, os);
         }
       }
       // Now check for missing values.
       bool printed_header2 = false;
       for (typename StlContainer::const_iterator it = expected_.begin();
            it != expected_.end(); ++it) {
         if (internal::ArrayAwareFind(
                 lhs_stl_container.begin(), lhs_stl_container.end(), *it) ==
             lhs_stl_container.end()) {
           if (printed_header2) {
             *os << ", ";
           } else {
             *os << (printed_header ? ",\nand" : "which")
                 << " doesn't have these expected elements: ";
             printed_header2 = true;
           }
           UniversalPrint(*it, os);
         }
       }
     }
     return false;
   }
template<typename Container > template<typename LhsContainer > bool testing::internal::ContainerEqMatcher< Container >::MatchAndExplain (const LhsContainer & lhs, MatchResultListener * listener) const inline
Definition at line 2547 of file gmock-matchers.h.
References testing::internal::ArrayAwareFind(), GTEST_DISALLOW_ASSIGN_, type, and testing::internal::UniversalPrint().
{
     // GTEST_REMOVE_CONST_() is needed to work around an MSVC 8.0 bug
     // that causes LhsContainer to be a const type sometimes.
     typedef internal::StlContainerView<GTEST_REMOVE_CONST_(LhsContainer)>
         LhsView;
     typedef typename LhsView::type LhsStlContainer;
     StlContainerReference lhs_stl_container = LhsView::ConstReference(lhs);
     if (lhs_stl_container == expected_)
       return true;
     ::std::ostream* const os = listener->stream();
     if (os != NULL) {
       // Something is different. Check for extra values first.
       bool printed_header = false;
       for (typename LhsStlContainer::const_iterator it =
                lhs_stl_container.begin();
            it != lhs_stl_container.end(); ++it) {
         if (internal::ArrayAwareFind(expected_.begin(), expected_.end(), *it) ==
             expected_.end()) {
           if (printed_header) {
             *os << ", ";
           } else {
             *os << "which has these unexpected elements: ";
             printed_header = true;
           }
           UniversalPrint(*it, os);
         }
       }
       // Now check for missing values.
       bool printed_header2 = false;
       for (typename StlContainer::const_iterator it = expected_.begin();
            it != expected_.end(); ++it) {
         if (internal::ArrayAwareFind(
                 lhs_stl_container.begin(), lhs_stl_container.end(), *it) ==
             lhs_stl_container.end()) {
           if (printed_header2) {
             *os << ", ";
           } else {
             *os << (printed_header ? ",\nand" : "which")
                 << " doesn't have these expected elements: ";
             printed_header2 = true;
           }
           UniversalPrint(*it, os);
         }
       }
     }
     return false;
   }
Member Data Documentation
template<typename Container > const StlContainer testing::internal::ContainerEqMatcher< Container >::expected_ private
Definition at line 2600 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h