proxygen: testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container > Class Template Reference
testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container > Class Template Reference
#include <gmock-matchers.h>
Public Types
typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(Container)> ContainerView
typedef ContainerView::type::size_type SizeType
typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(Container)> ContainerView
typedef ContainerView::type::size_type SizeType
typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(Container)> ContainerView
typedef ContainerView::type::size_type SizeType
Public Member Functions
Impl (const SizeMatcher &size_matcher)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (Container container, MatchResultListener *listener) const
Impl (const SizeMatcher &size_matcher)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (Container container, MatchResultListener *listener) const
Impl (const SizeMatcher &size_matcher)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (Container container, MatchResultListener *listener) const
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
virtual ~MatcherDescriberInterface ()
virtual ~MatcherDescriberInterface ()
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (Impl)
GTEST_DISALLOW_ASSIGN_ (Impl)
GTEST_DISALLOW_ASSIGN_ (Impl)
Private Attributes
const Matcher< SizeType > size_matcher_
Detailed Description
template<typename SizeMatcher>
template<typename Container>
class testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >
Definition at line 2411 of file gmock-matchers.h.
Member Typedef Documentation
template<typename SizeMatcher > template<typename Container > typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(Container)> testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::ContainerView
Definition at line 2414 of file gmock-matchers.h.
template<typename SizeMatcher > template<typename Container > typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(Container)> testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::ContainerView
Definition at line 2414 of file gmock-matchers.h.
template<typename SizeMatcher > template<typename Container > typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(Container)> testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::ContainerView
Definition at line 2414 of file gmock-matchers.h.
template<typename SizeMatcher > template<typename Container > typedef ContainerView::type::size_type testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::SizeType
Definition at line 2415 of file gmock-matchers.h.
template<typename SizeMatcher > template<typename Container > typedef ContainerView::type::size_type testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::SizeType
Definition at line 2415 of file gmock-matchers.h.
template<typename SizeMatcher > template<typename Container > typedef ContainerView::type::size_type testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::SizeType
Definition at line 2415 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename SizeMatcher > template<typename Container > testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::Impl (const SizeMatcher & size_matcher) inline explicit
Definition at line 2416 of file gmock-matchers.h.
         : size_matcher_(MatcherCast<SizeType>(size_matcher)) {}
template<typename SizeMatcher > template<typename Container > testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::Impl (const SizeMatcher & size_matcher) inline explicit
Definition at line 2416 of file gmock-matchers.h.
         : size_matcher_(MatcherCast<SizeType>(size_matcher)) {}
template<typename SizeMatcher > template<typename Container > testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::Impl (const SizeMatcher & size_matcher) inline explicit
Definition at line 2416 of file gmock-matchers.h.
         : size_matcher_(MatcherCast<SizeType>(size_matcher)) {}
Member Function Documentation
template<typename SizeMatcher > template<typename Container > virtual void testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 2423 of file gmock-matchers.h.
{
       *os << "size ";
       size_matcher_.DescribeNegationTo(os);
     }
template<typename SizeMatcher > template<typename Container > virtual void testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 2423 of file gmock-matchers.h.
{
       *os << "size ";
       size_matcher_.DescribeNegationTo(os);
     }
template<typename SizeMatcher > template<typename Container > virtual void testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 2423 of file gmock-matchers.h.
{
       *os << "size ";
       size_matcher_.DescribeNegationTo(os);
     }
template<typename SizeMatcher > template<typename Container > virtual void testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 2419 of file gmock-matchers.h.
{
       *os << "size ";
       size_matcher_.DescribeTo(os);
     }
template<typename SizeMatcher > template<typename Container > virtual void testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 2419 of file gmock-matchers.h.
{
       *os << "size ";
       size_matcher_.DescribeTo(os);
     }
template<typename SizeMatcher > template<typename Container > virtual void testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 2419 of file gmock-matchers.h.
{
       *os << "size ";
       size_matcher_.DescribeTo(os);
     }
template<typename SizeMatcher > template<typename Container > testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::GTEST_DISALLOW_ASSIGN_ (Impl< Container >) private
template<typename SizeMatcher > template<typename Container > testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::GTEST_DISALLOW_ASSIGN_ (Impl< Container >) private
template<typename SizeMatcher > template<typename Container > testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::GTEST_DISALLOW_ASSIGN_ (Impl< Container >) private
template<typename SizeMatcher > template<typename Container > virtual bool testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::MatchAndExplain (Container container, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< Container >.
Definition at line 2428 of file gmock-matchers.h.
References testing::internal::PrintIfNotEmpty(), folly::size(), testing::StringMatchResultListener::str(), and testing::MatchResultListener::stream().
{
       SizeType size = container.size();
       StringMatchResultListener size_listener;
       const bool result = size_matcher_.MatchAndExplain(size, &size_listener);
       *listener
           << "whose size " << size << (result ? " matches" : " doesn't match");
       PrintIfNotEmpty(size_listener.str(), listener->stream());
       return result;
     }
template<typename SizeMatcher > template<typename Container > virtual bool testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::MatchAndExplain (Container container, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< Container >.
Definition at line 2428 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, testing::internal::PrintIfNotEmpty(), folly::size(), and testing::StringMatchResultListener::str().
{
       SizeType size = container.size();
       StringMatchResultListener size_listener;
       const bool result = size_matcher_.MatchAndExplain(size, &size_listener);
       *listener
           << "whose size " << size << (result ? " matches" : " doesn't match");
       PrintIfNotEmpty(size_listener.str(), listener->stream());
       return result;
     }
template<typename SizeMatcher > template<typename Container > virtual bool testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::MatchAndExplain (Container container, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< Container >.
Definition at line 2428 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, testing::internal::PrintIfNotEmpty(), folly::size(), and testing::StringMatchResultListener::str().
{
       SizeType size = container.size();
       StringMatchResultListener size_listener;
       const bool result = size_matcher_.MatchAndExplain(size, &size_listener);
       *listener
           << "whose size " << size << (result ? " matches" : " doesn't match");
       PrintIfNotEmpty(size_listener.str(), listener->stream());
       return result;
     }
Member Data Documentation
template<typename SizeMatcher > template<typename Container > const Matcher< SizeType > testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::size_matcher_ private
Definition at line 2440 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h