proxygen: wangle::SocketPeeker Class Reference
wangle::SocketPeeker Class Reference
#include <SocketPeeker.h>
Classes
class Callback
Public Types
using UniquePtr = std::unique_ptr< SocketPeeker, folly::DelayedDestruction::Destructor >
Public Member Functions
SocketPeeker (folly::AsyncSocket &socket, Callback *callback, size_t numBytes)
~SocketPeeker () override
void start ()
void getReadBuffer (void **bufReturn, size_t *lenReturn) override
void readEOF () noexceptoverride
void readErr (const folly::AsyncSocketException &ex) noexceptoverride
void readDataAvailable (size_t len) noexceptoverride
bool isBufferMovable () noexceptoverride
Public Member Functions inherited from folly::AsyncReader::ReadCallback
virtual ~ReadCallback ()=default
virtual size_t maxBufferSize () const
virtual void readBufferAvailable (std::unique_ptr< IOBuf >) noexcept
Public Member Functions inherited from folly::DelayedDestruction
virtual void destroy ()
bool getDestroyPending () const
Public Member Functions inherited from folly::DelayedDestructionBase
virtual ~DelayedDestructionBase ()=default
Private Attributes
folly::AsyncSocket & socket_
Callback * callback_
size_t read_ {0}
std::vector< uint8_t > peekBytes_
Additional Inherited Members
Protected Member Functions inherited from folly::DelayedDestruction
~DelayedDestruction () override=default
DelayedDestruction ()
Protected Member Functions inherited from folly::DelayedDestructionBase
DelayedDestructionBase ()
uint32_t getDestructorGuardCount () const
Detailed Description
Definition at line 24 of file SocketPeeker.h.
Member Typedef Documentation
using wangle::SocketPeeker::UniquePtr = std::unique_ptr<SocketPeeker, folly::DelayedDestruction::Destructor>
Definition at line 28 of file SocketPeeker.h.
Constructor & Destructor Documentation
wangle::SocketPeeker::SocketPeeker (folly::AsyncSocket & socket, Callback * callback, size_t numBytes) inline
Definition at line 37 of file SocketPeeker.h.
       : socket_(socket), callback_(callback), peekBytes_(numBytes) {}
wangle::SocketPeeker::~SocketPeeker () inline override
Definition at line 40 of file SocketPeeker.h.
References folly::AsyncSocket::getReadCallback(), folly::AsyncSocket::setReadCB(), and socket_.
{
     if (socket_.getReadCallback() == this) {
       socket_.setReadCB(nullptr);
     }
   }
Member Function Documentation
void wangle::SocketPeeker::getReadBuffer (void ** bufReturn, size_t * lenReturn) inline override virtual
When data becomes available, getReadBuffer() will be invoked to get the buffer into which data should be read.
This method allows the ReadCallback to delay buffer allocation until data becomes available. This allows applications to manage large numbers of idle connections, without having to maintain a separate read buffer for each idle connection.
It is possible that in some cases, getReadBuffer() may be called multiple times before readDataAvailable() is invoked. In this case, the data will be written to the buffer returned from the most recent call to readDataAvailable(). If the previous calls to readDataAvailable() returned different buffers, the ReadCallback is responsible for ensuring that they are not leaked.
If getReadBuffer() throws an exception, returns a nullptr buffer, or returns a 0 length, the ReadCallback will be uninstalled and its readError() method will be invoked.
getReadBuffer() is not allowed to change the transport state before it returns. (For example, it should never uninstall the read callback, or set a different read callback.)
Parameters
bufReturn getReadBuffer() should update *bufReturn to contain the address of the read buffer. This parameter will never be nullptr.
lenReturn getReadBuffer() should update *lenReturn to contain the maximum number of bytes that may be written to the read buffer. This parameter will never be nullptr.
Implements folly::AsyncReader::ReadCallback.
Definition at line 57 of file SocketPeeker.h.
References peekBytes_, and read_.
{
     CHECK_LT(read_, peekBytes_.size());
     *bufReturn = reinterpret_cast<void*>(peekBytes_.data() + read_);
     *lenReturn = peekBytes_.size() - read_;
   }
bool wangle::SocketPeeker::isBufferMovable () inline override virtual noexcept
When data becomes available, isBufferMovable() will be invoked to figure out which API will be used, readBufferAvailable() or readDataAvailable(). If isBufferMovable() returns true, that means ReadCallback supports the IOBuf ownership transfer and readBufferAvailable() will be used. Otherwise, not.
By default, isBufferMovable() always return false. If readBufferAvailable() is implemented and to be invoked, You should overwrite isBufferMovable() and return true in the inherited class.
This method allows the AsyncSocket/AsyncSSLSocket do buffer allocation by itself until data becomes available. Compared with the pre/post buffer allocation in getReadBuffer()/readDataAvailabe(), readBufferAvailable() has two advantages. First, this can avoid memcpy. E.g., in AsyncSSLSocket, the decrypted data was copied from the openssl internal buffer to the readbuf buffer. With the buffer ownership transfer, the internal buffer can be directly "moved" to ReadCallback. Second, the memory allocation can be more precise. The reason is AsyncSocket/AsyncSSLSocket can allocate the memory of precise size because they have more context about the available data than ReadCallback. Think about the getReadBuffer() pre-allocate 4072 bytes buffer, but the available data is always 16KB (max OpenSSL record size).
Reimplemented from folly::AsyncReader::ReadCallback.
Definition at line 98 of file SocketPeeker.h.
{
     // Returning false so that we can supply the exact length of the
     // number of bytes we want to read.
     return false;
   }
void wangle::SocketPeeker::readDataAvailable (size_t len) inline override virtual noexcept
readDataAvailable() will be invoked when data has been successfully read into the buffer returned by the last call to getReadBuffer().
The read callback remains installed after readDataAvailable() returns. It must be explicitly uninstalled to stop receiving read events. getReadBuffer() will be called at least once before each call to readDataAvailable(). getReadBuffer() will also be called before any call to readEOF().
Parameters
len The number of bytes placed in the buffer.
Implements folly::AsyncReader::ReadCallback.
Definition at line 82 of file SocketPeeker.h.
References callback_, folly::IOBuf::copyBuffer(), folly::gen::move, peekBytes_, wangle::SocketPeeker::Callback::peekSuccess(), folly::range(), read_, folly::AsyncSocket::setPreReceivedData(), folly::AsyncSocket::setReadCB(), and socket_.
{
     folly::DelayedDestruction::DestructorGuard dg(this);
     read_ += len;
     CHECK_LE(read_, peekBytes_.size());
     if (read_ == peekBytes_.size()) {
       socket_.setPreReceivedData(
           folly::IOBuf::copyBuffer(folly::range(peekBytes_)));
       socket_.setReadCB(nullptr);
       auto callback = callback_;
       callback_ = nullptr;
       callback->peekSuccess(std::move(peekBytes_));
     }
   }
void wangle::SocketPeeker::readEOF () inline override virtual noexcept
readEOF() will be invoked when the transport is closed.
The read callback will be automatically uninstalled immediately before readEOF() is invoked.
Implements folly::AsyncReader::ReadCallback.
Definition at line 63 of file SocketPeeker.h.
References readErr(), and type.
{
     folly::DelayedDestruction::DestructorGuard dg(this);
     auto type =
         folly::AsyncSocketException::AsyncSocketExceptionType::END_OF_FILE;
     readErr(folly::AsyncSocketException(type, "Unexpected EOF"));
   }
void wangle::SocketPeeker::readErr (const folly::AsyncSocketException & ex) inline override virtual noexcept
readError() will be invoked if an error occurs reading from the transport.
The read callback will be automatically uninstalled immediately before readError() is invoked.
Parameters
ex An exception describing the error that occurred.
Implements folly::AsyncReader::ReadCallback.
Definition at line 71 of file SocketPeeker.h.
References callback_, wangle::SocketPeeker::Callback::peekError(), folly::AsyncSocket::setReadCB(), and socket_.
Referenced by readEOF().
{
     folly::DelayedDestruction::DestructorGuard dg(this);
     socket_.setReadCB(nullptr);
     if (callback_) {
       auto callback = callback_;
       callback_ = nullptr;
       callback->peekError(ex);
     }
   }
void wangle::SocketPeeker::start () inline
Definition at line 46 of file SocketPeeker.h.
References callback_, folly::gen::move, peekBytes_, wangle::SocketPeeker::Callback::peekSuccess(), folly::AsyncSocket::setReadCB(), and socket_.
                {
     if (peekBytes_.size() == 0) {
       // No peeking necessary.
       auto callback = callback_;
       callback_ = nullptr;
       callback->peekSuccess(std::move(peekBytes_));
     } else {
       socket_.setReadCB(this);
     }
   }
Member Data Documentation
Callback* wangle::SocketPeeker::callback_ private
Definition at line 106 of file SocketPeeker.h.
Referenced by readDataAvailable(), readErr(), and start().
std::vector<uint8_t> wangle::SocketPeeker::peekBytes_ private
Definition at line 108 of file SocketPeeker.h.
Referenced by getReadBuffer(), readDataAvailable(), and start().
size_t wangle::SocketPeeker::read_ {0} private
Definition at line 107 of file SocketPeeker.h.
Referenced by getReadBuffer(), and readDataAvailable().
folly::AsyncSocket& wangle::SocketPeeker::socket_ private
Definition at line 105 of file SocketPeeker.h.
Referenced by readDataAvailable(), readErr(), start(), and ~SocketPeeker().
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/acceptor/SocketPeeker.h