proxygen: foo::StreamableTemplateInFoo< T > Class Template Reference
foo::StreamableTemplateInFoo< T > Class Template Reference
Public Member Functions
StreamableTemplateInFoo ()
const T & value () const
StreamableTemplateInFoo ()
const T & value () const
StreamableTemplateInFoo ()
const T & value () const
Private Attributes
T value_
Detailed Description
template<typename T>
class foo::StreamableTemplateInFoo< T >
Definition at line 175 of file gtest-printers_test.cc.
Constructor & Destructor Documentation
template<typename T> foo::StreamableTemplateInFoo< T >::StreamableTemplateInFoo () inline
Definition at line 177 of file gtest-printers_test.cc.
 : value_() {}
template<typename T> foo::StreamableTemplateInFoo< T >::StreamableTemplateInFoo () inline
Definition at line 177 of file gtest-printers_test.cc.
 : value_() {}
template<typename T> foo::StreamableTemplateInFoo< T >::StreamableTemplateInFoo () inline
Definition at line 177 of file gtest-printers_test.cc.
 : value_() {}
Member Function Documentation
template<typename T> const T& foo::StreamableTemplateInFoo< T >::value () const inline
Definition at line 179 of file gtest-printers_test.cc.
Referenced by foo::operator<<(), and foo::StreamableTemplateInFoo< T >::value().
 { return value_; }
template<typename T> const T& foo::StreamableTemplateInFoo< T >::value () const inline
Definition at line 179 of file gtest-printers_test.cc.
References EXPECT_EQ, EXPECT_LT, f, testing::internal::FormatForComparisonFailureMessage(), testing::internal::ImplicitCast_(), kAE1, kAE2, kEWP1, kEWP2, kEWPT1, kEWS1, bm::list, map(), operator<<(), testing::gtest_printers_test::Print(), testing::gtest_printers_test::PrintByRef(), testing::PrintToString(), cpp.gmock_class::set, string, T, testing::gtest_printers_test::TEST(), testing::internal::UniversalPrint(), testing::internal::UniversalTersePrint(), value, and foo::StreamableTemplateInFoo< T >::value().
 { return value_; }
template<typename T> const T& foo::StreamableTemplateInFoo< T >::value () const inline
Definition at line 179 of file gtest-printers_test.cc.
References EXPECT_EQ, EXPECT_LT, f, testing::internal::FormatForComparisonFailureMessage(), testing::internal::ImplicitCast_(), kAE1, kAE2, kEWP1, kEWP2, kEWPT1, kEWS1, bm::list, map(), operator<<(), testing::gtest_printers_test::Print(), testing::gtest_printers_test::PrintByRef(), testing::PrintToString(), cpp.gmock_class::set, string, T, testing::gtest_printers_test::TEST(), testing::internal::UniversalPrint(), testing::internal::UniversalTersePrint(), value, and foo::StreamableTemplateInFoo< T >::value().
 { return value_; }
Member Data Documentation
template<typename T> T foo::StreamableTemplateInFoo< T >::value_ private
Definition at line 181 of file gtest-printers_test.cc.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest-printers_test.cc