proxygen: testing::internal::EqHelper< true > Class Template Reference
testing::internal::EqHelper< true > Class Template Reference
#include <gtest.h>
Static Public Member Functions
template<typename T1 , typename T2 >
static AssertionResult Compare (const char *lhs_expression, const char *rhs_expression, const T1 &lhs, const T2 &rhs, typename EnableIf<!is_pointer< T2 >::value >::type *=0)
template<typename T >
static AssertionResult Compare (const char *lhs_expression, const char *rhs_expression, Secret *, T *rhs)
template<typename T1 , typename T2 >
static AssertionResult Compare (const char *lhs_expression, const char *rhs_expression, const T1 &lhs, const T2 &rhs, typename EnableIf<!is_pointer< T2 >::value >::type *=0)
template<typename T >
static AssertionResult Compare (const char *lhs_expression, const char *rhs_expression, Secret *, T *rhs)
template<typename T1 , typename T2 >
static AssertionResult Compare (const char *lhs_expression, const char *rhs_expression, const T1 &lhs, const T2 &rhs, typename EnableIf<!is_pointer< T2 >::value >::type *=0)
template<typename T >
static AssertionResult Compare (const char *lhs_expression, const char *rhs_expression, Secret *, T *rhs)
Detailed Description
template<>
class testing::internal::EqHelper< true >
Definition at line 1441 of file gtest.h.
Member Function Documentation
template<typename T1 , typename T2 > static AssertionResult testing::internal::EqHelper< true >::Compare (const char * lhs_expression, const char * rhs_expression, const T1 & lhs, const T2 & rhs, typename EnableIf<!is_pointer< T2 >::value >::type * = 0) inline static
Definition at line 1448 of file gtest.h.
References testing::internal::CmpHelperEQ().
{
     return CmpHelperEQ(lhs_expression, rhs_expression, lhs, rhs);
   }
template<typename T1 , typename T2 > static AssertionResult testing::internal::EqHelper< true >::Compare (const char * lhs_expression, const char * rhs_expression, const T1 & lhs, const T2 & rhs, typename EnableIf<!is_pointer< T2 >::value >::type * = 0) inline static
Definition at line 1448 of file gtest.h.
References testing::internal::CmpHelperEQ().
{
     return CmpHelperEQ(lhs_expression, rhs_expression, lhs, rhs);
   }
template<typename T1 , typename T2 > static AssertionResult testing::internal::EqHelper< true >::Compare (const char * lhs_expression, const char * rhs_expression, const T1 & lhs, const T2 & rhs, typename EnableIf<!is_pointer< T2 >::value >::type * = 0) inline static
Definition at line 1448 of file gtest.h.
References testing::internal::CmpHelperEQ().
{
     return CmpHelperEQ(lhs_expression, rhs_expression, lhs, rhs);
   }
template<typename T > static AssertionResult testing::internal::EqHelper< true >::Compare (const char * lhs_expression, const char * rhs_expression, Secret * , T * rhs) inline static
Definition at line 1465 of file gtest.h.
References testing::AssertionFailure(), testing::internal::CmpHelperEQ(), testing::internal::CmpHelperOpFailure(), and testing::internal::FormatForComparisonFailureMessage().
               {
     // We already know that 'lhs' is a null pointer.
     return CmpHelperEQ(lhs_expression, rhs_expression,
                        static_cast<T*>(NULL), rhs);
   }
template<typename T > static AssertionResult testing::internal::EqHelper< true >::Compare (const char * lhs_expression, const char * rhs_expression, Secret * , T * rhs) inline static
Definition at line 1465 of file gtest.h.
References testing::internal::CmpHelperEQ().
               {
     // We already know that 'lhs' is a null pointer.
     return CmpHelperEQ(lhs_expression, rhs_expression,
                        static_cast<T*>(NULL), rhs);
   }
template<typename T > static AssertionResult testing::internal::EqHelper< true >::Compare (const char * lhs_expression, const char * rhs_expression, Secret * , T * rhs) inline static
Definition at line 1465 of file gtest.h.
References testing::AssertionFailure(), testing::internal::CmpHelperEQ(), testing::internal::CmpHelperOpFailure(), and testing::internal::FormatForComparisonFailureMessage().
               {
     // We already know that 'lhs' is a null pointer.
     return CmpHelperEQ(lhs_expression, rhs_expression,
                        static_cast<T*>(NULL), rhs);
   }
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/gtest.h