proxygen: testing::internal::PairMatcher< FirstMatcher, SecondMatcher > Class Template Reference
testing::internal::PairMatcher< FirstMatcher, SecondMatcher > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
PairMatcher (FirstMatcher first_matcher, SecondMatcher second_matcher)
template<typename PairType >
operator Matcher< PairType > () const
PairMatcher (FirstMatcher first_matcher, SecondMatcher second_matcher)
template<typename PairType >
operator Matcher< PairType > () const
PairMatcher (FirstMatcher first_matcher, SecondMatcher second_matcher)
template<typename PairType >
operator Matcher< PairType > () const
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (PairMatcher)
GTEST_DISALLOW_ASSIGN_ (PairMatcher)
GTEST_DISALLOW_ASSIGN_ (PairMatcher)
Private Attributes
const FirstMatcher first_matcher_
const SecondMatcher second_matcher_
Detailed Description
template<typename FirstMatcher, typename SecondMatcher>
class testing::internal::PairMatcher< FirstMatcher, SecondMatcher >
Definition at line 3087 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename FirstMatcher, typename SecondMatcher> testing::internal::PairMatcher< FirstMatcher, SecondMatcher >::PairMatcher (FirstMatcher first_matcher, SecondMatcher second_matcher) inline
Definition at line 3089 of file gmock-matchers.h.
       : first_matcher_(first_matcher), second_matcher_(second_matcher) {}
template<typename FirstMatcher, typename SecondMatcher> testing::internal::PairMatcher< FirstMatcher, SecondMatcher >::PairMatcher (FirstMatcher first_matcher, SecondMatcher second_matcher) inline
Definition at line 3089 of file gmock-matchers.h.
       : first_matcher_(first_matcher), second_matcher_(second_matcher) {}
template<typename FirstMatcher, typename SecondMatcher> testing::internal::PairMatcher< FirstMatcher, SecondMatcher >::PairMatcher (FirstMatcher first_matcher, SecondMatcher second_matcher) inline
Definition at line 3089 of file gmock-matchers.h.
       : first_matcher_(first_matcher), second_matcher_(second_matcher) {}
Member Function Documentation
template<typename FirstMatcher, typename SecondMatcher> testing::internal::PairMatcher< FirstMatcher, SecondMatcher >::GTEST_DISALLOW_ASSIGN_ (PairMatcher< FirstMatcher, SecondMatcher >) private
template<typename FirstMatcher, typename SecondMatcher> testing::internal::PairMatcher< FirstMatcher, SecondMatcher >::GTEST_DISALLOW_ASSIGN_ (PairMatcher< FirstMatcher, SecondMatcher >) private
template<typename FirstMatcher, typename SecondMatcher> testing::internal::PairMatcher< FirstMatcher, SecondMatcher >::GTEST_DISALLOW_ASSIGN_ (PairMatcher< FirstMatcher, SecondMatcher >) private
template<typename FirstMatcher, typename SecondMatcher> template<typename PairType > testing::internal::PairMatcher< FirstMatcher, SecondMatcher >::operator Matcher< PairType > () const inline
Definition at line 3093 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(
         new PairMatcherImpl<PairType>(
             first_matcher_, second_matcher_));
   }
template<typename FirstMatcher, typename SecondMatcher> template<typename PairType > testing::internal::PairMatcher< FirstMatcher, SecondMatcher >::operator Matcher< PairType > () const inline
Definition at line 3093 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, GTEST_REMOVE_REFERENCE_AND_CONST_, and testing::MakeMatcher().
{
     return MakeMatcher(
         new PairMatcherImpl<PairType>(
             first_matcher_, second_matcher_));
   }
template<typename FirstMatcher, typename SecondMatcher> template<typename PairType > testing::internal::PairMatcher< FirstMatcher, SecondMatcher >::operator Matcher< PairType > () const inline
Definition at line 3093 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, GTEST_REMOVE_REFERENCE_AND_CONST_, and testing::MakeMatcher().
{
     return MakeMatcher(
         new PairMatcherImpl<PairType>(
             first_matcher_, second_matcher_));
   }
Member Data Documentation
template<typename FirstMatcher, typename SecondMatcher> const FirstMatcher testing::internal::PairMatcher< FirstMatcher, SecondMatcher >::first_matcher_ private
Definition at line 3100 of file gmock-matchers.h.
template<typename FirstMatcher, typename SecondMatcher> const SecondMatcher testing::internal::PairMatcher< FirstMatcher, SecondMatcher >::second_matcher_ private
Definition at line 3101 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h