proxygen: testing::internal::AssertHelper Class Reference
testing::internal::AssertHelper Class Reference
#include <gtest.h>
Classes
struct AssertHelperData
Public Member Functions
AssertHelper (TestPartResult::Type type, const char *file, int line, const char *message)
~AssertHelper ()
void operator= (const Message &message) const
AssertHelper (TestPartResult::Type type, const char *file, int line, const char *message)
~AssertHelper ()
void operator= (const Message &message) const
AssertHelper (TestPartResult::Type type, const char *file, int line, const char *message)
~AssertHelper ()
void operator= (const Message &message) const
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (AssertHelper)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (AssertHelper)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (AssertHelper)
Private Attributes
AssertHelperData *const data_
Detailed Description
Definition at line 1668 of file gtest.h.
Constructor & Destructor Documentation
testing::internal::AssertHelper::AssertHelper (TestPartResult::Type type, const char * file, int line, const char * message)
Definition at line 361 of file gtest.cc.
Referenced by testing::internal::ShouldRunTestCase().
     : data_(new AssertHelperData(type, file, line, message)) {
 }
testing::internal::AssertHelper::~AssertHelper ()
Definition at line 368 of file gtest.cc.
References data_.
Referenced by testing::internal::ShouldRunTestCase().
{
   delete data_;
 }
testing::internal::AssertHelper::AssertHelper (TestPartResult::Type type, const char * file, int line, const char * message)
testing::internal::AssertHelper::~AssertHelper ()
testing::internal::AssertHelper::AssertHelper (TestPartResult::Type type, const char * file, int line, const char * message)
testing::internal::AssertHelper::~AssertHelper ()
Member Function Documentation
testing::internal::AssertHelper::GTEST_DISALLOW_COPY_AND_ASSIGN_ (AssertHelper) private
testing::internal::AssertHelper::GTEST_DISALLOW_COPY_AND_ASSIGN_ (AssertHelper) private
testing::internal::AssertHelper::GTEST_DISALLOW_COPY_AND_ASSIGN_ (AssertHelper) private
void testing::internal::AssertHelper::operator= (const Message & message) const
Definition at line 373 of file gtest.cc.
References testing::internal::AppendUserMessage(), testing::internal::UnitTestImpl::CurrentOsStackTraceExceptTop(), data_, testing::internal::AssertHelper::AssertHelperData::file, testing::UnitTest::GetInstance(), GTEST_API_, testing::internal::GTEST_DEFINE_STATIC_MUTEX_(), testing::UnitTest::impl(), testing::internal::AssertHelper::AssertHelperData::line, testing::internal::AssertHelper::AssertHelperData::message, and testing::internal::AssertHelper::AssertHelperData::type.
Referenced by testing::internal::ShouldRunTestCase().
{
   UnitTest::GetInstance()->
     AddTestPartResult(data_->type, data_->file, data_->line,
                       AppendUserMessage(data_->message, message),
                       UnitTest::GetInstance()->impl()
                       ->CurrentOsStackTraceExceptTop(1)
                       // Skips the stack frame for this function itself.
                       );  // NOLINT
 }
void testing::internal::AssertHelper::operator= (const Message & message) const
void testing::internal::AssertHelper::operator= (const Message & message) const
Member Data Documentation
AssertHelperData *const testing::internal::AssertHelper::data_ private
Definition at line 1702 of file gtest.h.
Referenced by operator=(), and ~AssertHelper().
The documentation for this class was generated from the following files:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/gtest.h
proxygen/fizz/build_/gtest/src/gtest/googletest/src/gtest.cc