proxygen: folly::PriorityMPMCQueue< T, Atom, Dynamic > Class Template Reference
folly::PriorityMPMCQueue< T, Atom, Dynamic > Class Template Reference
#include <PriorityMPMCQueue.h>
Public Member Functions
PriorityMPMCQueue (size_t numPriorities, size_t capacity)
size_t getNumPriorities ()
bool write (T &&item)
bool writeWithPriority (T &&item, size_t priority)
bool writeWithPriority (T &&item, size_t priority, std::chrono::milliseconds timeout)
bool read (T &item)
bool readWithPriority (T &item, size_t priority)
size_t size () const
size_t sizeGuess () const
bool isEmpty () const
Returns true if there are no items available for dequeue.
Private Attributes
std::vector< folly::MPMCQueue< T, Atom, Dynamic > > queues_
Detailed Description
template<typename T, template< typename > class Atom = std::atomic, bool Dynamic = false>
class folly::PriorityMPMCQueue< T, Atom, Dynamic >
PriorityMPMCQueue is a thin wrapper on MPMCQueue, providing priorities by managing multiple underlying MPMCQueues. As of now, this does not implement a blocking interface. For the purposes of this class, lower number is higher priority
Definition at line 35 of file PriorityMPMCQueue.h.
Constructor & Destructor Documentation
template<typename T, template< typename > class Atom = std::atomic, bool Dynamic = false> folly::PriorityMPMCQueue< T, Atom, Dynamic >::PriorityMPMCQueue (size_t numPriorities, size_t capacity) inline
Definition at line 37 of file PriorityMPMCQueue.h.
References i, and folly::PriorityMPMCQueue< T, Atom, Dynamic >::queues_.
{
     CHECK_GT(numPriorities, 0);
     queues_.reserve(numPriorities);
     for (size_t i = 0; i < numPriorities; i++) {
       queues_.emplace_back(capacity);
     }
   }
Member Function Documentation
template<typename T, template< typename > class Atom = std::atomic, bool Dynamic = false> size_t folly::PriorityMPMCQueue< T, Atom, Dynamic >::getNumPriorities () inline
Definition at line 45 of file PriorityMPMCQueue.h.
References folly::PriorityMPMCQueue< T, Atom, Dynamic >::queues_.
Referenced by TEST(), folly::PriorityMPMCQueue< T, Atom, Dynamic >::write(), and folly::PriorityMPMCQueue< T, Atom, Dynamic >::writeWithPriority().
{
     return queues_.size();
   }
template<typename T, template< typename > class Atom = std::atomic, bool Dynamic = false> bool folly::PriorityMPMCQueue< T, Atom, Dynamic >::isEmpty () const inline
Returns true if there are no items available for dequeue.
Definition at line 106 of file PriorityMPMCQueue.h.
References folly::PriorityMPMCQueue< T, Atom, Dynamic >::size().
Referenced by TEST().
{
     return size() == 0;
   }
template<typename T, template< typename > class Atom = std::atomic, bool Dynamic = false> bool folly::PriorityMPMCQueue< T, Atom, Dynamic >::read (T & item) inline
Definition at line 70 of file PriorityMPMCQueue.h.
References folly::PriorityMPMCQueue< T, Atom, Dynamic >::queues_.
Referenced by TEST().
                      {
     for (auto& q : queues_) {
       if (q.readIfNotEmpty(item)) {
         return true;
       }
     }
     return false;
   }
template<typename T, template< typename > class Atom = std::atomic, bool Dynamic = false> bool folly::PriorityMPMCQueue< T, Atom, Dynamic >::readWithPriority (T & item, size_t priority) inline
Definition at line 79 of file PriorityMPMCQueue.h.
References folly::PriorityMPMCQueue< T, Atom, Dynamic >::queues_.
Referenced by TEST().
{
     return queues_[priority].readIfNotEmpty(item);
   }
template<typename T, template< typename > class Atom = std::atomic, bool Dynamic = false> size_t folly::PriorityMPMCQueue< T, Atom, Dynamic >::size () const inline
Definition at line 83 of file PriorityMPMCQueue.h.
References folly::PriorityMPMCQueue< T, Atom, Dynamic >::queues_.
Referenced by folly::PriorityMPMCQueue< T, Atom, Dynamic >::isEmpty(), and TEST().
                       {
     size_t total_size = 0;
     for (auto& q : queues_) {
       // MPMCQueue can have a negative size if there are pending readers.
       // Since we don't expose a blocking interface this shouldn't happen,
       // But just in case we put a floor at 0
       total_size += std::max<ssize_t>(0, q.size());
     }
     return total_size;
   }
template<typename T, template< typename > class Atom = std::atomic, bool Dynamic = false> size_t folly::PriorityMPMCQueue< T, Atom, Dynamic >::sizeGuess () const inline
Definition at line 94 of file PriorityMPMCQueue.h.
References folly::PriorityMPMCQueue< T, Atom, Dynamic >::queues_.
Referenced by TEST().
{
     size_t total_size = 0;
     for (auto& q : queues_) {
       // MPMCQueue can have a negative size if there are pending readers.
       // Since we don't expose a blocking interface this shouldn't happen,
       // But just in case we put a floor at 0
       total_size += std::max<ssize_t>(0, q.sizeGuess());
     }
     return total_size;
   }
template<typename T, template< typename > class Atom = std::atomic, bool Dynamic = false> bool folly::PriorityMPMCQueue< T, Atom, Dynamic >::write (T && item) inline
Definition at line 50 of file PriorityMPMCQueue.h.
References folly::PriorityMPMCQueue< T, Atom, Dynamic >::getNumPriorities(), folly::gen::move, and folly::PriorityMPMCQueue< T, Atom, Dynamic >::writeWithPriority().
Referenced by TEST().
{
     return writeWithPriority(std::move(item), getNumPriorities() / 2);
   }
template<typename T, template< typename > class Atom = std::atomic, bool Dynamic = false> bool folly::PriorityMPMCQueue< T, Atom, Dynamic >::writeWithPriority (T && item, size_t priority) inline
Definition at line 54 of file PriorityMPMCQueue.h.
References folly::PriorityMPMCQueue< T, Atom, Dynamic >::getNumPriorities(), min, folly::gen::move, and folly::PriorityMPMCQueue< T, Atom, Dynamic >::queues_.
Referenced by TEST(), and folly::PriorityMPMCQueue< T, Atom, Dynamic >::write().
{
     size_t queue = std::min(getNumPriorities() - 1, priority);
     CHECK_LT(queue, queues_.size());
     return queues_.at(queue).write(std::move(item));
   }
template<typename T, template< typename > class Atom = std::atomic, bool Dynamic = false> bool folly::PriorityMPMCQueue< T, Atom, Dynamic >::writeWithPriority (T && item, size_t priority, std::chrono::milliseconds timeout) inline
Definition at line 60 of file PriorityMPMCQueue.h.
References folly::PriorityMPMCQueue< T, Atom, Dynamic >::getNumPriorities(), min, folly::gen::move, now(), and folly::PriorityMPMCQueue< T, Atom, Dynamic >::queues_.
{
     size_t queue = std::min(getNumPriorities() - 1, priority);
     CHECK_LT(queue, queues_.size());
     return queues_.at(queue).tryWriteUntil(
         std::chrono::steady_clock::now() + timeout, std::move(item));
   }
Member Data Documentation
template<typename T, template< typename > class Atom = std::atomic, bool Dynamic = false> std::vector<folly::MPMCQueue<T, Atom, Dynamic> > folly::PriorityMPMCQueue< T, Atom, Dynamic >::queues_ private
Definition at line 111 of file PriorityMPMCQueue.h.
Referenced by folly::PriorityMPMCQueue< T, Atom, Dynamic >::getNumPriorities(), folly::PriorityMPMCQueue< T, Atom, Dynamic >::PriorityMPMCQueue(), folly::PriorityMPMCQueue< T, Atom, Dynamic >::read(), folly::PriorityMPMCQueue< T, Atom, Dynamic >::readWithPriority(), folly::PriorityMPMCQueue< T, Atom, Dynamic >::size(), folly::PriorityMPMCQueue< T, Atom, Dynamic >::sizeGuess(), and folly::PriorityMPMCQueue< T, Atom, Dynamic >::writeWithPriority().
The documentation for this class was generated from the following file:
proxygen/folly/folly/PriorityMPMCQueue.h