proxygen: fizz::server::test::AeadTicketCipherTest Class Reference
fizz::server::test::AeadTicketCipherTest Class Reference
Public Member Functions
~AeadTicketCipherTest () override=default
void SetUp () override
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Protected Member Functions
void setTicketSecrets (std::string pskContext="")
void expectDecode ()
void checkUnsetEncrypt ()
Protected Member Functions inherited from testing::Test
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Protected Attributes
TestAeadTicketCipher cipher_
MockTicketCodecInstance codec_
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Detailed Description
Definition at line 79 of file AeadTicketCipherTest.cpp.
Constructor & Destructor Documentation
fizz::server::test::AeadTicketCipherTest::~AeadTicketCipherTest () override default
Member Function Documentation
void fizz::server::test::AeadTicketCipherTest::checkUnsetEncrypt () inline protected
Definition at line 112 of file AeadTicketCipherTest.cpp.
References fizz::server::AeadTicketCipher< AeadType, CodecType, HkdfType >::encrypt(), EXPECT_FALSE, and folly::gen::move.
{
     ResumptionState state;
     EXPECT_FALSE(cipher_.encrypt(std::move(state)).get().hasValue());
   }
void fizz::server::test::AeadTicketCipherTest::expectDecode () inline protected
Definition at line 102 of file AeadTicketCipherTest.cpp.
References testing::_, folly::IOBuf::copyBuffer(), EXPECT_CALL, EXPECT_TRUE, and testing::Invoke().
                       {
     EXPECT_CALL(codec_, _decode(_, _))
         .WillOnce(
             Invoke([](Buf& encoded, const FizzServerContext* /*context*/) {
               EXPECT_TRUE(
                   IOBufEqualTo()(encoded, IOBuf::copyBuffer("encodedticket")));
               return ResumptionState();
             }));
   }
void fizz::server::test::AeadTicketCipherTest::setTicketSecrets (std::string pskContext = "") inline protected
Definition at line 90 of file AeadTicketCipherTest.cpp.
References EXPECT_TRUE, folly::gen::move, fizz::server::AeadTicketCipher< AeadType, CodecType, HkdfType >::setTicketSecrets(), ticketSecret1, ticketSecret2, and fizz::test::toIOBuf().
{
     if (!pskContext.empty()) {
       cipher_ = TestAeadTicketCipher(pskContext);
     } else {
       cipher_ = TestAeadTicketCipher();
     }
     auto s1 = toIOBuf(ticketSecret1);
     auto s2 = toIOBuf(ticketSecret2);
     std::vector<ByteRange> ticketSecrets{{s1->coalesce(), s2->coalesce()}};
     EXPECT_TRUE(cipher_.setTicketSecrets(std::move(ticketSecrets)));
   }
void fizz::server::test::AeadTicketCipherTest::SetUp () inline override virtual
Reimplemented from testing::Test.
Definition at line 82 of file AeadTicketCipherTest.cpp.
References codec_.
{
     MockTicketCodec::instance = &codec_;
   }
Member Data Documentation
TestAeadTicketCipher fizz::server::test::AeadTicketCipherTest::cipher_ protected
Definition at line 87 of file AeadTicketCipherTest.cpp.
MockTicketCodecInstance fizz::server::test::AeadTicketCipherTest::codec_ protected
Definition at line 88 of file AeadTicketCipherTest.cpp.
The documentation for this class was generated from the following file:
proxygen/fizz/fizz/server/test/AeadTicketCipherTest.cpp