proxygen: testing::internal::PropertyMatcher< Class, PropertyType > Class Template Reference
testing::internal::PropertyMatcher< Class, PropertyType > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
typedef GTEST_REFERENCE_TO_CONST_ (PropertyType) RefToConstProperty
PropertyMatcher (PropertyType(Class::*property)() const, const Matcher< RefToConstProperty > &matcher)
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
template<typename T >
bool MatchAndExplain (const T &value, MatchResultListener *listener) const
typedef GTEST_REFERENCE_TO_CONST_ (PropertyType) RefToConstProperty
PropertyMatcher (PropertyType(Class::*property)() const, const Matcher< RefToConstProperty > &matcher)
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
template<typename T >
bool MatchAndExplain (const T &value, MatchResultListener *listener) const
typedef GTEST_REFERENCE_TO_CONST_ (PropertyType) RefToConstProperty
PropertyMatcher (PropertyType(Class::*property)() const, const Matcher< RefToConstProperty > &matcher)
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
template<typename T >
bool MatchAndExplain (const T &value, MatchResultListener *listener) const
Private Member Functions
bool MatchAndExplainImpl (false_type, const Class &obj, MatchResultListener *listener) const
bool MatchAndExplainImpl (true_type, const Class *p, MatchResultListener *listener) const
GTEST_DISALLOW_ASSIGN_ (PropertyMatcher)
bool MatchAndExplainImpl (false_type, const Class &obj, MatchResultListener *listener) const
bool MatchAndExplainImpl (true_type, const Class *p, MatchResultListener *listener) const
GTEST_DISALLOW_ASSIGN_ (PropertyMatcher)
bool MatchAndExplainImpl (false_type, const Class &obj, MatchResultListener *listener) const
bool MatchAndExplainImpl (true_type, const Class *p, MatchResultListener *listener) const
GTEST_DISALLOW_ASSIGN_ (PropertyMatcher)
Private Attributes
PropertyType(Class::* property_)() const
const Matcher< RefToConstProperty > matcher_
Detailed Description
template<typename Class, typename PropertyType>
class testing::internal::PropertyMatcher< Class, PropertyType >
Definition at line 2236 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename Class , typename PropertyType > testing::internal::PropertyMatcher< Class, PropertyType >::PropertyMatcher (PropertyType(Class::*)() const property, const Matcher< RefToConstProperty > & matcher) inline
Definition at line 2244 of file gmock-matchers.h.
       : property_(property), matcher_(matcher) {}
template<typename Class , typename PropertyType > testing::internal::PropertyMatcher< Class, PropertyType >::PropertyMatcher (PropertyType(Class::*)() const property, const Matcher< RefToConstProperty > & matcher) inline
Definition at line 2244 of file gmock-matchers.h.
       : property_(property), matcher_(matcher) {}
template<typename Class , typename PropertyType > testing::internal::PropertyMatcher< Class, PropertyType >::PropertyMatcher (PropertyType(Class::*)() const property, const Matcher< RefToConstProperty > & matcher) inline
Definition at line 2244 of file gmock-matchers.h.
       : property_(property), matcher_(matcher) {}
Member Function Documentation
template<typename Class , typename PropertyType > void testing::internal::PropertyMatcher< Class, PropertyType >::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 2253 of file gmock-matchers.h.
{
     *os << "is an object whose given property ";
     matcher_.DescribeNegationTo(os);
   }
template<typename Class , typename PropertyType > void testing::internal::PropertyMatcher< Class, PropertyType >::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 2253 of file gmock-matchers.h.
{
     *os << "is an object whose given property ";
     matcher_.DescribeNegationTo(os);
   }
template<typename Class , typename PropertyType > void testing::internal::PropertyMatcher< Class, PropertyType >::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 2253 of file gmock-matchers.h.
{
     *os << "is an object whose given property ";
     matcher_.DescribeNegationTo(os);
   }
template<typename Class , typename PropertyType > void testing::internal::PropertyMatcher< Class, PropertyType >::DescribeTo (::std::ostream * os) const inline
Definition at line 2248 of file gmock-matchers.h.
{
     *os << "is an object whose given property ";
     matcher_.DescribeTo(os);
   }
template<typename Class , typename PropertyType > void testing::internal::PropertyMatcher< Class, PropertyType >::DescribeTo (::std::ostream * os) const inline
Definition at line 2248 of file gmock-matchers.h.
{
     *os << "is an object whose given property ";
     matcher_.DescribeTo(os);
   }
template<typename Class , typename PropertyType > void testing::internal::PropertyMatcher< Class, PropertyType >::DescribeTo (::std::ostream * os) const inline
Definition at line 2248 of file gmock-matchers.h.
{
     *os << "is an object whose given property ";
     matcher_.DescribeTo(os);
   }
template<typename Class , typename PropertyType > testing::internal::PropertyMatcher< Class, PropertyType >::GTEST_DISALLOW_ASSIGN_ (PropertyMatcher< Class, PropertyType >) private
template<typename Class , typename PropertyType > testing::internal::PropertyMatcher< Class, PropertyType >::GTEST_DISALLOW_ASSIGN_ (PropertyMatcher< Class, PropertyType >) private
template<typename Class , typename PropertyType > testing::internal::PropertyMatcher< Class, PropertyType >::GTEST_DISALLOW_ASSIGN_ (PropertyMatcher< Class, PropertyType >) private
template<typename Class , typename PropertyType > typedef testing::internal::PropertyMatcher< Class, PropertyType >::GTEST_REFERENCE_TO_CONST_ (PropertyType)
template<typename Class , typename PropertyType > typedef testing::internal::PropertyMatcher< Class, PropertyType >::GTEST_REFERENCE_TO_CONST_ (PropertyType)
template<typename Class , typename PropertyType > typedef testing::internal::PropertyMatcher< Class, PropertyType >::GTEST_REFERENCE_TO_CONST_ (PropertyType)
template<typename Class , typename PropertyType > template<typename T > bool testing::internal::PropertyMatcher< Class, PropertyType >::MatchAndExplain (const T & value, MatchResultListener * listener) const inline
Definition at line 2259 of file gmock-matchers.h.
References GTEST_REMOVE_CONST_, T, and type.
{
     return MatchAndExplainImpl(
         typename ::testing::internal::
             is_pointer<GTEST_REMOVE_CONST_(T)>::type(),
         value, listener);
   }
template<typename Class , typename PropertyType > template<typename T > bool testing::internal::PropertyMatcher< Class, PropertyType >::MatchAndExplain (const T & value, MatchResultListener * listener) const inline
Definition at line 2259 of file gmock-matchers.h.
References GTEST_REMOVE_CONST_, and type.
{
     return MatchAndExplainImpl(
         typename ::testing::internal::
             is_pointer<GTEST_REMOVE_CONST_(T)>::type(),
         value, listener);
   }
template<typename Class , typename PropertyType > template<typename T > bool testing::internal::PropertyMatcher< Class, PropertyType >::MatchAndExplain (const T & value, MatchResultListener * listener) const inline
Definition at line 2259 of file gmock-matchers.h.
References GTEST_REMOVE_CONST_, and type.
{
     return MatchAndExplainImpl(
         typename ::testing::internal::
             is_pointer<GTEST_REMOVE_CONST_(T)>::type(),
         value, listener);
   }
template<typename Class , typename PropertyType > bool testing::internal::PropertyMatcher< Class, PropertyType >::MatchAndExplainImpl (false_type , const Class & obj, MatchResultListener * listener) const inline private
Definition at line 2270 of file gmock-matchers.h.
References testing::internal::posix::Abort(), and testing::internal::MatchPrintAndExplain().
{
     *listener << "whose given property is ";
     // Cannot pass the return value (for example, int) to MatchPrintAndExplain,
     // which takes a non-const reference as argument.
 #if defined(_PREFAST_ ) && _MSC_VER == 1800
     // Workaround bug in VC++ 2013's /analyze parser.
     // https://connect.microsoft.com/VisualStudio/feedback/details/1106363/internal-compiler-error-with-analyze-due-to-failure-to-infer-move
     posix::Abort();  // To make sure it is never run.
     return false;
 #else
     RefToConstProperty result = (obj.*property_)();
     return MatchPrintAndExplain(result, matcher_, listener);
 #endif
   }
template<typename Class , typename PropertyType > bool testing::internal::PropertyMatcher< Class, PropertyType >::MatchAndExplainImpl (false_type , const Class & obj, MatchResultListener * listener) const inline private
Definition at line 2270 of file gmock-matchers.h.
References testing::internal::posix::Abort(), and testing::internal::MatchPrintAndExplain().
{
     *listener << "whose given property is ";
     // Cannot pass the return value (for example, int) to MatchPrintAndExplain,
     // which takes a non-const reference as argument.
 #if defined(_PREFAST_ ) && _MSC_VER == 1800
     // Workaround bug in VC++ 2013's /analyze parser.
     // https://connect.microsoft.com/VisualStudio/feedback/details/1106363/internal-compiler-error-with-analyze-due-to-failure-to-infer-move
     posix::Abort();  // To make sure it is never run.
     return false;
 #else
     RefToConstProperty result = (obj.*property_)();
     return MatchPrintAndExplain(result, matcher_, listener);
 #endif
   }
template<typename Class , typename PropertyType > bool testing::internal::PropertyMatcher< Class, PropertyType >::MatchAndExplainImpl (false_type , const Class & obj, MatchResultListener * listener) const inline private
Definition at line 2270 of file gmock-matchers.h.
References testing::internal::posix::Abort(), and testing::internal::MatchPrintAndExplain().
{
     *listener << "whose given property is ";
     // Cannot pass the return value (for example, int) to MatchPrintAndExplain,
     // which takes a non-const reference as argument.
 #if defined(_PREFAST_ ) && _MSC_VER == 1800
     // Workaround bug in VC++ 2013's /analyze parser.
     // https://connect.microsoft.com/VisualStudio/feedback/details/1106363/internal-compiler-error-with-analyze-due-to-failure-to-infer-move
     posix::Abort();  // To make sure it is never run.
     return false;
 #else
     RefToConstProperty result = (obj.*property_)();
     return MatchPrintAndExplain(result, matcher_, listener);
 #endif
   }
template<typename Class , typename PropertyType > bool testing::internal::PropertyMatcher< Class, PropertyType >::MatchAndExplainImpl (true_type , const Class * p, MatchResultListener * listener) const inline private
Definition at line 2286 of file gmock-matchers.h.
{
     if (p == NULL)
       return false;
     *listener << "which points to an object ";
     // Since *p has a property method, it must be a class/struct/union
     // type and thus cannot be a pointer.  Therefore we pass
     // false_type() as the first argument.
     return MatchAndExplainImpl(false_type(), *p, listener);
   }
template<typename Class , typename PropertyType > bool testing::internal::PropertyMatcher< Class, PropertyType >::MatchAndExplainImpl (true_type , const Class * p, MatchResultListener * listener) const inline private
Definition at line 2286 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_.
{
     if (p == NULL)
       return false;
     *listener << "which points to an object ";
     // Since *p has a property method, it must be a class/struct/union
     // type and thus cannot be a pointer.  Therefore we pass
     // false_type() as the first argument.
     return MatchAndExplainImpl(false_type(), *p, listener);
   }
template<typename Class , typename PropertyType > bool testing::internal::PropertyMatcher< Class, PropertyType >::MatchAndExplainImpl (true_type , const Class * p, MatchResultListener * listener) const inline private
Definition at line 2286 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_.
{
     if (p == NULL)
       return false;
     *listener << "which points to an object ";
     // Since *p has a property method, it must be a class/struct/union
     // type and thus cannot be a pointer.  Therefore we pass
     // false_type() as the first argument.
     return MatchAndExplainImpl(false_type(), *p, listener);
   }
Member Data Documentation
template<typename Class , typename PropertyType > const Matcher< RefToConstProperty > testing::internal::PropertyMatcher< Class, PropertyType >::matcher_ private
Definition at line 2299 of file gmock-matchers.h.
template<typename Class , typename PropertyType > PropertyType(Class::* testing::internal::PropertyMatcher< Class, PropertyType >::property_)() const private
Definition at line 2298 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h