proxygen: testing::gmock_matchers_test::ConstPropagatingPtr< T > Class Template Reference
testing::gmock_matchers_test::ConstPropagatingPtr< T > Class Template Reference
Public Types
typedef T element_type
typedef T element_type
typedef T element_type
Public Member Functions
ConstPropagatingPtr ()
ConstPropagatingPtr (T *t)
ConstPropagatingPtr (const ConstPropagatingPtr &other)
T * get ()
T & operator* ()
const T * get () const
const T & operator* () const
ConstPropagatingPtr ()
ConstPropagatingPtr (T *t)
ConstPropagatingPtr (const ConstPropagatingPtr &other)
T * get ()
T & operator* ()
const T * get () const
const T & operator* () const
ConstPropagatingPtr ()
ConstPropagatingPtr (T *t)
ConstPropagatingPtr (const ConstPropagatingPtr &other)
T * get ()
T & operator* ()
const T * get () const
const T & operator* () const
Private Attributes
T * val_
Detailed Description
template<typename T>
class testing::gmock_matchers_test::ConstPropagatingPtr< T >
Definition at line 3286 of file gmock-matchers_test.cc.
Member Typedef Documentation
template<typename T> typedef T testing::gmock_matchers_test::ConstPropagatingPtr< T >::element_type
Definition at line 3288 of file gmock-matchers_test.cc.
template<typename T> typedef T testing::gmock_matchers_test::ConstPropagatingPtr< T >::element_type
Definition at line 3288 of file gmock-matchers_test.cc.
template<typename T> typedef T testing::gmock_matchers_test::ConstPropagatingPtr< T >::element_type
Definition at line 3288 of file gmock-matchers_test.cc.
Constructor & Destructor Documentation
template<typename T> testing::gmock_matchers_test::ConstPropagatingPtr< T >::ConstPropagatingPtr () inline
Definition at line 3290 of file gmock-matchers_test.cc.
 : val_() {}
template<typename T> testing::gmock_matchers_test::ConstPropagatingPtr< T >::ConstPropagatingPtr (T * t) inline explicit
Definition at line 3291 of file gmock-matchers_test.cc.
 : val_(t) {}
template<typename T> testing::gmock_matchers_test::ConstPropagatingPtr< T >::ConstPropagatingPtr (const ConstPropagatingPtr< T > & other) inline
Definition at line 3292 of file gmock-matchers_test.cc.
 : val_(other.val_) {}
template<typename T> testing::gmock_matchers_test::ConstPropagatingPtr< T >::ConstPropagatingPtr () inline
Definition at line 3290 of file gmock-matchers_test.cc.
 : val_() {}
template<typename T> testing::gmock_matchers_test::ConstPropagatingPtr< T >::ConstPropagatingPtr (T * t) inline explicit
Definition at line 3291 of file gmock-matchers_test.cc.
 : val_(t) {}
template<typename T> testing::gmock_matchers_test::ConstPropagatingPtr< T >::ConstPropagatingPtr (const ConstPropagatingPtr< T > & other) inline
Definition at line 3292 of file gmock-matchers_test.cc.
 : val_(other.val_) {}
template<typename T> testing::gmock_matchers_test::ConstPropagatingPtr< T >::ConstPropagatingPtr () inline
Definition at line 3290 of file gmock-matchers_test.cc.
 : val_() {}
template<typename T> testing::gmock_matchers_test::ConstPropagatingPtr< T >::ConstPropagatingPtr (T * t) inline explicit
Definition at line 3291 of file gmock-matchers_test.cc.
 : val_(t) {}
template<typename T> testing::gmock_matchers_test::ConstPropagatingPtr< T >::ConstPropagatingPtr (const ConstPropagatingPtr< T > & other) inline
Definition at line 3292 of file gmock-matchers_test.cc.
 : val_(other.val_) {}
Member Function Documentation
template<typename T> T* testing::gmock_matchers_test::ConstPropagatingPtr< T >::get () inline
Definition at line 3294 of file gmock-matchers_test.cc.
 { return val_; }
template<typename T> T* testing::gmock_matchers_test::ConstPropagatingPtr< T >::get () inline
Definition at line 3294 of file gmock-matchers_test.cc.
 { return val_; }
template<typename T> T* testing::gmock_matchers_test::ConstPropagatingPtr< T >::get () inline
Definition at line 3294 of file gmock-matchers_test.cc.
 { return val_; }
template<typename T> const T* testing::gmock_matchers_test::ConstPropagatingPtr< T >::get () const inline
Definition at line 3297 of file gmock-matchers_test.cc.
 { return val_; }
template<typename T> const T* testing::gmock_matchers_test::ConstPropagatingPtr< T >::get () const inline
Definition at line 3297 of file gmock-matchers_test.cc.
 { return val_; }
template<typename T> const T* testing::gmock_matchers_test::ConstPropagatingPtr< T >::get () const inline
Definition at line 3297 of file gmock-matchers_test.cc.
 { return val_; }
template<typename T> T& testing::gmock_matchers_test::ConstPropagatingPtr< T >::operator* () inline
Definition at line 3295 of file gmock-matchers_test.cc.
 { return *val_; }
template<typename T> T& testing::gmock_matchers_test::ConstPropagatingPtr< T >::operator* () inline
Definition at line 3295 of file gmock-matchers_test.cc.
 { return *val_; }
template<typename T> T& testing::gmock_matchers_test::ConstPropagatingPtr< T >::operator* () inline
Definition at line 3295 of file gmock-matchers_test.cc.
 { return *val_; }
template<typename T> const T& testing::gmock_matchers_test::ConstPropagatingPtr< T >::operator* () const inline
Definition at line 3298 of file gmock-matchers_test.cc.
References testing::_, GCC61971::co, testing::gmock_matchers_test::Describe(), testing::gmock_matchers_test::DescribeNegation(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testing::gmock_matchers_test::Explain(), testing::gmock_matchers_test::GreaterThan(), testing::Gt(), testing::Lt(), testing::internal::MatcherBase< T >::Matches(), testing::gmock_matchers_test::OfType(), testing::Pointee(), testing::StartsWith(), T, and testing::internal::TEST().
 { return *val_; }
template<typename T> const T& testing::gmock_matchers_test::ConstPropagatingPtr< T >::operator* () const inline
Definition at line 3298 of file gmock-matchers_test.cc.
 { return *val_; }
template<typename T> const T& testing::gmock_matchers_test::ConstPropagatingPtr< T >::operator* () const inline
Definition at line 3298 of file gmock-matchers_test.cc.
References testing::_, GCC61971::co, testing::gmock_matchers_test::Describe(), testing::gmock_matchers_test::DescribeNegation(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testing::gmock_matchers_test::Explain(), testing::gmock_matchers_test::GreaterThan(), testing::Gt(), testing::Lt(), testing::internal::MatcherBase< T >::Matches(), testing::gmock_matchers_test::OfType(), testing::Pointee(), testing::StartsWith(), T, and testing::internal::TEST().
 { return *val_; }
Member Data Documentation
template<typename T> T * testing::gmock_matchers_test::ConstPropagatingPtr< T >::val_ private
Definition at line 3301 of file gmock-matchers_test.cc.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-matchers_test.cc