proxygen: folly::hazptr_rec< Atom > Class Template Reference
folly::hazptr_rec< Atom > Class Template Reference
#include <Hazptr-fwd.h>
Private Member Functions
const void * hazptr () const noexcept
FOLLY_ALWAYS_INLINE void reset_hazptr (const void *p=nullptr) noexcept
bool active () const noexcept
void set_active () noexcept
bool try_acquire () noexcept
void release () noexcept
hazptr_rec< Atom > * next ()
void set_next (hazptr_rec< Atom > *rec)
FOLLY_ALWAYS_INLINE hazptr_domain< Atom > * domain ()
void set_domain (hazptr_domain< Atom > *dom)
Private Attributes
Atom< const void * > hazptr_ {nullptr}
hazptr_domain< Atom > * domain_
hazptr_rec * next_
Atom< bool > active_ {false}
Friends
class hazptr_domain< Atom >
class hazptr_holder< Atom >
class hazptr_tc_entry< Atom >
Detailed Description
template<template< typename > class Atom>
class folly::hazptr_rec< Atom >
Hazard pointer record. Defined in HazptrRec.hhazptr_rec
hazptr_rec:
Contains the actual hazard pointer.
Definition at line 42 of file Hazptr-fwd.h.
Member Function Documentation
template<template< typename > class Atom> bool folly::hazptr_rec< Atom >::active () const inline private noexcept
Definition at line 50 of file HazptrRec.h.
{
     return active_.load(std::memory_order_acquire);
   }
template<template< typename > class Atom> FOLLY_ALWAYS_INLINE hazptr_domain<Atom>* folly::hazptr_rec< Atom >::domain () inline private
Definition at line 77 of file HazptrRec.h.
Referenced by folly::hazptr_holder< Atom >::~hazptr_holder().
{
     return domain_;
   }
template<template< typename > class Atom> const void* folly::hazptr_rec< Atom >::hazptr () const inline private noexcept
Definition at line 42 of file HazptrRec.h.
{
     return hazptr_.load(std::memory_order_acquire);
   }
template<template< typename > class Atom> hazptr_rec<Atom>* folly::hazptr_rec< Atom >::next () inline private
Definition at line 69 of file HazptrRec.h.
{
     return next_;
   }
template<template< typename > class Atom> void folly::hazptr_rec< Atom >::release () inline private noexcept
Definition at line 65 of file HazptrRec.h.
{
     active_.store(false, std::memory_order_release);
   }
template<template< typename > class Atom> FOLLY_ALWAYS_INLINE void folly::hazptr_rec< Atom >::reset_hazptr (const void * p = nullptr) inline private noexcept
Definition at line 46 of file HazptrRec.h.
Referenced by folly::hazptr_holder< Atom >::reset(), and folly::hazptr_holder< Atom >::~hazptr_holder().
{
     hazptr_.store(p, std::memory_order_release);
   }
template<template< typename > class Atom> void folly::hazptr_rec< Atom >::set_active () inline private noexcept
Definition at line 54 of file HazptrRec.h.
Referenced by folly::hazptr_domain< DeterministicAtomic >::acquire_new_hprec().
{
     active_.store(true, std::memory_order_relaxed);
   }
template<template< typename > class Atom> void folly::hazptr_rec< Atom >::set_domain (hazptr_domain< Atom > * dom) inline private
Definition at line 81 of file HazptrRec.h.
{
     domain_ = dom;
   }
template<template< typename > class Atom> void folly::hazptr_rec< Atom >::set_next (hazptr_rec< Atom > * rec) inline private
Definition at line 73 of file HazptrRec.h.
{
     next_ = rec;
   }
template<template< typename > class Atom> bool folly::hazptr_rec< Atom >::try_acquire () inline private noexcept
Definition at line 58 of file HazptrRec.h.
References a.
{
     bool a = active();
     return !a &&
         active_.compare_exchange_strong(
             a, true, std::memory_order_release, std::memory_order_relaxed);
   }
Friends And Related Function Documentation
template<template< typename > class Atom> friend class hazptr_domain< Atom > friend
Definition at line 38 of file HazptrRec.h.
template<template< typename > class Atom> friend class hazptr_holder< Atom > friend
Definition at line 39 of file HazptrRec.h.
template<template< typename > class Atom> friend class hazptr_tc_entry< Atom > friend
Definition at line 40 of file HazptrRec.h.
Member Data Documentation
template<template< typename > class Atom> Atom<bool> folly::hazptr_rec< Atom >::active_ {false} private
Definition at line 36 of file HazptrRec.h.
template<template< typename > class Atom> hazptr_domain<Atom>* folly::hazptr_rec< Atom >::domain_ private
Definition at line 34 of file HazptrRec.h.
template<template< typename > class Atom> Atom<const void*> folly::hazptr_rec< Atom >::hazptr_ {nullptr} private
Definition at line 33 of file HazptrRec.h.
template<template< typename > class Atom> hazptr_rec* folly::hazptr_rec< Atom >::next_ private
Definition at line 35 of file HazptrRec.h.
The documentation for this class was generated from the following files:
proxygen/folly/folly/synchronization/Hazptr-fwd.h
proxygen/folly/folly/synchronization/HazptrRec.h