proxygen: folly::AsyncServerSocket::ConnectionEventCallback Class Reference
folly::AsyncServerSocket::ConnectionEventCallback Class Reference abstract
#include <AsyncServerSocket.h>
Public Member Functions
virtual ~ConnectionEventCallback ()=default
virtual void onConnectionAccepted (const int socket, const SocketAddress &addr) noexcept=0
virtual void onConnectionAcceptError (const int err) noexcept=0
virtual void onConnectionDropped (const int socket, const SocketAddress &addr) noexcept=0
virtual void onConnectionEnqueuedForAcceptorCallback (const int socket, const SocketAddress &addr) noexcept=0
virtual void onConnectionDequeuedByAcceptorCallback (const int socket, const SocketAddress &addr) noexcept=0
virtual void onBackoffStarted () noexcept=0
virtual void onBackoffEnded () noexcept=0
virtual void onBackoffError () noexcept=0
Detailed Description
A callback interface to get notified of client socket events.
The ConnectionEventCallback implementations need to be thread-safe as the callbacks may be called from different threads.
Definition at line 77 of file AsyncServerSocket.h.
Constructor & Destructor Documentation
virtual folly::AsyncServerSocket::ConnectionEventCallback::~ConnectionEventCallback () virtual default
Member Function Documentation
virtual void folly::AsyncServerSocket::ConnectionEventCallback::onBackoffEnded () pure virtual noexcept
onBackoffEnded is called when the backoff period has ended and the socket has successfully resumed accepting new connections if there is any AcceptCallback registered.
Implemented in folly::test::TestConnectionEventCallback.
Referenced by folly::AsyncServerSocket::backoffTimeoutExpired().
virtual void folly::AsyncServerSocket::ConnectionEventCallback::onBackoffError () pure virtual noexcept
onBackoffError is called when there is an error entering backoff
Implemented in folly::test::TestConnectionEventCallback.
Referenced by folly::AsyncServerSocket::enterBackoff().
virtual void folly::AsyncServerSocket::ConnectionEventCallback::onBackoffStarted () pure virtual noexcept
onBackoffStarted is called when the socket has successfully started backing off accepting new client sockets.
Implemented in folly::test::TestConnectionEventCallback.
Referenced by folly::AsyncServerSocket::enterBackoff().
virtual void folly::AsyncServerSocket::ConnectionEventCallback::onConnectionAccepted (const int socket, const SocketAddress & addr) pure virtual noexcept
onConnectionAccepted() is called right after a client connection is accepted using the system accept()/accept4() APIs.
Implemented in folly::test::TestConnectionEventCallback.
Referenced by folly::AsyncServerSocket::handlerReady().
virtual void folly::AsyncServerSocket::ConnectionEventCallback::onConnectionAcceptError (const int err) pure virtual noexcept
onConnectionAcceptError() is called when an error occurred accepting a connection.
Implemented in folly::test::TestConnectionEventCallback.
Referenced by folly::AsyncServerSocket::handlerReady().
virtual void folly::AsyncServerSocket::ConnectionEventCallback::onConnectionDequeuedByAcceptorCallback (const int socket, const SocketAddress & addr) pure virtual noexcept
onConnectionDequeuedByAcceptorCallback() is called when the connection is successfully dequeued by an AcceptCallback.
Implemented in folly::test::TestConnectionEventCallback.
Referenced by folly::AsyncServerSocket::RemoteAcceptor::messageAvailable().
virtual void folly::AsyncServerSocket::ConnectionEventCallback::onConnectionDropped (const int socket, const SocketAddress & addr) pure virtual noexcept
onConnectionDropped() is called when a connection is dropped, probably because of some error encountered.
Implemented in folly::test::TestConnectionEventCallback.
Referenced by folly::AsyncServerSocket::dispatchSocket(), and folly::AsyncServerSocket::handlerReady().
virtual void folly::AsyncServerSocket::ConnectionEventCallback::onConnectionEnqueuedForAcceptorCallback (const int socket, const SocketAddress & addr) pure virtual noexcept
onConnectionEnqueuedForAcceptorCallback() is called when the connection is successfully enqueued for an AcceptCallback to pick up.
Implemented in folly::test::TestConnectionEventCallback.
Referenced by folly::AsyncServerSocket::dispatchSocket().
The documentation for this class was generated from the following file:
proxygen/folly/folly/io/async/AsyncServerSocket.h