proxygen: testing::internal::BothOfMatcherImpl< T > Class Template Reference
testing::internal::BothOfMatcherImpl< T > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
BothOfMatcherImpl (const Matcher< T > &matcher1, const Matcher< T > &matcher2)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (T x, MatchResultListener *listener) const
BothOfMatcherImpl (const Matcher< T > &matcher1, const Matcher< T > &matcher2)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (T x, MatchResultListener *listener) const
BothOfMatcherImpl (const Matcher< T > &matcher1, const Matcher< T > &matcher2)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (T x, MatchResultListener *listener) const
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
virtual ~MatcherDescriberInterface ()
virtual ~MatcherDescriberInterface ()
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (BothOfMatcherImpl)
GTEST_DISALLOW_ASSIGN_ (BothOfMatcherImpl)
GTEST_DISALLOW_ASSIGN_ (BothOfMatcherImpl)
Private Attributes
const Matcher< T > matcher1_
const Matcher< T > matcher2_
Detailed Description
template<typename T>
class testing::internal::BothOfMatcherImpl< T >
Definition at line 1492 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename T > testing::internal::BothOfMatcherImpl< T >::BothOfMatcherImpl (const Matcher< T > & matcher1, const Matcher< T > & matcher2) inline
Definition at line 1494 of file gmock-matchers.h.
       : matcher1_(matcher1), matcher2_(matcher2) {}
template<typename T > testing::internal::BothOfMatcherImpl< T >::BothOfMatcherImpl (const Matcher< T > & matcher1, const Matcher< T > & matcher2) inline
Definition at line 1494 of file gmock-matchers.h.
       : matcher1_(matcher1), matcher2_(matcher2) {}
template<typename T > testing::internal::BothOfMatcherImpl< T >::BothOfMatcherImpl (const Matcher< T > & matcher1, const Matcher< T > & matcher2) inline
Definition at line 1494 of file gmock-matchers.h.
       : matcher1_(matcher1), matcher2_(matcher2) {}
Member Function Documentation
template<typename T > virtual void testing::internal::BothOfMatcherImpl< T >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 1505 of file gmock-matchers.h.
{
     *os << "(";
     matcher1_.DescribeNegationTo(os);
     *os << ") or (";
     matcher2_.DescribeNegationTo(os);
     *os << ")";
   }
template<typename T > virtual void testing::internal::BothOfMatcherImpl< T >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 1505 of file gmock-matchers.h.
{
     *os << "(";
     matcher1_.DescribeNegationTo(os);
     *os << ") or (";
     matcher2_.DescribeNegationTo(os);
     *os << ")";
   }
template<typename T > virtual void testing::internal::BothOfMatcherImpl< T >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 1505 of file gmock-matchers.h.
{
     *os << "(";
     matcher1_.DescribeNegationTo(os);
     *os << ") or (";
     matcher2_.DescribeNegationTo(os);
     *os << ")";
   }
template<typename T > virtual void testing::internal::BothOfMatcherImpl< T >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 1497 of file gmock-matchers.h.
{
     *os << "(";
     matcher1_.DescribeTo(os);
     *os << ") and (";
     matcher2_.DescribeTo(os);
     *os << ")";
   }
template<typename T > virtual void testing::internal::BothOfMatcherImpl< T >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 1497 of file gmock-matchers.h.
{
     *os << "(";
     matcher1_.DescribeTo(os);
     *os << ") and (";
     matcher2_.DescribeTo(os);
     *os << ")";
   }
template<typename T > virtual void testing::internal::BothOfMatcherImpl< T >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 1497 of file gmock-matchers.h.
{
     *os << "(";
     matcher1_.DescribeTo(os);
     *os << ") and (";
     matcher2_.DescribeTo(os);
     *os << ")";
   }
template<typename T > testing::internal::BothOfMatcherImpl< T >::GTEST_DISALLOW_ASSIGN_ (BothOfMatcherImpl< T >) private
template<typename T > testing::internal::BothOfMatcherImpl< T >::GTEST_DISALLOW_ASSIGN_ (BothOfMatcherImpl< T >) private
template<typename T > testing::internal::BothOfMatcherImpl< T >::GTEST_DISALLOW_ASSIGN_ (BothOfMatcherImpl< T >) private
template<typename T > virtual bool testing::internal::BothOfMatcherImpl< T >::MatchAndExplain (T x, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< T >.
Definition at line 1513 of file gmock-matchers.h.
References testing::StringMatchResultListener::str().
{
     // If either matcher1_ or matcher2_ doesn't match x, we only need
     // to explain why one of them fails.
     StringMatchResultListener listener1;
     if (!matcher1_.MatchAndExplain(x, &listener1)) {
       *listener << listener1.str();
       return false;
     }
     StringMatchResultListener listener2;
     if (!matcher2_.MatchAndExplain(x, &listener2)) {
       *listener << listener2.str();
       return false;
     }
     // Otherwise we need to explain why *both* of them match.
     const internal::string s1 = listener1.str();
     const internal::string s2 = listener2.str();
     if (s1 == "") {
       *listener << s2;
     } else {
       *listener << s1;
       if (s2 != "") {
         *listener << ", and " << s2;
       }
     }
     return true;
   }
template<typename T > virtual bool testing::internal::BothOfMatcherImpl< T >::MatchAndExplain (T x, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< T >.
Definition at line 1513 of file gmock-matchers.h.
References testing::Args(), GTEST_DISALLOW_ASSIGN_, testing::StringMatchResultListener::str(), and T.
{
     // If either matcher1_ or matcher2_ doesn't match x, we only need
     // to explain why one of them fails.
     StringMatchResultListener listener1;
     if (!matcher1_.MatchAndExplain(x, &listener1)) {
       *listener << listener1.str();
       return false;
     }
     StringMatchResultListener listener2;
     if (!matcher2_.MatchAndExplain(x, &listener2)) {
       *listener << listener2.str();
       return false;
     }
     // Otherwise we need to explain why *both* of them match.
     const internal::string s1 = listener1.str();
     const internal::string s2 = listener2.str();
     if (s1 == "") {
       *listener << s2;
     } else {
       *listener << s1;
       if (s2 != "") {
         *listener << ", and " << s2;
       }
     }
     return true;
   }
template<typename T > virtual bool testing::internal::BothOfMatcherImpl< T >::MatchAndExplain (T x, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< T >.
Definition at line 1513 of file gmock-matchers.h.
References testing::Args(), GTEST_DISALLOW_ASSIGN_, testing::StringMatchResultListener::str(), and T.
{
     // If either matcher1_ or matcher2_ doesn't match x, we only need
     // to explain why one of them fails.
     StringMatchResultListener listener1;
     if (!matcher1_.MatchAndExplain(x, &listener1)) {
       *listener << listener1.str();
       return false;
     }
     StringMatchResultListener listener2;
     if (!matcher2_.MatchAndExplain(x, &listener2)) {
       *listener << listener2.str();
       return false;
     }
     // Otherwise we need to explain why *both* of them match.
     const internal::string s1 = listener1.str();
     const internal::string s2 = listener2.str();
     if (s1 == "") {
       *listener << s2;
     } else {
       *listener << s1;
       if (s2 != "") {
         *listener << ", and " << s2;
       }
     }
     return true;
   }
Member Data Documentation
template<typename T > const Matcher< T > testing::internal::BothOfMatcherImpl< T >::matcher1_ private
Definition at line 1544 of file gmock-matchers.h.
template<typename T > const Matcher< T > testing::internal::BothOfMatcherImpl< T >::matcher2_ private
Definition at line 1545 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h