proxygen: folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed > Class Template Reference
folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed > Class Template Reference
#include <Parallel-inl.h>
Classes
class Executor
class Puller
class Pusher
Public Member Functions
Generator (Source source, Ops ops, size_t threads)
template<class Handler >
bool apply (Handler &&handler) const
template<class Body >
void foreach (Body &&body) const
Public Member Functions inherited from folly::gen::GenImpl< OutputDecayed &&, Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed > >
bool apply (Handler &&handler) const
void foreach (Body &&body) const
Public Member Functions inherited from folly::gen::FBounded< Self >
const Self & self () const
Self & self ()
Private Types
using InQueue = ClosableMPMCQueue< InputDecayed >
using OutQueue = ClosableMPMCQueue< OutputDecayed >
Private Attributes
Source source_
Ops ops_
size_t threads_
Additional Inherited Members
Public Types inherited from folly::gen::GenImpl< OutputDecayed &&, Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed > >
typedef OutputDecayed && ValueType
typedef std::decay< OutputDecayed && >::type StorageType
Static Public Attributes inherited from folly::gen::GenImpl< OutputDecayed &&, Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed > >
static constexpr bool infinite
Protected Member Functions inherited from folly::gen::GenImpl< OutputDecayed &&, Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed > >
GenImpl ()=default
GenImpl (GenImpl &&)=default
GenImpl (const GenImpl &)=default
GenImpl & operator= (GenImpl &&)=default
GenImpl & operator= (const GenImpl &)=default
Detailed Description
template<class Ops>
template<class Input, class Source, class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type>
class folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >
Definition at line 166 of file Parallel-inl.h.
Member Typedef Documentation
template<class Ops > template<class Input , class Source , class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type> using folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::InQueue = ClosableMPMCQueue<InputDecayed> private
Definition at line 179 of file Parallel-inl.h.
template<class Ops > template<class Input , class Source , class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type> using folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::OutQueue = ClosableMPMCQueue<OutputDecayed> private
Definition at line 180 of file Parallel-inl.h.
Constructor & Destructor Documentation
template<class Ops > template<class Input , class Source , class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type> folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Generator (Source source, Ops ops, size_t threads) inline
Definition at line 305 of file Parallel-inl.h.
         : source_(std::move(source)),
           ops_(std::move(ops)),
           threads_(
               threads
                   ? threads
                   : size_t(std::max<long>(1, sysconf(_SC_NPROCESSORS_CONF)))) {}
Member Function Documentation
template<class Ops > template<class Input , class Source , class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type> template<class Handler > bool folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::apply (Handler && handler) const inline
Definition at line 314 of file Parallel-inl.h.
References folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >::closeInputProducer(), folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >::closeOutputConsumer(), folly::pushmi::executor, handler(), folly::gen::move, gmock_output_test::output, folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >::readUnlessClosed(), folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >::readUnlessEmpty(), folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >::writeUnlessClosed(), and folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >::writeUnlessFull().
{
       Executor<false> executor(threads_, &ops_);
       bool more = true;
       source_.apply([&](Input input) {
         if (executor.writeUnlessFull(std::forward<Input>(input))) {
           return true;
         }
         OutputDecayed output;
         while (executor.readUnlessEmpty(output)) {
           if (!handler(std::move(output))) {
             more = false;
             return false;
           }
         }
         if (!executor.writeUnlessClosed(std::forward<Input>(input))) {
           return false;
         }
         return true;
       });
       executor.closeInputProducer();
       if (more) {
         OutputDecayed output;
         while (executor.readUnlessClosed(output)) {
           if (!handler(std::move(output))) {
             more = false;
             break;
           }
         }
       }
       executor.closeOutputConsumer();
       return more;
     }
template<class Ops > template<class Input , class Source , class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type> template<class Body > void folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::foreach (Body && body) const inline
Definition at line 350 of file Parallel-inl.h.
References folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >::closeInputProducer(), folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >::closeOutputConsumer(), folly::pushmi::executor, folly::gen::move, gmock_output_test::output, folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >::readUnlessClosed(), folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >::readUnlessEmpty(), folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >::writeUnlessClosed(), and folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Executor< all >::writeUnlessFull().
{
       Executor<true> executor(threads_, &ops_);
       source_.foreach([&](Input input) {
         if (executor.writeUnlessFull(std::forward<Input>(input))) {
           return;
         }
         OutputDecayed output;
         while (executor.readUnlessEmpty(output)) {
           body(std::move(output));
         }
         CHECK(executor.writeUnlessClosed(std::forward<Input>(input)));
       });
       executor.closeInputProducer();
       OutputDecayed output;
       while (executor.readUnlessClosed(output)) {
         body(std::move(output));
       }
       executor.closeOutputConsumer();
     }
Member Data Documentation
template<class Ops > template<class Input , class Source , class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type> Ops folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::ops_ private
Definition at line 176 of file Parallel-inl.h.
template<class Ops > template<class Input , class Source , class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type> Source folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::source_ private
Definition at line 175 of file Parallel-inl.h.
template<class Ops > template<class Input , class Source , class InputDecayed = typename std::decay<Input>::type, class Composed = decltype(std::declval<Ops>().compose(Empty<InputDecayed&&>())), class Output = typename Composed::ValueType, class OutputDecayed = typename std::decay<Output>::type> size_t folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::threads_ private
Definition at line 177 of file Parallel-inl.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/gen/Parallel-inl.h