proxygen: testing::internal::EachMatcher< M > Class Template Reference
testing::internal::EachMatcher< M > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
EachMatcher (M m)
template<typename Container >
operator Matcher< Container > () const
EachMatcher (M m)
template<typename Container >
operator Matcher< Container > () const
EachMatcher (M m)
template<typename Container >
operator Matcher< Container > () const
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (EachMatcher)
GTEST_DISALLOW_ASSIGN_ (EachMatcher)
GTEST_DISALLOW_ASSIGN_ (EachMatcher)
Private Attributes
const M inner_matcher_
Detailed Description
template<typename M>
class testing::internal::EachMatcher< M >
Definition at line 2919 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename M > testing::internal::EachMatcher< M >::EachMatcher (M m) inline explicit
Definition at line 2921 of file gmock-matchers.h.
 : inner_matcher_(m) {}
template<typename M > testing::internal::EachMatcher< M >::EachMatcher (M m) inline explicit
Definition at line 2921 of file gmock-matchers.h.
 : inner_matcher_(m) {}
template<typename M > testing::internal::EachMatcher< M >::EachMatcher (M m) inline explicit
Definition at line 2921 of file gmock-matchers.h.
 : inner_matcher_(m) {}
Member Function Documentation
template<typename M > testing::internal::EachMatcher< M >::GTEST_DISALLOW_ASSIGN_ (EachMatcher< M >) private
template<typename M > testing::internal::EachMatcher< M >::GTEST_DISALLOW_ASSIGN_ (EachMatcher< M >) private
template<typename M > testing::internal::EachMatcher< M >::GTEST_DISALLOW_ASSIGN_ (EachMatcher< M >) private
template<typename M > template<typename Container > testing::internal::EachMatcher< M >::operator Matcher< Container > () const inline
Definition at line 2924 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(new EachMatcherImpl<Container>(inner_matcher_));
   }
template<typename M > template<typename Container > testing::internal::EachMatcher< M >::operator Matcher< Container > () const inline
Definition at line 2924 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, GTEST_REMOVE_REFERENCE_AND_CONST_, M, and testing::MakeMatcher().
{
     return MakeMatcher(new EachMatcherImpl<Container>(inner_matcher_));
   }
template<typename M > template<typename Container > testing::internal::EachMatcher< M >::operator Matcher< Container > () const inline
Definition at line 2924 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, GTEST_REMOVE_REFERENCE_AND_CONST_, M, and testing::MakeMatcher().
{
     return MakeMatcher(new EachMatcherImpl<Container>(inner_matcher_));
   }
Member Data Documentation
template<typename M > const M testing::internal::EachMatcher< M >::inner_matcher_ private
Definition at line 2929 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h