proxygen: folly::DefaultKeepAliveExecutor::WeakRef Class Reference
folly::DefaultKeepAliveExecutor::WeakRef Class Reference
Public Member Functions
void add (Func f) override
void addWithPriority (Func f, int8_t priority) override
virtual uint8_t getNumPriorities () const override
Public Member Functions inherited from folly::Executor
virtual ~Executor ()
Static Public Member Functions
static folly::Executor::KeepAlive create (std::shared_ptr< ControlBlock > controlBlock, Executor *executor)
Static Public Member Functions inherited from folly::Executor
template<typename ExecutorT >
static KeepAlive< ExecutorT > getKeepAliveToken (ExecutorT *executor)
template<typename ExecutorT >
static KeepAlive< ExecutorT > getKeepAliveToken (ExecutorT &executor)
Private Member Functions
WeakRef (std::shared_ptr< ControlBlock > controlBlock, Executor *executor)
bool keepAliveAcquire () override
void keepAliveRelease () override
folly::Executor::KeepAlive lock ()
Private Attributes
std::atomic< size_t > keepAliveCount_ {1}
std::shared_ptr< ControlBlock > controlBlock_
Executor * executor_
uint8_t numPriorities_
Additional Inherited Members
Static Public Attributes inherited from folly::Executor
static const int8_t LO_PRI = SCHAR_MIN
static const int8_t MID_PRI = 0
static const int8_t HI_PRI = SCHAR_MAX
Static Protected Member Functions inherited from folly::Executor
template<typename ExecutorT >
static bool isKeepAliveDummy (const KeepAlive< ExecutorT > &keepAlive)
template<typename ExecutorT >
static KeepAlive< ExecutorT > makeKeepAlive (ExecutorT *executor)
Detailed Description
Definition at line 54 of file DefaultKeepAliveExecutor.h.
Constructor & Destructor Documentation
folly::DefaultKeepAliveExecutor::WeakRef::WeakRef (std::shared_ptr< ControlBlock > controlBlock, Executor * executor) inline private
Definition at line 79 of file DefaultKeepAliveExecutor.h.
         : controlBlock_(std::move(controlBlock)),
           executor_(executor),
           numPriorities_(executor->getNumPriorities()) {}
Member Function Documentation
void folly::DefaultKeepAliveExecutor::WeakRef::add (Func) inline override virtual
Enqueue a function to executed by this executor. This and all variants must be threadsafe.
Implements folly::Executor.
Definition at line 62 of file DefaultKeepAliveExecutor.h.
References folly::pushmi::executor, folly::lock(), and folly::gen::move.
{
       if (auto executor = lock()) {
         executor->add(std::move(f));
       }
     }
void folly::DefaultKeepAliveExecutor::WeakRef::addWithPriority (Func , int8_t priority) inline override virtual
Enqueue a function with a given priority, where 0 is the medium priority This is up to the implementation to enforce
Reimplemented from folly::Executor.
Definition at line 68 of file DefaultKeepAliveExecutor.h.
References folly::pushmi::executor, folly::lock(), and folly::gen::move.
{
       if (auto executor = lock()) {
         executor->addWithPriority(std::move(f), priority);
       }
     }
static folly::Executor::KeepAlive folly::DefaultKeepAliveExecutor::WeakRef::create (std::shared_ptr< ControlBlock > controlBlock, Executor * executor) inline static
Definition at line 56 of file DefaultKeepAliveExecutor.h.
References folly::Executor::makeKeepAlive(), and folly::gen::move.
Referenced by folly::DefaultKeepAliveExecutor::weakRef().
{
       return makeKeepAlive(new WeakRef(std::move(controlBlock), executor));
     }
virtual uint8_t folly::DefaultKeepAliveExecutor::WeakRef::getNumPriorities () const inline override virtual
Reimplemented from folly::Executor.
Definition at line 74 of file DefaultKeepAliveExecutor.h.
{
       return numPriorities_;
     }
bool folly::DefaultKeepAliveExecutor::WeakRef::keepAliveAcquire () inline override private virtual
Reimplemented from folly::Executor.
Definition at line 84 of file DefaultKeepAliveExecutor.h.
References folly::DefaultKeepAliveExecutor::ControlBlock::keepAliveCount_.
{
       auto keepAliveCount =
           keepAliveCount_.fetch_add(1, std::memory_order_relaxed);
       // We should never increment from 0
       DCHECK(keepAliveCount > 0);
       return true;
     }
void folly::DefaultKeepAliveExecutor::WeakRef::keepAliveRelease () inline override private virtual
Reimplemented from folly::Executor.
Definition at line 92 of file DefaultKeepAliveExecutor.h.
References folly::DefaultKeepAliveExecutor::ControlBlock::keepAliveCount_.
{
       auto keepAliveCount =
           keepAliveCount_.fetch_sub(1, std::memory_order_acq_rel);
       DCHECK(keepAliveCount >= 1);
       if (keepAliveCount == 1) {
         delete this;
       }
     }
folly::Executor::KeepAlive folly::DefaultKeepAliveExecutor::WeakRef::lock () inline private
Definition at line 102 of file DefaultKeepAliveExecutor.h.
References folly::DefaultKeepAliveExecutor::controlBlock_, and folly::Executor::makeKeepAlive().
{
       auto controlBlock =
           controlBlock_->keepAliveCount_.load(std::memory_order_relaxed);
       do {
         if (controlBlock == 0) {
           return {};
         }
       } while (!controlBlock_->keepAliveCount_.compare_exchange_weak(
           controlBlock,
           controlBlock + 1,
           std::memory_order_release,
           std::memory_order_relaxed));
       return makeKeepAlive(executor_);
     }
Member Data Documentation
std::shared_ptr<ControlBlock> folly::DefaultKeepAliveExecutor::WeakRef::controlBlock_ private
Definition at line 120 of file DefaultKeepAliveExecutor.h.
Executor* folly::DefaultKeepAliveExecutor::WeakRef::executor_ private
Definition at line 121 of file DefaultKeepAliveExecutor.h.
std::atomic<size_t> folly::DefaultKeepAliveExecutor::WeakRef::keepAliveCount_ {1} private
Definition at line 118 of file DefaultKeepAliveExecutor.h.
uint8_t folly::DefaultKeepAliveExecutor::WeakRef::numPriorities_ private
Definition at line 123 of file DefaultKeepAliveExecutor.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/DefaultKeepAliveExecutor.h