proxygen: folly::PriorityLifoSemMPMCQueue< T, kBehavior > Class Template Reference
folly::PriorityLifoSemMPMCQueue< T, kBehavior > Class Template Reference
#include <PriorityLifoSemMPMCQueue.h>
Public Member Functions
PriorityLifoSemMPMCQueue (uint8_t numPriorities, size_t max_capacity)
PriorityLifoSemMPMCQueue (folly::Range< const size_t * > capacities)
uint8_t getNumPriorities () override
BlockingQueueAddResult add (T item) override
BlockingQueueAddResult addWithPriority (T item, int8_t priority) override
T take () override
folly::Optional< T > try_take_for (std::chrono::milliseconds time) override
bool nonBlockingTake (T &item)
size_t size () override
size_t sizeGuess () const
Public Member Functions inherited from folly::BlockingQueue< T >
virtual ~BlockingQueue ()=default
Private Attributes
folly::LifoSem sem_
std::vector< folly::MPMCQueue< T > > queues_
Detailed Description
template<class T, QueueBehaviorIfFull kBehavior = QueueBehaviorIfFull::THROW>
class folly::PriorityLifoSemMPMCQueue< T, kBehavior >
Definition at line 29 of file PriorityLifoSemMPMCQueue.h.
Constructor & Destructor Documentation
template<class T, QueueBehaviorIfFull kBehavior = QueueBehaviorIfFull::THROW> folly::PriorityLifoSemMPMCQueue< T, kBehavior >::PriorityLifoSemMPMCQueue (uint8_t numPriorities, size_t max_capacity) inline
Definition at line 34 of file PriorityLifoSemMPMCQueue.h.
References i, int8_t, and folly::PriorityLifoSemMPMCQueue< T, kBehavior >::queues_.
{
     queues_.reserve(numPriorities);
     for (int8_t i = 0; i < numPriorities; i++) {
       queues_.emplace_back(max_capacity);
     }
   }
template<class T, QueueBehaviorIfFull kBehavior = QueueBehaviorIfFull::THROW> folly::PriorityLifoSemMPMCQueue< T, kBehavior >::PriorityLifoSemMPMCQueue (folly::Range< const size_t * > capacities) inline
Definition at line 41 of file PriorityLifoSemMPMCQueue.h.
References folly::PriorityLifoSemMPMCQueue< T, kBehavior >::queues_, and folly::Range< Iter >::size().
{
     CHECK_LT(capacities.size(), 256) << "At most 255 priorities supported";
     queues_.reserve(capacities.size());
     for (auto capacity : capacities) {
       queues_.emplace_back(capacity);
     }
   }
Member Function Documentation
template<class T, QueueBehaviorIfFull kBehavior = QueueBehaviorIfFull::THROW> BlockingQueueAddResult folly::PriorityLifoSemMPMCQueue< T, kBehavior >::add (T item) inline override virtual
Implements folly::BlockingQueue< T >.
Definition at line 55 of file PriorityLifoSemMPMCQueue.h.
References folly::PriorityLifoSemMPMCQueue< T, kBehavior >::addWithPriority(), folly::Executor::MID_PRI, and folly::gen::move.
{
     return addWithPriority(std::move(item), folly::Executor::MID_PRI);
   }
template<class T, QueueBehaviorIfFull kBehavior = QueueBehaviorIfFull::THROW> BlockingQueueAddResult folly::PriorityLifoSemMPMCQueue< T, kBehavior >::addWithPriority (T item, int8_t priority) inline override virtual
Reimplemented from folly::BlockingQueue< T >.
Definition at line 59 of file PriorityLifoSemMPMCQueue.h.
References folly::BLOCK, folly::PriorityLifoSemMPMCQueue< T, kBehavior >::getNumPriorities(), max, min, folly::gen::move, folly::detail::LifoSemBase< Handoff, Atom >::post(), folly::PriorityLifoSemMPMCQueue< T, kBehavior >::queues_, folly::PriorityLifoSemMPMCQueue< T, kBehavior >::sem_, folly::THROW, and fizz::detail::write().
Referenced by folly::PriorityLifoSemMPMCQueue< T, kBehavior >::add(), and TEST().
{
     int mid = getNumPriorities() / 2;
     size_t queue = priority < 0
         ? std::max(0, mid + priority)
         : std::min(getNumPriorities() - 1, mid + priority);
     CHECK_LT(queue, queues_.size());
     switch (kBehavior) { // static
       case QueueBehaviorIfFull::THROW:
         if (!queues_[queue].write(std::move(item))) {
           throw QueueFullException("LifoSemMPMCQueue full, can't add item");
         }
         break;
       case QueueBehaviorIfFull::BLOCK:
         queues_[queue].blockingWrite(std::move(item));
         break;
     }
     return sem_.post();
   }
template<class T, QueueBehaviorIfFull kBehavior = QueueBehaviorIfFull::THROW> uint8_t folly::PriorityLifoSemMPMCQueue< T, kBehavior >::getNumPriorities () inline override virtual
Reimplemented from folly::BlockingQueue< T >.
Definition at line 50 of file PriorityLifoSemMPMCQueue.h.
References folly::PriorityLifoSemMPMCQueue< T, kBehavior >::queues_.
Referenced by folly::PriorityLifoSemMPMCQueue< T, kBehavior >::addWithPriority().
{
     return queues_.size();
   }
template<class T, QueueBehaviorIfFull kBehavior = QueueBehaviorIfFull::THROW> bool folly::PriorityLifoSemMPMCQueue< T, kBehavior >::nonBlockingTake (T & item) inline
Definition at line 100 of file PriorityLifoSemMPMCQueue.h.
References folly::PriorityLifoSemMPMCQueue< T, kBehavior >::queues_.
Referenced by folly::PriorityLifoSemMPMCQueue< T, kBehavior >::take(), and folly::PriorityLifoSemMPMCQueue< T, kBehavior >::try_take_for().
{
     for (auto it = queues_.rbegin(); it != queues_.rend(); it++) {
       if (it->readIfNotEmpty(item)) {
         return true;
       }
     }
     return false;
   }
template<class T, QueueBehaviorIfFull kBehavior = QueueBehaviorIfFull::THROW> size_t folly::PriorityLifoSemMPMCQueue< T, kBehavior >::size () inline override virtual
Implements folly::BlockingQueue< T >.
Definition at line 109 of file PriorityLifoSemMPMCQueue.h.
References folly::PriorityLifoSemMPMCQueue< T, kBehavior >::queues_.
Referenced by folly::PriorityLifoSemMPMCQueue< T, kBehavior >::sizeGuess().
{
     size_t size = 0;
     for (auto& q : queues_) {
       size += q.size();
     }
     return size;
   }
template<class T, QueueBehaviorIfFull kBehavior = QueueBehaviorIfFull::THROW> size_t folly::PriorityLifoSemMPMCQueue< T, kBehavior >::sizeGuess () const inline
Definition at line 117 of file PriorityLifoSemMPMCQueue.h.
References folly::PriorityLifoSemMPMCQueue< T, kBehavior >::queues_, and folly::PriorityLifoSemMPMCQueue< T, kBehavior >::size().
{
     size_t size = 0;
     for (auto& q : queues_) {
       size += q.sizeGuess();
     }
     return size;
   }
template<class T, QueueBehaviorIfFull kBehavior = QueueBehaviorIfFull::THROW> T folly::PriorityLifoSemMPMCQueue< T, kBehavior >::take () inline override virtual
Implements folly::BlockingQueue< T >.
Definition at line 78 of file PriorityLifoSemMPMCQueue.h.
References folly::PriorityLifoSemMPMCQueue< T, kBehavior >::nonBlockingTake(), folly::PriorityLifoSemMPMCQueue< T, kBehavior >::sem_, folly::T, and folly::detail::LifoSemBase< Handoff, Atom >::wait().
                     {
     T item;
     while (true) {
       if (nonBlockingTake(item)) {
         return item;
       }
       sem_.wait();
     }
   }
template<class T, QueueBehaviorIfFull kBehavior = QueueBehaviorIfFull::THROW> folly::Optional<T> folly::PriorityLifoSemMPMCQueue< T, kBehavior >::try_take_for (std::chrono::milliseconds time) inline override virtual
Implements folly::BlockingQueue< T >.
Definition at line 88 of file PriorityLifoSemMPMCQueue.h.
References folly::gen::move, folly::PriorityLifoSemMPMCQueue< T, kBehavior >::nonBlockingTake(), folly::none, folly::PriorityLifoSemMPMCQueue< T, kBehavior >::sem_, folly::T, and folly::detail::LifoSemBase< Handoff, Atom >::try_wait_for().
{
     T item;
     while (true) {
       if (nonBlockingTake(item)) {
         return std::move(item);
       }
       if (!sem_.try_wait_for(time)) {
         return folly::none;
       }
     }
   }
Member Data Documentation
template<class T, QueueBehaviorIfFull kBehavior = QueueBehaviorIfFull::THROW> std::vector<folly::MPMCQueue<T> > folly::PriorityLifoSemMPMCQueue< T, kBehavior >::queues_ private
Definition at line 127 of file PriorityLifoSemMPMCQueue.h.
Referenced by folly::PriorityLifoSemMPMCQueue< T, kBehavior >::addWithPriority(), folly::PriorityLifoSemMPMCQueue< T, kBehavior >::getNumPriorities(), folly::PriorityLifoSemMPMCQueue< T, kBehavior >::nonBlockingTake(), folly::PriorityLifoSemMPMCQueue< T, kBehavior >::PriorityLifoSemMPMCQueue(), folly::PriorityLifoSemMPMCQueue< T, kBehavior >::size(), and folly::PriorityLifoSemMPMCQueue< T, kBehavior >::sizeGuess().
template<class T, QueueBehaviorIfFull kBehavior = QueueBehaviorIfFull::THROW> folly::LifoSem folly::PriorityLifoSemMPMCQueue< T, kBehavior >::sem_ private
Definition at line 126 of file PriorityLifoSemMPMCQueue.h.
Referenced by folly::PriorityLifoSemMPMCQueue< T, kBehavior >::addWithPriority(), folly::PriorityLifoSemMPMCQueue< T, kBehavior >::take(), and folly::PriorityLifoSemMPMCQueue< T, kBehavior >::try_take_for().
The documentation for this class was generated from the following file:
proxygen/folly/folly/executors/task_queue/PriorityLifoSemMPMCQueue.h