proxygen: testing::gmock_generated_function_mockers_test::MockOverloadedOnConstness Class Reference
testing::gmock_generated_function_mockers_test::MockOverloadedOnConstness Class Reference
Public Member Functions
MockOverloadedOnConstness ()
MOCK_CONST_METHOD1 (Overloaded, int(int n))
MOCK_METHOD1 (Overloaded, int(int n))
MockOverloadedOnConstness ()
MOCK_CONST_METHOD1 (Overloaded, int(int n))
MOCK_METHOD1 (Overloaded, int(int n))
MockOverloadedOnConstness ()
MOCK_CONST_METHOD1 (Overloaded, int(int n))
MOCK_METHOD1 (Overloaded, int(int n))
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockOverloadedOnConstness)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockOverloadedOnConstness)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockOverloadedOnConstness)
Detailed Description
Definition at line 535 of file gmock-generated-function-mockers_test.cc.
Constructor & Destructor Documentation
testing::gmock_generated_function_mockers_test::MockOverloadedOnConstness::MockOverloadedOnConstness () inline
Definition at line 537 of file gmock-generated-function-mockers_test.cc.
References GTEST_DISALLOW_COPY_AND_ASSIGN_, and MY_MOCK_METHODS2_.
 {}
testing::gmock_generated_function_mockers_test::MockOverloadedOnConstness::MockOverloadedOnConstness () inline
Definition at line 537 of file gmock-generated-function-mockers_test.cc.
References testing::_, call(), EXPECT_CALL, EXPECT_EQ, f, testing::gmock_matchers_test::foo, testing::Ge(), GTEST_DISALLOW_COPY_AND_ASSIGN_, i, MY_MOCK_METHODS2_, testing::Return(), testing::ReturnRef(), testing::gmock_generated_function_mockers_test::TEST(), and value.
 {}
testing::gmock_generated_function_mockers_test::MockOverloadedOnConstness::MockOverloadedOnConstness () inline
Definition at line 537 of file gmock-generated-function-mockers_test.cc.
References testing::_, call(), EXPECT_CALL, EXPECT_EQ, f, testing::gmock_matchers_test::foo, testing::Ge(), GTEST_DISALLOW_COPY_AND_ASSIGN_, i, MY_MOCK_METHODS2_, testing::Return(), testing::ReturnRef(), testing::gmock_generated_function_mockers_test::TEST(), and value.
 {}
Member Function Documentation
testing::gmock_generated_function_mockers_test::MockOverloadedOnConstness::GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockOverloadedOnConstness) private
testing::gmock_generated_function_mockers_test::MockOverloadedOnConstness::GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockOverloadedOnConstness) private
testing::gmock_generated_function_mockers_test::MockOverloadedOnConstness::GTEST_DISALLOW_COPY_AND_ASSIGN_ (MockOverloadedOnConstness) private
testing::gmock_generated_function_mockers_test::MockOverloadedOnConstness::MOCK_CONST_METHOD1 (Overloaded , int(int n))
testing::gmock_generated_function_mockers_test::MockOverloadedOnConstness::MOCK_CONST_METHOD1 (Overloaded , int(int n))
testing::gmock_generated_function_mockers_test::MockOverloadedOnConstness::MOCK_CONST_METHOD1 (Overloaded , int(int n))
testing::gmock_generated_function_mockers_test::MockOverloadedOnConstness::MOCK_METHOD1 (Overloaded , int(int n))
testing::gmock_generated_function_mockers_test::MockOverloadedOnConstness::MOCK_METHOD1 (Overloaded , int(int n))
testing::gmock_generated_function_mockers_test::MockOverloadedOnConstness::MOCK_METHOD1 (Overloaded , int(int n))
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-generated-function-mockers_test.cc