proxygen: folly::rcu_token Class Reference
folly::rcu_token Class Reference
#include <Rcu.h>
Public Member Functions
rcu_token (uint64_t epoch)
rcu_token ()
~rcu_token ()=default
rcu_token (const rcu_token &)=delete
rcu_token (rcu_token &&other)=default
rcu_token & operator= (const rcu_token &other)=delete
rcu_token & operator= (rcu_token &&other)=default
Private Attributes
uint64_t epoch_
Friends
template<typename Tag >
class rcu_domain
Detailed Description
Definition at line 291 of file Rcu.h.
Constructor & Destructor Documentation
folly::rcu_token::rcu_token (uint64_t epoch) inline
Definition at line 293 of file Rcu.h.
 : epoch_(epoch) {}
folly::rcu_token::rcu_token () inline
Definition at line 294 of file Rcu.h.
References operator=(), and ~rcu_token().
 {}
folly::rcu_token::~rcu_token () default
Referenced by rcu_token().
folly::rcu_token::rcu_token (const rcu_token &) delete
folly::rcu_token::rcu_token (rcu_token && other) default
Member Function Documentation
rcu_token& folly::rcu_token::operator= (const rcu_token & other) delete
Referenced by folly::rcu_reader_domain< Tag >::rcu_reader_domain(), and rcu_token().
rcu_token& folly::rcu_token::operator= (rcu_token && other) default
Friends And Related Function Documentation
template<typename Tag > friend class rcu_domain friend
Definition at line 304 of file Rcu.h.
Member Data Documentation
uint64_t folly::rcu_token::epoch_ private
Definition at line 305 of file Rcu.h.
Referenced by folly::rcu_reader_domain< Tag >::lock(), folly::rcu_reader_domain< Tag >::operator=(), folly::rcu_reader_domain< Tag >::swap(), folly::rcu_reader_domain< Tag >::unlock(), and folly::rcu_reader_domain< Tag >::~rcu_reader_domain().
The documentation for this class was generated from the following file:
proxygen/folly/folly/synchronization/Rcu.h