proxygen: folly::FileHandlerFactory::WriterFactory Class Reference
folly::FileHandlerFactory::WriterFactory Class Reference
Public Member Functions
bool processOption (StringPiece name, StringPiece value) override
std::shared_ptr< LogWriter > createWriter () override
Public Member Functions inherited from folly::StandardLogHandlerFactory::OptionProcessor
virtual ~OptionProcessor ()
Public Attributes
std::string path_
FileWriterFactory fileWriterFactory_
Detailed Description
Definition at line 24 of file FileHandlerFactory.cpp.
Member Function Documentation
std::shared_ptr<LogWriter> folly::FileHandlerFactory::WriterFactory::createWriter () inline override virtual
Implements folly::StandardLogHandlerFactory::WriterFactory.
Definition at line 39 of file FileHandlerFactory.cpp.
References folly::FileWriterFactory::createWriter(), fileWriterFactory_, and path_.
{
     // Get the output file to use
     if (path_.empty()) {
       throw std::invalid_argument("no path specified for file handler");
     }
     return fileWriterFactory_.createWriter(
         File{path_, O_WRONLY | O_APPEND | O_CREAT});
   }
bool folly::FileHandlerFactory::WriterFactory::processOption (StringPiece name, StringPiece value) inline override virtual
Process an option.
This should return true if the option was processed successfully, or false if this is an unknown option name. It should throw an exception if the option name is known but there is a problem with the value.
Implements folly::StandardLogHandlerFactory::OptionProcessor.
Definition at line 27 of file FileHandlerFactory.cpp.
References fileWriterFactory_, path_, folly::FileWriterFactory::processOption(), and folly::Range< Iter >::str().
{
     if (name == "path") {
       path_ = value.str();
       return true;
     }
     // TODO(T29811675): In the future it would be nice to support log rotation,
     // and add parameters to control when the log file should be rotated.
     return fileWriterFactory_.processOption(name, value);
   }
Member Data Documentation
FileWriterFactory folly::FileHandlerFactory::WriterFactory::fileWriterFactory_
Definition at line 49 of file FileHandlerFactory.cpp.
Referenced by createWriter(), and processOption().
std::string folly::FileHandlerFactory::WriterFactory::path_
Definition at line 48 of file FileHandlerFactory.cpp.
Referenced by createWriter(), and processOption().
The documentation for this class was generated from the following file:
proxygen/folly/folly/logging/FileHandlerFactory.cpp