proxygen: PCQ< T > Class Template Reference
PCQ< T > Class Template Reference
Public Member Functions
PCQ (uint64_t capacity)
void enqueue (const T &)
bool try_enqueue (const T &v)
bool try_enqueue (T &&v)
template<typename Rep , typename Period >
bool try_enqueue_for (const T &, const std::chrono::duration< Rep, Period > &)
void dequeue (T &)
bool try_dequeue (T &item)
template<typename Rep , typename Period >
bool try_dequeue_for (T &, const std::chrono::duration< Rep, Period > &)
PCQ ()
template<typename... Args>
void enqueue (Args &&...args)
void dequeue (T &)
bool try_dequeue (T &item)
template<typename Rep , typename Period >
bool try_dequeue_for (T &, const std::chrono::duration< Rep, Period > &) noexcept
Private Attributes
folly::ProducerConsumerQueue< T > q_
Detailed Description
template<typename T>
class PCQ< T >
Definition at line 477 of file DynamicBoundedQueueTest.cpp.
Constructor & Destructor Documentation
template<typename T > PCQ< T >::PCQ (uint64_t capacity) inline explicit
Definition at line 481 of file DynamicBoundedQueueTest.cpp.
 : q_(capacity) {}
template<typename T > PCQ< T >::PCQ () inline
Definition at line 432 of file UnboundedQueueTest.cpp.
References testing::Args().
 : q_(FLAGS_capacity) {}
Member Function Documentation
template<typename T > void PCQ< T >::dequeue (T &) inline
Definition at line 441 of file UnboundedQueueTest.cpp.
References ASSERT_TRUE.
                    {
     ASSERT_TRUE(false);
   }
template<typename T > void PCQ< T >::dequeue (T &) inline
Definition at line 500 of file DynamicBoundedQueueTest.cpp.
References ASSERT_TRUE.
                    {
     ASSERT_TRUE(false);
   }
template<typename T > template<typename... Args> void PCQ< T >::enqueue (Args &&... args) inline
Definition at line 435 of file UnboundedQueueTest.cpp.
References folly::ProducerConsumerQueue< T >::write().
{
     while (!q_.write(std::forward<Args>(args)...)) {
       /* keep trying*/;
     }
   }
template<typename T > void PCQ< T >::enqueue (const T &) inline
Definition at line 483 of file DynamicBoundedQueueTest.cpp.
References ASSERT_TRUE.
{
     ASSERT_TRUE(false);
   }
template<typename T > bool PCQ< T >::try_dequeue (T & item) inline
Definition at line 445 of file UnboundedQueueTest.cpp.
References folly::ProducerConsumerQueue< T >::read().
{
     return q_.read(item);
   }
template<typename T > bool PCQ< T >::try_dequeue (T & item) inline
Definition at line 504 of file DynamicBoundedQueueTest.cpp.
References folly::ProducerConsumerQueue< T >::read().
{
     return q_.read(item);
   }
template<typename T > template<typename Rep , typename Period > bool PCQ< T >::try_dequeue_for (T & , const std::chrono::duration< Rep, Period > &) inline noexcept
Definition at line 450 of file UnboundedQueueTest.cpp.
{
     return false;
   }
template<typename T > template<typename Rep , typename Period > bool PCQ< T >::try_dequeue_for (T & , const std::chrono::duration< Rep, Period > &) inline
Definition at line 509 of file DynamicBoundedQueueTest.cpp.
{
     return false;
   }
template<typename T > bool PCQ< T >::try_enqueue (const T & v) inline
Definition at line 487 of file DynamicBoundedQueueTest.cpp.
References folly::ProducerConsumerQueue< T >::write().
{
     return q_.write(v);
   }
template<typename T > bool PCQ< T >::try_enqueue (T && v) inline
Definition at line 491 of file DynamicBoundedQueueTest.cpp.
References folly::gen::move, and folly::ProducerConsumerQueue< T >::write().
{
     return q_.write(std::move(v));
   }
template<typename T > template<typename Rep , typename Period > bool PCQ< T >::try_enqueue_for (const T & , const std::chrono::duration< Rep, Period > &) inline
Definition at line 496 of file DynamicBoundedQueueTest.cpp.
{
     return false;
   }
Member Data Documentation
template<typename T > folly::ProducerConsumerQueue< T > PCQ< T >::q_ private
Definition at line 478 of file DynamicBoundedQueueTest.cpp.
The documentation for this class was generated from the following files:
proxygen/folly/folly/concurrency/test/DynamicBoundedQueueTest.cpp
proxygen/folly/folly/concurrency/test/UnboundedQueueTest.cpp