proxygen: folly::pushmi::any_flow_receiver< PE, PV, E, VN > Class Template Reference
folly::pushmi::any_flow_receiver< PE, PV, E, VN > Class Template Reference
#include <flow_receiver.h>
Classes
union data
struct vtable
Public Types
using properties = property_set< is_receiver<>, is_flow<>>
Public Member Functions
any_flow_receiver ()=default
any_flow_receiver (any_flow_receiver &&that) noexcept
requires FlowUpTo< wrapped_t< Wrapped >, any_receiver< PE, PV > > &&ReceiveValue< wrapped_t< Wrapped >, VN... > &&ReceiveError< wrapped_t< Wrapped >, E > any_flow_receiver (Wrapped obj) noexcept(insitu< Wrapped >())
~any_flow_receiver ()
any_flow_receiver & operator= (any_flow_receiver &&that) noexcept
void value (VN...vn)
void error (E e) noexcept
void done ()
void starting (any_receiver< PE, PV > up)
Private Types
template<class T , class U = std::decay_t<T>>
using wrapped_t = std::enable_if_t<!std::is_same< U, any_flow_receiver >::value, U >
Private Member Functions
template<class Wrapped >
any_flow_receiver (Wrapped obj, std::false_type)
template<class Wrapped >
any_flow_receiver (Wrapped obj, std::true_type) noexcept
Static Private Member Functions
template<class Wrapped >
static constexpr bool insitu ()
Private Attributes
bool done_ = false
bool started_ = false
union folly::pushmi::any_flow_receiver::data data_
vtable const * vptr_ = &noop_
Static Private Attributes
static constexpr vtable const noop_ {}
Detailed Description
template<class PE, class PV, class E, class... VN>
class folly::pushmi::any_flow_receiver< PE, PV, E, VN >
Definition at line 24 of file flow_receiver.h.
Member Typedef Documentation
template<class PE, class PV, class E, class... VN> using folly::pushmi::any_flow_receiver< PE, PV, E, VN >::properties = property_set<is_receiver<>, is_flow<>>
Definition at line 105 of file flow_receiver.h.
template<class PE, class PV, class E, class... VN> template<class T , class U = std::decay_t<T>> using folly::pushmi::any_flow_receiver< PE, PV, E, VN >::wrapped_t = std::enable_if_t<!std::is_same<U, any_flow_receiver>::value, U> private
Definition at line 103 of file flow_receiver.h.
Constructor & Destructor Documentation
template<class PE, class PV, class E, class... VN> template<class Wrapped > folly::pushmi::any_flow_receiver< PE, PV, E, VN >::any_flow_receiver (Wrapped obj, std::false_type) inline private
Definition at line 51 of file flow_receiver.h.
References upload::const, folly::pushmi::any_flow_receiver< PE, PV, E, VN >::data_, folly::pushmi::any_flow_receiver< PE, PV, E, VN >::done(), folly::pushmi::operators::error(), folly::pushmi::any_flow_receiver< PE, PV, E, VN >::error(), folly::exchange(), folly::gen::move, folly::pushmi::__adl::noexcept(), folly::pushmi::any_flow_receiver< PE, PV, E, VN >::data::pobj_, s, folly::pushmi::set_done, folly::pushmi::set_error, folly::pushmi::set_starting, folly::pushmi::set_value, folly::pushmi::any_flow_receiver< PE, PV, E, VN >::starting(), value, and folly::pushmi::any_flow_receiver< PE, PV, E, VN >::value().
                                                 : any_flow_receiver() {
     struct s {
       static void op(data& src, data* dst) {
         if (dst)
           dst->pobj_ = std::exchange(src.pobj_, nullptr);
         delete static_cast<Wrapped const*>(src.pobj_);
       }
       static void done(data& src) {
         set_done(*static_cast<Wrapped*>(src.pobj_));
       }
       static void error(data& src, E e) noexcept {
         set_error(*static_cast<Wrapped*>(src.pobj_), std::move(e));
       }
       static void value(data& src, VN... vn) {
         set_value(*static_cast<Wrapped*>(src.pobj_), std::move(vn)...);
       }
       static void starting(data& src, any_receiver<PE, PV> up) {
         set_starting(*static_cast<Wrapped*>(src.pobj_), std::move(up));
       }
     };
     static const vtable vtbl{s::op, s::done, s::error, s::value, s::starting};
     data_.pobj_ = new Wrapped(std::move(obj));
     vptr_ = &vtbl;
   }
template<class PE, class PV, class E, class... VN> template<class Wrapped > folly::pushmi::any_flow_receiver< PE, PV, E, VN >::any_flow_receiver (Wrapped obj, std::true_type) inline private noexcept
Definition at line 76 of file flow_receiver.h.
References folly::pushmi::any_flow_receiver< PE, PV, E, VN >::data::buffer_, upload::const, folly::pushmi::any_flow_receiver< PE, PV, E, VN >::data_, folly::pushmi::any_flow_receiver< PE, PV, E, VN >::done(), folly::pushmi::operators::error(), folly::pushmi::any_flow_receiver< PE, PV, E, VN >::error(), folly::gen::move, folly::pushmi::__adl::noexcept(), s, folly::pushmi::set_done, folly::pushmi::set_error, folly::pushmi::set_starting, folly::pushmi::set_value, folly::pushmi::any_flow_receiver< PE, PV, E, VN >::starting(), value, and folly::pushmi::any_flow_receiver< PE, PV, E, VN >::value().
                                                         : any_flow_receiver() {
     struct s {
       static void op(data& src, data* dst) {
         if (dst)
           new (dst->buffer_) Wrapped(
               std::move(*static_cast<Wrapped*>((void*)src.buffer_)));
         static_cast<Wrapped const*>((void*)src.buffer_)->~Wrapped();
       }
       static void done(data& src) {
         set_done(*static_cast<Wrapped*>((void*)src.buffer_));
       }
       static void error(data& src, E e) noexcept {
         set_error(*static_cast<Wrapped*>((void*)src.buffer_), std::move(e));
       }
       static void value(data& src, VN... vn) {
         set_value(*static_cast<Wrapped*>((void*)src.buffer_), std::move(vn)...);
       }
       static void starting(data& src, any_receiver<PE, PV> up) {
         set_starting(*static_cast<Wrapped*>((void*)src.buffer_), std::move(up));
       }
     };
     static const vtable vtbl{s::op, s::done, s::error, s::value, s::starting};
     new (data_.buffer_) Wrapped(std::move(obj));
     vptr_ = &vtbl;
   }
template<class PE, class PV, class E, class... VN> folly::pushmi::any_flow_receiver< PE, PV, E, VN >::any_flow_receiver () default
Referenced by folly::pushmi::any_flow_receiver< PE, PV, E, VN >::operator=().
template<class PE, class PV, class E, class... VN> folly::pushmi::any_flow_receiver< PE, PV, E, VN >::any_flow_receiver (any_flow_receiver< PE, PV, E, VN > && that) inline noexcept
Definition at line 108 of file flow_receiver.h.
References folly::pushmi::any_flow_receiver< PE, PV, E, VN >::data_, folly::pushmi::any_flow_receiver< PE, PV, E, VN >::vtable::op_, folly::pushmi::PUSHMI_TEMPLATE(), folly::pushmi::requires(), folly::f14::swap(), and folly::pushmi::any_flow_receiver< PE, PV, E, VN >::vptr_.
                                                        : any_flow_receiver() {
     that.vptr_->op_(that.data_, &data_);
     std::swap(that.vptr_, vptr_);
   }
template<class PE, class PV, class E, class... VN> requires FlowUpTo<wrapped_t<Wrapped>, any_receiver<PE, PV> >&& ReceiveValue<wrapped_t<Wrapped>, VN...>&& ReceiveError<wrapped_t<Wrapped>, E> folly::pushmi::any_flow_receiver< PE, PV, E, VN >::any_flow_receiver (Wrapped obj) inline explicit noexcept
Definition at line 116 of file flow_receiver.h.
References folly::gen::move.
     : any_flow_receiver{std::move(obj), bool_<insitu<Wrapped>()>{}} {}
template<class PE, class PV, class E, class... VN> folly::pushmi::any_flow_receiver< PE, PV, E, VN >::~any_flow_receiver () inline
Definition at line 118 of file flow_receiver.h.
References folly::pushmi::any_flow_receiver< PE, PV, E, VN >::data_, and folly::pushmi::any_flow_receiver< PE, PV, E, VN >::vtable::op_.
Referenced by folly::pushmi::any_flow_receiver< PE, PV, E, VN >::operator=().
{
     vptr_->op_(data_, nullptr);
   }
Member Function Documentation
template<class PE, class PV, class E, class... VN> void folly::pushmi::any_flow_receiver< PE, PV, E, VN >::done () inline
Definition at line 137 of file flow_receiver.h.
References folly::pushmi::any_flow_receiver< PE, PV, E, VN >::data_, and folly::pushmi::any_flow_receiver< PE, PV, E, VN >::vtable::done_.
Referenced by folly::pushmi::any_flow_receiver< PE, PV, E, VN >::any_flow_receiver().
               {
     if (!started_) {std::abort();}
     if (done_){ return; }
     done_ = true;
     vptr_->done_(data_);
   }
template<class PE, class PV, class E, class... VN> void folly::pushmi::any_flow_receiver< PE, PV, E, VN >::error (E e) inline noexcept
Definition at line 131 of file flow_receiver.h.
References folly::pushmi::any_flow_receiver< PE, PV, E, VN >::data_, folly::pushmi::any_flow_receiver< PE, PV, E, VN >::vtable::error_, and folly::gen::move.
Referenced by folly::pushmi::any_flow_receiver< PE, PV, E, VN >::any_flow_receiver().
{
     if (!started_) {std::abort();}
     if (done_){ return; }
     done_ = true;
     vptr_->error_(data_, std::move(e));
   }
template<class PE, class PV, class E, class... VN> template<class Wrapped > static constexpr bool folly::pushmi::any_flow_receiver< PE, PV, E, VN >::insitu () inline static private
Definition at line 32 of file flow_receiver.h.
References folly::pushmi::any_flow_receiver< PE, PV, E, VN >::data::buffer_, and value.
{
     return sizeof(Wrapped) <= sizeof(data::buffer_) &&
         std::is_nothrow_move_constructible<Wrapped>::value;
   }
template<class PE, class PV, class E, class... VN> any_flow_receiver& folly::pushmi::any_flow_receiver< PE, PV, E, VN >::operator= (any_flow_receiver< PE, PV, E, VN > && that) inline noexcept
Definition at line 121 of file flow_receiver.h.
References folly::pushmi::any_flow_receiver< PE, PV, E, VN >::any_flow_receiver(), folly::gen::move, and folly::pushmi::any_flow_receiver< PE, PV, E, VN >::~any_flow_receiver().
{
     this->~any_flow_receiver();
     new ((void*)this) any_flow_receiver(std::move(that));
     return *this;
   }
template<class PE, class PV, class E, class... VN> void folly::pushmi::any_flow_receiver< PE, PV, E, VN >::starting (any_receiver< PE, PV > up) inline
Definition at line 144 of file flow_receiver.h.
References folly::pushmi::any_flow_receiver< PE, PV, E, VN >::data_, folly::gen::move, folly::pushmi::any_flow_receiver< PE, PV, E, VN >::noop_, folly::pushmi::requires(), and folly::pushmi::any_flow_receiver< PE, PV, E, VN >::vtable::starting_.
Referenced by folly::pushmi::any_flow_receiver< PE, PV, E, VN >::any_flow_receiver().
{
     if (started_) {std::abort();}
     started_ = true;
     vptr_->starting_(data_, std::move(up));
   }
template<class PE, class PV, class E, class... VN> void folly::pushmi::any_flow_receiver< PE, PV, E, VN >::value (VN... vn) inline
Definition at line 126 of file flow_receiver.h.
References folly::pushmi::any_flow_receiver< PE, PV, E, VN >::data_, folly::gen::move, and folly::pushmi::any_flow_receiver< PE, PV, E, VN >::vtable::value_.
Referenced by folly::pushmi::any_flow_receiver< PE, PV, E, VN >::any_flow_receiver().
{
     if (!started_) {std::abort();}
     if (done_){ return; }
     vptr_->value_(data_, std::move(vn)...);
   }
Member Data Documentation
template<class PE, class PV, class E, class... VN> union folly::pushmi::any_flow_receiver::data folly::pushmi::any_flow_receiver< PE, PV, E, VN >::data_ private
Referenced by folly::pushmi::any_flow_receiver< PE, PV, E, VN >::any_flow_receiver(), folly::pushmi::flow_receiver< Data, DVF, DEF, DDF, DStrtF >::data(), folly::pushmi::any_flow_receiver< PE, PV, E, VN >::done(), folly::pushmi::any_flow_receiver< PE, PV, E, VN >::error(), folly::pushmi::flow_receiver< Data, DVF, DEF, DDF, DStrtF >::flow_receiver(), folly::pushmi::any_flow_receiver< PE, PV, E, VN >::starting(), folly::pushmi::any_flow_receiver< PE, PV, E, VN >::value(), and folly::pushmi::any_flow_receiver< PE, PV, E, VN >::~any_flow_receiver().
template<class PE, class PV, class E, class... VN> bool folly::pushmi::any_flow_receiver< PE, PV, E, VN >::done_ = false private
Definition at line 25 of file flow_receiver.h.
template<class PE, class PV, class E, class... VN> constexpr any_flow_receiver< PE, PV, E, VN... >::vtable const folly::pushmi::any_flow_receiver< PE, PV, E, VN >::noop_ {} static private
Definition at line 48 of file flow_receiver.h.
Referenced by folly::pushmi::any_flow_receiver< PE, PV, E, VN >::starting().
template<class PE, class PV, class E, class... VN> bool folly::pushmi::any_flow_receiver< PE, PV, E, VN >::started_ = false private
Definition at line 26 of file flow_receiver.h.
template<class PE, class PV, class E, class... VN> vtable const* folly::pushmi::any_flow_receiver< PE, PV, E, VN >::vptr_ = &noop_ private
Definition at line 49 of file flow_receiver.h.
Referenced by folly::pushmi::any_flow_receiver< PE, PV, E, VN >::any_flow_receiver().
The documentation for this class was generated from the following file:
proxygen/folly/folly/experimental/pushmi/flow_receiver.h