proxygen: gmock_output_test.GMockOutputTest Class Reference
gmock_output_test.GMockOutputTest Class Reference
Public Member Functions
def testOutput (self)
def testOutput (self)
def testOutput (self)
Detailed Description
Definition at line 156 of file gmock_output_test.py.
Member Function Documentation
def gmock_output_test.GMockOutputTest.testOutput (self)
Definition at line 157 of file gmock_output_test.py.
References gmock_output_test.GetNormalizedCommandOutputAndLeakyTests().
Referenced by gmock_output_test.GMockOutputTest.testOutput().
   def testOutput(self):
     (output, leaky_tests) = GetNormalizedCommandOutputAndLeakyTests(COMMAND)
     golden_file = open(GOLDEN_PATH, 'rb')
     golden = golden_file.read()
     golden_file.close()
     # The normalized output should match the golden file.
     self.assertEquals(golden, output)
     # The raw output should contain 2 leaked mock object errors for
     # test GMockOutputTest.CatchesLeakedMocks.
     self.assertEquals(['GMockOutputTest.CatchesLeakedMocks',
                        'GMockOutputTest.CatchesLeakedMocks'],
                       leaky_tests)
def gmock_output_test.GMockOutputTest.testOutput (self)
Definition at line 157 of file gmock_output_test.py.
References gmock_output_test.GetNormalizedCommandOutputAndLeakyTests(), gmock_test_utils.Main(), and gmock_output_test.GMockOutputTest.testOutput().
   def testOutput(self):
     (output, leaky_tests) = GetNormalizedCommandOutputAndLeakyTests(COMMAND)
     golden_file = open(GOLDEN_PATH, 'rb')
     golden = golden_file.read()
     golden_file.close()
     # The normalized output should match the golden file.
     self.assertEquals(golden, output)
     # The raw output should contain 2 leaked mock object errors for
     # test GMockOutputTest.CatchesLeakedMocks.
     self.assertEquals(['GMockOutputTest.CatchesLeakedMocks',
                        'GMockOutputTest.CatchesLeakedMocks'],
                       leaky_tests)
def gmock_output_test.GMockOutputTest.testOutput (self)
Definition at line 157 of file gmock_output_test.py.
References gmock_output_test.GetNormalizedCommandOutputAndLeakyTests(), gmock_test_utils.Main(), and gmock_output_test.GMockOutputTest.testOutput().
   def testOutput(self):
     (output, leaky_tests) = GetNormalizedCommandOutputAndLeakyTests(COMMAND)
     golden_file = open(GOLDEN_PATH, 'rb')
     golden = golden_file.read()
     golden_file.close()
     # The normalized output should match the golden file.
     self.assertEquals(golden, output)
     # The raw output should contain 2 leaked mock object errors for
     # test GMockOutputTest.CatchesLeakedMocks.
     self.assertEquals(['GMockOutputTest.CatchesLeakedMocks',
                        'GMockOutputTest.CatchesLeakedMocks'],
                       leaky_tests)
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock_output_test.py