proxygen: folly::FormatValue< T, typename std::enable_if< std::is_integral< T >::value &&!std::is_same< T, bool >::value >::type > Class Template Reference
folly::FormatValue< T, typename std::enable_if< std::is_integral< T >::value &&!std::is_same< T, bool >::value >::type > Class Template Reference
#include <Format-inl.h>
Public Member Functions
FormatValue (T val)
T getValue () const
template<class FormatCallback >
void format (FormatArg &arg, FormatCallback &cb) const
template<class FormatCallback >
void doFormat (FormatArg &arg, FormatCallback &cb) const
Private Attributes
T val_
Detailed Description
template<class T>
class folly::FormatValue< T, typename std::enable_if< std::is_integral< T >::value &&!std::is_same< T, bool >::value >::type >
Definition at line 423 of file Format-inl.h.
Constructor & Destructor Documentation
template<class T > folly::FormatValue< T, typename std::enable_if< std::is_integral< T >::value &&!std::is_same< T, bool >::value >::type >::FormatValue (T val) inline explicit
Definition at line 428 of file Format-inl.h.
 : val_(val) {}
Member Function Documentation
template<class T > template<class FormatCallback > void folly::FormatValue< T, typename std::enable_if< std::is_integral< T >::value &&!std::is_same< T, bool >::value >::type >::doFormat (FormatArg & arg, FormatCallback & cb) const inline
Definition at line 441 of file Format-inl.h.
References folly::FormatArg::basePrefix, folly::FormatArg::enforce(), folly::FormatArg::error(), folly::format_value::formatNumber(), folly::detail::insertThousandsGroupingUnsafe(), folly::is_negative(), folly::FormatArg::presentation, folly::FormatArg::sign, folly::FormatArg::thousandsSeparator, type, folly::uint64ToBufferUnsafe(), folly::detail::uintToBinary(), folly::detail::uintToHexLower(), folly::detail::uintToHexUpper(), folly::detail::uintToOctal(), and value.
{
     char presentation = arg.presentation;
     if (presentation == FormatArg::kDefaultPresentation) {
       presentation = std::is_same<T, char>::value ? 'c' : 'd';
     }
     // Do all work as unsigned, we'll add the prefix ('0' or '0x' if necessary)
     // and sign ourselves.
     typedef typename std::make_unsigned<T>::type UT;
     UT uval;
     char sign;
     if (std::is_signed<T>::value) {
       if (folly::is_negative(val_)) {
         uval = UT(-static_cast<UT>(val_));
         sign = '-';
       } else {
         uval = static_cast<UT>(val_);
         switch (arg.sign) {
           case FormatArg::Sign::PLUS_OR_MINUS:
             sign = '+';
             break;
           case FormatArg::Sign::SPACE_OR_MINUS:
             sign = ' ';
             break;
           default:
             sign = '\0';
             break;
         }
       }
     } else {
       uval = static_cast<UT>(val_);
       sign = '\0';
       arg.enforce(
           arg.sign == FormatArg::Sign::DEFAULT,
           "sign specifications not allowed for unsigned values");
     }
     // max of:
     // #x: 0x prefix + 16 bytes = 18 bytes
     // #o: 0 prefix + 22 bytes = 23 bytes
     // #b: 0b prefix + 64 bytes = 65 bytes
     // ,d: 26 bytes (including thousands separators!)
     // + nul terminator
     // + 3 for sign and prefix shenanigans (see below)
     constexpr size_t valBufSize = 69;
     char valBuf[valBufSize];
     char* valBufBegin = nullptr;
     char* valBufEnd = nullptr;
     int prefixLen = 0;
     switch (presentation) {
       case 'n': {
         arg.enforce(
             !arg.basePrefix,
             "base prefix not allowed with '",
             presentation,
             "' specifier");
         arg.enforce(
             !arg.thousandsSeparator,
             "cannot use ',' with the '",
             presentation,
             "' specifier");
         valBufBegin = valBuf + 3; // room for sign and base prefix
 #if defined(__ANDROID__)
         int len = snprintf(
             valBufBegin,
             (valBuf + valBufSize) - valBufBegin,
             "%" PRIuMAX,
             static_cast<uintmax_t>(uval));
 #else
         int len = snprintf(
             valBufBegin,
             size_t((valBuf + valBufSize) - valBufBegin),
             "%ju",
             static_cast<uintmax_t>(uval));
 #endif
         // valBufSize should always be big enough, so this should never
         // happen.
         assert(len < valBuf + valBufSize - valBufBegin);
         valBufEnd = valBufBegin + len;
         break;
       }
       case 'd':
         arg.enforce(
             !arg.basePrefix,
             "base prefix not allowed with '",
             presentation,
             "' specifier");
         valBufBegin = valBuf + 3; // room for sign and base prefix
         // Use uintToBuffer, faster than sprintf
         valBufEnd = valBufBegin + uint64ToBufferUnsafe(uval, valBufBegin);
         if (arg.thousandsSeparator) {
           detail::insertThousandsGroupingUnsafe(valBufBegin, &valBufEnd);
         }
         break;
       case 'c':
         arg.enforce(
             !arg.basePrefix,
             "base prefix not allowed with '",
             presentation,
             "' specifier");
         arg.enforce(
             !arg.thousandsSeparator,
             "thousands separator (',') not allowed with '",
             presentation,
             "' specifier");
         valBufBegin = valBuf + 3;
         *valBufBegin = static_cast<char>(uval);
         valBufEnd = valBufBegin + 1;
         break;
       case 'o':
       case 'O':
         arg.enforce(
             !arg.thousandsSeparator,
             "thousands separator (',') not allowed with '",
             presentation,
             "' specifier");
         valBufEnd = valBuf + valBufSize - 1;
         valBufBegin =
             valBuf + detail::uintToOctal(valBuf, valBufSize - 1, uval);
         if (arg.basePrefix) {
           *--valBufBegin = '0';
           prefixLen = 1;
         }
         break;
       case 'x':
         arg.enforce(
             !arg.thousandsSeparator,
             "thousands separator (',') not allowed with '",
             presentation,
             "' specifier");
         valBufEnd = valBuf + valBufSize - 1;
         valBufBegin =
             valBuf + detail::uintToHexLower(valBuf, valBufSize - 1, uval);
         if (arg.basePrefix) {
           *--valBufBegin = 'x';
           *--valBufBegin = '0';
           prefixLen = 2;
         }
         break;
       case 'X':
         arg.enforce(
             !arg.thousandsSeparator,
             "thousands separator (',') not allowed with '",
             presentation,
             "' specifier");
         valBufEnd = valBuf + valBufSize - 1;
         valBufBegin =
             valBuf + detail::uintToHexUpper(valBuf, valBufSize - 1, uval);
         if (arg.basePrefix) {
           *--valBufBegin = 'X';
           *--valBufBegin = '0';
           prefixLen = 2;
         }
         break;
       case 'b':
       case 'B':
         arg.enforce(
             !arg.thousandsSeparator,
             "thousands separator (',') not allowed with '",
             presentation,
             "' specifier");
         valBufEnd = valBuf + valBufSize - 1;
         valBufBegin =
             valBuf + detail::uintToBinary(valBuf, valBufSize - 1, uval);
         if (arg.basePrefix) {
           *--valBufBegin = presentation; // 0b or 0B
           *--valBufBegin = '0';
           prefixLen = 2;
         }
         break;
       default:
         arg.error("invalid specifier '", presentation, "'");
     }
     if (sign) {
       *--valBufBegin = sign;
       ++prefixLen;
     }
     format_value::formatNumber(
         StringPiece(valBufBegin, valBufEnd), prefixLen, arg, cb);
   }
template<class T > template<class FormatCallback > void folly::FormatValue< T, typename std::enable_if< std::is_integral< T >::value &&!std::is_same< T, bool >::value >::type >::format (FormatArg & arg, FormatCallback & cb) const inline
Definition at line 435 of file Format-inl.h.
References folly::FormatArg::validate().
{
     arg.validate(FormatArg::Type::INTEGER);
     doFormat(arg, cb);
   }
template<class T > T folly::FormatValue< T, typename std::enable_if< std::is_integral< T >::value &&!std::is_same< T, bool >::value >::type >::getValue () const inline
Definition at line 430 of file Format-inl.h.
                      {
     return val_;
   }
Member Data Documentation
template<class T > T folly::FormatValue< T, typename std::enable_if< std::is_integral< T >::value &&!std::is_same< T, bool >::value >::type >::val_ private
Definition at line 630 of file Format-inl.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/Format-inl.h