proxygen: testing::internal::FloatingEqMatcher< FloatType > Class Template Reference
testing::internal::FloatingEqMatcher< FloatType > Class Template Reference
#include <gmock-matchers.h>
Classes
class Impl
Public Member Functions
FloatingEqMatcher (FloatType expected, bool nan_eq_nan)
FloatingEqMatcher (FloatType expected, bool nan_eq_nan, FloatType max_abs_error)
operator Matcher< FloatType > () const
operator Matcher< const FloatType & > () const
operator Matcher< FloatType & > () const
FloatingEqMatcher (FloatType expected, bool nan_eq_nan)
FloatingEqMatcher (FloatType expected, bool nan_eq_nan, FloatType max_abs_error)
operator Matcher< FloatType > () const
operator Matcher< const FloatType & > () const
operator Matcher< FloatType & > () const
FloatingEqMatcher (FloatType expected, bool nan_eq_nan)
FloatingEqMatcher (FloatType expected, bool nan_eq_nan, FloatType max_abs_error)
operator Matcher< FloatType > () const
operator Matcher< const FloatType & > () const
operator Matcher< FloatType & > () const
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (FloatingEqMatcher)
GTEST_DISALLOW_ASSIGN_ (FloatingEqMatcher)
GTEST_DISALLOW_ASSIGN_ (FloatingEqMatcher)
Private Attributes
const FloatType expected_
const bool nan_eq_nan_
const FloatType max_abs_error_
Detailed Description
template<typename FloatType>
class testing::internal::FloatingEqMatcher< FloatType >
Definition at line 1888 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename FloatType> testing::internal::FloatingEqMatcher< FloatType >::FloatingEqMatcher (FloatType expected, bool nan_eq_nan) inline
Definition at line 1896 of file gmock-matchers.h.
                                                          :
     expected_(expected), nan_eq_nan_(nan_eq_nan), max_abs_error_(-1) {
   }
template<typename FloatType> testing::internal::FloatingEqMatcher< FloatType >::FloatingEqMatcher (FloatType expected, bool nan_eq_nan, FloatType max_abs_error) inline
Definition at line 1903 of file gmock-matchers.h.
References GTEST_CHECK_.
       : expected_(expected),
         nan_eq_nan_(nan_eq_nan),
         max_abs_error_(max_abs_error) {
     GTEST_CHECK_(max_abs_error >= 0)
         << ", where max_abs_error is" << max_abs_error;
   }
template<typename FloatType> testing::internal::FloatingEqMatcher< FloatType >::FloatingEqMatcher (FloatType expected, bool nan_eq_nan) inline
Definition at line 1896 of file gmock-matchers.h.
                                                          :
     expected_(expected), nan_eq_nan_(nan_eq_nan), max_abs_error_(-1) {
   }
template<typename FloatType> testing::internal::FloatingEqMatcher< FloatType >::FloatingEqMatcher (FloatType expected, bool nan_eq_nan, FloatType max_abs_error) inline
Definition at line 1903 of file gmock-matchers.h.
References GTEST_CHECK_.
       : expected_(expected),
         nan_eq_nan_(nan_eq_nan),
         max_abs_error_(max_abs_error) {
     GTEST_CHECK_(max_abs_error >= 0)
         << ", where max_abs_error is" << max_abs_error;
   }
template<typename FloatType> testing::internal::FloatingEqMatcher< FloatType >::FloatingEqMatcher (FloatType expected, bool nan_eq_nan) inline
Definition at line 1896 of file gmock-matchers.h.
                                                          :
     expected_(expected), nan_eq_nan_(nan_eq_nan), max_abs_error_(-1) {
   }
template<typename FloatType> testing::internal::FloatingEqMatcher< FloatType >::FloatingEqMatcher (FloatType expected, bool nan_eq_nan, FloatType max_abs_error) inline
Definition at line 1903 of file gmock-matchers.h.
References GTEST_CHECK_.
       : expected_(expected),
         nan_eq_nan_(nan_eq_nan),
         max_abs_error_(max_abs_error) {
     GTEST_CHECK_(max_abs_error >= 0)
         << ", where max_abs_error is" << max_abs_error;
   }
Member Function Documentation
template<typename FloatType> testing::internal::FloatingEqMatcher< FloatType >::GTEST_DISALLOW_ASSIGN_ (FloatingEqMatcher< FloatType >) private
template<typename FloatType> testing::internal::FloatingEqMatcher< FloatType >::GTEST_DISALLOW_ASSIGN_ (FloatingEqMatcher< FloatType >) private
template<typename FloatType> testing::internal::FloatingEqMatcher< FloatType >::GTEST_DISALLOW_ASSIGN_ (FloatingEqMatcher< FloatType >) private
template<typename FloatType> testing::internal::FloatingEqMatcher< FloatType >::operator Matcher< const FloatType & > () const inline
Definition at line 2021 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(
         new Impl<const FloatType&>(expected_, nan_eq_nan_, max_abs_error_));
   }
template<typename FloatType> testing::internal::FloatingEqMatcher< FloatType >::operator Matcher< const FloatType & > () const inline
Definition at line 2021 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(
         new Impl<const FloatType&>(expected_, nan_eq_nan_, max_abs_error_));
   }
template<typename FloatType> testing::internal::FloatingEqMatcher< FloatType >::operator Matcher< const FloatType & > () const inline
Definition at line 2021 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(
         new Impl<const FloatType&>(expected_, nan_eq_nan_, max_abs_error_));
   }
template<typename FloatType> testing::internal::FloatingEqMatcher< FloatType >::operator Matcher< FloatType & > () const inline
Definition at line 2026 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, and testing::MakeMatcher().
{
     return MakeMatcher(
         new Impl<FloatType&>(expected_, nan_eq_nan_, max_abs_error_));
   }
template<typename FloatType> testing::internal::FloatingEqMatcher< FloatType >::operator Matcher< FloatType & > () const inline
Definition at line 2026 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(
         new Impl<FloatType&>(expected_, nan_eq_nan_, max_abs_error_));
   }
template<typename FloatType> testing::internal::FloatingEqMatcher< FloatType >::operator Matcher< FloatType & > () const inline
Definition at line 2026 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, and testing::MakeMatcher().
{
     return MakeMatcher(
         new Impl<FloatType&>(expected_, nan_eq_nan_, max_abs_error_));
   }
template<typename FloatType> testing::internal::FloatingEqMatcher< FloatType >::operator Matcher< FloatType > () const inline
Definition at line 2016 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(
         new Impl<FloatType>(expected_, nan_eq_nan_, max_abs_error_));
   }
template<typename FloatType> testing::internal::FloatingEqMatcher< FloatType >::operator Matcher< FloatType > () const inline
Definition at line 2016 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(
         new Impl<FloatType>(expected_, nan_eq_nan_, max_abs_error_));
   }
template<typename FloatType> testing::internal::FloatingEqMatcher< FloatType >::operator Matcher< FloatType > () const inline
Definition at line 2016 of file gmock-matchers.h.
References testing::MakeMatcher().
{
     return MakeMatcher(
         new Impl<FloatType>(expected_, nan_eq_nan_, max_abs_error_));
   }
Member Data Documentation
template<typename FloatType> const FloatType testing::internal::FloatingEqMatcher< FloatType >::expected_ private
Definition at line 2032 of file gmock-matchers.h.
template<typename FloatType> const FloatType testing::internal::FloatingEqMatcher< FloatType >::max_abs_error_ private
Definition at line 2035 of file gmock-matchers.h.
template<typename FloatType> const bool testing::internal::FloatingEqMatcher< FloatType >::nan_eq_nan_ private
Definition at line 2033 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h