proxygen: fizz::JavaCryptoPeerCert Class Reference
fizz::JavaCryptoPeerCert Class Reference
#include <JavaCryptoPeerCert.h>
Public Member Functions
JavaCryptoPeerCert (Buf certData)
~JavaCryptoPeerCert () override=default
std::string getIdentity () const override
void verify (SignatureScheme scheme, CertificateVerifyContext context, folly::ByteRange toBeSigned, folly::ByteRange signature) const override
folly::ssl::X509UniquePtr getX509 () const override
Public Member Functions inherited from fizz::PeerCert
virtual ~PeerCert ()=default
Public Member Functions inherited from folly::AsyncTransportCertificate
virtual ~AsyncTransportCertificate ()=default
Static Public Member Functions
static void onLoad (JNIEnv *env)
Private Attributes
jobject jobject_
Detailed Description
Definition at line 21 of file JavaCryptoPeerCert.h.
Constructor & Destructor Documentation
fizz::JavaCryptoPeerCert::JavaCryptoPeerCert (Buf certData) explicit
Definition at line 30 of file JavaCryptoPeerCert.cpp.
References fizz::jni::createByteArray(), fizz::jni::getEnv(), jobject_, fizz::jni::maybeThrowException(), folly::gen::move, and fizz::jni::releaseEnv().
{
   bool shouldDetach;
   auto env = jni::getEnv(&shouldDetach);
   auto byteArray = jni::createByteArray(env, std::move(certData));
   jobject_ = env->NewObject(clazz, constructor, byteArray);
   env->DeleteLocalRef(byteArray);
   jni::maybeThrowException(env, shouldDetach);
   jni::releaseEnv(shouldDetach);
 }
fizz::JavaCryptoPeerCert::~JavaCryptoPeerCert () override default
Member Function Documentation
std::string fizz::JavaCryptoPeerCert::getIdentity () const override virtual
Returns the identity this certificate conveys.
An identity is an opaque string that may be used by the application for authentication or authorization purposes. The exact structure and semantics of the identity string are determined by concrete implementations of AsyncTransport.
Implements folly::AsyncTransportCertificate.
Definition at line 42 of file JavaCryptoPeerCert.cpp.
References fizz::jni::getEnv(), jobject_, fizz::jni::maybeThrowException(), fizz::jni::releaseEnv(), and string.
{
   bool shouldDetach;
   auto env = jni::getEnv(&shouldDetach);
   auto jIdentity = (jstring)env->CallObjectMethod(jobject_, getIdentityMethod);
   auto cIdentity = env->GetStringUTFChars(jIdentity, JNI_FALSE /* isCopy */);
   std::string identity{cIdentity};
   env->ReleaseStringUTFChars(jIdentity, cIdentity);
   jni::maybeThrowException(env, shouldDetach);
   jni::releaseEnv(shouldDetach);
   return identity;
 }
folly::ssl::X509UniquePtr fizz::JavaCryptoPeerCert::getX509 () const override virtual
Returns an X509 structure associated with this Certificate. This may be null.
Implements folly::AsyncTransportCertificate.
Definition at line 88 of file JavaCryptoPeerCert.cpp.
{
   return nullptr;
 }
void fizz::JavaCryptoPeerCert::onLoad (JNIEnv * env) static
Definition at line 21 of file JavaCryptoPeerCert.cpp.
References fizz::jni::getClass(), and fizz::jni::getMethodID().
Referenced by JNI_OnLoad().
{
   clazz = jni::getClass(env, "com/facebook/fizz/JavaCryptoPeerCert");
   constructor = jni::getMethodID(env, clazz, "<init>", "([B)V");
   getIdentityMethod =
       jni::getMethodID(env, clazz, "getIdentity", "()Ljava/lang/String;");
   verifyMethod =
       jni::getMethodID(env, clazz, "verify", "(Ljava/lang/String;[B[B)V");
 }
void fizz::JavaCryptoPeerCert::verify (SignatureScheme scheme, CertificateVerifyContext context, folly::ByteRange toBeSigned, folly::ByteRange signature) const override virtual
Verifies that signature is a valid signature of toBeSigned. Throws if it's not.
Implements fizz::PeerCert.
Definition at line 56 of file JavaCryptoPeerCert.cpp.
References fizz::jni::createByteArray(), fizz::ecdsa_secp256r1_sha256, fizz::jni::getEnv(), jobject_, fizz::jni::maybeThrowException(), folly::gen::move, fizz::CertUtils::prepareSignData(), fizz::jni::releaseEnv(), and string.
{
   bool shouldDetach;
   auto env = jni::getEnv(&shouldDetach);
   std::string algorithm;
   switch (scheme) {
     case SignatureScheme::ecdsa_secp256r1_sha256:
       algorithm = "SHA256withECDSA";
       break;
     default:
       throw std::runtime_error("Unsupported signature scheme");
   }
   auto jAlgorithm = env->NewStringUTF(algorithm.c_str());
   auto signData = CertUtils::prepareSignData(context, toBeSigned);
   auto jSignData = jni::createByteArray(env, std::move(signData));
   auto jSignature = jni::createByteArray(env, signature);
   env->CallObjectMethod(
       jobject_, verifyMethod, jAlgorithm, jSignData, jSignature);
   env->DeleteLocalRef(jSignature);
   env->DeleteLocalRef(jSignData);
   env->DeleteLocalRef(jAlgorithm);
   jni::maybeThrowException(env, shouldDetach);
   jni::releaseEnv(shouldDetach);
 }
Member Data Documentation
jobject fizz::JavaCryptoPeerCert::jobject_ private
Definition at line 41 of file JavaCryptoPeerCert.h.
Referenced by getIdentity(), JavaCryptoPeerCert(), and verify().
The documentation for this class was generated from the following files:
proxygen/fizz/fizz/extensions/javacrypto/JavaCryptoPeerCert.h
proxygen/fizz/fizz/extensions/javacrypto/JavaCryptoPeerCert.cpp