proxygen: fizz::extensions::test::ValidatorTest Class Reference
fizz::extensions::test::ValidatorTest Class Reference
Public Member Functions
void SetUp () override
TokenBinding setUpWithKeyParameters (TokenBindingKeyParameters params)
Buf getBuf (StringPiece hex)
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Public Attributes
Buf ekm_
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Protected Member Functions inherited from testing::Test
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Detailed Description
Definition at line 34 of file ValidatorTest.cpp.
Member Function Documentation
Buf fizz::extensions::test::ValidatorTest::getBuf (StringPiece hex) inline
Definition at line 59 of file ValidatorTest.cpp.
References folly::IOBuf::copyBuffer(), folly::data(), and folly::unhexlify().
{
     auto data = unhexlify(hex);
     return folly::IOBuf::copyBuffer(data.data(), data.size());
   }
void fizz::extensions::test::ValidatorTest::SetUp () inline override virtual
Reimplemented from testing::Test.
Definition at line 36 of file ValidatorTest.cpp.
References fizz::extensions::test::chrome_session_ekm.
{
     OpenSSL_add_all_algorithms();
     ekm_ = getBuf(chrome_session_ekm);
   }
TokenBinding fizz::extensions::test::ValidatorTest::setUpWithKeyParameters (TokenBindingKeyParameters params) inline
Definition at line 41 of file ValidatorTest.cpp.
References fizz::extensions::test::chrome_session_key, fizz::extensions::test::chrome_session_signature, folly::IOBuf::create(), fizz::extensions::TokenBinding::extensions, fizz::extensions::TokenBindingID::key_parameters, folly::gen::move, params, fizz::extensions::TokenBinding::signature, tokenBinding, fizz::extensions::TokenBinding::tokenbinding_type, and fizz::extensions::TokenBinding::tokenbindingid.
{
     TokenBinding tokenBinding;
     tokenBinding.tokenbinding_type = TokenBindingType::provided_token_binding;
     tokenBinding.extensions = folly::IOBuf::create(0);
     TokenBindingID id;
     id.key_parameters = params;
     switch (params) {
       case TokenBindingKeyParameters::ecdsap256: {
         id.key = getBuf(chrome_session_key);
         tokenBinding.tokenbindingid = std::move(id);
         tokenBinding.signature = getBuf(chrome_session_signature);
         return tokenBinding;
       }
       default: // rsa_pss and rsa_pkcs
         throw std::runtime_error("not implemented");
     }
   }
Member Data Documentation
Buf fizz::extensions::test::ValidatorTest::ekm_
Definition at line 64 of file ValidatorTest.cpp.
The documentation for this class was generated from the following file:
proxygen/fizz/fizz/extensions/tokenbinding/test/ValidatorTest.cpp