proxygen: folly::EventBase::SmoothLoopTime Class Reference
folly::EventBase::SmoothLoopTime Class Reference
#include <EventBase.h>
Public Member Functions
SmoothLoopTime (std::chrono::microseconds timeInterval)
void setTimeInterval (std::chrono::microseconds timeInterval)
void reset (double value=0.0)
void addSample (std::chrono::microseconds total, std::chrono::microseconds busy)
double get () const
void dampen (double factor)
Private Attributes
double expCoeff_
double value_
std::chrono::microseconds buffer_time_ {0}
std::chrono::microseconds busy_buffer_ {0}
std::size_t buffer_cnt_ {0}
Static Private Attributes
static constexpr std::chrono::milliseconds buffer_interval_ {10}
Detailed Description
Definition at line 553 of file EventBase.h.
Constructor & Destructor Documentation
folly::EventBase::SmoothLoopTime::SmoothLoopTime (std::chrono::microseconds timeInterval) inline explicit
Definition at line 555 of file EventBase.h.
References folly::value().
         : expCoeff_(-1.0 / timeInterval.count()), value_(0.0) {
       VLOG(11) << "expCoeff_ " << expCoeff_ << " " << __PRETTY_FUNCTION__;
     }
Member Function Documentation
void folly::EventBase::SmoothLoopTime::addSample (std::chrono::microseconds total, std::chrono::microseconds busy)
Definition at line 671 of file EventBase.cpp.
Referenced by folly::EventBase::loopBody().
{
   if ((buffer_time_ + total) > buffer_interval_ && buffer_cnt_ > 0) {
     // See https://en.wikipedia.org/wiki/Exponential_smoothing for
     // more info on this calculation.
     double coeff = exp(buffer_time_.count() * expCoeff_);
     value_ =
         value_ * coeff + (1.0 - coeff) * (busy_buffer_.count() / buffer_cnt_);
     buffer_time_ = std::chrono::microseconds{0};
     busy_buffer_ = std::chrono::microseconds{0};
     buffer_cnt_ = 0;
   }
   buffer_time_ += total;
   busy_buffer_ += busy;
   buffer_cnt_++;
 }
void folly::EventBase::SmoothLoopTime::dampen (double factor) inline
Definition at line 574 of file EventBase.h.
Referenced by folly::EventBase::loopBody().
{
       value_ *= factor;
     }
double folly::EventBase::SmoothLoopTime::get () const inline
Definition at line 567 of file EventBase.h.
Referenced by folly::EventBase::loopBody().
{
       // Add the outstanding buffered times linearly, to avoid
       // expensive exponentiation
       auto lcoeff = buffer_time_.count() * -expCoeff_;
       return value_ * (1.0 - lcoeff) + lcoeff * busy_buffer_.count();
     }
void folly::EventBase::SmoothLoopTime::reset (double value = 0.0)
Definition at line 667 of file EventBase.cpp.
References folly::value().
Referenced by folly::EventBase::resetLoadAvg().
{
   value_ = value;
 }
void folly::EventBase::SmoothLoopTime::setTimeInterval (std::chrono::microseconds timeInterval)
Definition at line 661 of file EventBase.cpp.
Referenced by folly::EventBase::setLoadAvgMsec().
{
   expCoeff_ = -1.0 / timeInterval.count();
   VLOG(11) << "expCoeff_ " << expCoeff_ << " " << __PRETTY_FUNCTION__;
 }
Member Data Documentation
std::size_t folly::EventBase::SmoothLoopTime::buffer_cnt_ {0} private
Definition at line 583 of file EventBase.h.
constexpr std::chrono::milliseconds folly::EventBase::SmoothLoopTime::buffer_interval_ {10} static private
Definition at line 584 of file EventBase.h.
Referenced by folly::EventBase::getEventBase().
std::chrono::microseconds folly::EventBase::SmoothLoopTime::buffer_time_ {0} private
Definition at line 581 of file EventBase.h.
std::chrono::microseconds folly::EventBase::SmoothLoopTime::busy_buffer_ {0} private
Definition at line 582 of file EventBase.h.
double folly::EventBase::SmoothLoopTime::expCoeff_ private
Definition at line 579 of file EventBase.h.
double folly::EventBase::SmoothLoopTime::value_ private
Definition at line 580 of file EventBase.h.
The documentation for this class was generated from the following files:
proxygen/folly/folly/io/async/EventBase.h
proxygen/folly/folly/io/async/EventBase.cpp