proxygen: SimpleDigest< MergeSize > Class Template Reference
SimpleDigest< MergeSize > Class Template Reference
Public Member Functions
SimpleDigest (size_t sz)
SimpleDigest merge (Range< const double * > r) const
std::vector< double > getValues () const
bool empty () const
SimpleDigest (size_t sz)
SimpleDigest merge (Range< const double * > r) const
int64_t getSize () const
Static Public Member Functions
static SimpleDigest merge (Range< const SimpleDigest * > r)
static SimpleDigest merge (Range< const SimpleDigest * > r)
Private Attributes
std::vector< double > values_
int64_t sz_
Detailed Description
template<size_t MergeSize>
class SimpleDigest< MergeSize >
Definition at line 39 of file BufferedStatTest.cpp.
Constructor & Destructor Documentation
template<size_t MergeSize> SimpleDigest< MergeSize >::SimpleDigest (size_t sz) inline explicit
Definition at line 41 of file BufferedStatTest.cpp.
References EXPECT_EQ, and kDigestSize.
{
     EXPECT_EQ(kDigestSize, sz);
   }
template<size_t MergeSize> SimpleDigest< MergeSize >::SimpleDigest (size_t sz) inline explicit
Definition at line 32 of file DigestBuilderTest.cpp.
 : sz_(sz) {}
Member Function Documentation
template<size_t MergeSize> bool SimpleDigest< MergeSize >::empty () const inline
Definition at line 69 of file BufferedStatTest.cpp.
                      {
     return values_.empty();
   }
template<size_t MergeSize> int64_t SimpleDigest< MergeSize >::getSize () const inline
Definition at line 47 of file DigestBuilderTest.cpp.
{
     return sz_;
   }
template<size_t MergeSize> std::vector<double> SimpleDigest< MergeSize >::getValues () const inline
Definition at line 65 of file BufferedStatTest.cpp.
{
     return values_;
   }
template<size_t MergeSize> SimpleDigest SimpleDigest< MergeSize >::merge (Range< const double * > r) const inline
Definition at line 34 of file DigestBuilderTest.cpp.
References EXPECT_EQ, EXPECT_GE, i, and folly::Range< Iter >::size().
{
     EXPECT_EQ(MergeSize, r.size());
     for (size_t i = 0; i < MergeSize; ++i) {
       EXPECT_GE(MergeSize, r[i]);
     }
     return *this;
   }
template<size_t MergeSize> static SimpleDigest SimpleDigest< MergeSize >::merge (Range< const SimpleDigest< MergeSize > * > r) inline static
Definition at line 42 of file DigestBuilderTest.cpp.
References folly::Range< Iter >::begin(), EXPECT_EQ, and folly::Range< Iter >::size().
{
     EXPECT_EQ(1, r.size());
     return *r.begin();
   }
template<size_t MergeSize> SimpleDigest SimpleDigest< MergeSize >::merge (Range< const double * > r) const inline
Definition at line 45 of file BufferedStatTest.cpp.
References folly::Range< Iter >::begin(), folly::Range< Iter >::end(), and SimpleDigest< MergeSize >::values_.
{
     SimpleDigest digest(100);
     digest.values_ = values_;
     for (auto it = r.begin(); it != r.end(); ++it) {
       digest.values_.push_back(*it);
     }
     return digest;
   }
template<size_t MergeSize> static SimpleDigest SimpleDigest< MergeSize >::merge (Range< const SimpleDigest< MergeSize > * > r) inline static
Definition at line 55 of file BufferedStatTest.cpp.
References folly::Range< Iter >::begin(), folly::Range< Iter >::end(), folly::value(), and SimpleDigest< MergeSize >::values_.
{
     SimpleDigest digest(100);
     for (auto it = r.begin(); it != r.end(); ++it) {
       for (auto value : it->values_) {
         digest.values_.push_back(value);
       }
     }
     return digest;
   }
Member Data Documentation
template<size_t MergeSize> int64_t SimpleDigest< MergeSize >::sz_ private
Definition at line 52 of file DigestBuilderTest.cpp.
template<size_t MergeSize> std::vector<double> SimpleDigest< MergeSize >::values_ private
Definition at line 74 of file BufferedStatTest.cpp.
Referenced by SimpleDigest< MergeSize >::merge().
The documentation for this class was generated from the following files:
proxygen/folly/folly/stats/test/BufferedStatTest.cpp
proxygen/folly/folly/stats/test/DigestBuilderTest.cpp