proxygen: folly::HazptrWideCAS< T, Atom > Class Template Reference
folly::HazptrWideCAS< T, Atom > Class Template Reference
#include <HazptrWideCAS.h>
Classes
struct Node
Public Member Functions
HazptrWideCAS ()
~HazptrWideCAS ()
bool cas (T &u, T &v)
Private Attributes
Atom< Node * > node_
Detailed Description
template<typename T, template< typename > class Atom = std::atomic>
class folly::HazptrWideCAS< T, Atom >
Wide CAS.
Definition at line 27 of file HazptrWideCAS.h.
Constructor & Destructor Documentation
template<typename T, template< typename > class Atom = std::atomic> folly::HazptrWideCAS< T, Atom >::HazptrWideCAS () inline
Definition at line 36 of file HazptrWideCAS.h.
 : node_(new Node()) {}
template<typename T, template< typename > class Atom = std::atomic> folly::HazptrWideCAS< T, Atom >::~HazptrWideCAS () inline
Definition at line 38 of file HazptrWideCAS.h.
                    {
     delete node_.load(std::memory_order_relaxed);
   }
Member Function Documentation
template<typename T, template< typename > class Atom = std::atomic> bool folly::HazptrWideCAS< T, Atom >::cas (T & u, T & v) inline
Definition at line 42 of file HazptrWideCAS.h.
References folly::hazptr_holder< Atom >::get_protected(), folly::HazptrWideCAS< T, Atom >::Node::Node(), folly::hazptr_holder< Atom >::reset(), folly::hazptr_obj_base< T, Atom, D >::retire(), and folly::HazptrWideCAS< T, Atom >::Node::val_.
Referenced by wide_cas_test().
{
     Node* n = new Node(v);
     hazptr_holder<Atom> hptr;
     Node* p;
     while (true) {
       p = hptr.get_protected(node_);
       if (p->val_ != u) {
         delete n;
         return false;
       }
       if (node_.compare_exchange_weak(
               p, n, std::memory_order_relaxed, std::memory_order_release)) {
         break;
       }
     }
     hptr.reset();
     p->retire();
     return true;
   }
Member Data Documentation
template<typename T, template< typename > class Atom = std::atomic> Atom<Node*> folly::HazptrWideCAS< T, Atom >::node_ private
Definition at line 33 of file HazptrWideCAS.h.
The documentation for this class was generated from the following file:
proxygen/folly/folly/synchronization/example/HazptrWideCAS.h