proxygen: folly::ZeroCopyTest Class Reference
folly::ZeroCopyTest Class Reference
#include <ZeroCopy.h>
Public Member Functions
ZeroCopyTest (size_t numClients, int numLoops, bool zeroCopy, size_t bufferSize)
bool run ()
Private Member Functions
void connectAll ()
Private Attributes
size_t numClients_
size_t counter_
int numLoops_
bool zeroCopy_
size_t bufferSize_
EventBase evb_
std::vector< std::unique_ptr< ZeroCopyTestAsyncSocket > > clients_
folly::AsyncServerSocket::UniquePtr listenSock_
ZeroCopyTestServer server_
Detailed Description
Definition at line 251 of file ZeroCopy.h.
Constructor & Destructor Documentation
folly::ZeroCopyTest::ZeroCopyTest (size_t numClients, int numLoops, bool zeroCopy, size_t bufferSize) explicit
Definition at line 22 of file ZeroCopy.cpp.
References folly::ZeroCopyTestServer::addCallbackToServerSocket(), bufferSize_, clients_, counter_, evb_, i, listenSock_, numClients_, numLoops_, and server_.
     : numClients_(numClients),
       counter_(numClients),
       numLoops_(numLoops),
       zeroCopy_(zeroCopy),
       bufferSize_(bufferSize),
       listenSock_(new folly::AsyncServerSocket(&evb_)),
       server_(&evb_, numLoops_, bufferSize_, zeroCopy) {
   clients_.reserve(numClients_);
   for (size_t i = 0; i < numClients_; i++) {
     clients_.emplace_back(std::make_unique<ZeroCopyTestAsyncSocket>(
         &counter_, &evb_, numLoops_, bufferSize_, zeroCopy));
   }
   if (listenSock_) {
     server_.addCallbackToServerSocket(*listenSock_);
   }
 }
Member Function Documentation
void folly::ZeroCopyTest::connectAll () inline private
Definition at line 261 of file ZeroCopy.h.
References addr.
Referenced by run().
                     {
     SocketAddress addr = listenSock_->getAddress();
     for (auto& client : clients_) {
       client->connect(addr);
     }
   }
bool folly::ZeroCopyTest::run ()
Definition at line 45 of file ZeroCopy.cpp.
References clients_, connectAll(), evb_, listenSock_, folly::EventBase::loopForever(), folly::EventBase::runInEventBaseThread(), and zeroCopy_.
Referenced by TEST(), zeroCopyOff(), and zeroCopyOn().
{
   evb_.runInEventBaseThread([this]() {
     if (listenSock_) {
       listenSock_->bind(0);
       listenSock_->setZeroCopy(zeroCopy_);
       listenSock_->listen(10);
       listenSock_->startAccepting();
       connectAll();
     }
   });
   evb_.loopForever();
   for (auto& client : clients_) {
     if (client->isZeroCopyWriteInProgress()) {
       return false;
     }
   }
   return true;
 }
Member Data Documentation
size_t folly::ZeroCopyTest::bufferSize_ private
Definition at line 272 of file ZeroCopy.h.
Referenced by ZeroCopyTest().
std::vector<std::unique_ptr<ZeroCopyTestAsyncSocket> > folly::ZeroCopyTest::clients_ private
Definition at line 275 of file ZeroCopy.h.
Referenced by run(), and ZeroCopyTest().
size_t folly::ZeroCopyTest::counter_ private
Definition at line 269 of file ZeroCopy.h.
Referenced by ZeroCopyTest().
EventBase folly::ZeroCopyTest::evb_ private
Definition at line 274 of file ZeroCopy.h.
Referenced by run(), and ZeroCopyTest().
folly::AsyncServerSocket::UniquePtr folly::ZeroCopyTest::listenSock_ private
Definition at line 276 of file ZeroCopy.h.
Referenced by run(), and ZeroCopyTest().
size_t folly::ZeroCopyTest::numClients_ private
Definition at line 268 of file ZeroCopy.h.
Referenced by ZeroCopyTest().
int folly::ZeroCopyTest::numLoops_ private
Definition at line 270 of file ZeroCopy.h.
Referenced by ZeroCopyTest().
ZeroCopyTestServer folly::ZeroCopyTest::server_ private
Definition at line 277 of file ZeroCopy.h.
Referenced by ZeroCopyTest().
bool folly::ZeroCopyTest::zeroCopy_ private
Definition at line 271 of file ZeroCopy.h.
Referenced by run().
The documentation for this class was generated from the following files:
proxygen/folly/folly/io/async/test/ZeroCopy.h
proxygen/folly/folly/io/async/test/ZeroCopy.cpp