proxygen: fizz::server::test::MockTicketCipher Class Reference
fizz::server::test::MockTicketCipher Class Reference
#include <Mocks.h>
Public Member Functions
MOCK_CONST_METHOD1 (_encrypt, folly::Future< folly::Optional< std::pair< Buf, std::chrono::seconds >>>(ResumptionState &))
folly::Future< folly::Optional< std::pair< Buf, std::chrono::seconds > > > encrypt (ResumptionState resState) const override
MOCK_CONST_METHOD1 (_decrypt, folly::Future< std::pair< PskType, folly::Optional< ResumptionState >>>(std::unique_ptr< folly::IOBuf > &encryptedTicket))
folly::Future< std::pair< PskType, folly::Optional< ResumptionState > > > decrypt (std::unique_ptr< folly::IOBuf > encryptedTicket) const override
void setDefaults ()
Public Member Functions inherited from fizz::server::TicketCipher
virtual ~TicketCipher ()=default
Detailed Description
Definition at line 88 of file Mocks.h.
Member Function Documentation
folly::Future<std::pair<PskType, folly::Optional<ResumptionState> > > fizz::server::test::MockTicketCipher::decrypt (std::unique_ptr< folly::IOBuf > encryptedTicket) const inline override virtual
Returns the ResumptionState for an opaque PSK, and the type of PSK (resumption or external).
Returns Rejected if the PSK is not recognized.
Implements fizz::server::TicketCipher.
Definition at line 103 of file Mocks.h.
{
     return _decrypt(encryptedTicket);
   }
folly::Future<folly::Optional<std::pair<Buf, std::chrono::seconds> > > fizz::server::test::MockTicketCipher::encrypt (ResumptionState resState) const inline override virtual
Returns an opaque PSK for ResumptionState, and its validity time.
Implements fizz::server::TicketCipher.
Definition at line 94 of file Mocks.h.
References MOCK_CONST_METHOD1.
{
     return _encrypt(resState);
   }
fizz::server::test::MockTicketCipher::MOCK_CONST_METHOD1 (_encrypt , folly::Future< folly::Optional< std::pair< Buf, std::chrono::seconds >>> ResumptionState &)
fizz::server::test::MockTicketCipher::MOCK_CONST_METHOD1 (_decrypt , folly::Future< std::pair< PskType, folly::Optional< ResumptionState >>> std::unique_ptr< folly::IOBuf > &encryptedTicket)
void fizz::server::test::MockTicketCipher::setDefaults () inline
Definition at line 108 of file Mocks.h.
References testing::_, fizz::server::ResumptionState::alpn, fizz::server::ResumptionState::cipher, folly::IOBuf::copyBuffer(), testing::InvokeWithoutArgs(), folly::gen::move, now(), ON_CALL, fizz::server::ResumptionState::resumptionSecret, fizz::server::ResumptionState::ticketAgeAdd, fizz::server::ResumptionState::ticketIssueTime, and fizz::server::ResumptionState::version.
                      {
     ON_CALL(*this, _decrypt(_)).WillByDefault(InvokeWithoutArgs([]() {
       ResumptionState res;
       res.version = ProtocolVersion::tls_1_3;
       res.cipher = CipherSuite::TLS_AES_128_GCM_SHA256;
       res.resumptionSecret = folly::IOBuf::copyBuffer("resumesecret");
       res.alpn = "h2";
       res.ticketAgeAdd = 0;
       res.ticketIssueTime =
           std::chrono::system_clock::now() - std::chrono::seconds(100);
       return std::make_pair(PskType::Resumption, std::move(res));
     }));
     ON_CALL(*this, _encrypt(_)).WillByDefault(InvokeWithoutArgs([]() {
       return std::make_pair(
           folly::IOBuf::copyBuffer("ticket"), std::chrono::seconds(100));
     }));
   }
The documentation for this class was generated from the following file:
proxygen/fizz/fizz/server/test/Mocks.h