proxygen: DownstreamTransactionTest Class Reference
DownstreamTransactionTest Class Reference
Public Member Functions
DownstreamTransactionTest ()
void SetUp () override
void setupRequestResponseFlow (HTTPTransaction *txn, uint32_t size, bool delayResponse=false)
Public Member Functions inherited from testing::Test
virtual ~Test ()
virtual ~Test ()
virtual ~Test ()
Protected Attributes
folly::EventBase eventBase_
folly::HHWheelTimer::UniquePtr transactionTimeouts_
MockHTTPTransactionTransport transport_
StrictMock< MockHTTPHandler > handler_
HTTP2PriorityQueue txnEgressQueue_
uint32_t received_ {0}
uint32_t sent_ {0}
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Protected Member Functions inherited from testing::Test
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Test ()
virtual void TearDown ()
Detailed Description
Definition at line 30 of file DownstreamTransactionTest.cpp.
Constructor & Destructor Documentation
DownstreamTransactionTest::DownstreamTransactionTest () inline
Definition at line 32 of file DownstreamTransactionTest.cpp.
 {}
Member Function Documentation
void DownstreamTransactionTest::SetUp () inline override virtual
Reimplemented from testing::Test.
Definition at line 34 of file DownstreamTransactionTest.cpp.
References testing::_, EXPECT_CALL, testing::Return(), and transport_.
{
     EXPECT_CALL(transport_, describe(_))
       .WillRepeatedly(Return());
   }
void DownstreamTransactionTest::setupRequestResponseFlow (HTTPTransaction * txn, uint32_t size, bool delayResponse = false) inline
Definition at line 39 of file DownstreamTransactionTest.cpp.
References testing::_, testing::DoDefault(), EXPECT_CALL, EXPECT_EQ, proxygen::HTTPMessage::getStatusCode(), testing::Invoke(), testing::InvokeWithoutArgs(), proxygen::makeBuf(), proxygen::makeResponse(), proxygen::HTTPTransaction::onIngressBody(), proxygen::HTTPTransaction::onIngressEOM(), proxygen::HTTPTransaction::onWriteReady(), proxygen::HTTPTransaction::sendBody(), proxygen::HTTPTransaction::sendEOM(), proxygen::HTTPTransaction::sendHeaders(), proxygen::HTTPTransaction::setHandler(), and transport_.
{
     EXPECT_CALL(handler_, setTransaction(txn));
     EXPECT_CALL(handler_, detachTransaction());
     EXPECT_CALL(transport_, detach(txn));
     if (delayResponse) {
       EXPECT_CALL(handler_, onHeadersComplete(_));
     } else {
       EXPECT_CALL(handler_, onHeadersComplete(_))
           .WillOnce(Invoke([=](std::shared_ptr<HTTPMessage> /*msg*/) {
             auto response = makeResponse(200);
             txn->sendHeaders(*response.get());
             txn->sendBody(makeBuf(size));
             txn->sendEOM();
           }));
     }
     EXPECT_CALL(transport_, sendHeaders(txn, _, _, _))
       .WillOnce(Invoke([=](Unused, const HTTPMessage& headers, Unused, Unused) {
             EXPECT_EQ(headers.getStatusCode(), 200);
           }));
     EXPECT_CALL(transport_, sendBody(txn, _, false, false))
       .WillRepeatedly(Invoke([=](Unused, std::shared_ptr<folly::IOBuf> body,
                                  Unused, Unused) {
                                auto cur = body->computeChainDataLength();
                                sent_ += cur;
                                return cur;
                              }));
     if (delayResponse) {
       EXPECT_CALL(transport_, sendEOM(txn, _));
     } else {
       EXPECT_CALL(transport_, sendEOM(txn, _))
           .WillOnce(InvokeWithoutArgs([=]() {
             CHECK_EQ(sent_, size);
             txn->onIngressBody(makeBuf(size), 0);
             txn->onIngressEOM();
             return 5;
           }));
     }
     EXPECT_CALL(handler_, onBody(_))
       .WillRepeatedly(Invoke([=](std::shared_ptr<folly::IOBuf> body) {
             received_ += body->computeChainDataLength();
           }));
     EXPECT_CALL(handler_, onEOM())
       .WillOnce(InvokeWithoutArgs([=] {
             CHECK_EQ(received_, size);
           }));
     EXPECT_CALL(transport_, notifyPendingEgress())
       .WillOnce(InvokeWithoutArgs([=] {
             txn->onWriteReady(size, 1);
           }))
       .WillOnce(DoDefault()); // The second call is for sending the eom
     txn->setHandler(&handler_);
   }
Member Data Documentation
folly::EventBase DownstreamTransactionTest::eventBase_ protected
Definition at line 95 of file DownstreamTransactionTest.cpp.
StrictMock<MockHTTPHandler> DownstreamTransactionTest::handler_ protected
Definition at line 103 of file DownstreamTransactionTest.cpp.
uint32_t DownstreamTransactionTest::received_ {0} protected
Definition at line 105 of file DownstreamTransactionTest.cpp.
uint32_t DownstreamTransactionTest::sent_ {0} protected
Definition at line 106 of file DownstreamTransactionTest.cpp.
folly::HHWheelTimer::UniquePtr DownstreamTransactionTest::transactionTimeouts_ protected
Initial value:
{
      folly::HHWheelTimer::newTimer(
          &eventBase_,
          std::chrono::milliseconds(folly::HHWheelTimer::DEFAULT_TICK_INTERVAL),
          folly::AsyncTimeout::InternalEnum::NORMAL,
          std::chrono::milliseconds(500))}
Definition at line 96 of file DownstreamTransactionTest.cpp.
MockHTTPTransactionTransport DownstreamTransactionTest::transport_ protected
Definition at line 102 of file DownstreamTransactionTest.cpp.
HTTP2PriorityQueue DownstreamTransactionTest::txnEgressQueue_ protected
Definition at line 104 of file DownstreamTransactionTest.cpp.
The documentation for this class was generated from the following file:
proxygen/lib/http/session/test/DownstreamTransactionTest.cpp