proxygen: testing::internal::ActionResultHolder< T > Class Template Reference
testing::internal::ActionResultHolder< T > Class Template Reference
#include <gmock-spec-builders.h>
Public Member Functions
T Unwrap ()
virtual void PrintAsActionResult (::std::ostream *os) const
T Unwrap ()
virtual void PrintAsActionResult (::std::ostream *os) const
T Unwrap ()
virtual void PrintAsActionResult (::std::ostream *os) const
Public Member Functions inherited from testing::internal::UntypedActionResultHolderBase
virtual ~UntypedActionResultHolderBase ()
virtual ~UntypedActionResultHolderBase ()
virtual ~UntypedActionResultHolderBase ()
Static Public Member Functions
template<typename F >
static ActionResultHolder * PerformDefaultAction (const FunctionMockerBase< F > *func_mocker, const typename Function< F >::ArgumentTuple &args, const string &call_description)
template<typename F >
static ActionResultHolder * PerformAction (const Action< F > &action, const typename Function< F >::ArgumentTuple &args)
template<typename F >
static ActionResultHolder * PerformDefaultAction (const FunctionMockerBase< F > *func_mocker, const typename Function< F >::ArgumentTuple &args, const string &call_description)
template<typename F >
static ActionResultHolder * PerformAction (const Action< F > &action, const typename Function< F >::ArgumentTuple &args)
template<typename F >
static ActionResultHolder * PerformDefaultAction (const FunctionMockerBase< F > *func_mocker, const typename Function< F >::ArgumentTuple &args, const string &call_description)
template<typename F >
static ActionResultHolder * PerformAction (const Action< F > &action, const typename Function< F >::ArgumentTuple &args)
Private Types
typedef ReferenceOrValueWrapper< T > Wrapper
typedef ReferenceOrValueWrapper< T > Wrapper
typedef ReferenceOrValueWrapper< T > Wrapper
Private Member Functions
ActionResultHolder (Wrapper result)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (ActionResultHolder)
ActionResultHolder (Wrapper result)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (ActionResultHolder)
ActionResultHolder (Wrapper result)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (ActionResultHolder)
Private Attributes
Wrapper result_
Detailed Description
template<typename T>
class testing::internal::ActionResultHolder< T >
Definition at line 1372 of file gmock-spec-builders.h.
Member Typedef Documentation
template<typename T > typedef ReferenceOrValueWrapper<T> testing::internal::ActionResultHolder< T >::Wrapper private
Definition at line 1407 of file gmock-spec-builders.h.
template<typename T > typedef ReferenceOrValueWrapper<T> testing::internal::ActionResultHolder< T >::Wrapper private
Definition at line 1407 of file gmock-spec-builders.h.
template<typename T > typedef ReferenceOrValueWrapper<T> testing::internal::ActionResultHolder< T >::Wrapper private
Definition at line 1407 of file gmock-spec-builders.h.
Constructor & Destructor Documentation
template<typename T > testing::internal::ActionResultHolder< T >::ActionResultHolder (Wrapper result) inline explicit private
Definition at line 1409 of file gmock-spec-builders.h.
       : result_(::testing::internal::move(result)) {
   }
template<typename T > testing::internal::ActionResultHolder< T >::ActionResultHolder (Wrapper result) inline explicit private
Definition at line 1409 of file gmock-spec-builders.h.
References GTEST_DISALLOW_COPY_AND_ASSIGN_.
       : result_(::testing::internal::move(result)) {
   }
template<typename T > testing::internal::ActionResultHolder< T >::ActionResultHolder (Wrapper result) inline explicit private
Definition at line 1409 of file gmock-spec-builders.h.
References GTEST_DISALLOW_COPY_AND_ASSIGN_.
       : result_(::testing::internal::move(result)) {
   }
Member Function Documentation
template<typename T > testing::internal::ActionResultHolder< T >::GTEST_DISALLOW_COPY_AND_ASSIGN_ (ActionResultHolder< T >) private
template<typename T > testing::internal::ActionResultHolder< T >::GTEST_DISALLOW_COPY_AND_ASSIGN_ (ActionResultHolder< T >) private
template<typename T > testing::internal::ActionResultHolder< T >::GTEST_DISALLOW_COPY_AND_ASSIGN_ (ActionResultHolder< T >) private
template<typename T > template<typename F > static ActionResultHolder* testing::internal::ActionResultHolder< T >::PerformAction (const Action< F > & action, const typename Function< F >::ArgumentTuple & args) inline static
Definition at line 1401 of file gmock-spec-builders.h.
References testing::Action< F >::Perform().
{
     return new ActionResultHolder(Wrapper(action.Perform(args)));
   }
template<typename T > template<typename F > static ActionResultHolder* testing::internal::ActionResultHolder< T >::PerformAction (const Action< F > & action, const typename Function< F >::ArgumentTuple & args) inline static
Definition at line 1401 of file gmock-spec-builders.h.
References testing::Action< F >::Perform().
{
     return new ActionResultHolder(Wrapper(action.Perform(args)));
   }
template<typename T > template<typename F > static ActionResultHolder* testing::internal::ActionResultHolder< T >::PerformAction (const Action< F > & action, const typename Function< F >::ArgumentTuple & args) inline static
Definition at line 1401 of file gmock-spec-builders.h.
References testing::Action< F >::Perform().
{
     return new ActionResultHolder(Wrapper(action.Perform(args)));
   }
template<typename T > template<typename F > static ActionResultHolder* testing::internal::ActionResultHolder< T >::PerformDefaultAction (const FunctionMockerBase< F > * func_mocker, const typename Function< F >::ArgumentTuple & args, const string & call_description) inline static
Definition at line 1389 of file gmock-spec-builders.h.
References testing::internal::FunctionMockerBase< F >::PerformDefaultAction().
{
     return new ActionResultHolder(Wrapper(
         func_mocker->PerformDefaultAction(args, call_description)));
   }
template<typename T > template<typename F > static ActionResultHolder* testing::internal::ActionResultHolder< T >::PerformDefaultAction (const FunctionMockerBase< F > * func_mocker, const typename Function< F >::ArgumentTuple & args, const string & call_description) inline static
Definition at line 1389 of file gmock-spec-builders.h.
References testing::internal::FunctionMockerBase< F >::PerformDefaultAction().
{
     return new ActionResultHolder(Wrapper(
         func_mocker->PerformDefaultAction(args, call_description)));
   }
template<typename T > template<typename F > static ActionResultHolder* testing::internal::ActionResultHolder< T >::PerformDefaultAction (const FunctionMockerBase< F > * func_mocker, const typename Function< F >::ArgumentTuple & args, const string & call_description) inline static
Definition at line 1389 of file gmock-spec-builders.h.
References testing::internal::FunctionMockerBase< F >::PerformDefaultAction().
{
     return new ActionResultHolder(Wrapper(
         func_mocker->PerformDefaultAction(args, call_description)));
   }
template<typename T > virtual void testing::internal::ActionResultHolder< T >::PrintAsActionResult (::std::ostream * os) const inline virtual
Implements testing::internal::UntypedActionResultHolderBase.
Definition at line 1380 of file gmock-spec-builders.h.
References testing::internal::UniversalPrinter< T >::Print().
{
     *os << "\n          Returns: ";
     // T may be a reference type, so we don't use UniversalPrint().
     UniversalPrinter<T>::Print(result_.Peek(), os);
   }
template<typename T > virtual void testing::internal::ActionResultHolder< T >::PrintAsActionResult (::std::ostream * os) const inline virtual
Implements testing::internal::UntypedActionResultHolderBase.
Definition at line 1380 of file gmock-spec-builders.h.
References testing::internal::UniversalPrinter< T >::Print().
{
     *os << "\n          Returns: ";
     // T may be a reference type, so we don't use UniversalPrint().
     UniversalPrinter<T>::Print(result_.Peek(), os);
   }
template<typename T > virtual void testing::internal::ActionResultHolder< T >::PrintAsActionResult (::std::ostream * os) const inline virtual
Implements testing::internal::UntypedActionResultHolderBase.
Definition at line 1380 of file gmock-spec-builders.h.
References testing::internal::UniversalPrinter< T >::Print().
{
     *os << "\n          Returns: ";
     // T may be a reference type, so we don't use UniversalPrint().
     UniversalPrinter<T>::Print(result_.Peek(), os);
   }
template<typename T > T testing::internal::ActionResultHolder< T >::Unwrap () inline
Definition at line 1375 of file gmock-spec-builders.h.
              {
     return result_.Unwrap();
   }
template<typename T > T testing::internal::ActionResultHolder< T >::Unwrap () inline
Definition at line 1375 of file gmock-spec-builders.h.
              {
     return result_.Unwrap();
   }
template<typename T > T testing::internal::ActionResultHolder< T >::Unwrap () inline
Definition at line 1375 of file gmock-spec-builders.h.
              {
     return result_.Unwrap();
   }
Member Data Documentation
template<typename T > Wrapper testing::internal::ActionResultHolder< T >::result_ private
Definition at line 1413 of file gmock-spec-builders.h.
The documentation for this class was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-spec-builders.h