proxygen: wangle::HandlerContext< In, Out > Class Template Reference
wangle::HandlerContext< In, Out > Class Template Reference abstract
#include <HandlerContext.h>
Public Member Functions
virtual ~HandlerContext ()=default
virtual void fireRead (In msg)=0
virtual void fireReadEOF ()=0
virtual void fireReadException (folly::exception_wrapper e)=0
virtual void fireTransportActive ()=0
virtual void fireTransportInactive ()=0
virtual folly::Future< folly::Unit > fireWrite (Out msg)=0
virtual folly::Future< folly::Unit > fireWriteException (folly::exception_wrapper e)=0
virtual folly::Future< folly::Unit > fireClose ()=0
virtual PipelineBase * getPipeline ()=0
virtual std::shared_ptr< PipelineBase > getPipelineShared ()=0
std::shared_ptr< folly::AsyncTransport > getTransport ()
virtual void setWriteFlags (folly::WriteFlags flags)=0
virtual folly::WriteFlags getWriteFlags ()=0
virtual void setReadBufferSettings (uint64_t minAvailable, uint64_t allocationSize)=0
virtual std::pair< uint64_t, uint64_t > getReadBufferSettings ()=0
Detailed Description
template<class In, class Out>
class wangle::HandlerContext< In, Out >
Definition at line 28 of file HandlerContext.h.
Constructor & Destructor Documentation
template<class In, class Out> virtual wangle::HandlerContext< In, Out >::~HandlerContext () virtual default
Member Function Documentation
template<class In, class Out> virtual folly::Future<folly::Unit> wangle::HandlerContext< In, Out >::fireClose () pure virtual
Implemented in wangle::ContextImpl< H >.
Referenced by wangle::Handler< Resp, Resp, folly::Req, folly::Req >::close().
template<class In, class Out> virtual void wangle::HandlerContext< In, Out >::fireRead (In msg) pure virtual
Implemented in wangle::ContextImpl< H >.
Referenced by ClientSerializeHandler::read(), ServerSerializeHandler::read(), wangle::HandlerAdapter< Req, Resp >::read(), and wangle::AsyncSocketHandler::readDataAvailable().
template<class In, class Out> virtual void wangle::HandlerContext< In, Out >::fireReadEOF () pure virtual
Implemented in wangle::ContextImpl< H >.
Referenced by wangle::Handler< Resp, Resp, folly::Req, folly::Req >::readEOF(), and wangle::AsyncSocketHandler::readEOF().
template<class In, class Out> virtual void wangle::HandlerContext< In, Out >::fireReadException (folly::exception_wrapper e) pure virtual
Implemented in wangle::ContextImpl< H >.
Referenced by wangle::AsyncSocketHandler::readErr(), and wangle::Handler< Resp, Resp, folly::Req, folly::Req >::readException().
template<class In, class Out> virtual void wangle::HandlerContext< In, Out >::fireTransportActive () pure virtual
Implemented in wangle::ContextImpl< H >.
Referenced by wangle::Handler< Resp, Resp, folly::Req, folly::Req >::transportActive().
template<class In, class Out> virtual void wangle::HandlerContext< In, Out >::fireTransportInactive () pure virtual
Implemented in wangle::ContextImpl< H >.
Referenced by wangle::Handler< Resp, Resp, folly::Req, folly::Req >::transportInactive().
template<class In, class Out> virtual folly::Future<folly::Unit> wangle::HandlerContext< In, Out >::fireWrite (Out msg) pure virtual
Implemented in wangle::ContextImpl< H >.
Referenced by wangle::PipelinedServerDispatcher< Req, Resp >::sendResponses(), ClientSerializeHandler::write(), ServerSerializeHandler::write(), and wangle::HandlerAdapter< Req, Resp >::write().
template<class In, class Out> virtual folly::Future<folly::Unit> wangle::HandlerContext< In, Out >::fireWriteException (folly::exception_wrapper e) pure virtual
Implemented in wangle::ContextImpl< H >.
Referenced by wangle::Handler< Resp, Resp, folly::Req, folly::Req >::writeException().
template<class In, class Out> virtual PipelineBase* wangle::HandlerContext< In, Out >::getPipeline () pure virtual
Implemented in wangle::ContextImpl< H >.
Referenced by wangle::HandlerContext< thrift::test::Bonk, std::unique_ptr< folly::IOBuf > >::getTransport(), wangle::InboundHandlerContext< M >::getTransport(), wangle::OutboundHandlerContext< Wout >::getTransport(), wangle::AsyncSocketHandler::refreshTimeout(), and TEST_F().
template<class In, class Out> virtual std::shared_ptr<PipelineBase> wangle::HandlerContext< In, Out >::getPipelineShared () pure virtual
Implemented in wangle::ContextImpl< H >.
Referenced by FileServerHandler::read().
template<class In, class Out> virtual std::pair<uint64_t, uint64_t> wangle::HandlerContext< In, Out >::getReadBufferSettings () pure virtual
Implemented in wangle::ContextImpl< H >.
Referenced by wangle::AsyncSocketHandler::getReadBuffer(), and wangle::HandlerContext< thrift::test::Bonk, std::unique_ptr< folly::IOBuf > >::getTransport().
template<class In, class Out> std::shared_ptr<folly::AsyncTransport> wangle::HandlerContext< In, Out >::getTransport () inline
Definition at line 45 of file HandlerContext.h.
Referenced by FileServerHandler::read(), TelnetHandler::transportActive(), and FileServerHandler::transportActive().
{
     return getPipeline()->getTransport();
   }
template<class In, class Out> virtual folly::WriteFlags wangle::HandlerContext< In, Out >::getWriteFlags () pure virtual
Implemented in wangle::ContextImpl< H >.
Referenced by wangle::HandlerContext< thrift::test::Bonk, std::unique_ptr< folly::IOBuf > >::getTransport().
template<class In, class Out> virtual void wangle::HandlerContext< In, Out >::setReadBufferSettings (uint64_t minAvailable, uint64_t allocationSize) pure virtual
Implemented in wangle::ContextImpl< H >.
Referenced by wangle::HandlerContext< thrift::test::Bonk, std::unique_ptr< folly::IOBuf > >::getTransport().
template<class In, class Out> virtual void wangle::HandlerContext< In, Out >::setWriteFlags (folly::WriteFlags flags) pure virtual
Implemented in wangle::ContextImpl< H >.
Referenced by wangle::HandlerContext< thrift::test::Bonk, std::unique_ptr< folly::IOBuf > >::getTransport().
The documentation for this class was generated from the following file:
proxygen/wangle/wangle/channel/HandlerContext.h