proxygen: proxygen/wangle/wangle/example/ssl/Client.cpp File Reference
Client.cpp File Reference
#include <iostream>
#include <folly/init/Init.h>
#include <folly/io/async/AsyncSSLSocket.h>
#include <folly/io/async/SSLOptions.h>
#include <folly/portability/GFlags.h>
#include <folly/ssl/Init.h>
#include <folly/io/async/DelayedDestruction.h>
#include <wangle/bootstrap/ClientBootstrap.h>
#include <wangle/channel/AsyncSocketHandler.h>
#include <wangle/channel/EventBaseHandler.h>
#include <wangle/client/ssl/SSLSessionPersistentCache.h>
#include <wangle/client/persistence/LRUPersistentCache.h>
#include <wangle/codec/LineBasedFrameDecoder.h>
#include <wangle/codec/StringCodec.h>
Functions
DEFINE_string (ip,"::1","Ip address to connect to")
DEFINE_uint32 (port, 8080,"Port to connect to")
DEFINE_bool (ssl, true,"Whether to use SSL")
DEFINE_string (cache_file,"","Session cache file")
DEFINE_string (cert_path,"","Path to client cert pem")
DEFINE_string (key_path,"","Path to client cert key pem")
DEFINE_string (ca_path,"","Path to trusted CA file")
int main (int argc, char **argv)
Variables
const std::string SESSION_KEY = "test_client"
Function Documentation
DEFINE_bool (ssl , true , "Whether to use SSL")
DEFINE_string (ip , "::1" , "Ip address to connect to")
DEFINE_string (cache_file , "" , "Session cache file")
DEFINE_string (cert_path , "" , "Path to client cert pem")
DEFINE_string (key_path , "" , "Path to client cert key pem")
DEFINE_string (ca_path , "" , "Path to trusted CA file")
DEFINE_uint32 (port , 8080 , "Port to connect to")
int main (int argc, char ** argv)
Definition at line 125 of file Client.cpp.
References addr, wangle::SSLSessionCallbacks::attachCallbacksToContext(), folly::exceptionStr(), getline(), folly::ssl::init(), bm::init(), SESSION_KEY, and string.
{
   folly::Init init(&argc, &argv);
   folly::ssl::init();
   // an in memory ssl session cache used for caching sessions
   std::shared_ptr<SSLSessionPersistentCache> cache;
   if (!FLAGS_cache_file.empty()) {
     cache = std::make_shared<SSLSessionPersistentCache>(
       FLAGS_cache_file, 100, std::chrono::seconds(60));
   }
   EchoClientBootstrap client;
   client.group(std::make_shared<IOThreadPoolExecutor>(1));
   client.pipelineFactory(std::make_shared<EchoPipelineFactory>());
   if (FLAGS_ssl) {
     auto ctx = createSSLContext();
     // attach the context to the cache
     if (cache) {
       wangle::SSLSessionCallbacks::attachCallbacksToContext(
         ctx->getSSLCtx(), cache.get());
       auto session = cache->getSSLSession(SESSION_KEY);
       if (session) {
         VLOG(0) << "Reusing session";
         client.sslSession(session.release());
       }
     }
     client.sslContext(ctx);
   }
   SocketAddress addr(FLAGS_ip.c_str(), FLAGS_port);
   VLOG(0) << "Connecting";
   auto pipeline = client.connect(addr).get();
   VLOG(0) << "Connected";
   try {
     while (true) {
       std::string line;
       std::getline(std::cin, line);
       if (line == "") {
         VLOG(0) << "End";
         break;
       }
       VLOG(0) << "Sending " << line;
       pipeline->write(line + "\r\n").get();
       if (line == "bye") {
         pipeline->close();
         break;
       }
     }
   } catch (const std::exception& e) {
     std::cout << exceptionStr(e) << std::endl;
   }
   return 0;
 }
Variable Documentation
const std::string SESSION_KEY = "test_client"
Definition at line 44 of file Client.cpp.
Referenced by main().