proxygen: proxygen/folly/folly/executors/test/CodelTest.cpp File Reference
CodelTest.cpp File Reference
#include <folly/executors/Codel.h>
#include <folly/portability/GTest.h>
#include <chrono>
#include <thread>
Functions
TEST (CodelTest, Basic)
TEST (CodelTest, highLoad)
TEST (CodelTest, mediumLoad)
TEST (CodelTest, reducingLoad)
TEST (CodelTest, oneRequestNoDrop)
TEST (CodelTest, getLoadSanity)
Function Documentation
TEST (CodelTest , Basic)
Definition at line 25 of file CodelTest.cpp.
References c, EXPECT_FALSE, EXPECT_TRUE, and folly::Codel::overloaded().
{
   folly::Codel c;
   std::this_thread::sleep_for(milliseconds(110));
   // This interval is overloaded
   EXPECT_FALSE(c.overloaded(milliseconds(100)));
   std::this_thread::sleep_for(milliseconds(90));
   // At least two requests must happen in an interval before they will fail
   EXPECT_FALSE(c.overloaded(milliseconds(50)));
   EXPECT_TRUE(c.overloaded(milliseconds(50)));
   std::this_thread::sleep_for(milliseconds(110));
   // Previous interval is overloaded, but 2ms isn't enough to fail
   EXPECT_FALSE(c.overloaded(milliseconds(2)));
   std::this_thread::sleep_for(milliseconds(90));
   // 20 ms > target interval * 2
   EXPECT_TRUE(c.overloaded(milliseconds(20)));
 }
TEST (CodelTest , highLoad)
Definition at line 42 of file CodelTest.cpp.
References c, EXPECT_EQ, folly::Codel::getLoad(), and folly::Codel::overloaded().
{
   folly::Codel c;
   c.overloaded(milliseconds(40));
   EXPECT_EQ(100, c.getLoad());
 }
TEST (CodelTest , mediumLoad)
Definition at line 48 of file CodelTest.cpp.
References c, EXPECT_FALSE, EXPECT_GT, folly::Codel::getLoad(), and folly::Codel::overloaded().
{
   folly::Codel c;
   c.overloaded(milliseconds(20));
   sleep_for(milliseconds(90));
   // this is overloaded but this request shouldn't drop because it's not >
   // slough timeout
   EXPECT_FALSE(c.overloaded(milliseconds(8)));
   EXPECT_GT(100, c.getLoad());
 }
TEST (CodelTest , reducingLoad)
Definition at line 58 of file CodelTest.cpp.
References c, EXPECT_FALSE, and folly::Codel::overloaded().
{
   folly::Codel c;
   c.overloaded(milliseconds(20));
   sleep_for(milliseconds(90));
   EXPECT_FALSE(c.overloaded(milliseconds(4)));
 }
TEST (CodelTest , oneRequestNoDrop)
Definition at line 65 of file CodelTest.cpp.
References c, EXPECT_FALSE, and folly::Codel::overloaded().
{
   folly::Codel c;
   EXPECT_FALSE(c.overloaded(milliseconds(20)));
 }
TEST (CodelTest , getLoadSanity)
Definition at line 70 of file CodelTest.cpp.
References c, EXPECT_GT, EXPECT_LT, folly::Codel::getLoad(), and folly::Codel::overloaded().
{
   folly::Codel c;
   // should be 100% but leave a litte wiggle room.
   c.overloaded(milliseconds(10));
   EXPECT_LT(99, c.getLoad());
   EXPECT_GT(101, c.getLoad());
   // should be 70% but leave a litte wiggle room.
   c.overloaded(milliseconds(7));
   EXPECT_LT(60, c.getLoad());
   EXPECT_GT(80, c.getLoad());
   // should be 20% but leave a litte wiggle room.
   c.overloaded(milliseconds(2));
   EXPECT_LT(10, c.getLoad());
   EXPECT_GT(30, c.getLoad());
   // this test demonstrates how silly getLoad() is, but silly isn't
   // necessarily useless
 }