proxygen: proxygen/folly/folly/futures/test/CollectTest.cpp File Reference
CollectTest.cpp File Reference
#include <numeric>
#include <boost/thread/barrier.hpp>
#include <folly/Random.h>
#include <folly/futures/Future.h>
#include <folly/portability/GTest.h>
#include <folly/small_vector.h>
Classes
struct NotDefaultConstructible
Typedefs
typedef FutureException eggs_t
Functions
TEST (Collect, collectAll)
TEST (Collect, collect)
TEST (Collect, collectNotDefaultConstructible)
TEST (Collect, collectAny)
TEST (Collect, collectAnyWithoutException)
TEST (Collect, alreadyCompleted)
TEST (Collect, parallel)
TEST (Collect, parallelWithError)
TEST (Collect, allParallel)
TEST (Collect, allParallelWithError)
TEST (Collect, collectN)
TEST (Collect, collectNParallel)
TEST (Collect, smallVector)
Ensure that we can compile collectAll/Any with folly::small_vector.
TEST (Collect, collectAllVariadic)
TEST (Collect, collectAllVariadicReferences)
TEST (Collect, collectAllVariadicWithException)
TEST (Collect, collectVariadic)
TEST (Collect, collectVariadicWithException)
TEST (Collect, collectAllNone)
TEST (Collect, noDefaultConstructor)
Variables
static eggs_t eggs ("eggs")
auto rng = std::mt19937(folly::randomNumberSeed())
Typedef Documentation
typedef FutureException eggs_t
Definition at line 28 of file CollectTest.cpp.
Function Documentation
TEST (Collect , collectAll)
Definition at line 33 of file CollectTest.cpp.
References folly::collectAll(), folly::collectAllSemiFuture(), eggs, EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, f, rng, folly::pushmi::detail::t, and folly::value().
{
   // returns a vector variant
   {
     std::vector<Promise<int>> promises(10);
     std::vector<Future<int>> futures;
     for (auto& p : promises) {
       futures.push_back(p.getFuture());
     }
     auto allf = collectAll(futures);
     std::shuffle(promises.begin(), promises.end(), rng);
     for (auto& p : promises) {
       EXPECT_FALSE(allf.isReady());
       p.setValue(42);
     }
     EXPECT_TRUE(allf.isReady());
     auto& results = allf.value();
     for (auto& t : results) {
       EXPECT_EQ(42, t.value());
     }
   }
   // check error semantics
   {
     std::vector<Promise<int>> promises(4);
     std::vector<Future<int>> futures;
     for (auto& p : promises) {
       futures.push_back(p.getFuture());
     }
     auto allf = collectAll(futures);
     promises[0].setValue(42);
     promises[1].setException(eggs);
     EXPECT_FALSE(allf.isReady());
     promises[2].setValue(42);
     EXPECT_FALSE(allf.isReady());
     promises[3].setException(eggs);
     EXPECT_TRUE(allf.isReady());
     EXPECT_FALSE(allf.getTry().hasException());
     auto& results = allf.value();
     EXPECT_EQ(42, results[0].value());
     EXPECT_TRUE(results[1].hasException());
     EXPECT_EQ(42, results[2].value());
     EXPECT_TRUE(results[3].hasException());
   }
   // check that futures are ready in then()
   {
     std::vector<Promise<Unit>> promises(10);
     std::vector<Future<Unit>> futures;
     for (auto& p : promises) {
       futures.push_back(p.getFuture());
     }
     auto allf = collectAllSemiFuture(futures).toUnsafeFuture().then(
         [](Try<std::vector<Try<Unit>>>&& ts) {
           for (auto& f : ts.value()) {
             f.value();
           }
         });
     std::shuffle(promises.begin(), promises.end(), rng);
     for (auto& p : promises) {
       p.setValue();
     }
     EXPECT_TRUE(allf.isReady());
   }
 }
TEST (Collect , collect)
Definition at line 114 of file CollectTest.cpp.
References folly::collect(), eggs, EXPECT_EQ, EXPECT_FALSE, EXPECT_THROW, EXPECT_TRUE, i, and rng.
{
   // success case
   {
     std::vector<Promise<int>> promises(10);
     std::vector<Future<int>> futures;
     for (auto& p : promises) {
       futures.push_back(p.getFuture());
     }
     auto allf = collect(futures);
     std::shuffle(promises.begin(), promises.end(), rng);
     for (auto& p : promises) {
       EXPECT_FALSE(allf.isReady());
       p.setValue(42);
     }
     EXPECT_TRUE(allf.isReady());
     for (auto i : allf.value()) {
       EXPECT_EQ(42, i);
     }
   }
   // failure case
   {
     std::vector<Promise<int>> promises(10);
     std::vector<Future<int>> futures;
     for (auto& p : promises) {
       futures.push_back(p.getFuture());
     }
     auto allf = collect(futures);
     std::shuffle(promises.begin(), promises.end(), rng);
     for (int i = 0; i < 10; i++) {
       if (i < 5) {
         // everthing goes well so far...
         EXPECT_FALSE(allf.isReady());
         promises[i].setValue(42);
       } else if (i == 5) {
         // short circuit with an exception
         EXPECT_FALSE(allf.isReady());
         promises[i].setException(eggs);
         EXPECT_TRUE(allf.isReady());
       } else if (i < 8) {
         // don't blow up on further values
         EXPECT_TRUE(allf.isReady());
         promises[i].setValue(42);
       } else {
         // don't blow up on further exceptions
         EXPECT_TRUE(allf.isReady());
         promises[i].setException(eggs);
       }
     }
     EXPECT_THROW(allf.value(), eggs_t);
   }
   // void futures success case
   {
     std::vector<Promise<Unit>> promises(10);
     std::vector<Future<Unit>> futures;
     for (auto& p : promises) {
       futures.push_back(p.getFuture());
     }
     auto allf = collect(futures);
     std::shuffle(promises.begin(), promises.end(), rng);
     for (auto& p : promises) {
       EXPECT_FALSE(allf.isReady());
       p.setValue();
     }
     EXPECT_TRUE(allf.isReady());
   }
   // void futures failure case
   {
     std::vector<Promise<Unit>> promises(10);
     std::vector<Future<Unit>> futures;
     for (auto& p : promises) {
       futures.push_back(p.getFuture());
     }
     auto allf = collect(futures);
     std::shuffle(promises.begin(), promises.end(), rng);
     for (int i = 0; i < 10; i++) {
       if (i < 5) {
         // everthing goes well so far...
         EXPECT_FALSE(allf.isReady());
         promises[i].setValue();
       } else if (i == 5) {
         // short circuit with an exception
         EXPECT_FALSE(allf.isReady());
         promises[i].setException(eggs);
         EXPECT_TRUE(allf.isReady());
       } else if (i < 8) {
         // don't blow up on further values
         EXPECT_TRUE(allf.isReady());
         promises[i].setValue();
       } else {
         // don't blow up on further exceptions
         EXPECT_TRUE(allf.isReady());
         promises[i].setException(eggs);
       }
     }
     EXPECT_THROW(allf.value(), eggs_t);
   }
   // move only compiles
   {
     std::vector<Promise<std::unique_ptr<int>>> promises(10);
     std::vector<Future<std::unique_ptr<int>>> futures;
     for (auto& p : promises) {
       futures.push_back(p.getFuture());
     }
     collect(futures);
   }
 }
TEST (Collect , collectNotDefaultConstructible)
Definition at line 251 of file CollectTest.cpp.
References folly::collect(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, i, rng, and val.
{
   std::vector<Promise<NotDefaultConstructible>> promises(10);
   std::vector<Future<NotDefaultConstructible>> futures;
   std::vector<int> indices(10);
   std::iota(indices.begin(), indices.end(), 0);
   std::shuffle(indices.begin(), indices.end(), rng);
   for (auto& p : promises) {
     futures.push_back(p.getFuture());
   }
   auto allf = collect(futures);
   for (auto i : indices) {
     EXPECT_FALSE(allf.isReady());
     promises[i].setValue(NotDefaultConstructible(i));
   }
   EXPECT_TRUE(allf.isReady());
   int i = 0;
   for (auto val : allf.value()) {
     EXPECT_EQ(i, val.i);
     i++;
   }
 }
TEST (Collect , collectAny)
Definition at line 277 of file CollectTest.cpp.
References folly::collectAny(), eggs, EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, f, and i.
{
   {
     std::vector<Promise<int>> promises(10);
     std::vector<Future<int>> futures;
     for (auto& p : promises) {
       futures.push_back(p.getFuture());
     }
     for (auto& f : futures) {
       EXPECT_FALSE(f.isReady());
     }
     auto anyf = collectAny(futures);
     /* futures were moved in, so these are invalid now */
     EXPECT_FALSE(anyf.isReady());
     promises[7].setValue(42);
     EXPECT_TRUE(anyf.isReady());
     auto& idx_fut = anyf.value();
     auto i = idx_fut.first;
     EXPECT_EQ(7, i);
     auto& f = idx_fut.second;
     EXPECT_EQ(42, f.value());
   }
   // error
   {
     std::vector<Promise<Unit>> promises(10);
     std::vector<Future<Unit>> futures;
     for (auto& p : promises) {
       futures.push_back(p.getFuture());
     }
     for (auto& f : futures) {
       EXPECT_FALSE(f.isReady());
     }
     auto anyf = collectAny(futures);
     EXPECT_FALSE(anyf.isReady());
     promises[3].setException(eggs);
     EXPECT_TRUE(anyf.isReady());
     EXPECT_TRUE(anyf.value().second.hasException());
   }
   // then()
   {
     std::vector<Promise<int>> promises(10);
     std::vector<Future<int>> futures;
     for (auto& p : promises) {
       futures.push_back(p.getFuture());
     }
     auto anyf = collectAny(futures).then(
         [](std::pair<size_t, Try<int>> p) { EXPECT_EQ(42, p.second.value()); });
     promises[3].setValue(42);
     EXPECT_TRUE(anyf.isReady());
   }
 }
TEST (Collect , collectAnyWithoutException)
Definition at line 345 of file CollectTest.cpp.
References folly::collectAnyWithoutException(), eggs, folly::pushmi::executor, EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, i, folly::InlineExecutor::instance(), folly::gen::move, and v.
{
   auto& executor = folly::InlineExecutor::instance();
   {
     std::vector<Promise<int>> promises(10);
     std::vector<Future<int>> futures;
     for (auto& p : promises) {
       futures.push_back(p.getFuture());
     }
     auto onef = collectAnyWithoutException(futures).via(&executor);
     /* futures were moved in, so these are invalid now */
     EXPECT_FALSE(onef.isReady());
     promises[7].setValue(42);
     EXPECT_TRUE(onef.isReady());
     auto& idx_fut = onef.value();
     EXPECT_EQ(7, idx_fut.first);
     EXPECT_EQ(42, idx_fut.second);
   }
   // some exception before ready
   {
     std::vector<Promise<int>> promises(10);
     std::vector<Future<int>> futures;
     for (auto& p : promises) {
       futures.push_back(p.getFuture());
     }
     auto onef = collectAnyWithoutException(futures).via(&executor);
     EXPECT_FALSE(onef.isReady());
     promises[3].setException(eggs);
     EXPECT_FALSE(onef.isReady());
     promises[4].setException(eggs);
     EXPECT_FALSE(onef.isReady());
     promises[0].setValue(99);
     EXPECT_TRUE(onef.isReady());
     auto& idx_fut = onef.value();
     EXPECT_EQ(0, idx_fut.first);
     EXPECT_EQ(99, idx_fut.second);
   }
   // all exceptions
   {
     std::vector<Promise<int>> promises(10);
     std::vector<Future<int>> futures;
     for (auto& p : promises) {
       futures.push_back(p.getFuture());
     }
     auto onef = collectAnyWithoutException(futures).via(&executor);
     EXPECT_FALSE(onef.isReady());
     for (int i = 0; i < 9; ++i) {
       promises[i].setException(eggs);
     }
     EXPECT_FALSE(onef.isReady());
     promises[9].setException(eggs);
     EXPECT_TRUE(onef.isReady());
     EXPECT_TRUE(onef.hasException());
   }
   // Deferred work
   {
     std::vector<Promise<int>> promises(10);
     auto onef = [&] {
       std::vector<SemiFuture<int>> futures;
       for (auto& p : promises) {
         futures.push_back(
             p.getSemiFuture().deferValue([](auto v) { return v; }));
       }
       return collectAnyWithoutException(futures);
     }();
     /* futures were moved in, so these are invalid now */
     promises[7].setValue(42);
     auto idx_fut = std::move(onef).get();
     EXPECT_EQ(7, idx_fut.first);
     EXPECT_EQ(42, idx_fut.second);
   }
 }
TEST (Collect , alreadyCompleted)
Definition at line 437 of file CollectTest.cpp.
References folly::collectAllSemiFuture(), folly::collectAny(), EXPECT_EQ, i, and folly::makeFuture().
{
   {
     std::vector<Future<Unit>> fs;
     for (int i = 0; i < 10; i++) {
       fs.push_back(makeFuture());
     }
     collectAllSemiFuture(fs).toUnsafeFuture().then(
         [&](std::vector<Try<Unit>> ts) { EXPECT_EQ(fs.size(), ts.size()); });
   }
   {
     std::vector<Future<int>> fs;
     for (int i = 0; i < 10; i++) {
       fs.push_back(makeFuture(i));
     }
     collectAny(fs).then([&](std::pair<size_t, Try<int>> p) {
       EXPECT_EQ(p.first, p.second.value());
     });
   }
 }
TEST (Collect , parallel)
Definition at line 459 of file CollectTest.cpp.
References folly::collect(), EXPECT_EQ, EXPECT_TRUE, f, and i.
{
   std::vector<Promise<int>> ps(10);
   std::vector<Future<int>> fs;
   for (size_t i = 0; i < ps.size(); i++) {
     fs.emplace_back(ps[i].getFuture());
   }
   auto f = collect(fs);
   std::vector<std::thread> ts;
   boost::barrier barrier(ps.size() + 1);
   for (size_t i = 0; i < ps.size(); i++) {
     ts.emplace_back([&ps, &barrier, i]() {
       barrier.wait();
       ps[i].setValue(i);
     });
   }
   barrier.wait();
   for (size_t i = 0; i < ps.size(); i++) {
     ts[i].join();
   }
   EXPECT_TRUE(f.isReady());
   for (size_t i = 0; i < ps.size(); i++) {
     EXPECT_EQ(i, f.value()[i]);
   }
 }
TEST (Collect , parallelWithError)
Definition at line 488 of file CollectTest.cpp.
References folly::collect(), eggs, EXPECT_THROW, EXPECT_TRUE, f, and i.
{
   std::vector<Promise<int>> ps(10);
   std::vector<Future<int>> fs;
   for (size_t i = 0; i < ps.size(); i++) {
     fs.emplace_back(ps[i].getFuture());
   }
   auto f = collect(fs);
   std::vector<std::thread> ts;
   boost::barrier barrier(ps.size() + 1);
   for (size_t i = 0; i < ps.size(); i++) {
     ts.emplace_back([&ps, &barrier, i]() {
       barrier.wait();
       if (i == (ps.size() / 2)) {
         ps[i].setException(eggs);
       } else {
         ps[i].setValue(i);
       }
     });
   }
   barrier.wait();
   for (size_t i = 0; i < ps.size(); i++) {
     ts[i].join();
   }
   EXPECT_TRUE(f.isReady());
   EXPECT_THROW(f.value(), eggs_t);
 }
TEST (Collect , allParallel)
Definition at line 519 of file CollectTest.cpp.
References folly::collectAll(), EXPECT_EQ, EXPECT_TRUE, f, and i.
{
   std::vector<Promise<int>> ps(10);
   std::vector<Future<int>> fs;
   for (size_t i = 0; i < ps.size(); i++) {
     fs.emplace_back(ps[i].getFuture());
   }
   auto f = collectAll(fs);
   std::vector<std::thread> ts;
   boost::barrier barrier(ps.size() + 1);
   for (size_t i = 0; i < ps.size(); i++) {
     ts.emplace_back([&ps, &barrier, i]() {
       barrier.wait();
       ps[i].setValue(i);
     });
   }
   barrier.wait();
   for (size_t i = 0; i < ps.size(); i++) {
     ts[i].join();
   }
   EXPECT_TRUE(f.isReady());
   for (size_t i = 0; i < ps.size(); i++) {
     EXPECT_TRUE(f.value()[i].hasValue());
     EXPECT_EQ(i, f.value()[i].value());
   }
 }
TEST (Collect , allParallelWithError)
Definition at line 549 of file CollectTest.cpp.
References folly::collectAll(), eggs, EXPECT_EQ, EXPECT_THROW, EXPECT_TRUE, f, and i.
{
   std::vector<Promise<int>> ps(10);
   std::vector<Future<int>> fs;
   for (size_t i = 0; i < ps.size(); i++) {
     fs.emplace_back(ps[i].getFuture());
   }
   auto f = collectAll(fs);
   std::vector<std::thread> ts;
   boost::barrier barrier(ps.size() + 1);
   for (size_t i = 0; i < ps.size(); i++) {
     ts.emplace_back([&ps, &barrier, i]() {
       barrier.wait();
       if (i == (ps.size() / 2)) {
         ps[i].setException(eggs);
       } else {
         ps[i].setValue(i);
       }
     });
   }
   barrier.wait();
   for (size_t i = 0; i < ps.size(); i++) {
     ts[i].join();
   }
   EXPECT_TRUE(f.isReady());
   for (size_t i = 0; i < ps.size(); i++) {
     if (i == (ps.size() / 2)) {
       EXPECT_THROW(f.value()[i].value(), eggs_t);
     } else {
       EXPECT_TRUE(f.value()[i].hasValue());
       EXPECT_EQ(i, f.value()[i].value());
     }
   }
 }
TEST (Collect , collectN)
Definition at line 587 of file CollectTest.cpp.
References folly::collectN(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, flag, and folly::InlineExecutor::instance().
{
   std::vector<Promise<Unit>> promises(10);
   std::vector<Future<Unit>> futures;
   for (auto& p : promises) {
     futures.push_back(p.getFuture());
   }
   bool flag = false;
   size_t n = 3;
   collectN(futures, n)
       .via(&InlineExecutor::instance())
       .then([&](std::vector<std::pair<size_t, Try<Unit>>> v) {
         flag = true;
         EXPECT_EQ(n, v.size());
         for (auto& tt : v) {
           EXPECT_TRUE(tt.second.hasValue());
         }
       });
   promises[0].setValue();
   EXPECT_FALSE(flag);
   promises[1].setValue();
   EXPECT_FALSE(flag);
   promises[2].setValue();
   EXPECT_TRUE(flag);
 }
TEST (Collect , collectNParallel)
Definition at line 615 of file CollectTest.cpp.
References folly::collectN(), EXPECT_EQ, EXPECT_TRUE, flag, i, and folly::InlineExecutor::instance().
{
   std::vector<Promise<Unit>> ps(100);
   std::vector<Future<Unit>> futures;
   for (auto& p : ps) {
     futures.push_back(p.getFuture());
   }
   bool flag = false;
   size_t n = 90;
   collectN(futures, n)
       .via(&InlineExecutor::instance())
       .then([&](std::vector<std::pair<size_t, Try<Unit>>> v) {
         flag = true;
         EXPECT_EQ(n, v.size());
         for (auto& tt : v) {
           EXPECT_TRUE(tt.second.hasValue());
         }
       });
   std::vector<std::thread> ts;
   boost::barrier barrier(ps.size() + 1);
   for (size_t i = 0; i < ps.size(); i++) {
     ts.emplace_back([&ps, &barrier, i]() {
       barrier.wait();
       ps[i].setValue();
     });
   }
   barrier.wait();
   for (size_t i = 0; i < ps.size(); i++) {
     ts[i].join();
   }
   EXPECT_TRUE(flag);
 }
TEST (Collect , smallVector)
Ensure that we can compile collectAll/Any with folly::small_vector.
Definition at line 654 of file CollectTest.cpp.
References folly::collectAll(), folly::collectAny(), i, folly::makeFuture(), folly::small_vector< Value, RequestedMaxInline, PolicyA, PolicyB, PolicyC >::push_back(), and folly::value().
{
   static_assert(
       !folly::is_trivially_copyable<Future<Unit>>::value,
       "Futures should not be trivially copyable");
   static_assert(
       !folly::is_trivially_copyable<Future<int>>::value,
       "Futures should not be trivially copyable");
   {
     folly::small_vector<Future<Unit>> futures;
     for (int i = 0; i < 10; i++) {
       futures.push_back(makeFuture());
     }
     auto anyf = collectAny(futures);
   }
   {
     folly::small_vector<Future<Unit>> futures;
     for (int i = 0; i < 10; i++) {
       futures.push_back(makeFuture());
     }
     auto allf = collectAll(futures);
   }
 }
TEST (Collect , collectAllVariadic)
Definition at line 682 of file CollectTest.cpp.
References folly::collectAllSemiFuture(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, flag, folly::Promise< T >::getFuture(), folly::gen::move, folly::Promise< T >::setValue(), and folly::value().
{
   Promise<bool> pb;
   Promise<int> pi;
   Future<bool> fb = pb.getFuture();
   Future<int> fi = pi.getFuture();
   bool flag = false;
   collectAllSemiFuture(std::move(fb), std::move(fi))
       .toUnsafeFuture()
       .then([&](std::tuple<Try<bool>, Try<int>> tup) {
         flag = true;
         EXPECT_TRUE(std::get<0>(tup).hasValue());
         EXPECT_EQ(std::get<0>(tup).value(), true);
         EXPECT_TRUE(std::get<1>(tup).hasValue());
         EXPECT_EQ(std::get<1>(tup).value(), 42);
       });
   pb.setValue(true);
   EXPECT_FALSE(flag);
   pi.setValue(42);
   EXPECT_TRUE(flag);
 }
TEST (Collect , collectAllVariadicReferences)
Definition at line 703 of file CollectTest.cpp.
References folly::collectAllSemiFuture(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, flag, folly::Promise< T >::getFuture(), folly::Promise< T >::setValue(), and folly::value().
{
   Promise<bool> pb;
   Promise<int> pi;
   Future<bool> fb = pb.getFuture();
   Future<int> fi = pi.getFuture();
   bool flag = false;
   collectAllSemiFuture(fb, fi).toUnsafeFuture().then(
       [&](std::tuple<Try<bool>, Try<int>> tup) {
         flag = true;
         EXPECT_TRUE(std::get<0>(tup).hasValue());
         EXPECT_EQ(std::get<0>(tup).value(), true);
         EXPECT_TRUE(std::get<1>(tup).hasValue());
         EXPECT_EQ(std::get<1>(tup).value(), 42);
       });
   pb.setValue(true);
   EXPECT_FALSE(flag);
   pi.setValue(42);
   EXPECT_TRUE(flag);
 }
TEST (Collect , collectAllVariadicWithException)
Definition at line 723 of file CollectTest.cpp.
References folly::collectAllSemiFuture(), eggs, EXPECT_EQ, EXPECT_FALSE, EXPECT_THROW, EXPECT_TRUE, flag, folly::Promise< T >::getFuture(), folly::gen::move, folly::Promise< T >::setException(), folly::Promise< T >::setValue(), and folly::value().
{
   Promise<bool> pb;
   Promise<int> pi;
   Future<bool> fb = pb.getFuture();
   Future<int> fi = pi.getFuture();
   bool flag = false;
   collectAllSemiFuture(std::move(fb), std::move(fi))
       .toUnsafeFuture()
       .then([&](std::tuple<Try<bool>, Try<int>> tup) {
         flag = true;
         EXPECT_TRUE(std::get<0>(tup).hasValue());
         EXPECT_EQ(std::get<0>(tup).value(), true);
         EXPECT_TRUE(std::get<1>(tup).hasException());
         EXPECT_THROW(std::get<1>(tup).value(), eggs_t);
       });
   pb.setValue(true);
   EXPECT_FALSE(flag);
   pi.setException(eggs);
   EXPECT_TRUE(flag);
 }
TEST (Collect , collectVariadic)
Definition at line 744 of file CollectTest.cpp.
References folly::collect(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, flag, folly::Promise< T >::getFuture(), folly::gen::move, and folly::Promise< T >::setValue().
{
   Promise<bool> pb;
   Promise<int> pi;
   Future<bool> fb = pb.getFuture();
   Future<int> fi = pi.getFuture();
   bool flag = false;
   collect(std::move(fb), std::move(fi)).then([&](std::tuple<bool, int> tup) {
     flag = true;
     EXPECT_EQ(std::get<0>(tup), true);
     EXPECT_EQ(std::get<1>(tup), 42);
   });
   pb.setValue(true);
   EXPECT_FALSE(flag);
   pi.setValue(42);
   EXPECT_TRUE(flag);
 }
TEST (Collect , collectVariadicWithException)
Definition at line 761 of file CollectTest.cpp.
References folly::collect(), eggs, EXPECT_FALSE, EXPECT_THROW, EXPECT_TRUE, f, folly::Promise< T >::getFuture(), folly::gen::move, folly::Promise< T >::setException(), and folly::Promise< T >::setValue().
{
   Promise<bool> pb;
   Promise<int> pi;
   Future<bool> fb = pb.getFuture();
   Future<int> fi = pi.getFuture();
   auto f = collect(std::move(fb), std::move(fi));
   pb.setValue(true);
   EXPECT_FALSE(f.isReady());
   pi.setException(eggs);
   EXPECT_TRUE(f.isReady());
   EXPECT_TRUE(f.getTry().hasException());
   EXPECT_THROW(std::move(f).get(), eggs_t);
 }
TEST (Collect , collectAllNone)
Definition at line 775 of file CollectTest.cpp.
References folly::collectAll(), EXPECT_TRUE, and f.
{
   std::vector<Future<int>> fs;
   auto f = collectAll(fs);
   EXPECT_TRUE(f.isReady());
 }
TEST (Collect , noDefaultConstructor)
Definition at line 781 of file CollectTest.cpp.
References folly::collect(), f, folly::makeFuture(), and folly::gen::move.
{
   struct A {
     explicit A(size_t /* x */) {}
   };
   auto f1 = makeFuture(A(1));
   auto f2 = makeFuture(A(2));
   auto f = collect(std::move(f1), std::move(f2));
 }
Variable Documentation
eggs_t eggs("eggs") static
Referenced by TEST().
auto rng = std::mt19937(folly::randomNumberSeed())
Definition at line 31 of file CollectTest.cpp.
Referenced by accuracy_test(), BENCHMARK(), concurrentOps(), concurrentPopforSharedBuffer(), concurrentPush(), concurrentSizeTest(), DSchedMixedTest(), folly::sync_tests::getRNG(), proxygen::parse(), proxygen::parseUnidirectional(), folly::SSLContext::passwordCollector(), producer_consumer_test(), folly::Random::rand32(), folly::Random::rand64(), folly::Random::randDouble01(), detail::randomBytes(), folly::io::test::RandomDataHolder::RandomDataHolder(), folly::futures::detail::retryingPolicyCappedJitteredExponentialBackoff(), folly::futures::retryingPolicyCappedJitteredExponentialBackoff(), folly::gen::sample(), folly::Random::secureRandDouble(), singleThreadTest(), folly::test::TEST(), TEST(), TEST_F(), and throughtput_test().