proxygen: proxygen/folly/folly/experimental/pushmi/examples/composition/composition_3.cpp File Reference
composition_3.cpp File Reference
#include <algorithm>
#include <cassert>
#include <iostream>
#include <vector>
#include <folly/experimental/pushmi/o/defer.h>
#include <folly/experimental/pushmi/o/share.h>
#include <folly/experimental/pushmi/o/just.h>
#include <folly/experimental/pushmi/o/tap.h>
Functions
auto defer_execution ()
auto defer_construction ()
auto eager_execution ()
int main ()
Function Documentation
auto defer_construction ()
Definition at line 42 of file composition_3.cpp.
References folly::pushmi::operators::defer, and defer_execution().
Referenced by main().
{
   return op::defer([] { return defer_execution(); });
 }
auto defer_execution ()
Definition at line 36 of file composition_3.cpp.
References folly::pushmi::operators::just, and folly::pushmi::operators::tap.
Referenced by defer_construction(), eager_execution(), and main().
{
   printf("construct just\n");
   return op::just(42) | op::tap([](int v) { printf("just - %d\n", v); });
 }
auto eager_execution ()
Definition at line 47 of file composition_3.cpp.
References defer_execution().
Referenced by main().
{
   return defer_execution() | op::share<int>();
 }
int main (void)
Definition at line 51 of file composition_3.cpp.
References defer_construction(), defer_execution(), eager_execution(), and submit.
            {
   printf("\ncall defer_execution\n");
   auto de = defer_execution();
   printf("submit defer_execution\n");
   de | op::submit();
   // call defer_execution
   // construct just
   // submit defer_execution
   // just - 42
   printf("\ncall defer_construction\n");
   auto dc = defer_construction();
   printf("submit defer_construction\n");
   dc | op::submit();
   // call defer_construction
   // submit defer_construction
   // construct just
   // just - 42
   printf("\ncall eager_execution\n");
   auto ee = eager_execution();
   printf("submit eager_execution\n");
   ee | op::submit();
   // call eager_execution
   // construct just
   // just - 42
   // submit eager_execution
   std::cout << "OK" << std::endl;
   // OK
 }