proxygen: proxygen/folly/folly/experimental/pushmi/examples/composition/composition_4.cpp File Reference
composition_4.cpp File Reference
#include <algorithm>
#include <cassert>
#include <iostream>
#include <vector>
#include <folly/experimental/pushmi/examples/pool.h>
#include <folly/experimental/pushmi/strand.h>
#include <folly/experimental/pushmi/o/request_via.h>
#include <folly/experimental/pushmi/o/tap.h>
#include <folly/experimental/pushmi/o/transform.h>
Functions
template<class Io >
auto io_operation (Io io)
int main ()
Function Documentation
template<class Io > auto io_operation (Io io)
Definition at line 33 of file composition_4.cpp.
References folly::pushmi::operators::request_via, folly::pushmi::operators::tap, and folly::pushmi::operators::transform.
Referenced by main().
{
   return io | op::transform([](auto) { return 42; }) |
       op::tap([](int v) { printf("io pool producing, %d\n", v); }) |
       op::request_via();
 }
int main (void)
Definition at line 39 of file composition_4.cpp.
References io_operation(), max, folly::pushmi::strands(), submit, folly::pushmi::operators::tap, and folly::pushmi::via_cast().
            {
   mi::pool cpuPool{std::max(1u, std::thread::hardware_concurrency())};
   mi::pool ioPool{std::max(1u, std::thread::hardware_concurrency())};
   auto io = ioPool.executor();
   auto cpu = cpuPool.executor();
   io_operation(io).via(mi::strands(cpu)) |
       op::tap([](int v) { printf("cpu pool processing, %d\n", v); }) |
       op::submit();
   // when the caller is not going to process the result (only side-effect
   // matters) or the caller is just going to push the result into a queue.
   // provide a way to skip the transition to a different executor and make it
   // stand out so that it has to be justified in code reviews.
   mi::via_cast<mi::is_sender<>>(io_operation(io)) | op::submit();
   ioPool.wait();
   cpuPool.wait();
   std::cout << "OK" << std::endl;
 }