proxygen: proxygen/folly/folly/portability/test/ConstexprTest.cpp File Reference
ConstexprTest.cpp File Reference
#include <folly/portability/Constexpr.h>
#include <folly/portability/GTest.h>
Functions
TEST (ConstexprTest, constexpr_strlen_cstr)
TEST (ConstexprTest, constexpr_strlen_ints)
TEST (ConstexprTest, constexpr_strcmp_ints)
Function Documentation
TEST (ConstexprTest , constexpr_strlen_cstr)
Definition at line 23 of file ConstexprTest.cpp.
References a, folly::constexpr_strlen(), EXPECT_EQ, EXPECT_TRUE, and value.
{
   constexpr auto v = "hello";
   constexpr auto a = folly::constexpr_strlen(v);
   EXPECT_EQ(5, a);
   EXPECT_TRUE((std::is_same<const size_t, decltype(a)>::value));
 }
TEST (ConstexprTest , constexpr_strlen_ints)
Definition at line 32 of file ConstexprTest.cpp.
References a, folly::constexpr_strlen(), EXPECT_EQ, EXPECT_TRUE, and value.
{
   constexpr int v[] = {5, 3, 4, 0, 7};
   constexpr auto a = folly::constexpr_strlen(v);
   EXPECT_EQ(3, a);
   EXPECT_TRUE((std::is_same<const size_t, decltype(a)>::value));
 }
TEST (ConstexprTest , constexpr_strcmp_ints)
Definition at line 39 of file ConstexprTest.cpp.
References folly::constexpr_strcmp().
{
   constexpr int v[] = {5, 3, 4, 0, 7};
   constexpr int v1[] = {6, 4};
   static_assert(constexpr_strcmp(v1, v) > 0, "constexpr_strcmp is broken");
   static_assert(constexpr_strcmp(v, v) == 0, "constexpr_strcmp is broken");
 }