proxygen: proxygen/folly/folly/futures/test/ContextTest.cpp File Reference
ContextTest.cpp File Reference
#include <folly/futures/Future.h>
#include <folly/portability/GTest.h>
#include <memory>
Classes
class TestData
Functions
TEST (Context, basic)
Function Documentation
TEST (Context , basic)
Definition at line 36 of file ContextTest.cpp.
References a, folly::data(), EXPECT_EQ, EXPECT_TRUE, folly::RequestContext::get(), folly::RequestContext::getContextData(), folly::Promise< T >::getFuture(), folly::RequestContext::setContext(), folly::RequestContext::setContextData(), and folly::Promise< T >::setValue().
                      {
   // Start a new context
   folly::RequestContextScopeGuard rctx;
   EXPECT_EQ(nullptr, RequestContext::get()->getContextData("test"));
   // Set some test data
   RequestContext::get()->setContextData("test", std::make_unique<TestData>(10));
   // Start a future
   Promise<Unit> p;
   auto future = p.getFuture().thenValue([&](auto&&) {
     // Check that the context followed the future
     EXPECT_TRUE(RequestContext::get() != nullptr);
     auto a =
         dynamic_cast<TestData*>(RequestContext::get()->getContextData("test"));
     auto data = a->data_;
     EXPECT_EQ(10, data);
   });
   // Clear the context
   RequestContext::setContext(nullptr);
   EXPECT_EQ(nullptr, RequestContext::get()->getContextData("test"));
   // Fulfill the promise
   p.setValue();
 }