proxygen: proxygen/folly/folly/test/ConvBenchmark.cpp File Reference
ConvBenchmark.cpp File Reference
#include <folly/Conv.h>
#include <boost/lexical_cast.hpp>
#include <folly/Benchmark.h>
#include <folly/CppAttributes.h>
#include <folly/container/Foreach.h>
#include <array>
#include <limits>
#include <stdexcept>
Classes
struct StringIdenticalToBM< String >
struct StringVariadicToBM< String >
Namespaces
folly
—— Concurrent Priority Queue Implementation ——
folly::conv_bench_detail
Macros
#define FOLLY_RANGE_CHECK_TO_STRING(x) std::to_string(x)
#define DEFINE_BENCHMARK_GROUP(n)
#define DEFINE_BENCHMARK_GROUP(n)
#define DEFINE_BENCHMARK_GROUP(n)
#define DEFINE_BENCHMARK_GROUP(T, n)
#define STRING_TO_TYPE_BENCHMARK(type, name, pass, fail)
#define PTR_PAIR_TO_INT_BENCHMARK(type, name, pass, fail)
#define ARITH_TO_ARITH_BENCHMARK(type, name, pass, fail)
#define INT_TO_ARITH_BENCHMARK(type, name, pass, fail) ARITH_TO_ARITH_BENCHMARK(type, intTo##name, pass, fail)
#define FLOAT_TO_ARITH_BENCHMARK(type, name, pass, fail) ARITH_TO_ARITH_BENCHMARK(type, floatTo##name, pass, fail)
Functions
static int64_t handwrittenAtoi (const char *start, const char *end)
void handwrittenAtoiMeasure (unsigned int n, unsigned int digits)
void follyAtoiMeasure (unsigned int n, unsigned int digits)
void clibAtoiMeasure (unsigned int n, unsigned int digits)
void lexicalCastMeasure (unsigned int n, unsigned int digits)
unsigned u64ToAsciiTable (uint64_t value, char *dst)
void u64ToAsciiTableBM (unsigned int n, size_t index)
unsigned u64ToAsciiClassic (uint64_t value, char *dst)
void u64ToAsciiClassicBM (unsigned int n, size_t index)
void u64ToAsciiFollyBM (unsigned int n, size_t index)
void u64ToStringClibMeasure (unsigned int n, size_t index)
void u64ToStringFollyMeasure (unsigned int n, size_t index)
void i64ToStringFollyMeasurePos (unsigned int n, size_t index)
void i64ToStringFollyMeasureNeg (unsigned int n, size_t index)
void u2aAppendClassicBM (unsigned int n, size_t index)
void u2aAppendFollyBM (unsigned int n, size_t index)
BENCHMARK (preallocateTestNoFloat, n)
BENCHMARK (preallocateTestFloat, n)
BENCHMARK (preallocateTestInt8, n)
BENCHMARK (preallocateTestInt16, n)
BENCHMARK (preallocateTestInt32, n)
BENCHMARK (preallocateTestInt64, n)
BENCHMARK_DRAW_LINE ()
BENCHMARK_PARAM (u64ToAsciiClassicBM, 1) BENCHMARK_RELATIVE_PARAM(u64ToAsciiTableBM
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM, 1) BENCHMARK_DRAW_LINE()
BENCHMARK_PARAM (u64ToAsciiClassicBM, 2) BENCHMARK_RELATIVE_PARAM(u64ToAsciiTableBM
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM, 2) BENCHMARK_DRAW_LINE()
BENCHMARK_PARAM (u64ToAsciiClassicBM, 3) BENCHMARK_RELATIVE_PARAM(u64ToAsciiTableBM
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM, 3) BENCHMARK_DRAW_LINE()
BENCHMARK_PARAM (u64ToAsciiClassicBM, 4) BENCHMARK_RELATIVE_PARAM(u64ToAsciiTableBM
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM, 4) BENCHMARK_DRAW_LINE()
BENCHMARK_PARAM (u64ToAsciiClassicBM, 5) BENCHMARK_RELATIVE_PARAM(u64ToAsciiTableBM
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM, 5) BENCHMARK_DRAW_LINE()
BENCHMARK_PARAM (u64ToAsciiClassicBM, 6) BENCHMARK_RELATIVE_PARAM(u64ToAsciiTableBM
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM, 6) BENCHMARK_DRAW_LINE()
BENCHMARK_PARAM (u64ToAsciiClassicBM, 7) BENCHMARK_RELATIVE_PARAM(u64ToAsciiTableBM
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM, 7) BENCHMARK_DRAW_LINE()
BENCHMARK_PARAM (u64ToAsciiClassicBM, 8) BENCHMARK_RELATIVE_PARAM(u64ToAsciiTableBM
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM, 8) BENCHMARK_DRAW_LINE()
BENCHMARK_PARAM (u64ToAsciiClassicBM, 9) BENCHMARK_RELATIVE_PARAM(u64ToAsciiTableBM
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM, 9) BENCHMARK_DRAW_LINE()
BENCHMARK_PARAM (u64ToAsciiClassicBM, 10) BENCHMARK_RELATIVE_PARAM(u64ToAsciiTableBM
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM, 10) BENCHMARK_DRAW_LINE()
BENCHMARK_PARAM (u64ToAsciiClassicBM, 11) BENCHMARK_RELATIVE_PARAM(u64ToAsciiTableBM
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM, 11) BENCHMARK_DRAW_LINE()
BENCHMARK_PARAM (u64ToAsciiClassicBM, 12) BENCHMARK_RELATIVE_PARAM(u64ToAsciiTableBM
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM, 12) BENCHMARK_DRAW_LINE()
BENCHMARK_PARAM (u64ToAsciiClassicBM, 13) BENCHMARK_RELATIVE_PARAM(u64ToAsciiTableBM
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM, 13) BENCHMARK_DRAW_LINE()
BENCHMARK_PARAM (u64ToAsciiClassicBM, 14) BENCHMARK_RELATIVE_PARAM(u64ToAsciiTableBM
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM, 14) BENCHMARK_DRAW_LINE()
BENCHMARK_PARAM (u64ToAsciiClassicBM, 15) BENCHMARK_RELATIVE_PARAM(u64ToAsciiTableBM
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM, 15) BENCHMARK_DRAW_LINE()
BENCHMARK_PARAM (u64ToAsciiClassicBM, 16) BENCHMARK_RELATIVE_PARAM(u64ToAsciiTableBM
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM, 16) BENCHMARK_DRAW_LINE()
BENCHMARK_PARAM (u64ToAsciiClassicBM, 17) BENCHMARK_RELATIVE_PARAM(u64ToAsciiTableBM
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM, 17) BENCHMARK_DRAW_LINE()
BENCHMARK_PARAM (u64ToAsciiClassicBM, 18) BENCHMARK_RELATIVE_PARAM(u64ToAsciiTableBM
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM, 18) BENCHMARK_DRAW_LINE()
BENCHMARK_PARAM (u64ToAsciiClassicBM, 19) BENCHMARK_RELATIVE_PARAM(u64ToAsciiTableBM
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM, 19) BENCHMARK_DRAW_LINE()
BENCHMARK_PARAM (u64ToAsciiClassicBM, 20) BENCHMARK_RELATIVE_PARAM(u64ToAsciiTableBM
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM, 20) BENCHMARK_DRAW_LINE()
BENCHMARK_PARAM (u64ToStringClibMeasure, 1) BENCHMARK_RELATIVE_PARAM(u64ToStringFollyMeasure
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos, 1) BENCHMARK_RELATIVE_PARAM(i64ToStringFollyMeasureNeg
BENCHMARK_PARAM (u64ToStringClibMeasure, 2) BENCHMARK_RELATIVE_PARAM(u64ToStringFollyMeasure
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos, 2) BENCHMARK_RELATIVE_PARAM(i64ToStringFollyMeasureNeg
BENCHMARK_PARAM (u64ToStringClibMeasure, 3) BENCHMARK_RELATIVE_PARAM(u64ToStringFollyMeasure
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos, 3) BENCHMARK_RELATIVE_PARAM(i64ToStringFollyMeasureNeg
BENCHMARK_PARAM (u64ToStringClibMeasure, 4) BENCHMARK_RELATIVE_PARAM(u64ToStringFollyMeasure
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos, 4) BENCHMARK_RELATIVE_PARAM(i64ToStringFollyMeasureNeg
BENCHMARK_PARAM (u64ToStringClibMeasure, 5) BENCHMARK_RELATIVE_PARAM(u64ToStringFollyMeasure
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos, 5) BENCHMARK_RELATIVE_PARAM(i64ToStringFollyMeasureNeg
BENCHMARK_PARAM (u64ToStringClibMeasure, 6) BENCHMARK_RELATIVE_PARAM(u64ToStringFollyMeasure
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos, 6) BENCHMARK_RELATIVE_PARAM(i64ToStringFollyMeasureNeg
BENCHMARK_PARAM (u64ToStringClibMeasure, 7) BENCHMARK_RELATIVE_PARAM(u64ToStringFollyMeasure
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos, 7) BENCHMARK_RELATIVE_PARAM(i64ToStringFollyMeasureNeg
BENCHMARK_PARAM (u64ToStringClibMeasure, 8) BENCHMARK_RELATIVE_PARAM(u64ToStringFollyMeasure
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos, 8) BENCHMARK_RELATIVE_PARAM(i64ToStringFollyMeasureNeg
BENCHMARK_PARAM (u64ToStringClibMeasure, 9) BENCHMARK_RELATIVE_PARAM(u64ToStringFollyMeasure
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos, 9) BENCHMARK_RELATIVE_PARAM(i64ToStringFollyMeasureNeg
BENCHMARK_PARAM (u64ToStringClibMeasure, 10) BENCHMARK_RELATIVE_PARAM(u64ToStringFollyMeasure
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos, 10) BENCHMARK_RELATIVE_PARAM(i64ToStringFollyMeasureNeg
BENCHMARK_PARAM (u64ToStringClibMeasure, 11) BENCHMARK_RELATIVE_PARAM(u64ToStringFollyMeasure
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos, 11) BENCHMARK_RELATIVE_PARAM(i64ToStringFollyMeasureNeg
BENCHMARK_PARAM (u64ToStringClibMeasure, 12) BENCHMARK_RELATIVE_PARAM(u64ToStringFollyMeasure
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos, 12) BENCHMARK_RELATIVE_PARAM(i64ToStringFollyMeasureNeg
BENCHMARK_PARAM (u64ToStringClibMeasure, 13) BENCHMARK_RELATIVE_PARAM(u64ToStringFollyMeasure
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos, 13) BENCHMARK_RELATIVE_PARAM(i64ToStringFollyMeasureNeg
BENCHMARK_PARAM (u64ToStringClibMeasure, 14) BENCHMARK_RELATIVE_PARAM(u64ToStringFollyMeasure
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos, 14) BENCHMARK_RELATIVE_PARAM(i64ToStringFollyMeasureNeg
BENCHMARK_PARAM (u64ToStringClibMeasure, 15) BENCHMARK_RELATIVE_PARAM(u64ToStringFollyMeasure
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos, 15) BENCHMARK_RELATIVE_PARAM(i64ToStringFollyMeasureNeg
BENCHMARK_PARAM (u64ToStringClibMeasure, 16) BENCHMARK_RELATIVE_PARAM(u64ToStringFollyMeasure
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos, 16) BENCHMARK_RELATIVE_PARAM(i64ToStringFollyMeasureNeg
BENCHMARK_PARAM (u64ToStringClibMeasure, 17) BENCHMARK_RELATIVE_PARAM(u64ToStringFollyMeasure
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos, 17) BENCHMARK_RELATIVE_PARAM(i64ToStringFollyMeasureNeg
BENCHMARK_PARAM (u64ToStringClibMeasure, 18) BENCHMARK_RELATIVE_PARAM(u64ToStringFollyMeasure
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos, 18) BENCHMARK_RELATIVE_PARAM(i64ToStringFollyMeasureNeg
BENCHMARK_PARAM (u64ToStringClibMeasure, 19) BENCHMARK_RELATIVE_PARAM(u64ToStringFollyMeasure
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos, 19) BENCHMARK_RELATIVE_PARAM(i64ToStringFollyMeasureNeg
BENCHMARK_PARAM (clibAtoiMeasure, 1) BENCHMARK_RELATIVE_PARAM(lexicalCastMeasure
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure, 1) BENCHMARK_RELATIVE_PARAM(follyAtoiMeasure
BENCHMARK_PARAM (clibAtoiMeasure, 2) BENCHMARK_RELATIVE_PARAM(lexicalCastMeasure
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure, 2) BENCHMARK_RELATIVE_PARAM(follyAtoiMeasure
BENCHMARK_PARAM (clibAtoiMeasure, 3) BENCHMARK_RELATIVE_PARAM(lexicalCastMeasure
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure, 3) BENCHMARK_RELATIVE_PARAM(follyAtoiMeasure
BENCHMARK_PARAM (clibAtoiMeasure, 4) BENCHMARK_RELATIVE_PARAM(lexicalCastMeasure
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure, 4) BENCHMARK_RELATIVE_PARAM(follyAtoiMeasure
BENCHMARK_PARAM (clibAtoiMeasure, 5) BENCHMARK_RELATIVE_PARAM(lexicalCastMeasure
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure, 5) BENCHMARK_RELATIVE_PARAM(follyAtoiMeasure
BENCHMARK_PARAM (clibAtoiMeasure, 6) BENCHMARK_RELATIVE_PARAM(lexicalCastMeasure
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure, 6) BENCHMARK_RELATIVE_PARAM(follyAtoiMeasure
BENCHMARK_PARAM (clibAtoiMeasure, 7) BENCHMARK_RELATIVE_PARAM(lexicalCastMeasure
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure, 7) BENCHMARK_RELATIVE_PARAM(follyAtoiMeasure
BENCHMARK_PARAM (clibAtoiMeasure, 8) BENCHMARK_RELATIVE_PARAM(lexicalCastMeasure
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure, 8) BENCHMARK_RELATIVE_PARAM(follyAtoiMeasure
BENCHMARK_PARAM (clibAtoiMeasure, 9) BENCHMARK_RELATIVE_PARAM(lexicalCastMeasure
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure, 9) BENCHMARK_RELATIVE_PARAM(follyAtoiMeasure
BENCHMARK_PARAM (clibAtoiMeasure, 10) BENCHMARK_RELATIVE_PARAM(lexicalCastMeasure
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure, 10) BENCHMARK_RELATIVE_PARAM(follyAtoiMeasure
BENCHMARK_PARAM (clibAtoiMeasure, 11) BENCHMARK_RELATIVE_PARAM(lexicalCastMeasure
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure, 11) BENCHMARK_RELATIVE_PARAM(follyAtoiMeasure
BENCHMARK_PARAM (clibAtoiMeasure, 12) BENCHMARK_RELATIVE_PARAM(lexicalCastMeasure
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure, 12) BENCHMARK_RELATIVE_PARAM(follyAtoiMeasure
BENCHMARK_PARAM (clibAtoiMeasure, 13) BENCHMARK_RELATIVE_PARAM(lexicalCastMeasure
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure, 13) BENCHMARK_RELATIVE_PARAM(follyAtoiMeasure
BENCHMARK_PARAM (clibAtoiMeasure, 14) BENCHMARK_RELATIVE_PARAM(lexicalCastMeasure
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure, 14) BENCHMARK_RELATIVE_PARAM(follyAtoiMeasure
BENCHMARK_PARAM (clibAtoiMeasure, 15) BENCHMARK_RELATIVE_PARAM(lexicalCastMeasure
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure, 15) BENCHMARK_RELATIVE_PARAM(follyAtoiMeasure
BENCHMARK_PARAM (clibAtoiMeasure, 16) BENCHMARK_RELATIVE_PARAM(lexicalCastMeasure
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure, 16) BENCHMARK_RELATIVE_PARAM(follyAtoiMeasure
BENCHMARK_PARAM (clibAtoiMeasure, 17) BENCHMARK_RELATIVE_PARAM(lexicalCastMeasure
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure, 17) BENCHMARK_RELATIVE_PARAM(follyAtoiMeasure
BENCHMARK_PARAM (clibAtoiMeasure, 18) BENCHMARK_RELATIVE_PARAM(lexicalCastMeasure
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure, 18) BENCHMARK_RELATIVE_PARAM(follyAtoiMeasure
BENCHMARK_PARAM (clibAtoiMeasure, 19) BENCHMARK_RELATIVE_PARAM(lexicalCastMeasure
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure, 19) BENCHMARK_RELATIVE_PARAM(follyAtoiMeasure
BENCHMARK_PARAM (stringVariadicToBM, 32) BENCHMARK_RELATIVE_PARAM(stringIdenticalToBM
BENCHMARK_PARAM (stringVariadicToBM, 1024) BENCHMARK_RELATIVE_PARAM(stringIdenticalToBM
BENCHMARK_PARAM (stringVariadicToBM, 32768) BENCHMARK_RELATIVE_PARAM(stringIdenticalToBM
BENCHMARK_PARAM (fbstringVariadicToBM, 32) BENCHMARK_RELATIVE_PARAM(fbstringIdenticalToBM
BENCHMARK_PARAM (fbstringVariadicToBM, 1024) BENCHMARK_RELATIVE_PARAM(fbstringIdenticalToBM
BENCHMARK_PARAM (fbstringVariadicToBM, 32768) BENCHMARK_RELATIVE_PARAM(fbstringIdenticalToBM
BENCHMARK (stringToBoolNumClassic, n)
BENCHMARK (stringToBoolNumClassicError, n)
BENCHMARK (stringToBoolNumOptional, n)
BENCHMARK (stringToBoolNumOptionalError, n)
BENCHMARK (stringToBoolStrClassic, n)
BENCHMARK (stringToBoolStrClassicError, n)
BENCHMARK (stringToBoolStrOptional, n)
BENCHMARK (stringToBoolStrOptionalError, n)
BENCHMARK (stringToFloatNumClassic, n)
BENCHMARK (stringToFloatNumClassicError, n)
BENCHMARK (stringToFloatNumOptional, n)
BENCHMARK (stringToFloatNumOptionalError, n)
BENCHMARK (stringToFloatStrClassic, n)
BENCHMARK (stringToFloatStrClassicError, n)
BENCHMARK (stringToFloatStrOptional, n)
BENCHMARK (stringToFloatStrOptionalError, n)
BENCHMARK (stringToDoubleNumClassic, n)
BENCHMARK (stringToDoubleNumClassicError, n)
BENCHMARK (stringToDoubleNumOptional, n)
BENCHMARK (stringToDoubleNumOptionalError, n)
BENCHMARK (stringToDoubleStrClassic, n)
BENCHMARK (stringToDoubleStrClassicError, n)
BENCHMARK (stringToDoubleStrOptional, n)
BENCHMARK (stringToDoubleStrOptionalError, n)
BENCHMARK (stringToCharSignedClassic, n)
BENCHMARK (stringToCharSignedClassicError, n)
BENCHMARK (stringToCharSignedOptional, n)
BENCHMARK (stringToCharSignedOptionalError, n)
BENCHMARK (stringToCharUnsignedClassic, n)
BENCHMARK (stringToCharUnsignedClassicError, n)
BENCHMARK (stringToCharUnsignedOptional, n)
BENCHMARK (stringToCharUnsignedOptionalError, n)
BENCHMARK (stringToIntSignedClassic, n)
BENCHMARK (stringToIntSignedClassicError, n)
BENCHMARK (stringToIntSignedOptional, n)
BENCHMARK (stringToIntSignedOptionalError, n)
BENCHMARK (stringToIntUnsignedClassic, n)
BENCHMARK (stringToIntUnsignedClassicError, n)
BENCHMARK (stringToIntUnsignedOptional, n)
BENCHMARK (stringToIntUnsignedOptionalError, n)
BENCHMARK (stringToLongLongSignedClassic, n)
BENCHMARK (stringToLongLongSignedClassicError, n)
BENCHMARK (stringToLongLongSignedOptional, n)
BENCHMARK (stringToLongLongSignedOptionalError, n)
BENCHMARK (stringToLongLongUnsignedClassic, n)
BENCHMARK (stringToLongLongUnsignedClassicError, n)
BENCHMARK (stringToLongLongUnsignedOptional, n)
BENCHMARK (stringToLongLongUnsignedOptionalError, n)
BENCHMARK (ptrPairToCharSignedClassic, n)
BENCHMARK (ptrPairToCharSignedClassicError, n)
BENCHMARK (ptrPairToCharSignedOptional, n)
BENCHMARK (ptrPairToCharSignedOptionalError, n)
BENCHMARK (ptrPairToCharUnsignedClassic, n)
BENCHMARK (ptrPairToCharUnsignedClassicError, n)
BENCHMARK (ptrPairToCharUnsignedOptional, n)
BENCHMARK (ptrPairToCharUnsignedOptionalError, n)
BENCHMARK (ptrPairToIntSignedClassic, n)
BENCHMARK (ptrPairToIntSignedClassicError, n)
BENCHMARK (ptrPairToIntSignedOptional, n)
BENCHMARK (ptrPairToIntSignedOptionalError, n)
BENCHMARK (ptrPairToIntUnsignedClassic, n)
BENCHMARK (ptrPairToIntUnsignedClassicError, n)
BENCHMARK (ptrPairToIntUnsignedOptional, n)
BENCHMARK (ptrPairToIntUnsignedOptionalError, n)
BENCHMARK (ptrPairToLongLongSignedClassic, n)
BENCHMARK (ptrPairToLongLongSignedClassicError, n)
BENCHMARK (ptrPairToLongLongSignedOptional, n)
BENCHMARK (ptrPairToLongLongSignedOptionalError, n)
BENCHMARK (ptrPairToLongLongUnsignedClassic, n)
BENCHMARK (ptrPairToLongLongUnsignedClassicError, n)
BENCHMARK (ptrPairToLongLongUnsignedOptional, n)
BENCHMARK (ptrPairToLongLongUnsignedOptionalError, n)
BENCHMARK_MULTI (intToCharSignedClassic)
BENCHMARK_MULTI (intToCharSignedClassicError)
BENCHMARK_MULTI (intToCharSignedOptional)
BENCHMARK_MULTI (intToCharSignedOptionalError)
BENCHMARK_MULTI (intToCharUnsignedClassic)
BENCHMARK_MULTI (intToCharUnsignedClassicError)
BENCHMARK_MULTI (intToCharUnsignedOptional)
BENCHMARK_MULTI (intToCharUnsignedOptionalError)
BENCHMARK_MULTI (intToIntSignedClassic)
BENCHMARK_MULTI (intToIntSignedClassicError)
BENCHMARK_MULTI (intToIntSignedOptional)
BENCHMARK_MULTI (intToIntSignedOptionalError)
BENCHMARK_MULTI (intToIntUnsignedClassic)
BENCHMARK_MULTI (intToIntUnsignedClassicError)
BENCHMARK_MULTI (intToIntUnsignedOptional)
BENCHMARK_MULTI (intToIntUnsignedOptionalError)
BENCHMARK_MULTI (intToFloatClassic)
BENCHMARK_MULTI (intToFloatClassicError)
BENCHMARK_MULTI (intToFloatOptional)
BENCHMARK_MULTI (intToFloatOptionalError)
BENCHMARK_MULTI (floatToFloatClassic)
BENCHMARK_MULTI (floatToFloatClassicError)
BENCHMARK_MULTI (floatToFloatOptional)
BENCHMARK_MULTI (floatToFloatOptionalError)
BENCHMARK_MULTI (floatToIntClassic)
BENCHMARK_MULTI (floatToIntClassicError)
BENCHMARK_MULTI (floatToIntOptional)
BENCHMARK_MULTI (floatToIntOptionalError)
int main (int argc, char **argv)
Variables
uint64_t folly::conv_bench_detail::uint64Num []
int64_t folly::conv_bench_detail::int64Pos []
int64_t folly::conv_bench_detail::int64Neg []
static StringPiece pc1 = "1234567890123456789"
size_t folly::conv_bench_detail::bigInt = 11424545345345
size_t folly::conv_bench_detail::smallInt = 104
char folly::conv_bench_detail::someString [] = "this is some nice string"
char folly::conv_bench_detail::otherString [] = "this is a long string, so it's not so nice"
char folly::conv_bench_detail::reallyShort [] = "meh"
std::string folly::conv_bench_detail::stdString = "std::strings are very nice"
float folly::conv_bench_detail::fValue = 1.2355f
double folly::conv_bench_detail::dValue = 345345345.435
int8_t folly::conv_bench_detail::i8s []
uint8_t folly::conv_bench_detail::u8s []
int16_t folly::conv_bench_detail::i16s []
uint16_t folly::conv_bench_detail::u16s []
int32_t folly::conv_bench_detail::i32s []
uint32_t folly::conv_bench_detail::u32s []
int64_t folly::conv_bench_detail::i64s []
uint64_t folly::conv_bench_detail::u64s []
static const StringIdenticalToBM< std::string > stringIdenticalToBM
static const StringVariadicToBM< std::string > stringVariadicToBM
static const StringIdenticalToBM< fbstring > fbstringIdenticalToBM
static const StringVariadicToBM< fbstring > fbstringVariadicToBM
std::array< int, 4 > folly::conv_bench_detail::int2ScharGood {{-128, 127, 0, -50}}
std::array< int, 4 > folly::conv_bench_detail::int2ScharBad {{-129, 128, 255, 10000}}
std::array< int, 4 > folly::conv_bench_detail::int2UcharGood {{0, 1, 254, 255}}
std::array< int, 4 > folly::conv_bench_detail::int2UcharBad {{-128, -1000, 256, -1}}
std::array< long long, 4 > folly::conv_bench_detail::ll2SintOrFloatGood {{-2, -1, 0, 1}}
std::array< long long, 4 > folly::conv_bench_detail::ll2SintOrFloatBad
std::array< long long, 4 > folly::conv_bench_detail::ll2UintGood {{1, 2, 3, 4}}
std::array< long long, 4 > folly::conv_bench_detail::ll2UintBad {{-1, -2, -3, -4}}
std::array< double, 4 > folly::conv_bench_detail::double2FloatGood {{1.0, 1.25, 2.5, 1000.0}}
std::array< double, 4 > folly::conv_bench_detail::double2FloatBad {{1e100, 1e101, 1e102, 1e103}}
std::array< double, 4 > folly::conv_bench_detail::double2IntGood {{1.0, 10.0, 100.0, 1000.0}}
std::array< double, 4 > folly::conv_bench_detail::double2IntBad {{1e100, 1.25, 2.5, 100.00001}}
Macro Definition Documentation
#define ARITH_TO_ARITH_BENCHMARK (type, name, pass, fail)
Value:
BENCHMARK_MULTI(name##Classic) {                               \
    return arithToArithClassic<type>(pass.data(), pass.size());  \
  }                                                              \
  BENCHMARK_MULTI(name##ClassicError) {                          \
    return arithToArithClassic<type>(fail.data(), fail.size());  \
  }                                                              \
  BENCHMARK_MULTI(name##Optional) {                              \
    return arithToArithOptional<type>(pass.data(), pass.size()); \
  }                                                              \
  BENCHMARK_MULTI(name##OptionalError) {                         \
    return arithToArithOptional<type>(fail.data(), fail.size()); \
  }
Definition at line 1049 of file ConvBenchmark.cpp.
#define DEFINE_BENCHMARK_GROUP (n)
Value:
BENCHMARK_PARAM(u64ToAsciiClassicBM, n)        \
  BENCHMARK_RELATIVE_PARAM(u64ToAsciiTableBM, n) \
  BENCHMARK_RELATIVE_PARAM(u64ToAsciiFollyBM, n) \
  BENCHMARK_DRAW_LINE()
Definition at line 891 of file ConvBenchmark.cpp.
#define DEFINE_BENCHMARK_GROUP (n)
Value:
BENCHMARK_PARAM(u64ToStringClibMeasure, n)              \
  BENCHMARK_RELATIVE_PARAM(u64ToStringFollyMeasure, n)    \
  BENCHMARK_RELATIVE_PARAM(i64ToStringFollyMeasurePos, n) \
  BENCHMARK_RELATIVE_PARAM(i64ToStringFollyMeasureNeg, n) \
  BENCHMARK_DRAW_LINE()
Definition at line 891 of file ConvBenchmark.cpp.
#define DEFINE_BENCHMARK_GROUP (n)
Value:
BENCHMARK_PARAM(clibAtoiMeasure, n)                 \
  BENCHMARK_RELATIVE_PARAM(lexicalCastMeasure, n)     \
  BENCHMARK_RELATIVE_PARAM(handwrittenAtoiMeasure, n) \
  BENCHMARK_RELATIVE_PARAM(follyAtoiMeasure, n)       \
  BENCHMARK_DRAW_LINE()
Definition at line 891 of file ConvBenchmark.cpp.
#define DEFINE_BENCHMARK_GROUP (T, n)
Value:
BENCHMARK_PARAM(T##VariadicToBM, n)           \
  BENCHMARK_RELATIVE_PARAM(T##IdenticalToBM, n) \
  BENCHMARK_DRAW_LINE()
Definition at line 891 of file ConvBenchmark.cpp.
#define FLOAT_TO_ARITH_BENCHMARK (type, name, pass, fail) ARITH_TO_ARITH_BENCHMARK(type, floatTo##name, pass, fail)
Definition at line 1066 of file ConvBenchmark.cpp.
#define FOLLY_RANGE_CHECK_TO_STRING (x) std::to_string(x)
Definition at line 36 of file ConvBenchmark.cpp.
Referenced by u64ToStringClibMeasure().
#define INT_TO_ARITH_BENCHMARK (type, name, pass, fail) ARITH_TO_ARITH_BENCHMARK(type, intTo##name, pass, fail)
Definition at line 1063 of file ConvBenchmark.cpp.
#define PTR_PAIR_TO_INT_BENCHMARK (type, name, pass, fail)
Value:
BENCHMARK(ptrPairTo##name##Classic, n) {                \
    ptrPairToIntClassic<type>(pass, n);                   \
  }                                                       \
  BENCHMARK(ptrPairTo##name##ClassicError, n) {           \
    ptrPairToIntClassic<type>(fail, n);                   \
  }                                                       \
  BENCHMARK(ptrPairTo##name##Optional, n) {               \
    ptrPairToIntOptional<type>(pass, n);                  \
  }                                                       \
  BENCHMARK(ptrPairTo##name##OptionalError, n) {          \
    ptrPairToIntOptional<type>(fail, n);                  \
  }
Definition at line 1035 of file ConvBenchmark.cpp.
#define STRING_TO_TYPE_BENCHMARK (type, name, pass, fail)
Value:
BENCHMARK(stringTo##name##Classic, n) {                \
    stringToTypeClassic<type>(pass, n);                  \
  }                                                      \
  BENCHMARK(stringTo##name##ClassicError, n) {           \
    stringToTypeClassic<type>(fail, n);                  \
  }                                                      \
  BENCHMARK(stringTo##name##Optional, n) {               \
    stringToTypeOptional<type>(pass, n);                 \
  }                                                      \
  BENCHMARK(stringTo##name##OptionalError, n) {          \
    stringToTypeOptional<type>(fail, n);                 \
  }
Definition at line 1021 of file ConvBenchmark.cpp.
Function Documentation
BENCHMARK (preallocateTestNoFloat , n)
Definition at line 520 of file ConvBenchmark.cpp.
References folly::conv_bench_detail::bigInt, folly::doNotOptimizeAway(), folly::conv_bench_detail::dValue, i, folly::conv_bench_detail::otherString, folly::conv_bench_detail::reallyShort, folly::size(), folly::conv_bench_detail::smallInt, folly::conv_bench_detail::someString, and folly::conv_bench_detail::stdString.
Referenced by BENCHMARK().
{
   for (size_t i = 0; i < n; ++i) {
     doNotOptimizeAway(
         to<std::string>(bigInt, someString, stdString, otherString).size());
     doNotOptimizeAway(to<std::string>(reallyShort, smallInt).size());
     doNotOptimizeAway(to<std::string>(bigInt, stdString).size());
     doNotOptimizeAway(
         to<std::string>(bigInt, stdString, dValue, otherString).size());
     doNotOptimizeAway(to<std::string>(bigInt, someString, reallyShort).size());
   }
 }
BENCHMARK (preallocateTestFloat , n)
Definition at line 532 of file ConvBenchmark.cpp.
References folly::doNotOptimizeAway(), folly::conv_bench_detail::dValue, folly::conv_bench_detail::fValue, i, folly::size(), and folly::conv_bench_detail::stdString.
{
   for (size_t i = 0; i < n; ++i) {
     doNotOptimizeAway(to<std::string>(stdString, ',', fValue, dValue).size());
     doNotOptimizeAway(to<std::string>(stdString, ',', dValue).size());
   }
 }
BENCHMARK (preallocateTestInt8 , n)
Definition at line 595 of file ConvBenchmark.cpp.
References folly::doNotOptimizeAway(), i, folly::conv_bench_detail::i8s, folly::size(), and folly::conv_bench_detail::u8s.
{
   for (size_t i = 0; i < n; ++i) {
     doNotOptimizeAway(to<std::string>(
                           i8s[0],
                           ',',
                           u8s[0],
                           ',',
                           i8s[1],
                           ',',
                           u8s[1],
                           ',',
                           i8s[2],
                           ',',
                           u8s[2])
                           .size());
   }
 }
BENCHMARK (preallocateTestInt16 , n)
Definition at line 613 of file ConvBenchmark.cpp.
References folly::doNotOptimizeAway(), i, folly::conv_bench_detail::i16s, folly::size(), and folly::conv_bench_detail::u16s.
{
   for (size_t i = 0; i < n; ++i) {
     doNotOptimizeAway(to<std::string>(
                           i16s[0],
                           ',',
                           u16s[0],
                           ',',
                           i16s[1],
                           ',',
                           u16s[1],
                           ',',
                           i16s[2],
                           ',',
                           u16s[2])
                           .size());
   }
 }
BENCHMARK (preallocateTestInt32 , n)
Definition at line 631 of file ConvBenchmark.cpp.
References folly::doNotOptimizeAway(), i, folly::conv_bench_detail::i32s, folly::size(), and folly::conv_bench_detail::u32s.
{
   for (size_t i = 0; i < n; ++i) {
     doNotOptimizeAway(to<std::string>(
                           i32s[0],
                           ',',
                           u32s[0],
                           ',',
                           i32s[1],
                           ',',
                           u32s[1],
                           ',',
                           i32s[2],
                           ',',
                           u32s[2])
                           .size());
   }
 }
BENCHMARK (preallocateTestInt64 , n)
Definition at line 649 of file ConvBenchmark.cpp.
References BENCHMARK(), BENCHMARK_DRAW_LINE(), folly::conv_bench_detail::bigInt, folly::doNotOptimizeAway(), folly::conv_bench_detail::dValue, i, folly::conv_bench_detail::i64s, folly::conv_bench_detail::otherString, folly::conv_bench_detail::reallyShort, folly::size(), folly::conv_bench_detail::smallInt, folly::conv_bench_detail::someString, folly::conv_bench_detail::stdString, and folly::conv_bench_detail::u64s.
{
   for (size_t i = 0; i < n; ++i) {
     doNotOptimizeAway(to<std::string>(
                           i64s[0],
                           ',',
                           u64s[0],
                           ',',
                           i64s[1],
                           ',',
                           u64s[1],
                           ',',
                           i64s[2],
                           ',',
                           u64s[2])
                           .size());
   }
 }
BENCHMARK (stringToBoolNumClassic , n)
Definition at line 1069 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToBoolNumClassicError , n)
Definition at line 1069 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToBoolNumOptional , n)
Definition at line 1069 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToBoolNumOptionalError , n)
Definition at line 1069 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToBoolStrClassic , n)
Definition at line 1070 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToBoolStrClassicError , n)
Definition at line 1070 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToBoolStrOptional , n)
Definition at line 1070 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToBoolStrOptionalError , n)
Definition at line 1070 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToFloatNumClassic , n)
Definition at line 1072 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToFloatNumClassicError , n)
Definition at line 1072 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToFloatNumOptional , n)
Definition at line 1072 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToFloatNumOptionalError , n)
Definition at line 1072 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToFloatStrClassic , n)
Definition at line 1073 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToFloatStrClassicError , n)
Definition at line 1073 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToFloatStrOptional , n)
Definition at line 1073 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToFloatStrOptionalError , n)
Definition at line 1073 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToDoubleNumClassic , n)
Definition at line 1074 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToDoubleNumClassicError , n)
Definition at line 1074 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToDoubleNumOptional , n)
Definition at line 1074 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToDoubleNumOptionalError , n)
Definition at line 1074 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToDoubleStrClassic , n)
Definition at line 1075 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToDoubleStrClassicError , n)
Definition at line 1075 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToDoubleStrOptional , n)
Definition at line 1075 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToDoubleStrOptionalError , n)
Definition at line 1075 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToCharSignedClassic , n)
Definition at line 1077 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToCharSignedClassicError , n)
Definition at line 1077 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToCharSignedOptional , n)
Definition at line 1077 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToCharSignedOptionalError , n)
Definition at line 1077 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToCharUnsignedClassic , n)
Definition at line 1078 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToCharUnsignedClassicError , n)
Definition at line 1078 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToCharUnsignedOptional , n)
Definition at line 1078 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToCharUnsignedOptionalError , n)
Definition at line 1078 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToIntSignedClassic , n)
Definition at line 1079 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToIntSignedClassicError , n)
Definition at line 1079 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToIntSignedOptional , n)
Definition at line 1079 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToIntSignedOptionalError , n)
Definition at line 1079 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToIntUnsignedClassic , n)
Definition at line 1080 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToIntUnsignedClassicError , n)
Definition at line 1080 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToIntUnsignedOptional , n)
Definition at line 1080 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToIntUnsignedOptionalError , n)
Definition at line 1080 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToLongLongSignedClassic , n)
Definition at line 1085 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToLongLongSignedClassicError , n)
Definition at line 1085 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToLongLongSignedOptional , n)
Definition at line 1085 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToLongLongSignedOptionalError , n)
Definition at line 1085 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToLongLongUnsignedClassic , n)
Definition at line 1090 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToLongLongUnsignedClassicError , n)
Definition at line 1090 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToLongLongUnsignedOptional , n)
Definition at line 1090 of file ConvBenchmark.cpp.
 {
BENCHMARK (stringToLongLongUnsignedOptionalError , n)
Definition at line 1090 of file ConvBenchmark.cpp.
 {
BENCHMARK (ptrPairToCharSignedClassic , n)
Definition at line 1093 of file ConvBenchmark.cpp.
 {
BENCHMARK (ptrPairToCharSignedClassicError , n)
Definition at line 1093 of file ConvBenchmark.cpp.
 {
BENCHMARK (ptrPairToCharSignedOptional , n)
Definition at line 1093 of file ConvBenchmark.cpp.
 {
BENCHMARK (ptrPairToCharSignedOptionalError , n)
Definition at line 1093 of file ConvBenchmark.cpp.
 {
BENCHMARK (ptrPairToCharUnsignedClassicError , n)
Definition at line 1094 of file ConvBenchmark.cpp.
 {
BENCHMARK (ptrPairToCharUnsignedClassic , n)
Definition at line 1094 of file ConvBenchmark.cpp.
 {
BENCHMARK (ptrPairToCharUnsignedOptional , n)
Definition at line 1094 of file ConvBenchmark.cpp.
 {
BENCHMARK (ptrPairToCharUnsignedOptionalError , n)
Definition at line 1094 of file ConvBenchmark.cpp.
 {
BENCHMARK (ptrPairToIntSignedClassicError , n)
Definition at line 1095 of file ConvBenchmark.cpp.
 {
BENCHMARK (ptrPairToIntSignedClassic , n)
Definition at line 1095 of file ConvBenchmark.cpp.
 {
BENCHMARK (ptrPairToIntSignedOptional , n)
Definition at line 1095 of file ConvBenchmark.cpp.
 {
BENCHMARK (ptrPairToIntSignedOptionalError , n)
Definition at line 1095 of file ConvBenchmark.cpp.
 {
BENCHMARK (ptrPairToIntUnsignedClassicError , n)
Definition at line 1100 of file ConvBenchmark.cpp.
 {
BENCHMARK (ptrPairToIntUnsignedClassic , n)
Definition at line 1100 of file ConvBenchmark.cpp.
 {
BENCHMARK (ptrPairToIntUnsignedOptional , n)
Definition at line 1100 of file ConvBenchmark.cpp.
 {
BENCHMARK (ptrPairToIntUnsignedOptionalError , n)
Definition at line 1100 of file ConvBenchmark.cpp.
 {
BENCHMARK (ptrPairToLongLongSignedClassic , n)
Definition at line 1105 of file ConvBenchmark.cpp.
 {
BENCHMARK (ptrPairToLongLongSignedClassicError , n)
Definition at line 1105 of file ConvBenchmark.cpp.
 {
BENCHMARK (ptrPairToLongLongSignedOptional , n)
Definition at line 1105 of file ConvBenchmark.cpp.
 {
BENCHMARK (ptrPairToLongLongSignedOptionalError , n)
Definition at line 1105 of file ConvBenchmark.cpp.
 {
BENCHMARK (ptrPairToLongLongUnsignedClassicError , n)
Definition at line 1110 of file ConvBenchmark.cpp.
 {
BENCHMARK (ptrPairToLongLongUnsignedClassic , n)
Definition at line 1110 of file ConvBenchmark.cpp.
 {
BENCHMARK (ptrPairToLongLongUnsignedOptional , n)
Definition at line 1110 of file ConvBenchmark.cpp.
 {
BENCHMARK (ptrPairToLongLongUnsignedOptionalError , n)
Definition at line 1110 of file ConvBenchmark.cpp.
 {
BENCHMARK_DRAW_LINE ()
Referenced by BENCHMARK().
BENCHMARK_MULTI (intToCharSignedClassicError)
Definition at line 1113 of file ConvBenchmark.cpp.
 {
BENCHMARK_MULTI (intToCharSignedClassic)
Definition at line 1113 of file ConvBenchmark.cpp.
 {
BENCHMARK_MULTI (intToCharSignedOptional)
Definition at line 1113 of file ConvBenchmark.cpp.
 {
BENCHMARK_MULTI (intToCharSignedOptionalError)
Definition at line 1113 of file ConvBenchmark.cpp.
 {
BENCHMARK_MULTI (intToCharUnsignedClassicError)
Definition at line 1114 of file ConvBenchmark.cpp.
 {
BENCHMARK_MULTI (intToCharUnsignedClassic)
Definition at line 1114 of file ConvBenchmark.cpp.
 {
BENCHMARK_MULTI (intToCharUnsignedOptional)
Definition at line 1114 of file ConvBenchmark.cpp.
 {
BENCHMARK_MULTI (intToCharUnsignedOptionalError)
Definition at line 1114 of file ConvBenchmark.cpp.
 {
BENCHMARK_MULTI (intToIntSignedClassic)
Definition at line 1115 of file ConvBenchmark.cpp.
 {
BENCHMARK_MULTI (intToIntSignedClassicError)
Definition at line 1115 of file ConvBenchmark.cpp.
 {
BENCHMARK_MULTI (intToIntSignedOptional)
Definition at line 1115 of file ConvBenchmark.cpp.
 {
BENCHMARK_MULTI (intToIntSignedOptionalError)
Definition at line 1115 of file ConvBenchmark.cpp.
 {
BENCHMARK_MULTI (intToIntUnsignedClassicError)
Definition at line 1116 of file ConvBenchmark.cpp.
 {
BENCHMARK_MULTI (intToIntUnsignedClassic)
Definition at line 1116 of file ConvBenchmark.cpp.
 {
BENCHMARK_MULTI (intToIntUnsignedOptional)
Definition at line 1116 of file ConvBenchmark.cpp.
 {
BENCHMARK_MULTI (intToIntUnsignedOptionalError)
Definition at line 1116 of file ConvBenchmark.cpp.
 {
BENCHMARK_MULTI (intToFloatClassicError)
Definition at line 1118 of file ConvBenchmark.cpp.
 {
BENCHMARK_MULTI (intToFloatClassic)
Definition at line 1118 of file ConvBenchmark.cpp.
 {
BENCHMARK_MULTI (intToFloatOptional)
Definition at line 1118 of file ConvBenchmark.cpp.
 {
BENCHMARK_MULTI (intToFloatOptionalError)
Definition at line 1118 of file ConvBenchmark.cpp.
 {
BENCHMARK_MULTI (floatToFloatClassicError)
Definition at line 1120 of file ConvBenchmark.cpp.
 {
BENCHMARK_MULTI (floatToFloatClassic)
Definition at line 1120 of file ConvBenchmark.cpp.
 {
BENCHMARK_MULTI (floatToFloatOptional)
Definition at line 1120 of file ConvBenchmark.cpp.
 {
BENCHMARK_MULTI (floatToFloatOptionalError)
Definition at line 1120 of file ConvBenchmark.cpp.
 {
BENCHMARK_MULTI (floatToIntClassic)
Definition at line 1122 of file ConvBenchmark.cpp.
 {
BENCHMARK_MULTI (floatToIntClassicError)
Definition at line 1122 of file ConvBenchmark.cpp.
 {
BENCHMARK_MULTI (floatToIntOptional)
Definition at line 1122 of file ConvBenchmark.cpp.
 {
BENCHMARK_MULTI (floatToIntOptionalError)
Definition at line 1122 of file ConvBenchmark.cpp.
 {
BENCHMARK_PARAM (u64ToAsciiClassicBM , 1)
BENCHMARK_PARAM (u64ToAsciiClassicBM , 2)
BENCHMARK_PARAM (u64ToAsciiClassicBM , 3)
BENCHMARK_PARAM (u64ToAsciiClassicBM , 4)
BENCHMARK_PARAM (u64ToAsciiClassicBM , 5)
BENCHMARK_PARAM (u64ToAsciiClassicBM , 6)
BENCHMARK_PARAM (u64ToAsciiClassicBM , 7)
BENCHMARK_PARAM (u64ToAsciiClassicBM , 8)
BENCHMARK_PARAM (u64ToAsciiClassicBM , 9)
BENCHMARK_PARAM (u64ToAsciiClassicBM , 10)
BENCHMARK_PARAM (u64ToAsciiClassicBM , 11)
BENCHMARK_PARAM (u64ToAsciiClassicBM , 12)
BENCHMARK_PARAM (u64ToAsciiClassicBM , 13)
BENCHMARK_PARAM (u64ToAsciiClassicBM , 14)
BENCHMARK_PARAM (u64ToAsciiClassicBM , 15)
BENCHMARK_PARAM (u64ToAsciiClassicBM , 16)
BENCHMARK_PARAM (u64ToAsciiClassicBM , 17)
BENCHMARK_PARAM (u64ToAsciiClassicBM , 18)
BENCHMARK_PARAM (u64ToAsciiClassicBM , 19)
BENCHMARK_PARAM (u64ToAsciiClassicBM , 20)
BENCHMARK_PARAM (u64ToStringClibMeasure , 1)
BENCHMARK_PARAM (u64ToStringClibMeasure , 2)
BENCHMARK_PARAM (u64ToStringClibMeasure , 3)
BENCHMARK_PARAM (u64ToStringClibMeasure , 4)
BENCHMARK_PARAM (u64ToStringClibMeasure , 5)
BENCHMARK_PARAM (u64ToStringClibMeasure , 6)
BENCHMARK_PARAM (u64ToStringClibMeasure , 7)
BENCHMARK_PARAM (u64ToStringClibMeasure , 8)
BENCHMARK_PARAM (u64ToStringClibMeasure , 9)
BENCHMARK_PARAM (u64ToStringClibMeasure , 10)
BENCHMARK_PARAM (u64ToStringClibMeasure , 11)
BENCHMARK_PARAM (u64ToStringClibMeasure , 12)
BENCHMARK_PARAM (u64ToStringClibMeasure , 13)
BENCHMARK_PARAM (u64ToStringClibMeasure , 14)
BENCHMARK_PARAM (u64ToStringClibMeasure , 15)
BENCHMARK_PARAM (u64ToStringClibMeasure , 16)
BENCHMARK_PARAM (u64ToStringClibMeasure , 17)
BENCHMARK_PARAM (u64ToStringClibMeasure , 18)
BENCHMARK_PARAM (u64ToStringClibMeasure , 19)
BENCHMARK_PARAM (clibAtoiMeasure , 1)
BENCHMARK_PARAM (clibAtoiMeasure , 2)
BENCHMARK_PARAM (clibAtoiMeasure , 3)
BENCHMARK_PARAM (clibAtoiMeasure , 4)
BENCHMARK_PARAM (clibAtoiMeasure , 5)
BENCHMARK_PARAM (clibAtoiMeasure , 6)
BENCHMARK_PARAM (clibAtoiMeasure , 7)
BENCHMARK_PARAM (clibAtoiMeasure , 8)
BENCHMARK_PARAM (clibAtoiMeasure , 9)
BENCHMARK_PARAM (clibAtoiMeasure , 10)
BENCHMARK_PARAM (clibAtoiMeasure , 11)
BENCHMARK_PARAM (clibAtoiMeasure , 12)
BENCHMARK_PARAM (clibAtoiMeasure , 13)
BENCHMARK_PARAM (clibAtoiMeasure , 14)
BENCHMARK_PARAM (clibAtoiMeasure , 15)
BENCHMARK_PARAM (clibAtoiMeasure , 16)
BENCHMARK_PARAM (clibAtoiMeasure , 17)
BENCHMARK_PARAM (clibAtoiMeasure , 18)
BENCHMARK_PARAM (clibAtoiMeasure , 19)
BENCHMARK_PARAM (stringVariadicToBM , 32)
BENCHMARK_PARAM (stringVariadicToBM , 1024)
BENCHMARK_PARAM (stringVariadicToBM , 32768)
BENCHMARK_PARAM (fbstringVariadicToBM , 32)
BENCHMARK_PARAM (fbstringVariadicToBM , 1024)
BENCHMARK_PARAM (fbstringVariadicToBM , 32768)
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM , 1)
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM , 2)
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM , 3)
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM , 4)
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM , 5)
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM , 6)
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM , 7)
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM , 8)
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM , 9)
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM , 10)
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM , 11)
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM , 12)
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM , 13)
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM , 14)
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM , 15)
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM , 16)
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM , 17)
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM , 18)
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM , 19)
BENCHMARK_RELATIVE_PARAM (u64ToAsciiFollyBM , 20)
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos , 1)
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos , 2)
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos , 3)
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos , 4)
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos , 5)
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos , 6)
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos , 7)
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos , 8)
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos , 9)
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos , 10)
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos , 11)
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos , 12)
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos , 13)
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos , 14)
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos , 15)
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos , 16)
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos , 17)
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos , 18)
BENCHMARK_RELATIVE_PARAM (i64ToStringFollyMeasurePos , 19)
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure , 1)
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure , 2)
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure , 3)
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure , 4)
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure , 5)
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure , 6)
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure , 7)
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure , 8)
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure , 9)
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure , 10)
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure , 11)
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure , 12)
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure , 13)
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure , 14)
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure , 15)
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure , 16)
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure , 17)
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure , 18)
BENCHMARK_RELATIVE_PARAM (handwrittenAtoiMeasure , 19)
void clibAtoiMeasure (unsigned int n, unsigned int digits)
Definition at line 319 of file ConvBenchmark.cpp.
References folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, folly::Range< Iter >::size(), and folly::Range< Iter >::subpiece().
{
   auto p = pc1.subpiece(pc1.size() - digits, digits);
   assert(*p.end() == 0);
   FOR_EACH_RANGE (i, 0, n) { doNotOptimizeAway(atoll(p.begin())); }
 }
void follyAtoiMeasure (unsigned int n, unsigned int digits)
Definition at line 312 of file ConvBenchmark.cpp.
References folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, folly::Range< Iter >::size(), and folly::Range< Iter >::subpiece().
{
   auto p = pc1.subpiece(pc1.size() - digits, digits);
   FOR_EACH_RANGE (i, 0, n) {
     doNotOptimizeAway(folly::to<int64_t>(p.begin(), p.end()));
   }
 }
static int64_t handwrittenAtoi (const char * start, const char * end) static
Definition at line 265 of file ConvBenchmark.cpp.
References FOLLY_FALLTHROUGH, int64_t, and start.
Referenced by handwrittenAtoiMeasure().
{
   bool positive = true;
   int64_t retVal = 0;
   if (start == end) {
     throw std::runtime_error("empty string");
   }
   while (start < end && isspace(*start)) {
     ++start;
   }
   switch (*start) {
     case '-':
       positive = false;
       FOLLY_FALLTHROUGH;
     case '+':
       ++start;
       FOLLY_FALLTHROUGH;
     default:
       break;
   }
   while (start < end && *start >= '0' && *start <= '9') {
     auto const newRetVal = retVal * 10 + (*start++ - '0');
     if (newRetVal < retVal) {
       throw std::runtime_error("overflow");
     }
     retVal = newRetVal;
   }
   if (start != end) {
     throw std::runtime_error("extra chars at the end");
   }
   return positive ? retVal : -retVal;
 }
void handwrittenAtoiMeasure (unsigned int n, unsigned int digits)
Definition at line 305 of file ConvBenchmark.cpp.
References folly::doNotOptimizeAway(), FOR_EACH_RANGE, handwrittenAtoi(), i, folly::Range< Iter >::size(), and folly::Range< Iter >::subpiece().
{
   auto p = pc1.subpiece(pc1.size() - digits, digits);
   FOR_EACH_RANGE (i, 0, n) {
     doNotOptimizeAway(handwrittenAtoi(p.begin(), p.end()));
   }
 }
void i64ToStringFollyMeasureNeg (unsigned int n, size_t index)
Definition at line 442 of file ConvBenchmark.cpp.
References folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, folly::conv_bench_detail::int64Neg, and folly::size().
{
   checkArrayIndex(int64Neg, index);
   FOR_EACH_RANGE (i, 0, n) {
     doNotOptimizeAway(to<std::string>(int64Neg[index] - (i % 8)).size());
   }
 }
void i64ToStringFollyMeasurePos (unsigned int n, size_t index)
Definition at line 435 of file ConvBenchmark.cpp.
References folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, folly::conv_bench_detail::int64Pos, and folly::size().
{
   checkArrayIndex(int64Pos, index);
   FOR_EACH_RANGE (i, 0, n) {
     doNotOptimizeAway(to<std::string>(int64Pos[index] + (i % 8)).size());
   }
 }
void lexicalCastMeasure (unsigned int n, unsigned int digits)
Definition at line 325 of file ConvBenchmark.cpp.
References folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, folly::Range< Iter >::size(), and folly::Range< Iter >::subpiece().
{
   auto p = pc1.subpiece(pc1.size() - digits, digits);
   assert(*p.end() == 0);
   FOR_EACH_RANGE (i, 0, n) {
     doNotOptimizeAway(boost::lexical_cast<uint64_t>(p.begin()));
   }
 }
int main (int argc, char ** argv)
Definition at line 1130 of file ConvBenchmark.cpp.
References folly::runBenchmarks().
{
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   folly::runBenchmarks();
   return 0;
 }
void u2aAppendClassicBM (unsigned int n, size_t index)
Definition at line 451 of file ConvBenchmark.cpp.
References buffer(), folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, s, u64ToAsciiClassic(), and folly::conv_bench_detail::uint64Num.
{
   checkArrayIndex(uint64Num, index);
   string s;
   FOR_EACH_RANGE (i, 0, n) {
     // auto buf = &s.back() + 1;
     char buffer[20];
     s.append(buffer, u64ToAsciiClassic(uint64Num[index] + (i % 8), buffer));
     doNotOptimizeAway(s.size());
   }
 }
void u2aAppendFollyBM (unsigned int n, size_t index)
Definition at line 462 of file ConvBenchmark.cpp.
References buffer(), folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, s, folly::conv_bench_detail::uint64Num, and folly::uint64ToBufferUnsafe().
{
   checkArrayIndex(uint64Num, index);
   string s;
   FOR_EACH_RANGE (i, 0, n) {
     // auto buf = &s.back() + 1;
     char buffer[20];
     s.append(buffer, uint64ToBufferUnsafe(uint64Num[index] + (i % 8), buffer));
     doNotOptimizeAway(s.size());
   }
 }
unsigned u64ToAsciiClassic (uint64_t value, char * dst)
Definition at line 376 of file ConvBenchmark.cpp.
References cpp.ast::next(), start, and folly::f14::swap().
Referenced by u2aAppendClassicBM(), and u64ToAsciiClassicBM().
{
   // Write backwards.
   char* next = (char*)dst;
   char* start = next;
   do {
     *next++ = '0' + (value % 10);
     value /= 10;
   } while (value != 0);
   unsigned length = next - start;
   // Reverse in-place.
   next--;
   while (next > start) {
     char swap = *next;
     *next = *start;
     *start = swap;
     next--;
     start++;
   }
   return length;
 }
void u64ToAsciiClassicBM (unsigned int n, size_t index)
Definition at line 398 of file ConvBenchmark.cpp.
References folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, u64ToAsciiClassic(), and folly::conv_bench_detail::uint64Num.
{
   checkArrayIndex(uint64Num, index);
   char buf[20];
   FOR_EACH_RANGE (i, 0, n) {
     doNotOptimizeAway(u64ToAsciiClassic(uint64Num[index] + (i % 8), buf));
   }
 }
void u64ToAsciiFollyBM (unsigned int n, size_t index)
Definition at line 406 of file ConvBenchmark.cpp.
References folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, folly::conv_bench_detail::uint64Num, and folly::uint64ToBufferUnsafe().
{
   checkArrayIndex(uint64Num, index);
   char buf[20];
   FOR_EACH_RANGE (i, 0, n) {
     doNotOptimizeAway(uint64ToBufferUnsafe(uint64Num[index] + (i % 8), buf));
   }
 }
unsigned u64ToAsciiTable (uint64_t value, char * dst)
Definition at line 335 of file ConvBenchmark.cpp.
References folly::digits10(), i, cpp.ast::next(), and uint32_t.
Referenced by u64ToAsciiTableBM().
{
   static const char digits[201] =
       "00010203040506070809"
       "10111213141516171819"
       "20212223242526272829"
       "30313233343536373839"
       "40414243444546474849"
       "50515253545556575859"
       "60616263646566676869"
       "70717273747576777879"
       "80818283848586878889"
       "90919293949596979899";
   uint32_t const length = digits10(value);
   uint32_t next = length - 1;
   while (value >= 100) {
     auto const i = (value % 100) * 2;
     value /= 100;
     dst[next] = digits[i + 1];
     dst[next - 1] = digits[i];
     next -= 2;
   }
   // Handle last 1-2 digits
   if (value < 10) {
     dst[next] = '0' + uint32_t(value);
   } else {
     auto i = uint32_t(value) * 2;
     dst[next] = digits[i + 1];
     dst[next - 1] = digits[i];
   }
   return length;
 }
void u64ToAsciiTableBM (unsigned int n, size_t index)
Definition at line 368 of file ConvBenchmark.cpp.
References folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, u64ToAsciiTable(), and folly::conv_bench_detail::uint64Num.
{
   checkArrayIndex(uint64Num, index);
   char buf[20];
   FOR_EACH_RANGE (i, 0, n) {
     doNotOptimizeAway(u64ToAsciiTable(uint64Num[index] + (i % 8), buf));
   }
 }
void u64ToStringClibMeasure (unsigned int n, size_t index)
Definition at line 416 of file ConvBenchmark.cpp.
References folly::doNotOptimizeAway(), FOLLY_RANGE_CHECK_TO_STRING, FOR_EACH_RANGE, i, folly::size(), and folly::conv_bench_detail::uint64Num.
{
   // FOLLY_RANGE_CHECK_TO_STRING expands to std::to_string, except on Android
   // where std::to_string is not supported
   checkArrayIndex(uint64Num, index);
   FOR_EACH_RANGE (i, 0, n) {
     doNotOptimizeAway(
         FOLLY_RANGE_CHECK_TO_STRING(uint64Num[index] + (i % 8)).size());
   }
 }
void u64ToStringFollyMeasure (unsigned int n, size_t index)
Definition at line 426 of file ConvBenchmark.cpp.
References folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, folly::size(), and folly::conv_bench_detail::uint64Num.
{
   checkArrayIndex(uint64Num, index);
   FOR_EACH_RANGE (i, 0, n) {
     doNotOptimizeAway(to<std::string>(uint64Num[index] + (i % 8)).size());
   }
 }
Variable Documentation
const StringIdenticalToBM<fbstring> fbstringIdenticalToBM static
Definition at line 721 of file ConvBenchmark.cpp.
const StringVariadicToBM<fbstring> fbstringVariadicToBM static
Definition at line 722 of file ConvBenchmark.cpp.
StringPiece pc1 = "1234567890123456789" static
Definition at line 303 of file ConvBenchmark.cpp.
const StringIdenticalToBM<std::string> stringIdenticalToBM static
Definition at line 719 of file ConvBenchmark.cpp.
const StringVariadicToBM<std::string> stringVariadicToBM static
Definition at line 720 of file ConvBenchmark.cpp.