proxygen: proxygen/folly/folly/experimental/coro/test/CoroBenchmarkNRVO.cpp File Reference
CoroBenchmarkNRVO.cpp File Reference
#include <folly/Benchmark.h>
#include <thread>
Classes
struct ExpensiveCopy
Functions
ExpensiveCopy nestedCalls (size_t times)
void NRVO (size_t times, size_t iters)
BENCHMARK (NRVOOneAwait, iters)
BENCHMARK (NRVOTenAwaits, iters)
int main (int argc, char **argv)
Function Documentation
BENCHMARK (NRVOOneAwait , iters)
Definition at line 208 of file CoroBenchmarkNRVO.cpp.
References NRVO().
Referenced by ExpensiveCopy::ExpensiveCopy().
{
   NRVO(1, iters);
 }
BENCHMARK (NRVOTenAwaits , iters)
Definition at line 212 of file CoroBenchmarkNRVO.cpp.
References NRVO().
{
   NRVO(10, iters);
 }
int main (int argc, char ** argv)
Definition at line 216 of file CoroBenchmarkNRVO.cpp.
References folly::runBenchmarks().
{
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   folly::runBenchmarks();
   return 0;
 }
ExpensiveCopy nestedCalls (size_t times)
Definition at line 193 of file CoroBenchmarkNRVO.cpp.
Referenced by NRVO().
{
   ExpensiveCopy ret;
   if (times > 0) {
     ret = nestedCalls(times - 1);
   }
   return ret;
 }
void NRVO (size_t times, size_t iters)
Definition at line 202 of file CoroBenchmarkNRVO.cpp.
References nestedCalls().
Referenced by BENCHMARK().
{
   for (size_t iter = 0; iter < iters; ++iter) {
     nestedCalls(times);
   }
 }