proxygen: proxygen/folly/folly/stats/test/DigestBuilderTest.cpp File Reference
DigestBuilderTest.cpp File Reference
#include <folly/stats/detail/DigestBuilder-defs.h>
#include <chrono>
#include <random>
#include <thread>
#include <folly/Range.h>
#include <folly/portability/GTest.h>
Classes
class SimpleDigest< MergeSize >
Functions
TEST (DigestBuilder, SingleThreadUnfilledBuffer)
TEST (DigestBuilder, SingleThreadFilledBuffer)
TEST (DigestBuilder, MultipleThreads)
Function Documentation
TEST (DigestBuilder , SingleThreadUnfilledBuffer)
Definition at line 55 of file DigestBuilderTest.cpp.
References folly::detail::DigestBuilder< DigestT >::append(), folly::detail::DigestBuilder< DigestT >::build(), shell_builder::builder, EXPECT_EQ, and i.
{
   DigestBuilder<SimpleDigest<999>> builder(1000, 100);
   for (int i = 0; i < 999; ++i) {
     builder.append(i);
   }
   EXPECT_EQ(100, builder.build().getSize());
 }
TEST (DigestBuilder , SingleThreadFilledBuffer)
Definition at line 63 of file DigestBuilderTest.cpp.
References folly::detail::DigestBuilder< DigestT >::append(), folly::detail::DigestBuilder< DigestT >::build(), shell_builder::builder, EXPECT_EQ, and i.
{
   DigestBuilder<SimpleDigest<1000>> builder(1000, 100);
   for (int i = 0; i < 1000; ++i) {
     builder.append(i);
   }
   EXPECT_EQ(100, builder.build().getSize());
 }
TEST (DigestBuilder , MultipleThreads)
Definition at line 71 of file DigestBuilderTest.cpp.
References folly::detail::DigestBuilder< DigestT >::append(), folly::detail::DigestBuilder< DigestT >::build(), shell_builder::builder, EXPECT_EQ, i, and threads.
{
   DigestBuilder<SimpleDigest<1000>> builder(1000, 100);
   std::vector<std::thread> threads;
   for (int i = 0; i < 10; ++i) {
     threads.push_back(std::thread([i, &builder]() {
       for (int j = 0; j < 100; ++j) {
         builder.append(i * 100 + j);
       }
     }));
   }
   for (auto& thread : threads) {
     thread.join();
   }
   EXPECT_EQ(100, builder.build().getSize());
 }