proxygen: proxygen/folly/folly/stats/test/DigestBuilderBenchmark.cpp File Reference
DigestBuilderBenchmark.cpp File Reference
#include <folly/stats/detail/DigestBuilder-defs.h>
#include <chrono>
#include <condition_variable>
#include <thread>
#include <boost/thread/barrier.hpp>
#include <folly/Benchmark.h>
#include <folly/Range.h>
#include <folly/portability/GFlags.h>
Classes
class FreeDigest
Functions
DEFINE_int32 (digest_merge_time_ns, 5500,"Time to merge into the digest")
unsigned int append (unsigned int iters, size_t bufSize, size_t nThreads)
BENCHMARK_DRAW_LINE ()
int main (int argc, char *argv[])
Function Documentation
unsigned int append (unsigned int iters, size_t bufSize, size_t nThreads)
Definition at line 47 of file DigestBuilderBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE(), BENCHMARK_NAMED_PARAM_MULTI, BENCHMARK_RELATIVE_NAMED_PARAM_MULTI, BENCHMARK_SUSPEND, buffer(), i, and threads.
{
   iters = 1000000;
   auto buffer = std::make_shared<DigestBuilder<FreeDigest>>(bufSize, 100);
   auto barrier = std::make_shared<boost::barrier>(nThreads + 1);
   std::vector<std::thread> threads;
   threads.reserve(nThreads);
   BENCHMARK_SUSPEND {
     for (size_t i = 0; i < nThreads; ++i) {
       threads.emplace_back([&]() {
         barrier->wait();
         for (size_t iter = 0; iter < iters; ++iter) {
           buffer->append(iter);
         }
         barrier->wait();
       });
     }
     barrier->wait();
   }
   barrier->wait();
   BENCHMARK_SUSPEND {
     for (auto& thread : threads) {
       thread.join();
     }
   }
   return iters;
 }
BENCHMARK_DRAW_LINE ()
DEFINE_int32 (digest_merge_time_ns , 5500 , "Time to merge into the digest")
int main (int argc, char * argv[])
Definition at line 112 of file DigestBuilderBenchmark.cpp.
References argv, and folly::runBenchmarks().
{
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   folly::runBenchmarks();
   return 0;
 }