var dir_95da60d4dd25016845c021644f02b10e =
[
    [ "benchmarks", "dir_83d028d115082d054b00b129696f4b15.html", "dir_83d028d115082d054b00b129696f4b15" ],
    [ "detail", "dir_3f6901467b3ad7e02315cee302953b53.html", "dir_3f6901467b3ad7e02315cee302953b53" ],
    [ "examples", "dir_726272ca97d8829ac3cb61a9d38b8dfe.html", "dir_726272ca97d8829ac3cb61a9d38b8dfe" ],
    [ "o", "dir_19bf4a357088881f7412abe30123a034.html", "dir_19bf4a357088881f7412abe30123a034" ],
    [ "test", "dir_7357032efe33f02de036cd1008239d2a.html", "dir_7357032efe33f02de036cd1008239d2a" ],
    [ "boosters.h", "boosters_8h.html", "boosters_8h" ],
    [ "concepts.h", "concepts_8h.html", "concepts_8h" ],
    [ "constrained_single_sender.h", "constrained__single__sender_8h.html", "constrained__single__sender_8h" ],
    [ "entangle.h", "entangle_8h.html", "entangle_8h" ],
    [ "executor.h", "executor_8h.html", "executor_8h" ],
    [ "extension_points.h", "extension__points_8h.html", "extension__points_8h" ],
    [ "flow_many_sender.h", "flow__many__sender_8h.html", "flow__many__sender_8h" ],
    [ "flow_receiver.h", "flow__receiver_8h.html", "flow__receiver_8h" ],
    [ "flow_single_sender.h", "flow__single__sender_8h.html", "flow__single__sender_8h" ],
    [ "forwards.h", "forwards_8h.html", [
      [ "property_traits", "structfolly_1_1pushmi_1_1property__traits.html", null ],
      [ "property_set_traits", "structfolly_1_1pushmi_1_1property__set__traits.html", null ],
      [ "property_set", "structfolly_1_1pushmi_1_1property__set.html", "structfolly_1_1pushmi_1_1property__set" ],
      [ "is_single", "structfolly_1_1pushmi_1_1is__single.html", null ],
      [ "is_many", "structfolly_1_1pushmi_1_1is__many.html", null ],
      [ "is_flow", "structfolly_1_1pushmi_1_1is__flow.html", null ],
      [ "is_receiver", "structfolly_1_1pushmi_1_1is__receiver.html", null ],
      [ "is_sender", "structfolly_1_1pushmi_1_1is__sender.html", null ],
      [ "is_executor", "structfolly_1_1pushmi_1_1is__executor.html", null ],
      [ "is_time", "structfolly_1_1pushmi_1_1is__time.html", null ],
      [ "is_constrained", "structfolly_1_1pushmi_1_1is__constrained.html", null ],
      [ "is_always_blocking", "structfolly_1_1pushmi_1_1is__always__blocking.html", null ],
      [ "is_never_blocking", "structfolly_1_1pushmi_1_1is__never__blocking.html", null ],
      [ "is_maybe_blocking", "structfolly_1_1pushmi_1_1is__maybe__blocking.html", null ],
      [ "is_fifo_sequence", "structfolly_1_1pushmi_1_1is__fifo__sequence.html", null ],
      [ "is_concurrent_sequence", "structfolly_1_1pushmi_1_1is__concurrent__sequence.html", null ],
      [ "receiver", "classfolly_1_1pushmi_1_1receiver.html", null ],
      [ "flow_receiver", "classfolly_1_1pushmi_1_1flow__receiver.html", null ],
      [ "single_sender", "classfolly_1_1pushmi_1_1single__sender.html", null ],
      [ "many_sender", "classfolly_1_1pushmi_1_1many__sender.html", null ],
      [ "constrained_single_sender", "classfolly_1_1pushmi_1_1constrained__single__sender.html", null ],
      [ "time_single_sender", "classfolly_1_1pushmi_1_1time__single__sender.html", "classfolly_1_1pushmi_1_1time__single__sender" ],
      [ "flow_single_sender", "classfolly_1_1pushmi_1_1flow__single__sender.html", null ],
      [ "flow_many_sender", "classfolly_1_1pushmi_1_1flow__many__sender.html", null ],
      [ "any_receiver", "classfolly_1_1pushmi_1_1any__receiver.html", "classfolly_1_1pushmi_1_1any__receiver" ],
      [ "any_flow_receiver", "classfolly_1_1pushmi_1_1any__flow__receiver.html", "classfolly_1_1pushmi_1_1any__flow__receiver" ],
      [ "any_single_sender", "classfolly_1_1pushmi_1_1any__single__sender.html", "classfolly_1_1pushmi_1_1any__single__sender" ],
      [ "any_many_sender", "classfolly_1_1pushmi_1_1any__many__sender.html", "classfolly_1_1pushmi_1_1any__many__sender" ],
      [ "any_flow_single_sender", "classfolly_1_1pushmi_1_1any__flow__single__sender.html", "classfolly_1_1pushmi_1_1any__flow__single__sender" ],
      [ "any_flow_many_sender", "classfolly_1_1pushmi_1_1any__flow__many__sender.html", "classfolly_1_1pushmi_1_1any__flow__many__sender" ],
      [ "any_constrained_single_sender", "classfolly_1_1pushmi_1_1any__constrained__single__sender.html", "classfolly_1_1pushmi_1_1any__constrained__single__sender" ],
      [ "any_time_single_sender", "classfolly_1_1pushmi_1_1any__time__single__sender.html", "classfolly_1_1pushmi_1_1any__time__single__sender" ],
      [ "any_executor", "structfolly_1_1pushmi_1_1any__executor.html", "structfolly_1_1pushmi_1_1any__executor" ],
      [ "any_executor_ref", "structfolly_1_1pushmi_1_1any__executor__ref.html", "structfolly_1_1pushmi_1_1any__executor__ref" ],
      [ "any_constrained_executor", "structfolly_1_1pushmi_1_1any__constrained__executor.html", "structfolly_1_1pushmi_1_1any__constrained__executor" ],
      [ "any_constrained_executor_ref", "structfolly_1_1pushmi_1_1any__constrained__executor__ref.html", "structfolly_1_1pushmi_1_1any__constrained__executor__ref" ],
      [ "any_time_executor", "structfolly_1_1pushmi_1_1any__time__executor.html", "structfolly_1_1pushmi_1_1any__time__executor" ],
      [ "any_time_executor_ref", "structfolly_1_1pushmi_1_1any__time__executor__ref.html", "structfolly_1_1pushmi_1_1any__time__executor__ref" ],
      [ "any", "structfolly_1_1pushmi_1_1detail_1_1any.html", "structfolly_1_1pushmi_1_1detail_1_1any" ]
    ] ],
    [ "inline.h", "inline_8h.html", "inline_8h" ],
    [ "many_sender.h", "many__sender_8h.html", "many__sender_8h" ],
    [ "new_thread.h", "new__thread_8h.html", "new__thread_8h" ],
    [ "piping.h", "piping_8h.html", "piping_8h" ],
    [ "properties.h", "properties_8h.html", "properties_8h" ],
    [ "receiver.h", "receiver_8h.html", "receiver_8h" ],
    [ "single_sender.h", "single__sender_8h.html", "single__sender_8h" ],
    [ "strand.h", "strand_8h.html", "strand_8h" ],
    [ "subject.h", "subject_8h.html", [
      [ "subject", "structfolly_1_1pushmi_1_1subject.html", null ],
      [ "subject< PS, TN... >", "structfolly_1_1pushmi_1_1subject_3_01PS_00_01TN_8_8_8_01_4.html", "structfolly_1_1pushmi_1_1subject_3_01PS_00_01TN_8_8_8_01_4" ],
      [ "subject_shared", "structfolly_1_1pushmi_1_1subject_3_01PS_00_01TN_8_8_8_01_4_1_1subject__shared.html", "structfolly_1_1pushmi_1_1subject_3_01PS_00_01TN_8_8_8_01_4_1_1subject__shared" ],
      [ "subject_receiver", "structfolly_1_1pushmi_1_1subject_3_01PS_00_01TN_8_8_8_01_4_1_1subject__receiver.html", "structfolly_1_1pushmi_1_1subject_3_01PS_00_01TN_8_8_8_01_4_1_1subject__receiver" ]
    ] ],
    [ "time_single_sender.h", "time__single__sender_8h.html", "time__single__sender_8h" ],
    [ "time_source.h", "time__source_8h.html", "time__source_8h" ],
    [ "traits.h", "experimental_2pushmi_2traits_8h.html", "experimental_2pushmi_2traits_8h" ],
    [ "trampoline.h", "trampoline_8h.html", "trampoline_8h" ]
];