var dir_dcf8e1233ba68571c5027662569cd1d9 =
[
    [ "chrono", "dir_b7cf047100e81d4416b08fd14415a295.html", "dir_b7cf047100e81d4416b08fd14415a295" ],
    [ "compression", "dir_0fcb2c71238aa35551dc32a49693aa96.html", "dir_0fcb2c71238aa35551dc32a49693aa96" ],
    [ "concurrency", "dir_5feb9546f642256217de2390be5a49dc.html", "dir_5feb9546f642256217de2390be5a49dc" ],
    [ "container", "dir_d099e51fdf6d275b7771453d75a8b201.html", "dir_d099e51fdf6d275b7771453d75a8b201" ],
    [ "detail", "dir_a066a76eafc9eb52f55f4a6beac281bd.html", "dir_a066a76eafc9eb52f55f4a6beac281bd" ],
    [ "executors", "dir_8e56188b5e93e9b6ac79534069252c69.html", "dir_8e56188b5e93e9b6ac79534069252c69" ],
    [ "experimental", "dir_81eb1dbd071cdd475d3d544204dd2893.html", "dir_81eb1dbd071cdd475d3d544204dd2893" ],
    [ "fibers", "dir_764b9069382febd53dbeb2b6bfbcc4b7.html", "dir_764b9069382febd53dbeb2b6bfbcc4b7" ],
    [ "functional", "dir_28c98390dcb734b02d3ebfa018e9650e.html", "dir_28c98390dcb734b02d3ebfa018e9650e" ],
    [ "futures", "dir_98686afb9f1ae3122fcd66a9704bd751.html", "dir_98686afb9f1ae3122fcd66a9704bd751" ],
    [ "gen", "dir_338df7fb5375cbb9d5dc5d2487fb7065.html", "dir_338df7fb5375cbb9d5dc5d2487fb7065" ],
    [ "hash", "dir_1c362833e65620483cd5e7bbf0d82515.html", "dir_1c362833e65620483cd5e7bbf0d82515" ],
    [ "init", "dir_1640f6aa60ad627dd2b73dfc7e87321a.html", "dir_1640f6aa60ad627dd2b73dfc7e87321a" ],
    [ "io", "dir_8b8cdcef1613958d35fc1de7b2d6bb26.html", "dir_8b8cdcef1613958d35fc1de7b2d6bb26" ],
    [ "lang", "dir_d9b0eeb23716fa53143aad038f801b1b.html", "dir_d9b0eeb23716fa53143aad038f801b1b" ],
    [ "logging", "dir_397bf65bc10f8fa58c4ba4269be7bc10.html", "dir_397bf65bc10f8fa58c4ba4269be7bc10" ],
    [ "memory", "dir_6c565051e087b4089515b7343dd83b92.html", "dir_6c565051e087b4089515b7343dd83b92" ],
    [ "net", "dir_2202eef673d30cdb44adee6d8a239cb0.html", "dir_2202eef673d30cdb44adee6d8a239cb0" ],
    [ "poly", "dir_095359f8668f351f4886b1d47b28aa18.html", "dir_095359f8668f351f4886b1d47b28aa18" ],
    [ "portability", "dir_cce08c02742e27a4caf5915fb11ae597.html", "dir_cce08c02742e27a4caf5915fb11ae597" ],
    [ "python", "dir_1642b5067ffe7653e49899c07f174e25.html", "dir_1642b5067ffe7653e49899c07f174e25" ],
    [ "ssl", "dir_df5e01536b01f364133ce50af0e4088f.html", "dir_df5e01536b01f364133ce50af0e4088f" ],
    [ "stats", "dir_1460bd6fe752a469a5f2c6b7d7e9f45c.html", "dir_1460bd6fe752a469a5f2c6b7d7e9f45c" ],
    [ "synchronization", "dir_0ef962fe73ad62cb233827ccf4c062b4.html", "dir_0ef962fe73ad62cb233827ccf4c062b4" ],
    [ "system", "dir_e756193bf55132b008fbb50c97cd8308.html", "dir_e756193bf55132b008fbb50c97cd8308" ],
    [ "test", "dir_1225781ec9161af73a1065ad4149bfd8.html", "dir_1225781ec9161af73a1065ad4149bfd8" ],
    [ "tools", "dir_ede2a99fd7cdbf57c8a87018ba3cdb13.html", "dir_ede2a99fd7cdbf57c8a87018ba3cdb13" ],
    [ "tracing", "dir_648bd70e2d643bbb50b2fbd320d676c9.html", "dir_648bd70e2d643bbb50b2fbd320d676c9" ],
    [ "AtomicBitSet.h", "AtomicBitSet_8h.html", [
      [ "AtomicBitSet", "classfolly_1_1AtomicBitSet.html", "classfolly_1_1AtomicBitSet" ]
    ] ],
    [ "AtomicHashArray-inl.h", "AtomicHashArray-inl_8h.html", [
      [ "aha_iterator", "structfolly_1_1AtomicHashArray_1_1aha__iterator.html", "structfolly_1_1AtomicHashArray_1_1aha__iterator" ]
    ] ],
    [ "AtomicHashArray.h", "AtomicHashArray_8h.html", "AtomicHashArray_8h" ],
    [ "AtomicHashMap-inl.h", "AtomicHashMap-inl_8h.html", [
      [ "ahm_iterator", "structfolly_1_1AtomicHashMap_1_1ahm__iterator.html", "structfolly_1_1AtomicHashMap_1_1ahm__iterator" ]
    ] ],
    [ "AtomicHashMap.h", "AtomicHashMap_8h.html", "AtomicHashMap_8h" ],
    [ "AtomicIntrusiveLinkedList.h", "AtomicIntrusiveLinkedList_8h.html", [
      [ "AtomicIntrusiveLinkedListHook", "structfolly_1_1AtomicIntrusiveLinkedListHook.html", "structfolly_1_1AtomicIntrusiveLinkedListHook" ],
      [ "AtomicIntrusiveLinkedList", "classfolly_1_1AtomicIntrusiveLinkedList.html", "classfolly_1_1AtomicIntrusiveLinkedList" ]
    ] ],
    [ "AtomicLinkedList.h", "AtomicLinkedList_8h.html", [
      [ "AtomicLinkedList", "classfolly_1_1AtomicLinkedList.html", "classfolly_1_1AtomicLinkedList" ],
      [ "Wrapper", "structfolly_1_1AtomicLinkedList_1_1Wrapper.html", "structfolly_1_1AtomicLinkedList_1_1Wrapper" ]
    ] ],
    [ "AtomicUnorderedMap.h", "AtomicUnorderedMap_8h.html", "AtomicUnorderedMap_8h" ],
    [ "Benchmark.cpp", "Benchmark_8cpp.html", "Benchmark_8cpp" ],
    [ "Benchmark.h", "Benchmark_8h.html", "Benchmark_8h" ],
    [ "Bits.h", "Bits_8h.html", null ],
    [ "CachelinePadded.h", "CachelinePadded_8h.html", [
      [ "CachelinePadded", "classfolly_1_1CachelinePadded.html", "classfolly_1_1CachelinePadded" ]
    ] ],
    [ "Chrono.h", "Chrono_8h.html", "Chrono_8h" ],
    [ "ClockGettimeWrappers.cpp", "ClockGettimeWrappers_8cpp.html", "ClockGettimeWrappers_8cpp" ],
    [ "ClockGettimeWrappers.h", "ClockGettimeWrappers_8h.html", null ],
    [ "ConcurrentSkipList-inl.h", "ConcurrentSkipList-inl_8h.html", [
      [ "csl_iterator", "classfolly_1_1detail_1_1csl__iterator.html", "classfolly_1_1detail_1_1csl__iterator" ],
      [ "SkipListNode", "classfolly_1_1detail_1_1SkipListNode.html", "classfolly_1_1detail_1_1SkipListNode" ],
      [ "DestroyIsNoOp", "structfolly_1_1detail_1_1SkipListNode_1_1DestroyIsNoOp.html", null ],
      [ "SkipListRandomHeight", "classfolly_1_1detail_1_1SkipListRandomHeight.html", "classfolly_1_1detail_1_1SkipListRandomHeight" ],
      [ "NodeRecycler", "classfolly_1_1detail_1_1NodeRecycler.html", null ],
      [ "NodeRecycler< NodeType, NodeAlloc, typename std::enable_if< !NodeType::template DestroyIsNoOp< NodeAlloc >::value >::type >", "classfolly_1_1detail_1_1NodeRecycler_3_01NodeType_00_01NodeAlloc_00_01typename_01std_1_1enable__cd89c712347c8311d43447d8114ddec4.html", "classfolly_1_1detail_1_1NodeRecycler_3_01NodeType_00_01NodeAlloc_00_01typename_01std_1_1enable__cd89c712347c8311d43447d8114ddec4" ],
      [ "NodeRecycler< NodeType, NodeAlloc, typename std::enable_if< NodeType::template DestroyIsNoOp< NodeAlloc >::value >::type >", "classfolly_1_1detail_1_1NodeRecycler_3_01NodeType_00_01NodeAlloc_00_01typename_01std_1_1enable__fbb5b9cbed2bbd22b07ecb04c90b2564.html", "classfolly_1_1detail_1_1NodeRecycler_3_01NodeType_00_01NodeAlloc_00_01typename_01std_1_1enable__fbb5b9cbed2bbd22b07ecb04c90b2564" ]
    ] ],
    [ "ConcurrentSkipList.h", "ConcurrentSkipList_8h.html", [
      [ "ConcurrentSkipList", "classfolly_1_1ConcurrentSkipList.html", "classfolly_1_1ConcurrentSkipList" ],
      [ "Accessor", "classfolly_1_1ConcurrentSkipList_1_1Accessor.html", "classfolly_1_1ConcurrentSkipList_1_1Accessor" ],
      [ "csl_iterator", "classfolly_1_1detail_1_1csl__iterator.html", "classfolly_1_1detail_1_1csl__iterator" ],
      [ "Skipper", "classfolly_1_1ConcurrentSkipList_1_1Skipper.html", "classfolly_1_1ConcurrentSkipList_1_1Skipper" ]
    ] ],
    [ "ConstexprMath.h", "ConstexprMath_8h.html", "ConstexprMath_8h" ],
    [ "Conv.cpp", "Conv_8cpp.html", "Conv_8cpp" ],
    [ "Conv.h", "Conv_8h.html", "Conv_8h" ],
    [ "CPortability.h", "CPortability_8h.html", "CPortability_8h" ],
    [ "CppAttributes.h", "CppAttributes_8h.html", "CppAttributes_8h" ],
    [ "CpuId.h", "CpuId_8h.html", "CpuId_8h" ],
    [ "DefaultKeepAliveExecutor.h", "DefaultKeepAliveExecutor_8h.html", [
      [ "DefaultKeepAliveExecutor", "classfolly_1_1DefaultKeepAliveExecutor.html", "classfolly_1_1DefaultKeepAliveExecutor" ],
      [ "ControlBlock", "structfolly_1_1DefaultKeepAliveExecutor_1_1ControlBlock.html", "structfolly_1_1DefaultKeepAliveExecutor_1_1ControlBlock" ],
      [ "WeakRef", "classfolly_1_1DefaultKeepAliveExecutor_1_1WeakRef.html", "classfolly_1_1DefaultKeepAliveExecutor_1_1WeakRef" ]
    ] ],
    [ "Demangle.cpp", "Demangle_8cpp.html", "Demangle_8cpp" ],
    [ "Demangle.h", "Demangle_8h.html", "Demangle_8h" ],
    [ "DiscriminatedPtr.h", "DiscriminatedPtr_8h.html", "DiscriminatedPtr_8h" ],
    [ "dynamic-inl.h", "dynamic-inl_8h.html", "dynamic-inl_8h" ],
    [ "dynamic.cpp", "dynamic_8cpp.html", "dynamic_8cpp" ],
    [ "dynamic.h", "dynamic_8h.html", [
      [ "dynamic", "structfolly_1_1dynamic.html", "structfolly_1_1dynamic" ],
      [ "NumericTypeHelper", "structfolly_1_1dynamic_1_1NumericTypeHelper.html", null ],
      [ "VectorBoolConstRefFake", "structfolly_1_1dynamic_1_1VectorBoolConstRefFake.html", null ],
      [ "EmptyArrayTag", "structfolly_1_1dynamic_1_1EmptyArrayTag.html", null ],
      [ "IterableProxy", "structfolly_1_1dynamic_1_1IterableProxy.html", "structfolly_1_1dynamic_1_1IterableProxy" ],
      [ "TypeInfo", "structfolly_1_1dynamic_1_1TypeInfo.html", null ],
      [ "CompareOp", "structfolly_1_1dynamic_1_1CompareOp.html", "structfolly_1_1dynamic_1_1CompareOp" ],
      [ "GetAddrImpl", "structfolly_1_1dynamic_1_1GetAddrImpl.html", null ],
      [ "PrintImpl", "structfolly_1_1dynamic_1_1PrintImpl.html", "structfolly_1_1dynamic_1_1PrintImpl" ],
      [ "Data", "unionfolly_1_1dynamic_1_1Data.html", "unionfolly_1_1dynamic_1_1Data" ]
    ] ],
    [ "DynamicConverter.h", "DynamicConverter_8h.html", "DynamicConverter_8h" ],
    [ "Exception.h", "folly_2folly_2Exception_8h.html", "folly_2folly_2Exception_8h" ],
    [ "ExceptionString.h", "ExceptionString_8h.html", "ExceptionString_8h" ],
    [ "ExceptionWrapper-inl.h", "ExceptionWrapper-inl_8h.html", "ExceptionWrapper-inl_8h" ],
    [ "ExceptionWrapper.cpp", "ExceptionWrapper_8cpp.html", "ExceptionWrapper_8cpp" ],
    [ "ExceptionWrapper.h", "ExceptionWrapper_8h.html", "ExceptionWrapper_8h" ],
    [ "Executor.cpp", "Executor_8cpp.html", null ],
    [ "Executor.h", "Executor_8h.html", "Executor_8h" ],
    [ "Expected.h", "Expected_8h.html", "Expected_8h" ],
    [ "FBString.h", "FBString_8h.html", "FBString_8h" ],
    [ "FBVector.h", "FBVector_8h.html", "FBVector_8h" ],
    [ "File.cpp", "File_8cpp.html", "File_8cpp" ],
    [ "File.h", "File_8h.html", "File_8h" ],
    [ "FileUtil.cpp", "FileUtil_8cpp.html", "FileUtil_8cpp" ],
    [ "FileUtil.h", "FileUtil_8h.html", "FileUtil_8h" ],
    [ "Fingerprint.cpp", "Fingerprint_8cpp.html", "Fingerprint_8cpp" ],
    [ "Fingerprint.h", "Fingerprint_8h.html", "Fingerprint_8h" ],
    [ "FixedString.h", "FixedString_8h.html", "FixedString_8h" ],
    [ "Format-inl.h", "Format-inl_8h.html", "Format-inl_8h" ],
    [ "Format.cpp", "Format_8cpp.html", "Format_8cpp" ],
    [ "Format.h", "Format_8h.html", "Format_8h" ],
    [ "FormatArg.h", "FormatArg_8h.html", [
      [ "BadFormatArg", "classfolly_1_1BadFormatArg.html", null ],
      [ "FormatArg", "structfolly_1_1FormatArg.html", "structfolly_1_1FormatArg" ]
    ] ],
    [ "FormatTraits.h", "FormatTraits_8h.html", [
      [ "FormatTraitsBase", "structfolly_1_1detail_1_1FormatTraitsBase.html", "structfolly_1_1detail_1_1FormatTraitsBase" ],
      [ "IndexableTraits", "structfolly_1_1detail_1_1IndexableTraits.html", null ],
      [ "IndexableTraitsSeq", "structfolly_1_1detail_1_1IndexableTraitsSeq.html", "structfolly_1_1detail_1_1IndexableTraitsSeq" ],
      [ "IndexableTraitsAssoc", "structfolly_1_1detail_1_1IndexableTraitsAssoc.html", "structfolly_1_1detail_1_1IndexableTraitsAssoc" ]
    ] ],
    [ "Function.h", "Function_8h.html", "Function_8h" ],
    [ "GLog.h", "GLog_8h.html", "GLog_8h" ],
    [ "GroupVarint.cpp", "GroupVarint_8cpp.html", null ],
    [ "GroupVarint.h", "GroupVarint_8h.html", null ],
    [ "Hash.h", "Hash_8h.html", null ],
    [ "Indestructible.h", "Indestructible_8h.html", [
      [ "Indestructible", "classfolly_1_1Indestructible.html", "classfolly_1_1Indestructible" ],
      [ "Storage", "unionfolly_1_1Indestructible_1_1Storage.html", "unionfolly_1_1Indestructible_1_1Storage" ]
    ] ],
    [ "IndexedMemPool.h", "IndexedMemPool_8h.html", "IndexedMemPool_8h" ],
    [ "IntrusiveList.h", "IntrusiveList_8h.html", "IntrusiveList_8h" ],
    [ "IPAddress.cpp", "IPAddress_8cpp.html", "IPAddress_8cpp" ],
    [ "IPAddress.h", "IPAddress_8h.html", null ],
    [ "IPAddressException.h", "IPAddressException_8h.html", "IPAddressException_8h" ],
    [ "IPAddressV4.cpp", "IPAddressV4_8cpp.html", "IPAddressV4_8cpp" ],
    [ "IPAddressV4.h", "IPAddressV4_8h.html", "IPAddressV4_8h" ],
    [ "IPAddressV6.cpp", "IPAddressV6_8cpp.html", "IPAddressV6_8cpp" ],
    [ "IPAddressV6.h", "IPAddressV6_8h.html", "IPAddressV6_8h" ],
    [ "json.cpp", "json_8cpp.html", "json_8cpp" ],
    [ "json.h", "json_8h.html", "json_8h" ],
    [ "json_patch.cpp", "json__patch_8cpp.html", null ],
    [ "json_patch.h", "json__patch_8h.html", [
      [ "json_patch", "classfolly_1_1json__patch.html", "classfolly_1_1json__patch" ],
      [ "parse_error", "structfolly_1_1json__patch_1_1parse__error.html", "structfolly_1_1json__patch_1_1parse__error" ],
      [ "patch_operation", "structfolly_1_1json__patch_1_1patch__operation.html", "structfolly_1_1json__patch_1_1patch__operation" ]
    ] ],
    [ "json_pointer.cpp", "json__pointer_8cpp.html", null ],
    [ "json_pointer.h", "json__pointer_8h.html", [
      [ "json_pointer", "classfolly_1_1json__pointer.html", "classfolly_1_1json__pointer" ],
      [ "parse_exception", "classfolly_1_1json__pointer_1_1parse__exception.html", null ]
    ] ],
    [ "Lazy.h", "Lazy_8h.html", "Lazy_8h" ],
    [ "Likely.h", "Likely_8h.html", "Likely_8h" ],
    [ "LockTraits.h", "LockTraits_8h.html", "LockTraits_8h" ],
    [ "LockTraitsBoost.h", "LockTraitsBoost_8h.html", null ],
    [ "MacAddress.cpp", "MacAddress_8cpp.html", "MacAddress_8cpp" ],
    [ "MacAddress.h", "MacAddress_8h.html", "MacAddress_8h" ],
    [ "MapUtil.h", "MapUtil_8h.html", "MapUtil_8h" ],
    [ "Math.h", "Math_8h.html", "Math_8h" ],
    [ "Memory.h", "Memory_8h.html", "Memory_8h" ],
    [ "MicroLock.cpp", "MicroLock_8cpp.html", null ],
    [ "MicroLock.h", "MicroLock_8h.html", "MicroLock_8h" ],
    [ "MicroSpinLock.h", "MicroSpinLock_8h.html", null ],
    [ "MoveWrapper.h", "MoveWrapper_8h.html", "MoveWrapper_8h" ],
    [ "MPMCPipeline.h", "MPMCPipeline_8h.html", [
      [ "MPMCPipelineStage", "classfolly_1_1MPMCPipelineStage.html", "classfolly_1_1MPMCPipelineStage" ],
      [ "MPMCPipeline", "classfolly_1_1MPMCPipeline.html", "classfolly_1_1MPMCPipeline" ],
      [ "TicketBaseDebug", "classfolly_1_1MPMCPipeline_1_1TicketBaseDebug.html", "classfolly_1_1MPMCPipeline_1_1TicketBaseDebug" ],
      [ "TicketBaseNDebug", "classfolly_1_1MPMCPipeline_1_1TicketBaseNDebug.html", "classfolly_1_1MPMCPipeline_1_1TicketBaseNDebug" ],
      [ "Ticket", "classfolly_1_1MPMCPipeline_1_1Ticket.html", "classfolly_1_1MPMCPipeline_1_1Ticket" ]
    ] ],
    [ "MPMCQueue.h", "MPMCQueue_8h.html", [
      [ "SingleElementQueue", "structfolly_1_1detail_1_1SingleElementQueue.html", "structfolly_1_1detail_1_1SingleElementQueue" ],
      [ "MPMCPipelineStageImpl", "classfolly_1_1detail_1_1MPMCPipelineStageImpl.html", "classfolly_1_1detail_1_1MPMCPipelineStageImpl" ],
      [ "MPMCQueueBase", "classfolly_1_1detail_1_1MPMCQueueBase.html", null ],
      [ "MPMCQueue", "classfolly_1_1MPMCQueue.html", "classfolly_1_1MPMCQueue" ],
      [ "MPMCQueue< T, Atom, true >", "classfolly_1_1MPMCQueue_3_01T_00_01Atom_00_01true_01_4.html", "classfolly_1_1MPMCQueue_3_01T_00_01Atom_00_01true_01_4" ],
      [ "ClosedArray", "structfolly_1_1MPMCQueue_3_01T_00_01Atom_00_01true_01_4_1_1ClosedArray.html", "structfolly_1_1MPMCQueue_3_01T_00_01Atom_00_01true_01_4_1_1ClosedArray" ],
      [ "MPMCQueueBase< Derived< T, Atom, Dynamic > >", "classfolly_1_1detail_1_1MPMCQueueBase_3_01Derived_3_01T_00_01Atom_00_01Dynamic_01_4_01_4.html", "classfolly_1_1detail_1_1MPMCQueueBase_3_01Derived_3_01T_00_01Atom_00_01Dynamic_01_4_01_4" ],
      [ "SingleElementQueue", "structfolly_1_1detail_1_1SingleElementQueue.html", "structfolly_1_1detail_1_1SingleElementQueue" ],
      [ "ImplByRelocation", "structfolly_1_1detail_1_1SingleElementQueue_1_1ImplByRelocation.html", null ],
      [ "ImplByMove", "structfolly_1_1detail_1_1SingleElementQueue_1_1ImplByMove.html", null ]
    ] ],
    [ "Optional.h", "Optional_8h.html", "Optional_8h" ],
    [ "Overload.h", "Overload_8h.html", "Overload_8h" ],
    [ "PackedSyncPtr.h", "PackedSyncPtr_8h.html", "PackedSyncPtr_8h" ],
    [ "Padded.h", "Padded_8h.html", "Padded_8h" ],
    [ "Poly-inl.h", "Poly-inl_8h.html", null ],
    [ "Poly.cpp", "Poly_8cpp.html", null ],
    [ "Poly.h", "Poly_8h.html", "Poly_8h" ],
    [ "PolyException.h", "PolyException_8h.html", [
      [ "BadPolyAccess", "structfolly_1_1BadPolyAccess.html", "structfolly_1_1BadPolyAccess" ],
      [ "BadPolyCast", "structfolly_1_1BadPolyCast.html", "structfolly_1_1BadPolyCast" ]
    ] ],
    [ "Portability.h", "Portability_8h.html", "Portability_8h" ],
    [ "Preprocessor.h", "Preprocessor_8h.html", "Preprocessor_8h" ],
    [ "PriorityMPMCQueue.h", "PriorityMPMCQueue_8h.html", [
      [ "PriorityMPMCQueue", "classfolly_1_1PriorityMPMCQueue.html", "classfolly_1_1PriorityMPMCQueue" ]
    ] ],
    [ "ProducerConsumerQueue.h", "ProducerConsumerQueue_8h.html", [
      [ "ProducerConsumerQueue", "structfolly_1_1ProducerConsumerQueue.html", "structfolly_1_1ProducerConsumerQueue" ]
    ] ],
    [ "Random-inl.h", "Random-inl_8h.html", "Random-inl_8h" ],
    [ "Random.cpp", "Random_8cpp.html", "Random_8cpp" ],
    [ "Random.h", "Random_8h.html", "Random_8h" ],
    [ "Range.h", "Range_8h.html", "Range_8h" ],
    [ "Replaceable.h", "Replaceable_8h.html", "Replaceable_8h" ],
    [ "RWSpinLock.h", "RWSpinLock_8h.html", null ],
    [ "ScopeGuard.cpp", "ScopeGuard_8cpp.html", null ],
    [ "ScopeGuard.h", "ScopeGuard_8h.html", "ScopeGuard_8h" ],
    [ "SharedMutex.cpp", "SharedMutex_8cpp.html", "SharedMutex_8cpp" ],
    [ "SharedMutex.h", "SharedMutex_8h.html", "SharedMutex_8h" ],
    [ "Singleton-inl.h", "Singleton-inl_8h.html", "Singleton-inl_8h" ],
    [ "Singleton.cpp", "Singleton_8cpp.html", "Singleton_8cpp" ],
    [ "Singleton.h", "Singleton_8h.html", "Singleton_8h" ],
    [ "SingletonThreadLocal.h", "SingletonThreadLocal_8h.html", "SingletonThreadLocal_8h" ],
    [ "small_vector.h", "small__vector_8h.html", "small__vector_8h" ],
    [ "SocketAddress.cpp", "SocketAddress_8cpp.html", "SocketAddress_8cpp" ],
    [ "SocketAddress.h", "SocketAddress_8h.html", "SocketAddress_8h" ],
    [ "sorted_vector_types.h", "sorted__vector__types_8h.html", "sorted__vector__types_8h" ],
    [ "SpinLock.h", "SpinLock_8h.html", "SpinLock_8h" ],
    [ "stop_watch.h", "stop__watch_8h.html", "stop__watch_8h" ],
    [ "String-inl.h", "String-inl_8h.html", "String-inl_8h" ],
    [ "String.cpp", "String_8cpp.html", "String_8cpp" ],
    [ "String.h", "String_8h.html", "String_8h" ],
    [ "Subprocess.cpp", "Subprocess_8cpp.html", "Subprocess_8cpp" ],
    [ "Subprocess.h", "Subprocess_8h.html", [
      [ "ProcessReturnCode", "classfolly_1_1ProcessReturnCode.html", "classfolly_1_1ProcessReturnCode" ],
      [ "SubprocessError", "classfolly_1_1SubprocessError.html", null ],
      [ "CalledProcessError", "classfolly_1_1CalledProcessError.html", "classfolly_1_1CalledProcessError" ],
      [ "SubprocessSpawnError", "classfolly_1_1SubprocessSpawnError.html", "classfolly_1_1SubprocessSpawnError" ],
      [ "Subprocess", "classfolly_1_1Subprocess.html", "classfolly_1_1Subprocess" ],
      [ "DangerousPostForkPreExecCallback", "structfolly_1_1Subprocess_1_1DangerousPostForkPreExecCallback.html", "structfolly_1_1Subprocess_1_1DangerousPostForkPreExecCallback" ],
      [ "Options", "classfolly_1_1Subprocess_1_1Options.html", "classfolly_1_1Subprocess_1_1Options" ],
      [ "ReadLinesCallback", "classfolly_1_1Subprocess_1_1ReadLinesCallback.html", "classfolly_1_1Subprocess_1_1ReadLinesCallback" ],
      [ "StreamSplitterCallback", "structfolly_1_1Subprocess_1_1ReadLinesCallback_1_1StreamSplitterCallback.html", "structfolly_1_1Subprocess_1_1ReadLinesCallback_1_1StreamSplitterCallback" ],
      [ "ChildPipe", "structfolly_1_1Subprocess_1_1ChildPipe.html", "structfolly_1_1Subprocess_1_1ChildPipe" ],
      [ "Pipe", "structfolly_1_1Subprocess_1_1Pipe.html", "structfolly_1_1Subprocess_1_1Pipe" ]
    ] ],
    [ "Synchronized.h", "Synchronized_8h.html", "Synchronized_8h" ],
    [ "SynchronizedPtr.h", "SynchronizedPtr_8h.html", [
      [ "SynchronizedPtrLockedElement", "structfolly_1_1SynchronizedPtrLockedElement.html", "structfolly_1_1SynchronizedPtrLockedElement" ],
      [ "SynchronizedPtr", "classfolly_1_1SynchronizedPtr.html", "classfolly_1_1SynchronizedPtr" ]
    ] ],
    [ "ThreadCachedInt.h", "ThreadCachedInt_8h.html", [
      [ "ThreadCachedInt", "classfolly_1_1ThreadCachedInt.html", "classfolly_1_1ThreadCachedInt" ],
      [ "IntCache", "structfolly_1_1ThreadCachedInt_1_1IntCache.html", "structfolly_1_1ThreadCachedInt_1_1IntCache" ]
    ] ],
    [ "ThreadLocal.h", "ThreadLocal_8h.html", [
      [ "ThreadLocalPtr", "classfolly_1_1ThreadLocalPtr.html", "classfolly_1_1ThreadLocalPtr" ],
      [ "ThreadLocal", "classfolly_1_1ThreadLocal.html", "classfolly_1_1ThreadLocal" ],
      [ "ThreadLocalPtr", "classfolly_1_1ThreadLocalPtr.html", "classfolly_1_1ThreadLocalPtr" ],
      [ "Accessor", "classfolly_1_1ThreadLocalPtr_1_1Accessor.html", "classfolly_1_1ThreadLocalPtr_1_1Accessor" ],
      [ "Iterator", "classfolly_1_1ThreadLocalPtr_1_1Accessor_1_1Iterator.html", "classfolly_1_1ThreadLocalPtr_1_1Accessor_1_1Iterator" ],
      [ "static_meta_of", "structfolly_1_1threadlocal__detail_1_1static__meta__of.html", null ],
      [ "static_meta_of< ThreadLocalPtr< T, Tag, AccessMode > >", "structfolly_1_1threadlocal__detail_1_1static__meta__of_3_01ThreadLocalPtr_3_01T_00_01Tag_00_01AccessMode_01_4_01_4.html", "structfolly_1_1threadlocal__detail_1_1static__meta__of_3_01ThreadLocalPtr_3_01T_00_01Tag_00_01AccessMode_01_4_01_4" ],
      [ "static_meta_of< ThreadLocal< T, Tag, AccessMode > >", "structfolly_1_1threadlocal__detail_1_1static__meta__of_3_01ThreadLocal_3_01T_00_01Tag_00_01AccessMode_01_4_01_4.html", "structfolly_1_1threadlocal__detail_1_1static__meta__of_3_01ThreadLocal_3_01T_00_01Tag_00_01AccessMode_01_4_01_4" ]
    ] ],
    [ "TimeoutQueue.cpp", "TimeoutQueue_8cpp.html", null ],
    [ "TimeoutQueue.h", "TimeoutQueue_8h.html", [
      [ "TimeoutQueue", "classfolly_1_1TimeoutQueue.html", "classfolly_1_1TimeoutQueue" ],
      [ "Event", "structfolly_1_1TimeoutQueue_1_1Event.html", "structfolly_1_1TimeoutQueue_1_1Event" ]
    ] ],
    [ "TokenBucket.h", "TokenBucket_8h.html", "TokenBucket_8h" ],
    [ "Traits.h", "Traits_8h.html", "Traits_8h" ],
    [ "Try-inl.h", "Try-inl_8h.html", "Try-inl_8h" ],
    [ "Try.h", "Try_8h.html", "Try_8h" ],
    [ "Unicode.cpp", "Unicode_8cpp.html", "Unicode_8cpp" ],
    [ "Unicode.h", "Unicode_8h.html", "Unicode_8h" ],
    [ "Unit.h", "Unit_8h.html", "Unit_8h" ],
    [ "Uri-inl.h", "Uri-inl_8h.html", "Uri-inl_8h" ],
    [ "Uri.cpp", "Uri_8cpp.html", null ],
    [ "Uri.h", "Uri_8h.html", "Uri_8h" ],
    [ "UTF8String.h", "UTF8String_8h.html", "UTF8String_8h" ],
    [ "Utility.h", "Utility_8h.html", "Utility_8h" ],
    [ "Varint.h", "Varint_8h.html", "Varint_8h" ],
    [ "VirtualExecutor.h", "VirtualExecutor_8h.html", [
      [ "VirtualExecutor", "classfolly_1_1VirtualExecutor.html", "classfolly_1_1VirtualExecutor" ]
    ] ]
];