proxygen: proxygen/folly/folly/experimental/symbolizer/test/DwarfBenchmark.cpp File Reference
DwarfBenchmark.cpp File Reference
#include <folly/Benchmark.h>
#include <folly/experimental/symbolizer/Dwarf.h>
#include <folly/portability/GFlags.h>
Functions
void dummy ()
BENCHMARK (DwarfFindAddressFast, n)
BENCHMARK (DwarfFindAddressFull, n)
int main (int argc, char *argv[])
Function Documentation
BENCHMARK (DwarfFindAddressFast , n)
Definition at line 42 of file DwarfBenchmark.cpp.
References folly::symbolizer::Dwarf::FAST, and folly::run().
{
   run(folly::symbolizer::Dwarf::LocationInfoMode::FAST, n);
 }
BENCHMARK (DwarfFindAddressFull , n)
Definition at line 46 of file DwarfBenchmark.cpp.
References folly::symbolizer::Dwarf::FULL, and folly::run().
{
   run(folly::symbolizer::Dwarf::LocationInfoMode::FULL, n);
 }
void dummy ()
Definition at line 21 of file DwarfBenchmark.cpp.
References folly::BenchmarkSuspender::dismiss(), folly::symbolizer::Dwarf::findAddress(), i, deadlock::info(), mode, and folly::run().
Referenced by testing::gmock_matchers_test::DerivedClass::k(), testing::gmock_matchers_test::GreaterThanMatcher::MatchAndExplain(), testing::internal::MatcherBase< const internal::string & >::Matches(), testing::internal::NoDefaultContructor::NoDefaultContructor(), testing::gmock_generated_actions_test::SubstractAction::Perform(), folly::detail::posixTimeToDuration(), folly::FlatCombining< FcSimpleExample< Mutex, Atom >, Mutex, Atom >::requestFC(), TEST(), testing::gmock_matchers_test::TEST(), testing::internal::TEST(), testing::gmock_generated_actions_test::TEST(), TEST_F(), test_operator_on_search(), HTTPUpstreamTest< C >::testSimpleUpgrade(), and testing::internal::To::To().
 {}
int main (int argc, char * argv[])
Definition at line 50 of file DwarfBenchmark.cpp.
References folly::runBenchmarksOnFlag().
{
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   google::InitGoogleLogging(argv[0]);
   folly::runBenchmarksOnFlag();
   return 0;
 }