proxygen: proxygen/wangle/wangle/example/echo/EchoClient.cpp File Reference
EchoClient.cpp File Reference
#include <iostream>
#include <gflags/gflags.h>
#include <folly/init/Init.h>
#include <wangle/bootstrap/ClientBootstrap.h>
#include <wangle/channel/AsyncSocketHandler.h>
#include <wangle/channel/EventBaseHandler.h>
#include <wangle/codec/LineBasedFrameDecoder.h>
#include <wangle/codec/StringCodec.h>
Classes
class EchoHandler
class EchoPipelineFactory
Typedefs
typedef Pipeline< folly::IOBufQueue &, std::string > EchoPipeline
Functions
DEFINE_int32 (port, 8080,"echo server port")
DEFINE_string (host,"::1","echo server address")
int main (int argc, char **argv)
Typedef Documentation
typedef Pipeline<folly::IOBufQueue&, std::string> EchoPipeline
Definition at line 34 of file EchoClient.cpp.
Function Documentation
DEFINE_int32 (port , 8080 , "echo server port")
DEFINE_string (host , "::1" , "echo server address")
int main (int argc, char ** argv)
Definition at line 69 of file EchoClient.cpp.
References wangle::ClientBootstrap< Pipeline >::connect(), folly::exceptionStr(), getline(), wangle::ClientBootstrap< Pipeline >::group(), folly::init(), wangle::BaseClientBootstrap< Pipeline >::pipelineFactory(), and string.
{
   folly::Init init(&argc, &argv);
   ClientBootstrap<EchoPipeline> client;
   client.group(std::make_shared<folly::IOThreadPoolExecutor>(1));
   client.pipelineFactory(std::make_shared<EchoPipelineFactory>());
   auto pipeline = client.connect(SocketAddress(FLAGS_host, FLAGS_port)).get();
   try {
     while (true) {
       std::string line;
       std::getline(std::cin, line);
       if (line == "") {
         break;
       }
       pipeline->write(line + "\r\n").get();
       if (line == "bye") {
         pipeline->close();
         break;
       }
     }
   } catch (const std::exception& e) {
     std::cout << exceptionStr(e) << std::endl;
   }
   return 0;
 }