proxygen: proxygen/httpserver/samples/echo/test/EchoHandlerTest.cpp File Reference
EchoHandlerTest.cpp File Reference
#include <folly/portability/GMock.h>
#include <folly/portability/GTest.h>
#include <proxygen/httpserver/Mocks.h>
#include <proxygen/httpserver/samples/echo/EchoHandler.h>
#include <proxygen/httpserver/samples/echo/EchoStats.h>
Classes
class MockEchoStats
class EchoHandlerFixture
Functions
TEST_F (EchoHandlerFixture, OnProperRequestSendsResponse)
TEST_F (EchoHandlerFixture, ReplaysBodyProperly)
Function Documentation
TEST_F (EchoHandlerFixture , OnProperRequestSendsResponse)
Definition at line 49 of file EchoHandlerTest.cpp.
References testing::_, testing::DoAll(), EXPECT_CALL, EXPECT_EQ, proxygen::HTTPMessage::getHeaders(), proxygen::HTTPHeaders::getSingleOrEmpty(), proxygen::HTTPMessage::getStatusCode(), handler(), and testing::Return().
{
   EXPECT_CALL(stats, recordRequest()).WillOnce(Return());
   EXPECT_CALL(stats, getRequestCount()).WillOnce(Return(5));
   HTTPMessage response;
   EXPECT_CALL(*responseHandler, sendHeaders(_)).WillOnce(
       DoAll(SaveArg<0>(&response), Return()));
   EXPECT_CALL(*responseHandler, sendEOM()).WillOnce(Return());
   // Since we know we dont touch request, its ok to pass `nullptr` here.
   handler->onRequest(nullptr);
   handler->onEOM();
   handler->requestComplete();
   EXPECT_EQ("5", response.getHeaders().getSingleOrEmpty("Request-Number"));
   EXPECT_EQ(200, response.getStatusCode());
 }
TEST_F (EchoHandlerFixture , ReplaysBodyProperly)
Definition at line 67 of file EchoHandlerTest.cpp.
References testing::_, b, folly::IOBuf::copyBuffer(), testing::DoAll(), EXPECT_CALL, EXPECT_EQ, proxygen::HTTPMessage::getHeaders(), proxygen::HTTPHeaders::getSingleOrEmpty(), proxygen::HTTPMessage::getStatusCode(), handler(), testing::Invoke(), and testing::Return().
{
   EXPECT_CALL(stats, recordRequest()).WillOnce(Return());
   EXPECT_CALL(stats, getRequestCount()).WillOnce(Return(5));
   HTTPMessage response;
   folly::fbstring body;
   EXPECT_CALL(*responseHandler, sendHeaders(_)).WillOnce(
       DoAll(SaveArg<0>(&response), Return()));
   EXPECT_CALL(*responseHandler, sendBody(_)).WillRepeatedly(
       DoAll(
           Invoke([&] (std::shared_ptr<folly::IOBuf> b) {
             body += b->moveToFbString();
           }),
           Return()));
   EXPECT_CALL(*responseHandler, sendEOM()).WillOnce(Return());
   // Since we know we dont touch request, its ok to pass `nullptr` here.
   handler->onRequest(nullptr);
   handler->onBody(folly::IOBuf::copyBuffer("part1"));
   handler->onBody(folly::IOBuf::copyBuffer("part2"));
   handler->onEOM();
   handler->requestComplete();
   EXPECT_EQ("5", response.getHeaders().getSingleOrEmpty("Request-Number"));
   EXPECT_EQ(200, response.getStatusCode());
   EXPECT_EQ("part1part2", body);
 }