proxygen: proxygen/folly/folly/experimental/symbolizer/test/ElfTests.cpp File Reference
ElfTests.cpp File Reference
#include <folly/FileUtil.h>
#include <folly/experimental/TestUtil.h>
#include <folly/experimental/symbolizer/Elf.h>
#include <folly/portability/GTest.h>
Classes
class ElfTest
Functions
TEST_F (ElfTest, IntegerValue)
TEST_F (ElfTest, PointerValue)
TEST_F (ElfTest, iterateProgramHeaders)
TEST_F (ElfTest, TinyNonElfFile)
TEST_F (ElfTest, NonElfScript)
Variables
uint64_t kIntegerValue = 1234567890UL
const char * kStringValue = "coconuts"
Function Documentation
TEST_F (ElfTest , IntegerValue)
Definition at line 34 of file ElfTests.cpp.
References ElfTest::elfFile_, EXPECT_EQ, EXPECT_NE, folly::symbolizer::ElfFile::getSymbolByName(), folly::symbolizer::ElfFile::getSymbolValue(), kIntegerValue, and uint64_t.
{
   auto sym = elfFile_.getSymbolByName("kIntegerValue");
   EXPECT_NE(nullptr, sym.first) << "Failed to look up symbol kIntegerValue";
   EXPECT_EQ(kIntegerValue, elfFile_.getSymbolValue<uint64_t>(sym.second));
 }
TEST_F (ElfTest , PointerValue)
Definition at line 40 of file ElfTests.cpp.
References addr, ElfTest::elfFile_, EXPECT_NE, EXPECT_STREQ, folly::symbolizer::ElfFile::getAddressValue(), folly::symbolizer::ElfFile::getSymbolByName(), folly::symbolizer::ElfFile::getSymbolValue(), and kStringValue.
{
   auto sym = elfFile_.getSymbolByName("kStringValue");
   EXPECT_NE(nullptr, sym.first) << "Failed to look up symbol kStringValue";
   ElfW(Addr) addr = elfFile_.getSymbolValue<ElfW(Addr)>(sym.second);
   const char* str = &elfFile_.getAddressValue<const char>(addr);
   EXPECT_STREQ(kStringValue, str);
 }
TEST_F (ElfTest , iterateProgramHeaders)
Definition at line 48 of file ElfTests.cpp.
References ElfTest::elfFile_, EXPECT_GE, EXPECT_NE, h, and folly::symbolizer::ElfFile::iterateProgramHeaders().
{
   auto phdr = elfFile_.iterateProgramHeaders(
       [](auto& h) { return h.p_type == PT_LOAD; });
   EXPECT_NE(nullptr, phdr);
   EXPECT_GE(phdr->p_filesz, 0);
 }
TEST_F (ElfTest , TinyNonElfFile)
Definition at line 55 of file ElfTests.cpp.
References folly::Range< Iter >::data(), EXPECT_EQ, EXPECT_STREQ, folly::test::TemporaryFile::fd(), folly::symbolizer::ElfFile::openNoThrow(), folly::test::TemporaryFile::path(), folly::Range< Iter >::size(), and folly::writeFull().
{
   folly::test::TemporaryFile tmpFile;
   const static folly::StringPiece contents = "!";
   folly::writeFull(tmpFile.fd(), contents.data(), contents.size());
   ElfFile elfFile;
   const char* msg = nullptr;
   auto res = elfFile.openNoThrow(tmpFile.path().c_str(), true, &msg);
   EXPECT_EQ(ElfFile::kInvalidElfFile, res);
   EXPECT_STREQ("not an ELF file (too short)", msg);
 }
TEST_F (ElfTest , NonElfScript)
Definition at line 67 of file ElfTests.cpp.
References folly::Range< Iter >::data(), EXPECT_EQ, EXPECT_STREQ, folly::test::TemporaryFile::fd(), folly::symbolizer::ElfFile::openNoThrow(), folly::test::TemporaryFile::path(), folly::Range< Iter >::size(), and folly::writeFull().
{
   folly::test::TemporaryFile tmpFile;
   const static folly::StringPiece contents =
       "#!/bin/sh\necho I'm small non-ELF executable\n";
   folly::writeFull(tmpFile.fd(), contents.data(), contents.size());
   ElfFile elfFile;
   const char* msg = nullptr;
   auto res = elfFile.openNoThrow(tmpFile.path().c_str(), true, &msg);
   EXPECT_EQ(ElfFile::kInvalidElfFile, res);
   EXPECT_STREQ("invalid ELF magic", msg);
 }
Variable Documentation
uint64_t kIntegerValue = 1234567890UL
Definition at line 26 of file ElfTests.cpp.
Referenced by TEST_F().
const char* kStringValue = "coconuts"
Definition at line 27 of file ElfTests.cpp.
Referenced by TEST_F().