proxygen: proxygen/folly/folly/io/async/test/EventBaseThreadTest.cpp File Reference
EventBaseThreadTest.cpp File Reference
#include <folly/io/async/EventBaseThread.h>
#include <chrono>
#include <folly/io/async/EventBaseManager.h>
#include <folly/portability/GTest.h>
#include <folly/synchronization/Baton.h>
#include <folly/system/ThreadName.h>
Classes
class EventBaseThreadTest
Functions
TEST_F (EventBaseThreadTest, example)
TEST_F (EventBaseThreadTest, start_stop)
TEST_F (EventBaseThreadTest, move)
TEST_F (EventBaseThreadTest, self_move)
TEST_F (EventBaseThreadTest, default_manager)
TEST_F (EventBaseThreadTest, custom_manager)
Function Documentation
TEST_F (EventBaseThreadTest , example)
Definition at line 32 of file EventBaseThreadTest.cpp.
References ASSERT_TRUE, EXPECT_EQ, folly::getCurrentThreadName(), folly::EventBaseThread::getEventBase(), folly::Baton< MayBlock, Atom >::post(), folly::EventBase::runInEventBaseThread(), folly::Baton< MayBlock, Atom >::try_wait_for(), and value.
{
   EventBaseThread ebt(true, nullptr, "monkey");
   Baton<> done;
   ebt.getEventBase()->runInEventBaseThread([&] {
     EXPECT_EQ(getCurrentThreadName().value(), "monkey");
     done.post();
   });
   ASSERT_TRUE(done.try_wait_for(seconds(1)));
 }
TEST_F (EventBaseThreadTest , start_stop)
Definition at line 43 of file EventBaseThreadTest.cpp.
References ASSERT_TRUE, EXPECT_EQ, EXPECT_NE, folly::EventBaseThread::getEventBase(), i, folly::EventBase::runInEventBaseThread(), folly::EventBaseThread::start(), and folly::EventBaseThread::stop().
{
   EventBaseThread ebt(false);
   for (size_t i = 0; i < 4; ++i) {
     EXPECT_EQ(nullptr, ebt.getEventBase());
     ebt.start();
     EXPECT_NE(nullptr, ebt.getEventBase());
     Baton<> done;
     ebt.getEventBase()->runInEventBaseThread([&] { done.post(); });
     ASSERT_TRUE(done.try_wait_for(seconds(1)));
     EXPECT_NE(nullptr, ebt.getEventBase());
     ebt.stop();
     EXPECT_EQ(nullptr, ebt.getEventBase());
   }
 }
TEST_F (EventBaseThreadTest , move)
Definition at line 61 of file EventBaseThreadTest.cpp.
References ASSERT_TRUE, EXPECT_EQ, EXPECT_NE, and folly::gen::move.
{
   auto ebt0 = EventBaseThread();
   auto ebt1 = std::move(ebt0);
   auto ebt2 = std::move(ebt1);
   EXPECT_EQ(nullptr, ebt0.getEventBase());
   EXPECT_EQ(nullptr, ebt1.getEventBase());
   EXPECT_NE(nullptr, ebt2.getEventBase());
   Baton<> done;
   ebt2.getEventBase()->runInEventBaseThread([&] { done.post(); });
   ASSERT_TRUE(done.try_wait_for(seconds(1)));
 }
TEST_F (EventBaseThreadTest , self_move)
Definition at line 75 of file EventBaseThreadTest.cpp.
References ASSERT_TRUE, EXPECT_NE, and folly::gen::move.
{
   EventBaseThread ebt0;
   auto ebt = std::move(ebt0);
   EXPECT_NE(nullptr, ebt.getEventBase());
   Baton<> done;
   ebt.getEventBase()->runInEventBaseThread([&] { done.post(); });
   ASSERT_TRUE(done.try_wait_for(seconds(1)));
 }
TEST_F (EventBaseThreadTest , default_manager)
Definition at line 86 of file EventBaseThreadTest.cpp.
References EXPECT_EQ, folly::pushmi::operators::get, folly::EventBaseThread::getEventBase(), and folly::EventBase::runInEventBaseThreadAndWait().
{
   auto ebm = EventBaseManager::get();
   EventBaseThread ebt;
   auto ebt_eb = ebt.getEventBase();
   auto ebm_eb = static_cast<EventBase*>(nullptr);
   ebt_eb->runInEventBaseThreadAndWait([&] { ebm_eb = ebm->getEventBase(); });
   EXPECT_EQ(uintptr_t(ebt_eb), uintptr_t(ebm_eb));
 }
TEST_F (EventBaseThreadTest , custom_manager)
Definition at line 95 of file EventBaseThreadTest.cpp.
References EXPECT_EQ, folly::EventBaseThread::getEventBase(), folly::EventBaseManager::getEventBase(), and folly::EventBase::runInEventBaseThreadAndWait().
{
   EventBaseManager ebm;
   EventBaseThread ebt(&ebm);
   auto ebt_eb = ebt.getEventBase();
   auto ebm_eb = static_cast<EventBase*>(nullptr);
   ebt_eb->runInEventBaseThreadAndWait([&] { ebm_eb = ebm.getEventBase(); });
   EXPECT_EQ(uintptr_t(ebt_eb), uintptr_t(ebm_eb));
 }