proxygen: proxygen/folly/folly/io/async/test/EventBaseBenchmark.cpp File Reference
EventBaseBenchmark.cpp File Reference
#include <folly/Benchmark.h>
#include <folly/io/async/EventBase.h>
#include <folly/portability/GFlags.h>
Classes
class CountedLoopCallback
Functions
BENCHMARK (timeMeasurementsOn, n)
BENCHMARK_RELATIVE (timeMeasurementsOff, n)
int main (int argc, char **argv)
Function Documentation
BENCHMARK (timeMeasurementsOn , n)
Definition at line 39 of file EventBaseBenchmark.cpp.
References c, folly::EventBase::loop(), and folly::EventBase::runInLoop().
{
   EventBase eventBase;
   while (n--) {
     CountedLoopCallback c(&eventBase, 10);
     eventBase.runInLoop(&c);
     eventBase.loop();
   }
 }
BENCHMARK_RELATIVE (timeMeasurementsOff , n)
Definition at line 49 of file EventBaseBenchmark.cpp.
References c, folly::EventBase::loop(), and folly::EventBase::runInLoop().
{
   EventBase eventBase(/* enableTimeMeasurement */ false);
   while (n--) {
     CountedLoopCallback c(&eventBase, 10);
     eventBase.runInLoop(&c);
     eventBase.loop();
   }
 }
int main (int argc, char ** argv)
–bm_min_iters=1000000
folly/io/async/test/EventBaseBenchmark.cpp relative time/iter iters/s
timeMeasurementsOn 1.25us 798.33K
timeMeasurementsOff 214.47% 584.04ns 1.71M
Definition at line 70 of file EventBaseBenchmark.cpp.
References folly::runBenchmarks().
{
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   runBenchmarks();
 }