proxygen: proxygen/folly/folly/io/async/test/EventBaseLocalTest.cpp File Reference
EventBaseLocalTest.cpp File Reference
#include <folly/io/async/EventBaseLocal.h>
#include <folly/portability/GTest.h>
Classes
class Foo
Typedefs
using IntPtr = std::unique_ptr< int >
Functions
TEST (EventBaseLocalTest, Basic)
TEST (EventBaseLocalTest, getOrCreate)
TEST (EventBaseLocalTest, getOrCreateNoncopyable)
TEST (EventBaseLocalTest, emplaceNoncopyable)
Typedef Documentation
using IntPtr = std::unique_ptr<int>
Definition at line 75 of file EventBaseLocalTest.cpp.
Function Documentation
TEST (EventBaseLocalTest , Basic)
Definition at line 31 of file EventBaseLocalTest.cpp.
References folly::EventBaseLocal< T >::emplace(), folly::detail::EventBaseLocalBase::erase(), EXPECT_EQ, testing::gmock_matchers_test::foo, folly::EventBaseLocal< T >::get(), and folly::EventBase::loop().
{
   int dtorCnt = 0;
   folly::EventBase evb1;
   {
     folly::EventBaseLocal<Foo> foo;
     EXPECT_EQ(foo.get(evb1), nullptr);
     foo.emplace(evb1, new Foo(5, [&]() { ++dtorCnt; }));
     EXPECT_EQ(foo.get(evb1)->n, 5);
     {
       folly::EventBase evb2;
       foo.emplace(evb2, new Foo(6, [&]() { ++dtorCnt; }));
       EXPECT_EQ(foo.get(evb2)->n, 6);
       foo.erase(evb2);
       EXPECT_EQ(dtorCnt, 1); // should dtor a Foo when we erase
       EXPECT_EQ(foo.get(evb2), nullptr);
       foo.emplace(evb2, 7, [&]() { ++dtorCnt; });
       EXPECT_EQ(foo.get(evb2)->n, 7);
     }
     EXPECT_EQ(dtorCnt, 2); // should dtor a Foo when evb2 destructs
   }
   EXPECT_EQ(dtorCnt, 2); // should schedule Foo destructor, when foo destructs
   evb1.loop();
   EXPECT_EQ(dtorCnt, 3); // Foo will be destroyed in EventBase loop
 }
TEST (EventBaseLocalTest , getOrCreate)
Definition at line 62 of file EventBaseLocalTest.cpp.
References folly::detail::EventBaseLocalBase::erase(), EXPECT_EQ, folly::EventBaseLocal< T >::getOrCreate(), and folly::EventBaseLocal< T >::getOrCreateFn().
{
   folly::EventBase evb1;
   folly::EventBaseLocal<int> ints;
   EXPECT_EQ(ints.getOrCreate(evb1), 0);
   EXPECT_EQ(ints.getOrCreate(evb1, 5), 0);
   folly::EventBase evb2;
   EXPECT_EQ(ints.getOrCreate(evb2, 5), 5);
   ints.erase(evb2);
   EXPECT_EQ(4, ints.getOrCreateFn(evb2, []() { return new int(4); }));
 }
TEST (EventBaseLocalTest , getOrCreateNoncopyable)
Definition at line 77 of file EventBaseLocalTest.cpp.
References EXPECT_EQ, and folly::EventBaseLocal< T >::getOrCreate().
{
   folly::EventBase evb1;
   folly::EventBaseLocal<IntPtr> ints;
   EXPECT_EQ(ints.getOrCreate(evb1), IntPtr());
   EXPECT_EQ(ints.getOrCreate(evb1, std::make_unique<int>(5)), IntPtr());
   folly::EventBase evb2;
   EXPECT_EQ(*ints.getOrCreate(evb2, std::make_unique<int>(5)), 5);
 }
TEST (EventBaseLocalTest , emplaceNoncopyable)
Definition at line 88 of file EventBaseLocalTest.cpp.
References folly::EventBaseLocal< T >::emplace(), EXPECT_EQ, and folly::EventBaseLocal< T >::get().
{
   folly::EventBase evb;
   folly::EventBaseLocal<IntPtr> ints;
   ints.emplace(evb, std::make_unique<int>(42));
   EXPECT_EQ(42, **ints.get(evb));
 }