proxygen: proxygen/folly/folly/experimental/exception_tracer/ExceptionTracerLib.cpp File Reference
ExceptionTracerLib.cpp File Reference
#include <folly/experimental/exception_tracer/ExceptionTracerLib.h>
#include <dlfcn.h>
#include <vector>
#include <folly/Indestructible.h>
#include <folly/Portability.h>
#include <folly/SharedMutex.h>
#include <folly/Synchronized.h>
Namespaces
__cxxabiv1
folly
—— Concurrent Priority Queue Implementation ——
folly::exception_tracer
Macros
#define DECLARE_CALLBACK(NAME)
Functions
void __cxxabiv1::__cxa_throw (void *thrownException, std::type_info *type, void(*destructor)(void *)) __attribute__((__noreturn__))
void * __cxxabiv1::__cxa_begin_catch (void *excObj) throw ()
void __cxxabiv1::__cxa_rethrow (void) __attribute__((__noreturn__))
void __cxxabiv1::__cxa_end_catch (void)
CallbackHolder< CxaThrowType > & folly::exception_tracer::getCxaThrowCallbacks ()
void folly::exception_tracer::registerCxaThrowCallback (CxaThrowType callback)
CallbackHolder< CxaBeginCatchType > & folly::exception_tracer::getCxaBeginCatchCallbacks ()
void folly::exception_tracer::registerCxaBeginCatchCallback (CxaBeginCatchType callback)
CallbackHolder< CxaRethrowType > & folly::exception_tracer::getCxaRethrowCallbacks ()
void folly::exception_tracer::registerCxaRethrowCallback (CxaRethrowType callback)
CallbackHolder< CxaEndCatchType > & folly::exception_tracer::getCxaEndCatchCallbacks ()
void folly::exception_tracer::registerCxaEndCatchCallback (CxaEndCatchType callback)
CallbackHolder< RethrowExceptionType > & folly::exception_tracer::getRethrowExceptionCallbacks ()
void folly::exception_tracer::registerRethrowExceptionCallback (RethrowExceptionType callback)
void std::rethrow_exception (std::exception_ptr ep)
Macro Definition Documentation
#define DECLARE_CALLBACK (NAME)
Value:
CallbackHolder<NAME##Type>& get##NAME##Callbacks() {           \
    static Indestructible<CallbackHolder<NAME##Type>> Callbacks; \
    return *Callbacks;                                           \
  }                                                              \
  void register##NAME##Callback(NAME##Type callback) {           \
    get##NAME##Callbacks().registerCallback(callback);           \
  }
Definition at line 71 of file ExceptionTracerLib.cpp.
Function Documentation
void std::rethrow_exception (std::exception_ptr ep)
Definition at line 144 of file ExceptionTracerLib.cpp.
References folly::exception_tracer::getRethrowExceptionCallbacks(), and std::rethrow_exception().
Referenced by std::rethrow_exception().
{
   // Mangled name for std::rethrow_exception
   // TODO(tudorb): Dicey, as it relies on the fact that std::exception_ptr
   // is typedef'ed to a type in namespace __exception_ptr
   static auto orig_rethrow_exception =
       reinterpret_cast<decltype(&rethrow_exception)>(dlsym(
           RTLD_NEXT,
           "_ZSt17rethrow_exceptionNSt15__exception_ptr13exception_ptrE"));
   getRethrowExceptionCallbacks().invoke(ep);
   orig_rethrow_exception(ep);
   __builtin_unreachable(); // orig_rethrow_exception never returns
 }