proxygen: proxygen/folly/folly/experimental/exception_tracer/test/ExceptionTracerTest.cpp File Reference
ExceptionTracerTest.cpp File Reference
#include <iostream>
#include <stdexcept>
#include <folly/experimental/exception_tracer/ExceptionTracer.h>
Functions
void bar ()
void dumpExceptions (const char *prefix)
void foo ()
void baz ()
void testExceptionPtr1 ()
void testExceptionPtr2 ()
int main (int, char *[])
Function Documentation
void bar ()
Definition at line 22 of file ExceptionTracerTest.cpp.
Referenced by baz(), folly::symbolizer::test::comparator(), foo(), folly::symbolizer::test::ElfCacheTest::SetUp(), folly::symbolizer::test::TEST(), and testExceptionPtr1().
{
   throw std::runtime_error("hello");
 }
void baz ()
Definition at line 48 of file ExceptionTracerTest.cpp.
References bar(), and dumpExceptions().
Referenced by main().
{
   try {
     try {
       bar();
     } catch (...) {
       dumpExceptions("baz: simple catch");
       throw;
     }
   } catch (const std::exception& e) {
     dumpExceptions("baz: catch rethrown exception");
     throw "hello";
   }
 }
void dumpExceptions (const char * prefix)
Definition at line 27 of file ExceptionTracerTest.cpp.
References folly::exception_tracer::getCurrentExceptions().
Referenced by baz(), foo(), testExceptionPtr1(), and testExceptionPtr2().
{
   std::cerr << "--- " << prefix << "\n";
   auto exceptions = ::folly::exception_tracer::getCurrentExceptions();
   for (auto& exc : exceptions) {
     std::cerr << exc << "\n";
   }
 }
void foo ()
Definition at line 35 of file ExceptionTracerTest.cpp.
References bar(), and dumpExceptions().
Referenced by main().
            {
   try {
     try {
       bar();
     } catch (const std::exception& e) {
       dumpExceptions("foo: simple catch");
       bar();
     }
   } catch (const std::exception& e) {
     dumpExceptions("foo: catch, exception thrown from previous catch block");
   }
 }
int main (int , char * [])
Definition at line 92 of file ExceptionTracerTest.cpp.
References baz(), foo(), testExceptionPtr1(), and testExceptionPtr2().
{
   foo();
   testExceptionPtr1();
   testExceptionPtr2();
   baz();
   // no return because baz() is [[noreturn]]
 }
void testExceptionPtr1 ()
Definition at line 62 of file ExceptionTracerTest.cpp.
References bar(), and dumpExceptions().
Referenced by main().
{
   std::exception_ptr exc;
   try {
     bar();
   } catch (...) {
     exc = std::current_exception();
   }
   try {
     std::rethrow_exception(exc);
   } catch (...) {
     dumpExceptions("std::rethrow_exception 1");
   }
 }
void testExceptionPtr2 ()
Definition at line 77 of file ExceptionTracerTest.cpp.
References dumpExceptions().
Referenced by main().
{
   std::exception_ptr exc;
   try {
     throw std::out_of_range("x");
   } catch (...) {
     exc = std::current_exception();
   }
   try {
     std::rethrow_exception(exc);
   } catch (...) {
     dumpExceptions("std::rethrow_exception 2");
   }
 }