proxygen: proxygen/folly/folly/experimental/exception_tracer/ExceptionStackTraceLib.cpp File Reference
ExceptionStackTraceLib.cpp File Reference
#include <exception>
#include <folly/experimental/exception_tracer/ExceptionAbi.h>
#include <folly/experimental/exception_tracer/ExceptionTracer.h>
#include <folly/experimental/exception_tracer/ExceptionTracerLib.h>
#include <folly/experimental/exception_tracer/StackTrace.h>
#include <folly/experimental/symbolizer/Symbolizer.h>
Functions
StackTraceStack * getExceptionStackTraceStack ()
Function Documentation
StackTraceStack* getExceptionStackTraceStack ()
Definition at line 39 of file ExceptionStackTraceLib.cpp.
References __cxxabiv1::__cxa_get_globals_fast(), __cxxabiv1::__cxa_eh_globals::caughtExceptions, folly::exception_tracer::StackTraceStack::clear(), folly::pushmi::operators::from, __cxxabiv1::__cxa_exception::handlerCount, folly::exception_tracer::installHandlers(), folly::exception_tracer::StackTraceStack::moveTopFrom(), folly::pushmi::__adl::noexcept(), folly::exception_tracer::registerCxaBeginCatchCallback(), folly::exception_tracer::registerCxaEndCatchCallback(), folly::exception_tracer::registerCxaRethrowCallback(), folly::exception_tracer::registerCxaThrowCallback(), folly::exception_tracer::registerRethrowExceptionCallback(), folly::to(), and folly::pushmi::top.
Referenced by folly::exception_tracer::getCurrentExceptions().
{
   return invalid ? nullptr : &caughtExceptions;
 }