proxygen: proxygen/folly/folly/experimental/exception_tracer/test/ExceptionTracerBenchmark.cpp File Reference
ExceptionTracerBenchmark.cpp File Reference
#include <stdexcept>
#include <thread>
#include <vector>
#include <glog/logging.h>
#include <folly/Benchmark.h>
#include <folly/experimental/exception_tracer/ExceptionTracer.h>
#include <folly/portability/GFlags.h>
Functions
void recurse (int level)
void loop (int iters)
BENCHMARK (ExceptionTracer, iters)
int main (int argc, char *argv[])
Function Documentation
BENCHMARK (ExceptionTracer , iters)
Definition at line 45 of file ExceptionTracerBenchmark.cpp.
References kNumThreads, loop(), folly::pushmi::detail::t, and threads.
{
   std::vector<std::thread> threads;
   constexpr size_t kNumThreads = 10;
   threads.resize(kNumThreads);
   for (auto& t : threads) {
     t = std::thread([iters]() { loop(iters); });
   }
   for (auto& t : threads) {
     t.join();
   }
 }
void loop (int iters)
Definition at line 35 of file ExceptionTracerBenchmark.cpp.
References folly::exception_tracer::getCurrentExceptions(), i, and recurse().
Referenced by BENCHMARK(), folly::EventBase::EventBase(), fizz::tool::fizzServerCommand(), main(), runBenchmark(), and TEST_F().
                      {
   for (int i = 0; i < iters * 100; ++i) {
     try {
       recurse(100);
     } catch (const std::exception& e) {
       folly::exception_tracer::getCurrentExceptions();
     }
   }
 }
int main (int argc, char * argv[])
Definition at line 57 of file ExceptionTracerBenchmark.cpp.
References folly::runBenchmarks().
{
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   google::InitGoogleLogging(argv[0]);
   folly::runBenchmarks();
   return 0;
 }
void recurse (int level)
Definition at line 27 of file ExceptionTracerBenchmark.cpp.
References folly::doNotOptimizeAway().
Referenced by loop().
{
   if (level == 0) {
     throw std::runtime_error("");
   }
   recurse(level - 1);
   folly::doNotOptimizeAway(0); // prevent tail recursion
 }