proxygen: proxygen/folly/folly/container/test/F14AsanSupportTest.cpp File Reference
F14AsanSupportTest.cpp File Reference
#include <folly/Portability.h>
#include <folly/container/F14Set.h>
#include <folly/portability/GTest.h>
Functions
template<typename S >
void useIteratorAfterInsertSmall ()
template<typename S >
void useIteratorAfterInsertLarge ()
template<typename S >
void useReferenceAfterInsertSmall ()
template<typename S >
void useReferenceAfterInsertLarge ()
template<typename F >
void repeat (F const &func)
template<typename F >
void expectAsanFailure (F const &func)
TEST (F14AsanSupportTest, F14ValueIterInsertSmall)
TEST (F14AsanSupportTest, F14NodeIterInsertSmall)
TEST (F14AsanSupportTest, F14VectorIterInsertSmall)
TEST (F14AsanSupportTest, F14FastIterInsertSmall)
TEST (F14AsanSupportTest, F14ValueIterInsertLarge)
TEST (F14AsanSupportTest, F14NodeIterInsertLarge)
TEST (F14AsanSupportTest, F14VectorIterInsertLarge)
TEST (F14AsanSupportTest, F14FastIterInsertLarge)
TEST (F14AsanSupportTest, F14ValueRefInsertSmall)
TEST (F14AsanSupportTest, F14VectorRefInsertSmall)
TEST (F14AsanSupportTest, F14FastRefInsertSmall)
TEST (F14AsanSupportTest, F14ValueRefInsertLarge)
TEST (F14AsanSupportTest, F14VectorRefInsertLarge)
TEST (F14AsanSupportTest, F14FastRefInsertLarge)
TEST (F14AsanSupportTest, F14VectorErase)
Function Documentation
template<typename F > void expectAsanFailure (F const & func)
Definition at line 73 of file F14AsanSupportTest.cpp.
References folly::kIsSanitizeAddress, and repeat().
Referenced by TEST().
{
   if (kIsSanitizeAddress) {
     EXPECT_EXIT(
         repeat(func), testing::ExitedWithCode(1), ".*heap-use-after-free.*");
   }
 }
template<typename F > void repeat (F const & func)
Definition at line 66 of file F14AsanSupportTest.cpp.
References i.
Referenced by testing::InitGoogleTestTest::CheckFlags(), expectAsanFailure(), testing::GetDefaultFilter(), testing::internal::GetThreadCount(), testing::internal::GetUnitTestImpl(), testing::internal::GTestFlagSaver::GTestFlagSaver(), main(), testing::internal::PrettyUnitTestResultPrinter::OnTestIterationStart(), testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), testing::internal::ParseGoogleTestFlag(), testing::PrintFlag(), testing::Flags::Repeat(), testing::internal::UnitTestImpl::RunAllTests(), testing::internal::UnitTestImpl::set_catch_exceptions(), testing::InitGoogleTestTest::SetUp(), testing::internal::TearDownEnvironment(), TEST(), testing::Flags::ThrowOnFailure(), testing::internal::UnitTestRecordPropertyTestHelper::UnitTestRecordProperty(), and testing::internal::GTestFlagSaver::~GTestFlagSaver().
{
   for (int i = 0; i < 32; ++i) {
     func();
   }
 }
TEST (F14AsanSupportTest , F14ValueIterInsertSmall)
Definition at line 80 of file F14AsanSupportTest.cpp.
References expectAsanFailure(), and useIteratorAfterInsertSmall().
{
   expectAsanFailure(useIteratorAfterInsertSmall<F14ValueSet<int>>);
 }
TEST (F14AsanSupportTest , F14NodeIterInsertSmall)
Definition at line 83 of file F14AsanSupportTest.cpp.
References expectAsanFailure(), and useIteratorAfterInsertSmall().
{
   expectAsanFailure(useIteratorAfterInsertSmall<F14NodeSet<int>>);
 }
TEST (F14AsanSupportTest , F14VectorIterInsertSmall)
Definition at line 86 of file F14AsanSupportTest.cpp.
References expectAsanFailure(), and useIteratorAfterInsertSmall().
{
   expectAsanFailure(useIteratorAfterInsertSmall<F14VectorSet<int>>);
 }
TEST (F14AsanSupportTest , F14FastIterInsertSmall)
Definition at line 89 of file F14AsanSupportTest.cpp.
References expectAsanFailure(), and useIteratorAfterInsertSmall().
{
   expectAsanFailure(useIteratorAfterInsertSmall<F14FastSet<int>>);
 }
TEST (F14AsanSupportTest , F14ValueIterInsertLarge)
Definition at line 93 of file F14AsanSupportTest.cpp.
References expectAsanFailure(), and useIteratorAfterInsertLarge().
{
   expectAsanFailure(useIteratorAfterInsertLarge<F14ValueSet<int>>);
 }
TEST (F14AsanSupportTest , F14NodeIterInsertLarge)
Definition at line 96 of file F14AsanSupportTest.cpp.
References expectAsanFailure(), and useIteratorAfterInsertLarge().
{
   expectAsanFailure(useIteratorAfterInsertLarge<F14NodeSet<int>>);
 }
TEST (F14AsanSupportTest , F14VectorIterInsertLarge)
Definition at line 99 of file F14AsanSupportTest.cpp.
References expectAsanFailure(), and useIteratorAfterInsertLarge().
{
   expectAsanFailure(useIteratorAfterInsertLarge<F14VectorSet<int>>);
 }
TEST (F14AsanSupportTest , F14FastIterInsertLarge)
Definition at line 102 of file F14AsanSupportTest.cpp.
References expectAsanFailure(), and useIteratorAfterInsertLarge().
{
   expectAsanFailure(useIteratorAfterInsertLarge<F14FastSet<int>>);
 }
TEST (F14AsanSupportTest , F14ValueRefInsertSmall)
Definition at line 106 of file F14AsanSupportTest.cpp.
References expectAsanFailure(), and useReferenceAfterInsertSmall().
{
   expectAsanFailure(useReferenceAfterInsertSmall<F14ValueSet<int>>);
 }
TEST (F14AsanSupportTest , F14VectorRefInsertSmall)
Definition at line 109 of file F14AsanSupportTest.cpp.
References expectAsanFailure(), and useReferenceAfterInsertSmall().
{
   expectAsanFailure(useReferenceAfterInsertSmall<F14VectorSet<int>>);
 }
TEST (F14AsanSupportTest , F14FastRefInsertSmall)
Definition at line 112 of file F14AsanSupportTest.cpp.
References expectAsanFailure(), and useReferenceAfterInsertSmall().
{
   expectAsanFailure(useReferenceAfterInsertSmall<F14FastSet<int>>);
 }
TEST (F14AsanSupportTest , F14ValueRefInsertLarge)
Definition at line 116 of file F14AsanSupportTest.cpp.
References expectAsanFailure(), and useReferenceAfterInsertLarge().
{
   expectAsanFailure(useReferenceAfterInsertLarge<F14ValueSet<int>>);
 }
TEST (F14AsanSupportTest , F14VectorRefInsertLarge)
Definition at line 119 of file F14AsanSupportTest.cpp.
References expectAsanFailure(), and useReferenceAfterInsertLarge().
{
   expectAsanFailure(useReferenceAfterInsertLarge<F14VectorSet<int>>);
 }
TEST (F14AsanSupportTest , F14FastRefInsertLarge)
Definition at line 122 of file F14AsanSupportTest.cpp.
References expectAsanFailure(), and useReferenceAfterInsertLarge().
{
   expectAsanFailure(useReferenceAfterInsertLarge<F14FastSet<int>>);
 }
TEST (F14AsanSupportTest , F14VectorErase)
Definition at line 126 of file F14AsanSupportTest.cpp.
References EXPECT_EQ, EXPECT_NE, and folly::kIsSanitizeAddress.
{
   F14VectorSet<int> set;
   set.insert(1);
   set.insert(2);
   set.insert(3);
   auto& v = *set.begin();
   EXPECT_EQ(v, 3);
   set.erase(2);
   if (kIsSanitizeAddress) {
     EXPECT_NE(v, 3);
   }
 }
template<typename S > void useIteratorAfterInsertLarge ()
Definition at line 32 of file F14AsanSupportTest.cpp.
References EXPECT_EQ, and i.
Referenced by TEST().
{
   S set;
   set.insert(10);
   for (int i = 0; i < 1000; ++i) {
     auto iter = set.find(10);
     set.insert(i);
     if (i > 500) {
       EXPECT_EQ(*iter, 10);
     }
   }
 }
template<typename S > void useIteratorAfterInsertSmall ()
Definition at line 24 of file F14AsanSupportTest.cpp.
References EXPECT_EQ.
Referenced by TEST().
{
   S set;
   auto iter = set.insert(1).first;
   set.insert(2);
   EXPECT_EQ(*iter, 1);
 }
template<typename S > void useReferenceAfterInsertLarge ()
Definition at line 53 of file F14AsanSupportTest.cpp.
References EXPECT_EQ, and i.
Referenced by TEST().
{
   S set;
   set.insert(10);
   for (int i = 0; i < 1000; ++i) {
     auto& ref = *set.find(10);
     set.insert(i);
     if (i > 500) {
       EXPECT_EQ(ref, 10);
     }
   }
 }
template<typename S > void useReferenceAfterInsertSmall ()
Definition at line 45 of file F14AsanSupportTest.cpp.
References EXPECT_EQ.
Referenced by TEST().
{
   S set;
   auto& ref = *set.insert(1).first;
   set.insert(2);
   EXPECT_EQ(ref, 1);
 }