proxygen: proxygen/folly/folly/container/test/F14SmallOverheads.cpp File Reference
F14SmallOverheads.cpp File Reference
#include <functional>
#include <iostream>
#include <limits>
#include <memory>
#include <string>
#include <unordered_map>
#include <utility>
#include <folly/container/F14Map.h>
Classes
struct LoggingAlloc< T >
struct LoggingAlloc< T >::rebind< U >
Typedefs
template<typename K , typename V , template< typename > class A>
using StdUnorderedMapTable = std::unordered_map< K, V, std::hash< K >, std::equal_to< K >, A< std::pair< K const, V >>>
template<typename K , typename V , template< typename > class A>
using F14ValueMapTable = F14ValueMap< K, V, std::hash< K >, std::equal_to< K >, A< std::pair< K const, V >>>
template<typename K , typename V , template< typename > class A>
using F14NodeMapTable = F14NodeMap< K, V, std::hash< K >, std::equal_to< K >, A< std::pair< K const, V >>>
template<typename K , typename V , template< typename > class A>
using F14VectorMapTable = F14VectorMap< K, V, std::hash< K >, std::equal_to< K >, A< std::pair< K const, V >>>
Functions
template<typename M >
void runSingleInsert (std::string const &name)
template<template< typename, typename, template< typename > class > class T>
void runSingleInserts (std::string const &name)
FOLLY_NOINLINE int codeSize_find_Std (std::unordered_map< int16_t, float > &m, int16_t k)
FOLLY_NOINLINE int codeSize_find_F14Value (F14ValueMap< int16_t, float > &m, int16_t k)
FOLLY_NOINLINE int codeSize_find_F14Node (F14NodeMap< int16_t, float > &m, int16_t k)
FOLLY_NOINLINE int codeSize_find_F14Vector (F14VectorMap< int16_t, float > &m, int16_t k)
FOLLY_NOINLINE void codeSize_bracket_Std (std::unordered_map< int16_t, uint32_t > &m, int16_t k, uint32_t v)
FOLLY_NOINLINE void codeSize_bracket_F14Value (F14ValueMap< int16_t, uint32_t > &m, int16_t k, uint32_t v)
FOLLY_NOINLINE void codeSize_bracket_F14Node (F14NodeMap< int16_t, uint32_t > &m, int16_t k, uint32_t v)
FOLLY_NOINLINE void codeSize_bracket_F14Vector (F14VectorMap< int16_t, uint32_t > &m, int16_t k, uint32_t v)
FOLLY_NOINLINE void codeSize_erase_Std (std::unordered_map< int16_t, uint32_t > &m, std::unordered_map< int16_t, uint32_t >::iterator iter)
FOLLY_NOINLINE void codeSize_erase_F14Value (F14ValueMap< int16_t, uint32_t > &m, F14ValueMap< int16_t, uint32_t >::iterator iter)
FOLLY_NOINLINE void codeSize_erase_F14Node (F14NodeMap< int16_t, uint32_t > &m, F14NodeMap< int16_t, uint32_t >::iterator iter)
FOLLY_NOINLINE void codeSize_erase_F14Vector (F14VectorMap< int16_t, uint32_t > &m, F14VectorMap< int16_t, uint32_t >::iterator iter)
int main (int, char **)
Typedef Documentation
template<typename K , typename V , template< typename > class A> using F14NodeMapTable = F14NodeMap<K, V, std::hash<K>, std::equal_to<K>, A<std::pair<K const, V>>>
Definition at line 96 of file F14SmallOverheads.cpp.
template<typename K , typename V , template< typename > class A> using F14ValueMapTable = F14ValueMap<K, V, std::hash<K>, std::equal_to<K>, A<std::pair<K const, V>>>
Definition at line 92 of file F14SmallOverheads.cpp.
template<typename K , typename V , template< typename > class A> using F14VectorMapTable = F14VectorMap< K, V, std::hash<K>, std::equal_to<K>, A<std::pair<K const, V>>>
Definition at line 104 of file F14SmallOverheads.cpp.
template<typename K , typename V , template< typename > class A> using StdUnorderedMapTable = std::unordered_map< K, V, std::hash<K>, std::equal_to<K>, A<std::pair<K const, V>>>
Definition at line 88 of file F14SmallOverheads.cpp.
Function Documentation
FOLLY_NOINLINE void codeSize_bracket_F14Node (F14NodeMap< int16_t, uint32_t > & m, int16_t k, uint32_t v)
Definition at line 175 of file F14SmallOverheads.cpp.
References k, and v.
Referenced by main().
                 {
   m[k] = v;
 }
FOLLY_NOINLINE void codeSize_bracket_F14Value (F14ValueMap< int16_t, uint32_t > & m, int16_t k, uint32_t v)
Definition at line 168 of file F14SmallOverheads.cpp.
References k, and v.
Referenced by main().
                 {
   m[k] = v;
 }
FOLLY_NOINLINE void codeSize_bracket_F14Vector (F14VectorMap< int16_t, uint32_t > & m, int16_t k, uint32_t v)
Definition at line 182 of file F14SmallOverheads.cpp.
References k, and v.
Referenced by main().
                 {
   m[k] = v;
 }
FOLLY_NOINLINE void codeSize_bracket_Std (std::unordered_map< int16_t, uint32_t > & m, int16_t k, uint32_t v)
Definition at line 161 of file F14SmallOverheads.cpp.
References k, and v.
Referenced by main().
                 {
   m[k] = v;
 }
FOLLY_NOINLINE void codeSize_erase_F14Node (F14NodeMap< int16_t, uint32_t > & m, F14NodeMap< int16_t, uint32_t >::iterator iter)
Definition at line 201 of file F14SmallOverheads.cpp.
Referenced by main().
{
   m.erase(iter);
 }
FOLLY_NOINLINE void codeSize_erase_F14Value (F14ValueMap< int16_t, uint32_t > & m, F14ValueMap< int16_t, uint32_t >::iterator iter)
Definition at line 195 of file F14SmallOverheads.cpp.
Referenced by main().
{
   m.erase(iter);
 }
FOLLY_NOINLINE void codeSize_erase_F14Vector (F14VectorMap< int16_t, uint32_t > & m, F14VectorMap< int16_t, uint32_t >::iterator iter)
Definition at line 207 of file F14SmallOverheads.cpp.
Referenced by main().
{
   m.erase(iter);
 }
FOLLY_NOINLINE void codeSize_erase_Std (std::unordered_map< int16_t, uint32_t > & m, std::unordered_map< int16_t, uint32_t >::iterator iter)
Definition at line 189 of file F14SmallOverheads.cpp.
Referenced by main().
{
   m.erase(iter);
 }
FOLLY_NOINLINE int codeSize_find_F14Node (F14NodeMap< int16_t, float > & m, int16_t k)
Definition at line 147 of file F14SmallOverheads.cpp.
References i.
Referenced by main().
                {
   auto i = m.find(k);
   return i != m.end() ? 1 : 0;
 }
FOLLY_NOINLINE int codeSize_find_F14Value (F14ValueMap< int16_t, float > & m, int16_t k)
Definition at line 140 of file F14SmallOverheads.cpp.
References i.
Referenced by main().
                {
   auto i = m.find(k);
   return i != m.end() ? 1 : 0;
 }
FOLLY_NOINLINE int codeSize_find_F14Vector (F14VectorMap< int16_t, float > & m, int16_t k)
Definition at line 154 of file F14SmallOverheads.cpp.
References i.
Referenced by main().
                {
   auto i = m.find(k);
   return i != m.end() ? 1 : 0;
 }
FOLLY_NOINLINE int codeSize_find_Std (std::unordered_map< int16_t, float > & m, int16_t k)
Definition at line 133 of file F14SmallOverheads.cpp.
References i.
Referenced by main().
                {
   auto i = m.find(k);
   return i != m.end() ? 1 : 0;
 }
int main (int , char **)
Definition at line 213 of file F14SmallOverheads.cpp.
References codeSize_bracket_F14Node(), codeSize_bracket_F14Value(), codeSize_bracket_F14Vector(), codeSize_bracket_Std(), codeSize_erase_F14Node(), codeSize_erase_F14Value(), codeSize_erase_F14Vector(), codeSize_erase_Std(), codeSize_find_F14Node(), codeSize_find_F14Value(), codeSize_find_F14Vector(), and codeSize_find_Std().
                       {
   (void)codeSize_find_Std;
   (void)codeSize_find_F14Value;
   (void)codeSize_find_F14Node;
   (void)codeSize_find_F14Vector;
   (void)codeSize_bracket_Std;
   (void)codeSize_bracket_F14Value;
   (void)codeSize_bracket_F14Node;
   (void)codeSize_bracket_F14Vector;
   (void)codeSize_erase_Std;
   (void)codeSize_erase_F14Value;
   (void)codeSize_erase_F14Node;
   (void)codeSize_erase_F14Vector;
   runSingleInserts<StdUnorderedMapTable>("std");
   runSingleInserts<F14ValueMapTable>("f14value");
   runSingleInserts<F14NodeMapTable>("f14node");
   runSingleInserts<F14VectorMapTable>("f14vector");
   return 0;
 }
template<typename M > void runSingleInsert (std::string const & name)
Definition at line 107 of file F14SmallOverheads.cpp.
References k, M, map(), and T.
{
   cout << "----------------------\n";
   cout << name << "\n";
   cout << "SIZE = " << sizeof(M) << "\n";
   cout << "CONSTRUCTING\n";
   {
     M map;
     cout << "INSERTING 1 VALUE\n";
     typename M::key_type k{};
     map[k];
     cout << "DESTROYING\n";
   }
   cout << "\n";
 }
template<template< typename, typename, template< typename > class > class T> void runSingleInserts (std::string const & name)
Definition at line 123 of file F14SmallOverheads.cpp.
References name.
{
   runSingleInsert<T<uint64_t, array<char, 8>, LoggingAlloc>>(
       name + " uint64_t 8");
   runSingleInsert<T<string, array<char, 8>, LoggingAlloc>>(name + " string 8");
   runSingleInsert<T<uint64_t, array<char, 128>, LoggingAlloc>>(
       name + " uint64_t 128");
   runSingleInsert<T<string, array<char, 128>, LoggingAlloc>>(
       name + " string 128");
 }