proxygen: proxygen/folly/folly/test/FBStringTestBenchmarks.cpp.h File Reference
FBStringTestBenchmarks.cpp.h File Reference
Functions
void BENCHFUN() initRNG (size_t, size_t)
void BENCHFUN() defaultCtor (size_t iters, size_t)
void BENCHFUN() copyCtor (size_t iters, size_t arg)
void BENCHFUN() ctorFromArray (size_t iters, size_t arg)
void BENCHFUN() ctorFromTwoPointers (size_t iters, size_t arg)
void BENCHFUN() ctorFromChar (size_t iters, size_t arg)
void BENCHFUN() assignmentOp (size_t iters, size_t arg)
void BENCHFUN() assignmentFill (size_t iters, size_t)
void BENCHFUN() resize (size_t iters, size_t arg)
void BENCHFUN() findSuccessful (size_t iters, size_t)
void BENCHFUN() findUnsuccessful (size_t iters, size_t)
void BENCHFUN() equality (size_t iters, size_t arg)
void BENCHFUN() replace (size_t iters, size_t arg)
void BENCHFUN() push_back (size_t iters, size_t arg)
void BENCHFUN() short_append (size_t iters, size_t arg)
void BENCHFUN() getline (size_t iters, size_t arg)
Function Documentation
void BENCHFUN() assignmentFill (size_t iters, size_t)
Definition at line 106 of file FBStringTestBenchmarks.cpp.h.
References BENCHFUN, BENCHMARK_PARAM, folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, s, and STRING.
{
   STRING s;
   FOR_EACH_RANGE (i, 0, iters) {
     s = static_cast<char>(i);
     doNotOptimizeAway(&s);
   }
 }
void BENCHFUN() assignmentOp (size_t iters, size_t arg)
Definition at line 90 of file FBStringTestBenchmarks.cpp.h.
References BENCHFUN, BENCHMARK_PARAM, BENCHMARK_SUSPEND, folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, randomString(), s, and STRING.
{
   STRING s;
   BENCHMARK_SUSPEND {
     randomString(&s, arg);
   }
   FOR_EACH_RANGE (i, 0, iters) {
     STRING s1;
     BENCHMARK_SUSPEND {
       randomString(&s1, arg);
       doNotOptimizeAway(&s1);
     }
     s1 = s;
   }
 }
void BENCHFUN() copyCtor (size_t iters, size_t arg)
Definition at line 37 of file FBStringTestBenchmarks.cpp.h.
References BENCHFUN, BENCHMARK_PARAM, BENCHMARK_SUSPEND, folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, randomString(), s, and STRING.
{
   STRING s;
   BENCHMARK_SUSPEND {
     randomString(&s, arg);
   }
   FOR_EACH_RANGE (i, 0, iters) {
     STRING s1 = s;
     doNotOptimizeAway(&s1);
   }
 }
void BENCHFUN() ctorFromArray (size_t iters, size_t arg)
Definition at line 49 of file FBStringTestBenchmarks.cpp.h.
References BENCHFUN, BENCHMARK_PARAM, BENCHMARK_SUSPEND, folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, randomString(), s, and STRING.
{
   STRING s;
   BENCHMARK_SUSPEND {
     randomString(&s, arg);
     if (s.empty()) {
       s = "This is rare.";
     }
   }
   FOR_EACH_RANGE (i, 0, iters) {
     STRING s1(s.data(), s.size());
     doNotOptimizeAway(&s1);
   }
 }
void BENCHFUN() ctorFromChar (size_t iters, size_t arg)
Definition at line 82 of file FBStringTestBenchmarks.cpp.h.
References BENCHFUN, BENCHMARK_PARAM, folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, and STRING.
{
   FOR_EACH_RANGE (i, 0, iters) {
     STRING s1('a', arg);
     doNotOptimizeAway(&s1);
   }
 }
void BENCHFUN() ctorFromTwoPointers (size_t iters, size_t arg)
Definition at line 64 of file FBStringTestBenchmarks.cpp.h.
References BENCHFUN, BENCHMARK_PARAM, BENCHMARK_SUSPEND, folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, s, and STRING.
{
   /* library-local */ static STRING s;
   BENCHMARK_SUSPEND {
     if (s.size() < arg) {
       s.resize(arg);
     }
   }
   FOR_EACH_RANGE (i, 0, iters) {
     STRING s1(s.begin(), s.end());
     doNotOptimizeAway(&s1);
   }
 }
void BENCHFUN() defaultCtor (size_t iters, size_t)
Definition at line 29 of file FBStringTestBenchmarks.cpp.h.
References BENCHFUN, BENCHMARK_PARAM, folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, s, and STRING.
{
   FOR_EACH_RANGE (i, 0, iters) {
     STRING s[4096];
     doNotOptimizeAway(&s);
   }
 }
void BENCHFUN() equality (size_t iters, size_t arg)
Definition at line 194 of file FBStringTestBenchmarks.cpp.h.
References BENCHFUN, BENCHMARK_PARAM, BENCHMARK_SUSPEND, folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, needle, randomBinaryString(), and STRING.
{
   std::vector<STRING> haystack(arg);
   BENCHMARK_SUSPEND {
     for (auto& hay : haystack) {
       randomBinaryString(&hay, 1024);
     }
   }
   FOR_EACH_RANGE (i, 0, iters) {
     STRING needle;
     randomBinaryString(&needle, 1024);
     doNotOptimizeAway(std::find(haystack.begin(), haystack.end(), needle));
   }
 }
void BENCHFUN() findSuccessful (size_t iters, size_t)
Definition at line 124 of file FBStringTestBenchmarks.cpp.h.
References BENCHFUN, BENCHMARK_PARAM, BENCHMARK_SUSPEND, folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, random(), s, and STRING.
{
   size_t pos, len;
   STRING s;
   BENCHMARK_SUSPEND {
     // Text courtesy (ahem) of
     // http://www.psychologytoday.com/blog/career-transitions/200906/
     // the-dreaded-writing-sample
     s = "\
 Even if you've mastered the art of the cover letter and the resume, \
 another part of the job search process can trip up an otherwise \
 qualified candidate: the writing sample.\n\
 \n\
 Strong writing and communication skills are highly sought after by \
 most employers. Whether crafting short emails or lengthy annual \
 reports, many workers use their writing skills every day. And for an \
 employer seeking proof behind that ubiquitous candidate \
 phrase,\"excellent communication skills\", a required writing sample \
 is invaluable.\n\
 \n\
 Writing samples need the same care and attention given to cover \
 letters and resumes. Candidates with otherwise impeccable credentials \
 are routinely eliminated by a poorly chosen writing sample. Notice I \
 said \"poorly chosen\" not \"poorly written.\" Because that's the rub: \
 a writing sample not only reveals the individual's writing skills, it \
 also offers a peek into what they consider important or relevant for \
 the position. If you miss that mark with your writing sample, don't \
 expect to get a call for an interview.";
     pos = random(0, s.size());
     len = random(0, s.size() - pos);
   }
   FOR_EACH_RANGE (i, 0, iters) {
     doNotOptimizeAway(s.find(s.data(), pos, len));
   }
 }
void BENCHFUN() findUnsuccessful (size_t iters, size_t)
Definition at line 162 of file FBStringTestBenchmarks.cpp.h.
References BENCHFUN, BENCHMARK_PARAM, BENCHMARK_SUSPEND, folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, s, and STRING.
{
   STRING s, s1;
   BENCHMARK_SUSPEND {
     s = "\
 Even if you've mastered the art of the cover letter and the resume, \
 another part of the job search process can trip up an otherwise \
 qualified candidate: the writing sample.\n\
 \n\
 Strong writing and communication skills are highly sought after by \
 most employers. Whether crafting short emails or lengthy annual \
 reports, many workers use their writing skills every day. And for an \
 employer seeking proof behind that ubiquitous candidate \
 phrase,\"excellent communication skills\", a required writing sample \
 is invaluable.\n\
 \n\
 Writing samples need the same care and attention given to cover \
 letters and resumes. Candidates with otherwise impeccable credentials \
 are routinely eliminated by a poorly chosen writing sample. Notice I \
 said \"poorly chosen\" not \"poorly written.\" Because that's the rub: \
 a writing sample not only reveals the individual's writing skills, it \
 also offers a peek into what they consider important or relevant for \
 the position. If you miss that mark with your writing sample, don't \
 expect to get a call for an interview.";
     s1 = "So how do you tackle that writing sample request?";
   }
   FOR_EACH_RANGE (i, 0, iters) { doNotOptimizeAway(s.find(s1)); }
 }
void BENCHFUN() getline (size_t iters, size_t arg)
Definition at line 251 of file FBStringTestBenchmarks.cpp.h.
References BENCHFUN, BENCHMARK_PARAM, BENCHMARK_SUSPEND, folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, folly::gen::lines(), randomString(), and STRING.
Referenced by folly::gen::detail::IStreamByLine::apply(), main(), folly::CacheLocality::readFromSysfs(), and TEST().
{
   string lines;
   BENCHMARK_SUSPEND {
     string line;
     FOR_EACH_RANGE (i, 0, 512) {
       randomString(&line, arg);
       lines += line;
       lines += '\n';
     }
   }
   STRING line;
   while (iters) {
     std::istringstream is(lines);
     while (iters && getline(is, line)) {
       folly::doNotOptimizeAway(line.size());
       iters--;
     }
   }
 }
void BENCHFUN() initRNG (size_t , size_t)
This file is supposed to be included from within FBStringTest. Do not use otherwise.
override-include-guard
Definition at line 24 of file FBStringTestBenchmarks.cpp.h.
References BENCHFUN, BENCHMARK_PARAM, and seed.
{
   srand(seed);
 }
void BENCHFUN() push_back (size_t iters, size_t arg)
Definition at line 231 of file FBStringTestBenchmarks.cpp.h.
References BENCHFUN, BENCHMARK_PARAM, FOR_EACH_RANGE, i, s, and STRING.
Referenced by folly::threadlocal_detail::ThreadEntryNode::getThreadEntry(), folly::small_vector< Observer< T > *, InlineObservers >::insert(), folly::basic_fbstring< char >::operator+=(), folly::BasicFixedString< Char, N >::operator+=(), TEST(), folly::sync_tests::testAcquireLocked(), and folly::sync_tests::testAcquireLockedWithConst().
{
   FOR_EACH_RANGE (i, 0, iters) {
     STRING s;
     FOR_EACH_RANGE (j, 0, arg) { s += ' '; }
   }
 }
void BENCHFUN() replace (size_t iters, size_t arg)
Definition at line 211 of file FBStringTestBenchmarks.cpp.h.
References BENCHFUN, BENCHMARK_PARAM, BENCHMARK_SUSPEND, folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, random(), randomString(), s, and STRING.
Referenced by folly::basic_fbstring< char >::assign(), testing::internal::edit_distance::CalculateOptimalEdits(), shell_builder.ShellFBCodeBuilder::copy_local_repo(), folly::BasicFixedString< Char, N >::erase(), shell_quoting.ShellQuoted::format(), upload.MercurialVCS::GetBaseFile(), upload.VersionControlSystem::GetBaseFiles(), shell_builder::persistent_temp_dir(), folly::basic_fbstring< char >::replace(), folly::BasicFixedString< Char, N >::replace(), folly::basic_fbstring< E, T, A, Storage >::replaceImplDiscr(), shell_quoting::shell_comment(), shell_quoting::shell_quote(), testing::internal::ShouldRunTestCase(), upload::SplitPatch(), gmock_output_test::ToUnixLineEnding(), and gtest_output_test::ToUnixLineEnding().
{
   STRING s;
   BENCHMARK_SUSPEND {
     randomString(&s, arg);
   }
   FOR_EACH_RANGE (i, 0, iters) {
     BenchmarkSuspender susp;
     doNotOptimizeAway(&s);
     auto const pos = random(0, s.size());
     auto toRemove = random(0, s.size() - pos);
     auto toInsert = random(0, arg);
     STRING s1;
     randomString(&s1, toInsert);
     susp.dismiss();
     s.replace(pos, toRemove, s1);
   }
 }
void BENCHFUN() resize (size_t iters, size_t arg)
Definition at line 115 of file FBStringTestBenchmarks.cpp.h.
References BENCHFUN, BENCHMARK_PARAM, folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, random(), s, and STRING.
Referenced by folly::basic_fbstring< E, T, A, Storage >::assign(), folly::basic_fbstring< char >::clear(), folly::basic_fbstring< char >::erase(), folly::basic_fbstring< E, T, A, Storage >::getlineImpl(), folly::basic_fbstring< char >::max_size(), folly::BasicFixedString< Char, N >::resize(), and folly::basic_fbstring< char >::substr().
{
   STRING s;
   FOR_EACH_RANGE (i, 0, iters) {
     s.resize(random(0, arg));
     doNotOptimizeAway(&s);
   }
 }
void BENCHFUN() short_append (size_t iters, size_t arg)
Definition at line 242 of file FBStringTestBenchmarks.cpp.h.
References BENCHFUN, BENCHMARK_PARAM, FOR_EACH_RANGE, i, s, and STRING.
{
   FOR_EACH_RANGE (i, 0, iters) {
     STRING s;
     FOR_EACH_RANGE (j, 0, arg) { s += "012"; }
   }
 }