proxygen: proxygen/folly/folly/test/FBVectorBenchmarks.cpp.h File Reference
FBVectorBenchmarks.cpp.h File Reference
Functions
BENCHMARK (BENCHFUN(zzInitRNG))
BENCHMARK (BENCHFUN(defaultCtor), iters)
void BENCHFUN() sizeCtor (int iters, int size)
void BENCHFUN() fillCtor (int iters, int size)
void BENCHFUN() reserve (int iters, int size)
void BENCHFUN() insertFront (int iters, int initialSize)
void BENCHFUN() pushBack (int iters, int initialSize)
Function Documentation
BENCHMARK (BENCHFUN(zzInitRNG))
This file is supposed to be included from within FBVectorBenchmark. Do not use otherwise.
Definition at line 22 of file FBVectorBenchmarks.cpp.h.
References seed.
{
   srand(seed);
 }
BENCHMARK (BENCHFUN(defaultCtor) , iters)
Definition at line 26 of file FBVectorBenchmarks.cpp.h.
References folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, v, and VECTOR.
{
   FOR_EACH_RANGE (i, 0, iters) {
     VECTOR v;
     doNotOptimizeAway(&v);
   }
 }
void BENCHFUN() fillCtor (int iters, int size)
Definition at line 43 of file FBVectorBenchmarks.cpp.h.
References BENCHFUN, BENCHMARK_PARAM, folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, v, and VECTOR.
{
   FOR_EACH_RANGE (i, 0, iters) {
     VECTOR v(size_t(size), randomObject<VECTOR::value_type>());
     doNotOptimizeAway(&v);
   }
 }
void BENCHFUN() insertFront (int iters, int initialSize)
Definition at line 66 of file FBVectorBenchmarks.cpp.h.
References BENCHFUN, BENCHMARK_PARAM, FOR_EACH_RANGE, i, v, and VECTOR.
{
   BenchmarkSuspender braces;
   auto const obj = randomObject<VECTOR::value_type>();
   VECTOR v(initialSize, obj);
   braces.dismissing([&]() {
     FOR_EACH_RANGE (i, 0, iters) { v.insert(v.begin(), obj); }
   });
 }
void BENCHFUN() pushBack (int iters, int initialSize)
Definition at line 82 of file FBVectorBenchmarks.cpp.h.
References BENCHFUN, BENCHMARK_PARAM, FOR_EACH_RANGE, i, v, and VECTOR.
{
   BenchmarkSuspender braces;
   auto const obj = randomObject<VECTOR::value_type>();
   VECTOR v(initialSize, obj);
   braces.dismissing([&]() {
     FOR_EACH_RANGE (i, 0, iters) { v.push_back(obj); }
   });
 }
void BENCHFUN() reserve (int iters, int size)
Definition at line 54 of file FBVectorBenchmarks.cpp.h.
References BENCHFUN, BENCHMARK_PARAM, FOR_EACH_RANGE, i, random(), folly::size(), v, and VECTOR.
Referenced by folly::fbstring_core< Char >::expandNoinit(), and folly::basic_fbstring< E, T, A, Storage >::getlineImpl().
{
   auto const obj = randomObject<VECTOR::value_type>();
   FOR_EACH_RANGE (i, 0, iters) {
     VECTOR v(random(0U, 1U), obj);
     v.reserve(size);
   }
 }
void BENCHFUN() sizeCtor (int iters, int size)
Definition at line 33 of file FBVectorBenchmarks.cpp.h.
References BENCHFUN, BENCHMARK_PARAM, folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, folly::size(), v, and VECTOR.
{
   FOR_EACH_RANGE (i, 0, iters) {
     VECTOR v(size);
     doNotOptimizeAway(&v);
   }
 }