proxygen: proxygen/folly/folly/fibers/test/FibersTestApp.cpp File Reference
FibersTestApp.cpp File Reference
#include <iostream>
#include <queue>
#include <folly/Memory.h>
#include <folly/fibers/FiberManager.h>
#include <folly/fibers/SimpleLoopController.h>
Classes
struct Application
Functions
int main ()
Function Documentation
int main (void)
Definition at line 80 of file FibersTestApp.cpp.
References Application::fiberManager, Application::loop(), loop(), folly::fibers::SimpleLoopController::loop(), folly::fibers::FiberManager::loopController(), and folly::gen::move.
            {
   Application app;
   auto loop = [&app]() { app.loop(); };
   auto& loopController =
       dynamic_cast<SimpleLoopController&>(app.fiberManager.loopController());
   loopController.loop(std::move(loop));
   return 0;
 }