proxygen: proxygen/folly/folly/fibers/test/FibersBenchmark.cpp File Reference
FibersBenchmark.cpp File Reference
#include <folly/fibers/FiberManager.h>
#include <folly/fibers/FiberManagerMap.h>
#include <queue>
#include <folly/Benchmark.h>
#include <folly/fibers/SimpleLoopController.h>
#include <folly/init/Init.h>
#include <folly/io/async/EventBase.h>
Functions
void runBenchmark (size_t numAwaits, size_t toSend)
BENCHMARK (FiberManagerBasicOneAwait, iters)
BENCHMARK (FiberManagerBasicFiveAwaits, iters)
BENCHMARK (FiberManagerCreateDestroy, iters)
BENCHMARK (FiberManagerAllocateDeallocatePattern, iters)
BENCHMARK (FiberManagerAllocateLargeChunk, iters)
int main (int argc, char **argv)
Variables
static size_t sNumAwaits
Function Documentation
BENCHMARK (FiberManagerBasicOneAwait , iters)
Definition at line 67 of file FibersBenchmark.cpp.
References runBenchmark().
{
   runBenchmark(1, iters);
 }
BENCHMARK (FiberManagerBasicFiveAwaits , iters)
Definition at line 71 of file FibersBenchmark.cpp.
References runBenchmark().
{
   runBenchmark(5, iters);
 }
BENCHMARK (FiberManagerCreateDestroy , iters)
Definition at line 75 of file FibersBenchmark.cpp.
References folly::fibers::getFiberManager(), i, and folly::EventBase::loop().
{
   for (size_t i = 0; i < iters; ++i) {
     folly::EventBase evb;
     auto& fm = folly::fibers::getFiberManager(evb);
     fm.addTask([]() {});
     evb.loop();
   }
 }
BENCHMARK (FiberManagerAllocateDeallocatePattern , iters)
Definition at line 84 of file FibersBenchmark.cpp.
References folly::fibers::FiberManager::addTask(), folly::fibers::FiberManager::fibersPoolSize(), i, folly::fibers::FiberManager::loopUntilNoReady(), and folly::fibers::FiberManager::Options::maxFibersPoolSize.
{
   static const size_t kNumAllocations = 10000;
   FiberManager::Options opts;
   opts.maxFibersPoolSize = 0;
   FiberManager fiberManager(std::make_unique<SimpleLoopController>(), opts);
   for (size_t iter = 0; iter < iters; ++iter) {
     DCHECK_EQ(0, fiberManager.fibersPoolSize());
     size_t fibersRun = 0;
     for (size_t i = 0; i < kNumAllocations; ++i) {
       fiberManager.addTask([&fibersRun] { ++fibersRun; });
       fiberManager.loopUntilNoReady();
     }
     DCHECK_EQ(10000, fibersRun);
     DCHECK_EQ(0, fiberManager.fibersPoolSize());
   }
 }
BENCHMARK (FiberManagerAllocateLargeChunk , iters)
Definition at line 107 of file FibersBenchmark.cpp.
References folly::fibers::FiberManager::addTask(), folly::fibers::FiberManager::fibersPoolSize(), i, folly::fibers::FiberManager::loopUntilNoReady(), and folly::fibers::FiberManager::Options::maxFibersPoolSize.
{
   static const size_t kNumAllocations = 10000;
   FiberManager::Options opts;
   opts.maxFibersPoolSize = 0;
   FiberManager fiberManager(std::make_unique<SimpleLoopController>(), opts);
   for (size_t iter = 0; iter < iters; ++iter) {
     DCHECK_EQ(0, fiberManager.fibersPoolSize());
     size_t fibersRun = 0;
     for (size_t i = 0; i < kNumAllocations; ++i) {
       fiberManager.addTask([&fibersRun] { ++fibersRun; });
     }
     fiberManager.loopUntilNoReady();
     DCHECK_EQ(10000, fibersRun);
     DCHECK_EQ(0, fiberManager.fibersPoolSize());
   }
 }
int main (int argc, char ** argv)
Definition at line 131 of file FibersBenchmark.cpp.
References folly::init(), and folly::runBenchmarks().
{
   folly::init(&argc, &argv, true);
   folly::runBenchmarks();
   return 0;
 }
void runBenchmark (size_t numAwaits, size_t toSend)
Definition at line 31 of file FibersBenchmark.cpp.
References folly::fibers::FiberManager::addTask(), folly::fibers::await(), i, loop(), folly::fibers::FiberManager::loopController(), folly::gen::move, and sNumAwaits.
Referenced by BENCHMARK().
{
   sNumAwaits = numAwaits;
   FiberManager fiberManager(std::make_unique<SimpleLoopController>());
   auto& loopController =
       dynamic_cast<SimpleLoopController&>(fiberManager.loopController());
   std::queue<Promise<int>> pendingRequests;
   static const size_t maxOutstanding = 5;
   auto loop = [&fiberManager, &loopController, &pendingRequests, &toSend]() {
     if (pendingRequests.size() == maxOutstanding || toSend == 0) {
       if (pendingRequests.empty()) {
         return;
       }
       pendingRequests.front().setValue(0);
       pendingRequests.pop();
     } else {
       fiberManager.addTask([&pendingRequests]() {
         for (size_t i = 0; i < sNumAwaits; ++i) {
           auto result = await([&pendingRequests](Promise<int> promise) {
             pendingRequests.push(std::move(promise));
           });
           DCHECK_EQ(result, 0);
         }
       });
       if (--toSend == 0) {
         loopController.stop();
       }
     }
   };
   loopController.loop(std::move(loop));
 }
Variable Documentation
size_t sNumAwaits static
Definition at line 29 of file FibersBenchmark.cpp.
Referenced by runBenchmark().