proxygen: proxygen/folly/folly/executors/test/FiberIOExecutorTest.cpp File Reference
FiberIOExecutorTest.cpp File Reference
#include <memory>
#include <folly/executors/FiberIOExecutor.h>
#include <folly/executors/IOThreadPoolExecutor.h>
#include <folly/portability/GTest.h>
Functions
TEST_F (FiberIOExecutorTest, event_base)
TEST_F (FiberIOExecutorTest, basic_execution)
Function Documentation
TEST_F (FiberIOExecutorTest , event_base)
Definition at line 29 of file FiberIOExecutorTest.cpp.
References ASSERT_EQ, and ASSERT_NE.
{
   auto tpe = std::make_shared<folly::IOThreadPoolExecutor>(1);
   folly::FiberIOExecutor e(tpe);
   ASSERT_NE(e.getEventBase(), nullptr);
   ASSERT_EQ(e.getEventBase(), tpe->getEventBase());
 }
TEST_F (FiberIOExecutorTest , basic_execution)
Definition at line 37 of file FiberIOExecutorTest.cpp.
References ASSERT_TRUE, folly::EventBaseManager::get(), folly::fibers::EventBaseLoopController::getEventBase(), folly::VirtualEventBase::getEventBase(), folly::EventBaseManager::getEventBase(), folly::fibers::getFiberManager(), folly::fibers::onFiber(), folly::Baton< MayBlock, Atom >::post(), and folly::Baton< MayBlock, Atom >::wait().
{
   auto tpe = std::make_shared<folly::IOThreadPoolExecutor>(1);
   folly::FiberIOExecutor e(tpe);
   // FiberIOExecutor should add tasks using the FiberManager mapped to the
   // IOThreadPoolExecutor's event base.
   folly::Baton<> baton;
   bool inContext = false;
   e.add([&]() {
     inContext = folly::fibers::onFiber();
     auto& lc = dynamic_cast<folly::fibers::EventBaseLoopController&>(
         folly::fibers::getFiberManager(*e.getEventBase()).loopController());
     auto& eb = lc.getEventBase()->getEventBase();
     inContext =
         inContext && &eb == folly::EventBaseManager::get()->getEventBase();
     baton.post();
   });
   baton.wait();
   ASSERT_TRUE(inContext);
 }