proxygen: proxygen/wangle/wangle/util/test/FilePollerTest.cpp File Reference
FilePollerTest.cpp File Reference
#include <chrono>
#include <condition_variable>
#include <mutex>
#include <boost/filesystem.hpp>
#include <folly/portability/GTest.h>
#include <folly/synchronization/Baton.h>
#include <folly/File.h>
#include <folly/FileUtil.h>
#include <folly/experimental/TestUtil.h>
#include <wangle/util/FilePoller.h>
#include <folly/Singleton.h>
Classes
class FilePollerTest
struct UpdateSyncState
class TestFile
class NoDiskPoller
struct PollerWithState
Functions
void updateModifiedTime (const std::string &fileName, bool forward=true)
TEST_F (FilePollerTest, TestUpdateFile)
TEST_F (FilePollerTest, TestUpdateFileBackwards)
TEST_F (FilePollerTest, TestCreateFile)
TEST_F (FilePollerTest, TestDeleteFile)
TEST_F (FilePollerTest, TestTwoUpdatesAndDelete)
TEST_F (FilePollerTest, TestFileCreatedLate)
TEST_F (FilePollerTest, TestMultiplePollers)
TEST (FilePoller, TestFork)
Function Documentation
TEST (FilePoller , TestFork)
Definition at line 233 of file FilePollerTest.cpp.
References ASSERT_NO_FATAL_FAILURE, folly::SingletonVault::destroyInstances(), folly::SingletonVault::singleton(), TestFile::update(), and PollerWithState::waitForUpdate().
{
   TestFile testFile(true, 1);
   PollerWithState p1(testFile);
   testFile.update(true, 2);
   ASSERT_NO_FATAL_FAILURE(p1.waitForUpdate());
   // nuke singleton
   folly::SingletonVault::singleton()->destroyInstances();
   testFile.update(true, 3);
   ASSERT_NO_FATAL_FAILURE(p1.waitForUpdate());
 }
TEST_F (FilePollerTest , TestUpdateFile)
Definition at line 58 of file FilePollerTest.cpp.
References wangle::FilePoller::addFileToTrack(), ASSERT_TRUE, folly::Baton< MayBlock, Atom >::post(), folly::Baton< MayBlock, Atom >::try_wait_for(), and updateModifiedTime().
{
   createFile();
   Baton<> baton;
   bool updated = false;
   FilePoller poller(std::chrono::milliseconds(1));
   poller.addFileToTrack(tmpFile, [&]() {
     updated = true;
     baton.post();
   });
   updateModifiedTime(tmpFile);
   ASSERT_TRUE(baton.try_wait_for(std::chrono::seconds(5)));
   ASSERT_TRUE(updated);
 }
TEST_F (FilePollerTest , TestUpdateFileBackwards)
Definition at line 72 of file FilePollerTest.cpp.
References wangle::FilePoller::addFileToTrack(), ASSERT_TRUE, folly::Baton< MayBlock, Atom >::post(), folly::Baton< MayBlock, Atom >::try_wait_for(), and updateModifiedTime().
{
   createFile();
   Baton<> baton;
   bool updated = false;
   FilePoller poller(std::chrono::milliseconds(1));
   poller.addFileToTrack(tmpFile, [&]() {
     updated = true;
     baton.post();
   });
   updateModifiedTime(tmpFile, false);
   ASSERT_TRUE(baton.try_wait_for(std::chrono::seconds(5)));
   ASSERT_TRUE(updated);
 }
TEST_F (FilePollerTest , TestCreateFile)
Definition at line 86 of file FilePollerTest.cpp.
References wangle::FilePoller::addFileToTrack(), ASSERT_TRUE, folly::Baton< MayBlock, Atom >::post(), and folly::Baton< MayBlock, Atom >::try_wait_for().
{
   Baton<> baton;
   bool updated = false;
   createFile();
   remove(tmpFile.c_str());
   FilePoller poller(std::chrono::milliseconds(1));
   poller.addFileToTrack(tmpFile, [&]() {
     updated = true;
     baton.post();
   });
   File(creat(tmpFile.c_str(), O_RDONLY));
   ASSERT_TRUE(baton.try_wait_for(std::chrono::seconds(5)));
   ASSERT_TRUE(updated);
 }
TEST_F (FilePollerTest , TestDeleteFile)
Definition at line 101 of file FilePollerTest.cpp.
References wangle::FilePoller::addFileToTrack(), ASSERT_FALSE, folly::Baton< MayBlock, Atom >::post(), and folly::Baton< MayBlock, Atom >::try_wait_for().
{
   Baton<> baton;
   bool updated = false;
   createFile();
   FilePoller poller(std::chrono::milliseconds(1));
   poller.addFileToTrack(tmpFile, [&]() {
     updated = true;
     baton.post();
   });
   remove(tmpFile.c_str());
   ASSERT_FALSE(baton.try_wait_for(std::chrono::seconds(1)));
   ASSERT_FALSE(updated);
 }
TEST_F (FilePollerTest , TestTwoUpdatesAndDelete)
Definition at line 189 of file FilePollerTest.cpp.
References ASSERT_NO_FATAL_FAILURE, TestFile::update(), and PollerWithState::waitForUpdate().
{
   TestFile testFile(true, 1);
   PollerWithState poller(testFile);
   testFile.update(true, 2);
   ASSERT_NO_FATAL_FAILURE(poller.waitForUpdate());
   testFile.update(true, 3);
   ASSERT_NO_FATAL_FAILURE(poller.waitForUpdate());
   testFile.update(false, 0);
   ASSERT_NO_FATAL_FAILURE(poller.waitForUpdate(false));
 }
TEST_F (FilePollerTest , TestFileCreatedLate)
Definition at line 203 of file FilePollerTest.cpp.
References ASSERT_NO_FATAL_FAILURE, TestFile::update(), and PollerWithState::waitForUpdate().
{
   TestFile testFile(false, 0); // not created yet
   PollerWithState poller(testFile);
   ASSERT_NO_FATAL_FAILURE(poller.waitForUpdate(false));
   testFile.update(true, 1);
   ASSERT_NO_FATAL_FAILURE(poller.waitForUpdate());
 }
TEST_F (FilePollerTest , TestMultiplePollers)
Definition at line 212 of file FilePollerTest.cpp.
References ASSERT_NO_FATAL_FAILURE, PollerWithState::poller, TestFile::update(), and PollerWithState::waitForUpdate().
{
   TestFile testFile(true, 1);
   PollerWithState p1(testFile);
   PollerWithState p2(testFile);
   testFile.update(true, 2);
   ASSERT_NO_FATAL_FAILURE(p1.waitForUpdate());
   ASSERT_NO_FATAL_FAILURE(p2.waitForUpdate());
   testFile.update(true, 1);
   ASSERT_NO_FATAL_FAILURE(p1.waitForUpdate());
   ASSERT_NO_FATAL_FAILURE(p2.waitForUpdate());
   // clear one of the pollers and make sure the other is still
   // getting them
   p2.poller.reset();
   testFile.update(true, 3);
   ASSERT_NO_FATAL_FAILURE(p1.waitForUpdate());
   ASSERT_NO_FATAL_FAILURE(p2.waitForUpdate(false));
 }
void updateModifiedTime (const std::string & fileName, bool forward = true)
Definition at line 43 of file FilePollerTest.cpp.
References diff().
Referenced by TEST_F().
{
   auto previous = std::chrono::system_clock::from_time_t(
       boost::filesystem::last_write_time(fileName));
   auto diff = std::chrono::seconds(10);
   std::chrono::system_clock::time_point newTime;
   if (forward) {
     newTime = previous + diff;
   } else {
     newTime = previous - diff;
   }
   time_t newTimet = std::chrono::system_clock::to_time_t(newTime);
   boost::filesystem::last_write_time(fileName, newTimet);
 }