proxygen: proxygen/folly/folly/gen/test/FileBenchmark.cpp File Reference
FileBenchmark.cpp File Reference
#include <thread>
#include <glog/logging.h>
#include <folly/Benchmark.h>
#include <folly/File.h>
#include <folly/gen/Base.h>
#include <folly/gen/File.h>
Functions
BENCHMARK (ByLine_Pipes, iters)
int main (int argc, char *argv[])
Function Documentation
BENCHMARK (ByLine_Pipes , iters)
Definition at line 28 of file FileBenchmark.cpp.
References BENCHMARK_SUSPEND, folly::gen::byLine(), folly::netops::close(), folly::doNotOptimizeAway(), f, FILE, i, int64_t, pipe(), fizz::detail::read(), s, folly::gen::sum, and fizz::detail::write().
{
   std::thread thread;
   int rfd = -1;
   int wfd;
   BENCHMARK_SUSPEND {
     int p[2];
     CHECK_ERR(::pipe(p));
     rfd = p[0];
     wfd = p[1];
     thread = std::thread([wfd, iters] {
       char x = 'x';
       PCHECK(::write(wfd, &x, 1) == 1); // signal startup
       FILE* f = fdopen(wfd, "w");
       PCHECK(f);
       for (size_t i = 1; i <= iters; ++i) {
         fprintf(f, "%zu\n", i);
       }
       fclose(f);
     });
     char buf;
     PCHECK(::read(rfd, &buf, 1) == 1); // wait for startup
   }
   CHECK_ERR(rfd);
   auto s = byLine(folly::File(rfd)) | eachTo<int64_t>() | sum;
   folly::doNotOptimizeAway(s);
   BENCHMARK_SUSPEND {
     ::close(rfd);
     CHECK_EQ(s, int64_t(iters) * (iters + 1) / 2);
     thread.join();
   }
 }
int main (int argc, char * argv[])
Definition at line 69 of file FileBenchmark.cpp.
References folly::runBenchmarks().
{
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   folly::runBenchmarks();
   return 0;
 }