proxygen: proxygen/wangle/wangle/example/file/FileServer.cpp File Reference
FileServer.cpp File Reference
#include <gflags/gflags.h>
#include <folly/init/Init.h>
#include <wangle/bootstrap/ServerBootstrap.h>
#include <wangle/channel/AsyncSocketHandler.h>
#include <wangle/channel/FileRegion.h>
#include <wangle/codec/LineBasedFrameDecoder.h>
#include <wangle/codec/StringCodec.h>
Classes
class FileServerHandler
class FileServerPipelineFactory
Typedefs
typedef Pipeline< IOBufQueue &, std::string > FileServerPipeline
Functions
DEFINE_int32 (port, 11219,"test file server port")
int main (int argc, char **argv)
Typedef Documentation
typedef Pipeline<IOBufQueue&, std::string> FileServerPipeline
Definition at line 31 of file FileServer.cpp.
Function Documentation
DEFINE_int32 (port , 11219 , "test file server port")
int main (int argc, char ** argv)
Definition at line 95 of file FileServer.cpp.
References wangle::ServerBootstrap< Pipeline >::bind(), wangle::ServerBootstrap< Pipeline >::childPipeline(), folly::init(), and wangle::ServerBootstrap< Pipeline >::waitForStop().
{
   folly::Init init(&argc, &argv);
   ServerBootstrap<FileServerPipeline> server;
   server.childPipeline(std::make_shared<FileServerPipelineFactory>());
   server.bind(FLAGS_port);
   server.waitForStop();
   return 0;
 }