proxygen: proxygen/folly/folly/futures/test/FilterTest.cpp File Reference
FilterTest.cpp File Reference
#include <folly/futures/Future.h>
#include <folly/portability/GTest.h>
Functions
TEST (Filter, alwaysTrye)
TEST (Filter, alwaysFalse)
TEST (Filter, moveOnlyValue)
Function Documentation
TEST (Filter , alwaysTrye)
Definition at line 22 of file FilterTest.cpp.
References EXPECT_EQ, folly::pushmi::operators::filter, and folly::makeFuture().
{
   EXPECT_EQ(42, makeFuture(42).filter([](int) { return true; }).get());
 }
TEST (Filter , alwaysFalse)
Definition at line 26 of file FilterTest.cpp.
References EXPECT_THROW, folly::pushmi::operators::filter, and folly::makeFuture().
{
   EXPECT_THROW(
       makeFuture(42).filter([](int) { return false; }).get(),
       folly::FuturePredicateDoesNotObtain);
 }
TEST (Filter , moveOnlyValue)
Definition at line 32 of file FilterTest.cpp.
References EXPECT_EQ, folly::pushmi::operators::filter, and folly::makeFuture().
{
   EXPECT_EQ(
       42,
       *makeFuture(std::make_unique<int>(42))
            .filter([](std::unique_ptr<int> const&) { return true; })
            .get());
 }