proxygen: proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest-listener_test.cc File Reference
gtest-listener_test.cc File Reference
#include "gtest/gtest.h"
#include <vector>
Classes
class testing::internal::EventRecordingListener
class testing::internal::EnvironmentInvocationCatcher
class testing::internal::ListenerTest
Namespaces
testing
testing::internal
Functions
testing::internal::TEST_F (ListenerTest, DoesFoo)
testing::internal::TEST_F (ListenerTest, DoesBar)
void VerifyResults (const std::vector< std::string > &data, const char *const *expected_data, size_t expected_data_size)
int main (int argc, char **argv)
Variables
std::vector< std::string > * g_events = NULL
Function Documentation
int main (int argc, char ** argv)
Definition at line 201 of file gtest-listener_test.cc.
References testing::AddGlobalTestEnvironment(), testing::TestEventListeners::Append(), testing::internal::EventRecordingListener::EventRecordingListener(), testing::UnitTest::GetInstance(), GTEST_CHECK_, GTEST_FLAG, testing::InitGoogleTest(), testing::UnitTest::listeners(), repeat(), RUN_ALL_TESTS(), and VerifyResults().
{
   std::vector<std::string> events;
   g_events = &events;
   InitGoogleTest(&argc, argv);
   UnitTest::GetInstance()->listeners().Append(
       new EventRecordingListener("1st"));
   UnitTest::GetInstance()->listeners().Append(
       new EventRecordingListener("2nd"));
   AddGlobalTestEnvironment(new EnvironmentInvocationCatcher);
   GTEST_CHECK_(events.size() == 0)
       << "AddGlobalTestEnvironment should not generate any events itself.";
   ::testing::GTEST_FLAG(repeat) = 2;
   int ret_val = RUN_ALL_TESTS();
   const char* const expected_events[] = {
     "1st.OnTestProgramStart",
     "2nd.OnTestProgramStart",
     "1st.OnTestIterationStart(0)",
     "2nd.OnTestIterationStart(0)",
     "1st.OnEnvironmentsSetUpStart",
     "2nd.OnEnvironmentsSetUpStart",
     "Environment::SetUp",
     "2nd.OnEnvironmentsSetUpEnd",
     "1st.OnEnvironmentsSetUpEnd",
     "1st.OnTestCaseStart",
     "2nd.OnTestCaseStart",
     "ListenerTest::SetUpTestCase",
     "1st.OnTestStart",
     "2nd.OnTestStart",
     "ListenerTest::SetUp",
     "ListenerTest::* Test Body",
     "1st.OnTestPartResult",
     "2nd.OnTestPartResult",
     "ListenerTest::TearDown",
     "2nd.OnTestEnd",
     "1st.OnTestEnd",
     "1st.OnTestStart",
     "2nd.OnTestStart",
     "ListenerTest::SetUp",
     "ListenerTest::* Test Body",
     "1st.OnTestPartResult",
     "2nd.OnTestPartResult",
     "ListenerTest::TearDown",
     "2nd.OnTestEnd",
     "1st.OnTestEnd",
     "ListenerTest::TearDownTestCase",
     "2nd.OnTestCaseEnd",
     "1st.OnTestCaseEnd",
     "1st.OnEnvironmentsTearDownStart",
     "2nd.OnEnvironmentsTearDownStart",
     "Environment::TearDown",
     "2nd.OnEnvironmentsTearDownEnd",
     "1st.OnEnvironmentsTearDownEnd",
     "2nd.OnTestIterationEnd(0)",
     "1st.OnTestIterationEnd(0)",
     "1st.OnTestIterationStart(1)",
     "2nd.OnTestIterationStart(1)",
     "1st.OnEnvironmentsSetUpStart",
     "2nd.OnEnvironmentsSetUpStart",
     "Environment::SetUp",
     "2nd.OnEnvironmentsSetUpEnd",
     "1st.OnEnvironmentsSetUpEnd",
     "1st.OnTestCaseStart",
     "2nd.OnTestCaseStart",
     "ListenerTest::SetUpTestCase",
     "1st.OnTestStart",
     "2nd.OnTestStart",
     "ListenerTest::SetUp",
     "ListenerTest::* Test Body",
     "1st.OnTestPartResult",
     "2nd.OnTestPartResult",
     "ListenerTest::TearDown",
     "2nd.OnTestEnd",
     "1st.OnTestEnd",
     "1st.OnTestStart",
     "2nd.OnTestStart",
     "ListenerTest::SetUp",
     "ListenerTest::* Test Body",
     "1st.OnTestPartResult",
     "2nd.OnTestPartResult",
     "ListenerTest::TearDown",
     "2nd.OnTestEnd",
     "1st.OnTestEnd",
     "ListenerTest::TearDownTestCase",
     "2nd.OnTestCaseEnd",
     "1st.OnTestCaseEnd",
     "1st.OnEnvironmentsTearDownStart",
     "2nd.OnEnvironmentsTearDownStart",
     "Environment::TearDown",
     "2nd.OnEnvironmentsTearDownEnd",
     "1st.OnEnvironmentsTearDownEnd",
     "2nd.OnTestIterationEnd(1)",
     "1st.OnTestIterationEnd(1)",
     "2nd.OnTestProgramEnd",
     "1st.OnTestProgramEnd"
   };
   VerifyResults(events,
                 expected_events,
                 sizeof(expected_events)/sizeof(expected_events[0]));
   // We need to check manually for ad hoc test failures that happen after
   // RUN_ALL_TESTS finishes.
   if (UnitTest::GetInstance()->Failed())
     ret_val = 1;
   return ret_val;
 }
void VerifyResults (const std::vector< std::string > & data, const char *const * expected_data, size_t expected_data_size)
Definition at line 177 of file gtest-listener_test.cc.
References ASSERT_STREQ, EXPECT_EQ, and i.
Referenced by main().
{
   const size_t actual_size = data.size();
   // If the following assertion fails, a new entry will be appended to
   // data.  Hence we save data.size() first.
   EXPECT_EQ(expected_data_size, actual_size);
   // Compares the common prefix.
   const size_t shorter_size = expected_data_size <= actual_size ?
       expected_data_size : actual_size;
   size_t i = 0;
   for (; i < shorter_size; ++i) {
     ASSERT_STREQ(expected_data[i], data[i].c_str())
         << "at position " << i;
   }
   // Prints extra elements in the actual data.
   for (; i < actual_size; ++i) {
     printf("  Actual event #%lu: %s\n",
         static_cast<unsigned long>(i), data[i].c_str());
   }
 }
Variable Documentation
std::vector<std::string>* g_events = NULL
Definition at line 50 of file gtest-listener_test.cc.