proxygen: proxygen/fizz/build_/gtest/src/gtest/googletest/CMakeLists.txt File Reference
proxygen/fizz/build_/gtest/src/gtest/googletest/CMakeLists.txt File Reference
Functions
option (BUILD_SHARED_LIBS"Build shared libraries (DLLs)."OFF) option(gtest_force_shared_crt"Use shared (DLL) run-time lib even when Google Test is built as static lib."OFF) option(gtest_build_tests"Build all of gtest's own tests."OFF) option(gtest_build_samples"Build gtest's sample programs."OFF) option(gtest_disable_pthreads"Disable uses of pthreads in gtest."OFF) option(gtest_hide_internal_symbols"Build gtest with internal symbols hidden in shared libraries."OFF) include(cmake/hermetic_build.cmake OPTIONAL) if(COMMAND pre_project_set_up_hermetic_build) pre_project_set_up_hermetic_build() endif() project(gtest CXX C) cmake_minimum_required(VERSION 2.6.2) if(COMMAND set_up_hermetic_build) set_up_hermetic_build() endif() if(gtest_hide_internal_symbols) set(CMAKE_CXX_VISIBILITY_PRESET hidden) set(CMAKE_VISIBILITY_INLINES_HIDDEN 1) endif() include(cmake/internal_utils.cmake) config_compiler_and_linker() include_directories($
Function Documentation
option (BUILD_SHARED_LIBS"Build shared libraries (DLLs)." OFF)
Definition at line 10 of file CMakeLists.txt.
References folly::gen::all(), D, flag, fuse_gmock_files::gtest, if(), lib, folly::pushmi::operators::on, option(), s, folly::to(), and folly::when().
       {gtest_SOURCE_DIR} and to the root binary directory as
 # ${gtest_BINARY_DIR}.
 # Language "C" is required for find_package(Threads).
 project(gtest CXX C)
 cmake_minimum_required(VERSION 2.6.2)
 if (COMMAND set_up_hermetic_build)
   set_up_hermetic_build()
 endif()
 if (gtest_hide_internal_symbols)
   set(CMAKE_CXX_VISIBILITY_PRESET hidden)
   set(CMAKE_VISIBILITY_INLINES_HIDDEN 1)
 endif()
 # Define helper functions and macros used by Google Test.
 include(cmake/internal_utils.cmake)
 config_compiler_and_linker()  # Defined in internal_utils.cmake.
 # Where Google Test's .h files can be found.
 include_directories(
   ${gtest_SOURCE_DIR}/include