proxygen: proxygen/fizz/build_/gtest/src/gtest/googletest/xcode/Samples/FrameworkSample/widget_test.cc File Reference
widget_test.cc File Reference
#include <string>
#include "gtest/gtest.h"
#include <Widget/widget.h>
Functions
TEST (WidgetInitializerTest, TestConstructor)
TEST (WidgetInitializerTest, TestConversion)
Function Documentation
TEST (WidgetInitializerTest , TestConstructor)
Definition at line 45 of file widget_test.cc.
References EXPECT_EQ, EXPECT_FLOAT_EQ, f, Widget::GetFloatValue(), Widget::GetStringValue(), and string.
{
   Widget widget(1.0f, "name");
   EXPECT_FLOAT_EQ(1.0f, widget.GetFloatValue());
   EXPECT_EQ(std::string("name"), widget.GetStringValue());
 }
TEST (WidgetInitializerTest , TestConversion)
Definition at line 53 of file widget_test.cc.
References buffer(), EXPECT_EQ, EXPECT_STREQ, f, Widget::GetCharPtrValue(), and Widget::GetIntValue().
{
   Widget widget(1.0f, "name");
   EXPECT_EQ(1, widget.GetIntValue());
   size_t max_size = 128;
   char buffer[max_size];
   widget.GetCharPtrValue(buffer, max_size);
   EXPECT_STREQ("name", buffer);
 }