proxygen: proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest_premature_exit_test.cc File Reference
gtest_premature_exit_test.cc File Reference
#include <stdio.h>
#include "gtest/gtest.h"
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 110 of file gtest_premature_exit_test.cc.
References testing::internal::posix::GetEnv(), testing::InitGoogleTest(), and RUN_ALL_TESTS().
{
   InitGoogleTest(&argc, argv);
   const int exit_code = RUN_ALL_TESTS();
   // Test that the premature-exit file is deleted upon return from
   // RUN_ALL_TESTS().
   const char* const filepath = GetEnv("TEST_PREMATURE_EXIT_FILE");
   if (filepath != NULL && *filepath != '\0') {
     if (PrematureExitTest::FileExists(filepath)) {
       printf(
           "File %s shouldn't exist after the test program finishes, but does.",
           filepath);
       return 1;
     }
   }
   return exit_code;
 }