proxygen: proxygen/fizz/fizz/tool/Main.cpp File Reference
Main.cpp File Reference
#include <fizz/tool/Commands.h>
#include <folly/ssl/Init.h>
#include <glog/logging.h>
#include <iostream>
#include <string>
#include <vector>
Functions
void showUsage ()
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 27 of file Main.cpp.
References fizz::tool::fizzUtilities, i, folly::ssl::init(), and showUsage().
{
   google::InitGoogleLogging(argv[0]);
   FLAGS_logtostderr = 1;
   folly::ssl::init();
   std::vector<std::string> arguments;
   for (int i = 0; i < argc; i++) {
     arguments.push_back(argv[i]);
   }
   if (arguments.size() < 2) {
     showUsage();
     return 1;
   } else {
     if (fizzUtilities.count(arguments[1])) {
       return fizzUtilities.at(arguments[1])(arguments);
     } else {
       std::cerr << "Unknown command '" << arguments[1] << "'." << std::endl;
       showUsage();
       return 1;
     }
   }
   return 0;
 }
void showUsage ()
Definition at line 19 of file Main.cpp.
References fizz::tool::fizzUtilities.
Referenced by main().
                  {
   std::cerr << "Supported commands:" << std::endl;
   for (const auto& command : fizzUtilities) {
     std::cerr << "  - " << command.first << std::endl;
   }
   std::cerr << std::endl;
 }