proxygen: proxygen/folly/CMakeLists.txt File Reference
proxygen/folly/CMakeLists.txt File Reference
Functions
cmake_minimum_required (VERSION 3.0.2 FATAL_ERROR) if(POLICY CMP0054) cmake_policy(SET CMP0054 NEW) endif() if(POLICY CMP0057) cmake_policy(SET CMP0057 NEW) endif() set(CMAKE_MODULE_PATH"$
Function Documentation
cmake_minimum_required (VERSION 3.0.2 FATAL_ERROR)
Definition at line 1 of file CMakeLists.txt.
References a, add, add_library(), folly::gen::all(), folly::async(), C, config, FILE, FOLLY_HAVE_PTHREAD, FOLLY_SUPPORT_SHARED_LIBRARY, folly::pushmi::operators::from, generator, proxygen::spdy::HEADERS, lib, bm::list, main(), message, folly::gen::move, folly::pushmi::operators::on, option(), PACKAGE_BUGREPORT, PACKAGE_NAME, PACKAGE_STRING, PACKAGE_TARNAME, PACKAGE_VERSION, s, so, STRING, gmock_test_utils::Subprocess, system, TEST, folly::detail::distributed_mutex::time(), and folly::to().
                         {CMAKE_CURRENT_SOURCE_DIR}/CMake" ${CMAKE_MODULE_PATH})