proxygen: proxygen/folly/folly/experimental/exception_tracer/CMakeLists.txt File Reference
proxygen/folly/folly/experimental/exception_tracer/CMakeLists.txt File Reference
Functions
if (FOLLY_USE_SYMBOLIZER) add_library(folly_exception_tracer_base ExceptionTracer.cpp StackTrace.cpp) apply_folly_compile_options_to_target(folly_exception_tracer_base) target_link_libraries(folly_exception_tracer_base PUBLIC folly) add_library(folly_exception_tracer ExceptionStackTraceLib.cpp ExceptionTracerLib.cpp) apply_folly_compile_options_to_target(folly_exception_tracer) target_link_libraries(folly_exception_tracer PUBLIC folly_exception_tracer_base) add_library(folly_exception_counter ExceptionCounterLib.cpp) apply_folly_compile_options_to_target(folly_exception_counter) target_link_libraries(folly_exception_counter PUBLIC folly_exception_tracer) install(FILES ExceptionAbi.h ExceptionCounterLib.h ExceptionTracer.h ExceptionTracerLib.h StackTrace.h DESTINATION $
Function Documentation
if (FOLLY_USE_SYMBOLIZER)
Definition at line 1 of file CMakeLists.txt.
Referenced by folly::gen::detail::Zip< Container >::Generator< Value1, Source, Value2, Result >::apply(), proxygen::GzipHeaderCodec::decode(), option(), TEST(), and folly::pushmi::operators::flow_from_up< Producer >::value().
        {INCLUDE_INSTALL_DIR}/folly/experimental/exception_tracer