proxygen: proxygen/folly/folly/test/FormatTest.cpp File Reference
FormatTest.cpp File Reference
#include <folly/Format.h>
#include <folly/Utility.h>
#include <folly/portability/GTest.h>
#include <string>
Classes
class folly::FormatValue< KeyValue >
class TestExtendingFormatter< containerMode, Args >
class TestExtendingFormatter< containerMode, Args >
class folly::FormatValue< NoncopyableInt >
Namespaces
folly
—— Concurrent Priority Queue Implementation ——
Macros
#define EXPECT_THROW_STR(code, type, str)
#define EXPECT_FORMAT_ERROR(code, str) EXPECT_THROW_STR(code, folly::BadFormatArg, (str))
Functions
template<class Uint >
void compareOctal (Uint u)
template<class Uint >
void compareHex (Uint u)
template<class Uint >
void compareBinary (Uint u)
TEST (Format, uintToOctal)
TEST (Format, uintToHex)
TEST (Format, uintToBinary)
TEST (Format, Simple)
TEST (Format, Float)
TEST (Format, MultiLevel)
TEST (Format, separatorDecimalInteger)
TEST (Format, separatorNumber)
static void testGrouping (const char *a_str, const char *expected)
TEST (Format, separatorUnit)
TEST (Format, Custom)
TEST (Format, Unformatted)
TEST (Format, Nested)
TEST (Format, OutOfBounds)
TEST (Format, BogusFormatString)
template<class... Args>
std::string texsformat (StringPiece fmt, Args &&...args)
TEST (Format, Extending)
TEST (Format, Temporary)
TEST (Format, NoncopyableArg)
Macro Definition Documentation
#define EXPECT_FORMAT_ERROR (code, str) EXPECT_THROW_STR(code, folly::BadFormatArg, (str))
Definition at line 408 of file FormatTest.cpp.
Referenced by TEST().
#define EXPECT_THROW_STR (code, type, str)
Value:
do {                                                                    \
    bool caught = false;                                                  \
    try {                                                                 \
      code;                                                               \
    } catch (const type& e) {                                             \
      caught = true;                                                      \
      EXPECT_TRUE(strstr(e.what(), (str)) != nullptr)                     \
          << "Expected message [" << (str) << "], actual message ["       \
          << e.what();                                                    \
    } catch (const std::exception& e) {                                   \
      caught = true;                                                      \
      ADD_FAILURE() << "Caught different exception type; expected " #type \
                       ", caught "                                        \
                    << folly::demangle(typeid(e));                        \
    } catch (...) {                                                       \
      caught = true;                                                      \
      ADD_FAILURE() << "Caught unknown exception type; expected " #type;  \
    }                                                                     \
    if (!caught) {                                                        \
      ADD_FAILURE() << "Expected exception " #type ", caught nothing";    \
    }                                                                     \
  } while (false)
Definition at line 384 of file FormatTest.cpp.
Referenced by TEST().
Function Documentation
template<class Uint > void compareBinary (Uint u)
Definition at line 54 of file FormatTest.cpp.
References EXPECT_EQ, folly::detail::kMaxBinaryLength, string, and folly::detail::uintToBinary().
Referenced by TEST().
{
   char buf[detail::kMaxBinaryLength + 1];
   buf[detail::kMaxBinaryLength] = '\0';
   char* p = buf + detail::uintToBinary(buf, detail::kMaxBinaryLength, u);
   std::string repr;
   if (u == 0) {
     repr = '0';
   } else {
     std::string tmp;
     for (; u; u >>= 1) {
       tmp.push_back(u & 1 ? '1' : '0');
     }
     repr.assign(tmp.rbegin(), tmp.rend());
   }
   EXPECT_EQ(repr, std::string(p));
 }
template<class Uint > void compareHex (Uint u)
Definition at line 40 of file FormatTest.cpp.
References EXPECT_EQ, EXPECT_LT, folly::detail::kMaxHexLength, string, and folly::detail::uintToHexLower().
Referenced by TEST().
{
   char buf1[detail::kMaxHexLength + 1];
   buf1[detail::kMaxHexLength] = '\0';
   char* p = buf1 + detail::uintToHexLower(buf1, detail::kMaxHexLength, u);
   char buf2[detail::kMaxHexLength + 1];
   EXPECT_LT(
       snprintf(buf2, sizeof(buf2), "%jx", static_cast<uintmax_t>(u)),
       sizeof(buf2));
   EXPECT_EQ(std::string(buf2), std::string(p));
 }
template<class Uint > void compareOctal (Uint u)
Definition at line 26 of file FormatTest.cpp.
References EXPECT_EQ, EXPECT_LT, folly::detail::kMaxOctalLength, string, and folly::detail::uintToOctal().
Referenced by TEST().
{
   char buf1[detail::kMaxOctalLength + 1];
   buf1[detail::kMaxOctalLength] = '\0';
   char* p = buf1 + detail::uintToOctal(buf1, detail::kMaxOctalLength, u);
   char buf2[detail::kMaxOctalLength + 1];
   EXPECT_LT(
       snprintf(buf2, sizeof(buf2), "%jo", static_cast<uintmax_t>(u)),
       sizeof(buf2));
   EXPECT_EQ(std::string(buf2), std::string(p));
 }
TEST (Format , uintToOctal)
Definition at line 73 of file FormatTest.cpp.
References compareOctal(), and i.
{
   for (unsigned i = 0; i < (1u << 16) + 2; i++) {
     compareOctal(i);
   }
 }
TEST (Format , uintToHex)
Definition at line 79 of file FormatTest.cpp.
References compareHex(), and i.
{
   for (unsigned i = 0; i < (1u << 16) + 2; i++) {
     compareHex(i);
   }
 }
TEST (Format , uintToBinary)
Definition at line 85 of file FormatTest.cpp.
References compareBinary(), and i.
{
   for (unsigned i = 0; i < (1u << 16) + 2; i++) {
     compareBinary(i);
   }
 }
TEST (Format , Simple)
Definition at line 91 of file FormatTest.cpp.
References folly::defaulted(), EXPECT_EQ, EXPECT_FALSE, EXPECT_NE, EXPECT_STREQ, EXPECT_THROW, folly::format(), folly::FormatKeyNotFoundException::key(), m, s, folly::sformat(), string, folly::svformat(), and folly::pushmi::detail::t.
                      {
   EXPECT_EQ("hello", sformat("hello"));
   EXPECT_EQ("42", sformat("{}", 42));
   EXPECT_EQ("42 42", sformat("{0} {0}", 42));
   EXPECT_EQ("00042  23   42", sformat("{0:05} {1:3} {0:4}", 42, 23));
   EXPECT_EQ(
       "hello world hello 42", sformat("{0} {1} {0} {2}", "hello", "world", 42));
   EXPECT_EQ("XXhelloXX", sformat("{:X^9}", "hello"));
   EXPECT_EQ("XXX42XXXX", sformat("{:X^9}", 42));
   EXPECT_EQ("-0xYYYY2a", sformat("{:Y=#9x}", -42));
   EXPECT_EQ("*", sformat("{}", '*'));
   EXPECT_EQ("42", sformat("{}", 42));
   EXPECT_EQ("0042", sformat("{:04}", 42));
   EXPECT_EQ("hello  ", sformat("{:7}", "hello"));
   EXPECT_EQ("hello  ", sformat("{:<7}", "hello"));
   EXPECT_EQ("  hello", sformat("{:>7}", "hello"));
   EXPECT_EQ("  hi", sformat("{:>*}", 4, "hi"));
   EXPECT_EQ("   hi!", sformat("{:*}{}", 3, "", "hi!"));
   EXPECT_EQ("    123", sformat("{:*}", 7, 123));
   EXPECT_EQ("123    ", sformat("{:<*}", 7, 123));
   EXPECT_EQ("----<=>----", sformat("{:-^*}", 11, "<=>"));
   EXPECT_EQ("+++456+++", sformat("{2:+^*0}", 9, "unused", 456));
   std::vector<int> v1{10, 20, 30};
   EXPECT_EQ("0020", sformat("{0[1]:04}", v1));
   EXPECT_EQ("0020", svformat("{1:04}", v1));
   EXPECT_EQ("10 20", svformat("{} {}", v1));
   const std::vector<int> v2 = v1;
   EXPECT_EQ("0020", sformat("{0[1]:04}", v2));
   EXPECT_EQ("0020", svformat("{1:04}", v2));
   EXPECT_THROW(sformat("{0[3]:04}", v2), std::out_of_range);
   EXPECT_THROW(svformat("{3:04}", v2), std::out_of_range);
   EXPECT_EQ("0020", sformat("{0[1]:04}", defaulted(v2, 42)));
   EXPECT_EQ("0020", svformat("{1:04}", defaulted(v2, 42)));
   EXPECT_EQ("0042", sformat("{0[3]:04}", defaulted(v2, 42)));
   EXPECT_EQ("0042", svformat("{3:04}", defaulted(v2, 42)));
   {
     const int p[] = {10, 20, 30};
     const int* q = p;
     EXPECT_EQ("0020", sformat("{0[1]:04}", p));
     EXPECT_EQ("0020", svformat("{1:04}", p));
     EXPECT_EQ("0020", sformat("{0[1]:04}", q));
     EXPECT_EQ("0020", svformat("{1:04}", q));
     EXPECT_NE("", sformat("{}", q));
     EXPECT_EQ("0x", sformat("{}", p).substr(0, 2));
     EXPECT_EQ("10", svformat("{}", p));
     EXPECT_EQ("0x", sformat("{}", q).substr(0, 2));
     EXPECT_EQ("10", svformat("{}", q));
     q = nullptr;
     EXPECT_EQ("(null)", sformat("{}", q));
   }
   std::map<int, std::string> m{{10, "hello"}, {20, "world"}};
   EXPECT_EQ("worldXX", sformat("{[20]:X<7}", m));
   EXPECT_EQ("worldXX", svformat("{20:X<7}", m));
   EXPECT_THROW(sformat("{[42]:X<7}", m), std::out_of_range);
   EXPECT_THROW(svformat("{42:X<7}", m), std::out_of_range);
   EXPECT_EQ("worldXX", sformat("{[20]:X<7}", defaulted(m, "meow")));
   EXPECT_EQ("worldXX", svformat("{20:X<7}", defaulted(m, "meow")));
   EXPECT_EQ("meowXXX", sformat("{[42]:X<7}", defaulted(m, "meow")));
   EXPECT_EQ("meowXXX", svformat("{42:X<7}", defaulted(m, "meow")));
   std::map<std::string, std::string> m2{{"hello", "world"}};
   EXPECT_EQ("worldXX", sformat("{[hello]:X<7}", m2));
   EXPECT_EQ("worldXX", svformat("{hello:X<7}", m2));
   EXPECT_THROW(sformat("{[none]:X<7}", m2), std::out_of_range);
   EXPECT_THROW(svformat("{none:X<7}", m2), std::out_of_range);
   EXPECT_EQ("worldXX", sformat("{[hello]:X<7}", defaulted(m2, "meow")));
   EXPECT_EQ("worldXX", svformat("{hello:X<7}", defaulted(m2, "meow")));
   EXPECT_EQ("meowXXX", sformat("{[none]:X<7}", defaulted(m2, "meow")));
   EXPECT_EQ("meowXXX", svformat("{none:X<7}", defaulted(m2, "meow")));
   try {
     svformat("{none:X<7}", m2);
     EXPECT_FALSE(true) << "svformat should throw on missing key";
   } catch (const FormatKeyNotFoundException& e) {
     EXPECT_STREQ("none", e.key());
   }
   // Test indexing in strings
   EXPECT_EQ("61 62", sformat("{0[0]:x} {0[1]:x}", "abcde"));
   EXPECT_EQ("61 62", svformat("{0:x} {1:x}", "abcde"));
   EXPECT_EQ("61 62", sformat("{0[0]:x} {0[1]:x}", std::string("abcde")));
   EXPECT_EQ("61 62", svformat("{0:x} {1:x}", std::string("abcde")));
   // Test booleans
   EXPECT_EQ("true", sformat("{}", true));
   EXPECT_EQ("1", sformat("{:d}", true));
   EXPECT_EQ("false", sformat("{}", false));
   EXPECT_EQ("0", sformat("{:d}", false));
   // Test pairs
   {
     std::pair<int, std::string> p{42, "hello"};
     EXPECT_EQ("    42 hello ", sformat("{0[0]:6} {0[1]:6}", p));
     EXPECT_EQ("    42 hello ", svformat("{:6} {:6}", p));
   }
   // Test tuples
   {
     std::tuple<int, std::string, int> t{42, "hello", 23};
     EXPECT_EQ("    42 hello      23", sformat("{0[0]:6} {0[1]:6} {0[2]:6}", t));
     EXPECT_EQ("    42 hello      23", svformat("{:6} {:6} {:6}", t));
   }
   // Test writing to stream
   std::ostringstream os;
   os << format("{} {}", 42, 23);
   EXPECT_EQ("42 23", os.str());
   // Test appending to string
   std::string s;
   format(&s, "{} {}", 42, 23);
   format(&s, " hello {:X<7}", "world");
   EXPECT_EQ("42 23 hello worldXX", s);
 }
TEST (Format , Float)
Definition at line 212 of file FormatTest.cpp.
References EXPECT_EQ, and folly::sformat().
                     {
   EXPECT_EQ("1", sformat("{}", 1.0));
   EXPECT_EQ("0.1", sformat("{}", 0.1));
   EXPECT_EQ("0.01", sformat("{}", 0.01));
   EXPECT_EQ("0.001", sformat("{}", 0.001));
   EXPECT_EQ("0.0001", sformat("{}", 0.0001));
   EXPECT_EQ("1e-5", sformat("{}", 0.00001));
   EXPECT_EQ("1e-6", sformat("{}", 0.000001));
   EXPECT_EQ("10", sformat("{}", 10.0));
   EXPECT_EQ("100", sformat("{}", 100.0));
   EXPECT_EQ("1000", sformat("{}", 1000.0));
   EXPECT_EQ("10000", sformat("{}", 10000.0));
   EXPECT_EQ("100000", sformat("{}", 100000.0));
   EXPECT_EQ("1e+6", sformat("{}", 1000000.0));
   EXPECT_EQ("1e+7", sformat("{}", 10000000.0));
   EXPECT_EQ("1.00", sformat("{:.2f}", 1.0));
   EXPECT_EQ("0.10", sformat("{:.2f}", 0.1));
   EXPECT_EQ("0.01", sformat("{:.2f}", 0.01));
   EXPECT_EQ("0.00", sformat("{:.2f}", 0.001));
   EXPECT_EQ("100000. !== 100000", sformat("{:.} !== {:.}", 100000.0, 100000));
   EXPECT_EQ("100000.", sformat("{:.}", 100000.0));
   EXPECT_EQ("1e+6", sformat("{:.}", 1000000.0));
   EXPECT_EQ(" 100000.", sformat("{:8.}", 100000.0));
   EXPECT_EQ("100000.", sformat("{:4.}", 100000.0));
   EXPECT_EQ("  100000", sformat("{:8.8}", 100000.0));
   EXPECT_EQ(" 100000.", sformat("{:8.8.}", 100000.0));
 }
TEST (Format , MultiLevel)
Definition at line 243 of file FormatTest.cpp.
References EXPECT_EQ, and folly::sformat().
{
   std::vector<std::map<std::string, std::string>> v = {
       {
           {"hello", "world"},
       },
   };
   EXPECT_EQ("world", sformat("{[0.hello]}", v));
 }
TEST (Format , separatorDecimalInteger)
Definition at line 253 of file FormatTest.cpp.
References EXPECT_EQ, int64_t, max, min, folly::sformat(), and uint64_t.
{
   EXPECT_EQ("0", sformat("{:,d}", 0));
   EXPECT_EQ("1", sformat("{:d}", 1));
   EXPECT_EQ("1", sformat("{:,d}", 1));
   EXPECT_EQ("1", sformat("{:,}", 1));
   EXPECT_EQ("123", sformat("{:d}", 123));
   EXPECT_EQ("123", sformat("{:,d}", 123));
   EXPECT_EQ("123", sformat("{:,}", 123));
   EXPECT_EQ("1234", sformat("{:d}", 1234));
   EXPECT_EQ("1,234", sformat("{:,d}", 1234));
   EXPECT_EQ("1,234", sformat("{:,}", 1234));
   EXPECT_EQ("12345678", sformat("{:d}", 12345678));
   EXPECT_EQ("12,345,678", sformat("{:,d}", 12345678));
   EXPECT_EQ("12,345,678", sformat("{:,}", 12345678));
   EXPECT_EQ("-1234", sformat("{:d}", -1234));
   EXPECT_EQ("-1,234", sformat("{:,d}", -1234));
   EXPECT_EQ("-1,234", sformat("{:,}", -1234));
   int64_t max_int64_t = std::numeric_limits<int64_t>::max();
   int64_t min_int64_t = std::numeric_limits<int64_t>::min();
   uint64_t max_uint64_t = std::numeric_limits<uint64_t>::max();
   EXPECT_EQ("9223372036854775807", sformat("{:d}", max_int64_t));
   EXPECT_EQ("9,223,372,036,854,775,807", sformat("{:,d}", max_int64_t));
   EXPECT_EQ("9,223,372,036,854,775,807", sformat("{:,}", max_int64_t));
   EXPECT_EQ("-9223372036854775808", sformat("{:d}", min_int64_t));
   EXPECT_EQ("-9,223,372,036,854,775,808", sformat("{:,d}", min_int64_t));
   EXPECT_EQ("-9,223,372,036,854,775,808", sformat("{:,}", min_int64_t));
   EXPECT_EQ("18446744073709551615", sformat("{:d}", max_uint64_t));
   EXPECT_EQ("18,446,744,073,709,551,615", sformat("{:,d}", max_uint64_t));
   EXPECT_EQ("18,446,744,073,709,551,615", sformat("{:,}", max_uint64_t));
   EXPECT_EQ("  -1,234", sformat("{: 8,}", -1234));
   EXPECT_EQ("-001,234", sformat("{:08,d}", -1234));
   EXPECT_EQ("-00001,234", sformat("{:010,d}", -1234));
   EXPECT_EQ(" -1,234 ", sformat("{:^ 8,d}", -1234));
 }
TEST (Format , separatorNumber)
Definition at line 292 of file FormatTest.cpp.
References EXPECT_EQ, int64_t, max, min, folly::sformat(), and uint64_t.
{
   EXPECT_EQ("0", sformat("{:n}", 0));
   EXPECT_EQ("1", sformat("{:n}", 1));
   EXPECT_EQ("123", sformat("{:n}", 123));
   EXPECT_EQ("1234", sformat("{:n}", 1234));
   EXPECT_EQ("12345678", sformat("{:n}", 12345678));
   EXPECT_EQ("-1234", sformat("{:n}", -1234));
   int64_t max_int64_t = std::numeric_limits<int64_t>::max();
   int64_t min_int64_t = std::numeric_limits<int64_t>::min();
   uint64_t max_uint64_t = std::numeric_limits<uint64_t>::max();
   EXPECT_EQ("9223372036854775807", sformat("{:n}", max_int64_t));
   EXPECT_EQ("-9223372036854775808", sformat("{:n}", min_int64_t));
   EXPECT_EQ("18446744073709551615", sformat("{:n}", max_uint64_t));
   EXPECT_EQ("   -1234", sformat("{: 8n}", -1234));
   EXPECT_EQ("-0001234", sformat("{:08n}", -1234));
   EXPECT_EQ("-000001234", sformat("{:010n}", -1234));
   EXPECT_EQ(" -1234  ", sformat("{:^ 8n}", -1234));
 }
TEST (Format , separatorUnit)
Definition at line 322 of file FormatTest.cpp.
References string, testGrouping(), and folly::value().
{
   testGrouping("0", "0");
   testGrouping("1", "1");
   testGrouping("12", "12");
   testGrouping("123", "123");
   testGrouping("1234", "1,234");
   testGrouping("12345", "12,345");
   testGrouping("123456", "123,456");
   testGrouping("1234567", "1,234,567");
   testGrouping("1234567890", "1,234,567,890");
   testGrouping("9223372036854775807", "9,223,372,036,854,775,807");
   testGrouping("18446744073709551615", "18,446,744,073,709,551,615");
 }
TEST (Format , Custom)
Definition at line 364 of file FormatTest.cpp.
References EXPECT_EQ, EXPECT_NE, k, and folly::sformat().
                      {
   KeyValue kv{"hello", 42};
   EXPECT_EQ("<key=hello, value=42>", sformat("{}", kv));
   EXPECT_EQ("<key=hello, value=42>", sformat("{:10}", kv));
   EXPECT_EQ("<key=hello", sformat("{:.10}", kv));
   EXPECT_EQ("<key=hello, value=42>XX", sformat("{:X<23}", kv));
   EXPECT_EQ("XX<key=hello, value=42>", sformat("{:X>23}", kv));
   EXPECT_EQ("<key=hello, value=42>", sformat("{0[0]}", &kv));
   EXPECT_NE("", sformat("{}", &kv));
 }
TEST (Format , Unformatted)
Definition at line 411 of file FormatTest.cpp.
References EXPECT_FORMAT_ERROR, EXPECT_NE, and folly::sformat().
{
   Opaque o;
   EXPECT_NE("", sformat("{}", &o));
   EXPECT_FORMAT_ERROR(
       sformat("{0[0]}", &o), "No formatter available for this type");
 }
TEST (Format , Nested)
Definition at line 418 of file FormatTest.cpp.
References EXPECT_EQ, folly::format(), and folly::sformat().
                      {
   EXPECT_EQ("1 2 3 4", sformat("{} {} {}", 1, 2, format("{} {}", 3, 4)));
   //
   // not copyable, must hold temporary in scope instead.
   auto&& saved = format("{} {}", 3, 4);
   EXPECT_EQ("1 2 3 4", sformat("{} {} {}", 1, 2, saved));
 }
TEST (Format , OutOfBounds)
Definition at line 426 of file FormatTest.cpp.
References EXPECT_EQ, EXPECT_THROW, folly::sformat(), and folly::svformat().
{
   std::vector<int> ints{1, 2, 3, 4, 5};
   EXPECT_EQ("1 3 5", sformat("{0[0]} {0[2]} {0[4]}", ints));
   EXPECT_THROW(sformat("{[5]}", ints), std::out_of_range);
   std::map<std::string, int> map{{"hello", 0}, {"world", 1}};
   EXPECT_EQ("hello = 0", sformat("hello = {[hello]}", map));
   EXPECT_THROW(sformat("{[nope]}", map), std::out_of_range);
   EXPECT_THROW(svformat("{nope}", map), std::out_of_range);
 }
TEST (Format , BogusFormatString)
Definition at line 437 of file FormatTest.cpp.
References testing::Args(), EXPECT_FORMAT_ERROR, EXPECT_THROW_STR, folly::sformat(), and folly::svformat().
{
   EXPECT_FORMAT_ERROR(sformat("}"), "single '}' in format string");
   EXPECT_FORMAT_ERROR(sformat("foo}bar"), "single '}' in format string");
   EXPECT_FORMAT_ERROR(sformat("foo{bar"), "missing ending '}'");
   EXPECT_FORMAT_ERROR(sformat("{[test]"), "missing ending '}'");
   EXPECT_FORMAT_ERROR(sformat("{-1.3}"), "argument index must be non-negative");
   EXPECT_FORMAT_ERROR(sformat("{1.3}", 0, 1, 2), "index not allowed");
   EXPECT_FORMAT_ERROR(
       sformat("{0} {} {1}", 0, 1, 2),
       "may not have both default and explicit arg indexes");
   EXPECT_FORMAT_ERROR(
       sformat("{:*}", 1.2), "dynamic field width argument must be integral");
   EXPECT_FORMAT_ERROR(
       sformat("{} {:*}", "hi"), "argument index out of range, max=1");
   EXPECT_FORMAT_ERROR(
       sformat("{:*0}", 12, "ok"),
       "cannot provide width arg index without value arg index");
   EXPECT_FORMAT_ERROR(
       sformat("{0:*}", 12, "ok"),
       "cannot provide value arg index without width arg index");
   std::vector<int> v{1, 2, 3};
   EXPECT_FORMAT_ERROR(
       svformat("{:*}", v), "dynamic field width not supported in vformat()");
   // This one fails in detail::enforceWhitespace(), which throws
   // std::range_error
   EXPECT_THROW_STR(sformat("{0[test}"), std::range_error, "Non-whitespace");
 }
TEST (Format , Extending)
Definition at line 510 of file FormatTest.cpp.
References EXPECT_EQ, folly::sformat(), and texsformat().
{
   EXPECT_EQ(texsformat("I {} brackets", "love"), "I {love} brackets");
   EXPECT_EQ(
       texsformat("I {} nesting", sformat("really {}", "love")),
       "I {really love} nesting");
   EXPECT_EQ(
       sformat("I also {} nesting", texsformat("have an {} for", "affinity")),
       "I also have an {affinity} for nesting");
   EXPECT_EQ(
       texsformat(
           "Extending {} in {}",
           texsformat("a {}", "formatter"),
           "another formatter"),
       "Extending {a {formatter}} in {another formatter}");
 }
TEST (Format , Temporary)
Definition at line 526 of file FormatTest.cpp.
References EXPECT_EQ, folly::format(), and folly::value().
{
   constexpr StringPiece kStr = "A long string that should go on the heap";
   auto fmt = format("{}", kStr.str()); // Pass a temporary std::string.
   EXPECT_EQ(fmt.str(), kStr);
   // The formatter can be reused.
   EXPECT_EQ(fmt.str(), kStr);
 }
TEST (Format , NoncopyableArg)
Definition at line 561 of file FormatTest.cpp.
References EXPECT_EQ, folly::format(), and v.
{
   {
     // Test that lvalues are held by reference.
     NoncopyableInt v(1);
     auto fmt = format("{}", v);
     EXPECT_EQ(fmt.str(), "1");
     // The formatter can be reused.
     EXPECT_EQ(fmt.str(), "1");
   }
   {
     // Test that rvalues are moved.
     auto fmt = format("{}", NoncopyableInt(1));
     EXPECT_EQ(fmt.str(), "1");
   }
 }
static void testGrouping (const char * a_str, const char * expected) static
Definition at line 314 of file FormatTest.cpp.
References ASSERT_LT, ASSERT_STREQ, and folly::detail::insertThousandsGroupingUnsafe().
Referenced by TEST().
{
   char str[256];
   char* end_ptr = str + snprintf(str, sizeof(str), "%s", a_str);
   ASSERT_LT(end_ptr, str + sizeof(str));
   folly::detail::insertThousandsGroupingUnsafe(str, &end_ptr);
   ASSERT_STREQ(expected, str);
 }
template<class... Args> std::string texsformat (StringPiece fmt, Args &&... args)
Definition at line 504 of file FormatTest.cpp.
References testing::Args().
Referenced by TEST().
{
   return TestExtendingFormatter<false, Args...>(
              fmt, std::forward<Args>(args)...)
       .str();
 }