proxygen: proxygen/folly/folly/experimental/io/test/FsUtilTest.cpp File Reference
FsUtilTest.cpp File Reference
#include <folly/experimental/io/FsUtil.h>
#include <glog/logging.h>
#include <folly/portability/GTest.h>
Functions
TEST (Simple, Path)
TEST (Simple, CanonicalizeParent)
Function Documentation
TEST (Simple , Path)
Definition at line 26 of file FsUtilTest.cpp.
References EXPECT_EQ, EXPECT_FALSE, EXPECT_THROW, EXPECT_TRUE, folly::fs::remove_prefix(), and folly::fs::starts_with().
                    {
   path root("/");
   path abs1("/hello/world");
   path rel1("meow");
   EXPECT_TRUE(starts_with(abs1, root));
   EXPECT_FALSE(starts_with(rel1, root));
   EXPECT_EQ(path("hello/world"), remove_prefix(abs1, root));
   EXPECT_THROW({ remove_prefix(rel1, root); }, filesystem_error);
   path abs2("/hello");
   path abs3("/hello/");
   path abs4("/hello/world");
   path abs5("/hello/world/");
   path abs6("/hello/wo");
   EXPECT_TRUE(starts_with(abs1, abs2));
   EXPECT_TRUE(starts_with(abs1, abs3));
   EXPECT_TRUE(starts_with(abs1, abs4));
   EXPECT_FALSE(starts_with(abs1, abs5));
   EXPECT_FALSE(starts_with(abs1, abs6));
   EXPECT_EQ(path("world"), remove_prefix(abs1, abs2));
   EXPECT_EQ(path("world"), remove_prefix(abs1, abs3));
   EXPECT_EQ(path(), remove_prefix(abs1, abs4));
   EXPECT_THROW({ remove_prefix(abs1, abs5); }, filesystem_error);
   EXPECT_THROW({ remove_prefix(abs1, abs6); }, filesystem_error);
 }
TEST (Simple , CanonicalizeParent)
Definition at line 52 of file FsUtilTest.cpp.
References a, b, c, folly::fs::canonical_parent(), EXPECT_EQ, and EXPECT_THROW.
{
   path a("/usr/bin/tail");
   path b("/usr/lib/../bin/tail");
   path c("/usr/bin/DOES_NOT_EXIST_ASDF");
   path d("/usr/lib/../bin/DOES_NOT_EXIST_ASDF");
   EXPECT_EQ(a, canonical(a));
   EXPECT_EQ(a, canonical_parent(b));
   EXPECT_EQ(a, canonical(b));
   EXPECT_EQ(a, canonical_parent(b));
   EXPECT_THROW({ canonical(c); }, filesystem_error);
   EXPECT_THROW({ canonical(d); }, filesystem_error);
   EXPECT_EQ(c, canonical_parent(c));
   EXPECT_EQ(c, canonical_parent(d));
 }