proxygen: proxygen/folly/folly/futures/test/FutureSplitterTest.cpp File Reference
FutureSplitterTest.cpp File Reference
#include <folly/futures/FutureSplitter.h>
#include <folly/portability/GTest.h>
Functions
TEST (FutureSplitter, splitFutureSuccess)
TEST (FutureSplitter, splitFutureSuccessSemiFuture)
TEST (FutureSplitter, splitFutureSuccessNullExecutor)
TEST (FutureSplitter, splitFutureCopyable)
TEST (FutureSplitter, splitFutureMovable)
TEST (FutureSplitter, splitFutureCopyAssignable)
TEST (FutureSplitter, splitFutureMoveAssignable)
TEST (FutureSplitter, splitFutureScope)
TEST (FutureSplitter, splitFutureFailure)
TEST (FutureSplitter, splitFuturePriority)
Function Documentation
TEST (FutureSplitter , splitFutureSuccess)
Definition at line 22 of file FutureSplitterTest.cpp.
References EXPECT_FALSE, EXPECT_TRUE, folly::FutureSplitter< T >::getFuture(), folly::Promise< T >::getSemiFuture(), folly::InlineExecutor::instance(), and folly::Promise< T >::setValue().
{
   Promise<int> p;
   folly::FutureSplitter<int> sp(
       p.getSemiFuture().via(&InlineExecutor::instance()));
   auto f1 = sp.getFuture();
   EXPECT_FALSE(f1.isReady());
   p.setValue(1);
   EXPECT_TRUE(f1.isReady());
   EXPECT_TRUE(f1.hasValue());
   auto f2 = sp.getFuture();
   EXPECT_TRUE(f2.isReady());
   EXPECT_TRUE(f2.hasValue());
 }
TEST (FutureSplitter , splitFutureSuccessSemiFuture)
Definition at line 36 of file FutureSplitterTest.cpp.
References EXPECT_FALSE, EXPECT_TRUE, folly::FutureSplitter< T >::getSemiFuture(), folly::Promise< T >::getSemiFuture(), folly::InlineExecutor::instance(), and folly::Promise< T >::setValue().
{
   Promise<int> p;
   folly::FutureSplitter<int> sp(
       p.getSemiFuture().via(&InlineExecutor::instance()));
   auto f1 = sp.getSemiFuture();
   EXPECT_FALSE(f1.isReady());
   p.setValue(1);
   EXPECT_TRUE(f1.isReady());
   EXPECT_TRUE(f1.hasValue());
   auto f2 = sp.getSemiFuture();
   EXPECT_TRUE(f2.isReady());
   EXPECT_TRUE(f2.hasValue());
 }
TEST (FutureSplitter , splitFutureSuccessNullExecutor)
Definition at line 50 of file FutureSplitterTest.cpp.
References EXPECT_FALSE, EXPECT_TRUE, f, folly::FutureSplitter< T >::getFuture(), folly::Promise< T >::getSemiFuture(), folly::InlineExecutor::instance(), folly::gen::move, and folly::Promise< T >::setValue().
{
   Promise<int> p;
   auto sf = p.getSemiFuture();
   // Double via because a null executor to SemiFuture.via is invalid but we
   // are testing a situation where we have a FutureSplitter from a future with
   // a null executor to account for legacy code.
   auto f = std::move(sf).via(&InlineExecutor::instance()).via(nullptr);
   folly::FutureSplitter<int> sp(std::move(f));
   auto f1 = sp.getFuture();
   EXPECT_FALSE(f1.isReady());
   p.setValue(1);
   EXPECT_TRUE(f1.isReady());
   EXPECT_TRUE(f1.hasValue());
   auto f2 = sp.getFuture();
   EXPECT_TRUE(f2.isReady());
   EXPECT_TRUE(f2.hasValue());
 }
TEST (FutureSplitter , splitFutureCopyable)
Definition at line 68 of file FutureSplitterTest.cpp.
References EXPECT_FALSE, EXPECT_TRUE, folly::FutureSplitter< T >::getFuture(), folly::Promise< T >::getSemiFuture(), folly::InlineExecutor::instance(), and folly::Promise< T >::setValue().
{
   Promise<int> p;
   folly::FutureSplitter<int> sp1(
       p.getSemiFuture().via(&InlineExecutor::instance()));
   folly::FutureSplitter<int> sp2(sp1);
   auto f1 = sp1.getFuture();
   EXPECT_FALSE(f1.isReady());
   p.setValue(1);
   EXPECT_TRUE(f1.isReady());
   EXPECT_TRUE(f1.hasValue());
   auto f2 = sp2.getFuture();
   EXPECT_TRUE(f2.isReady());
   EXPECT_TRUE(f2.hasValue());
   folly::FutureSplitter<int> sp3(sp1);
   auto f3 = sp3.getFuture();
   EXPECT_TRUE(f3.isReady());
   EXPECT_TRUE(f3.hasValue());
 }
TEST (FutureSplitter , splitFutureMovable)
Definition at line 87 of file FutureSplitterTest.cpp.
References EXPECT_FALSE, EXPECT_TRUE, folly::FutureSplitter< T >::getFuture(), folly::Promise< T >::getSemiFuture(), folly::InlineExecutor::instance(), folly::gen::move, and folly::Promise< T >::setValue().
{
   Promise<int> p;
   folly::FutureSplitter<int> sp1(
       p.getSemiFuture().via(&InlineExecutor::instance()));
   auto f1 = sp1.getFuture();
   folly::FutureSplitter<int> sp2(std::move(sp1));
   EXPECT_FALSE(f1.isReady());
   p.setValue(1);
   EXPECT_TRUE(f1.isReady());
   EXPECT_TRUE(f1.hasValue());
   auto f2 = sp2.getFuture();
   EXPECT_TRUE(f2.isReady());
   EXPECT_TRUE(f2.hasValue());
   folly::FutureSplitter<int> sp3(std::move(sp2));
   auto f3 = sp3.getFuture();
   EXPECT_TRUE(f3.isReady());
   EXPECT_TRUE(f3.hasValue());
 }
TEST (FutureSplitter , splitFutureCopyAssignable)
Definition at line 106 of file FutureSplitterTest.cpp.
References EXPECT_FALSE, EXPECT_TRUE, folly::FutureSplitter< T >::getFuture(), folly::Promise< T >::getSemiFuture(), folly::InlineExecutor::instance(), and folly::Promise< T >::setValue().
{
   Promise<int> p;
   folly::FutureSplitter<int> sp1(
       p.getSemiFuture().via(&InlineExecutor::instance()));
   folly::FutureSplitter<int> sp2{};
   sp2 = sp1;
   auto f1 = sp1.getFuture();
   EXPECT_FALSE(f1.isReady());
   p.setValue(1);
   EXPECT_TRUE(f1.isReady());
   EXPECT_TRUE(f1.hasValue());
   auto f2 = sp2.getFuture();
   EXPECT_TRUE(f2.isReady());
   EXPECT_TRUE(f2.hasValue());
   folly::FutureSplitter<int> sp3(sp1);
   auto f3 = sp3.getFuture();
   EXPECT_TRUE(f3.isReady());
   EXPECT_TRUE(f3.hasValue());
 }
TEST (FutureSplitter , splitFutureMoveAssignable)
Definition at line 126 of file FutureSplitterTest.cpp.
References EXPECT_FALSE, EXPECT_TRUE, folly::FutureSplitter< T >::getFuture(), folly::Promise< T >::getSemiFuture(), folly::InlineExecutor::instance(), folly::gen::move, and folly::Promise< T >::setValue().
{
   Promise<int> p;
   folly::FutureSplitter<int> sp1(
       p.getSemiFuture().via(&InlineExecutor::instance()));
   auto f1 = sp1.getFuture();
   folly::FutureSplitter<int> sp2{};
   sp2 = std::move(sp1);
   EXPECT_FALSE(f1.isReady());
   p.setValue(1);
   EXPECT_TRUE(f1.isReady());
   EXPECT_TRUE(f1.hasValue());
   auto f2 = sp2.getFuture();
   EXPECT_TRUE(f2.isReady());
   EXPECT_TRUE(f2.hasValue());
   folly::FutureSplitter<int> sp3(std::move(sp2));
   auto f3 = sp3.getFuture();
   EXPECT_TRUE(f3.isReady());
   EXPECT_TRUE(f3.hasValue());
 }
TEST (FutureSplitter , splitFutureScope)
Definition at line 146 of file FutureSplitterTest.cpp.
References EXPECT_EQ, EXPECT_FALSE, EXPECT_NO_THROW, EXPECT_TRUE, folly::Promise< T >::getFuture(), folly::Promise< T >::getSemiFuture(), folly::InlineExecutor::instance(), folly::gen::move, and folly::Promise< T >::setValue().
{
   Promise<int> p;
   auto pSP = std::make_unique<folly::FutureSplitter<int>>(
       p.getSemiFuture().via(&InlineExecutor::instance()));
   auto f1 = pSP->getFuture();
   EXPECT_FALSE(f1.isReady());
   pSP.reset();
   EXPECT_NO_THROW(EXPECT_FALSE(f1.isReady()));
   p.setValue(1);
   EXPECT_TRUE(f1.isReady());
   EXPECT_TRUE(f1.hasValue());
   EXPECT_EQ(1, std::move(f1).get());
 }
TEST (FutureSplitter , splitFutureFailure)
Definition at line 160 of file FutureSplitterTest.cpp.
References EXPECT_FALSE, EXPECT_TRUE, folly::FutureSplitter< T >::getFuture(), folly::Promise< T >::getSemiFuture(), folly::InlineExecutor::instance(), and folly::Promise< T >::setException().
{
   Promise<int> p;
   folly::FutureSplitter<int> sp(
       p.getSemiFuture().via(&InlineExecutor::instance()));
   auto f1 = sp.getFuture();
   EXPECT_FALSE(f1.isReady());
   try {
     throw std::runtime_error("Oops");
   } catch (std::exception& e) {
     p.setException(exception_wrapper(std::current_exception(), e));
   }
   EXPECT_TRUE(f1.isReady());
   EXPECT_TRUE(f1.hasException());
   auto f2 = sp.getFuture();
   EXPECT_TRUE(f2.isReady());
   EXPECT_TRUE(f2.hasException());
 }
TEST (FutureSplitter , splitFuturePriority)
Definition at line 178 of file FutureSplitterTest.cpp.
References EXPECT_EQ, folly::FutureSplitter< T >::getFuture(), folly::Promise< T >::getSemiFuture(), folly::Executor::HI_PRI, folly::InlineExecutor::instance(), folly::Executor::LO_PRI, and folly::Executor::MID_PRI.
{
   std::vector<int8_t> priorities = {
       folly::Executor::LO_PRI,
       folly::Executor::MID_PRI,
       folly::Executor::HI_PRI,
   };
   for (const auto priority : priorities) {
     Promise<int> p;
     folly::FutureSplitter<int> sp(
         p.getSemiFuture().via(&InlineExecutor::instance(), priority));
     auto fut = sp.getFuture();
     EXPECT_EQ(priority, fut.getPriority());
   }
 }