proxygen: proxygen/folly/folly/gen/test/StringBenchmark.cpp File Reference
StringBenchmark.cpp File Reference
#include <atomic>
#include <glog/logging.h>
#include <folly/Benchmark.h>
#include <folly/String.h>
#include <folly/container/Foreach.h>
#include <folly/gen/Base.h>
#include <folly/gen/String.h>
Functions
BENCHMARK (StringResplitter_Big, iters)
BENCHMARK_RELATIVE (StringResplitter_Small, iters)
BENCHMARK_DRAW_LINE ()
BENCHMARK (StringSplit_Old, iters)
BENCHMARK_RELATIVE (StringSplit_Gen_Vector, iters)
BENCHMARK (StringSplit_Old_ReuseVector, iters)
BENCHMARK_RELATIVE (StringSplit_Gen_ReuseVector, iters)
BENCHMARK_RELATIVE (StringSplit_Gen, iters)
BENCHMARK_RELATIVE (StringSplit_Gen_Take, iters)
BENCHMARK (StringUnsplit_Old, iters)
BENCHMARK_RELATIVE (StringUnsplit_Old_ReusedBuffer, iters)
BENCHMARK_RELATIVE (StringUnsplit_Gen, iters)
BENCHMARK_RELATIVE (StringUnsplit_Gen_ReusedBuffer, iters)
void StringUnsplit_Gen (size_t iters, size_t joinSize)
void Lines_Gen (size_t iters, int joinSize)
BENCHMARK (Records_EachToTuple, iters)
BENCHMARK_RELATIVE (Records_VectorStringPieceReused, iters)
BENCHMARK_RELATIVE (Records_VectorStringPiece, iters)
BENCHMARK_RELATIVE (Records_VectorString, iters)
int main (int argc, char *argv[])
Variables
fbstring records
Function Documentation
BENCHMARK (StringResplitter_Big , iters)
Definition at line 68 of file StringBenchmark.cpp.
References folly::doNotOptimizeAway(), folly::gen::from(), folly::gen::map(), folly::gen::resplit(), s, and folly::gen::sum.
{
   size_t s = 0;
   while (iters--) {
     s += from({bigLines}) | resplit('\n') | map(&len) | sum;
   }
   folly::doNotOptimizeAway(s);
 }
BENCHMARK (StringSplit_Old , iters)
Definition at line 86 of file StringBenchmark.cpp.
References folly::doNotOptimizeAway(), s, folly::gen::split(), and string.
{
   size_t s = 0;
   std::string line(kLine);
   while (iters--) {
     std::vector<StringPiece> parts;
     split(' ', line, parts);
     s += parts.size();
   }
   folly::doNotOptimizeAway(s);
 }
BENCHMARK (StringSplit_Old_ReuseVector , iters)
Definition at line 108 of file StringBenchmark.cpp.
References folly::doNotOptimizeAway(), s, folly::gen::split(), and string.
{
   size_t s = 0;
   std::string line(kLine);
   std::vector<StringPiece> parts;
   while (iters--) {
     parts.clear();
     split(' ', line, parts);
     s += parts.size();
   }
   folly::doNotOptimizeAway(s);
 }
BENCHMARK (StringUnsplit_Old , iters)
Definition at line 152 of file StringBenchmark.cpp.
References folly::doNotOptimizeAway(), folly::join(), s, and folly::basic_fbstring< E, T, A, Storage >::size().
{
   size_t s = 0;
   while (iters--) {
     fbstring joined;
     join(',', testStrVector, joined);
     s += joined.size();
   }
   folly::doNotOptimizeAway(s);
 }
BENCHMARK (Records_EachToTuple , iters)
Definition at line 239 of file StringBenchmark.cpp.
References folly::doNotOptimizeAway(), i, s, folly::gen::split(), and folly::gen::sum.
{
   size_t s = 0;
   for (size_t i = 0; i < iters; i += 1000) {
     // clang-format off
     s += split(records, '\n')
         | eachToTuple<int, size_t, StringPiece>(' ')
         | get<1>()
         | sum;
     // clang-format on
   }
   folly::doNotOptimizeAway(s);
 }
BENCHMARK_DRAW_LINE ()
BENCHMARK_RELATIVE (StringResplitter_Small , iters)
Definition at line 76 of file StringBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE(), folly::doNotOptimizeAway(), folly::gen::from(), folly::gen::map(), folly::gen::resplit(), s, and folly::gen::sum.
{
   size_t s = 0;
   while (iters--) {
     s += from(smallLines) | resplit('\n') | map(&len) | sum;
   }
   folly::doNotOptimizeAway(s);
 }
BENCHMARK_RELATIVE (StringSplit_Gen_Vector , iters)
Definition at line 97 of file StringBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE(), folly::doNotOptimizeAway(), s, and folly::gen::split().
{
   size_t s = 0;
   StringPiece line(kLine);
   while (iters--) {
     s += (split(line, ' ') | as<vector>()).size();
   }
   folly::doNotOptimizeAway(s);
 }
BENCHMARK_RELATIVE (StringSplit_Gen_ReuseVector , iters)
Definition at line 120 of file StringBenchmark.cpp.
References folly::gen::appendTo(), folly::doNotOptimizeAway(), s, and folly::gen::split().
{
   size_t s = 0;
   StringPiece line(kLine);
   std::vector<StringPiece> parts;
   while (iters--) {
     parts.clear();
     split(line, ' ') | appendTo(parts);
     s += parts.size();
   }
   folly::doNotOptimizeAway(s);
 }
BENCHMARK_RELATIVE (StringSplit_Gen , iters)
Definition at line 132 of file StringBenchmark.cpp.
References folly::gen::count, folly::doNotOptimizeAway(), s, and folly::gen::split().
{
   size_t s = 0;
   StringPiece line(kLine);
   while (iters--) {
     s += split(line, ' ') | count;
   }
   folly::doNotOptimizeAway(s);
 }
BENCHMARK_RELATIVE (StringSplit_Gen_Take , iters)
Definition at line 141 of file StringBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE(), folly::gen::count, folly::doNotOptimizeAway(), s, folly::gen::split(), and folly::gen::take().
{
   size_t s = 0;
   StringPiece line(kLine);
   while (iters--) {
     s += split(line, ' ') | take(10) | count;
   }
   folly::doNotOptimizeAway(s);
 }
BENCHMARK_RELATIVE (StringUnsplit_Old_ReusedBuffer , iters)
Definition at line 162 of file StringBenchmark.cpp.
References folly::basic_fbstring< E, T, A, Storage >::clear(), folly::doNotOptimizeAway(), folly::join(), s, and folly::basic_fbstring< E, T, A, Storage >::size().
{
   size_t s = 0;
   fbstring joined;
   while (iters--) {
     joined.clear();
     join(',', testStrVector, joined);
     s += joined.size();
   }
   folly::doNotOptimizeAway(s);
 }
BENCHMARK_RELATIVE (StringUnsplit_Gen , iters)
Definition at line 173 of file StringBenchmark.cpp.
References folly::doNotOptimizeAway(), folly::gen::from(), s, folly::basic_fbstring< E, T, A, Storage >::size(), and folly::gen::unsplit().
{
   size_t s = 0;
   while (iters--) {
     fbstring joined = from(testStrVector) | unsplit(',');
     s += joined.size();
   }
   folly::doNotOptimizeAway(s);
 }
BENCHMARK_RELATIVE (StringUnsplit_Gen_ReusedBuffer , iters)
Definition at line 182 of file StringBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE(), buffer(), folly::basic_fbstring< E, T, A, Storage >::clear(), folly::doNotOptimizeAway(), folly::gen::from(), s, folly::basic_fbstring< E, T, A, Storage >::size(), and folly::gen::unsplit().
{
   size_t s = 0;
   fbstring buffer;
   while (iters--) {
     buffer.clear();
     from(testStrVector) | unsplit(',', &buffer);
     s += buffer.size();
   }
   folly::doNotOptimizeAway(s);
 }
BENCHMARK_RELATIVE (Records_VectorStringPieceReused , iters)
Definition at line 252 of file StringBenchmark.cpp.
References folly::doNotOptimizeAway(), i, std::tr1::make_tuple(), folly::gen::mapped(), s, folly::gen::split(), folly::split(), and folly::gen::sum.
{
   size_t s = 0;
   std::vector<StringPiece> fields;
   for (size_t i = 0; i < iters; i += 1000) {
     // clang-format off
     s += split(records, '\n')
         | mapped([&](StringPiece line) {
           fields.clear();
           folly::split(' ', line, fields);
           CHECK(fields.size() == 3);
           return std::make_tuple(
               folly::to<int>(fields[0]),
               folly::to<size_t>(fields[1]),
               StringPiece(fields[2]));
         })
         | get<1>()
         | sum;
     // clang-format on
   }
   folly::doNotOptimizeAway(s);
 }
BENCHMARK_RELATIVE (Records_VectorStringPiece , iters)
Definition at line 274 of file StringBenchmark.cpp.
References folly::doNotOptimizeAway(), i, std::tr1::make_tuple(), folly::gen::mapped(), s, folly::gen::split(), folly::split(), and folly::gen::sum.
{
   size_t s = 0;
   for (size_t i = 0; i < iters; i += 1000) {
     // clang-format off
     s += split(records, '\n')
         | mapped([](StringPiece line) {
           std::vector<StringPiece> fields;
           folly::split(' ', line, fields);
           CHECK(fields.size() == 3);
           return std::make_tuple(
               folly::to<int>(fields[0]),
               folly::to<size_t>(fields[1]),
               StringPiece(fields[2]));
         })
         | get<1>()
         | sum;
     // clang-format on
   }
   folly::doNotOptimizeAway(s);
 }
BENCHMARK_RELATIVE (Records_VectorString , iters)
Definition at line 295 of file StringBenchmark.cpp.
References folly::doNotOptimizeAway(), i, std::tr1::make_tuple(), folly::gen::mapped(), s, folly::gen::split(), folly::split(), and folly::gen::sum.
{
   size_t s = 0;
   for (size_t i = 0; i < iters; i += 1000) {
     // clang-format off
     s += split(records, '\n')
         | mapped([](StringPiece line) {
           std::vector<std::string> fields;
           folly::split(' ', line, fields);
           CHECK(fields.size() == 3);
           return std::make_tuple(
               folly::to<int>(fields[0]),
               folly::to<size_t>(fields[1]),
               StringPiece(fields[2]));
         })
         | get<1>()
         | sum;
     // clang-format on
   }
   folly::doNotOptimizeAway(s);
 }
void Lines_Gen (size_t iters, int joinSize)
Definition at line 216 of file StringBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE(), BENCHMARK_PARAM, BENCHMARK_RELATIVE_PARAM, folly::gen::count, folly::doNotOptimizeAway(), i, folly::gen::lines(), s, folly::Range< Iter >::subpiece(), and folly::gen::take().
{
   size_t s = 0;
   StringPiece content = testFileContent;
   for (size_t i = 0; i < iters; ++i) {
     s += lines(content.subpiece(0, joinSize)) | take(100) | count;
   }
   folly::doNotOptimizeAway(s);
 }
int main (int argc, char * argv[])
Definition at line 347 of file StringBenchmark.cpp.
References folly::runBenchmarks().
{
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   initStringResplitterBenchmark();
   runBenchmarks();
   return 0;
 }
void StringUnsplit_Gen (size_t iters, size_t joinSize)
Definition at line 195 of file StringBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE(), BENCHMARK_PARAM, BENCHMARK_RELATIVE_PARAM, BENCHMARK_SUSPEND, buffer(), folly::basic_fbstring< E, T, A, Storage >::clear(), folly::doNotOptimizeAway(), FOR_EACH_RANGE, folly::gen::from(), i, s, folly::basic_fbstring< E, T, A, Storage >::size(), folly::gen::unsplit(), and v.
{
   std::vector<fbstring> v;
   BENCHMARK_SUSPEND {
     FOR_EACH_RANGE (i, 0, joinSize) { v.push_back(to<fbstring>(rand())); }
   }
   size_t s = 0;
   fbstring buffer;
   while (iters--) {
     buffer.clear();
     from(v) | unsplit(',', &buffer);
     s += buffer.size();
   }
   folly::doNotOptimizeAway(s);
 }
Variable Documentation
fbstring records
Initial value:
= seq<size_t>(1, 1000)
    | mapped([](size_t i) {
      return folly::to<fbstring>(i, ' ', i * i, ' ', i * i * i);
    })
    | unsplit('\n')
Definition at line 232 of file StringBenchmark.cpp.
Referenced by folly::test::TEST().