proxygen: proxygen/folly/folly/gen/test/FileTest.cpp File Reference
FileTest.cpp File Reference
#include <string>
#include <vector>
#include <folly/File.h>
#include <folly/Range.h>
#include <folly/container/Array.h>
#include <folly/experimental/TestUtil.h>
#include <folly/gen/Base.h>
#include <folly/gen/File.h>
#include <folly/portability/GTest.h>
Classes
class FileGenBufferedTest
Functions
TEST (FileGen, ByLine)
TEST (FileGen, ByLineFull)
TEST_P (FileGenBufferedTest, FileWriter)
TEST (FileGenBufferedTest, FileWriterSimple)
INSTANTIATE_TEST_CASE_P (DifferentBufferSizes, FileGenBufferedTest,::testing::Values(0, 1, 2, 4, 8, 64, 4096))
Function Documentation
INSTANTIATE_TEST_CASE_P (DifferentBufferSizes , FileGenBufferedTest , ::testing::Values(0, 1, 2, 4, 8, 64, 4096))
Referenced by TEST().
TEST (FileGen , ByLine)
Definition at line 32 of file FileTest.cpp.
References folly::gen::byLine(), folly::collect(), EXPECT_EQ, folly::test::TemporaryFile::fd(), folly::gen::from(), folly::gen::lines(), folly::test::TemporaryFile::path(), folly::gen::resplit(), string, and fizz::detail::write().
                       {
   auto collect = eachTo<std::string>() | as<vector>();
   const std::string cases[] = {
       "Hello world\n"
       "This is the second line\n"
       "\n"
       "\n"
       "a few empty lines above\n"
       "incomplete last line",
       "complete last line\n",
       "\n",
       "",
   };
   for (auto& lines : cases) {
     test::TemporaryFile file("ByLine");
     EXPECT_EQ(lines.size(), write(file.fd(), lines.data(), lines.size()));
     auto expected = from({lines}) | resplit('\n') | collect;
     auto found = byLine(file.path().string().c_str()) | collect;
     EXPECT_EQ(expected, found) << "For Input: '" << lines << "'";
   }
 }
TEST (FileGen , ByLineFull)
Definition at line 60 of file FileTest.cpp.
References folly::gen::byLineFull(), EXPECT_EQ, folly::test::TemporaryFile::fd(), folly::gen::lines(), folly::test::TemporaryFile::path(), folly::stripLeftMargin(), and fizz::detail::write().
{
   auto cases = std::vector<std::string>{
       stripLeftMargin(R"(
          Hello world
          This is the second line
          a few empty lines above
          incomplete last line)"),
       "complete last line\n",
       "\n",
       "",
   };
   for (auto& lines : cases) {
     test::TemporaryFile file("ByLineFull");
     EXPECT_EQ(lines.size(), write(file.fd(), lines.data(), lines.size()));
     auto found =
         byLineFull(file.path().string().c_str()) | unsplit<std::string>("");
     EXPECT_EQ(lines, found);
   }
 }
TEST (FileGenBufferedTest , FileWriterSimple)
Definition at line 111 of file FileTest.cpp.
References folly::gen::byLine(), EXPECT_EQ, folly::test::TemporaryFile::fd(), INSTANTIATE_TEST_CASE_P(), folly::gen::map(), folly::test::TemporaryFile::path(), folly::gen::seq(), folly::gen::sum, folly::gen::toFile(), v, and x.
{
   test::TemporaryFile file("FileWriter");
   auto toLine = [](int v) { return to<std::string>(v, '\n'); };
   auto squares = seq(1, 100) | map([](int x) { return x * x; });
   squares | map(toLine) | eachAs<StringPiece>() | toFile(File(file.fd()));
   EXPECT_EQ(
       squares | sum,
       byLine(File(file.path().string().c_str())) | eachTo<int>() | sum);
 }
TEST_P (FileGenBufferedTest , FileWriter)
Definition at line 90 of file FileTest.cpp.
References folly::gen::byLine(), folly::collect(), EXPECT_TRUE, folly::test::TemporaryFile::fd(), folly::gen::from(), folly::gen::lines(), folly::test::TemporaryFile::path(), folly::gen::resplit(), string, and folly::gen::toFile().
{
   size_t bufferSize = GetParam();
   test::TemporaryFile file("FileWriter");
   static const std::string lines(
       "Hello world\n"
       "This is the second line\n"
       "\n"
       "\n"
       "a few empty lines above\n");
   auto src = from({lines, lines, lines, lines, lines, lines, lines, lines});
   auto collect = eachTo<std::string>() | as<vector>();
   auto expected = src | resplit('\n') | collect;
   src | eachAs<StringPiece>() | toFile(File(file.fd()), bufferSize);
   auto found = byLine(file.path().string().c_str()) | collect;
   EXPECT_TRUE(expected == found);
 }