proxygen: proxygen/folly/folly/executors/test/GlobalExecutorTest.cpp File Reference
GlobalExecutorTest.cpp File Reference
#include <folly/executors/GlobalExecutor.h>
#include <folly/executors/IOExecutor.h>
#include <folly/portability/GTest.h>
Functions
TEST (GlobalExecutorTest, GlobalCPUExecutor)
TEST (GlobalExecutorTest, GlobalIOExecutor)
Function Documentation
TEST (GlobalExecutorTest , GlobalCPUExecutor)
Definition at line 23 of file GlobalExecutorTest.cpp.
References add, count, dummy(), EXPECT_EQ, f, folly::getCPUExecutor(), and folly::setCPUExecutor().
{
   class DummyExecutor : public folly::Executor {
    public:
     void add(Func f) override {
       f();
       count++;
     }
     int count{0};
   };
   // The default CPU executor is a synchronous inline executor, lets verify
   // that work we add is executed
   auto count = 0;
   auto f = [&]() { count++; };
   // Don't explode, we should create the default global CPUExecutor lazily here.
   getCPUExecutor()->add(f);
   EXPECT_EQ(1, count);
   {
     auto dummy = std::make_shared<DummyExecutor>();
     setCPUExecutor(dummy);
     getCPUExecutor()->add(f);
     // Make sure we were properly installed.
     EXPECT_EQ(1, dummy->count);
     EXPECT_EQ(2, count);
   }
   // Don't explode, we should restore the default global CPUExecutor because our
   // weak reference to dummy has expired
   getCPUExecutor()->add(f);
   EXPECT_EQ(3, count);
 }
TEST (GlobalExecutorTest , GlobalIOExecutor)
Definition at line 57 of file GlobalExecutorTest.cpp.
References add, count, dummy(), EXPECT_EQ, f, folly::getEventBase(), folly::getIOExecutor(), and folly::setIOExecutor().
{
   class DummyExecutor : public IOExecutor {
    public:
     void add(Func) override {
       count++;
     }
     folly::EventBase* getEventBase() override {
       return nullptr;
     }
     int count{0};
   };
   auto f = []() {};
   // Don't explode, we should create the default global IOExecutor lazily here.
   getIOExecutor()->add(f);
   {
     auto dummy = std::make_shared<DummyExecutor>();
     setIOExecutor(dummy);
     getIOExecutor()->add(f);
     // Make sure we were properly installed.
     EXPECT_EQ(1, dummy->count);
   }
   // Don't explode, we should restore the default global IOExecutor because our
   // weak reference to dummy has expired
   getIOExecutor()->add(f);
 }