proxygen: proxygen/folly/folly/logging/test/GlogFormatterTest.cpp File Reference
GlogFormatterTest.cpp File Reference
#include <cstdlib>
#include <folly/init/Init.h>
#include <folly/logging/GlogStyleFormatter.h>
#include <folly/logging/LogMessage.h>
#include <folly/logging/Logger.h>
#include <folly/logging/LoggerDB.h>
#include <folly/portability/GTest.h>
#include <folly/portability/Stdlib.h>
Functions
TEST (GlogFormatter, log)
TEST (GlogFormatter, filename)
TEST (GlogFormatter, multiline)
TEST (GlogFormatter, singleNewline)
TEST (GlogFormatter, unprintableChars)
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 191 of file GlogFormatterTest.cpp.
References folly::init(), testing::InitGoogleTest(), and RUN_ALL_TESTS().
{
   testing::InitGoogleTest(&argc, argv);
   folly::init(&argc, &argv);
   // Some of our tests check timestamps emitted by the formatter.
   // Set the timezone to a consistent value so that the tests are not
   // affected by the local time of the user running the test.
   //
   // UTC is the only timezone that we can really rely on to work consistently.
   // This will work even in the absence of a proper tzdata installation on the
   // local system.
   setenv("TZ", "UTC", 1);
   return RUN_ALL_TESTS();
 }
TEST (GlogFormatter , log)
Definition at line 66 of file GlogFormatterTest.cpp.
References EXPECT_EQ, folly::getOSThreadID(), folly::sformat(), and folly::WARN.
{
   auto tid = getOSThreadID();
   // Test a very simple single-line log message
   auto expected = folly::sformat(
       "W0417 13:45:56.123456 {:5d} myfile.cpp:1234] hello world\n", tid);
   EXPECT_EQ(
       expected,
       formatMsg(
           LogLevel::WARN, "hello world", "myfile.cpp", 1234, "testFunction"));
 }
TEST (GlogFormatter , filename)
Definition at line 78 of file GlogFormatterTest.cpp.
References EXPECT_EQ, folly::getOSThreadID(), folly::sformat(), and folly::WARN.
{
   auto tid = getOSThreadID();
   // Make sure only the file basename gets logged
   auto expected = folly::sformat(
       "W0417 13:45:56.123456 {:5d} myfile.cpp:1234] hello world\n", tid);
   EXPECT_EQ(
       expected,
       formatMsg(
           LogLevel::WARN,
           "hello world",
           "src/test/logging/code/myfile.cpp",
           1234,
           "testFunction"));
   // Log a message with a very long file name.
   expected = folly::sformat(
       "W0417 13:45:56.123456 {:5d} "
       "this_is_a_really_long_file_name_that_will_probably_exceed_"
       "our_buffer_allocation_guess.cpp:123456789] oh noes\n",
       tid);
   EXPECT_EQ(
       expected,
       formatMsg(
           LogLevel::WARN,
           "oh noes",
           "this_is_a_really_long_file_name_that_will_probably_exceed_"
           "our_buffer_allocation_guess.cpp",
           123456789,
           "testFunction"));
 }
TEST (GlogFormatter , multiline)
Definition at line 110 of file GlogFormatterTest.cpp.
References folly::DBG9, EXPECT_EQ, folly::getOSThreadID(), and folly::svformat().
{
   auto tid = getOSThreadID();
   std::map<std::string, std::string> formatMap{
       {"tid", folly::to<std::string>(tid)}};
   // Log a multi-line message
   auto expected = folly::svformat(
       "V0417 13:45:56.123456 {tid:>5s} rodent.cpp:777] Eeek, a mouse!\n"
       "V0417 13:45:56.123456 {tid:>5s} rodent.cpp:777]    .   .\n"
       "V0417 13:45:56.123456 {tid:>5s} rodent.cpp:777]   ( ).( )\n"
       "V0417 13:45:56.123456 {tid:>5s} rodent.cpp:777]    (o o) .-._.'\n"
       "V0417 13:45:56.123456 {tid:>5s} rodent.cpp:777]   (  -  )\n"
       "V0417 13:45:56.123456 {tid:>5s} rodent.cpp:777]    mm mm\n"
       "V0417 13:45:56.123456 {tid:>5s} rodent.cpp:777] \n"
       "V0417 13:45:56.123456 {tid:>5s} rodent.cpp:777] =============\n",
       formatMap);
   EXPECT_EQ(
       expected,
       formatMsg(
           LogLevel::DBG9,
           "Eeek, a mouse!\n"
           "   .   .\n"
           "  ( ).( )\n"
           "   (o o) .-._.'\n"
           "  (  -  )\n"
           "   mm mm\n"
           "\n"
           "=============",
           "src/rodent.cpp",
           777,
           "testFunction"));
 }
TEST (GlogFormatter , singleNewline)
Definition at line 143 of file GlogFormatterTest.cpp.
References folly::DBG9, EXPECT_EQ, folly::getOSThreadID(), and folly::svformat().
{
   auto tid = getOSThreadID();
   std::map<std::string, std::string> formatMap{
       {"tid", folly::to<std::string>(tid)}};
   // Logging a single newline is basically two empty strings.
   auto expected = folly::svformat(
       "V0417 13:45:56.123456 {tid:>5s} foo.txt:123] \n"
       "V0417 13:45:56.123456 {tid:>5s} foo.txt:123] \n",
       formatMap);
   EXPECT_EQ(
       expected,
       formatMsg(LogLevel::DBG9, "\n", "foo.txt", 123, "testFunction"));
 }
TEST (GlogFormatter , unprintableChars)
Definition at line 158 of file GlogFormatterTest.cpp.
References folly::CRITICAL, folly::ERR, EXPECT_EQ, folly::getOSThreadID(), folly::INFO, folly::sformat(), and string.
{
   auto tid = getOSThreadID();
   // Unprintable characters should be backslash escaped, as should backslashes.
   auto expected = folly::sformat(
       "E0417 13:45:56.123456 {:5d} escapes.cpp:97] foo\\x07bar\\x1btest\n",
       tid);
   EXPECT_EQ(
       expected,
       formatMsg(
           LogLevel::ERR,
           "foo\abar\x1btest",
           "escapes.cpp",
           97,
           "testFunction"));
   expected = folly::sformat(
       "I0417 13:45:56.123456 {:5d} escapes.cpp:98] foo\\\\bar\"test\n", tid);
   EXPECT_EQ(
       expected,
       formatMsg(
           LogLevel::INFO, "foo\\bar\"test", "escapes.cpp", 98, "testFunction"));
   expected = folly::sformat(
       "C0417 13:45:56.123456 {:5d} escapes.cpp:99] nul\\x00byte\n", tid);
   EXPECT_EQ(
       expected,
       formatMsg(
           LogLevel::CRITICAL,
           std::string("nul\0byte", 8),
           "escapes.cpp",
           99,
           "testFunction"));
 }