proxygen: proxygen/lib/utils/test/HTTPTimeTest.cpp File Reference
HTTPTimeTest.cpp File Reference
#include <folly/portability/GTest.h>
#include <proxygen/lib/utils/HTTPTime.h>
Functions
TEST (HTTPTimeTests, InvalidTimeTest)
TEST (HTTPTimeTests, ValidTimeTest)
TEST (HTTPTimeTests, EqualTimeTest)
TEST (HTTPTimeTests, ReallyOldTimeTest)
TEST (HTTPTimeTests, TzToUnixTsTest)
Function Documentation
TEST (HTTPTimeTests , InvalidTimeTest)
Definition at line 15 of file HTTPTimeTest.cpp.
References EXPECT_FALSE, and proxygen::parseHTTPDateTime().
{
   EXPECT_FALSE(parseHTTPDateTime("Hello, World").hasValue());
   EXPECT_FALSE(parseHTTPDateTime("Sun, 33 Nov 1994 08:49:37 GMT").hasValue());
   EXPECT_FALSE(parseHTTPDateTime("Sun, 06 Nov 1800").hasValue());
 }
TEST (HTTPTimeTests , ValidTimeTest)
Definition at line 21 of file HTTPTimeTest.cpp.
References EXPECT_TRUE, and proxygen::parseHTTPDateTime().
{
   // From http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.3
   EXPECT_TRUE(parseHTTPDateTime("Sun, 06 Nov 1994 08:49:37 GMT").hasValue());
   EXPECT_TRUE(parseHTTPDateTime("Sunday, 06-Nov-94 08:49:37 GMT").hasValue());
   EXPECT_TRUE(parseHTTPDateTime("Sun Nov  6 08:49:37 1994").hasValue());
 }
TEST (HTTPTimeTests , EqualTimeTest)
Definition at line 28 of file HTTPTimeTest.cpp.
References a, b, c, EXPECT_EQ, EXPECT_TRUE, and proxygen::parseHTTPDateTime().
{
   auto a = parseHTTPDateTime("Thu, 07 Mar 2013 08:49:37 GMT");
   EXPECT_TRUE(a.hasValue());
   auto b = parseHTTPDateTime("Thursday, 07-Mar-13 08:49:37 GMT");
   EXPECT_TRUE(b.hasValue());
   auto c = parseHTTPDateTime("Thu Mar 7 08:49:37 2013");
   EXPECT_TRUE(c.hasValue());
   EXPECT_EQ(a.value(), b.value());
   EXPECT_EQ(a.value(), c.value());
   EXPECT_EQ(b.value(), c.value());
 }
TEST (HTTPTimeTests , ReallyOldTimeTest)
Definition at line 41 of file HTTPTimeTest.cpp.
References a, b, c, EXPECT_LT, EXPECT_TRUE, and proxygen::parseHTTPDateTime().
{
   auto a = parseHTTPDateTime("Thu, 07 Mar 1770 08:49:37 GMT");
   EXPECT_TRUE(a.hasValue());
   auto b = parseHTTPDateTime("Thu, 07 Mar 1771 08:49:37 GMT");
   EXPECT_TRUE(b.hasValue());
   auto c = parseHTTPDateTime("Thu, 07 Mar 1980 08:49:37 GMT");
   EXPECT_TRUE(c.hasValue());
   EXPECT_LT(a, b);
   EXPECT_LT(a, c);
   EXPECT_LT(b, c);
 }
TEST (HTTPTimeTests , TzToUnixTsTest)
Definition at line 54 of file HTTPTimeTest.cpp.
References a, b, c, EXPECT_EQ, EXPECT_FALSE, f, g(), h, i, k, m, and proxygen::parseHTTPDateTime().
{
   auto a = parseHTTPDateTime("Wed, 13 Jun 2018 21:43:49 GMT");
   EXPECT_EQ(a.value(), 1528926229);
   auto b = parseHTTPDateTime("Wed, 31 Dec 1969 23:59:59 GMT");
   EXPECT_EQ(b.value(), -1);
   auto c = parseHTTPDateTime("Thu, 01 Jan 1970 00:00:00 GMT");
   EXPECT_EQ(c.value(), 0);
   auto d = parseHTTPDateTime("Thu, 01 Jan 1970 00:00:01 GMT");
   EXPECT_EQ(d.value(), 1);
   auto e = parseHTTPDateTime("Wed, 13-Jun-18 21:43:49 GMT");
   EXPECT_EQ(e.value(), 1528926229);
   auto f = parseHTTPDateTime("Wed, 31-Dec-69 23:59:59 GMT");
   EXPECT_EQ(f.value(), -1);
   auto g = parseHTTPDateTime("Wed, 01-Jan-70 00:00:00 GMT");
   EXPECT_EQ(g.value(), 0);
   auto h = parseHTTPDateTime("Thu, 01-Jan-70 00:00:01 GMT");
   EXPECT_EQ(h.value(), 1);
   auto i = parseHTTPDateTime("Wed Jun 13 21:43:49 2018");
   EXPECT_EQ(i.value(), 1528926229);
   auto j = parseHTTPDateTime("Wed Dec 31 23:59:59 1969");
   EXPECT_EQ(j.value(), -1);
   auto k = parseHTTPDateTime("Thu Jan 1 00:00:00 1970");
   EXPECT_EQ(k.value(), 0);
   auto l = parseHTTPDateTime("Thu Jan 1 00:00:01 1970");
   EXPECT_EQ(l.value(), 1);
   auto m = parseHTTPDateTime("Tue, 19 Jan 2038 03:14:07 GMT");
   EXPECT_EQ(m.value(), 2147483647);
   auto n = parseHTTPDateTime("Thu, 01 Jan 1970 00:00:01 PST");
   EXPECT_FALSE(n.hasValue());
   auto o = parseHTTPDateTime("Thu, 01 Jan 1970 00:00:01");
   EXPECT_FALSE(o.hasValue());
 }