proxygen: proxygen/lib/http/test/HTTPCommonHeadersTests.cpp File Reference
HTTPCommonHeadersTests.cpp File Reference
#include <folly/portability/GTest.h>
#include <proxygen/lib/http/HTTPCommonHeaders.h>
Classes
class HTTPCommonHeadersTests
Functions
TEST_F (HTTPCommonHeadersTests, TestHashing)
TEST_F (HTTPCommonHeadersTests, TestTwoTablesInitialized)
TEST_F (HTTPCommonHeadersTests, TestIsCommonHeaderNameFromTable)
TEST_F (HTTPCommonHeadersTests, TestGetHeaderCodeFromTableCommonHeaderName)
Function Documentation
TEST_F (HTTPCommonHeadersTests , TestHashing)
Definition at line 18 of file HTTPCommonHeadersTests.cpp.
References EXPECT_EQ, EXPECT_NE, proxygen::HTTPCommonHeaders::hash(), proxygen::HTTP_HEADER_OTHER, and string.
{
   std::string common1("Content-Length");
   std::string common2("content-length");
   std::string uncommon("Uncommon");
   HTTPHeaderCode commonCode1 = HTTPCommonHeaders::hash(common1);
   HTTPHeaderCode commonCode2 = HTTPCommonHeaders::hash(common2);
   HTTPHeaderCode uncommonCode = HTTPCommonHeaders::hash(uncommon);
   EXPECT_EQ(uncommonCode, HTTPHeaderCode::HTTP_HEADER_OTHER);
   EXPECT_NE(commonCode1, HTTPHeaderCode::HTTP_HEADER_OTHER);
   EXPECT_EQ(commonCode1, commonCode2);
 }
TEST_F (HTTPCommonHeadersTests , TestTwoTablesInitialized)
Definition at line 33 of file HTTPCommonHeadersTests.cpp.
References EXPECT_EQ, proxygen::HTTPCommonHeaders::getPointerToHeaderName(), proxygen::HTTPCommonHeaders::hash(), string, and proxygen::TABLE_LOWERCASE.
{
   std::string common("Content-Length");
   HTTPHeaderCode code = HTTPCommonHeaders::hash(common);
   EXPECT_EQ(*HTTPCommonHeaders::getPointerToHeaderName(code), "Content-Length");
   EXPECT_EQ(
     *HTTPCommonHeaders::getPointerToHeaderName(
       code, HTTPCommonHeaderTableType::TABLE_LOWERCASE), "content-length");
 }
TEST_F (HTTPCommonHeadersTests , TestIsCommonHeaderNameFromTable)
Definition at line 43 of file HTTPCommonHeadersTests.cpp.
References EXPECT_FALSE, EXPECT_TRUE, proxygen::HTTPCommonHeaders::getPointerToHeaderName(), proxygen::HTTP_HEADER_NONE, proxygen::HTTP_HEADER_OTHER, proxygen::HTTPHeaderCodeCommonOffset, proxygen::HTTPCommonHeaders::isHeaderNameFromTable(), proxygen::HTTPCommonHeaders::num_header_codes, string, and proxygen::TABLE_CAMELCASE.
{
   // The first two hardcoded headers are not considered actual common headers
   EXPECT_FALSE(
     HTTPCommonHeaders::isHeaderNameFromTable(
       HTTPCommonHeaders::getPointerToHeaderName(HTTP_HEADER_NONE),
       TABLE_CAMELCASE));
   EXPECT_FALSE(
     HTTPCommonHeaders::isHeaderNameFromTable(
       HTTPCommonHeaders::getPointerToHeaderName(HTTP_HEADER_OTHER),
       TABLE_CAMELCASE));
   // Verify that the first actual common header in the address table checks out
   // Assuming there is at least one common header in the table (first two
   // entries are HTTP_HEADER_NONE and HTTP_HEADER_OTHER)
   if (HTTPCommonHeaders::num_header_codes > HTTPHeaderCodeCommonOffset) {
     EXPECT_TRUE(
       HTTPCommonHeaders::isHeaderNameFromTable(
         HTTPCommonHeaders::getPointerToHeaderName(
           static_cast<HTTPHeaderCode>(HTTPHeaderCodeCommonOffset + 1)),
         TABLE_CAMELCASE));
     // Verify that the last header in the common address table checks out
     EXPECT_TRUE(
       HTTPCommonHeaders::isHeaderNameFromTable(
         HTTPCommonHeaders::getPointerToHeaderName(
           static_cast<HTTPHeaderCode>(
             HTTPCommonHeaders::num_header_codes - 1)), TABLE_CAMELCASE));
   }
   // Verify that a random header is not identified as being part of the common
   // address table
   std::string externalHeader = "externalHeader";
   EXPECT_FALSE(HTTPCommonHeaders::isHeaderNameFromTable(
     &externalHeader, TABLE_CAMELCASE));
 }
TEST_F (HTTPCommonHeadersTests , TestGetHeaderCodeFromTableCommonHeaderName)
Definition at line 79 of file HTTPCommonHeadersTests.cpp.
References EXPECT_TRUE, proxygen::HTTPCommonHeaders::getHeaderCodeFromTableCommonHeaderName(), proxygen::HTTPCommonHeaders::getPointerToHeaderName(), proxygen::HTTP_HEADER_OTHER, proxygen::HTTPHeaderCodeCommonOffset, proxygen::HTTPCommonHeaders::num_header_codes, string, proxygen::TABLE_CAMELCASE, and uint64_t.
{
   for (uint64_t j = HTTPHeaderCodeCommonOffset;
        j < HTTPCommonHeaders::num_header_codes; ++j) {
     HTTPHeaderCode code = static_cast<HTTPHeaderCode>(j);
     EXPECT_TRUE(
       code ==
       HTTPCommonHeaders::getHeaderCodeFromTableCommonHeaderName(
         HTTPCommonHeaders::getPointerToHeaderName(code), TABLE_CAMELCASE));
   }
   std::string externalHeader = "externalHeader";
   EXPECT_TRUE(HTTP_HEADER_OTHER ==
     HTTPCommonHeaders::getHeaderCodeFromTableCommonHeaderName(
       &externalHeader, TABLE_CAMELCASE));
 }