proxygen: proxygen/folly/folly/logging/test/InitTest.cpp File Reference
InitTest.cpp File Reference
#include <folly/logging/Init.h>
#include <folly/logging/LogConfigParser.h>
#include <folly/logging/LoggerDB.h>
#include <folly/logging/test/ConfigHelpers.h>
#include <folly/portability/GFlags.h>
#include <folly/portability/GTest.h>
#include <folly/test/TestUtils.h>
Namespaces
folly
—— Concurrent Priority Queue Implementation ——
Functions
const char * folly::getBaseLoggingConfig ()
TEST (Init, checkConfig)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 83 of file InitTest.cpp.
References testing::InitGoogleTest(), and RUN_ALL_TESTS().
{
   ::testing::InitGoogleTest(&argc, argv);
   gflags::ParseCommandLineFlags(&argc, &argv, /* remove_flags = */ true);
   return RUN_ALL_TESTS();
 }
TEST (Init , checkConfig)
Definition at line 44 of file InitTest.cpp.
References EXPECT_EQ, EXPECT_THROW_RE, folly::LoggerDB::get(), folly::LoggerDB::getConfig(), folly::initLogging(), and folly::parseLogConfig().
{
   // Before we call initLogging(), the LoggerDB will have the default
   // configuration provided by initializeLoggerDB().
   auto initialConfig = folly::LoggerDB::get().getConfig();
   EXPECT_EQ(0, getBaseLoggingConfigCalled);
   EXPECT_EQ(
       parseLogConfig(".:=INFO:default; "
                      "default=stream:stream=stderr,async=false"),
       LoggerDB::get().getConfig());
   // Call initLogging()
   // Make sure it merges the supplied config argument with our custom
   // base configuration.
   initLogging(".=ERROR,folly.logging=DBG7");
   EXPECT_EQ(1, getBaseLoggingConfigCalled);
   EXPECT_EQ(
       parseLogConfig(".:=ERROR:default,folly=INFO:,folly.logging=DBG7:; "
                      "default=stream:stream=stdout,async=false"),
       LoggerDB::get().getConfig());
   // Test calling initLogging() with bad configuration strings, and
   // configured such that it should throw an exception on error rather than
   // exiting.
   //
   // Note that it is okay to call initLogging() multiple times (we already
   // called it successfully once above), but this isn't really something to
   // expect most callers to want to do.
   EXPECT_THROW_RE(
       initLogging(".=BOGUSLEVEL"),
       folly::LogConfigParseError,
       R"(invalid log level "BOGUSLEVEL")");
   EXPECT_THROW_RE(
       initLogging(".=ERR:undefined_handler"),
       std::invalid_argument,
       R"(unknown log handler "undefined_handler")");
 }