proxygen: proxygen/folly/folly/futures/test/InterruptTest.cpp File Reference
InterruptTest.cpp File Reference
#include <folly/futures/Future.h>
#include <folly/futures/Promise.h>
#include <folly/portability/GTest.h>
#include <folly/synchronization/Baton.h>
Functions
TEST (Interrupt, raise)
TEST (Interrupt, cancel)
TEST (Interrupt, handleThenInterrupt)
TEST (Interrupt, interruptThenHandle)
TEST (Interrupt, interruptAfterFulfilNoop)
TEST (Interrupt, secondInterruptNoop)
TEST (Interrupt, futureWithinTimedOut)
TEST (Interrupt, semiFutureWithinTimedOut)
Function Documentation
TEST (Interrupt , raise)
Definition at line 24 of file InterruptTest.cpp.
References EXPECT_THROW, folly::Promise< T >::getFuture(), folly::Promise< T >::setInterruptHandler(), and folly::exception_wrapper::throw_exception().
{
   using eggs_t = std::runtime_error;
   Promise<Unit> p;
   p.setInterruptHandler([&](const exception_wrapper& e) {
     EXPECT_THROW(e.throw_exception(), eggs_t);
   });
   p.getFuture().raise(eggs_t("eggs"));
 }
TEST (Interrupt , cancel)
Definition at line 33 of file InterruptTest.cpp.
References EXPECT_THROW, folly::Promise< T >::getFuture(), folly::Promise< T >::setInterruptHandler(), and folly::exception_wrapper::throw_exception().
{
   Promise<Unit> p;
   p.setInterruptHandler([&](const exception_wrapper& e) {
     EXPECT_THROW(e.throw_exception(), FutureCancellation);
   });
   p.getFuture().cancel();
 }
TEST (Interrupt , handleThenInterrupt)
Definition at line 41 of file InterruptTest.cpp.
References EXPECT_TRUE, flag, folly::Promise< T >::getFuture(), and folly::Promise< T >::setInterruptHandler().
{
   Promise<int> p;
   bool flag = false;
   p.setInterruptHandler([&](const exception_wrapper& /* e */) { flag = true; });
   p.getFuture().cancel();
   EXPECT_TRUE(flag);
 }
TEST (Interrupt , interruptThenHandle)
Definition at line 49 of file InterruptTest.cpp.
References EXPECT_TRUE, flag, folly::Promise< T >::getFuture(), and folly::Promise< T >::setInterruptHandler().
{
   Promise<int> p;
   bool flag = false;
   p.getFuture().cancel();
   p.setInterruptHandler([&](const exception_wrapper& /* e */) { flag = true; });
   EXPECT_TRUE(flag);
 }
TEST (Interrupt , interruptAfterFulfilNoop)
Definition at line 57 of file InterruptTest.cpp.
References EXPECT_FALSE, flag, folly::Promise< T >::getFuture(), folly::Promise< T >::setInterruptHandler(), and folly::Promise< T >::setValue().
{
   Promise<Unit> p;
   bool flag = false;
   p.setInterruptHandler([&](const exception_wrapper& /* e */) { flag = true; });
   p.setValue();
   p.getFuture().cancel();
   EXPECT_FALSE(flag);
 }
TEST (Interrupt , secondInterruptNoop)
Definition at line 66 of file InterruptTest.cpp.
References count, EXPECT_EQ, f, folly::Promise< T >::getFuture(), and folly::Promise< T >::setInterruptHandler().
{
   Promise<Unit> p;
   int count = 0;
   p.setInterruptHandler([&](const exception_wrapper& /* e */) { count++; });
   auto f = p.getFuture();
   f.cancel();
   f.cancel();
   EXPECT_EQ(1, count);
 }
TEST (Interrupt , futureWithinTimedOut)
Definition at line 76 of file InterruptTest.cpp.
References EXPECT_TRUE, folly::Promise< T >::getFuture(), folly::Baton< MayBlock, Atom >::post(), folly::Promise< T >::setInterruptHandler(), and folly::Baton< MayBlock, Atom >::try_wait_for().
{
   Promise<int> p;
   Baton<> done;
   p.setInterruptHandler([&](const exception_wrapper& /* e */) { done.post(); });
   p.getFuture().within(std::chrono::milliseconds(1));
   // Give it 100ms to time out and call the interrupt handler
   EXPECT_TRUE(done.try_wait_for(std::chrono::milliseconds(100)));
 }
TEST (Interrupt , semiFutureWithinTimedOut)
Definition at line 85 of file InterruptTest.cpp.
References EXPECT_TRUE, folly::Promise< T >::getSemiFuture(), folly::Baton< MayBlock, Atom >::post(), folly::Promise< T >::setInterruptHandler(), and folly::Baton< MayBlock, Atom >::try_wait_for().
{
   Promise<int> p;
   Baton<> done;
   p.setInterruptHandler([&](const exception_wrapper& /* e */) { done.post(); });
   p.getSemiFuture().within(std::chrono::milliseconds(1));
   // Give it 100ms to time out and call the interrupt handler
   EXPECT_TRUE(done.try_wait_for(std::chrono::milliseconds(100)));
 }