proxygen: proxygen/folly/folly/io/test/IOBufBenchmark.cpp File Reference
IOBufBenchmark.cpp File Reference
#include <folly/Benchmark.h>
#include <folly/io/IOBuf.h>
Functions
BENCHMARK (cloneOneBenchmark, iters)
BENCHMARK (cloneOneIntoBenchmark, iters)
BENCHMARK (cloneBenchmark, iters)
BENCHMARK (cloneIntoBenchmark, iters)
BENCHMARK (moveBenchmark, iters)
BENCHMARK (copyBenchmark, iters)
BENCHMARK (cloneCoalescedBaseline, iters)
BENCHMARK_RELATIVE (cloneCoalescedBenchmark, iters)
int main (int argc, char **argv)
Function Documentation
BENCHMARK (cloneOneBenchmark , iters)
Definition at line 22 of file IOBufBenchmark.cpp.
References folly::IOBuf::cloneOne(), folly::copy(), CREATE, and folly::doNotOptimizeAway().
{
   IOBuf buf(IOBuf::CREATE, 10);
   while (iters--) {
     auto copy = buf.cloneOne();
     folly::doNotOptimizeAway(copy->capacity());
   }
 }
BENCHMARK (cloneOneIntoBenchmark , iters)
Definition at line 30 of file IOBufBenchmark.cpp.
References folly::IOBuf::capacity(), folly::IOBuf::cloneOneInto(), folly::copy(), CREATE, and folly::doNotOptimizeAway().
{
   IOBuf buf(IOBuf::CREATE, 10);
   IOBuf copy;
   while (iters--) {
     buf.cloneOneInto(copy);
     folly::doNotOptimizeAway(copy.capacity());
   }
 }
BENCHMARK (cloneBenchmark , iters)
Definition at line 39 of file IOBufBenchmark.cpp.
References folly::IOBuf::clone(), folly::copy(), CREATE, and folly::doNotOptimizeAway().
{
   IOBuf buf(IOBuf::CREATE, 10);
   while (iters--) {
     auto copy = buf.clone();
     folly::doNotOptimizeAway(copy->capacity());
   }
 }
BENCHMARK (cloneIntoBenchmark , iters)
Definition at line 47 of file IOBufBenchmark.cpp.
References folly::IOBuf::capacity(), folly::IOBuf::cloneInto(), folly::copy(), CREATE, and folly::doNotOptimizeAway().
{
   IOBuf buf(IOBuf::CREATE, 10);
   IOBuf copy;
   while (iters--) {
     buf.cloneInto(copy);
     folly::doNotOptimizeAway(copy.capacity());
   }
 }
BENCHMARK (moveBenchmark , iters)
Definition at line 56 of file IOBufBenchmark.cpp.
References CREATE, folly::doNotOptimizeAway(), and folly::gen::move.
{
   IOBuf buf(IOBuf::CREATE, 10);
   while (iters--) {
     auto tmp = std::move(buf);
     folly::doNotOptimizeAway(tmp.capacity());
     buf = std::move(tmp);
   }
 }
BENCHMARK (copyBenchmark , iters)
Definition at line 65 of file IOBufBenchmark.cpp.
References folly::copy(), CREATE, and folly::doNotOptimizeAway().
{
   IOBuf buf(IOBuf::CREATE, 10);
   while (iters--) {
     auto copy = buf;
     folly::doNotOptimizeAway(copy.capacity());
   }
 }
BENCHMARK (cloneCoalescedBaseline , iters)
Definition at line 73 of file IOBufBenchmark.cpp.
References folly::IOBuf::cloneAsValue(), folly::IOBuf::coalesce(), and folly::doNotOptimizeAway().
{
   std::unique_ptr<IOBuf> buf = IOBuf::createChain(100, 10);
   while (iters--) {
     auto clone = buf->cloneAsValue();
     clone.coalesce();
     folly::doNotOptimizeAway(clone.capacity());
   }
 }
BENCHMARK_RELATIVE (cloneCoalescedBenchmark , iters)
Definition at line 82 of file IOBufBenchmark.cpp.
References folly::IOBuf::cloneCoalescedAsValue(), folly::copy(), and folly::doNotOptimizeAway().
{
   std::unique_ptr<IOBuf> buf = IOBuf::createChain(100, 10);
   while (iters--) {
     auto copy = buf->cloneCoalescedAsValue();
     folly::doNotOptimizeAway(copy.capacity());
   }
 }
int main (int argc, char ** argv)
============================================================================
folly/io/test/IOBufBenchmark.cpp relative time/iter iters/s
cloneOneBenchmark 49.03ns 20.39M cloneOneIntoBenchmark 26.36ns 37.93M cloneBenchmark 49.43ns 20.23M cloneIntoBenchmark 30.03ns 33.30M moveBenchmark 15.35ns 65.14M copyBenchmark 33.63ns 29.73M cloneCoalescedBaseline 344.33ns 2.90M
cloneCoalescedBenchmark 605.62% 56.86ns 17.59M
Definition at line 105 of file IOBufBenchmark.cpp.
References folly::runBenchmarks().
{
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   folly::runBenchmarks();
   return 0;
 }