proxygen: proxygen/folly/folly/io/test/IOBufCursorBenchmark.cpp File Reference
IOBufCursorBenchmark.cpp File Reference
#include <folly/io/IOBuf.h>
#include <folly/Benchmark.h>
#include <folly/Format.h>
#include <folly/Range.h>
#include <folly/io/Cursor.h>
Functions
DECLARE_bool (benchmark)
template<class CursClass >
void runBenchmark ()
BENCHMARK (rwPrivateCursorBenchmark, iters)
BENCHMARK (rwUnshareCursorBenchmark, iters)
BENCHMARK (cursorBenchmark, iters)
BENCHMARK (skipBenchmark, iters)
BENCHMARK (cloneBenchmark, iters)
BENCHMARK (read, iters)
BENCHMARK (readSlow, iters)
bool prefixBaseline (Cursor &c, const std::array< uint8_t, 4 > &expected)
bool prefix (Cursor &c, uint32_t expected)
BENCHMARK (prefixBaseline, iters)
BENCHMARK_RELATIVE (prefix, iters)
int main (int argc, char **argv)
Variables
int benchmark_size = 1000
unique_ptr< IOBuf > iobuf_benchmark
unique_ptr< IOBuf > iobuf_read_benchmark
Function Documentation
BENCHMARK (rwPrivateCursorBenchmark , iters)
Definition at line 47 of file IOBufCursorBenchmark.cpp.
{
   while (iters--) {
     runBenchmark<RWPrivateCursor>();
   }
 }
BENCHMARK (rwUnshareCursorBenchmark , iters)
Definition at line 53 of file IOBufCursorBenchmark.cpp.
{
   while (iters--) {
     runBenchmark<RWUnshareCursor>();
   }
 }
BENCHMARK (cursorBenchmark , iters)
Definition at line 59 of file IOBufCursorBenchmark.cpp.
References benchmark_size, c, i, and uint8_t.
{
   while (iters--) {
     Cursor c(iobuf_read_benchmark.get());
     for (int i = 0; i < benchmark_size; i++) {
       c.read<uint8_t>();
     }
   }
 }
BENCHMARK (skipBenchmark , iters)
Definition at line 68 of file IOBufCursorBenchmark.cpp.
References benchmark_size, c, and i.
{
   while (iters--) {
     Cursor c(iobuf_read_benchmark.get());
     for (int i = 0; i < benchmark_size; i++) {
       c.peekBytes();
       c.skip(1);
     }
   }
 }
BENCHMARK (cloneBenchmark , iters)
Definition at line 78 of file IOBufCursorBenchmark.cpp.
References benchmark_size, c, and i.
{
   folly::IOBuf out;
   while (iters--) {
     Cursor c(iobuf_read_benchmark.get());
     for (int i = 0; i < benchmark_size; ++i) {
       c.clone(out, 1);
     }
   }
 }
BENCHMARK (read , iters)
Definition at line 88 of file IOBufCursorBenchmark.cpp.
References benchmark_size, c, folly::doNotOptimizeAway(), i, uint8_t, and val.
{
   while (iters--) {
     Cursor c(iobuf_read_benchmark.get());
     for (int i = 0; i < benchmark_size; ++i) {
       const auto val = c.read<uint8_t>();
       folly::doNotOptimizeAway(val);
     }
   }
 }
BENCHMARK (readSlow , iters)
Definition at line 98 of file IOBufCursorBenchmark.cpp.
References benchmark_size, c, folly::doNotOptimizeAway(), i, folly::size(), uint16_t, and val.
{
   while (iters--) {
     Cursor c(iobuf_read_benchmark.get());
     const int size = benchmark_size / 2;
     for (int i = 0; i < size; ++i) {
       const auto val = c.read<uint16_t>();
       folly::doNotOptimizeAway(val);
     }
   }
 }
BENCHMARK (prefixBaseline , iters)
Definition at line 125 of file IOBufCursorBenchmark.cpp.
References benchmark_size, c, folly::IOBuf::CREATE, folly::doNotOptimizeAway(), i, prefix(), and prefixBaseline().
{
   IOBuf buf{IOBuf::CREATE, 10};
   buf.append(10);
   constexpr std::array<uint8_t, 4> prefix = {{0x01, 0x02, 0x03, 0x04}};
   while (iters--) {
     for (int i = 0; i < benchmark_size; ++i) {
       Cursor c(&buf);
       bool result = prefixBaseline(c, prefix);
       folly::doNotOptimizeAway(result);
     }
   }
 }
BENCHMARK_RELATIVE (prefix , iters)
Definition at line 138 of file IOBufCursorBenchmark.cpp.
References benchmark_size, c, folly::IOBuf::CREATE, folly::doNotOptimizeAway(), i, and prefix().
{
   IOBuf buf{IOBuf::CREATE, 10};
   buf.append(10);
   while (iters--) {
     for (int i = 0; i < benchmark_size; ++i) {
       Cursor c(&buf);
       bool result = prefix(c, 0x01020304);
       folly::doNotOptimizeAway(result);
     }
   }
 }
DECLARE_bool (benchmark)
int main (int argc, char ** argv)
============================================================================
folly/io/test/IOBufCursorBenchmark.cpp relative time/iter iters/s
rwPrivateCursorBenchmark 1.01us 985.85K rwUnshareCursorBenchmark 1.01us 986.70K cursorBenchmark 4.77us 209.61K skipBenchmark 4.78us 209.42K cloneBenchmark 26.65us 37.52K read 4.35us 230.07K readSlow 5.45us 183.48K prefixBaseline 6.44us 155.24K
prefix 589.31% 1.09us 914.87K
Definition at line 166 of file IOBufCursorBenchmark.cpp.
References folly::IOBuf::append(), benchmark_size, folly::IOBuf::create(), i, folly::gen::move, folly::IOBuf::prependChain(), and folly::runBenchmarks().
{
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   iobuf_benchmark = IOBuf::create(benchmark_size);
   iobuf_benchmark->append(benchmark_size);
   iobuf_read_benchmark = IOBuf::create(1);
   for (int i = 0; i < benchmark_size; i++) {
     unique_ptr<IOBuf> iobuf2(IOBuf::create(1));
     iobuf2->append(1);
     iobuf_read_benchmark->prependChain(std::move(iobuf2));
   }
   folly::runBenchmarks();
   return 0;
 }
bool prefix (Cursor & c, uint32_t expected)
Definition at line 117 of file IOBufCursorBenchmark.cpp.
References folly::io::detail::CursorBase< Derived, BufType >::tryReadLE(), and uint32_t.
Referenced by testing::gmock_generated_actions_test::ACTION_P2(), folly::gen::detail::SplitStringSource< DelimiterType >::apply(), BENCHMARK(), BENCHMARK_RELATIVE(), testing::internal::CodeLocation::CodeLocation(), testing::ContainsRegex(), testing::gmock_matchers_test::EMString(), folly::json::escapeStringImpl(), folly::exception_tracer::getCurrentExceptions(), folly::IPAddressV4::longestCommonPrefix(), folly::IPAddressV6::longestCommonPrefix(), testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::Impl< T >::MatchAndExplain(), testing::gmock_matchers_test::MATCHER_P(), message_for_terminate_with(), folly::gen::StreamSplitter< Callback >::operator()(), folly::operator<(), ReadStats::parseMessage(), testing::gmock_generated_actions_test::SubstractAction::Perform(), folly::SocketAddress::prefixMatch(), testing::internal::PrintOnOneLine(), testing::gtest_printers_test::PrintPointer(), TEST(), testing::gmock_matchers_test::TEST_F(), folly::io::test::TEST_P(), testing::gmock_matchers_test::FloatingPointNearTest< RawType >::TestNearMatches(), folly::toSubprocessSpawnErrorMessage(), folly::hash::SpookyHashV1::Update(), folly::hash::SpookyHashV2::Update(), and vprintfCheck().
{
   uint32_t actual;
   if (!c.tryReadLE(actual)) {
     return false;
   }
   return actual == expected;
 }
bool prefixBaseline (Cursor & c, const std::array< uint8_t, 4 > & expected)
Definition at line 109 of file IOBufCursorBenchmark.cpp.
References folly::io::detail::CursorBase< Derived, BufType >::pullAtMost().
Referenced by BENCHMARK().
{
   std::array<uint8_t, 4> actual;
   if (c.pullAtMost(actual.data(), actual.size()) != actual.size()) {
     return false;
   }
   return memcmp(actual.data(), expected.data(), actual.size()) == 0;
 }
template<class CursClass > void runBenchmark ()
Definition at line 39 of file IOBufCursorBenchmark.cpp.
References benchmark_size, c, i, and uint8_t.
                     {
   CursClass c(iobuf_benchmark.get());
   for (int i = 0; i < benchmark_size; i++) {
     c.write((uint8_t)0);
   }
 }
Variable Documentation
int benchmark_size = 1000
Definition at line 33 of file IOBufCursorBenchmark.cpp.
Referenced by BENCHMARK(), BENCHMARK_RELATIVE(), main(), and runBenchmark().
unique_ptr<IOBuf> iobuf_benchmark
Definition at line 34 of file IOBufCursorBenchmark.cpp.
unique_ptr<IOBuf> iobuf_read_benchmark
Definition at line 36 of file IOBufCursorBenchmark.cpp.