proxygen: proxygen/folly/folly/test/IPAddressBenchmark.cpp File Reference
IPAddressBenchmark.cpp File Reference
#include <folly/Format.h>
#include <folly/IPAddress.h>
#include <glog/logging.h>
#include <folly/Benchmark.h>
Functions
BENCHMARK (ipv4_to_string_inet_ntop, iters)
BENCHMARK_RELATIVE (ipv4_to_fully_qualified, iters)
BENCHMARK_DRAW_LINE ()
BENCHMARK (ipv4_to_fully_qualified_port, iters)
BENCHMARK_RELATIVE (ipv4_append_to_fully_qualified_port, iters)
BENCHMARK (ipv6_to_string_inet_ntop, iters)
BENCHMARK_RELATIVE (ipv6_to_fully_qualified, iters)
BENCHMARK (ipv6_to_fully_qualified_port, iters)
BENCHMARK_RELATIVE (ipv6_append_to_fully_qualified_port, iters)
BENCHMARK (ipv6_ctor_valid, iters)
BENCHMARK_RELATIVE (ipv6_ctor_invalid, iters)
BENCHMARK (ipv6_try_from_string_valid, iters)
BENCHMARK_RELATIVE (ipv6_try_from_string_invalid, iters)
int main (int argc, char *argv[])
Function Documentation
BENCHMARK (ipv4_to_string_inet_ntop , iters)
Definition at line 27 of file IPAddressBenchmark.cpp.
References folly::doNotOptimizeAway(), folly::IPAddressV4::toAddr(), and val.
{
   folly::IPAddressV4 ipv4Addr("127.0.0.1");
   in_addr ip = ipv4Addr.toAddr();
   char outputString[INET_ADDRSTRLEN] = {0};
   while (iters--) {
     const char* val =
         inet_ntop(AF_INET, &ip, outputString, sizeof(outputString));
     folly::doNotOptimizeAway(val);
   }
 }
BENCHMARK (ipv4_to_fully_qualified_port , iters)
Definition at line 50 of file IPAddressBenchmark.cpp.
References folly::doNotOptimizeAway(), folly::sformat(), and folly::IPAddressV4::toFullyQualified().
{
   IPAddressV4 ip("255.255.255.255");
   while (iters--) {
     string outputString = folly::sformat("{}:{}", ip.toFullyQualified(), 65535);
     folly::doNotOptimizeAway(outputString);
     folly::doNotOptimizeAway(outputString.data());
   }
 }
BENCHMARK (ipv6_to_string_inet_ntop , iters)
Definition at line 74 of file IPAddressBenchmark.cpp.
References folly::doNotOptimizeAway(), folly::IPAddressV6::toAddr(), and val.
{
   IPAddressV6 ipv6Addr("F1E0:0ACE:FB94:7ADF:22E8:6DE6:9672:3725");
   in6_addr ip = ipv6Addr.toAddr();
   char outputString[INET6_ADDRSTRLEN] = {0};
   while (iters--) {
     const char* val =
         inet_ntop(AF_INET6, &ip, outputString, sizeof(outputString));
     folly::doNotOptimizeAway(val);
   }
 }
BENCHMARK (ipv6_to_fully_qualified_port , iters)
Definition at line 97 of file IPAddressBenchmark.cpp.
References folly::doNotOptimizeAway(), folly::sformat(), and folly::IPAddressV6::toFullyQualified().
{
   IPAddressV6 ip("F1E0:0ACE:FB94:7ADF:22E8:6DE6:9672:3725");
   while (iters--) {
     string outputString = folly::sformat("{}:{}", ip.toFullyQualified(), 65535);
     folly::doNotOptimizeAway(outputString);
     folly::doNotOptimizeAway(outputString.data());
   }
 }
BENCHMARK (ipv6_ctor_valid , iters)
Definition at line 121 of file IPAddressBenchmark.cpp.
References folly::doNotOptimizeAway().
{
   while (iters--) {
     try {
       IPAddressV6 ip("2803:6082:18e0:2c49:1a23:9ee0:5c87:9800");
       doNotOptimizeAway(ip);
     } catch (const IPAddressFormatException& ex) {
       doNotOptimizeAway(ex);
     }
   }
 }
BENCHMARK (ipv6_try_from_string_valid , iters)
Definition at line 145 of file IPAddressBenchmark.cpp.
References folly::doNotOptimizeAway(), and folly::IPAddressV6::tryFromString().
{
   while (iters--) {
     auto maybeIp =
         IPAddressV6::tryFromString("2803:6082:18e0:2c49:1a23:9ee0:5c87:9800");
     CHECK(maybeIp.hasValue());
     doNotOptimizeAway(maybeIp);
     doNotOptimizeAway(maybeIp.value());
   }
 }
BENCHMARK_DRAW_LINE ()
BENCHMARK_RELATIVE (ipv4_to_fully_qualified , iters)
Definition at line 39 of file IPAddressBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE(), folly::doNotOptimizeAway(), and folly::IPAddressV4::toFullyQualified().
{
   IPAddressV4 ip("127.0.0.1");
   while (iters--) {
     string outputString = ip.toFullyQualified();
     folly::doNotOptimizeAway(outputString);
     folly::doNotOptimizeAway(outputString.data());
   }
 }
BENCHMARK_RELATIVE (ipv4_append_to_fully_qualified_port , iters)
Definition at line 59 of file IPAddressBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE(), folly::doNotOptimizeAway(), folly::IPAddressV4::kMaxToFullyQualifiedSize, folly::toAppend(), and folly::IPAddressV4::toFullyQualifiedAppend().
{
   IPAddressV4 ip("255.255.255.255");
   while (iters--) {
     string outputString;
     outputString.reserve(IPAddressV4::kMaxToFullyQualifiedSize + 1 + 5);
     ip.toFullyQualifiedAppend(outputString);
     outputString += ':';
     folly::toAppend(65535, &outputString);
     folly::doNotOptimizeAway(outputString);
     folly::doNotOptimizeAway(outputString.data());
   }
 }
BENCHMARK_RELATIVE (ipv6_to_fully_qualified , iters)
Definition at line 86 of file IPAddressBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE(), folly::doNotOptimizeAway(), and folly::IPAddressV6::toFullyQualified().
{
   IPAddressV6 ip("F1E0:0ACE:FB94:7ADF:22E8:6DE6:9672:3725");
   while (iters--) {
     string outputString = ip.toFullyQualified();
     folly::doNotOptimizeAway(outputString);
     folly::doNotOptimizeAway(outputString.data());
   }
 }
BENCHMARK_RELATIVE (ipv6_append_to_fully_qualified_port , iters)
Definition at line 106 of file IPAddressBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE(), folly::doNotOptimizeAway(), folly::IPAddressV6::kToFullyQualifiedSize, folly::toAppend(), and folly::IPAddressV6::toFullyQualifiedAppend().
{
   IPAddressV6 ip("F1E0:0ACE:FB94:7ADF:22E8:6DE6:9672:3725");
   while (iters--) {
     string outputString;
     outputString.reserve(folly::IPAddressV6::kToFullyQualifiedSize + 1 + 5);
     ip.toFullyQualifiedAppend(outputString);
     outputString += ':';
     folly::toAppend(65535, &outputString);
     folly::doNotOptimizeAway(outputString);
     folly::doNotOptimizeAway(outputString.data());
   }
 }
BENCHMARK_RELATIVE (ipv6_ctor_invalid , iters)
Definition at line 132 of file IPAddressBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE(), and folly::doNotOptimizeAway().
{
   while (iters--) {
     try {
       IPAddressV6 ip("2803:6082:18e0:2c49:1a23:9ee0:5c87:980r");
       doNotOptimizeAway(ip);
     } catch (const IPAddressFormatException& ex) {
       doNotOptimizeAway(ex);
     }
   }
 }
BENCHMARK_RELATIVE (ipv6_try_from_string_invalid , iters)
Definition at line 155 of file IPAddressBenchmark.cpp.
References folly::doNotOptimizeAway(), and folly::IPAddressV6::tryFromString().
{
   while (iters--) {
     auto maybeIp =
         IPAddressV6::tryFromString("2803:6082:18e0:2c49:1a23:9ee0:5c87:980r");
     CHECK(maybeIp.hasError());
     doNotOptimizeAway(maybeIp);
     doNotOptimizeAway(maybeIp.error());
   }
 }
int main (int argc, char * argv[])
Definition at line 188 of file IPAddressBenchmark.cpp.
References folly::runBenchmarks().
{
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   runBenchmarks();
   return 0;
 }