proxygen: proxygen/folly/folly/container/test/IteratorTest.cpp File Reference
IteratorTest.cpp File Reference
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <deque>
#include <functional>
#include <map>
#include <set>
#include <tuple>
#include <type_traits>
#include <utility>
#include <vector>
#include <folly/container/Iterator.h>
#include <folly/portability/GTest.h>
Functions
TEST (EmplaceIterator, EmplacerTest)
TEST (EmplaceIterator, FrontEmplacerTest)
TEST (EmplaceIterator, BackEmplacerTest)
TEST (EmplaceIterator, HintEmplacerTest)
TEST (EmplaceIterator, Copy)
TEST (EmplaceIterator, Transform)
TEST (EmplaceIterator, EmplaceArgs)
TEST (EmplaceIterator, ImplicitUnpack)
Function Documentation
TEST (EmplaceIterator , EmplacerTest)
Basic tests for folly::emplace_iterator.
Definition at line 153 of file IteratorTest.cpp.
References copy_and_move_test(), folly::emplacer(), and EXPECT_EQ.
{
   {
     Container<int> q;
     copy_and_move_test(q, emplacer(q, q.begin()));
   }
   {
     Container<Object> q;
     emplace_test(q, emplacer(q, q.begin()));
   }
   {
     Container<int> q;
     auto it = emplacer(q, q.begin());
     it = 0;
     it = 1;
     it = 2;
     it = emplacer(q, q.begin());
     it = 3;
     it = 4;
     EXPECT_EQ(q, Container<int>({3, 4, 0, 1, 2}));
   }
 }
TEST (EmplaceIterator , FrontEmplacerTest)
Basic tests for folly::front_emplace_iterator.
Definition at line 178 of file IteratorTest.cpp.
References copy_and_move_test(), EXPECT_EQ, and folly::front_emplacer().
{
   {
     Container<int> q;
     copy_and_move_test(q, front_emplacer(q));
   }
   {
     Container<Object> q;
     emplace_test(q, front_emplacer(q));
   }
   {
     Container<int> q;
     auto it = front_emplacer(q);
     it = 0;
     it = 1;
     it = 2;
     it = front_emplacer(q);
     it = 3;
     it = 4;
     EXPECT_EQ(q, Container<int>({4, 3, 2, 1, 0}));
   }
 }
TEST (EmplaceIterator , BackEmplacerTest)
Basic tests for folly::back_emplace_iterator.
Definition at line 203 of file IteratorTest.cpp.
References folly::back_emplacer(), copy_and_move_test(), and EXPECT_EQ.
{
   {
     Container<int> q;
     copy_and_move_test(q, back_emplacer(q));
   }
   {
     Container<Object> q;
     emplace_test(q, back_emplacer(q));
   }
   {
     Container<int> q;
     auto it = back_emplacer(q);
     it = 0;
     it = 1;
     it = 2;
     it = back_emplacer(q);
     it = 3;
     it = 4;
     EXPECT_EQ(q, Container<int>({0, 1, 2, 3, 4}));
   }
 }
TEST (EmplaceIterator , HintEmplacerTest)
Basic tests for folly::hint_emplace_iterator.
Definition at line 228 of file IteratorTest.cpp.
References ASSERT_EQ, diff(), EXPECT_EQ, folly::hint_emplacer(), i, m, folly::make_emplace_args(), folly::operator<(), and operator==().
{
   {
     init_counters();
     std::map<int, Object> m;
     auto it = hint_emplacer(m, m.end());
     it = make_emplace_args(
         std::piecewise_construct,
         std::forward_as_tuple(0),
         std::forward_as_tuple(0));
     it = make_emplace_args(
         std::piecewise_construct,
         std::forward_as_tuple(1),
         std::forward_as_tuple(0, 0));
     it = make_emplace_args(
         std::piecewise_construct,
         std::forward_as_tuple(2),
         std::forward_as_tuple(Object{}));
     ASSERT_EQ(m.size(), 3);
     EXPECT_EQ(gDefaultCtrCnt, 1);
     EXPECT_EQ(gCopyCtrCnt, 0);
     EXPECT_EQ(gMoveCtrCnt, 1);
     EXPECT_EQ(gExplicitCtrCnt, 1);
     EXPECT_EQ(gMultiargCtrCnt, 1);
     EXPECT_EQ(gCopyOpCnt, 0);
     EXPECT_EQ(gMoveOpCnt, 0);
     EXPECT_EQ(gConvertOpCnt, 0);
   }
   {
     struct O {
       explicit O(int i_) : i(i_) {}
       bool operator<(const O& other) const {
         return i < other.i;
       }
       bool operator==(const O& other) const {
         return i == other.i;
       }
       int i;
     };
     std::vector<int> v1 = {0, 1, 2, 3, 4};
     std::vector<int> v2 = {0, 2, 4};
     std::set<O> diff;
     std::set_difference(
         v1.begin(),
         v1.end(),
         v2.begin(),
         v2.end(),
         hint_emplacer(diff, diff.end()));
     std::set<O> expected = {O(1), O(3)};
     ASSERT_EQ(diff, expected);
   }
 }
TEST (EmplaceIterator , Copy)
Test std::copy() with explicit conversion. This would not compile with a std::back_insert_iterator, because the constructor of Object that takes a single int is explicit.
Definition at line 285 of file IteratorTest.cpp.
References folly::back_emplacer(), folly::copy(), and EXPECT_EQ.
{
   init_counters();
   Container<int> in({0, 1, 2});
   Container<Object> out;
   std::copy(in.begin(), in.end(), back_emplacer(out));
   EXPECT_EQ(3, out.size());
   EXPECT_EQ(gDefaultCtrCnt, 0);
   EXPECT_EQ(gCopyCtrCnt, 0);
   EXPECT_EQ(gMoveCtrCnt, 0);
   EXPECT_EQ(gExplicitCtrCnt, 3);
   EXPECT_EQ(gMultiargCtrCnt, 0);
   EXPECT_EQ(gCopyOpCnt, 0);
   EXPECT_EQ(gMoveOpCnt, 0);
   EXPECT_EQ(gConvertOpCnt, 0);
 }
TEST (EmplaceIterator , Transform)
Test std::transform() with multi-argument constructors. This would require a temporary Object with std::back_insert_iterator.
Definition at line 305 of file IteratorTest.cpp.
References folly::back_emplacer(), EXPECT_EQ, i, folly::make_emplace_args(), and folly::pushmi::operators::transform.
{
   init_counters();
   Container<int> in({0, 1, 2});
   Container<Object> out;
   std::transform(in.begin(), in.end(), back_emplacer(out), [](int i) {
     return make_emplace_args(i, i);
   });
   EXPECT_EQ(3, out.size());
   EXPECT_EQ(gDefaultCtrCnt, 0);
   EXPECT_EQ(gCopyCtrCnt, 0);
   EXPECT_EQ(gMoveCtrCnt, 0);
   EXPECT_EQ(gExplicitCtrCnt, 0);
   EXPECT_EQ(gMultiargCtrCnt, 3);
   EXPECT_EQ(gCopyOpCnt, 0);
   EXPECT_EQ(gMoveOpCnt, 0);
   EXPECT_EQ(gConvertOpCnt, 0);
 }
TEST (EmplaceIterator , EmplaceArgs)
Test multi-argument store and forward.
Definition at line 326 of file IteratorTest.cpp.
References EXPECT_EQ, folly::make_emplace_args(), folly::gen::move, folly::rref(), and value.
{
   Object o1;
   const Object o2;
   Object& o3 = o1;
   const Object& o4 = o3;
   Object o5;
   {
     // Test copy construction.
     auto args = make_emplace_args(0, o1, o2, o3, o4, Object{}, std::cref(o2));
     init_counters();
     auto args2 = args;
     EXPECT_EQ(gDefaultCtrCnt, 0);
     EXPECT_EQ(gCopyCtrCnt, 5);
     EXPECT_EQ(gMoveCtrCnt, 0);
     EXPECT_EQ(gExplicitCtrCnt, 0);
     EXPECT_EQ(gMultiargCtrCnt, 0);
     EXPECT_EQ(gCopyOpCnt, 0);
     EXPECT_EQ(gMoveOpCnt, 0);
     EXPECT_EQ(gConvertOpCnt, 0);
     // Test copy assignment.
     init_counters();
     args = args2;
     EXPECT_EQ(gDefaultCtrCnt, 0);
     EXPECT_EQ(gCopyCtrCnt, 0);
     EXPECT_EQ(gMoveCtrCnt, 0);
     EXPECT_EQ(gExplicitCtrCnt, 0);
     EXPECT_EQ(gMultiargCtrCnt, 0);
     EXPECT_EQ(gCopyOpCnt, 5);
     EXPECT_EQ(gMoveOpCnt, 0);
     EXPECT_EQ(gConvertOpCnt, 0);
   }
   {
     // Test RVO.
     init_counters();
     auto args = make_emplace_args(
         0, o1, o2, o3, o4, Object{}, std::cref(o2), rref(std::move(o5)));
     EXPECT_EQ(gDefaultCtrCnt, 1);
     EXPECT_EQ(gCopyCtrCnt, 4);
     EXPECT_EQ(gMoveCtrCnt, 1);
     EXPECT_EQ(gExplicitCtrCnt, 0);
     EXPECT_EQ(gMultiargCtrCnt, 0);
     EXPECT_EQ(gCopyOpCnt, 0);
     EXPECT_EQ(gMoveOpCnt, 0);
     EXPECT_EQ(gConvertOpCnt, 0);
     // Test move construction.
     init_counters();
     auto args2 = std::move(args);
     EXPECT_EQ(gDefaultCtrCnt, 0);
     EXPECT_EQ(gCopyCtrCnt, 0);
     EXPECT_EQ(gMoveCtrCnt, 5);
     EXPECT_EQ(gExplicitCtrCnt, 0);
     EXPECT_EQ(gMultiargCtrCnt, 0);
     EXPECT_EQ(gCopyOpCnt, 0);
     EXPECT_EQ(gMoveOpCnt, 0);
     EXPECT_EQ(gConvertOpCnt, 0);
     // Test move assignment.
     init_counters();
     args = std::move(args2);
     EXPECT_EQ(gDefaultCtrCnt, 0);
     EXPECT_EQ(gCopyCtrCnt, 0);
     EXPECT_EQ(gMoveCtrCnt, 0);
     EXPECT_EQ(gExplicitCtrCnt, 0);
     EXPECT_EQ(gMultiargCtrCnt, 0);
     EXPECT_EQ(gCopyOpCnt, 0);
     EXPECT_EQ(gMoveOpCnt, 5);
     EXPECT_EQ(gConvertOpCnt, 0);
     // Make sure arguments are stored correctly. lvalues by reference, rvalues
     // by (moved) copy. Rvalues cannot be stored by reference because they may
     // refer to an expired temporary by the time they are accessed.
     static_assert(
         std::is_same<
             int,
             std::tuple_element_t<0, decltype(args)::storage_type>>::value,
         "");
     static_assert(
         std::is_same<
             Object,
             std::tuple_element_t<1, decltype(args)::storage_type>>::value,
         "");
     static_assert(
         std::is_same<
             Object,
             std::tuple_element_t<2, decltype(args)::storage_type>>::value,
         "");
     static_assert(
         std::is_same<
             Object,
             std::tuple_element_t<3, decltype(args)::storage_type>>::value,
         "");
     static_assert(
         std::is_same<
             Object,
             std::tuple_element_t<4, decltype(args)::storage_type>>::value,
         "");
     static_assert(
         std::is_same<
             Object,
             std::tuple_element_t<5, decltype(args)::storage_type>>::value,
         "");
     static_assert(
         std::is_same<
             std::reference_wrapper<const Object>,
             std::tuple_element_t<6, decltype(args)::storage_type>>::value,
         "");
     static_assert(
         std::is_same<
             rvalue_reference_wrapper<Object>,
             std::tuple_element_t<7, decltype(args)::storage_type>>::value,
         "");
     // Check whether args.get() restores the original argument type for
     // rvalue references to emplace_args.
     static_assert(
         std::is_same<int&&, decltype(get_emplace_arg<0>(std::move(args)))>::
             value,
         "");
     static_assert(
         std::is_same<Object&, decltype(get_emplace_arg<1>(std::move(args)))>::
             value,
         "");
     static_assert(
         std::is_same<
             const Object&,
             decltype(get_emplace_arg<2>(std::move(args)))>::value,
         "");
     static_assert(
         std::is_same<Object&, decltype(get_emplace_arg<3>(std::move(args)))>::
             value,
         "");
     static_assert(
         std::is_same<
             const Object&,
             decltype(get_emplace_arg<4>(std::move(args)))>::value,
         "");
     static_assert(
         std::is_same<Object&&, decltype(get_emplace_arg<5>(std::move(args)))>::
             value,
         "");
     static_assert(
         std::is_same<
             const Object&,
             decltype(get_emplace_arg<6>(std::move(args)))>::value,
         "");
     static_assert(
         std::is_same<Object&&, decltype(get_emplace_arg<7>(std::move(args)))>::
             value,
         "");
     // lvalue references to emplace_args should behave mostly like std::tuples.
     // Note that get_emplace_arg<7>(args) does not compile, because
     // folly::rvalue_reference_wrappers can only be unwrapped through an rvalue
     // reference.
     static_assert(
         std::is_same<int&, decltype(get_emplace_arg<0>(args))>::value, "");
     static_assert(
         std::is_same<Object&, decltype(get_emplace_arg<1>(args))>::value, "");
     static_assert(
         std::is_same<Object&, decltype(get_emplace_arg<2>(args))>::value, "");
     static_assert(
         std::is_same<Object&, decltype(get_emplace_arg<3>(args))>::value, "");
     static_assert(
         std::is_same<Object&, decltype(get_emplace_arg<4>(args))>::value, "");
     static_assert(
         std::is_same<Object&, decltype(get_emplace_arg<5>(args))>::value, "");
     static_assert(
         std::is_same<const Object&, decltype(get_emplace_arg<6>(args))>::value,
         "");
   }
 }
TEST (EmplaceIterator , ImplicitUnpack)
Test implicit unpacking.
Definition at line 505 of file IteratorTest.cpp.
References folly::back_emplacer(), folly::emplacer(), EXPECT_EQ, folly::front_emplacer(), std::tr1::make_tuple(), and test().
{
   static std::size_t multiCtrCnt;
   static std::size_t pairCtrCnt;
   static std::size_t tupleCtrCnt;
   struct Object2 {
     Object2(int, int) {
       ++multiCtrCnt;
     }
     explicit Object2(const std::pair<int, int>&) {
       ++pairCtrCnt;
     }
     explicit Object2(const std::tuple<int, int>&) {
       ++tupleCtrCnt;
     }
   };
   auto test = [](auto&& it, bool expectUnpack) {
     multiCtrCnt = pairCtrCnt = tupleCtrCnt = 0;
     it = std::make_pair(0, 0);
     it = std::make_tuple(0, 0);
     if (expectUnpack) {
       EXPECT_EQ(multiCtrCnt, 2);
       EXPECT_EQ(pairCtrCnt, 0);
       EXPECT_EQ(tupleCtrCnt, 0);
     } else {
       EXPECT_EQ(multiCtrCnt, 0);
       EXPECT_EQ(pairCtrCnt, 1);
       EXPECT_EQ(tupleCtrCnt, 1);
     }
   };
   Container<Object2> q;
   test(emplacer(q, q.begin()), true);
   test(emplacer<false>(q, q.begin()), false);
   test(front_emplacer(q), true);
   test(front_emplacer<false>(q), false);
   test(back_emplacer(q), true);
   test(back_emplacer<false>(q), false);
 }