proxygen: proxygen/folly/folly/experimental/test/JemallocNodumpAllocatorTest.cpp File Reference
JemallocNodumpAllocatorTest.cpp File Reference
#include <folly/experimental/JemallocNodumpAllocator.h>
#include <folly/io/IOBuf.h>
#include <folly/memory/Malloc.h>
#include <folly/portability/GTest.h>
Functions
TEST (JemallocNodumpAllocatorTest, Basic)
TEST (JemallocNodumpAllocatorTest, IOBuf)
Function Documentation
TEST (JemallocNodumpAllocatorTest , Basic)
Definition at line 23 of file JemallocNodumpAllocatorTest.cpp.
References folly::JemallocNodumpAllocator::allocate(), folly::JemallocNodumpAllocator::deallocate(), EXPECT_NE, folly::JemallocNodumpAllocator::getArenaIndex(), ptr, and folly::usingJEMalloc().
{
   folly::JemallocNodumpAllocator jna;
 #ifdef FOLLY_JEMALLOC_NODUMP_ALLOCATOR_SUPPORTED
   if (folly::usingJEMalloc()) {
     EXPECT_NE(0, jna.getArenaIndex());
   }
 #endif // FOLLY_JEMALLOC_NODUMP_ALLOCATOR_SUPPORTED
   auto ptr = jna.allocate(1024);
   EXPECT_NE(nullptr, ptr);
   jna.deallocate(ptr);
 }
TEST (JemallocNodumpAllocatorTest , IOBuf)
Definition at line 37 of file JemallocNodumpAllocatorTest.cpp.
References folly::JemallocNodumpAllocator::allocate(), folly::IOBuf::capacity(), data, folly::IOBuf::data(), EXPECT_EQ, EXPECT_NE, folly::JemallocNodumpAllocator::getArenaIndex(), i, ptr, folly::size(), folly::IOBuf::TAKE_OWNERSHIP, uint8_t, folly::usingJEMalloc(), and folly::IOBuf::writableData().
{
   folly::JemallocNodumpAllocator jna;
 #ifdef FOLLY_JEMALLOC_NODUMP_ALLOCATOR_SUPPORTED
   if (folly::usingJEMalloc()) {
     EXPECT_NE(0, jna.getArenaIndex());
   }
 #endif // FOLLY_JEMALLOC_NODUMP_ALLOCATOR_SUPPORTED
   const size_t size{1024};
   void* ptr = jna.allocate(size);
   EXPECT_NE(nullptr, ptr);
   folly::IOBuf ioBuf(folly::IOBuf::TAKE_OWNERSHIP, ptr, size);
   EXPECT_EQ(size, ioBuf.capacity());
   EXPECT_EQ(ptr, ioBuf.data());
   uint8_t* data = ioBuf.writableData();
   EXPECT_EQ(ptr, data);
   for (auto i = 0u; i < ioBuf.capacity(); ++i) {
     data[i] = 'A';
   }
   uint8_t* p = static_cast<uint8_t*>(ptr);
   for (auto i = 0u; i < size; ++i) {
     EXPECT_EQ('A', p[i]);
   }
 }