proxygen: proxygen/folly/folly/test/JsonOtherTest.cpp File Reference
JsonOtherTest.cpp File Reference
#include <folly/json.h>
#include <folly/Benchmark.h>
#include <folly/Conv.h>
#include <folly/FileUtil.h>
#include <folly/Range.h>
#include <folly/portability/GFlags.h>
#include <folly/portability/GTest.h>
Functions
TEST (Json, StripComments)
BENCHMARK (jsonSerialize, iters)
BENCHMARK (jsonSerializeWithNonAsciiEncoding, iters)
BENCHMARK (jsonSerializeWithUtf8Validation, iters)
BENCHMARK (jsonSerializeAsciiWithUtf8Validation, iters)
BENCHMARK (jsonSerializeWithExtraUnicodeEscapes, iters)
BENCHMARK (parseSmallStringWithUtf, iters)
BENCHMARK (parseNormalString, iters)
BENCHMARK (parseBigString, iters)
BENCHMARK (toJson, iters)
int main (int argc, char **argv)
Variables
constexpr folly::StringPiece kLargeAsciiString
constexpr folly::StringPiece kLargeNonAsciiString
constexpr folly::StringPiece kLargeAsciiStringWithSpecialChars
Function Documentation
BENCHMARK (jsonSerialize , iters)
Definition at line 82 of file JsonOtherTest.cpp.
References i, kLargeNonAsciiString, and folly::json::serialize().
{
   const dynamic obj = kLargeNonAsciiString;
   folly::json::serialization_opts opts;
   for (size_t i = 0; i < iters; ++i) {
     folly::json::serialize(obj, opts);
   }
 }
BENCHMARK (jsonSerializeWithNonAsciiEncoding , iters)
Definition at line 91 of file JsonOtherTest.cpp.
References folly::json::serialization_opts::encode_non_ascii, i, kLargeNonAsciiString, and folly::json::serialize().
{
   const dynamic obj = kLargeNonAsciiString;
   folly::json::serialization_opts opts;
   opts.encode_non_ascii = true;
   for (size_t i = 0; i < iters; ++i) {
     folly::json::serialize(obj, opts);
   }
 }
BENCHMARK (jsonSerializeWithUtf8Validation , iters)
Definition at line 102 of file JsonOtherTest.cpp.
References i, kLargeNonAsciiString, folly::json::serialize(), and folly::json::serialization_opts::validate_utf8.
{
   const dynamic obj = kLargeNonAsciiString;
   folly::json::serialization_opts opts;
   opts.validate_utf8 = true;
   for (size_t i = 0; i < iters; ++i) {
     folly::json::serialize(obj, opts);
   }
 }
BENCHMARK (jsonSerializeAsciiWithUtf8Validation , iters)
Definition at line 113 of file JsonOtherTest.cpp.
References i, kLargeAsciiString, folly::json::serialize(), and folly::json::serialization_opts::validate_utf8.
{
   const dynamic obj = kLargeAsciiString;
   folly::json::serialization_opts opts;
   opts.validate_utf8 = true;
   for (size_t i = 0; i < iters; ++i) {
     folly::json::serialize(obj, opts);
   }
 }
BENCHMARK (jsonSerializeWithExtraUnicodeEscapes , iters)
Definition at line 124 of file JsonOtherTest.cpp.
References folly::json::buildExtraAsciiToEscapeBitmap(), folly::json::serialization_opts::extra_ascii_to_escape_bitmap, i, kLargeAsciiStringWithSpecialChars, and folly::json::serialize().
{
   const dynamic obj = kLargeAsciiStringWithSpecialChars;
   folly::json::serialization_opts opts;
   opts.extra_ascii_to_escape_bitmap =
       folly::json::buildExtraAsciiToEscapeBitmap("<%@");
   for (size_t i = 0; i < iters; ++i) {
     folly::json::serialize(obj, opts);
   }
 }
BENCHMARK (parseSmallStringWithUtf , iters)
Definition at line 136 of file JsonOtherTest.cpp.
References i, and folly::parseJson().
{
   for (size_t i = 0; i < iters << 4; ++i) {
     parseJson("\"I \\u2665 UTF-8 thjasdhkjh blah blah blah\"");
   }
 }
BENCHMARK (parseNormalString , iters)
Definition at line 142 of file JsonOtherTest.cpp.
References i, and folly::parseJson().
{
   for (size_t i = 0; i < iters << 4; ++i) {
     parseJson("\"akjhfk jhkjlakjhfk jhkjlakjhfk jhkjl akjhfk\"");
   }
 }
BENCHMARK (parseBigString , iters)
Definition at line 148 of file JsonOtherTest.cpp.
References i, kLargeAsciiString, and folly::parseJson().
{
   const auto json = folly::to<std::string>('"', kLargeAsciiString, '"');
   for (size_t i = 0; i < iters; ++i) {
     parseJson(json);
   }
 }
BENCHMARK (toJson , iters)
Definition at line 156 of file JsonOtherTest.cpp.
References i, folly::parseJson(), and folly::toJson().
{
   dynamic something = parseJson(
       "{\"old_value\":40,\"changed\":true,\"opened\":false,\"foo\":[1,2,3,4,5,6]}");
   for (size_t i = 0; i < iters; i++) {
     toJson(something);
   }
 }
int main (int argc, char ** argv)
Definition at line 165 of file JsonOtherTest.cpp.
References testing::InitGoogleTest(), RUN_ALL_TESTS(), and folly::runBenchmarks().
{
   testing::InitGoogleTest(&argc, argv);
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   if (FLAGS_benchmark) {
     folly::runBenchmarks();
   }
   return RUN_ALL_TESTS();
 }
TEST (Json , StripComments)
Definition at line 64 of file JsonOtherTest.cpp.
References EXPECT_EQ, FAIL, folly::readFile(), string, and folly::json::stripComments().
{
   const std::string kTestDir = "folly/test/";
   const std::string kTestFile = "json_test_data/commented.json";
   const std::string kTestExpected = "json_test_data/commented.json.exp";
   std::string testStr;
   std::string expectedStr;
   if (!folly::readFile(kTestFile.data(), testStr) &&
       !folly::readFile((kTestDir + kTestFile).data(), testStr)) {
     FAIL() << "can not read test file " << kTestFile;
   }
   if (!folly::readFile(kTestExpected.data(), expectedStr) &&
       !folly::readFile((kTestDir + kTestExpected).data(), expectedStr)) {
     FAIL() << "can not read test file " << kTestExpected;
   }
   EXPECT_EQ(expectedStr, folly::json::stripComments(testStr));
 }
Variable Documentation
constexpr folly::StringPiece kLargeAsciiString
Initial value:
=
    "akjhfk jhkjlakjhfk jhkjlakjhfk jhkjl akjhfk"
    "akjhfk jhkjlakjhfk jhkjlakjhfk jhkjl akjhfk"
    "akjhfk jhkjlakjhfk jhkjlakjhfk jhkjl akjhfk"
    "akjhfk jhkjlakjhfk jhkjlakjhfk jhkjl akjhfk"
    "akjhfk jhkjlakjhfk jhkjlakjhfk jhkjl akjhfk"
    "akjhfk jhkjlakjhfk jhkjlakjhfk jhkjl akjhfk"
    "akjhfk jhkjlakjhfk jhkjlakjhfk jhkjl akjhfk"
    "akjhfk jhkjlakjhfk jhkjlakjhfk jhkjl akjhfk"
    "akjhfk jhkjlakjhfk jhkjlakjhfk jhkjl akjhfk"
    "akjhfk jhkjlakjhfk jhkjlakjhfk jhkjl akjhfk"
    "akjhfk jhkjlakjhfk jhkjlakjhfk jhkjl akjhfk"
Definition at line 30 of file JsonOtherTest.cpp.
Referenced by BENCHMARK().
constexpr folly::StringPiece kLargeAsciiStringWithSpecialChars
Initial value:
=
    "<script>foo%@bar.com</script>"
    "<script>foo%@bar.com</script>"
    "<script>foo%@bar.com</script>"
    "<script>foo%@bar.com</script>"
    "<script>foo%@bar.com</script>"
    "<script>foo%@bar.com</script>"
    "<script>foo%@bar.com</script>"
Definition at line 55 of file JsonOtherTest.cpp.
Referenced by BENCHMARK().
constexpr folly::StringPiece kLargeNonAsciiString
Initial value:
=
    "qwerty \xc2\x80 \xef\xbf\xbf poiuy"
    "qwerty \xc2\x80 \xef\xbf\xbf poiuy"
    "qwerty \xc2\x80 \xef\xbf\xbf poiuy"
    "qwerty \xc2\x80 \xef\xbf\xbf poiuy"
    "qwerty \xc2\x80 \xef\xbf\xbf poiuy"
    "qwerty \xc2\x80 \xef\xbf\xbf poiuy"
    "qwerty \xc2\x80 \xef\xbf\xbf poiuy"
    "qwerty \xc2\x80 \xef\xbf\xbf poiuy"
    "qwerty \xc2\x80 \xef\xbf\xbf poiuy"
    "qwerty \xc2\x80 \xef\xbf\xbf poiuy"
Definition at line 43 of file JsonOtherTest.cpp.
Referenced by BENCHMARK().