proxygen: proxygen/folly/folly/experimental/JSONSchemaTester.cpp File Reference
JSONSchemaTester.cpp File Reference
#include <folly/experimental/JSONSchema.h>
#include <folly/json.h>
#include <fstream>
#include <sstream>
#include <string>
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
A binary that supports testing against the official tests from: https://github.com/json-schema/JSON-Schema-Test-Suite
Use it like: ./jsonschema_tester /path/to/test.json
Definition at line 30 of file JSONSchemaTester.cpp.
References buffer(), i, folly::jsonschema::makeValidator(), folly::parseJson(), and folly::pushmi::detail::t.
{
   if (argc < 2) {
     printf("Usage: %s <testfile> [testfile2]...\n", argv[0]);
     return -1;
   }
   for (int i = 1; i < argc; ++i) {
     printf("FILE: %s\n", argv[i]);
     std::ifstream fin(argv[i]);
     std::stringstream buffer;
     buffer << fin.rdbuf();
     const folly::dynamic d = folly::parseJson(buffer.str());
     for (const auto& item : d) {
       printf("TEST: %s\n", item["description"].c_str());
       auto v = folly::jsonschema::makeValidator(item["schema"]);
       for (const auto& t : item["tests"]) {
         printf("\t%s... ", t["description"].c_str());
         auto ew = v->try_validate(t["data"]);
         bool had_error = !static_cast<bool>(ew);
         if (had_error == t["valid"].asBool()) {
           printf("passed\n");
         } else {
           printf("FAILED\n");
         }
       }
     }
   }
 }