proxygen: proxygen/folly/folly/lang/test/BitsTest.cpp File Reference
BitsTest.cpp File Reference
#include <algorithm>
#include <random>
#include <vector>
#include <folly/Random.h>
#include <folly/lang/Bits.h>
#include <folly/portability/GTest.h>
Functions
TEST (Bits, FindFirstSet)
TEST (Bits, FindLastSet)
TEST (Bits, nextPowTwoClz)
TEST (Bits, prevPowTwoClz)
TEST (Bits, isPowTwo)
TEST (Bits, popcount)
TEST (Bits, Endian_swap_uint)
TEST (Bits, Endian_swap_real)
uint64_t reverse_simple (uint64_t v)
TEST (Bits, BitReverse)
TEST (Bits, PartialLoadUnaligned)
Function Documentation
uint64_t reverse_simple (uint64_t v)
Definition at line 191 of file BitsTest.cpp.
References i, and uint64_t.
Referenced by TEST().
{
   uint64_t r = 0;
   for (int i = 0; i < 64; i++) {
     r <<= 1;
     r |= v & 1;
     v >>= 1;
   }
   return r;
 }
TEST (Bits , FindFirstSet)
Definition at line 70 of file BitsTest.cpp.
{
   testFFS<char>();
   testFFS<signed char>();
   testFFS<unsigned char>();
   testFFS<short>();
   testFFS<unsigned short>();
   testFFS<int>();
   testFFS<unsigned int>();
   testFFS<long>();
   testFFS<unsigned long>();
   testFFS<long long>();
   testFFS<unsigned long long>();
 }
TEST (Bits , FindLastSet)
Definition at line 84 of file BitsTest.cpp.
{
   testFLS<char>();
   testFLS<signed char>();
   testFLS<unsigned char>();
   testFLS<short>();
   testFLS<unsigned short>();
   testFLS<int>();
   testFLS<unsigned int>();
   testFLS<long>();
   testFLS<unsigned long>();
   testFLS<long long>();
   testFLS<unsigned long long>();
 }
TEST (Bits , nextPowTwoClz)
Definition at line 98 of file BitsTest.cpp.
References EXPECT_EQ, and folly::nextPowTwo().
{
   EXPECT_EQ(1, nextPowTwo(0u));
   EXPECT_EQ(1, nextPowTwo(1u));
   EXPECT_EQ(2, nextPowTwo(2u));
   EXPECT_EQ(4, nextPowTwo(3u));
   EXPECT_EQ(4, nextPowTwo(4u));
   EXPECT_EQ(8, nextPowTwo(5u));
   EXPECT_EQ(8, nextPowTwo(6u));
   EXPECT_EQ(8, nextPowTwo(7u));
   EXPECT_EQ(8, nextPowTwo(8u));
   EXPECT_EQ(16, nextPowTwo(9u));
   EXPECT_EQ(16, nextPowTwo(13u));
   EXPECT_EQ(16, nextPowTwo(16u));
   EXPECT_EQ(512, nextPowTwo(510u));
   EXPECT_EQ(512, nextPowTwo(511u));
   EXPECT_EQ(512, nextPowTwo(512u));
   EXPECT_EQ(1024, nextPowTwo(513u));
   EXPECT_EQ(1024, nextPowTwo(777u));
   EXPECT_EQ(1ul << 31, nextPowTwo((1ul << 31) - 1));
   EXPECT_EQ(1ull << 32, nextPowTwo((1ull << 32) - 1));
   EXPECT_EQ(1ull << 63, nextPowTwo((1ull << 62) + 1));
 }
TEST (Bits , prevPowTwoClz)
Definition at line 121 of file BitsTest.cpp.
References EXPECT_EQ, and folly::prevPowTwo().
{
   EXPECT_EQ(0, prevPowTwo(0u));
   EXPECT_EQ(1, prevPowTwo(1u));
   EXPECT_EQ(2, prevPowTwo(2u));
   EXPECT_EQ(2, prevPowTwo(3u));
   EXPECT_EQ(4, prevPowTwo(4u));
   EXPECT_EQ(4, prevPowTwo(5u));
   EXPECT_EQ(4, prevPowTwo(6u));
   EXPECT_EQ(4, prevPowTwo(7u));
   EXPECT_EQ(8, prevPowTwo(8u));
   EXPECT_EQ(8, prevPowTwo(9u));
   EXPECT_EQ(8, prevPowTwo(13u));
   EXPECT_EQ(16, prevPowTwo(16u));
   EXPECT_EQ(256, prevPowTwo(510u));
   EXPECT_EQ(256, prevPowTwo(511u));
   EXPECT_EQ(512, prevPowTwo(512u));
   EXPECT_EQ(512, prevPowTwo(513u));
   EXPECT_EQ(512, prevPowTwo(777u));
   EXPECT_EQ(1ul << 30, prevPowTwo((1ul << 31) - 1));
   EXPECT_EQ(1ull << 31, prevPowTwo((1ull << 32) - 1));
   EXPECT_EQ(1ull << 62, prevPowTwo((1ull << 62) + 1));
 }
TEST (Bits , isPowTwo)
Definition at line 144 of file BitsTest.cpp.
References EXPECT_FALSE, EXPECT_TRUE, and folly::isPowTwo().
                      {
   EXPECT_FALSE(isPowTwo(0u));
   EXPECT_TRUE(isPowTwo(1ul));
   EXPECT_TRUE(isPowTwo(2ull));
   EXPECT_FALSE(isPowTwo(3ul));
   EXPECT_TRUE(isPowTwo(4ul));
   EXPECT_FALSE(isPowTwo(5ul));
   EXPECT_TRUE(isPowTwo(8ul));
   EXPECT_FALSE(isPowTwo(15u));
   EXPECT_TRUE(isPowTwo(16u));
   EXPECT_FALSE(isPowTwo(17u));
   EXPECT_FALSE(isPowTwo(511ul));
   EXPECT_TRUE(isPowTwo(512ul));
   EXPECT_FALSE(isPowTwo(513ul));
   EXPECT_FALSE(isPowTwo((1ul << 31) - 1));
   EXPECT_TRUE(isPowTwo(1ul << 31));
   EXPECT_FALSE(isPowTwo((1ul << 31) + 1));
   EXPECT_FALSE(isPowTwo((1ull << 63) - 1));
   EXPECT_TRUE(isPowTwo(1ull << 63));
   EXPECT_FALSE(isPowTwo((1ull << 63) + 1));
 }
TEST (Bits , popcount)
Definition at line 166 of file BitsTest.cpp.
References EXPECT_EQ, folly::popcount(), uint32_t, and uint64_t.
                      {
   EXPECT_EQ(0, popcount(0U));
   EXPECT_EQ(1, popcount(1U));
   EXPECT_EQ(32, popcount(uint32_t(-1)));
   EXPECT_EQ(64, popcount(uint64_t(-1)));
 }
TEST (Bits , Endian_swap_uint)
Definition at line 173 of file BitsTest.cpp.
References EXPECT_EQ, folly::Endian::swap(), uint16_t, uint32_t, uint64_t, and uint8_t.
{
   EXPECT_EQ(uint8_t(0xda), Endian::swap(uint8_t(0xda)));
   EXPECT_EQ(uint16_t(0x4175), Endian::swap(uint16_t(0x7541)));
   EXPECT_EQ(uint32_t(0x42efb918), Endian::swap(uint32_t(0x18b9ef42)));
   EXPECT_EQ(
       uint64_t(0xa244f5e862c71d8a), Endian::swap(uint64_t(0x8a1dc762e8f544a2)));
 }
TEST (Bits , Endian_swap_real)
Definition at line 181 of file BitsTest.cpp.
References EXPECT_EQ, EXPECT_NE, f, rng, and folly::Endian::swap().
{
   std::mt19937_64 rng;
   auto f = std::uniform_real_distribution<float>()(rng);
   EXPECT_NE(f, Endian::swap(f));
   EXPECT_EQ(f, Endian::swap(Endian::swap(f)));
   auto d = std::uniform_real_distribution<double>()(rng);
   EXPECT_NE(d, Endian::swap(d));
   EXPECT_EQ(d, Endian::swap(Endian::swap(d)));
 }
TEST (Bits , BitReverse)
Definition at line 202 of file BitsTest.cpp.
References b, folly::bitReverse(), EXPECT_EQ, i, folly::Random::rand32(), folly::Random::rand64(), reverse_simple(), uint32_t, and uint64_t.
{
   EXPECT_EQ(folly::bitReverse<uint8_t>(0), 0);
   EXPECT_EQ(folly::bitReverse<uint8_t>(1), 128);
   for (int i = 0; i < 100; i++) {
     uint64_t v = folly::Random::rand64();
     EXPECT_EQ(folly::bitReverse(v), reverse_simple(v));
     uint32_t b = folly::Random::rand32();
     EXPECT_EQ(folly::bitReverse(b), reverse_simple(b) >> 32);
   }
 }
TEST (Bits , PartialLoadUnaligned)
Definition at line 213 of file BitsTest.cpp.
References EXPECT_EQ, folly::Random::rand32(), and uint64_t.
{
   std::vector<char> buf(128);
   std::generate(
       buf.begin(), buf.end(), [] { return folly::Random::rand32(255); });
   for (size_t l = 0; l < 8; ++l) {
     for (size_t pos = 0; pos <= buf.size() - l; ++pos) {
       auto p = buf.data() + pos;
       auto x = folly::partialLoadUnaligned<uint64_t>(p, l);
       uint64_t expected = 0;
       memcpy(&expected, p, l);
       EXPECT_EQ(x, expected);
       if (l < 4) {
         auto x32 = folly::partialLoadUnaligned<uint32_t>(p, l);
         EXPECT_EQ(x32, static_cast<uint32_t>(expected));
       }
     }
   }
 }