proxygen: proxygen/folly/folly/lang/test/BitsBenchmark.cpp File Reference
BitsBenchmark.cpp File Reference
#include <algorithm>
#include <vector>
#include <folly/CppAttributes.h>
#include <folly/Random.h>
#include <folly/lang/Assume.h>
#include <folly/lang/Bits.h>
#include <folly/Benchmark.h>
Functions
BENCHMARK (nextPowTwoClz, iters)
BENCHMARK_DRAW_LINE ()
BENCHMARK (isPowTwo, iters)
BENCHMARK (reverse, iters)
BENCHMARK (PartialLoadUnaligned, iters)
BENCHMARK (PartialLoadUnalignedMemcpy, iters)
BENCHMARK (PartialLoadUnalignedSwitch, iters)
int main (int argc, char **argv)
Function Documentation
BENCHMARK (nextPowTwoClz , iters)
Definition at line 31 of file BitsBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE(), folly::doNotOptimizeAway(), i, and folly::nextPowTwo().
{
   for (unsigned long i = 0; i < iters; ++i) {
     auto x = folly::nextPowTwo(i);
     folly::doNotOptimizeAway(x);
   }
 }
BENCHMARK (isPowTwo , iters)
Definition at line 39 of file BitsBenchmark.cpp.
References b, folly::BENCHMARK_DRAW_LINE(), folly::doNotOptimizeAway(), i, and folly::isPowTwo().
{
   bool b;
   for (unsigned long i = 0; i < iters; ++i) {
     b = folly::isPowTwo(i);
     folly::doNotOptimizeAway(b);
   }
 }
BENCHMARK (reverse , iters)
Definition at line 48 of file BitsBenchmark.cpp.
References folly::assume(), b, folly::BENCHMARK_DRAW_LINE(), BENCHMARK_SUSPEND, folly::bitReverse(), folly::doNotOptimizeAway(), f, FOLLY_FALLTHROUGH, i, folly::Random::rand32(), and uint64_t.
{
   uint64_t b = 0;
   for (unsigned long i = 0; i < iters; ++i) {
     b = folly::bitReverse(i + b);
     folly::doNotOptimizeAway(b);
   }
 }
BENCHMARK (PartialLoadUnaligned , iters)
Definition at line 126 of file BitsBenchmark.cpp.
{
   testPartialLoadUnaligned(folly::partialLoadUnaligned<uint64_t>, iters);
 }
BENCHMARK (PartialLoadUnalignedMemcpy , iters)
Definition at line 130 of file BitsBenchmark.cpp.
References folly::assume(), and uint64_t.
{
   testPartialLoadUnaligned(
       [](const char* p, size_t l) {
         folly::assume(l < 8);
         uint64_t ret;
         memcpy(&ret, p, l);
         return ret;
       },
       iters);
 }
BENCHMARK (PartialLoadUnalignedSwitch , iters)
Definition at line 142 of file BitsBenchmark.cpp.
{
   testPartialLoadUnaligned(partialLoadUnalignedSwitch, iters);
 }
BENCHMARK_DRAW_LINE ()
int main (int argc, char ** argv)
Definition at line 146 of file BitsBenchmark.cpp.
References folly::runBenchmarks().
{
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   folly::runBenchmarks();
   return 0;
 }