proxygen: proxygen/folly/folly/lang/test/ExceptionTest.cpp File Reference
ExceptionTest.cpp File Reference
#include <folly/lang/Exception.h>
#include <algorithm>
#include <cstring>
#include <string>
#include <folly/Portability.h>
#include <folly/portability/GTest.h>
Classes
class MyException
class ExceptionTest
Functions
template<typename Ex >
static std::string type_pretty_name ()
template<typename Ex >
static std::string message_for_terminate_with (std::string const &what)
static std::string message_for_terminate ()
TEST_F (ExceptionTest, throw_exception_direct)
TEST_F (ExceptionTest, throw_exception_variadic)
TEST_F (ExceptionTest, terminate_with_direct)
TEST_F (ExceptionTest, terminate_with_variadic)
TEST_F (ExceptionTest, invoke_noreturn_cold)
Function Documentation
static std::string message_for_terminate () static
Definition at line 51 of file ExceptionTest.cpp.
References folly::kIsGlibcxx, and folly::kIsLibcpp.
Referenced by TEST_F().
{
   // clang-format off
   return
       folly::kIsGlibcxx ? "terminate called without an active exception" :
       folly::kIsLibcpp ? "terminating" :
       "" /* empty regex matches anything */;
   // clang-format on
 }
template<typename Ex > static std::string message_for_terminate_with (std::string const & what) static
Definition at line 39 of file ExceptionTest.cpp.
References folly::kIsGlibcxx, folly::kIsLibcpp, name, prefix(), and string.
{
   auto const name = type_pretty_name<Ex>();
   auto const prefix =
       std::string("terminate called after throwing an instance of ");
   // clang-format off
   return
       folly::kIsGlibcxx ? prefix + "'" + name + "'\\s+what\\(\\):\\s+" + what :
       folly::kIsLibcpp ? prefix + name + ": " + what :
       "" /* empty regex matches anything */;
   // clang-format on
 }
TEST_F (ExceptionTest , throw_exception_direct)
Definition at line 76 of file ExceptionTest.cpp.
References ADD_FAILURE, EXPECT_STREQ, and MyException::what().
{
   try {
     folly::throw_exception<MyException>("hello world");
     ADD_FAILURE();
   } catch (MyException const& ex) {
     EXPECT_STREQ("hello world", ex.what());
   }
 }
TEST_F (ExceptionTest , throw_exception_variadic)
Definition at line 85 of file ExceptionTest.cpp.
References ADD_FAILURE, EXPECT_STREQ, and MyException::what().
{
   try {
     folly::throw_exception<MyException>("hello world", 6);
     ADD_FAILURE();
   } catch (MyException const& ex) {
     EXPECT_STREQ("world", ex.what());
   }
 }
TEST_F (ExceptionTest , terminate_with_direct)
Definition at line 94 of file ExceptionTest.cpp.
{
   EXPECT_DEATH(
       folly::terminate_with<MyException>("hello world"),
       message_for_terminate_with<MyException>("hello world"));
 }
TEST_F (ExceptionTest , terminate_with_variadic)
Definition at line 100 of file ExceptionTest.cpp.
{
   EXPECT_DEATH(
       folly::terminate_with<MyException>("hello world", 6),
       message_for_terminate_with<MyException>("world"));
 }
TEST_F (ExceptionTest , invoke_noreturn_cold)
Definition at line 106 of file ExceptionTest.cpp.
References EXPECT_THROW, folly::invoke_noreturn_cold(), and message_for_terminate().
{
   EXPECT_THROW(
       folly::invoke_noreturn_cold([] { throw std::runtime_error("bad"); }),
       std::runtime_error);
   EXPECT_DEATH(folly::invoke_noreturn_cold([] {}), message_for_terminate());
 }
template<typename Ex > static std::string type_pretty_name () static
Definition at line 27 of file ExceptionTest.cpp.
References min, name, folly::size(), and string.
{
   auto const name = __PRETTY_FUNCTION__;
   auto const size = std::strlen(name);
   auto const eq = std::find(name, name + size, '=');
   auto const sc = std::find(name, name + size, ';');
   auto const br = std::find(name, name + size, ']');
   auto const bpos = name + size - eq >= 2 ? eq + 2 : name + size;
   auto const epos = std::min(sc, br);
   return epos < bpos ? "" : std::string(bpos, epos - bpos);
 }