proxygen: proxygen/lib/utils/test/TimeTest.cpp File Reference
TimeTest.cpp File Reference
#include <folly/portability/GTest.h>
#include <proxygen/lib/utils/Time.h>
Functions
TEST (TimeTest, GetDateTimeStr)
Function Documentation
TEST (TimeTest , GetDateTimeStr)
Definition at line 15 of file TimeTest.cpp.
References ASSERT_EQ, ASSERT_FALSE, folly::empty(), proxygen::getCurrentTime(), proxygen::getDateTimeStr(), now(), and folly::pushmi::__adl::tp.
{
   ASSERT_FALSE(getDateTimeStr(getCurrentTime()).empty());
   SystemClock::time_point sys_tp{}; // epoch timepoint
   SteadyClock::time_point tp = SteadyClock::now() +
     std::chrono::duration_cast<SteadyClock::duration>(
       sys_tp - SystemClock::now());
   ASSERT_EQ("1970-01-01T00:00:00 +0000", getDateTimeStr(tp));
 }