proxygen: proxygen/lib/services/test/AcceptorTest.cpp File Reference
AcceptorTest.cpp File Reference
#include <wangle/acceptor/Acceptor.h>
#include <folly/io/async/EventBase.h>
#include <glog/logging.h>
#include <folly/portability/GTest.h>
Classes
class TestConnection
class TestAcceptor
Functions
TEST (AcceptorTest, Basic)
Function Documentation
TEST (AcceptorTest , Basic)
Definition at line 47 of file AcceptorTest.cpp.
References config, wangle::Acceptor::forceStop(), wangle::Acceptor::getNumConnections(), wangle::Acceptor::getState(), wangle::Acceptor::init(), folly::EventBase::loop(), folly::EventBase::loopForever(), folly::AsyncServerSocket::newSocket(), folly::AsyncSocket::newSocket(), and folly::netops::socket().
{
   EventBase base;
   auto socket = AsyncServerSocket::newSocket(&base);
   ServerSocketConfig config;
   TestAcceptor acceptor(config);
   socket->addAcceptCallback(&acceptor, &base);
   acceptor.init(socket.get(), &base);
   socket->bind(0);
   socket->listen(100);
   SocketAddress addy;
   socket->getAddress(&addy);
   socket->startAccepting();
   auto client_socket = AsyncSocket::newSocket(
     &base, addy);
   base.loopForever();
   CHECK_EQ(acceptor.getNumConnections(), 1);
   CHECK(acceptor.getState() == Acceptor::State::kRunning);
   acceptor.forceStop();
   socket->stopAccepting();
   base.loop();
 }