proxygen: proxygen/lib/test/googletest-release-1.8.0/googlemock/test/gmock_test.cc File Reference
gmock_test.cc File Reference
#include "gmock/gmock.h"
#include <string>
#include "gtest/gtest.h"
Functions
template<typename Char , int M, int N>
void TestInitGoogleMock (const Char *(&argv)[M], const Char *(&new_argv)[N], const ::std::string &expected_gmock_verbose)
TEST (InitGoogleMockTest, ParsesInvalidCommandLine)
TEST (InitGoogleMockTest, ParsesEmptyCommandLine)
TEST (InitGoogleMockTest, ParsesSingleFlag)
TEST (InitGoogleMockTest, ParsesUnrecognizedFlag)
TEST (InitGoogleMockTest, ParsesGoogleMockFlagAndUnrecognizedFlag)
TEST (WideInitGoogleMockTest, ParsesInvalidCommandLine)
TEST (WideInitGoogleMockTest, ParsesEmptyCommandLine)
TEST (WideInitGoogleMockTest, ParsesSingleFlag)
TEST (WideInitGoogleMockTest, ParsesUnrecognizedFlag)
TEST (WideInitGoogleMockTest, ParsesGoogleMockFlagAndUnrecognizedFlag)
TEST (FlagTest, IsAccessibleInCode)
Function Documentation
TEST (InitGoogleMockTest , ParsesInvalidCommandLine)
Definition at line 65 of file gmock_test.cc.
References argv, GMOCK_FLAG, and TestInitGoogleMock().
{
   const char* argv[] = {
     NULL
   };
   const char* new_argv[] = {
     NULL
   };
   TestInitGoogleMock(argv, new_argv, GMOCK_FLAG(verbose));
 }
TEST (InitGoogleMockTest , ParsesEmptyCommandLine)
Definition at line 77 of file gmock_test.cc.
References argv, GMOCK_FLAG, and TestInitGoogleMock().
{
   const char* argv[] = {
     "foo.exe",
     NULL
   };
   const char* new_argv[] = {
     "foo.exe",
     NULL
   };
   TestInitGoogleMock(argv, new_argv, GMOCK_FLAG(verbose));
 }
TEST (InitGoogleMockTest , ParsesSingleFlag)
Definition at line 91 of file gmock_test.cc.
References argv, and TestInitGoogleMock().
{
   const char* argv[] = {
     "foo.exe",
     "--gmock_verbose=info",
     NULL
   };
   const char* new_argv[] = {
     "foo.exe",
     NULL
   };
   TestInitGoogleMock(argv, new_argv, "info");
 }
TEST (InitGoogleMockTest , ParsesUnrecognizedFlag)
Definition at line 106 of file gmock_test.cc.
References argv, GMOCK_FLAG, and TestInitGoogleMock().
{
   const char* argv[] = {
     "foo.exe",
     "--non_gmock_flag=blah",
     NULL
   };
   const char* new_argv[] = {
     "foo.exe",
     "--non_gmock_flag=blah",
     NULL
   };
   TestInitGoogleMock(argv, new_argv, GMOCK_FLAG(verbose));
 }
TEST (InitGoogleMockTest , ParsesGoogleMockFlagAndUnrecognizedFlag)
Definition at line 122 of file gmock_test.cc.
References argv, and TestInitGoogleMock().
{
   const char* argv[] = {
     "foo.exe",
     "--non_gmock_flag=blah",
     "--gmock_verbose=error",
     NULL
   };
   const char* new_argv[] = {
     "foo.exe",
     "--non_gmock_flag=blah",
     NULL
   };
   TestInitGoogleMock(argv, new_argv, "error");
 }
TEST (WideInitGoogleMockTest , ParsesInvalidCommandLine)
Definition at line 139 of file gmock_test.cc.
References argv, GMOCK_FLAG, and TestInitGoogleMock().
{
   const wchar_t* argv[] = {
     NULL
   };
   const wchar_t* new_argv[] = {
     NULL
   };
   TestInitGoogleMock(argv, new_argv, GMOCK_FLAG(verbose));
 }
TEST (WideInitGoogleMockTest , ParsesEmptyCommandLine)
Definition at line 151 of file gmock_test.cc.
References argv, GMOCK_FLAG, and TestInitGoogleMock().
{
   const wchar_t* argv[] = {
     L"foo.exe",
     NULL
   };
   const wchar_t* new_argv[] = {
     L"foo.exe",
     NULL
   };
   TestInitGoogleMock(argv, new_argv, GMOCK_FLAG(verbose));
 }
TEST (WideInitGoogleMockTest , ParsesSingleFlag)
Definition at line 165 of file gmock_test.cc.
References argv, and TestInitGoogleMock().
{
   const wchar_t* argv[] = {
     L"foo.exe",
     L"--gmock_verbose=info",
     NULL
   };
   const wchar_t* new_argv[] = {
     L"foo.exe",
     NULL
   };
   TestInitGoogleMock(argv, new_argv, "info");
 }
TEST (WideInitGoogleMockTest , ParsesUnrecognizedFlag)
Definition at line 180 of file gmock_test.cc.
References argv, GMOCK_FLAG, and TestInitGoogleMock().
{
   const wchar_t* argv[] = {
     L"foo.exe",
     L"--non_gmock_flag=blah",
     NULL
   };
   const wchar_t* new_argv[] = {
     L"foo.exe",
     L"--non_gmock_flag=blah",
     NULL
   };
   TestInitGoogleMock(argv, new_argv, GMOCK_FLAG(verbose));
 }
TEST (WideInitGoogleMockTest , ParsesGoogleMockFlagAndUnrecognizedFlag)
Definition at line 196 of file gmock_test.cc.
References argv, and TestInitGoogleMock().
{
   const wchar_t* argv[] = {
     L"foo.exe",
     L"--non_gmock_flag=blah",
     L"--gmock_verbose=error",
     NULL
   };
   const wchar_t* new_argv[] = {
     L"foo.exe",
     L"--non_gmock_flag=blah",
     NULL
   };
   TestInitGoogleMock(argv, new_argv, "error");
 }
TEST (FlagTest , IsAccessibleInCode)
Definition at line 216 of file gmock_test.cc.
References dummy(), and GMOCK_FLAG.
{
   bool dummy = testing::GMOCK_FLAG(catch_leaked_mocks) &&
       testing::GMOCK_FLAG(verbose) == "";
   (void)dummy;  // Avoids the "unused local variable" warning.
 }
template<typename Char , int M, int N> void TestInitGoogleMock (const Char *(&) argv[M], const Char *(&) new_argv[N], const ::std::string & expected_gmock_verbose)
Definition at line 49 of file gmock_test.cc.
References argv, ASSERT_EQ, EXPECT_EQ, EXPECT_STREQ, GMOCK_FLAG, i, testing::InitGoogleMock(), M, and string.
{
   const ::std::string old_verbose = GMOCK_FLAG(verbose);
   int argc = M;
   InitGoogleMock(&argc, const_cast<Char**>(argv));
   ASSERT_EQ(N, argc) << "The new argv has wrong number of elements.";
   for (int i = 0; i < N; i++) {
     EXPECT_STREQ(new_argv[i], argv[i]);
   }
   EXPECT_EQ(expected_gmock_verbose, GMOCK_FLAG(verbose).c_str());
   GMOCK_FLAG(verbose) = old_verbose;  // Restores the gmock_verbose flag.
 }