proxygen: proxygen/lib/test/googletest-release-1.8.0/googletest/test/gtest_xml_output_unittest_.cc File Reference
gtest_xml_output_unittest_.cc File Reference
#include "gtest/gtest.h"
Classes
class SuccessfulTest
class FailedTest
class DisabledTest
class PropertyRecordingTest
class ValueParamTest
Functions
TEST_F (SuccessfulTest, Succeeds)
TEST_F (FailedTest, Fails)
TEST_F (DisabledTest, DISABLED_test_not_run)
TEST (MixedResultTest, Succeeds)
TEST (MixedResultTest, Fails)
TEST (MixedResultTest, DISABLED_test)
TEST (XmlQuotingTest, OutputsCData)
TEST (InvalidCharactersTest, InvalidCharactersInMessage)
TEST_F (PropertyRecordingTest, OneProperty)
TEST_F (PropertyRecordingTest, IntValuedProperty)
TEST_F (PropertyRecordingTest, ThreeProperties)
TEST_F (PropertyRecordingTest, TwoValuesForOneKeyUsesLastValue)
TEST (NoFixtureTest, RecordProperty)
void ExternalUtilityThatCallsRecordProperty (const std::string &key, int value)
void ExternalUtilityThatCallsRecordProperty (const std::string &key, const std::string &value)
TEST (NoFixtureTest, ExternalUtilityThatCallsRecordIntValuedProperty)
TEST (NoFixtureTest, ExternalUtilityThatCallsRecordStringValuedProperty)
TEST_P (ValueParamTest, HasValueParamAttribute)
TEST_P (ValueParamTest, AnotherTestThatHasValueParamAttribute)
INSTANTIATE_TEST_CASE_P (Single, ValueParamTest, Values(33, 42))
int main (int argc, char **argv)
Function Documentation
void ExternalUtilityThatCallsRecordProperty (const std::string & key, int value)
Definition at line 126 of file gtest_xml_output_unittest_.cc.
References testing::Test::RecordProperty().
{
   testing::Test::RecordProperty(key, value);
 }
void ExternalUtilityThatCallsRecordProperty (const std::string & key, const std::string & value)
Definition at line 130 of file gtest_xml_output_unittest_.cc.
References testing::Test::RecordProperty().
{
   testing::Test::RecordProperty(key, value);
 }
INSTANTIATE_TEST_CASE_P (Single , ValueParamTest , Values(33, 42))
int main (int argc, char ** argv)
Definition at line 172 of file gtest_xml_output_unittest_.cc.
References testing::InitGoogleTest(), testing::Test::RecordProperty(), and RUN_ALL_TESTS().
{
   InitGoogleTest(&argc, argv);
   if (argc > 1 && strcmp(argv[1], "--shut_down_xml") == 0) {
     TestEventListeners& listeners = UnitTest::GetInstance()->listeners();
     delete listeners.Release(listeners.default_xml_generator());
   }
   testing::Test::RecordProperty("ad_hoc_property", "42");
   return RUN_ALL_TESTS();
 }
TEST (MixedResultTest , Succeeds)
Definition at line 72 of file gtest_xml_output_unittest_.cc.
References ASSERT_EQ, and EXPECT_EQ.
{
   EXPECT_EQ(1, 1);
   ASSERT_EQ(1, 1);
 }
TEST (MixedResultTest , Fails)
Definition at line 77 of file gtest_xml_output_unittest_.cc.
References ASSERT_EQ, and EXPECT_EQ.
{
   EXPECT_EQ(1, 2);
   ASSERT_EQ(2, 3);
 }
TEST (MixedResultTest , DISABLED_test)
Definition at line 82 of file gtest_xml_output_unittest_.cc.
References FAIL.
{
   FAIL() << "Unexpected failure: Disabled test should not be run";
 }
TEST (XmlQuotingTest , OutputsCData)
Definition at line 86 of file gtest_xml_output_unittest_.cc.
References FAIL.
{
   FAIL() << "XML output: "
             "<?xml encoding=\"utf-8\"><top><![CDATA[cdata text]]></top>";
 }
TEST (InvalidCharactersTest , InvalidCharactersInMessage)
Definition at line 93 of file gtest_xml_output_unittest_.cc.
References FAIL.
{
   FAIL() << "Invalid characters in brackets [\x1\x2]";
 }
TEST (NoFixtureTest , RecordProperty)
Definition at line 122 of file gtest_xml_output_unittest_.cc.
{
   RecordProperty("key", "1");
 }
TEST (NoFixtureTest , ExternalUtilityThatCallsRecordIntValuedProperty)
Definition at line 135 of file gtest_xml_output_unittest_.cc.
References ExternalUtilityThatCallsRecordProperty().
{
   ExternalUtilityThatCallsRecordProperty("key_for_utility_int", 1);
 }
TEST (NoFixtureTest , ExternalUtilityThatCallsRecordStringValuedProperty)
Definition at line 139 of file gtest_xml_output_unittest_.cc.
References ExternalUtilityThatCallsRecordProperty().
{
   ExternalUtilityThatCallsRecordProperty("key_for_utility_string", "1");
 }
TEST_F (SuccessfulTest , Succeeds)
Definition at line 53 of file gtest_xml_output_unittest_.cc.
References ASSERT_EQ, and SUCCEED.
{
   SUCCEED() << "This is a success.";
   ASSERT_EQ(1, 1);
 }
TEST_F (FailedTest , Fails)
Definition at line 61 of file gtest_xml_output_unittest_.cc.
References ASSERT_EQ.
{
   ASSERT_EQ(1, 2);
 }
TEST_F (DisabledTest , DISABLED_test_not_run)
Definition at line 68 of file gtest_xml_output_unittest_.cc.
References FAIL.
{
   FAIL() << "Unexpected failure: Disabled test should not be run";
 }
TEST_F (PropertyRecordingTest , OneProperty)
Definition at line 103 of file gtest_xml_output_unittest_.cc.
{
   RecordProperty("key_1", "1");
 }
TEST_F (PropertyRecordingTest , IntValuedProperty)
Definition at line 107 of file gtest_xml_output_unittest_.cc.
{
   RecordProperty("key_int", 1);
 }
TEST_F (PropertyRecordingTest , ThreeProperties)
Definition at line 111 of file gtest_xml_output_unittest_.cc.
{
   RecordProperty("key_1", "1");
   RecordProperty("key_2", "2");
   RecordProperty("key_3", "3");
 }
TEST_F (PropertyRecordingTest , TwoValuesForOneKeyUsesLastValue)
Definition at line 117 of file gtest_xml_output_unittest_.cc.
{
   RecordProperty("key_1", "1");
   RecordProperty("key_1", "2");
 }
TEST_P (ValueParamTest , HasValueParamAttribute)
Definition at line 146 of file gtest_xml_output_unittest_.cc.
 {}
TEST_P (ValueParamTest , AnotherTestThatHasValueParamAttribute)
Definition at line 147 of file gtest_xml_output_unittest_.cc.
References INSTANTIATE_TEST_CASE_P(), INSTANTIATE_TYPED_TEST_CASE_P(), REGISTER_TYPED_TEST_CASE_P(), testing::Test::Test(), TYPED_TEST(), TYPED_TEST_CASE(), TYPED_TEST_CASE_P(), and TYPED_TEST_P().
 {}