proxygen: proxygen/folly/folly/memory/test/MallctlHelperTest.cpp File Reference
MallctlHelperTest.cpp File Reference
#include <folly/memory/MallctlHelper.h>
#include <folly/CPortability.h>
#include <folly/init/Init.h>
#include <folly/memory/Malloc.h>
#include <folly/portability/GTest.h>
Classes
class MallctlHelperTest
Functions
TEST_F (MallctlHelperTest, valid_read)
TEST_F (MallctlHelperTest, invalid_read)
TEST_F (MallctlHelperTest, valid_write)
TEST_F (MallctlHelperTest, invalid_write)
TEST_F (MallctlHelperTest, valid_read_write)
TEST_F (MallctlHelperTest, invalid_read_write)
TEST_F (MallctlHelperTest, valid_call)
TEST_F (MallctlHelperTest, invalid_call)
int main (int argc, char **argv)
Variables
static constexpr char const * kDecayCmd = "arena.0.decay_time"
const char * malloc_conf = "purge:decay,decay_time:10"
Function Documentation
int main (int argc, char ** argv)
Definition at line 102 of file MallctlHelperTest.cpp.
References folly::init(), testing::InitGoogleTest(), RUN_ALL_TESTS(), and folly::usingJEMalloc().
{
   ::testing::InitGoogleTest(&argc, argv);
   init(&argc, &argv);
   return usingJEMalloc() ? RUN_ALL_TESTS() : 0;
 }
TEST_F (MallctlHelperTest , valid_read)
Definition at line 52 of file MallctlHelperTest.cpp.
References EXPECT_EQ, EXPECT_NO_THROW, kDecayCmd, and folly::mallctlRead().
{
   ssize_t decayTime = 0;
   EXPECT_NO_THROW(mallctlRead(kDecayCmd, &decayTime));
   EXPECT_EQ(10, decayTime);
 }
TEST_F (MallctlHelperTest , invalid_read)
Definition at line 58 of file MallctlHelperTest.cpp.
References EXPECT_EQ, EXPECT_THROW, and folly::mallctlRead().
{
   ssize_t decayTime = 0;
   EXPECT_THROW(mallctlRead("invalid", &decayTime), std::runtime_error);
   EXPECT_EQ(0, decayTime);
 }
TEST_F (MallctlHelperTest , valid_write)
Definition at line 64 of file MallctlHelperTest.cpp.
References EXPECT_EQ, EXPECT_NO_THROW, kDecayCmd, and folly::mallctlWrite().
{
   ssize_t decayTime = 20;
   EXPECT_NO_THROW(mallctlWrite(kDecayCmd, decayTime));
   EXPECT_EQ(20, readArena0DecayTime());
 }
TEST_F (MallctlHelperTest , invalid_write)
Definition at line 70 of file MallctlHelperTest.cpp.
References EXPECT_EQ, EXPECT_THROW, and folly::mallctlWrite().
{
   ssize_t decayTime = 20;
   EXPECT_THROW(mallctlWrite("invalid", decayTime), std::runtime_error);
   EXPECT_EQ(10, readArena0DecayTime());
 }
TEST_F (MallctlHelperTest , valid_read_write)
Definition at line 76 of file MallctlHelperTest.cpp.
References EXPECT_EQ, EXPECT_NO_THROW, kDecayCmd, and folly::mallctlReadWrite().
{
   ssize_t oldDecayTime = 0;
   ssize_t newDecayTime = 20;
   EXPECT_NO_THROW(mallctlReadWrite(kDecayCmd, &oldDecayTime, newDecayTime));
   EXPECT_EQ(10, oldDecayTime);
   EXPECT_EQ(20, readArena0DecayTime());
 }
TEST_F (MallctlHelperTest , invalid_read_write)
Definition at line 84 of file MallctlHelperTest.cpp.
References EXPECT_EQ, EXPECT_THROW, and folly::mallctlReadWrite().
{
   ssize_t oldDecayTime = 0;
   ssize_t newDecayTime = 20;
   EXPECT_THROW(
       mallctlReadWrite("invalid", &oldDecayTime, newDecayTime),
       std::runtime_error);
   EXPECT_EQ(0, oldDecayTime);
   EXPECT_EQ(10, readArena0DecayTime());
 }
TEST_F (MallctlHelperTest , valid_call)
Definition at line 94 of file MallctlHelperTest.cpp.
References EXPECT_NO_THROW, and folly::mallctlCall().
{
   EXPECT_NO_THROW(mallctlCall("arena.0.decay"));
 }
TEST_F (MallctlHelperTest , invalid_call)
Definition at line 98 of file MallctlHelperTest.cpp.
References EXPECT_THROW, and folly::mallctlCall().
{
   EXPECT_THROW(mallctlCall("invalid"), std::runtime_error);
 }
Variable Documentation
constexpr char const* kDecayCmd = "arena.0.decay_time" static
Definition at line 33 of file MallctlHelperTest.cpp.
Referenced by MallctlHelperTest::readArena0DecayTime(), MallctlHelperTest::TearDown(), and TEST_F().
const char* malloc_conf = "purge:decay,decay_time:10"
Definition at line 34 of file MallctlHelperTest.cpp.