proxygen: proxygen/folly/folly/memory/detail/MallocImpl.cpp File Reference
MallocImpl.cpp File Reference
#include <folly/memory/detail/MallocImpl.h>
Variables
void *(* mallocx)(size_t, int) = nullptr
void *(* rallocx)(void *, size_t, int) = nullptr
size_t(* xallocx)(void *, size_t, size_t, int) = nullptr
size_t(* sallocx)(const void *, int) = nullptr
void(* dallocx)(void *, int) = nullptr
void(* sdallocx)(void *, size_t, int) = nullptr
size_t(* nallocx)(size_t, int) = nullptr
int(* mallctl)(const char *, void *, size_t *, void *, size_t) = nullptr
int(* mallctlnametomib)(const char *, size_t *, size_t *) = nullptr
int(* mallctlbymib)(const size_t *, size_t, void *, size_t *, void *, size_t)
Variable Documentation
void(* dallocx) (void *, int) = nullptr
Definition at line 39 of file MallocImpl.cpp.
Referenced by folly::JemallocHugePageAllocator::deallocate(), folly::JemallocNodumpAllocator::deallocate(), and folly::usingJEMalloc().
int(* mallctl) (const char *, void *, size_t *, void *, size_t) = nullptr
Definition at line 42 of file MallocImpl.cpp.
Referenced by folly::JemallocNodumpAllocator::extend_and_setup_arena(), folly::detail::MemoryIdler::flushLocalMallocCaches(), folly::detail::mallctlHelper(), and folly::usingJEMalloc().
int(* mallctlbymib) (const size_t *, size_t, void *, size_t *, void *, size_t)
Initial value:
=
    nullptr
Definition at line 44 of file MallocImpl.cpp.
Referenced by folly::detail::MemoryIdler::flushLocalMallocCaches(), and folly::usingJEMalloc().
int(* mallctlnametomib) (const char *, size_t *, size_t *) = nullptr
Definition at line 43 of file MallocImpl.cpp.
Referenced by folly::detail::MemoryIdler::flushLocalMallocCaches(), and folly::usingJEMalloc().
void*(* mallocx) (size_t, int) = nullptr
Definition at line 35 of file MallocImpl.cpp.
Referenced by folly::JemallocHugePageAllocator::allocate(), folly::JemallocNodumpAllocator::allocate(), folly::threadlocal_detail::StaticMetaBase::reallocate(), and folly::usingJEMalloc().
size_t(* nallocx) (size_t, int) = nullptr
Definition at line 41 of file MallocImpl.cpp.
Referenced by folly::goodMallocSize(), folly::threadlocal_detail::StaticMetaBase::reallocate(), and folly::usingJEMalloc().
void*(* rallocx) (void *, size_t, int) = nullptr
Definition at line 36 of file MallocImpl.cpp.
Referenced by folly::JemallocHugePageAllocator::reallocate(), folly::JemallocNodumpAllocator::reallocate(), and folly::usingJEMalloc().
size_t(* sallocx) (const void *, int) = nullptr
Definition at line 38 of file MallocImpl.cpp.
Referenced by folly::usingJEMalloc().
void(* sdallocx) (void *, size_t, int) = nullptr
Definition at line 40 of file MallocImpl.cpp.
Referenced by folly::usingJEMalloc().
size_t(* xallocx) (void *, size_t, size_t, int) = nullptr
Definition at line 37 of file MallocImpl.cpp.
Referenced by folly::fbvector< T, Allocator >::emplace_back_aux(), folly::threadlocal_detail::StaticMetaBase::reallocate(), folly::fbvector< HTTPHeaderCode >::reserve_in_place(), folly::IOBuf::reserveSlow(), folly::fbvector< HTTPHeaderCode >::shrink_to_fit(), and folly::usingJEMalloc().