proxygen: proxygen/folly/folly/test/MapUtilTest.cpp File Reference
MapUtilTest.cpp File Reference
#include <folly/MapUtil.h>
#include <cstddef>
#include <map>
#include <unordered_map>
#include <folly/Traits.h>
#include <folly/portability/GTest.h>
Functions
TEST (MapUtil, get_default)
TEST (MapUtil, get_default_function)
TEST (MapUtil, get_or_throw)
TEST (MapUtil, get_or_throw_specified)
TEST (MapUtil, get_optional)
TEST (MapUtil, get_optional_path_simple)
TEST (MapUtil, get_optional_path_mixed)
TEST (MapUtil, get_ref_default)
TEST (MapUtil, get_ref_default_function)
TEST (MapUtil, get_ptr)
TEST (MapUtil, get_ptr_path_simple)
TEST (MapUtil, get_ptr_path_mixed)
TEST (MapUtil, get_default_temporary)
TEST (MapUtil, get_default_path)
TEST (MapUtil, get_default_path_mixed)
TEST (MapUtil, get_ref_default_path)
TEST (MapUtil, get_ref_default_path_mixed)
TEST (MapUtil, get_ref_default_path_temporary)
TEST (MapUtil, test_get_default_deferred_construction)
Function Documentation
TEST (MapUtil , get_default)
Definition at line 28 of file MapUtilTest.cpp.
References EXPECT_EQ, folly::get_default(), and m.
{
   std::map<int, int> m;
   m[1] = 2;
   EXPECT_EQ(2, get_default(m, 1, 42));
   EXPECT_EQ(42, get_default(m, 2, 42));
   EXPECT_EQ(0, get_default(m, 3));
 }
TEST (MapUtil , get_default_function)
Definition at line 36 of file MapUtilTest.cpp.
References EXPECT_EQ, folly::get_default(), and m.
{
   std::map<int, int> m;
   m[1] = 2;
   EXPECT_EQ(2, get_default(m, 1, [] { return 42; }));
   EXPECT_EQ(42, get_default(m, 2, [] { return 42; }));
   EXPECT_EQ(0, get_default(m, 3));
 }
TEST (MapUtil , get_or_throw)
Definition at line 44 of file MapUtilTest.cpp.
References EXPECT_EQ, EXPECT_THROW, folly::get_or_throw(), and m.
{
   std::map<int, int> m;
   m[1] = 2;
   EXPECT_EQ(2, get_or_throw(m, 1));
   EXPECT_THROW(get_or_throw(m, 2), std::out_of_range);
   EXPECT_EQ(&m[1], &get_or_throw(m, 1));
   get_or_throw(m, 1) = 3;
   EXPECT_EQ(3, get_or_throw(m, 1));
   const auto& cm = m;
   EXPECT_EQ(&m[1], &get_or_throw(cm, 1));
   EXPECT_EQ(3, get_or_throw(cm, 1));
   EXPECT_THROW(get_or_throw(cm, 2), std::out_of_range);
 }
TEST (MapUtil , get_or_throw_specified)
Definition at line 58 of file MapUtilTest.cpp.
References EXPECT_EQ, EXPECT_THROW, and m.
{
   std::map<int, int> m;
   m[1] = 2;
   EXPECT_EQ(2, get_or_throw<std::runtime_error>(m, 1));
   EXPECT_THROW(get_or_throw<std::runtime_error>(m, 2), std::runtime_error);
 }
TEST (MapUtil , get_optional)
Definition at line 65 of file MapUtilTest.cpp.
References EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, folly::get_optional(), m, and folly::value().
{
   std::map<int, int> m;
   m[1] = 2;
   EXPECT_TRUE(get_optional(m, 1).hasValue());
   EXPECT_EQ(2, get_optional(m, 1).value());
   EXPECT_FALSE(get_optional(m, 2).hasValue());
 }
TEST (MapUtil , get_optional_path_simple)
Definition at line 73 of file MapUtilTest.cpp.
References EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, folly::get_optional(), m, and map().
{
   using std::map;
   map<int, map<int, map<int, map<int, int>>>> m{{1, {{2, {{3, {{4, 5}}}}}}}};
   EXPECT_EQ(folly::Optional<int>(5), get_optional(m, 1, 2, 3, 4));
   EXPECT_TRUE(get_optional(m, 1, 2, 3, 4));
   EXPECT_FALSE(get_optional(m, 1, 2, 3, 0));
   EXPECT_TRUE(get_optional(m, 1, 2, 3));
   EXPECT_FALSE(get_optional(m, 1, 2, 0));
   EXPECT_TRUE(get_optional(m, 1, 2));
   EXPECT_FALSE(get_optional(m, 1, 0));
   EXPECT_TRUE(get_optional(m, 1));
   EXPECT_FALSE(get_optional(m, 0));
 }
TEST (MapUtil , get_optional_path_mixed)
Definition at line 87 of file MapUtilTest.cpp.
References EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, folly::get_optional(), m, map(), and string.
{
   using std::map;
   using std::string;
   using std::unordered_map;
   unordered_map<string, map<int, map<string, int>>> m{{"a", {{1, {{"b", 2}}}}}};
   EXPECT_EQ(folly::Optional<int>(2), get_optional(m, "a", 1, "b"));
   EXPECT_TRUE(get_optional(m, "a", 1, "b"));
   EXPECT_FALSE(get_optional(m, "b", 1, "b"));
   EXPECT_FALSE(get_optional(m, "a", 2, "b"));
   EXPECT_FALSE(get_optional(m, "a", 1, "c"));
   EXPECT_TRUE(get_optional(m, "a", 1));
   EXPECT_TRUE(get_optional(m, "a"));
 }
TEST (MapUtil , get_ref_default)
Definition at line 101 of file MapUtilTest.cpp.
References EXPECT_EQ, folly::get_ref_default(), i, and m.
{
   std::map<int, int> m;
   m[1] = 2;
   const int i = 42;
   EXPECT_EQ(2, get_ref_default(m, 1, i));
   EXPECT_EQ(42, get_ref_default(m, 2, i));
   EXPECT_EQ(std::addressof(i), std::addressof(get_ref_default(m, 2, i)));
 }
TEST (MapUtil , get_ref_default_function)
Definition at line 110 of file MapUtilTest.cpp.
References EXPECT_EQ, folly::get_ref_default(), i, and m.
{
   std::map<int, int> m;
   m[1] = 2;
   const int i = 42;
   EXPECT_EQ(2, get_ref_default(m, 1, [&i]() -> const int& { return i; }));
   EXPECT_EQ(42, get_ref_default(m, 2, [&i]() -> const int& { return i; }));
   EXPECT_EQ(
       std::addressof(i),
       std::addressof(
           get_ref_default(m, 2, [&i]() -> const int& { return i; })));
   // statically disallowed:
   // get_ref_default(m, 2, [] { return 7; });
 }
TEST (MapUtil , get_ptr)
Definition at line 124 of file MapUtilTest.cpp.
References EXPECT_EQ, EXPECT_TRUE, folly::get_ptr(), and m.
{
   std::map<int, int> m;
   m[1] = 2;
   EXPECT_EQ(2, *get_ptr(m, 1));
   EXPECT_TRUE(get_ptr(m, 2) == nullptr);
   *get_ptr(m, 1) = 4;
   EXPECT_EQ(4, m.at(1));
 }
TEST (MapUtil , get_ptr_path_simple)
Definition at line 133 of file MapUtilTest.cpp.
References EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, folly::get_ptr(), m, and map().
{
   using std::map;
   map<int, map<int, map<int, map<int, int>>>> m{{1, {{2, {{3, {{4, 5}}}}}}}};
   EXPECT_EQ(5, *get_ptr(m, 1, 2, 3, 4));
   EXPECT_TRUE(get_ptr(m, 1, 2, 3, 4));
   EXPECT_FALSE(get_ptr(m, 1, 2, 3, 0));
   EXPECT_TRUE(get_ptr(m, 1, 2, 3));
   EXPECT_FALSE(get_ptr(m, 1, 2, 0));
   EXPECT_TRUE(get_ptr(m, 1, 2));
   EXPECT_FALSE(get_ptr(m, 1, 0));
   EXPECT_TRUE(get_ptr(m, 1));
   EXPECT_FALSE(get_ptr(m, 0));
   const auto& cm = m;
   ++*get_ptr(m, 1, 2, 3, 4);
   EXPECT_EQ(6, *get_ptr(cm, 1, 2, 3, 4));
   EXPECT_TRUE(get_ptr(cm, 1, 2, 3, 4));
   EXPECT_FALSE(get_ptr(cm, 1, 2, 3, 0));
 }
TEST (MapUtil , get_ptr_path_mixed)
Definition at line 152 of file MapUtilTest.cpp.
References EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, folly::get_ptr(), m, map(), string, folly::T, and type.
{
   using std::map;
   using std::string;
   using std::unordered_map;
   unordered_map<string, map<int, map<string, int>>> m{{"a", {{1, {{"b", 7}}}}}};
   EXPECT_EQ(7, *get_ptr(m, "a", 1, "b"));
   EXPECT_TRUE(get_ptr(m, "a", 1, "b"));
   EXPECT_FALSE(get_ptr(m, "b", 1, "b"));
   EXPECT_FALSE(get_ptr(m, "a", 2, "b"));
   EXPECT_FALSE(get_ptr(m, "a", 1, "c"));
   EXPECT_TRUE(get_ptr(m, "a", 1));
   EXPECT_TRUE(get_ptr(m, "a"));
   const auto& cm = m;
   ++*get_ptr(m, "a", 1, "b");
   EXPECT_EQ(8, *get_ptr(cm, "a", 1, "b"));
   EXPECT_TRUE(get_ptr(cm, "a", 1, "b"));
   EXPECT_FALSE(get_ptr(cm, "b", 1, "b"));
 }
TEST (MapUtil , get_default_temporary)
Definition at line 197 of file MapUtilTest.cpp.
References EXPECT_FALSE, EXPECT_TRUE, value, and folly::value().
{
   EXPECT_TRUE(Compiles<const int&>::value);
   EXPECT_TRUE(Compiles<int&>::value);
   EXPECT_FALSE(Compiles<const int&&>::value);
   EXPECT_FALSE(Compiles<int&&>::value);
   EXPECT_TRUE(Compiles<const int&()>::value);
   EXPECT_TRUE(Compiles<int&()>::value);
   EXPECT_FALSE(Compiles<int()>::value);
 }
TEST (MapUtil , get_default_path)
Definition at line 208 of file MapUtilTest.cpp.
References EXPECT_EQ, folly::get_default(), m, and map().
{
   using std::map;
   map<int, map<int, int>> m;
   m[4][2] = 42;
   EXPECT_EQ(42, get_default(m, 4, 2, 42));
   EXPECT_EQ(42, get_default(m, 1, 3, 42));
 }
TEST (MapUtil , get_default_path_mixed)
Definition at line 216 of file MapUtilTest.cpp.
References EXPECT_EQ, folly::get_default(), m, map(), string, and folly::value().
{
   using std::map;
   using std::string;
   using std::unordered_map;
   map<int, unordered_map<string, StringPiece>> m;
   int key1 = 42;
   const string key2 = "hello";
   constexpr StringPiece value = "world";
   constexpr StringPiece dflt = "default";
   m[key1][key2] = value;
   EXPECT_EQ(value, get_default(m, 42, key2, dflt));
   EXPECT_EQ(value, get_default(m, key1, "hello", dflt));
   EXPECT_EQ(dflt, get_default(m, 0, key2, dflt));
   EXPECT_EQ(dflt, get_default(m, key1, "bad", "default"));
 }
TEST (MapUtil , get_ref_default_path)
Definition at line 232 of file MapUtilTest.cpp.
References EXPECT_EQ, folly::get_ref_default(), m, and map().
{
   using std::map;
   map<int, map<int, int>> m;
   m[4][2] = 42;
   const int dflt = 13;
   EXPECT_EQ(42, get_ref_default(m, 4, 2, dflt));
   EXPECT_EQ(dflt, get_ref_default(m, 1, 3, dflt));
 }
TEST (MapUtil , get_ref_default_path_mixed)
Definition at line 241 of file MapUtilTest.cpp.
References EXPECT_EQ, folly::get_ref_default(), m, map(), string, and folly::value().
{
   using std::map;
   using std::string;
   using std::unordered_map;
   map<int, unordered_map<string, StringPiece>> m;
   int key1 = 42;
   const string key2 = "hello";
   constexpr StringPiece value = "world";
   constexpr StringPiece dflt = "default";
   m[key1][key2] = value;
   EXPECT_EQ(value, get_ref_default(m, 42, key2, dflt));
   EXPECT_EQ(value, get_ref_default(m, key1, "hello", dflt));
   EXPECT_EQ(dflt, get_ref_default(m, 0, key2, dflt));
   EXPECT_EQ(dflt, get_ref_default(m, key1, "bad", dflt));
 }
TEST (MapUtil , get_ref_default_path_temporary)
Definition at line 271 of file MapUtilTest.cpp.
References EXPECT_FALSE, EXPECT_TRUE, integer_, folly::gen::move, string, and value.
{
   EXPECT_TRUE(GetRefDefaultPathCompiles<const int&>::value);
   EXPECT_TRUE(GetRefDefaultPathCompiles<int&>::value);
   EXPECT_FALSE(GetRefDefaultPathCompiles<const int&&>::value);
   EXPECT_FALSE(GetRefDefaultPathCompiles<int&&>::value);
 }
TEST (MapUtil , test_get_default_deferred_construction)
Definition at line 305 of file MapUtilTest.cpp.
References EXPECT_EQ, folly::get_default(), and val.
{
   auto map = std::unordered_map<int, TestConstruction>{};
   map.emplace(
       std::piecewise_construct,
       std::forward_as_tuple(1),
       std::forward_as_tuple(1));
   EXPECT_EQ(map.at(1).integer_, 1);
   {
     auto val = get_default(map, 0, 1);
     EXPECT_EQ(val.integer_, 1);
     EXPECT_EQ(val.string_, "");
   }
   {
     auto val = get_default(map, 0, "something");
     EXPECT_EQ(val.integer_, 0);
     EXPECT_EQ(val.string_, "something");
   }
 }