proxygen: proxygen/folly/folly/test/MathBenchmark.cpp File Reference
MathBenchmark.cpp File Reference
#include <folly/Math.h>
#include <algorithm>
#include <random>
#include <folly/Benchmark.h>
Functions
BENCHMARK_DRAW_LINE ()
BENCHMARK (divTruncInt8, iters)
BENCHMARK (divFloorInt8, iters)
BENCHMARK (divCeilInt8, iters)
BENCHMARK_RELATIVE (branchlessDivCeilInt8, iters)
BENCHMARK_RELATIVE (branchfulDivCeilInt8, iters)
BENCHMARK_RELATIVE (brokenButWidespreadDivCeilInt8, iters)
BENCHMARK_RELATIVE (viaFloatDivCeilInt8, iters)
BENCHMARK_RELATIVE (viaDoubleDivCeilInt8, iters)
BENCHMARK_RELATIVE (viaLongDoubleDivCeilInt8, iters)
BENCHMARK (divRoundAwayInt8, iters)
BENCHMARK (divTruncInt16, iters)
BENCHMARK (divFloorInt16, iters)
BENCHMARK (divCeilInt16, iters)
BENCHMARK_RELATIVE (branchlessDivCeilInt16, iters)
BENCHMARK_RELATIVE (branchfulDivCeilInt16, iters)
BENCHMARK_RELATIVE (brokenButWidespreadDivCeilInt16, iters)
BENCHMARK_RELATIVE (viaFloatDivCeilInt16, iters)
BENCHMARK_RELATIVE (viaDoubleDivCeilInt16, iters)
BENCHMARK_RELATIVE (viaLongDoubleDivCeilInt16, iters)
BENCHMARK (divRoundAwayInt16, iters)
BENCHMARK (divTruncInt32, iters)
BENCHMARK (divFloorInt32, iters)
BENCHMARK (divCeilInt32, iters)
BENCHMARK_RELATIVE (branchlessDivCeilInt32, iters)
BENCHMARK_RELATIVE (branchfulDivCeilInt32, iters)
BENCHMARK_RELATIVE (brokenButWidespreadDivCeilInt32, iters)
BENCHMARK_RELATIVE (approxViaFloatDivCeilInt32, iters)
BENCHMARK_RELATIVE (viaDoubleDivCeilInt32, iters)
BENCHMARK_RELATIVE (viaLongDoubleDivCeilInt32, iters)
BENCHMARK (divRoundAwayInt32, iters)
BENCHMARK (divTruncInt64, iters)
BENCHMARK (divFloorInt64, iters)
BENCHMARK (divCeilInt64, iters)
BENCHMARK_RELATIVE (branchlessDivCeilInt64, iters)
BENCHMARK_RELATIVE (branchfulDivCeilInt64, iters)
BENCHMARK_RELATIVE (brokenButWidespreadDivCeilInt64, iters)
BENCHMARK_RELATIVE (approxViaFloatDivCeilInt64, iters)
BENCHMARK_RELATIVE (approxViaDoubleDivCeilInt64, iters)
BENCHMARK_RELATIVE (viaLongDoubleDivCeilInt64, iters)
BENCHMARK (divRoundAwayInt64, iters)
BENCHMARK (divTruncUint8, iters)
BENCHMARK (divFloorUint8, iters)
BENCHMARK (divCeilUint8, iters)
BENCHMARK_RELATIVE (branchlessDivCeilUint8, iters)
BENCHMARK_RELATIVE (branchfulDivCeilUint8, iters)
BENCHMARK_RELATIVE (brokenButWidespreadDivCeilUint8, iters)
BENCHMARK_RELATIVE (viaFloatDivCeilUint8, iters)
BENCHMARK_RELATIVE (viaDoubleDivCeilUint8, iters)
BENCHMARK_RELATIVE (viaLongDoubleDivCeilUint8, iters)
BENCHMARK (divRoundAwayUint8, iters)
BENCHMARK (divTruncUint16, iters)
BENCHMARK (divFloorUint16, iters)
BENCHMARK (divCeilUint16, iters)
BENCHMARK_RELATIVE (branchlessDivCeilUint16, iters)
BENCHMARK_RELATIVE (branchfulDivCeilUint16, iters)
BENCHMARK_RELATIVE (brokenButWidespreadDivCeilUint16, iters)
BENCHMARK_RELATIVE (viaFloatDivCeilUint16, iters)
BENCHMARK_RELATIVE (viaDoubleDivCeilUint16, iters)
BENCHMARK_RELATIVE (viaLongDoubleDivCeilUint16, iters)
BENCHMARK (divRoundAwayUint16, iters)
BENCHMARK (divTruncUint32, iters)
BENCHMARK (divFloorUint32, iters)
BENCHMARK (divCeilUint32, iters)
BENCHMARK_RELATIVE (branchlessDivCeilUint32, iters)
BENCHMARK_RELATIVE (branchfulDivCeilUint32, iters)
BENCHMARK_RELATIVE (brokenButWidespreadDivCeilUint32, iters)
BENCHMARK_RELATIVE (approxViaFloatDivCeilUint32, iters)
BENCHMARK_RELATIVE (viaDoubleDivCeilUint32, iters)
BENCHMARK_RELATIVE (viaLongDoubleDivCeilUint32, iters)
BENCHMARK (divRoundAwayUint32, iters)
BENCHMARK (divTruncUint64, iters)
BENCHMARK (divFloorUint64, iters)
BENCHMARK (divCeilUint64, iters)
BENCHMARK_RELATIVE (branchlessDivCeilUint64, iters)
BENCHMARK_RELATIVE (branchfulDivCeilUint64, iters)
BENCHMARK_RELATIVE (brokenButWidespreadDivCeilUint64, iters)
BENCHMARK_RELATIVE (approxViaFloatDivCeilUint64, iters)
BENCHMARK_RELATIVE (approxViaDoubleDivCeilUint64, iters)
BENCHMARK_RELATIVE (viaLongDoubleDivCeilUint64, iters)
BENCHMARK (divRoundAwayUint64, iters)
int main (int argc, char **argv)
Function Documentation
BENCHMARK (divTruncInt8 , iters)
Definition at line 95 of file MathBenchmark.cpp.
{
   runDivTests<int8_t>(&folly::divTrunc<int8_t, int8_t>, iters);
 }
BENCHMARK (divFloorInt8 , iters)
Definition at line 98 of file MathBenchmark.cpp.
{
   runDivTests<int8_t>(&folly::divFloor<int8_t, int8_t>, iters);
 }
BENCHMARK (divCeilInt8 , iters)
Definition at line 101 of file MathBenchmark.cpp.
{
   runDivTests<int8_t>(&folly::divCeil<int8_t, int8_t>, iters);
 }
BENCHMARK (divRoundAwayInt8 , iters)
Definition at line 122 of file MathBenchmark.cpp.
References BENCHMARK_DRAW_LINE().
{
   runDivTests<int8_t>(&folly::divRoundAway<int8_t, int8_t>, iters);
 }
BENCHMARK (divTruncInt16 , iters)
Definition at line 127 of file MathBenchmark.cpp.
{
   runDivTests<int16_t>(&folly::divTrunc<int16_t, int16_t>, iters);
 }
BENCHMARK (divFloorInt16 , iters)
Definition at line 130 of file MathBenchmark.cpp.
{
   runDivTests<int16_t>(&folly::divFloor<int16_t, int16_t>, iters);
 }
BENCHMARK (divCeilInt16 , iters)
Definition at line 133 of file MathBenchmark.cpp.
{
   runDivTests<int16_t>(&folly::divCeil<int16_t, int16_t>, iters);
 }
BENCHMARK (divRoundAwayInt16 , iters)
Definition at line 154 of file MathBenchmark.cpp.
References BENCHMARK_DRAW_LINE().
{
   runDivTests<int16_t>(&folly::divRoundAway<int16_t, int16_t>, iters);
 }
BENCHMARK (divTruncInt32 , iters)
Definition at line 159 of file MathBenchmark.cpp.
{
   runDivTests<int32_t>(&folly::divTrunc<int32_t, int32_t>, iters);
 }
BENCHMARK (divFloorInt32 , iters)
Definition at line 162 of file MathBenchmark.cpp.
{
   runDivTests<int32_t>(&folly::divFloor<int32_t, int32_t>, iters);
 }
BENCHMARK (divCeilInt32 , iters)
Definition at line 165 of file MathBenchmark.cpp.
{
   runDivTests<int32_t>(&folly::divCeil<int32_t, int32_t>, iters);
 }
BENCHMARK (divRoundAwayInt32 , iters)
Definition at line 186 of file MathBenchmark.cpp.
References BENCHMARK_DRAW_LINE().
{
   runDivTests<int32_t>(&folly::divRoundAway<int32_t, int32_t>, iters);
 }
BENCHMARK (divTruncInt64 , iters)
Definition at line 191 of file MathBenchmark.cpp.
{
   runDivTests<int64_t>(&folly::divTrunc<int64_t, int64_t>, iters);
 }
BENCHMARK (divFloorInt64 , iters)
Definition at line 194 of file MathBenchmark.cpp.
{
   runDivTests<int64_t>(&folly::divFloor<int64_t, int64_t>, iters);
 }
BENCHMARK (divCeilInt64 , iters)
Definition at line 197 of file MathBenchmark.cpp.
{
   runDivTests<int64_t>(&folly::divCeil<int64_t, int64_t>, iters);
 }
BENCHMARK (divRoundAwayInt64 , iters)
Definition at line 218 of file MathBenchmark.cpp.
References BENCHMARK_DRAW_LINE().
{
   runDivTests<int64_t>(&folly::divRoundAway<int64_t, int64_t>, iters);
 }
BENCHMARK (divTruncUint8 , iters)
Definition at line 223 of file MathBenchmark.cpp.
{
   runDivTests<uint8_t>(&folly::divTrunc<uint8_t, uint8_t>, iters);
 }
BENCHMARK (divFloorUint8 , iters)
Definition at line 226 of file MathBenchmark.cpp.
{
   runDivTests<uint8_t>(&folly::divFloor<uint8_t, uint8_t>, iters);
 }
BENCHMARK (divCeilUint8 , iters)
Definition at line 229 of file MathBenchmark.cpp.
{
   runDivTests<uint8_t>(&folly::divCeil<uint8_t, uint8_t>, iters);
 }
BENCHMARK (divRoundAwayUint8 , iters)
Definition at line 250 of file MathBenchmark.cpp.
References BENCHMARK_DRAW_LINE().
{
   runDivTests<uint8_t>(&folly::divRoundAway<uint8_t, uint8_t>, iters);
 }
BENCHMARK (divTruncUint16 , iters)
Definition at line 255 of file MathBenchmark.cpp.
{
   runDivTests<uint16_t>(&folly::divTrunc<uint16_t, uint16_t>, iters);
 }
BENCHMARK (divFloorUint16 , iters)
Definition at line 258 of file MathBenchmark.cpp.
{
   runDivTests<uint16_t>(&folly::divFloor<uint16_t, uint16_t>, iters);
 }
BENCHMARK (divCeilUint16 , iters)
Definition at line 261 of file MathBenchmark.cpp.
{
   runDivTests<uint16_t>(&folly::divCeil<uint16_t, uint16_t>, iters);
 }
BENCHMARK (divRoundAwayUint16 , iters)
Definition at line 282 of file MathBenchmark.cpp.
References BENCHMARK_DRAW_LINE().
{
   runDivTests<uint16_t>(&folly::divRoundAway<uint16_t, uint16_t>, iters);
 }
BENCHMARK (divTruncUint32 , iters)
Definition at line 287 of file MathBenchmark.cpp.
{
   runDivTests<uint32_t>(&folly::divTrunc<uint32_t, uint32_t>, iters);
 }
BENCHMARK (divFloorUint32 , iters)
Definition at line 290 of file MathBenchmark.cpp.
{
   runDivTests<uint32_t>(&folly::divFloor<uint32_t, uint32_t>, iters);
 }
BENCHMARK (divCeilUint32 , iters)
Definition at line 293 of file MathBenchmark.cpp.
{
   runDivTests<uint32_t>(&folly::divCeil<uint32_t, uint32_t>, iters);
 }
BENCHMARK (divRoundAwayUint32 , iters)
Definition at line 314 of file MathBenchmark.cpp.
References BENCHMARK_DRAW_LINE().
{
   runDivTests<uint32_t>(&folly::divRoundAway<uint32_t, uint32_t>, iters);
 }
BENCHMARK (divTruncUint64 , iters)
Definition at line 319 of file MathBenchmark.cpp.
{
   runDivTests<uint64_t>(&folly::divTrunc<uint64_t, uint64_t>, iters);
 }
BENCHMARK (divFloorUint64 , iters)
Definition at line 322 of file MathBenchmark.cpp.
{
   runDivTests<uint64_t>(&folly::divFloor<uint64_t, uint64_t>, iters);
 }
BENCHMARK (divCeilUint64 , iters)
Definition at line 325 of file MathBenchmark.cpp.
{
   runDivTests<uint64_t>(&folly::divCeil<uint64_t, uint64_t>, iters);
 }
BENCHMARK (divRoundAwayUint64 , iters)
Definition at line 346 of file MathBenchmark.cpp.
{
   runDivTests<uint64_t>(&folly::divRoundAway<uint64_t, uint64_t>, iters);
 }
BENCHMARK_DRAW_LINE ()
Referenced by BENCHMARK().
BENCHMARK_RELATIVE (branchlessDivCeilInt8 , iters)
Definition at line 104 of file MathBenchmark.cpp.
{
   runDivTests<int8_t>(&folly::detail::divCeilBranchless<int8_t>, iters);
 }
BENCHMARK_RELATIVE (branchfulDivCeilInt8 , iters)
Definition at line 107 of file MathBenchmark.cpp.
{
   runDivTests<int8_t>(&folly::detail::divCeilBranchful<int8_t>, iters);
 }
BENCHMARK_RELATIVE (brokenButWidespreadDivCeilInt8 , iters)
Definition at line 110 of file MathBenchmark.cpp.
{
   runDivTests<int8_t>(&brokenButWidespreadDivCeil<int8_t>, iters);
 }
BENCHMARK_RELATIVE (viaFloatDivCeilInt8 , iters)
Definition at line 113 of file MathBenchmark.cpp.
{
   runDivTests<int8_t>(&viaFloatDivCeil<int8_t>, iters);
 }
BENCHMARK_RELATIVE (viaDoubleDivCeilInt8 , iters)
Definition at line 116 of file MathBenchmark.cpp.
{
   runDivTests<int8_t>(&viaDoubleDivCeil<int8_t>, iters);
 }
BENCHMARK_RELATIVE (viaLongDoubleDivCeilInt8 , iters)
Definition at line 119 of file MathBenchmark.cpp.
{
   runDivTests<int8_t>(&viaLongDoubleDivCeil<int8_t>, iters);
 }
BENCHMARK_RELATIVE (branchlessDivCeilInt16 , iters)
Definition at line 136 of file MathBenchmark.cpp.
{
   runDivTests<int16_t>(&folly::detail::divCeilBranchless<int16_t>, iters);
 }
BENCHMARK_RELATIVE (branchfulDivCeilInt16 , iters)
Definition at line 139 of file MathBenchmark.cpp.
{
   runDivTests<int16_t>(&folly::detail::divCeilBranchful<int16_t>, iters);
 }
BENCHMARK_RELATIVE (brokenButWidespreadDivCeilInt16 , iters)
Definition at line 142 of file MathBenchmark.cpp.
{
   runDivTests<int16_t>(&brokenButWidespreadDivCeil<int16_t>, iters);
 }
BENCHMARK_RELATIVE (viaFloatDivCeilInt16 , iters)
Definition at line 145 of file MathBenchmark.cpp.
{
   runDivTests<int16_t>(&viaFloatDivCeil<int16_t>, iters);
 }
BENCHMARK_RELATIVE (viaDoubleDivCeilInt16 , iters)
Definition at line 148 of file MathBenchmark.cpp.
{
   runDivTests<int16_t>(&viaDoubleDivCeil<int16_t>, iters);
 }
BENCHMARK_RELATIVE (viaLongDoubleDivCeilInt16 , iters)
Definition at line 151 of file MathBenchmark.cpp.
{
   runDivTests<int16_t>(&viaLongDoubleDivCeil<int16_t>, iters);
 }
BENCHMARK_RELATIVE (branchlessDivCeilInt32 , iters)
Definition at line 168 of file MathBenchmark.cpp.
{
   runDivTests<int32_t>(&folly::detail::divCeilBranchless<int32_t>, iters);
 }
BENCHMARK_RELATIVE (branchfulDivCeilInt32 , iters)
Definition at line 171 of file MathBenchmark.cpp.
{
   runDivTests<int32_t>(&folly::detail::divCeilBranchful<int32_t>, iters);
 }
BENCHMARK_RELATIVE (brokenButWidespreadDivCeilInt32 , iters)
Definition at line 174 of file MathBenchmark.cpp.
{
   runDivTests<int32_t>(&brokenButWidespreadDivCeil<int32_t>, iters);
 }
BENCHMARK_RELATIVE (approxViaFloatDivCeilInt32 , iters)
Definition at line 177 of file MathBenchmark.cpp.
{
   runDivTests<int32_t>(&viaFloatDivCeil<int32_t>, iters);
 }
BENCHMARK_RELATIVE (viaDoubleDivCeilInt32 , iters)
Definition at line 180 of file MathBenchmark.cpp.
{
   runDivTests<int32_t>(&viaDoubleDivCeil<int32_t>, iters);
 }
BENCHMARK_RELATIVE (viaLongDoubleDivCeilInt32 , iters)
Definition at line 183 of file MathBenchmark.cpp.
{
   runDivTests<int32_t>(&viaLongDoubleDivCeil<int32_t>, iters);
 }
BENCHMARK_RELATIVE (branchlessDivCeilInt64 , iters)
Definition at line 200 of file MathBenchmark.cpp.
{
   runDivTests<int64_t>(&folly::detail::divCeilBranchless<int64_t>, iters);
 }
BENCHMARK_RELATIVE (branchfulDivCeilInt64 , iters)
Definition at line 203 of file MathBenchmark.cpp.
{
   runDivTests<int64_t>(&folly::detail::divCeilBranchful<int64_t>, iters);
 }
BENCHMARK_RELATIVE (brokenButWidespreadDivCeilInt64 , iters)
Definition at line 206 of file MathBenchmark.cpp.
{
   runDivTests<int64_t>(&brokenButWidespreadDivCeil<int64_t>, iters);
 }
BENCHMARK_RELATIVE (approxViaFloatDivCeilInt64 , iters)
Definition at line 209 of file MathBenchmark.cpp.
{
   runDivTests<int64_t>(&viaFloatDivCeil<int64_t>, iters);
 }
BENCHMARK_RELATIVE (approxViaDoubleDivCeilInt64 , iters)
Definition at line 212 of file MathBenchmark.cpp.
{
   runDivTests<int64_t>(&viaDoubleDivCeil<int64_t>, iters);
 }
BENCHMARK_RELATIVE (viaLongDoubleDivCeilInt64 , iters)
Definition at line 215 of file MathBenchmark.cpp.
{
   runDivTests<int64_t>(&viaLongDoubleDivCeil<int64_t>, iters);
 }
BENCHMARK_RELATIVE (branchlessDivCeilUint8 , iters)
Definition at line 232 of file MathBenchmark.cpp.
{
   runDivTests<uint8_t>(&folly::detail::divCeilBranchless<uint8_t>, iters);
 }
BENCHMARK_RELATIVE (branchfulDivCeilUint8 , iters)
Definition at line 235 of file MathBenchmark.cpp.
{
   runDivTests<uint8_t>(&folly::detail::divCeilBranchful<uint8_t>, iters);
 }
BENCHMARK_RELATIVE (brokenButWidespreadDivCeilUint8 , iters)
Definition at line 238 of file MathBenchmark.cpp.
{
   runDivTests<uint8_t>(&brokenButWidespreadDivCeil<uint8_t>, iters);
 }
BENCHMARK_RELATIVE (viaFloatDivCeilUint8 , iters)
Definition at line 241 of file MathBenchmark.cpp.
{
   runDivTests<uint8_t>(&viaFloatDivCeil<uint8_t>, iters);
 }
BENCHMARK_RELATIVE (viaDoubleDivCeilUint8 , iters)
Definition at line 244 of file MathBenchmark.cpp.
{
   runDivTests<uint8_t>(&viaDoubleDivCeil<uint8_t>, iters);
 }
BENCHMARK_RELATIVE (viaLongDoubleDivCeilUint8 , iters)
Definition at line 247 of file MathBenchmark.cpp.
{
   runDivTests<uint8_t>(&viaLongDoubleDivCeil<uint8_t>, iters);
 }
BENCHMARK_RELATIVE (branchlessDivCeilUint16 , iters)
Definition at line 264 of file MathBenchmark.cpp.
{
   runDivTests<uint16_t>(&folly::detail::divCeilBranchless<uint16_t>, iters);
 }
BENCHMARK_RELATIVE (branchfulDivCeilUint16 , iters)
Definition at line 267 of file MathBenchmark.cpp.
{
   runDivTests<uint16_t>(&folly::detail::divCeilBranchful<uint16_t>, iters);
 }
BENCHMARK_RELATIVE (brokenButWidespreadDivCeilUint16 , iters)
Definition at line 270 of file MathBenchmark.cpp.
{
   runDivTests<uint16_t>(&brokenButWidespreadDivCeil<uint16_t>, iters);
 }
BENCHMARK_RELATIVE (viaFloatDivCeilUint16 , iters)
Definition at line 273 of file MathBenchmark.cpp.
{
   runDivTests<uint16_t>(&viaFloatDivCeil<uint16_t>, iters);
 }
BENCHMARK_RELATIVE (viaDoubleDivCeilUint16 , iters)
Definition at line 276 of file MathBenchmark.cpp.
{
   runDivTests<uint16_t>(&viaDoubleDivCeil<uint16_t>, iters);
 }
BENCHMARK_RELATIVE (viaLongDoubleDivCeilUint16 , iters)
Definition at line 279 of file MathBenchmark.cpp.
{
   runDivTests<uint16_t>(&viaLongDoubleDivCeil<uint16_t>, iters);
 }
BENCHMARK_RELATIVE (branchlessDivCeilUint32 , iters)
Definition at line 296 of file MathBenchmark.cpp.
{
   runDivTests<uint32_t>(&folly::detail::divCeilBranchless<uint32_t>, iters);
 }
BENCHMARK_RELATIVE (branchfulDivCeilUint32 , iters)
Definition at line 299 of file MathBenchmark.cpp.
{
   runDivTests<uint32_t>(&folly::detail::divCeilBranchful<uint32_t>, iters);
 }
BENCHMARK_RELATIVE (brokenButWidespreadDivCeilUint32 , iters)
Definition at line 302 of file MathBenchmark.cpp.
{
   runDivTests<uint32_t>(&brokenButWidespreadDivCeil<uint32_t>, iters);
 }
BENCHMARK_RELATIVE (approxViaFloatDivCeilUint32 , iters)
Definition at line 305 of file MathBenchmark.cpp.
{
   runDivTests<uint32_t>(&viaFloatDivCeil<uint32_t>, iters);
 }
BENCHMARK_RELATIVE (viaDoubleDivCeilUint32 , iters)
Definition at line 308 of file MathBenchmark.cpp.
{
   runDivTests<uint32_t>(&viaDoubleDivCeil<uint32_t>, iters);
 }
BENCHMARK_RELATIVE (viaLongDoubleDivCeilUint32 , iters)
Definition at line 311 of file MathBenchmark.cpp.
{
   runDivTests<uint32_t>(&viaLongDoubleDivCeil<uint32_t>, iters);
 }
BENCHMARK_RELATIVE (branchlessDivCeilUint64 , iters)
Definition at line 328 of file MathBenchmark.cpp.
{
   runDivTests<uint64_t>(&folly::detail::divCeilBranchless<uint64_t>, iters);
 }
BENCHMARK_RELATIVE (branchfulDivCeilUint64 , iters)
Definition at line 331 of file MathBenchmark.cpp.
{
   runDivTests<uint64_t>(&folly::detail::divCeilBranchful<uint64_t>, iters);
 }
BENCHMARK_RELATIVE (brokenButWidespreadDivCeilUint64 , iters)
Definition at line 334 of file MathBenchmark.cpp.
{
   runDivTests<uint64_t>(&brokenButWidespreadDivCeil<uint64_t>, iters);
 }
BENCHMARK_RELATIVE (approxViaFloatDivCeilUint64 , iters)
Definition at line 337 of file MathBenchmark.cpp.
{
   runDivTests<uint64_t>(&viaFloatDivCeil<uint64_t>, iters);
 }
BENCHMARK_RELATIVE (approxViaDoubleDivCeilUint64 , iters)
Definition at line 340 of file MathBenchmark.cpp.
{
   runDivTests<uint64_t>(&viaDoubleDivCeil<uint64_t>, iters);
 }
BENCHMARK_RELATIVE (viaLongDoubleDivCeilUint64 , iters)
Definition at line 343 of file MathBenchmark.cpp.
{
   runDivTests<uint64_t>(&viaLongDoubleDivCeil<uint64_t>, iters);
 }
int main (int argc, char ** argv)
Definition at line 350 of file MathBenchmark.cpp.
References folly::runBenchmarks().
{
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   folly::runBenchmarks();
   return 0;
 }