proxygen: proxygen/folly/folly/test/MemcpyTest.cpp File Reference
MemcpyTest.cpp File Reference
#include <folly/Portability.h>
#include <folly/portability/GTest.h>
Functions
FOLLY_DISABLE_UNDEFINED_BEHAVIOR_SANITIZER ("nonnull-attribute")
void testLen (size_t len)
TEST (memcpy, small)
TEST (memcpy, main)
Function Documentation
FOLLY_DISABLE_UNDEFINED_BEHAVIOR_SANITIZER ("nonnull-attribute")
Definition at line 36 of file MemcpyTest.cpp.
{
   // If length is 0, we shouldn't touch any memory.  So this should
   // not crash.
   char* srcNull = nullptr;
   char* dstNull = nullptr;
   memcpy(dstNull, srcNull, 0);
 }
TEST (memcpy , small)
Definition at line 61 of file MemcpyTest.cpp.
References testLen().
                     {
   for (size_t len = 1; len < 8; ++len) {
     testLen(len);
   }
 }
TEST (memcpy , main)
Definition at line 67 of file MemcpyTest.cpp.
References testLen().
                    {
   for (size_t len = 8; len < 128; ++len) {
     testLen(len);
   }
   for (size_t len = 128; len < kSize; len += 128) {
     testLen(len);
   }
   for (size_t len = 128; len < kSize; len += 73) {
     testLen(len);
   }
 }
void testLen (size_t len)
Definition at line 45 of file MemcpyTest.cpp.
References EXPECT_EQ, i, and bm::init().
Referenced by TEST().
{
   if (len > kSize) {
     return;
   }
   init();
   memcpy(dst, src, len);
   for (size_t i = 0; i < len; ++i) {
     EXPECT_EQ(src[i], static_cast<char>(i));
     EXPECT_EQ(src[i], dst[i]);
   }
   if (len < kSize) {
     EXPECT_EQ(src[len], static_cast<char>(len));
     EXPECT_EQ(dst[len], static_cast<char>(255 - len));
   }
 }