proxygen: proxygen/folly/folly/test/MemoryIdlerTest.cpp File Reference
MemoryIdlerTest.cpp File Reference
#include <folly/detail/MemoryIdler.h>
#include <folly/portability/GMock.h>
#include <folly/portability/GTest.h>
#include <folly/synchronization/Baton.h>
#include <memory>
#include <thread>
Classes
struct MockClock
struct MockAtom< T >
Functions
TEST (MemoryIdler, releaseStack)
TEST (MemoryIdler, releaseStackMinExtra)
TEST (MemoryIdler, releaseStackLargeExtra)
TEST (MemoryIdler, releaseMallocTLS)
FutexResult futexWait (const Futex< MockAtom > *futex, uint32_t expected, uint32_t waitMask)
template<typename Clock , typename Duration >
FutexResult futexWaitUntil (const Futex< MockAtom > *futex, std::uint32_t expected, std::chrono::time_point< Clock, Duration > const &deadline, uint32_t waitMask)
TEST (MemoryIdler, futexWaitValueChangedEarly)
TEST (MemoryIdler, futexWaitValueChangedLate)
TEST (MemoryIdler, futexWaitAwokenEarly)
TEST (MemoryIdler, futexWaitAwokenLate)
TEST (MemoryIdler, futexWaitImmediateFlush)
TEST (MemoryIdler, futexWaitNeverFlush)
Variables
static auto const forever = MockClock::time_point::max()
Function Documentation
FutexResult futexWait (const Futex< MockAtom > * futex, uint32_t expected, uint32_t waitMask)
Definition at line 97 of file MemoryIdlerTest.cpp.
{
   return futex->futexWait(expected, waitMask);
 }
template<typename Clock , typename Duration > FutexResult futexWaitUntil (const Futex< MockAtom > * futex, std::uint32_t expected, std::chrono::time_point< Clock, Duration > const & deadline, uint32_t waitMask)
Definition at line 101 of file MemoryIdlerTest.cpp.
Referenced by folly::fibers::Baton::timedWaitThread().
{
   return futex->futexWaitUntil(expected, deadline, waitMask);
 }
TEST (MemoryIdler , releaseStack)
Definition at line 30 of file MemoryIdlerTest.cpp.
References folly::detail::MemoryIdler::unmapUnusedStack().
{
   MemoryIdler::unmapUnusedStack();
 }
TEST (MemoryIdler , releaseStackMinExtra)
Definition at line 34 of file MemoryIdlerTest.cpp.
References folly::detail::MemoryIdler::unmapUnusedStack().
{
   MemoryIdler::unmapUnusedStack(0);
 }
TEST (MemoryIdler , releaseStackLargeExtra)
Definition at line 38 of file MemoryIdlerTest.cpp.
References folly::detail::MemoryIdler::unmapUnusedStack().
{
   MemoryIdler::unmapUnusedStack(30000000);
 }
TEST (MemoryIdler , releaseMallocTLS)
Definition at line 42 of file MemoryIdlerTest.cpp.
References folly::detail::MemoryIdler::flushLocalMallocCaches().
{
   auto p = new int[4];
   MemoryIdler::flushLocalMallocCaches();
   delete[] p;
   MemoryIdler::flushLocalMallocCaches();
   p = new int[4];
   MemoryIdler::flushLocalMallocCaches();
   delete[] p;
 }
TEST (MemoryIdler , futexWaitValueChangedEarly)
Definition at line 109 of file MemoryIdlerTest.cpp.
References folly::test::begin(), folly::detail::MemoryIdler::defaultIdleTimeout, EXPECT_CALL, EXPECT_EQ, forever, folly::detail::futexWaitUntil(), folly::detail::MemoryIdler::futexWaitUntil(), testing::Ge(), folly::AtomicStruct< T, Atom >::load(), testing::Lt(), testing::Return(), MockClock::setup(), and folly::detail::VALUE_CHANGED.
{
   Futex<MockAtom> fut;
   auto clock = MockClock::setup();
   auto begin = MockClock::time_point(std::chrono::seconds(100));
   auto idleTimeout = MemoryIdler::defaultIdleTimeout.load();
   EXPECT_CALL(*clock, nowImpl()).WillOnce(Return(begin));
   EXPECT_CALL(
       fut,
       futexWaitUntil(
           1, AllOf(Ge(begin + idleTimeout), Lt(begin + 2 * idleTimeout)), -1))
       .WillOnce(Return(FutexResult::VALUE_CHANGED));
   EXPECT_EQ(
       FutexResult::VALUE_CHANGED, MemoryIdler::futexWaitUntil(fut, 1, forever));
 }
TEST (MemoryIdler , futexWaitValueChangedLate)
Definition at line 125 of file MemoryIdlerTest.cpp.
References folly::test::begin(), folly::detail::MemoryIdler::defaultIdleTimeout, EXPECT_CALL, EXPECT_EQ, forever, folly::detail::futexWaitUntil(), folly::detail::MemoryIdler::futexWaitUntil(), testing::Ge(), folly::AtomicStruct< T, Atom >::load(), testing::Lt(), testing::Return(), MockClock::setup(), folly::detail::TIMEDOUT, and folly::detail::VALUE_CHANGED.
{
   Futex<MockAtom> fut;
   auto clock = MockClock::setup();
   auto begin = MockClock::time_point(std::chrono::seconds(100));
   auto idleTimeout = MemoryIdler::defaultIdleTimeout.load();
   EXPECT_CALL(*clock, nowImpl()).WillOnce(Return(begin));
   EXPECT_CALL(
       fut,
       futexWaitUntil(
           1, AllOf(Ge(begin + idleTimeout), Lt(begin + 2 * idleTimeout)), -1))
       .WillOnce(Return(FutexResult::TIMEDOUT));
   EXPECT_CALL(fut, futexWaitUntil(1, forever, -1))
       .WillOnce(Return(FutexResult::VALUE_CHANGED));
   EXPECT_EQ(
       FutexResult::VALUE_CHANGED, MemoryIdler::futexWaitUntil(fut, 1, forever));
 }
TEST (MemoryIdler , futexWaitAwokenEarly)
Definition at line 143 of file MemoryIdlerTest.cpp.
References folly::detail::AWOKEN, folly::test::begin(), folly::detail::MemoryIdler::defaultIdleTimeout, EXPECT_CALL, EXPECT_EQ, forever, folly::detail::futexWaitUntil(), folly::detail::MemoryIdler::futexWaitUntil(), testing::Ge(), folly::AtomicStruct< T, Atom >::load(), testing::Return(), and MockClock::setup().
{
   Futex<MockAtom> fut;
   auto clock = MockClock::setup();
   auto begin = MockClock::time_point(std::chrono::seconds(100));
   auto idleTimeout = MemoryIdler::defaultIdleTimeout.load();
   EXPECT_CALL(*clock, nowImpl()).WillOnce(Return(begin));
   EXPECT_CALL(fut, futexWaitUntil(1, Ge(begin + idleTimeout), -1))
       .WillOnce(Return(FutexResult::AWOKEN));
   EXPECT_EQ(FutexResult::AWOKEN, MemoryIdler::futexWaitUntil(fut, 1, forever));
 }
TEST (MemoryIdler , futexWaitAwokenLate)
Definition at line 155 of file MemoryIdlerTest.cpp.
References folly::detail::AWOKEN, folly::test::begin(), folly::detail::MemoryIdler::defaultIdleTimeout, EXPECT_CALL, EXPECT_EQ, f, forever, folly::detail::futexWaitUntil(), folly::detail::MemoryIdler::futexWaitUntil(), folly::AtomicStruct< T, Atom >::load(), testing::Return(), MockClock::setup(), and folly::detail::TIMEDOUT.
{
   Futex<MockAtom> fut;
   auto clock = MockClock::setup();
   auto begin = MockClock::time_point(std::chrono::seconds(100));
   auto idleTimeout = MemoryIdler::defaultIdleTimeout.load();
   EXPECT_CALL(*clock, nowImpl()).WillOnce(Return(begin));
   EXPECT_CALL(fut, futexWaitUntil(1, begin + idleTimeout, -1))
       .WillOnce(Return(FutexResult::TIMEDOUT));
   EXPECT_CALL(fut, futexWaitUntil(1, forever, -1))
       .WillOnce(Return(FutexResult::AWOKEN));
   EXPECT_EQ(
       FutexResult::AWOKEN,
       MemoryIdler::futexWaitUntil(fut, 1, forever, -1, idleTimeout, 100, 0.0f));
 }
TEST (MemoryIdler , futexWaitImmediateFlush)
Definition at line 171 of file MemoryIdlerTest.cpp.
References folly::detail::AWOKEN, EXPECT_CALL, EXPECT_EQ, forever, folly::detail::futexWaitUntil(), folly::detail::MemoryIdler::futexWaitUntil(), testing::Return(), and MockClock::setup().
{
   Futex<MockAtom> fut;
   auto clock = MockClock::setup();
   EXPECT_CALL(fut, futexWaitUntil(2, forever, 0xff))
       .WillOnce(Return(FutexResult::AWOKEN));
   EXPECT_EQ(
       FutexResult::AWOKEN,
       MemoryIdler::futexWaitUntil(
           fut, 2, forever, 0xff, std::chrono::seconds(0)));
 }
TEST (MemoryIdler , futexWaitNeverFlush)
Definition at line 183 of file MemoryIdlerTest.cpp.
References folly::detail::AWOKEN, EXPECT_CALL, EXPECT_EQ, forever, folly::detail::futexWaitUntil(), folly::detail::MemoryIdler::futexWaitUntil(), testing::Return(), and MockClock::setup().
{
   Futex<MockAtom> fut;
   auto clock = MockClock::setup();
   EXPECT_CALL(fut, futexWaitUntil(1, forever, -1))
       .WillOnce(Return(FutexResult::AWOKEN));
   EXPECT_EQ(
       FutexResult::AWOKEN,
       MemoryIdler::futexWaitUntil(
           fut, 1, forever, -1, std::chrono::seconds(-7)));
 }
Variable Documentation
auto const forever = MockClock::time_point::max() static
Definition at line 77 of file MemoryIdlerTest.cpp.
Referenced by folly::gen::detail::Cycle< forever >::Generator< Value, Source >::apply(), folly::gen::detail::Cycle< forever >::Cycle(), testing::internal::UnitTestImpl::RunAllTests(), testing::internal::TearDownEnvironment(), and TEST().