proxygen: proxygen/folly/folly/test/MemoryIdlerBenchmark.cpp File Reference
MemoryIdlerBenchmark.cpp File Reference
#include <folly/detail/MemoryIdler.h>
#include <folly/Benchmark.h>
Functions
BENCHMARK (releaseStack, iters)
BENCHMARK (releaseMallocTLS, iters)
int main (int argc, char **argv)
Function Documentation
BENCHMARK (releaseStack , iters)
Definition at line 23 of file MemoryIdlerBenchmark.cpp.
References i, and folly::detail::MemoryIdler::unmapUnusedStack().
{
   for (size_t i = 0; i < iters; ++i) {
     MemoryIdler::unmapUnusedStack();
   }
 }
BENCHMARK (releaseMallocTLS , iters)
Definition at line 29 of file MemoryIdlerBenchmark.cpp.
References folly::detail::MemoryIdler::flushLocalMallocCaches(), and i.
{
   for (size_t i = 0; i < iters; ++i) {
     MemoryIdler::flushLocalMallocCaches();
   }
 }
int main (int argc, char ** argv)
Definition at line 35 of file MemoryIdlerBenchmark.cpp.
References folly::runBenchmarks().
{
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   folly::runBenchmarks();
   return 0;
 }