proxygen: proxygen/folly/folly/container/test/MergeTest.cpp File Reference
MergeTest.cpp File Reference
#include <folly/container/Merge.h>
#include <map>
#include <vector>
#include <folly/portability/GTest.h>
Functions
TEST (MergeTest, NonOverlapping)
TEST (MergeTest, OverlappingInSingleInputRange)
TEST (MergeTest, OverlappingInDifferentInputRange)
Function Documentation
TEST (MergeTest , NonOverlapping)
Definition at line 24 of file MergeTest.cpp.
References a, b, c, EXPECT_EQ, i, and folly::merge().
{
   std::vector<int> a = {0, 2, 4, 6};
   std::vector<int> b = {1, 3, 5, 7};
   std::vector<int> c;
   folly::merge(a.begin(), a.end(), b.begin(), b.end(), std::back_inserter(c));
   EXPECT_EQ(8, c.size());
   for (size_t i = 0; i < 8; ++i) {
     EXPECT_EQ(i, c[i]);
   }
 }
TEST (MergeTest , OverlappingInSingleInputRange)
Definition at line 36 of file MergeTest.cpp.
References a, b, c, EXPECT_EQ, and folly::merge().
{
   std::vector<std::pair<int, int>> a = {{0, 0}, {0, 1}};
   std::vector<std::pair<int, int>> b = {{2, 2}, {3, 3}};
   std::map<int, int> c;
   folly::merge(
       a.begin(), a.end(), b.begin(), b.end(), std::inserter(c, c.begin()));
   EXPECT_EQ(3, c.size());
   // First value is inserted, second is not
   EXPECT_EQ(c[0], 0);
   EXPECT_EQ(c[2], 2);
   EXPECT_EQ(c[3], 3);
 }
TEST (MergeTest , OverlappingInDifferentInputRange)
Definition at line 52 of file MergeTest.cpp.
References a, b, c, EXPECT_EQ, and folly::merge().
{
   std::vector<std::pair<int, int>> a = {{0, 0}, {1, 1}};
   std::vector<std::pair<int, int>> b = {{0, 2}, {3, 3}};
   std::map<int, int> c;
   folly::merge(
       a.begin(), a.end(), b.begin(), b.end(), std::inserter(c, c.begin()));
   EXPECT_EQ(3, c.size());
   // Value from a is inserted, value from b is not.
   EXPECT_EQ(c[0], 0);
   EXPECT_EQ(c[1], 1);
   EXPECT_EQ(c[3], 3);
 }