proxygen: gtest_uninitialized_test Namespace Reference
gtest_uninitialized_test Namespace Reference
Classes
class GTestUninitializedTest
Functions
def Assert (condition)
def AssertEq (expected, actual)
def TestExitCodeAndOutput (command)
Variables
string __author__ = 'wan@google.com (Zhanyong Wan)'
COMMAND = gtest_test_utils.GetTestExecutablePath('gtest_uninitialized_test_')
Function Documentation
def gtest_uninitialized_test.Assert (condition)
Definition at line 42 of file gtest_uninitialized_test.py.
Referenced by TestExitCodeAndOutput().
 def Assert(condition):
   if not condition:
     raise AssertionError
def gtest_uninitialized_test.AssertEq (expected, actual)
Definition at line 47 of file gtest_uninitialized_test.py.
Referenced by TestExitCodeAndOutput().
 def AssertEq(expected, actual):
   if expected != actual:
     print('Expected: %s' % (expected,))
     print('  Actual: %s' % (actual,))
     raise AssertionError
def gtest_uninitialized_test.TestExitCodeAndOutput (command)
Runs the given command and verifies its exit code and output.
Definition at line 54 of file gtest_uninitialized_test.py.
References Assert(), and AssertEq().
Referenced by gtest_uninitialized_test.GTestUninitializedTest.testExitCodeAndOutput().
 def TestExitCodeAndOutput(command):
   """Runs the given command and verifies its exit code and output."""
   # Verifies that 'command' exits with code 1.
   p = gtest_test_utils.Subprocess(command)
   Assert(p.exited)
   AssertEq(1, p.exit_code)
   Assert('InitGoogleTest' in p.output)
Variable Documentation
string gtest_uninitialized_test.__author__ = 'wan@google.com (Zhanyong Wan)' private
Definition at line 34 of file gtest_uninitialized_test.py.
gtest_uninitialized_test.COMMAND = gtest_test_utils.GetTestExecutablePath('gtest_uninitialized_test_')
Definition at line 39 of file gtest_uninitialized_test.py.