proxygen: __cxxabiv1 Namespace Reference
__cxxabiv1 Namespace Reference
Classes
struct __cxa_eh_globals
struct __cxa_exception
Functions
__cxa_eh_globals * __cxa_get_globals (void) noexcept
__cxa_eh_globals * __cxa_get_globals_fast (void) noexcept
void __cxa_throw (void *thrownException, std::type_info *type, void(*destructor)(void *)) __attribute__((__noreturn__))
void * __cxa_begin_catch (void *excObj) throw ()
void __cxa_rethrow (void) __attribute__((__noreturn__))
void __cxa_end_catch (void)
Function Documentation
void * __cxxabiv1::__cxa_begin_catch (void * excObj) throw ()
Definition at line 124 of file ExceptionTracerLib.cpp.
References folly::exception_tracer::getCxaBeginCatchCallbacks().
{
   // excObj is a pointer to the unwindHeader in __cxa_exception
   static auto orig_cxa_begin_catch =
       reinterpret_cast<decltype(&__cxa_begin_catch)>(
           dlsym(RTLD_NEXT, "__cxa_begin_catch"));
   getCxaBeginCatchCallbacks().invoke(excObj);
   return orig_cxa_begin_catch(excObj);
 }
void __cxxabiv1::__cxa_end_catch (void)
Definition at line 133 of file ExceptionTracerLib.cpp.
References folly::exception_tracer::getCxaEndCatchCallbacks().
{
   static auto orig_cxa_end_catch = reinterpret_cast<decltype(&__cxa_end_catch)>(
       dlsym(RTLD_NEXT, "__cxa_end_catch"));
   getCxaEndCatchCallbacks().invoke();
   orig_cxa_end_catch();
 }
__cxa_eh_globals* __cxxabiv1::__cxa_get_globals (void) noexcept
Referenced by folly::exception_tracer::getCurrentExceptions(), and folly::uncaught_exceptions().
__cxa_eh_globals* __cxxabiv1::__cxa_get_globals_fast (void) noexcept
Referenced by getExceptionStackTraceStack().
void __cxxabiv1::__cxa_rethrow (void)
Definition at line 111 of file ExceptionTracerLib.cpp.
References folly::exception_tracer::getCxaRethrowCallbacks().
                      {
   // __cxa_rethrow leaves the current exception on the caught stack,
   // and __cxa_begin_catch recognizes that case.  We could do the same, but
   // we'll implement something simpler (and slower): we pop the exception from
   // the caught stack, and push it back onto the active stack; this way, our
   // implementation of __cxa_begin_catch doesn't have to do anything special.
   static auto orig_cxa_rethrow = reinterpret_cast<decltype(&__cxa_rethrow)>(
       dlsym(RTLD_NEXT, "__cxa_rethrow"));
   getCxaRethrowCallbacks().invoke();
   orig_cxa_rethrow();
   __builtin_unreachable(); // orig_cxa_rethrow never returns
 }
void __cxxabiv1::__cxa_throw (void * thrownException, std::type_info * type, void(*)(void *) destructor)
Definition at line 100 of file ExceptionTracerLib.cpp.
References folly::exception_tracer::getCxaThrowCallbacks().
{
   static auto orig_cxa_throw =
       reinterpret_cast<decltype(&__cxa_throw)>(dlsym(RTLD_NEXT, "__cxa_throw"));
   getCxaThrowCallbacks().invoke(thrownException, type, destructor);
   orig_cxa_throw(thrownException, type, destructor);
   __builtin_unreachable(); // orig_cxa_throw never returns
 }