proxygen: p1055 Namespace Reference
p1055 Namespace Reference
Functions
template<class Executor , class Function , class Future >
auto then_execute (Executor &&e, Function &&f, Future &&pred)
template<class Executor , class Function >
auto twoway_execute (Executor &&e, Function &&f)
Function Documentation
template<class Executor , class Function , class Future > auto p1055::then_execute (Executor && e, Function && f, Future && pred)
Definition at line 106 of file then_execute_2.cpp.
References f, folly::pushmi::strands(), folly::pushmi::operators::transform, and folly::pushmi::operators::via.
Referenced by main().
{
   return pred | op::via(mi::strands(e)) |
       op::transform([f](auto v) { return f(v); });
 }
template<class Executor , class Function > auto p1055::twoway_execute (Executor && e, Function && f)
Definition at line 69 of file twoway_execute_2.cpp.
References f, and folly::pushmi::operators::transform.
Referenced by main().
{
   return e | op::transform([f](auto) { return f(); });
 }