proxygen: gtest_shuffle_test Namespace Reference
gtest_shuffle_test Namespace Reference
Classes
class GTestShuffleUnitTest
Functions
def AlsoRunDisabledTestsFlag ()
def FilterFlag (test_filter)
def RepeatFlag (n)
def ShuffleFlag ()
def RandomSeedFlag (n)
def RunAndReturnOutput (extra_env, args)
def GetTestsForAllIterations (extra_env, args)
def GetTestCases (tests)
def CalculateTestLists ()
Variables
string __author__ = 'wan@google.com (Zhanyong Wan)'
COMMAND = gtest_test_utils.GetTestExecutablePath('gtest_shuffle_test_')
string TOTAL_SHARDS_ENV_VAR = 'GTEST_TOTAL_SHARDS'
string SHARD_INDEX_ENV_VAR = 'GTEST_SHARD_INDEX'
string TEST_FILTER = 'A*.A:A*.B:C*'
list ALL_TESTS = []
list ACTIVE_TESTS = []
list FILTERED_TESTS = []
list SHARDED_TESTS = []
list SHUFFLED_ALL_TESTS = []
list SHUFFLED_ACTIVE_TESTS = []
list SHUFFLED_FILTERED_TESTS = []
list SHUFFLED_SHARDED_TESTS = []
Function Documentation
def gtest_shuffle_test.AlsoRunDisabledTestsFlag ()
Definition at line 58 of file gtest_shuffle_test.py.
Referenced by CalculateTestLists().
 def AlsoRunDisabledTestsFlag():
   return '--gtest_also_run_disabled_tests'
def gtest_shuffle_test.CalculateTestLists ()
Calculates the list of tests run under different flags.
Definition at line 130 of file gtest_shuffle_test.py.
References AlsoRunDisabledTestsFlag(), FilterFlag(), GetTestsForAllIterations(), RandomSeedFlag(), and ShuffleFlag().
Referenced by gtest_shuffle_test.GTestShuffleUnitTest.setUp().
 def CalculateTestLists():
   """Calculates the list of tests run under different flags."""
   if not ALL_TESTS:
     ALL_TESTS.extend(
         GetTestsForAllIterations({}, [AlsoRunDisabledTestsFlag()])[0])
   if not ACTIVE_TESTS:
     ACTIVE_TESTS.extend(GetTestsForAllIterations({}, [])[0])
   if not FILTERED_TESTS:
     FILTERED_TESTS.extend(
         GetTestsForAllIterations({}, [FilterFlag(TEST_FILTER)])[0])
   if not SHARDED_TESTS:
     SHARDED_TESTS.extend(
         GetTestsForAllIterations({TOTAL_SHARDS_ENV_VAR: '3',
                                   SHARD_INDEX_ENV_VAR: '1'},
                                  [])[0])
   if not SHUFFLED_ALL_TESTS:
     SHUFFLED_ALL_TESTS.extend(GetTestsForAllIterations(
         {}, [AlsoRunDisabledTestsFlag(), ShuffleFlag(), RandomSeedFlag(1)])[0])
   if not SHUFFLED_ACTIVE_TESTS:
     SHUFFLED_ACTIVE_TESTS.extend(GetTestsForAllIterations(
         {}, [ShuffleFlag(), RandomSeedFlag(1)])[0])
   if not SHUFFLED_FILTERED_TESTS:
     SHUFFLED_FILTERED_TESTS.extend(GetTestsForAllIterations(
         {}, [ShuffleFlag(), RandomSeedFlag(1), FilterFlag(TEST_FILTER)])[0])
   if not SHUFFLED_SHARDED_TESTS:
     SHUFFLED_SHARDED_TESTS.extend(
         GetTestsForAllIterations({TOTAL_SHARDS_ENV_VAR: '3',
                                   SHARD_INDEX_ENV_VAR: '1'},
                                  [ShuffleFlag(), RandomSeedFlag(1)])[0])
def gtest_shuffle_test.FilterFlag (test_filter)
Definition at line 62 of file gtest_shuffle_test.py.
Referenced by CalculateTestLists().
 def FilterFlag(test_filter):
   return '--gtest_filter=%s' % (test_filter,)
def gtest_shuffle_test.GetTestCases (tests)
Returns a list of test cases in the given full test names.
Args:
  tests: a list of full test names
Returns:
  A list of test cases from 'tests', in their original order.
  Consecutive duplicates are removed.
Definition at line 110 of file gtest_shuffle_test.py.
Referenced by gtest_shuffle_test.GTestShuffleUnitTest.testShuffleChangesTestCaseOrder().
 def GetTestCases(tests):
   """Returns a list of test cases in the given full test names.
   Args:
     tests: a list of full test names
   Returns:
     A list of test cases from 'tests', in their original order.
     Consecutive duplicates are removed.
   """
   test_cases = []
   for test in tests:
     test_case = test.split('.')[0]
     if not test_case in test_cases:
       test_cases.append(test_case)
   return test_cases
def gtest_shuffle_test.GetTestsForAllIterations (extra_env, args)
Runs the test program and returns a list of test lists.
Args:
  extra_env: a map from environment variables to their values
  args: command line flags to pass to gtest_shuffle_test_
Returns:
  A list where the i-th element is the list of tests run in the i-th
  test iteration.
Definition at line 87 of file gtest_shuffle_test.py.
References RunAndReturnOutput(), and folly::gen.split().
Referenced by CalculateTestLists(), gtest_shuffle_test.GTestShuffleUnitTest.testShuffleGeneratesNewOrderInEachIteration(), gtest_shuffle_test.GTestShuffleUnitTest.testShuffleRestoresOrderAfterEachIteration(), and gtest_shuffle_test.GTestShuffleUnitTest.testShuffleShardedTestsPreservesPartition().
 def GetTestsForAllIterations(extra_env, args):
   """Runs the test program and returns a list of test lists.
   Args:
     extra_env: a map from environment variables to their values
     args: command line flags to pass to gtest_shuffle_test_
   Returns:
     A list where the i-th element is the list of tests run in the i-th
     test iteration.
   """
   test_iterations = []
   for line in RunAndReturnOutput(extra_env, args).split('\n'):
     if line.startswith('----'):
       tests = []
       test_iterations.append(tests)
     elif line.strip():
       tests.append(line.strip())  # 'TestCaseName.TestName'
   return test_iterations
def gtest_shuffle_test.RandomSeedFlag (n)
Definition at line 74 of file gtest_shuffle_test.py.
Referenced by CalculateTestLists(), gtest_shuffle_test.GTestShuffleUnitTest.testShuffleGeneratesNewOrderInEachIteration(), gtest_shuffle_test.GTestShuffleUnitTest.testShuffleRestoresOrderAfterEachIteration(), and gtest_shuffle_test.GTestShuffleUnitTest.testShuffleShardedTestsPreservesPartition().
 def RandomSeedFlag(n):
   return '--gtest_random_seed=%s' % (n,)
def gtest_shuffle_test.RepeatFlag (n)
Definition at line 66 of file gtest_shuffle_test.py.
Referenced by gtest_shuffle_test.GTestShuffleUnitTest.testShuffleGeneratesNewOrderInEachIteration(), and gtest_shuffle_test.GTestShuffleUnitTest.testShuffleRestoresOrderAfterEachIteration().
 def RepeatFlag(n):
   return '--gtest_repeat=%s' % (n,)
def gtest_shuffle_test.RunAndReturnOutput (extra_env, args)
Runs the test program and returns its output.
Definition at line 78 of file gtest_shuffle_test.py.
Referenced by GetTestsForAllIterations().
 def RunAndReturnOutput(extra_env, args):
   """Runs the test program and returns its output."""
   environ_copy = os.environ.copy()
   environ_copy.update(extra_env)
   return gtest_test_utils.Subprocess([COMMAND] + args, env=environ_copy).output
def gtest_shuffle_test.ShuffleFlag ()
Definition at line 70 of file gtest_shuffle_test.py.
Referenced by CalculateTestLists(), gtest_shuffle_test.GTestShuffleUnitTest.testShuffleGeneratesNewOrderInEachIteration(), gtest_shuffle_test.GTestShuffleUnitTest.testShuffleRestoresOrderAfterEachIteration(), and gtest_shuffle_test.GTestShuffleUnitTest.testShuffleShardedTestsPreservesPartition().
 def ShuffleFlag():
   return '--gtest_shuffle'
Variable Documentation
string gtest_shuffle_test.__author__ = 'wan@google.com (Zhanyong Wan)' private
Definition at line 33 of file gtest_shuffle_test.py.
list gtest_shuffle_test.ACTIVE_TESTS = []
Definition at line 48 of file gtest_shuffle_test.py.
list gtest_shuffle_test.ALL_TESTS = []
Definition at line 47 of file gtest_shuffle_test.py.
gtest_shuffle_test.COMMAND = gtest_test_utils.GetTestExecutablePath('gtest_shuffle_test_')
Definition at line 39 of file gtest_shuffle_test.py.
list gtest_shuffle_test.FILTERED_TESTS = []
Definition at line 49 of file gtest_shuffle_test.py.
string gtest_shuffle_test.SHARD_INDEX_ENV_VAR = 'GTEST_SHARD_INDEX'
Definition at line 43 of file gtest_shuffle_test.py.
list gtest_shuffle_test.SHARDED_TESTS = []
Definition at line 50 of file gtest_shuffle_test.py.
list gtest_shuffle_test.SHUFFLED_ACTIVE_TESTS = []
Definition at line 53 of file gtest_shuffle_test.py.
list gtest_shuffle_test.SHUFFLED_ALL_TESTS = []
Definition at line 52 of file gtest_shuffle_test.py.
list gtest_shuffle_test.SHUFFLED_FILTERED_TESTS = []
Definition at line 54 of file gtest_shuffle_test.py.
list gtest_shuffle_test.SHUFFLED_SHARDED_TESTS = []
Definition at line 55 of file gtest_shuffle_test.py.
string gtest_shuffle_test.TEST_FILTER = 'A*.A:A*.B:C*'
Definition at line 45 of file gtest_shuffle_test.py.
string gtest_shuffle_test.TOTAL_SHARDS_ENV_VAR = 'GTEST_TOTAL_SHARDS'
Definition at line 42 of file gtest_shuffle_test.py.