proxygen: folly::futures::detail::detail_msvc_15_7_workaround Namespace Reference
folly::futures::detail::detail_msvc_15_7_workaround Namespace Reference
Typedefs
template<typename R , std::size_t S>
using IfArgsSizeIs = std::enable_if_t< R::Arg::ArgsSize::value==S, int >
Functions
template<typename R , typename State , typename T , IfArgsSizeIs< R, 0 > = 0>
decltype(auto) invoke (R, State &state, Try< T > &)
template<typename R , typename State , typename T , IfArgsSizeIs< R, 0 > = 0>
decltype(auto) tryInvoke (R, State &state, Try< T > &)
Typedef Documentation
template<typename R , std::size_t S> using folly::futures::detail::detail_msvc_15_7_workaround::IfArgsSizeIs = typedef std::enable_if_t<R::Arg::ArgsSize::value == S, int>
Definition at line 283 of file Future-inl.h.
Function Documentation
template<typename R , typename State , typename T , IfArgsSizeIs< R, 0 > = 0> decltype(auto) folly::futures::detail::detail_msvc_15_7_workaround::invoke (R , State & state, Try< T > & t)
Definition at line 285 of file Future-inl.h.
References folly::invoke(), and folly::pushmi::detail::t.
Referenced by folly::futures::detail::FutureBase< T >::thenImplementation().
{
   return state.invoke();
 }
template<typename R , typename State , typename T , IfArgsSizeIs< R, 0 > = 0> decltype(auto) folly::futures::detail::detail_msvc_15_7_workaround::tryInvoke (R , State & state, Try< T > & t)
Definition at line 294 of file Future-inl.h.
References testing::Invoke(), and type.
Referenced by folly::futures::detail::chainExecutor().
{
   return state.tryInvoke();
 }