proxygen: testing::internal2 Namespace Reference
testing::internal2 Namespace Reference
Classes
class TypeWithoutFormatter
class TypeWithoutFormatter< T, kConvertibleToInteger >
class TypeWithoutFormatter< T, kProtobuf >
Enumerations
enum TypeKind {
kProtobuf, kConvertibleToInteger, kOtherType, kProtobuf,
kConvertibleToInteger, kOtherType, kProtobuf, kConvertibleToInteger,
kOtherType
}
enum TypeKind {
kProtobuf, kConvertibleToInteger, kOtherType, kProtobuf,
kConvertibleToInteger, kOtherType, kProtobuf, kConvertibleToInteger,
kOtherType
}
enum TypeKind {
kProtobuf, kConvertibleToInteger, kOtherType, kProtobuf,
kConvertibleToInteger, kOtherType, kProtobuf, kConvertibleToInteger,
kOtherType
}
Functions
GTEST_API_ void PrintBytesInObjectTo (const unsigned char *obj_bytes, size_t count,::std::ostream *os)
template<typename Char , typename CharTraits , typename T >
::std::basic_ostream< Char, CharTraits > & operator<< (::std::basic_ostream< Char, CharTraits > &os, const T &x)
void PrintBytesInObjectTo (const unsigned char *obj_bytes, size_t count, ostream *os)
Variables
const size_t kProtobufOneLinerMaxLength = 50
Enumeration Type Documentation
enum testing::internal2::TypeKind
Enumerator
kProtobuf
kConvertibleToInteger
kOtherType
kProtobuf
kConvertibleToInteger
kOtherType
kProtobuf
kConvertibleToInteger
kOtherType
Definition at line 124 of file gtest-printers.h.
               {
   kProtobuf,              // a protobuf type
   kConvertibleToInteger,  // a type implicitly convertible to BiggestInt
                           // (e.g. a named or unnamed enum type)
   kOtherType              // anything else
 };
enum testing::internal2::TypeKind
Enumerator
kProtobuf
kConvertibleToInteger
kOtherType
kProtobuf
kConvertibleToInteger
kOtherType
kProtobuf
kConvertibleToInteger
kOtherType
Definition at line 124 of file gtest-printers.h.
               {
   kProtobuf,              // a protobuf type
   kConvertibleToInteger,  // a type implicitly convertible to BiggestInt
                           // (e.g. a named or unnamed enum type)
   kOtherType              // anything else
 };
enum testing::internal2::TypeKind
Enumerator
kProtobuf
kConvertibleToInteger
kOtherType
kProtobuf
kConvertibleToInteger
kOtherType
kProtobuf
kConvertibleToInteger
kOtherType
Definition at line 124 of file gtest-printers.h.
               {
   kProtobuf,              // a protobuf type
   kConvertibleToInteger,  // a type implicitly convertible to BiggestInt
                           // (e.g. a named or unnamed enum type)
   kOtherType              // anything else
 };
Function Documentation
template<typename Char , typename CharTraits , typename T > ::std::basic_ostream<Char, CharTraits>& testing::internal2::operator<< (::std::basic_ostream< Char, CharTraits > & os, const T & x)
Definition at line 203 of file gtest-printers.h.
References kConvertibleToInteger, kOtherType, kProtobuf, testing::internal2::TypeWithoutFormatter< T, kTypeKind >::PrintValue(), and T.
Referenced by testing::internal2::TypeWithoutFormatter< T, kConvertibleToInteger >::PrintValue().
{
   TypeWithoutFormatter<T,
       (internal::IsAProtocolMessage<T>::value ? kProtobuf :
        internal::ImplicitlyConvertible<const T&, internal::BiggestInt>::value ?
        kConvertibleToInteger : kOtherType)>::PrintValue(x, &os);
   return os;
 }
void testing::internal2::PrintBytesInObjectTo (const unsigned char * obj_bytes, size_t count, ostream * os)
Definition at line 114 of file gtest-printers.cc.
{
   PrintBytesInObjectToImpl(obj_bytes, count, os);
 }
GTEST_API_ void testing::internal2::PrintBytesInObjectTo (const unsigned char * obj_bytes, size_t count, ::std::ostream * os)
Referenced by testing::internal2::TypeWithoutFormatter< T, kTypeKind >::PrintValue().
Variable Documentation
const size_t testing::internal2::kProtobufOneLinerMaxLength = 50
Definition at line 148 of file gtest-printers.h.
Referenced by testing::internal2::TypeWithoutFormatter< T, kTypeKind >::PrintValue().