proxygen: gdb Namespace Reference
gdb Namespace Reference
Classes
class FiberActivateCommand
class FiberDeactivateCommand
class FiberManagerPrinter
class FiberPrinter
class FiberPrintLimitCommand
class FiberUnwinder
class FiberUnwinderFrameFilter
class FiberXMethodMatcher
class FiberXMethodWorker
class FrameId
class GetFiberXMethodMatcher
class GetFiberXMethodWorker
class Shortcut
Functions
def fiber_manager_active_fibers (fm)
def fiber_activate (fiber)
def fiber_deactivate ()
def get_fiber_manager_map (evb_type)
def get_fiber_manager_map_evb ()
def get_fiber_manager_map_vevb ()
def build_pretty_printer ()
def load ()
def info ()
Function Documentation
def gdb.build_pretty_printer ()
Definition at line 350 of file gdb.py.
Referenced by load().
 def build_pretty_printer():
     pp = gdb.printing.RegexpCollectionPrettyPrinter("folly_fibers")
     pp.add_printer('fibers::Fiber', '^folly::fibers::Fiber$', FiberPrinter)
     pp.add_printer('fibers::FiberManager', '^folly::fibers::FiberManager$',
                    FiberManagerPrinter)
     return pp
def gdb.fiber_activate (fiber)
Definition at line 250 of file gdb.py.
References folly::gen.dereference, and folly.format().
Referenced by gdb.FiberXMethodWorker.__call__(), and gdb.FiberActivateCommand.invoke().
 def fiber_activate(fiber):
     fiber_type = gdb.lookup_type("folly::fibers::Fiber")
     if fiber.type != fiber_type:
         fiber = fiber.cast(fiber_type.pointer()).dereference()
     if not FiberPrinter(fiber).backtrace_available():
         return "Can not activate a non-waiting fiber."
     gdb.invalidate_cached_frames()
     FiberUnwinder.set_fiber(fiber)
     return "Fiber 0x{:12x} activated. You can call 'bt' now.".format(int(fiber.address))
def gdb.fiber_deactivate ()
Definition at line 261 of file gdb.py.
Referenced by gdb.FiberDeactivateCommand.invoke().
 def fiber_deactivate():
     FiberUnwinderFrameFilter.set_skip_frame_sp(None)
     gdb.invalidate_cached_frames()
     return "Fiber de-activated."
def gdb.fiber_manager_active_fibers (fm)
Definition at line 91 of file gdb.py.
References folly::gen.dereference.
Referenced by gdb.GetFiberXMethodWorker.__call__(), and gdb.FiberManagerPrinter.children().
 def fiber_manager_active_fibers(fm):
     all_fibers = \
         fm['allFibers_']['data_']['root_plus_size_']['m_header']
     fiber_hook = all_fibers['next_']
     fiber_count = 0
     while fiber_hook != all_fibers.address:
         fiber = fiber_hook.cast(gdb.lookup_type("int64_t"))
         fiber = fiber - gdb.parse_and_eval(
             "(int64_t)&'folly::fibers::Fiber'::globalListHook_")
         fiber = fiber.cast(
             gdb.lookup_type('folly::fibers::Fiber').pointer()).dereference()
         if FiberPrinter(fiber).state != "folly::fibers::Fiber::INVALID":
             yield fiber
         fiber_hook = fiber_hook.dereference()['next_']
         fiber_count = fiber_count + 1
def gdb.get_fiber_manager_map (evb_type)
Definition at line 320 of file gdb.py.
References folly::gen.dereference.
Referenced by get_fiber_manager_map_evb(), and get_fiber_manager_map_vevb().
 def get_fiber_manager_map(evb_type):
     try:
         # Exception thrown if unable to find type
         # Probably because of missing debug symbols
         global_cache_type = gdb.lookup_type(
             "folly::fibers::(anonymous namespace)::GlobalCache<" + evb_type + ">")
     except gdb.error:
         raise gdb.GdbError("Unable to find types. "
                            "Please make sure debug info is available for this binary.\n"
                            "Have you run 'fbload debuginfo_fbpkg'?")
     global_cache_instance_ptr_ptr = gdb.parse_and_eval(
         "&'" + global_cache_type.name + "::instance()::ret'")
     global_cache_instance_ptr = global_cache_instance_ptr_ptr.cast(
         global_cache_type.pointer().pointer()).dereference()
     if global_cache_instance_ptr == 0x0:
         raise gdb.GdbError("FiberManager map is empty.")
     global_cache_instance = global_cache_instance_ptr.dereference()
     return global_cache_instance['map_']
def gdb.get_fiber_manager_map_evb ()
Definition at line 342 of file gdb.py.
References get_fiber_manager_map().
 def get_fiber_manager_map_evb():
     return get_fiber_manager_map("folly::EventBase")
def gdb.get_fiber_manager_map_vevb ()
Definition at line 346 of file gdb.py.
References get_fiber_manager_map().
 def get_fiber_manager_map_vevb():
     return get_fiber_manager_map("folly::VirtualEventBase")
def gdb.info ()
Definition at line 369 of file gdb.py.
 def info():
     return "Pretty printers for folly::fibers"
def gdb.load ()
Definition at line 358 of file gdb.py.
References build_pretty_printer().
 def load():
     gdb.printing.register_pretty_printer(gdb, build_pretty_printer())
     gdb.xmethod.register_xmethod_matcher(gdb, FiberXMethodMatcher())
     gdb.xmethod.register_xmethod_matcher(gdb, GetFiberXMethodMatcher())
     FiberPrintLimitCommand()
     FiberActivateCommand()
     FiberDeactivateCommand()
     Shortcut("get_fiber_manager_map_evb", get_fiber_manager_map_evb)
     Shortcut("get_fiber_manager_map_vevb", get_fiber_manager_map_vevb)