var namespacefolly_1_1test =
[
    [ "detail", "namespacefolly_1_1test_1_1detail.html", "namespacefolly_1_1test_1_1detail" ],
    [ "Barrier", "structfolly_1_1test_1_1Barrier.html", "structfolly_1_1test_1_1Barrier" ],
    [ "CaptureFD", "classfolly_1_1test_1_1CaptureFD.html", "classfolly_1_1test_1_1CaptureFD" ],
    [ "ChangeToTempDir", "classfolly_1_1test_1_1ChangeToTempDir.html", "classfolly_1_1test_1_1ChangeToTempDir" ],
    [ "DeterministicAtomicImpl", "structfolly_1_1test_1_1DeterministicAtomicImpl.html", "structfolly_1_1test_1_1DeterministicAtomicImpl" ],
    [ "DeterministicMutex", "structfolly_1_1test_1_1DeterministicMutex.html", "structfolly_1_1test_1_1DeterministicMutex" ],
    [ "DeterministicSchedule", "classfolly_1_1test_1_1DeterministicSchedule.html", "classfolly_1_1test_1_1DeterministicSchedule" ],
    [ "EnvVarSaver", "structfolly_1_1test_1_1EnvVarSaver.html", "structfolly_1_1test_1_1EnvVarSaver" ],
    [ "FileUtilTest", "classfolly_1_1test_1_1FileUtilTest.html", "classfolly_1_1test_1_1FileUtilTest" ],
    [ "IovecBuffers", "classfolly_1_1test_1_1IovecBuffers.html", "classfolly_1_1test_1_1IovecBuffers" ],
    [ "ManualSchedule", "classfolly_1_1test_1_1ManualSchedule.html", "classfolly_1_1test_1_1ManualSchedule" ],
    [ "MockAsyncServerSocket", "classfolly_1_1test_1_1MockAsyncServerSocket.html", "classfolly_1_1test_1_1MockAsyncServerSocket" ],
    [ "MockAsyncSocket", "classfolly_1_1test_1_1MockAsyncSocket.html", "classfolly_1_1test_1_1MockAsyncSocket" ],
    [ "MockAsyncSSLSocket", "classfolly_1_1test_1_1MockAsyncSSLSocket.html", "classfolly_1_1test_1_1MockAsyncSSLSocket" ],
    [ "MockAsyncTransport", "classfolly_1_1test_1_1MockAsyncTransport.html", "classfolly_1_1test_1_1MockAsyncTransport" ],
    [ "MockAsyncUDPSocket", "structfolly_1_1test_1_1MockAsyncUDPSocket.html", "structfolly_1_1test_1_1MockAsyncUDPSocket" ],
    [ "MockReadCallback", "classfolly_1_1test_1_1MockReadCallback.html", "classfolly_1_1test_1_1MockReadCallback" ],
    [ "MockReplaySafetyCallback", "classfolly_1_1test_1_1MockReplaySafetyCallback.html", "classfolly_1_1test_1_1MockReplaySafetyCallback" ],
    [ "MockTimeoutManager", "classfolly_1_1test_1_1MockTimeoutManager.html", "classfolly_1_1test_1_1MockTimeoutManager" ],
    [ "MockWriteCallback", "classfolly_1_1test_1_1MockWriteCallback.html", "classfolly_1_1test_1_1MockWriteCallback" ],
    [ "MovableInt", "classfolly_1_1test_1_1MovableInt.html", "classfolly_1_1test_1_1MovableInt" ],
    [ "One", "structfolly_1_1test_1_1One.html", "structfolly_1_1test_1_1One" ],
    [ "ReadFileFd", "classfolly_1_1test_1_1ReadFileFd.html", "classfolly_1_1test_1_1ReadFileFd" ],
    [ "Server", "classfolly_1_1test_1_1Server.html", "classfolly_1_1test_1_1Server" ],
    [ "TemporaryDirectory", "classfolly_1_1test_1_1TemporaryDirectory.html", "classfolly_1_1test_1_1TemporaryDirectory" ],
    [ "TemporaryFile", "classfolly_1_1test_1_1TemporaryFile.html", "classfolly_1_1test_1_1TemporaryFile" ],
    [ "TestAcceptCallback", "classfolly_1_1test_1_1TestAcceptCallback.html", "classfolly_1_1test_1_1TestAcceptCallback" ],
    [ "TestAdlIterable", "classfolly_1_1test_1_1TestAdlIterable.html", "classfolly_1_1test_1_1TestAdlIterable" ],
    [ "TestBothIndexingAndIter", "classfolly_1_1test_1_1TestBothIndexingAndIter.html", "classfolly_1_1test_1_1TestBothIndexingAndIter" ],
    [ "TestConnectionEventCallback", "classfolly_1_1test_1_1TestConnectionEventCallback.html", "classfolly_1_1test_1_1TestConnectionEventCallback" ],
    [ "TestRValueConstruct", "classfolly_1_1test_1_1TestRValueConstruct.html", "classfolly_1_1test_1_1TestRValueConstruct" ],
    [ "TestWriteChainAsyncTransportWrapper", "classfolly_1_1test_1_1TestWriteChainAsyncTransportWrapper.html", "classfolly_1_1test_1_1TestWriteChainAsyncTransportWrapper" ],
    [ "TupleTo", "structfolly_1_1test_1_1TupleTo.html", null ],
    [ "TupleTo2", "structfolly_1_1test_1_1TupleTo2.html", null ],
    [ "TupleTo2< TemplateSeq< std::size_t, Ns... > >", "structfolly_1_1test_1_1TupleTo2_3_01TemplateSeq_3_01std_1_1size__t_00_01Ns_8_8_8_01_4_01_4.html", "structfolly_1_1test_1_1TupleTo2_3_01TemplateSeq_3_01std_1_1size__t_00_01Ns_8_8_8_01_4_01_4" ],
    [ "TupleTo< std::tuple< U, Us... >, T >", "structfolly_1_1test_1_1TupleTo_3_01std_1_1tuple_3_01U_00_01Us_8_8_8_01_4_00_01T_01_4.html", "structfolly_1_1test_1_1TupleTo_3_01std_1_1tuple_3_01U_00_01Us_8_8_8_01_4_00_01T_01_4" ],
    [ "TupleTo< std::tuple<>, std::tuple<> >", "structfolly_1_1test_1_1TupleTo_3_01std_1_1tuple_3_4_00_01std_1_1tuple_3_4_01_4.html", "structfolly_1_1test_1_1TupleTo_3_01std_1_1tuple_3_4_00_01std_1_1tuple_3_4_01_4" ],
    [ "Two", "structfolly_1_1test_1_1Two.html", "structfolly_1_1test_1_1Two" ],
    [ "UniformSubset", "structfolly_1_1test_1_1UniformSubset.html", "structfolly_1_1test_1_1UniformSubset" ],
    [ "WriteFileAtomic", "classfolly_1_1test_1_1WriteFileAtomic.html", "classfolly_1_1test_1_1WriteFileAtomic" ]
];