var namespacefizz_1_1server =
[
    [ "test", "namespacefizz_1_1server_1_1test.html", "namespacefizz_1_1server_1_1test" ],
    [ "AeadCookieCipher", "classfizz_1_1server_1_1AeadCookieCipher.html", "classfizz_1_1server_1_1AeadCookieCipher" ],
    [ "AeadTicketCipher", "classfizz_1_1server_1_1AeadTicketCipher.html", "classfizz_1_1server_1_1AeadTicketCipher" ],
    [ "AeadTokenCipher", "classfizz_1_1server_1_1AeadTokenCipher.html", "classfizz_1_1server_1_1AeadTokenCipher" ],
    [ "AllowAllReplayReplayCache", "classfizz_1_1server_1_1AllowAllReplayReplayCache.html", "classfizz_1_1server_1_1AllowAllReplayReplayCache" ],
    [ "AppToken", "structfizz_1_1server_1_1AppToken.html", "structfizz_1_1server_1_1AppToken" ],
    [ "AppTokenValidator", "classfizz_1_1server_1_1AppTokenValidator.html", "classfizz_1_1server_1_1AppTokenValidator" ],
    [ "AsyncFizzServerT", "classfizz_1_1server_1_1AsyncFizzServerT.html", "classfizz_1_1server_1_1AsyncFizzServerT" ],
    [ "AttemptVersionFallback", "structfizz_1_1server_1_1AttemptVersionFallback.html", "structfizz_1_1server_1_1AttemptVersionFallback" ],
    [ "CertManager", "classfizz_1_1server_1_1CertManager.html", "classfizz_1_1server_1_1CertManager" ],
    [ "ClockSkewTolerance", "structfizz_1_1server_1_1ClockSkewTolerance.html", "structfizz_1_1server_1_1ClockSkewTolerance" ],
    [ "CookieCipher", "classfizz_1_1server_1_1CookieCipher.html", "classfizz_1_1server_1_1CookieCipher" ],
    [ "CookieState", "structfizz_1_1server_1_1CookieState.html", "structfizz_1_1server_1_1CookieState" ],
    [ "DualTicketCipher", "classfizz_1_1server_1_1DualTicketCipher.html", "classfizz_1_1server_1_1DualTicketCipher" ],
    [ "FizzServer", "classfizz_1_1server_1_1FizzServer.html", "classfizz_1_1server_1_1FizzServer" ],
    [ "FizzServerContext", "classfizz_1_1server_1_1FizzServerContext.html", "classfizz_1_1server_1_1FizzServerContext" ],
    [ "HandshakeLogging", "structfizz_1_1server_1_1HandshakeLogging.html", "structfizz_1_1server_1_1HandshakeLogging" ],
    [ "ReplayCache", "classfizz_1_1server_1_1ReplayCache.html", "classfizz_1_1server_1_1ReplayCache" ],
    [ "ReportEarlyHandshakeSuccess", "structfizz_1_1server_1_1ReportEarlyHandshakeSuccess.html", null ],
    [ "ReportHandshakeSuccess", "structfizz_1_1server_1_1ReportHandshakeSuccess.html", null ],
    [ "ResumptionState", "structfizz_1_1server_1_1ResumptionState.html", "structfizz_1_1server_1_1ResumptionState" ],
    [ "ServerStateMachine", "classfizz_1_1server_1_1ServerStateMachine.html", "classfizz_1_1server_1_1ServerStateMachine" ],
    [ "ServerTypes", "structfizz_1_1server_1_1ServerTypes.html", "structfizz_1_1server_1_1ServerTypes" ],
    [ "SlidingBloomReplayCache", "classfizz_1_1server_1_1SlidingBloomReplayCache.html", "classfizz_1_1server_1_1SlidingBloomReplayCache" ],
    [ "State", "classfizz_1_1server_1_1State.html", "classfizz_1_1server_1_1State" ],
    [ "StatelessHelloRetryRequest", "structfizz_1_1server_1_1StatelessHelloRetryRequest.html", "structfizz_1_1server_1_1StatelessHelloRetryRequest" ],
    [ "TicketCipher", "classfizz_1_1server_1_1TicketCipher.html", "classfizz_1_1server_1_1TicketCipher" ],
    [ "TicketCodec", "structfizz_1_1server_1_1TicketCodec.html", "structfizz_1_1server_1_1TicketCodec" ]
];