proxygen: folly::fbstring_detail Namespace Reference
folly::fbstring_detail Namespace Reference
Functions
template<class InIt , class OutIt >
std::pair< InIt, OutIt > copy_n (InIt b, typename std::iterator_traits< InIt >::difference_type n, OutIt d)
template<class Pod , class T >
void podFill (Pod *b, Pod *e, T c)
template<class Pod >
void podCopy (const Pod *b, const Pod *e, Pod *d)
template<class Pod >
void podMove (const Pod *b, const Pod *e, Pod *d)
void assume_unreachable ()
Function Documentation
void folly::fbstring_detail::assume_unreachable () inline
Definition at line 202 of file FBString.h.
Referenced by folly::fbstring_core< char >::fbstring_core(), folly::small_vector< Observer< T > *, InlineObservers >::makeSize(), folly::detail::IntegralSizePolicy< SizeType, false >::moveToUninitialized(), folly::detail::IntegralSizePolicy< SizeType, false >::moveToUninitializedEmplace(), folly::fbstring_core< char >::mutableData(), and folly::fbstring_core< char >::reserve().
{
 #if defined(__GNUC__) // Clang also defines __GNUC__
   __builtin_unreachable();
 #elif defined(_MSC_VER)
   __assume(0);
 #else
   // Well, it's better than nothing.
   std::abort();
 #endif
 }
template<class InIt , class OutIt > std::pair<InIt, OutIt> folly::fbstring_detail::copy_n (InIt b, typename std::iterator_traits< InIt >::difference_type n, OutIt d) inline
Definition at line 130 of file FBString.h.
References b.
Referenced by folly::small_vector< Observer< T > *, InlineObservers >::insertImpl(), and folly::basic_fbstring< E, T, A, Storage >::replaceImpl().
              {
   for (; n != 0; --n, ++b, ++d) {
     *d = *b;
   }
   return std::make_pair(b, d);
 }
template<class Pod > void folly::fbstring_detail::podCopy (const Pod * b, const Pod * e, Pod * d) inline
Definition at line 174 of file FBString.h.
References FBSTRING_ASSERT.
Referenced by folly::basic_fbstring< E, T, A, Storage >::append(), folly::basic_fbstring< E, T, A, Storage >::assign(), folly::basic_fbstring< char >::copy(), folly::fbstring_core< Char >::copyMedium(), folly::fbstring_core< Char >::RefCounted::create(), folly::fbstring_core< Char >::initMedium(), folly::fbstring_core< Char >::initSmall(), folly::fbstring_core< Char >::reserveMedium(), folly::fbstring_core< Char >::reserveSmall(), and folly::fbstring_core< Char >::unshare().
{
   FBSTRING_ASSERT(b != nullptr);
   FBSTRING_ASSERT(e != nullptr);
   FBSTRING_ASSERT(d != nullptr);
   FBSTRING_ASSERT(e >= b);
   FBSTRING_ASSERT(d >= e || d + (e - b) <= b);
   memcpy(d, b, (e - b) * sizeof(Pod));
 }
template<class Pod , class T > void folly::fbstring_detail::podFill (Pod * b, Pod * e, T c) inline
Definition at line 141 of file FBString.h.
References b, c, FBSTRING_ASSERT, and T.
Referenced by folly::basic_fbstring< E, T, A, Storage >::append(), folly::basic_fbstring< char >::basic_fbstring(), folly::basic_fbstring< E, T, A, Storage >::insertImplDiscr(), and folly::basic_fbstring< E, T, A, Storage >::resize().
{
   FBSTRING_ASSERT(b && e && b <= e);
   constexpr auto kUseMemset = sizeof(T) == 1;
   if /* constexpr */ (kUseMemset) {
     memset(b, c, size_t(e - b));
   } else {
     auto const ee = b + ((e - b) & ~7u);
     for (; b != ee; b += 8) {
       b[0] = c;
       b[1] = c;
       b[2] = c;
       b[3] = c;
       b[4] = c;
       b[5] = c;
       b[6] = c;
       b[7] = c;
     }
     // Leftovers
     for (; b != e; ++b) {
       *b = c;
     }
   }
 }
template<class Pod > void folly::fbstring_detail::podMove (const Pod * b, const Pod * e, Pod * d) inline
Definition at line 188 of file FBString.h.
References FBSTRING_ASSERT.
Referenced by folly::basic_fbstring< E, T, A, Storage >::append(), folly::basic_fbstring< E, T, A, Storage >::assign(), folly::basic_fbstring< E, T, A, Storage >::insertImpl(), and folly::basic_fbstring< E, T, A, Storage >::insertImplDiscr().
{
   FBSTRING_ASSERT(e >= b);
   memmove(d, b, (e - b) * sizeof(*b));
 }