proxygen: folly::pushmi::__adl Namespace Reference
folly::pushmi::__adl Namespace Reference
Classes
struct do_submit_fn
struct get_executor_fn
struct get_top_fn
struct set_done_fn
struct set_error_fn
struct set_starting_fn
struct set_value_fn
Functions
requires requires (std::declval< S & >().done())) void set_done(S &s) noexcept(noexcept(s.done()))
requires requires (std::declval< S & >().error(std::declval< E >()))) void set_error(S &s
requires E e noexcept (noexcept(s.error(std::move(e))))
requires requires (std::declval< S & >().value(std::declval< VN && >()...))) void set_value(S &s
requires VN &&vn noexcept (noexcept(s.value((VN &&) vn...)))
requires requires (std::declval< S & >().starting(std::declval< Up && >()))) void set_starting(S &s
requires Up &&up noexcept (noexcept(s.starting((Up &&) up)))
requires requires (std::declval< SD & >().executor())) auto executor(SD &sd) noexcept(noexcept(sd.executor()))
requires requires (std::declval< SD & >().submit(std::declval< Out >()))) void submit(SD &sd
requires Out out noexcept (noexcept(sd.submit(std::move(out))))
requires requires (std::declval< SD & >().top())) auto top(SD &sd) noexcept(noexcept(sd.top()))
requires requires (std::declval< SD & >().submit(std::declval< TP(&)(TP)>()(top(std::declval< SD & >())), std::declval< Out >()))) void submit(SD &sd
requires TP Out out noexcept (noexcept(sd.submit(std::move(tp), std::move(out))))
requires requires (std::declval< S & >() ->done())) void set_done(S &s) noexcept(noexcept(s->done()))
requires requires (std::declval< S & >() ->error(std::declval< E >()))) void set_error(S &s
requires E e noexcept (noexcept(s->error(std::move(e))))
requires requires (std::declval< S & >() ->value(std::declval< VN && >()...))) void set_value(S &s
requires VN &&vn noexcept (noexcept(s->value((VN &&) vn...)))
requires requires (std::declval< S & >() ->starting(std::declval< Up && >()))) void set_starting(S &s
requires Up &&up noexcept (noexcept(s->starting((Up &&) up)))
requires requires (std::declval< SD & >() ->executor())) auto executor(SD &sd) noexcept(noexcept(sd->executor()))
requires requires (std::declval< SD & >() ->submit(std::declval< Out >()))) void submit(SD &sd
requires Out out noexcept (noexcept(sd->submit(std::move(out))))
requires requires (std::declval< SD & >() ->top())) auto top(SD &sd) noexcept(noexcept(sd->top()))
requires requires (std::declval< SD & >() ->submit(std::declval< TP(&)(TP)>()(top(std::declval< SD & >())), std::declval< Out >()))) void submit(SD &sd
requires TP Out out noexcept (noexcept(sd->submit(std::move(tp), std::move(out))))
requires Invocable< S & > void set_done (S &) noexcept
requires Invocable< S & > void set_error (S &, E &&) noexcept
requires Invocable< S & > void set_value (S &s) noexcept(noexcept(s()))
template<class T >
void set_done (std::promise< T > &) noexcept
template<class T >
void set_error (std::promise< T > &p, std::exception_ptr e) noexcept
template<class T , class E >
void set_error (std::promise< T > &p, E e) noexcept
template<class T >
void set_value (std::promise< T > &p, T t) noexcept(noexcept(p.set_value(std::move(t))))
void set_value (std::promise< void > &p) noexcept(noexcept(p.set_value()))
requires requires (set_done(std::declval< S & >()))) void set_done(std
requires requires (set_error(std::declval< S & >(), std::declval< E >()))) void set_error(std
requires requires (set_starting(std::declval< S & >(), std::declval< Up && >()))) void set_starting(std
requires requires (executor(std::declval< SD & >()))) auto executor(std
requires requires (submit(std::declval< SD & >(), std::declval< Out >()))) void submit(std
requires requires (top(std::declval< SD & >()))) auto top(std
requires requires (submit(std::declval< SD & >(), std::declval< TP(&)(TP)>()(top(std::declval< SD & >())), std::declval< Out >()))) void submit(std
Variables
requires TP tp
Function Documentation
requires E e folly::pushmi::__adl::noexcept (noexcept(s.error(std::move(e))))
Examples:
/facebook/proxygen/proxygen/folly/folly/container/Iterator.h, /facebook/proxygen/proxygen/folly/folly/lang/RValueReferenceWrapper.h, and /facebook/proxygen/proxygen/folly/folly/memory/EnableSharedFromThis.h.
Definition at line 40 of file extension_points.h.
References folly::gen::move, folly::pushmi::PUSHMI_TEMPLATE(), requires(), and folly::value().
Referenced by wangle::AcceptorHandshakeManager::AcceptorHandshakeManager(), folly::InlineExecutor::add(), folly::IPAddressV4::AddressStorage::AddressStorage(), Alloc< T >::Alloc(), folly::pushmi::any_flow_receiver< PE, PV, E, VN >::any_flow_receiver(), folly::pushmi::any_receiver< E, folly::pushmi::any_executor_ref< E > >::any_receiver(), folly::BasicFixedString< Char, N >::append(), folly::BasicFixedString< Char, N >::assign(), folly::AtomicLinkedList< T >::AtomicLinkedList(), folly::coro::detail::BlockingWaitPromiseBase::FinalAwaiter::await_resume(), folly::coro::detail::InlineTaskPromiseBase::FinalAwaiter::await_resume(), folly::BasicFixedString< Char, N >::BasicFixedString(), folly::BasicTokenBucket< Clock >::BasicTokenBucket(), folly::coro::detail::BlockingWaitTask< T >::BlockingWaitTask(), folly::exception_wrapper::Buffer::Buffer(), folly::call_once(), proxygen::AsyncTimeoutSet::Callback::Callback(), ConcurrentFlowManySender::cancellation_test(), ConcurrentFlowSingleSender::cancellation_test(), folly::BasicFixedString< Char, N >::cappend(), folly::hazptr_domain< DeterministicAtomic >::cleanup(), folly::IOBuf::cloneOneInto(), folly::NotificationQueue< MessageT >::Consumer::Consumer(), folly::Subprocess::Options::dangerousPostForkPreExecCallback(), proxygen::QPACKCodec::decodeEncoderStream(), QueueTest::destroyCallback(), folly::detail::digits_to(), folly::Try< void >::emplace(), wangle::EvbHandshakeHelper::EvbHandshakeHelper(), folly::EventBaseThread::EventBaseThread(), folly::EventHandler::EventHandler(), proxygen::Exception::Exception(), folly::exception_wrapper::exception_wrapper(), wangle::FilePoller::fileTouchedCond(), wangle::FilePoller::fileTouchedCondInternal(), folly::coro::detail::ViaCoroutine::promise_type::final_suspend(), folly::coro::detail::TaskPromiseBase::final_suspend(), wangle::FizzAcceptorHandshakeHelper::FizzAcceptorHandshakeHelper(), flow_receiver_1_test(), flow_receiver_n_test(), proxygen::HTTPDirectResponseHandler::forceConnectionClose(), proxygen::AsyncTimeoutSet::front(), folly::Future< folly::folly::Unit >::Future(), folly::futures::detail::FutureBase< T >::FutureBase(), folly::Try< folly::folly::Unit >::get(), proxygen::MockHTTPTransactionTransport::getCodec(), proxygen::HTTPSessionAcceptor::getCodecFactory(), proxygen::GzipHeaderCodec::getDecodedSize(), folly::AsyncSignalHandler::getEventBase(), getExceptionStackTraceStack(), folly::AsyncSocket::SendMsgParamsCallback::getFlagsImpl(), proxygen::HTTPSession::getHTTPPriority(), proxygen::MockHTTPTransactionTransport::getLocalAddress(), proxygen::HTTPSession::getMaxConcurrentOutgoingStreamsRemote(), proxygen::HTTPMessageFilter::getNextTransactionHandler(), proxygen::MockHTTPTransactionTransport::getPeerAddress(), folly::AsyncSSLSocket::getSecurityProtocol(), proxygen::MockHTTPTransactionTransport::getSetupTransportInfo(), folly::AsyncSSLSocket::getSSLContext(), fizz::client::AsyncFizzClientT< fizz::client::test::MockClientStateMachineInstance >::getState(), wangle::Acceptor::getTotalNumPendingSSLConns(), folly::AsyncSSLSocket::HandshakeCB::handshakeVer(), proxygen::ParseURL::hostNoBrackets(), folly::exception_wrapper::SharedPtr::Impl< Ex >::Impl(), folly::DelayedDestructionBase::IntrusivePtr< AliasType >::IntrusivePtr(), proxygen::HTTPSession::isConnWindowFull(), folly::HHWheelTimer::isDetachable(), isLowercase(), folly::EventBase::keepAliveRelease(), Watchdog::livingWatchdogCount(), folly::LockedPtr< SynchronizedType, LockPolicy >::LockedPtr(), folly::logDisabledHelper(), folly::LogStreamProcessor::LogStreamProcessor(), wangle::LRUInMemoryCache< K, V, M >::LRUInMemoryCache(), main(), folly::DelayedDestructionBase::IntrusivePtr< AliasType >::make(), folly::futures::detail::Core< T >::make(), ImmediateFlowManySender::make_consumer(), ImmediateFlowSingleSender::make_consumer(), ImmediateFlowSingleSender::make_producer(), ImmediateFlowManySender::make_producer(), folly::makeExpected(), folly::makeGuard(), folly::detail::notification_queue_consumer_wrapper< MessageT, TCallback >::messageAvailable(), proxygen::MockByteEventTracker::MockByteEventTracker(), proxygen::MockHTTPTransactionTransport::MockHTTPTransactionTransport(), proxygen::MockHTTPTransactionTransportCallback::MockHTTPTransactionTransportCallback(), proxygen::MockResponseHandler::MockResponseHandler(), move_test(), folly::AsyncSSLSocket::newSocket(), wangle::SSLSessionPersistentCacheBase< K >::TimeUtil::now(), proxygen::MockHTTPMessageFilter::onBody(), proxygen::MockHTTPMessageFilter::onHeadersComplete(), proxygen::MockHTTPMessageFilter::onTrailers(), ProxyService::ProxyHandler::onUpgrade(), folly::File::operator bool(), folly::pushmi::concepts::detail::And< T, U >::operator bool(), folly::pushmi::concepts::detail::Or< T, U >::operator bool(), folly::pushmi::concepts::detail::Not< T >::operator std::integral_constant< bool, B >(), folly::pushmi::concepts::detail::And< T, U >::operator std::integral_constant< bool, B >(), folly::Range< unsigned char * >::operator Tgt(), folly::pushmi::concepts::detail::And< T, U >::operator!(), folly::pushmi::concepts::detail::Or< T, U >::operator!(), folly::pushmi::concepts::detail::Or< T, U >::operator&&(), std::hash< TestStruct >::operator()(), folly::detail::function::FunctionTraits< ReturnType(Args...) const >::SharedProxy::operator()(), hash< folly::Optional< T > >::operator()(), folly::IOBufCompare::operator()(), folly::detail::emplace_iterator_base< Derived, EmplaceImpl, false >::operator++(), folly::exception_tracer::operator<<(), folly::F14VectorSet< Key, Hasher, KeyEqual, Alloc >::operator=(), folly::F14VectorMap< Key, Mapped, Hasher, KeyEqual, Alloc >::operator=(), folly::detail::emplace_iterator_base< Derived, EmplaceImpl, true >::operator=(), folly::Function< std::vector< ResultT >(std::vector< InputT > &&)>::operator=(), folly::pushmi::concepts::detail::Or< T, U >::operator||(), folly::IOBufQueue::options(), folly::DynamicParser::ParserStack::ParserStack(), proxygen::PassThroughTransportFilter::PassThroughTransportFilter(), folly::poly_empty(), folly::poly_move(), folly::poly_type(), folly::DynamicParser::ParserStack::Pop::Pop(), folly::SaturatingSemaphore< true, Atom >::postFastWaiterMayBlock(), folly::ProcessReturnCode::ProcessReturnCode(), receiver_0_test(), receiver_1_test(), receiver_n_test(), folly::AsyncServerSocket::RemoteAcceptor::RemoteAcceptor(), requires(), folly::rref(), folly::rvalue_reference_wrapper< T >::rvalue_reference_wrapper(), folly::AsyncSocket::scheduleInitialReadWrite(), folly::HHWheelTimer::scheduleTimeoutFn(), folly::detail::ScopeGuardImplBase::ScopeGuardImplBase(), folly::SemiFuture< T >::SemiFuture(), proxygen::MockHTTPTransactionTransport::sendBody(), folly::AsyncUDPSocket::sendmsg(), folly::AsyncSSLSocket::setAsyncOperationFinishCallback(), proxygen::ByteEventTracker::setCallback(), folly::AsyncPipeReader::setCloseCallback(), folly::AsyncSocket::setEvbChangedCallback(), proxygen::HTTPConnector::setHTTPCodecFactory(), wangle::CachePersistence< K, V >::setPersistedVersion(), MockPersistenceLayer::setPersistedVersionConcrete(), proxygen::RequestHandler::setResponseHandler(), proxygen::HTTPSessionBase::setSessionStats(), wangle::LRUPersistentCache< K, V, M >::setSyncOnDestroy(), folly::ThreadedRepeatingFunctionRunner::size(), wangle::SSLAcceptorHandshakeHelper::SSLAcceptorHandshakeHelper(), folly::NotificationQueue< MessageT >::Consumer::startConsumingInternal(), folly::detail::str_to_floating(), folly::detail::str_to_integral(), folly::LogStreamProcessor::stream(), inline_executor_flow_single< CancellationFactory >::submit(), inline_executor_flow_many::submit(), folly::fibers::TaskIterator< T >::TaskIterator(), TEST(), folly::TEST(), TEST_F(), wangle::ThreadSafeSSLSessionCache::ThreadSafeSSLSessionCache(), folly::detail::async_timeout_wrapper< TCallback >::timeoutExpired(), folly::toAppend(), folly::toAppendStrImpl(), folly::IPAddressV4::toBinary(), folly::IPAddressV6::toBinary(), folly::Try< folly::folly::Unit >::Try(), folly::Try< void >::Try(), folly::TimedDrivableExecutor::try_drive_until(), folly::coro::Mutex::try_lock(), folly::TypeError::TypeError(), folly::usingJEMalloc(), folly::Promise< folly::folly::Unit >::valid(), folly::IOBuf::wrapBuffer(), folly::IOBuf::wrapBufferAsValue(), TestAsyncTransport::writesAllowed(), folly::AsyncPipeWriter::writev(), proxygen::compress::CompressionScheme::Ack::~Ack(), folly::exception_wrapper::SharedPtr::Base::~Base(), folly::basic_fbstring< char >::~basic_fbstring(), wangle::BroadcastPool< T, R, P >::BroadcastManager::~BroadcastManager(), proxygen::ByteEventTracker::Callback::~Callback(), proxygen::AckTimeout::Callback::~Callback(), wangle::ClientHelloExtStats::~ClientHelloExtStats(), folly::NotificationQueue< MessageT >::Consumer::~Consumer(), proxygen::Exception::~Exception(), folly::ExecutionObserver::~ExecutionObserver(), folly::ExpectWriteErrorCallback::~ExpectWriteErrorCallback(), wangle::FilePersistenceLayer< K, V >::~FilePersistenceLayer(), proxygen::HPACKCodec::~HPACKCodec(), proxygen::HTTPSessionStats::~HTTPSessionStats(), proxygen::QPACKCodec::~QPACKCodec(), proxygen::RequestHandlerFactory::~RequestHandlerFactory(), proxygen::ResponseHandler::~ResponseHandler(), wangle::ServerPool< std::string >::~ServerPool(), SSLCacheClient::~SSLCacheClient(), wangle::SSLStats::~SSLStats(), folly::TimedDrivableExecutor::~TimedDrivableExecutor(), proxygen::HTTPTransaction::Transport::~Transport(), proxygen::TTLBAStats::~TTLBAStats(), and folly::fibers::Baton::Waiter::~Waiter().
{
   s.error(std::move(e));
 }
requires VN&& vn folly::pushmi::__adl::noexcept (noexcept(s.value((VN &&) vn...)))
Definition at line 45 of file extension_points.h.
References folly::pushmi::PUSHMI_TEMPLATE(), and requires().
{
   s.value((VN&&) vn...);
 }
requires Up&& up folly::pushmi::__adl::noexcept (noexcept(s.starting((Up &&) up)))
Definition at line 51 of file extension_points.h.
References folly::pushmi::PUSHMI_TEMPLATE().
{
   s.starting((Up&&) up);
 }
requires Out out folly::pushmi::__adl::noexcept (noexcept(sd.submit(std::move(out))))
Definition at line 65 of file extension_points.h.
References folly::gen::move, and folly::pushmi::PUSHMI_TEMPLATE().
{
   sd.submit(std::move(out));
 }
requires TP Out out folly::pushmi::__adl::noexcept (noexcept(sd.submit(std::move(tp), std::move(out))))
Definition at line 82 of file extension_points.h.
References folly::gen::move, and folly::pushmi::PUSHMI_TEMPLATE().
{
   sd.submit(std::move(tp), std::move(out));
 }
requires E e folly::pushmi::__adl::noexcept (noexcept(s->error(std::move(e))))
Definition at line 97 of file extension_points.h.
References folly::gen::move, folly::pushmi::PUSHMI_TEMPLATE(), requires(), and folly::value().
{
   s->error(std::move(e));
 }
requires VN&& vn folly::pushmi::__adl::noexcept (noexcept(s->value((VN &&) vn...)))
Definition at line 102 of file extension_points.h.
References folly::pushmi::PUSHMI_TEMPLATE(), and requires().
{
   s->value((VN&&) vn...);
 }
requires Up&& up folly::pushmi::__adl::noexcept (noexcept(s->starting((Up &&) up)))
Definition at line 108 of file extension_points.h.
References folly::pushmi::PUSHMI_TEMPLATE().
{
   s->starting((Up&&) up);
 }
requires Out out folly::pushmi::__adl::noexcept (noexcept(sd->submit(std::move(out))))
Definition at line 120 of file extension_points.h.
References folly::gen::move, and folly::pushmi::PUSHMI_TEMPLATE().
{
   sd->submit(std::move(out));
 }
requires TP Out out folly::pushmi::__adl::noexcept (noexcept(sd->submit(std::move(tp), std::move(out))))
Definition at line 137 of file extension_points.h.
References folly::gen::move, folly::pushmi::PUSHMI_TEMPLATE(), and requires().
{
   sd->submit(std::move(tp), std::move(out));
 }
requires folly::pushmi::__adl::requires (std::declval< S & >).done() noexcept
Definition at line 34 of file extension_points.h.
References folly::pushmi::operators::error(), and folly::pushmi::PUSHMI_TEMPLATE().
Referenced by noexcept(), requires(), set_done(), and set_error().
{
   s.done();
 }
requires folly::pushmi::__adl::requires (std::declval< S & >).error(std::declval< E >())
requires folly::pushmi::__adl::requires (std::declval< S & >).value(std::declval< VN && >()...)
requires folly::pushmi::__adl::requires (std::declval< S & >).starting(std::declval< Up && >())
requires folly::pushmi::__adl::requires (std::declval< SD & >).executor() noexcept
Definition at line 56 of file extension_points.h.
References folly::pushmi::PUSHMI_TEMPLATE(), requires(), and folly::pushmi::submit.
{
   return sd.executor();
 }
requires folly::pushmi::__adl::requires (std::declval< SD & >).submit(std::declval< Out >())
requires folly::pushmi::__adl::requires (std::declval< SD & >).top() noexcept
Definition at line 70 of file extension_points.h.
References folly::pushmi::PUSHMI_TEMPLATE(), requires(), folly::pushmi::submit, and folly::pushmi::top.
{
   return sd.top();
 }
requires folly::pushmi::__adl::requires (std::declval< SD & >).submit(std::declval< TP(&)(TP)>()(top(std::declval< SD & >())),std::declval< Out >())
requires folly::pushmi::__adl::requires (std::declval< S & >) ->done() noexcept
Definition at line 91 of file extension_points.h.
References folly::pushmi::operators::error(), folly::pushmi::PUSHMI_TEMPLATE(), and requires().
{
   s->done();
 }
requires folly::pushmi::__adl::requires (std::declval< S & >) ->error(std::declval< E >())
requires folly::pushmi::__adl::requires (std::declval< S & >) ->value(std::declval< VN && >()...)
requires folly::pushmi::__adl::requires (std::declval< S & >) ->starting(std::declval< Up && >())
requires folly::pushmi::__adl::requires (std::declval< SD & >) ->executor() noexcept
Definition at line 113 of file extension_points.h.
References folly::pushmi::PUSHMI_TEMPLATE(), requires(), and folly::pushmi::submit.
{
   return sd->executor();
 }
requires folly::pushmi::__adl::requires (std::declval< SD & >) ->submit(std::declval< Out >())
requires folly::pushmi::__adl::requires (std::declval< SD & >) ->top() noexcept
Definition at line 125 of file extension_points.h.
References folly::pushmi::PUSHMI_TEMPLATE(), requires(), folly::pushmi::submit, and folly::pushmi::top.
{
   return sd->top();
 }
requires folly::pushmi::__adl::requires (std::declval< SD & >) ->submit(std::declval< TP(&)(TP)>()(top(std::declval< SD & >())),std::declval< Out >())
requires folly::pushmi::__adl::requires (set_done(std::declval< S & >()))
Definition at line 190 of file extension_points.h.
References folly::pushmi::PUSHMI_TEMPLATE(), and set_done().
{
   set_done(s.get());
 }
requires folly::pushmi::__adl::requires (set_error(std::declval< S & >(), std::declval< E >()))
Definition at line 196 of file extension_points.h.
References folly::gen::move, noexcept(), folly::pushmi::PUSHMI_TEMPLATE(), requires(), set_error(), and set_value().
{
   set_error(s.get(), std::move(e));
 }
 PUSHMI_TEMPLATE (class S, class... VN)
   (requires requires ( set_value(std::declval<S&>(), std::declval<VN&&>()...) ))
 void set_value(std::reference_wrapper<S> s, VN&&... vn) noexcept(
   noexcept(set_value(s.get(), (VN&&) vn...))) {
   set_value(s.get(), (VN&&) vn...);
 }
requires folly::pushmi::__adl::requires (set_starting(std::declval< S & >(), std::declval< Up && >()))
Definition at line 207 of file extension_points.h.
References folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::set_starting.
{
   set_starting(s.get(), (Up&&) up);
 }
requires folly::pushmi::__adl::requires (executor(std::declval< SD & >()))
Definition at line 213 of file extension_points.h.
References folly::pushmi::executor, and folly::pushmi::PUSHMI_TEMPLATE().
{
   return executor(sd.get());
 }
requires folly::pushmi::__adl::requires (submit(std::declval< SD & >(), std::declval< Out >()))
Definition at line 218 of file extension_points.h.
References folly::gen::move, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::submit.
{
   submit(sd.get(), std::move(out));
 }
requires folly::pushmi::__adl::requires (top(std::declval< SD & >()))
Definition at line 225 of file extension_points.h.
References folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::top.
{
   return top(sd.get());
 }
requires folly::pushmi::__adl::requires (submit(std::declval< SD & >(),std::declval< TP(&)(TP)>()(top(std::declval< SD & >())),std::declval< Out >()))
Definition at line 230 of file extension_points.h.
References folly::gen::move, and folly::pushmi::submit.
{
   submit(sd.get(), std::move(tp), std::move(out));
 }
requires Invocable<S&> void folly::pushmi::__adl::set_done (S &) noexcept
Definition at line 147 of file extension_points.h.
References folly::pushmi::PUSHMI_TEMPLATE(), and requires().
Referenced by requires(), and folly::pushmi::__adl::set_done_fn::requires().
{
 }
template<class T > void folly::pushmi::__adl::set_done (std::promise< T > &) noexcept
Definition at line 167 of file extension_points.h.
 {}
requires Invocable<S&> void folly::pushmi::__adl::set_error (S & , E &&) noexcept
Definition at line 151 of file extension_points.h.
References folly::pushmi::PUSHMI_TEMPLATE(), and requires().
Referenced by folly::pushmi::__adl::set_error_fn::noexcept(), folly::pushmi::__adl::set_value_fn::noexcept(), folly::pushmi::__adl::set_starting_fn::noexcept(), requires(), and folly::pushmi::__adl::set_done_fn::requires().
{
   std::abort();
 }
template<class T > void folly::pushmi::__adl::set_error (std::promise< T > & p, std::exception_ptr e) noexcept
Definition at line 170 of file extension_points.h.
References folly::gen::move.
{
   p.set_exception(std::move(e));
 }
template<class T , class E > void folly::pushmi::__adl::set_error (std::promise< T > & p, E e) noexcept
Definition at line 174 of file extension_points.h.
References folly::gen::move.
{
   p.set_exception(std::make_exception_ptr(std::move(e)));
 }
requires Invocable<S&> void folly::pushmi::__adl::set_value (S & s) noexcept
Definition at line 156 of file extension_points.h.
References s.
Referenced by folly::pushmi::__adl::set_value_fn::noexcept(), and requires().
{
   s();
 }
template<class T > void folly::pushmi::__adl::set_value (std::promise< T > & p, T t) noexcept
Definition at line 178 of file extension_points.h.
References folly::gen::move, and folly::pushmi::t.
{
   p.set_value(std::move(t));
 }
void folly::pushmi::__adl::set_value (std::promise< void > & p) inline noexcept
Definition at line 181 of file extension_points.h.
References folly::pushmi::PUSHMI_TEMPLATE().
{
   p.set_value();
 }
Variable Documentation
requires TP folly::pushmi::__adl::tp
Definition at line 81 of file extension_points.h.
Referenced by folly::ThreadCachedArena::allocateThreadLocalArena(), folly::pushmi::any_time_executor_ref< E, TP >::any_time_executor_ref(), wangle::FilePoller::checkFiles(), duration_to_ts(), std::chrono::PrintTo(), folly::pushmi::time_source_executor< E, TP, NF, Executor >::submit(), TEST(), and time_single_sender_test().