proxygen: gtest_color_test Namespace Reference
gtest_color_test Namespace Reference
Classes
class GTestColorTest
Functions
def SetEnvVar (env_var, value)
def UsesColor (term, color_env_var, color_flag)
Variables
string __author__ = 'wan@google.com (Zhanyong Wan)'
string IS_WINDOWS = 'nt'
string COLOR_ENV_VAR = 'GTEST_COLOR'
string COLOR_FLAG = 'gtest_color'
COMMAND = gtest_test_utils.GetTestExecutablePath('gtest_color_test_')
Function Documentation
def gtest_color_test.SetEnvVar (env_var, value)
Sets the env variable to 'value'; unsets it when 'value' is None.
Definition at line 47 of file gtest_color_test.py.
Referenced by UsesColor().
 def SetEnvVar(env_var, value):
   """Sets the env variable to 'value'; unsets it when 'value' is None."""
   if value is not None:
     os.environ[env_var] = value
   elif env_var in os.environ:
     del os.environ[env_var]
def gtest_color_test.UsesColor (term, color_env_var, color_flag)
Runs gtest_color_test_ and returns its exit code.
Definition at line 56 of file gtest_color_test.py.
References SetEnvVar().
Referenced by gtest_color_test.GTestColorTest.testAliasesOfYesAndNo(), gtest_color_test.GTestColorTest.testEnvVarAndFlag(), gtest_color_test.GTestColorTest.testEnvVarOnly(), gtest_color_test.GTestColorTest.testFlagOnly(), and gtest_color_test.GTestColorTest.testNoEnvVarNoFlag().
 def UsesColor(term, color_env_var, color_flag):
   """Runs gtest_color_test_ and returns its exit code."""
   SetEnvVar('TERM', term)
   SetEnvVar(COLOR_ENV_VAR, color_env_var)
   if color_flag is None:
     args = []
   else:
     args = ['--%s=%s' % (COLOR_FLAG, color_flag)]
   p = gtest_test_utils.Subprocess([COMMAND] + args)
   return not p.exited or p.exit_code
Variable Documentation
string gtest_color_test.__author__ = 'wan@google.com (Zhanyong Wan)' private
Definition at line 34 of file gtest_color_test.py.
string gtest_color_test.COLOR_ENV_VAR = 'GTEST_COLOR'
Definition at line 42 of file gtest_color_test.py.
string gtest_color_test.COLOR_FLAG = 'gtest_color'
Definition at line 43 of file gtest_color_test.py.
gtest_color_test.COMMAND = gtest_test_utils.GetTestExecutablePath('gtest_color_test_')
Definition at line 44 of file gtest_color_test.py.
string gtest_color_test.IS_WINDOWS = 'nt'
Definition at line 40 of file gtest_color_test.py.