proxygen: folly::detail::atomic_notification Namespace Reference
folly::detail::atomic_notification Namespace Reference
Functions
std::cv_status toCvStatus (FutexResult result)
std::cv_status toCvStatus (ParkResult result)
template<template< typename... > class Atom, typename... Args>
void atomic_wait_impl (const Atom< std::uint32_t, Args... > *atomic, std::uint32_t expected)
template<template< typename... > class Atom, typename Integer , typename... Args>
void atomic_wait_impl (const Atom< Integer, Args... > *atomic, Integer expected)
template<template< typename... > class Atom, typename... Args, typename Clock , typename Duration >
std::cv_status atomic_wait_until_impl (const Atom< std::uint32_t, Args... > *atomic, std::uint32_t expected, const std::chrono::time_point< Clock, Duration > &deadline)
template<template< typename... > class Atom, typename Integer , typename... Args, typename Clock , typename Duration >
std::cv_status atomic_wait_until_impl (const Atom< Integer, Args... > *atomic, Integer expected, const std::chrono::time_point< Clock, Duration > &deadline)
template<template< typename... > class Atom, typename... Args>
void atomic_notify_one_impl (const Atom< std::uint32_t, Args... > *atomic)
template<template< typename... > class Atom, typename Integer , typename... Args>
void atomic_notify_one_impl (const Atom< Integer, Args... > *atomic)
template<template< typename... > class Atom, typename Integer , typename... Args>
void atomic_notify_all_impl (const Atom< std::uint32_t, Args... > *atomic)
template<template< typename... > class Atom, typename Integer , typename... Args>
void atomic_notify_all_impl (const Atom< Integer, Args... > *atomic)
Variables
ParkingLot< std::uint32_t > parkingLot
Function Documentation
template<template< typename... > class Atom, typename Integer , typename... Args> void folly::detail::atomic_notification::atomic_notify_all_impl (const Atom< std::uint32_t, Args... > * atomic)
Definition at line 108 of file AtomicNotification-inl.h.
References testing::Args(), Atom, and folly::detail::futexWake().
Referenced by folly::atomic_notify_all().
{
   futexWake(atomic);
   return;
 }
template<template< typename... > class Atom, typename Integer , typename... Args> void folly::detail::atomic_notification::atomic_notify_all_impl (const Atom< Integer, Args... > * atomic)
Definition at line 114 of file AtomicNotification-inl.h.
References folly::data(), FOLLY_SAFE_DCHECK, max, folly::RemoveContinue, and folly::ParkingLot< Data >::unpark().
{
   static_assert(!std::is_same<Integer, std::uint32_t>{}, "");
   parkingLot.unpark(atomic, [&](const auto& data) {
     FOLLY_SAFE_DCHECK(data == std::numeric_limits<std::uint32_t>::max(), "");
     return UnparkControl::RemoveContinue;
   });
 }
template<template< typename... > class Atom, typename... Args> void folly::detail::atomic_notification::atomic_notify_one_impl (const Atom< std::uint32_t, Args... > * atomic)
Definition at line 93 of file AtomicNotification-inl.h.
References testing::Args(), Atom, and folly::detail::futexWake().
Referenced by folly::atomic_notify_one().
{
   futexWake(atomic, 1);
   return;
 }
template<template< typename... > class Atom, typename Integer , typename... Args> void folly::detail::atomic_notification::atomic_notify_one_impl (const Atom< Integer, Args... > * atomic)
Definition at line 99 of file AtomicNotification-inl.h.
References testing::Args(), Atom, folly::data(), FOLLY_SAFE_DCHECK, max, folly::RemoveBreak, and folly::ParkingLot< Data >::unpark().
{
   static_assert(!std::is_same<Integer, std::uint32_t>{}, "");
   parkingLot.unpark(atomic, [&](const auto& data) {
     FOLLY_SAFE_DCHECK(data == std::numeric_limits<std::uint32_t>::max(), "");
     return UnparkControl::RemoveBreak;
   });
 }
template<template< typename... > class Atom, typename... Args> void folly::detail::atomic_notification::atomic_wait_impl (const Atom< std::uint32_t, Args... > * atomic, std::uint32_t expected)
Definition at line 51 of file AtomicNotification-inl.h.
References testing::Args(), Atom, and folly::detail::futexWait().
Referenced by folly::atomic_wait().
{
   futexWait(atomic, expected);
   return;
 }
template<template< typename... > class Atom, typename Integer , typename... Args> void folly::detail::atomic_notification::atomic_wait_impl (const Atom< Integer, Args... > * atomic, Integer expected)
Definition at line 59 of file AtomicNotification-inl.h.
References testing::Args(), Atom, and folly::ParkingLot< Data >::park().
{
   static_assert(!std::is_same<Integer, std::uint32_t>{}, "");
   parkingLot.park(
       atomic, -1, [&] { return atomic->load() == expected; }, [] {});
 }
template<template< typename... > class Atom, typename... Args, typename Clock , typename Duration > std::cv_status folly::detail::atomic_notification::atomic_wait_until_impl (const Atom< std::uint32_t, Args... > * atomic, std::uint32_t expected, const std::chrono::time_point< Clock, Duration > & deadline)
Definition at line 70 of file AtomicNotification-inl.h.
References testing::Args(), Atom, folly::detail::futexWaitUntil(), and toCvStatus().
Referenced by folly::atomic_wait_until().
{
   return toCvStatus(futexWaitUntil(atomic, expected, deadline));
 }
template<template< typename... > class Atom, typename Integer , typename... Args, typename Clock , typename Duration > std::cv_status folly::detail::atomic_notification::atomic_wait_until_impl (const Atom< Integer, Args... > * atomic, Integer expected, const std::chrono::time_point< Clock, Duration > & deadline)
Definition at line 83 of file AtomicNotification-inl.h.
References testing::Args(), Atom, folly::ParkingLot< Data >::park_until(), and toCvStatus().
{
   static_assert(!std::is_same<Integer, std::uint32_t>{}, "");
   return toCvStatus(parkingLot.park_until(
       atomic, -1, [&] { return atomic->load() == expected; }, [] {}, deadline));
 }
std::cv_status folly::detail::atomic_notification::toCvStatus (FutexResult result) inline
We use Futex<std::atomic> as the alias that has the lowest performance overhead with respect to atomic notifications. Assert that atomic_uint_fast_wait_t is the same as Futex<std::atomic> Implementation and specializations for the atomic_wait() family of functions
Definition at line 38 of file AtomicNotification-inl.h.
References folly::detail::TIMEDOUT.
Referenced by atomic_wait_until_impl().
{
   return (result == FutexResult::TIMEDOUT) ? std::cv_status::timeout
                                            : std::cv_status::no_timeout;
 }
std::cv_status folly::detail::atomic_notification::toCvStatus (ParkResult result) inline
Definition at line 42 of file AtomicNotification-inl.h.
References testing::Args(), Atom, parkingLot, and folly::Timeout.
{
   return (result == ParkResult::Timeout) ? std::cv_status::timeout
                                          : std::cv_status::no_timeout;
 }
Variable Documentation
ParkingLot< std::uint32_t > folly::detail::atomic_notification::parkingLot
Definition at line 29 of file AtomicNotification.cpp.
Referenced by toCvStatus().