proxygen: std::tr1 Namespace Reference
std::tr1 Namespace Reference
Namespaces
gtest_internal
Classes
class tuple
class tuple< T0, T1, T2, T3, T4, T5, T6, T7, T8, void >
class tuple< T0, T1, T2, T3, T4, T5, T6, T7, void, void >
class tuple< T0, T1, T2, T3, T4, T5, T6, void, void, void >
class tuple< T0, T1, T2, T3, T4, T5, void, void, void, void >
class tuple< T0, T1, T2, T3, T4, void, void, void, void, void >
class tuple< T0, T1, T2, T3, void, void, void, void, void, void >
class tuple< T0, T1, T2, void, void, void, void, void, void, void >
class tuple< T0, T1, void, void, void, void, void, void, void, void >
class tuple< T0, void, void, void, void, void, void, void, void, void >
class tuple<>
struct tuple_element
struct tuple_size
struct tuple_size< tuple< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9 > >
struct tuple_size< tuple< T0, T1, T2, T3, T4, T5, T6, T7, T8, void > >
struct tuple_size< tuple< T0, T1, T2, T3, T4, T5, T6, T7, void, void > >
struct tuple_size< tuple< T0, T1, T2, T3, T4, T5, T6, void, void, void > >
struct tuple_size< tuple< T0, T1, T2, T3, T4, T5, void, void, void, void > >
struct tuple_size< tuple< T0, T1, T2, T3, T4, void, void, void, void, void > >
struct tuple_size< tuple< T0, T1, T2, T3, void, void, void, void, void, void > >
struct tuple_size< tuple< T0, T1, T2, void, void, void, void, void, void, void > >
struct tuple_size< tuple< T0, T1, void, void, void, void, void, void, void, void > >
struct tuple_size< tuple< T0, void, void, void, void, void, void, void, void, void > >
struct tuple_size< tuple<> >
Functions
tuple make_tuple ()
template<typename T0 >
tuple< T0, void, void, void, void, void, void, void, void, void > make_tuple (const T0 &f0)
template<typename T0 , typename T1 >
tuple< T0, T1, void, void, void, void, void, void, void, void > make_tuple (const T0 &f0, const T1 &f1)
template<typename T0 , typename T1 , typename T2 >
tuple< T0, T1, T2, void, void, void, void, void, void, void > make_tuple (const T0 &f0, const T1 &f1, const T2 &f2)
template<typename T0 , typename T1 , typename T2 , typename T3 >
tuple< T0, T1, T2, T3, void, void, void, void, void, void > make_tuple (const T0 &f0, const T1 &f1, const T2 &f2, const T3 &f3)
template<typename T0 , typename T1 , typename T2 , typename T3 , typename T4 >
tuple< T0, T1, T2, T3, T4, void, void, void, void, void > make_tuple (const T0 &f0, const T1 &f1, const T2 &f2, const T3 &f3, const T4 &f4)
template<typename T0 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
tuple< T0, T1, T2, T3, T4, T5, void, void, void, void > make_tuple (const T0 &f0, const T1 &f1, const T2 &f2, const T3 &f3, const T4 &f4, const T5 &f5)
template<typename T0 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 >
tuple< T0, T1, T2, T3, T4, T5, T6, void, void, void > make_tuple (const T0 &f0, const T1 &f1, const T2 &f2, const T3 &f3, const T4 &f4, const T5 &f5, const T6 &f6)
template<typename T0 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 >
tuple< T0, T1, T2, T3, T4, T5, T6, T7, void, void > make_tuple (const T0 &f0, const T1 &f1, const T2 &f2, const T3 &f3, const T4 &f4, const T5 &f5, const T6 &f6, const T7 &f7)
template<typename T0 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 >
tuple< T0, T1, T2, T3, T4, T5, T6, T7, T8, void > make_tuple (const T0 &f0, const T1 &f1, const T2 &f2, const T3 &f3, const T4 &f4, const T5 &f5, const T6 &f6, const T7 &f7, const T8 &f8)
template<typename T0 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 >
tuple< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9 > make_tuple (const T0 &f0, const T1 &f1, const T2 &f2, const T3 &f3, const T4 &f4, const T5 &f5, const T6 &f6, const T7 &f7, const T8 &f8, const T9 &f9)
template<int k, typename T0 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 >
typename::std::tr1::gtest_internal::AddRef< typename tuple_element< k, tuple< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9 > >::type >::type get (tuple< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9 > &t)
template<int k, typename T0 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 >
typename::std::tr1::gtest_internal::ByRef< typename tuple_element< k, tuple< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9 > >::type >::type get (const tuple< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9 > &t)
template<typename T0 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename U0 , typename U1 , typename U2 , typename U3 , typename U4 , typename U5 , typename U6 , typename U7 , typename U8 , typename U9 >
bool operator== (const tuple< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9 > &t, const tuple< U0, U1, U2, U3, U4, U5, U6, U7, U8, U9 > &u)
template<typename T0 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename U0 , typename U1 , typename U2 , typename U3 , typename U4 , typename U5 , typename U6 , typename U7 , typename U8 , typename U9 >
bool operator!= (const tuple< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9 > &t, const tuple< U0, U1, U2, U3, U4, U5, U6, U7, U8, U9 > &u)
Function Documentation
template<int k, typename T0 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 > typename::std::tr1::gtest_internal::AddRef< typename tuple_element< k, tuple< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9 > >::type >::type std::tr1::get (tuple< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9 > & t)
Definition at line 931 of file gtest-tuple.h.
References testing::Field(), GTEST_10_TUPLE_, GTEST_BY_REF_, GTEST_TUPLE_ELEMENT_, k, and T.
{
   return gtest_internal::Get<k>::Field(t);
 }
template<int k, typename T0 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 > typename::std::tr1::gtest_internal::ByRef< typename tuple_element< k, tuple< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9 > >::type >::type std::tr1::get (const tuple< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9 > & t)
Definition at line 937 of file gtest-tuple.h.
Referenced by std::tr1::gtest_internal::SameSizeTuplePrefixComparator< k, k >::Eq().
{
   return gtest_internal::Get<k>::ConstField(t);
 }
tuple std::tr1::make_tuple () inline
Definition at line 675 of file gtest-tuple.h.
Referenced by folly::acquireLocked(), folly::gen::detail::add_to_tuple(), proxygen::HTTP2Codec::addPriorityNodes(), folly::gen::detail::Zip< Container >::Generator< Value1, Source, Value2, Result >::apply(), BENCHMARK_RELATIVE(), testing::gmock_more_actions_test::Foo::Concat10(), folly::test::TupleTo< std::tuple<>, std::tuple<> >::convert(), folly::test::TupleTo2< TemplateSeq< std::size_t, Ns... > >::convert(), std::tr1::tuple< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::CopyFrom(), fizz::detail::decodeAuthRequest(), fizz::sm::getCertificate(), fizz::sm::getClientCert(), proxygen::HTTPTransaction::getPrioritySummary(), testing::gmock_generated_actions_test::GiantTemplate< T1, T2, T3, k4, k5, k6, T7, T8, T9 >::GiantTemplate(), fizz::sm::negotiateGroup(), fizz::sm::negotiateParameters(), testing::gmock_generated_actions_test::NullaryConstructorClass::NullaryConstructorClass(), wangle::ServerAcceptor< Pipeline >::onDataAvailable(), proxygen::SPDYCodec::onSynCommon(), testing::gtest_printers_test::AllowsGenericStreamingAndImplicitConversionTemplate< T >::operator bool(), testing::gmock_matchers_test::ConvertibleToBool::operator bool(), testing::gmock_generated_actions_test::SumOf6Functor::operator()(), testing::gmock_matchers_test::NotCopyable::operator>=(), proxygen::HTTP2Codec::parseHeadersDecodeFrames(), proxygen::HTTP2Codec::parsePriority(), testing::gmock_generated_actions_test::SubstractAction::Perform(), folly::detail::TupleSelect< TemplateSeq< std::size_t, Ns... > >::select(), proxygen::HTTPSession::sendPriorityImpl(), proxygen::MockHTTPPushHandler::sendPushHeaders(), testing::gmock_generated_actions_test::TenArgConstructorClass::TenArgConstructorClass(), folly::test::TEST(), testing::gmock_generated_actions_test::TEST(), testing::gmock_more_actions_test::TEST(), TEST(), testing::gtest_printers_test::TEST(), folly::TEST(), testing::gmock_matchers_test::TEST(), TEST_F(), folly::tuplePrepend(), testing::gmock_generated_actions_test::UnaryConstructorClass::UnaryConstructorClass(), folly::pushmi::subject< PS, TN... >::subject_shared::value(), testing::internal::FunctionMocker< R(A1)>::With(), testing::internal::FunctionMocker< R(A1, A2)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>::With(), testing::gmock_generated_actions_test::BoolResetter::~BoolResetter(), and testing::gmock_more_actions_test::DeletionTester::~DeletionTester().
 { return tuple<>(); }
template<typename T0 > tuple< T0, void, void, void, void, void, void, void, void, void > std::tr1::make_tuple (const T0 & f0) inline
Definition at line 678 of file gtest-tuple.h.
References GTEST_1_TUPLE_, and T.
{
   return GTEST_1_TUPLE_(T)(f0);
 }
template<typename T0 , typename T1 > tuple< T0, T1, void, void, void, void, void, void, void, void > std::tr1::make_tuple (const T0 & f0, const T1 & f1) inline
Definition at line 683 of file gtest-tuple.h.
References GTEST_2_TUPLE_, and T.
{
   return GTEST_2_TUPLE_(T)(f0, f1);
 }
template<typename T0 , typename T1 , typename T2 > tuple< T0, T1, T2, void, void, void, void, void, void, void > std::tr1::make_tuple (const T0 & f0, const T1 & f1, const T2 & f2) inline
Definition at line 688 of file gtest-tuple.h.
References GTEST_3_TUPLE_, and T.
{
   return GTEST_3_TUPLE_(T)(f0, f1, f2);
 }
template<typename T0 , typename T1 , typename T2 , typename T3 > tuple< T0, T1, T2, T3, void, void, void, void, void, void > std::tr1::make_tuple (const T0 & f0, const T1 & f1, const T2 & f2, const T3 & f3) inline
Definition at line 693 of file gtest-tuple.h.
References GTEST_4_TUPLE_, and T.
                   {
   return GTEST_4_TUPLE_(T)(f0, f1, f2, f3);
 }
template<typename T0 , typename T1 , typename T2 , typename T3 , typename T4 > tuple< T0, T1, T2, T3, T4, void, void, void, void, void > std::tr1::make_tuple (const T0 & f0, const T1 & f1, const T2 & f2, const T3 & f3, const T4 & f4) inline
Definition at line 699 of file gtest-tuple.h.
References GTEST_5_TUPLE_, and T.
{
   return GTEST_5_TUPLE_(T)(f0, f1, f2, f3, f4);
 }
template<typename T0 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > tuple< T0, T1, T2, T3, T4, T5, void, void, void, void > std::tr1::make_tuple (const T0 & f0, const T1 & f1, const T2 & f2, const T3 & f3, const T4 & f4, const T5 & f5) inline
Definition at line 705 of file gtest-tuple.h.
References GTEST_6_TUPLE_, and T.
{
   return GTEST_6_TUPLE_(T)(f0, f1, f2, f3, f4, f5);
 }
template<typename T0 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 > tuple< T0, T1, T2, T3, T4, T5, T6, void, void, void > std::tr1::make_tuple (const T0 & f0, const T1 & f1, const T2 & f2, const T3 & f3, const T4 & f4, const T5 & f5, const T6 & f6) inline
Definition at line 711 of file gtest-tuple.h.
References GTEST_7_TUPLE_, and T.
{
   return GTEST_7_TUPLE_(T)(f0, f1, f2, f3, f4, f5, f6);
 }
template<typename T0 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 > tuple< T0, T1, T2, T3, T4, T5, T6, T7, void, void > std::tr1::make_tuple (const T0 & f0, const T1 & f1, const T2 & f2, const T3 & f3, const T4 & f4, const T5 & f5, const T6 & f6, const T7 & f7) inline
Definition at line 717 of file gtest-tuple.h.
References GTEST_8_TUPLE_, and T.
{
   return GTEST_8_TUPLE_(T)(f0, f1, f2, f3, f4, f5, f6, f7);
 }
template<typename T0 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 > tuple< T0, T1, T2, T3, T4, T5, T6, T7, T8, void > std::tr1::make_tuple (const T0 & f0, const T1 & f1, const T2 & f2, const T3 & f3, const T4 & f4, const T5 & f5, const T6 & f6, const T7 & f7, const T8 & f8) inline
Definition at line 723 of file gtest-tuple.h.
References GTEST_9_TUPLE_, and T.
                   {
   return GTEST_9_TUPLE_(T)(f0, f1, f2, f3, f4, f5, f6, f7, f8);
 }
template<typename T0 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 > tuple< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9 > std::tr1::make_tuple (const T0 & f0, const T1 & f1, const T2 & f2, const T3 & f3, const T4 & f4, const T5 & f5, const T6 & f6, const T7 & f7, const T8 & f8, const T9 & f9) inline
Definition at line 730 of file gtest-tuple.h.
References GTEST_10_TUPLE_, and T.
{
   return GTEST_10_TUPLE_(T)(f0, f1, f2, f3, f4, f5, f6, f7, f8, f9);
 }
template<typename T0 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename U0 , typename U1 , typename U2 , typename U3 , typename U4 , typename U5 , typename U6 , typename U7 , typename U8 , typename U9 > bool std::tr1::operator!= (const tuple< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9 > & t, const tuple< U0, U1, U2, U3, U4, U5, U6, U7, U8, U9 > & u) inline
Definition at line 982 of file gtest-tuple.h.
Referenced by std::tr1::gtest_internal::SameSizeTuplePrefixComparator< k, k >::Eq().
                                                     { return !(t == u); }
template<typename T0 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename U0 , typename U1 , typename U2 , typename U3 , typename U4 , typename U5 , typename U6 , typename U7 , typename U8 , typename U9 > bool std::tr1::operator== (const tuple< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9 > & t, const tuple< U0, U1, U2, U3, U4, U5, U6, U7, U8, U9 > & u) inline
Definition at line 974 of file gtest-tuple.h.
References testing::Eq().
Referenced by std::tr1::gtest_internal::SameSizeTuplePrefixComparator< k, k >::Eq().
{
   return gtest_internal::SameSizeTuplePrefixComparator<
       tuple_size<GTEST_10_TUPLE_(T) >::value,
       tuple_size<GTEST_10_TUPLE_(U) >::value>::Eq(t, u);
 }