proxygen: fizz::client::detail Namespace Reference
fizz::client::detail Namespace Reference
Functions
template<typename... Args>
Actions actions (Args &&...act)
Actions processEvent (const State &state, Param param)
Actions handleError (const State &state, ReportError error, Optional< AlertDescription > alertDesc)
Actions handleAppClose (const State &state)
Actions handleInvalidEvent (const State &state, Event event, Param param)
Function Documentation
template<typename... Args> Actions fizz::client::detail::actions (Args &&... act)
Definition at line 86 of file Actions.h.
References fizz::detail::addAction().
Referenced by fizz::client::test::AsyncFizzClientTest::completeEarlyHandshake(), fizz::client::test::ClientProtocolTest::doFinishedFlow(), fizz::client::test::AsyncFizzClientTest::expectAppClose(), fizz::test::ProtocolTest< ClientTypes, Actions >::expectError(), fizz::test::ProtocolTest< ClientTypes, Actions >::expectExceptionType(), fizz::test::ProtocolTest< ClientTypes, Actions >::expectSingleAction(), fizz::FizzBase< FizzServer< ActionMoveVisitor, SM >, ActionMoveVisitor, SM >::FizzBase(), fizz::client::test::AsyncFizzClientTest::fullHandshakeSuccess(), fizz::sm::getClientCert(), fizz::sm::getEarlyDataParams(), fizz::sm::getHrrKeyExchangers(), fizz::sm::getMaxEarlyDataSize(), fizz::test::ProtocolTest< ClientTypes, Actions >::getNumActions(), handleAppClose(), fizz::sm::handleCertMsg(), fizz::sm::handleEarlyAppWrite(), handleError(), fizz::sm::ignoreEarlyAppWrite(), fizz::sm::negotiatePsk(), fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >::processPendingEvents(), fizz::client::ClientStateMachine::processSocketData(), fizz::client::test::TEST_F(), fizz::server::test::TEST_F(), and fizz::sm::validateAcceptedEarly().
{
   Actions acts;
   fizz::detail::addAction(acts, std::forward<Args>(act)...);
   return acts;
 }
Actions fizz::client::detail::handleAppClose (const State & state)
Definition at line 248 of file ClientProtocol.cpp.
References actions(), fizz::alert, fizz::close_notify, fizz::WriteToSocket::contents, fizz::client::Error, folly::gen::move, fizz::detail::write(), fizz::WriteRecordLayer::writeAlert(), and fizz::client::State::writeRecordLayer().
Referenced by fizz::client::ClientStateMachine::processAppClose().
{
   auto transition = [](State& newState) {
     newState.state() = StateEnum::Error;
     newState.writeRecordLayer() = nullptr;
     newState.readRecordLayer() = nullptr;
   };
   if (state.writeRecordLayer()) {
     Alert alert(AlertDescription::close_notify);
     WriteToSocket write;
     write.contents.emplace_back(
         state.writeRecordLayer()->writeAlert(std::move(alert)));
     return actions(std::move(transition), std::move(write));
   } else {
     return actions(std::move(transition));
   }
 }
Actions fizz::client::detail::handleError (const State & state, ReportError error, Optional< AlertDescription > alertDesc)
Definition at line 225 of file ClientProtocol.cpp.
References actions(), fizz::alert, fizz::WriteToSocket::contents, fizz::client::Error, folly::gen::move, fizz::client::State::state(), fizz::detail::write(), fizz::WriteRecordLayer::writeAlert(), and fizz::client::State::writeRecordLayer().
Referenced by processEvent(), and fizz::client::ClientStateMachine::processSocketData().
{
   if (state.state() == StateEnum::Error) {
     return actions(std::move(error));
   }
   auto transition = [](State& newState) {
     newState.state() = StateEnum::Error;
     newState.writeRecordLayer() = nullptr;
     newState.readRecordLayer() = nullptr;
   };
   if (alertDesc && state.writeRecordLayer()) {
     Alert alert(*alertDesc);
     WriteToSocket write;
     write.contents.emplace_back(
         state.writeRecordLayer()->writeAlert(std::move(alert)));
     return actions(std::move(transition), std::move(write), std::move(error));
   } else {
     return actions(std::move(transition), std::move(error));
   }
 }
Actions fizz::client::detail::handleInvalidEvent (const State & state, Event event, Param param)
Definition at line 265 of file ClientProtocol.cpp.
References fizz::Alert, fizz::alert, folly::none, fizz::client::State::state(), fizz::toString(), and fizz::unexpected_message.
{
   if (event == Event::Alert) {
     auto& alert = boost::get<Alert>(param);
     throw FizzException(
         folly::to<std::string>(
             "received alert: ",
             toString(alert.description),
             ", in state ",
             toString(state.state())),
         folly::none);
   } else {
     throw FizzException(
         folly::to<std::string>(
             "invalid event: ",
             toString(event),
             ", in state ",
             toString(state.state())),
         AlertDescription::unexpected_message);
   }
 }
Actions fizz::client::detail::processEvent (const State & state, Param param)
Definition at line 207 of file ClientProtocol.cpp.
References folly::apply_visitor(), fizz::FizzException::getAlert(), fizz::sm::StateMachine< SM >::getHandler(), handleError(), folly::gen::move, fizz::client::State::state(), and fizz::unexpected_message.
Referenced by fizz::client::test::ClientProtocolTest::doFinishedFlow(), fizz::client::ClientStateMachine::processAppWrite(), fizz::client::ClientStateMachine::processConnect(), fizz::client::ClientStateMachine::processEarlyAppWrite(), fizz::client::ClientStateMachine::processSocketData(), fizz::client::ClientStateMachine::processWriteNewSessionTicket(), fizz::client::test::TEST_F(), and fizz::server::test::TEST_F().
{
   auto event = boost::apply_visitor(EventVisitor(), param);
   try {
     return sm::StateMachine<ClientTypes>::getHandler(state.state(), event)(
         state, std::move(param));
   } catch (const FizzException& e) {
     return detail::handleError(
         state,
         ReportError(folly::exception_wrapper(std::current_exception(), e)),
         e.getAlert());
   } catch (const std::exception& e) {
     return detail::handleError(
         state,
         ReportError(folly::exception_wrapper(std::current_exception(), e)),
         AlertDescription::unexpected_message);
   }
 }