proxygen: fizz::testing Namespace Reference
fizz::testing Namespace Reference
Classes
class ECDSA256Test
class ECDSA384Test
class ECDSA521Test
class ECDSATest
struct KdfParams
class KeyDerivationTest
struct Params
Functions
void setPoint (EcKeyUniquePtr &key, std::string x, std::string y)
EvpPkeyUniquePtr getKey (int nid, const Params &param)
void modifySig (folly::IOBuf *sig)
void modifyData (folly::IOBuf *sig, std::string &msg)
TEST_P (ECDSA256Test, TestSignature)
TEST_P (ECDSA384Test, TestSignature)
TEST_P (ECDSA521Test, TestSignature)
INSTANTIATE_TEST_CASE_P (TestVectors, ECDSA256Test,::testing::Values(Params{"sample","C9AFA9D845BA75166B5C215767B1D6934E50C3DB36E89B127B8A622B120F6721","60FED4BA255A9D31C961EB74C6356D68C049B8923B61FA6CE669622E60F29FB6","7903FE1008B8BC99A41AE9E95628BC64F2F1B20C2D7E9F5177A3C294D4462299"}))
INSTANTIATE_TEST_CASE_P (TestVectors, ECDSA384Test,::testing::Values(Params{"sample","6B9D3DAD2E1B8C1C05B19875B6659F4DE23C3B667BF297BA9AA47740787137D8""96D5724E4C70A825F872C9EA60D2EDF5","EC3A4E415B4E19A4568618029F427FA5DA9A8BC4AE92E02E06AAE5286B300C64""DEF8F0EA9055866064A254515480BC13","8015D9B72D7D57244EA8EF9AC0C621896708A59367F9DFB9F54CA84B3F1C9DB1""288B231C3AE0D4FE7344FD2533264720"}))
INSTANTIATE_TEST_CASE_P (TestVectors, ECDSA521Test,::testing::Values(Params{"sample","00FAD06DAA62BA3B25D2FB40133DA757205DE67F5BB0018FEE8C86E1B68C7E75C""AA896EB32F1F47C70855836A6D16FCC1466F6D8FBEC67DB89EC0C08B0E996B83""538","01894550D0785932E00EAA23B694F213F8C3121F86DC97A04E5A7167DB4E5BCD3""71123D46E45DB6B5D5370A7F20FB633155D38FFA16D2BD761DCAC474B9A2F502""3A4","00493101C962CD4D2FDDF782285E64584139C2F91B47F87FF82354D6630F746A2""8A0DB25741B5B34A828008B22ACC23F924FAAFBD4D33F81EA66956DFEAA2BFDF""CF5"}))
TEST_P (KeyDerivationTest, ExpandLabel)
TEST (KeyDerivation, DeriveSecret)
TEST (KeyDerivation, Sha256BlankHash)
INSTANTIATE_TEST_CASE_P (KeyDerivation, KeyDerivationTest,::testing::Values(KdfParams{"09cf566b0a8cb6910fd56947fd030027f8195fc6c5b18ded76d758b436f5db2b","handshake key expansion, client write iv","b89ff73312c94b89fadc3320689fd2316a9fd04116b6742e5920a35aaed072a5","0788c228aca5f4b6873b7b57"}, KdfParams{"6174b457f0282fcad096afd50eb92d172638b6fa9baaf8e23ef6b23fe551df73","server finished","","e1ad4d2331428327317047fbf73f3545a8c46fc17b1db445586e9e9b4249c00d"}, KdfParams{"09cf566b0a8cb6910fd56947fd030027f8195fc6c5b18ded76d758b436f5db2b","handshake key expansion, client write key","b89ff73312c94b89fadc3320689fd2316a9fd04116b6742e5920a35aaed072a5","93f640530d77b1d386e1d1089ec86382"}))
Function Documentation
EvpPkeyUniquePtr fizz::testing::getKey (int nid, const Params & param)
Definition at line 46 of file ECSignatureTest.cpp.
References fizz::testing::Params::priv, fizz::testing::Params::pubX, fizz::testing::Params::pubY, setPoint(), uint8_t, and folly::unhexlify().
{
   auto privKeyBin = unhexlify(param.priv);
   BIGNUMUniquePtr privateBn(
       BN_bin2bn((uint8_t*)privKeyBin.c_str(), privKeyBin.size(), nullptr));
   EcKeyUniquePtr privateKey(EC_KEY_new_by_curve_name(nid));
   EC_KEY_set_private_key(privateKey.get(), privateBn.get());
   setPoint(privateKey, param.pubX, param.pubY);
   EvpPkeyUniquePtr pkeyPrivateKey(EVP_PKEY_new());
   EVP_PKEY_set1_EC_KEY(pkeyPrivateKey.get(), privateKey.get());
   return pkeyPrivateKey;
 }
fizz::testing::INSTANTIATE_TEST_CASE_P (KeyDerivation , KeyDerivationTest , ::testing::Values(KdfParams{"09cf566b0a8cb6910fd56947fd030027f8195fc6c5b18ded76d758b436f5db2b","handshake key expansion, client write iv","b89ff73312c94b89fadc3320689fd2316a9fd04116b6742e5920a35aaed072a5","0788c228aca5f4b6873b7b57"}, KdfParams{"6174b457f0282fcad096afd50eb92d172638b6fa9baaf8e23ef6b23fe551df73","server finished","","e1ad4d2331428327317047fbf73f3545a8c46fc17b1db445586e9e9b4249c00d"}, KdfParams{"09cf566b0a8cb6910fd56947fd030027f8195fc6c5b18ded76d758b436f5db2b","handshake key expansion, client write key","b89ff73312c94b89fadc3320689fd2316a9fd04116b6742e5920a35aaed072a5","93f640530d77b1d386e1d1089ec86382"}))
Referenced by TEST().
fizz::testing::INSTANTIATE_TEST_CASE_P (TestVectors , ECDSA256Test , ::testing::Values(Params{"sample","C9AFA9D845BA75166B5C215767B1D6934E50C3DB36E89B127B8A622B120F6721","60FED4BA255A9D31C961EB74C6356D68C049B8923B61FA6CE669622E60F29FB6","7903FE1008B8BC99A41AE9E95628BC64F2F1B20C2D7E9F5177A3C294D4462299"}))
fizz::testing::INSTANTIATE_TEST_CASE_P (TestVectors , ECDSA384Test , ::testing::Values(Params{"sample","6B9D3DAD2E1B8C1C05B19875B6659F4DE23C3B667BF297BA9AA47740787137D8""96D5724E4C70A825F872C9EA60D2EDF5","EC3A4E415B4E19A4568618029F427FA5DA9A8BC4AE92E02E06AAE5286B300C64""DEF8F0EA9055866064A254515480BC13","8015D9B72D7D57244EA8EF9AC0C621896708A59367F9DFB9F54CA84B3F1C9DB1""288B231C3AE0D4FE7344FD2533264720"}))
fizz::testing::INSTANTIATE_TEST_CASE_P (TestVectors , ECDSA521Test , ::testing::Values(Params{"sample","00FAD06DAA62BA3B25D2FB40133DA757205DE67F5BB0018FEE8C86E1B68C7E75C""AA896EB32F1F47C70855836A6D16FCC1466F6D8FBEC67DB89EC0C08B0E996B83""538","01894550D0785932E00EAA23B694F213F8C3121F86DC97A04E5A7167DB4E5BCD3""71123D46E45DB6B5D5370A7F20FB633155D38FFA16D2BD761DCAC474B9A2F502""3A4","00493101C962CD4D2FDDF782285E64584139C2F91B47F87FF82354D6630F746A2""8A0DB25741B5B34A828008B22ACC23F924FAAFBD4D33F81EA66956DFEAA2BFDF""CF5"}))
Referenced by TEST_P().
void fizz::testing::modifyData (folly::IOBuf * sig, std::string & msg)
Definition at line 67 of file ECSignatureTest.cpp.
References folly::IOBuf::writableData().
Referenced by TEST_P().
{
   auto& sigPtr = sig->writableData()[10];
   if (sigPtr == 1) {
     sigPtr = 2;
   } else {
     sigPtr = 1;
   }
   auto& msgPtr = msg[2];
   if (msgPtr == 1) {
     msgPtr = 2;
   } else {
     msgPtr = 1;
   }
 }
void fizz::testing::modifySig (folly::IOBuf * sig)
Definition at line 58 of file ECSignatureTest.cpp.
References folly::IOBuf::writableData().
Referenced by TEST_P().
{
   auto& sigPtr = sig->writableData()[10];
   if (sigPtr == 1) {
     sigPtr = 2;
   } else {
     sigPtr = 1;
   }
 }
void fizz::testing::setPoint (EcKeyUniquePtr & key, std::string x, std::string y)
Definition at line 38 of file ECSignatureTest.cpp.
References uint8_t, and folly::unhexlify().
Referenced by getKey().
{
   auto binX = unhexlify(x);
   auto binY = unhexlify(y);
   BIGNUMUniquePtr numX(BN_bin2bn((uint8_t*)binX.data(), binX.size(), nullptr));
   BIGNUMUniquePtr numY(BN_bin2bn((uint8_t*)binY.data(), binY.size(), nullptr));
   EC_KEY_set_public_key_affine_coordinates(key.get(), numX.get(), numY.get());
 }
fizz::testing::TEST (KeyDerivation , DeriveSecret)
Definition at line 47 of file KeyDerivationTest.cpp.
References fizz::kHkdfLabelPrefix, folly::range(), secret, and folly::Range< Iter >::str().
{
   // dummy prk
   std::vector<uint8_t> secret(
       KeyDerivationImpl<Sha256>(kHkdfLabelPrefix.str()).hashLength());
   std::vector<uint8_t> messageHash(
       KeyDerivationImpl<Sha256>(kHkdfLabelPrefix.str()).hashLength());
   auto deriver = KeyDerivationImpl<Sha256>(kHkdfLabelPrefix.str());
   deriver.deriveSecret(range(secret), "hey", range(messageHash));
 }
fizz::testing::TEST (KeyDerivation , Sha256BlankHash)
Definition at line 57 of file KeyDerivationTest.cpp.
References EXPECT_EQ, INSTANTIATE_TEST_CASE_P(), fizz::kHkdfLabelPrefix, folly::range(), and folly::Range< Iter >::str().
{
   std::vector<uint8_t> computed(
       KeyDerivationImpl<Sha256>(kHkdfLabelPrefix.str()).hashLength());
   folly::IOBuf blankBuf;
   Sha256::hash(blankBuf, MutableByteRange(computed.data(), computed.size()));
   EXPECT_EQ(
       StringPiece(
           KeyDerivationImpl<Sha256>(kHkdfLabelPrefix.str()).blankHash()),
       StringPiece(folly::range(computed)));
 }
fizz::testing::TEST_P (KeyDerivationTest , ExpandLabel)
Definition at line 29 of file KeyDerivationTest.cpp.
References EXPECT_EQ, folly::hexlify(), fizz::kHkdfLabelPrefix, fizz::test::label, folly::range(), secret, folly::Range< Iter >::size(), folly::Range< Iter >::str(), string, folly::unhexlify(), and folly::IOBuf::wrapBuffer().
{
   auto prk = unhexlify(GetParam().secret);
   auto hashValue = unhexlify(GetParam().hashValue);
   auto hash = IOBuf::wrapBuffer(range(hashValue));
   auto secret = std::vector<uint8_t>(prk.begin(), prk.end());
   auto deriver = KeyDerivationImpl<Sha256>(kHkdfLabelPrefix.str());
   auto out = deriver.expandLabel(
       range(secret),
       GetParam().label,
       hash->clone(),
       GetParam().result.size() / 2);
   std::string hexOut = hexlify(out->coalesce());
   EXPECT_EQ(GetParam().result, hexOut);
 }
fizz::testing::TEST_P (ECDSA256Test , TestSignature)
Definition at line 82 of file ECSignatureTest.cpp.
References folly::IOBuf::copyBuffer(), EXPECT_THROW, getKey(), modifyData(), modifySig(), folly::gen::move, fizz::OpenSSLSignature< T >::setKey(), folly::sig, fizz::OpenSSLSignature< T >::sign(), string, and fizz::OpenSSLSignature< T >::verify().
{
   auto key = getKey(P256::curveNid, GetParam());
   OpenSSLSignature<KeyType::P256> ecdsa;
   ecdsa.setKey(std::move(key));
   {
     std::string msg = GetParam().msg;
     auto sig = ecdsa.sign<SignatureScheme::ecdsa_secp256r1_sha256>(
         IOBuf::copyBuffer(msg)->coalesce());
     ecdsa.verify<SignatureScheme::ecdsa_secp256r1_sha256>(
         IOBuf::copyBuffer(msg)->coalesce(), sig->coalesce());
   }
   {
     std::string msg = GetParam().msg;
     auto sig = ecdsa.sign<SignatureScheme::ecdsa_secp256r1_sha256>(
         IOBuf::copyBuffer(msg)->coalesce());
     modifySig(sig.get());
     EXPECT_THROW(
         ecdsa.verify<SignatureScheme::ecdsa_secp256r1_sha256>(
             IOBuf::copyBuffer(msg)->coalesce(), sig->coalesce()),
         std::runtime_error);
   }
   {
     std::string msg = GetParam().msg;
     auto sig = ecdsa.sign<SignatureScheme::ecdsa_secp256r1_sha256>(
         IOBuf::copyBuffer(msg)->coalesce());
     modifyData(sig.get(), msg);
     EXPECT_THROW(
         ecdsa.verify<SignatureScheme::ecdsa_secp256r1_sha256>(
             IOBuf::copyBuffer(msg)->coalesce(), sig->coalesce()),
         std::runtime_error);
   }
 }
fizz::testing::TEST_P (ECDSA384Test , TestSignature)
Definition at line 115 of file ECSignatureTest.cpp.
References folly::IOBuf::copyBuffer(), EXPECT_THROW, getKey(), modifyData(), modifySig(), folly::gen::move, fizz::OpenSSLSignature< T >::setKey(), folly::sig, fizz::OpenSSLSignature< T >::sign(), string, and fizz::OpenSSLSignature< T >::verify().
{
   auto key = getKey(P384::curveNid, GetParam());
   OpenSSLSignature<KeyType::P384> ecdsa;
   ecdsa.setKey(std::move(key));
   {
     std::string msg = GetParam().msg;
     auto sig = ecdsa.sign<SignatureScheme::ecdsa_secp384r1_sha384>(
         IOBuf::copyBuffer(msg)->coalesce());
     ecdsa.verify<SignatureScheme::ecdsa_secp384r1_sha384>(
         IOBuf::copyBuffer(msg)->coalesce(), sig->coalesce());
   }
   {
     std::string msg = GetParam().msg;
     auto sig = ecdsa.sign<SignatureScheme::ecdsa_secp384r1_sha384>(
         IOBuf::copyBuffer(msg)->coalesce());
     modifySig(sig.get());
     EXPECT_THROW(
         ecdsa.verify<SignatureScheme::ecdsa_secp384r1_sha384>(
             IOBuf::copyBuffer(msg)->coalesce(), sig->coalesce()),
         std::runtime_error);
   }
   {
     std::string msg = GetParam().msg;
     auto sig = ecdsa.sign<SignatureScheme::ecdsa_secp384r1_sha384>(
         IOBuf::copyBuffer(msg)->coalesce());
     modifyData(sig.get(), msg);
     EXPECT_THROW(
         ecdsa.verify<SignatureScheme::ecdsa_secp384r1_sha384>(
             IOBuf::copyBuffer(msg)->coalesce(), sig->coalesce()),
         std::runtime_error);
   }
 }
fizz::testing::TEST_P (ECDSA521Test , TestSignature)
Definition at line 148 of file ECSignatureTest.cpp.
References folly::IOBuf::copyBuffer(), EXPECT_THROW, getKey(), INSTANTIATE_TEST_CASE_P(), modifyData(), modifySig(), folly::gen::move, fizz::OpenSSLSignature< T >::setKey(), folly::sig, fizz::OpenSSLSignature< T >::sign(), string, and fizz::OpenSSLSignature< T >::verify().
{
   auto key = getKey(P521::curveNid, GetParam());
   OpenSSLSignature<KeyType::P521> ecdsa;
   ecdsa.setKey(std::move(key));
   {
     std::string msg = GetParam().msg;
     auto sig = ecdsa.sign<SignatureScheme::ecdsa_secp521r1_sha512>(
         IOBuf::copyBuffer(msg)->coalesce());
     ecdsa.verify<SignatureScheme::ecdsa_secp521r1_sha512>(
         IOBuf::copyBuffer(msg)->coalesce(), sig->coalesce());
   }
   {
     std::string msg = GetParam().msg;
     auto sig = ecdsa.sign<SignatureScheme::ecdsa_secp521r1_sha512>(
         IOBuf::copyBuffer(msg)->coalesce());
     modifySig(sig.get());
     EXPECT_THROW(
         ecdsa.verify<SignatureScheme::ecdsa_secp521r1_sha512>(
             IOBuf::copyBuffer(msg)->coalesce(), sig->coalesce()),
         std::runtime_error);
   }
   {
     std::string msg = GetParam().msg;
     auto sig = ecdsa.sign<SignatureScheme::ecdsa_secp521r1_sha512>(
         IOBuf::copyBuffer(msg)->coalesce());
     modifyData(sig.get(), msg);
     EXPECT_THROW(
         ecdsa.verify<SignatureScheme::ecdsa_secp521r1_sha512>(
             IOBuf::copyBuffer(msg)->coalesce(), sig->coalesce()),
         std::runtime_error);
   }
 }