proxygen: a_ns Namespace Reference
a_ns Namespace Reference
Functions
FOLLY_SETTING_DEFINE (follytest, public_flag_to_a, int, 456,"Public flag to a")
int a_func ()
void setRemote (int value)
int getRemote ()
FOLLY_SETTING_DECLARE (follytest, public_flag_to_a, int)
Function Documentation
int a_ns::a_func ()
Definition at line 26 of file a.cpp.
References FOLLY_SETTING.
Referenced by TEST().
              {
   return *FOLLY_SETTING(follytest, public_flag_to_a) +
       *FOLLY_SETTING(follytest, internal_flag_to_a);
 }
a_ns::FOLLY_SETTING_DECLARE (follytest , public_flag_to_a , int)
a_ns::FOLLY_SETTING_DEFINE (follytest , public_flag_to_a , int , 456 , "Public flag to a")
int a_ns::getRemote ()
Definition at line 35 of file a.cpp.
References FOLLY_SETTING.
Referenced by TEST().
                 {
   return *FOLLY_SETTING(follytest, public_flag_to_a);
 }
void a_ns::setRemote (int value)
Definition at line 31 of file a.cpp.
References FOLLY_SETTING.
Referenced by TEST().
{
   FOLLY_SETTING(follytest, public_flag_to_a).set(value, "remote_set");
 }