proxygen: folly::padded Namespace Reference
folly::padded Namespace Reference
Namespaces
detail
Classes
class Adaptor
class Iterator
class Node
class Node< T, NS, typename detail::NodeValid< T, NS >::type >
Functions
template<class Container >
Iterator< typename Container::const_iterator > cbegin (const Container &c)
template<class Container >
Iterator< typename Container::const_iterator > cend (const Container &c)
template<class Container >
Iterator< typename Container::const_iterator > begin (const Container &c)
template<class Container >
Iterator< typename Container::const_iterator > end (const Container &c)
template<class Container >
Iterator< typename Container::iterator > begin (Container &c)
template<class Container >
Iterator< typename Container::iterator > end (Container &c)
Function Documentation
template<class Container > Iterator<typename Container::const_iterator> folly::padded::begin (const Container & c)
Definition at line 329 of file Padded.h.
References cbegin().
Referenced by TEST_F().
{
   return cbegin(c);
 }
template<class Container > Iterator<typename Container::iterator> folly::padded::begin (Container & c)
Definition at line 339 of file Padded.h.
Referenced by cbegin().
{
   return Iterator<typename Container::iterator>(std::begin(c));
 }
template<class Container > Iterator<typename Container::const_iterator> folly::padded::cbegin (const Container & c)
Given a container to Node, return iterators to the first element in the first Node / one past the last element in the last Node. Note that the last node is assumed to be full; if that's not the case, subtract from end() as appropriate.
Definition at line 319 of file Padded.h.
References begin().
Referenced by begin(), folly::padded::Adaptor< IntNodeVec >::begin(), folly::IOBuf::begin(), folly::IOBuf::cloneOneInto(), folly::basic_fbstring< char >::insert(), folly::basic_fbstring< E, T, A, Storage >::insertImpl(), folly::basic_fbstring< E, T, A, Storage >::insertImplDiscr(), folly::StringKeyedSetBase< Compare, Alloc >::operator=(), folly::StringKeyedMap< Value, Compare, Alloc >::operator=(), folly::F14VectorSet< Key, Hasher, KeyEqual, Alloc >::operator=(), folly::F14VectorMap< Key, Mapped, Hasher, KeyEqual, Alloc >::operator=(), folly::basic_fbstring< char >::shrink_to_fit(), and TEST_F().
{
   return Iterator<typename Container::const_iterator>(std::begin(c));
 }
template<class Container > Iterator<typename Container::const_iterator> folly::padded::cend (const Container & c)
Definition at line 324 of file Padded.h.
References end().
Referenced by folly::IOBuf::cloneOneInto(), folly::small_vector< Observer< T > *, InlineObservers >::emplace(), end(), folly::padded::Adaptor< IntNodeVec >::end(), folly::IOBuf::end(), folly::detail::ConcurrentHashMapSegment< KeyType, ValueType, ShardBits, HashFn, KeyEqual, Allocator, Atom, Mutex >::erase(), folly::basic_fbstring< E, T, A, Storage >::insertImpl(), folly::basic_fbstring< E, T, A, Storage >::insertImplDiscr(), folly::StringKeyedMap< Value, Compare, Alloc >::operator=(), folly::StringKeyedSetBase< Compare, Alloc >::operator=(), folly::F14VectorSet< Key, Hasher, KeyEqual, Alloc >::operator=(), folly::F14VectorMap< Key, Mapped, Hasher, KeyEqual, Alloc >::operator=(), folly::basic_fbstring< char >::shrink_to_fit(), TEST(), and TEST_F().
{
   return Iterator<typename Container::const_iterator>(std::end(c));
 }
template<class Container > Iterator<typename Container::const_iterator> folly::padded::end (const Container & c)
Definition at line 334 of file Padded.h.
References cend().
Referenced by TEST_F().
{
   return cend(c);
 }
template<class Container > Iterator<typename Container::iterator> folly::padded::end (Container & c)
Definition at line 344 of file Padded.h.
Referenced by cend().
{
   return Iterator<typename Container::iterator>(std::end(c));
 }