proxygen: detail Namespace Reference
detail Namespace Reference
Classes
struct FNV64
struct SpookyHashV2
Functions
std::vector< uint8_t > randomBytes (size_t n)
template<class Hasher >
void bmHasher (Hasher hasher, size_t k, size_t iters)
template<class Hasher >
void addHashBenchmark (const std::string &name)
template<typename T >
T * get_pointer (const unique_ptr< T > &ptr)
template<typename T >
T * get_pointer (T *ptr)
Variables
std::vector< uint8_t > benchData = randomBytes(1 << 20)
Function Documentation
template<class Hasher > void detail::addHashBenchmark (const std::string & name)
Definition at line 56 of file HashBenchmark.cpp.
References folly::addBenchmark(), bmHasher(), i, k, and folly::sformat().
{
   static std::deque<std::string> names;
   for (size_t i = 0; i < 16; ++i) {
     auto k = size_t(1) << i;
     names.emplace_back(folly::sformat("{}: k=2^{}", name, i));
     folly::addBenchmark(__FILE__, names.back().c_str(), [=](unsigned iters) {
       Hasher hasher;
       bmHasher(hasher, k, iters);
       return iters;
     });
   }
   /* Draw line. */
   folly::addBenchmark(__FILE__, "-", []() { return 0; });
 }
template<class Hasher > void detail::bmHasher (Hasher hasher, size_t k, size_t iters)
Definition at line 45 of file HashBenchmark.cpp.
References folly::doNotOptimizeAway(), i, and k.
Referenced by addHashBenchmark().
{
   CHECK_LE(k, benchData.size());
   for (size_t i = 0, pos = 0; i < iters; ++i, ++pos) {
     if (pos == benchData.size() - k + 1) {
       pos = 0;
     }
     folly::doNotOptimizeAway(hasher(benchData.data() + pos, k));
   }
 }
template<typename T > T* detail::get_pointer (const unique_ptr< T > & ptr)
Definition at line 29 of file GenericFilterTest.cpp.
Referenced by GenericFilterTest< Owned >::addFilterToChain().
{
   return ptr.get();
 }
template<typename T > T* detail::get_pointer (T * ptr)
Definition at line 34 of file GenericFilterTest.cpp.
References ptr.
{
   return ptr;
 }
std::vector<uint8_t> detail::randomBytes (size_t n)
Definition at line 34 of file HashBenchmark.cpp.
References dist, and rng.
{
   std::vector<uint8_t> ret(n);
   std::default_random_engine rng(1729); // Deterministic seed.
   std::uniform_int_distribution<uint16_t> dist(0, 255);
   std::generate(ret.begin(), ret.end(), [&]() { return dist(rng); });
   return ret;
 }
Variable Documentation
std::vector<uint8_t> detail::benchData = randomBytes(1 << 20)
Definition at line 42 of file HashBenchmark.cpp.