proxygen: folly::chrono Namespace Reference
folly::chrono Namespace Reference
Namespaces
detail
Classes
struct coarse_steady_clock
Functions
template<typename To , typename Rep , typename Period , typename = typename std::enable_if<detail::is_duration<To>::value>::type>
constexpr To ceil (std::chrono::duration< Rep, Period > const &d)
template<typename To , typename Clock , typename Duration , typename = typename std::enable_if<detail::is_duration<To>::value>::type>
constexpr std::chrono::time_point< Clock, To > ceil (std::chrono::time_point< Clock, Duration > const &tp)
template<typename To , typename Rep , typename Period , typename = typename std::enable_if<detail::is_duration<To>::value>::type>
constexpr To floor (std::chrono::duration< Rep, Period > const &d)
template<typename To , typename Clock , typename Duration , typename = typename std::enable_if<detail::is_duration<To>::value>::type>
constexpr std::chrono::time_point< Clock, To > floor (std::chrono::time_point< Clock, Duration > const &tp)
template<typename To , typename Rep , typename Period , typename = typename std::enable_if< detail::is_duration<To>::value && !std::chrono::treat_as_floating_point<typename To::rep>::value>::type>
constexpr To round (std::chrono::duration< Rep, Period > const &d)
template<typename To , typename Clock , typename Duration , typename = typename std::enable_if< detail::is_duration<To>::value && !std::chrono::treat_as_floating_point<typename To::rep>::value>::type>
constexpr std::chrono::time_point< Clock, To > round (std::chrono::time_point< Clock, Duration > const &tp)
static int64_t clock_gettime_ns_fallback (clockid_t clock)
Variables
int(* clock_gettime)(clockid_t, timespec *ts) = &::clock_gettime
int64_t(* clock_gettime_ns)(clockid_t) = &clock_gettime_ns_fallback
Function Documentation
template<typename To , typename Rep , typename Period , typename = typename std::enable_if<detail::is_duration<To>::value>::type> constexpr To folly::chrono::ceil (std::chrono::duration< Rep, Period > const & d)
Definition at line 91 of file Chrono.h.
References folly::chrono::detail::ceil_impl(), type, and value.
Referenced by proxygen::HeaderTable::add().
{
   return detail::ceil_impl(d, std::chrono::duration_cast<To>(d));
 }
template<typename To , typename Clock , typename Duration , typename = typename std::enable_if<detail::is_duration<To>::value>::type> constexpr std::chrono::time_point<Clock, To> folly::chrono::ceil (std::chrono::time_point< Clock, Duration > const & tp)
Definition at line 102 of file Chrono.h.
References type, and value.
{
   return std::chrono::time_point<Clock, To>{ceil<To>(tp.time_since_epoch())};
 }
static int64_t folly::chrono::clock_gettime_ns_fallback (clockid_t clock) static
Definition at line 33 of file ClockGettimeWrappers.cpp.
References clock_gettime, and UNLIKELY.
{
   struct timespec ts;
   int r = clock_gettime(clock, &ts);
   if (UNLIKELY(r != 0)) {
     // Mimic what __clock_gettime_ns does (even though this can be a legit
     // value).
     return -1;
   }
   std::chrono::nanoseconds result =
       std::chrono::seconds(ts.tv_sec) + std::chrono::nanoseconds(ts.tv_nsec);
   return result.count();
 }
template<typename To , typename Rep , typename Period , typename = typename std::enable_if<detail::is_duration<To>::value>::type> constexpr To folly::chrono::floor (std::chrono::duration< Rep, Period > const & d)
Definition at line 114 of file Chrono.h.
References folly::chrono::detail::floor_impl(), type, and value.
Referenced by fizz::test::chunkIOBuf().
{
   return detail::floor_impl(d, std::chrono::duration_cast<To>(d));
 }
template<typename To , typename Clock , typename Duration , typename = typename std::enable_if<detail::is_duration<To>::value>::type> constexpr std::chrono::time_point<Clock, To> folly::chrono::floor (std::chrono::time_point< Clock, Duration > const & tp)
Definition at line 125 of file Chrono.h.
References type, and value.
{
   return std::chrono::time_point<Clock, To>{floor<To>(tp.time_since_epoch())};
 }
template<typename To , typename Rep , typename Period , typename = typename std::enable_if< detail::is_duration<To>::value && !std::chrono::treat_as_floating_point<typename To::rep>::value>::type> constexpr To folly::chrono::round (std::chrono::duration< Rep, Period > const & d)
Definition at line 139 of file Chrono.h.
References folly::chrono::detail::round_impl(), type, and value.
Referenced by folly::constexpr_ceil(), fizz::HkdfImpl< Hash >::expand(), Run(), folly::TEST(), and TEST_F().
{
   return detail::round_impl(d, floor<To>(d));
 }
template<typename To , typename Clock , typename Duration , typename = typename std::enable_if< detail::is_duration<To>::value && !std::chrono::treat_as_floating_point<typename To::rep>::value>::type> constexpr std::chrono::time_point<Clock, To> folly::chrono::round (std::chrono::time_point< Clock, Duration > const & tp)
Definition at line 152 of file Chrono.h.
References chrono.
{
   return std::chrono::time_point<Clock, To>{round<To>(tp.time_since_epoch())};
 }
Variable Documentation
int(* folly::chrono::clock_gettime)(clockid_t, timespec *ts) = &::clock_gettime
Definition at line 48 of file ClockGettimeWrappers.cpp.
Referenced by clock_gettime_ns_fallback(), duration_to_ts(), GetClockTickCount(), folly::chrono::coarse_steady_clock::now(), run_steady_clock_test(), and run_system_clock_test().
int64_t(* folly::chrono::clock_gettime_ns)(clockid_t) = &clock_gettime_ns_fallback
Definition at line 49 of file ClockGettimeWrappers.cpp.