proxygen: gtest_output_test Namespace Reference
gtest_output_test Namespace Reference
Classes
class GTestOutputTest
Functions
def ToUnixLineEnding (s)
def RemoveLocations (test_output)
def RemoveStackTraceDetails (output)
def RemoveStackTraces (output)
def RemoveTime (output)
def RemoveTypeInfoDetails (test_output)
def NormalizeToCurrentPlatform (test_output)
def RemoveTestCounts (output)
def RemoveMatchingTests (test_output, pattern)
def NormalizeOutput (output)
def GetShellCommandOutput (env_cmd)
def GetCommandOutput (env_cmd)
def GetOutputOfAllCommands ()
Variables
string __author__ = 'wan@google.com (Zhanyong Wan)'
string GENGOLDEN_FLAG = '--gengolden'
string CATCH_EXCEPTIONS_ENV_VAR_NAME = 'GTEST_CATCH_EXCEPTIONS'
string IS_WINDOWS = 'nt'
string GOLDEN_NAME = 'gtest_output_test_golden_lin.txt'
PROGRAM_PATH = gtest_test_utils.GetTestExecutablePath('gtest_output_test_')
tuple COMMAND_LIST_TESTS = ({}, [PROGRAM_PATH, '--gtest_list_tests'])
tuple COMMAND_WITH_COLOR = ({}, [PROGRAM_PATH, '--gtest_color=yes'])
tuple COMMAND_WITH_TIME
tuple COMMAND_WITH_DISABLED
tuple COMMAND_WITH_SHARDING
GOLDEN_PATH = os.path.join(gtest_test_utils.GetSourceDir(), GOLDEN_NAME)
test_list = GetShellCommandOutput(COMMAND_LIST_TESTS)
string SUPPORTS_DEATH_TESTS = 'DeathTest'
string SUPPORTS_TYPED_TESTS = 'TypedTest'
string SUPPORTS_THREADS = 'ExpectFailureWithThreadsTest'
bool SUPPORTS_STACK_TRACES = False
tuple CAN_GENERATE_GOLDEN_FILE
output = GetOutputOfAllCommands()
golden_file = open(GOLDEN_PATH, 'wb')
tuple message
Function Documentation
def gtest_output_test.GetCommandOutput (env_cmd)
Runs a command and returns its output with all file location
info stripped off.
Args:
  env_cmd:  The shell command. A 2-tuple where element 0 is a dict of extra
            environment variables to set, and element 1 is a string with
            the command and any flags.
Definition at line 222 of file gtest_output_test.py.
References GetShellCommandOutput(), and NormalizeOutput().
Referenced by GetOutputOfAllCommands().
 def GetCommandOutput(env_cmd):
   """Runs a command and returns its output with all file location
   info stripped off.
   Args:
     env_cmd:  The shell command. A 2-tuple where element 0 is a dict of extra
               environment variables to set, and element 1 is a string with
               the command and any flags.
   """
   # Disables exception pop-ups on Windows.
   environ, cmdline = env_cmd
   environ = dict(environ)  # Ensures we are modifying a copy.
   environ[CATCH_EXCEPTIONS_ENV_VAR_NAME] = '1'
   return NormalizeOutput(GetShellCommandOutput((environ, cmdline)))
def gtest_output_test.GetOutputOfAllCommands ()
Returns concatenated output from several representative commands.
Definition at line 239 of file gtest_output_test.py.
References GetCommandOutput().
Referenced by gtest_output_test.GTestOutputTest.testOutput().
 def GetOutputOfAllCommands():
   """Returns concatenated output from several representative commands."""
   return (GetCommandOutput(COMMAND_WITH_COLOR) +
           GetCommandOutput(COMMAND_WITH_TIME) +
           GetCommandOutput(COMMAND_WITH_DISABLED) +
           GetCommandOutput(COMMAND_WITH_SHARDING))
def gtest_output_test.GetShellCommandOutput (env_cmd)
Runs a command in a sub-process, and returns its output in a string.
Args:
  env_cmd: The shell command. A 2-tuple where element 0 is a dict of extra
           environment variables to set, and element 1 is a string with
           the command and any flags.
Returns:
  A string with the command's combined standard and diagnostic output.
Definition at line 201 of file gtest_output_test.py.
Referenced by GetCommandOutput().
 def GetShellCommandOutput(env_cmd):
   """Runs a command in a sub-process, and returns its output in a string.
   Args:
     env_cmd: The shell command. A 2-tuple where element 0 is a dict of extra
              environment variables to set, and element 1 is a string with
              the command and any flags.
   Returns:
     A string with the command's combined standard and diagnostic output.
   """
   # Spawns cmd in a sub-process, and gets its standard I/O file objects.
   # Set and save the environment properly.
   environ = os.environ.copy()
   environ.update(env_cmd[0])
   p = gtest_test_utils.Subprocess(env_cmd[1], env=environ)
   return p.output
def gtest_output_test.NormalizeOutput (output)
Normalizes output (the output of gtest_output_test_.exe).
Definition at line 191 of file gtest_output_test.py.
References RemoveLocations(), RemoveStackTraceDetails(), RemoveTime(), and ToUnixLineEnding().
Referenced by GetCommandOutput().
 def NormalizeOutput(output):
   """Normalizes output (the output of gtest_output_test_.exe)."""
   output = ToUnixLineEnding(output)
   output = RemoveLocations(output)
   output = RemoveStackTraceDetails(output)
   output = RemoveTime(output)
   return output
def gtest_output_test.NormalizeToCurrentPlatform (test_output)
Normalizes platform specific output details for easier comparison.
Definition at line 140 of file gtest_output_test.py.
Referenced by gtest_output_test.GTestOutputTest.testOutput().
 def NormalizeToCurrentPlatform(test_output):
   """Normalizes platform specific output details for easier comparison."""
   if IS_WINDOWS:
     # Removes the color information that is not present on Windows.
     test_output = re.sub('\x1b\\[(0;3\d)?m', '', test_output)
     # Changes failure message headers into the Windows format.
     test_output = re.sub(r': Failure\n', r': error: ', test_output)
     # Changes file(line_number) to file:line_number.
     test_output = re.sub(r'((\w|\.)+)\((\d+)\):', r'\1:\3:', test_output)
   return test_output
def gtest_output_test.RemoveLocations (test_output)
Removes all file location info from a Google Test program's output.
Args:
     test_output:  the output of a Google Test program.
Returns:
     output with all file location info (in the form of
     'DIRECTORY/FILE_NAME:LINE_NUMBER: 'or
     'DIRECTORY\\FILE_NAME(LINE_NUMBER): ') replaced by
     'FILE_NAME:#: '.
Definition at line 89 of file gtest_output_test.py.
Referenced by NormalizeOutput().
 def RemoveLocations(test_output):
   """Removes all file location info from a Google Test program's output.
   Args:
        test_output:  the output of a Google Test program.
   Returns:
        output with all file location info (in the form of
        'DIRECTORY/FILE_NAME:LINE_NUMBER: 'or
        'DIRECTORY\\FILE_NAME(LINE_NUMBER): ') replaced by
        'FILE_NAME:#: '.
   """
   return re.sub(r'.*[/\\](.+)(\:\d+|\(\d+\))\: ', r'\1:#: ', test_output)
def gtest_output_test.RemoveMatchingTests (test_output, pattern)
Removes output of specified tests from a Google Test program's output.
This function strips not only the beginning and the end of a test but also
all output in between.
Args:
  test_output:       A string containing the test output.
  pattern:           A regex string that matches names of test cases or
                     tests to remove.
Returns:
  Contents of test_output with tests whose names match pattern removed.
Definition at line 168 of file gtest_output_test.py.
Referenced by gtest_output_test.GTestOutputTest.RemoveUnsupportedTests().
 def RemoveMatchingTests(test_output, pattern):
   """Removes output of specified tests from a Google Test program's output.
   This function strips not only the beginning and the end of a test but also
   all output in between.
   Args:
     test_output:       A string containing the test output.
     pattern:           A regex string that matches names of test cases or
                        tests to remove.
   Returns:
     Contents of test_output with tests whose names match pattern removed.
   """
   test_output = re.sub(
       r'.*\[ RUN      \] .*%s(.|\n)*?\[(  FAILED  |       OK )\] .*%s.*\n' % (
           pattern, pattern),
       '',
       test_output)
   return re.sub(r'.*%s.*\n' % pattern, '', test_output)
def gtest_output_test.RemoveStackTraceDetails (output)
Removes all stack traces from a Google Test program's output.
Definition at line 105 of file gtest_output_test.py.
Referenced by NormalizeOutput().
 def RemoveStackTraceDetails(output):
   """Removes all stack traces from a Google Test program's output."""
   # *? means "find the shortest string that matches".
   return re.sub(r'Stack trace:(.|\n)*?\n\n',
                 'Stack trace: (omitted)\n\n', output)
def gtest_output_test.RemoveStackTraces (output)
Removes all traces of stack traces from a Google Test program's output.
Definition at line 113 of file gtest_output_test.py.
Referenced by gtest_output_test.GTestOutputTest.RemoveUnsupportedTests().
 def RemoveStackTraces(output):
   """Removes all traces of stack traces from a Google Test program's output."""
   # *? means "find the shortest string that matches".
   return re.sub(r'Stack trace:(.|\n)*?\n\n', '', output)
def gtest_output_test.RemoveTestCounts (output)
Removes test counts from a Google Test program's output.
Definition at line 154 of file gtest_output_test.py.
Referenced by gtest_output_test.GTestOutputTest.testOutput().
 def RemoveTestCounts(output):
   """Removes test counts from a Google Test program's output."""
   output = re.sub(r'\d+ tests?, listed below',
                   '? tests, listed below', output)
   output = re.sub(r'\d+ FAILED TESTS',
                   '? FAILED TESTS', output)
   output = re.sub(r'\d+ tests? from \d+ test cases?',
                   '? tests from ? test cases', output)
   output = re.sub(r'\d+ tests? from ([a-zA-Z_])',
                   r'? tests from \1', output)
   return re.sub(r'\d+ tests?\.', '? tests.', output)
def gtest_output_test.RemoveTime (output)
Removes all time information from a Google Test program's output.
Definition at line 120 of file gtest_output_test.py.
Referenced by NormalizeOutput().
 def RemoveTime(output):
   """Removes all time information from a Google Test program's output."""
   return re.sub(r'\(\d+ ms', '(? ms', output)
def gtest_output_test.RemoveTypeInfoDetails (test_output)
Removes compiler-specific type info from Google Test program's output.
Args:
     test_output:  the output of a Google Test program.
Returns:
     output with type information normalized to canonical form.
Definition at line 126 of file gtest_output_test.py.
Referenced by gtest_output_test.GTestOutputTest.testOutput().
 def RemoveTypeInfoDetails(test_output):
   """Removes compiler-specific type info from Google Test program's output.
   Args:
        test_output:  the output of a Google Test program.
   Returns:
        output with type information normalized to canonical form.
   """
   # some compilers output the name of type 'unsigned int' as 'unsigned'
   return re.sub(r'unsigned int', 'unsigned', test_output)
def gtest_output_test.ToUnixLineEnding (s)
Changes all Windows/Mac line endings in s to UNIX line endings.
Definition at line 83 of file gtest_output_test.py.
References replace().
Referenced by NormalizeOutput(), and gtest_output_test.GTestOutputTest.testOutput().
 def ToUnixLineEnding(s):
   """Changes all Windows/Mac line endings in s to UNIX line endings."""
   return s.replace('\r\n', '\n').replace('\r', '\n')
Variable Documentation
string gtest_output_test.__author__ = 'wan@google.com (Zhanyong Wan)' private
Definition at line 41 of file gtest_output_test.py.
tuple gtest_output_test.CAN_GENERATE_GOLDEN_FILE
Initial value:
 = (SUPPORTS_DEATH_TESTS and
                             SUPPORTS_TYPED_TESTS and
                             SUPPORTS_THREADS and
                             not IS_WINDOWS)
Definition at line 254 of file gtest_output_test.py.
string gtest_output_test.CATCH_EXCEPTIONS_ENV_VAR_NAME = 'GTEST_CATCH_EXCEPTIONS'
Definition at line 52 of file gtest_output_test.py.
tuple gtest_output_test.COMMAND_LIST_TESTS = ({}, [PROGRAM_PATH, '--gtest_list_tests'])
Definition at line 63 of file gtest_output_test.py.
tuple gtest_output_test.COMMAND_WITH_COLOR = ({}, [PROGRAM_PATH, '--gtest_color=yes'])
Definition at line 64 of file gtest_output_test.py.
tuple gtest_output_test.COMMAND_WITH_DISABLED
Initial value:
 = (
     {}, [PROGRAM_PATH,
          '--gtest_also_run_disabled_tests',
          'internal_skip_environment_and_ad_hoc_tests',
          '--gtest_filter=*DISABLED_*'])
Definition at line 69 of file gtest_output_test.py.
tuple gtest_output_test.COMMAND_WITH_SHARDING
Initial value:
 = (
     {'GTEST_SHARD_INDEX': '1', 'GTEST_TOTAL_SHARDS': '2'},
     [PROGRAM_PATH,
      'internal_skip_environment_and_ad_hoc_tests',
      '--gtest_filter=PassingTest.*'])
Definition at line 74 of file gtest_output_test.py.
tuple gtest_output_test.COMMAND_WITH_TIME
Initial value:
 = ({}, [PROGRAM_PATH,
                           '--gtest_print_time',
                           'internal_skip_environment_and_ad_hoc_tests',
                           '--gtest_filter=FatalFailureTest.*:LoggingTest.*'])
Definition at line 65 of file gtest_output_test.py.
string gtest_output_test.GENGOLDEN_FLAG = '--gengolden'
Definition at line 51 of file gtest_output_test.py.
gtest_output_test.golden_file = open(GOLDEN_PATH, 'wb')
Definition at line 327 of file gtest_output_test.py.
string gtest_output_test.GOLDEN_NAME = 'gtest_output_test_golden_lin.txt'
Definition at line 57 of file gtest_output_test.py.
gtest_output_test.GOLDEN_PATH = os.path.join(gtest_test_utils.GetSourceDir(), GOLDEN_NAME)
Definition at line 80 of file gtest_output_test.py.
string gtest_output_test.IS_WINDOWS = 'nt'
Definition at line 54 of file gtest_output_test.py.
tuple gtest_output_test.message
Initial value:
 = (
           )
Definition at line 331 of file gtest_output_test.py.
gtest_output_test.output = GetOutputOfAllCommands()
Definition at line 326 of file gtest_output_test.py.
gtest_output_test.PROGRAM_PATH = gtest_test_utils.GetTestExecutablePath('gtest_output_test_')
Definition at line 59 of file gtest_output_test.py.
string gtest_output_test.SUPPORTS_DEATH_TESTS = 'DeathTest'
Definition at line 249 of file gtest_output_test.py.
bool gtest_output_test.SUPPORTS_STACK_TRACES = False
Definition at line 252 of file gtest_output_test.py.
string gtest_output_test.SUPPORTS_THREADS = 'ExpectFailureWithThreadsTest'
Definition at line 251 of file gtest_output_test.py.
string gtest_output_test.SUPPORTS_TYPED_TESTS = 'TypedTest'
Definition at line 250 of file gtest_output_test.py.
gtest_output_test.test_list = GetShellCommandOutput(COMMAND_LIST_TESTS)
Definition at line 248 of file gtest_output_test.py.