proxygen: my Namespace Reference
my Namespace Reference
Classes
struct ColorError
struct Dimensions
Enumerations
enum SmallEnum
enum Color { Color::Red, Color::Blue }
enum ColorErrorCode { ColorErrorCode::INVALID_COLOR }
Functions
Expected< StringPiece, ConversionCode > parseTo (folly::StringPiece in, Dimensions &out)
template<class String >
void toAppend (const Dimensions &in, String *result)
size_t estimateSpaceNeeded (const Dimensions &in)
Expected< StringPiece, ConversionCode > parseTo (StringPiece in, SmallEnum &out)
template<class String >
void toAppend (SmallEnum, String *result)
ColorError makeConversionError (ColorErrorCode, StringPiece sp)
Expected< StringPiece, ColorErrorCode > parseTo (StringPiece in, Color &out) noexcept
Enumeration Type Documentation
enum my::Color strong
Enumerator
Red
Blue
Definition at line 980 of file StringTest.cpp.
                  {
   Red,
   Blue,
 };
enum my::ColorErrorCode strong
Enumerator
INVALID_COLOR
Definition at line 985 of file StringTest.cpp.
 { INVALID_COLOR };
enum my::SmallEnum strong
Definition at line 1248 of file ConvTest.cpp.
 {};
Function Documentation
size_t my::estimateSpaceNeeded (const Dimensions & in)
Definition at line 1243 of file ConvTest.cpp.
References folly::estimateSpaceNeeded(), my::Dimensions::h, and my::Dimensions::w.
{
   return 2000 + folly::estimateSpaceNeeded(in.w) +
       folly::estimateSpaceNeeded(in.h);
 }
ColorError my::makeConversionError (ColorErrorCode , StringPiece sp)
Definition at line 991 of file StringTest.cpp.
References folly::Range< Iter >::str().
{
   return ColorError("Invalid my::Color representation : " + sp.str());
 }
Expected<StringPiece, ColorErrorCode> my::parseTo (StringPiece in, Color & out) noexcept
Definition at line 995 of file StringTest.cpp.
References folly::makeUnexpected().
{
   if (in == "R") {
     out = Color::Red;
   } else if (in == "B") {
     out = Color::Blue;
   } else {
     return makeUnexpected(ColorErrorCode::INVALID_COLOR);
   }
   return StringPiece(in.end(), in.end());
 }
Expected<StringPiece, ConversionCode> my::parseTo (folly::StringPiece in, Dimensions & out)
Definition at line 1230 of file ConvTest.cpp.
References my::Dimensions::h, parseTo(), folly::Range< Iter >::removePrefix(), and my::Dimensions::w.
                      {
   return parseTo(in, out.w)
       .then([](StringPiece sp) { return sp.removePrefix("x"), sp; })
       .then([&](StringPiece sp) { return parseTo(sp, out.h); });
 }
Expected<StringPiece, ConversionCode> my::parseTo (StringPiece in, SmallEnum & out)
Definition at line 1250 of file ConvTest.cpp.
References folly::makeUnexpected(), and folly::Range< Iter >::removePrefix().
Referenced by parseTo(), and TEST().
{
   out = {};
   if (in == "SmallEnum") {
     return in.removePrefix(in), in;
   } else {
     return makeUnexpected(ConversionCode::STRING_TO_FLOAT_ERROR);
   }
 }
template<class String > void my::toAppend (const Dimensions & in, String * result)
Definition at line 1239 of file ConvTest.cpp.
References my::Dimensions::h, folly::toAppend(), and my::Dimensions::w.
{
   folly::toAppend(in.w, 'x', in.h, result);
 }
template<class String > void my::toAppend (SmallEnum , String * result)
Definition at line 1260 of file ConvTest.cpp.
References folly::toAppend().
Referenced by TEST(), and testVariadicTo().
{
   folly::toAppend("SmallEnum", result);
 }