proxygen: testing::internal::posix Namespace Reference
testing::internal::posix Namespace Reference
Typedefs
typedef struct stat StatStruct
Functions
int FileNo (FILE *file)
int IsATTY (int fd)
int Stat (const char *path, StatStruct *buf)
int StrCaseCmp (const char *s1, const char *s2)
char * StrDup (const char *src)
int RmDir (const char *dir)
bool IsDir (const StatStruct &st)
const char * StrNCpy (char *dest, const char *src, size_t n)
int ChDir (const char *dir)
FILE * FOpen (const char *path, const char *mode)
FILE * FReopen (const char *path, const char *mode, FILE *stream)
FILE * FDOpen (int fd, const char *mode)
int FClose (FILE *fp)
int Read (int fd, void *buf, unsigned int count)
int Write (int fd, const void *buf, unsigned int count)
int Close (int fd)
const char * StrError (int errnum)
const char * GetEnv (const char *name)
void Abort ()
Typedef Documentation
typedef struct stat testing::internal::posix::StatStruct
Definition at line 2338 of file gtest-port.h.
Function Documentation
void testing::internal::posix::Abort () inline
Definition at line 2410 of file gtest-port.h.
Referenced by testing::internal::CodeLocation::CodeLocation(), GetEnv(), testing::TestPartResultArray::GetTestPartResult(), testing::TestResult::GetTestPartResult(), testing::TestResult::GetTestProperty(), testing::internal::PropertyMatcher< Class, PropertyType >::MatchAndExplainImpl(), testing::internal::ReadEntireFile(), testing::internal::GoogleTestFailureReporter::ReportFailure(), and testing::internal::GTestLog::~GTestLog().
 { abort(); }
int testing::internal::posix::ChDir (const char * dir) inline
Definition at line 2365 of file gtest-port.h.
 { return chdir(dir); }
int testing::internal::posix::Close (int fd) inline
Definition at line 2384 of file gtest-port.h.
References folly::netops::close().
 { return close(fd); }
int testing::internal::posix::FClose (FILE * fp) inline
Definition at line 2376 of file gtest-port.h.
Referenced by testing::internal::ParseGoogleTestFlag(), and testing::internal::GTestLog::~GTestLog().
 { return fclose(fp); }
FILE * testing::internal::posix::FDOpen (int fd, const char * mode) inline
Definition at line 2374 of file gtest-port.h.
 { return fdopen(fd, mode); }
int testing::internal::posix::FileNo (FILE * file) inline
Definition at line 2340 of file gtest-port.h.
Referenced by testing::internal::ColoredPrintf().
 { return fileno(file); }
FILE * testing::internal::posix::FOpen (const char * path, const char * mode) inline
Definition at line 2367 of file gtest-port.h.
Referenced by testing::internal::XmlUnitTestResultPrinter::EscapeXmlText(), testing::internal::XmlUnitTestResultPrinter::OnTestIterationEnd(), testing::internal::ParseGoogleTestFlag(), testing::internal::ScopedPrematureExitFile::ScopedPrematureExitFile(), testing::internal::TearDownEnvironment(), testing::TEST_F(), testing::internal::WriteToShardStatusFileIfNeeded(), and testing::internal::GTestLog::~GTestLog().
{
   return fopen(path, mode);
 }
FILE * testing::internal::posix::FReopen (const char * path, const char * mode, FILE * stream) inline
Definition at line 2371 of file gtest-port.h.
Referenced by main().
{
   return freopen(path, mode, stream);
 }
const char * testing::internal::posix::GetEnv (const char * name) inline
Definition at line 2387 of file gtest-port.h.
References Abort(), GTEST_DISABLE_MSC_WARNINGS_POP_, and name.
Referenced by testing::internal::BoolFromGTestEnv(), testing::internal::FlagToEnvVar(), testing::internal::Int32FromEnvOrDie(), testing::internal::Int32FromGTestEnv(), main(), testing::internal::PrettyUnitTestResultPrinter::OnTestIterationStart(), testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd(), testing::UnitTest::Run(), testing::internal::ShouldUseColor(), testing::internal::StringFromGTestEnv(), testing::internal::TearDownEnvironment(), testing::internal::TempDir(), testing::internal::WriteToShardStatusFileIfNeeded(), and testing::internal::ScopedPrematureExitFile::~ScopedPrematureExitFile().
{
 #if GTEST_OS_WINDOWS_MOBILE || GTEST_OS_WINDOWS_PHONE | GTEST_OS_WINDOWS_RT
   // We are on Windows CE, which has no environment variables.
   static_cast<void>(name);  // To prevent 'unused argument' warning.
   return NULL;
 #elif defined(__BORLANDC__) || defined(__SunOS_5_8) || defined(__SunOS_5_9)
   // Environment variables which we programmatically clear will be set to the
   // empty string rather than unset (NULL).  Handle that case.
   const char* const env = getenv(name);
   return (env != NULL && env[0] != '\0') ? env : NULL;
 #else
   return getenv(name);
 #endif
 }
int testing::internal::posix::IsATTY (int fd) inline
Definition at line 2341 of file gtest-port.h.
Referenced by testing::internal::ColoredPrintf().
 { return isatty(fd); }
bool testing::internal::posix::IsDir (const StatStruct & st) inline
Definition at line 2348 of file gtest-port.h.
References GTEST_DISABLE_MSC_WARNINGS_PUSH_.
Referenced by testing::internal::FilePath::DirectoryExists(), and testing::internal::IsPathSeparator().
 { return S_ISDIR(st.st_mode); }
int testing::internal::posix::Read (int fd, void * buf, unsigned int count) inline
Definition at line 2378 of file gtest-port.h.
References fizz::detail::read().
{
   return static_cast<int>(read(fd, buf, count));
 }
int testing::internal::posix::RmDir (const char * dir) inline
Definition at line 2347 of file gtest-port.h.
Referenced by testing::TEST_F().
 { return rmdir(dir); }
int testing::internal::posix::Stat (const char * path, StatStruct * buf) inline
Definition at line 2342 of file gtest-port.h.
Referenced by testing::internal::FilePath::DirectoryExists(), testing::internal::FilePath::FileOrDirectoryExists(), and testing::internal::IsPathSeparator().
 { return stat(path, buf); }
int testing::internal::posix::StrCaseCmp (const char * s1, const char * s2) inline
Definition at line 2343 of file gtest-port.h.
Referenced by testing::internal::String::CaseInsensitiveCStringEquals().
{
   return strcasecmp(s1, s2);
 }
char * testing::internal::posix::StrDup (const char * src) inline
Definition at line 2346 of file gtest-port.h.
Referenced by testing::internal::GetThreadCount().
 { return strdup(src); }
const char * testing::internal::posix::StrError (int errnum) inline
Definition at line 2385 of file gtest-port.h.
 { return strerror(errnum); }
const char * testing::internal::posix::StrNCpy (char * dest, const char * src, size_t n) inline
Definition at line 2356 of file gtest-port.h.
{
   return strncpy(dest, src, n);
 }
int testing::internal::posix::Write (int fd, const void * buf, unsigned int count) inline
Definition at line 2381 of file gtest-port.h.
References fizz::detail::write().
{
   return static_cast<int>(write(fd, buf, count));
 }