proxygen: cpp.keywords Namespace Reference
cpp.keywords Namespace Reference
Functions
def IsKeyword (token)
def IsBuiltinType (token)
Variables
string __author__ = 'nnorwitz@google.com (Neal Norwitz)'
TYPES = set('bool char int long short double float void wchar_t unsigned signed'.split())
TYPE_MODIFIERS = set('auto register const inline extern static virtual volatile mutable'.split())
ACCESS = set('public protected private friend'.split())
CASTS = set('static_cast const_cast dynamic_cast reinterpret_cast'.split())
OTHERS = set('true false asm class namespace using explicit this operator sizeof'.split())
OTHER_TYPES = set('new delete typedef struct union enum typeid typename template'.split())
CONTROL = set('case switch default if else return goto'.split())
EXCEPTION = set('try catch throw'.split())
LOOP = set('while do for break continue'.split())
ALL = TYPES|TYPE_MODIFIERS|ACCESS|CASTS|OTHERS|OTHER_TYPES|CONTROL|EXCEPTION|LOOP
Function Documentation
def cpp.keywords.IsBuiltinType (token)
Definition at line 55 of file keywords.py.
 def IsBuiltinType(token):
     if token in ('virtual', 'inline'):
         # These only apply to methods, they can't be types by themselves.
         return False
     return token in TYPES or token in TYPE_MODIFIERS
def cpp.keywords.IsKeyword (token)
Definition at line 52 of file keywords.py.
 def IsKeyword(token):
     return token in ALL
Variable Documentation
string cpp.keywords.__author__ = 'nnorwitz@google.com (Neal Norwitz)' private
Definition at line 20 of file keywords.py.
cpp.keywords.ACCESS = set('public protected private friend'.split())
Definition at line 38 of file keywords.py.
cpp.keywords.ALL = TYPES|TYPE_MODIFIERS|ACCESS|CASTS|OTHERS|OTHER_TYPES|CONTROL|EXCEPTION|LOOP
Definition at line 49 of file keywords.py.
cpp.keywords.CASTS = set('static_cast const_cast dynamic_cast reinterpret_cast'.split())
Definition at line 40 of file keywords.py.
cpp.keywords.CONTROL = set('case switch default if else return goto'.split())
Definition at line 45 of file keywords.py.
cpp.keywords.EXCEPTION = set('try catch throw'.split())
Definition at line 46 of file keywords.py.
Referenced by folly::Try< T >.destroy(), folly::Try< T >.emplaceException(), folly::Try< folly::folly::Unit >.hasException(), folly::Try< T >.operator=(), folly::Try< T >.throwIfFailed(), folly::Try< T >.Try(), and folly::Try< T >.~Try().
cpp.keywords.LOOP = set('while do for break continue'.split())
Definition at line 47 of file keywords.py.
cpp.keywords.OTHER_TYPES = set('new delete typedef struct union enum typeid typename template'.split())
Definition at line 43 of file keywords.py.
cpp.keywords.OTHERS = set('true false asm class namespace using explicit this operator sizeof'.split())
Definition at line 42 of file keywords.py.
cpp.keywords.TYPE_MODIFIERS = set('auto register const inline extern static virtual volatile mutable'.split())
Definition at line 37 of file keywords.py.
cpp.keywords.TYPES = set('bool char int long short double float void wchar_t unsigned signed'.split())
Definition at line 36 of file keywords.py.