proxygen: folly::jsonschema Namespace Reference
folly::jsonschema Namespace Reference
Classes
struct Validator
Functions
std::unique_ptr< Validator > makeValidator (const dynamic &schema)
std::shared_ptr< Validator > makeSchemaValidator ()
Function Documentation
std::shared_ptr< Validator > folly::jsonschema::makeSchemaValidator ()
Makes a validator for schemas. You should probably check your schema with this before you use makeValidator().
Definition at line 1037 of file JSONSchema.cpp.
Referenced by check(), and TEST().
{
   return schemaValidator.try_get();
 }
std::unique_ptr< Validator > folly::jsonschema::makeValidator (const dynamic & schema)
Make a validator that can be used to check various json. Thread-safe.
Definition at line 1029 of file JSONSchema.cpp.
References context, and folly::gen::move.
Referenced by check(), main(), and TEST().
{
   auto v = std::make_unique<SchemaValidator>();
   SchemaValidatorContext context(schema);
   context.refs["#"] = v.get();
   v->loadSchema(context, schema);
   return std::move(v);
 }