proxygen: testing::internal::invoke_argument Namespace Reference
testing::internal::invoke_argument Namespace Reference
Classes
struct AdlTag
Functions
template<typename R , typename F >
R InvokeArgumentAdl (AdlTag, F f)
template<typename R , typename F , typename A1 >
R InvokeArgumentAdl (AdlTag, F f, A1 a1)
template<typename R , typename F , typename A1 , typename A2 >
R InvokeArgumentAdl (AdlTag, F f, A1 a1, A2 a2)
template<typename R , typename F , typename A1 , typename A2 , typename A3 >
R InvokeArgumentAdl (AdlTag, F f, A1 a1, A2 a2, A3 a3)
template<typename R , typename F , typename A1 , typename A2 , typename A3 , typename A4 >
R InvokeArgumentAdl (AdlTag, F f, A1 a1, A2 a2, A3 a3, A4 a4)
template<typename R , typename F , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 >
R InvokeArgumentAdl (AdlTag, F f, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5)
template<typename R , typename F , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 >
R InvokeArgumentAdl (AdlTag, F f, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6)
template<typename R , typename F , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 >
R InvokeArgumentAdl (AdlTag, F f, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7)
template<typename R , typename F , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 >
R InvokeArgumentAdl (AdlTag, F f, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8)
template<typename R , typename F , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 >
R InvokeArgumentAdl (AdlTag, F f, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9)
template<typename R , typename F , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 , typename A10 >
R InvokeArgumentAdl (AdlTag, F f, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9, A10 a10)
Function Documentation
template<typename R , typename F > R testing::internal::invoke_argument::InvokeArgumentAdl (AdlTag , F f)
Definition at line 2137 of file gmock-generated-actions.h.
References f.
Referenced by testing::GTEST_CONCAT_TOKEN_(), and testing::InvokeArgument().
{
   return f();
 }
template<typename R , typename F , typename A1 > R testing::internal::invoke_argument::InvokeArgumentAdl (AdlTag , F f, A1 a1)
Definition at line 2141 of file gmock-generated-actions.h.
References f.
{
   return f(a1);
 }
template<typename R , typename F , typename A1 , typename A2 > R testing::internal::invoke_argument::InvokeArgumentAdl (AdlTag , F f, A1 a1, A2 a2)
Definition at line 2145 of file gmock-generated-actions.h.
References f.
{
   return f(a1, a2);
 }
template<typename R , typename F , typename A1 , typename A2 , typename A3 > R testing::internal::invoke_argument::InvokeArgumentAdl (AdlTag , F f, A1 a1, A2 a2, A3 a3)
Definition at line 2149 of file gmock-generated-actions.h.
References f.
{
   return f(a1, a2, a3);
 }
template<typename R , typename F , typename A1 , typename A2 , typename A3 , typename A4 > R testing::internal::invoke_argument::InvokeArgumentAdl (AdlTag , F f, A1 a1, A2 a2, A3 a3, A4 a4)
Definition at line 2154 of file gmock-generated-actions.h.
References f.
{
   return f(a1, a2, a3, a4);
 }
template<typename R , typename F , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 > R testing::internal::invoke_argument::InvokeArgumentAdl (AdlTag , F f, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5)
Definition at line 2159 of file gmock-generated-actions.h.
References f.
{
   return f(a1, a2, a3, a4, a5);
 }
template<typename R , typename F , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 > R testing::internal::invoke_argument::InvokeArgumentAdl (AdlTag , F f, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6)
Definition at line 2164 of file gmock-generated-actions.h.
References f.
{
   return f(a1, a2, a3, a4, a5, a6);
 }
template<typename R , typename F , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 > R testing::internal::invoke_argument::InvokeArgumentAdl (AdlTag , F f, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7)
Definition at line 2169 of file gmock-generated-actions.h.
References f.
            {
   return f(a1, a2, a3, a4, a5, a6, a7);
 }
template<typename R , typename F , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 > R testing::internal::invoke_argument::InvokeArgumentAdl (AdlTag , F f, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8)
Definition at line 2175 of file gmock-generated-actions.h.
References f.
                   {
   return f(a1, a2, a3, a4, a5, a6, a7, a8);
 }
template<typename R , typename F , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 > R testing::internal::invoke_argument::InvokeArgumentAdl (AdlTag , F f, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9)
Definition at line 2182 of file gmock-generated-actions.h.
References f.
{
   return f(a1, a2, a3, a4, a5, a6, a7, a8, a9);
 }
template<typename R , typename F , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 , typename A10 > R testing::internal::invoke_argument::InvokeArgumentAdl (AdlTag , F f, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9, A10 a10)
Definition at line 2189 of file gmock-generated-actions.h.
References testing::ACTION_TEMPLATE(), f, testing::InvokeArgument(), and k.
{
   return f(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10);
 }