proxygen: upload Namespace Reference
upload Namespace Reference
Classes
class AbstractRpcServer
class ClientLoginError
class GitVCS
class HttpRpcServer
elif e.code >= 500 and e.code < 600:
Server Error - try again.
class MercurialVCS
class SubversionVCS
class VersionControlSystem
Functions
def GetEmail (prompt)
def StatusUpdate (msg)
def ErrorExit (msg)
def GetRpcServer (options)
def EncodeMultipartFormData (fields, files)
def GetContentType (filename)
def RunShellWithReturnCode (command, print_output=False, universal_newlines=True)
def RunShell (command, silent_ok=False, universal_newlines=True, print_output=False)
def SplitPatch (data)
def UploadSeparatePatches (issue, rpc_server, patchset, data, options)
def GuessVCS (options)
def RealMain (argv, data=None)
def main ()
Variables
int verbosity = 1
int MAX_UPLOAD_SIZE = 900
parser = optparse.OptionParser(usage="%prog [options] [-- diff_options]")
action
dest
default
help
group = parser.add_option_group("Logging options")
const
metavar
type
use_shell = sys.platform.startswith("win")
Function Documentation
def upload.EncodeMultipartFormData (fields, files)
Encode form fields for multipart/form-data.
Args:
  fields: A sequence of (name, value) elements for regular form fields.
  files: A sequence of (name, filename, value) elements for data to be
         uploaded as files.
Returns:
  (content_type, body) ready for httplib.HTTP instance.
Source:
  http://aspn.activestate.com/ASPN/Cookbook/Python/Recipe/146306
Definition at line 498 of file upload.py.
References GetContentType().
Referenced by upload.HttpRpcServer._GetOpener(), upload.MercurialVCS.GetBaseFile(), RealMain(), upload.VersionControlSystem.UploadBaseFiles(), and UploadSeparatePatches().
 def EncodeMultipartFormData(fields, files):
   """Encode form fields for multipart/form-data.
   Args:
     fields: A sequence of (name, value) elements for regular form fields.
     files: A sequence of (name, filename, value) elements for data to be
            uploaded as files.
   Returns:
     (content_type, body) ready for httplib.HTTP instance.
   Source:
     http://aspn.activestate.com/ASPN/Cookbook/Python/Recipe/146306
   """
   BOUNDARY = '-M-A-G-I-C---B-O-U-N-D-A-R-Y-'
   CRLF = '\r\n'
   lines = []
   for (key, value) in fields:
     lines.append('--' + BOUNDARY)
     lines.append('Content-Disposition: form-data; name="%s"' % key)
     lines.append('')
     lines.append(value)
   for (key, filename, value) in files:
     lines.append('--' + BOUNDARY)
     lines.append('Content-Disposition: form-data; name="%s"; filename="%s"' %
              (key, filename))
     lines.append('Content-Type: %s' % GetContentType(filename))
     lines.append('')
     lines.append(value)
   lines.append('--' + BOUNDARY + '--')
   lines.append('')
   body = CRLF.join(lines)
   content_type = 'multipart/form-data; boundary=%s' % BOUNDARY
   return content_type, body
def upload.ErrorExit (msg)
Print an error message to stderr and exit.
Definition at line 109 of file upload.py.
Referenced by upload.SubversionVCS.__init__(), upload.HttpRpcServer._GetOpener(), upload.SubversionVCS._GuessBase(), upload.VersionControlSystem.CheckForUnknownFiles(), upload.SubversionVCS.GenerateDiff(), upload.GitVCS.GenerateDiff(), upload.MercurialVCS.GenerateDiff(), upload.GitVCS.GetBaseFile(), upload.MercurialVCS.GetBaseFile(), upload.SubversionVCS.GetStatus(), GuessVCS(), RealMain(), and RunShell().
 def ErrorExit(msg):
   """Print an error message to stderr and exit."""
   print >>sys.stderr, msg
   sys.exit(1)
def upload.GetContentType (filename)
Helper to guess the content-type from the filename.
Definition at line 533 of file upload.py.
Referenced by upload.HttpRpcServer._GetOpener(), and EncodeMultipartFormData().
 def GetContentType(filename):
   """Helper to guess the content-type from the filename."""
   return mimetypes.guess_type(filename)[0] or 'application/octet-stream'
 # Use a shell for subcommands on Windows to get a PATH search.
def upload.GetEmail (prompt)
Prompts the user for their email address and returns it.
The last used email address is saved to a file and offered up as a suggestion
to the user. If the user presses enter without typing in anything the last
used email address is used. If the user enters a new address, it is saved
for next time we prompt.
Definition at line 65 of file upload.py.
References folly::detail::distributed_mutex.strip().
Referenced by upload.HttpRpcServer._GetOpener(), and GetRpcServer().
 def GetEmail(prompt):
   """Prompts the user for their email address and returns it.
   The last used email address is saved to a file and offered up as a suggestion
   to the user. If the user presses enter without typing in anything the last
   used email address is used. If the user enters a new address, it is saved
   for next time we prompt.
   """
   last_email_file_name = os.path.expanduser("~/.last_codereview_email_address")
   last_email = ""
   if os.path.exists(last_email_file_name):
     try:
       last_email_file = open(last_email_file_name, "r")
       last_email = last_email_file.readline().strip("\n")
       last_email_file.close()
       prompt += " [%s]" % last_email
     except IOError, e:
       pass
   email = raw_input(prompt + ": ").strip()
   if email:
     try:
       last_email_file = open(last_email_file_name, "w")
       last_email_file.write(email)
       last_email_file.close()
     except IOError, e:
       pass
   else:
     email = last_email
   return email
def upload.GetRpcServer (options)
Returns an instance of an AbstractRpcServer.
Returns:
  A new AbstractRpcServer, on which RPC calls can be made.
Definition at line 458 of file upload.py.
References GetEmail().
Referenced by upload.HttpRpcServer._GetOpener(), upload.MercurialVCS.GetBaseFile(), and RealMain().
 def GetRpcServer(options):
   """Returns an instance of an AbstractRpcServer.
   Returns:
     A new AbstractRpcServer, on which RPC calls can be made.
   """
   rpc_server_class = HttpRpcServer
   def GetUserCredentials():
     """Prompts the user for a username and password."""
     email = options.email
     if email is None:
       email = GetEmail("Email (login for uploading to %s)" % options.server)
     password = getpass.getpass("Password for %s: " % email)
     return (email, password)
   # If this is the dev_appserver, use fake authentication.
   host = (options.host or options.server).lower()
   if host == "localhost" or host.startswith("localhost:"):
     email = options.email
     if email is None:
       email = "test@example.com"
       logging.info("Using debug user %s.  Override with --email" % email)
     server = rpc_server_class(
         options.server,
         lambda: (email, "password"),
         host_override=options.host,
         extra_headers={"Cookie":
                        'dev_appserver_login="%s:False"' % email},
         save_cookies=options.save_cookies)
     # Don't try to talk to ClientLogin.
     server.authenticated = True
     return server
   return rpc_server_class(options.server, GetUserCredentials,
                           host_override=options.host,
                           save_cookies=options.save_cookies)
def upload.GuessVCS (options)
Helper to guess the version control system.
This examines the current directory, guesses which VersionControlSystem
we're using, and returns an instance of the appropriate class.  Exit with an
error if we can't figure it out.
Returns:
  A VersionControlSystem instance. Exits if the VCS can't be guessed.
Definition at line 1209 of file upload.py.
References ErrorExit(), and RunShellWithReturnCode().
Referenced by upload.MercurialVCS.GetBaseFile(), and RealMain().
 def GuessVCS(options):
   """Helper to guess the version control system.
   This examines the current directory, guesses which VersionControlSystem
   we're using, and returns an instance of the appropriate class.  Exit with an
   error if we can't figure it out.
   Returns:
     A VersionControlSystem instance. Exits if the VCS can't be guessed.
   """
   # Mercurial has a command to get the base directory of a repository
   # Try running it, but don't die if we don't have hg installed.
   # NOTE: we try Mercurial first as it can sit on top of an SVN working copy.
   try:
     out, returncode = RunShellWithReturnCode(["hg", "root"])
     if returncode == 0:
       return MercurialVCS(options, out.strip())
   except OSError, (errno, message):
     if errno != 2:  # ENOENT -- they don't have hg installed.
       raise
   # Subversion has a .svn in all working directories.
   if os.path.isdir('.svn'):
     logging.info("Guessed VCS = Subversion")
     return SubversionVCS(options)
   # Git has a command to test if you're in a git tree.
   # Try running it, but don't die if we don't have git installed.
   try:
     out, returncode = RunShellWithReturnCode(["git", "rev-parse",
                                               "--is-inside-work-tree"])
     if returncode == 0:
       return GitVCS(options)
   except OSError, (errno, message):
     if errno != 2:  # ENOENT -- they don't have git installed.
       raise
   ErrorExit(("Could not guess version control system. "
              "Are you in a working copy directory?"))
def upload.main (void)
Definition at line 1377 of file upload.py.
References RealMain(), and StatusUpdate().
Referenced by upload.MercurialVCS.GetBaseFile().
 def main():
   try:
     RealMain(sys.argv)
   except KeyboardInterrupt:
     print
     StatusUpdate("Interrupted.")
     sys.exit(1)
def upload.RealMain (argv, data = None)
The real main function.
Args:
  argv: Command line arguments.
  data: Diff contents. If None (default) the diff is generated by
    the VersionControlSystem implementation returned by GuessVCS().
Returns:
  A 2-tuple (issue id, patchset id).
  The patchset id is None if the base files are not uploaded by this
  script (applies only to SVN checkouts).
Definition at line 1250 of file upload.py.
References count, EncodeMultipartFormData(), ErrorExit(), GetRpcServer(), GuessVCS(), StatusUpdate(), folly::detail::distributed_mutex.strip(), and UploadSeparatePatches().
Referenced by upload.MercurialVCS.GetBaseFile(), and main().
 def RealMain(argv, data=None):
   """The real main function.
   Args:
     argv: Command line arguments.
     data: Diff contents. If None (default) the diff is generated by
       the VersionControlSystem implementation returned by GuessVCS().
   Returns:
     A 2-tuple (issue id, patchset id).
     The patchset id is None if the base files are not uploaded by this
     script (applies only to SVN checkouts).
   """
   logging.basicConfig(format=("%(asctime).19s %(levelname)s %(filename)s:"
                               "%(lineno)s %(message)s "))
   os.environ['LC_ALL'] = 'C'
   options, args = parser.parse_args(argv[1:])
   global verbosity
   verbosity = options.verbose
   if verbosity >= 3:
     logging.getLogger().setLevel(logging.DEBUG)
   elif verbosity >= 2:
     logging.getLogger().setLevel(logging.INFO)
   vcs = GuessVCS(options)
   if isinstance(vcs, SubversionVCS):
     # base field is only allowed for Subversion.
     # Note: Fetching base files may become deprecated in future releases.
     base = vcs.GuessBase(options.download_base)
   else:
     base = None
   if not base and options.download_base:
     options.download_base = True
     logging.info("Enabled upload of base file")
   if not options.assume_yes:
     vcs.CheckForUnknownFiles()
   if data is None:
     data = vcs.GenerateDiff(args)
   files = vcs.GetBaseFiles(data)
   if verbosity >= 1:
     print "Upload server:", options.server, "(change with -s/--server)"
   if options.issue:
     prompt = "Message describing this patch set: "
   else:
     prompt = "New issue subject: "
   message = options.message or raw_input(prompt).strip()
   if not message:
     ErrorExit("A non-empty message is required")
   rpc_server = GetRpcServer(options)
   form_fields = [("subject", message)]
   if base:
     form_fields.append(("base", base))
   if options.issue:
     form_fields.append(("issue", str(options.issue)))
   if options.email:
     form_fields.append(("user", options.email))
   if options.reviewers:
     for reviewer in options.reviewers.split(','):
       if "@" in reviewer and not reviewer.split("@")[1].count(".") == 1:
         ErrorExit("Invalid email address: %s" % reviewer)
     form_fields.append(("reviewers", options.reviewers))
   if options.cc:
     for cc in options.cc.split(','):
       if "@" in cc and not cc.split("@")[1].count(".") == 1:
         ErrorExit("Invalid email address: %s" % cc)
     form_fields.append(("cc", options.cc))
   description = options.description
   if options.description_file:
     if options.description:
       ErrorExit("Can't specify description and description_file")
     file = open(options.description_file, 'r')
     description = file.read()
     file.close()
   if description:
     form_fields.append(("description", description))
   # Send a hash of all the base file so the server can determine if a copy
   # already exists in an earlier patchset.
   base_hashes = ""
   for file, info in files.iteritems():
     if not info[0] is None:
       checksum = md5.new(info[0]).hexdigest()
       if base_hashes:
         base_hashes += "|"
       base_hashes += checksum + ":" + file
   form_fields.append(("base_hashes", base_hashes))
   # If we're uploading base files, don't send the email before the uploads, so
   # that it contains the file status.
   if options.send_mail and options.download_base:
     form_fields.append(("send_mail", "1"))
   if not options.download_base:
     form_fields.append(("content_upload", "1"))
   if len(data) > MAX_UPLOAD_SIZE:
     print "Patch is large, so uploading file patches separately."
     uploaded_diff_file = []
     form_fields.append(("separate_patches", "1"))
   else:
     uploaded_diff_file = [("data", "data.diff", data)]
   ctype, body = EncodeMultipartFormData(form_fields, uploaded_diff_file)
   response_body = rpc_server.Send("/upload", body, content_type=ctype)
   patchset = None
   if not options.download_base or not uploaded_diff_file:
     lines = response_body.splitlines()
     if len(lines) >= 2:
       msg = lines[0]
       patchset = lines[1].strip()
       patches = [x.split(" ", 1) for x in lines[2:]]
     else:
       msg = response_body
   else:
     msg = response_body
   StatusUpdate(msg)
   if not response_body.startswith("Issue created.") and \
   not response_body.startswith("Issue updated."):
     sys.exit(0)
   issue = msg[msg.rfind("/")+1:]
   if not uploaded_diff_file:
     result = UploadSeparatePatches(issue, rpc_server, patchset, data, options)
     if not options.download_base:
       patches = result
   if not options.download_base:
     vcs.UploadBaseFiles(issue, rpc_server, patches, patchset, options, files)
     if options.send_mail:
       rpc_server.Send("/" + issue + "/mail", payload="")
   return issue, patchset
def upload.RunShell (command, silent_ok = False, universal_newlines = True, print_output = False)
Definition at line 578 of file upload.py.
References ErrorExit(), and RunShellWithReturnCode().
Referenced by upload.MercurialVCS.__init__(), upload.HttpRpcServer._GetOpener(), upload.SubversionVCS._GuessBase(), upload.SubversionVCS.GenerateDiff(), upload.GitVCS.GenerateDiff(), upload.MercurialVCS.GenerateDiff(), upload.SubversionVCS.GetBaseFile(), upload.MercurialVCS.GetBaseFile(), upload.SubversionVCS.GetStatus(), upload.SubversionVCS.GetUnknownFiles(), upload.GitVCS.GetUnknownFiles(), upload.MercurialVCS.GetUnknownFiles(), and RunShellWithReturnCode().
              print_output=False):
   data, retcode = RunShellWithReturnCode(command, print_output,
                                          universal_newlines)
   if retcode:
     ErrorExit("Got error status from %s:\n%s" % (command, data))
   if not silent_ok and not data:
     ErrorExit("No output from %s" % command)
   return data
def upload.RunShellWithReturnCode (command, print_output = False, universal_newlines = True)
Executes a command and returns the output from stdout and the return code.
Args:
  command: Command to execute.
  print_output: If True, the output is printed to stdout.
                If False, both stdout and stderr are ignored.
  universal_newlines: Use universal_newlines flag (default: True).
Returns:
  Tuple (output, return code)
Definition at line 542 of file upload.py.
References join, and RunShell().
Referenced by upload.HttpRpcServer._GetOpener(), upload.SubversionVCS.GetBaseFile(), upload.GitVCS.GetBaseFile(), upload.MercurialVCS.GetBaseFile(), upload.SubversionVCS.GetStatus(), GuessVCS(), and RunShell().
                            universal_newlines=True):
   """Executes a command and returns the output from stdout and the return code.
   Args:
     command: Command to execute.
     print_output: If True, the output is printed to stdout.
                   If False, both stdout and stderr are ignored.
     universal_newlines: Use universal_newlines flag (default: True).
   Returns:
     Tuple (output, return code)
   """
   logging.info("Running %s", command)
   p = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                        shell=use_shell, universal_newlines=universal_newlines)
   if print_output:
     output_array = []
     while True:
       line = p.stdout.readline()
       if not line:
         break
       print line.strip("\n")
       output_array.append(line)
     output = "".join(output_array)
   else:
     output = p.stdout.read()
   p.wait()
   errout = p.stderr.read()
   if print_output and errout:
     print >>sys.stderr, errout
   p.stdout.close()
   p.stderr.close()
   return output, p.returncode
def upload.SplitPatch (data)
Splits a patch into separate pieces for each file.
Args:
  data: A string containing the output of svn diff.
Returns:
  A list of 2-tuple (filename, text) where text is the svn diff output
    pertaining to filename.
Definition at line 1141 of file upload.py.
References join, and replace().
Referenced by upload.MercurialVCS.GetBaseFile(), and UploadSeparatePatches().
 def SplitPatch(data):
   """Splits a patch into separate pieces for each file.
   Args:
     data: A string containing the output of svn diff.
   Returns:
     A list of 2-tuple (filename, text) where text is the svn diff output
       pertaining to filename.
   """
   patches = []
   filename = None
   diff = []
   for line in data.splitlines(True):
     new_filename = None
     if line.startswith('Index:'):
       unused, new_filename = line.split(':', 1)
       new_filename = new_filename.strip()
     elif line.startswith('Property changes on:'):
       unused, temp_filename = line.split(':', 1)
       # When a file is modified, paths use '/' between directories, however
       # when a property is modified '\' is used on Windows.  Make them the same
       # otherwise the file shows up twice.
       temp_filename = temp_filename.strip().replace('\\', '/')
       if temp_filename != filename:
         # File has property changes but no modifications, create a new diff.
         new_filename = temp_filename
     if new_filename:
       if filename and diff:
         patches.append((filename, ''.join(diff)))
       filename = new_filename
       diff = [line]
       continue
     if diff is not None:
       diff.append(line)
   if filename and diff:
     patches.append((filename, ''.join(diff)))
   return patches
def upload.StatusUpdate (msg)
Print a status message to stdout.
If 'verbosity' is greater than 0, print the message.
Args:
  msg: The string to print.
Definition at line 97 of file upload.py.
Referenced by upload.HttpRpcServer._Authenticate(), upload.HttpRpcServer._GetOpener(), upload.SubversionVCS.GetBaseFile(), upload.MercurialVCS.GetBaseFile(), main(), RealMain(), upload.VersionControlSystem.UploadBaseFiles(), and UploadSeparatePatches().
 def StatusUpdate(msg):
   """Print a status message to stdout.
   If 'verbosity' is greater than 0, print the message.
   Args:
     msg: The string to print.
   """
   if verbosity > 0:
     print msg
def upload.UploadSeparatePatches (issue, rpc_server, patchset, data, options)
Uploads a separate patch for each file in the diff output.
Returns a list of [patch_key, filename] for each file.
Definition at line 1181 of file upload.py.
References EncodeMultipartFormData(), SplitPatch(), and StatusUpdate().
Referenced by upload.MercurialVCS.GetBaseFile(), and RealMain().
 def UploadSeparatePatches(issue, rpc_server, patchset, data, options):
   """Uploads a separate patch for each file in the diff output.
   Returns a list of [patch_key, filename] for each file.
   """
   patches = SplitPatch(data)
   rv = []
   for patch in patches:
     if len(patch[1]) > MAX_UPLOAD_SIZE:
       print ("Not uploading the patch for " + patch[0] +
              " because the file is too large.")
       continue
     form_fields = [("filename", patch[0])]
     if not options.download_base:
       form_fields.append(("content_upload", "1"))
     files = [("data", "data.diff", patch[1])]
     ctype, body = EncodeMultipartFormData(form_fields, files)
     url = "/%d/upload_patch/%d" % (int(issue), int(patchset))
     print "Uploading patch for " + patch[0]
     response_body = rpc_server.Send(url, body, content_type=ctype)
     lines = response_body.splitlines()
     if not lines or lines[0] != "OK":
       StatusUpdate("  --> %s" % response_body)
       sys.exit(1)
     rv.append([lines[1], patch[0]])
   return rv
Variable Documentation
upload.action
Definition at line 393 of file upload.py.
Referenced by testing::Action< InnerFunctionType >.Action(), fizz::test::ProtocolTest< ClientTypes, Actions >.expectAction(), folly::Subprocess::Options.fd(), fizz::test::ProtocolTest< ClientTypes, Actions >.getNumActions(), folly::Subprocess::Options.Options(), testing::internal::InvokeMethodAction< Class, MethodPtr >.Perform(), testing::gmock_generated_actions_test::SubstractAction.Perform(), testing::internal::ActionHelper< Result, Impl >.Perform(), fizz::FizzBase< Derived, ActionMoveVisitor, StateMachine >.processActions(), fizz::test::ProtocolTest< ClientTypes, Actions >.processStateMutations(), testing::gmock_generated_actions_test.TEST(), proxygen.TEST_F(), testing::internal::FunctionMockerBase< R(A1, A2)>.UntypedFindMatchingExpectation(), testing::internal::FunctionMockerBase< R(A1, A2)>.UntypedPerformAction(), testing::internal::OnCallSpec< F >.WillByDefault(), testing::internal::TypedExpectation< F >.WillRepeatedly(), testing.WithArg(), testing.WithArgs(), and testing.WithoutArgs().
upload.const
Definition at line 398 of file upload.py.
Referenced by folly::pushmi::any_constrained_single_sender< E, TP, VN... >.any_constrained_single_sender(), folly::pushmi::any_flow_many_sender< PE, PV, E, VN >.any_flow_many_sender(), folly::pushmi::any_flow_receiver< PE, PV, E, VN >.any_flow_receiver(), folly::pushmi::any_flow_single_sender< PE, E, VN >.any_flow_single_sender(), folly::pushmi::any_many_sender< E, VN >.any_many_sender(), folly::pushmi::any_receiver< E, folly::pushmi::any_executor_ref< E > >.any_receiver(), folly::pushmi::any_single_sender< E, VN >.any_single_sender(), folly::exception_wrapper::Buffer.as(), folly::exception_wrapper::ExceptionPtr.as_exception_(), folly::exception_wrapper::ExceptionPtr.as_int_(), folly::exception_wrapper::ExceptionPtr.as_type_(), folly::detail::IteratorFacade< dynamic::const_key_iterator, dynamic const , std::forward_iterator_tag >.asDerivedConst(), folly::dynamic.at(), folly::AtomicHashArray< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >.cellKeyPtr(), folly::replaceable_detail::copy_ctor_mixin< T, true >.copy_ctor_mixin(), folly::dynamic.get_ptr(), folly::F14VectorSet< Key, Hasher, KeyEqual, Alloc >.operator=(), folly::replaceable_detail::copy_assignment_mixin< T, true >.operator=(), folly::StringKeyedMap< Value, Compare, Alloc >.operator==(), folly::StringKeyedSetBase< Compare, Alloc >.operator==(), folly.poly_call(), TEST(), and folly::detail.to_exception_arg_().
upload.default
Definition at line 394 of file upload.py.
upload.dest
Definition at line 394 of file upload.py.
Referenced by testing::internal::CodeLocation.CodeLocation(), folly::BasicFixedString< Char, N >.copy(), folly::bser.decodeString(), folly.demangle(), folly::symbolizer::Dwarf::Path.file(), folly::IOBufQueue.fillWritableRangeCache(), testing::internal.IsPathSeparator(), testing::internal::FilePath.Normalize(), folly::compression::detail::UpperBitsReader< Encoder, Instructions, SizeType >.prepareSkipTo(), producerConsumerBench(), proxygen::TraceEvent.readIntMeta(), folly::fbvector< HTTPHeaderCode >.relocate_undo(), folly::NestedCommandLineApp.resolveAlias(), runElementTypeTest(), runNeverFailThread(), runNeverFailUntilThread(), folly::fbvector< HTTPHeaderCode >.S_copy_n(), folly::fbvector< HTTPHeaderCode >.S_uninitialized_copy(), folly::fbvector< HTTPHeaderCode >.S_uninitialized_copy_a(), folly::fbvector< HTTPHeaderCode >.S_uninitialized_fill_n(), folly::fbvector< HTTPHeaderCode >.S_uninitialized_fill_n_a(), testing::internal.ShouldRunTestCase(), folly::compression::BitVectorReader< Encoder, Instructions, kUnchecked >.skip(), folly::compression::detail::UpperBitsReader< Encoder, Instructions, SizeType >.skip(), folly::compression::detail::UpperBitsReader< Encoder, Instructions, SizeType >.skipToNext(), folly.TEST(), TEST(), folly::LockFreeRingBuffer< T, Atom >.tryRead(), folly::detail::RingBufferSlot< T, Atom >.tryRead(), folly::LockFreeRingBuffer< T, Atom >.waitAndTryRead(), and folly::detail::RingBufferSlot< T, Atom >.waitAndTryRead().
upload.group = parser.add_option_group("Logging options")
Definition at line 397 of file upload.py.
upload.help
Definition at line 395 of file upload.py.
int upload.MAX_UPLOAD_SIZE = 900
Definition at line 62 of file upload.py.
upload.metavar
Definition at line 409 of file upload.py.
upload.parser = optparse.OptionParser(usage="%prog [options] [-- diff_options]")
Definition at line 392 of file upload.py.
upload.type
Definition at line 443 of file upload.py.
upload.use_shell = sys.platform.startswith("win")
Definition at line 539 of file upload.py.
int upload.verbosity = 1
Definition at line 59 of file upload.py.
Referenced by proxygen::HTTPMessage.getUpgradeProtocol().