proxygen: folly::portability::ssl Namespace Reference
folly::portability::ssl Namespace Reference
Typedefs
using OPENSSL_INIT_SETTINGS = void
Functions
BIO_METHOD * BIO_meth_new (int type, const char *name)
void BIO_meth_free (BIO_METHOD *biom)
int BIO_meth_set_read (BIO_METHOD *biom, int(*read)(BIO *, char *, int))
int BIO_meth_set_write (BIO_METHOD *biom, int(*write)(BIO *, const char *, int))
int BIO_meth_set_puts (BIO_METHOD *biom, int(*bputs)(BIO *, const char *))
int BIO_meth_set_gets (BIO_METHOD *biom, int(*bgets)(BIO *, char *, int))
int BIO_meth_set_ctrl (BIO_METHOD *biom, long(*ctrl)(BIO *, int, long, void *))
int BIO_meth_set_create (BIO_METHOD *biom, int(*create)(BIO *))
int BIO_meth_set_destroy (BIO_METHOD *biom, int(*destroy)(BIO *))
void BIO_set_data (BIO *bio, void *ptr)
void * BIO_get_data (BIO *bio)
void BIO_set_init (BIO *bio, int init)
void BIO_set_shutdown (BIO *bio, int shutdown)
const SSL_METHOD * TLS_server_method (void)
const SSL_METHOD * TLS_client_method (void)
const char * SSL_SESSION_get0_hostname (const SSL_SESSION *s)
unsigned char * ASN1_STRING_get0_data (const ASN1_STRING *x)
int SSL_SESSION_has_ticket (const SSL_SESSION *s)
unsigned long SSL_SESSION_get_ticket_lifetime_hint (const SSL_SESSION *s)
int DH_set0_pqg (DH *dh, BIGNUM *p, BIGNUM *q, BIGNUM *g)
void DH_get0_pqg (const DH *dh, const BIGNUM **p, const BIGNUM **q, const BIGNUM **g)
void DH_get0_key (const DH *dh, const BIGNUM **pub_key, const BIGNUM **priv_key)
void DSA_get0_pqg (const DSA *dsa, const BIGNUM **p, const BIGNUM **q, const BIGNUM **g)
void DSA_get0_key (const DSA *dsa, const BIGNUM **pub_key, const BIGNUM **priv_key)
STACK_OF (X509_OBJECT)*X509_STORE_get0_objects(X509_STORE *store)
X509 * X509_STORE_CTX_get0_cert (X509_STORE_CTX *ctx)
STACK_OF (X509)*X509_STORE_CTX_get0_chain(X509_STORE_CTX *ctx)
EVP_MD_CTX * EVP_MD_CTX_new ()
void EVP_MD_CTX_free (EVP_MD_CTX *ctx)
HMAC_CTX * HMAC_CTX_new ()
void HMAC_CTX_free (HMAC_CTX *ctx)
bool RSA_set0_key (RSA *r, BIGNUM *n, BIGNUM *e, BIGNUM *d)
void RSA_get0_factors (const RSA *r, const BIGNUM **p, const BIGNUM **q)
void RSA_get0_crt_params (const RSA *r, const BIGNUM **dmp1, const BIGNUM **dmq1, const BIGNUM **iqmp)
int ECDSA_SIG_set0 (ECDSA_SIG *sig, BIGNUM *r, BIGNUM *s)
void ECDSA_SIG_get0 (const ECDSA_SIG *sig, const BIGNUM **pr, const BIGNUM **ps)
int OPENSSL_init_ssl (uint64_t, const OPENSSL_INIT_SETTINGS *)
void OPENSSL_cleanup ()
const ASN1_INTEGER * X509_REVOKED_get0_serialNumber (const X509_REVOKED *r)
const ASN1_TIME * X509_REVOKED_get0_revocationDate (const X509_REVOKED *r)
uint32_t X509_get_extension_flags (X509 *x)
uint32_t X509_get_key_usage (X509 *x)
uint32_t X509_get_extended_key_usage (X509 *x)
int X509_OBJECT_get_type (const X509_OBJECT *obj)
X509 * X509_OBJECT_get0_X509 (const X509_OBJECT *obj)
const ASN1_TIME * X509_CRL_get0_lastUpdate (const X509_CRL *crl)
const ASN1_TIME * X509_CRL_get0_nextUpdate (const X509_CRL *crl)
const X509_ALGOR * X509_get0_tbs_sigalg (const X509 *x)
Typedef Documentation
using folly::portability::ssl::OPENSSL_INIT_SETTINGS = typedef void
Definition at line 189 of file OpenSSL.h.
Function Documentation
unsigned char * folly::portability::ssl::ASN1_STRING_get0_data (const ASN1_STRING * x)
Definition at line 199 of file OpenSSL.cpp.
Referenced by folly::ssl::OpenSSLCertUtils::getCommonName(), wangle::SSLUtil::getSubjectAltName(), and folly::ssl::OpenSSLCertUtils::getSubjectAltNames().
{
   return ASN1_STRING_data((ASN1_STRING*)x);
 }
void * folly::portability::ssl::BIO_get_data (BIO * bio)
Definition at line 175 of file OpenSSL.cpp.
{
   return bio->ptr;
 }
void folly::portability::ssl::BIO_meth_free (BIO_METHOD * biom)
Definition at line 132 of file OpenSSL.cpp.
{
   OPENSSL_free((void*)biom);
 }
BIO_METHOD * folly::portability::ssl::BIO_meth_new (int type, const char * name)
Definition at line 121 of file OpenSSL.cpp.
References name, and type.
Referenced by folly::ssl::OpenSSLUtils::newSocketBioMethod().
{
   BIO_METHOD* method = (BIO_METHOD*)OPENSSL_malloc(sizeof(BIO_METHOD));
   if (method == nullptr) {
     return nullptr;
   }
   memset(method, 0, sizeof(BIO_METHOD));
   method->type = type;
   method->name = name;
   return method;
 }
int folly::portability::ssl::BIO_meth_set_create (BIO_METHOD * biom, int(*)(BIO *) create)
Definition at line 161 of file OpenSSL.cpp.
Referenced by folly::ssl::OpenSSLUtils::newSocketBioMethod().
{
   biom->create = create;
   return 1;
 }
int folly::portability::ssl::BIO_meth_set_ctrl (BIO_METHOD * biom, long(*)(BIO *, int, long, void *) ctrl)
Definition at line 156 of file OpenSSL.cpp.
Referenced by folly::ssl::OpenSSLUtils::newSocketBioMethod().
{
   biom->ctrl = ctrl;
   return 1;
 }
int folly::portability::ssl::BIO_meth_set_destroy (BIO_METHOD * biom, int(*)(BIO *) destroy)
Definition at line 166 of file OpenSSL.cpp.
References destroy().
Referenced by folly::ssl::OpenSSLUtils::newSocketBioMethod().
{
   biom->destroy = destroy;
   return 1;
 }
int folly::portability::ssl::BIO_meth_set_gets (BIO_METHOD * biom, int(*)(BIO *, char *, int) bgets)
Definition at line 151 of file OpenSSL.cpp.
Referenced by folly::ssl::OpenSSLUtils::newSocketBioMethod().
{
   biom->bgets = bgets;
   return 1;
 }
int folly::portability::ssl::BIO_meth_set_puts (BIO_METHOD * biom, int(*)(BIO *, const char *) bputs)
Definition at line 146 of file OpenSSL.cpp.
Referenced by folly::ssl::OpenSSLUtils::newSocketBioMethod().
{
   biom->bputs = bputs;
   return 1;
 }
int folly::portability::ssl::BIO_meth_set_read (BIO_METHOD * biom, int(*)(BIO *, char *, int) read)
Definition at line 136 of file OpenSSL.cpp.
References fizz::detail::read().
Referenced by folly::ssl::OpenSSLUtils::newSocketBioMethod(), and folly::ssl::OpenSSLUtils::setCustomBioReadMethod().
{
   biom->bread = read;
   return 1;
 }
int folly::portability::ssl::BIO_meth_set_write (BIO_METHOD * biom, int(*)(BIO *, const char *, int) write)
Definition at line 141 of file OpenSSL.cpp.
References fizz::detail::write().
Referenced by folly::ssl::OpenSSLUtils::newSocketBioMethod(), and folly::ssl::OpenSSLUtils::setCustomBioWriteMethod().
{
   biom->bwrite = write;
   return 1;
 }
void folly::portability::ssl::BIO_set_data (BIO * bio, void * ptr)
Definition at line 171 of file OpenSSL.cpp.
References ptr.
{
   bio->ptr = ptr;
 }
void folly::portability::ssl::BIO_set_init (BIO * bio, int init)
Definition at line 179 of file OpenSSL.cpp.
References folly::init().
{
   bio->init = init;
 }
void folly::portability::ssl::BIO_set_shutdown (BIO * bio, int shutdown)
Definition at line 183 of file OpenSSL.cpp.
References folly::shutdown().
{
   bio->shutdown = shutdown;
 }
void folly::portability::ssl::DH_get0_key (const DH * dh, const BIGNUM ** pub_key, const BIGNUM ** priv_key)
Definition at line 262 of file OpenSSL.cpp.
{
   // Based off of https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes
   if (pub_key != nullptr) {
     *pub_key = dh->pub_key;
   }
   if (priv_key != nullptr) {
     *priv_key = dh->priv_key;
   }
 }
void folly::portability::ssl::DH_get0_pqg (const DH * dh, const BIGNUM ** p, const BIGNUM ** q, const BIGNUM ** g)
Definition at line 245 of file OpenSSL.cpp.
                       {
   // Based off of https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes
   if (p != nullptr) {
     *p = dh->p;
   }
   if (q != nullptr) {
     *q = dh->q;
   }
   if (g != nullptr) {
     *g = dh->g;
   }
 }
int folly::portability::ssl::DH_set0_pqg (DH * dh, BIGNUM * p, BIGNUM * q, BIGNUM * g)
Definition at line 212 of file OpenSSL.cpp.
References g().
{
   /* If the fields p and g in d are nullptr, the corresponding input
    * parameters MUST not be nullptr.  q may remain nullptr.
    */
   if (dh == nullptr || (dh->p == nullptr && p == nullptr) ||
       (dh->g == nullptr && g == nullptr)) {
     return 0;
   }
   if (p != nullptr) {
     BN_free(dh->p);
     dh->p = p;
   }
   if (q != nullptr) {
     BN_free(dh->q);
     dh->q = q;
   }
   if (g != nullptr) {
     BN_free(dh->g);
     dh->g = g;
   }
   // In OpenSSL 1.1.0, DH_set0_pqg also sets
   //   dh->length = BN_num_bits(q)
   // With OpenSSL 1.0.2, the output of openssl dhparam -C 2048 doesn't set
   // the length field. So as far as the compat lib is concerned, this wrapper
   // mimics the functionality of OpenSSL 1.0.2
   // Note: BoringSSL doesn't even have a length field anymore, just something
   // called 'priv_length'. Let's not mess with that for now.
   return 1;
 }
void folly::portability::ssl::DSA_get0_key (const DSA * dsa, const BIGNUM ** pub_key, const BIGNUM ** priv_key)
Definition at line 292 of file OpenSSL.cpp.
{
   // Based off of https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes
   if (pub_key != nullptr) {
     *pub_key = dsa->pub_key;
   }
   if (priv_key != nullptr) {
     *priv_key = dsa->priv_key;
   }
 }
void folly::portability::ssl::DSA_get0_pqg (const DSA * dsa, const BIGNUM ** p, const BIGNUM ** q, const BIGNUM ** g)
Definition at line 275 of file OpenSSL.cpp.
                       {
   // Based off of https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes
   if (p != nullptr) {
     *p = dsa->p;
   }
   if (q != nullptr) {
     *q = dsa->q;
   }
   if (g != nullptr) {
     *g = dsa->g;
   }
 }
void folly::portability::ssl::ECDSA_SIG_get0 (const ECDSA_SIG * sig, const BIGNUM ** pr, const BIGNUM ** ps)
Definition at line 417 of file OpenSSL.cpp.
Referenced by fizz::extensions::TokenBindingConstructor::encodeEcdsaSignature(), and TEST().
{
   // Based off of https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes
   if (pr != nullptr) {
     *pr = sig->r;
   }
   if (ps != nullptr) {
     *ps = sig->s;
   }
 }
int folly::portability::ssl::ECDSA_SIG_set0 (ECDSA_SIG * sig, BIGNUM * r, BIGNUM * s)
Definition at line 405 of file OpenSSL.cpp.
References s.
Referenced by fizz::extensions::Validator::constructECDSASig(), and TEST().
{
   // Based off of https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes
   if (r == nullptr || s == nullptr) {
     return 0;
   }
   BN_clear_free(sig->r);
   BN_clear_free(sig->s);
   sig->r = r;
   sig->s = s;
   return 1;
 }
void folly::portability::ssl::EVP_MD_CTX_free (EVP_MD_CTX * ctx)
Definition at line 330 of file OpenSSL.cpp.
{
   if (ctx) {
     EVP_MD_CTX_cleanup(ctx);
     OPENSSL_free(ctx);
   }
 }
EVP_MD_CTX * folly::portability::ssl::EVP_MD_CTX_new ()
Definition at line 321 of file OpenSSL.cpp.
Referenced by folly::ssl::OpenSSLHash::Digest::Digest(), fizz::detail::ecSign(), fizz::detail::ecVerify(), fizz::detail::rsaPssSign(), and fizz::detail::rsaPssVerify().
{
   EVP_MD_CTX* ctx = (EVP_MD_CTX*)OPENSSL_malloc(sizeof(EVP_MD_CTX));
   if (!ctx) {
     throw std::runtime_error("Cannot allocate EVP_MD_CTX");
   }
   EVP_MD_CTX_init(ctx);
   return ctx;
 }
void folly::portability::ssl::HMAC_CTX_free (HMAC_CTX * ctx)
Definition at line 346 of file OpenSSL.cpp.
{
   if (ctx) {
     HMAC_CTX_cleanup(ctx);
     OPENSSL_free(ctx);
   }
 }
HMAC_CTX * folly::portability::ssl::HMAC_CTX_new ()
Definition at line 337 of file OpenSSL.cpp.
{
   HMAC_CTX* ctx = (HMAC_CTX*)OPENSSL_malloc(sizeof(HMAC_CTX));
   if (!ctx) {
     throw std::runtime_error("Cannot allocate HMAC_CTX");
   }
   HMAC_CTX_init(ctx);
   return ctx;
 }
void folly::portability::ssl::OPENSSL_cleanup ()
Definition at line 455 of file OpenSSL.cpp.
References folly::ssl::detail::cleanupThreadingLocks().
Referenced by main().
{
   folly::ssl::detail::cleanupThreadingLocks();
   CRYPTO_cleanup_all_ex_data();
   ERR_free_strings();
   EVP_cleanup();
   ERR_clear_error();
 }
int folly::portability::ssl::OPENSSL_init_ssl (uint64_t , const OPENSSL_INIT_SETTINGS *)
Compatibility shim for OpenSSL < 1.1.0.
For now, options and settings are ignored. We implement the most common behavior, which is to add all digests, ciphers, and strings.
Definition at line 436 of file OpenSSL.cpp.
References folly::ssl::detail::installThreadingLocks().
{
   // OpenSSL >= 1.1.0 handles initializing the library, adding digests &
   // ciphers, loading strings. Additionally, OpenSSL >= 1.1.0 uses platform
   // native threading & mutexes, which means that we should handle setting up
   // the necessary threading initialization in the compat layer as well.
   SSL_library_init();
   OpenSSL_add_all_ciphers();
   OpenSSL_add_all_digests();
   OpenSSL_add_all_algorithms();
   SSL_load_error_strings();
   ERR_load_crypto_strings();
   // The caller should have used SSLContext::setLockTypes() prior to calling
   // this function.
   folly::ssl::detail::installThreadingLocks();
   return 0;
 }
void folly::portability::ssl::RSA_get0_crt_params (const RSA * r, const BIGNUM ** dmp1, const BIGNUM ** dmq1, const BIGNUM ** iqmp)
Definition at line 388 of file OpenSSL.cpp.
{
   // Based off of https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes
   if (dmp1 != nullptr) {
     *dmp1 = r->dmp1;
   }
   if (dmq1 != nullptr) {
     *dmq1 = r->dmq1;
   }
   if (iqmp != nullptr) {
     *iqmp = r->iqmp;
   }
 }
void folly::portability::ssl::RSA_get0_factors (const RSA * r, const BIGNUM ** p, const BIGNUM ** q)
Definition at line 378 of file OpenSSL.cpp.
{
   // Based off of https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes
   if (p != nullptr) {
     *p = r->p;
   }
   if (q != nullptr) {
     *q = r->q;
   }
 }
bool folly::portability::ssl::RSA_set0_key (RSA * r, BIGNUM * n, BIGNUM * e, BIGNUM * d)
If the fields n and e in r are nullptr, the corresponding input parameters MUST be non-nullptr for n and e. d may be left NULL (in case only the public key is used).
Definition at line 353 of file OpenSSL.cpp.
Referenced by TEST().
{
   // Based off of https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes
   if ((r->n == nullptr && n == nullptr) || (r->e == nullptr && e == nullptr)) {
     return false;
   }
   if (n != nullptr) {
     BN_free(r->n);
     r->n = n;
   }
   if (e != nullptr) {
     BN_free(r->e);
     r->e = e;
   }
   if (d != nullptr) {
     BN_free(r->d);
     r->d = d;
   }
   return true;
 }
const char * folly::portability::ssl::SSL_SESSION_get0_hostname (const SSL_SESSION * s)
Definition at line 195 of file OpenSSL.cpp.
Referenced by wangle::SSLSessionCallbacks::removeSessionCallback(), and folly::AsyncSSLSocket::sslAccept().
{
   return s->tlsext_hostname;
 }
unsigned long folly::portability::ssl::SSL_SESSION_get_ticket_lifetime_hint (const SSL_SESSION * s)
Definition at line 207 of file OpenSSL.cpp.
Referenced by wangle::SSLSessionPersistentCacheBase< K >::getSSLSession(), and wangle::TEST_F().
{
   return s->tlsext_tick_lifetime_hint;
 }
int folly::portability::ssl::SSL_SESSION_has_ticket (const SSL_SESSION * s)
Definition at line 203 of file OpenSSL.cpp.
Referenced by wangle::SSLSessionPersistentCacheBase< K >::getSSLSession(), and wangle::TEST_F().
{
   return (s->tlsext_ticklen > 0) ? 1 : 0;
 }
folly::portability::ssl::STACK_OF (X509_OBJECT)
Definition at line 305 of file OpenSSL.cpp.
Referenced by fizz::JavaCryptoCertificateVerifier::createAuthorities(), fizz::DefaultCertificateVerifier::createAuthorities(), folly::ssl::getOpenSSLCipherNames(), folly::ssl::OpenSSLCertUtils::getSubjectAltNames(), STACK_OF(), and folly::ssl::OpenSSLUtils::validatePeerCertNames().
{
   return store->objs;
 }
folly::portability::ssl::STACK_OF (X509)
Definition at line 313 of file OpenSSL.cpp.
References STACK_OF().
{
   return X509_STORE_CTX_get_chain(ctx);
 }
const SSL_METHOD * folly::portability::ssl::TLS_client_method (void)
Definition at line 191 of file OpenSSL.cpp.
{
   return TLSv1_2_client_method();
 }
const SSL_METHOD * folly::portability::ssl::TLS_server_method (void)
Definition at line 187 of file OpenSSL.cpp.
{
   return TLSv1_2_server_method();
 }
const ASN1_TIME * folly::portability::ssl::X509_CRL_get0_lastUpdate (const X509_CRL * crl)
Definition at line 494 of file OpenSSL.cpp.
{
   return X509_CRL_get_lastUpdate(crl);
 }
const ASN1_TIME * folly::portability::ssl::X509_CRL_get0_nextUpdate (const X509_CRL * crl)
Definition at line 498 of file OpenSSL.cpp.
{
   return X509_CRL_get_nextUpdate(crl);
 }
const X509_ALGOR * folly::portability::ssl::X509_get0_tbs_sigalg (const X509 * x)
Definition at line 502 of file OpenSSL.cpp.
{
   return x->cert_info->signature;
 }
uint32_t folly::portability::ssl::X509_get_extended_key_usage (X509 * x)
Definition at line 479 of file OpenSSL.cpp.
{
   return x->ex_xkusage;
 }
uint32_t folly::portability::ssl::X509_get_extension_flags (X509 * x)
Definition at line 471 of file OpenSSL.cpp.
{
   return x->ex_flags;
 }
uint32_t folly::portability::ssl::X509_get_key_usage (X509 * x)
Definition at line 475 of file OpenSSL.cpp.
{
   return x->ex_kusage;
 }
X509 * folly::portability::ssl::X509_OBJECT_get0_X509 (const X509_OBJECT * obj)
Definition at line 487 of file OpenSSL.cpp.
Referenced by fizz::JavaCryptoCertificateVerifier::createAuthorities(), and fizz::DefaultCertificateVerifier::createAuthorities().
{
   if (obj == nullptr || obj->type != X509_LU_X509) {
     return nullptr;
   }
   return obj->data.x509;
 }
int folly::portability::ssl::X509_OBJECT_get_type (const X509_OBJECT * obj)
Definition at line 483 of file OpenSSL.cpp.
Referenced by fizz::JavaCryptoCertificateVerifier::createAuthorities(), and fizz::DefaultCertificateVerifier::createAuthorities().
{
   return obj->type;
 }
const ASN1_TIME * folly::portability::ssl::X509_REVOKED_get0_revocationDate (const X509_REVOKED * r)
Definition at line 467 of file OpenSSL.cpp.
Referenced by TEST().
{
   return r->revocationDate;
 }
const ASN1_INTEGER * folly::portability::ssl::X509_REVOKED_get0_serialNumber (const X509_REVOKED * r)
Definition at line 463 of file OpenSSL.cpp.
Referenced by TEST().
{
   return r->serialNumber;
 }
X509 * folly::portability::ssl::X509_STORE_CTX_get0_cert (X509_STORE_CTX * ctx)
Definition at line 309 of file OpenSSL.cpp.
{
   return ctx->cert;
 }