proxygen: logging_test Namespace Reference
logging_test Namespace Reference
Functions
void testXlogFile1Dbg1 (folly::StringPiece msg)
void testXlogFile2Dbg1 (folly::StringPiece msg)
void testXlogHdrLoop (size_t numIters, folly::StringPiece arg)
void testXlogHdrFunction (folly::StringPiece str, int value)
Function Documentation
void logging_test::testXlogFile1Dbg1 (folly::StringPiece msg)
Definition at line 20 of file XlogFile1.cpp.
References XLOG.
Referenced by TEST_F(), and testXlogHdrLoop().
{
   XLOG(DBG1) << "file1: " << msg;
 }
void logging_test::testXlogFile2Dbg1 (folly::StringPiece msg)
Definition at line 20 of file XlogFile2.cpp.
References XLOG.
Referenced by TEST_F(), and testXlogHdrLoop().
{
   XLOG(DBG1, "file2: ", msg);
 }
void logging_test::testXlogHdrFunction (folly::StringPiece str, int value) inline
Definition at line 22 of file XlogHeader2.h.
References XLOG.
Referenced by TEST_F().
{
   XLOG(DBG3, "test: ", str, "=", value);
 }
void logging_test::testXlogHdrLoop (size_t numIters, folly::StringPiece arg) inline
Definition at line 24 of file XlogHeader1.h.
References testXlogFile1Dbg1(), testXlogFile2Dbg1(), and XLOGF.
Referenced by TEST_F().
{
   XLOGF(DBG1, "starting: {}", arg);
   for (size_t n = 0; n < numIters; ++n) {
     XLOGF(DBG5, "test: {}", arg);
   }
   XLOGF(DBG1, "finished: {}", arg);
 }