var namespacefolly =
[
    [ "array_detail", "namespacefolly_1_1array__detail.html", "namespacefolly_1_1array__detail" ],
    [ "bititerator_detail", "namespacefolly_1_1bititerator__detail.html", "namespacefolly_1_1bititerator__detail" ],
    [ "bser", "namespacefolly_1_1bser.html", "namespacefolly_1_1bser" ],
    [ "chrono", "namespacefolly_1_1chrono.html", "namespacefolly_1_1chrono" ],
    [ "cold_detail", "namespacefolly_1_1cold__detail.html", "namespacefolly_1_1cold__detail" ],
    [ "compression", "namespacefolly_1_1compression.html", "namespacefolly_1_1compression" ],
    [ "coro", "namespacefolly_1_1coro.html", "namespacefolly_1_1coro" ],
    [ "detail", "namespacefolly_1_1detail.html", "namespacefolly_1_1detail" ],
    [ "dptr_detail", "namespacefolly_1_1dptr__detail.html", "namespacefolly_1_1dptr__detail" ],
    [ "dynamicconverter_detail", "namespacefolly_1_1dynamicconverter__detail.html", "namespacefolly_1_1dynamicconverter__detail" ],
    [ "exception_tracer", "namespacefolly_1_1exception__tracer.html", "namespacefolly_1_1exception__tracer" ],
    [ "exception_wrapper_detail", "namespacefolly_1_1exception__wrapper__detail.html", "namespacefolly_1_1exception__wrapper__detail" ],
    [ "expected_detail", "namespacefolly_1_1expected__detail.html", "namespacefolly_1_1expected__detail" ],
    [ "experimental", "namespacefolly_1_1experimental.html", "namespacefolly_1_1experimental" ],
    [ "f14", "namespacefolly_1_1f14.html", "namespacefolly_1_1f14" ],
    [ "fibers", "namespacefolly_1_1fibers.html", "namespacefolly_1_1fibers" ],
    [ "for_each_detail", "namespacefolly_1_1for__each__detail.html", "namespacefolly_1_1for__each__detail" ],
    [ "futures", "namespacefolly_1_1futures.html", "namespacefolly_1_1futures" ],
    [ "gen", "namespacefolly_1_1gen.html", "namespacefolly_1_1gen" ],
    [ "hash", "namespacefolly_1_1hash.html", "namespacefolly_1_1hash" ],
    [ "invoke_detail", "namespacefolly_1_1invoke__detail.html", "namespacefolly_1_1invoke__detail" ],
    [ "io", "namespacefolly_1_1io.html", "namespacefolly_1_1io" ],
    [ "json", "namespacefolly_1_1json.html", "namespacefolly_1_1json" ],
    [ "jsonschema", "namespacefolly_1_1jsonschema.html", "namespacefolly_1_1jsonschema" ],
    [ "literals", "namespacefolly_1_1literals.html", null ],
    [ "logging", "namespacefolly_1_1logging.html", "namespacefolly_1_1logging" ],
    [ "moveonly_", "namespacefolly_1_1moveonly__.html", "namespacefolly_1_1moveonly__" ],
    [ "netops", "namespacefolly_1_1netops.html", "namespacefolly_1_1netops" ],
    [ "observer", "namespacefolly_1_1observer.html", "namespacefolly_1_1observer" ],
    [ "observer_detail", "namespacefolly_1_1observer__detail.html", "namespacefolly_1_1observer__detail" ],
    [ "padded", "namespacefolly_1_1padded.html", "namespacefolly_1_1padded" ],
    [ "parking_lot_detail", "namespacefolly_1_1parking__lot__detail.html", "namespacefolly_1_1parking__lot__detail" ],
    [ "poly", "namespacefolly_1_1poly.html", "namespacefolly_1_1poly" ],
    [ "portability", "namespacefolly_1_1portability.html", null ],
    [ "pushmi", "namespacefolly_1_1pushmi.html", "namespacefolly_1_1pushmi" ],
    [ "python", "namespacefolly_1_1python.html", "namespacefolly_1_1python" ],
    [ "recordio_helpers", "namespacefolly_1_1recordio__helpers.html", "namespacefolly_1_1recordio__helpers" ],
    [ "replaceable_detail", "namespacefolly_1_1replaceable__detail.html", "namespacefolly_1_1replaceable__detail" ],
    [ "settings", "namespacefolly_1_1settings.html", "namespacefolly_1_1settings" ],
    [ "ssl", "namespacefolly_1_1ssl.html", "namespacefolly_1_1ssl" ],
    [ "symbolizer", "namespacefolly_1_1symbolizer.html", "namespacefolly_1_1symbolizer" ],
    [ "sync_tests", "namespacefolly_1_1sync__tests.html", "namespacefolly_1_1sync__tests" ],
    [ "test", "namespacefolly_1_1test.html", "namespacefolly_1_1test" ],
    [ "threadlocal_detail", "namespacefolly_1_1threadlocal__detail.html", "namespacefolly_1_1threadlocal__detail" ],
    [ "traits_detail", "namespacefolly_1_1traits__detail.html", "namespacefolly_1_1traits__detail" ],
    [ "traits_detail_IsEqualityComparable", "namespacefolly_1_1traits__detail__IsEqualityComparable.html", "namespacefolly_1_1traits__detail__IsEqualityComparable" ],
    [ "traits_detail_IsLessThanComparable", "namespacefolly_1_1traits__detail__IsLessThanComparable.html", "namespacefolly_1_1traits__detail__IsLessThanComparable" ],
    [ "traits_detail_IsNothrowSwappable", "namespacefolly_1_1traits__detail__IsNothrowSwappable.html", "namespacefolly_1_1traits__detail__IsNothrowSwappable" ],
    [ "try_detail", "namespacefolly_1_1try__detail.html", "namespacefolly_1_1try__detail" ],
    [ "utility_detail", "namespacefolly_1_1utility__detail.html", "namespacefolly_1_1utility__detail" ],
    [ "AccessModeStrict", "structfolly_1_1AccessModeStrict.html", null ],
    [ "AccessSpreader", "structfolly_1_1AccessSpreader.html", "structfolly_1_1AccessSpreader" ],
    [ "AlignedSysAllocator", "classfolly_1_1AlignedSysAllocator.html", "classfolly_1_1AlignedSysAllocator" ],
    [ "allocator_delete", "classfolly_1_1allocator__delete.html", "classfolly_1_1allocator__delete" ],
    [ "AllocatorHasDefaultObjectConstruct", "structfolly_1_1AllocatorHasDefaultObjectConstruct.html", null ],
    [ "AllocatorHasDefaultObjectConstruct< std::allocator< Value >, T, Args... >", "structfolly_1_1AllocatorHasDefaultObjectConstruct_3_01std_1_1allocator_3_01Value_01_4_00_01T_00_01Args_8_8_8_01_4.html", null ],
    [ "AllocatorHasDefaultObjectDestroy", "structfolly_1_1AllocatorHasDefaultObjectDestroy.html", null ],
    [ "AllocatorHasDefaultObjectDestroy< std::allocator< Value >, T >", "structfolly_1_1AllocatorHasDefaultObjectDestroy_3_01std_1_1allocator_3_01Value_01_4_00_01T_01_4.html", null ],
    [ "AllocatorHasTrivialDeallocate", "structfolly_1_1AllocatorHasTrivialDeallocate.html", null ],
    [ "AllocatorHasTrivialDeallocate< Arena< Alloc > >", "structfolly_1_1AllocatorHasTrivialDeallocate_3_01Arena_3_01Alloc_01_4_01_4.html", null ],
    [ "AllocatorHasTrivialDeallocate< CxxAllocatorAdaptor< T, Alloc > >", "structfolly_1_1AllocatorHasTrivialDeallocate_3_01CxxAllocatorAdaptor_3_01T_00_01Alloc_01_4_01_4.html", null ],
    [ "AllocatorHasTrivialDeallocate< ParanoidArenaAlloc< ParentAlloc > >", "structfolly_1_1AllocatorHasTrivialDeallocate_3_01ParanoidArenaAlloc_3_01ParentAlloc_01_4_01_4.html", null ],
    [ "AllocatorHasTrivialDeallocate< SysArena >", "structfolly_1_1AllocatorHasTrivialDeallocate_3_01SysArena_01_4.html", null ],
    [ "AllocatorHasTrivialDeallocate< ThreadCachedArena >", "structfolly_1_1AllocatorHasTrivialDeallocate_3_01ThreadCachedArena_01_4.html", null ],
    [ "AlpnClient", "classfolly_1_1AlpnClient.html", "classfolly_1_1AlpnClient" ],
    [ "AlpnServer", "classfolly_1_1AlpnServer.html", "classfolly_1_1AlpnServer" ],
    [ "apply_result", "structfolly_1_1apply__result.html", null ],
    [ "ApplyInvoke", "structfolly_1_1ApplyInvoke.html", "structfolly_1_1ApplyInvoke" ],
    [ "Arena", "classfolly_1_1Arena.html", "classfolly_1_1Arena" ],
    [ "ArenaAllocatorTraits", "structfolly_1_1ArenaAllocatorTraits.html", "structfolly_1_1ArenaAllocatorTraits" ],
    [ "ArenaAllocatorTraits< SysAllocator< void > >", "structfolly_1_1ArenaAllocatorTraits_3_01SysAllocator_3_01void_01_4_01_4.html", "structfolly_1_1ArenaAllocatorTraits_3_01SysAllocator_3_01void_01_4_01_4" ],
    [ "AsciiCaseInsensitive", "structfolly_1_1AsciiCaseInsensitive.html", "structfolly_1_1AsciiCaseInsensitive" ],
    [ "AsciiCaseSensitive", "structfolly_1_1AsciiCaseSensitive.html", "structfolly_1_1AsciiCaseSensitive" ],
    [ "AsyncFileWriter", "classfolly_1_1AsyncFileWriter.html", "classfolly_1_1AsyncFileWriter" ],
    [ "AsyncIO", "classfolly_1_1AsyncIO.html", "classfolly_1_1AsyncIO" ],
    [ "AsyncIOOp", "classfolly_1_1AsyncIOOp.html", "classfolly_1_1AsyncIOOp" ],
    [ "AsyncIOQueue", "classfolly_1_1AsyncIOQueue.html", "classfolly_1_1AsyncIOQueue" ],
    [ "AsyncPipeReader", "classfolly_1_1AsyncPipeReader.html", "classfolly_1_1AsyncPipeReader" ],
    [ "AsyncPipeWriter", "classfolly_1_1AsyncPipeWriter.html", "classfolly_1_1AsyncPipeWriter" ],
    [ "AsyncReader", "classfolly_1_1AsyncReader.html", "classfolly_1_1AsyncReader" ],
    [ "AsyncServerSocket", "classfolly_1_1AsyncServerSocket.html", "classfolly_1_1AsyncServerSocket" ],
    [ "AsyncSignalHandler", "classfolly_1_1AsyncSignalHandler.html", "classfolly_1_1AsyncSignalHandler" ],
    [ "AsyncSocket", "classfolly_1_1AsyncSocket.html", "classfolly_1_1AsyncSocket" ],
    [ "AsyncSocketBase", "classfolly_1_1AsyncSocketBase.html", "classfolly_1_1AsyncSocketBase" ],
    [ "AsyncSocketException", "classfolly_1_1AsyncSocketException.html", "classfolly_1_1AsyncSocketException" ],
    [ "AsyncSSLSocket", "classfolly_1_1AsyncSSLSocket.html", "classfolly_1_1AsyncSSLSocket" ],
    [ "AsyncSSLSocketWriteTest", "classfolly_1_1AsyncSSLSocketWriteTest.html", "classfolly_1_1AsyncSSLSocketWriteTest" ],
    [ "AsyncTimeout", "classfolly_1_1AsyncTimeout.html", "classfolly_1_1AsyncTimeout" ],
    [ "AsyncTransport", "classfolly_1_1AsyncTransport.html", "classfolly_1_1AsyncTransport" ],
    [ "AsyncTransportCertificate", "classfolly_1_1AsyncTransportCertificate.html", "classfolly_1_1AsyncTransportCertificate" ],
    [ "AsyncTransportWrapper", "classfolly_1_1AsyncTransportWrapper.html", "classfolly_1_1AsyncTransportWrapper" ],
    [ "AsyncUDPServerSocket", "classfolly_1_1AsyncUDPServerSocket.html", "classfolly_1_1AsyncUDPServerSocket" ],
    [ "AsyncUDPSocket", "classfolly_1_1AsyncUDPSocket.html", "classfolly_1_1AsyncUDPSocket" ],
    [ "AsyncWriter", "classfolly_1_1AsyncWriter.html", "classfolly_1_1AsyncWriter" ],
    [ "atomic_shared_ptr", "classfolly_1_1atomic__shared__ptr.html", "classfolly_1_1atomic__shared__ptr" ],
    [ "AtomicBitSet", "classfolly_1_1AtomicBitSet.html", "classfolly_1_1AtomicBitSet" ],
    [ "AtomicCoreCachedSharedPtr", "classfolly_1_1AtomicCoreCachedSharedPtr.html", "classfolly_1_1AtomicCoreCachedSharedPtr" ],
    [ "AtomicFetchResetTest", "classfolly_1_1AtomicFetchResetTest.html", null ],
    [ "AtomicFetchSetTest", "classfolly_1_1AtomicFetchSetTest.html", null ],
    [ "AtomicHashArray", "classfolly_1_1AtomicHashArray.html", "classfolly_1_1AtomicHashArray" ],
    [ "AtomicHashArrayLinearProbeFcn", "structfolly_1_1AtomicHashArrayLinearProbeFcn.html", "structfolly_1_1AtomicHashArrayLinearProbeFcn" ],
    [ "AtomicHashArrayQuadraticProbeFcn", "structfolly_1_1AtomicHashArrayQuadraticProbeFcn.html", "structfolly_1_1AtomicHashArrayQuadraticProbeFcn" ],
    [ "AtomicHashMap", "classfolly_1_1AtomicHashMap.html", "classfolly_1_1AtomicHashMap" ],
    [ "AtomicHashMapFullError", "structfolly_1_1AtomicHashMapFullError.html", "structfolly_1_1AtomicHashMapFullError" ],
    [ "AtomicIntrusiveLinkedList", "classfolly_1_1AtomicIntrusiveLinkedList.html", "classfolly_1_1AtomicIntrusiveLinkedList" ],
    [ "AtomicIntrusiveLinkedListHook", "structfolly_1_1AtomicIntrusiveLinkedListHook.html", "structfolly_1_1AtomicIntrusiveLinkedListHook" ],
    [ "AtomicLinkedList", "classfolly_1_1AtomicLinkedList.html", "classfolly_1_1AtomicLinkedList" ],
    [ "AtomicStruct", "classfolly_1_1AtomicStruct.html", "classfolly_1_1AtomicStruct" ],
    [ "AtomicUnorderedInsertMap", "structfolly_1_1AtomicUnorderedInsertMap.html", "structfolly_1_1AtomicUnorderedInsertMap" ],
    [ "AttachDetachClient", "classfolly_1_1AttachDetachClient.html", "classfolly_1_1AttachDetachClient" ],
    [ "AutoTimer", "classfolly_1_1AutoTimer.html", "classfolly_1_1AutoTimer" ],
    [ "B", "structfolly_1_1B.html", null ],
    [ "BadExpectedAccess", "classfolly_1_1BadExpectedAccess.html", "classfolly_1_1BadExpectedAccess" ],
    [ "BadFormatArg", "classfolly_1_1BadFormatArg.html", null ],
    [ "BadPolyAccess", "structfolly_1_1BadPolyAccess.html", "structfolly_1_1BadPolyAccess" ],
    [ "BadPolyCast", "structfolly_1_1BadPolyCast.html", "structfolly_1_1BadPolyCast" ],
    [ "BaseFormatter", "classfolly_1_1BaseFormatter.html", "classfolly_1_1BaseFormatter" ],
    [ "basic_fbstring", "classfolly_1_1basic__fbstring.html", "classfolly_1_1basic__fbstring" ],
    [ "basic_once_flag", "classfolly_1_1basic__once__flag.html", "classfolly_1_1basic__once__flag" ],
    [ "BasicDynamicTokenBucket", "classfolly_1_1BasicDynamicTokenBucket.html", "classfolly_1_1BasicDynamicTokenBucket" ],
    [ "BasicFixedString", "classfolly_1_1BasicFixedString.html", "classfolly_1_1BasicFixedString" ],
    [ "BasicTokenBucket", "classfolly_1_1BasicTokenBucket.html", "classfolly_1_1BasicTokenBucket" ],
    [ "Baton", "classfolly_1_1Baton.html", "classfolly_1_1Baton" ],
    [ "BenchmarkSuspender", "structfolly_1_1BenchmarkSuspender.html", "structfolly_1_1BenchmarkSuspender" ],
    [ "BitIterator", "classfolly_1_1BitIterator.html", "classfolly_1_1BitIterator" ],
    [ "Bits", "structfolly_1_1Bits.html", "structfolly_1_1Bits" ],
    [ "BlockingQueue", "classfolly_1_1BlockingQueue.html", "classfolly_1_1BlockingQueue" ],
    [ "BlockingQueueAddResult", "structfolly_1_1BlockingQueueAddResult.html", "structfolly_1_1BlockingQueueAddResult" ],
    [ "BlockingWriteClient", "classfolly_1_1BlockingWriteClient.html", "classfolly_1_1BlockingWriteClient" ],
    [ "BlockingWriteServer", "classfolly_1_1BlockingWriteServer.html", "classfolly_1_1BlockingWriteServer" ],
    [ "Bools", "structfolly_1_1Bools.html", "structfolly_1_1Bools" ],
    [ "BrokenPromise", "classfolly_1_1BrokenPromise.html", "classfolly_1_1BrokenPromise" ],
    [ "BucketedTimeSeries", "classfolly_1_1BucketedTimeSeries.html", "classfolly_1_1BucketedTimeSeries" ],
    [ "CachelinePadded", "classfolly_1_1CachelinePadded.html", "classfolly_1_1CachelinePadded" ],
    [ "CacheLocality", "structfolly_1_1CacheLocality.html", "structfolly_1_1CacheLocality" ],
    [ "CalledProcessError", "classfolly_1_1CalledProcessError.html", "classfolly_1_1CalledProcessError" ],
    [ "Codel", "classfolly_1_1Codel.html", "classfolly_1_1Codel" ],
    [ "compare_equal_to", "structfolly_1_1compare__equal__to.html", null ],
    [ "compare_greater", "structfolly_1_1compare__greater.html", null ],
    [ "compare_greater_equal", "structfolly_1_1compare__greater__equal.html", null ],
    [ "compare_less", "structfolly_1_1compare__less.html", null ],
    [ "compare_less_equal", "structfolly_1_1compare__less__equal.html", null ],
    [ "compare_not_equal_to", "structfolly_1_1compare__not__equal__to.html", null ],
    [ "ConcurrentHashMap", "classfolly_1_1ConcurrentHashMap.html", "classfolly_1_1ConcurrentHashMap" ],
    [ "ConcurrentSkipList", "classfolly_1_1ConcurrentSkipList.html", "classfolly_1_1ConcurrentSkipList" ],
    [ "Conjunction", "structfolly_1_1Conjunction.html", null ],
    [ "Conjunction< T >", "structfolly_1_1Conjunction_3_01T_01_4.html", null ],
    [ "Conjunction< T, TList... >", "structfolly_1_1Conjunction_3_01T_00_01TList_8_8_8_01_4.html", null ],
    [ "ConnectClient", "classfolly_1_1ConnectClient.html", "classfolly_1_1ConnectClient" ],
    [ "ConnectTimeoutCallback", "classfolly_1_1ConnectTimeoutCallback.html", "classfolly_1_1ConnectTimeoutCallback" ],
    [ "constexpr_equal_to", "structfolly_1_1constexpr__equal__to.html", "structfolly_1_1constexpr__equal__to" ],
    [ "constexpr_greater", "structfolly_1_1constexpr__greater.html", "structfolly_1_1constexpr__greater" ],
    [ "constexpr_greater_equal", "structfolly_1_1constexpr__greater__equal.html", "structfolly_1_1constexpr__greater__equal" ],
    [ "constexpr_less", "structfolly_1_1constexpr__less.html", "structfolly_1_1constexpr__less" ],
    [ "constexpr_less_equal", "structfolly_1_1constexpr__less__equal.html", "structfolly_1_1constexpr__less__equal" ],
    [ "constexpr_not_equal_to", "structfolly_1_1constexpr__not__equal__to.html", "structfolly_1_1constexpr__not__equal__to" ],
    [ "ContainsExpected", "classfolly_1_1ContainsExpected.html", "classfolly_1_1ContainsExpected" ],
    [ "ConversionError", "classfolly_1_1ConversionError.html", "classfolly_1_1ConversionError" ],
    [ "ConversionErrorBase", "structfolly_1_1ConversionErrorBase.html", null ],
    [ "CopyCount", "structfolly_1_1CopyCount.html", "structfolly_1_1CopyCount" ],
    [ "CoreCachedSharedPtr", "classfolly_1_1CoreCachedSharedPtr.html", "classfolly_1_1CoreCachedSharedPtr" ],
    [ "CoreCachedWeakPtr", "classfolly_1_1CoreCachedWeakPtr.html", "classfolly_1_1CoreCachedWeakPtr" ],
    [ "CoreRawAllocator", "classfolly_1_1CoreRawAllocator.html", "classfolly_1_1CoreRawAllocator" ],
    [ "CpuId", "classfolly_1_1CpuId.html", "classfolly_1_1CpuId" ],
    [ "CPUThreadPoolExecutor", "classfolly_1_1CPUThreadPoolExecutor.html", "classfolly_1_1CPUThreadPoolExecutor" ],
    [ "custom_stop_watch", "structfolly_1_1custom__stop__watch.html", "structfolly_1_1custom__stop__watch" ],
    [ "CustomLogFormatter", "classfolly_1_1CustomLogFormatter.html", "classfolly_1_1CustomLogFormatter" ],
    [ "CxxAllocatorAdaptor", "classfolly_1_1CxxAllocatorAdaptor.html", "classfolly_1_1CxxAllocatorAdaptor" ],
    [ "CxxHugePageAllocator", "classfolly_1_1CxxHugePageAllocator.html", "classfolly_1_1CxxHugePageAllocator" ],
    [ "Data", "classfolly_1_1Data.html", "classfolly_1_1Data" ],
    [ "DecoratedAsyncTransportWrapper", "classfolly_1_1DecoratedAsyncTransportWrapper.html", "classfolly_1_1DecoratedAsyncTransportWrapper" ],
    [ "DefaultAlign", "classfolly_1_1DefaultAlign.html", "classfolly_1_1DefaultAlign" ],
    [ "DefaultKeepAliveExecutor", "classfolly_1_1DefaultKeepAliveExecutor.html", "classfolly_1_1DefaultKeepAliveExecutor" ],
    [ "DefaultWeightFn", "structfolly_1_1DefaultWeightFn.html", "structfolly_1_1DefaultWeightFn" ],
    [ "DelayedDestruction", "classfolly_1_1DelayedDestruction.html", "classfolly_1_1DelayedDestruction" ],
    [ "DelayedDestructionBase", "classfolly_1_1DelayedDestructionBase.html", "classfolly_1_1DelayedDestructionBase" ],
    [ "DestructorCheck", "classfolly_1_1DestructorCheck.html", "classfolly_1_1DestructorCheck" ],
    [ "DiscriminatedPtr", "classfolly_1_1DiscriminatedPtr.html", "classfolly_1_1DiscriminatedPtr" ],
    [ "Disjunction", "structfolly_1_1Disjunction.html", null ],
    [ "Disjunction< T >", "structfolly_1_1Disjunction_3_01T_01_4.html", null ],
    [ "Disjunction< T, TList... >", "structfolly_1_1Disjunction_3_01T_00_01TList_8_8_8_01_4.html", null ],
    [ "DrivableExecutor", "classfolly_1_1DrivableExecutor.html", "classfolly_1_1DrivableExecutor" ],
    [ "drop_unit", "structfolly_1_1drop__unit.html", "structfolly_1_1drop__unit" ],
    [ "drop_unit< Unit >", "structfolly_1_1drop__unit_3_01Unit_01_4.html", "structfolly_1_1drop__unit_3_01Unit_01_4" ],
    [ "dummy_fbstring_core", "classfolly_1_1dummy__fbstring__core.html", "classfolly_1_1dummy__fbstring__core" ],
    [ "dynamic", "structfolly_1_1dynamic.html", "structfolly_1_1dynamic" ],
    [ "DynamicBoundedQueue", "classfolly_1_1DynamicBoundedQueue.html", "classfolly_1_1DynamicBoundedQueue" ],
    [ "DynamicConstructor", "structfolly_1_1DynamicConstructor.html", "structfolly_1_1DynamicConstructor" ],
    [ "DynamicConstructor< C, typename std::enable_if< !std::is_same< C, dynamic >::value &&!dynamicconverter_detail::is_map< C >::value &&!std::is_constructible< StringPiece, const C & >::value &&dynamicconverter_detail::is_range< C >::value >::type >", "structfolly_1_1DynamicConstructor_3_01C_00_01typename_01std_1_1enable__if_3_01_9std_1_1is__same_9a99fe4ac10f6a5a35433c65df39f2b4.html", "structfolly_1_1DynamicConstructor_3_01C_00_01typename_01std_1_1enable__if_3_01_9std_1_1is__same_9a99fe4ac10f6a5a35433c65df39f2b4" ],
    [ "DynamicConstructor< C, typename std::enable_if< !std::is_same< C, dynamic >::value &&dynamicconverter_detail::is_map< C >::value >::type >", "structfolly_1_1DynamicConstructor_3_01C_00_01typename_01std_1_1enable__if_3_01_9std_1_1is__same_96efb2e6e0acb6b0ca0a5449884f07f6.html", "structfolly_1_1DynamicConstructor_3_01C_00_01typename_01std_1_1enable__if_3_01_9std_1_1is__same_96efb2e6e0acb6b0ca0a5449884f07f6" ],
    [ "DynamicConstructor< C, typename std::enable_if< std::is_same< C, dynamic >::value >::type >", "structfolly_1_1DynamicConstructor_3_01C_00_01typename_01std_1_1enable__if_3_01std_1_1is__same_3_4e4d3929fa6dca6e67a8065522b80544.html", "structfolly_1_1DynamicConstructor_3_01C_00_01typename_01std_1_1enable__if_3_01std_1_1is__same_3_4e4d3929fa6dca6e67a8065522b80544" ],
    [ "DynamicConstructor< std::pair< A, B >, void >", "structfolly_1_1DynamicConstructor_3_01std_1_1pair_3_01A_00_01B_01_4_00_01void_01_4.html", "structfolly_1_1DynamicConstructor_3_01std_1_1pair_3_01A_00_01B_01_4_00_01void_01_4" ],
    [ "DynamicConstructor< std::vector< bool >, void >", "structfolly_1_1DynamicConstructor_3_01std_1_1vector_3_01bool_01_4_00_01void_01_4.html", "structfolly_1_1DynamicConstructor_3_01std_1_1vector_3_01bool_01_4_00_01void_01_4" ],
    [ "DynamicConverter", "structfolly_1_1DynamicConverter.html", null ],
    [ "DynamicConverter< A >", "structfolly_1_1DynamicConverter_3_01A_01_4.html", "structfolly_1_1DynamicConverter_3_01A_01_4" ],
    [ "DynamicConverter< B >", "structfolly_1_1DynamicConverter_3_01B_01_4.html", "structfolly_1_1DynamicConverter_3_01B_01_4" ],
    [ "DynamicConverter< bool >", "structfolly_1_1DynamicConverter_3_01bool_01_4.html", "structfolly_1_1DynamicConverter_3_01bool_01_4" ],
    [ "DynamicConverter< C, typename std::enable_if< dynamicconverter_detail::is_container< C >::value &&!dynamicconverter_detail::is_associative< C >::value >::type >", "structfolly_1_1DynamicConverter_3_01C_00_01typename_01std_1_1enable__if_3_01dynamicconverter__de05b3a26b6200d2a8f0cf35f6f735633b.html", "structfolly_1_1DynamicConverter_3_01C_00_01typename_01std_1_1enable__if_3_01dynamicconverter__de05b3a26b6200d2a8f0cf35f6f735633b" ],
    [ "DynamicConverter< C, typename std::enable_if< dynamicconverter_detail::is_container< C >::value &&dynamicconverter_detail::is_associative< C >::value >::type >", "structfolly_1_1DynamicConverter_3_01C_00_01typename_01std_1_1enable__if_3_01dynamicconverter__de5c01e28ee4755f6ea66a2a8029f618c0.html", "structfolly_1_1DynamicConverter_3_01C_00_01typename_01std_1_1enable__if_3_01dynamicconverter__de5c01e28ee4755f6ea66a2a8029f618c0" ],
    [ "DynamicConverter< folly::fbstring >", "structfolly_1_1DynamicConverter_3_01folly_1_1fbstring_01_4.html", "structfolly_1_1DynamicConverter_3_01folly_1_1fbstring_01_4" ],
    [ "DynamicConverter< std::pair< F, S > >", "structfolly_1_1DynamicConverter_3_01std_1_1pair_3_01F_00_01S_01_4_01_4.html", "structfolly_1_1DynamicConverter_3_01std_1_1pair_3_01F_00_01S_01_4_01_4" ],
    [ "DynamicConverter< std::string >", "structfolly_1_1DynamicConverter_3_01std_1_1string_01_4.html", "structfolly_1_1DynamicConverter_3_01std_1_1string_01_4" ],
    [ "DynamicConverter< T, typename std::enable_if< std::is_enum< T >::value >::type >", "structfolly_1_1DynamicConverter_3_01T_00_01typename_01std_1_1enable__if_3_01std_1_1is__enum_3_017e338d44a8c365ca167354b666848ae4.html", "structfolly_1_1DynamicConverter_3_01T_00_01typename_01std_1_1enable__if_3_01std_1_1is__enum_3_017e338d44a8c365ca167354b666848ae4" ],
    [ "DynamicConverter< T, typename std::enable_if< std::is_floating_point< T >::value >::type >", "structfolly_1_1DynamicConverter_3_01T_00_01typename_01std_1_1enable__if_3_01std_1_1is__floating_599423fd6f3da1bcd5c9deb6648aac4f.html", "structfolly_1_1DynamicConverter_3_01T_00_01typename_01std_1_1enable__if_3_01std_1_1is__floating_599423fd6f3da1bcd5c9deb6648aac4f" ],
    [ "DynamicConverter< T, typename std::enable_if< std::is_integral< T >::value &&!std::is_same< T, bool >::value >::type >", "structfolly_1_1DynamicConverter_3_01T_00_01typename_01std_1_1enable__if_3_01std_1_1is__integral_465bb649c5d332623dacd880f0449a0c.html", "structfolly_1_1DynamicConverter_3_01T_00_01typename_01std_1_1enable__if_3_01std_1_1is__integral_465bb649c5d332623dacd880f0449a0c" ],
    [ "DynamicConverter< Token >", "structfolly_1_1DynamicConverter_3_01Token_01_4.html", "structfolly_1_1DynamicConverter_3_01Token_01_4" ],
    [ "DynamicParser", "classfolly_1_1DynamicParser.html", "classfolly_1_1DynamicParser" ],
    [ "DynamicParserLogicError", "structfolly_1_1DynamicParserLogicError.html", "structfolly_1_1DynamicParserLogicError" ],
    [ "DynamicParserParseError", "structfolly_1_1DynamicParserParseError.html", "structfolly_1_1DynamicParserParseError" ],
    [ "emplace_args", "structfolly_1_1emplace__args.html", "structfolly_1_1emplace__args" ],
    [ "EmptyReadCallback", "classfolly_1_1EmptyReadCallback.html", "classfolly_1_1EmptyReadCallback" ],
    [ "enable_if<(n<=0)>::type >", "structfolly_1_1TemplateRange_3_01T_00_01start_00_01n_00_01typename_01std_1_1enable__if_3_07n_3_0A0_08_4_1_1type_01_4.html", "structfolly_1_1TemplateRange_3_01T_00_01start_00_01n_00_01typename_01std_1_1enable__if_3_07n_3_0A0_08_4_1_1type_01_4" ],
    [ "enable_shared_from_this", "classfolly_1_1enable__shared__from__this.html", "classfolly_1_1enable__shared__from__this" ],
    [ "Endian", "classfolly_1_1Endian.html", "classfolly_1_1Endian" ],
    [ "EvbAndContext", "structfolly_1_1EvbAndContext.html", "structfolly_1_1EvbAndContext" ],
    [ "EventBase", "classfolly_1_1EventBase.html", "classfolly_1_1EventBase" ],
    [ "EventBaseAborter", "classfolly_1_1EventBaseAborter.html", "classfolly_1_1EventBaseAborter" ],
    [ "EventBaseLocal", "classfolly_1_1EventBaseLocal.html", "classfolly_1_1EventBaseLocal" ],
    [ "EventBaseManager", "classfolly_1_1EventBaseManager.html", "classfolly_1_1EventBaseManager" ],
    [ "EventBaseObserver", "classfolly_1_1EventBaseObserver.html", "classfolly_1_1EventBaseObserver" ],
    [ "EventBaseThread", "classfolly_1_1EventBaseThread.html", "classfolly_1_1EventBaseThread" ],
    [ "EventCount", "classfolly_1_1EventCount.html", "classfolly_1_1EventCount" ],
    [ "EventHandler", "classfolly_1_1EventHandler.html", "classfolly_1_1EventHandler" ],
    [ "EventUtil", "classfolly_1_1EventUtil.html", "classfolly_1_1EventUtil" ],
    [ "EvictingCacheMap", "classfolly_1_1EvictingCacheMap.html", "classfolly_1_1EvictingCacheMap" ],
    [ "exception_wrapper", "classfolly_1_1exception__wrapper.html", "classfolly_1_1exception__wrapper" ],
    [ "ExecutionObserver", "classfolly_1_1ExecutionObserver.html", "classfolly_1_1ExecutionObserver" ],
    [ "Executor", "classfolly_1_1Executor.html", "classfolly_1_1Executor" ],
    [ "Expected", "classfolly_1_1Expected.html", "classfolly_1_1Expected" ],
    [ "ExpectingDeleter", "structfolly_1_1ExpectingDeleter.html", "structfolly_1_1ExpectingDeleter" ],
    [ "ExpectWriteErrorCallback", "classfolly_1_1ExpectWriteErrorCallback.html", "classfolly_1_1ExpectWriteErrorCallback" ],
    [ "F14FastMap", "classfolly_1_1F14FastMap.html", null ],
    [ "F14FastSet", "classfolly_1_1F14FastSet.html", null ],
    [ "F14NodeMap", "classfolly_1_1F14NodeMap.html", "classfolly_1_1F14NodeMap" ],
    [ "F14NodeSet", "classfolly_1_1F14NodeSet.html", "classfolly_1_1F14NodeSet" ],
    [ "F14TableStats", "structfolly_1_1F14TableStats.html", "structfolly_1_1F14TableStats" ],
    [ "F14ValueMap", "classfolly_1_1F14ValueMap.html", "classfolly_1_1F14ValueMap" ],
    [ "F14ValueSet", "classfolly_1_1F14ValueSet.html", "classfolly_1_1F14ValueSet" ],
    [ "F14VectorMap", "classfolly_1_1F14VectorMap.html", "classfolly_1_1F14VectorMap" ],
    [ "F14VectorSet", "classfolly_1_1F14VectorSet.html", "classfolly_1_1F14VectorSet" ],
    [ "FakeAllPowerfulAssertingMutex", "classfolly_1_1FakeAllPowerfulAssertingMutex.html", "classfolly_1_1FakeAllPowerfulAssertingMutex" ],
    [ "FakeAllPowerfulAssertingMutexInternal", "classfolly_1_1FakeAllPowerfulAssertingMutexInternal.html", "classfolly_1_1FakeAllPowerfulAssertingMutexInternal" ],
    [ "FakeMutex", "classfolly_1_1FakeMutex.html", "classfolly_1_1FakeMutex" ],
    [ "FallbackGetcpu", "structfolly_1_1FallbackGetcpu.html", "structfolly_1_1FallbackGetcpu" ],
    [ "fbstring_core", "classfolly_1_1fbstring__core.html", "classfolly_1_1fbstring__core" ],
    [ "fbvector", "classfolly_1_1fbvector.html", "classfolly_1_1fbvector" ],
    [ "FcCustomExample", "classfolly_1_1FcCustomExample.html", "classfolly_1_1FcCustomExample" ],
    [ "FcSimpleExample", "classfolly_1_1FcSimpleExample.html", "classfolly_1_1FcSimpleExample" ],
    [ "FiberIOExecutor", "classfolly_1_1FiberIOExecutor.html", "classfolly_1_1FiberIOExecutor" ],
    [ "File", "classfolly_1_1File.html", "classfolly_1_1File" ],
    [ "FileHandlerFactory", "classfolly_1_1FileHandlerFactory.html", "classfolly_1_1FileHandlerFactory" ],
    [ "FileWriterFactory", "classfolly_1_1FileWriterFactory.html", "classfolly_1_1FileWriterFactory" ],
    [ "Fingerprint", "classfolly_1_1Fingerprint.html", "classfolly_1_1Fingerprint" ],
    [ "FixedAlign", "classfolly_1_1FixedAlign.html", "classfolly_1_1FixedAlign" ],
    [ "FlatCombining", "classfolly_1_1FlatCombining.html", "classfolly_1_1FlatCombining" ],
    [ "FormatArg", "structfolly_1_1FormatArg.html", "structfolly_1_1FormatArg" ],
    [ "FormatKeyNotFoundException", "classfolly_1_1FormatKeyNotFoundException.html", "classfolly_1_1FormatKeyNotFoundException" ],
    [ "Formatter", "classfolly_1_1Formatter.html", "classfolly_1_1Formatter" ],
    [ "FormatValue", "classfolly_1_1FormatValue.html", null ],
    [ "FormatValue< bool >", "classfolly_1_1FormatValue_3_01bool_01_4.html", "classfolly_1_1FormatValue_3_01bool_01_4" ],
    [ "FormatValue< detail::DefaultValueWrapper< dynamic, V > >", "classfolly_1_1FormatValue_3_01detail_1_1DefaultValueWrapper_3_01dynamic_00_01V_01_4_01_4.html", "classfolly_1_1FormatValue_3_01detail_1_1DefaultValueWrapper_3_01dynamic_00_01V_01_4_01_4" ],
    [ "FormatValue< double >", "classfolly_1_1FormatValue_3_01double_01_4.html", "classfolly_1_1FormatValue_3_01double_01_4" ],
    [ "FormatValue< dynamic >", "classfolly_1_1FormatValue_3_01dynamic_01_4.html", "classfolly_1_1FormatValue_3_01dynamic_01_4" ],
    [ "FormatValue< float >", "classfolly_1_1FormatValue_3_01float_01_4.html", "classfolly_1_1FormatValue_3_01float_01_4" ],
    [ "FormatValue< FormattableButNoToString >", "classfolly_1_1FormatValue_3_01FormattableButNoToString_01_4.html", "classfolly_1_1FormatValue_3_01FormattableButNoToString_01_4" ],
    [ "FormatValue< KeyValue >", "classfolly_1_1FormatValue_3_01KeyValue_01_4.html", "classfolly_1_1FormatValue_3_01KeyValue_01_4" ],
    [ "FormatValue< NoncopyableInt >", "classfolly_1_1FormatValue_3_01NoncopyableInt_01_4.html", "classfolly_1_1FormatValue_3_01NoncopyableInt_01_4" ],
    [ "FormatValue< T, typename std::enable_if< std::is_integral< T >::value &&!std::is_same< T, bool >::value >::type >", "classfolly_1_1FormatValue_3_01T_00_01typename_01std_1_1enable__if_3_01std_1_1is__integral_3_01T_bf75b24c2428ebfb2393908938b3b9ef.html", "classfolly_1_1FormatValue_3_01T_00_01typename_01std_1_1enable__if_3_01std_1_1is__integral_3_01T_bf75b24c2428ebfb2393908938b3b9ef" ],
    [ "FormatValue< ToStringFailure >", "classfolly_1_1FormatValue_3_01ToStringFailure_01_4.html", "classfolly_1_1FormatValue_3_01ToStringFailure_01_4" ],
    [ "Function", "classfolly_1_1Function.html", "classfolly_1_1Function" ],
    [ "FunctionRef", "classfolly_1_1FunctionRef.html", null ],
    [ "FunctionRef< ReturnType(Args...)>", "classfolly_1_1FunctionRef_3_01ReturnType_07Args_8_8_8_08_4.html", "classfolly_1_1FunctionRef_3_01ReturnType_07Args_8_8_8_08_4" ],
    [ "FunctionScheduler", "classfolly_1_1FunctionScheduler.html", "classfolly_1_1FunctionScheduler" ],
    [ "Future", "classfolly_1_1Future.html", "classfolly_1_1Future" ],
    [ "FutureAlreadyContinued", "classfolly_1_1FutureAlreadyContinued.html", "classfolly_1_1FutureAlreadyContinued" ],
    [ "FutureAlreadyRetrieved", "classfolly_1_1FutureAlreadyRetrieved.html", "classfolly_1_1FutureAlreadyRetrieved" ],
    [ "FutureCancellation", "classfolly_1_1FutureCancellation.html", "classfolly_1_1FutureCancellation" ],
    [ "FutureDAG", "classfolly_1_1FutureDAG.html", "classfolly_1_1FutureDAG" ],
    [ "FutureDAGFunctor", "classfolly_1_1FutureDAGFunctor.html", "classfolly_1_1FutureDAGFunctor" ],
    [ "FutureException", "classfolly_1_1FutureException.html", null ],
    [ "FutureExecutor", "classfolly_1_1FutureExecutor.html", "classfolly_1_1FutureExecutor" ],
    [ "FutureInvalid", "classfolly_1_1FutureInvalid.html", "classfolly_1_1FutureInvalid" ],
    [ "FutureNoExecutor", "classfolly_1_1FutureNoExecutor.html", "classfolly_1_1FutureNoExecutor" ],
    [ "FutureNoTimekeeper", "classfolly_1_1FutureNoTimekeeper.html", "classfolly_1_1FutureNoTimekeeper" ],
    [ "FutureNotReady", "classfolly_1_1FutureNotReady.html", "classfolly_1_1FutureNotReady" ],
    [ "FuturePredicateDoesNotObtain", "classfolly_1_1FuturePredicateDoesNotObtain.html", "classfolly_1_1FuturePredicateDoesNotObtain" ],
    [ "FutureSplitter", "classfolly_1_1FutureSplitter.html", "classfolly_1_1FutureSplitter" ],
    [ "FutureSplitterInvalid", "classfolly_1_1FutureSplitterInvalid.html", "classfolly_1_1FutureSplitterInvalid" ],
    [ "FutureTimeout", "classfolly_1_1FutureTimeout.html", "classfolly_1_1FutureTimeout" ],
    [ "Getcpu", "structfolly_1_1Getcpu.html", "structfolly_1_1Getcpu" ],
    [ "GlogStyleFormatter", "classfolly_1_1GlogStyleFormatter.html", "classfolly_1_1GlogStyleFormatter" ],
    [ "GoogleLogger", "structfolly_1_1GoogleLogger.html", "structfolly_1_1GoogleLogger" ],
    [ "GroupVarint", "classfolly_1_1GroupVarint.html", null ],
    [ "HandshakeCallback", "classfolly_1_1HandshakeCallback.html", "classfolly_1_1HandshakeCallback" ],
    [ "HandshakeErrorCallback", "classfolly_1_1HandshakeErrorCallback.html", "classfolly_1_1HandshakeErrorCallback" ],
    [ "HandshakeTimeoutCallback", "classfolly_1_1HandshakeTimeoutCallback.html", "classfolly_1_1HandshakeTimeoutCallback" ],
    [ "Hash", "structfolly_1_1Hash.html", "structfolly_1_1Hash" ],
    [ "hasher", "structfolly_1_1hasher.html", null ],
    [ "hasher< bool >", "structfolly_1_1hasher_3_01bool_01_4.html", "structfolly_1_1hasher_3_01bool_01_4" ],
    [ "hasher< char >", "structfolly_1_1hasher_3_01char_01_4.html", null ],
    [ "hasher< double >", "structfolly_1_1hasher_3_01double_01_4.html", null ],
    [ "hasher< float >", "structfolly_1_1hasher_3_01float_01_4.html", null ],
    [ "hasher< folly::Range< T * >, std::enable_if_t< std::is_integral< T >::value, void > >", "structfolly_1_1hasher_3_01folly_1_1Range_3_01T_01_5_01_4_00_01std_1_1enable__if__t_3_01std_1_1is42a6d1af553c53bd7b9a10e14d3edb55.html", "structfolly_1_1hasher_3_01folly_1_1Range_3_01T_01_5_01_4_00_01std_1_1enable__if__t_3_01std_1_1is42a6d1af553c53bd7b9a10e14d3edb55" ],
    [ "hasher< signed char >", "structfolly_1_1hasher_3_01signed_01char_01_4.html", null ],
    [ "hasher< signed int >", "structfolly_1_1hasher_3_01signed_01int_01_4.html", null ],
    [ "hasher< signed long >", "structfolly_1_1hasher_3_01signed_01long_01_4.html", null ],
    [ "hasher< signed long long >", "structfolly_1_1hasher_3_01signed_01long_01long_01_4.html", null ],
    [ "hasher< signed short >", "structfolly_1_1hasher_3_01signed_01short_01_4.html", null ],
    [ "hasher< std::pair< T1, T2 > >", "structfolly_1_1hasher_3_01std_1_1pair_3_01T1_00_01T2_01_4_01_4.html", "structfolly_1_1hasher_3_01std_1_1pair_3_01T1_00_01T2_01_4_01_4" ],
    [ "hasher< std::string >", "structfolly_1_1hasher_3_01std_1_1string_01_4.html", "structfolly_1_1hasher_3_01std_1_1string_01_4" ],
    [ "hasher< std::tuple< Ts... > >", "structfolly_1_1hasher_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", "structfolly_1_1hasher_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4" ],
    [ "hasher< T, std::enable_if_t< std::is_enum< T >::value > >", "structfolly_1_1hasher_3_01T_00_01std_1_1enable__if__t_3_01std_1_1is__enum_3_01T_01_4_1_1value_01_4_01_4.html", "structfolly_1_1hasher_3_01T_00_01std_1_1enable__if__t_3_01std_1_1is__enum_3_01T_01_4_1_1value_01_4_01_4" ],
    [ "hasher< unsigned char >", "structfolly_1_1hasher_3_01unsigned_01char_01_4.html", null ],
    [ "hasher< unsigned int >", "structfolly_1_1hasher_3_01unsigned_01int_01_4.html", null ],
    [ "hasher< unsigned long >", "structfolly_1_1hasher_3_01unsigned_01long_01_4.html", null ],
    [ "hasher< unsigned long long >", "structfolly_1_1hasher_3_01unsigned_01long_01long_01_4.html", null ],
    [ "hasher< unsigned short >", "structfolly_1_1hasher_3_01unsigned_01short_01_4.html", null ],
    [ "HashingThreadId", "structfolly_1_1HashingThreadId.html", "structfolly_1_1HashingThreadId" ],
    [ "hazptr_array", "classfolly_1_1hazptr__array.html", "classfolly_1_1hazptr__array" ],
    [ "hazptr_default_domain_helper", "structfolly_1_1hazptr__default__domain__helper.html", "structfolly_1_1hazptr__default__domain__helper" ],
    [ "hazptr_default_domain_helper< std::atomic >", "structfolly_1_1hazptr__default__domain__helper_3_01std_1_1atomic_01_4.html", "structfolly_1_1hazptr__default__domain__helper_3_01std_1_1atomic_01_4" ],
    [ "hazptr_deleter", "classfolly_1_1hazptr__deleter.html", "classfolly_1_1hazptr__deleter" ],
    [ "hazptr_deleter< T, std::default_delete< T > >", "classfolly_1_1hazptr__deleter_3_01T_00_01std_1_1default__delete_3_01T_01_4_01_4.html", "classfolly_1_1hazptr__deleter_3_01T_00_01std_1_1default__delete_3_01T_01_4_01_4" ],
    [ "hazptr_domain", "classfolly_1_1hazptr__domain.html", "classfolly_1_1hazptr__domain" ],
    [ "hazptr_holder", "classfolly_1_1hazptr__holder.html", "classfolly_1_1hazptr__holder" ],
    [ "hazptr_local", "classfolly_1_1hazptr__local.html", "classfolly_1_1hazptr__local" ],
    [ "hazptr_obj", "classfolly_1_1hazptr__obj.html", "classfolly_1_1hazptr__obj" ],
    [ "hazptr_obj_base", "classfolly_1_1hazptr__obj__base.html", "classfolly_1_1hazptr__obj__base" ],
    [ "hazptr_obj_base_linked", "classfolly_1_1hazptr__obj__base__linked.html", "classfolly_1_1hazptr__obj__base__linked" ],
    [ "hazptr_obj_linked", "classfolly_1_1hazptr__obj__linked.html", "classfolly_1_1hazptr__obj__linked" ],
    [ "hazptr_obj_list", "classfolly_1_1hazptr__obj__list.html", "classfolly_1_1hazptr__obj__list" ],
    [ "hazptr_priv", "classfolly_1_1hazptr__priv.html", null ],
    [ "hazptr_rec", "classfolly_1_1hazptr__rec.html", "classfolly_1_1hazptr__rec" ],
    [ "hazptr_root", "classfolly_1_1hazptr__root.html", "classfolly_1_1hazptr__root" ],
    [ "hazptr_tc", "classfolly_1_1hazptr__tc.html", null ],
    [ "hazptr_tc_entry", "classfolly_1_1hazptr__tc__entry.html", null ],
    [ "HazptrLockFreeLIFO", "classfolly_1_1HazptrLockFreeLIFO.html", "classfolly_1_1HazptrLockFreeLIFO" ],
    [ "HazptrSWMRSet", "classfolly_1_1HazptrSWMRSet.html", "classfolly_1_1HazptrSWMRSet" ],
    [ "HazptrWideCAS", "classfolly_1_1HazptrWideCAS.html", "classfolly_1_1HazptrWideCAS" ],
    [ "HeterogeneousAccessEqualTo", "structfolly_1_1HeterogeneousAccessEqualTo.html", null ],
    [ "HeterogeneousAccessEqualTo< T, std::enable_if_t< detail::TransparentlyConvertibleToRange< T >::value > >", "structfolly_1_1HeterogeneousAccessEqualTo_3_01T_00_01std_1_1enable__if__t_3_01detail_1_1Transpar0cd3c387fc86ebed9ed8ce6491f3ee58.html", null ],
    [ "HeterogeneousAccessHash", "structfolly_1_1HeterogeneousAccessHash.html", "structfolly_1_1HeterogeneousAccessHash" ],
    [ "HeterogeneousAccessHash< T, std::enable_if_t< detail::TransparentlyConvertibleToRange< T >::value > >", "structfolly_1_1HeterogeneousAccessHash_3_01T_00_01std_1_1enable__if__t_3_01detail_1_1Transparent2c930fd3ba3933df3a37b0b0af7df901.html", null ],
    [ "HHWheelTimer", "classfolly_1_1HHWheelTimer.html", "classfolly_1_1HHWheelTimer" ],
    [ "Histogram", "classfolly_1_1Histogram.html", "classfolly_1_1Histogram" ],
    [ "HugePageSize", "structfolly_1_1HugePageSize.html", "structfolly_1_1HugePageSize" ],
    [ "Identity", "structfolly_1_1Identity.html", "structfolly_1_1Identity" ],
    [ "Ignore", "structfolly_1_1Ignore.html", "structfolly_1_1Ignore" ],
    [ "ImmediateFileWriter", "classfolly_1_1ImmediateFileWriter.html", "classfolly_1_1ImmediateFileWriter" ],
    [ "in_place_index_tag", "structfolly_1_1in__place__index__tag.html", null ],
    [ "in_place_tag", "structfolly_1_1in__place__tag.html", null ],
    [ "in_place_type_tag", "structfolly_1_1in__place__type__tag.html", null ],
    [ "Indestructible", "classfolly_1_1Indestructible.html", "classfolly_1_1Indestructible" ],
    [ "IndexedMemPool", "structfolly_1_1IndexedMemPool.html", "structfolly_1_1IndexedMemPool" ],
    [ "IndexedMemPoolTraits", "structfolly_1_1IndexedMemPoolTraits.html", "structfolly_1_1IndexedMemPoolTraits" ],
    [ "Init", "classfolly_1_1Init.html", "classfolly_1_1Init" ],
    [ "initlist_construct_t", "structfolly_1_1initlist__construct__t.html", null ],
    [ "InitThreadFactory", "classfolly_1_1InitThreadFactory.html", "classfolly_1_1InitThreadFactory" ],
    [ "InlineExecutor", "classfolly_1_1InlineExecutor.html", "classfolly_1_1InlineExecutor" ],
    [ "integer_sequence", "structfolly_1_1integer__sequence.html", "structfolly_1_1integer__sequence" ],
    [ "InvalidAddressFamilyException", "classfolly_1_1InvalidAddressFamilyException.html", "classfolly_1_1InvalidAddressFamilyException" ],
    [ "invoke_result", "structfolly_1_1invoke__result.html", null ],
    [ "IOBuf", "classfolly_1_1IOBuf.html", "classfolly_1_1IOBuf" ],
    [ "IOBufCompare", "structfolly_1_1IOBufCompare.html", "structfolly_1_1IOBufCompare" ],
    [ "IOBufEqualTo", "structfolly_1_1IOBufEqualTo.html", null ],
    [ "IOBufGreater", "structfolly_1_1IOBufGreater.html", null ],
    [ "IOBufGreaterEqual", "structfolly_1_1IOBufGreaterEqual.html", null ],
    [ "IOBufHash", "structfolly_1_1IOBufHash.html", "structfolly_1_1IOBufHash" ],
    [ "IOBufLess", "structfolly_1_1IOBufLess.html", null ],
    [ "IOBufLessEqual", "structfolly_1_1IOBufLessEqual.html", null ],
    [ "IOBufNotEqualTo", "structfolly_1_1IOBufNotEqualTo.html", null ],
    [ "IOBufQueue", "classfolly_1_1IOBufQueue.html", "classfolly_1_1IOBufQueue" ],
    [ "IOExecutor", "classfolly_1_1IOExecutor.html", "classfolly_1_1IOExecutor" ],
    [ "IOObjectCache", "classfolly_1_1IOObjectCache.html", "classfolly_1_1IOObjectCache" ],
    [ "IOThreadPoolExecutor", "classfolly_1_1IOThreadPoolExecutor.html", "classfolly_1_1IOThreadPoolExecutor" ],
    [ "IPAddressFormatException", "classfolly_1_1IPAddressFormatException.html", "classfolly_1_1IPAddressFormatException" ],
    [ "IPAddressV4", "classfolly_1_1IPAddressV4.html", "classfolly_1_1IPAddressV4" ],
    [ "IPAddressV6", "classfolly_1_1IPAddressV6.html", "classfolly_1_1IPAddressV6" ],
    [ "is_applicable", "structfolly_1_1is__applicable.html", null ],
    [ "is_applicable_r", "structfolly_1_1is__applicable__r.html", null ],
    [ "is_invocable", "structfolly_1_1is__invocable.html", null ],
    [ "is_invocable_r", "structfolly_1_1is__invocable__r.html", null ],
    [ "is_nothrow_applicable", "structfolly_1_1is__nothrow__applicable.html", null ],
    [ "is_nothrow_applicable_r", "structfolly_1_1is__nothrow__applicable__r.html", null ],
    [ "is_nothrow_invocable", "structfolly_1_1is__nothrow__invocable.html", null ],
    [ "is_nothrow_invocable_r", "structfolly_1_1is__nothrow__invocable__r.html", null ],
    [ "is_replaceable", "structfolly_1_1is__replaceable.html", null ],
    [ "is_replaceable< Replaceable< T > >", "structfolly_1_1is__replaceable_3_01Replaceable_3_01T_01_4_01_4.html", null ],
    [ "IsAvalanchingHasher", "structfolly_1_1IsAvalanchingHasher.html", null ],
    [ "IsAvalanchingHasher< Hash, K >", "structfolly_1_1IsAvalanchingHasher_3_01Hash_00_01K_01_4.html", null ],
    [ "IsAvalanchingHasher< hasher< bool >, K >", "structfolly_1_1IsAvalanchingHasher_3_01hasher_3_01bool_01_4_00_01K_01_4.html", null ],
    [ "IsAvalanchingHasher< hasher< std::string >, K >", "structfolly_1_1IsAvalanchingHasher_3_01hasher_3_01std_1_1string_01_4_00_01K_01_4.html", null ],
    [ "IsAvalanchingHasher< hasher< std::tuple< T > >, K >", "structfolly_1_1IsAvalanchingHasher_3_01hasher_3_01std_1_1tuple_3_01T_01_4_01_4_00_01K_01_4.html", null ],
    [ "IsAvalanchingHasher< hasher< std::tuple< T1, T2, Ts... > >, K >", "structfolly_1_1IsAvalanchingHasher_3_01hasher_3_01std_1_1tuple_3_01T1_00_01T2_00_01Ts_8_8_8_01_4_01_4_00_01K_01_4.html", null ],
    [ "IsAvalanchingHasher< hasher< T, std::enable_if_t< std::is_enum< T >::value > >, K >", "structfolly_1_1IsAvalanchingHasher_3_01hasher_3_01T_00_01std_1_1enable__if__t_3_01std_1_1is__enu005668421023e04587be61a36d9e0651.html", null ],
    [ "IsAvalanchingHasher< std::hash< std::basic_string< Args... > >, K >", "structfolly_1_1IsAvalanchingHasher_3_01std_1_1hash_3_01std_1_1basic__string_3_01Args_8_8_8_01_4_01_4_00_01K_01_4.html", null ],
    [ "IsAvalanchingHasher< transparent< H >, K >", "structfolly_1_1IsAvalanchingHasher_3_01transparent_3_01H_01_4_00_01K_01_4.html", null ],
    [ "IsConvertible", "structfolly_1_1IsConvertible.html", null ],
    [ "isFuture", "structfolly_1_1isFuture.html", "structfolly_1_1isFuture" ],
    [ "isFuture< Future< T > >", "structfolly_1_1isFuture_3_01Future_3_01T_01_4_01_4.html", "structfolly_1_1isFuture_3_01Future_3_01T_01_4_01_4" ],
    [ "isFutureOrSemiFuture", "structfolly_1_1isFutureOrSemiFuture.html", "structfolly_1_1isFutureOrSemiFuture" ],
    [ "isFutureOrSemiFuture< Future< T > >", "structfolly_1_1isFutureOrSemiFuture_3_01Future_3_01T_01_4_01_4.html", "structfolly_1_1isFutureOrSemiFuture_3_01Future_3_01T_01_4_01_4" ],
    [ "isFutureOrSemiFuture< SemiFuture< T > >", "structfolly_1_1isFutureOrSemiFuture_3_01SemiFuture_3_01T_01_4_01_4.html", "structfolly_1_1isFutureOrSemiFuture_3_01SemiFuture_3_01T_01_4_01_4" ],
    [ "IsRelocatable", "structfolly_1_1IsRelocatable.html", null ],
    [ "IsRelocatable< Data< f, pad > >", "structfolly_1_1IsRelocatable_3_01Data_3_01f_00_01pad_01_4_01_4.html", null ],
    [ "IsRelocatable< std::basic_string< T1, T2, T3 > >", "structfolly_1_1IsRelocatable_3_01std_1_1basic__string_3_01T1_00_01T2_00_01T3_01_4_01_4.html", null ],
    [ "IsRelocatable< std::deque< T1, T2 > >", "structfolly_1_1IsRelocatable_3_01std_1_1deque_3_01T1_00_01T2_01_4_01_4.html", null ],
    [ "IsRelocatable< std::function< T1 > >", "structfolly_1_1IsRelocatable_3_01std_1_1function_3_01T1_01_4_01_4.html", null ],
    [ "IsRelocatable< std::pair< T, U > >", "structfolly_1_1IsRelocatable_3_01std_1_1pair_3_01T_00_01U_01_4_01_4.html", null ],
    [ "IsRelocatable< std::shared_ptr< T1 > >", "structfolly_1_1IsRelocatable_3_01std_1_1shared__ptr_3_01T1_01_4_01_4.html", null ],
    [ "IsRelocatable< std::unique_ptr< T1, T2 > >", "structfolly_1_1IsRelocatable_3_01std_1_1unique__ptr_3_01T1_00_01T2_01_4_01_4.html", null ],
    [ "IsRelocatable< std::vector< T1, T2 > >", "structfolly_1_1IsRelocatable_3_01std_1_1vector_3_01T1_00_01T2_01_4_01_4.html", null ],
    [ "IsRelocatable< T1 >", "structfolly_1_1IsRelocatable_3_01T1_01_4.html", null ],
    [ "isSemiFuture", "structfolly_1_1isSemiFuture.html", "structfolly_1_1isSemiFuture" ],
    [ "isSemiFuture< SemiFuture< T > >", "structfolly_1_1isSemiFuture_3_01SemiFuture_3_01T_01_4_01_4.html", "structfolly_1_1isSemiFuture_3_01SemiFuture_3_01T_01_4_01_4" ],
    [ "IsSomeString", "structfolly_1_1IsSomeString.html", null ],
    [ "IsSomeString< fbstring >", "structfolly_1_1IsSomeString_3_01fbstring_01_4.html", null ],
    [ "IsSomeString< std::string >", "structfolly_1_1IsSomeString_3_01std_1_1string_01_4.html", null ],
    [ "isTry", "structfolly_1_1isTry.html", null ],
    [ "isTry< Try< T > >", "structfolly_1_1isTry_3_01Try_3_01T_01_4_01_4.html", null ],
    [ "IsZeroInitializable", "structfolly_1_1IsZeroInitializable.html", null ],
    [ "JemallocHugePageAllocator", "classfolly_1_1JemallocHugePageAllocator.html", "classfolly_1_1JemallocHugePageAllocator" ],
    [ "JemallocNodumpAllocator", "classfolly_1_1JemallocNodumpAllocator.html", "classfolly_1_1JemallocNodumpAllocator" ],
    [ "json_patch", "classfolly_1_1json__patch.html", "classfolly_1_1json__patch" ],
    [ "json_pointer", "classfolly_1_1json__pointer.html", "classfolly_1_1json__pointer" ],
    [ "KeepAliveTestExecutor", "classfolly_1_1KeepAliveTestExecutor.html", "classfolly_1_1KeepAliveTestExecutor" ],
    [ "LeakySingleton", "classfolly_1_1LeakySingleton.html", "classfolly_1_1LeakySingleton" ],
    [ "LegacyStatsClock", "classfolly_1_1LegacyStatsClock.html", "classfolly_1_1LegacyStatsClock" ],
    [ "LifoSemImpl", "structfolly_1_1LifoSemImpl.html", "structfolly_1_1LifoSemImpl" ],
    [ "LifoSemMPMCQueue", "classfolly_1_1LifoSemMPMCQueue.html", "classfolly_1_1LifoSemMPMCQueue" ],
    [ "lift_unit", "structfolly_1_1lift__unit.html", "structfolly_1_1lift__unit" ],
    [ "lift_unit< void >", "structfolly_1_1lift__unit_3_01void_01_4.html", "structfolly_1_1lift__unit_3_01void_01_4" ],
    [ "like", "structfolly_1_1like.html", "structfolly_1_1like" ],
    [ "Line", "structfolly_1_1Line.html", "structfolly_1_1Line" ],
    [ "LockedPtr", "classfolly_1_1LockedPtr.html", "classfolly_1_1LockedPtr" ],
    [ "LockedPtrBase", "classfolly_1_1LockedPtrBase.html", "classfolly_1_1LockedPtrBase" ],
    [ "LockedPtrBase< SynchronizedType, std::mutex, LockPolicy >", "classfolly_1_1LockedPtrBase_3_01SynchronizedType_00_01std_1_1mutex_00_01LockPolicy_01_4.html", "classfolly_1_1LockedPtrBase_3_01SynchronizedType_00_01std_1_1mutex_00_01LockPolicy_01_4" ],
    [ "LockFreeRingBuffer", "classfolly_1_1LockFreeRingBuffer.html", "classfolly_1_1LockFreeRingBuffer" ],
    [ "LockPolicyExclusive", "structfolly_1_1LockPolicyExclusive.html", "structfolly_1_1LockPolicyExclusive" ],
    [ "LockPolicyFromExclusiveToShared", "structfolly_1_1LockPolicyFromExclusiveToShared.html", "structfolly_1_1LockPolicyFromExclusiveToShared" ],
    [ "LockPolicyFromExclusiveToUpgrade", "structfolly_1_1LockPolicyFromExclusiveToUpgrade.html", "structfolly_1_1LockPolicyFromExclusiveToUpgrade" ],
    [ "LockPolicyFromUpgradeToExclusive", "structfolly_1_1LockPolicyFromUpgradeToExclusive.html", "structfolly_1_1LockPolicyFromUpgradeToExclusive" ],
    [ "LockPolicyFromUpgradeToShared", "structfolly_1_1LockPolicyFromUpgradeToShared.html", "structfolly_1_1LockPolicyFromUpgradeToShared" ],
    [ "LockPolicyShared", "structfolly_1_1LockPolicyShared.html", "structfolly_1_1LockPolicyShared" ],
    [ "LockPolicyTryExclusive", "structfolly_1_1LockPolicyTryExclusive.html", "structfolly_1_1LockPolicyTryExclusive" ],
    [ "LockPolicyTryShared", "structfolly_1_1LockPolicyTryShared.html", "structfolly_1_1LockPolicyTryShared" ],
    [ "LockPolicyTryUpgrade", "structfolly_1_1LockPolicyTryUpgrade.html", "structfolly_1_1LockPolicyTryUpgrade" ],
    [ "LockPolicyUpgrade", "structfolly_1_1LockPolicyUpgrade.html", "structfolly_1_1LockPolicyUpgrade" ],
    [ "LockTraits", "structfolly_1_1LockTraits.html", null ],
    [ "LockTraitsBase", "structfolly_1_1LockTraitsBase.html", null ],
    [ "LogCategory", "classfolly_1_1LogCategory.html", "classfolly_1_1LogCategory" ],
    [ "LogCategoryConfig", "classfolly_1_1LogCategoryConfig.html", "classfolly_1_1LogCategoryConfig" ],
    [ "LogConfig", "classfolly_1_1LogConfig.html", "classfolly_1_1LogConfig" ],
    [ "LogConfigParseError", "classfolly_1_1LogConfigParseError.html", null ],
    [ "LogFormatter", "classfolly_1_1LogFormatter.html", "classfolly_1_1LogFormatter" ],
    [ "Logger", "classfolly_1_1Logger.html", "classfolly_1_1Logger" ],
    [ "LoggerDB", "classfolly_1_1LoggerDB.html", "classfolly_1_1LoggerDB" ],
    [ "LogHandler", "classfolly_1_1LogHandler.html", "classfolly_1_1LogHandler" ],
    [ "LogHandlerConfig", "classfolly_1_1LogHandlerConfig.html", "classfolly_1_1LogHandlerConfig" ],
    [ "LogHandlerFactory", "classfolly_1_1LogHandlerFactory.html", "classfolly_1_1LogHandlerFactory" ],
    [ "LogMessage", "classfolly_1_1LogMessage.html", "classfolly_1_1LogMessage" ],
    [ "LogName", "classfolly_1_1LogName.html", "classfolly_1_1LogName" ],
    [ "LogStream", "classfolly_1_1LogStream.html", "classfolly_1_1LogStream" ],
    [ "LogStreamBuffer", "classfolly_1_1LogStreamBuffer.html", "classfolly_1_1LogStreamBuffer" ],
    [ "LogStreamProcessor", "classfolly_1_1LogStreamProcessor.html", "classfolly_1_1LogStreamProcessor" ],
    [ "LogStreamVoidify", "classfolly_1_1LogStreamVoidify.html", "classfolly_1_1LogStreamVoidify" ],
    [ "LogStreamVoidify< true >", "classfolly_1_1LogStreamVoidify_3_01true_01_4.html", "classfolly_1_1LogStreamVoidify_3_01true_01_4" ],
    [ "LogWriter", "classfolly_1_1LogWriter.html", "classfolly_1_1LogWriter" ],
    [ "MacAddress", "classfolly_1_1MacAddress.html", "classfolly_1_1MacAddress" ],
    [ "ManualExecutor", "classfolly_1_1ManualExecutor.html", "classfolly_1_1ManualExecutor" ],
    [ "max_align_t", "structfolly_1_1max__align__t.html", null ],
    [ "MemoryIdlerTimeout", "classfolly_1_1MemoryIdlerTimeout.html", "classfolly_1_1MemoryIdlerTimeout" ],
    [ "MemoryMapping", "classfolly_1_1MemoryMapping.html", "classfolly_1_1MemoryMapping" ],
    [ "MicroLockBase", "classfolly_1_1MicroLockBase.html", "classfolly_1_1MicroLockBase" ],
    [ "MicroLockCore", "classfolly_1_1MicroLockCore.html", "classfolly_1_1MicroLockCore" ],
    [ "MicroSpinLock", "structfolly_1_1MicroSpinLock.html", "structfolly_1_1MicroSpinLock" ],
    [ "MockAsyncSSLSocket", "classfolly_1_1MockAsyncSSLSocket.html", "classfolly_1_1MockAsyncSSLSocket" ],
    [ "MoveTester", "classfolly_1_1MoveTester.html", "classfolly_1_1MoveTester" ],
    [ "MoveWrapper", "classfolly_1_1MoveWrapper.html", "classfolly_1_1MoveWrapper" ],
    [ "MPMCPipeline", "classfolly_1_1MPMCPipeline.html", "classfolly_1_1MPMCPipeline" ],
    [ "MPMCPipelineStage", "classfolly_1_1MPMCPipelineStage.html", "classfolly_1_1MPMCPipelineStage" ],
    [ "MPMCQueue", "classfolly_1_1MPMCQueue.html", "classfolly_1_1MPMCQueue" ],
    [ "MPMCQueue< T, Atom, true >", "classfolly_1_1MPMCQueue_3_01T_00_01Atom_00_01true_01_4.html", "classfolly_1_1MPMCQueue_3_01T_00_01Atom_00_01true_01_4" ],
    [ "MultiLevelTimeSeries", "classfolly_1_1MultiLevelTimeSeries.html", "classfolly_1_1MultiLevelTimeSeries" ],
    [ "MutableAtom", "structfolly_1_1MutableAtom.html", "structfolly_1_1MutableAtom" ],
    [ "MutableData", "structfolly_1_1MutableData.html", "structfolly_1_1MutableData" ],
    [ "NamedThreadFactory", "classfolly_1_1NamedThreadFactory.html", "classfolly_1_1NamedThreadFactory" ],
    [ "Negation", "structfolly_1_1Negation.html", null ],
    [ "NestedCommandLineApp", "classfolly_1_1NestedCommandLineApp.html", "classfolly_1_1NestedCommandLineApp" ],
    [ "NestedCommandLineParseResult", "structfolly_1_1NestedCommandLineParseResult.html", "structfolly_1_1NestedCommandLineParseResult" ],
    [ "NetworkSocket", "structfolly_1_1NetworkSocket.html", "structfolly_1_1NetworkSocket" ],
    [ "NoConstructor", "structfolly_1_1NoConstructor.html", null ],
    [ "NoDefault", "structfolly_1_1NoDefault.html", "structfolly_1_1NoDefault" ],
    [ "NoDestructor", "structfolly_1_1NoDestructor.html", null ],
    [ "NonDefaultConstructibleMutex", "classfolly_1_1NonDefaultConstructibleMutex.html", "classfolly_1_1NonDefaultConstructibleMutex" ],
    [ "None", "structfolly_1_1None.html", "structfolly_1_1None" ],
    [ "NoopReadCallback", "classfolly_1_1NoopReadCallback.html", "classfolly_1_1NoopReadCallback" ],
    [ "NoSelfAssign", "structfolly_1_1NoSelfAssign.html", "structfolly_1_1NoSelfAssign" ],
    [ "NotificationQueue", "classfolly_1_1NotificationQueue.html", "classfolly_1_1NotificationQueue" ],
    [ "Optional", "classfolly_1_1Optional.html", "classfolly_1_1Optional" ],
    [ "OptionalEmptyException", "classfolly_1_1OptionalEmptyException.html", "classfolly_1_1OptionalEmptyException" ],
    [ "PackedSyncPtr", "classfolly_1_1PackedSyncPtr.html", "classfolly_1_1PackedSyncPtr" ],
    [ "ParkingLot", "classfolly_1_1ParkingLot.html", "classfolly_1_1ParkingLot" ],
    [ "PasswordCollector", "classfolly_1_1PasswordCollector.html", "classfolly_1_1PasswordCollector" ],
    [ "PasswordInFile", "classfolly_1_1PasswordInFile.html", "classfolly_1_1PasswordInFile" ],
    [ "PicoSpinLock", "structfolly_1_1PicoSpinLock.html", "structfolly_1_1PicoSpinLock" ],
    [ "Poly", "structfolly_1_1Poly.html", "structfolly_1_1Poly" ],
    [ "PolyExtends", "structfolly_1_1PolyExtends.html", "structfolly_1_1PolyExtends" ],
    [ "presorted_t", "structfolly_1_1presorted__t.html", null ],
    [ "PriorityLifoSemMPMCQueue", "classfolly_1_1PriorityLifoSemMPMCQueue.html", "classfolly_1_1PriorityLifoSemMPMCQueue" ],
    [ "PriorityMPMCQueue", "classfolly_1_1PriorityMPMCQueue.html", "classfolly_1_1PriorityMPMCQueue" ],
    [ "PriorityThreadFactory", "classfolly_1_1PriorityThreadFactory.html", "classfolly_1_1PriorityThreadFactory" ],
    [ "ProcessReturnCode", "classfolly_1_1ProcessReturnCode.html", "classfolly_1_1ProcessReturnCode" ],
    [ "ProducerConsumerQueue", "structfolly_1_1ProducerConsumerQueue.html", "structfolly_1_1ProducerConsumerQueue" ],
    [ "ProgramExit", "classfolly_1_1ProgramExit.html", "classfolly_1_1ProgramExit" ],
    [ "Promise", "classfolly_1_1Promise.html", "classfolly_1_1Promise" ],
    [ "PromiseAlreadySatisfied", "classfolly_1_1PromiseAlreadySatisfied.html", "classfolly_1_1PromiseAlreadySatisfied" ],
    [ "PromiseException", "classfolly_1_1PromiseException.html", null ],
    [ "PromiseInvalid", "classfolly_1_1PromiseInvalid.html", "classfolly_1_1PromiseInvalid" ],
    [ "propagate_const", "classfolly_1_1propagate__const.html", "classfolly_1_1propagate__const" ],
    [ "QuantileEstimates", "structfolly_1_1QuantileEstimates.html", "structfolly_1_1QuantileEstimates" ],
    [ "QueuedImmediateExecutor", "classfolly_1_1QueuedImmediateExecutor.html", "classfolly_1_1QueuedImmediateExecutor" ],
    [ "QueueFullException", "classfolly_1_1QueueFullException.html", null ],
    [ "Random", "classfolly_1_1Random.html", "classfolly_1_1Random" ],
    [ "Range", "classfolly_1_1Range.html", "classfolly_1_1Range" ],
    [ "rcu_domain", "classfolly_1_1rcu__domain.html", "classfolly_1_1rcu__domain" ],
    [ "rcu_obj_base", "classfolly_1_1rcu__obj__base.html", "classfolly_1_1rcu__obj__base" ],
    [ "rcu_reader_domain", "classfolly_1_1rcu__reader__domain.html", "classfolly_1_1rcu__reader__domain" ],
    [ "rcu_token", "classfolly_1_1rcu__token.html", "classfolly_1_1rcu__token" ],
    [ "ReadCallback", "classfolly_1_1ReadCallback.html", "classfolly_1_1ReadCallback" ],
    [ "ReadCallbackBase", "classfolly_1_1ReadCallbackBase.html", "classfolly_1_1ReadCallbackBase" ],
    [ "ReadCallbackTerminator", "classfolly_1_1ReadCallbackTerminator.html", "classfolly_1_1ReadCallbackTerminator" ],
    [ "ReadEOFCallback", "classfolly_1_1ReadEOFCallback.html", "classfolly_1_1ReadEOFCallback" ],
    [ "ReadErrorCallback", "classfolly_1_1ReadErrorCallback.html", "classfolly_1_1ReadErrorCallback" ],
    [ "ReadMostlyMainPtr", "classfolly_1_1ReadMostlyMainPtr.html", "classfolly_1_1ReadMostlyMainPtr" ],
    [ "ReadMostlyMainPtrDeleter", "classfolly_1_1ReadMostlyMainPtrDeleter.html", "classfolly_1_1ReadMostlyMainPtrDeleter" ],
    [ "ReadMostlySharedPtr", "classfolly_1_1ReadMostlySharedPtr.html", "classfolly_1_1ReadMostlySharedPtr" ],
    [ "ReadMostlyWeakPtr", "classfolly_1_1ReadMostlyWeakPtr.html", "classfolly_1_1ReadMostlyWeakPtr" ],
    [ "RecordIOReader", "classfolly_1_1RecordIOReader.html", "classfolly_1_1RecordIOReader" ],
    [ "RecordIOWriter", "classfolly_1_1RecordIOWriter.html", "classfolly_1_1RecordIOWriter" ],
    [ "RelaxedConcurrentPriorityQueue", "classfolly_1_1RelaxedConcurrentPriorityQueue.html", "classfolly_1_1RelaxedConcurrentPriorityQueue" ],
    [ "remove_cvref", "structfolly_1_1remove__cvref.html", "structfolly_1_1remove__cvref" ],
    [ "RenegotiatingServer", "classfolly_1_1RenegotiatingServer.html", "classfolly_1_1RenegotiatingServer" ],
    [ "Replaceable", "classfolly_1_1Replaceable.html", "classfolly_1_1Replaceable" ],
    [ "Req", "classfolly_1_1Req.html", "classfolly_1_1Req" ],
    [ "RequestContext", "classfolly_1_1RequestContext.html", "classfolly_1_1RequestContext" ],
    [ "RequestContextScopeGuard", "classfolly_1_1RequestContextScopeGuard.html", "classfolly_1_1RequestContextScopeGuard" ],
    [ "RequestData", "classfolly_1_1RequestData.html", "classfolly_1_1RequestData" ],
    [ "RequestEventBase", "classfolly_1_1RequestEventBase.html", "classfolly_1_1RequestEventBase" ],
    [ "RequestToken", "classfolly_1_1RequestToken.html", "classfolly_1_1RequestToken" ],
    [ "rvalue_reference_wrapper", "classfolly_1_1rvalue__reference__wrapper.html", "classfolly_1_1rvalue__reference__wrapper" ],
    [ "RWSpinLock", "classfolly_1_1RWSpinLock.html", "classfolly_1_1RWSpinLock" ],
    [ "SaturatingSemaphore", "classfolly_1_1SaturatingSemaphore.html", "classfolly_1_1SaturatingSemaphore" ],
    [ "ScaleInfo", "structfolly_1_1ScaleInfo.html", "structfolly_1_1ScaleInfo" ],
    [ "ScheduledExecutor", "classfolly_1_1ScheduledExecutor.html", "classfolly_1_1ScheduledExecutor" ],
    [ "ScopedBoundPort", "classfolly_1_1ScopedBoundPort.html", "classfolly_1_1ScopedBoundPort" ],
    [ "ScopedEventBaseThread", "classfolly_1_1ScopedEventBaseThread.html", "classfolly_1_1ScopedEventBaseThread" ],
    [ "ScopedUnlocker", "classfolly_1_1ScopedUnlocker.html", "classfolly_1_1ScopedUnlocker" ],
    [ "SemiFuture", "classfolly_1_1SemiFuture.html", "classfolly_1_1SemiFuture" ],
    [ "SendMsgDataCallback", "classfolly_1_1SendMsgDataCallback.html", "classfolly_1_1SendMsgDataCallback" ],
    [ "SendMsgFlagsCallback", "classfolly_1_1SendMsgFlagsCallback.html", "classfolly_1_1SendMsgFlagsCallback" ],
    [ "SendMsgParamsCallbackBase", "classfolly_1_1SendMsgParamsCallbackBase.html", "classfolly_1_1SendMsgParamsCallbackBase" ],
    [ "SequencedExecutor", "classfolly_1_1SequencedExecutor.html", null ],
    [ "SerialExecutor", "classfolly_1_1SerialExecutor.html", "classfolly_1_1SerialExecutor" ],
    [ "ShallowCopyRequestContextScopeGuard", "structfolly_1_1ShallowCopyRequestContextScopeGuard.html", "structfolly_1_1ShallowCopyRequestContextScopeGuard" ],
    [ "SharedMutexImpl", "classfolly_1_1SharedMutexImpl.html", "classfolly_1_1SharedMutexImpl" ],
    [ "SharedMutexToken", "structfolly_1_1SharedMutexToken.html", "structfolly_1_1SharedMutexToken" ],
    [ "SharedPromise", "classfolly_1_1SharedPromise.html", "classfolly_1_1SharedPromise" ],
    [ "ShutdownSemError", "structfolly_1_1ShutdownSemError.html", "structfolly_1_1ShutdownSemError" ],
    [ "ShutdownSocketSet", "classfolly_1_1ShutdownSocketSet.html", "classfolly_1_1ShutdownSocketSet" ],
    [ "SimpleAllocator", "classfolly_1_1SimpleAllocator.html", "classfolly_1_1SimpleAllocator" ],
    [ "SimpleQuantileEstimator", "classfolly_1_1SimpleQuantileEstimator.html", "classfolly_1_1SimpleQuantileEstimator" ],
    [ "Singleton", "classfolly_1_1Singleton.html", "classfolly_1_1Singleton" ],
    [ "SingletonThreadLocal", "classfolly_1_1SingletonThreadLocal.html", "classfolly_1_1SingletonThreadLocal" ],
    [ "SingletonVault", "classfolly_1_1SingletonVault.html", "classfolly_1_1SingletonVault" ],
    [ "SlidingWindowQuantileEstimator", "classfolly_1_1SlidingWindowQuantileEstimator.html", "classfolly_1_1SlidingWindowQuantileEstimator" ],
    [ "small_vector", "classfolly_1_1small__vector.html", "classfolly_1_1small__vector" ],
    [ "SNIClient", "classfolly_1_1SNIClient.html", "classfolly_1_1SNIClient" ],
    [ "SNIServer", "classfolly_1_1SNIServer.html", "classfolly_1_1SNIServer" ],
    [ "SocketAddress", "classfolly_1_1SocketAddress.html", "classfolly_1_1SocketAddress" ],
    [ "SocketAddressTestHelper", "classfolly_1_1SocketAddressTestHelper.html", "classfolly_1_1SocketAddressTestHelper" ],
    [ "SocketPair", "classfolly_1_1SocketPair.html", "classfolly_1_1SocketPair" ],
    [ "SomeClass", "classfolly_1_1SomeClass.html", "classfolly_1_1SomeClass" ],
    [ "sorted_vector_map", "classfolly_1_1sorted__vector__map.html", "classfolly_1_1sorted__vector__map" ],
    [ "sorted_vector_set", "classfolly_1_1sorted__vector__set.html", "classfolly_1_1sorted__vector__set" ],
    [ "SparseByteSet", "classfolly_1_1SparseByteSet.html", "classfolly_1_1SparseByteSet" ],
    [ "SpinLock", "classfolly_1_1SpinLock.html", "classfolly_1_1SpinLock" ],
    [ "SpinLockArray", "structfolly_1_1SpinLockArray.html", "structfolly_1_1SpinLockArray" ],
    [ "SpinLockGuardImpl", "classfolly_1_1SpinLockGuardImpl.html", "classfolly_1_1SpinLockGuardImpl" ],
    [ "SSLAcceptCloseRunner", "classfolly_1_1SSLAcceptCloseRunner.html", "classfolly_1_1SSLAcceptCloseRunner" ],
    [ "SSLAcceptDestroyRunner", "classfolly_1_1SSLAcceptDestroyRunner.html", "classfolly_1_1SSLAcceptDestroyRunner" ],
    [ "SSLAcceptErrorRunner", "classfolly_1_1SSLAcceptErrorRunner.html", "classfolly_1_1SSLAcceptErrorRunner" ],
    [ "SSLAcceptEvbRunner", "classfolly_1_1SSLAcceptEvbRunner.html", "classfolly_1_1SSLAcceptEvbRunner" ],
    [ "SSLAcceptRunner", "classfolly_1_1SSLAcceptRunner.html", "classfolly_1_1SSLAcceptRunner" ],
    [ "SSLClient", "classfolly_1_1SSLClient.html", "classfolly_1_1SSLClient" ],
    [ "SSLContext", "classfolly_1_1SSLContext.html", "classfolly_1_1SSLContext" ],
    [ "SSLContextTest", "classfolly_1_1SSLContextTest.html", "classfolly_1_1SSLContextTest" ],
    [ "SSLException", "classfolly_1_1SSLException.html", "classfolly_1_1SSLException" ],
    [ "SSLHandshakeBase", "classfolly_1_1SSLHandshakeBase.html", "classfolly_1_1SSLHandshakeBase" ],
    [ "SSLHandshakeClient", "classfolly_1_1SSLHandshakeClient.html", "classfolly_1_1SSLHandshakeClient" ],
    [ "SSLHandshakeClientDoVerify", "classfolly_1_1SSLHandshakeClientDoVerify.html", "classfolly_1_1SSLHandshakeClientDoVerify" ],
    [ "SSLHandshakeClientNoVerify", "classfolly_1_1SSLHandshakeClientNoVerify.html", "classfolly_1_1SSLHandshakeClientNoVerify" ],
    [ "SSLHandshakeServer", "classfolly_1_1SSLHandshakeServer.html", "classfolly_1_1SSLHandshakeServer" ],
    [ "SSLHandshakeServerDoVerify", "classfolly_1_1SSLHandshakeServerDoVerify.html", "classfolly_1_1SSLHandshakeServerDoVerify" ],
    [ "SSLHandshakeServerNoVerify", "classfolly_1_1SSLHandshakeServerNoVerify.html", "classfolly_1_1SSLHandshakeServerNoVerify" ],
    [ "SSLHandshakeServerParseClientHello", "classfolly_1_1SSLHandshakeServerParseClientHello.html", "classfolly_1_1SSLHandshakeServerParseClientHello" ],
    [ "SSLOptionsTest", "classfolly_1_1SSLOptionsTest.html", null ],
    [ "SSLServerAcceptCallback", "classfolly_1_1SSLServerAcceptCallback.html", "classfolly_1_1SSLServerAcceptCallback" ],
    [ "SSLServerAcceptCallbackBase", "classfolly_1_1SSLServerAcceptCallbackBase.html", "classfolly_1_1SSLServerAcceptCallbackBase" ],
    [ "SSLServerAcceptCallbackDelay", "classfolly_1_1SSLServerAcceptCallbackDelay.html", "classfolly_1_1SSLServerAcceptCallbackDelay" ],
    [ "SSLServerAsyncCacheAcceptCallback", "classfolly_1_1SSLServerAsyncCacheAcceptCallback.html", "classfolly_1_1SSLServerAsyncCacheAcceptCallback" ],
    [ "SSLSessionTest", "classfolly_1_1SSLSessionTest.html", "classfolly_1_1SSLSessionTest" ],
    [ "StampedPtr", "structfolly_1_1StampedPtr.html", "structfolly_1_1StampedPtr" ],
    [ "StandardLogHandler", "classfolly_1_1StandardLogHandler.html", "classfolly_1_1StandardLogHandler" ],
    [ "StandardLogHandlerFactory", "classfolly_1_1StandardLogHandlerFactory.html", "classfolly_1_1StandardLogHandlerFactory" ],
    [ "static_function_deleter", "structfolly_1_1static__function__deleter.html", "structfolly_1_1static__function__deleter" ],
    [ "StreamHandlerFactory", "classfolly_1_1StreamHandlerFactory.html", "classfolly_1_1StreamHandlerFactory" ],
    [ "StrictConjunction", "structfolly_1_1StrictConjunction.html", null ],
    [ "StrictDisjunction", "structfolly_1_1StrictDisjunction.html", null ],
    [ "StringKeyedMap", "classfolly_1_1StringKeyedMap.html", "classfolly_1_1StringKeyedMap" ],
    [ "StringKeyedSetBase", "classfolly_1_1StringKeyedSetBase.html", "classfolly_1_1StringKeyedSetBase" ],
    [ "StringKeyedUnorderedMap", "structfolly_1_1StringKeyedUnorderedMap.html", "structfolly_1_1StringKeyedUnorderedMap" ],
    [ "Subprocess", "classfolly_1_1Subprocess.html", "classfolly_1_1Subprocess" ],
    [ "SubprocessError", "classfolly_1_1SubprocessError.html", null ],
    [ "SubprocessSpawnError", "classfolly_1_1SubprocessSpawnError.html", "classfolly_1_1SubprocessSpawnError" ],
    [ "Synchronized", "structfolly_1_1Synchronized.html", "structfolly_1_1Synchronized" ],
    [ "SynchronizedBase", "classfolly_1_1SynchronizedBase.html", null ],
    [ "SynchronizedBase< Subclass, detail::MutexLevel::SHARED >", "classfolly_1_1SynchronizedBase_3_01Subclass_00_01detail_1_1MutexLevel_1_1SHARED_01_4.html", "classfolly_1_1SynchronizedBase_3_01Subclass_00_01detail_1_1MutexLevel_1_1SHARED_01_4" ],
    [ "SynchronizedBase< Subclass, detail::MutexLevel::UNIQUE >", "classfolly_1_1SynchronizedBase_3_01Subclass_00_01detail_1_1MutexLevel_1_1UNIQUE_01_4.html", "classfolly_1_1SynchronizedBase_3_01Subclass_00_01detail_1_1MutexLevel_1_1UNIQUE_01_4" ],
    [ "SynchronizedBase< Subclass, detail::MutexLevel::UPGRADE >", "classfolly_1_1SynchronizedBase_3_01Subclass_00_01detail_1_1MutexLevel_1_1UPGRADE_01_4.html", "classfolly_1_1SynchronizedBase_3_01Subclass_00_01detail_1_1MutexLevel_1_1UPGRADE_01_4" ],
    [ "SynchronizedLockTest", "classfolly_1_1SynchronizedLockTest.html", "classfolly_1_1SynchronizedLockTest" ],
    [ "SynchronizedPtr", "classfolly_1_1SynchronizedPtr.html", "classfolly_1_1SynchronizedPtr" ],
    [ "SynchronizedPtrLockedElement", "structfolly_1_1SynchronizedPtrLockedElement.html", "structfolly_1_1SynchronizedPtrLockedElement" ],
    [ "SynchronizedTest", "classfolly_1_1SynchronizedTest.html", null ],
    [ "SynchronizedTimedTest", "classfolly_1_1SynchronizedTimedTest.html", null ],
    [ "SynchronizedTimedWithConstTest", "classfolly_1_1SynchronizedTimedWithConstTest.html", null ],
    [ "SysAllocator", "classfolly_1_1SysAllocator.html", "classfolly_1_1SysAllocator" ],
    [ "SysArena", "classfolly_1_1SysArena.html", "classfolly_1_1SysArena" ],
    [ "SysBufferDeleter", "structfolly_1_1SysBufferDeleter.html", "structfolly_1_1SysBufferDeleter" ],
    [ "TDigest", "classfolly_1_1TDigest.html", "classfolly_1_1TDigest" ],
    [ "Tearable", "classfolly_1_1Tearable.html", "classfolly_1_1Tearable" ],
    [ "TemplateRange", "structfolly_1_1TemplateRange.html", [
      [ "type", "structfolly_1_1TemplateRange_1_1type.html", "structfolly_1_1TemplateRange_1_1type" ]
    ] ],
    [ "TemplateSeq", "structfolly_1_1TemplateSeq.html", "structfolly_1_1TemplateSeq" ],
    [ "TemplateTupleRange", "structfolly_1_1TemplateTupleRange.html", "structfolly_1_1TemplateTupleRange" ],
    [ "TestExecutor", "classfolly_1_1TestExecutor.html", "classfolly_1_1TestExecutor" ],
    [ "TestHandlerFactory", "classfolly_1_1TestHandlerFactory.html", "classfolly_1_1TestHandlerFactory" ],
    [ "TestLogHandler", "classfolly_1_1TestLogHandler.html", "classfolly_1_1TestLogHandler" ],
    [ "TestLogHandlerFactory", "classfolly_1_1TestLogHandlerFactory.html", "classfolly_1_1TestLogHandlerFactory" ],
    [ "TestLogWriter", "classfolly_1_1TestLogWriter.html", "classfolly_1_1TestLogWriter" ],
    [ "TestSSLAsyncCacheServer", "classfolly_1_1TestSSLAsyncCacheServer.html", "classfolly_1_1TestSSLAsyncCacheServer" ],
    [ "TestSSLServer", "classfolly_1_1TestSSLServer.html", "classfolly_1_1TestSSLServer" ],
    [ "ThreadCachedArena", "classfolly_1_1ThreadCachedArena.html", "classfolly_1_1ThreadCachedArena" ],
    [ "ThreadCachedInt", "classfolly_1_1ThreadCachedInt.html", "classfolly_1_1ThreadCachedInt" ],
    [ "ThreadedExecutor", "classfolly_1_1ThreadedExecutor.html", "classfolly_1_1ThreadedExecutor" ],
    [ "ThreadedRepeatingFunctionRunner", "classfolly_1_1ThreadedRepeatingFunctionRunner.html", "classfolly_1_1ThreadedRepeatingFunctionRunner" ],
    [ "ThreadFactory", "classfolly_1_1ThreadFactory.html", "classfolly_1_1ThreadFactory" ],
    [ "ThreadLocal", "classfolly_1_1ThreadLocal.html", "classfolly_1_1ThreadLocal" ],
    [ "ThreadLocalPRNG", "classfolly_1_1ThreadLocalPRNG.html", "classfolly_1_1ThreadLocalPRNG" ],
    [ "ThreadLocalPtr", "classfolly_1_1ThreadLocalPtr.html", "classfolly_1_1ThreadLocalPtr" ],
    [ "ThreadPoolExecutor", "classfolly_1_1ThreadPoolExecutor.html", "classfolly_1_1ThreadPoolExecutor" ],
    [ "ThreadPoolListHook", "classfolly_1_1ThreadPoolListHook.html", "classfolly_1_1ThreadPoolListHook" ],
    [ "ThreadWheelTimekeeper", "classfolly_1_1ThreadWheelTimekeeper.html", "classfolly_1_1ThreadWheelTimekeeper" ],
    [ "ThrowingBadness", "structfolly_1_1ThrowingBadness.html", "structfolly_1_1ThrowingBadness" ],
    [ "TimedDrivableExecutor", "classfolly_1_1TimedDrivableExecutor.html", "classfolly_1_1TimedDrivableExecutor" ],
    [ "Timekeeper", "classfolly_1_1Timekeeper.html", "classfolly_1_1Timekeeper" ],
    [ "TimeoutManager", "classfolly_1_1TimeoutManager.html", "classfolly_1_1TimeoutManager" ],
    [ "TimeoutQueue", "classfolly_1_1TimeoutQueue.html", "classfolly_1_1TimeoutQueue" ],
    [ "TimePoint", "classfolly_1_1TimePoint.html", "classfolly_1_1TimePoint" ],
    [ "TimeseriesHistogram", "classfolly_1_1TimeseriesHistogram.html", "classfolly_1_1TimeseriesHistogram" ],
    [ "TLRefCount", "classfolly_1_1TLRefCount.html", "classfolly_1_1TLRefCount" ],
    [ "TokenBucketTest", "structfolly_1_1TokenBucketTest.html", null ],
    [ "transparent", "structfolly_1_1transparent.html", "structfolly_1_1transparent" ],
    [ "TransparentStringEqualTo", "structfolly_1_1TransparentStringEqualTo.html", null ],
    [ "TransparentStringHash", "structfolly_1_1TransparentStringHash.html", null ],
    [ "Try", "classfolly_1_1Try.html", "classfolly_1_1Try" ],
    [ "Try< void >", "classfolly_1_1Try_3_01void_01_4.html", "classfolly_1_1Try_3_01void_01_4" ],
    [ "TryException", "classfolly_1_1TryException.html", null ],
    [ "TupleHasher", "structfolly_1_1TupleHasher.html", "structfolly_1_1TupleHasher" ],
    [ "TupleHasher< 0, Ts... >", "structfolly_1_1TupleHasher_3_010_00_01Ts_8_8_8_01_4.html", "structfolly_1_1TupleHasher_3_010_00_01Ts_8_8_8_01_4" ],
    [ "TypedIOBuf", "classfolly_1_1TypedIOBuf.html", "classfolly_1_1TypedIOBuf" ],
    [ "TypeError", "structfolly_1_1TypeError.html", "structfolly_1_1TypeError" ],
    [ "Unaligned", "structfolly_1_1Unaligned.html", null ],
    [ "Unaligned< T, typename std::enable_if< std::is_pod< T >::value >::type >", "structfolly_1_1Unaligned_3_01T_00_01typename_01std_1_1enable__if_3_01std_1_1is__pod_3_01T_01_4_1_1value_01_4_1_1type_01_4.html", "structfolly_1_1Unaligned_3_01T_00_01typename_01std_1_1enable__if_3_01std_1_1is__pod_3_01T_01_4_1_1value_01_4_1_1type_01_4" ],
    [ "UnalignedNoASan", "structfolly_1_1UnalignedNoASan.html", null ],
    [ "UnboundedBlockingQueue", "classfolly_1_1UnboundedBlockingQueue.html", "classfolly_1_1UnboundedBlockingQueue" ],
    [ "UnboundedQueue", "classfolly_1_1UnboundedQueue.html", "classfolly_1_1UnboundedQueue" ],
    [ "UndelayedDestruction", "classfolly_1_1UndelayedDestruction.html", "classfolly_1_1UndelayedDestruction" ],
    [ "Unexpected", "classfolly_1_1Unexpected.html", "classfolly_1_1Unexpected" ],
    [ "Unit", "structfolly_1_1Unit.html", "structfolly_1_1Unit" ],
    [ "unsorted_t", "structfolly_1_1unsorted__t.html", null ],
    [ "Uri", "classfolly_1_1Uri.html", "classfolly_1_1Uri" ],
    [ "UsingUninitializedTry", "classfolly_1_1UsingUninitializedTry.html", "classfolly_1_1UsingUninitializedTry" ],
    [ "UTF8Range", "classfolly_1_1UTF8Range.html", "classfolly_1_1UTF8Range" ],
    [ "VirtualEventBase", "classfolly_1_1VirtualEventBase.html", "classfolly_1_1VirtualEventBase" ],
    [ "VirtualExecutor", "classfolly_1_1VirtualExecutor.html", "classfolly_1_1VirtualExecutor" ],
    [ "WaitOptions", "classfolly_1_1WaitOptions.html", "classfolly_1_1WaitOptions" ],
    [ "WithConstructor", "structfolly_1_1WithConstructor.html", "structfolly_1_1WithConstructor" ],
    [ "WithDestructor", "structfolly_1_1WithDestructor.html", "structfolly_1_1WithDestructor" ],
    [ "WriteCallbackBase", "classfolly_1_1WriteCallbackBase.html", "classfolly_1_1WriteCallbackBase" ],
    [ "WriteChainAsyncTransportWrapper", "classfolly_1_1WriteChainAsyncTransportWrapper.html", "classfolly_1_1WriteChainAsyncTransportWrapper" ],
    [ "WriteErrorCallback", "classfolly_1_1WriteErrorCallback.html", "classfolly_1_1WriteErrorCallback" ],
    [ "XlogCategoryInfo", "classfolly_1_1XlogCategoryInfo.html", "classfolly_1_1XlogCategoryInfo" ],
    [ "XlogFileScopeInfo", "classfolly_1_1XlogFileScopeInfo.html", null ],
    [ "XlogLevelInfo", "classfolly_1_1XlogLevelInfo.html", "classfolly_1_1XlogLevelInfo" ],
    [ "ZeroCopyTest", "classfolly_1_1ZeroCopyTest.html", "classfolly_1_1ZeroCopyTest" ],
    [ "ZeroCopyTestAsyncSocket", "classfolly_1_1ZeroCopyTestAsyncSocket.html", "classfolly_1_1ZeroCopyTestAsyncSocket" ],
    [ "ZeroCopyTestServer", "classfolly_1_1ZeroCopyTestServer.html", "classfolly_1_1ZeroCopyTestServer" ]
];