proxygen: folly::fileutil_detail Namespace Reference
folly::fileutil_detail Namespace Reference
Functions
template<class F , class... Args>
ssize_t wrapNoInt (F f, Args...args)
void incr (ssize_t)
void incr (ssize_t n, off_t &offset)
template<class F , class... Offset>
ssize_t wrapFull (F f, int fd, void *buf, size_t count, Offset...offset)
template<class F , class... Offset>
ssize_t wrapvFull (F f, int fd, iovec *iov, int count, Offset...offset)
Function Documentation
void folly::fileutil_detail::incr (ssize_t) inline
Definition at line 42 of file FileUtilDetail.h.
Referenced by TEST(), wrapFull(), and wrapvFull().
 {}
void folly::fileutil_detail::incr (ssize_t n, off_t & offset) inline
Definition at line 43 of file FileUtilDetail.h.
{
   offset += off_t(n);
 }
template<class F , class... Offset> ssize_t folly::fileutil_detail::wrapFull (F f, int fd, void * buf, size_t count, Offset... offset)
Definition at line 53 of file FileUtilDetail.h.
References b, f, and incr().
Referenced by folly::preadFull(), folly::pwriteFull(), folly::readFull(), folly::test::TEST_F(), and folly::writeFull().
{
   char* b = static_cast<char*>(buf);
   ssize_t totalBytes = 0;
   ssize_t r;
   do {
     r = f(fd, b, count, offset...);
     if (r == -1) {
       if (errno == EINTR) {
         continue;
       }
       return r;
     }
     totalBytes += r;
     b += r;
     count -= r;
     incr(r, offset...);
   } while (r != 0 && count); // 0 means EOF
   return totalBytes;
 }
template<class F , class... Args> ssize_t folly::fileutil_detail::wrapNoInt (F f, Args... args)
Definition at line 34 of file FileUtilDetail.h.
References f.
Referenced by folly::dup2NoInt(), folly::dupNoInt(), folly::fdatasyncNoInt(), folly::flockNoInt(), folly::fsyncNoInt(), folly::ftruncateNoInt(), folly::openNoInt(), folly::preadNoInt(), folly::pwriteNoInt(), folly::readNoInt(), folly::readvNoInt(), folly::shutdownNoInt(), folly::truncateNoInt(), folly::writeNoInt(), and folly::writevNoInt().
{
   ssize_t r;
   do {
     r = f(args...);
   } while (r == -1 && errno == EINTR);
   return r;
 }
template<class F , class... Offset> ssize_t folly::fileutil_detail::wrapvFull (F f, int fd, iovec * iov, int count, Offset... offset)
Definition at line 78 of file FileUtilDetail.h.
References count, f, incr(), and folly::kIovMax.
Referenced by folly::preadvFull(), folly::pwritevFull(), folly::readvFull(), folly::test::TEST(), folly::test::TEST_F(), and folly::writevFull().
{
   ssize_t totalBytes = 0;
   ssize_t r;
   do {
     r = f(fd, iov, std::min<int>(count, kIovMax), offset...);
     if (r == -1) {
       if (errno == EINTR) {
         continue;
       }
       return r;
     }
     if (r == 0) {
       break; // EOF
     }
     totalBytes += r;
     incr(r, offset...);
     while (r != 0 && count != 0) {
       if (r >= ssize_t(iov->iov_len)) {
         r -= ssize_t(iov->iov_len);
         ++iov;
         --count;
       } else {
         iov->iov_base = static_cast<char*>(iov->iov_base) + r;
         iov->iov_len -= r;
         r = 0;
       }
     }
   } while (count);
   return totalBytes;
 }