proxygen: folly::pushmi::isolated Namespace Reference
folly::pushmi::isolated Namespace Reference
Functions
template<class T0 >
constexpr auto expAnd (T0 &&t0)
template<class T0 , class... TN>
constexpr auto expAnd (T0 &&, TN &&...tn)
Function Documentation
template<class T0 > constexpr auto folly::pushmi::isolated::expAnd (T0 && t0)
Definition at line 530 of file concept_def.h.
References folly::pushmi::expAnd().
Referenced by expAnd(), and folly::pushmi::expAnd().
                    {
 template <class T0>
template<class T0 , class... TN> constexpr auto folly::pushmi::isolated::expAnd (T0 && , TN &&... tn)
Definition at line 534 of file concept_def.h.
References expAnd().
{