proxygen: gtest_test_utils Namespace Reference
gtest_test_utils Namespace Reference
Classes
class Subprocess
Functions
def SetEnvVar (env_var, value)
def _ParseAndStripGTestFlags (argv)
def GetFlag (flag)
def GetSourceDir ()
def GetBuildDir ()
def _RemoveTempDir ()
def GetTempDir ()
def GetTestExecutablePath (executable_name, build_dir=None)
def GetExitStatus (exit_code)
def Main ()
Variables
string __author__ = 'wan@google.com (Zhanyong Wan)'
_test_module = unittest
bool _SUBPROCESS_MODULE_AVAILABLE = True
string GTEST_OUTPUT_VAR_NAME = 'GTEST_OUTPUT'
string IS_WINDOWS = 'nt'
string IS_CYGWIN = 'posix'
string PREMATURE_EXIT_FILE_ENV_VAR = 'TEST_PREMATURE_EXIT_FILE'
environ = os.environ.copy()
TestCase = _test_module.TestCase
dictionary _flag_map
bool _gtest_flags_are_parsed = False
_temp_dir = None
Function Documentation
def gtest_test_utils._ParseAndStripGTestFlags (argv) private
Parses and strips Google Test flags from argv.  This is idempotent.
Definition at line 86 of file gtest_test_utils.py.
Referenced by gtest_test_utils.Subprocess.__init__(), GetFlag(), and Main().
 def _ParseAndStripGTestFlags(argv):
   """Parses and strips Google Test flags from argv.  This is idempotent."""
   # Suppresses the lint complaint about a global variable since we need it
   # here to maintain module-wide state.
   global _gtest_flags_are_parsed  # pylint: disable-msg=W0603
   if _gtest_flags_are_parsed:
     return
   _gtest_flags_are_parsed = True
   for flag in _flag_map:
     # The environment variable overrides the default value.
     if flag.upper() in os.environ:
       _flag_map[flag] = os.environ[flag.upper()]
     # The command line flag overrides the environment variable.
     i = 1  # Skips the program name.
     while i < len(argv):
       prefix = '--' + flag + '='
       if argv[i].startswith(prefix):
         _flag_map[flag] = argv[i][len(prefix):]
         del argv[i]
         break
       else:
         # We don't increment i in case we just found a --gtest_* flag
         # and removed it from argv.
         i += 1
def gtest_test_utils._RemoveTempDir () private
Definition at line 140 of file gtest_test_utils.py.
 def _RemoveTempDir():
   if _temp_dir:
     shutil.rmtree(_temp_dir, ignore_errors=True)
 atexit.register(_RemoveTempDir)
def gtest_test_utils.GetBuildDir ()
Returns the absolute path of the directory where the test binaries are.
Definition at line 132 of file gtest_test_utils.py.
References GetFlag().
Referenced by GetTestExecutablePath().
 def GetBuildDir():
   """Returns the absolute path of the directory where the test binaries are."""
   return os.path.abspath(GetFlag('build_dir'))
def gtest_test_utils.GetExitStatus (exit_code)
Returns the argument to exit(), or -1 if exit() wasn't called.
Args:
  exit_code: the result value of os.system(command).
Definition at line 187 of file gtest_test_utils.py.
 def GetExitStatus(exit_code):
   """Returns the argument to exit(), or -1 if exit() wasn't called.
   Args:
     exit_code: the result value of os.system(command).
   """
   if os.name == 'nt':
     # On Windows, os.WEXITSTATUS() doesn't work and os.system() returns
     # the argument to exit() directly.
     return exit_code
   else:
     # On Unix, os.WEXITSTATUS() must be used to extract the exit status
     # from the result of os.system().
     if os.WIFEXITED(exit_code):
       return os.WEXITSTATUS(exit_code)
     else:
       return -1
def gtest_test_utils.GetFlag (flag)
Returns the value of the given flag.
Definition at line 115 of file gtest_test_utils.py.
References _ParseAndStripGTestFlags().
Referenced by GetBuildDir(), and GetSourceDir().
 def GetFlag(flag):
   """Returns the value of the given flag."""
   # In case GetFlag() is called before Main(), we always call
   # _ParseAndStripGTestFlags() here to make sure the --gtest_* flags
   # are parsed.
   _ParseAndStripGTestFlags(sys.argv)
   return _flag_map[flag]
def gtest_test_utils.GetSourceDir ()
Returns the absolute path of the directory where the .py files are.
Definition at line 126 of file gtest_test_utils.py.
References GetFlag().
Referenced by gmock_test_utils.GetSourceDir(), and gtest_output_test.GTestOutputTest.testOutput().
 def GetSourceDir():
   """Returns the absolute path of the directory where the .py files are."""
   return os.path.abspath(GetFlag('source_dir'))
def gtest_test_utils.GetTempDir ()
Returns a directory for temporary files.
Definition at line 147 of file gtest_test_utils.py.
Referenced by gtest_xml_output_unittest.GTestXMLOutputUnitTest._GetXmlOutput(), gtest_xml_outfiles_test.GTestXMLOutFilesTest._TestOutFile(), gtest_xml_outfiles_test.GTestXMLOutFilesTest.setUp(), gtest_xml_output_unittest.GTestXMLOutputUnitTest.testDefaultOutputFile(), gtest_filter_unittest.GTestFilterUnitTest.testShardStatusFileIsCreated(), gtest_filter_unittest.GTestFilterUnitTest.testShardStatusFileIsCreatedWithListTests(), and gtest_xml_output_unittest.GTestXMLOutputUnitTest.testSuppressedXmlOutput().
 def GetTempDir():
   """Returns a directory for temporary files."""
   global _temp_dir
   if not _temp_dir:
     _temp_dir = tempfile.mkdtemp()
   return _temp_dir
def gtest_test_utils.GetTestExecutablePath (executable_name, build_dir = None)
Returns the absolute path of the test binary given its name.
The function will print a message and abort the program if the resulting file
doesn't exist.
Args:
  executable_name: name of the test binary that the test script runs.
  build_dir:       directory where to look for executables, by default
                   the result of GetBuildDir().
Returns:
  The absolute path of the test binary.
Definition at line 156 of file gtest_test_utils.py.
References GetBuildDir().
Referenced by gtest_xml_output_unittest.GTestXMLOutputUnitTest._GetXmlOutput(), gtest_xml_outfiles_test.GTestXMLOutFilesTest._TestOutFile(), gmock_test_utils.GetTestExecutablePath(), and gtest_xml_output_unittest.GTestXMLOutputUnitTest.testDefaultOutputFile().
 def GetTestExecutablePath(executable_name, build_dir=None):
   """Returns the absolute path of the test binary given its name.
   The function will print a message and abort the program if the resulting file
   doesn't exist.
   Args:
     executable_name: name of the test binary that the test script runs.
     build_dir:       directory where to look for executables, by default
                      the result of GetBuildDir().
   Returns:
     The absolute path of the test binary.
   """
   path = os.path.abspath(os.path.join(build_dir or GetBuildDir(),
                                       executable_name))
   if (IS_WINDOWS or IS_CYGWIN) and not path.endswith('.exe'):
     path += '.exe'
   if not os.path.exists(path):
     message = (
         'Unable to find the test binary "%s". Please make sure to provide\n'
         'a path to the binary via the --build_dir flag or the BUILD_DIR\n'
         'environment variable.' % path)
     sys.stdout.write(message)
     sys.exit(1)
   return path
def gtest_test_utils.Main ()
Runs the unit test.
Definition at line 306 of file gtest_test_utils.py.
References _ParseAndStripGTestFlags().
Referenced by gtest_test_utils.Subprocess.__init__(), gtest_xml_outfiles_test.GTestXMLOutFilesTest._TestOutFile(), gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput(), gmock_test_utils.Main(), gtest_color_test.GTestColorTest.testAliasesOfYesAndNo(), gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.testCatchExceptionsDoesNotInterfere(), gtest_uninitialized_test.GTestUninitializedTest.testExitCodeAndOutput(), gtest_output_test.GTestOutputTest.testOutput(), gtest_help_test.GTestHelpTest.testRunsTestsWithGtestInternalFlag(), gtest_filter_unittest.GTestFilterUnitTest.testShardingWorksWithDeathTests(), gtest_shuffle_test.GTestShuffleUnitTest.testShuffleShardedTestsPreservesPartition(), gtest_throw_on_failure_test.ThrowOnFailureTest.testThrowOnFailureFlagOverridesEnvVar(), gtest_catch_exceptions_test.CatchCxxExceptionsTest.testUnhandledCxxExceptionsAbortTheProgram(), gtest_list_tests_unittest.GTestListTestsUnitTest.testWithFilterFlags(), and gtest_env_var_test.GTestEnvVarTest.testXmlOutputFileOverride().
 def Main():
   """Runs the unit test."""
   # We must call _ParseAndStripGTestFlags() before calling
   # unittest.main().  Otherwise the latter will be confused by the
   # --gtest_* flags.
   _ParseAndStripGTestFlags(sys.argv)
   # The tested binaries should not be writing XML output files unless the
   # script explicitly instructs them to.
   # TODO(vladl@google.com): Move this into Subprocess when we implement
   # passing environment into it as a parameter.
   if GTEST_OUTPUT_VAR_NAME in os.environ:
     del os.environ[GTEST_OUTPUT_VAR_NAME]
   _test_module.main()
def gtest_test_utils.SetEnvVar (env_var, value)
Sets/unsets an environment variable to a given value.
Definition at line 65 of file gtest_test_utils.py.
 def SetEnvVar(env_var, value):
   """Sets/unsets an environment variable to a given value."""
   if value is not None:
     environ[env_var] = value
   elif env_var in environ:
     del environ[env_var]
 # Here we expose a class from a particular module, depending on the
 # environment. The comment suppresses the 'Invalid variable name' lint
 # complaint.
Variable Documentation
string gtest_test_utils.__author__ = 'wan@google.com (Zhanyong Wan)' private
Definition at line 34 of file gtest_test_utils.py.
dictionary gtest_test_utils._flag_map private
Initial value:
 = {'source_dir': os.path.dirname(sys.argv[0]),
              'build_dir': os.path.dirname(sys.argv[0])}
Definition at line 81 of file gtest_test_utils.py.
bool gtest_test_utils._gtest_flags_are_parsed = False private
Definition at line 83 of file gtest_test_utils.py.
bool gtest_test_utils._SUBPROCESS_MODULE_AVAILABLE = True private
Definition at line 48 of file gtest_test_utils.py.
gtest_test_utils._temp_dir = None private
Definition at line 138 of file gtest_test_utils.py.
gtest_test_utils._test_module = unittest private
Definition at line 42 of file gtest_test_utils.py.
gtest_test_utils.environ = os.environ.copy()
Definition at line 62 of file gtest_test_utils.py.
string gtest_test_utils.GTEST_OUTPUT_VAR_NAME = 'GTEST_OUTPUT'
Definition at line 54 of file gtest_test_utils.py.
string gtest_test_utils.IS_CYGWIN = 'posix'
Definition at line 57 of file gtest_test_utils.py.
string gtest_test_utils.IS_WINDOWS = 'nt'
Definition at line 56 of file gtest_test_utils.py.
string gtest_test_utils.PREMATURE_EXIT_FILE_ENV_VAR = 'TEST_PREMATURE_EXIT_FILE'
Definition at line 60 of file gtest_test_utils.py.
gtest_test_utils.TestCase = _test_module.TestCase
Definition at line 77 of file gtest_test_utils.py.
Referenced by gtest_catch_exceptions_test.CatchSehExceptionsTest.testCatchesSehExceptionsWithCxxExceptionsDisabled().