proxygen: testing::gmock_nice_strict_test Namespace Reference
testing::gmock_nice_strict_test Namespace Reference
Classes
class Foo
class MockBar
class MockFoo
Functions
TEST (NiceMockTest, AllowsExpectedCall)
TEST (NiceMockTest, UnexpectedCallFails)
TEST (NiceMockTest, NonDefaultConstructor)
TEST (NiceMockTest, NonDefaultConstructor10)
TEST (NiceMockTest, AcceptsClassNamedMock)
TEST (NaggyMockTest, AllowsExpectedCall)
TEST (NaggyMockTest, UnexpectedCallFails)
TEST (NaggyMockTest, NonDefaultConstructor)
TEST (NaggyMockTest, NonDefaultConstructor10)
TEST (NaggyMockTest, AcceptsClassNamedMock)
TEST (StrictMockTest, AllowsExpectedCall)
TEST (StrictMockTest, UnexpectedCallFails)
TEST (StrictMockTest, UninterestingCallFails)
TEST (StrictMockTest, UninterestingCallFailsAfterDeath)
TEST (StrictMockTest, NonDefaultConstructor)
TEST (StrictMockTest, NonDefaultConstructor10)
TEST (StrictMockTest, AcceptsClassNamedMock)
Function Documentation
testing::gmock_nice_strict_test::TEST (NiceMockTest , AllowsExpectedCall)
Definition at line 204 of file gmock-nice-strict_test.cc.
References EXPECT_CALL.
{
   NiceMock<MockFoo> nice_foo;
   EXPECT_CALL(nice_foo, DoThis());
   nice_foo.DoThis();
 }
testing::gmock_nice_strict_test::TEST (NiceMockTest , UnexpectedCallFails)
Definition at line 212 of file gmock-nice-strict_test.cc.
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
{
   NiceMock<MockFoo> nice_foo;
   EXPECT_CALL(nice_foo, DoThis()).Times(0);
   EXPECT_NONFATAL_FAILURE(nice_foo.DoThis(), "called more times than expected");
 }
testing::gmock_nice_strict_test::TEST (NiceMockTest , NonDefaultConstructor)
Definition at line 221 of file gmock-nice-strict_test.cc.
References EXPECT_EQ.
{
   NiceMock<MockBar> nice_bar("hi");
   EXPECT_EQ("hi", nice_bar.str());
   nice_bar.This();
   nice_bar.That(5, true);
 }
testing::gmock_nice_strict_test::TEST (NiceMockTest , NonDefaultConstructor10)
Definition at line 231 of file gmock-nice-strict_test.cc.
References EXPECT_EQ.
{
   NiceMock<MockBar> nice_bar('a', 'b', "c", "d", 'e', 'f',
                              "g", "h", true, false);
   EXPECT_EQ("abcdefghTF", nice_bar.str());
   nice_bar.This();
   nice_bar.That(5, true);
 }
testing::gmock_nice_strict_test::TEST (NiceMockTest , AcceptsClassNamedMock)
Definition at line 249 of file gmock-nice-strict_test.cc.
References testing::internal::CaptureStdout(), testing::internal::Delete(), EXPECT_CALL, EXPECT_THAT, testing::internal::GetCapturedStdout(), GMOCK_FLAG, testing::HasSubstr(), testing::Invoke(), ON_CALL, and TEST().
{
   NiceMock< ::Mock> nice;
   EXPECT_CALL(nice, DoThis());
   nice.DoThis();
 }
testing::gmock_nice_strict_test::TEST (NaggyMockTest , AllowsExpectedCall)
Definition at line 296 of file gmock-nice-strict_test.cc.
References EXPECT_CALL.
{
   NaggyMock<MockFoo> naggy_foo;
   EXPECT_CALL(naggy_foo, DoThis());
   naggy_foo.DoThis();
 }
testing::gmock_nice_strict_test::TEST (NaggyMockTest , UnexpectedCallFails)
Definition at line 304 of file gmock-nice-strict_test.cc.
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
{
   NaggyMock<MockFoo> naggy_foo;
   EXPECT_CALL(naggy_foo, DoThis()).Times(0);
   EXPECT_NONFATAL_FAILURE(naggy_foo.DoThis(),
                           "called more times than expected");
 }
testing::gmock_nice_strict_test::TEST (NaggyMockTest , NonDefaultConstructor)
Definition at line 314 of file gmock-nice-strict_test.cc.
References EXPECT_EQ.
{
   NaggyMock<MockBar> naggy_bar("hi");
   EXPECT_EQ("hi", naggy_bar.str());
   naggy_bar.This();
   naggy_bar.That(5, true);
 }
testing::gmock_nice_strict_test::TEST (NaggyMockTest , NonDefaultConstructor10)
Definition at line 324 of file gmock-nice-strict_test.cc.
References EXPECT_EQ.
{
   NaggyMock<MockBar> naggy_bar('0', '1', "2", "3", '4', '5',
                                "6", "7", true, false);
   EXPECT_EQ("01234567TF", naggy_bar.str());
   naggy_bar.This();
   naggy_bar.That(5, true);
 }
testing::gmock_nice_strict_test::TEST (NaggyMockTest , AcceptsClassNamedMock)
Definition at line 342 of file gmock-nice-strict_test.cc.
References EXPECT_CALL.
{
   NaggyMock< ::Mock> naggy;
   EXPECT_CALL(naggy, DoThis());
   naggy.DoThis();
 }
testing::gmock_nice_strict_test::TEST (StrictMockTest , AllowsExpectedCall)
Definition at line 350 of file gmock-nice-strict_test.cc.
References EXPECT_CALL.
{
   StrictMock<MockFoo> strict_foo;
   EXPECT_CALL(strict_foo, DoThis());
   strict_foo.DoThis();
 }
testing::gmock_nice_strict_test::TEST (StrictMockTest , UnexpectedCallFails)
Definition at line 358 of file gmock-nice-strict_test.cc.
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
{
   StrictMock<MockFoo> strict_foo;
   EXPECT_CALL(strict_foo, DoThis()).Times(0);
   EXPECT_NONFATAL_FAILURE(strict_foo.DoThis(),
                           "called more times than expected");
 }
testing::gmock_nice_strict_test::TEST (StrictMockTest , UninterestingCallFails)
Definition at line 367 of file gmock-nice-strict_test.cc.
References EXPECT_NONFATAL_FAILURE.
{
   StrictMock<MockFoo> strict_foo;
   EXPECT_NONFATAL_FAILURE(strict_foo.DoThis(),
                           "Uninteresting mock function call");
 }
testing::gmock_nice_strict_test::TEST (StrictMockTest , UninterestingCallFailsAfterDeath)
Definition at line 376 of file gmock-nice-strict_test.cc.
References testing::internal::Delete(), EXPECT_NONFATAL_FAILURE, testing::Invoke(), and ON_CALL.
{
   StrictMock<MockFoo>* const strict_foo = new StrictMock<MockFoo>;
   ON_CALL(*strict_foo, DoThis())
       .WillByDefault(Invoke(strict_foo, &MockFoo::Delete));
   EXPECT_NONFATAL_FAILURE(strict_foo->DoThis(),
                           "Uninteresting mock function call");
 }
testing::gmock_nice_strict_test::TEST (StrictMockTest , NonDefaultConstructor)
Definition at line 388 of file gmock-nice-strict_test.cc.
References EXPECT_EQ, and EXPECT_NONFATAL_FAILURE.
{
   StrictMock<MockBar> strict_bar("hi");
   EXPECT_EQ("hi", strict_bar.str());
   EXPECT_NONFATAL_FAILURE(strict_bar.That(5, true),
                           "Uninteresting mock function call");
 }
testing::gmock_nice_strict_test::TEST (StrictMockTest , NonDefaultConstructor10)
Definition at line 398 of file gmock-nice-strict_test.cc.
References EXPECT_EQ, and EXPECT_NONFATAL_FAILURE.
{
   StrictMock<MockBar> strict_bar('a', 'b', "c", "d", 'e', 'f',
                                  "g", "h", true, false);
   EXPECT_EQ("abcdefghTF", strict_bar.str());
   EXPECT_NONFATAL_FAILURE(strict_bar.That(5, true),
                           "Uninteresting mock function call");
 }
testing::gmock_nice_strict_test::TEST (StrictMockTest , AcceptsClassNamedMock)
Definition at line 416 of file gmock-nice-strict_test.cc.
References EXPECT_CALL.
Referenced by testing::gmock_nice_strict_test::MockBar::str(), and TEST().
{
   StrictMock< ::Mock> strict;
   EXPECT_CALL(strict, DoThis());
   strict.DoThis();
 }