proxygen: bm Namespace Reference
bm Namespace Reference
Typedefs
typedef BitVectorEncoder< uint32_t, uint32_t, 128, 128 > Encoder
Functions
void init ()
void free ()
Variables
std::vector< uint32_t > data
std::vector< size_t > order
std::vector< uint32_t > encodeSmallData
std::vector< uint32_t > encodeLargeData
Encoder::MutableCompressedList list
std::vector< std::pair< size_t, size_t > > numLowerBitsInput
Typedef Documentation
typedef EliasFanoEncoderV2< uint32_t, uint32_t, 128, 128 > bm::Encoder
Definition at line 70 of file BitVectorCodingTest.cpp.
Function Documentation
void bm::free ()
Definition at line 94 of file BitVectorCodingTest.cpp.
References folly::compression::BitVectorCompressedListBase< Pointer >::free().
Referenced by folly::aligned_free(), folly::fbvector< T, Allocator >::Impl::D_deallocate(), folly::JemallocHugePageAllocator::deallocate(), folly::JemallocNodumpAllocator::deallocate(), folly::SysAllocator< T >::deallocate(), folly::deallocateBytes(), proxygen::compress::QMINScheme::decode(), folly::fbstring_core< Char >::RefCounted::decrementRefs(), folly::AsyncSocket::BytesWriteRequest::destroy(), TestAsyncTransport::WriteEvent::destroyEvent(), folly::fbstring_core< char >::destroyMediumLarge(), DoTimingBig(), proxygen::compress::QMINScheme::encode(), folly::fbstring_core< char >::fbstring_core(), folly::compression::BitVectorCompressedListBase< Pointer >::free(), folly::compression::EliasFanoCompressedListBase< Pointer >::free(), ReadCallback::Buffer::free(), folly::ReadCallback::Buffer::free(), folly::futures::Barrier::freeControlBlock(), folly::IOBuf::freeExtBuffer(), folly::small_vector< Value, RequestedMaxInline, PolicyA, PolicyB, PolicyC >::Data::freeHeap(), testing::internal::GetThreadCount(), testing::internal::GetTypeName(), main(), folly::small_vector< Observer< T > *, InlineObservers >::makeSizeInternal(), folly::threadlocal_detail::StaticMetaBase::onThreadExit(), folly::ShutdownSocketSet::Free::operator()(), folly::SysBufferDeleter::operator()(), operator<<(), counted_ptr< T, Atom >::operator=(), parser_free(), proxygen::compress::QMINScheme::recvAck(), counted_ptr_internals< Atom >::release_shared(), folly::IOBuf::releaseStorage(), folly::threadlocal_detail::StaticMetaBase::reserve(), folly::threadlocal_detail::StaticMetaBase::reserveHeadUnlocked(), folly::smartRealloc(), TEST(), test_relinquish3(), counted_ptr< T, Atom >::~counted_ptr(), folly::ProducerConsumerQueue< T >::~ProducerConsumerQueue(), proxygen::compress::QMINScheme::~QMINScheme(), TestAsyncTransport::ReadEvent::~ReadEvent(), SyncVec< T >::~SyncVec(), and TestAsyncTransport::WriteEvent::~WriteEvent().
             {
   list.free();
 }
void bm::init ()
Definition at line 80 of file BitVectorCodingTest.cpp.
References encode(), and folly::compression::generateRandomList().
Referenced by array_bench(), cleanup_bench(), holder_bench(), proxygen::HTTPAcceptor::init(), list_hoh_bench(), list_protect_all_bench(), local_bench(), main(), obj_bench(), run_once(), fizz::test::HandshakeTest::SetUp(), and testLen().
             {
   std::mt19937 gen;
   data = generateRandomList(100 * 1000, 10 * 1000 * 1000, gen);
   list = Encoder::encode(data.begin(), data.end());
   order.resize(data.size());
   std::iota(order.begin(), order.end(), size_t());
   std::shuffle(order.begin(), order.end(), gen);
   encodeSmallData = generateRandomList(10, 100 * 1000, gen);
   encodeLargeData = generateRandomList(1000 * 1000, 100 * 1000 * 1000, gen);
 }
Variable Documentation
std::vector< uint32_t > bm::data
Definition at line 72 of file BitVectorCodingTest.cpp.
Referenced by BENCHMARK(), Skip_ForwardQ128(), and SkipTo_SkipQ128().
std::vector< uint32_t > bm::encodeLargeData
Definition at line 76 of file BitVectorCodingTest.cpp.
Referenced by BENCHMARK(), and TEST_F().
std::vector< uint32_t > bm::encodeSmallData
Definition at line 75 of file BitVectorCodingTest.cpp.
Referenced by BENCHMARK(), and TEST_F().
Encoder::MutableCompressedList bm::list
Definition at line 78 of file BitVectorCodingTest.cpp.
Referenced by pump.ExpNode::__init__(), cpp.gmock_class::_GenerateMocks(), cpp.ast.AstBuilder::_GetClass(), cpp.ast.AstBuilder::_GetMethod(), cpp.ast.AstBuilder::_GetTemplatedTypes(), gmock_doctor::_NeedToUseSymbolDiagnoser(), gtest_filter_unittest.GTestFilterUnitTest::AdjustForParameterizedTests(), BENCHMARK(), testing::internal::edit_distance::CalculateOptimalEdits(), folly::fibers::TimeoutController::cancel(), cmake_minimum_required(), wangle::FizzConfigUtil::createFizzContext(), deadlock::find_cycle(), folly::detail::ThreadCachedLists< Tag >::ListHead::forEach(), cpp.gmock_class_test.GenerateMethodsTest::GenerateMethodSource(), cpp.gmock_class_test.GenerateMocksTest::GenerateMocks(), cpp.ast.AstBuilder::handle_namespace(), cpp.ast.AstBuilder::HandleError(), main(), pump::ParseToAST(), folly::fibers::TimeoutController::registerTimeout(), fatal_test.FatalTests::run_helper_nochecks(), folly::fibers::TimeoutController::runTimeouts(), folly::HHWheelTimer::scheduleTimeoutImpl(), deadlock::simple_cycles(), Skip_ForwardQ128(), SkipTo_SkipQ128(), TEST(), TEST_F(), folly::compression::testAll(), folly::compression::testEmpty(), folly::compression::testSkip(), folly::compression::testSkipTo(), folly::detail::AtFork::unregisterHandler(), and foo::StreamableTemplateInFoo< T >::value().
std::vector<std::pair<size_t, size_t> > bm::numLowerBitsInput
Definition at line 167 of file EliasFanoCodingTest.cpp.
Referenced by BENCHMARK().
std::vector< size_t > bm::order
Definition at line 73 of file BitVectorCodingTest.cpp.
Referenced by BENCHMARK().