proxygen: fizz::jni Namespace Reference
fizz::jni Namespace Reference
Functions
void setVM (JavaVM *jvm)
JNIEnv * getEnv (bool *shouldDetach)
void releaseEnv (bool shouldDetach)
jclass getClass (JNIEnv *env, const std::string &name)
jmethodID getMethodID (JNIEnv *env, jclass clazz, const std::string &name, const std::string &signature)
void maybeThrowException (JNIEnv *env, bool shouldDetach)
jbyteArray createByteArray (JNIEnv *env, folly::ByteRange byteRange)
jbyteArray createByteArray (JNIEnv *env, Buf buf)
Function Documentation
jbyteArray fizz::jni::createByteArray (JNIEnv * env, folly::ByteRange byteRange)
Definition at line 72 of file JniUtils.cpp.
References folly::Range< Iter >::data(), and folly::Range< Iter >::size().
Referenced by createByteArray(), fizz::JavaCryptoPeerCert::JavaCryptoPeerCert(), and fizz::JavaCryptoPeerCert::verify().
{
   auto byteArray = env->NewByteArray(byteRange.size());
   env->SetByteArrayRegion(
       byteArray,
       0 /*start*/,
       byteRange.size(),
       reinterpret_cast<const jbyte*>(byteRange.data()));
   return byteArray;
 }
jbyteArray fizz::jni::createByteArray (JNIEnv * env, Buf buf)
Definition at line 82 of file JniUtils.cpp.
References createByteArray().
{
   return createByteArray(env, buf->coalesce());
 }
jclass fizz::jni::getClass (JNIEnv * env, const std::string & name)
Definition at line 46 of file JniUtils.cpp.
Referenced by fizz::JavaCryptoPeerCert::onLoad().
{
   auto clazz =
       reinterpret_cast<jclass>(env->NewGlobalRef(env->FindClass(name.c_str())));
   CHECK(clazz);
   return clazz;
 }
JNIEnv * fizz::jni::getEnv (bool * shouldDetach)
Definition at line 23 of file JniUtils.cpp.
Referenced by fizz::JavaCryptoPeerCert::getIdentity(), fizz::JavaCryptoPeerCert::JavaCryptoPeerCert(), and fizz::JavaCryptoPeerCert::verify().
{
   *shouldDetach = false;
   JNIEnv* env;
   auto status = vm->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6);
   CHECK(status == JNI_OK || status == JNI_EDETACHED);
   if (status == JNI_EDETACHED) {
     status = vm->AttachCurrentThread(
         reinterpret_cast<void**>(&env), nullptr /*args*/);
     CHECK_EQ(status, JNI_OK);
     *shouldDetach = true;
   }
   return env;
 }
jmethodID fizz::jni::getMethodID (JNIEnv * env, jclass clazz, const std::string & name, const std::string & signature)
Definition at line 53 of file JniUtils.cpp.
Referenced by fizz::JavaCryptoPeerCert::onLoad().
{
   auto methodId = env->GetMethodID(clazz, name.c_str(), signature.c_str());
   CHECK(methodId);
   return methodId;
 }
void fizz::jni::maybeThrowException (JNIEnv * env, bool shouldDetach)
Definition at line 63 of file JniUtils.cpp.
References releaseEnv().
Referenced by fizz::JavaCryptoPeerCert::getIdentity(), fizz::JavaCryptoPeerCert::JavaCryptoPeerCert(), and fizz::JavaCryptoPeerCert::verify().
{
   if (!env->ExceptionCheck()) {
     return;
   }
   env->ExceptionDescribe();
   releaseEnv(shouldDetach);
   throw std::runtime_error("JNI exception");
 }
void fizz::jni::releaseEnv (bool shouldDetach)
Definition at line 40 of file JniUtils.cpp.
Referenced by fizz::JavaCryptoPeerCert::getIdentity(), fizz::JavaCryptoPeerCert::JavaCryptoPeerCert(), maybeThrowException(), and fizz::JavaCryptoPeerCert::verify().
{
   if (shouldDetach) {
     vm->DetachCurrentThread();
   }
 }
void fizz::jni::setVM (JavaVM * jvm)
Definition at line 19 of file JniUtils.cpp.
Referenced by JNI_OnLoad().
{
   vm = jvm;
 }