proxygen: folly::settings::detail Namespace Reference
folly::settings::detail Namespace Reference
Classes
class SettingCore
class SettingWrapper
class SnapshotSettingWrapper
struct TypeIdentity
Typedefs
template<class T >
using TypeIdentityT = typename TypeIdentity< T >::type
Functions
if (savedValue)
return core getSlow ()
template<class T >
void set (detail::SettingCore< T > &core, const T &t, StringPiece reason)
template<class T >
std::enable_if_t< std::is_constructible< T, StringPiece >::value, T > convertOrConstruct (StringPiece newValue)
template<class T >
std::enable_if_t<!std::is_constructible< T, StringPiece >::value, T > convertOrConstruct (StringPiece newValue)
void registerSetting (SettingCoreBase &core)
auto & getSavedValuesMutex ()
auto & getSavedValues ()
SettingCoreBase::Version nextGlobalVersion ()
void saveValueForOutstandingSnapshots (SettingCoreBase::Key settingKey, SettingCoreBase::Version version, const BoxedValue &value)
const BoxedValue *FOLLY_NULLABLE getSavedValue (SettingCoreBase::Key settingKey, SettingCoreBase::Version at)
Variables
template<class T >
auto savedValue = detail::getSavedValue(core.getKey(), at_)
std::atomic< SettingCoreBase::Version > gGlobalVersion_
Typedef Documentation
template<class T > using folly::settings::detail::TypeIdentityT = typedef typename TypeIdentity<T>::type
Definition at line 89 of file Settings.h.
Function Documentation
template<class T > std::enable_if_t<std::is_constructible<T, StringPiece>::value, T> folly::settings::detail::convertOrConstruct (StringPiece newValue)
Definition at line 239 of file SettingsImpl.h.
References folly::T, and value.
{
   return T(newValue);
 }
template<class T > std::enable_if_t<!std::is_constructible<T, StringPiece>::value, T> folly::settings::detail::convertOrConstruct (StringPiece newValue)
Definition at line 244 of file SettingsImpl.h.
{
   return to<T>(newValue);
 }
const BoxedValue* FOLLY_NULLABLE folly::settings::detail::getSavedValue (SettingCoreBase::Key settingKey, SettingCoreBase::Version at)
Definition at line 142 of file Settings.cpp.
References folly::test::end(), getSavedValues(), getSavedValuesMutex(), and gGlobalVersion_.
{
   SharedMutex::ReadHolder lg(getSavedValuesMutex());
   auto it = getSavedValues().find(at);
   if (it != getSavedValues().end()) {
     auto jt = it->second.second.find(settingKey);
     if (jt != it->second.second.end()) {
       return &jt->second;
     }
   }
   return nullptr;
 }
auto& folly::settings::detail::getSavedValues ()
Definition at line 117 of file Settings.cpp.
Referenced by getSavedValue(), and saveValueForOutstandingSnapshots().
{
   static std::unordered_map<
       SettingCoreBase::Version,
       std::pair<size_t, std::unordered_map<SettingCoreBase::Key, BoxedValue>>>
       gSavedValues;
   return gSavedValues;
 }
auto& folly::settings::detail::getSavedValuesMutex ()
Definition at line 111 of file Settings.cpp.
Referenced by getSavedValue(), and saveValueForOutstandingSnapshots().
{
   static SharedMutex gSavedValuesMutex;
   return gSavedValuesMutex;
 }
return core folly::settings::detail::getSlow ()
Referenced by folly::SingletonThreadLocal< T, Tag, Make, TLTag >::get(), folly::settings::detail::SettingCore< T >::getAsString(), and folly::SingletonThreadLocal< T, Tag, Make, TLTag >::getWrapper().
folly::settings::detail::if (savedValue)
Definition at line 225 of file SettingsImpl.h.
References savedValue.
                     {
       return savedValue->template unbox<T>();
     }
SettingCoreBase::Version folly::settings::detail::nextGlobalVersion ()
Definition at line 125 of file Settings.cpp.
Referenced by folly::settings::detail::SettingCore< T >::set().
{
   return gGlobalVersion_.fetch_add(1) + 1;
 }
void folly::settings::detail::registerSetting (SettingCoreBase & core)
Definition at line 33 of file Settings.cpp.
References folly::gen::move.
Referenced by folly::settings::detail::SettingCore< T >::SettingCore().
{
   if (core.meta().project.empty() ||
       core.meta().project.find('_') != std::string::npos) {
     throw std::logic_error(
         "Setting project must be nonempty and cannot contain underscores: " +
         core.meta().project.str());
   }
   auto fullname = core.meta().project.str() + "_" + core.meta().name.str();
   auto mapPtr = settingsMap().wlock();
   auto it = mapPtr->find(fullname);
   if (it != mapPtr->end()) {
     throw std::logic_error("FOLLY_SETTING already exists: " + fullname);
   }
   mapPtr->emplace(std::move(fullname), &core);
 }
void folly::settings::detail::saveValueForOutstandingSnapshots (SettingCoreBase::Key settingKey, SettingCoreBase::Version version, const BoxedValue & value)
Definition at line 129 of file Settings.cpp.
References FOLLY_NULLABLE, getSavedValues(), getSavedValuesMutex(), and folly::value().
Referenced by folly::settings::detail::SettingCore< T >::set().
{
   SharedMutex::WriteHolder lg(getSavedValuesMutex());
   for (auto& it : getSavedValues()) {
     if (version <= it.first) {
       it.second.second[settingKey] = value;
     }
   }
 }
template<class T > void folly::settings::detail::set (detail::SettingCore< T > & core, const T & t, StringPiece reason)
Definition at line 232 of file SettingsImpl.h.
References folly::T, and value.
{
     snapshotValues_[core.getKey()] = detail::BoxedValue(t, reason, core);
   }
Variable Documentation
std::atomic<SettingCoreBase::Version> folly::settings::detail::gGlobalVersion_
Definition at line 109 of file Settings.cpp.
Referenced by getSavedValue().
template<class T > auto folly::settings::detail::savedValue = detail::getSavedValue(core.getKey(), at_)
Can we store T in a global atomic?
Definition at line 224 of file SettingsImpl.h.
Referenced by if().