proxygen: GCC61971 Namespace Reference
GCC61971 Namespace Reference
Classes
struct S
Functions
template<typename T1 >
constexpr auto concatStuff (const T1 &component) noexcept
Variables
constexpr auto xyz = folly::makeFixedString("xyz")
constexpr auto dot = folly::makeFixedString(".")
constexpr auto co = folly::makeFixedString("co")
Function Documentation
template<typename T1 > constexpr auto GCC61971::concatStuff (const T1 & component) noexcept
Definition at line 674 of file FixedStringTest.cpp.
{
   return xyz + dot + component;
 }
Variable Documentation
constexpr auto GCC61971::co = folly::makeFixedString("co")
Definition at line 677 of file FixedStringTest.cpp.
Referenced by testing::gmock_matchers_test::ConstPropagatingPtr< T >::operator*(), TEST(), and testing::gmock_matchers_test::TEST().
constexpr auto GCC61971::dot = folly::makeFixedString(".")
Definition at line 671 of file FixedStringTest.cpp.
Referenced by fizz::server::CertManager::getCert(), and wangle::SSLContextManager::getSSLCtxBySuffix().
constexpr auto GCC61971::xyz = folly::makeFixedString("xyz")
Definition at line 670 of file FixedStringTest.cpp.