proxygen: gtest_env_var_test Namespace Reference
gtest_env_var_test Namespace Reference
Classes
class GTestEnvVarTest
Functions
def AssertEq (expected, actual)
def SetEnvVar (env_var, value)
def GetFlag (flag)
def TestFlag (flag, test_val, default_val)
Variables
string __author__ = 'wan@google.com (Zhanyong Wan)'
string IS_WINDOWS = 'nt'
string IS_LINUX = 'posix'
COMMAND = gtest_test_utils.GetTestExecutablePath('gtest_env_var_test_')
environ = os.environ.copy()
Function Documentation
def gtest_env_var_test.AssertEq (expected, actual)
Definition at line 48 of file gtest_env_var_test.py.
Referenced by TestFlag(), gtest_env_var_test.GTestEnvVarTest.testXmlOutputFile(), and gtest_env_var_test.GTestEnvVarTest.testXmlOutputFileOverride().
 def AssertEq(expected, actual):
   if expected != actual:
     print('Expected: %s' % (expected,))
     print('  Actual: %s' % (actual,))
     raise AssertionError
def gtest_env_var_test.GetFlag (flag)
Runs gtest_env_var_test_ and returns its output.
Definition at line 64 of file gtest_env_var_test.py.
Referenced by TestFlag(), gtest_env_var_test.GTestEnvVarTest.testXmlOutputFile(), and gtest_env_var_test.GTestEnvVarTest.testXmlOutputFileOverride().
 def GetFlag(flag):
   """Runs gtest_env_var_test_ and returns its output."""
   args = [COMMAND]
   if flag is not None:
     args += [flag]
   return gtest_test_utils.Subprocess(args, env=environ).output
def gtest_env_var_test.SetEnvVar (env_var, value)
Sets the env variable to 'value'; unsets it when 'value' is None.
Definition at line 55 of file gtest_env_var_test.py.
Referenced by gtest_env_var_test.GTestEnvVarTest.testEnvVarAffectsFlag(), TestFlag(), gtest_env_var_test.GTestEnvVarTest.testXmlOutputFile(), and gtest_env_var_test.GTestEnvVarTest.testXmlOutputFileOverride().
 def SetEnvVar(env_var, value):
   """Sets the env variable to 'value'; unsets it when 'value' is None."""
   if value is not None:
     environ[env_var] = value
   elif env_var in environ:
     del environ[env_var]
def gtest_env_var_test.TestFlag (flag, test_val, default_val)
Verifies that the given flag is affected by the corresponding env var.
Definition at line 73 of file gtest_env_var_test.py.
References AssertEq(), GetFlag(), and SetEnvVar().
Referenced by gtest_env_var_test.GTestEnvVarTest.testEnvVarAffectsFlag().
 def TestFlag(flag, test_val, default_val):
   """Verifies that the given flag is affected by the corresponding env var."""
   env_var = 'GTEST_' + flag.upper()
   SetEnvVar(env_var, test_val)
   AssertEq(test_val, GetFlag(flag))
   SetEnvVar(env_var, None)
   AssertEq(default_val, GetFlag(flag))
Variable Documentation
string gtest_env_var_test.__author__ = 'wan@google.com (Zhanyong Wan)' private
Definition at line 34 of file gtest_env_var_test.py.
gtest_env_var_test.COMMAND = gtest_test_utils.GetTestExecutablePath('gtest_env_var_test_')
Definition at line 43 of file gtest_env_var_test.py.
gtest_env_var_test.environ = os.environ.copy()
Definition at line 45 of file gtest_env_var_test.py.
string gtest_env_var_test.IS_LINUX = 'posix'
Definition at line 41 of file gtest_env_var_test.py.
string gtest_env_var_test.IS_WINDOWS = 'nt'
Definition at line 40 of file gtest_env_var_test.py.