proxygen: folly::io::compression::detail Namespace Reference
folly::io::compression::detail Namespace Reference
Functions
template<typename T >
std::enable_if< std::is_unsigned< T >::value, bool >::type dataStartsWithLE (const IOBuf *data, T prefix, uint64_t n=sizeof(T))
template<typename T >
std::enable_if< std::is_arithmetic< T >::value, std::string >::type prefixToStringLE (T prefix, uint64_t n=sizeof(T))
Function Documentation
template<typename T > std::enable_if<std::is_unsigned<T>::value, bool>::type folly::io::compression::detail::dataStartsWithLE (const IOBuf * data, T prefix, uint64_t n = sizeof(T))
Reads sizeof(T) bytes, and returns false if not enough bytes are available. Returns true if the first n bytes are equal to prefix when interpreted as a little endian T.
Definition at line 40 of file Utils.h.
References string, folly::T, type, value, and folly::value().
Referenced by folly::io::StreamCodec::doUncompress().
{
   DCHECK_GT(n, 0);
   DCHECK_LE(n, sizeof(T));
   T value;
   Cursor cursor{data};
   if (!cursor.tryReadLE(value)) {
     return false;
   }
   const T mask = n == sizeof(T) ? T(-1) : (T(1) << (8 * n)) - 1;
   return prefix == (value & mask);
 }
template<typename T > std::enable_if<std::is_arithmetic<T>::value, std::string>::type folly::io::compression::detail::prefixToStringLE (T prefix, uint64_t n = sizeof(T))
Definition at line 54 of file Utils.h.
References folly::Endian::little(), string, and folly::T.
Referenced by folly::io::StreamCodec::doUncompress().
{
   DCHECK_GT(n, 0);
   DCHECK_LE(n, sizeof(T));
   prefix = Endian::little(prefix);
   std::string result;
   result.resize(n);
   memcpy(&result[0], &prefix, n);
   return result;
 }