proxygen: folly::compression::instructions Namespace Reference
folly::compression::instructions Namespace Reference
Classes
struct Default
struct Haswell
struct Nehalem
Enumerations
enum Type { Type::DEFAULT, Type::NEHALEM, Type::HASWELL }
Functions
Type detect ()
template<class F >
auto dispatch (Type type, F &&f) -> decltype(f(std::declval< Default >()))
template<class F >
auto dispatch (F &&f) -> decltype(f(std::declval< Default >()))
Enumeration Type Documentation
enum folly::compression::instructions::Type strong
Enumerator
DEFAULT
NEHALEM
HASWELL
Definition at line 152 of file Instructions.h.
                 {
   DEFAULT,
   NEHALEM,
   HASWELL,
 };
Function Documentation
Type folly::compression::instructions::detect () inline
Definition at line 158 of file Instructions.h.
References DEFAULT, HASWELL, NEHALEM, folly::compression::instructions::Nehalem::supported(), folly::compression::instructions::Haswell::supported(), and type.
Referenced by dispatch().
                      {
   const static Type type = [] {
     if (instructions::Haswell::supported()) {
       VLOG(2) << "Will use folly::compression::instructions::Haswell";
       return Type::HASWELL;
     } else if (instructions::Nehalem::supported()) {
       VLOG(2) << "Will use folly::compression::instructions::Nehalem";
       return Type::NEHALEM;
     } else {
       VLOG(2) << "Will use folly::compression::instructions::Default";
       return Type::DEFAULT;
     }
   }();
   return type;
 }
template<class F > auto folly::compression::instructions::dispatch (Type type, F && f) -> decltype(f(std::declval<Default>()))
Definition at line 175 of file Instructions.h.
References folly::assume_unreachable(), DEFAULT, f, HASWELL, NEHALEM, and type.
Referenced by dispatch(), folly::compression::dispatchInstructions(), folly::pushmi::strand_queue_base< E >::front(), folly::compression::instructionsOverride(), and folly::pushmi::time_source_queue_base< E, TP >::top().
{
   switch (type) {
     case Type::HASWELL:
       return f(Haswell());
     case Type::NEHALEM:
       return f(Nehalem());
     case Type::DEFAULT:
       return f(Default());
   }
   assume_unreachable();
 }
template<class F > auto folly::compression::instructions::dispatch (F && f) -> decltype(f(std::declval<Default>()))
Definition at line 189 of file Instructions.h.
References detect(), dispatch(), and f.
{
   return dispatch(detect(), std::forward<F>(f));
 }