proxygen: folly::fibers::detail Namespace Reference
folly::fibers::detail Namespace Reference
Classes
struct ExtractFirstArg
struct ExtractFirstArg< Ret(First, Args...)>
struct ExtractFirstArg< Ret(T::*)(First, Args...) const >
struct ExtractFirstArg< Ret(T::*)(First, Args...)>
Functions
std::string createABDTokenNotDispatchedExMsg (const std::vector< size_t > &vecTokensNotDispatched)
std::string createUnexpectedNumResultsABDUsageExMsg (size_t numExpectedResults, size_t numActualResults)
Detailed Description
For any functor F taking >= 1 argument, FirstArgOf<F>::type is the type of F's first parameter.
Rationale: we want to declare a function func(F), where F has the signature void(X) and func should return T<X> (T and X are some types). Solution:
template <typename f>=""> T<typename FirstArgOf<F>::type> func(F&& f);
Function Documentation
std::string folly::fibers::detail::createABDTokenNotDispatchedExMsg (const std::vector< size_t > & vecTokensNotDispatched)
Definition at line 23 of file AtomicBatchDispatcher.cpp.
References i, folly::sformat(), and string.
Referenced by folly::fibers::AtomicBatchDispatcher< InputT, ResultT >::DispatchBaton< InputT, ResultT >::fulfillPromises().
{
   size_t numTokensNotDispatched = vecTokensNotDispatched.size();
   assert(numTokensNotDispatched > 0);
   size_t numSeqNumToPrint =
       (numTokensNotDispatched > 10 ? 10 : numTokensNotDispatched);
   std::string strInputsNotFound =
       folly::sformat("{}", vecTokensNotDispatched[0]);
   for (size_t i = 1; i < numSeqNumToPrint; ++i) {
     strInputsNotFound += folly::sformat(", {}", vecTokensNotDispatched[i]);
   }
   if (numSeqNumToPrint < numTokensNotDispatched) {
     strInputsNotFound += "...";
   }
   return folly::sformat(
       "{} input tokens (seq nums: {}) destroyed before calling dispatch",
       numTokensNotDispatched,
       strInputsNotFound);
 }
std::string folly::fibers::detail::createUnexpectedNumResultsABDUsageExMsg (size_t numExpectedResults, size_t numActualResults)
Definition at line 43 of file AtomicBatchDispatcher.cpp.
References folly::sformat().
Referenced by folly::fibers::AtomicBatchDispatcher< InputT, ResultT >::DispatchBaton< InputT, ResultT >::fulfillPromises().
{
   return folly::sformat(
       "Unexpected number of results ({}) returned from dispatch function, "
       "expected ({})",
       numActualResults,
       numExpectedResults);
 }