proxygen: folly::threadlocal_detail Namespace Reference
folly::threadlocal_detail Namespace Reference
Classes
struct ElementWrapper
class PthreadKeyUnregister
struct PthreadKeyUnregisterTester
struct static_meta_of
struct static_meta_of< ThreadLocal< T, Tag, AccessMode > >
struct static_meta_of< ThreadLocalPtr< T, Tag, AccessMode > >
struct StaticMeta
struct StaticMetaBase
struct ThreadEntry
struct ThreadEntryList
struct ThreadEntryNode
Variables
constexpr uint32_t kEntryIDInvalid = std::numeric_limits<uint32_t>::max()
Variable Documentation
constexpr uint32_t folly::threadlocal_detail::kEntryIDInvalid = std::numeric_limits<uint32_t>::max()
Definition at line 61 of file ThreadLocalDetail.h.
Referenced by folly::threadlocal_detail::StaticMetaBase::allocate(), folly::threadlocal_detail::StaticMetaBase::destroy(), folly::threadlocal_detail::StaticMetaBase::EntryID::EntryID(), and folly::threadlocal_detail::StaticMetaBase::EntryID::operator=().