proxygen: proxygen/folly/folly/experimental/test/NestedCommandLineAppTestHelper.cpp File Reference
NestedCommandLineAppTestHelper.cpp File Reference
#include <folly/experimental/NestedCommandLineApp.h>
#include <folly/portability/GFlags.h>
Functions
DEFINE_int32 (global_foo, 42,"Global foo")
int main (int argc, char *argv[])
Function Documentation
DEFINE_int32 (global_foo , 42 , "Global foo")
int main (int argc, char * argv[])
Definition at line 45 of file NestedCommandLineAppTestHelper.cpp.
References folly::NestedCommandLineApp::addAlias(), folly::NestedCommandLineApp::addCommand(), folly::NestedCommandLineApp::addGFlags(), bm::init(), and folly::NestedCommandLineApp::run().
{
   folly::NestedCommandLineApp app("", "0.1", "", "", init);
   app.addGFlags();
   // clang-format off
   app.addCommand("foo", "[args...]", "Do some foo", "Does foo", foo)
     .add_options()
       ("local-foo", po::value<int32_t>()->default_value(42), "Local foo");
   // clang-format on
   app.addAlias("bar", "foo");
   app.addAlias("baz", "bar");
   return app.run(argc, argv);
 }