proxygen: proxygen/folly/folly/experimental/test/NestedCommandLineAppExample.cpp File Reference
NestedCommandLineAppExample.cpp File Reference
#include <folly/ScopeGuard.h>
#include <folly/String.h>
#include <folly/experimental/NestedCommandLineApp.h>
#include <folly/experimental/ProgramOptions.h>
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 166 of file NestedCommandLineAppExample.cpp.
References folly::NestedCommandLineApp::addCommand(), folly::NestedCommandLineApp::addGFlags(), and folly::NestedCommandLineApp::run().
{
   // Initialize a NestedCommandLineApp object.
   //
   // The first argument is the program name -- an empty string will cause the
   // program name to be deduced from the executable name, which is usually
   // fine. The second argument is a version string.
   //
   // You may also add an "initialization function" that is always called
   // for every valid command before the command is executed.
   folly::NestedCommandLineApp app("", "0.1");
   // Add any GFlags-defined flags. These are global flags, and so they should
   // be valid for any command.
   app.addGFlags();
   // Add any commands. For our example, we'll implement simplified versions
   // of "cat" and "echo". Note that addCommand() returns a reference to a
   // boost::program_options object that you may use to add command-specific
   // options.
   // clang-format off
   app.addCommand(
       // command name
       "cat",
       // argument description
       "[file...]",
       // short help string
       "Concatenate files and print them on standard output",
       // Long help string
       "Concatenate files and print them on standard output.",
       // Function to execute
       runCat)
     .add_options()
       ("number,n", po::bool_switch(), "number all output lines");
   // clang-format on
   // clang-format off
   app.addCommand(
       "echo",
       "[string...]",
       "Display a line of text",
       "Display a line of text.",
       runEcho)
     .add_options()
       (",n", po::bool_switch(), "do not output the trailing newline");
   // clang-format on
   // You may also add command aliases -- that is, multiple command names
   // that do the same thing; see addAlias().
   // app.run returns an appropriate error code
   return app.run(argc, argv);
 }