proxygen: proxygen/folly/folly/io/test/NetworkBenchmark.cpp File Reference
NetworkBenchmark.cpp File Reference
#include <vector>
#include <folly/Benchmark.h>
#include <folly/io/Cursor.h>
#include <folly/io/IOBuf.h>
#include <folly/portability/GFlags.h>
Functions
BENCHMARK (reserveBenchmark, iters)
BENCHMARK (chainBenchmark, iters)
unique_ptr< IOBuf > poolGetIOBuf ()
void poolPutIOBuf (unique_ptr< IOBuf > &&buf)
BENCHMARK (poolBenchmark, iters)
void setNumbers (size_t size, size_t num)
int main (int argc, char **argv)
Variables
size_t buf_size = 0
size_t num_bufs = 0
vector< unique_ptr< IOBuf > > bufPool
Function Documentation
BENCHMARK (reserveBenchmark , iters)
Definition at line 32 of file NetworkBenchmark.cpp.
References folly::IOBuf::append(), buf_size, folly::IOBuf::create(), num_bufs, and folly::IOBuf::reserve().
{
   while (iters--) {
     unique_ptr<IOBuf> iobuf1(IOBuf::create(buf_size));
     iobuf1->append(buf_size);
     for (size_t bufs = num_bufs; bufs > 1; bufs--) {
       iobuf1->reserve(0, buf_size);
       iobuf1->append(buf_size);
     }
   }
 }
BENCHMARK (chainBenchmark , iters)
Definition at line 43 of file NetworkBenchmark.cpp.
References folly::IOBuf::append(), buf_size, folly::IOBuf::create(), folly::gen::move, num_bufs, and folly::IOBuf::prependChain().
{
   while (iters--) {
     unique_ptr<IOBuf> iobuf1(IOBuf::create(buf_size));
     iobuf1->append(buf_size);
     for (size_t bufs = num_bufs; bufs > 1; bufs--) {
       unique_ptr<IOBuf> iobufNext(IOBuf::create(buf_size));
       iobuf1->prependChain(std::move(iobufNext));
     }
   }
 }
BENCHMARK (poolBenchmark , iters)
Definition at line 76 of file NetworkBenchmark.cpp.
References folly::gen::move, num_bufs, poolGetIOBuf(), poolPutIOBuf(), and folly::IOBuf::prependChain().
{
   while (iters--) {
     unique_ptr<IOBuf> head = poolGetIOBuf();
     for (size_t bufs = num_bufs; bufs > 1; bufs--) {
       unique_ptr<IOBuf> iobufNext = poolGetIOBuf();
       head->prependChain(std::move(iobufNext));
     }
     // cleanup
     poolPutIOBuf(std::move(head));
   }
 }
int main (int argc, char ** argv)
Definition at line 151 of file NetworkBenchmark.cpp.
References folly::runBenchmarks(), and setNumbers().
{
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   setNumbers(10, 10);
   folly::runBenchmarks();
   setNumbers(100, 10);
   folly::runBenchmarks();
   setNumbers(2048, 10);
   folly::runBenchmarks();
   setNumbers(10000, 10);
   folly::runBenchmarks();
   setNumbers(100000, 10);
   folly::runBenchmarks();
   setNumbers(1000000, 10);
   folly::runBenchmarks();
   setNumbers(10, 20);
   folly::runBenchmarks();
   return 0;
 }
unique_ptr<IOBuf> poolGetIOBuf () inline
Definition at line 55 of file NetworkBenchmark.cpp.
References folly::IOBuf::append(), buf_size, folly::IOBuf::create(), and folly::gen::move.
Referenced by BENCHMARK().
{
   if (bufPool.size() > 0) {
     unique_ptr<IOBuf> ret = std::move(bufPool.back());
     bufPool.pop_back();
     return ret;
   } else {
     unique_ptr<IOBuf> iobuf(IOBuf::create(buf_size));
     iobuf->append(buf_size);
     return iobuf;
   }
 }
void poolPutIOBuf (unique_ptr< IOBuf > && buf) inline
Definition at line 67 of file NetworkBenchmark.cpp.
References folly::gen::move, cpp.ast::next(), and folly::IOBuf::pop().
Referenced by BENCHMARK().
{
   unique_ptr<IOBuf> head = std::move(buf);
   while (head) {
     unique_ptr<IOBuf> next = head->pop();
     bufPool.push_back(std::move(head));
     head = std::move(next);
   }
 }
void setNumbers (size_t size, size_t num)
Definition at line 88 of file NetworkBenchmark.cpp.
References buf_size, num_bufs, and folly::size().
Referenced by main().
{
   buf_size = size;
   num_bufs = num;
   bufPool.clear();
   printf("\nBuffer size: %zu, number of buffers: %zu\n\n", size, num);
 }
Variable Documentation
size_t buf_size = 0
Definition at line 29 of file NetworkBenchmark.cpp.
Referenced by BENCHMARK(), poolGetIOBuf(), and setNumbers().
vector<unique_ptr<IOBuf> > bufPool
Definition at line 54 of file NetworkBenchmark.cpp.
size_t num_bufs = 0
Definition at line 30 of file NetworkBenchmark.cpp.
Referenced by BENCHMARK(), and setNumbers().