proxygen: proxygen/folly/folly/io/async/test/NotificationQueueBenchmark.cpp File Reference
NotificationQueueBenchmark.cpp File Reference
#include <folly/Benchmark.h>
#include <folly/io/async/EventBase.h>
#include <folly/synchronization/Baton.h>
#include <condition_variable>
#include <mutex>
#include <thread>
Functions
void runTest (int iters, int numThreads)
int main (int argc, char *argv[])
Variables
static size_t constexpr kMaxRead = 20
Function Documentation
int main (int argc, char * argv[])
Definition at line 85 of file NotificationQueueBenchmark.cpp.
References argv, and folly::runBenchmarks().
{
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   folly::runBenchmarks();
   return 0;
 }
void runTest (int iters, int numThreads)
Definition at line 28 of file NotificationQueueBenchmark.cpp.
References BENCHMARK_PARAM, folly::BenchmarkSuspender::dismiss(), i, kMaxRead, folly::EventBase::loopForever(), m, mutex, folly::BenchmarkSuspender::rehire(), folly::EventBase::runInEventBaseThread(), folly::EventBase::setMaxReadAtOnce(), folly::pushmi::detail::t, folly::EventBase::terminateLoopSoon(), and threads.
{
   BenchmarkSuspender susp;
   EventBase evb;
   evb.setMaxReadAtOnce(kMaxRead);
   std::mutex m;
   std::condition_variable cv;
   int numRunning = 0;
   int numProcessed = 0;
   int numTotal = iters * numThreads;
   std::vector<std::thread> threads;
   for (int i = 0; i < numThreads; i++) {
     threads.push_back(std::thread([&]() mutable {
       // wait for all the threads to start up
       bool notifyAll = false;
       {
         std::lock_guard<std::mutex> lk(m);
         if (++numRunning == numThreads) {
           notifyAll = true;
           susp.dismiss();
         }
       }
       if (notifyAll) {
         cv.notify_all();
       } else {
         std::unique_lock<std::mutex> lk(m);
         cv.wait(lk, [&]() { return numRunning == numThreads; });
       }
       for (auto j = 0; j < iters; j++) {
         evb.runInEventBaseThread([&]() mutable {
           if (++numProcessed == numTotal) {
             evb.terminateLoopSoon();
             ;
           }
         });
       }
     }));
   }
   evb.loopForever();
   susp.rehire();
   for (auto& t : threads) {
     t.join();
   }
 }
Variable Documentation
size_t constexpr kMaxRead = 20 static
Definition at line 26 of file NotificationQueueBenchmark.cpp.
Referenced by runTest().