proxygen: proxygen/wangle/wangle/channel/broadcast/test/ObservingClientPipelineTest.cpp File Reference
ObservingClientPipelineTest.cpp File Reference
#include "wangle/bootstrap/ServerBootstrap.h"
#include "wangle/bootstrap/ClientBootstrap.h"
#include "wangle/channel/Handler.h"
#include "wangle/channel/broadcast/ObservingHandler.h"
#include <glog/logging.h>
#include <folly/portability/GTest.h>
Classes
struct TestRoutingData
class TestPipelineFactory
class CustomPipelineFactory
class CustomPipelineMakerTestClient
Typedefs
using BytesPipeline = Pipeline< IOBufQueue &, std::unique_ptr< IOBuf >>
using TestObsPipeline = ObservingPipeline< std::shared_ptr< folly::IOBuf >>
using TestServer = ServerBootstrap< BytesPipeline >
using TestClient = ClientBootstrap< TestObsPipeline >
Functions
TEST (ObservingClientPipelineTest, CustomPipelineMaker)
Typedef Documentation
using BytesPipeline = Pipeline<IOBufQueue&, std::unique_ptr<IOBuf>>
Definition at line 28 of file ObservingClientPipelineTest.cpp.
using TestClient = ClientBootstrap<TestObsPipeline>
Definition at line 32 of file ObservingClientPipelineTest.cpp.
using TestObsPipeline = ObservingPipeline<std::shared_ptr<folly::IOBuf>>
Definition at line 29 of file ObservingClientPipelineTest.cpp.
using TestServer = ServerBootstrap<BytesPipeline>
Definition at line 31 of file ObservingClientPipelineTest.cpp.
Function Documentation
TEST (ObservingClientPipelineTest , CustomPipelineMaker)
Definition at line 113 of file ObservingClientPipelineTest.cpp.
References TestRoutingData::data, EXPECT_EQ, folly::EventBaseManager::get(), TestServer::getAddress(), and folly::EventBaseManager::getEventBase().
{
   TestServer server;
   auto factory = std::make_shared<TestPipelineFactory>();
   server.childPipeline(factory);
   server.bind(0);
   auto base = EventBaseManager::get()->getEventBase();
   SocketAddress address;
   server.getSockets()[0]->getAddress(&address);
   TestRoutingData routingData;
   routingData.data = "Test";
   auto clientPipelineFactory = std::make_shared<CustomPipelineFactory>();
   auto client =
     std::make_unique<CustomPipelineMakerTestClient>(
         routingData, clientPipelineFactory);
   client->connect(address, std::chrono::milliseconds(0));
   base->loop();
   server.stop();
   server.join();
   EXPECT_EQ(1, clientPipelineFactory->routingPipelines_);
   EXPECT_EQ(routingData, clientPipelineFactory->routingData_);
   EXPECT_EQ(0, clientPipelineFactory->pipelines_);
 }