proxygen: proxygen/folly/folly/ssl/test/OpenSSLHashTest.cpp File Reference
OpenSSLHashTest.cpp File Reference
#include <folly/ssl/OpenSSLHash.h>
#include <folly/io/IOBufQueue.h>
#include <folly/portability/GTest.h>
Functions
TEST_F (OpenSSLHashTest, sha256)
TEST_F (OpenSSLHashTest, sha256_hashcopy)
TEST_F (OpenSSLHashTest, sha256_hashcopy_intermediate)
TEST_F (OpenSSLHashTest, hmac_sha256)
Function Documentation
TEST_F (OpenSSLHashTest , sha256)
Definition at line 31 of file OpenSSLHashTest.cpp.
References folly::IOBuf::computeChainDataLength(), folly::IOBuf::countChainElements(), EXPECT_EQ, folly::IOBuf::prependChain(), folly::gen::range(), and folly::ssl::SHA256.
{
   IOBuf buf;
   buf.prependChain(IOBuf::wrapBuffer(ByteRange(StringPiece("foo"))));
   buf.prependChain(IOBuf::wrapBuffer(ByteRange(StringPiece("bar"))));
   EXPECT_EQ(3, buf.countChainElements());
   EXPECT_EQ(6, buf.computeChainDataLength());
   auto expected = vector<uint8_t>(32);
   auto combined = ByteRange(StringPiece("foobar"));
   SHA256(combined.data(), combined.size(), expected.data());
   auto out = vector<uint8_t>(32);
   OpenSSLHash::sha256(range(out), buf);
   EXPECT_EQ(expected, out);
 }
TEST_F (OpenSSLHashTest , sha256_hashcopy)
Definition at line 47 of file OpenSSLHashTest.cpp.
References folly::copy(), EXPECT_EQ, folly::ssl::OpenSSLHash::Digest::hash_final(), folly::ssl::OpenSSLHash::Digest::hash_init(), folly::ssl::OpenSSLHash::Digest::hash_update(), and folly::gen::range().
{
   std::array<uint8_t, 32> expected, actual;
   OpenSSLHash::Digest digest;
   digest.hash_init(EVP_sha256());
   digest.hash_update(ByteRange(StringPiece("foobar")));
   OpenSSLHash::Digest copy(digest);
   digest.hash_final(range(expected));
   copy.hash_final(range(actual));
   EXPECT_EQ(expected, actual);
 }
TEST_F (OpenSSLHashTest , sha256_hashcopy_intermediate)
Definition at line 62 of file OpenSSLHashTest.cpp.
References folly::copy(), EXPECT_EQ, folly::ssl::OpenSSLHash::Digest::hash_final(), folly::ssl::OpenSSLHash::Digest::hash_init(), folly::ssl::OpenSSLHash::Digest::hash_update(), and folly::gen::range().
{
   std::array<uint8_t, 32> expected, actual;
   OpenSSLHash::Digest digest;
   digest.hash_init(EVP_sha256());
   digest.hash_update(ByteRange(StringPiece("foo")));
   OpenSSLHash::Digest copy(digest);
   digest.hash_update(ByteRange(StringPiece("bar")));
   copy.hash_update(ByteRange(StringPiece("bar")));
   digest.hash_final(range(expected));
   copy.hash_final(range(actual));
   EXPECT_EQ(expected, actual);
 }
TEST_F (OpenSSLHashTest , hmac_sha256)
Definition at line 80 of file OpenSSLHashTest.cpp.
References folly::IOBuf::computeChainDataLength(), folly::IOBuf::countChainElements(), EXPECT_EQ, folly::IOBuf::prependChain(), and folly::gen::range().
{
   auto key = ByteRange(StringPiece("qwerty"));
   IOBuf buf;
   buf.prependChain(IOBuf::wrapBuffer(ByteRange(StringPiece("foo"))));
   buf.prependChain(IOBuf::wrapBuffer(ByteRange(StringPiece("bar"))));
   EXPECT_EQ(3, buf.countChainElements());
   EXPECT_EQ(6, buf.computeChainDataLength());
   auto expected = vector<uint8_t>(32);
   auto combined = ByteRange(StringPiece("foobar"));
   HMAC(
       EVP_sha256(),
       key.data(),
       int(key.size()),
       combined.data(),
       combined.size(),
       expected.data(),
       nullptr);
   auto out = vector<uint8_t>(32);
   OpenSSLHash::hmac_sha256(range(out), key, buf);
   EXPECT_EQ(expected, out);
 }