proxygen: proxygen/wangle/wangle/channel/test/OutputBufferingHandlerTest.cpp File Reference
OutputBufferingHandlerTest.cpp File Reference
#include <wangle/channel/StaticPipeline.h>
#include <wangle/channel/OutputBufferingHandler.h>
#include <wangle/channel/test/MockHandler.h>
#include <folly/io/async/AsyncSocket.h>
#include <gmock/gmock.h>
#include <gtest/gtest.h>
Typedefs
typedef StrictMock< MockHandlerAdapter< IOBufQueue &, std::unique_ptr< IOBuf > > > MockBytesHandler
Functions
MATCHER_P (IOBufContains, str,"")
TEST (OutputBufferingHandlerTest, Basic)
Typedef Documentation
typedef StrictMock<MockHandlerAdapter< IOBufQueue&, std::unique_ptr<IOBuf> > > MockBytesHandler
Definition at line 31 of file OutputBufferingHandlerTest.cpp.
Function Documentation
MATCHER_P (IOBufContains , str , "")
Definition at line 33 of file OutputBufferingHandlerTest.cpp.
 { return arg->moveToFbString() == str; }
TEST (OutputBufferingHandlerTest , Basic)
Definition at line 35 of file OutputBufferingHandlerTest.cpp.
References testing::_, folly::IOBuf::copyBuffer(), EXPECT_CALL, EXPECT_FALSE, EXPECT_TRUE, f, folly::EventBase::loopOnce(), folly::AsyncSocket::newSocket(), and folly::netops::socket().
{
   MockBytesHandler mockHandler;
   EXPECT_CALL(mockHandler, attachPipeline(_));
   auto pipeline = StaticPipeline<IOBufQueue&, std::unique_ptr<IOBuf>,
     MockBytesHandler,
     OutputBufferingHandler>::create(
       &mockHandler,
       OutputBufferingHandler());
   EventBase eb;
   auto socket = AsyncSocket::newSocket(&eb);
   pipeline->setTransport(socket);
   // Buffering should prevent writes until the EB loops, and the writes should
   // be batched into one write call.
   auto f1 = pipeline->write(IOBuf::copyBuffer("hello"));
   auto f2 = pipeline->write(IOBuf::copyBuffer("world"));
   EXPECT_FALSE(f1.isReady());
   EXPECT_FALSE(f2.isReady());
   EXPECT_CALL(mockHandler, write_(_, IOBufContains("helloworld")));
   eb.loopOnce();
   EXPECT_TRUE(f1.isReady());
   EXPECT_TRUE(f2.isReady());
   EXPECT_CALL(mockHandler, detachPipeline(_));
  // Make sure the SharedPromise resets correctly
   auto f = pipeline->write(IOBuf::copyBuffer("foo"));
   EXPECT_FALSE(f.isReady());
   EXPECT_CALL(mockHandler, write_(_, IOBufContains("foo")));
   eb.loopOnce();
   EXPECT_TRUE(f.isReady());
   pipeline.reset();
 }