proxygen: proxygen/folly/folly/test/PackedSyncPtrTest.cpp File Reference
PackedSyncPtrTest.cpp File Reference
#include <folly/PackedSyncPtr.h>
#include <cinttypes>
#include <thread>
#include <unordered_map>
#include <utility>
#include <folly/portability/GTest.h>
Classes
struct SyncVec< T >
Typedefs
typedef SyncVec< intptr_t > VecT
typedef std::unordered_map< int64_t, VecT > Map
Functions
TEST (PackedSyncPtr, Basic)
static Map map (mapCap)
void appThread (intptr_t id)
TEST (PackedSyncPtr, Application)
TEST (PackedSyncPtr, extraData)
Variables
const int mapCap = 1317
const int nthrs = 297
Typedef Documentation
typedef std::unordered_map<int64_t, VecT> Map
Definition at line 101 of file PackedSyncPtrTest.cpp.
typedef SyncVec<intptr_t> VecT
Definition at line 100 of file PackedSyncPtrTest.cpp.
Function Documentation
void appThread (intptr_t id)
Definition at line 108 of file PackedSyncPtrTest.cpp.
Referenced by TEST().
{
   for (auto& kv : map) {
     kv.second.lock();
     kv.second.push_back(id);
     kv.second.unlock();
   }
 }
static Map map (mapCap) static
Referenced by folly::AtomicHashArray< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::create(), folly::settings::Snapshot::forEachSetting(), testing::internal::GetThreadCount(), runSingleInsert(), runVisitContiguousRangesTest(), TEST(), TEST_F(), wangle::ServerWorkerPool::threadNotYetStopped(), and foo::StreamableTemplateInFoo< T >::value().
TEST (PackedSyncPtr , Basic)
Definition at line 42 of file PackedSyncPtrTest.cpp.
References EXPECT_EQ, folly::PackedSyncPtr< T >::extra(), folly::gen::first, folly::PackedSyncPtr< T >::get(), folly::PackedSyncPtr< T >::init(), folly::PackedSyncPtr< T >::lock(), folly::PackedSyncPtr< T >::set(), folly::PackedSyncPtr< T >::setExtra(), and folly::PackedSyncPtr< T >::unlock().
{
   PackedSyncPtr<std::pair<int, int>> sp;
   sp.init(new std::pair<int, int>[2]);
   EXPECT_EQ(sizeof(sp), 8);
   sp->first = 5;
   EXPECT_EQ(sp[0].first, 5);
   sp[1].second = 7;
   EXPECT_EQ(sp[1].second, 7);
   sp.lock();
   EXPECT_EQ(sp[1].second, 7);
   sp[0].first = 9;
   EXPECT_EQ(sp->first, 9);
   sp.unlock();
   EXPECT_EQ((sp.get() + 1)->second, 7);
   sp.lock();
   EXPECT_EQ(sp.extra(), 0);
   sp.setExtra(0x13);
   EXPECT_EQ(sp.extra(), 0x13);
   EXPECT_EQ((sp.get() + 1)->second, 7);
   delete[] sp.get();
   auto newP = new std::pair<int, int>();
   sp.set(newP);
   EXPECT_EQ(sp.extra(), 0x13);
   EXPECT_EQ(sp.get(), newP);
   sp.unlock();
   delete sp.get();
 }
TEST (PackedSyncPtr , Application)
Definition at line 116 of file PackedSyncPtrTest.cpp.
References appThread(), EXPECT_EQ, EXPECT_TRUE, i, int64_t, nthrs, and folly::pushmi::detail::t.
{
   for (int64_t i = 0; i < mapCap / 2; ++i) {
     map.insert(std::make_pair(i, VecT()));
   }
   std::vector<std::thread> thrs;
   for (intptr_t i = 0; i < nthrs; i++) {
     thrs.push_back(std::thread(appThread, i));
   }
   for (auto& t : thrs) {
     t.join();
   }
   for (auto& kv : map) {
     // Make sure every thread successfully inserted it's ID into every vec
     std::set<intptr_t> idsFound;
     for (auto& elem : kv.second) {
       EXPECT_TRUE(idsFound.insert(elem).second); // check for dups
     }
     EXPECT_EQ(idsFound.size(), nthrs); // check they are all there
   }
 }
TEST (PackedSyncPtr , extraData)
Definition at line 138 of file PackedSyncPtrTest.cpp.
References EXPECT_EQ, folly::PackedSyncPtr< T >::get(), folly::PackedSyncPtr< T >::init(), folly::PackedSyncPtr< T >::lock(), folly::PackedSyncPtr< T >::set(), and folly::PackedSyncPtr< T >::unlock().
{
   PackedSyncPtr<int> p;
   p.init();
   int* unaligned = reinterpret_cast<int*>(0xf003);
   p.lock();
   p.set(unaligned);
   uintptr_t* bytes = reinterpret_cast<uintptr_t*>(&p);
   LOG(INFO) << "Bytes integer is: 0x" << std::hex << *bytes;
   EXPECT_EQ(p.get(), unaligned);
   p.unlock();
 }
Variable Documentation
const int mapCap = 1317
Definition at line 102 of file PackedSyncPtrTest.cpp.
const int nthrs = 297
Definition at line 103 of file PackedSyncPtrTest.cpp.
Referenced by TEST().