proxygen: proxygen/folly/folly/gen/test/ParallelTest.cpp File Reference
ParallelTest.cpp File Reference
#include <array>
#include <iostream>
#include <memory>
#include <vector>
#include <glog/logging.h>
#include <folly/gen/Base.h>
#include <folly/gen/Parallel.h>
#include <folly/portability/GTest.h>
Functions
TEST (ParallelTest, Serial)
TEST (ParallelTest, ComputeBound64)
TEST (ParallelTest, Take)
TEST (ParallelTest, Unique)
TEST (ParallelTest, PSum)
int main (int argc, char *argv[])
Variables
const auto square = [](int i) { return i * i; }
const auto even = [](int i) { return 0 == i % 2; }
static auto sleepyWork
static auto isPrime
struct {
} makeUnique
static auto primes = seq(1, 1 << 14) | filter(isPrime) | as<vector<size_t>>()
static auto primeFactors
auto heavyWork = map(primeFactors)
Function Documentation
int main (int argc, char * argv[])
Definition at line 108 of file ParallelTest.cpp.
References testing::InitGoogleTest(), and RUN_ALL_TESTS().
{
   testing::InitGoogleTest(&argc, argv);
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   return RUN_ALL_TESTS();
 }
TEST (ParallelTest , Serial)
Definition at line 66 of file ParallelTest.cpp.
References even, EXPECT_EQ, folly::gen::filter(), folly::gen::map(), folly::gen::parallel(), folly::gen::seq(), square, and folly::gen::sum.
{
   EXPECT_EQ(
       seq(1, 10) | map(square) | filter(even) | sum,
       seq(1, 10) | parallel(map(square) | filter(even)) | sum);
 }
TEST (ParallelTest , ComputeBound64)
Definition at line 74 of file ParallelTest.cpp.
References EXPECT_EQ, heavyWork, folly::gen::parallel(), and folly::gen::sum.
{
   int length = 1 << 10;
   EXPECT_EQ(
       seq<size_t>(1, length) | heavyWork | sum,
       seq<size_t>(1, length) | parallel(heavyWork) | sum);
 }
TEST (ParallelTest , Take)
Definition at line 81 of file ParallelTest.cpp.
References folly::gen::count, EXPECT_EQ, heavyWork, folly::gen::parallel(), folly::gen::seq(), and folly::gen::take().
{
   int length = 1 << 18;
   int limit = 1 << 14;
   EXPECT_EQ(
       seq(1, length) | take(limit) | count,
       seq(1, length) | parallel(heavyWork) | take(limit) | count);
 }
TEST (ParallelTest , Unique)
Definition at line 89 of file ParallelTest.cpp.
References folly::gen::count, folly::gen::dereference, EXPECT_EQ, folly::gen::from(), makeUnique, folly::gen::map(), folly::gen::parallel(), primes, and folly::gen::take().
{
   auto uniqued = from(primes) | map(makeUnique) | as<vector>();
   EXPECT_EQ(
       primes.size(),
       from(primes) | parallel(map(makeUnique)) |
           parallel(dereference | map(makeUnique)) | dereference | count);
   EXPECT_EQ(
       2,
       from(primes) | parallel(map(makeUnique)) |
           parallel(dereference | map(makeUnique)) | dereference | take(2) |
           count);
 }
TEST (ParallelTest , PSum)
Definition at line 102 of file ParallelTest.cpp.
References EXPECT_EQ, folly::gen::from(), folly::gen::map(), folly::gen::parallel(), primes, sleepyWork, folly::gen::sub(), and folly::gen::sum.
{
   EXPECT_EQ(
       from(primes) | map(sleepyWork) | sum,
       from(primes) | parallel(map(sleepyWork) | sub(sum)) | sum);
 }
Variable Documentation
const auto even = [](int i) { return 0 == i % 2; }
Definition at line 33 of file ParallelTest.cpp.
Referenced by TEST().
auto heavyWork = map(primeFactors)
Definition at line 72 of file ParallelTest.cpp.
Referenced by TEST().
auto isPrime static
Initial value:
= [](int n) {
  if (n < 2) {
    return false;
  } else if (n > 2) {
    for (int d = 3; d * d <= n; d += 2) {
      if (0 == n % d) {
        return false;
      }
    }
  }
  return true;
}
Definition at line 40 of file ParallelTest.cpp.
struct { ... } makeUnique
Referenced by TEST().
auto primeFactors static
Initial value:
= [](int n) {
  return from(primes) | filter([&](int d) { return 0 == n % d; }) | count;
}
Definition at line 62 of file ParallelTest.cpp.
auto primes = seq(1, 1 << 14) | filter(isPrime) | as<vector<size_t>>() static
Definition at line 60 of file ParallelTest.cpp.
Referenced by TEST().
auto sleepyWork static
Initial value:
= [](int i) {
  const auto sleepyTime = std::chrono::microseconds(100);
  std::this_thread::sleep_for(sleepyTime);
  return i;
}
Definition at line 34 of file ParallelTest.cpp.
Referenced by TEST().
const auto square = [](int i) { return i * i; }
Definition at line 32 of file ParallelTest.cpp.
Referenced by TEST().