proxygen: proxygen/folly/folly/gen/test/ParallelMapBenchmark.cpp File Reference
ParallelMapBenchmark.cpp File Reference
#include <algorithm>
#include <atomic>
#include <thread>
#include <vector>
#include <folly/Benchmark.h>
#include <folly/gen/Base.h>
#include <folly/gen/ParallelMap.h>
#include <folly/portability/Unistd.h>
Functions
DEFINE_int32 (threads, std::max(1,(int32_t) sysconf(_SC_NPROCESSORS_CONF)/2),"Num threads.")
size_t fib (int n)
BENCHMARK (FibSumMap, n)
BENCHMARK_RELATIVE (FibSumPmap, n)
BENCHMARK_RELATIVE (FibSumThreads, n)
int main (int argc, char *argv[])
Variables
constexpr int kFib = 35
Function Documentation
BENCHMARK (FibSumMap , n)
Definition at line 39 of file ParallelMapBenchmark.cpp.
References folly::doNotOptimizeAway(), fib(), folly::gen::map(), folly::gen::seq(), and folly::gen::sum.
{
   auto result = seq(1, (int)n) | map([](int) { return fib(kFib); }) | sum;
   folly::doNotOptimizeAway(result);
 }
BENCHMARK_RELATIVE (FibSumPmap , n)
Definition at line 44 of file ParallelMapBenchmark.cpp.
References folly::doNotOptimizeAway(), fib(), kNumThreads, folly::gen::pmap(), folly::gen::seq(), and folly::gen::sum.
{
   // Schedule more work: enough so that each worker thread does the
   // same amount as one FibSumMap.
   const size_t kNumThreads = FLAGS_threads;
   // clang-format off
   auto result =
     seq(1, (int)(n * kNumThreads))
     | pmap([](int) { return fib(kFib); }, kNumThreads)
     | sum;
   // clang-format on
   folly::doNotOptimizeAway(result);
 }
BENCHMARK_RELATIVE (FibSumThreads , n)
Definition at line 57 of file ParallelMapBenchmark.cpp.
References folly::doNotOptimizeAway(), fib(), i, kNumThreads, folly::gen::map(), folly::gen::seq(), and folly::gen::sum.
{
   // Schedule kNumThreads to execute the same code as FibSumMap.
   const size_t kNumThreads = FLAGS_threads;
   std::vector<std::thread> workers;
   workers.reserve(kNumThreads);
   auto fn = [n] {
     auto result = seq(1, (int)n) | map([](int) { return fib(kFib); }) | sum;
     folly::doNotOptimizeAway(result);
   };
   for (size_t i = 0; i < kNumThreads; i++) {
     workers.push_back(std::thread(fn));
   }
   for (auto& w : workers) {
     w.join();
   }
 }
DEFINE_int32 (threads , std::max(1,(int32_t) sysconf(_SC_NPROCESSORS_CONF)/2) , "Num threads.")
size_t fib (int n)
Definition at line 35 of file ParallelMapBenchmark.cpp.
Referenced by BENCHMARK(), and BENCHMARK_RELATIVE().
                   {
   return n <= 1 ? 1 : fib(n - 1) * fib(n - 2);
 }
int main (int argc, char * argv[])
Definition at line 88 of file ParallelMapBenchmark.cpp.
References folly::runBenchmarks().
{
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   folly::runBenchmarks();
   return 0;
 }
Variable Documentation
constexpr int kFib = 35
Definition at line 34 of file ParallelMapBenchmark.cpp.