proxygen: proxygen/folly/folly/synchronization/test/ParkingLotBenchmark.cpp File Reference
ParkingLotBenchmark.cpp File Reference
#include <thread>
#include <folly/synchronization/ParkingLot.h>
#include <folly/Benchmark.h>
#include <folly/detail/Futex.h>
#include <folly/synchronization/Baton.h>
#include <folly/synchronization/test/Barrier.h>
Functions
DEFINE_uint64 (threads, 32,"Number of threads for benchmark")
BENCHMARK (FutexNoWaitersWake, iters)
BENCHMARK_RELATIVE (ParkingLotNoWaitersWake, iters)
BENCHMARK (FutexWakeOne, iters)
BENCHMARK_RELATIVE (ParkingLotWakeOne, iters)
BENCHMARK (FutexWakeAll, iters)
BENCHMARK_RELATIVE (ParkingLotWakeAll, iters)
int main (int argc, char **argv)
Variables
ParkingLot lot
Function Documentation
BENCHMARK (FutexNoWaitersWake , iters)
Definition at line 32 of file ParkingLotBenchmark.cpp.
References b, folly::BenchmarkSuspender::dismiss(), folly::detail::futexWake(), i, folly::pushmi::detail::t, threads, and folly::test::Barrier::wait().
{
   BenchmarkSuspender susp;
   folly::detail::Futex<> fu;
   Barrier b(FLAGS_threads + 1);
   std::vector<std::thread> threads{FLAGS_threads};
   for (auto& t : threads) {
     t = std::thread([&]() {
       b.wait();
       for (auto i = 0u; i < iters; i++) {
         detail::futexWake(&fu, 1);
       }
     });
   }
   susp.dismiss();
   b.wait();
   for (auto& t : threads) {
     t.join();
   }
 }
BENCHMARK (FutexWakeOne , iters)
Definition at line 75 of file ParkingLotBenchmark.cpp.
References b, folly::BenchmarkSuspender::dismiss(), folly::detail::futexWait(), folly::detail::futexWake(), i, folly::pushmi::detail::t, threads, and folly::test::Barrier::wait().
{
   BenchmarkSuspender susp;
   folly::detail::Futex<> fu;
   Barrier b(FLAGS_threads + 1);
   std::vector<std::thread> threads{FLAGS_threads};
   for (auto& t : threads) {
     t = std::thread([&]() {
       b.wait();
       while (true) {
         detail::futexWait(&fu, 0);
         if (fu.load(std::memory_order_relaxed)) {
           return;
         }
       }
     });
   }
   susp.dismiss();
   b.wait();
   for (auto i = 0u; i < iters; i++) {
     detail::futexWake(&fu, 1);
   }
   fu.store(1);
   detail::futexWake(&fu, threads.size());
   for (auto& t : threads) {
     t.join();
   }
 }
BENCHMARK (FutexWakeAll , iters)
Definition at line 140 of file ParkingLotBenchmark.cpp.
References b, folly::BenchmarkSuspender::dismiss(), folly::detail::futexWait(), folly::detail::futexWake(), i, folly::pushmi::detail::t, threads, and folly::test::Barrier::wait().
{
   BenchmarkSuspender susp;
   Barrier b(FLAGS_threads + 1);
   folly::detail::Futex<> fu;
   std::atomic<bool> done{false};
   std::vector<std::thread> threads{FLAGS_threads};
   for (auto& t : threads) {
     t = std::thread([&]() {
       b.wait();
       while (true) {
         detail::futexWait(&fu, 0);
         if (done.load(std::memory_order_relaxed)) {
           return;
         }
       }
     });
   }
   susp.dismiss();
   b.wait();
   for (auto i = 0u; i < iters; i++) {
     detail::futexWake(&fu, threads.size());
   }
   fu.store(1);
   done = true;
   detail::futexWake(&fu, threads.size());
   for (auto& t : threads) {
     t.join();
   }
 }
BENCHMARK_RELATIVE (ParkingLotNoWaitersWake , iters)
Definition at line 54 of file ParkingLotBenchmark.cpp.
References b, folly::BenchmarkSuspender::dismiss(), i, folly::RetainContinue, folly::pushmi::detail::t, threads, folly::ParkingLot< Data >::unpark(), and folly::test::Barrier::wait().
{
   BenchmarkSuspender susp;
   Barrier b(FLAGS_threads + 1);
   std::vector<std::thread> threads{FLAGS_threads};
   for (auto& t : threads) {
     t = std::thread([&]() {
       b.wait();
       for (auto i = 0u; i < iters; i++) {
         lot.unpark(&lot, [](Unit) { return UnparkControl::RetainContinue; });
       }
     });
   }
   susp.dismiss();
   b.wait();
   for (auto& t : threads) {
     t.join();
   }
 }
BENCHMARK_RELATIVE (ParkingLotWakeOne , iters)
Definition at line 105 of file ParkingLotBenchmark.cpp.
References b, folly::BenchmarkSuspender::dismiss(), f, i, folly::ParkingLot< Data >::park(), folly::RemoveBreak, folly::RemoveContinue, folly::pushmi::detail::t, threads, folly::ParkingLot< Data >::unpark(), and folly::test::Barrier::wait().
{
   BenchmarkSuspender susp;
   std::atomic<bool> done{false};
   Barrier b(FLAGS_threads + 1);
   std::vector<std::thread> threads{FLAGS_threads};
   for (auto& t : threads) {
     t = std::thread([&]() {
       b.wait();
       while (true) {
         Unit f;
         lot.park(
             &done,
             f,
             [&] { return done.load(std::memory_order_relaxed) == 0; },
             [] {});
         if (done.load(std::memory_order_relaxed)) {
           return;
         }
       }
     });
   }
   susp.dismiss();
   b.wait();
   for (auto i = 0u; i < iters; i++) {
     lot.unpark(&done, [](Unit) { return UnparkControl::RemoveBreak; });
   }
   done = true;
   lot.unpark(&done, [](Unit) { return UnparkControl::RemoveContinue; });
   for (auto& t : threads) {
     t.join();
   }
 }
BENCHMARK_RELATIVE (ParkingLotWakeAll , iters)
Definition at line 172 of file ParkingLotBenchmark.cpp.
References b, folly::BenchmarkSuspender::dismiss(), f, i, folly::ParkingLot< Data >::park(), folly::RemoveContinue, folly::pushmi::detail::t, threads, folly::ParkingLot< Data >::unpark(), and folly::test::Barrier::wait().
{
   BenchmarkSuspender susp;
   Barrier b(FLAGS_threads + 1);
   std::atomic<bool> done{false};
   std::vector<std::thread> threads{FLAGS_threads};
   for (auto& t : threads) {
     t = std::thread([&]() {
       b.wait();
       while (true) {
         Unit f;
         lot.park(
             &done,
             f,
             [&] { return done.load(std::memory_order_relaxed) == 0; },
             [] {});
         if (done.load(std::memory_order_relaxed)) {
           return;
         }
       }
     });
   }
   susp.dismiss();
   b.wait();
   for (auto i = 0u; i < iters; i++) {
     lot.unpark(&done, [](Unit) { return UnparkControl::RemoveContinue; });
   }
   done = true;
   lot.unpark(&done, [](Unit) { return UnparkControl::RemoveContinue; });
   for (auto& t : threads) {
     t.join();
   }
 }
DEFINE_uint64 (threads , 32 , "Number of threads for benchmark")
int main (int argc, char ** argv)
Definition at line 207 of file ParkingLotBenchmark.cpp.
References folly::runBenchmarks().
{
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   folly::runBenchmarks();
 }
Variable Documentation
ParkingLot lot
Definition at line 30 of file ParkingLotBenchmark.cpp.
Referenced by TEST().