proxygen: proxygen/folly/folly/synchronization/test/ParkingLotTest.cpp File Reference
ParkingLotTest.cpp File Reference
#include <thread>
#include <folly/synchronization/ParkingLot.h>
#include <folly/portability/GTest.h>
#include <folly/synchronization/Baton.h>
Classes
class WaitableMutex
Functions
TEST (ParkingLot, multilot)
TEST (ParkingLot, LargeWord)
TEST (ParkingLot, WaitableMutexTest)
Function Documentation
TEST (ParkingLot , multilot)
Definition at line 26 of file ParkingLotTest.cpp.
References count, folly::data(), EXPECT_EQ, large, folly::Baton< MayBlock, Atom >::post(), folly::RemoveContinue, small, and folly::Baton< MayBlock, Atom >::wait().
{
   using SmallLot = ParkingLot<bool>;
   using LargeLot = ParkingLot<uint64_t>;
   SmallLot smalllot;
   LargeLot largelot;
   folly::Baton<> sb;
   folly::Baton<> lb;
   std::thread small([&]() {
     smalllot.park(0, false, [] { return true; }, [&]() { sb.post(); });
   });
   std::thread large([&]() {
     largelot.park(0, true, [] { return true; }, [&]() { lb.post(); });
   });
   sb.wait();
   lb.wait();
   int count = 0;
   smalllot.unpark(0, [&](bool data) {
     count++;
     EXPECT_EQ(data, false);
     return UnparkControl::RemoveContinue;
   });
   EXPECT_EQ(count, 1);
   count = 0;
   largelot.unpark(0, [&](bool data) {
     count++;
     EXPECT_EQ(data, true);
     return UnparkControl::RemoveContinue;
   });
   EXPECT_EQ(count, 1);
   small.join();
   large.join();
 }
TEST (ParkingLot , LargeWord)
Definition at line 64 of file ParkingLotTest.cpp.
References lot, and folly::ParkingLot< Data >::park().
{
   ParkingLot<uint64_t> lot;
   std::atomic<uint64_t> w{0};
   lot.park(0, false, [&]() { return w == 1; }, []() {});
   // Validate should return false, will hang otherwise.
 }
TEST (ParkingLot , WaitableMutexTest)
Definition at line 106 of file ParkingLotTest.cpp.
References g(), folly::kIsSanitizeThread, folly::futures::sleep(), folly::pushmi::detail::t, and WaitableMutex::wait().
{
   if (kIsSanitizeThread) {
     return;
   }
   std::atomic<bool> go{false};
   WaitableMutex mu;
   std::thread t([&]() {
     std::lock_guard<WaitableMutex> g(mu);
     mu.wait([&]() { return go == true; });
   });
   sleep(1);
   {
     std::lock_guard<WaitableMutex> g(mu);
     go = true;
   }
   t.join();
 }