proxygen: proxygen/wangle/wangle/acceptor/test/PeekingAcceptorHandshakeHelperTest.cpp File Reference
PeekingAcceptorHandshakeHelperTest.cpp File Reference
#include <wangle/acceptor/PeekingAcceptorHandshakeHelper.h>
#include <thread>
#include <folly/io/async/test/MockAsyncSSLSocket.h>
#include <folly/portability/GMock.h>
#include <folly/portability/GTest.h>
#include <wangle/acceptor/test/AcceptorHelperMocks.h>
Classes
class MockPeekingCallback
class PeekingAcceptorHandshakeHelperTest
Functions
TEST_F (PeekingAcceptorHandshakeHelperTest, TestPeekSuccess)
TEST_F (PeekingAcceptorHandshakeHelperTest, TestPeekNonSuccess)
TEST_F (PeekingAcceptorHandshakeHelperTest, TestPeek2ndSuccess)
TEST_F (PeekingAcceptorHandshakeHelperTest, TestEOFDuringPeek)
TEST_F (PeekingAcceptorHandshakeHelperTest, TestPeekErr)
TEST_F (PeekingAcceptorHandshakeHelperTest, TestDropDuringPeek)
TEST_F (PeekingAcceptorHandshakeHelperTest, TestDropAfterPeek)
Function Documentation
TEST_F (PeekingAcceptorHandshakeHelperTest , TestPeekSuccess)
Definition at line 95 of file PeekingAcceptorHandshakeHelperTest.cpp.
References testing::_, callback_, EXPECT_CALL, folly::gen::move, and testing::Return().
{
   helper_->start(std::move(sockPtr_), &callback_);
   // first 2 bytes of SSL3+.
   std::vector<uint8_t> buf(2);
   buf[0] = 0x16;
   buf[1] = 0x03;
   EXPECT_CALL(mockPeekCallback1_, getHelperInternal(_, _, _, _))
     .WillOnce(Return(helperPtr_.release()));
   EXPECT_CALL(*innerHelper_, startInternal(_, _));
   helper_->peekSuccess(buf);
 }
TEST_F (PeekingAcceptorHandshakeHelperTest , TestPeekNonSuccess)
Definition at line 107 of file PeekingAcceptorHandshakeHelperTest.cpp.
References testing::_, callback_, EXPECT_CALL, folly::gen::move, and testing::Return().
{
   helper_->start(std::move(sockPtr_), &callback_);
   // first 2 bytes of SSL3+.
   std::vector<uint8_t> buf(2);
   buf[0] = 0x16;
   buf[1] = 0x03;
   EXPECT_CALL(mockPeekCallback1_, getHelperInternal(_, _, _, _))
     .WillOnce(Return(nullptr));
   EXPECT_CALL(mockPeekCallback2_, getHelperInternal(_, _, _, _))
     .WillOnce(Return(nullptr));
   EXPECT_CALL(callback_, connectionError_(_, _, _));
   helper_->peekSuccess(buf);
 }
TEST_F (PeekingAcceptorHandshakeHelperTest , TestPeek2ndSuccess)
Definition at line 121 of file PeekingAcceptorHandshakeHelperTest.cpp.
References testing::_, callback_, EXPECT_CALL, folly::gen::move, and testing::Return().
{
   helper_->start(std::move(sockPtr_), &callback_);
   // first 2 bytes of SSL3+.
   std::vector<uint8_t> buf(2);
   buf[0] = 0x16;
   buf[1] = 0x03;
   EXPECT_CALL(mockPeekCallback1_, getHelperInternal(_, _, _, _))
     .WillOnce(Return(nullptr));
   EXPECT_CALL(mockPeekCallback2_, getHelperInternal(_, _, _, _))
     .WillOnce(Return(helperPtr_.release()));
   EXPECT_CALL(*innerHelper_, startInternal(_, _));
   helper_->peekSuccess(buf);
 }
TEST_F (PeekingAcceptorHandshakeHelperTest , TestEOFDuringPeek)
Definition at line 136 of file PeekingAcceptorHandshakeHelperTest.cpp.
References testing::_, ASSERT_TRUE, callback_, EXPECT_CALL, folly::gen::move, and folly::AsyncReader::ReadCallback::readEOF().
{
   AsyncTransportWrapper::ReadCallback* rcb;
   EXPECT_CALL(*sslSock_, setReadCB(_))
     .WillOnce(SaveArg<0>(&rcb));
   EXPECT_CALL(*sslSock_, setReadCB(nullptr));
   EXPECT_CALL(callback_, connectionError_(_, _, _));
   helper_->start(std::move(sockPtr_), &callback_);
   ASSERT_TRUE(rcb);
   rcb->readEOF();
 }
TEST_F (PeekingAcceptorHandshakeHelperTest , TestPeekErr)
Definition at line 147 of file PeekingAcceptorHandshakeHelperTest.cpp.
References testing::_, callback_, EXPECT_CALL, and folly::gen::move.
{
   helper_->start(std::move(sockPtr_), &callback_);
   EXPECT_CALL(callback_, connectionError_(_, _, _));
   helper_->peekError(AsyncSocketException(
         AsyncSocketException::AsyncSocketExceptionType::END_OF_FILE,
           "Unit test"));
 }
TEST_F (PeekingAcceptorHandshakeHelperTest , TestDropDuringPeek)
Definition at line 155 of file PeekingAcceptorHandshakeHelperTest.cpp.
References testing::_, testing::AtLeast(), callback_, EXPECT_CALL, testing::Invoke(), folly::gen::move, and cpp.tokenize::UNKNOWN.
{
   helper_->start(std::move(sockPtr_), &callback_);
   EXPECT_CALL(*sslSock_, closeNow()).Times(AtLeast(1)).WillOnce(Invoke([&] {
     helper_->peekError(AsyncSocketException(
         AsyncSocketException::AsyncSocketExceptionType::UNKNOWN, "unit test"));
   }));
   EXPECT_CALL(callback_, connectionError_(_, _, _));
   helper_->dropConnection();
 }
TEST_F (PeekingAcceptorHandshakeHelperTest , TestDropAfterPeek)
Definition at line 166 of file PeekingAcceptorHandshakeHelperTest.cpp.
References testing::_, callback_, EXPECT_CALL, folly::gen::move, and testing::Return().
{
   helper_->start(std::move(sockPtr_), &callback_);
   std::vector<uint8_t> buf(2);
   // first 2 bytes of SSL3+.
   buf[0] = 0x16;
   buf[1] = 0x03;
   EXPECT_CALL(mockPeekCallback1_, getHelperInternal(_, _, _, _))
     .WillOnce(Return(helperPtr_.release()));
   EXPECT_CALL(*innerHelper_, startInternal(_, _));
   helper_->peekSuccess(buf);
   EXPECT_CALL(*innerHelper_, dropConnection(_));
   helper_->dropConnection();
 }