proxygen: proxygen/folly/folly/futures/test/PollTest.cpp File Reference
PollTest.cpp File Reference
#include <folly/futures/Future.h>
#include <folly/portability/GTest.h>
Functions
TEST (Poll, ready)
TEST (Poll, notReady)
TEST (Poll, exception)
Function Documentation
TEST (Poll , ready)
Definition at line 22 of file PollTest.cpp.
References EXPECT_EQ, f, folly::Promise< T >::getFuture(), and folly::Promise< T >::setValue().
                   {
   Promise<int> p;
   auto f = p.getFuture();
   p.setValue(42);
   EXPECT_EQ(42, f.poll().value().value());
 }
TEST (Poll , notReady)
Definition at line 29 of file PollTest.cpp.
References EXPECT_FALSE, f, and folly::Promise< T >::getFuture().
                      {
   Promise<int> p;
   auto f = p.getFuture();
   EXPECT_FALSE(f.poll().hasValue());
 }
TEST (Poll , exception)
Definition at line 35 of file PollTest.cpp.
References EXPECT_TRUE, f, folly::Promise< T >::getFuture(), and folly::Promise< T >::setWith().
                       {
   Promise<Unit> p;
   auto f = p.getFuture();
   p.setWith([] { throw std::runtime_error("Runtime"); });
   EXPECT_TRUE(f.poll().value().hasException());
 }