proxygen: proxygen/folly/folly/test/PolyTest.cpp File Reference
PolyTest.cpp File Reference
#include <folly/Poly.h>
#include <folly/Conv.h>
#include <folly/poly/Nullable.h>
#include <folly/poly/Regular.h>
#include <folly/portability/GTest.h>
#include <array>
Functions
TEST (Poly, SemiRegular)
TEST (Poly, EqualityComparable)
TEST (Poly, StrictlyOrderable)
TEST (Poly, SemiRegularReference)
TEST (Poly, Conversions)
TEST (Poly, EqualityComparableReference)
TEST (Poly, Singular)
TEST (Poly, SingleInheritance)
TEST (Poly, MultipleInheritance)
TEST (Poly, OverloadedMembers)
TEST (Poly, NullablePointer)
TEST (Poly, Move)
TEST (Poly, RValueRef)
TEST (Poly, Function)
TEST (Poly, DiamondInheritance)
TEST (Poly, Sig)
TEST (Poly, Addable)
TEST (Poly, PolyRefAsArg)
Function Documentation
TEST (Poly , SemiRegular)
Definition at line 73 of file PolyTest.cpp.
References EXPECT_EQ, EXPECT_THROW, folly::poly_type(), folly::f14::swap(), folly::swap(), and folly::value().
{
   {
     // A small object, storable in-situ:
     Poly<ISemiRegular> p = 42;
     EXPECT_EQ(typeid(int), poly_type(p));
     EXPECT_EQ(42, poly_cast<int>(p));
     EXPECT_THROW(poly_cast<short>(p), BadPolyCast);
     Poly<ISemiRegular> p2 = p;
     EXPECT_EQ(typeid(int), poly_type(p2));
     EXPECT_EQ(42, poly_cast<int>(p2));
     EXPECT_THROW(poly_cast<short>(p2), BadPolyCast);
   }
   EXPECT_EQ(0, Big::s_count);
   {
     // A big object, stored on the heap:
     Poly<ISemiRegular> p = Big(42);
     EXPECT_EQ(1, Big::s_count);
     EXPECT_EQ(typeid(Big), poly_type(p));
     EXPECT_EQ(42, poly_cast<Big>(p).value());
     EXPECT_THROW(poly_cast<short>(p), BadPolyCast);
     Poly<ISemiRegular> p2 = p;
     EXPECT_EQ(2, Big::s_count);
     EXPECT_EQ(typeid(Big), poly_type(p2));
     EXPECT_EQ(42, poly_cast<Big>(p2).value());
     EXPECT_THROW(poly_cast<short>(p2), BadPolyCast);
   }
   EXPECT_EQ(0, Big::s_count);
   // four swap cases
   //
   {
     // A small object, storable in-situ:
     Poly<ISemiRegular> p = 42;
     EXPECT_EQ(typeid(int), poly_type(p));
     EXPECT_EQ(42, poly_cast<int>(p));
     EXPECT_THROW(poly_cast<short>(p), BadPolyCast);
     // A small object, storable in-situ:
     Poly<ISemiRegular> p2 = 4.2;
     EXPECT_EQ(typeid(double), poly_type(p2));
     EXPECT_EQ(4.2, poly_cast<double>(p2));
     EXPECT_THROW(poly_cast<short>(p2), BadPolyCast);
     std::swap(p, p2);
     EXPECT_EQ(typeid(double), poly_type(p));
     EXPECT_EQ(4.2, poly_cast<double>(p));
     EXPECT_THROW(poly_cast<short>(p), BadPolyCast);
     EXPECT_EQ(typeid(int), poly_type(p2));
     EXPECT_EQ(42, poly_cast<int>(p2));
     EXPECT_THROW(poly_cast<short>(p2), BadPolyCast);
     using std::swap;
     swap(p, p2);
     EXPECT_EQ(typeid(int), poly_type(p));
     EXPECT_EQ(42, poly_cast<int>(p));
     EXPECT_THROW(poly_cast<short>(p), BadPolyCast);
     EXPECT_EQ(typeid(double), poly_type(p2));
     EXPECT_EQ(4.2, poly_cast<double>(p2));
     EXPECT_THROW(poly_cast<short>(p2), BadPolyCast);
   }
   EXPECT_EQ(0, Big::s_count);
   EXPECT_EQ(0, BigDouble::s_count);
   {
     // A big object, stored on the heap:
     Poly<ISemiRegular> p = Big(42);
     EXPECT_EQ(1, Big::s_count);
     EXPECT_EQ(typeid(Big), poly_type(p));
     EXPECT_EQ(42, poly_cast<Big>(p).value());
     EXPECT_THROW(poly_cast<short>(p), BadPolyCast);
     // A big object, stored on the heap:
     Poly<ISemiRegular> p2 = BigDouble(4.2);
     EXPECT_EQ(1, BigDouble::s_count);
     EXPECT_EQ(typeid(BigDouble), poly_type(p2));
     EXPECT_EQ(4.2, poly_cast<BigDouble>(p2).value());
     EXPECT_THROW(poly_cast<short>(p2), BadPolyCast);
     std::swap(p, p2);
     EXPECT_EQ(1, Big::s_count);
     EXPECT_EQ(1, BigDouble::s_count);
     EXPECT_EQ(typeid(BigDouble), poly_type(p));
     EXPECT_EQ(4.2, poly_cast<BigDouble>(p).value());
     EXPECT_THROW(poly_cast<short>(p), BadPolyCast);
     EXPECT_EQ(typeid(Big), poly_type(p2));
     EXPECT_EQ(42, poly_cast<Big>(p2).value());
     EXPECT_THROW(poly_cast<short>(p2), BadPolyCast);
     using std::swap;
     swap(p, p2);
     EXPECT_EQ(1, Big::s_count);
     EXPECT_EQ(1, BigDouble::s_count);
     EXPECT_EQ(typeid(Big), poly_type(p));
     EXPECT_EQ(42, poly_cast<Big>(p).value());
     EXPECT_THROW(poly_cast<short>(p), BadPolyCast);
     EXPECT_EQ(typeid(BigDouble), poly_type(p2));
     EXPECT_EQ(4.2, poly_cast<BigDouble>(p2).value());
     EXPECT_THROW(poly_cast<short>(p2), BadPolyCast);
   }
   EXPECT_EQ(0, BigDouble::s_count);
   EXPECT_EQ(0, Big::s_count);
   EXPECT_EQ(0, Big::s_count);
   {
     // A big object, stored on the heap:
     Poly<ISemiRegular> p = Big(42);
     EXPECT_EQ(1, Big::s_count);
     EXPECT_EQ(typeid(Big), poly_type(p));
     EXPECT_EQ(42, poly_cast<Big>(p).value());
     EXPECT_THROW(poly_cast<short>(p), BadPolyCast);
     // A small object, storable in-situ:
     Poly<ISemiRegular> p2 = 4.2;
     EXPECT_EQ(typeid(double), poly_type(p2));
     EXPECT_EQ(4.2, poly_cast<double>(p2));
     EXPECT_THROW(poly_cast<short>(p2), BadPolyCast);
     std::swap(p, p2);
     EXPECT_EQ(1, Big::s_count);
     EXPECT_EQ(typeid(double), poly_type(p));
     EXPECT_EQ(4.2, poly_cast<double>(p));
     EXPECT_THROW(poly_cast<short>(p), BadPolyCast);
     EXPECT_EQ(typeid(Big), poly_type(p2));
     EXPECT_EQ(42, poly_cast<Big>(p2).value());
     EXPECT_THROW(poly_cast<short>(p2), BadPolyCast);
     using std::swap;
     swap(p, p2);
     EXPECT_EQ(1, Big::s_count);
     EXPECT_EQ(typeid(Big), poly_type(p));
     EXPECT_EQ(42, poly_cast<Big>(p).value());
     EXPECT_THROW(poly_cast<short>(p), BadPolyCast);
     EXPECT_EQ(typeid(double), poly_type(p2));
     EXPECT_EQ(4.2, poly_cast<double>(p2));
     EXPECT_THROW(poly_cast<short>(p2), BadPolyCast);
   }
   EXPECT_EQ(0, Big::s_count);
   EXPECT_EQ(0, BigDouble::s_count);
   {
     // A small object, storable in-situ:
     Poly<ISemiRegular> p = 42;
     EXPECT_EQ(typeid(int), poly_type(p));
     EXPECT_EQ(42, poly_cast<int>(p));
     EXPECT_THROW(poly_cast<short>(p), BadPolyCast);
     // A big object, stored on the heap:
     Poly<ISemiRegular> p2 = BigDouble(4.2);
     EXPECT_EQ(1, BigDouble::s_count);
     EXPECT_EQ(typeid(BigDouble), poly_type(p2));
     EXPECT_EQ(4.2, poly_cast<BigDouble>(p2).value());
     EXPECT_THROW(poly_cast<short>(p2), BadPolyCast);
     std::swap(p, p2);
     EXPECT_EQ(1, BigDouble::s_count);
     EXPECT_EQ(typeid(BigDouble), poly_type(p));
     EXPECT_EQ(4.2, poly_cast<BigDouble>(p).value());
     EXPECT_THROW(poly_cast<short>(p), BadPolyCast);
     EXPECT_EQ(typeid(int), poly_type(p2));
     EXPECT_EQ(42, poly_cast<int>(p2));
     EXPECT_THROW(poly_cast<short>(p2), BadPolyCast);
     using std::swap;
     swap(p, p2);
     EXPECT_EQ(1, BigDouble::s_count);
     EXPECT_EQ(typeid(int), poly_type(p));
     EXPECT_EQ(42, poly_cast<int>(p));
     EXPECT_THROW(poly_cast<short>(p), BadPolyCast);
     EXPECT_EQ(typeid(BigDouble), poly_type(p2));
     EXPECT_EQ(4.2, poly_cast<BigDouble>(p2).value());
     EXPECT_THROW(poly_cast<short>(p2), BadPolyCast);
   }
   EXPECT_EQ(0, BigDouble::s_count);
 }
TEST (Poly , EqualityComparable)
Definition at line 238 of file PolyTest.cpp.
References EXPECT_FALSE, EXPECT_THROW, and EXPECT_TRUE.
{
   {
     Poly<IEqualityComparable> p = 42;
     Poly<IEqualityComparable> q = 42;
     EXPECT_TRUE(p == q);
     EXPECT_TRUE(q == p);
     EXPECT_FALSE(p != q);
     EXPECT_FALSE(q != p);
     p = 43;
     EXPECT_FALSE(p == q);
     EXPECT_FALSE(q == p);
     EXPECT_TRUE(p != q);
     EXPECT_TRUE(q != p);
   }
   {
     // empty not equal
     Poly<IEqualityComparable> p;
     Poly<IEqualityComparable> q = 42;
     EXPECT_FALSE(p == q);
     EXPECT_FALSE(q == p);
   }
   {
     // empty equal
     Poly<IEqualityComparable> p;
     Poly<IEqualityComparable> q;
     EXPECT_TRUE(p == q);
     EXPECT_TRUE(q == p);
   }
   {
     // mismatched types throws
     Poly<IEqualityComparable> p = 4.2;
     Poly<IEqualityComparable> q = 42;
     EXPECT_THROW((void)(q == p), BadPolyCast);
   }
 }
TEST (Poly , StrictlyOrderable)
Definition at line 274 of file PolyTest.cpp.
References EXPECT_FALSE, EXPECT_THROW, and EXPECT_TRUE.
{
   {
     // A small object, storable in-situ:
     Poly<IStrictlyOrderable> p = 42;
     Poly<IStrictlyOrderable> q = 43;
     EXPECT_TRUE(p < q);
     EXPECT_TRUE(p <= q);
     EXPECT_FALSE(p > q);
     EXPECT_FALSE(p >= q);
     EXPECT_TRUE(q > p);
     EXPECT_TRUE(q >= p);
     EXPECT_FALSE(q < p);
     EXPECT_FALSE(q <= p);
   }
   {
     // A big object, stored on the heap:
     Poly<IStrictlyOrderable> p = Big(42);
     Poly<IStrictlyOrderable> q = Big(43);
     EXPECT_TRUE(p < q);
   }
   {
     // if equal, no one is bigger
     Poly<IStrictlyOrderable> p = 42;
     Poly<IStrictlyOrderable> q = 42;
     EXPECT_FALSE(p < q);
     EXPECT_TRUE(p <= q);
     EXPECT_FALSE(p > q);
     EXPECT_TRUE(p >= q);
     EXPECT_FALSE(q < p);
     EXPECT_TRUE(q <= p);
     EXPECT_FALSE(q > p);
     EXPECT_TRUE(q >= p);
   }
   {
     // empty is always smaller
     Poly<IStrictlyOrderable> p;
     Poly<IStrictlyOrderable> q = 42;
     EXPECT_TRUE(p < q);
     EXPECT_FALSE(q < p);
   }
   {
     // mismatched types throws
     Poly<IStrictlyOrderable> p = 4.2;
     Poly<IStrictlyOrderable> q = 42;
     EXPECT_THROW((void)(p < q), BadPolyCast);
     EXPECT_THROW((void)(q < p), BadPolyCast);
   }
 }
TEST (Poly , SemiRegularReference)
Definition at line 323 of file PolyTest.cpp.
References EXPECT_EQ, EXPECT_THROW, i, folly::poly_type(), folly::f14::swap(), folly::swap(), and folly::value().
{
   int i = 42;
   Poly<ISemiRegular&> p = i;
   EXPECT_EQ(42, i);
   EXPECT_EQ(typeid(int), poly_type(p));
   EXPECT_EQ(42, poly_cast<int>(p));
   EXPECT_EQ(&i, &poly_cast<int>(p));
   EXPECT_THROW(poly_cast<short>(p), BadPolyCast);
   Poly<ISemiRegular&> p2 = p;
   EXPECT_EQ(typeid(int), poly_type(p2));
   EXPECT_EQ(42, poly_cast<int>(p2));
   EXPECT_EQ(&i, &poly_cast<int>(p2));
   EXPECT_THROW(poly_cast<short>(p2), BadPolyCast);
   std::swap(p, p2);
   EXPECT_EQ(typeid(int), poly_type(p2));
   EXPECT_EQ(42, poly_cast<int>(p2));
   EXPECT_EQ(&i, &poly_cast<int>(p2));
   EXPECT_THROW(poly_cast<short>(p2), BadPolyCast);
   using std::swap;
   swap(p, p2);
   EXPECT_EQ(typeid(int), poly_type(p2));
   EXPECT_EQ(42, poly_cast<int>(p2));
   EXPECT_EQ(&i, &poly_cast<int>(p2));
   EXPECT_THROW(poly_cast<short>(p2), BadPolyCast);
   // Can't default-initialize reference-like Poly's:
   static_assert(!std::is_default_constructible<Poly<ISemiRegular&>>::value, "");
 }
TEST (Poly , Conversions)
Definition at line 351 of file PolyTest.cpp.
References EXPECT_EQ, i, and folly::value().
{
   int i = 42;
   Poly<ISemiRegular> p1 = i;
   Poly<ISemiRegular&> p2 = p1;
   EXPECT_EQ(&poly_cast<int>(p1), &poly_cast<int>(p2));
   Poly<ISemiRegular const&> p3 = p1;
   Poly<ISemiRegular const&> p4 = p2;
   EXPECT_EQ(&poly_cast<int>(p3), &poly_cast<int>(p1));
   EXPECT_EQ(&poly_cast<int>(p4), &poly_cast<int>(p1));
   static_assert(
       !std::is_constructible<Poly<ISemiRegular&>, Poly<ISemiRegular const&>&>::
           value,
       "");
   static_assert(
       !std::is_constructible<Poly<ISemiRegular>, Poly<ISemiRegular const&>&>::
           value,
       "");
 }
TEST (Poly , EqualityComparableReference)
Definition at line 370 of file PolyTest.cpp.
References EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, FOLLY_POLY_MEMBERS, folly::foo, testing::gmock_matchers_test::foo, and i.
{
   int i = 42;
   int j = 42;
   Poly<IEqualityComparable&> p1 = i;
   Poly<IEqualityComparable&> p2 = j;
   EXPECT_EQ(&i, &poly_cast<int>(p1));
   EXPECT_EQ(&j, &poly_cast<int>(p2));
   EXPECT_TRUE(p1 == p2);
   EXPECT_FALSE(p1 != p2);
   j = 43;
   EXPECT_FALSE(p1 == p2);
   EXPECT_TRUE(p1 != p2);
   EXPECT_EQ(42, poly_cast<int>(p1));
   EXPECT_EQ(43, poly_cast<int>(p2));
 }
TEST (Poly , Singular)
Definition at line 411 of file PolyTest.cpp.
References bar, EXPECT_EQ, FOLLY_POLY_MEMBERS, folly::foo, i, folly::poly_type(), and string.
                      {
   Poly<Foo> p = foo_{42};
   int i = 1;
   p.foo(i);
   EXPECT_EQ(43, i);
   EXPECT_EQ(typeid(foo_), poly_type(p));
 }
TEST (Poly , SingleInheritance)
Definition at line 448 of file PolyTest.cpp.
References bar, baz(), upload::const, EXPECT_EQ, fizz, FOLLY_POLY_MEMBERS, folly::foo, i, folly::poly_type(), and string.
{
   Poly<FooBar> p = foo_bar{42};
   int i = 1;
   p.foo(i);
   EXPECT_EQ(43, i);
   EXPECT_EQ("43", p.bar(1));
   EXPECT_EQ(typeid(foo_bar), poly_type(p));
   Poly<Foo> q = p; // OK, conversion works.
   q.foo(i);
   EXPECT_EQ(85, i);
   Poly<Foo&> r = p;
   r->foo(i);
   EXPECT_EQ(127, i);
   const_cast<Poly<Foo&> const&>(r)->foo(i);
   EXPECT_EQ(169, i);
   Poly<FooBar const&> cr = p;
   // cr->foo(i); // ERROR: calls a non-const member through a const reference
   cr->bar(i); // OK
 }
TEST (Poly , MultipleInheritance)
Definition at line 517 of file PolyTest.cpp.
References EXPECT_EQ, FOLLY_POLY_MEMBER, FOLLY_POLY_MEMBERS, i, folly::poly_type(), and testing::Property().
{
   Poly<FooBarBazFizz> p = foo_bar_baz_fizz{42};
   int i = 1;
   p.foo(i);
   EXPECT_EQ(43, i);
   EXPECT_EQ("43", p.bar(1));
   EXPECT_EQ("3", p.baz(1, 2));
   EXPECT_EQ("fizz", p.fizz());
   EXPECT_EQ(typeid(foo_bar_baz_fizz), poly_type(p));
 }
TEST (Poly , OverloadedMembers)
Definition at line 561 of file PolyTest.cpp.
References EXPECT_EQ, and folly::poly_type().
{
   Poly<Property> p = has_property{42};
   EXPECT_EQ(typeid(has_property), poly_type(p));
   EXPECT_EQ(42, p.prop());
   p.prop(68);
   EXPECT_EQ(68, p.prop());
 }
TEST (Poly , NullablePointer)
Definition at line 569 of file PolyTest.cpp.
References EXPECT_EQ, EXPECT_FALSE, EXPECT_THROW, EXPECT_TRUE, folly::poly_empty(), folly::poly_type(), and s.
{
   Poly<INullablePointer> p = nullptr;
   Poly<INullablePointer> q{};
   EXPECT_EQ(typeid(void), poly_type(p));
   EXPECT_TRUE(poly_empty(p));
   EXPECT_TRUE(p == q);
   EXPECT_FALSE(p != q);
   EXPECT_TRUE(p == nullptr);
   EXPECT_TRUE(nullptr == p);
   EXPECT_FALSE(p != nullptr);
   EXPECT_FALSE(nullptr != p);
   // No null references ever.
   Poly<INullablePointer> r = 42;
   Poly<INullablePointer&> s = r;
   static_assert(!poly_empty(s), "");
   EXPECT_THROW(Poly<INullablePointer&> r_(q), BadPolyAccess);
 }
TEST (Poly , Move)
Definition at line 598 of file PolyTest.cpp.
References EXPECT_EQ, i, folly::poly_move(), and folly::value().
                  {
   {
     int i = 42;
     Poly<IMoveOnly&> p = i;
     static_assert(
         !std::is_convertible<Poly<IMoveOnly&>, Poly<IMoveOnly&&>>::value, "");
     auto q = poly_move(p);
     static_assert(std::is_same<decltype(q), Poly<IMoveOnly&&>>::value, "");
     EXPECT_EQ(&poly_cast<int>(p), &poly_cast<int>(q));
   }
   {
     int i = 42;
     Poly<ISemiRegular const&> p = i;
     auto q = poly_move(p);
     static_assert(
         std::is_same<decltype(q), Poly<ISemiRegular const&>>::value, "");
     EXPECT_EQ(&poly_cast<int>(p), &poly_cast<int>(q));
   }
   {
     Poly<IMoveOnly> p = MoveOnly_{};
     static_assert(!std::is_copy_constructible<Poly<IMoveOnly>>::value, "");
     auto q = poly_move(p);
     static_assert(std::is_same<decltype(q), Poly<IMoveOnly>>::value, "");
   }
 }
TEST (Poly , RValueRef)
Definition at line 624 of file PolyTest.cpp.
References folly::gen::as(), EXPECT_EQ, FOLLY_POLY_MEMBER, FOLLY_POLY_MEMBERS, i, folly::gen::move, and folly::value().
                       {
   int i = 42;
   Poly<ISemiRegular&&> p = std::move(i);
   static_assert(std::is_same<decltype(poly_cast<int>(p)), int&>::value, "");
   EXPECT_EQ(&i, &poly_cast<int>(p));
 }
TEST (Poly , Function)
Definition at line 654 of file PolyTest.cpp.
References EXPECT_EQ, and fun().
                      {
   Function<int(int, int)> fun = std::plus<int>{};
   EXPECT_EQ(42, fun(22, 20));
   fun = std::multiplies<int>{};
   EXPECT_EQ(22 * 20, fun(22, 20));
 }
TEST (Poly , DiamondInheritance)
Definition at line 666 of file PolyTest.cpp.
References folly::eq, EXPECT_EQ, EXPECT_THROW, folly::poly_type(), and folly::value().
{
   {
     // A small object, storable in-situ:
     Poly<IDiamond> p = 42;
     EXPECT_EQ(typeid(int), poly_type(p));
     EXPECT_EQ(42, poly_cast<int>(p));
     EXPECT_THROW(poly_cast<short>(p), BadPolyCast);
     Poly<IDiamond> p2 = p;
     EXPECT_EQ(typeid(int), poly_type(p2));
     EXPECT_EQ(42, poly_cast<int>(p2));
     EXPECT_THROW(poly_cast<short>(p2), BadPolyCast);
     Poly<IEqualityComparable&> eq = p;
     EXPECT_EQ(&poly_cast<int>(p), &poly_cast<int>(eq));
   }
   EXPECT_EQ(0, Big::s_count);
   {
     // A big object, stored on the heap:
     Poly<IDiamond> p = Big(42);
     EXPECT_EQ(1, Big::s_count);
     EXPECT_EQ(typeid(Big), poly_type(p));
     EXPECT_EQ(42, poly_cast<Big>(p).value());
     EXPECT_THROW(poly_cast<short>(p), BadPolyCast);
     Poly<IDiamond> p2 = p;
     EXPECT_EQ(2, Big::s_count);
     EXPECT_EQ(typeid(Big), poly_type(p2));
     EXPECT_EQ(42, poly_cast<Big>(p2).value());
     EXPECT_THROW(poly_cast<short>(p2), BadPolyCast);
     Poly<IEqualityComparable&> eq = p;
     EXPECT_EQ(&poly_cast<Big>(p), &poly_cast<Big>(eq));
   }
   EXPECT_EQ(0, Big::s_count);
 }
TEST (Poly , Sig)
Definition at line 737 of file PolyTest.cpp.
References a, b, upload::const, EXPECT_EQ, FOLLY_POLY_MEMBERS, folly::operator+(), and folly::T.
                 {
   {
     auto m0 = folly::sig<int() const>(&Struct::property);
     EXPECT_EQ(static_cast<int (Struct::*)() const>(&Struct::property), m0);
     auto m1 = folly::sig<int()>(&Struct::property);
     EXPECT_EQ(static_cast<int (Struct::*)() const>(&Struct::property), m1);
     auto m2 = folly::sig<int() const>(&Struct2::property);
     EXPECT_EQ(static_cast<int (Struct2::*)() const>(&Struct2::property), m2);
     auto m3 = folly::sig<int()>(&Struct2::property);
     EXPECT_EQ(static_cast<int (Struct2::*)() const>(&Struct2::property), m3);
     auto m4 = folly::sig<long()>(&Struct2::meow);
     EXPECT_EQ(&Struct2::meow, m4);
     auto m5 = folly::sig<int()>(&Struct2::purr);
     EXPECT_EQ(static_cast<int (Struct2::*)()>(&Struct2::purr), m5);
     auto m6 = folly::sig<int() const>(&Struct2::purr);
     EXPECT_EQ(static_cast<int (Struct2::*)() const>(&Struct2::purr), m6);
   }
   {
     auto m0 = folly::sig<int(Struct const&)>(&::property);
     EXPECT_EQ(static_cast<int (*)(Struct const&)>(&::property), m0);
     auto m1 = folly::sig<int(Struct&)>(&::property);
     EXPECT_EQ(static_cast<int (*)(Struct const&)>(&::property), m1);
     auto m2 = folly::sig<long(Struct2&)>(&::meow);
     EXPECT_EQ(&::meow, m2);
     auto m3 = folly::sig<int(Struct2&)>(&::purr);
     EXPECT_EQ(static_cast<int (*)(Struct2&)>(&::purr), m3);
     auto m4 = folly::sig<int(Struct2 const&)>(&::purr);
     EXPECT_EQ(static_cast<int (*)(Struct2 const&)>(&::purr), m4);
   }
 }
TEST (Poly , Addable)
Definition at line 793 of file PolyTest.cpp.
References a, b, c, cc, EXPECT_EQ, FOLLY_POLY_MEMBERS, folly::poly_type(), folly::value(), and x.
                     {
   Poly<IAddable> a = 2, b = 3;
   Poly<IAddable> c = a + b;
   EXPECT_EQ(typeid(int), poly_type(c));
   EXPECT_EQ(5, poly_cast<int>(c));
   Poly<IAddable const&> aref = a, bref = b;
   auto cc = aref + bref;
   static_assert(std::is_same<decltype(cc), Poly<IAddable>>::value, "");
   EXPECT_EQ(typeid(int), poly_type(cc));
   EXPECT_EQ(5, poly_cast<int>(cc));
   b = 4;
   EXPECT_EQ(5, poly_cast<int>(cc));
   cc = aref + bref;
   EXPECT_EQ(6, poly_cast<int>(cc));
 }
TEST (Poly , PolyRefAsArg)
Definition at line 830 of file PolyTest.cpp.
{
   folly::Poly<folly::poly::IRegular> x = 42;
   Frobnicator frob = my_frobnicator{};
   // should not throw:
   frob.frobnicate(x);
   // should not throw:
   frob.frobnicate(folly::Poly<folly::poly::IRegular&>(x));
 }