proxygen: proxygen/folly/folly/test/PortabilityTest.cpp File Reference
PortabilityTest.cpp File Reference
#include <folly/Portability.h>
#include <memory>
#include <folly/portability/GTest.h>
Classes
class Base
class Derived
Functions
int fooBase (const Base *p)
int fooDerived (const Derived *p)
TEST (Portability, Final)
Function Documentation
int fooBase (const Base * p)
Definition at line 45 of file PortabilityTest.cpp.
Referenced by TEST().
{
   return p->foo() + 1;
 }
int fooDerived (const Derived * p)
Definition at line 48 of file PortabilityTest.cpp.
Referenced by TEST().
{
   return p->foo() + 1;
 }
TEST (Portability , Final)
Definition at line 52 of file PortabilityTest.cpp.
References EXPECT_EQ, fooBase(), and fooDerived().
{
   std::unique_ptr<Derived> p(new Derived);
   EXPECT_EQ(3, fooBase(p.get()));
   EXPECT_EQ(3, fooDerived(p.get()));
 }