proxygen: proxygen/folly/folly/test/PriorityMPMCQueueTest.cpp File Reference
PriorityMPMCQueueTest.cpp File Reference
#include <folly/PriorityMPMCQueue.h>
#include <folly/portability/GTest.h>
Functions
TEST (PriorityMPMCQueue, BasicOps)
TEST (PriorityMPMCQueue, TestPriorities)
TEST (PriorityMPMCQueue, TestReadWithPriority)
TEST (PriorityMPMCQueue, TestWriteWithPriorityAndTimeout)
Function Documentation
TEST (PriorityMPMCQueue , BasicOps)
Definition at line 22 of file PriorityMPMCQueueTest.cpp.
References EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, folly::PriorityMPMCQueue< T, Atom, Dynamic >::getNumPriorities(), folly::PriorityMPMCQueue< T, Atom, Dynamic >::isEmpty(), folly::PriorityMPMCQueue< T, Atom, Dynamic >::read(), folly::PriorityMPMCQueue< T, Atom, Dynamic >::size(), folly::PriorityMPMCQueue< T, Atom, Dynamic >::sizeGuess(), and folly::PriorityMPMCQueue< T, Atom, Dynamic >::write().
{
   // With just one priority, this should behave like a normal MPMCQueue
   PriorityMPMCQueue<size_t> queue(1, 10);
   EXPECT_TRUE(queue.isEmpty());
   EXPECT_EQ(1, queue.getNumPriorities());
   queue.write(9);
   queue.write(8);
   EXPECT_FALSE(queue.isEmpty());
   EXPECT_EQ(2, queue.size());
   EXPECT_EQ(2, queue.sizeGuess());
   size_t item;
   queue.read(item);
   EXPECT_EQ(9, item);
   EXPECT_FALSE(queue.isEmpty());
   EXPECT_EQ(1, queue.size());
   EXPECT_EQ(1, queue.sizeGuess());
   queue.read(item);
   EXPECT_EQ(8, item);
   EXPECT_TRUE(queue.isEmpty());
   EXPECT_EQ(0, queue.size());
   EXPECT_EQ(0, queue.sizeGuess());
 }
TEST (PriorityMPMCQueue , TestPriorities)
Definition at line 49 of file PriorityMPMCQueueTest.cpp.
References EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, folly::PriorityMPMCQueue< T, Atom, Dynamic >::getNumPriorities(), i, folly::PriorityMPMCQueue< T, Atom, Dynamic >::isEmpty(), folly::PriorityMPMCQueue< T, Atom, Dynamic >::read(), folly::PriorityMPMCQueue< T, Atom, Dynamic >::size(), folly::PriorityMPMCQueue< T, Atom, Dynamic >::sizeGuess(), folly::PriorityMPMCQueue< T, Atom, Dynamic >::write(), and folly::PriorityMPMCQueue< T, Atom, Dynamic >::writeWithPriority().
{
   PriorityMPMCQueue<size_t> queue(3, 10);
   EXPECT_TRUE(queue.isEmpty());
   EXPECT_EQ(3, queue.getNumPriorities());
   // This should go to the lowpri queue, as we only
   // have 3 priorities
   queue.writeWithPriority(5, 50);
   // unqualified writes should be mid-pri
   queue.write(3);
   queue.writeWithPriority(6, 2);
   queue.writeWithPriority(1, 0);
   queue.write(4);
   queue.writeWithPriority(2, 0);
   EXPECT_FALSE(queue.isEmpty());
   EXPECT_EQ(6, queue.size());
   EXPECT_EQ(6, queue.sizeGuess());
   size_t item;
   for (int i = 1; i <= 6; i++) {
     queue.read(item);
     EXPECT_EQ(i, item);
     EXPECT_EQ(6 - i, queue.size());
     EXPECT_EQ(6 - i, queue.sizeGuess());
   }
 }
TEST (PriorityMPMCQueue , TestReadWithPriority)
Definition at line 77 of file PriorityMPMCQueueTest.cpp.
References EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, folly::PriorityMPMCQueue< T, Atom, Dynamic >::getNumPriorities(), i, folly::PriorityMPMCQueue< T, Atom, Dynamic >::isEmpty(), folly::PriorityMPMCQueue< T, Atom, Dynamic >::readWithPriority(), folly::PriorityMPMCQueue< T, Atom, Dynamic >::size(), folly::PriorityMPMCQueue< T, Atom, Dynamic >::sizeGuess(), and folly::PriorityMPMCQueue< T, Atom, Dynamic >::writeWithPriority().
{
   PriorityMPMCQueue<size_t> queue(3, 10);
   EXPECT_TRUE(queue.isEmpty());
   EXPECT_EQ(3, queue.getNumPriorities());
   queue.writeWithPriority(2, 2);
   queue.writeWithPriority(1, 1);
   queue.writeWithPriority(0, 0);
   EXPECT_FALSE(queue.isEmpty());
   EXPECT_EQ(3, queue.size());
   EXPECT_EQ(3, queue.sizeGuess());
   size_t item;
   for (int i = 0; i < 3; i++) {
     EXPECT_TRUE(queue.readWithPriority(item, i));
     EXPECT_EQ(i, item);
     EXPECT_FALSE(queue.readWithPriority(item, i));
   }
 }
TEST (PriorityMPMCQueue , TestWriteWithPriorityAndTimeout)
Definition at line 98 of file PriorityMPMCQueueTest.cpp.
References EXPECT_EQ, EXPECT_FALSE, EXPECT_GE, EXPECT_LE, EXPECT_TRUE, folly::PriorityMPMCQueue< T, Atom, Dynamic >::getNumPriorities(), i, folly::PriorityMPMCQueue< T, Atom, Dynamic >::isEmpty(), now(), folly::PriorityMPMCQueue< T, Atom, Dynamic >::read(), folly::PriorityMPMCQueue< T, Atom, Dynamic >::size(), folly::PriorityMPMCQueue< T, Atom, Dynamic >::sizeGuess(), folly::detail::timeout, and folly::PriorityMPMCQueue< T, Atom, Dynamic >::writeWithPriority().
{
   PriorityMPMCQueue<size_t> queue(5, 1);
   EXPECT_TRUE(queue.isEmpty());
   EXPECT_EQ(5, queue.getNumPriorities());
   const auto timeout = std::chrono::milliseconds{30};
   for (int i = 0; i < 5; i++) {
     auto time_before = std::chrono::steady_clock::now();
     EXPECT_TRUE(queue.writeWithPriority(i, i, timeout));
     auto time_after = std::chrono::steady_clock::now();
     EXPECT_LE(time_after - time_before, timeout);
   }
   // check writeWithPriority will wait for at least timeout if the queue is
   // full.
   auto time_before = std::chrono::steady_clock::now();
   EXPECT_FALSE(queue.writeWithPriority(5, 0, timeout));
   auto time_after = std::chrono::steady_clock::now();
   EXPECT_GE(time_after - time_before, timeout);
   EXPECT_FALSE(queue.isEmpty());
   EXPECT_EQ(5, queue.size());
   EXPECT_EQ(5, queue.sizeGuess());
   size_t item;
   for (int i = 0; i < 5; i++) {
     queue.read(item);
     EXPECT_EQ(i, item);
     EXPECT_EQ(4 - i, queue.size());
     EXPECT_EQ(4 - i, queue.sizeGuess());
   }
 }