proxygen: proxygen/wangle/wangle/example/proxy/Proxy.cpp File Reference
Proxy.cpp File Reference
#include <gflags/gflags.h>
#include <folly/init/Init.h>
#include <wangle/bootstrap/ClientBootstrap.h>
#include <wangle/bootstrap/ServerBootstrap.h>
#include <wangle/channel/AsyncSocketHandler.h>
Classes
class ProxyBackendHandler
class ProxyBackendPipelineFactory
class ProxyFrontendHandler
class ProxyFrontendPipelineFactory
Functions
DEFINE_int32 (port, 1080,"proxy server port")
DEFINE_string (remote_host,"127.0.0.1","remote host")
DEFINE_int32 (remote_port, 23,"remote port")
int main (int argc, char **argv)
Function Documentation
DEFINE_int32 (port , 1080 , "proxy server port")
DEFINE_int32 (remote_port , 23 , "remote port")
DEFINE_string (remote_host , "127.0.0.1" , "remote host")
int main (int argc, char ** argv)
Definition at line 155 of file Proxy.cpp.
References wangle::ServerBootstrap< Pipeline >::bind(), wangle::ServerBootstrap< Pipeline >::childPipeline(), folly::init(), and wangle::ServerBootstrap< Pipeline >::waitForStop().
{
   folly::Init init(&argc, &argv);
   ServerBootstrap<DefaultPipeline> server;
   server.childPipeline(std::make_shared<ProxyFrontendPipelineFactory>(
       SocketAddress(FLAGS_remote_host, FLAGS_remote_port)));
   server.bind(FLAGS_port);
   server.waitForStop();
   return 0;
 }