proxygen: proxygen/folly/folly/stats/test/QuantileEstimatorTest.cpp File Reference
QuantileEstimatorTest.cpp File Reference
#include <folly/stats/QuantileEstimator-defs.h>
#include <folly/portability/GTest.h>
Classes
struct MockClock
Functions
TEST (SimpleQuantileEstimatorTest, EstimateQuantiles)
TEST (SlidingWindowQuantileEstimatorTest, EstimateQuantiles)
Function Documentation
TEST (SimpleQuantileEstimatorTest , EstimateQuantiles)
Definition at line 38 of file QuantileEstimatorTest.cpp.
References folly::SimpleQuantileEstimator< ClockT >::addValue(), folly::SimpleQuantileEstimator< ClockT >::estimateQuantiles(), EXPECT_EQ, i, and MockClock::Now.
{
   SimpleQuantileEstimator<MockClock> estimator;
   for (size_t i = 1; i <= 100; ++i) {
     estimator.addValue(i);
   }
   MockClock::Now += std::chrono::seconds{1};
   auto estimates = estimator.estimateQuantiles(
       std::array<double, 5>{{.001, .01, .5, .99, .999}});
   EXPECT_EQ(5050, estimates.sum);
   EXPECT_EQ(100, estimates.count);
   EXPECT_EQ(0.001, estimates.quantiles[0].first);
   EXPECT_EQ(0.01, estimates.quantiles[1].first);
   EXPECT_EQ(0.5, estimates.quantiles[2].first);
   EXPECT_EQ(0.99, estimates.quantiles[3].first);
   EXPECT_EQ(0.999, estimates.quantiles[4].first);
   EXPECT_EQ(1, estimates.quantiles[0].second);
   EXPECT_EQ(2.0 - 0.5, estimates.quantiles[1].second);
   EXPECT_EQ(50.375, estimates.quantiles[2].second);
   EXPECT_EQ(100.0 - 0.5, estimates.quantiles[3].second);
   EXPECT_EQ(100, estimates.quantiles[4].second);
 }
TEST (SlidingWindowQuantileEstimatorTest , EstimateQuantiles)
Definition at line 65 of file QuantileEstimatorTest.cpp.
References folly::SlidingWindowQuantileEstimator< ClockT >::addValue(), EXPECT_EQ, i, and MockClock::Now.
{
   SlidingWindowQuantileEstimator<MockClock> estimator(std::chrono::seconds{1});
   for (size_t i = 1; i <= 100; ++i) {
     estimator.addValue(i);
   }
   MockClock::Now += std::chrono::seconds{1};
   auto estimates = estimator.estimateQuantiles(
       std::array<double, 5>{{.001, .01, .5, .99, .999}});
   EXPECT_EQ(5050, estimates.sum);
   EXPECT_EQ(100, estimates.count);
   EXPECT_EQ(0.001, estimates.quantiles[0].first);
   EXPECT_EQ(0.01, estimates.quantiles[1].first);
   EXPECT_EQ(0.5, estimates.quantiles[2].first);
   EXPECT_EQ(0.99, estimates.quantiles[3].first);
   EXPECT_EQ(0.999, estimates.quantiles[4].first);
   EXPECT_EQ(1, estimates.quantiles[0].second);
   EXPECT_EQ(2.0 - 0.5, estimates.quantiles[1].second);
   EXPECT_EQ(50.375, estimates.quantiles[2].second);
   EXPECT_EQ(100.0 - 0.5, estimates.quantiles[3].second);
   EXPECT_EQ(100, estimates.quantiles[4].second);
 }