proxygen: proxygen/folly/folly/stats/detail/test/RadixSortTest.cpp File Reference
RadixSortTest.cpp File Reference
#include <folly/portability/GTest.h>
#include <folly/Random.h>
#include <folly/stats/detail/DoubleRadixSort.h>
Functions
TEST (DoubleRadixSort, Basic)
Function Documentation
TEST (DoubleRadixSort , Basic)
Definition at line 25 of file RadixSortTest.cpp.
References folly::detail::double_radix_sort(), EXPECT_TRUE, i, folly::Random::rand32(), folly::Random::randDouble(), and uint64_t.
{
   std::unique_ptr<uint64_t[]> buckets(new uint64_t[256 * 9]);
   for (int i = 0; i < 100; i++) {
     size_t sz = folly::Random::rand32(0, 100000);
     std::unique_ptr<double[]> in(new double[sz]);
     std::unique_ptr<double[]> out(new double[sz]);
     for (size_t j = 0; j < sz; j++) {
       in[j] = folly::Random::randDouble(-100.0, 100.0);
     }
     double_radix_sort(sz, buckets.get(), in.get(), out.get());
     EXPECT_TRUE(std::is_sorted(in.get(), in.get() + sz));
   }
 }