proxygen: proxygen/folly/folly/test/RandomTest.cpp File Reference
RandomTest.cpp File Reference
#include <folly/Random.h>
#include <algorithm>
#include <random>
#include <thread>
#include <unordered_set>
#include <vector>
#include <glog/logging.h>
#include <folly/portability/GTest.h>
Functions
TEST (Random, StateSize)
TEST (Random, Simple)
TEST (Random, FixedSeed)
TEST (Random, MultiThreaded)
TEST (Random, sanity)
TEST (Random, SecureFork)
Function Documentation
TEST (Random , StateSize)
Definition at line 31 of file RandomTest.cpp.
References EXPECT_EQ.
{
   using namespace folly::detail;
   // uint_fast32_t is uint64_t on x86_64, w00t
   EXPECT_EQ(
       sizeof(uint_fast32_t) / 4 + 3, StateSizeT<std::minstd_rand0>::value);
   EXPECT_EQ(624, StateSizeT<std::mt19937>::value);
 #if FOLLY_HAVE_EXTRANDOM_SFMT19937
   EXPECT_EQ(624, StateSizeT<__gnu_cxx::sfmt19937>::value);
 #endif
   EXPECT_EQ(24, StateSizeT<std::ranlux24_base>::value);
 }
TEST (Random , Simple)
Definition at line 44 of file RandomTest.cpp.
References EXPECT_NE, i, folly::randomNumberSeed(), seed, and uint32_t.
                      {
   uint32_t prev = 0, seed = 0;
   for (int i = 0; i < 1024; ++i) {
     EXPECT_NE(seed = randomNumberSeed(), prev);
     prev = seed;
   }
 }
TEST (Random , FixedSeed)
Definition at line 52 of file RandomTest.cpp.
References EXPECT_EQ, i, max, min, folly::Random::rand32(), uint32_t, and folly::value().
{
   // clang-format off
   struct ConstantRNG {
     typedef uint32_t result_type;
     result_type operator()() {
       return 4; // chosen by fair dice roll.
                 // guaranteed to be random.
     }
     static constexpr result_type min() {
       return std::numeric_limits<result_type>::min();
     }
     static constexpr result_type max() {
       return std::numeric_limits<result_type>::max();
     }
   };
   // clang-format on
   ConstantRNG gen;
   // Pick a constant random number...
   auto value = Random::rand32(10, gen);
   // Loop to make sure it really is constant.
   for (int i = 0; i < 1024; ++i) {
     auto result = Random::rand32(10, gen);
     EXPECT_EQ(value, result);
   }
 }
TEST (Random , MultiThreaded)
Definition at line 81 of file RandomTest.cpp.
References EXPECT_LT, i, folly::randomNumberSeed(), folly::pushmi::detail::t, and threads.
{
   const int n = 100;
   std::vector<uint32_t> seeds(n);
   std::vector<std::thread> threads;
   for (int i = 0; i < n; ++i) {
     threads.push_back(
         std::thread([i, &seeds] { seeds[i] = randomNumberSeed(); }));
   }
   for (auto& t : threads) {
     t.join();
   }
   std::sort(seeds.begin(), seeds.end());
   for (int i = 0; i < n - 1; ++i) {
     EXPECT_LT(seeds[i], seeds[i + 1]);
   }
 }
TEST (Random , sanity)
Definition at line 98 of file RandomTest.cpp.
References EXPECT_EQ, i, folly::Random::rand32(), folly::Random::rand64(), rng, and folly::size().
                      {
   // edge cases
   EXPECT_EQ(folly::Random::rand32(0), 0);
   EXPECT_EQ(folly::Random::rand32(12, 12), 0);
   EXPECT_EQ(folly::Random::rand64(0), 0);
   EXPECT_EQ(folly::Random::rand64(12, 12), 0);
   // 32-bit repeatability, uniqueness
   constexpr int kTestSize = 1000;
   {
     std::vector<uint32_t> vals;
     folly::Random::DefaultGenerator rng;
     rng.seed(0xdeadbeef);
     for (int i = 0; i < kTestSize; ++i) {
       vals.push_back(folly::Random::rand32(rng));
     }
     rng.seed(0xdeadbeef);
     for (int i = 0; i < kTestSize; ++i) {
       EXPECT_EQ(vals[i], folly::Random::rand32(rng));
     }
     EXPECT_EQ(
         vals.size(),
         std::unordered_set<uint32_t>(vals.begin(), vals.end()).size());
   }
   // 64-bit repeatability, uniqueness
   {
     std::vector<uint64_t> vals;
     folly::Random::DefaultGenerator rng;
     rng.seed(0xdeadbeef);
     for (int i = 0; i < kTestSize; ++i) {
       vals.push_back(folly::Random::rand64(rng));
     }
     rng.seed(0xdeadbeef);
     for (int i = 0; i < kTestSize; ++i) {
       EXPECT_EQ(vals[i], folly::Random::rand64(rng));
     }
     EXPECT_EQ(
         vals.size(),
         std::unordered_set<uint64_t>(vals.begin(), vals.end()).size());
   }
 }
TEST (Random , SecureFork)
Definition at line 142 of file RandomTest.cpp.
References buffer(), EXPECT_EQ, EXPECT_NE, folly::Random::secureRandom(), and folly::detail::distributed_mutex::wait().
{
   // Random buffer size is 128, must be less than that.
   int retries = 100;
   while (true) {
     unsigned char buffer = 0;
     // Init random buffer
     folly::Random::secureRandom(&buffer, 1);
     auto pid = fork();
     EXPECT_NE(pid, -1);
     if (pid) {
       // parent
       int status = 0;
       folly::Random::secureRandom(&buffer, 1);
       auto pid2 = wait(&status);
       EXPECT_EQ(pid, pid2);
       // Since this *is* random data, we could randomly end up with
       // the same byte.  Try again a few times if so before assuming
       // real failure.
       if (WEXITSTATUS(status) == buffer && retries-- > 0) {
         continue;
       }
       EXPECT_NE(WEXITSTATUS(status), buffer);
       return;
     } else {
       // child
       folly::Random::secureRandom(&buffer, 1);
       exit(buffer); // Do not print gtest results
     }
   }
 }