proxygen: proxygen/folly/folly/test/RandomBenchmark.cpp File Reference
RandomBenchmark.cpp File Reference
#include <folly/Random.h>
#include <random>
#include <thread>
#include <glog/logging.h>
#include <folly/Benchmark.h>
#include <folly/container/Foreach.h>
Functions
BENCHMARK (minstdrand, n)
BENCHMARK (mt19937, n)
BENCHMARK (threadprng, n)
BENCHMARK (RandomDouble)
BENCHMARK (Random32)
BENCHMARK (Random32Num)
BENCHMARK (Random64)
BENCHMARK (Random64Num)
BENCHMARK (Random64OneIn)
int main (int argc, char **argv)
Function Documentation
BENCHMARK (minstdrand , n)
Definition at line 33 of file RandomBenchmark.cpp.
References folly::BenchmarkSuspender::dismiss(), folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, rd, and rng.
{
   BenchmarkSuspender braces;
   std::random_device rd;
   std::minstd_rand rng(rd());
   braces.dismiss();
   FOR_EACH_RANGE (i, 0, n) { doNotOptimizeAway(rng()); }
 }
BENCHMARK (mt19937 , n)
Definition at line 43 of file RandomBenchmark.cpp.
References folly::BENCHMARK(), folly::BenchmarkSuspender::dismiss(), folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, rd, and rng.
                       {
   BenchmarkSuspender braces;
   std::random_device rd;
   std::mt19937 rng(rd());
   braces.dismiss();
   FOR_EACH_RANGE (i, 0, n) { doNotOptimizeAway(rng()); }
 }
BENCHMARK (threadprng , n)
Definition at line 65 of file RandomBenchmark.cpp.
References folly::BenchmarkSuspender::dismiss(), folly::doNotOptimizeAway(), FOR_EACH_RANGE, and i.
{
   BenchmarkSuspender braces;
   ThreadLocalPRNG tprng;
   tprng();
   braces.dismiss();
   FOR_EACH_RANGE (i, 0, n) { doNotOptimizeAway(tprng()); }
 }
BENCHMARK (RandomDouble)
Definition at line 75 of file RandomBenchmark.cpp.
References folly::doNotOptimizeAway(), and folly::Random::randDouble01().
{
   doNotOptimizeAway(Random::randDouble01());
 }
BENCHMARK (Random32)
Definition at line 78 of file RandomBenchmark.cpp.
References folly::doNotOptimizeAway(), and folly::Random::rand32().
                     {
   doNotOptimizeAway(Random::rand32());
 }
BENCHMARK (Random32Num)
Definition at line 81 of file RandomBenchmark.cpp.
References folly::doNotOptimizeAway(), and folly::Random::rand32().
{
   doNotOptimizeAway(Random::rand32(100));
 }
BENCHMARK (Random64)
Definition at line 84 of file RandomBenchmark.cpp.
References folly::doNotOptimizeAway(), and folly::Random::rand64().
                     {
   doNotOptimizeAway(Random::rand64());
 }
BENCHMARK (Random64Num)
Definition at line 87 of file RandomBenchmark.cpp.
References folly::doNotOptimizeAway(), and folly::Random::rand64().
{
   doNotOptimizeAway(Random::rand64(100ull << 32));
 }
BENCHMARK (Random64OneIn)
Definition at line 90 of file RandomBenchmark.cpp.
References folly::doNotOptimizeAway(), and folly::Random::oneIn().
{
   doNotOptimizeAway(Random::oneIn(100));
 }
int main (int argc, char ** argv)
Definition at line 94 of file RandomBenchmark.cpp.
References folly::runBenchmarks().
{
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   folly::runBenchmarks();
   return 0;
 }