proxygen: proxygen/folly/folly/test/RangeFindBenchmark.cpp File Reference
RangeFindBenchmark.cpp File Reference
#include <folly/Range.h>
#include <algorithm>
#include <iostream>
#include <random>
#include <string>
#include <folly/Benchmark.h>
#include <folly/container/Foreach.h>
Functions
BENCHMARK (FindSingleCharMemchr, n)
BENCHMARK_RELATIVE (FindSingleCharRange, n)
BENCHMARK_DRAW_LINE ()
template<class Func >
void countHits (Func func, size_t n)
template<class Func >
void findFirstOfRange (StringPiece needles, Func func, size_t n)
BENCHMARK (FindFirstOf1NeedlesBase, n)
BENCHMARK_RELATIVE (FindFirstOf1NeedlesNoSSE, n)
BENCHMARK_RELATIVE (FindFirstOf1NeedlesStd, n)
BENCHMARK_RELATIVE (FindFirstOf1NeedlesByteSet, n)
BENCHMARK_RELATIVE (FindFirstOf1NeedlesBitSet, n)
BENCHMARK (FindFirstOf2NeedlesBase, n)
BENCHMARK_RELATIVE (FindFirstOf2NeedlesNoSSE, n)
BENCHMARK_RELATIVE (FindFirstOf2NeedlesStd, n)
BENCHMARK_RELATIVE (FindFirstOf2NeedlesByteSet, n)
BENCHMARK_RELATIVE (FindFirstOf2NeedlesBitSet, n)
BENCHMARK (FindFirstOf4NeedlesBase, n)
BENCHMARK_RELATIVE (FindFirstOf4NeedlesNoSSE, n)
BENCHMARK_RELATIVE (FindFirstOf4NeedlesStd, n)
BENCHMARK_RELATIVE (FindFirstOf4NeedlesByteSet, n)
BENCHMARK_RELATIVE (FindFirstOf4NeedlesBitSet, n)
BENCHMARK (FindFirstOf8NeedlesBase, n)
BENCHMARK_RELATIVE (FindFirstOf8NeedlesNoSSE, n)
BENCHMARK_RELATIVE (FindFirstOf8NeedlesStd, n)
BENCHMARK_RELATIVE (FindFirstOf8NeedlesByteSet, n)
BENCHMARK_RELATIVE (FindFirstOf8NeedlesBitSet, n)
BENCHMARK (FindFirstOf16NeedlesBase, n)
BENCHMARK_RELATIVE (FindFirstOf16NeedlesNoSSE, n)
BENCHMARK_RELATIVE (FindFirstOf16NeedlesStd, n)
BENCHMARK_RELATIVE (FindFirstOf16NeedlesByteSet, n)
BENCHMARK_RELATIVE (FindFirstOf16NeedlesBitSet, n)
BENCHMARK (FindFirstOf32NeedlesBase, n)
BENCHMARK_RELATIVE (FindFirstOf32NeedlesNoSSE, n)
BENCHMARK_RELATIVE (FindFirstOf32NeedlesStd, n)
BENCHMARK_RELATIVE (FindFirstOf32NeedlesByteSet, n)
BENCHMARK_RELATIVE (FindFirstOf32NeedlesBitSet, n)
BENCHMARK (FindFirstOf64NeedlesBase, n)
BENCHMARK_RELATIVE (FindFirstOf64NeedlesNoSSE, n)
BENCHMARK_RELATIVE (FindFirstOf64NeedlesStd, n)
BENCHMARK_RELATIVE (FindFirstOf64NeedlesByteSet, n)
BENCHMARK_RELATIVE (FindFirstOf64NeedlesBitSet, n)
template<class Func >
void findFirstOfRandom (Func func, size_t iters)
BENCHMARK (FindFirstOfRandomBase, n)
BENCHMARK_RELATIVE (FindFirstOfRandomNoSSE, n)
BENCHMARK_RELATIVE (FindFirstOfRandomStd, n)
BENCHMARK_RELATIVE (FindFirstOfRandomByteSet, n)
BENCHMARK_RELATIVE (FindFirstOfRandomBitSet, n)
BENCHMARK (CountDelimsBase, n)
BENCHMARK_RELATIVE (CountDelimsNoSSE, n)
BENCHMARK_RELATIVE (CountDelimsStd, n)
BENCHMARK_RELATIVE (CountDelimsByteSet, n)
BENCHMARK_RELATIVE (CountDelimsBitSet, n)
BENCHMARK (FindFirstOfOffsetRange, n)
int main (int argc, char **argv)
Variables
const string delims1 = "b"
const string delims2 = "bc"
const string delims4 = "bcde"
const string delims8 = "0123456b"
const string delims16 = "0123456789bcdefg"
const string delims32 = "!bcdefghijklmnopqrstuvwxyz_012345"
const string delims64
Function Documentation
BENCHMARK (FindSingleCharMemchr , n)
Definition at line 116 of file RangeFindBenchmark.cpp.
References folly::doNotOptimizeAway(), folly::Range< Iter >::find(), FOR_EACH_RANGE, and i.
{
   StringPiece haystack(str);
   FOR_EACH_RANGE (i, 0, n) {
     doNotOptimizeAway(haystack.find('b'));
     char x = haystack[0];
     doNotOptimizeAway(&x);
   }
 }
BENCHMARK (FindFirstOf1NeedlesBase , n)
Definition at line 164 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of().
{
   findFirstOfRange(delims1, detail::qfind_first_byte_of, n);
 }
BENCHMARK (FindFirstOf2NeedlesBase , n)
Definition at line 188 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of().
{
   findFirstOfRange(delims2, detail::qfind_first_byte_of, n);
 }
BENCHMARK (FindFirstOf4NeedlesBase , n)
Definition at line 212 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of().
{
   findFirstOfRange(delims4, detail::qfind_first_byte_of, n);
 }
BENCHMARK (FindFirstOf8NeedlesBase , n)
Definition at line 236 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of().
{
   findFirstOfRange(delims8, detail::qfind_first_byte_of, n);
 }
BENCHMARK (FindFirstOf16NeedlesBase , n)
Definition at line 260 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of().
{
   findFirstOfRange(delims16, detail::qfind_first_byte_of, n);
 }
BENCHMARK (FindFirstOf32NeedlesBase , n)
Definition at line 284 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of().
{
   findFirstOfRange(delims32, detail::qfind_first_byte_of, n);
 }
BENCHMARK (FindFirstOf64NeedlesBase , n)
Definition at line 310 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of().
{
   findFirstOfRange(delims64, detail::qfind_first_byte_of, n);
 }
BENCHMARK (FindFirstOfRandomBase , n)
Definition at line 341 of file RangeFindBenchmark.cpp.
References findFirstOfRandom(), and folly::detail::qfind_first_byte_of().
{
   findFirstOfRandom(detail::qfind_first_byte_of, n);
 }
BENCHMARK (CountDelimsBase , n)
Definition at line 363 of file RangeFindBenchmark.cpp.
References countHits(), and folly::detail::qfind_first_byte_of().
{
   countHits(detail::qfind_first_byte_of, n);
 }
BENCHMARK (FindFirstOfOffsetRange , n)
Definition at line 385 of file RangeFindBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE(), folly::doNotOptimizeAway(), folly::Range< Iter >::find_first_of(), FOR_EACH_RANGE, i, and folly::Range< Iter >::size().
{
   StringPiece haystack(str);
   folly::StringPiece needles("bc");
   DCHECK_EQ(haystack.size() - 1, haystack.find_first_of(needles, 1)); // works!
   FOR_EACH_RANGE (i, 0, n) {
     size_t pos = i % 2; // not a constant to prevent optimization
     doNotOptimizeAway(haystack.find_first_of(needles, pos));
     char x = haystack[0];
     doNotOptimizeAway(&x);
   }
 }
BENCHMARK_DRAW_LINE ()
BENCHMARK_RELATIVE (FindSingleCharRange , n)
Definition at line 125 of file RangeFindBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE(), c, folly::doNotOptimizeAway(), folly::Range< Iter >::find(), FOR_EACH_RANGE, i, and needle.
{
   const char c = 'b';
   StringPiece haystack(str);
   folly::StringPiece needle(&c, &c + 1);
   FOR_EACH_RANGE (i, 0, n) {
     doNotOptimizeAway(haystack.find(needle));
     char x = haystack[0];
     doNotOptimizeAway(&x);
   }
 }
BENCHMARK_RELATIVE (FindFirstOf1NeedlesNoSSE , n)
Definition at line 168 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of_nosse().
{
   findFirstOfRange(delims1, detail::qfind_first_byte_of_nosse, n);
 }
BENCHMARK_RELATIVE (FindFirstOf1NeedlesStd , n)
Definition at line 172 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of_std().
{
   findFirstOfRange(delims1, detail::qfind_first_byte_of_std, n);
 }
BENCHMARK_RELATIVE (FindFirstOf1NeedlesByteSet , n)
Definition at line 176 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of_byteset().
{
   findFirstOfRange(delims1, detail::qfind_first_byte_of_byteset, n);
 }
BENCHMARK_RELATIVE (FindFirstOf1NeedlesBitSet , n)
Definition at line 180 of file RangeFindBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE(), findFirstOfRange(), and folly::detail::qfind_first_byte_of_bitset().
{
   findFirstOfRange(delims1, detail::qfind_first_byte_of_bitset, n);
 }
BENCHMARK_RELATIVE (FindFirstOf2NeedlesNoSSE , n)
Definition at line 192 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of_nosse().
{
   findFirstOfRange(delims2, detail::qfind_first_byte_of_nosse, n);
 }
BENCHMARK_RELATIVE (FindFirstOf2NeedlesStd , n)
Definition at line 196 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of_std().
{
   findFirstOfRange(delims2, detail::qfind_first_byte_of_std, n);
 }
BENCHMARK_RELATIVE (FindFirstOf2NeedlesByteSet , n)
Definition at line 200 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of_byteset().
{
   findFirstOfRange(delims2, detail::qfind_first_byte_of_byteset, n);
 }
BENCHMARK_RELATIVE (FindFirstOf2NeedlesBitSet , n)
Definition at line 204 of file RangeFindBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE(), findFirstOfRange(), and folly::detail::qfind_first_byte_of_bitset().
{
   findFirstOfRange(delims2, detail::qfind_first_byte_of_bitset, n);
 }
BENCHMARK_RELATIVE (FindFirstOf4NeedlesNoSSE , n)
Definition at line 216 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of_nosse().
{
   findFirstOfRange(delims4, detail::qfind_first_byte_of_nosse, n);
 }
BENCHMARK_RELATIVE (FindFirstOf4NeedlesStd , n)
Definition at line 220 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of_std().
{
   findFirstOfRange(delims4, detail::qfind_first_byte_of_std, n);
 }
BENCHMARK_RELATIVE (FindFirstOf4NeedlesByteSet , n)
Definition at line 224 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of_byteset().
{
   findFirstOfRange(delims4, detail::qfind_first_byte_of_byteset, n);
 }
BENCHMARK_RELATIVE (FindFirstOf4NeedlesBitSet , n)
Definition at line 228 of file RangeFindBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE(), findFirstOfRange(), and folly::detail::qfind_first_byte_of_bitset().
{
   findFirstOfRange(delims4, detail::qfind_first_byte_of_bitset, n);
 }
BENCHMARK_RELATIVE (FindFirstOf8NeedlesNoSSE , n)
Definition at line 240 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of_nosse().
{
   findFirstOfRange(delims8, detail::qfind_first_byte_of_nosse, n);
 }
BENCHMARK_RELATIVE (FindFirstOf8NeedlesStd , n)
Definition at line 244 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of_std().
{
   findFirstOfRange(delims8, detail::qfind_first_byte_of_std, n);
 }
BENCHMARK_RELATIVE (FindFirstOf8NeedlesByteSet , n)
Definition at line 248 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of_byteset().
{
   findFirstOfRange(delims8, detail::qfind_first_byte_of_byteset, n);
 }
BENCHMARK_RELATIVE (FindFirstOf8NeedlesBitSet , n)
Definition at line 252 of file RangeFindBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE(), findFirstOfRange(), and folly::detail::qfind_first_byte_of_bitset().
{
   findFirstOfRange(delims8, detail::qfind_first_byte_of_bitset, n);
 }
BENCHMARK_RELATIVE (FindFirstOf16NeedlesNoSSE , n)
Definition at line 264 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of_nosse().
{
   findFirstOfRange(delims16, detail::qfind_first_byte_of_nosse, n);
 }
BENCHMARK_RELATIVE (FindFirstOf16NeedlesStd , n)
Definition at line 268 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of_std().
{
   findFirstOfRange(delims16, detail::qfind_first_byte_of_std, n);
 }
BENCHMARK_RELATIVE (FindFirstOf16NeedlesByteSet , n)
Definition at line 272 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of_byteset().
{
   findFirstOfRange(delims16, detail::qfind_first_byte_of_byteset, n);
 }
BENCHMARK_RELATIVE (FindFirstOf16NeedlesBitSet , n)
Definition at line 276 of file RangeFindBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE(), findFirstOfRange(), and folly::detail::qfind_first_byte_of_bitset().
{
   findFirstOfRange(delims16, detail::qfind_first_byte_of_bitset, n);
 }
BENCHMARK_RELATIVE (FindFirstOf32NeedlesNoSSE , n)
Definition at line 288 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of_nosse().
{
   findFirstOfRange(delims32, detail::qfind_first_byte_of_nosse, n);
 }
BENCHMARK_RELATIVE (FindFirstOf32NeedlesStd , n)
Definition at line 292 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of_std().
{
   findFirstOfRange(delims32, detail::qfind_first_byte_of_std, n);
 }
BENCHMARK_RELATIVE (FindFirstOf32NeedlesByteSet , n)
Definition at line 296 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of_byteset().
{
   findFirstOfRange(delims32, detail::qfind_first_byte_of_byteset, n);
 }
BENCHMARK_RELATIVE (FindFirstOf32NeedlesBitSet , n)
Definition at line 300 of file RangeFindBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE(), findFirstOfRange(), and folly::detail::qfind_first_byte_of_bitset().
{
   findFirstOfRange(delims32, detail::qfind_first_byte_of_bitset, n);
 }
BENCHMARK_RELATIVE (FindFirstOf64NeedlesNoSSE , n)
Definition at line 314 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of_nosse().
{
   findFirstOfRange(delims64, detail::qfind_first_byte_of_nosse, n);
 }
BENCHMARK_RELATIVE (FindFirstOf64NeedlesStd , n)
Definition at line 318 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of_std().
{
   findFirstOfRange(delims64, detail::qfind_first_byte_of_std, n);
 }
BENCHMARK_RELATIVE (FindFirstOf64NeedlesByteSet , n)
Definition at line 322 of file RangeFindBenchmark.cpp.
References findFirstOfRange(), and folly::detail::qfind_first_byte_of_byteset().
{
   findFirstOfRange(delims64, detail::qfind_first_byte_of_byteset, n);
 }
BENCHMARK_RELATIVE (FindFirstOf64NeedlesBitSet , n)
Definition at line 326 of file RangeFindBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE(), findFirstOfRange(), and folly::detail::qfind_first_byte_of_bitset().
{
   findFirstOfRange(delims64, detail::qfind_first_byte_of_bitset, n);
 }
BENCHMARK_RELATIVE (FindFirstOfRandomNoSSE , n)
Definition at line 345 of file RangeFindBenchmark.cpp.
References findFirstOfRandom(), and folly::detail::qfind_first_byte_of_nosse().
{
   findFirstOfRandom(detail::qfind_first_byte_of_nosse, n);
 }
BENCHMARK_RELATIVE (FindFirstOfRandomStd , n)
Definition at line 349 of file RangeFindBenchmark.cpp.
References findFirstOfRandom(), and folly::detail::qfind_first_byte_of_std().
{
   findFirstOfRandom(detail::qfind_first_byte_of_std, n);
 }
BENCHMARK_RELATIVE (FindFirstOfRandomByteSet , n)
Definition at line 353 of file RangeFindBenchmark.cpp.
References findFirstOfRandom(), and folly::detail::qfind_first_byte_of_byteset().
{
   findFirstOfRandom(detail::qfind_first_byte_of_byteset, n);
 }
BENCHMARK_RELATIVE (FindFirstOfRandomBitSet , n)
Definition at line 357 of file RangeFindBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE(), findFirstOfRandom(), and folly::detail::qfind_first_byte_of_bitset().
{
   findFirstOfRandom(detail::qfind_first_byte_of_bitset, n);
 }
BENCHMARK_RELATIVE (CountDelimsNoSSE , n)
Definition at line 367 of file RangeFindBenchmark.cpp.
References countHits(), and folly::detail::qfind_first_byte_of_nosse().
{
   countHits(detail::qfind_first_byte_of_nosse, n);
 }
BENCHMARK_RELATIVE (CountDelimsStd , n)
Definition at line 371 of file RangeFindBenchmark.cpp.
References countHits(), and folly::detail::qfind_first_byte_of_std().
{
   countHits(detail::qfind_first_byte_of_std, n);
 }
BENCHMARK_RELATIVE (CountDelimsByteSet , n)
Definition at line 375 of file RangeFindBenchmark.cpp.
References countHits(), and folly::detail::qfind_first_byte_of_byteset().
{
   countHits(detail::qfind_first_byte_of_byteset, n);
 }
BENCHMARK_RELATIVE (CountDelimsBitSet , n)
Definition at line 379 of file RangeFindBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE(), countHits(), and folly::detail::qfind_first_byte_of_bitset().
{
   countHits(detail::qfind_first_byte_of_bitset, n);
 }
template<class Func > void countHits (Func func, size_t n)
Definition at line 139 of file RangeFindBenchmark.cpp.
References c, folly::doNotOptimizeAway(), FOR_EACH_RANGE, i, and folly::Range< const char * >::npos.
Referenced by BENCHMARK(), and BENCHMARK_RELATIVE().
{
   StringPiece needles = "\r\n\1";
   FOR_EACH_RANGE (i, 0, n) {
     size_t p, c = 0;
     for (StringPiece left = file;
          (p = func(left, needles)) != StringPiece::npos;
          left.advance(p + 1)) {
       ++c;
     }
     doNotOptimizeAway(c);
   }
 }
template<class Func > void findFirstOfRandom (Func func, size_t iters)
Definition at line 333 of file RangeFindBenchmark.cpp.
References folly::doNotOptimizeAway(), and i.
Referenced by BENCHMARK(), and BENCHMARK_RELATIVE().
{
   for (size_t i = 0; i < iters; ++i) {
     auto test = i % ffoDelim.size();
     auto p = func(ffoTestString, ffoDelim[test]);
     doNotOptimizeAway(p);
   }
 }
template<class Func > void findFirstOfRange (StringPiece needles, Func func, size_t n)
Definition at line 153 of file RangeFindBenchmark.cpp.
References folly::doNotOptimizeAway(), FOR_EACH_RANGE, and i.
Referenced by BENCHMARK(), and BENCHMARK_RELATIVE().
{
   FOR_EACH_RANGE (i, 0, n) {
     const StringPiece haystack = vstrp[i % kVstrSize];
     doNotOptimizeAway(func(haystack, needles));
     char x = haystack[0];
     doNotOptimizeAway(&x);
   }
 }
int main (int argc, char ** argv)
Definition at line 399 of file RangeFindBenchmark.cpp.
References folly::runBenchmarks().
{
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   for (int len : {1, 8, 10, 16, 32, 64, 128, 256, 10 * 1024, 1024 * 1024}) {
     initStr(len);
     initDelims(len);
     initFile(len);
     runBenchmarks();
   }
   return 0;
 }
Variable Documentation
const string delims1 = "b"
Definition at line 162 of file RangeFindBenchmark.cpp.
const string delims16 = "0123456789bcdefg"
Definition at line 258 of file RangeFindBenchmark.cpp.
const string delims2 = "bc"
Definition at line 186 of file RangeFindBenchmark.cpp.
const string delims32 = "!bcdefghijklmnopqrstuvwxyz_012345"
Definition at line 282 of file RangeFindBenchmark.cpp.
const string delims4 = "bcde"
Definition at line 210 of file RangeFindBenchmark.cpp.
const string delims64
Initial value:
=
    "!bcdefghijklmnopqrstuvwxyz_"
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ-0123456789$"
Definition at line 306 of file RangeFindBenchmark.cpp.
const string delims8 = "0123456b"
Definition at line 234 of file RangeFindBenchmark.cpp.