proxygen: proxygen/folly/folly/synchronization/test/RcuBenchmark.cpp File Reference
RcuBenchmark.cpp File Reference
#include <folly/Benchmark.h>
#include <folly/synchronization/Rcu.h>
Functions
void runTest (int iters)
BENCHMARK_DRAW_LINE ()
BENCHMARK (RcuReader, iters)
int main (int argc, char *argv[])
Function Documentation
BENCHMARK (RcuReader , iters)
Definition at line 35 of file RcuBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE(), and runTest().
{
   runTest(iters);
 }
BENCHMARK_DRAW_LINE ()
int main (int argc, char * argv[])
Definition at line 40 of file RcuBenchmark.cpp.
References folly::runBenchmarks().
{
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   folly::runBenchmarks();
   return 0;
 }
void runTest (int iters)
Definition at line 22 of file RcuBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE(), folly::BenchmarkSuspender::dismiss(), g(), and i.
Referenced by BENCHMARK().
{
   BenchmarkSuspender susp;
   { rcu_reader g; }
   susp.dismiss();
   // run the test loop
   for (int i = 0; i < iters; i++) {
     rcu_reader g;
   }
 }