proxygen: proxygen/folly/folly/experimental/pushmi/examples/reduce/reduce_3.cpp File Reference
reduce_3.cpp File Reference
#include <cassert>
#include <exception>
#include <iostream>
#include <numeric>
#include <vector>
#include <folly/experimental/pushmi/examples/reduce.h>
Functions
auto inline_bulk_target ()
int main ()
Function Documentation
auto inline_bulk_target ()
Definition at line 26 of file reduce_3.cpp.
References folly::init(), folly::gen::move, folly::pushmi::set_error, and folly::pushmi::set_value.
Referenced by main().
{
   return [](auto init,
             auto selector,
             auto input,
             auto&& func,
             auto sb,
             auto se,
             auto out) {
     try {
       auto acc = init(input);
       for (decltype(sb) idx{sb}; idx != se; ++idx) {
         func(acc, idx);
       }
       auto result = selector(std::move(acc));
       mi::set_value(out, std::move(result));
     } catch (...) {
       mi::set_error(out, std::current_exception());
     }
   };
 }
int main (void)
Definition at line 47 of file reduce_3.cpp.
References folly::f14::accumulate(), inline_bulk_target(), and folly::pushmi::reduce.
            {
   std::vector<int> vec(10);
   std::fill(vec.begin(), vec.end(), 4);
   auto fortyTwo = mi::reduce(
       inline_bulk_target(), vec.begin(), vec.end(), 2, std::plus<>{});
   assert(std::accumulate(vec.begin(), vec.end(), 2) == fortyTwo);
   std::cout << fortyTwo << std::endl;
   std::cout << "OK" << std::endl;
 }