proxygen: proxygen/httpserver/tests/RequestHandlerAdaptorTest.cpp File Reference
RequestHandlerAdaptorTest.cpp File Reference
#include <folly/portability/GTest.h>
#include <folly/portability/GMock.h>
#include "proxygen/httpserver/Mocks.h"
#include <proxygen/httpserver/RequestHandlerAdaptor.h>
#include "proxygen/lib/http/session/test/HTTPTransactionMocks.h"
Classes
struct StubRequestHandlerAdaptor
Functions
void testExpectHandling (bool handlerResponds)
TEST (RequestHandlerAdaptorTest, Expect)
TEST (RequestHandlerAdaptorTest, onError)
Function Documentation
TEST (RequestHandlerAdaptorTest , Expect)
Definition at line 47 of file RequestHandlerAdaptorTest.cpp.
References testExpectHandling().
{
   testExpectHandling(true /* handlerResponds */);
   testExpectHandling(false /* handlerResponds */);
 }
TEST (RequestHandlerAdaptorTest , onError)
Definition at line 52 of file RequestHandlerAdaptorTest.cpp.
References proxygen::kErrorTimeout, proxygen::HTTPTransaction::onError(), proxygen::HTTPTransaction::setHandler(), and proxygen::Exception::setProxygenError().
{
   NiceMock<MockRequestHandler> requestHandler_;
   auto adaptor = new RequestHandlerAdaptor(&requestHandler_);
   NiceMock<MockHTTPTransactionTransport> transport;
   HTTP2PriorityQueue egressQueue;
   HTTPTransaction txn(TransportDirection::DOWNSTREAM,
                       1, 1, transport, egressQueue);
   txn.setHandler(adaptor);
   // egress timeout error
   HTTPException ex(HTTPException::Direction::EGRESS, "egress timeout");
   ex.setProxygenError(kErrorTimeout);
   txn.onError(ex);
 }
void testExpectHandling (bool handlerResponds)
Definition at line 34 of file RequestHandlerAdaptorTest.cpp.
References testing::_, EXPECT_CALL, EXPECT_EQ, folly::gen::move, proxygen::HTTPTransactionHandler::onHeadersComplete(), and testing::Return().
Referenced by TEST().
{
   StrictMock<MockRequestHandler> requestHandler_;
   EXPECT_CALL(requestHandler_, canHandleExpect()).WillOnce(
     Return(handlerResponds));
   EXPECT_CALL(requestHandler_, onRequest(_));
   auto adaptor = std::make_shared<StubRequestHandlerAdaptor>(&requestHandler_);
   auto msg = std::make_unique<HTTPMessage>();
   msg->getHeaders().add("Expect", "100-continue");
   auto txHandler = std::dynamic_pointer_cast<HTTPTransactionHandler>(adaptor);
   txHandler->onHeadersComplete(std::move(msg));
   EXPECT_EQ(adaptor->headersSent_, !handlerResponds);
 }