proxygen: proxygen/folly/folly/io/async/test/RequestContextTest.cpp File Reference
RequestContextTest.cpp File Reference
#include <thread>
#include <folly/Memory.h>
#include <folly/io/async/EventBase.h>
#include <folly/io/async/Request.h>
#include <folly/portability/GTest.h>
Classes
class TestData
class RequestContextTest
Functions
TEST_F (RequestContextTest, SimpleTest)
TEST_F (RequestContextTest, RequestContextScopeGuard)
TEST_F (RequestContextTest, defaultContext)
TEST_F (RequestContextTest, setIfAbsentTest)
TEST_F (RequestContextTest, testSetUnset)
TEST_F (RequestContextTest, deadlockTest)
TEST_F (RequestContextTest, sharedGlobalTest)
TEST_F (RequestContextTest, ShallowCopyBasic)
TEST_F (RequestContextTest, ShallowCopyOverwrite)
TEST_F (RequestContextTest, ShallowCopyDefaultContext)
TEST_F (RequestContextTest, ShallowCopyClear)
Variables
RequestToken testtoken ("test")
Function Documentation
TEST_F (RequestContextTest , SimpleTest)
Definition at line 95 of file RequestContextTest.cpp.
References a, folly::RequestContext::create(), folly::data(), data_, EXPECT_EQ, EXPECT_NE, EXPECT_TRUE, folly::RequestContext::get(), folly::RequestContext::getContextData(), folly::EventBase::loopForever(), folly::EventBase::runInEventBaseThread(), folly::RequestContext::saveContext(), folly::RequestContext::setContext(), folly::RequestContext::setContextData(), folly::EventBase::terminateLoopSoon(), and testtoken.
{
   EventBase base;
   // There should always be a default context with get()
   EXPECT_TRUE(RequestContext::get() != nullptr);
   // but not with saveContext()
   EXPECT_EQ(RequestContext::saveContext(), nullptr);
   RequestContext::create();
   EXPECT_NE(RequestContext::saveContext(), nullptr);
   RequestContext::create();
   EXPECT_NE(RequestContext::saveContext(), nullptr);
   EXPECT_EQ(nullptr, RequestContext::get()->getContextData("test"));
   RequestContext::get()->setContextData("test", std::make_unique<TestData>(10));
   base.runInEventBaseThread([&]() {
     EXPECT_TRUE(RequestContext::get() != nullptr);
     auto data = dynamic_cast<TestData*>(
                     RequestContext::get()->getContextData(testtoken))
                     ->data_;
     EXPECT_EQ(10, data);
     base.terminateLoopSoon();
   });
   auto th = std::thread([&]() { base.loopForever(); });
   th.join();
   EXPECT_TRUE(RequestContext::get() != nullptr);
   auto a =
       dynamic_cast<TestData*>(RequestContext::get()->getContextData("test"));
   auto data = a->data_;
   EXPECT_EQ(10, data);
   RequestContext::setContext(std::shared_ptr<RequestContext>());
   // There should always be a default context
   EXPECT_TRUE(nullptr != RequestContext::get());
 }
TEST_F (RequestContextTest , RequestContextScopeGuard)
Definition at line 132 of file RequestContextTest.cpp.
References data_, EXPECT_EQ, and EXPECT_FALSE.
{
   RequestContextScopeGuard g0;
   setData(10);
   {
     RequestContextScopeGuard g1;
     EXPECT_FALSE(hasData());
     setData(20);
     EXPECT_EQ(20, getData().data_);
     EXPECT_EQ(1, getData().set_);
     EXPECT_EQ(0, getData().unset_);
   }
   EXPECT_EQ(10, getData().data_);
   EXPECT_EQ(2, getData().set_);
   EXPECT_EQ(1, getData().unset_);
 }
TEST_F (RequestContextTest , defaultContext)
Definition at line 148 of file RequestContextTest.cpp.
References data_, EXPECT_EQ, and EXPECT_FALSE.
{
   // Don't create a top level guard
   setData(10);
   {
     RequestContextScopeGuard g1;
     EXPECT_FALSE(hasData());
   }
   EXPECT_EQ(10, getData().data_);
   EXPECT_EQ(1, getData().set_);
   EXPECT_EQ(0, getData().unset_);
 }
TEST_F (RequestContextTest , setIfAbsentTest)
Definition at line 160 of file RequestContextTest.cpp.
References data_, EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, folly::RequestContext::get(), folly::RequestContext::setContext(), folly::RequestContext::setContextData(), and testtoken.
{
   EXPECT_TRUE(RequestContext::get() != nullptr);
   RequestContext::get()->setContextData("test", std::make_unique<TestData>(10));
   EXPECT_FALSE(RequestContext::get()->setContextDataIfAbsent(
       "test", std::make_unique<TestData>(20)));
   EXPECT_EQ(
       10,
       dynamic_cast<TestData*>(RequestContext::get()->getContextData(testtoken))
           ->data_);
   EXPECT_TRUE(RequestContext::get()->setContextDataIfAbsent(
       "test2", std::make_unique<TestData>(20)));
   EXPECT_EQ(
       20,
       dynamic_cast<TestData*>(RequestContext::get()->getContextData("test2"))
           ->data_);
   RequestContext::setContext(std::shared_ptr<RequestContext>());
   EXPECT_TRUE(nullptr != RequestContext::get());
 }
TEST_F (RequestContextTest , testSetUnset)
Definition at line 182 of file RequestContextTest.cpp.
References folly::RequestContext::create(), EXPECT_EQ, folly::RequestContext::saveContext(), folly::RequestContext::setContext(), and testtoken.
{
   RequestContext::create();
   auto ctx1 = RequestContext::saveContext();
   ctx1->setContextData("test", std::make_unique<TestData>(10));
   auto testData1 = dynamic_cast<TestData*>(ctx1->getContextData("test"));
   // onSet called in setContextData
   EXPECT_EQ(1, testData1->set_);
   // Override RequestContext
   RequestContext::create();
   auto ctx2 = RequestContext::saveContext();
   ctx2->setContextData(testtoken, std::make_unique<TestData>(20));
   auto testData2 = dynamic_cast<TestData*>(ctx2->getContextData(testtoken));
   // onSet called in setContextData
   EXPECT_EQ(1, testData2->set_);
   // Check ctx1->onUnset was called
   EXPECT_EQ(1, testData1->unset_);
   RequestContext::setContext(ctx1);
   EXPECT_EQ(2, testData1->set_);
   EXPECT_EQ(1, testData1->unset_);
   EXPECT_EQ(1, testData2->unset_);
   RequestContext::setContext(ctx2);
   EXPECT_EQ(2, testData1->set_);
   EXPECT_EQ(2, testData1->unset_);
   EXPECT_EQ(2, testData2->set_);
   EXPECT_EQ(1, testData2->unset_);
 }
TEST_F (RequestContextTest , deadlockTest)
Definition at line 215 of file RequestContextTest.cpp.
References folly::RequestContext::clearContextData(), folly::RequestContext::get(), folly::RequestContext::setContextData(), string, testtoken, and val.
{
   class DeadlockTestData : public RequestData {
    public:
     explicit DeadlockTestData(const std::string& val) : val_(val) {}
     ~DeadlockTestData() override {
       RequestContext::get()->setContextData(
           val_, std::make_unique<TestData>(1));
     }
     bool hasCallback() override {
       return false;
     }
     std::string val_;
   };
   RequestContext::get()->setContextData(
       "test", std::make_unique<DeadlockTestData>("test2"));
   RequestContext::get()->clearContextData(testtoken);
 }
TEST_F (RequestContextTest , sharedGlobalTest)
Definition at line 239 of file RequestContextTest.cpp.
References ASSERT_FALSE, ASSERT_TRUE, folly::RequestContext::get(), and folly::RequestContext::setContextData().
{
   static bool global = false;
   class GlobalTestData : public RequestData {
    public:
     void onSet() override {
       ASSERT_FALSE(global);
       global = true;
     }
     void onUnset() override {
       ASSERT_TRUE(global);
       global = false;
     }
     bool hasCallback() override {
       return true;
     }
   };
   RequestContextScopeGuard g0;
   RequestContext::get()->setContextData(
       "test", std::make_unique<GlobalTestData>());
   {
     RequestContextScopeGuard g1;
     RequestContext::get()->setContextData(
         "test", std::make_unique<GlobalTestData>());
   }
 }
TEST_F (RequestContextTest , ShallowCopyBasic)
Definition at line 269 of file RequestContextTest.cpp.
References data_, EXPECT_EQ, and EXPECT_FALSE.
{
   ShallowCopyRequestContextScopeGuard g0;
   setData(123, "immutable");
   EXPECT_EQ(123, getData("immutable").data_);
   EXPECT_FALSE(hasData());
   {
     ShallowCopyRequestContextScopeGuard g1;
     EXPECT_EQ(123, getData("immutable").data_);
     setData(789);
     EXPECT_EQ(789, getData().data_);
   }
   EXPECT_FALSE(hasData());
   EXPECT_EQ(123, getData("immutable").data_);
   EXPECT_EQ(1, getData("immutable").set_);
   EXPECT_EQ(0, getData("immutable").unset_);
 }
TEST_F (RequestContextTest , ShallowCopyOverwrite)
Definition at line 288 of file RequestContextTest.cpp.
References data_, and EXPECT_EQ.
{
   RequestContextScopeGuard g0;
   setData(123);
   EXPECT_EQ(123, getData().data_);
   {
     ShallowCopyRequestContextScopeGuard g1(
         "test", std::make_unique<TestData>(789));
     EXPECT_EQ(789, getData().data_);
     EXPECT_EQ(1, getData().set_);
     EXPECT_EQ(0, getData().unset_);
   }
   EXPECT_EQ(123, getData().data_);
   EXPECT_EQ(2, getData().set_);
   EXPECT_EQ(1, getData().unset_);
 }
TEST_F (RequestContextTest , ShallowCopyDefaultContext)
Definition at line 304 of file RequestContextTest.cpp.
References data_, and EXPECT_EQ.
{
   // Don't set global scope guard
   setData(123);
   EXPECT_EQ(123, getData().data_);
   {
     ShallowCopyRequestContextScopeGuard g1(
         "test", std::make_unique<TestData>(789));
     EXPECT_EQ(789, getData().data_);
   }
   EXPECT_EQ(123, getData().data_);
   EXPECT_EQ(1, getData().set_);
   EXPECT_EQ(0, getData().unset_);
 }
TEST_F (RequestContextTest , ShallowCopyClear)
Definition at line 318 of file RequestContextTest.cpp.
References data_, and EXPECT_EQ.
{
   RequestContextScopeGuard g0;
   setData(123);
   EXPECT_EQ(123, getData().data_);
   {
     ShallowCopyRequestContextScopeGuard g1;
     EXPECT_EQ(123, getData().data_);
     clearData();
     setData(789);
     EXPECT_EQ(789, getData().data_);
   }
   EXPECT_EQ(123, getData().data_);
   EXPECT_EQ(2, getData().set_);
   EXPECT_EQ(1, getData().unset_);
 }
Variable Documentation
RequestToken testtoken("test")
Referenced by TEST_F().