proxygen: proxygen/wangle/wangle/deprecated/rx/test/RxBenchmark.cpp File Reference
RxBenchmark.cpp File Reference
#include <folly/Benchmark.h>
#include <wangle/deprecated/rx/Observer.h>
#include <wangle/deprecated/rx/Subject.h>
#include <gflags/gflags.h>
Functions
static std::unique_ptr< Observer< int > > makeObserver ()
void subscribeImpl (uint32_t iters, int N, bool countUnsubscribe)
void subscribeAndUnsubscribe (uint32_t iters, int N)
void subscribe (uint32_t iters, int N)
void observe (uint32_t iters, int N)
void inlineObserve (uint32_t iters, int N)
void notifySubscribers (uint32_t iters, int N)
void notifyInlineObservers (uint32_t iters, int N)
BENCHMARK_DRAW_LINE ()
int main (int argc, char **argv)
Function Documentation
BENCHMARK_DRAW_LINE ()
Referenced by notifyInlineObservers().
void inlineObserve (uint32_t iters, int N)
Definition at line 74 of file RxBenchmark.cpp.
References folly::BenchmarkSuspender::dismiss(), i, makeObserver(), wangle::Observable< T >::observe(), folly::BenchmarkSuspender::rehire(), and uint32_t.
Referenced by notifyInlineObservers().
{
   for (uint32_t iter = 0; iter < iters; iter++) {
     BenchmarkSuspender bs;
     Subject<int> subject;
     std::vector<Observer<int>*> observers;
     for (int i = 0; i < N; i++) {
       observers.push_back(makeObserver().release());
     }
     bs.dismiss();
     for (int i = 0; i < N; i++) {
       subject.observe(observers[i]);
     }
     bs.rehire();
     for (int i = 0; i < N; i++) {
       delete observers[i];
     }
   }
 }
int main (int argc, char ** argv)
Definition at line 151 of file RxBenchmark.cpp.
References argv, and folly::runBenchmarks().
{
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   folly::runBenchmarks();
   return 0;
 }
static std::unique_ptr<Observer<int> > makeObserver () static
Definition at line 25 of file RxBenchmark.cpp.
References wangle::Observer< T >::create().
Referenced by inlineObserve(), notifyInlineObservers(), notifySubscribers(), observe(), and subscribeImpl().
{
   return Observer<int>::create([&] (int) {});
 }
void notifyInlineObservers (uint32_t iters, int N)
Definition at line 112 of file RxBenchmark.cpp.
References BENCHMARK_DRAW_LINE(), BENCHMARK_PARAM, BENCHMARK_RELATIVE_PARAM, folly::BenchmarkSuspender::dismiss(), i, inlineObserve(), makeObserver(), notifySubscribers(), observe(), wangle::Observable< T >::observe(), wangle::Subject< T >::onNext(), folly::BenchmarkSuspender::rehire(), subscribe(), subscribeAndUnsubscribe(), and uint32_t.
{
   for (uint32_t iter = 0; iter < iters; iter++) {
     BenchmarkSuspender bs;
     Subject<int> subject;
     std::vector<Observer<int>*> observers;
     for (int i = 0; i < N; i++) {
       observers.push_back(makeObserver().release());
     }
     for (int i = 0; i < N; i++) {
       subject.observe(observers[i]);
     }
     bs.dismiss();
     subject.onNext(42);
     bs.rehire();
   }
 }
void notifySubscribers (uint32_t iters, int N)
Definition at line 93 of file RxBenchmark.cpp.
References folly::BenchmarkSuspender::dismiss(), i, makeObserver(), folly::gen::move, wangle::Subject< T >::onNext(), folly::BenchmarkSuspender::rehire(), wangle::Observable< T >::subscribe(), and uint32_t.
Referenced by notifyInlineObservers().
{
   for (uint32_t iter = 0; iter < iters; iter++) {
     BenchmarkSuspender bs;
     Subject<int> subject;
     std::vector<std::unique_ptr<Observer<int>>> observers;
     std::vector<Subscription<int>> subscriptions;
     subscriptions.reserve(N);
     for (int i = 0; i < N; i++) {
       observers.push_back(makeObserver());
     }
     for (int i = 0; i < N; i++) {
       subscriptions.push_back(subject.subscribe(std::move(observers[i])));
     }
     bs.dismiss();
     subject.onNext(42);
     bs.rehire();
   }
 }
void observe (uint32_t iters, int N)
Definition at line 58 of file RxBenchmark.cpp.
References folly::BenchmarkSuspender::dismiss(), i, makeObserver(), folly::gen::move, wangle::Observable< T >::observe(), folly::BenchmarkSuspender::rehire(), and uint32_t.
Referenced by notifyInlineObservers().
{
   for (uint32_t iter = 0; iter < iters; iter++) {
     BenchmarkSuspender bs;
     Subject<int> subject;
     std::vector<std::unique_ptr<Observer<int>>> observers;
     for (int i = 0; i < N; i++) {
       observers.push_back(makeObserver());
     }
     bs.dismiss();
     for (int i = 0; i < N; i++) {
       subject.observe(std::move(observers[i]));
     }
     bs.rehire();
   }
 }
void subscribe (uint32_t iters, int N)
Definition at line 54 of file RxBenchmark.cpp.
References subscribeImpl().
Referenced by notifyInlineObservers(), folly::observer::detail::ObserverCreatorContext< Observable, Traits >::subscribe(), TEST(), and TEST_F().
{
   subscribeImpl(iters, N, false);
 }
void subscribeAndUnsubscribe (uint32_t iters, int N)
Definition at line 50 of file RxBenchmark.cpp.
References subscribeImpl().
Referenced by notifyInlineObservers().
{
   subscribeImpl(iters, N, true);
 }
void subscribeImpl (uint32_t iters, int N, bool countUnsubscribe)
Definition at line 29 of file RxBenchmark.cpp.
References folly::BenchmarkSuspender::dismiss(), i, makeObserver(), folly::gen::move, folly::BenchmarkSuspender::rehire(), wangle::Observable< T >::subscribe(), and uint32_t.
Referenced by subscribe(), and subscribeAndUnsubscribe().
{
   for (uint32_t iter = 0; iter < iters; iter++) {
     BenchmarkSuspender bs;
     Subject<int> subject;
     std::vector<std::unique_ptr<Observer<int>>> observers;
     std::vector<Subscription<int>> subscriptions;
     subscriptions.reserve(N);
     for (int i = 0; i < N; i++) {
       observers.push_back(makeObserver());
     }
     bs.dismiss();
     for (int i = 0; i < N; i++) {
       subscriptions.push_back(subject.subscribe(std::move(observers[i])));
     }
     if (countUnsubscribe) {
       subscriptions.clear();
     }
     bs.rehire();
   }
 }