proxygen: proxygen/folly/folly/lang/test/SafeAssertTest.cpp File Reference
SafeAssertTest.cpp File Reference
#include <folly/lang/SafeAssert.h>
#include <glog/logging.h>
#include <folly/Benchmark.h>
#include <folly/portability/GTest.h>
Functions
void fail ()
void succeed ()
TEST (SafeAssert, AssertionFailure)
Function Documentation
void fail ()
Definition at line 27 of file SafeAssertTest.cpp.
References FOLLY_SAFE_CHECK.
Referenced by TEST(), folly::TEST(), TEST_F(), and folly::test::TEST_F().
{
   FOLLY_SAFE_CHECK(0 + 0, "hello");
 }
void succeed ()
Definition at line 32 of file SafeAssertTest.cpp.
References FOLLY_SAFE_CHECK.
Referenced by TEST().
                {
   FOLLY_SAFE_CHECK(1, "world");
 }
TEST (SafeAssert , AssertionFailure)
Definition at line 36 of file SafeAssertTest.cpp.
References fail(), and succeed().
{
   succeed();
   EXPECT_DEATH(fail(), "Assertion failure: 0 \\+ 0");
   EXPECT_DEATH(fail(), "Message: hello");
 }