proxygen: proxygen/folly/folly/synchronization/SanitizeThread.cpp File Reference
SanitizeThread.cpp File Reference
#include <folly/synchronization/SanitizeThread.h>
Namespaces
folly
—— Concurrent Priority Queue Implementation ——
folly::detail
Macros
#define FOLLY_SANITIZE_THREAD_CALL_HOOK(name, ...) name(__VA_ARGS__)
Functions
FOLLY_ATTR_WEAK void AnnotateRWLockCreate (const char *f, int l, const volatile void *addr)
FOLLY_ATTR_WEAK void AnnotateRWLockCreateStatic (const char *f, int l, const volatile void *addr)
FOLLY_ATTR_WEAK void AnnotateRWLockDestroy (const char *f, int l, const volatile void *addr)
FOLLY_ATTR_WEAK void AnnotateRWLockAcquired (const char *f, int l, const volatile void *addr, long w)
FOLLY_ATTR_WEAK void AnnotateRWLockReleased (const char *f, int l, const volatile void *addr, long w)
FOLLY_ATTR_WEAK void AnnotateBenignRaceSized (const char *f, int l, const volatile void *addr, long size, const char *desc)
void folly::detail::annotate_rwlock_create_impl (void const volatile *const addr, char const *const f, int const l)
void folly::detail::annotate_rwlock_create_static_impl (void const volatile *const addr, char const *const f, int const l)
void folly::detail::annotate_rwlock_destroy_impl (void const volatile *const addr, char const *const f, int const l)
void folly::detail::annotate_rwlock_acquired_impl (void const volatile *const addr, annotate_rwlock_level const w, char const *const f, int const l)
void folly::detail::annotate_rwlock_try_acquired_impl (void const volatile *const addr, annotate_rwlock_level const w, bool const result, char const *const f, int const l)
void folly::detail::annotate_rwlock_released_impl (void const volatile *const addr, annotate_rwlock_level const w, char const *const f, int const l)
void folly::detail::annotate_benign_race_sized_impl (const volatile void *addr, long size, const char *desc, const char *f, int l)
Macro Definition Documentation
#define FOLLY_SANITIZE_THREAD_CALL_HOOK (name, ...) name(__VA_ARGS__)
Definition at line 52 of file SanitizeThread.cpp.
Referenced by folly::detail::annotate_benign_race_sized_impl(), folly::detail::annotate_rwlock_acquired_impl(), folly::detail::annotate_rwlock_create_impl(), folly::detail::annotate_rwlock_create_static_impl(), folly::detail::annotate_rwlock_destroy_impl(), and folly::detail::annotate_rwlock_released_impl().
Function Documentation
FOLLY_ATTR_WEAK void AnnotateBenignRaceSized (const char * f, int l, const volatile void * addr, long size, const char * desc)
Referenced by folly::detail::annotate_benign_race_sized_impl().
FOLLY_ATTR_WEAK void AnnotateRWLockAcquired (const char * f, int l, const volatile void * addr, long w)
Referenced by folly::detail::annotate_rwlock_acquired_impl().
FOLLY_ATTR_WEAK void AnnotateRWLockCreate (const char * f, int l, const volatile void * addr)
Referenced by folly::detail::annotate_rwlock_create_impl().
FOLLY_ATTR_WEAK void AnnotateRWLockCreateStatic (const char * f, int l, const volatile void * addr)
Referenced by folly::detail::annotate_rwlock_create_static_impl().
FOLLY_ATTR_WEAK void AnnotateRWLockDestroy (const char * f, int l, const volatile void * addr)
Referenced by folly::detail::annotate_rwlock_destroy_impl().
FOLLY_ATTR_WEAK void AnnotateRWLockReleased (const char * f, int l, const volatile void * addr, long w)
Referenced by folly::detail::annotate_rwlock_released_impl().