proxygen: proxygen/folly/folly/io/async/test/ScopedEventBaseThreadTest.cpp File Reference
ScopedEventBaseThreadTest.cpp File Reference
#include <folly/io/async/ScopedEventBaseThread.h>
#include <chrono>
#include <string>
#include <folly/Optional.h>
#include <folly/io/async/EventBaseManager.h>
#include <folly/portability/GTest.h>
#include <folly/synchronization/Baton.h>
#include <folly/system/ThreadName.h>
Classes
class ScopedEventBaseThreadTest
Functions
TEST_F (ScopedEventBaseThreadTest, example)
TEST_F (ScopedEventBaseThreadTest, named_example)
TEST_F (ScopedEventBaseThreadTest, default_manager)
TEST_F (ScopedEventBaseThreadTest, custom_manager)
TEST_F (ScopedEventBaseThreadTest, eb_dtor_in_io_thread)
Function Documentation
TEST_F (ScopedEventBaseThreadTest , example)
Definition at line 34 of file ScopedEventBaseThreadTest.cpp.
References ASSERT_TRUE, folly::ScopedEventBaseThread::getEventBase(), folly::Baton< MayBlock, Atom >::post(), folly::EventBase::runInEventBaseThread(), and folly::Baton< MayBlock, Atom >::try_wait_for().
{
   ScopedEventBaseThread sebt;
   Baton<> done;
   sebt.getEventBase()->runInEventBaseThread([&] { done.post(); });
   ASSERT_TRUE(done.try_wait_for(seconds(1)));
 }
TEST_F (ScopedEventBaseThreadTest , named_example)
Definition at line 42 of file ScopedEventBaseThreadTest.cpp.
References ASSERT_EQ, ASSERT_TRUE, folly::getCurrentThreadName(), folly::ScopedEventBaseThread::getEventBase(), folly::Baton< MayBlock, Atom >::post(), folly::EventBase::runInEventBaseThread(), folly::Baton< MayBlock, Atom >::try_wait_for(), and folly::Optional< Value >::value().
{
   static constexpr StringPiece kThreadName{"named_example"};
   Optional<std::string> createdThreadName;
   Baton<> done;
   ScopedEventBaseThread sebt{kThreadName};
   sebt.getEventBase()->runInEventBaseThread([&] {
     createdThreadName = folly::getCurrentThreadName();
     done.post();
   });
   ASSERT_TRUE(done.try_wait_for(seconds(1)));
   if (createdThreadName) {
     ASSERT_EQ(kThreadName.toString(), createdThreadName.value());
   }
 }
TEST_F (ScopedEventBaseThreadTest , default_manager)
Definition at line 60 of file ScopedEventBaseThreadTest.cpp.
References EXPECT_EQ, folly::pushmi::operators::get, folly::ScopedEventBaseThread::getEventBase(), and folly::EventBase::runInEventBaseThreadAndWait().
{
   auto ebm = EventBaseManager::get();
   ScopedEventBaseThread sebt;
   auto sebt_eb = sebt.getEventBase();
   auto ebm_eb = static_cast<EventBase*>(nullptr);
   sebt_eb->runInEventBaseThreadAndWait([&] { ebm_eb = ebm->getEventBase(); });
   EXPECT_EQ(uintptr_t(sebt_eb), uintptr_t(ebm_eb));
 }
TEST_F (ScopedEventBaseThreadTest , custom_manager)
Definition at line 69 of file ScopedEventBaseThreadTest.cpp.
References EXPECT_EQ, folly::ScopedEventBaseThread::getEventBase(), folly::EventBaseManager::getEventBase(), and folly::EventBase::runInEventBaseThreadAndWait().
{
   EventBaseManager ebm;
   ScopedEventBaseThread sebt(&ebm);
   auto sebt_eb = sebt.getEventBase();
   auto ebm_eb = static_cast<EventBase*>(nullptr);
   sebt_eb->runInEventBaseThreadAndWait([&] { ebm_eb = ebm.getEventBase(); });
   EXPECT_EQ(uintptr_t(sebt_eb), uintptr_t(ebm_eb));
 }
TEST_F (ScopedEventBaseThreadTest , eb_dtor_in_io_thread)
Definition at line 78 of file ScopedEventBaseThreadTest.cpp.
References folly::Optional< Value >::clear(), folly::Optional< Value >::emplace(), EXPECT_EQ, EXPECT_NE, folly::ScopedEventBaseThread::getEventBase(), folly::ScopedEventBaseThread::getThreadId(), and folly::EventBase::runOnDestruction().
{
   Optional<ScopedEventBaseThread> sebt;
   sebt.emplace();
   auto const io_thread_id = sebt->getThreadId();
   EXPECT_NE(this_thread::get_id(), io_thread_id) << "sanity";
   auto const eb = sebt->getEventBase();
   thread::id eb_dtor_thread_id;
   eb->runOnDestruction(new EventBase::FunctionLoopCallback(
       [&] { eb_dtor_thread_id = this_thread::get_id(); }));
   sebt.clear();
   EXPECT_EQ(io_thread_id, eb_dtor_thread_id);
 }