proxygen: proxygen/folly/folly/futures/test/SelfDestructTest.cpp File Reference
SelfDestructTest.cpp File Reference
#include <folly/executors/InlineExecutor.h>
#include <folly/futures/Future.h>
#include <folly/portability/GTest.h>
Classes
class ThrowingExecutorError
class ThrowingExecutor
Functions
TEST (SelfDestruct, then)
TEST (SelfDestruct, ensure)
TEST (SelfDestruct, throwingExecutor)
TEST (SelfDestruct, throwingInlineExecutor)
Function Documentation
TEST (SelfDestruct , then)
Definition at line 23 of file SelfDestructTest.cpp.
References EXPECT_EQ, folly::Promise< T >::getFuture(), and folly::gen::move.
{
   auto* p = new Promise<int>();
   auto future = p->getFuture().then([p](int x) {
     delete p;
     return x + 1;
   });
   p->setValue(123);
   EXPECT_EQ(124, std::move(future).get());
 }
TEST (SelfDestruct , ensure)
Definition at line 33 of file SelfDestructTest.cpp.
References EXPECT_EQ, folly::Promise< T >::getFuture(), and folly::gen::move.
{
   auto* p = new Promise<int>();
   auto future = p->getFuture().ensure([p] { delete p; });
   p->setValue(123);
   EXPECT_EQ(123, std::move(future).get());
 }
TEST (SelfDestruct , throwingExecutor)
Definition at line 52 of file SelfDestructTest.cpp.
References folly::pushmi::executor, EXPECT_EQ, folly::Promise< T >::getFuture(), and folly::gen::move.
{
   ThrowingExecutor executor;
   auto* p = new Promise<int>();
   auto future =
       p->getFuture().via(&executor).onError([p](ThrowingExecutorError const&) {
         delete p;
         return 456;
       });
   p->setValue(123);
   EXPECT_EQ(456, std::move(future).get());
 }
TEST (SelfDestruct , throwingInlineExecutor)
Definition at line 64 of file SelfDestructTest.cpp.
References folly::pushmi::executor, EXPECT_EQ, folly::Promise< T >::getFuture(), and folly::gen::move.
{
   InlineExecutor executor;
   auto* p = new Promise<int>();
   auto future = p->getFuture()
                     .via(&executor)
                     .thenValue([p](auto &&) -> int {
                       delete p;
                       throw ThrowingExecutorError("callback throws");
                     })
                     .onError([](ThrowingExecutorError const&) { return 456; });
   p->setValue(123);
   EXPECT_EQ(456, std::move(future).get());
 }