proxygen: proxygen/folly/folly/futures/test/SemiFutureTest.cpp File Reference
SemiFutureTest.cpp File Reference
#include <folly/Executor.h>
#include <folly/Memory.h>
#include <folly/Unit.h>
#include <folly/dynamic.h>
#include <folly/executors/ManualExecutor.h>
#include <folly/futures/Future.h>
#include <folly/io/async/EventBase.h>
#include <folly/portability/GTest.h>
#include <folly/synchronization/Baton.h>
#include <algorithm>
#include <atomic>
#include <future>
#include <memory>
#include <numeric>
#include <string>
#include <thread>
#include <type_traits>
Macros
#define EXPECT_TYPE(x, T) EXPECT_TRUE((std::is_same<decltype(x), T>::value))
#define DOIT(CREATION_EXPR)
#define DOIT(CREATION_EXPR)
#define DOIT(STMT)
#define DOIT(STMT)
#define DOIT(STMT)
#define DOIT(CTOR, STMT)
#define EXPECT_FLAG()
#define EXPECT_NO_FLAG()
Typedefs
typedef FutureException eggs_t
Functions
TEST (SemiFuture, makeEmpty)
TEST (SemiFuture, futureDefaultCtor)
TEST (SemiFuture, makeSemiFutureWithUnit)
TEST (SemiFuture, ctorPostconditionValid)
TEST (SemiFuture, ctorPostconditionInvalid)
TEST (SemiFuture, lacksPreconditionValid)
TEST (SemiFuture, hasPreconditionValid)
TEST (SemiFuture, hasPostconditionValid)
TEST (SemiFuture, hasPostconditionInvalid)
TEST (SemiFuture, special)
TEST (SemiFuture, value)
TEST (SemiFuture, hasException)
TEST (SemiFuture, hasValue)
TEST (SemiFuture, makeSemiFuture)
TEST (SemiFuture, Constructor)
TEST (SemiFuture, ImplicitConstructor)
TEST (SemiFuture, InPlaceConstructor)
TEST (SemiFuture, makeSemiFutureNoThrow)
TEST (SemiFuture, ViaThrowOnNull)
TEST (SemiFuture, ConstructSemiFutureFromEmptyFuture)
TEST (SemiFuture, ConstructSemiFutureFromFutureDefaultCtor)
TEST (SemiFuture, MakeSemiFutureFromFutureWithUnit)
TEST (SemiFuture, MakeSemiFutureFromFutureWithValue)
TEST (SemiFuture, MakeSemiFutureFromReadyFuture)
TEST (SemiFuture, MakeSemiFutureFromNotReadyFuture)
TEST (SemiFuture, MakeFutureFromSemiFuture)
TEST (SemiFuture, MakeFutureFromSemiFutureReturnFuture)
TEST (SemiFuture, MakeFutureFromSemiFutureReturnSemiFuture)
TEST (SemiFuture, MakeFutureFromSemiFutureLValue)
TEST (SemiFuture, SimpleGet)
TEST (SemiFuture, SimpleGetTry)
TEST (SemiFuture, SimpleTimedGet)
TEST (SemiFuture, SimpleTimedGetViaFromSemiFuture)
TEST (SemiFuture, SimpleTimedGetTry)
TEST (SemiFuture, SimpleTimedGetTryViaFromSemiFuture)
TEST (SemiFuture, SimpleValue)
TEST (SemiFuture, SimpleValueThrow)
TEST (SemiFuture, SimpleResult)
TEST (SemiFuture, SimpleResultThrow)
TEST (SemiFuture, SimpleDefer)
TEST (SemiFuture, DeferWithDelayedSetValue)
TEST (SemiFuture, DeferWithViaAndDelayedSetValue)
TEST (SemiFuture, DeferWithGetTimedGet)
TEST (SemiFuture, DeferWithVia)
TEST (SemiFuture, ChainingDefertoThen)
TEST (SemiFuture, SimpleDeferWithValue)
TEST (SemiFuture, SimpleDeferWithValueFunctionReference)
TEST (SemiFuture, ChainingDefertoThenWithValue)
TEST (SemiFuture, MakeSemiFutureFromFutureWithTry)
TEST (SemiFuture, DeferWithinContinuation)
TEST (SemiFuture, onError)
TEST (SemiFuture, makePromiseContract)
TEST (SemiFuture, invokeCallbackWithOriginalCVRef)
TEST (SemiFuture, semiFutureWithinCtxCleanedUpWhenTaskFinishedInTime)
TEST (SemiFuture, semiFutureWithinNoValueReferenceWhenTimeOut)
TEST (SemiFuture, collectAllSemiFutureDeferredWork)
TEST (SemiFuture, DeferWithNestedSemiFuture)
Variables
static eggs_t eggs ("eggs")
Macro Definition Documentation
#define DOIT (CREATION_EXPR)
Value:
do {                         \
    auto f1 = (CREATION_EXPR); \
    EXPECT_TRUE(f1.valid());   \
    auto f2 = std::move(f1);   \
    EXPECT_FALSE(f1.valid());  \
    EXPECT_TRUE(f2.valid());   \
  } while (false)
Referenced by TEST().
#define DOIT (CREATION_EXPR)
Value:
do {                         \
    auto f1 = (CREATION_EXPR); \
    EXPECT_FALSE(f1.valid());  \
    auto f2 = std::move(f1);   \
    EXPECT_FALSE(f1.valid());  \
    EXPECT_FALSE(f2.valid());  \
  } while (false)
#define DOIT (STMT)
Value:
do {                     \
    auto f = makeValid();  \
    { STMT; }              \
    copy(std::move(f));    \
    EXPECT_NO_THROW(STMT); \
  } while (false)
#define DOIT (STMT)
Value:
do {                                 \
    auto f = makeValid();              \
    EXPECT_NO_THROW(STMT);             \
    copy(std::move(f));                \
    EXPECT_THROW(STMT, FutureInvalid); \
  } while (false)
#define DOIT (STMT)
Value:
do {                      \
    auto f = makeValid();   \
    EXPECT_NO_THROW(STMT);  \
    EXPECT_TRUE(f.valid()); \
  } while (false)
#define DOIT (CTOR, STMT)
Value:
do {                       \
    auto f = (CTOR);         \
    EXPECT_NO_THROW(STMT);   \
    EXPECT_FALSE(f.valid()); \
  } while (false)
#define EXPECT_FLAG ()
Value:
do {                    \
    EXPECT_TRUE(theFlag); \
    theFlag = false;      \
  } while (0);
Referenced by TEST().
#define EXPECT_NO_FLAG ()
Value:
do {                     \
    EXPECT_FALSE(theFlag); \
    theFlag = false;       \
  } while (0);
Referenced by TEST().
#define EXPECT_TYPE (x, T) EXPECT_TRUE((std::is_same<decltype(x), T>::value))
Definition at line 37 of file SemiFutureTest.cpp.
Referenced by TEST().
Typedef Documentation
typedef FutureException eggs_t
Definition at line 39 of file SemiFutureTest.cpp.
Function Documentation
TEST (SemiFuture , makeEmpty)
Definition at line 44 of file SemiFutureTest.cpp.
References EXPECT_THROW, f, and folly::SemiFuture< T >::makeEmpty().
{
   auto f = SemiFuture<int>::makeEmpty();
   EXPECT_THROW(f.isReady(), FutureInvalid);
 }
TEST (SemiFuture , futureDefaultCtor)
Definition at line 49 of file SemiFutureTest.cpp.
{
   SemiFuture<Unit>();
 }
TEST (SemiFuture , makeSemiFutureWithUnit)
Definition at line 53 of file SemiFutureTest.cpp.
References count, EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, folly::SemiFuture< T >::makeEmpty(), and folly::makeSemiFutureWith().
{
   int count = 0;
   SemiFuture<Unit> fu = makeSemiFutureWith([&] { count++; });
   EXPECT_EQ(1, count);
 }
TEST (SemiFuture , ctorPostconditionValid)
Definition at line 72 of file SemiFutureTest.cpp.
References DOIT, and folly::makeSemiFuture().
{
   // Ctors/factories that promise valid -- postcondition: valid()
 #define DOIT(CREATION_EXPR)    \
   do {                         \
     auto f1 = (CREATION_EXPR); \
     EXPECT_TRUE(f1.valid());   \
     auto f2 = std::move(f1);   \
     EXPECT_FALSE(f1.valid());  \
     EXPECT_TRUE(f2.valid());   \
   } while (false)
   auto const except = std::logic_error("foo");
   auto const ewrap = folly::exception_wrapper(except);
   DOIT(makeValid());
   DOIT(SemiFuture<int>(42));
   DOIT(SemiFuture<int>{42});
   DOIT(SemiFuture<Unit>());
   DOIT(SemiFuture<Unit>{});
   DOIT(makeSemiFuture());
   DOIT(makeSemiFuture(Unit{}));
   DOIT(makeSemiFuture<Unit>(Unit{}));
   DOIT(makeSemiFuture(42));
   DOIT(makeSemiFuture<int>(42));
   DOIT(makeSemiFuture<int>(except));
   DOIT(makeSemiFuture<int>(ewrap));
   DOIT(makeSemiFuture(Try<int>(42)));
   DOIT(makeSemiFuture<int>(Try<int>(42)));
   DOIT(makeSemiFuture<int>(Try<int>(ewrap)));
 #undef DOIT
 }
TEST (SemiFuture , ctorPostconditionInvalid)
Definition at line 106 of file SemiFutureTest.cpp.
References DOIT.
{
   // Ctors/factories that promise invalid -- postcondition: !valid()
 #define DOIT(CREATION_EXPR)    \
   do {                         \
     auto f1 = (CREATION_EXPR); \
     EXPECT_FALSE(f1.valid());  \
     auto f2 = std::move(f1);   \
     EXPECT_FALSE(f1.valid());  \
     EXPECT_FALSE(f2.valid());  \
   } while (false)
   DOIT(makeInvalid());
   DOIT(SemiFuture<int>::makeEmpty());
 #undef DOIT
 }
TEST (SemiFuture , lacksPreconditionValid)
Definition at line 124 of file SemiFutureTest.cpp.
References folly::copy(), DOIT, f, and folly::gen::move.
{
   // Ops that don't throw FutureInvalid if !valid() --
   // without precondition: valid()
 #define DOIT(STMT)         \
   do {                     \
     auto f = makeValid();  \
     { STMT; }              \
     copy(std::move(f));    \
     EXPECT_NO_THROW(STMT); \
   } while (false)
   // .valid() itself
   DOIT(f.valid());
   // move-ctor - move-copy to local, copy(), pass-by-move-value
   DOIT(auto other = std::move(f));
   DOIT(copy(std::move(f)));
   DOIT(([](auto) {})(std::move(f)));
   // move-assignment into either {valid | invalid}
   DOIT({
     auto other = makeValid();
     other = std::move(f);
   });
   DOIT({
     auto other = makeInvalid();
     other = std::move(f);
   });
 #undef DOIT
 }
TEST (SemiFuture , hasPreconditionValid)
Definition at line 157 of file SemiFutureTest.cpp.
References DOIT, f, and folly::gen::move.
{
   // Ops that require validity; precondition: valid();
   // throw FutureInvalid if !valid()
 #define DOIT(STMT)                     \
   do {                                 \
     auto f = makeValid();              \
     EXPECT_NO_THROW(STMT);             \
     copy(std::move(f));                \
     EXPECT_THROW(STMT, FutureInvalid); \
   } while (false)
   DOIT(f.isReady());
   DOIT(f.result());
   DOIT(std::move(f).getTry());
   DOIT(f.hasValue());
   DOIT(f.hasException());
   DOIT(f.value());
 #undef DOIT
 }
TEST (SemiFuture , hasPostconditionValid)
Definition at line 179 of file SemiFutureTest.cpp.
References DOIT, f, and folly::gen::move.
{
   // Ops that preserve validity -- postcondition: valid()
 #define DOIT(STMT)          \
   do {                      \
     auto f = makeValid();   \
     EXPECT_NO_THROW(STMT);  \
     EXPECT_TRUE(f.valid()); \
   } while (false)
   auto const swallow = [](auto) {};
   DOIT(swallow(f.valid())); // f.valid() itself preserves validity
   DOIT(swallow(f.isReady()));
   DOIT(swallow(f.hasValue()));
   DOIT(swallow(f.hasException()));
   DOIT(swallow(f.value()));
   DOIT(swallow(f.poll()));
   DOIT(f.raise(std::logic_error("foo")));
   DOIT(f.cancel());
   DOIT(f.wait());
   DOIT(std::move(f.wait()));
 #undef DOIT
 }
TEST (SemiFuture , hasPostconditionInvalid)
Definition at line 205 of file SemiFutureTest.cpp.
References DOIT, f, folly::gen::move, and folly::detail::distributed_mutex::wait().
{
   // Ops that consume *this -- postcondition: !valid()
 #define DOIT(CTOR, STMT)     \
   do {                       \
     auto f = (CTOR);         \
     EXPECT_NO_THROW(STMT);   \
     EXPECT_FALSE(f.valid()); \
   } while (false)
   // move-ctor of {valid|invalid}
   DOIT(makeValid(), { auto other{std::move(f)}; });
   DOIT(makeInvalid(), { auto other{std::move(f)}; });
   // move-assignment of {valid|invalid} into {valid|invalid}
   DOIT(makeValid(), {
     auto other = makeValid();
     other = std::move(f);
   });
   DOIT(makeValid(), {
     auto other = makeInvalid();
     other = std::move(f);
   });
   DOIT(makeInvalid(), {
     auto other = makeValid();
     other = std::move(f);
   });
   DOIT(makeInvalid(), {
     auto other = makeInvalid();
     other = std::move(f);
   });
   // pass-by-value of {valid|invalid}
   DOIT(makeValid(), {
     auto const byval = [](auto) {};
     byval(std::move(f));
   });
   DOIT(makeInvalid(), {
     auto const byval = [](auto) {};
     byval(std::move(f));
   });
   // other consuming ops
   auto const swallow = [](auto) {};
   DOIT(makeValid(), swallow(std::move(f).get()));
   DOIT(makeValid(), swallow(std::move(f).getTry()));
   DOIT(makeValid(), swallow(std::move(f).wait()));
   DOIT(makeValid(), swallow(std::move(f.wait())));
 #undef DOIT
 }
TEST (SemiFuture , special)
Definition at line 266 of file SemiFutureTest.cpp.
References EXPECT_FALSE, EXPECT_TRUE, and folly::value().
{
   EXPECT_FALSE(std::is_copy_constructible<SemiFuture<int>>::value);
   EXPECT_FALSE(std::is_copy_assignable<SemiFuture<int>>::value);
   EXPECT_TRUE(std::is_move_constructible<SemiFuture<int>>::value);
   EXPECT_TRUE(std::is_move_assignable<SemiFuture<int>>::value);
 }
TEST (SemiFuture , value)
Definition at line 273 of file SemiFutureTest.cpp.
References eggs, EXPECT_EQ, EXPECT_THROW, EXPECT_TYPE, f, folly::makeSemiFuture(), folly::gen::move, and folly::value().
{
   auto f = makeSemiFuture(std::make_unique<int>(42));
   auto up = std::move(f.value());
   EXPECT_EQ(42, *up);
   EXPECT_THROW(makeSemiFuture<int>(eggs).value(), eggs_t);
   EXPECT_TYPE(std::declval<SemiFuture<int>&>().value(), int&);
   EXPECT_TYPE(std::declval<SemiFuture<int> const&>().value(), int const&);
   EXPECT_TYPE(std::declval<SemiFuture<int>&&>().value(), int&&);
   EXPECT_TYPE(std::declval<SemiFuture<int> const&&>().value(), int const&&);
 }
TEST (SemiFuture , hasException)
Definition at line 286 of file SemiFutureTest.cpp.
References eggs, EXPECT_FALSE, EXPECT_TRUE, and folly::makeSemiFuture().
{
   EXPECT_TRUE(makeSemiFuture<int>(eggs).getTry().hasException());
   EXPECT_FALSE(makeSemiFuture(42).getTry().hasException());
 }
TEST (SemiFuture , hasValue)
Definition at line 291 of file SemiFutureTest.cpp.
References eggs, EXPECT_FALSE, EXPECT_TRUE, and folly::makeSemiFuture().
{
   EXPECT_TRUE(makeSemiFuture(42).getTry().hasValue());
   EXPECT_FALSE(makeSemiFuture<int>(eggs).getTry().hasValue());
 }
TEST (SemiFuture , makeSemiFuture)
Definition at line 296 of file SemiFutureTest.cpp.
References eggs, EXPECT_EQ, EXPECT_NO_THROW, EXPECT_THROW, EXPECT_TYPE, fun(), folly::makeSemiFuture(), folly::makeSemiFutureWith(), and folly::value().
{
   EXPECT_TYPE(makeSemiFuture(42), SemiFuture<int>);
   EXPECT_EQ(42, makeSemiFuture(42).value());
   EXPECT_TYPE(makeSemiFuture<float>(42), SemiFuture<float>);
   EXPECT_EQ(42, makeSemiFuture<float>(42).value());
   auto fun = [] { return 42; };
   EXPECT_TYPE(makeSemiFutureWith(fun), SemiFuture<int>);
   EXPECT_EQ(42, makeSemiFutureWith(fun).value());
   auto funf = [] { return makeSemiFuture<int>(43); };
   EXPECT_TYPE(makeSemiFutureWith(funf), SemiFuture<int>);
   EXPECT_EQ(43, makeSemiFutureWith(funf).value());
   auto failfun = []() -> int { throw eggs; };
   EXPECT_TYPE(makeSemiFutureWith(failfun), SemiFuture<int>);
   EXPECT_NO_THROW(makeSemiFutureWith(failfun));
   EXPECT_THROW(makeSemiFutureWith(failfun).value(), eggs_t);
   auto failfunf = []() -> SemiFuture<int> { throw eggs; };
   EXPECT_TYPE(makeSemiFutureWith(failfunf), SemiFuture<int>);
   EXPECT_NO_THROW(makeSemiFutureWith(failfunf));
   EXPECT_THROW(makeSemiFutureWith(failfunf).value(), eggs_t);
   auto futurefun = [] { return makeFuture<int>(44); };
   EXPECT_TYPE(makeSemiFutureWith(futurefun), SemiFuture<int>);
   EXPECT_EQ(44, makeSemiFutureWith(futurefun).value());
   EXPECT_TYPE(makeSemiFuture(), SemiFuture<Unit>);
 }
TEST (SemiFuture , Constructor)
Definition at line 328 of file SemiFutureTest.cpp.
References EXPECT_EQ, EXPECT_NO_THROW, and folly::futures::detail::FutureBase< T >::value().
{
   auto f1 = []() -> SemiFuture<int> { return SemiFuture<int>(3); }();
   EXPECT_EQ(f1.value(), 3);
   auto f2 = []() -> SemiFuture<Unit> { return SemiFuture<Unit>(); }();
   EXPECT_NO_THROW(f2.value());
 }
TEST (SemiFuture , ImplicitConstructor)
Definition at line 335 of file SemiFutureTest.cpp.
References EXPECT_EQ.
{
   auto f1 = []() -> SemiFuture<int> { return 3; }();
   EXPECT_EQ(f1.value(), 3);
 }
TEST (SemiFuture , InPlaceConstructor)
Definition at line 340 of file SemiFutureTest.cpp.
References EXPECT_EQ, f, and folly::in_place().
{
   auto f = SemiFuture<std::pair<int, double>>(in_place, 5, 3.2);
   EXPECT_EQ(5, f.value().first);
 }
TEST (SemiFuture , makeSemiFutureNoThrow)
Definition at line 345 of file SemiFutureTest.cpp.
References folly::makeSemiFuture().
{
   makeSemiFuture().value();
 }
TEST (SemiFuture , ViaThrowOnNull)
Definition at line 349 of file SemiFutureTest.cpp.
References EXPECT_THROW, folly::makeSemiFuture(), and folly::via().
{
   EXPECT_THROW(makeSemiFuture().via(nullptr), FutureNoExecutor);
 }
TEST (SemiFuture , ConstructSemiFutureFromEmptyFuture)
Definition at line 353 of file SemiFutureTest.cpp.
References EXPECT_THROW, f, and folly::Future< T >::makeEmpty().
{
   auto f = SemiFuture<int>{Future<int>::makeEmpty()};
   EXPECT_THROW(f.isReady(), FutureInvalid);
 }
TEST (SemiFuture , ConstructSemiFutureFromFutureDefaultCtor)
Definition at line 358 of file SemiFutureTest.cpp.
{
   SemiFuture<Unit>(Future<Unit>{});
 }
TEST (SemiFuture , MakeSemiFutureFromFutureWithUnit)
Definition at line 362 of file SemiFutureTest.cpp.
References count, EXPECT_EQ, and folly::makeFutureWith().
{
   int count = 0;
   SemiFuture<Unit> fu = SemiFuture<Unit>{makeFutureWith([&] { count++; })};
   EXPECT_EQ(1, count);
 }
TEST (SemiFuture , MakeSemiFutureFromFutureWithValue)
Definition at line 368 of file SemiFutureTest.cpp.
References EXPECT_EQ, f, folly::makeFuture(), and folly::gen::move.
{
   auto f =
       SemiFuture<std::unique_ptr<int>>{makeFuture(std::make_unique<int>(42))};
   auto up = std::move(f.value());
   EXPECT_EQ(42, *up);
 }
TEST (SemiFuture , MakeSemiFutureFromReadyFuture)
Definition at line 375 of file SemiFutureTest.cpp.
References EXPECT_FALSE, EXPECT_TRUE, f, folly::Promise< T >::getSemiFuture(), and folly::Promise< T >::setValue().
{
   Promise<int> p;
   auto f = p.getSemiFuture();
   EXPECT_FALSE(f.isReady());
   p.setValue(42);
   EXPECT_TRUE(f.isReady());
 }
TEST (SemiFuture , MakeSemiFutureFromNotReadyFuture)
Definition at line 383 of file SemiFutureTest.cpp.
References EXPECT_THROW, f, and folly::Promise< T >::getSemiFuture().
{
   Promise<int> p;
   auto f = p.getSemiFuture();
   EXPECT_THROW(f.value(), eggs_t);
 }
TEST (SemiFuture , MakeFutureFromSemiFuture)
Definition at line 389 of file SemiFutureTest.cpp.
References ASSERT_EQ, EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, f, folly::Promise< T >::getSemiFuture(), folly::EventBase::loopOnce(), folly::gen::move, folly::Promise< T >::setValue(), and folly::value().
{
   folly::EventBase e;
   Promise<int> p;
   std::atomic<int> result{0};
   auto f = p.getSemiFuture();
   auto future = std::move(f).via(&e).then([&](int value) {
     result = value;
     return value;
   });
   e.loopOnce();
   EXPECT_EQ(result, 0);
   EXPECT_FALSE(future.isReady());
   p.setValue(42);
   e.loopOnce();
   EXPECT_TRUE(future.isReady());
   ASSERT_EQ(future.value(), 42);
   ASSERT_EQ(result, 42);
 }
TEST (SemiFuture , MakeFutureFromSemiFutureReturnFuture)
Definition at line 408 of file SemiFutureTest.cpp.
References ASSERT_EQ, EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, f, folly::Promise< T >::getSemiFuture(), folly::EventBase::loopOnce(), folly::makeFuture(), folly::gen::move, folly::Promise< T >::setValue(), and folly::value().
{
   folly::EventBase e;
   Promise<int> p;
   int result{0};
   auto f = p.getSemiFuture();
   auto future = std::move(f).via(&e).then([&](int value) {
     result = value;
     return folly::makeFuture(std::move(value));
   });
   e.loopOnce();
   EXPECT_EQ(result, 0);
   EXPECT_FALSE(future.isReady());
   p.setValue(42);
   e.loopOnce();
   EXPECT_TRUE(future.isReady());
   ASSERT_EQ(future.value(), 42);
   ASSERT_EQ(result, 42);
 }
TEST (SemiFuture , MakeFutureFromSemiFutureReturnSemiFuture)
Definition at line 427 of file SemiFutureTest.cpp.
References ASSERT_EQ, EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, f, folly::Promise< T >::getSemiFuture(), folly::EventBase::loopOnce(), folly::makeSemiFuture(), folly::gen::move, folly::Promise< T >::setValue(), and folly::value().
{
   folly::EventBase e;
   Promise<int> p;
   int result{0};
   auto f = p.getSemiFuture();
   auto future = std::move(f)
                     .via(&e)
                     .then([&](int value) {
                       result = value;
                       return folly::makeSemiFuture(std::move(value));
                     })
                     .then([&](int value) {
                       return folly::makeSemiFuture(std::move(value));
                     });
   e.loopOnce();
   EXPECT_EQ(result, 0);
   EXPECT_FALSE(future.isReady());
   p.setValue(42);
   e.loopOnce();
   e.loopOnce();
   EXPECT_TRUE(future.isReady());
   ASSERT_EQ(future.value(), 42);
   ASSERT_EQ(result, 42);
 }
TEST (SemiFuture , MakeFutureFromSemiFutureLValue)
Definition at line 452 of file SemiFutureTest.cpp.
References ASSERT_EQ, EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, f, folly::Promise< T >::getSemiFuture(), folly::EventBase::loopOnce(), folly::gen::move, folly::Promise< T >::setValue(), and folly::value().
{
   folly::EventBase e;
   Promise<int> p;
   std::atomic<int> result{0};
   auto f = p.getSemiFuture();
   auto future = std::move(f).via(&e).then([&](int value) {
     result = value;
     return value;
   });
   e.loopOnce();
   EXPECT_EQ(result, 0);
   EXPECT_FALSE(future.isReady());
   p.setValue(42);
   e.loopOnce();
   EXPECT_TRUE(future.isReady());
   ASSERT_EQ(future.value(), 42);
   ASSERT_EQ(result, 42);
 }
TEST (SemiFuture , SimpleGet)
Definition at line 471 of file SemiFutureTest.cpp.
References ASSERT_EQ, folly::Promise< T >::getSemiFuture(), folly::gen::move, and folly::Promise< T >::setValue().
{
   EventBase e2;
   Promise<int> p;
   auto sf = p.getSemiFuture();
   p.setValue(3);
   auto v = std::move(sf).get();
   ASSERT_EQ(v, 3);
 }
TEST (SemiFuture , SimpleGetTry)
Definition at line 480 of file SemiFutureTest.cpp.
References ASSERT_EQ, folly::Promise< T >::getSemiFuture(), folly::gen::move, and folly::Promise< T >::setValue().
{
   EventBase e2;
   Promise<int> p;
   auto sf = p.getSemiFuture();
   p.setValue(3);
   auto v = std::move(sf).getTry();
   ASSERT_EQ(v.value(), 3);
 }
TEST (SemiFuture , SimpleTimedGet)
Definition at line 489 of file SemiFutureTest.cpp.
References EXPECT_THROW, folly::Promise< T >::getSemiFuture(), and folly::gen::move.
{
   Promise<folly::Unit> p;
   auto sf = p.getSemiFuture();
   EXPECT_THROW(
       std::move(sf).get(std::chrono::milliseconds(100)), FutureTimeout);
 }
TEST (SemiFuture , SimpleTimedGetViaFromSemiFuture)
Definition at line 496 of file SemiFutureTest.cpp.
References EXPECT_THROW, folly::Promise< T >::getSemiFuture(), folly::gen::move, and folly::via().
{
   TimedDrivableExecutor e2;
   Promise<folly::Unit> p;
   auto sf = p.getSemiFuture();
   EXPECT_THROW(
       std::move(sf).via(&e2).getVia(&e2, std::chrono::milliseconds(100)),
       FutureTimeout);
 }
TEST (SemiFuture , SimpleTimedGetTry)
Definition at line 505 of file SemiFutureTest.cpp.
References EXPECT_THROW, folly::Promise< T >::getSemiFuture(), and folly::gen::move.
{
   Promise<folly::Unit> p;
   auto sf = p.getSemiFuture();
   EXPECT_THROW(
       std::move(sf).getTry(std::chrono::milliseconds(100)), FutureTimeout);
 }
TEST (SemiFuture , SimpleTimedGetTryViaFromSemiFuture)
Definition at line 512 of file SemiFutureTest.cpp.
References EXPECT_THROW, folly::Promise< T >::getSemiFuture(), folly::gen::move, and folly::via().
{
   TimedDrivableExecutor e2;
   Promise<folly::Unit> p;
   auto sf = p.getSemiFuture();
   EXPECT_THROW(
       std::move(sf).via(&e2).getTryVia(&e2, std::chrono::milliseconds(100)),
       FutureTimeout);
 }
TEST (SemiFuture , SimpleValue)
Definition at line 521 of file SemiFutureTest.cpp.
References ASSERT_EQ, folly::Promise< T >::getSemiFuture(), folly::gen::move, and folly::Promise< T >::setValue().
{
   Promise<int> p;
   auto sf = p.getSemiFuture();
   p.setValue(3);
   auto v = std::move(sf).value();
   ASSERT_EQ(v, 3);
 }
TEST (SemiFuture , SimpleValueThrow)
Definition at line 529 of file SemiFutureTest.cpp.
References EXPECT_THROW, folly::Promise< T >::getSemiFuture(), folly::gen::move, and folly::value().
{
   Promise<folly::Unit> p;
   auto sf = p.getSemiFuture();
   EXPECT_THROW(std::move(sf).value(), FutureNotReady);
 }
TEST (SemiFuture , SimpleResult)
Definition at line 535 of file SemiFutureTest.cpp.
References ASSERT_EQ, folly::Promise< T >::getSemiFuture(), folly::gen::move, and folly::Promise< T >::setValue().
{
   EventBase e2;
   Promise<int> p;
   auto sf = p.getSemiFuture();
   p.setValue(3);
   auto v = std::move(sf).result();
   ASSERT_EQ(v.value(), 3);
 }
TEST (SemiFuture , SimpleResultThrow)
Definition at line 544 of file SemiFutureTest.cpp.
References EXPECT_THROW, folly::Promise< T >::getSemiFuture(), and folly::gen::move.
{
   EventBase e2;
   Promise<folly::Unit> p;
   auto sf = p.getSemiFuture();
   EXPECT_THROW(std::move(sf).result(), FutureNotReady);
 }
TEST (SemiFuture , SimpleDefer)
Definition at line 551 of file SemiFutureTest.cpp.
References ASSERT_EQ, f, folly::Promise< T >::getSemiFuture(), folly::gen::move, and folly::Promise< T >::setValue().
{
   std::atomic<int> innerResult{0};
   Promise<folly::Unit> p;
   auto f = p.getSemiFuture().toUnsafeFuture();
   auto sf = std::move(f).semi().defer([&](auto&&) { innerResult = 17; });
   p.setValue();
   // Run "F" here inline in the calling thread
   std::move(sf).get();
   ASSERT_EQ(innerResult, 17);
 }
TEST (SemiFuture , DeferWithDelayedSetValue)
Definition at line 562 of file SemiFutureTest.cpp.
References ASSERT_EQ, folly::async(), f, folly::Promise< T >::getSemiFuture(), folly::gen::move, and folly::Promise< T >::setValue().
{
   EventBase e2;
   Promise<folly::Unit> p;
   auto f = p.getSemiFuture().toUnsafeFuture();
   auto sf = std::move(f).semi().defer([&](auto&&) { return 17; });
   // Start thread and have it blocking in the semifuture before we satisfy the
   // promise
   auto resultF =
       std::async(std::launch::async, [&]() { return std::move(sf).get(); });
   // Check that future is not already satisfied before setting the promise
   // Async task should be blocked on sf.
   ASSERT_EQ(
       resultF.wait_for(std::chrono::milliseconds(100)),
       std::future_status::timeout);
   p.setValue();
   ASSERT_EQ(resultF.get(), 17);
 }
TEST (SemiFuture , DeferWithViaAndDelayedSetValue)
Definition at line 582 of file SemiFutureTest.cpp.
References ASSERT_EQ, folly::async(), f, folly::Promise< T >::getSemiFuture(), folly::EventBase::loopForever(), folly::gen::move, folly::Promise< T >::setValue(), folly::pushmi::detail::t, folly::EventBase::terminateLoopSoon(), and folly::via().
{
   EventBase e2;
   Promise<folly::Unit> p;
   auto f = p.getSemiFuture().toUnsafeFuture();
   auto sf = std::move(f).semi().defer([&](auto&&) { return 17; }).via(&e2);
   // Start thread and have it blocking in the semifuture before we satisfy the
   // promise.
   auto resultF =
       std::async(std::launch::async, [&]() { return std::move(sf).get(); });
   std::thread t([&]() { e2.loopForever(); });
   // Check that future is not already satisfied before setting the promise
   // Async task should be blocked on sf.
   ASSERT_EQ(
       resultF.wait_for(std::chrono::milliseconds(100)),
       std::future_status::timeout);
   p.setValue();
   e2.terminateLoopSoon();
   t.join();
   ASSERT_EQ(resultF.get(), 17);
 }
TEST (SemiFuture , DeferWithGetTimedGet)
Definition at line 603 of file SemiFutureTest.cpp.
References ASSERT_EQ, EXPECT_THROW, f, folly::Promise< T >::getSemiFuture(), and folly::gen::move.
{
   std::atomic<int> innerResult{0};
   Promise<folly::Unit> p;
   auto f = p.getSemiFuture().toUnsafeFuture();
   auto sf = std::move(f).semi().defer([&](auto&&) { innerResult = 17; });
   EXPECT_THROW(
       std::move(sf).get(std::chrono::milliseconds(100)), FutureTimeout);
   ASSERT_EQ(innerResult, 0);
 }
TEST (SemiFuture , DeferWithVia)
Definition at line 613 of file SemiFutureTest.cpp.
References ASSERT_EQ, f, folly::Promise< T >::getSemiFuture(), folly::gen::move, and folly::Promise< T >::setValue().
{
   std::atomic<int> innerResult{0};
   EventBase e2;
   Promise<folly::Unit> p;
   auto f = p.getSemiFuture().toUnsafeFuture();
   auto sf = std::move(f).semi().defer([&](auto&&) { innerResult = 17; });
   // Run "F" here inline in the calling thread
   auto tf = std::move(sf).via(&e2);
   p.setValue();
   tf.getVia(&e2);
   ASSERT_EQ(innerResult, 17);
 }
TEST (SemiFuture , ChainingDefertoThen)
Definition at line 626 of file SemiFutureTest.cpp.
References ASSERT_EQ, f, folly::Promise< T >::getSemiFuture(), folly::gen::move, and folly::Promise< T >::setValue().
{
   std::atomic<int> innerResult{0};
   std::atomic<int> result{0};
   EventBase e2;
   Promise<folly::Unit> p;
   auto f = p.getSemiFuture().toUnsafeFuture();
   auto sf = std::move(f).semi().defer([&](auto&&) { innerResult = 17; });
   // Run "F" here inline in a task running on the eventbase
   auto tf = std::move(sf).via(&e2).thenValue([&](auto&&) { result = 42; });
   p.setValue();
   tf.getVia(&e2);
   ASSERT_EQ(innerResult, 17);
   ASSERT_EQ(result, 42);
 }
TEST (SemiFuture , SimpleDeferWithValue)
Definition at line 641 of file SemiFutureTest.cpp.
References a, ASSERT_EQ, f, folly::Promise< T >::getSemiFuture(), folly::gen::move, and folly::Promise< T >::setValue().
{
   std::atomic<int> innerResult{0};
   Promise<int> p;
   auto f = p.getSemiFuture().toUnsafeFuture();
   auto sf = std::move(f).semi().deferValue([&](int a) { innerResult = a; });
   p.setValue(7);
   // Run "F" here inline in the calling thread
   std::move(sf).get();
   ASSERT_EQ(innerResult, 7);
 }
TEST (SemiFuture , SimpleDeferWithValueFunctionReference)
Definition at line 658 of file SemiFutureTest.cpp.
References ASSERT_EQ, f, folly::Promise< T >::getSemiFuture(), folly::gen::move, and folly::Promise< T >::setValue().
{
   Promise<int> p;
   auto f = p.getSemiFuture().toUnsafeFuture();
   auto sf = std::move(f).semi().deferValue(deferValueHelper);
   p.setValue(7);
   // Run "F" here inline in the calling thread
   ASSERT_EQ(std::move(sf).get(), 7);
 }
TEST (SemiFuture , ChainingDefertoThenWithValue)
Definition at line 667 of file SemiFutureTest.cpp.
References a, ASSERT_EQ, f, folly::Promise< T >::getSemiFuture(), folly::gen::move, and folly::Promise< T >::setValue().
{
   std::atomic<int> innerResult{0};
   std::atomic<int> result{0};
   EventBase e2;
   Promise<int> p;
   auto f = p.getSemiFuture().toUnsafeFuture();
   auto sf = std::move(f).semi().deferValue([&](int a) {
     innerResult = a;
     return a;
   });
   // Run "F" here inline in a task running on the eventbase
   auto tf = std::move(sf).via(&e2).then([&](int a) { result = a; });
   p.setValue(7);
   tf.getVia(&e2);
   ASSERT_EQ(innerResult, 7);
   ASSERT_EQ(result, 7);
 }
TEST (SemiFuture , MakeSemiFutureFromFutureWithTry)
Definition at line 685 of file SemiFutureTest.cpp.
References ASSERT_EQ, eggs, f, folly::Promise< T >::getSemiFuture(), folly::gen::move, folly::Promise< T >::setException(), folly::pushmi::detail::t, and folly::Try< T >::tryGetExceptionObject().
{
   Promise<int> p;
   auto f = p.getSemiFuture().toUnsafeFuture();
   auto sf = std::move(f).semi().defer([&](Try<int> t) {
     if (auto err = t.tryGetExceptionObject<std::logic_error>()) {
       return Try<std::string>(err->what());
     }
     return Try<std::string>(
         make_exception_wrapper<std::logic_error>("Exception"));
   });
   p.setException(make_exception_wrapper<std::logic_error>("Try"));
   auto tryResult = std::move(sf).get();
   ASSERT_EQ(tryResult.value(), "Try");
 }
TEST (SemiFuture , DeferWithinContinuation)
Definition at line 706 of file SemiFutureTest.cpp.
References ASSERT_EQ, f, folly::Promise< T >::getSemiFuture(), folly::gen::move, and folly::Promise< T >::setValue().
{
   std::atomic<int> innerResult{0};
   std::atomic<int> result{0};
   EventBase e2;
   Promise<int> p;
   Promise<int> p2;
   auto f = p.getSemiFuture().via(&e2);
   auto resultF = std::move(f).then([&, p3 = std::move(p2)](int outer) mutable {
     result = outer;
     return makeSemiFuture<int>(std::move(outer))
         .deferValue([&, p4 = std::move(p3)](int inner) mutable {
           innerResult = inner;
           p4.setValue(inner);
           return inner;
         });
   });
   p.setValue(7);
   auto r = resultF.getVia(&e2);
   ASSERT_EQ(r, 7);
   ASSERT_EQ(innerResult, 7);
   ASSERT_EQ(result, 7);
 }
TEST (SemiFuture , onError)
Definition at line 729 of file SemiFutureTest.cpp.
References eggs, EXPECT_EQ, EXPECT_FLAG, EXPECT_NO_FLAG, EXPECT_NO_THROW, EXPECT_THROW, f, flag, folly::makeSemiFuture(), and folly::gen::move.
{
   bool theFlag = false;
   auto flag = [&] { theFlag = true; };
 #define EXPECT_FLAG()     \
   do {                    \
     EXPECT_TRUE(theFlag); \
     theFlag = false;      \
   } while (0);
 #define EXPECT_NO_FLAG()   \
   do {                     \
     EXPECT_FALSE(theFlag); \
     theFlag = false;       \
   } while (0);
   // By reference
   {
     auto f = makeSemiFuture()
                  .defer([](auto&&) { throw eggs; })
                  .deferError<eggs_t>([&](eggs_t const& /* e */) { flag(); });
     EXPECT_NO_THROW(std::move(f).get());
     EXPECT_FLAG();
   }
   {
     auto f = makeSemiFuture()
                  .defer(deferHelper)
                  .deferError<eggs_t>([&](eggs_t const& /* e */) { flag(); });
     EXPECT_NO_THROW(std::move(f).get());
     EXPECT_FLAG();
   }
   // By auto reference
   {
     auto f = makeSemiFuture()
                  .defer([](auto&&) { throw eggs; })
                  .deferError<eggs_t>([&](auto& /* e */) { flag(); });
     EXPECT_NO_THROW(std::move(f).get());
     EXPECT_FLAG();
   }
   // By value
   {
     auto f = makeSemiFuture()
                  .defer([](auto&&) { throw eggs; })
                  .deferError<eggs_t>([&](eggs_t /* e */) { flag(); });
     EXPECT_NO_THROW(std::move(f).get());
     EXPECT_FLAG();
   }
   // auto value
   {
     auto f = makeSemiFuture()
                  .defer([](auto&&) { throw eggs; })
                  .deferError<eggs_t>([&](auto /* e */) { flag(); });
     EXPECT_NO_THROW(std::move(f).get());
     EXPECT_FLAG();
   }
   // Polymorphic
   {
     auto f =
         makeSemiFuture()
             .defer([](auto&&) { throw eggs; })
             .deferError<std::exception>([&](auto const& /* e */) { flag(); });
     EXPECT_NO_THROW(std::move(f).get());
     EXPECT_FLAG();
   }
   // Non-exceptions
   {
     auto f = makeSemiFuture()
                  .defer([](auto&&) { throw - 1; })
                  .deferError<int>([&](auto /* e */) { flag(); });
     EXPECT_NO_THROW(std::move(f).get());
     EXPECT_FLAG();
   }
   // Mutable lambda
   {
     auto f =
         makeSemiFuture()
             .defer([](auto&&) { throw eggs; })
             .deferError<eggs_t>([&](auto const& /* e */) mutable { flag(); });
     EXPECT_NO_THROW(std::move(f).get());
     EXPECT_FLAG();
   }
   // Function pointer
   {
     auto f = makeSemiFuture()
                  .defer([](auto &&) -> int { throw eggs; })
                  .deferError<eggs_t>(onErrorHelperEggs)
                  .deferError(onErrorHelperGeneric);
     EXPECT_EQ(10, std::move(f).get());
   }
   {
     auto f =
         makeSemiFuture()
             .defer([](auto &&) -> int { throw std::runtime_error("test"); })
             .deferError<eggs_t>(onErrorHelperEggs)
             .deferError(onErrorHelperGeneric);
     EXPECT_EQ(20, std::move(f).get());
   }
   {
     auto f =
         makeSemiFuture()
             .defer([](auto &&) -> int { throw std::runtime_error("test"); })
             .deferError<eggs_t>(onErrorHelperEggs);
     EXPECT_THROW(std::move(f).get(), std::runtime_error);
   }
   // No throw
   {
     auto f = makeSemiFuture()
                  .defer([](auto&&) { return 42; })
                  .deferError<eggs_t>([&](auto& /* e */) {
                    flag();
                    return -1;
                  });
     EXPECT_NO_FLAG();
     EXPECT_EQ(42, std::move(f).get());
     EXPECT_NO_FLAG();
   }
   // Catch different exception
   {
     auto f = makeSemiFuture()
                  .defer([](auto&&) { throw eggs; })
                  .deferError<std::runtime_error>(
                      [&](auto const& /* e */) { flag(); });
     EXPECT_THROW(std::move(f).get(), eggs_t);
     EXPECT_NO_FLAG();
   }
   // Returned value propagates
   {
     auto f = makeSemiFuture()
                  .defer([](auto &&) -> int { throw eggs; })
                  .deferError<eggs_t>([&](auto const& /* e */) { return 42; });
     EXPECT_EQ(42, std::move(f).get());
   }
   // Throw in callback
   {
     auto f = makeSemiFuture()
                  .defer([](auto &&) -> int { throw eggs; })
                  .deferError<eggs_t>([&](auto const& e) -> int { throw e; });
     EXPECT_THROW(std::move(f).get(), eggs_t);
   }
   // exception_wrapper, return T
   {
     auto f = makeSemiFuture()
                  .defer([](auto &&) -> int { throw eggs; })
                  .deferError([&](exception_wrapper /* e */) {
                    flag();
                    return -1;
                  });
     EXPECT_EQ(-1, std::move(f).get());
     EXPECT_FLAG();
   }
   // exception_wrapper, return T but throw
   {
     auto f = makeSemiFuture()
                  .defer([](auto &&) -> int { throw eggs; })
                  .deferError([&](exception_wrapper /* e */) -> int {
                    flag();
                    throw eggs;
                  });
     EXPECT_THROW(std::move(f).get(), eggs_t);
     EXPECT_FLAG();
   }
   // const exception_wrapper&
   {
     auto f = makeSemiFuture()
                  .defer([](auto&&) { throw eggs; })
                  .deferError([&](const exception_wrapper& /* e */) { flag(); });
     EXPECT_NO_THROW(std::move(f).get());
     EXPECT_FLAG();
   }
 }
TEST (SemiFuture , makePromiseContract)
Definition at line 914 of file SemiFutureTest.cpp.
References testing::_, c, EXPECT_EQ, and folly::gen::move.
{
   auto c = makePromiseContract<int>();
   c.first.setValue(3);
   c.second = std::move(c.second).deferValue([](int _) { return _ + 1; });
   EXPECT_EQ(4, std::move(c.second).get());
 }
TEST (SemiFuture , invokeCallbackWithOriginalCVRef)
Definition at line 921 of file SemiFutureTest.cpp.
References EXPECT_EQ, folly::foo, folly::value(), and folly::detail::distributed_mutex::wait().
{
   struct Foo {
     int operator()(int x) & {
       return x + 1;
     }
     int operator()(int x) const& {
       return x + 2;
     }
     int operator()(int x) && {
       return x + 3;
     }
   };
   Foo foo;
   Foo const cfoo;
   // The continuation will be forward-constructed - copied if given as & and
   // moved if given as && - everywhere construction is required.
   // The continuation will be invoked with the same cvref as it is passed.
   EXPECT_EQ(101, makeSemiFuture<int>(100).deferValue(foo).wait().value());
   EXPECT_EQ(202, makeSemiFuture<int>(200).deferValue(cfoo).wait().value());
   EXPECT_EQ(303, makeSemiFuture<int>(300).deferValue(Foo()).wait().value());
 }
TEST (SemiFuture , semiFutureWithinCtxCleanedUpWhenTaskFinishedInTime)
Definition at line 945 of file SemiFutureTest.cpp.
References EXPECT_EQ, folly::Promise< T >::getSemiFuture(), and folly::Promise< T >::setValue().
{
   // Used to track the use_count of callbackInput even outside of its scope
   std::weak_ptr<int> target;
   {
     Promise<std::shared_ptr<int>> promise;
     auto input = std::make_shared<int>(1);
     auto longEnough = std::chrono::milliseconds(1000);
     promise.getSemiFuture()
         .within(longEnough)
         .toUnsafeFuture()
         .then([&target](
                   folly::Try<std::shared_ptr<int>>&& callbackInput) mutable {
           target = callbackInput.value();
         });
     promise.setValue(input);
   }
   // After promise's life cycle is finished, make sure no one is holding the
   // input anymore, in other words, ctx should have been cleaned up.
   EXPECT_EQ(0, target.use_count());
 }
TEST (SemiFuture , semiFutureWithinNoValueReferenceWhenTimeOut)
Definition at line 967 of file SemiFutureTest.cpp.
References EXPECT_EQ, and folly::Promise< T >::getSemiFuture().
{
   Promise<std::shared_ptr<int>> promise;
   auto veryShort = std::chrono::milliseconds(1);
   promise.getSemiFuture().within(veryShort).toUnsafeFuture().then(
       [](folly::Try<std::shared_ptr<int>>&& callbackInput) {
         // Timeout is fired. Verify callbackInput is not referenced
         EXPECT_EQ(0, callbackInput.value().use_count());
       });
 }
TEST (SemiFuture , collectAllSemiFutureDeferredWork)
Definition at line 978 of file SemiFutureTest.cpp.
References folly::collectAllSemiFuture(), folly::pushmi::executor, EXPECT_EQ, EXPECT_TRUE, folly::Promise< T >::getSemiFuture(), folly::gen::guard(), folly::makeGuard(), folly::gen::move, folly::Promise< T >::setValue(), folly::value(), and x.
{
   {
     Promise<int> promise1;
     Promise<int> promise2;
     auto future = collectAllSemiFuture(
         promise1.getSemiFuture().deferValue([](int x) { return x * 2; }),
         promise2.getSemiFuture().deferValue([](int x) { return x * 2; }));
     promise1.setValue(1);
     promise2.setValue(2);
     auto result = std::move(future).getTry(std::chrono::milliseconds{100});
     EXPECT_TRUE(result.hasValue());
     EXPECT_EQ(2, *std::get<0>(*result));
     EXPECT_EQ(4, *std::get<1>(*result));
   }
   {
     Promise<int> promise1;
     Promise<int> promise2;
     auto future = collectAllSemiFuture(
         promise1.getSemiFuture().deferValue([](int x) { return x * 2; }),
         promise2.getSemiFuture().deferValue([](int x) { return x * 2; }));
     promise1.setValue(1);
     promise2.setValue(2);
     ManualExecutor executor;
     auto value = std::move(future).via(&executor).getVia(&executor);
     EXPECT_EQ(2, *std::get<0>(value));
     EXPECT_EQ(4, *std::get<1>(value));
   }
   {
     Promise<int> promise1;
     Promise<int> promise2;
     std::vector<SemiFuture<int>> futures;
     futures.push_back(
         promise1.getSemiFuture().deferValue([](int x) { return x * 2; }));
     futures.push_back(
         promise2.getSemiFuture().deferValue([](int x) { return x * 2; }));
     auto future = collectAllSemiFuture(futures);
     promise1.setValue(1);
     promise2.setValue(2);
     EXPECT_TRUE(future.wait().isReady());
     auto value = std::move(future).get();
     EXPECT_EQ(2, *value[0]);
     EXPECT_EQ(4, *value[1]);
   }
   {
     bool deferredDestroyed = false;
     {
       Promise<int> promise;
       auto guard = makeGuard([&] { deferredDestroyed = true; });
       collectAllSemiFuture(promise.getSemiFuture().deferValue(
           [guard = std::move(guard)](int x) { return x; }));
     }
     EXPECT_TRUE(deferredDestroyed);
   }
 }
TEST (SemiFuture , DeferWithNestedSemiFuture)
Definition at line 1053 of file SemiFutureTest.cpp.
References EXPECT_GE, EXPECT_TRUE, now(), folly::futures::sleep(), and start.
{
   auto start = std::chrono::steady_clock::now();
   auto future = futures::sleep(std::chrono::milliseconds{100})
                     .semi()
                     .deferValue([](auto&&) {
                       return futures::sleep(std::chrono::milliseconds{200});
                     });
   future.wait();
   EXPECT_TRUE(future.hasValue());
   EXPECT_GE(
       std::chrono::steady_clock::now() - start, std::chrono::milliseconds{300});
 }
Variable Documentation
eggs_t eggs("eggs") static
Referenced by TEST().