proxygen: proxygen/folly/folly/experimental/pushmi/examples/set_done/set_done_2.cpp File Reference
set_done_2.cpp File Reference
#include <algorithm>
#include <cassert>
#include <iostream>
#include <vector>
#include <folly/experimental/pushmi/o/empty.h>
#include <folly/experimental/pushmi/o/filter.h>
#include <folly/experimental/pushmi/o/just.h>
#include <folly/experimental/pushmi/o/tap.h>
#include <folly/experimental/pushmi/o/transform.h>
Functions
auto get_setting ()
int main ()
Variables
const bool setting_exists = false
auto println = [](auto v) { std::cout << v << std::endl; }
template<class T , class E = std::exception_ptr>
auto concat
Function Documentation
auto get_setting ()
Definition at line 31 of file set_done_2.cpp.
References folly::pushmi::operators::just, folly::pushmi::make_single_sender, setting_exists, and submit.
Referenced by main().
                    {
   return mi::make_single_sender([](auto out) {
     if (setting_exists) {
       op::just(42) | op::submit(out);
     } else {
       op::empty<int>() | op::submit(out);
     }
   });
 }
int main (void)
Definition at line 53 of file set_done_2.cpp.
References folly::pushmi::operators::filter, get_setting(), i, folly::pushmi::operators::just, println, submit, and folly::pushmi::operators::transform.
            {
   get_setting() | op::transform([](int i) { return std::to_string(i); }) |
       op::submit(println);
   op::just(42) | op::filter([](int i) { return i < 42; }) |
       op::transform([](int i) { return std::to_string(i); }) |
       op::submit(println);
   op::just(42) | op::transform([](int i) {
     if (i < 42) {
       return mi::any_single_sender<std::exception_ptr, std::string>{
           op::empty<std::string>()};
     }
     return mi::any_single_sender<std::exception_ptr, std::string>{
         op::just(std::to_string(i))};
   }) | concat<std::string> |
       op::submit(println);
   std::cout << "OK" << std::endl;
 }
Variable Documentation
template<class T , class E = std::exception_ptr> auto concat
Initial value:
= [](auto in) {
  return mi::make_single_sender([in](auto out) mutable {
    mi::submit(in, mi::make_receiver(out, [](auto out, auto v) {
                 mi::submit(v, mi::any_receiver<E, T>(out));
               }));
  });
}
Definition at line 45 of file set_done_2.cpp.
auto println = [](auto v) { std::cout << v << std::endl; }
Definition at line 41 of file set_done_2.cpp.
Referenced by main(), and folly::symbolizer::SymbolizePrinter::println().
const bool setting_exists = false
Definition at line 29 of file set_done_2.cpp.
Referenced by get_setting().