proxygen: proxygen/folly/folly/experimental/pushmi/examples/set_error/set_error_2.cpp File Reference
set_error_2.cpp File Reference
#include <algorithm>
#include <cassert>
#include <iostream>
#include <vector>
#include <folly/experimental/pushmi/examples/no_fail.h>
#include <folly/experimental/pushmi/o/empty.h>
#include <folly/experimental/pushmi/o/error.h>
#include <folly/experimental/pushmi/o/just.h>
#include <folly/experimental/pushmi/o/switch_on_error.h>
#include <folly/experimental/pushmi/o/transform.h>
Functions
int main ()
Variables
template<class T , class E = std::exception_ptr>
auto concat
Function Documentation
int main (void)
Definition at line 40 of file set_error_2.cpp.
References folly::empty(), folly::pushmi::operators::error(), folly::pushmi::operators::just, folly::pushmi::operators::no_fail, folly::pushmi::__adl::noexcept(), folly::pushmi::on_error(), submit, folly::pushmi::operators::switch_on_error, and folly::pushmi::operators::transform.
            {
   auto stop_abort = mi::on_error([](auto) noexcept {});
   // support all error value types
   op::error(std::exception_ptr{}) | op::submit(stop_abort);
   op::error(std::errc::argument_list_too_long) | op::submit(stop_abort);
   // transform an error
   op::error(std::errc::argument_list_too_long) | op::switch_on_error([
   ](auto) noexcept { return op::error(std::exception_ptr{}); }) |
       op::submit(stop_abort);
   // use default value if an error occurs
   op::just(42) |
       op::switch_on_error([](auto) noexcept { return op::just(0); }) |
       op::submit();
   // suppress if an error occurs
   op::error(std::errc::argument_list_too_long) |
       op::switch_on_error([](auto) noexcept { return op::empty(); }) |
       op::submit();
   // abort if an error occurs
   op::just(42) | op::no_fail() | op::submit();
   // transform value to error_
   op::just(42) | op::transform([](auto v) {
     using r_t = mi::any_single_sender<std::exception_ptr, int>;
     if (v < 40) {
       return r_t{op::error<int>(std::exception_ptr{})};
     } else {
       return r_t{op::just(v)};
     }
   }) | concat<int> |
       op::submit();
   // retry on error
   // http.get(ex) |
   //   op::timeout(ex, 1s) |
   //   op::switch_on_error([](auto e) noexcept { return op::timer(ex, 1s); }) |
   //   op::repeat() |
   //   op::timeout(ex, 10s) |
   //   op::submit();
   std::cout << "OK" << std::endl;
 }
Variable Documentation
template<class T , class E = std::exception_ptr> auto concat
Initial value:
= [](auto in) {
  return mi::make_single_sender([in](auto out) mutable {
    mi::submit(in, mi::make_receiver(out, [](auto out, auto v) {
                 mi::submit(v, mi::any_receiver<E, T>(out));
               }));
  });
}
Definition at line 32 of file set_error_2.cpp.