proxygen: proxygen/folly/folly/experimental/settings/test/SettingsBenchmarks.cpp File Reference
SettingsBenchmarks.cpp File Reference
#include <folly/Benchmark.h>
#include <folly/experimental/settings/Settings.h>
#include <folly/init/Init.h>
Functions
FOLLY_SETTING_DEFINE (follytest, benchmarked, int, 100,"desc")
BENCHMARK (settings_get_bench, iters)
int main (int argc, char **argv)
Function Documentation
BENCHMARK (settings_get_bench , iters)
Definition at line 31 of file SettingsBenchmarks.cpp.
References folly::doNotOptimizeAway(), FOLLY_SETTING, i, and value.
{
   for (unsigned int i = 0; i < iters; ++i) {
     auto value = *FOLLY_SETTING(follytest, benchmarked);
     folly::doNotOptimizeAway(value);
   }
 }
FOLLY_SETTING_DEFINE (follytest , benchmarked , int , 100 , "desc")
int main (int argc, char ** argv)
Definition at line 38 of file SettingsBenchmarks.cpp.
References folly::init(), and folly::runBenchmarks().
{
   folly::init(&argc, &argv);
   folly::runBenchmarks();
   return 0;
 }