proxygen: proxygen/folly/folly/futures/test/SharedPromiseTest.cpp File Reference
SharedPromiseTest.cpp File Reference
#include <folly/futures/SharedPromise.h>
#include <folly/portability/GTest.h>
Functions
TEST (SharedPromise, setGetSemiFuture)
TEST (SharedPromise, setGetMixed)
TEST (SharedPromise, setGet)
TEST (SharedPromise, getSet)
TEST (SharedPromise, getSetGet)
TEST (SharedPromise, reset)
TEST (SharedPromise, getMoveSet)
TEST (SharedPromise, setMoveGet)
TEST (SharedPromise, moveSetGet)
TEST (SharedPromise, moveGetSet)
TEST (SharedPromise, moveMove)
TEST (SharedPromise, setWith)
TEST (SharedPromise, isFulfilled)
TEST (SharedPromise, interruptHandler)
Function Documentation
TEST (SharedPromise , setGetSemiFuture)
Definition at line 22 of file SharedPromiseTest.cpp.
References EXPECT_EQ, folly::SharedPromise< T >::getSemiFuture(), and folly::SharedPromise< T >::setValue().
{
   SharedPromise<int> p;
   p.setValue(1);
   auto f1 = p.getSemiFuture();
   auto f2 = p.getSemiFuture();
   EXPECT_EQ(1, f1.value());
   EXPECT_EQ(1, f2.value());
 }
TEST (SharedPromise , setGetMixed)
Definition at line 31 of file SharedPromiseTest.cpp.
References EXPECT_EQ, folly::SharedPromise< T >::getFuture(), folly::SharedPromise< T >::getSemiFuture(), and folly::SharedPromise< T >::setValue().
{
   SharedPromise<int> p;
   p.setValue(1);
   auto f1 = p.getSemiFuture();
   auto f2 = p.getFuture();
   EXPECT_EQ(1, f1.value());
   EXPECT_EQ(1, f2.value());
 }
TEST (SharedPromise , setGet)
Definition at line 40 of file SharedPromiseTest.cpp.
References EXPECT_EQ, folly::SharedPromise< T >::getFuture(), and folly::SharedPromise< T >::setValue().
{
   SharedPromise<int> p;
   p.setValue(1);
   auto f1 = p.getFuture();
   auto f2 = p.getFuture();
   EXPECT_EQ(1, f1.value());
   EXPECT_EQ(1, f2.value());
 }
TEST (SharedPromise , getSet)
Definition at line 48 of file SharedPromiseTest.cpp.
References EXPECT_EQ, folly::SharedPromise< T >::getFuture(), and folly::SharedPromise< T >::setValue().
{
   SharedPromise<int> p;
   auto f1 = p.getFuture();
   auto f2 = p.getFuture();
   p.setValue(1);
   EXPECT_EQ(1, f1.value());
   EXPECT_EQ(1, f2.value());
 }
TEST (SharedPromise , getSetGet)
Definition at line 57 of file SharedPromiseTest.cpp.
References EXPECT_EQ, folly::SharedPromise< T >::getFuture(), and folly::SharedPromise< T >::setValue().
{
   SharedPromise<int> p;
   auto f1 = p.getFuture();
   p.setValue(1);
   auto f2 = p.getFuture();
   EXPECT_EQ(1, f1.value());
   EXPECT_EQ(1, f2.value());
 }
TEST (SharedPromise , reset)
Definition at line 66 of file SharedPromiseTest.cpp.
References EXPECT_EQ, EXPECT_FALSE, folly::SharedPromise< T >::getFuture(), and folly::SharedPromise< T >::setValue().
{
   SharedPromise<int> p;
   auto f1 = p.getFuture();
   p.setValue(1);
   EXPECT_EQ(1, f1.value());
   p = SharedPromise<int>();
   auto f2 = p.getFuture();
   EXPECT_FALSE(f2.isReady());
   p.setValue(2);
   EXPECT_EQ(2, f2.value());
 }
TEST (SharedPromise , getMoveSet)
Definition at line 80 of file SharedPromiseTest.cpp.
References EXPECT_EQ, f, folly::SharedPromise< T >::getFuture(), and folly::gen::move.
{
   SharedPromise<int> p;
   auto f = p.getFuture();
   auto p2 = std::move(p);
   p2.setValue(1);
   EXPECT_EQ(1, f.value());
 }
TEST (SharedPromise , setMoveGet)
Definition at line 88 of file SharedPromiseTest.cpp.
References EXPECT_EQ, f, folly::gen::move, and folly::SharedPromise< T >::setValue().
{
   SharedPromise<int> p;
   p.setValue(1);
   auto p2 = std::move(p);
   auto f = p2.getFuture();
   EXPECT_EQ(1, f.value());
 }
TEST (SharedPromise , moveSetGet)
Definition at line 96 of file SharedPromiseTest.cpp.
References EXPECT_EQ, f, and folly::gen::move.
{
   SharedPromise<int> p;
   auto p2 = std::move(p);
   p2.setValue(1);
   auto f = p2.getFuture();
   EXPECT_EQ(1, f.value());
 }
TEST (SharedPromise , moveGetSet)
Definition at line 104 of file SharedPromiseTest.cpp.
References EXPECT_EQ, f, and folly::gen::move.
{
   SharedPromise<int> p;
   auto p2 = std::move(p);
   auto f = p2.getFuture();
   p2.setValue(1);
   EXPECT_EQ(1, f.value());
 }
TEST (SharedPromise , moveMove)
Definition at line 112 of file SharedPromiseTest.cpp.
References folly::SharedPromise< T >::getFuture(), folly::gen::move, and folly::SharedPromise< T >::setValue().
{
   SharedPromise<std::shared_ptr<int>> p;
   auto f1 = p.getFuture();
   auto f2 = p.getFuture();
   auto p2 = std::move(p);
   p = std::move(p2);
   p.setValue(std::make_shared<int>(1));
 }
TEST (SharedPromise , setWith)
Definition at line 121 of file SharedPromiseTest.cpp.
References EXPECT_EQ, folly::SharedPromise< T >::getFuture(), and folly::SharedPromise< T >::setWith().
{
   SharedPromise<int> p;
   p.setWith([] { return 1; });
   EXPECT_EQ(1, p.getFuture().value());
 }
TEST (SharedPromise , isFulfilled)
Definition at line 127 of file SharedPromiseTest.cpp.
References EXPECT_FALSE, EXPECT_TRUE, folly::SharedPromise< T >::isFulfilled(), and folly::gen::move.
{
   SharedPromise<int> p;
   EXPECT_FALSE(p.isFulfilled());
   auto p2 = std::move(p);
   EXPECT_FALSE(p2.isFulfilled());
   p2.setValue(1);
   EXPECT_TRUE(p2.isFulfilled());
   p = std::move(p2);
   EXPECT_TRUE(p.isFulfilled());
 }
TEST (SharedPromise , interruptHandler)
Definition at line 138 of file SharedPromiseTest.cpp.
References EXPECT_TRUE, f, flag, folly::SharedPromise< T >::getFuture(), and folly::SharedPromise< T >::setInterruptHandler().
{
   SharedPromise<int> p;
   bool flag = false;
   p.setInterruptHandler([&](const exception_wrapper&) { flag = true; });
   auto f = p.getFuture();
   f.cancel();
   EXPECT_TRUE(flag);
 }