proxygen: proxygen/folly/folly/test/SharedMutexTest.cpp File Reference
SharedMutexTest.cpp File Reference
#include <folly/SharedMutex.h>
#include <stdlib.h>
#include <thread>
#include <vector>
#include <boost/optional.hpp>
#include <boost/thread/shared_mutex.hpp>
#include <folly/Benchmark.h>
#include <folly/MPMCQueue.h>
#include <folly/portability/GFlags.h>
#include <folly/portability/GTest.h>
#include <folly/synchronization/RWSpinLock.h>
#include <folly/test/DeterministicSchedule.h>
#include <folly/test/TestUtils.h>
Classes
struct TokenLocker
struct Locker
struct EnterLocker
struct PosixRWLock
struct PosixMutex
Macros
#define BENCH_BASE(...) FB_VA_GLUE(BENCHMARK_NAMED_PARAM, (__VA_ARGS__))
#define BENCH_REL(...) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM, (__VA_ARGS__))
Typedefs
typedef DeterministicSchedule DSched
typedef SharedMutexImpl< true, void, DeterministicAtomic, true > DSharedMutexReadPriority
typedef SharedMutexImpl< false, void, DeterministicAtomic, true > DSharedMutexWritePriority
Functions
template<typename Lock >
void runBasicTest ()
TEST (SharedMutex, basic)
template<typename Lock >
void runBasicHoldersTest ()
TEST (SharedMutex, basic_holders)
template<typename Lock >
void runManyReadLocksTestWithTokens ()
TEST (SharedMutex, many_read_locks_with_tokens)
template<typename Lock >
void runManyReadLocksTestWithoutTokens ()
TEST (SharedMutex, many_read_locks_without_tokens)
template<typename Lock >
void runTimeoutInPastTest ()
TEST (SharedMutex, timeout_in_past)
template<class Func >
bool funcHasDuration (milliseconds expectedDuration, Func func)
template<typename Lock >
void runFailingTryTimeoutTest ()
TEST (SharedMutex, failing_try_timeout)
template<typename Lock >
void runBasicUpgradeTest ()
TEST (SharedMutex, basic_upgrade_tests)
TEST (SharedMutex, read_has_prio)
TEST (SharedMutex, write_has_prio)
template<template< typename > class Atom, typename Lock , typename Locker >
static void runContendedReaders (size_t numOps, size_t numThreads, bool useSeparateLocks)
static void folly_rwspin_reads (uint32_t numOps, size_t numThreads, bool useSeparateLocks)
static void shmtx_wr_pri_reads (uint32_t numOps, size_t numThreads, bool useSeparateLocks)
static void shmtx_w_bare_reads (uint32_t numOps, size_t numThreads, bool useSeparateLocks)
static void shmtx_rd_pri_reads (uint32_t numOps, size_t numThreads, bool useSeparateLocks)
static void shmtx_r_bare_reads (uint32_t numOps, size_t numThreads, bool useSeparateLocks)
static void folly_ticket_reads (uint32_t numOps, size_t numThreads, bool useSeparateLocks)
static void boost_shared_reads (uint32_t numOps, size_t numThreads, bool useSeparateLocks)
static void pthrd_rwlock_reads (uint32_t numOps, size_t numThreads, bool useSeparateLocks)
template<template< typename > class Atom, typename Lock , typename Locker >
static void runMixed (size_t numOps, size_t numThreads, double writeFraction, bool useSeparateLocks)
static void folly_rwspin (size_t numOps, size_t numThreads, double writeFraction, bool useSeparateLocks)
static void shmtx_wr_pri (uint32_t numOps, size_t numThreads, double writeFraction, bool useSeparateLocks)
static void shmtx_w_bare (uint32_t numOps, size_t numThreads, double writeFraction, bool useSeparateLocks)
static void shmtx_rd_pri (uint32_t numOps, size_t numThreads, double writeFraction, bool useSeparateLocks)
static void shmtx_r_bare (uint32_t numOps, size_t numThreads, double writeFraction, bool useSeparateLocks)
static void folly_ticket (size_t numOps, size_t numThreads, double writeFraction, bool useSeparateLocks)
static void boost_shared (size_t numOps, size_t numThreads, double writeFraction, bool useSeparateLocks)
static void pthrd_rwlock (size_t numOps, size_t numThreads, double writeFraction, bool useSeparateLocks)
static void pthrd_mutex_ (size_t numOps, size_t numThreads, double writeFraction, bool useSeparateLocks)
template<typename Lock , template< typename > class Atom>
static void runAllAndValidate (size_t numOps, size_t numThreads)
TEST (SharedMutex, deterministic_concurrent_readers_of_one_lock_read_prio)
TEST (SharedMutex, deterministic_concurrent_readers_of_one_lock_write_prio)
TEST (SharedMutex, concurrent_readers_of_one_lock_read_prio)
TEST (SharedMutex, concurrent_readers_of_one_lock_write_prio)
TEST (SharedMutex, deterministic_readers_of_concurrent_locks_read_prio)
TEST (SharedMutex, deterministic_readers_of_concurrent_locks_write_prio)
TEST (SharedMutex, readers_of_concurrent_locks_read_prio)
TEST (SharedMutex, readers_of_concurrent_locks_write_prio)
TEST (SharedMutex, deterministic_mixed_mostly_read_read_prio)
TEST (SharedMutex, deterministic_mixed_mostly_read_write_prio)
TEST (SharedMutex, mixed_mostly_read_read_prio)
TEST (SharedMutex, mixed_mostly_read_write_prio)
TEST (SharedMutex, deterministic_mixed_mostly_write_read_prio)
TEST (SharedMutex, deterministic_mixed_mostly_write_write_prio)
TEST (SharedMutex, deterministic_lost_wakeup_write_prio)
static std::size_t adjustReps (std::size_t reps)
TEST (SharedMutex, mixed_mostly_write_read_prio)
TEST (SharedMutex, mixed_mostly_write_write_prio)
TEST (SharedMutex, deterministic_all_ops_read_prio)
TEST (SharedMutex, deterministic_all_ops_write_prio)
TEST (SharedMutex, all_ops_read_prio)
TEST (SharedMutex, all_ops_write_prio)
FOLLY_ASSUME_FBVECTOR_COMPATIBLE (boost::optional< boost::optional< SharedMutexToken >>) template< typename Lock
template<typename >
class Atom static void runRemoteUnlock (size_t numOps, double preWriteFraction, double preUpgradeFraction, size_t numSendingThreads, size_t numReceivingThreads)
TEST (SharedMutex, deterministic_remote_write_prio)
TEST (SharedMutex, deterministic_remote_read_prio)
TEST (SharedMutex, remote_write_prio)
TEST (SharedMutex, remote_read_prio)
static void burn (size_t n)
template<typename Lock , template< typename > class Atom = atomic>
static void runPingPong (size_t numRounds, size_t burnCount)
static void folly_rwspin_ping_pong (size_t n, size_t scale, size_t burnCount)
static void shmtx_w_bare_ping_pong (size_t n, size_t scale, size_t burnCount)
static void shmtx_r_bare_ping_pong (size_t n, size_t scale, size_t burnCount)
static void folly_ticket_ping_pong (size_t n, size_t scale, size_t burnCount)
static void boost_shared_ping_pong (size_t n, size_t scale, size_t burnCount)
static void pthrd_rwlock_ping_pong (size_t n, size_t scale, size_t burnCount)
TEST (SharedMutex, deterministic_ping_pong_write_prio)
TEST (SharedMutex, deterministic_ping_pong_read_prio)
TEST (SharedMutex, ping_pong_write_prio)
TEST (SharedMutex, ping_pong_read_prio)
BENCHMARK (single_thread_lock_shared_unlock_shared, iters)
BENCHMARK (single_thread_lock_unlock, iters)
BENCHMARK_DRAW_LINE ()
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin_reads, 1thread, 1, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_w_bare_reads, 1thread, 1, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_r_bare_reads, 1thread, 1, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared_reads, 1thread, 1, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin_reads, 2thread, 2, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_w_bare_reads, 2thread, 2, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_r_bare_reads, 2thread, 2, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared_reads, 2thread, 2, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin_reads, 4thread, 4, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_w_bare_reads, 4thread, 4, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_r_bare_reads, 4thread, 4, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared_reads, 4thread, 4, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin_reads, 8thread, 8, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_w_bare_reads, 8thread, 8, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_r_bare_reads, 8thread, 8, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared_reads, 8thread, 8, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin_reads, 16thread, 16, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_w_bare_reads, 16thread, 16, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_r_bare_reads, 16thread, 16, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared_reads, 16thread, 16, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin_reads, 32thread, 32, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_w_bare_reads, 32thread, 32, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_r_bare_reads, 32thread, 32, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared_reads, 32thread, 32, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin_reads, 64thread, 64, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_w_bare_reads, 64thread, 64, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_r_bare_reads, 64thread, 64, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared_reads, 64thread, 64, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 1thread_all_write, 1, 1.0, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_rd_pri, 1thread_all_write, 1, 1.0, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared, 1thread_all_write, 1, 1.0, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(pthrd_mutex_, 1thread_all_write, 1, 1.0, false)) BENCHMARK_DRAW_LINE()
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 2thread_all_write, 2, 1.0, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_rd_pri, 2thread_all_write, 2, 1.0, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared, 2thread_all_write, 2, 1.0, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(pthrd_mutex_, 2thread_all_write, 2, 1.0, false)) BENCHMARK_DRAW_LINE()
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 4thread_all_write, 4, 1.0, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_rd_pri, 4thread_all_write, 4, 1.0, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared, 4thread_all_write, 4, 1.0, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(pthrd_mutex_, 4thread_all_write, 4, 1.0, false)) BENCHMARK_DRAW_LINE()
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 8thread_all_write, 8, 1.0, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_rd_pri, 8thread_all_write, 8, 1.0, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared, 8thread_all_write, 8, 1.0, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(pthrd_mutex_, 8thread_all_write, 8, 1.0, false)) BENCHMARK_DRAW_LINE()
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 16thread_all_write, 16, 1.0, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_rd_pri, 16thread_all_write, 16, 1.0, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared, 16thread_all_write, 16, 1.0, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(pthrd_mutex_, 16thread_all_write, 16, 1.0, false)) BENCHMARK_DRAW_LINE()
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 32thread_all_write, 32, 1.0, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_rd_pri, 32thread_all_write, 32, 1.0, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared, 32thread_all_write, 32, 1.0, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(pthrd_mutex_, 32thread_all_write, 32, 1.0, false)) BENCHMARK_DRAW_LINE()
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 64thread_all_write, 64, 1.0, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_rd_pri, 64thread_all_write, 64, 1.0, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared, 64thread_all_write, 64, 1.0, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(pthrd_mutex_, 64thread_all_write, 64, 1.0, false)) BENCHMARK_DRAW_LINE()
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 1thread_10pct_write, 1, 0.10, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_rd_pri, 1thread_10pct_write, 1, 0.10, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared, 1thread_10pct_write, 1, 0.10, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 2thread_10pct_write, 2, 0.10, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_rd_pri, 2thread_10pct_write, 2, 0.10, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared, 2thread_10pct_write, 2, 0.10, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 4thread_10pct_write, 4, 0.10, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_rd_pri, 4thread_10pct_write, 4, 0.10, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared, 4thread_10pct_write, 4, 0.10, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 8thread_10pct_write, 8, 0.10, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_rd_pri, 8thread_10pct_write, 8, 0.10, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared, 8thread_10pct_write, 8, 0.10, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 16thread_10pct_write, 16, 0.10, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_rd_pri, 16thread_10pct_write, 16, 0.10, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared, 16thread_10pct_write, 16, 0.10, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 32thread_10pct_write, 32, 0.10, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_rd_pri, 32thread_10pct_write, 32, 0.10, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared, 32thread_10pct_write, 32, 0.10, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 64thread_10pct_write, 64, 0.10, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_rd_pri, 64thread_10pct_write, 64, 0.10, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared, 64thread_10pct_write, 64, 0.10, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 1thread_1pct_write, 1, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_w_bare, 1thread_1pct_write, 1, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_r_bare, 1thread_1pct_write, 1, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared, 1thread_1pct_write, 1, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 2thread_1pct_write, 2, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_w_bare, 2thread_1pct_write, 2, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_r_bare, 2thread_1pct_write, 2, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared, 2thread_1pct_write, 2, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 4thread_1pct_write, 4, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_w_bare, 4thread_1pct_write, 4, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_r_bare, 4thread_1pct_write, 4, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared, 4thread_1pct_write, 4, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 8thread_1pct_write, 8, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_w_bare, 8thread_1pct_write, 8, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_r_bare, 8thread_1pct_write, 8, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared, 8thread_1pct_write, 8, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 16thread_1pct_write, 16, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_w_bare, 16thread_1pct_write, 16, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_r_bare, 16thread_1pct_write, 16, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared, 16thread_1pct_write, 16, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 32thread_1pct_write, 32, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_w_bare, 32thread_1pct_write, 32, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_r_bare, 32thread_1pct_write, 32, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared, 32thread_1pct_write, 32, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 64thread_1pct_write, 64, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_w_bare, 64thread_1pct_write, 64, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_r_bare, 64thread_1pct_write, 64, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared, 64thread_1pct_write, 64, 0.01, false)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 2thr_2lock_50pct_write, 2, 0.50, true)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_rd_pri, 2thr_2lock_50pct_write, 2, 0.50, true)) FB_VA_GLUE(BENCHMARK_NAMED_PARAM
true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_wr_pri, 4thr_4lock_50pct_write, 4, 0.50, true)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
true true true FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 8thr_8lock_50pct_write, 8, 0.50, true)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
true true true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_rd_pri, 8thr_8lock_50pct_write, 8, 0.50, true)) FB_VA_GLUE(BENCHMARK_NAMED_PARAM
true true true true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_wr_pri, 16thr_16lock_50pct_write, 16, 0.50, true)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
true true true true true true FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 32thr_32lock_50pct_write, 32, 0.50, true)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
true true true true true true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_rd_pri, 32thr_32lock_50pct_write, 32, 0.50, true)) FB_VA_GLUE(BENCHMARK_NAMED_PARAM
true true true true true true true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_wr_pri, 64thr_64lock_50pct_write, 64, 0.50, true)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 2thr_2lock_10pct_write, 2, 0.10, true)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_rd_pri, 2thr_2lock_10pct_write, 2, 0.10, true)) FB_VA_GLUE(BENCHMARK_NAMED_PARAM
true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_wr_pri, 4thr_4lock_10pct_write, 4, 0.10, true)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
true true true FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 8thr_8lock_10pct_write, 8, 0.10, true)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
true true true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_rd_pri, 8thr_8lock_10pct_write, 8, 0.10, true)) FB_VA_GLUE(BENCHMARK_NAMED_PARAM
true true true true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_wr_pri, 16thr_16lock_10pct_write, 16, 0.10, true)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
true true true true true true FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 32thr_32lock_10pct_write, 32, 0.10, true)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
true true true true true true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_rd_pri, 32thr_32lock_10pct_write, 32, 0.10, true)) FB_VA_GLUE(BENCHMARK_NAMED_PARAM
true true true true true true true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_wr_pri, 64thr_64lock_10pct_write, 64, 0.10, true)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 2thr_2lock_1pct_write, 2, 0.01, true)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_rd_pri, 2thr_2lock_1pct_write, 2, 0.01, true)) FB_VA_GLUE(BENCHMARK_NAMED_PARAM
true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_wr_pri, 4thr_4lock_1pct_write, 4, 0.01, true)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
true true true FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 8thr_8lock_1pct_write, 8, 0.01, true)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
true true true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_rd_pri, 8thr_8lock_1pct_write, 8, 0.01, true)) FB_VA_GLUE(BENCHMARK_NAMED_PARAM
true true true true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_wr_pri, 16thr_16lock_1pct_write, 16, 0.01, true)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
true true true true true true FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin, 32thr_32lock_1pct_write, 32, 0.01, true)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
true true true true true true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_rd_pri, 32thr_32lock_1pct_write, 32, 0.01, true)) FB_VA_GLUE(BENCHMARK_NAMED_PARAM
true true true true true true true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_wr_pri, 64thr_64lock_1pct_write, 64, 0.01, true)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin_ping_pong, burn0, 1, 0)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_r_bare_ping_pong, burn0, 1, 0)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared_ping_pong, burn0, 1, 0)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin_ping_pong, burn100k, 100, 100000)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_r_bare_ping_pong, burn100k, 100, 100000)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared_ping_pong, burn100k, 100, 100000)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin_ping_pong, burn300k, 100, 300000)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_r_bare_ping_pong, burn300k, 100, 300000)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared_ping_pong, burn300k, 100, 300000)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_NAMED_PARAM,(folly_rwspin_ping_pong, burn1M, 1000, 1000000)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(shmtx_r_bare_ping_pong, burn1M, 1000, 1000000)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM,(boost_shared_ping_pong, burn1M, 1000, 1000000)) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM
int main (int argc, char **argv)
Variables
shmtx_wr_pri_reads
false shmtx_rd_pri_reads
false false folly_ticket_reads
false false false pthrd_rwlock_reads
shmtx_wr_pri
false folly_ticket
false false pthrd_rwlock
false shmtx_rd_pri
true folly_rwspin
shmtx_w_bare_ping_pong
burn0
folly_ticket_ping_pong
pthrd_rwlock_ping_pong
burn100k
burn300k
burn1M
Macro Definition Documentation
#define BENCH_BASE (...) FB_VA_GLUE(BENCHMARK_NAMED_PARAM, (__VA_ARGS__))
Definition at line 1435 of file SharedMutexTest.cpp.
#define BENCH_REL (...) FB_VA_GLUE(BENCHMARK_RELATIVE_NAMED_PARAM, (__VA_ARGS__))
Definition at line 1436 of file SharedMutexTest.cpp.
Typedef Documentation
typedef DeterministicSchedule DSched
Definition at line 38 of file SharedMutexTest.cpp.
typedef SharedMutexImpl<true, void, DeterministicAtomic, true> DSharedMutexReadPriority
Definition at line 40 of file SharedMutexTest.cpp.
typedef SharedMutexImpl<false, void, DeterministicAtomic, true> DSharedMutexWritePriority
Definition at line 42 of file SharedMutexTest.cpp.
Function Documentation
static std::size_t adjustReps (std::size_t reps) static
Definition at line 1090 of file SharedMutexTest.cpp.
References folly::kIsSanitizeThread.
Referenced by TEST().
{
   if (folly::kIsSanitizeThread) {
     return reps / 10;
   }
   return reps;
 }
BENCHMARK (single_thread_lock_shared_unlock_shared , iters)
Definition at line 1416 of file SharedMutexTest.cpp.
References folly::doNotOptimizeAway(), folly::lock(), folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::lock_shared(), and folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::unlock_shared().
{
   SharedMutex lock;
   for (size_t n = 0; n < iters; ++n) {
     SharedMutex::Token token;
     lock.lock_shared(token);
     folly::doNotOptimizeAway(0);
     lock.unlock_shared(token);
   }
 }
BENCHMARK (single_thread_lock_unlock , iters)
Definition at line 1426 of file SharedMutexTest.cpp.
References folly::doNotOptimizeAway(), folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::lock(), folly::lock(), and folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::unlock().
{
   SharedMutex lock;
   for (size_t n = 0; n < iters; ++n) {
     lock.lock();
     folly::doNotOptimizeAway(0);
     lock.unlock();
   }
 }
BENCHMARK_DRAW_LINE ()
static void boost_shared (size_t numOps, size_t numThreads, double writeFraction, bool useSeparateLocks) static
Definition at line 726 of file SharedMutexTest.cpp.
{
   runMixed<atomic, boost::shared_mutex, Locker>(
       numOps, numThreads, writeFraction, useSeparateLocks);
 }
static void boost_shared_ping_pong (size_t n, size_t scale, size_t burnCount) static
Definition at line 1373 of file SharedMutexTest.cpp.
{
   runPingPong<boost::shared_mutex>(n / scale, burnCount);
 }
static void boost_shared_reads (uint32_t numOps, size_t numThreads, bool useSeparateLocks) static
Definition at line 606 of file SharedMutexTest.cpp.
{
   runContendedReaders<atomic, boost::shared_mutex, Locker>(
       numOps, numThreads, useSeparateLocks);
 }
static void burn (size_t n) static
Definition at line 1293 of file SharedMutexTest.cpp.
References Atom, folly::doNotOptimizeAway(), and i.
Referenced by runPingPong().
{
   for (size_t i = 0; i < n; ++i) {
     folly::doNotOptimizeAway(i);
   }
 }
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin_reads, 1thread, 1, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_w_bare_reads, 1thread, 1, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_r_bare_reads, 1thread, 1, false))
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared_reads, 1thread, 1, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin_reads, 2thread, 2, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_w_bare_reads, 2thread, 2, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_r_bare_reads, 2thread, 2, false))
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared_reads, 2thread, 2, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin_reads, 4thread, 4, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_w_bare_reads, 4thread, 4, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_r_bare_reads, 4thread, 4, false))
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared_reads, 4thread, 4, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin_reads, 8thread, 8, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_w_bare_reads, 8thread, 8, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_r_bare_reads, 8thread, 8, false))
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared_reads, 8thread, 8, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin_reads, 16thread, 16, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_w_bare_reads, 16thread, 16, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_r_bare_reads, 16thread, 16, false))
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared_reads, 16thread, 16, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin_reads, 32thread, 32, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_w_bare_reads, 32thread, 32, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_r_bare_reads, 32thread, 32, false))
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared_reads, 32thread, 32, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin_reads, 64thread, 64, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_w_bare_reads, 64thread, 64, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_r_bare_reads, 64thread, 64, false))
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared_reads, 64thread, 64, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 1thread_all_write, 1, 1.0, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_rd_pri, 1thread_all_write, 1, 1.0, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared, 1thread_all_write, 1, 1.0, false))
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (pthrd_mutex_, 1thread_all_write, 1, 1.0, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 2thread_all_write, 2, 1.0, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_rd_pri, 2thread_all_write, 2, 1.0, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared, 2thread_all_write, 2, 1.0, false))
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (pthrd_mutex_, 2thread_all_write, 2, 1.0, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 4thread_all_write, 4, 1.0, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_rd_pri, 4thread_all_write, 4, 1.0, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared, 4thread_all_write, 4, 1.0, false))
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (pthrd_mutex_, 4thread_all_write, 4, 1.0, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 8thread_all_write, 8, 1.0, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_rd_pri, 8thread_all_write, 8, 1.0, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared, 8thread_all_write, 8, 1.0, false))
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (pthrd_mutex_, 8thread_all_write, 8, 1.0, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 16thread_all_write, 16, 1.0, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_rd_pri, 16thread_all_write, 16, 1.0, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared, 16thread_all_write, 16, 1.0, false))
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (pthrd_mutex_, 16thread_all_write, 16, 1.0, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 32thread_all_write, 32, 1.0, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_rd_pri, 32thread_all_write, 32, 1.0, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared, 32thread_all_write, 32, 1.0, false))
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (pthrd_mutex_, 32thread_all_write, 32, 1.0, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 64thread_all_write, 64, 1.0, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_rd_pri, 64thread_all_write, 64, 1.0, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared, 64thread_all_write, 64, 1.0, false))
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (pthrd_mutex_, 64thread_all_write, 64, 1.0, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 1thread_10pct_write, 1, 0.10, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_rd_pri, 1thread_10pct_write, 1, 0.10, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared, 1thread_10pct_write, 1, 0.10, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 2thread_10pct_write, 2, 0.10, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_rd_pri, 2thread_10pct_write, 2, 0.10, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared, 2thread_10pct_write, 2, 0.10, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 4thread_10pct_write, 4, 0.10, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_rd_pri, 4thread_10pct_write, 4, 0.10, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared, 4thread_10pct_write, 4, 0.10, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 8thread_10pct_write, 8, 0.10, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_rd_pri, 8thread_10pct_write, 8, 0.10, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared, 8thread_10pct_write, 8, 0.10, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 16thread_10pct_write, 16, 0.10, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_rd_pri, 16thread_10pct_write, 16, 0.10, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared, 16thread_10pct_write, 16, 0.10, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 32thread_10pct_write, 32, 0.10, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_rd_pri, 32thread_10pct_write, 32, 0.10, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared, 32thread_10pct_write, 32, 0.10, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 64thread_10pct_write, 64, 0.10, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_rd_pri, 64thread_10pct_write, 64, 0.10, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared, 64thread_10pct_write, 64, 0.10, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 1thread_1pct_write, 1, 0.01, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_w_bare, 1thread_1pct_write, 1, 0.01, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_r_bare, 1thread_1pct_write, 1, 0.01, false))
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared, 1thread_1pct_write, 1, 0.01, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 2thread_1pct_write, 2, 0.01, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_w_bare, 2thread_1pct_write, 2, 0.01, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_r_bare, 2thread_1pct_write, 2, 0.01, false))
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared, 2thread_1pct_write, 2, 0.01, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 4thread_1pct_write, 4, 0.01, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_w_bare, 4thread_1pct_write, 4, 0.01, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_r_bare, 4thread_1pct_write, 4, 0.01, false))
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared, 4thread_1pct_write, 4, 0.01, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 8thread_1pct_write, 8, 0.01, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_w_bare, 8thread_1pct_write, 8, 0.01, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_r_bare, 8thread_1pct_write, 8, 0.01, false))
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared, 8thread_1pct_write, 8, 0.01, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 16thread_1pct_write, 16, 0.01, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_w_bare, 16thread_1pct_write, 16, 0.01, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_r_bare, 16thread_1pct_write, 16, 0.01, false))
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared, 16thread_1pct_write, 16, 0.01, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 32thread_1pct_write, 32, 0.01, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_w_bare, 32thread_1pct_write, 32, 0.01, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_r_bare, 32thread_1pct_write, 32, 0.01, false))
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared, 32thread_1pct_write, 32, 0.01, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 64thread_1pct_write, 64, 0.01, false))
false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_w_bare, 64thread_1pct_write, 64, 0.01, false))
false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_r_bare, 64thread_1pct_write, 64, 0.01, false))
false false false FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared, 64thread_1pct_write, 64, 0.01, false))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 2thr_2lock_50pct_write, 2, 0.50, true))
true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_rd_pri, 2thr_2lock_50pct_write, 2, 0.50, true))
true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_wr_pri, 4thr_4lock_50pct_write, 4, 0.50, true))
true true true FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 8thr_8lock_50pct_write, 8, 0.50, true))
true true true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_rd_pri, 8thr_8lock_50pct_write, 8, 0.50, true))
true true true true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_wr_pri, 16thr_16lock_50pct_write, 16, 0.50, true))
true true true true true true FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 32thr_32lock_50pct_write, 32, 0.50, true))
true true true true true true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_rd_pri, 32thr_32lock_50pct_write, 32, 0.50, true))
true true true true true true true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_wr_pri, 64thr_64lock_50pct_write, 64, 0.50, true))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 2thr_2lock_10pct_write, 2, 0.10, true))
true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_rd_pri, 2thr_2lock_10pct_write, 2, 0.10, true))
true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_wr_pri, 4thr_4lock_10pct_write, 4, 0.10, true))
true true true FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 8thr_8lock_10pct_write, 8, 0.10, true))
true true true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_rd_pri, 8thr_8lock_10pct_write, 8, 0.10, true))
true true true true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_wr_pri, 16thr_16lock_10pct_write, 16, 0.10, true))
true true true true true true FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 32thr_32lock_10pct_write, 32, 0.10, true))
true true true true true true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_rd_pri, 32thr_32lock_10pct_write, 32, 0.10, true))
true true true true true true true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_wr_pri, 64thr_64lock_10pct_write, 64, 0.10, true))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 2thr_2lock_1pct_write, 2, 0.01, true))
true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_rd_pri, 2thr_2lock_1pct_write, 2, 0.01, true))
true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_wr_pri, 4thr_4lock_1pct_write, 4, 0.01, true))
true true true FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 8thr_8lock_1pct_write, 8, 0.01, true))
true true true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_rd_pri, 8thr_8lock_1pct_write, 8, 0.01, true))
true true true true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_wr_pri, 16thr_16lock_1pct_write, 16, 0.01, true))
true true true true true true FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin, 32thr_32lock_1pct_write, 32, 0.01, true))
true true true true true true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_rd_pri, 32thr_32lock_1pct_write, 32, 0.01, true))
true true true true true true true true FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_wr_pri, 64thr_64lock_1pct_write, 64, 0.01, true))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin_ping_pong, burn0, 1, 0))
FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_r_bare_ping_pong, burn0, 1, 0))
FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared_ping_pong, burn0, 1, 0))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin_ping_pong, burn100k, 100, 100000))
FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_r_bare_ping_pong, burn100k, 100, 100000))
FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared_ping_pong, burn100k, 100, 100000))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin_ping_pong, burn300k, 100, 300000))
FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_r_bare_ping_pong, burn300k, 100, 300000))
FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared_ping_pong, burn300k, 100, 300000))
FB_VA_GLUE (BENCHMARK_NAMED_PARAM , (folly_rwspin_ping_pong, burn1M, 1000, 1000000))
FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (shmtx_r_bare_ping_pong, burn1M, 1000, 1000000))
FB_VA_GLUE (BENCHMARK_RELATIVE_NAMED_PARAM , (boost_shared_ping_pong, burn1M, 1000, 1000000))
FOLLY_ASSUME_FBVECTOR_COMPATIBLE (boost::optional< boost::optional< SharedMutexToken >>)
Referenced by TEST().
static void folly_rwspin (size_t numOps, size_t numThreads, double writeFraction, bool useSeparateLocks) static
Definition at line 672 of file SharedMutexTest.cpp.
{
   runMixed<atomic, RWSpinLock, Locker>(
       numOps, numThreads, writeFraction, useSeparateLocks);
 }
static void folly_rwspin_ping_pong (size_t n, size_t scale, size_t burnCount) static
Definition at line 1357 of file SharedMutexTest.cpp.
{
   runPingPong<RWSpinLock>(n / scale, burnCount);
 }
static void folly_rwspin_reads (uint32_t numOps, size_t numThreads, bool useSeparateLocks) static
Definition at line 570 of file SharedMutexTest.cpp.
{
   runContendedReaders<atomic, RWSpinLock, Locker>(
       numOps, numThreads, useSeparateLocks);
 }
static void folly_ticket (size_t numOps, size_t numThreads, double writeFraction, bool useSeparateLocks) static
Definition at line 717 of file SharedMutexTest.cpp.
{
   runMixed<atomic, RWTicketSpinLock64, Locker>(
       numOps, numThreads, writeFraction, useSeparateLocks);
 }
static void folly_ticket_ping_pong (size_t n, size_t scale, size_t burnCount) static
Definition at line 1369 of file SharedMutexTest.cpp.
{
   runPingPong<RWTicketSpinLock64>(n / scale, burnCount);
 }
static void folly_ticket_reads (uint32_t numOps, size_t numThreads, bool useSeparateLocks) static
Definition at line 600 of file SharedMutexTest.cpp.
{
   runContendedReaders<atomic, RWTicketSpinLock64, Locker>(
       numOps, numThreads, useSeparateLocks);
 }
template<class Func > bool funcHasDuration (milliseconds expectedDuration, Func func)
Definition at line 232 of file SharedMutexTest.cpp.
References now(), and start.
Referenced by runFailingTryTimeoutTest().
{
   // elapsed time should eventually fall within expectedDuration +- 25%
   for (int tries = 0; tries < 100; ++tries) {
     auto start = steady_clock::now();
     func();
     auto elapsed = steady_clock::now() - start;
     if (elapsed > expectedDuration - expectedDuration / 4 &&
         elapsed < expectedDuration + expectedDuration / 4) {
       return true;
     }
   }
   return false;
 }
int main (int argc, char ** argv)
Definition at line 2125 of file SharedMutexTest.cpp.
References testing::InitGoogleTest(), RUN_ALL_TESTS(), and folly::runBenchmarksOnFlag().
{
   (void)folly_rwspin_reads;
   (void)shmtx_wr_pri_reads;
   (void)shmtx_w_bare_reads;
   (void)shmtx_rd_pri_reads;
   (void)shmtx_r_bare_reads;
   (void)folly_ticket_reads;
   (void)boost_shared_reads;
   (void)pthrd_rwlock_reads;
   (void)folly_rwspin;
   (void)shmtx_wr_pri;
   (void)shmtx_w_bare;
   (void)shmtx_rd_pri;
   (void)shmtx_r_bare;
   (void)folly_ticket;
   (void)boost_shared;
   (void)pthrd_rwlock;
   (void)pthrd_mutex_;
   (void)folly_rwspin_ping_pong;
   (void)shmtx_w_bare_ping_pong;
   (void)shmtx_r_bare_ping_pong;
   (void)folly_ticket_ping_pong;
   (void)boost_shared_ping_pong;
   (void)pthrd_rwlock_ping_pong;
   testing::InitGoogleTest(&argc, argv);
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   int rv = RUN_ALL_TESTS();
   folly::runBenchmarksOnFlag();
   return rv;
 }
static void pthrd_mutex_ (size_t numOps, size_t numThreads, double writeFraction, bool useSeparateLocks) static
Definition at line 744 of file SharedMutexTest.cpp.
References Atom.
{
   runMixed<atomic, PosixMutex, Locker>(
       numOps, numThreads, writeFraction, useSeparateLocks);
 }
static void pthrd_rwlock (size_t numOps, size_t numThreads, double writeFraction, bool useSeparateLocks) static
Definition at line 735 of file SharedMutexTest.cpp.
{
   runMixed<atomic, PosixRWLock, Locker>(
       numOps, numThreads, writeFraction, useSeparateLocks);
 }
static void pthrd_rwlock_ping_pong (size_t n, size_t scale, size_t burnCount) static
Definition at line 1377 of file SharedMutexTest.cpp.
{
   runPingPong<PosixRWLock>(n / scale, burnCount);
 }
static void pthrd_rwlock_reads (uint32_t numOps, size_t numThreads, bool useSeparateLocks) static
Definition at line 612 of file SharedMutexTest.cpp.
References Atom.
{
   runContendedReaders<atomic, PosixRWLock, Locker>(
       numOps, numThreads, useSeparateLocks);
 }
template<typename Lock , template< typename > class Atom> static void runAllAndValidate (size_t numOps, size_t numThreads) static
Definition at line 754 of file SharedMutexTest.cpp.
References BENCHMARK_SUSPEND, EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, i, folly::test::DeterministicSchedule::join(), now(), folly::pushmi::detail::t, folly::test::DeterministicSchedule::thread(), threads, uint64_t, and folly::fibers::yield().
{
   Lock globalLock;
   Atom<int> globalExclusiveCount(0);
   Atom<int> globalUpgradeCount(0);
   Atom<int> globalSharedCount(0);
   Atom<bool> go(false);
   // clang crashes on access to Atom<> captured by ref in closure
   Atom<int>* globalExclusiveCountPtr = &globalExclusiveCount;
   Atom<int>* globalUpgradeCountPtr = &globalUpgradeCount;
   Atom<int>* globalSharedCountPtr = &globalSharedCount;
   Atom<bool>* goPtr = &go;
   vector<thread> threads(numThreads);
   BENCHMARK_SUSPEND {
     for (size_t t = 0; t < numThreads; ++t) {
       threads[t] = DSched::thread([&, t, numThreads] {
         struct drand48_data buffer;
         srand48_r(t, &buffer);
         bool exclusive = false;
         bool upgrade = false;
         bool shared = false;
         bool ourGlobalTokenUsed = false;
         SharedMutexToken ourGlobalToken;
         Lock privateLock;
         vector<SharedMutexToken> privateTokens;
         while (!goPtr->load()) {
           this_thread::yield();
         }
         for (size_t op = t; op < numOps; op += numThreads) {
           // randVal in [0,1000)
           long randVal;
           lrand48_r(&buffer, &randVal);
           randVal = (long)((randVal * (uint64_t)1000) / 0x7fffffff);
           // make as many assertions as possible about the global state
           if (exclusive) {
             EXPECT_EQ(1, globalExclusiveCountPtr->load(memory_order_acquire));
             EXPECT_EQ(0, globalUpgradeCountPtr->load(memory_order_acquire));
             EXPECT_EQ(0, globalSharedCountPtr->load(memory_order_acquire));
           }
           if (upgrade) {
             EXPECT_EQ(0, globalExclusiveCountPtr->load(memory_order_acquire));
             EXPECT_EQ(1, globalUpgradeCountPtr->load(memory_order_acquire));
           }
           if (shared) {
             EXPECT_EQ(0, globalExclusiveCountPtr->load(memory_order_acquire));
             EXPECT_TRUE(globalSharedCountPtr->load(memory_order_acquire) > 0);
           } else {
             EXPECT_FALSE(ourGlobalTokenUsed);
           }
           // independent 20% chance we do something to the private lock
           if (randVal < 200) {
             // it's okay to take multiple private shared locks because
             // we never take an exclusive lock, so reader versus writer
             // priority doesn't cause deadlocks
             if (randVal < 100 && privateTokens.size() > 0) {
               auto i = randVal % privateTokens.size();
               privateLock.unlock_shared(privateTokens[i]);
               privateTokens.erase(privateTokens.begin() + i);
             } else {
               SharedMutexToken token;
               privateLock.lock_shared(token);
               privateTokens.push_back(token);
             }
             continue;
           }
           // if we've got a lock, the only thing we can do is release it
           // or transform it into a different kind of lock
           if (exclusive) {
             exclusive = false;
             --*globalExclusiveCountPtr;
             if (randVal < 500) {
               globalLock.unlock();
             } else if (randVal < 700) {
               globalLock.unlock_and_lock_shared();
               ++*globalSharedCountPtr;
               shared = true;
             } else if (randVal < 900) {
               globalLock.unlock_and_lock_shared(ourGlobalToken);
               ++*globalSharedCountPtr;
               shared = true;
               ourGlobalTokenUsed = true;
             } else {
               globalLock.unlock_and_lock_upgrade();
               ++*globalUpgradeCountPtr;
               upgrade = true;
             }
           } else if (upgrade) {
             upgrade = false;
             --*globalUpgradeCountPtr;
             if (randVal < 500) {
               globalLock.unlock_upgrade();
             } else if (randVal < 700) {
               globalLock.unlock_upgrade_and_lock_shared();
               ++*globalSharedCountPtr;
               shared = true;
             } else if (randVal < 900) {
               globalLock.unlock_upgrade_and_lock_shared(ourGlobalToken);
               ++*globalSharedCountPtr;
               shared = true;
               ourGlobalTokenUsed = true;
             } else {
               globalLock.unlock_upgrade_and_lock();
               ++*globalExclusiveCountPtr;
               exclusive = true;
             }
           } else if (shared) {
             shared = false;
             --*globalSharedCountPtr;
             if (ourGlobalTokenUsed) {
               globalLock.unlock_shared(ourGlobalToken);
               ourGlobalTokenUsed = false;
             } else {
               globalLock.unlock_shared();
             }
           } else if (randVal < 400) {
             // 40% chance of shared lock with token, 5 ways to get it
             // delta t goes from -1 millis to 7 millis
             auto dt = microseconds(10 * (randVal - 100));
             if (randVal < 400) {
               globalLock.lock_shared(ourGlobalToken);
               shared = true;
             } else if (randVal < 500) {
               shared = globalLock.try_lock_shared(ourGlobalToken);
             } else if (randVal < 600) {
               shared = globalLock.try_lock_shared_for(dt, ourGlobalToken);
             } else if (randVal < 800) {
               shared = globalLock.try_lock_shared_until(
                   system_clock::now() + dt, ourGlobalToken);
             }
             if (shared) {
               ourGlobalTokenUsed = true;
               ++*globalSharedCountPtr;
             }
           } else if (randVal < 800) {
             // 40% chance of shared lock without token
             auto dt = microseconds(10 * (randVal - 100));
             if (randVal < 400) {
               globalLock.lock_shared();
               shared = true;
             } else if (randVal < 500) {
               shared = globalLock.try_lock_shared();
             } else if (randVal < 600) {
               shared = globalLock.try_lock_shared_for(dt);
             } else if (randVal < 800) {
               shared =
                   globalLock.try_lock_shared_until(system_clock::now() + dt);
             }
             if (shared) {
               ++*globalSharedCountPtr;
             }
           } else if (randVal < 900) {
             // 10% change of upgrade lock
             globalLock.lock_upgrade();
             upgrade = true;
             ++*globalUpgradeCountPtr;
           } else {
             // 10% chance of exclusive lock, 5 ways to get it
             // delta t goes from -1 millis to 9 millis
             auto dt = microseconds(100 * (randVal - 910));
             if (randVal < 400) {
               globalLock.lock();
               exclusive = true;
             } else if (randVal < 500) {
               exclusive = globalLock.try_lock();
             } else if (randVal < 600) {
               exclusive = globalLock.try_lock_for(dt);
             } else if (randVal < 700) {
               exclusive = globalLock.try_lock_until(steady_clock::now() + dt);
             } else {
               exclusive = globalLock.try_lock_until(system_clock::now() + dt);
             }
             if (exclusive) {
               ++*globalExclusiveCountPtr;
             }
           }
         }
         if (exclusive) {
           --*globalExclusiveCountPtr;
           globalLock.unlock();
         }
         if (upgrade) {
           --*globalUpgradeCountPtr;
           globalLock.unlock_upgrade();
         }
         if (shared) {
           --*globalSharedCountPtr;
           if (ourGlobalTokenUsed) {
             globalLock.unlock_shared(ourGlobalToken);
             ourGlobalTokenUsed = false;
           } else {
             globalLock.unlock_shared();
           }
         }
         for (auto& token : privateTokens) {
           privateLock.unlock_shared(token);
         }
       });
     }
   }
   go.store(true);
   for (auto& thr : threads) {
     DSched::join(thr);
   }
 }
template<typename Lock > void runBasicHoldersTest ()
Definition at line 86 of file SharedMutexTest.cpp.
References EXPECT_FALSE, EXPECT_TRUE, folly::lock(), and folly::gen::move.
{
   Lock lock;
   SharedMutexToken token;
   {
     // create an exclusive write lock via holder
     typename Lock::WriteHolder holder(lock);
     EXPECT_FALSE(lock.try_lock());
     EXPECT_FALSE(lock.try_lock_shared(token));
     // move ownership to another write holder via move constructor
     typename Lock::WriteHolder holder2(std::move(holder));
     EXPECT_FALSE(lock.try_lock());
     EXPECT_FALSE(lock.try_lock_shared(token));
     // move ownership to another write holder via assign operator
     typename Lock::WriteHolder holder3(nullptr);
     holder3 = std::move(holder2);
     EXPECT_FALSE(lock.try_lock());
     EXPECT_FALSE(lock.try_lock_shared(token));
     // downgrade from exclusive to upgrade lock via move constructor
     typename Lock::UpgradeHolder holder4(std::move(holder3));
     // ensure we can lock from a shared source
     EXPECT_FALSE(lock.try_lock());
     EXPECT_TRUE(lock.try_lock_shared(token));
     lock.unlock_shared(token);
     // promote from upgrade to exclusive lock via move constructor
     typename Lock::WriteHolder holder5(std::move(holder4));
     EXPECT_FALSE(lock.try_lock());
     EXPECT_FALSE(lock.try_lock_shared(token));
     // downgrade exclusive to shared lock via move constructor
     typename Lock::ReadHolder holder6(std::move(holder5));
     // ensure we can lock from another shared source
     EXPECT_FALSE(lock.try_lock());
     EXPECT_TRUE(lock.try_lock_shared(token));
     lock.unlock_shared(token);
   }
   {
     typename Lock::WriteHolder holder(lock);
     EXPECT_FALSE(lock.try_lock());
   }
   {
     typename Lock::ReadHolder holder(lock);
     typename Lock::ReadHolder holder2(lock);
     typename Lock::UpgradeHolder holder3(lock);
   }
   {
     typename Lock::UpgradeHolder holder(lock);
     typename Lock::ReadHolder holder2(lock);
     typename Lock::ReadHolder holder3(std::move(holder));
   }
 }
template<typename Lock > void runBasicTest ()
Definition at line 45 of file SharedMutexTest.cpp.
References EXPECT_FALSE, EXPECT_TRUE, and folly::lock().
                     {
   Lock lock;
   SharedMutexToken token1;
   SharedMutexToken token2;
   SharedMutexToken token3;
   EXPECT_TRUE(lock.try_lock());
   EXPECT_FALSE(lock.try_lock());
   EXPECT_FALSE(lock.try_lock_shared(token1));
   lock.unlock();
   EXPECT_TRUE(lock.try_lock_shared(token1));
   EXPECT_FALSE(lock.try_lock());
   EXPECT_TRUE(lock.try_lock_shared(token2));
   lock.lock_shared(token3);
   lock.unlock_shared(token3);
   lock.unlock_shared(token2);
   lock.unlock_shared(token1);
   lock.lock();
   lock.unlock();
   lock.lock_shared(token1);
   lock.lock_shared(token2);
   lock.unlock_shared(token1);
   lock.unlock_shared(token2);
   lock.lock();
   lock.unlock_and_lock_shared(token1);
   lock.lock_shared(token2);
   lock.unlock_shared(token2);
   lock.unlock_shared(token1);
 }
template<typename Lock > void runBasicUpgradeTest ()
Definition at line 319 of file SharedMutexTest.cpp.
References EXPECT_FALSE, EXPECT_TRUE, and folly::lock().
{
   Lock lock;
   typename Lock::Token token1;
   typename Lock::Token token2;
   lock.lock_upgrade();
   EXPECT_FALSE(lock.try_lock());
   EXPECT_TRUE(lock.try_lock_shared(token1));
   lock.unlock_shared(token1);
   lock.unlock_upgrade();
   lock.lock_upgrade();
   lock.unlock_upgrade_and_lock();
   EXPECT_FALSE(lock.try_lock_shared(token1));
   lock.unlock();
   lock.lock_upgrade();
   lock.unlock_upgrade_and_lock_shared(token1);
   lock.lock_upgrade();
   lock.unlock_upgrade_and_lock_shared(token2);
   lock.unlock_shared(token1);
   lock.unlock_shared(token2);
   lock.lock();
   lock.unlock_and_lock_upgrade();
   EXPECT_TRUE(lock.try_lock_shared(token1));
   lock.unlock_upgrade();
   lock.unlock_shared(token1);
 }
template<template< typename > class Atom, typename Lock , typename Locker > static void runContendedReaders (size_t numOps, size_t numThreads, bool useSeparateLocks) static
Definition at line 530 of file SharedMutexTest.cpp.
References BENCHMARK_SUSPEND, folly::copy(), folly::doNotOptimizeAway(), folly::test::DeterministicSchedule::join(), folly::lock(), Locker::lock_shared(), folly::pushmi::detail::t, folly::test::DeterministicSchedule::thread(), threads, Locker::unlock_shared(), and folly::fibers::yield().
{
   char padding1[64];
   (void)padding1;
   Lock globalLock;
   int valueProtectedByLock = 10;
   char padding2[64];
   (void)padding2;
   Atom<bool> go(false);
   Atom<bool>* goPtr = &go; // workaround for clang bug
   vector<thread> threads(numThreads);
   BENCHMARK_SUSPEND {
     for (size_t t = 0; t < numThreads; ++t) {
       threads[t] = DSched::thread([&, t, numThreads] {
         Lock privateLock;
         Lock* lock = useSeparateLocks ? &privateLock : &globalLock;
         Locker locker;
         while (!goPtr->load()) {
           this_thread::yield();
         }
         for (size_t op = t; op < numOps; op += numThreads) {
           locker.lock_shared(lock);
           // note: folly::doNotOptimizeAway reads and writes to its arg,
           // so the following two lines are very different than a call
           // to folly::doNotOptimizeAway(valueProtectedByLock);
           auto copy = valueProtectedByLock;
           folly::doNotOptimizeAway(copy);
           locker.unlock_shared(lock);
         }
       });
     }
   }
   go.store(true);
   for (auto& thr : threads) {
     DSched::join(thr);
   }
 }
template<typename Lock > void runFailingTryTimeoutTest ()
Definition at line 247 of file SharedMutexTest.cpp.
References EXPECT_FALSE, EXPECT_TRUE, funcHasDuration(), folly::lock(), and now().
{
   Lock lock;
   lock.lock();
   EXPECT_TRUE(funcHasDuration(milliseconds(10), [&] {
     EXPECT_FALSE(lock.try_lock_for(milliseconds(10)));
   }));
   EXPECT_TRUE(funcHasDuration(milliseconds(10), [&] {
     typename Lock::Token token;
     EXPECT_FALSE(lock.try_lock_shared_for(milliseconds(10), token));
   }));
   EXPECT_TRUE(funcHasDuration(milliseconds(10), [&] {
     EXPECT_FALSE(lock.try_lock_upgrade_for(milliseconds(10)));
   }));
   EXPECT_TRUE(funcHasDuration(milliseconds(10), [&] {
     EXPECT_FALSE(lock.try_lock_until(steady_clock::now() + milliseconds(10)));
   }));
   EXPECT_TRUE(funcHasDuration(milliseconds(10), [&] {
     typename Lock::Token token;
     EXPECT_FALSE(lock.try_lock_shared_until(
         steady_clock::now() + milliseconds(10), token));
   }));
   EXPECT_TRUE(funcHasDuration(milliseconds(10), [&] {
     EXPECT_FALSE(
         lock.try_lock_upgrade_until(steady_clock::now() + milliseconds(10)));
   }));
   EXPECT_TRUE(funcHasDuration(milliseconds(10), [&] {
     EXPECT_FALSE(lock.try_lock_until(system_clock::now() + milliseconds(10)));
   }));
   EXPECT_TRUE(funcHasDuration(milliseconds(10), [&] {
     typename Lock::Token token;
     EXPECT_FALSE(lock.try_lock_shared_until(
         system_clock::now() + milliseconds(10), token));
   }));
   EXPECT_TRUE(funcHasDuration(milliseconds(10), [&] {
     EXPECT_FALSE(
         lock.try_lock_upgrade_until(system_clock::now() + milliseconds(10)));
   }));
   lock.unlock();
   lock.lock_shared();
   EXPECT_TRUE(funcHasDuration(milliseconds(10), [&] {
     EXPECT_FALSE(lock.try_lock_for(milliseconds(10)));
   }));
   EXPECT_TRUE(funcHasDuration(milliseconds(10), [&] {
     EXPECT_FALSE(lock.try_lock_until(steady_clock::now() + milliseconds(10)));
   }));
   EXPECT_TRUE(funcHasDuration(milliseconds(10), [&] {
     EXPECT_FALSE(lock.try_lock_until(system_clock::now() + milliseconds(10)));
   }));
   lock.unlock_shared();
   lock.lock();
   for (int p = 0; p < 8; ++p) {
     EXPECT_FALSE(lock.try_lock_for(nanoseconds(1 << p)));
   }
   lock.unlock();
   for (int p = 0; p < 8; ++p) {
     typename Lock::ReadHolder holder1(lock);
     typename Lock::ReadHolder holder2(lock);
     typename Lock::ReadHolder holder3(lock);
     EXPECT_FALSE(lock.try_lock_for(nanoseconds(1 << p)));
   }
 }
template<typename Lock > void runManyReadLocksTestWithoutTokens ()
Definition at line 179 of file SharedMutexTest.cpp.
References EXPECT_TRUE, i, and folly::lock().
{
   Lock lock;
   for (int i = 0; i < 1000; ++i) {
     EXPECT_TRUE(lock.try_lock_shared());
   }
   for (int i = 0; i < 1000; ++i) {
     lock.unlock_shared();
   }
   EXPECT_TRUE(lock.try_lock());
   lock.unlock();
 }
template<typename Lock > void runManyReadLocksTestWithTokens ()
Definition at line 154 of file SharedMutexTest.cpp.
References EXPECT_TRUE, i, folly::lock(), and tokens.
{
   Lock lock;
   vector<SharedMutexToken> tokens;
   for (int i = 0; i < 1000; ++i) {
     tokens.emplace_back();
     EXPECT_TRUE(lock.try_lock_shared(tokens.back()));
   }
   for (auto& token : tokens) {
     lock.unlock_shared(token);
   }
   EXPECT_TRUE(lock.try_lock());
   lock.unlock();
 }
template<template< typename > class Atom, typename Lock , typename Locker > static void runMixed (size_t numOps, size_t numThreads, double writeFraction, bool useSeparateLocks) static
Definition at line 618 of file SharedMutexTest.cpp.
References BENCHMARK_SUSPEND, folly::doNotOptimizeAway(), folly::test::DeterministicSchedule::join(), Locker::lock(), folly::lock(), Locker::lock_shared(), folly::pushmi::detail::t, folly::test::DeterministicSchedule::thread(), threads, Locker::unlock(), Locker::unlock_shared(), and folly::fibers::yield().
{
   char padding1[64];
   (void)padding1;
   Lock globalLock;
   int valueProtectedByLock = 0;
   char padding2[64];
   (void)padding2;
   Atom<bool> go(false);
   Atom<bool>* goPtr = &go; // workaround for clang bug
   vector<thread> threads(numThreads);
   BENCHMARK_SUSPEND {
     for (size_t t = 0; t < numThreads; ++t) {
       threads[t] = DSched::thread([&, t, numThreads] {
         struct drand48_data buffer;
         srand48_r(t, &buffer);
         long writeThreshold = writeFraction * 0x7fffffff;
         Lock privateLock;
         Lock* lock = useSeparateLocks ? &privateLock : &globalLock;
         Locker locker;
         while (!goPtr->load()) {
           this_thread::yield();
         }
         for (size_t op = t; op < numOps; op += numThreads) {
           long randVal;
           lrand48_r(&buffer, &randVal);
           bool writeOp = randVal < writeThreshold;
           if (writeOp) {
             locker.lock(lock);
             if (!useSeparateLocks) {
               ++valueProtectedByLock;
             }
             locker.unlock(lock);
           } else {
             locker.lock_shared(lock);
             auto v = valueProtectedByLock;
             folly::doNotOptimizeAway(v);
             locker.unlock_shared(lock);
           }
         }
       });
     }
   }
   go.store(true);
   for (auto& thr : threads) {
     DSched::join(thr);
   }
 }
template<typename Lock , template< typename > class Atom = atomic> static void runPingPong (size_t numRounds, size_t burnCount) static
Definition at line 1302 of file SharedMutexTest.cpp.
References BENCHMARK_SUSPEND, burn(), folly::gen::first, i, folly::test::DeterministicSchedule::join(), folly::ssl::detail::locks(), folly::test::DeterministicSchedule::thread(), threads, and folly::fibers::yield().
{
   char padding1[56];
   (void)padding1;
   pair<Lock, char[56]> locks[3];
   char padding2[56];
   (void)padding2;
   Atom<int> avail(0);
   auto availPtr = &avail; // workaround for clang crash
   Atom<bool> go(false);
   auto goPtr = &go; // workaround for clang crash
   vector<thread> threads(2);
   locks[0].first.lock();
   locks[1].first.lock();
   locks[2].first.lock_shared();
   BENCHMARK_SUSPEND {
     threads[0] = DSched::thread([&] {
       ++*availPtr;
       while (!goPtr->load()) {
         this_thread::yield();
       }
       for (size_t i = 0; i < numRounds; ++i) {
         locks[i % 3].first.unlock();
         locks[(i + 2) % 3].first.lock();
         burn(burnCount);
       }
     });
     threads[1] = DSched::thread([&] {
       ++*availPtr;
       while (!goPtr->load()) {
         this_thread::yield();
       }
       for (size_t i = 0; i < numRounds; ++i) {
         locks[i % 3].first.lock_shared();
         burn(burnCount);
         locks[(i + 2) % 3].first.unlock_shared();
       }
     });
     while (avail.load() < 2) {
       this_thread::yield();
     }
   }
   go.store(true);
   for (auto& thr : threads) {
     DSched::join(thr);
   }
   locks[numRounds % 3].first.unlock();
   locks[(numRounds + 1) % 3].first.unlock();
   locks[(numRounds + 2) % 3].first.unlock_shared();
 }
template<typename > class Atom static void runRemoteUnlock (size_t numOps, double preWriteFraction, double preUpgradeFraction, size_t numSendingThreads, size_t numReceivingThreads)
Definition at line 1149 of file SharedMutexTest.cpp.
References Atom, BENCHMARK_SUSPEND, folly::test::DeterministicSchedule::join(), folly::gen::move, folly::none, folly::pushmi::detail::t, folly::test::DeterministicSchedule::thread(), threads, and folly::fibers::yield().
{
   Lock globalLock;
   MPMCQueue<boost::optional<boost::optional<SharedMutexToken>>, Atom> queue(10);
   auto queuePtr = &queue; // workaround for clang crash
   Atom<bool> go(false);
   auto goPtr = &go; // workaround for clang crash
   Atom<int> pendingSenders(numSendingThreads);
   auto pendingSendersPtr = &pendingSenders; // workaround for clang crash
   vector<thread> threads(numSendingThreads + numReceivingThreads);
   BENCHMARK_SUSPEND {
     for (size_t t = 0; t < threads.size(); ++t) {
       threads[t] = DSched::thread([&, t, numSendingThreads] {
         if (t >= numSendingThreads) {
           // we're a receiver
           typename decltype(queue)::value_type elem;
           while (true) {
             queuePtr->blockingRead(elem);
             if (!elem) {
               // EOF, pass the EOF token
               queuePtr->blockingWrite(std::move(elem));
               break;
             }
             if (*elem) {
               globalLock.unlock_shared(**elem);
             } else {
               globalLock.unlock_shared();
             }
           }
           return;
         }
         // else we're a sender
         struct drand48_data buffer;
         srand48_r(t, &buffer);
         while (!goPtr->load()) {
           this_thread::yield();
         }
         for (size_t op = t; op < numOps; op += numSendingThreads) {
           long unscaledRandVal;
           lrand48_r(&buffer, &unscaledRandVal);
           // randVal in [0,1]
           double randVal = ((double)unscaledRandVal) / 0x7fffffff;
           // extract a bit and rescale
           bool useToken = randVal >= 0.5;
           randVal = (randVal - (useToken ? 0.5 : 0.0)) * 2;
           boost::optional<SharedMutexToken> maybeToken;
           if (useToken) {
             SharedMutexToken token;
             if (randVal < preWriteFraction) {
               globalLock.lock();
               globalLock.unlock_and_lock_shared(token);
             } else if (randVal < preWriteFraction + preUpgradeFraction / 2) {
               globalLock.lock_upgrade();
               globalLock.unlock_upgrade_and_lock_shared(token);
             } else if (randVal < preWriteFraction + preUpgradeFraction) {
               globalLock.lock_upgrade();
               globalLock.unlock_upgrade_and_lock();
               globalLock.unlock_and_lock_shared(token);
             } else {
               globalLock.lock_shared(token);
             }
             maybeToken = token;
           } else {
             if (randVal < preWriteFraction) {
               globalLock.lock();
               globalLock.unlock_and_lock_shared();
             } else if (randVal < preWriteFraction + preUpgradeFraction / 2) {
               globalLock.lock_upgrade();
               globalLock.unlock_upgrade_and_lock_shared();
             } else if (randVal < preWriteFraction + preUpgradeFraction) {
               globalLock.lock_upgrade();
               globalLock.unlock_upgrade_and_lock();
               globalLock.unlock_and_lock_shared();
             } else {
               globalLock.lock_shared();
             }
           }
           // blockingWrite is emplace-like, so this automatically adds
           // another level of wrapping
           queuePtr->blockingWrite(maybeToken);
         }
         if (--*pendingSendersPtr == 0) {
           queuePtr->blockingWrite(boost::none);
         }
       });
     }
   }
   go.store(true);
   for (auto& thr : threads) {
     DSched::join(thr);
   }
 }
template<typename Lock > void runTimeoutInPastTest ()
Definition at line 202 of file SharedMutexTest.cpp.
References EXPECT_TRUE, folly::lock(), and now().
{
   Lock lock;
   EXPECT_TRUE(lock.try_lock_for(milliseconds(0)));
   lock.unlock();
   EXPECT_TRUE(lock.try_lock_for(milliseconds(-1)));
   lock.unlock();
   EXPECT_TRUE(lock.try_lock_shared_for(milliseconds(0)));
   lock.unlock_shared();
   EXPECT_TRUE(lock.try_lock_shared_for(milliseconds(-1)));
   lock.unlock_shared();
   EXPECT_TRUE(lock.try_lock_until(system_clock::now() - milliseconds(1)));
   lock.unlock();
   EXPECT_TRUE(
       lock.try_lock_shared_until(system_clock::now() - milliseconds(1)));
   lock.unlock_shared();
   EXPECT_TRUE(lock.try_lock_until(steady_clock::now() - milliseconds(1)));
   lock.unlock();
   EXPECT_TRUE(
       lock.try_lock_shared_until(steady_clock::now() - milliseconds(1)));
   lock.unlock_shared();
 }
static void shmtx_r_bare (uint32_t numOps, size_t numThreads, double writeFraction, bool useSeparateLocks) static
Definition at line 708 of file SharedMutexTest.cpp.
{
   runMixed<atomic, SharedMutexReadPriority, Locker>(
       numOps, numThreads, writeFraction, useSeparateLocks);
 }
static void shmtx_r_bare_ping_pong (size_t n, size_t scale, size_t burnCount) static
Definition at line 1365 of file SharedMutexTest.cpp.
{
   runPingPong<SharedMutexReadPriority>(n / scale, burnCount);
 }
static void shmtx_r_bare_reads (uint32_t numOps, size_t numThreads, bool useSeparateLocks) static
Definition at line 594 of file SharedMutexTest.cpp.
{
   runContendedReaders<atomic, SharedMutexReadPriority, Locker>(
       numOps, numThreads, useSeparateLocks);
 }
static void shmtx_rd_pri (uint32_t numOps, size_t numThreads, double writeFraction, bool useSeparateLocks) static
Definition at line 699 of file SharedMutexTest.cpp.
{
   runMixed<atomic, SharedMutexReadPriority, TokenLocker>(
       numOps, numThreads, writeFraction, useSeparateLocks);
 }
static void shmtx_rd_pri_reads (uint32_t numOps, size_t numThreads, bool useSeparateLocks) static
Definition at line 588 of file SharedMutexTest.cpp.
{
   runContendedReaders<atomic, SharedMutexReadPriority, TokenLocker>(
       numOps, numThreads, useSeparateLocks);
 }
static void shmtx_w_bare (uint32_t numOps, size_t numThreads, double writeFraction, bool useSeparateLocks) static
Definition at line 690 of file SharedMutexTest.cpp.
{
   runMixed<atomic, SharedMutexWritePriority, Locker>(
       numOps, numThreads, writeFraction, useSeparateLocks);
 }
static void shmtx_w_bare_ping_pong (size_t n, size_t scale, size_t burnCount) static
Definition at line 1361 of file SharedMutexTest.cpp.
{
   runPingPong<SharedMutexWritePriority>(n / scale, burnCount);
 }
static void shmtx_w_bare_reads (uint32_t numOps, size_t numThreads, bool useSeparateLocks) static
Definition at line 582 of file SharedMutexTest.cpp.
{
   runContendedReaders<atomic, SharedMutexWritePriority, Locker>(
       numOps, numThreads, useSeparateLocks);
 }
static void shmtx_wr_pri (uint32_t numOps, size_t numThreads, double writeFraction, bool useSeparateLocks) static
Definition at line 681 of file SharedMutexTest.cpp.
{
   runMixed<atomic, SharedMutexWritePriority, TokenLocker>(
       numOps, numThreads, writeFraction, useSeparateLocks);
 }
static void shmtx_wr_pri_reads (uint32_t numOps, size_t numThreads, bool useSeparateLocks) static
Definition at line 576 of file SharedMutexTest.cpp.
{
   runContendedReaders<atomic, SharedMutexWritePriority, TokenLocker>(
       numOps, numThreads, useSeparateLocks);
 }
TEST (SharedMutex , basic)
Definition at line 79 of file SharedMutexTest.cpp.
{
   runBasicTest<SharedMutexReadPriority>();
   runBasicTest<SharedMutexWritePriority>();
   runBasicTest<SharedMutexSuppressTSAN>();
 }
TEST (SharedMutex , basic_holders)
Definition at line 147 of file SharedMutexTest.cpp.
{
   runBasicHoldersTest<SharedMutexReadPriority>();
   runBasicHoldersTest<SharedMutexWritePriority>();
   runBasicHoldersTest<SharedMutexSuppressTSAN>();
 }
TEST (SharedMutex , many_read_locks_with_tokens)
Definition at line 169 of file SharedMutexTest.cpp.
References folly::kIsSanitizeThread, and SKIP_IF.
{
   // This test fails in an assertion in the TSAN library because there are too
   // many mutexes
   SKIP_IF(folly::kIsSanitizeThread);
   runManyReadLocksTestWithTokens<SharedMutexReadPriority>();
   runManyReadLocksTestWithTokens<SharedMutexWritePriority>();
   runManyReadLocksTestWithTokens<SharedMutexSuppressTSAN>();
 }
TEST (SharedMutex , many_read_locks_without_tokens)
Definition at line 192 of file SharedMutexTest.cpp.
References folly::kIsSanitizeThread, and SKIP_IF.
{
   // This test fails in an assertion in the TSAN library because there are too
   // many mutexes
   SKIP_IF(folly::kIsSanitizeThread);
   runManyReadLocksTestWithoutTokens<SharedMutexReadPriority>();
   runManyReadLocksTestWithoutTokens<SharedMutexWritePriority>();
   runManyReadLocksTestWithoutTokens<SharedMutexSuppressTSAN>();
 }
TEST (SharedMutex , timeout_in_past)
Definition at line 225 of file SharedMutexTest.cpp.
{
   runTimeoutInPastTest<SharedMutexReadPriority>();
   runTimeoutInPastTest<SharedMutexWritePriority>();
   runTimeoutInPastTest<SharedMutexSuppressTSAN>();
 }
TEST (SharedMutex , failing_try_timeout)
Definition at line 312 of file SharedMutexTest.cpp.
{
   runFailingTryTimeoutTest<SharedMutexReadPriority>();
   runFailingTryTimeoutTest<SharedMutexWritePriority>();
   runFailingTryTimeoutTest<SharedMutexSuppressTSAN>();
 }
TEST (SharedMutex , basic_upgrade_tests)
Definition at line 349 of file SharedMutexTest.cpp.
{
   runBasicUpgradeTest<SharedMutexReadPriority>();
   runBasicUpgradeTest<SharedMutexWritePriority>();
   runBasicUpgradeTest<SharedMutexSuppressTSAN>();
 }
TEST (SharedMutex , read_has_prio)
Definition at line 355 of file SharedMutexTest.cpp.
References EXPECT_FALSE, EXPECT_TRUE, folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::lock(), folly::lock(), folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::lock_shared(), folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::try_lock_shared(), folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::try_lock_upgrade(), folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::unlock(), folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::unlock_shared(), folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::unlock_upgrade(), and folly::fibers::yield().
{
   SharedMutexReadPriority lock;
   SharedMutexToken token1;
   SharedMutexToken token2;
   lock.lock_shared(token1);
   bool exclusiveAcquired = false;
   auto writer = thread([&] {
     lock.lock();
     exclusiveAcquired = true;
     lock.unlock();
   });
   // lock() can't complete until we unlock token1, but it should stake
   // its claim with regards to other exclusive or upgrade locks.  We can
   // use try_lock_upgrade to poll for that eventuality.
   while (lock.try_lock_upgrade()) {
     lock.unlock_upgrade();
     this_thread::yield();
   }
   EXPECT_FALSE(exclusiveAcquired);
   // Even though lock() is stuck we should be able to get token2
   EXPECT_TRUE(lock.try_lock_shared(token2));
   lock.unlock_shared(token1);
   lock.unlock_shared(token2);
   writer.join();
   EXPECT_TRUE(exclusiveAcquired);
 }
TEST (SharedMutex , write_has_prio)
Definition at line 384 of file SharedMutexTest.cpp.
References folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::lock(), folly::lock(), folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::lock_shared(), folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::try_lock_shared(), folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::unlock(), folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::unlock_shared(), and folly::fibers::yield().
{
   SharedMutexWritePriority lock;
   SharedMutexToken token1;
   SharedMutexToken token2;
   lock.lock_shared(token1);
   auto writer = thread([&] {
     lock.lock();
     lock.unlock();
   });
   // eventually lock() should block readers
   while (lock.try_lock_shared(token2)) {
     lock.unlock_shared(token2);
     this_thread::yield();
   }
   lock.unlock_shared(token1);
   writer.join();
 }
TEST (SharedMutex , deterministic_concurrent_readers_of_one_lock_read_prio)
Definition at line 974 of file SharedMutexTest.cpp.
References folly::test::DeterministicSchedule::uniform().
{
   for (int pass = 0; pass < 3; ++pass) {
     DSched sched(DSched::uniform(pass));
     runContendedReaders<DeterministicAtomic, DSharedMutexReadPriority, Locker>(
         1000, 3, false);
   }
 }
TEST (SharedMutex , deterministic_concurrent_readers_of_one_lock_write_prio)
Definition at line 982 of file SharedMutexTest.cpp.
References folly::test::DeterministicSchedule::uniform().
{
   for (int pass = 0; pass < 3; ++pass) {
     DSched sched(DSched::uniform(pass));
     runContendedReaders<DeterministicAtomic, DSharedMutexWritePriority, Locker>(
         1000, 3, false);
   }
 }
TEST (SharedMutex , concurrent_readers_of_one_lock_read_prio)
Definition at line 990 of file SharedMutexTest.cpp.
{
   for (int pass = 0; pass < 10; ++pass) {
     runContendedReaders<atomic, SharedMutexReadPriority, Locker>(
         100000, 32, false);
   }
 }
TEST (SharedMutex , concurrent_readers_of_one_lock_write_prio)
Definition at line 997 of file SharedMutexTest.cpp.
{
   for (int pass = 0; pass < 10; ++pass) {
     runContendedReaders<atomic, SharedMutexWritePriority, Locker>(
         100000, 32, false);
   }
 }
TEST (SharedMutex , deterministic_readers_of_concurrent_locks_read_prio)
Definition at line 1004 of file SharedMutexTest.cpp.
References folly::test::DeterministicSchedule::uniform().
{
   for (int pass = 0; pass < 3; ++pass) {
     DSched sched(DSched::uniform(pass));
     runContendedReaders<DeterministicAtomic, DSharedMutexReadPriority, Locker>(
         1000, 3, true);
   }
 }
TEST (SharedMutex , deterministic_readers_of_concurrent_locks_write_prio)
Definition at line 1012 of file SharedMutexTest.cpp.
References folly::test::DeterministicSchedule::uniform().
{
   for (int pass = 0; pass < 3; ++pass) {
     DSched sched(DSched::uniform(pass));
     runContendedReaders<DeterministicAtomic, DSharedMutexWritePriority, Locker>(
         1000, 3, true);
   }
 }
TEST (SharedMutex , readers_of_concurrent_locks_read_prio)
Definition at line 1020 of file SharedMutexTest.cpp.
{
   for (int pass = 0; pass < 10; ++pass) {
     runContendedReaders<atomic, SharedMutexReadPriority, TokenLocker>(
         100000, 32, true);
   }
 }
TEST (SharedMutex , readers_of_concurrent_locks_write_prio)
Definition at line 1027 of file SharedMutexTest.cpp.
{
   for (int pass = 0; pass < 10; ++pass) {
     runContendedReaders<atomic, SharedMutexWritePriority, TokenLocker>(
         100000, 32, true);
   }
 }
TEST (SharedMutex , deterministic_mixed_mostly_read_read_prio)
Definition at line 1034 of file SharedMutexTest.cpp.
References folly::test::DeterministicSchedule::uniform().
{
   for (int pass = 0; pass < 3; ++pass) {
     DSched sched(DSched::uniform(pass));
     runMixed<DeterministicAtomic, DSharedMutexReadPriority, Locker>(
         1000, 3, 0.1, false);
   }
 }
TEST (SharedMutex , deterministic_mixed_mostly_read_write_prio)
Definition at line 1042 of file SharedMutexTest.cpp.
References folly::test::DeterministicSchedule::uniform().
{
   for (int pass = 0; pass < 3; ++pass) {
     DSched sched(DSched::uniform(pass));
     runMixed<DeterministicAtomic, DSharedMutexWritePriority, Locker>(
         1000, 3, 0.1, false);
   }
 }
TEST (SharedMutex , mixed_mostly_read_read_prio)
Definition at line 1050 of file SharedMutexTest.cpp.
{
   for (int pass = 0; pass < 5; ++pass) {
     runMixed<atomic, SharedMutexReadPriority, TokenLocker>(
         10000, 32, 0.1, false);
   }
 }
TEST (SharedMutex , mixed_mostly_read_write_prio)
Definition at line 1057 of file SharedMutexTest.cpp.
{
   for (int pass = 0; pass < 5; ++pass) {
     runMixed<atomic, SharedMutexWritePriority, TokenLocker>(
         10000, 32, 0.1, false);
   }
 }
TEST (SharedMutex , deterministic_mixed_mostly_write_read_prio)
Definition at line 1064 of file SharedMutexTest.cpp.
References folly::test::DeterministicSchedule::uniform().
{
   for (int pass = 0; pass < 1; ++pass) {
     DSched sched(DSched::uniform(pass));
     runMixed<DeterministicAtomic, DSharedMutexReadPriority, TokenLocker>(
         1000, 10, 0.9, false);
   }
 }
TEST (SharedMutex , deterministic_mixed_mostly_write_write_prio)
Definition at line 1072 of file SharedMutexTest.cpp.
References folly::test::DeterministicSchedule::uniform().
{
   for (int pass = 0; pass < 1; ++pass) {
     DSched sched(DSched::uniform(pass));
     runMixed<DeterministicAtomic, DSharedMutexWritePriority, TokenLocker>(
         1000, 10, 0.9, false);
   }
 }
TEST (SharedMutex , deterministic_lost_wakeup_write_prio)
Definition at line 1080 of file SharedMutexTest.cpp.
References folly::test::DeterministicSchedule::uniformSubset().
{
   for (int pass = 0; pass < 10; ++pass) {
     DSched sched(DSched::uniformSubset(pass, 2, 200));
     runMixed<DeterministicAtomic, DSharedMutexWritePriority, TokenLocker>(
         1000, 3, 1.0, false);
   }
 }
TEST (SharedMutex , mixed_mostly_write_read_prio)
Definition at line 1097 of file SharedMutexTest.cpp.
References adjustReps(), and folly::kIsSanitizeAddress.
{
   for (int pass = 0; pass < (folly::kIsSanitizeAddress ? 1 : 5); ++pass) {
     runMixed<atomic, SharedMutexReadPriority, TokenLocker>(
         adjustReps(50000), adjustReps(300), 0.9, false);
   }
 }
TEST (SharedMutex , mixed_mostly_write_write_prio)
Definition at line 1104 of file SharedMutexTest.cpp.
References adjustReps(), and folly::kIsSanitizeAddress.
{
   for (int pass = 0; pass < (folly::kIsSanitizeAddress ? 1 : 5); ++pass) {
     runMixed<atomic, SharedMutexWritePriority, TokenLocker>(
         adjustReps(50000), adjustReps(300), 0.9, false);
   }
 }
TEST (SharedMutex , deterministic_all_ops_read_prio)
Definition at line 1111 of file SharedMutexTest.cpp.
References folly::test::DeterministicSchedule::uniform().
{
   for (int pass = 0; pass < 5; ++pass) {
     DSched sched(DSched::uniform(pass));
     runAllAndValidate<DSharedMutexReadPriority, DeterministicAtomic>(1000, 8);
   }
 }
TEST (SharedMutex , deterministic_all_ops_write_prio)
Definition at line 1118 of file SharedMutexTest.cpp.
References folly::kIsSanitizeThread, SKIP_IF, and folly::test::DeterministicSchedule::uniform().
{
   // This test fails in TSAN because of noisy lock ordering inversions.
   SKIP_IF(folly::kIsSanitizeThread);
   for (int pass = 0; pass < 5; ++pass) {
     DSched sched(DSched::uniform(pass));
     runAllAndValidate<DSharedMutexWritePriority, DeterministicAtomic>(1000, 8);
   }
 }
TEST (SharedMutex , all_ops_read_prio)
Definition at line 1127 of file SharedMutexTest.cpp.
{
   for (int pass = 0; pass < 5; ++pass) {
     runAllAndValidate<SharedMutexReadPriority, atomic>(100000, 32);
   }
 }
TEST (SharedMutex , all_ops_write_prio)
Definition at line 1133 of file SharedMutexTest.cpp.
References Atom, FOLLY_ASSUME_FBVECTOR_COMPATIBLE(), folly::kIsSanitizeThread, and SKIP_IF.
{
   // This test fails in TSAN because of noisy lock ordering inversions.
   SKIP_IF(folly::kIsSanitizeThread);
   for (int pass = 0; pass < 5; ++pass) {
     runAllAndValidate<SharedMutexWritePriority, atomic>(100000, 32);
   }
 }
TEST (SharedMutex , deterministic_remote_write_prio)
Definition at line 1256 of file SharedMutexTest.cpp.
References folly::kIsSanitizeThread, SKIP_IF, and folly::test::DeterministicSchedule::uniform().
{
   // This test fails in an assertion in the TSAN library because there are too
   // many mutexes
   SKIP_IF(folly::kIsSanitizeThread);
   for (int pass = 0; pass < 1; ++pass) {
     DSched sched(DSched::uniform(pass));
     runRemoteUnlock<DSharedMutexWritePriority, DeterministicAtomic>(
         500, 0.1, 0.1, 5, 5);
   }
 }
TEST (SharedMutex , deterministic_remote_read_prio)
Definition at line 1267 of file SharedMutexTest.cpp.
References folly::test::DeterministicSchedule::uniform().
{
   for (int pass = 0; pass < 1; ++pass) {
     DSched sched(DSched::uniform(pass));
     runRemoteUnlock<DSharedMutexReadPriority, DeterministicAtomic>(
         500, 0.1, 0.1, 5, 5);
   }
 }
TEST (SharedMutex , remote_write_prio)
Definition at line 1275 of file SharedMutexTest.cpp.
References folly::kIsSanitizeThread, and SKIP_IF.
{
   // This test fails in an assertion in the TSAN library because there are too
   // many mutexes
   SKIP_IF(folly::kIsSanitizeThread);
   for (int pass = 0; pass < 10; ++pass) {
     runRemoteUnlock<SharedMutexWritePriority, atomic>(100000, 0.1, 0.1, 5, 5);
   }
 }
TEST (SharedMutex , remote_read_prio)
Definition at line 1284 of file SharedMutexTest.cpp.
References folly::kIsSanitizeAddress, folly::kIsSanitizeThread, and SKIP_IF.
{
   // This test fails in an assertion in the TSAN library because there are too
   // many mutexes
   SKIP_IF(folly::kIsSanitizeThread);
   for (int pass = 0; pass < (folly::kIsSanitizeAddress ? 1 : 100); ++pass) {
     runRemoteUnlock<SharedMutexReadPriority, atomic>(100000, 0.1, 0.1, 5, 5);
   }
 }
TEST (SharedMutex , deterministic_ping_pong_write_prio)
Definition at line 1381 of file SharedMutexTest.cpp.
References folly::kIsSanitizeThread, SKIP_IF, and folly::test::DeterministicSchedule::uniform().
{
   // This test fails in TSAN because some mutexes are lock_shared() in one
   // thread and unlock_shared() in a different thread.
   SKIP_IF(folly::kIsSanitizeThread);
   for (int pass = 0; pass < 1; ++pass) {
     DSched sched(DSched::uniform(pass));
     runPingPong<DSharedMutexWritePriority, DeterministicAtomic>(500, 0);
   }
 }
TEST (SharedMutex , deterministic_ping_pong_read_prio)
Definition at line 1391 of file SharedMutexTest.cpp.
References folly::test::DeterministicSchedule::uniform().
{
   for (int pass = 0; pass < 1; ++pass) {
     DSched sched(DSched::uniform(pass));
     runPingPong<DSharedMutexReadPriority, DeterministicAtomic>(500, 0);
   }
 }
TEST (SharedMutex , ping_pong_write_prio)
Definition at line 1398 of file SharedMutexTest.cpp.
References folly::kIsSanitizeThread, and SKIP_IF.
{
   // This test fails in TSAN because some mutexes are lock_shared() in one
   // thread and unlock_shared() in a different thread.
   SKIP_IF(folly::kIsSanitizeThread);
   for (int pass = 0; pass < 1; ++pass) {
     runPingPong<SharedMutexWritePriority, atomic>(50000, 0);
   }
 }
TEST (SharedMutex , ping_pong_read_prio)
Definition at line 1407 of file SharedMutexTest.cpp.
{
   for (int pass = 0; pass < 1; ++pass) {
     runPingPong<SharedMutexReadPriority, atomic>(50000, 0);
   }
 }
Variable Documentation
burn0
Definition at line 1760 of file SharedMutexTest.cpp.
burn100k
Definition at line 1767 of file SharedMutexTest.cpp.
burn1M
Definition at line 1781 of file SharedMutexTest.cpp.
burn300k
Definition at line 1774 of file SharedMutexTest.cpp.
true true true true true true true folly_rwspin
Definition at line 1697 of file SharedMutexTest.cpp.
false false folly_ticket
Definition at line 1516 of file SharedMutexTest.cpp.
folly_ticket_ping_pong
Definition at line 1762 of file SharedMutexTest.cpp.
false false folly_ticket_reads
Definition at line 1448 of file SharedMutexTest.cpp.
false false false pthrd_rwlock
Definition at line 1518 of file SharedMutexTest.cpp.
pthrd_rwlock_ping_pong
Definition at line 1764 of file SharedMutexTest.cpp.
false false false pthrd_rwlock_reads
Definition at line 1450 of file SharedMutexTest.cpp.
true true true true true true true true shmtx_rd_pri
Definition at line 1630 of file SharedMutexTest.cpp.
false shmtx_rd_pri_reads
Definition at line 1446 of file SharedMutexTest.cpp.
shmtx_w_bare_ping_pong
Definition at line 1760 of file SharedMutexTest.cpp.
true true true true true true shmtx_wr_pri
Definition at line 1514 of file SharedMutexTest.cpp.
shmtx_wr_pri_reads
Definition at line 1444 of file SharedMutexTest.cpp.