proxygen: proxygen/folly/folly/test/SingletonTestGlobal.cpp File Reference
SingletonTestGlobal.cpp File Reference
#include <memory>
#include <vector>
#include <folly/Benchmark.h>
#include <folly/Singleton.h>
#include <folly/portability/GTest.h>
#include <folly/test/SingletonTestStructs.h>
Functions
TEST (Singleton, BasicGlobalUsage)
Function Documentation
TEST (Singleton , BasicGlobalUsage)
Definition at line 40 of file SingletonTestGlobal.cpp.
References Watchdog::creation_order(), folly::SingletonVault::destroyInstances(), EXPECT_EQ, EXPECT_GE, EXPECT_NE, folly::SingletonVault::singleton(), folly::size(), and folly::Singleton< T, Tag, VaultTag >::try_get().
{
   EXPECT_EQ(Watchdog::creation_order().size(), 0);
   EXPECT_GE(SingletonVault::singleton()->registeredSingletonCount(), 1);
   EXPECT_EQ(SingletonVault::singleton()->livingSingletonCount(), 0);
   {
     std::shared_ptr<GlobalWatchdog> wd1 = Singleton<GlobalWatchdog>::try_get();
     EXPECT_NE(wd1, nullptr);
     EXPECT_EQ(Watchdog::creation_order().size(), 1);
     std::shared_ptr<GlobalWatchdog> wd2 = Singleton<GlobalWatchdog>::try_get();
     EXPECT_NE(wd2, nullptr);
     EXPECT_EQ(wd1.get(), wd2.get());
     EXPECT_EQ(Watchdog::creation_order().size(), 1);
   }
   SingletonVault::singleton()->destroyInstances();
   EXPECT_EQ(Watchdog::creation_order().size(), 0);
 }