proxygen: proxygen/folly/folly/test/SingletonBenchmark.cpp File Reference
SingletonBenchmark.cpp File Reference
#include <folly/Singleton.h>
#include <iostream>
#include <thread>
#include <folly/Benchmark.h>
#include <folly/Memory.h>
#include <folly/portability/GFlags.h>
Classes
struct BenchmarkSingleton
struct BenchmarkTag
struct GetTag
struct TryGetTag
struct TryGetFastTag
Typedefs
template<typename T , typename Tag = detail::DefaultTag>
using SingletonBenchmark = Singleton< T, Tag, BenchmarkTag >
Functions
int * getMeyersSingleton ()
int * getNormalSingleton ()
void run4Threads (std::function< void()> f)
void normalSingleton (size_t n)
BENCHMARK (NormalSingleton, n)
BENCHMARK (NormalSingleton4Threads, n)
void meyersSingleton (size_t n)
BENCHMARK (MeyersSingleton, n)
BENCHMARK (MeyersSingleton4Threads, n)
void follySingletonRaw (size_t n)
BENCHMARK (FollySingletonRaw, n)
BENCHMARK (FollySingletonRaw4Threads, n)
void follySingletonTryGet (size_t n)
BENCHMARK (FollySingletonTryGet, n)
BENCHMARK (FollySingletonTryGet4Threads, n)
void follySingletonTryGetFast (size_t n)
BENCHMARK (FollySingletonTryGetFast, n)
BENCHMARK (FollySingletonTryGetFast4Threads, n)
int main (int argc, char **argv)
Variables
int normal_singleton_value = 0
SingletonBenchmark< BenchmarkSingleton, GetTag > benchmark_singleton_get
SingletonBenchmark< BenchmarkSingleton, TryGetTag > benchmark_singleton_try_get
SingletonBenchmark< BenchmarkSingleton, TryGetFastTag > benchmark_singleton_try_get_fast
Typedef Documentation
template<typename T , typename Tag = detail::DefaultTag> using SingletonBenchmark = Singleton<T, Tag, BenchmarkTag>
Definition at line 89 of file SingletonBenchmark.cpp.
Function Documentation
BENCHMARK (NormalSingleton , n)
Definition at line 65 of file SingletonBenchmark.cpp.
References normalSingleton().
{
   normalSingleton(n);
 }
BENCHMARK (NormalSingleton4Threads , n)
Definition at line 69 of file SingletonBenchmark.cpp.
References normalSingleton(), and run4Threads().
{
   run4Threads([=]() { normalSingleton(n); });
 }
BENCHMARK (MeyersSingleton , n)
Definition at line 79 of file SingletonBenchmark.cpp.
References meyersSingleton().
{
   meyersSingleton(n);
 }
BENCHMARK (MeyersSingleton4Threads , n)
Definition at line 83 of file SingletonBenchmark.cpp.
References meyersSingleton(), and run4Threads().
{
   run4Threads([=]() { meyersSingleton(n); });
 }
BENCHMARK (FollySingletonRaw , n)
Definition at line 106 of file SingletonBenchmark.cpp.
References follySingletonRaw().
{
   follySingletonRaw(n);
 }
BENCHMARK (FollySingletonRaw4Threads , n)
Definition at line 110 of file SingletonBenchmark.cpp.
References follySingletonRaw(), and run4Threads().
{
   run4Threads([=]() { follySingletonRaw(n); });
 }
BENCHMARK (FollySingletonTryGet , n)
Definition at line 120 of file SingletonBenchmark.cpp.
References follySingletonTryGet().
{
   follySingletonTryGet(n);
 }
BENCHMARK (FollySingletonTryGet4Threads , n)
Definition at line 124 of file SingletonBenchmark.cpp.
References follySingletonTryGet(), and run4Threads().
{
   run4Threads([=]() { follySingletonTryGet(n); });
 }
BENCHMARK (FollySingletonTryGetFast , n)
Definition at line 134 of file SingletonBenchmark.cpp.
References follySingletonTryGetFast().
{
   follySingletonTryGetFast(n);
 }
BENCHMARK (FollySingletonTryGetFast4Threads , n)
Definition at line 138 of file SingletonBenchmark.cpp.
References follySingletonTryGetFast(), and run4Threads().
{
   run4Threads([=]() { follySingletonTryGetFast(n); });
 }
void follySingletonRaw (size_t n)
Definition at line 100 of file SingletonBenchmark.cpp.
References folly::Singleton< T, Tag, VaultTag >::get(), and i.
Referenced by BENCHMARK().
{
   for (size_t i = 0; i < n; ++i) {
     SingletonBenchmark<BenchmarkSingleton, GetTag>::get();
   }
 }
void follySingletonTryGet (size_t n)
Definition at line 114 of file SingletonBenchmark.cpp.
References i, and folly::Singleton< T, Tag, VaultTag >::try_get().
Referenced by BENCHMARK().
{
   for (size_t i = 0; i < n; ++i) {
     SingletonBenchmark<BenchmarkSingleton, TryGetTag>::try_get();
   }
 }
void follySingletonTryGetFast (size_t n)
Definition at line 128 of file SingletonBenchmark.cpp.
References i, and folly::Singleton< T, Tag, VaultTag >::try_get_fast().
Referenced by BENCHMARK().
{
   for (size_t i = 0; i < n; ++i) {
     SingletonBenchmark<BenchmarkSingleton, TryGetFastTag>::try_get_fast();
   }
 }
int* getMeyersSingleton ()
Definition at line 34 of file SingletonBenchmark.cpp.
Referenced by meyersSingleton().
{
   static auto ret = new int(0);
   return ret;
 }
int* getNormalSingleton ()
Definition at line 40 of file SingletonBenchmark.cpp.
References folly::doNotOptimizeAway(), and normal_singleton_value.
Referenced by normalSingleton().
{
   doNotOptimizeAway(&normal_singleton_value);
   return &normal_singleton_value;
 }
int main (int argc, char ** argv)
Definition at line 142 of file SingletonBenchmark.cpp.
References folly::runBenchmarks().
{
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   gflags::SetCommandLineOptionWithMode(
       "bm_min_usec", "100000", gflags::SET_FLAG_IF_DEFAULT);
   folly::runBenchmarks();
   return 0;
 }
void meyersSingleton (size_t n)
Definition at line 73 of file SingletonBenchmark.cpp.
References folly::doNotOptimizeAway(), getMeyersSingleton(), and i.
Referenced by BENCHMARK().
{
   for (size_t i = 0; i < n; ++i) {
     doNotOptimizeAway(getMeyersSingleton());
   }
 }
void normalSingleton (size_t n)
Definition at line 59 of file SingletonBenchmark.cpp.
References folly::doNotOptimizeAway(), getNormalSingleton(), and i.
Referenced by BENCHMARK().
{
   for (size_t i = 0; i < n; ++i) {
     doNotOptimizeAway(getNormalSingleton());
   }
 }
void run4Threads (std::function< void()> f)
Definition at line 49 of file SingletonBenchmark.cpp.
References f, i, and threads.
Referenced by BENCHMARK().
{
   std::vector<std::thread> threads;
   for (size_t i = 0; i < 4; ++i) {
     threads.emplace_back(f);
   }
   for (auto& thread : threads) {
     thread.join();
   }
 }
Variable Documentation
SingletonBenchmark<BenchmarkSingleton, GetTag> benchmark_singleton_get
Definition at line 95 of file SingletonBenchmark.cpp.
SingletonBenchmark<BenchmarkSingleton, TryGetTag> benchmark_singleton_try_get
Definition at line 96 of file SingletonBenchmark.cpp.
SingletonBenchmark<BenchmarkSingleton, TryGetFastTag> benchmark_singleton_try_get_fast
Definition at line 98 of file SingletonBenchmark.cpp.
int normal_singleton_value = 0
Definition at line 39 of file SingletonBenchmark.cpp.
Referenced by getNormalSingleton().