proxygen: proxygen/folly/folly/io/async/test/SSLContextInitializationTest.cpp File Reference
SSLContextInitializationTest.cpp File Reference
#include <folly/io/async/test/AsyncSSLSocketTest.h>
#include <functional>
#include <folly/init/Init.h>
#include <folly/io/async/SSLContext.h>
#include <folly/portability/GTest.h>
#include <folly/ssl/Init.h>
Namespaces
folly
—— Concurrent Priority Queue Implementation ——
Functions
void folly::setupSSLLocks ()
folly::TEST (SSLContextInitializationTest, SSLContextInitializeThenSetLocksAndInit)
folly::TEST (SSLContextInitializationTest, SSLContextSetLocksAndInitialize)
folly::TEST (SSLContextInitializationTest, SSLContextLocks)
folly::TEST (SSLContextInitializationTest, SSLContextLocksSetAfterInitIgnored)
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 102 of file SSLContextInitializationTest.cpp.
References folly::init(), testing::InitGoogleTest(), and RUN_ALL_TESTS().
{
 #ifdef SIGPIPE
   signal(SIGPIPE, SIG_IGN);
 #endif
   testing::InitGoogleTest(&argc, argv);
   folly::init(&argc, &argv);
   return RUN_ALL_TESTS();
 }