proxygen: proxygen/wangle/wangle/client/ssl/test/SSLSessionCacheDataTest.cpp File Reference
SSLSessionCacheDataTest.cpp File Reference
#include <chrono>
#include <vector>
#include <folly/DynamicConverter.h>
#include <gtest/gtest.h>
#include <wangle/client/ssl/SSLSession.h>
#include <wangle/client/ssl/SSLSessionCacheData.h>
#include <wangle/client/ssl/SSLSessionCacheUtils.h>
#include <wangle/client/ssl/test/TestUtil.h>
#include <wangle/ssl/SSLUtil.h>
Classes
class SSLSessionCacheDataTest
Typedefs
using SSLCtxDeleter = folly::static_function_deleter< SSL_CTX,&SSL_CTX_free >
using SSLCtxPtr = std::unique_ptr< SSL_CTX, SSLCtxDeleter >
Functions
TEST_F (SSLSessionCacheDataTest, Basic)
TEST_F (SSLSessionCacheDataTest, CloneSSLSession)
TEST_F (SSLSessionCacheDataTest, ServiceIdentity)
Typedef Documentation
using SSLCtxDeleter = folly::static_function_deleter<SSL_CTX, &SSL_CTX_free>
Definition at line 31 of file SSLSessionCacheDataTest.cpp.
using SSLCtxPtr = std::unique_ptr<SSL_CTX, SSLCtxDeleter>
Definition at line 32 of file SSLSessionCacheDataTest.cpp.
Function Documentation
TEST_F (SSLSessionCacheDataTest , Basic)
Definition at line 51 of file SSLSessionCacheDataTest.cpp.
References wangle::SSLSessionCacheData::addedTime, data, EXPECT_EQ, now(), wangle::SSLSessionCacheData::serviceIdentity, wangle::SSLSessionCacheData::sessionData, and folly::toDynamic().
{
   SSLSessionCacheData data;
   data.sessionData = folly::fbstring("some session data");
   data.addedTime = system_clock::now();
   data.serviceIdentity = "some service";
   auto d = folly::toDynamic(data);
   auto deserializedData = folly::convertTo<SSLSessionCacheData>(d);
   EXPECT_EQ(deserializedData.sessionData, data.sessionData);
   EXPECT_EQ(deserializedData.addedTime, data.addedTime);
   EXPECT_EQ(deserializedData.serviceIdentity, data.serviceIdentity);
 }
TEST_F (SSLSessionCacheDataTest , CloneSSLSession)
Definition at line 65 of file SSLSessionCacheDataTest.cpp.
References wangle::cloneSSLSession(), and EXPECT_TRUE.
{
   for (auto& it : sessions_) {
     auto sess = SSLSessionPtr(cloneSSLSession(it.first));
     EXPECT_TRUE(sess);
   }
 }
TEST_F (SSLSessionCacheDataTest , ServiceIdentity)
Definition at line 72 of file SSLSessionCacheDataTest.cpp.
References wangle::cloneSSLSession(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, folly::gen::first, wangle::getCacheDataForSession(), wangle::getSessionFromCacheData(), wangle::getSessionServiceIdentity(), wangle::setSessionServiceIdentity(), and string.
{
   auto sessionPtr = SSLSessionPtr(cloneSSLSession(sessions_[0].first));
   auto session = sessionPtr.get();
   auto ident = getSessionServiceIdentity(session);
   EXPECT_FALSE(ident);
   std::string id("serviceId");
   EXPECT_TRUE(setSessionServiceIdentity(session, id));
   ident = getSessionServiceIdentity(session);
   EXPECT_TRUE(ident);
   EXPECT_EQ(ident.value(), id);
   auto cloned = SSLSessionPtr(cloneSSLSession(session));
   EXPECT_TRUE(cloned);
   ident = getSessionServiceIdentity(cloned.get());
   EXPECT_TRUE(ident);
   EXPECT_EQ(ident.value(), id);
   auto cacheDataOpt = getCacheDataForSession(session);
   EXPECT_TRUE(cacheDataOpt);
   auto& cacheData = cacheDataOpt.value();
   EXPECT_EQ(id, cacheData.serviceIdentity);
   auto deserialized = SSLSessionPtr(getSessionFromCacheData(cacheData));
   EXPECT_TRUE(deserialized);
   ident = getSessionServiceIdentity(deserialized.get());
   EXPECT_TRUE(ident);
   EXPECT_EQ(ident.value(), id);
 }