proxygen: proxygen/wangle/wangle/ssl/test/SSLSessionCacheManagerTest.cpp File Reference
SSLSessionCacheManagerTest.cpp File Reference
#include <glog/logging.h>
#include <folly/portability/GTest.h>
#include <wangle/ssl/SSLSessionCacheManager.h>
#include <folly/Random.h>
Functions
TEST (ShardedLocalSSLSessionCacheTest, TestHash)
Function Documentation
TEST (ShardedLocalSSLSessionCacheTest , TestHash)
Definition at line 25 of file SSLSessionCacheManagerTest.cpp.
References folly::data(), wangle::ShardedLocalSSLSessionCache::hash(), folly::Random::secureRandom(), folly::size(), string, and uint32_t.
{
   uint32_t buckets = 10;
   uint32_t cacheSize = 20;
   uint32_t cacheCullSize = 100;
   std::array<uint8_t, 32> id;
   Random::secureRandom(id.data(), id.size());
   ShardedLocalSSLSessionCache cache(buckets, cacheSize, cacheCullSize);
   cache.hash(std::string((char*)id.data(), id.size()));
 }