proxygen: proxygen/wangle/wangle/client/ssl/test/SSLSessionCallbackTest.cpp File Reference
SSLSessionCallbackTest.cpp File Reference
#include <folly/io/async/SSLContext.h>
#include <gtest/gtest.h>
#include <wangle/client/ssl/SSLSessionCallbacks.h>
#include <wangle/client/ssl/test/TestUtil.h>
#include <vector>
#include <map>
Classes
class FakeSessionCallbacks
Functions
TEST (SSLSessionCallbackTest, AttachMultiple)
Function Documentation
TEST (SSLSessionCallbackTest , AttachMultiple)
Definition at line 60 of file SSLSessionCallbackTest.cpp.
References wangle::SSLSessionCallbacks::attachCallbacksToContext(), wangle::SSLSessionCallbacks::detachCallbacksFromContext(), EXPECT_EQ, EXPECT_FALSE, wangle::SSLSessionCallbacks::getCacheFromContext(), and folly::SSLContext::getSSLCtx().
{
   SSLContext c1;
   SSLContext c2;
   FakeSessionCallbacks cb;
   FakeSessionCallbacks::attachCallbacksToContext(c1.getSSLCtx(), &cb);
   FakeSessionCallbacks::attachCallbacksToContext(c2.getSSLCtx(), &cb);
   auto cb1 = FakeSessionCallbacks::getCacheFromContext(c1.getSSLCtx());
   auto cb2 = FakeSessionCallbacks::getCacheFromContext(c2.getSSLCtx());
   EXPECT_EQ(cb1, cb2);
   FakeSessionCallbacks::detachCallbacksFromContext(c1.getSSLCtx(), cb1);
   EXPECT_FALSE(FakeSessionCallbacks::getCacheFromContext(c1.getSSLCtx()));
   FakeSessionCallbacks unused;
   FakeSessionCallbacks::detachCallbacksFromContext(c2.getSSLCtx(), &unused);
   cb2 = FakeSessionCallbacks::getCacheFromContext(c2.getSSLCtx());
   EXPECT_EQ(&cb, cb2);
 }