proxygen: proxygen/folly/folly/fibers/test/StackOverflow.cpp File Reference
StackOverflow.cpp File Reference
#include <folly/fibers/FiberManagerMap.h>
#include <folly/init/Init.h>
Functions
void f (int *p)
int main (int argc, char *argv[])
Function Documentation
void f (int * p)
Definition at line 20 of file StackOverflow.cpp.
References a, and i.
Referenced by main().
                {
   // Make sure recursion is not optimized out
   int a[100];
   for (size_t i = 0; i < 100; ++i) {
     a[i] = i;
     ++(a[i]);
     if (p) {
       a[i] += p[i];
     }
   }
   f(a);
 }
int main (int argc, char * argv[])
Definition at line 33 of file StackOverflow.cpp.
References folly::fibers::FiberManager::addTask(), f(), folly::fibers::getFiberManager(), folly::init(), and folly::EventBase::loop().
{
   folly::init(&argc, &argv);
   folly::EventBase evb;
   folly::fibers::getFiberManager(evb).addTask([&]() { f(nullptr); });
   evb.loop();
 }