proxygen: proxygen/folly/folly/logging/test/StandardLogHandlerTest.cpp File Reference
StandardLogHandlerTest.cpp File Reference
#include <folly/logging/StandardLogHandler.h>
#include <folly/Conv.h>
#include <folly/logging/LogCategory.h>
#include <folly/logging/LogFormatter.h>
#include <folly/logging/LogHandlerConfig.h>
#include <folly/logging/LogLevel.h>
#include <folly/logging/LogMessage.h>
#include <folly/logging/LogWriter.h>
#include <folly/logging/LoggerDB.h>
#include <folly/portability/GTest.h>
Functions
TEST (StandardLogHandler, simple)
TEST (StandardLogHandler, levelCheck)
Function Documentation
TEST (StandardLogHandler , simple)
Definition at line 76 of file StandardLogHandlerTest.cpp.
References ASSERT_EQ, config, folly::DBG8, EXPECT_EQ, folly::StandardLogHandler::handleMessage(), handler(), string, and folly::LoggerDB::TESTING.
{
   auto writer = make_shared<TestLogWriter>();
   LogHandlerConfig config{"std_test"};
   StandardLogHandler handler(config, make_shared<TestLogFormatter>(), writer);
   LoggerDB db{LoggerDB::TESTING};
   auto logCategory = db.getCategory("log_cat");
   auto handlerCategory = db.getCategory("handler_cat");
   LogMessage msg{logCategory,
                  LogLevel::DBG8,
                  "src/test.cpp",
                  1234,
                  "testMethod",
                  std::string{"hello world"}};
   handler.handleMessage(msg, handlerCategory);
   ASSERT_EQ(1, writer->getMessages().size());
   EXPECT_EQ(
       "DBG8::log_cat::handler_cat::src/test.cpp::1234::hello world",
       writer->getMessages()[0]);
 }
TEST (StandardLogHandler , levelCheck)
Definition at line 98 of file StandardLogHandlerTest.cpp.
References ASSERT_EQ, config, folly::DBG1, folly::DBG2, folly::DBG3, folly::DBG9, folly::ERR, EXPECT_EQ, folly::StandardLogHandler::handleMessage(), handler(), folly::INFO, message, messages, folly::StandardLogHandler::setLevel(), folly::LoggerDB::TESTING, and folly::WARN.
{
   auto writer = make_shared<TestLogWriter>();
   LogHandlerConfig config{"std_test"};
   StandardLogHandler handler(config, make_shared<TestLogFormatter>(), writer);
   LoggerDB db{LoggerDB::TESTING};
   auto logCategory = db.getCategory("log_cat");
   auto handlerCategory = db.getCategory("handler_cat");
   auto logMsg = [&](LogLevel level, folly::StringPiece message) {
     LogMessage msg{
         logCategory, level, "src/test.cpp", 1234, "testMethod", message};
     handler.handleMessage(msg, handlerCategory);
   };
   handler.setLevel(LogLevel::WARN);
   logMsg(LogLevel::INFO, "info");
   logMsg(LogLevel::WARN, "beware");
   logMsg(LogLevel::ERR, "whoops");
   logMsg(LogLevel::DBG1, "debug stuff");
   auto& messages = writer->getMessages();
   ASSERT_EQ(2, messages.size());
   EXPECT_EQ(
       "WARN::log_cat::handler_cat::src/test.cpp::1234::beware", messages.at(0));
   EXPECT_EQ(
       "ERR::log_cat::handler_cat::src/test.cpp::1234::whoops", messages.at(1));
   messages.clear();
   handler.setLevel(LogLevel::DBG2);
   logMsg(LogLevel::DBG3, "dbg");
   logMsg(LogLevel::DBG1, "here");
   logMsg(LogLevel::DBG2, "and here");
   logMsg(LogLevel::ERR, "oh noes");
   logMsg(LogLevel::DBG9, "very verbose");
   ASSERT_EQ(3, messages.size());
   EXPECT_EQ(
       "DBG1::log_cat::handler_cat::src/test.cpp::1234::here", messages.at(0));
   EXPECT_EQ(
       "DBG2::log_cat::handler_cat::src/test.cpp::1234::and here",
       messages.at(1));
   EXPECT_EQ(
       "ERR::log_cat::handler_cat::src/test.cpp::1234::oh noes", messages.at(2));
   messages.clear();
 }