proxygen: folly::DynamicParser::ParserStack Struct Reference
folly::DynamicParser::ParserStack Struct Reference
Classes
struct Pop
struct PopGuard
Public Member Functions
ParserStack (const folly::dynamic *input)
ParserStack (const ParserStack &)=delete
ParserStack & operator= (const ParserStack &)=delete
ParserStack (ParserStack &&)=delete
ParserStack & operator= (ParserStack &&)=delete
PopGuard push (const folly::dynamic &k, const folly::dynamic &v) noexcept
const folly::dynamic & key () const
const folly::dynamic & value () const
folly::dynamic & errors (bool allow_non_string_keys) noexcept
folly::dynamic releaseErrors ()
void throwErrors ()
Private Member Functions
folly::dynamic releaseErrorsImpl ()
Private Attributes
const folly::dynamic * key_ {nullptr}
const folly::dynamic * value_
folly::dynamic errors_
std::vector< const folly::dynamic * > unmaterializedSubErrorKeys_
std::vector< folly::dynamic * > subErrors_
Friends
struct Pop
Detailed Description
Definition at line 329 of file DynamicParser.h.
Constructor & Destructor Documentation
folly::DynamicParser::ParserStack::ParserStack (const folly::dynamic * input) inline explicit
Definition at line 349 of file DynamicParser.h.
References k, folly::pushmi::__adl::noexcept(), and folly::value().
         : value_(input),
           errors_(folly::dynamic::object()),
           subErrors_({&errors_}) {}
folly::DynamicParser::ParserStack::ParserStack (const ParserStack &) delete
folly::DynamicParser::ParserStack::ParserStack (ParserStack &&) delete
Member Function Documentation
folly::dynamic & folly::DynamicParser::ParserStack::errors (bool allow_non_string_keys) noexcept
Definition at line 144 of file DynamicParser.cpp.
References folly::dynamic::object().
Referenced by folly::DynamicParser::reportError().
{
   // Materialize the lazy "key + parent's type" error objects we'll need.
   CHECK(!subErrors_.empty()) << "Internal bug: out of suberrors";
   for (const auto& suberror_key : unmaterializedSubErrorKeys_) {
     auto& nested = (*subErrors_.back())["nested"];
     if (nested.isNull()) {
       nested = folly::dynamic::object();
     }
     // Find, or insert a dummy entry for the current key
     auto& my_errors =
         insertAtKey(&nested, allow_non_string_keys, *suberror_key);
     if (my_errors.isNull()) {
       my_errors = folly::dynamic::object();
     }
     subErrors_.emplace_back(&my_errors);
   }
   unmaterializedSubErrorKeys_.clear();
   return *subErrors_.back();
 }
const folly::dynamic & folly::DynamicParser::ParserStack::key () const inline
Definition at line 315 of file DynamicParser-inl.h.
{
   if (!key_) {
     throw DynamicParserLogicError("Only call key() inside parsing callbacks.");
   }
   return *key_;
 }
ParserStack& folly::DynamicParser::ParserStack::operator= (const ParserStack &) delete
ParserStack& folly::DynamicParser::ParserStack::operator= (ParserStack &&) delete
DynamicParser::ParserStack::PopGuard folly::DynamicParser::ParserStack::push (const folly::dynamic & k, const folly::dynamic & v) noexcept
Definition at line 130 of file DynamicParser.cpp.
References folly::gen::guard(), k, and v.
{
   // Save the previous state of the parser.
   DynamicParser::ParserStack::PopGuard guard{this};
   key_ = &k;
   value_ = &v;
   // We create errors_ sub-objects lazily to keep the result small.
   unmaterializedSubErrorKeys_.emplace_back(key_);
   return guard;
 }
folly::dynamic folly::DynamicParser::ParserStack::releaseErrors ()
Definition at line 165 of file DynamicParser.cpp.
{
   if (key_ || unmaterializedSubErrorKeys_.size() != 0 ||
       subErrors_.size() != 1) {
     throw DynamicParserLogicError(
         "Do not releaseErrors() while parsing: ",
         key_ != nullptr,
         " / ",
         unmaterializedSubErrorKeys_.size(),
         " / ",
         subErrors_.size());
   }
   return releaseErrorsImpl();
 }
folly::dynamic folly::DynamicParser::ParserStack::releaseErrorsImpl () private
Definition at line 183 of file DynamicParser.cpp.
References folly::gen::move.
{
   if (errors_.isNull()) {
     throw DynamicParserLogicError("Do not releaseErrors() twice");
   }
   auto errors = std::move(errors_);
   errors_ = nullptr; // Prevent a second release.
   value_ = nullptr; // Break attempts to parse again.
   return errors;
 }
void folly::DynamicParser::ParserStack::throwErrors ()
Definition at line 179 of file DynamicParser.cpp.
Referenced by folly::DynamicParser::reportError().
{
   throw DynamicParserParseError(releaseErrorsImpl());
 }
const folly::dynamic & folly::DynamicParser::ParserStack::value () const inline
Definition at line 322 of file DynamicParser-inl.h.
{
   if (!value_) {
     throw DynamicParserLogicError(
         "Parsing nullptr, or parsing after releaseErrors()");
   }
   return *value_;
 }
Friends And Related Function Documentation
friend struct Pop friend
Definition at line 380 of file DynamicParser.h.
Member Data Documentation
folly::dynamic folly::DynamicParser::ParserStack::errors_ private
Definition at line 398 of file DynamicParser.h.
const folly::dynamic* folly::DynamicParser::ParserStack::key_ {nullptr} private
Definition at line 385 of file DynamicParser.h.
std::vector<folly::dynamic*> folly::DynamicParser::ParserStack::subErrors_ private
Definition at line 403 of file DynamicParser.h.
std::vector<const folly::dynamic*> folly::DynamicParser::ParserStack::unmaterializedSubErrorKeys_ private
Definition at line 401 of file DynamicParser.h.
const folly::dynamic* folly::DynamicParser::ParserStack::value_ private
Definition at line 387 of file DynamicParser.h.
The documentation for this struct was generated from the following files:
proxygen/folly/folly/experimental/DynamicParser.h
proxygen/folly/folly/experimental/DynamicParser-inl.h
proxygen/folly/folly/experimental/DynamicParser.cpp