proxygen: PollerWithState Struct Reference
PollerWithState Struct Reference
Public Member Functions
PollerWithState (TestFile &testFile)
void waitForUpdate (bool expect=true)
Public Attributes
std::unique_ptr< FilePoller > poller
UpdateSyncState state
Detailed Description
Definition at line 173 of file FilePollerTest.cpp.
Constructor & Destructor Documentation
PollerWithState::PollerWithState (TestFile & testFile) inline explicit
Definition at line 174 of file FilePollerTest.cpp.
References TestFile::name.
{
     poller = std::make_unique<NoDiskPoller>(testFile);
     poller->addFileToTrack(testFile.name, [&] {
       state.updateTriggered();
     });
   }
Member Function Documentation
void PollerWithState::waitForUpdate (bool expect = true) inline
Definition at line 181 of file FilePollerTest.cpp.
References ASSERT_NO_FATAL_FAILURE, and folly::symbolizer::test::expect().
Referenced by TEST(), and TEST_F().
{
     ASSERT_NO_FATAL_FAILURE(state.waitForUpdate(expect));
   }
Member Data Documentation
std::unique_ptr<FilePoller> PollerWithState::poller
Definition at line 185 of file FilePollerTest.cpp.
Referenced by TEST_F().
UpdateSyncState PollerWithState::state
Definition at line 186 of file FilePollerTest.cpp.
The documentation for this struct was generated from the following file:
proxygen/wangle/wangle/util/test/FilePollerTest.cpp