proxygen: folly::Arena< Alloc >::Block Struct Reference
folly::Arena< Alloc >::Block Struct Reference
Public Member Functions
void deallocate (Alloc &alloc)
char * start ()
Static Public Member Functions
static std::pair< Block *, size_t > allocate (Alloc &alloc, size_t size, bool allowSlack)
Public Attributes
BlockLink link
Private Member Functions
Block ()=default
~Block ()=default
Detailed Description
template<class Alloc>
struct folly::Arena< Alloc >::Block
Definition at line 132 of file Arena.h.
Constructor & Destructor Documentation
template<class Alloc> folly::Arena< Alloc >::Block::Block () private default
Referenced by folly::Arena< Alloc >::Block::allocate(), and folly::Arena< Alloc >::allocateSlow().
template<class Alloc> folly::Arena< Alloc >::Block::~Block () private default
Referenced by folly::Arena< Alloc >::Block::deallocate().
Member Function Documentation
template<class Alloc> std::pair< typename Arena< Alloc >::Block *, size_t > folly::Arena< Alloc >::Block::allocate (Alloc & alloc, size_t size, bool allowSlack) static
Definition at line 27 of file Arena-inl.h.
References folly::Arena< Alloc >::Block::Block(), and folly::ArenaAllocatorTraits< Alloc >::goodSize().
Referenced by folly::Arena< Alloc >::allocateSlow().
{
   size_t allocSize = sizeof(Block) + size;
   if (allowSlack) {
     allocSize = ArenaAllocatorTraits<Alloc>::goodSize(alloc, allocSize);
   }
   void* mem = std::allocator_traits<Alloc>::allocate(alloc, allocSize);
   return std::make_pair(new (mem) Block(), allocSize - sizeof(Block));
 }
template<class Alloc> void folly::Arena< Alloc >::Block::deallocate (Alloc & alloc)
Definition at line 38 of file Arena-inl.h.
References folly::Arena< Alloc >::Block::~Block().
{
   this->~Block();
   std::allocator_traits<Alloc>::deallocate(alloc, this, 1);
 }
template<class Alloc> char* folly::Arena< Alloc >::Block::start () inline
Definition at line 143 of file Arena.h.
Referenced by folly::Arena< Alloc >::allocateSlow().
                   {
       return reinterpret_cast<char*>(this + 1);
     }
Member Data Documentation
template<class Alloc> BlockLink folly::Arena< Alloc >::Block::link
Definition at line 133 of file Arena.h.
The documentation for this struct was generated from the following files:
proxygen/folly/folly/memory/Arena.h
proxygen/folly/folly/memory/Arena-inl.h