proxygen: folly::DynamicConverter< std::pair< F, S > > Struct Template Reference
folly::DynamicConverter< std::pair< F, S > > Struct Template Reference
#include <DynamicConverter.h>
Static Public Member Functions
static std::pair< F, S > convert (const dynamic &d)
Detailed Description
template<typename F, typename S>
struct folly::DynamicConverter< std::pair< F, S > >
Definition at line 244 of file DynamicConverter.h.
Member Function Documentation
template<typename F , typename S > static std::pair<F, S> folly::DynamicConverter< std::pair< F, S > >::convert (const dynamic & d) inline static
Definition at line 245 of file DynamicConverter.h.
References folly::dynamic::isArray(), folly::dynamic::isObject(), folly::dynamic::items(), folly::dynamic::size(), and folly::dynamic::type().
{
     if (d.isArray() && d.size() == 2) {
       return std::make_pair(convertTo<F>(d[0]), convertTo<S>(d[1]));
     } else if (d.isObject() && d.size() == 1) {
       auto it = d.items().begin();
       return std::make_pair(convertTo<F>(it->first), convertTo<S>(it->second));
     } else {
       throw TypeError("array (size 2) or object (size 1)", d.type());
     }
   }
The documentation for this struct was generated from the following file:
proxygen/folly/folly/DynamicConverter.h