proxygen: fizz::Sha< T > Struct Template Reference
fizz::Sha< T > Struct Template Reference
#include <Sha.h>
Static Public Member Functions
static void hmac (folly::ByteRange key, const folly::IOBuf &in, folly::MutableByteRange out)
static void hash (const folly::IOBuf &in, folly::MutableByteRange out)
Detailed Description
template<typename T>
struct fizz::Sha< T >
Hash implementation using OpenSSL.
The template struct requires the following parameters:
HashLen: length of the hash digest
HashEngine: function returning EVP_MD* to use
BlankHash: ByteRange containing the digest of a hash of empty input
Definition at line 26 of file Sha.h.
Member Function Documentation
template<typename T > void fizz::Sha< T >::hash (const folly::IOBuf & in, folly::MutableByteRange out) static
Puts Hash(in) into out. Out must be at least of size HashLen.
Definition at line 23 of file Sha-inl.h.
References folly::ssl::OpenSSLHash::hash(), and folly::Range< Iter >::size().
{
   CHECK_GE(out.size(), T::HashLen);
   folly::ssl::OpenSSLHash::hash(out, T::HashEngine(), in);
 }
template<typename T > void fizz::Sha< T >::hmac (folly::ByteRange key, const folly::IOBuf & in, folly::MutableByteRange out) static
Puts HMAC(key, in) into out. Out must be at least of size HashLen.
Definition at line 14 of file Sha-inl.h.
References folly::ssl::OpenSSLHash::hmac(), and folly::Range< Iter >::size().
{
   CHECK_GE(out.size(), T::HashLen);
   folly::ssl::OpenSSLHash::hmac(out, T::HashEngine(), key, in);
 }
The documentation for this struct was generated from the following files:
proxygen/fizz/fizz/crypto/Sha.h
proxygen/fizz/fizz/crypto/Sha-inl.h