proxygen: Application Struct Reference
Application Struct Reference
Public Member Functions
Application ()
void loop ()
Public Attributes
FiberManager fiberManager
std::queue< Promise< int > > pendingRequests
size_t toSend
size_t maxOutstanding
Detailed Description
Definition at line 26 of file FibersTestApp.cpp.
Constructor & Destructor Documentation
Application::Application () inline
Definition at line 28 of file FibersTestApp.cpp.
       : fiberManager(std::make_unique<SimpleLoopController>()),
         toSend(20),
         maxOutstanding(5) {}
Member Function Documentation
void Application::loop () inline
Definition at line 33 of file FibersTestApp.cpp.
References folly::fibers::await(), folly::gen::move, folly::fibers::SimpleLoopController::stop(), and folly::value().
Referenced by main().
               {
     if (pendingRequests.size() == maxOutstanding || toSend == 0) {
       if (pendingRequests.empty()) {
         return;
       }
       intptr_t value = rand() % 1000;
       std::cout << "Completing request with data = " << value << std::endl;
       pendingRequests.front().setValue(value);
       pendingRequests.pop();
     } else {
       static size_t id_counter = 1;
       size_t id = id_counter++;
       std::cout << "Adding new request with id = " << id << std::endl;
       fiberManager.addTask([this, id]() {
         std::cout << "Executing fiber with id = " << id << std::endl;
         auto result1 = await([this](Promise<int> fiber) {
           pendingRequests.push(std::move(fiber));
         });
         std::cout << "Fiber id = " << id << " got result1 = " << result1
                   << std::endl;
         auto result2 = await([this](Promise<int> fiber) {
           pendingRequests.push(std::move(fiber));
         });
         std::cout << "Fiber id = " << id << " got result2 = " << result2
                   << std::endl;
       });
       if (--toSend == 0) {
         auto& loopController =
             dynamic_cast<SimpleLoopController&>(fiberManager.loopController());
         loopController.stop();
       }
     }
   }
Member Data Documentation
FiberManager Application::fiberManager
Definition at line 73 of file FibersTestApp.cpp.
Referenced by main().
size_t Application::maxOutstanding
Definition at line 77 of file FibersTestApp.cpp.
std::queue<Promise<int> > Application::pendingRequests
Definition at line 75 of file FibersTestApp.cpp.
size_t Application::toSend
Definition at line 76 of file FibersTestApp.cpp.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/fibers/test/FibersTestApp.cpp