proxygen: folly::pushmi::operators::flow_from_fn Struct Reference
folly::pushmi::operators::flow_from_fn Struct Reference
#include <from.h>
Classes
struct out_impl
Public Member Functions
requires DerivedFrom< typename std::iterator_traits< I >::iterator_category, std::forward_iterator_tag > auto operator() (I begin, S end) const
requires Range< R > auto operator() (R &&range) const
requires DerivedFrom< typename std::iterator_traits< I >::iterator_category, std::forward_iterator_tag > &&Sender< Exec, is_single<>, is_executor<> > auto operator() (I begin, S end, Exec exec) const
requires Range< R > &&Sender< Exec, is_single<>, is_executor<> > auto operator() (R &&range, Exec exec) const
Detailed Description
Definition at line 137 of file from.h.
Member Function Documentation
requires DerivedFrom< typename std::iterator_traits<I>::iterator_category, std::forward_iterator_tag> auto folly::pushmi::operators::flow_from_fn::operator() (I begin, S end) const inline
Definition at line 166 of file from.h.
References folly::test::begin(), folly::test::end(), folly::pushmi::PUSHMI_TEMPLATE(), folly::pushmi::requires(), and folly::pushmi::trampoline().
{
     return (*this)(begin, end, trampoline());
   }
requires Range<R> auto folly::pushmi::operators::flow_from_fn::operator() (R && range) const inline
Definition at line 172 of file from.h.
References folly::test::begin(), folly::test::end(), folly::pushmi::PUSHMI_TEMPLATE(), folly::range(), folly::pushmi::requires(), and folly::pushmi::trampoline().
{
     return (*this)(std::begin(range), std::end(range), trampoline());
   }
requires DerivedFrom< typename std::iterator_traits<I>::iterator_category, std::forward_iterator_tag>&& Sender<Exec, is_single<>, is_executor<> > auto folly::pushmi::operators::flow_from_fn::operator() (I begin, S end, Exec exec) const inline
Definition at line 180 of file from.h.
References folly::test::begin(), folly::test::end(), folly::pushmi::make_flow_many_sender, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return make_flow_many_sender(out_impl<I, S, Exec>{begin, end, exec});
   }
requires Range<R>&& Sender<Exec, is_single<>, is_executor<> > auto folly::pushmi::operators::flow_from_fn::operator() (R && range, Exec exec) const inline
Definition at line 186 of file from.h.
References folly::test::begin(), folly::test::end(), and folly::pushmi::operators::flow_from.
{
     return (*this)(std::begin(range), std::end(range), exec);
   }
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/pushmi/o/from.h