proxygen: folly::HazptrLockFreeLIFO< T, Atom >::Node Struct Reference
folly::HazptrLockFreeLIFO< T, Atom >::Node Struct Reference
Public Member Functions
Node (T v, Node *n)
Node * next ()
T value ()
Public Member Functions inherited from folly::hazptr_obj_base< Node, Atom >
void retire (D deleter={}, hazptr_domain< Atom > &domain=default_hazptr_domain< Atom >())
void retire (hazptr_domain< Atom > &domain)
Public Member Functions inherited from folly::hazptr_obj< Atom >
hazptr_obj () noexcept
hazptr_obj (const hazptr_obj< Atom > &) noexcept
hazptr_obj (hazptr_obj< Atom > &&) noexcept
hazptr_obj< Atom > & operator= (const hazptr_obj< Atom > &) noexcept
hazptr_obj< Atom > & operator= (hazptr_obj< Atom > &&) noexcept
Public Member Functions inherited from folly::hazptr_deleter< Node, D >
void set_deleter (D d={})
void delete_obj (Node *p)
Public Attributes
T value_
Node * next_
Detailed Description
template<typename T, template< typename > class Atom = std::atomic>
struct folly::HazptrLockFreeLIFO< T, Atom >::Node
Definition at line 77 of file HazptrLockFreeLIFO.h.
Constructor & Destructor Documentation
template<typename T, template< typename > class Atom = std::atomic> folly::HazptrLockFreeLIFO< T, Atom >::Node::Node (T v, Node * n) inline
Definition at line 81 of file HazptrLockFreeLIFO.h.
 : value_(v), next_(n) {}
Member Function Documentation
template<typename T, template< typename > class Atom = std::atomic> Node* folly::HazptrLockFreeLIFO< T, Atom >::Node::next () inline
Definition at line 83 of file HazptrLockFreeLIFO.h.
References folly::HazptrLockFreeLIFO< T, Atom >::Node::next_.
Referenced by folly::HazptrLockFreeLIFO< T, Atom >::pop(), and folly::HazptrLockFreeLIFO< T, Atom >::~HazptrLockFreeLIFO().
                  {
       return next_;
     }
template<typename T, template< typename > class Atom = std::atomic> T folly::HazptrLockFreeLIFO< T, Atom >::Node::value () inline
Definition at line 87 of file HazptrLockFreeLIFO.h.
References folly::HazptrLockFreeLIFO< T, Atom >::Node::value_.
Referenced by folly::HazptrLockFreeLIFO< T, Atom >::pop().
               {
       return value_;
     }
Member Data Documentation
template<typename T, template< typename > class Atom = std::atomic> Node* folly::HazptrLockFreeLIFO< T, Atom >::Node::next_
Definition at line 79 of file HazptrLockFreeLIFO.h.
Referenced by folly::HazptrLockFreeLIFO< T, Atom >::Node::next().
template<typename T, template< typename > class Atom = std::atomic> T folly::HazptrLockFreeLIFO< T, Atom >::Node::value_
Definition at line 78 of file HazptrLockFreeLIFO.h.
Referenced by folly::HazptrLockFreeLIFO< T, Atom >::Node::value().
The documentation for this struct was generated from the following file:
proxygen/folly/folly/synchronization/example/HazptrLockFreeLIFO.h