proxygen: folly::pushmi::concepts::detail::Or< T, U > Struct Template Reference
folly::pushmi::concepts::detail::Or< T, U > Struct Template Reference
#include <concept_def.h>
Public Member Functions
constexpr operator bool () const noexcept
template<class This = Or, bool B, int(*) _pushmi_concept_unique___LINE__ = nullptr, std::enable_if_t< _pushmi_concept_unique___LINE__||bool(B==(bool) This{}), int > = 0>
constexpr operator std::integral_constant< bool, B > () const noexcept
constexpr auto operator! () const noexcept
template<class That >
constexpr auto operator&& (That) const noexcept
template<class That >
constexpr auto operator|| (That) const noexcept
Detailed Description
template<class T, class U>
struct folly::pushmi::concepts::detail::Or< T, U >
Definition at line 457 of file concept_def.h.
Member Function Documentation
template<class T , class U > constexpr folly::pushmi::concepts::detail::Or< T, U >::operator bool () const inline explicit noexcept
Definition at line 505 of file concept_def.h.
References folly::pushmi::__adl::noexcept(), and folly::T.
           {
   explicit constexpr operator bool() const noexcept {
template<class T , class U > template<class This = Or, bool B, int(*) _pushmi_concept_unique___LINE__ = nullptr, std::enable_if_t< _pushmi_concept_unique___LINE__||bool(B==(bool) This{}), int > = 0> constexpr folly::pushmi::concepts::detail::Or< T, U >::operator std::integral_constant< bool, B > () const inline noexcept
Definition at line 509 of file concept_def.h.
                            {}) constexpr
template<class T , class U > constexpr auto folly::pushmi::concepts::detail::Or< T, U >::operator! () const inline noexcept
Definition at line 512 of file concept_def.h.
References folly::pushmi::__adl::noexcept(), and folly::pushmi::concepts::detail::Not< T >::operator!().
{
     return {};
   }
template<class T , class U > template<class That > constexpr auto folly::pushmi::concepts::detail::Or< T, U >::operator&& (That) const inline noexcept
Definition at line 516 of file concept_def.h.
References folly::pushmi::__adl::noexcept(), and folly::pushmi::concepts::detail::Not< T >::operator&&().
                   {};
   }
   template <class That>
template<class T , class U > template<class That > constexpr auto folly::pushmi::concepts::detail::Or< T, U >::operator|| (That) const inline noexcept
Definition at line 520 of file concept_def.h.
References folly::pushmi::__adl::noexcept(), and folly::pushmi::concepts::detail::Not< T >::operator||().
                         {};
   }
   template <class That>
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/pushmi/detail/concept_def.h