proxygen: folly::small_vector< Value, RequestedMaxInline, PolicyA, PolicyB, PolicyC >::HeapPtr Struct Reference
folly::small_vector< Value, RequestedMaxInline, PolicyA, PolicyB, PolicyC >::HeapPtr Struct Reference
Public Member Functions
InternalSizeType getCapacity () const
void setCapacity (InternalSizeType c)
Public Attributes
void * heap_
Detailed Description
template<class Value, std::size_t RequestedMaxInline = 1, class PolicyA = void, class PolicyB = void, class PolicyC = void>
struct folly::small_vector< Value, RequestedMaxInline, PolicyA, PolicyB, PolicyC >::HeapPtr
Definition at line 1113 of file small_vector.h.
Member Function Documentation
template<class Value, std::size_t RequestedMaxInline = 1, class PolicyA = void, class PolicyB = void, class PolicyC = void> InternalSizeType folly::small_vector< Value, RequestedMaxInline, PolicyA, PolicyB, PolicyC >::HeapPtr::getCapacity () const inline
Definition at line 1118 of file small_vector.h.
References folly::detail::pointerFlagClear(), and folly::detail::pointerFlagGet().
{
       assert(detail::pointerFlagGet(heap_));
       return *static_cast<InternalSizeType*>(detail::pointerFlagClear(heap_));
     }
template<class Value, std::size_t RequestedMaxInline = 1, class PolicyA = void, class PolicyB = void, class PolicyC = void> void folly::small_vector< Value, RequestedMaxInline, PolicyA, PolicyB, PolicyC >::HeapPtr::setCapacity (InternalSizeType c) inline
Definition at line 1122 of file small_vector.h.
References FOLLY_SV_PACK_ATTR, and folly::detail::pointerFlagClear().
{
       *static_cast<InternalSizeType*>(detail::pointerFlagClear(heap_)) = c;
     }
Member Data Documentation
template<class Value, std::size_t RequestedMaxInline = 1, class PolicyA = void, class PolicyB = void, class PolicyC = void> void* folly::small_vector< Value, RequestedMaxInline, PolicyA, PolicyB, PolicyC >::HeapPtr::heap_
Definition at line 1116 of file small_vector.h.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/small_vector.h