proxygen: folly::FunctionScheduler::LatencyDistribution Struct Reference
folly::FunctionScheduler::LatencyDistribution Struct Reference
#include <FunctionScheduler.h>
Public Member Functions
LatencyDistribution (bool poisson, double mean)
Public Attributes
bool isPoisson
double poissonMean
Detailed Description
Definition at line 81 of file FunctionScheduler.h.
Constructor & Destructor Documentation
folly::FunctionScheduler::LatencyDistribution::LatencyDistribution (bool poisson, double mean) inline
Definition at line 85 of file FunctionScheduler.h.
References folly::FunctionScheduler::addFunction(), folly::FunctionScheduler::addFunctionConsistentDelay(), folly::FunctionScheduler::addFunctionOnce(), and folly::FunctionScheduler::addFunctionUniformDistribution().
         : isPoisson(poisson), poissonMean(mean) {}
Member Data Documentation
bool folly::FunctionScheduler::LatencyDistribution::isPoisson
Definition at line 82 of file FunctionScheduler.h.
Referenced by folly::FunctionScheduler::~FunctionScheduler().
double folly::FunctionScheduler::LatencyDistribution::poissonMean
Definition at line 83 of file FunctionScheduler.h.
Referenced by folly::FunctionScheduler::~FunctionScheduler().
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/FunctionScheduler.h