proxygen: folly::exception_wrapper::VTable Struct Reference
folly::exception_wrapper::VTable Struct Reference
Public Attributes
void(* copy_)(exception_wrapper const *, exception_wrapper *)
void(* move_)(exception_wrapper *, exception_wrapper *)
void(* delete_)(exception_wrapper *)
void(* throw_)(exception_wrapper const *)
std::type_info const *(* type_)(exception_wrapper const *)
std::exception const *(* get_exception_)(exception_wrapper const *)
exception_wrapper(* get_exception_ptr_)(exception_wrapper const *)
Detailed Description
Definition at line 189 of file ExceptionWrapper.h.
Member Data Documentation
void(* folly::exception_wrapper::VTable::copy_) (exception_wrapper const *, exception_wrapper *)
Definition at line 190 of file ExceptionWrapper.h.
Referenced by folly::exception_wrapper::exception_wrapper().
void(* folly::exception_wrapper::VTable::delete_) (exception_wrapper *)
Definition at line 192 of file ExceptionWrapper.h.
Referenced by folly::exception_wrapper::operator=(), and folly::exception_wrapper::reset().
std::exception const*(* folly::exception_wrapper::VTable::get_exception_) (exception_wrapper const *)
Definition at line 195 of file ExceptionWrapper.h.
Referenced by folly::exception_wrapper::get_exception().
exception_wrapper(* folly::exception_wrapper::VTable::get_exception_ptr_) (exception_wrapper const *)
Definition at line 196 of file ExceptionWrapper.h.
Referenced by folly::exception_wrapper::to_exception_ptr().
void(* folly::exception_wrapper::VTable::move_) (exception_wrapper *, exception_wrapper *)
Definition at line 191 of file ExceptionWrapper.h.
void(* folly::exception_wrapper::VTable::throw_) (exception_wrapper const *)
Definition at line 193 of file ExceptionWrapper.h.
Referenced by folly::exception_wrapper::throw_exception().
std::type_info const*(* folly::exception_wrapper::VTable::type_) (exception_wrapper const *)
Definition at line 194 of file ExceptionWrapper.h.
Referenced by folly::exception_wrapper::type().
The documentation for this struct was generated from the following file:
proxygen/folly/folly/ExceptionWrapper.h