proxygen: counted_ptr_base< Atom > Struct Template Reference
counted_ptr_base< Atom > Struct Template Reference
#include <AtomicSharedPtrCounted.h>
Static Protected Member Functions
static intrusive_shared_count< Atom > * getRef (void *pt)
Detailed Description
template<template< typename > class Atom = std::atomic>
struct counted_ptr_base< Atom >
Definition at line 35 of file AtomicSharedPtrCounted.h.
Member Function Documentation
template<template< typename > class Atom = std::atomic> static intrusive_shared_count<Atom>* counted_ptr_base< Atom >::getRef (void * pt) inline static protected
Definition at line 37 of file AtomicSharedPtrCounted.h.
References Atom.
Referenced by counted_ptr< T, Atom >::counted_ptr(), counted_ptr_internals< Atom >::inc_shared_count(), and counted_ptr< T, Atom >::operator=().
{
     char* p = (char*)pt;
     p -= sizeof(intrusive_shared_count<Atom>);
     return (intrusive_shared_count<Atom>*)p;
   }
The documentation for this struct was generated from the following file:
proxygen/folly/folly/concurrency/test/AtomicSharedPtrCounted.h