proxygen: folly::threadlocal_detail::ThreadEntryNode Struct Reference
folly::threadlocal_detail::ThreadEntryNode Struct Reference
#include <ThreadLocalDetail.h>
Public Member Functions
void initIfZero (bool locked)
void init (ThreadEntry *entry, uint32_t newId)
void initZero (ThreadEntry *entry, uint32_t newId)
FOLLY_ALWAYS_INLINE bool empty () const
FOLLY_ALWAYS_INLINE bool zero () const
FOLLY_ALWAYS_INLINE ThreadEntry * getThreadEntry ()
FOLLY_ALWAYS_INLINE ThreadEntryNode * getPrev ()
FOLLY_ALWAYS_INLINE ThreadEntryNode * getNext ()
void push_back (ThreadEntry *head)
void eraseZero ()
Public Attributes
uint32_t id
ThreadEntry * parent
ThreadEntry * prev
ThreadEntry * next
Detailed Description
Definition at line 73 of file ThreadLocalDetail.h.
Member Function Documentation
FOLLY_ALWAYS_INLINE bool folly::threadlocal_detail::ThreadEntryNode::empty () const inline
Definition at line 93 of file ThreadLocalDetail.h.
{
     return (next == parent);
   }
void folly::threadlocal_detail::ThreadEntryNode::eraseZero ()
Definition at line 52 of file ThreadLocalDetail.cpp.
References folly::threadlocal_detail::ThreadEntry::elements, id, LIKELY, next, folly::threadlocal_detail::ElementWrapper::node, and prev.
{
   if (LIKELY(prev != nullptr)) {
     // get the prev and next nodes
     ThreadEntryNode* nprev = &prev->elements[id].node;
     ThreadEntryNode* nnext = &next->elements[id].node;
     // update the prev and next
     nnext->prev = prev;
     nprev->next = next;
     // set the prev and next to nullptr
     next = prev = nullptr;
   }
 }
FOLLY_ALWAYS_INLINE ThreadEntryNode * folly::threadlocal_detail::ThreadEntryNode::getNext ()
Definition at line 239 of file ThreadLocalDetail.h.
References cpp.ast::next().
Referenced by folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::increment(), and folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::incrementToValid().
{
   return &next->elements[id].node;
 }
FOLLY_ALWAYS_INLINE ThreadEntryNode * folly::threadlocal_detail::ThreadEntryNode::getPrev ()
Definition at line 235 of file ThreadLocalDetail.h.
Referenced by folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::decrement(), and folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::decrementToValid().
{
   return &prev->elements[id].node;
 }
FOLLY_ALWAYS_INLINE ThreadEntry* folly::threadlocal_detail::ThreadEntryNode::getThreadEntry () inline
Definition at line 101 of file ThreadLocalDetail.h.
References FOLLY_ALWAYS_INLINE, parent, and push_back().
Referenced by folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::dereference(), and folly::ThreadLocalPtr< T, Tag, AccessMode >::Accessor::Iterator::valid().
{
     return parent;
   }
void folly::threadlocal_detail::ThreadEntryNode::init (ThreadEntry * entry, uint32_t newId) inline
Definition at line 81 of file ThreadLocalDetail.h.
Referenced by folly::threadlocal_detail::StaticMetaBase::reserveHeadUnlocked().
{
     id = newId;
     parent = prev = next = entry;
   }
void folly::threadlocal_detail::ThreadEntryNode::initIfZero (bool locked)
Definition at line 28 of file ThreadLocalDetail.cpp.
References LIKELY, folly::threadlocal_detail::ThreadEntry::meta, next, parent, folly::threadlocal_detail::StaticMetaBase::pushBackLocked(), folly::threadlocal_detail::StaticMetaBase::pushBackUnlocked(), and UNLIKELY.
Referenced by folly::threadlocal_detail::StaticMeta< Tag, AccessMode >::onForkChild().
{
   if (UNLIKELY(!next)) {
     if (LIKELY(locked)) {
       parent->meta->pushBackLocked(parent, id);
     } else {
       parent->meta->pushBackUnlocked(parent, id);
     }
   }
 }
void folly::threadlocal_detail::ThreadEntryNode::initZero (ThreadEntry * entry, uint32_t newId) inline
Definition at line 86 of file ThreadLocalDetail.h.
Referenced by folly::threadlocal_detail::StaticMeta< Tag, AccessMode >::onForkChild(), and folly::threadlocal_detail::StaticMetaBase::reserve().
{
     id = newId;
     parent = entry;
     prev = next = nullptr;
   }
void folly::threadlocal_detail::ThreadEntryNode::push_back (ThreadEntry * head)
Definition at line 38 of file ThreadLocalDetail.cpp.
References folly::threadlocal_detail::ThreadEntry::elements, id, next, folly::threadlocal_detail::ElementWrapper::node, parent, and prev.
Referenced by folly::threadlocal_detail::StaticMetaBase::pushBackLocked(), and folly::threadlocal_detail::StaticMetaBase::pushBackUnlocked().
{
   // get the head prev and next nodes
   ThreadEntryNode* hnode = &head->elements[id].node;
   // update current
   next = head;
   prev = hnode->prev;
   // hprev
   ThreadEntryNode* hprev = &hnode->prev->elements[id].node;
   hprev->next = parent;
   hnode->prev = parent;
 }
FOLLY_ALWAYS_INLINE bool folly::threadlocal_detail::ThreadEntryNode::zero () const inline
Definition at line 97 of file ThreadLocalDetail.h.
Referenced by folly::threadlocal_detail::StaticMeta< Tag, AccessMode >::onForkChild().
{
     return (!prev);
   }
Member Data Documentation
uint32_t folly::threadlocal_detail::ThreadEntryNode::id
Definition at line 74 of file ThreadLocalDetail.h.
Referenced by eraseZero(), and push_back().
ThreadEntry* folly::threadlocal_detail::ThreadEntryNode::next
Definition at line 77 of file ThreadLocalDetail.h.
Referenced by eraseZero(), initIfZero(), and push_back().
ThreadEntry* folly::threadlocal_detail::ThreadEntryNode::parent
Definition at line 75 of file ThreadLocalDetail.h.
Referenced by initIfZero(), and push_back().
ThreadEntry* folly::threadlocal_detail::ThreadEntryNode::prev
Definition at line 76 of file ThreadLocalDetail.h.
Referenced by eraseZero(), and push_back().
The documentation for this struct was generated from the following files:
proxygen/folly/folly/detail/ThreadLocalDetail.h
proxygen/folly/folly/detail/ThreadLocalDetail.cpp