proxygen: AddressFlags Struct Reference
AddressFlags Struct Reference
Public Member Functions
AddressFlags (const std::string &addr, uint8_t version_, uint8_t flags_)
bool isLoopback () const
bool isNonroutable () const
bool isPrivate () const
bool isZero () const
bool isLinkLocal () const
bool isLinkLocalBroadcast () const
Public Attributes
std::string address
uint8_t flags
uint8_t version
Static Public Attributes
static const uint8_t IS_LOCAL = 1 << 0
static const uint8_t IS_NONROUTABLE = 1 << 1
static const uint8_t IS_PRIVATE = 1 << 2
static const uint8_t IS_ZERO = 1 << 3
static const uint8_t IS_LINK_LOCAL = 1 << 4
static const uint8_t IS_MULTICAST = 1 << 5
static const uint8_t IS_LINK_LOCAL_BROADCAST = 1 << 6
Detailed Description
Definition at line 65 of file IPAddressTest.cpp.
Constructor & Destructor Documentation
AddressFlags::AddressFlags (const std::string & addr, uint8_t version_, uint8_t flags_) inline
Definition at line 78 of file IPAddressTest.cpp.
       : address(addr), flags(flags_), version(version_) {}
Member Function Documentation
bool AddressFlags::isLinkLocal () const inline
Definition at line 93 of file IPAddressTest.cpp.
Referenced by TEST_P().
{
     return (flags & IS_LINK_LOCAL);
   }
bool AddressFlags::isLinkLocalBroadcast () const inline
Definition at line 96 of file IPAddressTest.cpp.
Referenced by TEST_P().
{
     return (flags & IS_LINK_LOCAL_BROADCAST);
   }
bool AddressFlags::isLoopback () const inline
Definition at line 81 of file IPAddressTest.cpp.
Referenced by TEST_P().
{
     return (flags & IS_LOCAL);
   }
bool AddressFlags::isNonroutable () const inline
Definition at line 84 of file IPAddressTest.cpp.
Referenced by TEST_P().
{
     return (flags & IS_NONROUTABLE);
   }
bool AddressFlags::isPrivate () const inline
Definition at line 87 of file IPAddressTest.cpp.
Referenced by TEST_P().
{
     return (flags & IS_PRIVATE);
   }
bool AddressFlags::isZero () const inline
Definition at line 90 of file IPAddressTest.cpp.
Referenced by TEST_P().
                       {
     return (flags & IS_ZERO);
   }
Member Data Documentation
std::string AddressFlags::address
Definition at line 66 of file IPAddressTest.cpp.
Referenced by TEST_P().
uint8_t AddressFlags::flags
Definition at line 67 of file IPAddressTest.cpp.
const uint8_t AddressFlags::IS_LINK_LOCAL = 1 << 4 static
Definition at line 74 of file IPAddressTest.cpp.
const uint8_t AddressFlags::IS_LINK_LOCAL_BROADCAST = 1 << 6 static
Definition at line 76 of file IPAddressTest.cpp.
const uint8_t AddressFlags::IS_LOCAL = 1 << 0 static
Definition at line 70 of file IPAddressTest.cpp.
const uint8_t AddressFlags::IS_MULTICAST = 1 << 5 static
Definition at line 75 of file IPAddressTest.cpp.
const uint8_t AddressFlags::IS_NONROUTABLE = 1 << 1 static
Definition at line 71 of file IPAddressTest.cpp.
const uint8_t AddressFlags::IS_PRIVATE = 1 << 2 static
Definition at line 72 of file IPAddressTest.cpp.
const uint8_t AddressFlags::IS_ZERO = 1 << 3 static
Definition at line 73 of file IPAddressTest.cpp.
uint8_t AddressFlags::version
Definition at line 68 of file IPAddressTest.cpp.
Referenced by TEST_P().
The documentation for this struct was generated from the following file:
proxygen/folly/folly/test/IPAddressTest.cpp