proxygen: testing::internal::CodeLocation Struct Reference
testing::internal::CodeLocation Struct Reference
#include <gtest-internal.h>
Public Member Functions
CodeLocation (const string &a_file, int a_line)
CodeLocation (const string &a_file, int a_line)
CodeLocation (const string &a_file, int a_line)
Public Attributes
string file
int line
Detailed Description
Definition at line 504 of file gtest-internal.h.
Constructor & Destructor Documentation
testing::internal::CodeLocation::CodeLocation (const string & a_file, int a_line) inline
Definition at line 505 of file gtest-internal.h.
 : file(a_file), line(a_line) {}
testing::internal::CodeLocation::CodeLocation (const string & a_file, int a_line) inline
Definition at line 505 of file gtest-internal.h.
References testing::internal::posix::Abort(), testing::internal::AlwaysFalse(), testing::internal::AlwaysTrue(), upload::dest, file, testing::internal::FormatFileLocation(), testing::internal::GetCurrentOsStackTraceExceptTop(), GTEST_API_, GTEST_CHECK_, testing::internal::IsSpace(), line, testing::internal::MakeAndRegisterTestInfo(), name, prefix(), testing::internal::SkipPrefix(), testing::internal::SplitString(), testing::internal::StreamableToString(), string, and testing::internal::StripTrailingSpaces().
 : file(a_file), line(a_line) {}
testing::internal::CodeLocation::CodeLocation (const string & a_file, int a_line) inline
Definition at line 505 of file gtest-internal.h.
References testing::internal::posix::Abort(), testing::internal::AlwaysFalse(), testing::internal::AlwaysTrue(), upload::dest, file, testing::internal::FormatFileLocation(), testing::internal::GetCurrentOsStackTraceExceptTop(), GTEST_API_, GTEST_CHECK_, testing::internal::IsSpace(), line, testing::internal::MakeAndRegisterTestInfo(), name, prefix(), testing::internal::SkipPrefix(), testing::internal::SplitString(), testing::internal::StreamableToString(), string, and testing::internal::StripTrailingSpaces().
 : file(a_file), line(a_line) {}
Member Data Documentation
string testing::internal::CodeLocation::file
Definition at line 507 of file gtest-internal.h.
Referenced by CodeLocation(), and testing::internal::MakeAndRegisterTestInfo().
int testing::internal::CodeLocation::line
Definition at line 508 of file gtest-internal.h.
Referenced by pump.Cursor::__add__(), pump.Cursor::__eq__(), pump.Cursor::__init__(), pump.Cursor::__lt__(), pump.Cursor::__str__(), pump.Cursor::__sub__(), pump.Cursor::Clone(), CodeLocation(), and testing::internal::MakeAndRegisterTestInfo().
The documentation for this struct was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/include/gtest/internal/gtest-internal.h