proxygen: folly::TypeError Struct Reference
folly::TypeError Struct Reference
#include <dynamic-inl.h>
Public Member Functions
TypeError (const std::string &expected, dynamic::Type actual)
TypeError (const std::string &expected, dynamic::Type actual1, dynamic::Type actual2)
TypeError (const TypeError &) noexcept(std::is_nothrow_copy_constructible< std::runtime_error >::value)
TypeError & operator= (const TypeError &) noexcept(std::is_nothrow_copy_assignable< std::runtime_error >::value)
TypeError (TypeError &&) noexcept(std::is_nothrow_move_constructible< std::runtime_error >::value)
TypeError & operator= (TypeError &&) noexcept(std::is_nothrow_move_assignable< std::runtime_error >::value)
~TypeError () override
Detailed Description
Definition at line 131 of file dynamic-inl.h.
Constructor & Destructor Documentation
folly::TypeError::TypeError (const std::string & expected, dynamic::Type actual) explicit
Definition at line 49 of file dynamic.cpp.
Referenced by TypeError().
     : std::runtime_error(sformat(
           "TypeError: expected dynamic type `{}', but had type `{}'",
           expected,
           dynamic::typeName(actual))) {}
folly::TypeError::TypeError (const std::string & expected, dynamic::Type actual1, dynamic::Type actual2) explicit
Definition at line 55 of file dynamic.cpp.
References folly::pushmi::__adl::noexcept(), operator=(), TypeError(), value, and ~TypeError().
     : std::runtime_error(sformat(
           "TypeError: expected dynamic types `{}, but had types `{}' and `{}'",
           expected,
           dynamic::typeName(actual1),
           dynamic::typeName(actual2))) {}
folly::TypeError::TypeError (const TypeError &) const default noexcept
folly::TypeError::TypeError (TypeError &&) const default noexcept
folly::TypeError::~TypeError () override default
Referenced by TypeError().
Member Function Documentation
TypeError & folly::TypeError::operator= (const TypeError &) default noexcept
Referenced by TypeError().
TypeError & folly::TypeError::operator= (TypeError &&) default noexcept
The documentation for this struct was generated from the following files:
proxygen/folly/folly/dynamic-inl.h
proxygen/folly/folly/dynamic.cpp