proxygen: fizz::detail::ReadVector< bits24, T > Struct Template Reference
fizz::detail::ReadVector< bits24, T > Struct Template Reference
#include <Types-inl.h>
Public Member Functions
size_t readVector (std::vector< T > &out, folly::io::Cursor &cursor)
Detailed Description
template<class T>
struct fizz::detail::ReadVector< bits24, T >
Definition at line 283 of file Types-inl.h.
Member Function Documentation
template<class T > size_t fizz::detail::ReadVector< bits24, T >::readVector (std::vector< T > & out, folly::io::Cursor & cursor) inline
Definition at line 284 of file Types-inl.h.
References fizz::detail::read(), fizz::detail::readBits24(), fizz::detail::bits24::size, T, and folly::io::detail::CursorBase< Derived, BufType >::totalLength().
{
     auto len = readBits24(cursor);
     if (cursor.totalLength() < len) {
       throw std::out_of_range("Not enough data");
     }
     size_t consumed = 0;
     while (consumed < len) {
       out.push_back(T());
       consumed += read(*out.rbegin(), cursor);
     }
     if (consumed != len) {
       throw std::runtime_error("Invalid data length supplied");
     }
     return len + bits24::size;
   }
The documentation for this struct was generated from the following file:
proxygen/fizz/fizz/record/Types-inl.h