proxygen: folly::pushmi::make_flow_single_sender_fn Struct Reference
folly::pushmi::make_flow_single_sender_fn Struct Reference
#include <flow_single_sender.h>
Public Member Functions
auto operator() () const
requires True PUSHMI_BROKEN_SUBSUMPTION not auto operator() (SF sf) const
requires True &&Invocable< EXF & > PUSHMI_BROKEN_SUBSUMPTION not auto operator() (SF sf, EXF exf) const
requires True &&Sender< Data, is_single<>, is_flow<> > auto operator() (Data d) const
requires Sender< Data, is_single<>, is_flow<> > auto operator() (Data d, DSF sf) const
requires Sender< Data, is_single<>, is_flow<> > &&Invocable< DEXF &, Data & > auto operator() (Data d, DSF sf, DEXF exf) const
Detailed Description
Definition at line 195 of file flow_single_sender.h.
Member Function Documentation
auto folly::pushmi::make_flow_single_sender_fn::operator() () const inline
Definition at line 196 of file flow_single_sender.h.
References PUSHMI_BROKEN_SUBSUMPTION, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return flow_single_sender<ignoreSF, trampolineEXF>{};
   }
requires True PUSHMI_BROKEN_SUBSUMPTION not auto folly::pushmi::make_flow_single_sender_fn::operator() (SF sf) const inline
Definition at line 201 of file flow_single_sender.h.
References folly::gen::move, PUSHMI_BROKEN_SUBSUMPTION, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return flow_single_sender<SF, trampolineEXF>{std::move(sf)};
   }
requires True&& Invocable<EXF&> PUSHMI_BROKEN_SUBSUMPTION not auto folly::pushmi::make_flow_single_sender_fn::operator() (SF sf, EXF exf) const inline
Definition at line 207 of file flow_single_sender.h.
References folly::gen::move, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return flow_single_sender<SF, EXF>{std::move(sf), std::move(exf)};
   }
requires True&& Sender<Data, is_single<>, is_flow<> > auto folly::pushmi::make_flow_single_sender_fn::operator() (Data d) const inline
Definition at line 212 of file flow_single_sender.h.
References folly::gen::move, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return flow_single_sender<Data, passDSF, passDEXF>{std::move(d)};
   }
requires Sender<Data, is_single<>, is_flow<> > auto folly::pushmi::make_flow_single_sender_fn::operator() (Data d, DSF sf) const inline
Definition at line 217 of file flow_single_sender.h.
References folly::gen::move, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return flow_single_sender<Data, DSF, passDEXF>{std::move(d), std::move(sf)};
   }
requires Sender<Data, is_single<>, is_flow<> >&& Invocable<DEXF&, Data&> auto folly::pushmi::make_flow_single_sender_fn::operator() (Data d, DSF sf, DEXF exf) const inline
Definition at line 222 of file flow_single_sender.h.
References folly::pushmi::make_flow_single_sender, folly::gen::move, PUSHMI_BROKEN_SUBSUMPTION, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return flow_single_sender<Data, DSF, DEXF>{std::move(d),
       std::move(sf), std::move(exf)};
   }
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/pushmi/flow_single_sender.h