proxygen: folly::exception_wrapper::InPlace< Ex > Struct Template Reference
folly::exception_wrapper::InPlace< Ex > Struct Template Reference
Static Public Member Functions
static void copy_ (exception_wrapper const *from, exception_wrapper *to)
static void move_ (exception_wrapper *from, exception_wrapper *to)
static void delete_ (exception_wrapper *that)
static void throw_ (exception_wrapper const *that)
static std::type_info const * type_ (exception_wrapper const *)
static std::exception const * get_exception_ (exception_wrapper const *that)
static exception_wrapper get_exception_ptr_ (exception_wrapper const *that)
Static Public Attributes
static constexpr VTable const ops_
Detailed Description
template<class Ex>
struct folly::exception_wrapper::InPlace< Ex >
Definition at line 284 of file ExceptionWrapper.h.
Member Function Documentation
template<class Ex > void folly::exception_wrapper::InPlace< Ex >::copy_ (exception_wrapper const * from, exception_wrapper * to) inline static
Definition at line 182 of file ExceptionWrapper-inl.h.
References folly::exception_wrapper::Buffer::as(), and folly::exception_wrapper::buff_.
{
   ::new (static_cast<void*>(std::addressof(to->buff_.as<Ex>())))
       Ex(from->buff_.as<Ex>());
 }
template<class Ex > void folly::exception_wrapper::InPlace< Ex >::delete_ (exception_wrapper * that) inline static
Definition at line 197 of file ExceptionWrapper-inl.h.
References folly::exception_wrapper::Buffer::as(), folly::exception_wrapper::buff_, folly::exception_wrapper::uninit_, and folly::exception_wrapper::vptr_.
{
   that->buff_.as<Ex>().~Ex();
   that->vptr_ = &uninit_;
 }
template<class Ex > std::exception const * folly::exception_wrapper::InPlace< Ex >::get_exception_ (exception_wrapper const * that) inline static
Definition at line 212 of file ExceptionWrapper-inl.h.
References folly::exception_wrapper::Buffer::as(), folly::exception_wrapper::as_exception_or_null_(), and folly::exception_wrapper::buff_.
{
   return as_exception_or_null_(that->buff_.as<Ex>());
 }
template<class Ex > exception_wrapper folly::exception_wrapper::InPlace< Ex >::get_exception_ptr_ (exception_wrapper const * that) inline static
Definition at line 217 of file ExceptionWrapper-inl.h.
{
   try {
     throw_(that);
   } catch (Ex const& ex) {
     return exception_wrapper{std::current_exception(), ex};
   }
 }
template<class Ex > void folly::exception_wrapper::InPlace< Ex >::move_ (exception_wrapper * from, exception_wrapper * to) inline static
Definition at line 189 of file ExceptionWrapper-inl.h.
References folly::exception_wrapper::Buffer::as(), folly::exception_wrapper::buff_, and folly::gen::move.
{
   ::new (static_cast<void*>(std::addressof(to->buff_.as<Ex>())))
       Ex(std::move(from->buff_.as<Ex>()));
   delete_(from);
 }
template<class Ex > void folly::exception_wrapper::InPlace< Ex >::throw_ (exception_wrapper const * that) inline static
Definition at line 202 of file ExceptionWrapper-inl.h.
References folly::exception_wrapper::Buffer::as(), and folly::exception_wrapper::buff_.
{
   throw that->buff_.as<Ex>(); // @nolint
 }
template<class Ex > std::type_info const * folly::exception_wrapper::InPlace< Ex >::type_ (exception_wrapper const *) inline static
Definition at line 207 of file ExceptionWrapper-inl.h.
{
   return &typeid(Ex);
 }
Member Data Documentation
template<class Ex > constexpr exception_wrapper::VTable folly::exception_wrapper::InPlace< Ex >::ops_ static
Initial value:
{copy_,
                                       move_,
                                       delete_,
                                       throw_,
                                       type_,
                                       get_exception_,
                                       get_exception_ptr_}
Definition at line 293 of file ExceptionWrapper.h.
The documentation for this struct was generated from the following files:
proxygen/folly/folly/ExceptionWrapper.h
proxygen/folly/folly/ExceptionWrapper-inl.h