proxygen: folly::test::DeterministicMutex Struct Reference
folly::test::DeterministicMutex Struct Reference
#include <DeterministicSchedule.h>
Public Member Functions
DeterministicMutex ()=default
~DeterministicMutex ()=default
DeterministicMutex (DeterministicMutex const &)=delete
DeterministicMutex & operator= (DeterministicMutex const &)=delete
void lock ()
bool try_lock ()
void unlock ()
Public Attributes
std::mutex m
std::queue< sem_t * > waiters_
Detailed Description
DeterministicMutex is a drop-in replacement of std::mutex that cooperates with DeterministicSchedule.
Definition at line 496 of file DeterministicSchedule.h.
Constructor & Destructor Documentation
folly::test::DeterministicMutex::DeterministicMutex () default
folly::test::DeterministicMutex::~DeterministicMutex () default
folly::test::DeterministicMutex::DeterministicMutex (DeterministicMutex const &) delete
Member Function Documentation
void folly::test::DeterministicMutex::lock () inline
Definition at line 505 of file DeterministicSchedule.h.
References folly::test::DeterministicSchedule::afterSharedAccess(), folly::test::DeterministicSchedule::beforeSharedAccess(), folly::test::DeterministicSchedule::descheduleCurrentThread(), and FOLLY_TEST_DSCHED_VLOG.
Referenced by TEST().
               {
     FOLLY_TEST_DSCHED_VLOG(this << ".lock()");
     DeterministicSchedule::beforeSharedAccess();
     while (!m.try_lock()) {
       sem_t* sem = DeterministicSchedule::descheduleCurrentThread();
       if (sem) {
         waiters_.push(sem);
       }
       DeterministicSchedule::afterSharedAccess();
       // Wait to be scheduled by unlock
       DeterministicSchedule::beforeSharedAccess();
     }
     DeterministicSchedule::afterSharedAccess();
   }
DeterministicMutex& folly::test::DeterministicMutex::operator= (DeterministicMutex const &) delete
bool folly::test::DeterministicMutex::try_lock () inline
Definition at line 520 of file DeterministicSchedule.h.
References folly::test::DeterministicSchedule::afterSharedAccess(), folly::test::DeterministicSchedule::beforeSharedAccess(), and FOLLY_TEST_DSCHED_VLOG.
Referenced by TEST().
                   {
     DeterministicSchedule::beforeSharedAccess();
     bool rv = m.try_lock();
     FOLLY_TEST_DSCHED_VLOG(this << ".try_lock() -> " << rv);
     DeterministicSchedule::afterSharedAccess();
     return rv;
   }
void folly::test::DeterministicMutex::unlock () inline
Definition at line 528 of file DeterministicSchedule.h.
References folly::test::DeterministicSchedule::afterSharedAccess(), folly::test::DeterministicSchedule::beforeSharedAccess(), FOLLY_TEST_DSCHED_VLOG, folly::AccessSpreader< Atom >::pickGetcpuFunc(), and folly::test::DeterministicSchedule::reschedule().
Referenced by TEST().
                 {
     FOLLY_TEST_DSCHED_VLOG(this << ".unlock()");
     m.unlock();
     DeterministicSchedule::beforeSharedAccess();
     if (!waiters_.empty()) {
       sem_t* sem = waiters_.front();
       DeterministicSchedule::reschedule(sem);
       waiters_.pop();
     }
     DeterministicSchedule::afterSharedAccess();
   }
Member Data Documentation
std::mutex folly::test::DeterministicMutex::m
Definition at line 497 of file DeterministicSchedule.h.
std::queue<sem_t*> folly::test::DeterministicMutex::waiters_
Definition at line 498 of file DeterministicSchedule.h.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/test/DeterministicSchedule.h