proxygen: proxygen::TraceEvent::MetaData::ConvVisitor< std::string > Struct Template Reference
proxygen::TraceEvent::MetaData::ConvVisitor< std::string > Struct Template Reference
#include <TraceEvent.h>
Public Member Functions
std::string operator() (const std::vector< std::string > &operand) const
template<typename U >
std::string operator() (U &operand) const
Detailed Description
template<>
struct proxygen::TraceEvent::MetaData::ConvVisitor< std::string >
Definition at line 295 of file TraceEvent.h.
Member Function Documentation
std::string proxygen::TraceEvent::MetaData::ConvVisitor< std::string >::operator() (const std::vector< std::string > & operand) const
Definition at line 106 of file TraceEvent.cpp.
References folly::dynamic::array(), data, folly::dynamic::push_back(), and folly::toJson().
{
   // parse string vector to json string.
   folly::dynamic data = folly::dynamic::array;
   for (auto item : operand) {
     data.push_back(item);
   }
   return folly::toJson(data);
 }
template<typename U > std::string proxygen::TraceEvent::MetaData::ConvVisitor< std::string >::operator() (U & operand) const inline
Definition at line 300 of file TraceEvent.h.
{
     return folly::to<std::string>(operand);
   }
The documentation for this struct was generated from the following files:
proxygen/lib/utils/TraceEvent.h
proxygen/lib/utils/TraceEvent.cpp