proxygen: AnnotatedAtomicCounter< T > Struct Template Reference
AnnotatedAtomicCounter< T > Struct Template Reference
Inherits Base< T >.
Public Member Functions
void setAuxChk ()
void clearAuxChk ()
void auxLog (uint64_t step)
void doAuxLog (uint64_t step)
void auxCheck ()
T loadDirect ()
AnnotatedAtomicCounter (int val)
void inc ()
void incBug ()
Detailed Description
template<typename T>
struct AnnotatedAtomicCounter< T >
Forward declaration of annotated template
Annotated shared class
Definition at line 170 of file DeterministicScheduleTest.cpp.
Constructor & Destructor Documentation
template<typename T > AnnotatedAtomicCounter< T >::AnnotatedAtomicCounter (int val) inline explicit
Definition at line 320 of file DeterministicScheduleTest.cpp.
 : Base<T>(val) {}
Member Function Documentation
template<typename T > void AnnotatedAtomicCounter< T >::auxCheck () inline
Definition at line 303 of file DeterministicScheduleTest.cpp.
References counter_, AuxData::lastUpdate_, AuxData::step_, sum(), folly::pushmi::detail::t, and AuxData::t_.
                   {
     /* Liveness */
     CHECK_LT(aux_->step_, aux_->lastUpdate_ + FLAGS_liveness_thresh);
     /* Safety */
     int sum = {0};
     for (auto& t : aux_->t_) {
       sum += t.count_;
     }
     CHECK_EQ(this->counter_.load_direct(), sum);
   }
template<typename T > void AnnotatedAtomicCounter< T >::auxLog (uint64_t step) inline
Aux log function
Definition at line 273 of file DeterministicScheduleTest.cpp.
References AuxData::lastUpdate_, AuxData::step_, and uint64_t.
{
     if (aux_->step_ == 0) {
       aux_->lastUpdate_ = step;
     }
     aux_->step_ = step;
     if (step > (uint64_t)FLAGS_max_steps) {
       exit(0);
     }
     bool doLog =
         (((FLAGS_log_begin > 0) && (step >= (uint64_t)FLAGS_log_begin) &&
           (step <= (uint64_t)FLAGS_log_begin + FLAGS_log_length)) ||
          ((step % FLAGS_log_freq) == 0));
     if (doLog) {
       doAuxLog(step);
     }
   }
template<typename T > void AnnotatedAtomicCounter< T >::clearAuxChk () inline
Definition at line 268 of file DeterministicScheduleTest.cpp.
References folly::test::DeterministicSchedule::clearAuxChk().
Referenced by TEST().
                      {
     DeterministicSchedule::clearAuxChk();
   }
template<typename T > void AnnotatedAtomicCounter< T >::doAuxLog (uint64_t step) inline
Definition at line 290 of file DeterministicScheduleTest.cpp.
References AUX_THR, counter_, AuxData::lastUpdate_, and tid_.
Referenced by TEST().
{
     std::stringstream ss;
     /* General */
     ss << step << " - " << aux_->lastUpdate_ << " --";
     /* Shared */
     ss << " counter =" << this->counter_.load_direct();
     /* Thread */
     ss << " -- t" << tid_ << " " << AUX_THR(func_) << ":" << AUX_THR(line_);
     ss << " count[" << tid_ << "] = " << AUX_THR(count_);
     /* Output */
     std::cerr << ss.str() << std::endl;
   }
template<typename T > void AnnotatedAtomicCounter< T >::inc () inline
Definition at line 324 of file DeterministicScheduleTest.cpp.
References AUX_ACT, AUX_THR, and counter_.
Referenced by TEST().
              {
     AUX_ACT({ ++AUX_THR(count_); });
     this->counter_.fetch_add(1);
   }
template<typename T > void AnnotatedAtomicCounter< T >::incBug () inline
Definition at line 329 of file DeterministicScheduleTest.cpp.
References AUX_ACT, AUX_THR, counter_, and folly::T.
Referenced by TEST().
                 {
     AUX_ACT({});
     T newval = this->counter_.load() + 1;
     AUX_ACT({ ++AUX_THR(count_); });
     this->counter_.store(newval);
   }
template<typename T > T AnnotatedAtomicCounter< T >::loadDirect () inline
Definition at line 315 of file DeterministicScheduleTest.cpp.
References counter_.
Referenced by TEST().
                  {
     return this->counter_.load_direct();
   }
template<typename T > void AnnotatedAtomicCounter< T >::setAuxChk () inline
Manage DSched auxChk
Definition at line 260 of file DeterministicScheduleTest.cpp.
References folly::test::DeterministicSchedule::setAuxChk(), and uint64_t.
Referenced by TEST().
                    {
     AuxChk auxfn([&](uint64_t step) {
       auxLog(step);
       auxCheck();
     });
     DeterministicSchedule::setAuxChk(auxfn);
   }
The documentation for this struct was generated from the following file:
proxygen/folly/folly/test/DeterministicScheduleTest.cpp