proxygen: folly::AtomicHashMap< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::ahm_iterator< ContT, IterVal, SubIt > Struct Template Reference
folly::AtomicHashMap< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::ahm_iterator< ContT, IterVal, SubIt > Struct Template Reference
#include <AtomicHashMap-inl.h>
Public Member Functions
ahm_iterator ()
template<class OtherContT , class OtherVal , class OtherSubIt >
ahm_iterator (const ahm_iterator< OtherContT, OtherVal, OtherSubIt > &o, typename std::enable_if< std::is_convertible< OtherSubIt, SubIt >::value >::type *=nullptr)
uint32_t getIndex () const
Private Member Functions
ahm_iterator (ContT *ahm, uint32_t subMap, const SubIt &subIt)
void increment ()
bool equal (const ahm_iterator &other) const
IterVal & dereference () const
bool isEnd () const
void checkAdvanceToNextSubmap ()
Private Attributes
ContT * ahm_
uint32_t subMap_
SubIt subIt_
Friends
class AtomicHashMap
Detailed Description
template<class KeyT, class ValueT, class HashFcn, class EqualFcn, class Allocator, class ProbeFcn, class KeyConvertFcn>
template<class ContT, class IterVal, class SubIt>
struct folly::AtomicHashMap< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::ahm_iterator< ContT, IterVal, SubIt >
Definition at line 561 of file AtomicHashMap-inl.h.
Constructor & Destructor Documentation
template<class KeyT, class ValueT, class HashFcn, class EqualFcn, class Allocator, class ProbeFcn, class KeyConvertFcn> template<class ContT, class IterVal, class SubIt> folly::AtomicHashMap< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::ahm_iterator< ContT, IterVal, SubIt >::ahm_iterator () inline explicit
Definition at line 573 of file AtomicHashMap-inl.h.
 : ahm_(nullptr) {}
template<class KeyT, class ValueT, class HashFcn, class EqualFcn, class Allocator, class ProbeFcn, class KeyConvertFcn> template<class ContT, class IterVal, class SubIt> template<class OtherContT , class OtherVal , class OtherSubIt > folly::AtomicHashMap< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::ahm_iterator< ContT, IterVal, SubIt >::ahm_iterator (const ahm_iterator< OtherContT, OtherVal, OtherSubIt > & o, typename std::enable_if< std::is_convertible< OtherSubIt, SubIt >::value >::type * = nullptr) inline
Definition at line 579 of file AtomicHashMap-inl.h.
       : ahm_(o.ahm_), subMap_(o.subMap_), subIt_(o.subIt_) {}
template<class KeyT, class ValueT, class HashFcn, class EqualFcn, class Allocator, class ProbeFcn, class KeyConvertFcn> template<class ContT, class IterVal, class SubIt> folly::AtomicHashMap< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::ahm_iterator< ContT, IterVal, SubIt >::ahm_iterator (ContT * ahm, uint32_t subMap, const SubIt & subIt) inline explicit private
Definition at line 596 of file AtomicHashMap-inl.h.
       : ahm_(ahm), subMap_(subMap), subIt_(subIt) {}
Member Function Documentation
template<class KeyT, class ValueT, class HashFcn, class EqualFcn, class Allocator, class ProbeFcn, class KeyConvertFcn> template<class ContT, class IterVal, class SubIt> void folly::AtomicHashMap< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::ahm_iterator< ContT, IterVal, SubIt >::checkAdvanceToNextSubmap () inline private
Definition at line 627 of file AtomicHashMap-inl.h.
References folly::AtomicHashArray< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::begin(), and folly::AtomicHashArray< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::end().
{
     if (isEnd()) {
       return;
     }
     SubMap* thisMap = ahm_->subMaps_[subMap_].load(std::memory_order_relaxed);
     while (subIt_ == thisMap->end()) {
       // This sub iterator is done, advance to next one
       if (subMap_ + 1 <
           ahm_->numMapsAllocated_.load(std::memory_order_acquire)) {
         ++subMap_;
         thisMap = ahm_->subMaps_[subMap_].load(std::memory_order_relaxed);
         subIt_ = thisMap->begin();
       } else {
         ahm_ = nullptr;
         return;
       }
     }
   }
template<class KeyT, class ValueT, class HashFcn, class EqualFcn, class Allocator, class ProbeFcn, class KeyConvertFcn> template<class ContT, class IterVal, class SubIt> IterVal& folly::AtomicHashMap< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::ahm_iterator< ContT, IterVal, SubIt >::dereference () const inline private
Definition at line 619 of file AtomicHashMap-inl.h.
{
     return *subIt_;
   }
template<class KeyT, class ValueT, class HashFcn, class EqualFcn, class Allocator, class ProbeFcn, class KeyConvertFcn> template<class ContT, class IterVal, class SubIt> bool folly::AtomicHashMap< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::ahm_iterator< ContT, IterVal, SubIt >::equal (const ahm_iterator< ContT, IterVal, SubIt > & other) const inline private
Definition at line 607 of file AtomicHashMap-inl.h.
References folly::AtomicHashMap< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::ahm_iterator< ContT, IterVal, SubIt >::ahm_, folly::AtomicHashMap< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::ahm_iterator< ContT, IterVal, SubIt >::isEnd(), folly::AtomicHashMap< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::ahm_iterator< ContT, IterVal, SubIt >::subIt_, and folly::AtomicHashMap< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::ahm_iterator< ContT, IterVal, SubIt >::subMap_.
{
     if (ahm_ != other.ahm_) {
       return false;
     }
     if (isEnd() || other.isEnd()) {
       return isEnd() == other.isEnd();
     }
     return subMap_ == other.subMap_ && subIt_ == other.subIt_;
   }
template<class KeyT, class ValueT, class HashFcn, class EqualFcn, class Allocator, class ProbeFcn, class KeyConvertFcn> template<class ContT, class IterVal, class SubIt> uint32_t folly::AtomicHashMap< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::ahm_iterator< ContT, IterVal, SubIt >::getIndex () const inline
Definition at line 589 of file AtomicHashMap-inl.h.
Referenced by TEST().
{
     CHECK(!isEnd());
     return ahm_->encodeIndex(subMap_, subIt_.getIndex());
   }
template<class KeyT, class ValueT, class HashFcn, class EqualFcn, class Allocator, class ProbeFcn, class KeyConvertFcn> template<class ContT, class IterVal, class SubIt> void folly::AtomicHashMap< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::ahm_iterator< ContT, IterVal, SubIt >::increment () inline private
Definition at line 601 of file AtomicHashMap-inl.h.
                    {
     CHECK(!isEnd());
     ++subIt_;
     checkAdvanceToNextSubmap();
   }
template<class KeyT, class ValueT, class HashFcn, class EqualFcn, class Allocator, class ProbeFcn, class KeyConvertFcn> template<class ContT, class IterVal, class SubIt> bool folly::AtomicHashMap< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::ahm_iterator< ContT, IterVal, SubIt >::isEnd () const inline private
Definition at line 623 of file AtomicHashMap-inl.h.
Referenced by folly::AtomicHashMap< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::ahm_iterator< ContT, IterVal, SubIt >::equal().
                      {
     return ahm_ == nullptr;
   }
Friends And Related Function Documentation
template<class KeyT, class ValueT, class HashFcn, class EqualFcn, class Allocator, class ProbeFcn, class KeyConvertFcn> template<class ContT, class IterVal, class SubIt> friend class AtomicHashMap friend
Definition at line 595 of file AtomicHashMap-inl.h.
Member Data Documentation
template<class KeyT, class ValueT, class HashFcn, class EqualFcn, class Allocator, class ProbeFcn, class KeyConvertFcn> template<class ContT, class IterVal, class SubIt> ContT* folly::AtomicHashMap< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::ahm_iterator< ContT, IterVal, SubIt >::ahm_ private
Definition at line 648 of file AtomicHashMap-inl.h.
Referenced by folly::AtomicHashMap< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::ahm_iterator< ContT, IterVal, SubIt >::equal().
template<class KeyT, class ValueT, class HashFcn, class EqualFcn, class Allocator, class ProbeFcn, class KeyConvertFcn> template<class ContT, class IterVal, class SubIt> SubIt folly::AtomicHashMap< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::ahm_iterator< ContT, IterVal, SubIt >::subIt_ private
Definition at line 650 of file AtomicHashMap-inl.h.
Referenced by folly::AtomicHashMap< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::ahm_iterator< ContT, IterVal, SubIt >::equal().
template<class KeyT, class ValueT, class HashFcn, class EqualFcn, class Allocator, class ProbeFcn, class KeyConvertFcn> template<class ContT, class IterVal, class SubIt> uint32_t folly::AtomicHashMap< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::ahm_iterator< ContT, IterVal, SubIt >::subMap_ private
Definition at line 649 of file AtomicHashMap-inl.h.
Referenced by folly::AtomicHashMap< KeyT, ValueT, HashFcn, EqualFcn, Allocator, ProbeFcn, KeyConvertFcn >::ahm_iterator< ContT, IterVal, SubIt >::equal().
The documentation for this struct was generated from the following file:
proxygen/folly/folly/AtomicHashMap-inl.h