proxygen: testing::gmock_matchers_test::ReferencingFunctor Struct Reference
testing::gmock_matchers_test::ReferencingFunctor Struct Reference
Public Types
typedef const int * result_type
typedef const int * result_type
typedef const int * result_type
Public Member Functions
result_type operator() (const int &n)
result_type operator() (const int &n)
result_type operator() (const int &n)
Detailed Description
Definition at line 3946 of file gmock-matchers_test.cc.
Member Typedef Documentation
typedef const int* testing::gmock_matchers_test::ReferencingFunctor::result_type
Definition at line 3947 of file gmock-matchers_test.cc.
typedef const int* testing::gmock_matchers_test::ReferencingFunctor::result_type
Definition at line 3947 of file gmock-matchers_test.cc.
typedef const int* testing::gmock_matchers_test::ReferencingFunctor::result_type
Definition at line 3947 of file gmock-matchers_test.cc.
Member Function Documentation
result_type testing::gmock_matchers_test::ReferencingFunctor::operator() (const int & n) inline
Definition at line 3948 of file gmock-matchers_test.cc.
 { return &n; }
result_type testing::gmock_matchers_test::ReferencingFunctor::operator() (const int & n) inline
Definition at line 3948 of file gmock-matchers_test.cc.
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), testing::gmock_matchers_test::ReferencingFunction(), testing::ResultOf(), and testing::internal::TEST().
 { return &n; }
result_type testing::gmock_matchers_test::ReferencingFunctor::operator() (const int & n) inline
Definition at line 3948 of file gmock-matchers_test.cc.
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), testing::gmock_matchers_test::ReferencingFunction(), testing::ResultOf(), and testing::internal::TEST().
 { return &n; }
The documentation for this struct was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-matchers_test.cc