proxygen: folly::DynamicConstructor< std::vector< bool >, void > Struct Template Reference
folly::DynamicConstructor< std::vector< bool >, void > Struct Template Reference
#include <DynamicConverter.h>
Static Public Member Functions
static dynamic construct (const std::vector< bool > &x)
Detailed Description
template<>
struct folly::DynamicConstructor< std::vector< bool >, void >
Definition at line 377 of file DynamicConverter.h.
Member Function Documentation
static dynamic folly::DynamicConstructor< std::vector< bool >, void >::construct (const std::vector< bool > & x) inline static
Definition at line 378 of file DynamicConverter.h.
References folly::dynamic::array(), folly::dynamic::push_back(), and folly::toDynamic().
{
     dynamic d = dynamic::array;
     // Intentionally specifying the type as bool here.
     // std::vector<bool>'s iterators return a proxy which is a prvalue
     // and hence cannot bind to an lvalue reference such as auto&
     for (bool item : x) {
       d.push_back(toDynamic(item));
     }
     return d;
   }
The documentation for this struct was generated from the following file:
proxygen/folly/folly/DynamicConverter.h