proxygen: non_atomic< T > Struct Template Reference
non_atomic< T > Struct Template Reference
Public Member Functions
non_atomic ()=default
non_atomic (const non_atomic &)=delete
constexpr non_atomic (T desired)
T operator+= (T arg)
T load (std::memory_order=std::memory_order_seq_cst) const
operator T () const
void store (T desired, std::memory_order=std::memory_order_seq_cst)
T exchange (T desired, std::memory_order=std::memory_order_seq_cst)
bool compare_exchange_weak (T &expected, T desired, std::memory_order=std::memory_order_seq_cst, std::memory_order=std::memory_order_seq_cst)
bool compare_exchange_strong (T &expected, T desired, std::memory_order=std::memory_order_seq_cst, std::memory_order=std::memory_order_seq_cst)
bool is_lock_free () const
Public Attributes
T value
Detailed Description
template<class T>
struct non_atomic< T >
Definition at line 33 of file AtomicUnorderedMapTest.cpp.
Constructor & Destructor Documentation
template<class T > non_atomic< T >::non_atomic () default
template<class T > non_atomic< T >::non_atomic (const non_atomic< T > &) delete
template<class T > constexpr non_atomic< T >::non_atomic (T desired) inline
Definition at line 38 of file AtomicUnorderedMapTest.cpp.
 : value(desired) {}
Member Function Documentation
template<class T > bool non_atomic< T >::compare_exchange_strong (T & expected, T desired, std::memory_order = std::memory_order_seq_cst, std::memory_order = std::memory_order_seq_cst) inline
Definition at line 82 of file AtomicUnorderedMapTest.cpp.
References folly::value().
{
     if (value == expected) {
       value = desired;
       return true;
     }
     expected = value;
     return false;
   }
template<class T > bool non_atomic< T >::compare_exchange_weak (T & expected, T desired, std::memory_order = std::memory_order_seq_cst, std::memory_order = std::memory_order_seq_cst) inline
Definition at line 68 of file AtomicUnorderedMapTest.cpp.
References folly::value().
{
     if (value == expected) {
       value = desired;
       return true;
     }
     expected = value;
     return false;
   }
template<class T > T non_atomic< T >::exchange (T desired, std::memory_order = std::memory_order_seq_cst) inline
Definition at line 60 of file AtomicUnorderedMapTest.cpp.
References deadlock::load(), and folly::T.
{
     T old = load();
     store(desired);
     return old;
   }
template<class T > bool non_atomic< T >::is_lock_free () const inline
Definition at line 96 of file AtomicUnorderedMapTest.cpp.
References Atom, testing::Key(), value, and testing::Value().
{
     return true;
   }
template<class T > T non_atomic< T >::load (std::memory_order = std::memory_order_seq_cst) const inline
Definition at line 45 of file AtomicUnorderedMapTest.cpp.
References folly::value().
{
     return value;
   }
template<class T > non_atomic< T >::operator T () const inline
Definition at line 50 of file AtomicUnorderedMapTest.cpp.
References deadlock::load().
                      {
     return load();
   }
template<class T > T non_atomic< T >::operator+= (T arg) inline
Definition at line 40 of file AtomicUnorderedMapTest.cpp.
References deadlock::load().
                       {
     value += arg;
     return load();
   }
template<class T > void non_atomic< T >::store (T desired, std::memory_order = std::memory_order_seq_cst) inline
Definition at line 54 of file AtomicUnorderedMapTest.cpp.
{
     value = desired;
   }
Member Data Documentation
template<class T > T non_atomic< T >::value
Definition at line 34 of file AtomicUnorderedMapTest.cpp.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/test/AtomicUnorderedMapTest.cpp