proxygen: folly::pushmi::make_time_single_sender_fn Struct Reference
folly::pushmi::make_time_single_sender_fn Struct Reference
#include <time_single_sender.h>
Public Member Functions
auto operator() () const
requires True PUSHMI_BROKEN_SUBSUMPTION not auto operator() (SF sf) const
requires Invocable< EXF & > PUSHMI_BROKEN_SUBSUMPTION not auto operator() (SF sf, EXF exf) const
requires Invocable< NF & > &&Invocable< EXF & > PUSHMI_BROKEN_SUBSUMPTION not auto operator() (SF sf, EXF exf, NF nf) const
requires TimeSender< Data, is_single<> > auto operator() (Data d) const
requires TimeSender< Data, is_single<> > auto operator() (Data d, DSF sf) const
requires TimeSender< Data, is_single<> > &&Invocable< DEXF &, Data & > auto operator() (Data d, DSF sf, DEXF exf) const
requires TimeSender< Data, is_single<> > &&Invocable< DNF &, Data & > &&Invocable< DEXF &, Data & > auto operator() (Data d, DSF sf, DEXF exf, DNF nf) const
Detailed Description
Definition at line 90 of file time_single_sender.h.
Member Function Documentation
auto folly::pushmi::make_time_single_sender_fn::operator() () const inline
Definition at line 91 of file time_single_sender.h.
References PUSHMI_BROKEN_SUBSUMPTION, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return time_single_sender<ignoreSF, systemNowF, inlineTimeEXF>{};
   }
requires True PUSHMI_BROKEN_SUBSUMPTION not auto folly::pushmi::make_time_single_sender_fn::operator() (SF sf) const inline
Definition at line 96 of file time_single_sender.h.
References folly::gen::move, PUSHMI_BROKEN_SUBSUMPTION, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return time_single_sender<SF, systemNowF, inlineTimeEXF>{std::move(sf)};
   }
requires Invocable<EXF&> PUSHMI_BROKEN_SUBSUMPTION not auto folly::pushmi::make_time_single_sender_fn::operator() (SF sf, EXF exf) const inline
Definition at line 101 of file time_single_sender.h.
References folly::gen::move, PUSHMI_BROKEN_SUBSUMPTION, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return time_single_sender<SF, systemNowF, EXF>{
       std::move(sf), std::move(exf)};
   }
requires Invocable<NF&>&& Invocable<EXF&> PUSHMI_BROKEN_SUBSUMPTION not auto folly::pushmi::make_time_single_sender_fn::operator() (SF sf, EXF exf, NF nf) const inline
Definition at line 107 of file time_single_sender.h.
References folly::gen::move, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return time_single_sender<SF, NF, EXF>{
       std::move(sf), std::move(exf), std::move(nf)};
   }
requires TimeSender<Data, is_single<> > auto folly::pushmi::make_time_single_sender_fn::operator() (Data d) const inline
Definition at line 113 of file time_single_sender.h.
References folly::gen::move, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return time_single_sender<Data, passDSF, passDNF, passDEXF>{std::move(d)};
   }
requires TimeSender<Data, is_single<> > auto folly::pushmi::make_time_single_sender_fn::operator() (Data d, DSF sf) const inline
Definition at line 118 of file time_single_sender.h.
References folly::gen::move, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return time_single_sender<Data, DSF, passDNF, passDEXF>{
       std::move(d), std::move(sf)};
   }
requires TimeSender<Data, is_single<> >&& Invocable<DEXF&, Data&> auto folly::pushmi::make_time_single_sender_fn::operator() (Data d, DSF sf, DEXF exf) const inline
Definition at line 124 of file time_single_sender.h.
References folly::gen::move, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return time_single_sender<Data, DSF, passDNF, DEXF>{
       std::move(d), std::move(sf), std::move(exf)};
   }
requires TimeSender<Data, is_single<> >&& Invocable<DNF&, Data&>&& Invocable<DEXF&, Data&> auto folly::pushmi::make_time_single_sender_fn::operator() (Data d, DSF sf, DEXF exf, DNF nf) const inline
Definition at line 131 of file time_single_sender.h.
References folly::pushmi::make_time_single_sender, folly::gen::move, PUSHMI_BROKEN_SUBSUMPTION, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return time_single_sender<Data, DSF, DNF, DEXF>{
       std::move(d), std::move(sf), std::move(exf), std::move(nf)};
   }
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/pushmi/time_single_sender.h