proxygen: folly::SingletonThreadLocal< T, Tag, Make, TLTag >::Node Struct Reference
folly::SingletonThreadLocal< T, Tag, Make, TLTag >::Node Struct Reference
Public Member Functions
Node (Wrapper *&cache_, bool &stale_)
~Node ()
void clear ()
Public Attributes
Wrapper *& cache
bool & stale
Detailed Description
template<typename T, typename Tag = detail::DefaultTag, typename Make = detail::DefaultMake<T>, typename TLTag = _t<std::conditional< std::is_same<Tag, detail::DefaultTag>::value, void, Tag>>>
struct folly::SingletonThreadLocal< T, Tag, Make, TLTag >::Node
Definition at line 75 of file SingletonThreadLocal.h.
Constructor & Destructor Documentation
template<typename T, typename Tag = detail::DefaultTag, typename Make = detail::DefaultMake<T>, typename TLTag = _t<std::conditional< std::is_same<Tag, detail::DefaultTag>::value, void, Tag>>> folly::SingletonThreadLocal< T, Tag, Make, TLTag >::Node::Node (Wrapper *& cache_, bool & stale_) inline
Definition at line 79 of file SingletonThreadLocal.h.
References folly::SingletonThreadLocal< T, Tag, Make, TLTag >::getWrapper().
                                          : cache(cache_), stale(stale_) {
       auto& wrapper = getWrapper();
       wrapper.caches.push_front(*this);
       cache = &wrapper;
     }
template<typename T, typename Tag = detail::DefaultTag, typename Make = detail::DefaultMake<T>, typename TLTag = _t<std::conditional< std::is_same<Tag, detail::DefaultTag>::value, void, Tag>>> folly::SingletonThreadLocal< T, Tag, Make, TLTag >::Node::~Node () inline
Definition at line 84 of file SingletonThreadLocal.h.
References folly::SingletonThreadLocal< T, Tag, Make, TLTag >::Node::clear().
             {
       clear();
     }
Member Function Documentation
template<typename T, typename Tag = detail::DefaultTag, typename Make = detail::DefaultMake<T>, typename TLTag = _t<std::conditional< std::is_same<Tag, detail::DefaultTag>::value, void, Tag>>> void folly::SingletonThreadLocal< T, Tag, Make, TLTag >::Node::clear () inline
Definition at line 88 of file SingletonThreadLocal.h.
Referenced by folly::SingletonThreadLocal< T, Tag, Make, TLTag >::Node::~Node().
                  {
       cache = nullptr;
       stale = true;
     }
Member Data Documentation
template<typename T, typename Tag = detail::DefaultTag, typename Make = detail::DefaultMake<T>, typename TLTag = _t<std::conditional< std::is_same<Tag, detail::DefaultTag>::value, void, Tag>>> Wrapper*& folly::SingletonThreadLocal< T, Tag, Make, TLTag >::Node::cache
Definition at line 76 of file SingletonThreadLocal.h.
Referenced by folly::SingletonThreadLocal< T, Tag, Make, TLTag >::get(), and folly::SingletonThreadLocal< T, Tag, Make, TLTag >::getWrapper().
template<typename T, typename Tag = detail::DefaultTag, typename Make = detail::DefaultMake<T>, typename TLTag = _t<std::conditional< std::is_same<Tag, detail::DefaultTag>::value, void, Tag>>> bool& folly::SingletonThreadLocal< T, Tag, Make, TLTag >::Node::stale
Definition at line 77 of file SingletonThreadLocal.h.
Referenced by folly::SingletonThreadLocal< T, Tag, Make, TLTag >::getWrapper().
The documentation for this struct was generated from the following file:
proxygen/folly/folly/SingletonThreadLocal.h