proxygen: folly::test::DeterministicAtomicImpl< T, Schedule, Atom > Struct Template Reference
folly::test::DeterministicAtomicImpl< T, Schedule, Atom > Struct Template Reference
#include <DeterministicSchedule.h>
Public Member Functions
DeterministicAtomicImpl ()=default
~DeterministicAtomicImpl ()=default
DeterministicAtomicImpl (DeterministicAtomicImpl< T > const &)=delete
DeterministicAtomicImpl< T > & operator= (DeterministicAtomicImpl< T > const &)=delete
constexpr DeterministicAtomicImpl (T v) noexcept
bool is_lock_free () const noexcept
bool compare_exchange_strong (T &v0, T v1, std::memory_order mo=std::memory_order_seq_cst) noexcept
bool compare_exchange_strong (T &v0, T v1, std::memory_order success, std::memory_order failure) noexcept
bool compare_exchange_weak (T &v0, T v1, std::memory_order mo=std::memory_order_seq_cst) noexcept
bool compare_exchange_weak (T &v0, T v1, std::memory_order success, std::memory_order failure) noexcept
T exchange (T v, std::memory_order mo=std::memory_order_seq_cst) noexcept
operator T () const noexcept
T load (std::memory_order mo=std::memory_order_seq_cst) const noexcept
T operator= (T v) noexcept
void store (T v, std::memory_order mo=std::memory_order_seq_cst) noexcept
T operator++ () noexcept
T operator++ (int) noexcept
T operator-- () noexcept
T operator-- (int) noexcept
T operator+= (T v) noexcept
T fetch_add (T v, std::memory_order mo=std::memory_order_seq_cst) noexcept
T operator-= (T v) noexcept
T fetch_sub (T v, std::memory_order mo=std::memory_order_seq_cst) noexcept
T operator&= (T v) noexcept
T fetch_and (T v, std::memory_order mo=std::memory_order_seq_cst) noexcept
T operator|= (T v) noexcept
T fetch_or (T v, std::memory_order mo=std::memory_order_seq_cst) noexcept
T operator^= (T v) noexcept
T fetch_xor (T v, std::memory_order mo=std::memory_order_seq_cst) noexcept
T load_direct () const noexcept
Private Attributes
Atom< T > data_
Detailed Description
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic>
struct folly::test::DeterministicAtomicImpl< T, Schedule, Atom >
DeterministicAtomic<T> is a drop-in replacement std::atomic<T> that cooperates with DeterministicSchedule.
Definition at line 229 of file DeterministicSchedule.h.
Constructor & Destructor Documentation
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::DeterministicAtomicImpl () default
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::~DeterministicAtomicImpl () default
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::DeterministicAtomicImpl (DeterministicAtomicImpl< T > const &) delete
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> constexpr folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::DeterministicAtomicImpl (T v) inline noexcept
Definition at line 236 of file DeterministicSchedule.h.
 : data_(v) {}
Member Function Documentation
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> bool folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::compare_exchange_strong (T & v0, T v1, std::memory_order mo = std::memory_order_seq_cst) inline noexcept
Definition at line 242 of file DeterministicSchedule.h.
References folly::detail::default_failure_memory_order().
{
     return compare_exchange_strong(
         v0, v1, mo, ::folly::detail::default_failure_memory_order(mo));
   }
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> bool folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::compare_exchange_strong (T & v0, T v1, std::memory_order success, std::memory_order failure) inline noexcept
Definition at line 249 of file DeterministicSchedule.h.
References data_, FOLLY_TEST_DSCHED_VLOG, and folly::detail::success.
{
     Schedule::beforeSharedAccess();
     auto orig = v0;
     bool rv = data_.compare_exchange_strong(v0, v1, success, failure);
     FOLLY_TEST_DSCHED_VLOG(
         this << ".compare_exchange_strong(" << std::hex << orig << ", "
              << std::hex << v1 << ") -> " << rv << "," << std::hex << v0);
     Schedule::afterSharedAccess(rv);
     return rv;
   }
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> bool folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::compare_exchange_weak (T & v0, T v1, std::memory_order mo = std::memory_order_seq_cst) inline noexcept
Definition at line 264 of file DeterministicSchedule.h.
References folly::detail::default_failure_memory_order().
{
     return compare_exchange_weak(
         v0, v1, mo, ::folly::detail::default_failure_memory_order(mo));
   }
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> bool folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::compare_exchange_weak (T & v0, T v1, std::memory_order success, std::memory_order failure) inline noexcept
Definition at line 271 of file DeterministicSchedule.h.
References data_, FOLLY_TEST_DSCHED_VLOG, and folly::detail::success.
{
     Schedule::beforeSharedAccess();
     auto orig = v0;
     bool rv = data_.compare_exchange_weak(v0, v1, success, failure);
     FOLLY_TEST_DSCHED_VLOG(
         this << ".compare_exchange_weak(" << std::hex << orig << ", "
              << std::hex << v1 << ") -> " << rv << "," << std::hex << v0);
     Schedule::afterSharedAccess(rv);
     return rv;
   }
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> T folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::exchange (T v, std::memory_order mo = std::memory_order_seq_cst) inline noexcept
Definition at line 286 of file DeterministicSchedule.h.
References data_, FOLLY_TEST_DSCHED_VLOG, and folly::T.
{
     Schedule::beforeSharedAccess();
     T rv = data_.exchange(v, mo);
     FOLLY_TEST_DSCHED_VLOG(
         this << ".exchange(" << std::hex << v << ") -> " << std::hex << rv);
     Schedule::afterSharedAccess(true);
     return rv;
   }
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> T folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::fetch_add (T v, std::memory_order mo = std::memory_order_seq_cst) inline noexcept
Definition at line 367 of file DeterministicSchedule.h.
References data_, FOLLY_TEST_DSCHED_VLOG, and folly::T.
{
     Schedule::beforeSharedAccess();
     T rv = data_.fetch_add(v, mo);
     FOLLY_TEST_DSCHED_VLOG(
         this << ".fetch_add(" << std::hex << v << ") -> " << std::hex << rv);
     Schedule::afterSharedAccess(true);
     return rv;
   }
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> T folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::fetch_and (T v, std::memory_order mo = std::memory_order_seq_cst) inline noexcept
Definition at line 403 of file DeterministicSchedule.h.
References data_, FOLLY_TEST_DSCHED_VLOG, and folly::T.
{
     Schedule::beforeSharedAccess();
     T rv = data_.fetch_and(v, mo);
     FOLLY_TEST_DSCHED_VLOG(
         this << ".fetch_and(" << std::hex << v << ") -> " << std::hex << rv);
     Schedule::afterSharedAccess(true);
     return rv;
   }
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> T folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::fetch_or (T v, std::memory_order mo = std::memory_order_seq_cst) inline noexcept
Definition at line 421 of file DeterministicSchedule.h.
References data_, FOLLY_TEST_DSCHED_VLOG, and folly::T.
{
     Schedule::beforeSharedAccess();
     T rv = data_.fetch_or(v, mo);
     FOLLY_TEST_DSCHED_VLOG(
         this << ".fetch_or(" << std::hex << v << ") -> " << std::hex << rv);
     Schedule::afterSharedAccess(true);
     return rv;
   }
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> T folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::fetch_sub (T v, std::memory_order mo = std::memory_order_seq_cst) inline noexcept
Definition at line 385 of file DeterministicSchedule.h.
References data_, FOLLY_TEST_DSCHED_VLOG, and folly::T.
{
     Schedule::beforeSharedAccess();
     T rv = data_.fetch_sub(v, mo);
     FOLLY_TEST_DSCHED_VLOG(
         this << ".fetch_sub(" << std::hex << v << ") -> " << std::hex << rv);
     Schedule::afterSharedAccess(true);
     return rv;
   }
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> T folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::fetch_xor (T v, std::memory_order mo = std::memory_order_seq_cst) inline noexcept
Definition at line 439 of file DeterministicSchedule.h.
References data_, FOLLY_TEST_DSCHED_VLOG, and folly::T.
{
     Schedule::beforeSharedAccess();
     T rv = data_.fetch_xor(v, mo);
     FOLLY_TEST_DSCHED_VLOG(
         this << ".fetch_xor(" << std::hex << v << ") -> " << std::hex << rv);
     Schedule::afterSharedAccess(true);
     return rv;
   }
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> bool folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::is_lock_free () const inline noexcept
Definition at line 238 of file DeterministicSchedule.h.
References data_.
{
     return data_.is_lock_free();
   }
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> T folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::load (std::memory_order mo = std::memory_order_seq_cst) const inline noexcept
Definition at line 303 of file DeterministicSchedule.h.
References data_, FOLLY_TEST_DSCHED_VLOG, and folly::T.
Referenced by TEST_F().
{
     Schedule::beforeSharedAccess();
     T rv = data_.load(mo);
     FOLLY_TEST_DSCHED_VLOG(this << ".load() -> " << std::hex << rv);
     Schedule::afterSharedAccess(true);
     return rv;
   }
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> T folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::load_direct () const inline noexcept
Read the value of the atomic variable without context switching
Definition at line 449 of file DeterministicSchedule.h.
References data_.
{
     return data_.load(std::memory_order_relaxed);
   }
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::operator T () const inline noexcept
Definition at line 295 of file DeterministicSchedule.h.
References data_, FOLLY_TEST_DSCHED_VLOG, and folly::T.
{
     Schedule::beforeSharedAccess();
     T rv = data_.operator T();
     FOLLY_TEST_DSCHED_VLOG(this << "() -> " << std::hex << rv);
     Schedule::afterSharedAccess(true);
     return rv;
   }
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> T folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::operator&= (T v) inline noexcept
Definition at line 394 of file DeterministicSchedule.h.
References data_, FOLLY_TEST_DSCHED_VLOG, folly::T, and v.
{
     Schedule::beforeSharedAccess();
     T rv = (data_ &= v);
     FOLLY_TEST_DSCHED_VLOG(
         this << " &= " << std::hex << v << " -> " << std::hex << rv);
     Schedule::afterSharedAccess(true);
     return rv;
   }
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> T folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::operator++ () inline noexcept
Definition at line 326 of file DeterministicSchedule.h.
References data_, FOLLY_TEST_DSCHED_VLOG, and folly::T.
{
     Schedule::beforeSharedAccess();
     T rv = ++data_;
     FOLLY_TEST_DSCHED_VLOG(this << " pre++ -> " << std::hex << rv);
     Schedule::afterSharedAccess(true);
     return rv;
   }
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> T folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::operator++ (int) inline noexcept
Definition at line 334 of file DeterministicSchedule.h.
References data_, FOLLY_TEST_DSCHED_VLOG, and folly::T.
{
     Schedule::beforeSharedAccess();
     T rv = data_++;
     FOLLY_TEST_DSCHED_VLOG(this << " post++ -> " << std::hex << rv);
     Schedule::afterSharedAccess(true);
     return rv;
   }
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> T folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::operator+= (T v) inline noexcept
Definition at line 358 of file DeterministicSchedule.h.
References data_, FOLLY_TEST_DSCHED_VLOG, folly::T, and v.
{
     Schedule::beforeSharedAccess();
     T rv = (data_ += v);
     FOLLY_TEST_DSCHED_VLOG(
         this << " += " << std::hex << v << " -> " << std::hex << rv);
     Schedule::afterSharedAccess(true);
     return rv;
   }
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> T folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::operator-- () inline noexcept
Definition at line 342 of file DeterministicSchedule.h.
References data_, FOLLY_TEST_DSCHED_VLOG, and folly::T.
{
     Schedule::beforeSharedAccess();
     T rv = --data_;
     FOLLY_TEST_DSCHED_VLOG(this << " pre-- -> " << std::hex << rv);
     Schedule::afterSharedAccess(true);
     return rv;
   }
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> T folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::operator-- (int) inline noexcept
Definition at line 350 of file DeterministicSchedule.h.
References data_, FOLLY_TEST_DSCHED_VLOG, and folly::T.
{
     Schedule::beforeSharedAccess();
     T rv = data_--;
     FOLLY_TEST_DSCHED_VLOG(this << " post-- -> " << std::hex << rv);
     Schedule::afterSharedAccess(true);
     return rv;
   }
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> T folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::operator-= (T v) inline noexcept
Definition at line 376 of file DeterministicSchedule.h.
References data_, FOLLY_TEST_DSCHED_VLOG, folly::T, and v.
{
     Schedule::beforeSharedAccess();
     T rv = (data_ -= v);
     FOLLY_TEST_DSCHED_VLOG(
         this << " -= " << std::hex << v << " -> " << std::hex << rv);
     Schedule::afterSharedAccess(true);
     return rv;
   }
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> DeterministicAtomicImpl<T>& folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::operator= (DeterministicAtomicImpl< T > const &) delete
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> T folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::operator= (T v) inline noexcept
Definition at line 311 of file DeterministicSchedule.h.
References data_, FOLLY_TEST_DSCHED_VLOG, folly::T, and v.
{
     Schedule::beforeSharedAccess();
     T rv = (data_ = v);
     FOLLY_TEST_DSCHED_VLOG(this << " = " << std::hex << v);
     Schedule::afterSharedAccess(true);
     return rv;
   }
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> T folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::operator^= (T v) inline noexcept
Definition at line 430 of file DeterministicSchedule.h.
References data_, FOLLY_TEST_DSCHED_VLOG, folly::T, and v.
{
     Schedule::beforeSharedAccess();
     T rv = (data_ ^= v);
     FOLLY_TEST_DSCHED_VLOG(
         this << " ^= " << std::hex << v << " -> " << std::hex << rv);
     Schedule::afterSharedAccess(true);
     return rv;
   }
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> T folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::operator|= (T v) inline noexcept
Definition at line 412 of file DeterministicSchedule.h.
References data_, FOLLY_TEST_DSCHED_VLOG, folly::T, and v.
{
     Schedule::beforeSharedAccess();
     T rv = (data_ |= v);
     FOLLY_TEST_DSCHED_VLOG(
         this << " |= " << std::hex << v << " -> " << std::hex << rv);
     Schedule::afterSharedAccess(true);
     return rv;
   }
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> void folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::store (T v, std::memory_order mo = std::memory_order_seq_cst) inline noexcept
Definition at line 319 of file DeterministicSchedule.h.
References data_, and FOLLY_TEST_DSCHED_VLOG.
Referenced by TEST_F().
{
     Schedule::beforeSharedAccess();
     data_.store(v, mo);
     FOLLY_TEST_DSCHED_VLOG(this << ".store(" << std::hex << v << ")");
     Schedule::afterSharedAccess(true);
   }
Member Data Documentation
template<typename T, typename Schedule = DeterministicSchedule, template< typename > class Atom = std::atomic> Atom<T> folly::test::DeterministicAtomicImpl< T, Schedule, Atom >::data_ private
Definition at line 454 of file DeterministicSchedule.h.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/test/DeterministicSchedule.h