proxygen: testing::gmock_matchers_test::IntReferenceWrapper Struct Reference
testing::gmock_matchers_test::IntReferenceWrapper Struct Reference
Public Member Functions
IntReferenceWrapper (const int &a_value)
IntReferenceWrapper (const int &a_value)
IntReferenceWrapper (const int &a_value)
Public Attributes
const int * value
Detailed Description
Definition at line 643 of file gmock-matchers_test.cc.
Constructor & Destructor Documentation
testing::gmock_matchers_test::IntReferenceWrapper::IntReferenceWrapper (const int & a_value) inline
Definition at line 644 of file gmock-matchers_test.cc.
 : value(&a_value) {}
testing::gmock_matchers_test::IntReferenceWrapper::IntReferenceWrapper (const int & a_value) inline
Definition at line 644 of file gmock-matchers_test.cc.
References EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), testing::internal::operator==(), testing::internal::TEST(), value, and value.
 : value(&a_value) {}
testing::gmock_matchers_test::IntReferenceWrapper::IntReferenceWrapper (const int & a_value) inline
Definition at line 644 of file gmock-matchers_test.cc.
References EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), testing::internal::operator==(), testing::internal::TEST(), value, and value.
 : value(&a_value) {}
Member Data Documentation
const int * testing::gmock_matchers_test::IntReferenceWrapper::value
Definition at line 645 of file gmock-matchers_test.cc.
Referenced by pump.Token::__init__(), pump.Token::__str__(), pump.Token::Clone(), IntReferenceWrapper(), and testing::gmock_matchers_test::operator==().
The documentation for this struct was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-matchers_test.cc