proxygen: folly::detail::AtFork Struct Reference
folly::detail::AtFork Struct Reference
#include <AtFork.h>
Static Public Member Functions
static void init ()
static void registerHandler (void *object, folly::Function< bool()> prepare, folly::Function< void()> parent, folly::Function< void()> child)
static void unregisterHandler (void *object)
Detailed Description
Definition at line 24 of file AtFork.h.
Member Function Documentation
void folly::detail::AtFork::init () static
Definition at line 104 of file AtFork.cpp.
                   {
   AtForkList::instance();
 }
void folly::detail::AtFork::registerHandler (void * object, folly::Function< bool()> prepare, folly::Function< void()> parent, folly::Function< void()> child) static
Definition at line 108 of file AtFork.cpp.
References child, folly::gen::move, object, parent, prepare, and tasksLock.
Referenced by folly::AsyncFileWriter::AsyncFileWriter(), folly::rcu_domain< Tag >::rcu_domain(), folly::threadlocal_detail::StaticMeta< Tag, AccessMode >::StaticMeta(), and TEST().
{
   std::lock_guard<std::mutex> lg(AtForkList::instance().tasksLock);
   AtForkList::instance().tasks.push_back(
       {object, std::move(prepare), std::move(parent), std::move(child)});
 }
void folly::detail::AtFork::unregisterHandler (void * object) static
Definition at line 118 of file AtFork.cpp.
References bm::list.
Referenced by TEST(), folly::AsyncFileWriter::~AsyncFileWriter(), and folly::rcu_domain< Tag >::~rcu_domain().
{
   auto& list = AtForkList::instance();
   std::lock_guard<std::mutex> lg(list.tasksLock);
   for (auto it = list.tasks.begin(); it != list.tasks.end(); ++it) {
     if (it->object == object) {
       list.tasks.erase(it);
       return;
     }
   }
 }
The documentation for this struct was generated from the following files:
proxygen/folly/folly/detail/AtFork.h
proxygen/folly/folly/detail/AtFork.cpp