proxygen: folly::PicoSpinLock< IntType, Bit > Struct Template Reference
folly::PicoSpinLock< IntType, Bit > Struct Template Reference
#include <PicoSpinLock.h>
Public Types
typedef std::make_unsigned< IntType >::type UIntType
Public Member Functions
void init (IntType initialValue=0)
IntType getData () const
void setData (IntType w)
bool try_lock () const
void lock () const
void unlock () const
Public Attributes
UIntType lock_
Static Public Attributes
static const UIntType kLockBitMask_ = UIntType(1) << Bit
Detailed Description
template<class IntType, int Bit = sizeof(IntType) * 8 - 1>
struct folly::PicoSpinLock< IntType, Bit >
Definition at line 73 of file PicoSpinLock.h.
Member Typedef Documentation
template<class IntType, int Bit = sizeof(IntType) * 8 - 1> typedef std::make_unsigned<IntType>::type folly::PicoSpinLock< IntType, Bit >::UIntType
Definition at line 75 of file PicoSpinLock.h.
Member Function Documentation
template<class IntType, int Bit = sizeof(IntType) * 8 - 1> IntType folly::PicoSpinLock< IntType, Bit >::getData () const inline
Definition at line 111 of file PicoSpinLock.h.
Referenced by folly::PackedSyncPtr< T >::extra(), folly::PackedSyncPtr< T >::get(), and folly::PackedSyncPtr< T >::setExtra().
{
     auto res = reinterpret_cast<std::atomic<UIntType>*>(&lock_)->load(
                    std::memory_order_relaxed) &
         ~kLockBitMask_;
     return res;
   }
template<class IntType, int Bit = sizeof(IntType) * 8 - 1> void folly::PicoSpinLock< IntType, Bit >::init (IntType initialValue = 0) inline
Definition at line 96 of file PicoSpinLock.h.
Referenced by folly::PackedSyncPtr< T >::init().
{
     CHECK(!(initialValue & kLockBitMask_));
     reinterpret_cast<std::atomic<UIntType>*>(&lock_)->store(
         UIntType(initialValue), std::memory_order_release);
   }
template<class IntType, int Bit = sizeof(IntType) * 8 - 1> void folly::PicoSpinLock< IntType, Bit >::lock () const inline
Definition at line 229 of file PicoSpinLock.h.
Referenced by folly::PackedSyncPtr< T >::lock().
                     {
     detail::Sleeper sleeper;
     while (!try_lock()) {
       sleeper.wait();
     }
   }
template<class IntType, int Bit = sizeof(IntType) * 8 - 1> void folly::PicoSpinLock< IntType, Bit >::setData (IntType w) inline
Definition at line 124 of file PicoSpinLock.h.
Referenced by folly::PackedSyncPtr< T >::set(), and folly::PackedSyncPtr< T >::setExtra().
{
     CHECK(!(w & kLockBitMask_));
     auto l = reinterpret_cast<std::atomic<UIntType>*>(&lock_);
     l->store(
         (l->load(std::memory_order_relaxed) & kLockBitMask_) | w,
         std::memory_order_relaxed);
   }
template<class IntType, int Bit = sizeof(IntType) * 8 - 1> bool folly::PicoSpinLock< IntType, Bit >::try_lock () const inline
Definition at line 136 of file PicoSpinLock.h.
Referenced by folly::PackedSyncPtr< T >::try_lock().
{
     bool ret = false;
 #if defined(FOLLY_SANITIZE_THREAD)
     // TODO: Might be able to fully move to std::atomic when gcc emits lock btr:
     // https://gcc.gnu.org/bugzilla/show_bug.cgi?id=49244
     ret =
         !(reinterpret_cast<std::atomic<UIntType>*>(&lock_)->fetch_or(
               kLockBitMask_, std::memory_order_acquire) &
           kLockBitMask_);
 #elif _MSC_VER
     switch (sizeof(IntType)) {
       case 2:
         // There is no _interlockedbittestandset16 for some reason :(
         ret = _InterlockedOr16((volatile short*)&lock_, (short)kLockBitMask_) &
             kLockBitMask_;
         break;
       case 4:
         ret = _interlockedbittestandset((volatile long*)&lock_, Bit);
         break;
       case 8:
         ret = _interlockedbittestandset64((volatile long long*)&lock_, Bit);
         break;
     }
 #elif FOLLY_X64
 #define FB_DOBTS(size)                                 \
   asm volatile("lock; bts" #size " %1, (%2); setnc %0" \
                : "=r"(ret)                             \
                : "i"(Bit), "r"(&lock_)                 \
                : "memory", "flags")
     switch (sizeof(IntType)) {
       case 2:
         FB_DOBTS(w);
         break;
       case 4:
         FB_DOBTS(l);
         break;
       case 8:
         FB_DOBTS(q);
         break;
     }
 #undef FB_DOBTS
 #elif FOLLY_AARCH64
     using SIntType = typename std::make_signed<UIntType>::type;
     auto const lock = reinterpret_cast<SIntType*>(&lock_);
     auto const mask = static_cast<SIntType>(kLockBitMask_);
     return !(mask & __atomic_fetch_or(lock, mask, __ATOMIC_ACQUIRE));
 #elif FOLLY_PPC64
 #define FB_DOBTS(size)                        \
   asm volatile(                               \
       "\teieio\n"                             \
       "\tl" #size                             \
       "arx 14,0,%[lockPtr]\n"                 \
       "\tli 15,1\n"                           \
       "\tsldi 15,15,%[bit]\n"                 \
       "\tand. 16,15,14\n"                     \
       "\tbne 0f\n"                            \
       "\tor 14,14,15\n"                       \
       "\tst" #size                            \
       "cx. 14,0,%[lockPtr]\n"                 \
       "\tbne 0f\n"                            \
       "\tori %[output],%[output],1\n"         \
       "\tisync\n"                             \
       "0:\n"                                  \
       : [output] "+r"(ret)                    \
       : [lockPtr] "r"(&lock_), [bit] "i"(Bit) \
       : "cr0", "memory", "r14", "r15", "r16")
     switch (sizeof(IntType)) {
       case 2:
         FB_DOBTS(h);
         break;
       case 4:
         FB_DOBTS(w);
         break;
       case 8:
         FB_DOBTS(d);
         break;
     }
 #undef FB_DOBTS
 #else
 #error "x86 aarch64 ppc64 only"
 #endif
     return ret;
   }
template<class IntType, int Bit = sizeof(IntType) * 8 - 1> void folly::PicoSpinLock< IntType, Bit >::unlock () const inline
Definition at line 240 of file PicoSpinLock.h.
Referenced by folly::PackedSyncPtr< T >::unlock().
                       {
 #ifdef _MSC_VER
     switch (sizeof(IntType)) {
       case 2:
         // There is no _interlockedbittestandreset16 for some reason :(
         _InterlockedAnd16((volatile short*)&lock_, (short)~kLockBitMask_);
         break;
       case 4:
         _interlockedbittestandreset((volatile long*)&lock_, Bit);
         break;
       case 8:
         _interlockedbittestandreset64((volatile long long*)&lock_, Bit);
         break;
     }
 #elif FOLLY_X64
 #define FB_DOBTR(size)                       \
   asm volatile("lock; btr" #size " %0, (%1)" \
                :                             \
                : "i"(Bit), "r"(&lock_)       \
                : "memory", "flags")
     // Reads and writes can not be reordered wrt locked instructions,
     // so we don't need a memory fence here.
     switch (sizeof(IntType)) {
       case 2:
         FB_DOBTR(w);
         break;
       case 4:
         FB_DOBTR(l);
         break;
       case 8:
         FB_DOBTR(q);
         break;
     }
 #undef FB_DOBTR
 #elif FOLLY_AARCH64
     using SIntType = typename std::make_signed<UIntType>::type;
     auto const lock = reinterpret_cast<SIntType*>(&lock_);
     auto const mask = static_cast<SIntType>(kLockBitMask_);
     __atomic_fetch_and(lock, ~mask, __ATOMIC_RELEASE);
 #elif FOLLY_PPC64
 #define FB_DOBTR(size)                        \
   asm volatile(                               \
       "\teieio\n"                             \
       "0:  l" #size                           \
       "arx 14,0,%[lockPtr]\n"                 \
       "\tli 15,1\n"                           \
       "\tsldi 15,15,%[bit]\n"                 \
       "\txor 14,14,15\n"                      \
       "\tst" #size                            \
       "cx. 14,0,%[lockPtr]\n"                 \
       "\tbne 0b\n"                            \
       "\tisync\n"                             \
       :                                       \
       : [lockPtr] "r"(&lock_), [bit] "i"(Bit) \
       : "cr0", "memory", "r14", "r15")
     switch (sizeof(IntType)) {
       case 2:
         FB_DOBTR(h);
         break;
       case 4:
         FB_DOBTR(w);
         break;
       case 8:
         FB_DOBTR(d);
         break;
     }
 #undef FB_DOBTR
 #else
 #error "x64 aarch64 ppc64 only"
 #endif
   }
Member Data Documentation
template<class IntType, int Bit = sizeof(IntType) * 8 - 1> const UIntType folly::PicoSpinLock< IntType, Bit >::kLockBitMask_ = UIntType(1) << Bit static
Definition at line 85 of file PicoSpinLock.h.
template<class IntType, int Bit = sizeof(IntType) * 8 - 1> UIntType folly::PicoSpinLock< IntType, Bit >::lock_ mutable
Definition at line 86 of file PicoSpinLock.h.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/synchronization/PicoSpinLock.h