proxygen: testing::gmock_matchers_test::Functor Struct Reference
testing::gmock_matchers_test::Functor Struct Reference
Public Member Functions
result_type operator() (argument_type input) const
result_type operator() (argument_type input) const
result_type operator() (argument_type input) const
Detailed Description
Definition at line 3910 of file gmock-matchers_test.cc.
Member Function Documentation
result_type testing::gmock_matchers_test::Functor::operator() (argument_type input) const inline
Definition at line 3911 of file gmock-matchers_test.cc.
References testing::gmock_matchers_test::IntToStringFunction().
{
     return IntToStringFunction(input);
   }
result_type testing::gmock_matchers_test::Functor::operator() (argument_type input) const inline
Definition at line 3911 of file gmock-matchers_test.cc.
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, testing::gmock_matchers_test::IntToStringFunction(), testing::internal::MatcherBase< T >::Matches(), testing::ResultOf(), and testing::internal::TEST().
{
     return IntToStringFunction(input);
   }
result_type testing::gmock_matchers_test::Functor::operator() (argument_type input) const inline
Definition at line 3911 of file gmock-matchers_test.cc.
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, testing::gmock_matchers_test::IntToStringFunction(), testing::internal::MatcherBase< T >::Matches(), testing::ResultOf(), and testing::internal::TEST().
{
     return IntToStringFunction(input);
   }
The documentation for this struct was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-matchers_test.cc