proxygen: folly::pushmi::make_receiver_fn Struct Reference
folly::pushmi::make_receiver_fn Struct Reference
#include <receiver.h>
Public Member Functions
auto operator() () const
requires PUSHMI_EXP (lazy::True<> PUSHMI_BROKEN_SUBSUMPTION(PUSHMI_AND not lazy::ReceiverDataArg< VF >))) auto operator()(VF vf) const
template<class... EFN>
auto operator() (on_error_fn< EFN... > ef) const
template<class... DFN>
auto operator() (on_done_fn< DFN... > df) const
requires PUSHMI_EXP (lazy::True<> PUSHMI_BROKEN_SUBSUMPTION(PUSHMI_ANDnot lazy::ReceiverDataArg< VF > PUSHMI_ANDnot lazy::Invocable< EF & >))) auto operator()(VF vf
requires PUSHMI_EXP (lazy::True<> PUSHMI_AND lazy::Invocable< DF & > PUSHMI_BROKEN_SUBSUMPTION(PUSHMI_AND not lazy::ReceiverDataArg< EF >))) auto operator()(EF ef
requires PUSHMI_EXP (lazy::True<> PUSHMI_AND lazy::Invocable< DF & > PUSHMI_BROKEN_SUBSUMPTION(PUSHMI_AND not lazy::ReceiverDataArg< VF >))) auto operator()(VF vf
requires PUSHMI_EXP (lazy::True<> PUSHMI_AND lazy::ReceiverDataArg< Data >)) auto operator()(Data d) const
requires PUSHMI_EXP (lazy::True<> PUSHMI_AND lazy::ReceiverDataArg< Data >)) auto operator()(Data d
requires PUSHMI_EXP (lazy::True<> PUSHMI_AND lazy::ReceiverDataArg< Data >)) auto operator()(Data d
requires PUSHMI_EXP (lazy::True<> PUSHMI_AND lazy::ReceiverDataArg< Data >)) auto operator()(Data d
requires PUSHMI_EXP (lazy::True<> PUSHMI_AND lazy::ReceiverDataArg< Data >)) auto operator()(Data d
requires PUSHMI_EXP (lazy::True<> PUSHMI_AND lazy::ReceiverDataArg< Data >)) auto operator()(Data d
requires PUSHMI_EXP (lazy::True<> PUSHMI_AND lazy::ReceiverDataArg< Data > PUSHMI_AND lazy::Invocable< DDF &, Data & >)) auto operator()(Data d
Public Attributes
requires EF ef const
requires DF df const
requires EF ef
requires EF DF df const
requires DVF vf const
requires on_error_fn< DEFN... > ef const
requires on_done_fn< DDFN... > df const
requires DVF vf
requires DVF on_error_fn< DEFN... > ef const
requires DEF ef
requires DEF on_done_fn< DDFN... > df const
requires DVF DEF ef
requires DVF DEF DDF df const
Detailed Description
Definition at line 313 of file receiver.h.
Member Function Documentation
auto folly::pushmi::make_receiver_fn::operator() () const inline
Definition at line 314 of file receiver.h.
References folly::pushmi::PUSHMI_TEMPLATE().
{
     return receiver<>{};
   }
template<class... EFN> auto folly::pushmi::make_receiver_fn::operator() (on_error_fn< EFN... > ef) const inline
Definition at line 325 of file receiver.h.
References folly::gen::move.
{
     return receiver<ignoreVF, on_error_fn<EFN...>, ignoreDF>{std::move(ef)};
   }
template<class... DFN> auto folly::pushmi::make_receiver_fn::operator() (on_done_fn< DFN... > df) const inline
Definition at line 329 of file receiver.h.
References folly::gen::move, PUSHMI_AND, PUSHMI_BROKEN_SUBSUMPTION, PUSHMI_EXP, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return receiver<ignoreVF, abortEF, on_done_fn<DFN...>>{std::move(df)};
   }
requires folly::pushmi::make_receiver_fn::PUSHMI_EXP (lazy::True<> PUSHMI_BROKEN_SUBSUMPTIONPUSHMI_AND not lazy::ReceiverDataArg< VF >) const inline
Definition at line 318 of file receiver.h.
References folly::gen::move.
{
     return receiver<VF, abortEF, ignoreDF>{std::move(vf)};
   }
requires folly::pushmi::make_receiver_fn::PUSHMI_EXP (lazy::True<> PUSHMI_BROKEN_SUBSUMPTIONPUSHMI_ANDnot lazy::ReceiverDataArg< VF > PUSHMI_ANDnot lazy::Invocable< EF & >)
requires folly::pushmi::make_receiver_fn::PUSHMI_EXP (lazy::True<> PUSHMI_AND lazy::Invocable< DF & > PUSHMI_BROKEN_SUBSUMPTIONPUSHMI_AND not lazy::ReceiverDataArg< EF >)
requires folly::pushmi::make_receiver_fn::PUSHMI_EXP (lazy::True<> PUSHMI_AND lazy::Invocable< DF & > PUSHMI_BROKEN_SUBSUMPTIONPUSHMI_AND not lazy::ReceiverDataArg< VF >)
requires folly::pushmi::make_receiver_fn::PUSHMI_EXP (lazy::True<> PUSHMI_AND lazy::ReceiverDataArg< Data >) const inline
Definition at line 358 of file receiver.h.
References folly::gen::move, PUSHMI_AND, PUSHMI_EXP, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return receiver<Data, passDVF, passDEF, passDDF>{std::move(d)};
   }
requires folly::pushmi::make_receiver_fn::PUSHMI_EXP (lazy::True<> PUSHMI_AND lazy::ReceiverDataArg< Data >)
requires folly::pushmi::make_receiver_fn::PUSHMI_EXP (lazy::True<> PUSHMI_AND lazy::ReceiverDataArg< Data >)
requires folly::pushmi::make_receiver_fn::PUSHMI_EXP (lazy::True<> PUSHMI_AND lazy::ReceiverDataArg< Data >)
requires folly::pushmi::make_receiver_fn::PUSHMI_EXP (lazy::True<> PUSHMI_AND lazy::ReceiverDataArg< Data >)
requires folly::pushmi::make_receiver_fn::PUSHMI_EXP (lazy::True<> PUSHMI_AND lazy::ReceiverDataArg< Data >)
requires folly::pushmi::make_receiver_fn::PUSHMI_EXP (lazy::True<> PUSHMI_AND lazy::ReceiverDataArg< Data > PUSHMI_AND lazy::Invocable< DDF &, Data & >)
Member Data Documentation
requires EF ef folly::pushmi::make_receiver_fn::const
Initial value:
{
    return receiver<VF, EF, ignoreDF>{std::move(vf), std::move(ef)}
Definition at line 338 of file receiver.h.
requires DF df folly::pushmi::make_receiver_fn::const
Initial value:
{
    return receiver<ignoreVF, EF, DF>{std::move(ef), std::move(df)}
Definition at line 346 of file receiver.h.
requires EF DF df folly::pushmi::make_receiver_fn::const
Initial value:
{
    return receiver<VF, EF, DF>{std::move(vf), std::move(ef), std::move(df)}
Definition at line 354 of file receiver.h.
requires DVF vf folly::pushmi::make_receiver_fn::const
Initial value:
{
    return receiver<Data, DVF, passDEF, passDDF>{std::move(d), std::move(vf)}
Definition at line 368 of file receiver.h.
requires on_error_fn<DEFN...> ef folly::pushmi::make_receiver_fn::const
Initial value:
{
    return receiver<Data, passDVF, on_error_fn<DEFN...>, passDDF>{std::move(d), std::move(ef)}
Definition at line 375 of file receiver.h.
requires on_done_fn<DDFN...> df folly::pushmi::make_receiver_fn::const
Initial value:
{
    return receiver<Data, passDVF, passDEF, on_done_fn<DDFN...>>{std::move(d), std::move(df)}
Definition at line 382 of file receiver.h.
requires DVF on_error_fn<DEFN...> ef folly::pushmi::make_receiver_fn::const
Initial value:
{
    return receiver<Data, DVF, on_error_fn<DEFN...>, passDDF>{std::move(d), std::move(vf), std::move(ef)}
Definition at line 389 of file receiver.h.
requires DEF on_done_fn<DDFN...> df folly::pushmi::make_receiver_fn::const
Initial value:
{
    return receiver<Data, passDVF, DEF, on_done_fn<DDFN...>>{std::move(d), std::move(ef), std::move(df)}
Definition at line 396 of file receiver.h.
requires DVF DEF DDF df folly::pushmi::make_receiver_fn::const
Initial value:
{
    return receiver<Data, DVF, DEF, DDF>{std::move(d), std::move(vf), std::move(ef), std::move(df)}
Definition at line 404 of file receiver.h.
requires EF folly::pushmi::make_receiver_fn::ef
Definition at line 354 of file receiver.h.
requires DEF folly::pushmi::make_receiver_fn::ef
Definition at line 396 of file receiver.h.
requires DVF DEF folly::pushmi::make_receiver_fn::ef
Definition at line 404 of file receiver.h.
requires DVF folly::pushmi::make_receiver_fn::vf
Definition at line 389 of file receiver.h.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/pushmi/receiver.h