proxygen: folly::expected_detail::expected_detail_ExpectedHelper::ExpectedHelper Struct Reference
folly::expected_detail::expected_detail_ExpectedHelper::ExpectedHelper Struct Reference
#include <Expected.h>
Static Public Member Functions
template<class Error , class T >
static constexpr Expected< T, Error > return_ (T t)
template<class Error , class T , class U , bool FB_CONCATENATE = false, typename std::enable_if< (FB_CONCATENATE(FB_CONCATENATE(Folly, Requires), __LINE__)||static_cast< bool >(expected_detail::IsConvertible< U &&, Error >::value)), int >::type = 0>
static constexpr Expected< T, Error > return_ (Expected< T, U > t)
template<class This >
static std::decay< This >::type then_ (This &&ex)
template<class This , class Fn , class... Fns, class E = ExpectedErrorType<This>, class T = ExpectedHelper>
static FOLLY_PUSH_WARNING auto then_ (This &&ex, Fn &&fn, Fns &&...fns) -> decltype(T::then_(T::template return_< E >((std::declval< Fn >()(std::declval< This >().value()), unit)), std::declval< Fns >()...))
template<class This , class Yes , class No , class Ret = decltype(std::declval<Yes>()(std::declval<This>().value())), class Err = decltype(std::declval<No>()(std::declval<This>().error())), bool FB_CONCATENATE = false, typename std::enable_if< (FB_CONCATENATE(FB_CONCATENATE(Folly, Requires), __LINE__)||static_cast< bool >(!std::is_void< Err >::value)), int >::type = 0>
static Ret thenOrThrow_ (This &&ex, Yes &&yes, No &&no)
template<class This , class Yes , class No , class Ret = decltype(std::declval<Yes>()(std::declval<This>().value())), class Err = decltype(std::declval<No>()(std::declval<This&>().error())), bool FB_CONCATENATE = false, typename std::enable_if< (FB_CONCATENATE(FB_CONCATENATE(Folly, Requires), __LINE__)||static_cast< bool >(std::is_void< Err >::value)), int >::type = 0>
static Ret thenOrThrow_ (This &&ex, Yes &&yes, No &&no)
Detailed Description
Definition at line 572 of file Expected.h.
Member Function Documentation
template<class Error , class T > static constexpr Expected<T, Error> folly::expected_detail::expected_detail_ExpectedHelper::ExpectedHelper::return_ (T t) inline static
Definition at line 574 of file Expected.h.
References FOLLY_REQUIRES_TRAILING, folly::pushmi::detail::t, and folly::T.
{
     return folly::makeExpected<Error>(t);
   }
template<class Error , class T , class U , bool FB_CONCATENATE = false, typename std::enable_if< (FB_CONCATENATE(FB_CONCATENATE(Folly, Requires), __LINE__)||static_cast< bool >(expected_detail::IsConvertible< U &&, Error >::value)), int >::type = 0> static constexpr Expected<T, Error> folly::expected_detail::expected_detail_ExpectedHelper::ExpectedHelper::return_ (Expected< T, U > t) inline static
Definition at line 582 of file Expected.h.
References folly::pushmi::detail::t.
{
     return t;
   }
template<class This > static std::decay<This>::type folly::expected_detail::expected_detail_ExpectedHelper::ExpectedHelper::then_ (This && ex) inline static
Definition at line 587 of file Expected.h.
References FOLLY_MSVC_DISABLE_WARNING, and FOLLY_PUSH_WARNING.
{
     return static_cast<This&&>(ex);
   }
template<class This , class Fn , class... Fns, class E = ExpectedErrorType<This>, class T = ExpectedHelper> static FOLLY_PUSH_WARNING auto folly::expected_detail::expected_detail_ExpectedHelper::ExpectedHelper::then_ (This && ex, Fn && fn, Fns &&... fns) -> decltype(T::then_(T::template return_<E>((std::declval<Fn>()(std::declval<This>().value()), unit)), std::declval<Fns>()...)) inline static
Definition at line 600 of file Expected.h.
References folly::pushmi::operators::error(), folly::expected_detail::eValue, FOLLY_REQUIRES_TRAILING, LIKELY, folly::makeUnexpected(), fizz::server::detail::No, folly::unit, value, folly::value(), and fizz::server::detail::Yes.
{
     if (LIKELY(ex.which_ == expected_detail::Which::eValue)) {
       return T::then_(
           T::template return_<E>(
               // Uses the comma operator defined above IFF the lambda
               // returns non-void.
               (static_cast<Fn&&>(fn)(static_cast<This&&>(ex).value()), unit)),
           static_cast<Fns&&>(fns)...);
     }
     return makeUnexpected(static_cast<This&&>(ex).error());
   }
template<class This , class Yes , class No , class Ret = decltype(std::declval<Yes>()(std::declval<This>().value())), class Err = decltype(std::declval<No>()(std::declval<This>().error())), bool FB_CONCATENATE = false, typename std::enable_if< (FB_CONCATENATE(FB_CONCATENATE(Folly, Requires), __LINE__)||static_cast< bool >(!std::is_void< Err >::value)), int >::type = 0> static Ret folly::expected_detail::expected_detail_ExpectedHelper::ExpectedHelper::thenOrThrow_ (This && ex, Yes && yes, No && no) inline static
Definition at line 622 of file Expected.h.
References folly::pushmi::operators::error(), folly::expected_detail::eValue, FOLLY_REQUIRES_TRAILING, LIKELY, fizz::server::detail::No, folly::throw_exception(), value, folly::value(), and fizz::server::detail::Yes.
{
     if (LIKELY(ex.which_ == expected_detail::Which::eValue)) {
       return Ret(static_cast<Yes&&>(yes)(static_cast<This&&>(ex).value()));
     }
     throw_exception(static_cast<No&&>(no)(static_cast<This&&>(ex).error()));
   }
template<class This , class Yes , class No , class Ret = decltype(std::declval<Yes>()(std::declval<This>().value())), class Err = decltype(std::declval<No>()(std::declval<This&>().error())), bool FB_CONCATENATE = false, typename std::enable_if< (FB_CONCATENATE(FB_CONCATENATE(Folly, Requires), __LINE__)||static_cast< bool >(std::is_void< Err >::value)), int >::type = 0> static Ret folly::expected_detail::expected_detail_ExpectedHelper::ExpectedHelper::thenOrThrow_ (This && ex, Yes && yes, No && no) inline static
Definition at line 636 of file Expected.h.
References folly::pushmi::operators::error(), folly::expected_detail::eValue, FOLLY_POP_WARNING, LIKELY, folly::throw_exception(), and folly::value().
{
     if (LIKELY(ex.which_ == expected_detail::Which::eValue)) {
       return Ret(static_cast<Yes&&>(yes)(static_cast<This&&>(ex).value()));
     }
     static_cast<No&&>(no)(ex.error());
     typename Unexpected<ExpectedErrorType<This>>::MakeBadExpectedAccess bad;
     throw_exception(bad(static_cast<This&&>(ex).error()));
   }
The documentation for this struct was generated from the following file:
proxygen/folly/folly/Expected.h