proxygen: folly::pushmi::detail::opt< T > Struct Template Reference
folly::pushmi::detail::opt< T > Struct Template Reference
#include <opt.h>
Public Member Functions
opt ()=default
opt (T &&t) noexcept(std::is_nothrow_move_constructible< T >::value)
opt (const T &t)
opt (opt &&that) noexcept(std::is_nothrow_move_constructible< T >::value)
opt (const opt &that)
~opt ()
opt & operator= (opt &&that) noexcept(std::is_nothrow_move_constructible< T >::value &&std::is_nothrow_move_assignable< T >::value)
opt & operator= (const opt &that)
opt & operator= (T &&t) noexcept(std::is_nothrow_move_constructible< T >::value &&std::is_nothrow_move_assignable< T >::value)
opt & operator= (const T &t)
operator bool () const noexcept
T & operator* () noexcept
const T & operator* () const noexcept
Private Member Functions
T * ptr ()
const T * ptr () const
void reset ()
Private Attributes
bool empty_ = true
std::aligned_union_t< 0, T > data_
Detailed Description
template<class T>
struct folly::pushmi::detail::opt< T >
Definition at line 39 of file opt.h.
Constructor & Destructor Documentation
template<class T> folly::pushmi::detail::opt< T >::opt () default
Referenced by folly::pushmi::detail::opt< std::tuple< std::decay_t< TN >... > >::reset().
template<class T> folly::pushmi::detail::opt< T >::opt (T && t) inline noexcept
Definition at line 58 of file opt.h.
{
     ::new (ptr()) T(std::move(t));
     empty_ = false;
   }
template<class T> folly::pushmi::detail::opt< T >::opt (const T & t) inline
Definition at line 62 of file opt.h.
                   {
     ::new (ptr()) T(t);
     empty_ = false;
   }
template<class T> folly::pushmi::detail::opt< T >::opt (opt< T > && that) inline noexcept
Definition at line 66 of file opt.h.
{
     if (that) {
       ::new (ptr()) T(std::move(*that));
       empty_ = false;
       that.reset();
     }
   }
template<class T> folly::pushmi::detail::opt< T >::opt (const opt< T > & that) inline
Definition at line 73 of file opt.h.
{
     if (that) {
       ::new (ptr()) T(*that);
       empty_ = false;
     }
   }
template<class T> folly::pushmi::detail::opt< T >::~opt () inline
Definition at line 79 of file opt.h.
          {
     reset();
   }
Member Function Documentation
template<class T> folly::pushmi::detail::opt< T >::operator bool () const inline explicit noexcept
Definition at line 127 of file opt.h.
{
     return !empty_;
   }
template<class T> T& folly::pushmi::detail::opt< T >::operator* () inline noexcept
Definition at line 130 of file opt.h.
{
     return *ptr();
   }
template<class T> const T& folly::pushmi::detail::opt< T >::operator* () const inline noexcept
Definition at line 133 of file opt.h.
{
     return *ptr();
   }
template<class T> opt& folly::pushmi::detail::opt< T >::operator= (opt< T > && that) inline noexcept
Definition at line 82 of file opt.h.
{
     if (*this && that) {
       **this = std::move(*that);
       that.reset();
     } else if (*this) {
       reset();
     } else if (that) {
       ::new (ptr()) T(std::move(*that));
       empty_ = false;
     }
     return *this;
   }
template<class T> opt& folly::pushmi::detail::opt< T >::operator= (const opt< T > & that) inline
Definition at line 96 of file opt.h.
{
     if (*this && that) {
       **this = *that;
     } else if (*this) {
       reset();
     } else if (that) {
       ::new (ptr()) T(*that);
       empty_ = false;
     }
     return *this;
   }
template<class T> opt& folly::pushmi::detail::opt< T >::operator= (T && t) inline noexcept
Definition at line 107 of file opt.h.
{
     if (*this)
       **this = std::move(t);
     else {
       ::new (ptr()) T(std::move(t));
       empty_ = false;
     }
     return *this;
   }
template<class T> opt& folly::pushmi::detail::opt< T >::operator= (const T & t) inline
Definition at line 118 of file opt.h.
{
     if (*this)
       **this = t;
     else {
       ::new (ptr()) T(t);
       empty_ = false;
     }
     return *this;
   }
template<class T> T* folly::pushmi::detail::opt< T >::ptr () inline private
Definition at line 43 of file opt.h.
Referenced by folly::pushmi::detail::opt< std::tuple< std::decay_t< TN >... > >::operator*(), folly::pushmi::detail::opt< std::tuple< std::decay_t< TN >... > >::operator=(), folly::pushmi::detail::opt< std::tuple< std::decay_t< TN >... > >::opt(), and folly::pushmi::detail::opt< std::tuple< std::decay_t< TN >... > >::reset().
            {
     return static_cast<T*>((void*)&data_);
   }
template<class T> const T* folly::pushmi::detail::opt< T >::ptr () const inline private
Definition at line 46 of file opt.h.
{
     return static_cast<const T*>((const void*)&data_);
   }
template<class T> void folly::pushmi::detail::opt< T >::reset () inline private
Definition at line 49 of file opt.h.
Referenced by folly::pushmi::detail::opt< std::tuple< std::decay_t< TN >... > >::operator=(), and folly::pushmi::detail::opt< std::tuple< std::decay_t< TN >... > >::~opt().
                {
     if (!empty_) {
       ptr()->~T();
       empty_ = true;
     }
   }
Member Data Documentation
template<class T> std::aligned_union_t<0, T> folly::pushmi::detail::opt< T >::data_ private
Definition at line 42 of file opt.h.
template<class T> bool folly::pushmi::detail::opt< T >::empty_ = true private
Definition at line 41 of file opt.h.
Referenced by folly::pushmi::detail::opt< std::tuple< std::decay_t< TN >... > >::operator bool().
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/pushmi/detail/opt.h