proxygen: testing::gtest_printers_test::Foo Struct Reference
testing::gtest_printers_test::Foo Struct Reference
Public Member Functions
virtual ~Foo ()
int MyMethod (char x)
virtual char MyVirtualMethod (int)
virtual ~Foo ()
int MyMethod (char x)
virtual char MyVirtualMethod (int)
virtual ~Foo ()
int MyMethod (char x)
virtual char MyVirtualMethod (int)
Public Attributes
int value
Detailed Description
Definition at line 558 of file gtest-printers_test.cc.
Constructor & Destructor Documentation
virtual testing::gtest_printers_test::Foo::~Foo () inline virtual
Definition at line 560 of file gtest-printers_test.cc.
 {}
virtual testing::gtest_printers_test::Foo::~Foo () inline virtual
Definition at line 560 of file gtest-printers_test.cc.
 {}
virtual testing::gtest_printers_test::Foo::~Foo () inline virtual
Definition at line 560 of file gtest-printers_test.cc.
 {}
Member Function Documentation
int testing::gtest_printers_test::Foo::MyMethod (char x) inline
Definition at line 561 of file gtest-printers_test.cc.
 { return x + 1; }
int testing::gtest_printers_test::Foo::MyMethod (char x) inline
Definition at line 561 of file gtest-printers_test.cc.
 { return x + 1; }
int testing::gtest_printers_test::Foo::MyMethod (char x) inline
Definition at line 561 of file gtest-printers_test.cc.
 { return x + 1; }
virtual char testing::gtest_printers_test::Foo::MyVirtualMethod (int) inline virtual
Definition at line 562 of file gtest-printers_test.cc.
References a, EXPECT_EQ, EXPECT_TRUE, testing::gtest_printers_test::HasPrefix(), operator<<(), testing::gtest_printers_test::Print(), testing::gtest_printers_test::PrintArrayHelper(), s, string, T, testing::gtest_printers_test::TEST(), and value.
 { return 'a'; }
virtual char testing::gtest_printers_test::Foo::MyVirtualMethod (int) inline virtual
Definition at line 562 of file gtest-printers_test.cc.
 { return 'a'; }
virtual char testing::gtest_printers_test::Foo::MyVirtualMethod (int) inline virtual
Definition at line 562 of file gtest-printers_test.cc.
References a, EXPECT_EQ, EXPECT_TRUE, testing::gtest_printers_test::HasPrefix(), operator<<(), testing::gtest_printers_test::Print(), testing::gtest_printers_test::PrintArrayHelper(), s, string, T, testing::gtest_printers_test::TEST(), and value.
 { return 'a'; }
Member Data Documentation
int Foo::value
Definition at line 564 of file gtest-printers_test.cc.
The documentation for this struct was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest-printers_test.cc