proxygen: folly::pushmi::detail::blocking_submit_fn::nested_executor_impl Struct Reference
folly::pushmi::detail::blocking_submit_fn::nested_executor_impl Struct Reference
Public Types
template<class U >
using test_for_this = nested_executor_impl< U >
using properties = properties_t< Exec >
Public Member Functions
nested_executor_impl (lock_state *state, Exec ex)
auto executor ()
requires Constrained< Exec > auto top ()
requires Receiver< Out > &&Constrained< Exec > void submit (CV cv, Out out)
requires Receiver< Out > &&not Constrained< Exec > void submit (Out out)
Static Public Member Functions
requires Sender< Ex > &&Executor< Ex > &&static detail::is_v< Ex, test_for_this > auto make (lock_state *, Ex ex)
requires Sender< Ex > &&Executor< Ex > &&not static detail::is_v< Ex, test_for_this > auto make (lock_state *state, Ex ex)
Public Attributes
lock_state * state_
Exec ex_
Detailed Description
Definition at line 139 of file submit.h.
Member Typedef Documentation
using folly::pushmi::detail::blocking_submit_fn::nested_executor_impl::properties = properties_t<Exec>
Definition at line 161 of file submit.h.
template<class U > using folly::pushmi::detail::blocking_submit_fn::nested_executor_impl::test_for_this = nested_executor_impl<U>
Definition at line 146 of file submit.h.
Constructor & Destructor Documentation
folly::pushmi::detail::blocking_submit_fn::nested_executor_impl::nested_executor_impl (lock_state * state, Exec ex) inline
Definition at line 140 of file submit.h.
         : state_(state), ex_(std::move(ex)) {}
Member Function Documentation
auto folly::pushmi::detail::blocking_submit_fn::nested_executor_impl::executor () inline
Definition at line 163 of file submit.h.
References folly::pushmi::executor, folly::pushmi::detail::PUSHMI_TEMPLATE(), and folly::pushmi::detail::requires().
                     {
       return make(state_, ::folly::pushmi::executor(ex_));
     }
requires Sender<Ex>&& Executor<Ex>&& static detail::is_v<Ex, test_for_this> auto folly::pushmi::detail::blocking_submit_fn::nested_executor_impl::make (lock_state * , Ex ex) inline static
Definition at line 151 of file submit.h.
References folly::pushmi::detail::PUSHMI_TEMPLATE(), and folly::pushmi::detail::requires().
{
       return ex;
     }
requires Sender<Ex>&& Executor<Ex>&& not static detail::is_v<Ex, test_for_this> auto folly::pushmi::detail::blocking_submit_fn::nested_executor_impl::make (lock_state * state, Ex ex) inline static
Definition at line 157 of file submit.h.
{
       return nested_executor_impl<Ex>{state, ex};
     }
requires Receiver<Out>&& Constrained<Exec> void folly::pushmi::detail::blocking_submit_fn::nested_executor_impl::submit (CV cv, Out out) inline
Definition at line 175 of file submit.h.
References folly::gen::move, folly::pushmi::detail::blocking_submit_fn::lock_state::nested, folly::pushmi::detail::PUSHMI_TEMPLATE(), folly::pushmi::detail::requires(), and submit.
{
       ++state_->nested;
       ::folly::pushmi::submit(
           ex_, cv, nested_receiver_impl<Out>{state_, std::move(out)});
     }
requires Receiver<Out>&& not Constrained<Exec> void folly::pushmi::detail::blocking_submit_fn::nested_executor_impl::submit (Out out) inline
Definition at line 183 of file submit.h.
References folly::gen::move, folly::pushmi::detail::blocking_submit_fn::lock_state::nested, and submit.
{
       ++state_->nested;
       ::folly::pushmi::submit(
           ex_, nested_receiver_impl<Out>{state_, std::move(out)});
     }
requires Constrained<Exec> auto folly::pushmi::detail::blocking_submit_fn::nested_executor_impl::top () inline
Definition at line 169 of file submit.h.
References folly::pushmi::detail::PUSHMI_TEMPLATE(), folly::pushmi::detail::requires(), and folly::pushmi::top.
                {
       return ::folly::pushmi::top(ex_);
     }
Member Data Documentation
Exec folly::pushmi::detail::blocking_submit_fn::nested_executor_impl::ex_
Definition at line 143 of file submit.h.
lock_state* folly::pushmi::detail::blocking_submit_fn::nested_executor_impl::state_
Definition at line 142 of file submit.h.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/pushmi/o/submit.h