proxygen: folly::test::Barrier Struct Reference
folly::test::Barrier Struct Reference
#include <Barrier.h>
Public Member Functions
Barrier (size_t count)
void wait ()
Private Attributes
std::mutex lock_
std::condition_variable cv_
size_t num_ {0}
size_t count_
size_t gen_ {0}
Detailed Description
Definition at line 27 of file Barrier.h.
Constructor & Destructor Documentation
folly::test::Barrier::Barrier (size_t count) inline explicit
Definition at line 28 of file Barrier.h.
 : lock_(), cv_(), count_(count) {}
Member Function Documentation
void folly::test::Barrier::wait () inline
Definition at line 30 of file Barrier.h.
References count_, cv_, gen_, lock_, and num_.
Referenced by BENCHMARK(), BENCHMARK_RELATIVE(), and run_once().
               {
     std::unique_lock<std::mutex> lockHeld(lock_);
     auto gen = gen_;
     if (++num_ == count_) {
       num_ = 0;
       gen_++;
       cv_.notify_all();
     } else {
       cv_.wait(lockHeld, [&]() { return gen == gen_; });
     }
   }
Member Data Documentation
size_t folly::test::Barrier::count_ private
Definition at line 46 of file Barrier.h.
Referenced by wait().
std::condition_variable folly::test::Barrier::cv_ private
Definition at line 44 of file Barrier.h.
Referenced by wait().
size_t folly::test::Barrier::gen_ {0} private
Definition at line 47 of file Barrier.h.
Referenced by wait().
std::mutex folly::test::Barrier::lock_ private
Definition at line 43 of file Barrier.h.
Referenced by wait().
size_t folly::test::Barrier::num_ {0} private
Definition at line 45 of file Barrier.h.
Referenced by wait().
The documentation for this struct was generated from the following file:
proxygen/folly/folly/synchronization/test/Barrier.h