proxygen: testing::gmock_matchers_test::AStruct Struct Reference
testing::gmock_matchers_test::AStruct Struct Reference
Public Member Functions
AStruct ()
AStruct (const AStruct &rhs)
AStruct ()
AStruct (const AStruct &rhs)
AStruct ()
AStruct (const AStruct &rhs)
Public Attributes
int x
const double y
Uncopyable z
const char * p
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (AStruct)
GTEST_DISALLOW_ASSIGN_ (AStruct)
GTEST_DISALLOW_ASSIGN_ (AStruct)
Detailed Description
Definition at line 3378 of file gmock-matchers_test.cc.
Constructor & Destructor Documentation
testing::gmock_matchers_test::AStruct::AStruct () inline
Definition at line 3379 of file gmock-matchers_test.cc.
 : x(0), y(1.0), z(5), p(NULL) {}
testing::gmock_matchers_test::AStruct::AStruct (const AStruct & rhs) inline
Definition at line 3380 of file gmock-matchers_test.cc.
       : x(rhs.x), y(rhs.y), z(rhs.z.value()), p(rhs.p) {}
testing::gmock_matchers_test::AStruct::AStruct () inline
Definition at line 3379 of file gmock-matchers_test.cc.
 : x(0), y(1.0), z(5), p(NULL) {}
testing::gmock_matchers_test::AStruct::AStruct (const AStruct & rhs) inline
Definition at line 3380 of file gmock-matchers_test.cc.
References testing::_, a, ch, testing::gmock_matchers_test::Describe(), testing::gmock_matchers_test::DescribeNegation(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testing::gmock_matchers_test::Explain(), testing::Field(), testing::Ge(), testing::gmock_matchers_test::GreaterThan(), GTEST_DISALLOW_ASSIGN_, testing::Le(), testing::internal::MatcherBase< T >::Matches(), testing::Not(), testing::gmock_matchers_test::OfType(), p, testing::StartsWith(), testing::internal::TEST(), testing::Truly(), testing::gmock_matchers_test::ValueIsPositive(), x, and x.
       : x(rhs.x), y(rhs.y), z(rhs.z.value()), p(rhs.p) {}
testing::gmock_matchers_test::AStruct::AStruct () inline
Definition at line 3379 of file gmock-matchers_test.cc.
 : x(0), y(1.0), z(5), p(NULL) {}
testing::gmock_matchers_test::AStruct::AStruct (const AStruct & rhs) inline
Definition at line 3380 of file gmock-matchers_test.cc.
References testing::_, a, ch, testing::gmock_matchers_test::Describe(), testing::gmock_matchers_test::DescribeNegation(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testing::gmock_matchers_test::Explain(), testing::Field(), testing::Ge(), testing::gmock_matchers_test::GreaterThan(), GTEST_DISALLOW_ASSIGN_, testing::Le(), testing::internal::MatcherBase< T >::Matches(), testing::Not(), testing::gmock_matchers_test::OfType(), p, testing::StartsWith(), testing::internal::TEST(), testing::Truly(), testing::gmock_matchers_test::ValueIsPositive(), x, and x.
       : x(rhs.x), y(rhs.y), z(rhs.z.value()), p(rhs.p) {}
Member Function Documentation
testing::gmock_matchers_test::AStruct::GTEST_DISALLOW_ASSIGN_ (AStruct) private
testing::gmock_matchers_test::AStruct::GTEST_DISALLOW_ASSIGN_ (AStruct) private
testing::gmock_matchers_test::AStruct::GTEST_DISALLOW_ASSIGN_ (AStruct) private
Member Data Documentation
const char * testing::gmock_matchers_test::AStruct::p
Definition at line 3386 of file gmock-matchers_test.cc.
Referenced by AStruct(), and testing::gmock_matchers_test::TEST().
int testing::gmock_matchers_test::AStruct::x
Definition at line 3383 of file gmock-matchers_test.cc.
Referenced by AStruct(), and testing::gmock_matchers_test::TEST().
const double testing::gmock_matchers_test::AStruct::y
Definition at line 3384 of file gmock-matchers_test.cc.
Uncopyable testing::gmock_matchers_test::AStruct::z
Definition at line 3385 of file gmock-matchers_test.cc.
The documentation for this struct was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-matchers_test.cc