proxygen: folly::SocketAddress::ExternalUnixAddr Struct Reference
folly::SocketAddress::ExternalUnixAddr Struct Reference
Public Member Functions
socklen_t pathLength () const
void init ()
void init (const ExternalUnixAddr &other)
void copy (const ExternalUnixAddr &other)
void free ()
Public Attributes
struct sockaddr_un * addr
socklen_t len
Detailed Description
Unix socket addresses require more storage than IPv4 and IPv6 addresses, and are comparatively little-used.
Therefore SocketAddress' internal storage_ member variable doesn't contain room for a full unix address, to avoid wasting space in the common case. When we do need to store a Unix socket address, we use this ExternalUnixAddr structure to allocate a struct sockaddr_un separately on the heap.
Definition at line 555 of file SocketAddress.h.
Member Function Documentation
void folly::SocketAddress::ExternalUnixAddr::copy (const ExternalUnixAddr & other) inline
Definition at line 573 of file SocketAddress.h.
References addr, and len.
Referenced by folly::SocketAddress::operator=().
{
       len = other.len;
       memcpy(addr, other.addr, size_t(len));
     }
void folly::SocketAddress::ExternalUnixAddr::free () inline
Definition at line 577 of file SocketAddress.h.
References addr, folly::SocketAddress::getAddrInfo(), folly::SocketAddress::getIpString(), folly::SocketAddress::setFromAddrInfo(), folly::SocketAddress::setFromLocalAddr(), folly::SocketAddress::setFromSocket(), string, uint16_t, and folly::SocketAddress::updateUnixAddressLength().
Referenced by folly::SocketAddress::operator=(), folly::SocketAddress::reset(), and folly::SocketAddress::~SocketAddress().
                 {
       delete addr;
     }
void folly::SocketAddress::ExternalUnixAddr::init () inline
Definition at line 563 of file SocketAddress.h.
Referenced by folly::SocketAddress::operator=(), and folly::SocketAddress::SocketAddress().
                 {
       addr = new struct sockaddr_un;
       addr->sun_family = AF_UNIX;
       len = 0;
     }
void folly::SocketAddress::ExternalUnixAddr::init (const ExternalUnixAddr & other) inline
Definition at line 568 of file SocketAddress.h.
References addr, and len.
{
       addr = new struct sockaddr_un;
       len = other.len;
       memcpy(addr, other.addr, size_t(len));
     }
socklen_t folly::SocketAddress::ExternalUnixAddr::pathLength () const inline
Definition at line 559 of file SocketAddress.h.
Referenced by folly::SocketAddress::operator<(), and folly::SocketAddress::operator==().
{
       return socklen_t(len - offsetof(struct sockaddr_un, sun_path));
     }
Member Data Documentation
struct sockaddr_un* folly::SocketAddress::ExternalUnixAddr::addr
Definition at line 556 of file SocketAddress.h.
Referenced by copy(), free(), folly::SocketAddress::getAddress(), init(), folly::SocketAddress::operator<(), and folly::SocketAddress::operator==().
socklen_t folly::SocketAddress::ExternalUnixAddr::len
Definition at line 557 of file SocketAddress.h.
Referenced by copy(), folly::SocketAddress::getAddress(), init(), and folly::SocketAddress::operator==().
The documentation for this struct was generated from the following file:
proxygen/folly/folly/SocketAddress.h