proxygen: folly::pushmi::__adl::set_done_fn Struct Reference
folly::pushmi::__adl::set_done_fn Struct Reference
#include <extension_points.h>
Public Member Functions
requires requires (set_done(std::declval< S & >()), set_error(std::declval< S & >(), std::current_exception()))) void operator()(S &&s) const noexcept(noexcept(set_done(s)))
Detailed Description
Definition at line 245 of file extension_points.h.
Member Function Documentation
requires folly::pushmi::__adl::set_done_fn::requires (set_done(std::declval< S & >()) , set_error(std::declval< S & >(), std::current_exception())) const inline noexcept
Definition at line 247 of file extension_points.h.
References folly::pushmi::__adl::set_done(), and folly::pushmi::__adl::set_error().
Referenced by folly::pushmi::__adl::do_submit_fn::noexcept().
{
     try {
       set_done(s);
     } catch (...) {
       set_error(s, std::current_exception());
     }
   }
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/pushmi/extension_points.h