proxygen: folly::pushmi::make_single_sender_fn Struct Reference
folly::pushmi::make_single_sender_fn Struct Reference
#include <single_sender.h>
Public Member Functions
auto operator() () const
requires True PUSHMI_BROKEN_SUBSUMPTION not auto operator() (SF sf) const
requires True &&Invocable< EXF & > PUSHMI_BROKEN_SUBSUMPTION not auto operator() (SF sf, EXF exf) const
requires True &&Sender< Data, is_single<> > auto operator() (Data d) const
requires Sender< Data, is_single<> > auto operator() (Data d, DSF sf) const
requires Sender< Data, is_single<> > &&Invocable< DEXF &, Data & > auto operator() (Data d, DSF sf, DEXF exf) const
Detailed Description
Definition at line 199 of file single_sender.h.
Member Function Documentation
auto folly::pushmi::make_single_sender_fn::operator() () const inline
Definition at line 200 of file single_sender.h.
References PUSHMI_BROKEN_SUBSUMPTION, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return single_sender<ignoreSF, trampolineEXF>{};
   }
requires True PUSHMI_BROKEN_SUBSUMPTION not auto folly::pushmi::make_single_sender_fn::operator() (SF sf) const inline
Definition at line 205 of file single_sender.h.
References folly::gen::move, PUSHMI_BROKEN_SUBSUMPTION, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return single_sender<SF, trampolineEXF>{std::move(sf)};
   }
requires True&& Invocable<EXF&> PUSHMI_BROKEN_SUBSUMPTION not auto folly::pushmi::make_single_sender_fn::operator() (SF sf, EXF exf) const inline
Definition at line 211 of file single_sender.h.
References folly::gen::move, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return single_sender<SF, EXF>{std::move(sf), std::move(exf)};
   }
requires True&& Sender<Data, is_single<> > auto folly::pushmi::make_single_sender_fn::operator() (Data d) const inline
Definition at line 216 of file single_sender.h.
References folly::gen::move, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return single_sender<Data, passDSF, passDEXF>{std::move(d)};
   }
requires Sender<Data, is_single<> > auto folly::pushmi::make_single_sender_fn::operator() (Data d, DSF sf) const inline
Definition at line 221 of file single_sender.h.
References folly::gen::move, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return single_sender<Data, DSF, passDEXF>{std::move(d), std::move(sf)};
   }
requires Sender<Data, is_single<> >&& Invocable<DEXF&, Data&> auto folly::pushmi::make_single_sender_fn::operator() (Data d, DSF sf, DEXF exf) const inline
Definition at line 226 of file single_sender.h.
References folly::pushmi::make_single_sender, folly::gen::move, PUSHMI_BROKEN_SUBSUMPTION, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return single_sender<Data, DSF, DEXF>{
         std::move(d), std::move(sf), std::move(exf)};
   }
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/pushmi/single_sender.h