proxygen: folly::pushmi::__adl::do_submit_fn Struct Reference
folly::pushmi::__adl::do_submit_fn Struct Reference
#include <extension_points.h>
Public Member Functions
requires requires (submit(std::declval< SD & >(), std::declval< Out >()))) void operator()(SD &&s
requires Out out const noexcept (noexcept(submit(s, std::move(out))))
requires requires (submit(std::declval< SD & >(), top(std::declval< SD & >()), std::declval< Out >()))) void operator()(SD &&s
requires Out out const noexcept (noexcept(submit(s, top(s), std::move(out))))
requires requires (submit(std::declval< SD & >(), std::declval< TP >(), std::declval< Out >()))) void operator()(SD &&s
requires TP Out out const noexcept (noexcept(submit(s, std::move(tp), std::move(out))))
Public Attributes
requires TP tp
Detailed Description
Definition at line 311 of file extension_points.h.
Member Function Documentation
requires Out out const folly::pushmi::__adl::do_submit_fn::noexcept (noexcept(submit(s, std::move(out)))) inline
Definition at line 317 of file extension_points.h.
References folly::gen::move, folly::pushmi::PUSHMI_TEMPLATE(), folly::pushmi::__adl::set_done_fn::requires(), s, folly::pushmi::submit, and folly::pushmi::top.
{
     submit(s, std::move(out));
   }
requires Out out const folly::pushmi::__adl::do_submit_fn::noexcept (noexcept(submit(s, top(s), std::move(out)))) inline
Definition at line 326 of file extension_points.h.
References folly::gen::move, folly::pushmi::PUSHMI_TEMPLATE(), folly::pushmi::__adl::set_done_fn::requires(), folly::pushmi::submit, and folly::pushmi::top.
{
     submit(s, top(s), std::move(out));
   }
requires TP Out out const folly::pushmi::__adl::do_submit_fn::noexcept (noexcept(submit(s, std::move(tp), std::move(out)))) inline
Definition at line 338 of file extension_points.h.
References folly::gen::move, and folly::pushmi::submit.
{
     submit(s, std::move(tp), std::move(out));
   }
requires folly::pushmi::__adl::do_submit_fn::requires (submit(std::declval< SD & >(), std::declval< Out >()))
requires folly::pushmi::__adl::do_submit_fn::requires (submit(std::declval< SD & >(), top(std::declval< SD & >()), std::declval< Out >()))
requires folly::pushmi::__adl::do_submit_fn::requires (submit(std::declval< SD & >(),std::declval< TP >(),std::declval< Out >()))
Member Data Documentation
requires TP folly::pushmi::__adl::do_submit_fn::tp
Definition at line 337 of file extension_points.h.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/pushmi/extension_points.h