proxygen: inline_executor_flow_single< CancellationFactory > Struct Template Reference
inline_executor_flow_single< CancellationFactory > Struct Template Reference
Public Types
using properties = mi::property_set< mi::is_sender<>, mi::is_flow<>, mi::is_fifo_sequence<>, mi::is_maybe_blocking<>, mi::is_single<>>
Public Member Functions
auto executor ()
template<class Out >
void submit (Out out)
Public Attributes
CancellationFactory cf
Detailed Description
template<class CancellationFactory>
struct inline_executor_flow_single< CancellationFactory >
Definition at line 118 of file PushmiBenchmarks.cpp.
Member Typedef Documentation
template<class CancellationFactory > using inline_executor_flow_single< CancellationFactory >::properties = mi::property_set< mi::is_sender<>, mi::is_flow<>, mi::is_fifo_sequence<>, mi::is_maybe_blocking<>, mi::is_single<>>
Definition at line 126 of file PushmiBenchmarks.cpp.
Member Function Documentation
template<class CancellationFactory > auto inline_executor_flow_single< CancellationFactory >::executor () inline
Definition at line 127 of file PushmiBenchmarks.cpp.
                   {
     return inline_time_executor{};
   }
template<class CancellationFactory > template<class Out > void inline_executor_flow_single< CancellationFactory >::submit (Out out) inline
Definition at line 131 of file PushmiBenchmarks.cpp.
References folly::data(), folly::pushmi::lock_both(), MAKE, folly::gen::move, folly::pushmi::__adl::noexcept(), folly::pushmi::set_done, folly::pushmi::set_starting, folly::pushmi::set_value, and tokens.
{
     auto tokens = cf();
     using Stopper = decltype(tokens.second);
     struct Data : mi::receiver<> {
       explicit Data(Stopper stopper) : stopper(std::move(stopper)) {}
       Stopper stopper;
     };
     auto up = mi::MAKE(receiver)(
         Data{std::move(tokens.second)},
         [](auto& data) {},
         [](auto& data, auto e) noexcept {
           auto both = lock_both(data.stopper);
           (*(both.first))(both.second);
         },
         [](auto& data) {
           auto both = lock_both(data.stopper);
           (*(both.first))(both.second);
         });
     // pass reference for cancellation.
     ::mi::set_starting(out, std::move(up));
     auto both = lock_both(tokens.first);
     if (!!both.first && !*(both.first)) {
       ::mi::set_value(out, *this);
     } else {
       // cancellation is not an error
       ::mi::set_done(out);
     }
   }
Member Data Documentation
template<class CancellationFactory > CancellationFactory inline_executor_flow_single< CancellationFactory >::cf
Definition at line 119 of file PushmiBenchmarks.cpp.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/pushmi/benchmarks/PushmiBenchmarks.cpp