proxygen: folly::ShallowCopyRequestContextScopeGuard Struct Reference
folly::ShallowCopyRequestContextScopeGuard Struct Reference
#include <Request.h>
Public Member Functions
ShallowCopyRequestContextScopeGuard ()
ShallowCopyRequestContextScopeGuard (const RequestToken &val, std::unique_ptr< RequestData > data)
ShallowCopyRequestContextScopeGuard (const std::string &val, std::unique_ptr< RequestData > data)
~ShallowCopyRequestContextScopeGuard ()
ShallowCopyRequestContextScopeGuard (const ShallowCopyRequestContextScopeGuard &)=delete
ShallowCopyRequestContextScopeGuard & operator= (const ShallowCopyRequestContextScopeGuard &)=delete
ShallowCopyRequestContextScopeGuard (ShallowCopyRequestContextScopeGuard &&)=delete
ShallowCopyRequestContextScopeGuard & operator= (ShallowCopyRequestContextScopeGuard &&)=delete
Private Attributes
std::shared_ptr< RequestContext > prev_
Detailed Description
This guard maintains all the RequestData pointers of the parent. This allows to overwrite a specific RequestData pointer for the scope's duration, without breaking others.
Only modified pointers will have their set/onset methods called
Definition at line 289 of file Request.h.
Constructor & Destructor Documentation
folly::ShallowCopyRequestContextScopeGuard::ShallowCopyRequestContextScopeGuard () inline
Definition at line 290 of file Request.h.
       : prev_(RequestContext::setShallowCopyContext()) {}
folly::ShallowCopyRequestContextScopeGuard::ShallowCopyRequestContextScopeGuard (const RequestToken & val, std::unique_ptr< RequestData > data) inline
Shallow copy then overwrite one specific RequestData
Helper constructor which is a more efficient equivalent to "clearRequestData" then "setRequestData" after the guard.
Definition at line 299 of file Request.h.
References folly::RequestContext::get(), folly::gen::move, and folly::RequestContext::overwriteContextData().
       : ShallowCopyRequestContextScopeGuard() {
     RequestContext::get()->overwriteContextData(val, std::move(data));
   }
folly::ShallowCopyRequestContextScopeGuard::ShallowCopyRequestContextScopeGuard (const std::string & val, std::unique_ptr< RequestData > data) inline
Definition at line 305 of file Request.h.
References folly::RequestContext::get(), folly::gen::move, and folly::RequestContext::overwriteContextData().
       : ShallowCopyRequestContextScopeGuard() {
     RequestContext::get()->overwriteContextData(val, std::move(data));
   }
folly::ShallowCopyRequestContextScopeGuard::~ShallowCopyRequestContextScopeGuard () inline
Definition at line 312 of file Request.h.
References folly::gen::move, and folly::RequestContext::setContext().
{
     RequestContext::setContext(std::move(prev_));
   }
folly::ShallowCopyRequestContextScopeGuard::ShallowCopyRequestContextScopeGuard (const ShallowCopyRequestContextScopeGuard &) delete
folly::ShallowCopyRequestContextScopeGuard::ShallowCopyRequestContextScopeGuard (ShallowCopyRequestContextScopeGuard &&) delete
Member Function Documentation
ShallowCopyRequestContextScopeGuard& folly::ShallowCopyRequestContextScopeGuard::operator= (const ShallowCopyRequestContextScopeGuard &) delete
ShallowCopyRequestContextScopeGuard& folly::ShallowCopyRequestContextScopeGuard::operator= (ShallowCopyRequestContextScopeGuard &&) delete
Member Data Documentation
std::shared_ptr<RequestContext> folly::ShallowCopyRequestContextScopeGuard::prev_ private
Definition at line 326 of file Request.h.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/io/async/Request.h