proxygen: SyncVec< T > Struct Template Reference
SyncVec< T > Struct Template Reference
Public Member Functions
SyncVec ()
~SyncVec ()
void push_back (const T &t)
void lock ()
void unlock ()
T * begin () const
T * end () const
Public Attributes
PackedSyncPtr< T > base
Detailed Description
template<typename T>
struct SyncVec< T >
Definition at line 73 of file PackedSyncPtrTest.cpp.
Constructor & Destructor Documentation
template<typename T > SyncVec< T >::SyncVec () inline
Definition at line 75 of file PackedSyncPtrTest.cpp.
References folly::PackedSyncPtr< T >::init().
             {
     base.init();
   }
template<typename T > SyncVec< T >::~SyncVec () inline
Definition at line 78 of file PackedSyncPtrTest.cpp.
References bm::free(), and folly::PackedSyncPtr< T >::get().
              {
     free(base.get());
   }
Member Function Documentation
template<typename T > T* SyncVec< T >::begin () const inline
Definition at line 93 of file PackedSyncPtrTest.cpp.
References folly::PackedSyncPtr< T >::get().
                    {
     return base.get();
   }
template<typename T > T* SyncVec< T >::end () const inline
Definition at line 96 of file PackedSyncPtrTest.cpp.
References folly::PackedSyncPtr< T >::extra(), and folly::PackedSyncPtr< T >::get().
                  {
     return base.get() + base.extra();
   }
template<typename T > void SyncVec< T >::lock () inline
Definition at line 86 of file PackedSyncPtrTest.cpp.
References folly::PackedSyncPtr< T >::lock().
               {
     base.lock();
   }
template<typename T > void SyncVec< T >::push_back (const T & t) inline
Definition at line 81 of file PackedSyncPtrTest.cpp.
References folly::PackedSyncPtr< T >::extra(), folly::PackedSyncPtr< T >::get(), folly::PackedSyncPtr< T >::set(), folly::PackedSyncPtr< T >::setExtra(), folly::pushmi::detail::t, and T.
{
     base.set((T*)realloc(base.get(), (base.extra() + 1) * sizeof(T)));
     base[base.extra()] = t;
     base.setExtra(base.extra() + 1);
   }
template<typename T > void SyncVec< T >::unlock () inline
Definition at line 89 of file PackedSyncPtrTest.cpp.
References folly::PackedSyncPtr< T >::unlock().
                 {
     base.unlock();
   }
Member Data Documentation
template<typename T > PackedSyncPtr<T> SyncVec< T >::base
Definition at line 74 of file PackedSyncPtrTest.cpp.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/test/PackedSyncPtrTest.cpp