proxygen: testing::internal::TransformTupleValuesHelper< Tuple, Func, OutIter >::IterateOverTuple< Tup, 0 > Struct Template Reference
testing::internal::TransformTupleValuesHelper< Tuple, Func, OutIter >::IterateOverTuple< Tup, 0 > Struct Template Reference
Public Member Functions
OutIter operator() (Func, const Tup &, OutIter out) const
OutIter operator() (Func, const Tup &, OutIter out) const
OutIter operator() (Func, const Tup &, OutIter out) const
Detailed Description
template<typename Tuple, typename Func, typename OutIter>
template<typename Tup>
struct testing::internal::TransformTupleValuesHelper< Tuple, Func, OutIter >::IterateOverTuple< Tup, 0 >
Definition at line 842 of file gmock-matchers.h.
Member Function Documentation
template<typename Tuple , typename Func , typename OutIter > template<typename Tup > OutIter testing::internal::TransformTupleValuesHelper< Tuple, Func, OutIter >::IterateOverTuple< Tup, 0 >::operator() (Func , const Tup & , OutIter out) const inline
Definition at line 843 of file gmock-matchers.h.
{
       return out;
     }
template<typename Tuple , typename Func , typename OutIter > template<typename Tup > OutIter testing::internal::TransformTupleValuesHelper< Tuple, Func, OutIter >::IterateOverTuple< Tup, 0 >::operator() (Func , const Tup & , OutIter out) const inline
Definition at line 843 of file gmock-matchers.h.
References f, Run(), folly::pushmi::detail::t, and testing::internal::TransformTupleValues().
{
       return out;
     }
template<typename Tuple , typename Func , typename OutIter > template<typename Tup > OutIter testing::internal::TransformTupleValuesHelper< Tuple, Func, OutIter >::IterateOverTuple< Tup, 0 >::operator() (Func , const Tup & , OutIter out) const inline
Definition at line 843 of file gmock-matchers.h.
References f, Run(), folly::pushmi::detail::t, and testing::internal::TransformTupleValues().
{
       return out;
     }
The documentation for this struct was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/include/gmock/gmock-matchers.h