proxygen: folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::Layout Struct Reference
folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::Layout Struct Reference
#include <BitVectorCoding.h>
Public Member Functions
size_t bytes () const
template<class Range >
BitVectorCompressedListBase< typename Range::iterator > openList (Range &buf) const
MutableCompressedList allocList () const
Static Public Member Functions
static Layout fromUpperBoundAndSize (size_t upperBound, size_t size)
Public Attributes
size_t size = 0
size_t upperBound = 0
size_t bits = 0
size_t skipPointers = 0
size_t forwardPointers = 0
Detailed Description
template<class Value, class SkipValue, size_t kSkipQuantum = 0, size_t kForwardQuantum = 0>
struct folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::Layout
Definition at line 176 of file BitVectorCoding.h.
Member Function Documentation
template<class Value , class SkipValue , size_t kSkipQuantum = 0, size_t kForwardQuantum = 0> MutableCompressedList folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::Layout::allocList () const inline
Definition at line 225 of file BitVectorCoding.h.
References folly::compression::BitVectorCompressedListBase< Pointer >::size, and uint8_t.
{
     uint8_t* buf = nullptr;
     if (size > 0) {
       buf = static_cast<uint8_t*>(malloc(bytes() + 7));
     }
     folly::MutableByteRange bufRange(buf, bytes());
     return openList(bufRange);
   }
template<class Value , class SkipValue , size_t kSkipQuantum = 0, size_t kForwardQuantum = 0> size_t folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::Layout::bytes () const inline
Definition at line 200 of file BitVectorCoding.h.
References folly::compression::BitVectorCompressedListBase< Pointer >::bits, folly::compression::BitVectorCompressedListBase< Pointer >::forwardPointers, and folly::compression::BitVectorCompressedListBase< Pointer >::skipPointers.
{
     return bits + skipPointers + forwardPointers;
   }
template<class Value , class SkipValue , size_t kSkipQuantum = 0, size_t kForwardQuantum = 0> static Layout folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::Layout::fromUpperBoundAndSize (size_t upperBound, size_t size) inline static
Definition at line 178 of file BitVectorCoding.h.
References folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::Layout::bits, folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::Layout::forwardPointers, max, folly::compression::BitVectorCompressedListBase< Pointer >::size, folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::Layout::size, folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::Layout::skipPointers, folly::compression::BitVectorCompressedListBase< Pointer >::upperBound, and folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::Layout::upperBound.
{
     Layout layout;
     layout.size = size;
     layout.upperBound = upperBound;
     size_t bitVectorSizeInBytes = (upperBound / 8) + 1;
     layout.bits = bitVectorSizeInBytes;
     if (skipQuantum != 0) {
       size_t numSkipPointers = upperBound / skipQuantum;
       layout.skipPointers = numSkipPointers * sizeof(SkipValueType);
     }
     if (forwardQuantum != 0) {
       size_t numForwardPointers = size / forwardQuantum;
       layout.forwardPointers = numForwardPointers * sizeof(SkipValueType);
     }
     CHECK_LT(size, std::numeric_limits<SkipValueType>::max());
     return layout;
   }
template<class Value , class SkipValue , size_t kSkipQuantum = 0, size_t kForwardQuantum = 0> template<class Range > BitVectorCompressedListBase<typename Range::iterator> folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::Layout::openList (Range & buf) const inline
Definition at line 205 of file BitVectorCoding.h.
References folly::detail::advance, folly::Range< Iter >::advance(), folly::test::begin(), folly::compression::BitVectorCompressedListBase< Pointer >::bits, folly::compression::BitVectorCompressedListBase< Pointer >::data, folly::Range< Iter >::data(), folly::compression::BitVectorCompressedListBase< Pointer >::forwardPointers, folly::compression::BitVectorCompressedListBase< Pointer >::size, folly::compression::BitVectorCompressedListBase< Pointer >::skipPointers, folly::Range< Iter >::subpiece(), and folly::compression::BitVectorCompressedListBase< Pointer >::upperBound.
{
     BitVectorCompressedListBase<typename Range::iterator> result;
     result.size = size;
     result.upperBound = upperBound;
     result.data = buf.subpiece(0, bytes());
     auto advance = [&](size_t n) {
       auto begin = buf.data();
       buf.advance(n);
       return begin;
     };
     result.bits = advance(bits);
     result.skipPointers = advance(skipPointers);
     result.forwardPointers = advance(forwardPointers);
     CHECK_EQ(buf.data() - result.data.data(), bytes());
     return result;
   }
Member Data Documentation
template<class Value , class SkipValue , size_t kSkipQuantum = 0, size_t kForwardQuantum = 0> size_t folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::Layout::bits = 0
Definition at line 238 of file BitVectorCoding.h.
Referenced by folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::Layout::fromUpperBoundAndSize().
template<class Value , class SkipValue , size_t kSkipQuantum = 0, size_t kForwardQuantum = 0> size_t folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::Layout::forwardPointers = 0
Definition at line 240 of file BitVectorCoding.h.
Referenced by folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::Layout::fromUpperBoundAndSize().
template<class Value , class SkipValue , size_t kSkipQuantum = 0, size_t kForwardQuantum = 0> size_t folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::Layout::size = 0
Definition at line 234 of file BitVectorCoding.h.
Referenced by folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::Layout::fromUpperBoundAndSize().
template<class Value , class SkipValue , size_t kSkipQuantum = 0, size_t kForwardQuantum = 0> size_t folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::Layout::skipPointers = 0
Definition at line 239 of file BitVectorCoding.h.
Referenced by folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::Layout::fromUpperBoundAndSize().
template<class Value , class SkipValue , size_t kSkipQuantum = 0, size_t kForwardQuantum = 0> size_t folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::Layout::upperBound = 0
Definition at line 235 of file BitVectorCoding.h.
Referenced by folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::Layout::fromUpperBoundAndSize().
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/BitVectorCoding.h