proxygen: fizz::CryptoUtils Struct Reference
fizz::CryptoUtils Struct Reference
#include <Utils.h>
Static Public Member Functions
static bool equal (folly::ByteRange a, folly::ByteRange b)
static void clean (folly::MutableByteRange range)
static void init ()
Detailed Description
Definition at line 15 of file Utils.h.
Member Function Documentation
void fizz::CryptoUtils::clean (folly::MutableByteRange range) static
Overwrites the memory in range.
Definition at line 38 of file Utils.cpp.
References folly::Range< Iter >::data(), and folly::Range< Iter >::size().
Referenced by fizz::server::AeadTokenCipher< AeadType, HkdfType >::clearSecrets().
{
   sodium_memzero(range.data(), range.size());
 }
bool fizz::CryptoUtils::equal (folly::ByteRange a, folly::ByteRange b) static
Returns true if a and b are identical.
Constant time in terms of the contents of a and b (but not in terms of length).
Definition at line 31 of file Utils.cpp.
References folly::Range< Iter >::data(), and folly::Range< Iter >::size().
Referenced by fizz::sm::generateTicket(), fizz::sm::handleCertMsg(), and fizz::sm::setupSchedulerAndContext().
{
   if (a.size() != b.size()) {
     return false;
   }
   return sodium_memcmp(a.data(), b.data(), a.size()) == 0;
 }
void fizz::CryptoUtils::init () static
Initialize all required crypto libraries.
Definition at line 42 of file Utils.cpp.
Referenced by main().
{
   static InitFizz initFizz;
 }
The documentation for this struct was generated from the following files:
proxygen/fizz/fizz/crypto/Utils.h
proxygen/fizz/fizz/crypto/Utils.cpp