proxygen: folly::experimental::EnvironmentState Struct Reference
folly::experimental::EnvironmentState Struct Reference
#include <EnvUtil.h>
Public Types
using EnvType = std::unordered_map< std::string, std::string >
Public Member Functions
EnvironmentState (EnvType const &env)
EnvironmentState (EnvType &&env)
EnvType const & operator* () const
EnvType const * operator-> () const
EnvType & operator* ()
EnvType * operator-> ()
void setAsCurrentEnvironment ()
std::vector< std::string > toVector () const
std::unique_ptr< char *, void(*)(char **)> toPointerArray () const
Static Public Member Functions
static EnvironmentState fromCurrentEnvironment ()
static EnvironmentState empty ()
Private Member Functions
EnvironmentState ()
Private Attributes
EnvType env_
Detailed Description
Definition at line 33 of file EnvUtil.h.
Member Typedef Documentation
using folly::experimental::EnvironmentState::EnvType = std::unordered_map<std::string, std::string>
Definition at line 34 of file EnvUtil.h.
Constructor & Destructor Documentation
folly::experimental::EnvironmentState::EnvironmentState (EnvType const & env) inline explicit
Definition at line 49 of file EnvUtil.h.
 : env_(env) {}
folly::experimental::EnvironmentState::EnvironmentState (EnvType && env) inline explicit
Definition at line 50 of file EnvUtil.h.
 : env_(std::move(env)) {}
folly::experimental::EnvironmentState::EnvironmentState () inline private
Definition at line 87 of file EnvUtil.h.
 {}
Member Function Documentation
static EnvironmentState folly::experimental::EnvironmentState::empty () inline static
Definition at line 45 of file EnvUtil.h.
{
     return {};
   }
EnvironmentState EnvironmentState::fromCurrentEnvironment () static
Definition at line 26 of file EnvUtil.cpp.
References folly::data(), gmock_leak_test::environ, folly::Range< Iter >::find(), folly::gen::move, folly::Range< Iter >::npos, string, folly::Range< Iter >::subpiece(), folly::Range< Iter >::toString(), and folly::value().
{
   std::unordered_map<std::string, std::string> data;
   for (auto it = environ; it && *it; ++it) {
     std::string key, value;
     folly::StringPiece entry(*it);
     auto equalsPosition = entry.find('=');
     if (equalsPosition == entry.npos) {
       throw MalformedEnvironment{to<std::string>(
           "Environment contains an non key-value-pair string \"", entry, "\"")};
     }
     key = entry.subpiece(0, equalsPosition).toString();
     value = entry.subpiece(equalsPosition + 1).toString();
     if (data.count(key)) {
       throw MalformedEnvironment{to<std::string>(
           "Environment contains duplicate value for \"", key, "\"")};
     }
     data.emplace(std::move(key), std::move(value));
   }
   return EnvironmentState{std::move(data)};
 }
EnvType const& folly::experimental::EnvironmentState::operator* () const inline
Definition at line 53 of file EnvUtil.h.
References env_.
{
     return env_;
   }
EnvType& folly::experimental::EnvironmentState::operator* () inline
Definition at line 61 of file EnvUtil.h.
References env_.
{
     return env_;
   }
EnvType const* folly::experimental::EnvironmentState::operator-> () const inline
Definition at line 56 of file EnvUtil.h.
References env_.
{
     return &env_;
   }
EnvType* folly::experimental::EnvironmentState::operator-> () inline
Definition at line 64 of file EnvUtil.h.
References env_, setAsCurrentEnvironment(), toPointerArray(), and toVector().
{
     return &env_;
   }
void EnvironmentState::setAsCurrentEnvironment ()
Definition at line 47 of file EnvUtil.cpp.
References clearenv(), and env_.
Referenced by operator->().
{
   PCHECK(0 == clearenv());
   for (const auto& kvp : env_) {
     PCHECK(0 == setenv(kvp.first.c_str(), kvp.second.c_str(), (int)true));
   }
 }
std::unique_ptr< char *, void(*)(char **)> EnvironmentState::toPointerArray () const
Definition at line 62 of file EnvUtil.cpp.
References env_, ptr, string, and folly::value().
Referenced by operator->().
           {
   size_t totalStringLength{};
   for (auto const& pair : env_) {
     totalStringLength += pair.first.size() + pair.second.size() +
         2 /* intermediate '=' and the terminating NUL */;
   }
   size_t allocationRequired =
       (totalStringLength / sizeof(char*) + 1) + env_.size() + 1;
   char** raw = new char*[allocationRequired];
   char** ptrBase = raw;
   char* stringBase = reinterpret_cast<char*>(&raw[env_.size() + 1]);
   char* const stringEnd = reinterpret_cast<char*>(&raw[allocationRequired]);
   for (auto const& pair : env_) {
     std::string const& key = pair.first;
     std::string const& value = pair.second;
     *ptrBase = stringBase;
     size_t lengthIncludingNullTerminator = key.size() + 1 + value.size() + 1;
     CHECK_GT(stringEnd - lengthIncludingNullTerminator, stringBase);
     memcpy(stringBase, key.c_str(), key.size());
     stringBase += key.size();
     *stringBase++ = '=';
     memcpy(stringBase, value.c_str(), value.size() + 1);
     stringBase += value.size() + 1;
     ++ptrBase;
   }
   *ptrBase = nullptr;
   CHECK_EQ(env_.size(), ptrBase - raw);
   return {raw, [](char** ptr) { delete[] ptr; }};
 }
std::vector< std::string > EnvironmentState::toVector () const
Definition at line 54 of file EnvUtil.cpp.
References env_.
Referenced by operator->().
{
   std::vector<std::string> result;
   for (auto const& pair : env_) {
     result.emplace_back(to<std::string>(pair.first, "=", pair.second));
   }
   return result;
 }
Member Data Documentation
EnvType folly::experimental::EnvironmentState::env_ private
Definition at line 88 of file EnvUtil.h.
Referenced by operator*(), operator->(), setAsCurrentEnvironment(), toPointerArray(), and toVector().
The documentation for this struct was generated from the following files:
proxygen/folly/folly/experimental/EnvUtil.h
proxygen/folly/folly/experimental/EnvUtil.cpp