proxygen: folly::detail::ThreadCachedLists< Tag >::ListHead Struct Reference
folly::detail::ThreadCachedLists< Tag >::ListHead Struct Reference
#include <ThreadCachedLists.h>
Public Member Functions
template<typename Func >
void forEach (Func func)
void splice (ListHead &other)
void splice (AtomicListHead &other)
Public Attributes
Node * head_ {nullptr}
Node * tail_ {nullptr}
Detailed Description
template<typename Tag>
struct folly::detail::ThreadCachedLists< Tag >::ListHead
Definition at line 50 of file ThreadCachedLists.h.
Member Function Documentation
template<typename Tag> template<typename Func > void folly::detail::ThreadCachedLists< Tag >::ListHead::forEach (Func func) inline
Definition at line 56 of file ThreadCachedLists.h.
References folly::collect(), bm::list, and cpp.ast::next().
{
       auto node = tail_;
       while (node != nullptr) {
         auto next = node->next_;
         func(node);
         node = next;
       }
     }
template<typename Tag > void folly::detail::ThreadCachedLists< Tag >::ListHead::splice (ListHead & other)
Definition at line 154 of file ThreadCachedLists.h.
References folly::detail::ThreadCachedLists< Tag >::ListHead::head_, and folly::detail::ThreadCachedLists< Tag >::ListHead::tail_.
Referenced by folly::detail::ThreadCachedLists< Tag >::collect().
{
   if (other.head_ != nullptr) {
     DCHECK(other.tail_ != nullptr);
   } else {
     DCHECK(other.tail_ == nullptr);
     return;
   }
   if (head_) {
     DCHECK(tail_ != nullptr);
     DCHECK(head_->next_ == nullptr);
     head_->next_ = other.tail_;
     head_ = other.head_;
   } else {
     DCHECK(head_ == nullptr);
     head_ = other.head_;
     tail_ = other.tail_;
   }
   other.head_ = nullptr;
   other.tail_ = nullptr;
 }
template<typename Tag > void folly::detail::ThreadCachedLists< Tag >::ListHead::splice (AtomicListHead & other)
Definition at line 178 of file ThreadCachedLists.h.
References folly::detail::ThreadCachedLists< Tag >::AtomicListHead::head_, folly::detail::ThreadCachedLists< Tag >::ListHead::head_, folly::fibers::local(), folly::detail::ThreadCachedLists< Tag >::AtomicListHead::tail_, and folly::detail::ThreadCachedLists< Tag >::ListHead::tail_.
{
   ListHead local;
   auto tail = list.tail_.load();
   if (tail) {
     local.tail_ = list.tail_.exchange(nullptr);
     local.head_ = list.head_.exchange(nullptr);
     splice(local);
   }
 }
Member Data Documentation
template<typename Tag> Node* folly::detail::ThreadCachedLists< Tag >::ListHead::head_ {nullptr}
Definition at line 51 of file ThreadCachedLists.h.
Referenced by folly::detail::ThreadCachedLists< Tag >::ListHead::splice().
template<typename Tag> Node* folly::detail::ThreadCachedLists< Tag >::ListHead::tail_ {nullptr}
Definition at line 52 of file ThreadCachedLists.h.
Referenced by folly::detail::ThreadCachedLists< Tag >::ListHead::splice().
The documentation for this struct was generated from the following file:
proxygen/folly/folly/synchronization/detail/ThreadCachedLists.h