proxygen: folly::fbstring_core< Char >::RefCounted Struct Reference
folly::fbstring_core< Char >::RefCounted Struct Reference
Static Public Member Functions
static constexpr size_t getDataOffset ()
static RefCounted * fromData (Char *p)
static size_t refs (Char *p)
static void incrementRefs (Char *p)
static void decrementRefs (Char *p)
static RefCounted * create (size_t *size)
static RefCounted * create (const Char *data, size_t *size)
static RefCounted * reallocate (Char *const data, const size_t currentSize, const size_t currentCapacity, size_t *newCapacity)
Public Attributes
std::atomic< size_t > refCount_
Char data_ [1]
Detailed Description
template<class Char>
struct folly::fbstring_core< Char >::RefCounted
Definition at line 549 of file FBString.h.
Member Function Documentation
template<class Char> static RefCounted* folly::fbstring_core< Char >::RefCounted::create (size_t * size) inline static
Definition at line 580 of file FBString.h.
References testing::gmock_generated_actions_test::Char(), folly::checkedMalloc(), folly::goodMallocSize(), and folly::fbstring_core< Char >::RefCounted::refCount_.
{
       const size_t allocSize =
           goodMallocSize(getDataOffset() + (*size + 1) * sizeof(Char));
       auto result = static_cast<RefCounted*>(checkedMalloc(allocSize));
       result->refCount_.store(1, std::memory_order_release);
       *size = (allocSize - getDataOffset()) / sizeof(Char) - 1;
       return result;
     }
template<class Char> static RefCounted* folly::fbstring_core< Char >::RefCounted::create (const Char * data, size_t * size) inline static
Definition at line 589 of file FBString.h.
References FBSTRING_LIKELY, folly::fbstring_detail::podCopy(), and folly::size().
{
       const size_t effectiveSize = *size;
       auto result = create(size);
       if (FBSTRING_LIKELY(effectiveSize > 0)) {
         fbstring_detail::podCopy(data, data + effectiveSize, result->data_);
       }
       return result;
     }
template<class Char> static void folly::fbstring_core< Char >::RefCounted::decrementRefs (Char * p) inline static
Definition at line 571 of file FBString.h.
References FBSTRING_ASSERT, and bm::free().
{
       auto const dis = fromData(p);
       size_t oldcnt = dis->refCount_.fetch_sub(1, std::memory_order_acq_rel);
       FBSTRING_ASSERT(oldcnt > 0);
       if (oldcnt == 1) {
         free(dis);
       }
     }
template<class Char> static RefCounted* folly::fbstring_core< Char >::RefCounted::fromData (Char * p) inline static
Definition at line 557 of file FBString.h.
{
       return static_cast<RefCounted*>(static_cast<void*>(
           static_cast<unsigned char*>(static_cast<void*>(p)) -
           getDataOffset()));
     }
template<class Char> static constexpr size_t folly::fbstring_core< Char >::RefCounted::getDataOffset () inline static
Definition at line 553 of file FBString.h.
{
       return offsetof(RefCounted, data_);
     }
template<class Char> static void folly::fbstring_core< Char >::RefCounted::incrementRefs (Char * p) inline static
Definition at line 567 of file FBString.h.
{
       fromData(p)->refCount_.fetch_add(1, std::memory_order_acq_rel);
     }
template<class Char> static RefCounted* folly::fbstring_core< Char >::RefCounted::reallocate (Char *const data, const size_t currentSize, const size_t currentCapacity, size_t * newCapacity) inline static
Definition at line 598 of file FBString.h.
References testing::gmock_generated_actions_test::Char(), FBSTRING_ASSERT, folly::goodMallocSize(), and folly::smartRealloc().
{
       FBSTRING_ASSERT(*newCapacity > 0 && *newCapacity > currentSize);
       const size_t allocNewCapacity =
           goodMallocSize(getDataOffset() + (*newCapacity + 1) * sizeof(Char));
       auto const dis = fromData(data);
       FBSTRING_ASSERT(dis->refCount_.load(std::memory_order_acquire) == 1);
       auto result = static_cast<RefCounted*>(smartRealloc(
           dis,
           getDataOffset() + (currentSize + 1) * sizeof(Char),
           getDataOffset() + (currentCapacity + 1) * sizeof(Char),
           allocNewCapacity));
       FBSTRING_ASSERT(result->refCount_.load(std::memory_order_acquire) == 1);
       *newCapacity = (allocNewCapacity - getDataOffset()) / sizeof(Char) - 1;
       return result;
     }
template<class Char> static size_t folly::fbstring_core< Char >::RefCounted::refs (Char * p) inline static
Definition at line 563 of file FBString.h.
{
       return fromData(p)->refCount_.load(std::memory_order_acquire);
     }
Member Data Documentation
template<class Char> Char folly::fbstring_core< Char >::RefCounted::data_[1]
Definition at line 551 of file FBString.h.
template<class Char> std::atomic<size_t> folly::fbstring_core< Char >::RefCounted::refCount_
Definition at line 550 of file FBString.h.
Referenced by folly::fbstring_core< Char >::RefCounted::create().
The documentation for this struct was generated from the following file:
proxygen/folly/folly/FBString.h