proxygen: Watchdog Struct Reference
Watchdog Struct Reference
#include <SingletonTestStructs.h>
Public Member Functions
Watchdog ()
~Watchdog ()
size_t livingWatchdogCount () const
Watchdog (const Watchdog &)=delete
Watchdog & operator= (const Watchdog &)=delete
Watchdog (Watchdog &&) noexcept=default
Watchdog & operator= (Watchdog &&) noexcept=default
Static Public Member Functions
static std::vector< Watchdog * > & creation_order ()
Public Attributes
const size_t serial_number
Detailed Description
Definition at line 26 of file SingletonTestStructs.h.
Constructor & Destructor Documentation
Watchdog::Watchdog ()
Definition at line 33 of file SingletonTestStructs.cpp.
References creation_order().
Referenced by livingWatchdogCount().
                    : serial_number(++global_counter) {
   creation_order().push_back(this);
 }
Watchdog::~Watchdog () inline
Definition at line 31 of file SingletonTestStructs.h.
References creation_order().
               {
     if (creation_order().back() != this) {
       LOG(FATAL) << "Watchdog destruction order mismatch";
     }
     creation_order().pop_back();
   }
Watchdog::Watchdog (const Watchdog &) delete
Watchdog::Watchdog (Watchdog &&) default noexcept
Member Function Documentation
std::vector< Watchdog * > & Watchdog::creation_order () static
Definition at line 28 of file SingletonTestStructs.cpp.
Referenced by livingWatchdogCount(), TEST(), Watchdog(), and ~Watchdog().
{
   static std::vector<Watchdog*> ret;
   return ret;
 }
size_t Watchdog::livingWatchdogCount () const inline
Definition at line 39 of file SingletonTestStructs.h.
References creation_order(), folly::pushmi::__adl::noexcept(), operator=(), and Watchdog().
{
     return creation_order().size();
   }
Watchdog& Watchdog::operator= (const Watchdog &) delete
Referenced by livingWatchdogCount().
Watchdog& Watchdog::operator= (Watchdog &&) default noexcept
Member Data Documentation
const size_t Watchdog::serial_number
Definition at line 38 of file SingletonTestStructs.h.
The documentation for this struct was generated from the following files:
proxygen/folly/folly/test/SingletonTestStructs.h
proxygen/folly/folly/test/SingletonTestStructs.cpp