proxygen: folly::fibers::FiberManager::FibersPoolResizer Struct Reference
folly::fibers::FiberManager::FibersPoolResizer Struct Reference
Public Member Functions
FibersPoolResizer (FiberManager &fm)
void operator() ()
Private Attributes
FiberManager & fiberManager_
Detailed Description
Definition at line 468 of file FiberManagerInternal.h.
Constructor & Destructor Documentation
folly::fibers::FiberManager::FibersPoolResizer::FibersPoolResizer (FiberManager & fm) inline explicit
Definition at line 469 of file FiberManagerInternal.h.
 : fiberManager_(fm) {}
Member Function Documentation
void folly::fibers::FiberManager::FibersPoolResizer::operator() ()
Definition at line 184 of file FiberManager.cpp.
References folly::constexpr_max(), folly::FATAL, folly::fibers::Fiber::getStack(), folly::fibers::FiberManager::operator=(), folly::size(), and stack_.
{
   fiberManager_.doFibersPoolResizing();
   fiberManager_.timeoutManager_->registerTimeout(
       *this,
       std::chrono::milliseconds(
           fiberManager_.options_.fibersPoolResizePeriodMs));
 }
Member Data Documentation
FiberManager& folly::fibers::FiberManager::FibersPoolResizer::fiberManager_ private
Definition at line 473 of file FiberManagerInternal.h.
The documentation for this struct was generated from the following files:
proxygen/folly/folly/fibers/FiberManagerInternal.h
proxygen/folly/folly/fibers/FiberManager.cpp