proxygen: folly::netops::detail::SocketFileDescriptorMap Struct Reference
folly::netops::detail::SocketFileDescriptorMap Struct Reference
#include <SocketFileDescriptorMap.h>
Static Public Member Functions
static int close (int fd) noexcept
static int fdToSocket (int fd) noexcept
static int socketToFd (int sock) noexcept
Detailed Description
Definition at line 30 of file SocketFileDescriptorMap.h.
Member Function Documentation
static int folly::netops::detail::SocketFileDescriptorMap::close (int fd) inline static noexcept
Definition at line 38 of file SocketFileDescriptorMap.h.
References folly::netops::close().
Referenced by folly::netops::close(), and folly::netops::TEST().
{
     return ::close(fd);
   }
static int folly::netops::detail::SocketFileDescriptorMap::fdToSocket (int fd) inline static noexcept
Definition at line 42 of file SocketFileDescriptorMap.h.
Referenced by folly::NetworkSocket::fromFd(), folly::getLibeventFd(), and folly::netops::TEST().
{
     return fd;
   }
static int folly::netops::detail::SocketFileDescriptorMap::socketToFd (int sock) inline static noexcept
Definition at line 45 of file SocketFileDescriptorMap.h.
Referenced by folly::libeventFdToFd(), folly::netops::TEST(), and folly::NetworkSocket::toFd().
{
     return sock;
   }
The documentation for this struct was generated from the following file:
proxygen/folly/folly/net/detail/SocketFileDescriptorMap.h