proxygen: folly::pushmi::locked_entangled_pair< T, Dual > Struct Template Reference
folly::pushmi::locked_entangled_pair< T, Dual > Struct Template Reference
#include <entangle.h>
Public Member Functions
~locked_entangled_pair ()
locked_entangled_pair (entangled< T, Dual > &e)
locked_entangled_pair ()=delete
locked_entangled_pair (const locked_entangled_pair &)=delete
locked_entangled_pair & operator= (const locked_entangled_pair &)=delete
locked_entangled_pair (locked_entangled_pair &&o)
locked_entangled_pair & operator= (locked_entangled_pair &&o)
Public Attributes
entangled< T, Dual > * e
Detailed Description
template<class T, class Dual>
struct folly::pushmi::locked_entangled_pair< T, Dual >
Definition at line 228 of file entangle.h.
Constructor & Destructor Documentation
template<class T , class Dual > folly::pushmi::locked_entangled_pair< T, Dual >::~locked_entangled_pair () inline
Definition at line 230 of file entangle.h.
References folly::pushmi::entangled< T, Dual >::unlockBoth().
{
     if (!!e) {
       e->unlockBoth();
     }
   }
template<class T , class Dual > folly::pushmi::locked_entangled_pair< T, Dual >::locked_entangled_pair (entangled< T, Dual > & e) inline explicit
Definition at line 235 of file entangle.h.
References folly::pushmi::entangled< T, Dual >::dual, folly::gen::first, folly::pushmi::entangled< T, Dual >::lockBoth(), folly::pushmi::entangled< T, Dual >::operator=(), and folly::pushmi::entangled< T, Dual >::t.
                                                         : e(std::addressof(e)) {
     this->e->lockBoth();
     this->first = std::addressof(this->e->t);
     this->second = !!this->e->dual ? std::addressof(this->e->dual->t) : nullptr;
   }
template<class T , class Dual > folly::pushmi::locked_entangled_pair< T, Dual >::locked_entangled_pair () delete
template<class T , class Dual > folly::pushmi::locked_entangled_pair< T, Dual >::locked_entangled_pair (const locked_entangled_pair< T, Dual > &) delete
template<class T , class Dual > folly::pushmi::locked_entangled_pair< T, Dual >::locked_entangled_pair (locked_entangled_pair< T, Dual > && o) inline
Definition at line 243 of file entangle.h.
       : std::pair<T*, Dual*>(o), e(o.e) {
     o.e = nullptr;
   }
Member Function Documentation
template<class T , class Dual > locked_entangled_pair& folly::pushmi::locked_entangled_pair< T, Dual >::operator= (const locked_entangled_pair< T, Dual > &) delete
template<class T , class Dual > locked_entangled_pair& folly::pushmi::locked_entangled_pair< T, Dual >::operator= (locked_entangled_pair< T, Dual > && o) inline
Definition at line 247 of file entangle.h.
{
     static_cast<std::pair<T*, Dual*>&>(*this) =
         static_cast<std::pair<T*, Dual*>&&>(o);
     e = o.e;
     o.e = nullptr;
     return *this;
   }
Member Data Documentation
template<class T , class Dual > entangled<T, Dual>* folly::pushmi::locked_entangled_pair< T, Dual >::e
Definition at line 229 of file entangle.h.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/pushmi/entangle.h