proxygen: folly::detail::Lazy< Func > Struct Template Reference
folly::detail::Lazy< Func > Struct Template Reference
#include <Lazy.h>
Public Types
typedef invoke_result_t< Func > result_type
Public Member Functions
Lazy (Func &&f)
Lazy (const Func &f)
Lazy (Lazy &&o)
Lazy (const Lazy &)=delete
Lazy & operator= (const Lazy &)=delete
Lazy & operator= (Lazy &&)=delete
const result_type & operator() () const
result_type & operator() ()
Private Member Functions
void ensure_initialized () const
Private Attributes
Optional< result_type > value_
Func func_
Detailed Description
template<class Func>
struct folly::detail::Lazy< Func >
Definition at line 91 of file Lazy.h.
Member Typedef Documentation
template<class Func > typedef invoke_result_t<Func> folly::detail::Lazy< Func >::result_type
Definition at line 92 of file Lazy.h.
Constructor & Destructor Documentation
template<class Func > folly::detail::Lazy< Func >::Lazy (Func && f) inline explicit
Definition at line 101 of file Lazy.h.
Referenced by folly::detail::Lazy< Func >::Lazy().
 : func_(std::move(f)) {}
template<class Func > folly::detail::Lazy< Func >::Lazy (const Func & f) inline explicit
Definition at line 102 of file Lazy.h.
 : func_(f) {}
template<class Func > folly::detail::Lazy< Func >::Lazy (Lazy< Func > && o) inline
Definition at line 104 of file Lazy.h.
References folly::detail::Lazy< Func >::Lazy(), and folly::detail::Lazy< Func >::operator=().
 : value_(std::move(o.value_)), func_(std::move(o.func_)) {}
template<class Func > folly::detail::Lazy< Func >::Lazy (const Lazy< Func > &) delete
Member Function Documentation
template<class Func > void folly::detail::Lazy< Func >::ensure_initialized () const inline private
Definition at line 123 of file Lazy.h.
References folly::detail::Lazy< Func >::func_, and folly::detail::Lazy< Func >::value_.
Referenced by folly::detail::Lazy< Func >::operator()().
{
     if (!value_) {
       value_ = func_();
     }
   }
template<class Func > const result_type& folly::detail::Lazy< Func >::operator() () const inline
Definition at line 110 of file Lazy.h.
References folly::detail::Lazy< Func >::ensure_initialized(), and folly::detail::Lazy< Func >::value_.
{
     ensure_initialized();
     return *value_;
   }
template<class Func > result_type& folly::detail::Lazy< Func >::operator() () inline
Definition at line 116 of file Lazy.h.
References folly::detail::Lazy< Func >::ensure_initialized(), and folly::detail::Lazy< Func >::value_.
{
     ensure_initialized();
     return *value_;
   }
template<class Func > Lazy& folly::detail::Lazy< Func >::operator= (const Lazy< Func > &) delete
Referenced by folly::detail::Lazy< Func >::Lazy().
template<class Func > Lazy& folly::detail::Lazy< Func >::operator= (Lazy< Func > &&) delete
Member Data Documentation
template<class Func > Func folly::detail::Lazy< Func >::func_ mutable private
Definition at line 130 of file Lazy.h.
Referenced by folly::detail::Lazy< Func >::ensure_initialized().
template<class Func > Optional<result_type> folly::detail::Lazy< Func >::value_ mutable private
Definition at line 129 of file Lazy.h.
Referenced by folly::detail::Lazy< Func >::ensure_initialized(), and folly::detail::Lazy< Func >::operator()().
The documentation for this struct was generated from the following file:
proxygen/folly/folly/Lazy.h