proxygen: folly::gen::FBounded< Self > Struct Template Reference
folly::gen::FBounded< Self > Struct Template Reference
#include <Core-inl.h>
Public Member Functions
const Self & self () const
Self & self ()
Detailed Description
template<class Self>
struct folly::gen::FBounded< Self >
FBounded - Helper type for the curiously recurring template pattern, used heavily here to enable inlining and obviate virtual functions
Definition at line 70 of file Core-inl.h.
Member Function Documentation
template<class Self > const Self& folly::gen::FBounded< Self >::self () const inline
Definition at line 71 of file Core-inl.h.
Referenced by folly::gen::detail::Interleave< Container >::compose(), folly::gen::detail::Zip< Container >::compose(), folly::gen::detail::Parallel< Ops >::Generator< Input, Source, InputDecayed, Composed, Output, OutputDecayed >::Pusher< all >::compose(), folly::gen::detail::PMap< Predicate >::compose(), folly::gen::detail::StringResplitter::compose(), folly::gen::detail::Composed< First, Second >::compose(), folly::gen::detail::Parallel< Ops >::compose(), folly::gen::detail::Map< Predicate >::compose(), folly::gen::detail::Filter< Predicate >::compose(), folly::gen::detail::Until< Predicate >::compose(), folly::gen::detail::Take::compose(), folly::gen::detail::Visit< Visitor >::compose(), folly::gen::detail::Stride::compose(), folly::gen::detail::Sample< Random >::compose(), folly::gen::detail::Skip::compose(), folly::gen::detail::Order< Selector, Comparer >::compose(), folly::gen::detail::GroupBy< Selector >::compose(), folly::gen::detail::GroupByAdjacent< Selector >::compose(), folly::gen::detail::TypeAssertion< Expected >::compose(), folly::gen::detail::Distinct< Selector >::compose(), folly::gen::detail::Batch::compose(), folly::gen::detail::Window::compose(), folly::gen::detail::Concat::compose(), folly::gen::detail::RangeConcat::compose(), folly::gen::detail::GuardImpl< Exception, ErrorHandler >::compose(), folly::gen::detail::Dereference::compose(), folly::gen::detail::Indirect::compose(), folly::gen::detail::Cycle< forever >::compose(), folly::gen::operator+(), and folly::gen::operator|().
{
     return *static_cast<const Self*>(this);
   }
template<class Self > Self& folly::gen::FBounded< Self >::self () inline
Definition at line 75 of file Core-inl.h.
                {
     return *static_cast<Self*>(this);
   }
The documentation for this struct was generated from the following file:
proxygen/folly/folly/gen/Core-inl.h