proxygen: testing::Flags Struct Reference
testing::Flags Struct Reference
Public Member Functions
Flags ()
Flags ()
Flags ()
Static Public Member Functions
static Flags AlsoRunDisabledTests (bool also_run_disabled_tests)
static Flags BreakOnFailure (bool break_on_failure)
static Flags CatchExceptions (bool catch_exceptions)
static Flags DeathTestUseFork (bool death_test_use_fork)
static Flags Filter (const char *filter)
static Flags ListTests (bool list_tests)
static Flags Output (const char *output)
static Flags PrintTime (bool print_time)
static Flags RandomSeed (Int32 random_seed)
static Flags Repeat (Int32 repeat)
static Flags Shuffle (bool shuffle)
static Flags StackTraceDepth (Int32 stack_trace_depth)
static Flags StreamResultTo (const char *stream_result_to)
static Flags ThrowOnFailure (bool throw_on_failure)
static Flags AlsoRunDisabledTests (bool also_run_disabled_tests)
static Flags BreakOnFailure (bool break_on_failure)
static Flags CatchExceptions (bool catch_exceptions)
static Flags DeathTestUseFork (bool death_test_use_fork)
static Flags Filter (const char *filter)
static Flags ListTests (bool list_tests)
static Flags Output (const char *output)
static Flags PrintTime (bool print_time)
static Flags RandomSeed (Int32 random_seed)
static Flags Repeat (Int32 repeat)
static Flags Shuffle (bool shuffle)
static Flags StackTraceDepth (Int32 stack_trace_depth)
static Flags StreamResultTo (const char *stream_result_to)
static Flags ThrowOnFailure (bool throw_on_failure)
static Flags AlsoRunDisabledTests (bool also_run_disabled_tests)
static Flags BreakOnFailure (bool break_on_failure)
static Flags CatchExceptions (bool catch_exceptions)
static Flags DeathTestUseFork (bool death_test_use_fork)
static Flags Filter (const char *filter)
static Flags ListTests (bool list_tests)
static Flags Output (const char *output)
static Flags PrintTime (bool print_time)
static Flags RandomSeed (Int32 random_seed)
static Flags Repeat (Int32 repeat)
static Flags Shuffle (bool shuffle)
static Flags StackTraceDepth (Int32 stack_trace_depth)
static Flags StreamResultTo (const char *stream_result_to)
static Flags ThrowOnFailure (bool throw_on_failure)
Public Attributes
bool also_run_disabled_tests
bool break_on_failure
bool catch_exceptions
bool death_test_use_fork
const char * filter
bool list_tests
const char * output
bool print_time
Int32 random_seed
Int32 repeat
bool shuffle
Int32 stack_trace_depth
const char * stream_result_to
bool throw_on_failure
Detailed Description
Definition at line 5456 of file gtest_unittest.cc.
Constructor & Destructor Documentation
testing::Flags::Flags () inline
Definition at line 5458 of file gtest_unittest.cc.
           : also_run_disabled_tests(false),
             break_on_failure(false),
             catch_exceptions(false),
             death_test_use_fork(false),
             filter(""),
             list_tests(false),
             output(""),
             print_time(true),
             random_seed(0),
             repeat(1),
             shuffle(false),
             stack_trace_depth(kMaxStackTraceDepth),
             stream_result_to(""),
             throw_on_failure(false) {}
testing::Flags::Flags () inline
Definition at line 5458 of file gtest_unittest.cc.
           : also_run_disabled_tests(false),
             break_on_failure(false),
             catch_exceptions(false),
             death_test_use_fork(false),
             filter(""),
             list_tests(false),
             output(""),
             print_time(true),
             random_seed(0),
             repeat(1),
             shuffle(false),
             stack_trace_depth(kMaxStackTraceDepth),
             stream_result_to(""),
             throw_on_failure(false) {}
testing::Flags::Flags () inline
Definition at line 5458 of file gtest_unittest.cc.
           : also_run_disabled_tests(false),
             break_on_failure(false),
             catch_exceptions(false),
             death_test_use_fork(false),
             filter(""),
             list_tests(false),
             output(""),
             print_time(true),
             random_seed(0),
             repeat(1),
             shuffle(false),
             stack_trace_depth(kMaxStackTraceDepth),
             stream_result_to(""),
             throw_on_failure(false) {}
Member Function Documentation
static Flags testing::Flags::AlsoRunDisabledTests (bool also_run_disabled_tests) inline static
Definition at line 5477 of file gtest_unittest.cc.
References also_run_disabled_tests.
Referenced by testing::TEST_F().
{
     Flags flags;
     flags.also_run_disabled_tests = also_run_disabled_tests;
     return flags;
   }
static Flags testing::Flags::AlsoRunDisabledTests (bool also_run_disabled_tests) inline static
Definition at line 5477 of file gtest_unittest.cc.
References also_run_disabled_tests.
{
     Flags flags;
     flags.also_run_disabled_tests = also_run_disabled_tests;
     return flags;
   }
static Flags testing::Flags::AlsoRunDisabledTests (bool also_run_disabled_tests) inline static
Definition at line 5477 of file gtest_unittest.cc.
References also_run_disabled_tests.
{
     Flags flags;
     flags.also_run_disabled_tests = also_run_disabled_tests;
     return flags;
   }
static Flags testing::Flags::BreakOnFailure (bool break_on_failure) inline static
Definition at line 5485 of file gtest_unittest.cc.
References break_on_failure.
Referenced by testing::TEST_F().
{
     Flags flags;
     flags.break_on_failure = break_on_failure;
     return flags;
   }
static Flags testing::Flags::BreakOnFailure (bool break_on_failure) inline static
Definition at line 5485 of file gtest_unittest.cc.
References break_on_failure.
{
     Flags flags;
     flags.break_on_failure = break_on_failure;
     return flags;
   }
static Flags testing::Flags::BreakOnFailure (bool break_on_failure) inline static
Definition at line 5485 of file gtest_unittest.cc.
References break_on_failure.
{
     Flags flags;
     flags.break_on_failure = break_on_failure;
     return flags;
   }
static Flags testing::Flags::CatchExceptions (bool catch_exceptions) inline static
Definition at line 5493 of file gtest_unittest.cc.
References catch_exceptions.
{
     Flags flags;
     flags.catch_exceptions = catch_exceptions;
     return flags;
   }
static Flags testing::Flags::CatchExceptions (bool catch_exceptions) inline static
Definition at line 5493 of file gtest_unittest.cc.
References catch_exceptions.
Referenced by testing::TEST_F().
{
     Flags flags;
     flags.catch_exceptions = catch_exceptions;
     return flags;
   }
static Flags testing::Flags::CatchExceptions (bool catch_exceptions) inline static
Definition at line 5493 of file gtest_unittest.cc.
References catch_exceptions.
{
     Flags flags;
     flags.catch_exceptions = catch_exceptions;
     return flags;
   }
static Flags testing::Flags::DeathTestUseFork (bool death_test_use_fork) inline static
Definition at line 5501 of file gtest_unittest.cc.
References death_test_use_fork.
{
     Flags flags;
     flags.death_test_use_fork = death_test_use_fork;
     return flags;
   }
static Flags testing::Flags::DeathTestUseFork (bool death_test_use_fork) inline static
Definition at line 5501 of file gtest_unittest.cc.
References death_test_use_fork.
Referenced by testing::TEST_F().
{
     Flags flags;
     flags.death_test_use_fork = death_test_use_fork;
     return flags;
   }
static Flags testing::Flags::DeathTestUseFork (bool death_test_use_fork) inline static
Definition at line 5501 of file gtest_unittest.cc.
References death_test_use_fork.
{
     Flags flags;
     flags.death_test_use_fork = death_test_use_fork;
     return flags;
   }
static Flags testing::Flags::Filter (const char * filter) inline static
Definition at line 5509 of file gtest_unittest.cc.
References folly::pushmi::operators::filter, and filter.
{
     Flags flags;
     flags.filter = filter;
     return flags;
   }
static Flags testing::Flags::Filter (const char * filter) inline static
Definition at line 5509 of file gtest_unittest.cc.
References folly::pushmi::operators::filter, and filter.
{
     Flags flags;
     flags.filter = filter;
     return flags;
   }
static Flags testing::Flags::Filter (const char * filter) inline static
Definition at line 5509 of file gtest_unittest.cc.
References folly::pushmi::operators::filter, and filter.
Referenced by testing::TEST_F().
{
     Flags flags;
     flags.filter = filter;
     return flags;
   }
static Flags testing::Flags::ListTests (bool list_tests) inline static
Definition at line 5517 of file gtest_unittest.cc.
References list_tests.
{
     Flags flags;
     flags.list_tests = list_tests;
     return flags;
   }
static Flags testing::Flags::ListTests (bool list_tests) inline static
Definition at line 5517 of file gtest_unittest.cc.
References list_tests.
{
     Flags flags;
     flags.list_tests = list_tests;
     return flags;
   }
static Flags testing::Flags::ListTests (bool list_tests) inline static
Definition at line 5517 of file gtest_unittest.cc.
References list_tests.
Referenced by testing::TEST_F().
{
     Flags flags;
     flags.list_tests = list_tests;
     return flags;
   }
static Flags testing::Flags::Output (const char * output) inline static
Definition at line 5525 of file gtest_unittest.cc.
References gmock_output_test::output, and output.
{
     Flags flags;
     flags.output = output;
     return flags;
   }
static Flags testing::Flags::Output (const char * output) inline static
Definition at line 5525 of file gtest_unittest.cc.
References gmock_output_test::output, and output.
{
     Flags flags;
     flags.output = output;
     return flags;
   }
static Flags testing::Flags::Output (const char * output) inline static
Definition at line 5525 of file gtest_unittest.cc.
References gmock_output_test::output, and output.
Referenced by testing::TEST_F().
{
     Flags flags;
     flags.output = output;
     return flags;
   }
static Flags testing::Flags::PrintTime (bool print_time) inline static
Definition at line 5533 of file gtest_unittest.cc.
References print_time.
Referenced by testing::TEST_F().
{
     Flags flags;
     flags.print_time = print_time;
     return flags;
   }
static Flags testing::Flags::PrintTime (bool print_time) inline static
Definition at line 5533 of file gtest_unittest.cc.
References print_time.
{
     Flags flags;
     flags.print_time = print_time;
     return flags;
   }
static Flags testing::Flags::PrintTime (bool print_time) inline static
Definition at line 5533 of file gtest_unittest.cc.
References print_time.
{
     Flags flags;
     flags.print_time = print_time;
     return flags;
   }
static Flags testing::Flags::RandomSeed (Int32 random_seed) inline static
Definition at line 5541 of file gtest_unittest.cc.
References random_seed.
{
     Flags flags;
     flags.random_seed = random_seed;
     return flags;
   }
static Flags testing::Flags::RandomSeed (Int32 random_seed) inline static
Definition at line 5541 of file gtest_unittest.cc.
References random_seed.
{
     Flags flags;
     flags.random_seed = random_seed;
     return flags;
   }
static Flags testing::Flags::RandomSeed (Int32 random_seed) inline static
Definition at line 5541 of file gtest_unittest.cc.
References random_seed.
Referenced by testing::TEST_F().
{
     Flags flags;
     flags.random_seed = random_seed;
     return flags;
   }
static Flags testing::Flags::Repeat (Int32 repeat) inline static
Definition at line 5549 of file gtest_unittest.cc.
References repeat(), and repeat.
Referenced by testing::TEST_F().
{
     Flags flags;
     flags.repeat = repeat;
     return flags;
   }
static Flags testing::Flags::Repeat (Int32 repeat) inline static
Definition at line 5549 of file gtest_unittest.cc.
References repeat(), and repeat.
{
     Flags flags;
     flags.repeat = repeat;
     return flags;
   }
static Flags testing::Flags::Repeat (Int32 repeat) inline static
Definition at line 5549 of file gtest_unittest.cc.
References repeat(), and repeat.
{
     Flags flags;
     flags.repeat = repeat;
     return flags;
   }
static Flags testing::Flags::Shuffle (bool shuffle) inline static
Definition at line 5557 of file gtest_unittest.cc.
References shuffle.
Referenced by testing::TEST_F().
{
     Flags flags;
     flags.shuffle = shuffle;
     return flags;
   }
static Flags testing::Flags::Shuffle (bool shuffle) inline static
Definition at line 5557 of file gtest_unittest.cc.
References shuffle.
{
     Flags flags;
     flags.shuffle = shuffle;
     return flags;
   }
static Flags testing::Flags::Shuffle (bool shuffle) inline static
Definition at line 5557 of file gtest_unittest.cc.
References shuffle.
{
     Flags flags;
     flags.shuffle = shuffle;
     return flags;
   }
static Flags testing::Flags::StackTraceDepth (Int32 stack_trace_depth) inline static
Definition at line 5565 of file gtest_unittest.cc.
References stack_trace_depth.
{
     Flags flags;
     flags.stack_trace_depth = stack_trace_depth;
     return flags;
   }
static Flags testing::Flags::StackTraceDepth (Int32 stack_trace_depth) inline static
Definition at line 5565 of file gtest_unittest.cc.
References stack_trace_depth.
{
     Flags flags;
     flags.stack_trace_depth = stack_trace_depth;
     return flags;
   }
static Flags testing::Flags::StackTraceDepth (Int32 stack_trace_depth) inline static
Definition at line 5565 of file gtest_unittest.cc.
References stack_trace_depth.
Referenced by testing::TEST_F().
{
     Flags flags;
     flags.stack_trace_depth = stack_trace_depth;
     return flags;
   }
static Flags testing::Flags::StreamResultTo (const char * stream_result_to) inline static
Definition at line 5573 of file gtest_unittest.cc.
References stream_result_to.
{
     Flags flags;
     flags.stream_result_to = stream_result_to;
     return flags;
   }
static Flags testing::Flags::StreamResultTo (const char * stream_result_to) inline static
Definition at line 5573 of file gtest_unittest.cc.
References stream_result_to.
{
     Flags flags;
     flags.stream_result_to = stream_result_to;
     return flags;
   }
static Flags testing::Flags::StreamResultTo (const char * stream_result_to) inline static
Definition at line 5573 of file gtest_unittest.cc.
References stream_result_to.
Referenced by testing::TEST_F().
{
     Flags flags;
     flags.stream_result_to = stream_result_to;
     return flags;
   }
static Flags testing::Flags::ThrowOnFailure (bool throw_on_failure) inline static
Definition at line 5581 of file gtest_unittest.cc.
References folly::pushmi::operators::filter, gmock_output_test::output, repeat(), and throw_on_failure.
{
     Flags flags;
     flags.throw_on_failure = throw_on_failure;
     return flags;
   }
static Flags testing::Flags::ThrowOnFailure (bool throw_on_failure) inline static
Definition at line 5581 of file gtest_unittest.cc.
References throw_on_failure.
Referenced by testing::TEST_F().
{
     Flags flags;
     flags.throw_on_failure = throw_on_failure;
     return flags;
   }
static Flags testing::Flags::ThrowOnFailure (bool throw_on_failure) inline static
Definition at line 5581 of file gtest_unittest.cc.
References folly::pushmi::operators::filter, gmock_output_test::output, repeat(), and throw_on_failure.
{
     Flags flags;
     flags.throw_on_failure = throw_on_failure;
     return flags;
   }
Member Data Documentation
bool testing::Flags::also_run_disabled_tests
Definition at line 5588 of file gtest_unittest.cc.
Referenced by AlsoRunDisabledTests(), and testing::InitGoogleTestTest::CheckFlags().
bool testing::Flags::break_on_failure
Definition at line 5589 of file gtest_unittest.cc.
Referenced by BreakOnFailure(), testing::InitGoogleTestTest::CheckFlags(), and testing::TEST_F().
bool testing::Flags::catch_exceptions
Definition at line 5590 of file gtest_unittest.cc.
Referenced by CatchExceptions(), and testing::InitGoogleTestTest::CheckFlags().
bool testing::Flags::death_test_use_fork
Definition at line 5591 of file gtest_unittest.cc.
Referenced by testing::InitGoogleTestTest::CheckFlags(), and DeathTestUseFork().
const char * testing::Flags::filter
Definition at line 5592 of file gtest_unittest.cc.
Referenced by testing::InitGoogleTestTest::CheckFlags(), Filter(), and testing::TEST_F().
bool testing::Flags::list_tests
Definition at line 5593 of file gtest_unittest.cc.
Referenced by testing::InitGoogleTestTest::CheckFlags(), ListTests(), and testing::TEST_F().
const char * testing::Flags::output
Definition at line 5594 of file gtest_unittest.cc.
Referenced by testing::InitGoogleTestTest::CheckFlags(), and Output().
bool testing::Flags::print_time
Definition at line 5595 of file gtest_unittest.cc.
Referenced by testing::InitGoogleTestTest::CheckFlags(), and PrintTime().
Int32 testing::Flags::random_seed
Definition at line 5596 of file gtest_unittest.cc.
Referenced by testing::InitGoogleTestTest::CheckFlags(), and RandomSeed().
Int32 testing::Flags::repeat
Definition at line 5597 of file gtest_unittest.cc.
Referenced by testing::InitGoogleTestTest::CheckFlags(), and Repeat().
bool testing::Flags::shuffle
Definition at line 5598 of file gtest_unittest.cc.
Referenced by testing::InitGoogleTestTest::CheckFlags(), and Shuffle().
Int32 testing::Flags::stack_trace_depth
Definition at line 5599 of file gtest_unittest.cc.
Referenced by testing::InitGoogleTestTest::CheckFlags(), and StackTraceDepth().
const char * testing::Flags::stream_result_to
Definition at line 5600 of file gtest_unittest.cc.
Referenced by testing::InitGoogleTestTest::CheckFlags(), and StreamResultTo().
bool testing::Flags::throw_on_failure
Definition at line 5601 of file gtest_unittest.cc.
Referenced by testing::InitGoogleTestTest::CheckFlags(), and ThrowOnFailure().
The documentation for this struct was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest_unittest.cc