proxygen: folly::pushmi::make_flow_receiver_fn Struct Reference
folly::pushmi::make_flow_receiver_fn Struct Reference
#include <flow_receiver.h>
Public Member Functions
auto operator() () const
requires PUSHMI_EXP (lazy::True<> PUSHMI_BROKEN_SUBSUMPTION(PUSHMI_ANDnot lazy::FlowReceiverDataArg< VF >))) auto operator()(VF nf) const
template<class... EFN>
auto operator() (on_error_fn< EFN... > ef) const
template<class... DFN>
auto operator() (on_done_fn< DFN... > df) const
requires PUSHMI_EXP (lazy::True<> PUSHMI_BROKEN_SUBSUMPTION(PUSHMI_ANDnot lazy::FlowReceiverDataArg< VF > PUSHMI_ANDnot lazy::Invocable< EF & >))) auto operator()(VF nf
requires PUSHMI_EXP (lazy::True<> PUSHMI_AND lazy::Invocable< DF & > PUSHMI_BROKEN_SUBSUMPTION(PUSHMI_ANDnot lazy::FlowReceiverDataArg< EF >))) auto operator()(EF ef
requires PUSHMI_EXP (lazy::Invocable< DF & > PUSHMI_BROKEN_SUBSUMPTION(PUSHMI_ANDnot lazy::FlowReceiverDataArg< VF >))) auto operator()(VF nf
requires PUSHMI_EXP (lazy::Invocable< DF & > PUSHMI_BROKEN_SUBSUMPTION(PUSHMI_ANDnot lazy::FlowReceiverDataArg< VF >))) auto operator()(VF nf
requires PUSHMI_EXP (lazy::True<> PUSHMI_AND lazy::FlowReceiverDataArg< Data >)) auto operator()(Data d) const
requires PUSHMI_EXP (lazy::True<> PUSHMI_AND lazy::FlowReceiverDataArg< Data >)) auto operator()(Data d
requires PUSHMI_EXP (lazy::FlowReceiverDataArg< Data >)) auto operator()(Data d
requires PUSHMI_EXP (lazy::FlowReceiverDataArg< Data >)) auto operator()(Data d
requires PUSHMI_EXP (lazy::FlowReceiverDataArg< Data > PUSHMI_BROKEN_SUBSUMPTION(PUSHMI_ANDnot lazy::Invocable< DEF &, Data & >))) auto operator()(Data d
requires PUSHMI_EXP (lazy::FlowReceiverDataArg< Data > PUSHMI_AND lazy::Invocable< DDF &, Data & >)) auto operator()(Data d
requires PUSHMI_EXP (lazy::FlowReceiverDataArg< Data > PUSHMI_AND lazy::Invocable< DDF &, Data & >)) auto operator()(Data d
requires PUSHMI_EXP (lazy::FlowReceiverDataArg< Data > PUSHMI_AND lazy::Invocable< DDF &, Data & >)) auto operator()(Data d
Public Attributes
requires EF ef const
requires DF df const
requires EF ef
requires EF DF df const
requires EF DF df
requires EF DF StrtF strtf const
requires DVF nf const
requires on_error_fn< DEFN... > ef const
requires on_done_fn< DDFN... > df const
requires DVF nf
requires DVF DEF ef const
requires DEF ef
requires DEF DDF df const
requires DVF DEF ef
requires DVF DEF DDF df const
requires DVF DEF DDF df
requires DVF DEF DDF DStrtF strtf const
Detailed Description
Definition at line 325 of file flow_receiver.h.
Member Function Documentation
auto folly::pushmi::make_flow_receiver_fn::operator() () const inline
Definition at line 326 of file flow_receiver.h.
References folly::pushmi::PUSHMI_TEMPLATE().
{
     return flow_receiver<>{};
   }
template<class... EFN> auto folly::pushmi::make_flow_receiver_fn::operator() (on_error_fn< EFN... > ef) const inline
Definition at line 339 of file flow_receiver.h.
References folly::gen::move.
{
     return flow_receiver<ignoreVF, on_error_fn<EFN...>, ignoreDF, ignoreStrtF>{
       std::move(ef)};
   }
template<class... DFN> auto folly::pushmi::make_flow_receiver_fn::operator() (on_done_fn< DFN... > df) const inline
Definition at line 344 of file flow_receiver.h.
References folly::gen::move, PUSHMI_AND, PUSHMI_BROKEN_SUBSUMPTION, PUSHMI_EXP, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return flow_receiver<ignoreVF, abortEF, on_done_fn<DFN...>, ignoreStrtF>{
       std::move(df)};
   }
requires folly::pushmi::make_flow_receiver_fn::PUSHMI_EXP (lazy::True<> PUSHMI_BROKEN_SUBSUMPTIONPUSHMI_ANDnot lazy::FlowReceiverDataArg< VF >) const inline
Definition at line 330 of file flow_receiver.h.
References folly::gen::move.
{
     return flow_receiver<VF, abortEF, ignoreDF, ignoreStrtF>{
       std::move(nf)};
   }
requires folly::pushmi::make_flow_receiver_fn::PUSHMI_EXP (lazy::True<> PUSHMI_BROKEN_SUBSUMPTIONPUSHMI_ANDnot lazy::FlowReceiverDataArg< VF > PUSHMI_ANDnot lazy::Invocable< EF & >)
requires folly::pushmi::make_flow_receiver_fn::PUSHMI_EXP (lazy::True<> PUSHMI_AND lazy::Invocable< DF & > PUSHMI_BROKEN_SUBSUMPTIONPUSHMI_ANDnot lazy::FlowReceiverDataArg< EF >)
requires folly::pushmi::make_flow_receiver_fn::PUSHMI_EXP (lazy::Invocable< DF & > PUSHMI_BROKEN_SUBSUMPTIONPUSHMI_ANDnot lazy::FlowReceiverDataArg< VF >)
requires folly::pushmi::make_flow_receiver_fn::PUSHMI_EXP (lazy::Invocable< DF & > PUSHMI_BROKEN_SUBSUMPTIONPUSHMI_ANDnot lazy::FlowReceiverDataArg< VF >)
requires folly::pushmi::make_flow_receiver_fn::PUSHMI_EXP (lazy::True<> PUSHMI_AND lazy::FlowReceiverDataArg< Data >) const inline
Definition at line 386 of file flow_receiver.h.
References folly::gen::move, PUSHMI_AND, PUSHMI_EXP, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return flow_receiver<Data, passDVF, passDEF, passDDF, passDStrtF>{
         std::move(d)};
   }
requires folly::pushmi::make_flow_receiver_fn::PUSHMI_EXP (lazy::True<> PUSHMI_AND lazy::FlowReceiverDataArg< Data >)
requires folly::pushmi::make_flow_receiver_fn::PUSHMI_EXP (lazy::FlowReceiverDataArg< Data >)
requires folly::pushmi::make_flow_receiver_fn::PUSHMI_EXP (lazy::FlowReceiverDataArg< Data >)
requires folly::pushmi::make_flow_receiver_fn::PUSHMI_EXP (lazy::FlowReceiverDataArg< Data > PUSHMI_BROKEN_SUBSUMPTIONPUSHMI_ANDnot lazy::Invocable< DEF &, Data & >)
requires folly::pushmi::make_flow_receiver_fn::PUSHMI_EXP (lazy::FlowReceiverDataArg< Data > PUSHMI_AND lazy::Invocable< DDF &, Data & >)
requires folly::pushmi::make_flow_receiver_fn::PUSHMI_EXP (lazy::FlowReceiverDataArg< Data > PUSHMI_AND lazy::Invocable< DDF &, Data & >)
requires folly::pushmi::make_flow_receiver_fn::PUSHMI_EXP (lazy::FlowReceiverDataArg< Data > PUSHMI_AND lazy::Invocable< DDF &, Data & >)
Member Data Documentation
requires EF ef folly::pushmi::make_flow_receiver_fn::const
Initial value:
{
    return flow_receiver<VF, EF, ignoreDF, ignoreStrtF>{std::move(nf),
      std::move(ef)}
Definition at line 354 of file flow_receiver.h.
requires DF df folly::pushmi::make_flow_receiver_fn::const
Initial value:
{
    return flow_receiver<ignoreVF, EF, DF, ignoreStrtF>{std::move(ef), std::move(df)}
Definition at line 364 of file flow_receiver.h.
requires EF DF df folly::pushmi::make_flow_receiver_fn::const
Initial value:
{
    return flow_receiver<VF, EF, DF, ignoreStrtF>{std::move(nf),
      std::move(ef), std::move(df)}
Definition at line 372 of file flow_receiver.h.
requires EF DF StrtF strtf folly::pushmi::make_flow_receiver_fn::const
Initial value:
{
    return flow_receiver<VF, EF, DF, StrtF>{std::move(nf), std::move(ef),
      std::move(df), std::move(strtf)}
Definition at line 381 of file flow_receiver.h.
requires DVF nf folly::pushmi::make_flow_receiver_fn::const
Initial value:
{
    return flow_receiver<Data, DVF, passDEF, passDDF, passDStrtF>{
      std::move(d), std::move(nf)}
Definition at line 397 of file flow_receiver.h.
requires on_error_fn<DEFN...> ef folly::pushmi::make_flow_receiver_fn::const
Initial value:
{
    return flow_receiver<Data, passDVF, on_error_fn<DEFN...>, passDDF, passDStrtF>{
      std::move(d), std::move(ef)}
Definition at line 404 of file flow_receiver.h.
requires on_done_fn<DDFN...> df folly::pushmi::make_flow_receiver_fn::const
Initial value:
{
    return flow_receiver<Data, passDVF, passDEF, on_done_fn<DDFN...>, passDStrtF>{
      std::move(d), std::move(df)}
Definition at line 411 of file flow_receiver.h.
requires DVF DEF ef folly::pushmi::make_flow_receiver_fn::const
Initial value:
{
    return flow_receiver<Data, DVF, DEF, passDDF, passDStrtF>{std::move(d), std::move(nf), std::move(ef)}
Definition at line 420 of file flow_receiver.h.
requires DEF DDF df folly::pushmi::make_flow_receiver_fn::const
Initial value:
{
    return flow_receiver<Data, passDVF, DEF, DDF, passDStrtF>{
      std::move(d), std::move(ef), std::move(df)}
Definition at line 427 of file flow_receiver.h.
requires DVF DEF DDF df folly::pushmi::make_flow_receiver_fn::const
Initial value:
{
    return flow_receiver<Data, DVF, DEF, DDF, passDStrtF>{std::move(d),
      std::move(nf), std::move(ef), std::move(df)}
Definition at line 435 of file flow_receiver.h.
requires DVF DEF DDF DStrtF strtf folly::pushmi::make_flow_receiver_fn::const
Initial value:
{
    return flow_receiver<Data, DVF, DEF, DDF, DStrtF>{std::move(d),
      std::move(nf), std::move(ef), std::move(df), std::move(strtf)}
Definition at line 443 of file flow_receiver.h.
requires EF DF folly::pushmi::make_flow_receiver_fn::df
Definition at line 381 of file flow_receiver.h.
requires DVF DEF DDF folly::pushmi::make_flow_receiver_fn::df
Definition at line 443 of file flow_receiver.h.
requires DVF DEF folly::pushmi::make_flow_receiver_fn::ef
Definition at line 372 of file flow_receiver.h.
requires DEF folly::pushmi::make_flow_receiver_fn::ef
Definition at line 427 of file flow_receiver.h.
requires DVF DEF folly::pushmi::make_flow_receiver_fn::ef
Definition at line 435 of file flow_receiver.h.
requires DVF folly::pushmi::make_flow_receiver_fn::nf
Definition at line 420 of file flow_receiver.h.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/pushmi/flow_receiver.h