proxygen: folly::pushmi::detail::for_each_fn::Pull< In, Out > Struct Template Reference
folly::pushmi::detail::for_each_fn::Pull< In, Out > Struct Template Reference
Public Types
using properties = property_set_insert_t< properties_t< Out >, property_set< is_flow<>>>
Public Member Functions
Pull (Out out)
template<class... VN>
void value (VN &&...vn)
template<class E >
void error (E &&e)
void done ()
requires Receiver< Up > &&ReceiveValue< Up, std::ptrdiff_t > void starting (Up up)
requires ReceiveValue< Up > void starting (Up)
Public Attributes
std::function< void(std::ptrdiff_t)> pull
Detailed Description
template<class In, class Out>
struct folly::pushmi::detail::for_each_fn::Pull< In, Out >
Definition at line 32 of file for_each.h.
Member Typedef Documentation
template<class In , class Out > using folly::pushmi::detail::for_each_fn::Pull< In, Out >::properties = property_set_insert_t<properties_t<Out>, property_set<is_flow<>>>
Definition at line 35 of file for_each.h.
Constructor & Destructor Documentation
template<class In , class Out > folly::pushmi::detail::for_each_fn::Pull< In, Out >::Pull (Out out) inline explicit
Definition at line 33 of file for_each.h.
 : Out(std::move(out)) {}
Member Function Documentation
template<class In , class Out > void folly::pushmi::detail::for_each_fn::Pull< In, Out >::done () inline
Definition at line 48 of file for_each.h.
References folly::pushmi::detail::PUSHMI_TEMPLATE(), folly::pushmi::detail::requires(), and folly::pushmi::set_done.
                 {
       // break circular reference
       pull = nullptr;
       ::folly::pushmi::set_done(static_cast<Out&>(*this));
     }
template<class In , class Out > template<class E > void folly::pushmi::detail::for_each_fn::Pull< In, Out >::error (E && e) inline
Definition at line 43 of file for_each.h.
References folly::pushmi::set_error.
                       {
       // break circular reference
       pull = nullptr;
       ::folly::pushmi::set_error(static_cast<Out&>(*this), (E &&) e);
     }
template<class In , class Out > requires Receiver<Up>&& ReceiveValue<Up, std::ptrdiff_t> void folly::pushmi::detail::for_each_fn::Pull< In, Out >::starting (Up up) inline
Definition at line 55 of file for_each.h.
References folly::gen::move, folly::pushmi::detail::PUSHMI_TEMPLATE(), folly::pushmi::detail::requires(), and folly::pushmi::set_value.
{
       pull = [up = std::move(up)](std::ptrdiff_t requested) mutable {
         ::folly::pushmi::set_value(up, requested);
       };
       pull(1);
     }
template<class In , class Out > requires ReceiveValue<Up> void folly::pushmi::detail::for_each_fn::Pull< In, Out >::starting (Up) inline
Definition at line 63 of file for_each.h.
 {}
template<class In , class Out > template<class... VN> void folly::pushmi::detail::for_each_fn::Pull< In, Out >::value (VN &&... vn) inline
Definition at line 38 of file for_each.h.
References folly::pushmi::set_value.
{
       ::folly::pushmi::set_value(static_cast<Out&>(*this), (VN &&) vn...);
       pull(1);
     }
Member Data Documentation
template<class In , class Out > std::function<void(std::ptrdiff_t)> folly::pushmi::detail::for_each_fn::Pull< In, Out >::pull
Definition at line 36 of file for_each.h.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/pushmi/o/for_each.h