proxygen: folly::MicroSpinLock Struct Reference
folly::MicroSpinLock Struct Reference
#include <MicroSpinLock.h>
Public Types
enum { FREE = 0, LOCKED = 1 }
Public Member Functions
void init () noexcept
bool try_lock () noexcept
void lock () noexcept
void unlock () noexcept
Public Attributes
uint8_t lock_
Private Member Functions
std::atomic< uint8_t > * payload () noexcept
bool cas (uint8_t compare, uint8_t newVal) noexcept
Detailed Description
Definition at line 65 of file MicroSpinLock.h.
Member Enumeration Documentation
anonymous enum
Enumerator
FREE
LOCKED
Definition at line 66 of file MicroSpinLock.h.
 { FREE = 0, LOCKED = 1 };
Member Function Documentation
bool folly::MicroSpinLock::cas (uint8_t compare, uint8_t newVal) inline private noexcept
Definition at line 100 of file MicroSpinLock.h.
References payload(), and value.
Referenced by try_lock().
{
     return std::atomic_compare_exchange_strong_explicit(
         payload(),
         &compare,
         newVal,
         std::memory_order_acquire,
         std::memory_order_relaxed);
   }
void folly::MicroSpinLock::init () inline noexcept
Definition at line 72 of file MicroSpinLock.h.
References FREE, and payload().
Referenced by folly::detail::SkipListNode< T >::SkipListNode(), and folly::SpinLock::SpinLock().
{
     payload()->store(FREE);
   }
void folly::MicroSpinLock::lock () inline noexcept
Definition at line 80 of file MicroSpinLock.h.
References deadlock::load(), LOCKED, payload(), try_lock(), and folly::detail::Sleeper::wait().
Referenced by folly::SpinLock::lock(), folly::futures::detail::SpinLock::SpinLock(), and folly::SpinLockGuardImpl< LOCK >::SpinLockGuardImpl().
{
     detail::Sleeper sleeper;
     while (!try_lock()) {
       do {
         sleeper.wait();
       } while (payload()->load(std::memory_order_relaxed) == LOCKED);
     }
     assert(payload()->load() == LOCKED);
   }
std::atomic<uint8_t>* folly::MicroSpinLock::payload () inline private noexcept
Definition at line 96 of file MicroSpinLock.h.
References lock_.
Referenced by cas(), init(), lock(), and unlock().
{
     return reinterpret_cast<std::atomic<uint8_t>*>(&this->lock_);
   }
bool folly::MicroSpinLock::try_lock () inline noexcept
Definition at line 76 of file MicroSpinLock.h.
References cas(), FREE, and LOCKED.
Referenced by lock(), and folly::SpinLock::try_lock().
{
     return cas(FREE, LOCKED);
   }
void folly::MicroSpinLock::unlock () inline noexcept
Definition at line 90 of file MicroSpinLock.h.
References FREE, deadlock::load(), LOCKED, and payload().
Referenced by folly::futures::detail::SpinLock::SpinLock(), folly::SpinLock::unlock(), and folly::SpinLockGuardImpl< LOCK >::~SpinLockGuardImpl().
{
     assert(payload()->load() == LOCKED);
     payload()->store(FREE, std::memory_order_release);
   }
Member Data Documentation
uint8_t folly::MicroSpinLock::lock_
Definition at line 68 of file MicroSpinLock.h.
Referenced by payload().
The documentation for this struct was generated from the following file:
proxygen/folly/folly/synchronization/MicroSpinLock.h