proxygen: countdown< R > Struct Template Reference
countdown< R > Struct Template Reference
Public Types
using properties = mi::properties_t< decltype(R{}())>
Public Member Functions
countdown (std::atomic< int > &c)
template<class ExecutorRef >
void value (ExecutorRef exec)
template<class E >
void error (E e)
void done ()
requires mi::Invocable< decltype(mi::set_value), Up, std::ptrdiff_t > void starting (Up up)
requires mi::True &&mi::Invocable< decltype(mi::set_value), Up > void starting (Up up) volatile
Public Attributes
std::atomic< int > * counter
Detailed Description
template<class R>
struct countdown< R >
Definition at line 40 of file PushmiBenchmarks.cpp.
Member Typedef Documentation
template<class R > using countdown< R >::properties = mi::properties_t<decltype(R{}())>
Definition at line 43 of file PushmiBenchmarks.cpp.
Constructor & Destructor Documentation
template<class R > countdown< R >::countdown (std::atomic< int > & c) inline explicit
Definition at line 41 of file PushmiBenchmarks.cpp.
 : counter(&c) {}
Member Function Documentation
template<class R > void countdown< R >::done () inline
Definition at line 53 of file PushmiBenchmarks.cpp.
References folly::pushmi::PUSHMI_TEMPLATE(), folly::pushmi::requires(), and folly::pushmi::set_value.
 {}
template<class R > template<class E > void countdown< R >::error (E e) inline
Definition at line 50 of file PushmiBenchmarks.cpp.
                   {
     std::abort();
   }
template<class R > requires mi::Invocable< decltype(mi::set_value), Up, std::ptrdiff_t> void countdown< R >::starting (Up up) inline
Definition at line 58 of file PushmiBenchmarks.cpp.
References folly::pushmi::PUSHMI_TEMPLATE(), folly::pushmi::requires(), and folly::pushmi::set_value.
{
     mi::set_value(up, 1);
   }
template<class R > requires mi::True&& mi:: Invocable<decltype(mi::set_value), Up> void countdown< R >::starting (Up up) volatile inline
Definition at line 63 of file PushmiBenchmarks.cpp.
References folly::pushmi::set_value.
{
     mi::set_value(up);
   }
template<class R > template<class ExecutorRef > void countdown< R >::value (ExecutorRef exec)
Definition at line 70 of file PushmiBenchmarks.cpp.
References submit.
{
   if (--*counter >= 0) {
     exec | op::submit(R{}(*this));
   }
 }
Member Data Documentation
template<class R > std::atomic<int>* countdown< R >::counter
Definition at line 45 of file PushmiBenchmarks.cpp.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/pushmi/benchmarks/PushmiBenchmarks.cpp