proxygen: folly::IOBufHash Struct Reference
folly::IOBufHash Struct Reference
#include <IOBuf.h>
Public Member Functions
size_t operator() (const IOBuf &buf) const noexcept
size_t operator() (const std::unique_ptr< IOBuf > &buf) const noexcept
size_t operator() (const IOBuf *buf) const noexcept
Detailed Description
Hasher for IOBuf objects. Hashes the entire chain using SpookyHashV2.
Definition at line 1510 of file IOBuf.h.
Member Function Documentation
size_t folly::IOBufHash::operator() (const IOBuf & buf) const noexcept
Definition at line 1090 of file IOBuf.cpp.
References b, folly::hash::SpookyHashV2::Final(), folly::hash::SpookyHashV2::Init(), folly::io::detail::CursorBase< Derived, BufType >::peekBytes(), folly::io::detail::CursorBase< Derived, BufType >::skip(), uint64_t, and folly::hash::SpookyHashV2::Update().
{
   folly::hash::SpookyHashV2 hasher;
   hasher.Init(0, 0);
   io::Cursor cursor(&buf);
   for (;;) {
     auto b = cursor.peekBytes();
     if (b.empty()) {
       break;
     }
     hasher.Update(b.data(), b.size());
     cursor.skip(b.size());
   }
   uint64_t h1;
   uint64_t h2;
   hasher.Final(&h1, &h2);
   return static_cast<std::size_t>(h1);
 }
size_t folly::IOBufHash::operator() (const std::unique_ptr< IOBuf > & buf) const inline noexcept
Definition at line 1512 of file IOBuf.h.
{
     return operator()(buf.get());
   }
size_t folly::IOBufHash::operator() (const IOBuf * buf) const inline noexcept
Definition at line 1515 of file IOBuf.h.
{
     return buf ? (*this)(*buf) : 0;
   }
The documentation for this struct was generated from the following files:
proxygen/folly/folly/io/IOBuf.h
proxygen/folly/folly/io/IOBuf.cpp