proxygen: folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum > Struct Template Reference
folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum > Struct Template Reference
#include <BitVectorCoding.h>
Classes
struct Layout
Public Types
typedef BitVectorCompressedList CompressedList
typedef MutableBitVectorCompressedList MutableCompressedList
typedef Value ValueType
typedef SkipValue SkipValueType
Public Member Functions
BitVectorEncoder (const MutableCompressedList &result)
BitVectorEncoder (size_t size, ValueType upperBound)
void add (ValueType value)
const MutableCompressedList & finish () const
Static Public Member Functions
template<class RandomAccessIterator >
static MutableCompressedList encode (RandomAccessIterator begin, RandomAccessIterator end)
Static Public Attributes
static constexpr size_t skipQuantum = kSkipQuantum
static constexpr size_t forwardQuantum = kForwardQuantum
Private Attributes
uint8_t *const bits_ = nullptr
uint8_t *const skipPointers_ = nullptr
uint8_t *const forwardPointers_ = nullptr
ValueType lastValue_ = -1
size_t size_ = 0
size_t skipPointersSize_ = 0
MutableCompressedList result_
Detailed Description
template<class Value, class SkipValue, size_t kSkipQuantum = 0, size_t kForwardQuantum = 0>
struct folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >
Definition at line 79 of file BitVectorCoding.h.
Member Typedef Documentation
template<class Value , class SkipValue , size_t kSkipQuantum = 0, size_t kForwardQuantum = 0> typedef BitVectorCompressedList folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::CompressedList
Definition at line 82 of file BitVectorCoding.h.
template<class Value , class SkipValue , size_t kSkipQuantum = 0, size_t kForwardQuantum = 0> typedef MutableBitVectorCompressedList folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::MutableCompressedList
Definition at line 85 of file BitVectorCoding.h.
template<class Value , class SkipValue , size_t kSkipQuantum = 0, size_t kForwardQuantum = 0> typedef SkipValue folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::SkipValueType
Definition at line 88 of file BitVectorCoding.h.
template<class Value , class SkipValue , size_t kSkipQuantum = 0, size_t kForwardQuantum = 0> typedef Value folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::ValueType
Definition at line 87 of file BitVectorCoding.h.
Constructor & Destructor Documentation
template<class Value , class SkipValue , size_t kSkipQuantum = 0, size_t kForwardQuantum = 0> folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::BitVectorEncoder (const MutableCompressedList & result) inline explicit
Definition at line 108 of file BitVectorCoding.h.
References folly::compression::BitVectorCompressedListBase< Pointer >::data, folly::Range< Iter >::data(), and folly::Range< Iter >::size().
       : bits_(result.bits),
         skipPointers_(result.skipPointers),
         forwardPointers_(result.forwardPointers),
         result_(result) {
     memset(result.data.data(), 0, result.data.size());
   }
template<class Value , class SkipValue , size_t kSkipQuantum = 0, size_t kForwardQuantum = 0> folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::BitVectorEncoder (size_t size, ValueType upperBound) inline
Definition at line 116 of file BitVectorCoding.h.
       : BitVectorEncoder(
             Layout::fromUpperBoundAndSize(upperBound, size).allocList()) {}
Member Function Documentation
template<class Value , class SkipValue , size_t kSkipQuantum = 0, size_t kForwardQuantum = 0> void folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::add (ValueType value) inline
Definition at line 120 of file BitVectorCoding.h.
References max, cpp.gmock_class::set, uint64_t, and folly::value().
Referenced by folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::encode().
{
     CHECK_LT(value, std::numeric_limits<ValueType>::max());
     // Also works when lastValue_ == -1.
     CHECK_GT(value + 1, lastValue_ + 1)
         << "BitVectorCoding only supports stricly monotone lists";
     auto block = bits_ + (value / 64) * sizeof(uint64_t);
     size_t inner = value % 64;
     folly::Bits<folly::Unaligned<uint64_t>>::set(
         reinterpret_cast<folly::Unaligned<uint64_t>*>(block), inner);
     if (skipQuantum != 0) {
       size_t nextSkipPointerSize = value / skipQuantum;
       while (skipPointersSize_ < nextSkipPointerSize) {
         auto pos = skipPointersSize_++;
         folly::storeUnaligned<SkipValueType>(
             skipPointers_ + pos * sizeof(SkipValueType), size_);
       }
     }
     if (forwardQuantum != 0) {
       if (size_ != 0 && (size_ % forwardQuantum == 0)) {
         const auto pos = size_ / forwardQuantum - 1;
         folly::storeUnaligned<SkipValueType>(
             forwardPointers_ + pos * sizeof(SkipValueType), value);
       }
     }
     lastValue_ = value;
     ++size_;
   }
template<class Value , class SkipValue , size_t kSkipQuantum = 0, size_t kForwardQuantum = 0> template<class RandomAccessIterator > static MutableCompressedList folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::encode (RandomAccessIterator begin, RandomAccessIterator end) inline static
Definition at line 95 of file BitVectorCoding.h.
References folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::add(), folly::test::begin(), folly::test::end(), and folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::finish().
Referenced by BENCHMARK().
{
     if (begin == end) {
       return MutableCompressedList();
     }
     BitVectorEncoder encoder(size_t(end - begin), *(end - 1));
     for (; begin != end; ++begin) {
       encoder.add(*begin);
     }
     return encoder.finish();
   }
template<class Value , class SkipValue , size_t kSkipQuantum = 0, size_t kForwardQuantum = 0> const MutableCompressedList& folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::finish () const inline
Definition at line 152 of file BitVectorCoding.h.
Referenced by folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::encode().
{
     CHECK_EQ(size_, result_.size);
     // TODO(ott): Relax this assumption.
     CHECK_EQ(result_.upperBound, lastValue_);
     return result_;
   }
Member Data Documentation
template<class Value , class SkipValue , size_t kSkipQuantum = 0, size_t kForwardQuantum = 0> uint8_t* const folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::bits_ = nullptr private
Definition at line 160 of file BitVectorCoding.h.
template<class Value , class SkipValue , size_t kSkipQuantum = 0, size_t kForwardQuantum = 0> uint8_t* const folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::forwardPointers_ = nullptr private
Definition at line 162 of file BitVectorCoding.h.
template<class Value , class SkipValue , size_t kSkipQuantum = 0, size_t kForwardQuantum = 0> constexpr size_t folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::forwardQuantum = kForwardQuantum static
Definition at line 92 of file BitVectorCoding.h.
template<class Value , class SkipValue , size_t kSkipQuantum = 0, size_t kForwardQuantum = 0> ValueType folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::lastValue_ = -1 private
Definition at line 164 of file BitVectorCoding.h.
template<class Value , class SkipValue , size_t kSkipQuantum = 0, size_t kForwardQuantum = 0> MutableCompressedList folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::result_ private
Definition at line 168 of file BitVectorCoding.h.
template<class Value , class SkipValue , size_t kSkipQuantum = 0, size_t kForwardQuantum = 0> size_t folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::size_ = 0 private
Definition at line 165 of file BitVectorCoding.h.
template<class Value , class SkipValue , size_t kSkipQuantum = 0, size_t kForwardQuantum = 0> uint8_t* const folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::skipPointers_ = nullptr private
Definition at line 161 of file BitVectorCoding.h.
template<class Value , class SkipValue , size_t kSkipQuantum = 0, size_t kForwardQuantum = 0> size_t folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::skipPointersSize_ = 0 private
Definition at line 166 of file BitVectorCoding.h.
template<class Value , class SkipValue , size_t kSkipQuantum = 0, size_t kForwardQuantum = 0> constexpr size_t folly::compression::BitVectorEncoder< Value, SkipValue, kSkipQuantum, kForwardQuantum >::skipQuantum = kSkipQuantum static
Definition at line 91 of file BitVectorCoding.h.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/BitVectorCoding.h