proxygen: EqTraits Struct Reference
EqTraits Struct Reference
Public Member Functions
bool operator() (char *a, char *b)
bool operator() (char *a, const char &b)
bool operator() (char *a, const StringPiece b)
bool operator() (const char *a, const char *b)
bool operator() (const char *a, const char &b)
bool operator() (const char *a, const StringPiece b)
Detailed Description
Definition at line 333 of file AtomicHashArrayTest.cpp.
Member Function Documentation
bool EqTraits::operator() (const char * a, const char * b) inline
Definition at line 121 of file AtomicHashMapTest.cpp.
References legalKey().
{
     return legalKey(a) && (strcmp(a, b) == 0);
   }
bool EqTraits::operator() (const char * a, const char & b) inline
Definition at line 124 of file AtomicHashMapTest.cpp.
References legalKey().
{
     return legalKey(a) && (a[0] != '\0') && (a[0] == b);
   }
bool EqTraits::operator() (const char * a, const StringPiece b) inline
Definition at line 127 of file AtomicHashMapTest.cpp.
References legalKey().
{
     return legalKey(a) && (strlen(a) == b.size()) &&
         (strcmp(a, b.begin()) == 0);
   }
bool EqTraits::operator() (char * a, char * b) inline
Definition at line 334 of file AtomicHashArrayTest.cpp.
References legalKey().
{
     return legalKey(a) && (strcmp(a, b) == 0);
   }
bool EqTraits::operator() (char * a, const char & b) inline
Definition at line 337 of file AtomicHashArrayTest.cpp.
References legalKey().
{
     return legalKey(a) && (a[0] != '\0') && (a[0] == b);
   }
bool EqTraits::operator() (char * a, const StringPiece b) inline
Definition at line 340 of file AtomicHashArrayTest.cpp.
References folly::Range< Iter >::begin(), legalKey(), and folly::Range< Iter >::size().
{
     return legalKey(a) && (strlen(a) == b.size()) &&
         (strncmp(a, b.begin(), b.size()) == 0);
   }
The documentation for this struct was generated from the following files:
proxygen/folly/folly/test/AtomicHashArrayTest.cpp
proxygen/folly/folly/test/AtomicHashMapTest.cpp