proxygen: AtomicBatchDispatcherTesting::Job Struct Reference
AtomicBatchDispatcherTesting::Job Struct Reference
Public Member Functions
void preprocess (FiberManager &executor, bool die)
Job (AtomicBatchDispatcher< ValueT, ResultT >::Token &&t, ValueT i)
Job (Job &&)=default
Job & operator= (Job &&)=default
Public Attributes
AtomicBatchDispatcher< ValueT, ResultT >::Token token
ValueT input
Detailed Description
Definition at line 1790 of file FibersTest.cpp.
Constructor & Destructor Documentation
AtomicBatchDispatcherTesting::Job::Job (AtomicBatchDispatcher< ValueT, ResultT >::Token && t, ValueT i) inline
Definition at line 1807 of file FibersTest.cpp.
       : token(std::move(t)), input(i) {}
AtomicBatchDispatcherTesting::Job::Job (Job &&) default
Member Function Documentation
Job& AtomicBatchDispatcherTesting::Job::operator= (Job &&) default
void AtomicBatchDispatcherTesting::Job::preprocess (FiberManager & executor, bool die) inline
Definition at line 1794 of file FibersTest.cpp.
References folly::Random::rand32(), start, and folly::fibers::FiberManager::yield().
Referenced by AtomicBatchDispatcherTesting::dispatchJobs().
{
     // Yield for a random duration [0, 10] ms to simulate I/O in preprocessing
     clock_t msecToDoIO = folly::Random::rand32() % 10;
     double start = (1000.0 * clock()) / CLOCKS_PER_SEC;
     double endAfter = start + msecToDoIO;
     while ((1000.0 * clock()) / CLOCKS_PER_SEC < endAfter) {
       executor.yield();
     }
     if (die) {
       throw std::logic_error("Simulating preprocessing failure");
     }
   }
Member Data Documentation
ValueT AtomicBatchDispatcherTesting::Job::input
Definition at line 1792 of file FibersTest.cpp.
Referenced by AtomicBatchDispatcherTesting::dispatchJobs().
AtomicBatchDispatcher<ValueT, ResultT>::Token AtomicBatchDispatcherTesting::Job::token
Definition at line 1791 of file FibersTest.cpp.
Referenced by AtomicBatchDispatcherTesting::dispatchJobs().
The documentation for this struct was generated from the following file:
proxygen/folly/folly/fibers/test/FibersTest.cpp