proxygen: folly::coro::detail::BlockingWaitPromiseBase::FinalAwaiter Struct Reference
folly::coro::detail::BlockingWaitPromiseBase::FinalAwaiter Struct Reference
Public Member Functions
bool await_ready () noexcept
template<typename Promise >
void await_suspend (std::experimental::coroutine_handle< Promise > coro) noexcept
void await_resume () noexcept
Detailed Description
Definition at line 38 of file BlockingWait.h.
Member Function Documentation
bool folly::coro::detail::BlockingWaitPromiseBase::FinalAwaiter::await_ready () inline noexcept
Definition at line 39 of file BlockingWait.h.
{
       return false;
     }
void folly::coro::detail::BlockingWaitPromiseBase::FinalAwaiter::await_resume () inline noexcept
Definition at line 48 of file BlockingWait.h.
References folly::coro::detail::BlockingWaitPromiseBase::BlockingWaitPromiseBase(), and folly::pushmi::__adl::noexcept().
 {}
template<typename Promise > void folly::coro::detail::BlockingWaitPromiseBase::FinalAwaiter::await_suspend (std::experimental::coroutine_handle< Promise > coro) inline noexcept
Definition at line 43 of file BlockingWait.h.
References folly::coro::detail::BlockingWaitPromiseBase::baton_, and folly::fibers::Baton::post().
{
       BlockingWaitPromiseBase& promise = coro.promise();
       promise.baton_.post();
     }
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/coro/BlockingWait.h