proxygen: folly::exception_wrapper::Buffer Struct Reference
folly::exception_wrapper::Buffer Struct Reference
Public Types
using Storage = _t< std::aligned_storage< 2 *sizeof(void *), alignof(std::exception)>>
Public Member Functions
Buffer ()
template<class Ex , typename... As>
Buffer (in_place_type_t< Ex >, As &&...as_)
template<class Ex >
Ex & as () noexcept
template<class Ex >
Ex const & as () const noexcept
Public Attributes
Storage buff_
Detailed Description
Definition at line 222 of file ExceptionWrapper.h.
Member Typedef Documentation
using folly::exception_wrapper::Buffer::Storage = _t<std::aligned_storage<2 * sizeof(void*), alignof(std::exception)>>
Definition at line 224 of file ExceptionWrapper.h.
Constructor & Destructor Documentation
folly::exception_wrapper::Buffer::Buffer () inline
Definition at line 227 of file ExceptionWrapper.h.
References folly::gen::as(), and folly::pushmi::__adl::noexcept().
 : buff_{} {}
template<class Ex , typename... As> folly::exception_wrapper::Buffer::Buffer (in_place_type_t< Ex > , As &&... as_) inline
Definition at line 72 of file ExceptionWrapper-inl.h.
References folly::exception_wrapper::buff_.
{
   ::new (static_cast<void*>(&buff_)) Ex(std::forward<As>(as_)...);
 }
Member Function Documentation
template<class Ex > Ex & folly::exception_wrapper::Buffer::as () inline noexcept
Definition at line 77 of file ExceptionWrapper-inl.h.
References folly::exception_wrapper::buff_.
Referenced by folly::exception_wrapper::InPlace< Ex >::copy_(), folly::exception_wrapper::InPlace< Ex >::delete_(), folly::exception_wrapper::InPlace< Ex >::get_exception_(), folly::exception_wrapper::InPlace< Ex >::move_(), and folly::exception_wrapper::InPlace< Ex >::throw_().
{
   return *static_cast<Ex*>(static_cast<void*>(&buff_));
 }
template<class Ex > Ex const & folly::exception_wrapper::Buffer::as () const inline noexcept
Definition at line 81 of file ExceptionWrapper-inl.h.
References folly::exception_wrapper::buff_, and upload::const.
{
   return *static_cast<Ex const*>(static_cast<void const*>(&buff_));
 }
Member Data Documentation
Storage folly::exception_wrapper::Buffer::buff_
Definition at line 225 of file ExceptionWrapper.h.
The documentation for this struct was generated from the following files:
proxygen/folly/folly/ExceptionWrapper.h
proxygen/folly/folly/ExceptionWrapper-inl.h