proxygen: Alloc< T > Struct Template Reference
Alloc< T > Struct Template Reference
Public Types
typedef std::allocator< T >::pointer pointer
typedef std::allocator< T >::const_pointer const_pointer
typedef std::allocator< T >::difference_type difference_type
typedef std::allocator< T >::size_type size_type
typedef std::allocator< T >::value_type value_type
typedef isPropCopy< T > propagate_on_container_copy_assignment
typedef isPropMove< T > propagate_on_container_move_assignment
typedef isPropSwap< T > propagate_on_container_swap
Public Member Functions
Alloc (int i=8)
Alloc (const Alloc &o)
Alloc (Alloc &&o) noexcept
Alloc & operator= (const Alloc &)=default
Alloc & operator= (Alloc &&) noexcept=default
bool operator== (const Alloc &o) const
bool operator!= (const Alloc &o) const
pointer allocate (size_type n)
void deallocate (pointer p, size_type n)
template<class U , class... Args>
void construct (U *p, Args &&...args)
template<class U >
void destroy (U *p)
Alloc select_on_container_copy_construction () const
Public Attributes
std::allocator< T > a
int id
Additional Inherited Members
Static Public Member Functions inherited from Ticker
static void Tick (const std::string &s)
Static Public Attributes inherited from AllocTracker
static int Constructed = 0
static int Destroyed = 0
static map< void *, size_t > Allocated
static map< void *, int > Owner
Static Public Attributes inherited from Ticker
static int CountTicks = 0
static int TicksLeft = -1
Detailed Description
template<class T>
struct Alloc< T >
Definition at line 650 of file StlVectorTest.cpp.
Member Typedef Documentation
template<class T> typedef std::allocator<T>::const_pointer Alloc< T >::const_pointer
Definition at line 652 of file StlVectorTest.cpp.
template<class T> typedef std::allocator<T>::difference_type Alloc< T >::difference_type
Definition at line 653 of file StlVectorTest.cpp.
template<class T> typedef std::allocator<T>::pointer Alloc< T >::pointer
Definition at line 651 of file StlVectorTest.cpp.
template<class T> typedef isPropCopy<T> Alloc< T >::propagate_on_container_copy_assignment
Definition at line 736 of file StlVectorTest.cpp.
template<class T> typedef isPropMove<T> Alloc< T >::propagate_on_container_move_assignment
Definition at line 737 of file StlVectorTest.cpp.
template<class T> typedef isPropSwap<T> Alloc< T >::propagate_on_container_swap
Definition at line 738 of file StlVectorTest.cpp.
template<class T> typedef std::allocator<T>::size_type Alloc< T >::size_type
Definition at line 654 of file StlVectorTest.cpp.
template<class T> typedef std::allocator<T>::value_type Alloc< T >::value_type
Definition at line 655 of file StlVectorTest.cpp.
Constructor & Destructor Documentation
template<class T> Alloc< T >::Alloc (int i = 8) inline explicit
Definition at line 662 of file StlVectorTest.cpp.
 : a(), id(i) {}
template<class T> Alloc< T >::Alloc (const Alloc< T > & o) inline
Definition at line 663 of file StlVectorTest.cpp.
 : a(o.a), id(o.id) {}
template<class T> Alloc< T >::Alloc (Alloc< T > && o) inline noexcept
Definition at line 664 of file StlVectorTest.cpp.
References folly::pushmi::__adl::noexcept(), and D0< b >::operator=().
 : a(move(o.a)), id(o.id) {}
Member Function Documentation
template<class T> pointer Alloc< T >::allocate (size_type n) inline
Definition at line 677 of file StlVectorTest.cpp.
Referenced by MemoryLeakCheckerAllocator< Alloc >::allocate().
{
     if (n == 0) {
       cerr << "called allocate(0)" << endl;
       throw runtime_error("allocate fail");
     }
     Tick("allocate");
     auto p = a.allocate(n);
     Allocated[p] = n;
     Owner[p] = id;
     return p;
   }
template<class T> template<class U , class... Args> void Alloc< T >::construct (U * p, Args &&... args) inline
Definition at line 716 of file StlVectorTest.cpp.
Referenced by MemoryLeakCheckerAllocator< Alloc >::construct().
{
     Tick("construct");
     a.construct(p, std::forward<Args>(args)...);
     Constructed++;
   }
template<class T> void Alloc< T >::deallocate (pointer p, size_type n) inline
Definition at line 689 of file StlVectorTest.cpp.
References testing::Args(), and FAIL.
Referenced by MemoryLeakCheckerAllocator< Alloc >::deallocate().
{
     if (p == nullptr) {
       cerr << "deallocate(nullptr, " << n << ")" << endl;
       FAIL() << "deallocate failed";
     }
     if (Allocated[p] != n) {
       cerr << "deallocate(" << p << ", " << n << ") invalid: ";
       if (Allocated[p] == 0) {
         cerr << "never allocated";
       } else if (Allocated[p] == size_t(-1)) {
         cerr << "already deallocated";
       } else {
         cerr << "wrong number (want " << Allocated[p] << ")";
       }
       cerr << endl;
       FAIL() << "deallocate failed";
     }
     if (Owner[p] != id) {
       cerr << "deallocate(" << p << "), where pointer is owned by " << Owner[p]
            << ", instead of self - " << id << endl;
       FAIL() << "deallocate failed";
     }
     Allocated[p] = -1;
     a.deallocate(p, n);
   }
template<class T> template<class U > void Alloc< T >::destroy (U * p) inline
Definition at line 723 of file StlVectorTest.cpp.
Referenced by MemoryLeakCheckerAllocator< Alloc >::destroy().
                      {
     Destroyed++;
     a.destroy(p);
   }
template<class T> bool Alloc< T >::operator!= (const Alloc< T > & o) const inline
Definition at line 670 of file StlVectorTest.cpp.
{
     return !(*this == o);
   }
template<class T> Alloc& Alloc< T >::operator= (const Alloc< T > &) default
template<class T> Alloc& Alloc< T >::operator= (Alloc< T > &&) default noexcept
template<class T> bool Alloc< T >::operator== (const Alloc< T > & o) const inline
Definition at line 667 of file StlVectorTest.cpp.
References Alloc< T >::a, and Alloc< T >::id.
{
     return a == o.a && id == o.id;
   }
template<class T> Alloc Alloc< T >::select_on_container_copy_construction () const inline
Definition at line 731 of file StlVectorTest.cpp.
{
     Tick("select allocator for copy");
     return Alloc(id + 1);
   }
Member Data Documentation
template<class T> std::allocator<T> Alloc< T >::a
Definition at line 660 of file StlVectorTest.cpp.
Referenced by Alloc< T >::operator==().
template<class T> int Alloc< T >::id
Definition at line 661 of file StlVectorTest.cpp.
Referenced by convertToInt(), and Alloc< T >::operator==().
The documentation for this struct was generated from the following file:
proxygen/folly/folly/test/stl_tests/StlVectorTest.cpp