proxygen: folly::detail::fixedstring::Helper Struct Reference
folly::detail::fixedstring::Helper Struct Reference
#include <FixedString.h>
Static Public Member Functions
template<class Char , class Left , class Right , std::size_t... Is>
static constexpr BasicFixedString< Char, sizeof...(Is)> concat_ (const Left &left, std::size_t left_count, const Right &right, std::size_t right_count, folly::index_sequence< Is... > is) noexcept
template<class Char , class Left , class Right , std::size_t... Is>
static constexpr BasicFixedString< Char, sizeof...(Is)> replace_ (const Left &left, std::size_t left_size, std::size_t left_pos, std::size_t left_count, const Right &right, std::size_t right_pos, std::size_t right_count, folly::index_sequence< Is... > is) noexcept
template<class Char , std::size_t N>
static constexpr const Char(& data_ (const BasicFixedString< Char, N > &that) noexcept)[N+1u]
Detailed Description
Definition at line 267 of file FixedString.h.
Member Function Documentation
template<class Char , class Left , class Right , std::size_t... Is> static constexpr BasicFixedString<Char, sizeof...(Is)> folly::detail::fixedstring::Helper::concat_ (const Left & left, std::size_t left_count, const Right & right, std::size_t right_count, folly::index_sequence< Is... > is) inline static noexcept
Definition at line 269 of file FixedString.h.
References testing::gmock_generated_actions_test::Char().
{
     return {left, left_count, right, right_count, is};
   }
template<class Char , std::size_t N> static constexpr const Char(& folly::detail::fixedstring::Helper::data_ (const BasicFixedString< Char, N > & that))[N+1u] inline static
Definition at line 300 of file FixedString.h.
Referenced by folly::operator+(), folly::operator<(), and folly::operator==().
{
     return that.data_;
   }
template<class Char , class Left , class Right , std::size_t... Is> static constexpr BasicFixedString<Char, sizeof...(Is)> folly::detail::fixedstring::Helper::replace_ (const Left & left, std::size_t left_size, std::size_t left_pos, std::size_t left_count, const Right & right, std::size_t right_pos, std::size_t right_count, folly::index_sequence< Is... > is) inline static noexcept
Definition at line 279 of file FixedString.h.
References testing::gmock_generated_actions_test::Char().
{
     return {left,
             left_size,
             left_pos,
             left_count,
             right,
             right_pos,
             right_count,
             is};
   }
The documentation for this struct was generated from the following file:
proxygen/folly/folly/FixedString.h