proxygen: folly::DynamicConverter< C, typename std::enable_if< dynamicconverter_detail::is_container< C >::value &&dynamicconverter_detail::is_associative< C >::value >::type > Struct Template Reference
folly::DynamicConverter< C, typename std::enable_if< dynamicconverter_detail::is_container< C >::value &&dynamicconverter_detail::is_associative< C >::value >::type > Struct Template Reference
#include <DynamicConverter.h>
Static Public Member Functions
static C convert (const dynamic &d)
Detailed Description
template<typename C>
struct folly::DynamicConverter< C, typename std::enable_if< dynamicconverter_detail::is_container< C >::value &&dynamicconverter_detail::is_associative< C >::value >::type >
Definition at line 281 of file DynamicConverter.h.
Member Function Documentation
template<typename C > static C folly::DynamicConverter< C, typename std::enable_if< dynamicconverter_detail::is_container< C >::value &&dynamicconverter_detail::is_associative< C >::value >::type >::convert (const dynamic & d) inline static
Definition at line 286 of file DynamicConverter.h.
References folly::dynamic::begin(), C, folly::dynamic::end(), folly::dynamic::isArray(), folly::dynamic::isObject(), folly::dynamic::items(), and folly::dynamic::type().
{
     C ret; // avoid direct initialization due to unordered_map's constructor
            // causing memory corruption if the iterator throws an exception
     if (d.isArray()) {
       ret.insert(
           dynamicconverter_detail::conversionIterator<C>(d.begin()),
           dynamicconverter_detail::conversionIterator<C>(d.end()));
     } else if (d.isObject()) {
       ret.insert(
           dynamicconverter_detail::conversionIterator<C>(d.items().begin()),
           dynamicconverter_detail::conversionIterator<C>(d.items().end()));
     } else {
       throw TypeError("object or array", d.type());
     }
     return ret;
   }
The documentation for this struct was generated from the following file:
proxygen/folly/folly/DynamicConverter.h