proxygen: folly::ThreadCachedInt< IntT, Tag >::IntCache Struct Reference
folly::ThreadCachedInt< IntT, Tag >::IntCache Struct Reference
Public Member Functions
IntCache (ThreadCachedInt &parent)
void increment (IntT inc)
void flush () const
~IntCache ()
Public Attributes
ThreadCachedInt * parent_
std::atomic< IntT > val_
uint32_t numUpdates_
std::atomic< bool > reset_
Detailed Description
template<class IntT, class Tag = IntT>
struct folly::ThreadCachedInt< IntT, Tag >::IntCache
Definition at line 142 of file ThreadCachedInt.h.
Constructor & Destructor Documentation
template<class IntT, class Tag = IntT> folly::ThreadCachedInt< IntT, Tag >::IntCache::IntCache (ThreadCachedInt & parent) inline explicit
Definition at line 148 of file ThreadCachedInt.h.
         : parent_(&parent), val_(0), numUpdates_(0), reset_(false) {}
template<class IntT, class Tag = IntT> folly::ThreadCachedInt< IntT, Tag >::IntCache::~IntCache () inline
Definition at line 176 of file ThreadCachedInt.h.
References folly::ThreadCachedInt< IntT, Tag >::IntCache::flush().
                 {
       flush();
     }
Member Function Documentation
template<class IntT, class Tag = IntT> void folly::ThreadCachedInt< IntT, Tag >::IntCache::flush () const inline
Definition at line 170 of file ThreadCachedInt.h.
References folly::ThreadCachedInt< IntT, Tag >::target_.
Referenced by folly::ThreadCachedInt< IntT, Tag >::IntCache::increment(), and folly::ThreadCachedInt< IntT, Tag >::IntCache::~IntCache().
{
       parent_->target_.fetch_add(val_, std::memory_order_release);
       val_.store(0, std::memory_order_release);
       numUpdates_ = 0;
     }
template<class IntT, class Tag = IntT> void folly::ThreadCachedInt< IntT, Tag >::IntCache::increment (IntT inc) inline
Definition at line 151 of file ThreadCachedInt.h.
References folly::ThreadCachedInt< IntT, Tag >::cacheSize_, folly::ThreadCachedInt< IntT, Tag >::IntCache::flush(), LIKELY, folly::ThreadCachedInt< IntT, Tag >::IntCache::numUpdates_, and UNLIKELY.
{
       if (LIKELY(!reset_.load(std::memory_order_acquire))) {
         // This thread is the only writer to val_, so it's fine do do
         // a relaxed load and do the addition non-atomically.
         val_.store(
             val_.load(std::memory_order_relaxed) + inc,
             std::memory_order_release);
       } else {
         val_.store(inc, std::memory_order_relaxed);
         reset_.store(false, std::memory_order_release);
       }
       ++numUpdates_;
       if (UNLIKELY(
               numUpdates_ >
               parent_->cacheSize_.load(std::memory_order_acquire))) {
         flush();
       }
     }
Member Data Documentation
template<class IntT, class Tag = IntT> uint32_t folly::ThreadCachedInt< IntT, Tag >::IntCache::numUpdates_ mutable
Definition at line 145 of file ThreadCachedInt.h.
Referenced by folly::ThreadCachedInt< IntT, Tag >::IntCache::increment().
template<class IntT, class Tag = IntT> ThreadCachedInt* folly::ThreadCachedInt< IntT, Tag >::IntCache::parent_
Definition at line 143 of file ThreadCachedInt.h.
template<class IntT, class Tag = IntT> std::atomic<bool> folly::ThreadCachedInt< IntT, Tag >::IntCache::reset_
Definition at line 146 of file ThreadCachedInt.h.
template<class IntT, class Tag = IntT> std::atomic<IntT> folly::ThreadCachedInt< IntT, Tag >::IntCache::val_ mutable
Definition at line 144 of file ThreadCachedInt.h.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/ThreadCachedInt.h