proxygen: ScheduledEvent Struct Reference
ScheduledEvent Struct Reference
Public Member Functions
void perform (int fd)
Public Attributes
int milliseconds
uint16_t events
size_t length
ssize_t result
Detailed Description
Definition at line 112 of file EventBaseTest.cpp.
Member Function Documentation
void ScheduledEvent::perform (int fd) inline
Definition at line 118 of file EventBaseTest.cpp.
References readFromFD(), readUntilEmpty(), writeToFD(), and writeUntilFull().
Referenced by scheduleEvents().
{
     if (events & EventHandler::READ) {
       if (length == 0) {
         result = readUntilEmpty(fd);
       } else {
         result = readFromFD(fd, length);
       }
     }
     if (events & EventHandler::WRITE) {
       if (length == 0) {
         result = writeUntilFull(fd);
       } else {
         result = writeToFD(fd, length);
       }
     }
   }
Member Data Documentation
uint16_t ScheduledEvent::events
Definition at line 114 of file EventBaseTest.cpp.
size_t ScheduledEvent::length
Definition at line 115 of file EventBaseTest.cpp.
Referenced by TEST().
int ScheduledEvent::milliseconds
Definition at line 113 of file EventBaseTest.cpp.
Referenced by scheduleEvents().
ssize_t ScheduledEvent::result
Definition at line 116 of file EventBaseTest.cpp.
Referenced by TEST().
The documentation for this struct was generated from the following file:
proxygen/folly/folly/io/async/test/EventBaseTest.cpp