proxygen: folly::pushmi::detail::tap_fn::in_impl< AN > Struct Template Reference
folly::pushmi::detail::tap_fn::in_impl< AN > Struct Template Reference
Public Member Functions
requires Sender< In > auto operator() (In in)
Public Attributes
std::tuple< AN... > args_
Detailed Description
template<class... AN>
struct folly::pushmi::detail::tap_fn::in_impl< AN >
Definition at line 88 of file tap.h.
Member Function Documentation
template<class... AN> requires Sender<In> auto folly::pushmi::detail::tap_fn::in_impl< AN >::operator() (In in) inline
Definition at line 92 of file tap.h.
References folly::pushmi::detail::tap_fn::impl(), folly::gen::move, folly::pushmi::detail::PUSHMI_TEMPLATE(), and folly::pushmi::detail::requires().
{
       return tap_fn::impl(
           std::move(in),
           ::folly::pushmi::detail::receiver_from_fn<In>()(std::move(args_)));
     }
Member Data Documentation
template<class... AN> std::tuple<AN...> folly::pushmi::detail::tap_fn::in_impl< AN >::args_
Definition at line 89 of file tap.h.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/pushmi/o/tap.h