proxygen: folly::dynamic Struct Reference
folly::dynamic Struct Reference
#include <dynamic.h>
Classes
struct CompareOp
struct CompareOp< dynamic::ObjectImpl >
struct CompareOp< std::nullptr_t >
struct const_item_iterator
struct const_key_iterator
struct const_value_iterator
union Data
struct EmptyArrayTag
struct GetAddrImpl
struct GetAddrImpl< bool >
struct GetAddrImpl< double >
struct GetAddrImpl< dynamic::Array >
struct GetAddrImpl< dynamic::ObjectImpl >
struct GetAddrImpl< int64_t >
struct GetAddrImpl< std::nullptr_t >
struct GetAddrImpl< std::string >
struct item_iterator
struct IterableProxy
struct NumericTypeHelper
struct NumericTypeHelper< bool >
struct NumericTypeHelper< double >
struct NumericTypeHelper< float >
struct NumericTypeHelper< T, typename std::enable_if< std::is_integral< T >::value >::type >
struct ObjectImpl
struct ObjectMaker
struct PrintImpl
struct PrintImpl< dynamic::Array >
struct PrintImpl< dynamic::ObjectImpl >
struct PrintImpl< std::nullptr_t >
struct TypeInfo
struct TypeInfo< bool >
struct TypeInfo< double >
struct TypeInfo< dynamic::Array >
struct TypeInfo< dynamic::ObjectImpl >
struct TypeInfo< int64_t >
struct TypeInfo< std::nullptr_t >
struct TypeInfo< std::string >
struct value_iterator
struct VectorBoolConstRefFake
Public Types
enum Type {
NULLT, ARRAY, BOOL, DOUBLE,
INT64, OBJECT, STRING
}
typedef Array::iterator iterator
typedef Array::const_iterator const_iterator
typedef dynamic value_type
Public Member Functions
dynamic ()
dynamic (std::nullptr_t)
dynamic (StringPiece val)
dynamic (char const *val)
dynamic (std::string val)
dynamic (void(*)(EmptyArrayTag))
dynamic (ObjectMaker(*)())
dynamic (ObjectMaker const &)=delete
dynamic (ObjectMaker &&)
template<class T , class NumericType = typename NumericTypeHelper<T>::type>
dynamic (T t)
dynamic (std::vector< bool >::reference val)
dynamic (VectorBoolConstRefCtorType val)
template<class Iterator >
dynamic (Iterator first, Iterator last)
dynamic (dynamic const &)
dynamic (dynamic &&) noexcept
~dynamic () noexcept
bool operator== (dynamic const &o) const
bool operator< (dynamic const &o) const
dynamic & operator+= (dynamic const &)
dynamic & operator-= (dynamic const &)
dynamic & operator*= (dynamic const &)
dynamic & operator/= (dynamic const &)
dynamic & operator%= (dynamic const &)
dynamic & operator|= (dynamic const &)
dynamic & operator&= (dynamic const &)
dynamic & operator^= (dynamic const &)
dynamic & operator++ ()
dynamic & operator-- ()
dynamic & operator= (dynamic const &)
dynamic & operator= (dynamic &&) noexcept
bool isString () const
bool isObject () const
bool isBool () const
bool isNull () const
bool isArray () const
bool isDouble () const
bool isInt () const
bool isNumber () const
Type type () const
const char * typeName () const
std::string asString () const
double asDouble () const
int64_t asInt () const
bool asBool () const
const std::string & getString () const &
double getDouble () const &
int64_t getInt () const &
bool getBool () const &
std::string & getString ()&
double & getDouble ()&
int64_t & getInt ()&
bool & getBool ()&
std::string && getString ()&&
double getDouble ()&&
int64_t getInt ()&&
bool getBool ()&&
const char * data () const &
const char * data ()&&=delete
const char * c_str () const &
const char * c_str ()&&=delete
StringPiece stringPiece () const
bool empty () const
std::size_t size () const
const_iterator begin () const
const_iterator end () const
iterator begin ()
iterator end ()
IterableProxy< const_key_iterator > keys () const
IterableProxy< const_value_iterator > values () const
IterableProxy< const_item_iterator > items () const
IterableProxy< value_iterator > values ()
IterableProxy< item_iterator > items ()
template<typename K >
IfIsNonStringDynamicConvertible< K, const_item_iterator > find (K &&) const
template<typename K >
IfIsNonStringDynamicConvertible< K, item_iterator > find (K &&)
const_item_iterator find (StringPiece) const
item_iterator find (StringPiece)
template<typename K >
IfIsNonStringDynamicConvertible< K, std::size_t > count (K &&) const
std::size_t count (StringPiece) const
template<typename K >
IfIsNonStringDynamicConvertible< K, dynamic const & > at (K &&) const &
template<typename K >
IfIsNonStringDynamicConvertible< K, dynamic & > at (K &&)&
template<typename K >
IfIsNonStringDynamicConvertible< K, dynamic && > at (K &&)&&
dynamic const & at (StringPiece) const &
dynamic & at (StringPiece)&
dynamic && at (StringPiece)&&
const dynamic * get_ptr (json_pointer const &) const &
dynamic * get_ptr (json_pointer const &)&
const dynamic * get_ptr (json_pointer const &) const &&=delete
dynamic * get_ptr (json_pointer const &)&&=delete
template<typename K >
IfIsNonStringDynamicConvertible< K, const dynamic * > get_ptr (K &&) const &
template<typename K >
IfIsNonStringDynamicConvertible< K, dynamic * > get_ptr (K &&)&
template<typename K >
IfIsNonStringDynamicConvertible< K, dynamic * > get_ptr (K &&)&&=delete
const dynamic * get_ptr (StringPiece) const &
dynamic * get_ptr (StringPiece)&
dynamic * get_ptr (StringPiece)&&=delete
template<typename K >
IfIsNonStringDynamicConvertible< K, dynamic & > operator[] (K &&)&
template<typename K >
IfIsNonStringDynamicConvertible< K, dynamic const & > operator[] (K &&) const &
template<typename K >
IfIsNonStringDynamicConvertible< K, dynamic && > operator[] (K &&)&&
dynamic & operator[] (StringPiece)&
dynamic const & operator[] (StringPiece) const &
dynamic && operator[] (StringPiece)&&
template<typename K >
IfIsNonStringDynamicConvertible< K, dynamic > getDefault (K &&k, const dynamic &v=dynamic::object) const &
template<typename K >
IfIsNonStringDynamicConvertible< K, dynamic > getDefault (K &&k, dynamic &&v) const &
template<typename K >
IfIsNonStringDynamicConvertible< K, dynamic > getDefault (K &&k, const dynamic &v=dynamic::object)&&
template<typename K >
IfIsNonStringDynamicConvertible< K, dynamic > getDefault (K &&k, dynamic &&v)&&
dynamic getDefault (StringPiece k, const dynamic &v=dynamic::object) const &
dynamic getDefault (StringPiece k, dynamic &&v) const &
dynamic getDefault (StringPiece k, const dynamic &v=dynamic::object)&&
dynamic getDefault (StringPiece k, dynamic &&v)&&
template<typename K , typename V >
IfIsNonStringDynamicConvertible< K, dynamic & > setDefault (K &&k, V &&v)
template<typename V >
dynamic & setDefault (StringPiece k, V &&v)
template<typename K >
IfIsNonStringDynamicConvertible< K, dynamic & > setDefault (K &&k, dynamic &&v)
template<typename K >
IfIsNonStringDynamicConvertible< K, dynamic & > setDefault (K &&k, const dynamic &v=dynamic::object)
dynamic & setDefault (StringPiece k, dynamic &&v)
dynamic & setDefault (StringPiece k, const dynamic &v=dynamic::object)
void resize (std::size_t n, dynamic const &=nullptr)
template<class K , class V >
void insert (K &&, V &&val)
void update (const dynamic &mergeObj)
void update_missing (const dynamic &other)
void merge_patch (const dynamic &patch)
template<typename K >
IfIsNonStringDynamicConvertible< K, std::size_t > erase (K &&)
std::size_t erase (StringPiece)
iterator erase (const_iterator it)
iterator erase (const_iterator first, const_iterator last)
const_key_iterator erase (const_key_iterator it)
const_key_iterator erase (const_key_iterator first, const_key_iterator last)
value_iterator erase (const_value_iterator it)
value_iterator erase (const_value_iterator first, const_value_iterator last)
item_iterator erase (const_item_iterator it)
item_iterator erase (const_item_iterator first, const_item_iterator last)
void push_back (dynamic const &)
void push_back (dynamic &&)
void pop_back ()
std::size_t hash () const
template<typename K >
dynamic::IfIsNonStringDynamicConvertible< K, dynamic const * > get_ptr (K &&k) const &
Static Public Member Functions
static void array (EmptyArrayTag)
template<class... Args>
static dynamic array (Args &&...args)
static ObjectMaker object ()
static ObjectMaker object (dynamic, dynamic)
static dynamic merge (const dynamic &mergeObj1, const dynamic &mergeObj2)
static dynamic merge_diff (const dynamic &source, const dynamic &target)
Private Types
typedef std::vector< dynamic > Array
using VectorBoolConstRefCtorType = std::conditional_t< std::is_same< std::vector< bool >::const_reference, bool >::value, VectorBoolConstRefFake, std::vector< bool >::const_reference >
template<typename K , typename T >
using IfIsNonStringDynamicConvertible = std::enable_if_t< !std::is_convertible< K, StringPiece >::value &&std::is_convertible< K, dynamic >::value, T >
Private Member Functions
dynamic const & atImpl (dynamic const &) const &
const dynamic * get_ptrImpl (dynamic const &) const &
dynamic (Array &&array)
template<class T >
T const & get () const
template<class T >
T & get ()
template<class T >
T * get_nothrow ()&noexcept
template<class T >
T const * get_nothrow () const &noexcept
template<class T >
T * get_nothrow ()&&noexcept=delete
template<class T >
T * getAddress () noexcept
template<class T >
T const * getAddress () const noexcept
template<class T >
T asImpl () const
void destroy () noexcept
void print (std::ostream &) const
void print_as_pseudo_json (std::ostream &) const
Static Private Member Functions
static char const * typeName (Type)
Private Attributes
Type type_
union folly::dynamic::Data u_
Friends
struct TypeError
std::ostream & operator<< (std::ostream &, dynamic const &)
Detailed Description
Definition at line 79 of file dynamic.h.
Member Typedef Documentation
typedef std::vector<dynamic> folly::dynamic::Array private
Definition at line 90 of file dynamic.h.
typedef Array::const_iterator folly::dynamic::const_iterator
Definition at line 119 of file dynamic.h.
template<typename K , typename T > using folly::dynamic::IfIsNonStringDynamicConvertible = std::enable_if_t< !std::is_convertible<K, StringPiece>::value && std::is_convertible<K, dynamic>::value, T> private
Definition at line 371 of file dynamic.h.
typedef Array::iterator folly::dynamic::iterator
Definition at line 118 of file dynamic.h.
typedef dynamic folly::dynamic::value_type
Definition at line 120 of file dynamic.h.
using folly::dynamic::VectorBoolConstRefCtorType = std::conditional_t< std::is_same<std::vector<bool>::const_reference, bool>::value, VectorBoolConstRefFake, std::vector<bool>::const_reference> private
Definition at line 115 of file dynamic.h.
Member Enumeration Documentation
enum folly::dynamic::Type
Enumerator
NULLT
ARRAY
BOOL
DOUBLE
INT64
OBJECT
STRING
Definition at line 80 of file dynamic.h.
             {
     NULLT,
     ARRAY,
     BOOL,
     DOUBLE,
     INT64,
     OBJECT,
     STRING,
   };
Constructor & Destructor Documentation
folly::dynamic::dynamic () inline
Default constructor, initializes with nullptr.
Definition at line 348 of file dynamic-inl.h.
 : dynamic(nullptr) {}
folly::dynamic::dynamic (std::nullptr_t) inline
Definition at line 350 of file dynamic-inl.h.
 : type_(NULLT) {}
folly::dynamic::dynamic (StringPiece val) inline
Definition at line 360 of file dynamic-inl.h.
References folly::Range< Iter >::data(), folly::Range< Iter >::size(), string, folly::dynamic::Data::string, and u_.
                                      : type_(STRING) {
   new (&u_.string) std::string(s.data(), s.size());
 }
folly::dynamic::dynamic (char const * val) inline
Definition at line 364 of file dynamic-inl.h.
References string, folly::dynamic::Data::string, and u_.
                                      : type_(STRING) {
   new (&u_.string) std::string(s);
 }
folly::dynamic::dynamic (std::string val) inline
Definition at line 368 of file dynamic-inl.h.
References folly::gen::move, string, folly::dynamic::Data::string, and u_.
                                    : type_(STRING) {
   new (&u_.string) std::string(std::move(s));
 }
folly::dynamic::dynamic (void(*)(EmptyArrayTag)) inline
Definition at line 352 of file dynamic-inl.h.
References folly::dynamic::Data::array, and u_.
                                                : type_(ARRAY) {
   new (&u_.array) Array();
 }
folly::dynamic::dynamic (ObjectMaker(*)()) inline
Definition at line 356 of file dynamic-inl.h.
                                          : type_(OBJECT) {
   new (getAddress<ObjectImpl>()) ObjectImpl();
 }
folly::dynamic::dynamic (ObjectMaker const &) delete
folly::dynamic::dynamic (ObjectMaker && maker) inline
Definition at line 372 of file dynamic-inl.h.
References folly::gen::move.
                                            : type_(OBJECT) {
   new (getAddress<ObjectImpl>())
       ObjectImpl(std::move(*maker.val_.getAddress<ObjectImpl>()));
 }
template<class T , class NumericType > folly::dynamic::dynamic (T t)
Definition at line 420 of file dynamic-inl.h.
References type_.
                     {
   type_ = TypeInfo<NumericType>::type;
   new (getAddress<NumericType>()) NumericType(NumericType(t));
 }
folly::dynamic::dynamic (std::vector< bool >::reference val) inline
Definition at line 412 of file dynamic-inl.h.
     : dynamic(static_cast<bool>(b)) {}
folly::dynamic::dynamic (VectorBoolConstRefCtorType val) inline
Definition at line 414 of file dynamic-inl.h.
References folly::T.
     : dynamic(static_cast<bool>(b)) {}
template<class Iterator > folly::dynamic::dynamic (Iterator first, Iterator last) explicit
Definition at line 426 of file dynamic-inl.h.
References folly::dynamic::Data::array, and u_.
                                               : type_(ARRAY) {
   new (&u_.array) Array(first, last);
 }
folly::dynamic::dynamic (dynamic const & o) inline
Definition at line 377 of file dynamic-inl.h.
                                         : type_(NULLT) {
   *this = o;
 }
folly::dynamic::dynamic (dynamic && o) inline noexcept
Definition at line 381 of file dynamic-inl.h.
References folly::gen::move.
                                             : type_(NULLT) {
   *this = std::move(o);
 }
folly::dynamic::~dynamic () inline noexcept
Definition at line 385 of file dynamic-inl.h.
References destroy().
{
   destroy();
 }
folly::dynamic::dynamic (Array && array) inline explicit private
Definition at line 986 of file dynamic-inl.h.
References folly::dynamic::Data::array, folly::gen::move, and u_.
                                  : type_(ARRAY) {
   new (&u_.array) Array(std::move(r));
 }
Member Function Documentation
void folly::dynamic::array (EmptyArrayTag) inline static
Definition at line 233 of file dynamic-inl.h.
References testing::Args().
Referenced by folly::DynamicConstructor< C, typename std::enable_if< !std::is_same< C, dynamic >::value &&!dynamicconverter_detail::is_map< C >::value &&!std::is_constructible< StringPiece, const C & >::value &&dynamicconverter_detail::is_range< C >::value >::type >::construct(), folly::DynamicConstructor< std::pair< A, B >, void >::construct(), folly::DynamicConstructor< std::vector< bool >, void >::construct(), wangle::LRUInMemoryCache< K, V, MutexT >::convertToKeyValuePairs(), folly::bser::decodeArray(), folly::bser::decodeTemplate(), folly::logConfigToDynamic(), proxygen::TraceEvent::MetaData::ConvVisitor< std::string >::operator()(), TEST(), and TYPED_TEST().
 {}
template<class... Args> dynamic folly::dynamic::array (Args &&... args) inline static
Definition at line 236 of file dynamic-inl.h.
{
   return dynamic(Array{std::forward<Args>(args)...});
 }
bool folly::dynamic::asBool () const inline
Definition at line 527 of file dynamic-inl.h.
Referenced by folly::compareDynamicWithTolerance(), folly::DynamicConverter< bool >::convert(), folly::detail::invokeForKeyValue(), and TEST().
{
   return asImpl<bool>();
 }
double folly::dynamic::asDouble () const inline
Definition at line 521 of file dynamic-inl.h.
Referenced by folly::compareDynamicWithTolerance(), folly::DynamicConverter< T, typename std::enable_if< std::is_floating_point< T >::value >::type >::convert(), folly::detail::invokeForKeyValue(), folly::detail::numericOp(), and TEST().
{
   return asImpl<double>();
 }
template<class T > T folly::dynamic::asImpl () const private
Definition at line 1009 of file dynamic-inl.h.
References BOOL, DOUBLE, INT64, STRING, and type().
{
   switch (type()) {
     case INT64:
       return to<T>(*get_nothrow<int64_t>());
     case DOUBLE:
       return to<T>(*get_nothrow<double>());
     case BOOL:
       return to<T>(*get_nothrow<bool>());
     case STRING:
       return to<T>(*get_nothrow<std::string>());
     default:
       throw_exception<TypeError>("int/double/bool/string", type());
   }
 }
int64_t folly::dynamic::asInt () const inline
Definition at line 524 of file dynamic-inl.h.
Referenced by folly::compareDynamicWithTolerance(), folly::DynamicConverter< T, typename std::enable_if< std::is_integral< T >::value &&!std::is_same< T, bool >::value >::type >::convert(), folly::detail::invokeForKeyValue(), folly::detail::numericOp(), operator==(), and TEST().
{
   return asImpl<int64_t>();
 }
std::string folly::dynamic::asString () const inline
Definition at line 518 of file dynamic-inl.h.
Referenced by folly::compareDynamicWithTolerance(), folly::DynamicConverter< folly::fbstring >::convert(), folly::DynamicConverter< std::string >::convert(), folly::convertTo(), folly::detail::invokeForKeyValue(), and TEST().
{
   return asImpl<std::string>();
 }
template<typename K > dynamic::IfIsNonStringDynamicConvertible< K, dynamic const & > folly::dynamic::at (K && k) const
Definition at line 792 of file dynamic-inl.h.
References atImpl(), and k.
Referenced by at(), checkItemParseError(), checkMaybeCoercedKeys(), checkXYKeyErrorsAndParseError(), operator[](), and TEST().
                   {
   return atImpl(std::forward<K>(k));
 }
template<typename K > dynamic::IfIsNonStringDynamicConvertible< K, dynamic & > folly::dynamic::at (K && idx)
Definition at line 798 of file dynamic-inl.h.
References at(), and upload::const.
{
   return const_cast<dynamic&>(const_cast<dynamic const*>(this)->at(idx));
 }
template<typename K > dynamic::IfIsNonStringDynamicConvertible< K, dynamic && > folly::dynamic::at (K && idx)
Definition at line 803 of file dynamic-inl.h.
References at(), and folly::gen::move.
{
   return std::move(at(idx));
 }
dynamic const & folly::dynamic::at (StringPiece idx) const
Definition at line 190 of file dynamic.cpp.
References k, operator[](), folly::sformat(), and type.
{
   auto* pobject = get_nothrow<ObjectImpl>();
   if (!pobject) {
     throw_exception<TypeError>("object", type());
   }
   auto it = pobject->find(idx);
   if (it == pobject->end()) {
     throw_exception<std::out_of_range>(
         sformat("couldn't find key {} in dynamic object", idx));
   }
   return it->second;
 }
dynamic && folly::dynamic::at (StringPiece idx) inline
Definition at line 807 of file dynamic-inl.h.
References at(), upload::const, and folly::gen::move.
{
   return const_cast<dynamic&>(const_cast<dynamic const*>(this)->at(idx));
 }
dynamic&& folly::dynamic::at (StringPiece)
dynamic const & folly::dynamic::atImpl (dynamic const & idx) const private
Definition at line 169 of file dynamic.cpp.
References find(), folly::sformat(), and type.
Referenced by at().
{
   if (auto* parray = get_nothrow<Array>()) {
     if (!idx.isInt()) {
       throw_exception<TypeError>("int64", idx.type());
     }
     if (idx < 0 || idx >= parray->size()) {
       throw_exception<std::out_of_range>("out of range in dynamic array");
     }
     return (*parray)[size_t(idx.asInt())];
   } else if (auto* pobject = get_nothrow<ObjectImpl>()) {
     auto it = pobject->find(idx);
     if (it == pobject->end()) {
       throw_exception<std::out_of_range>(
           sformat("couldn't find key {} in dynamic object", idx.asString()));
     }
     return it->second;
   } else {
     throw_exception<TypeError>("object/array", type());
   }
 }
dynamic::const_iterator folly::dynamic::begin () const inline
Definition at line 432 of file dynamic-inl.h.
Referenced by begin(), folly::compareDynamicWithTolerance(), folly::DynamicConverter< C, typename std::enable_if< dynamicconverter_detail::is_container< C >::value &&!dynamicconverter_detail::is_associative< C >::value >::type >::convert(), folly::DynamicConverter< C, typename std::enable_if< dynamicconverter_detail::is_container< C >::value &&dynamicconverter_detail::is_associative< C >::value >::type >::convert(), and TEST().
{
   return get<Array>().begin();
 }
dynamic::iterator folly::dynamic::begin () inline
Definition at line 439 of file dynamic-inl.h.
References begin().
{
   return get<Array>().begin();
 }
const char * folly::dynamic::c_str () const inline
Definition at line 573 of file dynamic-inl.h.
Referenced by TEST().
{
   return get<std::string>().c_str();
 }
const char* folly::dynamic::c_str () delete
template<typename K > dynamic::IfIsNonStringDynamicConvertible< K, std::size_t > folly::dynamic::count (K && key) const
Definition at line 843 of file dynamic-inl.h.
References find(), and items().
Referenced by wangle::TLSCredProcessor::processTLSTickets(), and TEST().
                    {
   return find(std::forward<K>(key)) != items().end() ? 1u : 0u;
 }
std::size_t folly::dynamic::count (StringPiece key) const inline
Definition at line 848 of file dynamic-inl.h.
References find(), and items().
{
   return find(key) != items().end() ? 1u : 0u;
 }
const char * folly::dynamic::data () const inline
Definition at line 570 of file dynamic-inl.h.
Referenced by folly::dynamic::GetAddrImpl< dynamic::ObjectImpl >::get(), and TEST().
{
   return get<std::string>().data();
 }
const char* folly::dynamic::data () delete
void folly::dynamic::destroy () private noexcept
Definition at line 330 of file dynamic.cpp.
References FB_DYNAMIC_APPLY, FB_X, and type_.
Referenced by ~dynamic().
{
   // This short-circuit speeds up some microbenchmarks.
   if (type_ == NULLT) {
     return;
   }
 #define FB_X(T) detail::Destroy::destroy(getAddress<T>())
   FB_DYNAMIC_APPLY(type_, FB_X);
 #undef FB_X
   type_ = NULLT;
   u_.nul = nullptr;
 }
bool folly::dynamic::empty () const inline
Definition at line 815 of file dynamic-inl.h.
References isNull(), and size().
Referenced by TEST().
{
   if (isNull()) {
     return true;
   }
   return !size();
 }
dynamic::const_iterator folly::dynamic::end () const inline
Definition at line 435 of file dynamic-inl.h.
Referenced by folly::compareDynamicWithTolerance(), folly::DynamicConverter< C, typename std::enable_if< dynamicconverter_detail::is_container< C >::value &&!dynamicconverter_detail::is_associative< C >::value >::type >::convert(), folly::DynamicConverter< C, typename std::enable_if< dynamicconverter_detail::is_container< C >::value &&dynamicconverter_detail::is_associative< C >::value >::type >::convert(), end(), get_ptr(), merge_patch(), and TEST().
{
   return get<Array>().end();
 }
dynamic::iterator folly::dynamic::end () inline
Definition at line 442 of file dynamic-inl.h.
References end().
{
   return get<Array>().end();
 }
template<typename K > dynamic::IfIsNonStringDynamicConvertible< K, std::size_t > folly::dynamic::erase (K && key)
Definition at line 916 of file dynamic-inl.h.
Referenced by erase(), and TEST().
              {
   auto& obj = get<ObjectImpl>();
   return obj.erase(std::forward<K>(key));
 }
std::size_t folly::dynamic::erase (StringPiece key) inline
Definition at line 921 of file dynamic-inl.h.
{
   auto& obj = get<ObjectImpl>();
   return obj.erase(key);
 }
dynamic::iterator folly::dynamic::erase (const_iterator it) inline
Definition at line 926 of file dynamic-inl.h.
References erase().
{
   auto& arr = get<Array>();
   // std::vector doesn't have an erase method that works on const iterators,
   // even though the standard says it should, so this hack converts to a
   // non-const iterator before calling erase.
   return get<Array>().erase(arr.begin() + (it - arr.begin()));
 }
dynamic::iterator folly::dynamic::erase (const_iterator first, const_iterator last)
Definition at line 288 of file dynamic.cpp.
{
   auto& arr = get<Array>();
   return get<Array>().erase(
       arr.begin() + (first - arr.begin()), arr.begin() + (last - arr.begin()));
 }
dynamic::const_key_iterator folly::dynamic::erase (const_key_iterator it) inline
Definition at line 934 of file dynamic-inl.h.
References folly::detail::IteratorAdaptor< D, I, V, Tag >::base(), and erase().
{
   return const_key_iterator(get<ObjectImpl>().erase(it.base()));
 }
dynamic::const_key_iterator folly::dynamic::erase (const_key_iterator first, const_key_iterator last) inline
Definition at line 938 of file dynamic-inl.h.
References folly::detail::IteratorAdaptor< D, I, V, Tag >::base(), and erase().
{
   return const_key_iterator(get<ObjectImpl>().erase(first.base(), last.base()));
 }
dynamic::value_iterator folly::dynamic::erase (const_value_iterator it) inline
Definition at line 944 of file dynamic-inl.h.
References folly::detail::IteratorAdaptor< D, I, V, Tag >::base(), and erase().
{
   return value_iterator(get<ObjectImpl>().erase(it.base()));
 }
dynamic::value_iterator folly::dynamic::erase (const_value_iterator first, const_value_iterator last) inline
Definition at line 948 of file dynamic-inl.h.
References folly::detail::IteratorAdaptor< D, I, V, Tag >::base(), and erase().
{
   return value_iterator(get<ObjectImpl>().erase(first.base(), last.base()));
 }
dynamic::item_iterator folly::dynamic::erase (const_item_iterator it) inline
Definition at line 954 of file dynamic-inl.h.
References folly::detail::IteratorAdaptor< D, I, V, Tag >::base(), and erase().
{
   return item_iterator(get<ObjectImpl>().erase(it.base()));
 }
dynamic::item_iterator folly::dynamic::erase (const_item_iterator first, const_item_iterator last) inline
Definition at line 958 of file dynamic-inl.h.
References folly::detail::IteratorAdaptor< D, I, V, Tag >::base(), and erase().
{
   return item_iterator(get<ObjectImpl>().erase(first.base(), last.base()));
 }
template<typename K > dynamic::IfIsNonStringDynamicConvertible< K, dynamic::const_item_iterator > folly::dynamic::find (K && key) const
Definition at line 824 of file dynamic-inl.h.
Referenced by atImpl(), count(), find(), get_ptr(), get_ptrImpl(), merge_diff(), and TEST().
{
   return get<ObjectImpl>().find(std::forward<K>(key));
 }
template<typename K > dynamic::IfIsNonStringDynamicConvertible< K, dynamic::item_iterator > folly::dynamic::find (K && key)
Definition at line 830 of file dynamic-inl.h.
References find().
                      {
   return get<ObjectImpl>().find(std::forward<K>(key));
 }
dynamic::const_item_iterator folly::dynamic::find (StringPiece key) const inline
Definition at line 834 of file dynamic-inl.h.
References find().
{
   return get<ObjectImpl>().find(key);
 }
dynamic::item_iterator folly::dynamic::find (StringPiece key) inline
Definition at line 838 of file dynamic-inl.h.
References find().
{
   return get<ObjectImpl>().find(key);
 }
template<class T > T const & folly::dynamic::get () const private
Definition at line 1113 of file dynamic-inl.h.
{
   return const_cast<dynamic*>(this)->get<T>();
 }
template<class T > T & folly::dynamic::get () private
Definition at line 1105 of file dynamic-inl.h.
References type().
                 {
   if (auto* p = get_nothrow<T>()) {
     return *p;
   }
   throw_exception<TypeError>(TypeInfo<T>::name, type());
 }
template<class T > T * folly::dynamic::get_nothrow () private noexcept
Definition at line 1027 of file dynamic-inl.h.
References type_.
Referenced by get_ptr().
{
   if (type_ != TypeInfo<T>::type) {
     return nullptr;
   }
   return getAddress<T>();
 }
template<class T > T const * folly::dynamic::get_nothrow () const private noexcept
Definition at line 1036 of file dynamic-inl.h.
{
   return const_cast<dynamic*>(this)->get_nothrow<T>();
 }
template<class T > T* folly::dynamic::get_nothrow () private delete noexcept
const dynamic * folly::dynamic::get_ptr (json_pointer const & jsonPtr) const
Definition at line 371 of file dynamic.cpp.
References end(), get_nothrow(), get_ptr(), isObject(), size(), tokens, and type().
Referenced by folly::compareDynamicWithTolerance(), get_ptr(), folly::parseLogConfigDynamic(), and TEST().
{
   auto const& tokens = jsonPtr.tokens();
   if (tokens.empty()) {
     return this;
   }
   dynamic const* dyn = this;
   for (auto const& token : tokens) {
     if (!dyn) {
       return nullptr;
     }
     // special case of parsing "/": lookup key with empty name
     if (token.empty()) {
       if (dyn->isObject()) {
         dyn = dyn->get_ptr("");
         continue;
       }
       throw_exception<TypeError>("object", dyn->type());
     }
     if (auto* parray = dyn->get_nothrow<dynamic::Array>()) {
       if (token.size() > 1 && token.at(0) == '0') {
         throw std::invalid_argument(
             "Leading zero not allowed when indexing arrays");
       }
       // special case, always return non-existent
       if (token.size() == 1 && token.at(0) == '-') {
         dyn = nullptr;
         continue;
       }
       auto const idx = folly::to<size_t>(token);
       dyn = idx < parray->size() ? &(*parray)[idx] : nullptr;
       continue;
     }
     if (auto* pobject = dyn->get_nothrow<dynamic::ObjectImpl>()) {
       auto const it = pobject->find(token);
       dyn = it != pobject->end() ? &it->second : nullptr;
       continue;
     }
     throw_exception<TypeError>("object/array", dyn->type());
   }
   return dyn;
 }
dynamic * folly::dynamic::get_ptr (json_pointer const & jsonPtr) inline
Definition at line 786 of file dynamic-inl.h.
References upload::const, and get_ptr().
{
   return const_cast<dynamic*>(
       const_cast<dynamic const*>(this)->get_ptr(jsonPtr));
 }
const dynamic* folly::dynamic::get_ptr (json_pointer const &) const delete
dynamic* folly::dynamic::get_ptr (json_pointer const &) delete
template<typename K > IfIsNonStringDynamicConvertible<K, const dynamic*> folly::dynamic::get_ptr (K &&) const
template<typename K > dynamic::IfIsNonStringDynamicConvertible< K, dynamic * > folly::dynamic::get_ptr (K && idx)
Definition at line 777 of file dynamic-inl.h.
References upload::const, and get_ptr().
                {
   return const_cast<dynamic*>(const_cast<dynamic const*>(this)->get_ptr(idx));
 }
template<typename K > IfIsNonStringDynamicConvertible<K, dynamic*> folly::dynamic::get_ptr (K &&) delete
const dynamic * folly::dynamic::get_ptr (StringPiece idx) const
Definition at line 263 of file dynamic.cpp.
References find(), and type.
{
   auto* pobject = get_nothrow<ObjectImpl>();
   if (!pobject) {
     throw_exception<TypeError>("object", type());
   }
   auto it = pobject->find(idx);
   if (it == pobject->end()) {
     return nullptr;
   }
   return &it->second;
 }
dynamic * folly::dynamic::get_ptr (StringPiece idx) inline
Definition at line 782 of file dynamic-inl.h.
References upload::const, and get_ptr().
{
   return const_cast<dynamic*>(const_cast<dynamic const*>(this)->get_ptr(idx));
 }
dynamic* folly::dynamic::get_ptr (StringPiece) delete
template<typename K > dynamic::IfIsNonStringDynamicConvertible<K, dynamic const*> folly::dynamic::get_ptr (K && k) const
Definition at line 771 of file dynamic-inl.h.
References get_ptrImpl(), and k.
                   {
   return get_ptrImpl(std::forward<K>(k));
 }
const dynamic * folly::dynamic::get_ptrImpl (dynamic const & idx) const private
Definition at line 243 of file dynamic.cpp.
References find(), and type.
Referenced by get_ptr().
{
   if (auto* parray = get_nothrow<Array>()) {
     if (!idx.isInt()) {
       throw_exception<TypeError>("int64", idx.type());
     }
     if (idx < 0 || idx >= parray->size()) {
       return nullptr;
     }
     return &(*parray)[size_t(idx.asInt())];
   } else if (auto* pobject = get_nothrow<ObjectImpl>()) {
     auto it = pobject->find(idx);
     if (it == pobject->end()) {
       return nullptr;
     }
     return &it->second;
   } else {
     throw_exception<TypeError>("object/array", type());
   }
 }
template<class T > T * folly::dynamic::getAddress () private noexcept
Definition at line 1043 of file dynamic-inl.h.
References folly::pushmi::operators::get, and u_.
Referenced by operator+=().
{
   return GetAddrImpl<T>::get(u_);
 }
template<class T > T const * folly::dynamic::getAddress () const private noexcept
Definition at line 1048 of file dynamic-inl.h.
{
   return const_cast<dynamic*>(this)->getAddress<T>();
 }
bool folly::dynamic::getBool () const inline
Definition at line 540 of file dynamic-inl.h.
Referenced by folly::bser::bserEncode(), getBool(), and TEST().
{
   return get<bool>();
 }
bool folly::dynamic::getBool () inline
Definition at line 553 of file dynamic-inl.h.
References getBool(), getDouble(), getInt(), getString(), int64_t, folly::gen::move, and string.
{
   return get<bool>();
 }
bool folly::dynamic::getBool ()
template<typename K > dynamic::IfIsNonStringDynamicConvertible< K, dynamic > folly::dynamic::getDefault (K && k, const dynamic & v = dynamic::object) const
Definition at line 685 of file dynamic-inl.h.
References k.
Referenced by folly::convertTo(), and TEST().
{
   auto& obj = get<ObjectImpl>();
   auto it = obj.find(std::forward<K>(k));
   return it == obj.end() ? v : it->second;
 }
template<typename K > dynamic::IfIsNonStringDynamicConvertible< K, dynamic > folly::dynamic::getDefault (K && k, dynamic && v) const
Definition at line 694 of file dynamic-inl.h.
References k, and folly::gen::move.
{
   auto& obj = get<ObjectImpl>();
   auto it = obj.find(std::forward<K>(k));
   // Avoid clang bug with ternary
   if (it == obj.end()) {
     return std::move(v);
   } else {
     return it->second;
   }
 }
template<typename K > dynamic::IfIsNonStringDynamicConvertible< K, dynamic > folly::dynamic::getDefault (K && k, const dynamic & v = dynamic::object)
Definition at line 708 of file dynamic-inl.h.
References k, folly::gen::move, and v.
{
   auto& obj = get<ObjectImpl>();
   auto it = obj.find(std::forward<K>(k));
   // Avoid clang bug with ternary
   if (it == obj.end()) {
     return v;
   } else {
     return std::move(it->second);
   }
 }
template<typename K > dynamic::IfIsNonStringDynamicConvertible< K, dynamic > folly::dynamic::getDefault (K && k, dynamic && v)
Definition at line 722 of file dynamic-inl.h.
References k, and folly::gen::move.
                     {
   auto& obj = get<ObjectImpl>();
   auto it = obj.find(std::forward<K>(k));
   return std::move(it == obj.end() ? v : it->second);
 }
dynamic folly::dynamic::getDefault (StringPiece k, const dynamic & v = dynamic::object) const
Definition at line 209 of file dynamic.cpp.
{
   auto& obj = get<ObjectImpl>();
   auto it = obj.find(k);
   return it == obj.end() ? v : it->second;
 }
dynamic folly::dynamic::getDefault (StringPiece k, dynamic && v) const
Definition at line 215 of file dynamic.cpp.
References folly::gen::move.
{
   auto& obj = get<ObjectImpl>();
   auto it = obj.find(k);
   // Avoid clang bug with ternary
   if (it == obj.end()) {
     return std::move(v);
   } else {
     return it->second;
   }
 }
dynamic folly::dynamic::getDefault (StringPiece k, const dynamic & v = dynamic::object)
Definition at line 226 of file dynamic.cpp.
References folly::gen::move, and v.
{
   auto& obj = get<ObjectImpl>();
   auto it = obj.find(k);
   // Avoid clang bug with ternary
   if (it == obj.end()) {
     return v;
   } else {
     return std::move(it->second);
   }
 }
dynamic folly::dynamic::getDefault (StringPiece k, dynamic && v)
Definition at line 237 of file dynamic.cpp.
References folly::gen::move.
{
   auto& obj = get<ObjectImpl>();
   auto it = obj.find(k);
   return std::move(it == obj.end() ? v : it->second);
 }
double folly::dynamic::getDouble () const inline
Definition at line 534 of file dynamic-inl.h.
Referenced by folly::bser::bserEncode(), getBool(), and TEST().
{
   return get<double>();
 }
double folly::dynamic::getDouble () inline
Definition at line 547 of file dynamic-inl.h.
{
   return get<double>();
 }
double folly::dynamic::getDouble ()
int64_t folly::dynamic::getInt () const inline
Definition at line 537 of file dynamic-inl.h.
Referenced by folly::bser::bserEncode(), getBool(), and TEST().
{
   return get<int64_t>();
 }
int64_t folly::dynamic::getInt () inline
Definition at line 550 of file dynamic-inl.h.
{
   return get<int64_t>();
 }
int64_t folly::dynamic::getInt ()
const std::string & folly::dynamic::getString () const inline
Definition at line 531 of file dynamic-inl.h.
Referenced by folly::bser::bserEncode(), getBool(), and TEST().
{
   return get<std::string>();
 }
std::string && folly::dynamic::getString () inline
Definition at line 544 of file dynamic-inl.h.
{
   return get<std::string>();
 }
std::string&& folly::dynamic::getString ()
std::size_t folly::dynamic::hash () const
Definition at line 294 of file dynamic.cpp.
References folly::f14::accumulate(), folly::assume_unreachable(), folly::test::begin(), folly::test::end(), h, folly::hash::hash_range(), STRING, and type.
Referenced by folly::detail::DynamicHasher::operator()(), and std::hash<::folly::dynamic >::operator()().
{
   switch (type()) {
     case NULLT:
       return 0xBAAAAAAD;
     case OBJECT: {
       // Accumulate using addition instead of using hash_range (as in the ARRAY
       // case), as we need a commutative hash operation since unordered_map's
       // iteration order is unspecified.
       auto h = std::hash<std::pair<dynamic, dynamic>>{};
       return std::accumulate(
           items().begin(),
           items().end(),
           size_t{0x0B1EC7},
           [&](auto acc, auto item) { return acc + h(item); });
     }
     case ARRAY:
       return folly::hash::hash_range(begin(), end());
     case INT64:
       return std::hash<int64_t>()(getInt());
     case DOUBLE:
       return std::hash<double>()(getDouble());
     case BOOL:
       return std::hash<bool>()(getBool());
     case STRING:
       // keep consistent with detail::DynamicHasher
       return Hash()(getString());
   }
   assume_unreachable();
 }
template<class K , class V > void folly::dynamic::insert (K && key, V && val) inline
Definition at line 853 of file dynamic-inl.h.
References val.
Referenced by folly::DynamicConstructor< C, typename std::enable_if< !std::is_same< C, dynamic >::value &&dynamicconverter_detail::is_map< C >::value >::type >::construct(), folly::logConfigToDynamic(), and TEST().
{
   auto& obj = get<ObjectImpl>();
   obj[std::forward<K>(key)] = std::forward<V>(val);
 }
bool folly::dynamic::isArray () const inline
Definition at line 498 of file dynamic-inl.h.
Referenced by folly::DynamicConverter< std::pair< F, S > >::convert(), folly::DynamicConverter< C, typename std::enable_if< dynamicconverter_detail::is_container< C >::value &&!dynamicconverter_detail::is_associative< C >::value >::type >::convert(), folly::DynamicConverter< C, typename std::enable_if< dynamicconverter_detail::is_container< C >::value &&dynamicconverter_detail::is_associative< C >::value >::type >::convert(), operator[](), and TEST().
{
   return get_nothrow<Array>() != nullptr;
 }
bool folly::dynamic::isBool () const inline
Definition at line 495 of file dynamic-inl.h.
{
   return get_nothrow<bool>() != nullptr;
 }
bool folly::dynamic::isDouble () const inline
Definition at line 501 of file dynamic-inl.h.
Referenced by isNumber(), and folly::detail::numericOp().
{
   return get_nothrow<double>() != nullptr;
 }
bool folly::dynamic::isInt () const inline
Definition at line 504 of file dynamic-inl.h.
Referenced by folly::compareDynamicWithTolerance(), isNumber(), and folly::detail::numericOp().
{
   return get_nothrow<int64_t>() != nullptr;
 }
bool folly::dynamic::isNull () const inline
Definition at line 507 of file dynamic-inl.h.
Referenced by empty(), and TEST().
{
   return get_nothrow<std::nullptr_t>() != nullptr;
 }
bool folly::dynamic::isNumber () const inline
Definition at line 510 of file dynamic-inl.h.
References isDouble(), and isInt().
Referenced by folly::compareDynamicWithTolerance(), folly::detail::numericOp(), and operator==().
{
   return isInt() || isDouble();
 }
bool folly::dynamic::isObject () const inline
Definition at line 492 of file dynamic-inl.h.
Referenced by folly::DynamicConverter< std::pair< F, S > >::convert(), folly::DynamicConverter< C, typename std::enable_if< dynamicconverter_detail::is_container< C >::value &&!dynamicconverter_detail::is_associative< C >::value >::type >::convert(), folly::DynamicConverter< C, typename std::enable_if< dynamicconverter_detail::is_container< C >::value &&dynamicconverter_detail::is_associative< C >::value >::type >::convert(), get_ptr(), merge_diff(), merge_patch(), operator[](), folly::parseLogConfigDynamic(), update(), and update_missing().
{
   return get_nothrow<ObjectImpl>() != nullptr;
 }
bool folly::dynamic::isString () const inline
Definition at line 489 of file dynamic-inl.h.
{
   return get_nothrow<std::string>() != nullptr;
 }
dynamic::IterableProxy< dynamic::const_item_iterator > folly::dynamic::items () const inline
Definition at line 476 of file dynamic-inl.h.
Referenced by folly::bser::bserEncodeObject(), folly::compareDynamicWithTolerance(), folly::DynamicConverter< std::pair< F, S > >::convert(), folly::DynamicConverter< C, typename std::enable_if< dynamicconverter_detail::is_container< C >::value &&!dynamicconverter_detail::is_associative< C >::value >::type >::convert(), folly::DynamicConverter< C, typename std::enable_if< dynamicconverter_detail::is_container< C >::value &&dynamicconverter_detail::is_associative< C >::value >::type >::convert(), count(), merge_diff(), merge_patch(), TEST(), update(), and update_missing().
           {
   return &(get<ObjectImpl>());
 }
dynamic::IterableProxy< dynamic::item_iterator > folly::dynamic::items () inline
Definition at line 485 of file dynamic-inl.h.
{
   return &(get<ObjectImpl>());
 }
dynamic::IterableProxy< dynamic::const_key_iterator > folly::dynamic::keys () const inline
Definition at line 466 of file dynamic-inl.h.
Referenced by TEST().
           {
   return &(get<ObjectImpl>());
 }
dynamic folly::dynamic::merge (const dynamic & mergeObj1, const dynamic & mergeObj2) inline static
Definition at line 904 of file dynamic-inl.h.
References update_missing().
{
   // No checks on type needed here because they are done in update_missing
   // Note that we do update_missing here instead of update() because
   // it will prevent the extra writes that would occur with update()
   auto ret = mergeObj2;
   ret.update_missing(mergeObj1);
   return ret;
 }
dynamic folly::dynamic::merge_diff (const dynamic & source, const dynamic & target) static
Definition at line 343 of file dynamic.cpp.
References diff(), find(), isObject(), items(), object, and type().
{
   if (!source.isObject() || source.type() != target.type()) {
     return target;
   }
   dynamic diff = object;
   // added/modified keys
   for (const auto& pair : target.items()) {
     auto it = source.find(pair.first);
     if (it == source.items().end()) {
       diff[pair.first] = pair.second;
     } else {
       diff[pair.first] = merge_diff(source[pair.first], target[pair.first]);
     }
   }
   // removed keys
   for (const auto& pair : source.items()) {
     auto it = target.find(pair.first);
     if (it == target.items().end()) {
       diff[pair.first] = nullptr;
     }
   }
   return diff;
 }
void folly::dynamic::merge_patch (const dynamic & patch) inline
Definition at line 881 of file dynamic-inl.h.
References end(), isObject(), items(), and object().
Referenced by TEST().
{
   auto& self = *this;
   if (!patch.isObject()) {
     self = patch;
     return;
   }
   // if we are not an object, erase all contents, reset to object
   if (!isObject()) {
     self = object;
   }
   for (const auto& pair : patch.items()) {
     if (pair.second.isNull()) {
       // if name could be found in current object, remove it
       auto it = self.find(pair.first);
       if (it != self.items().end()) {
         self.erase(it);
       }
     } else {
       self[pair.first].merge_patch(pair.second);
     }
   }
 }
dynamic::ObjectMaker folly::dynamic::object () inline static
Definition at line 240 of file dynamic-inl.h.
Referenced by checkItemParseError(), checkMaybeCoercedKeys(), checkXYKeyErrorsAndParseError(), folly::DynamicConstructor< C, typename std::enable_if< !std::is_same< C, dynamic >::value &&dynamicconverter_detail::is_map< C >::value >::type >::construct(), folly::bser::decodeObject(), folly::bser::decodeTemplate(), folly::DynamicParser::ParserStack::errors(), folly::logConfigToDynamic(), merge_patch(), folly::DynamicParser::reportError(), TEST(), and folly::toDynamic().
{
   return ObjectMaker();
 }
dynamic::ObjectMaker folly::dynamic::object (dynamic a, dynamic b) inline static
Definition at line 243 of file dynamic-inl.h.
References folly::gen::move.
{
   return ObjectMaker(std::move(a), std::move(b));
 }
dynamic & folly::dynamic::operator%= (dynamic const & o) inline
Definition at line 633 of file dynamic-inl.h.
dynamic & folly::dynamic::operator&= (dynamic const & o) inline
Definition at line 635 of file dynamic-inl.h.
dynamic & folly::dynamic::operator*= (dynamic const & o) inline
Definition at line 614 of file dynamic-inl.h.
{
   *this = detail::numericOp<std::multiplies>(*this, o);
   return *this;
 }
dynamic & folly::dynamic::operator++ () inline
Definition at line 640 of file dynamic-inl.h.
{
   ++get<int64_t>();
   return *this;
 }
dynamic & folly::dynamic::operator+= (dynamic const & o) inline
Definition at line 600 of file dynamic-inl.h.
References getAddress(), STRING, string, and type().
{
   if (type() == STRING && o.type() == STRING) {
     *getAddress<std::string>() += *o.getAddress<std::string>();
     return *this;
   }
   *this = detail::numericOp<std::plus>(*this, o);
   return *this;
 }
dynamic & folly::dynamic::operator-- () inline
Definition at line 645 of file dynamic-inl.h.
{
   --get<int64_t>();
   return *this;
 }
dynamic & folly::dynamic::operator-= (dynamic const & o) inline
Definition at line 609 of file dynamic-inl.h.
{
   *this = detail::numericOp<std::minus>(*this, o);
   return *this;
 }
dynamic & folly::dynamic::operator/= (dynamic const & o) inline
Definition at line 619 of file dynamic-inl.h.
{
   *this = detail::numericOp<std::divides>(*this, o);
   return *this;
 }
bool folly::dynamic::operator< (dynamic const & o) const
Definition at line 107 of file dynamic.cpp.
References FB_DYNAMIC_APPLY, FB_X, type_, type_, and UNLIKELY.
{
   if (UNLIKELY(type_ == OBJECT || o.type_ == OBJECT)) {
     throw_exception<TypeError>("object", type_);
   }
   if (type_ != o.type_) {
     return type_ < o.type_;
   }
 #define FB_X(T) return CompareOp<T>::comp(*getAddress<T>(), *o.getAddress<T>())
   FB_DYNAMIC_APPLY(type_, FB_X);
 #undef FB_X
 }
dynamic & folly::dynamic::operator= (dynamic const & o)
Definition at line 135 of file dynamic.cpp.
References destroy(), FB_DYNAMIC_APPLY, FB_X, type_, and type_.
{
   if (&o != this) {
     if (type_ == o.type_) {
 #define FB_X(T) *getAddress<T>() = *o.getAddress<T>()
       FB_DYNAMIC_APPLY(type_, FB_X);
 #undef FB_X
     } else {
       destroy();
 #define FB_X(T) new (getAddress<T>()) T(*o.getAddress<T>())
       FB_DYNAMIC_APPLY(o.type_, FB_X);
 #undef FB_X
       type_ = o.type_;
     }
   }
   return *this;
 }
dynamic & folly::dynamic::operator= (dynamic && o) noexcept
Definition at line 152 of file dynamic.cpp.
References destroy(), FB_DYNAMIC_APPLY, FB_X, and type_.
{
   if (&o != this) {
     if (type_ == o.type_) {
 #define FB_X(T) *getAddress<T>() = std::move(*o.getAddress<T>())
       FB_DYNAMIC_APPLY(type_, FB_X);
 #undef FB_X
     } else {
       destroy();
 #define FB_X(T) new (getAddress<T>()) T(std::move(*o.getAddress<T>()))
       FB_DYNAMIC_APPLY(o.type_, FB_X);
 #undef FB_X
       type_ = o.type_;
     }
   }
   return *this;
 }
bool folly::dynamic::operator== (dynamic const & o) const
Definition at line 120 of file dynamic.cpp.
References asInt(), FB_DYNAMIC_APPLY, FB_X, isNumber(), type(), type, and type_.
{
   if (type() != o.type()) {
     if (isNumber() && o.isNumber()) {
       auto& integ = isInt() ? *this : o;
       auto& doubl = isInt() ? o : *this;
       return integ.asInt() == doubl.asDouble();
     }
     return false;
   }
 #define FB_X(T) return *getAddress<T>() == *o.getAddress<T>();
   FB_DYNAMIC_APPLY(type_, FB_X);
 #undef FB_X
 }
template<typename K > dynamic::IfIsNonStringDynamicConvertible< K, dynamic & > folly::dynamic::operator[] (K && idx)
Definition at line 657 of file dynamic-inl.h.
References at(), isArray(), isObject(), and type().
Referenced by at().
                {
   if (!isObject() && !isArray()) {
     throw_exception<TypeError>("object/array", type());
   }
   if (isArray()) {
     return at(std::forward<K>(idx));
   }
   auto& obj = get<ObjectImpl>();
   auto ret = obj.emplace(std::forward<K>(idx), nullptr);
   return ret.first->second;
 }
template<typename K > dynamic::IfIsNonStringDynamicConvertible< K, dynamic const & > folly::dynamic::operator[] (K && idx) const
Definition at line 651 of file dynamic-inl.h.
References at().
                     {
   return at(std::forward<K>(idx));
 }
template<typename K > dynamic::IfIsNonStringDynamicConvertible< K, dynamic && > folly::dynamic::operator[] (K && idx)
Definition at line 671 of file dynamic-inl.h.
References folly::gen::move.
                 {
   return std::move((*this)[std::forward<K>(idx)]);
 }
dynamic & folly::dynamic::operator[] (StringPiece k) inline
Definition at line 680 of file dynamic-inl.h.
References k, and folly::gen::move.
{
   return std::move((*this)[k]);
 }
dynamic const & folly::dynamic::operator[] (StringPiece k) const inline
Definition at line 676 of file dynamic-inl.h.
References at(), and k.
{
   return at(k);
 }
dynamic&& folly::dynamic::operator[] (StringPiece)
dynamic & folly::dynamic::operator^= (dynamic const & o) inline
Definition at line 636 of file dynamic-inl.h.
dynamic & folly::dynamic::operator|= (dynamic const & o) inline
Definition at line 634 of file dynamic-inl.h.
void folly::dynamic::pop_back () inline
Definition at line 979 of file dynamic-inl.h.
{
   auto& arr = get<Array>();
   arr.pop_back();
 }
void folly::dynamic::print (std::ostream & out) const inline private
Definition at line 1152 of file dynamic-inl.h.
References FB_DYNAMIC_APPLY, FB_X, and type_.
Referenced by folly::operator<<().
{
 #define FB_X(T) PrintImpl<T>::print(*this, out, *getAddress<T>())
   FB_DYNAMIC_APPLY(type_, FB_X);
 #undef FB_X
 }
void folly::dynamic::print_as_pseudo_json (std::ostream & out) const private
Definition at line 930 of file json.cpp.
References folly::json::serialization_opts::allow_nan_inf, folly::json::serialization_opts::allow_non_string_keys, and folly::json::serialize().
Referenced by folly::dynamic::PrintImpl< dynamic::ObjectImpl >::print(), and folly::dynamic::PrintImpl< dynamic::Array >::print().
{
   json::serialization_opts opts;
   opts.allow_non_string_keys = true;
   opts.allow_nan_inf = true;
   out << json::serialize(*this, opts);
 }
void folly::dynamic::push_back (dynamic const & v) inline
Definition at line 969 of file dynamic-inl.h.
Referenced by folly::benchmarkResultsToDynamic(), folly::DynamicConstructor< C, typename std::enable_if< !std::is_same< C, dynamic >::value &&!dynamicconverter_detail::is_map< C >::value &&!std::is_constructible< StringPiece, const C & >::value &&dynamicconverter_detail::is_range< C >::value >::type >::construct(), folly::DynamicConstructor< std::pair< A, B >, void >::construct(), folly::DynamicConstructor< std::vector< bool >, void >::construct(), wangle::LRUInMemoryCache< K, V, MutexT >::convertToKeyValuePairs(), folly::bser::decodeArray(), folly::bser::decodeTemplate(), proxygen::TraceEvent::MetaData::ConvVisitor< std::string >::operator()(), and TEST().
{
   auto& arr = get<Array>();
   arr.push_back(v);
 }
void folly::dynamic::push_back (dynamic && v) inline
Definition at line 974 of file dynamic-inl.h.
References folly::gen::move.
{
   auto& arr = get<Array>();
   arr.push_back(std::move(v));
 }
void folly::dynamic::resize (std::size_t n, dynamic const & c = nullptr) inline
Definition at line 964 of file dynamic-inl.h.
Referenced by TEST().
{
   auto& arr = get<Array>();
   arr.resize(sz, c);
 }
template<typename K , typename V > dynamic::IfIsNonStringDynamicConvertible< K, dynamic & > folly::dynamic::setDefault (K && k, V && v)
Definition at line 731 of file dynamic-inl.h.
References k.
Referenced by TEST().
            {
   auto& obj = get<ObjectImpl>();
   return obj.emplace(std::forward<K>(k), std::forward<V>(v)).first->second;
 }
template<typename V > dynamic & folly::dynamic::setDefault (StringPiece k, V && v)
Definition at line 755 of file dynamic-inl.h.
{
   auto& obj = get<ObjectImpl>();
   return obj.emplace(k, std::forward<V>(v)).first->second;
 }
template<typename K > dynamic::IfIsNonStringDynamicConvertible< K, dynamic & > folly::dynamic::setDefault (K && k, dynamic && v)
Definition at line 739 of file dynamic-inl.h.
References k, and folly::gen::move.
                  {
   auto& obj = get<ObjectImpl>();
   return obj.emplace(std::forward<K>(k), std::move(v)).first->second;
 }
template<typename K > dynamic::IfIsNonStringDynamicConvertible< K, dynamic & > folly::dynamic::setDefault (K && k, const dynamic & v = dynamic::object)
Definition at line 747 of file dynamic-inl.h.
References k.
                       {
   auto& obj = get<ObjectImpl>();
   return obj.emplace(std::forward<K>(k), v).first->second;
 }
dynamic & folly::dynamic::setDefault (StringPiece k, dynamic && v) inline
Definition at line 760 of file dynamic-inl.h.
References folly::gen::move.
{
   auto& obj = get<ObjectImpl>();
   return obj.emplace(k, std::move(v)).first->second;
 }
dynamic & folly::dynamic::setDefault (StringPiece k, const dynamic & v = dynamic::object) inline
Definition at line 765 of file dynamic-inl.h.
{
   auto& obj = get<ObjectImpl>();
   return obj.emplace(k, v).first->second;
 }
std::size_t folly::dynamic::size () const
Definition at line 275 of file dynamic.cpp.
References type.
Referenced by folly::bser::bserEncodeArray(), folly::bser::bserEncodeArraySimple(), folly::bser::bserEncodeObject(), folly::compareDynamicWithTolerance(), folly::DynamicConverter< std::pair< F, S > >::convert(), empty(), get_ptr(), and TEST().
{
   if (auto* ar = get_nothrow<Array>()) {
     return ar->size();
   }
   if (auto* obj = get_nothrow<ObjectImpl>()) {
     return obj->size();
   }
   if (auto* str = get_nothrow<std::string>()) {
     return str->size();
   }
   throw_exception<TypeError>("array/object/string", type());
 }
StringPiece folly::dynamic::stringPiece () const inline
Definition at line 576 of file dynamic-inl.h.
Referenced by folly::detail::DynamicKeyEqual::operator()(), and TEST().
{
   return get<std::string>();
 }
dynamic::Type folly::dynamic::type () const inline
Definition at line 514 of file dynamic-inl.h.
References type_.
Referenced by asImpl(), folly::bser::bserEncode(), folly::compareDynamicWithTolerance(), folly::DynamicConverter< std::pair< F, S > >::convert(), folly::DynamicConverter< C, typename std::enable_if< dynamicconverter_detail::is_container< C >::value &&!dynamicconverter_detail::is_associative< C >::value >::type >::convert(), folly::DynamicConverter< C, typename std::enable_if< dynamicconverter_detail::is_container< C >::value &&dynamicconverter_detail::is_associative< C >::value >::type >::convert(), get(), get_ptr(), merge_diff(), folly::detail::numericOp(), folly::detail::DynamicKeyEqual::operator()(), operator+=(), operator==(), operator[](), wangle::TLSCredProcessor::processTLSTickets(), TEST(), update(), and update_missing().
{
   return type_;
 }
const char * folly::dynamic::typeName () const
Definition at line 45 of file dynamic.cpp.
References type_.
Referenced by TEST().
{
   return typeName(type_);
 }
char const * folly::dynamic::typeName (Type t) static private
Definition at line 324 of file dynamic.cpp.
References FB_DYNAMIC_APPLY, and FB_X.
{
 #define FB_X(T) return TypeInfo<T>::name
   FB_DYNAMIC_APPLY(t, FB_X);
 #undef FB_X
 }
void folly::dynamic::update (const dynamic & mergeObj) inline
Definition at line 858 of file dynamic-inl.h.
References isObject(), items(), and type().
Referenced by TEST().
{
   if (!isObject() || !mergeObj.isObject()) {
     throw_exception<TypeError>("object", type(), mergeObj.type());
   }
   for (const auto& pair : mergeObj.items()) {
     (*this)[pair.first] = pair.second;
   }
 }
void folly::dynamic::update_missing (const dynamic & other) inline
Definition at line 868 of file dynamic-inl.h.
References isObject(), items(), and type().
Referenced by merge(), and TEST().
{
   if (!isObject() || !mergeObj1.isObject()) {
     throw_exception<TypeError>("object", type(), mergeObj1.type());
   }
   // Only add if not already there
   for (const auto& pair : mergeObj1.items()) {
     if ((*this).find(pair.first) == (*this).items().end()) {
       (*this)[pair.first] = pair.second;
     }
   }
 }
dynamic::IterableProxy< dynamic::const_value_iterator > folly::dynamic::values () const inline
Definition at line 471 of file dynamic-inl.h.
Referenced by TEST().
           {
   return &(get<ObjectImpl>());
 }
dynamic::IterableProxy< dynamic::value_iterator > folly::dynamic::values () inline
Definition at line 481 of file dynamic-inl.h.
{
   return &(get<ObjectImpl>());
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, dynamic const & d) friend
Definition at line 1158 of file dynamic-inl.h.
{
   d.print(out);
   return out;
 }
friend struct TypeError friend
Definition at line 647 of file dynamic.h.
Member Data Documentation
Type folly::dynamic::type_ private
Definition at line 688 of file dynamic.h.
Referenced by dynamic(), get_nothrow(), operator<(), operator=(), print(), type(), and typeName().
union folly::dynamic::Data folly::dynamic::u_ private
Referenced by dynamic(), and getAddress().
The documentation for this struct was generated from the following files:
proxygen/folly/folly/dynamic.h
proxygen/folly/folly/dynamic-inl.h
proxygen/folly/folly/dynamic.cpp
proxygen/folly/folly/json.cpp