proxygen: folly::pushmi::make_constrained_single_sender_fn Struct Reference
folly::pushmi::make_constrained_single_sender_fn Struct Reference
#include <constrained_single_sender.h>
Public Member Functions
auto operator() () const
requires True PUSHMI_BROKEN_SUBSUMPTION not auto operator() (SF sf) const
requires Invocable< EXF & > PUSHMI_BROKEN_SUBSUMPTION not auto operator() (SF sf, EXF exf) const
requires Invocable< ZF & > &&Invocable< EXF & > PUSHMI_BROKEN_SUBSUMPTION not auto operator() (SF sf, EXF exf, ZF zf) const
requires ConstrainedSender< Data, is_single<> > auto operator() (Data d) const
requires ConstrainedSender< Data, is_single<> > auto operator() (Data d, DSF sf) const
requires ConstrainedSender< Data, is_single<> > &&Invocable< DEXF &, Data & > auto operator() (Data d, DSF sf, DEXF exf) const
requires ConstrainedSender< Data, is_single<> > &&Invocable< DZF &, Data & > &&Invocable< DEXF &, Data & > auto operator() (Data d, DSF sf, DEXF exf, DZF zf) const
Detailed Description
Definition at line 215 of file constrained_single_sender.h.
Member Function Documentation
auto folly::pushmi::make_constrained_single_sender_fn::operator() () const inline
Definition at line 216 of file constrained_single_sender.h.
References PUSHMI_BROKEN_SUBSUMPTION, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return constrained_single_sender<ignoreSF, priorityZeroF, inlineConstrainedEXF>{};
   }
requires True PUSHMI_BROKEN_SUBSUMPTION not auto folly::pushmi::make_constrained_single_sender_fn::operator() (SF sf) const inline
Definition at line 221 of file constrained_single_sender.h.
References folly::gen::move, PUSHMI_BROKEN_SUBSUMPTION, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return constrained_single_sender<SF, priorityZeroF, inlineConstrainedEXF>{std::move(sf)};
   }
requires Invocable<EXF&> PUSHMI_BROKEN_SUBSUMPTION not auto folly::pushmi::make_constrained_single_sender_fn::operator() (SF sf, EXF exf) const inline
Definition at line 226 of file constrained_single_sender.h.
References folly::gen::move, PUSHMI_BROKEN_SUBSUMPTION, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return constrained_single_sender<SF, priorityZeroF, EXF>{std::move(sf), std::move(exf)};
   }
requires Invocable<ZF&>&& Invocable<EXF&> PUSHMI_BROKEN_SUBSUMPTION not auto folly::pushmi::make_constrained_single_sender_fn::operator() (SF sf, EXF exf, ZF zf) const inline
Definition at line 231 of file constrained_single_sender.h.
References folly::gen::move, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return constrained_single_sender<SF, ZF, EXF>{std::move(sf), std::move(exf), std::move(zf)};
   }
requires ConstrainedSender<Data, is_single<> > auto folly::pushmi::make_constrained_single_sender_fn::operator() (Data d) const inline
Definition at line 236 of file constrained_single_sender.h.
References folly::gen::move, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return constrained_single_sender<Data, passDSF, passDZF, passDEXF>{std::move(d)};
   }
requires ConstrainedSender<Data, is_single<> > auto folly::pushmi::make_constrained_single_sender_fn::operator() (Data d, DSF sf) const inline
Definition at line 241 of file constrained_single_sender.h.
References folly::gen::move, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return constrained_single_sender<Data, DSF, passDZF, passDEXF>{std::move(d), std::move(sf)};
   }
requires ConstrainedSender<Data, is_single<> >&& Invocable<DEXF&, Data&> auto folly::pushmi::make_constrained_single_sender_fn::operator() (Data d, DSF sf, DEXF exf) const inline
Definition at line 246 of file constrained_single_sender.h.
References folly::gen::move, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return constrained_single_sender<Data, DSF, passDZF, DEXF>{std::move(d), std::move(sf),
       std::move(exf)};
   }
requires ConstrainedSender<Data, is_single<> >&& Invocable<DZF&, Data&>&& Invocable<DEXF&, Data&> auto folly::pushmi::make_constrained_single_sender_fn::operator() (Data d, DSF sf, DEXF exf, DZF zf) const inline
Definition at line 252 of file constrained_single_sender.h.
References folly::pushmi::make_constrained_single_sender, folly::gen::move, PUSHMI_BROKEN_SUBSUMPTION, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return constrained_single_sender<Data, DSF, DZF, DEXF>{std::move(d), std::move(sf),
       std::move(exf), std::move(zf)};
   }
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/pushmi/constrained_single_sender.h