proxygen: folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::vtable Struct Reference
folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::vtable Struct Reference
Static Public Member Functions
static void s_op (data &, data *)
static any_executor< E > s_executor (data &)
static void s_submit (data &, any_flow_receiver< PE, PV, E, VN... >)
Public Attributes
void(* op_)(data &, data *) = vtable::s_op
any_executor< E >(* executor_)(data &) = vtable::s_executor
void(* submit_)(data &, any_flow_receiver< PE, PV, E, VN... >) = vtable::s_submit
Detailed Description
template<class PE, class PV, class E, class... VN>
struct folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::vtable
Definition at line 36 of file flow_many_sender.h.
Member Function Documentation
template<class PE , class PV , class E , class... VN> static any_executor<E> folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::vtable::s_executor (data &) inline static
Definition at line 38 of file flow_many_sender.h.
 { return {}; }
template<class PE , class PV , class E , class... VN> static void folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::vtable::s_op (data & , data *) inline static
Definition at line 37 of file flow_many_sender.h.
 {}
template<class PE , class PV , class E , class... VN> static void folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::vtable::s_submit (data & , any_flow_receiver< PE, PV, E, VN... >) inline static
Definition at line 39 of file flow_many_sender.h.
 {}
Member Data Documentation
template<class PE , class PV , class E , class... VN> any_executor<E>(* folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::vtable::executor_) (data &) = vtable::s_executor
Definition at line 41 of file flow_many_sender.h.
Referenced by folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::executor().
template<class PE , class PV , class E , class... VN> void(* folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::vtable::op_) (data &, data *) = vtable::s_op
Definition at line 40 of file flow_many_sender.h.
Referenced by folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::any_flow_many_sender(), and folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::~any_flow_many_sender().
template<class PE , class PV , class E , class... VN> void(* folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::vtable::submit_) (data &, any_flow_receiver< PE, PV, E, VN... >) = vtable::s_submit
Definition at line 42 of file flow_many_sender.h.
Referenced by folly::pushmi::any_flow_many_sender< PE, PV, E, VN >::submit().
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/pushmi/flow_many_sender.h