proxygen: folly::pushmi::detail::submit_after_fn::fn< D, AN > Struct Template Reference
folly::pushmi::detail::submit_after_fn::fn< D, AN > Struct Template Reference
Public Member Functions
requires submit_detail::AutoTimeSenderTo< In, AN... > In operator() (In in)
Public Attributes
D after_
std::tuple< AN... > args_
Detailed Description
template<class D, class... AN>
struct folly::pushmi::detail::submit_after_fn::fn< D, AN >
Definition at line 101 of file submit.h.
Member Function Documentation
template<class D , class... AN> requires submit_detail::AutoTimeSenderTo<In, AN...> In folly::pushmi::detail::submit_after_fn::fn< D, AN >::operator() (In in) inline
Definition at line 106 of file submit.h.
References D, folly::gen::move, now(), folly::pushmi::detail::PUSHMI_TEMPLATE(), folly::pushmi::detail::requires(), and submit.
{
       // TODO - only move, move-only types..
       // if out can be copied, then submit can be called multiple
       // times..
       auto out{
           ::folly::pushmi::detail::receiver_from_fn<In>()(std::move(args_))};
       auto at = ::folly::pushmi::now(in) + std::move(after_);
       ::folly::pushmi::submit(in, std::move(at), std::move(out));
       return in;
     }
Member Data Documentation
template<class D , class... AN> D folly::pushmi::detail::submit_after_fn::fn< D, AN >::after_
Definition at line 102 of file submit.h.
template<class D , class... AN> std::tuple<AN...> folly::pushmi::detail::submit_after_fn::fn< D, AN >::args_
Definition at line 103 of file submit.h.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/pushmi/o/submit.h