proxygen: PredFormatFunctor3 Struct Reference
PredFormatFunctor3 Struct Reference
Public Member Functions
template<typename T1 , typename T2 , typename T3 >
testing::AssertionResult operator() (const char *e1, const char *e2, const char *e3, const T1 &v1, const T2 &v2, const T3 &v3) const
template<typename T1 , typename T2 , typename T3 >
testing::AssertionResult operator() (const char *e1, const char *e2, const char *e3, const T1 &v1, const T2 &v2, const T3 &v3) const
template<typename T1 , typename T2 , typename T3 >
testing::AssertionResult operator() (const char *e1, const char *e2, const char *e3, const T1 &v1, const T2 &v2, const T3 &v3) const
Detailed Description
Definition at line 935 of file gtest_pred_impl_unittest.cc.
Member Function Documentation
template<typename T1 , typename T2 , typename T3 > testing::AssertionResult PredFormatFunctor3::operator() (const char * e1, const char * e2, const char * e3, const T1 & v1, const T2 & v2, const T3 & v3) const inline
Definition at line 937 of file gtest_pred_impl_unittest.cc.
References PredFormatFunction3().
{
     return PredFormatFunction3(e1, e2, e3, v1, v2, v3);
   }
template<typename T1 , typename T2 , typename T3 > testing::AssertionResult PredFormatFunctor3::operator() (const char * e1, const char * e2, const char * e3, const T1 & v1, const T2 & v2, const T3 & v3) const inline
Definition at line 937 of file gtest_pred_impl_unittest.cc.
References PredFormatFunction3().
{
     return PredFormatFunction3(e1, e2, e3, v1, v2, v3);
   }
template<typename T1 , typename T2 , typename T3 > testing::AssertionResult PredFormatFunctor3::operator() (const char * e1, const char * e2, const char * e3, const T1 & v1, const T2 & v2, const T3 & v3) const inline
Definition at line 937 of file gtest_pred_impl_unittest.cc.
References PredFormatFunction3().
{
     return PredFormatFunction3(e1, e2, e3, v1, v2, v3);
   }
The documentation for this struct was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest_pred_impl_unittest.cc