proxygen: PredFormatFunctor1 Struct Reference
PredFormatFunctor1 Struct Reference
Public Member Functions
template<typename T1 >
testing::AssertionResult operator() (const char *e1, const T1 &v1) const
template<typename T1 >
testing::AssertionResult operator() (const char *e1, const T1 &v1) const
template<typename T1 >
testing::AssertionResult operator() (const char *e1, const T1 &v1) const
Detailed Description
Definition at line 113 of file gtest_pred_impl_unittest.cc.
Member Function Documentation
template<typename T1 > testing::AssertionResult PredFormatFunctor1::operator() (const char * e1, const T1 & v1) const inline
Definition at line 115 of file gtest_pred_impl_unittest.cc.
References PredFormatFunction1().
{
     return PredFormatFunction1(e1, v1);
   }
template<typename T1 > testing::AssertionResult PredFormatFunctor1::operator() (const char * e1, const T1 & v1) const inline
Definition at line 115 of file gtest_pred_impl_unittest.cc.
References PredFormatFunction1().
{
     return PredFormatFunction1(e1, v1);
   }
template<typename T1 > testing::AssertionResult PredFormatFunctor1::operator() (const char * e1, const T1 & v1) const inline
Definition at line 115 of file gtest_pred_impl_unittest.cc.
References PredFormatFunction1().
{
     return PredFormatFunction1(e1, v1);
   }
The documentation for this struct was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest_pred_impl_unittest.cc