proxygen: folly::BenchmarkSuspender Struct Reference
folly::BenchmarkSuspender Struct Reference
#include <Benchmark.h>
Public Types
using Clock = std::chrono::high_resolution_clock
using TimePoint = Clock::time_point
using Duration = Clock::duration
Public Member Functions
BenchmarkSuspender ()
BenchmarkSuspender (const BenchmarkSuspender &)=delete
BenchmarkSuspender (BenchmarkSuspender &&rhs) noexcept
BenchmarkSuspender & operator= (const BenchmarkSuspender &)=delete
BenchmarkSuspender & operator= (BenchmarkSuspender &&rhs)
~BenchmarkSuspender ()
void dismiss ()
void rehire ()
template<class F >
auto dismissing (F f) -> invoke_result_t< F >
operator bool () const
Static Public Attributes
static Duration timeSpent
Private Member Functions
void tally ()
Private Attributes
TimePoint start
Detailed Description
Supporting type for BENCHMARK_SUSPEND defined below.
Definition at line 87 of file Benchmark.h.
Member Typedef Documentation
using folly::BenchmarkSuspender::Clock = std::chrono::high_resolution_clock
Definition at line 88 of file Benchmark.h.
using folly::BenchmarkSuspender::Duration = Clock::duration
Definition at line 90 of file Benchmark.h.
using folly::BenchmarkSuspender::TimePoint = Clock::time_point
Definition at line 89 of file Benchmark.h.
Constructor & Destructor Documentation
folly::BenchmarkSuspender::BenchmarkSuspender () inline
Definition at line 92 of file Benchmark.h.
References now(), and start.
{
     start = Clock::now();
   }
folly::BenchmarkSuspender::BenchmarkSuspender (const BenchmarkSuspender &) delete
folly::BenchmarkSuspender::BenchmarkSuspender (BenchmarkSuspender && rhs) inline noexcept
Definition at line 97 of file Benchmark.h.
References folly::detail::rhs, and start.
{
     start = rhs.start;
     rhs.start = {};
   }
folly::BenchmarkSuspender::~BenchmarkSuspender () inline
Definition at line 112 of file Benchmark.h.
References start.
{
     if (start != TimePoint{}) {
       tally();
     }
   }
Member Function Documentation
void folly::BenchmarkSuspender::dismiss () inline
Definition at line 118 of file Benchmark.h.
References start.
Referenced by addValue(), atomicIncrBaseline(), BENCHMARK(), BENCHMARK_RELATIVE(), contend(), contentionAtWidth(), dummy(), folly::test::fc_test(), inlineObserve(), notifyInlineObservers(), notifySubscribers(), observe(), runTest(), runTestTag(), subscribeImpl(), TEST(), zeroCopyOff(), and zeroCopyOn().
                  {
     assert(start != TimePoint{});
     tally();
     start = {};
   }
template<class F > auto folly::BenchmarkSuspender::dismissing (F f) -> invoke_result_t<F> inline
Definition at line 130 of file Benchmark.h.
References f, and SCOPE_EXIT.
Referenced by BENCHMARK(), BENCHMARK_RELATIVE(), and runContended().
{
     SCOPE_EXIT {
       rehire();
     };
     dismiss();
     return f();
   }
folly::BenchmarkSuspender::operator bool () const inline explicit
This is for use inside of if-conditions, used in BENCHMARK macros. If-conditions bypass the explicit on operator bool.
Definition at line 142 of file Benchmark.h.
{
     return false;
   }
BenchmarkSuspender& folly::BenchmarkSuspender::operator= (const BenchmarkSuspender &) delete
BenchmarkSuspender& folly::BenchmarkSuspender::operator= (BenchmarkSuspender && rhs) inline
Definition at line 103 of file Benchmark.h.
References folly::detail::rhs, and start.
{
     if (start != TimePoint{}) {
       tally();
     }
     start = rhs.start;
     rhs.start = {};
     return *this;
   }
void folly::BenchmarkSuspender::rehire () inline
Definition at line 124 of file Benchmark.h.
References now(), and start.
Referenced by contend(), inlineObserve(), notifyInlineObservers(), notifySubscribers(), observe(), runTest(), runTestTag(), subscribeImpl(), zeroCopyOff(), and zeroCopyOn().
                 {
     assert(start == TimePoint{});
     start = Clock::now();
   }
void folly::BenchmarkSuspender::tally () inline private
Definition at line 152 of file Benchmark.h.
References folly::test::end(), now(), and start.
                {
     auto end = Clock::now();
     timeSpent += end - start;
     start = end;
   }
Member Data Documentation
TimePoint folly::BenchmarkSuspender::start private
Definition at line 158 of file Benchmark.h.
std::chrono::high_resolution_clock::duration folly::BenchmarkSuspender::timeSpent static
Accumulates time spent outside benchmark.
Definition at line 149 of file Benchmark.h.
Referenced by folly::addBenchmark().
The documentation for this struct was generated from the following files:
proxygen/folly/folly/Benchmark.h
proxygen/folly/folly/Benchmark.cpp