proxygen: folly::pushmi::operators::from_fn Struct Reference
folly::pushmi::operators::from_fn Struct Reference
#include <from.h>
Classes
struct out_impl
struct sender_base
Public Member Functions
requires DerivedFrom< typename std::iterator_traits< I >::iterator_category, std::forward_iterator_tag > auto operator() (I begin, S end) const
requires Range< R > auto operator() (R &&range) const
Detailed Description
Definition at line 36 of file from.h.
Member Function Documentation
requires DerivedFrom< typename std::iterator_traits<I>::iterator_category, std::forward_iterator_tag> auto folly::pushmi::operators::from_fn::operator() (I begin, S end) const inline
Definition at line 67 of file from.h.
References folly::test::begin(), folly::test::end(), folly::pushmi::make_many_sender, folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return make_many_sender(sender_base{}, out_impl<I, S>{begin, end});
   }
requires Range<R> auto folly::pushmi::operators::from_fn::operator() (R && range) const inline
Definition at line 73 of file from.h.
References folly::test::begin(), folly::test::end(), folly::pushmi::operators::from, and folly::range().
{
     return (*this)(std::begin(range), std::end(range));
   }
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/pushmi/o/from.h