proxygen: folly::DynamicConstructor< C, typename std::enable_if< !std::is_same< C, dynamic >::value &&dynamicconverter_detail::is_map< C >::value >::type > Struct Template Reference
folly::DynamicConstructor< C, typename std::enable_if< !std::is_same< C, dynamic >::value &&dynamicconverter_detail::is_map< C >::value >::type > Struct Template Reference
#include <DynamicConverter.h>
Static Public Member Functions
static dynamic construct (const C &x)
Detailed Description
template<typename C>
struct folly::DynamicConstructor< C, typename std::enable_if< !std::is_same< C, dynamic >::value &&dynamicconverter_detail::is_map< C >::value >::type >
Definition at line 332 of file DynamicConverter.h.
Member Function Documentation
template<typename C > static dynamic folly::DynamicConstructor< C, typename std::enable_if< !std::is_same< C, dynamic >::value &&dynamicconverter_detail::is_map< C >::value >::type >::construct (const C & x) inline static
Definition at line 337 of file DynamicConverter.h.
References folly::dynamic::insert(), folly::dynamic::object(), and folly::toDynamic().
{
     dynamic d = dynamic::object;
     for (const auto& pair : x) {
       d.insert(toDynamic(pair.first), toDynamic(pair.second));
     }
     return d;
   }
The documentation for this struct was generated from the following file:
proxygen/folly/folly/DynamicConverter.h