proxygen: folly::detail::fixedstring::FixedStringBase_< class > Struct Template Reference
folly::detail::fixedstring::FixedStringBase_< class > Struct Template Reference
#include <FixedString.h>
Static Public Attributes
static constexpr std::size_t npos = static_cast<std::size_t>(-1)
Detailed Description
template<class = void>
struct folly::detail::fixedstring::FixedStringBase_< class >
Definition at line 53 of file FixedString.h.
Member Data Documentation
template<class = void> constexpr std::size_t folly::detail::fixedstring::FixedStringBase_< Void >::npos = static_cast<std::size_t>(-1) static
Definition at line 54 of file FixedString.h.
Referenced by folly::detail::fixedstring::checkOverflowOrNpos(), folly::BasicFixedString< Char, N >::find(), folly::detail::fixedstring::find_(), folly::BasicFixedString< Char, N >::find_first_not_of(), folly::detail::fixedstring::find_first_not_of_(), folly::BasicFixedString< Char, N >::find_first_of(), folly::detail::fixedstring::find_first_of_(), folly::BasicFixedString< Char, N >::find_last_not_of(), folly::detail::fixedstring::find_last_not_of_(), folly::BasicFixedString< Char, N >::find_last_of(), folly::detail::fixedstring::find_last_of_(), folly::BasicFixedString< Char, N >::rfind(), and folly::detail::fixedstring::rfind_().
The documentation for this struct was generated from the following file:
proxygen/folly/folly/FixedString.h