proxygen: folly::NetworkSocket Struct Reference
folly::NetworkSocket Struct Reference
#include <NetworkSocket.h>
Public Types
using native_handle_type = int
Public Member Functions
constexpr NetworkSocket ()
constexpr NetworkSocket (native_handle_type d)
int toFd () const
Static Public Member Functions
static NetworkSocket fromFd (int fd)
Public Attributes
native_handle_type data
Static Public Attributes
static constexpr native_handle_type invalid_handle_value = -1
Friends
constexpr bool operator== (const NetworkSocket &a, const NetworkSocket &b) noexcept
constexpr bool operator!= (const NetworkSocket &a, const NetworkSocket &b) noexcept
Detailed Description
This is just a very thin wrapper around either a file descriptor or a SOCKET depending on platform, along with a couple of helper methods for explicitly converting to/from file descriptors, even on Windows.
Definition at line 30 of file NetworkSocket.h.
Member Typedef Documentation
using folly::NetworkSocket::native_handle_type = int
Definition at line 35 of file NetworkSocket.h.
Constructor & Destructor Documentation
constexpr folly::NetworkSocket::NetworkSocket () inline
Definition at line 41 of file NetworkSocket.h.
Referenced by fromFd().
 : data(invalid_handle_value) {}
constexpr folly::NetworkSocket::NetworkSocket (native_handle_type d) inline explicit
Definition at line 42 of file NetworkSocket.h.
 : data(d) {}
Member Function Documentation
static NetworkSocket folly::NetworkSocket::fromFd (int fd) inline static
Definition at line 44 of file NetworkSocket.h.
References folly::netops::detail::SocketFileDescriptorMap::fdToSocket(), and NetworkSocket().
Referenced by folly::EventHandler::changeHandlerFD(), folly::EventHandler::initHandler(), folly::AsyncUDPSocket::setFD(), and folly::shutdownNoInt().
{
     return NetworkSocket(
         netops::detail::SocketFileDescriptorMap::fdToSocket(fd));
   }
int folly::NetworkSocket::toFd () const inline
Definition at line 49 of file NetworkSocket.h.
References folly::netops::detail::SocketFileDescriptorMap::socketToFd().
Referenced by folly::EventHandler::changeHandlerFD(), folly::EventHandler::EventHandler(), folly::AsyncUDPSocket::getFD(), and folly::EventHandler::initHandler().
                    {
     return netops::detail::SocketFileDescriptorMap::socketToFd(data);
   }
Friends And Related Function Documentation
constexpr bool operator!= (const NetworkSocket & a, const NetworkSocket & b) friend
Definition at line 59 of file NetworkSocket.h.
{
     return !(a == b);
   }
constexpr bool operator== (const NetworkSocket & a, const NetworkSocket & b) friend
Definition at line 53 of file NetworkSocket.h.
{
     return a.data == b.data;
   }
Member Data Documentation
native_handle_type folly::NetworkSocket::data
Definition at line 39 of file NetworkSocket.h.
Referenced by folly::netops::close(), folly::operator<<(), folly::netops::recv(), folly::netops::recvfrom(), folly::netops::recvmsg(), folly::netops::sendmsg(), folly::netops::set_socket_close_on_exec(), and folly::netops::set_socket_non_blocking().
constexpr native_handle_type folly::NetworkSocket::invalid_handle_value = -1 static
Definition at line 36 of file NetworkSocket.h.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/net/NetworkSocket.h