proxygen: folly::detail::EndianInt< T > Struct Template Reference
folly::detail::EndianInt< T > Struct Template Reference
#include <Bits.h>
Static Public Member Functions
static T swap (T x)
static T big (T x)
static T little (T x)
Detailed Description
template<class T>
struct folly::detail::EndianInt< T >
Definition at line 199 of file Bits.h.
Member Function Documentation
template<class T > static T folly::detail::EndianInt< T >::big (T x) inline static
Definition at line 215 of file Bits.h.
References folly::kIsLittleEndian, folly::detail::EndianInt< T >::swap(), and x.
Referenced by folly::Endian::big().
                     {
     return kIsLittleEndian ? EndianInt::swap(x) : x;
   }
template<class T > static T folly::detail::EndianInt< T >::little (T x) inline static
Definition at line 218 of file Bits.h.
References folly::kIsBigEndian, folly::detail::EndianInt< T >::swap(), and x.
Referenced by folly::Endian::little().
{
     return kIsBigEndian ? EndianInt::swap(x) : x;
   }
template<class T > static T folly::detail::EndianInt< T >::swap (T x) inline static
Definition at line 204 of file Bits.h.
References b, folly::detail::byteswap_gen(), s, folly::T, and x.
Referenced by folly::detail::EndianInt< T >::big(), folly::detail::EndianInt< T >::little(), and folly::Endian::swap().
                      {
     // we implement this with memcpy because that is defined behavior in C++
     // we rely on compilers to optimize away the memcpy calls
     constexpr auto s = sizeof(T);
     using B = typename uint_types_by_size<s>::type;
     B b;
     std::memcpy(&b, &x, s);
     b = byteswap_gen(b);
     std::memcpy(&x, &b, s);
     return x;
   }
The documentation for this struct was generated from the following file:
proxygen/folly/folly/lang/Bits.h