proxygen: folly::detail::DynamicKeyEqual Struct Reference
folly::detail::DynamicKeyEqual Struct Reference
#include <dynamic-inl.h>
Public Types
using is_transparent = void
Public Member Functions
bool operator() (const dynamic &lhs, const dynamic &rhs) const
template<typename A , typename B >
std::enable_if_t< std::is_convertible< A, StringPiece >::value &&std::is_convertible< B, StringPiece >::value, bool > operator() (A const &lhs, B const &rhs) const =delete
template<typename A >
std::enable_if_t< std::is_convertible< A, StringPiece >::value, bool > operator() (A const &lhs, dynamic const &rhs) const
template<typename B >
std::enable_if_t< std::is_convertible< B, StringPiece >::value, bool > operator() (dynamic const &lhs, B const &rhs) const
Detailed Description
Definition at line 44 of file dynamic-inl.h.
Member Typedef Documentation
using folly::detail::DynamicKeyEqual::is_transparent = void
Definition at line 45 of file dynamic-inl.h.
Member Function Documentation
bool folly::detail::DynamicKeyEqual::operator() (const dynamic & lhs, const dynamic & rhs) const inline
Definition at line 47 of file dynamic-inl.h.
References folly::detail::DynamicHasher::operator()(), folly::detail::rhs, and value.
{
     return std::equal_to<dynamic>()(lhs, rhs);
   }
template<typename A , typename B > std::enable_if_t< std::is_convertible<A, StringPiece>::value && std::is_convertible<B, StringPiece>::value, bool> folly::detail::DynamicKeyEqual::operator() (A const & lhs, B const & rhs) const delete
template<typename A > std::enable_if_t<std::is_convertible<A, StringPiece>::value, bool> folly::detail::DynamicKeyEqual::operator() (A const & lhs, dynamic const & rhs) const inline
Definition at line 62 of file dynamic-inl.h.
References FOLLY_LIKELY, STRING, folly::dynamic::stringPiece(), and folly::dynamic::type().
{
     return FOLLY_LIKELY(rhs.type() == dynamic::Type::STRING) &&
         std::equal_to<StringPiece>()(lhs, rhs.stringPiece());
   }
template<typename B > std::enable_if_t<std::is_convertible<B, StringPiece>::value, bool> folly::detail::DynamicKeyEqual::operator() (dynamic const & lhs, B const & rhs) const inline
Definition at line 70 of file dynamic-inl.h.
References FOLLY_LIKELY, folly::detail::rhs, STRING, folly::dynamic::stringPiece(), and folly::dynamic::type().
{
     return FOLLY_LIKELY(lhs.type() == dynamic::Type::STRING) &&
         std::equal_to<StringPiece>()(lhs.stringPiece(), rhs);
   }
The documentation for this struct was generated from the following file:
proxygen/folly/folly/dynamic-inl.h