proxygen: testing::gmock_generated_actions_test::SumOf6Functor Struct Reference
testing::gmock_generated_actions_test::SumOf6Functor Struct Reference
Public Member Functions
int operator() (int a, int b, int c, int d, int e, int f)
int operator() (int a, int b, int c, int d, int e, int f)
int operator() (int a, int b, int c, int d, int e, int f)
Detailed Description
Definition at line 127 of file gmock-generated-actions_test.cc.
Member Function Documentation
int testing::gmock_generated_actions_test::SumOf6Functor::operator() (int a, int b, int c, int d, int e, int f) inline
Definition at line 128 of file gmock-generated-actions_test.cc.
References f.
{
     return a + b + c + d + e + f;
   }
int testing::gmock_generated_actions_test::SumOf6Functor::operator() (int a, int b, int c, int d, int e, int f) inline
Definition at line 128 of file gmock-generated-actions_test.cc.
References testing::gmock_generated_actions_test::Binary(), testing::gmock_generated_actions_test::ByConstRef(), testing::ByRef(), testing::gmock_generated_actions_test::Char(), testing::gmock_generated_actions_test::CharPtr(), testing::gmock_generated_actions_test::Concat10(), testing::gmock_generated_actions_test::Concat4(), testing::gmock_generated_actions_test::Concat5(), testing::gmock_generated_actions_test::Concat6(), testing::gmock_generated_actions_test::Concat7(), testing::gmock_generated_actions_test::Concat8(), testing::gmock_generated_actions_test::Concat9(), EXPECT_EQ, EXPECT_FALSE, EXPECT_STREQ, EXPECT_TRUE, f, testing::Invoke(), std::tr1::make_tuple(), testing::gmock_generated_actions_test::Nullary(), testing::Action< F >::Perform(), testing::gmock_generated_actions_test::ReferencesGlobalDouble(), s, testing::gmock_generated_actions_test::Short(), string, testing::gmock_generated_actions_test::SumOf5(), testing::gmock_generated_actions_test::SumOf6(), testing::gmock_generated_actions_test::Ternary(), testing::gmock_generated_actions_test::TEST(), and testing::gmock_generated_actions_test::Unary().
{
     return a + b + c + d + e + f;
   }
int testing::gmock_generated_actions_test::SumOf6Functor::operator() (int a, int b, int c, int d, int e, int f) inline
Definition at line 128 of file gmock-generated-actions_test.cc.
References testing::gmock_generated_actions_test::Binary(), testing::gmock_generated_actions_test::ByConstRef(), testing::ByRef(), testing::gmock_generated_actions_test::Char(), testing::gmock_generated_actions_test::CharPtr(), testing::gmock_generated_actions_test::Concat10(), testing::gmock_generated_actions_test::Concat4(), testing::gmock_generated_actions_test::Concat5(), testing::gmock_generated_actions_test::Concat6(), testing::gmock_generated_actions_test::Concat7(), testing::gmock_generated_actions_test::Concat8(), testing::gmock_generated_actions_test::Concat9(), EXPECT_EQ, EXPECT_FALSE, EXPECT_STREQ, EXPECT_TRUE, f, testing::Invoke(), std::tr1::make_tuple(), testing::gmock_generated_actions_test::Nullary(), testing::Action< F >::Perform(), testing::gmock_generated_actions_test::ReferencesGlobalDouble(), s, testing::gmock_generated_actions_test::Short(), string, testing::gmock_generated_actions_test::SumOf5(), testing::gmock_generated_actions_test::SumOf6(), testing::gmock_generated_actions_test::Ternary(), testing::gmock_generated_actions_test::TEST(), and testing::gmock_generated_actions_test::Unary().
{
     return a + b + c + d + e + f;
   }
The documentation for this struct was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-generated-actions_test.cc