proxygen: folly::UnboundedQueue< T, SingleProducer, SingleConsumer, MayBlock, LgSegmentSize, LgAlign, Atom >::Producer Struct Reference
folly::UnboundedQueue< T, SingleProducer, SingleConsumer, MayBlock, LgSegmentSize, LgAlign, Atom >::Producer Struct Reference
Public Member Functions
Producer (Segment *s)
Public Attributes
Atom< Segment * > tail
Atom< Ticket > ticket
Detailed Description
template<typename T, bool SingleProducer, bool SingleConsumer, bool MayBlock, size_t LgSegmentSize = 8, size_t LgAlign = constexpr_log2(hardware_destructive_interference_size), template< typename > class Atom = std::atomic>
struct folly::UnboundedQueue< T, SingleProducer, SingleConsumer, MayBlock, LgSegmentSize, LgAlign, Atom >::Producer
Definition at line 238 of file UnboundedQueue.h.
Constructor & Destructor Documentation
template<typename T, bool SingleProducer, bool SingleConsumer, bool MayBlock, size_t LgSegmentSize = 8, size_t LgAlign = constexpr_log2(hardware_destructive_interference_size), template< typename > class Atom = std::atomic> folly::UnboundedQueue< T, SingleProducer, SingleConsumer, MayBlock, LgSegmentSize, LgAlign, Atom >::Producer::Producer (Segment * s) inline explicit
Definition at line 241 of file UnboundedQueue.h.
 : tail(s), ticket(0) {}
Member Data Documentation
template<typename T, bool SingleProducer, bool SingleConsumer, bool MayBlock, size_t LgSegmentSize = 8, size_t LgAlign = constexpr_log2(hardware_destructive_interference_size), template< typename > class Atom = std::atomic> Atom<Segment*> folly::UnboundedQueue< T, SingleProducer, SingleConsumer, MayBlock, LgSegmentSize, LgAlign, Atom >::Producer::tail
Definition at line 239 of file UnboundedQueue.h.
Referenced by folly::UnboundedQueue< T, false, 6 >::casTail(), folly::UnboundedQueue< T, false, 6 >::enqueueImpl(), folly::UnboundedQueue< T, false, 6 >::setTail(), and folly::UnboundedQueue< T, false, 6 >::tail().
template<typename T, bool SingleProducer, bool SingleConsumer, bool MayBlock, size_t LgSegmentSize = 8, size_t LgAlign = constexpr_log2(hardware_destructive_interference_size), template< typename > class Atom = std::atomic> Atom<Ticket> folly::UnboundedQueue< T, SingleProducer, SingleConsumer, MayBlock, LgSegmentSize, LgAlign, Atom >::Producer::ticket
Definition at line 240 of file UnboundedQueue.h.
Referenced by folly::UnboundedQueue< T, false, 6 >::fetchIncrementProducerTicket(), folly::UnboundedQueue< T, false, 6 >::producerTicket(), and folly::UnboundedQueue< T, false, 6 >::setProducerTicket().
The documentation for this struct was generated from the following file:
proxygen/folly/folly/concurrency/UnboundedQueue.h