proxygen: folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::WaitForDuration< Rep, Period > Struct Template Reference
folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::WaitForDuration< Rep, Period > Struct Template Reference
Public Member Functions
WaitForDuration (const std::chrono::duration< Rep, Period > &duration)
std::chrono::steady_clock::time_point deadline ()
bool canBlock ()
bool canTimeOut ()
bool shouldTimeOut ()
bool doWait (Futex &futex, uint32_t expected, uint32_t waitMask)
Public Attributes
std::chrono::duration< Rep, Period > duration_
bool deadlineComputed_
std::chrono::steady_clock::time_point deadline_
Detailed Description
template<bool ReaderPriority, typename Tag_ = void, template< typename > class Atom = std::atomic, bool BlockImmediately = false, bool AnnotateForThreadSanitizer = kIsSanitizeThread && !ReaderPriority>
template<class Rep, class Period>
struct folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::WaitForDuration< Rep, Period >
Definition at line 617 of file SharedMutex.h.
Constructor & Destructor Documentation
template<bool ReaderPriority, typename Tag_ = void, template< typename > class Atom = std::atomic, bool BlockImmediately = false, bool AnnotateForThreadSanitizer = kIsSanitizeThread && !ReaderPriority> template<class Rep , class Period > folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::WaitForDuration< Rep, Period >::WaitForDuration (const std::chrono::duration< Rep, Period > & duration) inline explicit
Definition at line 622 of file SharedMutex.h.
         : duration_(duration), deadlineComputed_(false) {}
Member Function Documentation
template<bool ReaderPriority, typename Tag_ = void, template< typename > class Atom = std::atomic, bool BlockImmediately = false, bool AnnotateForThreadSanitizer = kIsSanitizeThread && !ReaderPriority> template<class Rep , class Period > bool folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::WaitForDuration< Rep, Period >::canBlock () inline
Definition at line 633 of file SharedMutex.h.
                     {
       return duration_.count() > 0;
     }
template<bool ReaderPriority, typename Tag_ = void, template< typename > class Atom = std::atomic, bool BlockImmediately = false, bool AnnotateForThreadSanitizer = kIsSanitizeThread && !ReaderPriority> template<class Rep , class Period > bool folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::WaitForDuration< Rep, Period >::canTimeOut () inline
Definition at line 636 of file SharedMutex.h.
                       {
       return true;
     }
template<bool ReaderPriority, typename Tag_ = void, template< typename > class Atom = std::atomic, bool BlockImmediately = false, bool AnnotateForThreadSanitizer = kIsSanitizeThread && !ReaderPriority> template<class Rep , class Period > std::chrono::steady_clock::time_point folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::WaitForDuration< Rep, Period >::deadline () inline
Definition at line 625 of file SharedMutex.h.
References now().
{
       if (!deadlineComputed_) {
         deadline_ = std::chrono::steady_clock::now() + duration_;
         deadlineComputed_ = true;
       }
       return deadline_;
     }
template<bool ReaderPriority, typename Tag_ = void, template< typename > class Atom = std::atomic, bool BlockImmediately = false, bool AnnotateForThreadSanitizer = kIsSanitizeThread && !ReaderPriority> template<class Rep , class Period > bool folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::WaitForDuration< Rep, Period >::doWait (Futex & futex, uint32_t expected, uint32_t waitMask) inline
Definition at line 644 of file SharedMutex.h.
References folly::detail::futexWaitUntil(), and folly::detail::TIMEDOUT.
{
       auto result =
           detail::futexWaitUntil(&futex, expected, deadline(), waitMask);
       return result != folly::detail::FutexResult::TIMEDOUT;
     }
template<bool ReaderPriority, typename Tag_ = void, template< typename > class Atom = std::atomic, bool BlockImmediately = false, bool AnnotateForThreadSanitizer = kIsSanitizeThread && !ReaderPriority> template<class Rep , class Period > bool folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::WaitForDuration< Rep, Period >::shouldTimeOut () inline
Definition at line 640 of file SharedMutex.h.
References now().
{
       return std::chrono::steady_clock::now() > deadline();
     }
Member Data Documentation
template<bool ReaderPriority, typename Tag_ = void, template< typename > class Atom = std::atomic, bool BlockImmediately = false, bool AnnotateForThreadSanitizer = kIsSanitizeThread && !ReaderPriority> template<class Rep , class Period > std::chrono::steady_clock::time_point folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::WaitForDuration< Rep, Period >::deadline_
Definition at line 620 of file SharedMutex.h.
template<bool ReaderPriority, typename Tag_ = void, template< typename > class Atom = std::atomic, bool BlockImmediately = false, bool AnnotateForThreadSanitizer = kIsSanitizeThread && !ReaderPriority> template<class Rep , class Period > bool folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::WaitForDuration< Rep, Period >::deadlineComputed_
Definition at line 619 of file SharedMutex.h.
template<bool ReaderPriority, typename Tag_ = void, template< typename > class Atom = std::atomic, bool BlockImmediately = false, bool AnnotateForThreadSanitizer = kIsSanitizeThread && !ReaderPriority> template<class Rep , class Period > std::chrono::duration<Rep, Period> folly::SharedMutexImpl< ReaderPriority, Tag_, Atom, BlockImmediately, AnnotateForThreadSanitizer >::WaitForDuration< Rep, Period >::duration_
Definition at line 618 of file SharedMutex.h.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/SharedMutex.h