proxygen: D0< b > Struct Template Reference
D0< b > Struct Template Reference
Public Member Functions
D0 ()=default
D0 (const D0 &)=default
D0 (D0 &&)=default
D0 (std::nullptr_t)
D0 & operator= (const D0 &)=default
D0 & operator= (D0 &&)=default
Detailed Description
template<bool b>
struct D0< b >
Definition at line 258 of file StlVectorTest.cpp.
Constructor & Destructor Documentation
template<bool b> D0< b >::D0 () default
template<bool b> D0< b >::D0 (const D0< b > &) default
template<bool b> D0< b >::D0 (D0< b > &&) default
template<bool b> D0< b >::D0 (std::nullptr_t) inline explicit
Definition at line 262 of file StlVectorTest.cpp.
 {}
Member Function Documentation
template<bool b> D0& D0< b >::operator= (const D0< b > &) default
Referenced by Alloc< T >::Alloc(), D0<(f &DC_DELETE)!=0 >::D0(), D0< true >::D0(), D1<(f &CC_DELETE)!=0 >::D1(), D1< true >::D1(), D2<(f &MC_DELETE)!=0 >::D2(), D2< true >::D2(), D3<(f &CA_DELETE)!=0 >::D3(), D3< true >::D3(), D4<(f &MA_DELETE)!=0 >::D4(), D4< true >::D4(), and Data< f, pad >::Data().
template<bool b> D0& D0< b >::operator= (D0< b > &&) default
The documentation for this struct was generated from the following file:
proxygen/folly/folly/test/stl_tests/StlVectorTest.cpp