proxygen: folly::DynamicConstructor< C, typename std::enable_if< !std::is_same< C, dynamic >::value &&!dynamicconverter_detail::is_map< C >::value &&!std::is_constructible< StringPiece, const C & >::value &&dynamicconverter_detail::is_range< C >::value >::type > Struct Template Reference
folly::DynamicConstructor< C, typename std::enable_if< !std::is_same< C, dynamic >::value &&!dynamicconverter_detail::is_map< C >::value &&!std::is_constructible< StringPiece, const C & >::value &&dynamicconverter_detail::is_range< C >::value >::type > Struct Template Reference
#include <DynamicConverter.h>
Static Public Member Functions
static dynamic construct (const C &x)
Detailed Description
template<typename C>
struct folly::DynamicConstructor< C, typename std::enable_if< !std::is_same< C, dynamic >::value &&!dynamicconverter_detail::is_map< C >::value &&!std::is_constructible< StringPiece, const C & >::value &&dynamicconverter_detail::is_range< C >::value >::type >
Definition at line 348 of file DynamicConverter.h.
Member Function Documentation
template<typename C > static dynamic folly::DynamicConstructor< C, typename std::enable_if< !std::is_same< C, dynamic >::value &&!dynamicconverter_detail::is_map< C >::value &&!std::is_constructible< StringPiece, const C & >::value &&dynamicconverter_detail::is_range< C >::value >::type >::construct (const C & x) inline static
Definition at line 355 of file DynamicConverter.h.
References folly::dynamic::array(), folly::dynamic::push_back(), and folly::toDynamic().
{
     dynamic d = dynamic::array;
     for (const auto& item : x) {
       d.push_back(toDynamic(item));
     }
     return d;
   }
The documentation for this struct was generated from the following file:
proxygen/folly/folly/DynamicConverter.h