proxygen: folly::UnboundedQueue< T, SingleProducer, SingleConsumer, MayBlock, LgSegmentSize, LgAlign, Atom >::Consumer Struct Reference
folly::UnboundedQueue< T, SingleProducer, SingleConsumer, MayBlock, LgSegmentSize, LgAlign, Atom >::Consumer Struct Reference
Public Member Functions
Consumer (Segment *s)
Public Attributes
Atom< Segment * > head
Atom< Ticket > ticket
Detailed Description
template<typename T, bool SingleProducer, bool SingleConsumer, bool MayBlock, size_t LgSegmentSize = 8, size_t LgAlign = constexpr_log2(hardware_destructive_interference_size), template< typename > class Atom = std::atomic>
struct folly::UnboundedQueue< T, SingleProducer, SingleConsumer, MayBlock, LgSegmentSize, LgAlign, Atom >::Consumer
Definition at line 233 of file UnboundedQueue.h.
Constructor & Destructor Documentation
template<typename T, bool SingleProducer, bool SingleConsumer, bool MayBlock, size_t LgSegmentSize = 8, size_t LgAlign = constexpr_log2(hardware_destructive_interference_size), template< typename > class Atom = std::atomic> folly::UnboundedQueue< T, SingleProducer, SingleConsumer, MayBlock, LgSegmentSize, LgAlign, Atom >::Consumer::Consumer (Segment * s) inline explicit
Definition at line 236 of file UnboundedQueue.h.
 : head(s), ticket(0) {}
Member Data Documentation
template<typename T, bool SingleProducer, bool SingleConsumer, bool MayBlock, size_t LgSegmentSize = 8, size_t LgAlign = constexpr_log2(hardware_destructive_interference_size), template< typename > class Atom = std::atomic> Atom<Segment*> folly::UnboundedQueue< T, SingleProducer, SingleConsumer, MayBlock, LgSegmentSize, LgAlign, Atom >::Consumer::head
Definition at line 234 of file UnboundedQueue.h.
Referenced by folly::UnboundedQueue< T, false, 6 >::advanceHeadToTicket(), folly::UnboundedQueue< T, false, 6 >::casHead(), folly::UnboundedQueue< T, false, 6 >::cleanUpRemainingItems(), folly::UnboundedQueue< T, false, 6 >::dequeueImpl(), folly::UnboundedQueue< T, false, 6 >::head(), folly::UnboundedQueue< T, false, 6 >::reclaimRemainingSegments(), folly::UnboundedQueue< T, false, 6 >::setHead(), folly::UnboundedQueue< T, false, 6 >::tryDequeueUntil(), and folly::UnboundedQueue< T, false, 6 >::tryPeekUntil().
template<typename T, bool SingleProducer, bool SingleConsumer, bool MayBlock, size_t LgSegmentSize = 8, size_t LgAlign = constexpr_log2(hardware_destructive_interference_size), template< typename > class Atom = std::atomic> Atom<Ticket> folly::UnboundedQueue< T, SingleProducer, SingleConsumer, MayBlock, LgSegmentSize, LgAlign, Atom >::Consumer::ticket
Definition at line 235 of file UnboundedQueue.h.
Referenced by folly::UnboundedQueue< T, false, 6 >::consumerTicket(), folly::UnboundedQueue< T, false, 6 >::fetchIncrementConsumerTicket(), folly::UnboundedQueue< T, false, 6 >::setConsumerTicket(), and folly::UnboundedQueue< T, false, 6 >::tryDequeueUntilMC().
The documentation for this struct was generated from the following file:
proxygen/folly/folly/concurrency/UnboundedQueue.h