proxygen: ShardedAtomicInt Struct Reference
ShardedAtomicInt Struct Reference
Public Member Functions
void inc (int64_t val=1)
int64_t readFast ()
int64_t readFull ()
Public Attributes
std::atomic< int64_t > ints_ [kBuckets_]
Static Public Attributes
static const int64_t kBuckets_ = 2048
Detailed Description
Definition at line 303 of file ThreadCachedIntTest.cpp.
Member Function Documentation
void ShardedAtomicInt::inc (int64_t val = 1) inline
Definition at line 307 of file ThreadCachedIntTest.cpp.
References folly::getCurrentThreadID(), folly::hash::twang_mix64(), and val.
{
     int buck = hash::twang_mix64(folly::getCurrentThreadID()) & (kBuckets_ - 1);
     std::atomic_fetch_add(&ints_[buck], val);
   }
int64_t ShardedAtomicInt::readFast () inline
Definition at line 313 of file ThreadCachedIntTest.cpp.
References FOR_EACH_RANGE, i, and int64_t.
Referenced by BENCHMARK().
                      {
     int64_t ret = 0;
     static const int numToRead = 8;
     FOR_EACH_RANGE (i, 0, numToRead) {
       ret += ints_[i].load(std::memory_order_relaxed);
     }
     return ret * (kBuckets_ / numToRead);
   }
int64_t ShardedAtomicInt::readFull () inline
Definition at line 323 of file ThreadCachedIntTest.cpp.
References i, and int64_t.
Referenced by BENCHMARK().
                      {
     int64_t ret = 0;
     for (auto& i : ints_) {
       // Fun fact - using memory_order_consume below reduces perf 30-40% in high
       // contention benchmarks.
       ret += i.load(std::memory_order_relaxed);
     }
     return ret;
   }
Member Data Documentation
std::atomic<int64_t> ShardedAtomicInt::ints_[kBuckets_]
Definition at line 305 of file ThreadCachedIntTest.cpp.
const int64_t ShardedAtomicInt::kBuckets_ = 2048 static
Definition at line 304 of file ThreadCachedIntTest.cpp.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/test/ThreadCachedIntTest.cpp