proxygen: folly::pushmi::concepts::detail::Not< T > Struct Template Reference
folly::pushmi::concepts::detail::Not< T > Struct Template Reference
#include <concept_def.h>
Public Member Functions
constexpr operator bool () const noexcept
template<class This = Not, bool B, int(*) _pushmi_concept_unique___LINE__ = nullptr, std::enable_if_t< _pushmi_concept_unique___LINE__||bool(B==(bool) This{}), int > = 0>
constexpr operator std::integral_constant< bool, B > () const noexcept
constexpr auto operator! () const noexcept
template<class That >
constexpr auto operator&& (That) const noexcept
template<class That >
constexpr auto operator|| (That) const noexcept
Detailed Description
template<class T>
struct folly::pushmi::concepts::detail::Not< T >
Definition at line 460 of file concept_def.h.
Member Function Documentation
template<class T > constexpr folly::pushmi::concepts::detail::Not< T >::operator bool () const inline explicit noexcept
Definition at line 461 of file concept_def.h.
References folly::pushmi::PUSHMI_TEMPLATE(), and folly::T.
{
     return !(bool)T{};
   }
template<class T > template<class This = Not, bool B, int(*) _pushmi_concept_unique___LINE__ = nullptr, std::enable_if_t< _pushmi_concept_unique___LINE__||bool(B==(bool) This{}), int > = 0> constexpr folly::pushmi::concepts::detail::Not< T >::operator std::integral_constant< bool, B > () const inline noexcept
Definition at line 465 of file concept_def.h.
References folly::pushmi::__adl::noexcept().
                            {}) constexpr
   operator std::integral_constant<bool, B>() const noexcept {
     return {};
template<class T > constexpr auto folly::pushmi::concepts::detail::Not< T >::operator! () const inline noexcept
Definition at line 468 of file concept_def.h.
References folly::T.
Referenced by folly::pushmi::concepts::detail::And< T, U >::operator!(), and folly::pushmi::concepts::detail::Or< T, U >::operator!().
{
     return T{};
template<class T > template<class That > constexpr auto folly::pushmi::concepts::detail::Not< T >::operator&& (That) const inline noexcept
Definition at line 472 of file concept_def.h.
Referenced by folly::pushmi::concepts::detail::Or< T, U >::operator&&().
{
     return And<Not, That>{};
template<class T > template<class That > constexpr auto folly::pushmi::concepts::detail::Not< T >::operator|| (That) const inline noexcept
Definition at line 476 of file concept_def.h.
Referenced by folly::pushmi::concepts::detail::Or< T, U >::operator||().
{
     return Or<Not, That>{};
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/pushmi/detail/concept_def.h