proxygen: folly::pushmi::subject< PS, TN... >::subject_shared Struct Reference
folly::pushmi::subject< PS, TN... >::subject_shared Struct Reference
#include <subject.h>
Public Types
using receiver_t = any_receiver< std::exception_ptr, TN... >
Public Member Functions
requires Receiver< Out > void submit (Out out)
requires And< SemiMovable< VN >... > void value (VN &&...vn)
requires SemiMovable< E > void error (E e) noexcept
void done ()
Public Attributes
bool done_ = false
::folly::pushmi::detail::opt< std::tuple< std::decay_t< TN >... > > t_
std::exception_ptr ep_
std::vector< receiver_t > receivers_
std::mutex lock_
Detailed Description
template<class PS, class... TN>
struct folly::pushmi::subject< PS, TN... >::subject_shared
Definition at line 35 of file subject.h.
Member Typedef Documentation
template<class PS , class... TN> using folly::pushmi::subject< PS, TN... >::subject_shared::receiver_t = any_receiver<std::exception_ptr, TN...>
Definition at line 36 of file subject.h.
Member Function Documentation
template<class PS , class... TN> void folly::pushmi::subject< PS, TN... >::subject_shared::done () inline
Definition at line 86 of file subject.h.
References folly::gen::guard(), and folly::pushmi::set_done.
                 {
       std::unique_lock<std::mutex> guard(lock_);
       done_ = true;
       for (auto& out : receivers_) {
         set_done(out);
       }
       receivers_.clear();
     }
template<class PS , class... TN> requires SemiMovable<E> void folly::pushmi::subject< PS, TN... >::subject_shared::error (E e) inline noexcept
Definition at line 78 of file subject.h.
References folly::gen::guard(), folly::gen::move, and folly::pushmi::set_error.
{
       std::unique_lock<std::mutex> guard(lock_);
       ep_ = e;
       for (auto& out : receivers_) {
         set_error(out, std::move(e));
       }
       receivers_.clear();
     }
template<class PS , class... TN> requires Receiver<Out> void folly::pushmi::subject< PS, TN... >::subject_shared::submit (Out out) inline
Definition at line 44 of file subject.h.
References folly::apply(), folly::gen::guard(), folly::gen::move, folly::pushmi::PUSHMI_TEMPLATE(), folly::pushmi::requires(), folly::pushmi::set_done, folly::pushmi::set_error, and folly::pushmi::set_value.
{
       std::unique_lock<std::mutex> guard(lock_);
       if (ep_) {
         set_error(out, ep_);
         return;
       }
       if (!!t_) {
         auto args = *t_;
         ::folly::pushmi::apply(
             ::folly::pushmi::set_value,
             std::tuple_cat(std::tuple<Out>{std::move(out)}, std::move(args)));
         return;
       }
       if (done_) {
         set_done(out);
         return;
       }
       receivers_.push_back(receiver_t{out});
     }
template<class PS , class... TN> requires And<SemiMovable<VN>...> void folly::pushmi::subject< PS, TN... >::subject_shared::value (VN &&... vn) inline
Definition at line 65 of file subject.h.
References folly::apply(), folly::pushmi::detail::as_const, folly::gen::guard(), std::tr1::make_tuple(), folly::pushmi::PUSHMI_TEMPLATE(), folly::pushmi::requires(), and folly::pushmi::set_value.
{
       std::unique_lock<std::mutex> guard(lock_);
       for (auto& out : receivers_) {
         ::folly::pushmi::apply(
             ::folly::pushmi::set_value,
             std::tuple<decltype(out), std::decay_t<TN>...>{
                 out, detail::as_const(vn)...});
       }
       t_ = std::make_tuple((VN &&) vn...);
       receivers_.clear();
     }
Member Data Documentation
template<class PS , class... TN> bool folly::pushmi::subject< PS, TN... >::subject_shared::done_ = false
Definition at line 37 of file subject.h.
template<class PS , class... TN> std::exception_ptr folly::pushmi::subject< PS, TN... >::subject_shared::ep_
Definition at line 39 of file subject.h.
template<class PS , class... TN> std::mutex folly::pushmi::subject< PS, TN... >::subject_shared::lock_
Definition at line 41 of file subject.h.
template<class PS , class... TN> std::vector<receiver_t> folly::pushmi::subject< PS, TN... >::subject_shared::receivers_
Definition at line 40 of file subject.h.
template<class PS , class... TN> ::folly::pushmi::detail::opt<std::tuple<std::decay_t<TN>...> > folly::pushmi::subject< PS, TN... >::subject_shared::t_
Definition at line 38 of file subject.h.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/pushmi/subject.h