proxygen: inline_executor_flow_many Struct Reference
inline_executor_flow_many Struct Reference
Public Types
using properties = mi::property_set< mi::is_sender<>, mi::is_flow<>, mi::is_fifo_sequence<>, mi::is_maybe_blocking<>, mi::is_many<>>
Public Member Functions
inline_executor_flow_many ()
inline_executor_flow_many (std::atomic< int > &c)
auto executor ()
template<class Out >
void submit (Out out)
Public Attributes
std::atomic< int > * counter
Detailed Description
Definition at line 213 of file PushmiBenchmarks.cpp.
Member Typedef Documentation
using inline_executor_flow_many::properties = mi::property_set< mi::is_sender<>, mi::is_flow<>, mi::is_fifo_sequence<>, mi::is_maybe_blocking<>, mi::is_many<>>
Definition at line 224 of file PushmiBenchmarks.cpp.
Constructor & Destructor Documentation
inline_executor_flow_many::inline_executor_flow_many () inline
Definition at line 214 of file PushmiBenchmarks.cpp.
 : counter(nullptr) {}
inline_executor_flow_many::inline_executor_flow_many (std::atomic< int > & c) inline
Definition at line 215 of file PushmiBenchmarks.cpp.
 : counter(&c) {}
Member Function Documentation
auto inline_executor_flow_many::executor () inline
Definition at line 226 of file PushmiBenchmarks.cpp.
                   {
     return inline_time_executor{};
   }
template<class Out > void inline_executor_flow_many::submit (Out out) inline
Definition at line 230 of file PushmiBenchmarks.cpp.
References counter, folly::data(), MAKE, folly::gen::move, folly::pushmi::__adl::noexcept(), s, folly::pushmi::set_done, folly::pushmi::set_starting, folly::pushmi::set_value, and stop().
{
     // boolean cancellation
     struct producer {
       producer(Out out, bool s) : out(std::move(out)), stop(s) {}
       Out out;
       std::atomic<bool> stop;
     };
     auto p = std::make_shared<producer>(std::move(out), false);
     struct Data : mi::receiver<> {
       explicit Data(std::shared_ptr<producer> p) : p(std::move(p)) {}
       std::shared_ptr<producer> p;
     };
     auto up = mi::MAKE(receiver)(
         Data{p},
         [counter = this->counter](auto& data, auto requested) {
           if (requested < 1) {
             return;
           }
           // this is re-entrant
           while (!data.p->stop && --requested >= 0 &&
                  (!counter || --*counter >= 0)) {
             ::mi::set_value(
                 data.p->out,
                 !!counter ? inline_executor_flow_many{*counter}
                           : inline_executor_flow_many{});
           }
           if (!counter || *counter == 0) {
             ::mi::set_done(data.p->out);
           }
         },
         [](auto& data, auto e) noexcept {
           data.p->stop.store(true);
           ::mi::set_done(data.p->out);
         },
         [](auto& data) {
           data.p->stop.store(true);
           ::mi::set_done(data.p->out);
         });
     // pass reference for cancellation.
     ::mi::set_starting(p->out, std::move(up));
   }
Member Data Documentation
std::atomic<int>* inline_executor_flow_many::counter
Definition at line 217 of file PushmiBenchmarks.cpp.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/pushmi/benchmarks/PushmiBenchmarks.cpp