proxygen: Locker Struct Reference
Locker Struct Reference
Public Member Functions
template<typename T >
void lock (T *lockable)
template<typename T >
void unlock (T *lockable)
template<typename T >
void lock_shared (T *lockable)
template<typename T >
void unlock_shared (T *lockable)
Detailed Description
Definition at line 428 of file SharedMutexTest.cpp.
Member Function Documentation
template<typename T > void Locker::lock (T * lockable) inline
Definition at line 430 of file SharedMutexTest.cpp.
Referenced by runMixed().
{
     lockable->lock();
   }
template<typename T > void Locker::lock_shared (T * lockable) inline
Definition at line 440 of file SharedMutexTest.cpp.
Referenced by runContendedReaders(), and runMixed().
{
     lockable->lock_shared();
   }
template<typename T > void Locker::unlock (T * lockable) inline
Definition at line 435 of file SharedMutexTest.cpp.
Referenced by runMixed().
{
     lockable->unlock();
   }
template<typename T > void Locker::unlock_shared (T * lockable) inline
Definition at line 445 of file SharedMutexTest.cpp.
Referenced by runContendedReaders(), and runMixed().
{
     lockable->unlock_shared();
   }
The documentation for this struct was generated from the following file:
proxygen/folly/folly/test/SharedMutexTest.cpp