proxygen: folly::fbvector< T, Allocator >::Impl Struct Reference
folly::fbvector< T, Allocator >::Impl Struct Reference
Public Types
typedef A::pointer pointer
typedef A::size_type size_type
Public Member Functions
Impl ()
Impl (const Allocator &alloc)
Impl (Allocator &&alloc)
Impl (size_type n, const Allocator &alloc=Allocator())
Impl (Impl &&other) noexcept
~Impl ()
T * D_allocate (size_type n)
void D_deallocate (T *p, size_type n) noexcept
void swapData (Impl &other)
void destroy () noexcept
void init (size_type n)
void set (pointer newB, size_type newSize, size_type newCap)
void reset (size_type newCap)
void reset ()
Public Attributes
pointer b_
pointer e_
pointer z_
Detailed Description
template<class T, class Allocator>
struct folly::fbvector< T, Allocator >::Impl
Definition at line 84 of file FBVector.h.
Member Typedef Documentation
template<class T, class Allocator> typedef A::pointer folly::fbvector< T, Allocator >::Impl::pointer
Definition at line 86 of file FBVector.h.
template<class T, class Allocator> typedef A::size_type folly::fbvector< T, Allocator >::Impl::size_type
Definition at line 87 of file FBVector.h.
Constructor & Destructor Documentation
template<class T, class Allocator> folly::fbvector< T, Allocator >::Impl::Impl () inline
Definition at line 93 of file FBVector.h.
 : Allocator(), b_(nullptr), e_(nullptr), z_(nullptr) {}
template<class T, class Allocator> folly::fbvector< T, Allocator >::Impl::Impl (const Allocator & alloc) inline
Definition at line 94 of file FBVector.h.
         : Allocator(alloc), b_(nullptr), e_(nullptr), z_(nullptr) {}
template<class T, class Allocator> folly::fbvector< T, Allocator >::Impl::Impl (Allocator && alloc) inline
Definition at line 96 of file FBVector.h.
         : Allocator(std::move(alloc)), b_(nullptr), e_(nullptr), z_(nullptr) {}
template<class T, class Allocator> folly::fbvector< T, Allocator >::Impl::Impl (size_type n, const Allocator & alloc = Allocator()) inline
Definition at line 99 of file FBVector.h.
References folly::fbvector< T, Allocator >::Impl::init().
         : Allocator(alloc) {
       init(n);
     }
template<class T, class Allocator> folly::fbvector< T, Allocator >::Impl::Impl (Impl && other) inline noexcept
Definition at line 104 of file FBVector.h.
         : Allocator(std::move(other)),
           b_(other.b_),
           e_(other.e_),
           z_(other.z_) {
       other.b_ = other.e_ = other.z_ = nullptr;
     }
template<class T, class Allocator> folly::fbvector< T, Allocator >::Impl::~Impl () inline
Definition at line 113 of file FBVector.h.
References folly::fbvector< T, Allocator >::Impl::destroy().
             {
       destroy();
     }
Member Function Documentation
template<class T, class Allocator> T* folly::fbvector< T, Allocator >::Impl::D_allocate (size_type n) inline
Definition at line 119 of file FBVector.h.
References folly::checkedMalloc(), folly::T, and value.
Referenced by folly::fbvector< T, Allocator >::Impl::init().
{
       if (usingStdAllocator::value) {
         return static_cast<T*>(checkedMalloc(n * sizeof(T)));
       } else {
         return std::allocator_traits<Allocator>::allocate(*this, n);
       }
     }
template<class T, class Allocator> void folly::fbvector< T, Allocator >::Impl::D_deallocate (T * p, size_type n) inline noexcept
Definition at line 127 of file FBVector.h.
References bm::free(), and value.
Referenced by folly::fbvector< T, Allocator >::Impl::destroy().
{
       if (usingStdAllocator::value) {
         free(p);
       } else {
         std::allocator_traits<Allocator>::deallocate(*this, p, n);
       }
     }
template<class T, class Allocator> void folly::fbvector< T, Allocator >::Impl::destroy () inline noexcept
Definition at line 143 of file FBVector.h.
References folly::fbvector< T, Allocator >::Impl::D_deallocate(), folly::fbvector< T, Allocator >::S_destroy_range(), folly::fbvector< T, Allocator >::S_destroy_range_a(), and value.
Referenced by folly::fbvector< T, Allocator >::Impl::reset(), and folly::fbvector< T, Allocator >::Impl::~Impl().
{
       if (b_) {
         // THIS DISPATCH CODE IS DUPLICATED IN fbvector::D_destroy_range_a.
         // It has been inlined here for speed. It calls the static fbvector
         //  methods to perform the actual destruction.
         if (usingStdAllocator::value) {
           S_destroy_range(b_, e_);
         } else {
           S_destroy_range_a(*this, b_, e_);
         }
         D_deallocate(b_, size_type(z_ - b_));
       }
     }
template<class T, class Allocator> void folly::fbvector< T, Allocator >::Impl::init (size_type n) inline
Definition at line 158 of file FBVector.h.
References folly::fbvector< T, Allocator >::Impl::b_, folly::fbvector< T, Allocator >::Impl::D_allocate(), folly::goodMallocSize(), folly::T, and UNLIKELY.
Referenced by folly::fbvector< HTTPHeaderCode >::fbvector(), folly::fbvector< T, Allocator >::Impl::Impl(), and folly::fbvector< T, Allocator >::Impl::reset().
{
       if (UNLIKELY(n == 0)) {
         b_ = e_ = z_ = nullptr;
       } else {
         size_type sz = folly::goodMallocSize(n * sizeof(T)) / sizeof(T);
         b_ = D_allocate(sz);
         e_ = b_;
         z_ = b_ + sz;
       }
     }
template<class T, class Allocator> void folly::fbvector< T, Allocator >::Impl::reset (size_type newCap) inline
Definition at line 175 of file FBVector.h.
References folly::fbvector< T, Allocator >::Impl::destroy(), and folly::fbvector< T, Allocator >::Impl::init().
Referenced by folly::fbvector< HTTPHeaderCode >::assign(), folly::fbvector< HTTPHeaderCode >::moveFrom(), folly::fbvector< HTTPHeaderCode >::operator=(), and folly::fbvector< HTTPHeaderCode >::shrink_to_fit().
{
       destroy();
       try {
         init(newCap);
       } catch (...) {
         init(0);
         throw;
       }
     }
template<class T, class Allocator> void folly::fbvector< T, Allocator >::Impl::reset () inline
Definition at line 184 of file FBVector.h.
References folly::fbvector< T, Allocator >::Impl::destroy(), and folly::fbvector< T, Allocator >::impl_.
                  { // same as reset(0)
       destroy();
       b_ = e_ = z_ = nullptr;
     }
template<class T, class Allocator> void folly::fbvector< T, Allocator >::Impl::set (pointer newB, size_type newSize, size_type newCap) inline
Definition at line 169 of file FBVector.h.
Referenced by folly::fbvector< HTTPHeaderCode >::do_real_insert().
{
       z_ = newB + newCap;
       e_ = newB + newSize;
       b_ = newB;
     }
template<class T, class Allocator> void folly::fbvector< T, Allocator >::Impl::swapData (Impl & other) inline
Definition at line 136 of file FBVector.h.
References folly::fbvector< T, Allocator >::Impl::b_, folly::fbvector< T, Allocator >::Impl::e_, folly::swap(), and folly::fbvector< T, Allocator >::Impl::z_.
Referenced by folly::fbvector< HTTPHeaderCode >::fbvector(), folly::fbvector< HTTPHeaderCode >::moveFrom(), and folly::fbvector< HTTPHeaderCode >::swap().
{
       std::swap(b_, other.b_);
       std::swap(e_, other.e_);
       std::swap(z_, other.z_);
     }
Member Data Documentation
template<class T, class Allocator> pointer folly::fbvector< T, Allocator >::Impl::b_
Definition at line 90 of file FBVector.h.
Referenced by folly::fbvector< HTTPHeaderCode >::assign(), folly::fbvector< HTTPHeaderCode >::begin(), folly::fbvector< HTTPHeaderCode >::capacity(), folly::fbvector< HTTPHeaderCode >::cbegin(), folly::fbvector< HTTPHeaderCode >::clear(), folly::fbvector< HTTPHeaderCode >::data(), folly::fbvector< HTTPHeaderCode >::dataIsInternal(), folly::fbvector< HTTPHeaderCode >::do_real_insert(), folly::fbvector< T, Allocator >::emplace_back_aux(), folly::fbvector< HTTPHeaderCode >::empty(), folly::fbvector< HTTPHeaderCode >::front(), folly::fbvector< T, Allocator >::Impl::init(), folly::fbvector< HTTPHeaderCode >::insert(), folly::fbvector< HTTPHeaderCode >::M_relocate(), folly::fbvector< HTTPHeaderCode >::operator[](), folly::fbvector< HTTPHeaderCode >::reserve(), folly::fbvector< HTTPHeaderCode >::reserve_in_place(), folly::fbvector< HTTPHeaderCode >::resize(), folly::fbvector< HTTPHeaderCode >::shrink_to_fit(), folly::fbvector< HTTPHeaderCode >::size(), folly::fbvector< T, Allocator >::Impl::swapData(), and folly::fbvector< HTTPHeaderCode >::wrap_frame().
template<class T, class Allocator> pointer folly::fbvector< T, Allocator >::Impl::e_
Definition at line 90 of file FBVector.h.
Referenced by folly::fbvector< HTTPHeaderCode >::assign(), folly::fbvector< HTTPHeaderCode >::back(), folly::fbvector< HTTPHeaderCode >::cend(), folly::fbvector< HTTPHeaderCode >::dataIsInternal(), folly::fbvector< HTTPHeaderCode >::do_real_insert(), folly::fbvector< HTTPHeaderCode >::emplace_back(), folly::fbvector< T, Allocator >::emplace_back_aux(), folly::fbvector< HTTPHeaderCode >::empty(), folly::fbvector< HTTPHeaderCode >::end(), folly::fbvector< HTTPHeaderCode >::erase(), folly::fbvector< HTTPHeaderCode >::M_destroy_range_e(), folly::fbvector< HTTPHeaderCode >::M_relocate(), folly::fbvector< HTTPHeaderCode >::M_uninitialized_copy_e(), folly::fbvector< HTTPHeaderCode >::M_uninitialized_fill_n_e(), folly::fbvector< HTTPHeaderCode >::M_uninitialized_move_e(), folly::fbvector< HTTPHeaderCode >::make_window(), folly::fbvector< HTTPHeaderCode >::pop_back(), folly::fbvector< HTTPHeaderCode >::push_back(), folly::fbvector< HTTPHeaderCode >::reserve(), folly::fbvector< HTTPHeaderCode >::shrink_to_fit(), folly::fbvector< HTTPHeaderCode >::size(), folly::fbvector< T, Allocator >::Impl::swapData(), folly::fbvector< HTTPHeaderCode >::undo_window(), and folly::fbvector< HTTPHeaderCode >::wrap_frame().
template<class T, class Allocator> pointer folly::fbvector< T, Allocator >::Impl::z_
Definition at line 90 of file FBVector.h.
Referenced by folly::fbvector< HTTPHeaderCode >::capacity(), folly::fbvector< HTTPHeaderCode >::emplace_back(), folly::fbvector< T, Allocator >::emplace_back_aux(), folly::fbvector< HTTPHeaderCode >::push_back(), folly::fbvector< HTTPHeaderCode >::reserve(), folly::fbvector< HTTPHeaderCode >::reserve_in_place(), folly::fbvector< HTTPHeaderCode >::shrink_to_fit(), and folly::fbvector< T, Allocator >::Impl::swapData().
The documentation for this struct was generated from the following file:
proxygen/folly/folly/FBVector.h