proxygen: folly::detail::IntegralSizePolicy< SizeType, false > Struct Template Reference
folly::detail::IntegralSizePolicy< SizeType, false > Struct Template Reference
#include <small_vector.h>
Public Member Functions
template<class T >
void moveToUninitialized (T *, T *, T *)
template<class T , class EmplaceFunc >
void moveToUninitializedEmplace (T *, T *, T *, SizeType, EmplaceFunc &&)
Public Member Functions inherited from folly::detail::IntegralSizePolicyBase< SizeType, false >
IntegralSizePolicyBase ()
Additional Inherited Members
Public Types inherited from folly::detail::IntegralSizePolicyBase< SizeType, false >
typedef SizeType InternalSizeType
Protected Member Functions inherited from folly::detail::IntegralSizePolicyBase< SizeType, false >
std::size_t doSize () const
std::size_t isExtern () const
void setExtern (bool b)
void setSize (std::size_t sz)
void swapSizePolicy (IntegralSizePolicyBase &o)
Static Protected Member Functions inherited from folly::detail::IntegralSizePolicyBase< SizeType, false >
static constexpr std::size_t policyMaxSize ()
Static Protected Attributes inherited from folly::detail::IntegralSizePolicyBase< SizeType, false >
static bool constexpr kShouldUseHeap
Detailed Description
template<class SizeType>
struct folly::detail::IntegralSizePolicy< SizeType, false >
Definition at line 294 of file small_vector.h.
Member Function Documentation
template<class SizeType > template<class T > void folly::detail::IntegralSizePolicy< SizeType, false >::moveToUninitialized (T * , T * , T *) inline
Definition at line 298 of file small_vector.h.
References folly::fbstring_detail::assume_unreachable().
{
     assume_unreachable();
   }
template<class SizeType > template<class T , class EmplaceFunc > void folly::detail::IntegralSizePolicy< SizeType, false >::moveToUninitializedEmplace (T * , T * , T * , SizeType , EmplaceFunc &&) inline
Definition at line 302 of file small_vector.h.
References folly::fbstring_detail::assume_unreachable(), and testing::Value().
{
     assume_unreachable();
   }
The documentation for this struct was generated from the following file:
proxygen/folly/folly/small_vector.h