proxygen: folly::EvbAndContext Struct Reference
folly::EvbAndContext Struct Reference
Public Member Functions
EvbAndContext ()
std::shared_ptr< AsyncSSLSocket > createSocket ()
EventBase * getEventBase ()
void attach (AsyncSSLSocket &socket)
Public Attributes
folly::ScopedEventBaseThread evb_
std::shared_ptr< SSLContext > ctx_
Detailed Description
Definition at line 37 of file AsyncSSLSocketTest2.cpp.
Constructor & Destructor Documentation
folly::EvbAndContext::EvbAndContext () inline
Definition at line 38 of file AsyncSSLSocketTest2.cpp.
References ctx_.
                   {
     ctx_.reset(new SSLContext());
     ctx_->setOptions(SSL_OP_NO_TICKET);
     ctx_->ciphers("ALL:!ADH:!LOW:!EXP:!MD5:@STRENGTH");
   }
Member Function Documentation
void folly::EvbAndContext::attach (AsyncSSLSocket & socket) inline
Definition at line 52 of file AsyncSSLSocketTest2.cpp.
References folly::AsyncSSLSocket::attachEventBase(), ctx_, and getEventBase().
Referenced by folly::AttachDetachClient::connect(), and folly::AttachDetachClient::connectSuccess().
{
     socket.attachEventBase(getEventBase());
     socket.attachSSLContext(ctx_);
   }
std::shared_ptr<AsyncSSLSocket> folly::EvbAndContext::createSocket () inline
Definition at line 44 of file AsyncSSLSocketTest2.cpp.
References ctx_, getEventBase(), and folly::AsyncSSLSocket::newSocket().
Referenced by folly::AttachDetachClient::connect().
{
     return AsyncSSLSocket::newSocket(ctx_, getEventBase());
   }
EventBase* folly::EvbAndContext::getEventBase () inline
Definition at line 48 of file AsyncSSLSocketTest2.cpp.
References evb_, and folly::ScopedEventBaseThread::getEventBase().
Referenced by attach(), folly::AttachDetachClient::connect(), folly::AttachDetachClient::connectSuccess(), createSocket(), and folly::AttachDetachClient::readDataAvailable().
{
     return evb_.getEventBase();
   }
Member Data Documentation
std::shared_ptr<SSLContext> folly::EvbAndContext::ctx_
Definition at line 58 of file AsyncSSLSocketTest2.cpp.
Referenced by attach(), folly::AttachDetachClient::connect(), folly::AttachDetachClient::connectSuccess(), createSocket(), and EvbAndContext().
folly::ScopedEventBaseThread folly::EvbAndContext::evb_
Definition at line 57 of file AsyncSSLSocketTest2.cpp.
Referenced by getEventBase().
The documentation for this struct was generated from the following file:
proxygen/folly/folly/io/async/test/AsyncSSLSocketTest2.cpp