proxygen: folly::expected_detail::ExpectedStorage< Value, Error, StorageType::eUnion > Struct Template Reference
folly::expected_detail::ExpectedStorage< Value, Error, StorageType::eUnion > Struct Template Reference
#include <Expected.h>
Public Types
using value_type = Value
using error_type = Error
using Base = ExpectedUnion< Value, Error >
Public Member Functions
template<class E = Error, class = decltype(E{})>
constexpr ExpectedStorage () noexcept(noexcept(E{}))
ExpectedStorage (const ExpectedStorage &)=default
ExpectedStorage (ExpectedStorage &&)=default
ExpectedStorage & operator= (const ExpectedStorage &)=default
ExpectedStorage & operator= (ExpectedStorage &&)=default
~ExpectedStorage ()
void clear () noexcept
bool uninitializedByException () const noexcept
template<class... Vs>
void assignValue (Vs &&...vs)
template<class... Es>
void assignError (Es &&...es)
bool isSelfAssign (const ExpectedStorage *that) const
constexpr bool isSelfAssign (const void *) const
template<class Other >
void assign (Other &&that)
Public Member Functions inherited from folly::expected_detail::ExpectedUnion< Value, Error >
constexpr ExpectedUnion (EmptyTag) noexcept
template<class... Vs>
constexpr ExpectedUnion (ValueTag, Vs &&...vs) noexcept(noexcept(Value(static_cast< Vs && >(vs)...)))
template<class... Es>
constexpr ExpectedUnion (ErrorTag, Es &&...es) noexcept(noexcept(Error(static_cast< Es && >(es)...)))
ExpectedUnion (const ExpectedUnion &)
ExpectedUnion (ExpectedUnion &&) noexcept
ExpectedUnion & operator= (const ExpectedUnion &)
ExpectedUnion & operator= (ExpectedUnion &&) noexcept
~ExpectedUnion ()
Value & value ()&
const Value & value () const &
Value && value ()&&
Error & error ()&
const Error & error () const &
Error && error ()&&
Public Member Functions inherited from folly::expected_detail::CopyConstructible< ExpectedStorage< Value, Error, StorageType::eUnion >, StrictAllOf< std::is_copy_constructible, Value, Error >::value, StrictAllOf< std::is_nothrow_copy_constructible, Value, Error >::value >
constexpr CopyConstructible ()=default
CopyConstructible (const CopyConstructible &that) noexcept(Noexcept)
constexpr CopyConstructible (CopyConstructible &&)=default
CopyConstructible & operator= (const CopyConstructible &)=default
CopyConstructible & operator= (CopyConstructible &&)=default
Public Member Functions inherited from folly::expected_detail::MoveConstructible< ExpectedStorage< Value, Error, StorageType::eUnion >, StrictAllOf< std::is_move_constructible, Value, Error >::value, StrictAllOf< std::is_nothrow_move_constructible, Value, Error >::value >
constexpr MoveConstructible ()=default
constexpr MoveConstructible (const MoveConstructible &)=default
MoveConstructible (MoveConstructible &&that) noexcept(Noexcept)
MoveConstructible & operator= (const MoveConstructible &)=default
MoveConstructible & operator= (MoveConstructible &&)=default
Public Member Functions inherited from folly::expected_detail::CopyAssignable< ExpectedStorage< Value, Error, StorageType::eUnion >, StrictAllOf< IsCopyable, Value, Error >::value, StrictAllOf< IsNothrowCopyable, Value, Error >::value >
constexpr CopyAssignable ()=default
constexpr CopyAssignable (const CopyAssignable &)=default
constexpr CopyAssignable (CopyAssignable &&)=default
CopyAssignable & operator= (const CopyAssignable &that) noexcept(Noexcept)
CopyAssignable & operator= (CopyAssignable &&)=default
Public Member Functions inherited from folly::expected_detail::MoveAssignable< ExpectedStorage< Value, Error, StorageType::eUnion >, StrictAllOf< IsMovable, Value, Error >::value, StrictAllOf< IsNothrowMovable, Value, Error >::value >
constexpr MoveAssignable ()=default
constexpr MoveAssignable (const MoveAssignable &)=default
constexpr MoveAssignable (MoveAssignable &&)=default
MoveAssignable & operator= (const MoveAssignable &)=default
MoveAssignable & operator= (MoveAssignable &&that) noexcept(Noexcept)
Additional Inherited Members
Public Attributes inherited from folly::expected_detail::ExpectedUnion< Value, Error >
union {
Value value_
Error error_
char ch_ {}
};
Which which_ = Which::eEmpty
Detailed Description
template<class Value, class Error>
struct folly::expected_detail::ExpectedStorage< Value, Error, StorageType::eUnion >
Definition at line 394 of file Expected.h.
Member Typedef Documentation
template<class Value , class Error > using folly::expected_detail::ExpectedStorage< Value, Error, StorageType::eUnion >::Base = ExpectedUnion<Value, Error>
Definition at line 414 of file Expected.h.
template<class Value , class Error > using folly::expected_detail::ExpectedStorage< Value, Error, StorageType::eUnion >::error_type = Error
Definition at line 413 of file Expected.h.
template<class Value , class Error > using folly::expected_detail::ExpectedStorage< Value, Error, StorageType::eUnion >::value_type = Value
Definition at line 412 of file Expected.h.
Constructor & Destructor Documentation
template<class Value , class Error > template<class E = Error, class = decltype(E{})> constexpr folly::expected_detail::ExpectedStorage< Value, Error, StorageType::eUnion >::ExpectedStorage () inline noexcept
Definition at line 416 of file Expected.h.
 {})) : Base{ErrorTag{}} {}
template<class Value , class Error > folly::expected_detail::ExpectedStorage< Value, Error, StorageType::eUnion >::ExpectedStorage (const ExpectedStorage< Value, Error, StorageType::eUnion > &) default
template<class Value , class Error > folly::expected_detail::ExpectedStorage< Value, Error, StorageType::eUnion >::ExpectedStorage (ExpectedStorage< Value, Error, StorageType::eUnion > &&) default
template<class Value , class Error > folly::expected_detail::ExpectedStorage< Value, Error, StorageType::eUnion >::~ExpectedStorage () inline
Definition at line 422 of file Expected.h.
                      {
     clear();
   }
Member Function Documentation
template<class Value , class Error > template<class Other > void folly::expected_detail::ExpectedStorage< Value, Error, StorageType::eUnion >::assign (Other && that) inline
Definition at line 472 of file Expected.h.
References folly::expected_detail::eError, folly::pushmi::operators::error(), folly::expected_detail::eValue, and folly::value().
{
     if (isSelfAssign(&that)) {
       return;
     }
     switch (that.which_) {
       case Which::eValue:
         this->assignValue(static_cast<Other&&>(that).value());
         break;
       case Which::eError:
         this->assignError(static_cast<Other&&>(that).error());
         break;
       default:
         this->clear();
         break;
     }
   }
template<class Value , class Error > template<class... Es> void folly::expected_detail::ExpectedStorage< Value, Error, StorageType::eUnion >::assignError (Es &&... es) inline
Definition at line 454 of file Expected.h.
References folly::expected_detail::doEmplaceAssign(), folly::expected_detail::eError, and folly::pushmi::operators::error().
{
     if (this->which_ == Which::eError) {
       expected_detail::doEmplaceAssign(
           0, this->error(), static_cast<Es&&>(es)...);
     } else {
       this->clear();
       ::new ((void*)std::addressof(this->error()))
           Error(static_cast<Es&&>(es)...);
       this->which_ = Which::eError;
     }
   }
template<class Value , class Error > template<class... Vs> void folly::expected_detail::ExpectedStorage< Value, Error, StorageType::eUnion >::assignValue (Vs &&... vs) inline
Definition at line 442 of file Expected.h.
References folly::expected_detail::doEmplaceAssign(), folly::expected_detail::eValue, folly::value(), and testing::Value().
{
     if (this->which_ == Which::eValue) {
       expected_detail::doEmplaceAssign(
           0, this->value(), static_cast<Vs&&>(vs)...);
     } else {
       this->clear();
       ::new ((void*)std::addressof(this->value()))
           Value(static_cast<Vs&&>(vs)...);
       this->which_ = Which::eValue;
     }
   }
template<class Value , class Error > void folly::expected_detail::ExpectedStorage< Value, Error, StorageType::eUnion >::clear () inline noexcept
Definition at line 425 of file Expected.h.
References folly::expected_detail::eEmpty, folly::expected_detail::eError, folly::pushmi::operators::error(), folly::expected_detail::eValue, and folly::value().
{
     switch (this->which_) {
       case Which::eValue:
         this->value().~Value();
         break;
       case Which::eError:
         this->error().~Error();
         break;
       default:
         break;
     }
     this->which_ = Which::eEmpty;
   }
template<class Value , class Error > bool folly::expected_detail::ExpectedStorage< Value, Error, StorageType::eUnion >::isSelfAssign (const ExpectedStorage< Value, Error, StorageType::eUnion > * that) const inline
Definition at line 465 of file Expected.h.
{
     return this == that;
   }
template<class Value , class Error > constexpr bool folly::expected_detail::ExpectedStorage< Value, Error, StorageType::eUnion >::isSelfAssign (const void *) const inline
Definition at line 468 of file Expected.h.
{
     return false;
   }
template<class Value , class Error > ExpectedStorage& folly::expected_detail::ExpectedStorage< Value, Error, StorageType::eUnion >::operator= (const ExpectedStorage< Value, Error, StorageType::eUnion > &) default
template<class Value , class Error > ExpectedStorage& folly::expected_detail::ExpectedStorage< Value, Error, StorageType::eUnion >::operator= (ExpectedStorage< Value, Error, StorageType::eUnion > &&) default
template<class Value , class Error > bool folly::expected_detail::ExpectedStorage< Value, Error, StorageType::eUnion >::uninitializedByException () const inline noexcept
Definition at line 438 of file Expected.h.
References folly::expected_detail::eEmpty.
{
     return this->which_ == Which::eEmpty;
   }
The documentation for this struct was generated from the following file:
proxygen/folly/folly/Expected.h