proxygen: folly::IOBufCompare Struct Reference
folly::IOBufCompare Struct Reference
#include <IOBuf.h>
Public Member Functions
ordering operator() (const IOBuf &a, const IOBuf &b) const
ordering operator() (const std::unique_ptr< IOBuf > &a, const std::unique_ptr< IOBuf > &b) const
ordering operator() (const IOBuf *a, const IOBuf *b) const
Private Member Functions
ordering impl (IOBuf const &a, IOBuf const &b) const noexcept
Detailed Description
Ordering for IOBuf objects. Compares data in the entire chain.
Definition at line 1523 of file IOBuf.h.
Member Function Documentation
ordering folly::IOBufCompare::impl (IOBuf const & a, IOBuf const & b) const private noexcept
Definition at line 1108 of file IOBuf.cpp.
References a, b, folly::eq, min, folly::io::detail::CursorBase< Derived, BufType >::peekBytes(), folly::io::detail::CursorBase< Derived, BufType >::skip(), and folly::to_ordering().
{
   io::Cursor ca(&a);
   io::Cursor cb(&b);
   for (;;) {
     auto ba = ca.peekBytes();
     auto bb = cb.peekBytes();
     if (ba.empty() || bb.empty()) {
       return to_ordering(int(bb.empty()) - int(ba.empty()));
     }
     const size_t n = std::min(ba.size(), bb.size());
     DCHECK_GT(n, 0u);
     const ordering r = to_ordering(std::memcmp(ba.data(), bb.data(), n));
     if (r != ordering::eq) {
       return r;
     }
     // Cursor::skip() may throw if n is too large, but n is not too large here
     ca.skip(n);
     cb.skip(n);
   }
 }
ordering folly::IOBufCompare::operator() (const IOBuf & a, const IOBuf & b) const inline
Definition at line 1524 of file IOBuf.h.
{
     return &a == &b ? ordering::eq : impl(a, b);
   }
ordering folly::IOBufCompare::operator() (const std::unique_ptr< IOBuf > & a, const std::unique_ptr< IOBuf > & b) const inline
Definition at line 1527 of file IOBuf.h.
{
     return operator()(a.get(), b.get());
   }
ordering folly::IOBufCompare::operator() (const IOBuf * a, const IOBuf * b) const inline
Definition at line 1532 of file IOBuf.h.
References a, b, and folly::pushmi::__adl::noexcept().
{
     // clang-format off
     return
         !a && !b ? ordering::eq :
         !a && b ? ordering::lt :
         a && !b ? ordering::gt :
         operator()(*a, *b);
     // clang-format on
   }
The documentation for this struct was generated from the following files:
proxygen/folly/folly/io/IOBuf.h
proxygen/folly/folly/io/IOBuf.cpp