proxygen: folly::pushmi::detail::tap_ Struct Reference
folly::pushmi::detail::tap_ Struct Reference
#include <tap.h>
Public Types
using properties = properties_t< Out >
Public Member Functions
requires ReceiveValue< SideEffects, const std::remove_reference_t< VN >... > &&ReceiveValue< Out, std::remove_reference_t< VN >... > void value (VN &&...vn)
requires ReceiveError< SideEffects, const E > &&ReceiveError< Out, E > void error (E e) noexcept
void done ()
requires FlowReceiver< SideEffects > &&FlowReceiver< Out > void starting (Up &&up)
Public Attributes
SideEffects sideEffects
Out out
Detailed Description
Definition at line 28 of file tap.h.
Member Typedef Documentation
using folly::pushmi::detail::tap_::properties = properties_t<Out>
Definition at line 33 of file tap.h.
Member Function Documentation
void folly::pushmi::detail::tap_::done () inline
Definition at line 51 of file tap.h.
References folly::pushmi::detail::PUSHMI_TEMPLATE(), folly::pushmi::detail::requires(), and folly::pushmi::set_done.
               {
     set_done(sideEffects);
     set_done(out);
   }
requires ReceiveError<SideEffects, const E>&& ReceiveError<Out, E> void folly::pushmi::detail::tap_::error (E e) inline noexcept
Definition at line 47 of file tap.h.
References folly::pushmi::detail::as_const, folly::gen::move, and folly::pushmi::set_error.
{
     set_error(sideEffects, as_const(e));
     set_error(out, std::move(e));
   }
requires FlowReceiver<SideEffects>&& FlowReceiver<Out> void folly::pushmi::detail::tap_::starting (Up && up) inline
Definition at line 57 of file tap.h.
References folly::pushmi::set_starting.
                {
     // up is not made const because sideEffects is allowed to call methods on up
     set_starting(sideEffects, up);
     set_starting(out, (Up &&) up);
   }
requires ReceiveValue<SideEffects, const std::remove_reference_t<VN>...>&& ReceiveValue< Out, std::remove_reference_t<VN>...> void folly::pushmi::detail::tap_::value (VN &&... vn) inline
Definition at line 40 of file tap.h.
References folly::pushmi::detail::as_const, folly::pushmi::detail::PUSHMI_TEMPLATE(), folly::pushmi::detail::requires(), and folly::pushmi::set_value.
{
     set_value(sideEffects, as_const(vn)...);
     set_value(out, (VN &&) vn...);
   }
Member Data Documentation
Out folly::pushmi::detail::tap_::out
Definition at line 30 of file tap.h.
SideEffects folly::pushmi::detail::tap_::sideEffects
Definition at line 29 of file tap.h.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/pushmi/o/tap.h