proxygen: folly::exception_wrapper::ExceptionPtr Struct Reference
folly::exception_wrapper::ExceptionPtr Struct Reference
Public Member Functions
bool has_exception_ () const
std::exception const * as_exception_ () const
std::type_info const * as_type_ () const
Static Public Member Functions
static std::uintptr_t as_int_ (std::exception_ptr const &ptr, std::exception const &e) noexcept
static std::uintptr_t as_int_ (std::exception_ptr const &ptr, AnyException e) noexcept
static void copy_ (exception_wrapper const *from, exception_wrapper *to)
static void move_ (exception_wrapper *from, exception_wrapper *to)
static void delete_ (exception_wrapper *that)
static void throw_ (exception_wrapper const *that)
static std::type_info const * type_ (exception_wrapper const *that)
static std::exception const * get_exception_ (exception_wrapper const *that)
static exception_wrapper get_exception_ptr_ (exception_wrapper const *that)
Public Attributes
std::exception_ptr ptr_
std::uintptr_t exception_or_type_
Static Public Attributes
static VTable const ops_
Detailed Description
Definition at line 256 of file ExceptionWrapper.h.
Member Function Documentation
std::exception const * folly::exception_wrapper::ExceptionPtr::as_exception_ () const inline
Definition at line 138 of file ExceptionWrapper-inl.h.
References upload::const.
Referenced by get_exception_().
           {
   return reinterpret_cast<std::exception const*>(exception_or_type_);
 }
std::uintptr_t folly::exception_wrapper::ExceptionPtr::as_int_ (std::exception_ptr const & ptr, std::exception const & e) inline static noexcept
Definition at line 99 of file ExceptionWrapper-inl.h.
References upload::const, folly::FOLLY_PACK_ATTR, FOLLY_PACK_PUSH, folly::kMicrosoftAbiVer, and ptr.
Referenced by folly::exception_wrapper::exception_wrapper().
{
   if (!kMicrosoftAbiVer) {
     return reinterpret_cast<std::uintptr_t>(&e);
   } else {
     // On Windows, as of MSVC2017, all thrown exceptions are copied to the stack
     // first. Thus, we cannot depend on exception references associated with an
     // exception_ptr to be live for the duration of the exception_ptr. We need
     // to directly access the heap allocated memory inside the exception_ptr.
     //
     // std::exception_ptr is an opaque reinterpret_cast of
     // std::shared_ptr<__ExceptionPtr>
     // __ExceptionPtr is a non-virtual class with two members, a union and a
     // bool. The union contains the now-undocumented EHExceptionRecord, which
     // contains a struct which contains a void* which points to the heap
     // allocated exception.
     // We derive the offset to pExceptionObject via manual means.
     FOLLY_PACK_PUSH
     struct Win32ExceptionPtr {
       char offset[8 + 4 * sizeof(void*)];
       void* exceptionObject;
     } FOLLY_PACK_ATTR;
     FOLLY_PACK_POP
     auto* win32ExceptionPtr =
         reinterpret_cast<std::shared_ptr<Win32ExceptionPtr> const*>(&ptr)
             ->get();
     return reinterpret_cast<std::uintptr_t>(win32ExceptionPtr->exceptionObject);
   }
 }
std::uintptr_t folly::exception_wrapper::ExceptionPtr::as_int_ (std::exception_ptr const & ptr, AnyException e) inline static noexcept
Definition at line 130 of file ExceptionWrapper-inl.h.
{
   return reinterpret_cast<std::uintptr_t>(e.typeinfo_) + 1;
 }
std::type_info const * folly::exception_wrapper::ExceptionPtr::as_type_ () const inline
Definition at line 142 of file ExceptionWrapper-inl.h.
References upload::const.
Referenced by type_().
{
   return reinterpret_cast<std::type_info const*>(exception_or_type_ - 1);
 }
void folly::exception_wrapper::ExceptionPtr::copy_ (exception_wrapper const * from, exception_wrapper * to) inline static
Definition at line 146 of file ExceptionWrapper-inl.h.
References folly::exception_wrapper::eptr_.
{
   ::new (static_cast<void*>(&to->eptr_)) ExceptionPtr(from->eptr_);
 }
void folly::exception_wrapper::ExceptionPtr::delete_ (exception_wrapper * that) inline static
Definition at line 157 of file ExceptionWrapper-inl.h.
References folly::exception_wrapper::eptr_, folly::exception_wrapper::uninit_, and folly::exception_wrapper::vptr_.
{
   that->eptr_.~ExceptionPtr();
   that->vptr_ = &uninit_;
 }
std::exception const * folly::exception_wrapper::ExceptionPtr::get_exception_ (exception_wrapper const * that) inline static
Definition at line 172 of file ExceptionWrapper-inl.h.
References as_exception_(), folly::exception_wrapper::eptr_, and has_exception_().
{
   return that->eptr_.has_exception_() ? that->eptr_.as_exception_() : nullptr;
 }
exception_wrapper folly::exception_wrapper::ExceptionPtr::get_exception_ptr_ (exception_wrapper const * that) inline static
Definition at line 176 of file ExceptionWrapper-inl.h.
{
   return *that;
 }
bool folly::exception_wrapper::ExceptionPtr::has_exception_ () const inline
Definition at line 135 of file ExceptionWrapper-inl.h.
Referenced by get_exception_().
{
   return 0 == exception_or_type_ % 2;
 }
void folly::exception_wrapper::ExceptionPtr::move_ (exception_wrapper * from, exception_wrapper * to) inline static
Definition at line 151 of file ExceptionWrapper-inl.h.
References folly::exception_wrapper::eptr_, and folly::gen::move.
{
   ::new (static_cast<void*>(&to->eptr_)) ExceptionPtr(std::move(from->eptr_));
   delete_(from);
 }
void folly::exception_wrapper::ExceptionPtr::throw_ (exception_wrapper const * that) inline static
Definition at line 161 of file ExceptionWrapper-inl.h.
References folly::exception_wrapper::eptr_, and ptr_.
{
   std::rethrow_exception(that->eptr_.ptr_);
 }
std::type_info const * folly::exception_wrapper::ExceptionPtr::type_ (exception_wrapper const * that) inline static
Definition at line 165 of file ExceptionWrapper-inl.h.
References as_type_(), and folly::exception_wrapper::eptr_.
{
   if (auto e = get_exception_(that)) {
     return &typeid(*e);
   }
   return that->eptr_.as_type_();
 }
Member Data Documentation
std::uintptr_t folly::exception_wrapper::ExceptionPtr::exception_or_type_
Definition at line 258 of file ExceptionWrapper.h.
exception_wrapper::VTable const folly::exception_wrapper::ExceptionPtr::ops_ static
Initial value:
{
    copy_,
    move_,
    delete_,
    throw_,
    type_,
    get_exception_,
    get_exception_ptr_}
Definition at line 280 of file ExceptionWrapper.h.
Referenced by folly::exception_wrapper::exception_wrapper(), and folly::exception_wrapper::has_exception_ptr().
std::exception_ptr folly::exception_wrapper::ExceptionPtr::ptr_
Definition at line 257 of file ExceptionWrapper.h.
Referenced by folly::exception_wrapper::exception_wrapper(), throw_(), and folly::exception_wrapper::to_exception_ptr().
The documentation for this struct was generated from the following files:
proxygen/folly/folly/ExceptionWrapper.h
proxygen/folly/folly/ExceptionWrapper-inl.h
proxygen/folly/folly/ExceptionWrapper.cpp