proxygen: testing::gmock_matchers_test::PolymorphicFunctor Struct Reference
testing::gmock_matchers_test::PolymorphicFunctor Struct Reference
Public Types
typedef int result_type
typedef int result_type
typedef int result_type
Public Member Functions
int operator() (int n)
int operator() (const char *s)
int operator() (int n)
int operator() (const char *s)
int operator() (int n)
int operator() (const char *s)
Detailed Description
Definition at line 3926 of file gmock-matchers_test.cc.
Member Typedef Documentation
typedef int testing::gmock_matchers_test::PolymorphicFunctor::result_type
Definition at line 3927 of file gmock-matchers_test.cc.
typedef int testing::gmock_matchers_test::PolymorphicFunctor::result_type
Definition at line 3927 of file gmock-matchers_test.cc.
typedef int testing::gmock_matchers_test::PolymorphicFunctor::result_type
Definition at line 3927 of file gmock-matchers_test.cc.
Member Function Documentation
int testing::gmock_matchers_test::PolymorphicFunctor::operator() (int n) inline
Definition at line 3928 of file gmock-matchers_test.cc.
 { return n; }
int testing::gmock_matchers_test::PolymorphicFunctor::operator() (int n) inline
Definition at line 3928 of file gmock-matchers_test.cc.
 { return n; }
int testing::gmock_matchers_test::PolymorphicFunctor::operator() (int n) inline
Definition at line 3928 of file gmock-matchers_test.cc.
 { return n; }
int testing::gmock_matchers_test::PolymorphicFunctor::operator() (const char * s) inline
Definition at line 3929 of file gmock-matchers_test.cc.
References EXPECT_FALSE, EXPECT_TRUE, testing::Ge(), testing::internal::MatcherBase< T >::Matches(), testing::gmock_matchers_test::ReferencingFunction(), testing::ResultOf(), and testing::internal::TEST().
 { return static_cast<int>(strlen(s)); }
int testing::gmock_matchers_test::PolymorphicFunctor::operator() (const char * s) inline
Definition at line 3929 of file gmock-matchers_test.cc.
 { return static_cast<int>(strlen(s)); }
int testing::gmock_matchers_test::PolymorphicFunctor::operator() (const char * s) inline
Definition at line 3929 of file gmock-matchers_test.cc.
References EXPECT_FALSE, EXPECT_TRUE, testing::Ge(), testing::internal::MatcherBase< T >::Matches(), testing::gmock_matchers_test::ReferencingFunction(), testing::ResultOf(), and testing::internal::TEST().
 { return static_cast<int>(strlen(s)); }
The documentation for this struct was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-matchers_test.cc