proxygen: folly::pushmi::any_flow_receiver< PE, PV, E, VN >::vtable Struct Reference
folly::pushmi::any_flow_receiver< PE, PV, E, VN >::vtable Struct Reference
Static Public Member Functions
static void s_op (data &, data *)
static void s_done (data &)
static void s_error (data &, E) noexcept
static void s_value (data &, VN...)
static void s_starting (data &, any_receiver< PE, PV >)
Public Attributes
void(* op_)(data &, data *) = vtable::s_op
void(* done_)(data &) = vtable::s_done
void(* error_)(data &, E) noexcept = vtable::s_error
void(* value_)(data &, VN...) = vtable::s_value
void(* starting_)(data &, any_receiver< PE, PV >) = vtable::s_starting
Detailed Description
template<class PE, class PV, class E, class... VN>
struct folly::pushmi::any_flow_receiver< PE, PV, E, VN >::vtable
Definition at line 36 of file flow_receiver.h.
Member Function Documentation
template<class PE, class PV, class E, class... VN> static void folly::pushmi::any_flow_receiver< PE, PV, E, VN >::vtable::s_done (data &) inline static
Definition at line 38 of file flow_receiver.h.
 {}
template<class PE, class PV, class E, class... VN> static void folly::pushmi::any_flow_receiver< PE, PV, E, VN >::vtable::s_error (data & , E) inline static noexcept
Definition at line 39 of file flow_receiver.h.
 { std::terminate(); }
template<class PE, class PV, class E, class... VN> static void folly::pushmi::any_flow_receiver< PE, PV, E, VN >::vtable::s_op (data & , data *) inline static
Definition at line 37 of file flow_receiver.h.
 {}
template<class PE, class PV, class E, class... VN> static void folly::pushmi::any_flow_receiver< PE, PV, E, VN >::vtable::s_starting (data & , any_receiver< PE, PV >) inline static
Definition at line 41 of file flow_receiver.h.
 {}
template<class PE, class PV, class E, class... VN> static void folly::pushmi::any_flow_receiver< PE, PV, E, VN >::vtable::s_value (data & , VN...) inline static
Definition at line 40 of file flow_receiver.h.
 {}
Member Data Documentation
template<class PE, class PV, class E, class... VN> void(* folly::pushmi::any_flow_receiver< PE, PV, E, VN >::vtable::done_) (data &) = vtable::s_done
Definition at line 43 of file flow_receiver.h.
Referenced by folly::pushmi::any_flow_receiver< PE, PV, E, VN >::done().
template<class PE, class PV, class E, class... VN> void(* folly::pushmi::any_flow_receiver< PE, PV, E, VN >::vtable::error_) (data &, E) noexcept = vtable::s_error noexcept
Definition at line 44 of file flow_receiver.h.
Referenced by folly::pushmi::any_flow_receiver< PE, PV, E, VN >::error().
template<class PE, class PV, class E, class... VN> void(* folly::pushmi::any_flow_receiver< PE, PV, E, VN >::vtable::op_) (data &, data *) = vtable::s_op
Definition at line 42 of file flow_receiver.h.
Referenced by folly::pushmi::any_flow_receiver< PE, PV, E, VN >::any_flow_receiver(), and folly::pushmi::any_flow_receiver< PE, PV, E, VN >::~any_flow_receiver().
template<class PE, class PV, class E, class... VN> void(* folly::pushmi::any_flow_receiver< PE, PV, E, VN >::vtable::starting_) (data &, any_receiver< PE, PV >) = vtable::s_starting
Definition at line 46 of file flow_receiver.h.
Referenced by folly::pushmi::any_flow_receiver< PE, PV, E, VN >::starting().
template<class PE, class PV, class E, class... VN> void(* folly::pushmi::any_flow_receiver< PE, PV, E, VN >::vtable::value_) (data &, VN...) = vtable::s_value
Definition at line 45 of file flow_receiver.h.
Referenced by folly::pushmi::any_flow_receiver< PE, PV, E, VN >::value().
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/pushmi/flow_receiver.h