proxygen: folly::pushmi::new_thread_executor Struct Reference
folly::pushmi::new_thread_executor Struct Reference
#include <new_thread.h>
Public Types
using properties = property_set< is_sender<>, is_executor<>, is_never_blocking<>, is_concurrent_sequence<>, is_single<>>
Public Member Functions
new_thread_executor executor ()
requires Receiver< Out > void submit (Out out)
Detailed Description
Definition at line 27 of file new_thread.h.
Member Typedef Documentation
using folly::pushmi::new_thread_executor::properties = property_set< is_sender<>, is_executor<>, is_never_blocking<>, is_concurrent_sequence<>, is_single<>>
Definition at line 33 of file new_thread.h.
Member Function Documentation
new_thread_executor folly::pushmi::new_thread_executor::executor () inline
Definition at line 35 of file new_thread.h.
References folly::pushmi::PUSHMI_TEMPLATE(), and folly::pushmi::requires().
{
     return {};
   }
requires Receiver<Out> void folly::pushmi::new_thread_executor::submit (Out out) inline
Definition at line 40 of file new_thread.h.
References folly::gen::move, submit, folly::pushmi::t, tr, and folly::pushmi::trampoline().
{
     std::thread t{[out = std::move(out)]() mutable {
       auto tr = ::folly::pushmi::trampoline();
       ::folly::pushmi::submit(tr, std::move(out));
     }};
     // pass ownership of thread to out
     t.detach();
   }
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/pushmi/new_thread.h