proxygen: folly::compression::instructions::Haswell Struct Reference
folly::compression::instructions::Haswell Struct Reference
#include <Instructions.h>
Static Public Member Functions
static bool supported (const folly::CpuId &cpuId={})
static FOLLY_ALWAYS_INLINE uint64_t blsr (uint64_t value)
static FOLLY_ALWAYS_INLINE uint64_t bextr (uint64_t value, uint32_t start, uint32_t length)
static FOLLY_ALWAYS_INLINE uint64_t bzhi (uint64_t value, uint32_t index)
Static Public Member Functions inherited from folly::compression::instructions::Nehalem
static bool supported (const folly::CpuId &cpuId={})
static FOLLY_ALWAYS_INLINE uint64_t popcount (uint64_t value)
Static Public Member Functions inherited from folly::compression::instructions::Default
static bool supported (const folly::CpuId &={})
static FOLLY_ALWAYS_INLINE uint64_t popcount (uint64_t value)
static FOLLY_ALWAYS_INLINE int ctz (uint64_t value)
static FOLLY_ALWAYS_INLINE int clz (uint64_t value)
static FOLLY_ALWAYS_INLINE uint64_t blsr (uint64_t value)
static FOLLY_ALWAYS_INLINE uint64_t bextr (uint64_t value, uint32_t start, uint32_t length)
static FOLLY_ALWAYS_INLINE uint64_t bzhi (uint64_t value, uint32_t index)
Detailed Description
Definition at line 104 of file Instructions.h.
Member Function Documentation
static FOLLY_ALWAYS_INLINE uint64_t folly::compression::instructions::Haswell::bextr (uint64_t value, uint32_t start, uint32_t length) inline static
Definition at line 123 of file Instructions.h.
References uint64_t.
Referenced by TEST().
{
 #if defined(__GNUC__) || defined(__clang__)
     // GCC and Clang won't inline the intrinsics.
     // Encode parameters in `pattern` where `pattern[0:7]` is `start` and
     // `pattern[8:15]` is `length`.
     // Ref: Intel Advanced Vector Extensions Programming Reference
     uint64_t pattern = start & 0xFF;
     pattern = pattern | ((length & 0xFF) << 8);
     uint64_t result;
     asm("bextrq %2, %1, %0" : "=r"(result) : "r"(value), "r"(pattern));
     return result;
 #else
     return _bextr_u64(value, start, length);
 #endif
   }
static FOLLY_ALWAYS_INLINE uint64_t folly::compression::instructions::Haswell::blsr (uint64_t value) inline static
Definition at line 109 of file Instructions.h.
References FOLLY_ALWAYS_INLINE, and uint64_t.
{
 // BMI1 is supported starting with Intel Haswell, AMD Piledriver.
 // BLSR combines two instructions into one and reduces register pressure.
 #if defined(__GNUC__) || defined(__clang__)
     // GCC and Clang won't inline the intrinsics.
     uint64_t result;
     asm("blsrq %1, %0" : "=r"(result) : "r"(value));
     return result;
 #else
     return _blsr_u64(value);
 #endif
   }
static FOLLY_ALWAYS_INLINE uint64_t folly::compression::instructions::Haswell::bzhi (uint64_t value, uint32_t index) inline static
Definition at line 139 of file Instructions.h.
References uint64_t.
{
 #if defined(__GNUC__) || defined(__clang__)
     // GCC and Clang won't inline the intrinsics.
     const uint64_t index64 = index;
     uint64_t result;
     asm("bzhiq %2, %1, %0" : "=r"(result) : "r"(value), "r"(index64));
     return result;
 #else
     return _bzhi_u64(value, index);
 #endif
   }
static bool folly::compression::instructions::Haswell::supported (const folly::CpuId & cpuId = {}) inline static
Definition at line 105 of file Instructions.h.
References folly::compression::instructions::Nehalem::supported().
Referenced by folly::compression::instructions::detect().
                                                   {}) {
     return Nehalem::supported(cpuId) && cpuId.bmi1() && cpuId.bmi2();
   }
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/Instructions.h