proxygen: fizz::test::TestMessages Struct Reference
fizz::test::TestMessages Struct Reference
#include <TestMessages.h>
Static Public Member Functions
template<typename T >
static void removeExtension (T &msg, ExtensionType ext)
static ClientHello clientHello ()
static void addPsk (ClientHello &chlo, uint32_t ticketAge=100000)
static ClientHello clientHelloPsk ()
static ClientHello clientHelloPskEarly ()
static HelloRetryRequest helloRetryRequest ()
static ServerHello serverHello ()
static ServerHello serverHelloPsk ()
static EndOfEarlyData endOfEarlyData ()
static EncryptedExtensions encryptedExt ()
static EncryptedExtensions encryptedExtEarly ()
static CertificateMsg certificate ()
static CompressedCertificate compressedCertificate ()
static CertificateVerify certificateVerify ()
static CertificateRequest certificateRequest ()
static Finished finished ()
static NewSessionTicket newSessionTicket ()
static AppData appData ()
static AppWrite appWrite ()
static EarlyAppWrite earlyAppWrite ()
static KeyUpdate keyUpdate (bool reqUpdate)
Detailed Description
Definition at line 19 of file TestMessages.h.
Member Function Documentation
static void fizz::test::TestMessages::addPsk (ClientHello & chlo, uint32_t ticketAge = 100000) inline static
Definition at line 70 of file TestMessages.h.
References fizz::PskBinder::binder, fizz::ClientPresharedKey::binders, folly::IOBuf::copyBuffer(), fizz::encodeExtension(), fizz::ClientHello::extensions, fizz::ClientPresharedKey::identities, folly::gen::move, fizz::PskIdentity::obfuscated_ticket_age, and fizz::PskIdentity::psk_identity.
Referenced by clientHelloPsk(), clientHelloPskEarly(), and fizz::server::test::TEST_F().
{
     ClientPresharedKey cpk;
     PskIdentity ident;
     ident.psk_identity = folly::IOBuf::copyBuffer("ident");
     ident.obfuscated_ticket_age = ticketAge;
     cpk.identities.push_back(std::move(ident));
     PskBinder binder;
     binder.binder = folly::IOBuf::copyBuffer("verifydata");
     cpk.binders.push_back(std::move(binder));
     chlo.extensions.push_back(encodeExtension(std::move(cpk)));
   }
static AppData fizz::test::TestMessages::appData () inline static
Definition at line 212 of file TestMessages.h.
References folly::IOBuf::copyBuffer().
Referenced by fizz::client::test::TEST_F(), and fizz::server::test::TEST_F().
{
     AppData appData(folly::IOBuf::copyBuffer("appdata"));
     return appData;
   }
static AppWrite fizz::test::TestMessages::appWrite () inline static
Definition at line 217 of file TestMessages.h.
References folly::IOBuf::copyBuffer(), and fizz::AppWrite::data.
Referenced by earlyAppWrite(), fizz::client::test::TEST_F(), and fizz::server::test::TEST_F().
{
     AppWrite appWrite;
     appWrite.data = folly::IOBuf::copyBuffer("appdata");
     return appWrite;
   }
static CertificateMsg fizz::test::TestMessages::certificate () inline static
Definition at line 158 of file TestMessages.h.
References fizz::CertificateMsg::certificate_request_context, folly::IOBuf::copyBuffer(), and fizz::HandshakeStruct< e, t >::originalEncoding.
Referenced by fizz::client::test::ClientProtocolTest::doFinishedFlow(), fizz::server::test::TEST_F(), and fizz::client::test::TEST_F().
{
     CertificateMsg certificate;
     certificate.certificate_request_context = folly::IOBuf::copyBuffer("");
     certificate.originalEncoding = folly::IOBuf::copyBuffer("certencoding");
     return certificate;
   }
static CertificateRequest fizz::test::TestMessages::certificateRequest () inline static
Definition at line 183 of file TestMessages.h.
References fizz::CertificateRequest::certificate_request_context, folly::IOBuf::copyBuffer(), fizz::ecdsa_secp256r1_sha256, fizz::encodeExtension(), fizz::CertificateRequest::extensions, folly::gen::move, fizz::HandshakeStruct< e, t >::originalEncoding, fizz::rsa_pss_sha256, and fizz::SignatureAlgorithms::supported_signature_algorithms.
Referenced by fizz::server::test::TEST_F(), and fizz::client::test::TEST_F().
{
     CertificateRequest cr;
     cr.certificate_request_context = folly::IOBuf::copyBuffer("");
     SignatureAlgorithms sigAlgs;
     sigAlgs.supported_signature_algorithms.push_back(
         SignatureScheme::ecdsa_secp256r1_sha256);
     sigAlgs.supported_signature_algorithms.push_back(
         SignatureScheme::rsa_pss_sha256);
     cr.extensions.push_back(encodeExtension(std::move(sigAlgs)));
     cr.originalEncoding = folly::IOBuf::copyBuffer("certrequestencoding");
     return cr;
   }
static CertificateVerify fizz::test::TestMessages::certificateVerify () inline static
Definition at line 175 of file TestMessages.h.
References fizz::CertificateVerify::algorithm, folly::IOBuf::copyBuffer(), fizz::ecdsa_secp256r1_sha256, fizz::HandshakeStruct< e, t >::originalEncoding, fizz::CertificateVerify::signature, and verify().
Referenced by fizz::client::test::ClientProtocolTest::doFinishedFlow(), fizz::server::test::TEST_F(), and fizz::client::test::TEST_F().
{
     CertificateVerify verify;
     verify.algorithm = SignatureScheme::ecdsa_secp256r1_sha256;
     verify.signature = folly::IOBuf::copyBuffer("signature");
     verify.originalEncoding = folly::IOBuf::copyBuffer("certverifyencoding");
     return verify;
   }
static ClientHello fizz::test::TestMessages::clientHello () inline static
Definition at line 26 of file TestMessages.h.
References alpn, chlo, fizz::ClientHello::cipher_suites, fizz::ClientKeyShare::client_shares, folly::IOBuf::copyBuffer(), folly::IOBuf::create(), fizz::ecdsa_secp256r1_sha256, fizz::encodeExtension(), fizz::ClientHello::extensions, fizz::KeyShareEntry::group, fizz::ServerName::hostname, fizz::KeyShareEntry::key_exchange, fizz::ClientHello::legacy_compression_methods, fizz::ClientHello::legacy_session_id, fizz::PskKeyExchangeModes::modes, folly::gen::move, fizz::ProtocolName::name, fizz::SupportedGroups::named_group_list, fizz::HandshakeStruct< e, t >::originalEncoding, fizz::ProtocolNameList::protocol_name_list, fizz::psk_dhe_ke, fizz::psk_ke, fizz::ClientHello::random, fizz::rsa_pss_sha256, fizz::secp256r1, fizz::ServerNameList::server_name_list, sni, fizz::SignatureAlgorithms::supported_signature_algorithms, fizz::test::TestProtocolVersion, fizz::TLS_AES_128_GCM_SHA256, fizz::TLS_AES_256_GCM_SHA384, fizz::SupportedVersions::versions, and fizz::x25519.
Referenced by clientHelloPsk(), clientHelloPskEarly(), fizz::server::test::AeadCookieCipherTest::getClientHello(), fizz::client::test::ClientProtocolTest::getDefaultClientHello(), and fizz::server::test::TEST_F().
{
     ClientHello chlo;
     chlo.cipher_suites.push_back(CipherSuite::TLS_AES_128_GCM_SHA256);
     chlo.cipher_suites.push_back(CipherSuite::TLS_AES_256_GCM_SHA384);
     chlo.random.fill(0x44);
     chlo.legacy_compression_methods.push_back(0x00);
     chlo.legacy_session_id = folly::IOBuf::create(0);
     SupportedVersions supportedVersions;
     supportedVersions.versions.push_back(TestProtocolVersion);
     chlo.extensions.push_back(encodeExtension(std::move(supportedVersions)));
     SupportedGroups supportedGroups;
     supportedGroups.named_group_list.push_back(NamedGroup::x25519);
     supportedGroups.named_group_list.push_back(NamedGroup::secp256r1);
     chlo.extensions.push_back(encodeExtension(std::move(supportedGroups)));
     ClientKeyShare keyShare;
     KeyShareEntry entry;
     entry.group = NamedGroup::x25519;
     entry.key_exchange = folly::IOBuf::copyBuffer("keyshare");
     keyShare.client_shares.push_back(std::move(entry));
     chlo.extensions.push_back(encodeExtension(std::move(keyShare)));
     SignatureAlgorithms sigAlgs;
     sigAlgs.supported_signature_algorithms.push_back(
         SignatureScheme::ecdsa_secp256r1_sha256);
     sigAlgs.supported_signature_algorithms.push_back(
         SignatureScheme::rsa_pss_sha256);
     chlo.extensions.push_back(encodeExtension(std::move(sigAlgs)));
     ServerNameList sni;
     ServerName sn;
     sn.hostname = folly::IOBuf::copyBuffer("www.hostname.com");
     sni.server_name_list.push_back(std::move(sn));
     chlo.extensions.push_back(encodeExtension(std::move(sni)));
     ProtocolNameList alpn;
     ProtocolName h2;
     h2.name = folly::IOBuf::copyBuffer("h2");
     alpn.protocol_name_list.push_back(std::move(h2));
     chlo.extensions.push_back(encodeExtension(std::move(alpn)));
     PskKeyExchangeModes modes;
     modes.modes.push_back(PskKeyExchangeMode::psk_dhe_ke);
     modes.modes.push_back(PskKeyExchangeMode::psk_ke);
     chlo.extensions.push_back(encodeExtension(std::move(modes)));
     chlo.originalEncoding = folly::IOBuf::copyBuffer("clienthelloencoding");
     return chlo;
   }
static ClientHello fizz::test::TestMessages::clientHelloPsk () inline static
Definition at line 82 of file TestMessages.h.
References addPsk(), chlo, and clientHello().
Referenced by fizz::server::test::TEST_F().
{
     auto chlo = clientHello();
     addPsk(chlo);
     return chlo;
   }
static ClientHello fizz::test::TestMessages::clientHelloPskEarly () inline static
Definition at line 88 of file TestMessages.h.
References addPsk(), chlo, clientHello(), and fizz::encodeExtension().
Referenced by fizz::server::test::TEST_F().
{
     auto chlo = clientHello();
     chlo.extensions.push_back(encodeExtension(ClientEarlyData()));
     addPsk(chlo);
     return chlo;
   }
static CompressedCertificate fizz::test::TestMessages::compressedCertificate () inline static
Definition at line 165 of file TestMessages.h.
References fizz::CompressedCertificate::algorithm, cc, fizz::CompressedCertificate::compressed_certificate_message, folly::IOBuf::copyBuffer(), fizz::HandshakeStruct< e, t >::originalEncoding, fizz::CompressedCertificate::uncompressed_length, and fizz::zlib.
Referenced by fizz::server::test::TEST_F(), and fizz::client::test::TEST_F().
{
     CompressedCertificate cc;
     cc.algorithm = CertificateCompressionAlgorithm::zlib;
     cc.uncompressed_length = 0x111111;
     cc.compressed_certificate_message =
         folly::IOBuf::copyBuffer("compressedcerts");
     cc.originalEncoding = folly::IOBuf::copyBuffer("compcertencoding");
     return cc;
   }
static EarlyAppWrite fizz::test::TestMessages::earlyAppWrite () inline static
Definition at line 223 of file TestMessages.h.
References appWrite(), folly::IOBuf::copyBuffer(), and fizz::EarlyAppWrite::data.
Referenced by fizz::client::test::TEST_F().
{
     EarlyAppWrite appWrite;
     appWrite.data = folly::IOBuf::copyBuffer("appdata");
     return appWrite;
   }
static EncryptedExtensions fizz::test::TestMessages::encryptedExt () inline static
Definition at line 141 of file TestMessages.h.
References alpn, folly::IOBuf::copyBuffer(), fizz::encodeExtension(), fizz::EncryptedExtensions::extensions, folly::gen::move, fizz::ProtocolName::name, fizz::HandshakeStruct< e, t >::originalEncoding, and fizz::ProtocolNameList::protocol_name_list.
Referenced by encryptedExtEarly(), fizz::server::test::TEST_F(), and fizz::client::test::TEST_F().
{
     EncryptedExtensions encryptedExt;
     ProtocolNameList alpn;
     ProtocolName h2;
     h2.name = folly::IOBuf::copyBuffer("h2");
     alpn.protocol_name_list.push_back(std::move(h2));
     encryptedExt.extensions.push_back(encodeExtension(std::move(alpn)));
     encryptedExt.originalEncoding = folly::IOBuf::copyBuffer("eeencoding");
     return encryptedExt;
   }
static EncryptedExtensions fizz::test::TestMessages::encryptedExtEarly () inline static
Definition at line 152 of file TestMessages.h.
References fizz::encodeExtension(), and encryptedExt().
Referenced by fizz::server::test::TEST_F().
{
     auto ee = encryptedExt();
     ee.extensions.push_back(encodeExtension(ServerEarlyData()));
     return ee;
   }
static EndOfEarlyData fizz::test::TestMessages::endOfEarlyData () inline static
Definition at line 135 of file TestMessages.h.
References folly::IOBuf::copyBuffer(), and fizz::HandshakeStruct< e, t >::originalEncoding.
Referenced by fizz::server::test::TEST_F().
{
     EndOfEarlyData eoed;
     eoed.originalEncoding = folly::IOBuf::copyBuffer("eoedencoding");
     return eoed;
   }
static Finished fizz::test::TestMessages::finished () inline static
Definition at line 196 of file TestMessages.h.
References folly::IOBuf::copyBuffer(), fizz::HandshakeStruct< e, t >::originalEncoding, and fizz::Finished::verify_data.
Referenced by fizz::client::test::ClientProtocolTest::doFinishedFlow(), fizz::server::test::TEST_F(), and fizz::client::test::TEST_F().
{
     Finished finished;
     finished.verify_data = folly::IOBuf::copyBuffer("verifydata");
     finished.originalEncoding = folly::IOBuf::copyBuffer("finishedencoding");
     return finished;
   }
static HelloRetryRequest fizz::test::TestMessages::helloRetryRequest () inline static
Definition at line 95 of file TestMessages.h.
References fizz::HelloRetryRequest::cipher_suite, folly::IOBuf::copyBuffer(), fizz::encodeExtension(), fizz::HelloRetryRequest::extensions, fizz::HelloRetryRequest::legacy_version, folly::gen::move, fizz::HandshakeStruct< e, t >::originalEncoding, fizz::secp256r1, fizz::HelloRetryRequestKeyShare::selected_group, fizz::ServerSupportedVersions::selected_version, fizz::test::TestProtocolVersion, fizz::tls_1_2, and fizz::TLS_AES_128_GCM_SHA256.
Referenced by fizz::client::test::TEST_F(), and fizz::server::test::TEST_F().
{
     HelloRetryRequest hrr;
     hrr.legacy_version = ProtocolVersion::tls_1_2;
     hrr.cipher_suite = CipherSuite::TLS_AES_128_GCM_SHA256;
     ServerSupportedVersions supportedVersions;
     supportedVersions.selected_version = TestProtocolVersion;
     hrr.extensions.push_back(encodeExtension(std::move(supportedVersions)));
     HelloRetryRequestKeyShare keyShare;
     keyShare.selected_group = NamedGroup::secp256r1;
     hrr.extensions.push_back(encodeExtension(std::move(keyShare)));
     hrr.originalEncoding = folly::IOBuf::copyBuffer("hrrencoding");
     return hrr;
   }
static KeyUpdate fizz::test::TestMessages::keyUpdate (bool reqUpdate) inline static
Definition at line 229 of file TestMessages.h.
References fizz::KeyUpdate::request_update, fizz::update_not_requested, and fizz::update_requested.
Referenced by fizz::client::test::TEST_F(), and fizz::server::test::TEST_F().
{
     KeyUpdate keyUpdate;
     keyUpdate.request_update = reqUpdate
         ? KeyUpdateRequest::update_requested
         : KeyUpdateRequest::update_not_requested;
     return keyUpdate;
   }
static NewSessionTicket fizz::test::TestMessages::newSessionTicket () inline static
Definition at line 203 of file TestMessages.h.
References folly::IOBuf::copyBuffer(), folly::IOBuf::create(), nst, fizz::NewSessionTicket::ticket, fizz::NewSessionTicket::ticket_age_add, fizz::NewSessionTicket::ticket_lifetime, and fizz::NewSessionTicket::ticket_nonce.
Referenced by fizz::client::test::TEST_F(), and fizz::server::test::TEST_F().
{
     NewSessionTicket nst;
     nst.ticket_lifetime = 100;
     nst.ticket_age_add = 0x44444444;
     nst.ticket_nonce = folly::IOBuf::create(0);
     nst.ticket = folly::IOBuf::copyBuffer("ticket");
     return nst;
   }
template<typename T > static void fizz::test::TestMessages::removeExtension (T & msg, ExtensionType ext) inline static
Definition at line 21 of file TestMessages.h.
References fizz::findExtension().
Referenced by fizz::server::test::TEST_F(), and fizz::client::test::TEST_F().
{
     auto it = findExtension(msg.extensions, ext);
     msg.extensions.erase(it);
   }
static ServerHello fizz::test::TestMessages::serverHello () inline static
Definition at line 109 of file TestMessages.h.
References fizz::ServerHello::cipher_suite, folly::IOBuf::copyBuffer(), folly::IOBuf::create(), fizz::encodeExtension(), fizz::ServerHello::extensions, fizz::KeyShareEntry::group, fizz::KeyShareEntry::key_exchange, fizz::ServerHello::legacy_session_id_echo, fizz::ServerHello::legacy_version, folly::gen::move, fizz::HandshakeStruct< e, t >::originalEncoding, fizz::ServerHello::random, fizz::ServerSupportedVersions::selected_version, fizz::ServerKeyShare::server_share, fizz::test::TestProtocolVersion, fizz::tls_1_2, fizz::TLS_AES_128_GCM_SHA256, and fizz::x25519.
Referenced by serverHelloPsk(), fizz::server::test::TEST_F(), and fizz::client::test::TEST_F().
{
     ServerHello shlo;
     shlo.legacy_version = ProtocolVersion::tls_1_2;
     shlo.legacy_session_id_echo = folly::IOBuf::create(0);
     shlo.random.fill(0x44);
     shlo.cipher_suite = CipherSuite::TLS_AES_128_GCM_SHA256;
     ServerSupportedVersions supportedVersions;
     supportedVersions.selected_version = TestProtocolVersion;
     shlo.extensions.push_back(encodeExtension(std::move(supportedVersions)));
     ServerKeyShare serverKeyShare;
     serverKeyShare.server_share.group = NamedGroup::x25519;
     serverKeyShare.server_share.key_exchange =
         folly::IOBuf::copyBuffer("servershare");
     shlo.extensions.push_back(encodeExtension(std::move(serverKeyShare)));
     shlo.originalEncoding = folly::IOBuf::copyBuffer("shloencoding");
     return shlo;
   }
static ServerHello fizz::test::TestMessages::serverHelloPsk () inline static
Definition at line 127 of file TestMessages.h.
References fizz::encodeExtension(), folly::gen::move, fizz::ServerPresharedKey::selected_identity, and serverHello().
Referenced by fizz::client::test::TEST_F().
{
     auto shlo = serverHello();
     ServerPresharedKey pskExt;
     pskExt.selected_identity = 0;
     shlo.extensions.push_back(encodeExtension(std::move(pskExt)));
     return shlo;
   }
The documentation for this struct was generated from the following file:
proxygen/fizz/fizz/protocol/test/TestMessages.h