proxygen: testing::gmock_matchers_test::Type< T > Struct Template Reference
testing::gmock_matchers_test::Type< T > Struct Template Reference
Static Public Member Functions
static bool IsTypeOf (const T &)
template<typename T2 >
static void IsTypeOf (T2 v)
static bool IsTypeOf (const T &)
template<typename T2 >
static void IsTypeOf (T2 v)
static bool IsTypeOf (const T &)
template<typename T2 >
static void IsTypeOf (T2 v)
Detailed Description
template<typename T>
struct testing::gmock_matchers_test::Type< T >
Definition at line 919 of file gmock-matchers_test.cc.
Member Function Documentation
template<typename T> static bool testing::gmock_matchers_test::Type< T >::IsTypeOf (const T &) inline static
Definition at line 920 of file gmock-matchers_test.cc.
 { return true; }
template<typename T> static bool testing::gmock_matchers_test::Type< T >::IsTypeOf (const T &) inline static
Definition at line 920 of file gmock-matchers_test.cc.
References testing::_, testing::AllOf(), testing::gmock_matchers_test::AllOfMatches(), testing::AnyOf(), testing::gmock_matchers_test::AnyOfMatches(), testing::Contains(), testing::ContainsRegex(), testing::gmock_matchers_test::Describe(), testing::gmock_matchers_test::DescribeNegation(), testing::EndsWith(), testing::Eq(), EXPECT_EQ, EXPECT_FALSE, EXPECT_THAT, EXPECT_TRUE, testing::gmock_matchers_test::Explain(), testing::Ge(), testing::gmock_matchers_test::GreaterThan(), testing::Gt(), testing::HasSubstr(), i, folly::is_negative(), folly::is_positive(), testing::internal::IsNull(), testing::gmock_matchers_test::IsPositive(), testing::Key(), testing::Le(), testing::Lt(), m, testing::internal::MatcherBase< T >::Matches(), testing::MatchesRegex(), testing::Ne(), testing::Not(), testing::NotNull(), testing::Pair(), testing::Ref(), SCOPED_TRACE, testing::StartsWith(), testing::StrCaseEq(), testing::StrCaseNe(), testing::StrEq(), string, testing::StrNe(), and testing::internal::TEST().
 { return true; }
template<typename T> static bool testing::gmock_matchers_test::Type< T >::IsTypeOf (const T &) inline static
Definition at line 920 of file gmock-matchers_test.cc.
References testing::_, testing::AllOf(), testing::gmock_matchers_test::AllOfMatches(), testing::AnyOf(), testing::gmock_matchers_test::AnyOfMatches(), testing::Contains(), testing::ContainsRegex(), testing::gmock_matchers_test::Describe(), testing::gmock_matchers_test::DescribeNegation(), testing::EndsWith(), testing::Eq(), EXPECT_EQ, EXPECT_FALSE, EXPECT_THAT, EXPECT_TRUE, testing::gmock_matchers_test::Explain(), testing::Ge(), testing::gmock_matchers_test::GreaterThan(), testing::Gt(), testing::HasSubstr(), i, folly::is_negative(), folly::is_positive(), testing::internal::IsNull(), testing::gmock_matchers_test::IsPositive(), testing::Key(), testing::Le(), testing::Lt(), m, testing::internal::MatcherBase< T >::Matches(), testing::MatchesRegex(), testing::Ne(), testing::Not(), testing::NotNull(), testing::Pair(), testing::Ref(), SCOPED_TRACE, testing::StartsWith(), testing::StrCaseEq(), testing::StrCaseNe(), testing::StrEq(), string, testing::StrNe(), and testing::internal::TEST().
 { return true; }
template<typename T> template<typename T2 > static void testing::gmock_matchers_test::Type< T >::IsTypeOf (T2 v) static
template<typename T> template<typename T2 > static void testing::gmock_matchers_test::Type< T >::IsTypeOf (T2 v) static
template<typename T> template<typename T2 > static void testing::gmock_matchers_test::Type< T >::IsTypeOf (T2 v) static
The documentation for this struct was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googlemock/test/gmock-matchers_test.cc