proxygen: folly::expected_detail::ExpectedStorage< Value, Error, StorageType::ePODStruct > Struct Template Reference
folly::expected_detail::ExpectedStorage< Value, Error, StorageType::ePODStruct > Struct Template Reference
#include <Expected.h>
Public Types
using value_type = Value
using error_type = Error
Public Member Functions
constexpr ExpectedStorage () noexcept
constexpr ExpectedStorage (EmptyTag) noexcept
template<class... Vs>
constexpr ExpectedStorage (ValueTag, Vs &&...vs) noexcept(noexcept(Value(static_cast< Vs && >(vs)...)))
template<class... Es>
constexpr ExpectedStorage (ErrorTag, Es &&...es) noexcept(noexcept(Error(static_cast< Es && >(es)...)))
void clear () noexcept
template<class... Vs>
void assignValue (Vs &&...vs)
template<class... Es>
void assignError (Es &&...es)
template<class Other >
void assign (Other &&that)
Value & value ()&
const Value & value () const &
Value && value ()&&
FOLLY_PUSH_WARNING FOLLY_MSVC_DISABLE_WARNING (4702) Error &error()&
const Error & error () const &
Error && error ()&&
Static Public Member Functions
static constexpr bool uninitializedByException () noexcept
Public Attributes
Which which_
Error error_
Value value_
Detailed Description
template<class Value, class Error>
struct folly::expected_detail::ExpectedStorage< Value, Error, StorageType::ePODStruct >
Definition at line 492 of file Expected.h.
Member Typedef Documentation
template<class Value , class Error > using folly::expected_detail::ExpectedStorage< Value, Error, StorageType::ePODStruct >::error_type = Error
Definition at line 494 of file Expected.h.
template<class Value , class Error > using folly::expected_detail::ExpectedStorage< Value, Error, StorageType::ePODStruct >::value_type = Value
Definition at line 493 of file Expected.h.
Constructor & Destructor Documentation
template<class Value , class Error > constexpr folly::expected_detail::ExpectedStorage< Value, Error, StorageType::ePODStruct >::ExpectedStorage () inline noexcept
Definition at line 499 of file Expected.h.
       : which_(Which::eError), error_{}, value_{} {}
template<class Value , class Error > constexpr folly::expected_detail::ExpectedStorage< Value, Error, StorageType::ePODStruct >::ExpectedStorage (EmptyTag) inline explicit noexcept
Definition at line 501 of file Expected.h.
       : which_(Which::eEmpty), error_{}, value_{} {}
template<class Value , class Error > template<class... Vs> constexpr folly::expected_detail::ExpectedStorage< Value, Error, StorageType::ePODStruct >::ExpectedStorage (ValueTag , Vs &&... vs) inline explicit noexcept
Definition at line 504 of file Expected.h.
       : which_(Which::eValue), error_{}, value_(static_cast<Vs&&>(vs)...) {}
template<class Value , class Error > template<class... Es> constexpr folly::expected_detail::ExpectedStorage< Value, Error, StorageType::ePODStruct >::ExpectedStorage (ErrorTag , Es &&... es) inline explicit noexcept
Definition at line 508 of file Expected.h.
       : which_(Which::eError), error_(static_cast<Es&&>(es)...), value_{} {}
Member Function Documentation
template<class Value , class Error > template<class Other > void folly::expected_detail::ExpectedStorage< Value, Error, StorageType::ePODStruct >::assign (Other && that) inline
Definition at line 526 of file Expected.h.
References folly::expected_detail::eError, folly::pushmi::operators::error(), folly::expected_detail::eValue, and folly::value().
{
     switch (that.which_) {
       case Which::eValue:
         this->assignValue(static_cast<Other&&>(that).value());
         break;
       case Which::eError:
         this->assignError(static_cast<Other&&>(that).error());
         break;
       default:
         this->clear();
         break;
     }
   }
template<class Value , class Error > template<class... Es> void folly::expected_detail::ExpectedStorage< Value, Error, StorageType::ePODStruct >::assignError (Es &&... es) inline
Definition at line 521 of file Expected.h.
References folly::expected_detail::doEmplaceAssign(), and folly::expected_detail::eError.
{
     expected_detail::doEmplaceAssign(0, error_, static_cast<Es&&>(es)...);
     which_ = Which::eError;
   }
template<class Value , class Error > template<class... Vs> void folly::expected_detail::ExpectedStorage< Value, Error, StorageType::ePODStruct >::assignValue (Vs &&... vs) inline
Definition at line 516 of file Expected.h.
References folly::expected_detail::doEmplaceAssign(), and folly::expected_detail::eValue.
{
     expected_detail::doEmplaceAssign(0, value_, static_cast<Vs&&>(vs)...);
     which_ = Which::eValue;
   }
template<class Value , class Error > void folly::expected_detail::ExpectedStorage< Value, Error, StorageType::ePODStruct >::clear () inline noexcept
Definition at line 511 of file Expected.h.
 {}
template<class Value , class Error > const Error& folly::expected_detail::ExpectedStorage< Value, Error, StorageType::ePODStruct >::error () const inline
Definition at line 556 of file Expected.h.
{
     return error_;
   }
template<class Value , class Error > Error&& folly::expected_detail::ExpectedStorage< Value, Error, StorageType::ePODStruct >::error () inline
Definition at line 559 of file Expected.h.
References FOLLY_POP_WARNING, and folly::gen::move.
                      {
     return std::move(error_);
   }
template<class Value , class Error > FOLLY_PUSH_WARNING folly::expected_detail::ExpectedStorage< Value, Error, StorageType::ePODStruct >::FOLLY_MSVC_DISABLE_WARNING (4702) inline
Definition at line 552 of file Expected.h.
                    {
     return error_;
   }
template<class Value , class Error > static constexpr bool folly::expected_detail::ExpectedStorage< Value, Error, StorageType::ePODStruct >::uninitializedByException () inline static noexcept
Definition at line 512 of file Expected.h.
{
     return false;
   }
template<class Value , class Error > Value& folly::expected_detail::ExpectedStorage< Value, Error, StorageType::ePODStruct >::value () inline
Definition at line 539 of file Expected.h.
                    {
     return value_;
   }
template<class Value , class Error > const Value& folly::expected_detail::ExpectedStorage< Value, Error, StorageType::ePODStruct >::value () const inline
Definition at line 542 of file Expected.h.
{
     return value_;
   }
template<class Value , class Error > Value&& folly::expected_detail::ExpectedStorage< Value, Error, StorageType::ePODStruct >::value () inline
Definition at line 545 of file Expected.h.
References FOLLY_PUSH_WARNING, and folly::gen::move.
                      {
     return std::move(value_);
   }
Member Data Documentation
template<class Value , class Error > Error folly::expected_detail::ExpectedStorage< Value, Error, StorageType::ePODStruct >::error_
Definition at line 496 of file Expected.h.
template<class Value , class Error > Value folly::expected_detail::ExpectedStorage< Value, Error, StorageType::ePODStruct >::value_
Definition at line 497 of file Expected.h.
template<class Value , class Error > Which folly::expected_detail::ExpectedStorage< Value, Error, StorageType::ePODStruct >::which_
Definition at line 495 of file Expected.h.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/Expected.h