proxygen: AddressData Struct Reference
AddressData Struct Reference
Public Member Functions
AddressData (const std::string &address_, const ByteVector &bytes_, uint8_t version_)
AddressData (const std::string &address_, uint8_t version_)
AddressData (const std::string &address_)
AddressData ()
Static Public Member Functions
static in_addr parseAddress4 (const std::string &src)
static in6_addr parseAddress6 (const std::string &src)
Public Attributes
std::string address
ByteVector bytes
uint8_t version
Detailed Description
Definition at line 36 of file IPAddressTest.cpp.
Constructor & Destructor Documentation
AddressData::AddressData (const std::string & address_, const ByteVector & bytes_, uint8_t version_) inline
Definition at line 41 of file IPAddressTest.cpp.
       : address(address_), bytes(bytes_), version(version_) {}
AddressData::AddressData (const std::string & address_, uint8_t version_) inline
Definition at line 46 of file IPAddressTest.cpp.
       : address(address_), bytes(), version(version_) {}
AddressData::AddressData (const std::string & address_) inline explicit
Definition at line 48 of file IPAddressTest.cpp.
       : address(address_), bytes(), version(0) {}
AddressData::AddressData () inline
Definition at line 50 of file IPAddressTest.cpp.
 : address(""), bytes(), version(0) {}
Member Function Documentation
static in_addr AddressData::parseAddress4 (const std::string & src) inline static
Definition at line 52 of file IPAddressTest.cpp.
References addr.
Referenced by IPAddressTest::ExpectIsValid(), and TEST_P().
{
     in_addr addr;
     inet_pton(AF_INET, src.c_str(), &addr);
     return addr;
   }
static in6_addr AddressData::parseAddress6 (const std::string & src) inline static
Definition at line 58 of file IPAddressTest.cpp.
References addr.
Referenced by IPAddressTest::ExpectIsValid(), and TEST_P().
{
     in6_addr addr;
     inet_pton(AF_INET6, src.c_str(), &addr);
     return addr;
   }
Member Data Documentation
std::string AddressData::address
Definition at line 37 of file IPAddressTest.cpp.
Referenced by IPAddressTest::ExpectIsValid(), and TEST_P().
ByteVector AddressData::bytes
Definition at line 38 of file IPAddressTest.cpp.
Referenced by TEST_P().
uint8_t AddressData::version
Definition at line 39 of file IPAddressTest.cpp.
Referenced by IPAddressTest::ExpectIsValid(), and TEST_P().
The documentation for this struct was generated from the following file:
proxygen/folly/folly/test/IPAddressTest.cpp