proxygen: folly::symbolizer::SymbolizedFrame Struct Reference
folly::symbolizer::SymbolizedFrame Struct Reference
#include <Symbolizer.h>
Public Member Functions
SymbolizedFrame ()
void set (const std::shared_ptr< ElfFile > &file, uintptr_t address, Dwarf::LocationInfoMode mode)
void clear ()
fbstring demangledName () const
Public Attributes
bool found = false
const char * name = nullptr
Dwarf::LocationInfo location
Private Attributes
std::shared_ptr< ElfFile > file_
Detailed Description
Frame information: symbol name and location.
Definition at line 44 of file Symbolizer.h.
Constructor & Destructor Documentation
folly::symbolizer::SymbolizedFrame::SymbolizedFrame () inline
Definition at line 45 of file Symbolizer.h.
References mode.
Referenced by clear().
 {}
Member Function Documentation
void folly::symbolizer::SymbolizedFrame::clear () inline
Definition at line 52 of file Symbolizer.h.
References SymbolizedFrame().
Referenced by set(), and folly::symbolizer::Symbolizer::symbolize().
                {
     *this = SymbolizedFrame();
   }
fbstring folly::symbolizer::SymbolizedFrame::demangledName () const inline
Demangle the name and return it. Not async-signal-safe; allocates memory.
Definition at line 63 of file Symbolizer.h.
References folly::demangle().
Referenced by folly::symbolizer::test::TEST().
{
     return name ? demangle(name) : fbstring();
   }
void folly::symbolizer::SymbolizedFrame::set (const std::shared_ptr< ElfFile > & file, uintptr_t address, Dwarf::LocationInfoMode mode)
Definition at line 65 of file Symbolizer.cpp.
References clear(), file_, found, location, and name.
{
   clear();
   found = true;
   address += file->getBaseAddress();
   auto sym = file->getDefinitionByAddress(address);
   if (!sym.first) {
     return;
   }
   file_ = file;
   name = file->getSymbolName(sym);
   Dwarf(file.get()).findAddress(address, location, mode);
 }
Member Data Documentation
std::shared_ptr<ElfFile> folly::symbolizer::SymbolizedFrame::file_ private
Definition at line 68 of file Symbolizer.h.
Referenced by set().
bool folly::symbolizer::SymbolizedFrame::found = false
Definition at line 56 of file Symbolizer.h.
Referenced by folly::symbolizer::SymbolizePrinter::print(), folly::symbolizer::SymbolizePrinter::printTerse(), set(), and folly::symbolizer::Symbolizer::symbolize().
Dwarf::LocationInfo folly::symbolizer::SymbolizedFrame::location
Definition at line 58 of file Symbolizer.h.
Referenced by folly::symbolizer::SymbolizePrinter::print(), set(), and folly::symbolizer::test::TEST().
const char* folly::symbolizer::SymbolizedFrame::name = nullptr
Definition at line 57 of file Symbolizer.h.
Referenced by folly::symbolizer::SymbolizePrinter::print(), folly::symbolizer::SymbolizePrinter::printTerse(), and set().
The documentation for this struct was generated from the following files:
proxygen/folly/folly/experimental/symbolizer/Symbolizer.h
proxygen/folly/folly/experimental/symbolizer/Symbolizer.cpp