proxygen: Bool Struct Reference
Bool Struct Reference
Public Member Functions
Bool (int val)
bool operator> (int n) const
Bool operator+ (const Bool &rhs) const
bool operator== (const Bool &rhs) const
Bool (int val)
bool operator> (int n) const
Bool operator+ (const Bool &rhs) const
bool operator== (const Bool &rhs) const
Bool (int val)
bool operator> (int n) const
Bool operator+ (const Bool &rhs) const
bool operator== (const Bool &rhs) const
Public Attributes
bool value
Detailed Description
Definition at line 56 of file gtest_pred_impl_unittest.cc.
Constructor & Destructor Documentation
Bool::Bool (int val) inline explicit
Definition at line 57 of file gtest_pred_impl_unittest.cc.
Referenced by operator+(), operator>(), and TEST_F().
 : value(val != 0) {}
Bool::Bool (int val) inline explicit
Definition at line 57 of file gtest_pred_impl_unittest.cc.
 : value(val != 0) {}
Bool::Bool (int val) inline explicit
Definition at line 57 of file gtest_pred_impl_unittest.cc.
 : value(val != 0) {}
Member Function Documentation
Bool Bool::operator+ (const Bool & rhs) const inline
Definition at line 61 of file gtest_pred_impl_unittest.cc.
References Bool(), and value.
 { return Bool(value + rhs.value); }
Bool Bool::operator+ (const Bool & rhs) const inline
Definition at line 61 of file gtest_pred_impl_unittest.cc.
References Bool(), and value.
 { return Bool(value + rhs.value); }
Bool Bool::operator+ (const Bool & rhs) const inline
Definition at line 61 of file gtest_pred_impl_unittest.cc.
References Bool(), and value.
 { return Bool(value + rhs.value); }
bool Bool::operator== (const Bool & rhs) const inline
Definition at line 63 of file gtest_pred_impl_unittest.cc.
References value.
 { return value == rhs.value; }
bool Bool::operator== (const Bool & rhs) const inline
Definition at line 63 of file gtest_pred_impl_unittest.cc.
References value.
 { return value == rhs.value; }
bool Bool::operator== (const Bool & rhs) const inline
Definition at line 63 of file gtest_pred_impl_unittest.cc.
References value.
 { return value == rhs.value; }
bool Bool::operator> (int n) const inline
Definition at line 59 of file gtest_pred_impl_unittest.cc.
References Bool(), and value.
 { return value > Bool(n).value; }
bool Bool::operator> (int n) const inline
Definition at line 59 of file gtest_pred_impl_unittest.cc.
References Bool(), and value.
 { return value > Bool(n).value; }
bool Bool::operator> (int n) const inline
Definition at line 59 of file gtest_pred_impl_unittest.cc.
References Bool(), and value.
 { return value > Bool(n).value; }
Member Data Documentation
bool Bool::value
Definition at line 65 of file gtest_pred_impl_unittest.cc.
Referenced by operator+(), operator<<(), operator==(), and operator>().
The documentation for this struct was generated from the following file:
proxygen/fizz/build_/gtest/src/gtest/googletest/test/gtest_pred_impl_unittest.cc