proxygen: folly::AsyncFileWriter::Data Struct Reference
folly::AsyncFileWriter::Data Struct Reference
Public Member Functions
std::vector< std::string > * getCurrentQueue ()
Public Attributes
std::array< std::vector< std::string >, 2 > queues
uint32_t flags {0}
uint64_t ioThreadCounter {0}
size_t maxBufferBytes {kDefaultMaxBufferSize}
size_t currentBufferSize {0}
size_t numDiscarded {0}
std::thread ioThread
Detailed Description
Definition at line 128 of file AsyncFileWriter.h.
Member Function Documentation
std::vector<std::string>* folly::AsyncFileWriter::Data::getCurrentQueue () inline
Definition at line 137 of file AsyncFileWriter.h.
References folly::data(), folly::AsyncFileWriter::getNumDiscardedMsg(), ioThread, ioThreadCounter, numDiscarded, folly::AsyncFileWriter::onIoError(), folly::AsyncFileWriter::performIO(), folly::AsyncFileWriter::postForkChild(), folly::AsyncFileWriter::postForkParent(), folly::AsyncFileWriter::preFork(), folly::AsyncFileWriter::restartThread(), folly::AsyncFileWriter::stopIoThread(), string, and uint32_t.
{
       return &queues[ioThreadCounter & 0x1];
     }
Member Data Documentation
size_t folly::AsyncFileWriter::Data::currentBufferSize {0}
Definition at line 133 of file AsyncFileWriter.h.
uint32_t folly::AsyncFileWriter::Data::flags {0}
Definition at line 130 of file AsyncFileWriter.h.
std::thread folly::AsyncFileWriter::Data::ioThread
Definition at line 135 of file AsyncFileWriter.h.
Referenced by getCurrentQueue().
uint64_t folly::AsyncFileWriter::Data::ioThreadCounter {0}
Definition at line 131 of file AsyncFileWriter.h.
Referenced by getCurrentQueue().
size_t folly::AsyncFileWriter::Data::maxBufferBytes {kDefaultMaxBufferSize}
Definition at line 132 of file AsyncFileWriter.h.
size_t folly::AsyncFileWriter::Data::numDiscarded {0}
Definition at line 134 of file AsyncFileWriter.h.
Referenced by getCurrentQueue().
std::array<std::vector<std::string>, 2> folly::AsyncFileWriter::Data::queues
Definition at line 129 of file AsyncFileWriter.h.
The documentation for this struct was generated from the following file:
proxygen/folly/folly/logging/AsyncFileWriter.h