proxygen: folly::coro::detail::InlineTaskPromiseBase::FinalAwaiter Struct Reference
folly::coro::detail::InlineTaskPromiseBase::FinalAwaiter Struct Reference
Public Member Functions
bool await_ready () noexcept
template<typename Promise >
std::experimental::coroutine_handle await_suspend (std::experimental::coroutine_handle< Promise > h) noexcept
void await_resume () noexcept
Detailed Description
Definition at line 45 of file InlineTask.h.
Member Function Documentation
bool folly::coro::detail::InlineTaskPromiseBase::FinalAwaiter::await_ready () inline noexcept
Definition at line 46 of file InlineTask.h.
{
       return false;
     }
void folly::coro::detail::InlineTaskPromiseBase::FinalAwaiter::await_resume () inline noexcept
Definition at line 57 of file InlineTask.h.
References folly::coro::detail::InlineTaskPromiseBase::InlineTaskPromiseBase(), folly::pushmi::__adl::noexcept(), and folly::coro::detail::InlineTaskPromiseBase::operator=().
 {}
template<typename Promise > std::experimental::coroutine_handle folly::coro::detail::InlineTaskPromiseBase::FinalAwaiter::await_suspend (std::experimental::coroutine_handle< Promise > h) inline noexcept
Definition at line 51 of file InlineTask.h.
References folly::coro::detail::InlineTaskPromiseBase::continuation_, and h.
{
       InlineTaskPromiseBase& promise = h.promise();
       return promise.continuation_;
     }
The documentation for this struct was generated from the following file:
proxygen/folly/folly/experimental/coro/detail/InlineTask.h