proxygen: proxygen/folly/folly/test/SubprocessTestParentDeathHelper.cpp File Reference
SubprocessTestParentDeathHelper.cpp File Reference
#include <fcntl.h>
#include <signal.h>
#include <sys/types.h>
#include <glog/logging.h>
#include <folly/Conv.h>
#include <folly/Subprocess.h>
#include <folly/portability/GFlags.h>
#include <folly/portability/Unistd.h>
Functions
DEFINE_bool (child, false,"")
void runChild (const char *file)
void runParent (const char *file)
int main (int argc, char *argv[])
Function Documentation
DEFINE_bool (child , false , "")
int main (int argc, char * argv[])
Definition at line 73 of file SubprocessTestParentDeathHelper.cpp.
References runChild(), and runParent().
{
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   CHECK_EQ(argc, 2);
   if (FLAGS_child) {
     runChild(argv[1]);
   } else {
     runParent(argv[1]);
   }
   return 0;
 }
void runChild (const char * file)
Definition at line 44 of file SubprocessTestParentDeathHelper.cpp.
References folly::sig.
Referenced by main(), and folly::Subprocess::spawnInternal().
{
   // Block SIGUSR1 so it's queued
   sigset_t sigs;
   CHECK_ERR(sigemptyset(&sigs));
   CHECK_ERR(sigaddset(&sigs, kSignal));
   CHECK_ERR(sigprocmask(SIG_BLOCK, &sigs, nullptr));
   // Kill the parent, wait for our signal.
   CHECK_ERR(kill(getppid(), SIGKILL));
   int sig = 0;
   CHECK_ERR(sigwait(&sigs, &sig));
   CHECK_EQ(sig, kSignal);
   // Signal completion by creating the file
   CHECK_ERR(creat(file, 0600));
 }
void runParent (const char * file)
Definition at line 62 of file SubprocessTestParentDeathHelper.cpp.
References folly::Subprocess::poll(), and folly::ProcessReturnCode::running().
Referenced by main().
{
   std::vector<std::string> args{"/proc/self/exe", "--child", file};
   Subprocess proc(args, Subprocess::Options().parentDeathSignal(kSignal));
   CHECK(proc.poll().running());
   // The child will kill us.
   for (;;) {
     pause();
   }
 }