proxygen: proxygen/folly/folly/synchronization/test/BatonTest.cpp File Reference
BatonTest.cpp File Reference
#include <folly/synchronization/Baton.h>
#include <thread>
#include <folly/portability/GTest.h>
#include <folly/synchronization/test/BatonTestHelpers.h>
#include <folly/test/DeterministicSchedule.h>
Functions
TEST (Baton, basic_blocking)
Basic test.
TEST (Baton, basic_nonblocking)
TEST (Baton, pingpong_blocking)
Ping pong tests.
TEST (Baton, pingpong_nonblocking)
TEST (Baton, timed_wait_basic_system_clock_blocking)
TEST (Baton, timed_wait_basic_system_clock_nonblocking)
TEST (Baton, timed_wait_timeout_system_clock_blocking)
TEST (Baton, timed_wait_timeout_system_clock_nonblocking)
TEST (Baton, timed_wait_system_clock_blocking)
TEST (Baton, timed_wait_system_clock_nonblocking)
TEST (Baton, timed_wait_basic_steady_clock_blocking)
TEST (Baton, timed_wait_basic_steady_clock_nonblocking)
TEST (Baton, timed_wait_timeout_steady_clock_blocking)
TEST (Baton, timed_wait_timeout_steady_clock_nonblocking)
TEST (Baton, timed_wait_steady_clock_blocking)
TEST (Baton, timed_wait_steady_clock_nonblocking)
TEST (Baton, try_wait_blocking)
Try wait tests.
TEST (Baton, try_wait_nonblocking)
Function Documentation
TEST (Baton , basic_blocking)
Basic test.
Definition at line 33 of file BatonTest.cpp.
{
   run_basic_test<true, std::atomic>();
   run_basic_test<true, EmulatedFutexAtomic>();
   run_basic_test<true, DeterministicAtomic>();
 }
TEST (Baton , basic_nonblocking)
Definition at line 39 of file BatonTest.cpp.
{
   run_basic_test<false, std::atomic>();
   run_basic_test<false, EmulatedFutexAtomic>();
   run_basic_test<false, DeterministicAtomic>();
 }
TEST (Baton , pingpong_blocking)
Ping pong tests.
Definition at line 47 of file BatonTest.cpp.
References folly::test::DeterministicSchedule::uniform().
{
   DSched sched(DSched::uniform(0));
   run_pingpong_test<true, DeterministicAtomic>(1000);
 }
TEST (Baton , pingpong_nonblocking)
Definition at line 53 of file BatonTest.cpp.
References folly::test::DeterministicSchedule::uniform().
{
   DSched sched(DSched::uniform(0));
   run_pingpong_test<false, DeterministicAtomic>(1000);
 }
TEST (Baton , timed_wait_basic_system_clock_blocking)
Definition at line 61 of file BatonTest.cpp.
{
   run_basic_timed_wait_tests<true, std::atomic, system_clock>();
   run_basic_timed_wait_tests<true, EmulatedFutexAtomic, system_clock>();
   run_basic_timed_wait_tests<true, DeterministicAtomic, system_clock>();
 }
TEST (Baton , timed_wait_basic_system_clock_nonblocking)
Definition at line 67 of file BatonTest.cpp.
{
   run_basic_timed_wait_tests<false, std::atomic, system_clock>();
   run_basic_timed_wait_tests<false, EmulatedFutexAtomic, system_clock>();
   run_basic_timed_wait_tests<false, DeterministicAtomic, system_clock>();
 }
TEST (Baton , timed_wait_timeout_system_clock_blocking)
Definition at line 75 of file BatonTest.cpp.
References folly::test::DeterministicSchedule::uniform().
{
   DSched sched(DSched::uniform(0));
   run_timed_wait_tmo_tests<true, std::atomic, system_clock>();
   run_timed_wait_tmo_tests<true, EmulatedFutexAtomic, system_clock>();
   run_timed_wait_tmo_tests<true, DeterministicAtomic, system_clock>();
 }
TEST (Baton , timed_wait_timeout_system_clock_nonblocking)
Definition at line 82 of file BatonTest.cpp.
References folly::test::DeterministicSchedule::uniform().
{
   DSched sched(DSched::uniform(0));
   run_timed_wait_tmo_tests<false, std::atomic, system_clock>();
   run_timed_wait_tmo_tests<false, EmulatedFutexAtomic, system_clock>();
   run_timed_wait_tmo_tests<false, DeterministicAtomic, system_clock>();
 }
TEST (Baton , timed_wait_system_clock_blocking)
Definition at line 91 of file BatonTest.cpp.
References folly::test::DeterministicSchedule::uniform().
{
   DSched sched(DSched::uniform(0));
   run_timed_wait_regular_test<true, std::atomic, system_clock>();
   run_timed_wait_regular_test<true, EmulatedFutexAtomic, system_clock>();
   run_timed_wait_regular_test<true, DeterministicAtomic, system_clock>();
 }
TEST (Baton , timed_wait_system_clock_nonblocking)
Definition at line 98 of file BatonTest.cpp.
References folly::test::DeterministicSchedule::uniform().
{
   DSched sched(DSched::uniform(0));
   run_timed_wait_regular_test<false, std::atomic, system_clock>();
   run_timed_wait_regular_test<false, EmulatedFutexAtomic, system_clock>();
   run_timed_wait_regular_test<false, DeterministicAtomic, system_clock>();
 }
TEST (Baton , timed_wait_basic_steady_clock_blocking)
Definition at line 107 of file BatonTest.cpp.
References folly::test::DeterministicSchedule::uniform().
{
   DSched sched(DSched::uniform(0));
   run_basic_timed_wait_tests<true, std::atomic, steady_clock>();
   run_basic_timed_wait_tests<true, EmulatedFutexAtomic, steady_clock>();
   run_basic_timed_wait_tests<true, DeterministicAtomic, steady_clock>();
 }
TEST (Baton , timed_wait_basic_steady_clock_nonblocking)
Definition at line 114 of file BatonTest.cpp.
References folly::test::DeterministicSchedule::uniform().
{
   DSched sched(DSched::uniform(0));
   run_basic_timed_wait_tests<false, std::atomic, steady_clock>();
   run_basic_timed_wait_tests<false, EmulatedFutexAtomic, steady_clock>();
   run_basic_timed_wait_tests<false, DeterministicAtomic, steady_clock>();
 }
TEST (Baton , timed_wait_timeout_steady_clock_blocking)
Definition at line 123 of file BatonTest.cpp.
References folly::test::DeterministicSchedule::uniform().
{
   DSched sched(DSched::uniform(0));
   run_timed_wait_tmo_tests<true, std::atomic, steady_clock>();
   run_timed_wait_tmo_tests<true, EmulatedFutexAtomic, steady_clock>();
   run_timed_wait_tmo_tests<true, DeterministicAtomic, steady_clock>();
 }
TEST (Baton , timed_wait_timeout_steady_clock_nonblocking)
Definition at line 130 of file BatonTest.cpp.
References folly::test::DeterministicSchedule::uniform().
{
   DSched sched(DSched::uniform(0));
   run_timed_wait_tmo_tests<false, std::atomic, steady_clock>();
   run_timed_wait_tmo_tests<false, EmulatedFutexAtomic, steady_clock>();
   run_timed_wait_tmo_tests<false, DeterministicAtomic, steady_clock>();
 }
TEST (Baton , timed_wait_steady_clock_blocking)
Definition at line 139 of file BatonTest.cpp.
References folly::test::DeterministicSchedule::uniform().
{
   DSched sched(DSched::uniform(0));
   run_timed_wait_regular_test<true, std::atomic, steady_clock>();
   run_timed_wait_regular_test<true, EmulatedFutexAtomic, steady_clock>();
   run_timed_wait_regular_test<true, DeterministicAtomic, steady_clock>();
 }
TEST (Baton , timed_wait_steady_clock_nonblocking)
Definition at line 146 of file BatonTest.cpp.
References folly::test::DeterministicSchedule::uniform().
{
   DSched sched(DSched::uniform(0));
   run_timed_wait_regular_test<false, std::atomic, steady_clock>();
   run_timed_wait_regular_test<false, EmulatedFutexAtomic, steady_clock>();
   run_timed_wait_regular_test<false, DeterministicAtomic, steady_clock>();
 }
TEST (Baton , try_wait_blocking)
Try wait tests.
Definition at line 155 of file BatonTest.cpp.
{
   run_try_wait_tests<true, std::atomic>();
   run_try_wait_tests<true, EmulatedFutexAtomic>();
   run_try_wait_tests<true, DeterministicAtomic>();
 }
TEST (Baton , try_wait_nonblocking)
Definition at line 161 of file BatonTest.cpp.
{
   run_try_wait_tests<false, std::atomic>();
   run_try_wait_tests<false, EmulatedFutexAtomic>();
   run_try_wait_tests<false, DeterministicAtomic>();
 }