proxygen: proxygen/folly/folly/portability/SysUio.h File Reference
SysUio.h File Reference
#include <folly/portability/Config.h>
#include <folly/portability/IOVec.h>
#include <folly/portability/SysTypes.h>
Namespaces
folly
—— Concurrent Priority Queue Implementation ——
Functions
ssize_t preadv (int fd, const iovec *iov, int count, off_t offset)
ssize_t pwritev (int fd, const iovec *iov, int count, off_t offset)
Variables
constexpr size_t folly::kIovMax = UIO_MAXIOV
Function Documentation
ssize_t preadv (int fd, const iovec * iov, int count, off_t offset)
Definition at line 52 of file SysUio.cpp.
References wrapPositional().
Referenced by folly::preadvFull().
{
   return wrapPositional(readv, fd, offset, iov, count);
 }
ssize_t pwritev (int fd, const iovec * iov, int count, off_t offset)
Definition at line 58 of file SysUio.cpp.
References count, folly::kIovMax, fizz::detail::read(), SCOPE_EXIT, wrapPositional(), and fizz::detail::write().
Referenced by folly::pwritevFull().
{
   return wrapPositional(writev, fd, offset, iov, count);
 }