proxygen: proxygen/folly/folly/portability/SysUio.cpp File Reference
SysUio.cpp File Reference
#include <folly/portability/SysUio.h>
#include <errno.h>
#include <stdio.h>
#include <folly/ScopeGuard.h>
#include <folly/portability/Sockets.h>
#include <folly/portability/SysFile.h>
#include <folly/portability/Unistd.h>
Functions
template<class F , class... Args>
static int wrapPositional (F f, int fd, off_t offset, Args...args)
ssize_t preadv (int fd, const iovec *iov, int count, off_t offset)
ssize_t pwritev (int fd, const iovec *iov, int count, off_t offset)
Function Documentation
ssize_t preadv (int fd, const iovec * iov, int count, off_t offset)
Definition at line 52 of file SysUio.cpp.
References wrapPositional().
Referenced by folly::preadvFull().
{
   return wrapPositional(readv, fd, offset, iov, count);
 }
ssize_t pwritev (int fd, const iovec * iov, int count, off_t offset)
Definition at line 58 of file SysUio.cpp.
References count, folly::kIovMax, fizz::detail::read(), SCOPE_EXIT, wrapPositional(), and fizz::detail::write().
Referenced by folly::pwritevFull().
{
   return wrapPositional(writev, fd, offset, iov, count);
 }
template<class F , class... Args> static int wrapPositional (F f, int fd, off_t offset, Args... args) static
Definition at line 28 of file SysUio.cpp.
References f.
Referenced by preadv(), and pwritev().
{
   off_t origLoc = lseek(fd, 0, SEEK_CUR);
   if (origLoc == off_t(-1)) {
     return -1;
   }
   if (lseek(fd, offset, SEEK_SET) == off_t(-1)) {
     return -1;
   }
   int res = (int)f(fd, args...);
   int curErrNo = errno;
   if (lseek(fd, origLoc, SEEK_SET) == off_t(-1)) {
     if (res == -1) {
       errno = curErrNo;
     }
     return -1;
   }
   errno = curErrNo;
   return res;
 }