proxygen: proxygen/wangle/wangle/example/telnet/TelnetServer.cpp File Reference
TelnetServer.cpp File Reference
#include <gflags/gflags.h>
#include <folly/init/Init.h>
#include <wangle/bootstrap/ServerBootstrap.h>
#include <wangle/channel/AsyncSocketHandler.h>
#include <wangle/codec/LineBasedFrameDecoder.h>
#include <wangle/codec/StringCodec.h>
Classes
class TelnetHandler
class TelnetPipelineFactory
Typedefs
typedef Pipeline< IOBufQueue &, std::string > TelnetPipeline
Functions
DEFINE_int32 (port, 23,"test telnet server port")
int main (int argc, char **argv)
Typedef Documentation
typedef Pipeline<IOBufQueue&, std::string> TelnetPipeline
Definition at line 30 of file TelnetServer.cpp.
Function Documentation
DEFINE_int32 (port , 23 , "test telnet server port")
int main (int argc, char ** argv)
Definition at line 70 of file TelnetServer.cpp.
References wangle::ServerBootstrap< Pipeline >::bind(), wangle::ServerBootstrap< Pipeline >::childPipeline(), folly::init(), and wangle::ServerBootstrap< Pipeline >::waitForStop().
{
   folly::Init init(&argc, &argv);
   ServerBootstrap<TelnetPipeline> server;
   server.childPipeline(std::make_shared<TelnetPipelineFactory>());
   server.bind(FLAGS_port);
   server.waitForStop();
   return 0;
 }