proxygen: proxygen/folly/folly/test/function_benchmark/test_functions.cpp File Reference
test_functions.cpp File Reference
#include <folly/test/function_benchmark/test_functions.h>
#include <folly/lang/Exception.h>
Functions
void doNothing ()
std::exception_ptr returnExceptionPtr ()
void exceptionPtrReturnParam (std::exception_ptr *excReturn)
std::string returnString ()
std::string returnStringNoExcept () noexcept
int returnCode (int value)
int returnCodeNoExcept (int value) noexcept
void invoke (std::function< void()> f)
void invoke (folly::Function< void()> f)
Function Documentation
void doNothing ()
Definition at line 26 of file test_functions.cpp.
Referenced by BENCHMARK().
 {}
void exceptionPtrReturnParam (std::exception_ptr * excReturn)
Definition at line 33 of file test_functions.cpp.
Referenced by BENCHMARK().
{
   if (excReturn) {
     Exception ex("this is a test");
     *excReturn = std::make_exception_ptr(ex);
   }
 }
void invoke (std::function< void()> f)
Definition at line 69 of file test_functions.cpp.
References f.
{
   f();
 }
void invoke (folly::Function< void()> f)
Definition at line 73 of file test_functions.cpp.
References f.
{
   f();
 }
int returnCode (int value)
Definition at line 48 of file test_functions.cpp.
References value.
Referenced by BENCHMARK(), and folly::SubprocessSpawnError::SubprocessSpawnError().
{
   return value;
 }
int returnCodeNoExcept (int value) noexcept
Definition at line 52 of file test_functions.cpp.
References value.
Referenced by BENCHMARK().
{
   return value;
 }
std::exception_ptr returnExceptionPtr ()
Definition at line 28 of file test_functions.cpp.
Referenced by BENCHMARK().
{
   Exception ex("this is a test");
   return std::make_exception_ptr(ex);
 }
std::string returnString ()
Definition at line 40 of file test_functions.cpp.
Referenced by BENCHMARK().
{
   return "this is a test";
 }
std::string returnStringNoExcept () noexcept
Definition at line 44 of file test_functions.cpp.
Referenced by BENCHMARK().
{
   return "this is a test";
 }