proxygen: proxygen/folly/folly/futures/test/ThenTest.cpp File Reference
ThenTest.cpp File Reference
#include <folly/futures/Future.h>
#include <folly/portability/GTest.h>
#include <thread>
Functions
TEST (Then, tryConstructor)
TEST (Then, makeFuture)
TEST (Then, tryConstRValueReference)
TEST (Then, tryRValueReference)
TEST (Then, tryConstLValueReference)
TEST (Then, tryValue)
TEST (Then, tryConstValue)
TEST (Then, constRValueReference)
TEST (Then, rValueReference)
TEST (Then, constLValueReference)
TEST (Then, value)
TEST (Then, constValue)
TEST (Then, objectAliveDuringImmediateNoParamContinuation)
TEST (Then, objectAliveDuringDeferredNoParamContinuation)
TEST (Then, voidThenShouldPropagateExceptions)
Function Documentation
TEST (Then , tryConstructor)
Definition at line 75 of file ThenTest.cpp.
References EXPECT_EQ, and folly::pushmi::detail::t.
{
   auto t = Try<Widget>(23);
   EXPECT_EQ(t.value().v_, 23);
   EXPECT_EQ(t.value().copied_, 0);
   EXPECT_EQ(t.value().moved_, 1);
 }
TEST (Then , makeFuture)
Definition at line 82 of file ThenTest.cpp.
References EXPECT_EQ.
{
   auto future = makeFuture<Widget>(23);
   EXPECT_EQ(future.value().v_, 23);
   EXPECT_EQ(future.value().copied_, 0);
   EXPECT_EQ(future.value().moved_, 2);
 }
TEST (Then , tryConstRValueReference)
Definition at line 89 of file ThenTest.cpp.
References EXPECT_EQ, and folly::pushmi::detail::t.
{
   auto future = makeFuture<Widget>(23).then([](const Try<Widget>&& t) {
     EXPECT_EQ(t.value().copied_, 0);
     EXPECT_EQ(t.value().moved_, 2);
     return t.value().v_;
   });
   EXPECT_EQ(future.value(), 23);
 }
TEST (Then , tryRValueReference)
Definition at line 98 of file ThenTest.cpp.
References EXPECT_EQ, and folly::pushmi::detail::t.
{
   auto future = makeFuture<Widget>(23).then([](Try<Widget>&& t) {
     EXPECT_EQ(t.value().copied_, 0);
     EXPECT_EQ(t.value().moved_, 2);
     return t.value().v_;
   });
   EXPECT_EQ(future.value(), 23);
 }
TEST (Then , tryConstLValueReference)
Definition at line 107 of file ThenTest.cpp.
References EXPECT_EQ, folly::pushmi::detail::t, and folly::Try< T >::value().
{
   auto future = makeFuture<Widget>(23).then([](const Try<Widget>& t) {
     EXPECT_EQ(t.value().copied_, 0);
     EXPECT_EQ(t.value().moved_, 2);
     return t.value().v_;
   });
   EXPECT_EQ(future.value(), 23);
 }
TEST (Then , tryValue)
Definition at line 116 of file ThenTest.cpp.
References EXPECT_EQ, folly::pushmi::detail::t, and folly::Try< T >::value().
                      {
   auto future = makeFuture<Widget>(23).then([](Try<Widget> t) {
     EXPECT_EQ(t.value().copied_, 0);
     EXPECT_EQ(t.value().moved_, 3);
     return t.value().v_;
   });
   EXPECT_EQ(future.value(), 23);
 }
TEST (Then , tryConstValue)
Definition at line 125 of file ThenTest.cpp.
References EXPECT_EQ, folly::pushmi::detail::t, and folly::Try< T >::value().
{
   auto future = makeFuture<Widget>(23).then([](const Try<Widget> t) {
     EXPECT_EQ(t.value().copied_, 0);
     EXPECT_EQ(t.value().moved_, 3);
     return t.value().v_;
   });
   EXPECT_EQ(future.value(), 23);
 }
TEST (Then , constRValueReference)
Definition at line 134 of file ThenTest.cpp.
References EXPECT_EQ.
{
   auto future = makeFuture<Widget>(23).then([](const Widget&& w) {
     EXPECT_EQ(w.copied_, 0);
     EXPECT_EQ(w.moved_, 2);
     return w.v_;
   });
   EXPECT_EQ(future.value(), 23);
 }
TEST (Then , rValueReference)
Definition at line 143 of file ThenTest.cpp.
References EXPECT_EQ.
{
   auto future = makeFuture<Widget>(23).then([](Widget&& w) {
     EXPECT_EQ(w.copied_, 0);
     EXPECT_EQ(w.moved_, 2);
     return w.v_;
   });
   EXPECT_EQ(future.value(), 23);
 }
TEST (Then , constLValueReference)
Definition at line 152 of file ThenTest.cpp.
References EXPECT_EQ.
{
   auto future = makeFuture<Widget>(23).then([](const Widget& w) {
     EXPECT_EQ(w.copied_, 0);
     EXPECT_EQ(w.moved_, 2);
     return w.v_;
   });
   EXPECT_EQ(future.value(), 23);
 }
TEST (Then , value)
Definition at line 161 of file ThenTest.cpp.
References EXPECT_EQ.
                   {
   auto future = makeFuture<Widget>(23).then([](Widget w) {
     EXPECT_EQ(w.copied_, 0);
     EXPECT_EQ(w.moved_, 3);
     return w.v_;
   });
   EXPECT_EQ(future.value(), 23);
 }
TEST (Then , constValue)
Definition at line 170 of file ThenTest.cpp.
References EXPECT_EQ.
{
   auto future = makeFuture<Widget>(23).then([](const Widget w) {
     EXPECT_EQ(w.copied_, 0);
     EXPECT_EQ(w.moved_, 3);
     return w.v_;
   });
   EXPECT_EQ(future.value(), 23);
 }
TEST (Then , objectAliveDuringImmediateNoParamContinuation)
Definition at line 179 of file ThenTest.cpp.
References EXPECT_EQ, f, folly::gen::move, and folly::size().
{
   auto f = makeFuture<CountedWidget>(23);
   auto called = false;
   std::move(f).thenValue([&](auto&&) {
     EXPECT_EQ(CountedWidget::instances_.size(), 1u);
     EXPECT_EQ(CountedWidget::instances_[0]->v_, 23);
     called = true;
   });
   EXPECT_EQ(true, called);
 }
TEST (Then , objectAliveDuringDeferredNoParamContinuation)
Definition at line 190 of file ThenTest.cpp.
References EXPECT_EQ, folly::Promise< T >::getFuture(), and folly::size().
{
   auto p = Promise<CountedWidget>{};
   bool called = false;
   p.getFuture().thenValue([&](auto&&) {
     EXPECT_EQ(CountedWidget::instances_.size(), 1u);
     EXPECT_EQ(CountedWidget::instances_[0]->v_, 23);
     called = true;
   });
   p.setValue(CountedWidget{23});
   EXPECT_EQ(true, called);
 }
TEST (Then , voidThenShouldPropagateExceptions)
Definition at line 202 of file ThenTest.cpp.
References EXPECT_FALSE, EXPECT_TRUE, and folly::makeFuture().
{
   EXPECT_FALSE(makeFuture(42).then().hasException());
   EXPECT_TRUE(makeFuture<int>(std::runtime_error("err")).then().hasException());
 }