proxygen: proxygen/folly/folly/system/test/ThreadNameTest.cpp File Reference
ThreadNameTest.cpp File Reference
#include <thread>
#include <folly/ScopeGuard.h>
#include <folly/portability/GTest.h>
#include <folly/synchronization/Baton.h>
#include <folly/system/ThreadName.h>
Functions
TEST (ThreadName, getCurrentThreadName)
TEST (ThreadName, setThreadName_other_id)
Function Documentation
TEST (ThreadName , getCurrentThreadName)
Definition at line 35 of file ThreadNameTest.cpp.
References EXPECT_EQ, folly::getCurrentThreadName(), folly::Baton< MayBlock, Atom >::post(), SCOPE_EXIT, folly::setThreadName(), and folly::Baton< MayBlock, Atom >::wait().
{
   thread th([] {
     EXPECT_EQ(expectedSetSelfThreadNameResult, setThreadName(kThreadName));
     if (expectedSetSelfThreadNameResult) {
       EXPECT_EQ(kThreadName.toString(), *getCurrentThreadName());
     }
   });
   SCOPE_EXIT {
     th.join();
   };
 }
TEST (ThreadName , setThreadName_other_id)
Definition at line 69 of file ThreadNameTest.cpp.
References EXPECT_EQ, folly::getThreadName(), folly::Baton< MayBlock, Atom >::post(), SCOPE_EXIT, folly::setThreadName(), and folly::Baton< MayBlock, Atom >::wait().
{
   Baton<> let_thread_end;
   thread th([&] { let_thread_end.wait(); });
   SCOPE_EXIT {
     th.join();
   };
   SCOPE_EXIT {
     let_thread_end.post();
   };
   EXPECT_EQ(
       expectedSetOtherThreadNameResult,
       setThreadName(th.get_id(), kThreadName));
   if (expectedSetOtherThreadNameResult) {
     EXPECT_EQ(*getThreadName(th.get_id()), kThreadName);
   }
 }