proxygen: proxygen/folly/folly/executors/test/ThreadedExecutorTest.cpp File Reference
ThreadedExecutorTest.cpp File Reference
#include <folly/executors/ThreadedExecutor.h>
#include <folly/Conv.h>
#include <folly/futures/Future.h>
#include <folly/gen/Base.h>
#include <folly/portability/GTest.h>
Functions
TEST_F (ThreadedExecutorTest, example)
TEST_F (ThreadedExecutorTest, dtor_waits)
TEST_F (ThreadedExecutorTest, many)
TEST_F (ThreadedExecutorTest, many_sleeping_constant_time)
TEST_F (ThreadedExecutorTest, many_sleeping_decreasing_time)
Function Documentation
TEST_F (ThreadedExecutorTest , example)
Definition at line 29 of file ThreadedExecutorTest.cpp.
References EXPECT_EQ, folly::via(), and x.
{
   folly::ThreadedExecutor x;
   auto ret = folly::via(&x)
                  .thenValue([&](auto&&) { return 42; })
                  .thenValue([&](int n) { return folly::to<std::string>(n); })
                  .get();
   EXPECT_EQ("42", ret);
 }
TEST_F (ThreadedExecutorTest , dtor_waits)
Definition at line 39 of file ThreadedExecutorTest.cpp.
References EXPECT_TRUE, and folly::via().
{
   constexpr auto kDelay = std::chrono::milliseconds(100);
   auto x = std::make_unique<folly::ThreadedExecutor>();
   auto fut = folly::via(&*x, [&] { /* sleep override */
                                    std::this_thread::sleep_for(kDelay);
   });
   x = nullptr;
   EXPECT_TRUE(fut.isReady());
 }
TEST_F (ThreadedExecutorTest , many)
Definition at line 50 of file ThreadedExecutorTest.cpp.
References folly::collect(), EXPECT_EQ, i, k, folly::gen::map(), folly::via(), and x.
{
   constexpr auto kNumTasks = 1024;
   folly::ThreadedExecutor x;
   auto rets =
       folly::collect(
           folly::gen::range<size_t>(0, kNumTasks) |
           folly::gen::map([&](size_t i) {
             return folly::via(&x)
                 .thenValue([=](auto&&) { return i; })
                 .thenValue([](size_t k) { return folly::to<std::string>(k); });
           }) |
           folly::gen::as<std::vector>())
           .get();
   EXPECT_EQ("42", rets[42]);
 }
TEST_F (ThreadedExecutorTest , many_sleeping_constant_time)
Definition at line 67 of file ThreadedExecutorTest.cpp.
References folly::collect(), EXPECT_EQ, i, k, folly::gen::map(), folly::via(), and x.
{
   constexpr auto kNumTasks = 256;
   constexpr auto kDelay = std::chrono::milliseconds(100);
   folly::ThreadedExecutor x;
   auto rets =
       folly::collect(
           folly::gen::range<size_t>(0, kNumTasks) |
           folly::gen::map([&](size_t i) {
             return folly::via(&x)
                 .thenValue([=](auto&&) {
                   /* sleep override */ std::this_thread::sleep_for(kDelay);
                 })
                 .thenValue([=](auto&&) { return i; })
                 .thenValue([](size_t k) { return folly::to<std::string>(k); });
           }) |
           folly::gen::as<std::vector>())
           .get();
   EXPECT_EQ("42", rets[42]);
 }
TEST_F (ThreadedExecutorTest , many_sleeping_decreasing_time)
Definition at line 88 of file ThreadedExecutorTest.cpp.
References folly::collect(), EXPECT_EQ, i, k, folly::gen::map(), folly::via(), and x.
{
   constexpr auto kNumTasks = 256;
   constexpr auto kDelay = std::chrono::milliseconds(100);
   folly::ThreadedExecutor x;
   auto rets =
       folly::collect(
           folly::gen::range<size_t>(0, kNumTasks) |
           folly::gen::map([&](size_t i) {
             return folly::via(&x)
                 .thenValue([=](auto&&) {
                   auto delay = kDelay * (kNumTasks - i) / kNumTasks;
                   /* sleep override */ std::this_thread::sleep_for(delay);
                 })
                 .thenValue([=](auto&&) { return i; })
                 .thenValue([](size_t k) { return folly::to<std::string>(k); });
           }) |
           folly::gen::as<std::vector>())
           .get();
   EXPECT_EQ("42", rets[42]);
 }