proxygen: proxygen/folly/folly/executors/test/TimedDrivableExecutorTest.cpp File Reference
TimedDrivableExecutorTest.cpp File Reference
#include <folly/executors/TimedDrivableExecutor.h>
#include <folly/futures/Future.h>
#include <folly/portability/GTest.h>
#include <folly/synchronization/Baton.h>
Functions
TEST (TimedDrivableExecutor, runIsStable)
TEST (TimedDrivableExecutor, drainIsNotStable)
TEST (TimedDrivableExecutor, try_drive)
TEST (TimedDrivableExecutor, try_drive_for)
TEST (TimedDrivableExecutor, try_drive_until)
Function Documentation
TEST (TimedDrivableExecutor , runIsStable)
Definition at line 25 of file TimedDrivableExecutorTest.cpp.
References folly::TimedDrivableExecutor::add(), count, EXPECT_EQ, folly::TimedDrivableExecutor::run(), and x.
{
   size_t count = 0;
   TimedDrivableExecutor x;
   auto f1 = [&]() { count++; };
   auto f2 = [&]() {
     x.add(f1);
     x.add(f1);
   };
   x.add(f2);
   x.run();
   EXPECT_EQ(count, 0);
 }
TEST (TimedDrivableExecutor , drainIsNotStable)
Definition at line 38 of file TimedDrivableExecutorTest.cpp.
References folly::TimedDrivableExecutor::add(), count, folly::TimedDrivableExecutor::drain(), EXPECT_EQ, and x.
{
   size_t count = 0;
   TimedDrivableExecutor x;
   auto f1 = [&]() { count++; };
   auto f2 = [&]() {
     x.add(f1);
     x.add(f1);
   };
   x.add(f2);
   x.drain();
   EXPECT_EQ(count, 2);
 }
TEST (TimedDrivableExecutor , try_drive)
Definition at line 51 of file TimedDrivableExecutorTest.cpp.
References folly::TimedDrivableExecutor::add(), count, EXPECT_EQ, folly::TimedDrivableExecutor::try_drive(), and x.
{
   size_t count = 0;
   TimedDrivableExecutor x;
   auto f1 = [&]() { count++; };
   x.try_drive();
   EXPECT_EQ(count, 0);
   x.add(f1);
   x.try_drive();
   EXPECT_EQ(count, 1);
 }
TEST (TimedDrivableExecutor , try_drive_for)
Definition at line 62 of file TimedDrivableExecutorTest.cpp.
References folly::TimedDrivableExecutor::add(), count, EXPECT_EQ, folly::TimedDrivableExecutor::try_drive_for(), and x.
{
   size_t count = 0;
   TimedDrivableExecutor x;
   auto f1 = [&]() { count++; };
   x.try_drive_for(std::chrono::milliseconds(100));
   EXPECT_EQ(count, 0);
   x.add(f1);
   x.try_drive_for(std::chrono::milliseconds(100));
   EXPECT_EQ(count, 1);
 }
TEST (TimedDrivableExecutor , try_drive_until)
Definition at line 73 of file TimedDrivableExecutorTest.cpp.
References folly::TimedDrivableExecutor::add(), count, EXPECT_EQ, now(), folly::TimedDrivableExecutor::try_drive_until(), and x.
{
   size_t count = 0;
   TimedDrivableExecutor x;
   auto f1 = [&]() { count++; };
   x.try_drive_until(
       std::chrono::system_clock::now() + std::chrono::milliseconds(100));
   EXPECT_EQ(count, 0);
   x.add(f1);
   x.try_drive_until(
       std::chrono::system_clock::now() + std::chrono::milliseconds(100));
   EXPECT_EQ(count, 1);
 }