proxygen: proxygen/wangle/wangle/ssl/test/TLSCredProcessorTest.cpp File Reference
TLSCredProcessorTest.cpp File Reference
#include <boost/filesystem.hpp>
#include <folly/portability/GTest.h>
#include <folly/synchronization/Baton.h>
#include <folly/File.h>
#include <folly/FileUtil.h>
#include <folly/Range.h>
#include <wangle/ssl/TLSCredProcessor.h>
#include <wangle/ssl/test/TicketUtil.h>
Classes
class ProcessTicketTest
Functions
void expectValidData (folly::Optional< wangle::TLSTicketKeySeeds > seeds)
TEST_F (ProcessTicketTest, ParseTicketFile)
TEST_F (ProcessTicketTest, ParseInvalidFile)
TEST_F (ProcessTicketTest, handleAbsentFile)
void updateModifiedTime (const std::string &fileName, int elapsed)
TEST_F (ProcessTicketTest, TestUpdateTicketFile)
TEST_F (ProcessTicketTest, TestMultipleCerts)
TEST_F (ProcessTicketTest, TestSetPullInterval)
Function Documentation
void expectValidData (folly::Optional< wangle::TLSTicketKeySeeds > seeds)
Definition at line 51 of file TLSCredProcessorTest.cpp.
References ASSERT_EQ, ASSERT_TRUE, wangle::TLSTicketKeySeeds::currentSeeds, wangle::TLSTicketKeySeeds::newSeeds, and wangle::TLSTicketKeySeeds::oldSeeds.
Referenced by TEST_F().
{
   ASSERT_TRUE(seeds);
   ASSERT_EQ(2, seeds->newSeeds.size());
   ASSERT_EQ(1, seeds->currentSeeds.size());
   ASSERT_EQ(0, seeds->oldSeeds.size());
   ASSERT_EQ("0000111122223333444455556666777788889999aaaabbbbccccddddeeeeffff", seeds->newSeeds[0]);
   ASSERT_EQ("111122223333444455556666777788889999aaaabbbbccccddddeeeeffff0000", seeds->newSeeds[1]);
 }
TEST_F (ProcessTicketTest , ParseTicketFile)
Definition at line 60 of file TLSCredProcessorTest.cpp.
References expectValidData(), validTicketData, and folly::writeFile().
{
   CHECK(writeFile(validTicketData, ticketFile.c_str()));
   auto seeds = TLSCredProcessor::processTLSTickets(ticketFile);
   expectValidData(seeds);
 }
TEST_F (ProcessTicketTest , ParseInvalidFile)
Definition at line 66 of file TLSCredProcessorTest.cpp.
References ASSERT_FALSE, invalidTicketData, and folly::writeFile().
{
   CHECK(writeFile(invalidTicketData, ticketFile.c_str()));
   auto seeds = TLSCredProcessor::processTLSTickets(ticketFile);
   ASSERT_FALSE(seeds);
 }
TEST_F (ProcessTicketTest , handleAbsentFile)
Definition at line 72 of file TLSCredProcessorTest.cpp.
References ASSERT_FALSE.
{
   auto seeds = TLSCredProcessor::processTLSTickets("/path/does/not/exist");
   ASSERT_FALSE(seeds);
 }
TEST_F (ProcessTicketTest , TestUpdateTicketFile)
Definition at line 85 of file TLSCredProcessorTest.cpp.
References wangle::TLSCredProcessor::addCertCallback(), wangle::TLSCredProcessor::addTicketCallback(), ASSERT_FALSE, ASSERT_TRUE, EXPECT_TRUE, folly::Baton< MayBlock, Atom >::post(), wangle::TLSCredProcessor::setCertPathsToWatch(), wangle::TLSCredProcessor::setTicketPathToWatch(), folly::Baton< MayBlock, Atom >::try_wait_for(), updateModifiedTime(), validTicketData, and folly::writeFile().
{
   Baton<> ticketBaton;
   Baton<> certBaton;
   TLSCredProcessor processor;
   processor.setTicketPathToWatch(ticketFile);
   processor.setCertPathsToWatch({certFile});
   bool ticketUpdated = false;
   bool certUpdated = false;
   processor.addTicketCallback([&](TLSTicketKeySeeds) {
     ticketUpdated = true;
     ticketBaton.post();
   });
   processor.addCertCallback([&]() {
     certUpdated = true;
     certBaton.post();
   });
   CHECK(writeFile(validTicketData, ticketFile.c_str()));
   updateModifiedTime(ticketFile,10);
   EXPECT_TRUE(ticketBaton.try_wait_for(std::chrono::seconds(30)));
   ASSERT_TRUE(ticketUpdated);
   ASSERT_FALSE(certUpdated);
   ticketUpdated = false;
   CHECK(writeFile(validTicketData, certFile.c_str()));
   updateModifiedTime(certFile,10);
   EXPECT_TRUE(certBaton.try_wait_for(std::chrono::seconds(30)));
   ASSERT_TRUE(certUpdated);
   ASSERT_FALSE(ticketUpdated);
 }
TEST_F (ProcessTicketTest , TestMultipleCerts)
Definition at line 114 of file TLSCredProcessorTest.cpp.
References wangle::TLSCredProcessor::addCertCallback(), EXPECT_TRUE, folly::Baton< MayBlock, Atom >::post(), folly::Baton< MayBlock, Atom >::reset(), wangle::TLSCredProcessor::setCertPathsToWatch(), folly::Baton< MayBlock, Atom >::try_wait_for(), updateModifiedTime(), validTicketData, and folly::writeFile().
{
   Baton<> certBaton;
   TLSCredProcessor processor;
   processor.setCertPathsToWatch({certFile, ticketFile});
   processor.addCertCallback([&]() {
     certBaton.post();
   });
   CHECK(writeFile(validTicketData, ticketFile.c_str()));
   updateModifiedTime(ticketFile,10);
   EXPECT_TRUE(certBaton.try_wait_for(std::chrono::seconds(30)));
   certBaton.reset();
   CHECK(writeFile(validTicketData, certFile.c_str()));
   updateModifiedTime(certFile,10);
   EXPECT_TRUE(certBaton.try_wait_for(std::chrono::seconds(30)));
 }
TEST_F (ProcessTicketTest , TestSetPullInterval)
Definition at line 130 of file TLSCredProcessorTest.cpp.
References wangle::TLSCredProcessor::addCertCallback(), wangle::TLSCredProcessor::addTicketCallback(), ASSERT_FALSE, ASSERT_TRUE, EXPECT_TRUE, folly::Baton< MayBlock, Atom >::post(), wangle::TLSCredProcessor::setCertPathsToWatch(), wangle::TLSCredProcessor::setPollInterval(), wangle::TLSCredProcessor::setTicketPathToWatch(), folly::Baton< MayBlock, Atom >::try_wait_for(), updateModifiedTime(), validTicketData, and folly::writeFile().
{
   Baton<> ticketBaton;
   Baton<> certBaton;
   TLSCredProcessor processor;
   processor.setTicketPathToWatch(ticketFile);
   processor.setCertPathsToWatch({certFile});
   processor.setPollInterval(std::chrono::seconds(3));
   bool ticketUpdated = false;
   bool certUpdated = false;
   processor.addTicketCallback([&](TLSTicketKeySeeds) {
     ticketUpdated = true;
     ticketBaton.post();
   });
   processor.addCertCallback([&]() {
     certUpdated = true;
     certBaton.post();
   });
   CHECK(writeFile(validTicketData, ticketFile.c_str()));
   updateModifiedTime(ticketFile,3);
   EXPECT_TRUE(ticketBaton.try_wait_for(std::chrono::seconds(5)));
   ASSERT_TRUE(ticketUpdated);
   ASSERT_FALSE(certUpdated);
   ticketUpdated = false;
   CHECK(writeFile(validTicketData, certFile.c_str()));
   updateModifiedTime(certFile,3);
   EXPECT_TRUE(certBaton.try_wait_for(std::chrono::seconds(5)));
   ASSERT_TRUE(certUpdated);
   ASSERT_FALSE(ticketUpdated);
 }
void updateModifiedTime (const std::string & fileName, int elapsed)
Definition at line 77 of file TLSCredProcessorTest.cpp.
Referenced by TEST_F().
{
   auto previous = fs::last_write_time(fileName);
   auto newTime = std::chrono::system_clock::to_time_t(
       std::chrono::system_clock::from_time_t(previous) +
       std::chrono::seconds(elapsed));
   fs::last_write_time(fileName, newTime);
 }