proxygen: proxygen/wangle/wangle/ssl/test/TLSTicketKeyManagerTest.cpp File Reference
TLSTicketKeyManagerTest.cpp File Reference
#include <folly/portability/GMock.h>
#include <gtest/gtest.h>
#include <wangle/ssl/SSLStats.h>
#include <wangle/ssl/TLSTicketKeyManager.h>
Classes
class MockSSLStats
Functions
TEST (TLSTicketKeyManager, TestSetGetTLSTicketKeySeeds)
TEST (TLSTicketKeyManager, TestValidateTicketSeedsSuccess)
TEST (TLSTicketKeyManager, TestValidateTicketSeedsIdempotent)
TEST (TLSTicketKeyManager, TestValidateTicketSeedsFailure)
TEST (TLSTicketKeyManager, TestValidateTicketSeedsSubsetPass)
Function Documentation
TEST (TLSTicketKeyManager , TestSetGetTLSTicketKeySeeds)
Definition at line 47 of file TLSTicketKeyManagerTest.cpp.
References ASSERT_EQ, and cpp.ast::next().
{
   std::vector<std::string> origOld = {"67"};
   std::vector<std::string> origCurr = {"68"};
   std::vector<std::string> origNext = {"69"};
   folly::SSLContext ctx;
   wangle::TLSTicketKeyManager manager(&ctx, nullptr);
   manager.setTLSTicketKeySeeds(origOld, origCurr, origNext);
   std::vector<std::string> old;
   std::vector<std::string> curr;
   std::vector<std::string> next;
   manager.getTLSTicketKeySeeds(old, curr, next);
   ASSERT_EQ(origOld, old);
   ASSERT_EQ(origCurr, curr);
   ASSERT_EQ(origNext, next);
 }
TEST (TLSTicketKeyManager , TestValidateTicketSeedsSuccess)
Definition at line 65 of file TLSTicketKeyManagerTest.cpp.
References EXPECT_CALL, and wangle::SSLStats::recordTLSTicketRotation().
{
   MockSSLStats stats;
   EXPECT_CALL(stats, recordTLSTicketRotation(true)).Times(2);
   std::vector<std::string> origOld = {"67", "77"};
   std::vector<std::string> origCurr = {"68", "78"};
   std::vector<std::string> origNext = {"69", "79"};
   // The new ticket seeds are compatible
   std::vector<std::string> newOld = {"68", "78"};
   std::vector<std::string> newCurr = {"69", "79"};
   std::vector<std::string> newNext = {"70", "80"};
   folly::SSLContext ctx;
   wangle::TLSTicketKeyManager manager(&ctx, &stats);
   manager.setTLSTicketKeySeeds(origOld, origCurr, origNext);
   manager.setTLSTicketKeySeeds(newOld, newCurr, newNext);
 }
TEST (TLSTicketKeyManager , TestValidateTicketSeedsIdempotent)
Definition at line 85 of file TLSTicketKeyManagerTest.cpp.
References EXPECT_CALL, and wangle::SSLStats::recordTLSTicketRotation().
{
   MockSSLStats stats;
   EXPECT_CALL(stats, recordTLSTicketRotation(true)).Times(2);
   std::vector<std::string> origOld = {"67", "77"};
   std::vector<std::string> origCurr = {"68", "78"};
   std::vector<std::string> origNext = {"69", "79"};
   folly::SSLContext ctx;
   wangle::TLSTicketKeyManager manager(&ctx, &stats);
   manager.setTLSTicketKeySeeds(origOld, origCurr, origNext);
   manager.setTLSTicketKeySeeds(origOld, origCurr, origNext);
 }
TEST (TLSTicketKeyManager , TestValidateTicketSeedsFailure)
Definition at line 100 of file TLSTicketKeyManagerTest.cpp.
References EXPECT_CALL, and wangle::SSLStats::recordTLSTicketRotation().
{
   MockSSLStats stats;
   InSequence inSequence;
   EXPECT_CALL(stats, recordTLSTicketRotation(true)).Times(1);
   EXPECT_CALL(stats, recordTLSTicketRotation(false)).Times(1);
   std::vector<std::string> origOld = {"67", "77"};
   std::vector<std::string> origCurr = {"68", "78"};
   std::vector<std::string> origNext = {"69", "79"};
   // The new seeds are incompatible
   std::vector<std::string> newOld = {"69", "79"};
   std::vector<std::string> newCurr = {"70", "80"};
   std::vector<std::string> newNext = {"71", "81"};
   folly::SSLContext ctx;
   wangle::TLSTicketKeyManager manager(&ctx, &stats);
   manager.setTLSTicketKeySeeds(origOld, origCurr, origNext);
   manager.setTLSTicketKeySeeds(newOld, newCurr, newNext);
 }
TEST (TLSTicketKeyManager , TestValidateTicketSeedsSubsetPass)
Definition at line 122 of file TLSTicketKeyManagerTest.cpp.
References EXPECT_CALL, and wangle::SSLStats::recordTLSTicketRotation().
{
   MockSSLStats stats;
   InSequence inSequence;
   EXPECT_CALL(stats, recordTLSTicketRotation(true)).Times(2);
   std::vector<std::string> origOld = {"67"};
   std::vector<std::string> origCurr = {"68"};
   std::vector<std::string> origNext = {"69"};
   // The new ticket seeds are compatible
   std::vector<std::string> newOld = {"68", "78"};
   std::vector<std::string> newCurr = {"69"};
   std::vector<std::string> newNext = {"70", "80"};
   folly::SSLContext ctx;
   wangle::TLSTicketKeyManager manager(&ctx, &stats);
   manager.setTLSTicketKeySeeds(origOld, origCurr, origNext);
   manager.setTLSTicketKeySeeds(newOld, newCurr, newNext);
 }