proxygen: proxygen/folly/folly/executors/task_queue/test/UnboundedBlockingQueueTest.cpp File Reference
UnboundedBlockingQueueTest.cpp File Reference
#include <folly/executors/task_queue/UnboundedBlockingQueue.h>
#include <folly/portability/GTest.h>
#include <folly/synchronization/Baton.h>
#include <thread>
Functions
TEST (UnboundedQueuee, push_pop)
TEST (UnboundedBlockingQueue, size)
TEST (UnboundedBlockingQueue, concurrent_push_pop)
Function Documentation
TEST (UnboundedQueuee , push_pop)
Definition at line 23 of file UnboundedBlockingQueueTest.cpp.
References folly::UnboundedBlockingQueue< T >::add(), EXPECT_EQ, and folly::UnboundedBlockingQueue< T >::take().
{
   UnboundedBlockingQueue<int> q;
   q.add(42);
   EXPECT_EQ(42, q.take());
 }
TEST (UnboundedBlockingQueue , size)
Definition at line 28 of file UnboundedBlockingQueueTest.cpp.
References folly::UnboundedBlockingQueue< T >::add(), EXPECT_EQ, folly::UnboundedBlockingQueue< T >::size(), and folly::UnboundedBlockingQueue< T >::take().
{
   UnboundedBlockingQueue<int> q;
   EXPECT_EQ(0, q.size());
   q.add(42);
   EXPECT_EQ(1, q.size());
   q.take();
   EXPECT_EQ(0, q.size());
 }
TEST (UnboundedBlockingQueue , concurrent_push_pop)
Definition at line 37 of file UnboundedBlockingQueueTest.cpp.
References folly::UnboundedBlockingQueue< T >::add(), EXPECT_EQ, folly::Baton< MayBlock, Atom >::post(), folly::UnboundedBlockingQueue< T >::size(), folly::pushmi::detail::t, folly::UnboundedBlockingQueue< T >::take(), and folly::Baton< MayBlock, Atom >::wait().
{
   UnboundedBlockingQueue<int> q;
   Baton<> b1, b2;
   std::thread t([&] {
     b1.post();
     EXPECT_EQ(42, q.take());
     EXPECT_EQ(0, q.size());
     b2.post();
   });
   b1.wait();
   q.add(42);
   b2.wait();
   EXPECT_EQ(0, q.size());
   t.join();
 }