proxygen: proxygen/folly/folly/lang/test/UncaughtExceptionsTest.cpp File Reference
UncaughtExceptionsTest.cpp File Reference
#include <folly/lang/UncaughtExceptions.h>
#include <folly/Conv.h>
#include <folly/portability/GTest.h>
#include <glog/logging.h>
Classes
class Validator
struct ThrowInDestructor< N, I >
struct ThrowInDestructor< N, 0 >
struct ThrowingConstructor
struct InheritsThrowingConstructor
Functions
TEST (UncaughtExceptions, no_exception)
TEST (UncaughtExceptions, no_uncaught_exception)
TEST (UncaughtExceptions, one_uncaught_exception)
TEST (UncaughtExceptions, catch_rethrow)
void throwingFunction ()
TEST (UncaughtExceptions, one_uncaught_exception_in_function)
TEST (UncaughtExceptions, two_uncaught_exceptions)
TEST (UncaughtExceptions, ten_uncaught_exceptions)
TEST (UncaughtExceptions, one_exception_in_ctor_initializer_expression)
Function Documentation
TEST (UncaughtExceptions , no_exception)
Definition at line 49 of file UncaughtExceptionsTest.cpp.
{
   Validator validator(0, "no_exception");
 }
TEST (UncaughtExceptions , no_uncaught_exception)
Definition at line 53 of file UncaughtExceptionsTest.cpp.
References Validator::validate().
{
   Validator validator(0, "no_uncaught_exception");
   try {
     throw std::runtime_error("exception");
   } catch (const std::runtime_error& e) {
     validator.validate();
   }
 }
TEST (UncaughtExceptions , one_uncaught_exception)
Definition at line 62 of file UncaughtExceptionsTest.cpp.
{
   try {
     Validator validator(1, "one_uncaught_exception");
     throw std::runtime_error("exception");
   } catch (const std::runtime_error& e) {
   }
 }
TEST (UncaughtExceptions , catch_rethrow)
Definition at line 70 of file UncaughtExceptionsTest.cpp.
References EXPECT_EQ, and folly::uncaught_exceptions().
{
   try {
     Validator validatorOuter(1, "catch_rethrow_outer");
     try {
       Validator validatorInner(1, "catch_rethrow_inner");
       throw std::runtime_error("exception");
     } catch (const std::runtime_error& e) {
       EXPECT_EQ(0, folly::uncaught_exceptions());
       Validator validatorRethrow(1, "catch_rethrow");
       throw;
     }
   } catch (const std::runtime_error& e) {
     EXPECT_EQ(0, folly::uncaught_exceptions());
   }
 }
TEST (UncaughtExceptions , one_uncaught_exception_in_function)
Definition at line 91 of file UncaughtExceptionsTest.cpp.
References EXPECT_THROW, and throwingFunction().
{
   EXPECT_THROW({ throwingFunction(); }, std::runtime_error);
 }
TEST (UncaughtExceptions , two_uncaught_exceptions)
Definition at line 134 of file UncaughtExceptionsTest.cpp.
{
   ThrowInDestructor<2> twoUncaughtExceptions;
 }
TEST (UncaughtExceptions , ten_uncaught_exceptions)
Definition at line 138 of file UncaughtExceptionsTest.cpp.
{
   ThrowInDestructor<10> twoUncaughtExceptions;
 }
TEST (UncaughtExceptions , one_exception_in_ctor_initializer_expression)
Definition at line 161 of file UncaughtExceptionsTest.cpp.
References EXPECT_THROW.
{
   EXPECT_THROW(
       { InheritsThrowingConstructor inheritsThrowingConstructor; },
       std::runtime_error);
 }
void throwingFunction ()
Definition at line 86 of file UncaughtExceptionsTest.cpp.
Referenced by TEST().
{
   Validator validator(1, "one_uncaught_exception_in_function");
   throw std::runtime_error("exception");
 }