proxygen: folly::small_vector< Value, RequestedMaxInline, PolicyA, PolicyB, PolicyC >::Data Union Reference
folly::small_vector< Value, RequestedMaxInline, PolicyA, PolicyB, PolicyC >::Data Union Reference
Public Member Functions
Data ()
value_type * buffer () noexcept
value_type const * buffer () const noexcept
value_type * heap () noexcept
value_type const * heap () const noexcept
bool hasCapacity () const
InternalSizeType getCapacity () const
void setCapacity (InternalSizeType c)
void freeHeap ()
Public Attributes
PointerType pdata_
InlineStorageType storage_
Detailed Description
template<class Value, std::size_t RequestedMaxInline = 1, class PolicyA = void, class PolicyB = void, class PolicyC = void>
union folly::small_vector< Value, RequestedMaxInline, PolicyA, PolicyB, PolicyC >::Data
Definition at line 1152 of file small_vector.h.
Constructor & Destructor Documentation
template<class Value, std::size_t RequestedMaxInline = 1, class PolicyA = void, class PolicyB = void, class PolicyC = void> folly::small_vector< Value, RequestedMaxInline, PolicyA, PolicyB, PolicyC >::Data::Data () inline explicit
Definition at line 1153 of file small_vector.h.
                     {
       pdata_.heap_ = nullptr;
     }
Member Function Documentation
template<class Value, std::size_t RequestedMaxInline = 1, class PolicyA = void, class PolicyB = void, class PolicyC = void> value_type* folly::small_vector< Value, RequestedMaxInline, PolicyA, PolicyB, PolicyC >::Data::buffer () inline noexcept
Definition at line 1160 of file small_vector.h.
{
       void* vp = &storage_;
       return static_cast<value_type*>(vp);
     }
template<class Value, std::size_t RequestedMaxInline = 1, class PolicyA = void, class PolicyB = void, class PolicyC = void> value_type const* folly::small_vector< Value, RequestedMaxInline, PolicyA, PolicyB, PolicyC >::Data::buffer () const inline noexcept
Definition at line 1164 of file small_vector.h.
References buffer().
{
       return const_cast<Data*>(this)->buffer();
     }
template<class Value, std::size_t RequestedMaxInline = 1, class PolicyA = void, class PolicyB = void, class PolicyC = void> void folly::small_vector< Value, RequestedMaxInline, PolicyA, PolicyB, PolicyC >::Data::freeHeap () inline
Definition at line 1189 of file small_vector.h.
References FOLLY_SV_PACK_POP, bm::free(), and folly::detail::pointerFlagClear().
                     {
       auto vp = detail::pointerFlagClear(pdata_.heap_);
       free(vp);
     }
template<class Value, std::size_t RequestedMaxInline = 1, class PolicyA = void, class PolicyB = void, class PolicyC = void> InternalSizeType folly::small_vector< Value, RequestedMaxInline, PolicyA, PolicyB, PolicyC >::Data::getCapacity () const inline
Definition at line 1182 of file small_vector.h.
{
       return pdata_.getCapacity();
     }
template<class Value, std::size_t RequestedMaxInline = 1, class PolicyA = void, class PolicyB = void, class PolicyC = void> bool folly::small_vector< Value, RequestedMaxInline, PolicyA, PolicyB, PolicyC >::Data::hasCapacity () const inline
Definition at line 1179 of file small_vector.h.
References folly::detail::pointerFlagGet().
{
       return kHasInlineCapacity || detail::pointerFlagGet(pdata_.heap_);
     }
template<class Value, std::size_t RequestedMaxInline = 1, class PolicyA = void, class PolicyB = void, class PolicyC = void> value_type* folly::small_vector< Value, RequestedMaxInline, PolicyA, PolicyB, PolicyC >::Data::heap () inline noexcept
Definition at line 1167 of file small_vector.h.
References folly::detail::pointerFlagClear(), folly::detail::pointerFlagGet(), and folly::detail::shiftPointer().
{
       if (kHasInlineCapacity || !detail::pointerFlagGet(pdata_.heap_)) {
         return static_cast<value_type*>(pdata_.heap_);
       } else {
         return static_cast<value_type*>(detail::shiftPointer(
             detail::pointerFlagClear(pdata_.heap_), kHeapifyCapacitySize));
       }
     }
template<class Value, std::size_t RequestedMaxInline = 1, class PolicyA = void, class PolicyB = void, class PolicyC = void> value_type const* folly::small_vector< Value, RequestedMaxInline, PolicyA, PolicyB, PolicyC >::Data::heap () const inline noexcept
Definition at line 1175 of file small_vector.h.
{
       return const_cast<Data*>(this)->heap();
     }
template<class Value, std::size_t RequestedMaxInline = 1, class PolicyA = void, class PolicyB = void, class PolicyC = void> void folly::small_vector< Value, RequestedMaxInline, PolicyA, PolicyB, PolicyC >::Data::setCapacity (InternalSizeType c) inline
Definition at line 1185 of file small_vector.h.
{
       pdata_.setCapacity(c);
     }
Member Data Documentation
template<class Value, std::size_t RequestedMaxInline = 1, class PolicyA = void, class PolicyB = void, class PolicyC = void> PointerType folly::small_vector< Value, RequestedMaxInline, PolicyA, PolicyB, PolicyC >::Data::pdata_
Definition at line 1157 of file small_vector.h.
Referenced by folly::small_vector< Observer< T > *, InlineObservers >::swap().
template<class Value, std::size_t RequestedMaxInline = 1, class PolicyA = void, class PolicyB = void, class PolicyC = void> InlineStorageType folly::small_vector< Value, RequestedMaxInline, PolicyA, PolicyB, PolicyC >::Data::storage_
Definition at line 1158 of file small_vector.h.
The documentation for this union was generated from the following file:
proxygen/folly/folly/small_vector.h