proxygen: proxygen/folly/folly/test/UriBenchmark.cpp File Reference
UriBenchmark.cpp File Reference
#include <folly/Uri.h>
#include <folly/Benchmark.h>
#include <folly/init/Init.h>
Functions
BENCHMARK (init_uri_simple, iters)
BENCHMARK (init_uri_simple_with_query_parsing, iters)
BENCHMARK (init_uri_complex, iters)
BENCHMARK (init_uri_complex_with_query_parsing, iters)
int main (int argc, char **argv)
Function Documentation
BENCHMARK (init_uri_simple , iters)
Result of benchmark varies by the complexity of query.
folly/test/UriTest.cpp relative time/iter iters/s
init_uri_simple 4.88us 204.80K init_uri_simple_with_query_parsing 22.46us 44.52K init_uri_complex 5.92us 168.85K
init_uri_complex_with_query_parsing 48.70us 20.53K
Definition at line 35 of file UriBenchmark.cpp.
References i, and s.
{
   const fbstring s("http://localhost?&key1=foo&key2=&key3&=bar&=bar=&");
   for (size_t i = 0; i < iters; ++i) {
     Uri u(s);
   }
 }
BENCHMARK (init_uri_simple_with_query_parsing , iters)
Definition at line 42 of file UriBenchmark.cpp.
References folly::Uri::getQueryParams(), i, and s.
{
   const fbstring s("http://localhost?&key1=foo&key2=&key3&=bar&=bar=&");
   for (size_t i = 0; i < iters; ++i) {
     Uri u(s);
     u.getQueryParams();
   }
 }
BENCHMARK (init_uri_complex , iters)
Definition at line 50 of file UriBenchmark.cpp.
References i, and s.
{
   const fbstring s(
       "https://mock.example.com/farm/track.php?TmOxQUDF=uSmTS_VwhjKnh_JME&DI"
       "h=fbbN&GRsoIm=bGshjaUqavZxQai&UMT=36k18N4dn21&3U=CD8o4A4497W152j6m0V%14"
       "%57&Hy=t%05mpr.80JUZ7ne_%23zS8DcA%0qc_%291ymamz096%11Zfb3r%09ZqPD%311ZX"
       "tqJd600ot&5U96U-Rh-VZ=-D_6-9xKYj%1gW6b43s1B9-j21P0oUW5-t46G4kgt&ezgj=mcW"
       "TTQ.c&Oh=%2PblUfuC%7C997048884827569%03xnyJ%2L1pi7irBioQ6D4r7nNHNdo6v7Y%"
       "84aurnSJ%2wCFePHMlGZmIHGfCe7392_lImWsSvN&sBeNN=Nf%80yOE%6X10M64F4gG197aX"
       "R2B4g2533x235A0i4e%57%58uWB%04Erw.60&VMS4=Ek_%02GC0Pkx%6Ov_%207WICUz007%"
       "04nYX8N%46zzpv%999h&KGmBt988y=q4P57C-Dh-Nz-x_7-5oPxz%1gz3N03t6c7-R67N4DT"
       "Y6-f98W1&Lts&%02dOty%8eEYEnLz4yexQQLnL4MGU2JFn3OcmXcatBcabZgBdDdy67hdgW"
       "tYn4");
   for (size_t i = 0; i < iters; ++i) {
     Uri u(s);
   }
 }
BENCHMARK (init_uri_complex_with_query_parsing , iters)
Definition at line 67 of file UriBenchmark.cpp.
References folly::Uri::getQueryParams(), i, and s.
{
   const fbstring s(
       "https://mock.example.com/farm/track.php?TmOxQUDF=uSmTS_VwhjKnh_JME&DI"
       "h=fbbN&GRsoIm=bGshjaUqavZxQai&UMT=36k18N4dn21&3U=CD8o4A4497W152j6m0V%14"
       "%57&Hy=t%05mpr.80JUZ7ne_%23zS8DcA%0qc_%291ymamz096%11Zfb3r%09ZqPD%311ZX"
       "tqJd600ot&5U96U-Rh-VZ=-D_6-9xKYj%1gW6b43s1B9-j21P0oUW5-t46G4kgt&ezgj=mcW"
       "TTQ.c&Oh=%2PblUfuC%7C997048884827569%03xnyJ%2L1pi7irBioQ6D4r7nNHNdo6v7Y%"
       "84aurnSJ%2wCFePHMlGZmIHGfCe7392_lImWsSvN&sBeNN=Nf%80yOE%6X10M64F4gG197aX"
       "R2B4g2533x235A0i4e%57%58uWB%04Erw.60&VMS4=Ek_%02GC0Pkx%6Ov_%207WICUz007%"
       "04nYX8N%46zzpv%999h&KGmBt988y=q4P57C-Dh-Nz-x_7-5oPxz%1gz3N03t6c7-R67N4DT"
       "Y6-f98W1&Lts&%02dOty%8eEYEnLz4yexQQLnL4MGU2JFn3OcmXcatBcabZgBdDdy67hdgW"
       "tYn4");
   for (size_t i = 0; i < iters; ++i) {
     Uri u(s);
     u.getQueryParams();
   }
 }
int main (int argc, char ** argv)
Definition at line 85 of file UriBenchmark.cpp.
References folly::init(), and folly::runBenchmarks().
{
   folly::init(&argc, &argv);
   folly::runBenchmarks();
   return 0;
 }