proxygen: proxygen/folly/folly/test/UTF8StringTest.cpp File Reference
UTF8StringTest.cpp File Reference
#include <folly/UTF8String.h>
#include <folly/Range.h>
#include <folly/portability/GTest.h>
#include <folly/test/TestUtils.h>
Functions
TEST (UTF8StringPiece, valid_utf8)
TEST (UTF8StringPiece, valid_suffix)
TEST (UTF8StringPiece, empty_mid_codepoint)
TEST (UTF8StringPiece, invalid_mid_codepoint)
TEST (UTF8StringPiece, valid_implicit_conversion)
Variables
const folly::StringPiece kTestUTF8 = u8"This is \U0001F602 stuff!"
Function Documentation
TEST (UTF8StringPiece , valid_utf8)
Definition at line 28 of file UTF8StringTest.cpp.
References EXPECT_EQ, and kTestUTF8.
{
   folly::StringPiece sp = kTestUTF8;
   UTF8StringPiece utf8 = sp;
   // utf8.size() not available since it's not a random-access range
   EXPECT_EQ(16, utf8.walk_size());
 }
TEST (UTF8StringPiece , valid_suffix)
Definition at line 35 of file UTF8StringTest.cpp.
References EXPECT_EQ, and folly::Range< Iter >::subpiece().
{
   UTF8StringPiece utf8 = kTestUTF8.subpiece(8);
   EXPECT_EQ(8, utf8.walk_size());
 }
TEST (UTF8StringPiece , empty_mid_codepoint)
Definition at line 40 of file UTF8StringTest.cpp.
References EXPECT_EQ, and folly::Range< Iter >::subpiece().
{
   UTF8StringPiece utf8 = kTestUTF8.subpiece(9, 0); // okay since it's empty
   EXPECT_EQ(0, utf8.walk_size());
 }
TEST (UTF8StringPiece , invalid_mid_codepoint)
Definition at line 45 of file UTF8StringTest.cpp.
References EXPECT_THROW, and folly::Range< Iter >::subpiece().
{
   EXPECT_THROW(UTF8StringPiece(kTestUTF8.subpiece(9, 1)), std::out_of_range);
 }
TEST (UTF8StringPiece , valid_implicit_conversion)
Definition at line 49 of file UTF8StringTest.cpp.
References EXPECT_EQ, and string.
{
   std::string input = u8"\U0001F602\U0001F602\U0001F602";
   auto checkImplicitCtor = [](UTF8StringPiece implicitCtor) {
     return implicitCtor.walk_size();
   };
   EXPECT_EQ(3, checkImplicitCtor(input));
 }
Variable Documentation
const folly::StringPiece kTestUTF8 = u8"This is \U0001F602 stuff!"
Definition at line 26 of file UTF8StringTest.cpp.
Referenced by TEST().