proxygen: proxygen/folly/folly/test/UtilityTest.cpp File Reference
UtilityTest.cpp File Reference
#include <type_traits>
#include <folly/Utility.h>
#include <folly/portability/GTest.h>
Functions
TEST_F (UtilityTest, copy)
TEST_F (UtilityTest, copy_noexcept_spec)
TEST_F (UtilityTest, as_const)
template<typename T >
static T & as_mutable (T const &t)
TEST_F (UtilityTest, forward_like)
TEST_F (UtilityTest, exchange)
TEST (FollyIntegerSequence, core)
TEST_F (UtilityTest, MoveOnly)
TEST_F (UtilityTest, to_signed)
TEST_F (UtilityTest, to_unsigned)
Function Documentation
template<typename T > static T& as_mutable (T const & t) static
Definition at line 81 of file UtilityTest.cpp.
References folly::pushmi::detail::t, and T.
Referenced by TEST_F().
{
   return const_cast<T&>(t);
 }
TEST (FollyIntegerSequence , core)
Definition at line 100 of file UtilityTest.cpp.
References folly::apply(), EXPECT_EQ, EXPECT_TRUE, folly::gen::seq(), folly::integer_sequence< T, Ints >::size(), and value.
{
   constexpr auto seq = folly::integer_sequence<int, 0, 3, 2>();
   static_assert(seq.size() == 3, "");
   EXPECT_EQ(3, seq.size());
   auto seq2 = folly::index_sequence<0, 4, 3>();
   EXPECT_EQ(3, seq2.size());
   constexpr auto seq3 = folly::make_index_sequence<3>();
   static_assert(seq3.size() == 3, "");
   EXPECT_EQ(3, seq3.size());
   // check our own implementation even when the builtin is available
   using seq4 = typename folly::utility_detail::make_seq<5>::template apply<
       folly::integer_sequence<int>,
       folly::integer_sequence<int, 0>>;
   EXPECT_EQ(5, seq4{}.size());
   EXPECT_TRUE((std::is_same<seq4::value_type, int>::value));
   using seq4_expected = folly::integer_sequence<int, 0, 1, 2, 3, 4>;
   EXPECT_TRUE((std::is_same<seq4, seq4_expected>::value));
 }
TEST_F (UtilityTest , copy)
Definition at line 27 of file UtilityTest.cpp.
References folly::copy(), data, EXPECT_EQ, and folly::gen::move.
{
   struct MyData {};
   struct Worker {
     size_t rrefs = 0, crefs = 0;
     void something(MyData&&) {
       ++rrefs;
     }
     void something(const MyData&) {
       ++crefs;
     }
   };
   MyData data;
   Worker worker;
   worker.something(folly::copy(data));
   worker.something(std::move(data));
   worker.something(data);
   EXPECT_EQ(2, worker.rrefs);
   EXPECT_EQ(1, worker.crefs);
 }
TEST_F (UtilityTest , copy_noexcept_spec)
Definition at line 48 of file UtilityTest.cpp.
References folly::copy(), EXPECT_FALSE, EXPECT_TRUE, folly::gen::move, and folly::pushmi::__adl::noexcept().
{
   struct MyNoexceptCopyable {};
   MyNoexceptCopyable noe;
   EXPECT_TRUE(noexcept(folly::copy(noe)));
   EXPECT_TRUE(noexcept(folly::copy(std::move(noe))));
   struct MyThrowingCopyable {
     MyThrowingCopyable() {}
     MyThrowingCopyable(const MyThrowingCopyable&) noexcept(false) {}
     MyThrowingCopyable(MyThrowingCopyable&&) = default;
   };
   MyThrowingCopyable thr;
   EXPECT_FALSE(noexcept(folly::copy(thr)));
   EXPECT_TRUE(noexcept(folly::copy(std::move(thr)))); // note: does not copy
 }
TEST_F (UtilityTest , as_const)
Definition at line 64 of file UtilityTest.cpp.
References folly::as_const(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, folly::gen::member(), folly::pushmi::__adl::noexcept(), and s.
{
   struct S {
     bool member() {
       return false;
     }
     bool member() const {
       return true;
     }
   };
   S s;
   EXPECT_FALSE(s.member());
   EXPECT_TRUE(folly::as_const(s).member());
   EXPECT_EQ(&s, &folly::as_const(s));
   EXPECT_TRUE(noexcept(folly::as_const(s)));
 }
TEST_F (UtilityTest , forward_like)
Definition at line 85 of file UtilityTest.cpp.
References as_mutable(), and EXPECT_EQ.
{
   int x = 0;
   // just show that it may be invoked, and that it is purely a cast
   // the real work is done by like_t, in terms of which forward_like is defined
   EXPECT_EQ(&x, std::addressof(folly::forward_like<char&>(x)));
   EXPECT_EQ(&x, std::addressof(as_mutable(folly::forward_like<char const>(x))));
 }
TEST_F (UtilityTest , exchange)
Definition at line 93 of file UtilityTest.cpp.
References folly::exchange(), and EXPECT_EQ.
{
   auto obj = std::map<std::string, int>{{"hello", 3}};
   auto old = exchange(obj, {{"world", 4}});
   EXPECT_EQ((std::map<std::string, int>{{"world", 4}}), obj);
   EXPECT_EQ((std::map<std::string, int>{{"hello", 3}}), old);
 }
TEST_F (UtilityTest , MoveOnly)
Definition at line 122 of file UtilityTest.cpp.
References a, folly::gen::move, and value.
{
   class FooBar : folly::MoveOnly {
     int a;
   };
   static_assert(
       !std::is_copy_constructible<FooBar>::value,
       "Should not be copy constructible");
   // Test that move actually works.
   FooBar foobar;
   FooBar foobar2(std::move(foobar));
   (void)foobar2;
   // Test that inheriting from MoveOnly doesn't prevent the move
   // constructor from being noexcept.
   static_assert(
       std::is_nothrow_move_constructible<FooBar>::value,
       "Should have noexcept move constructor");
 }
TEST_F (UtilityTest , to_signed)
Definition at line 143 of file UtilityTest.cpp.
References EXPECT_EQ, EXPECT_TRUE, int32_t, folly::to_signed(), uint32_t, and value.
{
   {
     constexpr auto actual = folly::to_signed(int32_t(-12));
     EXPECT_TRUE(std::is_signed<decltype(actual)>::value);
     EXPECT_EQ(-12, actual);
   }
   {
     constexpr auto actual = folly::to_signed(uint32_t(-12));
     EXPECT_TRUE(std::is_signed<decltype(actual)>::value);
     EXPECT_EQ(-12, actual);
   }
 }
TEST_F (UtilityTest , to_unsigned)
Definition at line 156 of file UtilityTest.cpp.
References EXPECT_EQ, EXPECT_TRUE, int32_t, folly::to_unsigned(), uint32_t, and value.
{
   {
     constexpr auto actual = folly::to_unsigned(int32_t(-12));
     EXPECT_TRUE(!std::is_signed<decltype(actual)>::value);
     EXPECT_EQ(-12, actual);
   }
   {
     constexpr auto actual = folly::to_unsigned(uint32_t(-12));
     EXPECT_TRUE(!std::is_signed<decltype(actual)>::value);
     EXPECT_EQ(-12, actual);
   }
 }