proxygen: proxygen/folly/folly/test/VarintTest.cpp File Reference
VarintTest.cpp File Reference
#include <folly/Varint.h>
#include <array>
#include <initializer_list>
#include <random>
#include <vector>
#include <glog/logging.h>
#include <folly/Benchmark.h>
#include <folly/Random.h>
#include <folly/portability/GTest.h>
Namespaces
folly
—— Concurrent Priority Queue Implementation ——
folly::test
Functions
DEFINE_int32 (random_seed, folly::randomNumberSeed(),"random seed")
void folly::test::testVarint (uint64_t val, std::initializer_list< uint8_t > bytes)
folly::test::TEST (Varint, Interface)
folly::test::TEST (Varint, Simple)
void folly::test::testVarintFail (std::initializer_list< uint8_t > bytes)
folly::test::TEST (Varint, Fail)
folly::test::TEST (ZigZag, Simple)
int main (int argc, char *argv[])
Function Documentation
DEFINE_int32 (random_seed , folly::randomNumberSeed() , "random seed")
int main (int argc, char * argv[])
Definition at line 203 of file VarintTest.cpp.
References testing::InitGoogleTest(), RUN_ALL_TESTS(), and folly::runBenchmarksOnFlag().
{
   testing::InitGoogleTest(&argc, argv);
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   google::InitGoogleLogging(argv[0]);
   int ret = RUN_ALL_TESTS();
   if (ret == 0) {
     folly::test::generateRandomValues();
     folly::runBenchmarksOnFlag();
   }
   return ret;
 }