proxygen: proxygen/wangle/_build/gtest/src/gtest/googletest/test/gtest-unittest-api_test.cc File Reference
gtest-unittest-api_test.cc File Reference
#include "gtest/gtest.h"
#include <string.h>
#include <algorithm>
Classes
struct testing::internal::LessByName< T >
class testing::internal::UnitTestHelper
class testing::internal::FinalSuccessChecker
Namespaces
testing
testing::internal
Functions
testing::internal::TEST (ApiTest, UnitTestImmutableAccessorsWork)
AssertionResult testing::internal::IsNull (const char *str)
testing::internal::TEST (ApiTest, TestCaseImmutableAccessorsWork)
testing::internal::TEST (ApiTest, TestCaseDisabledAccessorsWork)
testing::internal::TEST (ApiTest, DISABLED_Dummy1)
testing::internal::TEST (DISABLED_Test, Dummy2)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 335 of file gtest-unittest-api_test.cc.
References testing::AddGlobalTestEnvironment(), testing::InitGoogleTest(), and RUN_ALL_TESTS().
{
   InitGoogleTest(&argc, argv);
   AddGlobalTestEnvironment(new testing::internal::FinalSuccessChecker());
   return RUN_ALL_TESTS();
 }