proxygen: proxygen/wangle/_build/gtest/src/gtest/googletest/test/gtest_pred_impl_unittest.cc File Reference
gtest_pred_impl_unittest.cc File Reference
#include <iostream>
#include "gtest/gtest.h"
#include "gtest/gtest-spi.h"
Classes
struct Bool
struct PredFunctor1
struct PredFormatFunctor1
class Predicate1Test
struct PredFunctor2
struct PredFormatFunctor2
class Predicate2Test
struct PredFunctor3
struct PredFormatFunctor3
class Predicate3Test
struct PredFunctor4
struct PredFormatFunctor4
class Predicate4Test
struct PredFunctor5
struct PredFormatFunctor5
class Predicate5Test
Typedefs
typedef Predicate1Test EXPECT_PRED_FORMAT1Test
typedef Predicate1Test ASSERT_PRED_FORMAT1Test
typedef Predicate1Test EXPECT_PRED1Test
typedef Predicate1Test ASSERT_PRED1Test
typedef Predicate2Test EXPECT_PRED_FORMAT2Test
typedef Predicate2Test ASSERT_PRED_FORMAT2Test
typedef Predicate2Test EXPECT_PRED2Test
typedef Predicate2Test ASSERT_PRED2Test
typedef Predicate3Test EXPECT_PRED_FORMAT3Test
typedef Predicate3Test ASSERT_PRED_FORMAT3Test
typedef Predicate3Test EXPECT_PRED3Test
typedef Predicate3Test ASSERT_PRED3Test
typedef Predicate4Test EXPECT_PRED_FORMAT4Test
typedef Predicate4Test ASSERT_PRED_FORMAT4Test
typedef Predicate4Test EXPECT_PRED4Test
typedef Predicate4Test ASSERT_PRED4Test
typedef Predicate5Test EXPECT_PRED_FORMAT5Test
typedef Predicate5Test ASSERT_PRED_FORMAT5Test
typedef Predicate5Test EXPECT_PRED5Test
typedef Predicate5Test ASSERT_PRED5Test
Functions
std::ostream & operator<< (std::ostream &os, const Bool &x)
template<typename T1 >
bool PredFunction1 (T1 v1)
bool PredFunction1Int (int v1)
bool PredFunction1Bool (Bool v1)
template<typename T1 >
testing::AssertionResult PredFormatFunction1 (const char *e1, const T1 &v1)
TEST_F (EXPECT_PRED1Test, FunctionOnBuiltInTypeSuccess)
TEST_F (EXPECT_PRED1Test, FunctionOnUserTypeSuccess)
TEST_F (EXPECT_PRED1Test, FunctorOnBuiltInTypeSuccess)
TEST_F (EXPECT_PRED1Test, FunctorOnUserTypeSuccess)
TEST_F (EXPECT_PRED1Test, FunctionOnBuiltInTypeFailure)
TEST_F (EXPECT_PRED1Test, FunctionOnUserTypeFailure)
TEST_F (EXPECT_PRED1Test, FunctorOnBuiltInTypeFailure)
TEST_F (EXPECT_PRED1Test, FunctorOnUserTypeFailure)
template<typename T1 , typename T2 >
bool PredFunction2 (T1 v1, T2 v2)
bool PredFunction2Int (int v1, int v2)
bool PredFunction2Bool (Bool v1, Bool v2)
template<typename T1 , typename T2 >
testing::AssertionResult PredFormatFunction2 (const char *e1, const char *e2, const T1 &v1, const T2 &v2)
TEST_F (EXPECT_PRED2Test, FunctionOnBuiltInTypeSuccess)
TEST_F (EXPECT_PRED2Test, FunctionOnUserTypeSuccess)
TEST_F (EXPECT_PRED2Test, FunctorOnBuiltInTypeSuccess)
TEST_F (EXPECT_PRED2Test, FunctorOnUserTypeSuccess)
TEST_F (EXPECT_PRED2Test, FunctionOnBuiltInTypeFailure)
TEST_F (EXPECT_PRED2Test, FunctionOnUserTypeFailure)
TEST_F (EXPECT_PRED2Test, FunctorOnBuiltInTypeFailure)
TEST_F (EXPECT_PRED2Test, FunctorOnUserTypeFailure)
template<typename T1 , typename T2 , typename T3 >
bool PredFunction3 (T1 v1, T2 v2, T3 v3)
bool PredFunction3Int (int v1, int v2, int v3)
bool PredFunction3Bool (Bool v1, Bool v2, Bool v3)
template<typename T1 , typename T2 , typename T3 >
testing::AssertionResult PredFormatFunction3 (const char *e1, const char *e2, const char *e3, const T1 &v1, const T2 &v2, const T3 &v3)
TEST_F (EXPECT_PRED3Test, FunctionOnBuiltInTypeSuccess)
TEST_F (EXPECT_PRED3Test, FunctionOnUserTypeSuccess)
TEST_F (EXPECT_PRED3Test, FunctorOnBuiltInTypeSuccess)
TEST_F (EXPECT_PRED3Test, FunctorOnUserTypeSuccess)
TEST_F (EXPECT_PRED3Test, FunctionOnBuiltInTypeFailure)
TEST_F (EXPECT_PRED3Test, FunctionOnUserTypeFailure)
TEST_F (EXPECT_PRED3Test, FunctorOnBuiltInTypeFailure)
TEST_F (EXPECT_PRED3Test, FunctorOnUserTypeFailure)
template<typename T1 , typename T2 , typename T3 , typename T4 >
bool PredFunction4 (T1 v1, T2 v2, T3 v3, T4 v4)
bool PredFunction4Int (int v1, int v2, int v3, int v4)
bool PredFunction4Bool (Bool v1, Bool v2, Bool v3, Bool v4)
template<typename T1 , typename T2 , typename T3 , typename T4 >
testing::AssertionResult PredFormatFunction4 (const char *e1, const char *e2, const char *e3, const char *e4, const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4)
TEST_F (EXPECT_PRED4Test, FunctionOnBuiltInTypeSuccess)
TEST_F (EXPECT_PRED4Test, FunctionOnUserTypeSuccess)
TEST_F (EXPECT_PRED4Test, FunctorOnBuiltInTypeSuccess)
TEST_F (EXPECT_PRED4Test, FunctorOnUserTypeSuccess)
TEST_F (EXPECT_PRED4Test, FunctionOnBuiltInTypeFailure)
TEST_F (EXPECT_PRED4Test, FunctionOnUserTypeFailure)
TEST_F (EXPECT_PRED4Test, FunctorOnBuiltInTypeFailure)
TEST_F (EXPECT_PRED4Test, FunctorOnUserTypeFailure)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
bool PredFunction5 (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5)
bool PredFunction5Int (int v1, int v2, int v3, int v4, int v5)
bool PredFunction5Bool (Bool v1, Bool v2, Bool v3, Bool v4, Bool v5)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
testing::AssertionResult PredFormatFunction5 (const char *e1, const char *e2, const char *e3, const char *e4, const char *e5, const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4, const T5 &v5)
TEST_F (EXPECT_PRED5Test, FunctionOnBuiltInTypeSuccess)
TEST_F (EXPECT_PRED5Test, FunctionOnUserTypeSuccess)
TEST_F (EXPECT_PRED5Test, FunctorOnBuiltInTypeSuccess)
TEST_F (EXPECT_PRED5Test, FunctorOnUserTypeSuccess)
TEST_F (EXPECT_PRED5Test, FunctionOnBuiltInTypeFailure)
TEST_F (EXPECT_PRED5Test, FunctionOnUserTypeFailure)
TEST_F (EXPECT_PRED5Test, FunctorOnBuiltInTypeFailure)
TEST_F (EXPECT_PRED5Test, FunctorOnUserTypeFailure)
Typedef Documentation
typedef Predicate1Test ASSERT_PRED1Test
Definition at line 163 of file gtest_pred_impl_unittest.cc.
typedef Predicate2Test ASSERT_PRED2Test
Definition at line 560 of file gtest_pred_impl_unittest.cc.
typedef Predicate3Test ASSERT_PRED3Test
Definition at line 999 of file gtest_pred_impl_unittest.cc.
typedef Predicate4Test ASSERT_PRED4Test
Definition at line 1480 of file gtest_pred_impl_unittest.cc.
typedef Predicate5Test ASSERT_PRED5Test
Definition at line 2003 of file gtest_pred_impl_unittest.cc.
typedef Predicate1Test ASSERT_PRED_FORMAT1Test
Definition at line 161 of file gtest_pred_impl_unittest.cc.
typedef Predicate2Test ASSERT_PRED_FORMAT2Test
Definition at line 558 of file gtest_pred_impl_unittest.cc.
typedef Predicate3Test ASSERT_PRED_FORMAT3Test
Definition at line 997 of file gtest_pred_impl_unittest.cc.
typedef Predicate4Test ASSERT_PRED_FORMAT4Test
Definition at line 1478 of file gtest_pred_impl_unittest.cc.
typedef Predicate5Test ASSERT_PRED_FORMAT5Test
Definition at line 2001 of file gtest_pred_impl_unittest.cc.
typedef Predicate1Test EXPECT_PRED1Test
Definition at line 162 of file gtest_pred_impl_unittest.cc.
typedef Predicate2Test EXPECT_PRED2Test
Definition at line 559 of file gtest_pred_impl_unittest.cc.
typedef Predicate3Test EXPECT_PRED3Test
Definition at line 998 of file gtest_pred_impl_unittest.cc.
typedef Predicate4Test EXPECT_PRED4Test
Definition at line 1479 of file gtest_pred_impl_unittest.cc.
typedef Predicate5Test EXPECT_PRED5Test
Definition at line 2002 of file gtest_pred_impl_unittest.cc.
typedef Predicate1Test EXPECT_PRED_FORMAT1Test
Definition at line 160 of file gtest_pred_impl_unittest.cc.
typedef Predicate2Test EXPECT_PRED_FORMAT2Test
Definition at line 557 of file gtest_pred_impl_unittest.cc.
typedef Predicate3Test EXPECT_PRED_FORMAT3Test
Definition at line 996 of file gtest_pred_impl_unittest.cc.
typedef Predicate4Test EXPECT_PRED_FORMAT4Test
Definition at line 1477 of file gtest_pred_impl_unittest.cc.
typedef Predicate5Test EXPECT_PRED_FORMAT5Test
Definition at line 2000 of file gtest_pred_impl_unittest.cc.
Function Documentation
std::ostream& operator<< (std::ostream & os, const Bool & x)
Definition at line 69 of file gtest_pred_impl_unittest.cc.
References Bool::value.
{
   return os << (x.value ? "true" : "false");
 }
template<typename T1 > testing::AssertionResult PredFormatFunction1 (const char * e1, const T1 & v1)
Definition at line 101 of file gtest_pred_impl_unittest.cc.
References testing::AssertionFailure(), testing::AssertionSuccess(), and PredFunction1().
{
   if (PredFunction1(v1))
     return testing::AssertionSuccess();
   return testing::AssertionFailure()
       << e1
       << " is expected to be positive, but evaluates to "
       << v1 << ".";
 }
template<typename T1 , typename T2 > testing::AssertionResult PredFormatFunction2 (const char * e1, const char * e2, const T1 & v1, const T2 & v2)
Definition at line 489 of file gtest_pred_impl_unittest.cc.
References testing::AssertionFailure(), testing::AssertionSuccess(), and PredFunction2().
{
   if (PredFunction2(v1, v2))
     return testing::AssertionSuccess();
   return testing::AssertionFailure()
       << e1 << " + " << e2
       << " is expected to be positive, but evaluates to "
       << v1 + v2 << ".";
 }
template<typename T1 , typename T2 , typename T3 > testing::AssertionResult PredFormatFunction3 (const char * e1, const char * e2, const char * e3, const T1 & v1, const T2 & v2, const T3 & v3)
Definition at line 919 of file gtest_pred_impl_unittest.cc.
References testing::AssertionFailure(), testing::AssertionSuccess(), and PredFunction3().
{
   if (PredFunction3(v1, v2, v3))
     return testing::AssertionSuccess();
   return testing::AssertionFailure()
       << e1 << " + " << e2 << " + " << e3
       << " is expected to be positive, but evaluates to "
       << v1 + v2 + v3 << ".";
 }
template<typename T1 , typename T2 , typename T3 , typename T4 > testing::AssertionResult PredFormatFunction4 (const char * e1, const char * e2, const char * e3, const char * e4, const T1 & v1, const T2 & v2, const T3 & v3, const T4 & v4)
Definition at line 1391 of file gtest_pred_impl_unittest.cc.
References testing::AssertionFailure(), testing::AssertionSuccess(), and PredFunction4().
{
   if (PredFunction4(v1, v2, v3, v4))
     return testing::AssertionSuccess();
   return testing::AssertionFailure()
       << e1 << " + " << e2 << " + " << e3 << " + " << e4
       << " is expected to be positive, but evaluates to "
       << v1 + v2 + v3 + v4 << ".";
 }
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > testing::AssertionResult PredFormatFunction5 (const char * e1, const char * e2, const char * e3, const char * e4, const char * e5, const T1 & v1, const T2 & v2, const T3 & v3, const T4 & v4, const T5 & v5)
Definition at line 1905 of file gtest_pred_impl_unittest.cc.
References testing::AssertionFailure(), testing::AssertionSuccess(), and PredFunction5().
{
   if (PredFunction5(v1, v2, v3, v4, v5))
     return testing::AssertionSuccess();
   return testing::AssertionFailure()
       << e1 << " + " << e2 << " + " << e3 << " + " << e4 << " + " << e5
       << " is expected to be positive, but evaluates to "
       << v1 + v2 + v3 + v4 + v5 << ".";
 }
template<typename T1 > bool PredFunction1 (T1 v1)
Definition at line 77 of file gtest_pred_impl_unittest.cc.
{
   return v1 > 0;
 }
bool PredFunction1Bool (Bool v1)
Definition at line 87 of file gtest_pred_impl_unittest.cc.
{
   return v1 > 0;
 }
bool PredFunction1Int (int v1)
Definition at line 84 of file gtest_pred_impl_unittest.cc.
{
   return v1 > 0;
 }
template<typename T1 , typename T2 > bool PredFunction2 (T1 v1, T2 v2)
Definition at line 464 of file gtest_pred_impl_unittest.cc.
{
   return v1 + v2 > 0;
 }
bool PredFunction2Bool (Bool v1, Bool v2)
Definition at line 474 of file gtest_pred_impl_unittest.cc.
{
   return v1 + v2 > 0;
 }
bool PredFunction2Int (int v1, int v2)
Definition at line 471 of file gtest_pred_impl_unittest.cc.
{
   return v1 + v2 > 0;
 }
template<typename T1 , typename T2 , typename T3 > bool PredFunction3 (T1 v1, T2 v2, T3 v3)
Definition at line 893 of file gtest_pred_impl_unittest.cc.
{
   return v1 + v2 + v3 > 0;
 }
bool PredFunction3Bool (Bool v1, Bool v2, Bool v3)
Definition at line 903 of file gtest_pred_impl_unittest.cc.
{
   return v1 + v2 + v3 > 0;
 }
bool PredFunction3Int (int v1, int v2, int v3)
Definition at line 900 of file gtest_pred_impl_unittest.cc.
{
   return v1 + v2 + v3 > 0;
 }
template<typename T1 , typename T2 , typename T3 , typename T4 > bool PredFunction4 (T1 v1, T2 v2, T3 v3, T4 v4)
Definition at line 1364 of file gtest_pred_impl_unittest.cc.
{
   return v1 + v2 + v3 + v4 > 0;
 }
bool PredFunction4Bool (Bool v1, Bool v2, Bool v3, Bool v4)
Definition at line 1374 of file gtest_pred_impl_unittest.cc.
{
   return v1 + v2 + v3 + v4 > 0;
 }
bool PredFunction4Int (int v1, int v2, int v3, int v4)
Definition at line 1371 of file gtest_pred_impl_unittest.cc.
{
   return v1 + v2 + v3 + v4 > 0;
 }
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > bool PredFunction5 (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5)
Definition at line 1877 of file gtest_pred_impl_unittest.cc.
{
   return v1 + v2 + v3 + v4 + v5 > 0;
 }
bool PredFunction5Bool (Bool v1, Bool v2, Bool v3, Bool v4, Bool v5)
Definition at line 1887 of file gtest_pred_impl_unittest.cc.
{
   return v1 + v2 + v3 + v4 + v5 > 0;
 }
bool PredFunction5Int (int v1, int v2, int v3, int v4, int v5)
Definition at line 1884 of file gtest_pred_impl_unittest.cc.
{
   return v1 + v2 + v3 + v4 + v5 > 0;
 }
TEST_F (EXPECT_PRED1Test , FunctionOnBuiltInTypeSuccess)
Definition at line 167 of file gtest_pred_impl_unittest.cc.
References EXPECT_PRED1, and PredFunction1Int().
{
   EXPECT_PRED1(PredFunction1Int,
                ++n1_);
   finished_ = true;
 }
TEST_F (EXPECT_PRED1Test , FunctionOnUserTypeSuccess)
Definition at line 175 of file gtest_pred_impl_unittest.cc.
References Bool::Bool(), EXPECT_PRED1, and PredFunction1Bool().
{
   EXPECT_PRED1(PredFunction1Bool,
                Bool(++n1_));
   finished_ = true;
 }
TEST_F (EXPECT_PRED1Test , FunctorOnBuiltInTypeSuccess)
Definition at line 183 of file gtest_pred_impl_unittest.cc.
References EXPECT_PRED1.
{
   EXPECT_PRED1(PredFunctor1(),
                ++n1_);
   finished_ = true;
 }
TEST_F (EXPECT_PRED1Test , FunctorOnUserTypeSuccess)
Definition at line 191 of file gtest_pred_impl_unittest.cc.
References Bool::Bool(), and EXPECT_PRED1.
{
   EXPECT_PRED1(PredFunctor1(),
                Bool(++n1_));
   finished_ = true;
 }
TEST_F (EXPECT_PRED1Test , FunctionOnBuiltInTypeFailure)
Definition at line 199 of file gtest_pred_impl_unittest.cc.
References EXPECT_NONFATAL_FAILURE, EXPECT_PRED1, and PredFunction1Int().
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED1(PredFunction1Int,
                  n1_++);
     finished_ = true;
   }, "");
 }
TEST_F (EXPECT_PRED1Test , FunctionOnUserTypeFailure)
Definition at line 209 of file gtest_pred_impl_unittest.cc.
References Bool::Bool(), EXPECT_NONFATAL_FAILURE, EXPECT_PRED1, and PredFunction1Bool().
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED1(PredFunction1Bool,
                  Bool(n1_++));
     finished_ = true;
   }, "");
 }
TEST_F (EXPECT_PRED1Test , FunctorOnBuiltInTypeFailure)
Definition at line 219 of file gtest_pred_impl_unittest.cc.
References EXPECT_NONFATAL_FAILURE, and EXPECT_PRED1.
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED1(PredFunctor1(),
                  n1_++);
     finished_ = true;
   }, "");
 }
TEST_F (EXPECT_PRED1Test , FunctorOnUserTypeFailure)
Definition at line 229 of file gtest_pred_impl_unittest.cc.
References ASSERT_PRED1, ASSERT_PRED_FORMAT1, Bool::Bool(), EXPECT_FATAL_FAILURE, EXPECT_NONFATAL_FAILURE, EXPECT_PRED1, EXPECT_PRED_FORMAT1, PredFormatFunction1(), PredFunction1Bool(), PredFunction1Int(), and TEST_F().
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED1(PredFunctor1(),
                  Bool(n1_++));
     finished_ = true;
   }, "");
 }
TEST_F (EXPECT_PRED2Test , FunctionOnBuiltInTypeSuccess)
Definition at line 564 of file gtest_pred_impl_unittest.cc.
References EXPECT_PRED2, and PredFunction2Int().
{
   EXPECT_PRED2(PredFunction2Int,
                ++n1_,
                ++n2_);
   finished_ = true;
 }
TEST_F (EXPECT_PRED2Test , FunctionOnUserTypeSuccess)
Definition at line 573 of file gtest_pred_impl_unittest.cc.
References Bool::Bool(), EXPECT_PRED2, and PredFunction2Bool().
{
   EXPECT_PRED2(PredFunction2Bool,
                Bool(++n1_),
                Bool(++n2_));
   finished_ = true;
 }
TEST_F (EXPECT_PRED2Test , FunctorOnBuiltInTypeSuccess)
Definition at line 582 of file gtest_pred_impl_unittest.cc.
References EXPECT_PRED2.
{
   EXPECT_PRED2(PredFunctor2(),
                ++n1_,
                ++n2_);
   finished_ = true;
 }
TEST_F (EXPECT_PRED2Test , FunctorOnUserTypeSuccess)
Definition at line 591 of file gtest_pred_impl_unittest.cc.
References Bool::Bool(), and EXPECT_PRED2.
{
   EXPECT_PRED2(PredFunctor2(),
                Bool(++n1_),
                Bool(++n2_));
   finished_ = true;
 }
TEST_F (EXPECT_PRED2Test , FunctionOnBuiltInTypeFailure)
Definition at line 600 of file gtest_pred_impl_unittest.cc.
References EXPECT_NONFATAL_FAILURE, EXPECT_PRED2, and PredFunction2Int().
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED2(PredFunction2Int,
                  n1_++,
                  n2_++);
     finished_ = true;
   }, "");
 }
TEST_F (EXPECT_PRED2Test , FunctionOnUserTypeFailure)
Definition at line 611 of file gtest_pred_impl_unittest.cc.
References Bool::Bool(), EXPECT_NONFATAL_FAILURE, EXPECT_PRED2, and PredFunction2Bool().
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED2(PredFunction2Bool,
                  Bool(n1_++),
                  Bool(n2_++));
     finished_ = true;
   }, "");
 }
TEST_F (EXPECT_PRED2Test , FunctorOnBuiltInTypeFailure)
Definition at line 622 of file gtest_pred_impl_unittest.cc.
References EXPECT_NONFATAL_FAILURE, and EXPECT_PRED2.
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED2(PredFunctor2(),
                  n1_++,
                  n2_++);
     finished_ = true;
   }, "");
 }
TEST_F (EXPECT_PRED2Test , FunctorOnUserTypeFailure)
Definition at line 633 of file gtest_pred_impl_unittest.cc.
References ASSERT_PRED2, ASSERT_PRED_FORMAT2, Bool::Bool(), EXPECT_FATAL_FAILURE, EXPECT_NONFATAL_FAILURE, EXPECT_PRED2, EXPECT_PRED_FORMAT2, PredFormatFunction2(), PredFunction2Bool(), PredFunction2Int(), and TEST_F().
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED2(PredFunctor2(),
                  Bool(n1_++),
                  Bool(n2_++));
     finished_ = true;
   }, "");
 }
TEST_F (EXPECT_PRED3Test , FunctionOnBuiltInTypeSuccess)
Definition at line 1003 of file gtest_pred_impl_unittest.cc.
References EXPECT_PRED3, and PredFunction3Int().
{
   EXPECT_PRED3(PredFunction3Int,
                ++n1_,
                ++n2_,
                ++n3_);
   finished_ = true;
 }
TEST_F (EXPECT_PRED3Test , FunctionOnUserTypeSuccess)
Definition at line 1013 of file gtest_pred_impl_unittest.cc.
References Bool::Bool(), EXPECT_PRED3, and PredFunction3Bool().
{
   EXPECT_PRED3(PredFunction3Bool,
                Bool(++n1_),
                Bool(++n2_),
                Bool(++n3_));
   finished_ = true;
 }
TEST_F (EXPECT_PRED3Test , FunctorOnBuiltInTypeSuccess)
Definition at line 1023 of file gtest_pred_impl_unittest.cc.
References EXPECT_PRED3.
{
   EXPECT_PRED3(PredFunctor3(),
                ++n1_,
                ++n2_,
                ++n3_);
   finished_ = true;
 }
TEST_F (EXPECT_PRED3Test , FunctorOnUserTypeSuccess)
Definition at line 1033 of file gtest_pred_impl_unittest.cc.
References Bool::Bool(), and EXPECT_PRED3.
{
   EXPECT_PRED3(PredFunctor3(),
                Bool(++n1_),
                Bool(++n2_),
                Bool(++n3_));
   finished_ = true;
 }
TEST_F (EXPECT_PRED3Test , FunctionOnBuiltInTypeFailure)
Definition at line 1043 of file gtest_pred_impl_unittest.cc.
References EXPECT_NONFATAL_FAILURE, EXPECT_PRED3, and PredFunction3Int().
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED3(PredFunction3Int,
                  n1_++,
                  n2_++,
                  n3_++);
     finished_ = true;
   }, "");
 }
TEST_F (EXPECT_PRED3Test , FunctionOnUserTypeFailure)
Definition at line 1055 of file gtest_pred_impl_unittest.cc.
References Bool::Bool(), EXPECT_NONFATAL_FAILURE, EXPECT_PRED3, and PredFunction3Bool().
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED3(PredFunction3Bool,
                  Bool(n1_++),
                  Bool(n2_++),
                  Bool(n3_++));
     finished_ = true;
   }, "");
 }
TEST_F (EXPECT_PRED3Test , FunctorOnBuiltInTypeFailure)
Definition at line 1067 of file gtest_pred_impl_unittest.cc.
References EXPECT_NONFATAL_FAILURE, and EXPECT_PRED3.
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED3(PredFunctor3(),
                  n1_++,
                  n2_++,
                  n3_++);
     finished_ = true;
   }, "");
 }
TEST_F (EXPECT_PRED3Test , FunctorOnUserTypeFailure)
Definition at line 1079 of file gtest_pred_impl_unittest.cc.
References ASSERT_PRED3, ASSERT_PRED_FORMAT3, Bool::Bool(), EXPECT_FATAL_FAILURE, EXPECT_NONFATAL_FAILURE, EXPECT_PRED3, EXPECT_PRED_FORMAT3, PredFormatFunction3(), PredFunction3Bool(), PredFunction3Int(), and TEST_F().
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED3(PredFunctor3(),
                  Bool(n1_++),
                  Bool(n2_++),
                  Bool(n3_++));
     finished_ = true;
   }, "");
 }
TEST_F (EXPECT_PRED4Test , FunctionOnBuiltInTypeSuccess)
Definition at line 1484 of file gtest_pred_impl_unittest.cc.
References EXPECT_PRED4, and PredFunction4Int().
{
   EXPECT_PRED4(PredFunction4Int,
                ++n1_,
                ++n2_,
                ++n3_,
                ++n4_);
   finished_ = true;
 }
TEST_F (EXPECT_PRED4Test , FunctionOnUserTypeSuccess)
Definition at line 1495 of file gtest_pred_impl_unittest.cc.
References Bool::Bool(), EXPECT_PRED4, and PredFunction4Bool().
{
   EXPECT_PRED4(PredFunction4Bool,
                Bool(++n1_),
                Bool(++n2_),
                Bool(++n3_),
                Bool(++n4_));
   finished_ = true;
 }
TEST_F (EXPECT_PRED4Test , FunctorOnBuiltInTypeSuccess)
Definition at line 1506 of file gtest_pred_impl_unittest.cc.
References EXPECT_PRED4.
{
   EXPECT_PRED4(PredFunctor4(),
                ++n1_,
                ++n2_,
                ++n3_,
                ++n4_);
   finished_ = true;
 }
TEST_F (EXPECT_PRED4Test , FunctorOnUserTypeSuccess)
Definition at line 1517 of file gtest_pred_impl_unittest.cc.
References Bool::Bool(), and EXPECT_PRED4.
{
   EXPECT_PRED4(PredFunctor4(),
                Bool(++n1_),
                Bool(++n2_),
                Bool(++n3_),
                Bool(++n4_));
   finished_ = true;
 }
TEST_F (EXPECT_PRED4Test , FunctionOnBuiltInTypeFailure)
Definition at line 1528 of file gtest_pred_impl_unittest.cc.
References EXPECT_NONFATAL_FAILURE, EXPECT_PRED4, and PredFunction4Int().
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED4(PredFunction4Int,
                  n1_++,
                  n2_++,
                  n3_++,
                  n4_++);
     finished_ = true;
   }, "");
 }
TEST_F (EXPECT_PRED4Test , FunctionOnUserTypeFailure)
Definition at line 1541 of file gtest_pred_impl_unittest.cc.
References Bool::Bool(), EXPECT_NONFATAL_FAILURE, EXPECT_PRED4, and PredFunction4Bool().
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED4(PredFunction4Bool,
                  Bool(n1_++),
                  Bool(n2_++),
                  Bool(n3_++),
                  Bool(n4_++));
     finished_ = true;
   }, "");
 }
TEST_F (EXPECT_PRED4Test , FunctorOnBuiltInTypeFailure)
Definition at line 1554 of file gtest_pred_impl_unittest.cc.
References EXPECT_NONFATAL_FAILURE, and EXPECT_PRED4.
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED4(PredFunctor4(),
                  n1_++,
                  n2_++,
                  n3_++,
                  n4_++);
     finished_ = true;
   }, "");
 }
TEST_F (EXPECT_PRED4Test , FunctorOnUserTypeFailure)
Definition at line 1567 of file gtest_pred_impl_unittest.cc.
References ASSERT_PRED4, ASSERT_PRED_FORMAT4, Bool::Bool(), EXPECT_FATAL_FAILURE, EXPECT_NONFATAL_FAILURE, EXPECT_PRED4, EXPECT_PRED_FORMAT4, PredFormatFunction4(), PredFunction4Bool(), PredFunction4Int(), and TEST_F().
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED4(PredFunctor4(),
                  Bool(n1_++),
                  Bool(n2_++),
                  Bool(n3_++),
                  Bool(n4_++));
     finished_ = true;
   }, "");
 }
TEST_F (EXPECT_PRED5Test , FunctionOnBuiltInTypeSuccess)
Definition at line 2007 of file gtest_pred_impl_unittest.cc.
References EXPECT_PRED5, and PredFunction5Int().
{
   EXPECT_PRED5(PredFunction5Int,
                ++n1_,
                ++n2_,
                ++n3_,
                ++n4_,
                ++n5_);
   finished_ = true;
 }
TEST_F (EXPECT_PRED5Test , FunctionOnUserTypeSuccess)
Definition at line 2019 of file gtest_pred_impl_unittest.cc.
References Bool::Bool(), EXPECT_PRED5, and PredFunction5Bool().
{
   EXPECT_PRED5(PredFunction5Bool,
                Bool(++n1_),
                Bool(++n2_),
                Bool(++n3_),
                Bool(++n4_),
                Bool(++n5_));
   finished_ = true;
 }
TEST_F (EXPECT_PRED5Test , FunctorOnBuiltInTypeSuccess)
Definition at line 2031 of file gtest_pred_impl_unittest.cc.
References EXPECT_PRED5.
{
   EXPECT_PRED5(PredFunctor5(),
                ++n1_,
                ++n2_,
                ++n3_,
                ++n4_,
                ++n5_);
   finished_ = true;
 }
TEST_F (EXPECT_PRED5Test , FunctorOnUserTypeSuccess)
Definition at line 2043 of file gtest_pred_impl_unittest.cc.
References Bool::Bool(), and EXPECT_PRED5.
{
   EXPECT_PRED5(PredFunctor5(),
                Bool(++n1_),
                Bool(++n2_),
                Bool(++n3_),
                Bool(++n4_),
                Bool(++n5_));
   finished_ = true;
 }
TEST_F (EXPECT_PRED5Test , FunctionOnBuiltInTypeFailure)
Definition at line 2055 of file gtest_pred_impl_unittest.cc.
References EXPECT_NONFATAL_FAILURE, EXPECT_PRED5, and PredFunction5Int().
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED5(PredFunction5Int,
                  n1_++,
                  n2_++,
                  n3_++,
                  n4_++,
                  n5_++);
     finished_ = true;
   }, "");
 }
TEST_F (EXPECT_PRED5Test , FunctionOnUserTypeFailure)
Definition at line 2069 of file gtest_pred_impl_unittest.cc.
References Bool::Bool(), EXPECT_NONFATAL_FAILURE, EXPECT_PRED5, and PredFunction5Bool().
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED5(PredFunction5Bool,
                  Bool(n1_++),
                  Bool(n2_++),
                  Bool(n3_++),
                  Bool(n4_++),
                  Bool(n5_++));
     finished_ = true;
   }, "");
 }
TEST_F (EXPECT_PRED5Test , FunctorOnBuiltInTypeFailure)
Definition at line 2083 of file gtest_pred_impl_unittest.cc.
References EXPECT_NONFATAL_FAILURE, and EXPECT_PRED5.
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED5(PredFunctor5(),
                  n1_++,
                  n2_++,
                  n3_++,
                  n4_++,
                  n5_++);
     finished_ = true;
   }, "");
 }
TEST_F (EXPECT_PRED5Test , FunctorOnUserTypeFailure)
Definition at line 2097 of file gtest_pred_impl_unittest.cc.
References ASSERT_PRED5, ASSERT_PRED_FORMAT5, Bool::Bool(), EXPECT_FATAL_FAILURE, EXPECT_NONFATAL_FAILURE, EXPECT_PRED5, EXPECT_PRED_FORMAT5, PredFormatFunction5(), PredFunction5Bool(), PredFunction5Int(), and TEST_F().
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED5(PredFunctor5(),
                  Bool(n1_++),
                  Bool(n2_++),
                  Bool(n3_++),
                  Bool(n4_++),
                  Bool(n5_++));
     finished_ = true;
   }, "");
 }