proxygen: proxygen/folly/folly/io/async/test/ZeroCopyBenchmark.cpp File Reference
ZeroCopyBenchmark.cpp File Reference
#include <folly/Benchmark.h>
#include <folly/io/async/test/ZeroCopy.h>
#include <folly/portability/GFlags.h>
Functions
void zeroCopyOn (unsigned iters, size_t bufferSize, size_t numClients=1)
void zeroCopyOff (unsigned iters, size_t bufferSize, size_t numClients=1)
void zeroCopyOnMulti (unsigned iters, size_t bufferSize)
void zeroCopyOffMulti (unsigned iters, size_t bufferSize)
BENCHMARK_DRAW_LINE ()
DEFINE_bool (client, false,"client mode")
DEFINE_bool (server, false,"server mode")
DEFINE_bool (zeroCopy, false,"use zerocopy")
DEFINE_int32 (numLoops, kMaxLoops,"number of loops")
DEFINE_int32 (bufferSize, 524288,"buffer size")
DEFINE_int32 (port, 33130,"port")
DEFINE_string (host,"::1","host")
int main (int argc, char **argv)
Variables
static auto constexpr kMaxLoops = 20000
static auto constexpr kNumClients = 40
Function Documentation
BENCHMARK_DRAW_LINE ()
DEFINE_bool (client , false , "client mode")
Referenced by zeroCopyOffMulti().
DEFINE_bool (server , false , "server mode")
DEFINE_bool (zeroCopy , false , "use zerocopy")
DEFINE_int32 (numLoops , kMaxLoops , "number of loops")
Referenced by zeroCopyOffMulti().
DEFINE_int32 (bufferSize , 524288 , "buffer size")
DEFINE_int32 (port , 33130 , "port")
DEFINE_string (host , "::1" , "host")
Referenced by zeroCopyOffMulti().
int main (int argc, char ** argv)
Definition at line 132 of file ZeroCopyBenchmark.cpp.
References folly::runBenchmarks().
{
   gflags::ParseCommandLineFlags(&argc, &argv, true);
   if (FLAGS_client) {
     runClient(
         FLAGS_host,
         FLAGS_port,
         FLAGS_numLoops,
         FLAGS_zeroCopy,
         FLAGS_bufferSize);
   } else if (FLAGS_server) {
     runServer(FLAGS_port, FLAGS_numLoops, FLAGS_zeroCopy, FLAGS_bufferSize);
   } else {
     runBenchmarks();
   }
 }
void zeroCopyOff (unsigned iters, size_t bufferSize, size_t numClients = 1)
Definition at line 75 of file ZeroCopyBenchmark.cpp.
References folly::BenchmarkSuspender::dismiss(), folly::BenchmarkSuspender::rehire(), folly::ZeroCopyTest::run(), and test().
Referenced by zeroCopyOffMulti().
{
   BenchmarkSuspender susp;
   ZeroCopyTest test(numClients, iters, false, bufferSize);
   susp.dismiss();
   test.run();
   susp.rehire();
 }
void zeroCopyOffMulti (unsigned iters, size_t bufferSize)
Definition at line 89 of file ZeroCopyBenchmark.cpp.
References folly::BENCHMARK_DRAW_LINE(), BENCHMARK_PARAM, DEFINE_bool(), DEFINE_int32(), DEFINE_string(), zeroCopyOff(), zeroCopyOn(), and zeroCopyOnMulti().
{
   zeroCopyOff(iters, bufferSize, kNumClients);
 }
void zeroCopyOn (unsigned iters, size_t bufferSize, size_t numClients = 1)
Definition at line 67 of file ZeroCopyBenchmark.cpp.
References folly::BenchmarkSuspender::dismiss(), folly::BenchmarkSuspender::rehire(), folly::ZeroCopyTest::run(), and test().
Referenced by zeroCopyOffMulti(), and zeroCopyOnMulti().
{
   BenchmarkSuspender susp;
   ZeroCopyTest test(numClients, iters, true, bufferSize);
   susp.dismiss();
   test.run();
   susp.rehire();
 }
void zeroCopyOnMulti (unsigned iters, size_t bufferSize)
Definition at line 85 of file ZeroCopyBenchmark.cpp.
References zeroCopyOn().
Referenced by zeroCopyOffMulti().
{
   zeroCopyOn(iters, bufferSize, kNumClients);
 }
Variable Documentation
auto constexpr kMaxLoops = 20000 static
Definition at line 65 of file ZeroCopyBenchmark.cpp.
auto constexpr kNumClients = 40 static
Definition at line 83 of file ZeroCopyBenchmark.cpp.