proxygen: proxygen/lib/utils/test/ZlibTests.cpp File Reference
ZlibTests.cpp File Reference
#include <folly/Random.h>
#include <folly/ScopeGuard.h>
#include <folly/io/Cursor.h>
#include <folly/io/IOBuf.h>
#include <folly/portability/GTest.h>
#include <glog/logging.h>
#include <proxygen/lib/utils/ZlibStreamCompressor.h>
#include <proxygen/lib/utils/ZlibStreamDecompressor.h>
Classes
class ZlibTests
Functions
std::unique_ptr< folly::IOBuf > makeBuf (uint32_t size)
void verify (ZlibCompressionType type, std::unique_ptr< IOBuf > original, std::unique_ptr< IOBuf > compressed)
void compressThenDecompress (ZlibCompressionType type, int level, unique_ptr< IOBuf > buf)
TEST_F (ZlibTests, CompressDecompressGzip5000)
TEST_F (ZlibTests, CompressDecompressGzip2000)
TEST_F (ZlibTests, CompressDecompressGzip1024)
TEST_F (ZlibTests, CompressDecompressGzip500)
TEST_F (ZlibTests, CompressDecompressGzip50)
TEST_F (ZlibTests, CompressDecompressDeflate)
TEST_F (ZlibTests, CompressDecompressEmpty)
TEST_F (ZlibTests, CompressDecompressChain)
TEST_F (ZlibTests, CompressDecompressStreaming)
TEST_F (ZlibTests, CompressDecompressSmallBuffer)
Function Documentation
void compressThenDecompress (ZlibCompressionType type, int level, unique_ptr< IOBuf > buf)
Definition at line 52 of file ZlibTests.cpp.
References ASSERT_FALSE, proxygen::ZlibStreamCompressor::compress(), proxygen::ZlibStreamCompressor::getStatus(), proxygen::ZlibStreamCompressor::hasError(), folly::gen::move, and verify().
Referenced by TEST_F().
{
   unique_ptr<IOBuf> compressed;
   unique_ptr<IOBuf> decompressed;
   unique_ptr<ZlibStreamCompressor> zc(new ZlibStreamCompressor(type, level));
   compressed = zc->compress(buf.get(), true);
   ASSERT_FALSE(zc->hasError()) << "Compression error. r=" << zc->getStatus();
   verify(type, std::move(buf), std::move(compressed));
 }
std::unique_ptr<folly::IOBuf> makeBuf (uint32_t size)
Definition at line 26 of file ZlibTests.cpp.
References folly::IOBuf::create(), folly::Random::rand32(), folly::Random::rand64(), uint64_t, uint8_t, and folly::io::detail::Writable< Derived >::write().
Referenced by TestPriorityMapBuilder::createVirtualStreams(), HTTP2FramerTest::dataFrameTest(), TestAbortPost< stage >::doAbortTest(), proxygen::fakeMockCodec(), proxygen::makeResponse(), MoveToFbStringTest::SetUp(), TEST_F(), MockCodecDownstreamTest::testConnFlowControlBlocked(), and TYPED_TEST_P().
{
   auto out = folly::IOBuf::create(size);
   out->append(size);
   // fill with random junk
   folly::io::RWPrivateCursor cursor(out.get());
   while (cursor.length() >= 8) {
     cursor.write<uint64_t>(folly::Random::rand64());
   }
   while (cursor.length()) {
     cursor.write<uint8_t>((uint8_t)folly::Random::rand32());
   }
   return out;
 }
TEST_F (ZlibTests , CompressDecompressGzip5000)
Definition at line 68 of file ZlibTests.cpp.
References ASSERT_NO_FATAL_FAILURE, compressThenDecompress(), and makeBuf().
{
   ASSERT_NO_FATAL_FAILURE(
       { compressThenDecompress(ZlibCompressionType::GZIP, 6, makeBuf(5000)); });
 }
TEST_F (ZlibTests , CompressDecompressGzip2000)
Definition at line 73 of file ZlibTests.cpp.
References ASSERT_NO_FATAL_FAILURE, compressThenDecompress(), and makeBuf().
{
   ASSERT_NO_FATAL_FAILURE(
       { compressThenDecompress(ZlibCompressionType::GZIP, 6, makeBuf(2000)); });
 }
TEST_F (ZlibTests , CompressDecompressGzip1024)
Definition at line 78 of file ZlibTests.cpp.
References ASSERT_NO_FATAL_FAILURE, compressThenDecompress(), and makeBuf().
{
   ASSERT_NO_FATAL_FAILURE(
       { compressThenDecompress(ZlibCompressionType::GZIP, 6, makeBuf(1024)); });
 }
TEST_F (ZlibTests , CompressDecompressGzip500)
Definition at line 83 of file ZlibTests.cpp.
References ASSERT_NO_FATAL_FAILURE, compressThenDecompress(), and makeBuf().
{
   ASSERT_NO_FATAL_FAILURE(
       { compressThenDecompress(ZlibCompressionType::GZIP, 6, makeBuf(500)); });
 }
TEST_F (ZlibTests , CompressDecompressGzip50)
Definition at line 88 of file ZlibTests.cpp.
References ASSERT_NO_FATAL_FAILURE, compressThenDecompress(), and makeBuf().
{
   ASSERT_NO_FATAL_FAILURE(
       { compressThenDecompress(ZlibCompressionType::GZIP, 6, makeBuf(50)); });
 }
TEST_F (ZlibTests , CompressDecompressDeflate)
Definition at line 93 of file ZlibTests.cpp.
References ASSERT_NO_FATAL_FAILURE, compressThenDecompress(), and makeBuf().
{
   ASSERT_NO_FATAL_FAILURE({
     compressThenDecompress(ZlibCompressionType::DEFLATE, 6, makeBuf(500));
   });
 }
TEST_F (ZlibTests , CompressDecompressEmpty)
Definition at line 99 of file ZlibTests.cpp.
References ASSERT_NO_FATAL_FAILURE, compressThenDecompress(), and makeBuf().
{
   ASSERT_NO_FATAL_FAILURE(
       { compressThenDecompress(ZlibCompressionType::GZIP, 4, makeBuf(0)); });
 }
TEST_F (ZlibTests , CompressDecompressChain)
Definition at line 104 of file ZlibTests.cpp.
References ASSERT_NO_FATAL_FAILURE, compressThenDecompress(), makeBuf(), and folly::gen::move.
{
   ASSERT_NO_FATAL_FAILURE({
     auto buf = makeBuf(4);
     buf->appendChain(makeBuf(38));
     buf->appendChain(makeBuf(12));
     buf->appendChain(makeBuf(0));
     compressThenDecompress(ZlibCompressionType::GZIP, 6, std::move(buf));
   });
 }
TEST_F (ZlibTests , CompressDecompressStreaming)
Definition at line 114 of file ZlibTests.cpp.
References ASSERT_NO_FATAL_FAILURE, folly::IOBuf::create(), folly::empty(), folly::gen::first, makeBuf(), folly::gen::move, and verify().
{
   ASSERT_NO_FATAL_FAILURE({
     auto compressor =
         std::make_unique<ZlibStreamCompressor>(ZlibCompressionType::GZIP, 6);
     auto first = makeBuf(38);
     auto out = compressor->compress(first.get(), false);
     auto second = makeBuf(12);
     out->prev()->appendChain(compressor->compress(second.get(), false));
     first->prev()->appendChain(std::move(second));
     auto third = makeBuf(4096); // Larger than buffer size
     out->prev()->appendChain(compressor->compress(third.get(), false));
     first->prev()->appendChain(std::move(third));
     auto empty = IOBuf::create(0);
     out->prev()->appendChain(compressor->compress(empty.get(), true));
     verify(ZlibCompressionType::GZIP, std::move(first), std::move(out));
   });
 }
TEST_F (ZlibTests , CompressDecompressSmallBuffer)
Definition at line 137 of file ZlibTests.cpp.
References ASSERT_NO_FATAL_FAILURE, compressThenDecompress(), folly::gen::guard(), makeBuf(), and folly::makeGuard().
{
   ASSERT_NO_FATAL_FAILURE({
     auto oldFlag = FLAGS_zlib_compressor_buffer_growth;
     auto guard = folly::makeGuard([&] {
       FLAGS_zlib_compressor_buffer_growth = oldFlag;
     });
     // NB: This is picked intentionally so we don't generate multiple
     // zlib flush markers as ZlibStreamDecompressor fatals on them.
     FLAGS_zlib_compressor_buffer_growth = 10;
     compressThenDecompress(ZlibCompressionType::GZIP, 4, makeBuf(127));
   });
 }
void verify (ZlibCompressionType type, std::unique_ptr< IOBuf > original, std::unique_ptr< IOBuf > compressed)
Definition at line 40 of file ZlibTests.cpp.
References ASSERT_FALSE, ASSERT_TRUE, folly::eq, and type.
Referenced by compressThenDecompress(), and TEST_F().
{
   auto zd = std::make_unique<ZlibStreamDecompressor>(type);
   auto decompressed = zd->decompress(compressed.get());
   ASSERT_FALSE(zd->hasError()) << "Decompression error. r=" << zd->getStatus();
   IOBufEqualTo eq;
   ASSERT_TRUE(eq(original, decompressed));
 }